Repository aws/aws-cdk, pull requests merged in 2018-11, with the labels that each got.

#1122 docs: Fixed rendering of "API Gateway" in tutorial
  docs/src/tutorial.rst
Labels: 📚 documentation

#1161 docs: Added import statement to clarify using elbv2 in example code
  packages/@aws-cdk/aws-ecs/README.md
Labels: ecs, 📚 documentation

#1045 docs: updated "Getting Started" topic
  docs/src/getting-started.rst
Labels: 📚 documentation

#1205 chore: Add rule to guarantee node runtime compatibility
  package.json
  tools/pkglint/bin/pkglint.ts
  tools/pkglint/lib/packagejson.ts
  tools/pkglint/lib/rules.ts
  tools/pkglint/lib/util.ts
  tools/pkglint/package.json
Labels: enhancement

#1207 chore (docs): Replaced tools text w/output from cdk --help v0.17.0
  docs/src/tools.rst
Labels: 📚 documentation
