Repository aws/aws-cdk, pull requests merged in 2018-12, with the labels that each got.

#1195 feat(docs): Updated examples topic to use ECS L2 construct
  docs/src/examples.rst
Labels: 📚 documentation

#1344 fix(aws-logs): set default log retention of LogGroup to 731 instead of 730 (#1343)
  packages/@aws-cdk/aws-logs/lib/log-group.ts
  packages/@aws-cdk/aws-logs/test/integ.metricfilter.lit.expected.json
  packages/@aws-cdk/aws-logs/test/test.loggroup.ts
Labels: bug, cloudwatch

#1447 feat(cli): Allow specifying options using env vars
  packages/aws-cdk/bin/cdk.ts
  packages/aws-cdk/lib/commands/doctor.ts
Labels: enhancement, 🛠 toolkit
