Repository aws/aws-cdk, pull requests merged in 2018-09, with the labels that each got.

#649 feat(cdk-build-tools): Allow configuring jsii, jsii-pacmak and tsc
  tools/cdk-build-tools/bin/cdk-build.ts
  tools/cdk-build-tools/bin/cdk-package.ts
  tools/cdk-build-tools/bin/cdk-test.ts
  tools/cdk-build-tools/bin/cdk-watch.ts
  tools/cdk-build-tools/lib/compile.ts
  tools/cdk-build-tools/lib/package-info.ts
Labels: enhancement, feature

#670 Added Cloud9 link to landing page
  docs/src/index.rst
Labels: documentation

#698 Added note about version reporting not supported in China regions
  docs/src/getting-started.rst
  docs/src/region-note.rst
  docs/src/tools.rst
Labels: documentation

#700 Added info about passing values into a stack
  docs/src/concepts.rst
  docs/src/passing-in-data.rst
Labels: 📚 documentation

#779 feat(toolkit): Stop creating 'empty' stacks
  packages/aws-cdk/lib/api/deploy-stack.ts
Labels: enhancement

#783 fix(docs): fix issue #718 (Aurora DB example)
  docs/src/examples.rst
Labels: bug, 📚 documentation
