Repository aws/aws-cdk, pull requests merged in 2019-09, with the labels that each got.

#3890 chore(iam): migrate unit tests to Jest
  packages/@aws-cdk/aws-iam/package-lock.json
  packages/@aws-cdk/aws-iam/package.json
  packages/@aws-cdk/aws-iam/test/auto-cross-stack-refs.test.ts
  packages/@aws-cdk/aws-iam/test/escape-hatch.test.ts
  packages/@aws-cdk/aws-iam/test/grant.test.ts
  packages/@aws-cdk/aws-iam/test/group.test.ts
  packages/@aws-cdk/aws-iam/test/lazy-role.test.ts
  packages/@aws-cdk/aws-iam/test/managed-policy.test.ts
  packages/@aws-cdk/aws-iam/test/policy-document.test.ts
  packages/@aws-cdk/aws-iam/test/policy.test.ts
  packages/@aws-cdk/aws-iam/test/role.test.ts
  packages/@aws-cdk/aws-iam/test/test.grant.ts
  packages/@aws-cdk/aws-iam/test/user.test.ts
Labels: automerge-enabled

#3865 feat(init-templates): add typesRoot compiler option for typescript templates in the tsconfig.json
  packages/aws-cdk/lib/init-templates/app/typescript/tsconfig.json
  packages/aws-cdk/lib/init-templates/lib/typescript/tsconfig.json
  packages/aws-cdk/lib/init-templates/sample-app/javascript/tsconfig.json
  packages/aws-cdk/lib/init-templates/sample-app/typescript/tsconfig.json
Labels: automerge-enabled

#3885 docs(readme): remove same version badge
  README.md
Labels: automerge-enabled

#3874 chore: upgrade to use jsii 0.16.0 & typescript 3.6.2
  package-lock.json
  package.json
  packages/@aws-cdk/aws-dynamodb/test/test.dynamodb.ts
  packages/aws-cdk/lib/init-templates/app/typescript/package.template.json
  packages/aws-cdk/lib/init-templates/lib/typescript/package.template.json
  packages/aws-cdk/lib/init-templates/sample-app/typescript/package.template.json
  packages/decdk/package-lock.json
  packages/decdk/package.json
  tools/awslint/package-lock.json
  tools/awslint/package.json
  tools/cdk-build-tools/package-lock.json
  tools/cdk-build-tools/package.json
Labels: automerge-enabled

#3902 chore(docs): Section on connecting VS Code debugger
  CONTRIBUTING.md
Labels: automerge-enabled

#3833 feat(ecs,lambda,rds): specify allowAllOutbound when importing security groups
  packages/@aws-cdk/aws-ecs/lib/cluster.ts
  packages/@aws-cdk/aws-ecs/test/test.ecs-cluster.ts
  packages/@aws-cdk/aws-elasticloadbalancingv2/lib/alb/application-listener.ts
  packages/@aws-cdk/aws-elasticloadbalancingv2/test/alb/test.listener.ts
  packages/@aws-cdk/aws-lambda/lib/function-base.ts
  packages/@aws-cdk/aws-lambda/lib/function.ts
  packages/@aws-cdk/aws-lambda/test/test.lambda.ts
  packages/@aws-cdk/aws-rds/lib/cluster-ref.ts
  packages/@aws-cdk/aws-rds/lib/cluster.ts
  packages/@aws-cdk/aws-rds/lib/instance.ts
  packages/@aws-cdk/aws-rds/test/test.cluster.ts
  packages/@aws-cdk/aws-rds/test/test.instance.ts
Labels: automerge-enabled

#3811 feat(events): validate MessageGroupId is specified only for FIFO queues
  packages/@aws-cdk/aws-events-targets/lib/sqs.ts
  packages/@aws-cdk/aws-events-targets/test/sqs/sqs.test.ts
  packages/@aws-cdk/aws-sqs/lib/queue-base.ts
  packages/@aws-cdk/aws-sqs/lib/queue.ts
  packages/@aws-cdk/aws-sqs/test/test.sqs.ts
Labels: automerge-enabled

#3826 chore: stability report tool
  scripts/stability-report.sh
  scripts/stability.js
Labels: automerge-enabled

#3887 fix(ecs): default ecsmanagedtags and propagatetags to be undefined
  packages/@aws-cdk/aws-codepipeline-actions/test/integ.pipeline-ecs-deploy.expected.json
  packages/@aws-cdk/aws-ecs-patterns/test/fargate/integ.asset-image.expected.json
  packages/@aws-cdk/aws-ecs-patterns/test/fargate/integ.executionrole.expected.json
  packages/@aws-cdk/aws-ecs-patterns/test/fargate/integ.l3-autocreate.expected.json
  packages/@aws-cdk/aws-ecs-patterns/test/fargate/integ.l3-vpconly.expected.json
  packages/@aws-cdk/aws-ecs-patterns/test/fargate/integ.l3.expected.json
  packages/@aws-cdk/aws-ecs/lib/base/base-service.ts
  packages/@aws-cdk/aws-ecs/lib/ec2/ec2-service.ts
  packages/@aws-cdk/aws-ecs/lib/fargate/fargate-service.ts
  packages/@aws-cdk/aws-ecs/test/ec2/integ.lb-awsvpc-nw.expected.json
  packages/@aws-cdk/aws-ecs/test/ec2/integ.lb-bridge-nw.expected.json
  packages/@aws-cdk/aws-ecs/test/ec2/integ.sd-awsvpc-nw.expected.json
  packages/@aws-cdk/aws-ecs/test/ec2/integ.sd-bridge-nw.expected.json
  packages/@aws-cdk/aws-ecs/test/ec2/test.ec2-service.ts
  packages/@aws-cdk/aws-ecs/test/fargate/integ.lb-awsvpc-nw.expected.json
  packages/@aws-cdk/aws-ecs/test/fargate/test.fargate-service.ts
  packages/decdk/test/__snapshots__/synth.test.js.snap
Labels: automerge-enabled

#3942 feat: upgrade to CloudFormation specification 6.0.0
  packages/@aws-cdk/aws-autoscaling/test/integ.amazonlinux2.expected.json
  packages/@aws-cdk/aws-autoscaling/test/integ.asg-w-classic-loadbalancer.expected.json
  packages/@aws-cdk/aws-autoscaling/test/integ.asg-w-elbv2.expected.json
  packages/@aws-cdk/aws-autoscaling/test/integ.custom-scaling.expected.json
  packages/@aws-cdk/aws-autoscaling/test/integ.spot-instances.expected.json
  packages/@aws-cdk/aws-autoscaling/test/test.auto-scaling-group.ts
  packages/@aws-cdk/aws-codedeploy/test/server/integ.deployment-group.expected.json
  packages/@aws-cdk/aws-ec2/test/integ.bastion-host.expected.json
  packages/@aws-cdk/aws-ec2/test/integ.instance.expected.json
  packages/@aws-cdk/aws-ecs-patterns/test/ec2/integ.scheduled-ecs-task.lit.expected.json
  packages/@aws-cdk/aws-ecs/test/ec2/integ.lb-awsvpc-nw.expected.json
  packages/@aws-cdk/aws-ecs/test/ec2/integ.lb-bridge-nw.expected.json
  packages/@aws-cdk/aws-ecs/test/ec2/integ.sd-awsvpc-nw.expected.json
  packages/@aws-cdk/aws-ecs/test/ec2/integ.sd-bridge-nw.expected.json
  packages/@aws-cdk/aws-eks/test/integ.eks-cluster.defaults.expected.json
  packages/@aws-cdk/aws-eks/test/integ.eks-cluster.kubectl-disabled.expected.json
  packages/@aws-cdk/aws-eks/test/integ.eks-cluster.lit.expected.json
  packages/@aws-cdk/aws-eks/test/integ.eks-kubectl.lit.expected.json
  packages/@aws-cdk/aws-events-targets/test/ecs/integ.event-ec2-task.lit.expected.json
  packages/@aws-cdk/aws-stepfunctions-tasks/test/integ.ec2-task.expected.json
  packages/@aws-cdk/cfnspec/CHANGELOG.md
  packages/@aws-cdk/cfnspec/spec-source/000_CloudFormationResourceSpecification.json
Labels: automerge-enabled

#3932 chore(jsii): update to version 0.16
  packages/@aws-cdk/aws-cloudfront/package-lock.json
  packages/@aws-cdk/aws-cloudtrail/package-lock.json
  packages/@aws-cdk/aws-codebuild/package-lock.json
  packages/@aws-cdk/aws-codecommit/package-lock.json
  packages/@aws-cdk/aws-codepipeline-actions/package-lock.json
  packages/@aws-cdk/aws-iam/package-lock.json
  packages/@aws-cdk/aws-route53/package-lock.json
  packages/@aws-cdk/aws-sqs/package-lock.json
  packages/@aws-cdk/core/package-lock.json
  packages/aws-cdk/package-lock.json
  packages/decdk/package-lock.json
  packages/decdk/package.json
  packages/decdk/test/fixture/tsconfig.json
  tools/awslint/package-lock.json
  tools/cdk-build-tools/package-lock.json
  tools/cdk-integ-tools/package-lock.json
  tools/cfn2ts/package-lock.json
  tools/pkgtools/package-lock.json
Labels: automerge-enabled

#3955 chore(apigateway): fix typo
  packages/@aws-cdk/aws-apigateway/lib/domain-name.ts
Labels: automerge-enabled

#3966 chore: bump year in root LICENSE
  LICENSE
Labels: automerge-enabled

#3914 fix(certificatemanager): increase minimum validation total timeout
  packages/@aws-cdk/aws-certificatemanager/lambda-packages/dns_validated_certificate_handler/lib/index.js
  packages/@aws-cdk/aws-certificatemanager/lambda-packages/dns_validated_certificate_handler/test/handler.test.js
Labels: automerge-enabled

#3964 chore(repo): remove depbot autolabel
  .dependabot/config.yml
Labels: automerge-enabled

#3956 chore(docs): Fixup the VS code debugging section for accuracy
  CONTRIBUTING.md
Labels: automerge-enabled

#3716 fix(iam): only create policies for imported roles if they're in the same account as the owning stack
  packages/@aws-cdk/aws-iam/lib/role.ts
  packages/@aws-cdk/aws-iam/package.json
  packages/@aws-cdk/aws-iam/test/role.from-role-arn.test.ts
  packages/@aws-cdk/aws-iam/test/role.test.ts
Labels: automerge-enabled

#3978 chore(comments) Fix typo on a gitattributes comment
  .gitattributes
Labels: automerge-enabled

#3950 feat(eks): add EKS AMis for 1.14
  packages/@aws-cdk/aws-eks/lib/ami.ts
Labels: automerge-enabled

#3937 feat(eks): spot capacity and bootstrap options
  packages/@aws-cdk/aws-autoscaling/lib/auto-scaling-group.ts
  packages/@aws-cdk/aws-autoscaling/test/test.auto-scaling-group.ts
  packages/@aws-cdk/aws-eks/README.md
  packages/@aws-cdk/aws-eks/lib/cluster.ts
  packages/@aws-cdk/aws-eks/lib/instance-data.ts
  packages/@aws-cdk/aws-eks/lib/spot-interrupt-handler.ts
  packages/@aws-cdk/aws-eks/lib/user-data.ts
  packages/@aws-cdk/aws-eks/scripts/.gitignore
  packages/@aws-cdk/aws-eks/scripts/update-instance-data.js
  packages/@aws-cdk/aws-eks/test/integ.eks-cluster.defaults.expected.json
  packages/@aws-cdk/aws-eks/test/integ.eks-cluster.defaults.ts
  packages/@aws-cdk/aws-eks/test/integ.eks-cluster.kubectl-disabled.expected.json
  packages/@aws-cdk/aws-eks/test/integ.eks-cluster.kubectl-disabled.ts
  packages/@aws-cdk/aws-eks/test/integ.eks-cluster.lit.expected.json
  packages/@aws-cdk/aws-eks/test/integ.eks-cluster.lit.ts
  packages/@aws-cdk/aws-eks/test/integ.eks-kubectl.lit.expected.json
  packages/@aws-cdk/aws-eks/test/integ.eks-kubectl.lit.ts
  packages/@aws-cdk/aws-eks/test/integ.eks-spot.expected.json
  packages/@aws-cdk/aws-eks/test/integ.eks-spot.ts
  packages/@aws-cdk/aws-eks/test/test.cluster.ts
  packages/@aws-cdk/aws-eks/test/test.user-data.ts
  packages/@aws-cdk/aws-eks/test/util.ts
Labels: automerge-enabled

#3935 fix(dynamodb): prevent "StreamARN not found for resource" errors
  allowed-breaking-changes.txt
  packages/@aws-cdk/aws-dynamodb/lib/table.ts
  packages/@aws-cdk/aws-dynamodb/test/test.dynamodb.ts
  packages/@aws-cdk/aws-lambda-event-sources/lib/dynamodb.ts
  packages/@aws-cdk/aws-lambda-event-sources/test/test.dynamo.ts
Labels: automerge-enabled

#3972 feat(cli): rebuild .net project on cdk synth
  packages/aws-cdk/lib/init-templates/sample-app/csharp/cdk.template.json
  packages/aws-cdk/lib/init-templates/sample-app/csharp/src/%name.PascalCased%/%name.PascalCased%Construct.template.cs
Labels: automerge-enabled

#3947 chore(repo): re-add generalized issue template
  .github/ISSUE_TEMPLATE.md
Labels: automerge-enabled

#3992 chore(rds): fix README.md
  packages/@aws-cdk/aws-rds/README.md
Labels: automerge-enabled

#3986 fix(app-delivery): action template filename incorrect
  packages/@aws-cdk/app-delivery/lib/pipeline-deploy-stack-action.ts
  packages/@aws-cdk/app-delivery/test/integ.cicd.expected.json
Labels: automerge-enabled

#3989 feat(ecr-assets): fail if tokens are used in buildArgs
  packages/@aws-cdk/aws-ecr-assets/lib/image-asset.ts
  packages/@aws-cdk/aws-ecr-assets/test/test.image-asset.ts
Labels: automerge-enabled

#3990 build(travis): remove source modification check
  .travis.yml
Labels: automerge-enabled

#3991 chore: set default_labels to an empty array
  .dependabot/config.yml
Labels: automerge-enabled

#3699 feat(ec2): add networkacl related resources
  packages/@aws-cdk/assert/lib/assertions/match-template.ts
  packages/@aws-cdk/aws-ec2/lib/index.ts
  packages/@aws-cdk/aws-ec2/lib/network-acl-types.ts
  packages/@aws-cdk/aws-ec2/lib/network-acl.ts
  packages/@aws-cdk/aws-ec2/lib/vpc.ts
  packages/@aws-cdk/aws-ec2/test/integ.vpc-networkacl.expected.json
  packages/@aws-cdk/aws-ec2/test/integ.vpc-networkacl.ts
  packages/@aws-cdk/aws-ec2/test/test.vpc.ts
  packages/@aws-cdk/cloudformation-diff/lib/diff/types.ts
Labels: automerge-enabled, do-not-merge

#3995 chore(cli-tests): added assertion for conditional-resource stack
  packages/aws-cdk/test/integ/cli/test-cdk-ls.sh
Labels: automerge-enabled

#3916 fix(events): `fromObject` handles regular and field tokens together
  packages/@aws-cdk/aws-events/lib/input.ts
  packages/@aws-cdk/aws-events/test/test.input.ts
Labels: automerge-enabled, do-not-merge

#4000 fix(custom-resources): correctly handle booleans conversion
  packages/@aws-cdk/custom-resources/lib/aws-custom-resource-provider/index.ts
  packages/@aws-cdk/custom-resources/lib/aws-custom-resource.ts
  packages/@aws-cdk/custom-resources/test/integ.aws-custom-resource.expected.json
  packages/@aws-cdk/custom-resources/test/test.aws-custom-resource-provider.ts
  packages/@aws-cdk/custom-resources/test/test.aws-custom-resource.ts
Labels: automerge-enabled

#3948 feat(cli): added jest tests to typescript templates
  packages/aws-cdk/lib/init-templates/app/typescript/README.md
  packages/aws-cdk/lib/init-templates/app/typescript/jest.config.js
  packages/aws-cdk/lib/init-templates/app/typescript/package.template.json
  packages/aws-cdk/lib/init-templates/app/typescript/test/%name%.test.template.ts
  packages/aws-cdk/lib/init-templates/lib/typescript/README.md
  packages/aws-cdk/lib/init-templates/lib/typescript/jest.config.js
  packages/aws-cdk/lib/init-templates/lib/typescript/package.template.json
  packages/aws-cdk/lib/init-templates/lib/typescript/test/%name%.test.template.ts
  packages/aws-cdk/lib/init-templates/sample-app/typescript/README.md
  packages/aws-cdk/lib/init-templates/sample-app/typescript/jest.config.js
  packages/aws-cdk/lib/init-templates/sample-app/typescript/package.template.json
  packages/aws-cdk/lib/init-templates/sample-app/typescript/test/%name%.test.template.ts
  packages/aws-cdk/test/integ/init/test-typescript.sh
Labels: automerge-enabled

#4003 refactor(assets): remove content hash attribute
  packages/@aws-cdk/assets/lib/api.ts
  packages/@aws-cdk/aws-ecr-assets/lib/image-asset.ts
  packages/@aws-cdk/aws-ecr-assets/test/integ.assets-docker.expected.json
  packages/@aws-cdk/aws-ecr-assets/test/integ.assets-docker.ts
  packages/@aws-cdk/aws-s3-assets/lib/asset.ts
Labels: automerge-enabled

#4006 feat(events): allow passing a role to the CodePipeline target
  packages/@aws-cdk/aws-events-targets/lib/codepipeline.ts
  packages/@aws-cdk/aws-events-targets/test/codepipeline/pipeline.test.ts
Labels: automerge-enabled

#4012 chore(decdk): deps.js adds newline in package.json
  packages/decdk/deps.js
Labels: automerge-enabled

#3694 feat(codepipeline): cross-environment (account+region) actions
  packages/@aws-cdk/aws-codepipeline-actions/test/integ.cfn-template-from-repo.lit.expected.json
  packages/@aws-cdk/aws-codepipeline-actions/test/integ.lambda-deployed-through-codepipeline.lit.expected.json
  packages/@aws-cdk/aws-codepipeline-actions/test/integ.lambda-pipeline.expected.json
  packages/@aws-cdk/aws-codepipeline-actions/test/integ.pipeline-alexa-deploy.expected.json
  packages/@aws-cdk/aws-codepipeline-actions/test/integ.pipeline-cfn.expected.json
  packages/@aws-cdk/aws-codepipeline-actions/test/integ.pipeline-code-commit-build.expected.json
  packages/@aws-cdk/aws-codepipeline-actions/test/integ.pipeline-code-commit.expected.json
  packages/@aws-cdk/aws-codepipeline-actions/test/integ.pipeline-events.expected.json
  packages/@aws-cdk/aws-codepipeline-actions/test/integ.pipeline-s3-deploy.expected.json
  packages/@aws-cdk/aws-codepipeline/README.md
  packages/@aws-cdk/aws-codepipeline/lib/cross-region-support-stack.ts
  packages/@aws-cdk/aws-codepipeline/lib/pipeline.ts
  packages/@aws-cdk/aws-codepipeline/test/fake-build-action.ts
  packages/@aws-cdk/aws-codepipeline/test/test.pipeline.ts
  packages/@aws-cdk/aws-events-targets/test/codepipeline/integ.pipeline-event-target.expected.json
  packages/@aws-cdk/aws-iam/lib/grant.ts
  packages/@aws-cdk/aws-kms/lib/alias.ts
  packages/@aws-cdk/aws-kms/lib/key.ts
  packages/@aws-cdk/aws-kms/test/test.alias.ts
  packages/@aws-cdk/aws-kms/test/test.key.ts
  packages/@aws-cdk/aws-s3/lib/bucket.ts
  packages/@aws-cdk/core/lib/resource.ts
  packages/decdk/test/__snapshots__/synth.test.js.snap
Labels: automerge-enabled, do-not-merge

#4028 fix(aws-codepipeline-actions): Fixing a typo for Amazon.CDK.AWS.CodePipeline.Actions in .NET
  packages/@aws-cdk/aws-codepipeline-actions/package.json
Labels: automerge-enabled

#3997 fix(apigateway): json schema additionalProperties should be boolean
  allowed-breaking-changes.txt
  packages/@aws-cdk/aws-apigateway/lib/json-schema.ts
Labels: automerge-enabled

#3952 fix(events): remove custom resource for fargate event target
  packages/@aws-cdk/aws-ecs-patterns/test/fargate/integ.scheduled-fargate-task.lit.expected.json
  packages/@aws-cdk/aws-ecs-patterns/test/fargate/test.scheduled-fargate-task.ts
  packages/@aws-cdk/aws-events-targets/lib/ecs-task.ts
  packages/@aws-cdk/aws-events-targets/package.json
  packages/@aws-cdk/aws-events-targets/test/ecs/event-rule-target.test.ts
  packages/@aws-cdk/aws-events-targets/test/ecs/integ.event-fargate-task.expected.json
Labels: automerge-enabled

#4037 fix(events): remove policy statement from CF template when using AwsApi
  packages/@aws-cdk/aws-events-targets/lib/aws-api-handler/index.ts
  packages/@aws-cdk/aws-events-targets/lib/aws-api.ts
  packages/@aws-cdk/aws-events-targets/test/aws-api/aws-api.test.ts
Labels: automerge-enabled

#4011 fix(core): `stack.urlSuffix` is no longer scoped
  packages/@aws-cdk/aws-iam/lib/principals.ts
  packages/@aws-cdk/aws-iam/test/principals.test.ts
  packages/@aws-cdk/core/lib/stack.ts
  packages/@aws-cdk/core/test/test.stack.ts
Labels: pr-status/do-not-merge

#3762 feat(ecs): add additional log drivers
  packages/@aws-cdk/aws-ecs/README.md
  packages/@aws-cdk/aws-ecs/lib/index.ts
  packages/@aws-cdk/aws-ecs/lib/log-drivers/aws-log-driver.ts
  packages/@aws-cdk/aws-ecs/lib/log-drivers/base-log-driver.ts
  packages/@aws-cdk/aws-ecs/lib/log-drivers/fluentd-log-driver.ts
  packages/@aws-cdk/aws-ecs/lib/log-drivers/gelf-log-driver.ts
  packages/@aws-cdk/aws-ecs/lib/log-drivers/generic-log-driver.ts
  packages/@aws-cdk/aws-ecs/lib/log-drivers/journald-log-driver.ts
  packages/@aws-cdk/aws-ecs/lib/log-drivers/json-file-log-driver.ts
  packages/@aws-cdk/aws-ecs/lib/log-drivers/log-drivers.ts
  packages/@aws-cdk/aws-ecs/lib/log-drivers/splunk-log-driver.ts
  packages/@aws-cdk/aws-ecs/lib/log-drivers/syslog-log-driver.ts
  packages/@aws-cdk/aws-ecs/lib/log-drivers/utils.ts
  packages/@aws-cdk/aws-ecs/test/test.fluentd-log-driver.ts
  packages/@aws-cdk/aws-ecs/test/test.gelf-log-driver.ts
  packages/@aws-cdk/aws-ecs/test/test.journald-log-driver.ts
  packages/@aws-cdk/aws-ecs/test/test.json-file-log-driver.ts
  packages/@aws-cdk/aws-ecs/test/test.splunk-log-driver.ts
  packages/@aws-cdk/aws-ecs/test/test.syslog-log-driver.ts
Labels: review/large

#4097 chore(mergify): unroll team into members
  .mergify.yml
Labels: effort/small

#4089 fix(ec2): improve errors around subnet selection
  packages/@aws-cdk/aws-ec2/lib/util.ts
  packages/@aws-cdk/aws-ec2/lib/vpc.ts
  packages/@aws-cdk/aws-ec2/test/test.vpc.ts
Labels: pr-status/do-not-merge

#4090 fix(ec2): fix subnet selection on looked-up VPCs
  packages/@aws-cdk/aws-ec2/lib/vpc.ts
  packages/@aws-cdk/aws-ec2/test/test.vpc.ts
Labels: pr-status/do-not-merge

#4111 fix(ecs): fargate on ALB without cyclic dependencies
  packages/@aws-cdk/aws-ecs/lib/base/base-service.ts
  packages/@aws-cdk/aws-elasticloadbalancingv2/lib/alb/application-listener.ts
  packages/@aws-cdk/aws-elasticloadbalancingv2/test/alb/test.security-groups.ts
Labels: pr-status/do-not-merge

#3777 feat(codepipeline): handle non-CFN cross-region actions
  packages/@aws-cdk/aws-codepipeline-actions/test/test.pipeline.ts
  packages/@aws-cdk/aws-codepipeline/lib/cross-region-support-stack.ts
  packages/@aws-cdk/aws-codepipeline/lib/full-action-descriptor.ts
  packages/@aws-cdk/aws-codepipeline/lib/pipeline.ts
  packages/@aws-cdk/aws-codepipeline/test/test.pipeline.ts
Labels: pr-status/do-not-merge

#4107 feat(ecs): allow load balancing to any container and port of service
  packages/@aws-cdk/aws-ecs/README.md
  packages/@aws-cdk/aws-ecs/lib/base/base-service.ts
  packages/@aws-cdk/aws-ecs/lib/base/task-definition.ts
  packages/@aws-cdk/aws-ecs/lib/container-definition.ts
  packages/@aws-cdk/aws-ecs/lib/ec2/ec2-service.ts
  packages/@aws-cdk/aws-ecs/test/ec2/integ.clb-host-nw.expected.json
  packages/@aws-cdk/aws-ecs/test/ec2/integ.clb-host-nw.ts
  packages/@aws-cdk/aws-ecs/test/ec2/test.ec2-service.ts
  packages/@aws-cdk/aws-ecs/test/fargate/test.fargate-service.ts
Labels: pr-status/do-not-merge

#3772 feat(core): context lookup errors are reported to CX app
  packages/@aws-cdk/aws-ec2/lib/vpc.ts
  packages/@aws-cdk/aws-route53/lib/hosted-zone.ts
  packages/@aws-cdk/aws-ssm/lib/parameter.ts
  packages/@aws-cdk/core/lib/context-provider.ts
  packages/@aws-cdk/core/lib/stack.ts
  packages/@aws-cdk/core/test/test.context.ts
  packages/@aws-cdk/core/test/test.synthesis.ts
  packages/@aws-cdk/cx-api/lib/cxapi.ts
  packages/@aws-cdk/cx-api/lib/index.ts
  packages/aws-cdk/lib/api/cxapp/stacks.ts
  packages/aws-cdk/lib/context-providers/index.ts
  packages/aws-cdk/lib/settings.ts
  packages/aws-cdk/test/api/test.stacks.ts
  packages/aws-cdk/test/context-providers/test.generic.ts
  packages/aws-cdk/test/test.assets.ts
  packages/aws-cdk/test/test.context.ts
  packages/aws-cdk/test/test.diff.ts
  packages/aws-cdk/test/util.ts
Labels: effort/medium, pr-status/do-not-merge

#4132 refactor(elbv2): make load balancer targets bind to interfaces
  packages/@aws-cdk/aws-autoscaling/lib/auto-scaling-group.ts
  packages/@aws-cdk/aws-ecs/lib/base/base-service.ts
  packages/@aws-cdk/aws-elasticloadbalancingv2-targets/lib/instance-target.ts
  packages/@aws-cdk/aws-elasticloadbalancingv2-targets/lib/ip-target.ts
  packages/@aws-cdk/aws-elasticloadbalancingv2-targets/lib/lambda-target.ts
  packages/@aws-cdk/aws-elasticloadbalancingv2/lib/alb/application-target-group.ts
  packages/@aws-cdk/aws-elasticloadbalancingv2/lib/nlb/network-target-group.ts
  packages/@aws-cdk/aws-elasticloadbalancingv2/lib/shared/load-balancer-targets.ts
Labels: effort/small, pr-status/do-not-merge

#4235 chore: add backwards compatibility shell scripts
  packages/aws-cdk/test/integ/init/test-csharp-app.sh
  packages/aws-cdk/test/integ/init/test-python-app.sh
  packages/aws-cdk/test/integ/init/test-typescript-app.sh
  packages/aws-cdk/test/integ/init/test-typescript-lib.sh
  packages/aws-cdk/test/integ/init/test-typescript.sh
  packages/aws-cdk/test/integ/run-against-dist
Labels: pr-status/do-not-merge

#4100 feat(ecs-patterns): support `propagateTags` and `ecsManagedTags`
  packages/@aws-cdk/aws-ecs-patterns/lib/base/application-load-balanced-service-base.ts
  packages/@aws-cdk/aws-ecs-patterns/lib/base/network-load-balanced-service-base.ts
  packages/@aws-cdk/aws-ecs-patterns/lib/base/queue-processing-service-base.ts
  packages/@aws-cdk/aws-ecs-patterns/lib/ecs/application-load-balanced-ecs-service.ts
  packages/@aws-cdk/aws-ecs-patterns/lib/ecs/network-load-balanced-ecs-service.ts
  packages/@aws-cdk/aws-ecs-patterns/lib/ecs/queue-processing-ecs-service.ts
  packages/@aws-cdk/aws-ecs-patterns/lib/fargate/application-load-balanced-fargate-service.ts
  packages/@aws-cdk/aws-ecs-patterns/lib/fargate/network-load-balanced-fargate-service.ts
  packages/@aws-cdk/aws-ecs-patterns/lib/fargate/queue-processing-fargate-service.ts
  packages/@aws-cdk/aws-ecs/lib/ec2/ec2-service.ts
  packages/@aws-cdk/aws-ecs/lib/fargate/fargate-service.ts
  packages/@aws-cdk/aws-ecs/test/ec2/test.ec2-service.ts
Labels: pr-status/do-not-merge

#4251 fix(acm): support Tokens for domainName in Certificate
  packages/@aws-cdk/aws-certificatemanager/lib/certificate.ts
  packages/@aws-cdk/aws-certificatemanager/test/test.certificate.ts
Labels: contribution/core, effort/small

#4252 fix(rule): make `ruleName` accessible on `Rule` object
  packages/@aws-cdk/aws-events/lib/rule-ref.ts
  packages/@aws-cdk/aws-events/lib/rule.ts
  packages/@aws-cdk/aws-events/test/test.rule.ts
Labels: contribution/core, effort/small

#4253 fix(cloudwatch): can use percentile override in `Alarm`
  packages/@aws-cdk/aws-cloudwatch/lib/alarm.ts
  packages/@aws-cdk/aws-cloudwatch/test/test.alarm.ts
Labels: contribution/core, effort/small

#4255 fix(ecr-assets): give accurate error when Tokens are being used
  packages/@aws-cdk/aws-ecr-assets/lib/image-asset.ts
  packages/@aws-cdk/aws-ecr-assets/test/test.image-asset.ts
Labels: contribution/core, effort/small

#4270 fix(cloudtrail): fix use of imported bucket with CloudTrail
  packages/@aws-cdk/aws-cloudtrail/lib/index.ts
  packages/@aws-cdk/aws-cloudtrail/test/test.cloudtrail.ts
Labels: effort/small

#4269 chore(ec2): add missing test to Instance
  packages/@aws-cdk/aws-ec2/test/test.instance.ts
Labels: review/small

#4213 feat(ecs-patterns): Add LoadBalancer and TaskDefinition properties
  packages/@aws-cdk/aws-ecs-patterns/lib/base/application-load-balanced-service-base.ts
  packages/@aws-cdk/aws-ecs-patterns/lib/base/network-load-balanced-service-base.ts
  packages/@aws-cdk/aws-ecs-patterns/lib/base/scheduled-task-base.ts
  packages/@aws-cdk/aws-ecs-patterns/lib/ecs/application-load-balanced-ecs-service.ts
  packages/@aws-cdk/aws-ecs-patterns/lib/ecs/network-load-balanced-ecs-service.ts
  packages/@aws-cdk/aws-ecs-patterns/lib/ecs/scheduled-ecs-task.ts
  packages/@aws-cdk/aws-ecs-patterns/lib/fargate/application-load-balanced-fargate-service.ts
  packages/@aws-cdk/aws-ecs-patterns/lib/fargate/network-load-balanced-fargate-service.ts
  packages/@aws-cdk/aws-ecs-patterns/lib/fargate/scheduled-fargate-task.ts
  packages/@aws-cdk/aws-ecs-patterns/test/ec2/integ.scheduled-ecs-task.lit.ts
  packages/@aws-cdk/aws-ecs-patterns/test/ec2/test.l3s.ts
  packages/@aws-cdk/aws-ecs-patterns/test/ec2/test.scheduled-ecs-task.ts
  packages/@aws-cdk/aws-ecs-patterns/test/fargate/integ.asset-image.ts
  packages/@aws-cdk/aws-ecs-patterns/test/fargate/integ.executionrole.ts
  packages/@aws-cdk/aws-ecs-patterns/test/fargate/integ.https-fargate-service.lit.ts
  packages/@aws-cdk/aws-ecs-patterns/test/fargate/integ.l3-autocreate.ts
  packages/@aws-cdk/aws-ecs-patterns/test/fargate/integ.l3-vpconly.ts
  packages/@aws-cdk/aws-ecs-patterns/test/fargate/integ.l3.ts
  packages/@aws-cdk/aws-ecs-patterns/test/fargate/integ.scheduled-fargate-task.lit.ts
  packages/@aws-cdk/aws-ecs-patterns/test/fargate/test.load-balanced-fargate-service.ts
  packages/@aws-cdk/aws-ecs-patterns/test/fargate/test.scheduled-fargate-task.ts
Labels: pr-status/do-not-merge
