Repository aws/aws-cdk, pull requests merged in 2019-10, with the labels that each got.

#4307 fix(cli): make new CLI recognize old assembly versions
  packages/@aws-cdk/cx-api/lib/cloud-assembly.ts
  packages/@aws-cdk/cx-api/lib/cxapi.ts
  packages/@aws-cdk/cx-api/lib/versioning.ts
  packages/@aws-cdk/cx-api/test/cloud-assembly.test.ts
  packages/@aws-cdk/cx-api/test/fixtures/single-stack-0.36/manifest.json
  packages/@aws-cdk/cx-api/test/fixtures/single-stack-0.36/template.json
  packages/aws-cdk/lib/api/cxapp/exec.ts
  packages/aws-cdk/lib/version.ts
Labels: pr-status/do-not-merge

#4318 fix(apigateway): defaultChild on RestApi returns the underlying L1
  packages/@aws-cdk/aws-apigateway/lib/restapi.ts
  packages/@aws-cdk/aws-apigateway/test/test.restapi.ts
  packages/@aws-cdk/core/lib/construct.ts
Labels: contribution/core

#4334 feat(ecs): Add warning message when pulling ECR image
  packages/@aws-cdk/aws-ecs/lib/images/repository.ts
  packages/@aws-cdk/aws-ecs/test/ec2/test.ec2-task-definition.ts
Labels: package/ecs

#4007 feat(ecs): add support for ProxyConfiguration in ECS TaskDefinition
  packages/@aws-cdk/aws-ecs/lib/base/task-definition.ts
  packages/@aws-cdk/aws-ecs/lib/index.ts
  packages/@aws-cdk/aws-ecs/lib/proxy-configuration/app-mesh-proxy-configuration.ts
  packages/@aws-cdk/aws-ecs/lib/proxy-configuration/proxy-configuration.ts
  packages/@aws-cdk/aws-ecs/lib/proxy-configuration/proxy-configurations.ts
  packages/@aws-cdk/aws-ecs/test/ec2/integ.app-mesh-proxy-config.expected.json
  packages/@aws-cdk/aws-ecs/test/ec2/integ.app-mesh-proxy-config.ts
  packages/@aws-cdk/aws-ecs/test/ec2/test.ec2-task-definition.ts
  packages/@aws-cdk/aws-ecs/test/test.app-mesh-proxy-configuration.ts
Labels: package/ecs

#4317 fix(ecs): nat network mode for windows tasks
  packages/@aws-cdk/aws-ecs/lib/base/task-definition.ts
  packages/@aws-cdk/aws-ecs/test/ec2/test.ec2-service.ts
  packages/@aws-cdk/aws-ecs/test/test.container-definition.ts
Labels: package/ecs

#4171 fix(codebuild): validate if a CodePipeline action that is cross-account does not have outputs
  packages/@aws-cdk/aws-codepipeline-actions/lib/codebuild/build-action.ts
  packages/@aws-cdk/aws-codepipeline-actions/test/codebuild/test.codebuild-action.ts
  packages/@aws-cdk/aws-codepipeline-actions/test/test.pipeline.ts
Labels: contribution/core, pr-status/do-not-merge

#4369 feat(ecs-patterns): add CloudMapOptions to load balanced services
  packages/@aws-cdk/aws-ecs-patterns/README.md
  packages/@aws-cdk/aws-ecs-patterns/lib/base/application-load-balanced-service-base.ts
  packages/@aws-cdk/aws-ecs-patterns/lib/base/network-load-balanced-service-base.ts
  packages/@aws-cdk/aws-ecs-patterns/lib/ecs/application-load-balanced-ecs-service.ts
  packages/@aws-cdk/aws-ecs-patterns/lib/ecs/network-load-balanced-ecs-service.ts
  packages/@aws-cdk/aws-ecs-patterns/lib/fargate/application-load-balanced-fargate-service.ts
  packages/@aws-cdk/aws-ecs-patterns/lib/fargate/network-load-balanced-fargate-service.ts
  packages/@aws-cdk/aws-ecs-patterns/package.json
  packages/@aws-cdk/aws-ecs-patterns/test/ec2/test.l3s.ts
Labels: package/ecs-patterns

#2828 feat(rds): add support for monitoring to DatabaseCluster
  packages/@aws-cdk/aws-rds/lib/cluster.ts
  packages/@aws-cdk/aws-rds/lib/instance.ts
  packages/@aws-cdk/aws-rds/test/test.cluster.ts
  packages/@aws-cdk/aws-rds/test/test.instance.ts
Labels: review/small

#4313 fix(cloudmap): fix CloudMap Service import, expose ECS CloudMap Service
  allowed-breaking-changes.txt
  packages/@aws-cdk/app-delivery/lib/pipeline-deploy-stack-action.ts
  packages/@aws-cdk/aws-apigateway/lib/restapi.ts
  packages/@aws-cdk/aws-appmesh/lib/virtual-router.ts
  packages/@aws-cdk/aws-appmesh/test/test.virtual-router.ts
  packages/@aws-cdk/aws-codebuild/lib/project.ts
  packages/@aws-cdk/aws-ecs-patterns/lib/base/application-load-balanced-service-base.ts
  packages/@aws-cdk/aws-ecs/lib/base/base-service.ts
  packages/@aws-cdk/aws-ecs/lib/images/ecr.ts
  packages/@aws-cdk/aws-ecs/lib/log-drivers/generic-log-driver.ts
  packages/@aws-cdk/aws-ecs/test/fargate/test.fargate-service.ts
  packages/@aws-cdk/aws-eks/test/integ.eks-kubectl.lit.ts
  packages/@aws-cdk/aws-elasticloadbalancingv2/test/alb/test.security-groups.ts
  packages/@aws-cdk/aws-servicediscovery/lib/service.ts
  packages/@aws-cdk/aws-stepfunctions-tasks/lib/sagemaker-train-task.ts
Labels: pr-status/do-not-merge

#4145 feat(stepfunctions): add support for Map state
  packages/@aws-cdk/aws-stepfunctions/lib/index.ts
  packages/@aws-cdk/aws-stepfunctions/lib/states/map.ts
  packages/@aws-cdk/aws-stepfunctions/lib/states/private/state-type.ts
  packages/@aws-cdk/aws-stepfunctions/lib/states/state.ts
  packages/@aws-cdk/aws-stepfunctions/test/test.map.ts
  packages/@aws-cdk/aws-stepfunctions/test/test.parallel.ts
Labels: pr-status/do-not-merge

#4212 feat(ecs): add a new API for registering ECS targets
  packages/@aws-cdk/aws-ecs/README.md
  packages/@aws-cdk/aws-ecs/lib/base/base-service.ts
  packages/@aws-cdk/aws-ecs/test/fargate/integ.nlb-awsvpc-nw.expected.json
  packages/@aws-cdk/aws-ecs/test/fargate/integ.nlb-awsvpc-nw.ts
  packages/@aws-cdk/aws-ecs/test/fargate/test.fargate-service.ts
Labels: package/ecs

#4321 feat(ecs-patterns): ecs-patterns library is now stable
  packages/@aws-cdk/aws-ecs-patterns/README.md
  packages/@aws-cdk/aws-ecs-patterns/package.json
Labels: package/ecs-patterns

#4280 fix(elbv2): Do not allow invalid healthcheck intervals (#4279)
  packages/@aws-cdk/aws-elasticloadbalancingv2/lib/nlb/network-target-group.ts
  packages/@aws-cdk/aws-elasticloadbalancingv2/test/nlb/test.listener.ts
Labels: pr-status/do-not-merge

#4466 chore(cfnspec): drop VPC traffic mirroring resource types
  packages/@aws-cdk/cfnspec/CHANGELOG.md
  packages/@aws-cdk/cfnspec/spec-source/000_CloudFormationResourceSpecification.json
Labels: contribution/core, pr-status/do-not-merge

#4519 fix(cli): fix bootstrap so that it has a default for tags on the stack.
  packages/aws-cdk/bin/cdk.ts
  packages/aws-cdk/test/integ/cli/test-cdk-multiple-toolkit-stacks.sh
Labels: contribution/core

#4479 fix(ecs): validate networkMode is aws_vpc when proxyConfiguration is provided
  packages/@aws-cdk/aws-ecs/lib/base/task-definition.ts
  packages/@aws-cdk/aws-ecs/test/ec2/test.ec2-task-definition.ts
  packages/@aws-cdk/aws-ecs/test/test.app-mesh-proxy-configuration.ts
Labels: package/ecs

#4525 chore: fix CHANGELOG header
  CHANGELOG.md
Labels: contribution/core

#4539 chore: add an integ test for deploy with notification ARNs
  packages/aws-cdk/test/integ/cli/test-cdk-deploy-with-notification-arns.sh
Labels: contribution/core

#4211 feat(apigateway): cors preflight support
  packages/@aws-cdk/aws-apigateway/README.md
  packages/@aws-cdk/aws-apigateway/lib/cors.ts
  packages/@aws-cdk/aws-apigateway/lib/index.ts
  packages/@aws-cdk/aws-apigateway/lib/resource.ts
  packages/@aws-cdk/aws-apigateway/lib/restapi.ts
  packages/@aws-cdk/aws-apigateway/lib/util.ts
  packages/@aws-cdk/aws-apigateway/test/integ.cors.expected.json
  packages/@aws-cdk/aws-apigateway/test/integ.cors.handler/index.ts
  packages/@aws-cdk/aws-apigateway/test/integ.cors.ts
  packages/@aws-cdk/aws-apigateway/test/test.cors.ts
  packages/@aws-cdk/aws-apigateway/test/test.resource.ts
Labels: contribution/core

#4183 fix(codepipeline): work around CodeBuild's pipeline key bug
  packages/@aws-cdk/aws-codebuild/lib/project.ts
  packages/@aws-cdk/aws-codebuild/test/test.project.ts
  packages/@aws-cdk/aws-codepipeline-actions/lib/codebuild/build-action.ts
  packages/@aws-cdk/aws-codepipeline-actions/test/integ.lambda-deployed-through-codepipeline.lit.expected.json
  packages/@aws-cdk/aws-codepipeline-actions/test/integ.lambda-deployed-through-codepipeline.lit.ts
  packages/@aws-cdk/aws-codepipeline-actions/test/integ.pipeline-code-commit-build.expected.json
  packages/@aws-cdk/aws-codepipeline-actions/test/integ.pipeline-events.expected.json
Labels: contribution/core

#4564 chore(ecs): fix the first code snippet on ECS documentation
  packages/@aws-cdk/aws-ecs/README.md
Labels: contribution/core, package/ecs

#4508 feat(ecs-patterns): add family name to queue processing service properties
  packages/@aws-cdk/aws-ecs-patterns/lib/base/queue-processing-service-base.ts
  packages/@aws-cdk/aws-ecs-patterns/lib/ecs/queue-processing-ecs-service.ts
  packages/@aws-cdk/aws-ecs-patterns/lib/fargate/queue-processing-fargate-service.ts
  packages/@aws-cdk/aws-ecs-patterns/test/ec2/test.queue-processing-ecs-service.ts
  packages/@aws-cdk/aws-ecs-patterns/test/fargate/test.queue-processing-fargate-service.ts
Labels: package/ecs

#4603 fix(cli): patch security vulnerability in https-proxy-agent (npm advisory 1184)
  packages/aws-cdk/.gitignore
  packages/aws-cdk/.npmignore
  packages/aws-cdk/package-lock.json
  packages/aws-cdk/package.json
  packages/aws-cdk/vendored/.no-packagejson-validator
  packages/aws-cdk/vendored/pac-proxy-agent/.travis.yml
  packages/aws-cdk/vendored/pac-proxy-agent/History.md
  packages/aws-cdk/vendored/pac-proxy-agent/README.md
  packages/aws-cdk/vendored/pac-proxy-agent/index.js
  packages/aws-cdk/vendored/pac-proxy-agent/package.json
  packages/aws-cdk/vendored/pac-proxy-agent/package.json.original
  packages/aws-cdk/vendored/pac-proxy-agent/test/ssl-cert-snakeoil.key
  packages/aws-cdk/vendored/pac-proxy-agent/test/ssl-cert-snakeoil.pem
  packages/aws-cdk/vendored/pac-proxy-agent/test/test.js
  packages/aws-cdk/vendored/proxy-agent/.travis.yml
  packages/aws-cdk/vendored/proxy-agent/History.md
  packages/aws-cdk/vendored/proxy-agent/README.md
  packages/aws-cdk/vendored/proxy-agent/index.d.ts
  packages/aws-cdk/vendored/proxy-agent/index.js
  packages/aws-cdk/vendored/proxy-agent/package.json
  packages/aws-cdk/vendored/proxy-agent/package.json.original
  packages/aws-cdk/vendored/proxy-agent/test/ssl-cert-snakeoil.key
  packages/aws-cdk/vendored/proxy-agent/test/ssl-cert-snakeoil.pem
  packages/aws-cdk/vendored/proxy-agent/test/test.js
Labels: contribution/core

#4611 Revert "fix(cli): patch security vulnerability in https-proxy-agent (npm advisory 1184) (#4603)
  packages/aws-cdk/.gitignore
  packages/aws-cdk/.npmignore
  packages/aws-cdk/package-lock.json
  packages/aws-cdk/package.json
  packages/aws-cdk/vendored/.no-packagejson-validator
  packages/aws-cdk/vendored/pac-proxy-agent/.travis.yml
  packages/aws-cdk/vendored/pac-proxy-agent/History.md
  packages/aws-cdk/vendored/pac-proxy-agent/README.md
  packages/aws-cdk/vendored/pac-proxy-agent/index.js
  packages/aws-cdk/vendored/pac-proxy-agent/package.json
  packages/aws-cdk/vendored/pac-proxy-agent/package.json.original
  packages/aws-cdk/vendored/pac-proxy-agent/test/ssl-cert-snakeoil.key
  packages/aws-cdk/vendored/pac-proxy-agent/test/ssl-cert-snakeoil.pem
  packages/aws-cdk/vendored/pac-proxy-agent/test/test.js
  packages/aws-cdk/vendored/proxy-agent/.travis.yml
  packages/aws-cdk/vendored/proxy-agent/History.md
  packages/aws-cdk/vendored/proxy-agent/README.md
  packages/aws-cdk/vendored/proxy-agent/index.d.ts
  packages/aws-cdk/vendored/proxy-agent/index.js
  packages/aws-cdk/vendored/proxy-agent/package.json
  packages/aws-cdk/vendored/proxy-agent/package.json.original
  packages/aws-cdk/vendored/proxy-agent/test/ssl-cert-snakeoil.key
  packages/aws-cdk/vendored/proxy-agent/test/ssl-cert-snakeoil.pem
  packages/aws-cdk/vendored/proxy-agent/test/test.js
Labels: contribution/core

#4595 feat(cloudformation): update CloudFormation Resource Specification to v7.1.0
  packages/@aws-cdk/cfnspec/CHANGELOG.md
  packages/@aws-cdk/cfnspec/spec-source/000_CloudFormationResourceSpecification.json
  packages/@aws-cdk/cfnspec/spec-source/000_sam.spec.json
Labels: contribution/core

#4499 fix(core): removalpolicy correct default
  packages/@aws-cdk/core/lib/removal-policy.ts
Labels: contribution/core

#4109 chore(mergify): workflow updates
  .mergify.yml
Labels: contribution/core

#4637 fix(codepipeline): the CodeBuild action now works with imported projects
  packages/@aws-cdk/aws-codepipeline-actions/lib/codebuild/build-action.ts
  packages/@aws-cdk/aws-codepipeline-actions/test/codebuild/test.codebuild-action.ts
Labels: contribution/core

#4639 chore(ecs): fix comments and README example for registering targets
  packages/@aws-cdk/aws-ecs/README.md
  packages/@aws-cdk/aws-ecs/lib/base/base-service.ts
Labels: package/ecs

#4576 chore(ecs): add unit test for cluster with an asg in public vpc without gateway
  packages/@aws-cdk/aws-ecs/test/test.ecs-cluster.ts
Labels: package/ecs

#4505 feat(ecs-patterns): add service name to queue processing service properties
  packages/@aws-cdk/aws-ecs-patterns/lib/base/queue-processing-service-base.ts
  packages/@aws-cdk/aws-ecs-patterns/lib/ecs/queue-processing-ecs-service.ts
  packages/@aws-cdk/aws-ecs-patterns/lib/fargate/queue-processing-fargate-service.ts
  packages/@aws-cdk/aws-ecs-patterns/test/ec2/test.queue-processing-ecs-service.ts
  packages/@aws-cdk/aws-ecs-patterns/test/fargate/test.queue-processing-fargate-service.ts
Labels: package/ecs-patterns

#4638 feat(ecs): add support for start and stop timeout in ContainerDefinition
  packages/@aws-cdk/aws-ecs/lib/container-definition.ts
  packages/@aws-cdk/aws-ecs/test/test.container-definition.ts
Labels: package/ecs

#4502 feat(codepipeline): add ability to override env variables in CodeBuild actions
  packages/@aws-cdk/aws-codebuild/lib/project.ts
  packages/@aws-cdk/aws-codepipeline-actions/lib/codebuild/build-action.ts
  packages/@aws-cdk/aws-codepipeline-actions/test/integ.pipeline-code-commit-build.expected.json
  packages/@aws-cdk/aws-codepipeline-actions/test/integ.pipeline-code-commit-build.ts
Labels: contribution/core, pr-status/do-not-merge

#4630 fix(iam): fix `managedPolicyName` attribute
  packages/@aws-cdk/aws-iam/lib/managed-policy.ts
  packages/@aws-cdk/aws-iam/test/managed-policy.test.ts
Labels: contribution/core

#4667 chore(elbv2/ecs): clarify cross-stack ELB usage
  packages/@aws-cdk/aws-ecs/README.md
  packages/@aws-cdk/aws-ecs/lib/container-definition.ts
  packages/@aws-cdk/aws-elasticloadbalancingv2/README.md
  packages/@aws-cdk/aws-elasticloadbalancingv2/lib/alb/application-target-group.ts
  packages/@aws-cdk/aws-elasticloadbalancingv2/lib/nlb/network-target-group.ts
  packages/@aws-cdk/aws-elasticloadbalancingv2/lib/shared/base-target-group.ts
  packages/@aws-cdk/aws-elasticloadbalancingv2/test/alb/test.target-group.ts
  packages/@aws-cdk/aws-elasticloadbalancingv2/test/helpers.ts
  packages/@aws-cdk/aws-elasticloadbalancingv2/test/nlb/test.target-group.ts
Labels: contribution/core

#4625 fix(cli): add Cloud Assembly backwards compat tests
  packages/aws-cdk/.gitignore
  packages/aws-cdk/test/integ/cli/.gitignore
  packages/aws-cdk/test/integ/cli/app/.gitignore
  packages/aws-cdk/test/integ/cli/cloud-assemblies/0.36.0/InitStack.template.json
  packages/aws-cdk/test/integ/cli/cloud-assemblies/0.36.0/cdk.out
  packages/aws-cdk/test/integ/cli/cloud-assemblies/0.36.0/manifest.json
  packages/aws-cdk/test/integ/cli/cloud-assemblies/1.10.0-lookup-default-vpc/InitStack.template.json
  packages/aws-cdk/test/integ/cli/cloud-assemblies/1.10.0-lookup-default-vpc/cdk.out
  packages/aws-cdk/test/integ/cli/cloud-assemblies/1.10.0-lookup-default-vpc/manifest.json.js
  packages/aws-cdk/test/integ/cli/cloud-assemblies/1.10.0-request-azs/InitStack.template.json
  packages/aws-cdk/test/integ/cli/cloud-assemblies/1.10.0-request-azs/cdk.out
  packages/aws-cdk/test/integ/cli/cloud-assemblies/1.10.0-request-azs/manifest.json.js
  packages/aws-cdk/test/integ/cli/common.bash
  packages/aws-cdk/test/integ/cli/test-backwards-compat.sh
  packages/aws-cdk/test/integ/cli/test-cdk-ssm-parameter-provider-error.sh
Labels: contribution/core

#4689 fix(codebuild): revert validation that only a project with source CODEPIPELINE can be added to a pipeline
  packages/@aws-cdk/aws-codebuild/lib/project.ts
  packages/@aws-cdk/aws-codebuild/test/test.project.ts
  packages/@aws-cdk/aws-codepipeline-actions/test/integ.lambda-deployed-through-codepipeline.lit.expected.json
  packages/@aws-cdk/aws-codepipeline-actions/test/integ.lambda-deployed-through-codepipeline.lit.ts
Labels: contribution/core

#4668 feat(vpc): additional validation around Subnet Types
  packages/@aws-cdk/aws-ec2/lib/vpc.ts
  packages/@aws-cdk/aws-ec2/test/test.vpc.ts
Labels: contribution/core

#4688 feat(ecs-patterns): add family name to load balanced service properties
  packages/@aws-cdk/aws-ecs-patterns/lib/base/application-load-balanced-service-base.ts
  packages/@aws-cdk/aws-ecs-patterns/lib/base/network-load-balanced-service-base.ts
  packages/@aws-cdk/aws-ecs-patterns/lib/ecs/application-load-balanced-ecs-service.ts
  packages/@aws-cdk/aws-ecs-patterns/lib/ecs/network-load-balanced-ecs-service.ts
  packages/@aws-cdk/aws-ecs-patterns/lib/fargate/application-load-balanced-fargate-service.ts
  packages/@aws-cdk/aws-ecs-patterns/lib/fargate/network-load-balanced-fargate-service.ts
  packages/@aws-cdk/aws-ecs-patterns/test/fargate/test.load-balanced-fargate-service.ts
Labels: contribution/core, package/ecs

#4544 feat(vpc): allow Vpc.fromLookup() to discover asymmetric subnets
  packages/@aws-cdk/aws-ec2/lib/vpc-lookup.ts
  packages/@aws-cdk/aws-ec2/lib/vpc.ts
  packages/@aws-cdk/aws-ec2/test/test.vpc.from-lookup.ts
  packages/@aws-cdk/aws-ec2/test/test.vpc.ts
  packages/@aws-cdk/core/lib/context-provider.ts
  packages/@aws-cdk/core/test/test.context.ts
  packages/@aws-cdk/cx-api/lib/context/vpc.ts
  packages/@aws-cdk/cx-api/lib/versioning.ts
  packages/@aws-cdk/cx-api/test/__snapshots__/cloud-assembly.test.js.snap
  packages/aws-cdk/lib/context-providers/vpcs.ts
  packages/aws-cdk/test/context-providers/test.asymmetric-vpcs.ts
  packages/aws-cdk/test/context-providers/test.vpcs.ts
  tools/cdk-integ-tools/lib/integ-helpers.ts
Labels: contribution/core

#4760 fix(cloudfront): aliasConfiguration fallback identifier conflict
  packages/@aws-cdk/aws-cloudfront/lib/web_distribution.ts
  packages/@aws-cdk/aws-cloudfront/test/test.basic.ts
Labels: status/in-progress
