Repository aws/aws-cdk, pull requests merged in 2019-08, with the labels that each got.

#3032 feat(ecs): container dependencies
  packages/@aws-cdk/aws-codepipeline-actions/test/integ.pipeline-ecs-deploy.expected.json
  packages/@aws-cdk/aws-ecs-patterns/test/ec2/integ.scheduled-ecs-task.lit.expected.json
  packages/@aws-cdk/aws-ecs-patterns/test/ec2/test.scheduled-ecs-task.ts
  packages/@aws-cdk/aws-ecs-patterns/test/fargate/integ.asset-image.expected.json
  packages/@aws-cdk/aws-ecs-patterns/test/fargate/integ.executionrole.expected.json
  packages/@aws-cdk/aws-ecs-patterns/test/fargate/integ.l3-autocreate.expected.json
  packages/@aws-cdk/aws-ecs-patterns/test/fargate/integ.l3-vpconly.expected.json
  packages/@aws-cdk/aws-ecs-patterns/test/fargate/integ.l3.expected.json
  packages/@aws-cdk/aws-ecs-patterns/test/fargate/integ.scheduled-fargate-task.lit.expected.json
  packages/@aws-cdk/aws-ecs-patterns/test/fargate/test.scheduled-fargate-task.ts
  packages/@aws-cdk/aws-ecs/lib/base/base-service.ts
  packages/@aws-cdk/aws-ecs/lib/base/task-definition.ts
  packages/@aws-cdk/aws-ecs/lib/container-definition.ts
  packages/@aws-cdk/aws-ecs/lib/ec2/ec2-service.ts
  packages/@aws-cdk/aws-ecs/lib/linux-parameters.ts
  packages/@aws-cdk/aws-ecs/test/ec2/integ.lb-awsvpc-nw.expected.json
  packages/@aws-cdk/aws-ecs/test/ec2/integ.lb-bridge-nw.expected.json
  packages/@aws-cdk/aws-ecs/test/ec2/integ.sd-awsvpc-nw.expected.json
  packages/@aws-cdk/aws-ecs/test/ec2/integ.sd-bridge-nw.expected.json
  packages/@aws-cdk/aws-ecs/test/ec2/test.ec2-task-definition.ts
  packages/@aws-cdk/aws-ecs/test/fargate/integ.lb-awsvpc-nw.expected.json
  packages/@aws-cdk/aws-events-targets/test/ecs/integ.event-ec2-task.lit.expected.json
  packages/@aws-cdk/aws-events-targets/test/ecs/integ.event-fargate-task.expected.json
  packages/@aws-cdk/aws-stepfunctions-tasks/test/integ.ec2-task.expected.json
  packages/@aws-cdk/aws-stepfunctions-tasks/test/integ.fargate-task.expected.json
  packages/decdk/test/__snapshots__/synth.test.js.snap
Labels: blocked

#3551 chore(ecs): add missing unit tests
  packages/@aws-cdk/aws-ecs/test/ec2/test.ec2-service.ts
  packages/@aws-cdk/aws-ecs/test/ec2/test.ec2-task-definition.ts
  packages/@aws-cdk/aws-ecs/test/fargate/test.fargate-service.ts
  packages/@aws-cdk/aws-ecs/test/test.aws-log-driver.ts
  packages/@aws-cdk/aws-ecs/test/test.container-definition.ts
  packages/@aws-cdk/aws-ecs/test/test.ecs-cluster.ts
Labels: service/ecs

#3550 feat(ecs-patterns): allow customizing logdriver
  packages/@aws-cdk/aws-ecs-patterns/lib/base/load-balanced-service-base.ts
  packages/@aws-cdk/aws-ecs-patterns/lib/base/queue-processing-service-base.ts
  packages/@aws-cdk/aws-ecs-patterns/lib/base/scheduled-task-base.ts
  packages/@aws-cdk/aws-ecs-patterns/lib/ecs/queue-processing-ecs-service.ts
  packages/@aws-cdk/aws-ecs-patterns/lib/ecs/scheduled-ecs-task.ts
  packages/@aws-cdk/aws-ecs-patterns/lib/fargate/queue-processing-fargate-service.ts
  packages/@aws-cdk/aws-ecs-patterns/lib/fargate/scheduled-fargate-task.ts
  packages/@aws-cdk/aws-ecs-patterns/test/ec2/test.l3s.ts
Labels: service/ecs

#3560 Also redact AWS_SECURITY_TOKEN
  packages/aws-cdk/lib/commands/doctor.ts
Labels: cli, security

#3509 fix(ec2): allow adding gateway endpoints to imported VPC
  packages/@aws-cdk/aws-ec2/lib/util.ts
  packages/@aws-cdk/aws-ec2/lib/vpc.ts
  packages/@aws-cdk/aws-ec2/test/test.vpc-endpoint.ts
Labels: service/ec2

#3572 fix(asg/ec2): fix value of `defaultChild`
  packages/@aws-cdk/aws-autoscaling/lib/auto-scaling-group.ts
  packages/@aws-cdk/aws-autoscaling/test/test.auto-scaling-group.ts
  packages/@aws-cdk/aws-ec2/lib/vpc.ts
  packages/@aws-cdk/aws-ec2/test/test.vpc.ts
  packages/@aws-cdk/core/lib/construct.ts
  packages/@aws-cdk/core/test/test.construct.ts
Labels: small

#3568 fix(core): fix use of references in toJsonString()
  packages/@aws-cdk/aws-codepipeline-actions/test/cloudformation/test.pipeline-actions.ts
  packages/@aws-cdk/core/lib/private/cfn-reference.ts
  packages/@aws-cdk/core/lib/private/cloudformation-lang.ts
  packages/@aws-cdk/core/lib/private/resolve.ts
  packages/@aws-cdk/core/lib/resolvable.ts
  packages/@aws-cdk/core/lib/stack.ts
  packages/@aws-cdk/core/lib/token.ts
  packages/@aws-cdk/core/test/test.cloudformation-json.ts
Labels: small

#3597 chore(ec2): fix constants in comment
  packages/@aws-cdk/aws-ec2/lib/vpc.ts
Labels: tiny-review

#3522 feat(stepfunctions): support step functions state machine execution from a task state
  packages/@aws-cdk/aws-stepfunctions-tasks/lib/index.ts
  packages/@aws-cdk/aws-stepfunctions-tasks/lib/invoke-activity.ts
  packages/@aws-cdk/aws-stepfunctions-tasks/lib/invoke-function.ts
  packages/@aws-cdk/aws-stepfunctions-tasks/lib/publish-to-topic.ts
  packages/@aws-cdk/aws-stepfunctions-tasks/lib/send-to-queue.ts
  packages/@aws-cdk/aws-stepfunctions-tasks/lib/start-execution.ts
  packages/@aws-cdk/aws-stepfunctions-tasks/test/start-execution.test.ts
  packages/@aws-cdk/aws-stepfunctions/README.md
Labels: small-review

#3584 feat(iam): support permissions boundary policy for User and Role
  packages/@aws-cdk/aws-iam/lib/role.ts
  packages/@aws-cdk/aws-iam/lib/user.ts
  packages/@aws-cdk/aws-iam/test/test.role.ts
  packages/@aws-cdk/aws-iam/test/test.user.ts
Labels: tiny-review

#3598 feat(iam): allow supplying multiple external ids
  packages/@aws-cdk/aws-iam/lib/role.ts
  packages/@aws-cdk/aws-iam/test/example.external-id.lit.ts
  packages/@aws-cdk/aws-iam/test/integ.role.ts
  packages/@aws-cdk/aws-iam/test/test.role.ts
Labels: tiny-review

#3578 feat(iam): customer managed policies
  allowed-breaking-changes.txt
  packages/@aws-cdk/aws-iam/lib/group.ts
  packages/@aws-cdk/aws-iam/lib/managed-policy.ts
  packages/@aws-cdk/aws-iam/lib/role.ts
  packages/@aws-cdk/aws-iam/lib/user.ts
  packages/@aws-cdk/aws-iam/package.json
  packages/@aws-cdk/aws-iam/test/integ.managed-policy.expected.json
  packages/@aws-cdk/aws-iam/test/integ.managed-policy.ts
  packages/@aws-cdk/aws-iam/test/test.managed-policy.ts
  packages/@aws-cdk/aws-iam/test/test.role.ts
Labels: small-review

#3596 fix(kms): allow multiple `addAlias` calls on single key
  packages/@aws-cdk/aws-kms/lib/alias.ts
  packages/@aws-cdk/aws-kms/lib/key.ts
  packages/@aws-cdk/aws-kms/test/integ.key-sharing.lit.expected.json
  packages/@aws-cdk/aws-kms/test/integ.key-sharing.lit.ts
  packages/@aws-cdk/aws-kms/test/integ.key.expected.json
  packages/@aws-cdk/aws-kms/test/test.alias.ts
  packages/@aws-cdk/aws-kms/test/test.key.ts
Labels: small-review

#3020 fix(aws-ecs): ensure cluster attributes are accessible from constructor’s props
  packages/@aws-cdk/aws-ecs/lib/cluster.ts
  packages/@aws-cdk/aws-ecs/test/test.ecs-cluster.ts
Labels: service/ecs

#3358 fix(ecs): update driverOpts type definition from array to map
  allowed-breaking-changes.txt
  packages/@aws-cdk/aws-ecs/lib/base/task-definition.ts
  packages/@aws-cdk/aws-ecs/test/ec2/test.ec2-task-definition.ts
Labels: service/ecs

#3380 feat(route53): add classic elb target support
  packages/@aws-cdk/aws-route53-targets/README.md
  packages/@aws-cdk/aws-route53-targets/lib/classic-load-balancer-target.ts
  packages/@aws-cdk/aws-route53-targets/lib/index.ts
  packages/@aws-cdk/aws-route53-targets/package.json
  packages/@aws-cdk/aws-route53-targets/test/classic-load-balancer-target.test.ts
Labels: small-review

#3208 feat(codepipeline): allow cross-account CloudFormation Actions
  packages/@aws-cdk/aws-codepipeline-actions/README.md
  packages/@aws-cdk/aws-codepipeline-actions/lib/cloudformation/pipeline-actions.ts
  packages/@aws-cdk/aws-codepipeline-actions/test/cloudformation/test.cloudformation-pipeline-actions.ts
  packages/@aws-cdk/aws-codepipeline/lib/action.ts
  packages/@aws-cdk/aws-codepipeline/lib/pipeline.ts
  packages/@aws-cdk/aws-codepipeline/test/fake-build-action.ts
  packages/@aws-cdk/aws-codepipeline/test/test.pipeline.ts
Labels: do-not-merge

#3369 feat(apigateway): support imported roles for integrations
  allowed-breaking-changes.txt
  packages/@aws-cdk/aws-apigateway/lib/integration.ts
  packages/@aws-cdk/aws-apigateway/lib/method.ts
Labels: service/apigateway

#3682 docs(codepipeline) update oauthToken docstrings
  packages/@aws-cdk/aws-codepipeline-actions/README.md
  packages/@aws-cdk/aws-codepipeline-actions/lib/github/source-action.ts
Labels: do-not-merge

#3695 feat(cli): force deployment bucket to be private
  packages/aws-cdk/lib/api/bootstrap-environment.ts
Labels: automerge-enabled

#3576 fix(events-targets): allow adding same fargate task to multiple rules
  packages/@aws-cdk/aws-ecs-patterns/test/fargate/integ.scheduled-fargate-task.lit.expected.json
  packages/@aws-cdk/aws-events-targets/lib/ecs-task.ts
  packages/@aws-cdk/aws-events-targets/test/ecs/event-rule-target.test.ts
  packages/@aws-cdk/aws-events-targets/test/ecs/integ.event-fargate-task.expected.json
Labels: automerge-enabled

#3590 fix(ecr): set correct resource policy for ecr repository
  packages/@aws-cdk/aws-ecr/lib/repository.ts
  packages/@aws-cdk/aws-ecr/test/test.repository.ts
Labels: automerge-enabled

#3710 feat(cloudformation): Update CloudFormation spec to 5.2.0
  packages/@aws-cdk/cfnspec/CHANGELOG.md
  packages/@aws-cdk/cfnspec/spec-source/000_CloudFormationResourceSpecification.json
Labels: automerge-enabled

#3712 docs(aws-ecs-patterns): update documentation for the aws-ecs-patterns module
  packages/@aws-cdk/aws-ecs-patterns/lib/base/load-balanced-service-base.ts
  packages/@aws-cdk/aws-ecs-patterns/lib/base/queue-processing-service-base.ts
  packages/@aws-cdk/aws-ecs-patterns/lib/base/scheduled-task-base.ts
  packages/@aws-cdk/aws-ecs-patterns/lib/ecs/load-balanced-ecs-service.ts
  packages/@aws-cdk/aws-ecs-patterns/lib/ecs/queue-processing-ecs-service.ts
  packages/@aws-cdk/aws-ecs-patterns/lib/ecs/scheduled-ecs-task.ts
  packages/@aws-cdk/aws-ecs-patterns/lib/fargate/load-balanced-fargate-service.ts
Labels: automerge-enabled

#3679 chore(ecs): add additional missing unit tests
  packages/@aws-cdk/aws-ecs/lib/container-definition.ts
  packages/@aws-cdk/aws-ecs/lib/ec2/ec2-service.ts
  packages/@aws-cdk/aws-ecs/test/ec2/test.ec2-service.ts
  packages/@aws-cdk/aws-ecs/test/ec2/test.ec2-task-definition.ts
  packages/@aws-cdk/aws-ecs/test/fargate/test.fargate-service.ts
  packages/@aws-cdk/aws-ecs/test/fargate/test.fargate-task-definition.ts
  packages/@aws-cdk/aws-ecs/test/test.aws-log-driver.ts
  packages/@aws-cdk/aws-ecs/test/test.container-definition.ts
  packages/@aws-cdk/aws-ecs/test/test.ecs-cluster.ts
Labels: automerge-enabled, service/ecs

#3723 fix(aws-cdk): update Java template to new builder style
  packages/aws-cdk/lib/init-templates/app/java/src/main/java/com/myorg/HelloConstructProps.java
  packages/aws-cdk/lib/init-templates/app/java/src/main/java/com/myorg/HelloStack.java
Labels: automerge-enabled

#3727 chore(iam): fix casing of notActions, notResources
  packages/@aws-cdk/aws-iam/lib/policy-statement.ts
  packages/@aws-cdk/aws-iam/test/test.policy-document.ts
Labels: automerge-enabled

#3014 fix(aws-stepfunctions): refactor sagemaker tasks and fix default role issue
  packages/@aws-cdk/aws-stepfunctions-tasks/lib/sagemaker-task-base-types.ts
  packages/@aws-cdk/aws-stepfunctions-tasks/lib/sagemaker-train-task.ts
  packages/@aws-cdk/aws-stepfunctions-tasks/lib/sagemaker-transform-task.ts
  packages/@aws-cdk/aws-stepfunctions-tasks/test/integ.sagemaker.expected.json
  packages/@aws-cdk/aws-stepfunctions-tasks/test/integ.sagemaker.ts
  packages/@aws-cdk/aws-stepfunctions-tasks/test/sagemaker-training-job.test.ts
  packages/@aws-cdk/aws-stepfunctions-tasks/test/sagemaker-transform-job.test.ts
Labels: automerge-enabled

#3739 fix(ec2): throw useful error when using lazy CIDR in VPC
  packages/@aws-cdk/aws-ec2/lib/vpc.ts
  packages/@aws-cdk/aws-ec2/test/test.vpc.ts
Labels: automerge-enabled

#2861 feat(cloudfront): define lambda@edge as resolvable resource
  packages/@aws-cdk/aws-cloudfront/package.json
  packages/@aws-cdk/aws-cloudfront/test/test.basic.ts
  packages/@aws-cdk/aws-lambda/lib/lambda-version.ts
  packages/@aws-cdk/aws-lambda/test/test.lambda-version.ts
Labels: automerge-enabled

#3740 fix(ec2): fix error when using Tokens in Vpc.fromLookup()
  packages/@aws-cdk/aws-ec2/lib/vpc.ts
  packages/@aws-cdk/aws-ec2/test/test.vpc.ts
Labels: automerge-enabled

#3741 fix(ec2): also add egress rules for `allowInternally()`
  packages/@aws-cdk/aws-ec2/lib/connections.ts
  packages/@aws-cdk/aws-ec2/test/test.connections.ts
Labels: automerge-enabled

#3742 docs(aws-ecs-patterns): update ecs-patterns README
  packages/@aws-cdk/aws-ecs-patterns/README.md
Labels: automerge-enabled

#3743 docs(aws-ecs-patterns): update loadbalancedservicebase documentation
  packages/@aws-cdk/aws-ecs-patterns/lib/base/load-balanced-service-base.ts
Labels: automerge-enabled

#3738 fix(iam): make User implement IUser
  packages/@aws-cdk/aws-iam/lib/user.ts
Labels: automerge-enabled

#3642 feat(ec2): peer cidr ip validation
  packages/@aws-cdk/aws-ec2/lib/peer.ts
  packages/@aws-cdk/aws-ec2/test/test.security-group.ts
Labels: automerge-enabled

#3755 fix(ecs): IAM role ARN must not specific region.
  packages/@aws-cdk/aws-ecs/lib/base/base-service.ts
  packages/@aws-cdk/aws-ecs/test/fargate/integ.lb-awsvpc-nw.expected.json
Labels: automerge-enabled

#3680 feat(cloudtrail): accept existing S3 bucket
  packages/@aws-cdk/aws-cloudtrail/lib/index.ts
  packages/@aws-cdk/aws-cloudtrail/test/integ.cloudtrail-supplied-bucket.lit.expected.json
  packages/@aws-cdk/aws-cloudtrail/test/integ.cloudtrail-supplied-bucket.lit.ts
  packages/@aws-cdk/aws-cloudtrail/test/test.cloudtrail.ts
Labels: automerge-enabled, do-not-merge

#3756 fix(core): corrected documentation for CfnParameter#valueAsNumber()
  packages/@aws-cdk/core/lib/cfn-parameter.ts
Labels: automerge-enabled

#3044 feat(ecs): add GPU support in container definition
  packages/@aws-cdk/aws-ecs/lib/container-definition.ts
  packages/@aws-cdk/aws-ecs/test/test.container-definition.ts
Labels: automerge-enabled, service/ecs

#3420 feat(ecs): support ecs tag propagation and ecs managed tags
  design/aws-ecs/aws-ecs-tagging-support.md
  packages/@aws-cdk/aws-codepipeline-actions/test/integ.pipeline-ecs-deploy.expected.json
  packages/@aws-cdk/aws-ecs-patterns/test/fargate/integ.asset-image.expected.json
  packages/@aws-cdk/aws-ecs-patterns/test/fargate/integ.executionrole.expected.json
  packages/@aws-cdk/aws-ecs-patterns/test/fargate/integ.l3-autocreate.expected.json
  packages/@aws-cdk/aws-ecs-patterns/test/fargate/integ.l3-vpconly.expected.json
  packages/@aws-cdk/aws-ecs-patterns/test/fargate/integ.l3.expected.json
  packages/@aws-cdk/aws-ecs/lib/base/base-service.ts
  packages/@aws-cdk/aws-ecs/lib/ec2/ec2-service.ts
  packages/@aws-cdk/aws-ecs/lib/fargate/fargate-service.ts
  packages/@aws-cdk/aws-ecs/test/ec2/integ.lb-awsvpc-nw.expected.json
  packages/@aws-cdk/aws-ecs/test/ec2/integ.lb-bridge-nw.expected.json
  packages/@aws-cdk/aws-ecs/test/ec2/integ.sd-awsvpc-nw.expected.json
  packages/@aws-cdk/aws-ecs/test/ec2/integ.sd-bridge-nw.expected.json
  packages/@aws-cdk/aws-ecs/test/ec2/test.ec2-service.ts
  packages/@aws-cdk/aws-ecs/test/fargate/integ.lb-awsvpc-nw.expected.json
  packages/@aws-cdk/aws-ecs/test/fargate/test.fargate-service.ts
  packages/decdk/test/__snapshots__/synth.test.js.snap
Labels: automerge-enabled, service/ecs

#2299 feat(appmesh): add support for AWS AppMesh
  packages/@aws-cdk/aws-appmesh/README.md
  packages/@aws-cdk/aws-appmesh/lib/index.ts
  packages/@aws-cdk/aws-appmesh/lib/mesh.ts
  packages/@aws-cdk/aws-appmesh/lib/route.ts
  packages/@aws-cdk/aws-appmesh/lib/shared-interfaces.ts
  packages/@aws-cdk/aws-appmesh/lib/virtual-node.ts
  packages/@aws-cdk/aws-appmesh/lib/virtual-router.ts
  packages/@aws-cdk/aws-appmesh/lib/virtual-service.ts
  packages/@aws-cdk/aws-appmesh/package-lock.json
  packages/@aws-cdk/aws-appmesh/package.json
  packages/@aws-cdk/aws-appmesh/test/integ.mesh.expected.json
  packages/@aws-cdk/aws-appmesh/test/integ.mesh.ts
  packages/@aws-cdk/aws-appmesh/test/test.appmesh.ts
  packages/@aws-cdk/aws-appmesh/test/test.mesh.ts
  packages/@aws-cdk/aws-appmesh/test/test.route.ts
  packages/@aws-cdk/aws-appmesh/test/test.virtual-node.ts
  packages/@aws-cdk/aws-appmesh/test/test.virtual-router.ts
  packages/@aws-cdk/aws-appmesh/test/test.virtual-service.ts
  packages/@aws-cdk/aws-certificatemanager/lambda-packages/dns_validated_certificate_handler/package-lock.json
  packages/@aws-cdk/aws-ec2/lib/vpc.ts
  packages/@aws-cdk/core/lib/duration.ts
  packages/@aws-cdk/core/test/test.duration.ts
Labels: automerge-enabled, do-not-merge, review/large

#3758 fix(scaling): don't fail when using Tokens
  packages/@aws-cdk/aws-applicationautoscaling/lib/scalable-target.ts
  packages/@aws-cdk/aws-applicationautoscaling/test/test.scalable-target.ts
  packages/@aws-cdk/aws-autoscaling/lib/auto-scaling-group.ts
  packages/@aws-cdk/aws-autoscaling/test/test.auto-scaling-group.ts
  packages/@aws-cdk/core/lib/token.ts
Labels: automerge-enabled, do-not-merge

#3736 chore(events): add sqsparameters for event targets (#3735)
  packages/@aws-cdk/aws-events/lib/rule.ts
  packages/@aws-cdk/aws-events/lib/target.ts
  packages/@aws-cdk/aws-events/test/test.rule.ts
Labels: automerge-enabled

#3697 WIP: feat(ec2): add instance resource
  packages/@aws-cdk/aws-ec2/README.md
  packages/@aws-cdk/aws-ec2/lib/bastion-host.ts
  packages/@aws-cdk/aws-ec2/lib/index.ts
  packages/@aws-cdk/aws-ec2/lib/instance.ts
  packages/@aws-cdk/aws-ec2/lib/vpc.ts
  packages/@aws-cdk/aws-ec2/package-lock.json
  packages/@aws-cdk/aws-ec2/package.json
  packages/@aws-cdk/aws-ec2/test/integ.bastion-host.expected.json
  packages/@aws-cdk/aws-ec2/test/integ.bastion-host.ts
  packages/@aws-cdk/aws-ec2/test/integ.instance.expected.json
  packages/@aws-cdk/aws-ec2/test/integ.instance.ts
Labels: automerge-enabled, do-not-merge

#3386 feat(ec2): imported SecurityGroups don't create egress rules
  packages/@aws-cdk/aws-ec2/lib/connections.ts
  packages/@aws-cdk/aws-ec2/lib/security-group.ts
  packages/@aws-cdk/aws-ec2/package.json
  packages/@aws-cdk/aws-ec2/test/test.connections.ts
  packages/@aws-cdk/aws-ec2/test/test.security-group.ts
  packages/@aws-cdk/aws-elasticloadbalancingv2/lib/alb/application-listener.ts
  packages/@aws-cdk/aws-elasticloadbalancingv2/lib/alb/application-load-balancer.ts
  packages/@aws-cdk/aws-elasticloadbalancingv2/test/alb/test.security-groups.ts
Labels: automerge-enabled, do-not-merge

#3348 feat(elbv2): add support for Lambda targets
  packages/@aws-cdk/aws-elasticloadbalancingv2-targets/.gitignore
  packages/@aws-cdk/aws-elasticloadbalancingv2-targets/.npmignore
  packages/@aws-cdk/aws-elasticloadbalancingv2-targets/LICENSE
  packages/@aws-cdk/aws-elasticloadbalancingv2-targets/NOTICE
  packages/@aws-cdk/aws-elasticloadbalancingv2-targets/README.md
  packages/@aws-cdk/aws-elasticloadbalancingv2-targets/lib/index.ts
  packages/@aws-cdk/aws-elasticloadbalancingv2-targets/lib/instance-target.ts
  packages/@aws-cdk/aws-elasticloadbalancingv2-targets/lib/ip-target.ts
  packages/@aws-cdk/aws-elasticloadbalancingv2-targets/lib/lambda-target.ts
  packages/@aws-cdk/aws-elasticloadbalancingv2-targets/package-lock.json
  packages/@aws-cdk/aws-elasticloadbalancingv2-targets/package.json
  packages/@aws-cdk/aws-elasticloadbalancingv2-targets/test/instance-target.test.ts
  packages/@aws-cdk/aws-elasticloadbalancingv2-targets/test/integ.lambda-target.expected.json
  packages/@aws-cdk/aws-elasticloadbalancingv2-targets/test/integ.lambda-target.ts
  packages/@aws-cdk/aws-elasticloadbalancingv2-targets/test/ip-target.test.ts
  packages/@aws-cdk/aws-elasticloadbalancingv2-targets/test/lambda-target.test.ts
  packages/@aws-cdk/aws-elasticloadbalancingv2/README.md
  packages/@aws-cdk/aws-elasticloadbalancingv2/lib/alb/application-listener.ts
  packages/@aws-cdk/aws-elasticloadbalancingv2/lib/alb/application-target-group.ts
  packages/@aws-cdk/aws-elasticloadbalancingv2/lib/shared/base-target-group.ts
  packages/@aws-cdk/aws-elasticloadbalancingv2/lib/shared/enums.ts
  packages/@aws-cdk/aws-elasticloadbalancingv2/lib/shared/load-balancer-targets.ts
  packages/@aws-cdk/aws-elasticloadbalancingv2/lib/shared/util.ts
  packages/@aws-cdk/aws-elasticloadbalancingv2/package.json
  packages/decdk/package.json
Labels: automerge-enabled, do-not-merge, review/large

#3728 fix(lambda): generate correct metrics for aliases
  packages/@aws-cdk/aws-codedeploy/test/lambda/integ.deployment-group.expected.json
  packages/@aws-cdk/aws-lambda/lib/alias.ts
  packages/@aws-cdk/aws-lambda/test/test.alias.ts
Labels: automerge-enabled

#3789 feat: updated CloudFormation Resource specification 5.3.0
  packages/@aws-cdk/cfnspec/CHANGELOG.md
  packages/@aws-cdk/cfnspec/spec-source/000_CloudFormationResourceSpecification.json
Labels: automerge-enabled

#3720 feat(events): add target to make AWS API calls
  packages/@aws-cdk/aws-events-targets/.gitignore
  packages/@aws-cdk/aws-events-targets/README.md
  packages/@aws-cdk/aws-events-targets/lib/aws-api-handler/index.ts
  packages/@aws-cdk/aws-events-targets/lib/aws-api.ts
  packages/@aws-cdk/aws-events-targets/lib/index.ts
  packages/@aws-cdk/aws-events-targets/lib/lambda.ts
  packages/@aws-cdk/aws-events-targets/lib/util.ts
  packages/@aws-cdk/aws-events-targets/package-lock.json
  packages/@aws-cdk/aws-events-targets/package.json
  packages/@aws-cdk/aws-events-targets/test/aws-api/aws-api-handler.test.ts
  packages/@aws-cdk/aws-events-targets/test/aws-api/aws-api.test.ts
  packages/@aws-cdk/aws-events-targets/test/aws-api/integ.aws-api.expected.json
  packages/@aws-cdk/aws-events-targets/test/aws-api/integ.aws-api.ts
  packages/@aws-cdk/aws-events/README.md
Labels: automerge-enabled

#3785 feat(acm): validated certificate can use existing Role
  packages/@aws-cdk/aws-certificatemanager/lib/dns-validated-certificate.ts
  packages/@aws-cdk/aws-certificatemanager/test/test.dns-validated-certificate.ts
Labels: automerge-enabled

#3730 fix(lambda/rds): allow to specify a role for log retention lambda
  packages/@aws-cdk/aws-lambda/lib/function.ts
  packages/@aws-cdk/aws-lambda/lib/log-retention.ts
  packages/@aws-cdk/aws-lambda/test/integ.log-retention.expected.json
  packages/@aws-cdk/aws-lambda/test/test.log-retention.ts
  packages/@aws-cdk/aws-rds/lib/instance.ts
  packages/@aws-cdk/aws-rds/test/integ.instance.lit.expected.json
Labels: automerge-enabled

#3786 fix(events): fix ECS target in Isolated subnet
  packages/@aws-cdk/aws-events-targets/lib/ecs-task.ts
  packages/@aws-cdk/aws-events-targets/test/ecs/event-rule-target.test.ts
Labels: automerge-enabled

#3784 fix(vpc): recognize Public subnets by Internet Gateway
  packages/aws-cdk/lib/context-providers/vpcs.ts
  packages/aws-cdk/test/context-providers/test.vpcs.ts
Labels: automerge-enabled

#3144 fix(toolkit): do not deploy empty stacks
  packages/aws-cdk/bin/cdk.ts
  packages/aws-cdk/lib/cdk-toolkit.ts
  packages/aws-cdk/test/integ/cli/app/app.js
  packages/aws-cdk/test/integ/cli/test-cdk-no-resource.sh
  packages/aws-cdk/test/test.cdk-toolkit.ts
Labels: automerge-enabled

#3840 fix(init-templates): remove dependency on @types/node
  package-lock.json
  package.json
  packages/aws-cdk/lib/init-templates/app/javascript/bin/%name%.template.js
  packages/aws-cdk/lib/init-templates/app/javascript/package.template.json
  packages/aws-cdk/lib/init-templates/app/javascript/tsconfig.json
  packages/aws-cdk/lib/init-templates/app/typescript/package.template.json
  packages/aws-cdk/lib/init-templates/lib/typescript/package.template.json
  packages/aws-cdk/lib/init-templates/sample-app/typescript/package.template.json
  packages/decdk/package-lock.json
  tools/awslint/package.json
  tools/cdk-build-tools/package-lock.json
  tools/cdk-build-tools/package.json
Labels: automerge-enabled

#3810 docs(vpc): update VPC documentation in README and API
  packages/@aws-cdk/aws-ec2/README.md
  packages/@aws-cdk/aws-ec2/lib/vpc.ts
Labels: automerge-enabled

#3858 fix(lambda): environment var values are strings
  allowed-breaking-changes.txt
  packages/@aws-cdk/aws-lambda/lib/function.ts
Labels: automerge-enabled

#3863 fix(init-templates): fix to include environments and CDK files to .gitignore for Python templates
  packages/aws-cdk/lib/init-templates/sample-app/python/.gitignore
Labels: automerge-enabled

#3855 fix(codepipeline): insufficient deploy cross-account CFN role S3 permissions
  packages/@aws-cdk/aws-codepipeline-actions/lib/cloudformation/pipeline-actions.ts
  packages/@aws-cdk/aws-codepipeline-actions/test/cloudformation/test.cloudformation-pipeline-actions.ts
Labels: automerge-enabled, do-not-merge

#3880 fix(s3-deployment): CallerReference has to be unique
  packages/@aws-cdk/aws-s3-deployment/lambda/src/index.py
  packages/@aws-cdk/aws-s3-deployment/lambda/test/test.py
Labels: automerge-enabled
