Repository aws/aws-cdk, pull requests merged in 2019-12, with the labels that each got.

#5338 chore(lambda): improve tsdoc for handler property
  packages/@aws-cdk/aws-lambda/lib/function.ts
Labels: contribution/core

#5339 feat(cloudformation): update Resource Specification to v10.0.0
  packages/@aws-cdk/aws-accessanalyzer/.gitignore
  packages/@aws-cdk/aws-accessanalyzer/.npmignore
  packages/@aws-cdk/aws-accessanalyzer/LICENSE
  packages/@aws-cdk/aws-accessanalyzer/NOTICE
  packages/@aws-cdk/aws-accessanalyzer/README.md
  packages/@aws-cdk/aws-accessanalyzer/lib/index.ts
  packages/@aws-cdk/aws-accessanalyzer/package.json
  packages/@aws-cdk/aws-accessanalyzer/test/test.accessanalyzer.ts
  packages/@aws-cdk/aws-eventschemas/.gitignore
  packages/@aws-cdk/aws-eventschemas/.npmignore
  packages/@aws-cdk/aws-eventschemas/LICENSE
  packages/@aws-cdk/aws-eventschemas/NOTICE
  packages/@aws-cdk/aws-eventschemas/README.md
  packages/@aws-cdk/aws-eventschemas/lib/index.ts
  packages/@aws-cdk/aws-eventschemas/package.json
  packages/@aws-cdk/aws-eventschemas/test/test.eventschemas.ts
  packages/@aws-cdk/cfnspec/CHANGELOG.md
  packages/@aws-cdk/cfnspec/spec-source/000_CloudFormationResourceSpecification.json
  packages/@aws-cdk/core/package.json
  packages/decdk/package.json
  yarn.lock
Labels: contribution/core

#5284 fix: this.node.addError does not cause `cdk diff` to fail #4700
  packages/aws-cdk/lib/cdk-toolkit.ts
  packages/aws-cdk/test/test.diff.ts
Labels: pr-status/do-not-merge

#5127 docs: update pre-requisite information about .NET
  CONTRIBUTING.md
Labels: contribution/core

#5325 fix(init-templates): use pytest for Python sample-app init template
  packages/aws-cdk/lib/init-templates/sample-app/python/tests/unit/test_%name%_stack.template.py
Labels: contribution/core

#5230 fix(route53): return plain hosted zone id without /hostedzone/ prefix
  packages/@aws-cdk/aws-ecs-patterns/test/fargate/test.load-balanced-fargate-service.ts
  packages/@aws-cdk/aws-route53/lib/hosted-zone-ref.ts
  packages/@aws-cdk/aws-route53/lib/hosted-zone.ts
  packages/@aws-cdk/aws-route53/lib/util.ts
  packages/@aws-cdk/aws-route53/test/test.hosted-zone-provider.ts
  packages/@aws-cdk/aws-route53/test/test.hosted-zone.ts
Labels: pr-status/do-not-merge

#4820 feat(ecs-patterns): healthyPercent on ALB, NLB, Fargate
  packages/@aws-cdk/aws-ecs-patterns/lib/base/application-load-balanced-service-base.ts
  packages/@aws-cdk/aws-ecs-patterns/lib/base/network-load-balanced-service-base.ts
  packages/@aws-cdk/aws-ecs-patterns/lib/ecs/application-load-balanced-ecs-service.ts
  packages/@aws-cdk/aws-ecs-patterns/lib/ecs/network-load-balanced-ecs-service.ts
  packages/@aws-cdk/aws-ecs-patterns/lib/fargate/application-load-balanced-fargate-service.ts
  packages/@aws-cdk/aws-ecs-patterns/lib/fargate/network-load-balanced-fargate-service.ts
  packages/@aws-cdk/aws-ecs-patterns/test/ec2/test.l3s.ts
Labels: package/ecs

#5404 chore: normalize line endings of .bat files
  packages/aws-cdk/lib/init-templates/app/python/source.bat
  packages/aws-cdk/lib/init-templates/sample-app/python/source.bat
Labels: contribution/core

#5405 refactor(elbv2): introduce ListenerCertificate
  packages/@aws-cdk/aws-ecs-patterns/lib/base/application-load-balanced-service-base.ts
  packages/@aws-cdk/aws-elasticloadbalancingv2/lib/alb/application-listener-certificate.ts
  packages/@aws-cdk/aws-elasticloadbalancingv2/lib/alb/application-listener.ts
  packages/@aws-cdk/aws-elasticloadbalancingv2/lib/index.ts
  packages/@aws-cdk/aws-elasticloadbalancingv2/lib/nlb/network-listener.ts
  packages/@aws-cdk/aws-elasticloadbalancingv2/lib/shared/listener-certificate.ts
  packages/@aws-cdk/aws-elasticloadbalancingv2/package.json
  packages/@aws-cdk/aws-elasticloadbalancingv2/test/alb/test.listener.ts
  packages/@aws-cdk/aws-elasticloadbalancingv2/test/nlb/test.listener.ts
Labels: contribution/core

#5402 feat(ecs): Add support for deployment controller
  packages/@aws-cdk/aws-ecs/lib/base/base-service.ts
  packages/@aws-cdk/aws-ecs/test/ec2/test.ec2-service.ts
  packages/@aws-cdk/aws-ecs/test/fargate/test.fargate-service.ts
Labels: package/ecs

#5418 feat(ssm): document `fromStringListParameterName` return type
  packages/@aws-cdk/aws-ssm/lib/parameter.ts
Labels: contribution/core

#5431 feat(cfnspec): Update CloudFormation spec to v10.1.0
  packages/@aws-cdk/cfnspec/CHANGELOG.md
  packages/@aws-cdk/cfnspec/spec-source/000_CloudFormationResourceSpecification.json
Labels: contribution/core

#5432 chore: bump jsii to 0.20.11
  package.json
  packages/decdk/package.json
  tools/awslint/lib/linter.ts
  tools/awslint/package.json
  tools/cdk-build-tools/package.json
  yarn.lock
Labels: contribution/core

#5408 fix(sfn): Task `parameters` property does nothing
  packages/@aws-cdk/aws-stepfunctions/lib/states/task.ts
  packages/@aws-cdk/aws-stepfunctions/lib/step-functions-task.ts
  packages/@aws-cdk/aws-stepfunctions/lib/util.ts
  packages/@aws-cdk/aws-stepfunctions/test/test.state-machine-resources.ts
Labels: contribution/core

#5083 feat(ecs-patterns): higher-level constructs for ECS service with multiple target groups
  packages/@aws-cdk/aws-ecs-patterns/README.md
  packages/@aws-cdk/aws-ecs-patterns/lib/base/application-multiple-target-groups-service-base.ts
  packages/@aws-cdk/aws-ecs-patterns/lib/base/network-multiple-target-groups-service-base.ts
  packages/@aws-cdk/aws-ecs-patterns/lib/ecs/application-multiple-target-groups-ecs-service.ts
  packages/@aws-cdk/aws-ecs-patterns/lib/ecs/network-multiple-target-groups-ecs-service.ts
  packages/@aws-cdk/aws-ecs-patterns/lib/fargate/application-multiple-target-groups-fargate-service.ts
  packages/@aws-cdk/aws-ecs-patterns/lib/fargate/network-multiple-target-groups-fargate-service.ts
  packages/@aws-cdk/aws-ecs-patterns/lib/index.ts
  packages/@aws-cdk/aws-ecs-patterns/test/ec2/integ.multiple-application-load-balanced-ecs-service.expected.json
  packages/@aws-cdk/aws-ecs-patterns/test/ec2/integ.multiple-application-load-balanced-ecs-service.ts
  packages/@aws-cdk/aws-ecs-patterns/test/ec2/test.l3s-v2.ts
  packages/@aws-cdk/aws-ecs-patterns/test/ec2/test.l3s.ts
  packages/@aws-cdk/aws-ecs-patterns/test/fargate/integ.multiple-network-load-balanced-fargate-service.expected.json
  packages/@aws-cdk/aws-ecs-patterns/test/fargate/integ.multiple-network-load-balanced-fargate-service.ts
  packages/@aws-cdk/aws-ecs-patterns/test/fargate/test.load-balanced-fargate-service-v2.ts
  packages/@aws-cdk/aws-ecs-patterns/test/fargate/test.load-balanced-fargate-service.ts
  packages/@aws-cdk/aws-ecs/lib/base/task-definition.ts
  packages/@aws-cdk/aws-ecs/lib/container-definition.ts
Labels: package/ecs-patterns

#4938 fix(ec2): Allow ingress to VPC interface endpoints
  packages/@aws-cdk/aws-ec2/lib/security-group.ts
  packages/@aws-cdk/aws-ec2/lib/vpc-endpoint.ts
  packages/@aws-cdk/aws-ec2/lib/vpc.ts
  packages/@aws-cdk/aws-ec2/test/integ.vpc-endpoint.lit.expected.json
  packages/@aws-cdk/aws-ec2/test/integ.vpc-endpoint.lit.ts
  packages/@aws-cdk/aws-ec2/test/test.vpc-endpoint.ts
  packages/@aws-cdk/cx-api/lib/context/vpc.ts
  packages/aws-cdk/lib/context-providers/vpcs.ts
  packages/aws-cdk/test/context-providers/test.asymmetric-vpcs.ts
  packages/aws-cdk/test/context-providers/test.vpcs.ts
Labels: SECURITY, pr-status/do-not-merge

#5485 fix(tests): flaky integration tests in release pipeline
  packages/aws-cdk/test/integ/cli/common.bash
Labels: contribution/core

#5295 feat(cli): support custom CA certificate bundles
  packages/aws-cdk/bin/cdk.ts
  packages/aws-cdk/lib/api/util/sdk.ts
  packages/aws-cdk/package.json
Labels: pr-status/do-not-merge

#5281 feat(rds): more extensive secret rotation support
  packages/@aws-cdk/aws-rds/README.md
  packages/@aws-cdk/aws-rds/lib/cluster.ts
  packages/@aws-cdk/aws-rds/lib/index.ts
  packages/@aws-cdk/aws-rds/lib/instance.ts
  packages/@aws-cdk/aws-rds/lib/props.ts
  packages/@aws-cdk/aws-rds/lib/secret-rotation.ts
  packages/@aws-cdk/aws-rds/package.json
  packages/@aws-cdk/aws-rds/test/integ.cluster-rotation.lit.expected.json
  packages/@aws-cdk/aws-rds/test/integ.cluster-rotation.lit.ts
  packages/@aws-cdk/aws-rds/test/integ.cluster.expected.json
  packages/@aws-cdk/aws-rds/test/integ.cluster.ts
  packages/@aws-cdk/aws-rds/test/integ.instance.lit.expected.json
  packages/@aws-cdk/aws-rds/test/integ.instance.lit.ts
  packages/@aws-cdk/aws-rds/test/test.cluster.ts
  packages/@aws-cdk/aws-rds/test/test.instance.ts
  packages/@aws-cdk/aws-rds/test/test.secret-rotation.ts
  packages/@aws-cdk/aws-secretsmanager/README.md
  packages/@aws-cdk/aws-secretsmanager/lib/index.ts
  packages/@aws-cdk/aws-secretsmanager/lib/policy.ts
  packages/@aws-cdk/aws-secretsmanager/lib/secret-rotation.ts
  packages/@aws-cdk/aws-secretsmanager/lib/secret.ts
  packages/@aws-cdk/aws-secretsmanager/package.json
  packages/@aws-cdk/aws-secretsmanager/test/test.secret-rotation.ts
  packages/@aws-cdk/aws-secretsmanager/test/test.secret.ts
Labels: pr-status/do-not-merge

#5085 docs(alb): ALB requires region to use logging
  packages/@aws-cdk/aws-elasticloadbalancingv2/lib/alb/application-load-balancer.ts
Labels: contribution/core

#5504 chore: fix occasional timeouts in role assumption
  packages/aws-cdk/test/integ/cli/test-cdk-deploy-with-role.sh
Labels: contribution/core

#5528 chore(build): resolve eslint plugins relative to cdk-build-tools
  tools/cdk-build-tools/lib/compile.ts
Labels: contribution/core

#5529 chore: fix lambda destination api break error
  allowed-breaking-changes.txt
Labels: contribution/core

#5507 fix(autoscaling): every deployment resets capacity
  packages/@aws-cdk/aws-autoscaling/lib/auto-scaling-group.ts
  packages/@aws-cdk/aws-autoscaling/test/integ.amazonlinux2.expected.json
  packages/@aws-cdk/aws-autoscaling/test/integ.asg-w-classic-loadbalancer.expected.json
  packages/@aws-cdk/aws-autoscaling/test/integ.asg-w-elbv2.expected.json
  packages/@aws-cdk/aws-autoscaling/test/integ.custom-scaling.expected.json
  packages/@aws-cdk/aws-autoscaling/test/integ.external-role.expected.json
  packages/@aws-cdk/aws-autoscaling/test/integ.spot-instances.expected.json
  packages/@aws-cdk/aws-autoscaling/test/test.auto-scaling-group.ts
  packages/@aws-cdk/aws-autoscaling/test/test.scheduled-action.ts
  packages/@aws-cdk/aws-codedeploy/test/server/integ.deployment-group.expected.json
  packages/@aws-cdk/aws-ecs-patterns/test/ec2/integ.multiple-application-load-balanced-ecs-service.expected.json
  packages/@aws-cdk/aws-ecs-patterns/test/ec2/integ.scheduled-ecs-task.lit.expected.json
  packages/@aws-cdk/aws-ecs/test/ec2/integ.app-mesh-proxy-config.expected.json
  packages/@aws-cdk/aws-ecs/test/ec2/integ.clb-host-nw.expected.json
  packages/@aws-cdk/aws-ecs/test/ec2/integ.lb-awsvpc-nw.expected.json
  packages/@aws-cdk/aws-ecs/test/ec2/integ.lb-bridge-nw.expected.json
  packages/@aws-cdk/aws-ecs/test/ec2/integ.sd-awsvpc-nw.expected.json
  packages/@aws-cdk/aws-ecs/test/ec2/integ.sd-bridge-nw.expected.json
  packages/@aws-cdk/aws-ecs/test/ec2/integ.spot-drain.expected.json
  packages/@aws-cdk/aws-ecs/test/test.ecs-cluster.ts
  packages/@aws-cdk/aws-eks/test/integ.eks-spot.expected.json
  packages/@aws-cdk/aws-events-targets/test/ecs/integ.event-ec2-task.lit.expected.json
  packages/@aws-cdk/aws-stepfunctions-tasks/test/integ.ec2-task.expected.json
  yarn.lock
Labels: contribution/core

#5525 feat(custom-resources): ignore DELETE after failed CREATE
  packages/@aws-cdk/custom-resources/README.md
  packages/@aws-cdk/custom-resources/lib/provider-framework/runtime/cfn-response.ts
  packages/@aws-cdk/custom-resources/test/provider-framework/integ.provider.expected.json
  packages/@aws-cdk/custom-resources/test/provider-framework/runtime.test.ts
Labels: contribution/core

#5542 feat(cloudformation): update cloudformation spec to v10.2.0
  packages/@aws-cdk/cfnspec/CHANGELOG.md
  packages/@aws-cdk/cfnspec/spec-source/000_CloudFormationResourceSpecification.json
Labels: contribution/core

#5568 fix(iam): policy added to resource for immutable Role
  packages/@aws-cdk/aws-iam/lib/role.ts
  packages/@aws-cdk/aws-iam/test/role.from-role-arn.test.ts
Labels: contribution/core

#5580 feat(logs): import a LogGroup from its name
  packages/@aws-cdk/aws-logs/lib/log-group.ts
  packages/@aws-cdk/aws-logs/test/test.loggroup.ts
Labels: contribution/core

#5541 fix(codebuild): ARM images have the wrong type and compute kind
  packages/@aws-cdk/aws-codebuild/lib/project.ts
  packages/@aws-cdk/aws-codebuild/test/test.codebuild.ts
Labels: contribution/core
