Repository aws/aws-cdk, pull requests merged in 2020-05, with the labels that each got.

#7674 fix(cli): CLI can't be used in Lambda Function
  packages/aws-cdk/lib/api/aws-auth/account-cache.ts
  packages/aws-cdk/lib/init.ts
  packages/aws-cdk/lib/util/directories.ts
  packages/aws-cdk/lib/version.ts
  packages/aws-cdk/test/account-cache.test.ts
  packages/aws-cdk/test/version.test.ts
Labels: contribution/core

#7708 feat(core): move all types from "assets" to "core"
  package.json
  packages/@aws-cdk/assets/README.md
  packages/@aws-cdk/assets/lib/compat.ts
  packages/@aws-cdk/assets/lib/fs/follow-mode.ts
  packages/@aws-cdk/assets/lib/fs/index.ts
  packages/@aws-cdk/assets/lib/fs/options.ts
  packages/@aws-cdk/assets/lib/index.ts
  packages/@aws-cdk/assets/lib/staging.ts
  packages/@aws-cdk/assets/package.json
  packages/@aws-cdk/assets/test/test.compat.ts
  packages/@aws-cdk/aws-elasticloadbalancingv2-targets/package.json
  packages/@aws-cdk/core/lib/asset-staging.ts
  packages/@aws-cdk/core/lib/fs/copy.ts
  packages/@aws-cdk/core/lib/fs/fingerprint.ts
  packages/@aws-cdk/core/lib/fs/index.ts
  packages/@aws-cdk/core/lib/fs/options.ts
  packages/@aws-cdk/core/lib/fs/utils.ts
  packages/@aws-cdk/core/lib/index.ts
  packages/@aws-cdk/core/package.json
  packages/@aws-cdk/core/test/fs/.gitignore
  packages/@aws-cdk/core/test/fs/fixtures.tar.gz
  packages/@aws-cdk/core/test/fs/test.fs-copy.ts
  packages/@aws-cdk/core/test/fs/test.fs-fingerprint.ts
  packages/@aws-cdk/core/test/fs/test.utils.ts
  packages/@aws-cdk/core/test/test.staging.ts
  tools/cdk-build-tools/config/nyc.config.js
Labels: contribution/core

#7737 chore: handle `EROFS` error
  packages/aws-cdk/lib/api/aws-auth/account-cache.ts
Labels: contribution/core

#7764 chore(sqs): clear linter exclusions
  packages/@aws-cdk/aws-sqs/lib/policy.ts
  packages/@aws-cdk/aws-sqs/lib/queue-base.ts
  packages/@aws-cdk/aws-sqs/lib/queue.ts
  packages/@aws-cdk/aws-sqs/package.json
Labels: @aws-cdk/aws-sqs, contribution/core

#7763 chore(sns): clear docs linter exclusions
  packages/@aws-cdk/aws-sns/lib/policy.ts
  packages/@aws-cdk/aws-sns/lib/subscriber.ts
  packages/@aws-cdk/aws-sns/lib/subscription-filter.ts
  packages/@aws-cdk/aws-sns/lib/topic-base.ts
  packages/@aws-cdk/aws-sns/lib/topic.ts
  packages/@aws-cdk/aws-sns/package.json
Labels: @aws-cdk/aws-sns, contribution/core

#7760 fix(eks): impossible to define multiple spot capacities
  packages/@aws-cdk/aws-eks/lib/cluster.ts
  packages/@aws-cdk/aws-eks/test/test.cluster.ts
Labels: contribution/core

#7770 fix(ec2): `new Instance` fails in lookup Vpc
  packages/@aws-cdk/aws-ec2/lib/instance.ts
  packages/@aws-cdk/aws-ec2/test/test.vpc.from-lookup.ts
Labels: contribution/core

#7769 fix(ec2): NAT instances don't route ICMP or UDP
  packages/@aws-cdk/aws-ec2/README.md
  packages/@aws-cdk/aws-ec2/lib/nat.ts
  packages/@aws-cdk/aws-ec2/test/integ.nat-instances.lit.expected.json
  packages/@aws-cdk/aws-ec2/test/test.vpc.ts
Labels: contribution/core

#7731 fix(cli): cdk deploy cannot update stacks in REVIEW_IN_PROGRESS status
  packages/aws-cdk/lib/api/deploy-stack.ts
  packages/aws-cdk/test/api/deploy-stack.test.ts
Labels: contribution/core, package/tools

#7786 chore(cli): add termination-protection stack to `cdk ls` test
  packages/aws-cdk/test/integ/cli/test-cdk-ls.sh
Labels: contribution/core, package/tools

#7789 chore(cli): fix CLI integ test expectations
  packages/aws-cdk/test/integ/cli/test-cdk-ls.sh
Labels: contribution/core, package/tools

#7791 chore(cli): removing incorrectly merged duplicate entry in test
  packages/aws-cdk/test/integ/cli/test-cdk-ls.sh
Labels: contribution/core, package/tools

#7793 chore(sns-subscriptions): clear linter exclusions
  packages/@aws-cdk/aws-sns-subscriptions/lib/email.ts
  packages/@aws-cdk/aws-sns-subscriptions/lib/lambda.ts
  packages/@aws-cdk/aws-sns-subscriptions/lib/sqs.ts
  packages/@aws-cdk/aws-sns-subscriptions/lib/subscription.ts
  packages/@aws-cdk/aws-sns-subscriptions/lib/url.ts
  packages/@aws-cdk/aws-sns-subscriptions/package.json
Labels: @aws-cdk/aws-sns-subscriptions, contribution/core

#7703 fix(iam): principal with implicit conditions overwrite each other
  packages/@aws-cdk/aws-iam/lib/policy-statement.ts
  packages/@aws-cdk/aws-iam/test/principals.test.ts
Labels: contribution/core

#7772 fix(ec2): default gateway endpoint fails without private subnets
  packages/@aws-cdk/aws-ec2/lib/util.ts
  packages/@aws-cdk/aws-ec2/lib/vpc-endpoint.ts
  packages/@aws-cdk/aws-ec2/lib/vpc.ts
  packages/@aws-cdk/aws-ec2/test/integ.vpc-endpoint.lit.expected.json
  packages/@aws-cdk/aws-ec2/test/test.vpc-endpoint.ts
Labels: contribution/core

#7808 chore: merge release/1.37.0 to master
  CHANGELOG.md
  lerna.json
Labels: contribution/core, pr/no-squash

#7773 feat(core): custom resource provider helper
  packages/@aws-cdk/aws-cloudformation/test/core-custom-resource-provider-fixture/index.ts
  packages/@aws-cdk/aws-cloudformation/test/integ.core-custom-resources.expected.json
  packages/@aws-cdk/aws-cloudformation/test/integ.core-custom-resources.ts
  packages/@aws-cdk/core/README.md
  packages/@aws-cdk/core/lib/custom-resource-provider/custom-resource-provider.ts
  packages/@aws-cdk/core/lib/custom-resource-provider/index.ts
  packages/@aws-cdk/core/lib/custom-resource-provider/nodejs-entrypoint.ts
  packages/@aws-cdk/core/lib/index.ts
  packages/@aws-cdk/core/test/custom-resource-provider/mock-provider/index.ts
  packages/@aws-cdk/core/test/custom-resource-provider/test.custom-resource-provider.ts
  packages/@aws-cdk/core/test/custom-resource-provider/test.nodejs-entrypoint.ts
  packages/@aws-cdk/core/test/integration.custom-resources.readme
Labels: contribution/core

#7130 fix(ecs): blank taskDefinition and launchType when using external deployment controller
  packages/@aws-cdk/aws-ecs/lib/base/base-service.ts
  packages/@aws-cdk/aws-ecs/lib/ec2/ec2-service.ts
  packages/@aws-cdk/aws-ecs/lib/fargate/fargate-service.ts
  packages/@aws-cdk/aws-ecs/test/ec2/test.ec2-service.ts
  packages/@aws-cdk/aws-ecs/test/fargate/test.fargate-service.ts
Labels: @aws-cdk/aws-ecs

#7814 fix(ecs): update minHealthyPercent validation for ec2service
  packages/@aws-cdk/aws-ecs/lib/ec2/ec2-service.ts
  packages/@aws-cdk/aws-ecs/test/ec2/test.ec2-service.ts
Labels: @aws-cdk/aws-ecs

#7819 chore: remove keywords for `cloudlib` from `package.json`
  packages/@aws-cdk/aws-codepipeline-actions/package.json
  packages/@aws-cdk/aws-codepipeline/package.json
  packages/@aws-cdk/aws-elasticloadbalancingv2-targets/package.json
  packages/@aws-cdk/aws-events-targets/package.json
  packages/@aws-cdk/aws-events/package.json
  packages/@aws-cdk/aws-iam/package.json
Labels: contribution/core

#7818 chore(stepfunctions-tasks): fix up the keywords in `package.json`
  packages/@aws-cdk/aws-stepfunctions-tasks/package.json
Labels: @aws-cdk/aws-stepfunctions-tasks, contribution/core

#7820 chore: update .NET Core version in contributing.md
  CONTRIBUTING.md
Labels: contribution/core

#7817 docs(stepfunctions-tasks): add section to explain paths and their usage with tasks
  packages/@aws-cdk/aws-stepfunctions-tasks/README.md
Labels: @aws-cdk/aws-stepfunctions-tasks, contribution/core

#7815 docs(stepfunctions): update ts example state machine
  packages/@aws-cdk/aws-stepfunctions/README.md
Labels: @aws-cdk/aws-stepfunctions, contribution/core

#7798 fix(cli): parameter reuse is not configurable
  packages/aws-cdk/bin/cdk.ts
  packages/aws-cdk/lib/api/cloudformation-deployments.ts
  packages/aws-cdk/lib/api/deploy-stack.ts
  packages/aws-cdk/lib/cdk-toolkit.ts
  packages/aws-cdk/test/api/deploy-stack.test.ts
Labels: contribution/core

#7587 fix(aws-batch): gpuCount was ignored in JobDefinition creation
  packages/@aws-cdk/aws-batch/lib/job-definition.ts
  packages/@aws-cdk/aws-batch/test/job-definition.test.ts
Labels: @aws-cdk/aws-batch

#7823 chore: force resolution of tap-mocha-reporter
  package.json
  yarn.lock
Labels: contribution/core

#7822 feat(cfnspec): cloudformation spec v14.1.0
  packages/@aws-cdk/cfnspec/CHANGELOG.md
  packages/@aws-cdk/cfnspec/cfn.version
  packages/@aws-cdk/cfnspec/spec-source/000_CloudFormationResourceSpecification.json
Labels: pr-linter/exempt-test

#7803 feat(iam): openid connect provider
  packages/@aws-cdk/aws-iam/README.md
  packages/@aws-cdk/aws-iam/lib/index.ts
  packages/@aws-cdk/aws-iam/lib/oidc-provider.ts
  packages/@aws-cdk/aws-iam/lib/oidc-provider/diff.ts
  packages/@aws-cdk/aws-iam/lib/oidc-provider/external.ts
  packages/@aws-cdk/aws-iam/lib/oidc-provider/index.ts
  packages/@aws-cdk/aws-iam/package.json
  packages/@aws-cdk/aws-iam/test/integ.oidc-provider.expected.json
  packages/@aws-cdk/aws-iam/test/integ.oidc-provider.ts
  packages/@aws-cdk/aws-iam/test/oidc-provider.test.ts
Labels: contribution/core

#7782 chore(repo): Remove dry run from stale github action
  .github/workflows/close-stale-issues.yml
Labels: contribution/core

#7830 fix(eks): "vendor response doesn't contain attribute" when updating version
  packages/@aws-cdk/aws-eks/lib/cluster-resource-handler/cluster.ts
  packages/@aws-cdk/aws-eks/test/integ.eks-cluster.expected.json
  packages/@aws-cdk/aws-eks/test/integ.eks-cluster.ts
  packages/@aws-cdk/aws-eks/test/test.cluster-resource-provider.ts
Labels: contribution/core

#7691 feat(codebuild): add support for test reports
  packages/@aws-cdk/aws-codebuild/README.md
  packages/@aws-cdk/aws-codebuild/lib/index.ts
  packages/@aws-cdk/aws-codebuild/lib/project.ts
  packages/@aws-cdk/aws-codebuild/lib/report-group-utils.ts
  packages/@aws-cdk/aws-codebuild/lib/report-group.ts
  packages/@aws-cdk/aws-codebuild/test/integ.caching.ts
  packages/@aws-cdk/aws-codebuild/test/integ.defaults.lit.expected.json
  packages/@aws-cdk/aws-codebuild/test/integ.docker-asset.lit.ts
  packages/@aws-cdk/aws-codebuild/test/integ.docker-registry.lit.ts
  packages/@aws-cdk/aws-codebuild/test/integ.ecr.lit.ts
  packages/@aws-cdk/aws-codebuild/test/integ.github.ts
  packages/@aws-cdk/aws-codebuild/test/integ.project-bucket.ts
  packages/@aws-cdk/aws-codebuild/test/integ.project-buildspec-artifacts.ts
  packages/@aws-cdk/aws-codebuild/test/integ.project-file-system-location.ts
  packages/@aws-cdk/aws-codebuild/test/integ.project-secondary-sources-artifacts.ts
  packages/@aws-cdk/aws-codebuild/test/integ.project-vpc.ts
  packages/@aws-cdk/aws-codebuild/test/test.codebuild.ts
  packages/@aws-cdk/aws-codebuild/test/test.project.ts
  packages/@aws-cdk/aws-codebuild/test/test.report-group.ts
  packages/@aws-cdk/aws-codepipeline-actions/test/integ.lambda-deployed-through-codepipeline.lit.expected.json
  packages/@aws-cdk/aws-codepipeline-actions/test/integ.pipeline-code-build-multiple-inputs-outputs.ts
  packages/@aws-cdk/aws-codepipeline-actions/test/integ.pipeline-code-commit-build.ts
  packages/@aws-cdk/aws-codepipeline-actions/test/integ.pipeline-ecs-deploy.ts
  packages/@aws-cdk/aws-codepipeline-actions/test/integ.pipeline-events.ts
  packages/@aws-cdk/aws-codepipeline-actions/test/test.pipeline.ts
  packages/@aws-cdk/aws-events-targets/test/codebuild/integ.project-events.expected.json
  packages/decdk/test/__snapshots__/synth.test.js.snap
Labels: contribution/core

#7792 feat(stepfunctions): custom state as an escape hatch
  packages/@aws-cdk/aws-stepfunctions/README.md
  packages/@aws-cdk/aws-stepfunctions/lib/index.ts
  packages/@aws-cdk/aws-stepfunctions/lib/states/custom-state.ts
  packages/@aws-cdk/aws-stepfunctions/test/custom-state.test.ts
  packages/@aws-cdk/aws-stepfunctions/test/integ.custom-state.expected.json
  packages/@aws-cdk/aws-stepfunctions/test/integ.custom-state.ts
Labels: @aws-cdk/aws-stepfunctions, contribution/core

#7317 fix(ecs): update logic for secret JSON field with fargate task to fail
  packages/@aws-cdk/aws-ecs/lib/base/task-definition.ts
  packages/@aws-cdk/aws-ecs/lib/container-definition.ts
  packages/@aws-cdk/aws-ecs/lib/firelens-log-router.ts
  packages/@aws-cdk/aws-ecs/package.json
  packages/@aws-cdk/aws-ecs/test/ec2/integ.secret-json-field.expected.json
  packages/@aws-cdk/aws-ecs/test/ec2/integ.secret-json-field.ts
  packages/@aws-cdk/aws-ecs/test/fargate/integ.secret.expected.json
  packages/@aws-cdk/aws-ecs/test/fargate/integ.secret.ts
  packages/@aws-cdk/aws-ecs/test/test.container-definition.ts
Labels: @aws-cdk/aws-ecs

#7840 chore(core): docs refer to "createNamingScheme" which was renamed to "allocateLogicalId"
  packages/@aws-cdk/core/lib/stack.ts
Labels: contribution/core

#7829 chore(cli): re-enable regression tests
  packages/aws-cdk/package.json
  packages/aws-cdk/scripts/integ-cli-no-regression.sh
  packages/aws-cdk/scripts/integ-cli-regression.sh
  packages/aws-cdk/scripts/integ-cli.sh
  packages/aws-cdk/test/integ/run-against-dist
  packages/aws-cdk/test/integ/run-against-dist.bash
  packages/aws-cdk/test/integ/test-cli-regression-against-current-code.sh
  packages/aws-cdk/test/integ/test-cli-regression-against-latest-release.sh
Labels: contribution/core

#7800 chore: move context queries to cloud assembly schema
  allowed-breaking-changes.txt
  packages/@aws-cdk/aws-cloudformation/test/test.nested-stack.ts
  packages/@aws-cdk/aws-ec2/lib/machine-image.ts
  packages/@aws-cdk/aws-ec2/lib/vpc.ts
  packages/@aws-cdk/aws-ec2/package.json
  packages/@aws-cdk/aws-ec2/test/test.vpc.from-lookup.ts
  packages/@aws-cdk/aws-route53/lib/hosted-zone.ts
  packages/@aws-cdk/aws-route53/package.json
  packages/@aws-cdk/aws-ssm/lib/parameter.ts
  packages/@aws-cdk/aws-ssm/package.json
  packages/@aws-cdk/cloud-assembly-schema/lib/context-queries.ts
  packages/@aws-cdk/cloud-assembly-schema/lib/index.ts
  packages/@aws-cdk/cloud-assembly-schema/lib/schema.ts
  packages/@aws-cdk/cloud-assembly-schema/schema/cloud-assembly.schema.json
  packages/@aws-cdk/cloud-assembly-schema/schema/cloud-assembly.version.json
  packages/@aws-cdk/core/lib/context-provider.ts
  packages/@aws-cdk/core/lib/stack.ts
  packages/@aws-cdk/core/test/test.app.ts
  packages/@aws-cdk/core/test/test.context.ts
  packages/@aws-cdk/cx-api/lib/cloud-assembly.ts
  packages/@aws-cdk/cx-api/lib/context/ami.ts
  packages/@aws-cdk/cx-api/lib/context/availability-zones.ts
  packages/@aws-cdk/cx-api/lib/context/hosted-zone.ts
  packages/@aws-cdk/cx-api/lib/context/ssm-parameter.ts
  packages/@aws-cdk/cx-api/lib/context/vpc.ts
  packages/@aws-cdk/cx-api/lib/index.ts
  packages/@aws-cdk/cx-api/test/__snapshots__/cloud-assembly.test.js.snap
  packages/@aws-cdk/cx-api/test/cloud-assembly-builder.test.ts
  packages/@aws-cdk/cx-api/test/fixtures/missing-context/manifest.json
  packages/aws-cdk/lib/context-providers/ami.ts
  packages/aws-cdk/lib/context-providers/availability-zones.ts
  packages/aws-cdk/lib/context-providers/hosted-zones.ts
  packages/aws-cdk/lib/context-providers/index.ts
  packages/aws-cdk/lib/context-providers/ssm-parameters.ts
  packages/aws-cdk/lib/context-providers/vpcs.ts
  packages/aws-cdk/test/api/cloud-executable.test.ts
  packages/aws-cdk/test/context-providers/asymmetric-vpcs.test.ts
  packages/aws-cdk/test/context-providers/generic.test.ts
  packages/aws-cdk/test/context-providers/vpcs.test.ts
Labels: contribution/core

#7846 chore(cli): fix nested stack integ test collision
  packages/aws-cdk/test/integ/cli.exclusions.js
  packages/aws-cdk/test/integ/cli/app/app.js
  packages/aws-cdk/test/integ/cli/app/nested-stack.js
Labels: contribution/core

#7850 feat(ecs): support multiple security groups when creating an ec2 or fargate service
  packages/@aws-cdk/aws-ecs/README.md
  packages/@aws-cdk/aws-ecs/lib/base/base-service.ts
  packages/@aws-cdk/aws-ecs/lib/ec2/ec2-service.ts
  packages/@aws-cdk/aws-ecs/lib/fargate/fargate-service.ts
  packages/@aws-cdk/aws-ecs/test/ec2/test.ec2-service.ts
  packages/@aws-cdk/aws-ecs/test/fargate/test.fargate-service.ts
Labels: @aws-cdk/aws-ecs

#7854 chore(cli): fix cli integ output tests
  packages/aws-cdk/test/integ/cli/app/app.js
  packages/aws-cdk/test/integ/cli/cdk-deploy-wildcard-with-outputs-expected.template
  packages/aws-cdk/test/integ/cli/cdk-deploy-with-outputs-expected.template
Labels: contribution/core

#7855 chore(cli): exclude outputs test from regression suite
  packages/aws-cdk/test/integ/cli.exclusions.js
Labels: contribution/core

#7748 feat: add an example construct package
  CONTRIBUTING.md
  packages/@aws-cdk/example-construct-library/.eslintrc.js
  packages/@aws-cdk/example-construct-library/.gitignore
  packages/@aws-cdk/example-construct-library/.npmignore
  packages/@aws-cdk/example-construct-library/LICENSE
  packages/@aws-cdk/example-construct-library/NOTICE
  packages/@aws-cdk/example-construct-library/README.md
  packages/@aws-cdk/example-construct-library/lib/example-resource.ts
  packages/@aws-cdk/example-construct-library/lib/index.ts
  packages/@aws-cdk/example-construct-library/lib/private/example-resource-common.ts
  packages/@aws-cdk/example-construct-library/package.json
  packages/@aws-cdk/example-construct-library/test/example-resource.test.ts
  packages/@aws-cdk/example-construct-library/test/integ.example-resource.expected.json
  packages/@aws-cdk/example-construct-library/test/integ.example-resource.ts
  packages/decdk/deps.js
  packages/monocdk-experiment/deps.js
Labels: contribution/core

#7856 chore: upgrade jsii version to v1.5.0
  package.json
  packages/cdk-dasm/package.json
  packages/decdk/package.json
  packages/monocdk-experiment/package.json
  tools/awslint/package.json
  tools/cdk-build-tools/package.json
  tools/cfn2ts/package.json
  yarn.lock
Labels: contribution/core

#7866 chore: merge release/1.38.0 to master
  CHANGELOG.md
  lerna.json
Labels: contribution/core, pr/no-squash

#7869 chore: fix CHANGELOG
  CHANGELOG.md
Labels: contribution/core

#6366 chore: CDK apps generate asset manifest
  allowed-breaking-changes.txt
  packages/@aws-cdk/aws-ecr-assets/lib/image-asset.ts
  packages/@aws-cdk/aws-lambda/lib/code.ts
  packages/@aws-cdk/aws-s3-assets/lib/asset.ts
  packages/@aws-cdk/cdk-assets-schema/lib/aws-destination.ts
  packages/@aws-cdk/cloud-assembly-schema/lib/artifact-schema.ts
  packages/@aws-cdk/cloud-assembly-schema/lib/index.ts
  packages/@aws-cdk/cloud-assembly-schema/lib/manifest.ts
  packages/@aws-cdk/cloud-assembly-schema/lib/metadata-schema.ts
  packages/@aws-cdk/cloud-assembly-schema/lib/schema.ts
  packages/@aws-cdk/cloud-assembly-schema/schema/cloud-assembly.schema.json
  packages/@aws-cdk/cloud-assembly-schema/test/manifest.test.ts
  packages/@aws-cdk/core/lib/index.ts
  packages/@aws-cdk/core/lib/nested-stack.ts
  packages/@aws-cdk/core/lib/stack-synthesizers/_shared.ts
  packages/@aws-cdk/core/lib/stack-synthesizers/default-synthesizer.ts
  packages/@aws-cdk/core/lib/stack-synthesizers/index.ts
  packages/@aws-cdk/core/lib/stack-synthesizers/legacy.ts
  packages/@aws-cdk/core/lib/stack-synthesizers/nested.ts
  packages/@aws-cdk/core/lib/stack-synthesizers/types.ts
  packages/@aws-cdk/core/lib/stack.ts
  packages/@aws-cdk/core/package.json
  packages/@aws-cdk/core/test/evaluate-cfn.ts
  packages/@aws-cdk/core/test/stack-synthesis/test.new-style-synthesis.ts
  packages/@aws-cdk/core/test/test.app.ts
  packages/@aws-cdk/core/test/test.runtime-info.ts
  packages/@aws-cdk/cx-api/lib/asset-manifest-artifact.ts
  packages/@aws-cdk/cx-api/lib/cloud-artifact.ts
  packages/@aws-cdk/cx-api/lib/cloudformation-artifact.ts
  packages/@aws-cdk/cx-api/lib/features.ts
  packages/@aws-cdk/cx-api/lib/index.ts
  packages/@aws-cdk/cx-api/lib/placeholders.ts
  packages/@aws-cdk/cx-api/lib/tree-cloud-artifact.ts
  packages/@aws-cdk/cx-api/test/cloud-assembly.test.ts
  packages/@aws-cdk/cx-api/test/fixtures/asset-manifest/asset-dir/foo.txt
  packages/@aws-cdk/cx-api/test/fixtures/asset-manifest/assets.json
  packages/@aws-cdk/cx-api/test/fixtures/asset-manifest/docker-asset/Dockerfile
  packages/@aws-cdk/cx-api/test/fixtures/asset-manifest/manifest.json
  packages/@aws-cdk/cx-api/test/fixtures/asset-manifest/template.json
  packages/@aws-cdk/cx-api/test/placeholders.test.ts
  packages/aws-cdk/lib/api/cloudformation-deployments.ts
  packages/aws-cdk/lib/api/deploy-stack.ts
  packages/aws-cdk/lib/api/toolkit-info.ts
  packages/aws-cdk/lib/cdk-toolkit.ts
  packages/aws-cdk/test/api/cloudformation-deployments.test.ts
  packages/aws-cdk/test/api/deploy-stack.test.ts
  packages/aws-cdk/test/util.ts
  packages/aws-cdk/test/util/mock-sdk.ts
  packages/cdk-assets/lib/private/handlers/container-images.ts
  packages/cdk-assets/lib/private/placeholders.ts
  packages/cdk-assets/package.json
  packages/cdk-assets/test/mock-aws.ts
Labels: contribution/core

#7902 chore: fix termination protection
  packages/@aws-cdk/core/lib/stack-synthesizers/_shared.ts
  packages/@aws-cdk/core/test/test.stack.ts
Labels: contribution/core

#7304 feat: initial version of an improved CloudFormation template include experience
  package.json
  packages/@aws-cdk/cloudformation-include/.eslintrc.js
  packages/@aws-cdk/cloudformation-include/.gitignore
  packages/@aws-cdk/cloudformation-include/.npmignore
  packages/@aws-cdk/cloudformation-include/LICENSE
  packages/@aws-cdk/cloudformation-include/NOTICE
  packages/@aws-cdk/cloudformation-include/README.md
  packages/@aws-cdk/cloudformation-include/build.js
  packages/@aws-cdk/cloudformation-include/lib/cfn-include.ts
  packages/@aws-cdk/cloudformation-include/lib/cfn-type-to-l1-mapping.ts
  packages/@aws-cdk/cloudformation-include/lib/file-utils.ts
  packages/@aws-cdk/cloudformation-include/lib/index.ts
  packages/@aws-cdk/cloudformation-include/package.json
  packages/@aws-cdk/cloudformation-include/test/invalid-templates.test.ts
  packages/@aws-cdk/cloudformation-include/test/test-templates/bucket-with-encryption-key.json
  packages/@aws-cdk/cloudformation-include/test/test-templates/if-complex-property.json
  packages/@aws-cdk/cloudformation-include/test/test-templates/if-simple-property.json
  packages/@aws-cdk/cloudformation-include/test/test-templates/invalid/bucket-policy-without-bucket.json
  packages/@aws-cdk/cloudformation-include/test/test-templates/invalid/bucket-with-cors-rules-not-an-array.json
  packages/@aws-cdk/cloudformation-include/test/test-templates/invalid/bucket-with-cors-rules-null-element.json
  packages/@aws-cdk/cloudformation-include/test/test-templates/invalid/bucket-with-invalid-cors-rule.json
  packages/@aws-cdk/cloudformation-include/test/test-templates/non-existent-resource-type.json
  packages/@aws-cdk/cloudformation-include/test/test-templates/only-bucket-complex-props.json
  packages/@aws-cdk/cloudformation-include/test/test-templates/only-codecommit-repo-using-cfn-functions.json
  packages/@aws-cdk/cloudformation-include/test/test-templates/only-empty-bucket-with-parameters.json
  packages/@aws-cdk/cloudformation-include/test/test-templates/only-empty-bucket.json
  packages/@aws-cdk/cloudformation-include/test/test-templates/ref-array-property.json
  packages/@aws-cdk/cloudformation-include/test/test-templates/resource-attribute-condition.json
  packages/@aws-cdk/cloudformation-include/test/test-templates/resource-attribute-creation-policy.json
  packages/@aws-cdk/cloudformation-include/test/test-templates/resource-attribute-depends-on.json
  packages/@aws-cdk/cloudformation-include/test/test-templates/resource-attribute-update-policy.json
  packages/@aws-cdk/cloudformation-include/test/valid-templates.test.ts
  packages/@aws-cdk/core/lib/cfn-fn.ts
  packages/@aws-cdk/core/lib/cfn-parse.ts
  packages/@aws-cdk/core/lib/runtime.ts
  packages/@aws-cdk/core/test/test.logical-id.ts
  packages/decdk/deps.js
  packages/monocdk-experiment/package.json
  tools/cfn2ts/lib/codegen.ts
  tools/cfn2ts/lib/genspec.ts
Labels: contribution/core

#7907 chore: change CLI integ tests from Bash to TypeScript
  packages/aws-cdk/test/integ/cli/.gitignore
  packages/aws-cdk/test/integ/cli/README.md
  packages/aws-cdk/test/integ/cli/aws-helpers.ts
  packages/aws-cdk/test/integ/cli/bootstrapping.integtest.ts
  packages/aws-cdk/test/integ/cli/cdk-deploy-wildcard-with-outputs-expected.template
  packages/aws-cdk/test/integ/cli/cdk-deploy-with-outputs-expected.template
  packages/aws-cdk/test/integ/cli/cdk-helpers.ts
  packages/aws-cdk/test/integ/cli/cli.integtest.ts
  packages/aws-cdk/test/integ/cli/test-cdk-bootstrap-no-execute.sh
  packages/aws-cdk/test/integ/cli/test-cdk-context.sh
  packages/aws-cdk/test/integ/cli/test-cdk-deploy-all.sh
  packages/aws-cdk/test/integ/cli/test-cdk-deploy-nested-stack-with-parameters.sh
  packages/aws-cdk/test/integ/cli/test-cdk-deploy-no-execute.sh
  packages/aws-cdk/test/integ/cli/test-cdk-deploy-no-tty.sh
  packages/aws-cdk/test/integ/cli/test-cdk-deploy-wildcard-with-outputs.sh
  packages/aws-cdk/test/integ/cli/test-cdk-deploy-wildcard-with-parameters.sh
  packages/aws-cdk/test/integ/cli/test-cdk-deploy-with-notification-arns.sh
  packages/aws-cdk/test/integ/cli/test-cdk-deploy-with-outputs.sh
  packages/aws-cdk/test/integ/cli/test-cdk-deploy-with-parameters-multi.sh
  packages/aws-cdk/test/integ/cli/test-cdk-deploy-with-parameters.sh
  packages/aws-cdk/test/integ/cli/test-cdk-deploy-with-role.sh
  packages/aws-cdk/test/integ/cli/test-cdk-deploy.sh
  packages/aws-cdk/test/integ/cli/test-cdk-diff.sh
  packages/aws-cdk/test/integ/cli/test-cdk-docker.sh
  packages/aws-cdk/test/integ/cli/test-cdk-failed-deploy-doesnt-hang.sh
  packages/aws-cdk/test/integ/cli/test-cdk-fast-deploy.sh
  packages/aws-cdk/test/integ/cli/test-cdk-iam-diff.sh
  packages/aws-cdk/test/integ/cli/test-cdk-lambda.sh
  packages/aws-cdk/test/integ/cli/test-cdk-ls.sh
  packages/aws-cdk/test/integ/cli/test-cdk-multiple-toolkit-stacks.sh
  packages/aws-cdk/test/integ/cli/test-cdk-no-resource.sh
  packages/aws-cdk/test/integ/cli/test-cdk-order.sh
  packages/aws-cdk/test/integ/cli/test-cdk-ssm-parameter-provider-error.sh
  packages/aws-cdk/test/integ/cli/test-cdk-synth.sh
  packages/aws-cdk/test/integ/cli/test-cdk-termination-protection.sh
  packages/aws-cdk/test/integ/cli/test-cdk-version.sh
  packages/aws-cdk/test/integ/cli/test-jest.sh
  packages/aws-cdk/test/integ/cli/test-vpc-lookup.sh
Labels: contribution/core

#7774 fix(stepfunctions-tasks): EvaluateExpression is limited to expressions that contain state paths
  packages/@aws-cdk/aws-stepfunctions-tasks/lib/evaluate-expression.ts
  packages/@aws-cdk/aws-stepfunctions-tasks/test/evaluate-expression.test.ts
  packages/@aws-cdk/aws-stepfunctions-tasks/test/integ.evaluate-expression.expected.json
  packages/@aws-cdk/aws-stepfunctions-tasks/test/integ.evaluate-expression.ts
Labels: contribution/core

#7598 fix(elbv2): race condition for Lambda backends
  packages/@aws-cdk/aws-ecr/lib/repository.ts
  packages/@aws-cdk/aws-elasticloadbalancingv2-targets/lib/lambda-target.ts
  packages/@aws-cdk/aws-elasticloadbalancingv2-targets/test/integ.lambda-target.expected.json
  packages/@aws-cdk/aws-elasticloadbalancingv2-targets/test/lambda-target.test.ts
  packages/@aws-cdk/aws-iam/lib/grant.ts
  packages/@aws-cdk/aws-iam/lib/group.ts
  packages/@aws-cdk/aws-iam/lib/lazy-role.ts
  packages/@aws-cdk/aws-iam/lib/principals.ts
  packages/@aws-cdk/aws-iam/lib/private/immutable-role.ts
  packages/@aws-cdk/aws-iam/lib/role.ts
  packages/@aws-cdk/aws-iam/lib/unknown-principal.ts
  packages/@aws-cdk/aws-iam/lib/user.ts
  packages/@aws-cdk/aws-iam/test/grant.test.ts
  packages/@aws-cdk/aws-iam/test/policy-document.test.ts
  packages/@aws-cdk/aws-kms/lib/alias.ts
  packages/@aws-cdk/aws-kms/lib/key.ts
  packages/@aws-cdk/aws-lambda/lib/function-base.ts
  packages/@aws-cdk/aws-s3/lib/bucket.ts
  packages/@aws-cdk/aws-secretsmanager/lib/secret.ts
  packages/@aws-cdk/aws-sns/lib/topic-base.ts
  packages/@aws-cdk/aws-sqs/lib/queue-base.ts
Labels: contribution/core

#7926 docs(cloudfront): correct @default for CloudFrontWebDistribution priceClass
  packages/@aws-cdk/aws-cloudfront/lib/web_distribution.ts
Labels: @aws-cdk/aws-cloudfront, contribution/core

#7932 chore: fix integ tests
  packages/aws-cdk/test/integ/cli/.gitignore
  packages/aws-cdk/test/integ/cli/README.md
  packages/aws-cdk/test/integ/run-against-dist.bash
Labels: contribution/core

#7931 feat(init/java): model CDK version in property in Maven POMs
  packages/aws-cdk/lib/init-templates/app/java/pom.template.xml
  packages/aws-cdk/lib/init-templates/sample-app/java/pom.template.xml
Labels: contribution/core, pr-linter/exempt-readme, pr-linter/exempt-test

#7857 feat(events-targets): support multiple security groups for an ECS task
  packages/@aws-cdk/aws-events-targets/lib/ecs-task.ts
  packages/@aws-cdk/aws-events-targets/test/ecs/event-rule-target.test.ts
Labels: @aws-cdk/aws-events-targets, pr-linter/exempt-readme

#7947 chore: fix integ tests, take 3851
  packages/aws-cdk/.gitignore
  packages/aws-cdk/test/integ/cli/.gitignore
  packages/aws-cdk/test/integ/run-against-dist.bash
Labels: contribution/core

#7962 chore: make integ tests run on Linux
  packages/aws-cdk/test/integ/cli/cdk-helpers.ts
Labels: contribution/core

#7970 fix(cli): cdk bootstrap cannot be used without supplying the --app argument
  packages/aws-cdk/lib/cdk-toolkit.ts
  packages/aws-cdk/test/cdk-toolkit.test.ts
Labels: contribution/core, package/tools

#7974 chore: even more integ tests fixes
  packages/aws-cdk/test/integ/cli/bootstrapping.integtest.ts
  packages/aws-cdk/test/integ/cli/cdk-helpers.ts
  packages/aws-cdk/test/integ/cli/cli.integtest.ts
Labels: contribution/core

#7978 chore: use current package versions to check api compatibility
  scripts/check-api-compatibility.sh
Labels: contribution/core

#7425 feat(dynamodb): support for Customer-managed CMK
  packages/@aws-cdk/aws-dynamodb/README.md
  packages/@aws-cdk/aws-dynamodb/lib/perms.ts
  packages/@aws-cdk/aws-dynamodb/lib/replica-handler/index.ts
  packages/@aws-cdk/aws-dynamodb/lib/replica-provider.ts
  packages/@aws-cdk/aws-dynamodb/lib/table.ts
  packages/@aws-cdk/aws-dynamodb/package.json
  packages/@aws-cdk/aws-dynamodb/test/dynamodb.test.ts
  packages/@aws-cdk/aws-dynamodb/test/integ.dynamodb.sse.expected.json
  packages/@aws-cdk/aws-dynamodb/test/integ.dynamodb.sse.ts
  packages/@aws-cdk/aws-dynamodb/test/integ.global.expected.json
Labels: @aws-cdk/aws-dynamodb, review/medium

#7980 chore: fix regression tests
  packages/aws-cdk/test/integ/test-cli-regression-against-current-code.sh
Labels: contribution/core

#7997 fix(lambda): SingletonFunction ignores explicit declared dependencies
  packages/@aws-cdk/aws-lambda/lib/singleton-lambda.ts
  packages/@aws-cdk/aws-lambda/test/test.singleton-lambda.ts
Labels: contribution/core

#8000 fix(iot1click): incorrect type for Project.deviceTemplates
  packages/@aws-cdk/cfnspec/spec-source/500_IoT1Click_patch_PlacementTemplate_DeviceTemplates.json
Labels: @aws-cdk/aws-iot1click, @aws-cdk/cfnspec, bug, contribution/core, effort/small, pr-linter/exempt-test

#8019 chore: fix compatibility check for bump PRs
  build.sh
Labels: contribution/core

#7921 chore(repo): various small fixes to issue templates
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/doc.md
  .github/ISSUE_TEMPLATE/general-issues.md
Labels: contribution/core

#8021 chore: update stale cron to run once a day instead of every hour
  .github/workflows/close-stale-issues.yml
Labels: contribution/core

#8030 chore: merge release/1.39.0 to master
  CHANGELOG.md
  build.sh
  lerna.json
Labels: contribution/core, pr/no-squash

#8035 chore(apigateway): fix broken anchor link in README
  packages/@aws-cdk/aws-apigateway/README.md
Labels: @aws-cdk/aws-apigateway, contribution/core

#8054 chore: fix regression tests
  packages/aws-cdk/.gitignore
  packages/aws-cdk/test/integ/cli/jest.config.js
  packages/aws-cdk/test/integ/cli/test-jest.sh
  packages/aws-cdk/test/integ/test-cli-regression-against-current-code.sh
Labels: contribution/core

#8057 chore: need the integ tests's jest.config.js
  packages/aws-cdk/.npmignore
Labels: contribution/core

#8047 chore(cloudtrail): clear linter exclusions
  packages/@aws-cdk/aws-cloudtrail/lib/cloudtrail.ts
  packages/@aws-cdk/aws-cloudtrail/package.json
Labels: @aws-cdk/aws-cloudtrail, contribution/core

#8045 chore(certificatemanager): clear docs linter exclusions
  packages/@aws-cdk/aws-certificatemanager/lib/certificate.ts
  packages/@aws-cdk/aws-certificatemanager/lib/dns-validated-certificate.ts
  packages/@aws-cdk/aws-certificatemanager/package.json
Labels: contribution/core

#7876 feat(region-info): add information for us-gov, us-iso, and us-isob regions
  packages/@aws-cdk/region-info/build-tools/aws-entities.ts
  packages/@aws-cdk/region-info/build-tools/generate-static-data.ts
  packages/@aws-cdk/region-info/lib/default.ts
  packages/@aws-cdk/region-info/test/__snapshots__/region-info.test.js.snap
  packages/@aws-cdk/region-info/test/default.test.ts
  packages/@aws-cdk/region-info/test/region-info.test.ts
Labels: @aws-cdk/region-info, pr-linter/exempt-readme, pr-linter/exempt-test, review/small

#7741 feat(elbv2): full Action support
  packages/@aws-cdk/aws-elasticloadbalancingv2-actions/.eslintrc.js
  packages/@aws-cdk/aws-elasticloadbalancingv2-actions/.gitignore
  packages/@aws-cdk/aws-elasticloadbalancingv2-actions/.npmignore
  packages/@aws-cdk/aws-elasticloadbalancingv2-actions/LICENSE
  packages/@aws-cdk/aws-elasticloadbalancingv2-actions/NOTICE
  packages/@aws-cdk/aws-elasticloadbalancingv2-actions/README.md
  packages/@aws-cdk/aws-elasticloadbalancingv2-actions/jest.config.js
  packages/@aws-cdk/aws-elasticloadbalancingv2-actions/lib/cognito-action.ts
  packages/@aws-cdk/aws-elasticloadbalancingv2-actions/lib/index.ts
  packages/@aws-cdk/aws-elasticloadbalancingv2-actions/package.json
  packages/@aws-cdk/aws-elasticloadbalancingv2-actions/test/cognito.test.ts
  packages/@aws-cdk/aws-elasticloadbalancingv2-actions/test/integ.cognito.lit.expected.json
  packages/@aws-cdk/aws-elasticloadbalancingv2-actions/test/integ.cognito.lit.ts
  packages/@aws-cdk/aws-elasticloadbalancingv2/README.md
  packages/@aws-cdk/aws-elasticloadbalancingv2/lib/alb/application-listener-action.ts
  packages/@aws-cdk/aws-elasticloadbalancingv2/lib/alb/application-listener-rule.ts
  packages/@aws-cdk/aws-elasticloadbalancingv2/lib/alb/application-listener.ts
  packages/@aws-cdk/aws-elasticloadbalancingv2/lib/index.ts
  packages/@aws-cdk/aws-elasticloadbalancingv2/lib/nlb/network-listener-action.ts
  packages/@aws-cdk/aws-elasticloadbalancingv2/lib/nlb/network-listener.ts
  packages/@aws-cdk/aws-elasticloadbalancingv2/lib/shared/base-listener.ts
  packages/@aws-cdk/aws-elasticloadbalancingv2/lib/shared/listener-action.ts
  packages/@aws-cdk/aws-elasticloadbalancingv2/test/alb/test.actions.ts
  packages/@aws-cdk/aws-elasticloadbalancingv2/test/alb/test.listener.ts
  packages/@aws-cdk/aws-elasticloadbalancingv2/test/nlb/test.actions.ts
  packages/@aws-cdk/aws-elasticloadbalancingv2/test/nlb/test.listener.ts
  packages/decdk/package.json
  packages/monocdk-experiment/package.json
Labels: contribution/core

#7987 feat: add support for Gitpod workspaces
  .gitpod.yml
  CONTRIBUTING.md
  README.md
Labels: contribution/core, pr-linter/exempt-test

#7910 chore: make bootstrap v2 completely qualified
  allowed-breaking-changes.txt
  packages/@aws-cdk/core/lib/stack-synthesizers/default-synthesizer.ts
  packages/@aws-cdk/core/test/stack-synthesis/test.new-style-synthesis.ts
  packages/aws-cdk/.gitignore
  packages/aws-cdk/bin/cdk.ts
  packages/aws-cdk/lib/api/bootstrap/bootstrap-environment.ts
  packages/aws-cdk/lib/api/bootstrap/bootstrap-props.ts
  packages/aws-cdk/lib/api/bootstrap/bootstrap-template.yaml
  packages/aws-cdk/test/integ/bootstrap/bootstrap.integ-test.ts
  packages/aws-cdk/test/integ/bootstrap/example-cdk-app/.gitignore
  packages/aws-cdk/test/integ/bootstrap/example-cdk-app/assets/asset1.txt
  packages/aws-cdk/test/integ/bootstrap/example-cdk-app/assets/asset2.txt
  packages/aws-cdk/test/integ/bootstrap/example-cdk-app/my-test-cdk-stack.d.ts
  packages/aws-cdk/test/integ/bootstrap/example-cdk-app/my-test-cdk-stack.js
  packages/aws-cdk/test/integ/cli/aws-helpers.ts
  packages/aws-cdk/test/integ/cli/bootstrapping.integtest.ts
  packages/aws-cdk/test/integ/cli/cdk-helpers.ts
  packages/aws-cdk/test/integ/cli/cli.integtest.ts
  packages/aws-cdk/test/integ/cli/jest.setup.js
  packages/aws-cdk/test/integ/cli/test-jest.sh
Labels: contribution/core

#8073 chore: fix regression tests
  packages/aws-cdk/test/integ/test-cli-regression-against-current-code.sh
Labels: contribution/core

#8077 chore(cloudtrail): move to jest
  packages/@aws-cdk/aws-cloudtrail/.gitignore
  packages/@aws-cdk/aws-cloudtrail/.npmignore
  packages/@aws-cdk/aws-cloudtrail/jest.config.js
  packages/@aws-cdk/aws-cloudtrail/package.json
  packages/@aws-cdk/aws-cloudtrail/test/cloudtrail.test.ts
  packages/@aws-cdk/aws-cloudtrail/test/test.cloudtrail.ts
Labels: contribution/core

#8078 chore(core): already-uploaded template URL is incorrect in manifest
  packages/@aws-cdk/cloud-assembly-schema/schema/cloud-assembly.version.json
  packages/@aws-cdk/core/lib/stack-synthesizers/default-synthesizer.ts
  packages/@aws-cdk/core/test/stack-synthesis/test.new-style-synthesis.ts
  packages/aws-cdk/lib/api/deploy-stack.ts
  packages/aws-cdk/test/api/deploy-stack.test.ts
  packages/aws-cdk/test/integ/cli/bootstrapping.integtest.ts
Labels: contribution/core

#8059 chore: update quick iteration section in contributing guide
  CONTRIBUTING.md
Labels: contribution/core

#8101 chore: merge release/1.40.0 to master
  CHANGELOG.md
  lerna.json
Labels: contribution/core, pr/no-squash

#8076 feat(cloudtrail): create cloudwatch event without needing to create a Trail
  packages/@aws-cdk/aws-cloudtrail/README.md
  packages/@aws-cdk/aws-cloudtrail/lib/cloudtrail.ts
  packages/@aws-cdk/aws-cloudtrail/package.json
  packages/@aws-cdk/aws-cloudtrail/test/cloudtrail.test.ts
Labels: contribution/core

#7946 feat(stepfunctions): new service integration classes for Lambda, SNS, and SQS
  packages/@aws-cdk/aws-stepfunctions-tasks/README.md
  packages/@aws-cdk/aws-stepfunctions-tasks/lib/index.ts
  packages/@aws-cdk/aws-stepfunctions-tasks/lib/lambda/invoke-function.ts
  packages/@aws-cdk/aws-stepfunctions-tasks/lib/lambda/invoke.ts
  packages/@aws-cdk/aws-stepfunctions-tasks/lib/lambda/run-lambda-task.ts
  packages/@aws-cdk/aws-stepfunctions-tasks/lib/private/task-utils.ts
  packages/@aws-cdk/aws-stepfunctions-tasks/lib/sns/publish-to-topic.ts
  packages/@aws-cdk/aws-stepfunctions-tasks/lib/sns/publish.ts
  packages/@aws-cdk/aws-stepfunctions-tasks/lib/sqs/send-message.ts
  packages/@aws-cdk/aws-stepfunctions-tasks/lib/sqs/send-to-queue.ts
  packages/@aws-cdk/aws-stepfunctions-tasks/package.json
  packages/@aws-cdk/aws-stepfunctions-tasks/test/lambda/integ.invoke.expected.json
  packages/@aws-cdk/aws-stepfunctions-tasks/test/lambda/integ.invoke.ts
  packages/@aws-cdk/aws-stepfunctions-tasks/test/lambda/invoke.test.ts
  packages/@aws-cdk/aws-stepfunctions-tasks/test/private/task-utils.test.ts
  packages/@aws-cdk/aws-stepfunctions-tasks/test/sns/integ.publish.expected.json
  packages/@aws-cdk/aws-stepfunctions-tasks/test/sns/integ.publish.ts
  packages/@aws-cdk/aws-stepfunctions-tasks/test/sns/publish.test.ts
  packages/@aws-cdk/aws-stepfunctions-tasks/test/sqs/integ.send-message.expected.json
  packages/@aws-cdk/aws-stepfunctions-tasks/test/sqs/integ.send-message.ts
  packages/@aws-cdk/aws-stepfunctions-tasks/test/sqs/send-message.test.ts
  packages/@aws-cdk/aws-stepfunctions/README.md
  packages/@aws-cdk/aws-stepfunctions/lib/index.ts
  packages/@aws-cdk/aws-stepfunctions/lib/states/task-base.ts
  packages/@aws-cdk/aws-stepfunctions/test/task-base.test.ts
Labels: @aws-cdk/aws-stepfunctions, @aws-cdk/aws-stepfunctions-tasks, contribution/core

#8099 feat(core): CfnJson enables intrinsics in hash keys
  packages/@aws-cdk/aws-iam/README.md
  packages/@aws-cdk/aws-iam/lib/principals.ts
  packages/@aws-cdk/aws-iam/test/integ.condition-with-ref.expected.json
  packages/@aws-cdk/aws-iam/test/integ.condition-with-ref.ts
  packages/@aws-cdk/aws-iam/test/policy-document.test.ts
  packages/@aws-cdk/core/README.md
  packages/@aws-cdk/core/lib/cfn-json.ts
  packages/@aws-cdk/core/lib/index.ts
  packages/@aws-cdk/core/lib/private/cfn-utils-provider.ts
  packages/@aws-cdk/core/lib/private/cfn-utils-provider/consts.ts
  packages/@aws-cdk/core/lib/private/cfn-utils-provider/index.ts
  packages/@aws-cdk/core/lib/private/resolve.ts
  packages/@aws-cdk/core/package.json
  packages/@aws-cdk/core/test/test.cfn-json.ts
Labels: contribution/core

#8124 chore: integ test flakiness
  packages/aws-cdk/test/integ/cli/cli.integtest.ts
Labels: contribution/core

#8079 feat(cloudtrail): user specified log group
  packages/@aws-cdk/aws-cloudtrail/README.md
  packages/@aws-cdk/aws-cloudtrail/lib/cloudtrail.ts
  packages/@aws-cdk/aws-cloudtrail/test/cloudtrail.test.ts
Labels: contribution/core

#8046 chore(cloudwatch-actions): clear linter exclusions
  packages/@aws-cdk/aws-cloudwatch-actions/lib/appscaling.ts
  packages/@aws-cdk/aws-cloudwatch-actions/lib/autoscaling.ts
  packages/@aws-cdk/aws-cloudwatch-actions/lib/sns.ts
  packages/@aws-cdk/aws-cloudwatch-actions/package.json
Labels: @aws-cdk/aws-cloudwatch-actions, contribution/core

#8068 fix(events): cannot use the same target account for 2 cross-account event sources
  packages/@aws-cdk/aws-events/lib/rule.ts
  packages/@aws-cdk/aws-events/test/test.rule.ts
Labels: contribution/core

#8129 chore(cli): simpler error message on cloud assembly version mismatch
  packages/aws-cdk/lib/api/cxapp/exec.ts
  packages/aws-cdk/test/api/exec.test.ts
Labels: contribution/core

#8127 chore: add test deploying old-style synthesis to new-style bootstrap
  packages/aws-cdk/test/integ/cli/bootstrapping.integtest.ts
Labels: contribution/core

#8130 chore: merge release/1.41.0 to master
  CHANGELOG.md
  lerna.json
Labels: contribution/core, pr/no-squash

#8121 chore: add node version to issue template
  .github/ISSUE_TEMPLATE.md
Labels: contribution/core

#8147 chore(stepfunctions): add missing tests
  packages/@aws-cdk/aws-stepfunctions/test/custom-state.test.ts
  packages/@aws-cdk/aws-stepfunctions/test/private/render-util.ts
  packages/@aws-cdk/aws-stepfunctions/test/task.test.ts
  packages/@aws-cdk/aws-stepfunctions/test/wait.test.ts
Labels: @aws-cdk/aws-stepfunctions, contribution/core

#8143 feat(stepfunctions-tasks): task for starting a job run in AWS Glue
  packages/@aws-cdk/aws-stepfunctions-tasks/README.md
  packages/@aws-cdk/aws-stepfunctions-tasks/lib/glue/run-glue-job-task.ts
  packages/@aws-cdk/aws-stepfunctions-tasks/lib/glue/start-job-run.ts
  packages/@aws-cdk/aws-stepfunctions-tasks/lib/index.ts
  packages/@aws-cdk/aws-stepfunctions-tasks/test/glue/integ.start-job-run.expected.json
  packages/@aws-cdk/aws-stepfunctions-tasks/test/glue/integ.start-job-run.ts
  packages/@aws-cdk/aws-stepfunctions-tasks/test/glue/start-job-run.test.ts
Labels: @aws-cdk/aws-stepfunctions-tasks, contribution/core

#8070 feat(stepfunctions): support paths in Pass state
  packages/@aws-cdk/aws-stepfunctions/README.md
  packages/@aws-cdk/aws-stepfunctions/lib/states/pass.ts
  packages/@aws-cdk/aws-stepfunctions/test/state-machine-resources.test.ts
Labels: @aws-cdk/aws-stepfunctions, contribution/core

#8128 chore: clear 'breaking changes' history
  allowed-breaking-changes.txt
Labels: contribution/core

#8182 chore: fix tsc-3.9 issues ahead of upgrade
  packages/@aws-cdk/aws-events-targets/build-tools/gen.js
  packages/@aws-cdk/aws-events-targets/lib/aws-api.ts
  packages/@aws-cdk/aws-events-targets/package.json
  packages/@aws-cdk/cdk-assets-schema/lib/private/schema-helpers.ts
  packages/@aws-cdk/cdk-assets-schema/lib/validate.ts
  packages/@aws-cdk/cdk-assets-schema/test/validate.test.ts
Labels: contribution/core, effort/small

#8164 fix(cli): paper cuts
  packages/aws-cdk/bin/cdk.ts
  packages/aws-cdk/lib/api/aws-auth/sdk-provider.ts
  packages/aws-cdk/lib/api/aws-auth/sdk.ts
  packages/aws-cdk/lib/api/deploy-stack.ts
  packages/aws-cdk/lib/api/util/cloudformation.ts
  packages/aws-cdk/test/api/deploy-stack.test.ts
  packages/aws-cdk/test/api/sdk-provider.test.ts
Labels: contribution/core

#8091 feat(codepipeline): use a special bootstrapless synthesizer for cross-region support Stacks
  packages/@aws-cdk/aws-codepipeline/lib/cross-region-support-stack.ts
  packages/@aws-cdk/aws-codepipeline/lib/pipeline.ts
  packages/@aws-cdk/aws-codepipeline/package.json
  packages/@aws-cdk/aws-codepipeline/test/test.pipeline.ts
  packages/@aws-cdk/core/lib/stack-synthesizers/bootstrapless-synthesizer.ts
  packages/@aws-cdk/core/lib/stack-synthesizers/default-synthesizer.ts
  packages/@aws-cdk/core/lib/stack-synthesizers/index.ts
Labels: contribution/core, pr-linter/exempt-readme

#8186 fix(dynamodb): the maximum number of nonKeyAttributes is 100, not 20
  packages/@aws-cdk/aws-dynamodb/lib/table.ts
  packages/@aws-cdk/aws-dynamodb/test/dynamodb.test.ts
Labels: @aws-cdk/aws-dynamodb, bug, contribution/core, effort/small

#8187 chore: fix build
  packages/aws-cdk/lib/api/aws-auth/sdk.ts
Labels: contribution/core

#8179 chore(stepfunctions): add tests for state transition metrics
  packages/@aws-cdk/aws-stepfunctions/jest.config.js
  packages/@aws-cdk/aws-stepfunctions/test/state-transition-metrics.test.ts
Labels: contribution/core

#8097 chore(cloudtrail): better typed event selector apis
  packages/@aws-cdk/aws-cloudtrail/README.md
  packages/@aws-cdk/aws-cloudtrail/lib/cloudtrail.ts
  packages/@aws-cdk/aws-cloudtrail/package.json
  packages/@aws-cdk/aws-cloudtrail/test/cloudtrail.test.ts
  packages/@aws-cdk/aws-cloudtrail/test/integ.cloudtrail-supplied-bucket.lit.ts
  packages/@aws-cdk/aws-cloudtrail/test/integ.cloudtrail.lit.ts
  packages/@aws-cdk/aws-codepipeline-actions/test/integ.lambda-pipeline.ts
Labels: contribution/core

#8234 chore(monocdk): re-do build logic
  package.json
  packages/@monocdk-experiment/assert/package.json
  packages/@monocdk-experiment/rewrite-imports/lib/rewrite.ts
  packages/monocdk-experiment/.eslintrc.js
  packages/monocdk-experiment/.gitignore
  packages/monocdk-experiment/.npmignore
  packages/monocdk-experiment/README.md
  packages/monocdk-experiment/build-tools/gen.ts
  packages/monocdk-experiment/build.sh
  packages/monocdk-experiment/deps.js
  packages/monocdk-experiment/gen.js
  packages/monocdk-experiment/package.json
  yarn.lock
Labels: contribution/core, effort/small

#8246 chore(release): merge release/1.42.0 to master
  CHANGELOG.md
  lerna.json
Labels: pr/no-squash

#8217 fix(app-delivery): could not use PipelineDeployStackAction more than once in a Stage
  packages/@aws-cdk/app-delivery/lib/pipeline-deploy-stack-action.ts
  packages/@aws-cdk/app-delivery/test/test.pipeline-deploy-stack-action.ts
Labels: contribution/core

#7107 fix(codepipeline): correctly handle CODEBUILD_CLONE_REF in BitBucket source
  packages/@aws-cdk/aws-codepipeline-actions/lib/bitbucket/source-action.ts
  packages/@aws-cdk/aws-codepipeline-actions/lib/codebuild/build-action.ts
  packages/@aws-cdk/aws-codepipeline-actions/test/bitbucket/test.bitbucket-source-action.ts
  packages/@aws-cdk/aws-codepipeline/lib/artifact.ts
Labels: contribution/core

#8123 feat(cognito): addDomain() on an imported user pool
  packages/@aws-cdk/aws-cognito/lib/user-pool.ts
  packages/@aws-cdk/aws-cognito/test/user-pool.test.ts
Labels: contribution/core, pr-linter/exempt-readme

#8245 feat(dynamodb): allow providing indexes when importing a Table
  packages/@aws-cdk/aws-dynamodb/lib/table.ts
  packages/@aws-cdk/aws-dynamodb/test/dynamodb.test.ts
Labels: contribution/core, pr-linter/exempt-readme

#8207 fix(apigateway): deployment is not updated when OpenAPI definition is updated
  packages/@aws-cdk/aws-apigateway/lib/deployment.ts
  packages/@aws-cdk/aws-apigateway/test/integ.api-definition.asset.expected.json
  packages/@aws-cdk/aws-apigateway/test/integ.api-definition.inline.expected.json
Labels: contribution/core

#8256 fix(codepipeline): unhelpful artifact validation messages
  packages/@aws-cdk/aws-codepipeline/lib/pipeline.ts
  packages/@aws-cdk/aws-codepipeline/test/test.artifacts.ts
Labels: contribution/core

#8264 docs(cli): update readme section for `cdk synth`
  packages/aws-cdk/README.md
Labels: contribution/core, package/tools
