Repository aws/aws-cdk, pull requests merged in 2020-06, with the labels that each got.

#8184 chore: add a base VSCode config
  .gitignore
  .vscode/launch.json
  CONTRIBUTING.md
Labels: contribution/core

#8252 fix(sqs): unable to use CfnParameter 'valueAsNumber' to specify queue properties
  packages/@aws-cdk/aws-sqs/lib/validate-props.ts
  packages/@aws-cdk/aws-sqs/test/test.sqs.ts
Labels: @aws-cdk/aws-sqs, contribution/core

#8296 fix(lambda): `SingletonFunction.grantInvoke()` API fails with error 'No child with id'
  packages/@aws-cdk/aws-lambda/lib/function-base.ts
  packages/@aws-cdk/aws-lambda/lib/singleton-lambda.ts
  packages/@aws-cdk/aws-lambda/test/test.singleton-lambda.ts
Labels: contribution/core

#8302 chore(release): 1.42.1
  CHANGELOG.md
  lerna.json
  packages/@aws-cdk/aws-lambda/lib/function-base.ts
  packages/@aws-cdk/aws-lambda/lib/singleton-lambda.ts
  packages/@aws-cdk/aws-lambda/test/test.singleton-lambda.ts
Labels: contribution/core, pr/no-squash

#8023 feat(rds): change the default retention policy of Cluster and DB Instance
  packages/@aws-cdk/aws-rds/lib/cluster.ts
  packages/@aws-cdk/aws-rds/lib/instance.ts
  packages/@aws-cdk/aws-rds/test/integ.cluster-rotation.lit.expected.json
  packages/@aws-cdk/aws-rds/test/integ.cluster-s3.expected.json
  packages/@aws-cdk/aws-rds/test/integ.cluster.expected.json
  packages/@aws-cdk/aws-rds/test/integ.instance.lit.expected.json
  packages/@aws-cdk/aws-rds/test/test.cluster.ts
  packages/@aws-cdk/aws-rds/test/test.instance.ts
  packages/@aws-cdk/core/lib/cfn-resource.ts
  packages/@aws-cdk/core/lib/removal-policy.ts
Labels: contribution/core, pr-linter/exempt-readme, pr/do-not-merge

#8309 chore(release): merge release/1.42.1 to master
  CHANGELOG.md
  lerna.json
Labels: pr/no-squash

#8110 fix(rds): cannot delete a stack with DbCluster set to 'Retain'
  packages/@aws-cdk/aws-rds/lib/cluster.ts
  packages/@aws-cdk/aws-rds/test/test.cluster.ts
Labels: contribution/core

#8144 feat(cfn-include): add support for Conditions
  packages/@aws-cdk/cloudformation-include/README.md
  packages/@aws-cdk/cloudformation-include/lib/cfn-include.ts
  packages/@aws-cdk/cloudformation-include/test/invalid-templates.test.ts
  packages/@aws-cdk/cloudformation-include/test/test-templates/invalid/non-existent-condition.json
  packages/@aws-cdk/cloudformation-include/test/valid-templates.test.ts
  packages/@aws-cdk/core/lib/cfn-parse.ts
  packages/@aws-cdk/core/lib/from-cfn.ts
  tools/cfn2ts/lib/codegen.ts
Labels: contribution/core

#8018 fix(codepipeline): allow multiple CodeCommit source actions using events
  packages/@aws-cdk/aws-codepipeline-actions/lib/codecommit/source-action.ts
  packages/@aws-cdk/aws-codepipeline-actions/test/codecommit/test.codecommit-source-action.ts
Labels: contribution/core

#8251 fix(core): CFN version and description template sections were merged incorrectly
  packages/@aws-cdk/core/lib/stack.ts
  packages/@aws-cdk/core/test/test.include.ts
Labels: contribution/core

#8316 chore(cli): fix integ test for IAM diff
  packages/aws-cdk/test/integ/cli/cli.integtest.ts
Labels: contribution/core

#8322 chore(cloudtrail): revamp README
  packages/@aws-cdk/aws-cloudtrail/README.md
  packages/@aws-cdk/aws-cloudtrail/lib/cloudtrail.ts
  packages/@aws-cdk/aws-cloudtrail/test/cloudtrail.test.ts
Labels: contribution/core

#8323 chore(cli): fix integ test
  packages/aws-cdk/test/integ/cli/cli.integtest.ts
Labels: contribution/core, package/tools

#8334 chore(core): update comments
  packages/@aws-cdk/core/lib/size.ts
Labels: contribution/core

#8333 chore: update issue template to request nodejs version
  .github/ISSUE_TEMPLATE/bug.md
  .github/ISSUE_TEMPLATE/general-issues.md
Labels: contribution/core

#8134 feat(cognito): user pool identity provider with support for Facebook & Amazon
  packages/@aws-cdk/aws-cognito/README.md
  packages/@aws-cdk/aws-cognito/lib/index.ts
  packages/@aws-cdk/aws-cognito/lib/user-pool-client.ts
  packages/@aws-cdk/aws-cognito/lib/user-pool-idp.ts
  packages/@aws-cdk/aws-cognito/lib/user-pool-idps/amazon.ts
  packages/@aws-cdk/aws-cognito/lib/user-pool-idps/base.ts
  packages/@aws-cdk/aws-cognito/lib/user-pool-idps/facebook.ts
  packages/@aws-cdk/aws-cognito/lib/user-pool-idps/index.ts
  packages/@aws-cdk/aws-cognito/lib/user-pool.ts
  packages/@aws-cdk/aws-cognito/package.json
  packages/@aws-cdk/aws-cognito/test/integ.user-pool-idp.expected.json
  packages/@aws-cdk/aws-cognito/test/integ.user-pool-idp.ts
  packages/@aws-cdk/aws-cognito/test/user-pool-client.test.ts
  packages/@aws-cdk/aws-cognito/test/user-pool-idps/amazon.test.ts
  packages/@aws-cdk/aws-cognito/test/user-pool-idps/facebook.test.ts
  packages/@aws-cdk/aws-cognito/test/user-pool.test.ts
Labels: contribution/core

#8319 chore(bootstrap): split file/image publishing roles
  allowed-breaking-changes.txt
  packages/@aws-cdk/core/lib/stack-synthesizers/default-synthesizer.ts
  packages/@aws-cdk/core/test/stack-synthesis/test.new-style-synthesis.ts
  packages/aws-cdk/lib/api/bootstrap/bootstrap-template.yaml
  packages/aws-cdk/test/integ/cli/README.md
  packages/aws-cdk/test/integ/cli/aws-helpers.ts
  packages/aws-cdk/test/integ/cli/bootstrapping.integtest.ts
  packages/aws-cdk/test/integ/cli/cdk-helpers.ts
  packages/cdk-assets/lib/private/shell.ts
Labels: contribution/core

#8178 feat(stepfunctions-tasks): start a nested state machine execution as a construct
  packages/@aws-cdk/aws-stepfunctions-tasks/README.md
  packages/@aws-cdk/aws-stepfunctions-tasks/lib/index.ts
  packages/@aws-cdk/aws-stepfunctions-tasks/lib/start-execution.ts
  packages/@aws-cdk/aws-stepfunctions-tasks/lib/stepfunctions/start-execution.ts
  packages/@aws-cdk/aws-stepfunctions-tasks/test/stepfunctions/integ.start-execution.expected.json
  packages/@aws-cdk/aws-stepfunctions-tasks/test/stepfunctions/integ.start-execution.ts
  packages/@aws-cdk/aws-stepfunctions-tasks/test/stepfunctions/start-execution.test.ts
Labels: contribution/core

#8345 chore: fixup fetch-dotnet-snk.sh
  fetch-dotnet-snk.sh
Labels: contribution/core

#8331 chore(deps): upgrade jsii version to v1.6.0
  package.json
  packages/cdk-dasm/package.json
  packages/decdk/package.json
  tools/awslint/package.json
  tools/cdk-build-tools/package.json
  tools/cfn2ts/package.json
  yarn.lock
Labels: contribution/core

#8351 chore: revert "(bootstrap): split file/image publishing roles"
  allowed-breaking-changes.txt
  packages/@aws-cdk/core/lib/stack-synthesizers/default-synthesizer.ts
  packages/@aws-cdk/core/test/stack-synthesis/test.new-style-synthesis.ts
  packages/aws-cdk/lib/api/bootstrap/bootstrap-template.yaml
  packages/aws-cdk/test/integ/cli/README.md
  packages/aws-cdk/test/integ/cli/aws-helpers.ts
  packages/aws-cdk/test/integ/cli/bootstrapping.integtest.ts
  packages/aws-cdk/test/integ/cli/cdk-helpers.ts
  packages/cdk-assets/lib/private/shell.ts
Labels: contribution/core

#8312 feat(ecs-patterns): support min and max health percentage in queueprocessingservice
  packages/@aws-cdk/aws-ecs-patterns/README.md
  packages/@aws-cdk/aws-ecs-patterns/lib/base/queue-processing-service-base.ts
  packages/@aws-cdk/aws-ecs-patterns/lib/ecs/queue-processing-ecs-service.ts
  packages/@aws-cdk/aws-ecs-patterns/lib/fargate/queue-processing-fargate-service.ts
  packages/@aws-cdk/aws-ecs-patterns/test/ec2/test.queue-processing-ecs-service.ts
  packages/@aws-cdk/aws-ecs-patterns/test/fargate/test.queue-processing-fargate-service.ts
Labels: @aws-cdk/aws-ecs-patterns

#8361 chore(release): merge release/1.43.0 to master
  CHANGELOG.md
  lerna.json
Labels: pr/no-squash

#8368 chore(monocdk): align base namespace/package with regular build
  packages/monocdk-experiment/package.json
Labels: contribution/core

#8370 chore(release): 1.44.0
  CHANGELOG.md
  design/aws-guidelines.md
  lerna.json
  package.json
  packages/@aws-cdk/aws-ecs-patterns/README.md
  packages/@aws-cdk/aws-ecs-patterns/lib/base/queue-processing-service-base.ts
  packages/@aws-cdk/aws-ecs-patterns/lib/ecs/queue-processing-ecs-service.ts
  packages/@aws-cdk/aws-ecs-patterns/lib/fargate/queue-processing-fargate-service.ts
  packages/@aws-cdk/aws-ecs-patterns/test/ec2/test.queue-processing-ecs-service.ts
  packages/@aws-cdk/aws-ecs-patterns/test/fargate/test.queue-processing-fargate-service.ts
  packages/@aws-cdk/aws-lambda-nodejs/package.json
  packages/@aws-cdk/cfnspec/package.json
  packages/@aws-cdk/custom-resources/package.json
  packages/@aws-cdk/region-info/package.json
  packages/aws-cdk/package.json
  packages/decdk/package.json
  packages/monocdk-experiment/package.json
  tools/awslint/package.json
  tools/cdk-build-tools/package.json
  tools/cdk-integ-tools/package.json
  tools/cfn2ts/package.json
  tools/pkglint/package.json
  tools/pkgtools/package.json
  yarn.lock
Labels: pr/no-squash

#8375 chore(release): merge release/1.44.0 to master
  CHANGELOG.md
  lerna.json
Labels: pr/no-squash

#8366 chore: remove monocdk-experiment build exceptions
  pack.sh
  packages/@monocdk-experiment/assert/clone.sh
  scripts/list-packages
Labels: contribution/core

#8395 chore(merge-back): 1.43.0
  CHANGELOG.md
  lerna.json
Labels: pr/no-squash

#8324 feat(rds): rename 'kmsKey' properties to 'encryptionKey'
  packages/@aws-cdk/aws-rds/lib/cluster.ts
  packages/@aws-cdk/aws-rds/lib/instance.ts
  packages/@aws-cdk/aws-rds/lib/props.ts
  packages/@aws-cdk/aws-rds/test/integ.cluster-s3.ts
  packages/@aws-cdk/aws-rds/test/integ.cluster.ts
  packages/@aws-cdk/aws-rds/test/test.cluster.ts
Labels: contribution/core, pr-linter/exempt-readme

#8409 feat(secretsmanager): Secret.grantRead() also gives DescribeSecret permissions
  packages/@aws-cdk/aws-ecs/test/ec2/integ.secret-json-field.expected.json
  packages/@aws-cdk/aws-ecs/test/fargate/integ.secret.expected.json
  packages/@aws-cdk/aws-ecs/test/test.container-definition.ts
  packages/@aws-cdk/aws-secretsmanager/lib/secret.ts
  packages/@aws-cdk/aws-secretsmanager/test/integ.secret.lit.expected.json
  packages/@aws-cdk/aws-secretsmanager/test/test.secret.ts
Labels: pr-linter/exempt-readme

#8414 chore(release): 1.44.0
  CHANGELOG.md
  lerna.json
Labels: pr/no-squash

#8415 chore(merge-back): 1.44.0
  CHANGELOG.md
  lerna.json
Labels: pr/no-squash

#8403 chore(bootstrap): split file/image publishing roles
  allowed-breaking-changes.txt
  packages/@aws-cdk/core/lib/stack-synthesizers/default-synthesizer.ts
  packages/@aws-cdk/core/test/stack-synthesis/test.new-style-synthesis.ts
  packages/aws-cdk/.gitignore
  packages/aws-cdk/.npmignore
  packages/aws-cdk/lib/api/bootstrap/bootstrap-template.yaml
  packages/aws-cdk/test/integ/cli-regression-patches/README.md
  packages/aws-cdk/test/integ/cli-regression-patches/v1.44.0/NOTES.md
  packages/aws-cdk/test/integ/cli-regression-patches/v1.44.0/bootstrapping.integtest.js
  packages/aws-cdk/test/integ/cli-regression-patches/v1.44.0/test.sh
  packages/aws-cdk/test/integ/cli.exclusions.js
  packages/aws-cdk/test/integ/cli/README.md
  packages/aws-cdk/test/integ/cli/app/app.js
  packages/aws-cdk/test/integ/cli/aws-helpers.ts
  packages/aws-cdk/test/integ/cli/bootstrapping.integtest.ts
  packages/aws-cdk/test/integ/cli/cdk-helpers.ts
  packages/aws-cdk/test/integ/cli/cli.integtest.ts
  packages/aws-cdk/test/integ/cli/jest.setup.js
  packages/aws-cdk/test/integ/cli/skip-tests.txt
  packages/aws-cdk/test/integ/cli/test-helpers.ts
  packages/aws-cdk/test/integ/cli/test.sh
  packages/aws-cdk/test/integ/test-cli-regression-against-current-code.sh
  packages/aws-cdk/test/integ/test-cli-regression-against-latest-release.sh
  packages/cdk-assets/lib/private/shell.ts
Labels: contribution/core

#8399 fix(cognito): error when using parameter for `domainPrefix`
  packages/@aws-cdk/aws-cognito/lib/user-pool-attr.ts
  packages/@aws-cdk/aws-cognito/lib/user-pool-domain.ts
  packages/@aws-cdk/aws-cognito/lib/user-pool.ts
  packages/@aws-cdk/aws-cognito/test/user-pool-attr.test.ts
  packages/@aws-cdk/aws-cognito/test/user-pool-domain.test.ts
  packages/@aws-cdk/aws-cognito/test/user-pool.test.ts
Labels: contribution/core

#8421 chore(cli): fix "iam diff" integration test
  packages/aws-cdk/test/integ/cli/cli.integtest.ts
Labels: contribution/core

#8423 chore(core): Stages
  allowed-breaking-changes.txt
  packages/@aws-cdk/cloud-assembly-schema/lib/artifact-schema.ts
  packages/@aws-cdk/cloud-assembly-schema/lib/schema.ts
  packages/@aws-cdk/cloud-assembly-schema/schema/cloud-assembly.schema.json
  packages/@aws-cdk/cloud-assembly-schema/schema/cloud-assembly.version.json
  packages/@aws-cdk/cloud-assembly-schema/scripts/update-schema.sh
  packages/@aws-cdk/core/README.md
  packages/@aws-cdk/core/lib/app.ts
  packages/@aws-cdk/core/lib/construct-compat.ts
  packages/@aws-cdk/core/lib/deps.ts
  packages/@aws-cdk/core/lib/index.ts
  packages/@aws-cdk/core/lib/private/prepare-app.ts
  packages/@aws-cdk/core/lib/private/refs.ts
  packages/@aws-cdk/core/lib/private/synthesis.ts
  packages/@aws-cdk/core/lib/stack.ts
  packages/@aws-cdk/core/lib/stage.ts
  packages/@aws-cdk/core/test/test.stage.ts
  packages/@aws-cdk/cx-api/design/NESTED_ASSEMBLIES.md
  packages/@aws-cdk/cx-api/jest.config.js
  packages/@aws-cdk/cx-api/lib/artifacts/asset-manifest-artifact.ts
  packages/@aws-cdk/cx-api/lib/artifacts/cloudformation-artifact.ts
  packages/@aws-cdk/cx-api/lib/artifacts/nested-cloud-assembly-artifact.ts
  packages/@aws-cdk/cx-api/lib/artifacts/tree-cloud-artifact.ts
  packages/@aws-cdk/cx-api/lib/cloud-artifact.ts
  packages/@aws-cdk/cx-api/lib/cloud-assembly.ts
  packages/@aws-cdk/cx-api/lib/index.ts
  packages/@aws-cdk/cx-api/test/cloud-assembly-builder.test.ts
  packages/@aws-cdk/cx-api/test/placeholders.test.ts
Labels: contribution/core

#8206 fix(apigateway): methodArn not replacing path parameters with asterisks
  packages/@aws-cdk/aws-apigateway/lib/method.ts
  packages/@aws-cdk/aws-apigateway/test/integ.lambda-api.latebound-deploymentstage.expected.json
  packages/@aws-cdk/aws-apigateway/test/integ.restapi.books.expected.json
  packages/@aws-cdk/aws-apigateway/test/test.method.ts
  packages/@aws-cdk/aws-route53-targets/test/integ.api-gateway-domain-name.expected.json
  packages/decdk/test/__snapshots__/synth.test.js.snap
Labels: contribution/core

#8426 docs(ecs): fix an inline code sample in ECS
  packages/@aws-cdk/aws-ecs/lib/base/base-service.ts
Labels: contribution/core

#8224 fix(dynamodb): old global table replicas cannot be deleted
  packages/@aws-cdk/aws-dynamodb/lib/table.ts
  packages/@aws-cdk/aws-dynamodb/test/integ.global.expected.json
Labels: @aws-cdk/aws-dynamodb, contribution/core, effort/medium, pr-linter/exempt-readme, pr-linter/exempt-test

#8427 chore: re-enable using current pkg versions for api compat checks
  build.sh
  scripts/check-api-compatibility.sh
Labels: contribution/core

#8231 chore: remove awkward cfn2ts script entries
  packages/@aws-cdk/aws-autoscaling-hooktargets/package.json
  packages/@aws-cdk/aws-cloudwatch-actions/package.json
  packages/@aws-cdk/aws-docdb/package.json
  packages/@aws-cdk/aws-dynamodb-global/package.json
  packages/@aws-cdk/aws-ecs-patterns/package.json
  packages/@aws-cdk/aws-elasticloadbalancingv2-actions/package.json
  packages/@aws-cdk/aws-elasticloadbalancingv2-targets/package.json
  packages/@aws-cdk/aws-events-targets/package.json
  packages/@aws-cdk/aws-lambda-destinations/package.json
  packages/@aws-cdk/aws-lambda-nodejs/package.json
  packages/@aws-cdk/aws-logs-destinations/package.json
  packages/@aws-cdk/aws-route53-patterns/package.json
  packages/@aws-cdk/aws-route53-targets/package.json
  packages/@aws-cdk/aws-ses-actions/package.json
  packages/@aws-cdk/aws-sns-subscriptions/package.json
  packages/@aws-cdk/aws-stepfunctions-tasks/package.json
  packages/@aws-cdk/custom-resources/package.json
  packages/aws-cdk/package.json
  packages/cdk-assets/package.json
  tools/pkglint/lib/rules.ts
  tools/pkglint/package.json
  tools/yarn-cling/.eslintrc.js
  tools/yarn-cling/.gitignore
  tools/yarn-cling/.npmignore
  tools/yarn-cling/lib/index.ts
  tools/yarn-cling/package.json
  tools/yarn-cling/test/test-fixture/.no-packagejson-validator
Labels: contribution/core, effort/small

#8444 feat(assert): more powerful matchers
  packages/@aws-cdk/assert/README.md
  packages/@aws-cdk/assert/lib/assertions/have-resource.ts
  packages/@aws-cdk/assert/test/have-resource.test.ts
Labels: contribution/core

#8447 fix(eks): fargate profile role not added to aws-auth by the cdk
  packages/@aws-cdk/aws-eks/lib/fargate-profile.ts
  packages/@aws-cdk/aws-eks/test/integ.eks-cluster.expected.json
  packages/@aws-cdk/aws-eks/test/test.fargate.ts
Labels: contribution/core

#8401 chore: re-write @monocdk-experiment/rewrite-imports
  packages/@monocdk-experiment/rewrite-imports/bin/rewrite-imports.ts
  packages/@monocdk-experiment/rewrite-imports/lib/rewrite.ts
  packages/@monocdk-experiment/rewrite-imports/package.json
  packages/@monocdk-experiment/rewrite-imports/test/rewrite.test.ts
Labels: contribution/core

#8445 feat(cognito): user pool - identity provider attribute mapping
  packages/@aws-cdk/aws-cognito/README.md
  packages/@aws-cdk/aws-cognito/lib/private/attr-names.ts
  packages/@aws-cdk/aws-cognito/lib/user-pool-idps/amazon.ts
  packages/@aws-cdk/aws-cognito/lib/user-pool-idps/base.ts
  packages/@aws-cdk/aws-cognito/lib/user-pool-idps/facebook.ts
  packages/@aws-cdk/aws-cognito/lib/user-pool.ts
  packages/@aws-cdk/aws-cognito/test/integ.user-pool-idp.expected.json
  packages/@aws-cdk/aws-cognito/test/integ.user-pool-idp.ts
  packages/@aws-cdk/aws-cognito/test/user-pool-idps/amazon.test.ts
  packages/@aws-cdk/aws-cognito/test/user-pool-idps/base.test.ts
  packages/@aws-cdk/aws-cognito/test/user-pool-idps/facebook.test.ts
Labels: contribution/core

#8455 chore(release): merge release/1.45.0 to master
  CHANGELOG.md
  lerna.json
Labels: pr/no-squash

#8294 fix(autoscaling): can't configure notificationTypes
  packages/@aws-cdk/aws-autoscaling/lib/auto-scaling-group.ts
  packages/@aws-cdk/aws-autoscaling/test/test.auto-scaling-group.ts
Labels: contribution/core

#8481 feat(core,s3-assets): custom bundling docker command
  packages/@aws-cdk/aws-s3-assets/README.md
  packages/@aws-cdk/core/lib/asset-staging.ts
  packages/@aws-cdk/core/lib/bundling.ts
  packages/@aws-cdk/core/test/docker-stub.sh
  packages/@aws-cdk/core/test/test.staging.ts
Labels: contribution/core

#8487 chore(s3-deployment): explicitly pass --no-user to `pip3 install`
  packages/@aws-cdk/aws-s3-deployment/lambda/build.sh
Labels: contribution/core

#8507 fix(rds): rename 'instanceClass' in DatabaseInstance to 'instanceType'
  packages/@aws-cdk/aws-rds/README.md
  packages/@aws-cdk/aws-rds/lib/instance.ts
  packages/@aws-cdk/aws-rds/test/integ.instance.lit.ts
  packages/@aws-cdk/aws-rds/test/test.instance.ts
Labels: contribution/core

#8511 chore(s3-deployment): also pass --no-user in tests
  packages/@aws-cdk/aws-s3-deployment/lambda/test.sh
Labels: contribution/core

#8270 feat(apigateway): define Resources on imported RestApi
  packages/@aws-cdk/aws-apigateway/README.md
  packages/@aws-cdk/aws-apigateway/lib/authorizer.ts
  packages/@aws-cdk/aws-apigateway/lib/authorizers/lambda.ts
  packages/@aws-cdk/aws-apigateway/lib/method.ts
  packages/@aws-cdk/aws-apigateway/lib/resource.ts
  packages/@aws-cdk/aws-apigateway/lib/restapi.ts
  packages/@aws-cdk/aws-apigateway/package.json
  packages/@aws-cdk/aws-apigateway/test/integ.api-definition.asset.expected.json
  packages/@aws-cdk/aws-apigateway/test/integ.api-definition.asset.ts
  packages/@aws-cdk/aws-apigateway/test/integ.restapi-import.lit.expected.json
  packages/@aws-cdk/aws-apigateway/test/integ.restapi-import.lit.ts
  packages/@aws-cdk/aws-apigateway/test/test.authorizer.ts
  packages/@aws-cdk/aws-apigateway/test/test.method.ts
  packages/@aws-cdk/aws-apigateway/test/test.restapi.ts
Labels: contribution/core

#8509 fix(rds): 'engine' is no longer required in DatabaseInstanceReadReplica
  packages/@aws-cdk/aws-rds/README.md
  packages/@aws-cdk/aws-rds/lib/instance.ts
  packages/@aws-cdk/aws-rds/test/test.instance.ts
Labels: contribution/core

#8530 chore(stepfunctions-tasks): update references to the recently replace RunLambaTask task to use LambdaInvoke
  packages/@aws-cdk/aws-stepfunctions-tasks/README.md
Labels: @aws-cdk/aws-stepfunctions-tasks, contribution/core

#8547 feat(cfnspec): cloudformation spec v15.1.0
  packages/@aws-cdk/cfnspec/CHANGELOG.md
  packages/@aws-cdk/cfnspec/build-tools/update.sh
  packages/@aws-cdk/cfnspec/cfn.version
  packages/@aws-cdk/cfnspec/spec-source/000_CloudFormationResourceSpecification.json
  packages/@aws-cdk/cfnspec/spec-source/500_IoT_ProvisioningTemplate_Tags_CorrectItemType_patch.json
  packages/@aws-cdk/cfnspec/spec-source/550_ImageBuilder_Image_Attributes_OutputResources_patch.json
Labels: contribution/core, pr-linter/exempt-readme, pr-linter/exempt-test

#8534 chore: standardize calls to fs.readFileSync to work with all @types/node
  packages/@aws-cdk/aws-s3-assets/test/asset.test.ts
  packages/@aws-cdk/cloud-assembly-schema/lib/manifest.ts
  packages/@aws-cdk/cloud-assembly-schema/test/manifest.test.ts
  tools/cdk-integ-tools/lib/integ-helpers.ts
Labels: contribution/core

#8503 chore(certificate-manager): change naming from Amazon to AWS
  packages/@aws-cdk/aws-certificatemanager/README.md
  packages/@aws-cdk/aws-cloudfront/README.md
  tools/pkglint/lib/aws-service-official-names.json
Labels: contribution/core

#8564 chore(custom-resources): fix broken links in readme
  packages/@aws-cdk/custom-resources/README.md
Labels: contribution/core

#8515 chore(core): verify stack artifacts are written in topological order
  packages/@aws-cdk/core/test/test.app.ts
  packages/@aws-cdk/cx-api/test/cloud-assembly-builder.test.ts
  packages/@aws-cdk/cx-api/test/cloud-assembly.test.ts
Labels: contribution/core

#8577 fix(cli): bootstrapping cannot be retried
  packages/aws-cdk/lib/api/toolkit-info.ts
  packages/aws-cdk/lib/api/util/cloudformation.ts
  packages/aws-cdk/test/api/bootstrap.test.ts
Labels: contribution/core

#8477 chore: option to skip the next directory in foreach.sh
  scripts/foreach.sh
Labels: contribution/core

#8496 feat(cognito): user pool client - disable OAuth easily
  packages/@aws-cdk/aws-cognito/lib/user-pool-client.ts
  packages/@aws-cdk/aws-cognito/test/integ.user-pool-idp.expected.json
  packages/@aws-cdk/aws-cognito/test/integ.user-pool-signup-code.expected.json
  packages/@aws-cdk/aws-cognito/test/integ.user-pool-signup-link.expected.json
  packages/@aws-cdk/aws-cognito/test/user-pool-client.test.ts
Labels: contribution/core, pr-linter/exempt-readme

#8457 feat(cfn-include): add support for CreationPolicy and UpdatePolicy resource attributes
  packages/@aws-cdk/cloudformation-include/.eslintrc.js
  packages/@aws-cdk/cloudformation-include/README.md
  packages/@aws-cdk/cloudformation-include/lib/cfn-include.ts
  packages/@aws-cdk/cloudformation-include/test/invalid-templates.test.ts
  packages/@aws-cdk/cloudformation-include/test/test-templates/invalid/non-existent-resource-attribute.json
  packages/@aws-cdk/cloudformation-include/test/test-templates/resource-attribute-creation-policy.json
  packages/@aws-cdk/cloudformation-include/test/test-templates/resource-attribute-update-policy.json
  packages/@aws-cdk/cloudformation-include/test/valid-templates.test.ts
  packages/@aws-cdk/core/lib/cfn-parse.ts
  packages/@aws-cdk/core/test/test.cfn-parse.ts
  tools/cfn2ts/lib/codegen.ts
Labels: contribution/core

#8299 feat(kms): import an Alias by name
  packages/@aws-cdk/aws-kms/README.md
  packages/@aws-cdk/aws-kms/lib/alias.ts
  packages/@aws-cdk/aws-kms/test/test.alias.ts
Labels: contribution/core

#8562 chore: update stale gh action ancient issue check to 1 year
  .github/workflows/close-stale-issues.yml
Labels: contribution/core

#8575 fix(core): cannot use container assets with new-style synthesis
  packages/@aws-cdk/core/lib/stack-synthesizers/default-synthesizer.ts
  packages/@aws-cdk/core/test/evaluate-cfn.ts
Labels: contribution/core

#8165 feat(cli): new deployment monitoring
  packages/aws-cdk/lib/api/deploy-stack.ts
  packages/aws-cdk/lib/api/util/cloudformation/stack-activity-monitor.ts
  packages/aws-cdk/lib/api/util/display.ts
  packages/aws-cdk/package.json
  yarn.lock
Labels: contribution/core, pr-linter/exempt-readme, pr-linter/exempt-test

#8578 fix(core): s3-deployments don't work with new bootstrap stack
  packages/@aws-cdk/aws-s3-assets/lib/asset.ts
  packages/@aws-cdk/aws-s3-assets/package.json
  packages/@aws-cdk/aws-s3-assets/test/asset.test.ts
  packages/@aws-cdk/aws-s3-deployment/lib/bucket-deployment.ts
  packages/@aws-cdk/aws-s3-deployment/lib/source.ts
  packages/@aws-cdk/aws-s3-deployment/test/test.bucket-deployment.ts
  packages/@aws-cdk/core/lib/assets.ts
  packages/@aws-cdk/core/lib/stack-synthesizers/default-synthesizer.ts
  packages/aws-cdk/lib/api/bootstrap/bootstrap-template.yaml
  packages/aws-cdk/lib/api/bootstrap/deploy-bootstrap.ts
  packages/aws-cdk/test/api/bootstrap2.test.ts
Labels: contribution/core

#8510 feat(rds): multiple security groups in Cluster and Instance
  packages/@aws-cdk/aws-rds/lib/cluster-ref.ts
  packages/@aws-cdk/aws-rds/lib/cluster.ts
  packages/@aws-cdk/aws-rds/lib/props.ts
  packages/@aws-cdk/aws-rds/test/test.cluster.ts
Labels: contribution/core, pr-linter/exempt-readme

#8563 chore: add a github action that auto labels and assigns issues
  .github/ISSUE_TEMPLATE/bug.md
  .github/ISSUE_TEMPLATE/doc.md
  .github/ISSUE_TEMPLATE/feature-request.md
  .github/ISSUE_TEMPLATE/general-issues.md
  .github/workflows/issue-label-assign.yml
Labels: contribution/core

#8626 chore: copy fewer files in MonoCDK
  packages/monocdk-experiment/build-tools/gen.ts
Labels: contribution/core

#8522 feat(cognito): user pools are now in developer preview
  packages/@aws-cdk/aws-cognito/README.md
  packages/@aws-cdk/aws-cognito/package.json
  tools/pkglint/.gitignore
  tools/pkglint/jest.config.js
  tools/pkglint/lib/banners/README.md
  tools/pkglint/lib/banners/features-cfn-stable.md
  tools/pkglint/lib/banners/features-developer-preview.md
  tools/pkglint/lib/banners/features-experimental.md
  tools/pkglint/lib/banners/features-stable.md
  tools/pkglint/lib/rules.ts
  tools/pkglint/package.json
  tools/pkglint/test/rules.test.ts
Labels: @aws-cdk/aws-cognito, contribution/core

#8619 chore(stepfunctions): update README to include an example of importing a state machine
  packages/@aws-cdk/aws-stepfunctions/README.md
Labels: @aws-cdk/aws-stepfunctions, contribution/core

#8628 chore: update auto label gh action to trigger less often
  .github/ISSUE_TEMPLATE/bug.md
  .github/ISSUE_TEMPLATE/doc.md
  .github/ISSUE_TEMPLATE/feature-request.md
  .github/ISSUE_TEMPLATE/general-issues.md
  .github/workflows/issue-label-assign.yml
Labels: contribution/core

#8614 build: speed up tests
  packages/@aws-cdk/aws-cloudformation/test/integ.nested-stacks-nested-export-to-sibling.ts
  packages/@aws-cdk/aws-dynamodb-global/test/integ.dynamodb.global.expected.json
  packages/@aws-cdk/core/lib/construct-compat.ts
  packages/@aws-cdk/core/lib/stack-trace.ts
  packages/@aws-cdk/core/test/test.construct.ts
  packages/@aws-cdk/core/test/test.tokens.ts
  packages/@aws-cdk/core/test/util.ts
  tools/cdk-build-tools/bin/cdk-test.ts
  tools/cdk-build-tools/lib/os.ts
  tools/cdk-integ-tools/bin/cdk-integ-assert.ts
  tools/cdk-integ-tools/bin/cdk-integ.ts
  tools/cdk-integ-tools/lib/integ-helpers.ts
Labels: contribution/core

#8177 chore(stepfunctions-tasks): task state to call Amazon EMR
  packages/@aws-cdk/aws-stepfunctions-tasks/README.md
  packages/@aws-cdk/aws-stepfunctions-tasks/lib/emr/emr-add-step.ts
  packages/@aws-cdk/aws-stepfunctions-tasks/lib/emr/emr-cancel-step.ts
  packages/@aws-cdk/aws-stepfunctions-tasks/lib/emr/emr-create-cluster.ts
  packages/@aws-cdk/aws-stepfunctions-tasks/lib/emr/emr-modify-instance-fleet-by-name.ts
  packages/@aws-cdk/aws-stepfunctions-tasks/lib/emr/emr-modify-instance-group-by-name.ts
  packages/@aws-cdk/aws-stepfunctions-tasks/lib/emr/emr-set-cluster-termination-protection.ts
  packages/@aws-cdk/aws-stepfunctions-tasks/lib/emr/emr-terminate-cluster.ts
  packages/@aws-cdk/aws-stepfunctions-tasks/lib/emr/private/cluster-utils.ts
  packages/@aws-cdk/aws-stepfunctions-tasks/test/emr/emr-add-step.test.ts
  packages/@aws-cdk/aws-stepfunctions-tasks/test/emr/emr-cancel-step.test.ts
  packages/@aws-cdk/aws-stepfunctions-tasks/test/emr/emr-create-cluster.test.ts
  packages/@aws-cdk/aws-stepfunctions-tasks/test/emr/emr-modify-instance-fleet-by-name.test.ts
  packages/@aws-cdk/aws-stepfunctions-tasks/test/emr/emr-modify-instance-group-by-name.test.ts
  packages/@aws-cdk/aws-stepfunctions-tasks/test/emr/emr-set-cluster-termination-protection.test.ts
  packages/@aws-cdk/aws-stepfunctions-tasks/test/emr/emr-terminate-cluster.test.ts
Labels: @aws-cdk/aws-emr, @aws-cdk/aws-stepfunctions, @aws-cdk/aws-stepfunctions-tasks, contribution/core

#8020 chore(aws-events): rebrand of CloudWatch Events to EventBridge
  packages/@aws-cdk/aws-events-targets/README.md
  packages/@aws-cdk/aws-events-targets/lib/aws-api.ts
  packages/@aws-cdk/aws-events-targets/lib/batch.ts
  packages/@aws-cdk/aws-events-targets/lib/codebuild.ts
  packages/@aws-cdk/aws-events-targets/lib/codepipeline.ts
  packages/@aws-cdk/aws-events-targets/lib/ecs-task.ts
  packages/@aws-cdk/aws-events-targets/lib/lambda.ts
  packages/@aws-cdk/aws-events-targets/lib/sns.ts
  packages/@aws-cdk/aws-events-targets/lib/sqs.ts
  packages/@aws-cdk/aws-events-targets/lib/state-machine.ts
  packages/@aws-cdk/aws-events-targets/lib/util.ts
  packages/@aws-cdk/aws-events-targets/package.json
  packages/@aws-cdk/aws-events/README.md
  packages/@aws-cdk/aws-events/lib/event-bus.ts
  packages/@aws-cdk/aws-events/lib/input.ts
  packages/@aws-cdk/aws-events/lib/on-event-options.ts
  packages/@aws-cdk/aws-events/lib/rule-ref.ts
  packages/@aws-cdk/aws-events/lib/rule.ts
  packages/@aws-cdk/aws-events/lib/schedule.ts
  packages/@aws-cdk/aws-events/lib/target.ts
  packages/@aws-cdk/aws-events/package.json
  tools/pkglint/lib/aws-service-official-names.json
Labels: contribution/core

#8587 chore(ecs): fix typo
  packages/@aws-cdk/aws-ecs/lib/container-definition.ts
Labels: @aws-cdk/aws-ecs

#8558 feat(awslint): publish as an external module
  packages/awslint/.gitignore
  packages/awslint/.npmignore
  packages/awslint/LICENSE
  packages/awslint/NOTICE
  packages/awslint/README.md
  packages/awslint/bin/awslint
  packages/awslint/bin/awslint.ts
  packages/awslint/lib/index.ts
  packages/awslint/lib/linter.ts
  packages/awslint/lib/rules/api.ts
  packages/awslint/lib/rules/attributes.ts
  packages/awslint/lib/rules/cfn-resource.ts
  packages/awslint/lib/rules/cloudwatch-events.ts
  packages/awslint/lib/rules/construct.ts
  packages/awslint/lib/rules/core-types.ts
  packages/awslint/lib/rules/docs.ts
  packages/awslint/lib/rules/durations.ts
  packages/awslint/lib/rules/exports.ts
  packages/awslint/lib/rules/imports.ts
  packages/awslint/lib/rules/index.ts
  packages/awslint/lib/rules/integrations.ts
  packages/awslint/lib/rules/module.ts
  packages/awslint/lib/rules/no-unused-type.ts
  packages/awslint/lib/rules/public-static-properties.ts
  packages/awslint/lib/rules/resource.ts
  packages/awslint/lib/rules/util.ts
  packages/awslint/load.sh
  packages/awslint/package.json
  packages/awslint/tsconfig.json
  packages/awslint/tslint.yaml
Labels: pr-linter/exempt-readme, pr-linter/exempt-test

#8651 feat(cloudtrail): cloudtrail module is now stable!
  packages/@aws-cdk/aws-cloudtrail/README.md
  packages/@aws-cdk/aws-cloudtrail/lib/cloudtrail.ts
  packages/@aws-cdk/aws-cloudtrail/package.json
  packages/@aws-cdk/aws-cloudtrail/test/cloudtrail.test.ts
Labels: @aws-cdk/aws-cloudtrail, contribution/core

#8655 chore(awslint): remove 'main' key from package.json
  packages/awslint/package.json
Labels: contribution/core

#8632 feat: upgrade JSII to version 1.7.0
  package.json
  packages/@aws-cdk/aws-apigateway/test/authorizers/integ.request-authorizer.expected.json
  packages/@aws-cdk/aws-apigateway/test/authorizers/integ.token-authorizer-iam-role.expected.json
  packages/@aws-cdk/aws-apigateway/test/authorizers/integ.token-authorizer.expected.json
  packages/@aws-cdk/aws-cloudformation/test/integ.core-custom-resources.expected.json
  packages/@aws-cdk/aws-cognito/test/integ.user-pool-domain-cfdist.expected.json
  packages/@aws-cdk/aws-dynamodb/test/integ.global.expected.json
  packages/@aws-cdk/aws-ecr/test/integ.imagescan.expected.json
  packages/@aws-cdk/aws-eks/test/integ.eks-cluster.expected.json
  packages/@aws-cdk/aws-events-targets/test/aws-api/integ.aws-api.expected.json
  packages/@aws-cdk/aws-iam/test/integ.condition-with-ref.expected.json
  packages/@aws-cdk/aws-iam/test/integ.oidc-provider.expected.json
  packages/@aws-cdk/aws-lambda-nodejs/test/integ.function.expected.json
  packages/@aws-cdk/aws-lambda/test/integ.current-version.expected.json
  packages/@aws-cdk/aws-lambda/test/integ.layer-version.lit.expected.json
  packages/@aws-cdk/aws-lambda/test/integ.log-retention.expected.json
  packages/@aws-cdk/aws-lambda/test/test.layers.ts
  packages/@aws-cdk/aws-rds/test/integ.instance.lit.expected.json
  packages/@aws-cdk/aws-stepfunctions-tasks/test/integ.evaluate-expression.expected.json
  packages/@aws-cdk/core/test/custom-resource-provider/test.custom-resource-provider.ts
  packages/@aws-cdk/custom-resources/test/aws-custom-resource/integ.aws-custom-resource.expected.json
  packages/@aws-cdk/custom-resources/test/provider-framework/integ.provider.expected.json
  packages/@monocdk-experiment/rewrite-imports/package.json
  packages/awslint/package.json
  packages/cdk-dasm/package.json
  packages/decdk/package.json
  tools/cdk-build-tools/package.json
  tools/cfn2ts/package.json
  tools/pkglint/package.json
  tools/yarn-cling/package.json
  yarn.lock
Labels: pr-linter/exempt-readme, pr-linter/exempt-test

#8663 chore(release): merge release/1.46.0 to master
  CHANGELOG.md
  lerna.json
Labels: pr/no-squash

#8675 fix(cli): crash on tiny reported terminal width
  packages/aws-cdk/lib/api/util/cloudformation/stack-activity-monitor.ts
Labels: contribution/core, package/tools, pr-linter/exempt-test

#8673 fix(appsync): Not to throw an Error even if 'additionalAuthorizationModes' is undefined
  packages/@aws-cdk/aws-appsync/lib/graphqlapi.ts
  packages/@aws-cdk/aws-appsync/test/appsync.test.ts
Labels: @aws-cdk/aws-appsync

#8482 chore: incorporate cdk-assets-schema into cloud-assembly-schema
  allowed-breaking-changes.txt
  package.json
  packages/@aws-cdk/cdk-assets-schema/README.md
  packages/@aws-cdk/cdk-assets-schema/lib/index.ts
  packages/@aws-cdk/cdk-assets-schema/lib/private/my-package-json.ts
  packages/@aws-cdk/cdk-assets-schema/lib/private/schema-helpers.ts
  packages/@aws-cdk/cdk-assets-schema/lib/validate.ts
  packages/@aws-cdk/cdk-assets-schema/package.json
  packages/@aws-cdk/cdk-assets-schema/test/dummy.test.ts
  packages/@aws-cdk/cloud-assembly-schema/.gitignore
  packages/@aws-cdk/cloud-assembly-schema/lib/assets/aws-destination.ts
  packages/@aws-cdk/cloud-assembly-schema/lib/assets/docker-image-asset.ts
  packages/@aws-cdk/cloud-assembly-schema/lib/assets/file-asset.ts
  packages/@aws-cdk/cloud-assembly-schema/lib/assets/index.ts
  packages/@aws-cdk/cloud-assembly-schema/lib/assets/schema.ts
  packages/@aws-cdk/cloud-assembly-schema/lib/cloud-assembly/artifact-schema.ts
  packages/@aws-cdk/cloud-assembly-schema/lib/cloud-assembly/context-queries.ts
  packages/@aws-cdk/cloud-assembly-schema/lib/cloud-assembly/index.ts
  packages/@aws-cdk/cloud-assembly-schema/lib/cloud-assembly/metadata-schema.ts
  packages/@aws-cdk/cloud-assembly-schema/lib/cloud-assembly/schema.ts
  packages/@aws-cdk/cloud-assembly-schema/lib/index.ts
  packages/@aws-cdk/cloud-assembly-schema/lib/manifest.ts
  packages/@aws-cdk/cloud-assembly-schema/schema/assets.schema.json
  packages/@aws-cdk/cloud-assembly-schema/scripts/update-schema.sh
  packages/@aws-cdk/cloud-assembly-schema/scripts/update-schema.ts
  packages/@aws-cdk/cloud-assembly-schema/test/assets.test.ts
  packages/@aws-cdk/cloud-assembly-schema/test/manifest.test.ts
  packages/@aws-cdk/cloud-assembly-schema/test/schema.test.ts
  packages/@aws-cdk/core/lib/stack-synthesizers/default-synthesizer.ts
  packages/@aws-cdk/core/package.json
  packages/@aws-cdk/core/test/stack-synthesis/test.new-style-synthesis.ts
  packages/@aws-cdk/core/test/test.app.ts
  packages/@aws-cdk/core/test/test.runtime-info.ts
  packages/aws-cdk/lib/assets.ts
  packages/aws-cdk/lib/util/asset-manifest-builder.ts
  packages/aws-cdk/package.json
  packages/cdk-assets/lib/asset-manifest.ts
  packages/cdk-assets/lib/private/handlers/files.ts
  packages/cdk-assets/package.json
  packages/cdk-assets/test/docker-images.test.ts
  packages/cdk-assets/test/files.test.ts
  packages/cdk-assets/test/manifest.test.ts
  packages/cdk-assets/test/placeholders.test.ts
  packages/cdk-assets/test/progress.test.ts
  packages/cdk-assets/test/zipping.test.ts
  packages/cdk-assets/tsconfig.json
  packages/decdk/package.json
  packages/monocdk-experiment/package.json
  tools/pkglint/lib/rules.ts
Labels: contribution/core

#8677 fix(cli): cannot change policies or trust after initial bootstrap
  packages/aws-cdk/lib/api/deploy-stack.ts
  packages/aws-cdk/lib/api/util/cloudformation.ts
  packages/aws-cdk/test/api/deploy-stack.test.ts
  packages/aws-cdk/test/util/cloudformation.test.ts
Labels: contribution/core, package/tools

#8708 chore: make @aws-cdk/cdk-assets-schema/index.d.ts a module
  packages/@aws-cdk/cdk-assets-schema/lib/index.ts
Labels: contribution/core

#8466 feat(stepfunctions-tasks): task constructs to call DynamoDB APIs
  packages/@aws-cdk/aws-stepfunctions-tasks/README.md
  packages/@aws-cdk/aws-stepfunctions-tasks/lib/dynamodb/call-dynamodb.ts
  packages/@aws-cdk/aws-stepfunctions-tasks/lib/dynamodb/delete-item.ts
  packages/@aws-cdk/aws-stepfunctions-tasks/lib/dynamodb/get-item.ts
  packages/@aws-cdk/aws-stepfunctions-tasks/lib/dynamodb/private/utils.ts
  packages/@aws-cdk/aws-stepfunctions-tasks/lib/dynamodb/put-item.ts
  packages/@aws-cdk/aws-stepfunctions-tasks/lib/dynamodb/shared-types.ts
  packages/@aws-cdk/aws-stepfunctions-tasks/lib/dynamodb/update-item.ts
  packages/@aws-cdk/aws-stepfunctions-tasks/lib/index.ts
  packages/@aws-cdk/aws-stepfunctions-tasks/package.json
  packages/@aws-cdk/aws-stepfunctions-tasks/test/dynamodb/call-dynamodb.test.ts
  packages/@aws-cdk/aws-stepfunctions-tasks/test/dynamodb/delete-item.test.ts
  packages/@aws-cdk/aws-stepfunctions-tasks/test/dynamodb/get-item.test.ts
  packages/@aws-cdk/aws-stepfunctions-tasks/test/dynamodb/integ.call-dynamodb.expected.json
  packages/@aws-cdk/aws-stepfunctions-tasks/test/dynamodb/integ.call-dynamodb.ts
  packages/@aws-cdk/aws-stepfunctions-tasks/test/dynamodb/put-item.test.ts
  packages/@aws-cdk/aws-stepfunctions-tasks/test/dynamodb/shared-types.test.ts
  packages/@aws-cdk/aws-stepfunctions-tasks/test/dynamodb/update-item.test.ts
Labels: @aws-cdk/aws-stepfunctions-tasks, contribution/core

#8529 feat(cfn-include): support logical id overrides
  packages/@aws-cdk/cloudformation-include/lib/cfn-include.ts
  packages/@aws-cdk/cloudformation-include/test/invalid-templates.test.ts
  packages/@aws-cdk/cloudformation-include/test/test-templates/invalid/bucket-policy-without-bucket.json
  packages/@aws-cdk/cloudformation-include/test/test-templates/invalid/getting-attribute-of-a-non-existent-resource.json
  packages/@aws-cdk/cloudformation-include/test/test-templates/invalid/ref-ing-a-non-existent-element.json
  packages/@aws-cdk/cloudformation-include/test/valid-templates.test.ts
  packages/@aws-cdk/core/lib/cfn-parse.ts
  packages/@aws-cdk/core/lib/from-cfn.ts
  packages/@aws-cdk/core/test/test.cfn-parse.ts
  tools/cfn2ts/lib/codegen.ts
Labels: contribution/core, pr-linter/exempt-readme

#8711 fix(toolkit): CLI tool fails on CloudFormation Throttling
  packages/aws-cdk/lib/api/aws-auth/sdk.ts
Labels: contribution/core, pr-linter/exempt-readme, pr-linter/exempt-test

#8701 feat(ec2): add 6xlarge InstanceSize
  packages/@aws-cdk/aws-ec2/lib/instance-types.ts
  packages/@aws-cdk/aws-ec2/package.json
Labels: @aws-cdk/aws-ec2, contribution/core, pr-linter/exempt-readme, pr-linter/exempt-test

#8653 fix(backup): vault name may exceed 50 characters
  packages/@aws-cdk/aws-backup/README.md
  packages/@aws-cdk/aws-backup/lib/vault.ts
  packages/@aws-cdk/aws-backup/package.json
  packages/@aws-cdk/aws-backup/test/integ.backup.expected.json
  packages/@aws-cdk/aws-backup/test/vault.test.ts
Labels: @aws-cdk/aws-backup

#8647 feat(stepfunctions): class for working with Json paths to retrieve state machine data and context
  packages/@aws-cdk/aws-stepfunctions-tasks/README.md
  packages/@aws-cdk/aws-stepfunctions-tasks/lib/ecs/run-ecs-task-base.ts
  packages/@aws-cdk/aws-stepfunctions-tasks/lib/evaluate-expression.ts
  packages/@aws-cdk/aws-stepfunctions-tasks/lib/lambda/invoke.ts
  packages/@aws-cdk/aws-stepfunctions-tasks/lib/lambda/run-lambda-task.ts
  packages/@aws-cdk/aws-stepfunctions-tasks/lib/sagemaker/base-types.ts
  packages/@aws-cdk/aws-stepfunctions-tasks/lib/sagemaker/create-training-job.ts
  packages/@aws-cdk/aws-stepfunctions-tasks/lib/sns/publish-to-topic.ts
  packages/@aws-cdk/aws-stepfunctions-tasks/lib/sns/publish.ts
  packages/@aws-cdk/aws-stepfunctions-tasks/lib/sqs/send-message.ts
  packages/@aws-cdk/aws-stepfunctions-tasks/lib/sqs/send-to-queue.ts
  packages/@aws-cdk/aws-stepfunctions-tasks/lib/start-execution.ts
  packages/@aws-cdk/aws-stepfunctions-tasks/lib/stepfunctions/start-execution.ts
  packages/@aws-cdk/aws-stepfunctions-tasks/test/batch/integ.run-batch-job.ts
  packages/@aws-cdk/aws-stepfunctions-tasks/test/batch/integ.submit-job.ts
  packages/@aws-cdk/aws-stepfunctions-tasks/test/batch/run-batch-job.test.ts
  packages/@aws-cdk/aws-stepfunctions-tasks/test/batch/submit-job.test.ts
  packages/@aws-cdk/aws-stepfunctions-tasks/test/dynamodb/integ.call-dynamodb.ts
  packages/@aws-cdk/aws-stepfunctions-tasks/test/ecs/ecs-tasks.test.ts
  packages/@aws-cdk/aws-stepfunctions-tasks/test/ecs/integ.ec2-task.ts
  packages/@aws-cdk/aws-stepfunctions-tasks/test/ecs/integ.fargate-task.ts
  packages/@aws-cdk/aws-stepfunctions-tasks/test/emr/emr-add-step.test.ts
  packages/@aws-cdk/aws-stepfunctions-tasks/test/emr/emr-create-cluster.test.ts
  packages/@aws-cdk/aws-stepfunctions-tasks/test/emr/emr-modify-instance-fleet-by-name.test.ts
  packages/@aws-cdk/aws-stepfunctions-tasks/test/emr/emr-modify-instance-group-by-name.test.ts
  packages/@aws-cdk/aws-stepfunctions-tasks/test/integ.start-execution.ts
  packages/@aws-cdk/aws-stepfunctions-tasks/test/lambda/integ.invoke-function.ts
  packages/@aws-cdk/aws-stepfunctions-tasks/test/lambda/invoke-function.test.ts
  packages/@aws-cdk/aws-stepfunctions-tasks/test/lambda/invoke.test.ts
  packages/@aws-cdk/aws-stepfunctions-tasks/test/lambda/run-lambda-task.test.ts
  packages/@aws-cdk/aws-stepfunctions-tasks/test/sagemaker/create-training-job.test.ts
  packages/@aws-cdk/aws-stepfunctions-tasks/test/sagemaker/create-transform-job.test.ts
  packages/@aws-cdk/aws-stepfunctions-tasks/test/sns/publish-to-topic.test.ts
  packages/@aws-cdk/aws-stepfunctions-tasks/test/sns/publish.test.ts
  packages/@aws-cdk/aws-stepfunctions-tasks/test/sqs/send-message.test.ts
  packages/@aws-cdk/aws-stepfunctions-tasks/test/sqs/send-to-queue.test.ts
  packages/@aws-cdk/aws-stepfunctions-tasks/test/start-execution.test.ts
  packages/@aws-cdk/aws-stepfunctions-tasks/test/stepfunctions/integ.start-execution.ts
  packages/@aws-cdk/aws-stepfunctions-tasks/test/stepfunctions/start-execution.test.ts
  packages/@aws-cdk/aws-stepfunctions/README.md
  packages/@aws-cdk/aws-stepfunctions/lib/fields.ts
  packages/@aws-cdk/aws-stepfunctions/lib/input.ts
  packages/@aws-cdk/aws-stepfunctions/lib/states/map.ts
  packages/@aws-cdk/aws-stepfunctions/lib/states/parallel.ts
  packages/@aws-cdk/aws-stepfunctions/lib/states/pass.ts
  packages/@aws-cdk/aws-stepfunctions/lib/states/state.ts
  packages/@aws-cdk/aws-stepfunctions/lib/states/succeed.ts
  packages/@aws-cdk/aws-stepfunctions/lib/states/task-base.ts
  packages/@aws-cdk/aws-stepfunctions/lib/states/task.ts
  packages/@aws-cdk/aws-stepfunctions/test/fields.test.ts
  packages/@aws-cdk/aws-stepfunctions/test/map.test.ts
  packages/@aws-cdk/aws-stepfunctions/test/state-machine-resources.test.ts
Labels: @aws-cdk/aws-stepfunctions, contribution/core

#8722 chore: small updates to auto label/assign action
  .github/ISSUE_TEMPLATE/bug.md
  .github/ISSUE_TEMPLATE/doc.md
  .github/ISSUE_TEMPLATE/feature-request.md
  .github/ISSUE_TEMPLATE/general-issues.md
  .github/workflows/issue-label-assign.yml
Labels: contribution/core

#8735 chore(release): merge release/1.47.0 to master
  CHANGELOG.md
  lerna.json
Labels: pr/no-squash

#8730 chore(stepfunctions-tasks): update tests to use 'JsonPath' instead of 'Data' class
  packages/@aws-cdk/aws-stepfunctions-tasks/test/dynamodb/delete-item.test.ts
  packages/@aws-cdk/aws-stepfunctions-tasks/test/dynamodb/get-item.test.ts
  packages/@aws-cdk/aws-stepfunctions-tasks/test/dynamodb/integ.call-dynamodb.ts
  packages/@aws-cdk/aws-stepfunctions-tasks/test/dynamodb/put-item.test.ts
  packages/@aws-cdk/aws-stepfunctions-tasks/test/dynamodb/shared-types.test.ts
  packages/@aws-cdk/aws-stepfunctions-tasks/test/dynamodb/update-item.test.ts
Labels: @aws-cdk/aws-stepfunctions-tasks, contribution/core

#8715 fix(elbv2): Add missing accounts to ELBv2 Log Delivery.
  packages/@aws-cdk/aws-elasticloadbalancingv2/lib/shared/base-load-balancer.ts
Labels: pr-linter/exempt-test

#8622 fix(cognito): cannot add multiple route53 targets to the same user pool domain
  packages/@aws-cdk/aws-cognito/lib/user-pool-domain.ts
  packages/@aws-cdk/aws-cognito/test/user-pool-domain.test.ts
Labels: @aws-cdk/aws-cognito, contribution/core

#8723 fix(cli): post install warnings are not clearly visible when running cdk init
  packages/aws-cdk/lib/init.ts
Labels: contribution/core, package/tools, pr-linter/exempt-test

#8741 fix(s3-notifications): broken permissions query in `LambdaDestination`
  packages/@aws-cdk/aws-s3-notifications/lib/lambda.ts
  packages/@aws-cdk/aws-s3-notifications/test/lambda/lambda.test.ts
Labels: contribution/core

#8749 feat(cli): support multiple verbosity levels
  packages/aws-cdk/bin/cdk.ts
  packages/aws-cdk/lib/api/aws-auth/sdk.ts
  packages/aws-cdk/lib/api/util/cloudformation/stack-activity-monitor.ts
  packages/aws-cdk/lib/logging.ts
  packages/aws-cdk/test/api/exec.test.ts
  packages/aws-cdk/test/api/sdk-provider.test.ts
Labels: contribution/core, pr-linter/exempt-readme

#8756 docs: tweak docstring for ServiceProps.namespace
  packages/@aws-cdk/aws-servicediscovery/lib/service.ts
Labels: @aws-cdk/aws-servicediscovery, contribution/core, docs/inline

#8755 fix(cli): unable to use "legacy" bootstrap with --public-access-block-configuration=false
  packages/aws-cdk/lib/api/bootstrap/legacy-template.ts
  packages/aws-cdk/test/integ/cli/bootstrapping.integtest.ts
Labels: contribution/core

#8747 fix(route53-targets): A/AAAA Alias Record to ELB cannot resolve IPv6 addresses
  packages/@aws-cdk/aws-ecs-patterns/test/ec2/test.l3s.ts
  packages/@aws-cdk/aws-ecs-patterns/test/fargate/integ.load-balanced-fargate-service.expected.json
  packages/@aws-cdk/aws-route53-targets/README.md
  packages/@aws-cdk/aws-route53-targets/lib/classic-load-balancer-target.ts
  packages/@aws-cdk/aws-route53-targets/lib/load-balancer-target.ts
  packages/@aws-cdk/aws-route53-targets/test/classic-load-balancer-target.test.ts
  packages/@aws-cdk/aws-route53-targets/test/integ.alb-alias-target.expected.json
  packages/@aws-cdk/aws-route53-targets/test/load-balancer-target.test.ts
Labels: @aws-cdk/aws-route53-targets

#8777 fix(rewrite): script ignores list of files
  packages/@monocdk-experiment/rewrite-imports/bin/rewrite-imports.ts
Labels: contribution/core

#8768 chore(stepfunctions): make renderTask internal for the task state and derived classes
  packages/@aws-cdk/aws-stepfunctions-tasks/lib/batch/submit-job.ts
  packages/@aws-cdk/aws-stepfunctions-tasks/lib/dynamodb/delete-item.ts
  packages/@aws-cdk/aws-stepfunctions-tasks/lib/dynamodb/get-item.ts
  packages/@aws-cdk/aws-stepfunctions-tasks/lib/dynamodb/put-item.ts
  packages/@aws-cdk/aws-stepfunctions-tasks/lib/dynamodb/update-item.ts
  packages/@aws-cdk/aws-stepfunctions-tasks/lib/emr/emr-add-step.ts
  packages/@aws-cdk/aws-stepfunctions-tasks/lib/emr/emr-cancel-step.ts
  packages/@aws-cdk/aws-stepfunctions-tasks/lib/emr/emr-create-cluster.ts
  packages/@aws-cdk/aws-stepfunctions-tasks/lib/emr/emr-modify-instance-fleet-by-name.ts
  packages/@aws-cdk/aws-stepfunctions-tasks/lib/emr/emr-modify-instance-group-by-name.ts
  packages/@aws-cdk/aws-stepfunctions-tasks/lib/emr/emr-set-cluster-termination-protection.ts
  packages/@aws-cdk/aws-stepfunctions-tasks/lib/emr/emr-terminate-cluster.ts
  packages/@aws-cdk/aws-stepfunctions-tasks/lib/glue/start-job-run.ts
  packages/@aws-cdk/aws-stepfunctions-tasks/lib/lambda/invoke.ts
  packages/@aws-cdk/aws-stepfunctions-tasks/lib/sagemaker/create-training-job.ts
  packages/@aws-cdk/aws-stepfunctions-tasks/lib/sagemaker/create-transform-job.ts
  packages/@aws-cdk/aws-stepfunctions-tasks/lib/sns/publish.ts
  packages/@aws-cdk/aws-stepfunctions-tasks/lib/sqs/send-message.ts
  packages/@aws-cdk/aws-stepfunctions-tasks/lib/stepfunctions/start-execution.ts
  packages/@aws-cdk/aws-stepfunctions/lib/states/task-base.ts
  packages/@aws-cdk/aws-stepfunctions/test/task-base.test.ts
Labels: @aws-cdk/aws-stepfunctions, @aws-cdk/aws-stepfunctions-tasks, contribution/core

#8555 feat(stepfunctions-tasks): evaluate expression as a task construct
  packages/@aws-cdk/aws-stepfunctions-tasks/README.md
  packages/@aws-cdk/aws-stepfunctions-tasks/lib/evaluate-expression.ts
  packages/@aws-cdk/aws-stepfunctions-tasks/test/evaluate-expression.test.ts
  packages/@aws-cdk/aws-stepfunctions-tasks/test/integ.evaluate-expression.expected.json
  packages/@aws-cdk/aws-stepfunctions-tasks/test/integ.evaluate-expression.ts
Labels: @aws-cdk/aws-stepfunctions-tasks, contribution/core

#8782 chore(scripts): buildup should only build
  scripts/buildup
Labels: contribution/core

#8785 fix(apigateway): error defining lambda integration on imported RestApi
  packages/@aws-cdk/aws-apigateway/lib/integrations/lambda.ts
  packages/@aws-cdk/aws-apigateway/lib/method.ts
  packages/@aws-cdk/aws-apigateway/lib/restapi.ts
  packages/@aws-cdk/aws-apigateway/test/test.lambda.ts
  packages/@aws-cdk/aws-apigateway/test/test.method.ts
Labels: contribution/core

#8784 chore(scripts): builddown should use foreach to support resuming builds
  scripts/builddown
  scripts/foreach.sh
Labels: contribution/core

#8805 feat(autoscaling): bring your own security group
  packages/@aws-cdk/aws-autoscaling/README.md
  packages/@aws-cdk/aws-autoscaling/lib/auto-scaling-group.ts
  packages/@aws-cdk/aws-autoscaling/test/test.auto-scaling-group.ts
Labels: contribution/core

#8806 chore(release): merge release/1.47.1 to master
  CHANGELOG.md
  lerna.json
Labels: pr/no-squash

#8811 chore(ec2): convert tests to Jest
  packages/@aws-cdk/aws-ec2/.gitignore
  packages/@aws-cdk/aws-ec2/.npmignore
  packages/@aws-cdk/aws-ec2/jest.config.js
  packages/@aws-cdk/aws-ec2/package.json
  packages/@aws-cdk/aws-ec2/test/bastion-host.test.ts
  packages/@aws-cdk/aws-ec2/test/connections.test.ts
  packages/@aws-cdk/aws-ec2/test/instance.test.ts
  packages/@aws-cdk/aws-ec2/test/l1.test.ts
  packages/@aws-cdk/aws-ec2/test/machine-image.test.ts
  packages/@aws-cdk/aws-ec2/test/network-utils.test.ts
  packages/@aws-cdk/aws-ec2/test/security-group.test.ts
  packages/@aws-cdk/aws-ec2/test/test.l1.ts
  packages/@aws-cdk/aws-ec2/test/test.machine-image.ts
  packages/@aws-cdk/aws-ec2/test/userdata.test.ts
  packages/@aws-cdk/aws-ec2/test/volume.test.ts
  packages/@aws-cdk/aws-ec2/test/vpc-endpoint-service.test.ts
  packages/@aws-cdk/aws-ec2/test/vpc-endpoint.test.ts
  packages/@aws-cdk/aws-ec2/test/vpc-flow-logs.test.ts
  packages/@aws-cdk/aws-ec2/test/vpc.from-lookup.test.ts
  packages/@aws-cdk/aws-ec2/test/vpc.test.ts
  packages/@aws-cdk/aws-ec2/test/vpn.test.ts
  tools/nodeunit-shim/.gitignore
  tools/nodeunit-shim/README.md
  tools/nodeunit-shim/index.ts
  tools/nodeunit-shim/package.json
  tools/nodeunit-shim/tsconfig.json
Labels: contribution/core

#8807 feat(cfnspec): cloudformation spec v16.0.0
  packages/@aws-cdk/cfnspec/CHANGELOG.md
  packages/@aws-cdk/cfnspec/cfn.version
  packages/@aws-cdk/cfnspec/spec-source/000_CloudFormationResourceSpecification.json
  packages/@aws-cdk/cfnspec/spec-source/000_sam.spec.json
Labels: pr-linter/exempt-readme, pr-linter/exempt-test
