Repository aws/aws-cdk, pull requests merged in 2020-07, with the labels that each got.

#8817 feat(ec2): natGateways=0 disables private subnets
  packages/@aws-cdk/aws-ec2/README.md
  packages/@aws-cdk/aws-ec2/lib/vpc.ts
  packages/@aws-cdk/aws-ec2/test/vpc.test.ts
Labels: @aws-cdk/aws-ec2

#8823 chore(stepfunctions): minor updates to README
  packages/@aws-cdk/aws-stepfunctions/README.md
Labels: @aws-cdk/aws-stepfunctions, contribution/core

#8834 chore(release): merge release/1.48.0 to master
  CHANGELOG.md
  lerna.json
Labels: pr/no-squash

#8780 feat(eks): document how to define dependencies for resources and charts
  packages/@aws-cdk/aws-eks/README.md
  packages/@aws-cdk/aws-eks/test/integ.eks-cluster.expected.json
  packages/@aws-cdk/aws-eks/test/integ.eks-cluster.ts
Labels: contribution/core

#8798 fix(elasticloadbalancingv2): dualstack ALB missing default IPv6 ingress rule
  packages/@aws-cdk/aws-elasticloadbalancingv2/lib/alb/application-listener.ts
  packages/@aws-cdk/aws-elasticloadbalancingv2/lib/alb/application-load-balancer.ts
  packages/@aws-cdk/aws-elasticloadbalancingv2/test/alb/test.listener.ts
  packages/@aws-cdk/aws-elasticloadbalancingv2/test/integ.alb.dualstack.expected.json
  packages/@aws-cdk/aws-elasticloadbalancingv2/test/integ.alb.dualstack.ts
Labels: @aws-cdk/aws-elasticloadbalancingv2

#8813 fix(apigateway): permission error in lambda integration when function name is modified
  packages/@aws-cdk/aws-apigateway/lib/integration.ts
  packages/@aws-cdk/aws-apigateway/lib/integrations/aws.ts
  packages/@aws-cdk/aws-apigateway/lib/integrations/lambda.ts
  packages/@aws-cdk/aws-apigateway/lib/method.ts
  packages/@aws-cdk/aws-apigateway/test/integ.restapi.multistack.expected.json
  packages/@aws-cdk/aws-apigateway/test/test.lambda.ts
Labels: contribution/core

#8845 fix(codebuild): project didn't have permissions to retrieve secret of image with credentials
  packages/@aws-cdk/aws-codebuild/lib/project.ts
  packages/@aws-cdk/aws-codebuild/test/integ.docker-registry.lit.expected.json
Labels: contribution/core

#8855 fix(eks): kubectl resources fail before fargate profiles are created
  packages/@aws-cdk/aws-eks/lib/cluster-resource.ts
  packages/@aws-cdk/aws-eks/lib/cluster.ts
  packages/@aws-cdk/aws-eks/lib/helm-chart.ts
  packages/@aws-cdk/aws-eks/lib/k8s-patch.ts
  packages/@aws-cdk/aws-eks/lib/k8s-resource.ts
  packages/@aws-cdk/aws-eks/lib/kubectl-provider.ts
  packages/@aws-cdk/aws-eks/test/integ.eks-cluster.expected.json
  packages/@aws-cdk/aws-eks/test/test.cluster.ts
  packages/@aws-cdk/aws-eks/test/test.fargate.ts
Labels: contribution/core

#8860 chore(release): 1.49.0
  CHANGELOG.md
  lerna.json
  packages/@aws-cdk/aws-apigateway/lib/integration.ts
  packages/@aws-cdk/aws-apigateway/lib/integrations/aws.ts
  packages/@aws-cdk/aws-apigateway/lib/integrations/lambda.ts
  packages/@aws-cdk/aws-apigateway/lib/method.ts
  packages/@aws-cdk/aws-apigateway/test/integ.restapi.multistack.expected.json
  packages/@aws-cdk/aws-apigateway/test/test.lambda.ts
  packages/@aws-cdk/aws-cloudfront/package.json
  packages/@aws-cdk/aws-cloudtrail/package.json
  packages/@aws-cdk/aws-codebuild/lib/project.ts
  packages/@aws-cdk/aws-codebuild/package.json
  packages/@aws-cdk/aws-codebuild/test/integ.docker-registry.lit.expected.json
  packages/@aws-cdk/aws-codecommit/package.json
  packages/@aws-cdk/aws-dynamodb/package.json
  packages/@aws-cdk/aws-eks/README.md
  packages/@aws-cdk/aws-eks/package.json
  packages/@aws-cdk/aws-eks/test/integ.eks-cluster.expected.json
  packages/@aws-cdk/aws-eks/test/integ.eks-cluster.ts
  packages/@aws-cdk/aws-elasticloadbalancingv2/lib/alb/application-listener.ts
  packages/@aws-cdk/aws-elasticloadbalancingv2/lib/alb/application-load-balancer.ts
  packages/@aws-cdk/aws-elasticloadbalancingv2/test/alb/test.listener.ts
  packages/@aws-cdk/aws-elasticloadbalancingv2/test/integ.alb.dualstack.expected.json
  packages/@aws-cdk/aws-elasticloadbalancingv2/test/integ.alb.dualstack.ts
  packages/@aws-cdk/aws-events-targets/package.json
  packages/@aws-cdk/aws-lambda-nodejs/lib/bundling.ts
  packages/@aws-cdk/aws-lambda-nodejs/lib/function.ts
  packages/@aws-cdk/aws-lambda-nodejs/lib/package-json-manager.ts
  packages/@aws-cdk/aws-lambda-nodejs/lib/util.ts
  packages/@aws-cdk/aws-lambda-nodejs/test/bundling.test.ts
  packages/@aws-cdk/aws-lambda-nodejs/test/util.test.ts
  packages/@aws-cdk/aws-lambda/package.json
  packages/@aws-cdk/aws-rds/README.md
  packages/@aws-cdk/aws-rds/lib/cluster-ref.ts
  packages/@aws-cdk/aws-rds/lib/cluster.ts
  packages/@aws-cdk/aws-rds/lib/index.ts
  packages/@aws-cdk/aws-rds/lib/instance.ts
  packages/@aws-cdk/aws-rds/lib/proxy.ts
  packages/@aws-cdk/aws-rds/test/integ.proxy.expected.json
  packages/@aws-cdk/aws-rds/test/integ.proxy.ts
  packages/@aws-cdk/aws-rds/test/test.proxy.ts
  packages/@aws-cdk/aws-route53/package.json
  packages/@aws-cdk/aws-secretsmanager/lib/secret.ts
  packages/@aws-cdk/aws-sqs/package.json
  packages/@aws-cdk/aws-stepfunctions/README.md
  packages/@aws-cdk/core/lib/bundling.ts
  packages/@aws-cdk/core/test/test.bundling.ts
  packages/@aws-cdk/core/test/test.staging.ts
  packages/@aws-cdk/custom-resources/package.json
  packages/aws-cdk/package.json
  packages/cdk-assets/package.json
  yarn.lock
Labels: pr/no-squash

#8839 feat(custom-resources): include handler log group in error messages
  packages/@aws-cdk/aws-dynamodb/test/integ.global.expected.json
  packages/@aws-cdk/aws-eks/test/integ.eks-cluster.expected.json
  packages/@aws-cdk/custom-resources/lib/provider-framework/provider.ts
  packages/@aws-cdk/custom-resources/lib/provider-framework/runtime/framework.ts
  packages/@aws-cdk/custom-resources/test/provider-framework/integ.provider.expected.json
  packages/@aws-cdk/custom-resources/test/provider-framework/runtime.test.ts
Labels: contribution/core, pr-linter/exempt-readme

#8859 fix(eks): kubectl resources fail before fargate profiles are created
  packages/@aws-cdk/aws-eks/lib/cluster-resource.ts
  packages/@aws-cdk/aws-eks/lib/cluster.ts
  packages/@aws-cdk/aws-eks/lib/helm-chart.ts
  packages/@aws-cdk/aws-eks/lib/k8s-patch.ts
  packages/@aws-cdk/aws-eks/lib/k8s-resource.ts
  packages/@aws-cdk/aws-eks/lib/kubectl-provider.ts
  packages/@aws-cdk/aws-eks/test/integ.eks-cluster.expected.json
  packages/@aws-cdk/aws-eks/test/test.cluster.ts
  packages/@aws-cdk/aws-eks/test/test.fargate.ts
Labels: contribution/core

#8814 chore(apigateway): modernize Integration.bind()
  packages/@aws-cdk/aws-apigateway/lib/integration.ts
  packages/@aws-cdk/aws-apigateway/lib/integrations/aws.ts
  packages/@aws-cdk/aws-apigateway/lib/integrations/lambda.ts
  packages/@aws-cdk/aws-apigateway/lib/method.ts
  packages/@aws-cdk/aws-apigateway/test/test.integration.ts
  packages/@aws-cdk/aws-apigateway/test/test.method.ts
Labels: contribution/core

#8866 chore(release): merge release/1.49.0 to master
  CHANGELOG.md
  lerna.json
Labels: pr/no-squash

#8870 fix(apigateway): Lambda integration for imported functions
  packages/@aws-cdk/aws-apigateway/lib/integrations/lambda.ts
  packages/@aws-cdk/aws-apigateway/test/test.lambda.ts
Labels: contribution/core

#8871 chore(release): 1.49.1
  CHANGELOG.md
  lerna.json
  packages/@aws-cdk/aws-apigateway/lib/integrations/lambda.ts
  packages/@aws-cdk/aws-apigateway/test/test.lambda.ts
Labels: contribution/core, pr/no-squash

#8861 chore: cdk-integ --dry-run
  tools/cdk-integ-tools/bin/cdk-integ.ts
Labels: contribution/core

#8802 feat(eks): document how to add a manifest from url
  packages/@aws-cdk/aws-eks/README.md
Labels: pr-linter/exempt-readme, pr-linter/exempt-test

#8876 chore(release): merge release/1.49.1 to master
  CHANGELOG.md
  lerna.json
Labels: pr/no-squash

#8263 feat(s3-deployment): prune - keep missing files on destination bucket
  packages/@aws-cdk/assert/jest.ts
  packages/@aws-cdk/assert/lib/assertions/count-resources.ts
  packages/@aws-cdk/aws-s3-deployment/.gitignore
  packages/@aws-cdk/aws-s3-deployment/.npmignore
  packages/@aws-cdk/aws-s3-deployment/README.md
  packages/@aws-cdk/aws-s3-deployment/jest.config.js
  packages/@aws-cdk/aws-s3-deployment/lambda/src/index.py
  packages/@aws-cdk/aws-s3-deployment/lambda/test/aws
  packages/@aws-cdk/aws-s3-deployment/lambda/test/test.py
  packages/@aws-cdk/aws-s3-deployment/lib/bucket-deployment.ts
  packages/@aws-cdk/aws-s3-deployment/package.json
  packages/@aws-cdk/aws-s3-deployment/test/bucket-deployment.test.ts
  packages/@aws-cdk/aws-s3-deployment/test/integ.bucket-deployment-cloudfront.expected.json
  packages/@aws-cdk/aws-s3-deployment/test/integ.bucket-deployment.expected.json
  packages/@aws-cdk/aws-s3-deployment/test/integ.bucket-deployment.ts
  packages/@aws-cdk/aws-s3-deployment/test/test.bucket-deployment.ts
  tools/cdk-build-tools/bin/cdk-test.ts
  yarn.lock
Labels: contribution/core

#8840 feat(stepfunctions-tasks): task for invoking a Step Functions activity worker
  packages/@aws-cdk/aws-stepfunctions-tasks/README.md
  packages/@aws-cdk/aws-stepfunctions-tasks/lib/index.ts
  packages/@aws-cdk/aws-stepfunctions-tasks/lib/invoke-activity.ts
  packages/@aws-cdk/aws-stepfunctions-tasks/lib/stepfunctions/invoke-activity.ts
  packages/@aws-cdk/aws-stepfunctions-tasks/test/stepfunctions/integ.invoke-activity.expected.json
  packages/@aws-cdk/aws-stepfunctions-tasks/test/stepfunctions/integ.invoke-activity.ts
  packages/@aws-cdk/aws-stepfunctions-tasks/test/stepfunctions/invoke-activity.ts
Labels: @aws-cdk/aws-stepfunctions-tasks, contribution/core

#8829 chore(stepfunctions): mark the task class as deprecated
  packages/@aws-cdk/aws-stepfunctions/lib/states/task.ts
Labels: @aws-cdk/aws-stepfunctions, contribution/core

#8738 fix(config): cannot scope a custom rule without configurationChanges on
  packages/@aws-cdk/aws-config/lib/rule.ts
  packages/@aws-cdk/aws-config/test/integ.scoped-rule.expected.json
  packages/@aws-cdk/aws-config/test/integ.scoped-rule.ts
  packages/@aws-cdk/aws-config/test/test.rule.ts
Labels: bug, contribution/core

#8830 docs(route53): hostedZone import functions pre-requisites and usage causing confusion
  packages/@aws-cdk/aws-route53/README.md
  packages/@aws-cdk/aws-route53/lib/hosted-zone.ts
Labels: documentation

#8853 feat(autoscaling): allow setting autoscaling group name
  packages/@aws-cdk/aws-autoscaling/.gitignore
  packages/@aws-cdk/aws-autoscaling/.npmignore
  packages/@aws-cdk/aws-autoscaling/jest.config.js
  packages/@aws-cdk/aws-autoscaling/lib/auto-scaling-group.ts
  packages/@aws-cdk/aws-autoscaling/package.json
  packages/@aws-cdk/aws-autoscaling/test/auto-scaling-group.test.ts
  packages/@aws-cdk/aws-autoscaling/test/cron.test.ts
  packages/@aws-cdk/aws-autoscaling/test/lifecyclehooks.test.ts
  packages/@aws-cdk/aws-autoscaling/test/scaling.test.ts
  packages/@aws-cdk/aws-autoscaling/test/scheduled-action.test.ts
  packages/@aws-cdk/aws-autoscaling/test/test.cron.ts
Labels: contribution/core

#8912 feat(stepfunctions): stepfunctions and stepfunctions-tasks modules are now stable!
  packages/@aws-cdk/aws-stepfunctions-tasks/README.md
  packages/@aws-cdk/aws-stepfunctions-tasks/package.json
  packages/@aws-cdk/aws-stepfunctions/README.md
  packages/@aws-cdk/aws-stepfunctions/package.json
Labels: contribution/core, pr-linter/exempt-test

#8928 chore(mergeback): 1.50.0
  CHANGELOG.md
  lerna.json
Labels: pr/no-squash

#8868 feat: Developer Preview of CDK Pipelines
  packages/@aws-cdk/aws-codepipeline-actions/README.md
  packages/@aws-cdk/pipelines/.eslintrc.js
  packages/@aws-cdk/pipelines/.gitignore
  packages/@aws-cdk/pipelines/.npmignore
  packages/@aws-cdk/pipelines/LICENSE
  packages/@aws-cdk/pipelines/NOTICE
  packages/@aws-cdk/pipelines/README.md
  packages/@aws-cdk/pipelines/lib/actions/deploy-cdk-stack-action.ts
  packages/@aws-cdk/pipelines/lib/actions/index.ts
  packages/@aws-cdk/pipelines/lib/actions/publish-assets-action.ts
  packages/@aws-cdk/pipelines/lib/actions/update-pipeline-action.ts
  packages/@aws-cdk/pipelines/lib/index.ts
  packages/@aws-cdk/pipelines/lib/pipeline.ts
  packages/@aws-cdk/pipelines/lib/private/asset-manifest.ts
  packages/@aws-cdk/pipelines/lib/private/construct-internals.ts
  packages/@aws-cdk/pipelines/lib/private/toposort.ts
  packages/@aws-cdk/pipelines/lib/stage.ts
  packages/@aws-cdk/pipelines/lib/synths/_util.ts
  packages/@aws-cdk/pipelines/lib/synths/index.ts
  packages/@aws-cdk/pipelines/lib/synths/simple-synth-action.ts
  packages/@aws-cdk/pipelines/lib/validation/_files.ts
  packages/@aws-cdk/pipelines/lib/validation/index.ts
  packages/@aws-cdk/pipelines/lib/validation/shell-script-action.ts
  packages/@aws-cdk/pipelines/package.json
  packages/@aws-cdk/pipelines/test/builds.test.ts
  packages/@aws-cdk/pipelines/test/cross-environment-infra.test.ts
  packages/@aws-cdk/pipelines/test/integ.pipeline.expected.json
  packages/@aws-cdk/pipelines/test/integ.pipeline.ts
  packages/@aws-cdk/pipelines/test/pipeline-assets.test.ts
  packages/@aws-cdk/pipelines/test/pipeline.test.ts
  packages/@aws-cdk/pipelines/test/stack-ordering.test.ts
  packages/@aws-cdk/pipelines/test/test-docker-asset/Dockerfile
  packages/@aws-cdk/pipelines/test/test-file-asset-two.txt
  packages/@aws-cdk/pipelines/test/test-file-asset.txt
  packages/@aws-cdk/pipelines/test/testmatchers.ts
  packages/@aws-cdk/pipelines/test/testutil.ts
  packages/@aws-cdk/pipelines/test/validation.test.ts
  packages/aws-cdk/bin/cdk.ts
  packages/decdk/package.json
  packages/monocdk-experiment/package.json
Labels: contribution/core

#8939 chore(cloudfront): convert tests to Jest
  packages/@aws-cdk/aws-cloudfront/.gitignore
  packages/@aws-cdk/aws-cloudfront/.npmignore
  packages/@aws-cdk/aws-cloudfront/jest.config.js
  packages/@aws-cdk/aws-cloudfront/package.json
  packages/@aws-cdk/aws-cloudfront/test/oai.test.ts
  packages/@aws-cdk/aws-cloudfront/test/web_distribution.test.ts
Labels: contribution/core

#8942 chore: add account 2222222222 to git-secrets allowed pattern
  .gitallowed
Labels: contribution/core

#8936 fix(cli): Python sample app template does not follow PEP8
  packages/aws-cdk/lib/init-templates/sample-app/python/%name.PythonModule%/%name.PythonModule%_stack.template.py
Labels: effort/small, feature-request, good first issue, package/tools, pr-linter/exempt-test

#8878 docs(ecs): fix typo in awsLogs
  packages/@aws-cdk/aws-ecs/README.md
Labels: @aws-cdk/aws-ecs

#8944 chore(stepfunctions): fix documentation for `Pass` state
  packages/@aws-cdk/aws-stepfunctions/README.md
Labels: contribution/core

#8933 chore(appsync): reorganize code base to improve readability
  packages/@aws-cdk/aws-appsync/lib/dataSource.ts
  packages/@aws-cdk/aws-appsync/lib/graphqlapi.ts
  packages/@aws-cdk/aws-appsync/lib/index.ts
  packages/@aws-cdk/aws-appsync/lib/key.ts
  packages/@aws-cdk/aws-appsync/lib/mappingTemplate.ts
  packages/@aws-cdk/aws-appsync/lib/private.ts
  packages/@aws-cdk/aws-appsync/lib/resolver.ts
Labels: @aws-cdk/aws-appsync

#8958 refactor(appsync): rename files to follow dash-case syntax
  packages/@aws-cdk/aws-appsync/lib/data-source.ts
  packages/@aws-cdk/aws-appsync/lib/graphqlapi.ts
  packages/@aws-cdk/aws-appsync/lib/index.ts
  packages/@aws-cdk/aws-appsync/lib/mapping-template.ts
  packages/@aws-cdk/aws-appsync/lib/resolver.ts
Labels: @aws-cdk/aws-appsync

#8965 chore(app-delivery): deprecate @aws-cdk/app-delivery
  packages/@aws-cdk/app-delivery/README.md
  packages/@aws-cdk/app-delivery/package.json
Labels: contribution/core

#8969 chore: make tests independent of asset hashes
  packages/@aws-cdk/assert/lib/canonicalize-assets.ts
  packages/@aws-cdk/assert/lib/expect.ts
  packages/@aws-cdk/assert/lib/index.ts
  packages/@aws-cdk/assert/test/canonicalize-assets.test.ts
  packages/@aws-cdk/aws-lambda/test/test.layers.ts
  packages/@aws-cdk/core/lib/private/runtime-info.ts
  packages/@aws-cdk/core/test/custom-resource-provider/test.custom-resource-provider.ts
  tools/cdk-integ-tools/bin/cdk-integ-assert.ts
  tools/cdk-integ-tools/lib/integ-helpers.ts
  tools/cdk-integ-tools/package.json
Labels: contribution/core

#8981 chore(merge-back): 1.51.0
  CHANGELOG.md
  lerna.json
Labels: pr/no-squash

#8961 chore(appsync): integration test fails to deploy
  packages/@aws-cdk/aws-appsync/test/integ.graphql.expected.json
  packages/@aws-cdk/aws-appsync/test/integ.graphql.ts
  packages/@aws-cdk/aws-appsync/test/schema.graphql
  packages/@aws-cdk/aws-appsync/test/verify.graphql.sh
  packages/@aws-cdk/aws-appsync/test/verify.integ.graphql.sh
Labels: @aws-cdk/aws-appsync

#8850 chore(cli): Java init template compiles apps before trying to run them
  packages/aws-cdk/lib/init-templates/app/java/cdk.json
  packages/aws-cdk/lib/init-templates/sample-app/java/cdk.json
Labels: contribution/core, package/tools

#8988 chore: add guidance label to general question issue template
  .github/ISSUE_TEMPLATE/general-issues.md
Labels: contribution/core

#8686 chore(rds): change the way Engines are modeled
  packages/@aws-cdk/aws-rds/README.md
  packages/@aws-cdk/aws-rds/lib/cluster-engine.ts
  packages/@aws-cdk/aws-rds/lib/cluster.ts
  packages/@aws-cdk/aws-rds/lib/index.ts
  packages/@aws-cdk/aws-rds/lib/instance-engine.ts
  packages/@aws-cdk/aws-rds/lib/instance.ts
  packages/@aws-cdk/aws-rds/lib/option-group.ts
  packages/@aws-cdk/aws-rds/lib/parameter-group.ts
  packages/@aws-cdk/aws-rds/lib/private/parameter-group-family-mapping.ts
  packages/@aws-cdk/aws-rds/lib/props.ts
  packages/@aws-cdk/aws-rds/test/integ.instance.lit.ts
  packages/@aws-cdk/aws-rds/test/test.cluster-engine.ts
  packages/@aws-cdk/aws-rds/test/test.cluster.ts
  packages/@aws-cdk/aws-rds/test/test.instance.ts
  packages/@aws-cdk/aws-rds/test/test.option-group.ts
  packages/@aws-cdk/aws-rds/test/test.props.ts
  packages/@aws-cdk/aws-rds/test/test.proxy.ts
Labels: contribution/core

#8968 chore: update requirements to jsii@1.8.0, typescript@3.9.6
  package.json
  packages/@monocdk-experiment/rewrite-imports/package.json
  packages/awslint/package.json
  packages/cdk-dasm/package.json
  packages/decdk/package.json
  tools/cdk-build-tools/package.json
  tools/cfn2ts/package.json
  tools/nodeunit-shim/package.json
  tools/pkglint/package.json
  tools/yarn-cling/package.json
  yarn.lock
Labels: contribution/core, dependencies

#8973 chore: make `cdk-integ-assert` cleanup `cdk.out` directories
  packages/@aws-cdk/pipelines/test/integ.pipeline.expected.json
  tools/cdk-integ-tools/lib/integ-helpers.ts
Labels: contribution/core

#8974 chore: make matchers written for `pipelines` available globally
  packages/@aws-cdk/assert/README.md
  packages/@aws-cdk/assert/lib/assertions/have-resource-matchers.ts
  packages/@aws-cdk/assert/lib/assertions/have-resource.ts
  packages/@aws-cdk/assert/lib/index.ts
  packages/@aws-cdk/pipelines/.gitignore
  packages/@aws-cdk/pipelines/.npmignore
  packages/@aws-cdk/pipelines/jest.config.js
  packages/@aws-cdk/pipelines/package.json
  packages/@aws-cdk/pipelines/test/builds.test.ts
  packages/@aws-cdk/pipelines/test/cross-environment-infra.test.ts
  packages/@aws-cdk/pipelines/test/pipeline-assets.test.ts
  packages/@aws-cdk/pipelines/test/pipeline.test.ts
  packages/@aws-cdk/pipelines/test/testmatchers.ts
  packages/@aws-cdk/pipelines/test/validation.test.ts
Labels: contribution/core

#8997 chore(cli): increase retries for CLI integ tests
  packages/aws-cdk/test/integ/cli/aws-helpers.ts
Labels: contribution/core

#9004 chore: move `jest-junit` dependency to top-level
  package.json
  tools/cdk-build-tools/package.json
  tools/cdk-integ-tools/package.json
Labels: contribution/core

#8862 chore(glue): migrate unit tests to Jest
  packages/@aws-cdk/aws-glue/.gitignore
  packages/@aws-cdk/aws-glue/.npmignore
  packages/@aws-cdk/aws-glue/jest.config.js
  packages/@aws-cdk/aws-glue/lib/table.ts
  packages/@aws-cdk/aws-glue/package.json
  packages/@aws-cdk/aws-glue/test/database.test.ts
  packages/@aws-cdk/aws-glue/test/schema.test.ts
  packages/@aws-cdk/aws-glue/test/table.test.ts
  packages/@aws-cdk/aws-glue/test/test.database.ts
  packages/@aws-cdk/aws-glue/test/test.schema.ts
  packages/@aws-cdk/aws-glue/test/test.table.ts
Labels: response-requested

#9010 chore: switch owners in auto label action workflow
  .github/workflows/issue-label-assign.yml
Labels: contribution/core

#9002 feat(cli): bootstrap stacks are protected from termination by default
  packages/aws-cdk/README.md
  packages/aws-cdk/bin/cdk.ts
  packages/aws-cdk/lib/api/bootstrap/bootstrap-environment.ts
  packages/aws-cdk/lib/api/bootstrap/bootstrap-props.ts
  packages/aws-cdk/lib/api/bootstrap/deploy-bootstrap.ts
  packages/aws-cdk/test/api/bootstrap.test.ts
  packages/aws-cdk/test/api/bootstrap2.test.ts
Labels: contribution/core

#8998 refactor(elbv2): move accounts to region-info module
  packages/@aws-cdk/aws-elasticloadbalancingv2/lib/shared/base-load-balancer.ts
  packages/@aws-cdk/aws-elasticloadbalancingv2/package.json
  packages/@aws-cdk/region-info/build-tools/fact-tables.ts
  packages/@aws-cdk/region-info/build-tools/generate-static-data.ts
  packages/@aws-cdk/region-info/lib/fact.ts
  packages/@aws-cdk/region-info/lib/region-info.ts
Labels: contribution/core

#9036 chore(cli): handle term protected stacks during integ test clean up
  packages/aws-cdk/test/integ/cli/aws-helpers.ts
Labels: contribution/core

#9037 Revert "chore(core): allow the bundler to re-use pre-existing bundler output (#8916)"
  packages/@aws-cdk/aws-lambda/test/integ.bundling.ts
  packages/@aws-cdk/aws-s3-assets/test/integ.assets.bundling.lit.ts
  packages/@aws-cdk/core/lib/asset-staging.ts
  packages/@aws-cdk/core/test/docker-stub.sh
  packages/@aws-cdk/core/test/test.staging.ts
Labels: contribution/core, pr/do-not-merge

#9029 fix(eks): cluster creation fails due to missing `ec2:DescribeVpcs` permission
  packages/@aws-cdk/aws-eks/lib/cluster.ts
  packages/@aws-cdk/aws-eks/test/integ.eks-cluster.expected.json
  packages/@aws-cdk/aws-eks/test/test.cluster.ts
  packages/@aws-cdk/aws-eks/test/test.fargate.ts
Labels: contribution/core

#9043 chore(cli): fix integ tests to only update termination protection for parent stacks
  packages/aws-cdk/test/integ/cli/cdk-helpers.ts
Labels: contribution/core

#9041 chore: update auto label workflow with temporary owners
  .github/workflows/issue-label-assign.yml
Labels: contribution/core

#9042 fix(core): fix Duration.toIsoString() for millseconds
  packages/@aws-cdk/core/lib/duration.ts
  packages/@aws-cdk/core/test/test.duration.ts
Labels: contribution/core

#9046 chore(eks): add validation that integ test runs in a supported region
  packages/@aws-cdk/aws-eks/test/integ.eks-cluster.ts
Labels: contribution/core

#9058 chore(cli): bootstrap stack is not termination protected by default
  packages/aws-cdk/lib/api/bootstrap/deploy-bootstrap.ts
  packages/aws-cdk/test/api/bootstrap.test.ts
  packages/aws-cdk/test/api/bootstrap2.test.ts
Labels: contribution/core

#9008 fix(stepfunctions): Map state does not render JSON paths from state input
  packages/@aws-cdk/aws-stepfunctions/lib/states/map.ts
  packages/@aws-cdk/aws-stepfunctions/test/map.test.ts
Labels: @aws-cdk/aws-stepfunctions, contribution/core

#9061 feat(core): Duration.plus for adding durations
  packages/@aws-cdk/core/lib/duration.ts
  packages/@aws-cdk/core/test/test.duration.ts
Labels: contribution/core, pr-linter/exempt-readme

#9064 fix(lambda-event-sources): use of CfnParameter for maxBatchSize, retryAttempts & parallelizationFactor fails
  packages/@aws-cdk/aws-lambda-event-sources/lib/kinesis.ts
  packages/@aws-cdk/aws-lambda-event-sources/test/test.kinesis.ts
  packages/@aws-cdk/aws-lambda/lib/event-source-mapping.ts
  packages/@aws-cdk/aws-lambda/test/test.event-source-mapping.ts
Labels: contribution/core

#9062 chore: update github action RDS and pipelines ownership
  .github/workflows/issue-label-assign.yml
Labels: contribution/core

#8991 fix(stepfunctions): Choice state does not allow state input as a condition
  packages/@aws-cdk/aws-stepfunctions/lib/condition.ts
  packages/@aws-cdk/aws-stepfunctions/test/condition.test.ts
Labels: @aws-cdk/aws-stepfunctions, contribution/core

#9063 feat(core): cloudformation resource metadata
  packages/@aws-cdk/core/lib/cfn-resource.ts
  packages/@aws-cdk/core/test/test.cfn-resource.ts
Labels: contribution/core, pr-linter/exempt-readme

#9084 chore(core): Updated DESIGN_GUIDELINES
  CONTRIBUTING.md
  DESIGN_GUIDELINES.md
  design/aws-guidelines.md
Labels: contribution/core

#9096 chore(cli): set termination-protection to false by default
  packages/aws-cdk/bin/cdk.ts
Labels: contribution/core

#9099 chore(apigateway): remove default* properties from SpecRestApi
  packages/@aws-cdk/aws-apigateway/lib/restapi.ts
Labels: contribution/core

#8982 feat(cloudfront): Initial CloudFront redesign
  packages/@aws-cdk/aws-cloudfront/README.md
  packages/@aws-cdk/aws-cloudfront/lib/distribution.ts
  packages/@aws-cdk/aws-cloudfront/lib/index.ts
  packages/@aws-cdk/aws-cloudfront/lib/origin.ts
  packages/@aws-cdk/aws-cloudfront/lib/private/cache-behavior.ts
  packages/@aws-cdk/aws-cloudfront/lib/web_distribution.ts
  packages/@aws-cdk/aws-cloudfront/package.json
  packages/@aws-cdk/aws-cloudfront/test/distribution.test.ts
  packages/@aws-cdk/aws-cloudfront/test/origin.test.ts
  packages/@aws-cdk/aws-cloudfront/test/private/cache-behavior.test.ts
  packages/@aws-cdk/aws-s3/lib/bucket.ts
  packages/@aws-cdk/aws-s3/test/test.bucket.ts
Labels: contribution/core

#9022 feat(aws-stepfunctions-tasks): allow lambda invocations to combine input and function results
  packages/@aws-cdk/aws-stepfunctions-tasks/README.md
  packages/@aws-cdk/aws-stepfunctions-tasks/lib/lambda/invoke.ts
  packages/@aws-cdk/aws-stepfunctions-tasks/test/lambda/integ.invoke.payload.only.expected.json
  packages/@aws-cdk/aws-stepfunctions-tasks/test/lambda/integ.invoke.payload.only.ts
  packages/@aws-cdk/aws-stepfunctions-tasks/test/lambda/invoke.test.ts
Labels: @aws-cdk/aws-stepfunctions-tasks

#8959 feat(rds): unify ParameterGroup and ClusterParameterGroup
  packages/@aws-cdk/aws-rds/lib/cluster-engine.ts
  packages/@aws-cdk/aws-rds/lib/cluster.ts
  packages/@aws-cdk/aws-rds/lib/engine.ts
  packages/@aws-cdk/aws-rds/lib/index.ts
  packages/@aws-cdk/aws-rds/lib/instance-engine.ts
  packages/@aws-cdk/aws-rds/lib/instance.ts
  packages/@aws-cdk/aws-rds/lib/parameter-group.ts
  packages/@aws-cdk/aws-rds/lib/private/parameter-group-family-mapping.ts
  packages/@aws-cdk/aws-rds/package.json
  packages/@aws-cdk/aws-rds/test/integ.cluster.ts
  packages/@aws-cdk/aws-rds/test/integ.instance.lit.ts
  packages/@aws-cdk/aws-rds/test/test.cluster.ts
  packages/@aws-cdk/aws-rds/test/test.instance.ts
  packages/@aws-cdk/aws-rds/test/test.parameter-group.ts
Labels: contribution/core, pr-linter/exempt-readme

#9113 chore: turn off prerequisite check for Gitpod
  .gitpod.yml
  build.sh
Labels: contribution/core

#9016 feat(rds): introduce type-safe engine versions
  packages/@aws-cdk/aws-rds/README.md
  packages/@aws-cdk/aws-rds/lib/cluster-engine.ts
  packages/@aws-cdk/aws-rds/lib/cluster.ts
  packages/@aws-cdk/aws-rds/lib/engine-version.ts
  packages/@aws-cdk/aws-rds/lib/engine.ts
  packages/@aws-cdk/aws-rds/lib/index.ts
  packages/@aws-cdk/aws-rds/lib/instance-engine.ts
  packages/@aws-cdk/aws-rds/lib/instance.ts
  packages/@aws-cdk/aws-rds/lib/option-group.ts
  packages/@aws-cdk/aws-rds/lib/parameter-group.ts
  packages/@aws-cdk/aws-rds/lib/private/parameter-group-family-mapping.ts
  packages/@aws-cdk/aws-rds/lib/private/version.ts
  packages/@aws-cdk/aws-rds/package.json
  packages/@aws-cdk/aws-rds/test/integ.instance.lit.ts
  packages/@aws-cdk/aws-rds/test/private/test.version.ts
  packages/@aws-cdk/aws-rds/test/test.cluster-engine.ts
  packages/@aws-cdk/aws-rds/test/test.cluster.ts
  packages/@aws-cdk/aws-rds/test/test.instance-engine.ts
  packages/@aws-cdk/aws-rds/test/test.instance.ts
  packages/@aws-cdk/aws-rds/test/test.option-group.ts
  packages/@aws-cdk/aws-rds/test/test.proxy.ts
Labels: contribution/core

#9119 feat(rds): the RDS Construct Library is now in Developer Preview
  packages/@aws-cdk/aws-rds/README.md
  packages/@aws-cdk/aws-rds/package.json
Labels: contribution/core, pr-linter/exempt-test

#9127 chore(ec2): warn if egress rules are ignored
  packages/@aws-cdk/aws-ec2/lib/security-group.ts
Labels: contribution/core

#8948 fix(cli): unable to update stacks in UPDATE_ROLLBACK_COMPLETE
  packages/aws-cdk/lib/api/deploy-stack.ts
  packages/aws-cdk/lib/api/util/cloudformation.ts
  packages/aws-cdk/lib/api/util/cloudformation/stack-status.ts
  packages/aws-cdk/test/api/deploy-stack.test.ts
  packages/aws-cdk/test/integ/cli/cli.integtest.ts
Labels: contribution/core, package/tools

#9129 chore: upgrade jsii version to v1.9.0
  package.json
  packages/awslint/package.json
  packages/cdk-dasm/package.json
  packages/decdk/package.json
  tools/cdk-build-tools/package.json
  tools/cfn2ts/package.json
  yarn.lock
Labels: contribution/core

#9088 feat(stepfunctions-tasks): assign boolean value in DynamoDB from state input (Json path)
  packages/@aws-cdk/aws-stepfunctions-tasks/lib/dynamodb/private/utils.ts
  packages/@aws-cdk/aws-stepfunctions-tasks/lib/dynamodb/shared-types.ts
  packages/@aws-cdk/aws-stepfunctions-tasks/test/dynamodb/integ.call-dynamodb.expected.json
  packages/@aws-cdk/aws-stepfunctions-tasks/test/dynamodb/integ.call-dynamodb.ts
  packages/@aws-cdk/aws-stepfunctions-tasks/test/dynamodb/put-item.test.ts
  packages/@aws-cdk/aws-stepfunctions-tasks/test/dynamodb/shared-types.test.ts
Labels: @aws-cdk/aws-stepfunctions-tasks, pr-linter/exempt-readme

#9057 fix(appsync): erroneous api key created when additional authorization is not configured
  packages/@aws-cdk/aws-appsync/lib/graphqlapi.ts
  packages/@aws-cdk/aws-appsync/test/appsync-apikey.test.ts
Labels: @aws-cdk/aws-appsync

#9142 fix(cfn-include): fix issues in Conditions handling
  packages/@aws-cdk/cloudformation-include/lib/cfn-include.ts
  packages/@aws-cdk/cloudformation-include/test/invalid-templates.test.ts
  packages/@aws-cdk/cloudformation-include/test/test-templates/condition-same-name-as-resource.json
  packages/@aws-cdk/cloudformation-include/test/test-templates/invalid/getatt-in-conditions.json
  packages/@aws-cdk/cloudformation-include/test/test-templates/invalid/non-existent-condition-in-conditions.json
  packages/@aws-cdk/cloudformation-include/test/test-templates/invalid/non-existent-condition-in-if.json
  packages/@aws-cdk/cloudformation-include/test/valid-templates.test.ts
  packages/@aws-cdk/core/lib/cfn-parse.ts
Labels: contribution/core

#9150 chore(merge-back): 1.52.0
  CHANGELOG.md
  lerna.json
Labels: pr/no-squash

#9161 chore: remove reverted commit from changelog
  CHANGELOG.md
Labels: contribution/core

#9165 fix(cli): cli integ tests do not have a unique stack prefix
  packages/aws-cdk/test/integ/cli/README.md
  packages/aws-cdk/test/integ/cli/app/app.js
  packages/aws-cdk/test/integ/cli/cdk-helpers.ts
Labels: contribution/core

#9166 chore(release): 1.53.0
  CHANGELOG.md
  CONTRIBUTING.md
  lerna.json
  packages/@aws-cdk/aws-ec2/README.md
  packages/@aws-cdk/aws-ec2/lib/vpc.ts
  packages/@aws-cdk/aws-ec2/test/integ.vpc-gateway.expected.json
  packages/@aws-cdk/aws-ec2/test/integ.vpc-gateway.ts
  packages/@aws-cdk/aws-ec2/test/vpc.test.ts
  packages/@aws-cdk/aws-lambda-nodejs/README.md
  packages/@aws-cdk/aws-lambda-nodejs/lib/function.ts
  packages/@aws-cdk/aws-lambda-nodejs/test/function.test.ts
  packages/@aws-cdk/aws-lambda-nodejs/test/integ.dependencies.expected.json
  packages/@aws-cdk/aws-lambda-nodejs/test/integ.function.expected.json
  packages/aws-cdk/test/integ/cli/README.md
  packages/aws-cdk/test/integ/cli/app/app.js
  packages/aws-cdk/test/integ/cli/cdk-helpers.ts
  packages/awslint/README.md
Labels: pr/no-squash

#9137 feat(cloudfront): Custom origins and more origin properties
  packages/@aws-cdk/aws-cloudfront/README.md
  packages/@aws-cdk/aws-cloudfront/lib/origin.ts
  packages/@aws-cdk/aws-cloudfront/test/origin.test.ts
Labels: contribution/core

#9168 chore(merge-back): 1.53.0
  CHANGELOG.md
  lerna.json
Labels: pr/no-squash

#7432 feat(autoscaling): enable group metrics collections
  packages/@aws-cdk/aws-autoscaling/README.md
  packages/@aws-cdk/aws-autoscaling/lib/auto-scaling-group.ts
  packages/@aws-cdk/aws-autoscaling/test/auto-scaling-group.test.ts
  packages/@aws-cdk/aws-autoscaling/test/integ.asg-metrics-collections.expected.json
Labels: contribution/core

#9178 chore(cli-integ): keep junit.xml file in regression test
  packages/aws-cdk/test/integ/test-cli-regression-against-current-code.sh
Labels: contribution/core

#9180 fix(pipelines): standardYarnSynth cannot have custom install command
  packages/@aws-cdk/pipelines/lib/synths/simple-synth-action.ts
  packages/@aws-cdk/pipelines/test/builds.test.ts
Labels: contribution/core

#9183 fix(pipelines): prevent self-mutation on asset updates
  packages/@aws-cdk/pipelines/lib/pipeline.ts
  packages/@aws-cdk/pipelines/test/pipeline-assets.test.ts
Labels: contribution/core

#9188 chore(pipelines): Adding comment to explain asset naming strategy
  packages/@aws-cdk/pipelines/lib/pipeline.ts
Labels: contribution/core

#9172 chore: update auto assign action with temp owner
  .github/workflows/issue-label-assign.yml
Labels: contribution/core

#9203 chore(release): 1.54.0
  .github/workflows/issue-label-assign.yml
  CHANGELOG.md
  lerna.json
  packages/@aws-cdk/aws-apigatewayv2/README.md
  packages/@aws-cdk/aws-apigatewayv2/lib/http/api-mapping.ts
  packages/@aws-cdk/aws-apigatewayv2/lib/http/api.ts
  packages/@aws-cdk/aws-apigatewayv2/lib/http/stage.ts
  packages/@aws-cdk/aws-apigatewayv2/test/http/api-mapping.test.ts
  packages/@aws-cdk/aws-apigatewayv2/test/http/domain-name.test.ts
  packages/@aws-cdk/aws-apigatewayv2/test/http/integ.custom-domain.expected.json
  packages/@aws-cdk/aws-apigatewayv2/test/http/integ.custom-domain.ts
  packages/@aws-cdk/aws-autoscaling/README.md
  packages/@aws-cdk/aws-autoscaling/lib/auto-scaling-group.ts
  packages/@aws-cdk/aws-autoscaling/test/auto-scaling-group.test.ts
  packages/@aws-cdk/aws-autoscaling/test/integ.asg-metrics-collections.expected.json
  packages/@aws-cdk/aws-cloudfront/README.md
  packages/@aws-cdk/aws-cloudfront/lib/origin.ts
  packages/@aws-cdk/aws-cloudfront/lib/web_distribution.ts
  packages/@aws-cdk/aws-cloudfront/test/integ.cloudfront-failover.expected.json
  packages/@aws-cdk/aws-cloudfront/test/integ.cloudfront-failover.ts
  packages/@aws-cdk/aws-cloudfront/test/origin-groups.test.ts
  packages/@aws-cdk/aws-cloudfront/test/origin.test.ts
  packages/@aws-cdk/aws-kinesis/lib/stream.ts
  packages/@aws-cdk/aws-kinesis/test/stream.test.ts
  packages/@aws-cdk/aws-lambda-nodejs/parcel/Dockerfile
  packages/@aws-cdk/aws-lambda-nodejs/test/docker.test.ts
  packages/@aws-cdk/core/lib/bundling.ts
  packages/@aws-cdk/core/test/test.bundling.ts
  packages/@aws-cdk/pipelines/lib/pipeline.ts
  packages/@aws-cdk/pipelines/lib/synths/simple-synth-action.ts
  packages/@aws-cdk/pipelines/test/builds.test.ts
  packages/@aws-cdk/pipelines/test/pipeline-assets.test.ts
  packages/aws-cdk/test/integ/test-cli-regression-against-current-code.sh
Labels: pr/no-squash

#9208 chore(merge-back): 1.54.0
  CHANGELOG.md
  lerna.json
Labels: pr/no-squash

#9200 fix(cloudfront): Set MinimumProtocolVersion and SslSupportMethod when specifying distribution certificate
  packages/@aws-cdk/aws-cloudfront/README.md
  packages/@aws-cdk/aws-cloudfront/lib/distribution.ts
  packages/@aws-cdk/aws-cloudfront/lib/web_distribution.ts
  packages/@aws-cdk/aws-cloudfront/test/distribution.test.ts
Labels: @aws-cdk/aws-cloudfront

#9194 docs(route53-patterns): add detail to README and doc strings
  packages/@aws-cdk/aws-route53-patterns/README.md
  packages/@aws-cdk/aws-route53-patterns/lib/website-redirect.ts
  packages/@aws-cdk/aws-route53-patterns/package.json
  packages/@aws-cdk/aws-route53-patterns/test/bucket-website-target.test.ts
Labels: @aws-cdk/aws-route53-patterns, contribution/core

#9125 chore: update README
  README.md
Labels: contribution/core

#9216 feat(cfnspec): cloudformation spec v16.1.0
  packages/@aws-cdk/cfnspec/CHANGELOG.md
  packages/@aws-cdk/cfnspec/spec-source/000_sam.spec.json
Labels: pr-linter/exempt-test

#9209 feat(cloudfront): new aws-cloudfront-origins module, support for ALB/NLB origins
  packages/@aws-cdk/aws-cloudfront-origins/.eslintrc.js
  packages/@aws-cdk/aws-cloudfront-origins/.gitignore
  packages/@aws-cdk/aws-cloudfront-origins/.npmignore
  packages/@aws-cdk/aws-cloudfront-origins/LICENSE
  packages/@aws-cdk/aws-cloudfront-origins/NOTICE
  packages/@aws-cdk/aws-cloudfront-origins/README.md
  packages/@aws-cdk/aws-cloudfront-origins/jest.config.js
  packages/@aws-cdk/aws-cloudfront-origins/lib/http-origin.ts
  packages/@aws-cdk/aws-cloudfront-origins/lib/index.ts
  packages/@aws-cdk/aws-cloudfront-origins/lib/load-balancer-origin.ts
  packages/@aws-cdk/aws-cloudfront-origins/lib/s3-origin.ts
  packages/@aws-cdk/aws-cloudfront-origins/package.json
  packages/@aws-cdk/aws-cloudfront-origins/test/http-origin.test.ts
  packages/@aws-cdk/aws-cloudfront-origins/test/integ.s3-origin.expected.json
  packages/@aws-cdk/aws-cloudfront-origins/test/integ.s3-origin.ts
  packages/@aws-cdk/aws-cloudfront-origins/test/load-balancer-origin.test.ts
  packages/@aws-cdk/aws-cloudfront-origins/test/s3-origin.test.ts
  packages/@aws-cdk/aws-cloudfront/README.md
  packages/@aws-cdk/aws-cloudfront/lib/distribution.ts
  packages/@aws-cdk/aws-cloudfront/lib/origin.ts
  packages/@aws-cdk/aws-cloudfront/test/distribution.test.ts
  packages/@aws-cdk/aws-cloudfront/test/origin.test.ts
  packages/@aws-cdk/aws-cloudfront/test/private/cache-behavior.test.ts
  packages/decdk/package.json
  packages/monocdk-experiment/package.json
Labels: @aws-cdk/aws-cloudfront, contribution/core

#9229 chore: update synthetics area owner in auto assign action
  .github/workflows/issue-label-assign.yml
Labels: contribution/core

#9231 chore(cloudfront): fix error message that was not substituting in the region name
  packages/@aws-cdk/aws-cloudfront/lib/distribution.ts
  packages/@aws-cdk/aws-cloudfront/test/distribution.test.ts
Labels: @aws-cdk/aws-cloudfront, contribution/core

#9232 feat(route53-patterns): the route53-patterns module is now stable
  packages/@aws-cdk/aws-route53-patterns/README.md
  packages/@aws-cdk/aws-route53-patterns/package.json
Labels: @aws-cdk/aws-route53-patterns, contribution/core, pr-linter/exempt-readme, pr-linter/exempt-test

#8993 feat(appsync): grant APIs for managing permissions
  packages/@aws-cdk/aws-appsync/.gitignore
  packages/@aws-cdk/aws-appsync/README.md
  packages/@aws-cdk/aws-appsync/lib/graphqlapi.ts
  packages/@aws-cdk/aws-appsync/test/appsync-apikey.test.ts
  packages/@aws-cdk/aws-appsync/test/appsync-grant.test.ts
  packages/@aws-cdk/aws-appsync/test/appsync.test.graphql
  packages/@aws-cdk/aws-appsync/test/appsync.test.ts
  packages/@aws-cdk/aws-appsync/test/integ.graphql-iam.expected.json
  packages/@aws-cdk/aws-appsync/test/integ.graphql-iam.graphql
  packages/@aws-cdk/aws-appsync/test/integ.graphql-iam.ts
  packages/@aws-cdk/aws-appsync/test/integ.graphql.graphql
  packages/@aws-cdk/aws-appsync/test/integ.graphql.ts
  packages/@aws-cdk/aws-appsync/test/verify.integ.graphql-iam.sh
  packages/@aws-cdk/aws-appsync/test/verify.integ.graphql.sh
  packages/@aws-cdk/aws-appsync/test/verify/iam-query.js
Labels: @aws-cdk/aws-appsync

#9220 feat(cloudfront): support Lambda@Edge for behaviors
  packages/@aws-cdk/aws-cloudfront/README.md
  packages/@aws-cdk/aws-cloudfront/lib/distribution.ts
  packages/@aws-cdk/aws-cloudfront/lib/private/cache-behavior.ts
  packages/@aws-cdk/aws-cloudfront/lib/web_distribution.ts
  packages/@aws-cdk/aws-cloudfront/package.json
  packages/@aws-cdk/aws-cloudfront/test/distribution.test.ts
Labels: @aws-cdk/aws-cloudfront, contribution/core

#9093 fix(appsync): resolver unable to set pipelineConfig
  packages/@aws-cdk/aws-appsync/lib/resolver.ts
  packages/@aws-cdk/aws-appsync/test/appsync.test.ts
Labels: @aws-cdk/aws-appsync

#9215 fix(rds): SQL Server instance engine uses incorrect major version
  packages/@aws-cdk/aws-rds/lib/instance-engine.ts
  packages/@aws-cdk/aws-rds/test/sql-server/test.sql-server.instance-engine.ts
Labels: @aws-cdk/aws-rds, contribution/core

#9147 fix(codepipeline-actions): CodeDeployEcsDeployAction does not properly handle unnamed Artifacts
  packages/@aws-cdk/aws-codepipeline-actions/lib/codedeploy/ecs-deploy-action.ts
  packages/@aws-cdk/aws-codepipeline-actions/test/codedeploy/test.ecs-deploy-action.ts
Labels: contribution/core

#9280 chore: output junit files to coverage folder
  packages/aws-cdk/test/integ/cli/jest.config.js
  packages/aws-cdk/test/integ/test-cli-regression-against-current-code.sh
  tools/cdk-build-tools/config/jest.config.js
Labels: contribution/core

#9284 chore: use current path
  packages/aws-cdk/test/integ/test-cli-regression-against-current-code.sh
Labels: contribution/core

#9290 chore(certificatemanager): convert tests to Jest
  packages/@aws-cdk/aws-certificatemanager/.gitignore
  packages/@aws-cdk/aws-certificatemanager/.npmignore
  packages/@aws-cdk/aws-certificatemanager/jest.config.js
  packages/@aws-cdk/aws-certificatemanager/package.json
  packages/@aws-cdk/aws-certificatemanager/test/certificate.test.ts
  packages/@aws-cdk/aws-certificatemanager/test/dns-validated-certificate.test.ts
  packages/@aws-cdk/aws-certificatemanager/test/test.certificate.ts
  packages/@aws-cdk/aws-certificatemanager/test/test.dns-validated-certificate.ts
  packages/@aws-cdk/aws-certificatemanager/test/test.util.ts
  packages/@aws-cdk/aws-certificatemanager/test/util.test.ts
Labels: contribution/core

#9239 fix(cloudtrail): missing sns publish permissions
  packages/@aws-cdk/aws-cloudtrail/lib/cloudtrail.ts
  packages/@aws-cdk/aws-cloudtrail/test/cloudtrail.test.ts
  packages/@aws-cdk/aws-cloudtrail/test/integ.cloudtrail.lit.expected.json
  packages/@aws-cdk/aws-cloudtrail/test/integ.cloudtrail.lit.ts
Labels: @aws-cdk/aws-cloudtrail, contribution/core, pr/do-not-merge

#9309 chore(merge-back): 1.55.0
  CHANGELOG.md
  lerna.json
Labels: pr/no-squash

#9311 chore(core): copy test reports from coverage folder
  packages/aws-cdk/test/integ/test-cli-regression-against-current-code.sh
Labels: contribution/core

#9315 build: skip compatibility check for Gitpod
  .gitpod.yml
  build.sh
Labels: contribution/core

#9281 chore(cloudfront): small refactoring of the Origin API
  packages/@aws-cdk/aws-cloudfront-origins/lib/s3-origin.ts
  packages/@aws-cdk/aws-cloudfront-origins/test/http-origin.test.ts
  packages/@aws-cdk/aws-cloudfront-origins/test/integ.s3-origin.expected.json
  packages/@aws-cdk/aws-cloudfront-origins/test/load-balancer-origin.test.ts
  packages/@aws-cdk/aws-cloudfront-origins/test/s3-origin.test.ts
  packages/@aws-cdk/aws-cloudfront/lib/distribution.ts
  packages/@aws-cdk/aws-cloudfront/lib/origin.ts
  packages/@aws-cdk/aws-cloudfront/lib/private/cache-behavior.ts
  packages/@aws-cdk/aws-cloudfront/test/distribution.test.ts
  packages/@aws-cdk/aws-cloudfront/test/origin.test.ts
  packages/@aws-cdk/aws-cloudfront/test/private/cache-behavior.test.ts
Labels: contribution/core

#9326 chore(cloudfront): Removed duplicate origins in aws-cloudfront module
  packages/@aws-cdk/aws-cloudfront-origins/lib/http-origin.ts
  packages/@aws-cdk/aws-cloudfront-origins/lib/load-balancer-origin.ts
  packages/@aws-cdk/aws-cloudfront-origins/lib/s3-origin.ts
  packages/@aws-cdk/aws-cloudfront-origins/test/http-origin.test.ts
  packages/@aws-cdk/aws-cloudfront-origins/test/s3-origin.test.ts
  packages/@aws-cdk/aws-cloudfront/lib/origin.ts
  packages/@aws-cdk/aws-cloudfront/test/distribution.test.ts
  packages/@aws-cdk/aws-cloudfront/test/origin.test.ts
Labels: contribution/core

#9314 chore(cfn-include): update ReadMe for Nested Stacks
  packages/@aws-cdk/cloudformation-include/README.md
Labels: contribution/core

#9333 fix(pipelines): reduce assets IAM policy size
  packages/@aws-cdk/pipelines/lib/pipeline.ts
  packages/@aws-cdk/pipelines/test/integ.pipeline-with-assets.expected.json
  packages/@aws-cdk/pipelines/test/pipeline-assets.test.ts
Labels: contribution/core

#9291 fix(certificatemanager): DNS validation for wildcard certificates
  packages/@aws-cdk/aws-certificatemanager/lib/certificate.ts
  packages/@aws-cdk/aws-certificatemanager/test/certificate.test.ts
Labels: contribution/core

#9344 docs: add some missing imports and update some property names in code examples in pipelines README
  packages/@aws-cdk/pipelines/README.md
Labels: contribution/core

#8826 chore(scripts): allow --reset --up/--down to automatically run script
  scripts/builddown
  scripts/buildup
  scripts/foreach.sh
Labels: contribution/core

#9356 chore(cloudfront): README updates and notes of breaking changes
  packages/@aws-cdk/aws-cloudfront/README.md
Labels: contribution/core

#9283 refactor(appsync): strongly type schema definition mode
  packages/@aws-cdk/aws-appsync/README.md
  packages/@aws-cdk/aws-appsync/lib/graphqlapi.ts
  packages/@aws-cdk/aws-appsync/package.json
  packages/@aws-cdk/aws-appsync/test/appsync-apikey.test.ts
  packages/@aws-cdk/aws-appsync/test/appsync-grant.test.ts
  packages/@aws-cdk/aws-appsync/test/appsync-schema.test.ts
  packages/@aws-cdk/aws-appsync/test/appsync.test.ts
  packages/@aws-cdk/aws-appsync/test/integ.graphql-iam.ts
  packages/@aws-cdk/aws-appsync/test/integ.graphql.ts
Labels: @aws-cdk/aws-appsync, pr/breaking-change

#9373 docs(cfn-include): fixed CfnOutput comment docs
  packages/@aws-cdk/core/lib/cfn-output.ts
Labels: contribution/core

#9359 chore(cloudfront-origins): adding integ tests for HTTP and LB origins
  packages/@aws-cdk/aws-cloudfront-origins/package.json
  packages/@aws-cdk/aws-cloudfront-origins/test/integ.http-origin.expected.json
  packages/@aws-cdk/aws-cloudfront-origins/test/integ.http-origin.ts
  packages/@aws-cdk/aws-cloudfront-origins/test/integ.load-balancer-origin.expected.json
  packages/@aws-cdk/aws-cloudfront-origins/test/integ.load-balancer-origin.ts
Labels: contribution/core

#9365 feat(core): make the CfnParameter class mutable
  packages/@aws-cdk/cloudformation-include/README.md
  packages/@aws-cdk/cloudformation-include/test/valid-templates.test.ts
  packages/@aws-cdk/core/lib/cfn-parameter.ts
Labels: contribution/core
