Repository aws/aws-cdk, pull requests merged in 2020-09, with the labels that each got.

#9549 fix(cli): Linux browser not supported for `cdk docs`
  packages/aws-cdk/lib/commands/docs.ts
Labels: pr-linter/exempt-test

#10089 chore(core): deprecate KMS key ARN export name property
  packages/@aws-cdk/core/lib/stack-synthesizers/default-synthesizer.ts
Labels: contribution/core

#10087 chore(core): add @deprecated notices
  packages/@aws-cdk/core/lib/stack-synthesizers/legacy.ts
  packages/@aws-cdk/core/lib/stack.ts
Labels: contribution/core

#10093 feat(rds): rename DatabaseInstanceNewProps.vpcPlacement to vpcSubnets
  packages/@aws-cdk/aws-rds/README.md
  packages/@aws-cdk/aws-rds/lib/instance.ts
  packages/@aws-cdk/aws-rds/test/test.instance.ts
Labels: contribution/core

#10101 chore(appsync): introduce breaking changes to api for consistency
  packages/@aws-cdk/aws-appsync/README.md
  packages/@aws-cdk/aws-appsync/lib/graphqlapi.ts
  packages/@aws-cdk/aws-appsync/lib/schema.ts
  packages/@aws-cdk/aws-appsync/package.json
  packages/@aws-cdk/aws-appsync/test/appsync-auth.test.ts
  packages/@aws-cdk/aws-appsync/test/appsync-code-first.test.ts
  packages/@aws-cdk/aws-appsync/test/appsync-dynamodb.test.ts
  packages/@aws-cdk/aws-appsync/test/appsync-grant.test.ts
  packages/@aws-cdk/aws-appsync/test/appsync-http.test.ts
  packages/@aws-cdk/aws-appsync/test/appsync-input-types.test.ts
  packages/@aws-cdk/aws-appsync/test/appsync-interface-type.test.ts
  packages/@aws-cdk/aws-appsync/test/appsync-lambda.test.ts
  packages/@aws-cdk/aws-appsync/test/appsync-none.test.ts
  packages/@aws-cdk/aws-appsync/test/appsync-object-type.test.ts
  packages/@aws-cdk/aws-appsync/test/appsync-scalar-type.test.ts
  packages/@aws-cdk/aws-appsync/test/appsync-schema.test.ts
  packages/@aws-cdk/aws-appsync/test/appsync.test.ts
  packages/@aws-cdk/aws-appsync/test/integ.api-import.ts
  packages/@aws-cdk/aws-appsync/test/integ.graphql-iam.ts
  packages/@aws-cdk/aws-appsync/test/integ.graphql-schema.ts
  packages/@aws-cdk/aws-appsync/test/integ.graphql.ts
Labels: @aws-cdk/aws-appsync, contribution/core

#9701 fix(eks): creating a `ServiceAccount` in a different stack than the `Cluster` creates circular dependency between the two stacks
  packages/@aws-cdk/aws-eks/README.md
  packages/@aws-cdk/aws-eks/lib/aws-auth.ts
  packages/@aws-cdk/aws-eks/lib/service-account.ts
  packages/@aws-cdk/aws-eks/test/integ.eks-cluster-private-endpoint.expected.json
  packages/@aws-cdk/aws-eks/test/integ.eks-cluster.expected.json
  packages/@aws-cdk/aws-eks/test/test.awsauth.ts
  packages/@aws-cdk/aws-eks/test/test.cluster.ts
Labels: contribution/core

#9802 feat(eks): support adding k8s resources to imported clusters
  packages/@aws-cdk/aws-eks/README.md
  packages/@aws-cdk/aws-eks/lib/cluster-resource-provider.ts
  packages/@aws-cdk/aws-eks/lib/cluster-resource.ts
  packages/@aws-cdk/aws-eks/lib/cluster.ts
  packages/@aws-cdk/aws-eks/lib/fargate-profile.ts
  packages/@aws-cdk/aws-eks/lib/helm-chart.ts
  packages/@aws-cdk/aws-eks/lib/k8s-manifest.ts
  packages/@aws-cdk/aws-eks/lib/k8s-object-value.ts
  packages/@aws-cdk/aws-eks/lib/k8s-patch.ts
  packages/@aws-cdk/aws-eks/lib/kubectl-provider.ts
  packages/@aws-cdk/aws-eks/lib/legacy-cluster.ts
  packages/@aws-cdk/aws-eks/test/integ.eks-cluster-private-endpoint.expected.json
  packages/@aws-cdk/aws-eks/test/integ.eks-cluster.expected.json
  packages/@aws-cdk/aws-eks/test/test.cluster.ts
  packages/@aws-cdk/aws-eks/test/test.k8s-manifest.ts
  packages/@aws-cdk/aws-eks/test/test.legacy-cluster.ts
Labels: contribution/core

#10090 feat(eks): kubectl layer customization
  packages/@aws-cdk/aws-eks/README.md
  packages/@aws-cdk/aws-eks/lib/cluster.ts
  packages/@aws-cdk/aws-eks/lib/index.ts
  packages/@aws-cdk/aws-eks/lib/kubectl-layer.ts
  packages/@aws-cdk/aws-eks/lib/kubectl-provider.ts
  packages/@aws-cdk/aws-eks/test/test.cluster.ts
Labels: contribution/core

#10120 fix(cli): re-bootstrapping loses previous configuration
  packages/aws-cdk/bin/cdk.ts
  packages/aws-cdk/lib/api/bootstrap/bootstrap-environment.ts
  packages/aws-cdk/lib/api/bootstrap/deploy-bootstrap.ts
  packages/aws-cdk/lib/api/deploy-stack.ts
  packages/aws-cdk/lib/api/toolkit-info.ts
  packages/aws-cdk/lib/api/util/cloudformation.ts
  packages/aws-cdk/lib/settings.ts
  packages/aws-cdk/test/api/bootstrap2.test.ts
  packages/aws-cdk/test/integ/cli/bootstrapping.integtest.ts
  packages/aws-cdk/test/integ/cli/cdk-helpers.ts
  packages/aws-cdk/test/integ/cli/corking.ts
  packages/aws-cdk/test/integ/cli/test-helpers.ts
  packages/aws-cdk/test/util/mock-sdk.ts
Labels: contribution/core

#10128 chore(aws-codepipeline): switch tests to Jest
  packages/@aws-cdk/aws-codepipeline/.gitignore
  packages/@aws-cdk/aws-codepipeline/.npmignore
  packages/@aws-cdk/aws-codepipeline/jest.config.js
  packages/@aws-cdk/aws-codepipeline/package.json
  packages/@aws-cdk/aws-codepipeline/test/action.test.ts
  packages/@aws-cdk/aws-codepipeline/test/artifacts.test.ts
  packages/@aws-cdk/aws-codepipeline/test/general-validation.test.ts
  packages/@aws-cdk/aws-codepipeline/test/pipeline.test.ts
  packages/@aws-cdk/aws-codepipeline/test/stages.test.ts
  packages/@aws-cdk/aws-codepipeline/test/variables.test.ts
  packages/@aws-cdk/pipelines/lib/pipeline.ts
  tools/nodeunit-shim/index.ts
Labels: contribution/core

#10092 feat(rds): performance insights for DatabaseCluster instances
  packages/@aws-cdk/aws-rds/lib/cluster.ts
  packages/@aws-cdk/aws-rds/lib/instance.ts
  packages/@aws-cdk/aws-rds/lib/props.ts
  packages/@aws-cdk/aws-rds/test/test.cluster.ts
  packages/@aws-cdk/aws-rds/test/test.instance.ts
Labels: contribution/core, pr-linter/exempt-readme

#10105 fix(cfn-include): allow Conditions to reference Mappings in their definitions
  packages/@aws-cdk/cloudformation-include/lib/cfn-include.ts
  packages/@aws-cdk/cloudformation-include/test/test-templates/condition-using-mapping.json
  packages/@aws-cdk/cloudformation-include/test/valid-templates.test.ts
Labels: contribution/core

#9842 fix(cfn-include): allow parameters to be replaced across nested stacks
  packages/@aws-cdk/cloudformation-include/lib/cfn-include.ts
  packages/@aws-cdk/cloudformation-include/test/nested-stacks.test.ts
  packages/@aws-cdk/cloudformation-include/test/test-templates/nested/child-two-parameters.json
  packages/@aws-cdk/cloudformation-include/test/test-templates/nested/parent-two-parameters.json
Labels: contribution/core

#10121 fix(cli): bootstrapping qualifier length not validated
  packages/aws-cdk/lib/api/bootstrap/bootstrap-template.yaml
  packages/aws-cdk/test/integ/cli/bootstrapping.integtest.ts
Labels: contribution/core

#10097 feat(ecs): bottlerocket support
  packages/@aws-cdk/aws-ecs/README.md
  packages/@aws-cdk/aws-ecs/lib/cluster.ts
  packages/@aws-cdk/aws-ecs/test/ec2/integ.bottlerocket.expected.json
  packages/@aws-cdk/aws-ecs/test/ec2/integ.bottlerocket.ts
  packages/@aws-cdk/aws-ecs/test/test.ecs-cluster.ts
Labels: @aws-cdk/aws-ecs

#10147 chore: skip regression tests from v1.61.1 series
  packages/aws-cdk/CONTRIBUTING.md
  packages/aws-cdk/test/integ/cli-regression-patches/v1.61.1/NOTES.md
  packages/aws-cdk/test/integ/cli-regression-patches/v1.61.1/skip-tests.txt
Labels: contribution/core

#10152 feat(pipelines): `SimpleSynthAction` takes array of build commands
  packages/@aws-cdk/pipelines/README.md
  packages/@aws-cdk/pipelines/lib/synths/simple-synth-action.ts
  packages/@aws-cdk/pipelines/test/builds.test.ts
Labels: contribution/core

#10148 feat(pipelines): add control over underlying CodePipeline
  packages/@aws-cdk/aws-codepipeline/lib/pipeline.ts
  packages/@aws-cdk/aws-codepipeline/test/pipeline.test.ts
  packages/@aws-cdk/pipelines/README.md
  packages/@aws-cdk/pipelines/lib/pipeline.ts
  packages/@aws-cdk/pipelines/test/existing-pipeline.test.ts
  packages/@aws-cdk/pipelines/test/pipeline.test.ts
  packages/@aws-cdk/pipelines/test/testutil.ts
Labels: contribution/core

#9973 feat(appsync): implement directives for code-first approach
  packages/@aws-cdk/aws-appsync/README.md
  packages/@aws-cdk/aws-appsync/lib/graphqlapi.ts
  packages/@aws-cdk/aws-appsync/lib/private.ts
  packages/@aws-cdk/aws-appsync/lib/schema-base.ts
  packages/@aws-cdk/aws-appsync/lib/schema-field.ts
  packages/@aws-cdk/aws-appsync/lib/schema-intermediate.ts
  packages/@aws-cdk/aws-appsync/lib/schema.ts
  packages/@aws-cdk/aws-appsync/test/appsync-directives.test.ts
  packages/@aws-cdk/aws-appsync/test/appsync-interface-type.test.ts
  packages/@aws-cdk/aws-appsync/test/appsync-object-type.test.ts
  packages/@aws-cdk/aws-appsync/test/integ.graphql-schema.ts
Labels: @aws-cdk/aws-appsync, contribution/core

#10103 fix(eks): restricted public access breaks cluster functionality
  packages/@aws-cdk/aws-eks/lib/cluster.ts
  packages/@aws-cdk/aws-eks/test/integ.eks-cluster-private-endpoint.expected.json
  packages/@aws-cdk/aws-eks/test/integ.eks-cluster.expected.json
  packages/@aws-cdk/aws-eks/test/test.cluster.ts
Labels: contribution/core

#10167 build(appsync): fix jsii bug to prevent toString() override w/ dotnet
  packages/@aws-cdk/aws-appsync/lib/private.ts
  packages/@aws-cdk/aws-appsync/lib/schema-base.ts
  packages/@aws-cdk/aws-appsync/lib/schema-field.ts
  packages/@aws-cdk/aws-appsync/lib/schema-intermediate.ts
  packages/@aws-cdk/aws-appsync/lib/schema.ts
Labels: @aws-cdk/aws-appsync, contribution/core

#10124 chore(core,cx-api): centralize defaults for future flags
  packages/@aws-cdk/core/lib/feature-flags.ts
  packages/@aws-cdk/core/lib/index.ts
  packages/@aws-cdk/core/lib/private/refs.ts
  packages/@aws-cdk/core/lib/stack.ts
  packages/@aws-cdk/core/test/test.feature-flags.ts
  packages/@aws-cdk/cx-api/lib/features.ts
  packages/@aws-cdk/cx-api/test/features.test.ts
  packages/aws-cdk/bin/cdk.ts
Labels: contribution/core

#10173 chore(merge-back): 1.62.0
  CHANGELOG.md
  lerna.json
Labels: pr/no-squash

#10130 feat(rds): database clusters from snapshots
  packages/@aws-cdk/aws-rds/README.md
  packages/@aws-cdk/aws-rds/lib/cluster.ts
  packages/@aws-cdk/aws-rds/package.json
  packages/@aws-cdk/aws-rds/test/test.cluster.ts
Labels: contribution/core

#10169 feat(cfn-include): allow renaming the template elements logical IDs
  packages/@aws-cdk/cloudformation-include/README.md
  packages/@aws-cdk/cloudformation-include/lib/cfn-include.ts
  packages/@aws-cdk/cloudformation-include/test/valid-templates.test.ts
Labels: contribution/core

#10153 fix(pipelines): check for an empty Stage object
  packages/@aws-cdk/pipelines/lib/stage.ts
  packages/@aws-cdk/pipelines/test/pipeline.test.ts
Labels: contribution/core

#10149 feat(pipelines): adding IAM permissions to ShellScriptAction
  packages/@aws-cdk/pipelines/README.md
  packages/@aws-cdk/pipelines/lib/synths/simple-synth-action.ts
  packages/@aws-cdk/pipelines/lib/validation/shell-script-action.ts
  packages/@aws-cdk/pipelines/test/builds.test.ts
  packages/@aws-cdk/pipelines/test/validation.test.ts
Labels: contribution/core

#10143 feat(cfn-include): add support for Hooks
  packages/@aws-cdk/cloudformation-include/README.md
  packages/@aws-cdk/cloudformation-include/lib/cfn-include.ts
  packages/@aws-cdk/cloudformation-include/test/test-templates/hook-code-deploy-blue-green-ecs.json
  packages/@aws-cdk/cloudformation-include/test/valid-templates.test.ts
  packages/@aws-cdk/core/lib/cfn-codedeploy-blue-green-hook.ts
  packages/@aws-cdk/core/lib/cfn-hook.ts
  packages/@aws-cdk/core/lib/cfn-parse.ts
  packages/@aws-cdk/core/lib/index.ts
  packages/@aws-cdk/core/package.json
Labels: contribution/core

#10184 fix(cli): metadata not recorded for templates >50k
  packages/@aws-cdk/cx-api/lib/artifacts/cloudformation-artifact.ts
  packages/@aws-cdk/cx-api/lib/cloud-assembly.ts
  packages/aws-cdk/lib/api/cxapp/cloud-executable.ts
  packages/aws-cdk/test/integ/cli/app/app.js
  packages/aws-cdk/test/integ/cli/cli.integtest.ts
Labels: contribution/core

#10216 fix(ec2): cfn-init user data hash not updated if file asset changes
  packages/@aws-cdk/aws-ec2/lib/cfn-init-elements.ts
  packages/@aws-cdk/aws-ec2/lib/cfn-init.ts
  packages/@aws-cdk/aws-ec2/lib/private/cfn-init-internal.ts
  packages/@aws-cdk/aws-ec2/test/cfn-init.test.ts
  packages/@aws-cdk/aws-ec2/test/integ.instance-init.expected.json
Labels: contribution/core

#10162 feat(rds): metrics for clusters
  packages/@aws-cdk/aws-rds/README.md
  packages/@aws-cdk/aws-rds/lib/cluster.ts
  packages/@aws-cdk/aws-rds/test/test.cluster.ts
  packages/@aws-cdk/cfnspec/lib/augmentations/AWS_RDS_DBCluster.json
  packages/@aws-cdk/cfnspec/lib/schema/augmentation.ts
  tools/cfn2ts/lib/augmentation-generator.ts
Labels: contribution/core

#10235 chore(cli): run jest files in parallel in integ tests
  packages/aws-cdk/test/integ/cli/cdk-helpers.ts
  packages/aws-cdk/test/integ/cli/test.sh
Labels: contribution/core

#10237 chore(cli): integtest restores fixture
  packages/aws-cdk/test/integ/cli/cli.integtest.ts
Labels: contribution/core

#10155 chore(pipelines): sanity check on asset path
  packages/@aws-cdk/pipelines/lib/pipeline.ts
Labels: contribution/core

#10238 chore(cli): increase retry count in integ tests to be more resistent to throttling
  packages/aws-cdk/test/integ/cli/aws-helpers.ts
Labels: contribution/core

#10126 chore(cli): mark `cdk deploy --tags` for removal in v2
  packages/aws-cdk/bin/cdk.ts
Labels: contribution/core

#10156 fix(core): Stacks render CloudFormation elements in nested Stages
  packages/@aws-cdk/core/lib/stack.ts
  packages/@aws-cdk/core/test/test.cfn-resource.ts
  packages/@aws-cdk/core/test/test.stack.ts
Labels: contribution/core

#10192 refactor(core): move expiration from s3-deployments into core
  packages/@aws-cdk/aws-s3-deployment/lib/bucket-deployment.ts
  packages/@aws-cdk/aws-s3-deployment/test/bucket-deployment.test.ts
  packages/@aws-cdk/core/lib/expiration.ts
  packages/@aws-cdk/core/lib/index.ts
  packages/@aws-cdk/core/test/test.expiration.ts
Labels: @aws-cdk/aws-s3-deployment, @aws-cdk/core, contribution/core

#10195 fix(cfn-include): correctly substitute falsy parameter values
  packages/@aws-cdk/cloudformation-include/test/valid-templates.test.ts
  packages/@aws-cdk/core/lib/cfn-parse.ts
Labels: contribution/core

#10217 fix(codepipeline): cross-region support stack requires bootstrapping
  packages/@aws-cdk/core/lib/stack-synthesizers/bootstrapless-synthesizer.ts
  packages/@aws-cdk/core/lib/stack-synthesizers/default-synthesizer.ts
  packages/@aws-cdk/core/test/stack-synthesis/test.new-style-synthesis.ts
Labels: contribution/core

#10227 chore(cfn-include): fix typos in IncludeNestedStack
  packages/@aws-cdk/cloudformation-include/lib/cfn-include.ts
Labels: contribution/core

#10250 chore(s3-deployment): separate calls for core.Expiration causes build errors
  packages/@aws-cdk/aws-s3-deployment/test/bucket-deployment.test.ts
Labels: @aws-cdk/aws-s3-deployment, contribution/core

#10171 feat(appsync): add authorization config to the HttpDataSource
  packages/@aws-cdk/aws-appsync/README.md
  packages/@aws-cdk/aws-appsync/lib/data-source.ts
  packages/@aws-cdk/aws-appsync/lib/graphqlapi-base.ts
  packages/@aws-cdk/aws-appsync/test/appsync-http.test.ts
Labels: @aws-cdk/aws-appsync

#10197 fix(cfn-include): correctly parse YAML strings in short-form GetAtt
  packages/@aws-cdk/cloudformation-include/lib/file-utils.ts
  packages/@aws-cdk/cloudformation-include/test/invalid-templates.test.ts
  packages/@aws-cdk/cloudformation-include/test/test-templates/invalid/short-form-get-att-no-dot.yaml
  packages/@aws-cdk/cloudformation-include/test/test-templates/yaml/short-form-get-att.yaml
  packages/@aws-cdk/cloudformation-include/test/yaml-templates.test.ts
Labels: contribution/core

#10025 feat(appsync): support union types for code-first approach
  packages/@aws-cdk/aws-appsync/README.md
  packages/@aws-cdk/aws-appsync/lib/schema-intermediate.ts
  packages/@aws-cdk/aws-appsync/test/appsync-union-types.test.ts
  packages/@aws-cdk/aws-appsync/test/integ.graphql-schema.expected.json
  packages/@aws-cdk/aws-appsync/test/integ.graphql-schema.ts
Labels: @aws-cdk/aws-appsync, contribution/core

#9938 fix(cli): unable to set termination protection for pipeline stacks
  packages/aws-cdk/lib/api/bootstrap/bootstrap-template.yaml
Labels: pr-linter/exempt-test

#10244 feat(elasticloadbalancingv2): multiple security groups for ALBs
  packages/@aws-cdk/aws-elasticloadbalancingv2/README.md
  packages/@aws-cdk/aws-elasticloadbalancingv2/lib/alb/application-load-balancer.ts
  packages/@aws-cdk/aws-elasticloadbalancingv2/test/alb/load-balancer.test.ts
Labels: contribution/core

#10260 chore(cli): refactor integ tests to be isolated
  packages/aws-cdk/test/integ/cli/aws-helpers.ts
  packages/aws-cdk/test/integ/cli/bootstrapping.integtest.ts
  packages/aws-cdk/test/integ/cli/cdk-helpers.ts
  packages/aws-cdk/test/integ/cli/cli.integtest.ts
  packages/aws-cdk/test/integ/cli/corking.ts
  packages/aws-cdk/test/integ/cli/test-helpers.ts
Labels: contribution/core

#10246 fix(core): DefaultSynthesizer breaks this.node.setContext() on Stack
  allowed-breaking-changes.txt
  packages/@aws-cdk/core/lib/private/synthesis.ts
  packages/@aws-cdk/core/lib/stack-synthesizers/bootstrapless-synthesizer.ts
  packages/@aws-cdk/core/lib/stack-synthesizers/default-synthesizer.ts
  packages/@aws-cdk/core/lib/stack-synthesizers/index.ts
  packages/@aws-cdk/core/lib/stack-synthesizers/legacy.ts
  packages/@aws-cdk/core/lib/stack-synthesizers/nested.ts
  packages/@aws-cdk/core/lib/stack-synthesizers/stack-synthesizer.ts
  packages/@aws-cdk/core/lib/stack-synthesizers/types.ts
  packages/@aws-cdk/core/lib/stack.ts
  packages/@aws-cdk/core/test/stack-synthesis/test.new-style-synthesis.ts
  packages/@aws-cdk/core/test/test.stack.ts
Labels: contribution/core

#10241 feat(rds): deprecate OracleSE and OracleSE1 engine versions
  packages/@aws-cdk/aws-rds/README.md
  packages/@aws-cdk/aws-rds/lib/instance-engine.ts
  packages/@aws-cdk/aws-rds/test/integ.instance.lit.expected.json
  packages/@aws-cdk/aws-rds/test/integ.instance.lit.ts
  packages/@aws-cdk/aws-rds/test/test.instance.ts
Labels: contribution/core

#10275 chore(cli): incorrect options passing to `shell` in integration tests
  packages/aws-cdk/test/integ/cli/cdk-helpers.ts
Labels: contribution/core

#9122 fix(appsync): strongly type `expires` prop in apiKeyConfig
  packages/@aws-cdk/aws-appsync/lib/graphqlapi.ts
  packages/@aws-cdk/aws-appsync/test/appsync-auth.test.ts
  packages/@aws-cdk/aws-appsync/test/appsync.auth.graphql
  packages/@aws-cdk/aws-appsync/test/integ.auth-apikey.expected.json
  packages/@aws-cdk/aws-appsync/test/integ.auth-apikey.ts
  packages/@aws-cdk/aws-appsync/test/verify.integ.auth-apikey.sh
Labels: @aws-cdk/aws-appsync, contribution/core, pr/breaking-change

#10205 feat(elasticloadbalancingv2): more health check validations to NLB target group (#3703)
  packages/@aws-cdk/aws-elasticloadbalancingv2/lib/nlb/network-target-group.ts
  packages/@aws-cdk/aws-elasticloadbalancingv2/test/nlb/target-group.test.ts
Labels: pr-linter/exempt-readme

#10272 feat(cli): support credential_source in aws shared config file
  packages/aws-cdk/lib/api/aws-auth/aws-sdk-inifile.ts
  packages/aws-cdk/test/account-cache.test.ts
  packages/aws-cdk/test/api/sdk-provider.test.ts
  packages/aws-cdk/test/integ/cli-regression-patches/v1.62.0/NOTES.md
  packages/aws-cdk/test/integ/cli-regression-patches/v1.62.0/aws-helpers.js
  packages/aws-cdk/test/integ/cli/aws-helpers.ts
  packages/aws-cdk/test/integ/cli/test.sh
  packages/aws-cdk/test/integ/test-cli-regression-against-current-code.sh
  packages/aws-cdk/test/util.ts
Labels: contribution/core, pr-linter/exempt-readme

#10176 fix(pipelines): changing synth action doesn't restart pipeline
  packages/@aws-cdk/assert/README.md
  packages/@aws-cdk/assert/lib/assertions/have-resource-matchers.ts
  packages/@aws-cdk/assert/test/have-resource.test.ts
  packages/@aws-cdk/pipelines/lib/synths/simple-synth-action.ts
  packages/@aws-cdk/pipelines/test/builds.test.ts
  packages/@aws-cdk/pipelines/test/integ.pipeline-with-assets.expected.json
  packages/@aws-cdk/pipelines/test/integ.pipeline.expected.json
Labels: contribution/core

#10269 chore: parallelize integ tests across regions
  packages/aws-cdk/CONTRIBUTING.md
  packages/aws-cdk/test/integ/cli/aws-helpers.ts
  packages/aws-cdk/test/integ/cli/bootstrapping.integtest.ts
  packages/aws-cdk/test/integ/cli/cdk-helpers.ts
  packages/aws-cdk/test/integ/cli/cli.integtest.ts
  packages/aws-cdk/test/integ/cli/corking.ts
  packages/aws-cdk/test/integ/cli/resource-pool.test.ts
  packages/aws-cdk/test/integ/cli/resource-pool.ts
  packages/aws-cdk/test/integ/cli/test-helpers.ts
  packages/aws-cdk/test/integ/cli/test.sh
Labels: contribution/core

#10266 fix(cloudfront): comment for origin access identity is too long
  packages/@aws-cdk/aws-cloudfront-origins/lib/s3-origin.ts
  packages/@aws-cdk/aws-cloudfront-origins/test/integ.origin-group.expected.json
  packages/@aws-cdk/aws-cloudfront-origins/test/integ.s3-origin.expected.json
  packages/@aws-cdk/aws-cloudfront-origins/test/s3-origin.test.ts
  packages/@aws-cdk/aws-cloudfront/lib/origin_access_identity.ts
  packages/@aws-cdk/aws-cloudfront/test/oai.test.ts
Labels: contribution/core

#10297 chore(cli): install modules before bootstrap in integ tests
  packages/aws-cdk/test/integ/cli/cdk-helpers.ts
Labels: contribution/core

#10299 fix(kms): do not change the principal to root for imported resources in dependent Stacks
  packages/@aws-cdk/aws-kms/lib/key.ts
  packages/@aws-cdk/pipelines/test/cross-environment-infra.test.ts
Labels: contribution/core

#10291 fix(rds): Make most DatabaseClusterAttributes properties optional
  packages/@aws-cdk/aws-rds/lib/cluster-ref.ts
  packages/@aws-cdk/aws-rds/lib/cluster.ts
  packages/@aws-cdk/aws-rds/test/test.cluster.ts
Labels: contribution/core

#10023 feat(appsync): support enumeration types for code-first approach
  packages/@aws-cdk/aws-appsync/README.md
  packages/@aws-cdk/aws-appsync/lib/schema-intermediate.ts
  packages/@aws-cdk/aws-appsync/test/appsync-enum-type.test.ts
  packages/@aws-cdk/aws-appsync/test/integ.graphql-schema.expected.json
  packages/@aws-cdk/aws-appsync/test/integ.graphql-schema.ts
Labels: @aws-cdk/aws-appsync, contribution/core

#10078 feat(appsync): add support for subscriptions for code-first schema generation
  packages/@aws-cdk/aws-appsync/README.md
  packages/@aws-cdk/aws-appsync/lib/graphqlapi.ts
  packages/@aws-cdk/aws-appsync/lib/schema-base.ts
  packages/@aws-cdk/aws-appsync/lib/schema.ts
  packages/@aws-cdk/aws-appsync/test/appsync-schema.test.ts
  packages/@aws-cdk/aws-appsync/test/integ.graphql-schema.expected.json
  packages/@aws-cdk/aws-appsync/test/integ.graphql-schema.ts
Labels: @aws-cdk/aws-appsync, contribution/core

#10315 chore(cfn-include): updates to the ReadMe
  packages/@aws-cdk/cloudformation-include/README.md
Labels: contribution/core

#10309 feat(secretsmanager): import secrets by name
  packages/@aws-cdk/aws-docdb/package.json
  packages/@aws-cdk/aws-rds/package.json
  packages/@aws-cdk/aws-redshift/package.json
  packages/@aws-cdk/aws-secretsmanager/README.md
  packages/@aws-cdk/aws-secretsmanager/lib/secret.ts
  packages/@aws-cdk/aws-secretsmanager/package.json
  packages/@aws-cdk/aws-secretsmanager/test/test.secret.ts
Labels: contribution/core

#10336 chore(merge-back): 1.63.0
  CHANGELOG.md
  lerna.json
Labels: pr/no-squash

#10337 fix(bootstrapping): `--cloudformation-execution-policies` not checked
  packages/aws-cdk/bin/cdk.ts
  packages/aws-cdk/lib/api/bootstrap/bootstrap-environment.ts
  packages/aws-cdk/test/api/bootstrap2.test.ts
  packages/aws-cdk/test/integ/cli/bootstrapping.integtest.ts
Labels: contribution/core

#10343 fix(cli): `cdk synth` fails if AWS_ credentials have expired
  packages/aws-cdk/lib/api/aws-auth/sdk-provider.ts
  packages/aws-cdk/test/api/sdk-provider.test.ts
Labels: contribution/core

#10339 fix(eks): circular dependencies when security groups from other stacks are used
  packages/@aws-cdk/aws-eks/lib/cluster.ts
  packages/@aws-cdk/aws-eks/test/integ.eks-cluster-private-endpoint.expected.json
  packages/@aws-cdk/aws-eks/test/integ.eks-cluster.expected.json
  packages/@aws-cdk/aws-eks/test/test.cluster.ts
Labels: contribution/core

#10358 chore: add `return await` linting rule
  packages/@aws-cdk/aws-eks/lib/cluster-resource-handler/cluster.ts
  packages/@aws-cdk/aws-iam/test/oidc-provider.test.ts
  packages/@aws-cdk/custom-resources/lib/provider-framework/runtime/framework.ts
  packages/@aws-cdk/custom-resources/lib/provider-framework/runtime/outbound.ts
  packages/@aws-cdk/custom-resources/test/provider-framework/integration-test-fixtures/s3-file-handler/index.ts
  packages/aws-cdk/bin/cdk.ts
  packages/aws-cdk/lib/api/aws-auth/credential-plugins.ts
  packages/aws-cdk/lib/assets.ts
  packages/aws-cdk/lib/context-providers/vpcs.ts
  packages/aws-cdk/lib/init.ts
  packages/aws-cdk/test/api/cloud-assembly.test.ts
  packages/aws-cdk/test/integ/cli/aws-helpers.ts
  packages/aws-cdk/test/integ/cli/cdk-helpers.ts
  tools/cdk-build-tools/config/eslintrc.js
  tools/cfn2ts/bin/cfn2ts.ts
  tools/cfn2ts/lib/augmentation-generator.ts
  tools/cfn2ts/lib/codegen.ts
  tools/ubergen/bin/ubergen.ts
Labels: contribution/core

#10346 chore: add yarn upgrade workflow
  .github/workflows/yarn-upgrade.yml
Labels: contribution/core, effort/small, ops-excellence, p1

#10362 fix(cli): `--profile` is ignored if AWS_ variables are set
  packages/aws-cdk/lib/api/aws-auth/awscli-compatible.ts
  packages/aws-cdk/test/api/sdk-provider.test.ts
  packages/aws-cdk/test/util.ts
Labels: contribution/core

#10340 feat(redshift): support existing cluster subnet groups
  packages/@aws-cdk/aws-redshift/lib/cluster.ts
  packages/@aws-cdk/aws-redshift/lib/index.ts
  packages/@aws-cdk/aws-redshift/lib/subnet-group.ts
  packages/@aws-cdk/aws-redshift/package.json
  packages/@aws-cdk/aws-redshift/test/cluster.test.ts
  packages/@aws-cdk/aws-redshift/test/subnet-group.test.ts
Labels: contribution/core, pr-linter/exempt-readme

#10316 fix: SSM Association 'parameters' property has incorrect type
  packages/@aws-cdk/aws-ssm/test/test.ssm-document.ts
  packages/@aws-cdk/cfnspec/lib/schema/property.ts
  packages/@aws-cdk/cfnspec/spec-source/540_SSM_Association_Parameters_patch.json
  packages/@aws-cdk/cfnspec/test/spec-validators.ts
  packages/@aws-cdk/cloudformation-include/test/test-templates/ssm-association.json
  packages/@aws-cdk/cloudformation-include/test/valid-templates.test.ts
  tools/cfn2ts/lib/codegen.ts
  tools/cfn2ts/lib/genspec.ts
  tools/cfn2ts/lib/spec-utils.ts
Labels: contribution/core

#10384 chore: fix integ tests
  packages/aws-cdk/test/integ/cli-regression-patches/v1.63.0/NOTES.md
  packages/aws-cdk/test/integ/cli-regression-patches/v1.63.0/skip-tests.txt
  packages/aws-cdk/test/integ/cli/bootstrapping.integtest.ts
Labels: contribution/core

#10389 fix(redshift): cluster defaultChild broken after adding subnet group
  packages/@aws-cdk/aws-redshift/lib/cluster.ts
  packages/@aws-cdk/aws-redshift/lib/subnet-group.ts
  packages/@aws-cdk/aws-redshift/test/cluster.test.ts
Labels: contribution/core

#10351 chore(core): add missing maturities
  packages/@aws-cdk/aws-apigatewayv2/package.json
  packages/@aws-cdk/aws-cloudfront/package.json
  packages/@aws-cdk/aws-cognito/package.json
Labels: contribution/core

#10383 chore: update module description to align with other modules
  packages/@aws-cdk/aws-cloudformation/package.json
  packages/@aws-cdk/aws-cloudfront-origins/package.json
  packages/@aws-cdk/aws-cloudfront/package.json
  packages/@aws-cdk/aws-cloudtrail/package.json
  packages/@aws-cdk/aws-cloudwatch/package.json
  packages/@aws-cdk/aws-codebuild/package.json
  packages/@aws-cdk/aws-codecommit/package.json
  packages/@aws-cdk/aws-dynamodb/package.json
  packages/@aws-cdk/aws-ec2/package.json
  packages/@aws-cdk/aws-ecs-patterns/package.json
  packages/@aws-cdk/aws-elasticloadbalancing/package.json
  packages/@aws-cdk/aws-kinesis/package.json
  packages/@aws-cdk/aws-kms/package.json
  packages/@aws-cdk/aws-lambda-nodejs/package.json
  packages/@aws-cdk/aws-lambda-python/package.json
  packages/@aws-cdk/aws-lambda/package.json
  packages/@aws-cdk/aws-rds/package.json
  packages/@aws-cdk/aws-route53-patterns/package.json
  packages/@aws-cdk/aws-route53-targets/package.json
  packages/@aws-cdk/aws-route53/package.json
  packages/@aws-cdk/aws-s3/package.json
  packages/@aws-cdk/aws-sns/package.json
  packages/@aws-cdk/aws-sqs/package.json
Labels: contribution/core

#10373 fix(cfn-include): allow referring to Conditions in Outputs and Rules
  packages/@aws-cdk/cloudformation-include/lib/cfn-include.ts
  packages/@aws-cdk/cloudformation-include/test/test-templates/only-empty-bucket-with-parameters.json
  packages/@aws-cdk/cloudformation-include/test/test-templates/only-parameters-and-rule.json
Labels: contribution/core

#10378 fix(diff): allow strings to be passed for boolean properties
  packages/@aws-cdk/cloudformation-diff/lib/diff/util.ts
  packages/@aws-cdk/cloudformation-diff/test/diff-template.test.ts
  packages/@aws-cdk/cloudformation-include/test/test-templates/fn-sub-map-dotted-attributes.json
  packages/@aws-cdk/cloudformation-include/test/test-templates/resource-attribute-update-policy.json
  packages/@aws-cdk/core/lib/cfn-parse.ts
Labels: contribution/core

#10398 chore(config): clean up some of the doc strings and README
  packages/@aws-cdk/aws-config/README.md
  packages/@aws-cdk/aws-config/lib/managed-rules.ts
  packages/@aws-cdk/aws-config/lib/rule.ts
Labels: contribution/core

#10084 chore: update cli owner in auto assign/label workflow
  .github/workflows/issue-label-assign.yml
Labels: contribution/core

#10404 chore(init-templates): enable dotnet runtime major-version roll-forward
  packages/aws-cdk/lib/init-templates/app/csharp/src/%name.PascalCased%/%name.PascalCased%.template.csproj
  packages/aws-cdk/lib/init-templates/app/fsharp/src/%name.PascalCased%/%name.PascalCased%.template.fsproj
  packages/aws-cdk/lib/init-templates/sample-app/csharp/src/%name.PascalCased%/%name.PascalCased%.template.csproj
  packages/aws-cdk/lib/init-templates/sample-app/fsharp/src/%name.PascalCased%/%name.PascalCased%.template.fsproj
Labels: contribution/core

#10132 fix(rds): cannot use s3ImportBuckets or s3ExportBuckets with aurora postgres
  packages/@aws-cdk/aws-rds/lib/cluster-engine.ts
  packages/@aws-cdk/aws-rds/lib/cluster.ts
  packages/@aws-cdk/aws-rds/test/test.cluster.ts
Labels: @aws-cdk/aws-rds, contribution/core

#10365 fix(bootstrap): no longer creates KMS master key by default
  packages/aws-cdk/bin/cdk.ts
  packages/aws-cdk/lib/api/bootstrap/bootstrap-environment.ts
  packages/aws-cdk/lib/api/bootstrap/bootstrap-props.ts
  packages/aws-cdk/lib/api/bootstrap/bootstrap-template.yaml
  packages/aws-cdk/lib/api/util/cloudformation.ts
  packages/aws-cdk/test/api/bootstrap.test.ts
  packages/aws-cdk/test/api/bootstrap2.test.ts
  packages/aws-cdk/test/util/cloudformation.test.ts
Labels: contribution/core

#10376 feat: add support for the 'Version' resource attribute
  packages/@aws-cdk/cloudformation-include/lib/cfn-include.ts
  packages/@aws-cdk/cloudformation-include/test/invalid-templates.test.ts
  packages/@aws-cdk/cloudformation-include/test/test-templates/custom-resource-with-attributes.json
  packages/@aws-cdk/core/lib/cfn-parse.ts
  packages/@aws-cdk/core/lib/cfn-resource.ts
Labels: contribution/core, pr-linter/exempt-readme

#10410 chore(secretsmanager): Remove unused secretName attribute
  packages/@aws-cdk/aws-secretsmanager/lib/secret.ts
Labels: contribution/core

#10409 chore: restrict yarn-upgrade workflow to minor
  .github/workflows/yarn-upgrade.yml
Labels: contribution/core

#10370 feat(rds): S3 import and export for DatabaseInstances
  packages/@aws-cdk/aws-rds/README.md
  packages/@aws-cdk/aws-rds/lib/cluster.ts
  packages/@aws-cdk/aws-rds/lib/instance-engine.ts
  packages/@aws-cdk/aws-rds/lib/instance.ts
  packages/@aws-cdk/aws-rds/lib/option-group.ts
  packages/@aws-cdk/aws-rds/lib/private/util.ts
  packages/@aws-cdk/aws-rds/test/integ.instance-s3.expected.json
  packages/@aws-cdk/aws-rds/test/integ.instance-s3.ts
  packages/@aws-cdk/aws-rds/test/test.instance-engine.ts
  packages/@aws-cdk/aws-rds/test/test.instance.ts
Labels: contribution/core

#10412 fix(rds): standardize removal policies and deletion protection
  packages/@aws-cdk/aws-rds/lib/cluster.ts
  packages/@aws-cdk/aws-rds/lib/instance.ts
  packages/@aws-cdk/aws-rds/lib/private/util.ts
  packages/@aws-cdk/aws-rds/test/integ.instance-s3.expected.json
  packages/@aws-cdk/aws-rds/test/integ.instance.lit.expected.json
  packages/@aws-cdk/aws-rds/test/integ.proxy.expected.json
  packages/@aws-cdk/aws-rds/test/test.instance.ts
Labels: contribution/core

#10391 feat(rds): support existing cluster subnet groups
  packages/@aws-cdk/aws-rds/lib/cluster.ts
  packages/@aws-cdk/aws-rds/lib/index.ts
  packages/@aws-cdk/aws-rds/lib/instance.ts
  packages/@aws-cdk/aws-rds/lib/subnet-group.ts
  packages/@aws-cdk/aws-rds/package.json
  packages/@aws-cdk/aws-rds/test/test.cluster.ts
  packages/@aws-cdk/aws-rds/test/test.instance.ts
  packages/@aws-cdk/aws-rds/test/test.subnet-group.ts
Labels: contribution/core, pr-linter/exempt-readme

#10422 fix(core): CfnParameter of Number type cannot be used as a string
  packages/@aws-cdk/core/lib/cfn-parameter.ts
  packages/@aws-cdk/core/test/test.cfn-parameter.ts
Labels: contribution/core

#10292 feat(cfn-include): add 'loadNestedStack()' method
  packages/@aws-cdk/cloudformation-include/README.md
  packages/@aws-cdk/cloudformation-include/lib/cfn-include.ts
  packages/@aws-cdk/cloudformation-include/package.json
  packages/@aws-cdk/cloudformation-include/test/integ.nested-stacks.ts
  packages/@aws-cdk/cloudformation-include/test/nested-stacks.test.ts
Labels: contribution/core

#10436 feat(cfn-include): the package cloudformation-include is now 'Developer Preview'
  packages/@aws-cdk/cloudformation-include/README.md
  packages/@aws-cdk/cloudformation-include/package.json
Labels: contribution/core, pr-linter/exempt-readme, pr-linter/exempt-test

#8450 fix(dynamodb): cannot change serverSideEncryption from true to false
  packages/@aws-cdk/aws-dynamodb/lib/table.ts
  packages/@aws-cdk/aws-dynamodb/test/integ.dynamodb.sse.expected.json
Labels: contribution/core

#10437 chore(core): add @amzn to version reporting
  packages/@aws-cdk/core/lib/private/runtime-info.ts
Labels: contribution/core

#10328 fix(cli): stack outputs aren't sorted
  packages/aws-cdk/lib/cdk-toolkit.ts
Labels: pr-linter/exempt-test

#10369 feat(ec2): generic ssm backed machine image
  packages/@aws-cdk/aws-ec2/lib/machine-image.ts
  packages/@aws-cdk/aws-ec2/test/example.images.lit.ts
  packages/@aws-cdk/aws-ec2/test/machine-image.test.ts
Labels: pr-linter/exempt-readme

#10415 fix(cfn-include): correctly handle the 'AWS::CloudFormation::CustomResource' resource type
  packages/@aws-cdk/cloudformation-include/lib/cfn-include.ts
  packages/@aws-cdk/cloudformation-include/test/test-templates/custom-resource-with-attributes.json
Labels: contribution/core

#10450 fix(ec2): `InitFile` does not work on Windows
  packages/@aws-cdk/aws-ec2/lib/cfn-init-elements.ts
  packages/@aws-cdk/aws-ec2/test/cfn-init-element.test.ts
Labels: contribution/core

#10426 fix(s3-notifications): lambda destination creates a circular dependency when bucket and lambda are in different stacks
  packages/@aws-cdk/aws-lambda-event-sources/test/integ.s3.expected.json
  packages/@aws-cdk/aws-s3-notifications/lib/lambda.ts
  packages/@aws-cdk/aws-s3-notifications/test/lambda/integ.bucket-notifications.expected.json
  packages/@aws-cdk/aws-s3-notifications/test/lambda/lambda.test.ts
Labels: contribution/core

#10418 fix(cloudwatch): LTE operator renders wrong symbol
  packages/@aws-cdk/aws-cloudwatch/lib/alarm.ts
Labels: pr-linter/exempt-test

#8828 fix(lambda): unable to add permissions to imported lambda functions
  packages/@aws-cdk/aws-lambda/lib/alias.ts
  packages/@aws-cdk/aws-lambda/lib/function-base.ts
  packages/@aws-cdk/aws-lambda/lib/function.ts
  packages/@aws-cdk/aws-lambda/lib/lambda-version.ts
  packages/@aws-cdk/aws-lambda/test/test.lambda.ts
Labels: @aws-cdk/aws-lambda, contribution/core

#10456 chore: don't capture stack traces for `PostResolveToken`
  packages/@aws-cdk/core/lib/private/intrinsic.ts
  packages/@aws-cdk/core/lib/util.ts
Labels: contribution/core

#10381 fix(diff): handle YAML short-forms like '!GetAtt' in diff
  package.json
  packages/@aws-cdk/cloudformation-include/lib/file-utils.ts
  packages/@aws-cdk/cloudformation-include/package.json
  packages/@aws-cdk/yaml-cfn/.eslintrc.js
  packages/@aws-cdk/yaml-cfn/.gitignore
  packages/@aws-cdk/yaml-cfn/.npmignore
  packages/@aws-cdk/yaml-cfn/LICENSE
  packages/@aws-cdk/yaml-cfn/NOTICE
  packages/@aws-cdk/yaml-cfn/README.md
  packages/@aws-cdk/yaml-cfn/jest.config.js
  packages/@aws-cdk/yaml-cfn/lib/index.ts
  packages/@aws-cdk/yaml-cfn/lib/yaml.ts
  packages/@aws-cdk/yaml-cfn/package.json
  packages/@aws-cdk/yaml-cfn/test/yaml.test.ts
  packages/aws-cdk-lib/package.json
  packages/aws-cdk/lib/serialize.ts
  packages/aws-cdk/package.json
  packages/aws-cdk/test/api/bootstrap.test.ts
  packages/aws-cdk/test/yaml.test.ts
  packages/decdk/package.json
  packages/monocdk-experiment/package.json
  tools/pkglint/lib/rules.ts
Labels: contribution/core

#10459 fix(eks): cannot import a cluster with cdk managed `kubectlPrivateSubnets`
  packages/@aws-cdk/aws-eks/lib/cluster.ts
  packages/@aws-cdk/aws-eks/test/test.cluster.ts
Labels: contribution/core

#10440 docs(codepipeline-actions): update Github Access Token docs section
  packages/@aws-cdk/aws-codepipeline-actions/README.md
Labels: contribution/core

#10460 fix(codebuild): Project.addFileSystemLocation does not work without providing locations at construction
  packages/@aws-cdk/aws-codebuild/lib/project.ts
  packages/@aws-cdk/aws-codebuild/test/test.codebuild.ts
Labels: contribution/core

#10465 feat(core): add parseDomainName to Fn class
  packages/@aws-cdk/core/lib/cfn-fn.ts
  packages/@aws-cdk/core/test/test.fn.ts
Labels: pr-linter/exempt-readme

#10451 fix(cli): OS usernames cannot have Unicode characters
  packages/aws-cdk/lib/api/aws-auth/sdk-provider.ts
  packages/aws-cdk/lib/api/aws-auth/sdk.ts
  packages/aws-cdk/test/api/sdk-provider.test.ts
  packages/cdk-assets/bin/publish.ts
Labels: contribution/core

#10445 feat(lambda): kafka topic as an event source
  packages/@aws-cdk/aws-lambda/lib/event-source-mapping.ts
  packages/@aws-cdk/aws-lambda/test/test.event-source-mapping.ts
Labels: pr-linter/exempt-readme

#10470 feat: add configuration for GitHub CodeSpaces
  .devcontainer.json
Labels: pr-linter/exempt-readme, pr-linter/exempt-test

#10483 chore: revert casing of EFSVolumeConfiguration to prevent breaking changes
  packages/@aws-cdk/aws-ecs/lib/base/task-definition.ts
  packages/@aws-cdk/aws-ecs/test/ec2/test.ec2-task-definition.ts
  packages/@aws-cdk/cfnspec/spec-source/620_Ecs_TaskDefinition_EfsVolumeConfiguration_patch.json
Labels: contribution/core

#10496 chore(eks): readme touchups
  packages/@aws-cdk/aws-eks/README.md
Labels: contribution/core

#10472 chore(awslint): rules permit constructs to extend from 'constructs' module
  packages/@aws-cdk/aws-s3/lib/bucket-policy.ts
  packages/@aws-cdk/aws-s3/lib/bucket.ts
  packages/@aws-cdk/aws-s3/lib/util.ts
  packages/@aws-cdk/aws-s3/package.json
  packages/@aws-cdk/aws-s3/test/test.aspect.ts
  packages/@aws-cdk/core/lib/construct-compat.ts
  packages/@aws-cdk/core/lib/private/physical-name-generator.ts
  packages/@aws-cdk/core/lib/resource.ts
  packages/@aws-cdk/core/lib/stack.ts
  packages/@aws-cdk/core/lib/stage.ts
  packages/@aws-cdk/core/package.json
  packages/awslint/lib/rules/construct.ts
  packages/awslint/lib/rules/core-types.ts
  packages/awslint/lib/rules/imports.ts
  tools/cdk-build-tools/bin/cdk-build.ts
  tools/cdk-build-tools/lib/compile.ts
  tools/cdk-build-tools/lib/lint.ts
  tools/cdk-build-tools/lib/package-info.ts
Labels: contribution/core

#10458 feat(rds): support setting database master users from existing secrets
  packages/@aws-cdk/aws-rds/README.md
  packages/@aws-cdk/aws-rds/lib/cluster.ts
  packages/@aws-cdk/aws-rds/lib/instance.ts
  packages/@aws-cdk/aws-rds/lib/props.ts
  packages/@aws-cdk/aws-rds/test/integ.cluster-rotation.lit.ts
  packages/@aws-cdk/aws-rds/test/integ.cluster-s3.ts
  packages/@aws-cdk/aws-rds/test/integ.cluster.ts
  packages/@aws-cdk/aws-rds/test/integ.instance-s3.ts
  packages/@aws-cdk/aws-rds/test/integ.instance.lit.ts
  packages/@aws-cdk/aws-rds/test/integ.proxy.ts
  packages/@aws-cdk/aws-rds/test/test.cluster.ts
  packages/@aws-cdk/aws-rds/test/test.instance.ts
  packages/@aws-cdk/aws-rds/test/test.proxy.ts
Labels: contribution/core

#10488 fix(rds): allow creating Proxies for imported resources
  packages/@aws-cdk/aws-rds/lib/cluster-engine.ts
  packages/@aws-cdk/aws-rds/lib/cluster-ref.ts
  packages/@aws-cdk/aws-rds/lib/cluster.ts
  packages/@aws-cdk/aws-rds/lib/engine.ts
  packages/@aws-cdk/aws-rds/lib/instance-engine.ts
  packages/@aws-cdk/aws-rds/lib/instance.ts
  packages/@aws-cdk/aws-rds/lib/private/util.ts
  packages/@aws-cdk/aws-rds/lib/proxy.ts
  packages/@aws-cdk/aws-rds/test/test.proxy.ts
Labels: contribution/core

#10502 chore(rds): add extra abstract properties to base classes to fix the build
  packages/@aws-cdk/aws-rds/lib/cluster.ts
  packages/@aws-cdk/aws-rds/lib/instance.ts
Labels: contribution/core

#10505 chore(merge-back): 1.64.0
  CHANGELOG.md
  lerna.json
  packages/@aws-cdk/aws-ecs/lib/base/task-definition.ts
  packages/@aws-cdk/aws-ecs/test/ec2/test.ec2-task-definition.ts
  packages/@aws-cdk/cfnspec/spec-source/620_Ecs_TaskDefinition_EfsVolumeConfiguration_patch.json
Labels: contribution/core, pr/no-squash

#10503 chore(integ): run all CDK integ tests with `-v`
  packages/aws-cdk/test/integ/cli-regression-patches/v1.64.0/NOTES.md
  packages/aws-cdk/test/integ/cli-regression-patches/v1.64.0/cdk-helpers.js
  packages/aws-cdk/test/integ/cli/cdk-helpers.ts
Labels: contribution/core

#10511 chore(integ): revert run all CDK integ tests with `-v`
  packages/aws-cdk/test/integ/cli-regression-patches/v1.64.0/NOTES.md
  packages/aws-cdk/test/integ/cli-regression-patches/v1.64.0/cdk-helpers.js
  packages/aws-cdk/test/integ/cli/cdk-helpers.ts
Labels: contribution/core

#10324 feat(rds): add support for update and backup properties to Cluster instances
  packages/@aws-cdk/aws-rds/lib/cluster.ts
  packages/@aws-cdk/aws-rds/lib/props.ts
  packages/@aws-cdk/aws-rds/test/test.cluster.ts
Labels: pr-linter/exempt-readme

#10501 feat(ecs-patterns): allow passthrough of security groups to service
  packages/@aws-cdk/aws-ecs-patterns/README.md
  packages/@aws-cdk/aws-ecs-patterns/lib/fargate/application-load-balanced-fargate-service.ts
  packages/@aws-cdk/aws-ecs-patterns/test/fargate/test.load-balanced-fargate-service.ts
Labels: @aws-cdk/aws-ecs-patterns

#10536 fix(eks): `KubernetesPatch` and `FargateCluster` creates a circular dependency and breaks deployment
  packages/@aws-cdk/aws-eks/lib/k8s-patch.ts
  packages/@aws-cdk/aws-eks/test/integ.fargate-cluster.expected.json
  packages/@aws-cdk/aws-eks/test/integ.fargate-cluster.ts
  packages/@aws-cdk/aws-eks/test/test.k8s-patch.ts
Labels: contribution/core

#10525 chore: run integ test with 'v'
  packages/aws-cdk/test/integ/cli-regression-patches/v1.64.0/NOTES.md
  packages/aws-cdk/test/integ/cli-regression-patches/v1.64.0/cdk-helpers.js
  packages/aws-cdk/test/integ/cli/cdk-helpers.ts
  packages/aws-cdk/test/integ/cli/cli.integtest.ts
Labels: contribution/core

#10541 chore(release): 1.64.1
  CHANGELOG.md
  lerna.json
  packages/@aws-cdk/aws-eks/lib/k8s-patch.ts
  packages/@aws-cdk/aws-eks/test/integ.fargate-cluster.expected.json
  packages/@aws-cdk/aws-eks/test/integ.fargate-cluster.ts
  packages/@aws-cdk/aws-eks/test/test.k8s-patch.ts
Labels: contribution/core, pr/no-squash

#10542 chore: add patch for regression integ tests v1.64
  packages/aws-cdk/test/integ/cli-regression-patches/v1.64.0/cli.integtest.js
Labels: contribution/core

#10544 chore(merge-back): 1.64.1
  CHANGELOG.md
  lerna.json
Labels: pr/no-squash

#10548 chore: patch regression tests v1.64.1
  packages/aws-cdk/test/integ/cli-regression-patches/v1.64.1/NOTES.md
  packages/aws-cdk/test/integ/cli-regression-patches/v1.64.1/cdk-helpers.js
  packages/aws-cdk/test/integ/cli-regression-patches/v1.64.1/cli.integtest.js
Labels: contribution/core

#10546 fix(cfn-include): Fn::GetAtt with a string argument fails to include
  packages/@aws-cdk/cloudformation-include/test/test-templates/get-att-string-form.json
  packages/@aws-cdk/cloudformation-include/test/valid-templates.test.ts
  packages/@aws-cdk/cloudformation-include/test/yaml-templates.test.ts
  packages/@aws-cdk/core/lib/cfn-parse.ts
  packages/@aws-cdk/core/lib/private/cfn-reference.ts
  packages/@aws-cdk/yaml-cfn/lib/yaml.ts
Labels: contribution/core

#10522 feat: support the 'Description' resource attribute
  packages/@aws-cdk/cloudformation-include/lib/cfn-include.ts
  packages/@aws-cdk/cloudformation-include/test/test-templates/custom-resource-with-attributes.json
  packages/@aws-cdk/core/lib/cfn-parse.ts
  packages/@aws-cdk/core/lib/cfn-resource.ts
Labels: contribution/core, pr-linter/exempt-readme

#10474 fix(codebuild): `encryptionKey` cannot be disabled
  packages/@aws-cdk/aws-codebuild/lib/project.ts
  packages/@aws-cdk/aws-codebuild/test/integ.aws-deep-learning-container-build-image.expected.json
  packages/@aws-cdk/aws-codebuild/test/integ.caching.expected.json
  packages/@aws-cdk/aws-codebuild/test/integ.defaults.lit.expected.json
  packages/@aws-cdk/aws-codebuild/test/integ.docker-asset.lit.expected.json
  packages/@aws-cdk/aws-codebuild/test/integ.docker-registry.lit.expected.json
  packages/@aws-cdk/aws-codebuild/test/integ.ecr.lit.expected.json
  packages/@aws-cdk/aws-codebuild/test/integ.github.expected.json
  packages/@aws-cdk/aws-codebuild/test/integ.project-bucket.expected.json
  packages/@aws-cdk/aws-codebuild/test/integ.project-buildspec-artifacts.expected.json
  packages/@aws-cdk/aws-codebuild/test/integ.project-file-system-location.expected.json
  packages/@aws-cdk/aws-codebuild/test/integ.project-secondary-sources-artifacts.expected.json
  packages/@aws-cdk/aws-codebuild/test/integ.project-vpc.expected.json
  packages/@aws-cdk/aws-codebuild/test/test.codebuild.ts
  packages/@aws-cdk/aws-codepipeline-actions/test/integ.pipeline-code-build-multiple-inputs-outputs.expected.json
  packages/@aws-cdk/aws-codepipeline-actions/test/integ.pipeline-ecs-deploy.expected.json
  packages/@aws-cdk/aws-events-targets/test/codebuild/integ.project-events.expected.json
  packages/@aws-cdk/aws-stepfunctions-tasks/test/codebuild/integ.start-build.expected.json
Labels: contribution/core

#10568 fix(secretsmanager): cannot import secrets if ARN is a token
  packages/@aws-cdk/aws-secretsmanager/lib/secret.ts
  packages/@aws-cdk/aws-secretsmanager/test/test.secret.ts
Labels: contribution/core

#10533 fix(pipelines): stack tags
  packages/@aws-cdk/cloud-assembly-schema/lib/cloud-assembly/artifact-schema.ts
  packages/@aws-cdk/cloud-assembly-schema/lib/cloud-assembly/metadata-schema.ts
  packages/@aws-cdk/cloud-assembly-schema/lib/manifest.ts
  packages/@aws-cdk/cloud-assembly-schema/schema/cloud-assembly.schema.json
  packages/@aws-cdk/cloud-assembly-schema/schema/cloud-assembly.version.json
  packages/@aws-cdk/core/lib/stack-synthesizers/_shared.ts
  packages/@aws-cdk/core/lib/tag-manager.ts
  packages/@aws-cdk/core/test/test.stack.ts
  packages/@aws-cdk/cx-api/lib/artifacts/cloudformation-artifact.ts
  packages/@aws-cdk/cx-api/test/stack-artifact.test.ts
  packages/@aws-cdk/cx-api/test/util.ts
  packages/@aws-cdk/pipelines/lib/actions/deploy-cdk-stack-action.ts
  packages/@aws-cdk/pipelines/test/pipeline.test.ts
  packages/aws-cdk/lib/cdk-toolkit.ts
Labels: contribution/core

#10306 fix(core): write Metadata resource in core framework
  packages/@aws-cdk/cloud-assembly-schema/schema/cloud-assembly.version.json
  packages/@aws-cdk/core/lib/app.ts
  packages/@aws-cdk/core/lib/cfn-fn.ts
  packages/@aws-cdk/core/lib/private/metadata-resource.ts
  packages/@aws-cdk/core/lib/private/synthesis.ts
  packages/@aws-cdk/core/lib/stack.ts
  packages/@aws-cdk/core/lib/stage.ts
  packages/@aws-cdk/core/package.json
  packages/@aws-cdk/core/test/test.app.ts
  packages/@aws-cdk/core/test/test.rule.ts
  packages/@aws-cdk/core/test/test.runtime-info.ts
  packages/@aws-cdk/core/test/test.stack.ts
  packages/@aws-cdk/core/test/test.stage.ts
  packages/@aws-cdk/core/test/test.synthesis.ts
  packages/@aws-cdk/cx-api/lib/app.ts
  packages/@aws-cdk/cx-api/lib/cloud-assembly.ts
  packages/@aws-cdk/pipelines/test/testutil.ts
  packages/aws-cdk/lib/api/cxapp/exec.ts
  packages/aws-cdk/lib/settings.ts
Labels: contribution/core

#10566 chore(cfnspec): add junit.xml to ignore files
  packages/@aws-cdk/cfnspec/build-tools/create-missing-libraries.ts
Labels: contribution/core

#10587 chore(cli): undo rename 'versionReporting' => 'analyticsReporting'
  packages/aws-cdk/lib/settings.ts
Labels: contribution/core

#10396 feat(pipelines): allow disabling of KMS keys
  packages/@aws-cdk/aws-codepipeline/README.md
  packages/@aws-cdk/aws-codepipeline/lib/action.ts
  packages/@aws-cdk/aws-codepipeline/lib/artifact.ts
  packages/@aws-cdk/aws-codepipeline/lib/pipeline.ts
  packages/@aws-cdk/aws-codepipeline/lib/private/cross-region-support-stack.ts
  packages/@aws-cdk/aws-codepipeline/lib/private/full-action-descriptor.ts
  packages/@aws-cdk/aws-codepipeline/lib/private/rich-action.ts
  packages/@aws-cdk/aws-codepipeline/lib/private/stage.ts
  packages/@aws-cdk/aws-codepipeline/lib/private/validation.ts
  packages/@aws-cdk/aws-codepipeline/package.json
  packages/@aws-cdk/aws-codepipeline/test/action.test.ts
  packages/@aws-cdk/aws-codepipeline/test/cross-env.test.ts
  packages/@aws-cdk/aws-codepipeline/test/fake-build-action.ts
  packages/@aws-cdk/aws-codepipeline/test/general-validation.test.ts
  packages/@aws-cdk/aws-codepipeline/test/stages.test.ts
  packages/@aws-cdk/pipelines/README.md
  packages/@aws-cdk/pipelines/lib/pipeline.ts
Labels: contribution/core

#10129 feat(aws-ecs-builder): RFC 219 - An extendable service class for AWS ECS
  .gitallowed
  CONTRIBUTING.md
  lerna.json
  package.json
  packages/@aws-cdk-containers/ecs-service-extensions/.eslintrc.js
  packages/@aws-cdk-containers/ecs-service-extensions/.gitignore
  packages/@aws-cdk-containers/ecs-service-extensions/.npmignore
  packages/@aws-cdk-containers/ecs-service-extensions/LICENSE
  packages/@aws-cdk-containers/ecs-service-extensions/NOTICE
  packages/@aws-cdk-containers/ecs-service-extensions/README.md
  packages/@aws-cdk-containers/ecs-service-extensions/lib/environment.ts
  packages/@aws-cdk-containers/ecs-service-extensions/lib/extensions/appmesh.ts
  packages/@aws-cdk-containers/ecs-service-extensions/lib/extensions/cloudwatch-agent.ts
  packages/@aws-cdk-containers/ecs-service-extensions/lib/extensions/container.ts
  packages/@aws-cdk-containers/ecs-service-extensions/lib/extensions/extension-interfaces.ts
  packages/@aws-cdk-containers/ecs-service-extensions/lib/extensions/firelens.ts
  packages/@aws-cdk-containers/ecs-service-extensions/lib/extensions/http-load-balancer.ts
  packages/@aws-cdk-containers/ecs-service-extensions/lib/extensions/index.ts
  packages/@aws-cdk-containers/ecs-service-extensions/lib/extensions/scale-on-cpu-utilization.ts
  packages/@aws-cdk-containers/ecs-service-extensions/lib/extensions/xray.ts
  packages/@aws-cdk-containers/ecs-service-extensions/lib/index.ts
  packages/@aws-cdk-containers/ecs-service-extensions/lib/service-description.ts
  packages/@aws-cdk-containers/ecs-service-extensions/lib/service.ts
  packages/@aws-cdk-containers/ecs-service-extensions/package.json
  packages/@aws-cdk-containers/ecs-service-extensions/test/integ.all-service-addons.expected.json
  packages/@aws-cdk-containers/ecs-service-extensions/test/integ.all-service-addons.ts
  packages/@aws-cdk-containers/ecs-service-extensions/test/integ.custom-service-extension.expected.json
  packages/@aws-cdk-containers/ecs-service-extensions/test/integ.custom-service-extension.ts
  packages/@aws-cdk-containers/ecs-service-extensions/test/integ.multiple-environments.expected.json
  packages/@aws-cdk-containers/ecs-service-extensions/test/integ.multiple-environments.ts
  packages/@aws-cdk-containers/ecs-service-extensions/test/test.appmesh.ts
  packages/@aws-cdk-containers/ecs-service-extensions/test/test.cloudwatch-agent.ts
  packages/@aws-cdk-containers/ecs-service-extensions/test/test.environment.ts
  packages/@aws-cdk-containers/ecs-service-extensions/test/test.firelens.ts
  packages/@aws-cdk-containers/ecs-service-extensions/test/test.http-load-balancer.ts
  packages/@aws-cdk-containers/ecs-service-extensions/test/test.scale-on-cpu-utilization.ts
  packages/@aws-cdk-containers/ecs-service-extensions/test/test.service.ts
  packages/@aws-cdk-containers/ecs-service-extensions/test/test.xray.ts
  packages/@aws-cdk-containers/ecs-service-extensions/tsconfig.json
  packages/@aws-cdk/region-info/build-tools/fact-tables.ts
  packages/@aws-cdk/region-info/build-tools/generate-static-data.ts
  packages/@aws-cdk/region-info/lib/fact.ts
  packages/@aws-cdk/region-info/lib/region-info.ts
  yarn.lock
Labels: @aws-cdk/aws-ecs

#10583 feat(rds): add the ability to exclude characters when generating passwords for Cluster, Instance, DatabaseSecret
  packages/@aws-cdk/aws-rds/README.md
  packages/@aws-cdk/aws-rds/lib/cluster.ts
  packages/@aws-cdk/aws-rds/lib/database-secret.ts
  packages/@aws-cdk/aws-rds/lib/instance.ts
  packages/@aws-cdk/aws-rds/lib/private/util.ts
  packages/@aws-cdk/aws-rds/lib/props.ts
  packages/@aws-cdk/aws-rds/test/integ.cluster-rotation.lit.expected.json
  packages/@aws-cdk/aws-rds/test/integ.instance-s3.expected.json
  packages/@aws-cdk/aws-rds/test/integ.instance.lit.expected.json
  packages/@aws-cdk/aws-rds/test/integ.proxy.ts
  packages/@aws-cdk/aws-rds/test/test.cluster.ts
  packages/@aws-cdk/aws-rds/test/test.database-secret.ts
  packages/@aws-cdk/aws-rds/test/test.instance.ts
  packages/@aws-cdk/aws-secretsmanager/README.md
  packages/@aws-cdk/aws-secretsmanager/lib/secret-rotation.ts
  packages/@aws-cdk/aws-secretsmanager/test/test.secret-rotation.ts
Labels: contribution/core

#10518 feat(eks): EKS is now in Developer Preview
  packages/@aws-cdk/aws-eks/README.md
  packages/@aws-cdk/aws-eks/lib/cluster.ts
  packages/@aws-cdk/aws-eks/lib/legacy-cluster.ts
  packages/@aws-cdk/aws-eks/lib/managed-nodegroup.ts
  packages/@aws-cdk/aws-eks/package.json
  packages/@aws-cdk/aws-eks/test/example.ssh-into-nodes.lit.ts
  packages/@aws-cdk/aws-eks/test/integ.eks-cluster.ts
  packages/@aws-cdk/aws-eks/test/test.awsauth.ts
  packages/@aws-cdk/aws-eks/test/test.cluster.ts
  packages/@aws-cdk/aws-eks/test/test.k8s-manifest.ts
  packages/@aws-cdk/aws-eks/test/test.nodegroup.ts
Labels: contribution/core

#10552 feat(s3): support replication and restore s3 notification event types
  packages/@aws-cdk/aws-s3/lib/bucket.ts
  packages/@aws-cdk/aws-s3/test/test.notification.ts
Labels: pr-linter/exempt-readme

#10570 fix(cloudfront): logging bucket uses regional domain name
  packages/@aws-cdk/aws-cloudfront/lib/distribution.ts
  packages/@aws-cdk/aws-cloudfront/lib/web_distribution.ts
  packages/@aws-cdk/aws-cloudfront/test/distribution.test.ts
  packages/@aws-cdk/aws-cloudfront/test/integ.cloudfront-bucket-logging.expected.json
  packages/@aws-cdk/aws-cloudfront/test/integ.distribution-extensive.expected.json
Labels: contribution/core

#10591 chore: ignore parcel updates in yarn-upgrade
  .github/workflows/yarn-upgrade.yml
Labels: contribution/core

#10539 fix(core): properties set to false are not rendered in the template
  packages/@aws-cdk/core/lib/cfn-resource.ts
  packages/@aws-cdk/core/test/test.cfn-resource.ts
Labels: contribution/core

#10588 fix(cognito): callback URLs are specified when OAuth is disabled for user pool clients
  packages/@aws-cdk/aws-cognito/lib/user-pool-client.ts
  packages/@aws-cdk/aws-cognito/test/user-pool-client.test.ts
Labels: @aws-cdk/aws-cognito, contribution/core

#10561 fix(cognito): authFlows require refreshToken in all scenarios
  packages/@aws-cdk/aws-cognito/lib/user-pool-client.ts
  packages/@aws-cdk/aws-cognito/test/integ.user-pool-client-explicit-props.ts
  packages/@aws-cdk/aws-cognito/test/user-pool-client.test.ts
  packages/@aws-cdk/aws-elasticloadbalancingv2-actions/test/integ.cognito.lit.ts
Labels: pr/breaking-change

#10603 docs(lambda): correct default value for retryAttempts
  packages/@aws-cdk/aws-lambda/lib/event-source-mapping.ts
Labels: contribution/core

#10597 fix(rds): default username 'admin' doesn't work for PostgreSQL
  packages/@aws-cdk/aws-rds/lib/cluster-engine.ts
  packages/@aws-cdk/aws-rds/lib/cluster.ts
  packages/@aws-cdk/aws-rds/lib/engine.ts
  packages/@aws-cdk/aws-rds/lib/instance-engine.ts
  packages/@aws-cdk/aws-rds/lib/instance.ts
  packages/@aws-cdk/aws-rds/test/test.cluster.ts
  packages/@aws-cdk/aws-rds/test/test.instance.ts
Labels: contribution/core

#10605 feat(rds): the unversioned Cluster engine constants are no longer deprecated
  packages/@aws-cdk/aws-rds/lib/cluster-engine.ts
Labels: contribution/core, pr-linter/exempt-readme, pr-linter/exempt-test

#10609 fix(secretsmanager): cannot import secrets by ARN without suffix
  packages/@aws-cdk/aws-secretsmanager/lib/secret.ts
  packages/@aws-cdk/aws-secretsmanager/test/test.secret.ts
Labels: contribution/core
