Repository aws/aws-cdk, pull requests merged in 2020-03, with the labels that each got.

#6518 feat(custom-resources): physical resource id union type
  packages/@aws-cdk/custom-resources/README.md
  packages/@aws-cdk/custom-resources/lib/aws-custom-resource/aws-custom-resource.ts
  packages/@aws-cdk/custom-resources/lib/aws-custom-resource/runtime/index.ts
  packages/@aws-cdk/custom-resources/test/aws-custom-resource/aws-custom-resource-provider.test.ts
  packages/@aws-cdk/custom-resources/test/aws-custom-resource/aws-custom-resource.test.ts
  packages/@aws-cdk/custom-resources/test/aws-custom-resource/integ.aws-custom-resource.expected.json
  packages/@aws-cdk/custom-resources/test/aws-custom-resource/integ.aws-custom-resource.ts
Labels: contribution/core

#6523 chore(custom-resources): clear awslint exclusions
  packages/@aws-cdk/custom-resources/lib/aws-custom-resource/aws-custom-resource.ts
  packages/@aws-cdk/custom-resources/package.json
Labels: contribution/core

#6534 fix(rds): setting timezone on DatabaseInstance causes internal failure
  packages/@aws-cdk/aws-rds/lib/instance.ts
  packages/@aws-cdk/aws-rds/test/test.instance.ts
Labels: contribution/core

#6521 feat(custom-resources): enforce user opt-in when auto-generating SDK call policies
  packages/@aws-cdk/custom-resources/README.md
  packages/@aws-cdk/custom-resources/lib/aws-custom-resource/aws-custom-resource.ts
  packages/@aws-cdk/custom-resources/test/aws-custom-resource/aws-custom-resource.test.ts
  packages/@aws-cdk/custom-resources/test/aws-custom-resource/integ.aws-custom-resource.ts
Labels: contribution/core

#6554 chore(custom-resources): README clarifications
  packages/@aws-cdk/custom-resources/README.md
Labels: contribution/core

#6124 docs(apigateway): incorrect docs for requestTemplate property
  packages/@aws-cdk/aws-apigateway/lib/integration.ts
Labels: contribution/core

#6557 chore(cfnspec): prepare cfnspec update for autobump
  packages/@aws-cdk/cfnspec/README.md
  packages/@aws-cdk/cfnspec/build-tools/update.sh
  packages/@aws-cdk/cfnspec/cfn.version
  scripts/bump-cfnspec.sh
Labels: contribution/core

#6553 feat(custom-resources): rename `catchErrorPattern` to `ignoreErrorCodesMatching`
  packages/@aws-cdk/custom-resources/README.md
  packages/@aws-cdk/custom-resources/lib/aws-custom-resource/aws-custom-resource.ts
  packages/@aws-cdk/custom-resources/lib/aws-custom-resource/runtime/index.ts
  packages/@aws-cdk/custom-resources/test/aws-custom-resource/aws-custom-resource-provider.test.ts
  packages/@aws-cdk/custom-resources/test/aws-custom-resource/aws-custom-resource.test.ts
  packages/@aws-cdk/custom-resources/test/aws-custom-resource/integ.aws-custom-resource.expected.json
Labels: contribution/core

#6556 feat(custom-resources): rename `getData*` to `getResponseField*`
  packages/@aws-cdk/custom-resources/README.md
  packages/@aws-cdk/custom-resources/lib/aws-custom-resource/aws-custom-resource.ts
  packages/@aws-cdk/custom-resources/test/aws-custom-resource/aws-custom-resource.test.ts
  packages/@aws-cdk/custom-resources/test/aws-custom-resource/integ.aws-custom-resource.ts
Labels: contribution/core

#6584 feat(custom-resources): module is now stable :)
  packages/@aws-cdk/custom-resources/README.md
  packages/@aws-cdk/custom-resources/package.json
Labels: contribution/core

#6600 chore(prlint): exclude package cfnspec from expecting changes to README
  tools/prlint/index.js
Labels: contribution/core

#6621 chore(batch): include breaking change in previous PR
  .github/workflows/pr-linter.yml
Labels: contribution/core

#6573 chore(prlinter): added commit message validation
  .github/PULL_REQUEST_TEMPLATE.md
  .github/actions/prlinter/index.js
  CONTRIBUTING.md
  tools/prlint/index.js
Labels: contribution/core

#6552 chore(stepfunctions): clean up aws-stepfunctions linter exclusions
  packages/@aws-cdk/aws-stepfunctions/lib/activity.ts
  packages/@aws-cdk/aws-stepfunctions/lib/fields.ts
  packages/@aws-cdk/aws-stepfunctions/lib/input.ts
  packages/@aws-cdk/aws-stepfunctions/lib/state-graph.ts
  packages/@aws-cdk/aws-stepfunctions/lib/states/pass.ts
  packages/@aws-cdk/aws-stepfunctions/lib/states/wait.ts
  packages/@aws-cdk/aws-stepfunctions/lib/types.ts
  packages/@aws-cdk/aws-stepfunctions/package.json
Labels: contribution/core

#6633 chore(codebuild): props parameter of metric() method to be optional
  packages/@aws-cdk/aws-codebuild/lib/project.ts
  packages/@aws-cdk/aws-codebuild/test/test.project.ts
Labels: contribution/core

#6594 fix(cli): codepipeline cross account action fails writing output artifacts
  packages/aws-cdk/lib/api/bootstrap/bootstrap-template.json
Labels: contribution/core, pr/do-not-merge

#6635 feat(dynamodb): expose stream features on ITable
  packages/@aws-cdk/aws-dynamodb/README.md
  packages/@aws-cdk/aws-dynamodb/lib/table.ts
  packages/@aws-cdk/aws-dynamodb/package.json
  packages/@aws-cdk/aws-dynamodb/test/test.dynamodb.ts
  packages/@aws-cdk/aws-lambda-event-sources/lib/dynamodb.ts
Labels: contribution/core, effort/small, package/dynamodb

#6636 chore(eks): consolidate integ tests
  packages/@aws-cdk/aws-eks/README.md
  packages/@aws-cdk/aws-eks/test/integ.eks-cluster.defaults.expected.json
  packages/@aws-cdk/aws-eks/test/integ.eks-cluster.defaults.ts
  packages/@aws-cdk/aws-eks/test/integ.eks-cluster.expected.json
  packages/@aws-cdk/aws-eks/test/integ.eks-cluster.kubectl-disabled.ts
  packages/@aws-cdk/aws-eks/test/integ.eks-cluster.lit.expected.json
  packages/@aws-cdk/aws-eks/test/integ.eks-cluster.lit.ts
  packages/@aws-cdk/aws-eks/test/integ.eks-cluster.ts
  packages/@aws-cdk/aws-eks/test/integ.eks-fargate.expected.json
  packages/@aws-cdk/aws-eks/test/integ.eks-fargate.ts
  packages/@aws-cdk/aws-eks/test/integ.eks-helm.lit.expected.json
  packages/@aws-cdk/aws-eks/test/integ.eks-helm.lit.ts
  packages/@aws-cdk/aws-eks/test/integ.eks-kubectl.lit.expected.json
  packages/@aws-cdk/aws-eks/test/integ.eks-kubectl.lit.ts
  packages/@aws-cdk/aws-eks/test/integ.eks-spot.ts
Labels: contribution/core

#6522 fix(eks): sporadic broken pipe when deploying helm charts
  packages/@aws-cdk/aws-eks/lib/kubectl-handler/helm/__init__.py
  packages/@aws-cdk/aws-eks/test/integ.eks-cluster.expected.json
Labels: contribution/core

#6649 fix(apigateway): type mismatch in C# when setting identitySources
  allowed-breaking-changes.txt
  packages/@aws-cdk/aws-apigateway/lib/authorizers/lambda.ts
Labels: contribution/core

#6671 chore(config): clear awslint exclusions
  packages/@aws-cdk/aws-config/lib/rule.ts
  packages/@aws-cdk/aws-config/package.json
Labels: contribution/core

#6673 chore: add missing ECR permissions to publishing role
  packages/aws-cdk/lib/api/bootstrap/bootstrap-template.json
Labels: contribution/core

#6678 chore(prlinter): revert changes from (#6573)
  .github/PULL_REQUEST_TEMPLATE.md
  .github/actions/prlinter/index.js
  CONTRIBUTING.md
  tools/prlint/index.js
Labels: contribution/core

#6638 chore(cli): Remove Request dependency
  packages/aws-cdk/package.json
  yarn.lock
Labels: package/tools

#6579 chore(stepfunctions-tasks): clean up aws-stepfunctions-tasks linter exclusions
  packages/@aws-cdk/aws-stepfunctions-tasks/lib/publish-to-topic.ts
  packages/@aws-cdk/aws-stepfunctions-tasks/lib/run-ecs-task-base-types.ts
  packages/@aws-cdk/aws-stepfunctions-tasks/lib/run-ecs-task-base.ts
  packages/@aws-cdk/aws-stepfunctions-tasks/lib/run-lambda-task.ts
  packages/@aws-cdk/aws-stepfunctions-tasks/lib/sagemaker-task-base-types.ts
  packages/@aws-cdk/aws-stepfunctions-tasks/lib/sagemaker-train-task.ts
  packages/@aws-cdk/aws-stepfunctions-tasks/lib/sagemaker-transform-task.ts
  packages/@aws-cdk/aws-stepfunctions-tasks/lib/start-execution.ts
  packages/@aws-cdk/aws-stepfunctions-tasks/package.json
Labels: contribution/core

#6412 fix(codepipeline-actions): use IBaseService instead of BaseService in EcsDeployActionProps
  packages/@aws-cdk/aws-codepipeline-actions/lib/ecs/deploy-action.ts
  packages/@aws-cdk/aws-codepipeline-actions/test/ecs/test.ecs-deploy-action.ts
  packages/@aws-cdk/aws-ecs/lib/base/base-service.ts
  packages/@aws-cdk/aws-ecs/lib/base/from-service-attributes.ts
  packages/@aws-cdk/aws-ecs/lib/ec2/ec2-service.ts
  packages/@aws-cdk/aws-ecs/lib/fargate/fargate-service.ts
  packages/@aws-cdk/aws-ecs/test/ec2/test.ec2-service.ts
  packages/@aws-cdk/aws-ecs/test/fargate/test.fargate-service.ts
Labels: package/ecs

#6691 feat(core): duration.toHumanString()
  packages/@aws-cdk/aws-dynamodb/test/test.dynamodb.ts
  packages/@aws-cdk/core/lib/duration.ts
  packages/@aws-cdk/core/package.json
  packages/@aws-cdk/core/test/test.duration.ts
Labels: contribution/core, pr/do-not-merge

#6689 chore: cfnspec bump fails when new modules need to be created
  packages/@aws-cdk/cfnspec/build-tools/create-missing-libraries.ts
  scripts/bump-cfnspec.sh
Labels: contribution/core

#6693 feat(prlinter): support exempting checks from pr based on a label
  tools/prlint/README.md
  tools/prlint/index.js
Labels: contribution/core, pr-linter/exempt-readme, pr-linter/exempt-test

#6698 feat(custom-resources): log retention for AwsCustomResource
  tools/prlint/README.md
Labels: contribution/core, pr-linter/exempt-readme, pr-linter/exempt-test

#6725 docs(apigateway): erroneous docs for Model schema
  packages/@aws-cdk/aws-apigateway/README.md
Labels: contribution/core

#6722 feat(codebuild): add support for Source Credentials
  packages/@aws-cdk/aws-codebuild/README.md
  packages/@aws-cdk/aws-codebuild/lib/index.ts
  packages/@aws-cdk/aws-codebuild/lib/source-credentials.ts
  packages/@aws-cdk/aws-codebuild/package.json
  packages/@aws-cdk/aws-codebuild/test/test.project.ts
Labels: contribution/core

#6737 chore: merge release/1.28.0 to master
  CHANGELOG.md
  lerna.json
Labels: contribution/core, pr/no-squash

#6624 fix(aws-ecs-pattern): allow ScheduledTaskBase to run on a public subnet
  packages/@aws-cdk/aws-ecs-patterns/lib/base/scheduled-task-base.ts
  packages/@aws-cdk/aws-ecs-patterns/test/fargate/test.scheduled-fargate-task.ts
Labels: package/ecs-patterns

#6758 chore(kinesis): remove linter exclusions
  packages/@aws-cdk/aws-kinesis/lib/stream.ts
  packages/@aws-cdk/aws-kinesis/package.json
Labels: contribution/core

#6066 refactor(ec2): MachineImages create appropriate UserData
  packages/@aws-cdk/aws-autoscaling/lib/auto-scaling-group.ts
  packages/@aws-cdk/aws-ec2/lib/instance.ts
  packages/@aws-cdk/aws-ec2/lib/machine-image.ts
  packages/@aws-cdk/aws-ec2/test/test.machine-image.ts
  packages/@aws-cdk/aws-ecs/lib/cluster.ts
  packages/@aws-cdk/aws-eks-legacy/lib/cluster.ts
  packages/@aws-cdk/aws-eks/lib/cluster.ts
  scripts/builddown
Labels: contribution/core

#6487 feat(cognito): user pool - required & custom attributes
  packages/@aws-cdk/aws-cognito/README.md
  packages/@aws-cdk/aws-cognito/lib/index.ts
  packages/@aws-cdk/aws-cognito/lib/user-pool-attr.ts
  packages/@aws-cdk/aws-cognito/lib/user-pool.ts
  packages/@aws-cdk/aws-cognito/package.json
  packages/@aws-cdk/aws-cognito/test/integ.user-pool-explicit-props.expected.json
  packages/@aws-cdk/aws-cognito/test/integ.user-pool-explicit-props.ts
  packages/@aws-cdk/aws-cognito/test/integ.user-pool.expected.json
  packages/@aws-cdk/aws-cognito/test/integ.user-pool.ts
  packages/@aws-cdk/aws-cognito/test/user-pool-attr.test.ts
  packages/@aws-cdk/aws-cognito/test/user-pool.test.ts
Labels: contribution/core

#6684 feat(cli): add permissions to the bootstrap action role for `cdk deploy`
  packages/aws-cdk/lib/api/bootstrap/bootstrap-template.json
Labels: contribution/core, pr-linter/exempt-readme, pr-linter/exempt-test

#6717 feat(cognito): user pool - MFA, password policy and email settings
  packages/@aws-cdk/aws-cognito/README.md
  packages/@aws-cdk/aws-cognito/lib/user-pool.ts
  packages/@aws-cdk/aws-cognito/test/integ.user-pool-explicit-props.expected.json
  packages/@aws-cdk/aws-cognito/test/integ.user-pool-explicit-props.ts
  packages/@aws-cdk/aws-cognito/test/user-pool.test.ts
Labels: contribution/core

#5757 rfc: bring back removed `cdk bootstrap` CLI options
  design/cdk-bootstrap.md
Labels: contribution/core, management/rfc

#6778 chore(codebuild): wrong scope for SourceCredentials
  packages/@aws-cdk/aws-codebuild/lib/source-credentials.ts
Labels: contribution/core

#6769 chore(integ): consistently don't stage
  tools/cdk-integ-tools/bin/cdk-integ.ts
  tools/cdk-integ-tools/lib/integ-helpers.ts
Labels: contribution/core

#6747 feat(cloudwatch): standard set of graph colors
  packages/@aws-cdk/aws-cloudwatch/README.md
  packages/@aws-cdk/aws-cloudwatch/lib/graph.ts
  packages/@aws-cdk/aws-cloudwatch/lib/metric-types.ts
  packages/@aws-cdk/aws-cloudwatch/lib/metric.ts
  packages/@aws-cdk/aws-cloudwatch/package.json
  packages/@aws-cdk/aws-cloudwatch/test/test.graphs.ts
Labels: contribution/core

#6790 chore: stop auditing installed packages every time
  .yarnrc
Labels: contribution/core

#6789 chore: merge release/1.29.0 to master
  CHANGELOG.md
  lerna.json
Labels: contribution/core, pr/no-squash

#6794 fix(core): IConstruct no longer extends IDependable
  packages/@aws-cdk/core/lib/construct-compat.ts
Labels: contribution/core, pr-linter/exempt-test

#6795 chore(release): 1.30.0
  .yarnrc
  CHANGELOG.md
  lerna.json
  packages/@aws-cdk/core/lib/construct-compat.ts
  packages/aws-cdk/package.json
  yarn.lock
Labels: pr/no-squash

#6797 chore: merge release/1.30.0 to master
  CHANGELOG.md
  lerna.json
Labels: contribution/core, pr/no-squash

#6810 chore: document ELBv2 'open' property more clearly
  packages/@aws-cdk/aws-elasticloadbalancingv2/README.md
Labels: contribution/core

#6752 chore(ec2): spelling error in Instance's subnet selection logic.
  packages/@aws-cdk/aws-ec2/lib/instance.ts
Labels: pr-linter/exempt-test

#6799 chore(cli): convert the bootstrap template from JSON to YAML
  design/cdk-bootstrap.md
  packages/aws-cdk/lib/api/bootstrap/bootstrap-environment2.ts
  packages/aws-cdk/lib/api/bootstrap/bootstrap-template.json
  packages/aws-cdk/lib/api/bootstrap/bootstrap-template.yaml
  packages/aws-cdk/lib/serialize.ts
  packages/aws-cdk/test/integ/bootstrap/bootstrap.integ-test.ts
  packages/aws-cdk/test/integ/bootstrap/example-cdk-app/my-test-cdk-stack.d.ts
  packages/aws-cdk/test/integ/bootstrap/example-cdk-app/my-test-cdk-stack.js
Labels: contribution/core

#6756 feat(codepipeline): add experimental support for the BitBucket source action
  packages/@aws-cdk/aws-codepipeline-actions/README.md
  packages/@aws-cdk/aws-codepipeline-actions/lib/bitbucket/source-action.ts
  packages/@aws-cdk/aws-codepipeline-actions/lib/index.ts
  packages/@aws-cdk/aws-codepipeline-actions/test/bitbucket/test.bitbucket-source-action.ts
Labels: contribution/core

#6848 chore(codebuild): remove references to old `extraOutputs` property from docs
  packages/@aws-cdk/aws-codebuild/lib/project.ts
  packages/@aws-cdk/aws-codepipeline-actions/README.md
Labels: contribution/core

#6682 chore(codebuild): remove the reference in our docs to the old UBUNTU_14_04_RUBY_2_5_1 image
  packages/@aws-cdk/aws-codebuild/README.md
Labels: contribution/core

#6892 fix(cloudwatch): unhelpful error when reusing metric IDs
  packages/@aws-cdk/aws-cloudwatch/lib/graph.ts
  packages/@aws-cdk/aws-cloudwatch/lib/private/rendering.ts
  packages/@aws-cdk/aws-cloudwatch/test/test.metric-math.ts
Labels: contribution/core

#6886 chore(apigateway): improve error msg when authorizer has no attached RestApi
  packages/@aws-cdk/aws-apigateway/README.md
  packages/@aws-cdk/aws-apigateway/lib/authorizers/lambda.ts
  packages/@aws-cdk/aws-apigateway/test/authorizers/test.lambda.ts
Labels: contribution/core

#6920 fix(iam): immutable role cannot be used as a construct
  packages/@aws-cdk/aws-iam/lib/private/immutable-role.ts
  packages/@aws-cdk/aws-iam/lib/role.ts
  packages/@aws-cdk/aws-iam/test/immutable-role.test.ts
Labels: contribution/core

#6941 chore(cli): init templates for c# and f# use unsupported version of netcoreapp
  packages/aws-cdk/lib/init-templates/app/csharp/src/%name.PascalCased%/%name.PascalCased%.template.csproj
  packages/aws-cdk/lib/init-templates/app/fsharp/src/%name.PascalCased%/%name.PascalCased%.template.fsproj
  packages/aws-cdk/lib/init-templates/sample-app/csharp/src/%name.PascalCased%/%name.PascalCased%.template.csproj
  packages/aws-cdk/lib/init-templates/sample-app/fsharp/src/%name.PascalCased%/%name.PascalCased%.template.fsproj
Labels: contribution/core

#6951 docs: .NET Core 3.1 is required with JSII v1.1
  README.md
Labels: contribution/core

#6952 Revert "chore(deps): bump fs-extra from 8.1.0 to 9.0.0 (#6820)"
  package.json
  packages/@aws-cdk/aws-lambda-nodejs/package.json
  packages/@aws-cdk/cfnspec/package.json
  packages/@aws-cdk/custom-resources/package.json
  packages/@aws-cdk/region-info/package.json
  packages/aws-cdk/package.json
  packages/decdk/package.json
  tools/awslint/package.json
  tools/cdk-build-tools/package.json
  tools/cdk-integ-tools/package.json
  tools/cfn2ts/package.json
  tools/pkglint/package.json
  tools/pkgtools/package.json
  yarn.lock
Labels: contribution/core

#6761 chore(stepfunctions): add snippet for `Map` state
  packages/@aws-cdk/aws-stepfunctions/README.md
  packages/@aws-cdk/aws-stepfunctions/lib/states/map.ts
Labels: contribution/core, package/stepfunctions

#6957 fix(cdk-assets): context path not honored by Docker asset build
  packages/cdk-assets/lib/private/docker.ts
  packages/cdk-assets/test/docker-images.test.ts
  packages/cdk-assets/test/mock-child_process.ts
Labels: contribution/core

#6938 fix(cognito): user pool - link style email verification fails to deploy
  packages/@aws-cdk/aws-cognito/lib/user-pool.ts
  packages/@aws-cdk/aws-cognito/test/user-pool.test.ts
Labels: contribution/core

#6974 chore: mergify to only dismiss approvals on stale PRs
  .mergify.yml
Labels: contribution/core

#6971 fix(cognito): user pool - `passwordPolicy.minLength` is not optional in all cases
  packages/@aws-cdk/aws-cognito/lib/user-pool.ts
  packages/@aws-cdk/aws-cognito/test/user-pool.test.ts
Labels: contribution/core

#6816 chore(cognito): clean up and document triggers
  packages/@aws-cdk/aws-appsync/test/integ.graphql.expected.json
  packages/@aws-cdk/aws-cognito/README.md
  packages/@aws-cdk/aws-cognito/lib/user-pool.ts
  packages/@aws-cdk/aws-cognito/package.json
  packages/@aws-cdk/aws-cognito/test/integ.user-pool-explicit-props.expected.json
  packages/@aws-cdk/aws-cognito/test/integ.user-pool-explicit-props.ts
  packages/@aws-cdk/aws-cognito/test/integ.user-pool.expected.json
  packages/@aws-cdk/aws-cognito/test/user-pool.test.ts
Labels: contribution/core

#6968 feat(codebuild): support AL2 3.0 & Standard 4.0
  packages/@aws-cdk/aws-codebuild/lib/project.ts
Labels: pr-linter/exempt-readme, pr-linter/exempt-test

#6986 chore: merge release/1.31.0 to master
  CHANGELOG.md
  lerna.json
Labels: contribution/core, pr/no-squash

#6771 feat(lambda): currentVersion, version.addAlias()
  packages/@aws-cdk/aws-lambda/README.md
  packages/@aws-cdk/aws-lambda/lib/alias.ts
  packages/@aws-cdk/aws-lambda/lib/function-base.ts
  packages/@aws-cdk/aws-lambda/lib/function-hash.ts
  packages/@aws-cdk/aws-lambda/lib/function.ts
  packages/@aws-cdk/aws-lambda/lib/lambda-version.ts
  packages/@aws-cdk/aws-lambda/lib/util.ts
  packages/@aws-cdk/aws-lambda/test/integ.current-version.expected.json
  packages/@aws-cdk/aws-lambda/test/integ.current-version.ts
  packages/@aws-cdk/aws-lambda/test/test.function-hash.ts
  packages/@aws-cdk/aws-lambda/test/test.function.ts
  packages/@aws-cdk/aws-lambda/test/test.lambda-version.ts
Labels: contribution/core

#6996 chore(monocdk): support barrel imports
  packages/@monocdk-experiment/assert/clone.sh
  packages/@monocdk-experiment/assert/package.json
  packages/monocdk-experiment/.gitignore
  packages/monocdk-experiment/build.sh
  packages/monocdk-experiment/deps.js
  packages/monocdk-experiment/gen.js
  packages/monocdk-experiment/package.json
Labels: contribution/core

#6970 chore(cognito): integ tests for sign up
  packages/@aws-cdk/aws-cognito/test/integ.user-pool-signup-code.expected.json
  packages/@aws-cdk/aws-cognito/test/integ.user-pool-signup-code.ts
  packages/@aws-cdk/aws-cognito/test/integ.user-pool-signup-link.expected.json
  packages/@aws-cdk/aws-cognito/test/integ.user-pool-signup-link.ts
Labels: contribution/core

#7003 chore: add section to pack a module
  CONTRIBUTING.md
Labels: contribution/core

#7006 chore: add "commit message" section to PR template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: contribution/core

#7004 feat(codebuild): expose aws/windows/base:2.0 image
  packages/@aws-cdk/aws-codebuild/README.md
  packages/@aws-cdk/aws-codebuild/lib/project.ts
  packages/@aws-cdk/aws-codebuild/package.json
  packages/@aws-cdk/aws-codebuild/test/test.codebuild.ts
Labels: contribution/core, effort/small

#7007 chore(monocdk): export "core" types without a namespace
  packages/@monocdk-experiment/assert/clone.sh
  packages/@monocdk-experiment/rewrite-imports/.gitignore
  packages/@monocdk-experiment/rewrite-imports/README.md
  packages/@monocdk-experiment/rewrite-imports/bin/rewrite-imports.ts
  packages/@monocdk-experiment/rewrite-imports/lib/rewrite.ts
  packages/@monocdk-experiment/rewrite-imports/package.json
  packages/@monocdk-experiment/rewrite-imports/test/rewrite.test.ts
  packages/monocdk-experiment/gen.js
Labels: contribution/core

#6997 docs(dynamodb): remove reference to deprecated module
  packages/@aws-cdk/aws-dynamodb/README.md
Labels: contribution/core, effort/small

#7017 chore(monocdk-experiment): add missing dev dependency
  packages/@monocdk-experiment/rewrite-imports/package.json
Labels: contribution/core

#6961 feat(ec2): EFS interface VPC endpoint
  packages/@aws-cdk/aws-ec2/README.md
  packages/@aws-cdk/aws-ec2/lib/vpc-endpoint.ts
  packages/@aws-cdk/aws-ec2/package.json
  packages/@aws-cdk/aws-ec2/test/test.vpc-endpoint.ts
Labels: package/ec2

#7021 fix(rewrite-imports): incorrect main in package.json
  packages/@monocdk-experiment/rewrite-imports/.npmignore
  packages/@monocdk-experiment/rewrite-imports/package.json
Labels: contribution/core

#7008 fix(stepfunctions-tasks): batch job - can not use task input as array size
  packages/@aws-cdk/aws-stepfunctions-tasks/lib/run-batch-job.ts
  packages/@aws-cdk/aws-stepfunctions-tasks/test/run-batch-job.test.ts
Labels: contribution/core

#6940 feat(core): `Size` unit representing digital information quantity
  packages/@aws-cdk/core/README.md
  packages/@aws-cdk/core/lib/duration.ts
  packages/@aws-cdk/core/lib/index.ts
  packages/@aws-cdk/core/lib/size.ts
  packages/@aws-cdk/core/test/test.size.ts
Labels: contribution/core

#7022 fix(cli): can't use credential providers for stacks with assets
  packages/aws-cdk/lib/api/aws-auth/sdk.ts
  packages/aws-cdk/lib/util/asset-publishing.ts
  packages/aws-cdk/test/assets.test.ts
  packages/cdk-assets/lib/private/handlers/files.ts
  packages/cdk-assets/test/files.test.ts
Labels: contribution/core

#7019 fix(core): run prepare on constructs created by aspects
  packages/@aws-cdk/core/lib/construct.ts
Labels: contribution/core

#7027 chore(core): improved rounding options to Size
  packages/@aws-cdk/core/lib/size.ts
  packages/@aws-cdk/core/test/test.size.ts
Labels: contribution/core

#7037 fix(kinesis): retention period does not use Duration type
  packages/@aws-cdk/aws-kinesis/lib/stream.ts
  packages/@aws-cdk/aws-kinesis/test/test.stream.ts
Labels: contribution/core

#7028 chore: fix test by adding 'await' and setting up mocks
  packages/aws-cdk/test/assets.test.ts
  packages/aws-cdk/test/util/mock-sdk.ts
Labels: contribution/core

#6796 fix(stepfunctions-tasks): confusion between multiple ways to run a Lambda
  packages/@aws-cdk/aws-stepfunctions-tasks/lib/invoke-function.ts
  packages/@aws-cdk/aws-stepfunctions/README.md
Labels: contribution/core

#7065 fix(aws-kinesis): test assume order between stacks
  packages/@aws-cdk/aws-kinesis/test/test.stream.ts
Labels: contribution/core

#7064 chore: add key to disable announcing releases in awscdkio when creating missing libraries
  packages/@aws-cdk/cfnspec/build-tools/create-missing-libraries.ts
Labels: contribution/core

#7068 chore(batch): fix docstring for minVcpu in compute-environment
  packages/@aws-cdk/aws-batch/lib/compute-environment.ts
Labels: contribution/core

#7038 docs(kinesis): refresh README and add updated snippets
  packages/@aws-cdk/aws-kinesis/README.md
Labels: contribution/core, package/kinesis

#7057 feat(kinesis): stream encryption with the Kinesis master key
  packages/@aws-cdk/aws-kinesis/README.md
  packages/@aws-cdk/aws-kinesis/lib/stream.ts
  packages/@aws-cdk/aws-kinesis/test/test.stream.ts
Labels: contribution/core

#7087 chore(cli): fix bootstrap v2 by adding a missing 'await'
  packages/aws-cdk/lib/api/bootstrap/bootstrap-environment2.ts
Labels: contribution/core

#6748 feat(iam): `ManagedPolicy` can have an initial `PolicyDocument`
  packages/@aws-cdk/aws-iam/lib/managed-policy.ts
  packages/@aws-cdk/aws-iam/test/managed-policy.test.ts
Labels: pr-linter/exempt-readme

#7091 feat(cognito): import an existing user pool client
  packages/@aws-cdk/aws-cognito/README.md
  packages/@aws-cdk/aws-cognito/lib/user-pool-client.ts
  packages/@aws-cdk/aws-cognito/package.json
  packages/@aws-cdk/aws-cognito/test/user-pool-client.test.ts
Labels: contribution/core
