Repository aws/aws-cdk, pull requests merged in 2020-01, with the labels that each got.

#5597 fix(eks): generated cluster name can exceed 100 characters
  packages/@aws-cdk/aws-eks/lib/cluster-resource-handler/handler.ts
  packages/@aws-cdk/aws-eks/test/integ.eks-cluster.defaults.expected.json
  packages/@aws-cdk/aws-eks/test/integ.eks-cluster.lit.expected.json
  packages/@aws-cdk/aws-eks/test/integ.eks-helm.lit.expected.json
  packages/@aws-cdk/aws-eks/test/integ.eks-kubectl.lit.expected.json
  packages/@aws-cdk/aws-eks/test/integ.eks-spot.expected.json
  packages/@aws-cdk/aws-eks/test/test.cluster-resource-provider.ts
Labels: contribution/core

#5584 chore: proposed refactor for authorizers design
  packages/@aws-cdk/aws-apigateway/lib/authorizer.ts
  packages/@aws-cdk/aws-apigateway/lib/authorizers/authorizer-base.ts
  packages/@aws-cdk/aws-apigateway/lib/authorizers/index.ts
  packages/@aws-cdk/aws-apigateway/lib/authorizers/lambda.ts
  packages/@aws-cdk/aws-apigateway/lib/method.ts
  packages/@aws-cdk/aws-apigateway/test/authorizers/integ.token-authorizer-iam-role.ts
  packages/@aws-cdk/aws-apigateway/test/authorizers/integ.token-authorizer.ts
  packages/@aws-cdk/aws-apigateway/test/authorizers/test.authorizer-base.ts
  packages/@aws-cdk/aws-apigateway/test/test.method.ts
Labels: contribution/core

#5197 feat(apigateway): lambda token authorizer
  packages/@aws-cdk/aws-apigateway/README.md
  packages/@aws-cdk/aws-apigateway/lib/authorizer.ts
  packages/@aws-cdk/aws-apigateway/lib/authorizers/index.ts
  packages/@aws-cdk/aws-apigateway/lib/authorizers/lambda.ts
  packages/@aws-cdk/aws-apigateway/lib/index.ts
  packages/@aws-cdk/aws-apigateway/lib/method.ts
  packages/@aws-cdk/aws-apigateway/package.json
  packages/@aws-cdk/aws-apigateway/test/authorizers/integ.token-authorizer-iam-role.expected.json
  packages/@aws-cdk/aws-apigateway/test/authorizers/integ.token-authorizer-iam-role.ts
  packages/@aws-cdk/aws-apigateway/test/authorizers/integ.token-authorizer.expected.json
  packages/@aws-cdk/aws-apigateway/test/authorizers/integ.token-authorizer.handler/index.ts
  packages/@aws-cdk/aws-apigateway/test/authorizers/integ.token-authorizer.ts
  packages/@aws-cdk/aws-apigateway/test/authorizers/test.lambda.ts
  packages/@aws-cdk/aws-apigateway/test/test.method.ts
Labels: contribution/core

#5625 chore(eks): kubectl resource provider
  packages/@aws-cdk/aws-eks/lib/helm-chart.ts
  packages/@aws-cdk/aws-eks/lib/k8s-resource.ts
  packages/@aws-cdk/aws-eks/lib/kubectl-handler/apply/__init__.py
  packages/@aws-cdk/aws-eks/lib/kubectl-handler/helm/__init__.py
  packages/@aws-cdk/aws-eks/lib/kubectl-handler/index.py
  packages/@aws-cdk/aws-eks/lib/kubectl-provider.ts
  packages/@aws-cdk/aws-eks/test/integ.eks-cluster.defaults.expected.json
  packages/@aws-cdk/aws-eks/test/integ.eks-cluster.lit.expected.json
  packages/@aws-cdk/aws-eks/test/integ.eks-helm.lit.expected.json
  packages/@aws-cdk/aws-eks/test/integ.eks-kubectl.lit.expected.json
  packages/@aws-cdk/aws-eks/test/integ.eks-spot.expected.json
  packages/@aws-cdk/aws-eks/test/test.cluster.ts
Labels: contribution/core

#5582 feat(cloudwatch): support for metric math
  packages/@aws-cdk/aws-applicationautoscaling/lib/step-scaling-policy.ts
  packages/@aws-cdk/aws-applicationautoscaling/lib/target-tracking-scaling-policy.ts
  packages/@aws-cdk/aws-autoscaling/lib/step-scaling-policy.ts
  packages/@aws-cdk/aws-autoscaling/lib/target-tracking-scaling-policy.ts
  packages/@aws-cdk/aws-cloudwatch/README.md
  packages/@aws-cdk/aws-cloudwatch/lib/alarm.ts
  packages/@aws-cdk/aws-cloudwatch/lib/graph.ts
  packages/@aws-cdk/aws-cloudwatch/lib/metric-types.ts
  packages/@aws-cdk/aws-cloudwatch/lib/metric-util.ts
  packages/@aws-cdk/aws-cloudwatch/lib/metric.ts
  packages/@aws-cdk/aws-cloudwatch/test/integ.alarm-and-dashboard.expected.json
  packages/@aws-cdk/aws-cloudwatch/test/integ.math-alarm-and-dashboard.expected.json
  packages/@aws-cdk/aws-cloudwatch/test/integ.math-alarm-and-dashboard.ts
  packages/@aws-cdk/aws-cloudwatch/test/test.graphs.ts
  packages/@aws-cdk/aws-cloudwatch/test/test.metric-math.ts
  packages/@aws-cdk/aws-cloudwatch/test/test.metrics.ts
  packages/@aws-cdk/aws-elasticloadbalancingv2/test/integ.alb.expected.json
Labels: pr-status/do-not-merge

#5615 chore: update jsii to 0.21.1
  package.json
  packages/@aws-cdk/aws-eks/test/integ.eks-cluster.defaults.expected.json
  packages/@aws-cdk/aws-eks/test/integ.eks-cluster.lit.expected.json
  packages/@aws-cdk/aws-eks/test/integ.eks-helm.lit.expected.json
  packages/@aws-cdk/aws-eks/test/integ.eks-kubectl.lit.expected.json
  packages/@aws-cdk/aws-eks/test/integ.eks-spot.expected.json
  packages/@aws-cdk/custom-resources/test/aws-custom-resource/integ.aws-custom-resource.expected.json
  packages/@aws-cdk/custom-resources/test/provider-framework/integ.provider.expected.json
  packages/cdk-dasm/package.json
  packages/decdk/package.json
  tools/awslint/package.json
  tools/cdk-build-tools/package.json
  tools/cdk-integ-tools/.gitignore
  tools/cfn2ts/package.json
  yarn.lock
Labels: contribution/core

#5648 chore(scripts): foreach.sh --up
  CONTRIBUTING.md
  scripts/buildup
  scripts/foreach.sh
Labels: contribution/core, pr-status/do-not-merge

#5011 chore: make examples in `aws-ec2` package compilable
  .gitignore
  CONTRIBUTING.md
  pack.sh
  package.json
  packages/@aws-cdk/aws-cloudformation/lib/nested-stack.ts
  packages/@aws-cdk/aws-ec2/README.md
  packages/@aws-cdk/aws-ec2/lib/instance.ts
  packages/@aws-cdk/aws-ec2/lib/nat.ts
  packages/@aws-cdk/aws-ec2/lib/vpc.ts
  packages/@aws-cdk/aws-ec2/rosetta/conns.ts-fixture
  packages/@aws-cdk/aws-ec2/rosetta/default.ts-fixture
  packages/@aws-cdk/aws-ec2/rosetta/with-vpc.ts-fixture
  scripts/compile-samples
Labels: contribution/core

#5567 feat(ec2): support block devices for `Instance`
  packages/@aws-cdk/aws-autoscaling/lib/auto-scaling-group.ts
  packages/@aws-cdk/aws-autoscaling/lib/index.ts
  packages/@aws-cdk/aws-autoscaling/lib/volume.ts
  packages/@aws-cdk/aws-autoscaling/test/test.auto-scaling-group.ts
  packages/@aws-cdk/aws-ec2/README.md
  packages/@aws-cdk/aws-ec2/lib/index.ts
  packages/@aws-cdk/aws-ec2/lib/instance.ts
  packages/@aws-cdk/aws-ec2/lib/volume.ts
  packages/@aws-cdk/aws-ec2/test/test.instance.ts
Labels: contribution/core, pr-status/do-not-merge

#5659 chore: migrate aws-cdk from nodeunit to jest
  .gitignore
  packages/aws-cdk/lib/api/util/sdk.ts
  packages/aws-cdk/lib/init.ts
  packages/aws-cdk/package.json
  packages/aws-cdk/test/account-cache.test.ts
  packages/aws-cdk/test/api/bootstrap.test.ts
  packages/aws-cdk/test/api/deploy-stack.test.ts
  packages/aws-cdk/test/api/stacks.test.ts
  packages/aws-cdk/test/api/test.bootstrap.ts
  packages/aws-cdk/test/api/test.deploy-stack.ts
  packages/aws-cdk/test/api/test.stacks.ts
  packages/aws-cdk/test/archive.test.ts
  packages/aws-cdk/test/assets.test.ts
  packages/aws-cdk/test/cdk-docs.test.ts
  packages/aws-cdk/test/cdk-doctor.test.ts
  packages/aws-cdk/test/cdk-toolkit.test.ts
  packages/aws-cdk/test/commands/context-command.test.ts
  packages/aws-cdk/test/commands/test.context-command.ts
  packages/aws-cdk/test/context-providers/amis.test.ts
  packages/aws-cdk/test/context-providers/asymmetric-vpcs.test.ts
  packages/aws-cdk/test/context-providers/generic.test.ts
  packages/aws-cdk/test/context-providers/test.amis.ts
  packages/aws-cdk/test/context-providers/test.asymmetric-vpcs.ts
  packages/aws-cdk/test/context-providers/test.generic.ts
  packages/aws-cdk/test/context-providers/test.vpcs.ts
  packages/aws-cdk/test/context-providers/vpcs.test.ts
  packages/aws-cdk/test/context.test.ts
  packages/aws-cdk/test/diff.test.ts
  packages/aws-cdk/test/docker.test.ts
  packages/aws-cdk/test/init.test.ts
  packages/aws-cdk/test/serialize.test.ts
  packages/aws-cdk/test/settings.test.ts
  packages/aws-cdk/test/test.account-cache.ts
  packages/aws-cdk/test/test.archive.ts
  packages/aws-cdk/test/test.assets.ts
  packages/aws-cdk/test/test.cdk-docs.ts
  packages/aws-cdk/test/test.cdk-doctor.ts
  packages/aws-cdk/test/test.context.ts
  packages/aws-cdk/test/test.diff.ts
  packages/aws-cdk/test/test.docker.ts
  packages/aws-cdk/test/test.init.ts
  packages/aws-cdk/test/test.serialize.ts
  packages/aws-cdk/test/test.settings.ts
  packages/aws-cdk/test/test.version.ts
  packages/aws-cdk/test/test.yaml.ts
  packages/aws-cdk/test/util/applydefaults.test.ts
  packages/aws-cdk/test/util/arrays.test.ts
  packages/aws-cdk/test/util/console-formatters.test.ts
  packages/aws-cdk/test/util/mock-sdk.ts
  packages/aws-cdk/test/util/objects.test.ts
  packages/aws-cdk/test/util/test.applydefaults.ts
  packages/aws-cdk/test/util/test.arrays.ts
  packages/aws-cdk/test/util/test.console-formatters.ts
  packages/aws-cdk/test/util/test.objects.ts
  packages/aws-cdk/test/version.test.ts
  packages/aws-cdk/test/yaml.test.ts
Labels: contribution/core, ops-excellence

#5649 fix(eks): aws-auth username not set by default
  packages/@aws-cdk/aws-eks/lib/aws-auth.ts
  packages/@aws-cdk/aws-eks/test/integ.eks-helm.lit.expected.json
  packages/@aws-cdk/aws-eks/test/integ.eks-kubectl.lit.expected.json
  packages/@aws-cdk/aws-eks/test/test.awsauth.ts
  packages/@aws-cdk/aws-eks/test/test.cluster.ts
Labels: contribution/core

#5651 fix(eks): default capacity uses desiredCapacity which is an anti-pattern
  packages/@aws-cdk/aws-eks/README.md
  packages/@aws-cdk/aws-eks/lib/cluster.ts
  packages/@aws-cdk/aws-eks/test/integ.eks-cluster.defaults.expected.json
  packages/@aws-cdk/aws-eks/test/integ.eks-cluster.kubectl-disabled.expected.json
  packages/@aws-cdk/aws-eks/test/integ.eks-cluster.kubectl-disabled.ts
  packages/@aws-cdk/aws-eks/test/integ.eks-cluster.lit.expected.json
  packages/@aws-cdk/aws-eks/test/integ.eks-cluster.lit.ts
  packages/@aws-cdk/aws-eks/test/integ.eks-helm.lit.expected.json
  packages/@aws-cdk/aws-eks/test/integ.eks-helm.lit.ts
  packages/@aws-cdk/aws-eks/test/integ.eks-kubectl.lit.expected.json
  packages/@aws-cdk/aws-eks/test/integ.eks-kubectl.lit.ts
  packages/@aws-cdk/aws-eks/test/integ.eks-spot.expected.json
  packages/@aws-cdk/aws-eks/test/test.cluster.ts
Labels: contribution/core

#5628 feat(cloudwatch): make Metric objects region-aware
  packages/@aws-cdk/aws-cloudwatch/lib/alarm.ts
  packages/@aws-cdk/aws-cloudwatch/lib/graph.ts
  packages/@aws-cdk/aws-cloudwatch/lib/metric.ts
  packages/@aws-cdk/aws-cloudwatch/lib/private/drop-empty-object-at-the-end-of-an-array-token.ts
  packages/@aws-cdk/aws-cloudwatch/lib/private/env-tokens.ts
  packages/@aws-cdk/aws-cloudwatch/lib/private/metric-util.ts
  packages/@aws-cdk/aws-cloudwatch/lib/private/object.ts
  packages/@aws-cdk/aws-cloudwatch/lib/private/rendering.ts
  packages/@aws-cdk/aws-cloudwatch/lib/private/statistic.ts
  packages/@aws-cdk/aws-cloudwatch/test/test.cross-environment.ts
  packages/@aws-cdk/aws-cloudwatch/test/test.metric-math.ts
  packages/@aws-cdk/aws-cloudwatch/test/test.metrics.ts
  packages/@aws-cdk/aws-codebuild/lib/project.ts
  packages/@aws-cdk/aws-ecs/lib/base/base-service.ts
  packages/@aws-cdk/aws-ecs/lib/cluster.ts
  packages/@aws-cdk/aws-elasticloadbalancingv2/lib/alb/application-target-group.ts
  packages/@aws-cdk/aws-elasticloadbalancingv2/lib/nlb/network-load-balancer.ts
  packages/@aws-cdk/aws-logs/lib/log-group.ts
  packages/@aws-cdk/aws-stepfunctions/lib/activity.ts
  packages/@aws-cdk/aws-stepfunctions/lib/state-machine.ts
  packages/@aws-cdk/aws-stepfunctions/lib/states/task.ts
  tools/cfn2ts/lib/augmentation-generator.ts
Labels: contribution/core

#5608 fix(codebuild): cannot use immutable roles for Project
  packages/@aws-cdk/aws-codebuild/lib/project.ts
  packages/@aws-cdk/aws-codebuild/test/test.project.ts
  packages/@aws-cdk/aws-iam/lib/policy.ts
  packages/@aws-cdk/aws-iam/test/policy.test.ts
  packages/@aws-cdk/core/lib/construct.ts
  packages/@aws-cdk/core/test/test.construct.ts
Labels: contribution/core

#5679 fix(core): nested Fn.join with token fails
  packages/@aws-cdk/core/lib/private/cloudformation-lang.ts
  packages/@aws-cdk/core/test/test.fn.ts
Labels: contribution/core

#5662 docs(ec2): improve SecurityGroup documentation
  packages/@aws-cdk/aws-ec2/lib/peer.ts
  packages/@aws-cdk/aws-ec2/lib/security-group.ts
Labels: contribution/core

#5695 chore(cli): fix Java dist integ tests
  packages/aws-cdk/test/integ/run-against-dist.bash
Labels: contribution/core

#5699 chore(cli): fix Java dist integ tests (#5695)
  packages/aws-cdk/test/integ/run-against-dist.bash
Labels: contribution/core

#5692 chore: upgrade tests and docs to use NODEJS_10_X
  packages/@aws-cdk/aws-apigateway/test/authorizers/test.lambda.ts
  packages/@aws-cdk/aws-apigateway/test/test.method.ts
  packages/@aws-cdk/aws-codepipeline-actions/README.md
  packages/@aws-cdk/aws-lambda/README.md
  packages/@aws-cdk/aws-lambda/test/test.lambda.ts
  packages/@aws-cdk/aws-lambda/test/test.layers.ts
  packages/@aws-cdk/aws-lambda/test/test.vpc-lambda.ts
  packages/@aws-cdk/aws-sns-subscriptions/test/subs.test.ts
Labels: contribution/core

#5702 fix(rds): pass the ARN of master instead of its ID in DatabaseInstanceReadReplica
  packages/@aws-cdk/aws-rds/lib/instance.ts
  packages/@aws-cdk/aws-rds/test/test.instance.ts
Labels: contribution/core

#5701 feat(iam): support importing service roles
  packages/@aws-cdk/aws-iam/lib/role.ts
  packages/@aws-cdk/aws-iam/test/role.from-role-arn.test.ts
Labels: contribution/core

#5706 chore: fixup entries in the CHANGELOG
  CHANGELOG.md
Labels: contribution/core

#5698 feat(codepipeline): add CannedACL and CacheControl to S3 deploy action
  packages/@aws-cdk/aws-codepipeline-actions/lib/s3/deploy-action.ts
  packages/@aws-cdk/aws-codepipeline-actions/test/integ.pipeline-s3-deploy.expected.json
  packages/@aws-cdk/aws-codepipeline-actions/test/integ.pipeline-s3-deploy.ts
Labels: contribution/core

#5705 fix(ecr-assets): unable to use one Dockerfile to build multiple images
  packages/@aws-cdk/assets/lib/fs/copy.ts
  packages/@aws-cdk/assets/lib/fs/fingerprint.ts
  packages/@aws-cdk/assets/lib/fs/index.ts
  packages/@aws-cdk/assets/lib/fs/options.ts
  packages/@aws-cdk/assets/lib/index.ts
  packages/@aws-cdk/assets/lib/staging.ts
  packages/@aws-cdk/assets/test/test.staging.ts
  packages/@aws-cdk/aws-ecr-assets/lib/image-asset.ts
  packages/@aws-cdk/aws-ecr-assets/test/demo-image-custom-docker-file/Dockerfile
  packages/@aws-cdk/aws-ecr-assets/test/test.image-asset.ts
Labels: contribution/core

#5721 fix(codepipeline): Action.onStateChange() has wrong detail type
  packages/@aws-cdk/aws-codepipeline-actions/lib/action.ts
  packages/@aws-cdk/aws-codepipeline-actions/test/integ.pipeline-events.expected.json
Labels: contribution/core

#5723 chore(build): save the planet
  tools/cdk-build-tools/lib/package-info.ts
Labels: contribution/core

#5708 chore: fix repeated build of aws-events-targets
  packages/@aws-cdk/aws-events-targets/package.json
Labels: contribution/core

#5729 fix(cloudformation): nested stack example in readme is broken
  packages/@aws-cdk/aws-cloudformation/README.md
Labels: contribution/core

#5731 fix(apigateway): authorizer name is not optional
  packages/@aws-cdk/aws-apigateway/lib/authorizers/lambda.ts
  packages/@aws-cdk/aws-apigateway/test/authorizers/integ.token-authorizer-iam-role.expected.json
  packages/@aws-cdk/aws-apigateway/test/authorizers/integ.token-authorizer.expected.json
Labels: contribution/core

#5770 chore: re-add test that got missed in migration to jest
  packages/aws-cdk/test/docker.test.ts
Labels: contribution/core

#5746 fix(iam): can't use `OrganizationPrincipal` for assuming Role
  packages/@aws-cdk/aws-iam/lib/role.ts
  packages/@aws-cdk/aws-iam/test/integ.role.expected.json
  packages/@aws-cdk/aws-iam/test/integ.role.ts
  packages/@aws-cdk/aws-iam/test/role.test.ts
Labels: contribution/core

#5771 fix(acm): `DnsValidatedCertificate` in non-aws partitions
  packages/@aws-cdk/aws-certificatemanager/lib/dns-validated-certificate.ts
  packages/@aws-cdk/aws-certificatemanager/test/test.dns-validated-certificate.ts
Labels: contribution/core

#5775 fix(cloudwatch): cross-account metrics in env-agnostic stack
  packages/@aws-cdk/aws-cloudwatch/lib/private/env-tokens.ts
  packages/@aws-cdk/aws-cloudwatch/test/test.cross-environment.ts
Labels: contribution/core

#5604 feat(codepipeline): Pipeline Variables
  packages/@aws-cdk/aws-codepipeline-actions/README.md
  packages/@aws-cdk/aws-codepipeline-actions/lib/action.ts
  packages/@aws-cdk/aws-codepipeline-actions/lib/codebuild/build-action.ts
  packages/@aws-cdk/aws-codepipeline-actions/lib/codecommit/source-action.ts
  packages/@aws-cdk/aws-codepipeline-actions/lib/ecr/source-action.ts
  packages/@aws-cdk/aws-codepipeline-actions/lib/github/source-action.ts
  packages/@aws-cdk/aws-codepipeline-actions/lib/lambda/invoke-action.ts
  packages/@aws-cdk/aws-codepipeline-actions/lib/s3/source-action.ts
  packages/@aws-cdk/aws-codepipeline-actions/test/codebuild/test.codebuild-action.ts
  packages/@aws-cdk/aws-codepipeline-actions/test/codecommit/test.codecommit-source-action.ts
  packages/@aws-cdk/aws-codepipeline-actions/test/ecr/test.ecr-source-action.ts
  packages/@aws-cdk/aws-codepipeline-actions/test/github/test.github-source-action.ts
  packages/@aws-cdk/aws-codepipeline-actions/test/lambda/test.lambda-invoke-action.ts
  packages/@aws-cdk/aws-codepipeline-actions/test/s3/test.s3-source-action.ts
  packages/@aws-cdk/aws-codepipeline/README.md
  packages/@aws-cdk/aws-codepipeline/lib/action.ts
  packages/@aws-cdk/aws-codepipeline/lib/full-action-descriptor.ts
  packages/@aws-cdk/aws-codepipeline/lib/pipeline.ts
  packages/@aws-cdk/aws-codepipeline/lib/stage.ts
  packages/@aws-cdk/aws-codepipeline/lib/validation.ts
  packages/@aws-cdk/aws-codepipeline/package.json
  packages/@aws-cdk/aws-codepipeline/test/fake-build-action.ts
  packages/@aws-cdk/aws-codepipeline/test/fake-source-action.ts
  packages/@aws-cdk/aws-codepipeline/test/test.variables.ts
Labels: contribution/core

#5569 feat(iam): `Role.withoutPolicyUpdates()`
  packages/@aws-cdk/aws-codebuild/test/test.project.ts
  packages/@aws-cdk/aws-iam/README.md
  packages/@aws-cdk/aws-iam/lib/private/immutable-role.ts
  packages/@aws-cdk/aws-iam/lib/role.ts
  packages/@aws-cdk/aws-iam/test/immutable-role.test.ts
Labels: contribution/core, pr-status/do-not-merge

#5803 fix(cli): proxy support is broken
  packages/aws-cdk/lib/api/util/sdk.ts
  packages/aws-cdk/package.json
  yarn.lock
Labels: contribution/core, pr-status/do-not-merge

#5813 fix(ecs): cannot separate `Cluster` and `Ec2Service` behind ALB
  packages/@aws-cdk/aws-ec2/lib/security-group.ts
  packages/@aws-cdk/aws-ecs/lib/ec2/ec2-service.ts
  packages/@aws-cdk/aws-ecs/test/ec2/test.cross-stack.ts
Labels: contribution/core

#5394 chore(ecs): correct doc with proper comparison between launch types
  packages/@aws-cdk/aws-ecs/README.md
Labels: package/ecs

#5789 fix(autoscaling): can't use `MathExpression` in `scaleOnMetric`
  packages/@aws-cdk/aws-applicationautoscaling/lib/step-scaling-policy.ts
  packages/@aws-cdk/aws-applicationautoscaling/test/test.scalable-target.ts
  packages/@aws-cdk/aws-autoscaling/lib/step-scaling-policy.ts
  packages/@aws-cdk/aws-autoscaling/test/test.auto-scaling-group.ts
  packages/@aws-cdk/aws-cloudwatch/lib/metric.ts
Labels: contribution/core

#5816 feat(apigatewayv2): fork APIGatewayV2 into its own package
  packages/@aws-cdk/aws-apigateway/README.md
  packages/@aws-cdk/aws-apigateway/lib/apigatewayv2.ts
  packages/@aws-cdk/aws-apigateway/lib/index.ts
  packages/@aws-cdk/aws-apigateway/package.json
  packages/@aws-cdk/aws-apigatewayv2/.gitignore
  packages/@aws-cdk/aws-apigatewayv2/.npmignore
  packages/@aws-cdk/aws-apigatewayv2/LICENSE
  packages/@aws-cdk/aws-apigatewayv2/NOTICE
  packages/@aws-cdk/aws-apigatewayv2/README.md
  packages/@aws-cdk/aws-apigatewayv2/lib/index.ts
  packages/@aws-cdk/aws-apigatewayv2/package.json
  packages/@aws-cdk/aws-apigatewayv2/test/apigatewayv2.test.ts
  packages/decdk/package.json
Labels: contribution/core, pr-status/do-not-merge

#5838 fix(apigateway): LambdaRestApi fails when a user defined Stage is attached
  packages/@aws-cdk/aws-apigateway/lib/integrations/lambda.ts
  packages/@aws-cdk/aws-apigateway/test/integ.lambda-api.latebound-deploymentstage.expected.json
  packages/@aws-cdk/aws-apigateway/test/integ.lambda-api.latebound-deploymentstage.ts
Labels: contribution/core

#5848 chore(mergify): missing team members from mergify config
  .mergify.yml
Labels: contribution/core

#5869 docs(core): fix CfnOutput example in README
  packages/@aws-cdk/core/README.md
Labels: contribution/core

#5882 feat(cloudformation): upgrade the CloudFormation resource specification to v10.3.0
  packages/@aws-cdk/cfnspec/CHANGELOG.md
  packages/@aws-cdk/cfnspec/spec-source/000_CloudFormationResourceSpecification.json
Labels: contribution/core

#5876 fix(lambda): setting log retention to INFINITE causes failure
  packages/@aws-cdk/aws-lambda/lib/function.ts
  packages/@aws-cdk/aws-lambda/lib/log-retention.ts
  packages/@aws-cdk/aws-lambda/test/test.log-retention.ts
Labels: contribution/core

#5822 chore: codeowners references individuals rather than team for ECS
  .github/CODEOWNERS
Labels: contribution/core

#5908 fix(autoscaling): can't use block devices
  packages/@aws-cdk/assert/README.md
  packages/@aws-cdk/assert/lib/assertions/have-resource.ts
  packages/@aws-cdk/assert/test/have-resource.test.ts
  packages/@aws-cdk/aws-autoscaling/lib/auto-scaling-group.ts
  packages/@aws-cdk/aws-autoscaling/test/test.auto-scaling-group.ts
  packages/@aws-cdk/aws-lambda/test/test.log-retention.ts
Labels: contribution/core

#5919 feat: bump JSII to version 0.21.2
  package.json
  packages/cdk-dasm/package.json
  packages/decdk/package.json
  tools/awslint/package.json
  tools/cdk-build-tools/package.json
  tools/cfn2ts/package.json
  yarn.lock
Labels: contribution/core

#4053 rfc: tree.json
  design/construct-tree.md
Labels: contribution/core, management/rfc, pr-status/do-not-merge

#5878 feat(lambda): avail function log group in the CDK
  packages/@aws-cdk/aws-lambda/README.md
  packages/@aws-cdk/aws-lambda/lib/function.ts
  packages/@aws-cdk/aws-lambda/lib/log-retention-provider/index.ts
  packages/@aws-cdk/aws-lambda/lib/log-retention.ts
  packages/@aws-cdk/aws-lambda/test/integ.log-retention.expected.json
  packages/@aws-cdk/aws-lambda/test/test.function.ts
  packages/@aws-cdk/aws-lambda/test/test.log-retention-provider.ts
  packages/@aws-cdk/aws-lambda/test/test.log-retention.ts
  packages/@aws-cdk/aws-rds/test/integ.instance.lit.expected.json
Labels: contribution/core

#3437 RFC: 0049 Continuous Delivery for CDK Apps
  design/cdk-assets.md
  design/continuous-delivery.md
Labels: contribution/core, management/rfc, pr-status/do-not-merge

#5966 chore: redirect RFCs from "design"
  design/cdk-assets.md
  design/continuous-delivery.md
  design/feature-flags.md
Labels: contribution/core

#5973 fix(cognito): standard attr timezone unexpectedly creates custom attr
  packages/@aws-cdk/aws-cognito/lib/user-pool.ts
Labels: contribution/core

#5982 feat(cloudformation): update Resource Specification to v10.4.0
  packages/@aws-cdk/aws-acmpca/.gitignore
  packages/@aws-cdk/aws-acmpca/.npmignore
  packages/@aws-cdk/aws-acmpca/LICENSE
  packages/@aws-cdk/aws-acmpca/NOTICE
  packages/@aws-cdk/aws-acmpca/README.md
  packages/@aws-cdk/aws-acmpca/lib/index.ts
  packages/@aws-cdk/aws-acmpca/package.json
  packages/@aws-cdk/aws-acmpca/test/acmpca.test.ts
  packages/@aws-cdk/cfnspec/CHANGELOG.md
  packages/@aws-cdk/cfnspec/spec-source/000_CloudFormationResourceSpecification.json
  packages/decdk/package.json
Labels: contribution/core

#5250 fix(cli): colored text is unreadable when using light themes
  packages/aws-cdk/lib/logging.ts
Labels: pr-status/do-not-merge

#5857 chore: validate mandatory changes in pr with github actions
  .github/actions/prlinter/LICENSE
  .github/actions/prlinter/NOTICE
  .github/actions/prlinter/action.yml
  .github/actions/prlinter/index.js
  .github/actions/prlinter/package-lock.json
  .github/actions/prlinter/package.json
  .github/workflows/pr-linter.yml
  .mergify.yml
  tools/prlint/LICENSE
  tools/prlint/NOTICE
  tools/prlint/README.md
  tools/prlint/index.js
  tools/prlint/package-lock.json
  tools/prlint/package.json
Labels: contribution/core

#5995 chore(ssm): clear out awslint exclusions
  packages/@aws-cdk/aws-ssm/lib/parameter.ts
  packages/@aws-cdk/aws-ssm/package.json
Labels: contribution/core

#5457 feat(ecs): Firelens log driver support
  packages/@aws-cdk/aws-ecs/README.md
  packages/@aws-cdk/aws-ecs/lib/base/task-definition.ts
  packages/@aws-cdk/aws-ecs/lib/container-definition.ts
  packages/@aws-cdk/aws-ecs/lib/firelens-log-router.ts
  packages/@aws-cdk/aws-ecs/lib/index.ts
  packages/@aws-cdk/aws-ecs/lib/log-drivers/firelens-log-driver.ts
  packages/@aws-cdk/aws-ecs/lib/log-drivers/log-driver.ts
  packages/@aws-cdk/aws-ecs/lib/log-drivers/log-drivers.ts
  packages/@aws-cdk/aws-ecs/package.json
  packages/@aws-cdk/aws-ecs/test/ec2/firelens.conf
  packages/@aws-cdk/aws-ecs/test/ec2/integ.firelens-s3-config.expected.json
  packages/@aws-cdk/aws-ecs/test/ec2/integ.firelens-s3-config.ts
  packages/@aws-cdk/aws-ecs/test/fargate/integ.firelens-cloudwatch.expected.json
  packages/@aws-cdk/aws-ecs/test/fargate/integ.firelens-cloudwatch.ts
  packages/@aws-cdk/aws-ecs/test/test.firelens-log-driver.ts
Labels: package/ecs

#5996 chore(lambda): documentation for SingletonLambda in the README
  packages/@aws-cdk/aws-lambda/README.md
  packages/@aws-cdk/aws-lambda/lib/singleton-lambda.ts
Labels: contribution/core

#6014 chore: add integ tests section to CONTRIBUTING.md
  CONTRIBUTING.md
  packages/@aws-cdk/aws-apigateway/test/authorizers/integ.token-authorizer-iam-role.ts
  packages/@aws-cdk/aws-apigateway/test/authorizers/integ.token-authorizer.ts
  packages/@aws-cdk/aws-lambda-destinations/test/integ.destinations.ts
Labels: contribution/core
