Repository aws/aws-cdk, pull requests merged in 2020-04, with the labels that each got.

#7024 feat(lambda): ruby 2.7 runtime
  packages/@aws-cdk/aws-lambda/lib/runtime.ts
  packages/@aws-cdk/aws-lambda/package.json
Labels: pr-linter/exempt-readme, pr-linter/exempt-test

#7075 fix(dynamodb): cannot use attribute as key in a GSI, non-key in another
  packages/@aws-cdk/aws-dynamodb/lib/table.ts
  packages/@aws-cdk/aws-dynamodb/package.json
  packages/@aws-cdk/aws-dynamodb/test/dynamodb.test.ts
  packages/@aws-cdk/aws-dynamodb/test/integ.dynamodb.mixed-key-gsi.expected.json
  packages/@aws-cdk/aws-dynamodb/test/integ.dynamodb.mixed-key-gsi.ts
  packages/@aws-cdk/aws-dynamodb/test/replica-provider.test.ts
  packages/@aws-cdk/aws-dynamodb/test/test.dynamodb.ts
  packages/@aws-cdk/aws-dynamodb/test/test.replica-provider.ts
Labels: bug, contribution/core, effort/small

#7020 feat(cli): write stack outputs to a file
  packages/aws-cdk/README.md
  packages/aws-cdk/bin/cdk.ts
  packages/aws-cdk/lib/cdk-toolkit.ts
  packages/aws-cdk/test/integ/cli/app/app.js
  packages/aws-cdk/test/integ/cli/cdk-deploy-wildcard-with-outputs-expected.json
  packages/aws-cdk/test/integ/cli/cdk-deploy-with-outputs-expected.json
  packages/aws-cdk/test/integ/cli/common.bash
  packages/aws-cdk/test/integ/cli/test-cdk-deploy-wildcard-with-outputs.sh
  packages/aws-cdk/test/integ/cli/test-cdk-deploy-with-outputs.sh
  packages/aws-cdk/test/integ/cli/test-cdk-ls.sh
Labels: contribution/core

#7102 feat(kinesis): streams are encrypted by default
  packages/@aws-cdk/aws-kinesis/README.md
  packages/@aws-cdk/aws-kinesis/lib/stream.ts
  packages/@aws-cdk/aws-kinesis/test/test.stream.ts
  packages/@aws-cdk/aws-lambda-event-sources/test/integ.kinesis.expected.json
  packages/@aws-cdk/aws-lambda-event-sources/test/integ.kinesiswithdlq.expected.json
Labels: contribution/core, package/kinesis

#7134 chore(cli): fix integration tests for cdk deploy with outputs
  packages/aws-cdk/test/integ/cli/cdk-deploy-wildcard-with-outputs-expected.json
  packages/aws-cdk/test/integ/cli/cdk-deploy-wildcard-with-outputs-expected.template
  packages/aws-cdk/test/integ/cli/cdk-deploy-with-outputs-expected.json
  packages/aws-cdk/test/integ/cli/cdk-deploy-with-outputs-expected.template
  packages/aws-cdk/test/integ/cli/test-cdk-deploy-wildcard-with-outputs.sh
  packages/aws-cdk/test/integ/cli/test-cdk-deploy-with-outputs.sh
Labels: contribution/core

#7105 feat(lambda): .net core 3.1 runtime
  packages/@aws-cdk/aws-lambda/lib/runtime.ts
Labels: pr-linter/exempt-readme, pr-linter/exempt-test

#7138 chore: missing awaits
  packages/aws-cdk/lib/cdk-toolkit.ts
  packages/aws-cdk/test/api/sdk-provider.test.ts
  packages/aws-cdk/test/cdk-toolkit.test.ts
Labels: contribution/core

#7060 feat(cli): regression tests
  packages/aws-cdk/.gitignore
  packages/aws-cdk/CONTRIBUTING.md
  packages/aws-cdk/package.json
  packages/aws-cdk/scripts/integ-cli-no-regression.sh
  packages/aws-cdk/scripts/integ-cli-regression.sh
  packages/aws-cdk/scripts/integ-cli.sh
  packages/aws-cdk/test/integ/cli.exclusions.js
  packages/aws-cdk/test/integ/cli/common.bash
  packages/aws-cdk/test/integ/cli/test-cdk-deploy-nested-stack-with-parameters.sh
  packages/aws-cdk/test/integ/cli/test-cdk-deploy-wildcard-with-parameters.sh
  packages/aws-cdk/test/integ/cli/test-cdk-deploy-with-parameters.sh
  packages/aws-cdk/test/integ/cli/test.sh
  packages/aws-cdk/test/integ/run-against-dist.bash
  packages/aws-cdk/test/integ/run-wrappers/repo/npm
  packages/aws-cdk/test/integ/test-cli-regression-against-current-code.sh
  packages/aws-cdk/test/integ/test-cli-regression-against-latest-release.sh
  tools/prlint/package.json
Labels: contribution/core, pr-linter/exempt-readme

#7151 chore(cli): resurrect integ test execution
  packages/aws-cdk/test/integ/cli/test.sh
Labels: contribution/core

#7156 docs(core): add incomplete docs link for cfn-resources section
  packages/@aws-cdk/core/README.md
Labels: contribution/core

#7157 chore: remove duplicate 'yarn install'
  buildspec-pr.yaml
  buildspec.yaml
Labels: contribution/core

#7041 refactor(cli): cleanup of CLI code
  packages/aws-cdk/bin/cdk.ts
  packages/aws-cdk/lib/api/aws-auth/account-cache.ts
  packages/aws-cdk/lib/api/aws-auth/sdk-provider.ts
  packages/aws-cdk/lib/api/aws-auth/sdk.ts
  packages/aws-cdk/lib/api/bootstrap-environment.ts
  packages/aws-cdk/lib/api/bootstrap/bootstrap-environment2.ts
  packages/aws-cdk/lib/api/cloudformation-deployments.ts
  packages/aws-cdk/lib/api/cxapp/cloud-assembly.ts
  packages/aws-cdk/lib/api/cxapp/cloud-executable.ts
  packages/aws-cdk/lib/api/cxapp/environments.ts
  packages/aws-cdk/lib/api/cxapp/stacks.ts
  packages/aws-cdk/lib/api/deploy-stack.ts
  packages/aws-cdk/lib/api/deployment-target.ts
  packages/aws-cdk/lib/api/toolkit-info.ts
  packages/aws-cdk/lib/api/util/cloudformation.ts
  packages/aws-cdk/lib/api/util/cloudformation/stack-status.ts
  packages/aws-cdk/lib/assets.ts
  packages/aws-cdk/lib/cdk-toolkit.ts
  packages/aws-cdk/lib/command-api.ts
  packages/aws-cdk/lib/settings.ts
  packages/aws-cdk/lib/util/asset-publishing.ts
  packages/aws-cdk/test/api/bootstrap.test.ts
  packages/aws-cdk/test/api/bootstrap2.test.ts
  packages/aws-cdk/test/api/cloud-assembly.test.ts
  packages/aws-cdk/test/api/cloud-executable.test.ts
  packages/aws-cdk/test/api/deploy-stack.test.ts
  packages/aws-cdk/test/api/stacks.test.ts
  packages/aws-cdk/test/assets.test.ts
  packages/aws-cdk/test/cdk-toolkit.test.ts
  packages/aws-cdk/test/context-providers/amis.test.ts
  packages/aws-cdk/test/context-providers/asymmetric-vpcs.test.ts
  packages/aws-cdk/test/context-providers/generic.test.ts
  packages/aws-cdk/test/context-providers/vpcs.test.ts
  packages/aws-cdk/test/diff.test.ts
  packages/aws-cdk/test/integ/bootstrap/bootstrap.integ-test.ts
  packages/aws-cdk/test/util.ts
  packages/aws-cdk/test/util/cloudformation.test.ts
  packages/aws-cdk/test/util/mock-sdk.ts
Labels: contribution/core

#7159 chore: lock in TypeScript dependency for monocdk
  packages/monocdk-experiment/package.json
Labels: contribution/core

#7162 chore: fix CLI handling of `--no-execute` flag
  packages/aws-cdk/lib/api/util/cloudformation.ts
  packages/aws-cdk/test/api/deploy-stack.test.ts
Labels: contribution/core

#7175 chore(route53): clear doc string linter errors
  packages/@aws-cdk/aws-route53/lib/hosted-zone-provider.ts
  packages/@aws-cdk/aws-route53/lib/hosted-zone.ts
  packages/@aws-cdk/aws-route53/lib/record-set.ts
  packages/@aws-cdk/aws-route53/package.json
Labels: contribution/core, package/route53

#7178 chore: security diff calculation fails for nonexistent stack
  packages/aws-cdk/CONTRIBUTING.md
  packages/aws-cdk/lib/api/util/cloudformation.ts
  packages/aws-cdk/test/util/cloudformation.test.ts
Labels: contribution/core

#7180 chore(cli): exclude regression tests that collide with the normal integ suite
  packages/aws-cdk/test/integ/cli.exclusions.js
Labels: contribution/core

#7182 chore(cli): fix regression tests execution wrapping
  packages/aws-cdk/test/integ/test-cli-regression-against-current-code.sh
Labels: contribution/core

#7183 chore(cli): fix version in exclusions
  packages/aws-cdk/test/integ/cli.exclusions.js
Labels: contribution/core

#7188 fix(ecs): default Service throws in a VPC without private subnets
  packages/@aws-cdk/aws-ecs/lib/base/base-service.ts
  packages/@aws-cdk/aws-ecs/lib/ec2/ec2-service.ts
  packages/@aws-cdk/aws-ecs/lib/fargate/fargate-service.ts
  packages/@aws-cdk/aws-ecs/test/fargate/test.fargate-service.ts
Labels: contribution/core

#7141 feat(cognito): user pool - OAuth2.0 authentication
  packages/@aws-cdk/aws-cognito/README.md
  packages/@aws-cdk/aws-cognito/lib/user-pool-client.ts
  packages/@aws-cdk/aws-cognito/lib/user-pool.ts
  packages/@aws-cdk/aws-cognito/test/integ.user-pool-client-explcit-props.expected.json
  packages/@aws-cdk/aws-cognito/test/integ.user-pool-client-explcit-props.ts
  packages/@aws-cdk/aws-cognito/test/user-pool-client.test.ts
  packages/@aws-cdk/aws-cognito/test/user-pool.test.ts
Labels: contribution/core

#7135 chore(kinesis): some minor cleanup, adding a test
  packages/@aws-cdk/aws-kinesis/lib/stream.ts
  packages/@aws-cdk/aws-kinesis/test/test.stream.ts
Labels: contribution/core, package/kinesis

#7191 fix(events): Batch target does not work
  packages/@aws-cdk/aws-events-targets/lib/batch.ts
  packages/@aws-cdk/aws-events-targets/test/batch/batch.test.ts
  packages/@aws-cdk/aws-events-targets/test/batch/integ.job-definition-events.expected.json
  packages/@aws-cdk/aws-events/lib/rule.ts
Labels: contribution/core

#7192 feat(bootstrap): require `aws:SecureTransport` for staging bucket
  packages/aws-cdk/lib/api/bootstrap-environment.ts
  packages/aws-cdk/lib/api/bootstrap/bootstrap-template.yaml
Labels: contribution/core, pr-linter/exempt-readme, pr-linter/exempt-test

#7185 chore(kinesis): add integ test
  packages/@aws-cdk/aws-kinesis/package.json
  packages/@aws-cdk/aws-kinesis/test/integ.stream.expected.json
  packages/@aws-cdk/aws-kinesis/test/integ.stream.ts
Labels: contribution/core, package/kinesis

#6435 feat(ecs): secret JSON key for environment variables
  packages/@aws-cdk/aws-ecs/README.md
  packages/@aws-cdk/aws-ecs/lib/container-definition.ts
  packages/@aws-cdk/aws-ecs/test/fargate/integ.secret-json-key.expected.json
  packages/@aws-cdk/aws-ecs/test/fargate/integ.secret-json-key.ts
  packages/@aws-cdk/aws-ecs/test/test.container-definition.ts
Labels: package/ecs

#7218 chore(deps): revert bump codemaker from 1.1.0 to 1.2.0
  packages/cdk-dasm/package.json
  tools/cfn2ts/package.json
  yarn.lock
Labels: contribution/core

#7211 chore(deps-dev): revert bump jsii-rosetta from 1.1.0 to 1.2.0
  package.json
  yarn.lock
Labels: contribution/core

#7219 chore(deps): revert bump jsii from 1.1.0 to 1.2.0
  packages/decdk/package.json
  tools/cdk-build-tools/package.json
  yarn.lock
Labels: contribution/core

#7212 chore: configure Dependabot to ignore jsii dependencies updateds
  .dependabot/config.yml
Labels: contribution/core

#7222 chore(cli): add cdk-assets to CLI deps in regression suite
  packages/aws-cdk/test/integ/run-against-dist.bash
Labels: contribution/core

#7223 chore(cli): fix cdk assets dep path
  packages/aws-cdk/test/integ/run-against-dist.bash
Labels: contribution/core

#7227 chore(cli): add cfnspec transitive dep to cli deps
  packages/aws-cdk/test/integ/run-against-dist.bash
Labels: contribution/core

#7229 chore(cli): disable regression tests
  packages/aws-cdk/test/integ/test-cli-regression-against-current-code.sh
  packages/aws-cdk/test/integ/test-cli-regression-against-latest-release.sh
Labels: contribution/core

#7241 chore: merge release/1.32.0 to master
  CHANGELOG.md
  lerna.json
  packages/aws-cdk/test/integ/run-against-dist.bash
  packages/aws-cdk/test/integ/test-cli-regression-against-current-code.sh
  packages/aws-cdk/test/integ/test-cli-regression-against-latest-release.sh
Labels: contribution/core, pr/no-squash

#6141 feat(kinesis): `grantRead` now allows the `ListShards` action and `grant` is now public
  packages/@aws-cdk/aws-kinesis/README.md
  packages/@aws-cdk/aws-kinesis/lib/stream.ts
  packages/@aws-cdk/aws-kinesis/test/integ.stream.expected.json
  packages/@aws-cdk/aws-kinesis/test/test.stream.ts
  packages/@aws-cdk/aws-lambda-event-sources/test/integ.kinesis.expected.json
  packages/@aws-cdk/aws-lambda-event-sources/test/integ.kinesiswithdlq.expected.json
  packages/@aws-cdk/aws-lambda-event-sources/test/test.kinesis.ts
  packages/@aws-cdk/aws-logs-destinations/test/kinesis.test.ts
Labels: package/kinesis

#7269 chore(kinesis): remove outdated comments
  packages/@aws-cdk/aws-kinesis/lib/stream.ts
Labels: contribution/core, package/kinesis

#7270 fix: new IAM Condition type is unusable in Java
  allowed-breaking-changes.txt
  packages/@aws-cdk/aws-iam/lib/policy-statement.ts
Labels: contribution/core

#7275 chore(changelog): fix changelog corruption
  CHANGELOG.md
Labels: contribution/core

#7274 chore(release): 1.32.1
  CHANGELOG.md
  allowed-breaking-changes.txt
  lerna.json
  packages/@aws-cdk/aws-iam/lib/policy-statement.ts
Labels: contribution/core, pr/no-squash

#7249 fix(cli): --app command does not work when executing a command without arguments
  packages/aws-cdk/lib/api/cxapp/exec.ts
  packages/aws-cdk/test/api/exec.test.ts
  packages/aws-cdk/test/bockfs.ts
  packages/aws-cdk/test/util.ts
  packages/aws-cdk/test/util/mock-child_process.ts
Labels: contribution/core, package/tools

#7287 chore(iam): clear docs linter exclusions
  packages/@aws-cdk/aws-iam/lib/grant.ts
  packages/@aws-cdk/aws-iam/lib/group.ts
  packages/@aws-cdk/aws-iam/lib/lazy-role.ts
  packages/@aws-cdk/aws-iam/lib/managed-policy.ts
  packages/@aws-cdk/aws-iam/lib/policy-document.ts
  packages/@aws-cdk/aws-iam/lib/policy-statement.ts
  packages/@aws-cdk/aws-iam/lib/policy.ts
  packages/@aws-cdk/aws-iam/lib/principals.ts
  packages/@aws-cdk/aws-iam/lib/role.ts
  packages/@aws-cdk/aws-iam/lib/user.ts
  packages/@aws-cdk/aws-iam/package.json
  packages/@aws-cdk/aws-iam/test/policy-document.test.ts
Labels: contribution/core, package/iam

#7292 fix(cli): profile AssumeRole credentials don't work via proxy
  packages/aws-cdk/lib/api/aws-auth/awscli-compatible.ts
  packages/aws-cdk/lib/api/aws-auth/sdk-provider.ts
  packages/aws-cdk/test/api/sdk-provider.test.ts
  packages/aws-cdk/test/util/mock-sdk.ts
Labels: contribution/core

#7293 chore: update minimum Node version to 10.12 when creating missing libraries
  CONTRIBUTING.md
  README.md
  packages/@aws-cdk/cfnspec/build-tools/create-missing-libraries.ts
  packages/monocdk-experiment/package.json
  tools/awslint/package.json
Labels: contribution/core

#7294 chore(release): 1.32.2
  CHANGELOG.md
  lerna.json
  packages/aws-cdk/lib/api/aws-auth/awscli-compatible.ts
  packages/aws-cdk/lib/api/aws-auth/sdk-provider.ts
  packages/aws-cdk/test/api/sdk-provider.test.ts
  packages/aws-cdk/test/util/mock-sdk.ts
Labels: contribution/core, pr/no-squash

#7299 chore: Update PR template to match Mergify bugfix
  .github/PULL_REQUEST_TEMPLATE.md
Labels: contribution/core

#7301 chore(bockfs): initialize bockfs root with unique temp directory
  packages/aws-cdk/test/bockfs.ts
Labels: contribution/core

#7302 fix(eks): missing permissions to add and remove tags for clusters
  packages/@aws-cdk/aws-eks/lib/cluster-resource.ts
  packages/@aws-cdk/aws-eks/test/integ.eks-cluster.expected.json
  packages/@aws-cdk/aws-eks/test/test.cluster.ts
Labels: contribution/core, package/eks

#7308 chore(lambda): fix misleading reference to "codeHash" in readme
  packages/@aws-cdk/aws-lambda/README.md
Labels: contribution/core

#7321 chore(cloudwatch): clear docs linter errors
  packages/@aws-cdk/aws-cloudwatch/lib/alarm-action.ts
  packages/@aws-cdk/aws-cloudwatch/lib/alarm.ts
  packages/@aws-cdk/aws-cloudwatch/lib/dashboard.ts
  packages/@aws-cdk/aws-cloudwatch/lib/graph.ts
  packages/@aws-cdk/aws-cloudwatch/lib/metric-types.ts
  packages/@aws-cdk/aws-cloudwatch/package.json
Labels: contribution/core, package/cloudwatch

#7325 chore(kms): clear docs linter errors
  packages/@aws-cdk/aws-kms/lib/alias.ts
  packages/@aws-cdk/aws-kms/package.json
Labels: contribution/core, package/kms

#7314 chore(kinesis): convert tests to jest
  packages/@aws-cdk/aws-kinesis/package.json
  packages/@aws-cdk/aws-kinesis/test/stream.test.ts
  packages/@aws-cdk/aws-kinesis/test/test.stream.ts
Labels: contribution/core, package/kinesis

#7322 fix(eks): unable to create KubernetesResources in another stack
  packages/@aws-cdk/aws-eks/lib/cluster.ts
  packages/@aws-cdk/aws-eks/lib/helm-chart.ts
  packages/@aws-cdk/aws-eks/lib/k8s-patch.ts
  packages/@aws-cdk/aws-eks/lib/k8s-resource.ts
  packages/@aws-cdk/aws-eks/lib/kubectl-provider.ts
  packages/@aws-cdk/aws-eks/test/test.cluster.ts
Labels: contribution/core

#7334 chore: unify Jest versions to 25.x
  packages/@aws-cdk/aws-certificatemanager/lambda-packages/dns_validated_certificate_handler/package.json
  packages/@aws-cdk/aws-dynamodb-global/lambda-packages/aws-global-table-coordinator/package.json
  packages/aws-cdk/lib/init-templates/app/javascript/package.template.json
  packages/aws-cdk/lib/init-templates/app/typescript/package.template.json
  packages/aws-cdk/lib/init-templates/lib/typescript/package.template.json
  packages/aws-cdk/lib/init-templates/sample-app/javascript/package.template.json
  packages/aws-cdk/lib/init-templates/sample-app/typescript/package.template.json
Labels: contribution/core

#7338 chore(events): clear docs linter violations
  packages/@aws-cdk/aws-events/lib/input.ts
  packages/@aws-cdk/aws-events/lib/rule-ref.ts
  packages/@aws-cdk/aws-events/lib/rule.ts
  packages/@aws-cdk/aws-events/package.json
Labels: contribution/core, package/events

#7195 chore: correct regex in align-version script
  scripts/align-version.sh
Labels: review/small

#7139 chore: shrinkwrap CLI and cdk-assets tools
  packages/aws-cdk/.gitignore
  packages/aws-cdk/package.json
  packages/cdk-assets/.gitignore
  packages/cdk-assets/package.json
  scripts/align-version.sh
  tools/cdk-build-tools/bin/cdk-package.ts
  tools/cdk-build-tools/package.json
  tools/yarn-cling/.gitignore
  tools/yarn-cling/.npmignore
  tools/yarn-cling/LICENSE
  tools/yarn-cling/NOTICE
  tools/yarn-cling/README.md
  tools/yarn-cling/bin/yarn-cling
  tools/yarn-cling/bin/yarn-cling.ts
  tools/yarn-cling/lib/hoisting.ts
  tools/yarn-cling/lib/index.ts
  tools/yarn-cling/lib/types.ts
  tools/yarn-cling/package.json
  tools/yarn-cling/test/cling.test.ts
  tools/yarn-cling/test/hoisting.test.ts
  tools/yarn-cling/test/test-fixture/.gitignore
  tools/yarn-cling/test/test-fixture/package1/node_modules/package2
  tools/yarn-cling/test/test-fixture/package1/node_modules/registrydependency1/package.json
  tools/yarn-cling/test/test-fixture/package1/node_modules/registrydependency2/package.json
  tools/yarn-cling/test/test-fixture/package1/package.json
  tools/yarn-cling/test/test-fixture/package2/package.json
  tools/yarn-cling/test/test-fixture/yarn.lock
  tools/yarn-cling/tsconfig.json
  yarn.lock
Labels: contribution/core

#7343 chore: recreate symlink on build
  tools/yarn-cling/package.json
Labels: contribution/core

#7348 revert: "shrinkwrap CLI and cdk-assets tool"
  packages/aws-cdk/.gitignore
  packages/aws-cdk/package.json
  packages/cdk-assets/.gitignore
  packages/cdk-assets/package.json
  scripts/align-version.sh
  tools/cdk-build-tools/bin/cdk-package.ts
  tools/cdk-build-tools/package.json
  tools/yarn-cling/.gitignore
  tools/yarn-cling/.npmignore
  tools/yarn-cling/LICENSE
  tools/yarn-cling/NOTICE
  tools/yarn-cling/README.md
  tools/yarn-cling/bin/yarn-cling
  tools/yarn-cling/bin/yarn-cling.ts
  tools/yarn-cling/lib/hoisting.ts
  tools/yarn-cling/lib/index.ts
  tools/yarn-cling/lib/types.ts
  tools/yarn-cling/package.json
  tools/yarn-cling/test/cling.test.ts
  tools/yarn-cling/test/hoisting.test.ts
  tools/yarn-cling/test/test-fixture/.gitignore
  tools/yarn-cling/test/test-fixture/package1/node_modules/package2
  tools/yarn-cling/test/test-fixture/package1/node_modules/registrydependency1/package.json
  tools/yarn-cling/test/test-fixture/package1/node_modules/registrydependency2/package.json
  tools/yarn-cling/test/test-fixture/package1/package.json
  tools/yarn-cling/test/test-fixture/package2/package.json
  tools/yarn-cling/test/test-fixture/yarn.lock
  tools/yarn-cling/tsconfig.json
  yarn.lock
Labels: contribution/core

#7354 feat(kinesis): add `grant` API to IStream to add permissions to a Stream
  packages/@aws-cdk/aws-kinesis/README.md
  packages/@aws-cdk/aws-kinesis/lib/stream.ts
  packages/@aws-cdk/aws-kinesis/test/integ.stream.expected.json
  packages/@aws-cdk/aws-kinesis/test/stream.test.ts
  packages/@aws-cdk/aws-lambda-event-sources/lib/kinesis.ts
  packages/@aws-cdk/aws-lambda-event-sources/test/integ.kinesis.expected.json
  packages/@aws-cdk/aws-lambda-event-sources/test/integ.kinesiswithdlq.expected.json
  packages/@aws-cdk/aws-lambda-event-sources/test/test.kinesis.ts
Labels: contribution/core, package/kinesis

#7351 chore(stepfunctions): convert tests to jest
  packages/@aws-cdk/aws-stepfunctions/package.json
  packages/@aws-cdk/aws-stepfunctions/test/activity.test.ts
  packages/@aws-cdk/aws-stepfunctions/test/condition.test.ts
  packages/@aws-cdk/aws-stepfunctions/test/fail.test.ts
  packages/@aws-cdk/aws-stepfunctions/test/fields.test.ts
  packages/@aws-cdk/aws-stepfunctions/test/map.test.ts
  packages/@aws-cdk/aws-stepfunctions/test/parallel.test.ts
  packages/@aws-cdk/aws-stepfunctions/test/pass.test.ts
  packages/@aws-cdk/aws-stepfunctions/test/state-machine-resources.test.ts
  packages/@aws-cdk/aws-stepfunctions/test/state-machine.test.ts
  packages/@aws-cdk/aws-stepfunctions/test/states-language.test.ts
  packages/@aws-cdk/aws-stepfunctions/test/test.condition.ts
  packages/@aws-cdk/aws-stepfunctions/test/test.fields.ts
  packages/@aws-cdk/aws-stepfunctions/test/test.pass.ts
  packages/@aws-cdk/aws-stepfunctions/test/test.states-language.ts
Labels: contribution/core, package/stepfunctions

#7226 fix(cli): parameter values with multiple `=` symbols get truncated
  packages/aws-cdk/bin/cdk.ts
  packages/aws-cdk/test/api/deploy-stack.test.ts
  packages/aws-cdk/test/integ/cli/app/app.js
  packages/aws-cdk/test/integ/cli/common.bash
  packages/aws-cdk/test/integ/cli/test-cdk-deploy-with-parameters-multi.sh
Labels: package/tools

#7374 chore(cli): fix deploy with parameters integ test
  packages/aws-cdk/test/integ/cli/app/app.js
  packages/aws-cdk/test/integ/cli/test-cdk-deploy-with-parameters-multi.sh
Labels: contribution/core, package/tools

#7376 chore(cli): fix wildcard deploy with parameters integ test
  packages/aws-cdk/test/integ/cli/test-cdk-deploy-wildcard-with-parameters.sh
Labels: contribution/core, package/tools

#7378 chore(cli): make cli integ tests executable locally
  packages/aws-cdk/scripts/integ-cli.sh
  packages/aws-cdk/test/integ/cli/test-cdk-ls.sh
Labels: contribution/core, package/tools

#7349 feat(kinesis): the `aws-kinesis` module is now stable
  packages/@aws-cdk/aws-kinesis/README.md
  packages/@aws-cdk/aws-kinesis/package.json
Labels: contribution/core, package/kinesis, pr-linter/exempt-test

#7187 fix(core): unable to reference resources across multiple nested stacks
  packages/@aws-cdk/aws-cloudformation/lib/nested-stack.ts
  packages/@aws-cdk/aws-cloudformation/test/integ.nested-stack.expected.json
  packages/@aws-cdk/aws-cloudformation/test/integ.nested-stacks-multi-refs.expected.json
  packages/@aws-cdk/aws-cloudformation/test/integ.nested-stacks-multi-refs.ts
  packages/@aws-cdk/aws-cloudformation/test/integ.nested-stacks-nested-export-to-sibling.expected.json
  packages/@aws-cdk/aws-cloudformation/test/integ.nested-stacks-nested-export-to-sibling.ts
  packages/@aws-cdk/aws-cloudformation/test/integ.nested-stacks-refs3.expected.json
  packages/@aws-cdk/aws-cloudformation/test/test.nested-stack.ts
  packages/@aws-cdk/aws-dynamodb/test/integ.global.expected.json
  packages/@aws-cdk/aws-eks/test/integ.eks-cluster.expected.json
  packages/@aws-cdk/core/lib/app.ts
  packages/@aws-cdk/core/lib/deps.ts
  packages/@aws-cdk/core/lib/private/cfn-reference.ts
  packages/@aws-cdk/core/lib/private/prepare-app.ts
  packages/@aws-cdk/core/lib/private/refs.ts
  packages/@aws-cdk/core/lib/stack.ts
  packages/@aws-cdk/core/lib/util.ts
Labels: contribution/core

#7361 chore(custom-resources): remove stepfunctions as a dependency
  packages/@aws-cdk/custom-resources/lib/provider-framework/provider.ts
  packages/@aws-cdk/custom-resources/lib/provider-framework/util.ts
  packages/@aws-cdk/custom-resources/lib/provider-framework/waiter-state-machine.ts
  packages/@aws-cdk/custom-resources/package.json
  packages/@aws-cdk/custom-resources/test/provider-framework/waiter-state-machine.test.ts
Labels: contribution/core

#7386 chore(cfnspec): fix extra newline in stability banner when creating missing libraries
  packages/@aws-cdk/cfnspec/build-tools/create-missing-libraries.ts
Labels: contribution/core, package/tools

#7389 fix(route53-patterns): HttpsRedirect redirects to index.html
  packages/@aws-cdk/aws-route53-patterns/lib/website-redirect.ts
  packages/@aws-cdk/aws-route53-patterns/test/bucket-website-target.test.ts
Labels: package/route53

#7393 chore: upgrade jsii to v1.3.0
  package.json
  packages/decdk/package.json
  tools/awslint/lib/rules/docs.ts
  tools/awslint/lib/rules/exports.ts
  tools/awslint/package.json
  tools/cdk-build-tools/package.json
  yarn.lock
Labels: contribution/core

#7414 chore: merge release/1.33.0 to master
  CHANGELOG.md
  lerna.json
Labels: pr/do-not-merge, pr/no-squash

#7356 chore: update TS and JS init templates to consistently use ES6 imports
  packages/aws-cdk/lib/init-templates/app/javascript/bin/%name%.template.js
  packages/aws-cdk/lib/init-templates/app/javascript/lib/%name%-stack.template.js
  packages/aws-cdk/lib/init-templates/app/javascript/test/%name%.test.template.js
  packages/aws-cdk/lib/init-templates/app/typescript/test/%name%.test.template.ts
  packages/aws-cdk/lib/init-templates/lib/typescript/test/%name%.test.template.ts
  packages/aws-cdk/lib/init-templates/sample-app/javascript/bin/%name%.template.js
  packages/aws-cdk/lib/init-templates/sample-app/javascript/lib/%name%-stack.template.js
  packages/aws-cdk/lib/init-templates/sample-app/javascript/test/%name%.test.template.js
  packages/aws-cdk/lib/init-templates/sample-app/typescript/test/%name%.test.template.ts
Labels: contribution/core

#7420 chore: upgrade jsii-pacmak to 1.3.1
  yarn.lock
Labels: contribution/core

#7267 feat(ecs): add Fargate 1.4.0 support
  packages/@aws-cdk/aws-ecs/lib/fargate/fargate-service.ts
Labels: package/ecs

#7429 fix(stepfunctions-tasks): encryptionKey is Key instead of IKey
  packages/@aws-cdk/aws-stepfunctions-tasks/lib/sagemaker/sagemaker-task-base-types.ts
Labels: contribution/core, package/stepfunctions, pr-linter/exempt-test

#7401 chore: add missing breaking change entry into CHANGELOG for v1.19.0
  CHANGELOG.md
Labels: contribution/core

#7437 chore: patch release v1.33.1
  CHANGELOG.md
  lerna.json
  package.json
  packages/decdk/package.json
  tools/awslint/lib/rules/docs.ts
  tools/awslint/lib/rules/exports.ts
  tools/awslint/package.json
  tools/cdk-build-tools/package.json
  yarn.lock
Labels: contribution/core, pr/no-squash

#7436 fix: jsii version conflict due to upgrade from v1.1.0 to v1.3.0
  package.json
  packages/decdk/package.json
  tools/awslint/lib/rules/docs.ts
  tools/awslint/lib/rules/exports.ts
  tools/awslint/package.json
  tools/cdk-build-tools/package.json
  yarn.lock
Labels: contribution/core

#7440 chore: merge release/1.33.1 to master
  CHANGELOG.md
  lerna.json
  yarn.lock
Labels: contribution/core, pr/no-squash

#7442 chore: revert "Merge branch 'master' into 'release'"
  CHANGELOG.md
  packages/@aws-cdk/aws-cloudfront/package.json
  packages/@aws-cdk/aws-cloudtrail/package.json
  packages/@aws-cdk/aws-codebuild/package.json
  packages/@aws-cdk/aws-codecommit/package.json
  packages/@aws-cdk/aws-codepipeline-actions/package.json
  packages/@aws-cdk/aws-cognito/README.md
  packages/@aws-cdk/aws-cognito/lib/user-pool-attr.ts
  packages/@aws-cdk/aws-cognito/lib/user-pool.ts
  packages/@aws-cdk/aws-cognito/test/user-pool-attr.test.ts
  packages/@aws-cdk/aws-dynamodb/package.json
  packages/@aws-cdk/aws-ecs/lib/fargate/fargate-service.ts
  packages/@aws-cdk/aws-eks/package.json
  packages/@aws-cdk/aws-events-targets/package.json
  packages/@aws-cdk/aws-lambda/package.json
  packages/@aws-cdk/aws-route53/package.json
  packages/@aws-cdk/aws-sqs/package.json
  packages/@aws-cdk/aws-stepfunctions-tasks/lib/sagemaker/sagemaker-task-base-types.ts
  packages/@aws-cdk/core/package.json
  packages/@aws-cdk/custom-resources/package.json
  packages/aws-cdk/lib/init-templates/app/javascript/bin/%name%.template.js
  packages/aws-cdk/lib/init-templates/app/javascript/lib/%name%-stack.template.js
  packages/aws-cdk/lib/init-templates/app/javascript/test/%name%.test.template.js
  packages/aws-cdk/lib/init-templates/app/typescript/test/%name%.test.template.ts
  packages/aws-cdk/lib/init-templates/lib/typescript/test/%name%.test.template.ts
  packages/aws-cdk/lib/init-templates/sample-app/javascript/bin/%name%.template.js
  packages/aws-cdk/lib/init-templates/sample-app/javascript/lib/%name%-stack.template.js
  packages/aws-cdk/lib/init-templates/sample-app/javascript/test/%name%.test.template.js
  packages/aws-cdk/lib/init-templates/sample-app/typescript/test/%name%.test.template.ts
  packages/aws-cdk/package.json
  packages/cdk-assets/package.json
  yarn.lock
Labels: contribution/core

#7443 chore: revert and lock 'semver' package version to 7.2.2
  packages/@aws-cdk/cdk-assets-schema/package.json
  packages/@aws-cdk/cloud-assembly-schema/package.json
  packages/@aws-cdk/cx-api/package.json
  packages/aws-cdk/package.json
  tools/pkglint/package.json
  yarn.lock
Labels: contribution/core

#7446 chore: merge release/1.33.1 to master
  packages/@aws-cdk/cdk-assets-schema/package.json
  packages/@aws-cdk/cloud-assembly-schema/package.json
  packages/@aws-cdk/cx-api/package.json
  packages/aws-cdk/package.json
  tools/pkglint/package.json
  yarn.lock
Labels: contribution/core, pr/do-not-merge, pr/no-squash

#7404 fix(monocdk): assert package has incorrect imports
  packages/@monocdk-experiment/assert/clone.sh
  packages/@monocdk-experiment/assert/tsconfig.json
Labels: bug, contribution/core, pr-linter/exempt-test

#6934 docs(ecs-patterns): show health check customization in README
  packages/@aws-cdk/aws-ecs-patterns/README.md
Labels: package/ecs-patterns

#7468 chore: pin 'semver' to version 7.2.2 and turn off Dependabot updates
  .dependabot/config.yml
  packages/@aws-cdk/cdk-assets-schema/package.json
  packages/@aws-cdk/cloud-assembly-schema/package.json
  packages/@aws-cdk/cx-api/package.json
  packages/aws-cdk/package.json
  tools/pkglint/package.json
  yarn.lock
Labels: contribution/core

#7458 fix(glue): DataFormat constants are not visible in non-JS languages
  packages/@aws-cdk/aws-glue/lib/data-format.ts
  packages/@aws-cdk/aws-glue/test/integ.table.ts
  packages/@aws-cdk/aws-glue/test/test.table.ts
Labels: contribution/core

#7474 chore(apigateway): clean up README
  packages/@aws-cdk/aws-apigateway/README.md
Labels: contribution/core

#7478 chore(glue): README fixes + breaking changes notice
  packages/@aws-cdk/aws-glue/README.md
Labels: contribution/core

#7383 fix(cloudwatch): can't override Alarm statistic with percentile
  packages/@aws-cdk/aws-cloudwatch/lib/alarm.ts
  packages/@aws-cdk/aws-cloudwatch/test/test.alarm.ts
Labels: contribution/core

#7480 chore(config): added notice of initial setup for config
  packages/@aws-cdk/aws-config/README.md
Labels: contribution/core

#7487 chore: merge release/1.34.0 to master
  CHANGELOG.md
  lerna.json
Labels: contribution/core, pr/no-squash

#7495 fix(cli): Javascript init-templates cannot be synthesized
  packages/aws-cdk/lib/init-templates/app/javascript/bin/%name%.template.js
  packages/aws-cdk/lib/init-templates/app/javascript/lib/%name%-stack.template.js
  packages/aws-cdk/lib/init-templates/app/javascript/test/%name%.test.template.js
  packages/aws-cdk/lib/init-templates/sample-app/javascript/bin/%name%.template.js
  packages/aws-cdk/lib/init-templates/sample-app/javascript/lib/%name%-stack.template.js
  packages/aws-cdk/lib/init-templates/sample-app/javascript/test/%name%.test.template.js
Labels: contribution/core

#7498 chore(release): 1.34.1
  CHANGELOG.md
  lerna.json
  packages/aws-cdk/lib/init-templates/app/javascript/bin/%name%.template.js
  packages/aws-cdk/lib/init-templates/app/javascript/lib/%name%-stack.template.js
  packages/aws-cdk/lib/init-templates/app/javascript/test/%name%.test.template.js
  packages/aws-cdk/lib/init-templates/sample-app/javascript/bin/%name%.template.js
  packages/aws-cdk/lib/init-templates/sample-app/javascript/lib/%name%-stack.template.js
  packages/aws-cdk/lib/init-templates/sample-app/javascript/test/%name%.test.template.js
Labels: contribution/core, pr/no-squash

#7224 feat(cognito): user pool domain
  packages/@aws-cdk/aws-cognito/README.md
  packages/@aws-cdk/aws-cognito/lib/index.ts
  packages/@aws-cdk/aws-cognito/lib/user-pool-client.ts
  packages/@aws-cdk/aws-cognito/lib/user-pool-domain.ts
  packages/@aws-cdk/aws-cognito/lib/user-pool.ts
  packages/@aws-cdk/aws-cognito/package.json
  packages/@aws-cdk/aws-cognito/test/integ.user-pool-client-explicit-props.expected.json
  packages/@aws-cdk/aws-cognito/test/integ.user-pool-client-explicit-props.ts
  packages/@aws-cdk/aws-cognito/test/integ.user-pool-domain-cfdist.expected.json
  packages/@aws-cdk/aws-cognito/test/integ.user-pool-domain-cfdist.ts
  packages/@aws-cdk/aws-cognito/test/integ.user-pool-explicit-props.expected.json
  packages/@aws-cdk/aws-cognito/test/integ.user-pool-explicit-props.ts
  packages/@aws-cdk/aws-cognito/test/user-pool-domain.test.ts
  packages/@aws-cdk/aws-route53-targets/README.md
  packages/@aws-cdk/aws-route53-targets/lib/cloudfront-target.ts
  packages/@aws-cdk/aws-route53-targets/lib/index.ts
  packages/@aws-cdk/aws-route53-targets/lib/userpool-domain.ts
  packages/@aws-cdk/aws-route53-targets/package.json
  packages/@aws-cdk/aws-route53-targets/test/userpool-domain.test.ts
Labels: contribution/core

#7489 chore(route53-patterns): clear linter exclusions
  packages/@aws-cdk/aws-route53-patterns/lib/website-redirect.ts
  packages/@aws-cdk/aws-route53-patterns/package.json
Labels: contribution/core, package/route53

#7358 chore: shrinkwrap CLI and cdk-assets tools
  packages/@aws-cdk/custom-resources/package.json
  packages/aws-cdk/.gitignore
  packages/aws-cdk/package.json
  packages/aws-cdk/test/integ/init/test-typescript.sh
  packages/aws-cdk/test/integ/run-against-dist.bash
  packages/cdk-assets/.gitignore
  packages/cdk-assets/package.json
  scripts/align-version.sh
  tools/cdk-build-tools/bin/cdk-package.ts
  tools/cdk-build-tools/package.json
  tools/yarn-cling/.gitignore
  tools/yarn-cling/.npmignore
  tools/yarn-cling/LICENSE
  tools/yarn-cling/NOTICE
  tools/yarn-cling/README.md
  tools/yarn-cling/bin/yarn-cling
  tools/yarn-cling/bin/yarn-cling.ts
  tools/yarn-cling/lib/hoisting.ts
  tools/yarn-cling/lib/index.ts
  tools/yarn-cling/lib/types.ts
  tools/yarn-cling/package.json
  tools/yarn-cling/test/cling.test.ts
  tools/yarn-cling/test/hoisting.test.ts
  tools/yarn-cling/test/test-fixture/.gitignore
  tools/yarn-cling/test/test-fixture/package1/node_modules/package2
  tools/yarn-cling/test/test-fixture/package1/node_modules/registrydependency1/package.json
  tools/yarn-cling/test/test-fixture/package1/node_modules/registrydependency2/package.json
  tools/yarn-cling/test/test-fixture/package1/package.json
  tools/yarn-cling/test/test-fixture/package2/package.json
  tools/yarn-cling/test/test-fixture/yarn.lock
  tools/yarn-cling/tsconfig.json
  yarn.lock
Labels: contribution/core

#7115 fix(apigateway): changing RestApi policy does not trigger new deployment
  packages/@aws-cdk/aws-apigateway/lib/deployment.ts
  packages/@aws-cdk/aws-apigateway/test/authorizers/integ.request-authorizer.expected.json
  packages/@aws-cdk/aws-apigateway/test/authorizers/integ.token-authorizer-iam-role.expected.json
  packages/@aws-cdk/aws-apigateway/test/authorizers/integ.token-authorizer.expected.json
  packages/@aws-cdk/aws-apigateway/test/integ.cors.expected.json
  packages/@aws-cdk/aws-apigateway/test/integ.lambda-api.latebound-deploymentstage.expected.json
  packages/@aws-cdk/aws-apigateway/test/integ.restapi.books.expected.json
  packages/@aws-cdk/aws-apigateway/test/integ.restapi.defaults.expected.json
  packages/@aws-cdk/aws-apigateway/test/integ.restapi.expected.json
  packages/@aws-cdk/aws-apigateway/test/integ.restapi.multistack.expected.json
  packages/@aws-cdk/aws-apigateway/test/integ.restapi.multiuse.expected.json
  packages/@aws-cdk/aws-apigateway/test/integ.restapi.vpc-endpoint.expected.json
  packages/@aws-cdk/aws-apigateway/test/test.deployment.ts
  packages/@aws-cdk/aws-apigateway/test/test.restapi.ts
  packages/@aws-cdk/aws-apigateway/test/test.stage.ts
  packages/@aws-cdk/aws-route53-targets/test/integ.api-gateway-domain-name.expected.json
  packages/decdk/test/__snapshots__/synth.test.js.snap
Labels: contribution/core

#7525 chore: make `run-against-dist` permanently install Verdaccio tool
  packages/aws-cdk/test/integ/run-against-dist.bash
Labels: contribution/core

#7531 fix(route53): cannot add tags to `HostedZone`
  packages/@aws-cdk/aws-route53/test/test.hosted-zone.ts
  packages/@aws-cdk/cfnspec/lib/schema/property.ts
  packages/@aws-cdk/cfnspec/lib/schema/resource-type.ts
Labels: @aws-cdk/aws-route53, contribution/core

#7549 chore: remove imagebuilder dependency from decdk and monocdk-experiment
  packages/decdk/package.json
  packages/monocdk-experiment/package.json
Labels: contribution/core

#7537 chore(eks): improve bottlerocket disclaimer
  packages/@aws-cdk/aws-eks/README.md
Labels: contribution/core

#7481 chore(efs): drop Efs prefix from all exported types
  packages/@aws-cdk/aws-efs/lib/efs-file-system.ts
  packages/@aws-cdk/aws-efs/package.json
  packages/@aws-cdk/aws-efs/test/efs-file-system.test.ts
Labels: contribution/core

#7556 fix(assets): infrequent "ValidationError: S3 error: Access Denied"
  packages/cdk-assets/lib/private/handlers/files.ts
  packages/cdk-assets/test/files.test.ts
  packages/cdk-assets/test/placeholders.test.ts
  packages/cdk-assets/test/progress.test.ts
  packages/cdk-assets/test/zipping.test.ts
  packages/cdk-assets/tsconfig.json
Labels: bug, contribution/core, effort/small

#7557 chore(cognito): fix erroneous code snippet & improve README on domain
  packages/@aws-cdk/aws-cognito/README.md
Labels: contribution/core

#7520 chore(monocdk): upgrade jsii and generate bindings for monocdk
  package.json
  packages/cdk-dasm/package.json
  packages/decdk/package.json
  packages/monocdk-experiment/.gitignore
  packages/monocdk-experiment/.npmignore
  packages/monocdk-experiment/build.sh
  packages/monocdk-experiment/gen.js
  packages/monocdk-experiment/package.json
  packages/monocdk-experiment/tsconfig.json
  scripts/check-api-compatibility.sh
  tools/awslint/package.json
  tools/cdk-build-tools/package.json
  tools/cfn2ts/package.json
  yarn.lock
Labels: contribution/core, pr-linter/exempt-readme, pr-linter/exempt-test

#7565 chore: don't repack monocdk-experiment
  pack.sh
  packages/monocdk-experiment/.gitignore
  packages/monocdk-experiment/build.sh
  packages/monocdk-experiment/package.json
  scripts/list-packages
Labels: contribution/core

#7453 fix(dynamodb): grantXxx() does not grant in replication regions
  packages/@aws-cdk/aws-dynamodb/lib/table.ts
  packages/@aws-cdk/aws-dynamodb/test/dynamodb.test.ts
Labels: @aws-cdk/aws-dynamodb

#7563 fix(cli): context keys specified in `cdk.json` get moved to `cdk.context.json
  packages/aws-cdk/lib/settings.ts
  packages/aws-cdk/test/context.test.ts
Labels: contribution/core, package/tools

#7526 fix(eks): version update completes prematurely
  packages/@aws-cdk/aws-eks/lib/cluster-resource-handler/cluster.ts
  packages/@aws-cdk/aws-eks/lib/cluster-resource-handler/common.ts
  packages/@aws-cdk/aws-eks/lib/cluster-resource-handler/index.ts
  packages/@aws-cdk/aws-eks/lib/cluster-resource.ts
  packages/@aws-cdk/aws-eks/lib/cluster.ts
  packages/@aws-cdk/aws-eks/test/cluster-resource-handler-mocks.ts
  packages/@aws-cdk/aws-eks/test/integ.eks-cluster.expected.json
  packages/@aws-cdk/aws-eks/test/test.cluster-resource-provider.ts
  packages/@aws-cdk/aws-eks/test/test.cluster.ts
  packages/@aws-cdk/aws-eks/test/test.fargate-resource-provider.ts
  packages/@aws-cdk/custom-resources/README.md
  packages/@aws-cdk/custom-resources/lib/provider-framework/types.d.ts
  packages/@aws-cdk/custom-resources/test/provider-framework/integ.provider.expected.json
  packages/@aws-cdk/custom-resources/test/provider-framework/integration-test-fixtures/s3-assert-handler/index.py
  packages/@aws-cdk/custom-resources/test/provider-framework/runtime.test.ts
Labels: contribution/core

#7428 fix(stepfunctions-tasks): cannot specify part of execution data or task context as input to the `RunLambda` service integration
  packages/@aws-cdk/aws-stepfunctions-tasks/lib/lambda/run-lambda-task.ts
  packages/@aws-cdk/aws-stepfunctions-tasks/test/lambda/integ.invoke-function.ts
  packages/@aws-cdk/aws-stepfunctions-tasks/test/lambda/integ.run-lambda.expected.json
  packages/@aws-cdk/aws-stepfunctions-tasks/test/lambda/integ.run-lambda.ts
  packages/@aws-cdk/aws-stepfunctions-tasks/test/lambda/run-lambda-task.test.ts
  packages/@aws-cdk/aws-stepfunctions/README.md
Labels: @aws-cdk/aws-stepfunctions, contribution/core

#7510 fix(cli): can't bootstrap environment not in app
  packages/@aws-cdk/cx-api/lib/environment.ts
  packages/aws-cdk/bin/cdk.ts
  packages/aws-cdk/lib/api/aws-auth/sdk-provider.ts
  packages/aws-cdk/lib/api/bootstrap-environment.ts
  packages/aws-cdk/lib/api/bootstrap/bootstrap-environment.ts
  packages/aws-cdk/lib/api/bootstrap/bootstrap-environment2.ts
  packages/aws-cdk/lib/api/bootstrap/bootstrap-props.ts
  packages/aws-cdk/lib/api/bootstrap/deploy-bootstrap.ts
  packages/aws-cdk/lib/api/bootstrap/index.ts
  packages/aws-cdk/lib/api/bootstrap/legacy-template.ts
  packages/aws-cdk/lib/api/cloudformation-deployments.ts
  packages/aws-cdk/lib/api/cxapp/environments.ts
  packages/aws-cdk/lib/api/index.ts
  packages/aws-cdk/lib/api/toolkit-info.ts
  packages/aws-cdk/lib/cdk-toolkit.ts
  packages/aws-cdk/lib/context-providers/ami.ts
  packages/aws-cdk/lib/context-providers/availability-zones.ts
  packages/aws-cdk/lib/context-providers/hosted-zones.ts
  packages/aws-cdk/lib/context-providers/ssm-parameters.ts
  packages/aws-cdk/lib/context-providers/vpcs.ts
  packages/aws-cdk/lib/util/asset-publishing.ts
  packages/aws-cdk/test/api/bootstrap.test.ts
  packages/aws-cdk/test/api/bootstrap2.test.ts
  packages/aws-cdk/test/api/sdk-provider.test.ts
  packages/aws-cdk/test/cdk-toolkit.test.ts
  packages/aws-cdk/test/integ/bootstrap/bootstrap.integ-test.ts
  packages/aws-cdk/test/util/mock-sdk.ts
  packages/cdk-assets/bin/cdk-assets.ts
  scripts/buildup
Labels: contribution/core

#7594 chore: merge release/1.34.2 to master
  CHANGELOG.md
  lerna.json
Labels: contribution/core, pr/no-squash

#7596 fix(apigateway): authorizer is not attached to RestApi across projects
  packages/@aws-cdk/aws-apigateway/lib/authorizer.ts
  packages/@aws-cdk/aws-apigateway/lib/method.ts
  packages/@aws-cdk/aws-apigateway/test/test.authorizer.ts
Labels: contribution/core

#7047 chore(dynamodb): do not install aws-sdk in replica handler
  packages/@aws-cdk/aws-dynamodb/lib/replica-handler/index.ts
  packages/@aws-cdk/aws-dynamodb/test/integ.global.expected.json
  packages/@aws-cdk/aws-dynamodb/test/replica-provider.test.ts
Labels: @aws-cdk/aws-dynamodb, review/small

#7628 chore: remove semver exclusion from dependabot updates
  .dependabot/config.yml
Labels: contribution/core

#7583 feat(aws-ecs): add support for IPC and PID Mode with ECS Task Definition
  packages/@aws-cdk/aws-ecs/lib/base/task-definition.ts
  packages/@aws-cdk/aws-ecs/lib/ec2/ec2-task-definition.ts
  packages/@aws-cdk/aws-ecs/test/ec2/integ.app-mesh-proxy-config.expected.json
  packages/@aws-cdk/aws-ecs/test/ec2/integ.app-mesh-proxy-config.ts
  packages/@aws-cdk/aws-ecs/test/ec2/integ.clb-host-nw.expected.json
  packages/@aws-cdk/aws-ecs/test/ec2/integ.clb-host-nw.ts
  packages/@aws-cdk/aws-ecs/test/ec2/test.ec2-task-definition.ts
Labels: @aws-cdk/aws-ecs, feature-request, pr-linter/exempt-readme

#7638 refactor(core): move dependency logic to app and stack tags to synth
  packages/@aws-cdk/core/lib/private/prepare-app.ts
  packages/@aws-cdk/core/lib/stack.ts
  packages/@aws-cdk/core/test/test.stack.ts
Labels: contribution/core

#7631 chore(stepfunctions): add missing predefined error code `States.ParameterPathFailure`
  packages/@aws-cdk/aws-stepfunctions/lib/types.ts
Labels: @aws-cdk/aws-stepfunctions, contribution/core

#7642 chore: merge release/1.36.0 to master
  CHANGELOG.md
  lerna.json
Labels: contribution/core, pr/no-squash

#7538 feat(ecs-patterns): support FargatePlatformVersion as an input property
  packages/@aws-cdk/aws-ecs-patterns/README.md
  packages/@aws-cdk/aws-ecs-patterns/lib/fargate/application-load-balanced-fargate-service.ts
  packages/@aws-cdk/aws-ecs-patterns/lib/fargate/application-multiple-target-groups-fargate-service.ts
  packages/@aws-cdk/aws-ecs-patterns/lib/fargate/network-load-balanced-fargate-service.ts
  packages/@aws-cdk/aws-ecs-patterns/lib/fargate/network-multiple-target-groups-fargate-service.ts
  packages/@aws-cdk/aws-ecs-patterns/lib/fargate/queue-processing-fargate-service.ts
  packages/@aws-cdk/aws-ecs-patterns/test/fargate/test.load-balanced-fargate-service-v2.ts
  packages/@aws-cdk/aws-ecs-patterns/test/fargate/test.load-balanced-fargate-service.ts
  packages/@aws-cdk/aws-ecs-patterns/test/fargate/test.queue-processing-fargate-service.ts
Labels: @aws-cdk/aws-ecs, p2, review/small

#7653 fix(cdk-assets): assets archiving corruption
  packages/cdk-assets/lib/private/archive.ts
Labels: contribution/core, pr-linter/exempt-test

#7469 docs(stepfunctions-tasks): fill in README
  packages/@aws-cdk/aws-stepfunctions-tasks/README.md
  packages/@aws-cdk/aws-stepfunctions/README.md
Labels: contribution/core

#7645 docs(cli): Expand help for bootstrap bucket name
  packages/aws-cdk/bin/cdk.ts
Labels: contribution/core

#7398 fix(cli): CLI ignores profile in cdk.json
  packages/aws-cdk/bin/cdk.ts
  packages/aws-cdk/lib/settings.ts
Labels: pr-linter/exempt-test

#7606 chore: add .vscode settings for eslint & some missed cleanup
  .gitignore
  .vscode/settings.json
  CONTRIBUTING.md
  packages/@aws-cdk/cloud-assembly-schema/package.json
  tools/cfn2ts/package.json
Labels: contribution/core

#7663 fix(ec2): `Vpc.fromLookup()` does not work in unit tests
  packages/@aws-cdk/aws-ec2/lib/instance.ts
  packages/@aws-cdk/aws-ec2/lib/vpc.ts
  packages/@aws-cdk/aws-ec2/test/test.vpc.from-lookup.ts
Labels: contribution/core

#7667 fix: multiple breakages due to jest version upgrade
  package.json
  packages/@aws-cdk/assert/package.json
  packages/@aws-cdk/aws-autoscaling-hooktargets/package.json
  packages/@aws-cdk/aws-batch/package.json
  packages/@aws-cdk/aws-certificatemanager/lambda-packages/dns_validated_certificate_handler/package.json
  packages/@aws-cdk/aws-cloudwatch-actions/package.json
  packages/@aws-cdk/aws-cognito/package.json
  packages/@aws-cdk/aws-dynamodb-global/lambda-packages/aws-global-table-coordinator/package.json
  packages/@aws-cdk/aws-dynamodb/package.json
  packages/@aws-cdk/aws-ecs-patterns/package.json
  packages/@aws-cdk/aws-elasticloadbalancingv2-targets/package.json
  packages/@aws-cdk/aws-events-targets/package.json
  packages/@aws-cdk/aws-iam/package.json
  packages/@aws-cdk/aws-lambda-destinations/package.json
  packages/@aws-cdk/aws-logs-destinations/package.json
  packages/@aws-cdk/aws-route53-patterns/package.json
  packages/@aws-cdk/aws-route53-targets/package.json
  packages/@aws-cdk/aws-s3-notifications/package.json
  packages/@aws-cdk/aws-sam/package.json
  packages/@aws-cdk/aws-ses-actions/package.json
  packages/@aws-cdk/aws-sns-subscriptions/package.json
  packages/@aws-cdk/aws-stepfunctions-tasks/package.json
  packages/@aws-cdk/cdk-assets-schema/package.json
  packages/@aws-cdk/cloud-assembly-schema/package.json
  packages/@aws-cdk/cloudformation-diff/package.json
  packages/@aws-cdk/core/lib/private/runtime-info.ts
  packages/@aws-cdk/cx-api/package.json
  packages/@monocdk-experiment/assert/package.json
  packages/aws-cdk/lib/init-templates/app/javascript/package.template.json
  packages/aws-cdk/lib/init-templates/app/typescript/package.template.json
  packages/aws-cdk/lib/init-templates/lib/typescript/package.template.json
  packages/aws-cdk/lib/init-templates/sample-app/javascript/package.template.json
  packages/aws-cdk/lib/init-templates/sample-app/typescript/package.template.json
  packages/aws-cdk/package.json
  packages/cdk-assets/package.json
  packages/cdk-dasm/package.json
  packages/decdk/package.json
  packages/decdk/test/sanity.test.ts
  tools/cdk-build-tools/package.json
  tools/cfn2ts/package.json
  tools/yarn-cling/package.json
  yarn.lock
Labels: contribution/core, pr-linter/exempt-test, pr/do-not-merge

#7658 chore(repo): add close stale issues github action
  .github/workflows/close-stale-issues.yml
Labels: contribution/core

#7688 chore(release): 1.36.1
  CHANGELOG.md
  lerna.json
  package.json
  packages/@aws-cdk/assert/package.json
  packages/@aws-cdk/aws-autoscaling-hooktargets/package.json
  packages/@aws-cdk/aws-batch/package.json
  packages/@aws-cdk/aws-certificatemanager/lambda-packages/dns_validated_certificate_handler/package.json
  packages/@aws-cdk/aws-cloudwatch-actions/package.json
  packages/@aws-cdk/aws-cognito/package.json
  packages/@aws-cdk/aws-dynamodb-global/lambda-packages/aws-global-table-coordinator/package.json
  packages/@aws-cdk/aws-dynamodb/package.json
  packages/@aws-cdk/aws-ecs-patterns/package.json
  packages/@aws-cdk/aws-elasticloadbalancingv2-targets/package.json
  packages/@aws-cdk/aws-events-targets/package.json
  packages/@aws-cdk/aws-iam/package.json
  packages/@aws-cdk/aws-lambda-destinations/package.json
  packages/@aws-cdk/aws-logs-destinations/package.json
  packages/@aws-cdk/aws-route53-patterns/package.json
  packages/@aws-cdk/aws-route53-targets/package.json
  packages/@aws-cdk/aws-s3-notifications/package.json
  packages/@aws-cdk/aws-sam/package.json
  packages/@aws-cdk/aws-ses-actions/package.json
  packages/@aws-cdk/aws-sns-subscriptions/package.json
  packages/@aws-cdk/aws-stepfunctions-tasks/package.json
  packages/@aws-cdk/cdk-assets-schema/package.json
  packages/@aws-cdk/cloud-assembly-schema/package.json
  packages/@aws-cdk/cloudformation-diff/package.json
  packages/@aws-cdk/core/lib/private/runtime-info.ts
  packages/@aws-cdk/cx-api/package.json
  packages/@monocdk-experiment/assert/package.json
  packages/aws-cdk/lib/init-templates/app/javascript/package.template.json
  packages/aws-cdk/lib/init-templates/app/typescript/package.template.json
  packages/aws-cdk/lib/init-templates/lib/typescript/package.template.json
  packages/aws-cdk/lib/init-templates/sample-app/javascript/package.template.json
  packages/aws-cdk/lib/init-templates/sample-app/typescript/package.template.json
  packages/aws-cdk/package.json
  packages/aws-cdk/test/integ/init/test-javascript.sh
  packages/cdk-assets/package.json
  packages/cdk-dasm/package.json
  packages/decdk/package.json
  packages/decdk/test/sanity.test.ts
  tools/cdk-build-tools/package.json
  tools/cfn2ts/package.json
  tools/yarn-cling/package.json
  yarn.lock
Labels: contribution/core, pr/no-squash

#7666 fix(rds): Cluster does not work with imported VPC
  packages/@aws-cdk/aws-rds/lib/cluster.ts
  packages/@aws-cdk/aws-rds/test/test.cluster.ts
Labels: contribution/core

#7702 chore(dynamodb): clear linter exclusions
  packages/@aws-cdk/aws-dynamodb/lib/table.ts
  packages/@aws-cdk/aws-dynamodb/package.json
Labels: @aws-cdk/aws-dynamodb, contribution/core

#7695 chore(cfnspec): update missing libraries to align with added eslint config
  packages/@aws-cdk/cfnspec/build-tools/create-missing-libraries.ts
Labels: @aws-cdk/cfnspec, contribution/core

#7668 fix(logs): grants don't work on imported LogGroups
  packages/@aws-cdk/aws-logs/README.md
  packages/@aws-cdk/aws-logs/lib/log-group.ts
  packages/@aws-cdk/aws-logs/test/test.loggroup.ts
Labels: contribution/core

#7704 chore(cli): install specific cli version in integ tests
  packages/aws-cdk/test/integ/run-against-dist
  packages/aws-cdk/test/integ/run-against-dist.bash
Labels: contribution/core

#7711 chore(cli): integ tests breakage
  packages/aws-cdk/test/integ/run-against-dist
Labels: contribution/core

#7705 chore: merge release/1.36.1 to master
  CHANGELOG.md
  lerna.json
Labels: contribution/core

#7644 fix(cloudwatch): Alarm can't use `MathExpression` without submetrics
  packages/@aws-cdk/aws-cloudwatch/lib/alarm.ts
  packages/@aws-cdk/aws-cloudwatch/lib/metric-types.ts
  packages/@aws-cdk/aws-cloudwatch/lib/metric.ts
  packages/@aws-cdk/aws-cloudwatch/package.json
  packages/@aws-cdk/aws-cloudwatch/test/test.metric-math.ts
  packages/@aws-cdk/cfnspec/spec-source/500_CloudWatch_Alarm_MetricDataQuery_Period_patch.json
Labels: contribution/core
