Repository aws/aws-cdk, pull requests merged in 2020-08, with the labels that each got.

#9383 chore(cfn-include): remove an unnecessary closing brace from the ReadMe
  packages/@aws-cdk/cloudformation-include/README.md
Labels: contribution/core

#9385 chore(merge-back): 1.56.0
  CHANGELOG.md
  lerna.json
Labels: pr/no-squash

#9377 fix(dynamodb): allow using PhysicalName.GENERATE_IF_NEEDED as the Table name
  packages/@aws-cdk/aws-dynamodb/lib/table.ts
  packages/@aws-cdk/aws-dynamodb/test/dynamodb.test.ts
Labels: contribution/core

#9380 chore(cloudfront): remove the originId property from OriginBase
  packages/@aws-cdk/aws-cloudfront/lib/origin.ts
Labels: contribution/core

#8848 feat(apigateway): additionalProperties in RestApi Model supports JsonSchema type
  packages/@aws-cdk/aws-apigateway/lib/json-schema.ts
Labels: pr-linter/exempt-readme, pr-linter/exempt-test

#9342 feat(core): implicit app for root stacks
  packages/@aws-cdk/assert/lib/synth-utils.ts
  packages/@aws-cdk/aws-apigateway/test/authorizers/integ.request-authorizer.expected.json
  packages/@aws-cdk/aws-apigateway/test/authorizers/integ.token-authorizer-iam-role.expected.json
  packages/@aws-cdk/aws-apigateway/test/authorizers/integ.token-authorizer.expected.json
  packages/@aws-cdk/aws-apigateway/test/integ.cors.expected.json
  packages/@aws-cdk/aws-autoscaling/test/auto-scaling-group.test.ts
  packages/@aws-cdk/aws-autoscaling/test/scheduled-action.test.ts
  packages/@aws-cdk/aws-cloudformation/test/test.deps.ts
  packages/@aws-cdk/aws-codecommit/test/test.codecommit.ts
  packages/@aws-cdk/aws-dynamodb/test/dynamodb.test.ts
  packages/@aws-cdk/aws-ec2/test/connections.test.ts
  packages/@aws-cdk/aws-ec2/test/userdata.test.ts
  packages/@aws-cdk/aws-ec2/test/vpc-endpoint.test.ts
  packages/@aws-cdk/aws-ec2/test/vpc.test.ts
  packages/@aws-cdk/aws-ecs-patterns/test/fargate/test.load-balanced-fargate-service.ts
  packages/@aws-cdk/aws-ecs/test/fargate/test.fargate-service.ts
  packages/@aws-cdk/aws-ecs/test/test.ecs-cluster.ts
  packages/@aws-cdk/aws-events/test/test.rule.ts
  packages/@aws-cdk/aws-glue/test/table.test.ts
  packages/@aws-cdk/aws-kinesis/test/stream.test.ts
  packages/@aws-cdk/aws-lambda-event-sources/test/test.dynamo.ts
  packages/@aws-cdk/aws-lambda/test/integ.current-version.expected.json
  packages/@aws-cdk/aws-lambda/test/test.function.ts
  packages/@aws-cdk/aws-s3-notifications/test/lambda/lambda.test.ts
  packages/@aws-cdk/aws-s3-notifications/test/queue.test.ts
  packages/@aws-cdk/aws-s3/test/test.bucket.ts
  packages/@aws-cdk/aws-secretsmanager/test/test.secret-rotation.ts
  packages/@aws-cdk/aws-sns-subscriptions/test/subs.test.ts
  packages/@aws-cdk/core/lib/asset-staging.ts
  packages/@aws-cdk/core/lib/private/prepare-app.ts
  packages/@aws-cdk/core/lib/stack.ts
  packages/@aws-cdk/core/lib/stage.ts
  packages/@aws-cdk/core/test/fs/test.fs.ts
  packages/@aws-cdk/core/test/test.aspect.ts
  packages/@aws-cdk/core/test/test.context.ts
  packages/@aws-cdk/core/test/test.resource.ts
  packages/@aws-cdk/core/test/test.stack.ts
  packages/@aws-cdk/core/test/test.tag-aspect.ts
  packages/@aws-cdk/core/test/util.ts
Labels: contribution/core, pr-linter/exempt-readme

#9415 chore(apigatewayv2): disallow allowCredentials when allowOrigin has '*'
  packages/@aws-cdk/aws-apigatewayv2/README.md
  packages/@aws-cdk/aws-apigatewayv2/lib/http/api.ts
  packages/@aws-cdk/aws-apigatewayv2/test/http/api.test.ts
  packages/@aws-cdk/aws-apigatewayv2/test/http/integrations/http.test.ts
Labels: contribution/core

#9416 chore: restore regular owners in the auto label action workflow
  .github/workflows/issue-label-assign.yml
Labels: contribution/core

#9360 feat(cloudfront): add support for Origin Groups
  packages/@aws-cdk/aws-cloudfront-origins/README.md
  packages/@aws-cdk/aws-cloudfront-origins/lib/index.ts
  packages/@aws-cdk/aws-cloudfront-origins/lib/origin-group.ts
  packages/@aws-cdk/aws-cloudfront-origins/lib/s3-origin.ts
  packages/@aws-cdk/aws-cloudfront-origins/test/integ.origin-group.expected.json
  packages/@aws-cdk/aws-cloudfront-origins/test/integ.origin-group.ts
  packages/@aws-cdk/aws-cloudfront-origins/test/origin-group.test.ts
  packages/@aws-cdk/aws-cloudfront/lib/distribution.ts
  packages/@aws-cdk/aws-cloudfront/lib/origin.ts
Labels: contribution/core

#9411 feat(cloudfront): Behaviors support cached methods, compression, viewer protocol, and smooth streaming
  packages/@aws-cdk/aws-cloudfront/README.md
  packages/@aws-cdk/aws-cloudfront/lib/distribution.ts
  packages/@aws-cdk/aws-cloudfront/lib/private/cache-behavior.ts
  packages/@aws-cdk/aws-cloudfront/test/private/cache-behavior.test.ts
Labels: @aws-cdk/aws-cloudfront, contribution/core

#8639 feat(core): warn if an aspect was added via another aspect
  packages/@aws-cdk/core/lib/private/synthesis.ts
  packages/@aws-cdk/core/test/test.aspect.ts
Labels: @aws-cdk/core, contribution/core, pr-linter/exempt-readme, pr/ready-to-merge

#9420 chore(cfn-include): correct the link to CFN docs about Parameters
  packages/@aws-cdk/cloudformation-include/README.md
Labels: contribution/core

#9423 chore: switch bug template to "expected/actual" behavior
  .github/ISSUE_TEMPLATE/bug.md
Labels: contribution/core

#9410 chore: do not use "synthesize" and "prepare" in the cdk
  packages/@aws-cdk/aws-apigateway/lib/deployment.ts
  packages/@aws-cdk/aws-apigateway/test/integ.restapi.multistack.expected.json
  packages/@aws-cdk/aws-apigateway/test/test.deployment.ts
  packages/@aws-cdk/aws-cloudfront/test/distribution.test.ts
  packages/@aws-cdk/aws-codepipeline-actions/test/cloudformation/test.pipeline-actions.ts
  packages/@aws-cdk/aws-ec2/test/connections.test.ts
  packages/@aws-cdk/aws-lambda/lib/function.ts
  packages/@aws-cdk/aws-lambda/test/integ.current-version.expected.json
  packages/@aws-cdk/aws-lambda/test/test.lambda-version.ts
  packages/@aws-cdk/aws-s3-notifications/test/notifications.test.ts
  packages/@aws-cdk/core/lib/private/synthesis.ts
  packages/@aws-cdk/core/lib/private/tree-metadata.ts
  packages/@aws-cdk/core/lib/stack.ts
  packages/@aws-cdk/core/test/test.stack.ts
Labels: contribution/core

#9428 chore: remove an additional "prepare" usage
  packages/@aws-cdk/aws-apigateway/lib/deployment.ts
  packages/@aws-cdk/aws-apigateway/lib/restapi.ts
  packages/@aws-cdk/aws-iam/lib/policy.ts
  packages/@aws-cdk/core/lib/cfn-resource.ts
  packages/@aws-cdk/core/lib/nested-stack.ts
  packages/@aws-cdk/core/test/test.cfn-resource.ts
  packages/@aws-cdk/pipelines/lib/pipeline.ts
  packages/@aws-cdk/pipelines/lib/stage.ts
Labels: contribution/core

#9095 feat(eks): endpoint access customization
  packages/@aws-cdk/aws-ec2/lib/vpc.ts
  packages/@aws-cdk/aws-ec2/test/vpc.test.ts
  packages/@aws-cdk/aws-eks/README.md
  packages/@aws-cdk/aws-eks/lib/cluster-resource-handler/cluster.ts
  packages/@aws-cdk/aws-eks/lib/cluster-resource.ts
  packages/@aws-cdk/aws-eks/lib/cluster.ts
  packages/@aws-cdk/aws-eks/lib/kubectl-handler/apply/__init__.py
  packages/@aws-cdk/aws-eks/lib/kubectl-handler/helm/__init__.py
  packages/@aws-cdk/aws-eks/lib/kubectl-handler/patch/__init__.py
  packages/@aws-cdk/aws-eks/lib/kubectl-provider.ts
  packages/@aws-cdk/aws-eks/test/integ.eks-cluster-private-endpoint.expected.json
  packages/@aws-cdk/aws-eks/test/integ.eks-cluster-private-endpoint.ts
  packages/@aws-cdk/aws-eks/test/integ.eks-cluster.expected.json
  packages/@aws-cdk/aws-eks/test/test.cluster.ts
Labels: contribution/core

#9451 fix(core): docs for CfnMapping are not clear
  packages/@aws-cdk/core/README.md
Labels: contribution/core, pr-linter/exempt-test

#9434 fix(ecs-patterns): Adds missing option to secure ingress of ALB in Ap…
  packages/@aws-cdk/aws-ecs-patterns/lib/base/application-load-balanced-service-base.ts
  packages/@aws-cdk/aws-ecs-patterns/test/ec2/test.l3s.ts
Labels: @aws-cdk/aws-ecs-patterns

#9464 feat(eks): default masters role
  packages/@aws-cdk/aws-eks/README.md
  packages/@aws-cdk/aws-eks/lib/cluster.ts
  packages/@aws-cdk/aws-eks/test/test.awsauth.ts
  packages/@aws-cdk/aws-eks/test/test.cluster.ts
  packages/@aws-cdk/aws-eks/test/test.fargate.ts
  packages/@aws-cdk/aws-eks/test/test.nodegroup.ts
Labels: contribution/core

#9454 feat(eks): deprecate "kubectlEnabled: false"
  packages/@aws-cdk/aws-eks/README.md
  packages/@aws-cdk/aws-eks/lib/cluster.ts
  packages/@aws-cdk/aws-eks/lib/fargate-profile.ts
  packages/@aws-cdk/aws-eks/lib/index.ts
  packages/@aws-cdk/aws-eks/lib/legacy-cluster.ts
  packages/@aws-cdk/aws-eks/lib/managed-nodegroup.ts
  packages/@aws-cdk/aws-eks/test/integ.eks-cluster.kubectl-disabled.ts
  packages/@aws-cdk/aws-eks/test/test.cluster.ts
  packages/@aws-cdk/aws-eks/test/test.fargate.ts
  packages/@aws-cdk/aws-eks/test/test.legacy-cluster.ts
  packages/@aws-cdk/aws-eks/test/test.nodegroup.ts
Labels: contribution/core, pr/breaking-change

#9100 fix(apigatewayv2): cyclic dependency between HttpApi and the lambda function
  packages/@aws-cdk/aws-apigatewayv2/lib/http/integration.ts
  packages/@aws-cdk/aws-apigatewayv2/lib/http/integrations/http.ts
  packages/@aws-cdk/aws-apigatewayv2/lib/http/integrations/lambda.ts
  packages/@aws-cdk/aws-apigatewayv2/lib/http/route.ts
  packages/@aws-cdk/aws-apigatewayv2/test/http/integ.custom-domain.expected.json
  packages/@aws-cdk/aws-apigatewayv2/test/http/integrations/integ.http-proxy.expected.json
  packages/@aws-cdk/aws-apigatewayv2/test/http/integrations/integ.lambda-proxy.expected.json
  packages/@aws-cdk/aws-apigatewayv2/test/http/integrations/lambda.test.ts
Labels: contribution/core

#9476 fix(cfn-include): no longer concatenate elements of Fn::Join without tokens
  packages/@aws-cdk/cloudformation-include/test/test-templates/user-data.json
  packages/@aws-cdk/cloudformation-include/test/valid-templates.test.ts
  packages/@aws-cdk/core/lib/cfn-parse.ts
Labels: contribution/core

#9389 feat(appsync): add x-ray parameter to AppSync
  packages/@aws-cdk/aws-appsync/README.md
  packages/@aws-cdk/aws-appsync/lib/graphqlapi.ts
  packages/@aws-cdk/aws-appsync/test/appsync.test.ts
Labels: @aws-cdk/aws-appsync

#9442 fix(cfn-include): fails to load SAM resources
  packages/@aws-cdk/cloudformation-include/test/serverless-transform.test.ts
  packages/@aws-cdk/cloudformation-include/test/test-templates/sam/only-minimal-sam-function-codeuri-as-param.yaml
  packages/@aws-cdk/cloudformation-include/test/test-templates/sam/only-minimal-sam-function-codeuri-as-s3location.yaml
  packages/@aws-cdk/cloudformation-include/test/test-templates/sam/only-minimal-sam-function-codeuri-bucket-as-param.yaml
  packages/@aws-cdk/cloudformation-include/test/test-templates/sam/only-sam-function-policies-array-ddb-crud-if.yaml
  packages/@aws-cdk/cloudformation-include/test/test-templates/sam/only-sam-function-policies-array-ddb-crud.yaml
  packages/@aws-cdk/core/lib/cfn-parse.ts
  packages/@aws-cdk/core/lib/stack.ts
  tools/cfn2ts/lib/codegen.ts
Labels: contribution/core

#9500 fix(core): can't have multiple CfnRules in a Stack
  packages/@aws-cdk/core/lib/stack.ts
  packages/@aws-cdk/core/test/test.rule.ts
Labels: contribution/core

#9514 chore(cognito): move some tests into the correct describe block.
  packages/@aws-cdk/aws-cognito/test/user-pool.test.ts
Labels: contribution/core

#9532 fix(cfn-include): allowedValues aren't included when specified by a parameter
  packages/@aws-cdk/cloudformation-include/lib/cfn-include.ts
  packages/@aws-cdk/cloudformation-include/test/test-templates/bucket-with-parameters.json
Labels: contribution/core

#9528 chore(merge-back): 1.57.0
  CHANGELOG.md
  lerna.json
Labels: pr/no-squash

#9252 fix(codedeploy): ServerDeploymentGroup takes AutoScalingGroup instead of IAutoScalingGroup
  allowed-breaking-changes.txt
  packages/@aws-cdk/aws-autoscaling/lib/auto-scaling-group.ts
  packages/@aws-cdk/aws-codedeploy/lib/server/deployment-group.ts
  packages/@aws-cdk/aws-codepipeline-actions/lib/codedeploy/server-deploy-action.ts
  packages/@aws-cdk/aws-ec2/lib/machine-image.ts
  packages/@aws-cdk/aws-ec2/lib/user-data.ts
Labels: contribution/core, pr-linter/exempt-test

#9544 fix(eks): private endpoint access doesn't work with `Vpc.fromLookup`
  packages/@aws-cdk/aws-eks/lib/cluster.ts
  packages/@aws-cdk/aws-eks/test/test.cluster.ts
Labels: contribution/core

#9504 chore(core): document how to override availability zones
  packages/@aws-cdk/aws-ec2/README.md
  packages/@aws-cdk/core/lib/stack.ts
Labels: contribution/core

#9558 feat(core): new APIs for Aspects and Tags
  packages/@aws-cdk/core/lib/aspect.ts
  packages/@aws-cdk/core/lib/construct-compat.ts
  packages/@aws-cdk/core/lib/private/synthesis.ts
  packages/@aws-cdk/core/lib/tag-aspect.ts
  packages/@aws-cdk/core/test/test.aspect.ts
  packages/@aws-cdk/core/test/test.stack.ts
  packages/@aws-cdk/core/test/test.stage.ts
  packages/@aws-cdk/core/test/test.tag-aspect.ts
Labels: contribution/core, pr-linter/exempt-readme

#9557 feat(core): deprecate "Construct.node" in favor of "Construct.construct"
  packages/@aws-cdk/aws-ecs-patterns/test/fargate/integ.load-balanced-fargate-service.ts
  packages/@aws-cdk/aws-ecs-patterns/test/fargate/test.load-balanced-fargate-service.ts
  packages/@aws-cdk/aws-lambda/lib/function-base.ts
  packages/@aws-cdk/aws-route53/test/test.util.ts
  packages/@aws-cdk/core/README.md
  packages/@aws-cdk/core/lib/app.ts
  packages/@aws-cdk/core/lib/asset-staging.ts
  packages/@aws-cdk/core/lib/cfn-element.ts
  packages/@aws-cdk/core/lib/cfn-output.ts
  packages/@aws-cdk/core/lib/cfn-parse.ts
  packages/@aws-cdk/core/lib/cfn-resource.ts
  packages/@aws-cdk/core/lib/construct-compat.ts
  packages/@aws-cdk/core/lib/context-provider.ts
  packages/@aws-cdk/core/lib/custom-resource-provider/custom-resource-provider.ts
  packages/@aws-cdk/core/lib/deps.ts
  packages/@aws-cdk/core/lib/nested-stack.ts
  packages/@aws-cdk/core/lib/private/cfn-reference.ts
  packages/@aws-cdk/core/lib/private/physical-name-generator.ts
  packages/@aws-cdk/core/lib/private/prepare-app.ts
  packages/@aws-cdk/core/lib/private/refs.ts
  packages/@aws-cdk/core/lib/private/synthesis.ts
  packages/@aws-cdk/core/lib/private/tree-metadata.ts
  packages/@aws-cdk/core/lib/resource.ts
  packages/@aws-cdk/core/lib/stack-synthesizers/_shared.ts
  packages/@aws-cdk/core/lib/stack-synthesizers/default-synthesizer.ts
  packages/@aws-cdk/core/lib/stack-synthesizers/legacy.ts
  packages/@aws-cdk/core/lib/stack.ts
  packages/@aws-cdk/core/lib/stage.ts
  packages/@aws-cdk/core/test/custom-resource-provider/test.custom-resource-provider.ts
  packages/@aws-cdk/core/test/private/test.tree-metadata.ts
  packages/@aws-cdk/core/test/test.app.ts
  packages/@aws-cdk/core/test/test.aspect.ts
  packages/@aws-cdk/core/test/test.assets.ts
  packages/@aws-cdk/core/test/test.cfn-resource.ts
  packages/@aws-cdk/core/test/test.construct.ts
  packages/@aws-cdk/core/test/test.context.ts
  packages/@aws-cdk/core/test/test.logical-id.ts
  packages/@aws-cdk/core/test/test.resource.ts
  packages/@aws-cdk/core/test/test.stack.ts
  packages/@aws-cdk/core/test/test.stage.ts
  packages/@aws-cdk/core/test/test.staging.ts
  packages/@aws-cdk/core/test/test.synthesis.ts
  packages/@aws-cdk/core/test/test.util.ts
Labels: contribution/core

#9563 feat(core): new annotations api
  packages/@aws-cdk/core/lib/annotations.ts
  packages/@aws-cdk/core/lib/construct-compat.ts
  packages/@aws-cdk/core/lib/context-provider.ts
  packages/@aws-cdk/core/lib/private/synthesis.ts
  packages/@aws-cdk/core/lib/private/tree-metadata.ts
  packages/@aws-cdk/core/lib/stack.ts
  packages/@aws-cdk/core/test/test.app.ts
  packages/@aws-cdk/core/test/test.construct.ts
Labels: contribution/core, pr-linter/exempt-readme

#9553 fix(eks): clusters in a FAILED state are not detected
  packages/@aws-cdk/aws-eks/lib/cluster-resource-handler/cluster.ts
  packages/@aws-cdk/aws-eks/test/test.cluster-resource-provider.ts
Labels: contribution/core

#9594 feat(secretsmanager): Specify secret value at creation
  packages/@aws-cdk/aws-secretsmanager/README.md
  packages/@aws-cdk/aws-secretsmanager/lib/secret.ts
  packages/@aws-cdk/aws-secretsmanager/package.json
  packages/@aws-cdk/aws-secretsmanager/test/test.secret.ts
Labels: contribution/core

#9412 chore(ecs): fix comment @default on CloudMapOptions.dnsRecordType
  packages/@aws-cdk/aws-ecs/lib/base/base-service.ts
Labels: @aws-cdk/aws-ecs

#9571 chore: update eks assignee in github action workflow
  .github/workflows/issue-label-assign.yml
Labels: contribution/core

#9595 docs(codepipeline): document required GitHub token scopes
  packages/@aws-cdk/aws-codepipeline-actions/README.md
  packages/@aws-cdk/aws-codepipeline-actions/lib/github/source-action.ts
  packages/@aws-cdk/pipelines/README.md
Labels: contribution/core

#9610 revert(secretsmanager): Specify secret value at creation
  packages/@aws-cdk/aws-secretsmanager/README.md
  packages/@aws-cdk/aws-secretsmanager/lib/secret.ts
  packages/@aws-cdk/aws-secretsmanager/package.json
  packages/@aws-cdk/aws-secretsmanager/test/test.secret.ts
Labels: contribution/core

#8883 feat(lambda): autoscaling for lambda aliases
  packages/@aws-cdk/aws-lambda/README.md
  packages/@aws-cdk/aws-lambda/lib/alias.ts
  packages/@aws-cdk/aws-lambda/lib/index.ts
  packages/@aws-cdk/aws-lambda/lib/private/scalable-function-attribute.ts
  packages/@aws-cdk/aws-lambda/lib/scalable-attribute-api.ts
  packages/@aws-cdk/aws-lambda/package.json
  packages/@aws-cdk/aws-lambda/test/integ.autoscaling.lit.expected.json
  packages/@aws-cdk/aws-lambda/test/integ.autoscaling.lit.ts
  packages/@aws-cdk/aws-lambda/test/test.alias.ts
Labels: contribution/core

#9343 feat(ecs): Option to encrypt lifecycle hook SNS Topic
  packages/@aws-cdk/aws-autoscaling-hooktargets/lib/lambda-hook.ts
  packages/@aws-cdk/aws-autoscaling-hooktargets/package.json
  packages/@aws-cdk/aws-autoscaling-hooktargets/test/hooks.test.ts
  packages/@aws-cdk/aws-ecs/README.md
  packages/@aws-cdk/aws-ecs/lib/cluster.ts
  packages/@aws-cdk/aws-ecs/lib/drain-hook/instance-drain-hook.ts
  packages/@aws-cdk/aws-ecs/package.json
  packages/@aws-cdk/aws-ecs/test/test.ecs-cluster.ts
Labels: @aws-cdk/aws-ecs

#9616 chore(kms): overridden validate method must be protected
  packages/@aws-cdk/aws-kms/lib/key.ts
Labels: contribution/core

#9513 feat(cognito): better control sms role creation
  packages/@aws-cdk/aws-appsync/test/integ.graphql-iam.expected.json
  packages/@aws-cdk/aws-appsync/test/integ.graphql.expected.json
  packages/@aws-cdk/aws-cognito/README.md
  packages/@aws-cdk/aws-cognito/lib/user-pool.ts
  packages/@aws-cdk/aws-cognito/test/integ.user-pool-client-explicit-props.expected.json
  packages/@aws-cdk/aws-cognito/test/integ.user-pool-domain-cfdist.expected.json
  packages/@aws-cdk/aws-cognito/test/integ.user-pool-domain-signinurl.expected.json
  packages/@aws-cdk/aws-cognito/test/integ.user-pool-idp.expected.json
  packages/@aws-cdk/aws-cognito/test/integ.user-pool-signup-code.expected.json
  packages/@aws-cdk/aws-cognito/test/integ.user-pool-signup-link.expected.json
  packages/@aws-cdk/aws-cognito/test/integ.user-pool.expected.json
  packages/@aws-cdk/aws-cognito/test/user-pool.test.ts
  packages/@aws-cdk/aws-elasticloadbalancingv2-actions/test/integ.cognito.lit.expected.json
Labels: contribution/core

#9604 feat: "stack relative exports" flag
  packages/@aws-cdk/core/lib/private/refs.ts
  packages/@aws-cdk/core/test/test.stack.ts
  packages/@aws-cdk/cx-api/lib/features.ts
Labels: contribution/core, pr-linter/exempt-readme

#9648 fix(cloudfront): Escape hatch support for Distribution
  packages/@aws-cdk/aws-cloudfront-origins/test/integ.http-origin.expected.json
  packages/@aws-cdk/aws-cloudfront-origins/test/integ.load-balancer-origin.expected.json
  packages/@aws-cdk/aws-cloudfront-origins/test/integ.origin-group.expected.json
  packages/@aws-cdk/aws-cloudfront-origins/test/integ.s3-origin.expected.json
  packages/@aws-cdk/aws-cloudfront/lib/distribution.ts
  packages/@aws-cdk/aws-cloudfront/test/distribution.test.ts
Labels: contribution/core

#8879 feat(codebuild): add support for GPU build images
  packages/@aws-cdk/aws-codebuild/README.md
  packages/@aws-cdk/aws-codebuild/lib/index.ts
  packages/@aws-cdk/aws-codebuild/lib/linux-gpu-build-image.ts
  packages/@aws-cdk/aws-codebuild/lib/private/run-script-linux-build-spec.ts
  packages/@aws-cdk/aws-codebuild/lib/project.ts
  packages/@aws-cdk/aws-codebuild/package.json
  packages/@aws-cdk/aws-codebuild/test/integ.aws-deep-learning-container-build-image.expected.json
  packages/@aws-cdk/aws-codebuild/test/integ.aws-deep-learning-container-build-image.ts
  packages/@aws-cdk/aws-codebuild/test/test.linux-gpu-build-image.ts
  packages/@aws-cdk/aws-ecr/lib/repository.ts
  packages/@aws-cdk/region-info/build-tools/fact-tables.ts
  packages/@aws-cdk/region-info/build-tools/generate-static-data.ts
  packages/@aws-cdk/region-info/lib/fact.ts
  packages/@aws-cdk/region-info/lib/region-info.ts
Labels: contribution/core

#9657 chore: secret scan in CodeBuild test
  git-secrets-scan.sh
  packages/@aws-cdk/aws-codebuild/lib/linux-gpu-build-image.ts
  packages/@aws-cdk/aws-codebuild/test/integ.aws-deep-learning-container-build-image.expected.json
Labels: contribution/core

#9653 chore(merge-back): 1.58.0
  CHANGELOG.md
  lerna.json
Labels: pr/no-squash

#9065 feat(ec2): CloudFormation-init support
  packages/@aws-cdk/aws-ec2/README.md
  packages/@aws-cdk/aws-ec2/lib/cfn-init-elements.ts
  packages/@aws-cdk/aws-ec2/lib/cfn-init.ts
  packages/@aws-cdk/aws-ec2/lib/index.ts
  packages/@aws-cdk/aws-ec2/lib/instance.ts
  packages/@aws-cdk/aws-ec2/lib/private/cfn-init-internal.ts
  packages/@aws-cdk/aws-ec2/package.json
  packages/@aws-cdk/aws-ec2/test/cfn-init-element.test.ts
  packages/@aws-cdk/aws-ec2/test/cfn-init.test.ts
  packages/@aws-cdk/aws-ec2/test/instance.test.ts
  packages/@aws-cdk/aws-ec2/test/integ.instance-init.expected.json
  packages/@aws-cdk/aws-ec2/test/integ.instance-init.ts
Labels: contribution/core

#9634 chore: apply white background on default logos
  logo/default-128-dark.png
  logo/default-256-dark.png
  logo/default-64-dark.png
Labels: contribution/core

#9543 feat(cfn-include): allow passing Parameters to the included template
  packages/@aws-cdk/cloudformation-include/README.md
  packages/@aws-cdk/cloudformation-include/lib/cfn-include.ts
  packages/@aws-cdk/cloudformation-include/test/test-templates/bucket-with-parameters.json
  packages/@aws-cdk/cloudformation-include/test/test-templates/fn-sub-parameters.json
  packages/@aws-cdk/cloudformation-include/test/test-templates/fn-sub-shadow-parameter.json
  packages/@aws-cdk/cloudformation-include/test/test-templates/parameter-references.json
  packages/@aws-cdk/cloudformation-include/test/valid-templates.test.ts
  packages/@aws-cdk/core/lib/cfn-parse.ts
  packages/@aws-cdk/core/lib/from-cfn.ts
  packages/@aws-cdk/core/lib/index.ts
  tools/cfn2ts/lib/codegen.ts
Labels: contribution/core

#9575 fix(codepipeline): S3 source Action with trigger=Events fails for bucketKey a Token
  packages/@aws-cdk/aws-codepipeline-actions/lib/s3/source-action.ts
  packages/@aws-cdk/aws-codepipeline-actions/test/s3/test.s3-source-action.ts
Labels: contribution/core

#9535 feat(eks): ability to query runtime information from the cluster
  packages/@aws-cdk/aws-eks/README.md
  packages/@aws-cdk/aws-eks/lib/aws-auth.ts
  packages/@aws-cdk/aws-eks/lib/cluster-resource-provider.ts
  packages/@aws-cdk/aws-eks/lib/cluster.ts
  packages/@aws-cdk/aws-eks/lib/index.ts
  packages/@aws-cdk/aws-eks/lib/k8s-manifest.ts
  packages/@aws-cdk/aws-eks/lib/k8s-object-value.ts
  packages/@aws-cdk/aws-eks/lib/kubectl-handler/get/__init__.py
  packages/@aws-cdk/aws-eks/lib/kubectl-handler/index.py
  packages/@aws-cdk/aws-eks/lib/kubectl-layer.ts
  packages/@aws-cdk/aws-eks/lib/service-account.ts
  packages/@aws-cdk/aws-eks/test/integ.eks-cluster-private-endpoint.expected.json
  packages/@aws-cdk/aws-eks/test/integ.eks-cluster-private-endpoint.ts
  packages/@aws-cdk/aws-eks/test/integ.eks-cluster.expected.json
  packages/@aws-cdk/aws-eks/test/integ.eks-cluster.ts
  packages/@aws-cdk/aws-eks/test/pinger/function/index.py
  packages/@aws-cdk/aws-eks/test/pinger/pinger.ts
  packages/@aws-cdk/aws-eks/test/test.awsauth.ts
  packages/@aws-cdk/aws-eks/test/test.cluster.ts
  packages/@aws-cdk/aws-eks/test/test.k8s-manifest.ts
  packages/@aws-cdk/aws-eks/test/test.k8s-object-value.ts
  packages/@aws-cdk/aws-eks/test/test.legacy-cluster.ts
  packages/@aws-cdk/aws-eks/test/test.nodegroup.ts
  packages/@aws-cdk/aws-eks/test/test.service-account.ts
Labels: contribution/core

#9692 chore(cli): bump up jest and ts-jest versions in TypeScript and JavaScript init templates
  packages/aws-cdk/lib/init-templates/app/javascript/package.template.json
  packages/aws-cdk/lib/init-templates/app/typescript/package.template.json
  packages/aws-cdk/lib/init-templates/lib/typescript/package.template.json
  packages/aws-cdk/lib/init-templates/sample-app/javascript/package.template.json
  packages/aws-cdk/lib/init-templates/sample-app/typescript/package.template.json
Labels: contribution/core, package/tools

#9697 chore(cognito): emailTransmission is actually emailSettings
  packages/@aws-cdk/aws-cognito/README.md
Labels: contribution/core

#9640 chore: formatting fixes to DESIGN_GUIDELINES.md
  DESIGN_GUIDELINES.md
Labels: contribution/core

#9707 chore(assert): bump up jest version to align with @types/jest version
  packages/@aws-cdk/assert/package.json
Labels: contribution/core

#9708 chore(cli): bump up typescript version for TS init templates
  packages/aws-cdk/lib/init-templates/app/typescript/package.template.json
  packages/aws-cdk/lib/init-templates/lib/typescript/package.template.json
  packages/aws-cdk/lib/init-templates/sample-app/typescript/package.template.json
Labels: contribution/core

#9611 chore: add new module to auto assign/label action workflow
  .github/workflows/issue-label-assign.yml
Labels: contribution/core

#9722 chore(assert): missed updating peerDependencies when updating jest
  packages/@aws-cdk/assert/package.json
Labels: contribution/core

#8824 feat(synthetics): Synthetics L2 Support
  packages/@aws-cdk/aws-synthetics/README.md
  packages/@aws-cdk/aws-synthetics/images/endpoint-example.png
  packages/@aws-cdk/aws-synthetics/images/ui-screenshot.png
  packages/@aws-cdk/aws-synthetics/lib/canary.ts
  packages/@aws-cdk/aws-synthetics/lib/code.ts
  packages/@aws-cdk/aws-synthetics/lib/index.ts
  packages/@aws-cdk/aws-synthetics/lib/schedule.ts
  packages/@aws-cdk/aws-synthetics/package.json
  packages/@aws-cdk/aws-synthetics/test/canaries/nodejs/node_modules/canary.js
  packages/@aws-cdk/aws-synthetics/test/canary.test.ts
  packages/@aws-cdk/aws-synthetics/test/canary.zip
  packages/@aws-cdk/aws-synthetics/test/code.test.ts
  packages/@aws-cdk/aws-synthetics/test/integ.asset.expected.json
  packages/@aws-cdk/aws-synthetics/test/integ.asset.ts
  packages/@aws-cdk/aws-synthetics/test/integ.canary.expected.json
  packages/@aws-cdk/aws-synthetics/test/integ.canary.ts
  packages/@aws-cdk/aws-synthetics/test/metric.test.ts
  packages/@aws-cdk/aws-synthetics/test/synthetics.test.ts
Labels: @aws-cdk/aws-synthetics, contribution/core

#9691 docs: Add info about stability to repo README
  README.md
Labels: contribution/core

#9254 feat(appsync): import existing graphql api
  packages/@aws-cdk/aws-appsync/README.md
  packages/@aws-cdk/aws-appsync/lib/data-source.ts
  packages/@aws-cdk/aws-appsync/lib/graphqlapi-base.ts
  packages/@aws-cdk/aws-appsync/lib/graphqlapi.ts
  packages/@aws-cdk/aws-appsync/lib/index.ts
  packages/@aws-cdk/aws-appsync/lib/resolver.ts
  packages/@aws-cdk/aws-appsync/package.json
  packages/@aws-cdk/aws-appsync/test/appsync-apikey.test.ts
  packages/@aws-cdk/aws-appsync/test/appsync-dynamodb.test.ts
  packages/@aws-cdk/aws-appsync/test/appsync-http.test.ts
  packages/@aws-cdk/aws-appsync/test/appsync-lambda.test.ts
  packages/@aws-cdk/aws-appsync/test/appsync-none.test.ts
  packages/@aws-cdk/aws-appsync/test/integ.api-import.expected.json
  packages/@aws-cdk/aws-appsync/test/integ.api-import.ts
  packages/@aws-cdk/aws-appsync/test/integ.graphql-iam.expected.json
  packages/@aws-cdk/aws-appsync/test/integ.graphql-iam.ts
  packages/@aws-cdk/aws-appsync/test/integ.graphql.expected.json
  packages/@aws-cdk/aws-appsync/test/integ.graphql.ts
Labels: @aws-cdk/aws-appsync, pr/breaking-change

#9417 feat(appsync): code-first schema allows for object type definition
  packages/@aws-cdk/aws-appsync/README.md
  packages/@aws-cdk/aws-appsync/lib/graphqlapi.ts
  packages/@aws-cdk/aws-appsync/lib/index.ts
  packages/@aws-cdk/aws-appsync/lib/schema-types.ts
  packages/@aws-cdk/aws-appsync/test/appsync-code-first.test.ts
  packages/@aws-cdk/aws-appsync/test/appsync-schema.test.ts
  packages/@aws-cdk/aws-appsync/test/integ.graphql-schema.expected.json
  packages/@aws-cdk/aws-appsync/test/integ.graphql-schema.ts
  packages/@aws-cdk/aws-appsync/test/object-type-definitions.ts
  packages/@aws-cdk/aws-appsync/test/scalar-type-defintions.ts
  packages/@aws-cdk/aws-appsync/test/verify.integ.graphql-schema.sh
Labels: @aws-cdk/aws-appsync, contribution/core

#9734 chore(merge-back): 1.59.0
  CHANGELOG.md
  lerna.json
Labels: pr/no-squash

#9750 chore(core): Prereq check - support paths with spaces.
  scripts/check-prerequisites.sh
Labels: p1

#9746 fix(eks): AMI changes in managed SSM store param causes rolling update of ASG
  packages/@aws-cdk/aws-eks/lib/cluster.ts
  packages/@aws-cdk/aws-eks/lib/legacy-cluster.ts
  packages/@aws-cdk/aws-eks/test/integ.eks-cluster.expected.json
  packages/@aws-cdk/aws-eks/test/test.cluster.ts
Labels: contribution/core

#9699 feat(cloudfront): Distribution - alternate domains
  packages/@aws-cdk/aws-cloudfront/README.md
  packages/@aws-cdk/aws-cloudfront/lib/distribution.ts
  packages/@aws-cdk/aws-cloudfront/test/distribution.test.ts
Labels: contribution/core

#9664 feat(ec2): CloudFormation init for files, packages, sources, users, & groups
  packages/@aws-cdk/aws-ec2/README.md
  packages/@aws-cdk/aws-ec2/lib/cfn-init-elements.ts
  packages/@aws-cdk/aws-ec2/lib/cfn-init.ts
  packages/@aws-cdk/aws-ec2/lib/instance.ts
  packages/@aws-cdk/aws-ec2/lib/private/cfn-init-internal.ts
  packages/@aws-cdk/aws-ec2/test/asset-fixture/data.txt
  packages/@aws-cdk/aws-ec2/test/cfn-init-element.test.ts
  packages/@aws-cdk/aws-ec2/test/cfn-init.test.ts
  packages/@aws-cdk/aws-ec2/test/integ.instance-init.expected.json
  packages/@aws-cdk/aws-ec2/test/integ.instance-init.ts
Labels: contribution/core

#9769 fix(apigateway): access log format does not allow tokens
  packages/@aws-cdk/aws-apigateway/lib/stage.ts
  packages/@aws-cdk/aws-apigateway/test/test.stage.ts
Labels: contribution/core

#9341 feat(ecs): add support for automatic HTTPS redirect
  packages/@aws-cdk/aws-ecs-patterns/README.md
  packages/@aws-cdk/aws-ecs-patterns/lib/base/application-load-balanced-service-base.ts
  packages/@aws-cdk/aws-ecs-patterns/test/fargate/integ.load-balanced-fargate-service.expected.json
  packages/@aws-cdk/aws-ecs-patterns/test/fargate/integ.load-balanced-fargate-service.ts
Labels: @aws-cdk/aws-ecs

#9525 fix(cfn-include): handle numbers expressed as strings in templates
  packages/@aws-cdk/cloudformation-diff/lib/diff/util.ts
  packages/@aws-cdk/cloudformation-diff/test/diff-template.test.ts
  packages/@aws-cdk/cloudformation-include/test/invalid-templates.test.ts
  packages/@aws-cdk/cloudformation-include/test/test-templates/invalid/alphabetical-string-passed-to-number.json
  packages/@aws-cdk/cloudformation-include/test/test-templates/parsing-as-numbers.json
  packages/@aws-cdk/cloudformation-include/test/valid-templates.test.ts
  packages/@aws-cdk/core/lib/cfn-parse.ts
Labels: contribution/core

#9768 chore(ownership): transfer ownership of core to rix0rrr
  .github/workflows/issue-label-assign.yml
Labels: contribution/core

#9516 fix(cli): "fancy" progress reporting not disabled on all CI systems
  packages/aws-cdk/bin/cdk.ts
  packages/aws-cdk/lib/api/cloudformation-deployments.ts
  packages/aws-cdk/lib/api/deploy-stack.ts
  packages/aws-cdk/lib/api/util/cloudformation/stack-activity-monitor.ts
  packages/aws-cdk/lib/cdk-toolkit.ts
Labels: pr-linter/exempt-test

#9795 fix(cli): stack monitor reads complete stack history every 5 seconds
  packages/aws-cdk/lib/api/deploy-stack.ts
  packages/aws-cdk/lib/api/util/cloudformation/stack-activity-monitor.ts
  packages/aws-cdk/test/util/stack-monitor.test.ts
Labels: contribution/core

#9772 feat(rds): CloudWatch logs exports for DB clusters
  packages/@aws-cdk/aws-rds/README.md
  packages/@aws-cdk/aws-rds/lib/cluster.ts
  packages/@aws-cdk/aws-rds/test/test.cluster.ts
Labels: contribution/core

#9801 chore(apigatewayv2): use segments to announce stability
  packages/@aws-cdk/aws-apigatewayv2/README.md
  packages/@aws-cdk/aws-apigatewayv2/package.json
Labels: contribution/core

#8467 feat(ecs): add EfsVolumeConfiguration to Volume
  packages/@aws-cdk/aws-ecs/README.md
  packages/@aws-cdk/aws-ecs/lib/base/task-definition.ts
  packages/@aws-cdk/aws-ecs/package.json
  packages/@aws-cdk/aws-ecs/test/ec2/test.ec2-task-definition.ts
  packages/@aws-cdk/cfnspec/spec-source/000_CloudFormationResourceSpecification.json
Labels: @aws-cdk/aws-ecs

#9805 refactor(appsync): refactor schema-types to separate files
  packages/@aws-cdk/aws-appsync/lib/graphqlapi.ts
  packages/@aws-cdk/aws-appsync/lib/index.ts
  packages/@aws-cdk/aws-appsync/lib/schema-base.ts
  packages/@aws-cdk/aws-appsync/lib/schema-field.ts
  packages/@aws-cdk/aws-appsync/lib/schema-intermediate.ts
Labels: @aws-cdk/aws-appsync, contribution/core

#9809 chore: log in to DockerHub in the PR build
  buildspec-pr.yaml
Labels: contribution/core

#9800 chore(certificatemanager): Update README to inline examples and mention limits
  packages/@aws-cdk/aws-certificatemanager/README.md
  packages/@aws-cdk/aws-certificatemanager/test/example.dns.lit.ts
  packages/@aws-cdk/aws-certificatemanager/test/example.simple-request.lit.ts
Labels: contribution/core

#9814 fix(cloudformation-diff): DependsOn singleton arrays aren't equal to string values
  packages/@aws-cdk/cloudformation-diff/lib/diff/util.ts
  packages/@aws-cdk/cloudformation-diff/test/diff-template.test.ts
Labels: contribution/core

#9796 chore(rds): Refactor DatabaseCluster constructor
  packages/@aws-cdk/aws-rds/README.md
  packages/@aws-cdk/aws-rds/lib/cluster.ts
Labels: contribution/core

#9777 feat(cfn-include): add support for retrieving Mapping objects from the template
  packages/@aws-cdk/cloudformation-include/README.md
  packages/@aws-cdk/cloudformation-include/lib/cfn-include.ts
  packages/@aws-cdk/cloudformation-include/test/invalid-templates.test.ts
  packages/@aws-cdk/cloudformation-include/test/test-templates/invalid/non-existent-mapping.json
  packages/@aws-cdk/cloudformation-include/test/test-templates/only-mapping-and-bucket.json
  packages/@aws-cdk/cloudformation-include/test/valid-templates.test.ts
  packages/@aws-cdk/core/lib/cfn-parse.ts
Labels: contribution/core

#9797 feat(rds): Validate log types for clusters
  packages/@aws-cdk/aws-rds/lib/cluster-engine.ts
  packages/@aws-cdk/aws-rds/lib/cluster.ts
  packages/@aws-cdk/aws-rds/test/test.cluster-engine.ts
  packages/@aws-cdk/aws-rds/test/test.cluster.ts
Labels: contribution/core, pr-linter/exempt-readme

#9835 fix(cli): CLI does not use regional endpoints
  packages/aws-cdk/lib/api/aws-auth/sdk-provider.ts
  packages/cdk-assets/bin/publish.ts
Labels: contribution/core, pr-linter/exempt-test

#9829 fix(cloudfront): all origin access identities have identical names
  packages/@aws-cdk/aws-cloudfront-origins/lib/s3-origin.ts
  packages/@aws-cdk/aws-cloudfront-origins/test/integ.origin-group.expected.json
  packages/@aws-cdk/aws-cloudfront-origins/test/integ.s3-origin.expected.json
  packages/@aws-cdk/aws-cloudfront-origins/test/s3-origin.test.ts
Labels: contribution/core

#9826 chore(ownership): transfer cloudfront to nick
  .github/workflows/issue-label-assign.yml
Labels: contribution/core

#9828 fix(cloudfront): Distribution ignores webAclId
  packages/@aws-cdk/aws-cloudfront/lib/distribution.ts
  packages/@aws-cdk/aws-cloudfront/test/distribution.test.ts
Labels: @aws-cdk/aws-cloudfront, contribution/core

#9830 chore(cli): fix bugs introduced in stack monitor
  packages/aws-cdk/lib/api/deploy-stack.ts
  packages/aws-cdk/lib/api/util/cloudformation/stack-activity-monitor.ts
  packages/aws-cdk/test/api/bootstrap.test.ts
  packages/aws-cdk/test/api/deploy-stack.test.ts
  packages/aws-cdk/test/util/stack-monitor.test.ts
Labels: contribution/core

#9839 chore: log in to DockerHub during the main build
  buildspec.yaml
Labels: contribution/core

#9783 feat(cfn-include): add support for retrieving Rule objects from the template
  packages/@aws-cdk/cloudformation-include/README.md
  packages/@aws-cdk/cloudformation-include/lib/cfn-include.ts
  packages/@aws-cdk/cloudformation-include/test/invalid-templates.test.ts
  packages/@aws-cdk/cloudformation-include/test/test-templates/invalid/only-codecommit-repo-using-cfn-functions.json
  packages/@aws-cdk/cloudformation-include/test/test-templates/invalid/rule-referencing-a-non-existent-parameter.json
  packages/@aws-cdk/cloudformation-include/test/test-templates/only-parameters-and-rule.json
  packages/@aws-cdk/cloudformation-include/test/valid-templates.test.ts
  packages/@aws-cdk/core/lib/cfn-parse.ts
Labels: contribution/core

#8280 feat: make imported resources account/region-aware
  packages/@aws-cdk/aws-certificatemanager/test/util.test.ts
  packages/@aws-cdk/aws-codepipeline-actions/README.md
  packages/@aws-cdk/aws-codepipeline-actions/test/s3/test.s3-deploy-action.ts
  packages/@aws-cdk/aws-codepipeline/lib/pipeline.ts
  packages/@aws-cdk/aws-dynamodb/test/dynamodb.test.ts
  packages/@aws-cdk/aws-ec2/lib/bastion-host.ts
  packages/@aws-cdk/aws-ec2/package.json
  packages/@aws-cdk/aws-ec2/test/integ.instance-init.expected.json
  packages/@aws-cdk/aws-ec2/test/userdata.test.ts
  packages/@aws-cdk/aws-ecs-patterns/test/fargate/integ.load-balanced-fargate-service.ts
  packages/@aws-cdk/aws-ecs-patterns/test/fargate/test.load-balanced-fargate-service.ts
  packages/@aws-cdk/aws-eks-legacy/lib/kubectl-layer.ts
  packages/@aws-cdk/aws-eks/lib/kubectl-layer.ts
  packages/@aws-cdk/aws-iam/lib/grant.ts
  packages/@aws-cdk/aws-iam/lib/group.ts
  packages/@aws-cdk/aws-iam/lib/lazy-role.ts
  packages/@aws-cdk/aws-iam/lib/oidc-provider.ts
  packages/@aws-cdk/aws-iam/lib/principals.ts
  packages/@aws-cdk/aws-iam/lib/private/immutable-role.ts
  packages/@aws-cdk/aws-iam/lib/role.ts
  packages/@aws-cdk/aws-iam/lib/user.ts
  packages/@aws-cdk/aws-iam/package.json
  packages/@aws-cdk/aws-iam/test/cross-account.test.ts
  packages/@aws-cdk/aws-iam/test/grant.test.ts
  packages/@aws-cdk/aws-lambda/lib/function-base.ts
  packages/@aws-cdk/aws-route53/test/test.util.ts
  packages/@aws-cdk/aws-s3/lib/bucket.ts
  packages/@aws-cdk/aws-s3/test/test.util.ts
  packages/@aws-cdk/core/lib/arn.ts
  packages/@aws-cdk/core/lib/cfn-pseudo.ts
  packages/@aws-cdk/core/lib/resource.ts
  packages/@aws-cdk/core/lib/token.ts
  packages/@aws-cdk/core/test/test.arn.ts
  packages/@aws-cdk/pipelines/lib/actions/deploy-cdk-stack-action.ts
  packages/@aws-cdk/pipelines/test/cross-environment-infra.test.ts
  packages/@aws-cdk/pipelines/test/integ.pipeline-with-assets.expected.json
  packages/@aws-cdk/pipelines/test/integ.pipeline-with-assets.ts
  packages/@aws-cdk/pipelines/test/integ.pipeline.expected.json
  packages/@aws-cdk/pipelines/test/integ.pipeline.ts
  packages/@aws-cdk/pipelines/test/pipeline.test.ts
Labels: contribution/core

#9737 fix(appsync): add dependency between apikey and schema
  packages/@aws-cdk/aws-appsync/lib/graphqlapi.ts
  packages/@aws-cdk/aws-appsync/test/appsync-apikey.test.ts
  packages/@aws-cdk/aws-appsync/test/integ.api-import.expected.json
  packages/@aws-cdk/aws-appsync/test/integ.graphql-schema.expected.json
  packages/@aws-cdk/aws-appsync/test/integ.graphql.expected.json
Labels: @aws-cdk/aws-appsync

#9850 chore(merge-back): 1.60.0
  CHANGELOG.md
  lerna.json
Labels: pr/no-squash

#9569 feat(region-info): add information for af-south-1 and eu-south-1 regions
  packages/@aws-cdk/region-info/build-tools/aws-entities.ts
  packages/@aws-cdk/region-info/build-tools/fact-tables.ts
  packages/@aws-cdk/region-info/test/__snapshots__/region-info.test.js.snap
Labels: pr-linter/exempt-readme

#9849 fix(cfn-include): allow numbers to be passed to string properties
  packages/@aws-cdk/cloudformation-include/test/test-templates/number-for-string.json
  packages/@aws-cdk/cloudformation-include/test/test-templates/string-for-number.json
  packages/@aws-cdk/cloudformation-include/test/valid-templates.test.ts
  packages/@aws-cdk/core/lib/cfn-parse.ts
Labels: contribution/core

#9798 chore: cleanup awscli-compatible credential loading
  packages/aws-cdk/lib/api/aws-auth/awscli-compatible.ts
Labels: contribution/core

#9585 feat(core): facility to warn when deprecated APIs are used
  packages/@aws-cdk/aws-athena/test/athena.test.ts
  packages/@aws-cdk/aws-autoscaling/lib/auto-scaling-group.ts
  packages/@aws-cdk/aws-autoscaling/test/auto-scaling-group.test.ts
  packages/@aws-cdk/aws-backup/lib/selection.ts
  packages/@aws-cdk/aws-cognito/test/user-pool.test.ts
  packages/@aws-cdk/aws-dynamodb/test/dynamodb.test.ts
  packages/@aws-cdk/aws-dynamodb/test/integ.dynamodb.ondemand.ts
  packages/@aws-cdk/aws-dynamodb/test/integ.dynamodb.sse.ts
  packages/@aws-cdk/aws-dynamodb/test/integ.dynamodb.ts
  packages/@aws-cdk/aws-ec2/lib/instance.ts
  packages/@aws-cdk/aws-ec2/lib/volume.ts
  packages/@aws-cdk/aws-ec2/lib/vpc.ts
  packages/@aws-cdk/aws-ec2/test/volume.test.ts
  packages/@aws-cdk/aws-ec2/test/vpc.test.ts
  packages/@aws-cdk/aws-efs/lib/efs-file-system.ts
  packages/@aws-cdk/aws-efs/test/efs-file-system.test.ts
  packages/@aws-cdk/aws-eks-legacy/lib/cluster.ts
  packages/@aws-cdk/aws-eks/lib/cluster.ts
  packages/@aws-cdk/aws-eks/lib/legacy-cluster.ts
  packages/@aws-cdk/aws-eks/test/test.fargate.ts
  packages/@aws-cdk/aws-kms/test/test.key.ts
  packages/@aws-cdk/aws-route53/test/test.hosted-zone.ts
  packages/@aws-cdk/aws-s3-notifications/test/notifications.test.ts
  packages/@aws-cdk/aws-s3/test/test.aspect.ts
  packages/@aws-cdk/core/lib/annotations.ts
  packages/@aws-cdk/core/lib/construct-compat.ts
  packages/@aws-cdk/core/lib/index.ts
  packages/@aws-cdk/core/lib/tag-aspect.ts
  packages/@aws-cdk/core/test/test.annotations.ts
  packages/@aws-cdk/pipelines/lib/pipeline.ts
  packages/@aws-cdk/pipelines/lib/stage.ts
Labels: contribution/core, pr-linter/exempt-readme

#9831 fix(core): Access Denied using legacy synthesizer with new bootstrap
  packages/@aws-cdk/aws-s3-assets/test/asset.test.ts
  packages/@aws-cdk/aws-s3-deployment/test/bucket-deployment.test.ts
  packages/@aws-cdk/core/lib/assets.ts
  packages/@aws-cdk/core/lib/stack-synthesizers/default-synthesizer.ts
  packages/@aws-cdk/core/test/stack-synthesis/test.new-style-synthesis.ts
  packages/@aws-cdk/pipelines/test/integ.pipeline-with-assets.expected.json
  packages/@aws-cdk/pipelines/test/integ.pipeline.expected.json
  packages/aws-cdk/lib/api/bootstrap/bootstrap-props.ts
  packages/aws-cdk/lib/api/bootstrap/bootstrap-template.yaml
  packages/aws-cdk/lib/api/bootstrap/deploy-bootstrap.ts
  packages/aws-cdk/lib/api/util/cloudformation/stack-activity-monitor.ts
  packages/aws-cdk/test/api/bootstrap2.test.ts
Labels: contribution/core, pr/requires-two-approvers

#9872 fix(bootstrap): add alias for the asset key
  packages/aws-cdk/lib/api/bootstrap/bootstrap-template.yaml
Labels: contribution/core, pr-linter/exempt-test

#9848 chore: update ownership in auto label/assign action
  .github/workflows/issue-label-assign.yml
Labels: contribution/core

#9876 chore: clarify that breaking changes are for experimental APIs
  bump.sh
Labels: contribution/core

#9865 fix(cfn-include): short form for Condition
  packages/@aws-cdk/cloudformation-include/lib/file-utils.ts
  packages/@aws-cdk/cloudformation-include/test/test-templates/yaml/short-form-conditions.yaml
  packages/@aws-cdk/cloudformation-include/test/yaml-templates.test.ts
Labels: contribution/core

#9929 chore: change bootstrap SSM prefix to "cdk-bootstrap"
  packages/@aws-cdk/core/lib/stack-synthesizers/default-synthesizer.ts
  packages/@aws-cdk/core/test/stack-synthesis/test.new-style-synthesis.ts
  packages/@aws-cdk/pipelines/test/integ.pipeline-with-assets.expected.json
  packages/@aws-cdk/pipelines/test/integ.pipeline.expected.json
  packages/aws-cdk/lib/api/bootstrap/bootstrap-template.yaml
Labels: contribution/core

#9936 feat(s3): imported buckets can have an explicit region
  packages/@aws-cdk/aws-s3/README.md
  packages/@aws-cdk/aws-s3/lib/bucket.ts
  packages/@aws-cdk/aws-s3/test/test.bucket.ts
Labels: contribution/core

#9933 chore(elasticloadbalancingv2): Update README for Java naming collision
  packages/@aws-cdk/aws-elasticloadbalancingv2/README.md
Labels: contribution/core

#9887 feat(rds): grantConnect for database instances
  packages/@aws-cdk/aws-rds/README.md
  packages/@aws-cdk/aws-rds/lib/instance.ts
  packages/@aws-cdk/aws-rds/test/test.instance.ts
Labels: contribution/core

#9939 fix(elasticloadbalancingv2): imported listener ignores conditions attribute
  packages/@aws-cdk/aws-elasticloadbalancingv2/lib/alb/application-listener.ts
  packages/@aws-cdk/aws-elasticloadbalancingv2/test/alb/test.listener.ts
Labels: contribution/core

#9871 feat(rds): deletion protection for RDS cluster
  packages/@aws-cdk/aws-rds/lib/cluster.ts
  packages/@aws-cdk/aws-rds/test/test.cluster.ts
Labels: contribution/core, pr-linter/exempt-readme

#9660 feat(appsync): implement resolvable fields for code-first schema
  packages/@aws-cdk/aws-appsync/README.md
  packages/@aws-cdk/aws-appsync/lib/schema-base.ts
  packages/@aws-cdk/aws-appsync/lib/schema-field.ts
  packages/@aws-cdk/aws-appsync/lib/schema-intermediate.ts
  packages/@aws-cdk/aws-appsync/test/appsync-code-first.test.ts
  packages/@aws-cdk/aws-appsync/test/appsync-interface-type.test.ts
  packages/@aws-cdk/aws-appsync/test/appsync-object-type.test.ts
  packages/@aws-cdk/aws-appsync/test/appsync-scalar-type.test.ts
Labels: @aws-cdk/aws-appsync, contribution/core

#9955 chore(ec2): remove unneeded override LookedUpVpc.vpnGatewayId
  packages/@aws-cdk/aws-ec2/lib/vpc.ts
Labels: @aws-cdk/aws-ec2, contribution/core, effort/small

#9313 feat(cli): automatically determine region on EC2 instances
  packages/aws-cdk/lib/api/aws-auth/awscli-compatible.ts
  packages/aws-cdk/lib/api/aws-auth/sdk-provider.ts
  packages/aws-cdk/test/diff.test.ts
  packages/aws-cdk/test/util.ts
  packages/aws-cdk/test/util/awscli-compatible.test.ts
Labels: pr-linter/exempt-readme

#9935 fix(core): Duration incorrectly renders Days
  packages/@aws-cdk/aws-stepfunctions/test/state-transition-metrics.test.ts
  packages/@aws-cdk/aws-stepfunctions/test/task-base.test.ts
  packages/@aws-cdk/aws-stepfunctions/test/task.test.ts
  packages/@aws-cdk/aws-synthetics/test/metric.test.ts
  packages/@aws-cdk/core/lib/duration.ts
  packages/@aws-cdk/core/test/test.duration.ts
Labels: contribution/core

#9928 chore: check format of 'BREAKING CHANGE:' notice
  .github/actions/prlinter/action.yml
  .github/actions/prlinter/index.js
  .github/workflows/pr-linter.yml
  tools/prlint/index.js
Labels: contribution/core

#9967 chore: convert ELB and ELBv2 tests from nodeunit to jest
  packages/@aws-cdk/aws-elasticloadbalancing/.gitignore
  packages/@aws-cdk/aws-elasticloadbalancing/.npmignore
  packages/@aws-cdk/aws-elasticloadbalancing/jest.config.js
  packages/@aws-cdk/aws-elasticloadbalancing/package.json
  packages/@aws-cdk/aws-elasticloadbalancing/test/loadbalancer.test.ts
  packages/@aws-cdk/aws-elasticloadbalancingv2/.gitignore
  packages/@aws-cdk/aws-elasticloadbalancingv2/.npmignore
  packages/@aws-cdk/aws-elasticloadbalancingv2/jest.config.js
  packages/@aws-cdk/aws-elasticloadbalancingv2/package.json
  packages/@aws-cdk/aws-elasticloadbalancingv2/test/alb/actions.test.ts
  packages/@aws-cdk/aws-elasticloadbalancingv2/test/alb/listener.test.ts
  packages/@aws-cdk/aws-elasticloadbalancingv2/test/alb/load-balancer.test.ts
  packages/@aws-cdk/aws-elasticloadbalancingv2/test/alb/security-group.test.ts
  packages/@aws-cdk/aws-elasticloadbalancingv2/test/alb/target-group.test.ts
  packages/@aws-cdk/aws-elasticloadbalancingv2/test/nlb/actions.test.ts
  packages/@aws-cdk/aws-elasticloadbalancingv2/test/nlb/listener.test.ts
  packages/@aws-cdk/aws-elasticloadbalancingv2/test/nlb/load-balancer.test.ts
  packages/@aws-cdk/aws-elasticloadbalancingv2/test/nlb/target-group.test.ts
Labels: contribution/core

#9966 fix(lambda): cannot use latest version in multiple cloudfront distributions
  packages/@aws-cdk/aws-lambda/lib/function-base.ts
  packages/@aws-cdk/aws-lambda/test/test.function.ts
Labels: contribution/core

#9994 chore(logs): update aws-sdk dependency in aws-logs
  packages/@aws-cdk/aws-logs/README.md
  packages/@aws-cdk/aws-logs/package.json
Labels: contribution/core

#9903 feat(appsync): separating schema from graphql api
  packages/@aws-cdk/aws-appsync/README.md
  packages/@aws-cdk/aws-appsync/lib/graphqlapi.ts
  packages/@aws-cdk/aws-appsync/lib/index.ts
  packages/@aws-cdk/aws-appsync/lib/private.ts
  packages/@aws-cdk/aws-appsync/lib/schema-base.ts
  packages/@aws-cdk/aws-appsync/lib/schema.ts
  packages/@aws-cdk/aws-appsync/test/appsync-auth.test.ts
  packages/@aws-cdk/aws-appsync/test/appsync-code-first.test.ts
  packages/@aws-cdk/aws-appsync/test/appsync-dynamodb.test.ts
  packages/@aws-cdk/aws-appsync/test/appsync-grant.test.ts
  packages/@aws-cdk/aws-appsync/test/appsync-http.test.ts
  packages/@aws-cdk/aws-appsync/test/appsync-interface-type.test.ts
  packages/@aws-cdk/aws-appsync/test/appsync-lambda.test.ts
  packages/@aws-cdk/aws-appsync/test/appsync-none.test.ts
  packages/@aws-cdk/aws-appsync/test/appsync-object-type.test.ts
  packages/@aws-cdk/aws-appsync/test/appsync-scalar-type.test.ts
  packages/@aws-cdk/aws-appsync/test/appsync-schema.test.ts
  packages/@aws-cdk/aws-appsync/test/appsync.test.ts
  packages/@aws-cdk/aws-appsync/test/integ.api-import.ts
  packages/@aws-cdk/aws-appsync/test/integ.graphql-iam.ts
  packages/@aws-cdk/aws-appsync/test/integ.graphql-schema.expected.json
  packages/@aws-cdk/aws-appsync/test/integ.graphql-schema.ts
  packages/@aws-cdk/aws-appsync/test/integ.graphql.ts
Labels: @aws-cdk/aws-appsync, contribution/core

#9960 fix(lambda): grantInvoke fails on second invocation
  packages/@aws-cdk/aws-lambda/lib/function-base.ts
  packages/@aws-cdk/aws-lambda/test/test.lambda.ts
Labels: contribution/core

#10005 chore(merge-back): 1.61.0
  CHANGELOG.md
  lerna.json
Labels: pr/no-squash

#9961 fix(redshift): single-node clusters fail with node count error
  packages/@aws-cdk/aws-redshift/lib/cluster.ts
  packages/@aws-cdk/aws-redshift/test/cluster.test.ts
Labels: contribution/core

#9623 feat(cli): control progress output style with --progress=bar|events
  packages/aws-cdk/README.md
  packages/aws-cdk/bin/cdk.ts
  packages/aws-cdk/lib/api/cloudformation-deployments.ts
  packages/aws-cdk/lib/api/deploy-stack.ts
  packages/aws-cdk/lib/api/util/cloudformation/stack-activity-monitor.ts
  packages/aws-cdk/lib/cdk-toolkit.ts
  packages/aws-cdk/lib/settings.ts
Labels: contribution/core, package/tools, pr-linter/exempt-test

#10019 refactor(appsync): abstract schema stringify to utility functions
  packages/@aws-cdk/aws-appsync/lib/private.ts
  packages/@aws-cdk/aws-appsync/lib/schema-intermediate.ts
Labels: @aws-cdk/aws-appsync, contribution/core

#10030 fix(cli): unable to upgrade new style bootstrap to version
  packages/aws-cdk/lib/api/bootstrap/deploy-bootstrap.ts
Labels: contribution/core, package/tools, pr-linter/exempt-test

#10034 chore(release): 1.61.1
  CHANGELOG.md
  lerna.json
  packages/aws-cdk/lib/api/bootstrap/deploy-bootstrap.ts
Labels: contribution/core, pr/no-squash

#10011 feat(rds): custom security groups for OptionGroups
  packages/@aws-cdk/aws-rds/README.md
  packages/@aws-cdk/aws-rds/lib/option-group.ts
  packages/@aws-cdk/aws-rds/test/test.option-group.ts
Labels: contribution/core

#10007 feat(cloudfront): import existing CloudFrontWebDistributions
  packages/@aws-cdk/aws-cloudfront/README.md
  packages/@aws-cdk/aws-cloudfront/lib/web_distribution.ts
  packages/@aws-cdk/aws-cloudfront/test/web_distribution.test.ts
Labels: contribution/core

#10006 fix(cloudfront): Distribution does not add edgelambda trust policy
  packages/@aws-cdk/aws-cloudfront/lib/private/cache-behavior.ts
  packages/@aws-cdk/aws-cloudfront/test/distribution.test.ts
  packages/@aws-cdk/aws-cloudfront/test/integ.distribution-lambda.expected.json
  packages/@aws-cdk/aws-cloudfront/test/integ.distribution-lambda.ts
Labels: contribution/core

#10032 fix(cli): AssumeRole profiles require a [default] profile
  packages/aws-cdk/lib/api/aws-auth/aws-sdk-inifile.ts
  packages/aws-cdk/lib/api/aws-auth/awscli-compatible.ts
  packages/aws-cdk/test/api/sdk-provider.test.ts
Labels: contribution/core

#9957 fix(lambda): grantInvoke fails for imported IAM identities
  packages/@aws-cdk/aws-lambda/lib/function-base.ts
  packages/@aws-cdk/aws-lambda/test/test.lambda.ts
Labels: contribution/core

#10037 chore(monocdk-experiment): `constructs` should NOT be a dependency
  packages/monocdk-experiment/package.json
Labels: contribution/core

#10008 feat(cloudfront): support includeBody for Lambda@Edge
  packages/@aws-cdk/aws-cloudfront/README.md
  packages/@aws-cdk/aws-cloudfront/lib/distribution.ts
  packages/@aws-cdk/aws-cloudfront/lib/private/cache-behavior.ts
  packages/@aws-cdk/aws-cloudfront/lib/web_distribution.ts
  packages/@aws-cdk/aws-cloudfront/test/distribution.test.ts
  packages/@aws-cdk/aws-cloudfront/test/private/cache-behavior.test.ts
  packages/@aws-cdk/aws-cloudfront/test/web_distribution.test.ts
Labels: contribution/core

#10038 chore(merge-back): 1.61.1
  CHANGELOG.md
  lerna.json
Labels: pr/no-squash

#9992 feat(appsync): support query & mutation generation for code-first approach
  packages/@aws-cdk/aws-appsync/README.md
  packages/@aws-cdk/aws-appsync/lib/graphqlapi.ts
  packages/@aws-cdk/aws-appsync/lib/schema.ts
  packages/@aws-cdk/aws-appsync/test/appsync-schema.test.ts
  packages/@aws-cdk/aws-appsync/test/appsync.test.graphql
  packages/@aws-cdk/aws-appsync/test/integ.api-import.expected.json
  packages/@aws-cdk/aws-appsync/test/integ.graphql-schema.expected.json
  packages/@aws-cdk/aws-appsync/test/integ.graphql-schema.ts
  packages/@aws-cdk/aws-appsync/test/scalar-type-defintions.ts
  packages/@aws-cdk/aws-appsync/test/verify.integ.graphql-schema.sh
Labels: @aws-cdk/aws-appsync, contribution/core

#9886 feat(bootstrap): customizable bootstrap template
  packages/@aws-cdk/custom-resources/test/aws-custom-resource/aws-custom-resource-provider.test.ts
  packages/aws-cdk/CONTRIBUTING.md
  packages/aws-cdk/README.md
  packages/aws-cdk/bin/cdk.ts
  packages/aws-cdk/lib/api/bootstrap/bootstrap-environment.ts
  packages/aws-cdk/lib/api/bootstrap/bootstrap-props.ts
  packages/aws-cdk/lib/api/bootstrap/deploy-bootstrap.ts
  packages/aws-cdk/lib/cdk-toolkit.ts
  packages/aws-cdk/test/api/bootstrap.test.ts
  packages/aws-cdk/test/api/bootstrap2.test.ts
  packages/aws-cdk/test/cdk-toolkit.test.ts
  packages/aws-cdk/test/integ/cli/bootstrapping.integtest.ts
Labels: contribution/core

#10024 feat(appsync): support Input Types for code-first approach
  packages/@aws-cdk/aws-appsync/README.md
  packages/@aws-cdk/aws-appsync/lib/schema-base.ts
  packages/@aws-cdk/aws-appsync/lib/schema-intermediate.ts
  packages/@aws-cdk/aws-appsync/lib/schema.ts
  packages/@aws-cdk/aws-appsync/test/appsync-code-first.test.ts
  packages/@aws-cdk/aws-appsync/test/appsync-input-types.test.ts
  packages/@aws-cdk/aws-appsync/test/appsync-interface-type.test.ts
  packages/@aws-cdk/aws-appsync/test/appsync-object-type.test.ts
  packages/@aws-cdk/aws-appsync/test/integ.graphql-schema.expected.json
  packages/@aws-cdk/aws-appsync/test/integ.graphql-schema.ts
Labels: @aws-cdk/aws-appsync, contribution/core
