Repository aws/aws-cdk, pull requests merged in 2021-07, with the labels that each got.

#15348 fix(pipelines): artifact bucket permissions missing for in-account deployments
  packages/@aws-cdk/aws-iam/lib/private/immutable-role.ts
  packages/@aws-cdk/aws-iam/lib/role.ts
  packages/@aws-cdk/aws-iam/test/role.from-role-arn.test.ts
  packages/@aws-cdk/pipelines/lib/actions/deploy-cdk-stack-action.ts
  packages/@aws-cdk/pipelines/test/cross-environment-infra.test.ts
  packages/@aws-cdk/pipelines/test/integ.pipeline-with-assets-single-upload.expected.json
  packages/@aws-cdk/pipelines/test/integ.pipeline-with-assets.expected.json
  packages/@aws-cdk/pipelines/test/integ.pipeline.expected.json
Labels: contribution/core

#15332 feat(codebuild): improve merging of BuildSpecs
  packages/@aws-cdk/aws-codebuild/lib/build-spec.ts
  packages/@aws-cdk/aws-codebuild/test/test.build-spec.ts
Labels: pr-linter/exempt-readme

#15380 fix(core): unresolved tokens in generated nested stack outputs
  packages/@aws-cdk/aws-cloudformation/test/test.nested-stack.ts
  packages/@aws-cdk/core/lib/private/refs.ts
Labels: contribution/core

#15055 chore(nodejs-lambda): option to override project root
  packages/@aws-cdk/aws-lambda-nodejs/lib/bundling.ts
  packages/@aws-cdk/aws-lambda-nodejs/lib/function.ts
  packages/@aws-cdk/aws-lambda-nodejs/test/bundling.test.ts
Labels: @aws-cdk/aws-lambda-nodejs

#15386 docs: disable strict compilation for failing modules
  packages/@aws-cdk/aws-iam/package.json
  packages/@aws-cdk/core/package.json
Labels: contribution/core

#15374 feat(cli): add option --security-only to diff
  packages/aws-cdk/bin/cdk.ts
  packages/aws-cdk/lib/cdk-toolkit.ts
  packages/aws-cdk/lib/util/bool.ts
  packages/aws-cdk/lib/util/index.ts
  packages/aws-cdk/test/integ/cli/cli.integtest.ts
Labels: contribution/core, package/tools, pr-linter/exempt-readme

#15396 chore(merge-back): 1.111.0
  CHANGELOG.md
  version.v1.json
Labels: pr/auto-approve, pr/no-squash

#15364 feat(pipelines): Docker registry credentials
  packages/@aws-cdk/pipelines/README.md
  packages/@aws-cdk/pipelines/lib/actions/update-pipeline-action.ts
  packages/@aws-cdk/pipelines/lib/docker-credentials.ts
  packages/@aws-cdk/pipelines/lib/index.ts
  packages/@aws-cdk/pipelines/lib/pipeline.ts
  packages/@aws-cdk/pipelines/lib/synths/simple-synth-action.ts
  packages/@aws-cdk/pipelines/package.json
  packages/@aws-cdk/pipelines/test/docker-credentials.test.ts
  packages/@aws-cdk/pipelines/test/integ.pipeline-with-assets-single-upload.expected.json
  packages/@aws-cdk/pipelines/test/integ.pipeline-with-assets.expected.json
  packages/@aws-cdk/pipelines/test/integ.pipeline.expected.json
  packages/@aws-cdk/pipelines/test/pipeline-assets.test.ts
  packages/@aws-cdk/pipelines/test/pipeline.test.ts
  packages/@aws-cdk/pipelines/test/testutil.ts
Labels: contribution/core

#15405 docs(pipeline): document work-arounds for when bootstrap stack has been recreated
  packages/@aws-cdk/pipelines/README.md
Labels: contribution/core

#15387 feat(cloudwatch): allow arbitrary statistics in Metric and Alarm
  packages/@aws-cdk/aws-cloudwatch/lib/private/statistic.ts
  packages/@aws-cdk/aws-cloudwatch/test/test.metrics.ts
Labels: contribution/core, pr-linter/exempt-readme

#15409 fix(cfnspec): .npmignore generated by cfnspec does not pass pkglint
  packages/@aws-cdk/cfnspec/build-tools/create-missing-libraries.ts
Labels: contribution/core, pr-linter/exempt-test

#15401 fix(pipelines): unable to add assets stage to existing VPC pipeline
  packages/@aws-cdk/pipelines/lib/actions/publish-assets-action.ts
  packages/@aws-cdk/pipelines/lib/pipeline.ts
  packages/@aws-cdk/pipelines/test/pipeline-assets.test.ts
Labels: contribution/core

#15207 fix(cli): prevent 'Failed resources:' message when no failures and report all progress steps
  packages/aws-cdk/lib/api/util/cloudformation/stack-activity-monitor.ts
  packages/aws-cdk/test/api/console-listener.ts
  packages/aws-cdk/test/api/stack-activity-monitor.test.ts
Labels: package/tools

#15201 chore(build): build no longer fails if there are multiple dotnet versions installed
  scripts/check-build-prerequisites.sh
  scripts/check-pack-prerequisites.sh
Labels: package/tools

#15204 feat(core): add docker security option to asset bundling
  packages/@aws-cdk/core/lib/asset-staging.ts
  packages/@aws-cdk/core/lib/bundling.ts
  packages/@aws-cdk/core/test/staging.test.ts
Labels: @aws-cdk/core, pr-linter/exempt-readme

#15240 feat(ec2): add rds-data vpc endpoint
  packages/@aws-cdk/aws-ec2/lib/vpc-endpoint.ts
  packages/@aws-cdk/aws-ec2/package.json
Labels: pr-linter/exempt-readme, pr-linter/exempt-test

#15424 feat(acm): DaysToExpiry metric
  packages/@aws-cdk/aws-certificatemanager/README.md
  packages/@aws-cdk/aws-certificatemanager/lib/certificate-base.ts
  packages/@aws-cdk/aws-certificatemanager/lib/certificate.ts
  packages/@aws-cdk/aws-certificatemanager/lib/dns-validated-certificate.ts
  packages/@aws-cdk/aws-certificatemanager/package.json
  packages/@aws-cdk/aws-certificatemanager/test/certificate.test.ts
  yarn.lock
Labels: contribution/core

#15435 fix(build): explicit non-private package not respected in packaging
  tools/cdk-build-tools/lib/package-info.ts
Labels: contribution/core, pr-linter/exempt-test

#15331 chore: new private 'cdk-release' tool for performing releases
  bump.sh
  scripts/bump.js
  tools/cdk-release/.eslintrc.js
  tools/cdk-release/.gitignore
  tools/cdk-release/.npmignore
  tools/cdk-release/LICENSE
  tools/cdk-release/NOTICE
  tools/cdk-release/README.md
  tools/cdk-release/jest.config.js
  tools/cdk-release/lib/conventional-commits.ts
  tools/cdk-release/lib/defaults.ts
  tools/cdk-release/lib/index.ts
  tools/cdk-release/lib/lifecycles/bump.ts
  tools/cdk-release/lib/lifecycles/changelog.ts
  tools/cdk-release/lib/lifecycles/commit.ts
  tools/cdk-release/lib/private/files.ts
  tools/cdk-release/lib/private/print.ts
  tools/cdk-release/lib/private/run-exec-file.ts
  tools/cdk-release/lib/types.ts
  tools/cdk-release/lib/updaters/index.ts
  tools/cdk-release/lib/updaters/types/json.ts
  tools/cdk-release/lib/updaters/types/plain-text.ts
  tools/cdk-release/package.json
  tools/cdk-release/test/changelog.test.ts
  tools/cdk-release/tsconfig.json
Labels: contribution/core

#15445 chore(release): 2.0.0-rc.11
  CHANGELOG.v2.md
  version.v2.json
Labels: pr/auto-approve

#15429 fix(codebuild): merge spec correctly when using strings
  packages/@aws-cdk/aws-codebuild/lib/build-spec.ts
  packages/@aws-cdk/aws-codebuild/test/test.build-spec.ts
Labels: @aws-cdk/aws-codebuild

#15356 fix(pipelines): singlePublisherPerType overwrites assets buildspec file of other pipelines
  packages/@aws-cdk/pipelines/lib/actions/publish-assets-action.ts
  packages/@aws-cdk/pipelines/test/integ.pipeline-with-assets-single-upload.expected.json
  packages/@aws-cdk/pipelines/test/pipeline-assets.test.ts
Labels: @aws-cdk/pipelines

#15410 fix(lambda-nodejs): pnpm exec args separator order
  packages/@aws-cdk/aws-lambda-nodejs/lib/package-manager.ts
  packages/@aws-cdk/aws-lambda-nodejs/test/package-manager.test.ts
Labels: @aws-cdk/aws-lambda-nodejs

#15430 fix(iam): set principalAccount in AccountPrincipal and PrincipalWithConditions
  packages/@aws-cdk/aws-iam/lib/principals.ts
  packages/@aws-cdk/aws-iam/test/principals.test.ts
Labels: @aws-cdk/aws-iam

#15376 fix(events): Archive event pattern fields are not translated correctly
  packages/@aws-cdk/aws-events/lib/archive.ts
  packages/@aws-cdk/aws-events/lib/rule.ts
  packages/@aws-cdk/aws-events/lib/util.ts
  packages/@aws-cdk/aws-events/test/test.archive.ts
Labels: @aws-cdk/aws-events

#15345 fix(autoscaling): scaling intervals are incorrect if the bottom one does not start at 0
  packages/@aws-cdk/aws-autoscaling-common/lib/interval-utils.ts
  packages/@aws-cdk/aws-autoscaling-common/test/test.intervals.ts
Labels: @aws-cdk/aws-autoscaling-common

#15308 feat(events): DLQ and retry policy support for BatchJob target
  packages/@aws-cdk/aws-events-targets/README.md
  packages/@aws-cdk/aws-events-targets/lib/batch.ts
  packages/@aws-cdk/aws-events-targets/lib/kinesis-stream.ts
  packages/@aws-cdk/aws-events-targets/lib/sns.ts
  packages/@aws-cdk/aws-events-targets/lib/sqs.ts
  packages/@aws-cdk/aws-events-targets/lib/withRepoAndKinesisStream.ts-fixture
  packages/@aws-cdk/aws-events-targets/rosetta/default.ts-fixture
  packages/@aws-cdk/aws-events-targets/rosetta/withRepoAndKinesisStream.ts-fixture
  packages/@aws-cdk/aws-events-targets/rosetta/withRepoAndSqsQueue.ts-fixture
  packages/@aws-cdk/aws-events-targets/rosetta/withRepoAndTopic.ts-fixture
  packages/@aws-cdk/aws-events-targets/test/batch/batch.test.ts
  packages/@aws-cdk/aws-events-targets/test/batch/integ.job-definition-events.expected.json
  packages/@aws-cdk/aws-events-targets/test/batch/integ.job-definition-events.ts
Labels: @aws-cdk/aws-events-targets

#15248 fix(iam): remove incorrect normalization of principal
  packages/@aws-cdk/aws-apigateway/test/integ.restapi.vpc-endpoint.expected.json
  packages/@aws-cdk/aws-backup/test/vault.test.ts
  packages/@aws-cdk/aws-cloudfront/test/integ.cloudfront-custom-s3.expected.json
  packages/@aws-cdk/aws-ec2/test/integ.vpc-endpoint.lit.expected.json
  packages/@aws-cdk/aws-ec2/test/vpc-endpoint.test.ts
  packages/@aws-cdk/aws-ecr/test/repository.test.ts
  packages/@aws-cdk/aws-elasticsearch/test/elasticsearch-access-policy.test.ts
  packages/@aws-cdk/aws-elasticsearch/test/integ.elasticsearch.custom-kms-key.expected.json
  packages/@aws-cdk/aws-elasticsearch/test/integ.elasticsearch.expected.json
  packages/@aws-cdk/aws-elasticsearch/test/integ.elasticsearch.unsignedbasicauth.expected.json
  packages/@aws-cdk/aws-iam/lib/policy-statement.ts
  packages/@aws-cdk/aws-iam/test/policy-document.test.ts
  packages/@aws-cdk/aws-kms/test/key.test.ts
  packages/@aws-cdk/aws-kms/test/via-service-principal.test.ts
  packages/@aws-cdk/aws-msk/test/cluster.test.ts
  packages/@aws-cdk/aws-s3/test/bucket-policy.test.ts
  packages/@aws-cdk/aws-s3/test/bucket.test.ts
Labels: @aws-cdk/aws-iam

#15302 feat(autoscaling): ScalingEvents.TERMINATION_EVENTS
  packages/@aws-cdk/aws-autoscaling/lib/auto-scaling-group.ts
Labels: @aws-cdk/aws-autoscaling, pr-linter/exempt-readme, pr-linter/exempt-test

#15461 revert(migration): add constructs migration to rewrite script
  packages/aws-cdk-migration/README.md
  packages/aws-cdk-migration/lib/rewrite.ts
  packages/aws-cdk-migration/test/rewrite.test.ts
Labels: contribution/core

#15467 chore(cdk-release): do not get commits if Changelog generation is skipped
  tools/cdk-release/lib/conventional-commits.ts
  tools/cdk-release/lib/index.ts
  tools/cdk-release/test/changelog.test.ts
Labels: contribution/core

#15486 chore(merge-back): 1.112.0
  CHANGELOG.md
  version.v1.json
Labels: pr/auto-approve, pr/no-squash

#15442 chore: add build of experimental modules
  packages/@aws-cdk-lib/.gitignore
  packages/@aws-cdk-lib/README.md
  packages/@aws-cdk-lib/gen.js
  packages/@aws-cdk-lib/lerna.json
  packages/@aws-cdk-lib/package.json
  packages/@aws-cdk/assertions/package.json
  packages/@aws-cdk/aws-lambda-go/package.json
  packages/@aws-cdk/aws-lambda-python/package.json
  packages/@aws-cdk/aws-synthetics/package.json
  packages/@aws-cdk/example-construct-library/package.json
  packages/aws-cdk-migration/lib/rewrite.ts
  tools/pkglint/lib/rules.ts
  tools/pkglint/lib/util.ts
Labels: contribution/core

#15438 feat(assets): docker images from tar file
  packages/@aws-cdk/aws-ecr-assets/README.md
  packages/@aws-cdk/aws-ecr-assets/lib/index.ts
  packages/@aws-cdk/aws-ecr-assets/lib/tarball-asset.ts
  packages/@aws-cdk/aws-ecr-assets/test/demo-tarball/empty.tar
  packages/@aws-cdk/aws-ecr-assets/test/tarball-asset.test.ts
  packages/@aws-cdk/aws-ecs/README.md
  packages/@aws-cdk/aws-ecs/lib/container-image.ts
Labels: @aws-cdk/assets

#14731 feat(events): cross-region event rules
  packages/@aws-cdk/aws-events-targets/lib/util.ts
  packages/@aws-cdk/aws-events/README.md
  packages/@aws-cdk/aws-events/lib/rule.ts
  packages/@aws-cdk/aws-events/lib/util.ts
  packages/@aws-cdk/aws-events/test/test.rule.ts
Labels: @aws-cdk/aws-events

#15511 chore(release): 1.113.0
  CHANGELOG.md
  packages/@aws-cdk/aws-codepipeline-actions/README.md
  packages/@aws-cdk/aws-codepipeline-actions/lib/codebuild/build-action.ts
  packages/@aws-cdk/aws-codepipeline-actions/test/codebuild/codebuild-action.test.ts
  packages/@aws-cdk/aws-ecr-assets/README.md
  packages/@aws-cdk/aws-ecr-assets/lib/index.ts
  packages/@aws-cdk/aws-ecr-assets/lib/tarball-asset.ts
  packages/@aws-cdk/aws-ecr-assets/test/demo-tarball/empty.tar
  packages/@aws-cdk/aws-ecr-assets/test/tarball-asset.test.ts
  packages/@aws-cdk/aws-ecs/README.md
  packages/@aws-cdk/aws-ecs/lib/container-image.ts
  packages/@aws-cdk/aws-ecs/lib/log-drivers/splunk-log-driver.ts
  packages/@aws-cdk/aws-ecs/test/splunk-log-driver.test.ts
  packages/@aws-cdk/aws-events-targets/lib/util.ts
  packages/@aws-cdk/aws-events/README.md
  packages/@aws-cdk/aws-events/lib/rule.ts
  packages/@aws-cdk/aws-events/lib/util.ts
  packages/@aws-cdk/aws-events/test/test.rule.ts
  version.v1.json
Labels: pr/no-squash

#15514 chore(merge-back): 1.113.0
  CHANGELOG.md
  version.v1.json
Labels: pr/auto-approve, pr/no-squash

#14931 feat(aws-ecs): New CDK constructs for ECS Anywhere task and service definitions
  packages/@aws-cdk/aws-ecs/README.md
  packages/@aws-cdk/aws-ecs/lib/external/external-service.ts
  packages/@aws-cdk/aws-ecs/lib/external/external-task-definition.ts
  packages/@aws-cdk/aws-ecs/lib/index.ts
  packages/@aws-cdk/aws-ecs/package.json
  packages/@aws-cdk/aws-ecs/test/external/external-service.test.ts
  packages/@aws-cdk/aws-ecs/test/external/external-task-definition.test.ts
Labels: @aws-cdk/aws-ecs

#15535 chore(release): 2.0.0-rc.12
  CHANGELOG.v2.md
  version.v2.json
Labels: pr/auto-approve

#15423 feat(bootstrap): widen lookup role permissions for future extension
  packages/aws-cdk/lib/api/bootstrap/bootstrap-template.yaml
Labels: contribution/core, pr-linter/exempt-readme, pr-linter/exempt-test

#15538 chore(cli): improve error message when bootstrap can't find stacks
  packages/aws-cdk/lib/cdk-toolkit.ts
Labels: contribution/core

#15452 feat(servicecatalog): Add portfolio-product association and tag update constraint
  packages/@aws-cdk/aws-servicecatalog/README.md
  packages/@aws-cdk/aws-servicecatalog/lib/common.ts
  packages/@aws-cdk/aws-servicecatalog/lib/constraints.ts
  packages/@aws-cdk/aws-servicecatalog/lib/index.ts
  packages/@aws-cdk/aws-servicecatalog/lib/portfolio.ts
  packages/@aws-cdk/aws-servicecatalog/lib/private/association-manager.ts
  packages/@aws-cdk/aws-servicecatalog/lib/product.ts
  packages/@aws-cdk/aws-servicecatalog/rosetta/portfolio-product.ts-fixture
  packages/@aws-cdk/aws-servicecatalog/test/integ.portfolio.expected.json
  packages/@aws-cdk/aws-servicecatalog/test/integ.portfolio.ts
  packages/@aws-cdk/aws-servicecatalog/test/portfolio.test.ts
Labels: @aws-cdk/aws-servicecatalog

#15560 feat(appmesh): the App Mesh Construct Library is now Generally Available (stable)
  packages/@aws-cdk/aws-appmesh/README.md
  packages/@aws-cdk/aws-appmesh/package.json
Labels: pr-linter/exempt-test

#15570 chore(merge-back): 1.114.0
  CHANGELOG.md
  version.v1.json
Labels: pr/auto-approve, pr/no-squash

#14999 feat(aws-efs): grant support on FileSystem
  packages/@aws-cdk/aws-efs/README.md
  packages/@aws-cdk/aws-efs/lib/efs-file-system.ts
  packages/@aws-cdk/aws-efs/package.json
  packages/@aws-cdk/aws-efs/test/efs-file-system.test.ts
Labels: @aws-cdk/aws-efs

#15526 fix(cfnspec): make EndpointConfiguration of AWS::Serverless::Api a union type
  packages/@aws-cdk/aws-sam/test/api.test.ts
  packages/@aws-cdk/cfnspec/spec-source/901_SAM_Api_EndpointConfiguration_patch.json
  packages/@aws-cdk/cloudformation-include/test/serverless-transform.test.ts
  packages/@aws-cdk/cloudformation-include/test/test-templates/sam/api-endpoint-config-object.yaml
  packages/@aws-cdk/cloudformation-include/test/test-templates/sam/api-endpoint-config-string-empty.yaml
  packages/@aws-cdk/cloudformation-include/test/test-templates/sam/api-endpoint-config-string.yaml
  tools/cfn2ts/lib/codegen.ts
Labels: contribution/core

#15565 chore(cli): tests that apply only to v1 are failing when building for v2
  packages/aws-cdk/test/api/cloud-assembly.test.ts
  packages/aws-cdk/test/cdk-toolkit.test.ts
Labels: contribution/core

#15580 chore(kms): cross-stack usage detection depends on NPM tree
  packages/@aws-cdk/aws-kms/lib/key.ts
Labels: contribution/core

#15600 fix(pipelines): unresolved source names aren't handled properly
  packages/@aws-cdk/aws-codepipeline/lib/private/stage.ts
  packages/@aws-cdk/pipelines/lib/blueprint/step.ts
  packages/@aws-cdk/pipelines/lib/codepipeline/codepipeline-source.ts
  packages/@aws-cdk/pipelines/test/codepipeline/codepipeline-sources.test.ts
Labels: contribution/core

#15599 chore: add license notice, remove Docker instructions
  CONTRIBUTING.md
  Dockerfile
Labels: contribution/core

#15603 fix(cli): `cdk deploy` is listing deprecated ids
  packages/aws-cdk/lib/api/cxapp/cloud-assembly.ts
  packages/aws-cdk/test/api/cloud-assembly.test.ts
Labels: contribution/core

#15545 feat(aws-kinesisfirehose): specific metrics functions for DeliveryStream
  packages/@aws-cdk/aws-kinesisfirehose/README.md
  packages/@aws-cdk/aws-kinesisfirehose/lib/delivery-stream.ts
  packages/@aws-cdk/aws-kinesisfirehose/test/delivery-stream.test.ts
Labels: contribution/core

#15441 feat(pipelines): confirm IAM changes before starting the deployment
  package.json
  packages/@aws-cdk/pipelines/ORIGINAL_API.md
  packages/@aws-cdk/pipelines/README.md
  packages/@aws-cdk/pipelines/lib/codepipeline/codepipeline-action-factory.ts
  packages/@aws-cdk/pipelines/lib/codepipeline/confirm-permissions-broadening.ts
  packages/@aws-cdk/pipelines/lib/codepipeline/index.ts
  packages/@aws-cdk/pipelines/lib/legacy/pipeline.ts
  packages/@aws-cdk/pipelines/lib/legacy/stage.ts
  packages/@aws-cdk/pipelines/lib/main/pipeline-base.ts
  packages/@aws-cdk/pipelines/lib/private/application-security-check.ts
  packages/@aws-cdk/pipelines/lib/private/approve-lambda/index.ts
  packages/@aws-cdk/pipelines/package.json
  packages/@aws-cdk/pipelines/test/compliance/security-check.test.ts
  packages/@aws-cdk/pipelines/test/integ.pipeline-security.expected.json
  packages/@aws-cdk/pipelines/test/integ.pipeline-security.ts
Labels: @aws-cdk/pipelines, contribution/core, feature/enhancement

#15227 feat(apigatewayv2): websocket - callback url
  packages/@aws-cdk/aws-apigatewayv2/README.md
  packages/@aws-cdk/aws-apigatewayv2/lib/websocket/stage.ts
  packages/@aws-cdk/aws-apigatewayv2/test/websocket/stage.test.ts
Labels: @aws-cdk/aws-apigatewayv2

#15604 feat(cli): add ability to specify an external id for the deploy-role
  packages/@aws-cdk/cloud-assembly-schema/lib/cloud-assembly/artifact-schema.ts
  packages/@aws-cdk/cloud-assembly-schema/schema/cloud-assembly.schema.json
  packages/@aws-cdk/cloud-assembly-schema/schema/cloud-assembly.version.json
  packages/@aws-cdk/core/lib/stack-synthesizers/default-synthesizer.ts
  packages/@aws-cdk/core/lib/stack-synthesizers/stack-synthesizer.ts
  packages/@aws-cdk/core/test/stack-synthesis/new-style-synthesis.test.ts
  packages/@aws-cdk/cx-api/lib/artifacts/cloudformation-artifact.ts
  packages/aws-cdk/lib/api/cloudformation-deployments.ts
Labels: pr-linter/exempt-readme

#15633 chore: some cli tests still rely on legacy behavior and fail in v2
  packages/aws-cdk/lib/api/cxapp/cloud-assembly.ts
  packages/aws-cdk/test/api/cloud-assembly.test.ts
Labels: contribution/core

#15606 chore: migrate sns, lambda-event-sources, cloudwatch to jest
  packages/@aws-cdk/aws-apigatewayv2-integrations/package.json
  packages/@aws-cdk/aws-cloudwatch/.gitignore
  packages/@aws-cdk/aws-cloudwatch/.npmignore
  packages/@aws-cdk/aws-cloudwatch/jest.config.js
  packages/@aws-cdk/aws-cloudwatch/package.json
  packages/@aws-cdk/aws-cloudwatch/test/alarm-status-widget.test.ts
  packages/@aws-cdk/aws-cloudwatch/test/alarm.test.ts
  packages/@aws-cdk/aws-cloudwatch/test/composite-alarm.test.ts
  packages/@aws-cdk/aws-cloudwatch/test/cross-environment.test.ts
  packages/@aws-cdk/aws-cloudwatch/test/dashboard.test.ts
  packages/@aws-cdk/aws-cloudwatch/test/graphs.test.ts
  packages/@aws-cdk/aws-cloudwatch/test/layout.test.ts
  packages/@aws-cdk/aws-cloudwatch/test/metric-math.test.ts
  packages/@aws-cdk/aws-cloudwatch/test/metrics.test.ts
  packages/@aws-cdk/aws-lambda-event-sources/.gitignore
  packages/@aws-cdk/aws-lambda-event-sources/.npmignore
  packages/@aws-cdk/aws-lambda-event-sources/jest.config.js
  packages/@aws-cdk/aws-lambda-event-sources/package.json
  packages/@aws-cdk/aws-lambda-event-sources/test/api.test.ts
  packages/@aws-cdk/aws-lambda-event-sources/test/dynamo.test.ts
  packages/@aws-cdk/aws-lambda-event-sources/test/kafka.test.ts
  packages/@aws-cdk/aws-lambda-event-sources/test/kinesis.test.ts
  packages/@aws-cdk/aws-lambda-event-sources/test/s3.test.ts
  packages/@aws-cdk/aws-lambda-event-sources/test/sns.test.ts
  packages/@aws-cdk/aws-lambda-event-sources/test/sqs.test.ts
  packages/@aws-cdk/aws-sns/.gitignore
  packages/@aws-cdk/aws-sns/.npmignore
  packages/@aws-cdk/aws-sns/jest.config.js
  packages/@aws-cdk/aws-sns/package.json
  packages/@aws-cdk/aws-sns/test/sns.test.ts
  packages/@aws-cdk/aws-sns/test/subscription.test.ts
  packages/@aws-cdk/aws-sns/test/test.sns.ts
Labels: contribution/core

#15634 chore: forward merge 'master' into 'v2-main'
  packages/aws-cdk/lib/api/cxapp/cloud-assembly.ts
  packages/aws-cdk/test/api/cloud-assembly.test.ts
Labels: pr/auto-approve, pr/forward-merge, pr/no-squash

#15414 fix(iam): `PrincipalWithConditions.addCondition` does not work
  packages/@aws-cdk/aws-iam/lib/principals.ts
  packages/@aws-cdk/aws-iam/test/principals.test.ts
Labels: @aws-cdk/aws-iam

#15640 chore: forward merge 'master' into 'v2-main'
  packages/@aws-cdk/aws-apigatewayv2-integrations/package.json
  packages/@aws-cdk/aws-cloudwatch/.gitignore
  packages/@aws-cdk/aws-cloudwatch/.npmignore
  packages/@aws-cdk/aws-cloudwatch/jest.config.js
  packages/@aws-cdk/aws-cloudwatch/package.json
  packages/@aws-cdk/aws-cloudwatch/test/alarm-status-widget.test.ts
  packages/@aws-cdk/aws-cloudwatch/test/alarm.test.ts
  packages/@aws-cdk/aws-cloudwatch/test/composite-alarm.test.ts
  packages/@aws-cdk/aws-cloudwatch/test/cross-environment.test.ts
  packages/@aws-cdk/aws-cloudwatch/test/dashboard.test.ts
  packages/@aws-cdk/aws-cloudwatch/test/graphs.test.ts
  packages/@aws-cdk/aws-cloudwatch/test/layout.test.ts
  packages/@aws-cdk/aws-cloudwatch/test/metric-math.test.ts
  packages/@aws-cdk/aws-cloudwatch/test/metrics.test.ts
  packages/@aws-cdk/aws-lambda-event-sources/.gitignore
  packages/@aws-cdk/aws-lambda-event-sources/.npmignore
  packages/@aws-cdk/aws-lambda-event-sources/jest.config.js
  packages/@aws-cdk/aws-lambda-event-sources/package.json
  packages/@aws-cdk/aws-lambda-event-sources/test/api.test.ts
  packages/@aws-cdk/aws-lambda-event-sources/test/dynamo.test.ts
  packages/@aws-cdk/aws-lambda-event-sources/test/kafka.test.ts
  packages/@aws-cdk/aws-lambda-event-sources/test/kinesis.test.ts
  packages/@aws-cdk/aws-lambda-event-sources/test/s3.test.ts
  packages/@aws-cdk/aws-lambda-event-sources/test/sns.test.ts
  packages/@aws-cdk/aws-lambda-event-sources/test/sqs.test.ts
  packages/@aws-cdk/aws-sns/.gitignore
  packages/@aws-cdk/aws-sns/.npmignore
  packages/@aws-cdk/aws-sns/jest.config.js
  packages/@aws-cdk/aws-sns/package.json
  packages/@aws-cdk/aws-sns/test/sns.test.ts
  packages/@aws-cdk/aws-sns/test/subscription.test.ts
  packages/@aws-cdk/aws-sns/test/test.sns.ts
Labels: pr/auto-approve, pr/forward-merge, pr/no-squash

#15644 docs(pipelines): explain 'no matching base directory' error
  packages/@aws-cdk/pipelines/README.md
Labels: contribution/core

#15643 chore(pipelines): new tests for CodePipelineSource
  packages/@aws-cdk/pipelines/lib/codepipeline/codepipeline-source.ts
  packages/@aws-cdk/pipelines/test/codepipeline/codepipeline-sources.test.ts
Labels: contribution/core

#15648 chore: fix versions of inner dependencies in @aws-cdk-lib
  packages/@aws-cdk-lib/gen.js
Labels: contribution/core

#15283 feat(appsync): optional operation parameter for lambdaRequest mapping template
  packages/@aws-cdk/aws-appsync/.gitignore
  packages/@aws-cdk/aws-appsync/lib/mapping-template.ts
  packages/@aws-cdk/aws-appsync/test/appsync-lambda.test.ts
  packages/@aws-cdk/aws-appsync/test/appsync-mapping-template.test.ts
  packages/@aws-cdk/aws-appsync/test/appsync-object-type.test.ts
  packages/@aws-cdk/aws-appsync/test/appsync.lambda.graphql
  packages/@aws-cdk/aws-appsync/test/integ.appsync-lambda.expected.json
  packages/@aws-cdk/aws-appsync/test/integ.appsync-lambda.ts
  packages/@aws-cdk/aws-appsync/test/integ.graphql-iam.ts
  packages/@aws-cdk/aws-appsync/test/verify.integ.appsync-lambda.sh
  packages/@aws-cdk/aws-appsync/test/verify/iam-query/iam-query.js
  packages/@aws-cdk/aws-appsync/test/verify/lambda-tutorial/lambda-tutorial.js
Labels: @aws-cdk/aws-appsync, contribution/core, feature/enhancement, pr-linter/exempt-readme

#15657 chore(release): 2.0.0-rc.13
  CHANGELOG.v2.md
  version.v2.json
Labels: pr/auto-approve

#15660 fix(pipelines): permissions check in legacy API does not work
  packages/@aws-cdk/pipelines/lib/legacy/stage.ts
  packages/@aws-cdk/pipelines/test/compliance/security-check.test.ts
  packages/@aws-cdk/pipelines/test/integ.pipeline-security.expected.json
Labels: contribution/core

#15663 docs(pipelines): describe context lookups
  packages/@aws-cdk/pipelines/README.md
Labels: contribution/core

#15665 fix(pipelines): new pipeline stages aren't validated
  packages/@aws-cdk/pipelines/lib/blueprint/stage-deployment.ts
  packages/@aws-cdk/pipelines/lib/legacy/stage.ts
  packages/@aws-cdk/pipelines/lib/private/construct-internals.ts
  packages/@aws-cdk/pipelines/test/compliance/synths.test.ts
Labels: contribution/core

#15469 feat(apigatewayv2-integrations): http private integrations - tls config
  packages/@aws-cdk/aws-apigatewayv2-integrations/lib/http/alb.ts
  packages/@aws-cdk/aws-apigatewayv2-integrations/lib/http/base-types.ts
  packages/@aws-cdk/aws-apigatewayv2-integrations/lib/http/nlb.ts
  packages/@aws-cdk/aws-apigatewayv2-integrations/lib/http/service-discovery.ts
  packages/@aws-cdk/aws-apigatewayv2-integrations/test/http/alb.test.ts
  packages/@aws-cdk/aws-apigatewayv2-integrations/test/http/nlb.test.ts
  packages/@aws-cdk/aws-apigatewayv2-integrations/test/http/service-discovery.test.ts
  packages/@aws-cdk/aws-apigatewayv2/lib/http/api.ts
  packages/@aws-cdk/aws-apigatewayv2/lib/http/integration.ts
  packages/@aws-cdk/aws-apigatewayv2/test/http/route.test.ts
Labels: @aws-cdk/aws-apigatewayv2-integrations, pr-linter/exempt-readme

#15669 docs(pipeline): clarify that `ShellStep` needs to be added to the pipeline
  packages/@aws-cdk/pipelines/README.md
Labels: contribution/core

#15676 feat(kinesisfirehose): destinations can provide resources to be depended on by the delivery stream
  packages/@aws-cdk/aws-kinesisfirehose-destinations/lib/private/helpers.ts
  packages/@aws-cdk/aws-kinesisfirehose-destinations/lib/s3-bucket.ts
  packages/@aws-cdk/aws-kinesisfirehose-destinations/test/helpers.test.ts
  packages/@aws-cdk/aws-kinesisfirehose-destinations/test/integ.s3-bucket.expected.json
  packages/@aws-cdk/aws-kinesisfirehose-destinations/test/s3-bucket.test.ts
  packages/@aws-cdk/aws-kinesisfirehose/lib/delivery-stream.ts
  packages/@aws-cdk/aws-kinesisfirehose/lib/destination.ts
  packages/@aws-cdk/aws-kinesisfirehose/test/delivery-stream.test.ts
  packages/@aws-cdk/aws-kinesisfirehose/test/integ.delivery-stream.expected.json
  packages/@aws-cdk/aws-kinesisfirehose/test/integ.delivery-stream.ts
Labels: @aws-cdk/aws-kinesisfirehose, contribution/core, pr-linter/exempt-readme

#15656 docs(ecs): Specify units for DNS TTL
  packages/@aws-cdk/aws-ecs/lib/base/base-service.ts
Labels: contribution/core

#15685 docs(pipelines): stress implications of `--trust` again
  packages/@aws-cdk/pipelines/README.md
Labels: contribution/core

#15687 chore(release): 2.0.0-rc.14
  CHANGELOG.v2.md
  version.v2.json
Labels: pr/auto-approve

#15693 chore: npm-check-updates && yarn upgrade
  package.json
  packages/@aws-cdk/aws-apigatewayv2-authorizers/package.json
  packages/@aws-cdk/aws-certificatemanager/lambda-packages/dns_validated_certificate_handler/package.json
  packages/@aws-cdk/aws-cloudformation/package.json
  packages/@aws-cdk/aws-dynamodb-global/lambda-packages/aws-global-table-coordinator/package.json
  packages/@aws-cdk/aws-dynamodb/package.json
  packages/@aws-cdk/aws-ec2/package.json
  packages/@aws-cdk/aws-eks/package.json
  packages/@aws-cdk/aws-iam/package.json
  packages/@aws-cdk/aws-lambda/package.json
  packages/@aws-cdk/aws-logs/package.json
  packages/@aws-cdk/aws-route53/package.json
  packages/@aws-cdk/aws-s3/package.json
  packages/@aws-cdk/aws-ses/package.json
  packages/@aws-cdk/core/package.json
  packages/@aws-cdk/custom-resources/package.json
  packages/@aws-cdk/pipelines/package.json
  packages/aws-cdk/package.json
  packages/awslint/package.json
  tools/cdk-build-tools/package.json
  tools/eslint-plugin-cdk/package.json
  tools/pkglint/package.json
  yarn.lock
Labels: contribution/core, dependencies, pr/auto-approve

#15699 chore(merge-back): 1.115.0
  CHANGELOG.md
  version.v1.json
Labels: pr/auto-approve, pr/no-squash

#15506 docs(appmesh): Suggest improvements for App Mesh readme
  packages/@aws-cdk/aws-appmesh/README.md
Labels: contribution/core

#15667 feat(pipelines): CDK Pipelines is now Generally Available
  packages/@aws-cdk/pipelines/README.md
  packages/@aws-cdk/pipelines/package.json
Labels: contribution/core, pr-linter/exempt-readme, pr-linter/exempt-test

#15696 docs(pipelines): add migration guide
  packages/@aws-cdk/pipelines/ORIGINAL_API.md
  packages/@aws-cdk/pipelines/README.md
Labels: contribution/core

#15617 feat(core): lazy mappings will only synthesize if keys are unresolved
  packages/@aws-cdk/core/README.md
  packages/@aws-cdk/core/lib/cfn-mapping.ts
  packages/@aws-cdk/core/test/mappings.test.ts
  packages/aws-cdk-lib/README.md
Labels: contribution/core

#15714 fix(elasticsearch): slow logs incorrectly disabled for Elasticsearch versions lower than 5.1
  packages/@aws-cdk/aws-elasticsearch/lib/domain.ts
  packages/@aws-cdk/aws-elasticsearch/test/domain.test.ts
Labels: @aws-cdk/aws-elasticsearch

#14631 fix(stepfunctions): non-object arguments to recurseObject are incorrectly treated as objects
  packages/@aws-cdk/aws-stepfunctions/lib/json-path.ts
  packages/@aws-cdk/aws-stepfunctions/test/fields.test.ts
Labels: @aws-cdk/aws-stepfunctions

#15718 fix(pipelines): Secrets Manager permissions not added to asset projects
  packages/@aws-cdk/aws-codebuild/lib/project.ts
  packages/@aws-cdk/aws-codebuild/test/test.project.ts
  packages/@aws-cdk/pipelines/lib/codepipeline/codepipeline.ts
  packages/@aws-cdk/pipelines/lib/legacy/pipeline.ts
  packages/@aws-cdk/pipelines/lib/legacy/stage.ts
  packages/@aws-cdk/pipelines/lib/private/asset-singleton-role.ts
  packages/@aws-cdk/pipelines/test/compliance/assets.test.ts
  packages/@aws-cdk/pipelines/test/integ.newpipeline-with-vpc.expected.json
  packages/@aws-cdk/pipelines/test/integ.newpipeline-with-vpc.ts
Labels: contribution/core

#15734 docs(pipelines): fix table rendering in MarkDown
  packages/@aws-cdk/pipelines/ORIGINAL_API.md
Labels: contribution/core

#15330 fix(elasticsearch): advancedOptions in domain has no effect
  packages/@aws-cdk/aws-elasticsearch/README.md
  packages/@aws-cdk/aws-elasticsearch/lib/domain.ts
  packages/@aws-cdk/aws-elasticsearch/test/domain.test.ts
  packages/@aws-cdk/aws-elasticsearch/test/integ.elasticsearch.expected.json
  packages/@aws-cdk/aws-elasticsearch/test/integ.elasticsearch.ts
Labels: @aws-cdk/aws-elasticsearch

#15320 feat(stepfunctions): allow intrinsic functions for json path
  packages/@aws-cdk/aws-stepfunctions-tasks/README.md
  packages/@aws-cdk/aws-stepfunctions/lib/fields.ts
  packages/@aws-cdk/aws-stepfunctions/test/fields.test.ts
Labels: @aws-cdk/aws-stepfunctions

#15726 fix(stepfunctions-tasks): instance type cannot be provided to SageMakerCreateTransformJob as input path
  packages/@aws-cdk/aws-stepfunctions-tasks/lib/sagemaker/create-transform-job.ts
  packages/@aws-cdk/aws-stepfunctions-tasks/test/sagemaker/create-transform-job.test.ts
Labels: @aws-cdk/aws-stepfunctions-tasks

#15761 chore(s3): additional documentation for addToResourcePolicy.
  packages/@aws-cdk/aws-s3/README.md
  packages/@aws-cdk/aws-s3/lib/bucket.ts
Labels: contribution/core

#15659 chore: forward merge 'master' into 'v2-main'
  packages/@aws-cdk/aws-appsync/.gitignore
  packages/@aws-cdk/aws-appsync/lib/mapping-template.ts
  packages/@aws-cdk/aws-appsync/test/appsync-lambda.test.ts
  packages/@aws-cdk/aws-appsync/test/appsync-mapping-template.test.ts
  packages/@aws-cdk/aws-appsync/test/appsync-object-type.test.ts
  packages/@aws-cdk/aws-appsync/test/appsync.lambda.graphql
  packages/@aws-cdk/aws-appsync/test/integ.appsync-lambda.expected.json
  packages/@aws-cdk/aws-appsync/test/integ.appsync-lambda.ts
  packages/@aws-cdk/aws-appsync/test/integ.graphql-iam.ts
  packages/@aws-cdk/aws-appsync/test/verify.integ.appsync-lambda.sh
  packages/@aws-cdk/aws-appsync/test/verify/iam-query/iam-query.js
  packages/@aws-cdk/aws-appsync/test/verify/lambda-tutorial/lambda-tutorial.js
  packages/@aws-cdk/aws-iam/lib/principals.ts
  packages/@aws-cdk/aws-iam/test/principals.test.ts
  packages/@aws-cdk/aws-lambda-nodejs/README.md
  packages/@aws-cdk/aws-lambda-nodejs/lib/bundling.ts
  packages/@aws-cdk/aws-lambda-nodejs/lib/types.ts
  packages/@aws-cdk/aws-lambda-nodejs/test/bundling.test.ts
  packages/@aws-cdk/aws-lambda-nodejs/test/integ.function.expected.json
  packages/@aws-cdk/aws-lambda-nodejs/test/integ.function.ts
  packages/@aws-cdk/aws-rds/README.md
  packages/@aws-cdk/aws-rds/lib/cluster.ts
  packages/@aws-cdk/aws-rds/test/cluster.test.ts
  packages/@aws-cdk/aws-rds/test/integ.cluster-rotation.lit.expected.json
  packages/@aws-cdk/aws-rds/test/integ.cluster-s3.expected.json
  packages/@aws-cdk/aws-rds/test/integ.cluster.expected.json
  packages/@aws-cdk/aws-servicecatalog/README.md
  packages/@aws-cdk/aws-servicecatalog/lib/index.ts
  packages/@aws-cdk/aws-servicecatalog/lib/portfolio.ts
  packages/@aws-cdk/aws-servicecatalog/lib/private/association-manager.ts
  packages/@aws-cdk/aws-servicecatalog/lib/tag-options.ts
  packages/@aws-cdk/aws-servicecatalog/test/integ.portfolio.expected.json
  packages/@aws-cdk/aws-servicecatalog/test/integ.portfolio.ts
  packages/@aws-cdk/aws-servicecatalog/test/portfolio.test.ts
  packages/@aws-cdk/pipelines/README.md
  packages/@aws-cdk/pipelines/lib/blueprint/index.ts
  packages/@aws-cdk/pipelines/lib/blueprint/shell-step.ts
  packages/@aws-cdk/pipelines/lib/codepipeline/_codebuild-factory.ts
  packages/@aws-cdk/pipelines/lib/codepipeline/codebuild-step.ts
  packages/@aws-cdk/pipelines/lib/codepipeline/codepipeline-source.ts
  packages/@aws-cdk/pipelines/lib/codepipeline/codepipeline.ts
  packages/@aws-cdk/pipelines/lib/helpers-internal/pipeline-graph.ts
  packages/@aws-cdk/pipelines/lib/legacy/actions/publish-assets-action.ts
  packages/@aws-cdk/pipelines/lib/legacy/actions/update-pipeline-action.ts
  packages/@aws-cdk/pipelines/lib/legacy/pipeline.ts
  packages/@aws-cdk/pipelines/lib/legacy/synths/simple-synth-action.ts
  packages/@aws-cdk/pipelines/lib/private/application-security-check.ts
  packages/@aws-cdk/pipelines/lib/private/asset-manifest.ts
  packages/@aws-cdk/pipelines/test/codepipeline/codepipeline-sources.test.ts
  packages/@aws-cdk/pipelines/test/compliance/assets.test.ts
  packages/@aws-cdk/pipelines/test/compliance/escape-hatching.test.ts
  packages/@aws-cdk/pipelines/test/compliance/self-mutation.test.ts
  packages/@aws-cdk/pipelines/test/compliance/synths.test.ts
Labels: pr/auto-approve, pr/forward-merge, pr/no-squash

#15796 feat(cfnspec): cloudformation spec v39.7.0
  packages/monocdk/rosetta/with-bucket.ts-fixture
  packages/monocdk/rosetta/with-delivery-stream.ts-fixture
  packages/monocdk/rosetta/with-destination.ts-fixture
Labels: pr-linter/exempt-test, pr/auto-approve

#15795 chore(release): 2.0.0-rc.15
  CHANGELOG.v2.md
  version.v2.json
Labels: pr/auto-approve

#15800 chore(merge-back): 1.116.0
  CHANGELOG.md
  version.v1.json
Labels: pr/auto-approve, pr/no-squash

#15779 chore: introduce pragma:context to cdk-integ
  packages/@aws-cdk/pipelines/test/integ.newpipeline.ts
  packages/@aws-cdk/pipelines/test/integ.pipeline-security.ts
  tools/cdk-integ-tools/lib/integ-helpers.ts
Labels: contribution/core

#15465 feat(ec2): Add Transcribe interface endpoint
  packages/@aws-cdk/aws-ec2/lib/vpc-endpoint.ts
  packages/@aws-cdk/aws-ec2/package.json
Labels: @aws-cdk/aws-ec2, pr-linter/exempt-readme, pr-linter/exempt-test

#15666 fix(assert): module is incompatible with jest@27
  packages/@aws-cdk/assert/package.json
Labels: @aws-cdk/assert, pr-linter/exempt-readme, pr-linter/exempt-test

#14817 feat(stepfunctions-tasks): add sns publish with message attributes
  packages/@aws-cdk/aws-stepfunctions-tasks/README.md
  packages/@aws-cdk/aws-stepfunctions-tasks/lib/sns/publish.ts
  packages/@aws-cdk/aws-stepfunctions-tasks/test/sns/publish.test.ts
Labels: @aws-cdk/aws-stepfunctions-tasks, p1

#15803 docs(lambda-event-sources): max batch size docs for SqsEventSource
  packages/@aws-cdk/aws-lambda-event-sources/lib/sqs.ts
Labels: contribution/core

#15618 feat(kinesisfirehose): add metrics functions to IDeliveryStream
  packages/@aws-cdk/aws-kinesisfirehose/README.md
  packages/@aws-cdk/aws-kinesisfirehose/lib/delivery-stream.ts
  packages/@aws-cdk/aws-kinesisfirehose/test/delivery-stream.test.ts
Labels: contribution/core

#15547 feat(kinesisfirehose): add support for server-side encryption on DeliveryStream
  packages/@aws-cdk/aws-kinesisfirehose/README.md
  packages/@aws-cdk/aws-kinesisfirehose/lib/delivery-stream.ts
  packages/@aws-cdk/aws-kinesisfirehose/package.json
  packages/@aws-cdk/aws-kinesisfirehose/test/delivery-stream.test.ts
  packages/@aws-cdk/aws-kinesisfirehose/test/integ.delivery-stream.expected.json
  packages/@aws-cdk/aws-kinesisfirehose/test/integ.delivery-stream.ts
Labels: contribution/core

#15550 feat(kinesisfirehose-destinations): add support for compression on S3 delivery stream destinations
  packages/@aws-cdk/aws-kinesisfirehose-destinations/lib/common.ts
  packages/@aws-cdk/aws-kinesisfirehose-destinations/lib/s3-bucket.ts
  packages/@aws-cdk/aws-kinesisfirehose-destinations/test/integ.s3-bucket.expected.json
  packages/@aws-cdk/aws-kinesisfirehose-destinations/test/integ.s3-bucket.ts
  packages/@aws-cdk/aws-kinesisfirehose-destinations/test/s3-bucket.test.ts
  packages/@aws-cdk/aws-kinesisfirehose/README.md
Labels: contribution/core

#15552 feat(kinesisfirehose-destinations): add support for prefixes in the S3 destination
  packages/@aws-cdk/aws-kinesisfirehose-destinations/lib/s3-bucket.ts
  packages/@aws-cdk/aws-kinesisfirehose-destinations/test/integ.s3-bucket.expected.json
  packages/@aws-cdk/aws-kinesisfirehose-destinations/test/integ.s3-bucket.ts
  packages/@aws-cdk/aws-kinesisfirehose/README.md
Labels: contribution/core

#15557 feat(kinesisfirehose): add support for BufferingHints
  packages/@aws-cdk/aws-kinesisfirehose-destinations/lib/private/helpers.ts
  packages/@aws-cdk/aws-kinesisfirehose-destinations/lib/s3-bucket.ts
  packages/@aws-cdk/aws-kinesisfirehose-destinations/test/integ.s3-bucket.expected.json
  packages/@aws-cdk/aws-kinesisfirehose-destinations/test/integ.s3-bucket.ts
  packages/@aws-cdk/aws-kinesisfirehose-destinations/test/s3-bucket.test.ts
  packages/@aws-cdk/aws-kinesisfirehose/README.md
Labels: contribution/core

#15558 feat(aws-kinesisfirehose): support for S3 destination encryption on DeliveryStream
  packages/@aws-cdk/aws-kinesisfirehose-destinations/lib/private/helpers.ts
  packages/@aws-cdk/aws-kinesisfirehose-destinations/lib/s3-bucket.ts
  packages/@aws-cdk/aws-kinesisfirehose-destinations/package.json
  packages/@aws-cdk/aws-kinesisfirehose-destinations/test/integ.s3-bucket.expected.json
  packages/@aws-cdk/aws-kinesisfirehose-destinations/test/integ.s3-bucket.ts
  packages/@aws-cdk/aws-kinesisfirehose-destinations/test/s3-bucket.test.ts
  packages/@aws-cdk/aws-kinesisfirehose/README.md
Labels: contribution/core

#15433 feat(aws-cloudfront): add enabled to web distribution
  packages/@aws-cdk/aws-cloudfront/lib/web-distribution.ts
  packages/@aws-cdk/aws-cloudfront/test/web-distribution.test.ts
Labels: @aws-cdk/aws-cloudfront, pr-linter/exempt-readme

#15704 feat(kinesisfirehose): add support for Lambda data processors
  packages/@aws-cdk/aws-kinesisfirehose-destinations/lib/common.ts
  packages/@aws-cdk/aws-kinesisfirehose-destinations/lib/private/helpers.ts
  packages/@aws-cdk/aws-kinesisfirehose-destinations/lib/s3-bucket.ts
  packages/@aws-cdk/aws-kinesisfirehose-destinations/package.json
  packages/@aws-cdk/aws-kinesisfirehose-destinations/test/integ.s3-bucket.lit.expected.json
  packages/@aws-cdk/aws-kinesisfirehose-destinations/test/integ.s3-bucket.lit.ts
  packages/@aws-cdk/aws-kinesisfirehose-destinations/test/lambda-data-processor.js
  packages/@aws-cdk/aws-kinesisfirehose-destinations/test/s3-bucket.test.ts
  packages/@aws-cdk/aws-kinesisfirehose/README.md
  packages/@aws-cdk/aws-kinesisfirehose/lib/index.ts
  packages/@aws-cdk/aws-kinesisfirehose/lib/lambda-function-processor.ts
  packages/@aws-cdk/aws-kinesisfirehose/lib/processor.ts
  packages/@aws-cdk/aws-kinesisfirehose/package.json
Labels: contribution/core

#15439 feat(lambda): cloudwatch lambda insights
  packages/@aws-cdk/aws-lambda/README.md
  packages/@aws-cdk/aws-lambda/lib/function.ts
  packages/@aws-cdk/aws-lambda/lib/index.ts
  packages/@aws-cdk/aws-lambda/lib/lambda-insights.ts
  packages/@aws-cdk/aws-lambda/package.json
  packages/@aws-cdk/aws-lambda/test/integ.lambda-insights-mapping.expected.json
  packages/@aws-cdk/aws-lambda/test/integ.lambda-insights-mapping.ts
  packages/@aws-cdk/aws-lambda/test/lambda-insights.test.ts
  packages/@aws-cdk/region-info/build-tools/fact-tables.ts
  packages/@aws-cdk/region-info/build-tools/generate-static-data.ts
  packages/@aws-cdk/region-info/lib/fact.ts
  packages/@aws-cdk/region-info/lib/region-info.ts
  packages/@aws-cdk/region-info/test/__snapshots__/region-info.test.js.snap
  packages/@aws-cdk/region-info/test/region-info.test.ts
Labels: @aws-cdk/aws-lambda, effort/medium, p2

#15829 fix(cli): move fail option into the diff command
  packages/aws-cdk/bin/cdk.ts
Labels: package/tools, pr-linter/exempt-test

#15755 fix(stepfunctions-tasks): Stage field not included in CallApiGatewayHttpApiEndpoint task definition
  packages/@aws-cdk/aws-stepfunctions-tasks/lib/apigateway/call-http-api.ts
  packages/@aws-cdk/aws-stepfunctions-tasks/test/apigateway/call-http-api.test.ts
Labels: @aws-cdk/aws-stepfunctions-tasks

#15830 fix(aws-appsync): graphqlapi throws incorrect error message for authorizationConfig
  packages/@aws-cdk/aws-appsync/lib/graphqlapi.ts
Labels: @aws-cdk/aws-appsync, effort/small, pr-linter/exempt-test

#15774 feat(eks): support Kubernetes 1.21
  packages/@aws-cdk/aws-eks/README.md
  packages/@aws-cdk/aws-eks/lib/cluster.ts
  packages/@aws-cdk/aws-eks/test/example.ssh-into-nodes.lit.ts
  packages/@aws-cdk/aws-eks/test/integ.eks-cluster-handlers-vpc.expected.json
  packages/@aws-cdk/aws-eks/test/integ.eks-cluster-handlers-vpc.ts
  packages/@aws-cdk/aws-eks/test/integ.eks-cluster-private-endpoint.expected.json
  packages/@aws-cdk/aws-eks/test/integ.eks-cluster-private-endpoint.ts
  packages/@aws-cdk/aws-eks/test/integ.eks-cluster.expected.json
  packages/@aws-cdk/aws-eks/test/integ.eks-cluster.ts
  packages/@aws-cdk/aws-eks/test/integ.fargate-cluster.expected.json
  packages/@aws-cdk/aws-eks/test/integ.fargate-cluster.ts
  packages/@aws-cdk/aws-eks/test/test.cluster.ts
  packages/@aws-cdk/aws-eks/test/test.fargate.ts
  packages/@aws-cdk/aws-eks/test/test.nodegroup.ts
  packages/@aws-cdk/aws-eks/test/test.user-data.ts
  packages/@aws-cdk/lambda-layer-kubectl/layer/Dockerfile
Labels: @aws-cdk/aws-eks

#15487 fix(aws-eks): Allow desiredsize minsize and maxsize to accept CfnParameters.
  packages/@aws-cdk/aws-eks/lib/managed-nodegroup.ts
  packages/@aws-cdk/aws-eks/test/test.nodegroup.ts
Labels: @aws-cdk/aws-eks

#15373 feat(aws-ec2): Add SubnetFilter for Id and CIDR netmask
  packages/@aws-cdk/aws-ec2/README.md
  packages/@aws-cdk/aws-ec2/lib/subnet.ts
  packages/@aws-cdk/aws-ec2/test/vpc.test.ts
Labels: @aws-cdk/aws-ec2, effort/small, p1

#15453 feat(cloudfront): Origin Shield support
  packages/@aws-cdk/aws-cloudfront/README.md
  packages/@aws-cdk/aws-cloudfront/lib/origin.ts
  packages/@aws-cdk/aws-cloudfront/lib/web-distribution.ts
  packages/@aws-cdk/aws-cloudfront/test/integ.distribution-extensive.expected.json
  packages/@aws-cdk/aws-cloudfront/test/integ.distribution-extensive.ts
  packages/@aws-cdk/aws-cloudfront/test/origin.test.ts
  packages/@aws-cdk/aws-cloudfront/test/web-distribution.test.ts
Labels: @aws-cdk/aws-cloudfront

#15782 feat(Route53): add support for RemovalPolicy in CrossAccountZoneDelegationRecord
  packages/@aws-cdk/aws-route53/lib/record-set.ts
  packages/@aws-cdk/aws-route53/test/record-set.test.ts
Labels: @aws-cdk/aws-route53, pr-linter/exempt-readme

#15804 fix(elbv2): unresolved listener priority throws error
  packages/@aws-cdk/aws-elasticloadbalancingv2/lib/alb/application-listener-rule.ts
  packages/@aws-cdk/aws-elasticloadbalancingv2/test/alb/listener.test.ts
Labels: @aws-cdk/aws-elasticloadbalancingv2

#15477 feat(cloudfront): use TLS_V1_2_2021 SecurityPolicy as default version (under feature flag)
  packages/@aws-cdk/aws-cloudfront/README.md
  packages/@aws-cdk/aws-cloudfront/lib/distribution.ts
  packages/@aws-cdk/aws-cloudfront/lib/web-distribution.ts
  packages/@aws-cdk/aws-cloudfront/package.json
  packages/@aws-cdk/aws-cloudfront/test/distribution.test.ts
  packages/@aws-cdk/cx-api/lib/features.ts
Labels: @aws-cdk/aws-cloudfront

#15839 docs: remove BREAKING CHANGES requirement for feature flags
  CONTRIBUTING.md
Labels: contribution/core

#15722 chore: move the build of the experimental modules to a separate script
  buildspec-pr.yaml
  buildspec.yaml
  packages/@aws-cdk-lib/README.md
  packages/@aws-cdk-lib/gen.js
  packages/@aws-cdk-lib/package.json
  packages/@aws-cdk/assertions/package.json
  packages/@aws-cdk/aws-amplify/package.json
  packages/@aws-cdk/aws-apigatewayv2-authorizers/package.json
  packages/@aws-cdk/aws-apigatewayv2-integrations/package.json
  packages/@aws-cdk/aws-apigatewayv2/package.json
  packages/@aws-cdk/aws-appsync/package.json
  packages/@aws-cdk/aws-batch/package.json
  packages/@aws-cdk/aws-cloud9/package.json
  packages/@aws-cdk/aws-codestar/package.json
  packages/@aws-cdk/aws-glue/package.json
  packages/@aws-cdk/aws-ivs/package.json
  packages/@aws-cdk/aws-kinesisanalytics-flink/package.json
  packages/@aws-cdk/aws-lambda-go/package.json
  packages/@aws-cdk/aws-lambda-python/package.json
  packages/@aws-cdk/aws-msk/package.json
  packages/@aws-cdk/aws-neptune/package.json
  packages/@aws-cdk/aws-redshift/package.json
  packages/@aws-cdk/aws-servicecatalog/package.json
  packages/@aws-cdk/aws-servicecatalogappregistry/package.json
  packages/@aws-cdk/aws-synthetics/package.json
  packages/@aws-cdk/example-construct-library/package.json
  packages/@aws-cdk/pipelines/package.json
  packages/individual-packages/.gitignore
  packages/individual-packages/README.md
  packages/individual-packages/lerna.json
  packages/individual-packages/package.json
  scripts/transform.sh
  tools/individual-pkg-gen/.eslintrc.js
  tools/individual-pkg-gen/.gitignore
  tools/individual-pkg-gen/.npmignore
  tools/individual-pkg-gen/LICENSE
  tools/individual-pkg-gen/NOTICE
  tools/individual-pkg-gen/README.md
  tools/individual-pkg-gen/bin/individual-pkg-gen
  tools/individual-pkg-gen/copy-files-removing-deps.ts
  tools/individual-pkg-gen/jest.config.js
  tools/individual-pkg-gen/package.json
  tools/individual-pkg-gen/restore-package-jsons.ts
  tools/individual-pkg-gen/test/gen.test.ts
  tools/individual-pkg-gen/tsconfig.json
  tools/pkglint/lib/rules.ts
  tools/pkglint/lib/util.ts
Labels: contribution/core

#15725 feat(kinesisfirehose): add support for backing up source records to S3
  packages/@aws-cdk/aws-kinesisfirehose-destinations/lib/common.ts
  packages/@aws-cdk/aws-kinesisfirehose-destinations/lib/private/helpers.ts
  packages/@aws-cdk/aws-kinesisfirehose-destinations/lib/s3-bucket.ts
  packages/@aws-cdk/aws-kinesisfirehose-destinations/test/integ.s3-bucket.lit.expected.json
  packages/@aws-cdk/aws-kinesisfirehose-destinations/test/integ.s3-bucket.lit.ts
  packages/@aws-cdk/aws-kinesisfirehose-destinations/test/s3-bucket.test.ts
  packages/@aws-cdk/aws-kinesisfirehose/README.md
Labels: contribution/core

#15770 feat(servicecatalog): add CloudFormation Parameter constraint
  packages/@aws-cdk/aws-servicecatalog/README.md
  packages/@aws-cdk/aws-servicecatalog/lib/constraints.ts
  packages/@aws-cdk/aws-servicecatalog/lib/portfolio.ts
  packages/@aws-cdk/aws-servicecatalog/lib/private/association-manager.ts
  packages/@aws-cdk/aws-servicecatalog/test/integ.portfolio.expected.json
  packages/@aws-cdk/aws-servicecatalog/test/integ.portfolio.ts
  packages/@aws-cdk/aws-servicecatalog/test/portfolio.test.ts
  packages/@aws-cdk/core/lib/cfn-condition.ts
  packages/@aws-cdk/core/lib/cfn-fn.ts
Labels: @aws-cdk/aws-servicecatalog
