Repository aws/aws-cdk, pull requests merged in 2021-09, with the labels that each got.

#16312 chore(release): 2.0.0-rc.20
  CHANGELOG.v2.md
  version.v2.json
Labels: pr/auto-approve

#16318 chore(merge-back): 1.121.0
  CHANGELOG.md
  version.v1.json
Labels: pr/no-squash, pr/auto-approve

#16321 chore(resolve-version): export the alphaVersion
  scripts/resolve-version-lib.js
  scripts/script-tests/resolve-version.test.js
Labels: contribution/core

#16325 chore(yarn-cling): rename test packages to real package names
  tools/yarn-cling/.gitignore
  tools/yarn-cling/package.json
  tools/yarn-cling/test/cling.test.ts
  tools/yarn-cling/test/test-fixture/cdk/package.json
  tools/yarn-cling/test/test-fixture/jsii/node_modules/aws-cdk-lib/package.json
  tools/yarn-cling/test/test-fixture/jsii/node_modules/aws-cdk/package.json
  tools/yarn-cling/test/test-fixture/jsii/node_modules/cdk
  tools/yarn-cling/test/test-fixture/jsii/package.json
  tools/yarn-cling/test/test-fixture/package1/node_modules/package2
  tools/yarn-cling/test/test-fixture/package1/node_modules/registrydependency1/package.json
  tools/yarn-cling/test/test-fixture/package1/node_modules/registrydependency2/package.json
  tools/yarn-cling/test/test-fixture/package1/package.json
  tools/yarn-cling/test/test-fixture/yarn.lock
Labels: contribution/core

#16049 feat(ecs-service-extensions): Subscribe Extension
  packages/@aws-cdk-containers/ecs-service-extensions/README.md
  packages/@aws-cdk-containers/ecs-service-extensions/lib/extensions/index.ts
  packages/@aws-cdk-containers/ecs-service-extensions/lib/extensions/queue.ts
  packages/@aws-cdk-containers/ecs-service-extensions/package.json
  packages/@aws-cdk-containers/ecs-service-extensions/test/test.queue.ts
Labels: @aws-cdk-containers/ecs-service-extensions

#15742 fix(core): allow asset bundling when selinux is enabled
  packages/@aws-cdk/core/lib/bundling.ts
  packages/@aws-cdk/core/test/bundling.test.ts
Labels: p1, @aws-cdk/core, effort/small

#16341 chore: forward merge 'master' into 'v2-main'
  CHANGELOG.md
  packages/@aws-cdk-containers/ecs-service-extensions/README.md
  packages/@aws-cdk-containers/ecs-service-extensions/lib/extensions/index.ts
  packages/@aws-cdk-containers/ecs-service-extensions/lib/extensions/queue.ts
  packages/@aws-cdk-containers/ecs-service-extensions/package.json
  packages/@aws-cdk-containers/ecs-service-extensions/test/test.queue.ts
  packages/@aws-cdk/aws-ecr-assets/README.md
  packages/@aws-cdk/pipelines/README.md
  scripts/resolve-version-lib.js
  scripts/script-tests/resolve-version.test.js
  tools/yarn-cling/.gitignore
  tools/yarn-cling/package.json
  tools/yarn-cling/test/cling.test.ts
  tools/yarn-cling/test/test-fixture/cdk/package.json
  tools/yarn-cling/test/test-fixture/jsii/node_modules/aws-cdk-lib/package.json
  tools/yarn-cling/test/test-fixture/jsii/node_modules/aws-cdk/package.json
  tools/yarn-cling/test/test-fixture/jsii/node_modules/cdk
  tools/yarn-cling/test/test-fixture/jsii/package.json
  tools/yarn-cling/test/test-fixture/package1/node_modules/package2
  tools/yarn-cling/test/test-fixture/package1/node_modules/registrydependency1/package.json
  tools/yarn-cling/test/test-fixture/package1/node_modules/registrydependency2/package.json
  tools/yarn-cling/test/test-fixture/package1/package.json
  tools/yarn-cling/test/test-fixture/yarn.lock
  version.v1.json
Labels: pr/no-squash, pr/forward-merge, pr/auto-approve

#16322 chore(individual-pkg-gen): set the alpha version in alpha module's package.json files if present
  tools/individual-pkg-gen/copy-files-removing-deps.ts
Labels: contribution/core

#15748 feat(cli): hotswap deployments
  packages/@aws-cdk/cloudformation-diff/lib/diff/types.ts
  packages/aws-cdk/README.md
  packages/aws-cdk/bin/cdk.ts
  packages/aws-cdk/lib/api/aws-auth/sdk.ts
  packages/aws-cdk/lib/api/cloudformation-deployments.ts
  packages/aws-cdk/lib/api/deploy-stack.ts
  packages/aws-cdk/lib/api/hotswap-deployments.ts
  packages/aws-cdk/lib/api/hotswap/common.ts
  packages/aws-cdk/lib/api/hotswap/lambda-functions.ts
  packages/aws-cdk/lib/api/util/cloudformation/evaluate-cfn.ts
  packages/aws-cdk/lib/cdk-toolkit.ts
  packages/aws-cdk/test/api/cloudformation-deployments.test.ts
  packages/aws-cdk/test/api/deploy-stack.test.ts
  packages/aws-cdk/test/api/fake-cloudformation-stack.ts
  packages/aws-cdk/test/api/hotswap-deployments.test.ts
  packages/aws-cdk/test/cdk-toolkit.test.ts
  packages/aws-cdk/test/util.ts
  packages/aws-cdk/test/util/mock-sdk.ts
Labels: contribution/core

#16290 feat(stepfunctions-tasks): await the eval so async ops can be passed to tasks.EvaluateExpression
  packages/@aws-cdk/aws-stepfunctions-tasks/lib/eval-nodejs-handler/index.ts
Labels: p1, effort/small, pr-linter/exempt-readme, pr-linter/exempt-test, @aws-cdk/aws-stepfunctions-tasks

#16362 chore: forward merge 'master' into 'v2-main'
  packages/@aws-cdk/aws-stepfunctions-tasks/lib/eval-nodejs-handler/index.ts
  packages/@aws-cdk/cloudformation-diff/lib/diff/types.ts
  packages/@aws-cdk/core/lib/bundling.ts
  packages/@aws-cdk/core/test/bundling.test.ts
  packages/aws-cdk/README.md
  packages/aws-cdk/bin/cdk.ts
  packages/aws-cdk/lib/api/aws-auth/sdk.ts
  packages/aws-cdk/lib/api/cloudformation-deployments.ts
  packages/aws-cdk/lib/api/deploy-stack.ts
  packages/aws-cdk/lib/api/hotswap-deployments.ts
  packages/aws-cdk/lib/api/hotswap/common.ts
  packages/aws-cdk/lib/api/hotswap/lambda-functions.ts
  packages/aws-cdk/lib/api/util/cloudformation/evaluate-cfn.ts
  packages/aws-cdk/lib/cdk-toolkit.ts
  packages/aws-cdk/test/api/cloudformation-deployments.test.ts
  packages/aws-cdk/test/api/deploy-stack.test.ts
  packages/aws-cdk/test/api/fake-cloudformation-stack.ts
  packages/aws-cdk/test/api/hotswap-deployments.test.ts
  packages/aws-cdk/test/cdk-toolkit.test.ts
  packages/aws-cdk/test/util.ts
  packages/aws-cdk/test/util/mock-sdk.ts
Labels: pr/no-squash, pr/forward-merge, pr/auto-approve

#16348 feat(ec2): rename SubnetTypes to improve clarity with EC2 conventions
  packages/@aws-cdk/aws-ec2/README.md
  packages/@aws-cdk/aws-ec2/lib/util.ts
  packages/@aws-cdk/aws-ec2/lib/vpc-endpoint.ts
  packages/@aws-cdk/aws-ec2/lib/vpc.ts
  packages/@aws-cdk/aws-ec2/test/bastion-host.test.ts
  packages/@aws-cdk/aws-ec2/test/integ.reserved-private-subnet.ts
  packages/@aws-cdk/aws-ec2/test/integ.vpc-gateway.ts
  packages/@aws-cdk/aws-ec2/test/integ.vpc-networkacl.ts
  packages/@aws-cdk/aws-ec2/test/vpc-endpoint.test.ts
  packages/@aws-cdk/aws-ec2/test/vpc.from-lookup.test.ts
  packages/@aws-cdk/aws-ec2/test/vpc.test.ts
Labels: contribution/core

#15652 feat(kms): support fromLookup in KMS key to get key by alias name
  packages/@aws-cdk/aws-kms/README.md
  packages/@aws-cdk/aws-kms/lib/index.ts
  packages/@aws-cdk/aws-kms/lib/key-lookup.ts
  packages/@aws-cdk/aws-kms/lib/key.ts
  packages/@aws-cdk/aws-kms/package.json
  packages/@aws-cdk/aws-kms/test/key.from-lookup.test.ts
  packages/@aws-cdk/cloud-assembly-schema/lib/cloud-assembly/context-queries.ts
  packages/@aws-cdk/cloud-assembly-schema/schema/cloud-assembly.schema.json
  packages/@aws-cdk/cloud-assembly-schema/schema/cloud-assembly.version.json
  packages/@aws-cdk/cx-api/lib/context/key.ts
  packages/@aws-cdk/cx-api/lib/index.ts
  packages/aws-cdk/lib/api/aws-auth/sdk.ts
  packages/aws-cdk/lib/context-providers/index.ts
  packages/aws-cdk/lib/context-providers/keys.ts
  packages/aws-cdk/test/context-providers/keys.test.ts
  packages/aws-cdk/test/util/mock-sdk.ts
Labels: p1, @aws-cdk/aws-kms, effort/medium

#16121 feat(aws-ec2): Allow ApplyCloudformationInitOptions to set additional params
  packages/@aws-cdk/aws-autoscaling/lib/auto-scaling-group.ts
  packages/@aws-cdk/aws-ec2/README.md
  packages/@aws-cdk/aws-ec2/lib/cfn-init.ts
  packages/@aws-cdk/aws-ec2/lib/instance.ts
  packages/@aws-cdk/aws-ec2/test/cfn-init.test.ts
Labels: p1, @aws-cdk/aws-ec2, effort/small

#16306 feat(ec2): vpc endpoint for aws keyspaces
  packages/@aws-cdk/aws-ec2/README.md
  packages/@aws-cdk/aws-ec2/lib/vpc-endpoint.ts
  packages/@aws-cdk/aws-ec2/package.json
Labels: p1, effort/small, pr-linter/exempt-test

#15956 feat(elasticloadbalancingv2): ALPN policy support for NLB listener
  packages/@aws-cdk/aws-elasticloadbalancingv2/lib/nlb/network-listener.ts
  packages/@aws-cdk/aws-elasticloadbalancingv2/lib/shared/enums.ts
  packages/@aws-cdk/aws-elasticloadbalancingv2/test/nlb/listener.test.ts
Labels: pr-linter/exempt-readme, @aws-cdk/aws-elasticloadbalancingv2

#15607 fix(apigatewayv2): some methods of the `defaultStage` are not available without casting it to `IHttpStage`
  packages/@aws-cdk/aws-apigatewayv2/lib/http/api.ts
Labels: pr-linter/exempt-test, @aws-cdk/aws-apigatewayv2

#16141 fix(stepfunctions-tasks): Athena StartQueryExecution includes QueryExecutionContext even when object is empty
  packages/@aws-cdk/aws-stepfunctions-tasks/lib/athena/start-query-execution.ts
  packages/@aws-cdk/aws-stepfunctions-tasks/test/athena/start-query-execution.test.ts
Labels: p1, effort/small, @aws-cdk/aws-stepfunctions-tasks

#16094 fix(assets): run executable command of container assets in cloud assembly root directory
  packages/cdk-assets/lib/private/handlers/container-images.ts
  packages/cdk-assets/test/docker-images.test.ts
Labels: p1, @aws-cdk/assets, effort/small

#16028 fix(autoscaling): EbsDeviceVolumeType.IO2 is not a valid CloudFormation value
  allowed-breaking-changes.txt
  packages/@aws-cdk/aws-autoscaling/lib/volume.ts
Labels: @aws-cdk/aws-autoscaling, effort/small, pr-linter/exempt-test

#16011 feat(config): EC2_INSTANCE_PROFILE_ATTACHED managed rule
  packages/@aws-cdk/aws-config/lib/rule.ts
  packages/@aws-cdk/aws-config/test/test.managed-rules.ts
Labels: p2, effort/small, @aws-cdk/aws-config, pr-linter/exempt-readme, pr-linter/exempt-test

#16401 chore: bringing the changes from v2-main to master related to the experimental modules
  buildspec-pr.yaml
  buildspec.yaml
  package.json
  packages/@aws-cdk/assertions/vendor-in.sh
  packages/@aws-cdk/aws-kinesisfirehose-destinations/test/integ.s3-bucket.lit.ts
  packages/aws-cdk-migration/lib/rewrite.ts
  packages/individual-packages/.gitignore
  packages/individual-packages/README.md
  packages/individual-packages/lerna.json
  packages/individual-packages/package.json
  scripts/transform.sh
  tools/individual-pkg-gen/.eslintrc.js
  tools/individual-pkg-gen/.gitignore
  tools/individual-pkg-gen/.npmignore
  tools/individual-pkg-gen/LICENSE
  tools/individual-pkg-gen/NOTICE
  tools/individual-pkg-gen/README.md
  tools/individual-pkg-gen/bin/individual-pkg-gen
  tools/individual-pkg-gen/copy-files-removing-deps.ts
  tools/individual-pkg-gen/jest.config.js
  tools/individual-pkg-gen/package.json
  tools/individual-pkg-gen/restore-package-jsons.ts
  tools/individual-pkg-gen/test/gen.test.ts
  tools/individual-pkg-gen/tsconfig.json
  tools/pkglint/lib/rules.ts
  tools/pkglint/lib/util.ts
Labels: contribution/core

#16333 fix(cloudwatch): cross account alarms does not support math expressions
  packages/@aws-cdk/aws-cloudwatch/lib/alarm.ts
  packages/@aws-cdk/aws-cloudwatch/test/cross-environment.test.ts
Labels: contribution/core

#16215 feat(pipelines): stack-level steps
  packages/@aws-cdk/pipelines/README.md
  packages/@aws-cdk/pipelines/lib/blueprint/stack-deployment.ts
  packages/@aws-cdk/pipelines/lib/blueprint/stage-deployment.ts
  packages/@aws-cdk/pipelines/lib/blueprint/step.ts
  packages/@aws-cdk/pipelines/lib/blueprint/wave.ts
  packages/@aws-cdk/pipelines/lib/helpers-internal/pipeline-graph.ts
  packages/@aws-cdk/pipelines/lib/main/pipeline-base.ts
  packages/@aws-cdk/pipelines/test/blueprint/helpers-internal/pipeline-graph.test.ts
  packages/@aws-cdk/pipelines/test/testhelpers/test-app.ts
Labels: contribution/core

#16409 chore(release): 2.0.0-rc.21
  CHANGELOG.v2.md
  version.v2.json
Labels: pr/auto-approve

#16282 feat(backup): option to prevent recovery point deletions
  packages/@aws-cdk/aws-backup/README.md
  packages/@aws-cdk/aws-backup/lib/vault.ts
  packages/@aws-cdk/aws-backup/package.json
  packages/@aws-cdk/aws-backup/test/plan.test.ts
  packages/@aws-cdk/aws-backup/test/selection.test.ts
  packages/@aws-cdk/aws-backup/test/vault.test.ts
Labels: effort/small, @aws-cdk/aws-backup

#16150 fix(cli): 'deploy' and 'diff' silently does nothing when given unknown stack name
  packages/aws-cdk/lib/cdk-toolkit.ts
  packages/aws-cdk/test/cdk-toolkit.test.ts
  packages/aws-cdk/test/diff.test.ts
Labels: contribution/core

#16329 fix(assertions): output and mapping assertions do not accept logical id
  packages/@aws-cdk/assertions/README.md
  packages/@aws-cdk/assertions/lib/private/mappings.ts
  packages/@aws-cdk/assertions/lib/private/outputs.ts
  packages/@aws-cdk/assertions/lib/private/section.ts
  packages/@aws-cdk/assertions/lib/template.ts
  packages/@aws-cdk/assertions/test/template.test.ts
  packages/@aws-cdk/aws-kinesisfirehose/test/delivery-stream.test.ts
  packages/@aws-cdk/aws-neptune/test/instance.test.ts
Labels: contribution/core

#12506 feat(glue): Job construct
  packages/@aws-cdk/aws-glue/README.md
  packages/@aws-cdk/aws-glue/lib/code.ts
  packages/@aws-cdk/aws-glue/lib/index.ts
  packages/@aws-cdk/aws-glue/lib/job-executable.ts
  packages/@aws-cdk/aws-glue/lib/job.ts
  packages/@aws-cdk/aws-glue/package.json
  packages/@aws-cdk/aws-glue/test/code.test.ts
  packages/@aws-cdk/aws-glue/test/integ.job.expected.json
  packages/@aws-cdk/aws-glue/test/integ.job.ts
  packages/@aws-cdk/aws-glue/test/job-executable.test.ts
  packages/@aws-cdk/aws-glue/test/job-script/hello_world.py
  packages/@aws-cdk/aws-glue/test/job-script/hello_world_2.py
  packages/@aws-cdk/aws-glue/test/job.test.ts
Labels: p1, effort/medium, @aws-cdk/aws-glue

#16420 chore(merge-back): 1.122.0
  CHANGELOG.md
  version.v1.json
Labels: pr/no-squash, pr/auto-approve

#16201 fix(apigatewayv2): ApiMapping does not depend on DomainName
  packages/@aws-cdk/aws-apigatewayv2/lib/common/domain-name.ts
  packages/@aws-cdk/aws-apigatewayv2/test/common/api-mapping.test.ts
  packages/@aws-cdk/aws-apigatewayv2/test/http/domain-name.test.ts
  packages/@aws-cdk/aws-apigatewayv2/test/http/stage.test.ts
Labels: contribution/core

#16430 chore: add breaking changes entry to 1.122.0 release
  CHANGELOG.md
Labels: contribution/core

#16021 feat(ec2/ecs): `cacheInContext` properties for machine images
  packages/@aws-cdk/aws-ec2/lib/machine-image.ts
  packages/@aws-cdk/aws-ec2/test/machine-image.test.ts
  packages/@aws-cdk/aws-ecs/README.md
  packages/@aws-cdk/aws-ecs/lib/amis.ts
  packages/@aws-cdk/aws-ecs/lib/cluster.ts
  packages/@aws-cdk/aws-ecs/lib/index.ts
  packages/@aws-cdk/aws-ecs/test/cluster.test.ts
  packages/@aws-cdk/aws-ecs/test/ec2/integ.bottlerocket.expected.json
  packages/@aws-cdk/aws-ecs/test/ec2/integ.firelens-s3-config.expected.json
  packages/@aws-cdk/aws-ecs/test/ec2/integ.graviton-bottlerocket.expected.json
  packages/@aws-cdk/aws-ecs/test/fargate/integ.firelens-cloudwatch.expected.json
Labels: contribution/core

#16426 feat(assertions): capture matching value
  packages/@aws-cdk/assertions/README.md
  packages/@aws-cdk/assertions/lib/capture.ts
  packages/@aws-cdk/assertions/lib/index.ts
  packages/@aws-cdk/assertions/lib/match.ts
  packages/@aws-cdk/assertions/lib/matcher.ts
  packages/@aws-cdk/assertions/lib/private/type.ts
  packages/@aws-cdk/assertions/test/capture.test.ts
  packages/@aws-cdk/assertions/test/match.test.ts
  packages/@aws-cdk/pipelines/package.json
  packages/@aws-cdk/pipelines/test/blueprint/logicalid-stability.test.ts
  packages/@aws-cdk/pipelines/test/codepipeline/codepipeline-sources.test.ts
  packages/@aws-cdk/pipelines/test/compliance/basic-behavior.test.ts
  packages/@aws-cdk/pipelines/test/compliance/environments.test.ts
  packages/@aws-cdk/pipelines/test/compliance/escape-hatching.test.ts
  packages/@aws-cdk/pipelines/test/docker-credentials.test.ts
  packages/@aws-cdk/pipelines/test/testhelpers/index.ts
  packages/@aws-cdk/pipelines/test/testhelpers/matchers.ts
Labels: contribution/core

#16429 fix(core): asset hash of symlinked dir is wrong
  packages/@aws-cdk/core/lib/fs/fingerprint.ts
  packages/@aws-cdk/core/test/staging.test.ts
Labels: contribution/core

#16050 fix(cloudformation-diff): cdk diff not picking up differences if old/new value is in format n.n.n
  packages/@aws-cdk/cloudformation-diff/lib/diff/util.ts
  packages/@aws-cdk/cloudformation-diff/test/diff-template.test.ts
Labels: p1, effort/small, @aws-cdk/cloudformation-diff

#15764 feat(sns): adding support for firehose subscription protocol
  packages/@aws-cdk/aws-sns/README.md
  packages/@aws-cdk/aws-sns/lib/subscription.ts
  packages/@aws-cdk/aws-sns/package.json
  packages/@aws-cdk/aws-sns/test/subscription.test.ts
Labels: p1, @aws-cdk/aws-sns, effort/small

#16394 feat(neptune): add engine version 1.0.5.0
  packages/@aws-cdk/aws-neptune/lib/cluster.ts
Labels: pr-linter/exempt-readme, pr-linter/exempt-test

#16083 fix(logs): log retention fails with OperationAbortedException
  packages/@aws-cdk/aws-logs/lib/log-retention-provider/index.ts
  packages/@aws-cdk/aws-logs/test/test.log-retention-provider.ts
Labels: p1, effort/small, @aws-cdk/aws-logs

#16424 docs(pipelines): CLI not compatible with the library used by your application
  packages/@aws-cdk/pipelines/README.md
  packages/@aws-cdk/pipelines/lib/codepipeline/codepipeline.ts
Labels: contribution/core

#15750 docs(assets): tarball path should be absolute
  packages/@aws-cdk/aws-ecr-assets/lib/tarball-asset.ts
  packages/@aws-cdk/aws-ecs/lib/container-image.ts
Labels: contribution/core

#15848 feat(batch): fargate support for jobs
  packages/@aws-cdk/aws-batch/README.md
  packages/@aws-cdk/aws-batch/lib/compute-environment.ts
  packages/@aws-cdk/aws-batch/lib/job-definition.ts
  packages/@aws-cdk/aws-batch/test/compute-environment.test.ts
  packages/@aws-cdk/aws-batch/test/integ.batch.expected.json
  packages/@aws-cdk/aws-batch/test/integ.batch.ts
  packages/@aws-cdk/aws-batch/test/job-definition.test.ts
  packages/@aws-cdk/aws-events-targets/test/batch/integ.job-definition-events.expected.json
  packages/@aws-cdk/aws-stepfunctions-tasks/test/batch/integ.run-batch-job.expected.json
  packages/@aws-cdk/aws-stepfunctions-tasks/test/batch/integ.submit-job.expected.json
Labels: response-requested

#16470 chore(deps): bump version of `conventional-commits-parser`
  tools/cdk-release/package.json
  yarn.lock
Labels: contribution/core

#16469 chore(deps): bump `proxy-agent` to `5.0.0`
  packages/aws-cdk/package.json
  yarn.lock
Labels: contribution/core

#16456 feat(assertions): match into serialized json
  packages/@aws-cdk/assertions/README.md
  packages/@aws-cdk/assertions/lib/match.ts
  packages/@aws-cdk/assertions/test/match.test.ts
  packages/@aws-cdk/pipelines/package.json
  packages/@aws-cdk/pipelines/test/compliance/assets.test.ts
  packages/@aws-cdk/pipelines/test/compliance/docker-credentials.test.ts
  packages/@aws-cdk/pipelines/test/compliance/security-check.test.ts
  packages/@aws-cdk/pipelines/test/compliance/self-mutation.test.ts
  packages/@aws-cdk/pipelines/test/compliance/stack-ordering.test.ts
  packages/@aws-cdk/pipelines/test/compliance/synths.test.ts
  packages/@aws-cdk/pipelines/test/compliance/validations.test.ts
  packages/@aws-cdk/pipelines/test/testhelpers/index.ts
  packages/@aws-cdk/pipelines/test/testhelpers/matchers.ts
  packages/@aws-cdk/pipelines/test/testhelpers/testmatchers.ts
Labels: contribution/core

#15931 feat(redshift): manage database users and tables via cdk
  packages/@aws-cdk/aws-redshift/README.md
  packages/@aws-cdk/aws-redshift/lib/database-options.ts
  packages/@aws-cdk/aws-redshift/lib/index.ts
  packages/@aws-cdk/aws-redshift/lib/private/database-query-provider/handler-name.ts
  packages/@aws-cdk/aws-redshift/lib/private/database-query-provider/index.ts
  packages/@aws-cdk/aws-redshift/lib/private/database-query-provider/privileges.ts
  packages/@aws-cdk/aws-redshift/lib/private/database-query-provider/table.ts
  packages/@aws-cdk/aws-redshift/lib/private/database-query-provider/user.ts
  packages/@aws-cdk/aws-redshift/lib/private/database-query-provider/util.ts
  packages/@aws-cdk/aws-redshift/lib/private/database-query.ts
  packages/@aws-cdk/aws-redshift/lib/private/handler-props.ts
  packages/@aws-cdk/aws-redshift/lib/private/privileges.ts
  packages/@aws-cdk/aws-redshift/lib/table.ts
  packages/@aws-cdk/aws-redshift/lib/user.ts
  packages/@aws-cdk/aws-redshift/package.json
  packages/@aws-cdk/aws-redshift/rosetta/cluster.ts-fixture
  packages/@aws-cdk/aws-redshift/rosetta/default.ts-fixture
  packages/@aws-cdk/aws-redshift/test/database-query-provider/index.test.ts
  packages/@aws-cdk/aws-redshift/test/database-query-provider/privileges.test.ts
  packages/@aws-cdk/aws-redshift/test/database-query-provider/table.test.ts
  packages/@aws-cdk/aws-redshift/test/database-query-provider/user.test.ts
  packages/@aws-cdk/aws-redshift/test/database-query.test.ts
  packages/@aws-cdk/aws-redshift/test/integ.database.expected.json
  packages/@aws-cdk/aws-redshift/test/integ.database.ts
  packages/@aws-cdk/aws-redshift/test/privileges.test.ts
  packages/@aws-cdk/aws-redshift/test/table.test.ts
  packages/@aws-cdk/aws-redshift/test/user.test.ts
Labels: contribution/core, @aws-cdk/aws-redshift

#16111 feat(lambda): configure workdir for docker image based functions
  packages/@aws-cdk/aws-lambda/README.md
  packages/@aws-cdk/aws-lambda/lib/code.ts
  packages/@aws-cdk/aws-lambda/lib/function.ts
  packages/@aws-cdk/aws-lambda/test/code.test.ts
  packages/@aws-cdk/aws-lambda/test/function.test.ts
Labels: @aws-cdk/aws-lambda, effort/small

#16281 feat(lambda): use bundling docker image from ECR public for dotnet and go runtimes
  packages/@aws-cdk/aws-lambda/lib/runtime.ts
  packages/@aws-cdk/aws-lambda/test/runtime.test.ts
Labels: @aws-cdk/aws-lambda, effort/small, pr-linter/exempt-readme

#16464 fix(config): the IGW mapping to correct resource type
  packages/@aws-cdk/aws-config/lib/rule.ts
Labels: pr-linter/exempt-test

#16495 chore(release): 2.0.0-rc.22
  CHANGELOG.v2.md
  version.v2.json
Labels: pr/auto-approve

#15220 feat(s3-deployment): enable efs support for handling large files in lambda
  packages/@aws-cdk/aws-ecs/test/ec2/integ.environment-file.expected.json
  packages/@aws-cdk/aws-s3-deployment/README.md
  packages/@aws-cdk/aws-s3-deployment/lib/bucket-deployment.ts
  packages/@aws-cdk/aws-s3-deployment/lib/lambda/index.py
  packages/@aws-cdk/aws-s3-deployment/package.json
  packages/@aws-cdk/aws-s3-deployment/test/bucket-deployment.test.ts
  packages/@aws-cdk/aws-s3-deployment/test/integ.bucket-deployment-cloudfront.expected.json
  packages/@aws-cdk/aws-s3-deployment/test/integ.bucket-deployment.expected.json
  packages/@aws-cdk/aws-s3-deployment/test/integ.bucket-deployment.ts
Labels: response-requested

#16475 feat(stepfunctions-tasks): support Associate Workflow Executions on StepFunctionsStartExecution via associateWithParent property
  packages/@aws-cdk/aws-stepfunctions-tasks/README.md
  packages/@aws-cdk/aws-stepfunctions-tasks/lib/stepfunctions/start-execution.ts
  packages/@aws-cdk/aws-stepfunctions-tasks/test/stepfunctions/start-execution.test.ts
Labels: contribution/core

#16228 fix(SSM API docs): Typo `SecretString` -> `SecureString` and note how SecureStrings cannot be created via CDK
  packages/@aws-cdk/aws-ssm/README.md
  packages/@aws-cdk/aws-ssm/lib/parameter.ts
Labels: docs/generated, pr-linter/exempt-test

#16454 feat(assertions): findXxx() APIs now includes the logical id as part of its result
  packages/@aws-cdk/assertions/README.md
  packages/@aws-cdk/assertions/lib/private/mappings.ts
  packages/@aws-cdk/assertions/lib/private/outputs.ts
  packages/@aws-cdk/assertions/lib/private/resources.ts
  packages/@aws-cdk/assertions/lib/private/section.ts
  packages/@aws-cdk/assertions/lib/template.ts
  packages/@aws-cdk/assertions/test/private/section.test.ts
  packages/@aws-cdk/assertions/test/template.test.ts
  packages/@aws-cdk/aws-apigatewayv2/test/http/api.test.ts
  packages/@aws-cdk/aws-cloudwatch/test/dashboard.test.ts
Labels: contribution/core

#16504 chore: migrate even more modules to jest
  packages/@aws-cdk/assets/.gitignore
  packages/@aws-cdk/assets/.npmignore
  packages/@aws-cdk/assets/jest.config.js
  packages/@aws-cdk/assets/package.json
  packages/@aws-cdk/assets/test/compat.test.ts
  packages/@aws-cdk/assets/test/staging.test.ts
  packages/@aws-cdk/assets/test/test.compat.ts
  packages/@aws-cdk/aws-codedeploy/.gitignore
  packages/@aws-cdk/aws-codedeploy/.npmignore
  packages/@aws-cdk/aws-codedeploy/jest.config.js
  packages/@aws-cdk/aws-codedeploy/package.json
  packages/@aws-cdk/aws-codedeploy/test/ecs/application.test.ts
  packages/@aws-cdk/aws-codedeploy/test/ecs/deployment-group.test.ts
  packages/@aws-cdk/aws-codedeploy/test/ecs/test.application.ts
  packages/@aws-cdk/aws-codedeploy/test/ecs/test.deployment-group.ts
  packages/@aws-cdk/aws-codedeploy/test/lambda/application.test.ts
  packages/@aws-cdk/aws-codedeploy/test/lambda/custom-deployment-config.test.ts
  packages/@aws-cdk/aws-codedeploy/test/lambda/deployment-group.test.ts
  packages/@aws-cdk/aws-codedeploy/test/lambda/test.application.ts
  packages/@aws-cdk/aws-codedeploy/test/lambda/test.custom-deployment-config.ts
  packages/@aws-cdk/aws-codedeploy/test/lambda/test.deployment-group.ts
  packages/@aws-cdk/aws-codedeploy/test/server/deployment-config.test.ts
  packages/@aws-cdk/aws-codedeploy/test/server/deployment-group.test.ts
  packages/@aws-cdk/aws-codedeploy/test/server/test.deployment-config.ts
  packages/@aws-cdk/aws-codedeploy/test/server/test.deployment-group.ts
  packages/@aws-cdk/aws-config/.gitignore
  packages/@aws-cdk/aws-config/.npmignore
  packages/@aws-cdk/aws-config/jest.config.js
  packages/@aws-cdk/aws-config/package.json
  packages/@aws-cdk/aws-config/test/managed-rules.test.ts
  packages/@aws-cdk/aws-config/test/rule.test.ts
  packages/@aws-cdk/aws-dynamodb-global/.gitignore
  packages/@aws-cdk/aws-dynamodb-global/.npmignore
  packages/@aws-cdk/aws-dynamodb-global/jest.config.js
  packages/@aws-cdk/aws-dynamodb-global/package.json
  packages/@aws-cdk/aws-dynamodb-global/test/dynamodb-global.test.ts
  packages/@aws-cdk/aws-dynamodb-global/test/test.dynamodb.global.ts
  packages/@aws-cdk/aws-ssm/.gitignore
  packages/@aws-cdk/aws-ssm/.npmignore
  packages/@aws-cdk/aws-ssm/jest.config.js
  packages/@aws-cdk/aws-ssm/package.json
  packages/@aws-cdk/aws-ssm/test/parameter-store-string.test.ts
  packages/@aws-cdk/aws-ssm/test/parameter.test.ts
  packages/@aws-cdk/aws-ssm/test/ssm-document.test.ts
  packages/@aws-cdk/aws-ssm/test/test.parameter-store-string.ts
  packages/@aws-cdk/aws-ssm/test/test.parameter.ts
  packages/@aws-cdk/aws-ssm/test/test.ssm-document.ts
  packages/@aws-cdk/aws-ssm/test/test.util.ts
  packages/@aws-cdk/aws-ssm/test/util.test.ts
Labels: contribution/core

#16524 feat(cfnspec): cloudformation spec v41.1.0
  packages/monocdk/rosetta/cluster.ts-fixture
  packages/monocdk/rosetta/migrate-opensearch.ts-fixture
Labels: pr-linter/exempt-test, pr/auto-approve

#16326 feat(ecs-service-extensions): Publish Extension
  packages/@aws-cdk-containers/ecs-service-extensions/README.md
  packages/@aws-cdk-containers/ecs-service-extensions/lib/extensions/index.ts
  packages/@aws-cdk-containers/ecs-service-extensions/lib/extensions/injecter.ts
  packages/@aws-cdk-containers/ecs-service-extensions/test/injecter.test.ts
  packages/@aws-cdk-containers/ecs-service-extensions/test/integ.publish-subscribe.expected.json
  packages/@aws-cdk-containers/ecs-service-extensions/test/integ.publish-subscribe.ts
Labels: @aws-cdk-containers/ecs-service-extensions

#16526 docs(pipelines): fix small issues in README
  packages/@aws-cdk/pipelines/README.md
Labels: contribution/core

#16533 chore: migrate more modules to jest
  packages/@aws-cdk/aws-ecs-patterns/.gitignore
  packages/@aws-cdk/aws-ecs-patterns/.npmignore
  packages/@aws-cdk/aws-ecs-patterns/jest.config.js
  packages/@aws-cdk/aws-ecs-patterns/package.json
  packages/@aws-cdk/aws-ecs-patterns/test/ec2/l3s-v2.test.ts
  packages/@aws-cdk/aws-ecs-patterns/test/ec2/l3s.test.ts
  packages/@aws-cdk/aws-ecs-patterns/test/ec2/queue-processing-ecs-service.test.ts
  packages/@aws-cdk/aws-ecs-patterns/test/ec2/scheduled-ecs-task.test.ts
  packages/@aws-cdk/aws-ecs-patterns/test/ec2/test.l3s-v2.ts
  packages/@aws-cdk/aws-ecs-patterns/test/ec2/test.l3s.ts
  packages/@aws-cdk/aws-ecs-patterns/test/ec2/test.queue-processing-ecs-service.ts
  packages/@aws-cdk/aws-ecs-patterns/test/ec2/test.scheduled-ecs-task.ts
  packages/@aws-cdk/aws-ecs-patterns/test/fargate/load-balanced-fargate-service-v2.test.ts
  packages/@aws-cdk/aws-ecs-patterns/test/fargate/load-balanced-fargate-service.test.ts
  packages/@aws-cdk/aws-ecs-patterns/test/fargate/queue-processing-fargate-service.test.ts
  packages/@aws-cdk/aws-ecs-patterns/test/fargate/scheduled-fargate-task.test.ts
  packages/@aws-cdk/aws-ecs-patterns/test/fargate/test.load-balanced-fargate-service-v2.ts
  packages/@aws-cdk/aws-ecs-patterns/test/fargate/test.load-balanced-fargate-service.ts
  packages/@aws-cdk/aws-ecs-patterns/test/fargate/test.queue-processing-fargate-service.ts
  packages/@aws-cdk/aws-ecs-patterns/test/fargate/test.scheduled-fargate-task.ts
  packages/@aws-cdk/aws-sqs/.gitignore
  packages/@aws-cdk/aws-sqs/.npmignore
  packages/@aws-cdk/aws-sqs/jest.config.js
  packages/@aws-cdk/aws-sqs/package.json
  packages/@aws-cdk/aws-sqs/test/sqs.test.ts
  packages/@aws-cdk/aws-sqs/test/test.sqs.ts
Labels: contribution/core

#16116 chore(ec2): deprecate security group name accessor
  packages/@aws-cdk/aws-ec2/lib/security-group.ts
Labels: p1, @aws-cdk/aws-ec2, effort/small

#16561 chore: transfer BenChaimberg ownership over to kaizen3031593 and comcalvi
  .github/workflows/issue-label-assign.yml
Labels: contribution/core

#16576 chore(init-templates): fix v2 Java init template tests
  packages/aws-cdk/lib/init-templates/v2/app/java/src/test/java/com/myorg/%name.PascalCased%Test.template.java
Labels: contribution/core

#16578 chore(aws-cdk): correct construct-versions for v2 init templates
  packages/aws-cdk/lib/init-templates/v2/app/csharp/src/%name.PascalCased%/%name.PascalCased%.template.csproj
  packages/aws-cdk/lib/init-templates/v2/app/fsharp/src/%name.PascalCased%/%name.PascalCased%.template.fsproj
  packages/aws-cdk/lib/init-templates/v2/app/java/pom.template.xml
  packages/aws-cdk/lib/init-templates/v2/app/java/src/main/java/com/myorg/%name.PascalCased%Stack.template.java
  packages/aws-cdk/lib/init-templates/v2/app/java/src/test/java/com/myorg/%name.PascalCased%Test.template.java
  packages/aws-cdk/lib/init-templates/v2/app/javascript/lib/%name%-stack.template.js
  packages/aws-cdk/lib/init-templates/v2/app/javascript/package.template.json
  packages/aws-cdk/lib/init-templates/v2/app/python/%name.PythonModule%/%name.PythonModule%_stack.template.py
  packages/aws-cdk/lib/init-templates/v2/app/python/setup.template.py
  packages/aws-cdk/lib/init-templates/v2/app/typescript/lib/%name%-stack.template.ts
  packages/aws-cdk/lib/init-templates/v2/app/typescript/package.template.json
  packages/aws-cdk/lib/init-templates/v2/lib/typescript/lib/index.template.ts
  packages/aws-cdk/lib/init-templates/v2/lib/typescript/package.template.json
  packages/aws-cdk/lib/init-templates/v2/sample-app/csharp/src/%name.PascalCased%/%name.PascalCased%.template.csproj
  packages/aws-cdk/lib/init-templates/v2/sample-app/csharp/src/%name.PascalCased%/%name.PascalCased%Stack.template.cs
  packages/aws-cdk/lib/init-templates/v2/sample-app/fsharp/src/%name.PascalCased%/%name.PascalCased%.template.fsproj
  packages/aws-cdk/lib/init-templates/v2/sample-app/java/pom.template.xml
  packages/aws-cdk/lib/init-templates/v2/sample-app/java/src/main/java/com/myorg/%name.PascalCased%App.template.java
  packages/aws-cdk/lib/init-templates/v2/sample-app/java/src/main/java/com/myorg/%name.PascalCased%Stack.template.java
  packages/aws-cdk/lib/init-templates/v2/sample-app/java/src/test/java/com/myorg/%name.PascalCased%StackTest.template.java
  packages/aws-cdk/lib/init-templates/v2/sample-app/javascript/package.template.json
  packages/aws-cdk/lib/init-templates/v2/sample-app/python/%name.PythonModule%/%name.PythonModule%_stack.template.py
  packages/aws-cdk/lib/init-templates/v2/sample-app/python/setup.template.py
  packages/aws-cdk/lib/init-templates/v2/sample-app/typescript/lib/%name%-stack.template.ts
  packages/aws-cdk/lib/init-templates/v2/sample-app/typescript/package.template.json
  packages/aws-cdk/lib/init.ts
  packages/aws-cdk/package.json
Labels: contribution/core

#16584 fix: permissions for github actions
  .github/workflows/close-stale-issues.yml
Labels: pr-linter/exempt-test

#16587 fix: remove invalid entry from stale issue bot config
  .github/workflows/close-stale-issues.yml
Labels: pr-linter/exempt-readme, pr-linter/exempt-test

#16589 chore(merge-back): 1.124.0
  CHANGELOG.md
  version.v1.json
Labels: pr/no-squash, pr/auto-approve

#16585 chore: migrate all remaining modules from NodeUnit to Jest
  packages/@aws-cdk/aws-cloudformation/.gitignore
  packages/@aws-cdk/aws-cloudformation/.npmignore
  packages/@aws-cdk/aws-cloudformation/jest.config.js
  packages/@aws-cdk/aws-cloudformation/package.json
  packages/@aws-cdk/aws-cloudformation/test/deps.test.ts
  packages/@aws-cdk/aws-cloudformation/test/nested-stack.test.ts
  packages/@aws-cdk/aws-cloudformation/test/resource.test.ts
  packages/@aws-cdk/aws-cloudformation/test/test.deps.ts
  packages/@aws-cdk/aws-cloudformation/test/test.nested-stack.ts
  packages/@aws-cdk/aws-cloudformation/test/test.resource.ts
  packages/@aws-cdk/aws-codebuild/.gitignore
  packages/@aws-cdk/aws-codebuild/.npmignore
  packages/@aws-cdk/aws-codebuild/jest.config.js
  packages/@aws-cdk/aws-codebuild/package.json
  packages/@aws-cdk/aws-codebuild/test/build-spec.test.ts
  packages/@aws-cdk/aws-codebuild/test/codebuild.test.ts
  packages/@aws-cdk/aws-codebuild/test/linux-gpu-build-image.test.ts
  packages/@aws-cdk/aws-codebuild/test/notification-rule.test.ts
  packages/@aws-cdk/aws-codebuild/test/project.test.ts
  packages/@aws-cdk/aws-codebuild/test/report-group.test.ts
  packages/@aws-cdk/aws-codebuild/test/test.build-spec.ts
  packages/@aws-cdk/aws-codebuild/test/test.codebuild.ts
  packages/@aws-cdk/aws-codebuild/test/test.linux-gpu-build-image.ts
  packages/@aws-cdk/aws-codebuild/test/test.notification-rule.ts
  packages/@aws-cdk/aws-codebuild/test/test.project.ts
  packages/@aws-cdk/aws-codebuild/test/test.report-group.ts
  packages/@aws-cdk/aws-codebuild/test/test.untrusted-code-boundary.ts
  packages/@aws-cdk/aws-codebuild/test/untrusted-code-boundary.test.ts
  packages/@aws-cdk/cfnspec/.gitignore
  packages/@aws-cdk/cfnspec/.npmignore
  packages/@aws-cdk/cfnspec/jest.config.js
  packages/@aws-cdk/cfnspec/package.json
  packages/@aws-cdk/cfnspec/test/augmentation.test.ts
  packages/@aws-cdk/cfnspec/test/build.test.ts
  packages/@aws-cdk/cfnspec/test/canned-metrics.test.ts
  packages/@aws-cdk/cfnspec/test/cfnlint-annotations.test.ts
  packages/@aws-cdk/cfnspec/test/filtered-specification.test.ts
  packages/@aws-cdk/cfnspec/test/namespaces.test.ts
  packages/@aws-cdk/cfnspec/test/scrutiny.test.ts
  packages/@aws-cdk/cfnspec/test/spec-validators.ts
  packages/@aws-cdk/cfnspec/test/test.augmentation.ts
  packages/@aws-cdk/cfnspec/test/test.build.ts
  packages/@aws-cdk/cfnspec/test/test.canned-metrics.ts
  packages/@aws-cdk/cfnspec/test/test.cfnlint-annotations.ts
  packages/@aws-cdk/cfnspec/test/test.filtered-specification.ts
  packages/@aws-cdk/cfnspec/test/test.namespaces.ts
  packages/@aws-cdk/cfnspec/test/test.scrutiny.ts
Labels: contribution/core

#16377 chore: forward merge 'master' into 'v2-main'
  packages/@aws-cdk/aws-apigatewayv2/lib/http/api.ts
  packages/@aws-cdk/aws-autoscaling/lib/auto-scaling-group.ts
  packages/@aws-cdk/aws-ec2/README.md
  packages/@aws-cdk/aws-ec2/lib/cfn-init.ts
  packages/@aws-cdk/aws-ec2/lib/instance.ts
  packages/@aws-cdk/aws-ec2/lib/util.ts
  packages/@aws-cdk/aws-ec2/lib/vpc-endpoint.ts
  packages/@aws-cdk/aws-ec2/lib/vpc.ts
  packages/@aws-cdk/aws-ec2/package.json
  packages/@aws-cdk/aws-ec2/test/bastion-host.test.ts
  packages/@aws-cdk/aws-ec2/test/cfn-init.test.ts
  packages/@aws-cdk/aws-ec2/test/integ.reserved-private-subnet.ts
  packages/@aws-cdk/aws-ec2/test/integ.vpc-gateway.ts
  packages/@aws-cdk/aws-ec2/test/integ.vpc-networkacl.ts
  packages/@aws-cdk/aws-ec2/test/vpc-endpoint.test.ts
  packages/@aws-cdk/aws-ec2/test/vpc.from-lookup.test.ts
  packages/@aws-cdk/aws-ec2/test/vpc.test.ts
  packages/@aws-cdk/aws-elasticloadbalancingv2/lib/nlb/network-listener.ts
  packages/@aws-cdk/aws-elasticloadbalancingv2/lib/shared/enums.ts
  packages/@aws-cdk/aws-elasticloadbalancingv2/test/nlb/listener.test.ts
  packages/@aws-cdk/aws-kms/README.md
  packages/@aws-cdk/aws-kms/lib/index.ts
  packages/@aws-cdk/aws-kms/lib/key-lookup.ts
  packages/@aws-cdk/aws-kms/lib/key.ts
  packages/@aws-cdk/aws-kms/package.json
  packages/@aws-cdk/aws-kms/test/key.from-lookup.test.ts
  packages/@aws-cdk/aws-lambda/README.md
  packages/@aws-cdk/aws-lambda/lib/runtime.ts
  packages/@aws-cdk/aws-lambda/test/integ.runtime.inlinecode.expected.json
  packages/@aws-cdk/aws-lambda/test/integ.runtime.inlinecode.ts
  packages/@aws-cdk/aws-stepfunctions-tasks/lib/athena/start-query-execution.ts
  packages/@aws-cdk/aws-stepfunctions-tasks/test/athena/start-query-execution.test.ts
  packages/@aws-cdk/cloud-assembly-schema/lib/cloud-assembly/context-queries.ts
  packages/@aws-cdk/cloud-assembly-schema/schema/cloud-assembly.schema.json
  packages/@aws-cdk/cloud-assembly-schema/schema/cloud-assembly.version.json
  packages/@aws-cdk/cx-api/lib/context/key.ts
  packages/@aws-cdk/cx-api/lib/index.ts
  packages/aws-cdk/lib/api/aws-auth/sdk.ts
  packages/aws-cdk/lib/context-providers/index.ts
  packages/aws-cdk/lib/context-providers/keys.ts
  packages/aws-cdk/test/context-providers/keys.test.ts
  packages/aws-cdk/test/util/mock-sdk.ts
Labels: pr/no-squash, pr/forward-merge, pr/auto-approve

#15352 docs(synthetics): canary schedule section in README
  packages/@aws-cdk/aws-synthetics/README.md
Labels: @aws-cdk/aws-synthetics

#16615 chore(release): 2.0.0-rc.23
  CHANGELOG.v2.md
  version.v2.json
Labels: pr/auto-approve

#16610 fix(route53-targets): ApiGateway does not accept RestApiBase
  packages/@aws-cdk/aws-route53-targets/lib/api-gateway-domain-name.ts
  packages/@aws-cdk/aws-route53-targets/test/apigateway-target.test.ts
Labels: contribution/core

#16606 chore(aws-cdk-lib): add helm and kubectl to aws-cdk-lib NOTICE
  packages/aws-cdk-lib/NOTICE
  packages/aws-cdk-lib/package.json
Labels: contribution/core

#15810 feat(aws-apprunner): support the Service L2 construct
  packages/@aws-cdk/aws-apprunner/README.md
  packages/@aws-cdk/aws-apprunner/lib/index.ts
  packages/@aws-cdk/aws-apprunner/lib/service.ts
  packages/@aws-cdk/aws-apprunner/package.json
  packages/@aws-cdk/aws-apprunner/test/apprunner.test.ts
  packages/@aws-cdk/aws-apprunner/test/docker.assets/Dockerfile
  packages/@aws-cdk/aws-apprunner/test/integ.service.expected.json
  packages/@aws-cdk/aws-apprunner/test/integ.service.ts
  packages/@aws-cdk/aws-apprunner/test/service.test.ts
Labels: @aws-cdk/aws-apprunner

#16609 fix(aws-eks): Support for http proxy in EKS onEvent lambda
  packages/@aws-cdk/aws-eks/.npmignore
  packages/@aws-cdk/aws-eks/lib/cluster-resource-handler/.no-packagejson-validator
  packages/@aws-cdk/aws-eks/lib/cluster-resource-handler/cluster.ts
  packages/@aws-cdk/aws-eks/lib/cluster-resource-handler/common.ts
  packages/@aws-cdk/aws-eks/lib/cluster-resource-handler/index.ts
  packages/@aws-cdk/aws-eks/lib/cluster-resource-handler/package.json
  packages/@aws-cdk/aws-eks/lib/cluster-resource-provider.ts
  packages/@aws-cdk/aws-eks/package.json
  packages/@aws-cdk/aws-eks/test/cluster.test.ts
  packages/@aws-cdk/aws-eks/test/integ.eks-cluster-handlers-vpc.expected.json
  packages/@aws-cdk/aws-eks/test/integ.eks-cluster-private-endpoint.expected.json
  packages/@aws-cdk/aws-eks/test/integ.eks-cluster.expected.json
  packages/@aws-cdk/aws-eks/test/integ.fargate-cluster.expected.json
  packages/@aws-cdk/aws-stepfunctions-tasks/test/eks/integ.call.expected.json
Labels: p1, @aws-cdk/aws-eks, contribution/core

#16628 chore: move modules from assert to assertions
  packages/@aws-cdk/assets/package.json
  packages/@aws-cdk/assets/test/compat.test.ts
  packages/@aws-cdk/assets/test/staging.test.ts
  packages/@aws-cdk/aws-acmpca/package.json
  packages/@aws-cdk/aws-acmpca/test/acmpca.test.ts
  packages/@aws-cdk/aws-codeguruprofiler/package.json
  packages/@aws-cdk/aws-codeguruprofiler/test/codeguruprofiler.test.ts
  packages/@aws-cdk/aws-codeguruprofiler/test/profiling-group.test.ts
  packages/@aws-cdk/aws-codestarnotifications/package.json
  packages/@aws-cdk/aws-codestarnotifications/test/notification-rule.test.ts
  packages/@aws-cdk/aws-events/package.json
  packages/@aws-cdk/aws-events/test/archive.test.ts
  packages/@aws-cdk/aws-events/test/event-bus.test.ts
  packages/@aws-cdk/aws-events/test/input.test.ts
  packages/@aws-cdk/aws-events/test/rule.test.ts
  packages/@aws-cdk/aws-iam/package.json
  packages/@aws-cdk/aws-iam/test/auto-cross-stack-refs.test.ts
  packages/@aws-cdk/aws-iam/test/cross-account.test.ts
  packages/@aws-cdk/aws-iam/test/escape-hatch.test.ts
  packages/@aws-cdk/aws-iam/test/grant.test.ts
  packages/@aws-cdk/aws-iam/test/group.test.ts
  packages/@aws-cdk/aws-iam/test/immutable-role.test.ts
  packages/@aws-cdk/aws-iam/test/lazy-role.test.ts
  packages/@aws-cdk/aws-iam/test/managed-policy.test.ts
  packages/@aws-cdk/aws-iam/test/oidc-provider.test.ts
  packages/@aws-cdk/aws-iam/test/permissions-boundary.test.ts
  packages/@aws-cdk/aws-iam/test/policy-document.test.ts
  packages/@aws-cdk/aws-iam/test/policy-statement.test.ts
  packages/@aws-cdk/aws-iam/test/policy.test.ts
  packages/@aws-cdk/aws-iam/test/principals.test.ts
  packages/@aws-cdk/aws-iam/test/role.from-role-arn.test.ts
  packages/@aws-cdk/aws-iam/test/role.test.ts
  packages/@aws-cdk/aws-iam/test/saml-provider.test.ts
  packages/@aws-cdk/aws-iam/test/user.test.ts
  packages/@aws-cdk/aws-kms/package.json
  packages/@aws-cdk/aws-kms/test/alias.test.ts
  packages/@aws-cdk/aws-kms/test/key.from-lookup.test.ts
  packages/@aws-cdk/aws-kms/test/key.test.ts
  packages/@aws-cdk/aws-kms/test/via-service-principal.test.ts
  packages/@aws-cdk/aws-signer/package.json
  packages/@aws-cdk/aws-signer/test/signing-profile.test.ts
Labels: contribution/core

#16631 feat(eks): add warning to fargateProfile
  packages/@aws-cdk/aws-eks/lib/fargate-profile.ts
Labels: p1, @aws-cdk/aws-eks, effort/small, contribution/core, pr-linter/exempt-readme, pr-linter/exempt-test

#16632 docs(eks): clarify requirements to use subnetSelection
  packages/@aws-cdk/aws-eks/lib/fargate-profile.ts
Labels: p1, @aws-cdk/aws-eks, effort/small, contribution/core

#16651 revert(aws-eks): "fix(aws-eks): Support for http proxy in EKS onEvent lambda"
  packages/@aws-cdk/aws-eks/.npmignore
  packages/@aws-cdk/aws-eks/lib/cluster-resource-handler/.no-packagejson-validator
  packages/@aws-cdk/aws-eks/lib/cluster-resource-handler/cluster.ts
  packages/@aws-cdk/aws-eks/lib/cluster-resource-handler/common.ts
  packages/@aws-cdk/aws-eks/lib/cluster-resource-handler/index.ts
  packages/@aws-cdk/aws-eks/lib/cluster-resource-handler/package.json
  packages/@aws-cdk/aws-eks/lib/cluster-resource-provider.ts
  packages/@aws-cdk/aws-eks/package.json
  packages/@aws-cdk/aws-eks/test/cluster.test.ts
  packages/@aws-cdk/aws-eks/test/integ.eks-cluster-handlers-vpc.expected.json
  packages/@aws-cdk/aws-eks/test/integ.eks-cluster-private-endpoint.expected.json
  packages/@aws-cdk/aws-eks/test/integ.eks-cluster.expected.json
  packages/@aws-cdk/aws-eks/test/integ.fargate-cluster.expected.json
  packages/@aws-cdk/aws-stepfunctions-tasks/test/eks/integ.call.expected.json
Labels: @aws-cdk/aws-eks, contribution/core

#16481 chore(individual-pkg-gen): remove L1s from alpha modules
  packages/@aws-cdk/aws-apprunner/lib/service.ts
  packages/@aws-cdk/aws-glue/test/table.test.ts
  packages/@aws-cdk/aws-kinesisanalytics-flink/lib/application.ts
  packages/@aws-cdk/aws-kinesisfirehose-destinations/lib/private/helpers.ts
  packages/@aws-cdk/aws-msk/lib/cluster.ts
  packages/@aws-cdk/aws-redshift/test/cluster.test.ts
  packages/aws-cdk-migration/lib/rewrite.ts
  packages/aws-cdk-migration/test/rewrite.test.ts
  packages/awslint/.eslintrc.js
  tools/cdk-build-tools/config/eslintrc.js
  tools/eslint-plugin-cdk/lib/index.ts
  tools/eslint-plugin-cdk/lib/rules/invalid-cfn-imports.ts
  tools/eslint-plugin-cdk/test/rules/fixtures.test.ts
  tools/eslint-plugin-cdk/test/rules/fixtures/invalid-cfn-imports/cfn-constructor.error.txt
  tools/eslint-plugin-cdk/test/rules/fixtures/invalid-cfn-imports/cfn-constructor.ts
  tools/eslint-plugin-cdk/test/rules/fixtures/invalid-cfn-imports/cfn-import-from-relative-path.error.txt
  tools/eslint-plugin-cdk/test/rules/fixtures/invalid-cfn-imports/cfn-import-from-relative-path.ts
  tools/eslint-plugin-cdk/test/rules/fixtures/invalid-cfn-imports/cfn-import-mixed-with-other-imports.error.txt
  tools/eslint-plugin-cdk/test/rules/fixtures/invalid-cfn-imports/cfn-import-mixed-with-other-imports.ts
  tools/eslint-plugin-cdk/test/rules/fixtures/invalid-cfn-imports/eslintrc.js
  tools/eslint-plugin-cdk/test/rules/fixtures/invalid-cfn-imports/reference-cfn-construct-on-barrel-import.error.txt
  tools/eslint-plugin-cdk/test/rules/fixtures/invalid-cfn-imports/reference-cfn-construct-on-barrel-import.ts
  tools/individual-pkg-gen/copy-files-removing-deps.ts
  tools/pkglint/.eslintrc.js
Labels: contribution/core

#16674 chore: enable publishing of independent alpha modules
  lerna.json
  package.json
  scripts/bump.js
  tools/individual-pkg-gen/README.md
  tools/individual-pkg-gen/bin/individual-pkg-gen
  tools/individual-pkg-gen/transform-packages.ts
  tools/pkglint/lib/rules.ts
  version.v2.json
Labels: contribution/core

#16671 chore: move modules to assertions
  packages/@aws-cdk/aws-applicationautoscaling/package.json
  packages/@aws-cdk/aws-applicationautoscaling/test/scalable-target.test.ts
  packages/@aws-cdk/aws-applicationautoscaling/test/step-scaling-policy.test.ts
  packages/@aws-cdk/aws-applicationautoscaling/test/target-tracking.test.ts
  packages/@aws-cdk/aws-chatbot/package.json
  packages/@aws-cdk/aws-chatbot/test/slack-channel-configuration.test.ts
  packages/@aws-cdk/aws-codecommit/package.json
  packages/@aws-cdk/aws-codecommit/test/codecommit.test.ts
  packages/@aws-cdk/aws-codecommit/test/notification-rule.test.ts
  packages/@aws-cdk/aws-codepipeline/package.json
  packages/@aws-cdk/aws-codepipeline/test/action.test.ts
  packages/@aws-cdk/aws-codepipeline/test/artifacts.test.ts
  packages/@aws-cdk/aws-codepipeline/test/cross-env.test.ts
  packages/@aws-cdk/aws-codepipeline/test/general-validation.test.ts
  packages/@aws-cdk/aws-codepipeline/test/notification-rule.test.ts
  packages/@aws-cdk/aws-codepipeline/test/pipeline.test.ts
  packages/@aws-cdk/aws-codepipeline/test/stages.test.ts
  packages/@aws-cdk/aws-codepipeline/test/variables.test.ts
  packages/@aws-cdk/aws-ecr-assets/package.json
  packages/@aws-cdk/aws-ecr-assets/test/image-asset.test.ts
  packages/@aws-cdk/aws-ecr-assets/test/tarball-asset.test.ts
  packages/@aws-cdk/aws-ecr/package.json
  packages/@aws-cdk/aws-ecr/test/auth-token.test.ts
  packages/@aws-cdk/aws-ecr/test/repository.test.ts
  packages/@aws-cdk/aws-logs/package.json
  packages/@aws-cdk/aws-logs/test/destination.test.ts
  packages/@aws-cdk/aws-logs/test/log-retention.test.ts
  packages/@aws-cdk/aws-logs/test/loggroup.test.ts
  packages/@aws-cdk/aws-logs/test/logstream.test.ts
  packages/@aws-cdk/aws-logs/test/metricfilter.test.ts
  packages/@aws-cdk/aws-logs/test/subscriptionfilter.test.ts
  packages/@aws-cdk/aws-s3-assets/package.json
  packages/@aws-cdk/aws-s3-assets/test/asset.test.ts
  packages/@aws-cdk/aws-s3/package.json
  packages/@aws-cdk/aws-s3/test/aspect.test.ts
  packages/@aws-cdk/aws-s3/test/bucket-policy.test.ts
  packages/@aws-cdk/aws-s3/test/bucket.test.ts
  packages/@aws-cdk/aws-s3/test/cors.test.ts
  packages/@aws-cdk/aws-s3/test/metrics.test.ts
  packages/@aws-cdk/aws-s3/test/notification.test.ts
  packages/@aws-cdk/aws-s3/test/rules.test.ts
  packages/@aws-cdk/aws-s3/test/util.test.ts
  packages/@aws-cdk/aws-sqs/package.json
  packages/@aws-cdk/aws-sqs/test/sqs.test.ts
  packages/@aws-cdk/aws-ssm/package.json
  packages/@aws-cdk/aws-ssm/test/parameter-store-string.test.ts
  packages/@aws-cdk/aws-ssm/test/parameter.test.ts
  packages/@aws-cdk/aws-ssm/test/ssm-document.test.ts
Labels: contribution/core

#16702 chore(release): 2.0.0-rc.24
  CHANGELOG.v2.alpha.md
  CHANGELOG.v2.md
  version.v2.json
Labels: pr/auto-approve

#16264 feat(aws-ec2): userdata cfn-signal signal resource which is different than the attached resource
  packages/@aws-cdk/aws-ec2/lib/cfn-init.ts
  packages/@aws-cdk/aws-ec2/test/cfn-init.test.ts
Labels: pr-linter/exempt-readme

#16445 fix(elasticloadbalancingv2): Incorrect validation on `NetworkLoadBalancer.configureHealthCheck()`
  packages/@aws-cdk/aws-elasticloadbalancingv2/lib/alb/application-target-group.ts
  packages/@aws-cdk/aws-elasticloadbalancingv2/lib/shared/base-target-group.ts
  packages/@aws-cdk/aws-elasticloadbalancingv2/test/alb/target-group.test.ts
  packages/@aws-cdk/aws-elasticloadbalancingv2/test/nlb/target-group.test.ts
Labels: p1, contribution/core, @aws-cdk/aws-elasticloadbalancingv2

#16706 chore: upgrade dependencies
  package.json
  packages/@aws-cdk/assertions/package.json
  packages/@aws-cdk/aws-apigatewayv2-authorizers/package.json
  packages/@aws-cdk/aws-aps/package.json
  packages/@aws-cdk/aws-certificatemanager/lambda-packages/dns_validated_certificate_handler/package.json
  packages/@aws-cdk/aws-cloudformation/package.json
  packages/@aws-cdk/aws-codepipeline-actions/package.json
  packages/@aws-cdk/aws-dynamodb-global/lambda-packages/aws-global-table-coordinator/package.json
  packages/@aws-cdk/aws-dynamodb/package.json
  packages/@aws-cdk/aws-ec2/package.json
  packages/@aws-cdk/aws-eks/package.json
  packages/@aws-cdk/aws-events-targets/package.json
  packages/@aws-cdk/aws-globalaccelerator-endpoints/package.json
  packages/@aws-cdk/aws-healthlake/package.json
  packages/@aws-cdk/aws-iam/package.json
  packages/@aws-cdk/aws-lambda-nodejs/package.json
  packages/@aws-cdk/aws-lambda/package.json
  packages/@aws-cdk/aws-logs/package.json
  packages/@aws-cdk/aws-lookoutequipment/package.json
  packages/@aws-cdk/aws-memorydb/package.json
  packages/@aws-cdk/aws-route53/package.json
  packages/@aws-cdk/aws-route53recoverycontrol/package.json
  packages/@aws-cdk/aws-route53recoveryreadiness/package.json
  packages/@aws-cdk/aws-s3/package.json
  packages/@aws-cdk/aws-ses/package.json
  packages/@aws-cdk/aws-stepfunctions-tasks/lib/eval-nodejs-handler/index.ts
  packages/@aws-cdk/cloud-assembly-schema/package.json
  packages/@aws-cdk/cloudformation-diff/package.json
  packages/@aws-cdk/core/package.json
  packages/@aws-cdk/custom-resources/package.json
  packages/@aws-cdk/cx-api/package.json
  packages/@monocdk-experiment/rewrite-imports/package.json
  packages/aws-cdk-lib/package.json
  packages/aws-cdk-migration/package.json
  packages/aws-cdk/package.json
  packages/awslint/package.json
  packages/cdk-assets/package.json
  packages/cdk-dasm/package.json
  packages/decdk/package.json
  packages/monocdk/package.json
  tools/@aws-cdk/cdk-build-tools/package.json
  tools/@aws-cdk/cfn2ts/package.json
  tools/@aws-cdk/eslint-plugin/package.json
  tools/@aws-cdk/pkglint/package.json
  tools/@aws-cdk/prlint/package.json
  tools/@aws-cdk/yarn-cling/package.json
  yarn.lock
Labels: contribution/core

#16719 feat(lambda): support for ARM architecture
  CHANGELOG.md
  packages/@aws-cdk/aws-lambda/README.md
  packages/@aws-cdk/aws-lambda/lib/architecture.ts
  packages/@aws-cdk/aws-lambda/lib/function.ts
  packages/@aws-cdk/aws-lambda/lib/index.ts
  packages/@aws-cdk/aws-lambda/lib/layers.ts
  packages/@aws-cdk/aws-lambda/test/function.test.ts
  packages/@aws-cdk/aws-lambda/test/layers.test.ts
  packages/@aws-cdk/cfnspec/spec-source/530_Lambda_ARM_patch.json
  version.v1.json
Labels: contribution/core, pr/no-squash

#16711 chore: allow-list devDeps to keep in transform.sh
  buildspec-pr.yaml
  buildspec.yaml
  packages/aws-cdk-migration/lib/rewrite.ts
  tools/@aws-cdk/individual-pkg-gen/copy-files-removing-deps.ts
Labels: contribution/core

#16389 feat(cloudfront): support Behavior-specific viewer protocol policy for CloudFrontWebDistribution
  packages/@aws-cdk/aws-cloudfront/lib/web-distribution.ts
  packages/@aws-cdk/aws-cloudfront/test/web-distribution.test.ts
Labels: pr-linter/exempt-readme

#16722 chore(merge-back): 1.125.0
  CHANGELOG.md
  packages/@aws-cdk/aws-lambda/README.md
  packages/@aws-cdk/aws-lambda/lib/architecture.ts
  packages/@aws-cdk/aws-lambda/lib/function.ts
  packages/@aws-cdk/aws-lambda/lib/index.ts
  packages/@aws-cdk/aws-lambda/lib/layers.ts
  packages/@aws-cdk/aws-lambda/test/function.test.ts
  packages/@aws-cdk/aws-lambda/test/layers.test.ts
  packages/@aws-cdk/cfnspec/spec-source/530_Lambda_ARM_patch.json
  version.v1.json
Labels: pr/no-squash, pr/auto-approve

#16729 chore: revert "chore(release): 2.0.0-rc.24 (#16702)"
  CHANGELOG.v2.alpha.md
  CHANGELOG.v2.md
  version.v2.json
Labels: contribution/core

#16727 chore: (revert) chore: move modules to assertions (#16671)
  packages/@aws-cdk/aws-applicationautoscaling/package.json
  packages/@aws-cdk/aws-applicationautoscaling/test/scalable-target.test.ts
  packages/@aws-cdk/aws-applicationautoscaling/test/step-scaling-policy.test.ts
  packages/@aws-cdk/aws-applicationautoscaling/test/target-tracking.test.ts
  packages/@aws-cdk/aws-chatbot/package.json
  packages/@aws-cdk/aws-chatbot/test/slack-channel-configuration.test.ts
  packages/@aws-cdk/aws-codecommit/package.json
  packages/@aws-cdk/aws-codecommit/test/codecommit.test.ts
  packages/@aws-cdk/aws-codecommit/test/notification-rule.test.ts
  packages/@aws-cdk/aws-codepipeline/package.json
  packages/@aws-cdk/aws-codepipeline/test/action.test.ts
  packages/@aws-cdk/aws-codepipeline/test/artifacts.test.ts
  packages/@aws-cdk/aws-codepipeline/test/cross-env.test.ts
  packages/@aws-cdk/aws-codepipeline/test/general-validation.test.ts
  packages/@aws-cdk/aws-codepipeline/test/notification-rule.test.ts
  packages/@aws-cdk/aws-codepipeline/test/pipeline.test.ts
  packages/@aws-cdk/aws-codepipeline/test/stages.test.ts
  packages/@aws-cdk/aws-codepipeline/test/variables.test.ts
  packages/@aws-cdk/aws-ecr-assets/package.json
  packages/@aws-cdk/aws-ecr-assets/test/image-asset.test.ts
  packages/@aws-cdk/aws-ecr-assets/test/tarball-asset.test.ts
  packages/@aws-cdk/aws-ecr/package.json
  packages/@aws-cdk/aws-ecr/test/auth-token.test.ts
  packages/@aws-cdk/aws-ecr/test/repository.test.ts
  packages/@aws-cdk/aws-logs/package.json
  packages/@aws-cdk/aws-logs/test/destination.test.ts
  packages/@aws-cdk/aws-logs/test/log-retention.test.ts
  packages/@aws-cdk/aws-logs/test/loggroup.test.ts
  packages/@aws-cdk/aws-logs/test/logstream.test.ts
  packages/@aws-cdk/aws-logs/test/metricfilter.test.ts
  packages/@aws-cdk/aws-logs/test/subscriptionfilter.test.ts
  packages/@aws-cdk/aws-s3-assets/package.json
  packages/@aws-cdk/aws-s3-assets/test/asset.test.ts
  packages/@aws-cdk/aws-s3/package.json
  packages/@aws-cdk/aws-s3/test/aspect.test.ts
  packages/@aws-cdk/aws-s3/test/bucket-policy.test.ts
  packages/@aws-cdk/aws-s3/test/bucket.test.ts
  packages/@aws-cdk/aws-s3/test/cors.test.ts
  packages/@aws-cdk/aws-s3/test/metrics.test.ts
  packages/@aws-cdk/aws-s3/test/notification.test.ts
  packages/@aws-cdk/aws-s3/test/rules.test.ts
  packages/@aws-cdk/aws-s3/test/util.test.ts
  packages/@aws-cdk/aws-sqs/package.json
  packages/@aws-cdk/aws-sqs/test/sqs.test.ts
  packages/@aws-cdk/aws-ssm/package.json
  packages/@aws-cdk/aws-ssm/test/parameter-store-string.test.ts
  packages/@aws-cdk/aws-ssm/test/parameter.test.ts
  packages/@aws-cdk/aws-ssm/test/ssm-document.test.ts
Labels: contribution/core

#16693 chore: (backport) enable publishing of independent alpha modules
  lerna.json
  package.json
  scripts/bump.js
  tools/@aws-cdk/individual-pkg-gen/README.md
  tools/@aws-cdk/individual-pkg-gen/bin/individual-pkg-gen
  tools/@aws-cdk/individual-pkg-gen/transform-packages.ts
  tools/@aws-cdk/pkglint/lib/rules.ts
Labels: contribution/core

#16577 chore(init-templates): fix dependencies in v2 TypeScript templates
  packages/aws-cdk/lib/init-templates/v2/lib/typescript/package.template.json
Labels: contribution/core

#14650 feat(eks): `connectAutoScalingGroupCapacity` on imported clusters
  packages/@aws-cdk/aws-eks/README.md
  packages/@aws-cdk/aws-eks/lib/cluster.ts
  packages/@aws-cdk/aws-eks/lib/user-data.ts
  packages/@aws-cdk/aws-eks/test/cluster.test.ts
  packages/@aws-cdk/aws-eks/test/user-data.test.ts
Labels: p2, @aws-cdk/aws-eks, effort/small

#16738 fix: set ROSETTA_MAX_WORKER_COUNT in pack.sh
  buildspec-pr.yaml
  buildspec.yaml
  pack.sh
Labels: contribution/core, pr-linter/exempt-test

#16696 chore(cli): add more capabilities to the hotswap CFN evaluate sub-system
  packages/aws-cdk/lib/api/deploy-stack.ts
  packages/aws-cdk/lib/api/hotswap-deployments.ts
  packages/aws-cdk/lib/api/hotswap/common.ts
  packages/aws-cdk/lib/api/hotswap/evaluate-cloudformation-template.ts
  packages/aws-cdk/lib/api/hotswap/lambda-functions.ts
  packages/aws-cdk/lib/api/util/cloudformation/evaluate-cfn.ts
  packages/aws-cdk/test/api/hotswap-deployments.test.ts
Labels: contribution/core
