Repository aws/aws-cdk, pull requests merged in 2021-08, with the labels that each got.

#15819 fix(pipelines): Prepare stage doesn't have AUTO_EXPAND capability
  packages/@aws-cdk/pipelines/lib/codepipeline/codepipeline.ts
  packages/@aws-cdk/pipelines/test/integ.newpipeline-with-vpc.expected.json
  packages/@aws-cdk/pipelines/test/integ.newpipeline.expected.json
Labels: @aws-cdk/pipelines, contribution/core

#15823 chore(assertions): rename TemplateAssertions to Template
  packages/@aws-cdk/assertions/README.md
  packages/@aws-cdk/assertions/lib/template.ts
  packages/@aws-cdk/assertions/test/template.test.ts
  packages/@aws-cdk/aws-cloudwatch/test/alarm.test.ts
  packages/@aws-cdk/aws-cloudwatch/test/composite-alarm.test.ts
  packages/@aws-cdk/aws-cloudwatch/test/cross-environment.test.ts
  packages/@aws-cdk/aws-cloudwatch/test/dashboard.test.ts
  packages/@aws-cdk/aws-cloudwatch/test/metric-math.test.ts
  packages/@aws-cdk/aws-cloudwatch/test/metrics.test.ts
  packages/@aws-cdk/aws-cognito/test/user-pool-client.test.ts
  packages/@aws-cdk/aws-cognito/test/user-pool-domain.test.ts
  packages/@aws-cdk/aws-cognito/test/user-pool-idps/amazon.test.ts
  packages/@aws-cdk/aws-cognito/test/user-pool-idps/apple.ts
  packages/@aws-cdk/aws-cognito/test/user-pool-idps/facebook.test.ts
  packages/@aws-cdk/aws-cognito/test/user-pool-idps/google.test.ts
  packages/@aws-cdk/aws-cognito/test/user-pool-resource-server.test.ts
  packages/@aws-cdk/aws-cognito/test/user-pool.test.ts
  packages/@aws-cdk/aws-efs/test/access-point.test.ts
  packages/@aws-cdk/aws-efs/test/efs-file-system.test.ts
  packages/@aws-cdk/aws-lambda-event-sources/test/api.test.ts
  packages/@aws-cdk/aws-lambda-event-sources/test/dynamo.test.ts
  packages/@aws-cdk/aws-lambda-event-sources/test/kafka.test.ts
  packages/@aws-cdk/aws-lambda-event-sources/test/kinesis.test.ts
  packages/@aws-cdk/aws-lambda-event-sources/test/s3.test.ts
  packages/@aws-cdk/aws-lambda-event-sources/test/sns.test.ts
  packages/@aws-cdk/aws-lambda-event-sources/test/sqs.test.ts
  packages/@aws-cdk/aws-sns/test/sns.test.ts
  packages/@aws-cdk/aws-sns/test/subscription.test.ts
  packages/@aws-cdk/aws-synthetics/test/canary.test.ts
  packages/@aws-cdk/aws-synthetics/test/code.test.ts
Labels: contribution/core

#15730 feat(s3-deployment): control object access
  package.json
  packages/@aws-cdk/aws-s3-deployment/NOTICE
  packages/@aws-cdk/aws-s3-deployment/README.md
  packages/@aws-cdk/aws-s3-deployment/lib/bucket-deployment.ts
  packages/@aws-cdk/aws-s3-deployment/package.json
  packages/@aws-cdk/aws-s3-deployment/test/bucket-deployment.test.ts
Labels: @aws-cdk/aws-s3-deployment, effort/small, p1

#15870 chore(lambda): lambda insights incorrectly accesses non-exported files
  packages/@aws-cdk/aws-lambda/lib/lambda-insights.ts
Labels: contribution/core

#15872 chore: temporarily transfer @skinny85 module ownership
  .github/workflows/issue-label-assign.yml
Labels: contribution/core

#15884 fix(s3): notifications are broken in some regions
  packages/@aws-cdk/aws-lambda-event-sources/test/integ.s3.expected.json
  packages/@aws-cdk/aws-s3-notifications/test/integ.notifications.expected.json
  packages/@aws-cdk/aws-s3-notifications/test/lambda/integ.bucket-notifications.expected.json
  packages/@aws-cdk/aws-s3-notifications/test/sns/integ.sns-bucket-notifications.expected.json
  packages/@aws-cdk/aws-s3-notifications/test/sqs/integ.bucket-notifications.expected.json
  packages/@aws-cdk/aws-s3/lib/notifications-resource/notifications-resource-handler.ts
  packages/@aws-cdk/aws-s3/test/notifications-resource-handler/Dockerfile
Labels: contribution/core

#15886 chore(release): 2.0.0-rc.16
  CHANGELOG.v2.md
  version.v2.json
Labels: pr/auto-approve

#15890 chore: rewrite jsii targets for experimental packages during transformation
  packages/@aws-cdk/assertions/package.json
  packages/@aws-cdk/aws-amplify/package.json
  packages/@aws-cdk/aws-apigatewayv2-authorizers/package.json
  packages/@aws-cdk/aws-apigatewayv2-integrations/package.json
  packages/@aws-cdk/aws-apigatewayv2/package.json
  packages/@aws-cdk/aws-appsync/package.json
  packages/@aws-cdk/aws-batch/package.json
  packages/@aws-cdk/aws-cloud9/package.json
  packages/@aws-cdk/aws-codestar/package.json
  packages/@aws-cdk/aws-glue/package.json
  packages/@aws-cdk/aws-ivs/package.json
  packages/@aws-cdk/aws-kinesisanalytics-flink/package.json
  packages/@aws-cdk/aws-lambda-go/package.json
  packages/@aws-cdk/aws-lambda-python/package.json
  packages/@aws-cdk/aws-msk/package.json
  packages/@aws-cdk/aws-neptune/package.json
  packages/@aws-cdk/aws-redshift/package.json
  packages/@aws-cdk/aws-servicecatalog/package.json
  packages/@aws-cdk/aws-servicecatalogappregistry/package.json
  packages/@aws-cdk/aws-synthetics/package.json
  packages/@aws-cdk/example-construct-library/package.json
  packages/@aws-cdk/pipelines/package.json
  tools/individual-pkg-gen/copy-files-removing-deps.ts
  tools/individual-pkg-gen/package.json
  tools/pkglint/lib/rules.ts
Labels: contribution/core

#15836 feat(kinesisfirehose): supports Kinesis data stream source for delivery stream
  packages/@aws-cdk/aws-kinesisfirehose/README.md
  packages/@aws-cdk/aws-kinesisfirehose/lib/delivery-stream.ts
  packages/@aws-cdk/aws-kinesisfirehose/package.json
  packages/@aws-cdk/aws-kinesisfirehose/test/delivery-stream.test.ts
  packages/@aws-cdk/aws-kinesisfirehose/test/integ.delivery-stream.source-stream.expected.json
  packages/@aws-cdk/aws-kinesisfirehose/test/integ.delivery-stream.source-stream.ts
Labels: contribution/core

#15896 chore(docs): update doc strings in DestinationS3BackupProps
  packages/@aws-cdk/aws-kinesisfirehose-destinations/lib/common.ts
Labels: contribution/core

#15905 chore(merge-back): 1.117.0
  CHANGELOG.md
  version.v1.json
Labels: pr/auto-approve, pr/no-squash

#15921 test(aws-lambda-python): remove hard-coded references to @aws-cdk/aws-lambda
  packages/@aws-cdk/aws-lambda-python/test/bundling.test.ts
Labels: contribution/core

#15924 chore(assertions): explicit feature flags to produce a consistent template during tests
  packages/@aws-cdk/assertions/test/template.test.ts
Labels: contribution/core

#15614 chore(assertions): release as an alpha module in CDKv2
  package.json
  packages/@aws-cdk/assertions/package.json
  packages/@aws-cdk/assertions/vendor-in.sh
  packages/@aws-cdk/aws-synthetics/package.json
  tools/individual-pkg-gen/copy-files-removing-deps.ts
Labels: contribution/core

#15949 chore: align v2 alpha package naming conventions to proposal
  package.json
  tools/individual-pkg-gen/copy-files-removing-deps.ts
  tools/pkglint/lib/rules.ts
Labels: contribution/core, pr/requires-two-approvers

#15953 chore(sam): explicit feature flags to produce a consistent template during tests
  packages/@aws-cdk/aws-sam/test/application.test.ts
Labels: contribution/core

#15955 chore(servicecatalogappregistry): explicit feature flags to produce a consistent template during tests
  packages/@aws-cdk/aws-servicecatalogappregistry/test/application.test.ts
  packages/@aws-cdk/aws-servicecatalogappregistry/test/attribute-group.test.ts
Labels: contribution/core

#15960 chore(glue, ivs, msk, servicecatalog): explicit feature flags to produce a consistent template during tests
  packages/@aws-cdk/aws-glue/test/database.test.ts
  packages/@aws-cdk/aws-ivs/test/ivs.test.ts
  packages/@aws-cdk/aws-msk/test/cluster.test.ts
  packages/@aws-cdk/aws-servicecatalog/test/portfolio.test.ts
Labels: contribution/core

#14902 fix(ec2): "clientVpnEndoint" => "clientVpnEndpoint"
  packages/@aws-cdk/aws-ec2/lib/client-vpn-authorization-rule.ts
  packages/@aws-cdk/aws-ec2/lib/client-vpn-endpoint.ts
  packages/@aws-cdk/aws-ec2/lib/client-vpn-route.ts
  packages/@aws-cdk/aws-ec2/test/client-vpn-authorization-rule.test.ts
  packages/@aws-cdk/aws-ec2/test/client-vpn-route.test.ts
Labels: @aws-cdk/aws-ec2

#15627 feat(pipelines): add `synthCodeBuildDefaults`
  packages/@aws-cdk/pipelines/README.md
  packages/@aws-cdk/pipelines/lib/codepipeline/codepipeline.ts
  packages/@aws-cdk/pipelines/test/compliance/synths.test.ts
Labels: @aws-cdk/pipelines

#15622 feat(aws-elbv2): ALB target group routing algorithms
  packages/@aws-cdk/aws-elasticloadbalancingv2/lib/alb/application-listener.ts
  packages/@aws-cdk/aws-elasticloadbalancingv2/lib/alb/application-target-group.ts
  packages/@aws-cdk/aws-elasticloadbalancingv2/lib/shared/enums.ts
  packages/@aws-cdk/aws-elasticloadbalancingv2/test/alb/listener.test.ts
  packages/@aws-cdk/aws-elasticloadbalancingv2/test/alb/target-group.test.ts
Labels: pr-linter/exempt-readme, @aws-cdk/aws-elasticloadbalancingv2

#15893 docs(cognito): describe addDependency for identity provider and app client
  packages/@aws-cdk/aws-cognito/README.md
Labels: @aws-cdk/aws-cognito

#15978 chore(release): 1.118.0
  .github/workflows/yarn-upgrade.yml
  .mergify.yml
  CHANGELOG.md
  packages/@aws-cdk/assertions/test/template.test.ts
  packages/@aws-cdk/aws-appmesh/README.md
  packages/@aws-cdk/aws-cognito/README.md
  packages/@aws-cdk/aws-cognito/lib/user-pool-client.ts
  packages/@aws-cdk/aws-cognito/test/user-pool-client.test.ts
  packages/@aws-cdk/aws-ec2/lib/client-vpn-authorization-rule.ts
  packages/@aws-cdk/aws-ec2/lib/client-vpn-endpoint.ts
  packages/@aws-cdk/aws-ec2/lib/client-vpn-route.ts
  packages/@aws-cdk/aws-ec2/test/client-vpn-authorization-rule.test.ts
  packages/@aws-cdk/aws-ec2/test/client-vpn-route.test.ts
  packages/@aws-cdk/aws-ecs/lib/base/task-definition.ts
  packages/@aws-cdk/aws-elasticloadbalancingv2/lib/alb/application-listener.ts
  packages/@aws-cdk/aws-elasticloadbalancingv2/lib/alb/application-target-group.ts
  packages/@aws-cdk/aws-elasticloadbalancingv2/lib/shared/enums.ts
  packages/@aws-cdk/aws-elasticloadbalancingv2/test/alb/listener.test.ts
  packages/@aws-cdk/aws-elasticloadbalancingv2/test/alb/target-group.test.ts
  packages/@aws-cdk/aws-glue/test/database.test.ts
  packages/@aws-cdk/aws-ivs/test/ivs.test.ts
  packages/@aws-cdk/aws-lambda-python/test/bundling.test.ts
  packages/@aws-cdk/aws-msk/test/cluster.test.ts
  packages/@aws-cdk/aws-sam/test/application.test.ts
  packages/@aws-cdk/aws-servicecatalog/test/portfolio.test.ts
  packages/@aws-cdk/aws-servicecatalogappregistry/test/application.test.ts
  packages/@aws-cdk/aws-servicecatalogappregistry/test/attribute-group.test.ts
  packages/@aws-cdk/pipelines/README.md
  packages/@aws-cdk/pipelines/lib/codepipeline/codepipeline.ts
  packages/@aws-cdk/pipelines/test/compliance/synths.test.ts
  version.v1.json
Labels: pr/no-squash

#15982 chore(merge-back): 1.118.0
  CHANGELOG.md
  version.v1.json
Labels: pr/no-squash, pr/auto-approve

#15986 chore(release): 2.0.0-rc.17
  CHANGELOG.v2.md
  version.v2.json
Labels: pr/auto-approve

#15988 docs(codepipeline): explain how cross-account CodeCommit works
  packages/@aws-cdk/aws-codepipeline-actions/lib/codecommit/source-action.ts
Labels: contribution/core

#15989 chore(scripts): safety script incorrectly checks `peerDependencies`
  scripts/check-yarn-lock.js
  yarn.lock
Labels: contribution/core

#15994 test(aws-lambda-python): remove hard-coded references to @aws-cdk/aws-lambda
  packages/@aws-cdk/aws-lambda-python/test/function.test.ts
Labels: contribution/core

#16008 chore(ec2): explicit feature flags to produce a consistent template during tests
  packages/@aws-cdk/aws-ec2/test/client-vpn-authorization-rule.test.ts
  packages/@aws-cdk/aws-ec2/test/client-vpn-route.test.ts
Labels: contribution/core

#15977 chore(pipelines): improve CodeBuildStep.project error message
  packages/@aws-cdk/pipelines/lib/codepipeline/codebuild-step.ts
Labels: effort/small, @aws-cdk/pipelines

#16015 fix(assert): matchTemplate with superset fails when additional parameters are present
  packages/@aws-cdk/assert-internal/lib/assertions/match-template.ts
  packages/@aws-cdk/assert-internal/test/cloud-artifact.ts
  packages/@aws-cdk/assert-internal/test/have-output.test.ts
  packages/@aws-cdk/assert-internal/test/have-resource.test.ts
  packages/@aws-cdk/assert-internal/test/match-template.test.ts
Labels: contribution/core

#15771 feat(aws-apigateway): import existing usage plan
  packages/@aws-cdk/aws-apigateway/README.md
  packages/@aws-cdk/aws-apigateway/lib/usage-plan.ts
  packages/@aws-cdk/aws-apigateway/test/integ.usage-plan.sharing.expected.json
  packages/@aws-cdk/aws-apigateway/test/integ.usage-plan.sharing.ts
  packages/@aws-cdk/aws-apigateway/test/usage-plan.test.ts
Labels: @aws-cdk/aws-apigateway

#16017 fix(pipelines): repos with dashes cannot be used as additionalInputs
  packages/@aws-cdk/pipelines/lib/codepipeline/_codebuild-factory.ts
  packages/@aws-cdk/pipelines/lib/codepipeline/artifact-map.ts
  packages/@aws-cdk/pipelines/lib/codepipeline/codepipeline.ts
  packages/@aws-cdk/pipelines/test/codepipeline/codepipeline-sources.test.ts
  packages/@aws-cdk/pipelines/test/compliance/synths.test.ts
  packages/@aws-cdk/pipelines/test/integ.newpipeline-with-vpc.expected.json
  packages/@aws-cdk/pipelines/test/integ.newpipeline.expected.json
Labels: contribution/core

#15958 chore(lambda-python): strip out deprecated symbols
  packages/@aws-cdk/aws-lambda-python/lib/bundling.ts
Labels: effort/small, @aws-cdk/aws-lambda-python

#15973 feat(apigatewayv2): http api - domain url for a stage
  packages/@aws-cdk/aws-apigatewayv2/README.md
  packages/@aws-cdk/aws-apigatewayv2/lib/common/api-mapping.ts
  packages/@aws-cdk/aws-apigatewayv2/lib/common/base.ts
  packages/@aws-cdk/aws-apigatewayv2/lib/http/stage.ts
  packages/@aws-cdk/aws-apigatewayv2/test/http/stage.test.ts
Labels: effort/small, @aws-cdk/aws-apigatewayv2

#15865 fix(s3-deployment): BucketDeployment doesn't validate that distribution paths start with "/"
  packages/@aws-cdk/aws-s3-deployment/lib/bucket-deployment.ts
  packages/@aws-cdk/aws-s3-deployment/test/bucket-deployment.test.ts
Labels: effort/small, @aws-cdk/aws-s3-deployment

#16040 fix(ec2): opaque error when insufficient NAT EIPs are configured
  packages/@aws-cdk/aws-ec2/lib/nat.ts
  packages/@aws-cdk/aws-ec2/test/vpc.test.ts
Labels: contribution/core

#15717 fix(events): cross-account event targets that have a Role are broken
  packages/@aws-cdk/aws-codepipeline-actions/test/codecommit/codecommit-source-action.test.ts
  packages/@aws-cdk/aws-events/lib/rule.ts
  packages/@aws-cdk/aws-events/test/test.rule.ts
Labels: contribution/core

#16038 chore(ecs): allow selecting Bottlerocket via `machineImage`
  packages/@aws-cdk/aws-ecs/README.md
  packages/@aws-cdk/aws-ecs/lib/cluster.ts
  packages/@aws-cdk/aws-ecs/test/cluster.test.ts
Labels: contribution/core

#16043 chore(cdk-release): track and bump separate alpha version
  scripts/bump.js
  tools/cdk-release/lib/conventional-commits.ts
  tools/cdk-release/lib/defaults.ts
  tools/cdk-release/lib/index.ts
  tools/cdk-release/lib/lifecycles/bump.ts
  tools/cdk-release/lib/lifecycles/changelog.ts
  tools/cdk-release/lib/private/files.ts
  tools/cdk-release/lib/private/print.ts
  tools/cdk-release/lib/types.ts
  tools/cdk-release/lib/updaters/index.ts
  tools/cdk-release/lib/updaters/types/json.ts
  tools/cdk-release/lib/updaters/types/plain-text.ts
  tools/cdk-release/test/bump.test.ts
  tools/cdk-release/test/changelog.test.ts
  tools/cdk-release/test/conventional-commits.test.ts
Labels: contribution/core

#16034 feat(assets): exclude "cdk.out" from docker assets
  packages/@aws-cdk/aws-codebuild/test/integ.docker-asset.lit.expected.json
  packages/@aws-cdk/aws-ecr-assets/lib/image-asset.ts
  packages/@aws-cdk/aws-ecr-assets/test/image-asset.test.ts
  packages/@aws-cdk/aws-ecr-assets/test/integ.assets-docker.expected.json
  packages/@aws-cdk/aws-ecr-assets/test/integ.nested-stacks-docker.expected.json
  packages/@aws-cdk/aws-ecs-patterns/test/ec2/integ.multiple-application-load-balanced-ecs-service.expected.json
  packages/@aws-cdk/aws-ecs-patterns/test/ec2/integ.scheduled-ecs-task.lit.expected.json
  packages/@aws-cdk/aws-ecs-patterns/test/fargate/integ.alb-fargate-service-https.expected.json
  packages/@aws-cdk/aws-ecs-patterns/test/fargate/integ.asset-image.expected.json
  packages/@aws-cdk/aws-ecs-patterns/test/fargate/integ.circuit-breaker-load-balanced-fargate-service.expected.json
  packages/@aws-cdk/aws-ecs-patterns/test/fargate/integ.circuit-breaker-queue-processing-fargate-service.expected.json
  packages/@aws-cdk/aws-ecs-patterns/test/fargate/integ.executionrole.expected.json
  packages/@aws-cdk/aws-ecs-patterns/test/fargate/integ.l3-autocreate.expected.json
  packages/@aws-cdk/aws-ecs-patterns/test/fargate/integ.l3-vpconly.expected.json
  packages/@aws-cdk/aws-ecs-patterns/test/fargate/integ.l3.expected.json
  packages/@aws-cdk/aws-ecs-patterns/test/fargate/integ.multiple-network-load-balanced-fargate-service.expected.json
  packages/@aws-cdk/aws-ecs-patterns/test/fargate/integ.queue-processing-fargate-service-isolated.expected.json
  packages/@aws-cdk/aws-ecs-patterns/test/fargate/integ.queue-processing-fargate-service-public.expected.json
  packages/@aws-cdk/aws-ecs-patterns/test/fargate/integ.queue-processing-fargate-service.expected.json
  packages/@aws-cdk/aws-ecs-patterns/test/fargate/integ.scheduled-fargate-task.lit.expected.json
  packages/@aws-cdk/aws-ecs-patterns/test/fargate/integ.special-listener.expected.json
  packages/@aws-cdk/aws-ecs/test/container-definition.test.ts
  packages/@aws-cdk/aws-ecs/test/ec2/ec2-task-definition.test.ts
  packages/@aws-cdk/aws-events-targets/test/ecs/integ.event-ec2-task.lit.expected.json
  packages/@aws-cdk/aws-events-targets/test/ecs/integ.event-fargate-task.expected.json
  packages/@aws-cdk/aws-lambda-python/test/integ.function.expected.json
  packages/@aws-cdk/aws-lambda-python/test/integ.function.pipenv.expected.json
  packages/@aws-cdk/aws-lambda-python/test/integ.function.poetry.expected.json
  packages/@aws-cdk/aws-lambda-python/test/integ.function.project.expected.json
  packages/@aws-cdk/aws-lambda-python/test/integ.function.py38.expected.json
  packages/@aws-cdk/aws-lambda-python/test/integ.function.requirements.removed.expected.json
  packages/@aws-cdk/aws-lambda-python/test/integ.function.vpc.expected.json
  packages/@aws-cdk/aws-lambda/test/code.test.ts
  packages/@aws-cdk/aws-lambda/test/integ.lambda.docker.expected.json
  packages/@aws-cdk/aws-s3-deployment/test/bucket-deployment.test.ts
  packages/@aws-cdk/aws-stepfunctions-tasks/test/batch/integ.run-batch-job.expected.json
  packages/@aws-cdk/aws-stepfunctions-tasks/test/batch/integ.submit-job.expected.json
  packages/@aws-cdk/aws-stepfunctions-tasks/test/ecs/integ.ec2-run-task.expected.json
  packages/@aws-cdk/aws-stepfunctions-tasks/test/ecs/integ.ec2-task.expected.json
  packages/@aws-cdk/aws-stepfunctions-tasks/test/ecs/integ.fargate-run-task.expected.json
  packages/@aws-cdk/aws-stepfunctions-tasks/test/ecs/integ.fargate-task.expected.json
  packages/@aws-cdk/core/lib/fs/fingerprint.ts
  packages/@aws-cdk/core/test/fs/fs-fingerprint.test.ts
Labels: pr-linter/exempt-readme

#16035 chore: forward merge 'master' into 'v2-main'
  packages/@aws-cdk/assert-internal/lib/assertions/match-template.ts
  packages/@aws-cdk/assert-internal/test/cloud-artifact.ts
  packages/@aws-cdk/assert-internal/test/have-output.test.ts
  packages/@aws-cdk/assert-internal/test/have-resource.test.ts
  packages/@aws-cdk/assert-internal/test/match-template.test.ts
  packages/@aws-cdk/aws-apigateway/README.md
  packages/@aws-cdk/aws-apigateway/lib/usage-plan.ts
  packages/@aws-cdk/aws-apigateway/test/integ.usage-plan.sharing.expected.json
  packages/@aws-cdk/aws-apigateway/test/integ.usage-plan.sharing.ts
  packages/@aws-cdk/aws-apigateway/test/usage-plan.test.ts
  packages/@aws-cdk/aws-apigatewayv2/README.md
  packages/@aws-cdk/aws-apigatewayv2/lib/common/api-mapping.ts
  packages/@aws-cdk/aws-apigatewayv2/lib/common/base.ts
  packages/@aws-cdk/aws-apigatewayv2/lib/http/stage.ts
  packages/@aws-cdk/aws-apigatewayv2/test/http/stage.test.ts
  packages/@aws-cdk/aws-lambda-python/lib/bundling.ts
  packages/@aws-cdk/core/lib/stack.ts
  packages/@aws-cdk/core/test/stack.test.ts
  packages/@aws-cdk/pipelines/lib/codepipeline/_codebuild-factory.ts
  packages/@aws-cdk/pipelines/lib/codepipeline/artifact-map.ts
  packages/@aws-cdk/pipelines/lib/codepipeline/codebuild-step.ts
  packages/@aws-cdk/pipelines/lib/codepipeline/codepipeline.ts
  packages/@aws-cdk/pipelines/test/codepipeline/codepipeline-sources.test.ts
  packages/@aws-cdk/pipelines/test/compliance/synths.test.ts
  packages/@aws-cdk/pipelines/test/integ.newpipeline-with-vpc.expected.json
  packages/@aws-cdk/pipelines/test/integ.newpipeline.expected.json
Labels: pr/no-squash, pr/forward-merge, pr/auto-approve

#16101 chore(merge-back): 1.119.0
  CHANGELOG.md
  version.v1.json
Labels: pr/no-squash, pr/auto-approve

#16097 fix(appsync): addSubscription only allows for field type
  packages/@aws-cdk/aws-appsync/README.md
  packages/@aws-cdk/aws-appsync/lib/schema.ts
  packages/@aws-cdk/aws-appsync/test/appsync-code-first.test.ts
Labels: contribution/core

#16109 chore(deps): bump tar from 6.1.0 to 6.1.8
  yarn.lock
Labels: contribution/core

#16113 chore(release): 2.0.0-rc.18
  CHANGELOG.v2.md
  version.v2.json
Labels: pr/auto-approve

#16073 fix(cli): 'deploy' and 'diff' silently does nothing when given unknown stack name
  packages/aws-cdk/lib/cdk-toolkit.ts
  packages/aws-cdk/test/cdk-toolkit.test.ts
  packages/aws-cdk/test/diff.test.ts
Labels: contribution/core

#16078 feat(aws-stepfunctions): add support to heartbeat error inside catch block
  packages/@aws-cdk/aws-stepfunctions/README.md
  packages/@aws-cdk/aws-stepfunctions/lib/types.ts
  packages/@aws-cdk/aws-stepfunctions/package.json
Labels: @aws-cdk/aws-stepfunctions, pr-linter/exempt-test

#16119 chore(autoscaling): transfer ownership of autoscaling to @comcalvi
  .github/workflows/issue-label-assign.yml
Labels: contribution/core

#16125 revert(cli): 'deploy' and 'diff' silently does nothing when given unknown stack name
  packages/aws-cdk/lib/cdk-toolkit.ts
  packages/aws-cdk/test/cdk-toolkit.test.ts
  packages/aws-cdk/test/diff.test.ts
Labels: contribution/core

#15939 fix(cli): Python init template does not work in directory with '-'
  packages/aws-cdk/lib/init-templates/v1/sample-app/python/tests/unit/test_%name.PythonModule%_stack.template.py
  packages/aws-cdk/lib/init-templates/v2/sample-app/python/tests/unit/test_%name.PythonModule%_stack.template.py
  packages/aws-cdk/test/integ/init/test-python.sh
Labels: package/tools, effort/small

#16112 chore: jsii-rosetta cannot be found when building individual packages
  scripts/transform.sh
Labels: contribution/core, pr-linter/exempt-test

#16132 chore: using the function parameter instead of '.' to find the folders
  scripts/transform.sh
Labels: contribution/core

#16134 fix(cli): unknown command pytest in build container fails integration tests
  packages/aws-cdk/test/integ/init/test-python.sh
Labels: contribution/core, pr-linter/exempt-test

#16136 docs(apigateway): @see tag doesn't work with the @deprecated tag in docs
  packages/@aws-cdk/aws-apigateway/lib/model.ts
Labels: pr-linter/exempt-test

#16106 chore(eks): bad indent in kubectl apply handler
  packages/@aws-cdk/aws-eks/lib/kubectl-handler/apply/__init__.py
Labels: p2, @aws-cdk/aws-eks, effort/small

#15874 chore(appsync): Correct VTL for aurora Serverless
  packages/@aws-cdk/aws-appsync/README.md
Labels: effort/small, @aws-cdk/aws-appsync

#16063 fix: KubectlHandler - insecure kubeconfig warning
  packages/@aws-cdk/aws-eks/lib/kubectl-handler/apply/__init__.py
  packages/@aws-cdk/aws-eks/lib/kubectl-handler/get/__init__.py
  packages/@aws-cdk/aws-eks/lib/kubectl-handler/helm/__init__.py
  packages/@aws-cdk/aws-eks/lib/kubectl-handler/patch/__init__.py
Labels: p2, @aws-cdk/aws-eks, effort/small, pr-linter/exempt-test

#16170 fix(cfnspec): changes to resource-level documentation not supported
  packages/@aws-cdk/cfnspec/build-tools/spec-diff.ts
Labels: contribution/core, pr-linter/exempt-test

#16146 fix(ses): drop spam rule appears in the incorrect order
  packages/@aws-cdk/aws-ses/lib/receipt-rule-set.ts
  packages/@aws-cdk/aws-ses/test/test.receipt-rule-set.ts
Labels: contribution/core

#15995 chore: fix alpha build of lambda-go/python packages
  packages/@aws-cdk/aws-lambda-go/package.json
  packages/@aws-cdk/aws-lambda-python/package.json
Labels: contribution/core

#16067 docs(cloudfront): fix CacheHeaderBehavior.behavior docstring
  packages/@aws-cdk/aws-cloudfront/lib/cache-policy.ts
Labels: contribution/core

#15984 docs(pipelines): should use 'lookup' tag instead of 'deploy' tag
  packages/@aws-cdk/pipelines/README.md
Labels: contribution/core

#16196 chore: `publishInParallel=false` with tokens produces useless error m…
  packages/@aws-cdk/pipelines/lib/codepipeline/_codebuild-factory.ts
  packages/@aws-cdk/pipelines/test/docker-credentials.test.ts
Labels: contribution/core

#16044 fix(apigatewayv2): http api - disallow empty string as domain name
  packages/@aws-cdk/aws-apigatewayv2/lib/common/domain-name.ts
  packages/@aws-cdk/aws-apigatewayv2/test/http/domain-name.test.ts
Labels: p2, effort/small, @aws-cdk/aws-apigatewayv2

#16131 feat(lambda): nodejs14.x supports inline code
  packages/@aws-cdk/aws-lambda/lib/runtime.ts
  packages/@aws-cdk/aws-lambda/test/integ.runtime.inlinecode.expected.json
  packages/@aws-cdk/aws-lambda/test/integ.runtime.inlinecode.ts
Labels: @aws-cdk/aws-lambda, effort/small, pr-linter/exempt-readme, pr-linter/exempt-test

#16055 feat(cognito): user pools - device tracking
  packages/@aws-cdk/aws-cognito/README.md
  packages/@aws-cdk/aws-cognito/lib/user-pool.ts
  packages/@aws-cdk/aws-cognito/test/user-pool.test.ts
Labels: p2, @aws-cdk/aws-cognito, effort/small

#15892 feat(assertions): queries and assertions against the Outputs and Mappings sections
  packages/@aws-cdk/assertions/README.md
  packages/@aws-cdk/assertions/lib/match.ts
  packages/@aws-cdk/assertions/lib/matcher.ts
  packages/@aws-cdk/assertions/lib/private/mappings.ts
  packages/@aws-cdk/assertions/lib/private/outputs.ts
  packages/@aws-cdk/assertions/lib/private/resource.ts
  packages/@aws-cdk/assertions/lib/private/resources.ts
  packages/@aws-cdk/assertions/lib/private/section.ts
  packages/@aws-cdk/assertions/lib/template.ts
  packages/@aws-cdk/assertions/test/private/section.test.ts
  packages/@aws-cdk/assertions/test/template.test.ts
  packages/@aws-cdk/aws-kinesisfirehose/package.json
  packages/@aws-cdk/aws-kinesisfirehose/test/delivery-stream.test.ts
  packages/@aws-cdk/aws-neptune/package.json
  packages/@aws-cdk/aws-neptune/test/cluster.test.ts
  packages/@aws-cdk/aws-neptune/test/instance.test.ts
  packages/@aws-cdk/aws-neptune/test/parameter-group.test.ts
  packages/@aws-cdk/aws-neptune/test/subnet-group.test.ts
Labels: contribution/core

#16205 chore(cli): Add node 10 deprecation warning
  packages/aws-cdk/bin/cdk.ts
  packages/aws-cdk/package.json
  yarn.lock
Labels: contribution/core

#15976 fix(sqs): unable to import a FIFO queue when the queue ARN is a token
  packages/@aws-cdk/aws-sqs/lib/queue-base.ts
  packages/@aws-cdk/aws-sqs/lib/queue.ts
  packages/@aws-cdk/aws-sqs/test/test.sqs.ts
Labels: p1, effort/small, @aws-cdk/aws-sqs

#16048 fix(ssm): StringParameter.fromStringParameterAttributes cannot accept version as a numeric Token
  packages/@aws-cdk/aws-ssm/lib/parameter.ts
  packages/@aws-cdk/aws-ssm/test/integ.parameter-store-string.lit.expected.json
  packages/@aws-cdk/aws-ssm/test/integ.parameter-store-string.lit.ts
  packages/@aws-cdk/aws-ssm/test/test.parameter.ts
Labels: p1, effort/small, @aws-cdk/aws-ssm

#15216 feat(docdb): cluster - deletion protection
  packages/@aws-cdk/aws-docdb/README.md
  packages/@aws-cdk/aws-docdb/lib/cluster.ts
  packages/@aws-cdk/aws-docdb/test/cluster.test.ts
Labels: @aws-cdk/aws-docdb

#16211 fix(resourcegroups): ResourceGroup not using TagType.STANDARD, causes deploy failure
  packages/@aws-cdk/cfnspec/spec-source/530_ResourceGroups_Tags_patch.json
Labels: pr-linter/exempt-test

#16216 chore(integ): node check breaks cli integ tests
  packages/aws-cdk/test/integ/cli/cli.integtest.ts
  packages/aws-cdk/test/integ/helpers/cdk.ts
Labels: contribution/core

#16007 feat(cloudwatch): add support for cross-account alarms
  packages/@aws-cdk/aws-cloudwatch/README.md
  packages/@aws-cdk/aws-cloudwatch/lib/alarm.ts
  packages/@aws-cdk/aws-cloudwatch/test/cross-environment.test.ts
Labels: p1, @aws-cdk/aws-cloudwatch, effort/small, contribution/core

#16220 chore(release): 2.0.0-rc.19
  CHANGELOG.v2.md
  version.v2.json
Labels: pr/auto-approve

#16206 revert: temporarily transfer @skinny85 module ownership
  .github/workflows/issue-label-assign.yml
Labels: contribution/core

#16203 fix(s3): bucket is not emptied before update when the name changes
  packages/@aws-cdk/aws-kinesisfirehose-destinations/test/integ.s3-bucket.lit.expected.json
  packages/@aws-cdk/aws-s3/lib/auto-delete-objects-handler/index.ts
  packages/@aws-cdk/aws-s3/test/auto-delete-objects-handler.test.ts
  packages/@aws-cdk/aws-s3/test/integ.bucket-auto-delete-objects.expected.json
Labels: contribution/core

#16258 chore: migrate a few modules from nodeunit-shim to jest
  packages/@aws-cdk/aws-autoscaling/package.json
  packages/@aws-cdk/aws-autoscaling/test/auto-scaling-group.test.ts
  packages/@aws-cdk/aws-autoscaling/test/cfn-init.test.ts
  packages/@aws-cdk/aws-autoscaling/test/lifecyclehooks.test.ts
  packages/@aws-cdk/aws-autoscaling/test/scaling.test.ts
  packages/@aws-cdk/aws-autoscaling/test/scheduled-action.test.ts
  packages/@aws-cdk/aws-codepipeline-actions/package.json
  packages/@aws-cdk/aws-codepipeline-actions/test/bitbucket/bitbucket-source-action.test.ts
  packages/@aws-cdk/aws-codepipeline-actions/test/cloudformation/cloudformation-pipeline-actions.test.ts
  packages/@aws-cdk/aws-codepipeline-actions/test/cloudformation/pipeline-actions.test.ts
  packages/@aws-cdk/aws-codepipeline-actions/test/codebuild/codebuild-action.test.ts
  packages/@aws-cdk/aws-codepipeline-actions/test/codecommit/codecommit-source-action.test.ts
  packages/@aws-cdk/aws-codepipeline-actions/test/codedeploy/ecs-deploy-action.test.ts
  packages/@aws-cdk/aws-codepipeline-actions/test/codestar-connections/codestar-connections-source-action.test.ts
  packages/@aws-cdk/aws-codepipeline-actions/test/ecr/ecr-source-action.test.ts
  packages/@aws-cdk/aws-codepipeline-actions/test/ecs/ecs-deploy-action.test.ts
  packages/@aws-cdk/aws-codepipeline-actions/test/github/github-source-action.test.ts
  packages/@aws-cdk/aws-codepipeline-actions/test/manual-approval.test.ts
  packages/@aws-cdk/aws-codepipeline-actions/test/pipeline.test.ts
  packages/@aws-cdk/aws-codepipeline-actions/test/s3/s3-source-action.test.ts
  packages/@aws-cdk/aws-codepipeline-actions/test/servicecatalog/servicecatalog-deploy-action-beta1.test.ts
  packages/@aws-cdk/aws-codepipeline-actions/test/stepfunctions/stepfunctions-invoke-actions.test.ts
  packages/@aws-cdk/aws-ecs/package.json
  packages/@aws-cdk/aws-ecs/test/app-mesh-proxy-configuration.test.ts
  packages/@aws-cdk/aws-ecs/test/aws-log-driver.test.ts
  packages/@aws-cdk/aws-ecs/test/cluster.test.ts
  packages/@aws-cdk/aws-ecs/test/ec2/cross-stack.test.ts
  packages/@aws-cdk/aws-ecs/test/ec2/ec2-service.test.ts
  packages/@aws-cdk/aws-ecs/test/environment-file.test.ts
  packages/@aws-cdk/aws-ecs/test/external/external-service.test.ts
  packages/@aws-cdk/aws-ecs/test/external/external-task-definition.test.ts
  packages/@aws-cdk/aws-ecs/test/fargate/fargate-service.test.ts
  packages/@aws-cdk/aws-ecs/test/fargate/fargate-task-definition.test.ts
  packages/@aws-cdk/aws-ecs/test/firelens-log-driver.test.ts
  packages/@aws-cdk/aws-ecs/test/fluentd-log-driver.test.ts
  packages/@aws-cdk/aws-ecs/test/gelf-log-driver.test.ts
  packages/@aws-cdk/aws-ecs/test/images/tag-parameter-container-image.test.ts
  packages/@aws-cdk/aws-ecs/test/journald-log-driver.test.ts
  packages/@aws-cdk/aws-ecs/test/json-file-log-driver.test.ts
  packages/@aws-cdk/aws-ecs/test/splunk-log-driver.test.ts
  packages/@aws-cdk/aws-ecs/test/syslog-log-driver.test.ts
  packages/@aws-cdk/aws-ecs/test/task-definition.test.ts
  packages/@aws-cdk/aws-route53/package.json
  packages/@aws-cdk/aws-route53/test/hosted-zone-provider.test.ts
  packages/@aws-cdk/aws-route53/test/hosted-zone.test.ts
  packages/@aws-cdk/aws-route53/test/record-set.test.ts
  packages/@aws-cdk/aws-route53/test/route53.test.ts
  packages/@aws-cdk/aws-route53/test/util.test.ts
  packages/@aws-cdk/aws-route53/test/vpc-endpoint-service-domain-name.test.ts
  packages/@aws-cdk/aws-s3/package.json
  packages/@aws-cdk/aws-s3/test/aspect.test.ts
  packages/@aws-cdk/aws-s3/test/bucket-policy.test.ts
  packages/@aws-cdk/aws-s3/test/cors.test.ts
  packages/@aws-cdk/aws-s3/test/metrics.test.ts
  packages/@aws-cdk/aws-s3/test/notification.test.ts
  packages/@aws-cdk/aws-s3/test/rules.test.ts
  packages/@aws-cdk/aws-s3/test/util.test.ts
Labels: contribution/core

#16276 feat(core): normalize line endings in asset hash calculation
  packages/@aws-cdk/core/lib/fs/fingerprint.ts
  packages/@aws-cdk/core/test/fs/eol/lf.txt
  packages/@aws-cdk/core/test/fs/fs-fingerprint.test.ts
Labels: pr-linter/exempt-readme

#16184 chore: upgrade jsii packages
  package.json
  tools/cdk-integ-tools/lib/integ-helpers.ts
  yarn.lock
Labels: contribution/core

#16285 chore: upgrade jsii version
  tools/cdk-build-tools/package.json
  yarn.lock
Labels: contribution/core

#16248 chore: assign AppMesh issues to Seiya6329
  .github/workflows/issue-label-assign.yml
Labels: contribution/core

#16286 fix(aws-rds): fromDatabaseInstanceAttributes incorrectly stringifies ports with tokens
  packages/@aws-cdk/aws-rds/lib/instance.ts
  packages/@aws-cdk/aws-rds/test/instance.test.ts
Labels: contribution/core

#15031 feat(route53resolver): DNS Firewall
  packages/@aws-cdk/aws-route53resolver/README.md
  packages/@aws-cdk/aws-route53resolver/lib/firewall-domain-list.ts
  packages/@aws-cdk/aws-route53resolver/lib/firewall-rule-group-association.ts
  packages/@aws-cdk/aws-route53resolver/lib/firewall-rule-group.ts
  packages/@aws-cdk/aws-route53resolver/lib/index.ts
  packages/@aws-cdk/aws-route53resolver/package.json
  packages/@aws-cdk/aws-route53resolver/test/domains.txt
  packages/@aws-cdk/aws-route53resolver/test/firewall-domain-list.test.ts
  packages/@aws-cdk/aws-route53resolver/test/firewall-rule-group.test.ts
  packages/@aws-cdk/aws-route53resolver/test/integ.firewall.expected.json
  packages/@aws-cdk/aws-route53resolver/test/integ.firewall.ts
  packages/@aws-cdk/aws-route53resolver/test/route53resolver.test.ts
Labels: p1, effort/medium, @aws-cdk/aws-route53resolver

#16293 feat(cli): support `--no-rollback` flag
  packages/aws-cdk/README.md
  packages/aws-cdk/bin/cdk.ts
  packages/aws-cdk/lib/api/cloudformation-deployments.ts
  packages/aws-cdk/lib/api/deploy-stack.ts
  packages/aws-cdk/lib/cdk-toolkit.ts
  packages/aws-cdk/lib/settings.ts
  packages/aws-cdk/package.json
  packages/aws-cdk/test/api/deploy-stack.test.ts
  yarn.lock
Labels: contribution/core

#16295 chore: migrate some modules from nodeunit to jest
  packages/@aws-cdk/app-delivery/.gitignore
  packages/@aws-cdk/app-delivery/.npmignore
  packages/@aws-cdk/app-delivery/jest.config.js
  packages/@aws-cdk/app-delivery/package.json
  packages/@aws-cdk/app-delivery/test/pipeline-deploy-stack-action.test.ts
  packages/@aws-cdk/aws-applicationautoscaling/.gitignore
  packages/@aws-cdk/aws-applicationautoscaling/.npmignore
  packages/@aws-cdk/aws-applicationautoscaling/jest.config.js
  packages/@aws-cdk/aws-applicationautoscaling/package.json
  packages/@aws-cdk/aws-applicationautoscaling/test/cron.test.ts
  packages/@aws-cdk/aws-applicationautoscaling/test/scalable-target.test.ts
  packages/@aws-cdk/aws-applicationautoscaling/test/step-scaling-policy.test.ts
  packages/@aws-cdk/aws-applicationautoscaling/test/target-tracking.test.ts
  packages/@aws-cdk/aws-applicationautoscaling/test/test.cron.ts
  packages/@aws-cdk/aws-eks-legacy/.gitignore
  packages/@aws-cdk/aws-eks-legacy/.npmignore
  packages/@aws-cdk/aws-eks-legacy/jest.config.js
  packages/@aws-cdk/aws-eks-legacy/package.json
  packages/@aws-cdk/aws-eks-legacy/test/awsauth.test.ts
  packages/@aws-cdk/aws-eks-legacy/test/cluster.test.ts
  packages/@aws-cdk/aws-eks-legacy/test/helm-chart.test.ts
  packages/@aws-cdk/aws-eks-legacy/test/manifest.test.ts
  packages/@aws-cdk/aws-eks-legacy/test/test.cluster-resource.ts
  packages/@aws-cdk/aws-eks-legacy/test/test.helm-chart.ts
  packages/@aws-cdk/aws-eks-legacy/test/user-data.test.ts
  packages/@aws-cdk/aws-events/.gitignore
  packages/@aws-cdk/aws-events/.npmignore
  packages/@aws-cdk/aws-events/jest.config.js
  packages/@aws-cdk/aws-events/package.json
  packages/@aws-cdk/aws-events/test/archive.test.ts
  packages/@aws-cdk/aws-events/test/event-bus.test.ts
  packages/@aws-cdk/aws-events/test/input.test.ts
  packages/@aws-cdk/aws-events/test/rule.test.ts
  packages/@aws-cdk/aws-events/test/schedule.test.ts
  packages/@aws-cdk/aws-events/test/test.schedule.ts
  packages/@aws-cdk/aws-events/test/util.test.ts
Labels: contribution/core

#16219 chore: forward merge 'master' into 'v2-main'
  packages/@aws-cdk/assertions/README.md
  packages/@aws-cdk/assertions/lib/match.ts
  packages/@aws-cdk/assertions/lib/matcher.ts
  packages/@aws-cdk/assertions/lib/private/mappings.ts
  packages/@aws-cdk/assertions/lib/private/outputs.ts
  packages/@aws-cdk/assertions/lib/private/resource.ts
  packages/@aws-cdk/assertions/lib/private/resources.ts
  packages/@aws-cdk/assertions/lib/private/section.ts
  packages/@aws-cdk/assertions/lib/template.ts
  packages/@aws-cdk/assertions/test/private/section.test.ts
  packages/@aws-cdk/assertions/test/template.test.ts
  packages/@aws-cdk/aws-apigatewayv2/lib/common/domain-name.ts
  packages/@aws-cdk/aws-apigatewayv2/test/http/domain-name.test.ts
  packages/@aws-cdk/aws-cloudwatch/README.md
  packages/@aws-cdk/aws-cloudwatch/lib/alarm.ts
  packages/@aws-cdk/aws-cloudwatch/test/cross-environment.test.ts
  packages/@aws-cdk/aws-cognito/README.md
  packages/@aws-cdk/aws-cognito/lib/user-pool.ts
  packages/@aws-cdk/aws-cognito/test/user-pool.test.ts
  packages/@aws-cdk/aws-docdb/README.md
  packages/@aws-cdk/aws-docdb/lib/cluster.ts
  packages/@aws-cdk/aws-docdb/test/cluster.test.ts
  packages/@aws-cdk/aws-ec2/lib/vpc-endpoint.ts
  packages/@aws-cdk/aws-ec2/test/vpc-endpoint.test.ts
  packages/@aws-cdk/aws-kinesisfirehose/package.json
  packages/@aws-cdk/aws-kinesisfirehose/test/delivery-stream.test.ts
  packages/@aws-cdk/aws-lambda/lib/runtime.ts
  packages/@aws-cdk/aws-lambda/test/integ.runtime.inlinecode.expected.json
  packages/@aws-cdk/aws-lambda/test/integ.runtime.inlinecode.ts
  packages/@aws-cdk/aws-neptune/package.json
  packages/@aws-cdk/aws-neptune/test/cluster.test.ts
  packages/@aws-cdk/aws-neptune/test/instance.test.ts
  packages/@aws-cdk/aws-neptune/test/parameter-group.test.ts
  packages/@aws-cdk/aws-neptune/test/subnet-group.test.ts
  packages/@aws-cdk/aws-sqs/lib/queue-base.ts
  packages/@aws-cdk/aws-sqs/lib/queue.ts
  packages/@aws-cdk/aws-sqs/test/test.sqs.ts
  packages/@aws-cdk/aws-ssm/lib/parameter.ts
  packages/@aws-cdk/aws-ssm/test/integ.parameter-store-string.lit.expected.json
  packages/@aws-cdk/aws-ssm/test/integ.parameter-store-string.lit.ts
  packages/@aws-cdk/aws-ssm/test/test.parameter.ts
  packages/@aws-cdk/cfnspec/spec-source/530_ResourceGroups_Tags_patch.json
  packages/@aws-cdk/pipelines/README.md
  packages/@aws-cdk/pipelines/lib/codepipeline/_codebuild-factory.ts
  packages/@aws-cdk/pipelines/test/docker-credentials.test.ts
  packages/aws-cdk/bin/cdk.ts
  packages/aws-cdk/package.json
  packages/aws-cdk/test/integ/cli/cli.integtest.ts
  packages/aws-cdk/test/integ/helpers/cdk.ts
  yarn.lock
Labels: pr/no-squash, pr/forward-merge, pr/auto-approve

#16182 chore(cdk-release): support separate alpha Changelog
  scripts/bump.js
  scripts/resolve-version-lib.js
  scripts/script-tests/resolve-version.test.js
  tools/cdk-release/lib/conventional-commits.ts
  tools/cdk-release/lib/index.ts
  tools/cdk-release/lib/lifecycles/changelog.ts
  tools/cdk-release/lib/types.ts
  tools/cdk-release/test/changelog.test.ts
  tools/cdk-release/test/conventional-commits.test.ts
Labels: contribution/core

#16300 fix(core): inconsistent analytics string across operating systems
  packages/@aws-cdk/core/lib/private/metadata-resource.ts
  packages/@aws-cdk/core/test/metadata-resource.test.ts
Labels: contribution/core

#16296 feat(stepfunctions-tasks): support allocation strategies in EMR CreateCluster
  packages/@aws-cdk/aws-stepfunctions-tasks/lib/emr/emr-create-cluster.ts
  packages/@aws-cdk/aws-stepfunctions-tasks/lib/emr/private/cluster-utils.ts
  packages/@aws-cdk/aws-stepfunctions-tasks/test/emr/emr-create-cluster.test.ts
Labels: pr-linter/exempt-readme, @aws-cdk/aws-stepfunctions-tasks
