Repository aws/aws-cdk, pull requests merged in 2022-06, with the labels that each got.

#20560 fix(core): logicalId is consumed prior to being overridden
  packages/@aws-cdk/core/lib/cfn-element.ts
  packages/@aws-cdk/core/lib/stack.ts
  packages/@aws-cdk/core/test/stack.test.ts
Labels: bug, p1, effort/medium, contribution/core

#20563 fix(ecr-assets): cannot build ARM images using modern stack synthesis
  packages/@aws-cdk/aws-ecr-assets/test/image-asset.test.ts
  packages/@aws-cdk/core/lib/stack-synthesizers/_asset-manifest-builder.ts
Labels: p2

#20497 fix(iam): referencing the same immutable role twice makes it mutable
  packages/@aws-cdk/aws-iam/lib/role.ts
  packages/@aws-cdk/aws-iam/test/immutable-role.test.ts
Labels: bug, p1, effort/small, contribution/core

#20479 fix(events-targets): EventBus IAM statements are only added for the first target
  packages/@aws-cdk/aws-events-targets/lib/api-destination.ts
  packages/@aws-cdk/aws-events-targets/lib/api-gateway.ts
  packages/@aws-cdk/aws-events-targets/lib/batch.ts
  packages/@aws-cdk/aws-events-targets/lib/codebuild.ts
  packages/@aws-cdk/aws-events-targets/lib/codepipeline.ts
  packages/@aws-cdk/aws-events-targets/lib/ecs-task.ts
  packages/@aws-cdk/aws-events-targets/lib/event-bus.ts
  packages/@aws-cdk/aws-events-targets/lib/kinesis-firehose-stream.ts
  packages/@aws-cdk/aws-events-targets/lib/kinesis-stream.ts
  packages/@aws-cdk/aws-events-targets/lib/state-machine.ts
  packages/@aws-cdk/aws-events-targets/lib/util.ts
  packages/@aws-cdk/aws-events-targets/test/event-bus/event-rule-target.test.ts
Labels: bug, p1, effort/small, contribution/core

#19942 chore: update dependabot and yarn-upgrade config
  .github/dependabot.yml
  .github/workflows/yarn-upgrade-v1main.yml
Labels: p2, contribution/core

#20504 fix(rds): clusters created from snapshots generate incorrect passwords
  packages/@aws-cdk/aws-rds/lib/cluster.ts
  packages/@aws-cdk/aws-rds/package.json
  packages/@aws-cdk/aws-rds/test/cluster-snapshot.integ.snapshot/asset.1e025324752b3133dc230c4b8b8752f666b63c09cd4aa605ec2b322cc40def2e/index.d.ts
  packages/@aws-cdk/aws-rds/test/cluster-snapshot.integ.snapshot/asset.1e025324752b3133dc230c4b8b8752f666b63c09cd4aa605ec2b322cc40def2e/index.js
  packages/@aws-cdk/aws-rds/test/cluster-snapshot.integ.snapshot/asset.1e025324752b3133dc230c4b8b8752f666b63c09cd4aa605ec2b322cc40def2e/index.ts
  packages/@aws-cdk/aws-rds/test/cluster-snapshot.integ.snapshot/asset.8dd02cc4ac473ca5b08800e92edaa31a1a7db4005928021d029c5363584f11b9/cfn-response.js
  packages/@aws-cdk/aws-rds/test/cluster-snapshot.integ.snapshot/asset.8dd02cc4ac473ca5b08800e92edaa31a1a7db4005928021d029c5363584f11b9/consts.js
  packages/@aws-cdk/aws-rds/test/cluster-snapshot.integ.snapshot/asset.8dd02cc4ac473ca5b08800e92edaa31a1a7db4005928021d029c5363584f11b9/framework.js
  packages/@aws-cdk/aws-rds/test/cluster-snapshot.integ.snapshot/asset.8dd02cc4ac473ca5b08800e92edaa31a1a7db4005928021d029c5363584f11b9/outbound.js
  packages/@aws-cdk/aws-rds/test/cluster-snapshot.integ.snapshot/asset.8dd02cc4ac473ca5b08800e92edaa31a1a7db4005928021d029c5363584f11b9/util.js
  packages/@aws-cdk/aws-rds/test/cluster-snapshot.integ.snapshot/cdk-integ-cluster-snapshot.template.json
  packages/@aws-cdk/aws-rds/test/cluster-snapshot.integ.snapshot/cdk.out
  packages/@aws-cdk/aws-rds/test/cluster-snapshot.integ.snapshot/integ.json
  packages/@aws-cdk/aws-rds/test/cluster-snapshot.integ.snapshot/manifest.json
  packages/@aws-cdk/aws-rds/test/cluster-snapshot.integ.snapshot/tree.json
  packages/@aws-cdk/aws-rds/test/cluster.test.ts
  packages/@aws-cdk/aws-rds/test/integ.cluster-snapshot.ts
  packages/@aws-cdk/aws-rds/test/snapshot-handler/index.ts
Labels: bug, p1, effort/medium

#20449 feat(core): `addToRolePolicy()` for custom resource provider
  packages/@aws-cdk/core/README.md
  packages/@aws-cdk/core/lib/custom-resource-provider/custom-resource-provider.ts
  packages/@aws-cdk/core/test/custom-resource-provider/custom-resource-provider.test.ts
  packages/aws-cdk-lib/README.md
Labels: p2, pr-linter/exempt-integ-test

#20589 chore(core): backport unit test fix from main to v1-main
  packages/@aws-cdk/core/test/stack.test.ts
Labels: p2, contribution/core

#20576 feat(pipelines): pass role to s3 source action
  packages/@aws-cdk/pipelines/lib/codepipeline/codepipeline-source.ts
  packages/@aws-cdk/pipelines/test/codepipeline/codepipeline-sources.test.ts
Labels: p1, feature-request, effort/small, pr-linter/exempt-readme, pr-linter/exempt-integ-test

#20577 docs(glue): refresh links for aws glue documentation
  packages/@aws-cdk/aws-glue/lib/data-format.ts
Labels: p2, effort/small

#20581 chore: update the contributing guide for post v1 maintenance mode
  CONTRIBUTING.md
Labels: p2, effort/small, contribution/core

#20599 chore(merge-back): 2.27.0
  CHANGELOG.v2.alpha.md
  CHANGELOG.v2.md
  version.v2.json
Labels: p2, pr/no-squash, auto-approve

#20600 chore(merge-back): 1.159.0
  CHANGELOG.md
  version.v1.json
Labels: p2, pr/no-squash, auto-approve

#20608 fix(core): property overrides sometimes don't work with intrinsics
  packages/@aws-cdk/core/lib/cfn-resource.ts
  packages/@aws-cdk/core/test/resource.test.ts
Labels: bug, p1, effort/small, contribution/core

#20178 feat(codebuild): adds report group type property
  packages/@aws-cdk/aws-codebuild/README.md
  packages/@aws-cdk/aws-codebuild/lib/report-group.ts
  packages/@aws-cdk/aws-codebuild/test/report-group.test.ts
Labels: p1, feature-request, effort/medium, pr-linter/exempt-integ-test

#20562 feat(aws-ec2): control over VPC AZs
  packages/@aws-cdk/aws-ec2/README.md
  packages/@aws-cdk/aws-ec2/lib/vpc.ts
  packages/@aws-cdk/aws-ec2/test/integ.vpc-azs.ts
  packages/@aws-cdk/aws-ec2/test/vpc-azs.integ.snapshot/aws-cdk-ec2-vpc-azs.assets.json
  packages/@aws-cdk/aws-ec2/test/vpc-azs.integ.snapshot/aws-cdk-ec2-vpc-azs.template.json
  packages/@aws-cdk/aws-ec2/test/vpc-azs.integ.snapshot/cdk.out
  packages/@aws-cdk/aws-ec2/test/vpc-azs.integ.snapshot/integ.json
  packages/@aws-cdk/aws-ec2/test/vpc-azs.integ.snapshot/manifest.json
  packages/@aws-cdk/aws-ec2/test/vpc-azs.integ.snapshot/tree.json
  packages/@aws-cdk/aws-ec2/test/vpc.test.ts
Labels: p2, feature-request, effort/small

#20639 chore(servicediscovery): rename docs/test props
  packages/@aws-cdk/aws-servicediscovery/test/integ.service-with-http-namespace.lit.ts
  packages/@aws-cdk/aws-servicediscovery/test/service-with-http-namespace.lit.integ.snapshot/aws-servicediscovery-integ.template.json
  packages/@aws-cdk/aws-servicediscovery/test/service-with-http-namespace.lit.integ.snapshot/tree.json
Labels: p2

#20637 docs(lambda): close code block in addAlias, restore addEnvironment docs
  packages/@aws-cdk/aws-lambda/lib/function.ts
Labels: p2, effort/small

#20654 feat(core): allow specifying Docker build targets
  packages/@aws-cdk/core/lib/bundling.ts
  packages/@aws-cdk/core/test/bundling.test.ts
Labels: p2, feature-request

#20612 chore: clarify .Net core versions in contributing guide
  CONTRIBUTING.md
Labels: p2

#20671 chore(cx-api): add missing documentation for feature flag
  packages/@aws-cdk/cx-api/lib/features.ts
Labels: p2, contribution/core

#20621 fix(iam): conditions in FederatedPrincipal should be optional
  packages/@aws-cdk/aws-iam/lib/principals.ts
  packages/@aws-cdk/aws-iam/test/principals.test.ts
Labels: bug, p2, effort/small, pr-linter/exempt-integ-test

#20688 fix(servicecatalog): ProductStackHistory does not accept nested directories
  packages/@aws-cdk/aws-servicecatalog/lib/product-stack-history.ts
  packages/@aws-cdk/aws-servicecatalog/test/product.test.ts
Labels: bug, p2, effort/small

#20692 docs(rds): Fix storage allocation units
  packages/@aws-cdk/aws-rds/lib/instance.ts
Labels: bug, p1, effort/small

#20699 chore(region-info): Register iso facts
  packages/@aws-cdk/region-info/build-tools/fact-tables.ts
Labels: p2

#20604 Add Textract support to AWS VpcEndpoint services
  packages/@aws-cdk/aws-ec2/lib/vpc-endpoint.ts
  packages/@aws-cdk/aws-ec2/package.json
Labels: p2

#20672 docs(secretsmanager): Updates example in secretsmanager code
  packages/@aws-cdk/aws-secretsmanager/lib/secret.ts
Labels: bug, p2, effort/small

#20602 feat(opensearchservice): When a Domain has enforceHttps true, set the connections defaultPort
  packages/@aws-cdk/aws-opensearchservice/lib/domain.ts
  packages/@aws-cdk/aws-opensearchservice/test/domain.test.ts
Labels: p2, feature-request, effort/small, pr-linter/exempt-readme, pr-linter/exempt-integ-test

#20707 fix(eks): add clusterLogging props to Fargate Cluster
  packages/@aws-cdk/aws-eks/lib/cluster.ts
  packages/@aws-cdk/aws-eks/test/fargate.test.ts
Labels: bug, p1, effort/small

#20720 chore(aws-rds): add doc references
  packages/@aws-cdk/aws-rds/lib/cluster.ts
Labels: p2, pr-linter/exempt-test, pr-linter/exempt-integ-test

#20696 chore(core): IConstruct is passed to Names.uniqueId instead of Construct (#20584)
  packages/@aws-cdk/core/lib/names.ts
Labels: p2, feature-request, effort/small

#20614 fix(integ-runner): don't allow new legacy tests
  CONTRIBUTING.md
  INTEGRATION_TESTS.md
  packages/@aws-cdk/integ-runner/lib/runner/integ-test-runner.ts
  packages/@aws-cdk/integ-runner/lib/runner/runner-base.ts
  packages/@aws-cdk/integ-runner/test/runner/integ-test-runner.test.ts
  packages/@aws-cdk/integ-runner/test/runner/snapshot-test-runner.test.ts
  packages/@aws-cdk/integ-runner/test/test-data/cdk-integ.out.integ-test1/integ.json
  packages/@aws-cdk/integ-runner/test/test-data/cdk-integ.out.test-with-snapshot-assets/integ.json
  packages/@aws-cdk/integ-runner/test/test-data/cdk-integ.out.test-with-snapshot/integ.json
  packages/@aws-cdk/integ-runner/test/test-data/test-with-snapshot-assets-diff.integ.snapshot/integ.json
  packages/@aws-cdk/integ-runner/test/test-data/test-with-snapshot-assets.integ.snapshot/integ.json
  packages/@aws-cdk/integ-runner/test/test-data/test-with-snapshot-diff.integ.snapshot/integ.json
  packages/@aws-cdk/integ-runner/test/test-data/test-with-snapshot.integ.snapshot/integ.json
  packages/@aws-cdk/integ-runner/test/test-data/xxxxx.integ-test1.ts
  packages/@aws-cdk/integ-runner/test/test-data/xxxxx.integ-test2.ts
  packages/@aws-cdk/integ-runner/test/test-data/xxxxx.test-with-snapshot-assets-diff.ts
  packages/@aws-cdk/integ-runner/test/test-data/xxxxx.test-with-snapshot-assets.ts
  packages/@aws-cdk/integ-runner/test/test-data/xxxxx.test-with-snapshot.ts
  packages/@aws-cdk/integ-runner/test/workers/integ-worker.test.ts
  packages/@aws-cdk/integ-runner/test/workers/snapshot-worker.test.ts
Labels: p2, contribution/core

#18663 feat(ecs-patterns): add ecs exec support
  packages/@aws-cdk/aws-ecs-patterns/README.md
  packages/@aws-cdk/aws-ecs-patterns/lib/base/application-load-balanced-service-base.ts
  packages/@aws-cdk/aws-ecs-patterns/lib/base/application-multiple-target-groups-service-base.ts
  packages/@aws-cdk/aws-ecs-patterns/lib/base/network-load-balanced-service-base.ts
  packages/@aws-cdk/aws-ecs-patterns/lib/base/network-multiple-target-groups-service-base.ts
  packages/@aws-cdk/aws-ecs-patterns/lib/base/queue-processing-service-base.ts
  packages/@aws-cdk/aws-ecs-patterns/lib/ecs/application-load-balanced-ecs-service.ts
  packages/@aws-cdk/aws-ecs-patterns/lib/ecs/application-multiple-target-groups-ecs-service.ts
  packages/@aws-cdk/aws-ecs-patterns/lib/ecs/network-load-balanced-ecs-service.ts
  packages/@aws-cdk/aws-ecs-patterns/lib/ecs/network-multiple-target-groups-ecs-service.ts
  packages/@aws-cdk/aws-ecs-patterns/lib/ecs/queue-processing-ecs-service.ts
  packages/@aws-cdk/aws-ecs-patterns/lib/fargate/application-load-balanced-fargate-service.ts
  packages/@aws-cdk/aws-ecs-patterns/lib/fargate/application-multiple-target-groups-fargate-service.ts
  packages/@aws-cdk/aws-ecs-patterns/lib/fargate/network-load-balanced-fargate-service.ts
  packages/@aws-cdk/aws-ecs-patterns/lib/fargate/network-multiple-target-groups-fargate-service.ts
  packages/@aws-cdk/aws-ecs-patterns/lib/fargate/queue-processing-fargate-service.ts
  packages/@aws-cdk/aws-ecs-patterns/test/ec2/integ.multiple-application-load-balanced-ecs-service.ts
  packages/@aws-cdk/aws-ecs-patterns/test/ec2/l3s-v2.test.ts
  packages/@aws-cdk/aws-ecs-patterns/test/ec2/multiple-application-load-balanced-ecs-service.integ.snapshot/aws-ecs-integ.template.json
  packages/@aws-cdk/aws-ecs-patterns/test/ec2/queue-processing-ecs-service.test.ts
  packages/@aws-cdk/aws-ecs-patterns/test/fargate/alb-fargate-service-https.integ.snapshot/aws-ecs-integ-alb-fg-https.template.json
  packages/@aws-cdk/aws-ecs-patterns/test/fargate/integ.alb-fargate-service-https.ts
  packages/@aws-cdk/aws-ecs-patterns/test/fargate/load-balanced-fargate-service-v2.test.ts
  packages/@aws-cdk/aws-ecs-patterns/test/fargate/queue-processing-fargate-service.test.ts
  packages/@aws-cdk/cx-api/package.json
Labels: p2, feature-request, effort/small

#18615 feat(cloudwatch): add `addWidget` method in widget container classes
  packages/@aws-cdk/aws-cloudwatch/README.md
  packages/@aws-cdk/aws-cloudwatch/lib/layout.ts
  packages/@aws-cdk/aws-cloudwatch/test/layout.test.ts
Labels: p2, feature-request, effort/small, pr-linter/exempt-integ-test

#17762 feat(ecs): add external network modes to ExternalTaskDefinition and TaskDefinition
  packages/@aws-cdk/aws-ecs/README.md
  packages/@aws-cdk/aws-ecs/lib/base/task-definition.ts
  packages/@aws-cdk/aws-ecs/lib/external/external-task-definition.ts
  packages/@aws-cdk/aws-ecs/test/external/external-task-definition.test.ts
  packages/@aws-cdk/aws-ecs/test/task-definition.test.ts
Labels: p2, @aws-cdk/aws-ecs, pr-linter/exempt-integ-test

#20719 fix(events): eventSourceName does not accept tokens
  packages/@aws-cdk/aws-events/lib/event-bus.ts
  packages/@aws-cdk/aws-events/test/event-bus.test.ts
Labels: p2

#20733 chore(merge-back): 2.28.0
  CHANGELOG.v2.alpha.md
  CHANGELOG.v2.md
  version.v2.json
Labels: p2, pr/no-squash, auto-approve

#20736 chore(merge-back): 1.160.0
  CHANGELOG.md
  version.v1.json
Labels: p2, pr/no-squash, auto-approve

#20624 feat(lambda): inline function code can exceed 4096 bytes
  packages/@aws-cdk/aws-lambda/README.md
  packages/@aws-cdk/aws-lambda/lib/code.ts
  packages/@aws-cdk/aws-lambda/test/code.test.ts
Labels: p2, pr-linter/exempt-integ-test

#20062 feat(events-targets): Add DLQ support for SNS target
  packages/@aws-cdk/aws-events-targets/README.md
  packages/@aws-cdk/aws-events-targets/lib/sns.ts
  packages/@aws-cdk/aws-events-targets/test/sns/integ.sns-event-rule-target.ts
  packages/@aws-cdk/aws-events-targets/test/sns/sns-event-rule-target.integ.snapshot/aws-cdk-sns-event-target.template.json
  packages/@aws-cdk/aws-events-targets/test/sns/sns-event-rule-target.integ.snapshot/cdk.out
  packages/@aws-cdk/aws-events-targets/test/sns/sns-event-rule-target.integ.snapshot/integ.json
  packages/@aws-cdk/aws-events-targets/test/sns/sns-event-rule-target.integ.snapshot/manifest.json
  packages/@aws-cdk/aws-events-targets/test/sns/sns-event-rule-target.integ.snapshot/tree.json
  packages/@aws-cdk/aws-events-targets/test/sns/sns.test.ts
Labels: p2, feature-request, effort/small

#20740 docs(synthetics): update inline code limitation
  packages/@aws-cdk/aws-synthetics/lib/code.ts
Labels: p2

#20616 fix(core): CfnMapping values cannot be used in other stacks
  packages/@aws-cdk/core/lib/cfn-mapping.ts
  packages/@aws-cdk/core/test/mappings.test.ts
Labels: bug, p1, effort/small, contribution/core

#20745 fix(codepipeline): cannot deploy pipeline stack with crossAccountKeys twice (under feature flag)
  packages/@aws-cdk/aws-codepipeline-actions/test/cfn-template-from-repo.lit.integ.snapshot/aws-cdk-codepipeline-cloudformation.template.json
  packages/@aws-cdk/aws-codepipeline-actions/test/lambda-deployed-through-codepipeline.lit.integ.snapshot/PipelineStack.template.json
  packages/@aws-cdk/aws-codepipeline-actions/test/lambda-pipeline.integ.snapshot/aws-cdk-codepipeline-lambda.template.json
  packages/@aws-cdk/aws-codepipeline-actions/test/pipeline-alexa-deploy.integ.snapshot/aws-cdk-codepipeline-alexa-deploy.template.json
  packages/@aws-cdk/aws-codepipeline-actions/test/pipeline-cfn.integ.snapshot/aws-cdk-codepipeline-cloudformation.template.json
  packages/@aws-cdk/aws-codepipeline-actions/test/pipeline-code-commit-build.integ.snapshot/aws-cdk-codepipeline-codecommit-codebuild.template.json
  packages/@aws-cdk/aws-codepipeline-actions/test/pipeline-code-commit.integ.snapshot/aws-cdk-codepipeline-codecommit.template.json
  packages/@aws-cdk/aws-codepipeline-actions/test/pipeline-events.integ.snapshot/aws-cdk-pipeline-event-target.template.json
  packages/@aws-cdk/aws-codepipeline-actions/test/pipeline-stepfunctions.integ.snapshot/aws-cdk-codepipeline-stepfunctions.template.json
  packages/@aws-cdk/aws-codepipeline/lib/pipeline.ts
  packages/@aws-cdk/aws-codepipeline/package.json
  packages/@aws-cdk/aws-codepipeline/test/pipeline.test.ts
  packages/@aws-cdk/aws-events-targets/test/codepipeline/pipeline-event-target.integ.snapshot/pipeline-events.template.json
  packages/@aws-cdk/core/lib/names.ts
  packages/@aws-cdk/core/lib/private/unique-resource-name.ts
  packages/@aws-cdk/core/test/private/unique-resource-name.test.ts
  packages/@aws-cdk/cx-api/lib/features.ts
  packages/@aws-cdk/pipelines/test/pipeline-security.integ.snapshot/PipelineSecurityStack.template.json
  packages/@aws-cdk/pipelines/test/pipeline-with-assets-single-upload.integ.snapshot/PipelineStack.template.json
  packages/@aws-cdk/pipelines/test/pipeline-with-assets.integ.snapshot/PipelineStack.template.json
  packages/@aws-cdk/pipelines/test/pipeline.integ.snapshot/PipelineStack.template.json
Labels: p1, contribution/core, pr-linter/exempt-readme

#20533 feat(pipelines): add support for caching to codebuild steps
  packages/@aws-cdk/pipelines/README.md
  packages/@aws-cdk/pipelines/lib/codepipeline/codebuild-step.ts
  packages/@aws-cdk/pipelines/lib/codepipeline/codepipeline.ts
  packages/@aws-cdk/pipelines/lib/codepipeline/private/codebuild-factory.ts
  packages/@aws-cdk/pipelines/test/codepipeline/codebuild-step.test.ts
  packages/@aws-cdk/pipelines/test/integ.pipeline-with-variables.ts
  packages/@aws-cdk/pipelines/test/pipeline-with-variables.integ.snapshot/VariablePipelineStack.template.json
  packages/@aws-cdk/pipelines/test/pipeline-with-variables.integ.snapshot/manifest.json
  packages/@aws-cdk/pipelines/test/pipeline-with-variables.integ.snapshot/tree.json
Labels: p2, feature-request, effort/medium

#20752 fix(init-templates): unable to initialize typescript templates
  packages/aws-cdk/lib/init-templates/v1/app/typescript/package.json
  packages/aws-cdk/lib/init-templates/v1/lib/typescript/package.json
  packages/aws-cdk/lib/init-templates/v1/sample-app/typescript/package.json
  packages/aws-cdk/lib/init-templates/v2/app/typescript/package.json
  packages/aws-cdk/lib/init-templates/v2/lib/typescript/package.json
  packages/aws-cdk/lib/init-templates/v2/sample-app/typescript/package.json
Labels: bug, p0, pr-linter/exempt-test

#20759 fix(autoscaling): osType is wrong when using CloudformationInit with launchTemplate
  packages/@aws-cdk/aws-autoscaling/lib/auto-scaling-group.ts
  packages/@aws-cdk/aws-autoscaling/test/auto-scaling-group.test.ts
Labels: bug, p2, effort/small

#20761 docs(lambda): Fixed consecutive "when"
  packages/@aws-cdk/aws-lambda/lib/function.ts
Labels: p2

#20767 fix(iam): duplicate PolicyStatements lead to too many overflow policies
  packages/@aws-cdk/aws-iam/lib/policy-document.ts
  packages/@aws-cdk/aws-iam/lib/private/merge-statements.ts
  packages/@aws-cdk/aws-iam/test/role.test.ts
Labels: p2, contribution/core

#20768 feat(secretsmanager): exclude characters for hosted rotation
  packages/@aws-cdk/aws-secretsmanager/README.md
  packages/@aws-cdk/aws-secretsmanager/lib/rotation-schedule.ts
  packages/@aws-cdk/aws-secretsmanager/lib/secret.ts
  packages/@aws-cdk/aws-secretsmanager/test/hosted-rotation.integ.snapshot/cdk-integ-secret-hosted-rotation.assets.json
  packages/@aws-cdk/aws-secretsmanager/test/hosted-rotation.integ.snapshot/cdk-integ-secret-hosted-rotation.template.json
  packages/@aws-cdk/aws-secretsmanager/test/hosted-rotation.integ.snapshot/cdk.out
  packages/@aws-cdk/aws-secretsmanager/test/hosted-rotation.integ.snapshot/integ.json
  packages/@aws-cdk/aws-secretsmanager/test/hosted-rotation.integ.snapshot/manifest.json
  packages/@aws-cdk/aws-secretsmanager/test/hosted-rotation.integ.snapshot/tree.json
  packages/@aws-cdk/aws-secretsmanager/test/integ.hosted-rotation.ts
  packages/@aws-cdk/aws-secretsmanager/test/rotation-schedule.test.ts
Labels: p2

#20416 feat(route53): replace existing record sets
  packages/@aws-cdk/aws-route53/README.md
  packages/@aws-cdk/aws-route53/lib/delete-existing-record-set-handler/index.ts
  packages/@aws-cdk/aws-route53/lib/record-set.ts
  packages/@aws-cdk/aws-route53/test/delete-existing-record-set-handler.test.ts
  packages/@aws-cdk/aws-route53/test/delete-existing-record-set.integ.snapshot/asset.c23b07956b28fe984628bd40d10bd917e27100e0eb632e8b093e789cd110a5ad/__entrypoint__.js
  packages/@aws-cdk/aws-route53/test/delete-existing-record-set.integ.snapshot/asset.c23b07956b28fe984628bd40d10bd917e27100e0eb632e8b093e789cd110a5ad/index.d.ts
  packages/@aws-cdk/aws-route53/test/delete-existing-record-set.integ.snapshot/asset.c23b07956b28fe984628bd40d10bd917e27100e0eb632e8b093e789cd110a5ad/index.js
  packages/@aws-cdk/aws-route53/test/delete-existing-record-set.integ.snapshot/asset.c23b07956b28fe984628bd40d10bd917e27100e0eb632e8b093e789cd110a5ad/index.ts
  packages/@aws-cdk/aws-route53/test/delete-existing-record-set.integ.snapshot/cdk-route53-integ-delete-existing-record-set.assets.json
  packages/@aws-cdk/aws-route53/test/delete-existing-record-set.integ.snapshot/cdk-route53-integ-delete-existing-record-set.template.json
  packages/@aws-cdk/aws-route53/test/delete-existing-record-set.integ.snapshot/cdk.out
  packages/@aws-cdk/aws-route53/test/delete-existing-record-set.integ.snapshot/integ.json
  packages/@aws-cdk/aws-route53/test/delete-existing-record-set.integ.snapshot/manifest.json
  packages/@aws-cdk/aws-route53/test/delete-existing-record-set.integ.snapshot/tree.json
  packages/@aws-cdk/aws-route53/test/integ.delete-existing-record-set.ts
  packages/@aws-cdk/aws-route53/test/record-set.test.ts
  packages/@aws-cdk/core/lib/custom-resource-provider/custom-resource-provider.ts
Labels: p2

#20755 fix(route53): improve fromHostedZoneId error message
  packages/@aws-cdk/aws-route53/lib/hosted-zone.ts
  packages/@aws-cdk/aws-route53/test/hosted-zone.test.ts
Labels: p1, effort/small, contribution/core

#20742 fix(core): Durations in the expected unit are not tested for integer-ness
  packages/@aws-cdk/aws-cloudfront-origins/test/http-origin.test.ts
  packages/@aws-cdk/aws-cloudfront/test/origin.test.ts
  packages/@aws-cdk/aws-cloudfront/test/web-distribution.test.ts
  packages/@aws-cdk/aws-events/lib/rule.ts
  packages/@aws-cdk/aws-events/lib/schedule.ts
  packages/@aws-cdk/aws-events/test/schedule.test.ts
  packages/@aws-cdk/core/lib/duration.ts
  packages/@aws-cdk/core/test/duration.test.ts
Labels: p2, feature-request, effort/small

#20583 feat(servicediscovery): add hostedzoneid as attribute to namespace
  packages/@aws-cdk/aws-servicediscovery/lib/private-dns-namespace.ts
  packages/@aws-cdk/aws-servicediscovery/lib/public-dns-namespace.ts
  packages/@aws-cdk/aws-servicediscovery/test/namespace.test.ts
Labels: p2, effort/small, contribution/core, pr-linter/exempt-readme, pr-linter/exempt-integ-test

#20748 fix(events-targets): cloudwatch logs requires specific input template
  packages/@aws-cdk/aws-events-targets/README.md
  packages/@aws-cdk/aws-events-targets/lib/log-group.ts
  packages/@aws-cdk/aws-events-targets/package.json
  packages/@aws-cdk/aws-events-targets/test/logs/integ.log-group.ts
  packages/@aws-cdk/aws-events-targets/test/logs/log-group.integ.snapshot/LogGroupDefaultTestDeployAssert353EE07A.template.json
  packages/@aws-cdk/aws-events-targets/test/logs/log-group.integ.snapshot/asset.41fc8f2dc7c01b34dda9916c7f763e7b7909eb629da9ffe879cb786114aae736.bundle/index.js
  packages/@aws-cdk/aws-events-targets/test/logs/log-group.integ.snapshot/asset.9d784cf317cead201dfe56ed0404d6d23eba6d499ca7354138230c2267f2fe90/index.js
  packages/@aws-cdk/aws-events-targets/test/logs/log-group.integ.snapshot/asset.c1bc48e68a705504356d7b5178aa4617261dbfcf12b70eb9b10fe1fb207ff560/index.js
  packages/@aws-cdk/aws-events-targets/test/logs/log-group.integ.snapshot/integ.json
  packages/@aws-cdk/aws-events-targets/test/logs/log-group.integ.snapshot/log-group-events.assets.json
  packages/@aws-cdk/aws-events-targets/test/logs/log-group.integ.snapshot/log-group-events.template.json
  packages/@aws-cdk/aws-events-targets/test/logs/log-group.integ.snapshot/manifest.json
  packages/@aws-cdk/aws-events-targets/test/logs/log-group.integ.snapshot/tree.json
  packages/@aws-cdk/aws-events-targets/test/logs/log-group.test.ts
Labels: bug, p1, effort/small, contribution/core

#20543 feat(aws-eks): allow the use of graviton3 processors
  packages/@aws-cdk/aws-eks/README.md
  packages/@aws-cdk/aws-eks/lib/cluster.ts
  packages/@aws-cdk/aws-eks/lib/instance-types.ts
  packages/@aws-cdk/aws-eks/test/cluster.test.ts
  packages/@aws-cdk/aws-eks/test/eks-cluster.integ.snapshot/aws-cdk-eks-cluster-test.template.json
  packages/@aws-cdk/aws-eks/test/integ.eks-cluster.ts
Labels: p2

#20791 Update yarn-upgrade.yml
  .github/workflows/yarn-upgrade.yml
Labels: p2, contribution/core

#17065 feat(apigateway): Add LambdaIntegrationOptions to LambdaRestApi
  packages/@aws-cdk/aws-apigateway/README.md
  packages/@aws-cdk/aws-apigateway/lib/lambda-api.ts
  packages/@aws-cdk/aws-apigateway/rosetta/default.ts-fixture
  packages/@aws-cdk/aws-apigateway/test/integ.lambda-api-nonproxy.ts
  packages/@aws-cdk/aws-apigateway/test/integ.lambda-api.ts
  packages/@aws-cdk/aws-apigateway/test/lambda-api-nonproxy.integ.snapshot/LambdaApiIntegrationOptionsNonProxyIntegrationStack.template.json
  packages/@aws-cdk/aws-apigateway/test/lambda-api-nonproxy.integ.snapshot/cdk.out
  packages/@aws-cdk/aws-apigateway/test/lambda-api-nonproxy.integ.snapshot/integ.json
  packages/@aws-cdk/aws-apigateway/test/lambda-api-nonproxy.integ.snapshot/manifest.json
  packages/@aws-cdk/aws-apigateway/test/lambda-api-nonproxy.integ.snapshot/tree.json
  packages/@aws-cdk/aws-apigateway/test/lambda-api.integ.snapshot/LambdaApiIntegrationOptionsStack.template.json
  packages/@aws-cdk/aws-apigateway/test/lambda-api.integ.snapshot/cdk.out
  packages/@aws-cdk/aws-apigateway/test/lambda-api.integ.snapshot/integ.json
  packages/@aws-cdk/aws-apigateway/test/lambda-api.integ.snapshot/manifest.json
  packages/@aws-cdk/aws-apigateway/test/lambda-api.integ.snapshot/tree.json
  packages/@aws-cdk/aws-apigateway/test/lambda-api.test.ts
Labels: p2

#20842 chore(merge-back): 2.29.0
  CHANGELOG.v2.alpha.md
  CHANGELOG.v2.md
  version.v2.json
Labels: p2, pr/no-squash, auto-approve

#20843 chore(merge-back): 1.161.0
  CHANGELOG.md
  version.v1.json
Labels: p2, pr/no-squash, auto-approve

#20861 fix(pipelines): 'ConfirmPermissionsBroadening' uses wrong node version
  packages/@aws-cdk/pipelines/lib/private/application-security-check.ts
  packages/@aws-cdk/pipelines/test/compliance/security-check.test.ts
  packages/@aws-cdk/pipelines/test/pipeline-security.integ.snapshot/PipelineSecurityStack.assets.json
  packages/@aws-cdk/pipelines/test/pipeline-security.integ.snapshot/PipelineSecurityStack.template.json
  packages/@aws-cdk/pipelines/test/pipeline-security.integ.snapshot/manifest.json
  packages/@aws-cdk/pipelines/test/pipeline-security.integ.snapshot/tree.json
Labels: p2, contribution/core

#20864 chore(release): v2.29.1
  CHANGELOG.v2.alpha.md
  CHANGELOG.v2.md
  packages/@aws-cdk/pipelines/lib/private/application-security-check.ts
  packages/@aws-cdk/pipelines/test/compliance/security-check.test.ts
  packages/@aws-cdk/pipelines/test/pipeline-security.integ.snapshot/PipelineSecurityStack.assets.json
  packages/@aws-cdk/pipelines/test/pipeline-security.integ.snapshot/PipelineSecurityStack.template.json
  packages/@aws-cdk/pipelines/test/pipeline-security.integ.snapshot/manifest.json
  packages/@aws-cdk/pipelines/test/pipeline-security.integ.snapshot/tree.json
  version.v2.json
Labels: p2, contribution/core, pr/no-squash

#20867 chore(merge-back): 2.29.1
  CHANGELOG.v2.alpha.md
  CHANGELOG.v2.md
  version.v2.json
Labels: p2, pr/no-squash, auto-approve

#20724 fix(eks): revert shell=True and allow public ecr to work
  packages/@aws-cdk/aws-eks/lib/kubectl-handler/helm/__init__.py
  packages/@aws-cdk/aws-eks/test/eks-helm-asset.integ.snapshot/aws-cdk-eks-helm-test.template.json
  packages/@aws-cdk/aws-eks/test/integ.eks-helm-asset.ts
Labels: p2

#20830 feat(rds): add missing aurora postgres versions
  packages/@aws-cdk/aws-rds/lib/cluster-engine.ts
Labels: p2, pr-linter/exempt-readme, pr-linter/exempt-test, pr-linter/exempt-integ-test

#20766 feat(appmesh): ipv6 support for app mesh
  packages/@aws-cdk/aws-appmesh/README.md
  packages/@aws-cdk/aws-appmesh/lib/mesh.ts
  packages/@aws-cdk/aws-appmesh/lib/service-discovery.ts
  packages/@aws-cdk/aws-appmesh/test/integ.mesh.ts
  packages/@aws-cdk/aws-appmesh/test/mesh.integ.snapshot/cdk.out
  packages/@aws-cdk/aws-appmesh/test/mesh.integ.snapshot/integ.json
  packages/@aws-cdk/aws-appmesh/test/mesh.integ.snapshot/manifest.json
  packages/@aws-cdk/aws-appmesh/test/mesh.integ.snapshot/mesh-stack.assets.json
  packages/@aws-cdk/aws-appmesh/test/mesh.integ.snapshot/mesh-stack.template.json
  packages/@aws-cdk/aws-appmesh/test/mesh.integ.snapshot/tree.json
  packages/@aws-cdk/aws-appmesh/test/mesh.test.ts
  packages/@aws-cdk/aws-appmesh/test/virtual-node.test.ts
Labels: p2, feature-request, effort/small

#20844 chore: advertise construct hub on the readme
  README.md
Labels: p2, contribution/core

#19975 feat(lambda): grant function permissions to an AWS organization
  packages/@aws-cdk/aws-lambda/README.md
  packages/@aws-cdk/aws-lambda/lib/function-base.ts
  packages/@aws-cdk/aws-lambda/lib/permission.ts
  packages/@aws-cdk/aws-lambda/test/function.test.ts
  packages/@aws-cdk/aws-lambda/test/integ.permissions.ts
  packages/@aws-cdk/aws-lambda/test/permissions.integ.snapshot/cdk.out
  packages/@aws-cdk/aws-lambda/test/permissions.integ.snapshot/integ.json
  packages/@aws-cdk/aws-lambda/test/permissions.integ.snapshot/lambda-permissions.assets.json
  packages/@aws-cdk/aws-lambda/test/permissions.integ.snapshot/lambda-permissions.template.json
  packages/@aws-cdk/aws-lambda/test/permissions.integ.snapshot/manifest.json
  packages/@aws-cdk/aws-lambda/test/permissions.integ.snapshot/tree.json
Labels: bug, p1, effort/small, contribution/core

#20799 feat(cognito): make `grant()` available on `IUserPool`
  packages/@aws-cdk/aws-cognito/lib/user-pool.ts
Labels: p2, pr-linter/exempt-readme, pr-linter/exempt-test, pr-linter/exempt-integ-test

#20906 chore(docdb): non-TS examples fail to build due to the wrong enum being used
  packages/@aws-cdk/aws-docdb/README.md
Labels: p2, effort/small

#20900 chore(cfnspec): new libraries do not conform to pkglint
  packages/@aws-cdk/cfnspec/build-tools/create-missing-libraries.ts
Labels: p2, contribution/core

#19320 refactor: update enum types to remove duplicate member values
  packages/@aws-cdk/aws-ec2/lib/instance-types.ts
  packages/@aws-cdk/aws-ec2/lib/machine-image.ts
  packages/@aws-cdk/aws-ec2/lib/port.ts
  packages/@aws-cdk/aws-ec2/lib/util.ts
  packages/@aws-cdk/aws-ec2/lib/vpc.ts
  packages/@aws-cdk/aws-ec2/lib/windows-versions.ts
  packages/@aws-cdk/aws-ec2/test/instance.test.ts
Labels: p2, @aws-cdk/aws-ec2, contribution/core

#20911 feat(iam): PolicyStatements can be frozen
  packages/@aws-cdk/aws-iam/lib/policy-document.ts
  packages/@aws-cdk/aws-iam/lib/policy-statement.ts
  packages/@aws-cdk/aws-iam/test/merge-statements.test.ts
  packages/@aws-cdk/aws-iam/test/policy-statement.test.ts
Labels: p2, contribution/core, pr-linter/exempt-readme, pr-linter/exempt-test, pr-linter/exempt-integ-test

#20569 docs(pipelines): describe how to work around policy size errors
  packages/@aws-cdk/pipelines/README.md
Labels: bug, p2, effort/small, contribution/core
