Repository aws/aws-cdk, pull requests merged in 2022-07, with the labels that each got.

#20954 chore(merge-back): 1.162.0
  CHANGELOG.md
  version.v1.json
Labels: p2, pr/no-squash, auto-approve

#20936 feat(autoscaling): step scaling policy supports estimatedInstanceWarmup property
  packages/@aws-cdk/aws-autoscaling/lib/step-scaling-policy.ts
  packages/@aws-cdk/aws-autoscaling/test/scaling.test.ts
Labels: bug, p1, effort/small, pr-linter/exempt-readme, pr-linter/exempt-integ-test

#20913 feat(s3): Event Bridge notification can be enabled after the bucket is created
  packages/@aws-cdk/aws-s3/lib/bucket.ts
  packages/@aws-cdk/aws-s3/test/bucket.test.ts
Labels: p1, feature-request, contribution/core, pr-linter/exempt-readme, pr-linter/exempt-integ-test

#20772 fix(cloudfront): fromOriginAccessIdentityName is a misnomer
  packages/@aws-cdk/aws-cloudfront-origins/lib/s3-origin.ts
  packages/@aws-cdk/aws-cloudfront/lib/origin-access-identity.ts
  packages/@aws-cdk/aws-cloudfront/lib/web-distribution.ts
  packages/@aws-cdk/aws-cloudfront/test/integ.cloudfront-s3.ts
  packages/@aws-cdk/aws-cloudfront/test/oai.test.ts
Labels: bug, p2, effort/small

#20963 Remove redundancy to improve clarity
  docs/DESIGN_GUIDELINES.md
Labels: p2

#20957 fix(cli): standard log messages are sent to stderr when CI=true
  packages/aws-cdk/README.md
  packages/aws-cdk/lib/api/cloudformation-deployments.ts
  packages/aws-cdk/lib/api/deploy-stack.ts
  packages/aws-cdk/lib/api/util/cloudformation/stack-activity-monitor.ts
  packages/aws-cdk/lib/cdk-toolkit.ts
  packages/aws-cdk/lib/cli.ts
  packages/aws-cdk/lib/logging.ts
  packages/aws-cdk/test/api/deploy-stack.test.ts
  packages/aws-cdk/test/integ/cli/cli.integtest.ts
  packages/aws-cdk/test/integ/helpers/cdk.ts
Labels: bug, p1, effort/large, contribution/core

#20977 chore: a couple more places where `ResponseURL` is logged
  packages/@aws-cdk/core/lib/custom-resource-provider/nodejs-entrypoint.ts
  packages/@aws-cdk/custom-resources/README.md
  packages/@aws-cdk/custom-resources/lib/provider-framework/runtime/framework.ts
  packages/@aws-cdk/pipelines/test/pipeline-security.integ.snapshot/PipelineSecurityStack.assets.json
  packages/@aws-cdk/pipelines/test/pipeline-security.integ.snapshot/PipelineSecurityStack.template.json
  packages/@aws-cdk/pipelines/test/pipeline-security.integ.snapshot/asset.17cb4b37288c269a54418db6e9c7c3763b2d1a82bdc374be4653bd366345eccb/__entrypoint__.js
  packages/@aws-cdk/pipelines/test/pipeline-security.integ.snapshot/asset.17cb4b37288c269a54418db6e9c7c3763b2d1a82bdc374be4653bd366345eccb/index.d.ts
  packages/@aws-cdk/pipelines/test/pipeline-security.integ.snapshot/asset.17cb4b37288c269a54418db6e9c7c3763b2d1a82bdc374be4653bd366345eccb/index.js
  packages/@aws-cdk/pipelines/test/pipeline-security.integ.snapshot/asset.17cb4b37288c269a54418db6e9c7c3763b2d1a82bdc374be4653bd366345eccb/index.ts
  packages/@aws-cdk/pipelines/test/pipeline-security.integ.snapshot/manifest.json
  packages/@aws-cdk/pipelines/test/pipeline-with-assets-single-upload.integ.snapshot/PipelineStack.assets.json
  packages/@aws-cdk/pipelines/test/pipeline-with-assets-single-upload.integ.snapshot/PipelineStack.template.json
  packages/@aws-cdk/pipelines/test/pipeline-with-assets-single-upload.integ.snapshot/asset.17cb4b37288c269a54418db6e9c7c3763b2d1a82bdc374be4653bd366345eccb/__entrypoint__.js
  packages/@aws-cdk/pipelines/test/pipeline-with-assets-single-upload.integ.snapshot/asset.17cb4b37288c269a54418db6e9c7c3763b2d1a82bdc374be4653bd366345eccb/index.d.ts
  packages/@aws-cdk/pipelines/test/pipeline-with-assets-single-upload.integ.snapshot/asset.17cb4b37288c269a54418db6e9c7c3763b2d1a82bdc374be4653bd366345eccb/index.js
  packages/@aws-cdk/pipelines/test/pipeline-with-assets-single-upload.integ.snapshot/asset.17cb4b37288c269a54418db6e9c7c3763b2d1a82bdc374be4653bd366345eccb/index.ts
  packages/@aws-cdk/pipelines/test/pipeline-with-assets-single-upload.integ.snapshot/manifest.json
  packages/@aws-cdk/pipelines/test/pipeline-with-assets-single-upload.integ.snapshot/tree.json
  packages/@aws-cdk/pipelines/test/pipeline-with-assets.integ.snapshot/PipelineStack.assets.json
  packages/@aws-cdk/pipelines/test/pipeline-with-assets.integ.snapshot/PipelineStack.template.json
  packages/@aws-cdk/pipelines/test/pipeline-with-assets.integ.snapshot/asset.17cb4b37288c269a54418db6e9c7c3763b2d1a82bdc374be4653bd366345eccb/__entrypoint__.js
  packages/@aws-cdk/pipelines/test/pipeline-with-assets.integ.snapshot/asset.17cb4b37288c269a54418db6e9c7c3763b2d1a82bdc374be4653bd366345eccb/index.d.ts
  packages/@aws-cdk/pipelines/test/pipeline-with-assets.integ.snapshot/asset.17cb4b37288c269a54418db6e9c7c3763b2d1a82bdc374be4653bd366345eccb/index.js
  packages/@aws-cdk/pipelines/test/pipeline-with-assets.integ.snapshot/asset.17cb4b37288c269a54418db6e9c7c3763b2d1a82bdc374be4653bd366345eccb/index.ts
  packages/@aws-cdk/pipelines/test/pipeline-with-assets.integ.snapshot/manifest.json
  packages/@aws-cdk/pipelines/test/pipeline-with-assets.integ.snapshot/tree.json
  packages/@aws-cdk/pipelines/test/pipeline-with-variables.integ.snapshot/VariablePipelineStack.assets.json
  packages/@aws-cdk/pipelines/test/pipeline-with-variables.integ.snapshot/VariablePipelineStack.template.json
  packages/@aws-cdk/pipelines/test/pipeline-with-variables.integ.snapshot/asset.17cb4b37288c269a54418db6e9c7c3763b2d1a82bdc374be4653bd366345eccb/__entrypoint__.js
  packages/@aws-cdk/pipelines/test/pipeline-with-variables.integ.snapshot/asset.17cb4b37288c269a54418db6e9c7c3763b2d1a82bdc374be4653bd366345eccb/index.d.ts
  packages/@aws-cdk/pipelines/test/pipeline-with-variables.integ.snapshot/asset.17cb4b37288c269a54418db6e9c7c3763b2d1a82bdc374be4653bd366345eccb/index.js
  packages/@aws-cdk/pipelines/test/pipeline-with-variables.integ.snapshot/asset.17cb4b37288c269a54418db6e9c7c3763b2d1a82bdc374be4653bd366345eccb/index.ts
  packages/@aws-cdk/pipelines/test/pipeline-with-variables.integ.snapshot/manifest.json
  packages/@aws-cdk/pipelines/test/pipeline.integ.snapshot/PipelineStack.assets.json
  packages/@aws-cdk/pipelines/test/pipeline.integ.snapshot/PipelineStack.template.json
  packages/@aws-cdk/pipelines/test/pipeline.integ.snapshot/asset.17cb4b37288c269a54418db6e9c7c3763b2d1a82bdc374be4653bd366345eccb/__entrypoint__.js
  packages/@aws-cdk/pipelines/test/pipeline.integ.snapshot/asset.17cb4b37288c269a54418db6e9c7c3763b2d1a82bdc374be4653bd366345eccb/index.d.ts
  packages/@aws-cdk/pipelines/test/pipeline.integ.snapshot/asset.17cb4b37288c269a54418db6e9c7c3763b2d1a82bdc374be4653bd366345eccb/index.js
  packages/@aws-cdk/pipelines/test/pipeline.integ.snapshot/asset.17cb4b37288c269a54418db6e9c7c3763b2d1a82bdc374be4653bd366345eccb/index.ts
  packages/@aws-cdk/pipelines/test/pipeline.integ.snapshot/manifest.json
  packages/@aws-cdk/pipelines/test/pipeline.integ.snapshot/tree.json
  packages/aws-cdk-lib/package.json
Labels: p2, contribution/core

#20910 docs: clarify commit prefixes
  CONTRIBUTING.md
Labels: p2, contribution/core

#20986 chore: make `does-not-exist.json` actually not exist
  packages/aws-cdk/does-not-exist.json
  packages/aws-cdk/test/notices.test.ts
Labels: p2, contribution/core

#20982 refactor: remove more duplicate enum values
  packages/@aws-cdk/aws-secretsmanager/lib/secret.ts
  packages/@aws-cdk/aws-secretsmanager/test/secret.test.ts
  packages/@aws-cdk/core/lib/custom-resource-provider/custom-resource-provider.ts
Labels: p2, contribution/core

#20989 docs: explain procedure for rotating a SecretsManager Secret
  packages/@aws-cdk/aws-codepipeline-actions/lib/github/source-action.ts
  packages/@aws-cdk/core/README.md
  packages/@aws-cdk/core/lib/secret-value.ts
  packages/@aws-cdk/pipelines/lib/codepipeline/codepipeline-source.ts
  packages/aws-cdk-lib/README.md
Labels: p2, contribution/core

#20999 docs(pipelines): explain lookup-role assumption error
  packages/@aws-cdk/pipelines/README.md
Labels: p2, contribution/core

#20964 docs: fix wrong annotation used in example
  docs/DESIGN_GUIDELINES.md
Labels: p2

#20871 feat(batch): add secrets props to job definition
  packages/@aws-cdk/aws-batch/README.md
  packages/@aws-cdk/aws-batch/lib/job-definition.ts
  packages/@aws-cdk/aws-batch/rosetta/default.ts-fixture
  packages/@aws-cdk/aws-batch/test/batch.integ.snapshot/batch-stack.assets.json
  packages/@aws-cdk/aws-batch/test/batch.integ.snapshot/batch-stack.template.json
  packages/@aws-cdk/aws-batch/test/batch.integ.snapshot/cdk.out
  packages/@aws-cdk/aws-batch/test/batch.integ.snapshot/integ.json
  packages/@aws-cdk/aws-batch/test/batch.integ.snapshot/manifest.json
  packages/@aws-cdk/aws-batch/test/batch.integ.snapshot/tree.json
  packages/@aws-cdk/aws-batch/test/integ.batch.ts
  packages/@aws-cdk/aws-batch/test/job-definition.test.ts
Labels: p1, feature-request, effort/medium

#20915 docs(opensearch): add example for token based import
  packages/@aws-cdk/aws-opensearchservice/README.md
Labels: p2

#21000 chore: fix ci=true integ tests
  packages/aws-cdk-lib/package.json
  packages/aws-cdk/CONTRIBUTING.md
  packages/aws-cdk/lib/logging.ts
  packages/aws-cdk/test/integ/cli/cli.integtest.ts
Labels: p2, contribution/core

#20682 feat(dynamodb): imported tables always grant permissions for indexes
  packages/@aws-cdk/aws-dynamodb/README.md
  packages/@aws-cdk/aws-dynamodb/lib/table.ts
  packages/@aws-cdk/aws-dynamodb/test/dynamodb.test.ts
Labels: p1, feature-request, effort/small, pr-linter/exempt-integ-test

#20826 fix(eks): latest `AlbController` version isn't compatible with the chart version
  packages/@aws-cdk/aws-eks/README.md
  packages/@aws-cdk/aws-eks/lib/alb-controller.ts
  packages/@aws-cdk/aws-eks/test/alb-controller.integ.snapshot/aws-cdk-eks-cluster-alb-controller-test.template.json
  packages/@aws-cdk/aws-eks/test/eks-inference.integ.snapshot/aws-cdk-eks-cluster-inference-test.template.json
Labels: bug, p1, effort/small

#20972 feat(ec2): add additional instance type classes
  packages/@aws-cdk/aws-ec2/lib/instance-types.ts
Labels: p2, pr-linter/exempt-readme, pr-linter/exempt-test, pr-linter/exempt-integ-test

#20821 feat(elbv2) expose connection_termination attribute on network target group
  packages/@aws-cdk/aws-elasticloadbalancingv2/lib/nlb/network-target-group.ts
  packages/@aws-cdk/aws-elasticloadbalancingv2/package.json
  packages/@aws-cdk/aws-elasticloadbalancingv2/test/connection-termination.nlb.integ.snapshot/aws-cdk-elbv2-integ.template.json
  packages/@aws-cdk/aws-elasticloadbalancingv2/test/connection-termination.nlb.integ.snapshot/cdk.out
  packages/@aws-cdk/aws-elasticloadbalancingv2/test/connection-termination.nlb.integ.snapshot/integ.json
  packages/@aws-cdk/aws-elasticloadbalancingv2/test/connection-termination.nlb.integ.snapshot/manifest.json
  packages/@aws-cdk/aws-elasticloadbalancingv2/test/connection-termination.nlb.integ.snapshot/targetGroupTestDefaultTestDeployAssert29FB5AEF.template.json
  packages/@aws-cdk/aws-elasticloadbalancingv2/test/connection-termination.nlb.integ.snapshot/tree.json
  packages/@aws-cdk/aws-elasticloadbalancingv2/test/integ.connection-termination.nlb.ts
  packages/@aws-cdk/aws-elasticloadbalancingv2/test/nlb/target-group.test.ts
Labels: p1, feature-request, effort/small, pr-linter/exempt-readme

#20965 feat(ec2): expose interface endpoint service shortname
  packages/@aws-cdk/aws-ec2/lib/vpc-endpoint.ts
  packages/@aws-cdk/aws-ec2/test/vpc-endpoint.test.ts
Labels: p2, pr-linter/exempt-readme, pr-linter/exempt-integ-test

#20992 feat(codebuild): add support for new codebuild images
  packages/@aws-cdk/aws-codebuild/lib/project.ts
  packages/@aws-cdk/aws-codebuild/test/project.test.ts
Labels: p2, feature-request, pr-linter/exempt-readme, pr-linter/exempt-integ-test

#21024 chore(merge-back): 1.163.0
  CHANGELOG.md
  version.v1.json
Labels: p2, pr/no-squash, auto-approve

#20919 chore(eks): update cdk8s integration docs to use cdk8s v2
  packages/@aws-cdk/aws-eks/README.md
  packages/@aws-cdk/aws-eks/package.json
  packages/@aws-cdk/aws-eks/test/alb-controller.integ.snapshot/aws-cdk-eks-cluster-alb-controller-test.assets.json
  packages/@aws-cdk/aws-eks/test/alb-controller.integ.snapshot/aws-cdk-eks-cluster-alb-controller-test.template.json
  packages/@aws-cdk/aws-eks/test/alb-controller.integ.snapshot/awscdkeksclusteralbcontrollertestawscdkawseksClusterResourceProvider5DBBAFBB.nested.template.json
  packages/@aws-cdk/aws-eks/test/alb-controller.integ.snapshot/awscdkeksclusteralbcontrollertestawscdkawseksKubectlProviderA1AC28D1.nested.template.json
  packages/@aws-cdk/aws-eks/test/alb-controller.integ.snapshot/integ.json
  packages/@aws-cdk/aws-eks/test/alb-controller.integ.snapshot/manifest.json
  packages/@aws-cdk/aws-eks/test/alb-controller.integ.snapshot/tree.json
  yarn.lock
Labels: p2, contribution/core

#21023 chore(merge-back): 2.31.0
  CHANGELOG.v2.alpha.md
  CHANGELOG.v2.md
  version.v2.json
Labels: p2, pr/no-squash, auto-approve

#20819 chore(sns): addSubscription does not return the subscription
  packages/@aws-cdk/aws-sns/lib/topic-base.ts
Labels: p2

#21030 chore: remove cfnspec patch for Cognito::UserPool.UsernameConfiguration
  packages/@aws-cdk/cfnspec/spec-source/specification/000_cfn/500_Cognito_UserPool_UsernameConfiguration_patch.json
Labels: p2, contribution/core

#21031 chore: add mrgrain to mergify as core contributor
  .mergify.yml
Labels: p2

#21033 doc(cli): point out `cdk watch` limitations
  packages/aws-cdk/README.md
Labels: p2, contribution/core

#20769 feat(integ-tests): expose adding IAM policies to the assertion provider
  packages/@aws-cdk/integ-tests/README.md
  packages/@aws-cdk/integ-tests/lib/assertions/providers/provider.ts
  packages/@aws-cdk/integ-tests/lib/assertions/sdk.ts
  packages/@aws-cdk/integ-tests/rosetta/default.ts-fixture
  packages/@aws-cdk/integ-tests/test/assertions/sdk.test.ts
Labels: p2, contribution/core

#21018 fix(cli): CLI errors when run as a non-existent user
  packages/aws-cdk/lib/util/directories.ts
Labels: bug, p1, effort/small, contribution/core, pr-linter/exempt-test

#21039 fix(logs): `ResourcePolicy` does not have a `defaultChild`
  packages/@aws-cdk/aws-logs/lib/policy.ts
  packages/@aws-cdk/aws-logs/test/policy.test.ts
Labels: p2, contribution/core

#21010 fix(pipelines): cannot publish assets to more than 35 environments
  packages/@aws-cdk/aws-iam/lib/policy-statement.ts
  packages/@aws-cdk/aws-iam/test/policy-document.test.ts
  packages/@aws-cdk/aws-iam/test/policy-statement.test.ts
  packages/@aws-cdk/pipelines/lib/codepipeline/codepipeline.ts
  packages/@aws-cdk/pipelines/lib/legacy/pipeline.ts
  packages/@aws-cdk/pipelines/lib/private/asset-singleton-role.ts
  packages/@aws-cdk/pipelines/lib/private/cached-fnsub.ts
  packages/@aws-cdk/pipelines/test/compliance/assets.test.ts
Labels: p2, contribution/core

#21044 chore: add manual dispatch option to issue reprioritization manager
  .github/workflows/issue-reprioritization.yml
Labels: p2, contribution/core

#21045 fix: flowlog has no default child
  packages/@aws-cdk/aws-ec2/lib/vpc-flow-logs.ts
  packages/@aws-cdk/aws-ec2/test/vpc-flow-logs.test.ts
Labels: p2, contribution/core

#20930 feat(core): add a description parameter for the NestedStackProps
  packages/@aws-cdk/aws-cloudformation/test/integ.nested-stack.ts
  packages/@aws-cdk/core/README.md
  packages/@aws-cdk/core/lib/nested-stack.ts
  packages/@aws-cdk/core/test/nested-stack.test.ts
  packages/aws-cdk-lib/README.md
Labels: p1, feature-request, effort/small

#19404 docs(ecs-patterns): make property descriptions more clear
  packages/@aws-cdk/aws-ecs-patterns/lib/base/application-load-balanced-service-base.ts
Labels: p2

#21047 docs(ecs): add an example for AsgCapacityProvider with EC2 LaunchTemplate
  packages/@aws-cdk/aws-ecs/README.md
Labels: bug, p2, effort/small

#21007 fix(route53): publichostedzone import returns IHostedZone instead of IPublicHostedZone
  packages/@aws-cdk/aws-elasticloadbalancingv2/test/nlb/load-balancer.test.ts
  packages/@aws-cdk/aws-route53/lib/hosted-zone.ts
Labels: bug, p1, effort/small, contribution/core

#21050 fix(cli): format of tags in cdk.json is not validated
  packages/aws-cdk/lib/cli.ts
  packages/aws-cdk/lib/util/tags.ts
  packages/aws-cdk/test/util/tags.test.ts
Labels: bug, p1, effort/small

#20521 fix(sns-subscriptions): restrict encryption of queue to only the respective sns topic (under feature flag)
  packages/@aws-cdk/aws-sns-subscriptions/lib/sqs.ts
  packages/@aws-cdk/aws-sns-subscriptions/package.json
  packages/@aws-cdk/aws-sns-subscriptions/test/integ.sns-sqs.lit.ts
  packages/@aws-cdk/aws-sns-subscriptions/test/sns-sqs.lit.integ.snapshot/aws-cdk-sns-sqs.template.json
  packages/@aws-cdk/aws-sns-subscriptions/test/subs.test.ts
  packages/@aws-cdk/cx-api/README.md
  packages/@aws-cdk/cx-api/lib/features.ts
Labels: p2

#21065 fix(custom-resources): Custom resource provider framework not passing `ResponseURL` to user function
  packages/@aws-cdk/custom-resources/lib/provider-framework/runtime/framework.ts
Labels: bug, p0, effort/small, contribution/core, pr-linter/exempt-test, pr-linter/exempt-integ-test

#21067 chore(release): 2.31.1
  CHANGELOG.v2.alpha.md
  CHANGELOG.v2.md
  packages/@aws-cdk/custom-resources/lib/provider-framework/runtime/framework.ts
  version.v2.json
Labels: p2, contribution/core, pr/no-squash

#21068 chore(release): 1.163.1
  CHANGELOG.md
  packages/@aws-cdk/custom-resources/lib/provider-framework/runtime/framework.ts
  version.v1.json
Labels: p2, contribution/core, pr/no-squash

#21069 chore(merge-back): 2.31.1
  CHANGELOG.v2.alpha.md
  CHANGELOG.v2.md
  version.v2.json
Labels: p2, pr/no-squash, auto-approve

#21070 chore(merge-back): 1.163.1
  CHANGELOG.md
  packages/@aws-cdk/custom-resources/lib/provider-framework/runtime/framework.ts
  version.v1.json
Labels: p2, pr/no-squash, auto-approve

#21079 feat(neptune): add engine version 1.1.1.0
  packages/@aws-cdk/aws-neptune/lib/cluster.ts
  packages/@aws-cdk/aws-neptune/test/cluster.test.ts
Labels: p2, feature-request, effort/small, pr-linter/exempt-readme, @aws-cdk/aws-neptune, pr-linter/exempt-integ-test

#21092 fix(cli): revert "fix(cli): format of tags in cdk.json is not validated"
  packages/aws-cdk/lib/cli.ts
  packages/aws-cdk/lib/util/tags.ts
  packages/aws-cdk/test/util/tags.test.ts
Labels: p2, contribution/core

#21081 feat(glue): enable partition filtering on tables
  packages/@aws-cdk/aws-glue/README.md
  packages/@aws-cdk/aws-glue/lib/table.ts
  packages/@aws-cdk/aws-glue/test/integ.table.ts
  packages/@aws-cdk/aws-glue/test/table.integ.snapshot/aws-cdk-glue.assets.json
  packages/@aws-cdk/aws-glue/test/table.integ.snapshot/aws-cdk-glue.template.json
  packages/@aws-cdk/aws-glue/test/table.integ.snapshot/cdk.out
  packages/@aws-cdk/aws-glue/test/table.integ.snapshot/integ.json
  packages/@aws-cdk/aws-glue/test/table.integ.snapshot/manifest.json
  packages/@aws-cdk/aws-glue/test/table.integ.snapshot/tree.json
  packages/@aws-cdk/aws-glue/test/table.test.ts
Labels: p2, feature-request, effort/small

#21098 chore: re-update F# template for new addSubscription signature
  packages/aws-cdk/lib/init-templates/sample-app/fsharp/src/%name.PascalCased%/%name.PascalCased%Stack.template.fs
Labels: p2, contribution/core

#21084 feat(redshift): adds classic or elastic resize type option
  packages/@aws-cdk/aws-redshift/lib/cluster.ts
  packages/@aws-cdk/aws-redshift/test/cluster.test.ts
Labels: p2, feature-request, effort/small, pr-linter/exempt-readme, pr-linter/exempt-integ-test

#21106 typo:Lambda Role Principal was a different service
  packages/@aws-cdk/aws-lambda/README.md
Labels: p2

#21094 chore(mergify): update current members of contribution/core
  .mergify.yml
Labels: p2, contribution/core

#21105 feat(backup): vault lock
  packages/@aws-cdk/aws-backup/README.md
  packages/@aws-cdk/aws-backup/lib/vault.ts
  packages/@aws-cdk/aws-backup/test/backup.integ.snapshot/cdk-backup.template.json
  packages/@aws-cdk/aws-backup/test/backup.integ.snapshot/cdk.out
  packages/@aws-cdk/aws-backup/test/backup.integ.snapshot/integ.json
  packages/@aws-cdk/aws-backup/test/backup.integ.snapshot/manifest.json
  packages/@aws-cdk/aws-backup/test/backup.integ.snapshot/tree.json
  packages/@aws-cdk/aws-backup/test/integ.backup.ts
  packages/@aws-cdk/aws-backup/test/vault.test.ts
Labels: p2

#21077 feat(stepfunctions-tasks): support parameters in StepFunctionsInvokeActivity
  packages/@aws-cdk/aws-stepfunctions-tasks/README.md
  packages/@aws-cdk/aws-stepfunctions-tasks/lib/stepfunctions/invoke-activity.ts
  packages/@aws-cdk/aws-stepfunctions-tasks/test/stepfunctions/integ.invoke-activity.ts
  packages/@aws-cdk/aws-stepfunctions-tasks/test/stepfunctions/invoke-activity.integ.snapshot/aws-stepfunctions-integ.assets.json
  packages/@aws-cdk/aws-stepfunctions-tasks/test/stepfunctions/invoke-activity.integ.snapshot/aws-stepfunctions-integ.template.json
  packages/@aws-cdk/aws-stepfunctions-tasks/test/stepfunctions/invoke-activity.integ.snapshot/cdk.out
  packages/@aws-cdk/aws-stepfunctions-tasks/test/stepfunctions/invoke-activity.integ.snapshot/integ.json
  packages/@aws-cdk/aws-stepfunctions-tasks/test/stepfunctions/invoke-activity.integ.snapshot/manifest.json
  packages/@aws-cdk/aws-stepfunctions-tasks/test/stepfunctions/invoke-activity.integ.snapshot/tree.json
Labels: p2, feature-request, effort/small

#21109 Revert "fix(custom-resources): Custom resource provider framework not passing `ResponseURL` to user function"
  packages/@aws-cdk/custom-resources/lib/provider-framework/runtime/framework.ts
Labels: p2, contribution/core

#20054 feat(rds): support rolling instance updates to reduce downtime
  packages/@aws-cdk/aws-rds/README.md
  packages/@aws-cdk/aws-rds/lib/cluster.ts
  packages/@aws-cdk/aws-rds/package.json
  packages/@aws-cdk/aws-rds/test/cluster.test.ts
  packages/@aws-cdk/aws-rds/test/integ.rolling-instance-updates.ts
  packages/@aws-cdk/aws-rds/test/rolling-instance-updates.integ.snapshot/BulkUpdate.template.json
  packages/@aws-cdk/aws-rds/test/rolling-instance-updates.integ.snapshot/InstanceUpdateBehaviorTestsDefaultTestDeployAssert287956FD.template.json
  packages/@aws-cdk/aws-rds/test/rolling-instance-updates.integ.snapshot/RollingUpdate.template.json
  packages/@aws-cdk/aws-rds/test/rolling-instance-updates.integ.snapshot/cdk.out
  packages/@aws-cdk/aws-rds/test/rolling-instance-updates.integ.snapshot/integ.json
  packages/@aws-cdk/aws-rds/test/rolling-instance-updates.integ.snapshot/manifest.json
  packages/@aws-cdk/aws-rds/test/rolling-instance-updates.integ.snapshot/tree.json
Labels: p2

#21117 fix(custom-resources): Custom resource provider framework not passing `ResponseURL` to user function
  packages/@aws-cdk/custom-resources/lib/provider-framework/runtime/framework.ts
  packages/@aws-cdk/custom-resources/test/provider-framework/runtime.test.ts
Labels: bug, p0, contribution/core, @aws-cdk/custom-resources

#20997 feat(ses): DedicatedIpPool, ConfigurationSet and EmailIdentity
  packages/@aws-cdk/aws-ses/README.md
  packages/@aws-cdk/aws-ses/lib/configuration-set.ts
  packages/@aws-cdk/aws-ses/lib/dedicated-ip-pool.ts
  packages/@aws-cdk/aws-ses/lib/email-identity.ts
  packages/@aws-cdk/aws-ses/lib/index.ts
  packages/@aws-cdk/aws-ses/lib/private/utils.ts
  packages/@aws-cdk/aws-ses/package.json
  packages/@aws-cdk/aws-ses/rosetta/default.ts-fixture
  packages/@aws-cdk/aws-ses/test/configuration-set.integ.snapshot/ConfigurationSetIntegDefaultTestDeployAssert9B6AD46A.template.json
  packages/@aws-cdk/aws-ses/test/configuration-set.integ.snapshot/cdk-ses-configuration-set-integ.template.json
  packages/@aws-cdk/aws-ses/test/configuration-set.integ.snapshot/cdk.out
  packages/@aws-cdk/aws-ses/test/configuration-set.integ.snapshot/integ.json
  packages/@aws-cdk/aws-ses/test/configuration-set.integ.snapshot/manifest.json
  packages/@aws-cdk/aws-ses/test/configuration-set.integ.snapshot/tree.json
  packages/@aws-cdk/aws-ses/test/configuration-set.test.ts
  packages/@aws-cdk/aws-ses/test/dedicated-ip-pool.test.ts
  packages/@aws-cdk/aws-ses/test/email-identity.integ.snapshot/EmailIdentityIntegDefaultTestDeployAssert3F909307.template.json
  packages/@aws-cdk/aws-ses/test/email-identity.integ.snapshot/cdk-ses-email-identity-integ.template.json
  packages/@aws-cdk/aws-ses/test/email-identity.integ.snapshot/cdk.out
  packages/@aws-cdk/aws-ses/test/email-identity.integ.snapshot/integ.json
  packages/@aws-cdk/aws-ses/test/email-identity.integ.snapshot/manifest.json
  packages/@aws-cdk/aws-ses/test/email-identity.integ.snapshot/tree.json
  packages/@aws-cdk/aws-ses/test/email-identity.test.ts
  packages/@aws-cdk/aws-ses/test/integ.configuration-set.ts
  packages/@aws-cdk/aws-ses/test/integ.email-identity.ts
  packages/@aws-cdk/custom-resources/README.md
Labels: p2

#20995 feat(appsync): set max batch size when using batch invoke
  packages/@aws-cdk/aws-appsync/lib/resolver.ts
  packages/@aws-cdk/aws-appsync/test/appsync-mapping-template.test.ts
  packages/@aws-cdk/aws-appsync/test/appsync.lambda.graphql
  packages/@aws-cdk/aws-appsync/test/integ.appsync-lambda.ts
  packages/@aws-cdk/aws-appsync/test/verify.integ.appsync-lambda.sh
  packages/@aws-cdk/aws-appsync/test/verify/lambda-tutorial/lambda-tutorial.js
Labels: p1, feature-request, effort/small, pr-linter/exempt-readme

#19950 fix(core): use node.path in skip bundling check for consistency with cdk deploy CLI
  packages/@aws-cdk/core/lib/stack.ts
  packages/@aws-cdk/core/test/staging.test.ts
Labels: bug, p1, effort/small

#21129 chore(release): 1.163.2
  CHANGELOG.md
  packages/@aws-cdk/custom-resources/lib/provider-framework/runtime/framework.ts
  packages/@aws-cdk/custom-resources/test/provider-framework/runtime.test.ts
  version.v1.json
Labels: p2, contribution/core, pr/no-squash

#21128 chore(release): 2.31.2
  CHANGELOG.v2.alpha.md
  CHANGELOG.v2.md
  packages/@aws-cdk/custom-resources/lib/provider-framework/runtime/framework.ts
  packages/@aws-cdk/custom-resources/test/provider-framework/runtime.test.ts
  version.v2.json
Labels: p2, contribution/core, pr/no-squash

#21127 docs(aws-ssm): StringParameter example is wrong
  packages/@aws-cdk/aws-ssm/lib/parameter.ts
Labels: p2, effort/small

#21130 chore: remove note of go being in dev preview
  packages/aws-cdk/lib/init-templates/app/go/README.md
  packages/aws-cdk/lib/init-templates/sample-app/go/README.md
Labels: p2, contribution/core

#19890 feat(cli): --force flag and glob-style key matches for context --reset
  packages/aws-cdk/lib/cli.ts
  packages/aws-cdk/lib/commands/context.ts
  packages/aws-cdk/test/commands/context-command.test.ts
Labels: p2, pr-linter/exempt-readme, pr-linter/exempt-integ-test

#20423 fix(pipelines): reuseCrossRegionSupportStacks=true does not fail when existing pipeline is used
  packages/@aws-cdk/pipelines/lib/codepipeline/codepipeline.ts
  packages/@aws-cdk/pipelines/test/codepipeline/codepipeline.test.ts
Labels: bug, p2, effort/small

#20173 fix(appsync): domain name api association fails when domain name creation is in the same stack
  packages/@aws-cdk/aws-appsync/lib/graphqlapi.ts
  packages/@aws-cdk/aws-appsync/test/appsync-domain.test.ts
Labels: bug, p2

#21132 chore(merge-back): 1.163.2
  CHANGELOG.md
  version.v1.json
Labels: p2, pr/no-squash, auto-approve

#20169 fix(apigateway): serialization exception with step functions integration
  packages/@aws-cdk/aws-apigateway/lib/integrations/stepfunctions.vtl
  packages/@aws-cdk/aws-apigateway/test/integrations/stepfunctions.test.ts
  packages/@aws-cdk/aws-apigateway/test/stepfunctions-api.integ.snapshot/StepFunctionsRestApiDeploymentStack.template.json
  packages/@aws-cdk/aws-apigateway/test/stepfunctions-api.integ.snapshot/cdk.out
  packages/@aws-cdk/aws-apigateway/test/stepfunctions-api.integ.snapshot/integ.json
  packages/@aws-cdk/aws-apigateway/test/stepfunctions-api.integ.snapshot/manifest.json
  packages/@aws-cdk/aws-apigateway/test/stepfunctions-api.integ.snapshot/tree.json
  packages/@aws-cdk/aws-apigateway/test/stepfunctions-api.test.ts
Labels: p2

#21060 docs(logs): clarify encryption default for log groups
  packages/@aws-cdk/aws-logs/lib/log-group.ts
Labels: p2

#21124 fix(core): entrypoint option never used
  packages/@aws-cdk/core/lib/asset-staging.ts
  packages/@aws-cdk/core/test/staging.test.ts
Labels: p2

#21111 fix(events-targets): api destination target ignores pathParameterValues and queryStringParameters
  packages/@aws-cdk/aws-events-targets/lib/api-destination.ts
  packages/@aws-cdk/aws-events-targets/test/api-destination/api-destination.test.ts
Labels: bug, p2

#21133 chore(merge-back): 2.31.2
  CHANGELOG.v2.alpha.md
  CHANGELOG.v2.md
  version.v2.json
Labels: p2, pr/no-squash, auto-approve

#17971 feat(backup): support RDS database cluster and serverless cluster
  packages/@aws-cdk/aws-backup/README.md
  packages/@aws-cdk/aws-backup/lib/backupable-resources-collector.ts
  packages/@aws-cdk/aws-backup/lib/resource.ts
  packages/@aws-cdk/aws-backup/rosetta/default.ts-fixture
  packages/@aws-cdk/aws-backup/test/selection.test.ts
Labels: p2, feature-request, effort/small, pr-linter/exempt-integ-test

#19449 docs(cli): bundling implications on contributions
  packages/aws-cdk/CONTRIBUTING.md
Labels: p2, contribution/core

#21074 docs(contributing): add additional step in the feature flags section
  CONTRIBUTING.md
Labels: p2

#21110 docs(s3): add example to s3 bucket documentation
  packages/@aws-cdk/aws-s3/lib/bucket.ts
Labels: p2, effort/small

#21071 fix(core): updatedProperties function name is misspelled
  packages/@aws-cdk/core/lib/cfn-resource.ts
  packages/@aws-cdk/core/test/resource.test.ts
Labels: p2

#19908 feat(cli): allow diffing against a processed template
  packages/@aws-cdk/cloudformation-include/README.md
  packages/@aws-cdk/cloudformation-include/doc-images/processed-template.png
  packages/@aws-cdk/cloudformation-include/doc-images/unprocessed-template.png
  packages/aws-cdk/lib/api/cloudformation-deployments.ts
  packages/aws-cdk/lib/api/nested-stack-helpers.ts
  packages/aws-cdk/lib/api/util/cloudformation.ts
  packages/aws-cdk/lib/cdk-toolkit.ts
  packages/aws-cdk/lib/cli.ts
  packages/aws-cdk/test/util/cloudformation.test.ts
Labels: p2, pr-linter/exempt-integ-test

#20874 fix(aws-s3-assets): support asset url with two extension name like tar.gz
  packages/@aws-cdk/assets/test/staging.test.ts
  packages/@aws-cdk/core/lib/asset-staging.ts
  packages/@aws-cdk/core/test/archive/DockerFile
  packages/@aws-cdk/core/test/archive/artifact.da.vinci.monalisa.tar.gz
  packages/@aws-cdk/core/test/archive/artifact.tar
  packages/@aws-cdk/core/test/archive/artifact.tar.gz
  packages/@aws-cdk/core/test/archive/artifact.tgz
  packages/@aws-cdk/core/test/archive/artifact.zip.txt
  packages/@aws-cdk/core/test/staging.test.ts
Labels: bug, p1, effort/small

#21144 chore(core): point deprecated updatedProperites at updatedProperties
  packages/@aws-cdk/core/lib/cfn-resource.ts
Labels: p2, contribution/core

#21150 chore(merge-back): 2.32.0
  CHANGELOG.v2.alpha.md
  CHANGELOG.v2.md
  version.v2.json
Labels: p2, pr/no-squash, auto-approve

#21152 fix(cli): pin geonamescache dependency to 1.3
  packages/aws-cdk/test/integ/cli/sam_cdk_integ_app/src/python/Function/requirements.txt
  packages/aws-cdk/test/integ/cli/sam_cdk_integ_app/src/python/Layer/requirements.txt
Labels: p2, contribution/core

#21166 chore(release): 2.32.1
  CHANGELOG.v2.alpha.md
  CHANGELOG.v2.md
  packages/aws-cdk/test/integ/cli/sam_cdk_integ_app/src/python/Function/requirements.txt
  packages/aws-cdk/test/integ/cli/sam_cdk_integ_app/src/python/Layer/requirements.txt
  version.v2.json
Labels: p2, contribution/core, pr/no-squash

#21174 revert(core): revert "fix(core): use node.path in skip bundling check for consistency with cdk deploy CLI"
  packages/@aws-cdk/core/lib/stack.ts
  packages/@aws-cdk/core/test/staging.test.ts
Labels: p2, contribution/core

#21175 chore(release): 2.32.1
  CHANGELOG.v2.md
  packages/@aws-cdk/core/lib/stack.ts
  packages/@aws-cdk/core/test/staging.test.ts
Labels: p2, contribution/core, pr/no-squash

#21177 chore(merge-back): 1.164.0
  CHANGELOG.md
  version.v1.json
Labels: p2, pr/no-squash, auto-approve

#21178 chore(merge-back): 2.32.1
  CHANGELOG.v2.alpha.md
  CHANGELOG.v2.md
  version.v2.json
Labels: p2, pr/no-squash, auto-approve

#21198 fix: integration test for appsync apikey auth fails with out of bound API key expiration
  packages/@aws-cdk/aws-appsync/test/auth-apikey.integ.snapshot/aws-appsync-integ.assets.json
  packages/@aws-cdk/aws-appsync/test/auth-apikey.integ.snapshot/aws-appsync-integ.template.json
  packages/@aws-cdk/aws-appsync/test/auth-apikey.integ.snapshot/cdk.out
  packages/@aws-cdk/aws-appsync/test/auth-apikey.integ.snapshot/manifest.json
  packages/@aws-cdk/aws-appsync/test/auth-apikey.integ.snapshot/tree.json
  packages/@aws-cdk/aws-appsync/test/integ.auth-apikey.ts
Labels: p2, contribution/core

#20308 fix(cli): CLI timeout fetching notices prints "unreachable" branch error message
  packages/aws-cdk/lib/notices.ts
Labels: bug, p1, contribution/core, pr-linter/exempt-test

#20953 fix(core): CustomResourceProvider assets are staged in node_modules
  packages/@aws-cdk/core/lib/custom-resource-provider/custom-resource-provider.ts
  packages/@aws-cdk/core/test/custom-resource-provider/custom-resource-provider.test.ts
  packages/@aws-cdk/pipelines/test/integ.newpipeline-with-vpc.ts
  packages/@aws-cdk/pipelines/test/integ.newpipeline.ts
  packages/@aws-cdk/pipelines/test/pipeline-security.integ.snapshot/asset.207d1c59082dd1ab722c445b190e0c2cbb20d6c3e981cf674a60159b56338e86/__entrypoint__.js
  packages/@aws-cdk/pipelines/test/pipeline-security.integ.snapshot/asset.207d1c59082dd1ab722c445b190e0c2cbb20d6c3e981cf674a60159b56338e86/index.js
  packages/@aws-cdk/pipelines/test/pipeline-with-assets-single-upload.integ.snapshot/asset.207d1c59082dd1ab722c445b190e0c2cbb20d6c3e981cf674a60159b56338e86/__entrypoint__.js
  packages/@aws-cdk/pipelines/test/pipeline-with-assets-single-upload.integ.snapshot/asset.207d1c59082dd1ab722c445b190e0c2cbb20d6c3e981cf674a60159b56338e86/index.js
  packages/@aws-cdk/pipelines/test/pipeline-with-assets.integ.snapshot/asset.207d1c59082dd1ab722c445b190e0c2cbb20d6c3e981cf674a60159b56338e86/__entrypoint__.js
  packages/@aws-cdk/pipelines/test/pipeline-with-assets.integ.snapshot/asset.207d1c59082dd1ab722c445b190e0c2cbb20d6c3e981cf674a60159b56338e86/index.js
  packages/@aws-cdk/pipelines/test/pipeline-with-variables.integ.snapshot/asset.207d1c59082dd1ab722c445b190e0c2cbb20d6c3e981cf674a60159b56338e86/__entrypoint__.js
  packages/@aws-cdk/pipelines/test/pipeline-with-variables.integ.snapshot/asset.207d1c59082dd1ab722c445b190e0c2cbb20d6c3e981cf674a60159b56338e86/index.js
  packages/@aws-cdk/pipelines/test/pipeline.integ.snapshot/asset.207d1c59082dd1ab722c445b190e0c2cbb20d6c3e981cf674a60159b56338e86/__entrypoint__.js
  packages/@aws-cdk/pipelines/test/pipeline.integ.snapshot/asset.207d1c59082dd1ab722c445b190e0c2cbb20d6c3e981cf674a60159b56338e86/index.js
  tools/@aws-cdk/node-bundle/.projen/deps.json
  tools/@aws-cdk/node-bundle/package.json
  yarn.lock
Labels: bug, p1, effort/medium, contribution/core

#20036 feat(stepfunctions): add `fromStateMachineName` to import a state machine by resource name
  packages/@aws-cdk/aws-stepfunctions/README.md
  packages/@aws-cdk/aws-stepfunctions/lib/state-machine.ts
  packages/@aws-cdk/aws-stepfunctions/test/state-machine.test.ts
  packages/@aws-cdk/core/lib/stack.ts
Labels: p2, pr-linter/exempt-integ-test

#21085 feat(redshift): adds elasticIp parameter to redshift cluster
  packages/@aws-cdk/aws-redshift/README.md
  packages/@aws-cdk/aws-redshift/lib/cluster.ts
  packages/@aws-cdk/aws-redshift/test/cluster-elasticip.integ.snapshot/aws-cdk-redshift-cluster-database.assets.json
  packages/@aws-cdk/aws-redshift/test/cluster-elasticip.integ.snapshot/aws-cdk-redshift-cluster-database.template.json
  packages/@aws-cdk/aws-redshift/test/cluster-elasticip.integ.snapshot/cdk.out
  packages/@aws-cdk/aws-redshift/test/cluster-elasticip.integ.snapshot/integ.json
  packages/@aws-cdk/aws-redshift/test/cluster-elasticip.integ.snapshot/manifest.json
  packages/@aws-cdk/aws-redshift/test/cluster-elasticip.integ.snapshot/tree.json
  packages/@aws-cdk/aws-redshift/test/cluster.test.ts
  packages/@aws-cdk/aws-redshift/test/integ.cluster-elasticip.ts
Labels: p1, feature-request

#21212 chore: npm-check-updates && yarn upgrade
  package.json
  packages/@aws-cdk/aws-apigatewayv2-authorizers/package.json
  packages/@aws-cdk/aws-certificatemanager/lambda-packages/dns_validated_certificate_handler/package.json
  packages/@aws-cdk/aws-cloudformation/package.json
  packages/@aws-cdk/aws-dynamodb-global/lambda-packages/aws-global-table-coordinator/package.json
  packages/@aws-cdk/aws-dynamodb/package.json
  packages/@aws-cdk/aws-ec2/package.json
  packages/@aws-cdk/aws-eks/package.json
  packages/@aws-cdk/aws-iam/package.json
  packages/@aws-cdk/aws-lambda-nodejs/package.json
  packages/@aws-cdk/aws-lambda-nodejs/test/__snapshots__/bundling.test.js.snap
  packages/@aws-cdk/aws-lambda/package.json
  packages/@aws-cdk/aws-logs/package.json
  packages/@aws-cdk/aws-route53/package.json
  packages/@aws-cdk/aws-s3/package.json
  packages/@aws-cdk/aws-ses/package.json
  packages/@aws-cdk/cloud-assembly-schema/package.json
  packages/@aws-cdk/core/package.json
  packages/@aws-cdk/custom-resources/package.json
  packages/@aws-cdk/cx-api/package.json
  packages/@aws-cdk/integ-tests/package.json
  packages/aws-cdk-lib/package.json
  packages/aws-cdk/lib/init-templates/app/typescript/package.json
  packages/aws-cdk/lib/init-templates/sample-app/typescript/package.json
  packages/aws-cdk/package.json
  packages/awslint/package.json
  packages/cdk-dasm/package.json
  tools/@aws-cdk/cdk-build-tools/package.json
  tools/@aws-cdk/cfn2ts/package.json
  tools/@aws-cdk/node-bundle/package.json
  tools/@aws-cdk/pkglint/package.json
  tools/@aws-cdk/prlint/package.json
  tools/@aws-cdk/yarn-cling/package.json
  yarn.lock
Labels: p2, dependencies, contribution/core, auto-approve

#20879 feat(ecs-patterns): add capacityProviderStrategies props to (Application/Network)LoadBalanced(Ec2/Fargate)Service
  packages/@aws-cdk/aws-ecs-patterns/README.md
  packages/@aws-cdk/aws-ecs-patterns/lib/base/application-load-balanced-service-base.ts
  packages/@aws-cdk/aws-ecs-patterns/lib/base/network-load-balanced-service-base.ts
  packages/@aws-cdk/aws-ecs-patterns/lib/ecs/application-load-balanced-ecs-service.ts
  packages/@aws-cdk/aws-ecs-patterns/lib/ecs/network-load-balanced-ecs-service.ts
  packages/@aws-cdk/aws-ecs-patterns/lib/fargate/application-load-balanced-fargate-service.ts
  packages/@aws-cdk/aws-ecs-patterns/lib/fargate/network-load-balanced-fargate-service.ts
  packages/@aws-cdk/aws-ecs-patterns/test/ec2/application-load-balanced-ecs-service.integ.snapshot/aws-ecs-integ.assets.json
  packages/@aws-cdk/aws-ecs-patterns/test/ec2/application-load-balanced-ecs-service.integ.snapshot/aws-ecs-integ.template.json
  packages/@aws-cdk/aws-ecs-patterns/test/ec2/application-load-balanced-ecs-service.integ.snapshot/cdk.out
  packages/@aws-cdk/aws-ecs-patterns/test/ec2/application-load-balanced-ecs-service.integ.snapshot/integ.json
  packages/@aws-cdk/aws-ecs-patterns/test/ec2/application-load-balanced-ecs-service.integ.snapshot/manifest.json
  packages/@aws-cdk/aws-ecs-patterns/test/ec2/application-load-balanced-ecs-service.integ.snapshot/tree.json
  packages/@aws-cdk/aws-ecs-patterns/test/ec2/integ.application-load-balanced-ecs-service.ts
  packages/@aws-cdk/aws-ecs-patterns/test/ec2/integ.network-load-balanced-ecs-service.ts
  packages/@aws-cdk/aws-ecs-patterns/test/ec2/l3s.test.ts
  packages/@aws-cdk/aws-ecs-patterns/test/ec2/network-load-balanced-ecs-service.integ.snapshot/aws-ecs-integ.assets.json
  packages/@aws-cdk/aws-ecs-patterns/test/ec2/network-load-balanced-ecs-service.integ.snapshot/aws-ecs-integ.template.json
  packages/@aws-cdk/aws-ecs-patterns/test/ec2/network-load-balanced-ecs-service.integ.snapshot/cdk.out
  packages/@aws-cdk/aws-ecs-patterns/test/ec2/network-load-balanced-ecs-service.integ.snapshot/integ.json
  packages/@aws-cdk/aws-ecs-patterns/test/ec2/network-load-balanced-ecs-service.integ.snapshot/manifest.json
  packages/@aws-cdk/aws-ecs-patterns/test/ec2/network-load-balanced-ecs-service.integ.snapshot/tree.json
  packages/@aws-cdk/aws-ecs-patterns/test/fargate/integ.l3-capacity-provider-strategies.ts
  packages/@aws-cdk/aws-ecs-patterns/test/fargate/l3-capacity-provider-strategies.integ.snapshot/aws-ecs-integ-lb-fargate.assets.json
  packages/@aws-cdk/aws-ecs-patterns/test/fargate/l3-capacity-provider-strategies.integ.snapshot/aws-ecs-integ-lb-fargate.template.json
  packages/@aws-cdk/aws-ecs-patterns/test/fargate/l3-capacity-provider-strategies.integ.snapshot/cdk.out
  packages/@aws-cdk/aws-ecs-patterns/test/fargate/l3-capacity-provider-strategies.integ.snapshot/integ.json
  packages/@aws-cdk/aws-ecs-patterns/test/fargate/l3-capacity-provider-strategies.integ.snapshot/manifest.json
  packages/@aws-cdk/aws-ecs-patterns/test/fargate/l3-capacity-provider-strategies.integ.snapshot/tree.json
  packages/@aws-cdk/aws-ecs-patterns/test/fargate/load-balanced-fargate-service.test.ts
Labels: p2, feature-request, effort/small

#21226 docs(rds): typo OracleSe2 is Standard Edition 2
  packages/@aws-cdk/aws-rds/lib/instance-engine.ts
Labels: p2

#21202 docs: update documentation for custom resources
  packages/@aws-cdk/core/README.md
  packages/@aws-cdk/core/lib/custom-resource-provider/custom-resource-provider.ts
  packages/@aws-cdk/core/lib/custom-resource.ts
  packages/@aws-cdk/custom-resources/README.md
  packages/aws-cdk-lib/README.md
Labels: p2, contribution/core

#21229 chore: npm-check-updates && yarn upgrade
  package.json
  packages/@aws-cdk/aws-apigatewayv2-authorizers/package.json
  packages/@aws-cdk/aws-certificatemanager/lambda-packages/dns_validated_certificate_handler/package.json
  packages/@aws-cdk/aws-cloudformation/package.json
  packages/@aws-cdk/aws-dynamodb-global/lambda-packages/aws-global-table-coordinator/package.json
  packages/@aws-cdk/aws-dynamodb/package.json
  packages/@aws-cdk/aws-ec2/package.json
  packages/@aws-cdk/aws-eks/package.json
  packages/@aws-cdk/aws-iam/package.json
  packages/@aws-cdk/aws-lambda-nodejs/package.json
  packages/@aws-cdk/aws-lambda-nodejs/test/__snapshots__/bundling.test.js.snap
  packages/@aws-cdk/aws-lambda/package.json
  packages/@aws-cdk/aws-logs/package.json
  packages/@aws-cdk/aws-route53/package.json
  packages/@aws-cdk/aws-s3/package.json
  packages/@aws-cdk/aws-ses/package.json
  packages/@aws-cdk/cloud-assembly-schema/package.json
  packages/@aws-cdk/core/package.json
  packages/@aws-cdk/custom-resources/package.json
  packages/@aws-cdk/cx-api/package.json
  packages/@aws-cdk/integ-runner/THIRD_PARTY_LICENSES
  packages/@aws-cdk/integ-tests/package.json
  packages/aws-cdk-lib/package.json
  packages/aws-cdk/THIRD_PARTY_LICENSES
  packages/aws-cdk/package.json
  packages/awslint/package.json
  packages/cdk-dasm/package.json
  tools/@aws-cdk/cdk-build-tools/package.json
  tools/@aws-cdk/cfn2ts/package.json
  tools/@aws-cdk/node-bundle/package.json
  tools/@aws-cdk/pkglint/package.json
  tools/@aws-cdk/prlint/package.json
  tools/@aws-cdk/yarn-cling/package.json
  yarn.lock
Labels: p2, dependencies, contribution/core, auto-approve

#21228 chore: update THIRD_PARTY_LICENSES
  packages/aws-cdk/THIRD_PARTY_LICENSES
  packages/aws-cdk/package.json
Labels: p2, contribution/core

#20626 feat(ec2): add ICMPv6 protocol
  packages/@aws-cdk/aws-ec2/README.md
  packages/@aws-cdk/aws-ec2/lib/port.ts
  packages/@aws-cdk/aws-ec2/test/integ.ports.ts
  packages/@aws-cdk/aws-ec2/test/ports.integ.snapshot/PortsDefaultTestDeployAssert044B81BF.template.json
  packages/@aws-cdk/aws-ec2/test/ports.integ.snapshot/PortsTestStack.template.json
  packages/@aws-cdk/aws-ec2/test/ports.integ.snapshot/TestStack.assets.json
  packages/@aws-cdk/aws-ec2/test/ports.integ.snapshot/TestStack.template.json
  packages/@aws-cdk/aws-ec2/test/ports.integ.snapshot/cdk.out
  packages/@aws-cdk/aws-ec2/test/ports.integ.snapshot/integ.json
  packages/@aws-cdk/aws-ec2/test/ports.integ.snapshot/manifest.json
  packages/@aws-cdk/aws-ec2/test/ports.integ.snapshot/tree.json
Labels: p2

#21236 chore: handle rejected CFN spec updates
  packages/@aws-cdk/cfnspec/build-tools/patch-set.ts
  packages/@aws-cdk/cfnspec/build-tools/report-issues.ts
  packages/@aws-cdk/cfnspec/build-tools/split-spec-by-service.ts
  packages/@aws-cdk/cfnspec/package.json
  packages/@aws-cdk/cfnspec/spec-source/specification/000_cfn/000_official/.000_AWS_ConnectCampaigns.rejected.json
  packages/@aws-cdk/cfnspec/spec-source/specification/000_cfn/000_official/.000_AWS_Rekognition.rejected.json
  packages/@aws-cdk/cfnspec/spec-source/specification/000_cfn/000_official/.000_AWS_RolesAnywhere.rejected.json
  packages/@aws-cdk/cfnspec/spec-source/specification/000_cfn/000_official/.000_AWS_SageMaker.rejected.json
  packages/@aws-cdk/cfnspec/spec-source/specification/000_cfn/000_official/000_AWS_ConnectCampaigns.json
  packages/@aws-cdk/cfnspec/spec-source/specification/000_cfn/000_official/000_AWS_RolesAnywhere.json
  scripts/cfnspec-report-rejected.sh
Labels: p2, contribution/core

#21240 chore(merge-back): 2.33.0
  CHANGELOG.v2.alpha.md
  CHANGELOG.v2.md
  version.v2.json
Labels: p2, pr/no-squash, auto-approve

#21241 feat(ecs): add function to grant run permissions to task definition
  packages/@aws-cdk/aws-ecs/README.md
  packages/@aws-cdk/aws-ecs/lib/base/task-definition.ts
  packages/@aws-cdk/aws-ecs/test/task-definition.test.ts
Labels: p2, pr-linter/exempt-integ-test

#21244 docs(ecs): update documentation for clusters
  packages/@aws-cdk/aws-ecs/lib/cluster.ts
Labels: p2

#21252 chore: npm-check-updates && yarn upgrade
  packages/@aws-cdk/aws-certificatemanager/lambda-packages/dns_validated_certificate_handler/package.json
  packages/@aws-cdk/aws-dynamodb-global/lambda-packages/aws-global-table-coordinator/package.json
  packages/@aws-cdk/aws-eks/package.json
  packages/@aws-cdk/aws-logs/package.json
  packages/@aws-cdk/custom-resources/package.json
  packages/@aws-cdk/integ-tests/package.json
  packages/aws-cdk/package.json
  tools/@aws-cdk/node-bundle/package.json
  yarn.lock
Labels: p2, dependencies, contribution/core, auto-approve

#21251 chore: npm-check-updates && yarn upgrade
  packages/@aws-cdk/aws-certificatemanager/lambda-packages/dns_validated_certificate_handler/package.json
  packages/@aws-cdk/aws-dynamodb-global/lambda-packages/aws-global-table-coordinator/package.json
  packages/@aws-cdk/aws-eks/package.json
  packages/@aws-cdk/aws-logs/package.json
  packages/@aws-cdk/custom-resources/package.json
  packages/@aws-cdk/integ-runner/THIRD_PARTY_LICENSES
  packages/@aws-cdk/integ-tests/package.json
  packages/aws-cdk/THIRD_PARTY_LICENSES
  packages/aws-cdk/package.json
  tools/@aws-cdk/node-bundle/package.json
  yarn.lock
Labels: p2, dependencies, contribution/core, auto-approve

#21234 chore(rds): add missing oracle versions
  packages/@aws-cdk/aws-rds/lib/instance-engine.ts
  packages/@aws-cdk/aws-rds/test/instance-engine.test.ts
Labels: p2

#21225 docs(ecs-patterns):fix aws ecs patterns docs
  packages/@aws-cdk/aws-ecs-patterns/README.md
Labels: p2

#21256 chore: update attributions
  packages/aws-cdk/THIRD_PARTY_LICENSES
Labels: p2, contribution/core

#20068 feat(cli): cannot pass objects and numbers as context arguments
  packages/aws-cdk/lib/settings.ts
  packages/aws-cdk/test/settings.test.ts
Labels: p2, contribution/core, pr-linter/exempt-readme, pr-linter/exempt-integ-test

#21258 chore: check different build project
  .github/workflows/close-stale-prs.yml
Labels: p2, contribution/core

#21260 chore(ecs-patterns) updating integration tests
  packages/@aws-cdk/aws-ecs-patterns/test/ec2/integ.application-load-balanced-ecs-service.ts
  packages/@aws-cdk/aws-ecs-patterns/test/ec2/integ.network-load-balanced-ecs-service.ts
  packages/@aws-cdk/aws-ecs-patterns/test/ec2/network-load-balanced-ecs-service.integ.snapshot/aws-ecs-integ.assets.json
  packages/@aws-cdk/aws-ecs-patterns/test/ec2/network-load-balanced-ecs-service.integ.snapshot/aws-ecs-integ.template.json
  packages/@aws-cdk/aws-ecs-patterns/test/ec2/network-load-balanced-ecs-service.integ.snapshot/integ.json
  packages/@aws-cdk/aws-ecs-patterns/test/ec2/network-load-balanced-ecs-service.integ.snapshot/manifest.json
  packages/@aws-cdk/aws-ecs-patterns/test/ec2/network-load-balanced-ecs-service.integ.snapshot/networkLoadBalancedEc2ServiceTestDefaultTestDeployAssert34DAD7DE.template.json
  packages/@aws-cdk/aws-ecs-patterns/test/ec2/network-load-balanced-ecs-service.integ.snapshot/tree.json
  packages/@aws-cdk/aws-ecs-patterns/test/fargate/integ.l3-capacity-provider-strategies.ts
Labels: p2, effort/small

#20741 feat(lambda-event-sources): add AT_TIMESTAMP event source mapping starting position
  packages/@aws-cdk/aws-lambda-event-sources/README.md
  packages/@aws-cdk/aws-lambda-event-sources/lib/kinesis.ts
  packages/@aws-cdk/aws-lambda-event-sources/package.json
  packages/@aws-cdk/aws-lambda-event-sources/test/integ.kinesis-at-timestamp.ts
  packages/@aws-cdk/aws-lambda-event-sources/test/kinesis-at-timestamp.integ.snapshot/AtTimestampDefaultTestDeployAssert8000E9DC.template.json
  packages/@aws-cdk/aws-lambda-event-sources/test/kinesis-at-timestamp.integ.snapshot/cdk.out
  packages/@aws-cdk/aws-lambda-event-sources/test/kinesis-at-timestamp.integ.snapshot/integ.json
  packages/@aws-cdk/aws-lambda-event-sources/test/kinesis-at-timestamp.integ.snapshot/lambda-event-source-kinesis-at-timestamp.template.json
  packages/@aws-cdk/aws-lambda-event-sources/test/kinesis-at-timestamp.integ.snapshot/manifest.json
  packages/@aws-cdk/aws-lambda-event-sources/test/kinesis-at-timestamp.integ.snapshot/tree.json
  packages/@aws-cdk/aws-lambda-event-sources/test/kinesis.test.ts
  packages/@aws-cdk/aws-lambda/lib/event-source-mapping.ts
  packages/@aws-cdk/aws-lambda/test/event-source-mapping.test.ts
Labels: p2, feature-request, effort/small

#21257 feat(ec2): add R6A instances
  packages/@aws-cdk/aws-ec2/lib/instance-types.ts
  packages/@aws-cdk/aws-ec2/test/instance.test.ts
Labels: p2, pr-linter/exempt-readme, pr-linter/exempt-integ-test

#21274 chore: add more SslPolicy values
  packages/@aws-cdk/aws-elasticloadbalancingv2/lib/shared/enums.ts
Labels: p2, contribution/core

#21265 chore(pkglint): remove test artifacts after test run
  tools/@aws-cdk/pkglint/test/libary-creation.test.ts
Labels: p2

#21137 fix(ecr): Repository.addToResourcePolicy returns incorrect result
  packages/@aws-cdk/aws-ecr/lib/repository.ts
  packages/@aws-cdk/aws-ecr/test/repository.test.ts
Labels: bug, p2, effort/medium

#21267 chore: escape the process execPath to avoid issues with spaces in dir names
  tools/@aws-cdk/cdk-build-tools/lib/lint.ts
  tools/@aws-cdk/cdk-build-tools/lib/os.ts
Labels: p2

#21290 chore: run close-stale-prs with user permissions
  .github/workflows/close-stale-prs.yml
Labels: p2, contribution/core

#21293 chore(elbv2): remove deprecated enum
  packages/@aws-cdk/aws-elasticloadbalancingv2/lib/shared/enums.ts
Labels: p2, contribution/core

#21270 fix(cli): add validation of --notification-arns structure
  packages/aws-cdk/lib/cdk-toolkit.ts
  packages/aws-cdk/lib/util/validate-notification-arn.ts
  packages/aws-cdk/test/cdk-toolkit.test.ts
  packages/aws-cdk/test/util/validate-notification-arn.test.ts
Labels: bug, p1, effort/small

#21302 chore(lambda): update link to handler docs
  packages/@aws-cdk/aws-lambda/lib/function.ts
Labels: p2

#21294 chore(cli): add integ test for asset bundling in a stage
  packages/aws-cdk/test/integ/cli/app/app.js
  packages/aws-cdk/test/integ/cli/cli.integtest.ts
Labels: p2, contribution/core

#21208 fix(pkglint): allow dependencies on L1 only modules
  tools/@aws-cdk/pkglint/lib/rules.ts
Labels: p2, contribution/core, pr-linter/exempt-test

#21207 feat(api-gateway): allow configuration of deployment description
  packages/@aws-cdk/aws-apigateway/lib/restapi.ts
  packages/@aws-cdk/aws-apigateway/test/restapi.test.ts
Labels: p2, feature-request, effort/small, pr-linter/exempt-readme, pr-linter/exempt-integ-test

#21201 fix(ecs-patterns): memory limit is not set at the container level
  packages/@aws-cdk/aws-ecs-patterns/lib/fargate/application-load-balanced-fargate-service.ts
  packages/@aws-cdk/aws-ecs-patterns/lib/fargate/application-multiple-target-groups-fargate-service.ts
  packages/@aws-cdk/aws-ecs-patterns/lib/fargate/network-load-balanced-fargate-service.ts
  packages/@aws-cdk/aws-ecs-patterns/lib/fargate/network-multiple-target-groups-fargate-service.ts
  packages/@aws-cdk/aws-ecs-patterns/lib/fargate/queue-processing-fargate-service.ts
  packages/@aws-cdk/aws-ecs-patterns/lib/fargate/scheduled-fargate-task.ts
  packages/@aws-cdk/aws-ecs-patterns/test/ec2/l3s.test.ts
  packages/@aws-cdk/aws-ecs-patterns/test/fargate/alb-fargate-service-https.integ.snapshot/aws-ecs-integ-alb-fg-https.template.json
  packages/@aws-cdk/aws-ecs-patterns/test/fargate/circuit-breaker-load-balanced-fargate-service.integ.snapshot/aws-ecs-integ.template.json
  packages/@aws-cdk/aws-ecs-patterns/test/fargate/circuit-breaker-queue-processing-fargate-service.integ.snapshot/aws-ecs-patterns-queue.template.json
  packages/@aws-cdk/aws-ecs-patterns/test/fargate/executionrole.integ.snapshot/aws-ecs-integ.template.json
  packages/@aws-cdk/aws-ecs-patterns/test/fargate/l3-autocreate.integ.snapshot/aws-ecs-integ-l3-autocreate.template.json
  packages/@aws-cdk/aws-ecs-patterns/test/fargate/l3-capacity-provider-strategies.integ.snapshot/aws-ecs-integ-lb-fargate.template.json
  packages/@aws-cdk/aws-ecs-patterns/test/fargate/l3-vpconly.integ.snapshot/aws-ecs-integ-l3-vpconly.template.json
  packages/@aws-cdk/aws-ecs-patterns/test/fargate/l3.integ.snapshot/aws-ecs-integ-lb-fargate.template.json
  packages/@aws-cdk/aws-ecs-patterns/test/fargate/multiple-network-load-balanced-fargate-service.integ.snapshot/aws-ecs-integ.template.json
  packages/@aws-cdk/aws-ecs-patterns/test/fargate/queue-processing-fargate-service-isolated.integ.snapshot/aws-ecs-patterns-queue-isolated.template.json
  packages/@aws-cdk/aws-ecs-patterns/test/fargate/queue-processing-fargate-service-public.integ.snapshot/aws-ecs-patterns-queue-public.template.json
  packages/@aws-cdk/aws-ecs-patterns/test/fargate/queue-processing-fargate-service.integ.snapshot/aws-ecs-patterns-queue.template.json
  packages/@aws-cdk/aws-ecs-patterns/test/fargate/scheduled-fargate-task.integ.snapshot/aws-fargate-integ.template.json
  packages/@aws-cdk/aws-ecs-patterns/test/fargate/scheduled-fargate-task.lit.integ.snapshot/aws-fargate-integ.template.json
Labels: p2

#21327 chore: merge-back v1.165.0
  CHANGELOG.md
  version.v1.json
Labels: p2, contribution/core, pr/no-squash, auto-approve

#20636 fix(ecs): firelens configFileValue is unnecessarily required
  packages/@aws-cdk/aws-ecs/lib/firelens-log-router.ts
  packages/@aws-cdk/aws-ecs/test/ec2/integ.firelens-s3-config.ts
  packages/@aws-cdk/aws-ecs/test/firelens-log-driver.test.ts
Labels: p1

#21230 fix(cli): large context causes E2BIG error during synthesis on Linux
  packages/@aws-cdk/core/lib/app.ts
  packages/@aws-cdk/core/test/app.test.ts
  packages/@aws-cdk/cx-api/lib/cxapi.ts
  packages/aws-cdk/lib/api/cxapp/exec.ts
  packages/aws-cdk/lib/commands/doctor.ts
Labels: bug, p1, effort/medium, contribution/core

#21340 chore: npm-check-updates && yarn upgrade
  package.json
  packages/@aws-cdk/aws-eks/package.json
  packages/@aws-cdk/aws-lambda-nodejs/package.json
  packages/aws-cdk-lib/package.json
  packages/aws-cdk/package.json
  packages/awslint/package.json
  packages/cdk-dasm/package.json
  tools/@aws-cdk/cdk-build-tools/package.json
  tools/@aws-cdk/cfn2ts/package.json
  tools/@aws-cdk/node-bundle/package.json
  yarn.lock
Labels: p2, dependencies, contribution/core, auto-approve

#21342 fix(bootstrap): remove image scanning configuration
  packages/aws-cdk/lib/api/bootstrap/bootstrap-template.yaml
Labels: p2, contribution/core, pr-linter/exempt-test

#21353 fix(aws-lambda): FunctionUrl incorrectly uses Alias ARNs
  packages/@aws-cdk/aws-lambda/lib/function-url.ts
  packages/@aws-cdk/aws-lambda/test/alias.test.ts
  packages/@aws-cdk/aws-lambda/test/function-url.test.ts
  packages/@aws-cdk/aws-lambda/test/lambda.integ.snapshot/aws-cdk-lambda-1.assets.json
  packages/@aws-cdk/aws-lambda/test/lambda.integ.snapshot/aws-cdk-lambda-1.template.json
  packages/@aws-cdk/aws-lambda/test/lambda.integ.snapshot/manifest.json
  packages/@aws-cdk/aws-lambda/test/lambda.integ.snapshot/tree.json
Labels: p2, contribution/core

#21355 chore: fixup cli THIRD_PARTY_LICENSES
  packages/@aws-cdk/integ-runner/THIRD_PARTY_LICENSES
  packages/aws-cdk/THIRD_PARTY_LICENSES
  tools/@aws-cdk/pkglint/lib/rules.ts
Labels: p2, contribution/core

#21321 feat(core): cache fingerprints of large assets
  packages/@aws-cdk/core/lib/asset-staging.ts
  packages/@aws-cdk/core/lib/fs/fingerprint.ts
  packages/@aws-cdk/core/test/fs/fs-fingerprint.test.ts
Labels: p2, pr-linter/exempt-readme, pr-linter/exempt-integ-test

#21344 feat(config): add support for eks-cluster-xxx-version managed rule
  packages/@aws-cdk/aws-config/lib/rule.ts
  packages/@aws-cdk/aws-config/test/rule.test.ts
Labels: p2, feature-request, effort/small, pr-linter/exempt-readme, pr-linter/exempt-integ-test

#18140 fix(ecs): new arn format not supported (under feature flag)
  packages/@aws-cdk/aws-ecs/README.md
  packages/@aws-cdk/aws-ecs/lib/base/from-service-attributes.ts
  packages/@aws-cdk/aws-ecs/lib/ec2/ec2-service.ts
  packages/@aws-cdk/aws-ecs/lib/fargate/fargate-service.ts
  packages/@aws-cdk/aws-ecs/test/ec2/ec2-service.test.ts
  packages/@aws-cdk/aws-ecs/test/fargate/fargate-service.test.ts
  packages/@aws-cdk/cx-api/lib/features.ts
Labels: bug, p1, @aws-cdk/aws-ecs, effort/medium

#21301 feat(fsx): support AutoImportPolicy in LustreFilesystem
  packages/@aws-cdk/aws-fsx/README.md
  packages/@aws-cdk/aws-fsx/lib/lustre-file-system.ts
  packages/@aws-cdk/aws-fsx/package.json
  packages/@aws-cdk/aws-fsx/test/integ.lustre-file-system-with-s3.ts
  packages/@aws-cdk/aws-fsx/test/lustre-file-system-with-s3.integ.snapshot/AwsCdkFsxLustre.assets.json
  packages/@aws-cdk/aws-fsx/test/lustre-file-system-with-s3.integ.snapshot/AwsCdkFsxLustre.template.json
  packages/@aws-cdk/aws-fsx/test/lustre-file-system-with-s3.integ.snapshot/FsxLustreWithS3TestDefaultTestDeployAssert0752DB81.template.json
  packages/@aws-cdk/aws-fsx/test/lustre-file-system-with-s3.integ.snapshot/cdk.out
  packages/@aws-cdk/aws-fsx/test/lustre-file-system-with-s3.integ.snapshot/integ.json
  packages/@aws-cdk/aws-fsx/test/lustre-file-system-with-s3.integ.snapshot/manifest.json
  packages/@aws-cdk/aws-fsx/test/lustre-file-system-with-s3.integ.snapshot/tree.json
  packages/@aws-cdk/aws-fsx/test/lustre-file-system.test.ts
Labels: p1, feature-request, effort/medium

#21372 chore(merge-back): 2.34.0
  CHANGELOG.v2.alpha.md
  CHANGELOG.v2.md
  buildspec-pr.yaml
  buildspec.yaml
  version.v2.json
Labels: p2, pr/no-squash, auto-approve

#21374 fix(core): asset fingerprint cache invalidation incorrectly uses mtime
  packages/@aws-cdk/cloudformation-diff/package.json
  packages/@aws-cdk/core/lib/fs/fingerprint.ts
  packages/@aws-cdk/core/package.json
  packages/@aws-cdk/core/test/fs/fs-fingerprint.test.ts
  packages/@aws-cdk/integ-runner/lib/runner/snapshot-test-runner.ts
  packages/@aws-cdk/integ-runner/package.json
  packages/@aws-cdk/integ-tests/package.json
  packages/@monocdk-experiment/assert/package.json
  packages/@monocdk-experiment/rewrite-imports/package.json
  packages/aws-cdk-lib/package.json
  packages/aws-cdk-migration/package.json
  packages/aws-cdk/package.json
  packages/aws-cdk/test/api/util/display.test.ts
  packages/aws-cdk/test/diff.test.ts
  packages/aws-cdk/test/version.test.ts
  packages/cdk-assets/lib/private/shell.ts
  packages/cdk-assets/package.json
  packages/cdk-cli-wrapper/package.json
  packages/monocdk/package.json
  tools/@aws-cdk/eslint-plugin/package.json
  tools/@aws-cdk/node-bundle/package.json
  tools/@aws-cdk/pkglint/lib/rules.ts
  tools/@aws-cdk/yarn-cling/package.json
  yarn.lock
Labels: p2, contribution/core, pr-linter/exempt-test, pr-linter/exempt-integ-test

#21382 chore(merge-back): 2.34.1
  CHANGELOG.v2.alpha.md
  CHANGELOG.v2.md
  package.json
  tools/@aws-cdk/cdk-build-tools/package.json
  version.v2.json
  yarn.lock
Labels: p2, pr/no-squash, auto-approve

#19889 chore(iot-events): support all binary operators
  packages/@aws-cdk/aws-iotevents/lib/expression.ts
  packages/@aws-cdk/aws-iotevents/test/detector-model.test.ts
Labels: p2

#21385 chore(merge-back): 1.166.1
  CHANGELOG.md
  buildspec-pr.yaml
  buildspec.yaml
  package.json
  tools/@aws-cdk/cdk-build-tools/package.json
  version.v1.json
  yarn.lock
Labels: p2, pr/no-squash, auto-approve

#21387 revert(cli): cannot pass objects and numbers as context arguments
  packages/aws-cdk/lib/settings.ts
  packages/aws-cdk/test/settings.test.ts
Labels: bug, p0, contribution/core

#21388 chore(release): 2.34.2
  CHANGELOG.v2.alpha.md
  CHANGELOG.v2.md
  packages/aws-cdk/lib/settings.ts
  packages/aws-cdk/test/settings.test.ts
  version.v2.json
Labels: p2, contribution/core, pr/no-squash

#21386 fix(cognito): UserPoolClient doesn't correctly respect authFlows
  packages/@aws-cdk/aws-cognito/lib/user-pool-client.ts
  packages/@aws-cdk/aws-cognito/test/user-pool-client.test.ts
Labels: bug, p2, effort/small

#21056 feat(rds): add copyTagsToSnapshot to the construct props for ServerlessCluster and ServerlessClusterFromSnapshot
  packages/@aws-cdk/aws-rds/README.md
  packages/@aws-cdk/aws-rds/lib/serverless-cluster.ts
  packages/@aws-cdk/aws-rds/test/integ.serverless-cluster-no-vpc.ts
  packages/@aws-cdk/aws-rds/test/integ.serverless-cluster.ts
  packages/@aws-cdk/aws-rds/test/serverless-cluster-from-snapshot.test.ts
  packages/@aws-cdk/aws-rds/test/serverless-cluster-no-vpc.integ.snapshot/aws-cdk-sls-cluster-no-vpc-integ.assets.json
  packages/@aws-cdk/aws-rds/test/serverless-cluster-no-vpc.integ.snapshot/aws-cdk-sls-cluster-no-vpc-integ.template.json
  packages/@aws-cdk/aws-rds/test/serverless-cluster-no-vpc.integ.snapshot/cdk.out
  packages/@aws-cdk/aws-rds/test/serverless-cluster-no-vpc.integ.snapshot/manifest.json
  packages/@aws-cdk/aws-rds/test/serverless-cluster-no-vpc.integ.snapshot/tree.json
  packages/@aws-cdk/aws-rds/test/serverless-cluster.integ.snapshot/aws-cdk-rds-integ.assets.json
  packages/@aws-cdk/aws-rds/test/serverless-cluster.integ.snapshot/aws-cdk-rds-integ.template.json
  packages/@aws-cdk/aws-rds/test/serverless-cluster.integ.snapshot/cdk.out
  packages/@aws-cdk/aws-rds/test/serverless-cluster.integ.snapshot/manifest.json
  packages/@aws-cdk/aws-rds/test/serverless-cluster.integ.snapshot/tree.json
  packages/@aws-cdk/aws-rds/test/serverless-cluster.test.ts
Labels: bug, p2, effort/small

#20938 docs(dynamodb): the documentation is wrong around table encryption
  packages/@aws-cdk/aws-dynamodb/lib/table.ts
Labels: bug, p2, effort/small

#21261 feat(ecs-patterns) add idle timeout to alb fargate and ec2 services
  packages/@aws-cdk/aws-ecs-patterns/README.md
  packages/@aws-cdk/aws-ecs-patterns/lib/base/application-load-balanced-service-base.ts
  packages/@aws-cdk/aws-ecs-patterns/test/ec2/l3s.test.ts
  packages/@aws-cdk/aws-ecs-patterns/test/fargate/alb-fargate-service-https-idle-timeout.integ.snapshot/aws-ecs-integ-alb-fg-idletimeout.template.json
  packages/@aws-cdk/aws-ecs-patterns/test/fargate/alb-fargate-service-https-idle-timeout.integ.snapshot/cdk.out
  packages/@aws-cdk/aws-ecs-patterns/test/fargate/alb-fargate-service-https-idle-timeout.integ.snapshot/idleTimeoutTestDefaultTestDeployAssert276553CB.template.json
  packages/@aws-cdk/aws-ecs-patterns/test/fargate/alb-fargate-service-https-idle-timeout.integ.snapshot/integ.json
  packages/@aws-cdk/aws-ecs-patterns/test/fargate/alb-fargate-service-https-idle-timeout.integ.snapshot/manifest.json
  packages/@aws-cdk/aws-ecs-patterns/test/fargate/alb-fargate-service-https-idle-timeout.integ.snapshot/tree.json
  packages/@aws-cdk/aws-ecs-patterns/test/fargate/integ.alb-fargate-service-https-idle-timeout.ts
Labels: p2, feature-request, effort/small

#21389 chore(merge-back): 2.34.2
  CHANGELOG.v2.alpha.md
  CHANGELOG.v2.md
  version.v2.json
Labels: p2, pr/no-squash, auto-approve
