Repository aws/aws-cdk, pull requests merged in 2022-10, with the labels that each got.

#21488 feat(apigateway): create BasePathMapping without stage
  packages/@aws-cdk/aws-apigateway/README.md
  packages/@aws-cdk/aws-apigateway/lib/base-path-mapping.ts
  packages/@aws-cdk/aws-apigateway/test/base-path-mapping.integ.snapshot/basepathmappingDefaultTestDeployAssertDA82B6F0.assets.json
  packages/@aws-cdk/aws-apigateway/test/base-path-mapping.integ.snapshot/basepathmappingDefaultTestDeployAssertDA82B6F0.template.json
  packages/@aws-cdk/aws-apigateway/test/base-path-mapping.integ.snapshot/cdk.out
  packages/@aws-cdk/aws-apigateway/test/base-path-mapping.integ.snapshot/integ.json
  packages/@aws-cdk/aws-apigateway/test/base-path-mapping.integ.snapshot/manifest.json
  packages/@aws-cdk/aws-apigateway/test/base-path-mapping.integ.snapshot/test-stack.assets.json
  packages/@aws-cdk/aws-apigateway/test/base-path-mapping.integ.snapshot/test-stack.template.json
  packages/@aws-cdk/aws-apigateway/test/base-path-mapping.integ.snapshot/tree.json
  packages/@aws-cdk/aws-apigateway/test/base-path-mapping.test.ts
  packages/@aws-cdk/aws-apigateway/test/integ.base-path-mapping.ts
Labels: p2, feature-request, effort/medium

#22276 chore: Update ignore-usernames for merit badger
  .github/workflows/github-merit-badger.yml
  .mergify.yml
Labels: p2, contribution/core

#22324 chore(rds): add MySQL 5.7.38~39 and mariadb 10.6.10
  packages/@aws-cdk/aws-rds/lib/instance-engine.ts
Labels: p2, valued-contributor

#22322 feat(apigateway): add accessLogField static method
  packages/@aws-cdk/aws-apigateway/README.md
  packages/@aws-cdk/aws-apigateway/lib/access-log.ts
  packages/@aws-cdk/aws-apigateway/test/access-log.test.ts
  packages/@aws-cdk/aws-apigateway/test/integ.restapi.access-log.ts
  packages/@aws-cdk/aws-apigateway/test/restapi.access-log.integ.snapshot/manifest.json
  packages/@aws-cdk/aws-apigateway/test/restapi.access-log.integ.snapshot/test-apigateway-access-logs.assets.json
  packages/@aws-cdk/aws-apigateway/test/restapi.access-log.integ.snapshot/test-apigateway-access-logs.template.json
  packages/@aws-cdk/aws-apigateway/test/restapi.access-log.integ.snapshot/tree.json
Labels: p2, feature-request, effort/small, beginning-contributor

#22242 fix(stepfunctions-tasks): emrcontainers has incorrect validation of entry point arguments
  packages/@aws-cdk/aws-stepfunctions-tasks/lib/emrcontainers/start-job-run.ts
  packages/@aws-cdk/aws-stepfunctions-tasks/test/emrcontainers/start-job-run.test.ts
Labels: bug, p2, effort/small, contribution/core, pr-linter/exempt-integ-test

#21797 fix(sns): race condition exists between sqs queue policy and sns subscription
  packages/@aws-cdk-containers/ecs-service-extensions/test/publish-subscribe.integ.snapshot/aws-ecs-integ.template.json
  packages/@aws-cdk/aws-cloudformation/test/nested-stack.integ.snapshot/nested-stacks-test.template.json
  packages/@aws-cdk/aws-events-targets/test/codebuild/project-events.integ.snapshot/aws-cdk-codebuild-events.template.json
  packages/@aws-cdk/aws-events-targets/test/sns/sns-event-rule-target.integ.snapshot/aws-cdk-sns-event-target.template.json
  packages/@aws-cdk/aws-sns-subscriptions/lib/sqs.ts
  packages/@aws-cdk/aws-sns-subscriptions/test/sns-sqs.lit.integ.snapshot/aws-cdk-sns-sqs.template.json
  packages/@aws-cdk/aws-sns/lib/subscriber.ts
  packages/@aws-cdk/aws-sns/lib/topic-base.ts
  packages/@aws-cdk/aws-stepfunctions-tasks/test/sns/publish.integ.snapshot/aws-stepfunctions-tasks-sns-publish-integ.template.json
Labels: bug, p1, effort/small, pr-linter/exempt-integ-test

#22238 chore(integ-tests): refactor assertions provider
  packages/@aws-cdk/aws-events-targets/test/logs/log-group.integ.snapshot/LogGroupDefaultTestDeployAssert353EE07A.assets.json
  packages/@aws-cdk/aws-events-targets/test/logs/log-group.integ.snapshot/LogGroupDefaultTestDeployAssert353EE07A.template.json
  packages/@aws-cdk/aws-events-targets/test/logs/log-group.integ.snapshot/asset.d47f7e6772bfdf47ecbc070ffe204baf53bacbfbf7814eb407bd8ea108c1c1bb.bundle/index.js
  packages/@aws-cdk/aws-events-targets/test/logs/log-group.integ.snapshot/manifest.json
  packages/@aws-cdk/aws-events-targets/test/logs/log-group.integ.snapshot/tree.json
  packages/@aws-cdk/aws-ssm/test/list-parameter.integ.snapshot/asset.d47f7e6772bfdf47ecbc070ffe204baf53bacbfbf7814eb407bd8ea108c1c1bb.bundle/index.js
  packages/@aws-cdk/aws-ssm/test/list-parameter.integ.snapshot/manifest.json
  packages/@aws-cdk/aws-ssm/test/list-parameter.integ.snapshot/ssmstringparamDefaultTestDeployAssert9C612E37.assets.json
  packages/@aws-cdk/aws-ssm/test/list-parameter.integ.snapshot/ssmstringparamDefaultTestDeployAssert9C612E37.template.json
  packages/@aws-cdk/integ-tests/lib/assertions/api-call-base.ts
  packages/@aws-cdk/integ-tests/lib/assertions/providers/lambda-handler/assertion.ts
  packages/@aws-cdk/integ-tests/lib/assertions/providers/lambda-handler/base.ts
  packages/@aws-cdk/integ-tests/lib/assertions/providers/lambda-handler/index.ts
  packages/@aws-cdk/integ-tests/lib/assertions/providers/lambda-handler/sdk.ts
  packages/@aws-cdk/integ-tests/lib/assertions/providers/lambda-handler/types.ts
  packages/@aws-cdk/integ-tests/lib/assertions/sdk.ts
  packages/@aws-cdk/integ-tests/test/assertions/providers/lambda-handler/assertion.test.ts
  packages/@aws-cdk/integ-tests/test/assertions/providers/lambda-handler/base.test.ts
  packages/@aws-cdk/integ-tests/test/assertions/providers/provider.test.ts
  packages/@aws-cdk/integ-tests/test/assertions/sdk.test.ts
Labels: p2, contribution/core

#22308 feat(core): make `StackSynthesizer` easier to subclass
  packages/@aws-cdk/aws-ecr-assets/test/custom-synthesis.test.ts
  packages/@aws-cdk/aws-s3-assets/test/custom-synthesis.test.ts
  packages/@aws-cdk/aws-servicecatalog/lib/private/product-stack-synthesizer.ts
  packages/@aws-cdk/cloud-assembly-schema/lib/cloud-assembly/artifact-schema.ts
  packages/@aws-cdk/core/lib/stack-synthesizers/_asset-manifest-builder.ts
  packages/@aws-cdk/core/lib/stack-synthesizers/_shared.ts
  packages/@aws-cdk/core/lib/stack-synthesizers/asset-manifest-builder.ts
  packages/@aws-cdk/core/lib/stack-synthesizers/bootstrapless-synthesizer.ts
  packages/@aws-cdk/core/lib/stack-synthesizers/cli-credentials-synthesizer.ts
  packages/@aws-cdk/core/lib/stack-synthesizers/default-synthesizer.ts
  packages/@aws-cdk/core/lib/stack-synthesizers/index.ts
  packages/@aws-cdk/core/lib/stack-synthesizers/legacy.ts
  packages/@aws-cdk/core/lib/stack-synthesizers/nested.ts
  packages/@aws-cdk/core/lib/stack-synthesizers/stack-synthesizer.ts
  packages/@aws-cdk/core/test/stack-synthesis/new-style-synthesis.test.ts
  packages/@aws-cdk/core/test/synthesis.test.ts
  packages/@aws-cdk/cx-api/lib/artifacts/asset-manifest-artifact.ts
Labels: p2, contribution/core, pr-linter/exempt-readme, pr-linter/exempt-integ-test

#22278 chore: documentation and comments for `--hotswap`
  packages/aws-cdk/README.md
  packages/aws-cdk/lib/api/hotswap/ecs-services.ts
Labels: p2, beginning-contributor, pr-linter/cli-integ-tested

#22126 feat(cfn-include): allow cyclical dependencies
  packages/@aws-cdk/assertions/README.md
  packages/@aws-cdk/assertions/lib/template.ts
  packages/@aws-cdk/assertions/test/template.test.ts
  packages/@aws-cdk/cloudformation-include/README.md
  packages/@aws-cdk/cloudformation-include/lib/cfn-include.ts
  packages/@aws-cdk/cloudformation-include/test/invalid-templates.test.ts
  packages/@aws-cdk/cloudformation-include/test/test-templates/invalid/multi-cycle-in-resources.json
  packages/@aws-cdk/cloudformation-include/test/test-templates/invalid/multi-cycle-multi-dest-in-resources.json
Labels: bug, p2, pr-linter/exempt-integ-test

#22331 fix(s3): Bucket Key cannot be used with KMS_MANAGED key
  packages/@aws-cdk/aws-s3/lib/bucket.ts
  packages/@aws-cdk/aws-s3/test/bucket.test.ts
Labels: p2, contribution/core, pr-linter/exempt-integ-test

#22313 feat(gamelift): add Build L2 constructs for GameLift
  packages/@aws-cdk/aws-gamelift/.gitignore
  packages/@aws-cdk/aws-gamelift/README.md
  packages/@aws-cdk/aws-gamelift/lib/build.ts
  packages/@aws-cdk/aws-gamelift/lib/content.ts
  packages/@aws-cdk/aws-gamelift/lib/index.ts
  packages/@aws-cdk/aws-gamelift/package.json
  packages/@aws-cdk/aws-gamelift/rosetta/default.ts-fixture
  packages/@aws-cdk/aws-gamelift/test/build.integ.snapshot/asset.6019bfc8ab05a24b0ae9b5d8f4585cbfc7d1c30a23286d0b25ce7066a368a5d7/index.js
  packages/@aws-cdk/aws-gamelift/test/build.integ.snapshot/aws-gamelift-build.assets.json
  packages/@aws-cdk/aws-gamelift/test/build.integ.snapshot/aws-gamelift-build.template.json
  packages/@aws-cdk/aws-gamelift/test/build.integ.snapshot/cdk.out
  packages/@aws-cdk/aws-gamelift/test/build.integ.snapshot/integ.json
  packages/@aws-cdk/aws-gamelift/test/build.integ.snapshot/manifest.json
  packages/@aws-cdk/aws-gamelift/test/build.integ.snapshot/tree.json
  packages/@aws-cdk/aws-gamelift/test/build.test.ts
  packages/@aws-cdk/aws-gamelift/test/content.test.ts
  packages/@aws-cdk/aws-gamelift/test/gamelift.test.ts
  packages/@aws-cdk/aws-gamelift/test/integ.build.ts
  packages/@aws-cdk/aws-gamelift/test/my-game-build.zip
  packages/@aws-cdk/aws-gamelift/test/my-game-build/index.js
Labels: p2, beginning-contributor

#22330 feat(aws-cloudwatch): composite alarm actions suppression
  packages/@aws-cdk/aws-cloudwatch/README.md
  packages/@aws-cdk/aws-cloudwatch/lib/composite-alarm.ts
  packages/@aws-cdk/aws-cloudwatch/test/composite-alarm.integ.snapshot/CompositeAlarmIntegrationTest.assets.json
  packages/@aws-cdk/aws-cloudwatch/test/composite-alarm.integ.snapshot/CompositeAlarmIntegrationTest.template.json
  packages/@aws-cdk/aws-cloudwatch/test/composite-alarm.integ.snapshot/cdk.out
  packages/@aws-cdk/aws-cloudwatch/test/composite-alarm.integ.snapshot/integ.json
  packages/@aws-cdk/aws-cloudwatch/test/composite-alarm.integ.snapshot/manifest.json
  packages/@aws-cdk/aws-cloudwatch/test/composite-alarm.integ.snapshot/tree.json
  packages/@aws-cdk/aws-cloudwatch/test/composite-alarm.test.ts
  packages/@aws-cdk/aws-cloudwatch/test/integ.composite-alarm.ts
Labels: p2, @aws-cdk/aws-cloudwatch, beginning-contributor

#22327 fix(region-info): SSM service principals are incorrect in opt-in regions
  packages/@aws-cdk/aws-iam/test/principals.test.ts
  packages/@aws-cdk/region-info/lib/aws-entities.ts
  packages/@aws-cdk/region-info/lib/default.ts
  packages/@aws-cdk/region-info/test/__snapshots__/region-info.test.js.snap
  packages/@aws-cdk/region-info/test/default.test.ts
Labels: p2, contribution/core, pr-linter/exempt-integ-test

#22345 chore: options must not be mandatory
  packages/@aws-cdk/assertions/lib/template.ts
Labels: p2, contribution/core

#22346 chore(rds): update aurora and aurora-mysql engine versions
  packages/@aws-cdk/aws-rds/lib/cluster-engine.ts
Labels: p2, contribution/core

#22336 chore(prlint): cleanup old review comments for less noisy reviews
  tools/@aws-cdk/prlint/lint.ts
  tools/@aws-cdk/prlint/test/lint.test.ts
Labels: p2, contribution/core

#22350 chore: do not dismiss changes requested by aws-cdk-automation
  .mergify.yml
  tools/@aws-cdk/prlint/lint.ts
Labels: p2, contribution/core

#22135 feat(codepipeline-actions): add elastic beanstalk deploy action
  packages/@aws-cdk/aws-codepipeline-actions/README.md
  packages/@aws-cdk/aws-codepipeline-actions/lib/elastic-beanstalk/deploy-action.ts
  packages/@aws-cdk/aws-codepipeline-actions/lib/index.ts
  packages/@aws-cdk/aws-codepipeline-actions/package.json
  packages/@aws-cdk/aws-codepipeline-actions/test/assets/nodejs.zip
  packages/@aws-cdk/aws-codepipeline-actions/test/elastic-beanstalk/elastic-beanstalk-deploy-action.test.ts
  packages/@aws-cdk/aws-codepipeline-actions/test/integ.pipeilne-elastic-beanstalk-deploy.ts
  packages/@aws-cdk/aws-codepipeline-actions/test/pipeilne-elastic-beanstalk-deploy.integ.snapshot/aws-cdk-codepipeline-elastic-beanstalk-deploy.assets.json
  packages/@aws-cdk/aws-codepipeline-actions/test/pipeilne-elastic-beanstalk-deploy.integ.snapshot/aws-cdk-codepipeline-elastic-beanstalk-deploy.template.json
  packages/@aws-cdk/aws-codepipeline-actions/test/pipeilne-elastic-beanstalk-deploy.integ.snapshot/cdk.out
  packages/@aws-cdk/aws-codepipeline-actions/test/pipeilne-elastic-beanstalk-deploy.integ.snapshot/codepipelineelasticbeanstalkdeployDefaultTestDeployAssert785E452B.assets.json
  packages/@aws-cdk/aws-codepipeline-actions/test/pipeilne-elastic-beanstalk-deploy.integ.snapshot/codepipelineelasticbeanstalkdeployDefaultTestDeployAssert785E452B.template.json
  packages/@aws-cdk/aws-codepipeline-actions/test/pipeilne-elastic-beanstalk-deploy.integ.snapshot/integ.json
  packages/@aws-cdk/aws-codepipeline-actions/test/pipeilne-elastic-beanstalk-deploy.integ.snapshot/manifest.json
  packages/@aws-cdk/aws-codepipeline-actions/test/pipeilne-elastic-beanstalk-deploy.integ.snapshot/tree.json
Labels: p1, feature-request, effort/medium, contribution/core

#22337 feat: add `addMetadata()` method to `Stack`
  packages/@aws-cdk/core/lib/stack.ts
  packages/@aws-cdk/core/test/stack.test.ts
Labels: p2, contribution/core, pr-linter/exempt-readme, pr-linter/exempt-integ-test

#21373 fix(cli): large context causes E2BIG error during synthesis on Linux
  packages/@aws-cdk/core/lib/app.ts
  packages/@aws-cdk/core/test/app.test.ts
  packages/@aws-cdk/cx-api/lib/cxapi.ts
  packages/aws-cdk/lib/api/cxapp/exec.ts
  packages/aws-cdk/lib/commands/doctor.ts
  packages/aws-cdk/lib/notices.ts
  packages/aws-cdk/lib/tree.ts
  packages/aws-cdk/lib/util/objects.ts
  packages/aws-cdk/package.json
  packages/aws-cdk/test/tree.test.ts
  packages/aws-cdk/test/util/objects.test.ts
Labels: bug, p1, effort/medium, contribution/core, pr-linter/exempt-integ-test, pr-linter/cli-integ-tested

#22360 chore: use fixed package versions in integ tests
  packages/aws-cdk/test/integ/common/jest-test.bash
Labels: p2, contribution/core

#22355 docs(cli): update grammar and spelling mistakes in readme.md
  packages/aws-cdk/README.md
Labels: p2, beginning-contributor

#22365 chore: add integ-tests and integ-runner to ownership
  .github/workflows/issue-label-assign.yml
Labels: p2, contribution/core

#22378 fix(appsync): can not use Tokens in the name of a DataSource
  packages/@aws-cdk/aws-appsync/lib/data-source.ts
  packages/@aws-cdk/aws-appsync/test/appsync-none.integ.snapshot/apiDefaultTestDeployAssert018781F2.assets.json
  packages/@aws-cdk/aws-appsync/test/appsync-none.integ.snapshot/apiDefaultTestDeployAssert018781F2.template.json
  packages/@aws-cdk/aws-appsync/test/appsync-none.integ.snapshot/cdk.out
  packages/@aws-cdk/aws-appsync/test/appsync-none.integ.snapshot/integ.json
  packages/@aws-cdk/aws-appsync/test/appsync-none.integ.snapshot/manifest.json
  packages/@aws-cdk/aws-appsync/test/appsync-none.integ.snapshot/stack.assets.json
  packages/@aws-cdk/aws-appsync/test/appsync-none.integ.snapshot/stack.template.json
  packages/@aws-cdk/aws-appsync/test/appsync-none.integ.snapshot/tree.json
  packages/@aws-cdk/aws-appsync/test/appsync-none.test.ts
  packages/@aws-cdk/aws-appsync/test/appsync.none.graphql
  packages/@aws-cdk/aws-appsync/test/integ.appsync-none.ts
Labels: bug, p1, beginning-contributor

#22382 chore: version updates, including breaking changes in jsii
  package.json
  packages/@aws-cdk/aws-apigatewayv2-authorizers/package.json
  packages/@aws-cdk/aws-autoscaling/test/auto-scaling-group.test.ts
  packages/@aws-cdk/aws-certificatemanager/lambda-packages/dns_validated_certificate_handler/package.json
  packages/@aws-cdk/aws-cloudformation/package.json
  packages/@aws-cdk/aws-cloudfront/test/origin-groups.test.ts
  packages/@aws-cdk/aws-cloudfront/test/web-distribution.test.ts
  packages/@aws-cdk/aws-dynamodb/package.json
  packages/@aws-cdk/aws-ec2/lib/vpc.ts
  packages/@aws-cdk/aws-ec2/package.json
  packages/@aws-cdk/aws-ec2/test/vpc.test.ts
  packages/@aws-cdk/aws-ec2/test/vpn.test.ts
  packages/@aws-cdk/aws-eks/package.json
  packages/@aws-cdk/aws-iam/package.json
  packages/@aws-cdk/aws-lambda-nodejs/package.json
  packages/@aws-cdk/aws-lambda-nodejs/test/testtsconfig.json
  packages/@aws-cdk/aws-lambda-nodejs/test/util.test.ts
  packages/@aws-cdk/aws-lambda/package.json
  packages/@aws-cdk/aws-logs/package.json
  packages/@aws-cdk/aws-route53/package.json
  packages/@aws-cdk/aws-s3/package.json
  packages/@aws-cdk/aws-ses/package.json
  packages/@aws-cdk/cloudformation-diff/package.json
  packages/@aws-cdk/core/package.json
  packages/@aws-cdk/custom-resources/package.json
  packages/@aws-cdk/custom-resources/test/aws-custom-resource/aws-custom-resource.test.ts
  packages/@aws-cdk/custom-resources/test/aws-custom-resource/integ.aws-custom-resource-vpc.ts
  packages/@aws-cdk/integ-runner/THIRD_PARTY_LICENSES
  packages/@aws-cdk/integ-runner/package.json
  packages/@aws-cdk/integ-tests/package.json
  packages/@monocdk-experiment/assert/package.json
  packages/@monocdk-experiment/rewrite-imports/package.json
  packages/aws-cdk-lib/package.json
  packages/aws-cdk-migration/package.json
  packages/aws-cdk/THIRD_PARTY_LICENSES
  packages/aws-cdk/package.json
  packages/awslint/package.json
  packages/cdk-assets/package.json
  packages/cdk-cli-wrapper/package.json
  packages/cdk-dasm/package.json
  packages/monocdk/package.json
  tools/@aws-cdk/cdk-build-tools/lib/deprecated-symbols.ts
  tools/@aws-cdk/cdk-build-tools/package.json
  tools/@aws-cdk/cfn2ts/package.json
  tools/@aws-cdk/eslint-plugin/package.json
  tools/@aws-cdk/node-bundle/package.json
  tools/@aws-cdk/prlint/package.json
  tools/@aws-cdk/yarn-cling/package.json
  yarn.lock
Labels: p2, contribution/core

#22387 chore: v1 version updates, including breaking changes in jsii
  packages/@aws-cdk/aws-autoscaling/test/auto-scaling-group.test.ts
  packages/@aws-cdk/aws-cloudfront/test/origin-groups.test.ts
  packages/@aws-cdk/aws-cloudfront/test/web-distribution.test.ts
  packages/@aws-cdk/aws-lambda-nodejs/test/testtsconfig.json
  packages/@aws-cdk/aws-lambda-nodejs/test/util.test.ts
Labels: p2, contribution/core

#22388 chore(merge-back): 2.45.0
  CHANGELOG.v2.alpha.md
  CHANGELOG.v2.md
  version.v2.json
Labels: p2, pr/no-squash, auto-approve

#22269 chore: npm-check-updates && yarn upgrade
  package.json
  packages/@aws-cdk/aws-codepipeline-actions/package.json
  packages/@aws-cdk/aws-eks/package.json
  packages/@aws-cdk/aws-lambda-nodejs/package.json
  packages/@aws-cdk/aws-lambda/package.json
  packages/@aws-cdk/cloud-assembly-schema/package.json
  packages/@aws-cdk/core/package.json
  packages/@aws-cdk/cx-api/package.json
  packages/@aws-cdk/integ-runner/THIRD_PARTY_LICENSES
  packages/aws-cdk-lib/package.json
  packages/aws-cdk/THIRD_PARTY_LICENSES
  packages/aws-cdk/package.json
  packages/monocdk/package.json
  tools/@aws-cdk/cdk-build-tools/package.json
  tools/@aws-cdk/cdk-release/package.json
  tools/@aws-cdk/node-bundle/package.json
  tools/@aws-cdk/pkglint/package.json
  tools/@aws-cdk/prlint/package.json
  tools/@aws-cdk/yarn-cling/package.json
  yarn.lock
Labels: p2, dependencies, contribution/core, auto-approve

#22372 chore(integ-tests): missing link to integ-runner
  packages/@aws-cdk/integ-tests/README.md
Labels: p2, contribution/core

#22374 feat(synthetics): new runtime synthetics nodejs puppeteer 3 6
  packages/@aws-cdk/aws-synthetics/lib/runtime.ts
  packages/aws-cdk-lib/package.json
Labels: p2, pr-linter/exempt-readme, pr-linter/exempt-test, pr-linter/exempt-integ-test, beginning-contributor

#22393 fix: half-written asset zips can be uploaded if process is interrupted
  packages/@aws-cdk/core/lib/asset-staging.ts
  packages/@aws-cdk/core/test/staging.test.ts
  packages/aws-cdk/test/integ/cli/app/app.js
  packages/cdk-assets/lib/private/archive.ts
  packages/cdk-assets/lib/private/handlers/files.ts
  packages/cdk-assets/test/archive.test.ts
Labels: bug, p1, contribution/core, pr-linter/exempt-test, pr-linter/exempt-integ-test

#22400 chore(merge-back): 1.176.0
  CHANGELOG.md
  packages/aws-cdk/test/integ/common/jest-test.bash
  version.v1.json
Labels: p2, pr/no-squash, auto-approve

#22405 docs: Fix typo
  packages/@aws-cdk/aws-route53/README.md
Labels: p2, beginning-contributor

#22408 chore(config): AWS Config add new resource types
  packages/@aws-cdk/aws-config/lib/rule.ts
Labels: p2, @aws-cdk/aws-config, valued-contributor

#22411 chore: some integ tests fail because two synths have different output
  packages/aws-cdk/test/integ/cli/app/app.js
Labels: p2, contribution/core

#22396 fix(cli): state machine hotswap fails if the `DependsOn` change
  packages/aws-cdk/lib/api/hotswap/stepfunctions-state-machines.ts
  packages/aws-cdk/test/api/hotswap/state-machine-hotswap-deployments.test.ts
Labels: p2, contribution/core, pr-linter/exempt-integ-test, pr-linter/cli-integ-tested

#22328 fix(ecs): removed explicit addition of ecs deployment type when circuit breaker is enabled
  packages/@aws-cdk/aws-ecs-patterns/test/ec2/l3s.test.ts
  packages/@aws-cdk/aws-ecs-patterns/test/ec2/queue-processing-ecs-service.test.ts
  packages/@aws-cdk/aws-ecs-patterns/test/fargate/alb-fargate-service-https.integ.snapshot/aws-ecs-integ-alb-fg-https.template.json
  packages/@aws-cdk/aws-ecs-patterns/test/fargate/circuit-breaker-load-balanced-fargate-service.integ.snapshot/aws-ecs-integ-circuit-breaker.template.json
  packages/@aws-cdk/aws-ecs-patterns/test/fargate/circuit-breaker-load-balanced-fargate-service.integ.snapshot/tree.json
  packages/@aws-cdk/aws-ecs-patterns/test/fargate/circuit-breaker-queue-processing-fargate-service.integ.snapshot/aws-ecs-patterns-queue.template.json
  packages/@aws-cdk/aws-ecs-patterns/test/fargate/circuit-breaker-queue-processing-fargate-service.integ.snapshot/tree.json
  packages/@aws-cdk/aws-ecs-patterns/test/fargate/integ.alb-fargate-service-https.ts
  packages/@aws-cdk/aws-ecs-patterns/test/fargate/load-balanced-fargate-service.test.ts
  packages/@aws-cdk/aws-ecs-patterns/test/fargate/queue-processing-fargate-service.test.ts
  packages/@aws-cdk/aws-ecs/lib/base/base-service.ts
  packages/@aws-cdk/aws-ecs/test/ec2/ec2-service.test.ts
  packages/@aws-cdk/aws-ecs/test/external/external-service.test.ts
  packages/@aws-cdk/aws-ecs/test/fargate/fargate-service.test.ts
Labels: bug, p2, effort/small, beginning-contributor

#22414 fix(ec2): cannot deploy SecurityGroup with allowAllIpv6Outbound
  packages/@aws-cdk/aws-ec2/lib/security-group.ts
  packages/@aws-cdk/aws-ec2/test/instance.integ.snapshot/cdk.out
  packages/@aws-cdk/aws-ec2/test/instance.integ.snapshot/instancetestDefaultTestDeployAssert5516EAF1.assets.json
  packages/@aws-cdk/aws-ec2/test/instance.integ.snapshot/instancetestDefaultTestDeployAssert5516EAF1.template.json
  packages/@aws-cdk/aws-ec2/test/instance.integ.snapshot/integ-ec2-instance.assets.json
  packages/@aws-cdk/aws-ec2/test/instance.integ.snapshot/integ-ec2-instance.template.json
  packages/@aws-cdk/aws-ec2/test/instance.integ.snapshot/integ.json
  packages/@aws-cdk/aws-ec2/test/instance.integ.snapshot/manifest.json
  packages/@aws-cdk/aws-ec2/test/instance.integ.snapshot/tree.json
  packages/@aws-cdk/aws-ec2/test/integ.instance.ts
  packages/@aws-cdk/aws-ec2/test/security-group.test.ts
Labels: bug, p2, contribution/core

#22301 feat(aws-certificatemanager): Add ability to specify the certificate name
  packages/@aws-cdk/aws-certificatemanager/README.md
  packages/@aws-cdk/aws-certificatemanager/lib/certificate.ts
  packages/@aws-cdk/aws-certificatemanager/test/certificate-name.integ.snapshot/cdk.out
  packages/@aws-cdk/aws-certificatemanager/test/certificate-name.integ.snapshot/integ-certificate-name.assets.json
  packages/@aws-cdk/aws-certificatemanager/test/certificate-name.integ.snapshot/integ-certificate-name.template.json
  packages/@aws-cdk/aws-certificatemanager/test/certificate-name.integ.snapshot/integ.json
  packages/@aws-cdk/aws-certificatemanager/test/certificate-name.integ.snapshot/integtestDefaultTestDeployAssert24D5C536.assets.json
  packages/@aws-cdk/aws-certificatemanager/test/certificate-name.integ.snapshot/integtestDefaultTestDeployAssert24D5C536.template.json
  packages/@aws-cdk/aws-certificatemanager/test/certificate-name.integ.snapshot/manifest.json
  packages/@aws-cdk/aws-certificatemanager/test/certificate-name.integ.snapshot/tree.json
  packages/@aws-cdk/aws-certificatemanager/test/certificate.test.ts
  packages/@aws-cdk/aws-certificatemanager/test/integ.certificate-name.ts
  packages/@aws-cdk/aws-ecs-patterns/test/fargate/alb-fargate-service-https-idle-timeout.integ.snapshot/aws-ecs-integ-alb-fg-idletimeout.template.json
  packages/@aws-cdk/aws-ecs-patterns/test/fargate/alb-fargate-service-https.integ.snapshot/aws-ecs-integ-alb-fg-https.template.json
Labels: p2, repeat-contributor

#22363 feat(sqs): add enforceSSL property to enforce encryption of data in transit
  packages/@aws-cdk/aws-sqs/README.md
  packages/@aws-cdk/aws-sqs/lib/queue.ts
  packages/@aws-cdk/aws-sqs/test/integ.sqs.ts
  packages/@aws-cdk/aws-sqs/test/sqs.integ.snapshot/aws-cdk-sqs.assets.json
  packages/@aws-cdk/aws-sqs/test/sqs.integ.snapshot/aws-cdk-sqs.template.json
  packages/@aws-cdk/aws-sqs/test/sqs.integ.snapshot/manifest.json
  packages/@aws-cdk/aws-sqs/test/sqs.integ.snapshot/tree.json
  packages/@aws-cdk/aws-sqs/test/sqs.test.ts
Labels: p2, beginning-contributor

#22351 fix(aws-lambda-python): export poetry dependencies without hashes
  packages/@aws-cdk/aws-lambda-python/lib/bundling.ts
  packages/@aws-cdk/aws-lambda-python/lib/packaging.ts
  packages/@aws-cdk/aws-lambda-python/lib/types.ts
  packages/@aws-cdk/aws-lambda-python/test/bundling.test.ts
  packages/@aws-cdk/aws-lambda-python/test/function.poetry.integ.snapshot/asset.d47f7e6772bfdf47ecbc070ffe204baf53bacbfbf7814eb407bd8ea108c1c1bb.bundle/index.js
  packages/@aws-cdk/aws-lambda-python/test/function.poetry.integ.snapshot/integ-lambda-python-poetry.assets.json
  packages/@aws-cdk/aws-lambda-python/test/function.poetry.integ.snapshot/integ-lambda-python-poetry.template.json
  packages/@aws-cdk/aws-lambda-python/test/function.poetry.integ.snapshot/manifest.json
  packages/@aws-cdk/aws-lambda-python/test/function.poetry.integ.snapshot/poetryDefaultTestDeployAssertE9C9CB8F.assets.json
  packages/@aws-cdk/aws-lambda-python/test/function.poetry.integ.snapshot/poetryDefaultTestDeployAssertE9C9CB8F.template.json
  packages/@aws-cdk/aws-lambda-python/test/function.poetry.integ.snapshot/tree.json
  packages/@aws-cdk/aws-lambda-python/test/integ.function.poetry.ts
  packages/@aws-cdk/aws-lambda-python/test/packaging.test.ts
Labels: bug, p2, effort/small, beginning-contributor

#22118 fix(core): Custom Resource type length validation
  packages/@aws-cdk/aws-cloudformation/test/core-custom-resources.integ.snapshot/cdk.out
  packages/@aws-cdk/aws-cloudformation/test/core-custom-resources.integ.snapshot/custom-resource-test.assets.json
  packages/@aws-cdk/aws-cloudformation/test/core-custom-resources.integ.snapshot/custom-resource-test.template.json
  packages/@aws-cdk/aws-cloudformation/test/core-custom-resources.integ.snapshot/integ.json
  packages/@aws-cdk/aws-cloudformation/test/core-custom-resources.integ.snapshot/manifest.json
  packages/@aws-cdk/aws-cloudformation/test/core-custom-resources.integ.snapshot/tree.json
  packages/@aws-cdk/aws-cloudformation/test/integ.core-custom-resources.ts
  packages/@aws-cdk/core/lib/custom-resource.ts
  packages/@aws-cdk/core/test/custom-resource.test.ts
Labels: p2

#22404 feat(integ-tests): allow for user provided assertions stack
  packages/@aws-cdk/integ-tests/README.md
  packages/@aws-cdk/integ-tests/lib/assertions/private/deploy-assert.ts
  packages/@aws-cdk/integ-tests/lib/test-case.ts
  packages/@aws-cdk/integ-tests/test/assertions/deploy-assert.test.ts
  packages/@aws-cdk/integ-tests/test/assertions/sdk.test.ts
Labels: p2, feature-request, effort/small, pr-linter/exempt-integ-test, repeat-contributor

#22312 feat(aws-ec2): add metadata options support for launchTemplate construct
  packages/@aws-cdk/aws-ec2/README.md
  packages/@aws-cdk/aws-ec2/lib/launch-template.ts
  packages/@aws-cdk/aws-ec2/test/integ.launch-template.ts
  packages/@aws-cdk/aws-ec2/test/launch-template.integ.snapshot/LambdaTestDefaultTestDeployAssert1AF2B360.assets.json
  packages/@aws-cdk/aws-ec2/test/launch-template.integ.snapshot/LambdaTestDefaultTestDeployAssert1AF2B360.template.json
  packages/@aws-cdk/aws-ec2/test/launch-template.integ.snapshot/TestStack.assets.json
  packages/@aws-cdk/aws-ec2/test/launch-template.integ.snapshot/TestStack.template.json
  packages/@aws-cdk/aws-ec2/test/launch-template.integ.snapshot/aws-cdk-ec2-lt-metadata-1.assets.json
  packages/@aws-cdk/aws-ec2/test/launch-template.integ.snapshot/aws-cdk-ec2-lt-metadata-1.template.json
  packages/@aws-cdk/aws-ec2/test/launch-template.integ.snapshot/cdk.out
  packages/@aws-cdk/aws-ec2/test/launch-template.integ.snapshot/integ.json
  packages/@aws-cdk/aws-ec2/test/launch-template.integ.snapshot/manifest.json
  packages/@aws-cdk/aws-ec2/test/launch-template.integ.snapshot/tree.json
  packages/@aws-cdk/aws-ec2/test/launch-template.test.ts
Labels: p2, contribution/core

#21248 fix(core): asset bundling skipped when using --exclusively with custom stack name
  packages/@aws-cdk/core/lib/stack.ts
  packages/@aws-cdk/core/test/staging.test.ts
  packages/aws-cdk/README.md
  packages/aws-cdk/lib/api/cxapp/exec.ts
  packages/aws-cdk/lib/settings.ts
  packages/aws-cdk/test/settings.test.ts
Labels: bug, p1, effort/small, pr-linter/exempt-integ-test, pr-linter/cli-integ-tested

#22423 chore(prlint): should allow revert commits
  tools/@aws-cdk/prlint/lint.ts
Labels: p2, contribution/core

#22418 revert: "fix(ecs): removed explicit addition of ecs deployment type when circuit breaker is enabled (#22328)"
  packages/@aws-cdk/aws-ecs-patterns/test/ec2/l3s.test.ts
  packages/@aws-cdk/aws-ecs-patterns/test/ec2/queue-processing-ecs-service.test.ts
  packages/@aws-cdk/aws-ecs-patterns/test/fargate/alb-fargate-service-https.integ.snapshot/aws-ecs-integ-alb-fg-https.template.json
  packages/@aws-cdk/aws-ecs-patterns/test/fargate/circuit-breaker-load-balanced-fargate-service.integ.snapshot/aws-ecs-integ-circuit-breaker.template.json
  packages/@aws-cdk/aws-ecs-patterns/test/fargate/circuit-breaker-load-balanced-fargate-service.integ.snapshot/tree.json
  packages/@aws-cdk/aws-ecs-patterns/test/fargate/circuit-breaker-queue-processing-fargate-service.integ.snapshot/aws-ecs-patterns-queue.template.json
  packages/@aws-cdk/aws-ecs-patterns/test/fargate/circuit-breaker-queue-processing-fargate-service.integ.snapshot/tree.json
  packages/@aws-cdk/aws-ecs-patterns/test/fargate/integ.alb-fargate-service-https.ts
  packages/@aws-cdk/aws-ecs-patterns/test/fargate/load-balanced-fargate-service.test.ts
  packages/@aws-cdk/aws-ecs-patterns/test/fargate/queue-processing-fargate-service.test.ts
  packages/@aws-cdk/aws-ecs/lib/base/base-service.ts
  packages/@aws-cdk/aws-ecs/test/ec2/ec2-service.test.ts
  packages/@aws-cdk/aws-ecs/test/external/external-service.test.ts
  packages/@aws-cdk/aws-ecs/test/fargate/fargate-service.test.ts
Labels: p2, contribution/core

#22457 docs: Correct the code syntax
  docs/DESIGN_GUIDELINES.md
Labels: p2, contribution/core

#22375 feat(sns): topic name with `.fifo` suffix generated automatically
  packages/@aws-cdk/aws-sns/README.md
  packages/@aws-cdk/aws-sns/lib/topic.ts
  packages/@aws-cdk/aws-sns/package.json
  packages/@aws-cdk/aws-sns/test/integ.sns-fifo.no-name.ts
  packages/@aws-cdk/aws-sns/test/sns-fifo.no-name.integ.snapshot/SnsFifoNoNameTestDefaultTestDeployAssert931FC5EA.assets.json
  packages/@aws-cdk/aws-sns/test/sns-fifo.no-name.integ.snapshot/SnsFifoNoNameTestDefaultTestDeployAssert931FC5EA.template.json
  packages/@aws-cdk/aws-sns/test/sns-fifo.no-name.integ.snapshot/aws-cdk-sns-fifo-1.assets.json
  packages/@aws-cdk/aws-sns/test/sns-fifo.no-name.integ.snapshot/aws-cdk-sns-fifo-1.template.json
  packages/@aws-cdk/aws-sns/test/sns-fifo.no-name.integ.snapshot/cdk.out
  packages/@aws-cdk/aws-sns/test/sns-fifo.no-name.integ.snapshot/integ.json
  packages/@aws-cdk/aws-sns/test/sns-fifo.no-name.integ.snapshot/manifest.json
  packages/@aws-cdk/aws-sns/test/sns-fifo.no-name.integ.snapshot/tree.json
  packages/@aws-cdk/aws-sns/test/sns.test.ts
Labels: p2, beginning-contributor

#22460 chore(backup): plus-s3-BackupVaultEvents
  packages/@aws-cdk/aws-backup/lib/vault.ts
Labels: p2, valued-contributor

#22419 docs: fix default Security Policy TLS Version
  packages/@aws-cdk/aws-apigateway/lib/domain-name.ts
Labels: p2, beginning-contributor

#22368 fix(apigateway): cannot create an ApiKey with an imported RestApi
  packages/@aws-cdk/aws-apigateway/README.md
  packages/@aws-cdk/aws-apigateway/lib/api-key.ts
  packages/@aws-cdk/aws-apigateway/lib/restapi.ts
  packages/@aws-cdk/aws-apigateway/lib/stage.ts
  packages/@aws-cdk/aws-apigateway/test/api-key.test.ts
  packages/@aws-cdk/aws-apigateway/test/integ.restapi.ts
  packages/@aws-cdk/aws-apigateway/test/restapi.integ.snapshot/apigatewayrestapiDefaultTestDeployAssert6A9696A7.assets.json
  packages/@aws-cdk/aws-apigateway/test/restapi.integ.snapshot/cdk.out
  packages/@aws-cdk/aws-apigateway/test/restapi.integ.snapshot/integ.json
  packages/@aws-cdk/aws-apigateway/test/restapi.integ.snapshot/manifest.json
  packages/@aws-cdk/aws-apigateway/test/restapi.integ.snapshot/test-apigateway-restapi.assets.json
  packages/@aws-cdk/aws-apigateway/test/restapi.integ.snapshot/test-apigateway-restapi.template.json
  packages/@aws-cdk/aws-apigateway/test/restapi.integ.snapshot/tree.json
  packages/@aws-cdk/aws-apigateway/test/restapi.test.ts
  packages/@aws-cdk/aws-apigateway/test/stage.test.ts
Labels: contribution/core

#22349 feat(cloudfront-origins): allow setting a user defined origin id
  packages/@aws-cdk/aws-cloudfront-origins/test/http-origin.test.ts
  packages/@aws-cdk/aws-cloudfront-origins/test/load-balancer-origin.test.ts
  packages/@aws-cdk/aws-cloudfront-origins/test/origin-group.test.ts
  packages/@aws-cdk/aws-cloudfront-origins/test/rest-api-origin.test.ts
  packages/@aws-cdk/aws-cloudfront-origins/test/s3-origin.test.ts
  packages/@aws-cdk/aws-cloudfront/lib/distribution.ts
  packages/@aws-cdk/aws-cloudfront/lib/origin.ts
Labels: p1, feature-request, effort/medium, contribution/core, pr-linter/exempt-readme, pr-linter/exempt-integ-test

#22398 fix(lambda-python): commands run non-sequentially on Graviton when building container image
  packages/@aws-cdk/aws-lambda-python/lib/Dockerfile
Labels: bug, p1, effort/small, pr-linter/exempt-test, pr-linter/exempt-integ-test, beginning-contributor

#22270 chore: npm-check-updates && yarn upgrade
  package.json
  packages/@aws-cdk/aws-apigatewayv2-authorizers/package.json
  packages/@aws-cdk/aws-certificatemanager/lambda-packages/dns_validated_certificate_handler/package.json
  packages/@aws-cdk/aws-cloudformation/package.json
  packages/@aws-cdk/aws-codepipeline-actions/package.json
  packages/@aws-cdk/aws-dynamodb/package.json
  packages/@aws-cdk/aws-ec2/package.json
  packages/@aws-cdk/aws-eks/package.json
  packages/@aws-cdk/aws-iam/package.json
  packages/@aws-cdk/aws-lambda-nodejs/package.json
  packages/@aws-cdk/aws-lambda/package.json
  packages/@aws-cdk/aws-logs/package.json
  packages/@aws-cdk/aws-route53/package.json
  packages/@aws-cdk/aws-s3/package.json
  packages/@aws-cdk/aws-ses/package.json
  packages/@aws-cdk/cloud-assembly-schema/package.json
  packages/@aws-cdk/core/package.json
  packages/@aws-cdk/custom-resources/package.json
  packages/@aws-cdk/cx-api/package.json
  packages/@aws-cdk/integ-runner/THIRD_PARTY_LICENSES
  packages/aws-cdk-lib/package.json
  packages/aws-cdk/THIRD_PARTY_LICENSES
  packages/aws-cdk/package.json
  packages/awslint/package.json
  packages/cdk-dasm/package.json
  packages/monocdk/package.json
  tools/@aws-cdk/cdk-build-tools/package.json
  tools/@aws-cdk/cdk-release/package.json
  tools/@aws-cdk/cfn2ts/package.json
  tools/@aws-cdk/node-bundle/package.json
  tools/@aws-cdk/pkglint/package.json
  tools/@aws-cdk/prlint/package.json
  tools/@aws-cdk/yarn-cling/package.json
  yarn.lock
Labels: p2, dependencies, contribution/core, auto-approve

#21709 feat(ec2): adds persist option to user data on windows instances
  packages/@aws-cdk/aws-ec2/README.md
  packages/@aws-cdk/aws-ec2/lib/user-data.ts
  packages/@aws-cdk/aws-ec2/test/integ.userdata.ts
  packages/@aws-cdk/aws-ec2/test/userdata.integ.snapshot/cdk.out
  packages/@aws-cdk/aws-ec2/test/userdata.integ.snapshot/integ-userdata.assets.json
  packages/@aws-cdk/aws-ec2/test/userdata.integ.snapshot/integ-userdata.template.json
  packages/@aws-cdk/aws-ec2/test/userdata.integ.snapshot/manifest.json
  packages/@aws-cdk/aws-ec2/test/userdata.integ.snapshot/tree.json
  packages/@aws-cdk/aws-ec2/test/userdata.test.ts
Labels: p2, @aws-cdk/aws-ec2

#22481 chore(ec2): one type of missing vpc endpoint per service
  packages/@aws-cdk/aws-ec2/lib/vpc-endpoint.ts
Labels: p2, valued-contributor

#22492 chore(merge-back): 2.46.0
  CHANGELOG.v2.alpha.md
  CHANGELOG.v2.md
  version.v2.json
Labels: p2, pr/no-squash, auto-approve

#21906 fix(iam): missing validation for actions added post instantiation of a policy statement
  packages/@aws-cdk/aws-iam/lib/policy-statement.ts
  packages/@aws-cdk/aws-iam/test/policy-document.test.ts
  packages/@aws-cdk/aws-iam/test/policy-statement.test.ts
Labels: bug, p2, @aws-cdk/aws-iam, effort/small, pr-linter/exempt-integ-test

#22496 chore(merge-back): 1.177.0
  CHANGELOG.md
  version.v1.json
Labels: p2, pr/no-squash, auto-approve

#22472 fix(stepfunctions): JsonPath.listAt does not accept strings starting with `$[`
  packages/@aws-cdk/aws-stepfunctions-tasks/package.json
  packages/@aws-cdk/aws-stepfunctions-tasks/test/dynamodb/integ.stringset-after-parallel.ts
  packages/@aws-cdk/aws-stepfunctions-tasks/test/dynamodb/stringset-after-parallel.integ.snapshot/StringSetAfterParallelDefaultTestDeployAssert649ABBB9.assets.json
  packages/@aws-cdk/aws-stepfunctions-tasks/test/dynamodb/stringset-after-parallel.integ.snapshot/StringSetAfterParallelDefaultTestDeployAssert649ABBB9.template.json
  packages/@aws-cdk/aws-stepfunctions-tasks/test/dynamodb/stringset-after-parallel.integ.snapshot/cdk.out
  packages/@aws-cdk/aws-stepfunctions-tasks/test/dynamodb/stringset-after-parallel.integ.snapshot/integ.json
  packages/@aws-cdk/aws-stepfunctions-tasks/test/dynamodb/stringset-after-parallel.integ.snapshot/manifest.json
  packages/@aws-cdk/aws-stepfunctions-tasks/test/dynamodb/stringset-after-parallel.integ.snapshot/stringset-after-parallel.assets.json
  packages/@aws-cdk/aws-stepfunctions-tasks/test/dynamodb/stringset-after-parallel.integ.snapshot/stringset-after-parallel.template.json
  packages/@aws-cdk/aws-stepfunctions-tasks/test/dynamodb/stringset-after-parallel.integ.snapshot/tree.json
  packages/@aws-cdk/aws-stepfunctions/lib/fields.ts
  packages/@aws-cdk/aws-stepfunctions/package.json
  packages/@aws-cdk/aws-stepfunctions/test/fields.test.ts
  packages/@aws-cdk/aws-stepfunctions/test/integ.listAt-after-parallel.ts
  packages/@aws-cdk/aws-stepfunctions/test/listAt-after-parallel.integ.snapshot/ListAtAfterParallelDefaultTestDeployAssert1589F6AD.assets.json
  packages/@aws-cdk/aws-stepfunctions/test/listAt-after-parallel.integ.snapshot/ListAtAfterParallelDefaultTestDeployAssert1589F6AD.template.json
  packages/@aws-cdk/aws-stepfunctions/test/listAt-after-parallel.integ.snapshot/cdk.out
  packages/@aws-cdk/aws-stepfunctions/test/listAt-after-parallel.integ.snapshot/integ.json
  packages/@aws-cdk/aws-stepfunctions/test/listAt-after-parallel.integ.snapshot/listAt-after-parallel.assets.json
  packages/@aws-cdk/aws-stepfunctions/test/listAt-after-parallel.integ.snapshot/listAt-after-parallel.template.json
  packages/@aws-cdk/aws-stepfunctions/test/listAt-after-parallel.integ.snapshot/manifest.json
  packages/@aws-cdk/aws-stepfunctions/test/listAt-after-parallel.integ.snapshot/tree.json
Labels: bug, p1, repeat-contributor

#22499 feat(redshift): support enhanced vpc routing when creating redshift cluster
  packages/@aws-cdk/aws-redshift/README.md
  packages/@aws-cdk/aws-redshift/lib/cluster.ts
  packages/@aws-cdk/aws-redshift/test/cluster-enhancedvpcrouting.integ.snapshot/EnhancedVpcRoutingDefaultTestDeployAssert10B513A1.assets.json
  packages/@aws-cdk/aws-redshift/test/cluster-enhancedvpcrouting.integ.snapshot/EnhancedVpcRoutingDefaultTestDeployAssert10B513A1.template.json
  packages/@aws-cdk/aws-redshift/test/cluster-enhancedvpcrouting.integ.snapshot/cdk.out
  packages/@aws-cdk/aws-redshift/test/cluster-enhancedvpcrouting.integ.snapshot/integ.json
  packages/@aws-cdk/aws-redshift/test/cluster-enhancedvpcrouting.integ.snapshot/manifest.json
  packages/@aws-cdk/aws-redshift/test/cluster-enhancedvpcrouting.integ.snapshot/redshift-enhancedvpcrouting-integ.assets.json
  packages/@aws-cdk/aws-redshift/test/cluster-enhancedvpcrouting.integ.snapshot/redshift-enhancedvpcrouting-integ.template.json
  packages/@aws-cdk/aws-redshift/test/cluster-enhancedvpcrouting.integ.snapshot/tree.json
  packages/@aws-cdk/aws-redshift/test/integ.cluster-enhancedvpcrouting.ts
Labels: p2, beginning-contributor

#22463 feat(apigateway): support multi-level paths for custom domains
  packages/@aws-cdk/aws-apigateway/README.md
  packages/@aws-cdk/aws-apigateway/lib/domain-name.ts
  packages/@aws-cdk/aws-apigateway/package.json
  packages/@aws-cdk/aws-apigateway/test/domain-name.integ.snapshot/asset.456da4984f762c1c25e94bd5f2df6758d2b0884d0dae8ca59bb8f4e3de7c2136.bundle/index.js
  packages/@aws-cdk/aws-apigateway/test/domain-name.integ.snapshot/cdk.out
  packages/@aws-cdk/aws-apigateway/test/domain-name.integ.snapshot/domainnamemappingtestDefaultTestDeployAssert4FFC8047.assets.json
  packages/@aws-cdk/aws-apigateway/test/domain-name.integ.snapshot/domainnamemappingtestDefaultTestDeployAssert4FFC8047.template.json
  packages/@aws-cdk/aws-apigateway/test/domain-name.integ.snapshot/integ-apigw-domain-name-mapping.assets.json
  packages/@aws-cdk/aws-apigateway/test/domain-name.integ.snapshot/integ-apigw-domain-name-mapping.template.json
  packages/@aws-cdk/aws-apigateway/test/domain-name.integ.snapshot/integ.json
  packages/@aws-cdk/aws-apigateway/test/domain-name.integ.snapshot/manifest.json
  packages/@aws-cdk/aws-apigateway/test/domain-name.integ.snapshot/tree.json
  packages/@aws-cdk/aws-apigateway/test/domains.test.ts
  packages/@aws-cdk/aws-apigateway/test/integ.domain-name.ts
  packages/@aws-cdk/integ-runner/lib/runner/runner-base.ts
Labels: p1, feature-request, effort/medium, contribution/core

#22540 chore(api-gateway): Fix typo in LambdaAuthorizerProps documentation.
  packages/@aws-cdk/aws-apigateway/lib/authorizers/lambda.ts
Labels: p2, beginning-contributor

#22092 chore(applicationautoscaling): add neptune as an option for ServiceNamespaces
  packages/@aws-cdk/aws-applicationautoscaling/lib/scalable-target.ts
  packages/@aws-cdk/aws-applicationautoscaling/test/scalable-target.test.ts
Labels: p2

#21594 fix(config): Creating multiple rules from the same lambda
  packages/@aws-cdk/aws-config/lib/rule.ts
  packages/@aws-cdk/aws-config/test/integ.rule.lit.ts
  packages/@aws-cdk/aws-config/test/integ.scoped-rule.ts
  packages/@aws-cdk/aws-config/test/rule.lit.integ.snapshot/aws-cdk-config-rule-integ.assets.json
  packages/@aws-cdk/aws-config/test/rule.lit.integ.snapshot/aws-cdk-config-rule-integ.template.json
  packages/@aws-cdk/aws-config/test/rule.lit.integ.snapshot/manifest.json
  packages/@aws-cdk/aws-config/test/rule.lit.integ.snapshot/tree.json
  packages/@aws-cdk/aws-config/test/rule.test.ts
  packages/@aws-cdk/aws-config/test/scoped-rule.integ.snapshot/aws-cdk-config-rule-scoped-integ.assets.json
  packages/@aws-cdk/aws-config/test/scoped-rule.integ.snapshot/aws-cdk-config-rule-scoped-integ.template.json
  packages/@aws-cdk/aws-config/test/scoped-rule.integ.snapshot/manifest.json
  packages/@aws-cdk/aws-config/test/scoped-rule.integ.snapshot/tree.json
Labels: bug, p1, effort/medium, @aws-cdk/aws-config

#22555 chore(prlint): add pagination to listFiles in PR
  tools/@aws-cdk/prlint/lint.ts
  tools/@aws-cdk/prlint/test/lint.test.ts
Labels: p2, beginning-contributor

#22512 fix(lambda-python): root-owned cache items not cleaned up after install
  packages/@aws-cdk/aws-lambda-python/lib/Dockerfile
  packages/@aws-cdk/aws-lambda-python/test/function.arm64.integ.snapshot/asset.3074b79e05e7b98930b6449e01baa3e68b32ecff86328933c2542f7b7fe6fdac.bundle/index.js
  packages/@aws-cdk/aws-lambda-python/test/function.arm64.integ.snapshot/cdk.out
  packages/@aws-cdk/aws-lambda-python/test/function.arm64.integ.snapshot/integ-lambda-python-arm64.assets.json
  packages/@aws-cdk/aws-lambda-python/test/function.arm64.integ.snapshot/integ-lambda-python-arm64.template.json
  packages/@aws-cdk/aws-lambda-python/test/function.arm64.integ.snapshot/integ.json
  packages/@aws-cdk/aws-lambda-python/test/function.arm64.integ.snapshot/lambdapythonarm64DefaultTestDeployAssertAB537F34.assets.json
  packages/@aws-cdk/aws-lambda-python/test/function.arm64.integ.snapshot/lambdapythonarm64DefaultTestDeployAssertAB537F34.template.json
  packages/@aws-cdk/aws-lambda-python/test/function.arm64.integ.snapshot/manifest.json
  packages/@aws-cdk/aws-lambda-python/test/function.arm64.integ.snapshot/tree.json
  packages/@aws-cdk/aws-lambda-python/test/integ.function.arm64.ts
  packages/@aws-cdk/aws-lambda-python/test/lambda-handler-arm64/handler/index.py
  packages/@aws-cdk/aws-lambda-python/test/lambda-handler-arm64/layer/requirements.txt
  packages/@aws-cdk/aws-lambda-python/test/packaging.test.ts
Labels: p2, beginning-contributor

#22524 fix(cloudwatch): remove region from dashboard ARN
  packages/@aws-cdk/aws-cloudwatch/lib/dashboard.ts
  packages/@aws-cdk/aws-cloudwatch/test/dashboard.integ.snapshot/DashboardIntegrationTestDefaultTestDeployAssert5BE38902.assets.json
  packages/@aws-cdk/aws-cloudwatch/test/dashboard.integ.snapshot/DashboardIntegrationTestDefaultTestDeployAssert5BE38902.template.json
  packages/@aws-cdk/aws-cloudwatch/test/dashboard.integ.snapshot/DashboardIntegrationTestStack.assets.json
  packages/@aws-cdk/aws-cloudwatch/test/dashboard.integ.snapshot/DashboardIntegrationTestStack.template.json
  packages/@aws-cdk/aws-cloudwatch/test/dashboard.integ.snapshot/cdk.out
  packages/@aws-cdk/aws-cloudwatch/test/dashboard.integ.snapshot/integ.json
  packages/@aws-cdk/aws-cloudwatch/test/dashboard.integ.snapshot/manifest.json
  packages/@aws-cdk/aws-cloudwatch/test/dashboard.integ.snapshot/tree.json
  packages/@aws-cdk/aws-cloudwatch/test/dashboard.test.ts
  packages/@aws-cdk/aws-cloudwatch/test/integ.dashboard.ts
Labels: p2, beginning-contributor

#22466 feat(elbv2): add dropInvalidHeaderFields for elbv2
  packages/@aws-cdk/aws-elasticloadbalancingv2/lib/alb/application-load-balancer.ts
  packages/@aws-cdk/aws-elasticloadbalancingv2/test/alb/load-balancer.test.ts
Labels: p2, pr-linter/exempt-readme, pr-linter/exempt-integ-test, beginning-contributor

#22558 chore(ec2): add email-smtp interface endpoint
  packages/@aws-cdk/aws-ec2/lib/vpc-endpoint.ts
  packages/@aws-cdk/aws-ec2/package.json
Labels: p2, beginning-contributor

#22429 fix(integ-runner): Fix call to spawnSync for hooks commands
  packages/@aws-cdk/integ-runner/lib/runner/integ-test-runner.ts
  packages/@aws-cdk/integ-runner/lib/utils.ts
  packages/@aws-cdk/integ-runner/test/runner/integ-test-runner.test.ts
  packages/@aws-cdk/integ-runner/test/test-data/cdk-integ.out.test-with-snapshot-assets/integ.json
Labels: p2, pr-linter/exempt-integ-test, repeat-contributor

#22554 fix(codeguruprofiler): incorrect profiling group name is returned when using importing
  packages/@aws-cdk/aws-codeguruprofiler/lib/profiling-group.ts
  packages/@aws-cdk/aws-codeguruprofiler/package.json
  packages/@aws-cdk/aws-codeguruprofiler/test/integ.profiler-group-import-functions.ts
  packages/@aws-cdk/aws-codeguruprofiler/test/profiler-group-import-functions.integ.snapshot/ProfilingGroupTestStack.assets.json
  packages/@aws-cdk/aws-codeguruprofiler/test/profiler-group-import-functions.integ.snapshot/ProfilingGroupTestStack.template.json
  packages/@aws-cdk/aws-codeguruprofiler/test/profiler-group-import-functions.integ.snapshot/asset.b54b99043c35bd080b9d9d1afce31e3541cf15b679799ba980ed40c837dcb03b.bundle/index.js
  packages/@aws-cdk/aws-codeguruprofiler/test/profiler-group-import-functions.integ.snapshot/cdk.out
  packages/@aws-cdk/aws-codeguruprofiler/test/profiler-group-import-functions.integ.snapshot/integ.json
  packages/@aws-cdk/aws-codeguruprofiler/test/profiler-group-import-functions.integ.snapshot/manifest.json
  packages/@aws-cdk/aws-codeguruprofiler/test/profiler-group-import-functions.integ.snapshot/testDefaultTestDeployAssert4D02624A.assets.json
  packages/@aws-cdk/aws-codeguruprofiler/test/profiler-group-import-functions.integ.snapshot/testDefaultTestDeployAssert4D02624A.template.json
  packages/@aws-cdk/aws-codeguruprofiler/test/profiler-group-import-functions.integ.snapshot/tree.json
  packages/@aws-cdk/aws-codeguruprofiler/test/profiling-group.test.ts
Labels: bug, p2, effort/small, beginning-contributor

#22339 fix(cli): hotswap deploy fails on multiple CfnEvaluationException
  packages/aws-cdk/lib/api/hotswap-deployments.ts
  packages/aws-cdk/test/api/hotswap/hotswap-deployments.test.ts
Labels: bug, p2, pr-linter/exempt-integ-test, valued-contributor, pr-linter/cli-integ-tested

#22567 fix: breaking change to deployment config props
  packages/@aws-cdk/aws-codedeploy/lib/base-deployment-config.ts
  packages/@aws-cdk/aws-codedeploy/lib/ecs/deployment-config.ts
  packages/@aws-cdk/aws-codedeploy/lib/lambda/deployment-config.ts
  packages/@aws-cdk/aws-codedeploy/lib/server/deployment-config.ts
  packages/@aws-cdk/aws-codedeploy/lib/utils.ts
Labels: bug, p0, effort/small, contribution/core, pr-linter/exempt-test, pr-linter/exempt-integ-test

#22577 chore(release): 1.178.0
  .github/workflows/auto-approve.yml
  CHANGELOG.md
  package.json
  packages/@aws-cdk/aws-apigatewayv2-authorizers/package.json
  packages/@aws-cdk/aws-certificatemanager/lambda-packages/dns_validated_certificate_handler/package.json
  packages/@aws-cdk/aws-cloudformation/package.json
  packages/@aws-cdk/aws-dynamodb/package.json
  packages/@aws-cdk/aws-ec2/package.json
  packages/@aws-cdk/aws-eks/package.json
  packages/@aws-cdk/aws-iam/package.json
  packages/@aws-cdk/aws-lambda-nodejs/package.json
  packages/@aws-cdk/aws-lambda/package.json
  packages/@aws-cdk/aws-logs/package.json
  packages/@aws-cdk/aws-route53/package.json
  packages/@aws-cdk/aws-s3/package.json
  packages/@aws-cdk/aws-ses/package.json
  packages/@aws-cdk/core/package.json
  packages/@aws-cdk/custom-resources/package.json
  packages/@aws-cdk/integ-runner/THIRD_PARTY_LICENSES
  packages/@aws-cdk/lambda-layer-awscli/layer/requirements.txt
  packages/aws-cdk-lib/package.json
  packages/aws-cdk/THIRD_PARTY_LICENSES
  packages/aws-cdk/package.json
  tools/@aws-cdk/node-bundle/package.json
  tools/@aws-cdk/prlint/package.json
  version.v1.json
  yarn.lock
Labels: p2, pr/no-squash

#22587 chore(merge-back): 1.178.0
  CHANGELOG.md
  version.v1.json
Labels: p2, pr/no-squash, auto-approve

#22586 docs(acm): Fix typo in ACM documentation.
  packages/@aws-cdk/aws-certificatemanager/README.md
Labels: p2, beginning-contributor

#22590 chore(aws-eks): changed instanceType to instanceTypes in addNodegroupCapacity functions
  packages/@aws-cdk/aws-eks/test/integ.eks-cluster.ts
Labels: bug, p2, effort/small, beginning-contributor

#22598 chore(rds): Latest version available
  packages/@aws-cdk/aws-rds/lib/instance-engine.ts
Labels: p2, beginning-contributor

#22597 docs: fix simple typo in aws-ec2 module
  packages/@aws-cdk/aws-ec2/lib/vpc.ts
Labels: p2, beginning-contributor

#22591 fix(apigateway): relax access log format check to allow either requestId or extendedRequestId
  packages/@aws-cdk/aws-apigateway/README.md
  packages/@aws-cdk/aws-apigateway/lib/stage.ts
  packages/@aws-cdk/aws-apigateway/test/stage.test.ts
Labels: p2, contribution/core, pr-linter/exempt-integ-test

#22595 docs: adds comments about 8vCpu and 16vCpu options for Fargate services in @aws-cdk/aws-ecs-patterns
  packages/@aws-cdk/aws-ecs-patterns/lib/base/fargate-service-base.ts
  packages/@aws-cdk/aws-ecs-patterns/test/fargate/scheduled-fargate-task.test.ts
Labels: p2, beginning-contributor

#22611 docs(ecs): typos in README about AWS ECS Anywhere Launch Type
  packages/@aws-cdk/aws-ecs/README.md
Labels: p2, beginning-contributor

#22630 chore(lambda-python): remove arm integ tests
  packages/@aws-cdk/aws-lambda-python/test/function.arm64.integ.snapshot/asset.3074b79e05e7b98930b6449e01baa3e68b32ecff86328933c2542f7b7fe6fdac.bundle/index.js
  packages/@aws-cdk/aws-lambda-python/test/function.arm64.integ.snapshot/cdk.out
  packages/@aws-cdk/aws-lambda-python/test/function.arm64.integ.snapshot/integ-lambda-python-arm64.assets.json
  packages/@aws-cdk/aws-lambda-python/test/function.arm64.integ.snapshot/integ-lambda-python-arm64.template.json
  packages/@aws-cdk/aws-lambda-python/test/function.arm64.integ.snapshot/integ.json
  packages/@aws-cdk/aws-lambda-python/test/function.arm64.integ.snapshot/lambdapythonarm64DefaultTestDeployAssertAB537F34.assets.json
  packages/@aws-cdk/aws-lambda-python/test/function.arm64.integ.snapshot/lambdapythonarm64DefaultTestDeployAssertAB537F34.template.json
  packages/@aws-cdk/aws-lambda-python/test/function.arm64.integ.snapshot/manifest.json
  packages/@aws-cdk/aws-lambda-python/test/function.arm64.integ.snapshot/tree.json
  packages/@aws-cdk/aws-lambda-python/test/integ.function.arm64.ts
  packages/@aws-cdk/aws-lambda-python/test/lambda-handler-arm64/handler/index.py
  packages/@aws-cdk/aws-lambda-python/test/lambda-handler-arm64/layer/requirements.txt
Labels: p2, contribution/core

#22613 refactor(ec2): fix endpoint comment style
  packages/@aws-cdk/aws-ec2/lib/vpc-endpoint.ts
  packages/@aws-cdk/aws-ec2/package.json
Labels: p2, @aws-cdk/aws-ec2, effort/small, admired-contributor

#22633 docs(apigateway): add single quotes to `api.addGatewayResponse` example code
  packages/@aws-cdk/aws-apigateway/README.md
Labels: p2, beginning-contributor

#22618 fix(ssm): `StringParameter.fromSecureStringParameterAttributes` not working without version
  packages/@aws-cdk/aws-ssm/README.md
  packages/@aws-cdk/aws-ssm/lib/parameter.ts
  packages/@aws-cdk/aws-ssm/test/integ.parameter-store-string.ts
  packages/@aws-cdk/aws-ssm/test/parameter-store-string.integ.snapshot/asset.b54b99043c35bd080b9d9d1afce31e3541cf15b679799ba980ed40c837dcb03b.bundle/index.js
  packages/@aws-cdk/aws-ssm/test/parameter-store-string.integ.snapshot/cdk.out
  packages/@aws-cdk/aws-ssm/test/parameter-store-string.integ.snapshot/integ.json
  packages/@aws-cdk/aws-ssm/test/parameter-store-string.integ.snapshot/manifest.json
  packages/@aws-cdk/aws-ssm/test/parameter-store-string.integ.snapshot/sspms-cleanup.assets.json
  packages/@aws-cdk/aws-ssm/test/parameter-store-string.integ.snapshot/sspms-cleanup.template.json
  packages/@aws-cdk/aws-ssm/test/parameter-store-string.integ.snapshot/sspms-creating.assets.json
  packages/@aws-cdk/aws-ssm/test/parameter-store-string.integ.snapshot/sspms-creating.template.json
  packages/@aws-cdk/aws-ssm/test/parameter-store-string.integ.snapshot/sspms-using.assets.json
  packages/@aws-cdk/aws-ssm/test/parameter-store-string.integ.snapshot/sspms-using.template.json
  packages/@aws-cdk/aws-ssm/test/parameter-store-string.integ.snapshot/tree.json
  packages/@aws-cdk/aws-ssm/test/parameter-store-string.lit.integ.snapshot/cdk.out
  packages/@aws-cdk/aws-ssm/test/parameter-store-string.lit.integ.snapshot/integ.json
  packages/@aws-cdk/aws-ssm/test/parameter-store-string.lit.integ.snapshot/manifest.json
  packages/@aws-cdk/aws-ssm/test/parameter-store-string.lit.integ.snapshot/sspms-creating.template.json
  packages/@aws-cdk/aws-ssm/test/parameter-store-string.lit.integ.snapshot/sspms-using.template.json
  packages/@aws-cdk/aws-ssm/test/parameter-store-string.lit.integ.snapshot/tree.json
  packages/@aws-cdk/aws-ssm/test/parameter.test.ts
Labels: p2, contribution/core

#22637 refactor(apigateway): Enclose getaway response parameters within single quotes
  packages/@aws-cdk/aws-apigateway/README.md
  packages/@aws-cdk/aws-apigateway/lib/gateway-response.ts
  packages/@aws-cdk/aws-apigateway/lib/util.ts
  packages/@aws-cdk/aws-apigateway/test/gateway-response.test.ts
Labels: p2, beginning-contributor

#22649 feat(cfnspec): cloudformation spec v94.0.0
  packages/@aws-cdk/cfnspec/CHANGELOG.md
  packages/@aws-cdk/cfnspec/spec-source/specification/000_cfn/000_official/000_AWS_ACMPCA.json
  packages/@aws-cdk/cfnspec/spec-source/specification/000_cfn/000_official/000_AWS_ApiGatewayV2.json
  packages/@aws-cdk/cfnspec/spec-source/specification/000_cfn/000_official/000_AWS_Cognito.json
  packages/@aws-cdk/cfnspec/spec-source/specification/000_cfn/000_official/000_AWS_EC2.json
  packages/@aws-cdk/cfnspec/spec-source/specification/000_cfn/000_official/000_AWS_ECS.json
  packages/@aws-cdk/cfnspec/spec-source/specification/000_cfn/000_official/000_AWS_FSx.json
  packages/@aws-cdk/cfnspec/spec-source/specification/000_cfn/000_official/000_AWS_IoT.json
Labels: p2, pr-linter/exempt-test, auto-approve, pr-linter/exempt-integ-test

#22648 feat(cfnspec): cloudformation spec v94.0.0
  packages/@aws-cdk/cfnspec/CHANGELOG.md
  packages/@aws-cdk/cfnspec/spec-source/specification/000_cfn/000_official/000_AWS_ACMPCA.json
  packages/@aws-cdk/cfnspec/spec-source/specification/000_cfn/000_official/000_AWS_ApiGatewayV2.json
  packages/@aws-cdk/cfnspec/spec-source/specification/000_cfn/000_official/000_AWS_Cognito.json
  packages/@aws-cdk/cfnspec/spec-source/specification/000_cfn/000_official/000_AWS_EC2.json
  packages/@aws-cdk/cfnspec/spec-source/specification/000_cfn/000_official/000_AWS_ECS.json
  packages/@aws-cdk/cfnspec/spec-source/specification/000_cfn/000_official/000_AWS_FSx.json
  packages/@aws-cdk/cfnspec/spec-source/specification/000_cfn/000_official/000_AWS_IoT.json
Labels: p2, pr-linter/exempt-test, auto-approve, pr-linter/exempt-integ-test

#22579 feat(cli): allow disabling parallel asset publishing
  packages/aws-cdk/lib/api/cloudformation-deployments.ts
  packages/aws-cdk/lib/api/deploy-stack.ts
  packages/aws-cdk/lib/cdk-toolkit.ts
  packages/aws-cdk/lib/cli.ts
  packages/aws-cdk/lib/settings.ts
  packages/aws-cdk/lib/util/asset-publishing.ts
  packages/aws-cdk/test/api/cloudformation-deployments.test.ts
  packages/aws-cdk/test/cdk-toolkit.test.ts
  packages/aws-cdk/test/util.ts
Labels: p2, contribution/core, pr-linter/exempt-readme, pr-linter/exempt-test, pr-linter/exempt-integ-test, pr-linter/cli-integ-tested

#22652 chore: npm-check-updates && yarn upgrade
  package.json
  packages/@aws-cdk/aws-eks/package.json
  packages/@aws-cdk/aws-lambda-nodejs/package.json
  packages/@aws-cdk/cfnspec/package.json
  packages/@aws-cdk/integ-runner/THIRD_PARTY_LICENSES
  packages/@aws-cdk/integ-runner/package.json
  packages/aws-cdk-lib/package.json
  packages/aws-cdk/THIRD_PARTY_LICENSES
  packages/aws-cdk/package.json
  packages/awslint/package.json
  packages/cdk-dasm/package.json
  tools/@aws-cdk/cdk-build-tools/package.json
  tools/@aws-cdk/cfn2ts/package.json
  tools/@aws-cdk/node-bundle/package.json
  yarn.lock
Labels: p2, dependencies, contribution/core, auto-approve

#22653 chore: npm-check-updates && yarn upgrade
  package.json
  packages/@aws-cdk/aws-eks/package.json
  packages/@aws-cdk/aws-lambda-nodejs/package.json
  packages/@aws-cdk/cfnspec/package.json
  packages/@aws-cdk/integ-runner/THIRD_PARTY_LICENSES
  packages/@aws-cdk/integ-runner/package.json
  packages/aws-cdk-lib/package.json
  packages/aws-cdk/THIRD_PARTY_LICENSES
  packages/aws-cdk/package.json
  packages/awslint/package.json
  packages/cdk-dasm/package.json
  tools/@aws-cdk/cdk-build-tools/package.json
  tools/@aws-cdk/cfn2ts/package.json
  tools/@aws-cdk/node-bundle/package.json
  yarn.lock
Labels: p2, dependencies, contribution/core, auto-approve

#22646 docs(ecs): fixes rosetta extraction errors in the README file
  packages/@aws-cdk/aws-ecs/README.md
  packages/@aws-cdk/aws-ecs/rosetta/default.ts-fixture
Labels: p2, repeat-contributor

#22458 feat(ec2): Vpc supports allocating CIDR from AWS IPAM
  packages/@aws-cdk/aws-apprunner/README.md
  packages/@aws-cdk/aws-apprunner/test/integ.service-vpc-connector.ts
  packages/@aws-cdk/aws-apprunner/test/service.test.ts
  packages/@aws-cdk/aws-apprunner/test/vpc-connector.test.ts
  packages/@aws-cdk/aws-ec2/README.md
  packages/@aws-cdk/aws-ec2/lib/cidr-splits.ts
  packages/@aws-cdk/aws-ec2/lib/index.ts
  packages/@aws-cdk/aws-ec2/lib/ip-addresses.ts
  packages/@aws-cdk/aws-ec2/lib/vpc.ts
  packages/@aws-cdk/aws-ec2/test/cidr-splits.test.ts
  packages/@aws-cdk/aws-ec2/test/integ.reserved-private-subnet.ts
  packages/@aws-cdk/aws-ec2/test/integ.vpc-ipam.ts
  packages/@aws-cdk/aws-ec2/test/integ.vpn-pre-shared-key-token.ts
  packages/@aws-cdk/aws-ec2/test/ip-addresses.test.ts
  packages/@aws-cdk/aws-ec2/test/vpc-ipam.integ.snapshot/VpcIpamDefaultTestDeployAssertB1CA1C3A.assets.json
  packages/@aws-cdk/aws-ec2/test/vpc-ipam.integ.snapshot/VpcIpamDefaultTestDeployAssertB1CA1C3A.template.json
  packages/@aws-cdk/aws-ec2/test/vpc-ipam.integ.snapshot/asset.d47f7e6772bfdf47ecbc070ffe204baf53bacbfbf7814eb407bd8ea108c1c1bb.bundle/index.js
  packages/@aws-cdk/aws-ec2/test/vpc-ipam.integ.snapshot/aws-cdk-ec2-ipam-vpc.assets.json
  packages/@aws-cdk/aws-ec2/test/vpc-ipam.integ.snapshot/aws-cdk-ec2-ipam-vpc.template.json
  packages/@aws-cdk/aws-ec2/test/vpc-ipam.integ.snapshot/cdk.out
  packages/@aws-cdk/aws-ec2/test/vpc-ipam.integ.snapshot/integ.json
  packages/@aws-cdk/aws-ec2/test/vpc-ipam.integ.snapshot/manifest.json
  packages/@aws-cdk/aws-ec2/test/vpc-ipam.integ.snapshot/tree.json
  packages/@aws-cdk/aws-ec2/test/vpc.test.ts
Labels: p1, feature-request, effort/large, beginning-contributor

#22667 chore(aws-eks): pin `aws-cdk-lib` devDependency to `2.47.0`
  packages/@aws-cdk/aws-eks/package.json
Labels: p2, contribution/core

#22672 chore(merge-back): 1.179.0
  CHANGELOG.md
  version.v1.json
Labels: p2, pr/no-squash, auto-approve

#22674 chore(eks): remove whitespace and stylistic updates
  packages/@aws-cdk/aws-eks/README.md
  packages/@aws-cdk/aws-eks/lib/cluster.ts
  packages/@aws-cdk/aws-eks/test/alb-controller.test.ts
  packages/@aws-cdk/aws-eks/test/awsauth.test.ts
  packages/@aws-cdk/aws-eks/test/cluster-resource-provider.test.ts
  packages/@aws-cdk/aws-eks/test/cluster.test.ts
  packages/@aws-cdk/aws-eks/test/fargate-resource-provider.test.ts
  packages/@aws-cdk/aws-eks/test/fargate.test.ts
  packages/@aws-cdk/aws-eks/test/helm-chart.test.ts
  packages/@aws-cdk/aws-eks/test/k8s-manifest.test.ts
  packages/@aws-cdk/aws-eks/test/k8s-object-value.test.ts
  packages/@aws-cdk/aws-eks/test/k8s-patch.test.ts
  packages/@aws-cdk/aws-eks/test/nodegroup.test.ts
  packages/@aws-cdk/aws-eks/test/service-account.test.ts
  packages/@aws-cdk/aws-eks/test/user-data.test.ts
Labels: p2, contribution/core

#22676 chore(merge-back): 2.48.0
  CHANGELOG.v2.alpha.md
  CHANGELOG.v2.md
  version.v2.json
Labels: p2, pr/no-squash, auto-approve

#22679 chore(eks): pin aws-cdk-lib devDependency to 2.47.0
  packages/@aws-cdk/aws-eks/package.json
Labels: p2, contribution/core

#22680 chore(release): 2.49.0
  packages/@aws-cdk/aws-eks/package.json
Labels: p2, pr/no-squash, auto-approve

#22681 chore(merge-back): 2.49.0
  CHANGELOG.v2.alpha.md
  CHANGELOG.v2.md
  version.v2.json
Labels: p2, pr/no-squash, auto-approve

#22609 feat(aws-ecs-patterns): entryPoint and command support within ApplicationLoadBalancedFargateService and ApplicationLoadBalancedEc2Service
  packages/@aws-cdk/aws-ecs-patterns/README.md
  packages/@aws-cdk/aws-ecs-patterns/lib/base/application-load-balanced-service-base.ts
  packages/@aws-cdk/aws-ecs-patterns/lib/ecs/application-load-balanced-ecs-service.ts
  packages/@aws-cdk/aws-ecs-patterns/lib/fargate/application-load-balanced-fargate-service.ts
  packages/@aws-cdk/aws-ecs-patterns/test/ec2/alb-ecs-service-command-entry-point.integ.snapshot/AlbEc2ServiceWithCommandAndEntryPointDefaultTestDeployAssert91EF33D6.assets.json
  packages/@aws-cdk/aws-ecs-patterns/test/ec2/alb-ecs-service-command-entry-point.integ.snapshot/AlbEc2ServiceWithCommandAndEntryPointDefaultTestDeployAssert91EF33D6.template.json
  packages/@aws-cdk/aws-ecs-patterns/test/ec2/alb-ecs-service-command-entry-point.integ.snapshot/aws-ecs-integ-alb-ec2-cmd-entrypoint.assets.json
  packages/@aws-cdk/aws-ecs-patterns/test/ec2/alb-ecs-service-command-entry-point.integ.snapshot/aws-ecs-integ-alb-ec2-cmd-entrypoint.template.json
  packages/@aws-cdk/aws-ecs-patterns/test/ec2/alb-ecs-service-command-entry-point.integ.snapshot/cdk.out
  packages/@aws-cdk/aws-ecs-patterns/test/ec2/alb-ecs-service-command-entry-point.integ.snapshot/integ.json
  packages/@aws-cdk/aws-ecs-patterns/test/ec2/alb-ecs-service-command-entry-point.integ.snapshot/manifest.json
  packages/@aws-cdk/aws-ecs-patterns/test/ec2/alb-ecs-service-command-entry-point.integ.snapshot/tree.json
  packages/@aws-cdk/aws-ecs-patterns/test/ec2/integ.alb-ecs-service-command-entry-point.ts
  packages/@aws-cdk/aws-ecs-patterns/test/ec2/l3s.test.ts
  packages/@aws-cdk/aws-ecs-patterns/test/fargate/alb-fargate-service-command-entry-point.integ.snapshot/AlbFargateServiceWithCommandAndEntryPointDefaultTestDeployAssert84DAACDF.assets.json
  packages/@aws-cdk/aws-ecs-patterns/test/fargate/alb-fargate-service-command-entry-point.integ.snapshot/AlbFargateServiceWithCommandAndEntryPointDefaultTestDeployAssert84DAACDF.template.json
  packages/@aws-cdk/aws-ecs-patterns/test/fargate/alb-fargate-service-command-entry-point.integ.snapshot/aws-ecs-integ-lb-fargate-cmd-entrypoint-test.assets.json
  packages/@aws-cdk/aws-ecs-patterns/test/fargate/alb-fargate-service-command-entry-point.integ.snapshot/aws-ecs-integ-lb-fargate-cmd-entrypoint-test.template.json
  packages/@aws-cdk/aws-ecs-patterns/test/fargate/alb-fargate-service-command-entry-point.integ.snapshot/cdk.out
  packages/@aws-cdk/aws-ecs-patterns/test/fargate/alb-fargate-service-command-entry-point.integ.snapshot/integ.json
  packages/@aws-cdk/aws-ecs-patterns/test/fargate/alb-fargate-service-command-entry-point.integ.snapshot/manifest.json
  packages/@aws-cdk/aws-ecs-patterns/test/fargate/alb-fargate-service-command-entry-point.integ.snapshot/tree.json
  packages/@aws-cdk/aws-ecs-patterns/test/fargate/integ.alb-fargate-service-command-entry-point.ts
  packages/@aws-cdk/aws-ecs-patterns/test/fargate/load-balanced-fargate-service.test.ts
Labels: p2, feature-request, effort/small, beginning-contributor

#22683 docs: fix an incorrect changelog entry
  CHANGELOG.v2.md
Labels: p2, beginning-contributor

#22690 chore(eks): kubectl docs updates
  packages/@aws-cdk/aws-eks/README.md
Labels: p2, distinguished-contributor

#22691 docs(eks): corrects url of stable helm charts
  packages/@aws-cdk/aws-eks/lib/helm-chart.ts
Labels: p2, beginning-contributor

#22692 fix(stepfunctions-tasks): athenaStartQueryExecution task generates invalid s3 arn
  packages/@aws-cdk/aws-stepfunctions-tasks/lib/athena/start-query-execution.ts
  packages/@aws-cdk/aws-stepfunctions-tasks/test/athena/start-query-execution.test.ts
Labels: p2, contribution/core, pr-linter/exempt-integ-test

#22295 feat(codedeploy): CodeDeploy deployment group construct for ECS
  packages/@aws-cdk/aws-codedeploy/README.md
  packages/@aws-cdk/aws-codedeploy/lib/ecs/deployment-group.ts
  packages/@aws-cdk/aws-codedeploy/package.json
  packages/@aws-cdk/aws-codedeploy/test/ecs/deployment-group.integ.snapshot/EcsDeploymentGroupTestDefaultTestDeployAssert60AABFA0.assets.json
  packages/@aws-cdk/aws-codedeploy/test/ecs/deployment-group.integ.snapshot/EcsDeploymentGroupTestDefaultTestDeployAssert60AABFA0.template.json
  packages/@aws-cdk/aws-codedeploy/test/ecs/deployment-group.integ.snapshot/aws-cdk-codedeploy-ecs-dg.assets.json
  packages/@aws-cdk/aws-codedeploy/test/ecs/deployment-group.integ.snapshot/aws-cdk-codedeploy-ecs-dg.template.json
  packages/@aws-cdk/aws-codedeploy/test/ecs/deployment-group.integ.snapshot/cdk.out
  packages/@aws-cdk/aws-codedeploy/test/ecs/deployment-group.integ.snapshot/integ.json
  packages/@aws-cdk/aws-codedeploy/test/ecs/deployment-group.integ.snapshot/manifest.json
  packages/@aws-cdk/aws-codedeploy/test/ecs/deployment-group.integ.snapshot/tree.json
  packages/@aws-cdk/aws-codedeploy/test/ecs/deployment-group.test.ts
  packages/@aws-cdk/aws-codedeploy/test/ecs/integ.deployment-group.ts
  packages/@aws-cdk/aws-ecs/lib/base/base-service.ts
  packages/@aws-cdk/aws-ecs/test/ec2/ec2-service.test.ts
  packages/@aws-cdk/aws-ecs/test/fargate/fargate-service.test.ts
  packages/@aws-cdk/aws-elasticloadbalancingv2/lib/alb/application-listener.ts
  packages/@aws-cdk/aws-elasticloadbalancingv2/lib/nlb/network-listener.ts
  packages/@aws-cdk/aws-elasticloadbalancingv2/lib/shared/base-listener.ts
Labels: p1, feature-request, effort/large, admired-contributor

#22671 fix(apigateway): race condition exists between stage and cfnaccount in specrestapi
  packages/@aws-cdk/aws-apigateway/lib/restapi.ts
  packages/@aws-cdk/aws-apigateway/test/api-definition.asset.integ.snapshot/cdk.out
  packages/@aws-cdk/aws-apigateway/test/api-definition.asset.integ.snapshot/integ.json
  packages/@aws-cdk/aws-apigateway/test/api-definition.asset.integ.snapshot/integtest-restapi-fromdefinition-asset.assets.json
  packages/@aws-cdk/aws-apigateway/test/api-definition.asset.integ.snapshot/integtest-restapi-fromdefinition-asset.template.json
  packages/@aws-cdk/aws-apigateway/test/api-definition.asset.integ.snapshot/manifest.json
  packages/@aws-cdk/aws-apigateway/test/api-definition.asset.integ.snapshot/restapifromdefinitionDefaultTestDeployAssertDF3B0845.assets.json
  packages/@aws-cdk/aws-apigateway/test/api-definition.asset.integ.snapshot/tree.json
  packages/@aws-cdk/aws-apigateway/test/api-definition.inline.integ.snapshot/cdk.out
  packages/@aws-cdk/aws-apigateway/test/api-definition.inline.integ.snapshot/inlineapidefinitionDefaultTestDeployAssert923CAC29.assets.json
  packages/@aws-cdk/aws-apigateway/test/api-definition.inline.integ.snapshot/integ.json
  packages/@aws-cdk/aws-apigateway/test/api-definition.inline.integ.snapshot/integtest-restapi-fromdefinition-inline.assets.json
  packages/@aws-cdk/aws-apigateway/test/api-definition.inline.integ.snapshot/integtest-restapi-fromdefinition-inline.template.json
  packages/@aws-cdk/aws-apigateway/test/api-definition.inline.integ.snapshot/manifest.json
  packages/@aws-cdk/aws-apigateway/test/api-definition.inline.integ.snapshot/tree.json
  packages/@aws-cdk/aws-apigateway/test/spec-restapi.integ.snapshot/manifest.json
  packages/@aws-cdk/aws-apigateway/test/spec-restapi.integ.snapshot/test-apigateway-spec-restapi.assets.json
  packages/@aws-cdk/aws-apigateway/test/spec-restapi.integ.snapshot/test-apigateway-spec-restapi.template.json
  packages/@aws-cdk/aws-apigateway/test/spec-restapi.integ.snapshot/tree.json
  packages/@aws-cdk/aws-apigateway/test/stage.test.ts
Labels: bug, p1, pr-linter/exempt-integ-test, beginning-contributor

#22462 docs(cognito): update user pool example with case insensitive sign in
  packages/@aws-cdk/aws-cognito/README.md
Labels: p2, beginning-contributor

#22296 fix(aws-events): restrict eventbus statementId to 64 characters
  packages/@aws-cdk/aws-events/lib/rule.ts
  packages/@aws-cdk/aws-events/test/cross-account-rule.integ.snapshot/CrossAccountDeployDefaultTestDeployAssertB5328BEF.assets.json
  packages/@aws-cdk/aws-events/test/cross-account-rule.integ.snapshot/CrossAccountDeployDefaultTestDeployAssertB5328BEF.template.json
  packages/@aws-cdk/aws-events/test/cross-account-rule.integ.snapshot/EventBusPolicy-987654321-test-region-12345678.assets.json
  packages/@aws-cdk/aws-events/test/cross-account-rule.integ.snapshot/EventBusPolicy-987654321-test-region-12345678.template.json
  packages/@aws-cdk/aws-events/test/cross-account-rule.integ.snapshot/FromCrossAccountRuleStack.assets.json
  packages/@aws-cdk/aws-events/test/cross-account-rule.integ.snapshot/FromCrossAccountRuleStack.template.json
  packages/@aws-cdk/aws-events/test/cross-account-rule.integ.snapshot/ToCrossAccountRuleStack.assets.json
  packages/@aws-cdk/aws-events/test/cross-account-rule.integ.snapshot/ToCrossAccountRuleStack.template.json
  packages/@aws-cdk/aws-events/test/cross-account-rule.integ.snapshot/asset.2a53dc40a7dae81c8850e125ab49e5f55d80b7b8ceac86976f2a4119393cab72.bundle/index.js
  packages/@aws-cdk/aws-events/test/cross-account-rule.integ.snapshot/cdk.out
  packages/@aws-cdk/aws-events/test/cross-account-rule.integ.snapshot/integ.json
  packages/@aws-cdk/aws-events/test/cross-account-rule.integ.snapshot/manifest.json
  packages/@aws-cdk/aws-events/test/cross-account-rule.integ.snapshot/tree.json
  packages/@aws-cdk/aws-events/test/integ.cross-account-rule.ts
  packages/@aws-cdk/aws-events/test/rule.test.ts
Labels: bug, p2, @aws-cdk/aws-events, effort/small, beginning-contributor

#22707 feat(synthetics): aws synthetics runtime version syn-nodejs-puppeteer-3.8
  packages/@aws-cdk/aws-synthetics/README.md
  packages/@aws-cdk/aws-synthetics/lib/runtime.ts
  packages/@aws-cdk/aws-synthetics/test/canary.integ.snapshot/canary-one.assets.json
  packages/@aws-cdk/aws-synthetics/test/canary.integ.snapshot/canary-one.template.json
  packages/@aws-cdk/aws-synthetics/test/canary.integ.snapshot/manifest.json
  packages/@aws-cdk/aws-synthetics/test/canary.integ.snapshot/tree.json
  packages/@aws-cdk/aws-synthetics/test/integ.canary.ts
Labels: p2, repeat-contributor

#22705 feat(ec2): Vpc supports reserving space for future AZs
  packages/@aws-cdk/aws-ec2/README.md
  packages/@aws-cdk/aws-ec2/lib/vpc.ts
  packages/@aws-cdk/aws-ec2/test/integ.vpc-reserved-azs.ts
  packages/@aws-cdk/aws-ec2/test/vpc-reserved-azs.integ.snapshot/cdk.out
  packages/@aws-cdk/aws-ec2/test/vpc-reserved-azs.integ.snapshot/integ.json
  packages/@aws-cdk/aws-ec2/test/vpc-reserved-azs.integ.snapshot/integtest-vpc-reserved-azs.assets.json
  packages/@aws-cdk/aws-ec2/test/vpc-reserved-azs.integ.snapshot/integtest-vpc-reserved-azs.template.json
  packages/@aws-cdk/aws-ec2/test/vpc-reserved-azs.integ.snapshot/manifest.json
  packages/@aws-cdk/aws-ec2/test/vpc-reserved-azs.integ.snapshot/tree.json
  packages/@aws-cdk/aws-ec2/test/vpc-reserved-azs.integ.snapshot/vpcreservedazsDefaultTestDeployAssertE48D2C6D.assets.json
  packages/@aws-cdk/aws-ec2/test/vpc-reserved-azs.integ.snapshot/vpcreservedazsDefaultTestDeployAssertE48D2C6D.template.json
  packages/@aws-cdk/aws-ec2/test/vpc.test.ts
Labels: p2, beginning-contributor

#22699 chore(stepfunctions-tasks): athenaStartQueryExecution addition to integration tests for better coverage
  packages/@aws-cdk/aws-stepfunctions-tasks/test/athena/integ.start-query-execution.ts
  packages/@aws-cdk/aws-stepfunctions-tasks/test/athena/start-query-execution.integ.snapshot/aws-stepfunctions-tasks-athena-start-query-execution-integ.assets.json
  packages/@aws-cdk/aws-stepfunctions-tasks/test/athena/start-query-execution.integ.snapshot/aws-stepfunctions-tasks-athena-start-query-execution-integ.template.json
  packages/@aws-cdk/aws-stepfunctions-tasks/test/athena/start-query-execution.integ.snapshot/cdk.out
  packages/@aws-cdk/aws-stepfunctions-tasks/test/athena/start-query-execution.integ.snapshot/integ.json
  packages/@aws-cdk/aws-stepfunctions-tasks/test/athena/start-query-execution.integ.snapshot/manifest.json
  packages/@aws-cdk/aws-stepfunctions-tasks/test/athena/start-query-execution.integ.snapshot/tree.json
Labels: p2, beginning-contributor

#22626 chore(lambda): adding Lambda insights 1.0.143.0
  packages/@aws-cdk/aws-lambda/lib/lambda-insights.ts
  packages/@aws-cdk/aws-lambda/test/lambda-insights.test.ts
  packages/@aws-cdk/region-info/build-tools/fact-tables.ts
  packages/@aws-cdk/region-info/test/__snapshots__/region-info.test.js.snap
Labels: p2, admired-contributor

#22715 fix: revert jsii to version 1.69.0
  package.json
  packages/aws-cdk/THIRD_PARTY_LICENSES
  packages/aws-cdk/package.json
  packages/awslint/package.json
  packages/cdk-dasm/package.json
  tools/@aws-cdk/cdk-build-tools/package.json
  tools/@aws-cdk/cfn2ts/package.json
  yarn.lock
Labels: p2, contribution/core, pr-linter/exempt-test, pr-linter/exempt-integ-test

#22431 feat(stepfunctions): add intrinsic functions
  packages/@aws-cdk/aws-stepfunctions/README.md
  packages/@aws-cdk/aws-stepfunctions/lib/fields.ts
  packages/@aws-cdk/aws-stepfunctions/lib/private/json-path.ts
  packages/@aws-cdk/aws-stepfunctions/test/fields.test.ts
  packages/@aws-cdk/aws-stepfunctions/test/integ.intrinsics.ts
  packages/@aws-cdk/aws-stepfunctions/test/intrinsics.integ.snapshot/StateMachineIntrinsicsTestDefaultTestDeployAssert1C1E1D7E.assets.json
  packages/@aws-cdk/aws-stepfunctions/test/intrinsics.integ.snapshot/StateMachineIntrinsicsTestDefaultTestDeployAssert1C1E1D7E.template.json
  packages/@aws-cdk/aws-stepfunctions/test/intrinsics.integ.snapshot/asset.3074b79e05e7b98930b6449e01baa3e68b32ecff86328933c2542f7b7fe6fdac.bundle/index.js
  packages/@aws-cdk/aws-stepfunctions/test/intrinsics.integ.snapshot/aws-stepfunctions-intrinsics-integ.assets.json
  packages/@aws-cdk/aws-stepfunctions/test/intrinsics.integ.snapshot/aws-stepfunctions-intrinsics-integ.template.json
  packages/@aws-cdk/aws-stepfunctions/test/intrinsics.integ.snapshot/cdk.out
  packages/@aws-cdk/aws-stepfunctions/test/intrinsics.integ.snapshot/integ.json
  packages/@aws-cdk/aws-stepfunctions/test/intrinsics.integ.snapshot/manifest.json
  packages/@aws-cdk/aws-stepfunctions/test/intrinsics.integ.snapshot/tree.json
  packages/@aws-cdk/aws-stepfunctions/test/private/json-path.test.ts
Labels: p1, feature-request, effort/medium, beginning-contributor

#22718 chore(release): 2.49.1
  CHANGELOG.v2.alpha.md
  CHANGELOG.v2.md
  package.json
  packages/aws-cdk/THIRD_PARTY_LICENSES
  packages/aws-cdk/package.json
  packages/awslint/package.json
  packages/cdk-dasm/package.json
  tools/@aws-cdk/cdk-build-tools/package.json
  tools/@aws-cdk/cfn2ts/package.json
  version.v2.json
  yarn.lock
Labels: p2, contribution/core, pr/no-squash
