Repository aws/aws-cdk, pull requests merged in 2023-06, with the labels that each got.

#25809 feat(cfnspec): cloudformation spec v124.0.0
  packages/@aws-cdk/cfnspec/CHANGELOG.md
  packages/@aws-cdk/cfnspec/skip-evolution-check.txt
  packages/@aws-cdk/cfnspec/spec-source/specification/000_cfn/000_official/000_AWS_S3.json
  packages/@aws-cdk/cfnspec/spec-source/specification/000_cfn/500_Revert_To_Json_Types_patch.json
Labels: p2, pr-linter/exempt-test, auto-approve, pr-linter/exempt-integ-test

#25790 feat(cfnspec): cloudformation spec v124.0.0
  packages/@aws-cdk/cfnspec/CHANGELOG.md
  packages/@aws-cdk/cfnspec/skip-evolution-check.txt
  packages/@aws-cdk/cfnspec/spec-source/specification/000_cfn/000_official/000_AWS_S3.json
  packages/@aws-cdk/cfnspec/spec-source/specification/000_cfn/500_Revert_To_Json_Types_patch.json
Labels: p2, pr-linter/exempt-test, auto-approve, pr-linter/exempt-integ-test

#25811 docs(app-staging-synthesizer): example for `DefaultStagingStack`
  packages/@aws-cdk/app-staging-synthesizer-alpha/lib/default-staging-stack.ts
Labels: p2, contribution/core

#25823 chore(app-staging-synthesizer): use an accepted dotnet namespace/packageId
  packages/@aws-cdk/app-staging-synthesizer-alpha/package.json
Labels: p2, contribution/core

#25817 feat(lambda): add Runtime.RUBY_3_2
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda/test/integ.ruby.file.js.snapshot/IntegTestDefaultTestDeployAssertE3E7D2A4.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda/test/integ.ruby.file.js.snapshot/IntegTestDefaultTestDeployAssertE3E7D2A4.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda/test/integ.ruby.file.js.snapshot/asset.ae370e1010629b78f494346f49ceef3ab2875718f20e6c808114e6aa770c7bf3.bundle/index.js
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda/test/integ.ruby.file.js.snapshot/asset.b9d265a7298dcf7774794746a1aac25ee61dc998230526747e062aeaff88af86/index.rb
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda/test/integ.ruby.file.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda/test/integ.ruby.file.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda/test/integ.ruby.file.js.snapshot/lambda-test-assets-file.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda/test/integ.ruby.file.js.snapshot/lambda-test-assets-file.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda/test/integ.ruby.file.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda/test/integ.ruby.file.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda/test/integ.ruby.file.ts
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda/test/integ.ruby.file.ts.snapshot/IntegTestDefaultTestDeployAssertE3E7D2A4.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda/test/integ.ruby.file.ts.snapshot/IntegTestDefaultTestDeployAssertE3E7D2A4.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda/test/integ.ruby.file.ts.snapshot/asset.1f3c2cfb18e102edc713fe4c4b4d87572f4297ee4a5e80a5960adf526ee9ea28.bundle/index.js
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda/test/integ.ruby.file.ts.snapshot/asset.b9d265a7298dcf7774794746a1aac25ee61dc998230526747e062aeaff88af86/index.rb
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda/test/integ.ruby.file.ts.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda/test/integ.ruby.file.ts.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda/test/integ.ruby.file.ts.snapshot/lambda-test-assets-file.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda/test/integ.ruby.file.ts.snapshot/lambda-test-assets-file.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda/test/integ.ruby.file.ts.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda/test/integ.ruby.file.ts.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda/test/rubyhandler/index.rb
  packages/aws-cdk-lib/aws-lambda/lib/runtime.ts
Labels: p2, contribution/core, pr-linter/exempt-readme

#25825 chore(release): 2.82.0
  CHANGELOG.v2.alpha.md
  CHANGELOG.v2.md
  packages/@aws-cdk-testing/framework-integ/test/aws-cloudformation/test/integ.core-custom-resources-node-18.js.snapshot/asset.5a80abfca3e7d70957e8c0a553225876c69fb6038b810fe65b581b6b58453bf7/__entrypoint__.js
  packages/@aws-cdk-testing/framework-integ/test/aws-cloudformation/test/integ.core-custom-resources-node-18.js.snapshot/asset.5a80abfca3e7d70957e8c0a553225876c69fb6038b810fe65b581b6b58453bf7/index.js
  packages/@aws-cdk-testing/framework-integ/test/aws-cloudformation/test/integ.core-custom-resources-node-18.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-cloudformation/test/integ.core-custom-resources-node-18.js.snapshot/custom-resource-test-node-18-stack.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-cloudformation/test/integ.core-custom-resources-node-18.js.snapshot/custom-resource-test-node-18-stack.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-cloudformation/test/integ.core-custom-resources-node-18.js.snapshot/customresourcetestnode18integDefaultTestDeployAssert9B8E9A20.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-cloudformation/test/integ.core-custom-resources-node-18.js.snapshot/customresourcetestnode18integDefaultTestDeployAssert9B8E9A20.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-cloudformation/test/integ.core-custom-resources-node-18.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-cloudformation/test/integ.core-custom-resources-node-18.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-cloudformation/test/integ.core-custom-resources-node-18.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-cloudformation/test/integ.core-custom-resources-node-18.ts
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda/test/integ.ruby.file.js.snapshot/IntegTestDefaultTestDeployAssertE3E7D2A4.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda/test/integ.ruby.file.js.snapshot/IntegTestDefaultTestDeployAssertE3E7D2A4.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda/test/integ.ruby.file.js.snapshot/asset.ae370e1010629b78f494346f49ceef3ab2875718f20e6c808114e6aa770c7bf3.bundle/index.js
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda/test/integ.ruby.file.js.snapshot/asset.b9d265a7298dcf7774794746a1aac25ee61dc998230526747e062aeaff88af86/index.rb
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda/test/integ.ruby.file.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda/test/integ.ruby.file.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda/test/integ.ruby.file.js.snapshot/lambda-test-assets-file.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda/test/integ.ruby.file.js.snapshot/lambda-test-assets-file.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda/test/integ.ruby.file.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda/test/integ.ruby.file.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda/test/integ.ruby.file.ts
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda/test/integ.ruby.file.ts.snapshot/IntegTestDefaultTestDeployAssertE3E7D2A4.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda/test/integ.ruby.file.ts.snapshot/IntegTestDefaultTestDeployAssertE3E7D2A4.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda/test/integ.ruby.file.ts.snapshot/asset.1f3c2cfb18e102edc713fe4c4b4d87572f4297ee4a5e80a5960adf526ee9ea28.bundle/index.js
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda/test/integ.ruby.file.ts.snapshot/asset.b9d265a7298dcf7774794746a1aac25ee61dc998230526747e062aeaff88af86/index.rb
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda/test/integ.ruby.file.ts.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda/test/integ.ruby.file.ts.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda/test/integ.ruby.file.ts.snapshot/lambda-test-assets-file.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda/test/integ.ruby.file.ts.snapshot/lambda-test-assets-file.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda/test/integ.ruby.file.ts.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda/test/integ.ruby.file.ts.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda/test/rubyhandler/index.rb
  packages/@aws-cdk/app-staging-synthesizer-alpha/lib/default-staging-stack.ts
  packages/@aws-cdk/app-staging-synthesizer-alpha/package.json
  packages/@aws-cdk/cfnspec/CHANGELOG.md
  packages/@aws-cdk/cfnspec/skip-evolution-check.txt
  packages/@aws-cdk/cfnspec/spec-source/specification/000_cfn/000_official/000_AWS_S3.json
  packages/@aws-cdk/cfnspec/spec-source/specification/000_cfn/500_Revert_To_Json_Types_patch.json
  packages/aws-cdk-lib/aws-ecr/lib/repository.ts
  packages/aws-cdk-lib/aws-ecr/test/repository.test.ts
  packages/aws-cdk-lib/aws-lambda/lib/runtime.ts
  packages/aws-cdk-lib/aws-lambda/test/lambda-insights.test.ts
  packages/aws-cdk-lib/aws-s3/test/util.test.ts
  packages/aws-cdk-lib/core/README.md
  packages/aws-cdk-lib/core/lib/custom-resource-provider/custom-resource-provider.ts
  packages/aws-cdk-lib/pipelines/test/docker-credentials.test.ts
Labels: p2, pr/no-squash, auto-approve

#25829 chore(merge-back): 2.82.0
  CHANGELOG.v2.alpha.md
  CHANGELOG.v2.md
  packages/@aws-cdk/cfnspec/skip-evolution-check.txt
  version.v2.json
Labels: p2, pr/no-squash, auto-approve

#25822 fix(kms): aliasName references alias itself (under feature flag)
  packages/aws-cdk-lib/aws-codepipeline/test/artifacts.test.ts
  packages/aws-cdk-lib/aws-kms/lib/alias.ts
  packages/aws-cdk-lib/aws-kms/test/alias.test.ts
  packages/aws-cdk-lib/core/lib/feature-flags.ts
  packages/aws-cdk-lib/cx-api/lib/features.ts
Labels: bug, p1, effort/small, pr/needs-review, contribution/core, pr-linter/exempt-integ-test

#25545 chore(region-info): register ap-south-2
  packages/@aws-cdk/aws-iot-actions-alpha/test/kinesis-firehose/integ.firehose-put-record-action.js.snapshot/cdk.out
  packages/@aws-cdk/aws-iot-actions-alpha/test/kinesis-firehose/integ.firehose-put-record-action.js.snapshot/integ.json
  packages/@aws-cdk/aws-iot-actions-alpha/test/kinesis-firehose/integ.firehose-put-record-action.js.snapshot/manifest.json
  packages/@aws-cdk/aws-iot-actions-alpha/test/kinesis-firehose/integ.firehose-put-record-action.js.snapshot/test-stack.assets.json
  packages/@aws-cdk/aws-iot-actions-alpha/test/kinesis-firehose/integ.firehose-put-record-action.js.snapshot/test-stack.template.json
  packages/@aws-cdk/aws-iot-actions-alpha/test/kinesis-firehose/integ.firehose-put-record-action.js.snapshot/tree.json
  packages/@aws-cdk/aws-kinesisfirehose-alpha/test/integ.delivery-stream.js.snapshot/aws-cdk-firehose-delivery-stream.assets.json
  packages/@aws-cdk/aws-kinesisfirehose-alpha/test/integ.delivery-stream.js.snapshot/aws-cdk-firehose-delivery-stream.template.json
  packages/@aws-cdk/aws-kinesisfirehose-alpha/test/integ.delivery-stream.js.snapshot/cdk.out
  packages/@aws-cdk/aws-kinesisfirehose-alpha/test/integ.delivery-stream.js.snapshot/integ.json
  packages/@aws-cdk/aws-kinesisfirehose-alpha/test/integ.delivery-stream.js.snapshot/manifest.json
  packages/@aws-cdk/aws-kinesisfirehose-alpha/test/integ.delivery-stream.js.snapshot/tree.json
  packages/@aws-cdk/aws-kinesisfirehose-alpha/test/integ.delivery-stream.source-stream.js.snapshot/aws-cdk-firehose-delivery-stream-source-stream.assets.json
  packages/@aws-cdk/aws-kinesisfirehose-alpha/test/integ.delivery-stream.source-stream.js.snapshot/aws-cdk-firehose-delivery-stream-source-stream.template.json
  packages/@aws-cdk/aws-kinesisfirehose-alpha/test/integ.delivery-stream.source-stream.js.snapshot/cdk.out
  packages/@aws-cdk/aws-kinesisfirehose-alpha/test/integ.delivery-stream.source-stream.js.snapshot/integ.json
  packages/@aws-cdk/aws-kinesisfirehose-alpha/test/integ.delivery-stream.source-stream.js.snapshot/manifest.json
  packages/@aws-cdk/aws-kinesisfirehose-alpha/test/integ.delivery-stream.source-stream.js.snapshot/tree.json
  packages/@aws-cdk/aws-kinesisfirehose-destinations-alpha/test/integ.s3-bucket.lit.js.snapshot/aws-cdk-firehose-delivery-stream-s3-all-properties.assets.json
  packages/@aws-cdk/aws-kinesisfirehose-destinations-alpha/test/integ.s3-bucket.lit.js.snapshot/aws-cdk-firehose-delivery-stream-s3-all-properties.template.json
  packages/@aws-cdk/aws-kinesisfirehose-destinations-alpha/test/integ.s3-bucket.lit.js.snapshot/cdk.out
  packages/@aws-cdk/aws-kinesisfirehose-destinations-alpha/test/integ.s3-bucket.lit.js.snapshot/integ.json
  packages/@aws-cdk/aws-kinesisfirehose-destinations-alpha/test/integ.s3-bucket.lit.js.snapshot/manifest.json
  packages/@aws-cdk/aws-kinesisfirehose-destinations-alpha/test/integ.s3-bucket.lit.js.snapshot/tree.json
  packages/@aws-cdk/aws-lambda-go-alpha/package.json
  packages/@aws-cdk/cli-lib-alpha/THIRD_PARTY_LICENSES
  packages/aws-cdk-lib/region-info/build-tools/fact-tables.ts
  packages/aws-cdk-lib/region-info/test/__snapshots__/region-info.test.js.snap
Labels: p1, feature-request, effort/medium, contribution/core

#25815 chore(deps): upgrade cdk-generate-synthetic-examples to latest fixed version
  package.json
  scripts/run-rosetta.sh
  yarn.lock
Labels: p2, pr/needs-review, contribution/core

#25680 chore: update ancient issue time
  .github/workflows/close-stale-issues.yml
Labels: p2, pr/needs-review, contribution/core

#25836 chore(cdk-release): alpha package changes aren't written to alpha CHANGELOG
  tools/@aws-cdk/cdk-release/lib/conventional-commits.ts
  tools/@aws-cdk/cdk-release/test/conventional-commits.test.ts
Labels: p2, contribution/core

#25830 chore(cli): print detected cycle if work graph stalls
  packages/aws-cdk/lib/util/work-graph.ts
  packages/aws-cdk/test/work-graph.test.ts
Labels: p2, contribution/core, pr-linter/cli-integ-tested

#25801 chore(merge-back): 1.203.0
  CHANGELOG.md
  packages/@aws-cdk/cfnspec/skip-evolution-check.txt
  version.v1.json
Labels: p2, pr/no-squash, auto-approve

#25639 feat(events-targets): support enableExecuteCommand in EcsTask construct
  packages/@aws-cdk-testing/framework-integ/test/aws-events-targets/test/ecs/integ.event-fargate-task.js.snapshot/EcsFargateTestDefaultTestDeployAssert36341BFB.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-events-targets/test/ecs/integ.event-fargate-task.js.snapshot/aws-ecs-integ-fargate.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-events-targets/test/ecs/integ.event-fargate-task.js.snapshot/aws-ecs-integ-fargate.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-events-targets/test/ecs/integ.event-fargate-task.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-events-targets/test/ecs/integ.event-fargate-task.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-events-targets/test/ecs/integ.event-fargate-task.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-events-targets/test/ecs/integ.event-fargate-task.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-events-targets/test/ecs/integ.event-fargate-task.ts
  packages/aws-cdk-lib/aws-events-targets/README.md
  packages/aws-cdk-lib/aws-events-targets/lib/ecs-task.ts
  packages/aws-cdk-lib/aws-events-targets/test/ecs/event-rule-target.test.ts
Labels: p2, pr/needs-review, repeat-contributor

#25846 fix(cli): deployment gets stuck deploying stacks with shared assets
  packages/aws-cdk/lib/cdk-toolkit.ts
  packages/aws-cdk/lib/util/work-graph-builder.ts
  packages/aws-cdk/lib/util/work-graph.ts
  packages/aws-cdk/test/work-graph-builder.test.ts
Labels: bug, p1, pr/needs-review, contribution/core, pr-linter/exempt-integ-test, pr-linter/cli-integ-tested

#25593 feat(cloud9): support setting automaticStopTimeMinutes
  packages/@aws-cdk/aws-cloud9-alpha/README.md
  packages/@aws-cdk/aws-cloud9-alpha/lib/environment.ts
  packages/@aws-cdk/aws-cloud9-alpha/rosetta/default.ts-fixture
  packages/@aws-cdk/aws-cloud9-alpha/test/cloud9.environment.test.ts
  packages/@aws-cdk/aws-cloud9-alpha/test/integ.automatic-stop.js.snapshot/C9automaticStopStack.assets.json
  packages/@aws-cdk/aws-cloud9-alpha/test/integ.automatic-stop.js.snapshot/C9automaticStopStack.template.json
  packages/@aws-cdk/aws-cloud9-alpha/test/integ.automatic-stop.js.snapshot/cdk.out
  packages/@aws-cdk/aws-cloud9-alpha/test/integ.automatic-stop.js.snapshot/cloud9automaticstoptimemintuesDefaultTestDeployAssertBBFEEF89.assets.json
  packages/@aws-cdk/aws-cloud9-alpha/test/integ.automatic-stop.js.snapshot/cloud9automaticstoptimemintuesDefaultTestDeployAssertBBFEEF89.template.json
  packages/@aws-cdk/aws-cloud9-alpha/test/integ.automatic-stop.js.snapshot/integ.json
  packages/@aws-cdk/aws-cloud9-alpha/test/integ.automatic-stop.js.snapshot/manifest.json
  packages/@aws-cdk/aws-cloud9-alpha/test/integ.automatic-stop.js.snapshot/tree.json
  packages/@aws-cdk/aws-cloud9-alpha/test/integ.automatic-stop.ts
Labels: p2, feature-request, pr/needs-review, beginning-contributor

#25866 fix(cli): asset existence check is slow for many assets
  packages/aws-cdk/lib/util/parallel.ts
  packages/aws-cdk/lib/util/work-graph-builder.ts
  packages/aws-cdk/lib/util/work-graph.ts
  packages/aws-cdk/test/util/parallel.test.ts
Labels: p2, contribution/core, pr-linter/exempt-integ-test, pr-linter/cli-integ-tested

#25861 docs(contributing): Fix broken link in CONTRIBUTING.md
  CONTRIBUTING.md
Labels: p2, pr/needs-review, beginning-contributor

#25869 fix(cli): ENOENT during asset publishing
  packages/cdk-assets/lib/private/archive.ts
Labels: p2, contribution/core, pr-linter/exempt-test, pr-linter/exempt-integ-test

#25789 fix(ecr): auto delete images on ECR repository containing manifest list
  packages/@aws-cdk-testing/framework-integ/test/aws-ecr/test/integ.repository-auto-delete-images.js.snapshot/aws-ecr-integ-stack.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecr/test/integ.repository-auto-delete-images.ts
  packages/aws-cdk-lib/aws-ecr/lib/auto-delete-images-handler/index.ts
  packages/aws-cdk-lib/aws-ecr/test/auto-delete-images-handler.test.ts
Labels: bug, p2, effort/medium, beginning-contributor

#25573 chore(region-info): register eu-south-2
  packages/@aws-cdk/aws-iot-actions-alpha/test/kinesis-firehose/integ.firehose-put-record-action.js.snapshot/cdk.out
  packages/@aws-cdk/aws-iot-actions-alpha/test/kinesis-firehose/integ.firehose-put-record-action.js.snapshot/manifest.json
  packages/@aws-cdk/aws-iot-actions-alpha/test/kinesis-firehose/integ.firehose-put-record-action.js.snapshot/test-stack.assets.json
  packages/@aws-cdk/aws-iot-actions-alpha/test/kinesis-firehose/integ.firehose-put-record-action.js.snapshot/test-stack.template.json
  packages/@aws-cdk/aws-kinesisfirehose-alpha/test/integ.delivery-stream.js.snapshot/aws-cdk-firehose-delivery-stream.assets.json
  packages/@aws-cdk/aws-kinesisfirehose-alpha/test/integ.delivery-stream.js.snapshot/aws-cdk-firehose-delivery-stream.template.json
  packages/@aws-cdk/aws-kinesisfirehose-alpha/test/integ.delivery-stream.js.snapshot/cdk.out
  packages/@aws-cdk/aws-kinesisfirehose-alpha/test/integ.delivery-stream.js.snapshot/manifest.json
  packages/@aws-cdk/aws-kinesisfirehose-alpha/test/integ.delivery-stream.source-stream.js.snapshot/aws-cdk-firehose-delivery-stream-source-stream.assets.json
  packages/@aws-cdk/aws-kinesisfirehose-alpha/test/integ.delivery-stream.source-stream.js.snapshot/aws-cdk-firehose-delivery-stream-source-stream.template.json
  packages/@aws-cdk/aws-kinesisfirehose-alpha/test/integ.delivery-stream.source-stream.js.snapshot/manifest.json
  packages/@aws-cdk/aws-kinesisfirehose-destinations-alpha/test/integ.s3-bucket.lit.js.snapshot/aws-cdk-firehose-delivery-stream-s3-all-properties.assets.json
  packages/@aws-cdk/aws-kinesisfirehose-destinations-alpha/test/integ.s3-bucket.lit.js.snapshot/aws-cdk-firehose-delivery-stream-s3-all-properties.template.json
  packages/@aws-cdk/aws-kinesisfirehose-destinations-alpha/test/integ.s3-bucket.lit.js.snapshot/manifest.json
  packages/aws-cdk-lib/region-info/build-tools/fact-tables.ts
  packages/aws-cdk-lib/region-info/test/__snapshots__/region-info.test.js.snap
Labels: p1, feature-request, effort/medium, contribution/core

#25889 chore(merge-back): 2.83.0
  CHANGELOG.v2.alpha.md
  CHANGELOG.v2.md
  packages/aws-cdk-lib/cx-api/FEATURE_FLAGS.md
  version.v2.json
Labels: p2, pr/needs-review, pr/no-squash, auto-approve

#25863 feat(backup): add recovery point tags param to backup plan rule
  packages/@aws-cdk-testing/framework-integ/test/aws-backup/test/integ.backup.js.snapshot/cdk-backup.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-backup/test/integ.backup.js.snapshot/cdk-backup.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-backup/test/integ.backup.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-backup/test/integ.backup.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-backup/test/integ.backup.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-backup/test/integ.backup.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-backup/test/integ.backup.ts
  packages/aws-cdk-lib/aws-backup/README.md
  packages/aws-cdk-lib/aws-backup/lib/plan.ts
  packages/aws-cdk-lib/aws-backup/lib/rule.ts
  packages/aws-cdk-lib/aws-backup/test/plan.test.ts
Labels: p2, feature-request, effort/small, pr/needs-review, beginning-contributor

#25896 chore(app-staging-synthesizer): remove unnecessary documentation
  packages/@aws-cdk/app-staging-synthesizer-alpha/lib/default-staging-stack.ts
Labels: p2, pr/needs-review, contribution/core

#25529 fix(iam): Modify addManagedPolicy to compare ARN instead of instance reference
  packages/aws-cdk-lib/aws-iam/lib/role.ts
  packages/aws-cdk-lib/aws-iam/test/role.test.ts
Labels: p2, pr/needs-review, pr-linter/exempt-integ-test, beginning-contributor, pr-linter/exemption-requested

#25907 fix(cli): assets shared between stages lead to an error
  packages/aws-cdk/lib/util/work-graph-builder.ts
  packages/aws-cdk/test/work-graph-builder.test.ts
  packages/cdk-assets/lib/asset-manifest.ts
Labels: p2, contribution/core, pr-linter/exempt-integ-test, pr-linter/cli-integ-tested

#25919 chore: Revert "feat(lambda): provide support for AWS Parameters and Secrets Extension for Lambda"
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda/test/integ.params-and-secrets.js.snapshot/IntegTestDefaultTestDeployAssertE3E7D2A4.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda/test/integ.params-and-secrets.js.snapshot/IntegTestDefaultTestDeployAssertE3E7D2A4.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda/test/integ.params-and-secrets.js.snapshot/Stack1.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda/test/integ.params-and-secrets.js.snapshot/Stack1.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda/test/integ.params-and-secrets.js.snapshot/Stack2.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda/test/integ.params-and-secrets.js.snapshot/Stack2.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda/test/integ.params-and-secrets.js.snapshot/asset.b375dfd7699947c404936c2d1c4a0b91bd2bb49158ce52f6064bda6d3a7e0ead/index.py
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda/test/integ.params-and-secrets.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda/test/integ.params-and-secrets.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda/test/integ.params-and-secrets.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda/test/integ.params-and-secrets.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda/test/integ.params-and-secrets.ts
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda/test/params-and-secrets-handler/index.py
  packages/aws-cdk-lib/aws-lambda/README.md
  packages/aws-cdk-lib/aws-lambda/lib/function.ts
  packages/aws-cdk-lib/aws-lambda/lib/index.ts
  packages/aws-cdk-lib/aws-lambda/lib/params-and-secrets-layers.ts
  packages/aws-cdk-lib/aws-lambda/test/params-and-secrets.test.ts
  packages/aws-cdk-lib/region-info/build-tools/fact-tables.ts
  packages/aws-cdk-lib/region-info/build-tools/generate-static-data.ts
  packages/aws-cdk-lib/region-info/lib/fact.ts
  packages/aws-cdk-lib/region-info/lib/region-info.ts
Labels: p2, contribution/core

#25928 feat(lambda): provide support for AWS Parameters and Secrets Extension for Lambda
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda/test/integ.params-and-secrets.js.snapshot/IntegTestDefaultTestDeployAssertE3E7D2A4.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda/test/integ.params-and-secrets.js.snapshot/IntegTestDefaultTestDeployAssertE3E7D2A4.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda/test/integ.params-and-secrets.js.snapshot/Stack1.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda/test/integ.params-and-secrets.js.snapshot/Stack1.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda/test/integ.params-and-secrets.js.snapshot/Stack2.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda/test/integ.params-and-secrets.js.snapshot/Stack2.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda/test/integ.params-and-secrets.js.snapshot/asset.b375dfd7699947c404936c2d1c4a0b91bd2bb49158ce52f6064bda6d3a7e0ead/index.py
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda/test/integ.params-and-secrets.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda/test/integ.params-and-secrets.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda/test/integ.params-and-secrets.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda/test/integ.params-and-secrets.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda/test/integ.params-and-secrets.ts
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda/test/params-and-secrets-handler/index.py
  packages/aws-cdk-lib/aws-lambda/README.md
  packages/aws-cdk-lib/aws-lambda/lib/function.ts
  packages/aws-cdk-lib/aws-lambda/lib/index.ts
  packages/aws-cdk-lib/aws-lambda/lib/params-and-secrets-layers.ts
  packages/aws-cdk-lib/aws-lambda/test/params-and-secrets.test.ts
  packages/aws-cdk-lib/region-info/build-tools/fact-tables.ts
  packages/aws-cdk-lib/region-info/build-tools/generate-static-data.ts
  packages/aws-cdk-lib/region-info/lib/fact.ts
  packages/aws-cdk-lib/region-info/lib/region-info.ts
Labels: p1, feature-request, pr/needs-review, effort/medium, contribution/core

#25913 chore: Remove `npm bin` from scripts
  build.sh
  scripts/gen.sh
Labels: p2, pr/needs-review, valued-contributor

#25877 chore(apprunner): add validation cpu and memory for app runner
  packages/@aws-cdk/aws-apprunner-alpha/lib/service.ts
  packages/@aws-cdk/aws-apprunner-alpha/test/service.test.ts
Labels: p2, feature-request, pr/needs-review, effort/medium, beginning-contributor

#25880 fix(codebuild): add possibility to specify `BUILD_GENERAL1_SMALL` compute type with Linux GPU build image
  packages/aws-cdk-lib/aws-codebuild/lib/linux-gpu-build-image.ts
  packages/aws-cdk-lib/aws-codebuild/test/linux-gpu-build-image.test.ts
Labels: bug, p1, effort/small, pr-linter/exempt-integ-test, admired-contributor, pr-linter/exemption-requested, pr/reviewer-clarification-requested

#25660 feat(events-targets): support assignPublicIp flag to EcsTask
  packages/@aws-cdk-testing/framework-integ/test/aws-events-targets/test/ecs/integ.event-fargate-task.js.snapshot/aws-ecs-integ-fargate.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-events-targets/test/ecs/integ.event-fargate-task.js.snapshot/aws-ecs-integ-fargate.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-events-targets/test/ecs/integ.event-fargate-task.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-events-targets/test/ecs/integ.event-fargate-task.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-events-targets/test/ecs/integ.event-fargate-task.ts
  packages/aws-cdk-lib/aws-events-targets/README.md
  packages/aws-cdk-lib/aws-events-targets/lib/ecs-task.ts
  packages/aws-cdk-lib/aws-events-targets/test/ecs/event-rule-target.test.ts
Labels: p1, feature-request, effort/small, pr/needs-review, repeat-contributor

#25911 fix(stepfunctions-tasks): incorrect policy generated for athena startqueryexecution task
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/athena/integ.start-query-execution.js.snapshot/aws-stepfunctions-tasks-athena-start-query-execution-integ.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/athena/integ.start-query-execution.js.snapshot/aws-stepfunctions-tasks-athena-start-query-execution-integ.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/athena/integ.start-query-execution.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/athena/integ.start-query-execution.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/athena/integ.start-query-execution.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/athena/integ.start-query-execution.js.snapshot/tree.json
  packages/aws-cdk-lib/aws-stepfunctions-tasks/lib/athena/start-query-execution.ts
  packages/aws-cdk-lib/aws-stepfunctions-tasks/test/athena/start-query-execution.test.ts
Labels: bug, p1, effort/small, contribution/core, pr-linter/exempt-integ-test, pr-linter/exemption-requested

#25762 docs(elbv2): metricRequestCountPerTarget docstring points to correct replacement function
  packages/aws-cdk-lib/aws-elasticloadbalancingv2/lib/alb/application-target-group.ts
Labels: p2, effort/small

#25359 fix(core): Add stage prefix to stack name shortening process
  packages/aws-cdk-lib/core/lib/private/unique-resource-name.ts
  packages/aws-cdk-lib/core/lib/stack.ts
  packages/aws-cdk-lib/core/test/stage.test.ts
  packages/aws-cdk-lib/cx-api/FEATURE_FLAGS.md
  packages/aws-cdk-lib/cx-api/README.md
  packages/aws-cdk-lib/cx-api/lib/features.ts
Labels: bug, p2, pr/needs-review, pr-linter/exempt-integ-test, beginning-contributor, pr-linter/exemption-requested, pr/reviewer-clarification-requested

#25944 fix(batch): computeEnvironmentName is not set in FargateComputeEnvironment
  packages/@aws-cdk/aws-batch-alpha/lib/managed-compute-environment.ts
  packages/@aws-cdk/aws-batch-alpha/test/integ.managed-compute-environment.js.snapshot/BatchManagedComputeEnvironmentTestDefaultTestDeployAssertD4528F80.assets.json
  packages/@aws-cdk/aws-batch-alpha/test/integ.managed-compute-environment.js.snapshot/batch-stack.assets.json
  packages/@aws-cdk/aws-batch-alpha/test/integ.managed-compute-environment.js.snapshot/batch-stack.template.json
  packages/@aws-cdk/aws-batch-alpha/test/integ.managed-compute-environment.js.snapshot/cdk.out
  packages/@aws-cdk/aws-batch-alpha/test/integ.managed-compute-environment.js.snapshot/integ.json
  packages/@aws-cdk/aws-batch-alpha/test/integ.managed-compute-environment.js.snapshot/manifest.json
  packages/@aws-cdk/aws-batch-alpha/test/integ.managed-compute-environment.js.snapshot/tree.json
  packages/@aws-cdk/aws-batch-alpha/test/managed-compute-environment.test.ts
Labels: bug, p1, effort/small, pr-linter/exempt-integ-test, beginning-contributor

#25856 docs(ecs): fix a property doc in ExecuteCommandLogConfiguration
  packages/aws-cdk-lib/aws-ecs/lib/cluster.ts
Labels: p2, pr/needs-review, beginning-contributor

#25921 chore(merge-back): 2.83.1
  CHANGELOG.v2.alpha.md
  CHANGELOG.v2.md
  version.v2.json
Labels: p2, pr/needs-review, pr/no-squash, auto-approve

#25891 fix(ecs): remove accidental duplication of cloudmap namespaces with service connect
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs/test/fargate/integ.service-connect.js.snapshot/ServiceConnectDefaultTestDeployAssert88F6A66F.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs/test/fargate/integ.service-connect.js.snapshot/ServiceConnectDefaultTestDeployAssert88F6A66F.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs/test/fargate/integ.service-connect.js.snapshot/asset.36618132bd37b6b15f9987b57ad1fbf613f1ad937aec72381232b163ed9c44c4.bundle/index.js
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs/test/fargate/integ.service-connect.js.snapshot/aws-ecs-service-connect.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs/test/fargate/integ.service-connect.js.snapshot/aws-ecs-service-connect.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs/test/fargate/integ.service-connect.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs/test/fargate/integ.service-connect.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs/test/fargate/integ.service-connect.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs/test/fargate/integ.service-connect.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs/test/fargate/integ.service-connect.ts
  packages/aws-cdk-lib/aws-ecs/lib/cluster.ts
  packages/aws-cdk-lib/aws-ecs/test/cluster.test.ts
Labels: bug, p2, pr/needs-review, effort/medium, beginning-contributor

#25922 fix(autoscaling): AutoScalingGroup maxCapacity defaults to minCapacity when using Token
  packages/@aws-cdk-testing/framework-integ/test/aws-autoscaling/test/integ.capacity.js.snapshot/AutoScalingGroupCapacityDefaultTestDeployAssert4677C00C.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-autoscaling/test/integ.capacity.js.snapshot/AutoScalingGroupCapacityDefaultTestDeployAssert4677C00C.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-autoscaling/test/integ.capacity.js.snapshot/aws-cdk-autoscaling-integ.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-autoscaling/test/integ.capacity.js.snapshot/aws-cdk-autoscaling-integ.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-autoscaling/test/integ.capacity.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-autoscaling/test/integ.capacity.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-autoscaling/test/integ.capacity.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-autoscaling/test/integ.capacity.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-autoscaling/test/integ.capacity.ts
  packages/aws-cdk-lib/aws-autoscaling/lib/auto-scaling-group.ts
  packages/aws-cdk-lib/aws-autoscaling/test/auto-scaling-group.test.ts
Labels: p2, pr/needs-review, valued-contributor, pr-linter/exemption-requested

#25961 feat(s3): support s3 bucket double encryption mode aws:kms:dsse (…
  packages/@aws-cdk-testing/framework-integ/test/aws-s3/test/integ.bucket-encryption.js.snapshot/IntegTestDSSEBucketDefaultTestDeployAssert56801A2F.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-s3/test/integ.bucket-encryption.js.snapshot/IntegTestDSSEBucketDefaultTestDeployAssert56801A2F.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-s3/test/integ.bucket-encryption.js.snapshot/aws-cdk-s3-bucket-encryption.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-s3/test/integ.bucket-encryption.js.snapshot/aws-cdk-s3-bucket-encryption.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-s3/test/integ.bucket-encryption.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-s3/test/integ.bucket-encryption.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-s3/test/integ.bucket-encryption.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-s3/test/integ.bucket-encryption.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-s3/test/integ.bucket-encryption.ts
  packages/aws-cdk-lib/aws-s3/README.md
  packages/aws-cdk-lib/aws-s3/lib/bucket.ts
  packages/aws-cdk-lib/aws-s3/test/bucket.test.ts
Labels: p2, pr/needs-review, contribution/core

#25973 chore: fix security (non-)issue with poetry.lock in test
  packages/@aws-cdk/aws-lambda-python-alpha/test/lambda-handler-poetry/poetry.lock
  packages/@aws-cdk/aws-lambda-python-alpha/test/lambda-handler-poetry/pyproject.toml
Labels: p2, contribution/core

#25708 fix(core): prevent the error when the condition is split into groups of 10 and 1 in `Fn.conditionOr()`
  packages/aws-cdk-lib/core/lib/cfn-fn.ts
  packages/aws-cdk-lib/core/test/condition.test.ts
Labels: bug, p2, effort/small, pr/needs-review, pr-linter/exempt-integ-test, beginning-contributor, pr-linter/exemption-requested

#25841 fix(s3): fail fast for s3 lifecycle configuration when ExpiredObjectDeleteMarker specified with ExpirationInDays, ExpirationDate, or TagFilters.
  packages/aws-cdk-lib/aws-s3/lib/bucket.ts
  packages/aws-cdk-lib/aws-s3/test/rules.test.ts
Labels: bug, p2, effort/small, pr-linter/exempt-integ-test, repeat-contributor, pr-linter/exemption-requested

#25932 feat(stepfunctions): support string and file definitions
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions/test/integ.state-machine-string.js.snapshot/IntegTestDefaultTestDeployAssertE3E7D2A4.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions/test/integ.state-machine-string.js.snapshot/IntegTestDefaultTestDeployAssertE3E7D2A4.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions/test/integ.state-machine-string.js.snapshot/aws-stepfunctions-integ.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions/test/integ.state-machine-string.js.snapshot/aws-stepfunctions-integ.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions/test/integ.state-machine-string.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions/test/integ.state-machine-string.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions/test/integ.state-machine-string.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions/test/integ.state-machine-string.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions/test/integ.state-machine-string.ts
  packages/aws-cdk-lib/aws-apigateway/test/integrations/stepfunctions.test.ts
  packages/aws-cdk-lib/aws-apigateway/test/stepfunctions-api.test.ts
  packages/aws-cdk-lib/aws-codepipeline-actions/test/stepfunctions/stepfunctions-invoke-actions.test.ts
  packages/aws-cdk-lib/aws-events-targets/test/stepfunctions/statemachine.test.ts
  packages/aws-cdk-lib/aws-stepfunctions-tasks/test/athena/start-query-execution.test.ts
  packages/aws-cdk-lib/aws-stepfunctions-tasks/test/aws-sdk/call-aws-service.test.ts
  packages/aws-cdk-lib/aws-stepfunctions-tasks/test/ecs/ecs-tasks.test.ts
  packages/aws-cdk-lib/aws-stepfunctions-tasks/test/ecs/run-tasks.test.ts
  packages/aws-cdk-lib/aws-stepfunctions-tasks/test/emr/emr-add-step.test.ts
  packages/aws-cdk-lib/aws-stepfunctions-tasks/test/emr/emr-cancel-step.test.ts
  packages/aws-cdk-lib/aws-stepfunctions-tasks/test/emr/emr-modify-instance-fleet-by-name.test.ts
  packages/aws-cdk-lib/aws-stepfunctions-tasks/test/emr/emr-modify-instance-group-by-name.test.ts
  packages/aws-cdk-lib/aws-stepfunctions-tasks/test/emr/emr-set-cluster-termination-protection.test.ts
  packages/aws-cdk-lib/aws-stepfunctions-tasks/test/emr/emr-terminate-cluster.test.ts
  packages/aws-cdk-lib/aws-stepfunctions-tasks/test/emrcontainers/create-virtual-cluster.test.ts
  packages/aws-cdk-lib/aws-stepfunctions-tasks/test/emrcontainers/delete-virtual-cluster.test.ts
  packages/aws-cdk-lib/aws-stepfunctions-tasks/test/emrcontainers/start-job-run.test.ts
  packages/aws-cdk-lib/aws-stepfunctions-tasks/test/evaluate-expression.test.ts
  packages/aws-cdk-lib/aws-stepfunctions-tasks/test/eventbridge/put-events.test.ts
  packages/aws-cdk-lib/aws-stepfunctions-tasks/test/glue/run-glue-job-task.test.ts
  packages/aws-cdk-lib/aws-stepfunctions-tasks/test/glue/start-job-run.test.ts
  packages/aws-cdk-lib/aws-stepfunctions-tasks/test/invoke-activity.test.ts
  packages/aws-cdk-lib/aws-stepfunctions-tasks/test/lambda/invoke-function.test.ts
  packages/aws-cdk-lib/aws-stepfunctions-tasks/test/lambda/run-lambda-task.test.ts
  packages/aws-cdk-lib/aws-stepfunctions-tasks/test/start-execution.test.ts
  packages/aws-cdk-lib/aws-stepfunctions-tasks/test/stepfunctions/invoke-activity.test.ts
  packages/aws-cdk-lib/aws-stepfunctions-tasks/test/stepfunctions/start-execution.test.ts
  packages/aws-cdk-lib/aws-stepfunctions/README.md
  packages/aws-cdk-lib/aws-stepfunctions/lib/state-machine.ts
  packages/aws-cdk-lib/aws-stepfunctions/test/state-machine-fragment.test.ts
  packages/aws-cdk-lib/aws-stepfunctions/test/state-machine-resources.test.ts
  packages/aws-cdk-lib/aws-stepfunctions/test/state-machine.test.ts
  packages/aws-cdk-lib/aws-stepfunctions/test/state.test.ts
Labels: p1, feature-request, effort/large, distinguished-contributor

#25977 chore(eks): masters role docs
  packages/aws-cdk-lib/aws-eks/README.md
  packages/aws-cdk-lib/aws-eks/lib/cluster.ts
Labels: p2, contribution/core

#25981 chore(merge-back): 2.84.0
  CHANGELOG.v2.alpha.md
  CHANGELOG.v2.md
  packages/aws-cdk-lib/cx-api/FEATURE_FLAGS.md
  packages/aws-cdk-lib/cx-api/lib/features.ts
  version.v2.json
Labels: p2, pr/needs-review, pr/no-squash, auto-approve

#25982 chore: update cdk-generate-synthetic-examples
  package.json
  yarn.lock
Labels: p2, contribution/core

#25697 feat(ec2): add addSecurityGroup method to launth template
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.launch-template.js.snapshot/LambdaTestDefaultTestDeployAssert1AF2B360.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.launch-template.js.snapshot/aws-cdk-ec2-lt-metadata-1.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.launch-template.js.snapshot/aws-cdk-ec2-lt-metadata-1.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.launch-template.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.launch-template.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.launch-template.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.launch-template.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.launch-template.ts
  packages/aws-cdk-lib/aws-ec2/README.md
  packages/aws-cdk-lib/aws-ec2/lib/launch-template.ts
Labels: p2, feature-request, effort/small, pr/needs-review, beginning-contributor

#25912 chore: hide diffs of mangled unicode strings
  packages/@aws-cdk/cloudformation-diff/lib/diff/util.ts
  packages/@aws-cdk/cloudformation-diff/lib/index.ts
  packages/@aws-cdk/cloudformation-diff/test/util-test.ts
  packages/aws-cdk/lib/cli.ts
  packages/aws-cdk/lib/diff.ts
Labels: bug, p1, effort/medium, beginning-contributor, pr-linter/cli-integ-tested

#25964 fix(ecr): autoDeleteImages fails on multiple repositories
  packages/aws-cdk-lib/aws-ecr/lib/repository.ts
  packages/aws-cdk-lib/aws-ecr/test/repository.test.ts
Labels: p2, contribution/core, pr-linter/exempt-integ-test

#25984 chore: upgrade lerna & nx to next major
  lerna.json
  nx.json
  package.json
  packages/@aws-cdk/integ-runner/THIRD_PARTY_LICENSES
  packages/aws-cdk/THIRD_PARTY_LICENSES
  yarn.lock
Labels: p2, contribution/core

#25976 fix(ec2): securityGroups is mandatory in fromClusterAttributes
  packages/aws-cdk-lib/aws-ecs/lib/cluster.ts
  packages/aws-cdk-lib/aws-ecs/test/cluster.test.ts
Labels: pr/needs-review, contribution/core, pr-linter/exempt-integ-test

#25993 chore: run yarn install before trying to use lerna
  scripts/align-version.sh
Labels: p2, contribution/core

#25992 chore: add app-staging-synthesizer to issue-label-assign
  .github/workflows/issue-label-assign.yml
Labels: p2, contribution/core

#25994 chore(cx-api): feature flags are documented incorrectly
  packages/aws-cdk-lib/cx-api/FEATURE_FLAGS.md
  packages/aws-cdk-lib/cx-api/lib/features.ts
Labels: p2, contribution/core

#26000 chore: fix json in issue-label-assign
  .github/workflows/issue-label-assign.yml
Labels: p2, beginning-contributor

#26016 fix(lambda): corrected environment variable naming for params and secrets extension
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda/test/integ.params-and-secrets.js.snapshot/Stack1.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda/test/integ.params-and-secrets.js.snapshot/Stack1.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda/test/integ.params-and-secrets.js.snapshot/Stack2.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda/test/integ.params-and-secrets.js.snapshot/Stack2.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda/test/integ.params-and-secrets.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda/test/integ.params-and-secrets.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda/test/integ.params-and-secrets.ts
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda/test/params-and-secrets-handler/index.py
  packages/aws-cdk-lib/aws-lambda/lib/params-and-secrets-layers.ts
  packages/aws-cdk-lib/aws-lambda/test/params-and-secrets.test.ts
Labels: bug, p1, effort/small, contribution/core

#26018 chore: revert to last known working jsii versions
  package.json
  packages/awslint/package.json
  packages/cdk-dasm/package.json
  tools/@aws-cdk/cdk-build-tools/package.json
  tools/@aws-cdk/cfn2ts/package.json
  yarn.lock
Labels: p2, contribution/core

#26019 chore: re-roll jsii upgrades & fixup integ test comment
  package.json
  packages/@aws-cdk/aws-codepipeline-actions/test/integ.pipeline-ecs-separate-source.lit.ts
  packages/aws-cdk/package.json
  packages/awslint/package.json
  packages/cdk-dasm/package.json
  tools/@aws-cdk/cdk-build-tools/package.json
  tools/@aws-cdk/cfn2ts/package.json
  yarn.lock
Labels: p2, contribution/core

#26021 chore: fix broken v1 lints
  packages/aws-cdk/THIRD_PARTY_LICENSES
  packages/aws-cdk/lib/api/aws-auth/credential-plugins.ts
  packages/aws-cdk/lib/api/bootstrap/bootstrap-environment.ts
  packages/aws-cdk/lib/api/bootstrap/deploy-bootstrap.ts
  packages/aws-cdk/lib/api/cloudformation-deployments.ts
  packages/aws-cdk/lib/api/cxapp/cloud-executable.ts
  packages/aws-cdk/lib/api/cxapp/environments.ts
  packages/aws-cdk/lib/api/deploy-stack.ts
  packages/aws-cdk/lib/api/hotswap-deployments.ts
  packages/aws-cdk/lib/api/hotswap/appsync-mapping-templates.ts
  packages/aws-cdk/lib/api/hotswap/code-build-projects.ts
  packages/aws-cdk/lib/api/hotswap/ecs-services.ts
  packages/aws-cdk/lib/api/hotswap/lambda-functions.ts
  packages/aws-cdk/lib/api/hotswap/s3-bucket-deployments.ts
  packages/aws-cdk/lib/api/hotswap/stepfunctions-state-machines.ts
  packages/aws-cdk/lib/api/toolkit-info.ts
  packages/aws-cdk/lib/api/util/cloudformation.ts
  packages/aws-cdk/lib/cdk-toolkit.ts
  packages/aws-cdk/lib/context-providers/index.ts
  packages/aws-cdk/lib/version.ts
  packages/aws-cdk/test/account-cache.test.ts
  packages/aws-cdk/test/api/cloudformation-deployments.test.ts
  packages/aws-cdk/test/api/hotswap/nested-stacks-hotswap.test.ts
  packages/aws-cdk/test/api/hotswap/s3-bucket-hotswap-deployments.test.ts
  packages/aws-cdk/test/api/sdk-provider.test.ts
  packages/aws-cdk/test/api/stack-activity-monitor.test.ts
  packages/aws-cdk/test/assets.test.ts
  packages/aws-cdk/test/cdk-toolkit.test.ts
  packages/aws-cdk/test/diff.test.ts
  packages/aws-cdk/test/import.test.ts
  packages/aws-cdk/test/util.ts
  packages/aws-cdk/test/util/cloudformation.test.ts
  packages/aws-cdk/test/util/stack-monitor.test.ts
Labels: p2, contribution/core

#26017 chore(elasticloadbalancingv2): moved health check docstring over health check attribute
  packages/aws-cdk-lib/aws-elasticloadbalancingv2/lib/shared/base-target-group.ts
Labels: p2, pr/needs-review, contribution/core

#25909 chore(aws-cdk-lib): Add New ADOT Lambda Layer v0.30.0 ARNs
  packages/aws-cdk-lib/region-info/build-tools/fact-tables.ts
Labels: p2, beginning-contributor

#26041 docs: update missing link
  CONTRIBUTING.md
Labels: p2, pr/needs-review, beginning-contributor

#26046 chore(merge-back): 1.204.0
  CHANGELOG.md
  packages/@aws-cdk/aws-codepipeline-actions/test/integ.pipeline-ecs-separate-source.lit.ts
  packages/@aws-cdk/cfnspec/skip-evolution-check.txt
  packages/aws-cdk/THIRD_PARTY_LICENSES
  packages/aws-cdk/lib/api/aws-auth/credential-plugins.ts
  packages/aws-cdk/lib/api/bootstrap/bootstrap-environment.ts
  packages/aws-cdk/lib/api/bootstrap/deploy-bootstrap.ts
  packages/aws-cdk/lib/api/cloudformation-deployments.ts
  packages/aws-cdk/lib/api/cxapp/cloud-executable.ts
  packages/aws-cdk/lib/api/cxapp/environments.ts
  packages/aws-cdk/lib/api/deploy-stack.ts
  packages/aws-cdk/lib/api/hotswap-deployments.ts
  packages/aws-cdk/lib/api/hotswap/appsync-mapping-templates.ts
  packages/aws-cdk/lib/api/hotswap/code-build-projects.ts
  packages/aws-cdk/lib/api/hotswap/ecs-services.ts
  packages/aws-cdk/lib/api/hotswap/lambda-functions.ts
  packages/aws-cdk/lib/api/hotswap/s3-bucket-deployments.ts
  packages/aws-cdk/lib/api/hotswap/stepfunctions-state-machines.ts
  packages/aws-cdk/lib/api/toolkit-info.ts
  packages/aws-cdk/lib/api/util/cloudformation.ts
  packages/aws-cdk/lib/cdk-toolkit.ts
  packages/aws-cdk/lib/context-providers/index.ts
  packages/aws-cdk/lib/version.ts
  packages/aws-cdk/package.json
  packages/aws-cdk/test/account-cache.test.ts
  packages/aws-cdk/test/api/cloudformation-deployments.test.ts
  packages/aws-cdk/test/api/hotswap/nested-stacks-hotswap.test.ts
  packages/aws-cdk/test/api/hotswap/s3-bucket-hotswap-deployments.test.ts
  packages/aws-cdk/test/api/sdk-provider.test.ts
  packages/aws-cdk/test/api/stack-activity-monitor.test.ts
  packages/aws-cdk/test/assets.test.ts
  packages/aws-cdk/test/cdk-toolkit.test.ts
  packages/aws-cdk/test/diff.test.ts
  packages/aws-cdk/test/import.test.ts
  packages/aws-cdk/test/util.ts
  packages/aws-cdk/test/util/cloudformation.test.ts
  packages/aws-cdk/test/util/stack-monitor.test.ts
  scripts/align-version.sh
  version.v1.json
  yarn.lock
Labels: p2, pr/no-squash, auto-approve

#26056 chore(region-info): remove regions that don't have CDK Metadata
  packages/aws-cdk-lib/region-info/build-tools/fact-tables.ts
  packages/aws-cdk-lib/region-info/test/__snapshots__/region-info.test.js.snap
Labels: p2, contribution/core

#26015 fix(apprunner): incorrect serviceName
  packages/@aws-cdk/aws-apprunner-alpha/lib/service.ts
  packages/@aws-cdk/aws-apprunner-alpha/test/integ.service-ecr-public.js.snapshot/cdk.out
  packages/@aws-cdk/aws-apprunner-alpha/test/integ.service-ecr-public.js.snapshot/integ-apprunner-ecr-public.assets.json
  packages/@aws-cdk/aws-apprunner-alpha/test/integ.service-ecr-public.js.snapshot/integ-apprunner-ecr-public.template.json
  packages/@aws-cdk/aws-apprunner-alpha/test/integ.service-ecr-public.js.snapshot/integ.json
  packages/@aws-cdk/aws-apprunner-alpha/test/integ.service-ecr-public.js.snapshot/manifest.json
  packages/@aws-cdk/aws-apprunner-alpha/test/integ.service-ecr-public.js.snapshot/tree.json
  packages/@aws-cdk/aws-apprunner-alpha/test/integ.service-ecr-public.ts
  packages/@aws-cdk/aws-apprunner-alpha/test/service.test.ts
Labels: bug, p1, effort/small, contribution/core

#25399 feat(batch): `ephemeralStorage` property on job definitions
  packages/@aws-cdk/aws-batch-alpha/lib/ecs-container-definition.ts
  packages/@aws-cdk/aws-batch-alpha/test/ecs-container-definition.test.ts
  packages/@aws-cdk/aws-batch-alpha/test/integ.ecs-job-definition.js.snapshot/manifest.json
  packages/@aws-cdk/aws-batch-alpha/test/integ.ecs-job-definition.js.snapshot/stack.assets.json
  packages/@aws-cdk/aws-batch-alpha/test/integ.ecs-job-definition.js.snapshot/stack.template.json
  packages/@aws-cdk/aws-batch-alpha/test/integ.ecs-job-definition.js.snapshot/tree.json
  packages/@aws-cdk/aws-batch-alpha/test/integ.ecs-job-definition.ts
Labels: p2, feature-request, effort/small, contribution/core, pr-linter/exempt-readme

#26024 chore(app-staging-synthesizer): reduce the size of DefaultStagingStack template by 5KB
  packages/@aws-cdk/app-staging-synthesizer-alpha/lib/default-staging-stack.ts
  packages/@aws-cdk/app-staging-synthesizer-alpha/test/app-staging-synthesizer.test.ts
  packages/@aws-cdk/app-staging-synthesizer-alpha/test/integ.synth-default-resources.js.snapshot/cdk.out
  packages/@aws-cdk/app-staging-synthesizer-alpha/test/integ.synth-default-resources.js.snapshot/integ.json
  packages/@aws-cdk/app-staging-synthesizer-alpha/test/integ.synth-default-resources.js.snapshot/integtestsDefaultTestDeployAssert44C8D370.assets.json
  packages/@aws-cdk/app-staging-synthesizer-alpha/test/integ.synth-default-resources.js.snapshot/manifest.json
  packages/@aws-cdk/app-staging-synthesizer-alpha/test/integ.synth-default-resources.js.snapshot/synthesize-default-resources.assets.json
  packages/@aws-cdk/app-staging-synthesizer-alpha/test/integ.synth-default-resources.js.snapshot/tree.json
Labels: p2, contribution/core

#26060 fix(cli): deployment continues if ECR asset fails to build or publish
  packages/aws-cdk/lib/api/deployments.ts
  packages/aws-cdk/test/work-graph.test.ts
Labels: bug, p1, effort/medium, contribution/core, pr-linter/exempt-integ-test, pr-linter/cli-integ-tested

#26069 chore: npm-check-updates && yarn upgrade
  packages/@aws-cdk/cx-api/FEATURE_FLAGS.md
  packages/@aws-cdk/integ-runner/THIRD_PARTY_LICENSES
  packages/aws-cdk/THIRD_PARTY_LICENSES
  yarn.lock
Labels: p2, dependencies, contribution/core, auto-approve

#26073 chore(merge-back): 2.85.0
  .github/workflows/cr-checklist.yml
  .github/workflows/cr-mapping.json
  CHANGELOG.v2.alpha.md
  CHANGELOG.v2.md
  version.v2.json
Labels: p2, pr/needs-review, pr/no-squash, auto-approve

#26050 chore(rds): Add support for RDS MySQL minor versions of 8.0.33 and 5.7.42
  packages/aws-cdk-lib/aws-rds/lib/instance-engine.ts
Labels: p2, pr/needs-review, beginning-contributor

#26087 feat(integ-runner): integ-runner --watch
  packages/@aws-cdk/cdk-cli-wrapper/lib/cdk-wrapper.ts
  packages/@aws-cdk/cdk-cli-wrapper/lib/commands/deploy.ts
  packages/@aws-cdk/cdk-cli-wrapper/lib/utils.ts
  packages/@aws-cdk/cdk-cli-wrapper/test/cdk-wrapper.test.ts
  packages/@aws-cdk/integ-runner/README.md
  packages/@aws-cdk/integ-runner/THIRD_PARTY_LICENSES
  packages/@aws-cdk/integ-runner/lib/cli.ts
  packages/@aws-cdk/integ-runner/lib/runner/integ-test-runner.ts
  packages/@aws-cdk/integ-runner/lib/runner/integration-tests.ts
  packages/@aws-cdk/integ-runner/lib/workers/common.ts
  packages/@aws-cdk/integ-runner/lib/workers/extract/extract_worker.ts
  packages/@aws-cdk/integ-runner/lib/workers/integ-test-worker.ts
  packages/@aws-cdk/integ-runner/lib/workers/integ-watch-worker.ts
  packages/@aws-cdk/integ-runner/package.json
  packages/@aws-cdk/integ-runner/test/helpers.ts
  packages/@aws-cdk/integ-runner/test/runner/integ-test-runner.test.ts
Labels: p2, pr/needs-review, contribution/core, pr-linter/exempt-integ-test

#26014 fix(core): network option is not being propagated to Docker
  packages/aws-cdk-lib/core/lib/private/asset-staging.ts
  packages/aws-cdk-lib/core/test/private/asset-staging.test.ts
Labels: bug, p1, effort/small, pr/needs-review, contribution/core, pr-linter/exempt-integ-test

#25859 chore: experimental cdk migrate command
  .gitmodules
  package.json
  packages/@aws-cdk-testing/cli-integ/lib/corking.ts
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-nodejs/tsconfig-custom.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-nodejs/tsconfig.json
  packages/@aws-cdk/cli-lib-alpha/generate.sh
  packages/@aws-cdk/cli-lib-alpha/package.json
  packages/aws-cdk-lib/aws-lambda-nodejs/lib/bundling.ts
  packages/aws-cdk-lib/aws-lambda-nodejs/lib/util.ts
  packages/aws-cdk-lib/aws-lambda-nodejs/test/bundling.test.ts
  packages/aws-cdk-lib/aws-lambda-nodejs/test/util.test.ts
  packages/aws-cdk-lib/package.json
  packages/aws-cdk-migration/package.json
  packages/aws-cdk/.eslintrc.js
  packages/aws-cdk/.gitignore
  packages/aws-cdk/.npmignore
  packages/aws-cdk/generate.sh
  packages/aws-cdk/lib/cli.ts
  packages/aws-cdk/lib/commands/migrate.ts
  packages/aws-cdk/lib/init-templates/app/typescript/package.json
  packages/aws-cdk/lib/init-templates/lib/typescript/package.json
  packages/aws-cdk/lib/init-templates/sample-app/typescript/package.json
  packages/aws-cdk/lib/init.ts
  packages/aws-cdk/package.json
  packages/aws-cdk/tsconfig.json
  packages/aws-cdk/vendor/README.md
  packages/awslint/package.json
  tools/@aws-cdk/cdk-build-tools/lib/os.ts
  tools/@aws-cdk/cdk-build-tools/package.json
  tools/@aws-cdk/cdk-release/lib/lifecycles/bumphooks.ts
  tools/@aws-cdk/eslint-plugin/package.json
  tools/@aws-cdk/node-bundle/package.json
  tools/@aws-cdk/pkglint/package.json
  tools/@aws-cdk/prlint/package.json
  tools/@aws-cdk/yarn-cling/package.json
  yarn.lock
Labels: p2, contribution/core, pr-linter/cli-integ-tested

#26057 docs(codepipeline): fix module name in README "@aws-cdk/aws-codepipeline-actions" => "aws-cdk-lib/aws-codepipeline-actions"
  packages/aws-cdk-lib/aws-codepipeline/README.md
Labels: p2, pr/needs-review, beginning-contributor

#25985 fix(batch-alpha): cannot import FargateComputeEnvironment with fromFargateComputeEnvironmentArn
  packages/@aws-cdk/aws-batch-alpha/lib/managed-compute-environment.ts
  packages/@aws-cdk/aws-batch-alpha/test/managed-compute-environment.test.ts
Labels: bug, p1, effort/small, pr-linter/exempt-integ-test, admired-contributor, pr-linter/exemption-requested, pr/reviewer-clarification-requested

#26031 fix(elbv2): correct wrong timeout validation
  packages/@aws-cdk-testing/framework-integ/test/aws-elasticloadbalancingv2/test/integ.nlb.js.snapshot/aws-cdk-elbv2-integ.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-elasticloadbalancingv2/test/integ.nlb.js.snapshot/aws-cdk-elbv2-integ.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-elasticloadbalancingv2/test/integ.nlb.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-elasticloadbalancingv2/test/integ.nlb.js.snapshot/elbv2integDefaultTestDeployAssert6120E394.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-elasticloadbalancingv2/test/integ.nlb.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-elasticloadbalancingv2/test/integ.nlb.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-elasticloadbalancingv2/test/integ.nlb.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-elasticloadbalancingv2/test/integ.nlb.ts
  packages/aws-cdk-lib/aws-elasticloadbalancingv2/lib/nlb/network-target-group.ts
  packages/aws-cdk-lib/aws-elasticloadbalancingv2/lib/shared/base-target-group.ts
  packages/aws-cdk-lib/aws-elasticloadbalancingv2/test/nlb/listener.test.ts
Labels: bug, p1, effort/small, pr/needs-review, beginning-contributor

#26098 chore(rds): Rds version upgrade
  packages/aws-cdk-lib/aws-rds/lib/instance-engine.ts
Labels: p2, star-contributor

#26116 fix(cdk-lib): Pass lookupRoleArn to NestedStackSynthesizer
  packages/aws-cdk-lib/core/lib/stack-synthesizers/default-synthesizer.ts
  packages/aws-cdk-lib/core/lib/stack-synthesizers/nested.ts
  packages/aws-cdk-lib/core/lib/stack-synthesizers/stack-synthesizer.ts
  packages/aws-cdk-lib/core/lib/stack-synthesizers/types.ts
  packages/aws-cdk-lib/core/test/stack-synthesis/new-style-synthesis.test.ts
Labels: bug, p1, effort/medium, pr-linter/exempt-integ-test, beginning-contributor, pr-linter/exemption-requested

#26133 chore: fixup @aws-cdk/cdk-lib-alpha bundling
  packages/@aws-cdk/cli-lib-alpha/.gitignore
  packages/@aws-cdk/cli-lib-alpha/THIRD_PARTY_LICENSES
  packages/@aws-cdk/cli-lib-alpha/generate.sh
  packages/@aws-cdk/cli-lib-alpha/package.json
Labels: p2, pr/needs-review, contribution/core

#26138 chore: add workflow for handling discussions
  .github/workflows/handle-stale-discussions.yml
Labels: p2

#26129 feat(app-staging-synthesizer): select different bootstrap region
  packages/@aws-cdk/app-staging-synthesizer-alpha/README.md
  packages/@aws-cdk/app-staging-synthesizer-alpha/lib/app-staging-synthesizer.ts
  packages/@aws-cdk/app-staging-synthesizer-alpha/lib/bootstrap-roles.ts
  packages/@aws-cdk/app-staging-synthesizer-alpha/test/bootstrap-roles.test.ts
Labels: p2, pr/needs-review, contribution/core, pr-linter/exempt-integ-test

#26123 chore: build noctilucent WASM library in a container
  CONTRIBUTING.md
  packages/aws-cdk/.gitignore
  packages/aws-cdk/.npmignore
  packages/aws-cdk/generate.sh
  packages/aws-cdk/lib/vendor/noctilucent/.gitignore
  packages/aws-cdk/lib/vendor/noctilucent/Dockerfile
  packages/aws-cdk/vendor/README.md
Labels: p2, contribution/core

#25999 fix(core): prevent the error when the condition is split into groups of 10 and 1 in `Fn.conditionAnd()`
  packages/aws-cdk-lib/core/lib/cfn-fn.ts
  packages/aws-cdk-lib/core/test/condition.test.ts
Labels: bug, p2, effort/small, pr-linter/exempt-integ-test, beginning-contributor, pr-linter/exemption-requested

#26151 chore(integ-runner): add fsevents to optionalDependencies
  packages/@aws-cdk/integ-runner/package.json
Labels: p2, contribution/core

#26154 chore: added write permissions in the stale-discussions workflow
  .github/workflows/handle-stale-discussions.yml
Labels: p2

#26126 fix(batch): Allow ECS JobDefinition Containers to pass Secrets as Environment Variables & Enable Kubernetes Secret Volumes
  packages/@aws-cdk/aws-batch-alpha/README.md
  packages/@aws-cdk/aws-batch-alpha/lib/ecs-container-definition.ts
  packages/@aws-cdk/aws-batch-alpha/lib/eks-container-definition.ts
  packages/@aws-cdk/aws-batch-alpha/lib/eks-job-definition.ts
  packages/@aws-cdk/aws-batch-alpha/test/ecs-container-definition.test.ts
  packages/@aws-cdk/aws-batch-alpha/test/eks-container-definition.test.ts
  packages/@aws-cdk/aws-batch-alpha/test/integ.ecs-job-definition.js.snapshot/BatchEcsJobDefinitionTestDefaultTestDeployAssertE5BAAC9B.assets.json
  packages/@aws-cdk/aws-batch-alpha/test/integ.ecs-job-definition.js.snapshot/cdk.out
  packages/@aws-cdk/aws-batch-alpha/test/integ.ecs-job-definition.js.snapshot/integ.json
  packages/@aws-cdk/aws-batch-alpha/test/integ.ecs-job-definition.js.snapshot/manifest.json
  packages/@aws-cdk/aws-batch-alpha/test/integ.ecs-job-definition.js.snapshot/stack.assets.json
  packages/@aws-cdk/aws-batch-alpha/test/integ.ecs-job-definition.js.snapshot/stack.template.json
  packages/@aws-cdk/aws-batch-alpha/test/integ.ecs-job-definition.js.snapshot/tree.json
  packages/@aws-cdk/aws-batch-alpha/test/integ.ecs-job-definition.ts
  packages/@aws-cdk/aws-batch-alpha/test/integ.eks-job-definition.js.snapshot/BatchEcsJobDefinitionTestDefaultTestDeployAssertE5BAAC9B.assets.json
  packages/@aws-cdk/aws-batch-alpha/test/integ.eks-job-definition.js.snapshot/cdk.out
  packages/@aws-cdk/aws-batch-alpha/test/integ.eks-job-definition.js.snapshot/integ.json
  packages/@aws-cdk/aws-batch-alpha/test/integ.eks-job-definition.js.snapshot/manifest.json
  packages/@aws-cdk/aws-batch-alpha/test/integ.eks-job-definition.js.snapshot/stack.assets.json
  packages/@aws-cdk/aws-batch-alpha/test/integ.eks-job-definition.js.snapshot/stack.template.json
  packages/@aws-cdk/aws-batch-alpha/test/integ.eks-job-definition.js.snapshot/tree.json
  packages/@aws-cdk/aws-batch-alpha/test/integ.eks-job-definition.ts
  packages/@aws-cdk/aws-batch-alpha/test/job-definition-base.test.ts
Labels: bug, p1, pr/needs-review, effort/medium, contribution/core

#25571 chore(region-info): register me-central-1
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.instance-public.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.instance-public.js.snapshot/instancetestDefaultTestDeployAssert5516EAF1.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.instance-public.js.snapshot/integ-ec2-instance.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.instance-public.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.instance-public.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.instance-public.js.snapshot/tree.json
  packages/@aws-cdk/aws-iot-actions-alpha/test/kinesis-firehose/integ.firehose-put-record-action.js.snapshot/manifest.json
  packages/@aws-cdk/aws-iot-actions-alpha/test/kinesis-firehose/integ.firehose-put-record-action.js.snapshot/test-stack.assets.json
  packages/@aws-cdk/aws-iot-actions-alpha/test/kinesis-firehose/integ.firehose-put-record-action.js.snapshot/test-stack.template.json
  packages/@aws-cdk/aws-kinesisfirehose-alpha/test/integ.delivery-stream.js.snapshot/aws-cdk-firehose-delivery-stream.assets.json
  packages/@aws-cdk/aws-kinesisfirehose-alpha/test/integ.delivery-stream.js.snapshot/aws-cdk-firehose-delivery-stream.template.json
  packages/@aws-cdk/aws-kinesisfirehose-alpha/test/integ.delivery-stream.js.snapshot/cdk.out
  packages/@aws-cdk/aws-kinesisfirehose-alpha/test/integ.delivery-stream.js.snapshot/manifest.json
  packages/@aws-cdk/aws-kinesisfirehose-alpha/test/integ.delivery-stream.source-stream.js.snapshot/aws-cdk-firehose-delivery-stream-source-stream.assets.json
  packages/@aws-cdk/aws-kinesisfirehose-alpha/test/integ.delivery-stream.source-stream.js.snapshot/aws-cdk-firehose-delivery-stream-source-stream.template.json
  packages/@aws-cdk/aws-kinesisfirehose-alpha/test/integ.delivery-stream.source-stream.js.snapshot/manifest.json
  packages/@aws-cdk/aws-kinesisfirehose-destinations-alpha/test/integ.s3-bucket.lit.js.snapshot/aws-cdk-firehose-delivery-stream-s3-all-properties.assets.json
  packages/@aws-cdk/aws-kinesisfirehose-destinations-alpha/test/integ.s3-bucket.lit.js.snapshot/aws-cdk-firehose-delivery-stream-s3-all-properties.template.json
  packages/@aws-cdk/aws-kinesisfirehose-destinations-alpha/test/integ.s3-bucket.lit.js.snapshot/manifest.json
  packages/aws-cdk-lib/cx-api/FEATURE_FLAGS.md
  packages/aws-cdk-lib/region-info/build-tools/fact-tables.ts
  packages/aws-cdk-lib/region-info/test/__snapshots__/region-info.test.js.snap
Labels: p1, feature-request, pr/needs-review, effort/medium, contribution/core

#25867 fix(glue): support Ray jobs with Runtime parameter
  packages/@aws-cdk/aws-glue-alpha/README.md
  packages/@aws-cdk/aws-glue-alpha/lib/job-executable.ts
  packages/@aws-cdk/aws-glue-alpha/lib/job.ts
  packages/@aws-cdk/aws-glue-alpha/test/integ.job.js.snapshot/aws-glue-job.assets.json
  packages/@aws-cdk/aws-glue-alpha/test/integ.job.js.snapshot/aws-glue-job.template.json
  packages/@aws-cdk/aws-glue-alpha/test/integ.job.js.snapshot/cdk.out
  packages/@aws-cdk/aws-glue-alpha/test/integ.job.js.snapshot/integ.json
  packages/@aws-cdk/aws-glue-alpha/test/integ.job.js.snapshot/manifest.json
  packages/@aws-cdk/aws-glue-alpha/test/integ.job.js.snapshot/tree.json
  packages/@aws-cdk/aws-glue-alpha/test/integ.job.ts
  packages/@aws-cdk/aws-glue-alpha/test/job-executable.test.ts
  packages/@aws-cdk/aws-glue-alpha/test/job.test.ts
Labels: p2, pr/needs-review, beginning-contributor

#26140 docs(s3): fix docs for BucketProps
  packages/aws-cdk-lib/aws-s3/lib/bucket.ts
Labels: p2, repeat-contributor

#26170 chore(merge-back): 2.86.0
  CHANGELOG.v2.alpha.md
  CHANGELOG.v2.md
  version.v2.json
Labels: p2, pr/needs-review, pr/no-squash, auto-approve

#25663 feat(scheduler): ScheduleTargetInput
  packages/@aws-cdk/aws-scheduler-alpha/README.md
  packages/@aws-cdk/aws-scheduler-alpha/lib/index.ts
  packages/@aws-cdk/aws-scheduler-alpha/lib/input.ts
  packages/@aws-cdk/aws-scheduler-alpha/lib/private/index.ts
  packages/@aws-cdk/aws-scheduler-alpha/lib/private/schedule.ts
  packages/@aws-cdk/aws-scheduler-alpha/lib/private/targets.ts
  packages/@aws-cdk/aws-scheduler-alpha/lib/schedule.ts
  packages/@aws-cdk/aws-scheduler-alpha/rosetta/default.ts-fixture
  packages/@aws-cdk/aws-scheduler-alpha/test/input.test.ts
Labels: p2, pr/needs-review, pr-linter/exempt-integ-test, beginning-contributor

#26030 chore(ecs): remove unnecessary js and d.ts files for integration test
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs/test/ec2/integ.task-definition-container-ulimits.d.ts
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs/test/ec2/integ.task-definition-container-ulimits.js
Labels: p2, pr/needs-review, beginning-contributor, pr-linter/exemption-requested

#26006 fix(rds): monitoring role is not created by default when using readers and writers
  packages/aws-cdk-lib/aws-rds/lib/cluster.ts
  packages/aws-cdk-lib/aws-rds/test/cluster.test.ts
Labels: bug, p1, effort/small, pr-linter/exempt-integ-test, admired-contributor, pr-linter/exemption-requested

#25749 fix(ssm): cannot import a ssm parameter with a name containing unresolved token
  packages/@aws-cdk-testing/framework-integ/test/aws-ssm/test/integ.import-parameter.js.snapshot/Import-SSM-Parameter.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ssm/test/integ.import-parameter.js.snapshot/Import-SSM-Parameter.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ssm/test/integ.import-parameter.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-ssm/test/integ.import-parameter.js.snapshot/cdkintegimportssmparameterDefaultTestDeployAssert2A3D6843.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ssm/test/integ.import-parameter.js.snapshot/cdkintegimportssmparameterDefaultTestDeployAssert2A3D6843.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ssm/test/integ.import-parameter.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ssm/test/integ.import-parameter.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ssm/test/integ.import-parameter.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ssm/test/integ.import-parameter.ts
  packages/aws-cdk-lib/aws-ssm/lib/parameter.ts
  packages/aws-cdk-lib/aws-ssm/test/parameter.test.ts
  packages/aws-cdk-lib/core/lib/cfn-fn.ts
Labels: bug, p1, effort/small, pr/needs-review, admired-contributor

#26153 chore(lambda): Add missing ARNs for cloudwatch lambda insights
  packages/aws-cdk-lib/aws-lambda/lib/lambda-insights.ts
  packages/aws-cdk-lib/region-info/build-tools/fact-tables.ts
  packages/aws-cdk-lib/region-info/test/__snapshots__/region-info.test.js.snap
Labels: p2, feature-request, effort/small, pr/needs-review, beginning-contributor

#26059 feat(iot): add action to start Step Functions State Machine
  packages/@aws-cdk/aws-iot-actions-alpha/README.md
  packages/@aws-cdk/aws-iot-actions-alpha/lib/index.ts
  packages/@aws-cdk/aws-iot-actions-alpha/lib/step-functions-state-machine-action.ts
  packages/@aws-cdk/aws-iot-actions-alpha/package.json
  packages/@aws-cdk/aws-iot-actions-alpha/rosetta/default.ts-fixture
  packages/@aws-cdk/aws-iot-actions-alpha/test/step-functions/integ.step-functions-start-state-machine.js.snapshot/cdk.out
  packages/@aws-cdk/aws-iot-actions-alpha/test/step-functions/integ.step-functions-start-state-machine.js.snapshot/integ.json
  packages/@aws-cdk/aws-iot-actions-alpha/test/step-functions/integ.step-functions-start-state-machine.js.snapshot/manifest.json
  packages/@aws-cdk/aws-iot-actions-alpha/test/step-functions/integ.step-functions-start-state-machine.js.snapshot/statemachineintegtestDefaultTestDeployAssert1FAFBF55.assets.json
  packages/@aws-cdk/aws-iot-actions-alpha/test/step-functions/integ.step-functions-start-state-machine.js.snapshot/statemachineintegtestDefaultTestDeployAssert1FAFBF55.template.json
  packages/@aws-cdk/aws-iot-actions-alpha/test/step-functions/integ.step-functions-start-state-machine.js.snapshot/test-step-functions-start-state-machine-action-stack.assets.json
  packages/@aws-cdk/aws-iot-actions-alpha/test/step-functions/integ.step-functions-start-state-machine.js.snapshot/test-step-functions-start-state-machine-action-stack.template.json
  packages/@aws-cdk/aws-iot-actions-alpha/test/step-functions/integ.step-functions-start-state-machine.js.snapshot/tree.json
  packages/@aws-cdk/aws-iot-actions-alpha/test/step-functions/integ.step-functions-start-state-machine.ts
  packages/@aws-cdk/aws-iot-actions-alpha/test/step-functions/step-functions-start-state-machine.test.ts
Labels: p2, feature-request, effort/small, pr/needs-review, star-contributor

#25895 feat: update alpha modules to sdk v3
  packages/@aws-cdk/aws-amplify-alpha/lib/asset-deployment-handler/handler.ts
  packages/@aws-cdk/aws-amplify-alpha/lib/asset-deployment-handler/index.ts
  packages/@aws-cdk/aws-amplify-alpha/lib/branch.ts
  packages/@aws-cdk/aws-amplify-alpha/package.json
  packages/@aws-cdk/aws-amplify-alpha/test/asset-deployment-handler/index.test.ts
  packages/@aws-cdk/aws-redshift-alpha/lib/cluster-parameter-change-reboot-handler/index.ts
  packages/@aws-cdk/aws-redshift-alpha/lib/cluster.ts
  packages/@aws-cdk/aws-redshift-alpha/lib/private/database-query-provider/redshift-data.ts
  packages/@aws-cdk/aws-redshift-alpha/lib/private/database-query-provider/user.ts
  packages/@aws-cdk/aws-redshift-alpha/package.json
  packages/@aws-cdk/aws-redshift-alpha/test/cluster.test.ts
  packages/@aws-cdk/aws-redshift-alpha/test/database-query-provider/privileges.test.ts
  packages/@aws-cdk/aws-redshift-alpha/test/database-query-provider/table.test.ts
  packages/@aws-cdk/aws-redshift-alpha/test/database-query-provider/user.test.ts
  packages/@aws-cdk/aws-redshift-alpha/test/integ.cluster-reboot.js.snapshot/asset.ae370e1010629b78f494346f49ceef3ab2875718f20e6c808114e6aa770c7bf3.bundle/index.js
  packages/@aws-cdk/aws-redshift-alpha/test/integ.cluster-reboot.js.snapshot/asset.b5afd122c605f8f3ce8ca9656e47d6db7acb702ecd2bc9823eadde03a2ceb9e8.bundle/index.js
  packages/@aws-cdk/aws-redshift-alpha/test/integ.cluster-reboot.js.snapshot/aws-cdk-redshift-cluster-create.assets.json
  packages/@aws-cdk/aws-redshift-alpha/test/integ.cluster-reboot.js.snapshot/aws-cdk-redshift-cluster-create.template.json
  packages/@aws-cdk/aws-redshift-alpha/test/integ.cluster-reboot.js.snapshot/aws-cdk-redshift-cluster-update.assets.json
  packages/@aws-cdk/aws-redshift-alpha/test/integ.cluster-reboot.js.snapshot/aws-cdk-redshift-cluster-update.template.json
  packages/@aws-cdk/aws-redshift-alpha/test/integ.cluster-reboot.js.snapshot/awscdkredshiftreboottestDefaultTestDeployAssert1AE11B34.assets.json
  packages/@aws-cdk/aws-redshift-alpha/test/integ.cluster-reboot.js.snapshot/awscdkredshiftreboottestDefaultTestDeployAssert1AE11B34.template.json
  packages/@aws-cdk/aws-redshift-alpha/test/integ.cluster-reboot.js.snapshot/integ.json
  packages/@aws-cdk/aws-redshift-alpha/test/integ.cluster-reboot.js.snapshot/manifest.json
  packages/@aws-cdk/aws-redshift-alpha/test/integ.cluster-reboot.js.snapshot/tree.json
  packages/@aws-cdk/aws-redshift-alpha/test/integ.cluster-reboot.ts
  packages/@aws-cdk/aws-sagemaker-alpha/package.json
  packages/@aws-cdk/cli-lib-alpha/test/cli.test.ts
  packages/@aws-cdk/integ-tests-alpha/lib/assertions/providers/lambda-handler/base.ts
  packages/@aws-cdk/integ-tests-alpha/lib/assertions/providers/lambda-handler/sdk.ts
  packages/@aws-cdk/integ-tests-alpha/lib/assertions/providers/provider.ts
  packages/@aws-cdk/integ-tests-alpha/package.json
  packages/@aws-cdk/integ-tests-alpha/test/assertions/providers/lambda-handler/base.test.ts
  packages/@aws-cdk/integ-tests-alpha/test/assertions/providers/lambda-handler/sdk.test.ts
  packages/aws-cdk-lib/custom-resources/lib/aws-custom-resource/runtime/aws-sdk-v3-handler/index.ts
  packages/aws-cdk-lib/package.json
  yarn.lock
Labels: p2, contribution/core, pr-linter/exempt-readme
