Repository aws/aws-cdk, pull requests merged in 2023-11, with the labels that each got.

#27784 chore: update Contributors File
  CONTRIBUTORS.md
Labels: p2, auto-approve

#27001 feat(cloud9-alpha): add support for `federated-user` and `assumed-role` for Cloud9 environment ownership
  packages/@aws-cdk/aws-cloud9-alpha/README.md
  packages/@aws-cdk/aws-cloud9-alpha/lib/environment.ts
  packages/@aws-cdk/aws-cloud9-alpha/test/cloud9.environment.test.ts
  packages/@aws-cdk/aws-cloud9-alpha/test/integ.owner.js.snapshot/OwnerIntegDefaultTestDeployAssertEE359F09.assets.json
  packages/@aws-cdk/aws-cloud9-alpha/test/integ.owner.js.snapshot/OwnerIntegDefaultTestDeployAssertEE359F09.template.json
  packages/@aws-cdk/aws-cloud9-alpha/test/integ.owner.js.snapshot/cdk.out
  packages/@aws-cdk/aws-cloud9-alpha/test/integ.owner.js.snapshot/cloud9-owner-integ.assets.json
  packages/@aws-cdk/aws-cloud9-alpha/test/integ.owner.js.snapshot/cloud9-owner-integ.template.json
  packages/@aws-cdk/aws-cloud9-alpha/test/integ.owner.js.snapshot/integ.json
  packages/@aws-cdk/aws-cloud9-alpha/test/integ.owner.js.snapshot/manifest.json
  packages/@aws-cdk/aws-cloud9-alpha/test/integ.owner.js.snapshot/tree.json
  packages/@aws-cdk/aws-cloud9-alpha/test/integ.owner.ts
Labels: p2, beginning-contributor, pr/needs-review

#27692 fix(cli): fix stack monitoring when the stack events do not have phsical resource id set
  packages/aws-cdk/lib/api/util/cloudformation/stack-activity-monitor.ts
  packages/aws-cdk/test/util/stack-monitor.test.ts
Labels: p2, pr-linter/exempt-integ-test, repeat-contributor, pr-linter/cli-integ-tested

#27734 feat(dynamodb): add seed capacity property to support changing table billing mode
  packages/@aws-cdk-testing/framework-integ/test/aws-dynamodb/test/integ.table-v2-global.js.snapshot/aws-cdk-global-table.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-dynamodb/test/integ.table-v2-global.js.snapshot/aws-cdk-global-table.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-dynamodb/test/integ.table-v2-global.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-dynamodb/test/integ.table-v2-global.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-dynamodb/test/integ.table-v2-global.ts
  packages/aws-cdk-lib/aws-dynamodb/README.md
  packages/aws-cdk-lib/aws-dynamodb/lib/capacity.ts
  packages/aws-cdk-lib/aws-dynamodb/test/capacity.test.ts
Labels: p2, feature-request, contribution/core

#27748 feat(rds): support aurora MySQL 3.05.0
  packages/aws-cdk-lib/aws-rds/lib/cluster-engine.ts
Labels: p2, pr-linter/exempt-readme, pr-linter/exempt-test, pr-linter/exempt-integ-test, beginning-contributor

#27759 test(core): unit tests for cfn utils provider handler
  packages/@aws-cdk-testing/framework-integ/test/aws-iam/test/integ.condition-with-ref.js.snapshot/test-condition-with-ref.template.json
  packages/aws-cdk-lib/core/lib/private/cfn-utils-provider/index.ts
  packages/aws-cdk-lib/core/test/private/cfn-utils-provider-handler.test.ts
Labels: p2, feature-request, distinguished-contributor

#27777 test(pipelines): create unit tests for approve lambda handler
  packages/aws-cdk-lib/pipelines/test/private/approve-lambda-handler.test.ts
Labels: p2, feature-request, distinguished-contributor

#27765 fix(opensearchservice): IM4GN instances don't support EBS
  packages/aws-cdk-lib/aws-opensearchservice/lib/domain.ts
  packages/aws-cdk-lib/aws-opensearchservice/test/domain.test.ts
Labels: bug, p2, effort/small, pr-linter/exempt-integ-test, admired-contributor

#27795 feat(ec2): support for m6in, m6idn, r6in and r6idn instance types in aws-ec2
  packages/aws-cdk-lib/aws-ec2/lib/instance-types.ts
Labels: p2, pr-linter/exempt-readme, pr-linter/exempt-test, pr-linter/exempt-integ-test, admired-contributor

#27705 feat(ec2): Add support for P5 instances EC2
  packages/aws-cdk-lib/aws-ec2/lib/instance-types.ts
  packages/aws-cdk-lib/aws-ec2/test/instance.test.ts
Labels: p2, feature-request, pr-linter/exempt-readme, pr-linter/exempt-integ-test, beginning-contributor

#27811 chore(merge-back): 2.104.0
  CHANGELOG.v2.alpha.md
  CHANGELOG.v2.md
  version.v2.json
Labels: p2, pr/needs-community-review, pr/no-squash, auto-approve

#27681 chore(spec2cdk): generate ICfnResource interface
  packages/awslint/lib/rules/core-types.ts
  tools/@aws-cdk/spec2cdk/lib/cdk/ast.ts
  tools/@aws-cdk/spec2cdk/lib/cdk/resource-class.ts
  tools/@aws-cdk/spec2cdk/lib/cdk/resource-decider.ts
  tools/@aws-cdk/spec2cdk/lib/naming/conventions.ts
  tools/@aws-cdk/spec2cdk/test/__snapshots__/resources.test.ts.snap
  tools/@aws-cdk/spec2cdk/test/resources.test.ts
Labels: p2, contribution/core

#27788 test(redshift): unit tests for cluster parameter change reboot handler
  packages/@aws-cdk/aws-redshift-alpha/test/cluster-parameter-change-reboot-handler.test.ts
Labels: p2, feature-request, distinguished-contributor

#27778 fix(ec2): two undefined tunnelInsideCidr should not throw error
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.vpn-two-tunnels.js.snapshot/aws-cdk-ec2-vpn-two-tunnels.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.vpn-two-tunnels.js.snapshot/aws-cdk-ec2-vpn-two-tunnels.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.vpn-two-tunnels.js.snapshot/awscdkec2vpntwotunnelstestDefaultTestDeployAssert354DB13C.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.vpn-two-tunnels.js.snapshot/awscdkec2vpntwotunnelstestDefaultTestDeployAssert354DB13C.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.vpn-two-tunnels.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.vpn-two-tunnels.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.vpn-two-tunnels.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.vpn-two-tunnels.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.vpn-two-tunnels.ts
  packages/aws-cdk-lib/aws-ec2/README.md
  packages/aws-cdk-lib/aws-ec2/lib/vpn.ts
  packages/aws-cdk-lib/aws-ec2/test/vpn.test.ts
Labels: bug, p2, admired-contributor

#27792 feat(scheduler-targets): CodeBuild scheduler target
  packages/@aws-cdk/aws-scheduler-targets-alpha/README.md
  packages/@aws-cdk/aws-scheduler-targets-alpha/lib/codebuild-start-build.ts
  packages/@aws-cdk/aws-scheduler-targets-alpha/lib/index.ts
  packages/@aws-cdk/aws-scheduler-targets-alpha/package.json
  packages/@aws-cdk/aws-scheduler-targets-alpha/test/codebuild-start-build.test.ts
  packages/@aws-cdk/aws-scheduler-targets-alpha/test/integ.codebuild-start-build.js.snapshot/asset.a5feac1d1e65b04919886f5961fd2ba1352489d558439d9d6592877e92fc2814.bundle/index.js
  packages/@aws-cdk/aws-scheduler-targets-alpha/test/integ.codebuild-start-build.js.snapshot/aws-cdk-scheduler-targets-codebuild-start-build.assets.json
  packages/@aws-cdk/aws-scheduler-targets-alpha/test/integ.codebuild-start-build.js.snapshot/aws-cdk-scheduler-targets-codebuild-start-build.template.json
  packages/@aws-cdk/aws-scheduler-targets-alpha/test/integ.codebuild-start-build.js.snapshot/cdk.out
  packages/@aws-cdk/aws-scheduler-targets-alpha/test/integ.codebuild-start-build.js.snapshot/integ.json
  packages/@aws-cdk/aws-scheduler-targets-alpha/test/integ.codebuild-start-build.js.snapshot/integrationtestcodebuildstartbuildDefaultTestDeployAssert416931F1.assets.json
  packages/@aws-cdk/aws-scheduler-targets-alpha/test/integ.codebuild-start-build.js.snapshot/integrationtestcodebuildstartbuildDefaultTestDeployAssert416931F1.template.json
  packages/@aws-cdk/aws-scheduler-targets-alpha/test/integ.codebuild-start-build.js.snapshot/manifest.json
  packages/@aws-cdk/aws-scheduler-targets-alpha/test/integ.codebuild-start-build.js.snapshot/tree.json
  packages/@aws-cdk/aws-scheduler-targets-alpha/test/integ.codebuild-start-build.ts
Labels: p2, feature-request, effort/medium, star-contributor

#27769 chore(ses): create unit tests for drop spam handler
  packages/aws-cdk-lib/aws-ses/test/drop-spam-handler/drop-spam-handler.test.ts
Labels: p2, feature-request, contribution/core

#27821 feat: update AWS Service Spec
  tools/@aws-cdk/spec2cdk/package.json
  yarn.lock
Labels: p2, dependencies, contribution/core, pr-linter/exempt-readme, pr-linter/exempt-test, auto-approve, pr-linter/exempt-integ-test

#27831 chore(appsync): Change reference of API source in comments to Definition
  packages/aws-cdk-lib/aws-appsync/lib/graphqlapi.ts
Labels: p2, repeat-contributor

#27686 test(eks): Dockerfile used in an integ test fails
  packages/@aws-cdk-testing/framework-integ/test/aws-eks/test/sdk-call-integ-test-docker-app/app/Dockerfile
  packages/@aws-cdk-testing/framework-integ/test/aws-eks/test/sdk-call-integ-test-docker-app/app/package-lock.json
Labels: p2, admired-contributor

#27809 chore(stepfunctions-tasks): add a doc and an integ test for spot instance fleets in EMR
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/emr/integ.emr-create-cluster-with-spot-instance-fleet.js.snapshot/EmrCreateClusterTestDefaultTestDeployAssert697DC891.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/emr/integ.emr-create-cluster-with-spot-instance-fleet.js.snapshot/EmrCreateClusterTestDefaultTestDeployAssert697DC891.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/emr/integ.emr-create-cluster-with-spot-instance-fleet.js.snapshot/aws-cdk-emr-create-cluster-with-spot-instance-fleet.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/emr/integ.emr-create-cluster-with-spot-instance-fleet.js.snapshot/aws-cdk-emr-create-cluster-with-spot-instance-fleet.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/emr/integ.emr-create-cluster-with-spot-instance-fleet.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/emr/integ.emr-create-cluster-with-spot-instance-fleet.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/emr/integ.emr-create-cluster-with-spot-instance-fleet.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/emr/integ.emr-create-cluster-with-spot-instance-fleet.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/emr/integ.emr-create-cluster-with-spot-instance-fleet.ts
  packages/aws-cdk-lib/aws-stepfunctions-tasks/lib/emr/emr-create-cluster.ts
Labels: p2, star-contributor

#27823 feat(ec2): support for m7a, r7a and c7a instance types in aws-ec2
  packages/aws-cdk-lib/aws-ec2/lib/instance-types.ts
Labels: p2, pr-linter/exempt-readme, pr-linter/exempt-test, pr-linter/exempt-integ-test, admired-contributor

#27851 feat: update AWS Service Spec
  tools/@aws-cdk/spec2cdk/package.json
  yarn.lock
Labels: p2, dependencies, contribution/core, pr-linter/exempt-readme, pr-linter/exempt-test, auto-approve, pr-linter/exempt-integ-test, pr/needs-maintainer-review

#27854 chore: include @aws-cdk/service-spec-importers in service spec update
  .github/workflows/spec-update.yml
Labels: p2, contribution/core, pr/needs-maintainer-review

#27813 feat(cloudformation-diff): use awscdk-service-spec as data source
  aws-cdk.code-workspace
  packages/@aws-cdk/cloudformation-diff/jest.config.js
  packages/@aws-cdk/cloudformation-diff/lib/diff/index.ts
  packages/@aws-cdk/cloudformation-diff/lib/diff/types.ts
  packages/@aws-cdk/cloudformation-diff/lib/diff/util.ts
  packages/@aws-cdk/cloudformation-diff/lib/format.ts
  packages/@aws-cdk/cloudformation-diff/lib/iam/iam-changes.ts
  packages/@aws-cdk/cloudformation-diff/lib/util.ts
  packages/@aws-cdk/cloudformation-diff/package.json
  packages/@aws-cdk/integ-runner/package.json
  packages/aws-cdk/.gitignore
  packages/aws-cdk/package.json
Labels: p2, contribution/core, pr-linter/exempt-readme, pr-linter/exempt-test, pr-linter/exempt-integ-test

#27604 feat(ec2): vpc flow logs supports kinesis data firehose
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.vpc-flow-logs-kinesis.js.snapshot/FlowLogsDefaultTestDeployAssert6AFD1854.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.vpc-flow-logs-kinesis.js.snapshot/FlowLogsDefaultTestDeployAssert6AFD1854.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.vpc-flow-logs-kinesis.js.snapshot/FlowLogsTestStack.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.vpc-flow-logs-kinesis.js.snapshot/FlowLogsTestStack.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.vpc-flow-logs-kinesis.js.snapshot/asset.1be0bac6581864b510bdbf0a114f1d3429244758da7657cc365f73d371fe70ed/__entrypoint__.js
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.vpc-flow-logs-kinesis.js.snapshot/asset.1be0bac6581864b510bdbf0a114f1d3429244758da7657cc365f73d371fe70ed/index.js
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.vpc-flow-logs-kinesis.js.snapshot/asset.2ec8ad9e91dcd6e7ad6a5c84ffc6c9c05c408aca3b26ceb2816d81043e6c4dc3/index.js
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.vpc-flow-logs-kinesis.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.vpc-flow-logs-kinesis.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.vpc-flow-logs-kinesis.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.vpc-flow-logs-kinesis.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.vpc-flow-logs-kinesis.ts
  packages/aws-cdk-lib/aws-ec2/README.md
  packages/aws-cdk-lib/aws-ec2/lib/vpc-flow-logs.ts
  packages/aws-cdk-lib/aws-ec2/test/vpc-flow-logs.test.ts
Labels: p1, feature-request, effort/small, valued-contributor, pr/needs-maintainer-review

#27862 chore(spec2cdk): ICfnResource extends IConstruct
  packages/awslint/lib/rules/construct.ts
  tools/@aws-cdk/spec2cdk/lib/cdk/resource-class.ts
  tools/@aws-cdk/spec2cdk/test/__snapshots__/resources.test.ts.snap
Labels: p2, contribution/core

#27856 feat(lambda): new lambda runtime provided.al2023
  packages/@aws-cdk/aws-lambda-go-alpha/package.json
  packages/@aws-cdk/aws-lambda-go-alpha/test/bundling.test.ts
  packages/@aws-cdk/aws-lambda-go-alpha/test/integ.function.provided.al2023.js.snapshot/asset.92cf51642c9fbfef03751059a700f012eb605f85114cafc66e2fb70e37b18c64/bootstrap
  packages/@aws-cdk/aws-lambda-go-alpha/test/integ.function.provided.al2023.js.snapshot/cdk-integ-lambda-golang-provided-al2023.assets.json
  packages/@aws-cdk/aws-lambda-go-alpha/test/integ.function.provided.al2023.js.snapshot/cdk-integ-lambda-golang-provided-al2023.template.json
  packages/@aws-cdk/aws-lambda-go-alpha/test/integ.function.provided.al2023.js.snapshot/cdk.out
  packages/@aws-cdk/aws-lambda-go-alpha/test/integ.function.provided.al2023.js.snapshot/integ.json
  packages/@aws-cdk/aws-lambda-go-alpha/test/integ.function.provided.al2023.js.snapshot/lambdagoruntimeDefaultTestDeployAssert366012A1.assets.json
  packages/@aws-cdk/aws-lambda-go-alpha/test/integ.function.provided.al2023.js.snapshot/lambdagoruntimeDefaultTestDeployAssert366012A1.template.json
  packages/@aws-cdk/aws-lambda-go-alpha/test/integ.function.provided.al2023.js.snapshot/manifest.json
  packages/@aws-cdk/aws-lambda-go-alpha/test/integ.function.provided.al2023.js.snapshot/tree.json
  packages/@aws-cdk/aws-lambda-go-alpha/test/integ.function.provided.al2023.ts
  packages/aws-cdk-lib/aws-lambda/lib/runtime.ts
Labels: p2, contribution/core, pr-linter/exempt-readme

#27790 chore(awslint): new rules for reference interfaces
  packages/aws-cdk-lib/awslint.json
  packages/awslint/lib/rules/api.ts
  packages/awslint/lib/rules/cfn-resource.ts
  packages/awslint/lib/rules/resource.ts
Labels: p2, contribution/core, pr/needs-cli-test-run

#27871 chore(aws-cdk-lib): remove superfluous script
  packages/aws-cdk-lib/package.json
  packages/aws-cdk-lib/scripts/verify-stripped-exp.ts
Labels: p2, contribution/core

#27877 chore: fix broken link in README.md
  README.md
Labels: p2, beginning-contributor

#27879 chore: fix second broken link in README
  README.md
Labels: p2, contribution/core, pr/needs-maintainer-review

#27872 docs(cognito): update selfSignUpEnabled documentation
  packages/aws-cdk-lib/aws-cognito/lib/user-pool.ts
Labels: p2, distinguished-contributor

#27870 fix: update commented template test
  packages/aws-cdk/lib/init-templates/app/go/%name%_test.template.go
Labels: bug, p2, pr-linter/exempt-integ-test, beginning-contributor

#27836 chore(rds): support for aurora mysql 2.07.9, 2.07.10, 2.11.4, 2.12.0 and deprecated versions
  packages/aws-cdk-lib/aws-rds/lib/cluster-engine.ts
Labels: p2, star-contributor

#27696 feat(appconfig): inline YAML support for hosted configuration
  packages/@aws-cdk/aws-appconfig-alpha/README.md
  packages/@aws-cdk/aws-appconfig-alpha/lib/configuration.ts
  packages/@aws-cdk/aws-appconfig-alpha/test/configuration.test.ts
  packages/@aws-cdk/aws-appconfig-alpha/test/integ.configuration.js.snapshot/appconfigconfigurationDefaultTestDeployAssert6752CD38.assets.json
  packages/@aws-cdk/aws-appconfig-alpha/test/integ.configuration.js.snapshot/aws-appconfig-configuration.assets.json
  packages/@aws-cdk/aws-appconfig-alpha/test/integ.configuration.js.snapshot/aws-appconfig-configuration.template.json
  packages/@aws-cdk/aws-appconfig-alpha/test/integ.configuration.js.snapshot/cdk.out
  packages/@aws-cdk/aws-appconfig-alpha/test/integ.configuration.js.snapshot/integ.json
  packages/@aws-cdk/aws-appconfig-alpha/test/integ.configuration.js.snapshot/manifest.json
  packages/@aws-cdk/aws-appconfig-alpha/test/integ.configuration.js.snapshot/tree.json
  packages/@aws-cdk/aws-appconfig-alpha/test/integ.configuration.ts
Labels: p2, repeat-contributor, pr-linter/exemption-requested

#27875 chore(release): 2.105.0
  CHANGELOG.v2.alpha.md
  CHANGELOG.v2.md
  packages/@aws-cdk/aws-lambda-go-alpha/package.json
  packages/@aws-cdk/aws-lambda-go-alpha/test/bundling.test.ts
  packages/@aws-cdk/aws-lambda-go-alpha/test/integ.function.provided.al2023.js.snapshot/asset.92cf51642c9fbfef03751059a700f012eb605f85114cafc66e2fb70e37b18c64/bootstrap
  packages/@aws-cdk/aws-lambda-go-alpha/test/integ.function.provided.al2023.js.snapshot/cdk-integ-lambda-golang-provided-al2023.assets.json
  packages/@aws-cdk/aws-lambda-go-alpha/test/integ.function.provided.al2023.js.snapshot/cdk-integ-lambda-golang-provided-al2023.template.json
  packages/@aws-cdk/aws-lambda-go-alpha/test/integ.function.provided.al2023.js.snapshot/cdk.out
  packages/@aws-cdk/aws-lambda-go-alpha/test/integ.function.provided.al2023.js.snapshot/integ.json
  packages/@aws-cdk/aws-lambda-go-alpha/test/integ.function.provided.al2023.js.snapshot/lambdagoruntimeDefaultTestDeployAssert366012A1.assets.json
  packages/@aws-cdk/aws-lambda-go-alpha/test/integ.function.provided.al2023.js.snapshot/lambdagoruntimeDefaultTestDeployAssert366012A1.template.json
  packages/@aws-cdk/aws-lambda-go-alpha/test/integ.function.provided.al2023.js.snapshot/manifest.json
  packages/@aws-cdk/aws-lambda-go-alpha/test/integ.function.provided.al2023.js.snapshot/tree.json
  packages/@aws-cdk/aws-lambda-go-alpha/test/integ.function.provided.al2023.ts
  packages/aws-cdk-lib/aws-lambda/lib/runtime.ts
  version.v2.json
Labels: p2, contribution/core, pr/no-squash, pr/needs-maintainer-review

#27887 chore(region-info): move the AWS_CDK_METADATA set to its own file
  packages/aws-cdk-lib/region-info/build-tools/fact-tables.ts
  packages/aws-cdk-lib/region-info/build-tools/generate-static-data.ts
  packages/aws-cdk-lib/region-info/build-tools/metadata.ts
Labels: p2, contribution/core

#27888 chore(merge-back): 2.105.0
  CHANGELOG.v2.alpha.md
  CHANGELOG.v2.md
  version.v2.json
Labels: p2, pr/needs-community-review, pr/no-squash, auto-approve

#27867 docs(ssm): doc for grantRead in IParameter is missing GetParameters
  packages/aws-cdk-lib/aws-ssm/lib/parameter.ts
Labels: p2, star-contributor

#27883 chore(redshift-alpha): migrate cluster parameter change reboot handler
  packages/@aws-cdk/aws-redshift-alpha/lib/cluster.ts
  packages/@aws-cdk/aws-redshift-alpha/package.json
  packages/@aws-cdk/aws-redshift-alpha/test/integ.cluster-reboot.js.snapshot/asset.211bd8c514e07e047addb5c06afe6f8e85ce4e0b19b64ad78b28e84fc09aafe7.bundle/index.js
  packages/@aws-cdk/aws-redshift-alpha/test/integ.cluster-reboot.js.snapshot/aws-cdk-redshift-cluster-create.assets.json
  packages/@aws-cdk/aws-redshift-alpha/test/integ.cluster-reboot.js.snapshot/aws-cdk-redshift-cluster-create.template.json
  packages/@aws-cdk/aws-redshift-alpha/test/integ.cluster-reboot.js.snapshot/aws-cdk-redshift-cluster-update.assets.json
  packages/@aws-cdk/aws-redshift-alpha/test/integ.cluster-reboot.js.snapshot/aws-cdk-redshift-cluster-update.template.json
  packages/@aws-cdk/aws-redshift-alpha/test/integ.cluster-reboot.js.snapshot/awscdkredshiftreboottestDefaultTestDeployAssert1AE11B34.assets.json
  packages/@aws-cdk/aws-redshift-alpha/test/integ.cluster-reboot.js.snapshot/awscdkredshiftreboottestDefaultTestDeployAssert1AE11B34.template.json
  packages/@aws-cdk/aws-redshift-alpha/test/integ.cluster-reboot.js.snapshot/manifest.json
  packages/@aws-cdk/aws-redshift-alpha/test/integ.cluster-reboot.js.snapshot/tree.json
  packages/@aws-cdk/custom-resource-handlers/lib/aws-redshift-alpha/cluster-parameter-change-reboot-handler/index.ts
  packages/@aws-cdk/custom-resource-handlers/package.json
  packages/@aws-cdk/custom-resource-handlers/test/aws-redshift-alpha/cluster-parameter-change-reboot-handler.test.ts
  yarn.lock
Labels: p2, contribution/core, pr/needs-maintainer-review, handler-migration

#27863 chore(ecs): migrate drain hook lambda source handler
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs/test/ec2/integ.spot-drain.js.snapshot/aws-ecs-integ-spot.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs/test/ec2/integ.spot-drain.js.snapshot/aws-ecs-integ-spot.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs/test/ec2/integ.spot-drain.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs/test/ec2/integ.spot-drain.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs/test/ec2/integ.spot-drain.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs/test/ec2/integ.spot-drain.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs/test/ec2/integ.spot-drain.ts
  packages/@aws-cdk/custom-resource-handlers/lib/aws-ecs/lambda-source/index.py
  packages/@aws-cdk/custom-resource-handlers/scripts/minify-and-bundle-sources.ts
  packages/aws-cdk-lib/aws-ecs/lib/drain-hook/instance-drain-hook.ts
  packages/aws-cdk-lib/scripts/airlift-custom-resource-handlers.sh
Labels: p2, contribution/core, handler-migration

#27819 chore(prlint): don't mark PRs as 'not ready' on community comment
  tools/@aws-cdk/prlint/lint.ts
  tools/@aws-cdk/prlint/test/lint.test.ts
Labels: p2, star-contributor, pr/needs-maintainer-review

#27893 fix(appconfig): turn on awslint and fix linter errors
  packages/@aws-cdk/aws-appconfig-alpha/README.md
  packages/@aws-cdk/aws-appconfig-alpha/awslint.json
  packages/@aws-cdk/aws-appconfig-alpha/lib/application.ts
  packages/@aws-cdk/aws-appconfig-alpha/lib/configuration.ts
  packages/@aws-cdk/aws-appconfig-alpha/lib/deployment-strategy.ts
  packages/@aws-cdk/aws-appconfig-alpha/lib/environment.ts
  packages/@aws-cdk/aws-appconfig-alpha/lib/extension.ts
Labels: p2, contribution/core, pr-linter/exempt-test, pr-linter/exempt-integ-test

#27857 feat(gamelift): support Build serverSdkVersion, updated OperatingSystem values
  packages/@aws-cdk/aws-gamelift-alpha/README.md
  packages/@aws-cdk/aws-gamelift-alpha/lib/build.ts
  packages/@aws-cdk/aws-gamelift-alpha/test/build.test.ts
  packages/@aws-cdk/aws-gamelift-alpha/test/integ.build.js.snapshot/aws-gamelift-build.template.json
  packages/@aws-cdk/aws-gamelift-alpha/test/integ.build.ts
Labels: p2, feature-request, effort/small, distinguished-contributor

#27892 chore(spec2cdk): fix cli not working for single services
  tools/@aws-cdk/spec2cdk/README.md
  tools/@aws-cdk/spec2cdk/lib/cli/args.ts
  tools/@aws-cdk/spec2cdk/lib/cli/cli.ts
  tools/@aws-cdk/spec2cdk/lib/cli/help.ts
  tools/@aws-cdk/spec2cdk/lib/cli/index.ts
  tools/@aws-cdk/spec2cdk/lib/generate.ts
  tools/@aws-cdk/spec2cdk/package.json
  tools/@aws-cdk/spec2cdk/test/cli.test.ts
  yarn.lock
Labels: p2, contribution/core, pr/needs-maintainer-review

#27737 feat(ec2): support for r7i instance type in aws-ec2
  packages/aws-cdk-lib/aws-ec2/lib/instance-types.ts
Labels: p2, pr/needs-community-review, pr-linter/exempt-readme, pr-linter/exempt-test, pr-linter/exempt-integ-test, beginning-contributor

#27849 chore(cdk): update ADOT Lambda Layer ARNs
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda/test/integ.lambda-adot.js.snapshot/Stack1.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda/test/integ.lambda-adot.js.snapshot/Stack1.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda/test/integ.lambda-adot.js.snapshot/Stack2.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda/test/integ.lambda-adot.js.snapshot/Stack2.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda/test/integ.lambda-adot.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda/test/integ.lambda-adot.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda/test/integ.lambda-adot.ts
  packages/aws-cdk-lib/aws-lambda/lib/adot-layers.ts
  packages/aws-cdk-lib/aws-lambda/test/adot.test.ts
  packages/aws-cdk-lib/aws-lambda/test/function.test.ts
  packages/aws-cdk-lib/region-info/build-tools/fact-tables.ts
Labels: p2, repeat-contributor

#27839 chore(ec2): deprecate duplicate InterfaceVpcEndpointAwsService
  packages/aws-cdk-lib/aws-ec2/lib/vpc-endpoint.ts
Labels: bug, p2, effort/small, distinguished-contributor

#27794 fix(s3): InventoryConfiguration[].Id exceeds maximum size allowed by the PutBucketInventoryConfiguration API
  packages/@aws-cdk-testing/framework-integ/test/aws-s3/test/integ.bucket.inventory.js.snapshot/aws-cdk-bucket-inventory.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-s3/test/integ.bucket.inventory.js.snapshot/aws-cdk-bucket-inventory.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-s3/test/integ.bucket.inventory.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-s3/test/integ.bucket.inventory.js.snapshot/cdkintegbucketinventoryDefaultTestDeployAssertDAAFB0C3.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-s3/test/integ.bucket.inventory.js.snapshot/cdkintegbucketinventoryDefaultTestDeployAssertDAAFB0C3.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-s3/test/integ.bucket.inventory.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-s3/test/integ.bucket.inventory.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-s3/test/integ.bucket.inventory.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-s3/test/integ.bucket.inventory.ts
  packages/aws-cdk-lib/aws-s3/lib/bucket.ts
  packages/aws-cdk-lib/aws-s3/test/bucket.test.ts
Labels: bug, p2, effort/small, valued-contributor

#27800 chore: update DSE assignees
  .github/workflows/issue-label-assign.yml
Labels: p2, contribution/core

#27901 chore: turn on awslint in alpha modules
  packages/@aws-cdk/aws-apprunner-alpha/awslint.json
  packages/@aws-cdk/aws-cloud9-alpha/awslint.json
  packages/@aws-cdk/aws-codestar-alpha/awslint.json
  packages/@aws-cdk/aws-cognito-identitypool-alpha/awslint.json
  packages/@aws-cdk/aws-gamelift-alpha/awslint.json
  packages/@aws-cdk/aws-glue-alpha/awslint.json
  packages/@aws-cdk/aws-iot-actions-alpha/awslint.json
  packages/@aws-cdk/aws-iot-alpha/awslint.json
  packages/@aws-cdk/aws-iotevents-actions-alpha/awslint.json
  packages/@aws-cdk/aws-iotevents-alpha/awslint.json
  packages/@aws-cdk/aws-ivs-alpha/awslint.json
  packages/@aws-cdk/aws-kinesisanalytics-flink-alpha/awslint.json
  packages/@aws-cdk/aws-kinesisfirehose-alpha/awslint.json
  packages/@aws-cdk/aws-kinesisfirehose-destinations-alpha/awslint.json
  packages/@aws-cdk/aws-lambda-go-alpha/awslint.json
  packages/@aws-cdk/aws-lambda-python-alpha/awslint.json
  packages/@aws-cdk/aws-location-alpha/awslint.json
  packages/@aws-cdk/aws-location-alpha/lib/place-index.ts
  packages/@aws-cdk/aws-msk-alpha/awslint.json
  packages/@aws-cdk/aws-neptune-alpha/awslint.json
  packages/@aws-cdk/aws-redshift-alpha/awslint.json
  packages/@aws-cdk/aws-route53resolver-alpha/awslint.json
  packages/@aws-cdk/aws-s3objectlambda-alpha/awslint.json
  packages/@aws-cdk/aws-sagemaker-alpha/awslint.json
  packages/@aws-cdk/aws-scheduler-alpha/awslint.json
  packages/@aws-cdk/aws-scheduler-targets-alpha/awslint.json
  packages/@aws-cdk/aws-servicecatalogappregistry-alpha/awslint.json
  packages/@aws-cdk/cli-lib-alpha/awslint.json
  packages/@aws-cdk/integ-tests-alpha/awslint.json
Labels: p2, contribution/core

#27764 chore(cdk): boostrap template uses deprecated AccessControl property
  packages/aws-cdk/lib/api/bootstrap/bootstrap-template.yaml
Labels: p2, pr-linter/exempt-test, pr-linter/exempt-integ-test, beginning-contributor, pr-linter/cli-integ-tested, pr/needs-maintainer-review

#27908 chore(rds): add missing rds engine versions
  packages/aws-cdk-lib/aws-rds/lib/instance-engine.ts
Labels: p2, beginning-contributor

#27922 chore(merge-back): 2.106.0
  CHANGELOG.v2.alpha.md
  CHANGELOG.v2.md
  version.v2.json
Labels: p2, pr/needs-community-review, pr/no-squash, auto-approve

#27924 fix(integ-runner): update workflow error message is inaccurate
  packages/@aws-cdk/integ-runner/README.md
  packages/@aws-cdk/integ-runner/lib/runner/integ-test-runner.ts
Labels: p2, contribution/core, pr-linter/exempt-readme, pr-linter/exempt-test, pr-linter/exempt-integ-test, pr/needs-maintainer-review

#27931 docs(eks): remove description about incorrect requirement for vpcSubnets
  packages/aws-cdk-lib/aws-eks/lib/cluster.ts
Labels: p2, pr/needs-community-review, admired-contributor

#27698 fix(ec2): `AmazonLinuxImage` construct generates incorrect SSM parameter name for AL2023 images
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.machine-image.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.machine-image.js.snapshot/integ-ec2-machine-image-test.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.machine-image.js.snapshot/integ-ec2-machine-image-test.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.machine-image.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.machine-image.js.snapshot/integtestDefaultTestDeployAssert24D5C536.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.machine-image.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.machine-image.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.machine-image.ts
  packages/aws-cdk-lib/aws-ec2/lib/machine-image/machine-image.ts
  packages/aws-cdk-lib/aws-ec2/test/machine-image.test.ts
Labels: bug, p1, admired-contributor

#27930 feat(eks): support for Kubernetes version 1.28
  packages/aws-cdk-lib/aws-eks/README.md
  packages/aws-cdk-lib/aws-eks/lib/cluster.ts
  packages/aws-cdk-lib/package.json
Labels: p2, feature-request, effort/small, contribution/core, pr-linter/exempt-test, pr-linter/exempt-integ-test

#27917 chore: add L1 example to lakeformation readme
  packages/aws-cdk-lib/aws-lakeformation/README.md
Labels: p2, contribution/core

#27830 chore(triggers): migrate triggers handler
  packages/@aws-cdk-testing/framework-integ/test/triggers/test/integ.triggers.js.snapshot/MyStack.assets.json
  packages/@aws-cdk-testing/framework-integ/test/triggers/test/integ.triggers.js.snapshot/MyStack.template.json
  packages/@aws-cdk-testing/framework-integ/test/triggers/test/integ.triggers.js.snapshot/TriggerTestDefaultTestDeployAssert61636546.assets.json
  packages/@aws-cdk-testing/framework-integ/test/triggers/test/integ.triggers.js.snapshot/TriggerTestDefaultTestDeployAssert61636546.template.json
  packages/@aws-cdk-testing/framework-integ/test/triggers/test/integ.triggers.js.snapshot/asset.0289625ce635f0512d37a96c063b537131526fb13471d401c897885e11cf1ac7/__entrypoint__.js
  packages/@aws-cdk-testing/framework-integ/test/triggers/test/integ.triggers.js.snapshot/asset.0289625ce635f0512d37a96c063b537131526fb13471d401c897885e11cf1ac7/index.js
  packages/@aws-cdk-testing/framework-integ/test/triggers/test/integ.triggers.js.snapshot/asset.211bd8c514e07e047addb5c06afe6f8e85ce4e0b19b64ad78b28e84fc09aafe7.bundle/index.js
  packages/@aws-cdk-testing/framework-integ/test/triggers/test/integ.triggers.js.snapshot/asset.c742deecee726a924dde348ee95639f764a851c3300d7668a4ca0d7e4a2ffeb4/index.js
  packages/@aws-cdk-testing/framework-integ/test/triggers/test/integ.triggers.js.snapshot/manifest.json
  packages/@aws-cdk/custom-resource-handlers/lib/triggers/lambda/index.ts
  packages/@aws-cdk/custom-resource-handlers/package.json
  packages/@aws-cdk/custom-resource-handlers/test/triggers/trigger-handler.test.ts
  packages/aws-cdk-lib/triggers/lib/lambda/.is_custom_resource
  packages/aws-cdk-lib/triggers/lib/trigger.ts
Labels: p2, contribution/core, handler-migration

#27915 chore(s3-notifications): migrate notifications resource handler
  packages/@aws-cdk-testing/framework-integ/test/aws-s3-notifications/test/lambda/integ.bucket-notifications.js.snapshot/cdk-integ-lambda-bucket-notifications.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-s3-notifications/test/lambda/integ.bucket-notifications.js.snapshot/cdk-integ-lambda-bucket-notifications.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-s3-notifications/test/lambda/integ.bucket-notifications.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-s3-notifications/test/lambda/integ.bucket-notifications.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-s3-notifications/test/lambda/integ.bucket-notifications.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-s3-notifications/test/lambda/integ.bucket-notifications.ts
  packages/@aws-cdk/custom-resource-handlers/lib/aws-s3/notifications-resource-handler/index.py
  packages/@aws-cdk/custom-resource-handlers/test/aws-s3/notifications-resource-handler/Dockerfile
  packages/@aws-cdk/custom-resource-handlers/test/aws-s3/notifications-resource-handler/test.sh
  packages/@aws-cdk/custom-resource-handlers/test/aws-s3/notifications-resource-handler/test_index.py
  packages/aws-cdk-lib/aws-s3/lib/notifications-resource/notifications-resource-handler.ts
Labels: p2, contribution/core, handler-migration

#27904 chore(core): migrate cfn-utils handler
  packages/@aws-cdk-testing/framework-integ/test/aws-iam/test/integ.condition-with-ref.js.snapshot/asset.1e14e895fcbdf65feb0a29e4aa74c6c92a6fb0e41f228bef7ab23627ed409cde/consts.js
  packages/@aws-cdk-testing/framework-integ/test/aws-iam/test/integ.condition-with-ref.js.snapshot/asset.1e14e895fcbdf65feb0a29e4aa74c6c92a6fb0e41f228bef7ab23627ed409cde/index.js
  packages/@aws-cdk-testing/framework-integ/test/aws-iam/test/integ.condition-with-ref.js.snapshot/asset.f58e5b0009fc349d5e78d41594373bd6723e705a3c961a42adfbefa36cbe1bcf/__entrypoint__.js
  packages/@aws-cdk-testing/framework-integ/test/aws-iam/test/integ.condition-with-ref.js.snapshot/asset.f58e5b0009fc349d5e78d41594373bd6723e705a3c961a42adfbefa36cbe1bcf/index.js
  packages/@aws-cdk-testing/framework-integ/test/aws-iam/test/integ.condition-with-ref.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-iam/test/integ.condition-with-ref.js.snapshot/iamtestconditionwithrefDefaultTestDeployAssert5E44A64B.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-iam/test/integ.condition-with-ref.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-iam/test/integ.condition-with-ref.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-iam/test/integ.condition-with-ref.js.snapshot/test-condition-with-ref.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-iam/test/integ.condition-with-ref.js.snapshot/test-condition-with-ref.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-iam/test/integ.condition-with-ref.js.snapshot/tree.json
  packages/@aws-cdk/custom-resource-handlers/lib/core/cfn-utils-provider/index.ts
  packages/@aws-cdk/custom-resource-handlers/test/core/cfn-utils-provider-handler.test.ts
  packages/aws-cdk-lib/core/lib/private/cfn-utils-provider.ts
  packages/aws-cdk-lib/core/lib/private/cfn-utils-provider/.is_custom_resource
  packages/aws-cdk-lib/core/lib/private/cfn-utils-provider/consts.ts
  packages/aws-cdk-lib/core/test/cfn-json.test.ts
Labels: p2, contribution/core, handler-migration

#27827 chore(ses): migrate drop spam handler
  packages/@aws-cdk-testing/framework-integ/test/aws-ses/test/integ.receipt.js.snapshot/asset.19044c50ec489a0413f51a8e60d6272e5746e9b5a0356ed15c12de97c3ca93ec/index.js
  packages/@aws-cdk-testing/framework-integ/test/aws-ses/test/integ.receipt.js.snapshot/asset.96d0b6be9a64ae309bf89a86f5515453f0fa1d07b4f6b37198051cc98e251f34/index.d.ts
  packages/@aws-cdk-testing/framework-integ/test/aws-ses/test/integ.receipt.js.snapshot/asset.96d0b6be9a64ae309bf89a86f5515453f0fa1d07b4f6b37198051cc98e251f34/index.js
  packages/@aws-cdk-testing/framework-integ/test/aws-ses/test/integ.receipt.js.snapshot/asset.96d0b6be9a64ae309bf89a86f5515453f0fa1d07b4f6b37198051cc98e251f34/index.ts
  packages/@aws-cdk-testing/framework-integ/test/aws-ses/test/integ.receipt.js.snapshot/aws-cdk-ses-receipt.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ses/test/integ.receipt.js.snapshot/aws-cdk-ses-receipt.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ses/test/integ.receipt.js.snapshot/cdksesreceiptintegDefaultTestDeployAssertA2776C75.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ses/test/integ.receipt.js.snapshot/cdksesreceiptintegDefaultTestDeployAssertA2776C75.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ses/test/integ.receipt.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ses/test/integ.receipt.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ses/test/integ.receipt.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ses/test/integ.receipt.ts
  packages/@aws-cdk/custom-resource-handlers/lib/aws-ses/drop-spam-handler/index.ts
  packages/@aws-cdk/custom-resource-handlers/test/aws-ses/drop-spam-handler.test.ts
  packages/aws-cdk-lib/aws-ses/lib/drop-spam-handler/.is_custom_resource
  packages/aws-cdk-lib/aws-ses/lib/receipt-rule.ts
Labels: p2, contribution/core, handler-migration

#27907 fix(events): imported event rule ignores environment from arn
  packages/aws-cdk-lib/aws-events/lib/rule.ts
  packages/aws-cdk-lib/aws-events/test/rule.test.ts
Labels: p2, pr-linter/exempt-integ-test, star-contributor, pr-linter/exemption-requested

#27906 fix(sqs): imported queue ignores environment from arn
  packages/aws-cdk-lib/aws-sqs/lib/queue.ts
  packages/aws-cdk-lib/aws-sqs/test/sqs.test.ts
Labels: p2, pr-linter/exempt-integ-test, star-contributor, pr-linter/exemption-requested

#27828 chore(pipelines): migrate approve lambda handler
  packages/@aws-cdk-testing/framework-integ/test/pipelines/test/integ.pipeline-security.js.snapshot/PipelineSecurityStack.assets.json
  packages/@aws-cdk-testing/framework-integ/test/pipelines/test/integ.pipeline-security.js.snapshot/PipelineSecurityStack.template.json
  packages/@aws-cdk-testing/framework-integ/test/pipelines/test/integ.pipeline-security.js.snapshot/asset.8aa652c34c594d3c7ff1fe10240de14208e0d856f77eb4d56bd01bd9fc1f1273/index.d.ts
  packages/@aws-cdk-testing/framework-integ/test/pipelines/test/integ.pipeline-security.js.snapshot/asset.8aa652c34c594d3c7ff1fe10240de14208e0d856f77eb4d56bd01bd9fc1f1273/index.js
  packages/@aws-cdk-testing/framework-integ/test/pipelines/test/integ.pipeline-security.js.snapshot/asset.8aa652c34c594d3c7ff1fe10240de14208e0d856f77eb4d56bd01bd9fc1f1273/index.ts
  packages/@aws-cdk-testing/framework-integ/test/pipelines/test/integ.pipeline-security.js.snapshot/asset.c2adac8ea3baf51ce56c33ef5da361ea693f7ed128ddbc9777c557e9e7c741a6/index.js
  packages/@aws-cdk-testing/framework-integ/test/pipelines/test/integ.pipeline-security.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/pipelines/test/integ.pipeline-security.js.snapshot/tree.json
  packages/@aws-cdk/custom-resource-handlers/lib/pipelines/approve-lambda/index.ts
  packages/@aws-cdk/custom-resource-handlers/package.json
  packages/@aws-cdk/custom-resource-handlers/test/pipelines/approve-lambda-handler.test.ts
  packages/aws-cdk-lib/pipelines/lib/private/application-security-check.ts
  packages/aws-cdk-lib/pipelines/lib/private/approve-lambda/.is_custom_resource
Labels: p2, contribution/core, handler-migration

#27939 revert: "chore(cdk): boostrap template uses deprecated AccessControl property"
  packages/aws-cdk/lib/api/bootstrap/bootstrap-template.yaml
Labels: p2, contribution/core

#27941 chore: bump bootstrap template to version 19
  packages/aws-cdk/lib/api/bootstrap/bootstrap-template.yaml
Labels: p2, contribution/core

#27942 chore(release): v2.106.1
  CHANGELOG.v2.alpha.md
  CHANGELOG.v2.md
  packages/aws-cdk/lib/api/bootstrap/bootstrap-template.yaml
  version.v2.json
Labels: p2, contribution/core, pr/no-squash, pr/needs-maintainer-review

#27945 chore(merge-back): 2.106.1
  CHANGELOG.v2.alpha.md
  CHANGELOG.v2.md
  version.v2.json
Labels: p2, pr/needs-community-review, pr/no-squash, auto-approve

#27805 chore(cloudfront): migrate edge function handler
  packages/@aws-cdk-testing/framework-integ/test/aws-cloudfront/test/integ.distribution-lambda-cross-region.js.snapshot/asset.cd19575860c0626abb20d8fd8434732eed25190474a6a59becad0eadd913b065/__entrypoint__.js
  packages/@aws-cdk-testing/framework-integ/test/aws-cloudfront/test/integ.distribution-lambda-cross-region.js.snapshot/asset.cd19575860c0626abb20d8fd8434732eed25190474a6a59becad0eadd913b065/index.js
  packages/@aws-cdk-testing/framework-integ/test/aws-cloudfront/test/integ.distribution-lambda-cross-region.js.snapshot/asset.e718f39096261b3e336dd6d896baabf1049bb1938cb1865de1b5e576cb57376a/__entrypoint__.js
  packages/@aws-cdk-testing/framework-integ/test/aws-cloudfront/test/integ.distribution-lambda-cross-region.js.snapshot/asset.e718f39096261b3e336dd6d896baabf1049bb1938cb1865de1b5e576cb57376a/index.js
  packages/@aws-cdk-testing/framework-integ/test/aws-cloudfront/test/integ.distribution-lambda-cross-region.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-cloudfront/test/integ.distribution-lambda-cross-region.js.snapshot/cdkintegdistributionlambdacrossregionDefaultTestDeployAssert47F14485.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-cloudfront/test/integ.distribution-lambda-cross-region.js.snapshot/cdkintegdistributionlambdacrossregionDefaultTestDeployAssert47F14485.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-cloudfront/test/integ.distribution-lambda-cross-region.js.snapshot/edge-lambda-stack-c8363f8375cbe20a55dbe2aafe5dcee3889b0631e6.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-cloudfront/test/integ.distribution-lambda-cross-region.js.snapshot/edge-lambda-stack-c8363f8375cbe20a55dbe2aafe5dcee3889b0631e6.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-cloudfront/test/integ.distribution-lambda-cross-region.js.snapshot/edge-lambda-stack-eu-west-1-2.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-cloudfront/test/integ.distribution-lambda-cross-region.js.snapshot/edge-lambda-stack-eu-west-1-2.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-cloudfront/test/integ.distribution-lambda-cross-region.js.snapshot/integ-distribution-lambda-cross-region.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-cloudfront/test/integ.distribution-lambda-cross-region.js.snapshot/integ-distribution-lambda-cross-region.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-cloudfront/test/integ.distribution-lambda-cross-region.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-cloudfront/test/integ.distribution-lambda-cross-region.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-cloudfront/test/integ.distribution-lambda-cross-region.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-cloudfront/test/integ.distribution-lambda-cross-region.ts
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-nodejs/test/integ.latest.js.snapshot/asset.8b74e8b5925e743296f47264a1d280e895424cbb5d2cc612a77a3a9e9def7741/index.js
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-nodejs/test/integ.latest.js.snapshot/asset.8b74e8b5925e743296f47264a1d280e895424cbb5d2cc612a77a3a9e9def7741/node_modules/.yarn-integrity
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-nodejs/test/integ.latest.js.snapshot/asset.8b74e8b5925e743296f47264a1d280e895424cbb5d2cc612a77a3a9e9def7741/node_modules/delay/index.d.ts
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-nodejs/test/integ.latest.js.snapshot/asset.8b74e8b5925e743296f47264a1d280e895424cbb5d2cc612a77a3a9e9def7741/node_modules/delay/index.js
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-nodejs/test/integ.latest.js.snapshot/asset.8b74e8b5925e743296f47264a1d280e895424cbb5d2cc612a77a3a9e9def7741/node_modules/delay/license
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-nodejs/test/integ.latest.js.snapshot/asset.8b74e8b5925e743296f47264a1d280e895424cbb5d2cc612a77a3a9e9def7741/node_modules/delay/package.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-nodejs/test/integ.latest.js.snapshot/asset.8b74e8b5925e743296f47264a1d280e895424cbb5d2cc612a77a3a9e9def7741/node_modules/delay/readme.md
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-nodejs/test/integ.latest.js.snapshot/asset.8b74e8b5925e743296f47264a1d280e895424cbb5d2cc612a77a3a9e9def7741/package.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-nodejs/test/integ.latest.js.snapshot/asset.8b74e8b5925e743296f47264a1d280e895424cbb5d2cc612a77a3a9e9def7741/yarn.lock
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-nodejs/test/integ.latest.js.snapshot/asset.e7a77a480d6ecc875e791cead1bff764ebb5df141c46219196902068f9d3f7d2.bundle/index.js
  packages/@aws-cdk/custom-resource-handlers/.gitignore
  packages/@aws-cdk/custom-resource-handlers/lib/aws-cloudfront/edge-function/index.js
  packages/@aws-cdk/custom-resource-handlers/test/aws-cloudfront/edge-function.test.ts
  packages/aws-cdk-lib/aws-cloudfront/lib/experimental/edge-function.ts
  packages/aws-cdk-lib/aws-cloudfront/test/experimental/edge-function.test.ts
Labels: p2, contribution/core, handler-migration

#27958 feat: update AWS Service Spec
  packages/@aws-cdk/cloudformation-diff/package.json
  packages/aws-cdk-lib/package.json
  tools/@aws-cdk/spec2cdk/package.json
  yarn.lock
Labels: p2, dependencies, contribution/core, pr-linter/exempt-readme, pr-linter/exempt-test, auto-approve, pr-linter/exempt-integ-test

#27781 chore(spec2cdk): Resource class implements ICfnResource
  tools/@aws-cdk/spec2cdk/lib/cdk/resource-class.ts
  tools/@aws-cdk/spec2cdk/lib/cdk/resource-decider.ts
  tools/@aws-cdk/spec2cdk/test/__snapshots__/resources.test.ts.snap
  tools/@aws-cdk/spec2cdk/test/resources.test.ts
Labels: p2, contribution/core

#27897 feat(lambda): node20 runtime
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda/test/integ.runtime.inlinecode.js.snapshot/aws-cdk-lambda-runtime-inlinecode.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda/test/integ.runtime.inlinecode.js.snapshot/aws-cdk-lambda-runtime-inlinecode.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda/test/integ.runtime.inlinecode.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda/test/integ.runtime.inlinecode.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda/test/integ.runtime.inlinecode.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda/test/integ.runtime.inlinecode.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda/test/integ.runtime.inlinecode.ts
  packages/aws-cdk-lib/aws-lambda/lib/runtime.ts
Labels: p2, contribution/core, pr-linter/exempt-readme, pr-linter/exempt-test

#27965 chore(release): 2.107.0
  CHANGELOG.v2.alpha.md
  CHANGELOG.v2.md
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda/test/integ.runtime.inlinecode.js.snapshot/aws-cdk-lambda-runtime-inlinecode.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda/test/integ.runtime.inlinecode.js.snapshot/aws-cdk-lambda-runtime-inlinecode.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda/test/integ.runtime.inlinecode.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda/test/integ.runtime.inlinecode.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda/test/integ.runtime.inlinecode.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda/test/integ.runtime.inlinecode.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda/test/integ.runtime.inlinecode.ts
  packages/aws-cdk-lib/aws-lambda/lib/runtime.ts
  version.v2.json
Labels: p2, contribution/core, pr/no-squash

#27967 feat(lambda): add python 3.12 runtime
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda/test/integ.runtime.fromasset.js.snapshot/asset.211bd8c514e07e047addb5c06afe6f8e85ce4e0b19b64ad78b28e84fc09aafe7.bundle/index.js
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda/test/integ.runtime.inlinecode.js.snapshot/aws-cdk-lambda-runtime-inlinecode.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda/test/integ.runtime.inlinecode.js.snapshot/aws-cdk-lambda-runtime-inlinecode.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda/test/integ.runtime.inlinecode.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda/test/integ.runtime.inlinecode.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda/test/integ.runtime.inlinecode.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda/test/integ.runtime.inlinecode.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda/test/integ.runtime.inlinecode.ts
  packages/aws-cdk-lib/aws-lambda/lib/runtime.ts
Labels: p2, contribution/core, pr-linter/exempt-readme, pr/needs-maintainer-review

#27972 chore(release): 2.108.0
  CHANGELOG.v2.alpha.md
  CHANGELOG.v2.md
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda/test/integ.runtime.fromasset.js.snapshot/asset.211bd8c514e07e047addb5c06afe6f8e85ce4e0b19b64ad78b28e84fc09aafe7.bundle/index.js
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda/test/integ.runtime.inlinecode.js.snapshot/aws-cdk-lambda-runtime-inlinecode.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda/test/integ.runtime.inlinecode.js.snapshot/aws-cdk-lambda-runtime-inlinecode.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda/test/integ.runtime.inlinecode.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda/test/integ.runtime.inlinecode.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda/test/integ.runtime.inlinecode.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda/test/integ.runtime.inlinecode.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda/test/integ.runtime.inlinecode.ts
  packages/aws-cdk-lib/aws-lambda/lib/runtime.ts
  version.v2.json
Labels: p2, contribution/core, pr/no-squash

#27975 chore(merge-back): 2.108.0
  CHANGELOG.v2.alpha.md
  CHANGELOG.v2.md
  version.v2.json
Labels: p2, pr/needs-community-review, pr/no-squash, auto-approve

#27977 docs(rds): change default value for deleteAutomatedBackups from false to true
  packages/aws-cdk-lib/aws-rds/lib/instance.ts
Labels: p2, effort/small, star-contributor, pr/needs-maintainer-review

#27948 fix(elasticloadbalancingv2): access logging fails on imported bucket
  packages/@aws-cdk-testing/framework-integ/test/aws-elasticloadbalancingv2/test/integ.alb.log.imported-bucket.js.snapshot/aws-cdk-alb-log-imported-bucket-integ.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-elasticloadbalancingv2/test/integ.alb.log.imported-bucket.js.snapshot/aws-cdk-alb-log-imported-bucket-integ.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-elasticloadbalancingv2/test/integ.alb.log.imported-bucket.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-elasticloadbalancingv2/test/integ.alb.log.imported-bucket.js.snapshot/cdkintegalblogimportedbucketDefaultTestDeployAssert163162C1.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-elasticloadbalancingv2/test/integ.alb.log.imported-bucket.js.snapshot/cdkintegalblogimportedbucketDefaultTestDeployAssert163162C1.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-elasticloadbalancingv2/test/integ.alb.log.imported-bucket.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-elasticloadbalancingv2/test/integ.alb.log.imported-bucket.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-elasticloadbalancingv2/test/integ.alb.log.imported-bucket.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-elasticloadbalancingv2/test/integ.alb.log.imported-bucket.ts
  packages/aws-cdk-lib/aws-elasticloadbalancingv2/lib/shared/base-load-balancer.ts
  packages/aws-cdk-lib/aws-elasticloadbalancingv2/test/alb/load-balancer.test.ts
  packages/aws-cdk-lib/aws-elasticloadbalancingv2/test/nlb/load-balancer.test.ts
Labels: bug, p1, effort/medium, distinguished-contributor

#27992 chore(release): 2.108.1
  CHANGELOG.v2.alpha.md
  CHANGELOG.v2.md
  packages/@aws-cdk-testing/framework-integ/test/aws-elasticloadbalancingv2/test/integ.alb.log.imported-bucket.js.snapshot/aws-cdk-alb-log-imported-bucket-integ.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-elasticloadbalancingv2/test/integ.alb.log.imported-bucket.js.snapshot/aws-cdk-alb-log-imported-bucket-integ.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-elasticloadbalancingv2/test/integ.alb.log.imported-bucket.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-elasticloadbalancingv2/test/integ.alb.log.imported-bucket.js.snapshot/cdkintegalblogimportedbucketDefaultTestDeployAssert163162C1.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-elasticloadbalancingv2/test/integ.alb.log.imported-bucket.js.snapshot/cdkintegalblogimportedbucketDefaultTestDeployAssert163162C1.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-elasticloadbalancingv2/test/integ.alb.log.imported-bucket.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-elasticloadbalancingv2/test/integ.alb.log.imported-bucket.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-elasticloadbalancingv2/test/integ.alb.log.imported-bucket.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-elasticloadbalancingv2/test/integ.alb.log.imported-bucket.ts
  packages/aws-cdk-lib/aws-elasticloadbalancingv2/lib/shared/base-load-balancer.ts
  packages/aws-cdk-lib/aws-elasticloadbalancingv2/test/alb/load-balancer.test.ts
  packages/aws-cdk-lib/aws-elasticloadbalancingv2/test/nlb/load-balancer.test.ts
  version.v2.json
Labels: p2, contribution/core, pr/no-squash

#27990 docs(s3): clarify objectSizeGreaterThan attribute for lifecycle rules
  packages/aws-cdk-lib/aws-s3/lib/rule.ts
Labels: p2, pr/needs-community-review, admired-contributor

#27959 feat(apigateway): support firehose access log destination
  packages/@aws-cdk-testing/framework-integ/test/aws-apigateway/test/integ.restapi.access-log-firehose.js.snapshot/apigatewayaccesslogsfirehoseDefaultTestDeployAssert6376A91B.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-apigateway/test/integ.restapi.access-log-firehose.js.snapshot/apigatewayaccesslogsfirehoseDefaultTestDeployAssert6376A91B.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-apigateway/test/integ.restapi.access-log-firehose.js.snapshot/asset.2ec8ad9e91dcd6e7ad6a5c84ffc6c9c05c408aca3b26ceb2816d81043e6c4dc3/index.js
  packages/@aws-cdk-testing/framework-integ/test/aws-apigateway/test/integ.restapi.access-log-firehose.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-apigateway/test/integ.restapi.access-log-firehose.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-apigateway/test/integ.restapi.access-log-firehose.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-apigateway/test/integ.restapi.access-log-firehose.js.snapshot/test-apigateway-access-logs-firehose.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-apigateway/test/integ.restapi.access-log-firehose.js.snapshot/test-apigateway-access-logs-firehose.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-apigateway/test/integ.restapi.access-log-firehose.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-apigateway/test/integ.restapi.access-log-firehose.ts
  packages/aws-cdk-lib/aws-apigateway/README.md
  packages/aws-cdk-lib/aws-apigateway/lib/access-log.ts
  packages/aws-cdk-lib/aws-apigateway/lib/stage.ts
  packages/aws-cdk-lib/aws-apigateway/test/stage.test.ts
  packages/aws-cdk-lib/rosetta/aws_apigateway/default.ts-fixture
Labels: p2, feature-request, distinguished-contributor

#27995 chore(merge-back): 2.108.1
  CHANGELOG.v2.alpha.md
  CHANGELOG.v2.md
  version.v2.json
Labels: p2, pr/needs-community-review, pr/no-squash, auto-approve

#27981 chore: workflow to update the list of regions for `AWS::CDK::Metadata`
  .github/workflows/update-metadata-regions.yml
  scripts/update-metadata-regions.js
Labels: p2, contribution/core

#27984 docs(lambda-nodejs): fix default runtime docs
  packages/aws-cdk-lib/aws-lambda-nodejs/lib/function.ts
Labels: p2, beginning-contributor

#28007 chore: new prlint rule to protect the metadata.ts file against manual changes
  tools/@aws-cdk/prlint/lint.ts
  tools/@aws-cdk/prlint/test/lint.test.ts
Labels: p2, contribution/core

#27822 feat(lambda): add java 21 lambda runtime
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda/test/integ.runtime.fromasset.js.snapshot/IntegDefaultTestDeployAssert4E6713E1.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda/test/integ.runtime.fromasset.js.snapshot/IntegDefaultTestDeployAssert4E6713E1.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda/test/integ.runtime.fromasset.js.snapshot/asset.6e5ba7464138b7720c27df56bcc0a5463093492a1f311ed8a4f4c6baf84acaa8.bundle/index.js
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda/test/integ.runtime.fromasset.js.snapshot/asset.ae370e1010629b78f494346f49ceef3ab2875718f20e6c808114e6aa770c7bf3.bundle/index.js
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda/test/integ.runtime.fromasset.js.snapshot/aws-cdk-lambda-runtime-fromasset.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda/test/integ.runtime.fromasset.js.snapshot/aws-cdk-lambda-runtime-fromasset.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda/test/integ.runtime.fromasset.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda/test/integ.runtime.fromasset.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda/test/integ.runtime.fromasset.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda/test/integ.runtime.fromasset.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda/test/integ.runtime.fromasset.ts
  packages/aws-cdk-lib/aws-lambda/lib/runtime.ts
Labels: p2, contribution/core, pr-linter/exempt-readme

#28010 feat(lambda): Support S3 as onFailure destinations on MSK and SelfManagedKafka events
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-event-sources/test/integ.s3-onfailuire-destination.js.snapshot/LambdaEventSourceS3OnFailureDestinationIntegDefaultTestDeployAssert62366951.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-event-sources/test/integ.s3-onfailuire-destination.js.snapshot/LambdaEventSourceS3OnFailureDestinationIntegDefaultTestDeployAssert62366951.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-event-sources/test/integ.s3-onfailuire-destination.js.snapshot/asset.2ec8ad9e91dcd6e7ad6a5c84ffc6c9c05c408aca3b26ceb2816d81043e6c4dc3/index.js
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-event-sources/test/integ.s3-onfailuire-destination.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-event-sources/test/integ.s3-onfailuire-destination.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-event-sources/test/integ.s3-onfailuire-destination.js.snapshot/lambda-event-source-s3ofd.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-event-sources/test/integ.s3-onfailuire-destination.js.snapshot/lambda-event-source-s3ofd.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-event-sources/test/integ.s3-onfailuire-destination.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-event-sources/test/integ.s3-onfailuire-destination.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-event-sources/test/integ.s3-onfailuire-destination.ts
  packages/aws-cdk-lib/aws-lambda-event-sources/README.md
  packages/aws-cdk-lib/aws-lambda-event-sources/lib/index.ts
  packages/aws-cdk-lib/aws-lambda-event-sources/lib/kafka.ts
  packages/aws-cdk-lib/aws-lambda-event-sources/lib/s3-onfailuire-destination.ts
  packages/aws-cdk-lib/aws-lambda-event-sources/lib/stream.ts
  packages/aws-cdk-lib/aws-lambda-event-sources/test/dynamo.test.ts
  packages/aws-cdk-lib/aws-lambda-event-sources/test/kafka.test.ts
  packages/aws-cdk-lib/aws-lambda-event-sources/test/kinesis.test.ts
  packages/aws-cdk-lib/aws-lambda/lib/event-source-mapping.ts
Labels: p2, contribution/core

#28002 chore(rds): support for aurora mysql 3.04.1
  packages/aws-cdk-lib/aws-rds/lib/cluster-engine.ts
Labels: p2, beginning-contributor

#28011 feat: update AWS Service Spec
  packages/@aws-cdk/cloudformation-diff/package.json
  packages/@aws-cdk/integ-runner/package.json
  packages/aws-cdk-lib/aws-lambda/lib/function-hash.ts
  packages/aws-cdk-lib/package.json
  tools/@aws-cdk/spec2cdk/package.json
  yarn.lock
Labels: p2, dependencies, contribution/core, pr-linter/exempt-readme, pr-linter/exempt-test, auto-approve, pr-linter/exempt-integ-test

#28020 chore(merge-back): 2.109.0
  CHANGELOG.v2.alpha.md
  CHANGELOG.v2.md
  version.v2.json
Labels: p2, pr/needs-community-review, pr/no-squash, auto-approve

#28000 chore: add integ test for postgres with access to S3 bucket
  packages/@aws-cdk-testing/framework-integ/test/aws-rds/test/integ.cluster-s3.postgres.js.snapshot/aws-cdk-rds-s3-postgres-15-integ.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-rds/test/integ.cluster-s3.postgres.js.snapshot/aws-cdk-rds-s3-postgres-15-integ.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-rds/test/integ.cluster-s3.postgres.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-rds/test/integ.cluster-s3.postgres.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-rds/test/integ.cluster-s3.postgres.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-rds/test/integ.cluster-s3.postgres.js.snapshot/postgress3integtestDefaultTestDeployAssert71482B98.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-rds/test/integ.cluster-s3.postgres.js.snapshot/postgress3integtestDefaultTestDeployAssert71482B98.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-rds/test/integ.cluster-s3.postgres.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-rds/test/integ.cluster-s3.postgres.ts
Labels: p2, contribution/core

#28029 chore(rds): support RDS for SQL Server 16.00.4085.2.v1 as major version 2022
  packages/aws-cdk-lib/aws-rds/lib/instance-engine.ts
Labels: p2, star-contributor

#28003 docs: Update template README.md (JavaScript, TypeScript)
  packages/aws-cdk/lib/init-templates/app/javascript/README.md
  packages/aws-cdk/lib/init-templates/app/typescript/README.md
Labels: p2, beginning-contributor

#28033 docs(ec2): fix typo from Amazon Linux 2022 to Amazon Linux 2023
  packages/aws-cdk-lib/aws-ec2/lib/machine-image/amazon-linux-2023.ts
Labels: p2, star-contributor

#28034 feat: update AWS Service Spec
  packages/@aws-cdk/cloudformation-diff/package.json
  packages/@aws-cdk/integ-runner/package.json
  packages/aws-cdk-lib/package.json
  tools/@aws-cdk/spec2cdk/package.json
  yarn.lock
Labels: p2, dependencies, contribution/core, pr-linter/exempt-readme, pr-linter/exempt-test, auto-approve, pr-linter/exempt-integ-test

#28025 chore(migrate): improve warning
  packages/aws-cdk/lib/cdk-toolkit.ts
Labels: p2, contribution/core, pr-linter/cli-integ-tested

#28041 chore(release): 2.110.0
  CHANGELOG.v2.alpha.md
  CHANGELOG.v2.md
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda/test/integ.logging-config.js.snapshot/aws-cdk-lambda-logging-config.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda/test/integ.logging-config.js.snapshot/aws-cdk-lambda-logging-config.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda/test/integ.logging-config.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda/test/integ.logging-config.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda/test/integ.logging-config.js.snapshot/lambdaloggingconfigDefaultTestDeployAssert24012B25.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda/test/integ.logging-config.js.snapshot/lambdaloggingconfigDefaultTestDeployAssert24012B25.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda/test/integ.logging-config.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda/test/integ.logging-config.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda/test/integ.logging-config.ts
  packages/@aws-cdk-testing/framework-integ/test/aws-rds/test/integ.cluster-s3.postgres.js.snapshot/aws-cdk-rds-s3-postgres-15-integ.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-rds/test/integ.cluster-s3.postgres.js.snapshot/aws-cdk-rds-s3-postgres-15-integ.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-rds/test/integ.cluster-s3.postgres.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-rds/test/integ.cluster-s3.postgres.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-rds/test/integ.cluster-s3.postgres.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-rds/test/integ.cluster-s3.postgres.js.snapshot/postgress3integtestDefaultTestDeployAssert71482B98.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-rds/test/integ.cluster-s3.postgres.js.snapshot/postgress3integtestDefaultTestDeployAssert71482B98.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-rds/test/integ.cluster-s3.postgres.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-rds/test/integ.cluster-s3.postgres.ts
  packages/@aws-cdk/cloudformation-diff/package.json
  packages/@aws-cdk/integ-runner/package.json
  packages/aws-cdk-lib/aws-ec2/lib/machine-image/amazon-linux-2023.ts
  packages/aws-cdk-lib/aws-lambda/README.md
  packages/aws-cdk-lib/aws-lambda/lib/function.ts
  packages/aws-cdk-lib/aws-lambda/test/logging-config.test.ts
  packages/aws-cdk-lib/aws-rds/lib/instance-engine.ts
  packages/aws-cdk-lib/package.json
  packages/aws-cdk/lib/cdk-toolkit.ts
  packages/aws-cdk/lib/init-templates/app/javascript/README.md
  packages/aws-cdk/lib/init-templates/app/typescript/README.md
  tools/@aws-cdk/spec2cdk/package.json
  tools/@aws-cdk/spec2cdk/temporary-schemas/us-east-1/aws-lambda-function.json
  version.v2.json
  yarn.lock
Labels: p2, pr/no-squash, auto-approve

#28024 chore: Add author moelasmat to .mergify.yml
  .github/workflows/github-merit-badger.yml
  .mergify.yml
Labels: p2, repeat-contributor

#28043 chore(merge-back): 2.110.0
  CHANGELOG.v2.alpha.md
  CHANGELOG.v2.md
  version.v2.json
Labels: p2, pr/needs-community-review, pr/no-squash, auto-approve

#28027 fix(ec2): IPAM allocated subnets cannot split more than 256 times
  packages/aws-cdk-lib/aws-ec2/lib/ip-addresses.ts
  packages/aws-cdk-lib/aws-ec2/test/ip-addresses.test.ts
Labels: bug, p2, effort/medium, contribution/core, pr-linter/exempt-integ-test

#28009 chore: npm-check-updates && yarn upgrade
  package.json
  packages/@aws-cdk-testing/cli-integ/package.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-nodejs/test/integ.latest.js.snapshot/LambdaNodeJsLatestIntegDefaultTestDeployAssertD40B5C28.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-nodejs/test/integ.latest.js.snapshot/LambdaNodeJsLatestIntegDefaultTestDeployAssertD40B5C28.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-nodejs/test/integ.latest.js.snapshot/asset.4012e9468badb2b8e1a18d0513e222f2ad6246cf6ddc9f167fc9add9a48bb84e.bundle/index.js
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-nodejs/test/integ.latest.js.snapshot/asset.6e5ba7464138b7720c27df56bcc0a5463093492a1f311ed8a4f4c6baf84acaa8.bundle/index.js
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-nodejs/test/integ.latest.js.snapshot/asset.8b74e8b5925e743296f47264a1d280e895424cbb5d2cc612a77a3a9e9def7741/index.js
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-nodejs/test/integ.latest.js.snapshot/asset.c11c5e960d923b204379beb43f1461779af4a262e9a4b9c2e804ad1ec6f28568/index.js
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-nodejs/test/integ.latest.js.snapshot/asset.c11c5e960d923b204379beb43f1461779af4a262e9a4b9c2e804ad1ec6f28568/node_modules/.yarn-integrity
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-nodejs/test/integ.latest.js.snapshot/asset.c11c5e960d923b204379beb43f1461779af4a262e9a4b9c2e804ad1ec6f28568/node_modules/delay/index.d.ts
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-nodejs/test/integ.latest.js.snapshot/asset.c11c5e960d923b204379beb43f1461779af4a262e9a4b9c2e804ad1ec6f28568/node_modules/delay/index.js
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-nodejs/test/integ.latest.js.snapshot/asset.c11c5e960d923b204379beb43f1461779af4a262e9a4b9c2e804ad1ec6f28568/node_modules/delay/license
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-nodejs/test/integ.latest.js.snapshot/asset.c11c5e960d923b204379beb43f1461779af4a262e9a4b9c2e804ad1ec6f28568/node_modules/delay/package.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-nodejs/test/integ.latest.js.snapshot/asset.c11c5e960d923b204379beb43f1461779af4a262e9a4b9c2e804ad1ec6f28568/node_modules/delay/readme.md
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-nodejs/test/integ.latest.js.snapshot/asset.c11c5e960d923b204379beb43f1461779af4a262e9a4b9c2e804ad1ec6f28568/package.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-nodejs/test/integ.latest.js.snapshot/asset.c11c5e960d923b204379beb43f1461779af4a262e9a4b9c2e804ad1ec6f28568/yarn.lock
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-nodejs/test/integ.latest.js.snapshot/asset.f65ed1f2b93b6c6b88cb97ff443d650e4e09589d9c7e796f63abbf32ceb40866/index.js
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-nodejs/test/integ.latest.js.snapshot/asset.f65ed1f2b93b6c6b88cb97ff443d650e4e09589d9c7e796f63abbf32ceb40866/node_modules/.yarn-integrity
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-nodejs/test/integ.latest.js.snapshot/asset.f65ed1f2b93b6c6b88cb97ff443d650e4e09589d9c7e796f63abbf32ceb40866/node_modules/delay/index.d.ts
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-nodejs/test/integ.latest.js.snapshot/asset.f65ed1f2b93b6c6b88cb97ff443d650e4e09589d9c7e796f63abbf32ceb40866/node_modules/delay/index.js
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-nodejs/test/integ.latest.js.snapshot/asset.f65ed1f2b93b6c6b88cb97ff443d650e4e09589d9c7e796f63abbf32ceb40866/node_modules/delay/license
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-nodejs/test/integ.latest.js.snapshot/asset.f65ed1f2b93b6c6b88cb97ff443d650e4e09589d9c7e796f63abbf32ceb40866/node_modules/delay/package.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-nodejs/test/integ.latest.js.snapshot/asset.f65ed1f2b93b6c6b88cb97ff443d650e4e09589d9c7e796f63abbf32ceb40866/node_modules/delay/readme.md
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-nodejs/test/integ.latest.js.snapshot/asset.f65ed1f2b93b6c6b88cb97ff443d650e4e09589d9c7e796f63abbf32ceb40866/package.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-nodejs/test/integ.latest.js.snapshot/asset.f65ed1f2b93b6c6b88cb97ff443d650e4e09589d9c7e796f63abbf32ceb40866/yarn.lock
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-nodejs/test/integ.latest.js.snapshot/cdk-integ-lambda-nodejs-latest.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-nodejs/test/integ.latest.js.snapshot/cdk-integ-lambda-nodejs-latest.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-nodejs/test/integ.latest.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-nodejs/test/integ.latest.js.snapshot/tree.json
  packages/@aws-cdk/aws-amplify-alpha/package.json
  packages/@aws-cdk/aws-redshift-alpha/package.json
  packages/@aws-cdk/custom-resource-handlers/package.json
  packages/@aws-cdk/integ-tests-alpha/package.json
  packages/aws-cdk-lib/package.json
  packages/aws-cdk/THIRD_PARTY_LICENSES
  packages/aws-cdk/lib/init-templates/app/typescript/package.json
  packages/aws-cdk/lib/init-templates/lib/typescript/package.json
  packages/aws-cdk/lib/init-templates/sample-app/typescript/package.json
  packages/aws-cdk/package.json
  packages/awslint/package.json
  packages/cdk-assets/package.json
  tools/@aws-cdk/cdk-build-tools/package.json
  tools/@aws-cdk/eslint-plugin/package.json
  tools/@aws-cdk/node-bundle/package.json
  tools/@aws-cdk/pkglint/package.json
  tools/@aws-cdk/spec2cdk/package.json
  yarn.lock
Labels: p2, dependencies, contribution/core, auto-approve

#28048 chore(lambda): add AWS_DEFAULT_REGION to the list of reserved environment variables
  packages/aws-cdk-lib/aws-lambda/lib/function.ts
Labels: p2, beginning-contributor

#27860 fix(awslint): linting is slow
  packages/aws-cdk-lib/awslint.json
  packages/awslint/.eslintrc.js
  packages/awslint/bin/awslint.ts
  packages/awslint/lib/case.ts
  packages/awslint/lib/rules/api.ts
  packages/awslint/lib/rules/cfn-resource.ts
  packages/awslint/lib/rules/construct.ts
  packages/awslint/lib/rules/core-types.ts
  packages/awslint/lib/rules/imports.ts
  packages/awslint/lib/rules/resource.ts
  packages/awslint/lib/rules/util.ts
  packages/awslint/package.json
  yarn.lock
Labels: p2, contribution/core, pr-linter/exempt-test, pr-linter/exempt-integ-test

#27840 chore(stepfunctions-tasks): migrate eval-nodejs handler
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/integ.evaluate-expression.js.snapshot/asset.4a61519d8f4df8206cfaff4e519462aa81beab9213c3642a1353cd679c697638/index.js
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/integ.evaluate-expression.js.snapshot/asset.b8cec122f25692e8b194663d25a2ee5e0b65e55df966120791d6a3ddc08fc136/index.js
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/integ.evaluate-expression.js.snapshot/cdk-sfn-evaluate-expression-integ.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/integ.evaluate-expression.js.snapshot/cdk-sfn-evaluate-expression-integ.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/integ.evaluate-expression.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/integ.evaluate-expression.js.snapshot/tree.json
  packages/@aws-cdk/custom-resource-handlers/lib/aws-stepfunctions-tasks/eval-nodejs-handler/index.ts
  packages/@aws-cdk/custom-resource-handlers/test/aws-stepfunctions-tasks/eval-nodejs-handler.test.ts
  packages/aws-cdk-lib/aws-stepfunctions-tasks/lib/eval-nodejs-handler/.is_custom_resource
  packages/aws-cdk-lib/aws-stepfunctions-tasks/lib/evaluate-expression.ts
Labels: p2, contribution/core, handler-migration

#27814 chore(logs): migrate log retention handler
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda/test/integ.log-retention.js.snapshot/asset.06e556630dea1544fb71a394cf744fc6471c533769911adb44a84d795729c1f5/index.d.ts
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda/test/integ.log-retention.js.snapshot/asset.06e556630dea1544fb71a394cf744fc6471c533769911adb44a84d795729c1f5/index.js
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda/test/integ.log-retention.js.snapshot/asset.06e556630dea1544fb71a394cf744fc6471c533769911adb44a84d795729c1f5/index.ts
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda/test/integ.log-retention.js.snapshot/asset.e4afb15788ec44ed9ff3377e1d131ba2768d7b2e2931bc000d1f2005879b3035/index.js
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda/test/integ.log-retention.js.snapshot/aws-cdk-lambda-log-retention.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda/test/integ.log-retention.js.snapshot/aws-cdk-lambda-log-retention.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda/test/integ.log-retention.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda/test/integ.log-retention.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda/test/integ.log-retention.ts
  packages/@aws-cdk-testing/framework-integ/test/aws-logs/test/integ.log-retention.js.snapshot/asset.a8515c042d9c942705087943220417be929ac44f968d8fcef2681681b400c0c0/index.d.ts
  packages/@aws-cdk-testing/framework-integ/test/aws-logs/test/integ.log-retention.js.snapshot/asset.a8515c042d9c942705087943220417be929ac44f968d8fcef2681681b400c0c0/index.js
  packages/@aws-cdk-testing/framework-integ/test/aws-logs/test/integ.log-retention.js.snapshot/asset.a8515c042d9c942705087943220417be929ac44f968d8fcef2681681b400c0c0/index.ts
  packages/@aws-cdk-testing/framework-integ/test/aws-logs/test/integ.log-retention.js.snapshot/asset.e4afb15788ec44ed9ff3377e1d131ba2768d7b2e2931bc000d1f2005879b3035/index.js
  packages/@aws-cdk-testing/framework-integ/test/aws-logs/test/integ.log-retention.js.snapshot/aws-cdk-log-retention-integ.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-logs/test/integ.log-retention.js.snapshot/aws-cdk-log-retention-integ.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-logs/test/integ.log-retention.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-logs/test/integ.log-retention.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-logs/test/integ.log-retention.ts
  packages/@aws-cdk/custom-resource-handlers/lib/aws-logs/log-retention-handler/index.ts
  packages/@aws-cdk/custom-resource-handlers/package.json
  packages/@aws-cdk/custom-resource-handlers/test/aws-logs/log-retention-handler.test.ts
  packages/aws-cdk-lib/aws-logs/lib/log-retention-provider/.is_custom_resource
  packages/aws-cdk-lib/aws-logs/lib/log-retention.ts
  packages/aws-cdk-lib/aws-logs/test/log-retention.test.ts
Labels: p2, contribution/core, handler-migration

#28052 chore(iam): migrate oidc handler
  packages/@aws-cdk-testing/framework-integ/test/aws-iam/test/integ.oidc-provider.js.snapshot/asset.9c9c077e1db371e9d23da63db88926d5de460a4c66d88015384bf7156e8ef1b9/diff.js
  packages/@aws-cdk-testing/framework-integ/test/aws-iam/test/integ.oidc-provider.js.snapshot/asset.9c9c077e1db371e9d23da63db88926d5de460a4c66d88015384bf7156e8ef1b9/external.js
  packages/@aws-cdk-testing/framework-integ/test/aws-iam/test/integ.oidc-provider.js.snapshot/asset.9c9c077e1db371e9d23da63db88926d5de460a4c66d88015384bf7156e8ef1b9/index.js
  packages/@aws-cdk-testing/framework-integ/test/aws-iam/test/integ.oidc-provider.js.snapshot/asset.fe07e5b9d977c2146233a33c70d0afd1d984895920c4f555e3e2282e022361f6/__entrypoint__.js
  packages/@aws-cdk-testing/framework-integ/test/aws-iam/test/integ.oidc-provider.js.snapshot/asset.fe07e5b9d977c2146233a33c70d0afd1d984895920c4f555e3e2282e022361f6/index.js
  packages/@aws-cdk-testing/framework-integ/test/aws-iam/test/integ.oidc-provider.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-iam/test/integ.oidc-provider.js.snapshot/oidc-provider-integ-test.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-iam/test/integ.oidc-provider.js.snapshot/oidc-provider-integ-test.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-iam/test/integ.oidc-provider.js.snapshot/tree.json
  packages/@aws-cdk/custom-resource-handlers/lib/aws-iam/oidc-handler/diff.ts
  packages/@aws-cdk/custom-resource-handlers/lib/aws-iam/oidc-handler/external.ts
  packages/@aws-cdk/custom-resource-handlers/lib/aws-iam/oidc-handler/index.ts
  packages/@aws-cdk/custom-resource-handlers/test/aws-iam/oidc-handler.test.ts
  packages/aws-cdk-lib/aws-iam/lib/oidc-provider.ts
  packages/aws-cdk-lib/aws-iam/lib/oidc-provider/.is_custom_resource
  packages/aws-cdk-lib/aws-iam/test/oidc-provider.test.ts
Labels: p2, contribution/core, handler-migration

#28054 chore: check-pack-prerequisites checks for python 3.8 now
  CONTRIBUTING.md
  README.md
  scripts/check-pack-prerequisites.sh
Labels: p2, contribution/core

#27998 chore: convert contribution diagram from png to mermaid
  CONTRIBUTING.md
  docs/contribution_flow.png
Labels: p2, contribution/core

#27898 chore(certificatemanager): migrate dns validated certificate handler
  packages/@aws-cdk-testing/framework-integ/test/aws-certificatemanager/test/integ.dns-validated-certificate.js.snapshot/asset.8dd3f997ac74aa13ef09bc8bed060ecdbe3111898c6bbc0eb4f2130c9c53233b/index.js
  packages/@aws-cdk-testing/framework-integ/test/aws-certificatemanager/test/integ.dns-validated-certificate.js.snapshot/asset.fb83c347f6a5e3099f787c17ce0845a70a81fd83fdc20eb2e4e1cb01961a8774/index.js
  packages/@aws-cdk-testing/framework-integ/test/aws-certificatemanager/test/integ.dns-validated-certificate.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-certificatemanager/test/integ.dns-validated-certificate.js.snapshot/integ-dns-validated-certificate.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-certificatemanager/test/integ.dns-validated-certificate.js.snapshot/integ-dns-validated-certificate.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-certificatemanager/test/integ.dns-validated-certificate.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-certificatemanager/test/integ.dns-validated-certificate.js.snapshot/integtestDefaultTestDeployAssert24D5C536.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-certificatemanager/test/integ.dns-validated-certificate.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-certificatemanager/test/integ.dns-validated-certificate.js.snapshot/tree.json
  packages/@aws-cdk/custom-resource-handlers/.gitignore
  packages/@aws-cdk/custom-resource-handlers/lib/aws-certificatemanager/dns-validated-certificate-handler/index.js
  packages/@aws-cdk/custom-resource-handlers/package.json
  packages/@aws-cdk/custom-resource-handlers/test/aws-certificatemanager/dns-validated-certificate-handler.test.js
  packages/aws-cdk-lib/aws-certificatemanager/lambda-packages/.no-packagejson-validator
  packages/aws-cdk-lib/aws-certificatemanager/lambda-packages/dns_validated_certificate_handler/.eslintrc.js
  packages/aws-cdk-lib/aws-certificatemanager/lambda-packages/dns_validated_certificate_handler/.gitignore
  packages/aws-cdk-lib/aws-certificatemanager/lambda-packages/dns_validated_certificate_handler/.node-version
  packages/aws-cdk-lib/aws-certificatemanager/lambda-packages/dns_validated_certificate_handler/.npmignore
  packages/aws-cdk-lib/aws-certificatemanager/lambda-packages/dns_validated_certificate_handler/LICENSE
  packages/aws-cdk-lib/aws-certificatemanager/lambda-packages/dns_validated_certificate_handler/NOTICE
  packages/aws-cdk-lib/aws-certificatemanager/lambda-packages/dns_validated_certificate_handler/README.md
  packages/aws-cdk-lib/aws-certificatemanager/lambda-packages/dns_validated_certificate_handler/jest.config.js
  packages/aws-cdk-lib/aws-certificatemanager/lambda-packages/dns_validated_certificate_handler/package.json
  packages/aws-cdk-lib/aws-certificatemanager/lib/dns-validated-certificate.ts
Labels: p2, contribution/core, handler-migration

#28068 chore: pr-build failing with unsafe-perm is not a valid npm option
  buildspec-pr.yaml
Labels: p2, contribution/core, pr/needs-maintainer-review

#28069 chore: build failing with unsafe-perm is not a valid npm option
  buildspec.yaml
Labels: p2, contribution/core, pr-linter/cli-integ-tested, pr/needs-maintainer-review

#28073 feat: update AWS Service Spec
  packages/@aws-cdk/cloudformation-diff/package.json
  packages/@aws-cdk/integ-runner/package.json
  packages/aws-cdk-lib/package.json
  tools/@aws-cdk/spec2cdk/package.json
  yarn.lock
Labels: p2, dependencies, contribution/core, pr-linter/exempt-readme, pr-linter/exempt-test, auto-approve, pr-linter/exempt-integ-test

#28067 fix(cloudformation-diff): cdk diff fails on node14
  packages/@aws-cdk/cloudformation-diff/lib/diff/util.ts
Labels: p2, contribution/core, pr-linter/exempt-test, pr-linter/exempt-integ-test, pr/needs-maintainer-review

#27861 fix(apigatewayv2-integrations): integrations of imported lambda functions do not get configured
  packages/@aws-cdk/aws-apigatewayv2-integrations-alpha/test/http/integ.add-subroute-integration.js.snapshot/IntegDefaultTestDeployAssert4E6713E1.assets.json
  packages/@aws-cdk/aws-apigatewayv2-integrations-alpha/test/http/integ.add-subroute-integration.js.snapshot/IntegDefaultTestDeployAssert4E6713E1.template.json
  packages/@aws-cdk/aws-apigatewayv2-integrations-alpha/test/http/integ.add-subroute-integration.js.snapshot/asset.a5feac1d1e65b04919886f5961fd2ba1352489d558439d9d6592877e92fc2814.bundle/index.js
  packages/@aws-cdk/aws-apigatewayv2-integrations-alpha/test/http/integ.add-subroute-integration.js.snapshot/cdk.out
  packages/@aws-cdk/aws-apigatewayv2-integrations-alpha/test/http/integ.add-subroute-integration.js.snapshot/integ-lambda-add-subroute-integration.assets.json
  packages/@aws-cdk/aws-apigatewayv2-integrations-alpha/test/http/integ.add-subroute-integration.js.snapshot/integ-lambda-add-subroute-integration.template.json
  packages/@aws-cdk/aws-apigatewayv2-integrations-alpha/test/http/integ.add-subroute-integration.js.snapshot/integ.json
  packages/@aws-cdk/aws-apigatewayv2-integrations-alpha/test/http/integ.add-subroute-integration.js.snapshot/manifest.json
  packages/@aws-cdk/aws-apigatewayv2-integrations-alpha/test/http/integ.add-subroute-integration.js.snapshot/tree.json
  packages/@aws-cdk/aws-apigatewayv2-integrations-alpha/test/http/integ.add-subroute-integration.ts
  packages/aws-cdk-lib/aws-lambda/README.md
  packages/aws-cdk-lib/aws-lambda/lib/function-base.ts
  packages/aws-cdk-lib/aws-lambda/lib/function.ts
Labels: bug, p1, effort/small, contribution/core

#28053 chore(route53): migrate existing record set handler
  packages/@aws-cdk-testing/framework-integ/test/aws-route53/test/integ.delete-existing-record-set.js.snapshot/asset.482643dcf7106ecdc7f4ff9aefba13d1e5c7265377e6c6b9c77245f2bc55f6ef/index.js
  packages/@aws-cdk-testing/framework-integ/test/aws-route53/test/integ.delete-existing-record-set.js.snapshot/asset.a4d4a9308995dd99b8a8a3089e4f2087a577a6d3f8a3fc902354155a2b0b00c5/__entrypoint__.js
  packages/@aws-cdk-testing/framework-integ/test/aws-route53/test/integ.delete-existing-record-set.js.snapshot/asset.a4d4a9308995dd99b8a8a3089e4f2087a577a6d3f8a3fc902354155a2b0b00c5/index.js
  packages/@aws-cdk-testing/framework-integ/test/aws-route53/test/integ.delete-existing-record-set.js.snapshot/cdk-route53-integ-delete-existing-record-set.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-route53/test/integ.delete-existing-record-set.js.snapshot/cdk-route53-integ-delete-existing-record-set.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-route53/test/integ.delete-existing-record-set.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-route53/test/integ.delete-existing-record-set.js.snapshot/tree.json
  packages/@aws-cdk/custom-resource-handlers/lib/aws-route53/delete-existing-record-set-handler/index.ts
  packages/@aws-cdk/custom-resource-handlers/test/aws-route53/delete-existing-record-set-handler.test.ts
  packages/aws-cdk-lib/aws-route53/lib/delete-existing-record-set-handler/.is_custom_resource
  packages/aws-cdk-lib/aws-route53/lib/record-set.ts
Labels: p2, contribution/core, handler-migration

#27797 fix(lambda-event-sources): event source property maxConcurrency is not token-aware
  packages/aws-cdk-lib/aws-lambda/lib/event-source-mapping.ts
  packages/aws-cdk-lib/aws-lambda/test/event-source-mapping.test.ts
Labels: bug, p2, pr-linter/exempt-integ-test, beginning-contributor

#27807 chore(ec2): migrate restrict default security group handler
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.launch-template.js.snapshot/LambdaTestDefaultTestDeployAssert1AF2B360.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.launch-template.js.snapshot/asset.18d379b052acd60e0d086d5b19d9bef956ebc0bd018c5570960125aab0c7f837/index.js
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.launch-template.js.snapshot/asset.a099fdfc61c84ffc56cef4fb2c9472483623ac865ce5d8fca88c89cf60d48d03/__entrypoint__.js
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.launch-template.js.snapshot/asset.a099fdfc61c84ffc56cef4fb2c9472483623ac865ce5d8fca88c89cf60d48d03/index.js
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.launch-template.js.snapshot/aws-cdk-ec2-lt-metadata-1.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.launch-template.js.snapshot/aws-cdk-ec2-lt-metadata-1.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.launch-template.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.launch-template.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.launch-template.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.launch-template.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.launch-template.ts
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.vpc-flow-logs-kinesis.js.snapshot/FlowLogsTestStack.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.vpc-flow-logs-kinesis.js.snapshot/FlowLogsTestStack.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.vpc-flow-logs-kinesis.js.snapshot/asset.1be0bac6581864b510bdbf0a114f1d3429244758da7657cc365f73d371fe70ed/index.js
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.vpc-flow-logs-kinesis.js.snapshot/asset.a099fdfc61c84ffc56cef4fb2c9472483623ac865ce5d8fca88c89cf60d48d03/__entrypoint__.js
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.vpc-flow-logs-kinesis.js.snapshot/asset.a099fdfc61c84ffc56cef4fb2c9472483623ac865ce5d8fca88c89cf60d48d03/index.js
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.vpc-flow-logs-kinesis.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.vpc-flow-logs-kinesis.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.vpc-restrict-default-sg.js.snapshot/asset.18d379b052acd60e0d086d5b19d9bef956ebc0bd018c5570960125aab0c7f837/index.js
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.vpc-restrict-default-sg.js.snapshot/asset.6eced19a8c3006faf4829b3f9c70fe1a0ebacbe51afcc72d41b338e5e904d67f.bundle/index.js
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.vpc-restrict-default-sg.js.snapshot/asset.a099fdfc61c84ffc56cef4fb2c9472483623ac865ce5d8fca88c89cf60d48d03/__entrypoint__.js
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.vpc-restrict-default-sg.js.snapshot/asset.a099fdfc61c84ffc56cef4fb2c9472483623ac865ce5d8fca88c89cf60d48d03/index.js
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.vpc-restrict-default-sg.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.vpc-restrict-default-sg.js.snapshot/integ-restrict-default-sg.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.vpc-restrict-default-sg.js.snapshot/integ-restrict-default-sg.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.vpc-restrict-default-sg.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.vpc-restrict-default-sg.js.snapshot/integtestDefaultTestDeployAssert24D5C536.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.vpc-restrict-default-sg.js.snapshot/integtestDefaultTestDeployAssert24D5C536.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.vpc-restrict-default-sg.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.vpc-restrict-default-sg.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.vpc-restrict-default-sg.ts
  packages/@aws-cdk-testing/framework-integ/test/aws-elasticloadbalancingv2/test/integ.alb.oidc.js.snapshot/IntegAlbOidc.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-elasticloadbalancingv2/test/integ.alb.oidc.js.snapshot/IntegAlbOidc.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-elasticloadbalancingv2/test/integ.alb.oidc.js.snapshot/IntegTestAlbOidcDefaultTestDeployAssert2476ECB6.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-elasticloadbalancingv2/test/integ.alb.oidc.js.snapshot/IntegTestAlbOidcDefaultTestDeployAssert2476ECB6.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-elasticloadbalancingv2/test/integ.alb.oidc.js.snapshot/asset.1be0bac6581864b510bdbf0a114f1d3429244758da7657cc365f73d371fe70ed/index.js
  packages/@aws-cdk-testing/framework-integ/test/aws-elasticloadbalancingv2/test/integ.alb.oidc.js.snapshot/asset.6eced19a8c3006faf4829b3f9c70fe1a0ebacbe51afcc72d41b338e5e904d67f.bundle/index.js
  packages/@aws-cdk-testing/framework-integ/test/aws-elasticloadbalancingv2/test/integ.alb.oidc.js.snapshot/asset.a099fdfc61c84ffc56cef4fb2c9472483623ac865ce5d8fca88c89cf60d48d03/__entrypoint__.js
  packages/@aws-cdk-testing/framework-integ/test/aws-elasticloadbalancingv2/test/integ.alb.oidc.js.snapshot/asset.a099fdfc61c84ffc56cef4fb2c9472483623ac865ce5d8fca88c89cf60d48d03/index.js
  packages/@aws-cdk-testing/framework-integ/test/aws-elasticloadbalancingv2/test/integ.alb.oidc.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-nodejs/test/integ.latest.js.snapshot/asset.5dc6123387f48186befea8235f67522a8415162b86b07a456ba44684bdf32a29.bundle/index.js
  packages/@aws-cdk/custom-resource-handlers/lib/aws-ec2/restrict-default-security-group-handler/index.ts
  packages/@aws-cdk/custom-resource-handlers/package.json
  packages/@aws-cdk/custom-resource-handlers/test/aws-ec2/restrict-default-security-group-handler.test.ts
  packages/aws-cdk-lib/aws-ec2/lib/restrict-default-security-group-handler/.is_custom_resource
  packages/aws-cdk-lib/aws-ec2/lib/vpc.ts
Labels: p2, contribution/core, handler-migration

#28075 chore(core): use key instead of logicalId for key when provided
  packages/aws-cdk-lib/core/lib/cfn-output.ts
  packages/aws-cdk-lib/core/test/output.test.ts
Labels: p2, contribution/core

#28045 chore(lambda): validate logLevel with logFormat for advanced logging
  packages/aws-cdk-lib/aws-lambda/README.md
  packages/aws-cdk-lib/aws-lambda/lib/function.ts
  packages/aws-cdk-lib/aws-lambda/test/logging-config.test.ts
Labels: p2, star-contributor, pr/needs-maintainer-review

#27927 fix(scheduler): schedule not added to group with unspecified name
  packages/@aws-cdk/aws-scheduler-alpha/lib/group.ts
  packages/@aws-cdk/aws-scheduler-alpha/test/group.test.ts
  packages/@aws-cdk/aws-scheduler-alpha/test/integ.schedule.js.snapshot/aws-cdk-scheduler-schedule.assets.json
  packages/@aws-cdk/aws-scheduler-alpha/test/integ.schedule.js.snapshot/aws-cdk-scheduler-schedule.template.json
  packages/@aws-cdk/aws-scheduler-alpha/test/integ.schedule.js.snapshot/manifest.json
  packages/@aws-cdk/aws-scheduler-alpha/test/integ.schedule.js.snapshot/tree.json
  packages/@aws-cdk/aws-scheduler-alpha/test/integ.schedule.ts
Labels: bug, p2, effort/medium, admired-contributor

#27873 fix(apigateway): lambda authorizer does not enforce default cache TTL
  packages/@aws-cdk-testing/framework-integ/test/aws-apigateway/test/authorizers/integ.request-authorizer.lit.js.snapshot/RequestAuthorizerInteg.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-apigateway/test/authorizers/integ.token-authorizer-iam-role.js.snapshot/TokenAuthorizerIAMRoleInteg.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-apigateway/test/authorizers/integ.token-authorizer.js.snapshot/TokenAuthorizerInteg.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-apigateway/test/authorizers/integ.token-authorizer.ts
  packages/aws-cdk-lib/aws-apigateway/lib/authorizers/lambda.ts
  packages/aws-cdk-lib/aws-apigateway/test/authorizers/lambda.test.ts
Labels: bug, p2, distinguished-contributor, pr/needs-maintainer-review

#27978 feat(elasticloadbalancingv2): add security group support for nlb
  packages/@aws-cdk-testing/framework-integ/test/aws-elasticloadbalancingv2/test/integ.nlb.js.snapshot/aws-cdk-elbv2-integ.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-elasticloadbalancingv2/test/integ.nlb.js.snapshot/aws-cdk-elbv2-integ.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-elasticloadbalancingv2/test/integ.nlb.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-elasticloadbalancingv2/test/integ.nlb.js.snapshot/elbv2integDefaultTestDeployAssert6120E394.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-elasticloadbalancingv2/test/integ.nlb.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-elasticloadbalancingv2/test/integ.nlb.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-elasticloadbalancingv2/test/integ.nlb.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-elasticloadbalancingv2/test/integ.nlb.ts
  packages/@aws-cdk/cli-lib-alpha/THIRD_PARTY_LICENSES
  packages/aws-cdk-lib/aws-elasticloadbalancingv2/README.md
  packages/aws-cdk-lib/aws-elasticloadbalancingv2/lib/nlb/network-load-balancer.ts
  packages/aws-cdk-lib/aws-elasticloadbalancingv2/test/nlb/load-balancer.test.ts
  packages/aws-cdk-lib/awslint.json
Labels: p2, feature-request, effort/medium, admired-contributor

#27774 feat(scheduler-targets): SqsSendMessage Target
  packages/@aws-cdk/aws-scheduler-targets-alpha/README.md
  packages/@aws-cdk/aws-scheduler-targets-alpha/lib/index.ts
  packages/@aws-cdk/aws-scheduler-targets-alpha/lib/sqs-send-message.ts
  packages/@aws-cdk/aws-scheduler-targets-alpha/test/integ.sqs-send-message.js.snapshot/asset.211bd8c514e07e047addb5c06afe6f8e85ce4e0b19b64ad78b28e84fc09aafe7.bundle/index.js
  packages/@aws-cdk/aws-scheduler-targets-alpha/test/integ.sqs-send-message.js.snapshot/aws-cdk-schedule.assets.json
  packages/@aws-cdk/aws-scheduler-targets-alpha/test/integ.sqs-send-message.js.snapshot/aws-cdk-schedule.template.json
  packages/@aws-cdk/aws-scheduler-targets-alpha/test/integ.sqs-send-message.js.snapshot/cdk.out
  packages/@aws-cdk/aws-scheduler-targets-alpha/test/integ.sqs-send-message.js.snapshot/integ.json
  packages/@aws-cdk/aws-scheduler-targets-alpha/test/integ.sqs-send-message.js.snapshot/integsqssendmessageDefaultTestDeployAssert883D0D33.assets.json
  packages/@aws-cdk/aws-scheduler-targets-alpha/test/integ.sqs-send-message.js.snapshot/integsqssendmessageDefaultTestDeployAssert883D0D33.template.json
  packages/@aws-cdk/aws-scheduler-targets-alpha/test/integ.sqs-send-message.js.snapshot/manifest.json
  packages/@aws-cdk/aws-scheduler-targets-alpha/test/integ.sqs-send-message.js.snapshot/tree.json
  packages/@aws-cdk/aws-scheduler-targets-alpha/test/integ.sqs-send-message.ts
  packages/@aws-cdk/aws-scheduler-targets-alpha/test/sqs-send-message.test.ts
Labels: p2, feature-request, effort/medium, star-contributor, pr/needs-maintainer-review

#28091 docs(scheduler): fix typo in EventBridge Scheduler docs
  packages/@aws-cdk/aws-scheduler-alpha/lib/target.ts
Labels: p2, repeat-contributor

#28085 chore(rds): support RDS for SQL Server 14.00.3465.1.v1, 13.00.6435.1.v1 and 12.00.6449.1.v1
  packages/aws-cdk-lib/aws-rds/lib/instance-engine.ts
Labels: p2, star-contributor

#27996 chore(apigatewayv2): review readme
  packages/@aws-cdk/aws-apigatewayv2-alpha/README.md
  packages/@aws-cdk/aws-apigatewayv2-authorizers-alpha/README.md
  packages/@aws-cdk/aws-apigatewayv2-integrations-alpha/README.md
Labels: p2, contribution/core

#28093 chore(release): v2.110.1
  CHANGELOG.v2.alpha.md
  CHANGELOG.v2.md
  buildspec-pr.yaml
  buildspec.yaml
  packages/aws-cdk/lib/api/evaluate-cloudformation-template.ts
  packages/aws-cdk/test/api/hotswap/nested-stacks-hotswap.test.ts
  packages/aws-cdk/test/nested-stack-templates/one-stack-with-two-nested-stacks-stack.template.json
  version.v2.json
Labels: p2, contribution/core, pr/no-squash, pr-linter/cli-integ-tested

#27925 feat(backup): add disableDefaultBackupPolicy property to selection
  packages/@aws-cdk-testing/framework-integ/test/aws-backup/test/integ.backup-selection.js.snapshot/BackupSelectionTestDefaultTestDeployAssertA837BB17.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-backup/test/integ.backup-selection.js.snapshot/BackupSelectionTestDefaultTestDeployAssertA837BB17.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-backup/test/integ.backup-selection.js.snapshot/cdk-backup-selection.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-backup/test/integ.backup-selection.js.snapshot/cdk-backup-selection.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-backup/test/integ.backup-selection.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-backup/test/integ.backup-selection.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-backup/test/integ.backup-selection.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-backup/test/integ.backup-selection.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-backup/test/integ.backup-selection.ts
  packages/aws-cdk-lib/aws-backup/README.md
  packages/aws-cdk-lib/aws-backup/lib/selection.ts
  packages/aws-cdk-lib/aws-backup/test/selection.test.ts
Labels: p2, feature-request, effort/small, star-contributor

#28096 chore(merge-back): 2.110.1
  CHANGELOG.v2.alpha.md
  CHANGELOG.v2.md
  version.v2.json
Labels: p2, pr/needs-community-review, pr/no-squash, auto-approve

#28097 chore(rds): support RDS for PostgreSQL 16.1 and 15.5
  packages/aws-cdk-lib/aws-rds/lib/instance-engine.ts
Labels: p2, pr/needs-community-review, star-contributor

#28110 chore(ec2): improve doc for resolveSsmParameterAtLaunch()
  packages/aws-cdk-lib/aws-ec2/README.md
Labels: bug, p2, effort/small, contribution/core, pr/needs-maintainer-review

#28109 feat(opensearch): OpenSearch 2.11 engine version
  packages/@aws-cdk-testing/framework-integ/test/aws-opensearchservice/test/integ.opensearch.min.js.snapshot/IntegDefaultTestDeployAssert4E6713E1.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-opensearchservice/test/integ.opensearch.min.js.snapshot/cdk-integ-opensearch.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-opensearchservice/test/integ.opensearch.min.js.snapshot/cdk-integ-opensearch.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-opensearchservice/test/integ.opensearch.min.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-opensearchservice/test/integ.opensearch.min.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-opensearchservice/test/integ.opensearch.min.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-opensearchservice/test/integ.opensearch.min.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-opensearchservice/test/integ.opensearch.min.ts
  packages/aws-cdk-lib/aws-opensearchservice/lib/version.ts
  packages/aws-cdk-lib/aws-opensearchservice/test/domain.test.ts
Labels: p2, pr-linter/exempt-readme, distinguished-contributor

#28113 chore(cli): cli import code never reaches "??" operator
  packages/aws-cdk/lib/import.ts
Labels: p2, contribution/core, pr-linter/cli-integ-tested, pr/needs-maintainer-review

#28121 fix: java package names are incorrect for a number of packages
  packages/aws-cdk-lib/aws-backupgateway/.jsiirc.json
  packages/aws-cdk-lib/aws-cleanrooms/.jsiirc.json
  packages/aws-cdk-lib/aws-entityresolution/.jsiirc.json
  packages/aws-cdk-lib/aws-healthimaging/.jsiirc.json
  packages/aws-cdk-lib/aws-mediapackagev2/.jsiirc.json
  packages/aws-cdk-lib/aws-osis/.jsiirc.json
  packages/aws-cdk-lib/aws-pcaconnectorad/.jsiirc.json
  packages/aws-cdk-lib/aws-proton/.jsiirc.json
  packages/aws-cdk-lib/aws-shield/.jsiirc.json
  packages/aws-cdk-lib/aws-verifiedpermissions/.jsiirc.json
  packages/aws-cdk-lib/aws-workspacesweb/.jsiirc.json
  tools/@aws-cdk/spec2cdk/lib/cfn2ts/pkglint.ts
Labels: p2, contribution/core, pr-linter/exempt-test, pr-linter/exempt-integ-test, pr/needs-maintainer-review

#28147 feat: update AWS Service Spec
  packages/@aws-cdk/cloudformation-diff/package.json
  packages/@aws-cdk/integ-runner/package.json
  packages/aws-cdk-lib/package.json
  tools/@aws-cdk/spec2cdk/package.json
  yarn.lock
Labels: p2, dependencies, contribution/core, pr-linter/exempt-readme, pr-linter/exempt-test, auto-approve, pr-linter/exempt-integ-test

#28112 fix(msk-alpha): cluster deployment fails in `ap-southeast-1`
  packages/@aws-cdk/aws-msk-alpha/lib/cluster.ts
  packages/@aws-cdk/aws-msk-alpha/test/integ.cluster-zookeeper.js.snapshot/KafkaZookeeperIntegTestDefaultTestDeployAssert731E1402.assets.json
  packages/@aws-cdk/aws-msk-alpha/test/integ.cluster-zookeeper.js.snapshot/KafkaZookeeperTestStack.assets.json
  packages/@aws-cdk/aws-msk-alpha/test/integ.cluster-zookeeper.js.snapshot/KafkaZookeeperTestStack.template.json
  packages/@aws-cdk/aws-msk-alpha/test/integ.cluster-zookeeper.js.snapshot/asset.b0de6372e1c756b7afa1a8a1d0a21ee4cd330150290abffc9bc163f285150514/index.js
  packages/@aws-cdk/aws-msk-alpha/test/integ.cluster-zookeeper.js.snapshot/asset.e5178afc49b7c6a85127a67856ce958e4f0879ce6aad5e974cac2a088bf939db/index.js
  packages/@aws-cdk/aws-msk-alpha/test/integ.cluster-zookeeper.js.snapshot/cdk.out
  packages/@aws-cdk/aws-msk-alpha/test/integ.cluster-zookeeper.js.snapshot/integ.json
  packages/@aws-cdk/aws-msk-alpha/test/integ.cluster-zookeeper.js.snapshot/manifest.json
  packages/@aws-cdk/aws-msk-alpha/test/integ.cluster-zookeeper.js.snapshot/tree.json
Labels: bug, p1, effort/medium, contribution/core, pr-linter/exempt-integ-test

#28151 chore: remove cdkMetadataResourceAvailable from the region test snapshot
  packages/aws-cdk-lib/region-info/test/__snapshots__/region-info.test.ts.snap
  packages/aws-cdk-lib/region-info/test/region-info.test.ts
Labels: p2, contribution/core

#27658 feat(lambda-nodejs): add verbose and debug log level to esbuild bundling
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-nodejs/test/integ.function.js.snapshot/cdk-integ-lambda-nodejs.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-nodejs/test/integ.function.js.snapshot/cdk-integ-lambda-nodejs.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-nodejs/test/integ.function.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-nodejs/test/integ.function.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-nodejs/test/integ.function.ts
  packages/aws-cdk-lib/aws-lambda-nodejs/README.md
  packages/aws-cdk-lib/aws-lambda-nodejs/lib/types.ts
  packages/aws-cdk-lib/aws-lambda-nodejs/test/bundling.test.ts
Labels: p2, feature-request, effort/small, admired-contributor, pr/needs-maintainer-review

#28153 chore(release): 2.111.0
  CHANGELOG.v2.alpha.md
  CHANGELOG.v2.md
  packages/@aws-cdk-testing/framework-integ/test/aws-logs/test/integ.loggroupclass.js.snapshot/LogGroupClassIntegTestDefaultTestDeployAssert18FBD13E.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-logs/test/integ.loggroupclass.js.snapshot/LogGroupClassIntegTestDefaultTestDeployAssert18FBD13E.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-logs/test/integ.loggroupclass.js.snapshot/asset.d2177630a4e35343f2d3607feeb0ff4cb752ff09905bd54e63cf05f6de393c58.bundle/index.js
  packages/@aws-cdk-testing/framework-integ/test/aws-logs/test/integ.loggroupclass.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-logs/test/integ.loggroupclass.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-logs/test/integ.loggroupclass.js.snapshot/log-group-class.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-logs/test/integ.loggroupclass.js.snapshot/log-group-class.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-logs/test/integ.loggroupclass.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-logs/test/integ.loggroupclass.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-logs/test/integ.loggroupclass.ts
  packages/aws-cdk-lib/aws-logs/lib/log-group.ts
  packages/aws-cdk-lib/aws-logs/test/loggroup.test.ts
  tools/@aws-cdk/spec2cdk/temporary-schemas/us-east-1/aws-logs-loggroup.json
  version.v2.json
Labels: p2, contribution/core, pr/no-squash

#28157 chore(merge-back): 2.111.0
  CHANGELOG.v2.alpha.md
  CHANGELOG.v2.md
  packages/@aws-cdk-testing/framework-integ/test/aws-logs/test/integ.loggroupclass.js.snapshot/LogGroupClassIntegTestDefaultTestDeployAssert18FBD13E.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-logs/test/integ.loggroupclass.js.snapshot/LogGroupClassIntegTestDefaultTestDeployAssert18FBD13E.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-logs/test/integ.loggroupclass.js.snapshot/asset.d2177630a4e35343f2d3607feeb0ff4cb752ff09905bd54e63cf05f6de393c58.bundle/index.js
  packages/@aws-cdk-testing/framework-integ/test/aws-logs/test/integ.loggroupclass.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-logs/test/integ.loggroupclass.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-logs/test/integ.loggroupclass.js.snapshot/log-group-class.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-logs/test/integ.loggroupclass.js.snapshot/log-group-class.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-logs/test/integ.loggroupclass.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-logs/test/integ.loggroupclass.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-logs/test/integ.loggroupclass.ts
  packages/aws-cdk-lib/aws-logs/lib/log-group.ts
  packages/aws-cdk-lib/aws-logs/test/loggroup.test.ts
  tools/@aws-cdk/spec2cdk/temporary-schemas/us-east-1/aws-logs-loggroup.json
  version.v2.json
Labels: p2, pr/needs-community-review, pr/no-squash, auto-approve

#28115 docs(rds): typo in RDS prop docs
  packages/aws-cdk-lib/aws-rds/lib/aurora-cluster-instance.ts
  packages/aws-cdk-lib/aws-rds/lib/instance.ts
  packages/aws-cdk-lib/aws-rds/lib/props.ts
Labels: p2, beginning-contributor

#28160 feat(region-info): update Metadata regions
  packages/aws-cdk-lib/region-info/build-tools/metadata.ts
Labels: p2, dependencies, contribution/core, pr-linter/exempt-readme, pr-linter/exempt-test, auto-approve, pr-linter/exempt-integ-test

#28166 feat(region-info): update Metadata regions
  packages/aws-cdk-lib/region-info/build-tools/metadata.ts
Labels: p2, dependencies, contribution/core, pr-linter/exempt-readme, pr-linter/exempt-test, auto-approve, pr-linter/exempt-integ-test

#28149 fix(core): incorrect CloudFormation date formatting
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda/test/integ.autoscaling.lit.js.snapshot/aws-lambda-autoscaling.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda/test/integ.autoscaling.lit.js.snapshot/aws-lambda-autoscaling.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda/test/integ.autoscaling.lit.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda/test/integ.autoscaling.lit.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda/test/integ.autoscaling.lit.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda/test/integ.autoscaling.lit.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda/test/integ.autoscaling.lit.ts
  packages/@aws-cdk-testing/framework-integ/test/aws-s3/test/integ.lifecycle.js.snapshot/aws-cdk-s3.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-s3/test/integ.lifecycle.js.snapshot/aws-cdk-s3.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-s3/test/integ.lifecycle.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-s3/test/integ.lifecycle.js.snapshot/cdkinteglifecycleDefaultTestDeployAssert83FA03B1.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-s3/test/integ.lifecycle.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-s3/test/integ.lifecycle.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-s3/test/integ.lifecycle.js.snapshot/tree.json
  packages/aws-cdk-lib/aws-s3/test/rules.test.ts
  packages/aws-cdk-lib/core/lib/runtime.ts
Labels: bug, p2, effort/medium, admired-contributor, pr/needs-maintainer-review

#28171 docs(lambda): explain NODEJS_LATEST better
  packages/aws-cdk-lib/aws-lambda/lib/runtime.ts
Labels: p2, contribution/core

#28172 chore(apigatewayv2-authorizers-alpha): turn on awslint
  packages/@aws-cdk/aws-apigatewayv2-authorizers-alpha/awslint.json
Labels: p2, contribution/core

#28173 chore(apigatewayv2-integrations-alpha): turn on awslint
  packages/@aws-cdk/aws-apigatewayv2-integrations-alpha/awslint.json
Labels: p2, contribution/core

#27946 chore(codebuild): added validation when using Windows Image
  packages/aws-cdk-lib/aws-codebuild/lib/project.ts
  packages/aws-cdk-lib/aws-codebuild/test/codebuild.test.ts
Labels: p2, beginning-contributor
