Repository aws/aws-cdk, pull requests merged in 2023-03, with the labels that each got.

#24227 refactor(ecs): refactor addPortMapping method
  packages/@aws-cdk/aws-ecs/lib/container-definition.ts
  packages/@aws-cdk/aws-ecs/test/container-definition.test.ts
Labels: p2, feature-request, effort/medium, repeat-contributor

#24385 chore(iam): throw warning if managed policies attached to a group exceeds 10
  packages/@aws-cdk/aws-iam/lib/group.ts
  packages/@aws-cdk/aws-iam/test/group.test.ts
Labels: p1, feature-request, effort/small, repeat-contributor

#24396 chore: use jsii-rosetta@v4.9-next
  package.json
  yarn.lock
Labels: p2, contribution/core

#24398 chore: npm-check-updates && yarn upgrade
  package.json
  packages/@aws-cdk-testing/cli-integ/package.json
  packages/@aws-cdk/aws-amplify/package.json
  packages/@aws-cdk/aws-certificatemanager/lambda-packages/dns_validated_certificate_handler/package.json
  packages/@aws-cdk/aws-cloudfront-origins/package.json
  packages/@aws-cdk/aws-cloudfront/package.json
  packages/@aws-cdk/aws-cloudtrail/package.json
  packages/@aws-cdk/aws-codebuild/package.json
  packages/@aws-cdk/aws-codecommit/package.json
  packages/@aws-cdk/aws-dynamodb/package.json
  packages/@aws-cdk/aws-eks/package.json
  packages/@aws-cdk/aws-eks/test/sdk-call-integ-test-docker-app/app/package.json
  packages/@aws-cdk/aws-events-targets/package.json
  packages/@aws-cdk/aws-globalaccelerator-endpoints/package.json
  packages/@aws-cdk/aws-logs/package.json
  packages/@aws-cdk/aws-redshift/package.json
  packages/@aws-cdk/aws-route53/package.json
  packages/@aws-cdk/aws-sqs/package.json
  packages/@aws-cdk/core/package.json
  packages/@aws-cdk/custom-resources/package.json
  packages/@aws-cdk/integ-runner/THIRD_PARTY_LICENSES
  packages/@aws-cdk/integ-runner/package.json
  packages/@aws-cdk/integ-tests/package.json
  packages/@aws-cdk/lambda-layer-awscli/package.json
  packages/@aws-cdk/lambda-layer-node-proxy-agent/package.json
  packages/@aws-cdk/pipelines/package.json
  packages/@aws-cdk/triggers/package.json
  packages/aws-cdk-lib/package.json
  packages/aws-cdk/THIRD_PARTY_LICENSES
  packages/aws-cdk/lib/init-templates/app/typescript/package.json
  packages/aws-cdk/lib/init-templates/lib/typescript/package.json
  packages/aws-cdk/lib/init-templates/sample-app/typescript/package.json
  packages/aws-cdk/package.json
  packages/awslint/package.json
  packages/cdk-assets/package.json
  packages/cdk-dasm/package.json
  tools/@aws-cdk/cdk-build-tools/package.json
  tools/@aws-cdk/cfn2ts/package.json
  tools/@aws-cdk/node-bundle/package.json
  yarn.lock
Labels: p2, dependencies, contribution/core, auto-approve

#24067 feat(apigateway): minCompressionSize on SpecRestApi
  packages/@aws-cdk/aws-apigateway/lib/restapi.ts
  packages/@aws-cdk/aws-apigateway/test/integ.restapi.js.snapshot/apigatewayrestapiDefaultTestDeployAssert6A9696A7.assets.json
  packages/@aws-cdk/aws-apigateway/test/integ.restapi.js.snapshot/cdk.out
  packages/@aws-cdk/aws-apigateway/test/integ.restapi.js.snapshot/integ.json
  packages/@aws-cdk/aws-apigateway/test/integ.restapi.js.snapshot/manifest.json
  packages/@aws-cdk/aws-apigateway/test/integ.restapi.js.snapshot/test-apigateway-restapi.assets.json
  packages/@aws-cdk/aws-apigateway/test/integ.restapi.js.snapshot/test-apigateway-restapi.template.json
  packages/@aws-cdk/aws-apigateway/test/integ.restapi.js.snapshot/tree.json
  packages/@aws-cdk/aws-apigateway/test/integ.restapi.ts
  packages/@aws-cdk/aws-apigateway/test/integ.spec-restapi.js.snapshot/apigatewayspecrestapiDefaultTestDeployAssertD16AA485.assets.json
  packages/@aws-cdk/aws-apigateway/test/integ.spec-restapi.js.snapshot/cdk.out
  packages/@aws-cdk/aws-apigateway/test/integ.spec-restapi.js.snapshot/integ.json
  packages/@aws-cdk/aws-apigateway/test/integ.spec-restapi.js.snapshot/manifest.json
  packages/@aws-cdk/aws-apigateway/test/integ.spec-restapi.js.snapshot/test-apigateway-spec-restapi.assets.json
  packages/@aws-cdk/aws-apigateway/test/integ.spec-restapi.js.snapshot/test-apigateway-spec-restapi.template.json
  packages/@aws-cdk/aws-apigateway/test/integ.spec-restapi.js.snapshot/tree.json
  packages/@aws-cdk/aws-apigateway/test/integ.spec-restapi.ts
  packages/@aws-cdk/aws-apigateway/test/restapi.test.ts
Labels: p2, feature-request, effort/small, contribution/core, pr-linter/exempt-readme

#24402 chore: reduce amount of throttling to CodeArtifact
  packages/@aws-cdk-testing/cli-integ/bin/stage-distribution.ts
  packages/aws-cdk/test/integ/test-cli-regression-against-current-code.sh
  packages/aws-cdk/test/integ/test-cli-regression-against-latest-release.sh
Labels: p2, contribution/core

#23926 feat(cli): update csharp & fsharp template to net6.0
  CONTRIBUTING.md
  README.md
  packages/aws-cdk/lib/init-templates/app/csharp/README.md
  packages/aws-cdk/lib/init-templates/app/csharp/src/%name.PascalCased%/%name.PascalCased%.template.csproj
  packages/aws-cdk/lib/init-templates/app/fsharp/src/%name.PascalCased%/%name.PascalCased%.template.fsproj
  packages/aws-cdk/lib/init-templates/sample-app/csharp/README.template.md
  packages/aws-cdk/lib/init-templates/sample-app/csharp/src/%name.PascalCased%/%name.PascalCased%.template.csproj
  packages/aws-cdk/lib/init-templates/sample-app/fsharp/README.template.md
  packages/aws-cdk/lib/init-templates/sample-app/fsharp/src/%name.PascalCased%/%name.PascalCased%.template.fsproj
  packages/aws-cdk/test/init.test.ts
  scripts/check-build-prerequisites.sh
  scripts/check-pack-prerequisites.sh
Labels: p2, feature-request, effort/small, pr-linter/exempt-integ-test, beginning-contributor, pr/needs-cli-test-run

#24393 fix(servicecatalog): wrong asset path is generated in case outdir is absolute
  packages/@aws-cdk/aws-servicecatalog/lib/private/product-stack-synthesizer.ts
  packages/@aws-cdk/aws-servicecatalog/test/product-stack.test.ts
Labels: bug, p2, pr-linter/exempt-integ-test, beginning-contributor

#24391 feat(remodel): generate new package for integ tests
  packages/@aws-cdk/custom-resources/lib/provider-framework/index.ts
  tools/@aws-cdk/remodel/lib/cli.ts
  tools/@aws-cdk/remodel/lib/template/packages/@aws-cdk-testing/framework-integ/.eslintrc.js
  tools/@aws-cdk/remodel/lib/template/packages/@aws-cdk-testing/framework-integ/.gitignore
  tools/@aws-cdk/remodel/lib/template/packages/@aws-cdk-testing/framework-integ/.npmignore
  tools/@aws-cdk/remodel/lib/template/packages/@aws-cdk-testing/framework-integ/LICENSE
  tools/@aws-cdk/remodel/lib/template/packages/@aws-cdk-testing/framework-integ/NOTICE
  tools/@aws-cdk/remodel/lib/template/packages/@aws-cdk-testing/framework-integ/package.json
  tools/@aws-cdk/remodel/lib/template/packages/@aws-cdk-testing/framework-integ/tsconfig.json
  tools/@aws-cdk/remodel/lib/template/packages/aws-cdk-lib/scripts/gen.ts
  tools/@aws-cdk/remodel/lib/util.ts
Labels: p2, contribution/core

#24409 fix(servicecatalogappregistry): applicationName can not be changed after deployment
  packages/@aws-cdk/aws-servicecatalogappregistry/lib/target-application.ts
  packages/@aws-cdk/aws-servicecatalogappregistry/test/integ.application.js.snapshot/cdk.out
  packages/@aws-cdk/aws-servicecatalogappregistry/test/integ.application.js.snapshot/integ-servicecatalogappregistry-application.assets.json
  packages/@aws-cdk/aws-servicecatalogappregistry/test/integ.application.js.snapshot/integ-servicecatalogappregistry-application.template.json
  packages/@aws-cdk/aws-servicecatalogappregistry/test/integ.application.js.snapshot/integ.json
  packages/@aws-cdk/aws-servicecatalogappregistry/test/integ.application.js.snapshot/manifest.json
  packages/@aws-cdk/aws-servicecatalogappregistry/test/integ.application.js.snapshot/tree.json
  packages/@aws-cdk/aws-servicecatalogappregistry/test/integ.application.ts
Labels: p2, repeat-contributor

#24421 chore(merge-back): 2.67.0
  CHANGELOG.v2.alpha.md
  CHANGELOG.v2.md
  packages/@aws-cdk/cx-api/FEATURE_FLAGS.md
  packages/@aws-cdk/cx-api/lib/features.ts
  version.v2.json
Labels: p2, pr/no-squash, auto-approve

#23871 fix(lambda-nodejs): esbuild preCompilation tsconfig precedence is wrong
  packages/@aws-cdk/aws-lambda-nodejs/lib/util.ts
  packages/@aws-cdk/aws-lambda-nodejs/test/testtsconfig-extended.json
  packages/@aws-cdk/aws-lambda-nodejs/test/util.test.ts
Labels: p2, pr-linter/exempt-integ-test, beginning-contributor

#24429 chore(merge-back): 1.195.0
  CHANGELOG.md
  version.v1.json
Labels: p2, pr/no-squash, auto-approve

#24426 chore(rds): RDS VersionUP follow-up in 2023.3
  packages/@aws-cdk/aws-rds/lib/cluster-engine.ts
  packages/@aws-cdk/aws-rds/lib/instance-engine.ts
Labels: p2, star-contributor

#24424 chore(config): AWS Config now supports 20 new resource types
  packages/@aws-cdk/aws-config/lib/rule.ts
Labels: p2, star-contributor

#24346 fix(apprunner-alpha): env vars and secrets can't solely be added via .add*() methods
  packages/@aws-cdk/aws-apprunner/lib/service.ts
  packages/@aws-cdk/aws-apprunner/test/integ.service-later-secrets-env-vars.js.snapshot/AppRunnerLaterSecretsEnvVarsDefaultTestDeployAssert07867A67.assets.json
  packages/@aws-cdk/aws-apprunner/test/integ.service-later-secrets-env-vars.js.snapshot/AppRunnerLaterSecretsEnvVarsDefaultTestDeployAssert07867A67.template.json
  packages/@aws-cdk/aws-apprunner/test/integ.service-later-secrets-env-vars.js.snapshot/cdk.out
  packages/@aws-cdk/aws-apprunner/test/integ.service-later-secrets-env-vars.js.snapshot/integ-apprunner-later-secrets-env-vars.assets.json
  packages/@aws-cdk/aws-apprunner/test/integ.service-later-secrets-env-vars.js.snapshot/integ-apprunner-later-secrets-env-vars.template.json
  packages/@aws-cdk/aws-apprunner/test/integ.service-later-secrets-env-vars.js.snapshot/integ.json
  packages/@aws-cdk/aws-apprunner/test/integ.service-later-secrets-env-vars.js.snapshot/manifest.json
  packages/@aws-cdk/aws-apprunner/test/integ.service-later-secrets-env-vars.js.snapshot/tree.json
  packages/@aws-cdk/aws-apprunner/test/integ.service-later-secrets-env-vars.ts
  packages/@aws-cdk/aws-apprunner/test/service.test.ts
Labels: bug, p2, effort/medium, repeat-contributor

#24340 refactor(apigateway): divide setupPermissions methods to small functions
  packages/@aws-cdk/aws-apigateway/lib/authorizers/lambda.ts
  packages/@aws-cdk/aws-iam/lib/role.ts
  packages/@aws-cdk/aws-iam/test/role.test.ts
Labels: p2, feature-request, repeat-contributor

#24446 chore: refactoring files to work with repo restructure
  packages/@aws-cdk/aws-apigateway/test/authorizers/integ.request-authorizer.lit.ts
  packages/@aws-cdk/aws-docdb/test/integ.cluster.ts
  packages/@aws-cdk/aws-iam/test/integ.managed-policy.ts
  packages/@aws-cdk/aws-iam/test/integ.policy.ts
  packages/@aws-cdk/aws-rds/test/snapshot-handler/index.ts
  packages/@aws-cdk/aws-stepfunctions-tasks/test/emrcontainers/integ.start-job-run.ts
  packages/@aws-cdk/aws-stepfunctions-tasks/test/sagemaker/integ.create-training-job.ts
  packages/@aws-cdk/pipelines/test/integ.pipeline-without-prepare.ts
Labels: p2, contribution/core

#24448 refactor(cloudfront): replace instanceOf into Role.isRole() methodd
  packages/@aws-cdk/aws-cloudfront/lib/experimental/edge-function.ts
  packages/@aws-cdk/aws-cloudfront/lib/private/cache-behavior.ts
  packages/@aws-cdk/aws-cloudfront/lib/web-distribution.ts
  packages/@aws-cdk/aws-codepipeline/lib/pipeline.ts
Labels: p2, feature-request, repeat-contributor

#24378 fix(servicecatalogappregistry): Associate an application with attribute group
  packages/@aws-cdk/aws-servicecatalogappregistry/README.md
  packages/@aws-cdk/aws-servicecatalogappregistry/lib/application.ts
  packages/@aws-cdk/aws-servicecatalogappregistry/lib/attribute-group.ts
  packages/@aws-cdk/aws-servicecatalogappregistry/test/application-associator.test.ts
  packages/@aws-cdk/aws-servicecatalogappregistry/test/attribute-group.test.ts
  packages/@aws-cdk/aws-servicecatalogappregistry/test/integ.application.js.snapshot/integ-servicecatalogappregistry-application.assets.json
  packages/@aws-cdk/aws-servicecatalogappregistry/test/integ.application.js.snapshot/integ-servicecatalogappregistry-application.template.json
  packages/@aws-cdk/aws-servicecatalogappregistry/test/integ.application.js.snapshot/manifest.json
  packages/@aws-cdk/aws-servicecatalogappregistry/test/integ.application.js.snapshot/tree.json
  packages/@aws-cdk/aws-servicecatalogappregistry/test/integ.application.ts
  packages/@aws-cdk/aws-servicecatalogappregistry/test/integ.attribute-group.js.snapshot/cdk.out
  packages/@aws-cdk/aws-servicecatalogappregistry/test/integ.attribute-group.js.snapshot/integ-servicecatalogappregistry-attribute-group.assets.json
  packages/@aws-cdk/aws-servicecatalogappregistry/test/integ.attribute-group.js.snapshot/integ-servicecatalogappregistry-attribute-group.template.json
  packages/@aws-cdk/aws-servicecatalogappregistry/test/integ.attribute-group.js.snapshot/integ.json
  packages/@aws-cdk/aws-servicecatalogappregistry/test/integ.attribute-group.js.snapshot/manifest.json
  packages/@aws-cdk/aws-servicecatalogappregistry/test/integ.attribute-group.js.snapshot/tree.json
  packages/@aws-cdk/aws-servicecatalogappregistry/test/integ.attribute-group.ts
Labels: p2, repeat-contributor

#24439 fix(cli): cannot `cdk import` resources with multiple identifiers
  packages/aws-cdk/lib/import.ts
  packages/aws-cdk/test/import.test.ts
Labels: bug, p2, contribution/core, pr-linter/exempt-integ-test, pr-linter/cli-integ-tested

#24406 fix(lambda-nodejs): Required auto prefix of `handler` with `index.` breaks custom non-`index` handler settings used by layers
  packages/@aws-cdk/aws-lambda-nodejs/README.md
  packages/@aws-cdk/aws-lambda-nodejs/lib/function.ts
  packages/@aws-cdk/aws-lambda-nodejs/test/function.test.ts
  packages/@aws-cdk/aws-lambda-nodejs/test/integ-handlers/ts-web-handler.ts
  packages/@aws-cdk/aws-lambda-nodejs/test/integ-handlers/ts-web-run.sh
  packages/@aws-cdk/aws-lambda-nodejs/test/integ.function.js.snapshot/asset.a33898f49e24c41ff9be236439c418d30e576c5f57763097162d9ec4245216ce/index.js
  packages/@aws-cdk/aws-lambda-nodejs/test/integ.function.js.snapshot/asset.a33898f49e24c41ff9be236439c418d30e576c5f57763097162d9ec4245216ce/index.js.map
  packages/@aws-cdk/aws-lambda-nodejs/test/integ.function.js.snapshot/asset.a33898f49e24c41ff9be236439c418d30e576c5f57763097162d9ec4245216ce/ts-web-run.sh
  packages/@aws-cdk/aws-lambda-nodejs/test/integ.function.js.snapshot/cdk-integ-lambda-nodejs.assets.json
  packages/@aws-cdk/aws-lambda-nodejs/test/integ.function.js.snapshot/cdk-integ-lambda-nodejs.template.json
  packages/@aws-cdk/aws-lambda-nodejs/test/integ.function.js.snapshot/cdk.out
  packages/@aws-cdk/aws-lambda-nodejs/test/integ.function.js.snapshot/integ.json
  packages/@aws-cdk/aws-lambda-nodejs/test/integ.function.js.snapshot/manifest.json
  packages/@aws-cdk/aws-lambda-nodejs/test/integ.function.js.snapshot/tree.json
  packages/@aws-cdk/aws-lambda-nodejs/test/integ.function.ts
Labels: bug, p2, beginning-contributor

#23605 fix(rds): add clusterResourceIdentifier property to database cluster
  packages/@aws-cdk/aws-rds/lib/cluster-ref.ts
  packages/@aws-cdk/aws-rds/lib/cluster.ts
  packages/@aws-cdk/aws-rds/test/cluster.test.ts
  packages/@aws-cdk/aws-rds/test/integ.cluster.js.snapshot/aws-cdk-rds-integ.assets.json
  packages/@aws-cdk/aws-rds/test/integ.cluster.js.snapshot/aws-cdk-rds-integ.template.json
  packages/@aws-cdk/aws-rds/test/integ.cluster.js.snapshot/cdk.out
  packages/@aws-cdk/aws-rds/test/integ.cluster.js.snapshot/integ.json
  packages/@aws-cdk/aws-rds/test/integ.cluster.js.snapshot/manifest.json
  packages/@aws-cdk/aws-rds/test/integ.cluster.js.snapshot/tree.json
  packages/@aws-cdk/aws-rds/test/integ.cluster.ts
Labels: p2, beginning-contributor

#24455 refactor(ecs): replace instanceOf into Cluster.isCluster() method
  packages/@aws-cdk/aws-ecs/lib/cluster.ts
  packages/@aws-cdk/aws-ecs/test/cluster.test.ts
Labels: p2, feature-request, valued-contributor

#24467 fix(core): Fix dotnet version check to allow .NET 7.0
  scripts/check-build-prerequisites.sh
Labels: bug, p2, pr-linter/exempt-test, pr-linter/exempt-integ-test, valued-contributor

#24472 chore: fix go init template test to unblock v2 pipeline
  packages/@aws-cdk-testing/cli-integ/tests/init-go/init-go.integtest.ts
  packages/aws-cdk/lib/init-templates/sample-app/go/%name%_test.template.go
Labels: p2, contribution/core

#24496 chore(cli-integ): ResourcePool will not reacquire dead processes
  packages/@aws-cdk-testing/cli-integ/lib/resource-pool.ts
  packages/@aws-cdk-testing/cli-integ/lib/xpmutex.ts
  packages/@aws-cdk-testing/cli-integ/test/xpmutex.test.ts
Labels: p2, contribution/core

#24499 chore: add extra output in CLI integ tests
  packages/@aws-cdk-testing/cli-integ/lib/integ-test.ts
Labels: p2, contribution/core

#24497 chore: npm-check-updates && yarn upgrade
  package.json
  packages/@aws-cdk-testing/cli-integ/package.json
  packages/@aws-cdk/aws-amplify/package.json
  packages/@aws-cdk/aws-certificatemanager/lambda-packages/dns_validated_certificate_handler/package.json
  packages/@aws-cdk/aws-cloudfront-origins/package.json
  packages/@aws-cdk/aws-cloudfront/package.json
  packages/@aws-cdk/aws-cloudtrail/package.json
  packages/@aws-cdk/aws-codebuild/package.json
  packages/@aws-cdk/aws-codecommit/package.json
  packages/@aws-cdk/aws-dynamodb/package.json
  packages/@aws-cdk/aws-eks/package.json
  packages/@aws-cdk/aws-eks/test/sdk-call-integ-test-docker-app/app/package.json
  packages/@aws-cdk/aws-events-targets/package.json
  packages/@aws-cdk/aws-globalaccelerator-endpoints/package.json
  packages/@aws-cdk/aws-lambda-nodejs/package.json
  packages/@aws-cdk/aws-logs/package.json
  packages/@aws-cdk/aws-redshift/package.json
  packages/@aws-cdk/aws-route53/package.json
  packages/@aws-cdk/aws-sqs/package.json
  packages/@aws-cdk/core/package.json
  packages/@aws-cdk/custom-resources/package.json
  packages/@aws-cdk/integ-runner/THIRD_PARTY_LICENSES
  packages/@aws-cdk/integ-tests/package.json
  packages/@aws-cdk/lambda-layer-awscli/package.json
  packages/@aws-cdk/lambda-layer-node-proxy-agent/package.json
  packages/@aws-cdk/pipelines/package.json
  packages/@aws-cdk/triggers/package.json
  packages/aws-cdk-lib/package.json
  packages/aws-cdk/THIRD_PARTY_LICENSES
  packages/aws-cdk/lib/init-templates/app/javascript/package.json
  packages/aws-cdk/lib/init-templates/app/typescript/package.json
  packages/aws-cdk/lib/init-templates/lib/typescript/package.json
  packages/aws-cdk/lib/init-templates/sample-app/javascript/package.json
  packages/aws-cdk/lib/init-templates/sample-app/typescript/package.json
  packages/aws-cdk/package.json
  packages/awslint/package.json
  packages/cdk-assets/package.json
  packages/cdk-dasm/package.json
  tools/@aws-cdk/cdk-build-tools/package.json
  tools/@aws-cdk/cfn2ts/package.json
  tools/@aws-cdk/node-bundle/package.json
  yarn.lock
Labels: p2, dependencies, contribution/core, auto-approve

#24440 feat(msk): add Kafka version 3.3.2
  packages/@aws-cdk/aws-msk/lib/cluster-version.ts
  packages/@aws-cdk/aws-msk/test/cluster.test.ts
  packages/@aws-cdk/aws-msk/test/integ.cluster.js.snapshot/MskLoggingDefaultTestDeployAssertC2F074AF.assets.json
  packages/@aws-cdk/aws-msk/test/integ.cluster.js.snapshot/MskLoggingDefaultTestDeployAssertC2F074AF.template.json
  packages/@aws-cdk/aws-msk/test/integ.cluster.js.snapshot/asset.73c20a669c041469f7fc3fc03d574b093b5b97e7c716f76c1e8117e6163e4dc4.bundle/index.js
  packages/@aws-cdk/aws-msk/test/integ.cluster.js.snapshot/asset.a268caa53756f51bda8ad5f499be4ed8484a81b314811806fbb66f874837c476/index.js
  packages/@aws-cdk/aws-msk/test/integ.cluster.js.snapshot/aws-cdk-msk-integ.assets.json
  packages/@aws-cdk/aws-msk/test/integ.cluster.js.snapshot/aws-cdk-msk-integ.template.json
  packages/@aws-cdk/aws-msk/test/integ.cluster.js.snapshot/cdk.out
  packages/@aws-cdk/aws-msk/test/integ.cluster.js.snapshot/integ.json
  packages/@aws-cdk/aws-msk/test/integ.cluster.js.snapshot/manifest.json
  packages/@aws-cdk/aws-msk/test/integ.cluster.js.snapshot/tree.json
  packages/@aws-cdk/aws-msk/test/integ.cluster.ts
Labels: p2, feature-request, pr-linter/exempt-readme, beginning-contributor

#24504 chore(cli-integ): add per-test timeouts
  packages/@aws-cdk-testing/cli-integ/lib/resource-pool.ts
  packages/@aws-cdk-testing/cli-integ/lib/with-cdk-app.ts
  packages/@aws-cdk-testing/cli-integ/lib/with-sam.ts
  packages/@aws-cdk-testing/cli-integ/lib/with-timeout.ts
  packages/@aws-cdk-testing/cli-integ/test/resource-pool.test.ts
Labels: p2, contribution/core

#24508 chore: remove parentheses in 'sam local start-api' filter
  packages/@aws-cdk-testing/cli-integ/lib/with-sam.ts
Labels: p2, contribution/core

#24521 chore(merge-back): 2.68.0
  CHANGELOG.v2.alpha.md
  CHANGELOG.v2.md
  packages/@aws-cdk/cx-api/FEATURE_FLAGS.md
  packages/@aws-cdk/cx-api/lib/features.ts
  version.v2.json
Labels: p2, pr/no-squash, auto-approve

#24524 fix(ecr-assets): prefix cache arguments correctly
  packages/cdk-assets/lib/private/docker.ts
  packages/cdk-assets/test/docker-images.test.ts
Labels: p2, pr-linter/exempt-integ-test, repeat-contributor

#24442 feat(kinesisanalytics-flink): VPC support for Flink applications
  packages/@aws-cdk/aws-kinesisanalytics-flink/README.md
  packages/@aws-cdk/aws-kinesisanalytics-flink/lib/application.ts
  packages/@aws-cdk/aws-kinesisanalytics-flink/lib/private/validation.ts
  packages/@aws-cdk/aws-kinesisanalytics-flink/package.json
  packages/@aws-cdk/aws-kinesisanalytics-flink/rosetta/default.ts-fixture
  packages/@aws-cdk/aws-kinesisanalytics-flink/test/application.test.ts
  packages/@aws-cdk/aws-kinesisanalytics-flink/test/integ.vpc-application.js.snapshot/FlinkAppTest.assets.json
  packages/@aws-cdk/aws-kinesisanalytics-flink/test/integ.vpc-application.js.snapshot/FlinkAppTest.template.json
  packages/@aws-cdk/aws-kinesisanalytics-flink/test/integ.vpc-application.js.snapshot/VpcTestDefaultTestDeployAssert06A9965C.assets.json
  packages/@aws-cdk/aws-kinesisanalytics-flink/test/integ.vpc-application.js.snapshot/VpcTestDefaultTestDeployAssert06A9965C.template.json
  packages/@aws-cdk/aws-kinesisanalytics-flink/test/integ.vpc-application.js.snapshot/asset.8be9e0b5f53d41e9a3b1d51c9572c65f24f8170a7188d0ed57fb7d571de4d577/WordCount.jar
  packages/@aws-cdk/aws-kinesisanalytics-flink/test/integ.vpc-application.js.snapshot/cdk.out
  packages/@aws-cdk/aws-kinesisanalytics-flink/test/integ.vpc-application.js.snapshot/integ.json
  packages/@aws-cdk/aws-kinesisanalytics-flink/test/integ.vpc-application.js.snapshot/manifest.json
  packages/@aws-cdk/aws-kinesisanalytics-flink/test/integ.vpc-application.js.snapshot/tree.json
  packages/@aws-cdk/aws-kinesisanalytics-flink/test/integ.vpc-application.ts
Labels: p1, feature-request, effort/medium, valued-contributor

#24526 chore(merge-back): 1.196.0
  CHANGELOG.md
  version.v1.json
Labels: p2, pr/no-squash, auto-approve

#24039 feat(docdb): added ability to enable performance insights
  packages/@aws-cdk/aws-docdb/README.md
  packages/@aws-cdk/aws-docdb/lib/cluster.ts
  packages/@aws-cdk/aws-docdb/lib/instance.ts
  packages/@aws-cdk/aws-docdb/test/cluster.test.ts
  packages/@aws-cdk/aws-docdb/test/instance.test.ts
  packages/@aws-cdk/aws-docdb/test/integ.cluster.js.snapshot/aws-cdk-docdb-integ.assets.json
  packages/@aws-cdk/aws-docdb/test/integ.cluster.js.snapshot/aws-cdk-docdb-integ.template.json
  packages/@aws-cdk/aws-docdb/test/integ.cluster.js.snapshot/cdk.out
  packages/@aws-cdk/aws-docdb/test/integ.cluster.js.snapshot/integ.json
  packages/@aws-cdk/aws-docdb/test/integ.cluster.js.snapshot/manifest.json
  packages/@aws-cdk/aws-docdb/test/integ.cluster.js.snapshot/tree.json
  packages/@aws-cdk/aws-docdb/test/integ.cluster.ts
Labels: p2, feature-request, beginning-contributor

#24194 feat(custom-resources): AwsCustomResource copy physicalResourceId from request when omit it in onUpdate
  packages/@aws-cdk/custom-resources/README.md
  packages/@aws-cdk/custom-resources/lib/aws-custom-resource/aws-custom-resource.ts
  packages/@aws-cdk/custom-resources/test/aws-custom-resource/aws-custom-resource.test.ts
  packages/@aws-cdk/custom-resources/test/aws-custom-resource/integ.aws-custom-resource-athena.js.snapshot/CustomResourceAthenaDefaultTestDeployAssert7AE6A475.assets.json
  packages/@aws-cdk/custom-resources/test/aws-custom-resource/integ.aws-custom-resource-athena.js.snapshot/CustomResourceAthenaDefaultTestDeployAssert7AE6A475.template.json
  packages/@aws-cdk/custom-resources/test/aws-custom-resource/integ.aws-custom-resource-athena.js.snapshot/asset.a268caa53756f51bda8ad5f499be4ed8484a81b314811806fbb66f874837c476/index.js
  packages/@aws-cdk/custom-resources/test/aws-custom-resource/integ.aws-custom-resource-athena.js.snapshot/aws-cdk-customresources-athena.assets.json
  packages/@aws-cdk/custom-resources/test/aws-custom-resource/integ.aws-custom-resource-athena.js.snapshot/aws-cdk-customresources-athena.template.json
  packages/@aws-cdk/custom-resources/test/aws-custom-resource/integ.aws-custom-resource-athena.js.snapshot/cdk.out
  packages/@aws-cdk/custom-resources/test/aws-custom-resource/integ.aws-custom-resource-athena.js.snapshot/integ.json
  packages/@aws-cdk/custom-resources/test/aws-custom-resource/integ.aws-custom-resource-athena.js.snapshot/manifest.json
  packages/@aws-cdk/custom-resources/test/aws-custom-resource/integ.aws-custom-resource-athena.js.snapshot/tree.json
  packages/@aws-cdk/custom-resources/test/aws-custom-resource/integ.aws-custom-resource-athena.ts
Labels: p2, feature-request, effort/medium, beginning-contributor

#24452 docs(codepipeline): Replaces old link to CodePipeline docs with new one
  packages/@aws-cdk/aws-codepipeline-actions/README.md
Labels: p2, effort/small, admired-contributor

#24463 feat(rds): PostgreSQL engine version 15.2
  packages/@aws-cdk/aws-rds/lib/instance-engine.ts
Labels: p2, feature-request, effort/small, pr-linter/exempt-readme, pr-linter/exempt-test, pr-linter/exempt-integ-test, beginning-contributor

#24532 chore(assert): remove packages never in v2
  .github/workflows/issue-label-assign.yml
  packages/@aws-cdk/assert-internal/.eslintrc.js
  packages/@aws-cdk/assert-internal/.gitignore
  packages/@aws-cdk/assert-internal/.npmignore
  packages/@aws-cdk/assert-internal/LICENSE
  packages/@aws-cdk/assert-internal/NOTICE
  packages/@aws-cdk/assert-internal/README.md
  packages/@aws-cdk/assert-internal/jest.config.js
  packages/@aws-cdk/assert-internal/jest.ts
  packages/@aws-cdk/assert-internal/lib/assertion.ts
  packages/@aws-cdk/assert-internal/lib/assertions/and-assertion.ts
  packages/@aws-cdk/assert-internal/lib/assertions/count-resources.ts
  packages/@aws-cdk/assert-internal/lib/assertions/exist.ts
  packages/@aws-cdk/assert-internal/lib/assertions/have-output.ts
  packages/@aws-cdk/assert-internal/lib/assertions/have-resource-matchers.ts
  packages/@aws-cdk/assert-internal/lib/assertions/have-resource.ts
  packages/@aws-cdk/assert-internal/lib/assertions/have-type.ts
  packages/@aws-cdk/assert-internal/lib/assertions/match-template.ts
  packages/@aws-cdk/assert-internal/lib/assertions/negated-assertion.ts
  packages/@aws-cdk/assert-internal/lib/canonicalize-assets.ts
  packages/@aws-cdk/assert-internal/lib/expect.ts
  packages/@aws-cdk/assert-internal/lib/index.ts
  packages/@aws-cdk/assert-internal/lib/inspector.ts
  packages/@aws-cdk/assert-internal/lib/synth-utils.ts
  packages/@aws-cdk/assert-internal/package.json
  packages/@aws-cdk/assert-internal/test/assertions.test.ts
  packages/@aws-cdk/assert-internal/test/canonicalize-assets.test.ts
  packages/@aws-cdk/assert-internal/test/cloud-artifact.ts
  packages/@aws-cdk/assert-internal/test/have-output.test.ts
  packages/@aws-cdk/assert-internal/test/have-resource.test.ts
  packages/@aws-cdk/assert-internal/test/match-template.test.ts
  packages/@aws-cdk/assert-internal/test/synth-utils.test.ts
  packages/@aws-cdk/assert-internal/tsconfig.json
  packages/@aws-cdk/assert/.eslintrc.js
  packages/@aws-cdk/assert/.gitignore
  packages/@aws-cdk/assert/.npmignore
  packages/@aws-cdk/assert/BUILD.md
  packages/@aws-cdk/assert/LICENSE
  packages/@aws-cdk/assert/NOTICE
  packages/@aws-cdk/assert/clone.sh
  packages/@aws-cdk/assert/jest.config.js
  packages/@aws-cdk/assert/package.json
  packages/@aws-cdk/assert/tsconfig.json
  packages/@aws-cdk/pipelines/test/testhelpers/matchers.ts
  packages/aws-cdk-migration/lib/rewrite.ts
  packages/aws-cdk-migration/test/rewrite.test.ts
  tools/@aws-cdk/eslint-plugin/lib/rules/invalid-cfn-imports.ts
  tools/@aws-cdk/individual-pkg-gen/transform-packages.ts
  tools/@aws-cdk/pkglint/lib/rules.ts
  tools/@aws-cdk/prlint/test/module.test.ts
Labels: p2, contribution/core

#24539 feat(rds): add support for minor versions of PostgreSQL: 14.7, 13.10, 12.14, and 11.19
  packages/@aws-cdk/aws-rds/lib/instance-engine.ts
Labels: p2, pr-linter/exempt-readme, pr-linter/exempt-test, pr-linter/exempt-integ-test, distinguished-contributor

#24593 fix(sfn): can't override toStateJson() from other languages
  packages/@aws-cdk/aws-stepfunctions/lib/fields.ts
  packages/@aws-cdk/aws-stepfunctions/lib/states/state.ts
  packages/@aws-cdk/aws-stepfunctions/test/state.test.ts
  packages/@aws-cdk/core/lib/token.ts
Labels: bug, p2, contribution/core, pr-linter/exempt-integ-test

#24605 chore: make some tests less directory dependent
  packages/@aws-cdk/aws-ecr-assets/test/tarball-asset.test.ts
  packages/@aws-cdk/aws-lambda-go/test/docker.test.ts
  packages/@aws-cdk/aws-lambda-go/test/function.test.ts
  packages/@aws-cdk/aws-lambda-nodejs/test/bundling.test.ts
  packages/@aws-cdk/aws-lambda-nodejs/test/docker.test.ts
  packages/@aws-cdk/aws-lambda-python/test/function.test.ts
  packages/@aws-cdk/aws-lambda/test/function.test.ts
  packages/@aws-cdk/core/test/runtime-info.test.ts
Labels: p2, contribution/core

#24613 chore(cdk-assets): disable JS SDKv2 warning message
  packages/cdk-assets/lib/aws.ts
Labels: p2, contribution/core

#24596 chore: improve error reporting for asset staging
  packages/@aws-cdk/core/lib/private/asset-staging.ts
  packages/@aws-cdk/core/test/bundling.test.ts
  packages/@aws-cdk/core/test/private/asset-staging.test.ts
Labels: p2, contribution/core

#24619 chore(merge-back): 2.69.0
  CHANGELOG.v2.alpha.md
  CHANGELOG.v2.md
  version.v2.json
Labels: p2, pr/no-squash, auto-approve

#24623 chore(merge-back): 1.197.0
  CHANGELOG.md
  version.v1.json
Labels: p2, pr/no-squash, auto-approve

#24408 feat(servicecatalogappregistry-alpha): Introduce flag to control application sharing and association behavior for cross-account stacks
  packages/@aws-cdk/aws-servicecatalogappregistry/README.md
  packages/@aws-cdk/aws-servicecatalogappregistry/lib/application-associator.ts
  packages/@aws-cdk/aws-servicecatalogappregistry/lib/application.ts
  packages/@aws-cdk/aws-servicecatalogappregistry/lib/aspects/stack-associator.ts
  packages/@aws-cdk/aws-servicecatalogappregistry/lib/target-application.ts
  packages/@aws-cdk/aws-servicecatalogappregistry/test/application-associator.test.ts
  packages/@aws-cdk/aws-servicecatalogappregistry/test/integ.application-associator.cross-account-stack-association-enabled.js.snapshot/ApplicationAssociatorTestDefaultTestDeployAssert2A5F2DB9.assets.json
  packages/@aws-cdk/aws-servicecatalogappregistry/test/integ.application-associator.cross-account-stack-association-enabled.js.snapshot/ApplicationAssociatorTestDefaultTestDeployAssert2A5F2DB9.template.json
  packages/@aws-cdk/aws-servicecatalogappregistry/test/integ.application-associator.cross-account-stack-association-enabled.js.snapshot/TestAppRegistryApplicationStack.assets.json
  packages/@aws-cdk/aws-servicecatalogappregistry/test/integ.application-associator.cross-account-stack-association-enabled.js.snapshot/TestAppRegistryApplicationStack.template.json
  packages/@aws-cdk/aws-servicecatalogappregistry/test/integ.application-associator.cross-account-stack-association-enabled.js.snapshot/cdk.out
  packages/@aws-cdk/aws-servicecatalogappregistry/test/integ.application-associator.cross-account-stack-association-enabled.js.snapshot/integ-servicecatalogappregistry-cross-account-resource.assets.json
  packages/@aws-cdk/aws-servicecatalogappregistry/test/integ.application-associator.cross-account-stack-association-enabled.js.snapshot/integ-servicecatalogappregistry-cross-account-resource.template.json
  packages/@aws-cdk/aws-servicecatalogappregistry/test/integ.application-associator.cross-account-stack-association-enabled.js.snapshot/integ-servicecatalogappregistry-local-resource.assets.json
  packages/@aws-cdk/aws-servicecatalogappregistry/test/integ.application-associator.cross-account-stack-association-enabled.js.snapshot/integ-servicecatalogappregistry-local-resource.template.json
  packages/@aws-cdk/aws-servicecatalogappregistry/test/integ.application-associator.cross-account-stack-association-enabled.js.snapshot/integ.json
  packages/@aws-cdk/aws-servicecatalogappregistry/test/integ.application-associator.cross-account-stack-association-enabled.js.snapshot/manifest.json
  packages/@aws-cdk/aws-servicecatalogappregistry/test/integ.application-associator.cross-account-stack-association-enabled.js.snapshot/tree.json
  packages/@aws-cdk/aws-servicecatalogappregistry/test/integ.application-associator.cross-account-stack-association-enabled.ts
Labels: p2, beginning-contributor

#24646 docs(lambda-python): add troubleshooting for Finch
  packages/@aws-cdk/aws-lambda-python/README.md
Labels: bug, p2, contribution/core

#24653 chore(stepfunctions): remove integ dependency
  packages/@aws-cdk/aws-stepfunctions/test/fake-task.ts
  packages/@aws-cdk/aws-stepfunctions/test/integ.state-machine-credentials.ts
  packages/@aws-cdk/aws-stepfunctions/test/state.test.ts
Labels: p2, contribution/core

#24353 feat(elasticloadbalancing): classic load balancer supports ec2 instances
  packages/@aws-cdk/aws-elasticloadbalancing/README.md
  packages/@aws-cdk/aws-elasticloadbalancing/lib/load-balancer.ts
  packages/@aws-cdk/aws-elasticloadbalancing/package.json
  packages/@aws-cdk/aws-elasticloadbalancing/test/integ.instanceTarget.elb.js.snapshot/InstanceTargetTestDefaultTestDeployAssertAF607556.assets.json
  packages/@aws-cdk/aws-elasticloadbalancing/test/integ.instanceTarget.elb.js.snapshot/InstanceTargetTestDefaultTestDeployAssertAF607556.template.json
  packages/@aws-cdk/aws-elasticloadbalancing/test/integ.instanceTarget.elb.js.snapshot/aws-cdk-elb-instance-target-integ.assets.json
  packages/@aws-cdk/aws-elasticloadbalancing/test/integ.instanceTarget.elb.js.snapshot/aws-cdk-elb-instance-target-integ.template.json
  packages/@aws-cdk/aws-elasticloadbalancing/test/integ.instanceTarget.elb.js.snapshot/cdk.out
  packages/@aws-cdk/aws-elasticloadbalancing/test/integ.instanceTarget.elb.js.snapshot/integ.json
  packages/@aws-cdk/aws-elasticloadbalancing/test/integ.instanceTarget.elb.js.snapshot/manifest.json
  packages/@aws-cdk/aws-elasticloadbalancing/test/integ.instanceTarget.elb.js.snapshot/tree.json
  packages/@aws-cdk/aws-elasticloadbalancing/test/integ.instanceTarget.elb.ts
  packages/@aws-cdk/aws-elasticloadbalancing/test/loadbalancer.test.ts
Labels: p2, feature-request, effort/small, contribution/core

#24664 chore(logs): add new supported value of 3 years
  packages/@aws-cdk/aws-logs/lib/log-group.ts
Labels: p2, contribution/core

#24663 fix(cli): user agent is reported as `undefined/undefined`
  packages/aws-cdk/lib/api/aws-auth/sdk-provider.ts
  packages/aws-cdk/lib/util/directories.ts
  packages/aws-cdk/test/api/sdk-provider.test.ts
Labels: p2, contribution/core, pr-linter/exempt-integ-test, pr-linter/cli-integ-tested

#24665 chore(cli-integ): retry throttled Maven uploads
  packages/@aws-cdk-testing/cli-integ/lib/staging/maven.ts
Labels: p2, contribution/core

#24651 fix(WAFv2): add patch to revert struct names
  packages/@aws-cdk/cfnspec/spec-source/specification/000_cfn/500_Revert_To_Json_Types_patch.json
  packages/@aws-cdk/cfnspec/spec-source/specification/000_cfn/500_WAFv2_RuleGroup_Rename_Properties_patch.json
Labels: p2, contribution/core, pr-linter/exempt-test, pr-linter/exempt-integ-test

#24602 fix(cli): no change deployment prints "hotswap deployment skipped" without hotswap flag
  packages/aws-cdk/lib/api/deploy-stack.ts
Labels: p2, contribution/core, pr-linter/exempt-test, pr-linter/exempt-integ-test, pr-linter/cli-integ-tested

#24649 chore: Minor updates for the used deployment methods
  packages/aws-cdk/lib/cdk-toolkit.ts
  packages/aws-cdk/lib/cli.ts
  packages/aws-cdk/lib/import.ts
Labels: p2, contribution/core, pr-linter/cli-integ-tested

#24673 feat(ec2): SSM sessions
  packages/@aws-cdk/aws-autoscaling/README.md
  packages/@aws-cdk/aws-autoscaling/lib/auto-scaling-group.ts
  packages/@aws-cdk/aws-autoscaling/test/auto-scaling-group.test.ts
  packages/@aws-cdk/aws-ec2/README.md
  packages/@aws-cdk/aws-ec2/lib/instance.ts
  packages/@aws-cdk/aws-ec2/lib/machine-image.ts
  packages/@aws-cdk/aws-ec2/test/instance.test.ts
Labels: p2, contribution/core, pr-linter/exempt-integ-test

#24702 fix(toolkit): RWLock.acquireRead is not re-entrant
  packages/aws-cdk/lib/api/util/rwlock.ts
Labels: p2, contribution/core, pr-linter/exempt-test, pr-linter/exempt-integ-test, pr-linter/cli-integ-tested

#24703 fix(WAFv2): add patch to revert struct names
  packages/@aws-cdk/cfnspec/spec-source/specification/000_cfn/500_Revert_To_Json_Types_patch.json
  packages/@aws-cdk/cfnspec/spec-source/specification/000_cfn/500_WAFv2_RuleGroup_Rename_Properties_patch.json
Labels: p2, contribution/core, pr-linter/exempt-test, pr-linter/exemption-requested

#24683 feat(ec2): CFN-init support for systemd
  packages/@aws-cdk/aws-ec2/README.md
  packages/@aws-cdk/aws-ec2/lib/cfn-init-elements.ts
  packages/@aws-cdk/aws-ec2/test/cfn-init-element.test.ts
  packages/@aws-cdk/aws-elasticloadbalancing/package.json
  packages/@aws-cdk/aws-elasticloadbalancing/test/integ.instanceTarget.elb.js.snapshot/InstanceTargetTestDefaultTestDeployAssertAF607556.assets.json
  packages/@aws-cdk/aws-elasticloadbalancing/test/integ.instanceTarget.elb.js.snapshot/aws-cdk-elb-instance-target-integ.assets.json
  packages/@aws-cdk/aws-elasticloadbalancing/test/integ.instanceTarget.elb.js.snapshot/aws-cdk-elb-instance-target-integ.template.json
  packages/@aws-cdk/aws-elasticloadbalancing/test/integ.instanceTarget.elb.js.snapshot/cdk.out
  packages/@aws-cdk/aws-elasticloadbalancing/test/integ.instanceTarget.elb.js.snapshot/integ.json
  packages/@aws-cdk/aws-elasticloadbalancing/test/integ.instanceTarget.elb.js.snapshot/manifest.json
  packages/@aws-cdk/aws-elasticloadbalancing/test/integ.instanceTarget.elb.js.snapshot/tree.json
  packages/@aws-cdk/aws-elasticloadbalancing/test/integ.instanceTarget.elb.ts
Labels: p2, contribution/core, pr-linter/exempt-integ-test

#24718 chore: detect property type renames to protect against breakage
  packages/@aws-cdk/cfnspec/build-tools/spec-diff.ts
  packages/@aws-cdk/cfnspec/build-tools/update.sh
  packages/@aws-cdk/cfnspec/spec-source/specification/000_cfn/500_WAFv2_RuleGroup_Rename_Properties_patch.json
Labels: p2, contribution/core

#24719 chore(integ-runner): tag should be `latest-1` for v1
  packages/@aws-cdk/integ-runner/package.json
  tools/@aws-cdk/pkglint/lib/rules.ts
Labels: bug, p1, effort/small, contribution/core

#24717 fix(sfn): stop replacing JsonPath.DISCARD with `null`
  packages/@aws-cdk/aws-stepfunctions/lib/states/state.ts
  packages/@aws-cdk/aws-stepfunctions/test/state.test.ts
  packages/@aws-cdk/core/lib/private/cloudformation-lang.ts
  packages/@aws-cdk/core/lib/private/resolve.ts
  packages/@aws-cdk/core/lib/token.ts
Labels: p2, contribution/core, pr-linter/exempt-test, pr-linter/exempt-integ-test

#24688 fix(eks): fail to update cluster by disabling logging props
  packages/@aws-cdk/aws-eks/lib/cluster-resource-handler/cluster.ts
  packages/@aws-cdk/aws-eks/lib/cluster-resource-handler/compareLogging.ts
  packages/@aws-cdk/aws-eks/test/compareLog.test.ts
Labels: bug, p1, effort/small, contribution/core, pr-linter/exempt-integ-test

#24707 feat(cloudwatch): added defaultInterval prop to cw-dashboard
  packages/@aws-cdk/aws-cloudwatch/README.md
  packages/@aws-cdk/aws-cloudwatch/lib/dashboard.ts
  packages/@aws-cdk/aws-cloudwatch/test/dashboard.test.ts
  packages/@aws-cdk/aws-cloudwatch/test/integ.dashboard.js.snapshot/DashboardIntegrationTestDefaultTestDeployAssert5BE38902.assets.json
  packages/@aws-cdk/aws-cloudwatch/test/integ.dashboard.js.snapshot/DashboardIntegrationTestStack.assets.json
  packages/@aws-cdk/aws-cloudwatch/test/integ.dashboard.js.snapshot/DashboardIntegrationTestStack.template.json
  packages/@aws-cdk/aws-cloudwatch/test/integ.dashboard.js.snapshot/cdk.out
  packages/@aws-cdk/aws-cloudwatch/test/integ.dashboard.js.snapshot/integ.json
  packages/@aws-cdk/aws-cloudwatch/test/integ.dashboard.js.snapshot/manifest.json
  packages/@aws-cdk/aws-cloudwatch/test/integ.dashboard.js.snapshot/tree.json
  packages/@aws-cdk/aws-cloudwatch/test/integ.dashboard.ts
Labels: p2, contribution/core

#24572 feat(ecr): add option to auto delete images upon ECR repository removal
  packages/@aws-cdk/aws-ecr/README.md
  packages/@aws-cdk/aws-ecr/lib/auto-delete-images-handler/index.ts
  packages/@aws-cdk/aws-ecr/lib/repository.ts
  packages/@aws-cdk/aws-ecr/test/auto-delete-images-handler.test.ts
  packages/@aws-cdk/aws-ecr/test/integ.repository-auto-delete-images.js.snapshot/asset.6150227d515909a73f0bcde4b9e19b4b206cc65634027053380d700f6e53f08e/__entrypoint__.js
  packages/@aws-cdk/aws-ecr/test/integ.repository-auto-delete-images.js.snapshot/asset.6150227d515909a73f0bcde4b9e19b4b206cc65634027053380d700f6e53f08e/index.js
  packages/@aws-cdk/aws-ecr/test/integ.repository-auto-delete-images.js.snapshot/aws-ecr-integ-stack.assets.json
  packages/@aws-cdk/aws-ecr/test/integ.repository-auto-delete-images.js.snapshot/aws-ecr-integ-stack.template.json
  packages/@aws-cdk/aws-ecr/test/integ.repository-auto-delete-images.js.snapshot/cdk.out
  packages/@aws-cdk/aws-ecr/test/integ.repository-auto-delete-images.js.snapshot/cdkintegautodeleteimagesDefaultTestDeployAssert6B08011C.assets.json
  packages/@aws-cdk/aws-ecr/test/integ.repository-auto-delete-images.js.snapshot/cdkintegautodeleteimagesDefaultTestDeployAssert6B08011C.template.json
  packages/@aws-cdk/aws-ecr/test/integ.repository-auto-delete-images.js.snapshot/integ.json
  packages/@aws-cdk/aws-ecr/test/integ.repository-auto-delete-images.js.snapshot/manifest.json
  packages/@aws-cdk/aws-ecr/test/integ.repository-auto-delete-images.js.snapshot/tree.json
  packages/@aws-cdk/aws-ecr/test/integ.repository-auto-delete-images.ts
Labels: p2, beginning-contributor

#24672 feat(servicecatalogappregistry): add attribute groups to an application
  packages/@aws-cdk/aws-servicecatalogappregistry/README.md
  packages/@aws-cdk/aws-servicecatalogappregistry/lib/application-associator.ts
  packages/@aws-cdk/aws-servicecatalogappregistry/lib/application.ts
  packages/@aws-cdk/aws-servicecatalogappregistry/lib/aspects/stack-associator.ts
  packages/@aws-cdk/aws-servicecatalogappregistry/lib/target-application.ts
  packages/@aws-cdk/aws-servicecatalogappregistry/test/application-associator.test.ts
  packages/@aws-cdk/aws-servicecatalogappregistry/test/application.test.ts
  packages/@aws-cdk/aws-servicecatalogappregistry/test/integ.application.js.snapshot/cdk.out
  packages/@aws-cdk/aws-servicecatalogappregistry/test/integ.application.js.snapshot/integ-servicecatalogappregistry-application.assets.json
  packages/@aws-cdk/aws-servicecatalogappregistry/test/integ.application.js.snapshot/integ-servicecatalogappregistry-application.template.json
  packages/@aws-cdk/aws-servicecatalogappregistry/test/integ.application.js.snapshot/integ.json
  packages/@aws-cdk/aws-servicecatalogappregistry/test/integ.application.js.snapshot/manifest.json
  packages/@aws-cdk/aws-servicecatalogappregistry/test/integ.application.js.snapshot/tree.json
  packages/@aws-cdk/aws-servicecatalogappregistry/test/integ.application.ts
Labels: p2, beginning-contributor

#24706 fix(ivs): Not a standard physical name pattern
  packages/@aws-cdk/aws-ivs/lib/channel.ts
  packages/@aws-cdk/aws-ivs/lib/playback-key-pair.ts
  packages/@aws-cdk/aws-ivs/package.json
  packages/@aws-cdk/aws-ivs/test/integ.ivs.js.snapshot/aws-cdk-ivs.assets.json
  packages/@aws-cdk/aws-ivs/test/integ.ivs.js.snapshot/aws-cdk-ivs.template.json
  packages/@aws-cdk/aws-ivs/test/integ.ivs.js.snapshot/cdk.out
  packages/@aws-cdk/aws-ivs/test/integ.ivs.js.snapshot/integ.json
  packages/@aws-cdk/aws-ivs/test/integ.ivs.js.snapshot/ivstestDefaultTestDeployAssertDCE80D47.assets.json
  packages/@aws-cdk/aws-ivs/test/integ.ivs.js.snapshot/manifest.json
  packages/@aws-cdk/aws-ivs/test/integ.ivs.js.snapshot/tree.json
  packages/@aws-cdk/aws-ivs/test/integ.ivs.ts
  packages/@aws-cdk/aws-ivs/test/ivs.test.ts
Labels: p2, valued-contributor

#24612 feat(apprunner-alpha): support autoDeploymentsEnabled flag for Service
  packages/@aws-cdk/aws-apprunner/README.md
  packages/@aws-cdk/aws-apprunner/lib/service.ts
  packages/@aws-cdk/aws-apprunner/test/integ.service-ecr-public.js.snapshot/cdk.out
  packages/@aws-cdk/aws-apprunner/test/integ.service-ecr-public.js.snapshot/integ-apprunner-ecr-public.assets.json
  packages/@aws-cdk/aws-apprunner/test/integ.service-ecr-public.js.snapshot/integ-apprunner-ecr-public.template.json
  packages/@aws-cdk/aws-apprunner/test/integ.service-ecr-public.js.snapshot/integ.json
  packages/@aws-cdk/aws-apprunner/test/integ.service-ecr-public.js.snapshot/manifest.json
  packages/@aws-cdk/aws-apprunner/test/integ.service-ecr-public.js.snapshot/tree.json
  packages/@aws-cdk/aws-apprunner/test/integ.service-ecr-public.ts
  packages/@aws-cdk/aws-apprunner/test/integ.service-ecr.js.snapshot/cdk.out
  packages/@aws-cdk/aws-apprunner/test/integ.service-ecr.js.snapshot/integ-apprunner.assets.json
  packages/@aws-cdk/aws-apprunner/test/integ.service-ecr.js.snapshot/integ-apprunner.template.json
  packages/@aws-cdk/aws-apprunner/test/integ.service-ecr.js.snapshot/integ.json
  packages/@aws-cdk/aws-apprunner/test/integ.service-ecr.js.snapshot/manifest.json
  packages/@aws-cdk/aws-apprunner/test/integ.service-ecr.js.snapshot/tree.json
  packages/@aws-cdk/aws-apprunner/test/integ.service-ecr.ts
  packages/@aws-cdk/aws-apprunner/test/service.test.ts
Labels: p2, feature-request, effort/medium, beginning-contributor

#24581 feat(dynamodb): adds deletion protection for tables
  packages/@aws-cdk/aws-dynamodb/README.md
  packages/@aws-cdk/aws-dynamodb/lib/table.ts
  packages/@aws-cdk/aws-dynamodb/test/dynamodb.test.ts
  packages/@aws-cdk/aws-dynamodb/test/integ.dynamodb.deletion-protection.js.snapshot/cdk.out
  packages/@aws-cdk/aws-dynamodb/test/integ.dynamodb.deletion-protection.js.snapshot/deletion-protection-stack.assets.json
  packages/@aws-cdk/aws-dynamodb/test/integ.dynamodb.deletion-protection.js.snapshot/deletion-protection-stack.template.json
  packages/@aws-cdk/aws-dynamodb/test/integ.dynamodb.deletion-protection.js.snapshot/deletionprotectionintegtestDefaultTestDeployAssertA66823A5.assets.json
  packages/@aws-cdk/aws-dynamodb/test/integ.dynamodb.deletion-protection.js.snapshot/deletionprotectionintegtestDefaultTestDeployAssertA66823A5.template.json
  packages/@aws-cdk/aws-dynamodb/test/integ.dynamodb.deletion-protection.js.snapshot/integ.json
  packages/@aws-cdk/aws-dynamodb/test/integ.dynamodb.deletion-protection.js.snapshot/manifest.json
  packages/@aws-cdk/aws-dynamodb/test/integ.dynamodb.deletion-protection.js.snapshot/tree.json
  packages/@aws-cdk/aws-dynamodb/test/integ.dynamodb.deletion-protection.ts
Labels: p2, feature-request, effort/medium, admired-contributor

#24562 feat: added AllViewerExceptHostHeader as new OriginRequest policy
  packages/@aws-cdk/aws-cloudfront/lib/origin-request-policy.ts
  packages/@aws-cdk/aws-cloudfront/test/integ.distribution-policies.js.snapshot/cdk.out
  packages/@aws-cdk/aws-cloudfront/test/integ.distribution-policies.js.snapshot/integ-distribution-policies.assets.json
  packages/@aws-cdk/aws-cloudfront/test/integ.distribution-policies.js.snapshot/integ-distribution-policies.template.json
  packages/@aws-cdk/aws-cloudfront/test/integ.distribution-policies.js.snapshot/integ.json
  packages/@aws-cdk/aws-cloudfront/test/integ.distribution-policies.js.snapshot/manifest.json
  packages/@aws-cdk/aws-cloudfront/test/integ.distribution-policies.js.snapshot/tree.json
  packages/@aws-cdk/aws-cloudfront/test/integ.distribution-policies.ts
  packages/@aws-cdk/aws-cloudfront/test/origin-request-policy.test.ts
Labels: p2, feature-request, effort/small, pr/needs-review, pr-linter/exempt-readme, beginning-contributor, pr-linter/exemption-requested

#24693 refactor(ecs): replace instanceOf into BottleRocketImage.isBottleRocketImage() method
  packages/@aws-cdk/aws-ecs/lib/amis.ts
  packages/@aws-cdk/aws-ecs/lib/cluster.ts
  packages/@aws-cdk/aws-ecs/test/cluster.test.ts
Labels: p2, feature-request, valued-contributor

#24755 chore(merge-back): 2.70.0
  CHANGELOG.v2.alpha.md
  CHANGELOG.v2.md
  version.v2.json
Labels: p2, pr/no-squash, auto-approve

#24533 fix(cli): pathMetadata and assetMetadata defaults cannot be configured in cdk.json
  packages/aws-cdk/lib/cli.ts
  packages/aws-cdk/lib/settings.ts
Labels: bug, p1, effort/medium, pr-linter/exempt-test, pr-linter/exempt-integ-test, beginning-contributor, pr-linter/cli-integ-tested

#24682 fix(dynamodb): add missing iam permissions to custom resource for deleting dynamodb replica table
  packages/@aws-cdk/aws-dynamodb/lib/replica-provider.ts
  packages/@aws-cdk/aws-dynamodb/lib/table.ts
  packages/@aws-cdk/aws-dynamodb/test/dynamodb.test.ts
  packages/@aws-cdk/aws-dynamodb/test/integ.global-replicas-provisioned.js.snapshot/asset.7215c88dd3e638d28329d4538b36cdbfb54233a4d972181795814f8b904d1037/cfn-response.js
  packages/@aws-cdk/aws-dynamodb/test/integ.global-replicas-provisioned.js.snapshot/asset.7215c88dd3e638d28329d4538b36cdbfb54233a4d972181795814f8b904d1037/framework.js
  packages/@aws-cdk/aws-dynamodb/test/integ.global-replicas-provisioned.js.snapshot/asset.7215c88dd3e638d28329d4538b36cdbfb54233a4d972181795814f8b904d1037/outbound.js
  packages/@aws-cdk/aws-dynamodb/test/integ.global-replicas-provisioned.js.snapshot/asset.e1c44c46b1daa364ad4e38dbc77e6fe7714ea5fbf40251a924e8c34281aa2eda/cfn-response.js
  packages/@aws-cdk/aws-dynamodb/test/integ.global-replicas-provisioned.js.snapshot/asset.e1c44c46b1daa364ad4e38dbc77e6fe7714ea5fbf40251a924e8c34281aa2eda/consts.js
  packages/@aws-cdk/aws-dynamodb/test/integ.global-replicas-provisioned.js.snapshot/asset.e1c44c46b1daa364ad4e38dbc77e6fe7714ea5fbf40251a924e8c34281aa2eda/framework.js
  packages/@aws-cdk/aws-dynamodb/test/integ.global-replicas-provisioned.js.snapshot/asset.e1c44c46b1daa364ad4e38dbc77e6fe7714ea5fbf40251a924e8c34281aa2eda/outbound.js
  packages/@aws-cdk/aws-dynamodb/test/integ.global-replicas-provisioned.js.snapshot/asset.e1c44c46b1daa364ad4e38dbc77e6fe7714ea5fbf40251a924e8c34281aa2eda/util.js
  packages/@aws-cdk/aws-dynamodb/test/integ.global-replicas-provisioned.js.snapshot/aws-cdk-dynamodb-global-replicas-provisioned.assets.json
  packages/@aws-cdk/aws-dynamodb/test/integ.global-replicas-provisioned.js.snapshot/aws-cdk-dynamodb-global-replicas-provisioned.template.json
  packages/@aws-cdk/aws-dynamodb/test/integ.global-replicas-provisioned.js.snapshot/awscdkdynamodbglobalreplicasprovisionedawscdkawsdynamodbReplicaProviderEA32CB30.nested.template.json
  packages/@aws-cdk/aws-dynamodb/test/integ.global-replicas-provisioned.js.snapshot/cdk.out
  packages/@aws-cdk/aws-dynamodb/test/integ.global-replicas-provisioned.js.snapshot/integ.json
  packages/@aws-cdk/aws-dynamodb/test/integ.global-replicas-provisioned.js.snapshot/manifest.json
  packages/@aws-cdk/aws-dynamodb/test/integ.global-replicas-provisioned.js.snapshot/tree.json
  packages/@aws-cdk/aws-dynamodb/test/integ.global.js.snapshot/asset.7215c88dd3e638d28329d4538b36cdbfb54233a4d972181795814f8b904d1037/cfn-response.js
  packages/@aws-cdk/aws-dynamodb/test/integ.global.js.snapshot/asset.7215c88dd3e638d28329d4538b36cdbfb54233a4d972181795814f8b904d1037/framework.js
  packages/@aws-cdk/aws-dynamodb/test/integ.global.js.snapshot/asset.7215c88dd3e638d28329d4538b36cdbfb54233a4d972181795814f8b904d1037/outbound.js
  packages/@aws-cdk/aws-dynamodb/test/integ.global.js.snapshot/asset.e1c44c46b1daa364ad4e38dbc77e6fe7714ea5fbf40251a924e8c34281aa2eda/cfn-response.js
  packages/@aws-cdk/aws-dynamodb/test/integ.global.js.snapshot/asset.e1c44c46b1daa364ad4e38dbc77e6fe7714ea5fbf40251a924e8c34281aa2eda/consts.js
  packages/@aws-cdk/aws-dynamodb/test/integ.global.js.snapshot/asset.e1c44c46b1daa364ad4e38dbc77e6fe7714ea5fbf40251a924e8c34281aa2eda/framework.js
  packages/@aws-cdk/aws-dynamodb/test/integ.global.js.snapshot/asset.e1c44c46b1daa364ad4e38dbc77e6fe7714ea5fbf40251a924e8c34281aa2eda/outbound.js
  packages/@aws-cdk/aws-dynamodb/test/integ.global.js.snapshot/asset.e1c44c46b1daa364ad4e38dbc77e6fe7714ea5fbf40251a924e8c34281aa2eda/util.js
  packages/@aws-cdk/aws-dynamodb/test/integ.global.js.snapshot/cdk-dynamodb-global-20191121.assets.json
  packages/@aws-cdk/aws-dynamodb/test/integ.global.js.snapshot/cdk-dynamodb-global-20191121.template.json
  packages/@aws-cdk/aws-dynamodb/test/integ.global.js.snapshot/cdk.out
  packages/@aws-cdk/aws-dynamodb/test/integ.global.js.snapshot/cdkdynamodbglobal20191121awscdkawsdynamodbReplicaProviderB281C954.nested.template.json
  packages/@aws-cdk/aws-dynamodb/test/integ.global.js.snapshot/integ.json
  packages/@aws-cdk/aws-dynamodb/test/integ.global.js.snapshot/manifest.json
  packages/@aws-cdk/aws-dynamodb/test/integ.global.js.snapshot/tree.json
Labels: bug, p1, effort/small, pr-linter/exempt-integ-test, beginning-contributor, pr-linter/exemption-requested

#24756 chore(merge-back): 1.198.0
  CHANGELOG.md
  version.v1.json
Labels: p2, pr/no-squash, auto-approve

#23866 feat(kms): Adds support for hmac and sm2 key spec
  packages/@aws-cdk/aws-kms/README.md
  packages/@aws-cdk/aws-kms/lib/alias.ts
  packages/@aws-cdk/aws-kms/lib/key.ts
  packages/@aws-cdk/aws-kms/lib/private/perms.ts
  packages/@aws-cdk/aws-kms/package.json
  packages/@aws-cdk/aws-kms/test/alias.test.ts
  packages/@aws-cdk/aws-kms/test/integ.key-hmac.js.snapshot/HmacIntegTestDefaultTestDeployAssert10C19CC4.assets.json
  packages/@aws-cdk/aws-kms/test/integ.key-hmac.js.snapshot/HmacIntegTestDefaultTestDeployAssert10C19CC4.template.json
  packages/@aws-cdk/aws-kms/test/integ.key-hmac.js.snapshot/aws-cdk-kms-hmac.assets.json
  packages/@aws-cdk/aws-kms/test/integ.key-hmac.js.snapshot/aws-cdk-kms-hmac.template.json
  packages/@aws-cdk/aws-kms/test/integ.key-hmac.js.snapshot/cdk.out
  packages/@aws-cdk/aws-kms/test/integ.key-hmac.js.snapshot/integ.json
  packages/@aws-cdk/aws-kms/test/integ.key-hmac.js.snapshot/manifest.json
  packages/@aws-cdk/aws-kms/test/integ.key-hmac.js.snapshot/tree.json
  packages/@aws-cdk/aws-kms/test/integ.key-hmac.ts
  packages/@aws-cdk/aws-kms/test/key.test.ts
Labels: p2, feature-request, effort/small, admired-contributor

#24023 feat(cloudfront-origins): allow custom originPath for apigateway.RestApi constructs
  packages/@aws-cdk/aws-cloudfront-origins/README.md
  packages/@aws-cdk/aws-cloudfront-origins/lib/rest-api-origin.ts
  packages/@aws-cdk/aws-cloudfront-origins/test/integ.rest-api-origin-custom-origin-path.js.snapshot/cdk.out
  packages/@aws-cdk/aws-cloudfront-origins/test/integ.rest-api-origin-custom-origin-path.js.snapshot/integ-cloudfront-rest-api-origin-custom-origin-path.assets.json
  packages/@aws-cdk/aws-cloudfront-origins/test/integ.rest-api-origin-custom-origin-path.js.snapshot/integ-cloudfront-rest-api-origin-custom-origin-path.template.json
  packages/@aws-cdk/aws-cloudfront-origins/test/integ.rest-api-origin-custom-origin-path.js.snapshot/integ.json
  packages/@aws-cdk/aws-cloudfront-origins/test/integ.rest-api-origin-custom-origin-path.js.snapshot/manifest.json
  packages/@aws-cdk/aws-cloudfront-origins/test/integ.rest-api-origin-custom-origin-path.js.snapshot/restapiorigincustomoriginpathDefaultTestDeployAssertCD227A2A.assets.json
  packages/@aws-cdk/aws-cloudfront-origins/test/integ.rest-api-origin-custom-origin-path.js.snapshot/restapiorigincustomoriginpathDefaultTestDeployAssertCD227A2A.template.json
  packages/@aws-cdk/aws-cloudfront-origins/test/integ.rest-api-origin-custom-origin-path.js.snapshot/tree.json
  packages/@aws-cdk/aws-cloudfront-origins/test/integ.rest-api-origin-custom-origin-path.ts
  packages/@aws-cdk/aws-cloudfront-origins/test/integ.rest-api-origin-custom-origin-path.ts.snapshot/cdk.out
  packages/@aws-cdk/aws-cloudfront-origins/test/integ.rest-api-origin-custom-origin-path.ts.snapshot/integ-cloudfront-rest-api-origin-custom-origin-path.assets.json
  packages/@aws-cdk/aws-cloudfront-origins/test/integ.rest-api-origin-custom-origin-path.ts.snapshot/integ-cloudfront-rest-api-origin-custom-origin-path.template.json
  packages/@aws-cdk/aws-cloudfront-origins/test/integ.rest-api-origin-custom-origin-path.ts.snapshot/integ.json
  packages/@aws-cdk/aws-cloudfront-origins/test/integ.rest-api-origin-custom-origin-path.ts.snapshot/manifest.json
  packages/@aws-cdk/aws-cloudfront-origins/test/integ.rest-api-origin-custom-origin-path.ts.snapshot/restapiorigincustomoriginpathDefaultTestDeployAssertCD227A2A.assets.json
  packages/@aws-cdk/aws-cloudfront-origins/test/integ.rest-api-origin-custom-origin-path.ts.snapshot/restapiorigincustomoriginpathDefaultTestDeployAssertCD227A2A.template.json
  packages/@aws-cdk/aws-cloudfront-origins/test/integ.rest-api-origin-custom-origin-path.ts.snapshot/tree.json
  packages/@aws-cdk/aws-cloudfront-origins/test/rest-api-origin.test.ts
Labels: p2, beginning-contributor

#24760 fix(servicecatalogappregistry): RAM Share is replaced on every change to Application
  packages/@aws-cdk/aws-servicecatalogappregistry/README.md
  packages/@aws-cdk/aws-servicecatalogappregistry/lib/application.ts
  packages/@aws-cdk/aws-servicecatalogappregistry/lib/aspects/stack-associator.ts
  packages/@aws-cdk/aws-servicecatalogappregistry/lib/attribute-group.ts
  packages/@aws-cdk/aws-servicecatalogappregistry/lib/common.ts
  packages/@aws-cdk/aws-servicecatalogappregistry/test/application.test.ts
  packages/@aws-cdk/aws-servicecatalogappregistry/test/attribute-group.test.ts
  packages/@aws-cdk/aws-servicecatalogappregistry/test/integ.application.js.snapshot/integ-servicecatalogappregistry-application.assets.json
  packages/@aws-cdk/aws-servicecatalogappregistry/test/integ.application.js.snapshot/integ-servicecatalogappregistry-application.template.json
  packages/@aws-cdk/aws-servicecatalogappregistry/test/integ.application.js.snapshot/manifest.json
  packages/@aws-cdk/aws-servicecatalogappregistry/test/integ.application.js.snapshot/tree.json
  packages/@aws-cdk/aws-servicecatalogappregistry/test/integ.application.ts
  packages/@aws-cdk/aws-servicecatalogappregistry/test/integ.attribute-group.js.snapshot/cdk.out
  packages/@aws-cdk/aws-servicecatalogappregistry/test/integ.attribute-group.js.snapshot/integ-servicecatalogappregistry-attribute-group.assets.json
  packages/@aws-cdk/aws-servicecatalogappregistry/test/integ.attribute-group.js.snapshot/integ-servicecatalogappregistry-attribute-group.template.json
  packages/@aws-cdk/aws-servicecatalogappregistry/test/integ.attribute-group.js.snapshot/integ.json
  packages/@aws-cdk/aws-servicecatalogappregistry/test/integ.attribute-group.js.snapshot/manifest.json
  packages/@aws-cdk/aws-servicecatalogappregistry/test/integ.attribute-group.js.snapshot/tree.json
  packages/@aws-cdk/aws-servicecatalogappregistry/test/integ.attribute-group.ts
Labels: p2, beginning-contributor

#23985 fix(stepfunctions-tasks): updated EMR service role to use `AmazonEMRServicePolicy_v2` (under feature flag)
  packages/@aws-cdk/aws-stepfunctions-tasks/lib/emr/emr-create-cluster.ts
  packages/@aws-cdk/aws-stepfunctions-tasks/package.json
  packages/@aws-cdk/aws-stepfunctions-tasks/test/emr/emr-create-cluster.test.ts
  packages/@aws-cdk/aws-stepfunctions-tasks/test/emr/integ.emr-create-cluster-with-v1-policy.js.snapshot/EmrCreateClusterTestDefaultTestDeployAssert697DC891.assets.json
  packages/@aws-cdk/aws-stepfunctions-tasks/test/emr/integ.emr-create-cluster-with-v1-policy.js.snapshot/EmrCreateClusterTestDefaultTestDeployAssert697DC891.template.json
  packages/@aws-cdk/aws-stepfunctions-tasks/test/emr/integ.emr-create-cluster-with-v1-policy.js.snapshot/aws-cdk-emr-create-cluster.assets.json
  packages/@aws-cdk/aws-stepfunctions-tasks/test/emr/integ.emr-create-cluster-with-v1-policy.js.snapshot/aws-cdk-emr-create-cluster.template.json
  packages/@aws-cdk/aws-stepfunctions-tasks/test/emr/integ.emr-create-cluster-with-v1-policy.js.snapshot/cdk.out
  packages/@aws-cdk/aws-stepfunctions-tasks/test/emr/integ.emr-create-cluster-with-v1-policy.js.snapshot/integ.json
  packages/@aws-cdk/aws-stepfunctions-tasks/test/emr/integ.emr-create-cluster-with-v1-policy.js.snapshot/manifest.json
  packages/@aws-cdk/aws-stepfunctions-tasks/test/emr/integ.emr-create-cluster-with-v1-policy.js.snapshot/tree.json
  packages/@aws-cdk/aws-stepfunctions-tasks/test/emr/integ.emr-create-cluster-with-v1-policy.ts
  packages/@aws-cdk/aws-stepfunctions-tasks/test/emr/integ.emr-create-cluster-with-v2-policy.js.snapshot/EmrCreateClusterTestDefaultTestDeployAssert697DC891.assets.json
  packages/@aws-cdk/aws-stepfunctions-tasks/test/emr/integ.emr-create-cluster-with-v2-policy.js.snapshot/EmrCreateClusterTestDefaultTestDeployAssert697DC891.template.json
  packages/@aws-cdk/aws-stepfunctions-tasks/test/emr/integ.emr-create-cluster-with-v2-policy.js.snapshot/aws-cdk-emr-create-cluster.assets.json
  packages/@aws-cdk/aws-stepfunctions-tasks/test/emr/integ.emr-create-cluster-with-v2-policy.js.snapshot/aws-cdk-emr-create-cluster.template.json
  packages/@aws-cdk/aws-stepfunctions-tasks/test/emr/integ.emr-create-cluster-with-v2-policy.js.snapshot/cdk.out
  packages/@aws-cdk/aws-stepfunctions-tasks/test/emr/integ.emr-create-cluster-with-v2-policy.js.snapshot/integ.json
  packages/@aws-cdk/aws-stepfunctions-tasks/test/emr/integ.emr-create-cluster-with-v2-policy.js.snapshot/manifest.json
  packages/@aws-cdk/aws-stepfunctions-tasks/test/emr/integ.emr-create-cluster-with-v2-policy.js.snapshot/tree.json
  packages/@aws-cdk/aws-stepfunctions-tasks/test/emr/integ.emr-create-cluster-with-v2-policy.ts
  packages/@aws-cdk/cx-api/FEATURE_FLAGS.md
  packages/@aws-cdk/cx-api/README.md
  packages/@aws-cdk/cx-api/lib/features.ts
Labels: bug, p2, effort/small, beginning-contributor

#24794 chore: Corrected typos
  packages/@aws-cdk/core/lib/app.ts
  packages/@aws-cdk/core/lib/assets.ts
  packages/@aws-cdk/core/lib/bundling.ts
  packages/@aws-cdk/core/lib/cfn-condition.ts
  packages/@aws-cdk/core/lib/cfn-element.ts
  packages/@aws-cdk/core/lib/cfn-fn.ts
  packages/@aws-cdk/core/lib/cfn-json.ts
  packages/@aws-cdk/core/lib/cfn-resource.ts
  packages/@aws-cdk/core/lib/duration.ts
  packages/@aws-cdk/core/lib/expiration.ts
  packages/@aws-cdk/core/lib/lazy.ts
  packages/@aws-cdk/core/lib/nested-stack.ts
  packages/@aws-cdk/core/lib/physical-name.ts
  packages/@aws-cdk/core/lib/private/cfn-reference.ts
  packages/@aws-cdk/core/lib/private/cfn-utils-provider.ts
  packages/@aws-cdk/core/lib/private/cloudformation-lang.ts
  packages/@aws-cdk/core/lib/private/logical-id.ts
  packages/@aws-cdk/core/lib/private/prepare-app.ts
  packages/@aws-cdk/core/lib/removal-policy.ts
  packages/@aws-cdk/core/lib/resource.ts
  packages/@aws-cdk/core/lib/runtime.ts
  packages/@aws-cdk/core/lib/secret-value.ts
  packages/@aws-cdk/core/lib/stack-synthesizers/asset-manifest-builder.ts
  packages/@aws-cdk/core/lib/stack-synthesizers/cli-credentials-synthesizer.ts
  packages/@aws-cdk/core/lib/stack-synthesizers/default-synthesizer.ts
  packages/@aws-cdk/core/lib/stack-synthesizers/legacy.ts
  packages/@aws-cdk/core/lib/stack-synthesizers/stack-synthesizer.ts
  packages/@aws-cdk/core/lib/stack-trace.ts
  packages/@aws-cdk/core/lib/stack.ts
  packages/@aws-cdk/core/lib/token.ts
  packages/@aws-cdk/core/lib/util.ts
Labels: p2, contribution/core

#24444 fix(cli): cdk deploy output hook failure reason if cloudformation failed by hook
  packages/aws-cdk/lib/api/util/cloudformation/stack-activity-monitor.ts
  packages/aws-cdk/test/api/stack-activity-monitor.test.ts
Labels: p2, no-autoclose, pr-linter/exempt-integ-test, beginning-contributor, pr-linter/cli-integ-tested

#23951 feat(core): template validation after synthesis
  package.json
  packages/@aws-cdk/core/README.md
  packages/@aws-cdk/core/lib/app.ts
  packages/@aws-cdk/core/lib/index.ts
  packages/@aws-cdk/core/lib/private/runtime-info.ts
  packages/@aws-cdk/core/lib/private/synthesis.ts
  packages/@aws-cdk/core/lib/private/tree-metadata.ts
  packages/@aws-cdk/core/lib/stage.ts
  packages/@aws-cdk/core/lib/validation/index.ts
  packages/@aws-cdk/core/lib/validation/private/construct-tree.ts
  packages/@aws-cdk/core/lib/validation/private/report.ts
  packages/@aws-cdk/core/lib/validation/private/trace.ts
  packages/@aws-cdk/core/lib/validation/report.ts
  packages/@aws-cdk/core/lib/validation/validation.ts
  packages/@aws-cdk/core/package.json
  packages/@aws-cdk/core/rosetta/README-custom-resource-provider.ts-fixture
  packages/@aws-cdk/core/test/metadata-resource.test.ts
  packages/@aws-cdk/core/test/validation/trace.test.ts
  packages/@aws-cdk/core/test/validation/validation.test.ts
  packages/@aws-cdk/cx-api/FEATURE_FLAGS.md
  packages/@aws-cdk/cx-api/lib/features.ts
  packages/aws-cdk-lib/.gitignore
  packages/aws-cdk-lib/NOTICE
  packages/aws-cdk-lib/README.md
  packages/aws-cdk-lib/package.json
Labels: p2, contribution/core, pr-linter/exempt-integ-test

#24720 fix(integ-runner): update workflow doesn't support resource replacement
  packages/@aws-cdk/integ-runner/lib/runner/integ-test-runner.ts
  packages/@aws-cdk/integ-runner/test/runner/integ-test-runner.test.ts
  packages/@aws-cdk/integ-runner/test/test-data/cdk-integ.out.xxxxx.test-with-snapshot.js.snapshot/integ.json
  packages/@aws-cdk/integ-runner/test/test-data/xxxxx.test-with-snapshot.js.snapshot/integ.json
Labels: p2, contribution/core

#24538 chore(rds): deprecate PostgreSQL 10.x
  packages/@aws-cdk/aws-rds/README.md
  packages/@aws-cdk/aws-rds/lib/instance-engine.ts
  packages/@aws-cdk/aws-rds/test/instance-engine.test.ts
  packages/@aws-cdk/aws-rds/test/instance.test.ts
  packages/@aws-cdk/aws-rds/test/integ.instance-dual.js.snapshot/aws-cdk-rds-instance-dual-integ.assets.json
  packages/@aws-cdk/aws-rds/test/integ.instance-dual.js.snapshot/aws-cdk-rds-instance-dual-integ.template.json
  packages/@aws-cdk/aws-rds/test/integ.instance-dual.js.snapshot/cdk.out
  packages/@aws-cdk/aws-rds/test/integ.instance-dual.js.snapshot/instancedualtestDefaultTestDeployAssertD87FA35D.assets.json
  packages/@aws-cdk/aws-rds/test/integ.instance-dual.js.snapshot/integ.json
  packages/@aws-cdk/aws-rds/test/integ.instance-dual.js.snapshot/manifest.json
  packages/@aws-cdk/aws-rds/test/integ.instance-dual.js.snapshot/tree.json
  packages/@aws-cdk/aws-rds/test/integ.instance-dual.ts
  packages/@aws-cdk/aws-rds/test/integ.instance-s3-postgres.js.snapshot/aws-cdk-rds-instance-s3-postgres-integ.assets.json
  packages/@aws-cdk/aws-rds/test/integ.instance-s3-postgres.js.snapshot/aws-cdk-rds-instance-s3-postgres-integ.template.json
  packages/@aws-cdk/aws-rds/test/integ.instance-s3-postgres.js.snapshot/cdk.out
  packages/@aws-cdk/aws-rds/test/integ.instance-s3-postgres.js.snapshot/integ.json
  packages/@aws-cdk/aws-rds/test/integ.instance-s3-postgres.js.snapshot/manifest.json
  packages/@aws-cdk/aws-rds/test/integ.instance-s3-postgres.js.snapshot/tree.json
  packages/@aws-cdk/aws-rds/test/integ.instance-s3-postgres.ts
  packages/@aws-cdk/aws-rds/test/integ.proxy.js.snapshot/aws-cdk-rds-proxy.assets.json
  packages/@aws-cdk/aws-rds/test/integ.proxy.js.snapshot/aws-cdk-rds-proxy.template.json
  packages/@aws-cdk/aws-rds/test/integ.proxy.js.snapshot/cdk.out
  packages/@aws-cdk/aws-rds/test/integ.proxy.js.snapshot/databaseproxyintegtestDefaultTestDeployAssert1DC3D9D5.assets.json
  packages/@aws-cdk/aws-rds/test/integ.proxy.js.snapshot/integ.json
  packages/@aws-cdk/aws-rds/test/integ.proxy.js.snapshot/manifest.json
  packages/@aws-cdk/aws-rds/test/integ.proxy.js.snapshot/tree.json
  packages/@aws-cdk/aws-rds/test/integ.proxy.ts
  packages/@aws-cdk/aws-rds/test/integ.read-replica.js.snapshot/cdk-rds-read-replica.assets.json
  packages/@aws-cdk/aws-rds/test/integ.read-replica.js.snapshot/cdk-rds-read-replica.template.json
  packages/@aws-cdk/aws-rds/test/integ.read-replica.js.snapshot/cdk.out
  packages/@aws-cdk/aws-rds/test/integ.read-replica.js.snapshot/integ.json
  packages/@aws-cdk/aws-rds/test/integ.read-replica.js.snapshot/manifest.json
  packages/@aws-cdk/aws-rds/test/integ.read-replica.js.snapshot/tree.json
  packages/@aws-cdk/aws-rds/test/integ.read-replica.ts
Labels: p2, distinguished-contributor

#24829 fix(lambda-nodejs): pnpm no longer supports nodejs14.x (backport #24821)
  packages/@aws-cdk/aws-lambda-nodejs/lib/Dockerfile
  packages/@aws-cdk/aws-lambda-nodejs/test/docker.test.ts
Labels: p2, contribution/core

#24818 feat(cfnspec): cloudformation spec v117.0.0
  packages/@aws-cdk/cfnspec/spec-source/cfn-lint/StatefulResources/000.json
Labels: p2, pr-linter/exempt-test, auto-approve, pr-linter/exempt-integ-test

#24833 chore(release): 1.198.1
  CHANGELOG.md
  packages/@aws-cdk/aws-lambda-nodejs/lib/Dockerfile
  packages/@aws-cdk/aws-lambda-nodejs/test/docker.test.ts
  version.v1.json
Labels: p2, contribution/core, pr/no-squash

#24811 fix(logs-destinations): missing dependency to Policy created by KinesisDestination
  packages/@aws-cdk/aws-logs-destinations/lib/kinesis.ts
  packages/@aws-cdk/aws-logs-destinations/package.json
  packages/@aws-cdk/aws-logs-destinations/test/integ.kinesis.js.snapshot/KinesisIntegDefaultTestDeployAssertE6E3ADDB.assets.json
  packages/@aws-cdk/aws-logs-destinations/test/integ.kinesis.js.snapshot/KinesisIntegDefaultTestDeployAssertE6E3ADDB.template.json
  packages/@aws-cdk/aws-logs-destinations/test/integ.kinesis.js.snapshot/cdk.out
  packages/@aws-cdk/aws-logs-destinations/test/integ.kinesis.js.snapshot/integ.json
  packages/@aws-cdk/aws-logs-destinations/test/integ.kinesis.js.snapshot/kinesis-logsubscription-integ.assets.json
  packages/@aws-cdk/aws-logs-destinations/test/integ.kinesis.js.snapshot/kinesis-logsubscription-integ.template.json
  packages/@aws-cdk/aws-logs-destinations/test/integ.kinesis.js.snapshot/manifest.json
  packages/@aws-cdk/aws-logs-destinations/test/integ.kinesis.js.snapshot/tree.json
  packages/@aws-cdk/aws-logs-destinations/test/integ.kinesis.ts
  packages/@aws-cdk/aws-logs-destinations/test/kinesis.test.ts
Labels: bug, p2, effort/small, beginning-contributor

#24735 fix(bootstrap): ECR repository produces Security Hub finding [ECR.3] because of missing lifecycle policy
  packages/aws-cdk/lib/api/bootstrap/bootstrap-template.yaml
Labels: p2, feature-request, effort/small, pr-linter/exempt-test, pr-linter/exempt-integ-test, beginning-contributor

#24211 feat(s3): add `allowedActionPatterns` parameter to grantWrite
  packages/@aws-cdk/aws-s3/lib/bucket.ts
  packages/@aws-cdk/aws-s3/test/bucket.test.ts
  packages/@aws-cdk/aws-s3/test/integ.bucket-grant-write.js.snapshot/BucketGrantWriteTestDefaultTestDeployAssertF3318F24.assets.json
  packages/@aws-cdk/aws-s3/test/integ.bucket-grant-write.js.snapshot/BucketGrantWriteTestDefaultTestDeployAssertF3318F24.template.json
  packages/@aws-cdk/aws-s3/test/integ.bucket-grant-write.js.snapshot/aws-cdk-s3.assets.json
  packages/@aws-cdk/aws-s3/test/integ.bucket-grant-write.js.snapshot/aws-cdk-s3.template.json
  packages/@aws-cdk/aws-s3/test/integ.bucket-grant-write.js.snapshot/cdk.out
  packages/@aws-cdk/aws-s3/test/integ.bucket-grant-write.js.snapshot/integ.json
  packages/@aws-cdk/aws-s3/test/integ.bucket-grant-write.js.snapshot/manifest.json
  packages/@aws-cdk/aws-s3/test/integ.bucket-grant-write.js.snapshot/tree.json
  packages/@aws-cdk/aws-s3/test/integ.bucket-grant-write.ts
Labels: p2, feature-request, effort/small, pr-linter/exempt-readme, repeat-contributor

#24450 chore(ec2): add M7g and R7g instances
  packages/@aws-cdk/aws-ec2/lib/instance-types.ts
  packages/@aws-cdk/aws-ec2/test/instance.test.ts
Labels: p2, pr-linter/exempt-readme, pr-linter/exempt-integ-test, star-contributor, pr-linter/exemption-requested, pr/reviewer-clarification-requested

#24453 feat(efs): implement IResourceWithPolicy
  packages/@aws-cdk/aws-efs/README.md
  packages/@aws-cdk/aws-efs/lib/efs-file-system.ts
  packages/@aws-cdk/aws-efs/test/efs-file-system.test.ts
  packages/@aws-cdk/aws-efs/test/integ.efs-filesystem-policy.js.snapshot/manifest.json
  packages/@aws-cdk/aws-efs/test/integ.efs-filesystem-policy.js.snapshot/test-efs-integ.assets.json
  packages/@aws-cdk/aws-efs/test/integ.efs-filesystem-policy.js.snapshot/test-efs-integ.template.json
  packages/@aws-cdk/aws-efs/test/integ.efs-filesystem-policy.js.snapshot/tree.json
  packages/@aws-cdk/aws-efs/test/integ.efs-filesystem-policy.ts
Labels: p2, feature-request, effort/small, valued-contributor

#24679 chore(ec2): KMS supports FIPS 140-2 enabled Endpoint and Other
  packages/@aws-cdk/aws-ec2/lib/vpc-endpoint.ts
  packages/@aws-cdk/aws-ec2/package.json
Labels: p2, star-contributor

#24625 fix(ec2): tokenised subnet.subnetId filtered by the SubnetIdSubnetFilter returns an empty array
  packages/@aws-cdk/aws-ec2/lib/subnet.ts
  packages/@aws-cdk/aws-ec2/test/integ.vpc-filter-subnets.js.snapshot/VPCFilterSubnetsDefaultTestDeployAssertC02936E8.assets.json
  packages/@aws-cdk/aws-ec2/test/integ.vpc-filter-subnets.js.snapshot/VPCFilterSubnetsDefaultTestDeployAssertC02936E8.template.json
  packages/@aws-cdk/aws-ec2/test/integ.vpc-filter-subnets.js.snapshot/VPCFilterSubnetsTestStack.assets.json
  packages/@aws-cdk/aws-ec2/test/integ.vpc-filter-subnets.js.snapshot/VPCFilterSubnetsTestStack.template.json
  packages/@aws-cdk/aws-ec2/test/integ.vpc-filter-subnets.js.snapshot/cdk.out
  packages/@aws-cdk/aws-ec2/test/integ.vpc-filter-subnets.js.snapshot/integ.json
  packages/@aws-cdk/aws-ec2/test/integ.vpc-filter-subnets.js.snapshot/manifest.json
  packages/@aws-cdk/aws-ec2/test/integ.vpc-filter-subnets.js.snapshot/tree.json
  packages/@aws-cdk/aws-ec2/test/integ.vpc-filter-subnets.ts
  packages/@aws-cdk/aws-ec2/test/vpc.test.ts
Labels: bug, p1, effort/small, beginning-contributor

#24823 fix(logs-destinations): missing dependency to Permission Policy created by LambdaDestination
  packages/@aws-cdk/aws-logs-destinations/lib/lambda.ts
  packages/@aws-cdk/aws-logs-destinations/package.json
  packages/@aws-cdk/aws-logs-destinations/test/integ.lambda.js.snapshot/LambdaIntegDefaultTestDeployAssert7BC530B7.assets.json
  packages/@aws-cdk/aws-logs-destinations/test/integ.lambda.js.snapshot/LambdaIntegDefaultTestDeployAssert7BC530B7.template.json
  packages/@aws-cdk/aws-logs-destinations/test/integ.lambda.js.snapshot/asset.33583035258f91f2130bb9759626b0a4b2fe7fad9f3e63d427ce5cdc3447b820.bundle/index.js
  packages/@aws-cdk/aws-logs-destinations/test/integ.lambda.js.snapshot/asset.a9d3d4d1afa000946b9863b3e7578a5a5ad86d88274b3639938aa2baebf822ce/index.js
  packages/@aws-cdk/aws-logs-destinations/test/integ.lambda.js.snapshot/cdk.out
  packages/@aws-cdk/aws-logs-destinations/test/integ.lambda.js.snapshot/integ.json
  packages/@aws-cdk/aws-logs-destinations/test/integ.lambda.js.snapshot/lambda-logssubscription-integ.assets.json
  packages/@aws-cdk/aws-logs-destinations/test/integ.lambda.js.snapshot/lambda-logssubscription-integ.template.json
  packages/@aws-cdk/aws-logs-destinations/test/integ.lambda.js.snapshot/manifest.json
  packages/@aws-cdk/aws-logs-destinations/test/integ.lambda.js.snapshot/tree.json
  packages/@aws-cdk/aws-logs-destinations/test/integ.lambda.ts
  packages/@aws-cdk/aws-logs-destinations/test/lambda.test.ts
Labels: bug, p1, effort/small, beginning-contributor

#24837 chore(lambda-nodejs): pin pnpm version to 7
  packages/@aws-cdk/aws-lambda-nodejs/lib/Dockerfile
Labels: p2, contribution/core

#24647 fix(ecs): cpu in container definition may be less than total cpu allocated to the container
  packages/@aws-cdk/aws-ecs/lib/base/task-definition.ts
  packages/@aws-cdk/aws-ecs/lib/container-definition.ts
  packages/@aws-cdk/aws-ecs/test/task-definition.test.ts
Labels: p2, feature-request, effort/medium, pr-linter/exempt-integ-test, beginning-contributor

#24428 fix(s3-deployment): physical id not set during failure scenario
  packages/@aws-cdk/aws-s3-deployment/lib/lambda/index.py
  packages/@aws-cdk/aws-s3-deployment/test/lambda/test.py
Labels: bug, p1, effort/small, pr-linter/exempt-integ-test, beginning-contributor

#24841 feat(cfnspec): cloudformation spec v117.0.0
  packages/@aws-cdk/cfnspec/spec-source/cfn-lint/StatefulResources/000.json
Labels: p2, pr-linter/exempt-test, auto-approve, pr-linter/exempt-integ-test

#24845 chore(release): 2.71.0
  CHANGELOG.v2.md
  packages/@aws-cdk/aws-lambda-nodejs/lib/Dockerfile
Labels: p2, contribution/core, pr/no-squash

#24849 chore: record `cdk8s` usage in stack metadata
  packages/@aws-cdk/core/lib/private/runtime-info.ts
Labels: p2, contribution/core

#24858 chore(merge-back): 2.72.0
  CHANGELOG.v2.alpha.md
  CHANGELOG.v2.md
  packages/@aws-cdk/cx-api/FEATURE_FLAGS.md
  packages/@aws-cdk/cx-api/lib/features.ts
  version.v2.json
Labels: p2, pr/no-squash, auto-approve

#24793 feat(cli): exposed synth's quiet option in cdk.json
  packages/@aws-cdk-testing/cli-integ/tests/cli-integ-tests/cli.integtest.ts
  packages/aws-cdk/README.md
  packages/aws-cdk/lib/cli.ts
  packages/aws-cdk/test/usersettings.test.ts
Labels: p2, feature-request, effort/small, pr-linter/exempt-integ-test, repeat-contributor, pr-linter/cli-integ-tested

#24781 fix(lambda-nodejs): pnpm installs frozen lockfile in a CI environment
  packages/@aws-cdk/aws-lambda-nodejs/lib/package-manager.ts
  packages/@aws-cdk/aws-lambda-nodejs/test/bundling.test.ts
  packages/@aws-cdk/aws-lambda-nodejs/test/package-manager.test.ts
Labels: p2, pr-linter/exempt-integ-test, beginning-contributor

#24549 fix(iam): roleName not validated in fromRoleName function
  packages/@aws-cdk/aws-iam/lib/role.ts
  packages/@aws-cdk/aws-iam/test/role.test.ts
Labels: bug, p2, effort/small, pr-linter/exempt-integ-test, repeat-contributor

#24869 chore: upgrade to jsii@5.0.2
  packages/@aws-cdk/assertions/package.json
  packages/@aws-cdk/aws-eks/package.json
  packages/@aws-cdk/aws-elasticloadbalancingv2/package.json
  packages/@aws-cdk/aws-elasticsearch/package.json
  packages/@aws-cdk/aws-events-targets/package.json
  packages/@aws-cdk/aws-lambda-go/package.json
  packages/@aws-cdk/aws-lambda-nodejs/package.json
  packages/@aws-cdk/aws-opensearchservice/package.json
  packages/@aws-cdk/cli-lib/THIRD_PARTY_LICENSES
  packages/@aws-cdk/core/package.json
  packages/@aws-cdk/custom-resources/package.json
  packages/@aws-cdk/pipelines/package.json
  packages/aws-cdk-lib/package.json
  tools/@aws-cdk/cdk-build-tools/package.json
  yarn.lock
Labels: p2, contribution/core

#24872 chore: in case of policy validation failures, don't throw
  packages/@aws-cdk/core/lib/private/synthesis.ts
  packages/@aws-cdk/core/test/validation/validation.test.ts
Labels: p2, contribution/core

#24876 chore(release): v2.72.1
  CHANGELOG.v2.alpha.md
  CHANGELOG.v2.md
  packages/@aws-cdk/assertions/package.json
  packages/@aws-cdk/aws-eks/package.json
  packages/@aws-cdk/aws-elasticloadbalancingv2/package.json
  packages/@aws-cdk/aws-elasticsearch/package.json
  packages/@aws-cdk/aws-events-targets/package.json
  packages/@aws-cdk/aws-lambda-go/package.json
  packages/@aws-cdk/aws-lambda-nodejs/package.json
  packages/@aws-cdk/aws-opensearchservice/package.json
  packages/@aws-cdk/cli-lib/THIRD_PARTY_LICENSES
  packages/@aws-cdk/core/package.json
  packages/@aws-cdk/custom-resources/package.json
  packages/@aws-cdk/pipelines/package.json
  packages/aws-cdk-lib/package.json
  tools/@aws-cdk/cdk-build-tools/package.json
  version.v2.json
  yarn.lock
Labels: p2, contribution/core, pr/no-squash

#24729 feat(rds): Add dbname parameter to RDS.DatabaseSecret construct
  packages/@aws-cdk/aws-rds/README.md
  packages/@aws-cdk/aws-rds/lib/database-secret.ts
  packages/@aws-cdk/aws-rds/test/database-secret.test.ts
  packages/@aws-cdk/aws-rds/test/integ.serverless-cluster-secret-rotation-custom-names.js.snapshot/aws-cdk-rds-integ-secret-rotation.assets.json
  packages/@aws-cdk/aws-rds/test/integ.serverless-cluster-secret-rotation-custom-names.js.snapshot/aws-cdk-rds-integ-secret-rotation.template.json
  packages/@aws-cdk/aws-rds/test/integ.serverless-cluster-secret-rotation-custom-names.js.snapshot/cdk.out
  packages/@aws-cdk/aws-rds/test/integ.serverless-cluster-secret-rotation-custom-names.js.snapshot/cdkrdsintegsecretrotationDefaultTestDeployAssert9780868B.assets.json
  packages/@aws-cdk/aws-rds/test/integ.serverless-cluster-secret-rotation-custom-names.js.snapshot/cdkrdsintegsecretrotationDefaultTestDeployAssert9780868B.template.json
  packages/@aws-cdk/aws-rds/test/integ.serverless-cluster-secret-rotation-custom-names.js.snapshot/integ.json
  packages/@aws-cdk/aws-rds/test/integ.serverless-cluster-secret-rotation-custom-names.js.snapshot/manifest.json
  packages/@aws-cdk/aws-rds/test/integ.serverless-cluster-secret-rotation-custom-names.js.snapshot/tree.json
  packages/@aws-cdk/aws-rds/test/integ.serverless-cluster-secret-rotation-custom-names.ts
Labels: p2, feature-request, beginning-contributor

#24864 docs(s3-assets): fix the doc to compilable
  packages/@aws-cdk/aws-s3-assets/README.md
  packages/@aws-cdk/aws-s3-assets/rosetta/default.ts-fixture
Labels: p2, valued-contributor

#24877 docs(secretsmanager): improve the doc for fromSecretNameV2()
  packages/@aws-cdk/aws-secretsmanager/lib/secret.ts
Labels: p2, contribution/core

#24889 fix(core): some trace info is missing from the validation report
  packages/@aws-cdk/core/lib/private/tree-metadata.ts
  packages/@aws-cdk/core/lib/validation/private/construct-tree.ts
  packages/@aws-cdk/core/test/validation/trace.test.ts
Labels: p2, contribution/core, pr-linter/exempt-integ-test

#24893 chore(merge-back): 1.199.0
  CHANGELOG.md
  version.v1.json
Labels: p2, pr/no-squash, auto-approve

#24894 chore: fix gitignore
  packages/@aws-cdk/aws-amplify/.gitignore
  packages/@aws-cdk/aws-apigatewayv2-authorizers/.gitignore
  packages/@aws-cdk/aws-apigatewayv2-integrations/.gitignore
  packages/@aws-cdk/aws-apigatewayv2/.gitignore
  packages/@aws-cdk/aws-apprunner/.gitignore
  packages/@aws-cdk/aws-batch/.gitignore
  packages/@aws-cdk/aws-cloud9/.gitignore
  packages/@aws-cdk/aws-codestar/.gitignore
  packages/@aws-cdk/aws-cognito-identitypool/.gitignore
  packages/@aws-cdk/aws-gamelift/.gitignore
  packages/@aws-cdk/aws-glue/.gitignore
  packages/@aws-cdk/aws-iot-actions/.gitignore
  packages/@aws-cdk/aws-iot/.gitignore
  packages/@aws-cdk/aws-iotevents-actions/.gitignore
  packages/@aws-cdk/aws-iotevents/.gitignore
  packages/@aws-cdk/aws-ivs/.gitignore
  packages/@aws-cdk/aws-kinesisanalytics-flink/.gitignore
  packages/@aws-cdk/aws-kinesisfirehose-destinations/.gitignore
  packages/@aws-cdk/aws-kinesisfirehose/.gitignore
  packages/@aws-cdk/aws-lambda-go/.gitignore
  packages/@aws-cdk/aws-lambda-python/.gitignore
  packages/@aws-cdk/aws-location/.gitignore
  packages/@aws-cdk/aws-msk/.gitignore
  packages/@aws-cdk/aws-neptune/.gitignore
  packages/@aws-cdk/aws-redshift/.gitignore
  packages/@aws-cdk/aws-route53resolver/.gitignore
  packages/@aws-cdk/aws-s3objectlambda/.gitignore
  packages/@aws-cdk/aws-sagemaker/.gitignore
  packages/@aws-cdk/aws-servicecatalogappregistry/.gitignore
  packages/@aws-cdk/aws-synthetics/.gitignore
  packages/@aws-cdk/cli-lib/.gitignore
  packages/@aws-cdk/integ-tests/.gitignore
  yarn.lock
Labels: p2, contribution/core

#24895 chore: detect property type renames to protect against breakage
  packages/@aws-cdk/cfnspec/build-tools/spec-diff.ts
  packages/@aws-cdk/cfnspec/build-tools/update.sh
  packages/@aws-cdk/cfnspec/spec-source/specification/000_cfn/500_WAFv2_RuleGroup_Rename_Properties_patch.json
Labels: p2, contribution/core

#24890 chore(cli-integ-tests): silence JSII warnings in test env
  packages/@aws-cdk-testing/cli-integ/tests/cli-integ-tests/cli.integtest.ts
Labels: p2, contribution/core
