Repository aws/aws-cdk, pull requests merged in 2023-02, with the labels that each got.

#23913 chore: update cluster-engine to support latest postgres aurora version
  packages/@aws-cdk/aws-rds/lib/cluster-engine.ts
Labels: p2, beginning-contributor

#23943 chore(elasticsearch): remove elasticsearch legacy reference
  packages/@aws-cdk/aws-elasticsearch/README.md
Labels: p2, beginning-contributor

#23954 chore: npm-check-updates && yarn upgrade
  package.json
  packages/@aws-cdk/aws-eks/package.json
  packages/@aws-cdk/integ-runner/THIRD_PARTY_LICENSES
  packages/aws-cdk/THIRD_PARTY_LICENSES
  packages/aws-cdk/lib/init-templates/app/typescript/package.json
  packages/aws-cdk/lib/init-templates/lib/typescript/package.json
  packages/aws-cdk/lib/init-templates/sample-app/typescript/package.json
  tools/@aws-cdk/node-bundle/package.json
  yarn.lock
Labels: p2, dependencies, contribution/core, auto-approve

#23953 chore: npm-check-updates && yarn upgrade
  package.json
  packages/@aws-cdk/aws-apigatewayv2-authorizers/package.json
  packages/@aws-cdk/aws-certificatemanager/lambda-packages/dns_validated_certificate_handler/package.json
  packages/@aws-cdk/aws-cloudformation/package.json
  packages/@aws-cdk/aws-dynamodb/package.json
  packages/@aws-cdk/aws-ec2/package.json
  packages/@aws-cdk/aws-eks/package.json
  packages/@aws-cdk/aws-iam/package.json
  packages/@aws-cdk/aws-lambda-nodejs/package.json
  packages/@aws-cdk/aws-lambda/package.json
  packages/@aws-cdk/aws-logs/package.json
  packages/@aws-cdk/aws-route53/package.json
  packages/@aws-cdk/aws-s3/package.json
  packages/@aws-cdk/aws-ses/package.json
  packages/@aws-cdk/core/package.json
  packages/@aws-cdk/custom-resources/package.json
  packages/@aws-cdk/cx-api/package.json
  packages/@aws-cdk/integ-runner/THIRD_PARTY_LICENSES
  packages/aws-cdk-lib/package.json
  packages/aws-cdk/THIRD_PARTY_LICENSES
  packages/aws-cdk/package.json
  packages/awslint/package.json
  packages/cdk-dasm/package.json
  tools/@aws-cdk/cdk-build-tools/package.json
  tools/@aws-cdk/cfn2ts/package.json
  tools/@aws-cdk/node-bundle/package.json
  yarn.lock
Labels: p2, dependencies, contribution/core, auto-approve

#23960 chore: add label to stop bot from closing pr
  .github/workflows/close-stale-prs.yml
Labels: p2, contribution/core

#23962 chore: make ubergen a library
  tools/@aws-cdk/ubergen/bin/ubergen.ts
  tools/@aws-cdk/ubergen/lib/index.ts
  tools/@aws-cdk/ubergen/package.json
Labels: p2, contribution/core

#23968 feat(cfnspec): cloudformation spec v109.0.0
  packages/@aws-cdk/cfnspec/CHANGELOG.md
  packages/@aws-cdk/cfnspec/spec-source/specification/100_sam/000_official/spec.json
Labels: p2, pr-linter/exempt-test, auto-approve, pr-linter/exempt-integ-test

#23967 feat(cfnspec): cloudformation spec v109.0.0
  packages/@aws-cdk/cfnspec/CHANGELOG.md
  packages/@aws-cdk/cfnspec/spec-source/specification/100_sam/000_official/spec.json
Labels: p2, pr-linter/exempt-test, auto-approve, pr-linter/exempt-integ-test

#23961 chore(iam): correct spelling in documentation
  packages/@aws-cdk/aws-iam/lib/principals.ts
Labels: p2, beginning-contributor

#23971 chore(rds): support versions for postgresql
  packages/@aws-cdk/aws-rds/lib/cluster-engine.ts
  packages/@aws-cdk/aws-rds/lib/instance-engine.ts
Labels: p2, star-contributor

#23970 feat(remodel): generate index.ts and .jsiirc.json files
  tools/@aws-cdk/cfn2ts/lib/augmentation-generator.ts
  tools/@aws-cdk/cfn2ts/lib/canned-metrics-generator.ts
  tools/@aws-cdk/cfn2ts/lib/index.ts
  tools/@aws-cdk/remodel/lib/template/packages/aws-cdk-lib/scripts/gen.ts
Labels: p2, contribution/core

#23979 chore: add extra lib dir in each submodule
  tools/@aws-cdk/cfn2ts/lib/index.ts
Labels: p2, contribution/core

#23984 feat(cfnspec): cloudformation spec v109.0.0
  packages/@aws-cdk/aws-omics/.eslintrc.js
  packages/@aws-cdk/aws-omics/.gitignore
  packages/@aws-cdk/aws-omics/.npmignore
  packages/@aws-cdk/aws-omics/LICENSE
  packages/@aws-cdk/aws-omics/NOTICE
  packages/@aws-cdk/aws-omics/README.md
  packages/@aws-cdk/aws-omics/jest.config.js
  packages/@aws-cdk/aws-omics/lib/index.ts
  packages/@aws-cdk/aws-omics/package.json
  packages/@aws-cdk/aws-omics/rosetta/default.ts-fixture
  packages/@aws-cdk/aws-omics/test/omics.test.ts
  packages/@aws-cdk/aws-simspaceweaver/.eslintrc.js
  packages/@aws-cdk/aws-simspaceweaver/.gitignore
  packages/@aws-cdk/aws-simspaceweaver/.npmignore
  packages/@aws-cdk/aws-simspaceweaver/LICENSE
  packages/@aws-cdk/aws-simspaceweaver/NOTICE
  packages/@aws-cdk/aws-simspaceweaver/README.md
  packages/@aws-cdk/aws-simspaceweaver/jest.config.js
  packages/@aws-cdk/aws-simspaceweaver/lib/index.ts
  packages/@aws-cdk/aws-simspaceweaver/package.json
  packages/@aws-cdk/aws-simspaceweaver/rosetta/default.ts-fixture
  packages/@aws-cdk/aws-simspaceweaver/test/simspaceweaver.test.ts
  packages/@aws-cdk/cfnspec/CHANGELOG.md
  packages/@aws-cdk/cfnspec/spec-source/specification/000_cfn/000_official/000_AWS_AmplifyUIBuilder.json
  packages/@aws-cdk/cfnspec/spec-source/specification/000_cfn/000_official/000_AWS_AppConfig.json
  packages/@aws-cdk/cfnspec/spec-source/specification/000_cfn/000_official/000_AWS_CloudTrail.json
  packages/@aws-cdk/cfnspec/spec-source/specification/000_cfn/000_official/000_AWS_ConnectCampaigns.json
  packages/@aws-cdk/cfnspec/spec-source/specification/000_cfn/000_official/000_AWS_EC2.json
  packages/@aws-cdk/cfnspec/spec-source/specification/000_cfn/000_official/000_AWS_IoT.json
  packages/@aws-cdk/cfnspec/spec-source/specification/000_cfn/000_official/000_AWS_NetworkFirewall.json
  packages/@aws-cdk/cfnspec/spec-source/specification/000_cfn/000_official/000_AWS_NetworkManager.json
  packages/@aws-cdk/cfnspec/spec-source/specification/000_cfn/000_official/000_AWS_NimbleStudio.json
  packages/@aws-cdk/cfnspec/spec-source/specification/000_cfn/000_official/000_AWS_Omics.json
  packages/@aws-cdk/cfnspec/spec-source/specification/000_cfn/000_official/000_AWS_OpsWorksCM.json
  packages/@aws-cdk/cfnspec/spec-source/specification/000_cfn/000_official/000_AWS_RDS.json
  packages/@aws-cdk/cfnspec/spec-source/specification/000_cfn/000_official/000_AWS_RolesAnywhere.json
  packages/@aws-cdk/cfnspec/spec-source/specification/000_cfn/000_official/000_AWS_SNS.json
  packages/@aws-cdk/cfnspec/spec-source/specification/000_cfn/000_official/000_AWS_SageMaker.json
  packages/@aws-cdk/cfnspec/spec-source/specification/000_cfn/000_official/000_AWS_SimSpaceWeaver.json
  packages/@aws-cdk/cfnspec/spec-source/specification/000_cfn/000_official/000_AWS_WAFv2.json
  packages/@aws-cdk/cloudformation-include/package.json
  packages/aws-cdk-lib/package.json
Labels: p2, pr-linter/exempt-test, auto-approve, pr-linter/exempt-integ-test

#23983 feat(cfnspec): cloudformation spec v109.0.0
  packages/@aws-cdk/aws-omics/.eslintrc.js
  packages/@aws-cdk/aws-omics/.gitignore
  packages/@aws-cdk/aws-omics/.npmignore
  packages/@aws-cdk/aws-omics/LICENSE
  packages/@aws-cdk/aws-omics/NOTICE
  packages/@aws-cdk/aws-omics/README.md
  packages/@aws-cdk/aws-omics/jest.config.js
  packages/@aws-cdk/aws-omics/lib/index.ts
  packages/@aws-cdk/aws-omics/package.json
  packages/@aws-cdk/aws-omics/rosetta/default.ts-fixture
  packages/@aws-cdk/aws-omics/test/omics.test.ts
  packages/@aws-cdk/aws-simspaceweaver/.eslintrc.js
  packages/@aws-cdk/aws-simspaceweaver/.gitignore
  packages/@aws-cdk/aws-simspaceweaver/.npmignore
  packages/@aws-cdk/aws-simspaceweaver/LICENSE
  packages/@aws-cdk/aws-simspaceweaver/NOTICE
  packages/@aws-cdk/aws-simspaceweaver/README.md
  packages/@aws-cdk/aws-simspaceweaver/jest.config.js
  packages/@aws-cdk/aws-simspaceweaver/lib/index.ts
  packages/@aws-cdk/aws-simspaceweaver/package.json
  packages/@aws-cdk/aws-simspaceweaver/rosetta/default.ts-fixture
  packages/@aws-cdk/aws-simspaceweaver/test/simspaceweaver.test.ts
  packages/@aws-cdk/cfnspec/CHANGELOG.md
  packages/@aws-cdk/cfnspec/spec-source/specification/000_cfn/000_official/000_AWS_AmplifyUIBuilder.json
  packages/@aws-cdk/cfnspec/spec-source/specification/000_cfn/000_official/000_AWS_AppConfig.json
  packages/@aws-cdk/cfnspec/spec-source/specification/000_cfn/000_official/000_AWS_CloudTrail.json
  packages/@aws-cdk/cfnspec/spec-source/specification/000_cfn/000_official/000_AWS_ConnectCampaigns.json
  packages/@aws-cdk/cfnspec/spec-source/specification/000_cfn/000_official/000_AWS_EC2.json
  packages/@aws-cdk/cfnspec/spec-source/specification/000_cfn/000_official/000_AWS_IoT.json
  packages/@aws-cdk/cfnspec/spec-source/specification/000_cfn/000_official/000_AWS_NetworkFirewall.json
  packages/@aws-cdk/cfnspec/spec-source/specification/000_cfn/000_official/000_AWS_NetworkManager.json
  packages/@aws-cdk/cfnspec/spec-source/specification/000_cfn/000_official/000_AWS_NimbleStudio.json
  packages/@aws-cdk/cfnspec/spec-source/specification/000_cfn/000_official/000_AWS_Omics.json
  packages/@aws-cdk/cfnspec/spec-source/specification/000_cfn/000_official/000_AWS_OpsWorksCM.json
  packages/@aws-cdk/cfnspec/spec-source/specification/000_cfn/000_official/000_AWS_RDS.json
  packages/@aws-cdk/cfnspec/spec-source/specification/000_cfn/000_official/000_AWS_RolesAnywhere.json
  packages/@aws-cdk/cfnspec/spec-source/specification/000_cfn/000_official/000_AWS_SNS.json
  packages/@aws-cdk/cfnspec/spec-source/specification/000_cfn/000_official/000_AWS_SageMaker.json
  packages/@aws-cdk/cfnspec/spec-source/specification/000_cfn/000_official/000_AWS_SimSpaceWeaver.json
  packages/@aws-cdk/cfnspec/spec-source/specification/000_cfn/000_official/000_AWS_WAFv2.json
  packages/@aws-cdk/cloudformation-include/package.json
  packages/aws-cdk-lib/package.json
  packages/monocdk/package.json
Labels: p2, pr-linter/exempt-test, auto-approve, pr-linter/exempt-integ-test

#23847 feat(redshift): Tables can include comments
  packages/@aws-cdk/aws-redshift/README.md
  packages/@aws-cdk/aws-redshift/lib/private/database-query-provider/table.ts
  packages/@aws-cdk/aws-redshift/lib/private/handler-props.ts
  packages/@aws-cdk/aws-redshift/lib/table.ts
  packages/@aws-cdk/aws-redshift/test/database-query-provider/table.test.ts
  packages/@aws-cdk/aws-redshift/test/integ.database.js.snapshot/asset.8359857aa9b7c3fbc8bba9a505282ba848915383c4549f21b9f93f9f35b56415/table.js
  packages/@aws-cdk/aws-redshift/test/integ.database.js.snapshot/asset.ab58b1384030fef0fc8663c06f6fd62196fb3ae8807ab82e4559967d3b885b08/handler-name.js
  packages/@aws-cdk/aws-redshift/test/integ.database.js.snapshot/asset.ab58b1384030fef0fc8663c06f6fd62196fb3ae8807ab82e4559967d3b885b08/index.js
  packages/@aws-cdk/aws-redshift/test/integ.database.js.snapshot/asset.ab58b1384030fef0fc8663c06f6fd62196fb3ae8807ab82e4559967d3b885b08/privileges.js
  packages/@aws-cdk/aws-redshift/test/integ.database.js.snapshot/asset.ab58b1384030fef0fc8663c06f6fd62196fb3ae8807ab82e4559967d3b885b08/redshift-data.js
  packages/@aws-cdk/aws-redshift/test/integ.database.js.snapshot/asset.ab58b1384030fef0fc8663c06f6fd62196fb3ae8807ab82e4559967d3b885b08/table.js
  packages/@aws-cdk/aws-redshift/test/integ.database.js.snapshot/asset.ab58b1384030fef0fc8663c06f6fd62196fb3ae8807ab82e4559967d3b885b08/types.js
  packages/@aws-cdk/aws-redshift/test/integ.database.js.snapshot/asset.ab58b1384030fef0fc8663c06f6fd62196fb3ae8807ab82e4559967d3b885b08/user.js
  packages/@aws-cdk/aws-redshift/test/integ.database.js.snapshot/asset.ab58b1384030fef0fc8663c06f6fd62196fb3ae8807ab82e4559967d3b885b08/util.js
  packages/@aws-cdk/aws-redshift/test/integ.database.js.snapshot/aws-cdk-redshift-cluster-database.assets.json
  packages/@aws-cdk/aws-redshift/test/integ.database.js.snapshot/aws-cdk-redshift-cluster-database.template.json
  packages/@aws-cdk/aws-redshift/test/integ.database.js.snapshot/cdk.out
  packages/@aws-cdk/aws-redshift/test/integ.database.js.snapshot/integ.json
  packages/@aws-cdk/aws-redshift/test/integ.database.js.snapshot/manifest.json
  packages/@aws-cdk/aws-redshift/test/integ.database.js.snapshot/redshiftclusterdatabaseintegDefaultTestDeployAssert4339FB48.assets.json
  packages/@aws-cdk/aws-redshift/test/integ.database.js.snapshot/tree.json
  packages/@aws-cdk/aws-redshift/test/integ.database.ts
Labels: p2, feature-request, effort/small, beginning-contributor

#23986 fix(codedeploy): cross-region referenced groups use wrong config
  .gitallowed
  packages/@aws-cdk/aws-codedeploy/lib/ecs/deployment-group.ts
  packages/@aws-cdk/aws-codedeploy/lib/lambda/deployment-group.ts
  packages/@aws-cdk/aws-codedeploy/lib/private/base-deployment-group.ts
  packages/@aws-cdk/aws-codedeploy/lib/private/predefined-deployment-config.ts
  packages/@aws-cdk/aws-codedeploy/lib/private/utils.ts
  packages/@aws-cdk/aws-codedeploy/lib/server/deployment-group.ts
  packages/@aws-cdk/aws-codedeploy/test/ecs/deployment-group.test.ts
  packages/@aws-cdk/aws-codedeploy/test/lambda/deployment-group.test.ts
  packages/@aws-cdk/aws-codedeploy/test/server/deployment-group.test.ts
Labels: p2, contribution/core, pr-linter/exempt-integ-test

#23995 chore(release): v2.63.1
  CHANGELOG.v2.alpha.md
  CHANGELOG.v2.md
  packages/cdk-assets/lib/private/archive.ts
  version.v2.json
Labels: p2, contribution/core, pr/no-squash

#23999 chore(merge-back): 2.63.1
  CHANGELOG.v2.alpha.md
  CHANGELOG.v2.md
  version.v2.json
Labels: p2, pr/no-squash, auto-approve

#24006 chore: revert "chore(pipelines): write a GraphViz file with the pipeline structure (#23908)"
  packages/@aws-cdk/pipelines/lib/codepipeline/codepipeline.ts
  packages/@aws-cdk/pipelines/lib/helpers-internal/graph.ts
Labels: bug, p0, contribution/core

#24008 chore(release): 2.63.2
  CHANGELOG.v2.alpha.md
  CHANGELOG.v2.md
  packages/@aws-cdk/pipelines/lib/codepipeline/codepipeline.ts
  packages/@aws-cdk/pipelines/lib/helpers-internal/graph.ts
  version.v2.json
Labels: p2, contribution/core, pr/no-squash

#24012 chore(merge-back): 2.63.2
  CHANGELOG.v2.alpha.md
  CHANGELOG.v2.md
  version.v2.json
Labels: p2, pr/no-squash, auto-approve

#24026 fix(cdk-assets): asset concurrency leaves a corrupted archive
  packages/cdk-assets/lib/private/archive.ts
Labels: contribution/core, pr-linter/exempt-test, pr-linter/exempt-integ-test

#24030 chore(pipelines): write a GraphViz file with the pipeline structure
  packages/@aws-cdk/pipelines/lib/codepipeline/codepipeline.ts
  packages/@aws-cdk/pipelines/lib/helpers-internal/graph.ts
  packages/@aws-cdk/pipelines/lib/helpers-internal/toposort.ts
  packages/@aws-cdk/pipelines/test/codepipeline/codepipeline.test.ts
Labels: p2, contribution/core

#24010 docs(stepfunctions): Fix typo Langauge => Language
  packages/@aws-cdk/aws-stepfunctions/README.md
Labels: p2, repeat-contributor

#23744 feat(s3): allow configuring S3 Object Lock
  packages/@aws-cdk/aws-s3/README.md
  packages/@aws-cdk/aws-s3/lib/bucket.ts
  packages/@aws-cdk/aws-s3/test/bucket.test.ts
  packages/@aws-cdk/aws-s3/test/integ.bucket-object-lock.js.snapshot/ServerAccessLogsImportTestDefaultTestDeployAssert076DA7F5.assets.json
  packages/@aws-cdk/aws-s3/test/integ.bucket-object-lock.js.snapshot/ServerAccessLogsImportTestDefaultTestDeployAssert076DA7F5.template.json
  packages/@aws-cdk/aws-s3/test/integ.bucket-object-lock.js.snapshot/aws-cdk-s3-bucket-object-lock.assets.json
  packages/@aws-cdk/aws-s3/test/integ.bucket-object-lock.js.snapshot/aws-cdk-s3-bucket-object-lock.template.json
  packages/@aws-cdk/aws-s3/test/integ.bucket-object-lock.js.snapshot/cdk.out
  packages/@aws-cdk/aws-s3/test/integ.bucket-object-lock.js.snapshot/integ.json
  packages/@aws-cdk/aws-s3/test/integ.bucket-object-lock.js.snapshot/manifest.json
  packages/@aws-cdk/aws-s3/test/integ.bucket-object-lock.js.snapshot/tree.json
  packages/@aws-cdk/aws-s3/test/integ.bucket-object-lock.ts
Labels: p2

#23891 feat(lambda): enable RuntimeManagementConfig
  packages/@aws-cdk/aws-lambda/README.md
  packages/@aws-cdk/aws-lambda/lib/adot-layers.ts
  packages/@aws-cdk/aws-lambda/lib/function.ts
  packages/@aws-cdk/aws-lambda/lib/index.ts
  packages/@aws-cdk/aws-lambda/lib/runtime-management.ts
  packages/@aws-cdk/aws-lambda/package.json
  packages/@aws-cdk/aws-lambda/test/integ.runtime-management.js.snapshot/aws-cdk-lambda-runtime-management.assets.json
  packages/@aws-cdk/aws-lambda/test/integ.runtime-management.js.snapshot/aws-cdk-lambda-runtime-management.template.json
  packages/@aws-cdk/aws-lambda/test/integ.runtime-management.js.snapshot/cdk.out
  packages/@aws-cdk/aws-lambda/test/integ.runtime-management.js.snapshot/integ.json
  packages/@aws-cdk/aws-lambda/test/integ.runtime-management.js.snapshot/lambdaruntimemanagementDefaultTestDeployAssertDE680AF3.assets.json
  packages/@aws-cdk/aws-lambda/test/integ.runtime-management.js.snapshot/lambdaruntimemanagementDefaultTestDeployAssertDE680AF3.template.json
  packages/@aws-cdk/aws-lambda/test/integ.runtime-management.js.snapshot/manifest.json
  packages/@aws-cdk/aws-lambda/test/integ.runtime-management.js.snapshot/tree.json
  packages/@aws-cdk/aws-lambda/test/integ.runtime-management.ts
  packages/@aws-cdk/aws-lambda/test/runtime-management.test.ts
Labels: p2, feature-request, star-contributor

#24027 fix(pipelines): cannot configure actionName for all sources
  packages/@aws-cdk/pipelines/lib/codepipeline/codepipeline-source.ts
  packages/@aws-cdk/pipelines/test/codepipeline/codepipeline-sources.test.ts
Labels: p2, contribution/core, pr-linter/exempt-integ-test

#24052 chore: fix only docker can be used in some helper scripts
  packages/@aws-cdk/aws-s3-deployment/test/lambda/debug.sh
  packages/@aws-cdk/aws-s3-deployment/test/lambda/test.sh
Labels: p2, contribution/core

#23987 fix(core): cross-stack reference error doesn't include violation
  packages/@aws-cdk/core/lib/private/refs.ts
  packages/@aws-cdk/core/test/stack.test.ts
Labels: p2, contribution/core, pr-linter/exempt-integ-test

#24056 docs(synthetics): reference to incorrect property name
  packages/@aws-cdk/aws-synthetics/README.md
Labels: p2, contribution/core

#23823 fix(servicecatalogappregistry): default stack name is not meaningful and causes conflict when multiple stacks deployed to the same account-region
  packages/@aws-cdk/aws-servicecatalogappregistry/lib/aspects/stack-associator.ts
  packages/@aws-cdk/aws-servicecatalogappregistry/lib/target-application.ts
  packages/@aws-cdk/aws-servicecatalogappregistry/package.json
  packages/@aws-cdk/aws-servicecatalogappregistry/test/application-associator.test.ts
  packages/@aws-cdk/aws-servicecatalogappregistry/test/integ.application-associator.all-stacks-association-no-stack-name.js.snapshot/ApplicationAssociatorStack.assets.json
  packages/@aws-cdk/aws-servicecatalogappregistry/test/integ.application-associator.all-stacks-association-no-stack-name.js.snapshot/ApplicationAssociatorStack.template.json
  packages/@aws-cdk/aws-servicecatalogappregistry/test/integ.application-associator.all-stacks-association-no-stack-name.js.snapshot/ApplicationAssociatorTestDefaultTestDeployAssert2A5F2DB9.assets.json
  packages/@aws-cdk/aws-servicecatalogappregistry/test/integ.application-associator.all-stacks-association-no-stack-name.js.snapshot/ApplicationAssociatorTestDefaultTestDeployAssert2A5F2DB9.template.json
  packages/@aws-cdk/aws-servicecatalogappregistry/test/integ.application-associator.all-stacks-association-no-stack-name.js.snapshot/cdk.out
  packages/@aws-cdk/aws-servicecatalogappregistry/test/integ.application-associator.all-stacks-association-no-stack-name.js.snapshot/integ-servicecatalogappregistry-application.assets.json
  packages/@aws-cdk/aws-servicecatalogappregistry/test/integ.application-associator.all-stacks-association-no-stack-name.js.snapshot/integ-servicecatalogappregistry-application.template.json
  packages/@aws-cdk/aws-servicecatalogappregistry/test/integ.application-associator.all-stacks-association-no-stack-name.js.snapshot/integ.json
  packages/@aws-cdk/aws-servicecatalogappregistry/test/integ.application-associator.all-stacks-association-no-stack-name.js.snapshot/integservicecatalogappregistryapplicationresourcesStack4399A149.assets.json
  packages/@aws-cdk/aws-servicecatalogappregistry/test/integ.application-associator.all-stacks-association-no-stack-name.js.snapshot/integservicecatalogappregistryapplicationresourcesStack4399A149.template.json
  packages/@aws-cdk/aws-servicecatalogappregistry/test/integ.application-associator.all-stacks-association-no-stack-name.js.snapshot/manifest.json
  packages/@aws-cdk/aws-servicecatalogappregistry/test/integ.application-associator.all-stacks-association-no-stack-name.js.snapshot/tree.json
  packages/@aws-cdk/aws-servicecatalogappregistry/test/integ.application-associator.all-stacks-association-no-stack-name.ts
Labels: p2, beginning-contributor

#23878 feat(cloud9): support setting environment owner
  packages/@aws-cdk/aws-cloud9/README.md
  packages/@aws-cdk/aws-cloud9/lib/environment.ts
  packages/@aws-cdk/aws-cloud9/package.json
  packages/@aws-cdk/aws-cloud9/test/cloud9.environment.test.ts
Labels: bug, p2, effort/small, contribution/core, pr-linter/exempt-integ-test

#23653 feat(cli): --hotswap will not use CFN anymore, --hotswap-fallback to fall back if necessary
  packages/aws-cdk/README.md
  packages/aws-cdk/lib/api/cloudformation-deployments.ts
  packages/aws-cdk/lib/api/deploy-stack.ts
  packages/aws-cdk/lib/api/hotswap-deployments.ts
  packages/aws-cdk/lib/api/hotswap/appsync-mapping-templates.ts
  packages/aws-cdk/lib/api/hotswap/code-build-projects.ts
  packages/aws-cdk/lib/api/hotswap/common.ts
  packages/aws-cdk/lib/api/hotswap/ecs-services.ts
  packages/aws-cdk/lib/api/hotswap/lambda-functions.ts
  packages/aws-cdk/lib/api/hotswap/s3-bucket-deployments.ts
  packages/aws-cdk/lib/api/hotswap/stepfunctions-state-machines.ts
  packages/aws-cdk/lib/cdk-toolkit.ts
  packages/aws-cdk/lib/cli.ts
  packages/aws-cdk/test/api/cloudformation-deployments.test.ts
  packages/aws-cdk/test/api/deploy-stack.test.ts
  packages/aws-cdk/test/api/hotswap/appsync-mapping-templates-hotswap-deployments.test.ts
  packages/aws-cdk/test/api/hotswap/code-build-projects-hotswap-deployments.test.ts
  packages/aws-cdk/test/api/hotswap/ecs-services-hotswap-deployments.test.ts
  packages/aws-cdk/test/api/hotswap/hotswap-deployments.test.ts
  packages/aws-cdk/test/api/hotswap/hotswap-test-setup.ts
  packages/aws-cdk/test/api/hotswap/lambda-functions-docker-hotswap-deployments.test.ts
  packages/aws-cdk/test/api/hotswap/lambda-functions-hotswap-deployments.test.ts
  packages/aws-cdk/test/api/hotswap/lambda-functions-inline-hotswap-deployments.test.ts
  packages/aws-cdk/test/api/hotswap/lambda-versions-aliases-hotswap-deployments.test.ts
  packages/aws-cdk/test/api/hotswap/nested-stacks-hotswap.test.ts
  packages/aws-cdk/test/api/hotswap/s3-bucket-hotswap-deployments.test.ts
  packages/aws-cdk/test/api/hotswap/state-machine-hotswap-deployments.test.ts
  packages/aws-cdk/test/cdk-toolkit.test.ts
Labels: p2, feature-request, effort/small, contribution/core, pr-linter/exempt-integ-test, pr-linter/cli-integ-tested

#23972 fix: Use the correct LB full name when creating metrics for imported LBs
  packages/@aws-cdk/aws-elasticloadbalancingv2/lib/shared/util.ts
  packages/@aws-cdk/aws-elasticloadbalancingv2/test/integ.nlb-lookup.js.snapshot/aws-cdk-elbv2-StackWithLb.assets.json
  packages/@aws-cdk/aws-elasticloadbalancingv2/test/integ.nlb-lookup.js.snapshot/aws-cdk-elbv2-StackWithLb.template.json
  packages/@aws-cdk/aws-elasticloadbalancingv2/test/integ.nlb-lookup.js.snapshot/aws-cdk-elbv2-integ-StackUnderTest.assets.json
  packages/@aws-cdk/aws-elasticloadbalancingv2/test/integ.nlb-lookup.js.snapshot/aws-cdk-elbv2-integ-StackUnderTest.template.json
  packages/@aws-cdk/aws-elasticloadbalancingv2/test/integ.nlb-lookup.js.snapshot/integ.json
  packages/@aws-cdk/aws-elasticloadbalancingv2/test/integ.nlb-lookup.js.snapshot/manifest.json
  packages/@aws-cdk/aws-elasticloadbalancingv2/test/integ.nlb-lookup.js.snapshot/tree.json
  packages/@aws-cdk/aws-elasticloadbalancingv2/test/integ.nlb-lookup.ts
Labels: p2, beginning-contributor

#24081 chore(merge-back): 2.64.0
  CHANGELOG.v2.alpha.md
  CHANGELOG.v2.md
  version.v2.json
Labels: p2, pr/no-squash, auto-approve

#24082 chore(merge-back): 1.192.0
  CHANGELOG.md
  version.v1.json
Labels: p2, pr/no-squash, auto-approve

#24019 fix(core): messages are displayed multiple times per construct
  packages/@aws-cdk/core/lib/annotations.ts
  packages/@aws-cdk/core/test/annotations.test.ts
Labels: bug, p2, effort/small, pr-linter/exempt-integ-test, beginning-contributor

#24071 docs(lambda-layers): point to alternative versions
  packages/@aws-cdk/lambda-layer-awscli/README.md
  packages/@aws-cdk/lambda-layer-kubectl/README.md
Labels: p2, contribution/core

#23978 feat(remodel): Create or add to top-level index.ts and package.json exports during gen
  tools/@aws-cdk/cfn2ts/lib/index.ts
  tools/@aws-cdk/pkglint/lib/library-creation.ts
  tools/@aws-cdk/remodel/lib/template/packages/aws-cdk-lib/scripts/gen.ts
Labels: p2, contribution/core

#23778 feat(core): Allow passing Docker build secrets
  packages/@aws-cdk/aws-ecr-assets/README.md
  packages/@aws-cdk/aws-ecr-assets/lib/image-asset.ts
  packages/@aws-cdk/aws-ecr-assets/test/demo-image-secret/Dockerfile
  packages/@aws-cdk/aws-ecr-assets/test/demo-image-secret/index.py
  packages/@aws-cdk/aws-ecr-assets/test/image-asset.test.ts
  packages/@aws-cdk/aws-ecr-assets/test/integ.assets-docker.js.snapshot/asset.60dea2e16e94d1977b92fe03fa7085fea446233f1fe499702b69593438baa59f/Dockerfile
  packages/@aws-cdk/aws-ecr-assets/test/integ.assets-docker.js.snapshot/asset.60dea2e16e94d1977b92fe03fa7085fea446233f1fe499702b69593438baa59f/index.py
  packages/@aws-cdk/aws-ecr-assets/test/integ.assets-docker.js.snapshot/cdk.out
  packages/@aws-cdk/aws-ecr-assets/test/integ.assets-docker.js.snapshot/integ-assets-docker.assets.json
  packages/@aws-cdk/aws-ecr-assets/test/integ.assets-docker.js.snapshot/integ-assets-docker.template.json
  packages/@aws-cdk/aws-ecr-assets/test/integ.assets-docker.js.snapshot/integ.json
  packages/@aws-cdk/aws-ecr-assets/test/integ.assets-docker.js.snapshot/manifest.json
  packages/@aws-cdk/aws-ecr-assets/test/integ.assets-docker.js.snapshot/tree.json
  packages/@aws-cdk/aws-ecr-assets/test/integ.assets-docker.ts
  packages/@aws-cdk/aws-ecr-assets/test/integ.nested-stacks-docker.js.snapshot/cdk.out
  packages/@aws-cdk/aws-ecr-assets/test/integ.nested-stacks-docker.js.snapshot/integ.json
  packages/@aws-cdk/aws-ecr-assets/test/integ.nested-stacks-docker.js.snapshot/manifest.json
  packages/@aws-cdk/aws-ecr-assets/test/integ.nested-stacks-docker.js.snapshot/nested-stacks-docker.assets.json
  packages/@aws-cdk/aws-ecr-assets/test/integ.nested-stacks-docker.js.snapshot/tree.json
  packages/@aws-cdk/cloud-assembly-schema/lib/assets/docker-image-asset.ts
  packages/@aws-cdk/cloud-assembly-schema/lib/cloud-assembly/metadata-schema.ts
  packages/@aws-cdk/cloud-assembly-schema/schema/assets.schema.json
  packages/@aws-cdk/cloud-assembly-schema/schema/cloud-assembly.schema.json
  packages/@aws-cdk/cloud-assembly-schema/schema/cloud-assembly.version.json
  packages/@aws-cdk/core/lib/assets.ts
  packages/@aws-cdk/core/lib/bundling.ts
  packages/@aws-cdk/core/lib/stack-synthesizers/asset-manifest-builder.ts
  packages/@aws-cdk/core/test/bundling.test.ts
  packages/@aws-cdk/core/test/stack-synthesis/new-style-synthesis.test.ts
  packages/@aws-cdk/cx-api/lib/assets.ts
  packages/cdk-assets/lib/private/docker.ts
  packages/cdk-assets/lib/private/handlers/container-images.ts
Labels: p1, feature-request, effort/small, beginning-contributor

#24053 fix(codepipeline): x-env ECS deployment lacking support stack-dependency
  packages/@aws-cdk/aws-codepipeline-actions/lib/codedeploy/ecs-deploy-action.ts
  packages/@aws-cdk/aws-codepipeline-actions/lib/private/stack-dependency.ts
  packages/@aws-cdk/aws-codepipeline-actions/test/codedeploy/ecs-deploy-action.test.ts
  packages/@aws-cdk/aws-ecs-patterns/test/ec2/integ.healthchecks-multiple-application-load-balanced-ecs-service.ts
  packages/@aws-cdk/aws-ecs-patterns/test/ec2/integ.healthchecks-multiple-network-load-balanced-ecs-service.ts
  packages/@aws-cdk/aws-ecs-patterns/test/fargate/integ.healthchecks-multiple-application-load-balanced-fargate-service.ts
  packages/@aws-cdk/aws-ecs-patterns/test/fargate/integ.healthchecks-multiple-network-load-balanced-fargate-service.ts
  packages/@aws-cdk/core/lib/cfn-resource.ts
  packages/@aws-cdk/core/lib/stack.ts
  packages/@aws-cdk/core/test/stack.test.ts
Labels: p2, contribution/core, pr-linter/exempt-integ-test

#23514 fix(s3): logging bucket blocks KMS_MANAGED encryption
  packages/@aws-cdk/aws-s3/lib/bucket.ts
  packages/@aws-cdk/aws-s3/test/bucket.test.ts
Labels: bug, p1, effort/small, pr-linter/exempt-integ-test, beginning-contributor

#24034 fix(iam): SamlConsolePrincipal does not work in China #22091
  packages/@aws-cdk/aws-iam/lib/principals.ts
  packages/@aws-cdk/aws-iam/test/integ.saml-provider.js.snapshot/cdk-saml-provider.assets.json
  packages/@aws-cdk/aws-iam/test/integ.saml-provider.js.snapshot/cdk-saml-provider.template.json
  packages/@aws-cdk/aws-iam/test/integ.saml-provider.js.snapshot/cdk.out
  packages/@aws-cdk/aws-iam/test/integ.saml-provider.js.snapshot/integ.json
  packages/@aws-cdk/aws-iam/test/integ.saml-provider.js.snapshot/manifest.json
  packages/@aws-cdk/aws-iam/test/integ.saml-provider.js.snapshot/tree.json
  packages/@aws-cdk/aws-iam/test/integ.saml-provider.ts
  packages/@aws-cdk/aws-iam/test/principals.test.ts
Labels: bug, p1, effort/small, beginning-contributor

#24025 feat(autoscaling): L2 construct for enabling capacity rebalance of autoscaling
  packages/@aws-cdk/aws-autoscaling/README.md
  packages/@aws-cdk/aws-autoscaling/lib/auto-scaling-group.ts
  packages/@aws-cdk/aws-autoscaling/test/auto-scaling-group.test.ts
  packages/@aws-cdk/aws-autoscaling/test/integ.asg-capacity-rebalance.js.snapshot/CapacityRebalanceTestDefaultTestDeployAssert759ED6BE.assets.json
  packages/@aws-cdk/aws-autoscaling/test/integ.asg-capacity-rebalance.js.snapshot/CapacityRebalanceTestDefaultTestDeployAssert759ED6BE.template.json
  packages/@aws-cdk/aws-autoscaling/test/integ.asg-capacity-rebalance.js.snapshot/aws-cdk-autoscaling-integ.assets.json
  packages/@aws-cdk/aws-autoscaling/test/integ.asg-capacity-rebalance.js.snapshot/aws-cdk-autoscaling-integ.template.json
  packages/@aws-cdk/aws-autoscaling/test/integ.asg-capacity-rebalance.js.snapshot/cdk.out
  packages/@aws-cdk/aws-autoscaling/test/integ.asg-capacity-rebalance.js.snapshot/integ.json
  packages/@aws-cdk/aws-autoscaling/test/integ.asg-capacity-rebalance.js.snapshot/manifest.json
  packages/@aws-cdk/aws-autoscaling/test/integ.asg-capacity-rebalance.js.snapshot/tree.json
  packages/@aws-cdk/aws-autoscaling/test/integ.asg-capacity-rebalance.ts
Labels: p2, feature-request, effort/small, beginning-contributor

#24018 docs(aipgatewayv2): HttpUrl example uses private TLD
  packages/@aws-cdk/aws-apigatewayv2-authorizers/README.md
  packages/@aws-cdk/aws-apigatewayv2-integrations/README.md
  packages/@aws-cdk/aws-apigatewayv2/README.md
Labels: p2, effort/small, beginning-contributor

#24098 docs(stepfunctions-tasks): description for ecs run task with imported
  packages/@aws-cdk/aws-stepfunctions-tasks/lib/ecs/run-ecs-task-base.ts
  packages/@aws-cdk/aws-stepfunctions-tasks/lib/ecs/run-task.ts
Labels: p2, beginning-contributor

#24095 chore: add labels to pr based off comment content and labels already added
  .github/workflows/pr-linter-exemption-labeler.yml
  tools/@aws-cdk/prlint/lint.ts
  tools/@aws-cdk/prlint/test/lint.test.ts
Labels: p2, contribution/core

#24100 chore(pipelines): inspect whether pipeline has selfMutation enabled
  packages/@aws-cdk/pipelines/lib/codepipeline/codepipeline.ts
  packages/@aws-cdk/pipelines/test/codepipeline/codepipeline.test.ts
Labels: p2, contribution/core

#24115 docs: change api reference link from v1 to v2.
  README.md
Labels: p2, contribution/core

#24118 fix(ec2): enable set throughput param to CfnVolume
  packages/@aws-cdk/aws-ec2/lib/volume.ts
  packages/@aws-cdk/aws-ec2/test/integ.volume.js.snapshot/VolumeTestDefaultTestDeployAssert896AAE82.assets.json
  packages/@aws-cdk/aws-ec2/test/integ.volume.js.snapshot/VolumeTestDefaultTestDeployAssert896AAE82.template.json
  packages/@aws-cdk/aws-ec2/test/integ.volume.js.snapshot/aws-cdk-ec2-volume-1.assets.json
  packages/@aws-cdk/aws-ec2/test/integ.volume.js.snapshot/aws-cdk-ec2-volume-1.template.json
  packages/@aws-cdk/aws-ec2/test/integ.volume.js.snapshot/cdk.out
  packages/@aws-cdk/aws-ec2/test/integ.volume.js.snapshot/integ.json
  packages/@aws-cdk/aws-ec2/test/integ.volume.js.snapshot/manifest.json
  packages/@aws-cdk/aws-ec2/test/integ.volume.js.snapshot/tree.json
  packages/@aws-cdk/aws-ec2/test/integ.volume.ts
  packages/@aws-cdk/aws-ec2/test/integ.volume.ts.snapshot/VolumeTestDefaultTestDeployAssert896AAE82.assets.json
  packages/@aws-cdk/aws-ec2/test/integ.volume.ts.snapshot/VolumeTestDefaultTestDeployAssert896AAE82.template.json
  packages/@aws-cdk/aws-ec2/test/integ.volume.ts.snapshot/aws-cdk-ec2-volume-1.assets.json
  packages/@aws-cdk/aws-ec2/test/integ.volume.ts.snapshot/aws-cdk-ec2-volume-1.template.json
  packages/@aws-cdk/aws-ec2/test/integ.volume.ts.snapshot/cdk.out
  packages/@aws-cdk/aws-ec2/test/integ.volume.ts.snapshot/integ.json
  packages/@aws-cdk/aws-ec2/test/integ.volume.ts.snapshot/manifest.json
  packages/@aws-cdk/aws-ec2/test/integ.volume.ts.snapshot/tree.json
  packages/@aws-cdk/aws-ec2/test/volume.test.ts
Labels: bug, p1, effort/small, beginning-contributor

#24117 docs(stepfunctions): Update Step Functions Job Poller example
  packages/@aws-cdk/aws-stepfunctions/README.md
Labels: p2, repeat-contributor

#24114 feat(chatbot): support guardrail policies
  packages/@aws-cdk/aws-chatbot/README.md
  packages/@aws-cdk/aws-chatbot/lib/slack-channel-configuration.ts
  packages/@aws-cdk/aws-chatbot/test/integ.chatbot-guardrails.js.snapshot/ChatbotGuardrailsInteg.assets.json
  packages/@aws-cdk/aws-chatbot/test/integ.chatbot-guardrails.js.snapshot/ChatbotGuardrailsInteg.template.json
  packages/@aws-cdk/aws-chatbot/test/integ.chatbot-guardrails.js.snapshot/cdk.out
  packages/@aws-cdk/aws-chatbot/test/integ.chatbot-guardrails.js.snapshot/manifest.json
  packages/@aws-cdk/aws-chatbot/test/integ.chatbot-guardrails.js.snapshot/tree.json
  packages/@aws-cdk/aws-chatbot/test/integ.chatbot-guardrails.ts
  packages/@aws-cdk/aws-chatbot/test/slack-channel-configuration.test.ts
Labels: p2, feature-request, beginning-contributor

#24101 feat(synthetics): support runtime 3.9
  packages/@aws-cdk/aws-synthetics/README.md
  packages/@aws-cdk/aws-synthetics/lib/runtime.ts
  packages/@aws-cdk/aws-synthetics/test/integ.canary.js.snapshot/canary-one.template.json
  packages/@aws-cdk/aws-synthetics/test/integ.canary.js.snapshot/tree.json
  packages/@aws-cdk/aws-synthetics/test/integ.canary.ts
  packages/@aws-cdk/aws-synthetics/test/integ.vpc.js.snapshot/canary-vpc.assets.json
  packages/@aws-cdk/aws-synthetics/test/integ.vpc.js.snapshot/cdk.out
  packages/@aws-cdk/aws-synthetics/test/integ.vpc.js.snapshot/integ.json
  packages/@aws-cdk/aws-synthetics/test/integ.vpc.js.snapshot/manifest.json
  packages/@aws-cdk/aws-synthetics/test/integ.vpc.js.snapshot/tree.json
Labels: p2, contribution/core

#23782 fix(iam): PrincipalWithConditions.addCondition fails with a new key
  packages/@aws-cdk/aws-iam/lib/principals.ts
  packages/@aws-cdk/aws-iam/test/integ.principal-with-conditions.js.snapshot/PrincipalWithConditionDefaultTestDeployAssertA4D5A2E9.assets.json
  packages/@aws-cdk/aws-iam/test/integ.principal-with-conditions.js.snapshot/PrincipalWithConditionDefaultTestDeployAssertA4D5A2E9.template.json
  packages/@aws-cdk/aws-iam/test/integ.principal-with-conditions.js.snapshot/cdk.out
  packages/@aws-cdk/aws-iam/test/integ.principal-with-conditions.js.snapshot/integ-principal-with-conditions.assets.json
  packages/@aws-cdk/aws-iam/test/integ.principal-with-conditions.js.snapshot/integ-principal-with-conditions.template.json
  packages/@aws-cdk/aws-iam/test/integ.principal-with-conditions.js.snapshot/integ.json
  packages/@aws-cdk/aws-iam/test/integ.principal-with-conditions.js.snapshot/manifest.json
  packages/@aws-cdk/aws-iam/test/integ.principal-with-conditions.js.snapshot/tree.json
  packages/@aws-cdk/aws-iam/test/integ.principal-with-conditions.ts
  packages/@aws-cdk/aws-iam/test/principals.test.ts
Labels: bug, p2, beginning-contributor

#24007 chore(custom-resources): AwsCustomResource - export provider lambda uuid
  packages/@aws-cdk/custom-resources/lib/aws-custom-resource/aws-custom-resource.ts
Labels: p2, feature-request, effort/small, beginning-contributor

#24110 chore(region-info): register eu-central-2
  packages/@aws-cdk/aws-iot-actions/test/kinesis-firehose/integ.firehose-put-record-action.js.snapshot/cdk.out
  packages/@aws-cdk/aws-iot-actions/test/kinesis-firehose/integ.firehose-put-record-action.js.snapshot/integ.json
  packages/@aws-cdk/aws-iot-actions/test/kinesis-firehose/integ.firehose-put-record-action.js.snapshot/manifest.json
  packages/@aws-cdk/aws-iot-actions/test/kinesis-firehose/integ.firehose-put-record-action.js.snapshot/test-stack.assets.json
  packages/@aws-cdk/aws-iot-actions/test/kinesis-firehose/integ.firehose-put-record-action.js.snapshot/test-stack.template.json
  packages/@aws-cdk/aws-iot-actions/test/kinesis-firehose/integ.firehose-put-record-action.js.snapshot/tree.json
  packages/@aws-cdk/aws-kinesisfirehose-destinations/test/integ.s3-bucket.lit.js.snapshot/asset.33e2651435a0d472a75c1e033c9832b21321d9e56711926b04c5705e5f63874c/__entrypoint__.js
  packages/@aws-cdk/aws-kinesisfirehose-destinations/test/integ.s3-bucket.lit.js.snapshot/asset.33e2651435a0d472a75c1e033c9832b21321d9e56711926b04c5705e5f63874c/index.js
  packages/@aws-cdk/aws-kinesisfirehose-destinations/test/integ.s3-bucket.lit.js.snapshot/asset.bb426cfb5fed5237e5928f871893b243ddf86a591a592b558bd29f60e28bad9d/index.d.ts
  packages/@aws-cdk/aws-kinesisfirehose-destinations/test/integ.s3-bucket.lit.js.snapshot/asset.bb426cfb5fed5237e5928f871893b243ddf86a591a592b558bd29f60e28bad9d/index.ts
  packages/@aws-cdk/aws-kinesisfirehose-destinations/test/integ.s3-bucket.lit.js.snapshot/asset.fe1ae9f614deb9ad8681131e8d3ebb6f23ae0c8f1f589d433c09881ad327487f/index.js
  packages/@aws-cdk/aws-kinesisfirehose-destinations/test/integ.s3-bucket.lit.js.snapshot/aws-cdk-firehose-delivery-stream-s3-all-properties.assets.json
  packages/@aws-cdk/aws-kinesisfirehose-destinations/test/integ.s3-bucket.lit.js.snapshot/aws-cdk-firehose-delivery-stream-s3-all-properties.template.json
  packages/@aws-cdk/aws-kinesisfirehose-destinations/test/integ.s3-bucket.lit.js.snapshot/cdk.out
  packages/@aws-cdk/aws-kinesisfirehose-destinations/test/integ.s3-bucket.lit.js.snapshot/integ.json
  packages/@aws-cdk/aws-kinesisfirehose-destinations/test/integ.s3-bucket.lit.js.snapshot/manifest.json
  packages/@aws-cdk/aws-kinesisfirehose-destinations/test/integ.s3-bucket.lit.js.snapshot/tree.json
  packages/@aws-cdk/aws-kinesisfirehose/test/integ.delivery-stream.js.snapshot/aws-cdk-firehose-delivery-stream.assets.json
  packages/@aws-cdk/aws-kinesisfirehose/test/integ.delivery-stream.js.snapshot/aws-cdk-firehose-delivery-stream.template.json
  packages/@aws-cdk/aws-kinesisfirehose/test/integ.delivery-stream.js.snapshot/cdk.out
  packages/@aws-cdk/aws-kinesisfirehose/test/integ.delivery-stream.js.snapshot/integ.json
  packages/@aws-cdk/aws-kinesisfirehose/test/integ.delivery-stream.js.snapshot/manifest.json
  packages/@aws-cdk/aws-kinesisfirehose/test/integ.delivery-stream.js.snapshot/tree.json
  packages/@aws-cdk/aws-kinesisfirehose/test/integ.delivery-stream.source-stream.js.snapshot/aws-cdk-firehose-delivery-stream-source-stream.assets.json
  packages/@aws-cdk/aws-kinesisfirehose/test/integ.delivery-stream.source-stream.js.snapshot/aws-cdk-firehose-delivery-stream-source-stream.template.json
  packages/@aws-cdk/aws-kinesisfirehose/test/integ.delivery-stream.source-stream.js.snapshot/cdk.out
  packages/@aws-cdk/aws-kinesisfirehose/test/integ.delivery-stream.source-stream.js.snapshot/integ.json
  packages/@aws-cdk/aws-kinesisfirehose/test/integ.delivery-stream.source-stream.js.snapshot/manifest.json
  packages/@aws-cdk/aws-kinesisfirehose/test/integ.delivery-stream.source-stream.js.snapshot/tree.json
  packages/@aws-cdk/aws-s3-deployment/test/integ.bucket-deployment-deployed-bucket.js.snapshot/cdk.out
  packages/@aws-cdk/aws-s3-deployment/test/integ.bucket-deployment-deployed-bucket.js.snapshot/integ.json
  packages/@aws-cdk/aws-s3-deployment/test/integ.bucket-deployment-deployed-bucket.js.snapshot/integtestbucketdeploymentsDefaultTestDeployAssertCF25A2DF.assets.json
  packages/@aws-cdk/aws-s3-deployment/test/integ.bucket-deployment-deployed-bucket.js.snapshot/manifest.json
  packages/@aws-cdk/aws-s3-deployment/test/integ.bucket-deployment-deployed-bucket.js.snapshot/test-bucket-deployment-deployed-bucket.assets.json
  packages/@aws-cdk/aws-s3-deployment/test/integ.bucket-deployment-deployed-bucket.js.snapshot/test-bucket-deployment-deployed-bucket.template.json
  packages/@aws-cdk/aws-s3-deployment/test/integ.bucket-deployment-deployed-bucket.js.snapshot/tree.json
  packages/@aws-cdk/region-info/build-tools/fact-tables.ts
  packages/@aws-cdk/region-info/lib/aws-entities.ts
  packages/@aws-cdk/region-info/test/__snapshots__/region-info.test.js.snap
Labels: p2, contribution/core

#24121 chore(region-info): register eu-south-2
  packages/@aws-cdk/aws-iot-actions/test/kinesis-firehose/integ.firehose-put-record-action.js.snapshot/test-stack.template.json
  packages/@aws-cdk/aws-kinesisfirehose-destinations/test/integ.s3-bucket.lit.js.snapshot/aws-cdk-firehose-delivery-stream-s3-all-properties.template.json
  packages/@aws-cdk/aws-kinesisfirehose/test/integ.delivery-stream.js.snapshot/aws-cdk-firehose-delivery-stream.template.json
  packages/@aws-cdk/aws-kinesisfirehose/test/integ.delivery-stream.source-stream.js.snapshot/aws-cdk-firehose-delivery-stream-source-stream.template.json
  packages/@aws-cdk/region-info/build-tools/fact-tables.ts
Labels: p1, feature-request, effort/medium, beginning-contributor

#24091 chore(cli-integ): try to fix some integ test failures
  packages/@aws-cdk-testing/cli-integ/bin/run-suite.ts
  packages/@aws-cdk-testing/cli-integ/lib/integ-test.ts
  packages/@aws-cdk-testing/cli-integ/lib/with-aws.ts
  packages/@aws-cdk-testing/cli-integ/lib/with-cdk-app.ts
  packages/@aws-cdk-testing/cli-integ/lib/with-sam.ts
  packages/@aws-cdk-testing/cli-integ/resources/cdk-apps/app/app.js
  packages/@aws-cdk-testing/cli-integ/tests/cli-integ-tests/bootstrapping.integtest.ts
Labels: p2, contribution/core, pr-linter/cli-integ-tested

#24127 chore: add TimeZones class
  packages/@aws-cdk/core/lib/index.ts
  packages/@aws-cdk/core/lib/time-zone.ts
  packages/@aws-cdk/core/test/time-zone.test.ts
Labels: p2, contribution/core

#24128 chore: delete app-delivery module
  .github/workflows/issue-label-assign.yml
  packages/@aws-cdk/app-delivery/.eslintrc.js
  packages/@aws-cdk/app-delivery/.gitignore
  packages/@aws-cdk/app-delivery/.npmignore
  packages/@aws-cdk/app-delivery/LICENSE
  packages/@aws-cdk/app-delivery/NOTICE
  packages/@aws-cdk/app-delivery/README.md
  packages/@aws-cdk/app-delivery/jest.config.js
  packages/@aws-cdk/app-delivery/lib/index.ts
  packages/@aws-cdk/app-delivery/lib/pipeline-deploy-stack-action.ts
  packages/@aws-cdk/app-delivery/package.json
  packages/@aws-cdk/app-delivery/test/integ.cicd.js.snapshot/CICD.assets.json
  packages/@aws-cdk/app-delivery/test/integ.cicd.js.snapshot/CICD.template.json
  packages/@aws-cdk/app-delivery/test/integ.cicd.js.snapshot/cdk.out
  packages/@aws-cdk/app-delivery/test/integ.cicd.js.snapshot/integ.json
  packages/@aws-cdk/app-delivery/test/integ.cicd.js.snapshot/manifest.json
  packages/@aws-cdk/app-delivery/test/integ.cicd.js.snapshot/tree.json
  packages/@aws-cdk/app-delivery/test/integ.cicd.ts
  packages/@aws-cdk/app-delivery/test/pipeline-deploy-stack-action.test.ts
  packages/aws-cdk-lib/package.json
  tests.txt
Labels: p2, contribution/core

#24129 chore: pin and update dependencies
  .github/workflows/yarn-upgrade-v1main.yml
  .github/workflows/yarn-upgrade.yml
  package.json
  packages/@aws-cdk-testing/cli-integ/lib/npm.ts
  packages/@aws-cdk-testing/cli-integ/lib/staging/npm.ts
  packages/@aws-cdk-testing/cli-integ/package.json
  packages/@aws-cdk/assert/package.json
  packages/@aws-cdk/aws-amplifyuibuilder/package.json
  packages/@aws-cdk/aws-eks/package.json
  packages/@aws-cdk/aws-eks/test/sdk-call-integ-test-docker-app/app/package.json
  packages/@aws-cdk/aws-evidently/package.json
  packages/@aws-cdk/aws-lambda-nodejs/package.json
  packages/@aws-cdk/aws-lex/package.json
  packages/@aws-cdk/aws-refactorspaces/package.json
  packages/@aws-cdk/aws-resiliencehub/package.json
  packages/@aws-cdk/aws-rum/package.json
  packages/@aws-cdk/cfnspec/package.json
  packages/@aws-cdk/cli-lib/THIRD_PARTY_LICENSES
  packages/@aws-cdk/cli-lib/package.json
  packages/@aws-cdk/cloudformation-diff/package.json
  packages/@aws-cdk/core/package.json
  packages/@aws-cdk/custom-resources/package.json
  packages/@aws-cdk/integ-runner/THIRD_PARTY_LICENSES
  packages/@aws-cdk/integ-runner/package.json
  packages/@aws-cdk/integ-tests/package.json
  packages/@aws-cdk/lambda-layer-awscli/package.json
  packages/@aws-cdk/lambda-layer-node-proxy-agent/package.json
  packages/@aws-cdk/region-info/package.json
  packages/aws-cdk-lib/package.json
  packages/aws-cdk-migration/package.json
  packages/aws-cdk/THIRD_PARTY_LICENSES
  packages/aws-cdk/lib/init-templates/app/javascript/package.json
  packages/aws-cdk/lib/init-templates/app/typescript/package.json
  packages/aws-cdk/lib/init-templates/lib/typescript/package.json
  packages/aws-cdk/lib/init-templates/sample-app/javascript/package.json
  packages/aws-cdk/lib/init-templates/sample-app/typescript/package.json
  packages/aws-cdk/package.json
  packages/awslint/package.json
  packages/cdk-assets/package.json
  packages/cdk-cli-wrapper/package.json
  tools/@aws-cdk/cdk-build-tools/package.json
  tools/@aws-cdk/cdk-release/package.json
  tools/@aws-cdk/cfn2ts/package.json
  tools/@aws-cdk/eslint-plugin/package.json
  tools/@aws-cdk/individual-pkg-gen/package.json
  tools/@aws-cdk/node-bundle/package.json
  tools/@aws-cdk/pkglint/lib/rules.ts
  tools/@aws-cdk/pkglint/package.json
  tools/@aws-cdk/pkgtools/package.json
  tools/@aws-cdk/ubergen/package.json
  tools/@aws-cdk/yarn-cling/package.json
  yarn.lock
Labels: p2, contribution/core, pr-linter/cli-integ-tested

#24141 chore(feature-flags): fix formatting issue
  packages/@aws-cdk/cx-api/lib/features.ts
Labels: p2, contribution/core

#24144 chore(region-info): add correct `ROUTE_53_BUCKET_WEBSITE_ZONE_ID` of ap southeast 3
  packages/@aws-cdk/region-info/build-tools/fact-tables.ts
Labels: bug, p1, effort/small, beginning-contributor

#24148 chore(actions): fix yarn upgrade scripts
  .github/workflows/yarn-upgrade-v1main.yml
  .github/workflows/yarn-upgrade.yml
Labels: p2, contribution/core

#23993 feat(elbv2): add metrics to INetworkTargetGroup and IApplicationTargetGroup
  packages/@aws-cdk/aws-elasticloadbalancingv2/README.md
  packages/@aws-cdk/aws-elasticloadbalancingv2/lib/alb/application-target-group.ts
  packages/@aws-cdk/aws-elasticloadbalancingv2/lib/nlb/network-target-group.ts
  packages/@aws-cdk/aws-elasticloadbalancingv2/lib/shared/util.ts
  packages/@aws-cdk/aws-elasticloadbalancingv2/test/alb/listener.test.ts
  packages/@aws-cdk/aws-elasticloadbalancingv2/test/alb/target-group.test.ts
  packages/@aws-cdk/aws-elasticloadbalancingv2/test/integ.nlb-lookup.js.snapshot/aws-cdk-elbv2-StackWithLb.assets.json
  packages/@aws-cdk/aws-elasticloadbalancingv2/test/integ.nlb-lookup.js.snapshot/aws-cdk-elbv2-StackWithLb.template.json
  packages/@aws-cdk/aws-elasticloadbalancingv2/test/integ.nlb-lookup.js.snapshot/aws-cdk-elbv2-integ-StackUnderTest.assets.json
  packages/@aws-cdk/aws-elasticloadbalancingv2/test/integ.nlb-lookup.js.snapshot/aws-cdk-elbv2-integ-StackUnderTest.template.json
  packages/@aws-cdk/aws-elasticloadbalancingv2/test/integ.nlb-lookup.js.snapshot/manifest.json
  packages/@aws-cdk/aws-elasticloadbalancingv2/test/integ.nlb-lookup.js.snapshot/tree.json
  packages/@aws-cdk/aws-elasticloadbalancingv2/test/integ.nlb-lookup.ts
  packages/@aws-cdk/aws-elasticloadbalancingv2/test/nlb/target-group.test.ts
Labels: p2, beginning-contributor

#24161 docs(elasticloadbalancingv2): removed deprecated `elbv2.ContentType` reference
  packages/@aws-cdk/aws-elasticloadbalancingv2/README.md
Labels: bug, p1, effort/small, beginning-contributor

#23308 fix(codedeploy): unable to remove alarms from deployment group
  packages/@aws-cdk/aws-codedeploy/lib/ecs/deployment-group.ts
  packages/@aws-cdk/aws-codedeploy/lib/lambda/deployment-group.ts
  packages/@aws-cdk/aws-codedeploy/lib/private/utils.ts
  packages/@aws-cdk/aws-codedeploy/lib/server/deployment-group.ts
  packages/@aws-cdk/aws-codedeploy/package.json
  packages/@aws-cdk/aws-codedeploy/test/ecs/deployment-group.test.ts
  packages/@aws-cdk/aws-codedeploy/test/lambda/deployment-group.test.ts
  packages/@aws-cdk/aws-codedeploy/test/lambda/integ.deployment-group.js.snapshot/aws-cdk-codedeploy-lambda.assets.json
  packages/@aws-cdk/aws-codedeploy/test/lambda/integ.deployment-group.js.snapshot/aws-cdk-codedeploy-lambda.template.json
  packages/@aws-cdk/aws-codedeploy/test/lambda/integ.deployment-group.js.snapshot/cdk.out
  packages/@aws-cdk/aws-codedeploy/test/lambda/integ.deployment-group.js.snapshot/integ.json
  packages/@aws-cdk/aws-codedeploy/test/lambda/integ.deployment-group.js.snapshot/manifest.json
  packages/@aws-cdk/aws-codedeploy/test/lambda/integ.deployment-group.js.snapshot/tree.json
  packages/@aws-cdk/aws-codedeploy/test/lambda/integ.deployment-group.ts
  packages/@aws-cdk/aws-codedeploy/test/server/deployment-group.test.ts
  packages/@aws-cdk/aws-codepipeline-actions/test/integ.pipeline-code-deploy.js.snapshot/aws-cdk-codepipeline-codedeploy.assets.json
  packages/@aws-cdk/aws-codepipeline-actions/test/integ.pipeline-code-deploy.js.snapshot/aws-cdk-codepipeline-codedeploy.template.json
  packages/@aws-cdk/aws-codepipeline-actions/test/integ.pipeline-code-deploy.js.snapshot/cdk.out
  packages/@aws-cdk/aws-codepipeline-actions/test/integ.pipeline-code-deploy.js.snapshot/integ.json
  packages/@aws-cdk/aws-codepipeline-actions/test/integ.pipeline-code-deploy.js.snapshot/manifest.json
  packages/@aws-cdk/aws-codepipeline-actions/test/integ.pipeline-code-deploy.js.snapshot/tree.json
  packages/@aws-cdk/cx-api/FEATURE_FLAGS.md
  packages/@aws-cdk/cx-api/lib/features.ts
Labels: bug, p2, repeat-contributor

#24157 fix(elbv2): healthcheck interval is overly restrictive
  packages/@aws-cdk/aws-elasticloadbalancingv2/lib/nlb/network-target-group.ts
  packages/@aws-cdk/aws-elasticloadbalancingv2/lib/shared/base-target-group.ts
  packages/@aws-cdk/aws-elasticloadbalancingv2/test/integ.nlb.js.snapshot/aws-cdk-elbv2-integ.assets.json
  packages/@aws-cdk/aws-elasticloadbalancingv2/test/integ.nlb.js.snapshot/aws-cdk-elbv2-integ.template.json
  packages/@aws-cdk/aws-elasticloadbalancingv2/test/integ.nlb.js.snapshot/cdk.out
  packages/@aws-cdk/aws-elasticloadbalancingv2/test/integ.nlb.js.snapshot/elbv2integDefaultTestDeployAssert6120E394.assets.json
  packages/@aws-cdk/aws-elasticloadbalancingv2/test/integ.nlb.js.snapshot/integ.json
  packages/@aws-cdk/aws-elasticloadbalancingv2/test/integ.nlb.js.snapshot/manifest.json
  packages/@aws-cdk/aws-elasticloadbalancingv2/test/integ.nlb.js.snapshot/tree.json
  packages/@aws-cdk/aws-elasticloadbalancingv2/test/integ.nlb.ts
  packages/@aws-cdk/aws-elasticloadbalancingv2/test/nlb/listener.test.ts
  packages/@aws-cdk/aws-elasticloadbalancingv2/test/nlb/target-group.test.ts
Labels: bug, p1, effort/small, contribution/core

#24175 fix(bootstrap): remove Security Hub finding S3.10
  packages/aws-cdk/lib/api/bootstrap/bootstrap-template.yaml
Labels: p2, contribution/core, pr-linter/exempt-test, pr-linter/exempt-integ-test

#24176 docs(ecs): updated documentation for addCapabilities and dropCapabilities
  packages/@aws-cdk/aws-ecs/lib/linux-parameters.ts
Labels: p2, beginning-contributor

#23215 fix(apigateway): rest api deployment does not depend on authorizers
  packages/@aws-cdk/aws-apigateway/README.md
  packages/@aws-cdk/aws-apigateway/lib/authorizers/cognito.ts
  packages/@aws-cdk/aws-apigateway/lib/authorizers/lambda.ts
  packages/@aws-cdk/aws-apigateway/test/authorizers/cognito.test.ts
  packages/@aws-cdk/aws-apigateway/test/authorizers/integ.cognito-authorizer.js.snapshot/CognitoUserPoolsAuthorizerInteg.assets.json
  packages/@aws-cdk/aws-apigateway/test/authorizers/integ.cognito-authorizer.js.snapshot/CognitoUserPoolsAuthorizerInteg.template.json
  packages/@aws-cdk/aws-apigateway/test/authorizers/integ.cognito-authorizer.js.snapshot/cdk.out
  packages/@aws-cdk/aws-apigateway/test/authorizers/integ.cognito-authorizer.js.snapshot/cognitoauthorizerDefaultTestDeployAssert4551574C.assets.json
  packages/@aws-cdk/aws-apigateway/test/authorizers/integ.cognito-authorizer.js.snapshot/integ.json
  packages/@aws-cdk/aws-apigateway/test/authorizers/integ.cognito-authorizer.js.snapshot/manifest.json
  packages/@aws-cdk/aws-apigateway/test/authorizers/integ.cognito-authorizer.js.snapshot/tree.json
  packages/@aws-cdk/aws-apigateway/test/authorizers/integ.request-authorizer.lit.js.snapshot/RequestAuthorizerInteg.assets.json
  packages/@aws-cdk/aws-apigateway/test/authorizers/integ.request-authorizer.lit.js.snapshot/RequestAuthorizerInteg.template.json
  packages/@aws-cdk/aws-apigateway/test/authorizers/integ.request-authorizer.lit.js.snapshot/cdk.out
  packages/@aws-cdk/aws-apigateway/test/authorizers/integ.request-authorizer.lit.js.snapshot/integ.json
  packages/@aws-cdk/aws-apigateway/test/authorizers/integ.request-authorizer.lit.js.snapshot/manifest.json
  packages/@aws-cdk/aws-apigateway/test/authorizers/integ.request-authorizer.lit.js.snapshot/tree.json
  packages/@aws-cdk/aws-apigateway/test/authorizers/integ.request-authorizer.lit.ts
  packages/@aws-cdk/aws-apigateway/test/authorizers/integ.token-authorizer-iam-role.js.snapshot/TokenAuthorizerIAMRoleInteg.assets.json
  packages/@aws-cdk/aws-apigateway/test/authorizers/integ.token-authorizer-iam-role.js.snapshot/TokenAuthorizerIAMRoleInteg.template.json
  packages/@aws-cdk/aws-apigateway/test/authorizers/integ.token-authorizer-iam-role.js.snapshot/cdk.out
  packages/@aws-cdk/aws-apigateway/test/authorizers/integ.token-authorizer-iam-role.js.snapshot/iamtokenauthorizerDefaultTestDeployAssert87D47FBB.assets.json
  packages/@aws-cdk/aws-apigateway/test/authorizers/integ.token-authorizer-iam-role.js.snapshot/integ.json
  packages/@aws-cdk/aws-apigateway/test/authorizers/integ.token-authorizer-iam-role.js.snapshot/manifest.json
  packages/@aws-cdk/aws-apigateway/test/authorizers/integ.token-authorizer-iam-role.js.snapshot/tree.json
  packages/@aws-cdk/aws-apigateway/test/authorizers/integ.token-authorizer.js.snapshot/TokenAuthorizerInteg.assets.json
  packages/@aws-cdk/aws-apigateway/test/authorizers/integ.token-authorizer.js.snapshot/TokenAuthorizerInteg.template.json
  packages/@aws-cdk/aws-apigateway/test/authorizers/integ.token-authorizer.js.snapshot/apigwtokenauthDefaultTestDeployAssert2CF60E05.assets.json
  packages/@aws-cdk/aws-apigateway/test/authorizers/integ.token-authorizer.js.snapshot/apigwtokenauthDefaultTestDeployAssert2CF60E05.template.json
  packages/@aws-cdk/aws-apigateway/test/authorizers/integ.token-authorizer.js.snapshot/asset.382ba2a8fd0a13f6782aec5543e465f988f5c100f35ed20f90cd96b8ee53f674.bundle/index.js
  packages/@aws-cdk/aws-apigateway/test/authorizers/integ.token-authorizer.js.snapshot/cdk.out
  packages/@aws-cdk/aws-apigateway/test/authorizers/integ.token-authorizer.js.snapshot/integ.json
  packages/@aws-cdk/aws-apigateway/test/authorizers/integ.token-authorizer.js.snapshot/manifest.json
  packages/@aws-cdk/aws-apigateway/test/authorizers/integ.token-authorizer.js.snapshot/tree.json
  packages/@aws-cdk/aws-apigateway/test/authorizers/lambda.test.ts
  packages/@aws-cdk/cx-api/FEATURE_FLAGS.md
  packages/@aws-cdk/cx-api/lib/features.ts
Labels: bug, p2, effort/small, repeat-contributor

#24136 feat(core): Size.bytes()
  packages/@aws-cdk/core/lib/size.ts
  packages/@aws-cdk/core/test/size.test.ts
Labels: bug, p1, effort/small, contribution/core, pr-linter/exempt-readme, pr-linter/exempt-integ-test

#24190 chore(merge-back): 1.193.0
  CHANGELOG.md
  version.v1.json
Labels: p2, pr/no-squash, auto-approve

#24191 chore(merge-back): 2.65.0
  CHANGELOG.v2.alpha.md
  CHANGELOG.v2.md
  packages/@aws-cdk/cx-api/FEATURE_FLAGS.md
  packages/@aws-cdk/cx-api/lib/features.ts
  version.v2.json
Labels: p2, pr/no-squash, auto-approve

#23378 fix(eks): nested OCI repository names for private ECR helmchart deployments are not properly handled
  packages/@aws-cdk/aws-eks/lib/kubectl-handler/helm/__init__.py
  packages/@aws-cdk/aws-eks/test/integ.eks-helm-asset.ts
Labels: bug, p2, pr-linter/exempt-test, pr-linter/exempt-integ-test, beginning-contributor

#24196 feat(efs): support file system policy
  packages/@aws-cdk/aws-efs/README.md
  packages/@aws-cdk/aws-efs/lib/efs-file-system.ts
  packages/@aws-cdk/aws-efs/test/efs-file-system.test.ts
  packages/@aws-cdk/aws-efs/test/integ.efs-filesystem-policy.js.snapshot/FileSystemPolicyTestDefaultTestDeployAssertD0596FC1.assets.json
  packages/@aws-cdk/aws-efs/test/integ.efs-filesystem-policy.js.snapshot/FileSystemPolicyTestDefaultTestDeployAssertD0596FC1.template.json
  packages/@aws-cdk/aws-efs/test/integ.efs-filesystem-policy.js.snapshot/cdk.out
  packages/@aws-cdk/aws-efs/test/integ.efs-filesystem-policy.js.snapshot/integ.json
  packages/@aws-cdk/aws-efs/test/integ.efs-filesystem-policy.js.snapshot/manifest.json
  packages/@aws-cdk/aws-efs/test/integ.efs-filesystem-policy.js.snapshot/test-efs-integ.assets.json
  packages/@aws-cdk/aws-efs/test/integ.efs-filesystem-policy.js.snapshot/test-efs-integ.template.json
  packages/@aws-cdk/aws-efs/test/integ.efs-filesystem-policy.js.snapshot/tree.json
  packages/@aws-cdk/aws-efs/test/integ.efs-filesystem-policy.ts
Labels: p2, feature-request, effort/medium, beginning-contributor

#24171 fix(servicecatalogappregistry): Allow user to control stack id via stack name for Application stack
  packages/@aws-cdk/aws-servicecatalogappregistry/lib/target-application.ts
  packages/@aws-cdk/aws-servicecatalogappregistry/test/integ.application-associator.all-stacks-association-no-stack-id-or-name.js.snapshot/Application-AppRegistryAssociatedApplication-Stack.assets.json
  packages/@aws-cdk/aws-servicecatalogappregistry/test/integ.application-associator.all-stacks-association-no-stack-id-or-name.js.snapshot/Application-AppRegistryAssociatedApplication-Stack.template.json
  packages/@aws-cdk/aws-servicecatalogappregistry/test/integ.application-associator.all-stacks-association-no-stack-id-or-name.js.snapshot/ApplicationAssociatorTestDefaultTestDeployAssert2A5F2DB9.assets.json
  packages/@aws-cdk/aws-servicecatalogappregistry/test/integ.application-associator.all-stacks-association-no-stack-id-or-name.js.snapshot/ApplicationAssociatorTestDefaultTestDeployAssert2A5F2DB9.template.json
  packages/@aws-cdk/aws-servicecatalogappregistry/test/integ.application-associator.all-stacks-association-no-stack-id-or-name.js.snapshot/cdk.out
  packages/@aws-cdk/aws-servicecatalogappregistry/test/integ.application-associator.all-stacks-association-no-stack-id-or-name.js.snapshot/integ-servicecatalogappregistry-application.assets.json
  packages/@aws-cdk/aws-servicecatalogappregistry/test/integ.application-associator.all-stacks-association-no-stack-id-or-name.js.snapshot/integ-servicecatalogappregistry-application.template.json
  packages/@aws-cdk/aws-servicecatalogappregistry/test/integ.application-associator.all-stacks-association-no-stack-id-or-name.js.snapshot/integ.json
  packages/@aws-cdk/aws-servicecatalogappregistry/test/integ.application-associator.all-stacks-association-no-stack-id-or-name.js.snapshot/integservicecatalogappregistryapplicationresourcesStack4399A149.assets.json
  packages/@aws-cdk/aws-servicecatalogappregistry/test/integ.application-associator.all-stacks-association-no-stack-id-or-name.js.snapshot/integservicecatalogappregistryapplicationresourcesStack4399A149.template.json
  packages/@aws-cdk/aws-servicecatalogappregistry/test/integ.application-associator.all-stacks-association-no-stack-id-or-name.js.snapshot/manifest.json
  packages/@aws-cdk/aws-servicecatalogappregistry/test/integ.application-associator.all-stacks-association-no-stack-id-or-name.js.snapshot/tree.json
  packages/@aws-cdk/aws-servicecatalogappregistry/test/integ.application-associator.all-stacks-association-no-stack-id-or-name.ts
  packages/@aws-cdk/aws-servicecatalogappregistry/test/integ.application-associator.all-stacks-association-no-stack-name.js.snapshot/cdk.out
Labels: p2, feature-request, beginning-contributor

#24204 docs(lambda-nodejs): fixed documentation formatting error for loader type
  packages/@aws-cdk/aws-lambda-nodejs/lib/types.ts
Labels: p2, beginning-contributor

#24207 docs(eks): change cdk8s-charts index level on README
  packages/@aws-cdk/aws-eks/README.md
Labels: p2, effort/small, beginning-contributor

#24222 chore(issue-template): create issue template for new regions
  .github/ISSUE_TEMPLATE/region.yml
Labels: p2, contribution/core

#22063 feat(redshift): optionally reboot Clusters to apply parameter changes
  packages/@aws-cdk/aws-redshift/README.md
  packages/@aws-cdk/aws-redshift/lib/cluster-parameter-change-reboot-handler/index.ts
  packages/@aws-cdk/aws-redshift/lib/cluster.ts
  packages/@aws-cdk/aws-redshift/test/cluster-reboot.integ.snapshot/asset.1b88b7c3e3e0f8d3e27ded1bde51b7a80c75f3d8733872af7952c3a6d902147e/index.d.ts
  packages/@aws-cdk/aws-redshift/test/cluster-reboot.integ.snapshot/asset.1b88b7c3e3e0f8d3e27ded1bde51b7a80c75f3d8733872af7952c3a6d902147e/index.js
  packages/@aws-cdk/aws-redshift/test/cluster-reboot.integ.snapshot/asset.1b88b7c3e3e0f8d3e27ded1bde51b7a80c75f3d8733872af7952c3a6d902147e/index.ts
  packages/@aws-cdk/aws-redshift/test/cluster-reboot.integ.snapshot/asset.7215c88dd3e638d28329d4538b36cdbfb54233a4d972181795814f8b904d1037/cfn-response.js
  packages/@aws-cdk/aws-redshift/test/cluster-reboot.integ.snapshot/asset.7215c88dd3e638d28329d4538b36cdbfb54233a4d972181795814f8b904d1037/consts.js
  packages/@aws-cdk/aws-redshift/test/cluster-reboot.integ.snapshot/asset.7215c88dd3e638d28329d4538b36cdbfb54233a4d972181795814f8b904d1037/framework.js
  packages/@aws-cdk/aws-redshift/test/cluster-reboot.integ.snapshot/asset.7215c88dd3e638d28329d4538b36cdbfb54233a4d972181795814f8b904d1037/outbound.js
  packages/@aws-cdk/aws-redshift/test/cluster-reboot.integ.snapshot/asset.7215c88dd3e638d28329d4538b36cdbfb54233a4d972181795814f8b904d1037/util.js
  packages/@aws-cdk/aws-redshift/test/cluster-reboot.integ.snapshot/aws-cdk-redshift-cluster-create.assets.json
  packages/@aws-cdk/aws-redshift/test/cluster-reboot.integ.snapshot/aws-cdk-redshift-cluster-create.template.json
  packages/@aws-cdk/aws-redshift/test/cluster-reboot.integ.snapshot/aws-cdk-redshift-cluster-update.assets.json
  packages/@aws-cdk/aws-redshift/test/cluster-reboot.integ.snapshot/aws-cdk-redshift-cluster-update.template.json
  packages/@aws-cdk/aws-redshift/test/cluster-reboot.integ.snapshot/awscdkredshiftreboottestDefaultTestDeployAssert1AE11B34.assets.json
  packages/@aws-cdk/aws-redshift/test/cluster-reboot.integ.snapshot/awscdkredshiftreboottestDefaultTestDeployAssert1AE11B34.template.json
  packages/@aws-cdk/aws-redshift/test/cluster-reboot.integ.snapshot/cdk.out
  packages/@aws-cdk/aws-redshift/test/cluster-reboot.integ.snapshot/integ.json
  packages/@aws-cdk/aws-redshift/test/cluster-reboot.integ.snapshot/manifest.json
  packages/@aws-cdk/aws-redshift/test/cluster-reboot.integ.snapshot/tree.json
  packages/@aws-cdk/aws-redshift/test/cluster.test.ts
  packages/@aws-cdk/aws-redshift/test/integ.cluster-reboot.js.snapshot/asset.382ba2a8fd0a13f6782aec5543e465f988f5c100f35ed20f90cd96b8ee53f674.bundle/index.js
  packages/@aws-cdk/aws-redshift/test/integ.cluster-reboot.js.snapshot/aws-cdk-redshift-cluster-create.assets.json
  packages/@aws-cdk/aws-redshift/test/integ.cluster-reboot.js.snapshot/aws-cdk-redshift-cluster-create.template.json
  packages/@aws-cdk/aws-redshift/test/integ.cluster-reboot.js.snapshot/aws-cdk-redshift-cluster-update.assets.json
  packages/@aws-cdk/aws-redshift/test/integ.cluster-reboot.js.snapshot/aws-cdk-redshift-cluster-update.template.json
  packages/@aws-cdk/aws-redshift/test/integ.cluster-reboot.js.snapshot/awscdkredshiftreboottestDefaultTestDeployAssert1AE11B34.assets.json
  packages/@aws-cdk/aws-redshift/test/integ.cluster-reboot.js.snapshot/awscdkredshiftreboottestDefaultTestDeployAssert1AE11B34.template.json
  packages/@aws-cdk/aws-redshift/test/integ.cluster-reboot.js.snapshot/cdk.out
  packages/@aws-cdk/aws-redshift/test/integ.cluster-reboot.js.snapshot/integ.json
  packages/@aws-cdk/aws-redshift/test/integ.cluster-reboot.js.snapshot/manifest.json
  packages/@aws-cdk/aws-redshift/test/integ.cluster-reboot.js.snapshot/tree.json
  packages/@aws-cdk/aws-redshift/test/integ.cluster-reboot.ts
Labels: p2, feature-request, effort/medium

#24022 feat(logs): Add support for multiple parse and filter statements in QueryString
  packages/@aws-cdk/aws-logs/README.md
  packages/@aws-cdk/aws-logs/lib/query-definition.ts
  packages/@aws-cdk/aws-logs/test/integ.save-logs-insights-query-definition.js.snapshot/LogsInsightsQueryDefinitionIntegTestDefaultTestDeployAssert902BAAD5.assets.json
  packages/@aws-cdk/aws-logs/test/integ.save-logs-insights-query-definition.js.snapshot/aws-cdk-logs-insights-querydefinition-integ.assets.json
  packages/@aws-cdk/aws-logs/test/integ.save-logs-insights-query-definition.js.snapshot/aws-cdk-logs-insights-querydefinition-integ.template.json
  packages/@aws-cdk/aws-logs/test/integ.save-logs-insights-query-definition.js.snapshot/cdk.out
  packages/@aws-cdk/aws-logs/test/integ.save-logs-insights-query-definition.js.snapshot/integ.json
  packages/@aws-cdk/aws-logs/test/integ.save-logs-insights-query-definition.js.snapshot/manifest.json
  packages/@aws-cdk/aws-logs/test/integ.save-logs-insights-query-definition.js.snapshot/tree.json
  packages/@aws-cdk/aws-logs/test/integ.save-logs-insights-query-definition.ts
  packages/@aws-cdk/aws-logs/test/query-definition.test.ts
Labels: p2, beginning-contributor

#23670 feat(lambda-python): add optional poetry bundling exclusion list parameter
  packages/@aws-cdk/aws-lambda-python/README.md
  packages/@aws-cdk/aws-lambda-python/lib/bundling.ts
  packages/@aws-cdk/aws-lambda-python/lib/types.ts
  packages/@aws-cdk/aws-lambda-python/test/bundling.test.ts
  packages/@aws-cdk/aws-lambda-python/test/integ.function.js.snapshot/asset.73c20a669c041469f7fc3fc03d574b093b5b97e7c716f76c1e8117e6163e4dc4.bundle/index.js
  packages/@aws-cdk/aws-lambda-python/test/integ.function.js.snapshot/asset.84802aa01d2d2c9e7d8d69705ee832c97f1ebad2d73c72be5c32d53f16cf90a7.bundle/index.js
  packages/@aws-cdk/aws-lambda-python/test/integ.function.js.snapshot/cdk.out
  packages/@aws-cdk/aws-lambda-python/test/integ.function.js.snapshot/integ-lambda-python-function.assets.json
  packages/@aws-cdk/aws-lambda-python/test/integ.function.js.snapshot/integ-lambda-python-function.template.json
  packages/@aws-cdk/aws-lambda-python/test/integ.function.js.snapshot/integ.json
  packages/@aws-cdk/aws-lambda-python/test/integ.function.js.snapshot/lambdapythonfunctionDefaultTestDeployAssertC9C6EE6F.assets.json
  packages/@aws-cdk/aws-lambda-python/test/integ.function.js.snapshot/lambdapythonfunctionDefaultTestDeployAssertC9C6EE6F.template.json
  packages/@aws-cdk/aws-lambda-python/test/integ.function.js.snapshot/manifest.json
  packages/@aws-cdk/aws-lambda-python/test/integ.function.js.snapshot/tree.json
  packages/@aws-cdk/aws-lambda-python/test/integ.function.pipenv.js.snapshot/asset.73c20a669c041469f7fc3fc03d574b093b5b97e7c716f76c1e8117e6163e4dc4.bundle/index.js
  packages/@aws-cdk/aws-lambda-python/test/integ.function.pipenv.js.snapshot/asset.84802aa01d2d2c9e7d8d69705ee832c97f1ebad2d73c72be5c32d53f16cf90a7.bundle/index.js
  packages/@aws-cdk/aws-lambda-python/test/integ.function.pipenv.js.snapshot/cdk.out
  packages/@aws-cdk/aws-lambda-python/test/integ.function.pipenv.js.snapshot/integ-lambda-python-pipenv.assets.json
  packages/@aws-cdk/aws-lambda-python/test/integ.function.pipenv.js.snapshot/integ-lambda-python-pipenv.template.json
  packages/@aws-cdk/aws-lambda-python/test/integ.function.pipenv.js.snapshot/integ.json
  packages/@aws-cdk/aws-lambda-python/test/integ.function.pipenv.js.snapshot/manifest.json
  packages/@aws-cdk/aws-lambda-python/test/integ.function.pipenv.js.snapshot/pipenvDefaultTestDeployAssertF8231517.assets.json
  packages/@aws-cdk/aws-lambda-python/test/integ.function.pipenv.js.snapshot/pipenvDefaultTestDeployAssertF8231517.template.json
  packages/@aws-cdk/aws-lambda-python/test/integ.function.pipenv.js.snapshot/tree.json
  packages/@aws-cdk/aws-lambda-python/test/integ.function.pipenv.ts
  packages/@aws-cdk/aws-lambda-python/test/integ.function.poetry.js.snapshot/asset.73c20a669c041469f7fc3fc03d574b093b5b97e7c716f76c1e8117e6163e4dc4.bundle/index.js
  packages/@aws-cdk/aws-lambda-python/test/integ.function.poetry.js.snapshot/asset.d47f7e6772bfdf47ecbc070ffe204baf53bacbfbf7814eb407bd8ea108c1c1bb.bundle/index.js
  packages/@aws-cdk/aws-lambda-python/test/integ.function.poetry.js.snapshot/cdk.out
  packages/@aws-cdk/aws-lambda-python/test/integ.function.poetry.js.snapshot/integ-lambda-python-poetry.assets.json
  packages/@aws-cdk/aws-lambda-python/test/integ.function.poetry.js.snapshot/integ-lambda-python-poetry.template.json
  packages/@aws-cdk/aws-lambda-python/test/integ.function.poetry.js.snapshot/integ.json
  packages/@aws-cdk/aws-lambda-python/test/integ.function.poetry.js.snapshot/manifest.json
  packages/@aws-cdk/aws-lambda-python/test/integ.function.poetry.js.snapshot/poetryDefaultTestDeployAssertE9C9CB8F.assets.json
  packages/@aws-cdk/aws-lambda-python/test/integ.function.poetry.js.snapshot/poetryDefaultTestDeployAssertE9C9CB8F.template.json
  packages/@aws-cdk/aws-lambda-python/test/integ.function.poetry.js.snapshot/tree.json
  packages/@aws-cdk/aws-lambda-python/test/integ.function.poetry.ts
  packages/@aws-cdk/aws-lambda-python/test/integ.function.ts
  packages/@aws-cdk/aws-lambda-python/test/lambda-handler/.ignorelist
Labels: bug, p2, effort/small, beginning-contributor

#22984 feat(apigatewayv2): allow websockets routes to return response to client
  packages/@aws-cdk/aws-apigatewayv2-integrations/package.json
  packages/@aws-cdk/aws-apigatewayv2-integrations/test/websocket/integ.route-response.js.snapshot/IntegDefaultTestDeployAssert4E6713E1.assets.json
  packages/@aws-cdk/aws-apigatewayv2-integrations/test/websocket/integ.route-response.js.snapshot/IntegDefaultTestDeployAssert4E6713E1.template.json
  packages/@aws-cdk/aws-apigatewayv2-integrations/test/websocket/integ.route-response.js.snapshot/aws-cdk-aws-apigatewayv2-websockets.assets.json
  packages/@aws-cdk/aws-apigatewayv2-integrations/test/websocket/integ.route-response.js.snapshot/aws-cdk-aws-apigatewayv2-websockets.template.json
  packages/@aws-cdk/aws-apigatewayv2-integrations/test/websocket/integ.route-response.js.snapshot/cdk.out
  packages/@aws-cdk/aws-apigatewayv2-integrations/test/websocket/integ.route-response.js.snapshot/integ.json
  packages/@aws-cdk/aws-apigatewayv2-integrations/test/websocket/integ.route-response.js.snapshot/manifest.json
  packages/@aws-cdk/aws-apigatewayv2-integrations/test/websocket/integ.route-response.js.snapshot/tree.json
  packages/@aws-cdk/aws-apigatewayv2-integrations/test/websocket/integ.route-response.ts
  packages/@aws-cdk/aws-apigatewayv2/README.md
  packages/@aws-cdk/aws-apigatewayv2/lib/websocket/route.ts
  packages/@aws-cdk/aws-apigatewayv2/test/websocket/api.test.ts
  packages/@aws-cdk/aws-apigatewayv2/test/websocket/route.test.ts
Labels: p2, beginning-contributor

#24230 chore: add suppression of maintenance mode warning so dependencies can be upgraded
  .github/workflows/yarn-upgrade-v1main.yml
  .github/workflows/yarn-upgrade.yml
  lerna.json
  package.json
  packages/@aws-cdk-testing/cli-integ/lib/aws.ts
  packages/@aws-cdk-testing/cli-integ/package.json
  packages/@aws-cdk/aws-amplify/package.json
  packages/@aws-cdk/aws-certificatemanager/lambda-packages/dns_validated_certificate_handler/package.json
  packages/@aws-cdk/aws-cloudfront-origins/package.json
  packages/@aws-cdk/aws-cloudfront/package.json
  packages/@aws-cdk/aws-cloudtrail/package.json
  packages/@aws-cdk/aws-codebuild/package.json
  packages/@aws-cdk/aws-codecommit/package.json
  packages/@aws-cdk/aws-dynamodb-global/lambda-packages/aws-global-table-coordinator/package.json
  packages/@aws-cdk/aws-dynamodb/package.json
  packages/@aws-cdk/aws-eks/package.json
  packages/@aws-cdk/aws-events-targets/package.json
  packages/@aws-cdk/aws-gamelift/package.json
  packages/@aws-cdk/aws-globalaccelerator-endpoints/package.json
  packages/@aws-cdk/aws-lambda-nodejs/package.json
  packages/@aws-cdk/aws-logs/package.json
  packages/@aws-cdk/aws-redshift/package.json
  packages/@aws-cdk/aws-route53/package.json
  packages/@aws-cdk/aws-sqs/package.json
  packages/@aws-cdk/cli-lib/THIRD_PARTY_LICENSES
  packages/@aws-cdk/core/package.json
  packages/@aws-cdk/custom-resources/package.json
  packages/@aws-cdk/cx-api/package.json
  packages/@aws-cdk/integ-runner/THIRD_PARTY_LICENSES
  packages/@aws-cdk/integ-tests/package.json
  packages/@aws-cdk/lambda-layer-awscli/package.json
  packages/@aws-cdk/lambda-layer-node-proxy-agent/package.json
  packages/@aws-cdk/pipelines/package.json
  packages/@aws-cdk/triggers/package.json
  packages/aws-cdk-lib/package.json
  packages/aws-cdk/THIRD_PARTY_LICENSES
  packages/aws-cdk/lib/api/aws-auth/sdk.ts
  packages/aws-cdk/package.json
  packages/awslint/package.json
  packages/cdk-assets/package.json
  packages/cdk-dasm/package.json
  packages/individual-packages/lerna.json
  tools/@aws-cdk/cdk-build-tools/package.json
  tools/@aws-cdk/cfn2ts/package.json
  tools/@aws-cdk/node-bundle/package.json
  tools/@aws-cdk/node-bundle/test/cli.test.ts
  yarn.lock
Labels: p2, contribution/core, pr-linter/cli-integ-tested

#23095 feat(cloudwatch): parse all metrics statistics and support long format
  packages/@aws-cdk/aws-cloudwatch/README.md
  packages/@aws-cdk/aws-cloudwatch/lib/alarm.ts
  packages/@aws-cdk/aws-cloudwatch/lib/metric.ts
  packages/@aws-cdk/aws-cloudwatch/lib/private/statistic.ts
  packages/@aws-cdk/aws-cloudwatch/test/alarm.test.ts
  packages/@aws-cdk/aws-cloudwatch/test/integ.dashboard-with-graphwidget-with-statistic.js.snapshot/DashboardWithGraphWidgetWithStatisticIntegrationTest.assets.json
  packages/@aws-cdk/aws-cloudwatch/test/integ.dashboard-with-graphwidget-with-statistic.js.snapshot/DashboardWithGraphWidgetWithStatisticIntegrationTest.template.json
  packages/@aws-cdk/aws-cloudwatch/test/integ.dashboard-with-graphwidget-with-statistic.js.snapshot/cdk.out
  packages/@aws-cdk/aws-cloudwatch/test/integ.dashboard-with-graphwidget-with-statistic.js.snapshot/manifest.json
  packages/@aws-cdk/aws-cloudwatch/test/integ.dashboard-with-graphwidget-with-statistic.js.snapshot/tree.json
  packages/@aws-cdk/aws-cloudwatch/test/integ.dashboard-with-graphwidget-with-statistic.ts
  packages/@aws-cdk/aws-cloudwatch/test/metrics.test.ts
Labels: p2, beginning-contributor

#24239 chore: use @types/conventional-commits-parser instead of decs file
  package.json
  packages/@aws-cdk/aws-amplifyuibuilder/package.json
  tools/@aws-cdk/node-bundle/package.json
  tools/@aws-cdk/prlint/decs.d.ts
  tools/@aws-cdk/prlint/package.json
  tools/@aws-cdk/yarn-cling/package.json
  yarn.lock
Labels: p2, contribution/core

#24240 chore: update yarn update actions
  .github/workflows/yarn-upgrade-v1main.yml
  .github/workflows/yarn-upgrade.yml
Labels: p2, contribution/core

#24252 fix(lambda): RuntimeManagementMode.FUNCTION_UPDATE has wrong value
  packages/@aws-cdk/aws-lambda/lib/runtime-management.ts
  packages/@aws-cdk/aws-lambda/test/runtime-management.test.ts
Labels: p2, pr-linter/exempt-integ-test, beginning-contributor

#24260 chore(merge-back): 2.66.0
  CHANGELOG.v2.alpha.md
  CHANGELOG.v2.md
  packages/@aws-cdk/cx-api/FEATURE_FLAGS.md
  packages/@aws-cdk/cx-api/lib/features.ts
  version.v2.json
Labels: p2, pr/no-squash, auto-approve

#24264 chore(merge-back): 1.194.0
  CHANGELOG.md
  version.v1.json
Labels: p2, pr/no-squash, auto-approve

#24256 chore(ec2): allow opting out of VPN Gateway lookup
  packages/@aws-cdk/aws-ec2/lib/vpc-lookup.ts
  packages/@aws-cdk/aws-ec2/lib/vpc.ts
  packages/@aws-cdk/cloud-assembly-schema/lib/cloud-assembly/context-queries.ts
  packages/@aws-cdk/cloud-assembly-schema/schema/cloud-assembly.schema.json
  packages/@aws-cdk/cloud-assembly-schema/schema/cloud-assembly.version.json
  packages/aws-cdk/lib/context-providers/vpcs.ts
  scripts/check-build-prerequisites.sh
Labels: p2, contribution/core, pr-linter/cli-integ-tested

#24277 fix: Correct SamlConsolePrincipal for non-China
  packages/@aws-cdk/aws-iam/lib/principals.ts
  packages/@aws-cdk/aws-iam/test/integ.saml-provider.js.snapshot/cdk-saml-provider.assets.json
  packages/@aws-cdk/aws-iam/test/integ.saml-provider.js.snapshot/cdk-saml-provider.template.json
  packages/@aws-cdk/aws-iam/test/integ.saml-provider.js.snapshot/cdk.out
  packages/@aws-cdk/aws-iam/test/integ.saml-provider.js.snapshot/integ.json
  packages/@aws-cdk/aws-iam/test/integ.saml-provider.js.snapshot/manifest.json
  packages/@aws-cdk/aws-iam/test/integ.saml-provider.js.snapshot/samlprovidertestDefaultTestDeployAssert29A1AF64.assets.json
  packages/@aws-cdk/aws-iam/test/integ.saml-provider.js.snapshot/tree.json
  packages/@aws-cdk/aws-iam/test/integ.saml-provider.ts
  packages/@aws-cdk/aws-iam/test/principals.test.ts
Labels: bug, p0, effort/small, contribution/core

#24269 fix(sns): sns subscription filter policy condition limit should be 150
  packages/@aws-cdk/aws-sns/lib/subscription.ts
  packages/@aws-cdk/aws-sns/test/subscription.test.ts
Labels: p2, pr-linter/exempt-integ-test, beginning-contributor, pr/reviewer-clarification-requested

#24263 feat(remodel): call ubergen to create aws-cdk-lib
  package.json
  tools/@aws-cdk/cfn2ts/lib/augmentation-generator.ts
  tools/@aws-cdk/cfn2ts/lib/index.ts
  tools/@aws-cdk/remodel/.eslintrc.js
  tools/@aws-cdk/remodel/.gitignore
  tools/@aws-cdk/remodel/.npmignore
  tools/@aws-cdk/remodel/LICENSE
  tools/@aws-cdk/remodel/NOTICE
  tools/@aws-cdk/remodel/bin/remodel.ts
  tools/@aws-cdk/remodel/lib/cli.ts
  tools/@aws-cdk/remodel/lib/template/.gitignore
  tools/@aws-cdk/remodel/lib/template/packages/aws-cdk-lib/scripts/fact-tables.ts
  tools/@aws-cdk/remodel/lib/template/packages/aws-cdk-lib/scripts/gen-region-info-builtins.ts
  tools/@aws-cdk/remodel/lib/template/packages/aws-cdk-lib/scripts/gen-sdk-api-metadata.ts
  tools/@aws-cdk/remodel/lib/template/packages/aws-cdk-lib/scripts/gen.ts
  tools/@aws-cdk/remodel/package.json
  tools/@aws-cdk/ubergen/bin/ubergen.ts
  tools/@aws-cdk/ubergen/lib/index.ts
Labels: p2, contribution/core, pr-linter/exempt-readme, pr-linter/exempt-test, pr-linter/exempt-integ-test

#23955 feat(ecs): enable default capacity provider strategy
  packages/@aws-cdk/aws-ecs/README.md
  packages/@aws-cdk/aws-ecs/lib/cluster.ts
  packages/@aws-cdk/aws-ecs/test/cluster.test.ts
  packages/@aws-cdk/aws-ecs/test/ec2/integ.default-capacity-provider.js.snapshot/CapacityProvidersDefaultTestDeployAssert30F9785A.assets.json
  packages/@aws-cdk/aws-ecs/test/ec2/integ.default-capacity-provider.js.snapshot/CapacityProvidersDefaultTestDeployAssert30F9785A.template.json
  packages/@aws-cdk/aws-ecs/test/ec2/integ.default-capacity-provider.js.snapshot/cdk.out
  packages/@aws-cdk/aws-ecs/test/ec2/integ.default-capacity-provider.js.snapshot/integ-default-capacity-provider.assets.json
  packages/@aws-cdk/aws-ecs/test/ec2/integ.default-capacity-provider.js.snapshot/integ-default-capacity-provider.template.json
  packages/@aws-cdk/aws-ecs/test/ec2/integ.default-capacity-provider.js.snapshot/integ.json
  packages/@aws-cdk/aws-ecs/test/ec2/integ.default-capacity-provider.js.snapshot/manifest.json
  packages/@aws-cdk/aws-ecs/test/ec2/integ.default-capacity-provider.js.snapshot/tree.json
  packages/@aws-cdk/aws-ecs/test/ec2/integ.default-capacity-provider.ts
Labels: p2, beginning-contributor

#24289 feat(codebuild): adds file asset support to build-spec
  packages/@aws-cdk/aws-codebuild/README.md
  packages/@aws-cdk/aws-codebuild/lib/build-spec.ts
  packages/@aws-cdk/aws-codebuild/lib/project.ts
  packages/@aws-cdk/aws-codebuild/test/build-spec-asset.yml
  packages/@aws-cdk/aws-codebuild/test/integ.asset-build-spec.js.snapshot/AssetBuildSpecTestDefaultTestDeployAssertC826AACC.assets.json
  packages/@aws-cdk/aws-codebuild/test/integ.asset-build-spec.js.snapshot/AssetBuildSpecTestDefaultTestDeployAssertC826AACC.template.json
  packages/@aws-cdk/aws-codebuild/test/integ.asset-build-spec.js.snapshot/CodeBuildAssetBuildSpecStack.assets.json
  packages/@aws-cdk/aws-codebuild/test/integ.asset-build-spec.js.snapshot/CodeBuildAssetBuildSpecStack.template.json
  packages/@aws-cdk/aws-codebuild/test/integ.asset-build-spec.js.snapshot/asset.0ddfdbafee06424f04319f1476a7a991c4d29cdfc917e4c4c5fac49ade421ad4.yml
  packages/@aws-cdk/aws-codebuild/test/integ.asset-build-spec.js.snapshot/asset.73c20a669c041469f7fc3fc03d574b093b5b97e7c716f76c1e8117e6163e4dc4.bundle/index.js
  packages/@aws-cdk/aws-codebuild/test/integ.asset-build-spec.js.snapshot/cdk.out
  packages/@aws-cdk/aws-codebuild/test/integ.asset-build-spec.js.snapshot/integ.json
  packages/@aws-cdk/aws-codebuild/test/integ.asset-build-spec.js.snapshot/manifest.json
  packages/@aws-cdk/aws-codebuild/test/integ.asset-build-spec.js.snapshot/tree.json
  packages/@aws-cdk/aws-codebuild/test/integ.asset-build-spec.ts
Labels: p2, contribution/core

#24304 chore(rds): update aurora-mysql engine versions
  packages/@aws-cdk/aws-rds/lib/cluster-engine.ts
Labels: p2, contribution/core

#24303 chore(release): 2.66.1
  CHANGELOG.v2.alpha.md
  CHANGELOG.v2.md
  packages/@aws-cdk/aws-iam/lib/principals.ts
  packages/@aws-cdk/aws-iam/test/integ.saml-provider.js.snapshot/cdk-saml-provider.assets.json
  packages/@aws-cdk/aws-iam/test/integ.saml-provider.js.snapshot/cdk-saml-provider.template.json
  packages/@aws-cdk/aws-iam/test/integ.saml-provider.js.snapshot/manifest.json
  packages/@aws-cdk/aws-iam/test/integ.saml-provider.js.snapshot/tree.json
  packages/@aws-cdk/aws-iam/test/integ.saml-provider.ts
  packages/@aws-cdk/aws-iam/test/principals.test.ts
  version.v2.json
Labels: p2, contribution/core, pr/no-squash

#24292 chore(events): update integ tests for events
  packages/@aws-cdk/aws-events/test/integ.archive.ts
  packages/@aws-cdk/aws-events/test/integ.connection.ts
  packages/@aws-cdk/aws-events/test/integ.cross-account-rule.ts
  packages/@aws-cdk/aws-events/test/integ.eventbus.ts
  packages/@aws-cdk/aws-events/test/integ.rule.ts
Labels: p2, contribution/core

#24293 chore(iotevents): update integ tests to use IntegTest
  packages/@aws-cdk/aws-iotevents/package.json
  packages/@aws-cdk/aws-iotevents/test/integ.detector-model.js.snapshot/cdk.out
  packages/@aws-cdk/aws-iotevents/test/integ.detector-model.js.snapshot/detector-model-test-stack.assets.json
  packages/@aws-cdk/aws-iotevents/test/integ.detector-model.js.snapshot/integ.json
  packages/@aws-cdk/aws-iotevents/test/integ.detector-model.js.snapshot/manifest.json
  packages/@aws-cdk/aws-iotevents/test/integ.detector-model.js.snapshot/tree.json
  packages/@aws-cdk/aws-iotevents/test/integ.detector-model.ts
Labels: p2, contribution/core

#24294 chore: ignore lock files on integ tests
  .gitignore
Labels: p2, contribution/core

#24295 chore(location): update integ tests to use IntegTest construct
  packages/@aws-cdk/aws-location/test/integ.place-index.js.snapshot/PlaceIndexTestDefaultTestDeployAssert3F96C508.assets.json
  packages/@aws-cdk/aws-location/test/integ.place-index.js.snapshot/cdk-integ-location-place-index.assets.json
  packages/@aws-cdk/aws-location/test/integ.place-index.js.snapshot/cdk.out
  packages/@aws-cdk/aws-location/test/integ.place-index.js.snapshot/integ.json
  packages/@aws-cdk/aws-location/test/integ.place-index.js.snapshot/manifest.json
  packages/@aws-cdk/aws-location/test/integ.place-index.js.snapshot/tree.json
  packages/@aws-cdk/aws-location/test/integ.place-index.ts
Labels: p2, contribution/core

#24306 chore: delete module not in v2
  .github/workflows/issue-label-assign.yml
  packages/@aws-cdk/aws-dynamodb-global/.eslintrc.js
  packages/@aws-cdk/aws-dynamodb-global/.gitignore
  packages/@aws-cdk/aws-dynamodb-global/.npmignore
  packages/@aws-cdk/aws-dynamodb-global/LICENSE
  packages/@aws-cdk/aws-dynamodb-global/NOTICE
  packages/@aws-cdk/aws-dynamodb-global/README.md
  packages/@aws-cdk/aws-dynamodb-global/jest.config.js
  packages/@aws-cdk/aws-dynamodb-global/lambda-packages/.no-packagejson-validator
  packages/@aws-cdk/aws-dynamodb-global/lambda-packages/aws-global-table-coordinator/.gitignore
  packages/@aws-cdk/aws-dynamodb-global/lambda-packages/aws-global-table-coordinator/LICENSE
  packages/@aws-cdk/aws-dynamodb-global/lambda-packages/aws-global-table-coordinator/NOTICE
  packages/@aws-cdk/aws-dynamodb-global/lambda-packages/aws-global-table-coordinator/README.md
  packages/@aws-cdk/aws-dynamodb-global/lambda-packages/aws-global-table-coordinator/jest.config.js
  packages/@aws-cdk/aws-dynamodb-global/lambda-packages/aws-global-table-coordinator/lib/index.js
  packages/@aws-cdk/aws-dynamodb-global/lambda-packages/aws-global-table-coordinator/package.json
  packages/@aws-cdk/aws-dynamodb-global/lambda-packages/aws-global-table-coordinator/test/test.lambda.handler.js
  packages/@aws-cdk/aws-dynamodb-global/lib/aws-dynamodb-global.ts
  packages/@aws-cdk/aws-dynamodb-global/lib/global-table-coordinator.ts
  packages/@aws-cdk/aws-dynamodb-global/lib/index.ts
  packages/@aws-cdk/aws-dynamodb-global/package.json
  packages/@aws-cdk/aws-dynamodb-global/test/dynamodb-global.test.ts
  packages/@aws-cdk/aws-dynamodb-global/test/integ.dynamodb.global.js.snapshot/Default.template.json
  packages/@aws-cdk/aws-dynamodb-global/test/integ.dynamodb.global.js.snapshot/asset.94575de3fd18404e41e94a6c1d4b7a1eec2985fd23d2c11999d095e09667ba3a/index.js
  packages/@aws-cdk/aws-dynamodb-global/test/integ.dynamodb.global.js.snapshot/cdk.out
  packages/@aws-cdk/aws-dynamodb-global/test/integ.dynamodb.global.js.snapshot/globdynamodbintegCustomResource.template.json
  packages/@aws-cdk/aws-dynamodb-global/test/integ.dynamodb.global.js.snapshot/globdynamodbintegglobdynamodbinteguseast11DF47AEF.template.json
  packages/@aws-cdk/aws-dynamodb-global/test/integ.dynamodb.global.js.snapshot/globdynamodbintegglobdynamodbinteguseast23BC6B972.template.json
  packages/@aws-cdk/aws-dynamodb-global/test/integ.dynamodb.global.js.snapshot/globdynamodbintegglobdynamodbinteguswest2104B9501.template.json
  packages/@aws-cdk/aws-dynamodb-global/test/integ.dynamodb.global.js.snapshot/integ.json
  packages/@aws-cdk/aws-dynamodb-global/test/integ.dynamodb.global.js.snapshot/manifest.json
  packages/@aws-cdk/aws-dynamodb-global/test/integ.dynamodb.global.js.snapshot/tree.json
  packages/@aws-cdk/aws-dynamodb-global/test/integ.dynamodb.global.ts
  tests.txt
Labels: p2, contribution/core

#24312 chore(init-tests): update go test
  packages/@aws-cdk-testing/cli-integ/README.md
  packages/aws-cdk/test/integ/init/test-go-app.sh
Labels: p2, contribution/core

#24313 fix(cloudwatch): math expressions incorrectly warn about search and metrics
  packages/@aws-cdk/aws-cloudwatch/lib/metric.ts
  packages/@aws-cdk/aws-cloudwatch/test/metric-math.test.ts
Labels: p1, pr-linter/exempt-integ-test, beginning-contributor

#24324 chore(merge-back): 2.66.1
  CHANGELOG.v2.alpha.md
  CHANGELOG.v2.md
  packages/@aws-cdk/aws-iam/test/integ.saml-provider.js.snapshot/tree.json
  packages/@aws-cdk/aws-iam/test/integ.saml-provider.ts
  version.v2.json
Labels: p2, pr/no-squash, auto-approve

#24311 chore(lambda): update ADOT fact tables for v0.26.0 release
  packages/@aws-cdk/region-info/build-tools/fact-tables.ts
Labels: p2, beginning-contributor

#24334 chore: update v1 go test name
  packages/aws-cdk/test/integ/init/test-go-app.sh
Labels: p2, contribution/core

#24352 chore: asset-staging test always expects 'docker' invocation
  packages/@aws-cdk/core/test/private/asset-staging.test.ts
Labels: p2, contribution/core, pr-linter/exempt-integ-test

#23593 fix(ec2): userData in launchTemplate is created automatically when machineImege is provided
  packages/@aws-cdk/aws-autoscaling/test/integ.asg-lt.js.snapshot/aws-cdk-asg-integ.assets.json
  packages/@aws-cdk/aws-autoscaling/test/integ.asg-lt.js.snapshot/aws-cdk-asg-integ.template.json
  packages/@aws-cdk/aws-autoscaling/test/integ.asg-lt.js.snapshot/manifest.json
  packages/@aws-cdk/aws-autoscaling/test/integ.asg-lt.js.snapshot/tree.json
  packages/@aws-cdk/aws-ec2/lib/launch-template.ts
  packages/@aws-cdk/aws-ec2/test/integ.launch-template.js.snapshot/LambdaTestDefaultTestDeployAssert1AF2B360.assets.json
  packages/@aws-cdk/aws-ec2/test/integ.launch-template.js.snapshot/TestStack.assets.json
  packages/@aws-cdk/aws-ec2/test/integ.launch-template.js.snapshot/TestStack.template.json
  packages/@aws-cdk/aws-ec2/test/integ.launch-template.js.snapshot/aws-cdk-ec2-lt-metadata-1.assets.json
  packages/@aws-cdk/aws-ec2/test/integ.launch-template.js.snapshot/aws-cdk-ec2-lt-metadata-1.template.json
  packages/@aws-cdk/aws-ec2/test/integ.launch-template.js.snapshot/cdk.out
  packages/@aws-cdk/aws-ec2/test/integ.launch-template.js.snapshot/integ.json
  packages/@aws-cdk/aws-ec2/test/integ.launch-template.js.snapshot/manifest.json
  packages/@aws-cdk/aws-ec2/test/integ.launch-template.js.snapshot/tree.json
  packages/@aws-cdk/aws-ec2/test/integ.launch-template.ts
  packages/@aws-cdk/aws-ec2/test/launch-template.test.ts
  packages/@aws-cdk/aws-gamelift/test/integ.game-server-group.js.snapshot/GameServerGroupDefaultTestDeployAssertA631B19B.assets.json
  packages/@aws-cdk/aws-gamelift/test/integ.game-server-group.js.snapshot/aws-gamelift-game-server-group.assets.json
  packages/@aws-cdk/aws-gamelift/test/integ.game-server-group.js.snapshot/aws-gamelift-game-server-group.template.json
  packages/@aws-cdk/aws-gamelift/test/integ.game-server-group.js.snapshot/cdk.out
  packages/@aws-cdk/aws-gamelift/test/integ.game-server-group.js.snapshot/integ.json
  packages/@aws-cdk/aws-gamelift/test/integ.game-server-group.js.snapshot/manifest.json
  packages/@aws-cdk/aws-gamelift/test/integ.game-server-group.js.snapshot/tree.json
  packages/@aws-cdk/cx-api/FEATURE_FLAGS.md
  packages/@aws-cdk/cx-api/lib/features.ts
Labels: bug, p2, effort/small, admired-contributor

#24213 feat(eks): add helm flag --skip-crds
  packages/@aws-cdk/aws-eks/README.md
  packages/@aws-cdk/aws-eks/lib/helm-chart.ts
  packages/@aws-cdk/aws-eks/lib/kubectl-handler/helm/__init__.py
  packages/@aws-cdk/aws-eks/test/helm-chart.test.ts
  packages/@aws-cdk/aws-eks/test/integ.eks-helm-asset.js.snapshot/asset.92ea03f8b2e779503519f7781d06c03f95b46863db85f5c50a4e7debfd04be02/apply/__init__.py
  packages/@aws-cdk/aws-eks/test/integ.eks-helm-asset.js.snapshot/asset.92ea03f8b2e779503519f7781d06c03f95b46863db85f5c50a4e7debfd04be02/get/__init__.py
  packages/@aws-cdk/aws-eks/test/integ.eks-helm-asset.js.snapshot/asset.92ea03f8b2e779503519f7781d06c03f95b46863db85f5c50a4e7debfd04be02/helm/__init__.py
  packages/@aws-cdk/aws-eks/test/integ.eks-helm-asset.js.snapshot/asset.92ea03f8b2e779503519f7781d06c03f95b46863db85f5c50a4e7debfd04be02/index.py
  packages/@aws-cdk/aws-eks/test/integ.eks-helm-asset.js.snapshot/asset.92ea03f8b2e779503519f7781d06c03f95b46863db85f5c50a4e7debfd04be02/patch/__init__.py
  packages/@aws-cdk/aws-eks/test/integ.eks-helm-asset.js.snapshot/aws-cdk-eks-helm-test.assets.json
  packages/@aws-cdk/aws-eks/test/integ.eks-helm-asset.js.snapshot/aws-cdk-eks-helm-test.template.json
  packages/@aws-cdk/aws-eks/test/integ.eks-helm-asset.js.snapshot/awscdkekshelmtestawscdkawseksKubectlProvider207F42E4.nested.template.json
  packages/@aws-cdk/aws-eks/test/integ.eks-helm-asset.js.snapshot/manifest.json
  packages/@aws-cdk/aws-eks/test/integ.eks-helm-asset.js.snapshot/tree.json
  packages/@aws-cdk/aws-eks/test/integ.eks-helm-asset.ts
Labels: p2, feature-request, beginning-contributor

#24368 chore(rds): RDS VersionUP follow-up in 2023.2
  packages/@aws-cdk/aws-rds/lib/instance-engine.ts
Labels: p2, star-contributor

#24359 feat(remodel): make tests more directory agnostic
  packages/@aws-cdk/aws-ecr-assets/test/tarball-asset.test.ts
  packages/@aws-cdk/aws-lambda-nodejs/test/bundling.test.ts
  packages/@aws-cdk/core/test/runtime-info.test.ts
  tools/@aws-cdk/cfn2ts/lib/index.ts
  tools/@aws-cdk/remodel/lib/cli.ts
  tools/@aws-cdk/remodel/lib/template/packages/aws-cdk-lib/cloudformation-include/build.ts
  tools/@aws-cdk/remodel/lib/template/packages/aws-cdk-lib/jest.config.js
  tools/@aws-cdk/remodel/lib/template/packages/aws-cdk-lib/scripts/gen.ts
  tools/@aws-cdk/ubergen/lib/index.ts
Labels: p2, contribution/core

#24302 feat(bootstrap): prevent accidental bootstrap overwrites
  packages/@aws-cdk-testing/cli-integ/package.json
  packages/@aws-cdk-testing/cli-integ/tests/cli-integ-tests/bootstrapping.integtest.ts
  packages/aws-cdk/lib/api/bootstrap/bootstrap-props.ts
  packages/aws-cdk/lib/api/bootstrap/bootstrap-template.yaml
  packages/aws-cdk/lib/api/bootstrap/deploy-bootstrap.ts
  packages/aws-cdk/lib/api/toolkit-info.ts
  packages/aws-cdk/test/api/bootstrap2.test.ts
  packages/aws-cdk/test/api/cloudformation-deployments.test.ts
  packages/aws-cdk/test/util/mock-toolkitinfo.ts
Labels: p2, contribution/core, pr-linter/exempt-readme, pr-linter/exempt-integ-test, pr-linter/cli-integ-tested

#24377 feat(remodel): make codegen handle cfn-include cfn2ts-cfn-include-map
  tools/@aws-cdk/cfn2ts/lib/codegen.ts
  tools/@aws-cdk/cfn2ts/lib/index.ts
  tools/@aws-cdk/remodel/lib/cli.ts
  tools/@aws-cdk/remodel/lib/template/packages/aws-cdk-lib/scripts/gen.ts
Labels: p2, contribution/core

#24003 fix(cdk-assets): Error when building Docker Image Assets with Podman
  packages/cdk-assets/lib/private/docker.ts
  packages/cdk-assets/lib/private/shell.ts
  packages/cdk-assets/test/private/docker.test.ts
Labels: p2, feature-request, effort/small, pr-linter/exempt-integ-test, beginning-contributor

#23497 fix(ecr-assets): fix repeated deploys of stacks with tar assets
  packages/@aws-cdk/aws-ecr-assets/lib/tarball-asset.ts
  packages/@aws-cdk/aws-ecr-assets/package.json
  packages/@aws-cdk/aws-ecr-assets/test/demo-tarball-hello-world/hello-world.tar
  packages/@aws-cdk/aws-ecr-assets/test/integ.assets-tarball.js.snapshot/LoadFromTarballDefaultTestDeployAssert46673615.assets.json
  packages/@aws-cdk/aws-ecr-assets/test/integ.assets-tarball.js.snapshot/LoadFromTarballDefaultTestDeployAssert46673615.template.json
  packages/@aws-cdk/aws-ecr-assets/test/integ.assets-tarball.js.snapshot/asset.a5fbe3aa4a0e49fac7d3fbe7b913cf022d307bfad6ef1e88e06cc2a229523474.tar
  packages/@aws-cdk/aws-ecr-assets/test/integ.assets-tarball.js.snapshot/cdk.out
  packages/@aws-cdk/aws-ecr-assets/test/integ.assets-tarball.js.snapshot/integ-assets-tarball.assets.json
  packages/@aws-cdk/aws-ecr-assets/test/integ.assets-tarball.js.snapshot/integ-assets-tarball.template.json
  packages/@aws-cdk/aws-ecr-assets/test/integ.assets-tarball.js.snapshot/integ.json
  packages/@aws-cdk/aws-ecr-assets/test/integ.assets-tarball.js.snapshot/manifest.json
  packages/@aws-cdk/aws-ecr-assets/test/integ.assets-tarball.js.snapshot/tree.json
  packages/@aws-cdk/aws-ecr-assets/test/integ.assets-tarball.ts
  packages/@aws-cdk/aws-ecr-assets/test/tarball-asset.test.ts
Labels: bug, p2, effort/small, beginning-contributor
