Repository aws/aws-cdk, pull requests merged in 2023-12, with the labels that each got.

#28210 chore: update Contributors File
  CONTRIBUTORS.md
Labels: p2, auto-approve

#28219 chore(merge-back): 2.112.0
  CHANGELOG.v2.alpha.md
  CHANGELOG.v2.md
  version.v2.json
Labels: p2, pr/needs-community-review, pr/no-squash, auto-approve

#28221 chore: add changelog items that were missed during the 2.122.0 release
  CHANGELOG.v2.md
Labels: p2, contribution/core

#28222 feat: update AWS Service Spec
  packages/@aws-cdk/cloudformation-diff/package.json
  packages/@aws-cdk/integ-runner/package.json
  packages/aws-cdk-lib/aws-s3express/.jsiirc.json
  packages/aws-cdk-lib/aws-s3express/README.md
  packages/aws-cdk-lib/aws-s3express/index.ts
  packages/aws-cdk-lib/aws-s3express/lib/index.ts
  packages/aws-cdk-lib/index.ts
  packages/aws-cdk-lib/package.json
  packages/aws-cdk-lib/scripts/scope-map.json
  tools/@aws-cdk/spec2cdk/package.json
  yarn.lock
Labels: p2, dependencies, contribution/core, pr-linter/exempt-readme, pr-linter/exempt-test, auto-approve, pr-linter/exempt-integ-test

#28231 chore(merge-back): 2.113.0
  CHANGELOG.v2.alpha.md
  CHANGELOG.v2.md
  version.v2.json
Labels: p2, pr/needs-community-review, pr/no-squash, auto-approve

#28227 chore(spec2cdk): remove temporary patch schema aws-logs-loggroup.json after re:Invent launch
  tools/@aws-cdk/spec2cdk/temporary-schemas/us-east-1/aws-logs-loggroup.json
Labels: p2, contribution/core

#28224 chore(redshift-alpha): formatting typos
  packages/@aws-cdk/aws-redshift-alpha/lib/cluster.ts
Labels: p2, contribution/core

#27845 feat(scheduler-targets-alpha): `KinesisStreamPutRecord` Target
  packages/@aws-cdk/aws-scheduler-targets-alpha/README.md
  packages/@aws-cdk/aws-scheduler-targets-alpha/lib/index.ts
  packages/@aws-cdk/aws-scheduler-targets-alpha/lib/kinesis-stream-put-record.ts
  packages/@aws-cdk/aws-scheduler-targets-alpha/test/integ.kinesis-stream-put-record.js.snapshot/asset.2039afff5ee58473c609351d85a209bceb4ce0c16644a1baba0a0f8231c3ee17.bundle/index.js
  packages/@aws-cdk/aws-scheduler-targets-alpha/test/integ.kinesis-stream-put-record.js.snapshot/aws-cdk-scheduler-targets-kinesis-stream-put-record.assets.json
  packages/@aws-cdk/aws-scheduler-targets-alpha/test/integ.kinesis-stream-put-record.js.snapshot/aws-cdk-scheduler-targets-kinesis-stream-put-record.template.json
  packages/@aws-cdk/aws-scheduler-targets-alpha/test/integ.kinesis-stream-put-record.js.snapshot/cdk.out
  packages/@aws-cdk/aws-scheduler-targets-alpha/test/integ.kinesis-stream-put-record.js.snapshot/integ.json
  packages/@aws-cdk/aws-scheduler-targets-alpha/test/integ.kinesis-stream-put-record.js.snapshot/integrationtestkinesisstreamputrecordDefaultTestDeployAssert6B5E163F.assets.json
  packages/@aws-cdk/aws-scheduler-targets-alpha/test/integ.kinesis-stream-put-record.js.snapshot/integrationtestkinesisstreamputrecordDefaultTestDeployAssert6B5E163F.template.json
  packages/@aws-cdk/aws-scheduler-targets-alpha/test/integ.kinesis-stream-put-record.js.snapshot/manifest.json
  packages/@aws-cdk/aws-scheduler-targets-alpha/test/integ.kinesis-stream-put-record.js.snapshot/tree.json
  packages/@aws-cdk/aws-scheduler-targets-alpha/test/integ.kinesis-stream-put-record.ts
  packages/@aws-cdk/aws-scheduler-targets-alpha/test/kinesis-stream-put-record.test.ts
  packages/aws-cdk-lib/aws-kinesis/lib/stream.ts
  packages/aws-cdk-lib/aws-kinesis/test/stream.test.ts
Labels: p2, feature-request, effort/medium, star-contributor, pr/needs-maintainer-review

#28214 chore(apigateway): improve docs and default value settings for identity source in authorizer
  packages/aws-cdk-lib/aws-apigateway/lib/authorizers/cognito.ts
  packages/aws-cdk-lib/aws-apigateway/lib/authorizers/lambda.ts
Labels: p2, star-contributor

#28250 fix(apigatewayv2): export newly graduated apigatewayv2 modules
  packages/aws-cdk-lib/index.ts
Labels: bug, p2, pr-linter/exempt-test, pr-linter/exempt-integ-test, beginning-contributor

#28191 feat(appconfig-alpha): support for relative file paths when importing config
  packages/@aws-cdk/aws-appconfig-alpha/README.md
  packages/@aws-cdk/aws-appconfig-alpha/lib/configuration.ts
  packages/@aws-cdk/aws-appconfig-alpha/test/configuration.test.ts
  packages/@aws-cdk/aws-appconfig-alpha/test/integ.configuration.js.snapshot/appconfigconfigurationDefaultTestDeployAssert6752CD38.assets.json
  packages/@aws-cdk/aws-appconfig-alpha/test/integ.configuration.js.snapshot/asset.9eb41a5505d37607ac419321497a4f8c21cf0ee1f9b4a6b29aa04301aea5c7fd/index.py
  packages/@aws-cdk/aws-appconfig-alpha/test/integ.configuration.js.snapshot/asset.e976a796f036a5efbf44b99e44cfb5a961df08d8dbf7cd37e60bf216fb982a00/index.py
  packages/@aws-cdk/aws-appconfig-alpha/test/integ.configuration.js.snapshot/aws-appconfig-configuration.assets.json
  packages/@aws-cdk/aws-appconfig-alpha/test/integ.configuration.js.snapshot/aws-appconfig-configuration.template.json
  packages/@aws-cdk/aws-appconfig-alpha/test/integ.configuration.js.snapshot/cdk.out
  packages/@aws-cdk/aws-appconfig-alpha/test/integ.configuration.js.snapshot/integ.json
  packages/@aws-cdk/aws-appconfig-alpha/test/integ.configuration.js.snapshot/manifest.json
  packages/@aws-cdk/aws-appconfig-alpha/test/integ.configuration.js.snapshot/tree.json
  packages/@aws-cdk/aws-appconfig-alpha/test/integ.configuration.ts
  packages/@aws-cdk/aws-appconfig-alpha/test/schema.json
Labels: p2, feature-request, effort/small, valued-contributor

#28129 fix(iam): attaching a policy is not idempotent with imported resources
  packages/@aws-cdk-testing/framework-integ/test/aws-iam/test/integ.managed-policy.js.snapshot/ManagedPolicyIntegDefaultTestDeployAssert27007DC6.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-iam/test/integ.managed-policy.js.snapshot/aws-cdk-iam-managed-policy.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-iam/test/integ.managed-policy.js.snapshot/aws-cdk-iam-managed-policy.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-iam/test/integ.managed-policy.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-iam/test/integ.managed-policy.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-iam/test/integ.managed-policy.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-iam/test/integ.managed-policy.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-iam/test/integ.managed-policy.ts
  packages/@aws-cdk-testing/framework-integ/test/aws-iam/test/integ.role.ts
  packages/aws-cdk-lib/aws-iam/lib/managed-policy.ts
  packages/aws-cdk-lib/aws-iam/lib/policy.ts
  packages/aws-cdk-lib/aws-iam/test/managed-policy.test.ts
  packages/aws-cdk-lib/aws-iam/test/policy.test.ts
Labels: bug, p2, effort/small, distinguished-contributor

#28156 feat(appconfig-alpha): support for composite alarms
  packages/@aws-cdk/aws-appconfig-alpha/README.md
  packages/@aws-cdk/aws-appconfig-alpha/lib/environment.ts
  packages/@aws-cdk/aws-appconfig-alpha/test/environment.test.ts
  packages/@aws-cdk/aws-appconfig-alpha/test/integ.environment.js.snapshot/appconfigenvironmentDefaultTestDeployAssert75BD28E7.assets.json
  packages/@aws-cdk/aws-appconfig-alpha/test/integ.environment.js.snapshot/aws-appconfig-environment.assets.json
  packages/@aws-cdk/aws-appconfig-alpha/test/integ.environment.js.snapshot/aws-appconfig-environment.template.json
  packages/@aws-cdk/aws-appconfig-alpha/test/integ.environment.js.snapshot/cdk.out
  packages/@aws-cdk/aws-appconfig-alpha/test/integ.environment.js.snapshot/integ.json
  packages/@aws-cdk/aws-appconfig-alpha/test/integ.environment.js.snapshot/manifest.json
  packages/@aws-cdk/aws-appconfig-alpha/test/integ.environment.js.snapshot/tree.json
  packages/@aws-cdk/aws-appconfig-alpha/test/integ.environment.ts
Labels: p2, valued-contributor

#28118 feat(rds): grantConnect method enables iam auth to rds cluster
  packages/aws-cdk-lib/aws-rds/README.md
  packages/aws-cdk-lib/aws-rds/lib/cluster-ref.ts
  packages/aws-cdk-lib/aws-rds/lib/cluster.ts
  packages/aws-cdk-lib/aws-rds/test/cluster.test.ts
Labels: p2, contribution/core, pr-linter/exempt-integ-test, pr-linter/exemption-requested

#27742 fix(apigateway): move url property to RestApiBase
  packages/@aws-cdk-testing/framework-integ/test/aws-cloudfront-origins/test/integ.spec-rest-api-origin-custom-origin.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-cloudfront-origins/test/integ.spec-rest-api-origin-custom-origin.js.snapshot/integ-spec-rest-api-origin-custom-origin.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-cloudfront-origins/test/integ.spec-rest-api-origin-custom-origin.js.snapshot/integ-spec-rest-api-origin-custom-origin.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-cloudfront-origins/test/integ.spec-rest-api-origin-custom-origin.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-cloudfront-origins/test/integ.spec-rest-api-origin-custom-origin.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-cloudfront-origins/test/integ.spec-rest-api-origin-custom-origin.js.snapshot/restapiorigincustomoriginpathDefaultTestDeployAssertCD227A2A.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-cloudfront-origins/test/integ.spec-rest-api-origin-custom-origin.js.snapshot/restapiorigincustomoriginpathDefaultTestDeployAssertCD227A2A.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-cloudfront-origins/test/integ.spec-rest-api-origin-custom-origin.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-cloudfront-origins/test/integ.spec-rest-api-origin-custom-origin.ts
  packages/aws-cdk-lib/aws-apigateway/lib/restapi.ts
  packages/aws-cdk-lib/aws-apigateway/test/restapi.test.ts
  packages/aws-cdk-lib/aws-cloudfront-origins/lib/rest-api-origin.ts
Labels: p1, feature-request, effort/small, beginning-contributor, pr-linter/exemption-requested

#28082 fix(stepfunctions-tasks): mwaa service generates wrong action in role policy
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/aws-sdk/integ.call-aws-service-mwaa.js.snapshot/IntegTestDefaultTestDeployAssertE3E7D2A4.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/aws-sdk/integ.call-aws-service-mwaa.js.snapshot/IntegTestDefaultTestDeployAssertE3E7D2A4.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/aws-sdk/integ.call-aws-service-mwaa.js.snapshot/asset.4012e9468badb2b8e1a18d0513e222f2ad6246cf6ddc9f167fc9add9a48bb84e.bundle/index.js
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/aws-sdk/integ.call-aws-service-mwaa.js.snapshot/aws-stepfunctions-tasks-call-aws-service-mwaa-integ.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/aws-sdk/integ.call-aws-service-mwaa.js.snapshot/aws-stepfunctions-tasks-call-aws-service-mwaa-integ.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/aws-sdk/integ.call-aws-service-mwaa.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/aws-sdk/integ.call-aws-service-mwaa.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/aws-sdk/integ.call-aws-service-mwaa.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/aws-sdk/integ.call-aws-service-mwaa.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/aws-sdk/integ.call-aws-service-mwaa.ts
  packages/aws-cdk-lib/aws-stepfunctions-tasks/lib/aws-sdk/call-aws-service.ts
  packages/aws-cdk-lib/aws-stepfunctions-tasks/test/aws-sdk/call-aws-service.test.ts
Labels: bug, p2, star-contributor

#27842 feat(scheduler-targets-alpha): `KinesisDataFirehosePutRecord` Target
  packages/@aws-cdk/aws-scheduler-targets-alpha/README.md
  packages/@aws-cdk/aws-scheduler-targets-alpha/lib/index.ts
  packages/@aws-cdk/aws-scheduler-targets-alpha/lib/kinesis-data-firehose-put-record.ts
  packages/@aws-cdk/aws-scheduler-targets-alpha/test/integ.kinesis-data-firehose-put-record.js.snapshot/asset.2039afff5ee58473c609351d85a209bceb4ce0c16644a1baba0a0f8231c3ee17.bundle/index.js
  packages/@aws-cdk/aws-scheduler-targets-alpha/test/integ.kinesis-data-firehose-put-record.js.snapshot/aws-cdk-scheduler-targets-firehose-put-record.assets.json
  packages/@aws-cdk/aws-scheduler-targets-alpha/test/integ.kinesis-data-firehose-put-record.js.snapshot/aws-cdk-scheduler-targets-firehose-put-record.template.json
  packages/@aws-cdk/aws-scheduler-targets-alpha/test/integ.kinesis-data-firehose-put-record.js.snapshot/cdk.out
  packages/@aws-cdk/aws-scheduler-targets-alpha/test/integ.kinesis-data-firehose-put-record.js.snapshot/integ.json
  packages/@aws-cdk/aws-scheduler-targets-alpha/test/integ.kinesis-data-firehose-put-record.js.snapshot/integrationtestfirehoseputrecordDefaultTestDeployAssert781A189E.assets.json
  packages/@aws-cdk/aws-scheduler-targets-alpha/test/integ.kinesis-data-firehose-put-record.js.snapshot/integrationtestfirehoseputrecordDefaultTestDeployAssert781A189E.template.json
  packages/@aws-cdk/aws-scheduler-targets-alpha/test/integ.kinesis-data-firehose-put-record.js.snapshot/manifest.json
  packages/@aws-cdk/aws-scheduler-targets-alpha/test/integ.kinesis-data-firehose-put-record.js.snapshot/tree.json
  packages/@aws-cdk/aws-scheduler-targets-alpha/test/integ.kinesis-data-firehose-put-record.ts
  packages/@aws-cdk/aws-scheduler-targets-alpha/test/kinesis-data-firehose-put-record.test.ts
Labels: p2, feature-request, effort/medium, star-contributor, pr/needs-maintainer-review

#28197 chore(kms): prefer new `aliasArn` to `keyArn` for getting arn of an alias
  packages/aws-cdk-lib/aws-kms/lib/alias.ts
  packages/aws-cdk-lib/aws-kms/test/alias.test.ts
Labels: bug, p2, effort/medium, pr-linter/exempt-readme, pr-linter/exempt-integ-test, beginning-contributor

#28259 feat: update AWS Service Spec
  packages/@aws-cdk/cloudformation-diff/package.json
  packages/@aws-cdk/integ-runner/package.json
  packages/aws-cdk-lib/aws-arczonalshift/.jsiirc.json
  packages/aws-cdk-lib/aws-arczonalshift/README.md
  packages/aws-cdk-lib/aws-arczonalshift/index.ts
  packages/aws-cdk-lib/aws-arczonalshift/lib/index.ts
  packages/aws-cdk-lib/aws-workspacesthinclient/.jsiirc.json
  packages/aws-cdk-lib/aws-workspacesthinclient/README.md
  packages/aws-cdk-lib/aws-workspacesthinclient/index.ts
  packages/aws-cdk-lib/aws-workspacesthinclient/lib/index.ts
  packages/aws-cdk-lib/index.ts
  packages/aws-cdk-lib/package.json
  packages/aws-cdk-lib/scripts/scope-map.json
  tools/@aws-cdk/spec2cdk/package.json
  yarn.lock
Labels: p2, dependencies, contribution/core, pr-linter/exempt-readme, pr-linter/exempt-test, auto-approve, pr-linter/exempt-integ-test

#28260 chore: add author paulhcs to .mergify.yml and merit badger
  .github/workflows/github-merit-badger.yml
  .mergify.yml
Labels: p2, beginning-contributor

#28253 chore: update version of cdk-from-cfn
  packages/@aws-cdk/cli-lib-alpha/THIRD_PARTY_LICENSES
  packages/aws-cdk/THIRD_PARTY_LICENSES
  packages/aws-cdk/package.json
  packages/aws-cdk/test/commands/test-resources/stacks/S3Stack.java
  packages/aws-cdk/test/commands/test-resources/stacks/s3-stack.ts
  packages/aws-cdk/test/commands/test-resources/stacks/s3_stack.py
  yarn.lock
Labels: p2, contribution/core, pr-linter/cli-integ-tested

#28267 chore(merge-back): 2.114.0
  CHANGELOG.v2.alpha.md
  CHANGELOG.v2.md
  version.v2.json
Labels: p2, pr/needs-community-review, pr/no-squash, auto-approve

#28272 docs(stepfunctions-tasks): restore README
  packages/aws-cdk-lib/aws-stepfunctions-tasks/README.md
Labels: p2, pr/needs-community-review, star-contributor

#28273 chore(merge-back): 2.114.1
  CHANGELOG.v2.alpha.md
  CHANGELOG.v2.md
  version.v2.json
Labels: p2, pr/needs-community-review, pr/no-squash, auto-approve

#28269 feat(appconfig-alpha): add deploy method to configuration constructs
  packages/@aws-cdk/aws-appconfig-alpha/README.md
  packages/@aws-cdk/aws-appconfig-alpha/lib/configuration.ts
  packages/@aws-cdk/aws-appconfig-alpha/test/configuration.test.ts
  packages/@aws-cdk/aws-appconfig-alpha/test/integ.configuration.js.snapshot/.cache/e976a796f036a5efbf44b99e44cfb5a961df08d8dbf7cd37e60bf216fb982a00.zip
  packages/@aws-cdk/aws-appconfig-alpha/test/integ.configuration.js.snapshot/aws-appconfig-configuration.assets.json
  packages/@aws-cdk/aws-appconfig-alpha/test/integ.configuration.js.snapshot/aws-appconfig-configuration.template.json
  packages/@aws-cdk/aws-appconfig-alpha/test/integ.configuration.js.snapshot/manifest.json
  packages/@aws-cdk/aws-appconfig-alpha/test/integ.configuration.js.snapshot/tree.json
  packages/@aws-cdk/aws-appconfig-alpha/test/integ.configuration.ts
Labels: p2, valued-contributor

#28275 chore(aws-cdk-lib): fix error message using deprecated 'name' property
  packages/aws-cdk-lib/scripts/submodules/index.ts
Labels: p2, contribution/core, pr/needs-maintainer-review

#28274 feat(rds): support RDS for SQL Server 16.00.4095.4.v1
  packages/aws-cdk-lib/aws-rds/lib/instance-engine.ts
Labels: p2, pr-linter/exempt-readme, pr-linter/exempt-test, pr-linter/exempt-integ-test, star-contributor

#28277 chore: restrict `@aws-sdk/*` updates
  .github/workflows/yarn-upgrade.yml
Labels: p2, contribution/core

#28038 fix(rds): publiclyAccessible=false set on an instance is ignored when cluster is placed in a public subnet
  packages/@aws-cdk-testing/framework-integ/test/aws-rds/test/integ.cluster-public-subnets.js.snapshot/asset.a099fdfc61c84ffc56cef4fb2c9472483623ac865ce5d8fca88c89cf60d48d03/__entrypoint__.js
  packages/@aws-cdk-testing/framework-integ/test/aws-rds/test/integ.cluster-public-subnets.js.snapshot/asset.a099fdfc61c84ffc56cef4fb2c9472483623ac865ce5d8fca88c89cf60d48d03/index.js
  packages/@aws-cdk-testing/framework-integ/test/aws-rds/test/integ.cluster-public-subnets.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-rds/test/integ.cluster-public-subnets.js.snapshot/integ-aurora-pub-sn-cluster.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-rds/test/integ.cluster-public-subnets.js.snapshot/integ-aurora-pub-sn-cluster.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-rds/test/integ.cluster-public-subnets.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-rds/test/integ.cluster-public-subnets.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-rds/test/integ.cluster-public-subnets.js.snapshot/testaurorapubsnclusterDefaultTestDeployAssert6E7F54F3.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-rds/test/integ.cluster-public-subnets.js.snapshot/testaurorapubsnclusterDefaultTestDeployAssert6E7F54F3.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-rds/test/integ.cluster-public-subnets.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-rds/test/integ.cluster-public-subnets.ts
  packages/aws-cdk-lib/aws-rds/README.md
  packages/aws-cdk-lib/aws-rds/lib/aurora-cluster-instance.ts
  packages/aws-cdk-lib/aws-rds/lib/instance.ts
  packages/aws-cdk-lib/aws-rds/test/cluster.test.ts
Labels: bug, p2, effort/medium, beginning-contributor

#24308 fix(redshift): tables were dropped on table name change
  packages/@aws-cdk/aws-redshift-alpha/README.md
  packages/@aws-cdk/aws-redshift-alpha/lib/private/database-query-provider/table.ts
  packages/@aws-cdk/aws-redshift-alpha/test/database-query-provider/table.test.ts
  packages/@aws-cdk/aws-redshift-alpha/test/integ.cluster-reboot.js.snapshot/asset.f3de7fa69bbae9bbe9472b98f9b1b3626a9ee748b2fd5895278331be04efa56b.bundle/index.js
  packages/@aws-cdk/aws-redshift-alpha/test/integ.cluster-reboot.js.snapshot/aws-cdk-redshift-cluster-create.assets.json
  packages/@aws-cdk/aws-redshift-alpha/test/integ.cluster-reboot.js.snapshot/aws-cdk-redshift-cluster-create.template.json
  packages/@aws-cdk/aws-redshift-alpha/test/integ.cluster-reboot.js.snapshot/aws-cdk-redshift-cluster-update.assets.json
  packages/@aws-cdk/aws-redshift-alpha/test/integ.cluster-reboot.js.snapshot/aws-cdk-redshift-cluster-update.template.json
  packages/@aws-cdk/aws-redshift-alpha/test/integ.cluster-reboot.js.snapshot/awscdkredshiftreboottestDefaultTestDeployAssert1AE11B34.assets.json
  packages/@aws-cdk/aws-redshift-alpha/test/integ.cluster-reboot.js.snapshot/awscdkredshiftreboottestDefaultTestDeployAssert1AE11B34.template.json
  packages/@aws-cdk/aws-redshift-alpha/test/integ.cluster-reboot.js.snapshot/manifest.json
  packages/@aws-cdk/aws-redshift-alpha/test/integ.cluster-reboot.js.snapshot/tree.json
  packages/@aws-cdk/aws-redshift-alpha/test/integ.cluster-reboot.ts
  packages/@aws-cdk/aws-redshift-alpha/test/integ.database-columnid.js.snapshot/aws-cdk-redshift-cluster-database.assets.json
  packages/@aws-cdk/aws-redshift-alpha/test/integ.database-columnid.js.snapshot/integ.json
  packages/@aws-cdk/aws-redshift-alpha/test/integ.database-columnid.js.snapshot/redshiftclusterdatabaseintegDefaultTestDeployAssert4339FB48.assets.json
  packages/@aws-cdk/aws-redshift-alpha/test/integ.database.js.snapshot/asset.5fa8a88136dc7e690e28026dcb3452a4d2f80f327bb49094dc1e3c39d551c52f/handler-name.js
  packages/@aws-cdk/aws-redshift-alpha/test/integ.database.js.snapshot/asset.5fa8a88136dc7e690e28026dcb3452a4d2f80f327bb49094dc1e3c39d551c52f/index.js
  packages/@aws-cdk/aws-redshift-alpha/test/integ.database.js.snapshot/asset.5fa8a88136dc7e690e28026dcb3452a4d2f80f327bb49094dc1e3c39d551c52f/privileges.js
  packages/@aws-cdk/aws-redshift-alpha/test/integ.database.js.snapshot/asset.5fa8a88136dc7e690e28026dcb3452a4d2f80f327bb49094dc1e3c39d551c52f/redshift-data.js
  packages/@aws-cdk/aws-redshift-alpha/test/integ.database.js.snapshot/asset.5fa8a88136dc7e690e28026dcb3452a4d2f80f327bb49094dc1e3c39d551c52f/table.js
  packages/@aws-cdk/aws-redshift-alpha/test/integ.database.js.snapshot/asset.5fa8a88136dc7e690e28026dcb3452a4d2f80f327bb49094dc1e3c39d551c52f/types.js
  packages/@aws-cdk/aws-redshift-alpha/test/integ.database.js.snapshot/asset.5fa8a88136dc7e690e28026dcb3452a4d2f80f327bb49094dc1e3c39d551c52f/user.js
  packages/@aws-cdk/aws-redshift-alpha/test/integ.database.js.snapshot/asset.5fa8a88136dc7e690e28026dcb3452a4d2f80f327bb49094dc1e3c39d551c52f/util.js
  packages/@aws-cdk/aws-redshift-alpha/test/integ.database.js.snapshot/asset.e275fde8d2a03c793e28878ff6a48e84af45d2655f0c79418b5b86f2add826f7/table.js
  packages/@aws-cdk/aws-redshift-alpha/test/integ.database.js.snapshot/aws-cdk-redshift-cluster-database.assets.json
  packages/@aws-cdk/aws-redshift-alpha/test/integ.database.js.snapshot/aws-cdk-redshift-cluster-database.template.json
  packages/@aws-cdk/aws-redshift-alpha/test/integ.database.js.snapshot/manifest.json
  packages/@aws-cdk/aws-redshift-alpha/test/integ.database.js.snapshot/tree.json
  packages/@aws-cdk/aws-redshift-alpha/test/integ.database.ts
Labels: bug, p2, effort/medium, repeat-contributor

#28295 chore(logs): update comment to property
  packages/aws-cdk-lib/aws-logs/lib/log-group.ts
Labels: p2, pr/needs-community-review, beginning-contributor

#28296 chore(gamelift): fix some horrible formatting errors
  packages/@aws-cdk/aws-gamelift-alpha/lib/alias.ts
  packages/@aws-cdk/aws-gamelift-alpha/lib/build-fleet.ts
  packages/@aws-cdk/aws-gamelift-alpha/lib/build.ts
  packages/@aws-cdk/aws-gamelift-alpha/lib/content.ts
  packages/@aws-cdk/aws-gamelift-alpha/lib/fleet-base.ts
  packages/@aws-cdk/aws-gamelift-alpha/lib/game-server-group.ts
  packages/@aws-cdk/aws-gamelift-alpha/lib/game-session-queue.ts
  packages/@aws-cdk/aws-gamelift-alpha/lib/matchmaking-configuration.ts
  packages/@aws-cdk/aws-gamelift-alpha/lib/matchmaking-ruleset-body.ts
  packages/@aws-cdk/aws-gamelift-alpha/lib/matchmaking-ruleset.ts
  packages/@aws-cdk/aws-gamelift-alpha/lib/queued-matchmaking-configuration.ts
  packages/@aws-cdk/aws-gamelift-alpha/lib/script.ts
  packages/@aws-cdk/aws-gamelift-alpha/lib/standalone-matchmaking-configuration.ts
Labels: p2, contribution/core

#28287 feat(eks): support Bottlerocket Nvidia AMIs
  packages/aws-cdk-lib/aws-eks/README.md
  packages/aws-cdk-lib/aws-eks/lib/managed-nodegroup.ts
  packages/aws-cdk-lib/aws-eks/test/nodegroup.test.ts
Labels: p2, feature-request, effort/small, pr-linter/exempt-integ-test, distinguished-contributor, pr-linter/exemption-requested

#28307 fix(scheduler): typo in metricSentToDLQ... methods
  packages/@aws-cdk/aws-scheduler-alpha/lib/group.ts
  packages/@aws-cdk/aws-scheduler-alpha/lib/schedule.ts
Labels: p2, pr-linter/exempt-test, pr-linter/exempt-integ-test

#28305 chore: add awsmjs to core contributors
  .github/workflows/github-merit-badger.yml
  .mergify.yml
Labels: p2, contribution/core

#28264 fix(appconfig-alpha): extensions always create cdk diff
  packages/@aws-cdk/aws-appconfig-alpha/lib/application.ts
  packages/@aws-cdk/aws-appconfig-alpha/lib/configuration.ts
  packages/@aws-cdk/aws-appconfig-alpha/lib/environment.ts
  packages/@aws-cdk/aws-appconfig-alpha/lib/extension.ts
  packages/@aws-cdk/aws-appconfig-alpha/test/application.test.ts
  packages/@aws-cdk/aws-appconfig-alpha/test/extension.test.ts
  packages/@aws-cdk/aws-appconfig-alpha/test/integ.extension.js.snapshot/aws-appconfig-extension.assets.json
  packages/@aws-cdk/aws-appconfig-alpha/test/integ.extension.js.snapshot/aws-appconfig-extension.template.json
  packages/@aws-cdk/aws-appconfig-alpha/test/integ.extension.js.snapshot/awsappconfigextensionMyApplicationappconfigextensionDefaultTestDeployAssert64BA6C4E.assets.json
  packages/@aws-cdk/aws-appconfig-alpha/test/integ.extension.js.snapshot/cdk.out
  packages/@aws-cdk/aws-appconfig-alpha/test/integ.extension.js.snapshot/integ.json
  packages/@aws-cdk/aws-appconfig-alpha/test/integ.extension.js.snapshot/manifest.json
  packages/@aws-cdk/aws-appconfig-alpha/test/integ.extension.js.snapshot/tree.json
  packages/@aws-cdk/aws-appconfig-alpha/test/integ.extension.ts
Labels: bug, p2, effort/small, valued-contributor, pr/needs-maintainer-review

#28324 chore: include basic changelog in service spec database upgrade PRs
  .github/workflows/spec-update.yml
Labels: p2, contribution/core

#28299 docs(apigateway): set integrationHttpMethod for vpc link integration
  packages/aws-cdk-lib/aws-apigateway/README.md
Labels: p2, star-contributor

#28276 feat(stepfunctions-tasks): support for the Step Functions optimized integration for Bedrock InvokeModel API
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/bedrock/integ.invoke-model.js.snapshot/InvokeModelDefaultTestDeployAssert9C0D2DFC.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/bedrock/integ.invoke-model.js.snapshot/InvokeModelDefaultTestDeployAssert9C0D2DFC.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/bedrock/integ.invoke-model.js.snapshot/aws-stepfunctions-tasks-bedrock-invoke-model-integ.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/bedrock/integ.invoke-model.js.snapshot/aws-stepfunctions-tasks-bedrock-invoke-model-integ.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/bedrock/integ.invoke-model.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/bedrock/integ.invoke-model.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/bedrock/integ.invoke-model.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/bedrock/integ.invoke-model.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/bedrock/integ.invoke-model.ts
  packages/aws-cdk-lib/aws-bedrock/.jsiirc.json
  packages/aws-cdk-lib/aws-bedrock/README.md
  packages/aws-cdk-lib/aws-bedrock/index.ts
  packages/aws-cdk-lib/aws-bedrock/lib/foundation-model.ts
  packages/aws-cdk-lib/aws-bedrock/lib/index.ts
  packages/aws-cdk-lib/aws-bedrock/lib/model-base.ts
  packages/aws-cdk-lib/aws-bedrock/lib/provisioned-model.ts
  packages/aws-cdk-lib/aws-bedrock/test/model.test.ts
  packages/aws-cdk-lib/aws-stepfunctions-tasks/README.md
  packages/aws-cdk-lib/aws-stepfunctions-tasks/lib/bedrock/invoke-model.ts
  packages/aws-cdk-lib/aws-stepfunctions-tasks/lib/index.ts
  packages/aws-cdk-lib/aws-stepfunctions-tasks/test/bedrock/invoke-model.test.ts
  packages/aws-cdk-lib/index.ts
  packages/aws-cdk-lib/package.json
Labels: p2, feature-request, pr/needs-community-review, effort/medium, admired-contributor

#28327 fix(stepfunctions-tasks): missing tags & perms for emr cluster creation
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/emr/integ.emr-create-cluster-with-spot-instance-fleet.js.snapshot/EmrCreateClusterTestDefaultTestDeployAssert697DC891.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/emr/integ.emr-create-cluster-with-spot-instance-fleet.js.snapshot/aws-cdk-emr-create-cluster-with-spot-instance-fleet.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/emr/integ.emr-create-cluster-with-spot-instance-fleet.js.snapshot/aws-cdk-emr-create-cluster-with-spot-instance-fleet.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/emr/integ.emr-create-cluster-with-spot-instance-fleet.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/emr/integ.emr-create-cluster-with-spot-instance-fleet.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/emr/integ.emr-create-cluster-with-spot-instance-fleet.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/emr/integ.emr-create-cluster-with-spot-instance-fleet.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/emr/integ.emr-create-cluster-with-spot-instance-fleet.ts
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/emr/integ.emr-create-cluster-with-tags.js.snapshot/EmrCreateClusterTestDefaultTestDeployAssert697DC891.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/emr/integ.emr-create-cluster-with-tags.js.snapshot/aws-cdk-emr-create-cluster-tags.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/emr/integ.emr-create-cluster-with-tags.js.snapshot/aws-cdk-emr-create-cluster-tags.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/emr/integ.emr-create-cluster-with-tags.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/emr/integ.emr-create-cluster-with-tags.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/emr/integ.emr-create-cluster-with-tags.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/emr/integ.emr-create-cluster-with-tags.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/emr/integ.emr-create-cluster-with-tags.ts
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/emr/integ.emr-create-cluster-with-v1-policy.js.snapshot/EmrCreateClusterTestDefaultTestDeployAssert697DC891.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/emr/integ.emr-create-cluster-with-v1-policy.js.snapshot/aws-cdk-emr-create-cluster-v1-policy.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/emr/integ.emr-create-cluster-with-v1-policy.js.snapshot/aws-cdk-emr-create-cluster-v1-policy.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/emr/integ.emr-create-cluster-with-v1-policy.js.snapshot/aws-cdk-emr-create-cluster.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/emr/integ.emr-create-cluster-with-v1-policy.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/emr/integ.emr-create-cluster-with-v1-policy.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/emr/integ.emr-create-cluster-with-v1-policy.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/emr/integ.emr-create-cluster-with-v1-policy.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/emr/integ.emr-create-cluster-with-v1-policy.ts
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/emr/integ.emr-create-cluster-with-v2-policy.js.snapshot/EmrCreateClusterTestDefaultTestDeployAssert697DC891.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/emr/integ.emr-create-cluster-with-v2-policy.js.snapshot/aws-cdk-emr-create-cluster-v2-policy.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/emr/integ.emr-create-cluster-with-v2-policy.js.snapshot/aws-cdk-emr-create-cluster-v2-policy.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/emr/integ.emr-create-cluster-with-v2-policy.js.snapshot/aws-cdk-emr-create-cluster.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/emr/integ.emr-create-cluster-with-v2-policy.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/emr/integ.emr-create-cluster-with-v2-policy.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/emr/integ.emr-create-cluster-with-v2-policy.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/emr/integ.emr-create-cluster-with-v2-policy.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/emr/integ.emr-create-cluster-with-v2-policy.ts
  packages/aws-cdk-lib/aws-stepfunctions-tasks/lib/emr/emr-create-cluster.ts
  packages/aws-cdk-lib/aws-stepfunctions-tasks/test/emr/emr-create-cluster.test.ts
Labels: p2, pr/needs-community-review, star-contributor

#27736 feat(stepfunctions-tasks): runtime role in EmrAddStep
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/emr/integ.emr-create-cluster-add-step-runtime-role.js.snapshot/EmrCreateClusterTestDefaultTestDeployAssert697DC891.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/emr/integ.emr-create-cluster-add-step-runtime-role.js.snapshot/EmrCreateClusterTestDefaultTestDeployAssert697DC891.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/emr/integ.emr-create-cluster-add-step-runtime-role.js.snapshot/aws-cdk-emr-add-step-runtime-role.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/emr/integ.emr-create-cluster-add-step-runtime-role.js.snapshot/aws-cdk-emr-add-step-runtime-role.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/emr/integ.emr-create-cluster-add-step-runtime-role.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/emr/integ.emr-create-cluster-add-step-runtime-role.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/emr/integ.emr-create-cluster-add-step-runtime-role.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/emr/integ.emr-create-cluster-add-step-runtime-role.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/emr/integ.emr-create-cluster-add-step-runtime-role.ts
  packages/aws-cdk-lib/aws-stepfunctions-tasks/README.md
  packages/aws-cdk-lib/aws-stepfunctions-tasks/lib/emr/emr-add-step.ts
  packages/aws-cdk-lib/aws-stepfunctions-tasks/test/emr/emr-add-step.test.ts
  packages/aws-cdk-lib/awslint.json
Labels: p2, feature-request, effort/medium, admired-contributor, pr/needs-maintainer-review

#28335 chore(stepfunctions-tasks): update integ test to deploy emr cluster with tags
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/emr/integ.emr-create-cluster-with-tags.js.snapshot/aws-cdk-emr-create-cluster-tags.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/emr/integ.emr-create-cluster-with-tags.js.snapshot/aws-cdk-emr-create-cluster-tags.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/emr/integ.emr-create-cluster-with-tags.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/emr/integ.emr-create-cluster-with-tags.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/emr/integ.emr-create-cluster-with-tags.ts
Labels: p2, star-contributor, pr/needs-maintainer-review

#28351 chore: npm-check-updates && yarn upgrade
  package.json
  packages/@aws-cdk-testing/cli-integ/package.json
  packages/@aws-cdk-testing/framework-integ/package.json
  packages/@aws-cdk/cli-lib-alpha/package.json
  packages/@aws-cdk/custom-resource-handlers/package.json
  packages/@aws-cdk/integ-runner/package.json
  packages/aws-cdk-lib/package.json
  packages/aws-cdk/THIRD_PARTY_LICENSES
  packages/aws-cdk/lib/init-templates/app/typescript/package.json
  packages/aws-cdk/lib/init-templates/lib/typescript/package.json
  packages/aws-cdk/lib/init-templates/sample-app/typescript/package.json
  packages/aws-cdk/package.json
  packages/awslint/package.json
  packages/cdk-assets/package.json
  tools/@aws-cdk/cdk-build-tools/package.json
  tools/@aws-cdk/eslint-plugin/package.json
  tools/@aws-cdk/lazify/package.json
  tools/@aws-cdk/node-bundle/package.json
  tools/@aws-cdk/pkglint/package.json
  yarn.lock
Labels: p2, dependencies, contribution/core, auto-approve

#28306 feat(scheduler): start and end time for schedule construct
  packages/@aws-cdk/aws-scheduler-alpha/README.md
  packages/@aws-cdk/aws-scheduler-alpha/lib/schedule.ts
  packages/@aws-cdk/aws-scheduler-alpha/test/integ.schedule.js.snapshot/aws-cdk-scheduler-schedule.assets.json
  packages/@aws-cdk/aws-scheduler-alpha/test/integ.schedule.js.snapshot/aws-cdk-scheduler-schedule.template.json
  packages/@aws-cdk/aws-scheduler-alpha/test/integ.schedule.js.snapshot/cdk.out
  packages/@aws-cdk/aws-scheduler-alpha/test/integ.schedule.js.snapshot/integ.json
  packages/@aws-cdk/aws-scheduler-alpha/test/integ.schedule.js.snapshot/integtestscheduleDefaultTestDeployAssert24CB3896.assets.json
  packages/@aws-cdk/aws-scheduler-alpha/test/integ.schedule.js.snapshot/manifest.json
  packages/@aws-cdk/aws-scheduler-alpha/test/integ.schedule.js.snapshot/tree.json
  packages/@aws-cdk/aws-scheduler-alpha/test/integ.schedule.ts
  packages/@aws-cdk/aws-scheduler-alpha/test/schedule.test.ts
Labels: p2, valued-contributor

#28345 feat(rds): support RDS for MariaDB 10.11.6, 10.6.16, 10.5.23 and 10.4.32
  packages/aws-cdk-lib/aws-rds/lib/instance-engine.ts
Labels: p2, pr-linter/exempt-readme, pr-linter/exempt-test, pr-linter/exempt-integ-test, star-contributor

#28346 feat(cloud9-alpha): support image ids for Amazon Linux 2023 and Ubuntu 22.04
  packages/@aws-cdk/aws-cloud9-alpha/lib/environment.ts
  packages/@aws-cdk/aws-cloud9-alpha/test/cloud9.environment.test.ts
Labels: p2, pr-linter/exempt-readme, pr-linter/exempt-test, pr-linter/exempt-integ-test, star-contributor

#28364 chore(merge-back): 2.115.0
  CHANGELOG.v2.alpha.md
  CHANGELOG.v2.md
  version.v2.json
Labels: p2, pr/needs-community-review, pr/no-squash, auto-approve

#28365 chore(cdk-testing): fix init-go canary
  packages/@aws-cdk-testing/cli-integ/tests/init-go/init-go.integtest.ts
Labels: p2, contribution/core

#27036 feat(ecs): Support specifying revision of task definition
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs/test/fargate/integ.custom-task-revision.js.snapshot/EcsCustomTaskRevisionDefaultTestDeployAssert0E9C7509.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs/test/fargate/integ.custom-task-revision.js.snapshot/EcsCustomTaskRevisionDefaultTestDeployAssert0E9C7509.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs/test/fargate/integ.custom-task-revision.js.snapshot/aws-ecs-integ-custom-task-revision.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs/test/fargate/integ.custom-task-revision.js.snapshot/aws-ecs-integ-custom-task-revision.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs/test/fargate/integ.custom-task-revision.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs/test/fargate/integ.custom-task-revision.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs/test/fargate/integ.custom-task-revision.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs/test/fargate/integ.custom-task-revision.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs/test/fargate/integ.custom-task-revision.ts
  packages/aws-cdk-lib/aws-ecs/README.md
  packages/aws-cdk-lib/aws-ecs/lib/base/base-service.ts
  packages/aws-cdk-lib/aws-ecs/lib/base/task-definition.ts
  packages/aws-cdk-lib/aws-ecs/test/base-service.test.ts
  packages/aws-cdk-lib/aws-ecs/test/task-definition.test.ts
Labels: p2, feature-request, effort/medium, beginning-contributor, pr/needs-maintainer-review

#28370 feat(rds): support aurora mysql 3.05.1
  packages/aws-cdk-lib/aws-rds/lib/cluster-engine.ts
Labels: p2, pr-linter/exempt-readme, pr-linter/exempt-test, pr-linter/exempt-integ-test, star-contributor

#28373 chore(amplify-alpha): add dependency from @aws-cdk/custom-resource-handlers
  packages/@aws-cdk/aws-amplify-alpha/package.json
Labels: p2, effort/small, contribution/core, pr-linter/exempt-integ-test

#28303 fix(secretsmanager): cannot set hourly rotation
  packages/@aws-cdk-testing/framework-integ/test/aws-docdb/test/integ.cluster-rotation.lit.js.snapshot/aws-cdk-docdb-cluster-rotation.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-docdb/test/integ.cluster-rotation.lit.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-rds/test/integ.cluster-rotation.lit.js.snapshot/aws-cdk-rds-cluster-rotation.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-rds/test/integ.cluster-rotation.lit.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-rds/test/integ.cluster-snapshot.js.snapshot/cdk-integ-cluster-snapshot.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-rds/test/integ.cluster-snapshot.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-rds/test/integ.instance.lit.js.snapshot/aws-cdk-rds-instance.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-rds/test/integ.instance.lit.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-rds/test/integ.serverless-cluster-secret-rotation-custom-names.js.snapshot/aws-cdk-rds-integ-secret-rotation.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-rds/test/integ.serverless-cluster-secret-rotation-custom-names.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-rds/test/integ.serverless-cluster-secret-rotation.js.snapshot/aws-cdk-rds-integ-secret-rotation.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-rds/test/integ.serverless-cluster-secret-rotation.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-secretsmanager/test/integ.hosted-rotation.js.snapshot/cdk-integ-secret-hosted-rotation.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-secretsmanager/test/integ.hosted-rotation.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-secretsmanager/test/integ.lambda-rotation.js.snapshot/cdk-integ-secret-lambda-rotation.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-secretsmanager/test/integ.lambda-rotation.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-secretsmanager/test/integ.lambda-rotation.ts
  packages/aws-cdk-lib/aws-docdb/test/cluster.test.ts
  packages/aws-cdk-lib/aws-rds/test/cluster.test.ts
  packages/aws-cdk-lib/aws-rds/test/instance.test.ts
  packages/aws-cdk-lib/aws-secretsmanager/lib/rotation-schedule.ts
  packages/aws-cdk-lib/aws-secretsmanager/test/rotation-schedule.test.ts
  packages/aws-cdk-lib/aws-secretsmanager/test/secret-rotation.test.ts
Labels: bug, p2, effort/medium, distinguished-contributor

#27913 feat(stepfunctions): support Map ItemProcessor
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions/test/integ.map-distributed.js.snapshot/cdk-stepfunctions-map-distributed-stack.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions/test/integ.map-distributed.js.snapshot/cdk-stepfunctions-map-distributed-stack.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions/test/integ.map-distributed.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions/test/integ.map-distributed.js.snapshot/cdkstepfunctionsmapdistributedintegDefaultTestDeployAssert69F30423.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions/test/integ.map-distributed.js.snapshot/cdkstepfunctionsmapdistributedintegDefaultTestDeployAssert69F30423.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions/test/integ.map-distributed.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions/test/integ.map-distributed.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions/test/integ.map-distributed.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions/test/integ.map-distributed.ts
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions/test/integ.map-inline.js.snapshot/cdk-stepfunctions-map-inline-stack.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions/test/integ.map-inline.js.snapshot/cdk-stepfunctions-map-inline-stack.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions/test/integ.map-inline.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions/test/integ.map-inline.js.snapshot/cdkstepfunctionsmapinlineintegDefaultTestDeployAssertD29BA3EB.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions/test/integ.map-inline.js.snapshot/cdkstepfunctionsmapinlineintegDefaultTestDeployAssertD29BA3EB.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions/test/integ.map-inline.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions/test/integ.map-inline.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions/test/integ.map-inline.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions/test/integ.map-inline.ts
  packages/aws-cdk-lib/aws-stepfunctions/README.md
  packages/aws-cdk-lib/aws-stepfunctions/lib/states/map.ts
  packages/aws-cdk-lib/aws-stepfunctions/lib/states/state.ts
  packages/aws-cdk-lib/aws-stepfunctions/lib/types.ts
  packages/aws-cdk-lib/aws-stepfunctions/test/map.test.ts
Labels: p2, feature-request, distinguished-contributor

#28316 feat(apigateway): validate integrationHttpMethod with non-MOCK integration types
  packages/aws-cdk-lib/aws-apigateway/lib/integration.ts
  packages/aws-cdk-lib/aws-apigateway/test/integration.test.ts
  packages/aws-cdk-lib/aws-apigateway/test/method.test.ts
Labels: p2, pr-linter/exempt-readme, pr-linter/exempt-integ-test, distinguished-contributor

#28367 docs(lambda): clarify FunctionOptions.allowAllOutbound property
  packages/aws-cdk-lib/aws-lambda/lib/function.ts
Labels: p2, valued-contributor

#28098 feat(scheduler): flexible time windows
  packages/@aws-cdk/aws-scheduler-alpha/README.md
  packages/@aws-cdk/aws-scheduler-alpha/lib/schedule.ts
  packages/@aws-cdk/aws-scheduler-alpha/rosetta/default.ts-fixture
  packages/@aws-cdk/aws-scheduler-alpha/test/integ.schedule.js.snapshot/aws-cdk-scheduler-schedule.assets.json
  packages/@aws-cdk/aws-scheduler-alpha/test/integ.schedule.js.snapshot/aws-cdk-scheduler-schedule.template.json
  packages/@aws-cdk/aws-scheduler-alpha/test/integ.schedule.js.snapshot/manifest.json
  packages/@aws-cdk/aws-scheduler-alpha/test/integ.schedule.js.snapshot/tree.json
  packages/@aws-cdk/aws-scheduler-alpha/test/integ.schedule.ts
  packages/@aws-cdk/aws-scheduler-alpha/test/schedule.test.ts
Labels: p2, repeat-contributor, pr/needs-maintainer-review

#28232 chore(sqs): use ICfnQueue wherever possible
  packages/@aws-cdk/aws-appconfig-alpha/lib/extension.ts
  packages/@aws-cdk/aws-iot-actions-alpha/lib/sqs-queue-action.ts
  packages/aws-cdk-lib/aws-autoscaling-hooktargets/lib/queue-hook.ts
  packages/aws-cdk-lib/aws-ecs-patterns/lib/base/queue-processing-service-base.ts
  packages/aws-cdk-lib/aws-events-targets/lib/util.ts
  packages/aws-cdk-lib/aws-lambda-destinations/lib/sqs.ts
  packages/aws-cdk-lib/aws-lambda-event-sources/lib/sqs-dlq.ts
  packages/aws-cdk-lib/aws-lambda/lib/function.ts
  packages/aws-cdk-lib/aws-s3-notifications/lib/sqs.ts
  packages/aws-cdk-lib/aws-sns-subscriptions/lib/subscription.ts
  packages/aws-cdk-lib/aws-sns/lib/subscription.ts
  packages/aws-cdk-lib/aws-sqs/lib/policy.ts
  packages/aws-cdk-lib/aws-sqs/lib/queue-base.ts
  packages/aws-cdk-lib/aws-sqs/lib/queue.ts
  packages/aws-cdk-lib/aws-stepfunctions-tasks/lib/sqs/send-message.ts
  packages/aws-cdk-lib/aws-stepfunctions-tasks/lib/sqs/send-to-queue.ts
Labels: p2, contribution/core

#28366 chore(roadmap): Add IPv6 work to the roadmap
  ROADMAP.md
Labels: p1, feature-request, effort/large, repeat-contributor

#28251 feat: implement code generated handler framework
  packages/@aws-cdk/custom-resource-handlers/lib/custom-resources-framework/README.md
  packages/@aws-cdk/custom-resource-handlers/lib/custom-resources-framework/classes.ts
  packages/@aws-cdk/custom-resource-handlers/lib/custom-resources-framework/config.ts
  packages/@aws-cdk/custom-resource-handlers/lib/custom-resources-framework/framework.ts
  packages/@aws-cdk/custom-resource-handlers/lib/custom-resources-framework/modules.ts
  packages/@aws-cdk/custom-resource-handlers/lib/custom-resources-framework/utils/framework-utils.ts
  packages/@aws-cdk/custom-resource-handlers/package.json
  packages/@aws-cdk/custom-resource-handlers/scripts/generate.ts
  packages/@aws-cdk/custom-resource-handlers/scripts/minify-and-bundle-sources.ts
  packages/@aws-cdk/custom-resource-handlers/test/custom-resources-framework/expected/custom-resource-provider-core.ts
  packages/@aws-cdk/custom-resource-handlers/test/custom-resources-framework/expected/custom-resource-provider.ts
  packages/@aws-cdk/custom-resource-handlers/test/custom-resources-framework/expected/function.ts
  packages/@aws-cdk/custom-resource-handlers/test/custom-resources-framework/expected/singleton-function.ts
  packages/@aws-cdk/custom-resource-handlers/test/custom-resources-framework/framework.test.ts
  packages/@aws-cdk/custom-resource-handlers/test/custom-resources-framework/my-handler/index.ts
  packages/@aws-cdk/custom-resource-handlers/test/custom-resources-framework/utils/framework-utils.test.ts
  packages/@aws-cdk/custom-resource-handlers/tsconfig.json
  packages/aws-cdk-lib/aws-certificatemanager/lib/dns-validated-certificate.ts
  packages/aws-cdk-lib/aws-cloudfront/lib/experimental/edge-function.ts
  packages/aws-cdk-lib/aws-dynamodb/lib/replica-provider.ts
  packages/aws-cdk-lib/aws-ec2/lib/vpc.ts
  packages/aws-cdk-lib/aws-ecr/lib/repository.ts
  packages/aws-cdk-lib/aws-eks/lib/cluster-resource-provider.ts
  packages/aws-cdk-lib/aws-eks/lib/kubectl-provider.ts
  packages/aws-cdk-lib/aws-events-targets/lib/aws-api.ts
  packages/aws-cdk-lib/aws-iam/lib/oidc-provider.ts
  packages/aws-cdk-lib/aws-route53/lib/record-set.ts
  packages/aws-cdk-lib/aws-s3-deployment/lib/bucket-deployment.ts
  packages/aws-cdk-lib/aws-s3/lib/bucket.ts
  packages/aws-cdk-lib/aws-ses/lib/receipt-rule.ts
  packages/aws-cdk-lib/aws-stepfunctions-tasks/lib/emrcontainers/start-job-run.ts
  packages/aws-cdk-lib/aws-stepfunctions-tasks/lib/evaluate-expression.ts
  packages/aws-cdk-lib/aws-synthetics/lib/canary.ts
  packages/aws-cdk-lib/core/lib/custom-resource-provider/cross-region-export-providers/export-reader-provider.ts
  packages/aws-cdk-lib/core/lib/custom-resource-provider/cross-region-export-providers/export-writer-provider.ts
  packages/aws-cdk-lib/core/lib/custom-resource-provider/custom-resource-provider-base.ts
  packages/aws-cdk-lib/core/lib/custom-resource-provider/custom-resource-provider.ts
  packages/aws-cdk-lib/core/lib/custom-resource-provider/index.ts
  packages/aws-cdk-lib/core/lib/custom-resource-provider/shared.ts
  packages/aws-cdk-lib/core/lib/private/cfn-utils-provider.ts
  packages/aws-cdk-lib/custom-resources/lib/aws-custom-resource/aws-custom-resource.ts
  packages/aws-cdk-lib/pipelines/lib/private/application-security-check.ts
  packages/aws-cdk-lib/scripts/airlift-custom-resource-handlers.sh
  packages/aws-cdk-lib/triggers/lib/trigger.ts
Labels: p1, feature-request, effort/medium, contribution/core, pr-linter/exempt-integ-test

#28403 chore(cdk-testing): fix integ test case using unrestricted principal for role
  packages/@aws-cdk-testing/cli-integ/resources/cdk-apps/simple-app/app.js
Labels: p2, contribution/core

#28407 feat: update AWS Service Spec
  packages/@aws-cdk/cloudformation-diff/package.json
  packages/@aws-cdk/integ-runner/package.json
  packages/aws-cdk-lib/aws-b2bi/.jsiirc.json
  packages/aws-cdk-lib/aws-b2bi/README.md
  packages/aws-cdk-lib/aws-b2bi/index.ts
  packages/aws-cdk-lib/aws-b2bi/lib/index.ts
  packages/aws-cdk-lib/index.ts
  packages/aws-cdk-lib/package.json
  packages/aws-cdk-lib/scripts/scope-map.json
  tools/@aws-cdk/spec2cdk/package.json
  yarn.lock
Labels: p2, dependencies, contribution/core, pr-linter/exempt-readme, pr-linter/exempt-test, auto-approve, pr-linter/exempt-integ-test

#28411 chore(apigateway): fix typo in a doc and a private method for lambda authorizers
  packages/aws-cdk-lib/aws-apigateway/lib/authorizers/lambda.ts
Labels: p2, distinguished-contributor

#28396 chore(autoscaling): add lowest-price OnDemandAllocationStrategy enum to aws-autoscaling
  packages/aws-cdk-lib/aws-autoscaling/lib/auto-scaling-group.ts
  packages/aws-cdk-lib/aws-autoscaling/test/auto-scaling-group.test.ts
Labels: bug, p2, beginning-contributor

#27799 feat(scheduler-targets): add CodePipeline as target for scheduler
  packages/@aws-cdk/aws-scheduler-targets-alpha/README.md
  packages/@aws-cdk/aws-scheduler-targets-alpha/lib/codepipeline-start-pipeline-execution.ts
  packages/@aws-cdk/aws-scheduler-targets-alpha/lib/index.ts
  packages/@aws-cdk/aws-scheduler-targets-alpha/test/codepipeline-start-pipeline-execution.test.ts
  packages/@aws-cdk/aws-scheduler-targets-alpha/test/integ.codepipeline-start-pipeline-execution.js.snapshot/asset.a5feac1d1e65b04919886f5961fd2ba1352489d558439d9d6592877e92fc2814.bundle/index.js
  packages/@aws-cdk/aws-scheduler-targets-alpha/test/integ.codepipeline-start-pipeline-execution.js.snapshot/aws-cdk-scheduler-targets-codepipeline-start-pipeline-execution.assets.json
  packages/@aws-cdk/aws-scheduler-targets-alpha/test/integ.codepipeline-start-pipeline-execution.js.snapshot/aws-cdk-scheduler-targets-codepipeline-start-pipeline-execution.template.json
  packages/@aws-cdk/aws-scheduler-targets-alpha/test/integ.codepipeline-start-pipeline-execution.js.snapshot/cdk.out
  packages/@aws-cdk/aws-scheduler-targets-alpha/test/integ.codepipeline-start-pipeline-execution.js.snapshot/integ.json
  packages/@aws-cdk/aws-scheduler-targets-alpha/test/integ.codepipeline-start-pipeline-execution.js.snapshot/integrationtestcodepipelinestartpipelineexecutionDefaultTestDeployAssert922B4892.assets.json
  packages/@aws-cdk/aws-scheduler-targets-alpha/test/integ.codepipeline-start-pipeline-execution.js.snapshot/integrationtestcodepipelinestartpipelineexecutionDefaultTestDeployAssert922B4892.template.json
  packages/@aws-cdk/aws-scheduler-targets-alpha/test/integ.codepipeline-start-pipeline-execution.js.snapshot/manifest.json
  packages/@aws-cdk/aws-scheduler-targets-alpha/test/integ.codepipeline-start-pipeline-execution.js.snapshot/tree.json
  packages/@aws-cdk/aws-scheduler-targets-alpha/test/integ.codepipeline-start-pipeline-execution.ts
  packages/aws-cdk-lib/aws-codepipeline/lib/pipeline.ts
  packages/aws-cdk-lib/aws-codepipeline/test/pipeline.test.ts
Labels: p2, feature-request, effort/medium, star-contributor

#27787 fix(logs): adding a resource policy statement with `AnyPrincipal` fails
  packages/@aws-cdk-testing/framework-integ/test/aws-logs/test/integ.log-resource-policy-any-principal.js.snapshot/LogGroupResourcePolicyAnyPrincialIntegDefaultTestDeployAssert1A3C13F5.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-logs/test/integ.log-resource-policy-any-principal.js.snapshot/LogGroupResourcePolicyAnyPrincialIntegDefaultTestDeployAssert1A3C13F5.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-logs/test/integ.log-resource-policy-any-principal.js.snapshot/aws-cdk-log-group-resource-policy-any-integ.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-logs/test/integ.log-resource-policy-any-principal.js.snapshot/aws-cdk-log-group-resource-policy-any-integ.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-logs/test/integ.log-resource-policy-any-principal.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-logs/test/integ.log-resource-policy-any-principal.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-logs/test/integ.log-resource-policy-any-principal.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-logs/test/integ.log-resource-policy-any-principal.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-logs/test/integ.log-resource-policy-any-principal.ts
  packages/aws-cdk-lib/aws-logs/lib/log-group.ts
  packages/aws-cdk-lib/aws-logs/test/loggroup.test.ts
Labels: bug, p2, star-contributor

#28416 chore(logs): fix method name typo
  packages/aws-cdk-lib/aws-iam/lib/principals.ts
  packages/aws-cdk-lib/aws-logs/lib/log-group.ts
Labels: p2, contribution/core

#28317 fix(lambda-python-alpha): pipenv lock -r is no longer supported
  packages/@aws-cdk/aws-lambda-python-alpha/lib/packaging.ts
  packages/@aws-cdk/aws-lambda-python-alpha/test/bundling.test.ts
Labels: bug, p2, effort/small, pr-linter/exempt-integ-test, repeat-contributor

#28354 feat(ecs): log retention for FireLensLogDriver
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs/test/fargate/integ.firelens-cloudwatch.js.snapshot/aws-ecs-integ.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs/test/fargate/integ.firelens-cloudwatch.js.snapshot/aws-ecs-integ.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs/test/fargate/integ.firelens-cloudwatch.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs/test/fargate/integ.firelens-cloudwatch.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs/test/fargate/integ.firelens-cloudwatch.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs/test/fargate/integ.firelens-cloudwatch.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs/test/fargate/integ.firelens-cloudwatch.ts
  packages/aws-cdk-lib/aws-ecs/README.md
  packages/aws-cdk-lib/aws-ecs/lib/firelens-log-router.ts
  packages/aws-cdk-lib/aws-ecs/test/firelens-log-driver.test.ts
Labels: p2, valued-contributor

#28233 feat(ecr): Add emptyOnDelete CloudFormation property to Repository L2 construct
  packages/@aws-cdk-testing/framework-integ/test/aws-ecr/test/integ.basic.js.snapshot/aws-ecr-integ-stack.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecr/test/integ.basic.js.snapshot/aws-ecr-integ-stack.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecr/test/integ.basic.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-ecr/test/integ.basic.js.snapshot/cdkecrintegtestbasicDefaultTestDeployAssert4F7FBFB4.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecr/test/integ.basic.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecr/test/integ.basic.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecr/test/integ.basic.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecr/test/integ.basic.ts
  packages/@aws-cdk/app-staging-synthesizer-alpha/README.md
  packages/@aws-cdk/app-staging-synthesizer-alpha/lib/default-staging-stack.ts
  packages/@aws-cdk/app-staging-synthesizer-alpha/test/integ.synth-default-resources.js.snapshot/StagingStack-default-resourcesmax-ACCOUNT-REGION.template.json
  packages/@aws-cdk/app-staging-synthesizer-alpha/test/integ.synth-default-resources.js.snapshot/cdk.out
  packages/@aws-cdk/app-staging-synthesizer-alpha/test/integ.synth-default-resources.js.snapshot/integ.json
  packages/@aws-cdk/app-staging-synthesizer-alpha/test/integ.synth-default-resources.js.snapshot/integtestsDefaultTestDeployAssert44C8D370.assets.json
  packages/@aws-cdk/app-staging-synthesizer-alpha/test/integ.synth-default-resources.js.snapshot/manifest.json
  packages/@aws-cdk/app-staging-synthesizer-alpha/test/integ.synth-default-resources.js.snapshot/synthesize-default-resources.assets.json
  packages/@aws-cdk/app-staging-synthesizer-alpha/test/integ.synth-default-resources.js.snapshot/tree.json
  packages/@aws-cdk/app-staging-synthesizer-alpha/test/integ.synth-default-resources.ts.snapshot/StagingStack-default-resourcesmax-ACCOUNT-REGION.template.json
  packages/@aws-cdk/app-staging-synthesizer-alpha/test/integ.synth-default-resources.ts.snapshot/cdk.out
  packages/@aws-cdk/app-staging-synthesizer-alpha/test/integ.synth-default-resources.ts.snapshot/integ.json
  packages/@aws-cdk/app-staging-synthesizer-alpha/test/integ.synth-default-resources.ts.snapshot/integtestsDefaultTestDeployAssert44C8D370.assets.json
  packages/@aws-cdk/app-staging-synthesizer-alpha/test/integ.synth-default-resources.ts.snapshot/manifest.json
  packages/@aws-cdk/app-staging-synthesizer-alpha/test/integ.synth-default-resources.ts.snapshot/synthesize-default-resources.assets.json
  packages/@aws-cdk/app-staging-synthesizer-alpha/test/integ.synth-default-resources.ts.snapshot/tree.json
  packages/aws-cdk-lib/aws-ecr/README.md
  packages/aws-cdk-lib/aws-ecr/lib/repository.ts
  packages/aws-cdk-lib/aws-ecr/test/repository.test.ts
Labels: p2, feature-request, effort/small, beginning-contributor

#28419 chore(eks): document failure conditions for albController
  packages/aws-cdk-lib/aws-eks/README.md
Labels: bug, p2, contribution/core

#28392 feat(ses): add scalingMode property to dedicated ip pool
  packages/@aws-cdk-testing/framework-integ/test/aws-ses/test/integ.dedicated-ip-pool.js.snapshot/DedicatedIpPoolIntegDefaultTestDeployAssert1E9B4C6C.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ses/test/integ.dedicated-ip-pool.js.snapshot/DedicatedIpPoolIntegDefaultTestDeployAssert1E9B4C6C.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ses/test/integ.dedicated-ip-pool.js.snapshot/aws-cdk-dedicated-ip-pool.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ses/test/integ.dedicated-ip-pool.js.snapshot/aws-cdk-dedicated-ip-pool.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ses/test/integ.dedicated-ip-pool.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-ses/test/integ.dedicated-ip-pool.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ses/test/integ.dedicated-ip-pool.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ses/test/integ.dedicated-ip-pool.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ses/test/integ.dedicated-ip-pool.ts
  packages/aws-cdk-lib/aws-ses/README.md
  packages/aws-cdk-lib/aws-ses/lib/dedicated-ip-pool.ts
  packages/aws-cdk-lib/aws-ses/test/dedicated-ip-pool.test.ts
Labels: p2, feature-request, effort/small, beginning-contributor

#28422 feat(stepfunctions): CustomState addCatch
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions/test/integ.custom-state.js.snapshot/aws-stepfunctions-custom-state-integ.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions/test/integ.custom-state.ts
  packages/aws-cdk-lib/aws-stepfunctions/README.md
  packages/aws-cdk-lib/aws-stepfunctions/lib/states/custom-state.ts
  packages/aws-cdk-lib/aws-stepfunctions/test/custom-state.test.ts
Labels: bug, p1, effort/medium, beginning-contributor

#27340 feat(events): add multiple event bus policies on a single event bus
  packages/@aws-cdk-testing/framework-integ/test/aws-events/test/integ.eventbus.js.snapshot/IntegTestEventBusStackDefaultTestDeployAssertE6DF8EA9.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-events/test/integ.eventbus.js.snapshot/IntegTestEventBusStackDefaultTestDeployAssertE6DF8EA9.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-events/test/integ.eventbus.js.snapshot/Stack.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-events/test/integ.eventbus.js.snapshot/Stack.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-events/test/integ.eventbus.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-events/test/integ.eventbus.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-events/test/integ.eventbus.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-events/test/integ.eventbus.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-events/test/integ.eventbus.ts
  packages/aws-cdk-lib/aws-events/lib/event-bus.ts
  packages/aws-cdk-lib/aws-events/test/event-bus.test.ts
Labels: bug, p2, pr-linter/exempt-readme, beginning-contributor

#28220 fix(ecs-patterns): taskDefinition ignored by queueProcessingFargateService
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs-patterns/test/fargate/integ.queue-processing-fargate-service-task-definition.js.snapshot/asset.95cefedd43575452a70cdeeeceb0f1c5728fd58c9ff8e81e760c3dac33c46417/Dockerfile
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs-patterns/test/fargate/integ.queue-processing-fargate-service-task-definition.js.snapshot/asset.95cefedd43575452a70cdeeeceb0f1c5728fd58c9ff8e81e760c3dac33c46417/index.py
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs-patterns/test/fargate/integ.queue-processing-fargate-service-task-definition.js.snapshot/aws-ecs-patterns-queue.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs-patterns/test/fargate/integ.queue-processing-fargate-service-task-definition.js.snapshot/aws-ecs-patterns-queue.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs-patterns/test/fargate/integ.queue-processing-fargate-service-task-definition.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs-patterns/test/fargate/integ.queue-processing-fargate-service-task-definition.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs-patterns/test/fargate/integ.queue-processing-fargate-service-task-definition.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs-patterns/test/fargate/integ.queue-processing-fargate-service-task-definition.js.snapshot/taskDefinitionQueueProcessingFargateServiceTestDefaultTestDeployAssert406F467D.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs-patterns/test/fargate/integ.queue-processing-fargate-service-task-definition.js.snapshot/taskDefinitionQueueProcessingFargateServiceTestDefaultTestDeployAssert406F467D.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs-patterns/test/fargate/integ.queue-processing-fargate-service-task-definition.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs-patterns/test/fargate/integ.queue-processing-fargate-service-task-definition.ts
  packages/aws-cdk-lib/aws-ecs-patterns/lib/base/queue-processing-service-base.ts
  packages/aws-cdk-lib/aws-ecs-patterns/lib/ecs/queue-processing-ecs-service.ts
  packages/aws-cdk-lib/aws-ecs-patterns/lib/fargate/queue-processing-fargate-service.ts
  packages/aws-cdk-lib/aws-ecs-patterns/test/ec2/queue-processing-ecs-service.test.ts
  packages/aws-cdk-lib/aws-ecs-patterns/test/fargate/queue-processing-fargate-service.test.ts
Labels: bug, p2, effort/small, beginning-contributor

#28435 docs(apigatewayv2): revive README.md
  packages/aws-cdk-lib/aws-apigatewayv2/README.md
Labels: p2, star-contributor

#28413 chore(roadmap): add GC to the roadmap
  ROADMAP.md
Labels: p2, pr/needs-community-review, repeat-contributor

#28424 fix(integ-tests): apply correct IAM policy to waiterProvider
  packages/@aws-cdk/integ-tests-alpha/lib/assertions/sdk.ts
  packages/@aws-cdk/integ-tests-alpha/test/assertions/providers/integ.invoke-function-assertions.js.snapshot/AssertionsTestDefaultTestDeployAssertDC0672BB.assets.json
  packages/@aws-cdk/integ-tests-alpha/test/assertions/providers/integ.invoke-function-assertions.js.snapshot/AssertionsTestDefaultTestDeployAssertDC0672BB.template.json
  packages/@aws-cdk/integ-tests-alpha/test/assertions/providers/integ.invoke-function-assertions.js.snapshot/InvokeFunctionAssertions.assets.json
  packages/@aws-cdk/integ-tests-alpha/test/assertions/providers/integ.invoke-function-assertions.js.snapshot/InvokeFunctionAssertions.template.json
  packages/@aws-cdk/integ-tests-alpha/test/assertions/providers/integ.invoke-function-assertions.js.snapshot/cdk.out
  packages/@aws-cdk/integ-tests-alpha/test/assertions/providers/integ.invoke-function-assertions.js.snapshot/integ.json
  packages/@aws-cdk/integ-tests-alpha/test/assertions/providers/integ.invoke-function-assertions.js.snapshot/manifest.json
  packages/@aws-cdk/integ-tests-alpha/test/assertions/providers/integ.invoke-function-assertions.js.snapshot/tree.json
  packages/@aws-cdk/integ-tests-alpha/test/assertions/providers/integ.invoke-function-assertions.ts
  packages/@aws-cdk/integ-tests-alpha/test/assertions/sdk.test.ts
Labels: bug, p1, effort/medium, valued-contributor

#28138 feat(ec2): support creating key pairs
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.key-pair.js.snapshot/KeyPairTestDefaultTestDeployAssertF103D058.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.key-pair.js.snapshot/KeyPairTestDefaultTestDeployAssertF103D058.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.key-pair.js.snapshot/asset.a099fdfc61c84ffc56cef4fb2c9472483623ac865ce5d8fca88c89cf60d48d03/__entrypoint__.js
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.key-pair.js.snapshot/asset.a099fdfc61c84ffc56cef4fb2c9472483623ac865ce5d8fca88c89cf60d48d03/index.js
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.key-pair.js.snapshot/aws-cdk-ec2-key-pair-1.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.key-pair.js.snapshot/aws-cdk-ec2-key-pair-1.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.key-pair.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.key-pair.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.key-pair.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.key-pair.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.key-pair.ts
  packages/aws-cdk-lib/aws-ec2/README.md
  packages/aws-cdk-lib/aws-ec2/lib/index.ts
  packages/aws-cdk-lib/aws-ec2/lib/instance.ts
  packages/aws-cdk-lib/aws-ec2/lib/key-pair.ts
  packages/aws-cdk-lib/aws-ec2/lib/launch-template.ts
  packages/aws-cdk-lib/aws-ec2/lib/nat.ts
  packages/aws-cdk-lib/aws-ec2/test/instance.test.ts
  packages/aws-cdk-lib/aws-ec2/test/key-pair.test.ts
  packages/aws-cdk-lib/aws-ec2/test/launch-template.test.ts
Labels: p1, feature-request, effort/large, star-contributor

#28439 chore(roadmap): Add EKSv2 to the ROADMAP.md
  ROADMAP.md
Labels: p2, valued-contributor

#28432 feat(ecr): tag pattern list for lifecycle policy
  packages/@aws-cdk-testing/framework-integ/test/aws-ecr/test/integ.basic.js.snapshot/aws-ecr-integ-stack.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecr/test/integ.basic.js.snapshot/aws-ecr-integ-stack.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecr/test/integ.basic.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecr/test/integ.basic.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecr/test/integ.basic.ts
  packages/aws-cdk-lib/aws-ecr/README.md
  packages/aws-cdk-lib/aws-ecr/lib/lifecycle.ts
  packages/aws-cdk-lib/aws-ecr/lib/repository.ts
  packages/aws-cdk-lib/aws-ecr/test/repository.test.ts
  packages/aws-cdk-lib/awslint.json
Labels: p2, distinguished-contributor

#28441 chore: make the service-spec update more user friendly
  .github/workflows/spec-update.yml
Labels: p2, contribution/core

#28440 chore: add evgenyka to mergify and githubmerit badger
  .github/workflows/github-merit-badger.yml
  .mergify.yml
Labels: p2, contribution/core

#28379 fix(secretsmanager): hosted rotation with fromSecretNameV2() does not create correct iam policy
  packages/@aws-cdk-testing/framework-integ/test/aws-secretsmanager/test/integ.hosted-rotation.js.snapshot/cdk-integ-secret-hosted-rotation.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-secretsmanager/test/integ.hosted-rotation.js.snapshot/cdk-integ-secret-hosted-rotation.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-secretsmanager/test/integ.hosted-rotation.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-secretsmanager/test/integ.hosted-rotation.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-secretsmanager/test/integ.hosted-rotation.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-secretsmanager/test/integ.hosted-rotation.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-secretsmanager/test/integ.hosted-rotation.ts
  packages/aws-cdk-lib/aws-secretsmanager/lib/rotation-schedule.ts
  packages/aws-cdk-lib/aws-secretsmanager/test/rotation-schedule.test.ts
Labels: bug, p2, pr/needs-community-review, effort/medium, distinguished-contributor

#27791 feat(stepfunctions-tasks): EMR createCluster command support OnDemandSpecification
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/emr/integ.emr-create-cluster-with-on-demand-instance-fleet.js.snapshot/EmrCreateClusterTestDefaultTestDeployAssert697DC891.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/emr/integ.emr-create-cluster-with-on-demand-instance-fleet.js.snapshot/EmrCreateClusterTestDefaultTestDeployAssert697DC891.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/emr/integ.emr-create-cluster-with-on-demand-instance-fleet.js.snapshot/aws-cdk-emr-create-cluster-with-on-demand-instance-fleet.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/emr/integ.emr-create-cluster-with-on-demand-instance-fleet.js.snapshot/aws-cdk-emr-create-cluster-with-on-demand-instance-fleet.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/emr/integ.emr-create-cluster-with-on-demand-instance-fleet.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/emr/integ.emr-create-cluster-with-on-demand-instance-fleet.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/emr/integ.emr-create-cluster-with-on-demand-instance-fleet.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/emr/integ.emr-create-cluster-with-on-demand-instance-fleet.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/emr/integ.emr-create-cluster-with-on-demand-instance-fleet.ts
  packages/aws-cdk-lib/aws-stepfunctions-tasks/README.md
  packages/aws-cdk-lib/aws-stepfunctions-tasks/lib/emr/emr-create-cluster.ts
  packages/aws-cdk-lib/aws-stepfunctions-tasks/lib/emr/private/cluster-utils.ts
  packages/aws-cdk-lib/aws-stepfunctions-tasks/test/emr/emr-create-cluster.test.ts
Labels: p2, feature-request, effort/medium, star-contributor

#27548 fix(iam): importedRoleStackSafeDefaultPolicyName feature flag results in excessively long IAM policy names
  packages/@aws-cdk-testing/framework-integ/test/aws-iam/test/integ.imported-role.js.snapshot/ImportedRoleTestAssertions.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-iam/test/integ.imported-role.js.snapshot/ImportedRoleTestAssertions.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-iam/test/integ.imported-role.js.snapshot/asset.73c20a669c041469f7fc3fc03d574b093b5b97e7c716f76c1e8117e6163e4dc4.bundle/index.js
  packages/@aws-cdk-testing/framework-integ/test/aws-iam/test/integ.imported-role.js.snapshot/asset.c91921c142e824b74d06797a2be74eab5d0dd0453e753549f5182ac7a02f556b.bundle/index.js
  packages/@aws-cdk-testing/framework-integ/test/aws-iam/test/integ.imported-role.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-iam/test/integ.imported-role.js.snapshot/integ-iam-imported-role-1.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-iam/test/integ.imported-role.js.snapshot/integ-iam-imported-role-1.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-iam/test/integ.imported-role.js.snapshot/integ-iam-imported-role-2.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-iam/test/integ.imported-role.js.snapshot/integ-iam-imported-role-2.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-iam/test/integ.imported-role.js.snapshot/integ-iam-imported-role-role-stack.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-iam/test/integ.imported-role.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-iam/test/integ.imported-role.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-iam/test/integ.imported-role.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-iam/test/integ.imported-role.ts
  packages/aws-cdk-lib/aws-iam/lib/private/imported-role.ts
  packages/aws-cdk-lib/aws-iam/lib/private/util.ts
  packages/aws-cdk-lib/aws-iam/test/role.from-role-arn.test.ts
Labels: bug, p1, effort/small, beginning-contributor

#28285 fix(events-targets): imported sqs queue cannot be used as a rule dlq (#28165)
  packages/aws-cdk-lib/aws-events-targets/lib/util.ts
  packages/aws-cdk-lib/aws-events-targets/test/sqs/sqs.test.ts
Labels: bug, p2, effort/medium, pr-linter/exempt-integ-test, beginning-contributor

#27844 chore(integ-tests): add waiterProvider to IApiCall
  packages/@aws-cdk/integ-tests-alpha/README.md
  packages/@aws-cdk/integ-tests-alpha/lib/assertions/api-call-base.ts
  packages/@aws-cdk/integ-tests-alpha/test/assertions/providers/lambda-handler/integ.waiter-provider.js.snapshot/WaiterProviderStack.assets.json
  packages/@aws-cdk/integ-tests-alpha/test/assertions/providers/lambda-handler/integ.waiter-provider.js.snapshot/WaiterProviderStack.template.json
  packages/@aws-cdk/integ-tests-alpha/test/assertions/providers/lambda-handler/integ.waiter-provider.js.snapshot/WaiterProviderTestDefaultTestDeployAssertDADDA65F.assets.json
  packages/@aws-cdk/integ-tests-alpha/test/assertions/providers/lambda-handler/integ.waiter-provider.js.snapshot/WaiterProviderTestDefaultTestDeployAssertDADDA65F.template.json
  packages/@aws-cdk/integ-tests-alpha/test/assertions/providers/lambda-handler/integ.waiter-provider.js.snapshot/cdk.out
  packages/@aws-cdk/integ-tests-alpha/test/assertions/providers/lambda-handler/integ.waiter-provider.js.snapshot/integ.json
  packages/@aws-cdk/integ-tests-alpha/test/assertions/providers/lambda-handler/integ.waiter-provider.js.snapshot/manifest.json
  packages/@aws-cdk/integ-tests-alpha/test/assertions/providers/lambda-handler/integ.waiter-provider.js.snapshot/tree.json
  packages/@aws-cdk/integ-tests-alpha/test/assertions/providers/lambda-handler/integ.waiter-provider.ts
  packages/@aws-cdk/integ-tests-alpha/test/assertions/sdk.test.ts
Labels: p2, star-contributor, pr/needs-maintainer-review

#28457 chore(integ-tests): revert add waiterProvider to IApiCall
  packages/@aws-cdk/integ-tests-alpha/README.md
  packages/@aws-cdk/integ-tests-alpha/lib/assertions/api-call-base.ts
  packages/@aws-cdk/integ-tests-alpha/test/assertions/providers/lambda-handler/integ.waiter-provider.js.snapshot/WaiterProviderStack.assets.json
  packages/@aws-cdk/integ-tests-alpha/test/assertions/providers/lambda-handler/integ.waiter-provider.js.snapshot/WaiterProviderStack.template.json
  packages/@aws-cdk/integ-tests-alpha/test/assertions/providers/lambda-handler/integ.waiter-provider.js.snapshot/WaiterProviderTestDefaultTestDeployAssertDADDA65F.assets.json
  packages/@aws-cdk/integ-tests-alpha/test/assertions/providers/lambda-handler/integ.waiter-provider.js.snapshot/WaiterProviderTestDefaultTestDeployAssertDADDA65F.template.json
  packages/@aws-cdk/integ-tests-alpha/test/assertions/providers/lambda-handler/integ.waiter-provider.js.snapshot/cdk.out
  packages/@aws-cdk/integ-tests-alpha/test/assertions/providers/lambda-handler/integ.waiter-provider.js.snapshot/integ.json
  packages/@aws-cdk/integ-tests-alpha/test/assertions/providers/lambda-handler/integ.waiter-provider.js.snapshot/manifest.json
  packages/@aws-cdk/integ-tests-alpha/test/assertions/providers/lambda-handler/integ.waiter-provider.js.snapshot/tree.json
  packages/@aws-cdk/integ-tests-alpha/test/assertions/providers/lambda-handler/integ.waiter-provider.ts
  packages/@aws-cdk/integ-tests-alpha/test/assertions/sdk.test.ts
Labels: p2, contribution/core

#28449 fix(lambda-python-alpha): use function architecture (#18696)
  packages/@aws-cdk/aws-lambda-python-alpha/lib/function.ts
  packages/@aws-cdk/aws-lambda-python-alpha/test/function.test.ts
Labels: bug, p1, effort/small, pr-linter/exempt-integ-test, beginning-contributor

#28458 chore(release): 2.116.0
  packages/@aws-cdk/integ-tests-alpha/README.md
  packages/@aws-cdk/integ-tests-alpha/lib/assertions/api-call-base.ts
  packages/@aws-cdk/integ-tests-alpha/test/assertions/providers/lambda-handler/integ.waiter-provider.js.snapshot/WaiterProviderStack.assets.json
  packages/@aws-cdk/integ-tests-alpha/test/assertions/providers/lambda-handler/integ.waiter-provider.js.snapshot/WaiterProviderStack.template.json
  packages/@aws-cdk/integ-tests-alpha/test/assertions/providers/lambda-handler/integ.waiter-provider.js.snapshot/WaiterProviderTestDefaultTestDeployAssertDADDA65F.assets.json
  packages/@aws-cdk/integ-tests-alpha/test/assertions/providers/lambda-handler/integ.waiter-provider.js.snapshot/WaiterProviderTestDefaultTestDeployAssertDADDA65F.template.json
  packages/@aws-cdk/integ-tests-alpha/test/assertions/providers/lambda-handler/integ.waiter-provider.js.snapshot/cdk.out
  packages/@aws-cdk/integ-tests-alpha/test/assertions/providers/lambda-handler/integ.waiter-provider.js.snapshot/integ.json
  packages/@aws-cdk/integ-tests-alpha/test/assertions/providers/lambda-handler/integ.waiter-provider.js.snapshot/manifest.json
  packages/@aws-cdk/integ-tests-alpha/test/assertions/providers/lambda-handler/integ.waiter-provider.js.snapshot/tree.json
  packages/@aws-cdk/integ-tests-alpha/test/assertions/providers/lambda-handler/integ.waiter-provider.ts
  packages/@aws-cdk/integ-tests-alpha/test/assertions/sdk.test.ts
Labels: p2, pr/no-squash, auto-approve

#28461 chore(merge-back): 2.116.0
  CHANGELOG.v2.alpha.md
  CHANGELOG.v2.md
  version.v2.json
Labels: p2, pr/needs-community-review, pr/no-squash, auto-approve

#28467 fix(core): core constructs fail with `Error: Cannot find module '../dist/core/<file>.generated'`
  packages/aws-cdk-lib/.npmignore
  packages/aws-cdk-lib/core/adr/acknowledge-warnings.md
Labels: p0, contribution/core, pr-linter/exempt-test, pr-linter/exempt-integ-test

#28468 chore(release): 2.116.1
  CHANGELOG.v2.alpha.md
  CHANGELOG.v2.md
  packages/aws-cdk-lib/.npmignore
  packages/aws-cdk-lib/core/adr/acknowledge-warnings.md
  version.v2.json
Labels: p2, contribution/core, pr/no-squash

#28472 chore(merge-back): 2.116.1
  CHANGELOG.v2.alpha.md
  CHANGELOG.v2.md
  version.v2.json
Labels: p2, pr/needs-community-review, pr/no-squash, auto-approve

#28400 feat(api-gateway-v2): Add method to generate flexible execute-api ARN
  packages/@aws-cdk-testing/framework-integ/test/aws-apigatewayv2/test/http/integ.api.js.snapshot/aws-cdk-aws-apigatewayv2.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-apigatewayv2/test/http/integ.api.js.snapshot/aws-cdk-aws-apigatewayv2.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-apigatewayv2/test/http/integ.api.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-apigatewayv2/test/http/integ.api.js.snapshot/httpapiDefaultTestDeployAssert77633A40.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-apigatewayv2/test/http/integ.api.js.snapshot/httpapiDefaultTestDeployAssert77633A40.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-apigatewayv2/test/http/integ.api.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-apigatewayv2/test/http/integ.api.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-apigatewayv2/test/http/integ.api.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-apigatewayv2/test/http/integ.api.ts
  packages/@aws-cdk-testing/framework-integ/test/aws-apigatewayv2/test/websocket/integ.api.js.snapshot/aws-cdk-aws-apigatewayv2.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-apigatewayv2/test/websocket/integ.api.js.snapshot/aws-cdk-aws-apigatewayv2.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-apigatewayv2/test/websocket/integ.api.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-apigatewayv2/test/websocket/integ.api.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-apigatewayv2/test/websocket/integ.api.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-apigatewayv2/test/websocket/integ.api.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-apigatewayv2/test/websocket/integ.api.js.snapshot/websocketapiDefaultTestDeployAssert230DE1C6.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-apigatewayv2/test/websocket/integ.api.js.snapshot/websocketapiDefaultTestDeployAssert230DE1C6.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-apigatewayv2/test/websocket/integ.api.ts
  packages/aws-cdk-lib/aws-apigatewayv2/README.md
  packages/aws-cdk-lib/aws-apigatewayv2/lib/http/api.ts
  packages/aws-cdk-lib/aws-apigatewayv2/lib/websocket/api.ts
  packages/aws-cdk-lib/aws-apigatewayv2/test/http/api.test.ts
  packages/aws-cdk-lib/aws-apigatewayv2/test/websocket/api.test.ts
Labels: p2, feature-request, effort/small, beginning-contributor

#28381 feat(ecs): Implement method in ECS cluster to retrieve task ARN
  packages/aws-cdk-lib/aws-ecs/README.md
  packages/aws-cdk-lib/aws-ecs/lib/cluster.ts
  packages/aws-cdk-lib/aws-ecs/test/cluster.test.ts
Labels: p2, feature-request, effort/small, pr-linter/exempt-integ-test, beginning-contributor

#28466 feat(ses): synth-time naming validation for dedicatedIpPoolName
  packages/aws-cdk-lib/aws-ses/README.md
  packages/aws-cdk-lib/aws-ses/lib/dedicated-ip-pool.ts
  packages/aws-cdk-lib/aws-ses/test/dedicated-ip-pool.test.ts
Labels: p2, feature-request, effort/small, pr-linter/exempt-integ-test, repeat-contributor

#28315 feat(ecs-patterns): support disabling CPU-based scaling and custom target utilization
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs-patterns/test/fargate/integ.queue-processing-fargate-service-custom-cpu-scaling.js.snapshot/asset.8be39d348c20f7e58a373abbd1152069e18da130e51bf52c89bd82a38d0e51d7/Dockerfile
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs-patterns/test/fargate/integ.queue-processing-fargate-service-custom-cpu-scaling.js.snapshot/asset.8be39d348c20f7e58a373abbd1152069e18da130e51bf52c89bd82a38d0e51d7/index.py
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs-patterns/test/fargate/integ.queue-processing-fargate-service-custom-cpu-scaling.js.snapshot/aws-ecs-patterns-queue-custom-cpu-scaling.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs-patterns/test/fargate/integ.queue-processing-fargate-service-custom-cpu-scaling.js.snapshot/aws-ecs-patterns-queue-custom-cpu-scaling.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs-patterns/test/fargate/integ.queue-processing-fargate-service-custom-cpu-scaling.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs-patterns/test/fargate/integ.queue-processing-fargate-service-custom-cpu-scaling.js.snapshot/customCpuScalingQueueProcessingFargateServiceTestDefaultTestDeployAssert7FDCD114.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs-patterns/test/fargate/integ.queue-processing-fargate-service-custom-cpu-scaling.js.snapshot/customCpuScalingQueueProcessingFargateServiceTestDefaultTestDeployAssert7FDCD114.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs-patterns/test/fargate/integ.queue-processing-fargate-service-custom-cpu-scaling.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs-patterns/test/fargate/integ.queue-processing-fargate-service-custom-cpu-scaling.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs-patterns/test/fargate/integ.queue-processing-fargate-service-custom-cpu-scaling.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs-patterns/test/fargate/integ.queue-processing-fargate-service-custom-cpu-scaling.ts
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs-patterns/test/fargate/integ.queue-processing-fargate-service-no-cpu-scaling.js.snapshot/asset.8be39d348c20f7e58a373abbd1152069e18da130e51bf52c89bd82a38d0e51d7/Dockerfile
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs-patterns/test/fargate/integ.queue-processing-fargate-service-no-cpu-scaling.js.snapshot/asset.8be39d348c20f7e58a373abbd1152069e18da130e51bf52c89bd82a38d0e51d7/index.py
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs-patterns/test/fargate/integ.queue-processing-fargate-service-no-cpu-scaling.js.snapshot/aws-ecs-patterns-queue-no-cpu-scaling.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs-patterns/test/fargate/integ.queue-processing-fargate-service-no-cpu-scaling.js.snapshot/aws-ecs-patterns-queue-no-cpu-scaling.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs-patterns/test/fargate/integ.queue-processing-fargate-service-no-cpu-scaling.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs-patterns/test/fargate/integ.queue-processing-fargate-service-no-cpu-scaling.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs-patterns/test/fargate/integ.queue-processing-fargate-service-no-cpu-scaling.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs-patterns/test/fargate/integ.queue-processing-fargate-service-no-cpu-scaling.js.snapshot/noCpuScalingQueueProcessingFargateServiceTestDefaultTestDeployAssertE4E4F855.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs-patterns/test/fargate/integ.queue-processing-fargate-service-no-cpu-scaling.js.snapshot/noCpuScalingQueueProcessingFargateServiceTestDefaultTestDeployAssertE4E4F855.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs-patterns/test/fargate/integ.queue-processing-fargate-service-no-cpu-scaling.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs-patterns/test/fargate/integ.queue-processing-fargate-service-no-cpu-scaling.ts
  packages/aws-cdk-lib/aws-ecs-patterns/README.md
  packages/aws-cdk-lib/aws-ecs-patterns/lib/base/queue-processing-service-base.ts
  packages/aws-cdk-lib/aws-ecs-patterns/test/fargate/queue-processing-fargate-service.test.ts
Labels: bug, p2, beginning-contributor, pr/needs-maintainer-review

#28092 feat(autoscaling): instance maintenance policy for AutoScalingGroup
  packages/@aws-cdk-testing/framework-integ/test/aws-autoscaling/test/integ.asg-instance-maintenance-policy.js.snapshot/InstanceMaintenancePolicyTestDefaultTestDeployAssertD50B51FD.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-autoscaling/test/integ.asg-instance-maintenance-policy.js.snapshot/InstanceMaintenancePolicyTestDefaultTestDeployAssertD50B51FD.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-autoscaling/test/integ.asg-instance-maintenance-policy.js.snapshot/aws-cdk-autoscaling-instance-maintenance-policy.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-autoscaling/test/integ.asg-instance-maintenance-policy.js.snapshot/aws-cdk-autoscaling-instance-maintenance-policy.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-autoscaling/test/integ.asg-instance-maintenance-policy.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-autoscaling/test/integ.asg-instance-maintenance-policy.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-autoscaling/test/integ.asg-instance-maintenance-policy.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-autoscaling/test/integ.asg-instance-maintenance-policy.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-autoscaling/test/integ.asg-instance-maintenance-policy.ts
  packages/aws-cdk-lib/aws-autoscaling/README.md
  packages/aws-cdk-lib/aws-autoscaling/lib/auto-scaling-group.ts
  packages/aws-cdk-lib/aws-autoscaling/test/auto-scaling-group.test.ts
Labels: p2, feature-request, effort/medium, star-contributor

#27934 feat(codebuild): Lambda compute for codebuild projects
  packages/@aws-cdk-testing/framework-integ/test/aws-codebuild/test/integ.project-linux-arm-lambda-image.lit.js.snapshot/asset.57562799cf15fb41a7aa03a2d25a0707be565346aac1fb1f9634924d82585d44.bundle/index.js
  packages/@aws-cdk-testing/framework-integ/test/aws-codebuild/test/integ.project-linux-arm-lambda-image.lit.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-codebuild/test/integ.project-linux-arm-lambda-image.lit.js.snapshot/codebuild-project-linux-arm-lambda.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-codebuild/test/integ.project-linux-arm-lambda-image.lit.js.snapshot/codebuild-project-linux-arm-lambda.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-codebuild/test/integ.project-linux-arm-lambda-image.lit.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-codebuild/test/integ.project-linux-arm-lambda-image.lit.js.snapshot/linuxarmlambdacodebuildDefaultTestDeployAssert131511F5.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-codebuild/test/integ.project-linux-arm-lambda-image.lit.js.snapshot/linuxarmlambdacodebuildDefaultTestDeployAssert131511F5.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-codebuild/test/integ.project-linux-arm-lambda-image.lit.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-codebuild/test/integ.project-linux-arm-lambda-image.lit.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-codebuild/test/integ.project-linux-arm-lambda-image.lit.ts
  packages/@aws-cdk-testing/framework-integ/test/aws-codebuild/test/integ.project-linux-lambda-image.lit.js.snapshot/asset.57562799cf15fb41a7aa03a2d25a0707be565346aac1fb1f9634924d82585d44.bundle/index.js
  packages/@aws-cdk-testing/framework-integ/test/aws-codebuild/test/integ.project-linux-lambda-image.lit.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-codebuild/test/integ.project-linux-lambda-image.lit.js.snapshot/codebuild-project-linux-lambda.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-codebuild/test/integ.project-linux-lambda-image.lit.js.snapshot/codebuild-project-linux-lambda.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-codebuild/test/integ.project-linux-lambda-image.lit.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-codebuild/test/integ.project-linux-lambda-image.lit.js.snapshot/linuxlambdacodebuildDefaultTestDeployAssertD60C42C8.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-codebuild/test/integ.project-linux-lambda-image.lit.js.snapshot/linuxlambdacodebuildDefaultTestDeployAssertD60C42C8.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-codebuild/test/integ.project-linux-lambda-image.lit.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-codebuild/test/integ.project-linux-lambda-image.lit.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-codebuild/test/integ.project-linux-lambda-image.lit.ts
  packages/aws-cdk-lib/aws-codebuild/README.md
  packages/aws-cdk-lib/aws-codebuild/lib/compute-type.ts
  packages/aws-cdk-lib/aws-codebuild/lib/index.ts
  packages/aws-cdk-lib/aws-codebuild/lib/linux-arm-build-image.ts
  packages/aws-cdk-lib/aws-codebuild/lib/linux-arm-lambda-build-image.ts
  packages/aws-cdk-lib/aws-codebuild/lib/linux-gpu-build-image.ts
  packages/aws-cdk-lib/aws-codebuild/lib/linux-lambda-build-image.ts
  packages/aws-cdk-lib/aws-codebuild/lib/project.ts
  packages/aws-cdk-lib/aws-codebuild/test/codebuild.test.ts
  packages/aws-cdk-lib/aws-codebuild/test/linux-arm-lambda-build-image.test.ts
  packages/aws-cdk-lib/aws-codebuild/test/linux-lambda-build-image.test.ts
Labels: p2, feature-request, effort/medium, beginning-contributor

#28452 chore(migrate): only allow migrate on healthy stacks
  packages/aws-cdk/lib/api/util/cloudformation/stack-status.ts
  packages/aws-cdk/lib/commands/migrate.ts
  packages/aws-cdk/test/cdk-toolkit.test.ts
  packages/aws-cdk/test/commands/migrate.test.ts
Labels: p2, contribution/core, pr-linter/cli-integ-tested

#28477 feat(ec2): trn1 instance type
  packages/aws-cdk-lib/aws-ec2/lib/instance-types.ts
Labels: p2, pr-linter/exempt-readme, pr-linter/exempt-test, pr-linter/exempt-integ-test, beginning-contributor

#28479 feat(elasticloadbalancingv2): FIPS compliant SSL policy to ALB
  packages/aws-cdk-lib/aws-elasticloadbalancingv2/lib/shared/enums.ts
Labels: bug, p2, effort/small, pr-linter/exempt-readme, pr-linter/exempt-test, pr-linter/exempt-integ-test, valued-contributor

#27944 feat(core): option to disable cache for docker build
  packages/@aws-cdk-testing/framework-integ/test/aws-ecr-assets/test/integ.assets-docker.js.snapshot/asset.615e365307bd4811880256cf541a7d05b5d4a752ee76ac03863a0a39631607a6/Dockerfile
  packages/@aws-cdk-testing/framework-integ/test/aws-ecr-assets/test/integ.assets-docker.js.snapshot/asset.615e365307bd4811880256cf541a7d05b5d4a752ee76ac03863a0a39631607a6/index.py
  packages/@aws-cdk-testing/framework-integ/test/aws-ecr-assets/test/integ.assets-docker.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-ecr-assets/test/integ.assets-docker.js.snapshot/integ-assets-docker.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecr-assets/test/integ.assets-docker.js.snapshot/integ-assets-docker.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecr-assets/test/integ.assets-docker.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecr-assets/test/integ.assets-docker.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecr-assets/test/integ.assets-docker.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecr-assets/test/integ.assets-docker.ts
  packages/aws-cdk-lib/aws-ecr-assets/README.md
  packages/aws-cdk-lib/aws-ecr-assets/lib/image-asset.ts
  packages/aws-cdk-lib/aws-ecr-assets/test/build-image-cache.test.ts
  packages/aws-cdk-lib/aws-lambda/test/code.test.ts
  packages/aws-cdk-lib/cloud-assembly-schema/lib/assets/docker-image-asset.ts
  packages/aws-cdk-lib/cloud-assembly-schema/lib/cloud-assembly/metadata-schema.ts
  packages/aws-cdk-lib/cloud-assembly-schema/schema/assets.schema.json
  packages/aws-cdk-lib/cloud-assembly-schema/schema/cloud-assembly.schema.json
  packages/aws-cdk-lib/cloud-assembly-schema/schema/cloud-assembly.version.json
  packages/aws-cdk-lib/core/lib/assets.ts
  packages/aws-cdk-lib/core/lib/bundling.ts
  packages/aws-cdk-lib/core/lib/stack-synthesizers/asset-manifest-builder.ts
  packages/aws-cdk-lib/core/lib/stack-synthesizers/legacy.ts
  packages/aws-cdk-lib/core/test/assets.test.ts
  packages/aws-cdk-lib/core/test/bundling.test.ts
  packages/aws-cdk-lib/cx-api/lib/assets.ts
  packages/cdk-assets/lib/private/docker.ts
  packages/cdk-assets/lib/private/handlers/container-images.ts
  packages/cdk-assets/test/docker-images.test.ts
Labels: p1, feature-request, effort/medium, admired-contributor

#27903 fix(lambda-python-alpha): bundling hash logic includes auth tokens in PIP urls, causing an unnecessary rebuild
  packages/@aws-cdk/aws-lambda-python-alpha/test/integ.function.js.snapshot/asset.73c20a669c041469f7fc3fc03d574b093b5b97e7c716f76c1e8117e6163e4dc4.bundle/index.js
  packages/@aws-cdk/aws-lambda-python-alpha/test/integ.function.js.snapshot/asset.a5feac1d1e65b04919886f5961fd2ba1352489d558439d9d6592877e92fc2814.bundle/index.js
  packages/@aws-cdk/aws-lambda-python-alpha/test/integ.function.js.snapshot/cdk.out
  packages/@aws-cdk/aws-lambda-python-alpha/test/integ.function.js.snapshot/integ-lambda-python-function.assets.json
  packages/@aws-cdk/aws-lambda-python-alpha/test/integ.function.js.snapshot/integ-lambda-python-function.template.json
  packages/@aws-cdk/aws-lambda-python-alpha/test/integ.function.js.snapshot/integ.json
  packages/@aws-cdk/aws-lambda-python-alpha/test/integ.function.js.snapshot/lambdapythonfunctionDefaultTestDeployAssertC9C6EE6F.assets.json
  packages/@aws-cdk/aws-lambda-python-alpha/test/integ.function.js.snapshot/lambdapythonfunctionDefaultTestDeployAssertC9C6EE6F.template.json
  packages/@aws-cdk/aws-lambda-python-alpha/test/integ.function.js.snapshot/manifest.json
  packages/@aws-cdk/aws-lambda-python-alpha/test/integ.function.js.snapshot/tree.json
  packages/@aws-cdk/aws-lambda-python-alpha/test/integ.function.ts
  packages/aws-cdk-lib/core/lib/asset-staging.ts
  packages/aws-cdk-lib/core/test/staging.test.ts
Labels: bug, p2, effort/medium, beginning-contributor

#28481 chore: refuse to close PRs that are awaiting maintainer review
  .github/workflows/close-stale-prs.yml
Labels: p2, contribution/core

#28394 fix(ecs-patterns): `ApplicationMultipleTargetGroupsEc2Service` ignores load balancer name
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs-patterns/test/ec2/integ.healthchecks-multiple-application-load-balanced-ecs-service.js.snapshot/aws-ecs-integ-multiple-alb-healthchecks.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs-patterns/test/ec2/integ.healthchecks-multiple-application-load-balanced-ecs-service.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs-patterns/test/ec2/integ.multiple-application-load-balanced-ecs-service-idle-timeout.js.snapshot/aws-ecs-integ-alb-idle-timeout.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs-patterns/test/ec2/integ.multiple-application-load-balanced-ecs-service-idle-timeout.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs-patterns/test/ec2/integ.multiple-application-load-balanced-ecs-service-idle-timeout.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs-patterns/test/ec2/integ.multiple-application-load-balanced-ecs-service-idle-timeout.ts
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs-patterns/test/ec2/integ.multiple-application-load-balanced-ecs-service.js.snapshot/aws-ecs-integ-multiple-alb.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs-patterns/test/fargate/integ.healthchecks-multiple-application-load-balanced-fargate-service.js.snapshot/aws-ecs-integ-fargate-multi-alb-health.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs-patterns/test/fargate/integ.healthchecks-multiple-application-load-balanced-fargate-service.js.snapshot/tree.json
  packages/aws-cdk-lib/aws-ecs-patterns/lib/base/application-multiple-target-groups-service-base.ts
  packages/aws-cdk-lib/aws-ecs-patterns/test/ec2/l3s-v2.test.ts
Labels: bug, p2, effort/small, distinguished-contributor, pr/needs-maintainer-review

#28486 feat(ecs): enable cluster to grant task protection API permissions to IAM entities
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs/test/integ.cluster-grant-task-protection.js.snapshot/aws-ecs-integ.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs/test/integ.cluster-grant-task-protection.js.snapshot/aws-ecs-integ.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs/test/integ.cluster-grant-task-protection.js.snapshot/awsecsclustergranttaskprotectionDefaultTestDeployAssert24DEFE93.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs/test/integ.cluster-grant-task-protection.js.snapshot/awsecsclustergranttaskprotectionDefaultTestDeployAssert24DEFE93.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs/test/integ.cluster-grant-task-protection.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs/test/integ.cluster-grant-task-protection.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs/test/integ.cluster-grant-task-protection.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs/test/integ.cluster-grant-task-protection.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs/test/integ.cluster-grant-task-protection.ts
  packages/aws-cdk-lib/aws-ecs/README.md
  packages/aws-cdk-lib/aws-ecs/lib/cluster.ts
  packages/aws-cdk-lib/aws-ecs/test/cluster.test.ts
Labels: p2, feature-request, effort/small, valued-contributor

#28488 feat(ecs): nvidia support to BottlerocketEcsVariant enum for gpu-accelerated tasks
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs/test/integ.cluster-bottlerocket-nvidia-ami.js.snapshot/aws-ecs-integ-bottlerocket-nvidia-ami.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs/test/integ.cluster-bottlerocket-nvidia-ami.js.snapshot/aws-ecs-integ-bottlerocket-nvidia-ami.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs/test/integ.cluster-bottlerocket-nvidia-ami.js.snapshot/awsecsbottlerocketnvidiaamiDefaultTestDeployAssert682D6B79.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs/test/integ.cluster-bottlerocket-nvidia-ami.js.snapshot/awsecsbottlerocketnvidiaamiDefaultTestDeployAssert682D6B79.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs/test/integ.cluster-bottlerocket-nvidia-ami.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs/test/integ.cluster-bottlerocket-nvidia-ami.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs/test/integ.cluster-bottlerocket-nvidia-ami.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs/test/integ.cluster-bottlerocket-nvidia-ami.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs/test/integ.cluster-bottlerocket-nvidia-ami.ts
  packages/aws-cdk-lib/aws-ecs/README.md
  packages/aws-cdk-lib/aws-ecs/lib/amis.ts
  packages/aws-cdk-lib/aws-ecs/test/amis.test.ts
Labels: p2, feature-request, effort/small, valued-contributor, pr/needs-maintainer-review

#27643 feat(glue-alpha): add `cfn-glue-table-tableinput-parameters` to Glue table construct
  packages/@aws-cdk/aws-glue-alpha/README.md
  packages/@aws-cdk/aws-glue-alpha/lib/external-table.ts
  packages/@aws-cdk/aws-glue-alpha/lib/s3-table.ts
  packages/@aws-cdk/aws-glue-alpha/lib/table-base.ts
  packages/@aws-cdk/aws-glue-alpha/test/external-table.test.ts
  packages/@aws-cdk/aws-glue-alpha/test/integ.table.js.snapshot/aws-cdk-glue.assets.json
  packages/@aws-cdk/aws-glue-alpha/test/integ.table.js.snapshot/aws-cdk-glue.template.json
  packages/@aws-cdk/aws-glue-alpha/test/integ.table.js.snapshot/manifest.json
  packages/@aws-cdk/aws-glue-alpha/test/integ.table.js.snapshot/tree.json
  packages/@aws-cdk/aws-glue-alpha/test/integ.table.ts
  packages/@aws-cdk/aws-glue-alpha/test/s3-table.test.ts
  packages/@aws-cdk/aws-glue-alpha/test/table-base.test.ts
Labels: p1, feature-request, effort/small, beginning-contributor, pr/needs-maintainer-review

#28503 chore(merge-back): 2.117.0
  CHANGELOG.v2.alpha.md
  CHANGELOG.v2.md
  version.v2.json
Labels: p2, pr/needs-community-review, pr/no-squash, auto-approve

#28497 feat(opensearchservice): ip address type for domain
  packages/@aws-cdk-testing/framework-integ/test/aws-opensearchservice/test/integ.opensearch.ip-address-type.js.snapshot/OpenSearchIpAddressTypeIntegDefaultTestDeployAssertE117ADBF.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-opensearchservice/test/integ.opensearch.ip-address-type.js.snapshot/OpenSearchIpAddressTypeIntegDefaultTestDeployAssertE117ADBF.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-opensearchservice/test/integ.opensearch.ip-address-type.js.snapshot/cdk-integ-opensearch-ip-address-type.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-opensearchservice/test/integ.opensearch.ip-address-type.js.snapshot/cdk-integ-opensearch-ip-address-type.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-opensearchservice/test/integ.opensearch.ip-address-type.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-opensearchservice/test/integ.opensearch.ip-address-type.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-opensearchservice/test/integ.opensearch.ip-address-type.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-opensearchservice/test/integ.opensearch.ip-address-type.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-opensearchservice/test/integ.opensearch.ip-address-type.ts
  packages/aws-cdk-lib/aws-opensearchservice/README.md
  packages/aws-cdk-lib/aws-opensearchservice/lib/domain.ts
  packages/aws-cdk-lib/aws-opensearchservice/test/domain.test.ts
  packages/aws-cdk-lib/rosetta/aws_opensearchservice/default.ts-fixture
Labels: p2, feature-request, effort/medium, distinguished-contributor, pr/needs-maintainer-review

#28500 feat(appsync): IntrospectionConfig property
  packages/@aws-cdk-testing/framework-integ/test/aws-appsync/test/integ.appsync-disable-introspection.js.snapshot/apiDefaultTestDeployAssert018781F2.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-appsync/test/integ.appsync-disable-introspection.js.snapshot/apiDefaultTestDeployAssert018781F2.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-appsync/test/integ.appsync-disable-introspection.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-appsync/test/integ.appsync-disable-introspection.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-appsync/test/integ.appsync-disable-introspection.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-appsync/test/integ.appsync-disable-introspection.js.snapshot/stack.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-appsync/test/integ.appsync-disable-introspection.js.snapshot/stack.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-appsync/test/integ.appsync-disable-introspection.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-appsync/test/integ.appsync-disable-introspection.ts
  packages/aws-cdk-lib/aws-appsync/README.md
  packages/aws-cdk-lib/aws-appsync/lib/graphqlapi.ts
  packages/aws-cdk-lib/aws-appsync/test/appsync.test.ts
Labels: bug, p2, pr/needs-community-review, effort/medium, repeat-contributor

#28471 fix(rds): circular dependencies when creating multiple DatabaseProxies
  packages/@aws-cdk-testing/framework-integ/test/aws-rds/test/integ.proxy.js.snapshot/aws-cdk-rds-proxy.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-rds/test/integ.proxy.js.snapshot/aws-cdk-rds-proxy.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-rds/test/integ.proxy.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-rds/test/integ.proxy.js.snapshot/databaseproxyintegtestDefaultTestDeployAssert1DC3D9D5.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-rds/test/integ.proxy.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-rds/test/integ.proxy.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-rds/test/integ.proxy.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-rds/test/integ.proxy.ts
  packages/aws-cdk-lib/aws-rds/lib/proxy.ts
  packages/aws-cdk-lib/aws-rds/test/proxy.test.ts
Labels: bug, p1, effort/medium, valued-contributor, pr/needs-maintainer-review

#28505 chore(prlint): fix broken link to get trusted members
  tools/@aws-cdk/prlint/lint.ts
Labels: p2, pr/needs-community-review, admired-contributor

#28504 chore(lambda): formatting of enums
  packages/aws-cdk-lib/aws-lambda/lib/function.ts
Labels: p2, contribution/core, pr/needs-maintainer-review

#28464 feat(autoscaling): add support for `InstanceRequirements` property
  packages/@aws-cdk-testing/framework-integ/test/aws-autoscaling/test/integ.asg-lt.js.snapshot/aws-cdk-asg-integ.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-autoscaling/test/integ.asg-lt.js.snapshot/aws-cdk-asg-integ.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-autoscaling/test/integ.asg-lt.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-autoscaling/test/integ.asg-lt.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-autoscaling/test/integ.asg-lt.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-autoscaling/test/integ.asg-lt.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-autoscaling/test/integ.asg-lt.ts
  packages/aws-cdk-lib/aws-autoscaling/README.md
  packages/aws-cdk-lib/aws-autoscaling/lib/auto-scaling-group.ts
  packages/aws-cdk-lib/aws-autoscaling/test/auto-scaling-group.test.ts
Labels: p2, feature-request, effort/small, repeat-contributor, pr-linter/exemption-requested

#28298 chore(sns): use ICfnTopic wherever possible
  packages/@aws-cdk/aws-appconfig-alpha/lib/extension.ts
  packages/@aws-cdk/aws-iot-actions-alpha/lib/sns-topic-action.ts
  packages/@aws-cdk/aws-scheduler-targets-alpha/lib/sns-publish.ts
  packages/aws-cdk-lib/aws-autoscaling-hooktargets/lib/topic-hook.ts
  packages/aws-cdk-lib/aws-autoscaling/lib/auto-scaling-group.ts
  packages/aws-cdk-lib/aws-backup/lib/vault.ts
  packages/aws-cdk-lib/aws-chatbot/lib/slack-channel-configuration.ts
  packages/aws-cdk-lib/aws-cloudformation/lib/nested-stack.ts
  packages/aws-cdk-lib/aws-cloudtrail/lib/cloudtrail.ts
  packages/aws-cdk-lib/aws-cloudwatch-actions/lib/sns.ts
  packages/aws-cdk-lib/aws-codepipeline-actions/lib/manual-approval-action.ts
  packages/aws-cdk-lib/aws-config/lib/managed-rules.ts
  packages/aws-cdk-lib/aws-lambda-destinations/lib/sns.ts
  packages/aws-cdk-lib/aws-lambda-event-sources/lib/sns-dlq.ts
  packages/aws-cdk-lib/aws-lambda/lib/function.ts
  packages/aws-cdk-lib/aws-s3-notifications/lib/sns.ts
  packages/aws-cdk-lib/aws-ses-actions/lib/bounce.ts
  packages/aws-cdk-lib/aws-ses-actions/lib/s3.ts
  packages/aws-cdk-lib/aws-ses-actions/lib/stop.ts
  packages/aws-cdk-lib/aws-sns-subscriptions/lib/email.ts
  packages/aws-cdk-lib/aws-sns-subscriptions/lib/lambda.ts
  packages/aws-cdk-lib/aws-sns-subscriptions/lib/sms.ts
  packages/aws-cdk-lib/aws-sns-subscriptions/lib/sqs.ts
  packages/aws-cdk-lib/aws-sns-subscriptions/lib/url.ts
  packages/aws-cdk-lib/aws-sns/lib/policy.ts
  packages/aws-cdk-lib/aws-sns/lib/subscriber.ts
  packages/aws-cdk-lib/aws-sns/lib/subscription.ts
  packages/aws-cdk-lib/aws-sns/lib/topic-base.ts
  packages/aws-cdk-lib/aws-sns/lib/topic.ts
  packages/aws-cdk-lib/aws-stepfunctions-tasks/lib/sns/publish-to-topic.ts
  packages/aws-cdk-lib/pipelines/lib/codepipeline/confirm-permissions-broadening.ts
Labels: p2, contribution/core

#28473 feat(cloudfront): Key Value Store L2
  packages/@aws-cdk-testing/framework-integ/test/aws-cloudfront/test/integ.key-value-store.js.snapshot/KeyValueStoreDefaultTestDeployAssert87336A31.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-cloudfront/test/integ.key-value-store.js.snapshot/KeyValueStoreDefaultTestDeployAssert87336A31.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-cloudfront/test/integ.key-value-store.js.snapshot/asset.9c0f502203ec9d802046021b8a20affe8fd26234f67dcf2e93db5142bc2991a1.json
  packages/@aws-cdk-testing/framework-integ/test/aws-cloudfront/test/integ.key-value-store.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-cloudfront/test/integ.key-value-store.js.snapshot/integ-key-value-store.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-cloudfront/test/integ.key-value-store.js.snapshot/integ-key-value-store.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-cloudfront/test/integ.key-value-store.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-cloudfront/test/integ.key-value-store.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-cloudfront/test/integ.key-value-store.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-cloudfront/test/integ.key-value-store.ts
  packages/@aws-cdk-testing/framework-integ/test/aws-cloudfront/test/test-import-source.json
  packages/aws-cdk-lib/aws-cloudfront/README.md
  packages/aws-cdk-lib/aws-cloudfront/lib/index.ts
  packages/aws-cdk-lib/aws-cloudfront/lib/key-value-store.ts
  packages/aws-cdk-lib/aws-cloudfront/test/key-value-store-source.json
  packages/aws-cdk-lib/aws-cloudfront/test/key-value-store.test.ts
Labels: p2, feature-request, effort/medium, star-contributor

#28099 feat(cloudfront): CloudFront Function runtime property
  .pre-commit-config.yaml
  packages/@aws-cdk-testing/framework-integ/test/aws-cloudfront/test/integ.distribution-function-runtime.js.snapshot/CF2RuntimeDefaultTestDeployAssertB25F4037.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-cloudfront/test/integ.distribution-function-runtime.js.snapshot/CF2RuntimeDefaultTestDeployAssertB25F4037.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-cloudfront/test/integ.distribution-function-runtime.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-cloudfront/test/integ.distribution-function-runtime.js.snapshot/integ-distribution-function.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-cloudfront/test/integ.distribution-function-runtime.js.snapshot/integ-distribution-function.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-cloudfront/test/integ.distribution-function-runtime.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-cloudfront/test/integ.distribution-function-runtime.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-cloudfront/test/integ.distribution-function-runtime.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-cloudfront/test/integ.distribution-function-runtime.ts
  packages/aws-cdk-lib/aws-cloudfront/README.md
  packages/aws-cdk-lib/aws-cloudfront/lib/function.ts
  packages/aws-cdk-lib/aws-cloudfront/test/function.test.ts
  packages/aws-cdk-lib/awslint.json
Labels: p2, feature-request, effort/medium, distinguished-contributor

#28508 feat(rds): new Aurora Postgres engine versions
  packages/aws-cdk-lib/aws-rds/lib/cluster-engine.ts
Labels: p2, pr-linter/exempt-readme, pr-linter/exempt-test, pr-linter/exempt-integ-test, beginning-contributor

#28529 feat(stepfunctions-tasks): add validations for EmrCreateCluster
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-nodejs/test/integ.latest.js.snapshot/LambdaNodeJsLatestIntegDefaultTestDeployAssertD40B5C28.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-nodejs/test/integ.latest.js.snapshot/LambdaNodeJsLatestIntegDefaultTestDeployAssertD40B5C28.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-nodejs/test/integ.latest.js.snapshot/asset.eed45a32a57f32bc36031539054db0b27239d161061c528482bb55be51068664/index.js
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-nodejs/test/integ.latest.js.snapshot/asset.eed45a32a57f32bc36031539054db0b27239d161061c528482bb55be51068664/node_modules/.yarn-integrity
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-nodejs/test/integ.latest.js.snapshot/asset.eed45a32a57f32bc36031539054db0b27239d161061c528482bb55be51068664/node_modules/delay/index.d.ts
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-nodejs/test/integ.latest.js.snapshot/asset.eed45a32a57f32bc36031539054db0b27239d161061c528482bb55be51068664/node_modules/delay/index.js
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-nodejs/test/integ.latest.js.snapshot/asset.eed45a32a57f32bc36031539054db0b27239d161061c528482bb55be51068664/node_modules/delay/license
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-nodejs/test/integ.latest.js.snapshot/asset.eed45a32a57f32bc36031539054db0b27239d161061c528482bb55be51068664/node_modules/delay/package.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-nodejs/test/integ.latest.js.snapshot/asset.eed45a32a57f32bc36031539054db0b27239d161061c528482bb55be51068664/node_modules/delay/readme.md
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-nodejs/test/integ.latest.js.snapshot/asset.eed45a32a57f32bc36031539054db0b27239d161061c528482bb55be51068664/package.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-nodejs/test/integ.latest.js.snapshot/asset.eed45a32a57f32bc36031539054db0b27239d161061c528482bb55be51068664/yarn.lock
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-nodejs/test/integ.latest.js.snapshot/cdk-integ-lambda-nodejs-latest.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-nodejs/test/integ.latest.js.snapshot/cdk-integ-lambda-nodejs-latest.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-nodejs/test/integ.latest.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-nodejs/test/integ.latest.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-nodejs/test/integ.latest.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-nodejs/test/integ.latest.js.snapshot/tree.json
  packages/aws-cdk-lib/aws-stepfunctions-tasks/lib/emr/emr-create-cluster.ts
  packages/aws-cdk-lib/aws-stepfunctions-tasks/lib/emr/private/cluster-utils.ts
  packages/aws-cdk-lib/aws-stepfunctions-tasks/test/emr/emr-create-cluster.test.ts
Labels: p2, pr/needs-community-review, pr-linter/exempt-readme, pr-linter/exempt-integ-test, distinguished-contributor

#28525 feat(stepfunctions-tasks): additional allocation strategies for spot instance fleets in EmrCreateCluster
  packages/aws-cdk-lib/aws-stepfunctions-tasks/lib/emr/emr-create-cluster.ts
  packages/aws-cdk-lib/aws-stepfunctions-tasks/test/emr/emr-create-cluster.test.ts
Labels: p2, pr-linter/exempt-readme, pr-linter/exempt-integ-test, distinguished-contributor

#28510 fix(iam): withConditions overrides Principal actions
  packages/@aws-cdk-testing/framework-integ/test/aws-iam/test/integ.principal-with-conditions-and-tags.js.snapshot/PrincipalWithConditionAndTagsDefaultTestDeployAssertA5074573.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-iam/test/integ.principal-with-conditions-and-tags.js.snapshot/PrincipalWithConditionAndTagsDefaultTestDeployAssertA5074573.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-iam/test/integ.principal-with-conditions-and-tags.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-iam/test/integ.principal-with-conditions-and-tags.js.snapshot/integ-principal-with-conditions-and-tags.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-iam/test/integ.principal-with-conditions-and-tags.js.snapshot/integ-principal-with-conditions-and-tags.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-iam/test/integ.principal-with-conditions-and-tags.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-iam/test/integ.principal-with-conditions-and-tags.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-iam/test/integ.principal-with-conditions-and-tags.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-iam/test/integ.principal-with-conditions-and-tags.ts
  packages/aws-cdk-lib/aws-iam/lib/principals.ts
  packages/aws-cdk-lib/aws-iam/test/principals.test.ts
Labels: bug, p2, effort/small, distinguished-contributor

#28491 feat(codepipeline-actions): more convenient methods to `CacheControl`
  packages/aws-cdk-lib/aws-codepipeline-actions/lib/s3/deploy-action.ts
  packages/aws-cdk-lib/aws-codepipeline-actions/test/s3/s3-deploy-action.test.ts
Labels: p2, pr-linter/exempt-readme, pr-linter/exempt-integ-test, valued-contributor

#27744 feat(glue): database description property
  packages/@aws-cdk/aws-glue-alpha/README.md
  packages/@aws-cdk/aws-glue-alpha/lib/database.ts
  packages/@aws-cdk/aws-glue-alpha/test/database.test.ts
  packages/@aws-cdk/aws-glue-alpha/test/integ.table.js.snapshot/aws-cdk-glue.assets.json
  packages/@aws-cdk/aws-glue-alpha/test/integ.table.js.snapshot/aws-cdk-glue.template.json
  packages/@aws-cdk/aws-glue-alpha/test/integ.table.js.snapshot/manifest.json
  packages/@aws-cdk/aws-glue-alpha/test/integ.table.js.snapshot/tree.json
  packages/@aws-cdk/aws-glue-alpha/test/integ.table.ts
Labels: p2, feature-request, admired-contributor

#28533 chore(codebuild): deprecate images that are no longer actively maintained
  packages/aws-cdk-lib/aws-codebuild/lib/linux-arm-build-image.ts
  packages/aws-cdk-lib/aws-codebuild/lib/project.ts
Labels: p2, admired-contributor
