Repository aws/aws-cdk, pull requests merged in 2023-10, with the labels that each got.

#27366 chore: update Contributors File
  CONTRIBUTORS.md
Labels: p2, auto-approve

#27375 feat: update AWS Service Spec
  tools/@aws-cdk/spec2cdk/package.json
  yarn.lock
Labels: p2, dependencies, contribution/core, pr-linter/exempt-readme, pr-linter/exempt-test, auto-approve, pr-linter/exempt-integ-test

#27357 docs(s3-deployment): dataJson should be jsonData
  packages/aws-cdk-lib/aws-s3-deployment/lib/source.ts
Labels: p2, beginning-contributor

#27376 chore: align-version script drops caret from dependencies it rewrites
  packages/@aws-cdk/app-staging-synthesizer-alpha/package.json
  packages/@aws-cdk/aws-appconfig-alpha/package.json
  packages/@aws-cdk/custom-resource-handlers/package.json
  packages/@aws-cdk/example-construct-library/package.json
  scripts/align-version.js
  tools/@aws-cdk/pkglint/lib/rules.ts
Labels: p2, contribution/core

#27362 feat(aws-cdk-lib): reduce JavaScript load time, second attempt
  packages/@aws-cdk-testing/cli-integ/tests/init-javascript/init-javascript.integtest.ts
  packages/aws-cdk-lib/custom-resource-handlers/.is_custom_resource
  tools/@aws-cdk/lazify/lib/index.ts
  tools/@aws-cdk/lazify/package.json
  tools/@aws-cdk/lazify/test/export-star.test.ts
  yarn.lock
Labels: p2, contribution/core, pr-linter/exempt-readme, pr-linter/exempt-integ-test

#27394 chore(synthetics): restore synthetics alpha module
  packages/@aws-cdk/aws-synthetics-alpha/.eslintrc.js
  packages/@aws-cdk/aws-synthetics-alpha/.gitignore
  packages/@aws-cdk/aws-synthetics-alpha/.npmignore
  packages/@aws-cdk/aws-synthetics-alpha/LICENSE
  packages/@aws-cdk/aws-synthetics-alpha/NOTICE
  packages/@aws-cdk/aws-synthetics-alpha/README.md
  packages/@aws-cdk/aws-synthetics-alpha/awslint.json
  packages/@aws-cdk/aws-synthetics-alpha/images/endpoint-example.png
  packages/@aws-cdk/aws-synthetics-alpha/images/ui-screenshot.png
  packages/@aws-cdk/aws-synthetics-alpha/jest.config.js
  packages/@aws-cdk/aws-synthetics-alpha/lib/canary.ts
  packages/@aws-cdk/aws-synthetics-alpha/lib/code.ts
  packages/@aws-cdk/aws-synthetics-alpha/lib/index.ts
  packages/@aws-cdk/aws-synthetics-alpha/lib/runtime.ts
  packages/@aws-cdk/aws-synthetics-alpha/lib/schedule.ts
  packages/@aws-cdk/aws-synthetics-alpha/package.json
  packages/@aws-cdk/aws-synthetics-alpha/rosetta/default.ts-fixture
  packages/@aws-cdk/aws-synthetics-alpha/scripts/airlift-custom-resource-handlers.sh
  packages/@aws-cdk/aws-synthetics-alpha/test/canaries/nodejs/node_modules/canary.js
  packages/@aws-cdk/aws-synthetics-alpha/test/canaries/nodejs/node_modules/folder/canary.js
  packages/@aws-cdk/aws-synthetics-alpha/test/canaries/python/canary.py
  packages/@aws-cdk/aws-synthetics-alpha/test/canary.test.ts
  packages/@aws-cdk/aws-synthetics-alpha/test/canary.zip
  packages/@aws-cdk/aws-synthetics-alpha/test/code.test.ts
  packages/@aws-cdk/aws-synthetics-alpha/test/integ.canary-auto-delete-lambda.js.snapshot/cdk-synthetics-canary-auto-delete.assets.json
  packages/@aws-cdk/aws-synthetics-alpha/test/integ.canary-auto-delete-lambda.js.snapshot/cdk-synthetics-canary-auto-delete.template.json
  packages/@aws-cdk/aws-synthetics-alpha/test/integ.canary-auto-delete-lambda.js.snapshot/cdk.out
  packages/@aws-cdk/aws-synthetics-alpha/test/integ.canary-auto-delete-lambda.js.snapshot/cdkintegsyntheticscanaryautodeleteDefaultTestDeployAssert94B79CED.assets.json
  packages/@aws-cdk/aws-synthetics-alpha/test/integ.canary-auto-delete-lambda.js.snapshot/cdkintegsyntheticscanaryautodeleteDefaultTestDeployAssert94B79CED.template.json
  packages/@aws-cdk/aws-synthetics-alpha/test/integ.canary-auto-delete-lambda.js.snapshot/integ.json
  packages/@aws-cdk/aws-synthetics-alpha/test/integ.canary-auto-delete-lambda.js.snapshot/manifest.json
  packages/@aws-cdk/aws-synthetics-alpha/test/integ.canary-auto-delete-lambda.js.snapshot/tree.json
  packages/@aws-cdk/aws-synthetics-alpha/test/integ.canary-auto-delete-lambda.ts
  packages/@aws-cdk/aws-synthetics-alpha/test/integ.canary.js.snapshot/IntegCanaryTestDefaultTestDeployAssert3AD5A094.assets.json
  packages/@aws-cdk/aws-synthetics-alpha/test/integ.canary.js.snapshot/IntegCanaryTestDefaultTestDeployAssert3AD5A094.template.json
  packages/@aws-cdk/aws-synthetics-alpha/test/integ.canary.js.snapshot/asset.086fe534b1e7545fbc662251685b8a7d91ab2061bbfe98d857b27478442487cb/index.js
  packages/@aws-cdk/aws-synthetics-alpha/test/integ.canary.js.snapshot/asset.294c96d7313c65f945a0d69f7b736dacbd169f3c6fe864b216c754371be2e195.bundle/index.js
  packages/@aws-cdk/aws-synthetics-alpha/test/integ.canary.js.snapshot/asset.2ec8ad9e91dcd6e7ad6a5c84ffc6c9c05c408aca3b26ceb2816d81043e6c4dc3/index.js
  packages/@aws-cdk/aws-synthetics-alpha/test/integ.canary.js.snapshot/asset.b1b777dcb79a2fa2790059927207d10bf5f4747d6dd1516e2780726d9d6fa820.zip
  packages/@aws-cdk/aws-synthetics-alpha/test/integ.canary.js.snapshot/asset.d6b51cbdd22d449b9e57c20ef9d0977e1cfbf06806f8008ce376101a2ad432a8/nodejs/node_modules/canary.js
  packages/@aws-cdk/aws-synthetics-alpha/test/integ.canary.js.snapshot/asset.d6b51cbdd22d449b9e57c20ef9d0977e1cfbf06806f8008ce376101a2ad432a8/nodejs/node_modules/folder/canary.js
  packages/@aws-cdk/aws-synthetics-alpha/test/integ.canary.js.snapshot/asset.d6b51cbdd22d449b9e57c20ef9d0977e1cfbf06806f8008ce376101a2ad432a8/python/canary.py
  packages/@aws-cdk/aws-synthetics-alpha/test/integ.canary.js.snapshot/canary-one.assets.json
  packages/@aws-cdk/aws-synthetics-alpha/test/integ.canary.js.snapshot/canary-one.template.json
  packages/@aws-cdk/aws-synthetics-alpha/test/integ.canary.js.snapshot/cdk.out
  packages/@aws-cdk/aws-synthetics-alpha/test/integ.canary.js.snapshot/integ.json
  packages/@aws-cdk/aws-synthetics-alpha/test/integ.canary.js.snapshot/manifest.json
  packages/@aws-cdk/aws-synthetics-alpha/test/integ.canary.js.snapshot/tree.json
  packages/@aws-cdk/aws-synthetics-alpha/test/integ.canary.ts
  packages/@aws-cdk/aws-synthetics-alpha/test/integ.vpc.js.snapshot/asset.b1b777dcb79a2fa2790059927207d10bf5f4747d6dd1516e2780726d9d6fa820.zip
  packages/@aws-cdk/aws-synthetics-alpha/test/integ.vpc.js.snapshot/canary-vpc.assets.json
  packages/@aws-cdk/aws-synthetics-alpha/test/integ.vpc.js.snapshot/canary-vpc.template.json
  packages/@aws-cdk/aws-synthetics-alpha/test/integ.vpc.js.snapshot/cdk.out
  packages/@aws-cdk/aws-synthetics-alpha/test/integ.vpc.js.snapshot/manifest.json
  packages/@aws-cdk/aws-synthetics-alpha/test/integ.vpc.js.snapshot/tree.json
  packages/@aws-cdk/aws-synthetics-alpha/test/integ.vpc.ts
  packages/@aws-cdk/aws-synthetics-alpha/test/metric.test.ts
  packages/@aws-cdk/aws-synthetics-alpha/test/schedule.test.ts
  packages/@aws-cdk/custom-resource-handlers/lib/aws-synthetics-alpha/auto-delete-underlying-resources-handler/index.ts
Labels: p2, contribution/core

#27363 chore(merge-back): 2.99.1
  CHANGELOG.v2.alpha.md
  CHANGELOG.v2.md
  version.v2.json
Labels: p2, pr/needs-community-review, pr/no-squash, auto-approve

#27391 chore(core): enable deletion of more than 10 ssm parameters at a time
  packages/@aws-cdk-testing/framework-integ/test/core/test/integ.cross-region-references.js.snapshot/CrossRegionRefProducerInteg.assets.json
  packages/@aws-cdk-testing/framework-integ/test/core/test/integ.cross-region-references.js.snapshot/CrossRegionRefProducerInteg.template.json
  packages/@aws-cdk-testing/framework-integ/test/core/test/integ.cross-region-references.js.snapshot/asset.0cd3b0876ff31491e457d92c24b80c95310950e9839c43eb5a86ad9535d15597/__entrypoint__.js
  packages/@aws-cdk-testing/framework-integ/test/core/test/integ.cross-region-references.js.snapshot/asset.0cd3b0876ff31491e457d92c24b80c95310950e9839c43eb5a86ad9535d15597/index.js
  packages/@aws-cdk-testing/framework-integ/test/core/test/integ.cross-region-references.js.snapshot/asset.1a067234d252533a95ecaaccd4b3e821e6a69df0b03b918b596fc5a40eeb71a1/index.js
  packages/@aws-cdk-testing/framework-integ/test/core/test/integ.cross-region-references.js.snapshot/manifest.json
  packages/aws-cdk-lib/core/lib/custom-resource-provider/cross-region-export-providers/cross-region-ssm-writer-handler/index.ts
  packages/aws-cdk-lib/core/test/custom-resource-provider/cross-region-ssm-writer-handler.test.ts
Labels: p2, pr-linter/exempt-integ-test, beginning-contributor, pr/reviewer-clarification-requested

#27403 chore: remove unused packages
  package.json
Labels: p2, distinguished-contributor

#27373 feat(eks): support INF2 instance types
  packages/@aws-cdk-testing/framework-integ/test/aws-eks/test/integ.eks-inference.js.snapshot/asset.0f19e51d1e47290d7a33e0b67405e4722942dee4b92b9d29425fccf0d99017c3/apply/__init__.py
  packages/@aws-cdk-testing/framework-integ/test/aws-eks/test/integ.eks-inference.js.snapshot/asset.0f19e51d1e47290d7a33e0b67405e4722942dee4b92b9d29425fccf0d99017c3/get/__init__.py
  packages/@aws-cdk-testing/framework-integ/test/aws-eks/test/integ.eks-inference.js.snapshot/asset.0f19e51d1e47290d7a33e0b67405e4722942dee4b92b9d29425fccf0d99017c3/helm/__init__.py
  packages/@aws-cdk-testing/framework-integ/test/aws-eks/test/integ.eks-inference.js.snapshot/asset.0f19e51d1e47290d7a33e0b67405e4722942dee4b92b9d29425fccf0d99017c3/index.py
  packages/@aws-cdk-testing/framework-integ/test/aws-eks/test/integ.eks-inference.js.snapshot/asset.0f19e51d1e47290d7a33e0b67405e4722942dee4b92b9d29425fccf0d99017c3/patch/__init__.py
  packages/@aws-cdk-testing/framework-integ/test/aws-eks/test/integ.eks-inference.js.snapshot/asset.81328426dba578d9ff57b0b54146bc81395a478131b0b61e40236fcc8395c2db/outbound.js
  packages/@aws-cdk-testing/framework-integ/test/aws-eks/test/integ.eks-inference.js.snapshot/asset.968f385a33c07678c81a74fa6d36baf4a5efe934fe6d178d5585ecaafe89b934/cluster.js
  packages/@aws-cdk-testing/framework-integ/test/aws-eks/test/integ.eks-inference.js.snapshot/asset.968f385a33c07678c81a74fa6d36baf4a5efe934fe6d178d5585ecaafe89b934/common.js
  packages/@aws-cdk-testing/framework-integ/test/aws-eks/test/integ.eks-inference.js.snapshot/asset.968f385a33c07678c81a74fa6d36baf4a5efe934fe6d178d5585ecaafe89b934/compareLogging.js
  packages/@aws-cdk-testing/framework-integ/test/aws-eks/test/integ.eks-inference.js.snapshot/asset.968f385a33c07678c81a74fa6d36baf4a5efe934fe6d178d5585ecaafe89b934/consts.js
  packages/@aws-cdk-testing/framework-integ/test/aws-eks/test/integ.eks-inference.js.snapshot/asset.968f385a33c07678c81a74fa6d36baf4a5efe934fe6d178d5585ecaafe89b934/fargate.js
  packages/@aws-cdk-testing/framework-integ/test/aws-eks/test/integ.eks-inference.js.snapshot/asset.968f385a33c07678c81a74fa6d36baf4a5efe934fe6d178d5585ecaafe89b934/index.js
  packages/@aws-cdk-testing/framework-integ/test/aws-eks/test/integ.eks-inference.js.snapshot/asset.9efb96d8186dd343e3f84c72cfbcaaf16aa5579bbac0c02c60d4f19f4300d832/cluster.d.ts
  packages/@aws-cdk-testing/framework-integ/test/aws-eks/test/integ.eks-inference.js.snapshot/asset.9efb96d8186dd343e3f84c72cfbcaaf16aa5579bbac0c02c60d4f19f4300d832/cluster.js
  packages/@aws-cdk-testing/framework-integ/test/aws-eks/test/integ.eks-inference.js.snapshot/asset.9efb96d8186dd343e3f84c72cfbcaaf16aa5579bbac0c02c60d4f19f4300d832/cluster.ts
  packages/@aws-cdk-testing/framework-integ/test/aws-eks/test/integ.eks-inference.js.snapshot/asset.9efb96d8186dd343e3f84c72cfbcaaf16aa5579bbac0c02c60d4f19f4300d832/common.d.ts
  packages/@aws-cdk-testing/framework-integ/test/aws-eks/test/integ.eks-inference.js.snapshot/asset.9efb96d8186dd343e3f84c72cfbcaaf16aa5579bbac0c02c60d4f19f4300d832/common.js
  packages/@aws-cdk-testing/framework-integ/test/aws-eks/test/integ.eks-inference.js.snapshot/asset.9efb96d8186dd343e3f84c72cfbcaaf16aa5579bbac0c02c60d4f19f4300d832/common.ts
  packages/@aws-cdk-testing/framework-integ/test/aws-eks/test/integ.eks-inference.js.snapshot/asset.9efb96d8186dd343e3f84c72cfbcaaf16aa5579bbac0c02c60d4f19f4300d832/compareLogging.d.ts
  packages/@aws-cdk-testing/framework-integ/test/aws-eks/test/integ.eks-inference.js.snapshot/asset.9efb96d8186dd343e3f84c72cfbcaaf16aa5579bbac0c02c60d4f19f4300d832/compareLogging.js
  packages/@aws-cdk-testing/framework-integ/test/aws-eks/test/integ.eks-inference.js.snapshot/asset.9efb96d8186dd343e3f84c72cfbcaaf16aa5579bbac0c02c60d4f19f4300d832/compareLogging.ts
  packages/@aws-cdk-testing/framework-integ/test/aws-eks/test/integ.eks-inference.js.snapshot/asset.9efb96d8186dd343e3f84c72cfbcaaf16aa5579bbac0c02c60d4f19f4300d832/consts.d.ts
  packages/@aws-cdk-testing/framework-integ/test/aws-eks/test/integ.eks-inference.js.snapshot/asset.9efb96d8186dd343e3f84c72cfbcaaf16aa5579bbac0c02c60d4f19f4300d832/consts.js
  packages/@aws-cdk-testing/framework-integ/test/aws-eks/test/integ.eks-inference.js.snapshot/asset.9efb96d8186dd343e3f84c72cfbcaaf16aa5579bbac0c02c60d4f19f4300d832/consts.ts
  packages/@aws-cdk-testing/framework-integ/test/aws-eks/test/integ.eks-inference.js.snapshot/asset.9efb96d8186dd343e3f84c72cfbcaaf16aa5579bbac0c02c60d4f19f4300d832/fargate.d.ts
  packages/@aws-cdk-testing/framework-integ/test/aws-eks/test/integ.eks-inference.js.snapshot/asset.9efb96d8186dd343e3f84c72cfbcaaf16aa5579bbac0c02c60d4f19f4300d832/fargate.js
  packages/@aws-cdk-testing/framework-integ/test/aws-eks/test/integ.eks-inference.js.snapshot/asset.9efb96d8186dd343e3f84c72cfbcaaf16aa5579bbac0c02c60d4f19f4300d832/fargate.ts
  packages/@aws-cdk-testing/framework-integ/test/aws-eks/test/integ.eks-inference.js.snapshot/asset.9efb96d8186dd343e3f84c72cfbcaaf16aa5579bbac0c02c60d4f19f4300d832/index.d.ts
  packages/@aws-cdk-testing/framework-integ/test/aws-eks/test/integ.eks-inference.js.snapshot/asset.9efb96d8186dd343e3f84c72cfbcaaf16aa5579bbac0c02c60d4f19f4300d832/index.js
  packages/@aws-cdk-testing/framework-integ/test/aws-eks/test/integ.eks-inference.js.snapshot/asset.9efb96d8186dd343e3f84c72cfbcaaf16aa5579bbac0c02c60d4f19f4300d832/index.ts
  packages/@aws-cdk-testing/framework-integ/test/aws-eks/test/integ.eks-inference.js.snapshot/asset.d002370061965c69bc4caf15dddb5eccc9df318933ade6e4fa57cddb81c5abef/cfn-response.js
  packages/@aws-cdk-testing/framework-integ/test/aws-eks/test/integ.eks-inference.js.snapshot/asset.d002370061965c69bc4caf15dddb5eccc9df318933ade6e4fa57cddb81c5abef/consts.js
  packages/@aws-cdk-testing/framework-integ/test/aws-eks/test/integ.eks-inference.js.snapshot/asset.d002370061965c69bc4caf15dddb5eccc9df318933ade6e4fa57cddb81c5abef/framework.js
  packages/@aws-cdk-testing/framework-integ/test/aws-eks/test/integ.eks-inference.js.snapshot/asset.d002370061965c69bc4caf15dddb5eccc9df318933ade6e4fa57cddb81c5abef/outbound.js
  packages/@aws-cdk-testing/framework-integ/test/aws-eks/test/integ.eks-inference.js.snapshot/asset.d002370061965c69bc4caf15dddb5eccc9df318933ade6e4fa57cddb81c5abef/util.js
  packages/@aws-cdk-testing/framework-integ/test/aws-eks/test/integ.eks-inference.js.snapshot/aws-cdk-eks-cluster-inference-test.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-eks/test/integ.eks-inference.js.snapshot/aws-cdk-eks-cluster-inference-test.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-eks/test/integ.eks-inference.js.snapshot/awscdkeksclusterinferencetestawscdkawseksClusterResourceProviderFE14F3C4.nested.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-eks/test/integ.eks-inference.js.snapshot/awscdkeksclusterinferencetestawscdkawseksKubectlProviderB4348345.nested.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-eks/test/integ.eks-inference.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-eks/test/integ.eks-inference.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-eks/test/integ.eks-inference.ts
  packages/@aws-cdk/aws-sagemaker-alpha/lib/instance-type.ts
  packages/aws-cdk-lib/aws-eks/lib/addons/neuron-device-plugin.yaml
  packages/aws-cdk-lib/aws-eks/lib/instance-types.ts
  packages/aws-cdk-lib/aws-eks/lib/managed-nodegroup.ts
  packages/aws-cdk-lib/aws-eks/test/cluster.test.ts
Labels: p2, pr-linter/exempt-readme, pr-linter/exempt-integ-test, beginning-contributor

#27388 fix(logs): remove invalid data protection data identifier
  allowed-breaking-changes.txt
  packages/aws-cdk-lib/aws-logs/lib/data-protection-policy.ts
  packages/aws-cdk-lib/awslint.json
Labels: p2, pr-linter/exempt-test, pr-linter/exempt-integ-test, beginning-contributor, pr-linter/exemption-requested

#27227 fix(sns-subscriptions): cannot add SqsSubscription when using an Sqs Construct from a different Constructs library
  packages/aws-cdk-lib/aws-sns-subscriptions/lib/sqs.ts
Labels: bug, p2, pr-linter/exempt-test, pr-linter/exempt-integ-test, beginning-contributor, pr-linter/exemption-requested

#27419 chore: fix the linter check to be aware of prerelease
  tools/@aws-cdk/pkglint/lib/rules.ts
Labels: p2, contribution/core

#27406 chore: upgrade cdk migrate version with bug fixes
  packages/@aws-cdk/cli-lib-alpha/THIRD_PARTY_LICENSES
  packages/aws-cdk/THIRD_PARTY_LICENSES
  packages/aws-cdk/package.json
  packages/aws-cdk/test/commands/migrate.test.ts
  packages/aws-cdk/test/commands/test-resources/stacks/S3Stack.java
  packages/aws-cdk/test/commands/test-resources/stacks/s3-stack.ts
  packages/aws-cdk/test/commands/test-resources/stacks/s3_stack.py
  yarn.lock
Labels: p2, contribution/core, pr-linter/cli-integ-tested, pr/needs-maintainer-review

#27429 chore: fix pipeline by finding another generated form
  tools/@aws-cdk/lazify/lib/index.ts
Labels: p2, contribution/core

#27435 chore: fix typo in issue template
  .github/ISSUE_TEMPLATE/bug-report.yml
Labels: p2, admired-contributor

#27325 feat(cli): CDK Migrate CLI command
  packages/aws-cdk/README.md
Labels: p2, pr/do-not-merge, contribution/core, pr-linter/exempt-test, pr-linter/exempt-integ-test

#27438 chore: fix monthly pr report title
  .github/workflows/repo-metrics.yml
Labels: p2, contribution/core

#27440 chore(merge-back): 2.100.0
  CHANGELOG.v2.alpha.md
  CHANGELOG.v2.md
  version.v2.json
Labels: p2, pr/needs-community-review, pr/no-squash, auto-approve

#27464 feat: update AWS Service Spec
  tools/@aws-cdk/spec2cdk/package.json
  yarn.lock
Labels: p2, dependencies, contribution/core, pr-linter/exempt-readme, pr-linter/exempt-test, auto-approve, pr-linter/exempt-integ-test

#27441 chore(synthetics): delete alpha module
  packages/@aws-cdk/aws-synthetics-alpha/.eslintrc.js
  packages/@aws-cdk/aws-synthetics-alpha/.gitignore
  packages/@aws-cdk/aws-synthetics-alpha/.npmignore
  packages/@aws-cdk/aws-synthetics-alpha/LICENSE
  packages/@aws-cdk/aws-synthetics-alpha/NOTICE
  packages/@aws-cdk/aws-synthetics-alpha/README.md
  packages/@aws-cdk/aws-synthetics-alpha/awslint.json
  packages/@aws-cdk/aws-synthetics-alpha/images/endpoint-example.png
  packages/@aws-cdk/aws-synthetics-alpha/images/ui-screenshot.png
  packages/@aws-cdk/aws-synthetics-alpha/jest.config.js
  packages/@aws-cdk/aws-synthetics-alpha/lib/canary.ts
  packages/@aws-cdk/aws-synthetics-alpha/lib/code.ts
  packages/@aws-cdk/aws-synthetics-alpha/lib/index.ts
  packages/@aws-cdk/aws-synthetics-alpha/lib/runtime.ts
  packages/@aws-cdk/aws-synthetics-alpha/lib/schedule.ts
  packages/@aws-cdk/aws-synthetics-alpha/package.json
  packages/@aws-cdk/aws-synthetics-alpha/rosetta/default.ts-fixture
  packages/@aws-cdk/aws-synthetics-alpha/scripts/airlift-custom-resource-handlers.sh
  packages/@aws-cdk/aws-synthetics-alpha/test/canaries/nodejs/node_modules/canary.js
  packages/@aws-cdk/aws-synthetics-alpha/test/canaries/nodejs/node_modules/folder/canary.js
  packages/@aws-cdk/aws-synthetics-alpha/test/canaries/python/canary.py
  packages/@aws-cdk/aws-synthetics-alpha/test/canary.test.ts
  packages/@aws-cdk/aws-synthetics-alpha/test/canary.zip
  packages/@aws-cdk/aws-synthetics-alpha/test/code.test.ts
  packages/@aws-cdk/aws-synthetics-alpha/test/integ.canary-auto-delete-lambda.js.snapshot/cdk-synthetics-canary-auto-delete.assets.json
  packages/@aws-cdk/aws-synthetics-alpha/test/integ.canary-auto-delete-lambda.js.snapshot/cdk-synthetics-canary-auto-delete.template.json
  packages/@aws-cdk/aws-synthetics-alpha/test/integ.canary-auto-delete-lambda.js.snapshot/cdk.out
  packages/@aws-cdk/aws-synthetics-alpha/test/integ.canary-auto-delete-lambda.js.snapshot/cdkintegsyntheticscanaryautodeleteDefaultTestDeployAssert94B79CED.assets.json
  packages/@aws-cdk/aws-synthetics-alpha/test/integ.canary-auto-delete-lambda.js.snapshot/cdkintegsyntheticscanaryautodeleteDefaultTestDeployAssert94B79CED.template.json
  packages/@aws-cdk/aws-synthetics-alpha/test/integ.canary-auto-delete-lambda.js.snapshot/integ.json
  packages/@aws-cdk/aws-synthetics-alpha/test/integ.canary-auto-delete-lambda.js.snapshot/manifest.json
  packages/@aws-cdk/aws-synthetics-alpha/test/integ.canary-auto-delete-lambda.js.snapshot/tree.json
  packages/@aws-cdk/aws-synthetics-alpha/test/integ.canary-auto-delete-lambda.ts
  packages/@aws-cdk/aws-synthetics-alpha/test/integ.canary.js.snapshot/IntegCanaryTestDefaultTestDeployAssert3AD5A094.assets.json
  packages/@aws-cdk/aws-synthetics-alpha/test/integ.canary.js.snapshot/IntegCanaryTestDefaultTestDeployAssert3AD5A094.template.json
  packages/@aws-cdk/aws-synthetics-alpha/test/integ.canary.js.snapshot/asset.086fe534b1e7545fbc662251685b8a7d91ab2061bbfe98d857b27478442487cb/index.js
  packages/@aws-cdk/aws-synthetics-alpha/test/integ.canary.js.snapshot/asset.294c96d7313c65f945a0d69f7b736dacbd169f3c6fe864b216c754371be2e195.bundle/index.js
  packages/@aws-cdk/aws-synthetics-alpha/test/integ.canary.js.snapshot/asset.2ec8ad9e91dcd6e7ad6a5c84ffc6c9c05c408aca3b26ceb2816d81043e6c4dc3/index.js
  packages/@aws-cdk/aws-synthetics-alpha/test/integ.canary.js.snapshot/asset.b1b777dcb79a2fa2790059927207d10bf5f4747d6dd1516e2780726d9d6fa820.zip
  packages/@aws-cdk/aws-synthetics-alpha/test/integ.canary.js.snapshot/asset.d6b51cbdd22d449b9e57c20ef9d0977e1cfbf06806f8008ce376101a2ad432a8/nodejs/node_modules/canary.js
  packages/@aws-cdk/aws-synthetics-alpha/test/integ.canary.js.snapshot/asset.d6b51cbdd22d449b9e57c20ef9d0977e1cfbf06806f8008ce376101a2ad432a8/nodejs/node_modules/folder/canary.js
  packages/@aws-cdk/aws-synthetics-alpha/test/integ.canary.js.snapshot/asset.d6b51cbdd22d449b9e57c20ef9d0977e1cfbf06806f8008ce376101a2ad432a8/python/canary.py
  packages/@aws-cdk/aws-synthetics-alpha/test/integ.canary.js.snapshot/canary-one.assets.json
  packages/@aws-cdk/aws-synthetics-alpha/test/integ.canary.js.snapshot/canary-one.template.json
  packages/@aws-cdk/aws-synthetics-alpha/test/integ.canary.js.snapshot/cdk.out
  packages/@aws-cdk/aws-synthetics-alpha/test/integ.canary.js.snapshot/integ.json
  packages/@aws-cdk/aws-synthetics-alpha/test/integ.canary.js.snapshot/manifest.json
  packages/@aws-cdk/aws-synthetics-alpha/test/integ.canary.js.snapshot/tree.json
  packages/@aws-cdk/aws-synthetics-alpha/test/integ.canary.ts
  packages/@aws-cdk/aws-synthetics-alpha/test/integ.vpc.js.snapshot/asset.b1b777dcb79a2fa2790059927207d10bf5f4747d6dd1516e2780726d9d6fa820.zip
  packages/@aws-cdk/aws-synthetics-alpha/test/integ.vpc.js.snapshot/canary-vpc.assets.json
  packages/@aws-cdk/aws-synthetics-alpha/test/integ.vpc.js.snapshot/canary-vpc.template.json
  packages/@aws-cdk/aws-synthetics-alpha/test/integ.vpc.js.snapshot/cdk.out
  packages/@aws-cdk/aws-synthetics-alpha/test/integ.vpc.js.snapshot/manifest.json
  packages/@aws-cdk/aws-synthetics-alpha/test/integ.vpc.js.snapshot/tree.json
  packages/@aws-cdk/aws-synthetics-alpha/test/integ.vpc.ts
  packages/@aws-cdk/aws-synthetics-alpha/test/metric.test.ts
  packages/@aws-cdk/aws-synthetics-alpha/test/schedule.test.ts
Labels: p2, contribution/core

#27422 feat(init-templates): update init templates to use the current LTS version of Java
  packages/aws-cdk/lib/init-templates/app/java/pom.xml
  packages/aws-cdk/lib/init-templates/sample-app/java/pom.xml
Labels: p2, contribution/core, pr-linter/exempt-readme, pr-linter/exempt-test, pr-linter/exempt-integ-test, pr-linter/cli-integ-tested

#27467 chore(issue-label-assign): aws-scheduler and aws-scheduler-targets
  .github/workflows/issue-label-assign.yml
Labels: p2, contribution/core

#27470 revert: "chore(synthetics): delete alpha module"
  packages/@aws-cdk/aws-synthetics-alpha/.eslintrc.js
  packages/@aws-cdk/aws-synthetics-alpha/.gitignore
  packages/@aws-cdk/aws-synthetics-alpha/.npmignore
  packages/@aws-cdk/aws-synthetics-alpha/LICENSE
  packages/@aws-cdk/aws-synthetics-alpha/NOTICE
  packages/@aws-cdk/aws-synthetics-alpha/README.md
  packages/@aws-cdk/aws-synthetics-alpha/awslint.json
  packages/@aws-cdk/aws-synthetics-alpha/images/endpoint-example.png
  packages/@aws-cdk/aws-synthetics-alpha/images/ui-screenshot.png
  packages/@aws-cdk/aws-synthetics-alpha/jest.config.js
  packages/@aws-cdk/aws-synthetics-alpha/lib/canary.ts
  packages/@aws-cdk/aws-synthetics-alpha/lib/code.ts
  packages/@aws-cdk/aws-synthetics-alpha/lib/index.ts
  packages/@aws-cdk/aws-synthetics-alpha/lib/runtime.ts
  packages/@aws-cdk/aws-synthetics-alpha/lib/schedule.ts
  packages/@aws-cdk/aws-synthetics-alpha/package.json
  packages/@aws-cdk/aws-synthetics-alpha/rosetta/default.ts-fixture
  packages/@aws-cdk/aws-synthetics-alpha/scripts/airlift-custom-resource-handlers.sh
  packages/@aws-cdk/aws-synthetics-alpha/test/canaries/nodejs/node_modules/canary.js
  packages/@aws-cdk/aws-synthetics-alpha/test/canaries/nodejs/node_modules/folder/canary.js
  packages/@aws-cdk/aws-synthetics-alpha/test/canaries/python/canary.py
  packages/@aws-cdk/aws-synthetics-alpha/test/canary.test.ts
  packages/@aws-cdk/aws-synthetics-alpha/test/canary.zip
  packages/@aws-cdk/aws-synthetics-alpha/test/code.test.ts
  packages/@aws-cdk/aws-synthetics-alpha/test/integ.canary-auto-delete-lambda.js.snapshot/cdk-synthetics-canary-auto-delete.assets.json
  packages/@aws-cdk/aws-synthetics-alpha/test/integ.canary-auto-delete-lambda.js.snapshot/cdk-synthetics-canary-auto-delete.template.json
  packages/@aws-cdk/aws-synthetics-alpha/test/integ.canary-auto-delete-lambda.js.snapshot/cdk.out
  packages/@aws-cdk/aws-synthetics-alpha/test/integ.canary-auto-delete-lambda.js.snapshot/cdkintegsyntheticscanaryautodeleteDefaultTestDeployAssert94B79CED.assets.json
  packages/@aws-cdk/aws-synthetics-alpha/test/integ.canary-auto-delete-lambda.js.snapshot/cdkintegsyntheticscanaryautodeleteDefaultTestDeployAssert94B79CED.template.json
  packages/@aws-cdk/aws-synthetics-alpha/test/integ.canary-auto-delete-lambda.js.snapshot/integ.json
  packages/@aws-cdk/aws-synthetics-alpha/test/integ.canary-auto-delete-lambda.js.snapshot/manifest.json
  packages/@aws-cdk/aws-synthetics-alpha/test/integ.canary-auto-delete-lambda.js.snapshot/tree.json
  packages/@aws-cdk/aws-synthetics-alpha/test/integ.canary-auto-delete-lambda.ts
  packages/@aws-cdk/aws-synthetics-alpha/test/integ.canary.js.snapshot/IntegCanaryTestDefaultTestDeployAssert3AD5A094.assets.json
  packages/@aws-cdk/aws-synthetics-alpha/test/integ.canary.js.snapshot/IntegCanaryTestDefaultTestDeployAssert3AD5A094.template.json
  packages/@aws-cdk/aws-synthetics-alpha/test/integ.canary.js.snapshot/asset.086fe534b1e7545fbc662251685b8a7d91ab2061bbfe98d857b27478442487cb/index.js
  packages/@aws-cdk/aws-synthetics-alpha/test/integ.canary.js.snapshot/asset.294c96d7313c65f945a0d69f7b736dacbd169f3c6fe864b216c754371be2e195.bundle/index.js
  packages/@aws-cdk/aws-synthetics-alpha/test/integ.canary.js.snapshot/asset.2ec8ad9e91dcd6e7ad6a5c84ffc6c9c05c408aca3b26ceb2816d81043e6c4dc3/index.js
  packages/@aws-cdk/aws-synthetics-alpha/test/integ.canary.js.snapshot/asset.b1b777dcb79a2fa2790059927207d10bf5f4747d6dd1516e2780726d9d6fa820.zip
  packages/@aws-cdk/aws-synthetics-alpha/test/integ.canary.js.snapshot/asset.d6b51cbdd22d449b9e57c20ef9d0977e1cfbf06806f8008ce376101a2ad432a8/nodejs/node_modules/canary.js
  packages/@aws-cdk/aws-synthetics-alpha/test/integ.canary.js.snapshot/asset.d6b51cbdd22d449b9e57c20ef9d0977e1cfbf06806f8008ce376101a2ad432a8/nodejs/node_modules/folder/canary.js
  packages/@aws-cdk/aws-synthetics-alpha/test/integ.canary.js.snapshot/asset.d6b51cbdd22d449b9e57c20ef9d0977e1cfbf06806f8008ce376101a2ad432a8/python/canary.py
  packages/@aws-cdk/aws-synthetics-alpha/test/integ.canary.js.snapshot/canary-one.assets.json
  packages/@aws-cdk/aws-synthetics-alpha/test/integ.canary.js.snapshot/canary-one.template.json
  packages/@aws-cdk/aws-synthetics-alpha/test/integ.canary.js.snapshot/cdk.out
  packages/@aws-cdk/aws-synthetics-alpha/test/integ.canary.js.snapshot/integ.json
  packages/@aws-cdk/aws-synthetics-alpha/test/integ.canary.js.snapshot/manifest.json
  packages/@aws-cdk/aws-synthetics-alpha/test/integ.canary.js.snapshot/tree.json
  packages/@aws-cdk/aws-synthetics-alpha/test/integ.canary.ts
  packages/@aws-cdk/aws-synthetics-alpha/test/integ.vpc.js.snapshot/asset.b1b777dcb79a2fa2790059927207d10bf5f4747d6dd1516e2780726d9d6fa820.zip
  packages/@aws-cdk/aws-synthetics-alpha/test/integ.vpc.js.snapshot/canary-vpc.assets.json
  packages/@aws-cdk/aws-synthetics-alpha/test/integ.vpc.js.snapshot/canary-vpc.template.json
  packages/@aws-cdk/aws-synthetics-alpha/test/integ.vpc.js.snapshot/cdk.out
  packages/@aws-cdk/aws-synthetics-alpha/test/integ.vpc.js.snapshot/manifest.json
  packages/@aws-cdk/aws-synthetics-alpha/test/integ.vpc.js.snapshot/tree.json
  packages/@aws-cdk/aws-synthetics-alpha/test/integ.vpc.ts
  packages/@aws-cdk/aws-synthetics-alpha/test/metric.test.ts
  packages/@aws-cdk/aws-synthetics-alpha/test/schedule.test.ts
Labels: p2, contribution/core, pr/needs-maintainer-review

#27471 chore(synthetics): deprecate aws-synthetics-alpha
  packages/@aws-cdk/aws-synthetics-alpha/README.md
  packages/@aws-cdk/aws-synthetics-alpha/package.json
Labels: p2, contribution/core, pr/needs-maintainer-review

#27472 fix(glue-alpha): prefix validation logic is incorrect
  packages/@aws-cdk/aws-glue-alpha/lib/job.ts
  packages/@aws-cdk/aws-glue-alpha/test/job.test.ts
Labels: bug, p2, effort/small, contribution/core, pr-linter/exempt-integ-test

#27442 feat(lambda-python-alpha): add without-urls option for poetry
  packages/@aws-cdk/aws-lambda-python-alpha/README.md
  packages/@aws-cdk/aws-lambda-python-alpha/lib/bundling.ts
  packages/@aws-cdk/aws-lambda-python-alpha/lib/packaging.ts
  packages/@aws-cdk/aws-lambda-python-alpha/lib/types.ts
  packages/@aws-cdk/aws-lambda-python-alpha/test/bundling.test.ts
  packages/@aws-cdk/aws-lambda-python-alpha/test/integ.function.poetry.js.snapshot/asset.73c20a669c041469f7fc3fc03d574b093b5b97e7c716f76c1e8117e6163e4dc4.bundle/index.js
  packages/@aws-cdk/aws-lambda-python-alpha/test/integ.function.poetry.js.snapshot/asset.f3de7fa69bbae9bbe9472b98f9b1b3626a9ee748b2fd5895278331be04efa56b.bundle/index.js
  packages/@aws-cdk/aws-lambda-python-alpha/test/integ.function.poetry.js.snapshot/cdk.out
  packages/@aws-cdk/aws-lambda-python-alpha/test/integ.function.poetry.js.snapshot/integ-lambda-python-poetry.assets.json
  packages/@aws-cdk/aws-lambda-python-alpha/test/integ.function.poetry.js.snapshot/integ-lambda-python-poetry.template.json
  packages/@aws-cdk/aws-lambda-python-alpha/test/integ.function.poetry.js.snapshot/integ.json
  packages/@aws-cdk/aws-lambda-python-alpha/test/integ.function.poetry.js.snapshot/manifest.json
  packages/@aws-cdk/aws-lambda-python-alpha/test/integ.function.poetry.js.snapshot/poetryDefaultTestDeployAssertE9C9CB8F.assets.json
  packages/@aws-cdk/aws-lambda-python-alpha/test/integ.function.poetry.js.snapshot/poetryDefaultTestDeployAssertE9C9CB8F.template.json
  packages/@aws-cdk/aws-lambda-python-alpha/test/integ.function.poetry.js.snapshot/tree.json
  packages/@aws-cdk/aws-lambda-python-alpha/test/integ.function.poetry.ts
  packages/@aws-cdk/aws-lambda-python-alpha/test/lambda-handler-poetry/basic.py
Labels: p2, feature-request, effort/small, valued-contributor, pr/needs-maintainer-review

#27380 fix(integ-tests): cannot make two or more identical assertions
  packages/@aws-cdk/integ-tests-alpha/lib/assertions/private/deploy-assert.ts
  packages/@aws-cdk/integ-tests-alpha/test/assertions/deploy-assert.test.ts
  packages/@aws-cdk/integ-tests-alpha/test/assertions/providers/integ.assertions.js.snapshot/Assertions.assets.json
  packages/@aws-cdk/integ-tests-alpha/test/assertions/providers/integ.assertions.js.snapshot/AssertionsTestDefaultTestDeployAssertDC0672BB.assets.json
  packages/@aws-cdk/integ-tests-alpha/test/assertions/providers/integ.assertions.js.snapshot/AssertionsTestDefaultTestDeployAssertDC0672BB.template.json
  packages/@aws-cdk/integ-tests-alpha/test/assertions/providers/integ.assertions.js.snapshot/cdk.out
  packages/@aws-cdk/integ-tests-alpha/test/assertions/providers/integ.assertions.js.snapshot/integ.json
  packages/@aws-cdk/integ-tests-alpha/test/assertions/providers/integ.assertions.js.snapshot/manifest.json
  packages/@aws-cdk/integ-tests-alpha/test/assertions/providers/integ.assertions.js.snapshot/tree.json
  packages/@aws-cdk/integ-tests-alpha/test/assertions/providers/integ.assertions.ts
Labels: bug, p2, effort/small, admired-contributor

#27463 fix(assertions): cannot use HTTP apis that do not return JSON
  packages/@aws-cdk/integ-tests-alpha/lib/assertions/providers/lambda-handler/http.ts
  packages/@aws-cdk/integ-tests-alpha/lib/assertions/providers/lambda-handler/types.ts
  packages/@aws-cdk/integ-tests-alpha/test/assertions/providers/lambda-handler/http.test.ts
Labels: p2, contribution/core, pr-linter/exempt-integ-test

#27287 feat(stepfunctions-tasks): add `ExecutionParameters` to `AthenaStartQueryExecution`
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/athena/integ.start-query-execution.js.snapshot/aws-stepfunctions-tasks-athena-start-query-execution-integ.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/athena/integ.start-query-execution.js.snapshot/aws-stepfunctions-tasks-athena-start-query-execution-integ.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/athena/integ.start-query-execution.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/athena/integ.start-query-execution.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/athena/integ.start-query-execution.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/athena/integ.start-query-execution.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/athena/integ.start-query-execution.ts
  packages/aws-cdk-lib/aws-stepfunctions-tasks/README.md
  packages/aws-cdk-lib/aws-stepfunctions-tasks/lib/athena/start-query-execution.ts
  packages/aws-cdk-lib/aws-stepfunctions-tasks/test/athena/start-query-execution.test.ts
Labels: p2, feature-request, effort/small, beginning-contributor, pr/needs-maintainer-review

#27306 feat(stepfunctions): adding custom state name prop
  packages/aws-cdk-lib/aws-stepfunctions/README.md
  packages/aws-cdk-lib/aws-stepfunctions/lib/state-machine.ts
  packages/aws-cdk-lib/aws-stepfunctions/lib/states/choice.ts
  packages/aws-cdk-lib/aws-stepfunctions/lib/states/fail.ts
  packages/aws-cdk-lib/aws-stepfunctions/lib/states/map.ts
  packages/aws-cdk-lib/aws-stepfunctions/lib/states/parallel.ts
  packages/aws-cdk-lib/aws-stepfunctions/lib/states/pass.ts
  packages/aws-cdk-lib/aws-stepfunctions/lib/states/state.ts
  packages/aws-cdk-lib/aws-stepfunctions/lib/states/succeed.ts
  packages/aws-cdk-lib/aws-stepfunctions/lib/states/task-base.ts
  packages/aws-cdk-lib/aws-stepfunctions/lib/states/task.ts
  packages/aws-cdk-lib/aws-stepfunctions/lib/states/wait.ts
  packages/aws-cdk-lib/aws-stepfunctions/test/custom-state.test.ts
  packages/aws-cdk-lib/aws-stepfunctions/test/fail.test.ts
  packages/aws-cdk-lib/aws-stepfunctions/test/map.test.ts
  packages/aws-cdk-lib/aws-stepfunctions/test/parallel.test.ts
  packages/aws-cdk-lib/aws-stepfunctions/test/state-machine-resources.test.ts
  packages/aws-cdk-lib/aws-stepfunctions/test/wait.test.ts
Labels: p1, feature-request, effort/small, contribution/core, pr-linter/exempt-integ-test

#27496 chore(CHANGELOG): synthetics feature was released in stable version
  CHANGELOG.v2.alpha.md
  CHANGELOG.v2.md
Labels: p2, contribution/core

#27425 feat(ec2): Add SubnetFilter for CIDR Range
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.vpc-filter-subnets.js.snapshot/VPCFilterSubnetsDefaultTestDeployAssertC02936E8.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.vpc-filter-subnets.js.snapshot/VPCFilterSubnetsTestStack.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.vpc-filter-subnets.js.snapshot/VPCFilterSubnetsTestStack.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.vpc-filter-subnets.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.vpc-filter-subnets.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.vpc-filter-subnets.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.vpc-filter-subnets.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.vpc-filter-subnets.ts
  packages/aws-cdk-lib/aws-ec2/README.md
  packages/aws-cdk-lib/aws-ec2/lib/subnet.ts
  packages/aws-cdk-lib/aws-ec2/test/vpc.test.ts
Labels: p2, feature-request, effort/small, beginning-contributor

#27369 fix(stepfunctions-tasks): SNS FIFO tasks does not support messageGroupId and messageDeduplicationId
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/sns/integ.publish.js.snapshot/aws-stepfunctions-tasks-sns-publish-integ.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/sns/integ.publish.js.snapshot/aws-stepfunctions-tasks-sns-publish-integ.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/sns/integ.publish.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/sns/integ.publish.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/sns/integ.publish.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/sns/integ.publish.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/sns/integ.publish.ts
  packages/aws-cdk-lib/aws-sns/lib/topic-base.ts
  packages/aws-cdk-lib/aws-sns/lib/topic.ts
  packages/aws-cdk-lib/aws-stepfunctions-tasks/lib/sns/publish.ts
  packages/aws-cdk-lib/aws-stepfunctions-tasks/test/sns/publish.test.ts
Labels: p2, feature-request, distinguished-contributor

#27042 chore(ec2): update Windows version enum list
  packages/aws-cdk-lib/aws-ec2/lib/windows-versions.ts
  packages/aws-cdk-lib/awslint.json
Labels: p2, feature-request, effort/small, valued-contributor, pr/needs-maintainer-review

#27166 chore(init-templates): allow renaming in templates for cdk migrate apps
  packages/aws-cdk/lib/init-templates/app/csharp/src/%name.PascalCased%/Program.template.cs
  packages/aws-cdk/lib/init.ts
  packages/aws-cdk/test/commands/migrate.test.ts
Labels: p2, contribution/core, pr-linter/cli-integ-tested

#27505 chore(synthetics-alpha): remove deprecated flag from package.json
  packages/@aws-cdk/aws-synthetics-alpha/package.json
Labels: p2, contribution/core

#27510 chore: upgrade version of cdk-generate-synthetic-examples
  scripts/run-rosetta.sh
Labels: p2, contribution/core

#27509 chore(migrate): add integ tests with app deployment
  packages/@aws-cdk-testing/cli-integ/lib/with-cdk-app.ts
  packages/@aws-cdk-testing/cli-integ/resources/templates/sqs-template.json
  packages/@aws-cdk-testing/cli-integ/tests/cli-integ-tests/cli.integtest.ts
Labels: p2, contribution/core, pr-linter/cli-integ-tested, pr/needs-maintainer-review

#27508 chore(aws-cdk-lib): Update adot lambda layers to the latest version
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda/test/integ.lambda-adot.js.snapshot/Stack1.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda/test/integ.lambda-adot.js.snapshot/Stack1.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda/test/integ.lambda-adot.js.snapshot/Stack2.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda/test/integ.lambda-adot.js.snapshot/Stack2.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda/test/integ.lambda-adot.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda/test/integ.lambda-adot.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda/test/integ.lambda-adot.ts
  packages/aws-cdk-lib/aws-lambda/lib/adot-layers.ts
  packages/aws-cdk-lib/aws-lambda/test/adot.test.ts
  packages/aws-cdk-lib/aws-lambda/test/function.test.ts
  packages/aws-cdk-lib/region-info/build-tools/fact-tables.ts
Labels: p2, beginning-contributor

#27358 revert: "fix(cli): cannot hotswap ECS task definitions containing certain intrinsics"
  packages/aws-cdk/lib/api/hotswap/common.ts
  packages/aws-cdk/lib/api/hotswap/ecs-services.ts
  packages/aws-cdk/test/api/hotswap/ecs-services-hotswap-deployments.test.ts
Labels: bug, p1, pr-linter/exempt-integ-test, admired-contributor, pr-linter/cli-integ-tested, pr-linter/exemption-requested, pr/needs-maintainer-review

#27539 chore(merge-back): 2.101.0
  CHANGELOG.v2.alpha.md
  CHANGELOG.v2.md
  version.v2.json
Labels: p2, pr/needs-community-review, pr/no-squash, auto-approve

#27557 feat: update AWS Service Spec
  tools/@aws-cdk/spec2cdk/package.json
  yarn.lock
Labels: p2, dependencies, contribution/core, pr-linter/exempt-readme, pr-linter/exempt-test, auto-approve, pr-linter/exempt-integ-test

#27550 docs(ec2): clarify error message for vpc sizing error
  packages/aws-cdk-lib/aws-ec2/lib/network-util.ts
Labels: bug, p2, admired-contributor

#27533 fix(custom-resources): custom resource provider can't exceed 1 hour
  packages/aws-cdk-lib/custom-resources/lib/provider-framework/provider.ts
Labels: bug, p1, effort/medium, contribution/core, pr-linter/exempt-test, pr-linter/exempt-integ-test, pr/needs-maintainer-review

#27568 chore: delete @aws-cdk/aws-synthetics-alpha
  packages/@aws-cdk/aws-synthetics-alpha/.eslintrc.js
  packages/@aws-cdk/aws-synthetics-alpha/.gitignore
  packages/@aws-cdk/aws-synthetics-alpha/.npmignore
  packages/@aws-cdk/aws-synthetics-alpha/LICENSE
  packages/@aws-cdk/aws-synthetics-alpha/NOTICE
  packages/@aws-cdk/aws-synthetics-alpha/README.md
  packages/@aws-cdk/aws-synthetics-alpha/awslint.json
  packages/@aws-cdk/aws-synthetics-alpha/images/endpoint-example.png
  packages/@aws-cdk/aws-synthetics-alpha/images/ui-screenshot.png
  packages/@aws-cdk/aws-synthetics-alpha/jest.config.js
  packages/@aws-cdk/aws-synthetics-alpha/lib/canary.ts
  packages/@aws-cdk/aws-synthetics-alpha/lib/code.ts
  packages/@aws-cdk/aws-synthetics-alpha/lib/index.ts
  packages/@aws-cdk/aws-synthetics-alpha/lib/runtime.ts
  packages/@aws-cdk/aws-synthetics-alpha/lib/schedule.ts
  packages/@aws-cdk/aws-synthetics-alpha/package.json
  packages/@aws-cdk/aws-synthetics-alpha/rosetta/default.ts-fixture
  packages/@aws-cdk/aws-synthetics-alpha/scripts/airlift-custom-resource-handlers.sh
  packages/@aws-cdk/aws-synthetics-alpha/test/canaries/nodejs/node_modules/canary.js
  packages/@aws-cdk/aws-synthetics-alpha/test/canaries/nodejs/node_modules/folder/canary.js
  packages/@aws-cdk/aws-synthetics-alpha/test/canaries/python/canary.py
  packages/@aws-cdk/aws-synthetics-alpha/test/canary.test.ts
  packages/@aws-cdk/aws-synthetics-alpha/test/canary.zip
  packages/@aws-cdk/aws-synthetics-alpha/test/code.test.ts
  packages/@aws-cdk/aws-synthetics-alpha/test/integ.canary-auto-delete-lambda.js.snapshot/cdk-synthetics-canary-auto-delete.assets.json
  packages/@aws-cdk/aws-synthetics-alpha/test/integ.canary-auto-delete-lambda.js.snapshot/cdk-synthetics-canary-auto-delete.template.json
  packages/@aws-cdk/aws-synthetics-alpha/test/integ.canary-auto-delete-lambda.js.snapshot/cdk.out
  packages/@aws-cdk/aws-synthetics-alpha/test/integ.canary-auto-delete-lambda.js.snapshot/cdkintegsyntheticscanaryautodeleteDefaultTestDeployAssert94B79CED.assets.json
  packages/@aws-cdk/aws-synthetics-alpha/test/integ.canary-auto-delete-lambda.js.snapshot/cdkintegsyntheticscanaryautodeleteDefaultTestDeployAssert94B79CED.template.json
  packages/@aws-cdk/aws-synthetics-alpha/test/integ.canary-auto-delete-lambda.js.snapshot/integ.json
  packages/@aws-cdk/aws-synthetics-alpha/test/integ.canary-auto-delete-lambda.js.snapshot/manifest.json
  packages/@aws-cdk/aws-synthetics-alpha/test/integ.canary-auto-delete-lambda.js.snapshot/tree.json
  packages/@aws-cdk/aws-synthetics-alpha/test/integ.canary-auto-delete-lambda.ts
  packages/@aws-cdk/aws-synthetics-alpha/test/integ.canary.js.snapshot/IntegCanaryTestDefaultTestDeployAssert3AD5A094.assets.json
  packages/@aws-cdk/aws-synthetics-alpha/test/integ.canary.js.snapshot/IntegCanaryTestDefaultTestDeployAssert3AD5A094.template.json
  packages/@aws-cdk/aws-synthetics-alpha/test/integ.canary.js.snapshot/asset.086fe534b1e7545fbc662251685b8a7d91ab2061bbfe98d857b27478442487cb/index.js
  packages/@aws-cdk/aws-synthetics-alpha/test/integ.canary.js.snapshot/asset.294c96d7313c65f945a0d69f7b736dacbd169f3c6fe864b216c754371be2e195.bundle/index.js
  packages/@aws-cdk/aws-synthetics-alpha/test/integ.canary.js.snapshot/asset.2ec8ad9e91dcd6e7ad6a5c84ffc6c9c05c408aca3b26ceb2816d81043e6c4dc3/index.js
  packages/@aws-cdk/aws-synthetics-alpha/test/integ.canary.js.snapshot/asset.b1b777dcb79a2fa2790059927207d10bf5f4747d6dd1516e2780726d9d6fa820.zip
  packages/@aws-cdk/aws-synthetics-alpha/test/integ.canary.js.snapshot/asset.d6b51cbdd22d449b9e57c20ef9d0977e1cfbf06806f8008ce376101a2ad432a8/nodejs/node_modules/canary.js
  packages/@aws-cdk/aws-synthetics-alpha/test/integ.canary.js.snapshot/asset.d6b51cbdd22d449b9e57c20ef9d0977e1cfbf06806f8008ce376101a2ad432a8/nodejs/node_modules/folder/canary.js
  packages/@aws-cdk/aws-synthetics-alpha/test/integ.canary.js.snapshot/asset.d6b51cbdd22d449b9e57c20ef9d0977e1cfbf06806f8008ce376101a2ad432a8/python/canary.py
  packages/@aws-cdk/aws-synthetics-alpha/test/integ.canary.js.snapshot/canary-one.assets.json
  packages/@aws-cdk/aws-synthetics-alpha/test/integ.canary.js.snapshot/canary-one.template.json
  packages/@aws-cdk/aws-synthetics-alpha/test/integ.canary.js.snapshot/cdk.out
  packages/@aws-cdk/aws-synthetics-alpha/test/integ.canary.js.snapshot/integ.json
  packages/@aws-cdk/aws-synthetics-alpha/test/integ.canary.js.snapshot/manifest.json
  packages/@aws-cdk/aws-synthetics-alpha/test/integ.canary.js.snapshot/tree.json
  packages/@aws-cdk/aws-synthetics-alpha/test/integ.canary.ts
  packages/@aws-cdk/aws-synthetics-alpha/test/integ.vpc.js.snapshot/asset.b1b777dcb79a2fa2790059927207d10bf5f4747d6dd1516e2780726d9d6fa820.zip
  packages/@aws-cdk/aws-synthetics-alpha/test/integ.vpc.js.snapshot/canary-vpc.assets.json
  packages/@aws-cdk/aws-synthetics-alpha/test/integ.vpc.js.snapshot/canary-vpc.template.json
  packages/@aws-cdk/aws-synthetics-alpha/test/integ.vpc.js.snapshot/cdk.out
  packages/@aws-cdk/aws-synthetics-alpha/test/integ.vpc.js.snapshot/manifest.json
  packages/@aws-cdk/aws-synthetics-alpha/test/integ.vpc.js.snapshot/tree.json
  packages/@aws-cdk/aws-synthetics-alpha/test/integ.vpc.ts
  packages/@aws-cdk/aws-synthetics-alpha/test/metric.test.ts
  packages/@aws-cdk/aws-synthetics-alpha/test/schedule.test.ts
Labels: p2, contribution/core

#27567 chore(merge-back): 2.101.1
  CHANGELOG.v2.alpha.md
  CHANGELOG.v2.md
  version.v2.json
Labels: p2, pr/needs-community-review, pr/no-squash, auto-approve

#27541 fix(eks): partition is hardcoded in ALB controller IAM policies
  packages/@aws-cdk-testing/framework-integ/test/aws-eks/test/integ.alb-controller.js.snapshot/asset.0f19e51d1e47290d7a33e0b67405e4722942dee4b92b9d29425fccf0d99017c3/apply/__init__.py
  packages/@aws-cdk-testing/framework-integ/test/aws-eks/test/integ.alb-controller.js.snapshot/asset.0f19e51d1e47290d7a33e0b67405e4722942dee4b92b9d29425fccf0d99017c3/get/__init__.py
  packages/@aws-cdk-testing/framework-integ/test/aws-eks/test/integ.alb-controller.js.snapshot/asset.0f19e51d1e47290d7a33e0b67405e4722942dee4b92b9d29425fccf0d99017c3/helm/__init__.py
  packages/@aws-cdk-testing/framework-integ/test/aws-eks/test/integ.alb-controller.js.snapshot/asset.0f19e51d1e47290d7a33e0b67405e4722942dee4b92b9d29425fccf0d99017c3/index.py
  packages/@aws-cdk-testing/framework-integ/test/aws-eks/test/integ.alb-controller.js.snapshot/asset.0f19e51d1e47290d7a33e0b67405e4722942dee4b92b9d29425fccf0d99017c3/patch/__init__.py
  packages/@aws-cdk-testing/framework-integ/test/aws-eks/test/integ.alb-controller.js.snapshot/asset.9efb96d8186dd343e3f84c72cfbcaaf16aa5579bbac0c02c60d4f19f4300d832/cluster.d.ts
  packages/@aws-cdk-testing/framework-integ/test/aws-eks/test/integ.alb-controller.js.snapshot/asset.9efb96d8186dd343e3f84c72cfbcaaf16aa5579bbac0c02c60d4f19f4300d832/cluster.js
  packages/@aws-cdk-testing/framework-integ/test/aws-eks/test/integ.alb-controller.js.snapshot/asset.9efb96d8186dd343e3f84c72cfbcaaf16aa5579bbac0c02c60d4f19f4300d832/cluster.ts
  packages/@aws-cdk-testing/framework-integ/test/aws-eks/test/integ.alb-controller.js.snapshot/asset.9efb96d8186dd343e3f84c72cfbcaaf16aa5579bbac0c02c60d4f19f4300d832/common.d.ts
  packages/@aws-cdk-testing/framework-integ/test/aws-eks/test/integ.alb-controller.js.snapshot/asset.9efb96d8186dd343e3f84c72cfbcaaf16aa5579bbac0c02c60d4f19f4300d832/common.js
  packages/@aws-cdk-testing/framework-integ/test/aws-eks/test/integ.alb-controller.js.snapshot/asset.9efb96d8186dd343e3f84c72cfbcaaf16aa5579bbac0c02c60d4f19f4300d832/common.ts
  packages/@aws-cdk-testing/framework-integ/test/aws-eks/test/integ.alb-controller.js.snapshot/asset.9efb96d8186dd343e3f84c72cfbcaaf16aa5579bbac0c02c60d4f19f4300d832/compareLogging.d.ts
  packages/@aws-cdk-testing/framework-integ/test/aws-eks/test/integ.alb-controller.js.snapshot/asset.9efb96d8186dd343e3f84c72cfbcaaf16aa5579bbac0c02c60d4f19f4300d832/compareLogging.js
  packages/@aws-cdk-testing/framework-integ/test/aws-eks/test/integ.alb-controller.js.snapshot/asset.9efb96d8186dd343e3f84c72cfbcaaf16aa5579bbac0c02c60d4f19f4300d832/compareLogging.ts
  packages/@aws-cdk-testing/framework-integ/test/aws-eks/test/integ.alb-controller.js.snapshot/asset.9efb96d8186dd343e3f84c72cfbcaaf16aa5579bbac0c02c60d4f19f4300d832/consts.d.ts
  packages/@aws-cdk-testing/framework-integ/test/aws-eks/test/integ.alb-controller.js.snapshot/asset.9efb96d8186dd343e3f84c72cfbcaaf16aa5579bbac0c02c60d4f19f4300d832/consts.js
  packages/@aws-cdk-testing/framework-integ/test/aws-eks/test/integ.alb-controller.js.snapshot/asset.9efb96d8186dd343e3f84c72cfbcaaf16aa5579bbac0c02c60d4f19f4300d832/consts.ts
  packages/@aws-cdk-testing/framework-integ/test/aws-eks/test/integ.alb-controller.js.snapshot/asset.9efb96d8186dd343e3f84c72cfbcaaf16aa5579bbac0c02c60d4f19f4300d832/fargate.d.ts
  packages/@aws-cdk-testing/framework-integ/test/aws-eks/test/integ.alb-controller.js.snapshot/asset.9efb96d8186dd343e3f84c72cfbcaaf16aa5579bbac0c02c60d4f19f4300d832/fargate.js
  packages/@aws-cdk-testing/framework-integ/test/aws-eks/test/integ.alb-controller.js.snapshot/asset.9efb96d8186dd343e3f84c72cfbcaaf16aa5579bbac0c02c60d4f19f4300d832/fargate.ts
  packages/@aws-cdk-testing/framework-integ/test/aws-eks/test/integ.alb-controller.js.snapshot/asset.9efb96d8186dd343e3f84c72cfbcaaf16aa5579bbac0c02c60d4f19f4300d832/index.d.ts
  packages/@aws-cdk-testing/framework-integ/test/aws-eks/test/integ.alb-controller.js.snapshot/asset.9efb96d8186dd343e3f84c72cfbcaaf16aa5579bbac0c02c60d4f19f4300d832/index.js
  packages/@aws-cdk-testing/framework-integ/test/aws-eks/test/integ.alb-controller.js.snapshot/asset.9efb96d8186dd343e3f84c72cfbcaaf16aa5579bbac0c02c60d4f19f4300d832/index.ts
  packages/@aws-cdk-testing/framework-integ/test/aws-eks/test/integ.alb-controller.js.snapshot/asset.b8426d60bacb99593213adedd37997b7d83efb99683ef98c85e692a82056e829/cluster.js
  packages/@aws-cdk-testing/framework-integ/test/aws-eks/test/integ.alb-controller.js.snapshot/asset.b8426d60bacb99593213adedd37997b7d83efb99683ef98c85e692a82056e829/common.js
  packages/@aws-cdk-testing/framework-integ/test/aws-eks/test/integ.alb-controller.js.snapshot/asset.b8426d60bacb99593213adedd37997b7d83efb99683ef98c85e692a82056e829/compareLogging.js
  packages/@aws-cdk-testing/framework-integ/test/aws-eks/test/integ.alb-controller.js.snapshot/asset.b8426d60bacb99593213adedd37997b7d83efb99683ef98c85e692a82056e829/consts.js
  packages/@aws-cdk-testing/framework-integ/test/aws-eks/test/integ.alb-controller.js.snapshot/asset.b8426d60bacb99593213adedd37997b7d83efb99683ef98c85e692a82056e829/fargate.js
  packages/@aws-cdk-testing/framework-integ/test/aws-eks/test/integ.alb-controller.js.snapshot/asset.b8426d60bacb99593213adedd37997b7d83efb99683ef98c85e692a82056e829/index.js
  packages/@aws-cdk-testing/framework-integ/test/aws-eks/test/integ.alb-controller.js.snapshot/aws-cdk-eks-cluster-alb-controller-test.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-eks/test/integ.alb-controller.js.snapshot/aws-cdk-eks-cluster-alb-controller-test.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-eks/test/integ.alb-controller.js.snapshot/awscdkeksclusteralbcontrollertestawscdkawseksClusterResourceProvider5DBBAFBB.nested.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-eks/test/integ.alb-controller.js.snapshot/awscdkeksclusteralbcontrollertestawscdkawseksKubectlProviderA1AC28D1.nested.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-eks/test/integ.alb-controller.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-eks/test/integ.alb-controller.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-eks/test/integ.eks-inference.js.snapshot/aws-cdk-eks-cluster-inference-test.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-eks/test/integ.eks-inference.js.snapshot/aws-cdk-eks-cluster-inference-test.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-eks/test/integ.eks-inference.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-eks/test/integ.eks-inference.js.snapshot/tree.json
  packages/aws-cdk-lib/aws-eks/lib/alb-controller.ts
  packages/aws-cdk-lib/aws-eks/test/alb-controller.test.ts
  packages/aws-cdk-lib/aws-eks/test/util.ts
Labels: bug, p2, effort/small, pr/needs-community-review, star-contributor, pr-linter/exemption-requested

#27544 feat(scheduler): metrics for all schedules
  packages/@aws-cdk/aws-scheduler-alpha/README.md
  packages/@aws-cdk/aws-scheduler-alpha/lib/schedule.ts
  packages/@aws-cdk/aws-scheduler-alpha/test/integ.schedule.js.snapshot/aws-cdk-scheduler-schedule.assets.json
  packages/@aws-cdk/aws-scheduler-alpha/test/integ.schedule.js.snapshot/aws-cdk-scheduler-schedule.template.json
  packages/@aws-cdk/aws-scheduler-alpha/test/integ.schedule.js.snapshot/manifest.json
  packages/@aws-cdk/aws-scheduler-alpha/test/integ.schedule.js.snapshot/tree.json
  packages/@aws-cdk/aws-scheduler-alpha/test/integ.schedule.ts
  packages/@aws-cdk/aws-scheduler-alpha/test/schedule.test.ts
Labels: p2, repeat-contributor

#27570 docs(secretsmanager): doc when automaticallyAfter for RotationSchedule is 0 is wrong
  packages/aws-cdk-lib/aws-secretsmanager/lib/rotation-schedule.ts
Labels: p2, admired-contributor

#27596 chore: add sinon dep
  packages/@aws-cdk-testing/cli-integ/package.json
Labels: p2, contribution/core

#27516 refactor(elasticloadbalancingv2-targets): update AlbTarget constructor
  packages/aws-cdk-lib/aws-elasticloadbalancingv2-targets/lib/alb-target.ts
Labels: p1, feature-request, effort/small, beginning-contributor

#27588 chore(appsync): link to the SourceApiAssociationMergeOperation construct in the AppSync utils package
  packages/aws-cdk-lib/aws-appsync/README.md
Labels: p2, beginning-contributor

#27592 feat(secretsmanager): validate maximum value of automaticallyAfter in RotationSchedule
  packages/aws-cdk-lib/aws-secretsmanager/lib/rotation-schedule.ts
  packages/aws-cdk-lib/aws-secretsmanager/test/rotation-schedule.test.ts
Labels: p2, pr-linter/exempt-readme, pr-linter/exempt-integ-test, admired-contributor

#27601 chore(merge-back): 2.102.0
  CHANGELOG.v2.alpha.md
  CHANGELOG.v2.md
  version.v2.json
Labels: p2, pr/needs-community-review, pr/no-squash, auto-approve

#27292 feat(cli): support `Fn::ImportValue` intrinsic function for hotswap deployments
  packages/@aws-cdk-testing/cli-integ/resources/cdk-apps/app/app.js
  packages/@aws-cdk-testing/cli-integ/tests/cli-integ-tests/cli.integtest.ts
  packages/aws-cdk/README.md
  packages/aws-cdk/lib/api/evaluate-cloudformation-template.ts
  packages/aws-cdk/lib/api/hotswap-deployments.ts
  packages/aws-cdk/test/api/evaluate-cloudformation-template.test.ts
  packages/aws-cdk/test/api/hotswap/hotswap-deployments.test.ts
  packages/aws-cdk/test/api/lazy-lookup-export.test.ts
Labels: p1, feature-request, effort/medium, pr-linter/exempt-integ-test, beginning-contributor, pr-linter/cli-integ-tested, pr-linter/do-not-close

#27612 feat(opensearch): OpenSearch 2.9 engine version
  packages/@aws-cdk-testing/framework-integ/test/aws-opensearchservice/test/integ.opensearch.min.js.snapshot/IntegDefaultTestDeployAssert4E6713E1.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-opensearchservice/test/integ.opensearch.min.js.snapshot/cdk-integ-opensearch.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-opensearchservice/test/integ.opensearch.min.js.snapshot/cdk-integ-opensearch.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-opensearchservice/test/integ.opensearch.min.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-opensearchservice/test/integ.opensearch.min.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-opensearchservice/test/integ.opensearch.min.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-opensearchservice/test/integ.opensearch.min.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-opensearchservice/test/integ.opensearch.min.ts
  packages/aws-cdk-lib/aws-opensearchservice/lib/version.ts
  packages/aws-cdk-lib/aws-opensearchservice/test/domain.test.ts
Labels: p2, feature-request, effort/small, pr-linter/exempt-readme, admired-contributor

#27611 feat(ec2): support for c7i and r7iz instance types in aws-ec2
  packages/aws-cdk-lib/aws-ec2/lib/instance-types.ts
Labels: p2, pr-linter/exempt-readme, pr-linter/exempt-test, pr-linter/exempt-integ-test, beginning-contributor

#27617 chore(prlint): add rule to reject pr contribution from main branch
  tools/@aws-cdk/prlint/lint.ts
  tools/@aws-cdk/prlint/test/lint.test.ts
Labels: p2, contribution/core, pr/needs-maintainer-review

#27621 chore(logs): remove hardcoded account id and region from snapshot
  packages/@aws-cdk-testing/framework-integ/test/aws-logs/test/integ.subscriptionfilter.js.snapshot/aws-cdk-subscriptionfilter-integ.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-logs/test/integ.subscriptionfilter.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-logs/test/integ.subscriptionfilter.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-logs/test/integ.subscriptionfilter.js.snapshot/integtestDefaultTestDeployAssert24D5C536.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-logs/test/integ.subscriptionfilter.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-logs/test/integ.subscriptionfilter.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-logs/test/integ.subscriptionfilter.ts
Labels: p2, admired-contributor

#27609 feat(schedule-alpha): support customer managed KMS keys
  packages/@aws-cdk/aws-scheduler-alpha/README.md
  packages/@aws-cdk/aws-scheduler-alpha/lib/schedule.ts
  packages/@aws-cdk/aws-scheduler-alpha/test/integ.schedule.js.snapshot/aws-cdk-scheduler-schedule.assets.json
  packages/@aws-cdk/aws-scheduler-alpha/test/integ.schedule.js.snapshot/aws-cdk-scheduler-schedule.template.json
  packages/@aws-cdk/aws-scheduler-alpha/test/integ.schedule.js.snapshot/cdk.out
  packages/@aws-cdk/aws-scheduler-alpha/test/integ.schedule.js.snapshot/integ.json
  packages/@aws-cdk/aws-scheduler-alpha/test/integ.schedule.js.snapshot/integtestscheduleDefaultTestDeployAssert24CB3896.assets.json
  packages/@aws-cdk/aws-scheduler-alpha/test/integ.schedule.js.snapshot/manifest.json
  packages/@aws-cdk/aws-scheduler-alpha/test/integ.schedule.js.snapshot/tree.json
  packages/@aws-cdk/aws-scheduler-alpha/test/integ.schedule.ts
  packages/@aws-cdk/aws-scheduler-alpha/test/schedule.test.ts
Labels: p2, feature-request, effort/small, distinguished-contributor

#27625 docs: clarify pull request source branch a little more
  CONTRIBUTING.md
Labels: p2, contribution/core

#27627 chore: auto close pr if opened from fork's main branch
  tools/@aws-cdk/prlint/lint.ts
  tools/@aws-cdk/prlint/test/lint.test.ts
Labels: p2, contribution/core

#27565 feat(synthetics): syn-python-selenium-2.0 runtime
  packages/@aws-cdk-testing/framework-integ/test/aws-synthetics/test/integ.canary.js.snapshot/IntegCanaryTestDefaultTestDeployAssert3AD5A094.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-synthetics/test/integ.canary.js.snapshot/IntegCanaryTestDefaultTestDeployAssert3AD5A094.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-synthetics/test/integ.canary.js.snapshot/asset.086fe534b1e7545fbc662251685b8a7d91ab2061bbfe98d857b27478442487cb/index.js
  packages/@aws-cdk-testing/framework-integ/test/aws-synthetics/test/integ.canary.js.snapshot/asset.2ec8ad9e91dcd6e7ad6a5c84ffc6c9c05c408aca3b26ceb2816d81043e6c4dc3/index.js
  packages/@aws-cdk-testing/framework-integ/test/aws-synthetics/test/integ.canary.js.snapshot/asset.f07f565d85d232ca058a2fc39ccc2c55ab6950e96ba8dd9a09dafe803dd1247b.bundle/index.js
  packages/@aws-cdk-testing/framework-integ/test/aws-synthetics/test/integ.canary.js.snapshot/canary-one.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-synthetics/test/integ.canary.js.snapshot/canary-one.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-synthetics/test/integ.canary.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-synthetics/test/integ.canary.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-synthetics/test/integ.canary.ts
  packages/aws-cdk-lib/aws-synthetics/lib/runtime.ts
  packages/aws-cdk-lib/aws-synthetics/test/canary.test.ts
  packages/aws-cdk-lib/aws-synthetics/test/code.test.ts
Labels: p2, feature-request, effort/small, pr-linter/exempt-readme, pr-linter/exempt-test, beginning-contributor

#27632 docs: update INTEGRATION_TESTS.md
  INTEGRATION_TESTS.md
Labels: p2, contribution/core

#27630 docs(pipelines): update README
  packages/aws-cdk-lib/pipelines/README.md
Labels: p2, contribution/core

#27468 fix(ec2): naming collisions when using `ec2.InitFile.fromAsset()` on multiple instances in the same stack
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.instance-init-multiple.js.snapshot/asset.04c44be8722f4360fe0830af22298ad0870480310d7bd6eedbbd2391aecf59a8
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.instance-init-multiple.js.snapshot/asset.1be0bac6581864b510bdbf0a114f1d3429244758da7657cc365f73d371fe70ed/__entrypoint__.js
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.instance-init-multiple.js.snapshot/asset.1be0bac6581864b510bdbf0a114f1d3429244758da7657cc365f73d371fe70ed/index.js
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.instance-init-multiple.js.snapshot/asset.b9ca21e9930115b91ab7e6877bec3bc97b410a6d41fd58816b56aba6db2643bd
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.instance-init-multiple.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.instance-init-multiple.js.snapshot/instancetestDefaultTestDeployAssert5516EAF1.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.instance-init-multiple.js.snapshot/instancetestDefaultTestDeployAssert5516EAF1.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.instance-init-multiple.js.snapshot/integ-ec2-multiple-instances-in-stack.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.instance-init-multiple.js.snapshot/integ-ec2-multiple-instances-in-stack.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.instance-init-multiple.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.instance-init-multiple.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.instance-init-multiple.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.instance-init-multiple.ts
  packages/aws-cdk-lib/aws-ec2/lib/cfn-init-elements.ts
  packages/aws-cdk-lib/aws-ec2/test/cfn-init-element.test.ts
  packages/aws-cdk-lib/aws-ec2/test/init-configs/configFileForFirstInstance.json
  packages/aws-cdk-lib/aws-ec2/test/init-configs/configFileForSecondInstance.json
Labels: bug, p1, effort/small, contribution/core, pr/needs-maintainer-review

#27652 chore: fix the use of mixed dep/devdeps
  packages/@aws-cdk/app-staging-synthesizer-alpha/package.json
  packages/@aws-cdk/aws-appconfig-alpha/package.json
  packages/@aws-cdk/cx-api/package.json
  packages/@aws-cdk/example-construct-library/package.json
  packages/aws-cdk-lib/package.json
  packages/aws-cdk/package.json
  tools/@aws-cdk/cdk-build-tools/config/eslintrc.js
  tools/@aws-cdk/cfn2ts/package.json
  tools/@aws-cdk/pkglint/lib/rules.ts
Labels: p2, contribution/core

#27506 fix(region-info): facts only returned from constant region list
  packages/aws-cdk-lib/region-info/lib/fact.ts
  packages/aws-cdk-lib/region-info/test/fact.test.ts
  packages/aws-cdk-lib/region-info/test/region-info.test.ts
Labels: bug, p2, effort/small, pr-linter/exempt-integ-test, admired-contributor, pr-linter/exemption-requested

#27559 fix(cdk): Add AppSync:Api_Key as hot swappable and fix a bug with AppSync.function
  packages/aws-cdk/lib/api/hotswap-deployments.ts
  packages/aws-cdk/lib/api/hotswap/appsync-mapping-templates.ts
  packages/aws-cdk/test/api/hotswap/appsync-mapping-templates-hotswap-deployments.test.ts
Labels: p2, pr-linter/exempt-integ-test, repeat-contributor, pr-linter/cli-integ-tested

#27639 feat(ec2): support for i4g instance types in aws-ec2
  packages/aws-cdk-lib/aws-ec2/lib/instance-types.ts
Labels: p2, feature-request, effort/small, pr-linter/exempt-readme, pr-linter/exempt-test, pr-linter/exempt-integ-test, admired-contributor

#27635 chore(stepfunctions-tasks): validate cases of action and parameters in CallAwsService
  packages/aws-cdk-lib/aws-stepfunctions-tasks/lib/aws-sdk/call-aws-service.ts
  packages/aws-cdk-lib/aws-stepfunctions-tasks/test/aws-sdk/call-aws-service.test.ts
Labels: p2, admired-contributor

#27623 fix(stepfunctions-tasks): cloudwatchlogs service generates wrong action in role policy
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/aws-sdk/integ.call-aws-service-logs.js.snapshot/IntegTestDefaultTestDeployAssertE3E7D2A4.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/aws-sdk/integ.call-aws-service-logs.js.snapshot/IntegTestDefaultTestDeployAssertE3E7D2A4.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/aws-sdk/integ.call-aws-service-logs.js.snapshot/asset.211bd8c514e07e047addb5c06afe6f8e85ce4e0b19b64ad78b28e84fc09aafe7.bundle/index.js
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/aws-sdk/integ.call-aws-service-logs.js.snapshot/aws-stepfunctions-tasks-call-aws-service-logs-integ.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/aws-sdk/integ.call-aws-service-logs.js.snapshot/aws-stepfunctions-tasks-call-aws-service-logs-integ.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/aws-sdk/integ.call-aws-service-logs.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/aws-sdk/integ.call-aws-service-logs.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/aws-sdk/integ.call-aws-service-logs.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/aws-sdk/integ.call-aws-service-logs.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/aws-sdk/integ.call-aws-service-logs.ts
  packages/aws-cdk-lib/aws-stepfunctions-tasks/lib/aws-sdk/call-aws-service.ts
  packages/aws-cdk-lib/aws-stepfunctions-tasks/test/aws-sdk/call-aws-service.test.ts
Labels: bug, p2, admired-contributor

#27672 chore(region-info): Adding missing regions for kinesisfirehose
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda/test/integ.bundling.docker-opts.js.snapshot/DockerOptsBundlingDefaultTestDeployAssert72BE28F7.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda/test/integ.bundling.docker-opts.js.snapshot/DockerOptsBundlingDefaultTestDeployAssert72BE28F7.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda/test/integ.bundling.docker-opts.js.snapshot/asset.d69f83e949b9c49809604e7bcd3a868d44f04f936029b55662aa14982d9bd44b.bundle/index.js
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda/test/integ.bundling.docker-opts.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda/test/integ.bundling.docker-opts.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda/test/integ.bundling.js.snapshot/BundlingDefaultTestDeployAssertAACA0CAF.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda/test/integ.bundling.js.snapshot/BundlingDefaultTestDeployAssertAACA0CAF.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda/test/integ.bundling.js.snapshot/asset.d69f83e949b9c49809604e7bcd3a868d44f04f936029b55662aa14982d9bd44b.bundle/index.js
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda/test/integ.bundling.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda/test/integ.bundling.js.snapshot/tree.json
  packages/@aws-cdk/aws-iot-actions-alpha/test/kinesis-firehose/integ.firehose-put-record-action.js.snapshot/manifest.json
  packages/@aws-cdk/aws-iot-actions-alpha/test/kinesis-firehose/integ.firehose-put-record-action.js.snapshot/test-stack.assets.json
  packages/@aws-cdk/aws-iot-actions-alpha/test/kinesis-firehose/integ.firehose-put-record-action.js.snapshot/test-stack.template.json
  packages/@aws-cdk/aws-iot-actions-alpha/test/kinesis-firehose/integ.firehose-put-record-action.js.snapshot/tree.json
  packages/@aws-cdk/aws-kinesisfirehose-alpha/test/integ.delivery-stream.js.snapshot/aws-cdk-firehose-delivery-stream.assets.json
  packages/@aws-cdk/aws-kinesisfirehose-alpha/test/integ.delivery-stream.js.snapshot/aws-cdk-firehose-delivery-stream.template.json
  packages/@aws-cdk/aws-kinesisfirehose-alpha/test/integ.delivery-stream.js.snapshot/manifest.json
  packages/@aws-cdk/aws-kinesisfirehose-alpha/test/integ.delivery-stream.js.snapshot/tree.json
  packages/@aws-cdk/aws-kinesisfirehose-alpha/test/integ.delivery-stream.source-stream.js.snapshot/aws-cdk-firehose-delivery-stream-source-stream.assets.json
  packages/@aws-cdk/aws-kinesisfirehose-alpha/test/integ.delivery-stream.source-stream.js.snapshot/aws-cdk-firehose-delivery-stream-source-stream.template.json
  packages/@aws-cdk/aws-kinesisfirehose-alpha/test/integ.delivery-stream.source-stream.js.snapshot/manifest.json
  packages/@aws-cdk/aws-kinesisfirehose-alpha/test/integ.delivery-stream.source-stream.js.snapshot/tree.json
  packages/@aws-cdk/aws-kinesisfirehose-destinations-alpha/test/integ.s3-bucket.lit.js.snapshot/aws-cdk-firehose-delivery-stream-s3-all-properties.assets.json
  packages/@aws-cdk/aws-kinesisfirehose-destinations-alpha/test/integ.s3-bucket.lit.js.snapshot/aws-cdk-firehose-delivery-stream-s3-all-properties.template.json
  packages/@aws-cdk/aws-kinesisfirehose-destinations-alpha/test/integ.s3-bucket.lit.js.snapshot/manifest.json
  packages/aws-cdk-lib/region-info/build-tools/fact-tables.ts
Labels: bug, p0, contribution/core

#27650 feat: update AWS Service Spec
  tools/@aws-cdk/spec2cdk/package.json
  yarn.lock
Labels: p2, dependencies, contribution/core, pr-linter/exempt-readme, pr-linter/exempt-test, auto-approve, pr-linter/exempt-integ-test

#27675 chore(spec2cdk): support local, temporary service files
  tools/@aws-cdk/spec2cdk/README.md
  tools/@aws-cdk/spec2cdk/lib/generate.ts
  tools/@aws-cdk/spec2cdk/package.json
  tools/@aws-cdk/spec2cdk/temporary-schemas/us-east-1/.keep
  yarn.lock
Labels: p2, contribution/core

#27677 chore(release): 2.102.1
  CHANGELOG.v2.alpha.md
  CHANGELOG.v2.md
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda/test/integ.bundling.docker-opts.js.snapshot/DockerOptsBundlingDefaultTestDeployAssert72BE28F7.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda/test/integ.bundling.docker-opts.js.snapshot/DockerOptsBundlingDefaultTestDeployAssert72BE28F7.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda/test/integ.bundling.docker-opts.js.snapshot/asset.d69f83e949b9c49809604e7bcd3a868d44f04f936029b55662aa14982d9bd44b.bundle/index.js
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda/test/integ.bundling.docker-opts.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda/test/integ.bundling.docker-opts.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda/test/integ.bundling.js.snapshot/BundlingDefaultTestDeployAssertAACA0CAF.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda/test/integ.bundling.js.snapshot/BundlingDefaultTestDeployAssertAACA0CAF.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda/test/integ.bundling.js.snapshot/asset.d69f83e949b9c49809604e7bcd3a868d44f04f936029b55662aa14982d9bd44b.bundle/index.js
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda/test/integ.bundling.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda/test/integ.bundling.js.snapshot/tree.json
  packages/@aws-cdk/aws-iot-actions-alpha/test/kinesis-firehose/integ.firehose-put-record-action.js.snapshot/manifest.json
  packages/@aws-cdk/aws-iot-actions-alpha/test/kinesis-firehose/integ.firehose-put-record-action.js.snapshot/test-stack.assets.json
  packages/@aws-cdk/aws-iot-actions-alpha/test/kinesis-firehose/integ.firehose-put-record-action.js.snapshot/test-stack.template.json
  packages/@aws-cdk/aws-iot-actions-alpha/test/kinesis-firehose/integ.firehose-put-record-action.js.snapshot/tree.json
  packages/@aws-cdk/aws-kinesisfirehose-alpha/test/integ.delivery-stream.js.snapshot/aws-cdk-firehose-delivery-stream.assets.json
  packages/@aws-cdk/aws-kinesisfirehose-alpha/test/integ.delivery-stream.js.snapshot/aws-cdk-firehose-delivery-stream.template.json
  packages/@aws-cdk/aws-kinesisfirehose-alpha/test/integ.delivery-stream.js.snapshot/manifest.json
  packages/@aws-cdk/aws-kinesisfirehose-alpha/test/integ.delivery-stream.js.snapshot/tree.json
  packages/@aws-cdk/aws-kinesisfirehose-alpha/test/integ.delivery-stream.source-stream.js.snapshot/aws-cdk-firehose-delivery-stream-source-stream.assets.json
  packages/@aws-cdk/aws-kinesisfirehose-alpha/test/integ.delivery-stream.source-stream.js.snapshot/aws-cdk-firehose-delivery-stream-source-stream.template.json
  packages/@aws-cdk/aws-kinesisfirehose-alpha/test/integ.delivery-stream.source-stream.js.snapshot/manifest.json
  packages/@aws-cdk/aws-kinesisfirehose-alpha/test/integ.delivery-stream.source-stream.js.snapshot/tree.json
  packages/@aws-cdk/aws-kinesisfirehose-destinations-alpha/test/integ.s3-bucket.lit.js.snapshot/aws-cdk-firehose-delivery-stream-s3-all-properties.assets.json
  packages/@aws-cdk/aws-kinesisfirehose-destinations-alpha/test/integ.s3-bucket.lit.js.snapshot/aws-cdk-firehose-delivery-stream-s3-all-properties.template.json
  packages/@aws-cdk/aws-kinesisfirehose-destinations-alpha/test/integ.s3-bucket.lit.js.snapshot/manifest.json
  packages/aws-cdk-lib/region-info/build-tools/fact-tables.ts
  version.v2.json
Labels: p2, contribution/core, pr/no-squash, pr/needs-maintainer-review

#27679 chore(appsync): Tidy up README for Merged APIs
  packages/aws-cdk-lib/aws-appsync/README.md
Labels: p2, beginning-contributor

#27682 chore(merge-back): 2.102.1
  CHANGELOG.v2.alpha.md
  CHANGELOG.v2.md
  version.v2.json
Labels: p2, pr/needs-community-review, pr/no-squash, auto-approve

#27685 chore(merge-back): 2.103.0
  CHANGELOG.v2.alpha.md
  CHANGELOG.v2.md
  version.v2.json
Labels: p2, pr/needs-community-review, pr/no-squash, auto-approve

#27645 feat(apigateway): add useDefaultMethodResponses property for StepFunctionsIntegrations
  packages/@aws-cdk-testing/framework-integ/test/aws-apigateway/test/integ.stepfunctions-api-without-default-method-responses.js.snapshot/SfnRestApiWithoutDefaultMethodResponses.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-apigateway/test/integ.stepfunctions-api-without-default-method-responses.js.snapshot/SfnRestApiWithoutDefaultMethodResponses.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-apigateway/test/integ.stepfunctions-api-without-default-method-responses.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-apigateway/test/integ.stepfunctions-api-without-default-method-responses.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-apigateway/test/integ.stepfunctions-api-without-default-method-responses.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-apigateway/test/integ.stepfunctions-api-without-default-method-responses.js.snapshot/sfnrestapiwithoutdefaultmethodresponsesDefaultTestDeployAssert7E2275C8.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-apigateway/test/integ.stepfunctions-api-without-default-method-responses.js.snapshot/sfnrestapiwithoutdefaultmethodresponsesDefaultTestDeployAssert7E2275C8.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-apigateway/test/integ.stepfunctions-api-without-default-method-responses.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-apigateway/test/integ.stepfunctions-api-without-default-method-responses.ts
  packages/@aws-cdk-testing/framework-integ/test/aws-apigateway/test/integ.stepfunctions-startexecution-without-default-method-responses.js.snapshot/aws-cdk-aws-apigateway-stepfunctions-startexecution-without-default-method-responses.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-apigateway/test/integ.stepfunctions-startexecution-without-default-method-responses.js.snapshot/aws-cdk-aws-apigateway-stepfunctions-startexecution-without-default-method-responses.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-apigateway/test/integ.stepfunctions-startexecution-without-default-method-responses.js.snapshot/awsapigatewaystepfunctionsstartexecutionwithoutdefaultmethodresponsesDefaultTestDeployAssert8B46AA47.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-apigateway/test/integ.stepfunctions-startexecution-without-default-method-responses.js.snapshot/awsapigatewaystepfunctionsstartexecutionwithoutdefaultmethodresponsesDefaultTestDeployAssert8B46AA47.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-apigateway/test/integ.stepfunctions-startexecution-without-default-method-responses.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-apigateway/test/integ.stepfunctions-startexecution-without-default-method-responses.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-apigateway/test/integ.stepfunctions-startexecution-without-default-method-responses.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-apigateway/test/integ.stepfunctions-startexecution-without-default-method-responses.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-apigateway/test/integ.stepfunctions-startexecution-without-default-method-responses.ts
  packages/aws-cdk-lib/aws-apigateway/README.md
  packages/aws-cdk-lib/aws-apigateway/lib/integrations/stepfunctions.ts
  packages/aws-cdk-lib/aws-apigateway/lib/stepfunctions-api.ts
  packages/aws-cdk-lib/aws-apigateway/test/integrations/stepfunctions.test.ts
  packages/aws-cdk-lib/aws-apigateway/test/stepfunctions-api.test.ts
Labels: p2, feature-request, effort/medium, admired-contributor

#27619 fix(apigateway): validation for path parts does not allow creation of resources beginning with dollar sign
  packages/@aws-cdk-testing/framework-integ/test/aws-apigateway/test/integ.restapi.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-apigateway/test/integ.restapi.js.snapshot/test-apigateway-restapi.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-apigateway/test/integ.restapi.js.snapshot/test-apigateway-restapi.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-apigateway/test/integ.restapi.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-apigateway/test/integ.restapi.ts
  packages/aws-cdk-lib/aws-apigateway/lib/resource.ts
  packages/aws-cdk-lib/aws-apigateway/test/resource.test.ts
Labels: bug, p2, effort/small, beginning-contributor

#27648 fix(autoscaling): AutoScalingGroup.requireImdsv2 throws error with LaunchTemplates
  packages/@aws-cdk-testing/framework-integ/test/aws-autoscaling/test/integ.asg-lt.js.snapshot/aws-cdk-asg-integ.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-autoscaling/test/integ.asg-lt.js.snapshot/aws-cdk-asg-integ.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-autoscaling/test/integ.asg-lt.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-autoscaling/test/integ.asg-lt.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-autoscaling/test/integ.asg-lt.ts
  packages/aws-cdk-lib/aws-autoscaling/lib/aspects/require-imdsv2-aspect.ts
  packages/aws-cdk-lib/aws-autoscaling/test/aspects/require-imdsv2-aspect.test.ts
  packages/aws-cdk-lib/aws-autoscaling/test/auto-scaling-group.test.ts
Labels: bug, p1, effort/small, admired-contributor

#27680 feat(appconfig): support for CfnMonitorsProperty in environments
  packages/@aws-cdk/aws-appconfig-alpha/README.md
  packages/@aws-cdk/aws-appconfig-alpha/lib/configuration.ts
  packages/@aws-cdk/aws-appconfig-alpha/lib/environment.ts
  packages/@aws-cdk/aws-appconfig-alpha/lib/extension.ts
  packages/@aws-cdk/aws-appconfig-alpha/test/environment.test.ts
  packages/@aws-cdk/aws-appconfig-alpha/test/integ.environment.js.snapshot/aws-appconfig-environment.assets.json
  packages/@aws-cdk/aws-appconfig-alpha/test/integ.environment.js.snapshot/aws-appconfig-environment.template.json
  packages/@aws-cdk/aws-appconfig-alpha/test/integ.environment.js.snapshot/manifest.json
  packages/@aws-cdk/aws-appconfig-alpha/test/integ.environment.js.snapshot/tree.json
  packages/@aws-cdk/aws-appconfig-alpha/test/integ.environment.ts
Labels: p2, repeat-contributor

#27664 fix: duration doesn't get accurately compared in multi alb service base
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs-patterns/test/ec2/integ.multiple-application-load-balanced-ecs-service-idle-timeout.js.snapshot/aws-ecs-integ-alb-idle-timeout.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs-patterns/test/ec2/integ.multiple-application-load-balanced-ecs-service-idle-timeout.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs-patterns/test/ec2/integ.multiple-application-load-balanced-ecs-service-idle-timeout.ts
  packages/aws-cdk-lib/aws-ecs-patterns/lib/base/application-multiple-target-groups-service-base.ts
  packages/aws-cdk-lib/aws-ecs-patterns/test/ec2/l3s.test.ts
Labels: p2, beginning-contributor, pr-linter/exemption-requested

#27603 feat(scheduler-alpha): target properties override
  packages/@aws-cdk/aws-scheduler-alpha/README.md
  packages/@aws-cdk/aws-scheduler-alpha/lib/schedule.ts
  packages/@aws-cdk/aws-scheduler-alpha/test/input.test.ts
  packages/@aws-cdk/aws-scheduler-alpha/test/integ.schedule.js.snapshot/aws-cdk-scheduler-schedule.assets.json
  packages/@aws-cdk/aws-scheduler-alpha/test/integ.schedule.js.snapshot/aws-cdk-scheduler-schedule.template.json
  packages/@aws-cdk/aws-scheduler-alpha/test/integ.schedule.js.snapshot/manifest.json
  packages/@aws-cdk/aws-scheduler-alpha/test/integ.schedule.js.snapshot/tree.json
  packages/@aws-cdk/aws-scheduler-alpha/test/integ.schedule.ts
  packages/@aws-cdk/aws-scheduler-alpha/test/retry-policy.test.ts
Labels: p2, feature-request, effort/small, distinguished-contributor, pr-linter/exemption-requested

#27649 feat(dynamodb): add tagging support to TableV2
  packages/@aws-cdk-testing/framework-integ/test/aws-dynamodb/test/integ.table-v2-global.js.snapshot/aws-cdk-global-table.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-dynamodb/test/integ.table-v2-global.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-dynamodb/test/integ.table-v2-global.ts
  packages/aws-cdk-lib/aws-dynamodb/README.md
  packages/aws-cdk-lib/aws-dynamodb/lib/table-v2.ts
  packages/aws-cdk-lib/aws-dynamodb/test/table-v2.test.ts
Labels: p1, feature-request, effort/medium, beginning-contributor

#27700 revert: "fix(pipelines): using the same source (s3, connection, or codecommit) in a pipeline causes duplicate id error"
  packages/@aws-cdk-testing/framework-integ/test/pipelines/test/integ.newpipeline-with-file-system-locations.js.snapshot/PipelinesFileSystemLocations.assets.json
  packages/@aws-cdk-testing/framework-integ/test/pipelines/test/integ.newpipeline-with-file-system-locations.js.snapshot/PipelinesFileSystemLocations.template.json
  packages/@aws-cdk-testing/framework-integ/test/pipelines/test/integ.newpipeline-with-file-system-locations.js.snapshot/PipelinesFileSystemLocationsPipeline5689C8D8.dot
  packages/@aws-cdk-testing/framework-integ/test/pipelines/test/integ.newpipeline-with-file-system-locations.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/pipelines/test/integ.newpipeline-with-file-system-locations.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/pipelines/test/integ.pipeline-with-additional-inputs.js.snapshot/PipelineAdditionalInputs.assets.json
  packages/@aws-cdk-testing/framework-integ/test/pipelines/test/integ.pipeline-with-additional-inputs.js.snapshot/PipelineAdditionalInputs.template.json
  packages/@aws-cdk-testing/framework-integ/test/pipelines/test/integ.pipeline-with-additional-inputs.js.snapshot/PipelineAdditionalInputsMultiSourcePipeline1F1B15BF4.dot
  packages/@aws-cdk-testing/framework-integ/test/pipelines/test/integ.pipeline-with-additional-inputs.js.snapshot/PipelineAdditionalInputsMultiSourcePipeline2F6A2A9FB.dot
  packages/@aws-cdk-testing/framework-integ/test/pipelines/test/integ.pipeline-with-additional-inputs.js.snapshot/PipelineAdditionalInputsTestDefaultTestDeployAssert78A10DC5.assets.json
  packages/@aws-cdk-testing/framework-integ/test/pipelines/test/integ.pipeline-with-additional-inputs.js.snapshot/PipelineAdditionalInputsTestDefaultTestDeployAssert78A10DC5.template.json
  packages/@aws-cdk-testing/framework-integ/test/pipelines/test/integ.pipeline-with-additional-inputs.js.snapshot/asset.a5feac1d1e65b04919886f5961fd2ba1352489d558439d9d6592877e92fc2814.bundle/index.js
  packages/@aws-cdk-testing/framework-integ/test/pipelines/test/integ.pipeline-with-additional-inputs.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/pipelines/test/integ.pipeline-with-additional-inputs.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/pipelines/test/integ.pipeline-with-additional-inputs.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/pipelines/test/integ.pipeline-with-additional-inputs.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/pipelines/test/integ.pipeline-with-additional-inputs.ts
  packages/@aws-cdk-testing/framework-integ/test/pipelines/test/integ.pipeline-with-artifact-bucket.js.snapshot/ClusterTestDefaultTestDeployAssert6A1BBA9D.assets.json
  packages/@aws-cdk-testing/framework-integ/test/pipelines/test/integ.pipeline-with-artifact-bucket.js.snapshot/PipelineStack.assets.json
  packages/@aws-cdk-testing/framework-integ/test/pipelines/test/integ.pipeline-with-artifact-bucket.js.snapshot/PipelineStack.template.json
  packages/@aws-cdk-testing/framework-integ/test/pipelines/test/integ.pipeline-with-artifact-bucket.js.snapshot/PipelineStackPipeline9DB740AF.dot
  packages/@aws-cdk-testing/framework-integ/test/pipelines/test/integ.pipeline-with-artifact-bucket.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/pipelines/test/integ.pipeline-with-artifact-bucket.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/pipelines/test/integ.pipeline-with-artifact-bucket.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/pipelines/test/integ.pipeline-with-artifact-bucket.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/pipelines/test/integ.pipeline-with-variables.js.snapshot/VariablePipelineStack.assets.json
  packages/@aws-cdk-testing/framework-integ/test/pipelines/test/integ.pipeline-with-variables.js.snapshot/VariablePipelineStack.template.json
  packages/@aws-cdk-testing/framework-integ/test/pipelines/test/integ.pipeline-with-variables.js.snapshot/VariablePipelineStackPipeline0F9B805A.dot
  packages/@aws-cdk-testing/framework-integ/test/pipelines/test/integ.pipeline-with-variables.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/pipelines/test/integ.pipeline-with-variables.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/pipelines/test/integ.pipeline-without-prepare.js.snapshot/PreparelessPipelineStack.assets.json
  packages/@aws-cdk-testing/framework-integ/test/pipelines/test/integ.pipeline-without-prepare.js.snapshot/PreparelessPipelineStack.template.json
  packages/@aws-cdk-testing/framework-integ/test/pipelines/test/integ.pipeline-without-prepare.js.snapshot/PreparelessPipelineStackPipeline55359117.dot
  packages/@aws-cdk-testing/framework-integ/test/pipelines/test/integ.pipeline-without-prepare.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/pipelines/test/integ.pipeline-without-prepare.js.snapshot/tree.json
  packages/aws-cdk-lib/pipelines/lib/codepipeline/codepipeline-source.ts
Labels: p2, contribution/core

#27702 chore(release): 2.103.1
  CHANGELOG.v2.alpha.md
  CHANGELOG.v2.md
  packages/@aws-cdk-testing/framework-integ/test/pipelines/test/integ.newpipeline-with-file-system-locations.js.snapshot/PipelinesFileSystemLocations.assets.json
  packages/@aws-cdk-testing/framework-integ/test/pipelines/test/integ.newpipeline-with-file-system-locations.js.snapshot/PipelinesFileSystemLocations.template.json
  packages/@aws-cdk-testing/framework-integ/test/pipelines/test/integ.newpipeline-with-file-system-locations.js.snapshot/PipelinesFileSystemLocationsPipeline5689C8D8.dot
  packages/@aws-cdk-testing/framework-integ/test/pipelines/test/integ.newpipeline-with-file-system-locations.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/pipelines/test/integ.newpipeline-with-file-system-locations.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/pipelines/test/integ.pipeline-with-additional-inputs.js.snapshot/PipelineAdditionalInputs.assets.json
  packages/@aws-cdk-testing/framework-integ/test/pipelines/test/integ.pipeline-with-additional-inputs.js.snapshot/PipelineAdditionalInputs.template.json
  packages/@aws-cdk-testing/framework-integ/test/pipelines/test/integ.pipeline-with-additional-inputs.js.snapshot/PipelineAdditionalInputsMultiSourcePipeline1F1B15BF4.dot
  packages/@aws-cdk-testing/framework-integ/test/pipelines/test/integ.pipeline-with-additional-inputs.js.snapshot/PipelineAdditionalInputsMultiSourcePipeline2F6A2A9FB.dot
  packages/@aws-cdk-testing/framework-integ/test/pipelines/test/integ.pipeline-with-additional-inputs.js.snapshot/PipelineAdditionalInputsTestDefaultTestDeployAssert78A10DC5.assets.json
  packages/@aws-cdk-testing/framework-integ/test/pipelines/test/integ.pipeline-with-additional-inputs.js.snapshot/PipelineAdditionalInputsTestDefaultTestDeployAssert78A10DC5.template.json
  packages/@aws-cdk-testing/framework-integ/test/pipelines/test/integ.pipeline-with-additional-inputs.js.snapshot/asset.a5feac1d1e65b04919886f5961fd2ba1352489d558439d9d6592877e92fc2814.bundle/index.js
  packages/@aws-cdk-testing/framework-integ/test/pipelines/test/integ.pipeline-with-additional-inputs.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/pipelines/test/integ.pipeline-with-additional-inputs.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/pipelines/test/integ.pipeline-with-additional-inputs.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/pipelines/test/integ.pipeline-with-additional-inputs.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/pipelines/test/integ.pipeline-with-additional-inputs.ts
  packages/@aws-cdk-testing/framework-integ/test/pipelines/test/integ.pipeline-with-artifact-bucket.js.snapshot/ClusterTestDefaultTestDeployAssert6A1BBA9D.assets.json
  packages/@aws-cdk-testing/framework-integ/test/pipelines/test/integ.pipeline-with-artifact-bucket.js.snapshot/PipelineStack.assets.json
  packages/@aws-cdk-testing/framework-integ/test/pipelines/test/integ.pipeline-with-artifact-bucket.js.snapshot/PipelineStack.template.json
  packages/@aws-cdk-testing/framework-integ/test/pipelines/test/integ.pipeline-with-artifact-bucket.js.snapshot/PipelineStackPipeline9DB740AF.dot
  packages/@aws-cdk-testing/framework-integ/test/pipelines/test/integ.pipeline-with-artifact-bucket.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/pipelines/test/integ.pipeline-with-artifact-bucket.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/pipelines/test/integ.pipeline-with-artifact-bucket.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/pipelines/test/integ.pipeline-with-artifact-bucket.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/pipelines/test/integ.pipeline-with-variables.js.snapshot/VariablePipelineStack.assets.json
  packages/@aws-cdk-testing/framework-integ/test/pipelines/test/integ.pipeline-with-variables.js.snapshot/VariablePipelineStack.template.json
  packages/@aws-cdk-testing/framework-integ/test/pipelines/test/integ.pipeline-with-variables.js.snapshot/VariablePipelineStackPipeline0F9B805A.dot
  packages/@aws-cdk-testing/framework-integ/test/pipelines/test/integ.pipeline-with-variables.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/pipelines/test/integ.pipeline-with-variables.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/pipelines/test/integ.pipeline-without-prepare.js.snapshot/PreparelessPipelineStack.assets.json
  packages/@aws-cdk-testing/framework-integ/test/pipelines/test/integ.pipeline-without-prepare.js.snapshot/PreparelessPipelineStack.template.json
  packages/@aws-cdk-testing/framework-integ/test/pipelines/test/integ.pipeline-without-prepare.js.snapshot/PreparelessPipelineStackPipeline55359117.dot
  packages/@aws-cdk-testing/framework-integ/test/pipelines/test/integ.pipeline-without-prepare.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/pipelines/test/integ.pipeline-without-prepare.js.snapshot/tree.json
  packages/aws-cdk-lib/pipelines/lib/codepipeline/codepipeline-source.ts
  version.v2.json
Labels: p2, contribution/core, pr/no-squash

#27706 chore(merge-back): 2.103.1
  CHANGELOG.v2.alpha.md
  CHANGELOG.v2.md
  version.v2.json
Labels: p2, pr/needs-community-review, pr/no-squash, auto-approve

#27716 docs: fix typos in developer docs
  CONTRIBUTING.md
  INTEGRATION_TESTS.md
Labels: p2, valued-contributor

#27718 docs: update CONTRIBUTING.md
  CONTRIBUTING.md
Labels: p2, valued-contributor

#27576 fix(apigatewayv2): defaultAuthorizer cannot be applied to HttpRoute
  packages/@aws-cdk/aws-apigatewayv2-alpha/lib/http/api.ts
  packages/@aws-cdk/aws-apigatewayv2-alpha/lib/http/route.ts
  packages/@aws-cdk/aws-apigatewayv2-alpha/test/http/route.test.ts
  packages/@aws-cdk/aws-apigatewayv2-authorizers-alpha/test/http/integ.lambda.js.snapshot/AuthorizerInteg.assets.json
  packages/@aws-cdk/aws-apigatewayv2-authorizers-alpha/test/http/integ.lambda.js.snapshot/AuthorizerInteg.template.json
  packages/@aws-cdk/aws-apigatewayv2-authorizers-alpha/test/http/integ.lambda.js.snapshot/manifest.json
  packages/@aws-cdk/aws-apigatewayv2-authorizers-alpha/test/http/integ.lambda.js.snapshot/tree.json
  packages/@aws-cdk/aws-apigatewayv2-authorizers-alpha/test/http/integ.lambda.ts
  packages/@aws-cdk/aws-apigatewayv2-authorizers-alpha/test/http/integ.user-pool.js.snapshot/AuthorizerInteg.assets.json
  packages/@aws-cdk/aws-apigatewayv2-authorizers-alpha/test/http/integ.user-pool.js.snapshot/AuthorizerInteg.template.json
  packages/@aws-cdk/aws-apigatewayv2-authorizers-alpha/test/http/integ.user-pool.js.snapshot/manifest.json
  packages/@aws-cdk/aws-apigatewayv2-authorizers-alpha/test/http/integ.user-pool.js.snapshot/tree.json
  packages/@aws-cdk/aws-apigatewayv2-authorizers-alpha/test/http/integ.user-pool.ts
Labels: bug, p2, admired-contributor

#27755 feat: update AWS Service Spec
  tools/@aws-cdk/spec2cdk/package.json
  yarn.lock
Labels: p2, dependencies, contribution/core, pr-linter/exempt-readme, pr-linter/exempt-test, auto-approve, pr-linter/exempt-integ-test

#27720 fix(cloudwatch): setting gauge widget annotations caused deployment failures
  packages/@aws-cdk-testing/framework-integ/test/aws-cloudwatch/test/integ.gauge-widget.js.snapshot/LambdaTestDefaultTestDeployAssert1AF2B360.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-cloudwatch/test/integ.gauge-widget.js.snapshot/LambdaTestDefaultTestDeployAssert1AF2B360.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-cloudwatch/test/integ.gauge-widget.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-cloudwatch/test/integ.gauge-widget.js.snapshot/gauge-alarm.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-cloudwatch/test/integ.gauge-widget.js.snapshot/gauge-alarm.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-cloudwatch/test/integ.gauge-widget.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-cloudwatch/test/integ.gauge-widget.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-cloudwatch/test/integ.gauge-widget.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-cloudwatch/test/integ.gauge-widget.ts
  packages/aws-cdk-lib/aws-cloudwatch/lib/graph.ts
  packages/aws-cdk-lib/aws-cloudwatch/test/graphs.test.ts
Labels: bug, p1, effort/medium, contribution/core, pr/needs-maintainer-review

#27767 chore(apigatewayv2): turn on awslint
  packages/@aws-cdk/aws-apigatewayv2-alpha/awslint.json
  packages/@aws-cdk/aws-apigatewayv2-alpha/lib/http/api.ts
Labels: p2, contribution/core, pr/needs-maintainer-review

#27766 chore(amplify): turn on awslint
  packages/@aws-cdk/aws-amplify-alpha/awslint.json
  packages/@aws-cdk/aws-amplify-alpha/lib/app.ts
Labels: p2, contribution/core

#27771 chore: check region-info completeness
  packages/aws-cdk-lib/region-info/lib/fact.ts
  scripts/check-api-compatibility.sh
  scripts/check-region-info-compatibility.ts
Labels: p2, contribution/core, pr/needs-maintainer-review

#27703 chore: add more details to CONTRIBUTING
  CONTRIBUTING.md
  docs/contribution_flow.png
Labels: p2, contribution/core

#27768 chore(cloudfront): create unit tests to mock edge function handler
  packages/aws-cdk-lib/aws-cloudfront/test/experimental/edge-function.test.ts
Labels: p2, feature-request, contribution/core
