Repository aws/aws-cdk, pull requests merged in 2023-08, with the labels that each got.

#26584 chore(actions): stop spamming stale notification for forks + 2
  .github/workflows/repo-metrics.yml
  .github/workflows/spec-update.yml
Labels: p2, pr/needs-community-review, star-contributor

#26591 docs(appsync): fix outdated documentation
  packages/aws-cdk-lib/aws-appsync/lib/graphqlapi.ts
Labels: p2, beginning-contributor

#26590 chore: fix "certifcate" typos
  packages/aws-cdk-lib/aws-certificatemanager/lib/certificate.ts
  packages/aws-cdk-lib/aws-certificatemanager/test/certificate.test.ts
  packages/aws-cdk-lib/aws-cloudfront/lib/web-distribution.ts
Labels: p2, beginning-contributor

#25858 feat(stepfunctions): allow setting comment on state machine
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions/test/integ.state-machine.js.snapshot/aws-stepfunctions-integ.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions/test/integ.state-machine.js.snapshot/aws-stepfunctions-integ.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions/test/integ.state-machine.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions/test/integ.state-machine.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions/test/integ.state-machine.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions/test/integ.state-machine.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions/test/integ.state-machine.ts
  packages/aws-cdk-lib/aws-stepfunctions/README.md
  packages/aws-cdk-lib/aws-stepfunctions/lib/state-machine.ts
  packages/aws-cdk-lib/aws-stepfunctions/test/state-machine.test.ts
Labels: p2, beginning-contributor

#26569 fix(synthetics): updated handler validation
  packages/@aws-cdk/aws-synthetics-alpha/lib/canary.ts
  packages/@aws-cdk/aws-synthetics-alpha/test/canaries/nodejs/node_modules/folder/canary.js
  packages/@aws-cdk/aws-synthetics-alpha/test/canary.test.ts
  packages/@aws-cdk/aws-synthetics-alpha/test/integ.canary.js.snapshot/IntegCanaryTestDefaultTestDeployAssert3AD5A094.assets.json
  packages/@aws-cdk/aws-synthetics-alpha/test/integ.canary.js.snapshot/IntegCanaryTestDefaultTestDeployAssert3AD5A094.template.json
  packages/@aws-cdk/aws-synthetics-alpha/test/integ.canary.js.snapshot/asset.216218e507a977a1bb3592f29c1a62ab3e0a9eb25569109a395315638e154329/index.js
  packages/@aws-cdk/aws-synthetics-alpha/test/integ.canary.js.snapshot/asset.4914857a6c9238eb37ddc008b7f94fd44599625d49d95ee13c68e8e177dee7e9/nodejs/node_modules/canary.js
  packages/@aws-cdk/aws-synthetics-alpha/test/integ.canary.js.snapshot/asset.4914857a6c9238eb37ddc008b7f94fd44599625d49d95ee13c68e8e177dee7e9/nodejs/node_modules/folder/canary.js
  packages/@aws-cdk/aws-synthetics-alpha/test/integ.canary.js.snapshot/asset.4914857a6c9238eb37ddc008b7f94fd44599625d49d95ee13c68e8e177dee7e9/python/canary.py
  packages/@aws-cdk/aws-synthetics-alpha/test/integ.canary.js.snapshot/asset.89c643a8a6c919d906e0b1cb079b0c5e131cf3cc19c05126f90fc118647fb08c/index.js
  packages/@aws-cdk/aws-synthetics-alpha/test/integ.canary.js.snapshot/asset.d5b88712f80b7d8c96ddbffc883a569f5e5681cf14a985d4d0933ca3712f5110.bundle/index.js
  packages/@aws-cdk/aws-synthetics-alpha/test/integ.canary.js.snapshot/canary-one.assets.json
  packages/@aws-cdk/aws-synthetics-alpha/test/integ.canary.js.snapshot/canary-one.template.json
  packages/@aws-cdk/aws-synthetics-alpha/test/integ.canary.js.snapshot/cdk.out
  packages/@aws-cdk/aws-synthetics-alpha/test/integ.canary.js.snapshot/integ.json
  packages/@aws-cdk/aws-synthetics-alpha/test/integ.canary.js.snapshot/manifest.json
  packages/@aws-cdk/aws-synthetics-alpha/test/integ.canary.js.snapshot/tree.json
  packages/@aws-cdk/aws-synthetics-alpha/test/integ.canary.ts
Labels: bug, p2, effort/small, star-contributor, pr-linter/exemption-requested

#26606 chore: npm-check-updates && yarn upgrade
  package.json
  packages/@aws-cdk-testing/cli-integ/package.json
  packages/@aws-cdk-testing/framework-integ/package.json
  packages/@aws-cdk-testing/framework-integ/test/aws-eks/test/sdk-call-integ-test-docker-app/app/package.json
  packages/@aws-cdk/aws-amplify-alpha/package.json
  packages/@aws-cdk/aws-redshift-alpha/package.json
  packages/@aws-cdk/custom-resource-handlers/package.json
  packages/@aws-cdk/integ-runner/THIRD_PARTY_LICENSES
  packages/@aws-cdk/integ-tests-alpha/package.json
  packages/aws-cdk-lib/package.json
  packages/aws-cdk/THIRD_PARTY_LICENSES
  packages/aws-cdk/package.json
  packages/awslint/package.json
  packages/cdk-assets/package.json
  tools/@aws-cdk/cdk-build-tools/package.json
  tools/@aws-cdk/cfn2ts/package.json
  tools/@aws-cdk/node-bundle/package.json
  tools/@aws-cdk/pkglint/package.json
  tools/@aws-cdk/prlint/package.json
  yarn.lock
Labels: p2, dependencies, contribution/core, auto-approve, pr/needs-maintainer-review

#26384 fix(ecs): unclear docs on valid ec2 task definition placement constraints and no validation of input #25933
  package.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs/test/ec2/integ.task-definition-placement-constraints.js.snapshot/asset.ba598c1f1d84f7077ea9c16a6b921e4f8acf18e996100e72a8f17da980e64fdd/__entrypoint__.js
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs/test/ec2/integ.task-definition-placement-constraints.js.snapshot/asset.ba598c1f1d84f7077ea9c16a6b921e4f8acf18e996100e72a8f17da980e64fdd/index.js
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs/test/ec2/integ.task-definition-placement-constraints.js.snapshot/aws-cdk-ecs-integration-test-stack.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs/test/ec2/integ.task-definition-placement-constraints.js.snapshot/aws-cdk-ecs-integration-test-stack.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs/test/ec2/integ.task-definition-placement-constraints.js.snapshot/awscdkecsintegrationteststackTaskDefinitionPlacementConstraintsDefaultTestDeployAssert906A0CF3.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs/test/ec2/integ.task-definition-placement-constraints.js.snapshot/awscdkecsintegrationteststackTaskDefinitionPlacementConstraintsDefaultTestDeployAssert906A0CF3.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs/test/ec2/integ.task-definition-placement-constraints.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs/test/ec2/integ.task-definition-placement-constraints.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs/test/ec2/integ.task-definition-placement-constraints.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs/test/ec2/integ.task-definition-placement-constraints.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs/test/ec2/integ.task-definition-placement-constraints.ts
  packages/aws-cdk-lib/aws-ecs/lib/ec2/ec2-task-definition.ts
  packages/aws-cdk-lib/aws-ecs/test/ec2/ec2-task-definition.test.ts
  yarn.lock
Labels: bug, p2, effort/small, beginning-contributor

#26607 fix(app-staging-synthesizer): misleading error message about environment-agnostic/aware stacks
  packages/@aws-cdk/app-staging-synthesizer-alpha/lib/app-staging-synthesizer.ts
Labels: p2, contribution/core, pr-linter/exempt-test, pr-linter/exempt-integ-test

#26602 feat(core): new RemovalPolicy.RETAIN_EXCEPT_ON_CREATE to only retain resources that have been successfully created
  packages/aws-cdk-lib/core/lib/cfn-resource-policy.ts
  packages/aws-cdk-lib/core/lib/cfn-resource.ts
  packages/aws-cdk-lib/core/lib/removal-policy.ts
  packages/aws-cdk-lib/core/test/removal-policy.test.ts
Labels: p1, feature-request, contribution/core, pr-linter/exempt-readme, pr-linter/exempt-integ-test

#26371 fix(ec2): flowLogName property for FlowLog construct does not work
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.vpc-flow-logs-customformat.js.snapshot/FlowLogsTestStack.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.vpc-flow-logs-customformat.js.snapshot/FlowLogsTestStack.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.vpc-flow-logs-customformat.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.vpc-flow-logs-customformat.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.vpc-flow-logs-interval.js.snapshot/FlowLogsTestStack.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.vpc-flow-logs-interval.js.snapshot/FlowLogsTestStack.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.vpc-flow-logs-interval.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.vpc-flow-logs-interval.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.vpc-flow-logs.js.snapshot/DependencyTestStack.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.vpc-flow-logs.js.snapshot/DependencyTestStack.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.vpc-flow-logs.js.snapshot/FlowLogsDefaultTestDeployAssert6AFD1854.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.vpc-flow-logs.js.snapshot/FlowLogsDefaultTestDeployAssert6AFD1854.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.vpc-flow-logs.js.snapshot/FlowLogsFeatureFlag.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.vpc-flow-logs.js.snapshot/FlowLogsFeatureFlag.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.vpc-flow-logs.js.snapshot/FlowLogsTestStack.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.vpc-flow-logs.js.snapshot/FlowLogsTestStack.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.vpc-flow-logs.js.snapshot/asset.24c03de0e1b6ad4676ce5381cc627036845a778dbd7efe5a16cbb13dc5003fdc.bundle/index.js
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.vpc-flow-logs.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.vpc-flow-logs.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.vpc-flow-logs.ts
  packages/aws-cdk-lib/aws-ec2/lib/vpc-flow-logs.ts
  packages/aws-cdk-lib/aws-ec2/test/vpc-flow-logs.test.ts
Labels: bug, p2, repeat-contributor

#26493 fix(cli): specifying --quiet does not suppress asset building and publishing logs
  packages/aws-cdk/lib/util/asset-publishing.ts
  packages/cdk-assets/lib/private/asset-handler.ts
  packages/cdk-assets/lib/private/docker.ts
  packages/cdk-assets/lib/private/handlers/container-images.ts
  packages/cdk-assets/lib/private/handlers/index.ts
  packages/cdk-assets/lib/publishing.ts
Labels: p2, contribution/core, pr-linter/exempt-test, pr-linter/exempt-integ-test, pr-linter/cli-integ-tested

#26505 feat(aws-cdk-lib): ADOT Lambda Layer v0.31.0
  packages/aws-cdk-lib/region-info/build-tools/fact-tables.ts
Labels: p2, pr-linter/exempt-readme, pr-linter/exempt-test, pr-linter/exempt-integ-test, beginning-contributor

#26475 chore(lambda): update default node runtime for all partitions
  packages/aws-cdk-lib/aws-logs/lib/log-retention.ts
  packages/aws-cdk-lib/core/lib/custom-resource-provider/custom-resource-provider.ts
  packages/aws-cdk-lib/core/test/custom-resource-provider/custom-resource-provider.test.ts
  packages/aws-cdk-lib/custom-resources/lib/aws-custom-resource/aws-custom-resource.ts
  packages/aws-cdk-lib/custom-resources/test/aws-custom-resource/aws-custom-resource.test.ts
  packages/aws-cdk-lib/region-info/build-tools/fact-tables.ts
Labels: bug, p1, pr-linter/exempt-integ-test, star-contributor, pr/needs-maintainer-review

#26631 docs(custom-resources): remove section about experimental SDKv3 support
  packages/aws-cdk-lib/custom-resources/README.md
Labels: p2, contribution/core

#26356 feat(core): support ssh build arg in DockerImageAsset
  packages/@aws-cdk-testing/framework-integ/test/aws-ecr-assets/test/demo-image-ssh/Dockerfile
  packages/@aws-cdk-testing/framework-integ/test/aws-ecr-assets/test/demo-image-ssh/index.py
  packages/@aws-cdk-testing/framework-integ/test/aws-ecr-assets/test/integ.assets-docker.js.snapshot/asset.6308cecadfac022764e8f3e3272baeab95b48a260cae3978b7ef93bd3ff2be17/Dockerfile
  packages/@aws-cdk-testing/framework-integ/test/aws-ecr-assets/test/integ.assets-docker.js.snapshot/asset.6308cecadfac022764e8f3e3272baeab95b48a260cae3978b7ef93bd3ff2be17/index.py
  packages/@aws-cdk-testing/framework-integ/test/aws-ecr-assets/test/integ.assets-docker.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-ecr-assets/test/integ.assets-docker.js.snapshot/integ-assets-docker.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecr-assets/test/integ.assets-docker.js.snapshot/integ-assets-docker.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecr-assets/test/integ.assets-docker.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecr-assets/test/integ.assets-docker.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecr-assets/test/integ.assets-docker.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecr-assets/test/integ.assets-docker.ts
  packages/aws-cdk-lib/aws-ecr-assets/README.md
  packages/aws-cdk-lib/aws-ecr-assets/lib/image-asset.ts
  packages/aws-cdk-lib/aws-ecr-assets/test/image-asset.test.ts
  packages/aws-cdk-lib/cloud-assembly-schema/lib/assets/docker-image-asset.ts
  packages/aws-cdk-lib/cloud-assembly-schema/lib/cloud-assembly/metadata-schema.ts
  packages/aws-cdk-lib/cloud-assembly-schema/schema/assets.schema.json
  packages/aws-cdk-lib/cloud-assembly-schema/schema/cloud-assembly.schema.json
  packages/aws-cdk-lib/core/lib/assets.ts
  packages/aws-cdk-lib/cx-api/lib/assets.ts
  packages/aws-cdk/lib/assets.ts
  packages/cdk-assets/lib/private/docker.ts
Labels: p2, pr/needs-community-review, beginning-contributor, pr-linter/cli-integ-tested

#26643 chore(merge-back): 2.90.0
  CHANGELOG.v2.alpha.md
  CHANGELOG.v2.md
  version.v2.json
Labels: p2, pr/needs-community-review, pr/no-squash, auto-approve

#26650 fix(glue): synth time validation does not work in Python/Java/C#/Go
  packages/@aws-cdk/aws-glue-alpha/lib/job-executable.ts
  packages/@aws-cdk/aws-glue-alpha/lib/job.ts
  packages/@aws-cdk/aws-glue-alpha/test/integ.job-python-shell.js.snapshot/asset.432033e3218068a915d2532fa9be7858a12b228a2ae6e5c10faccd9097b1e855.py
  packages/@aws-cdk/aws-glue-alpha/test/integ.job-python-shell.js.snapshot/aws-glue-job-python-shell.assets.json
  packages/@aws-cdk/aws-glue-alpha/test/integ.job-python-shell.js.snapshot/aws-glue-job-python-shell.template.json
  packages/@aws-cdk/aws-glue-alpha/test/integ.job-python-shell.js.snapshot/awsgluejobpythonshellintegtestDefaultTestDeployAssert453D25B7.assets.json
  packages/@aws-cdk/aws-glue-alpha/test/integ.job-python-shell.js.snapshot/awsgluejobpythonshellintegtestDefaultTestDeployAssert453D25B7.template.json
  packages/@aws-cdk/aws-glue-alpha/test/integ.job-python-shell.js.snapshot/cdk.out
  packages/@aws-cdk/aws-glue-alpha/test/integ.job-python-shell.js.snapshot/integ.json
  packages/@aws-cdk/aws-glue-alpha/test/integ.job-python-shell.js.snapshot/manifest.json
  packages/@aws-cdk/aws-glue-alpha/test/integ.job-python-shell.js.snapshot/tree.json
  packages/@aws-cdk/aws-glue-alpha/test/integ.job-python-shell.ts
  packages/@aws-cdk/aws-glue-alpha/test/job-executable.test.ts
  packages/@aws-cdk/aws-glue-alpha/test/job.test.ts
Labels: p1, feature-request, effort/small, star-contributor

#26626 fix(lambda): Lambda Insights Layer ARN 1.0.229 in us-west-1 on ARM64 incorrect
  packages/aws-cdk-lib/region-info/build-tools/fact-tables.ts
  packages/aws-cdk-lib/region-info/test/__snapshots__/region-info.test.js.snap
Labels: bug, p1, effort/small, pr-linter/exempt-test, pr-linter/exempt-integ-test

#26658 feat: update AWS Service Spec
  package.json
  tools/@aws-cdk/spec2cdk/package.json
  yarn.lock
Labels: p2, dependencies, contribution/core, pr-linter/exempt-readme, pr-linter/exempt-test, auto-approve, pr-linter/exempt-integ-test

#26651 feat(rds): support aurora mysql 3.04.0
  packages/aws-cdk-lib/aws-rds/lib/cluster-engine.ts
Labels: p2, pr-linter/exempt-readme, pr-linter/exempt-test, pr-linter/exempt-integ-test, beginning-contributor

#26664 chore(lambda-nodejs): update docs for default runtime value
  packages/aws-cdk-lib/aws-lambda-nodejs/lib/function.ts
Labels: bug, p2, effort/medium, beginning-contributor

#26666 fix: broken cross-region reference in aws-route53
  packages/@aws-cdk-testing/framework-integ/test/aws-route53/test/integ.cross-account-zone-delegation.js.snapshot/Route53CrossAccountIntegDefaultTestDeployAssertF1D808C9.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-route53/test/integ.cross-account-zone-delegation.js.snapshot/Route53CrossAccountIntegDefaultTestDeployAssertF1D808C9.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-route53/test/integ.cross-account-zone-delegation.js.snapshot/asset.41c4b73830acc6810dfa58ee8d966cb1485aa9daa124decc1e33f957eeb1adb3/index.js
  packages/@aws-cdk-testing/framework-integ/test/aws-route53/test/integ.cross-account-zone-delegation.js.snapshot/asset.ab0afc2f801b8ac11473bad4d9f22578919d8959b5f1bcd21b05c4ac895dbcab/__entrypoint__.js
  packages/@aws-cdk-testing/framework-integ/test/aws-route53/test/integ.cross-account-zone-delegation.js.snapshot/asset.ab0afc2f801b8ac11473bad4d9f22578919d8959b5f1bcd21b05c4ac895dbcab/index.js
  packages/@aws-cdk-testing/framework-integ/test/aws-route53/test/integ.cross-account-zone-delegation.js.snapshot/aws-cdk-route53-cross-account-integ.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-route53/test/integ.cross-account-zone-delegation.js.snapshot/aws-cdk-route53-cross-account-integ.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-route53/test/integ.cross-account-zone-delegation.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-route53/test/integ.cross-account-zone-delegation.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-route53/test/integ.cross-account-zone-delegation.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-route53/test/integ.cross-account-zone-delegation.js.snapshot/tree.json
  packages/aws-cdk-lib/aws-route53/lib/cross-account-zone-delegation-handler/index.ts
  packages/aws-cdk-lib/aws-route53/lib/record-set.ts
  packages/aws-cdk-lib/aws-route53/test/cross-account-zone-delegation-handler/index.test.ts
Labels: p2, contribution/core, pr-linter/exempt-integ-test

#26685 chore: npm-check-updates && yarn upgrade
  package.json
  packages/@aws-cdk-testing/cli-integ/package.json
  packages/@aws-cdk-testing/framework-integ/package.json
  packages/@aws-cdk-testing/framework-integ/test/aws-eks/test/sdk-call-integ-test-docker-app/app/package.json
  packages/@aws-cdk/aws-amplify-alpha/package.json
  packages/@aws-cdk/aws-redshift-alpha/package.json
  packages/@aws-cdk/custom-resource-handlers/package.json
  packages/@aws-cdk/integ-runner/THIRD_PARTY_LICENSES
  packages/@aws-cdk/integ-tests-alpha/package.json
  packages/aws-cdk-lib/package.json
  packages/aws-cdk/THIRD_PARTY_LICENSES
  packages/aws-cdk/lib/init-templates/app/typescript/package.json
  packages/aws-cdk/lib/init-templates/lib/typescript/package.json
  packages/aws-cdk/lib/init-templates/sample-app/typescript/package.json
  packages/aws-cdk/package.json
  packages/awslint/package.json
  packages/cdk-assets/package.json
  tools/@aws-cdk/cdk-build-tools/package.json
  tools/@aws-cdk/cfn2ts/package.json
  tools/@aws-cdk/node-bundle/package.json
  tools/@aws-cdk/pkglint/package.json
  tools/@aws-cdk/prlint/package.json
  yarn.lock
Labels: p2, dependencies, contribution/core, auto-approve

#26683 chore(ground-station): Scaffold AWS Ground Station alpha
  packages/@aws-cdk/aws-groundstation-alpha/.eslintrc.js
  packages/@aws-cdk/aws-groundstation-alpha/.gitignore
  packages/@aws-cdk/aws-groundstation-alpha/.npmignore
  packages/@aws-cdk/aws-groundstation-alpha/LICENSE
  packages/@aws-cdk/aws-groundstation-alpha/NOTICE
  packages/@aws-cdk/aws-groundstation-alpha/README.md
  packages/@aws-cdk/aws-groundstation-alpha/jest.config.js
  packages/@aws-cdk/aws-groundstation-alpha/lib/index.ts
  packages/@aws-cdk/aws-groundstation-alpha/package.json
  packages/@aws-cdk/aws-groundstation-alpha/rosetta/default.ts-fixture
Labels: p2, beginning-contributor

#26700 docs(cognito): wrong default value for UserPoolClient authFlows
  packages/aws-cdk-lib/aws-cognito/lib/user-pool-client.ts
Labels: bug, p1, effort/small, star-contributor, pr/needs-maintainer-review

#26699 chore(rds): Add support for RDS MySQL minor versions of 8.0.34 and 5.7.43
  packages/aws-cdk-lib/aws-rds/lib/instance-engine.ts
Labels: p2, beginning-contributor

#26676 fix(triggers): executed on update even when executeOnHandlerChange is false
  packages/@aws-cdk-testing/framework-integ/test/triggers/test/integ.triggers.js.snapshot/MyStack.assets.json
  packages/@aws-cdk-testing/framework-integ/test/triggers/test/integ.triggers.js.snapshot/MyStack.template.json
  packages/@aws-cdk-testing/framework-integ/test/triggers/test/integ.triggers.js.snapshot/TriggerTestDefaultTestDeployAssert61636546.assets.json
  packages/@aws-cdk-testing/framework-integ/test/triggers/test/integ.triggers.js.snapshot/TriggerTestDefaultTestDeployAssert61636546.template.json
  packages/@aws-cdk-testing/framework-integ/test/triggers/test/integ.triggers.js.snapshot/asset.237e4a416773a5765262a8b9c70210bd35dfd48ae5a364b19e35f260026b5139/__entrypoint__.js
  packages/@aws-cdk-testing/framework-integ/test/triggers/test/integ.triggers.js.snapshot/asset.237e4a416773a5765262a8b9c70210bd35dfd48ae5a364b19e35f260026b5139/index.js
  packages/@aws-cdk-testing/framework-integ/test/triggers/test/integ.triggers.js.snapshot/asset.bcb8f5f1cebce365c4a0bf886b9820908bb469b121d65ef42809ae9798fb9232/index.js
  packages/@aws-cdk-testing/framework-integ/test/triggers/test/integ.triggers.js.snapshot/asset.e4815916885b43e053d8fcef603638aa3a4754c27a3cb0d21fd1c50c2923415b.bundle/index.js
  packages/@aws-cdk-testing/framework-integ/test/triggers/test/integ.triggers.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/triggers/test/integ.triggers.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/triggers/test/integ.triggers.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/triggers/test/integ.triggers.js.snapshot/tree.json
  packages/aws-cdk-lib/triggers/lib/lambda/index.ts
  packages/aws-cdk-lib/triggers/lib/trigger.ts
  packages/aws-cdk-lib/triggers/test/trigger-handler.test.ts
  packages/aws-cdk-lib/triggers/test/triggers.test.ts
Labels: bug, p1, effort/medium, pr-linter/exempt-integ-test, valued-contributor, pr-linter/exemption-requested

#26648 fix(apigateway): allowedOrigins are incorrectly interpreted as regexes
  packages/@aws-cdk-testing/framework-integ/test/aws-apigateway/test/integ.cors-allow-multiple-origins.js.snapshot/asset.c7bba0d9d477c86c6dc2adb0eb95842634a1c040dd3a66b42eec2bb604644d4f.handler/index.d.ts
  packages/@aws-cdk-testing/framework-integ/test/aws-apigateway/test/integ.cors-allow-multiple-origins.js.snapshot/asset.c7bba0d9d477c86c6dc2adb0eb95842634a1c040dd3a66b42eec2bb604644d4f.handler/index.js
  packages/@aws-cdk-testing/framework-integ/test/aws-apigateway/test/integ.cors-allow-multiple-origins.js.snapshot/asset.c7bba0d9d477c86c6dc2adb0eb95842634a1c040dd3a66b42eec2bb604644d4f.handler/index.ts
  packages/@aws-cdk-testing/framework-integ/test/aws-apigateway/test/integ.cors-allow-multiple-origins.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-apigateway/test/integ.cors-allow-multiple-origins.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-apigateway/test/integ.cors-allow-multiple-origins.js.snapshot/integcorsallowmultipleoriginsDefaultTestDeployAssertEBF0A1B1.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-apigateway/test/integ.cors-allow-multiple-origins.js.snapshot/integcorsallowmultipleoriginsDefaultTestDeployAssertEBF0A1B1.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-apigateway/test/integ.cors-allow-multiple-origins.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-apigateway/test/integ.cors-allow-multiple-origins.js.snapshot/stack-cors-allow-multiple-origins.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-apigateway/test/integ.cors-allow-multiple-origins.js.snapshot/stack-cors-allow-multiple-origins.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-apigateway/test/integ.cors-allow-multiple-origins.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-apigateway/test/integ.cors-allow-multiple-origins.ts
  packages/@aws-cdk-testing/framework-integ/test/aws-apigateway/test/integ.cors.js.snapshot/cors-twitch-test.template.json
  packages/aws-cdk-lib/aws-apigateway/lib/resource.ts
  packages/aws-cdk-lib/aws-apigateway/test/cors.test.ts
Labels: bug, p1, effort/small, star-contributor

#26652 feat(cdk): `cdk diff --quiet` suppresses progress messages
  packages/@aws-cdk-testing/cli-integ/tests/cli-integ-tests/cli.integtest.ts
  packages/aws-cdk/README.md
  packages/aws-cdk/lib/cdk-toolkit.ts
  packages/aws-cdk/lib/cli.ts
  packages/aws-cdk/lib/diff.ts
  packages/aws-cdk/test/diff.test.ts
Labels: p1, feature-request, effort/small, pr-linter/exempt-integ-test, beginning-contributor, pr-linter/cli-integ-tested

#26621 docs(custom-resource): add example for AwsApiCall
  packages/aws-cdk-lib/custom-resources/lib/aws-custom-resource/aws-custom-resource.ts
Labels: p2, repeat-contributor

#26704 revert: "chore(ground-station): Scaffold AWS Ground Station alpha"
  packages/@aws-cdk/aws-groundstation-alpha/.eslintrc.js
  packages/@aws-cdk/aws-groundstation-alpha/.gitignore
  packages/@aws-cdk/aws-groundstation-alpha/.npmignore
  packages/@aws-cdk/aws-groundstation-alpha/LICENSE
  packages/@aws-cdk/aws-groundstation-alpha/NOTICE
  packages/@aws-cdk/aws-groundstation-alpha/README.md
  packages/@aws-cdk/aws-groundstation-alpha/jest.config.js
  packages/@aws-cdk/aws-groundstation-alpha/lib/index.ts
  packages/@aws-cdk/aws-groundstation-alpha/package.json
  packages/@aws-cdk/aws-groundstation-alpha/rosetta/default.ts-fixture
Labels: p2, contribution/core

#26679 fix(sam): CfnFunction events are not rendered
  packages/aws-cdk-lib/aws-sam/test/l1/sam.test.ts
  tools/@aws-cdk/spec2cdk/jest.config.js
  tools/@aws-cdk/spec2cdk/lib/cdk/cloudformation-mapping.ts
  tools/@aws-cdk/spec2cdk/lib/cdk/resource-class.ts
  tools/@aws-cdk/spec2cdk/lib/cdk/type-converter.ts
  tools/@aws-cdk/spec2cdk/lib/cdk/typedefinition-struct.ts
  tools/@aws-cdk/spec2cdk/lib/cdk/union-ordering.ts
  tools/@aws-cdk/spec2cdk/lib/util/sets.ts
  tools/@aws-cdk/spec2cdk/lib/util/toposort.ts
Labels: p2, contribution/core, pr-linter/exempt-integ-test

#26705 chore(deps): pin jsii to 1.85.0
  package.json
  packages/@aws-cdk/cli-lib-alpha/THIRD_PARTY_LICENSES
  packages/@aws-cdk/integ-runner/THIRD_PARTY_LICENSES
  packages/aws-cdk/THIRD_PARTY_LICENSES
  packages/aws-cdk/package.json
  packages/awslint/package.json
  tools/@aws-cdk/cdk-build-tools/package.json
  tools/@aws-cdk/cfn2ts/package.json
  yarn.lock
Labels: p2, contribution/core

#26696 feat(glue): Job construct does not honor SparkUIProps S3 prefix when granting S3 access
  packages/@aws-cdk/aws-glue-alpha/README.md
  packages/@aws-cdk/aws-glue-alpha/lib/job.ts
  packages/@aws-cdk/aws-glue-alpha/test/job.test.ts
Labels: bug, p2, effort/small, contribution/core, pr-linter/exempt-integ-test

#26713 chore(merge-back): 2.91.0
  CHANGELOG.v2.alpha.md
  CHANGELOG.v2.md
  version.v2.json
Labels: p2, pr/needs-community-review, pr/no-squash, auto-approve

#26706 chore: update mergify and github-merit-badger
  .github/workflows/github-merit-badger.yml
  .mergify.yml
Labels: p2, contribution/core

#26722 chore(deps): upgrade to @aws-cdk/node-proxy-agent-v6
  packages/aws-cdk-lib/lambda-layer-node-proxy-agent/lib/node-proxy-agent-layer.ts
  packages/aws-cdk-lib/package.json
  tools/@aws-cdk/pkglint/lib/rules.ts
  yarn.lock
Labels: p2, contribution/core

#26731 feat(batch): set default spot allocation strategy to `SPOT_PRICE_CAPACITY_OPTIMIZED`
  packages/@aws-cdk/aws-batch-alpha/README.md
  packages/@aws-cdk/aws-batch-alpha/lib/managed-compute-environment.ts
  packages/@aws-cdk/aws-batch-alpha/test/integ.managed-compute-environment.js.snapshot/BatchManagedComputeEnvironmentTestDefaultTestDeployAssertD4528F80.assets.json
  packages/@aws-cdk/aws-batch-alpha/test/integ.managed-compute-environment.js.snapshot/batch-stack.assets.json
  packages/@aws-cdk/aws-batch-alpha/test/integ.managed-compute-environment.js.snapshot/batch-stack.template.json
  packages/@aws-cdk/aws-batch-alpha/test/integ.managed-compute-environment.js.snapshot/cdk.out
  packages/@aws-cdk/aws-batch-alpha/test/integ.managed-compute-environment.js.snapshot/integ.json
  packages/@aws-cdk/aws-batch-alpha/test/integ.managed-compute-environment.js.snapshot/manifest.json
  packages/@aws-cdk/aws-batch-alpha/test/integ.managed-compute-environment.js.snapshot/tree.json
  packages/@aws-cdk/aws-batch-alpha/test/integ.managed-compute-environment.ts
  packages/@aws-cdk/aws-batch-alpha/test/managed-compute-environment.test.ts
Labels: p2, contribution/core

#26673 feat(opensearchservice): SAML authorization properties for Domain construct
  packages/@aws-cdk-testing/framework-integ/test/aws-opensearchservice/test/integ.opensearch.advancedsecurity-with-saml.js.snapshot/cdk-opensearch-advancedsecurity-with-saml.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-opensearchservice/test/integ.opensearch.advancedsecurity-with-saml.js.snapshot/cdk-opensearch-advancedsecurity-with-saml.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-opensearchservice/test/integ.opensearch.advancedsecurity-with-saml.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-opensearchservice/test/integ.opensearch.advancedsecurity-with-saml.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-opensearchservice/test/integ.opensearch.advancedsecurity-with-saml.js.snapshot/integopensearchadvancedsecuritywithsamlDefaultTestDeployAssertA27B274A.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-opensearchservice/test/integ.opensearch.advancedsecurity-with-saml.js.snapshot/integopensearchadvancedsecuritywithsamlDefaultTestDeployAssertA27B274A.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-opensearchservice/test/integ.opensearch.advancedsecurity-with-saml.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-opensearchservice/test/integ.opensearch.advancedsecurity-with-saml.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-opensearchservice/test/integ.opensearch.advancedsecurity-with-saml.ts
  packages/@aws-cdk-testing/framework-integ/test/aws-opensearchservice/test/saml-metadata-document.xml
  packages/aws-cdk-lib/aws-opensearchservice/README.md
  packages/aws-cdk-lib/aws-opensearchservice/lib/domain.ts
  packages/aws-cdk-lib/aws-opensearchservice/test/domain.test.ts
Labels: p2, feature-request, effort/medium, star-contributor

#26734 chore: npm-check-updates && yarn upgrade
  package.json
  packages/@aws-cdk-testing/cli-integ/package.json
  packages/@aws-cdk-testing/framework-integ/package.json
  packages/@aws-cdk-testing/framework-integ/test/aws-eks/test/sdk-call-integ-test-docker-app/app/package.json
  packages/@aws-cdk/aws-amplify-alpha/package.json
  packages/@aws-cdk/aws-redshift-alpha/package.json
  packages/@aws-cdk/custom-resource-handlers/package.json
  packages/@aws-cdk/integ-runner/THIRD_PARTY_LICENSES
  packages/@aws-cdk/integ-tests-alpha/package.json
  packages/aws-cdk-lib/package.json
  packages/aws-cdk/THIRD_PARTY_LICENSES
  packages/aws-cdk/lib/init-templates/app/typescript/package.json
  packages/aws-cdk/lib/init-templates/lib/typescript/package.json
  packages/aws-cdk/lib/init-templates/sample-app/typescript/package.json
  packages/aws-cdk/package.json
  packages/awslint/package.json
  packages/cdk-assets/package.json
  tools/@aws-cdk/cdk-build-tools/package.json
  tools/@aws-cdk/cfn2ts/package.json
  tools/@aws-cdk/node-bundle/package.json
  yarn.lock
Labels: p2, dependencies, contribution/core, auto-approve

#26729 feat(batch): grantSubmitJob method
  packages/@aws-cdk/aws-batch-alpha/README.md
  packages/@aws-cdk/aws-batch-alpha/lib/ecs-job-definition.ts
  packages/@aws-cdk/aws-batch-alpha/test/ecs-job-definition.test.ts
  packages/@aws-cdk/aws-batch-alpha/test/integ.grants.js.snapshot/BatchEcsJobDefinitionTestDefaultTestDeployAssertE5BAAC9B.assets.json
  packages/@aws-cdk/aws-batch-alpha/test/integ.grants.js.snapshot/BatchEcsJobDefinitionTestDefaultTestDeployAssertE5BAAC9B.template.json
  packages/@aws-cdk/aws-batch-alpha/test/integ.grants.js.snapshot/cdk.out
  packages/@aws-cdk/aws-batch-alpha/test/integ.grants.js.snapshot/integ.json
  packages/@aws-cdk/aws-batch-alpha/test/integ.grants.js.snapshot/manifest.json
  packages/@aws-cdk/aws-batch-alpha/test/integ.grants.js.snapshot/stack.assets.json
  packages/@aws-cdk/aws-batch-alpha/test/integ.grants.js.snapshot/stack.template.json
  packages/@aws-cdk/aws-batch-alpha/test/integ.grants.js.snapshot/tree.json
  packages/@aws-cdk/aws-batch-alpha/test/integ.grants.ts
Labels: bug, p1, contribution/core

#26727 chore(lambda-python-alpha): remove default doc from required prop
  packages/@aws-cdk/aws-lambda-python-alpha/lib/function.ts
Labels: p2, contribution/core

#26762 chore: pr-linter/do-not-close never worked
  .github/workflows/close-stale-prs.yml
Labels: p2, contribution/core

#26764 chore(merge-back): 2.92.0
  CHANGELOG.v2.alpha.md
  CHANGELOG.v2.md
  version.v2.json
Labels: p2, pr/needs-community-review, pr/no-squash, auto-approve

#26765 chore(prlint): account for same user with multiple reviews
  tools/@aws-cdk/prlint/lint.ts
  tools/@aws-cdk/prlint/test/lint.test.ts
Labels: p2, contribution/core

#26775 chore: npm-check-updates && yarn upgrade
  package.json
  packages/@aws-cdk-testing/cli-integ/package.json
  packages/@aws-cdk-testing/framework-integ/package.json
  packages/@aws-cdk-testing/framework-integ/test/aws-eks/test/sdk-call-integ-test-docker-app/app/package.json
  packages/@aws-cdk/aws-amplify-alpha/package.json
  packages/@aws-cdk/aws-redshift-alpha/package.json
  packages/@aws-cdk/custom-resource-handlers/package.json
  packages/@aws-cdk/integ-runner/THIRD_PARTY_LICENSES
  packages/@aws-cdk/integ-tests-alpha/package.json
  packages/aws-cdk-lib/package.json
  packages/aws-cdk/THIRD_PARTY_LICENSES
  packages/aws-cdk/lib/init-templates/app/typescript/package.json
  packages/aws-cdk/lib/init-templates/lib/typescript/package.json
  packages/aws-cdk/lib/init-templates/sample-app/typescript/package.json
  packages/aws-cdk/package.json
  packages/cdk-assets/package.json
  tools/@aws-cdk/node-bundle/package.json
  yarn.lock
Labels: p2, dependencies, contribution/core, auto-approve

#26763 fix: lambda-nodejs default runtime regression
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-nodejs/test/integ.latest.js.snapshot/LambdaNodeJsLatestIntegDefaultTestDeployAssertD40B5C28.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-nodejs/test/integ.latest.js.snapshot/LambdaNodeJsLatestIntegDefaultTestDeployAssertD40B5C28.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-nodejs/test/integ.latest.js.snapshot/asset.50a8879346510e33e69a511e29d588e7b2d2b477b6989a4db677027bb8605b9f/index.js
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-nodejs/test/integ.latest.js.snapshot/asset.50a8879346510e33e69a511e29d588e7b2d2b477b6989a4db677027bb8605b9f/node_modules/.yarn-integrity
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-nodejs/test/integ.latest.js.snapshot/asset.50a8879346510e33e69a511e29d588e7b2d2b477b6989a4db677027bb8605b9f/node_modules/delay/index.d.ts
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-nodejs/test/integ.latest.js.snapshot/asset.50a8879346510e33e69a511e29d588e7b2d2b477b6989a4db677027bb8605b9f/node_modules/delay/index.js
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-nodejs/test/integ.latest.js.snapshot/asset.50a8879346510e33e69a511e29d588e7b2d2b477b6989a4db677027bb8605b9f/node_modules/delay/license
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-nodejs/test/integ.latest.js.snapshot/asset.50a8879346510e33e69a511e29d588e7b2d2b477b6989a4db677027bb8605b9f/node_modules/delay/package.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-nodejs/test/integ.latest.js.snapshot/asset.50a8879346510e33e69a511e29d588e7b2d2b477b6989a4db677027bb8605b9f/node_modules/delay/readme.md
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-nodejs/test/integ.latest.js.snapshot/asset.50a8879346510e33e69a511e29d588e7b2d2b477b6989a4db677027bb8605b9f/package.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-nodejs/test/integ.latest.js.snapshot/asset.50a8879346510e33e69a511e29d588e7b2d2b477b6989a4db677027bb8605b9f/yarn.lock
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-nodejs/test/integ.latest.js.snapshot/asset.fc4da43a214bb79ca557ca6c54e8dfcc4f2aabbd6672873b7b3ea417576612f5.bundle/index.js
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-nodejs/test/integ.latest.js.snapshot/cdk-integ-lambda-nodejs-latest.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-nodejs/test/integ.latest.js.snapshot/cdk-integ-lambda-nodejs-latest.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-nodejs/test/integ.latest.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-nodejs/test/integ.latest.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-nodejs/test/integ.latest.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-nodejs/test/integ.latest.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-nodejs/test/integ.latest.ts
  packages/@aws-cdk/cx-api/FEATURE_FLAGS.md
  packages/aws-cdk-lib/aws-lambda-nodejs/README.md
  packages/aws-cdk-lib/aws-lambda-nodejs/lib/bundling.ts
  packages/aws-cdk-lib/aws-lambda-nodejs/lib/function.ts
  packages/aws-cdk-lib/aws-lambda-nodejs/lib/types.ts
  packages/aws-cdk-lib/aws-lambda-nodejs/test/bundling.test.ts
  packages/aws-cdk-lib/aws-lambda-nodejs/test/function.test.ts
  packages/aws-cdk-lib/aws-lambda/lib/runtime.ts
  packages/aws-cdk-lib/cx-api/FEATURE_FLAGS.md
  packages/aws-cdk-lib/cx-api/README.md
  packages/aws-cdk-lib/cx-api/lib/features.ts
Labels: bug, p1, contribution/core

#26781 chore(cloudwatch): correct spelling error in alarm-base docstrings
  packages/aws-cdk-lib/aws-cloudwatch/lib/alarm-base.ts
Labels: p2, pr/needs-community-review, beginning-contributor

#26782 fix(eks): undefined constructor in custom resource
  packages/@aws-cdk-testing/framework-integ/test/aws-eks/test/integ.eks-cluster.js.snapshot/asset.3f579d6c1ab146cac713730c96809dd4a9c5d9750440fb835ab20fd6925e528c.zip
  packages/@aws-cdk-testing/framework-integ/test/aws-eks/test/integ.eks-cluster.js.snapshot/asset.9202bb21d52e07810fc1da0f6acf2dcb75a40a43a9a2efbcfc9ae39535c6260c.zip
  packages/@aws-cdk-testing/framework-integ/test/aws-eks/test/integ.eks-cluster.js.snapshot/asset.acb2f8cda93fc5e8f324cbdf29471a1182441f7707645a562b4d29eb57c80eea/cluster.d.ts
  packages/@aws-cdk-testing/framework-integ/test/aws-eks/test/integ.eks-cluster.js.snapshot/asset.acb2f8cda93fc5e8f324cbdf29471a1182441f7707645a562b4d29eb57c80eea/cluster.js
  packages/@aws-cdk-testing/framework-integ/test/aws-eks/test/integ.eks-cluster.js.snapshot/asset.acb2f8cda93fc5e8f324cbdf29471a1182441f7707645a562b4d29eb57c80eea/cluster.ts
  packages/@aws-cdk-testing/framework-integ/test/aws-eks/test/integ.eks-cluster.js.snapshot/asset.acb2f8cda93fc5e8f324cbdf29471a1182441f7707645a562b4d29eb57c80eea/common.d.ts
  packages/@aws-cdk-testing/framework-integ/test/aws-eks/test/integ.eks-cluster.js.snapshot/asset.acb2f8cda93fc5e8f324cbdf29471a1182441f7707645a562b4d29eb57c80eea/common.js
  packages/@aws-cdk-testing/framework-integ/test/aws-eks/test/integ.eks-cluster.js.snapshot/asset.acb2f8cda93fc5e8f324cbdf29471a1182441f7707645a562b4d29eb57c80eea/common.ts
  packages/@aws-cdk-testing/framework-integ/test/aws-eks/test/integ.eks-cluster.js.snapshot/asset.acb2f8cda93fc5e8f324cbdf29471a1182441f7707645a562b4d29eb57c80eea/compareLogging.d.ts
  packages/@aws-cdk-testing/framework-integ/test/aws-eks/test/integ.eks-cluster.js.snapshot/asset.acb2f8cda93fc5e8f324cbdf29471a1182441f7707645a562b4d29eb57c80eea/compareLogging.js
  packages/@aws-cdk-testing/framework-integ/test/aws-eks/test/integ.eks-cluster.js.snapshot/asset.acb2f8cda93fc5e8f324cbdf29471a1182441f7707645a562b4d29eb57c80eea/compareLogging.ts
  packages/@aws-cdk-testing/framework-integ/test/aws-eks/test/integ.eks-cluster.js.snapshot/asset.acb2f8cda93fc5e8f324cbdf29471a1182441f7707645a562b4d29eb57c80eea/consts.d.ts
  packages/@aws-cdk-testing/framework-integ/test/aws-eks/test/integ.eks-cluster.js.snapshot/asset.acb2f8cda93fc5e8f324cbdf29471a1182441f7707645a562b4d29eb57c80eea/consts.js
  packages/@aws-cdk-testing/framework-integ/test/aws-eks/test/integ.eks-cluster.js.snapshot/asset.acb2f8cda93fc5e8f324cbdf29471a1182441f7707645a562b4d29eb57c80eea/consts.ts
  packages/@aws-cdk-testing/framework-integ/test/aws-eks/test/integ.eks-cluster.js.snapshot/asset.acb2f8cda93fc5e8f324cbdf29471a1182441f7707645a562b4d29eb57c80eea/fargate.d.ts
  packages/@aws-cdk-testing/framework-integ/test/aws-eks/test/integ.eks-cluster.js.snapshot/asset.acb2f8cda93fc5e8f324cbdf29471a1182441f7707645a562b4d29eb57c80eea/fargate.js
  packages/@aws-cdk-testing/framework-integ/test/aws-eks/test/integ.eks-cluster.js.snapshot/asset.acb2f8cda93fc5e8f324cbdf29471a1182441f7707645a562b4d29eb57c80eea/fargate.ts
  packages/@aws-cdk-testing/framework-integ/test/aws-eks/test/integ.eks-cluster.js.snapshot/asset.acb2f8cda93fc5e8f324cbdf29471a1182441f7707645a562b4d29eb57c80eea/index.d.ts
  packages/@aws-cdk-testing/framework-integ/test/aws-eks/test/integ.eks-cluster.js.snapshot/asset.acb2f8cda93fc5e8f324cbdf29471a1182441f7707645a562b4d29eb57c80eea/index.js
  packages/@aws-cdk-testing/framework-integ/test/aws-eks/test/integ.eks-cluster.js.snapshot/asset.acb2f8cda93fc5e8f324cbdf29471a1182441f7707645a562b4d29eb57c80eea/index.ts
  packages/@aws-cdk-testing/framework-integ/test/aws-eks/test/integ.eks-cluster.js.snapshot/asset.bb544555825b6abfdf2cf0c13f9410a77d62ad0fe0bf5c38cef55631cf427f31/index.js
  packages/@aws-cdk-testing/framework-integ/test/aws-eks/test/integ.eks-cluster.js.snapshot/aws-cdk-eks-cluster-test.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-eks/test/integ.eks-cluster.js.snapshot/aws-cdk-eks-cluster-test.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-eks/test/integ.eks-cluster.js.snapshot/awscdkeksclustertestawscdkawseksClusterResourceProvider5F388D1A.nested.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-eks/test/integ.eks-cluster.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-eks/test/integ.eks-cluster.js.snapshot/tree.json
  packages/aws-cdk-lib/aws-eks/lib/cluster-resource-handler/index.ts
Labels: p2, contribution/core

#26404 fix(cli): cannot hotswap ECS task definitions containing certain intrinsics
  packages/aws-cdk/lib/api/hotswap/common.ts
  packages/aws-cdk/lib/api/hotswap/ecs-services.ts
  packages/aws-cdk/test/api/hotswap/ecs-services-hotswap-deployments.test.ts
Labels: p1, feature-request, effort/medium, pr-linter/exempt-integ-test, admired-contributor, pr-linter/cli-integ-tested, pr/needs-maintainer-review

#26777 fix(lambda): use of `currentVersion` fails deployment after upgrade
  packages/aws-cdk-lib/aws-lambda/lib/function-hash.ts
  packages/aws-cdk-lib/aws-lambda/test/function.test.ts
  packages/aws-cdk-lib/aws-lambda/test/x.zip
Labels: bug, p0, effort/medium, contribution/core, pr-linter/exempt-integ-test

#26636 fix(apigateway): duplicate methodResponses if the same array is reused between addMethod calls
  packages/@aws-cdk-testing/framework-integ/test/aws-apigateway/test/integ.stepfunctions-startexecution.js.snapshot/aws-cdk-aws-apigateway-stepfunctions-startexecution.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-apigateway/test/integ.stepfunctions-startexecution.js.snapshot/aws-cdk-aws-apigateway-stepfunctions-startexecution.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-apigateway/test/integ.stepfunctions-startexecution.js.snapshot/awsapigatewaystepfunctionsstartexecutionDefaultTestDeployAssert3A9ACD49.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-apigateway/test/integ.stepfunctions-startexecution.js.snapshot/awsapigatewaystepfunctionsstartexecutionDefaultTestDeployAssert3A9ACD49.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-apigateway/test/integ.stepfunctions-startexecution.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-apigateway/test/integ.stepfunctions-startexecution.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-apigateway/test/integ.stepfunctions-startexecution.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-apigateway/test/integ.stepfunctions-startexecution.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-apigateway/test/integ.stepfunctions-startexecution.ts
  packages/aws-cdk-lib/aws-apigateway/lib/integrations/stepfunctions.ts
  packages/aws-cdk-lib/aws-apigateway/lib/method.ts
  packages/aws-cdk-lib/aws-apigateway/test/integrations/stepfunctions.test.ts
Labels: bug, p1, effort/medium, star-contributor

#26742 fix(ecr): autoDeleteImages fails when repository is renamed
  packages/@aws-cdk-testing/framework-integ/test/aws-ecr/test/integ.repository-auto-delete-images.js.snapshot/aws-ecr-integ-stack.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecr/test/integ.repository-auto-delete-images.js.snapshot/aws-ecr-integ-stack.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecr/test/integ.repository-auto-delete-images.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecr/test/integ.repository-auto-delete-images.js.snapshot/tree.json
  packages/@aws-cdk/app-staging-synthesizer-alpha/test/integ.synth-default-resources.js.snapshot/StagingStack-default-resourcesmax-ACCOUNT-REGION.template.json
  packages/aws-cdk-lib/aws-ecr/lib/repository.ts
  packages/aws-cdk-lib/aws-ecr/test/repository.test.ts
Labels: bug, p1, effort/medium, pr-linter/exempt-integ-test, valued-contributor, pr-linter/exemption-requested

#26784 docs(iot): fix CloudWatch Metric example
  packages/@aws-cdk/aws-iot-actions-alpha/README.md
Labels: p2, contribution/core

#26789 fix(redshift): adding distKey to an existing table fails deployment
  packages/@aws-cdk/aws-redshift-alpha/lib/private/database-query-provider/table.ts
  packages/@aws-cdk/aws-redshift-alpha/test/database-query-provider/table.test.ts
  packages/@aws-cdk/aws-redshift-alpha/test/integ.cluster-distkey.js.snapshot/asset.73b60c2cf141bf58c33cfaa33858f5c84103a0232ba7192d696536488f7731c4/cfn-response.js
  packages/@aws-cdk/aws-redshift-alpha/test/integ.cluster-distkey.js.snapshot/asset.73b60c2cf141bf58c33cfaa33858f5c84103a0232ba7192d696536488f7731c4/consts.js
  packages/@aws-cdk/aws-redshift-alpha/test/integ.cluster-distkey.js.snapshot/asset.73b60c2cf141bf58c33cfaa33858f5c84103a0232ba7192d696536488f7731c4/framework.js
  packages/@aws-cdk/aws-redshift-alpha/test/integ.cluster-distkey.js.snapshot/asset.73b60c2cf141bf58c33cfaa33858f5c84103a0232ba7192d696536488f7731c4/outbound.js
  packages/@aws-cdk/aws-redshift-alpha/test/integ.cluster-distkey.js.snapshot/asset.73b60c2cf141bf58c33cfaa33858f5c84103a0232ba7192d696536488f7731c4/util.js
  packages/@aws-cdk/aws-redshift-alpha/test/integ.cluster-distkey.js.snapshot/asset.95dfca0d51dadef71390a414c093b29c52f39e1ff2acef2a26ded36e756bf386/handler-name.js
  packages/@aws-cdk/aws-redshift-alpha/test/integ.cluster-distkey.js.snapshot/asset.95dfca0d51dadef71390a414c093b29c52f39e1ff2acef2a26ded36e756bf386/index.js
  packages/@aws-cdk/aws-redshift-alpha/test/integ.cluster-distkey.js.snapshot/asset.95dfca0d51dadef71390a414c093b29c52f39e1ff2acef2a26ded36e756bf386/privileges.js
  packages/@aws-cdk/aws-redshift-alpha/test/integ.cluster-distkey.js.snapshot/asset.95dfca0d51dadef71390a414c093b29c52f39e1ff2acef2a26ded36e756bf386/redshift-data.js
  packages/@aws-cdk/aws-redshift-alpha/test/integ.cluster-distkey.js.snapshot/asset.95dfca0d51dadef71390a414c093b29c52f39e1ff2acef2a26ded36e756bf386/table.js
  packages/@aws-cdk/aws-redshift-alpha/test/integ.cluster-distkey.js.snapshot/asset.95dfca0d51dadef71390a414c093b29c52f39e1ff2acef2a26ded36e756bf386/types.js
  packages/@aws-cdk/aws-redshift-alpha/test/integ.cluster-distkey.js.snapshot/asset.95dfca0d51dadef71390a414c093b29c52f39e1ff2acef2a26ded36e756bf386/user.js
  packages/@aws-cdk/aws-redshift-alpha/test/integ.cluster-distkey.js.snapshot/asset.95dfca0d51dadef71390a414c093b29c52f39e1ff2acef2a26ded36e756bf386/util.js
  packages/@aws-cdk/aws-redshift-alpha/test/integ.cluster-distkey.js.snapshot/aws-cdk-redshift-distkey-create.assets.json
  packages/@aws-cdk/aws-redshift-alpha/test/integ.cluster-distkey.js.snapshot/aws-cdk-redshift-distkey-create.template.json
  packages/@aws-cdk/aws-redshift-alpha/test/integ.cluster-distkey.js.snapshot/aws-cdk-redshift-distkey-update.assets.json
  packages/@aws-cdk/aws-redshift-alpha/test/integ.cluster-distkey.js.snapshot/aws-cdk-redshift-distkey-update.template.json
  packages/@aws-cdk/aws-redshift-alpha/test/integ.cluster-distkey.js.snapshot/awscdkredshiftdistkeytestDefaultTestDeployAssert61A36BE8.assets.json
  packages/@aws-cdk/aws-redshift-alpha/test/integ.cluster-distkey.js.snapshot/awscdkredshiftdistkeytestDefaultTestDeployAssert61A36BE8.template.json
  packages/@aws-cdk/aws-redshift-alpha/test/integ.cluster-distkey.js.snapshot/cdk.out
  packages/@aws-cdk/aws-redshift-alpha/test/integ.cluster-distkey.js.snapshot/integ.json
  packages/@aws-cdk/aws-redshift-alpha/test/integ.cluster-distkey.js.snapshot/manifest.json
  packages/@aws-cdk/aws-redshift-alpha/test/integ.cluster-distkey.js.snapshot/tree.json
  packages/@aws-cdk/aws-redshift-alpha/test/integ.cluster-distkey.ts
Labels: bug, p1, effort/small, star-contributor

#26770 refactor(stepfunctions): deprecate unused DISCARD variable and include JsonPath.DISCARD in docs
  packages/aws-cdk-lib/aws-stepfunctions/lib/states/choice.ts
  packages/aws-cdk-lib/aws-stepfunctions/lib/states/state.ts
  packages/aws-cdk-lib/aws-stepfunctions/lib/types.ts
Labels: bug, p2, effort/small, beginning-contributor

#26792 chore(spec2cdk): assertTruthy error message typo
  tools/@aws-cdk/spec2cdk/lib/cdk/union-ordering.ts
Labels: p2, beginning-contributor

#26656 feat(app-staging-synthesizer): enable tag immutability
  packages/@aws-cdk/app-staging-synthesizer-alpha/lib/default-staging-stack.ts
  packages/@aws-cdk/app-staging-synthesizer-alpha/test/integ.synth-default-resources.js.snapshot/StagingStack-default-resourcesmax-ACCOUNT-REGION.template.json
  packages/@aws-cdk/app-staging-synthesizer-alpha/test/integ.synth-default-resources.js.snapshot/tree.json
Labels: p2, feature-request, effort/small, pr-linter/exempt-readme, pr-linter/exempt-test, pr-linter/exempt-integ-test, beginning-contributor

#26793 feat(aws-cdk-lib): ADOT Lambda Layer v0.32.0
  packages/aws-cdk-lib/region-info/build-tools/fact-tables.ts
Labels: p2, pr/needs-community-review, pr-linter/exempt-readme, pr-linter/exempt-test, pr-linter/exempt-integ-test, beginning-contributor

#26737 chore(ecs-patterns): ScheduledFargateTaskProps is exposing unused props from FargateServiceBaseProps
  packages/aws-cdk-lib/aws-ecs-patterns/lib/fargate/scheduled-fargate-task.ts
  packages/aws-cdk-lib/aws-ecs-patterns/test/fargate/scheduled-fargate-task.test.ts
Labels: bug, p1, effort/small, star-contributor

#26756 fix: aws-sdk still used in EKS custom resources
  packages/aws-cdk-lib/aws-eks/lib/cluster-resource-handler/cluster.ts
  packages/aws-cdk-lib/aws-eks/lib/cluster-resource-handler/common.ts
  packages/aws-cdk-lib/aws-eks/lib/cluster-resource-handler/compareLogging.ts
  packages/aws-cdk-lib/aws-eks/lib/cluster-resource-handler/fargate.ts
  packages/aws-cdk-lib/aws-eks/test/cluster-resource-handler-mocks.ts
Labels: p2, contribution/core, pr-linter/exempt-integ-test

#26592 chore(codebuild): improve the doc for subnetSelection
  packages/aws-cdk-lib/aws-codebuild/lib/project.ts
Labels: p2, contribution/core

#26767 fix(assertions): stack overflow while parsing template
  packages/aws-cdk-lib/assertions/lib/private/cyclic.ts
  packages/aws-cdk-lib/assertions/test/template.test.ts
Labels: bug, p2, effort/medium, pr-linter/exempt-integ-test, admired-contributor

#26791 fix(cloudformation-diff): fails on CloudFormation intrinsics in unexpected places
  packages/@aws-cdk/cloudformation-diff/lib/diff/maybe-parsed.ts
  packages/@aws-cdk/cloudformation-diff/lib/diff/util.ts
  packages/@aws-cdk/cloudformation-diff/lib/iam/iam-changes.ts
  packages/@aws-cdk/cloudformation-diff/lib/iam/managed-policy.ts
  packages/@aws-cdk/cloudformation-diff/lib/iam/statement.ts
  packages/@aws-cdk/cloudformation-diff/lib/network/security-group-changes.ts
  packages/@aws-cdk/cloudformation-diff/lib/network/security-group-rule.ts
  packages/@aws-cdk/cloudformation-diff/package.json
  packages/@aws-cdk/cloudformation-diff/test/diff-template.test.ts
  packages/@aws-cdk/cloudformation-diff/test/iam/detect-changes.test.ts
  packages/@aws-cdk/cloudformation-diff/test/iam/statement.test.ts
  packages/@aws-cdk/cloudformation-diff/test/network/rule.test.ts
  packages/@aws-cdk/cloudformation-diff/test/test-arbitraries.ts
  packages/aws-cdk-lib/aws-applicationautoscaling/test/util.ts
  packages/aws-cdk-lib/aws-autoscaling-common/test/util.ts
  packages/aws-cdk-lib/core/test/fn.test.ts
  packages/aws-cdk-lib/package.json
  packages/aws-cdk/package.json
  yarn.lock
Labels: bug, p1, effort/medium, contribution/core, pr-linter/exempt-integ-test

#26776 chore(ec2): add M7gd, R7gd, C7gd instance types
  packages/aws-cdk-lib/aws-ec2/lib/instance-types.ts
  packages/aws-cdk-lib/aws-ec2/test/instance.test.ts
Labels: p2, feature-request, effort/small, beginning-contributor, pr/reviewer-clarification-requested

#26333 feat(route53): add support for grantDelegation on imported PublicHostedZone
  packages/@aws-cdk-testing/framework-integ/test/aws-route53/test/integ.cross-account-zone-delegation.js.snapshot/aws-cdk-route53-cross-account-integ.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-route53/test/integ.cross-account-zone-delegation.js.snapshot/aws-cdk-route53-cross-account-integ.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-route53/test/integ.cross-account-zone-delegation.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-route53/test/integ.cross-account-zone-delegation.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-route53/test/integ.cross-account-zone-delegation.ts
  packages/aws-cdk-lib/aws-ec2/README.md
  packages/aws-cdk-lib/aws-route53/README.md
  packages/aws-cdk-lib/aws-route53/lib/hosted-zone.ts
  packages/aws-cdk-lib/aws-route53/lib/util.ts
  packages/aws-cdk-lib/aws-route53/test/hosted-zone.test.ts
Labels: p2, feature-request, effort/small, star-contributor

#26805 docs(events-targets): add link for Run an ECS task section
  packages/aws-cdk-lib/aws-events-targets/README.md
Labels: p2, valued-contributor

#26512 fix(secretsmanager): rotation resource creation can fail due to race condition
  packages/@aws-cdk-testing/framework-integ/test/aws-secretsmanager/test/integ.lambda-rotation.js.snapshot/cdk-integ-secret-lambda-rotation.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-secretsmanager/test/integ.lambda-rotation.ts
  packages/aws-cdk-lib/aws-secretsmanager/lib/rotation-schedule.ts
  packages/aws-cdk-lib/aws-secretsmanager/test/rotation-schedule.test.ts
Labels: bug, p2, effort/small, star-contributor

#26796 fix(CLI): diff reports wrong count of changed stacks
  packages/aws-cdk/lib/api/deployments.ts
  packages/aws-cdk/lib/api/nested-stack-helpers.ts
  packages/aws-cdk/lib/cdk-toolkit.ts
  packages/aws-cdk/test/api/cloudformation-deployments.test.ts
  packages/aws-cdk/test/diff.test.ts
Labels: bug, p1, effort/small, contribution/core, pr-linter/exempt-integ-test, pr-linter/cli-integ-tested

#26800 fix(ecr): AutoDeleteImages custom resource description contains "undefined"
  packages/@aws-cdk-testing/framework-integ/test/aws-ecr/test/integ.repository-auto-delete-images.js.snapshot/aws-ecr-integ-stack.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecr/test/integ.repository-auto-delete-images.js.snapshot/aws-ecr-integ-stack.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecr/test/integ.repository-auto-delete-images.js.snapshot/manifest.json
  packages/@aws-cdk/app-staging-synthesizer-alpha/test/integ.synth-default-resources.js.snapshot/StagingStack-default-resourcesmax-ACCOUNT-REGION.template.json
  packages/@aws-cdk/app-staging-synthesizer-alpha/test/integ.synth-default-resources.js.snapshot/tree.json
  packages/aws-cdk-lib/aws-ecr/lib/repository.ts
  packages/aws-cdk-lib/aws-ecr/test/repository.test.ts
Labels: p2, pr-linter/exempt-test, pr-linter/exempt-integ-test, valued-contributor

#26825 feat: update AWS Service Spec
  allowed-breaking-changes.txt
  tools/@aws-cdk/spec2cdk/lib/cdk/typedefinition-struct.ts
  tools/@aws-cdk/spec2cdk/package.json
  yarn.lock
Labels: p2, dependencies, contribution/core, pr-linter/exempt-readme, pr-linter/exempt-test, auto-approve, pr-linter/exempt-integ-test

#26692 feat(ecs): container port ranges in port mappings
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs/test/fargate/integ.container-port-range.js.snapshot/EcsContainerPortRangeDefaultTestDeployAssert87C0580C.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs/test/fargate/integ.container-port-range.js.snapshot/EcsContainerPortRangeDefaultTestDeployAssert87C0580C.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs/test/fargate/integ.container-port-range.js.snapshot/asset.ba598c1f1d84f7077ea9c16a6b921e4f8acf18e996100e72a8f17da980e64fdd/__entrypoint__.js
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs/test/fargate/integ.container-port-range.js.snapshot/asset.ba598c1f1d84f7077ea9c16a6b921e4f8acf18e996100e72a8f17da980e64fdd/index.js
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs/test/fargate/integ.container-port-range.js.snapshot/aws-ecs-container-port-range.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs/test/fargate/integ.container-port-range.js.snapshot/aws-ecs-container-port-range.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs/test/fargate/integ.container-port-range.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs/test/fargate/integ.container-port-range.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs/test/fargate/integ.container-port-range.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs/test/fargate/integ.container-port-range.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs/test/fargate/integ.container-port-range.ts
  packages/aws-cdk-lib/aws-ecs-patterns/lib/ecs/network-multiple-target-groups-ecs-service.ts
  packages/aws-cdk-lib/aws-ecs-patterns/lib/fargate/network-multiple-target-groups-fargate-service.ts
  packages/aws-cdk-lib/aws-ecs-patterns/test/ec2/l3s-v2.test.ts
  packages/aws-cdk-lib/aws-ecs-patterns/test/fargate/load-balanced-fargate-service-v2.test.ts
  packages/aws-cdk-lib/aws-ecs/README.md
  packages/aws-cdk-lib/aws-ecs/lib/base/base-service.ts
  packages/aws-cdk-lib/aws-ecs/lib/base/task-definition.ts
  packages/aws-cdk-lib/aws-ecs/lib/container-definition.ts
  packages/aws-cdk-lib/aws-ecs/test/container-definition.test.ts
  packages/aws-cdk-lib/aws-ecs/test/ec2/ec2-service.test.ts
  packages/aws-cdk-lib/aws-ecs/test/fargate/fargate-service.test.ts
Labels: p1, feature-request, effort/small, beginning-contributor

#26817 fix(pipelines): default image Ubuntu6 using EOL Node 16, switch to Ubuntu7
  packages/@aws-cdk-testing/framework-integ/test/pipelines/test/integ.newpipeline-with-codebuild-logging.js.snapshot/PipelineStack.template.json
  packages/@aws-cdk-testing/framework-integ/test/pipelines/test/integ.newpipeline-with-codebuild-logging.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/pipelines/test/integ.newpipeline-with-cross-account-keys.js.snapshot/PipelineStack.template.json
  packages/@aws-cdk-testing/framework-integ/test/pipelines/test/integ.newpipeline-with-cross-account-keys.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/pipelines/test/integ.newpipeline-with-file-system-locations.js.snapshot/PipelinesFileSystemLocations.template.json
  packages/@aws-cdk-testing/framework-integ/test/pipelines/test/integ.newpipeline-with-file-system-locations.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/pipelines/test/integ.newpipeline-with-vpc.js.snapshot/PipelineStack.template.json
  packages/@aws-cdk-testing/framework-integ/test/pipelines/test/integ.newpipeline-with-vpc.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/pipelines/test/integ.newpipeline.js.snapshot/PipelineStack.template.json
  packages/@aws-cdk-testing/framework-integ/test/pipelines/test/integ.newpipeline.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/pipelines/test/integ.pipeline-security.js.snapshot/PipelineSecurityStack.template.json
  packages/@aws-cdk-testing/framework-integ/test/pipelines/test/integ.pipeline-security.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/pipelines/test/integ.pipeline-with-artifact-bucket.js.snapshot/PipelineStack.template.json
  packages/@aws-cdk-testing/framework-integ/test/pipelines/test/integ.pipeline-with-artifact-bucket.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/pipelines/test/integ.pipeline-with-assets-single-upload.js.snapshot/PipelineStack.template.json
  packages/@aws-cdk-testing/framework-integ/test/pipelines/test/integ.pipeline-with-assets-single-upload.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/pipelines/test/integ.pipeline-with-assets.js.snapshot/PipelineStack.template.json
  packages/@aws-cdk-testing/framework-integ/test/pipelines/test/integ.pipeline-with-assets.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/pipelines/test/integ.pipeline-with-stack-outputs-in-custom-step.js.snapshot/StackOutputPipelineStack.template.json
  packages/@aws-cdk-testing/framework-integ/test/pipelines/test/integ.pipeline-with-stack-outputs-in-custom-step.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/pipelines/test/integ.pipeline-with-variables.js.snapshot/VariablePipelineStack.template.json
  packages/@aws-cdk-testing/framework-integ/test/pipelines/test/integ.pipeline-with-variables.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/pipelines/test/integ.pipeline-without-prepare.js.snapshot/PreparelessPipelineStack.template.json
  packages/@aws-cdk-testing/framework-integ/test/pipelines/test/integ.pipeline-without-prepare.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/pipelines/test/integ.pipeline.js.snapshot/PipelineStack.template.json
  packages/@aws-cdk-testing/framework-integ/test/pipelines/test/integ.pipeline.js.snapshot/tree.json
  packages/aws-cdk-lib/pipelines/lib/codepipeline/codepipeline.ts
  packages/aws-cdk-lib/pipelines/lib/legacy/validation/shell-script-action.ts
  packages/aws-cdk-lib/pipelines/lib/private/default-codebuild-image.ts
Labels: p2, feature-request, effort/small, pr-linter/exempt-integ-test, star-contributor

#26821 fix(core): logical IDs are not allowed to start with digits
  packages/@aws-cdk-testing/framework-integ/test/core/test/integ.logical-id.js.snapshot/Default.assets.json
  packages/@aws-cdk-testing/framework-integ/test/core/test/integ.logical-id.js.snapshot/Default.template.json
  packages/@aws-cdk-testing/framework-integ/test/core/test/integ.logical-id.js.snapshot/LogicalIdTestDefaultTestDeployAssert178196BF.assets.json
  packages/@aws-cdk-testing/framework-integ/test/core/test/integ.logical-id.js.snapshot/LogicalIdTestDefaultTestDeployAssert178196BF.template.json
  packages/@aws-cdk-testing/framework-integ/test/core/test/integ.logical-id.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/core/test/integ.logical-id.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/core/test/integ.logical-id.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/core/test/integ.logical-id.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/core/test/integ.logical-id.ts
  packages/aws-cdk-lib/core/lib/private/logical-id.ts
  packages/aws-cdk-lib/core/test/logical-id.test.ts
Labels: bug, p2, effort/small, beginning-contributor

#26172 feat(opensearchservice): configuring gp3 throughput
  packages/@aws-cdk-testing/framework-integ/test/aws-opensearchservice/test/integ.opensearch.gp3.js.snapshot/IntegDefaultTestDeployAssert4E6713E1.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-opensearchservice/test/integ.opensearch.gp3.js.snapshot/IntegDefaultTestDeployAssert4E6713E1.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-opensearchservice/test/integ.opensearch.gp3.js.snapshot/cdk-integ-opensearch-gp3.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-opensearchservice/test/integ.opensearch.gp3.js.snapshot/cdk-integ-opensearch-gp3.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-opensearchservice/test/integ.opensearch.gp3.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-opensearchservice/test/integ.opensearch.gp3.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-opensearchservice/test/integ.opensearch.gp3.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-opensearchservice/test/integ.opensearch.gp3.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-opensearchservice/test/integ.opensearch.gp3.ts
  packages/aws-cdk-lib/aws-opensearchservice/README.md
  packages/aws-cdk-lib/aws-opensearchservice/lib/domain.ts
  packages/aws-cdk-lib/aws-opensearchservice/test/domain.test.ts
Labels: p2, feature-request, effort/medium, beginning-contributor

#26528 refactor(lambda): missing Lambda VPC and security validation
  packages/aws-cdk-lib/aws-eks/lib/kubectl-provider.ts
  packages/aws-cdk-lib/aws-lambda/lib/function.ts
  packages/aws-cdk-lib/aws-lambda/test/function.test.ts
Labels: bug, p2, effort/medium, star-contributor, pr-linter/exemption-requested

#26665 chore: remove DEFAULT_CR_NODE_VERSION regional map
  allowed-breaking-changes.txt
  packages/aws-cdk-lib/aws-logs/lib/log-retention.ts
  packages/aws-cdk-lib/core/lib/custom-resource-provider/custom-resource-provider.ts
  packages/aws-cdk-lib/core/test/custom-resource-provider/custom-resource-provider.test.ts
  packages/aws-cdk-lib/custom-resources/README.md
  packages/aws-cdk-lib/custom-resources/lib/aws-custom-resource/aws-custom-resource.ts
  packages/aws-cdk-lib/custom-resources/test/aws-custom-resource/aws-custom-resource.test.ts
  packages/aws-cdk-lib/region-info/build-tools/fact-tables.ts
  packages/aws-cdk-lib/region-info/build-tools/generate-static-data.ts
  packages/aws-cdk-lib/region-info/lib/fact.ts
Labels: p2, contribution/core

#26580 feat(synthetics): enable auto delete lambdas via custom resource
  packages/@aws-cdk/aws-synthetics-alpha/README.md
  packages/@aws-cdk/aws-synthetics-alpha/lib/canary.ts
  packages/@aws-cdk/aws-synthetics-alpha/package.json
  packages/@aws-cdk/aws-synthetics-alpha/scripts/airlift-custom-resource-handlers.sh
  packages/@aws-cdk/aws-synthetics-alpha/test/canary.test.ts
  packages/@aws-cdk/aws-synthetics-alpha/test/code.test.ts
  packages/@aws-cdk/aws-synthetics-alpha/test/integ.canary-auto-delete-lambda.js.snapshot/cdk-synthetics-canary-auto-delete.assets.json
  packages/@aws-cdk/aws-synthetics-alpha/test/integ.canary-auto-delete-lambda.js.snapshot/cdk-synthetics-canary-auto-delete.template.json
  packages/@aws-cdk/aws-synthetics-alpha/test/integ.canary-auto-delete-lambda.js.snapshot/cdk.out
  packages/@aws-cdk/aws-synthetics-alpha/test/integ.canary-auto-delete-lambda.js.snapshot/cdkintegsyntheticscanaryautodeleteDefaultTestDeployAssert94B79CED.assets.json
  packages/@aws-cdk/aws-synthetics-alpha/test/integ.canary-auto-delete-lambda.js.snapshot/cdkintegsyntheticscanaryautodeleteDefaultTestDeployAssert94B79CED.template.json
  packages/@aws-cdk/aws-synthetics-alpha/test/integ.canary-auto-delete-lambda.js.snapshot/integ.json
  packages/@aws-cdk/aws-synthetics-alpha/test/integ.canary-auto-delete-lambda.js.snapshot/manifest.json
  packages/@aws-cdk/aws-synthetics-alpha/test/integ.canary-auto-delete-lambda.js.snapshot/tree.json
  packages/@aws-cdk/aws-synthetics-alpha/test/integ.canary-auto-delete-lambda.ts
  packages/@aws-cdk/aws-synthetics-alpha/test/integ.canary.js.snapshot/IntegCanaryTestDefaultTestDeployAssert3AD5A094.assets.json
  packages/@aws-cdk/aws-synthetics-alpha/test/integ.canary.js.snapshot/IntegCanaryTestDefaultTestDeployAssert3AD5A094.template.json
  packages/@aws-cdk/aws-synthetics-alpha/test/integ.canary.js.snapshot/asset.40129686bd15b9964212325144aa0db37ac362e1e290ab678d8679880f705e83/index.js
  packages/@aws-cdk/aws-synthetics-alpha/test/integ.canary.js.snapshot/asset.54ed1902ad5ad220444041937ce65cb63c7fbccd0c11fdfd9ecbec43770cdaa5.bundle/index.js
  packages/@aws-cdk/aws-synthetics-alpha/test/integ.canary.js.snapshot/asset.d6b51cbdd22d449b9e57c20ef9d0977e1cfbf06806f8008ce376101a2ad432a8/nodejs/node_modules/canary.js
  packages/@aws-cdk/aws-synthetics-alpha/test/integ.canary.js.snapshot/asset.d6b51cbdd22d449b9e57c20ef9d0977e1cfbf06806f8008ce376101a2ad432a8/nodejs/node_modules/folder/canary.js
  packages/@aws-cdk/aws-synthetics-alpha/test/integ.canary.js.snapshot/asset.d6b51cbdd22d449b9e57c20ef9d0977e1cfbf06806f8008ce376101a2ad432a8/python/canary.py
  packages/@aws-cdk/aws-synthetics-alpha/test/integ.canary.js.snapshot/canary-one.assets.json
  packages/@aws-cdk/aws-synthetics-alpha/test/integ.canary.js.snapshot/canary-one.template.json
  packages/@aws-cdk/aws-synthetics-alpha/test/integ.canary.js.snapshot/manifest.json
  packages/@aws-cdk/aws-synthetics-alpha/test/integ.canary.js.snapshot/tree.json
  packages/@aws-cdk/aws-synthetics-alpha/test/integ.canary.ts
  packages/@aws-cdk/aws-synthetics-alpha/test/metric.test.ts
  packages/@aws-cdk/custom-resource-handlers/README.md
  packages/@aws-cdk/custom-resource-handlers/lib/aws-synthetics-alpha/auto-delete-underlying-resources-handler/index.ts
  packages/@aws-cdk/custom-resource-handlers/package.json
  packages/@aws-cdk/custom-resource-handlers/test/aws-synthetics-alpha/auto-delete-underlying-resources-handler.test.ts
  yarn.lock
Labels: p1, feature-request, effort/medium, contribution/core

#26587 chore: introduce Contributors file
  .github/workflows/README.md
  .github/workflows/update-contributors.yml
Labels: p2, repeat-contributor

#26813 fix(secretsmanager): fix cross-region policy arn for imported secrets
  packages/aws-cdk-lib/aws-secretsmanager/lib/secret.ts
  packages/aws-cdk-lib/aws-secretsmanager/test/secret.test.ts
Labels: bug, p0, effort/small, pr/needs-community-review, pr-linter/exempt-integ-test, beginning-contributor

#26846 fix(cdk-assets): propagate buildSsh flag to docker build
  packages/aws-cdk-lib/aws-lambda/test/code.test.ts
  packages/aws-cdk-lib/core/lib/stack-synthesizers/asset-manifest-builder.ts
  packages/aws-cdk-lib/core/lib/stack-synthesizers/legacy.ts
  packages/cdk-assets/lib/private/handlers/container-images.ts
Labels: p2, pr/needs-community-review, pr-linter/exempt-integ-test, beginning-contributor

#26106 feat(core): support bundling for single non-archive file
  packages/@aws-cdk-testing/framework-integ/test/aws-s3-assets/test/integ.assets.file-bundling.lit.js.snapshot/IntegTestDefaultTestDeployAssertE3E7D2A4.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-s3-assets/test/integ.assets.file-bundling.lit.js.snapshot/IntegTestDefaultTestDeployAssertE3E7D2A4.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-s3-assets/test/integ.assets.file-bundling.lit.js.snapshot/asset.68c2f55451f9566ae0c08664249d08921ab032b2aea797bd8ba293885bf00d64.html
  packages/@aws-cdk-testing/framework-integ/test/aws-s3-assets/test/integ.assets.file-bundling.lit.js.snapshot/asset.68c2f55451f9566ae0c08664249d08921ab032b2aea797bd8ba293885bf00d64/index.html
  packages/@aws-cdk-testing/framework-integ/test/aws-s3-assets/test/integ.assets.file-bundling.lit.js.snapshot/cdk-integ-assets-bundling.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-s3-assets/test/integ.assets.file-bundling.lit.js.snapshot/cdk-integ-assets-bundling.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-s3-assets/test/integ.assets.file-bundling.lit.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-s3-assets/test/integ.assets.file-bundling.lit.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-s3-assets/test/integ.assets.file-bundling.lit.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-s3-assets/test/integ.assets.file-bundling.lit.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-s3-assets/test/integ.assets.file-bundling.lit.ts
  packages/aws-cdk-lib/core/lib/asset-staging.ts
  packages/aws-cdk-lib/core/lib/bundling.ts
  packages/aws-cdk-lib/core/test/docker-stub.sh
  packages/aws-cdk-lib/core/test/staging.test.ts
Labels: p2, pr-linter/exempt-readme, distinguished-contributor

#26794 fix(eks): helm private ecr in govcloud
  packages/aws-cdk-lib/aws-eks/lib/kubectl-handler/helm/__init__.py
Labels: p2, pr-linter/exempt-test, pr-linter/exempt-integ-test, beginning-contributor

#26855 chore: exclude bots from CONTRIBUTORS file
  .github/workflows/update-contributors.yml
Labels: p2, contribution/core

#26856 chore: update badges in README.md
  README.md
Labels: p2, pr/needs-community-review, admired-contributor

#25965 feat(ec2): contributor insight rules for vpc endpoint service
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.vpc-endpoint-service.js.snapshot/TestStackLoadBalancer.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.vpc-endpoint-service.js.snapshot/TestStackLoadBalancer.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.vpc-endpoint-service.js.snapshot/VpcEndpointserviceDefaultTestDeployAssert1FF764BE.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.vpc-endpoint-service.js.snapshot/VpcEndpointserviceDefaultTestDeployAssert1FF764BE.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.vpc-endpoint-service.js.snapshot/asset.ba598c1f1d84f7077ea9c16a6b921e4f8acf18e996100e72a8f17da980e64fdd/__entrypoint__.js
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.vpc-endpoint-service.js.snapshot/asset.ba598c1f1d84f7077ea9c16a6b921e4f8acf18e996100e72a8f17da980e64fdd/index.js
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.vpc-endpoint-service.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.vpc-endpoint-service.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.vpc-endpoint-service.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.vpc-endpoint-service.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.vpc-endpoint-service.ts
  packages/aws-cdk-lib/aws-ec2/README.md
  packages/aws-cdk-lib/aws-ec2/lib/vpc-endpoint-service.ts
  packages/aws-cdk-lib/aws-ec2/test/vpc-endpoint-service.test.ts
Labels: p2

#26862 chore(merge-back): 2.93.0
  CHANGELOG.v2.alpha.md
  CHANGELOG.v2.md
  packages/aws-cdk-lib/cx-api/FEATURE_FLAGS.md
  packages/aws-cdk-lib/cx-api/lib/features.ts
  version.v2.json
Labels: p2, pr/needs-community-review, pr/no-squash, auto-approve

#26860 chore: Add mikewrighton to github-merit-badger.yml.
  .github/workflows/github-merit-badger.yml
Labels: p2, beginning-contributor

#26675 feat(stepfunctions-tasks): FastFile mode for SageMaker Training Job
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/sagemaker/integ.create-training-job.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/sagemaker/integ.create-training-job.js.snapshot/integ-stepfunctions-sagemaker.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/sagemaker/integ.create-training-job.js.snapshot/integ-stepfunctions-sagemaker.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/sagemaker/integ.create-training-job.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/sagemaker/integ.create-training-job.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/sagemaker/integ.create-training-job.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/sagemaker/integ.create-training-job.ts
  packages/aws-cdk-lib/aws-stepfunctions-tasks/README.md
  packages/aws-cdk-lib/aws-stepfunctions-tasks/lib/sagemaker/base-types.ts
  packages/aws-cdk-lib/aws-stepfunctions-tasks/test/sagemaker/create-training-job.test.ts
Labels: p2, feature-request, effort/small, beginning-contributor

#26852 refactor(eks): exposed chart, repository, version and chartAsset props for HelmChart construct
  packages/aws-cdk-lib/aws-eks/lib/helm-chart.ts
Labels: p2, feature-request, effort/small, beginning-contributor, pr/needs-maintainer-review

#26845 chore: Add author mikewrighton to .mergify.yml.
  .mergify.yml
Labels: p2, beginning-contributor

#26801 fix(aws-cdk-lib): ADOT Lambda Layer constants update - v0.32.0
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda/test/integ.lambda-adot.js.snapshot/IntegTestDefaultTestDeployAssertE3E7D2A4.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda/test/integ.lambda-adot.js.snapshot/Stack1.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda/test/integ.lambda-adot.js.snapshot/Stack1.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda/test/integ.lambda-adot.js.snapshot/Stack2.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda/test/integ.lambda-adot.js.snapshot/Stack2.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda/test/integ.lambda-adot.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda/test/integ.lambda-adot.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda/test/integ.lambda-adot.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda/test/integ.lambda-adot.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda/test/integ.lambda-adot.ts
  packages/aws-cdk-lib/aws-lambda/lib/adot-layers.ts
  packages/aws-cdk-lib/aws-lambda/test/adot.test.ts
  packages/aws-cdk-lib/aws-lambda/test/function.test.ts
Labels: p2, repeat-contributor, pr/reviewer-clarification-requested, pr/needs-maintainer-review

#26831 chore(region-info): sort tables and remove region name comments
  packages/aws-cdk-lib/region-info/build-tools/fact-tables.ts
Labels: p1, feature-request, effort/medium, contribution/core

#26808 feat(cloudfront): Add RealtimeLogConfig to Distribution
  packages/@aws-cdk-testing/framework-integ/test/aws-cloudfront/test/integ.realtime-log-config.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-cloudfront/test/integ.realtime-log-config.js.snapshot/integ-realtime-config.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-cloudfront/test/integ.realtime-log-config.js.snapshot/integ-realtime-config.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-cloudfront/test/integ.realtime-log-config.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-cloudfront/test/integ.realtime-log-config.js.snapshot/integrealtimeconfigrealtimelogconfigDefaultTestDeployAssert02ABDB2F.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-cloudfront/test/integ.realtime-log-config.js.snapshot/integrealtimeconfigrealtimelogconfigDefaultTestDeployAssert02ABDB2F.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-cloudfront/test/integ.realtime-log-config.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-cloudfront/test/integ.realtime-log-config.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-cloudfront/test/integ.realtime-log-config.ts
  packages/aws-cdk-lib/aws-cloudfront/README.md
  packages/aws-cdk-lib/aws-cloudfront/lib/distribution.ts
  packages/aws-cdk-lib/aws-cloudfront/lib/endpoint.ts
  packages/aws-cdk-lib/aws-cloudfront/lib/index.ts
  packages/aws-cdk-lib/aws-cloudfront/lib/private/cache-behavior.ts
  packages/aws-cdk-lib/aws-cloudfront/lib/realtime-log-config.ts
  packages/aws-cdk-lib/aws-cloudfront/test/distribution.test.ts
  packages/aws-cdk-lib/aws-cloudfront/test/endpoint.test.ts
  packages/aws-cdk-lib/aws-cloudfront/test/realtime-log-config.test.ts
Labels: p2, beginning-contributor, pr/needs-maintainer-review

#26761 feat(lambda): L2 constructs for SnapStart
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda/test/handler-snapstart.zip
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda/test/integ.lambda.js.snapshot/asset.a37d3ef54c18e7738fe5dc008504591bd3b1f14c6a09ee91eac6d55f7ca5ba5f.zip
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda/test/integ.lambda.js.snapshot/aws-cdk-lambda-1.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda/test/integ.lambda.js.snapshot/aws-cdk-lambda-1.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda/test/integ.lambda.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda/test/integ.lambda.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda/test/integ.lambda.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda/test/integ.lambda.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda/test/integ.lambda.ts
  packages/aws-cdk-lib/aws-lambda/README.md
  packages/aws-cdk-lib/aws-lambda/lib/function.ts
  packages/aws-cdk-lib/aws-lambda/lib/index.ts
  packages/aws-cdk-lib/aws-lambda/lib/runtime.ts
  packages/aws-cdk-lib/aws-lambda/lib/snapstart-config.ts
  packages/aws-cdk-lib/aws-lambda/test/function.test.ts
Labels: p2, feature-request, pr/needs-community-review, effort/medium, beginning-contributor

#26854 chore(aws-cdk-lib): increase `jest` test speed, remove warnings
  nx.json
  package.json
  packages/@aws-cdk-testing/cli-integ/test/resource-pool.test.ts
  packages/@aws-cdk-testing/framework-integ/.gitignore
  packages/@aws-cdk-testing/framework-integ/jest.config.js
  packages/@aws-cdk-testing/framework-integ/test/aws-iam/test/integ.condition-with-ref.js.snapshot/asset.1e14e895fcbdf65feb0a29e4aa74c6c92a6fb0e41f228bef7ab23627ed409cde/__entrypoint__.js
  packages/@aws-cdk-testing/framework-integ/test/aws-iam/test/integ.condition-with-ref.js.snapshot/asset.1e14e895fcbdf65feb0a29e4aa74c6c92a6fb0e41f228bef7ab23627ed409cde/consts.js
  packages/@aws-cdk-testing/framework-integ/test/aws-iam/test/integ.condition-with-ref.js.snapshot/asset.1e14e895fcbdf65feb0a29e4aa74c6c92a6fb0e41f228bef7ab23627ed409cde/index.js
  packages/@aws-cdk-testing/framework-integ/test/aws-iam/test/integ.condition-with-ref.js.snapshot/asset.a913a2614f4e118cb83fa3c0dd17575c9adbbdbad4da17aecd505282a25513f8/consts.js
  packages/@aws-cdk-testing/framework-integ/test/aws-iam/test/integ.condition-with-ref.js.snapshot/asset.a913a2614f4e118cb83fa3c0dd17575c9adbbdbad4da17aecd505282a25513f8/index.js
  packages/@aws-cdk-testing/framework-integ/test/aws-iam/test/integ.condition-with-ref.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-iam/test/integ.condition-with-ref.js.snapshot/iamtestconditionwithrefDefaultTestDeployAssert5E44A64B.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-iam/test/integ.condition-with-ref.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-iam/test/integ.condition-with-ref.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-iam/test/integ.condition-with-ref.js.snapshot/test-condition-with-ref.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-iam/test/integ.condition-with-ref.js.snapshot/test-condition-with-ref.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-iam/test/integ.condition-with-ref.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/core/test/runtime-info.test.ts
  packages/@aws-cdk-testing/framework-integ/test/core/test/tree-metadata.test.ts
  packages/@aws-cdk/app-staging-synthesizer-alpha/test/app-staging-synthesizer.test.ts
  packages/@aws-cdk/aws-msk-alpha/test/__snapshots__/cluster.test.ts.snap
  packages/@aws-cdk/cloud-assembly-schema/jest.config.js
  packages/@aws-cdk/cx-api/jest.config.js
  packages/@aws-cdk/region-info/jest.config.js
  packages/aws-cdk-lib/aws-apigateway/lib/usage-plan.ts
  packages/aws-cdk-lib/aws-ecr/lib/repository.ts
  packages/aws-cdk-lib/core/lib/helpers-internal/index.ts
  packages/aws-cdk-lib/core/lib/private/cfn-utils-provider/consts.ts
  packages/aws-cdk-lib/core/test/stack-synthesis/clicreds-synthesis.test.ts
  packages/aws-cdk-lib/core/test/stack-synthesis/new-style-synthesis.test.ts
  packages/aws-cdk-lib/jest.config.js
  packages/aws-cdk-lib/package.json
  packages/aws-cdk/test/assets.test.ts
  tools/@aws-cdk/cdk-build-tools/config/jest.config.js
  tools/@aws-cdk/cdk-build-tools/package.json
  tools/@aws-cdk/pkglint/jest.config.js
  tools/@aws-cdk/spec2cdk/jest.config.js
Labels: p2, contribution/core

#26880 fix(core): add RetainExceptOnCreate to ParseDeletionPolicy method
  packages/aws-cdk-lib/core/lib/helpers-internal/cfn-parse.ts
Labels: bug, p1, effort/small, pr-linter/exempt-test, pr-linter/exempt-integ-test, beginning-contributor, pr-linter/exemption-requested

#26876 fix(cli): ecs hotswap fails on log configuration enabled
  packages/aws-cdk/lib/api/hotswap/ecs-services.ts
  packages/aws-cdk/test/api/hotswap/ecs-services-hotswap-deployments.test.ts
Labels: bug, p1, effort/small, pr-linter/exempt-integ-test, admired-contributor, pr-linter/cli-integ-tested, pr-linter/exemption-requested

#26881 chore: generate coverage report in text
  tools/@aws-cdk/cdk-build-tools/config/jest.config.js
Labels: p2, feature-request, effort/small, contribution/core

#26337 fix(core): support cache-from and cache-to flags in DockerImage
  packages/aws-cdk-lib/core/lib/bundling.ts
  packages/aws-cdk-lib/core/test/bundling.test.ts
Labels: p2, pr-linter/exempt-readme, pr-linter/exempt-test, pr-linter/exempt-integ-test, beginning-contributor

#26886 fix(sqs): encryptionType is incorrect when encryptionMasterKey is provided
  packages/aws-cdk-lib/aws-sns-subscriptions/test/sqs.test.ts
  packages/aws-cdk-lib/aws-sqs/lib/queue.ts
  packages/aws-cdk-lib/aws-sqs/test/sqs.test.ts
Labels: bug, p0, effort/small, contribution/core, pr-linter/exempt-integ-test

#26882 docs(lambda-event-sources): remove incorrect description regarding receiveMessageWaitTime
  packages/aws-cdk-lib/aws-lambda-event-sources/README.md
Labels: bug, p2, effort/small, valued-contributor

#26861 feat(amplify): enables apps hosted with server side rendering
  packages/@aws-cdk/aws-amplify-alpha/README.md
  packages/@aws-cdk/aws-amplify-alpha/lib/app.ts
  packages/@aws-cdk/aws-amplify-alpha/test/app.test.ts
  packages/@aws-cdk/aws-amplify-alpha/test/integ.app-asset-deployment.js.snapshot/cdk-amplify-app-asset-deployment.template.json
  packages/@aws-cdk/aws-amplify-alpha/test/integ.app-codecommit.js.snapshot/cdk-amplify-codecommit-app.template.json
  packages/@aws-cdk/aws-amplify-alpha/test/integ.app.js.snapshot/cdk-amplify-app.template.json
  packages/@aws-cdk/aws-amplify-alpha/test/integ.app.ts
Labels: p2, feature-request, effort/small, beginning-contributor

#26888 fix(route53): IHostedZone cannot be used for ses.Identity.publicHostedZone anymore
  packages/@aws-cdk-testing/framework-integ/test/aws-route53/test/integ.cross-account-zone-delegation.js.snapshot/aws-cdk-route53-cross-account-integ.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-route53/test/integ.cross-account-zone-delegation.ts
  packages/aws-cdk-lib/aws-route53/README.md
  packages/aws-cdk-lib/aws-route53/lib/hosted-zone-ref.ts
  packages/aws-cdk-lib/aws-route53/lib/hosted-zone.ts
  packages/aws-cdk-lib/aws-route53/test/hosted-zone.test.ts
Labels: bug, p2, effort/medium, distinguished-contributor

#25459 feat(apigateway): L2 construct for Sagemaker Integration
  packages/@aws-cdk/aws-sagemaker-alpha/lib/endpoint.ts
  packages/aws-cdk-lib/aws-apigateway/README.md
  packages/aws-cdk-lib/aws-apigateway/lib/integrations/index.ts
  packages/aws-cdk-lib/aws-apigateway/lib/integrations/sagemaker.ts
  packages/aws-cdk-lib/aws-apigateway/lib/integrations/stepfunctions.ts
  packages/aws-cdk-lib/aws-apigateway/test/integrations/sagemaker.test.ts
  packages/aws-cdk-lib/aws-sagemaker/lib/endpoint.ts
  packages/aws-cdk-lib/aws-sagemaker/lib/index.ts
  packages/aws-cdk-lib/rosetta/aws_apigateway/default.ts-fixture
  packages/aws-cdk-lib/rosetta/aws_apigateway/stepfunctions.ts-fixture
Labels: p2, contribution/core, pr-linter/exempt-integ-test

#26870 docs(stepfunctions): multi-state example for map state
  packages/aws-cdk-lib/aws-stepfunctions/README.md
Labels: p1, effort/small, beginning-contributor

#26903 fix(lambda): NodeJS14 runtime will be EOL soon, deprecate in favor of newer runtimes
  packages/aws-cdk-lib/aws-lambda/lib/runtime.ts
Labels: p2, pr-linter/exempt-test, pr-linter/exempt-integ-test, distinguished-contributor

#26904 fix(lambda): PROVIDED runtime will be EOL soon, deprecate in favor of PROVIDED_AL2
  packages/aws-cdk-lib/aws-lambda/lib/runtime.ts
Labels: p2, pr-linter/exempt-test, pr-linter/exempt-integ-test, distinguished-contributor

#26899 fix(lambda): GO_1_X runtime will be EOL soon, deprecate in favor of PROVIDED_AL2 runtime
  packages/aws-cdk-lib/aws-lambda/lib/runtime.ts
Labels: p2, pr-linter/exempt-test, pr-linter/exempt-integ-test, distinguished-contributor

#26905 feat(ec2): add c7gn instance type
  packages/aws-cdk-lib/aws-ec2/lib/instance-types.ts
Labels: p2, pr-linter/exempt-readme, pr-linter/exempt-test, pr-linter/exempt-integ-test, distinguished-contributor

#26911 feat: update AWS Service Spec
  package.json
  tools/@aws-cdk/spec2cdk/package.json
  yarn.lock
Labels: p2, dependencies, contribution/core, pr-linter/exempt-readme, pr-linter/exempt-test, auto-approve, pr-linter/exempt-integ-test

#26915 chore: Fix full clean instructions in CONTRIBUTING.md
  CONTRIBUTING.md
Labels: p2, contribution/core

#26883 feat(rds): support certificate autority certificate
  packages/@aws-cdk-testing/framework-integ/test/aws-rds/test/integ.instance-ca-certificate.js.snapshot/InstanceCACertificateTestDefaultTestDeployAssert948327B8.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-rds/test/integ.instance-ca-certificate.js.snapshot/InstanceCACertificateTestDefaultTestDeployAssert948327B8.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-rds/test/integ.instance-ca-certificate.js.snapshot/cdk-integ-rds-instance-ca-certificate.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-rds/test/integ.instance-ca-certificate.js.snapshot/cdk-integ-rds-instance-ca-certificate.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-rds/test/integ.instance-ca-certificate.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-rds/test/integ.instance-ca-certificate.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-rds/test/integ.instance-ca-certificate.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-rds/test/integ.instance-ca-certificate.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-rds/test/integ.instance-ca-certificate.ts
  packages/aws-cdk-lib/aws-rds/README.md
  packages/aws-cdk-lib/aws-rds/lib/cluster.ts
  packages/aws-cdk-lib/aws-rds/lib/instance.ts
  packages/aws-cdk-lib/aws-rds/test/instance.test.ts
Labels: p2, feature-request, effort/medium, distinguished-contributor

#26877 feat(stepfunctions-tasks): `algorithmName` validation for `SageMakerCreateTrainingJob`
  packages/aws-cdk-lib/aws-stepfunctions-tasks/lib/sagemaker/create-training-job.ts
  packages/aws-cdk-lib/aws-stepfunctions-tasks/test/sagemaker/create-training-job.test.ts
Labels: p2, pr-linter/exempt-readme, pr-linter/exempt-integ-test, repeat-contributor, pr-linter/exemption-requested

#26898 fix(ec2): networkAclName property for NetworkAcl does not work
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.vpc-networkacl.js.snapshot/aws-cdk-ec2-vpc.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.vpc-networkacl.js.snapshot/aws-cdk-ec2-vpc.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.vpc-networkacl.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.vpc-networkacl.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.vpc-networkacl.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.vpc-networkacl.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.vpc-networkacl.ts
  packages/aws-cdk-lib/aws-ec2/lib/network-acl.ts
  packages/aws-cdk-lib/aws-ec2/test/vpc.test.ts
Labels: bug, p2, admired-contributor

#26910 fix(cli): asset not uploaded with different synthesizer configs
  packages/aws-cdk/lib/util/content-hash.ts
  packages/aws-cdk/lib/util/work-graph-builder.ts
  packages/aws-cdk/lib/util/work-graph-types.ts
  packages/aws-cdk/lib/util/work-graph.ts
  packages/aws-cdk/test/work-graph-builder.test.ts
Labels: bug, p1, effort/medium, contribution/core, pr-linter/exempt-integ-test, pr-linter/cli-integ-tested

#26923 chore: upgrade @typescript-eslint/* packages to be compatible with ts5.2
  packages/@aws-cdk-testing/cli-integ/lib/aws.ts
  packages/@aws-cdk/cli-lib-alpha/THIRD_PARTY_LICENSES
  packages/@aws-cdk/integ-runner/THIRD_PARTY_LICENSES
  packages/aws-cdk/THIRD_PARTY_LICENSES
  packages/awslint/package.json
  tools/@aws-cdk/cdk-build-tools/package.json
  tools/@aws-cdk/eslint-plugin/package.json
  tools/@aws-cdk/node-bundle/package.json
  tools/@aws-cdk/pkglint/package.json
  yarn.lock
Labels: p2, contribution/core

#26919 chore(region-info): ap-southeast-4 region
  packages/@aws-cdk-testing/framework-integ/test/aws-s3-deployment/test/integ.bucket-deployment-deployed-bucket.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-s3-deployment/test/integ.bucket-deployment-deployed-bucket.js.snapshot/test-bucket-deployment-deployed-bucket.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-s3-deployment/test/integ.bucket-deployment-deployed-bucket.js.snapshot/test-bucket-deployment-deployed-bucket.template.json
  packages/@aws-cdk/aws-iot-actions-alpha/test/kinesis-firehose/integ.firehose-put-record-action.js.snapshot/manifest.json
  packages/@aws-cdk/aws-iot-actions-alpha/test/kinesis-firehose/integ.firehose-put-record-action.js.snapshot/test-stack.assets.json
  packages/@aws-cdk/aws-iot-actions-alpha/test/kinesis-firehose/integ.firehose-put-record-action.js.snapshot/test-stack.template.json
  packages/@aws-cdk/aws-kinesisfirehose-alpha/test/integ.delivery-stream.js.snapshot/aws-cdk-firehose-delivery-stream.assets.json
  packages/@aws-cdk/aws-kinesisfirehose-alpha/test/integ.delivery-stream.js.snapshot/aws-cdk-firehose-delivery-stream.template.json
  packages/@aws-cdk/aws-kinesisfirehose-alpha/test/integ.delivery-stream.js.snapshot/manifest.json
  packages/@aws-cdk/aws-kinesisfirehose-alpha/test/integ.delivery-stream.source-stream.js.snapshot/aws-cdk-firehose-delivery-stream-source-stream.assets.json
  packages/@aws-cdk/aws-kinesisfirehose-alpha/test/integ.delivery-stream.source-stream.js.snapshot/aws-cdk-firehose-delivery-stream-source-stream.template.json
  packages/@aws-cdk/aws-kinesisfirehose-alpha/test/integ.delivery-stream.source-stream.js.snapshot/manifest.json
  packages/@aws-cdk/aws-kinesisfirehose-destinations-alpha/test/integ.s3-bucket.lit.js.snapshot/aws-cdk-firehose-delivery-stream-s3-all-properties.assets.json
  packages/@aws-cdk/aws-kinesisfirehose-destinations-alpha/test/integ.s3-bucket.lit.js.snapshot/aws-cdk-firehose-delivery-stream-s3-all-properties.template.json
  packages/@aws-cdk/aws-kinesisfirehose-destinations-alpha/test/integ.s3-bucket.lit.js.snapshot/manifest.json
  packages/aws-cdk-lib/region-info/build-tools/fact-tables.ts
  packages/aws-cdk-lib/region-info/lib/aws-entities.ts
  packages/aws-cdk-lib/region-info/test/__snapshots__/region-info.test.ts.snap
Labels: p2, contribution/core

#26895 feat(appsync): merged APIs
  packages/@aws-cdk-testing/framework-integ/test/aws-appsync/test/appsync.merged-api-1.graphql
  packages/@aws-cdk-testing/framework-integ/test/aws-appsync/test/appsync.merged-api-2.graphql
  packages/@aws-cdk-testing/framework-integ/test/aws-appsync/test/integ.appsync-merged-api.js.snapshot/apiDefaultTestDeployAssert018781F2.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-appsync/test/integ.appsync-merged-api.js.snapshot/apiDefaultTestDeployAssert018781F2.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-appsync/test/integ.appsync-merged-api.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-appsync/test/integ.appsync-merged-api.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-appsync/test/integ.appsync-merged-api.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-appsync/test/integ.appsync-merged-api.js.snapshot/stack.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-appsync/test/integ.appsync-merged-api.js.snapshot/stack.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-appsync/test/integ.appsync-merged-api.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-appsync/test/integ.appsync-merged-api.ts
  packages/aws-cdk-lib/aws-appsync/README.md
  packages/aws-cdk-lib/aws-appsync/lib/graphqlapi.ts
  packages/aws-cdk-lib/aws-appsync/test/appsync-merged-api.test.ts
  packages/aws-cdk-lib/aws-appsync/test/appsync.test.ts
Labels: p2, feature-request, effort/medium, distinguished-contributor

#26934 chore: fix tests that check package versions in the pipeline
  packages/@aws-cdk-testing/framework-integ/test/core/test/runtime-info.test.ts
Labels: p2, contribution/core

#26938 chore: npm-check-updates && yarn upgrade
  package.json
  packages/@aws-cdk-testing/cli-integ/package.json
  packages/@aws-cdk-testing/framework-integ/package.json
  packages/@aws-cdk-testing/framework-integ/test/aws-eks/test/sdk-call-integ-test-docker-app/app/package.json
  packages/@aws-cdk/aws-amplify-alpha/package.json
  packages/@aws-cdk/aws-appconfig-alpha/package.json
  packages/@aws-cdk/aws-batch-alpha/package.json
  packages/@aws-cdk/aws-cognito-identitypool-alpha/package.json
  packages/@aws-cdk/aws-gamelift-alpha/package.json
  packages/@aws-cdk/aws-glue-alpha/package.json
  packages/@aws-cdk/aws-iot-actions-alpha/package.json
  packages/@aws-cdk/aws-iot-alpha/package.json
  packages/@aws-cdk/aws-iotevents-actions-alpha/package.json
  packages/@aws-cdk/aws-iotevents-alpha/package.json
  packages/@aws-cdk/aws-kinesisanalytics-flink-alpha/package.json
  packages/@aws-cdk/aws-kinesisfirehose-destinations-alpha/package.json
  packages/@aws-cdk/aws-msk-alpha/package.json
  packages/@aws-cdk/aws-redshift-alpha/package.json
  packages/@aws-cdk/aws-s3objectlambda-alpha/package.json
  packages/@aws-cdk/aws-sagemaker-alpha/package.json
  packages/@aws-cdk/aws-scheduler-targets-alpha/package.json
  packages/@aws-cdk/aws-synthetics-alpha/package.json
  packages/@aws-cdk/cdk-cli-wrapper/package.json
  packages/@aws-cdk/cfnspec/package.json
  packages/@aws-cdk/cli-lib-alpha/package.json
  packages/@aws-cdk/cloud-assembly-schema/package.json
  packages/@aws-cdk/cloudformation-diff/package.json
  packages/@aws-cdk/custom-resource-handlers/package.json
  packages/@aws-cdk/cx-api/package.json
  packages/@aws-cdk/example-construct-library/package.json
  packages/@aws-cdk/integ-runner/THIRD_PARTY_LICENSES
  packages/@aws-cdk/integ-runner/package.json
  packages/@aws-cdk/integ-tests-alpha/package.json
  packages/@aws-cdk/sdk-v2-to-v3-adapter/package.json
  packages/aws-cdk-lib/package.json
  packages/aws-cdk/THIRD_PARTY_LICENSES
  packages/aws-cdk/lib/init-templates/app/javascript/package.json
  packages/aws-cdk/lib/init-templates/app/typescript/package.json
  packages/aws-cdk/lib/init-templates/lib/typescript/package.json
  packages/aws-cdk/lib/init-templates/sample-app/javascript/package.json
  packages/aws-cdk/lib/init-templates/sample-app/typescript/package.json
  packages/aws-cdk/package.json
  packages/awslint/package.json
  packages/cdk-assets/package.json
  scripts/@aws-cdk/script-tests/package.json
  tools/@aws-cdk/cdk-build-tools/package.json
  tools/@aws-cdk/cdk-release/package.json
  tools/@aws-cdk/cfn2ts/package.json
  tools/@aws-cdk/eslint-plugin/package.json
  tools/@aws-cdk/pkglint/package.json
  tools/@aws-cdk/prlint/package.json
  tools/@aws-cdk/spec2cdk/package.json
  tools/@aws-cdk/yarn-cling/package.json
  yarn.lock
Labels: p2, dependencies, contribution/core, auto-approve

#26943 fix(core): undeprecate `addWarning`
  packages/aws-cdk-lib/core/lib/annotations.ts
Labels: p2, contribution/core, pr-linter/exempt-test, pr-linter/exempt-integ-test

#26928 docs(redshift): add details on cluster resizing
  packages/@aws-cdk/aws-redshift-alpha/README.md
Labels: p2, feature-request, effort/medium, repeat-contributor

#26949 fix(elasticloadbalancingv2): remove equality check for health threshold counts
  packages/@aws-cdk-testing/framework-integ/test/aws-elasticloadbalancingv2/test/integ.nlb.js.snapshot/aws-cdk-elbv2-integ.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-elasticloadbalancingv2/test/integ.nlb.js.snapshot/aws-cdk-elbv2-integ.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-elasticloadbalancingv2/test/integ.nlb.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-elasticloadbalancingv2/test/integ.nlb.js.snapshot/elbv2integDefaultTestDeployAssert6120E394.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-elasticloadbalancingv2/test/integ.nlb.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-elasticloadbalancingv2/test/integ.nlb.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-elasticloadbalancingv2/test/integ.nlb.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-elasticloadbalancingv2/test/integ.nlb.ts
  packages/aws-cdk-lib/aws-elasticloadbalancingv2/lib/nlb/network-target-group.ts
  packages/aws-cdk-lib/aws-elasticloadbalancingv2/test/nlb/target-group.test.ts
Labels: bug, p2, effort/small, pr/needs-community-review, repeat-contributor
