Repository aws/aws-cdk, pull requests merged in 2023-07, with the labels that each got.

#26191 test(s3): add test cases for buckets and kms keys
  packages/aws-cdk-lib/aws-s3/test/bucket.test.ts
Labels: p2, pr/needs-review, repeat-contributor

#26201 docs: reduce size of QuickSight generated examples
  package.json
  yarn.lock
Labels: p2, contribution/core

#26202 docs: reduce size of QuickSight generated examples
  package.json
  yarn.lock
Labels: p2, contribution/core

#24732 docs(elasticloadbalancing): update readme on internetFacing
  packages/aws-cdk-lib/aws-elasticloadbalancing/README.md
Labels: p2, @aws-cdk/aws-elasticloadbalancing, effort/small, contribution/core

#25572 chore(region-info): register eu-central-2, fix firehose cidr blocks for ap-south-2, eu-south-2, me-central-1
  packages/@aws-cdk/aws-iot-actions-alpha/test/kinesis-firehose/integ.firehose-put-record-action.js.snapshot/cdk.out
  packages/@aws-cdk/aws-iot-actions-alpha/test/kinesis-firehose/integ.firehose-put-record-action.js.snapshot/manifest.json
  packages/@aws-cdk/aws-iot-actions-alpha/test/kinesis-firehose/integ.firehose-put-record-action.js.snapshot/test-stack.assets.json
  packages/@aws-cdk/aws-iot-actions-alpha/test/kinesis-firehose/integ.firehose-put-record-action.js.snapshot/test-stack.template.json
  packages/@aws-cdk/aws-iot-actions-alpha/test/kinesis-firehose/integ.firehose-put-record-action.js.snapshot/tree.json
  packages/@aws-cdk/aws-kinesisfirehose-alpha/test/integ.delivery-stream.js.snapshot/aws-cdk-firehose-delivery-stream.assets.json
  packages/@aws-cdk/aws-kinesisfirehose-alpha/test/integ.delivery-stream.js.snapshot/aws-cdk-firehose-delivery-stream.template.json
  packages/@aws-cdk/aws-kinesisfirehose-alpha/test/integ.delivery-stream.js.snapshot/manifest.json
  packages/@aws-cdk/aws-kinesisfirehose-alpha/test/integ.delivery-stream.js.snapshot/tree.json
  packages/@aws-cdk/aws-kinesisfirehose-alpha/test/integ.delivery-stream.source-stream.js.snapshot/aws-cdk-firehose-delivery-stream-source-stream.assets.json
  packages/@aws-cdk/aws-kinesisfirehose-alpha/test/integ.delivery-stream.source-stream.js.snapshot/aws-cdk-firehose-delivery-stream-source-stream.template.json
  packages/@aws-cdk/aws-kinesisfirehose-alpha/test/integ.delivery-stream.source-stream.js.snapshot/manifest.json
  packages/@aws-cdk/aws-kinesisfirehose-alpha/test/integ.delivery-stream.source-stream.js.snapshot/tree.json
  packages/@aws-cdk/aws-kinesisfirehose-destinations-alpha/test/integ.s3-bucket.lit.js.snapshot/asset.2575608c9455922c199396dd056f7479bb172f5c6068cd093f6d061160f48cee/index.js
  packages/@aws-cdk/aws-kinesisfirehose-destinations-alpha/test/integ.s3-bucket.lit.js.snapshot/aws-cdk-firehose-delivery-stream-s3-all-properties.assets.json
  packages/@aws-cdk/aws-kinesisfirehose-destinations-alpha/test/integ.s3-bucket.lit.js.snapshot/aws-cdk-firehose-delivery-stream-s3-all-properties.template.json
  packages/@aws-cdk/aws-kinesisfirehose-destinations-alpha/test/integ.s3-bucket.lit.js.snapshot/manifest.json
  packages/@aws-cdk/aws-kinesisfirehose-destinations-alpha/test/integ.s3-bucket.lit.js.snapshot/tree.json
  packages/aws-cdk-lib/region-info/build-tools/fact-tables.ts
Labels: p1, feature-request, effort/medium, contribution/core

#26204 docs(cloudwatch): document cross-account/cross-region alarm limitations
  packages/aws-cdk-lib/aws-cloudwatch/README.md
Labels: p2, pr/needs-review, contribution/core

#26181 fix(core): tags disappear if CDK app is bundled+minified
  packages/aws-cdk-lib/core/lib/tag-manager.ts
Labels: bug, p2, effort/medium, contribution/core, pr-linter/exempt-test, pr-linter/exempt-integ-test

#26203 feat(glue): add ExecutionClass for FLEX
  packages/@aws-cdk/aws-glue-alpha/README.md
  packages/@aws-cdk/aws-glue-alpha/lib/job.ts
  packages/@aws-cdk/aws-glue-alpha/test/integ.job.js.snapshot/aws-glue-job.assets.json
  packages/@aws-cdk/aws-glue-alpha/test/integ.job.js.snapshot/aws-glue-job.template.json
  packages/@aws-cdk/aws-glue-alpha/test/integ.job.js.snapshot/manifest.json
  packages/@aws-cdk/aws-glue-alpha/test/integ.job.js.snapshot/tree.json
  packages/@aws-cdk/aws-glue-alpha/test/integ.job.ts
  packages/@aws-cdk/aws-glue-alpha/test/job.test.ts
Labels: p2, feature-request, effort/small, pr/needs-review, valued-contributor

#26205 feat(cli-lib): support bootstrap command
  packages/@aws-cdk/cli-lib-alpha/README.md
  packages/@aws-cdk/cli-lib-alpha/lib/cli.ts
  packages/@aws-cdk/cli-lib-alpha/lib/commands/bootstrap.ts
  packages/@aws-cdk/cli-lib-alpha/lib/commands/index.ts
  packages/@aws-cdk/cli-lib-alpha/test/commands.test.ts
Labels: p2, pr-linter/exempt-integ-test, beginning-contributor

#26206 fix(sns-subscriptions): cannot add Lambda Subscription when using a Lambda Construct from a different Construct Library
  packages/aws-cdk-lib/aws-sns-subscriptions/lib/lambda.ts
Labels: bug, p2, effort/medium, pr-linter/exempt-test, pr-linter/exempt-integ-test

#26173 chore(app-staging-synthesizer): tool to test maximum ecr repository allowance
  packages/@aws-cdk/app-staging-synthesizer-alpha/README.md
  packages/@aws-cdk/app-staging-synthesizer-alpha/lib/default-staging-stack.ts
  packages/@aws-cdk/app-staging-synthesizer-alpha/test/check-max-repos.ts
  packages/@aws-cdk/app-staging-synthesizer-alpha/test/default-staging-stack.test.ts
  packages/@aws-cdk/app-staging-synthesizer-alpha/test/integ.synth-default-resources.js.snapshot/StagingStack-default-resourcesmax-ACCOUNT-REGION.template.json
  packages/@aws-cdk/app-staging-synthesizer-alpha/test/integ.synth-default-resources.js.snapshot/integ.json
  packages/@aws-cdk/app-staging-synthesizer-alpha/test/integ.synth-default-resources.js.snapshot/manifest.json
  packages/@aws-cdk/app-staging-synthesizer-alpha/test/integ.synth-default-resources.js.snapshot/synthesize-default-resources.assets.json
  packages/@aws-cdk/app-staging-synthesizer-alpha/test/integ.synth-default-resources.js.snapshot/synthesize-default-resources.template.json
  packages/@aws-cdk/app-staging-synthesizer-alpha/test/integ.synth-default-resources.js.snapshot/tree.json
  packages/@aws-cdk/app-staging-synthesizer-alpha/test/integ.synth-default-resources.ts
  packages/@aws-cdk/app-staging-synthesizer-alpha/test/util.ts
Labels: p2, contribution/core

#26058 feat(codebuild): Support for CodeBuild Image `aws/codebuild/amazonlinux2-x86_64-standard:5.0`
  packages/@aws-cdk-testing/framework-integ/test/aws-codebuild/test/integ.project-amazonlinux-image.lit.js.snapshot/amazonlinux25codebuildDefaultTestDeployAssertB1E0750B.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-codebuild/test/integ.project-amazonlinux-image.lit.js.snapshot/amazonlinux25codebuildDefaultTestDeployAssertB1E0750B.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-codebuild/test/integ.project-amazonlinux-image.lit.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-codebuild/test/integ.project-amazonlinux-image.lit.js.snapshot/codebuild-project-amazonlinux-2-5.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-codebuild/test/integ.project-amazonlinux-image.lit.js.snapshot/codebuild-project-amazonlinux-2-5.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-codebuild/test/integ.project-amazonlinux-image.lit.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-codebuild/test/integ.project-amazonlinux-image.lit.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-codebuild/test/integ.project-amazonlinux-image.lit.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-codebuild/test/integ.project-amazonlinux-image.lit.ts
  packages/aws-cdk-lib/aws-codebuild/README.md
  packages/aws-cdk-lib/aws-codebuild/lib/project.ts
  packages/aws-cdk-lib/aws-codebuild/test/project.test.ts
Labels: p2, pr/needs-review, beginning-contributor

#26218 chore: disable v1 branch upkeep
  .github/dependabot.yml
  .github/workflows/yarn-upgrade-v1main.yml
Labels: p2, contribution/core

#26229 fix(cli-lib): bundle bootstrap template
  packages/@aws-cdk/cli-lib-alpha/.gitignore
  packages/@aws-cdk/cli-lib-alpha/.npmignore
  packages/@aws-cdk/cli-lib-alpha/package.json
Labels: bug, p2, contribution/core, pr-linter/exempt-test, pr-linter/exempt-integ-test

#26231 chore: updates container-definition user jsdoc
  packages/aws-cdk-lib/aws-ecs/lib/container-definition.ts
Labels: p2, pr/needs-review, beginning-contributor

#26227 chore: bump spec2cdk packages to 0.0.1
  tools/@aws-cdk/spec2cdk/jest.config.js
  tools/@aws-cdk/spec2cdk/package.json
  tools/@aws-cdk/spec2cdk/test/__snapshots__/resources.test.js.snap
  tools/@aws-cdk/spec2cdk/test/__snapshots__/services.test.js.snap
  tools/@aws-cdk/spec2cdk/test/resources.test.ts
  tools/@aws-cdk/spec2cdk/test/services.test.ts
  tools/@aws-cdk/spec2cdk/tsconfig.json
  yarn.lock
Labels: p2, contribution/core

#26257 chore(ec2): update link to v2 in SecurityGroup docs
  packages/aws-cdk-lib/aws-ec2/lib/security-group.ts
Labels: p2, beginning-contributor

#26208 fix(aws-cdk-lib): specifying EC2 private IP with associate public IP enabled generates invalid CFn
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.instance-public-and-privateip.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.instance-public-and-privateip.js.snapshot/instancetestDefaultTestDeployAssert5516EAF1.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.instance-public-and-privateip.js.snapshot/instancetestDefaultTestDeployAssert5516EAF1.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.instance-public-and-privateip.js.snapshot/integ-ec2-instance.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.instance-public-and-privateip.js.snapshot/integ-ec2-instance.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.instance-public-and-privateip.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.instance-public-and-privateip.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.instance-public-and-privateip.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.instance-public-and-privateip.ts
  packages/aws-cdk-lib/aws-ec2/lib/instance.ts
  packages/aws-cdk-lib/aws-ec2/test/instance.test.ts
Labels: bug, p1, pr/needs-review, effort/medium, beginning-contributor

#26246 chore: revert "docs(cloudwatch): document cross-account/cross-region alarm limitations"
  packages/aws-cdk-lib/aws-cloudwatch/README.md
Labels: p2, pr/needs-review, contribution/core

#26279 chore: latest lerna doesn't work anymore with repo
  .github/workflows/yarn-upgrade-v1main.yml
Labels: p2, contribution/core

#26272 feat(glue): support Data Quality ruleset
  packages/@aws-cdk/aws-glue-alpha/README.md
  packages/@aws-cdk/aws-glue-alpha/lib/data-quality-ruleset.ts
  packages/@aws-cdk/aws-glue-alpha/lib/index.ts
  packages/@aws-cdk/aws-glue-alpha/package.json
  packages/@aws-cdk/aws-glue-alpha/test/data-quality-ruleset.test.ts
  packages/@aws-cdk/aws-glue-alpha/test/integ.data-quality-ruleset.js.snapshot/aws-glue-data-quality-ruleset.assets.json
  packages/@aws-cdk/aws-glue-alpha/test/integ.data-quality-ruleset.js.snapshot/aws-glue-data-quality-ruleset.template.json
  packages/@aws-cdk/aws-glue-alpha/test/integ.data-quality-ruleset.js.snapshot/cdk.out
  packages/@aws-cdk/aws-glue-alpha/test/integ.data-quality-ruleset.js.snapshot/gluedataqualityrulesetDefaultTestDeployAssertDE1B6FD7.assets.json
  packages/@aws-cdk/aws-glue-alpha/test/integ.data-quality-ruleset.js.snapshot/gluedataqualityrulesetDefaultTestDeployAssertDE1B6FD7.template.json
  packages/@aws-cdk/aws-glue-alpha/test/integ.data-quality-ruleset.js.snapshot/integ.json
  packages/@aws-cdk/aws-glue-alpha/test/integ.data-quality-ruleset.js.snapshot/manifest.json
  packages/@aws-cdk/aws-glue-alpha/test/integ.data-quality-ruleset.js.snapshot/tree.json
  packages/@aws-cdk/aws-glue-alpha/test/integ.data-quality-ruleset.ts
Labels: p2, pr/needs-review, repeat-contributor

#25767 feat(cloudfront): add denyList to OriginRequestPolicy behaviors
  packages/@aws-cdk-testing/framework-integ/test/aws-cloudfront/test/integ.distribution-policies.js.snapshot/integ-distribution-policies.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-cloudfront/test/integ.distribution-policies.js.snapshot/integ-distribution-policies.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-cloudfront/test/integ.distribution-policies.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-cloudfront/test/integ.distribution-policies.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-cloudfront/test/integ.distribution-policies.ts
  packages/aws-cdk-lib/aws-cloudfront/lib/origin-request-policy.ts
  packages/aws-cdk-lib/aws-cloudfront/test/origin-request-policy.test.ts
Labels: p2, pr-linter/exempt-readme, beginning-contributor, pr-linter/exemption-requested

#26114 feat(app-mesh): support port property on weighted targets
  packages/@aws-cdk-testing/framework-integ/test/aws-appmesh/test/integ.mesh-port-match.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-appmesh/test/integ.mesh-port-match.js.snapshot/mesh-stack.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-appmesh/test/integ.mesh-port-match.js.snapshot/mesh-stack.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-appmesh/test/integ.mesh-port-match.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-appmesh/test/integ.mesh-port-match.ts
  packages/aws-cdk-lib/aws-appmesh/lib/route-spec.ts
  packages/aws-cdk-lib/aws-appmesh/test/route.test.ts
Labels: p2, feature-request, pr/needs-review, effort/medium, pr-linter/exempt-readme, beginning-contributor

#25897 feat(eks): support eks with k8s 1.27
  packages/aws-cdk-lib/aws-eks/README.md
  packages/aws-cdk-lib/aws-eks/lib/cluster.ts
Labels: p2, contribution/core, pr-linter/exempt-test, pr-linter/exempt-integ-test

#26238 fix(apprunner-alpha): respect serviceName property
  packages/@aws-cdk/aws-apprunner-alpha/lib/service.ts
  packages/@aws-cdk/aws-apprunner-alpha/test/integ.service-ecr-public.js.snapshot/integ-apprunner-ecr-public.assets.json
  packages/@aws-cdk/aws-apprunner-alpha/test/integ.service-ecr-public.js.snapshot/integ-apprunner-ecr-public.template.json
  packages/@aws-cdk/aws-apprunner-alpha/test/integ.service-ecr-public.js.snapshot/manifest.json
  packages/@aws-cdk/aws-apprunner-alpha/test/integ.service-ecr-public.js.snapshot/tree.json
  packages/@aws-cdk/aws-apprunner-alpha/test/integ.service-ecr-public.ts
  packages/@aws-cdk/aws-apprunner-alpha/test/service.test.ts
Labels: bug, p2, effort/small, pr/needs-review, beginning-contributor

#26287 chore(custom-resource-handlers): refactor minify and bundling step
  packages/@aws-cdk/custom-resource-handlers/package.json
  packages/@aws-cdk/custom-resource-handlers/scripts/minify-and-bundle-sources.ts
  packages/aws-cdk-lib/aws-ecr/lib/repository.ts
  packages/aws-cdk-lib/aws-s3/lib/bucket.ts
  packages/aws-cdk-lib/scripts/airlift-custom-resource-handlers.sh
Labels: p2, pr/needs-review, contribution/core

#26260 feat(cloudwatch): allow configuring period on SingleValueWidget
  packages/@aws-cdk-testing/framework-integ/test/aws-cloudwatch/test/integ.period-singlevaluewidget-and-dashboard.js.snapshot/aws-cdk-cloudwatch-singlevaluewidget-period-integ.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-cloudwatch/test/integ.period-singlevaluewidget-and-dashboard.js.snapshot/aws-cdk-cloudwatch-singlevaluewidget-period-integ.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-cloudwatch/test/integ.period-singlevaluewidget-and-dashboard.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-cloudwatch/test/integ.period-singlevaluewidget-and-dashboard.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-cloudwatch/test/integ.period-singlevaluewidget-and-dashboard.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-cloudwatch/test/integ.period-singlevaluewidget-and-dashboard.js.snapshot/singlevaluewidgetwithperiodDefaultTestDeployAssert48DEBCE0.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-cloudwatch/test/integ.period-singlevaluewidget-and-dashboard.js.snapshot/singlevaluewidgetwithperiodDefaultTestDeployAssert48DEBCE0.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-cloudwatch/test/integ.period-singlevaluewidget-and-dashboard.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-cloudwatch/test/integ.period-singlevaluewidget-and-dashboard.ts
  packages/aws-cdk-lib/aws-cloudwatch/README.md
  packages/aws-cdk-lib/aws-cloudwatch/lib/graph.ts
  packages/aws-cdk-lib/aws-cloudwatch/test/graphs.test.ts
Labels: p2, feature-request, valued-contributor

#26040 fix(lambda): add instrument handler option to adotInstrumentation to support python lambda functions
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda/test/integ.lambda-adot.js.snapshot/IntegTestDefaultTestDeployAssertE3E7D2A4.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda/test/integ.lambda-adot.js.snapshot/Stack1.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda/test/integ.lambda-adot.js.snapshot/Stack1.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda/test/integ.lambda-adot.js.snapshot/Stack2.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda/test/integ.lambda-adot.js.snapshot/Stack2.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda/test/integ.lambda-adot.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda/test/integ.lambda-adot.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda/test/integ.lambda-adot.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda/test/integ.lambda-adot.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda/test/integ.lambda-adot.ts
  packages/aws-cdk-lib/aws-lambda/README.md
  packages/aws-cdk-lib/aws-lambda/lib/adot-layers.ts
  packages/aws-cdk-lib/aws-lambda/lib/function.ts
  packages/aws-cdk-lib/aws-lambda/test/function.test.ts
Labels: bug, p2, pr/needs-review, effort/medium, beginning-contributor, pr-linter/exemption-requested

#26291 fix(synthetics): asset code validation failed on bundled assets
  packages/@aws-cdk/aws-synthetics-alpha/lib/code.ts
  packages/@aws-cdk/aws-synthetics-alpha/test/code.test.ts
Labels: bug, p1, effort/medium, contribution/core, pr-linter/exempt-integ-test

#26273 feat(ec2): support using ssm parameter to resolve AMI ID at instance launch time
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.machine-image.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.machine-image.js.snapshot/integ-ec2-machine-image-test.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.machine-image.js.snapshot/integ-ec2-machine-image-test.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.machine-image.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.machine-image.js.snapshot/integtestDefaultTestDeployAssert24D5C536.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.machine-image.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.machine-image.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.machine-image.ts
  packages/aws-cdk-lib/aws-ec2/README.md
  packages/aws-cdk-lib/aws-ec2/lib/machine-image/machine-image.ts
  packages/aws-cdk-lib/aws-ec2/test/machine-image.test.ts
Labels: p1, feature-request, effort/small, contribution/core

#26248 feat(lambda): lambda runtime python3.11
  packages/aws-cdk-lib/aws-lambda/lib/runtime.ts
Labels: p2, pr/do-not-merge, contribution/core, pr-linter/exempt-readme, pr-linter/exempt-test, pr-linter/exempt-integ-test

#26313 feat(opensearch): opensearch 2.7 engine version
  packages/@aws-cdk-testing/framework-integ/test/aws-opensearchservice/test/integ.opensearch.min.js.snapshot/IntegDefaultTestDeployAssert4E6713E1.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-opensearchservice/test/integ.opensearch.min.js.snapshot/cdk-integ-opensearch.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-opensearchservice/test/integ.opensearch.min.js.snapshot/cdk-integ-opensearch.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-opensearchservice/test/integ.opensearch.min.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-opensearchservice/test/integ.opensearch.min.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-opensearchservice/test/integ.opensearch.min.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-opensearchservice/test/integ.opensearch.min.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-opensearchservice/test/integ.opensearch.min.ts
  packages/aws-cdk-lib/aws-opensearchservice/lib/version.ts
  packages/aws-cdk-lib/aws-opensearchservice/test/domain.test.ts
Labels: p2, contribution/core, pr-linter/exempt-readme

#26241 feat(glue): validate maxCapacity, workerCount, and workerType
  packages/@aws-cdk/aws-glue-alpha/lib/job.ts
  packages/@aws-cdk/aws-glue-alpha/test/job.test.ts
Labels: p2, pr-linter/exempt-readme, pr-linter/exempt-integ-test, valued-contributor

#26322 chore: remove aws-cdk-migration package
  packages/aws-cdk-migration/.eslintrc.js
  packages/aws-cdk-migration/.gitignore
  packages/aws-cdk-migration/.no-packagejson-validator
  packages/aws-cdk-migration/.npmignore
  packages/aws-cdk-migration/LICENSE
  packages/aws-cdk-migration/NOTICE
  packages/aws-cdk-migration/README.md
  packages/aws-cdk-migration/bin/rewrite-imports-v2
  packages/aws-cdk-migration/bin/rewrite-imports-v2.ts
  packages/aws-cdk-migration/jest.config.js
  packages/aws-cdk-migration/lib/rewrite.ts
  packages/aws-cdk-migration/package.json
  packages/aws-cdk-migration/test/rewrite.test.ts
  packages/aws-cdk-migration/tsconfig.json
Labels: p2, contribution/core

#26290 feat(synthetics): lifecycle rules for auto-generated artifact buckets
  packages/@aws-cdk/aws-synthetics-alpha/README.md
  packages/@aws-cdk/aws-synthetics-alpha/lib/canary.ts
  packages/@aws-cdk/aws-synthetics-alpha/test/canary.test.ts
  packages/@aws-cdk/aws-synthetics-alpha/test/integ.canary.js.snapshot/IntegCanaryTestDefaultTestDeployAssert3AD5A094.assets.json
  packages/@aws-cdk/aws-synthetics-alpha/test/integ.canary.js.snapshot/IntegCanaryTestDefaultTestDeployAssert3AD5A094.template.json
  packages/@aws-cdk/aws-synthetics-alpha/test/integ.canary.js.snapshot/asset.3e6ea85c994cf2198f02e67a9e98e8f23456efa8bd72dd55b3a86454c4db9d5f/index.js
  packages/@aws-cdk/aws-synthetics-alpha/test/integ.canary.js.snapshot/asset.89c643a8a6c919d906e0b1cb079b0c5e131cf3cc19c05126f90fc118647fb08c/index.js
  packages/@aws-cdk/aws-synthetics-alpha/test/integ.canary.js.snapshot/asset.fe2373df587bda7e4bf68910b7be30b2042493413a6f6f2c43efab4f184d3bad.bundle/index.js
  packages/@aws-cdk/aws-synthetics-alpha/test/integ.canary.js.snapshot/canary-one.assets.json
  packages/@aws-cdk/aws-synthetics-alpha/test/integ.canary.js.snapshot/canary-one.template.json
  packages/@aws-cdk/aws-synthetics-alpha/test/integ.canary.js.snapshot/manifest.json
  packages/@aws-cdk/aws-synthetics-alpha/test/integ.canary.js.snapshot/tree.json
  packages/@aws-cdk/aws-synthetics-alpha/test/integ.canary.ts
Labels: p2, feature-request, effort/small, pr/needs-review, contribution/core

#26285 feat(cloudwatch): dashboard variables
  packages/@aws-cdk-testing/framework-integ/test/aws-cloudwatch/test/integ.dashboard-variables.js.snapshot/DashboardVariablesIntegrationTest.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-cloudwatch/test/integ.dashboard-variables.js.snapshot/DashboardVariablesIntegrationTest.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-cloudwatch/test/integ.dashboard-variables.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-cloudwatch/test/integ.dashboard-variables.js.snapshot/cdkintegdashboardwithvariablesDefaultTestDeployAssertE08F481E.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-cloudwatch/test/integ.dashboard-variables.js.snapshot/cdkintegdashboardwithvariablesDefaultTestDeployAssertE08F481E.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-cloudwatch/test/integ.dashboard-variables.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-cloudwatch/test/integ.dashboard-variables.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-cloudwatch/test/integ.dashboard-variables.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-cloudwatch/test/integ.dashboard-variables.ts
  packages/aws-cdk-lib/aws-cloudwatch/README.md
  packages/aws-cdk-lib/aws-cloudwatch/lib/dashboard.ts
  packages/aws-cdk-lib/aws-cloudwatch/lib/index.ts
  packages/aws-cdk-lib/aws-cloudwatch/lib/variable.ts
  packages/aws-cdk-lib/aws-cloudwatch/test/dashboard.test.ts
Labels: p2, feature-request, pr/needs-review, effort/medium, repeat-contributor

#26317 fix(ecs): DeploymentAlarms property is specified for ECS service with CODE_DEPLOY and EXTERNAL deployment controller
  packages/@aws-cdk-testing/framework-integ/test/aws-codedeploy/test/ecs/integ.deployment-group.js.snapshot/aws-cdk-codedeploy-ecs-dg.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-codedeploy/test/ecs/integ.deployment-group.js.snapshot/aws-cdk-codedeploy-ecs-dg.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-codedeploy/test/ecs/integ.deployment-group.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-codedeploy/test/ecs/integ.deployment-group.js.snapshot/tree.json
  packages/aws-cdk-lib/aws-ecs/lib/base/base-service.ts
  packages/aws-cdk-lib/aws-ecs/test/base-service.test.ts
Labels: bug, p1, pr-linter/exempt-integ-test, repeat-contributor, pr-linter/exemption-requested

#26288 fix(batch): grant execution role logs:CreateLogStream by default
  packages/@aws-cdk-testing/framework-integ/test/aws-events-targets/test/batch/integ.job-definition-events.js.snapshot/batch-events.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-events-targets/test/batch/integ.job-definition-events.js.snapshot/batch-events.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-events-targets/test/batch/integ.job-definition-events.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-events-targets/test/batch/integ.job-definition-events.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-events-targets/test/batch/integ.job-definition-events.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-events-targets/test/batch/integ.job-definition-events.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/batch/integ.run-batch-job.js.snapshot/aws-stepfunctions-integ.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/batch/integ.run-batch-job.js.snapshot/aws-stepfunctions-integ.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/batch/integ.run-batch-job.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/batch/integ.run-batch-job.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/batch/integ.run-batch-job.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/batch/integ.run-batch-job.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/batch/integ.submit-job.js.snapshot/aws-stepfunctions-integ.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/batch/integ.submit-job.js.snapshot/aws-stepfunctions-integ.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/batch/integ.submit-job.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/batch/integ.submit-job.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/batch/integ.submit-job.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/batch/integ.submit-job.js.snapshot/tree.json
  packages/@aws-cdk/aws-batch-alpha/lib/ecs-container-definition.ts
  packages/@aws-cdk/aws-batch-alpha/test/ecs-container-definition.test.ts
  packages/@aws-cdk/aws-batch-alpha/test/integ.batch-unique-name.js.snapshot/BatchUniqueNameTestDefaultTestDeployAssertA3886AB9.assets.json
  packages/@aws-cdk/aws-batch-alpha/test/integ.batch-unique-name.js.snapshot/cdk.out
  packages/@aws-cdk/aws-batch-alpha/test/integ.batch-unique-name.js.snapshot/integ.json
  packages/@aws-cdk/aws-batch-alpha/test/integ.batch-unique-name.js.snapshot/manifest.json
  packages/@aws-cdk/aws-batch-alpha/test/integ.batch-unique-name.js.snapshot/stack.assets.json
  packages/@aws-cdk/aws-batch-alpha/test/integ.batch-unique-name.js.snapshot/stack.template.json
  packages/@aws-cdk/aws-batch-alpha/test/integ.batch-unique-name.js.snapshot/tree.json
  packages/@aws-cdk/aws-batch-alpha/test/integ.ecs-job-definition.js.snapshot/manifest.json
  packages/@aws-cdk/aws-batch-alpha/test/integ.ecs-job-definition.js.snapshot/stack.assets.json
  packages/@aws-cdk/aws-batch-alpha/test/integ.ecs-job-definition.js.snapshot/stack.template.json
  packages/@aws-cdk/aws-batch-alpha/test/integ.ecs-job-definition.js.snapshot/tree.json
  packages/@aws-cdk/aws-batch-alpha/test/integ.multinode-job-definition.js.snapshot/BatchMultiNodeJobDefinitionTestDefaultTestDeployAssertDB834B9D.assets.json
  packages/@aws-cdk/aws-batch-alpha/test/integ.multinode-job-definition.js.snapshot/cdk.out
  packages/@aws-cdk/aws-batch-alpha/test/integ.multinode-job-definition.js.snapshot/integ.json
  packages/@aws-cdk/aws-batch-alpha/test/integ.multinode-job-definition.js.snapshot/manifest.json
  packages/@aws-cdk/aws-batch-alpha/test/integ.multinode-job-definition.js.snapshot/stack.assets.json
  packages/@aws-cdk/aws-batch-alpha/test/integ.multinode-job-definition.js.snapshot/stack.template.json
  packages/@aws-cdk/aws-batch-alpha/test/integ.multinode-job-definition.js.snapshot/tree.json
Labels: bug, p1, effort/small, contribution/core, pr-linter/exempt-integ-test

#26244 fix(cli): credential plugin exceptions stop the entire CLI
  packages/aws-cdk/lib/api/aws-auth/credential-plugins.ts
Labels: contribution/core, pr-linter/exempt-test, pr-linter/exempt-integ-test, pr-linter/cli-integ-tested

#26326 fix(ecs): Windows ECS Optimized AMI SSM parameter format is incorrect
  packages/aws-cdk-lib/aws-ecs/lib/amis.ts
  packages/aws-cdk-lib/aws-ecs/test/cluster.test.ts
Labels: bug, p2, effort/small, pr-linter/exempt-integ-test, beginning-contributor, pr-linter/exemption-requested

#26314 feat(ec2): make VPC internet gateway creation controllable
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.vpc-no-default-igw.js.snapshot/VpcNoDefaultIgwDefaultTestDeployAssertDB3FDBEB.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.vpc-no-default-igw.js.snapshot/VpcNoDefaultIgwDefaultTestDeployAssertDB3FDBEB.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.vpc-no-default-igw.js.snapshot/asset.ba598c1f1d84f7077ea9c16a6b921e4f8acf18e996100e72a8f17da980e64fdd/__entrypoint__.js
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.vpc-no-default-igw.js.snapshot/asset.ba598c1f1d84f7077ea9c16a6b921e4f8acf18e996100e72a8f17da980e64fdd/index.js
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.vpc-no-default-igw.js.snapshot/aws-cdk-vpc-no-default-igw.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.vpc-no-default-igw.js.snapshot/aws-cdk-vpc-no-default-igw.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.vpc-no-default-igw.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.vpc-no-default-igw.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.vpc-no-default-igw.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.vpc-no-default-igw.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.vpc-no-default-igw.ts
  packages/aws-cdk-lib/aws-ec2/README.md
  packages/aws-cdk-lib/aws-ec2/lib/vpc.ts
  packages/aws-cdk-lib/aws-ec2/test/vpc.test.ts
Labels: p2, feature-request, effort/small, pr/needs-review, star-contributor

#26330 fix(pkglint): library creation generates incorrect package names
  packages/aws-cdk-lib/aws-backupgateway/README.md
  packages/aws-cdk-lib/aws-cleanrooms/README.md
  packages/aws-cdk-lib/aws-proton/README.md
  tools/@aws-cdk/pkglint/lib/library-creation.ts
  tools/@aws-cdk/pkglint/test/libary-creation.test.ts
Labels: p2, pr/needs-review, contribution/core, pr-linter/exempt-test, pr-linter/exempt-integ-test

#26321 chore(app-staging-synthesizer): document and test `autoDeleteStagingAssets: false`
  packages/@aws-cdk/app-staging-synthesizer-alpha/README.md
  packages/@aws-cdk/app-staging-synthesizer-alpha/test/app-staging-synthesizer.test.ts
Labels: p2, pr/needs-review, contribution/core

#26347 chore(deps): remove v1 upgrades
  .github/workflows/yarn-upgrade-v1main.yml
Labels: p2, contribution/core

#25535 feat(iot-actions): iot rule https action l2 construct
  packages/@aws-cdk/aws-iot-actions-alpha/README.md
  packages/@aws-cdk/aws-iot-actions-alpha/lib/https-action.ts
  packages/@aws-cdk/aws-iot-actions-alpha/lib/index.ts
  packages/@aws-cdk/aws-iot-actions-alpha/test/https/https-action.test.ts
  packages/@aws-cdk/aws-iot-actions-alpha/test/https/integ.https-action.js.snapshot/IoTHttpsActionDefaultTestDeployAssert019947CA.assets.json
  packages/@aws-cdk/aws-iot-actions-alpha/test/https/integ.https-action.js.snapshot/IoTHttpsActionDefaultTestDeployAssert019947CA.template.json
  packages/@aws-cdk/aws-iot-actions-alpha/test/https/integ.https-action.js.snapshot/IoTHttpsActionTestStack.assets.json
  packages/@aws-cdk/aws-iot-actions-alpha/test/https/integ.https-action.js.snapshot/IoTHttpsActionTestStack.template.json
  packages/@aws-cdk/aws-iot-actions-alpha/test/https/integ.https-action.js.snapshot/cdk.out
  packages/@aws-cdk/aws-iot-actions-alpha/test/https/integ.https-action.js.snapshot/integ.json
  packages/@aws-cdk/aws-iot-actions-alpha/test/https/integ.https-action.js.snapshot/manifest.json
  packages/@aws-cdk/aws-iot-actions-alpha/test/https/integ.https-action.js.snapshot/tree.json
  packages/@aws-cdk/aws-iot-actions-alpha/test/https/integ.https-action.ts
Labels: p2, feature-request, pr/needs-review, effort/medium, beginning-contributor

#26331 chore: fix example compilation issues
  package.json
  packages/aws-cdk-lib/aws-apigateway/README.md
  packages/aws-cdk-lib/aws-appmesh/README.md
  packages/aws-cdk-lib/aws-appsync/README.md
  packages/aws-cdk-lib/aws-codepipeline-actions/README.md
  packages/aws-cdk-lib/aws-ec2/README.md
  packages/aws-cdk-lib/aws-ec2/lib/launch-template.ts
  packages/aws-cdk-lib/aws-ecr/README.md
  packages/aws-cdk-lib/aws-ecs/README.md
  packages/aws-cdk-lib/aws-eks/README.md
  packages/aws-cdk-lib/aws-events-targets/README.md
  packages/aws-cdk-lib/aws-iam/README.md
  packages/aws-cdk-lib/aws-lambda/README.md
  packages/aws-cdk-lib/aws-logs/README.md
  packages/aws-cdk-lib/aws-osis/README.md
  packages/aws-cdk-lib/aws-rds/README.md
  packages/aws-cdk-lib/aws-rds/lib/aurora-cluster-instance.ts
  packages/aws-cdk-lib/aws-s3-deployment/README.md
  packages/aws-cdk-lib/aws-shield/README.md
  packages/aws-cdk-lib/aws-stepfunctions/README.md
  packages/aws-cdk-lib/aws-stepfunctions/lib/state-machine.ts
  packages/aws-cdk-lib/aws-synthetics/README.md
  packages/aws-cdk-lib/aws-verifiedpermissions/README.md
  packages/aws-cdk-lib/aws-wafv2/README.md
  packages/aws-cdk-lib/aws-workspaces/README.md
  packages/aws-cdk-lib/aws-xray/README.md
  packages/aws-cdk-lib/cloud-assembly-schema/lib/cloud-assembly/metadata-schema.ts
  packages/aws-cdk-lib/custom-resources/README.md
  packages/aws-cdk-lib/lambda-layer-awscli/README.md
  packages/aws-cdk-lib/lambda-layer-kubectl/README.md
  packages/aws-cdk-lib/lambda-layer-node-proxy-agent/README.md
  packages/aws-cdk-lib/package.json
  packages/aws-cdk-lib/rosetta/aws_ecs/default.ts-fixture
  packages/aws-cdk-lib/rosetta/aws_logs/default.ts-fixture
  scripts/run-rosetta.sh
  yarn.lock
Labels: p2, pr/needs-review, contribution/core

#26364 chore(core): augmentations should use relative import
  packages/aws-cdk-lib/package.json
  tools/@aws-cdk/spec2cdk/lib/cfn2ts/index.ts
Labels: p2, contribution/core

#26338 fix(aws_ecs): Do not output NetworkConfiguraiton to ECS Service when using EXTERNAL deployment controller
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs/test/fargate/integ.external-deploy-controller.js.snapshot/aws-ecs-integ.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs/test/fargate/integ.external-deploy-controller.js.snapshot/aws-ecs-integ.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs/test/fargate/integ.external-deploy-controller.js.snapshot/awsecsfargateintegexternaldeploycontrollerDefaultTestDeployAssert27D69498.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs/test/fargate/integ.external-deploy-controller.js.snapshot/awsecsfargateintegexternaldeploycontrollerDefaultTestDeployAssert27D69498.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs/test/fargate/integ.external-deploy-controller.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs/test/fargate/integ.external-deploy-controller.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs/test/fargate/integ.external-deploy-controller.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs/test/fargate/integ.external-deploy-controller.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs/test/fargate/integ.external-deploy-controller.ts
  packages/aws-cdk-lib/aws-ecs/lib/fargate/fargate-service.ts
  packages/aws-cdk-lib/aws-ecs/test/fargate/fargate-service.test.ts
Labels: bug, p2, pr/needs-review, effort/medium, repeat-contributor

#26368 feat(core): allow user to specify --platform
  packages/aws-cdk-lib/core/lib/bundling.ts
  packages/aws-cdk-lib/core/test/bundling.test.ts
Labels: p1, feature-request, effort/medium, pr-linter/exempt-readme, pr-linter/exempt-integ-test, valued-contributor, pr/reviewer-clarification-requested

#26366 feat(lambda-event-sources): added filters support to kafka sources
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-event-sources/test/integ.kafka-selfmanaged.js.snapshot/lambda-event-source-kafka-self-managed.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-event-sources/test/integ.kafka-selfmanaged.ts
  packages/aws-cdk-lib/aws-lambda-event-sources/README.md
  packages/aws-cdk-lib/aws-lambda-event-sources/lib/kafka.ts
  packages/aws-cdk-lib/aws-lambda-event-sources/test/kafka.test.ts
Labels: p2, feature-request, pr/needs-review, effort/medium, star-contributor

#26367 chore(cdk-lib): re-enable skipped tests
  packages/aws-cdk-lib/aws-lambda-nodejs/test/function.test.ts
  packages/aws-cdk-lib/aws-lambda-nodejs/test/util.test.ts
  packages/aws-cdk-lib/cloud-assembly-schema/test/schema.test.ts
  tools/@aws-cdk/cdk-build-tools/config/eslintrc.js
Labels: bug, p1, effort/medium, contribution/core

#26386 fix(lambda): bundling fails with pnpm >= 8.4.0 (#25612)
  packages/aws-cdk-lib/aws-lambda-nodejs/lib/bundling.ts
  packages/aws-cdk-lib/aws-lambda-nodejs/test/bundling.test.ts
Labels: bug, p1, effort/medium, pr-linter/exempt-integ-test, beginning-contributor

#26379 chore: dont npm ignore custom resource handlers
  packages/aws-cdk-lib/.npmignore
Labels: p2, pr/needs-review, contribution/core

#26377 feat(rds): support aurora postgresql 15.3
  packages/aws-cdk-lib/aws-rds/lib/cluster-engine.ts
Labels: p2, feature-request, effort/small, pr-linter/exempt-readme, pr-linter/exempt-test, pr-linter/exempt-integ-test, admired-contributor

#26145 chore(lambda): add toString to lambda architecture
  packages/aws-cdk-lib/aws-lambda/lib/architecture.ts
  packages/aws-cdk-lib/aws-lambda/test/architecture.test.ts
Labels: p2, feature-request, pr/needs-review, effort/medium, beginning-contributor

#26243 fix(s3): allow empty string as keyPrefixEquals
  packages/@aws-cdk-testing/framework-integ/test/aws-s3/test/integ.bucket.website-routing-rules.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-s3/test/integ.bucket.website-routing-rules.js.snapshot/cdkintegs3bucketDefaultTestDeployAssertB89636B8.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-s3/test/integ.bucket.website-routing-rules.js.snapshot/cdkintegs3bucketDefaultTestDeployAssertB89636B8.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-s3/test/integ.bucket.website-routing-rules.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-s3/test/integ.bucket.website-routing-rules.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-s3/test/integ.bucket.website-routing-rules.js.snapshot/s3-bucket-routing.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-s3/test/integ.bucket.website-routing-rules.js.snapshot/s3-bucket-routing.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-s3/test/integ.bucket.website-routing-rules.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-s3/test/integ.bucket.website-routing-rules.ts
  packages/aws-cdk-lib/aws-s3/lib/bucket.ts
  packages/aws-cdk-lib/aws-s3/test/bucket.test.ts
Labels: bug, p2, effort/small, repeat-contributor

#26329 feat(rds): support configuring secret rotation behavior via rotateImmediatelyOnUpdate prop
  packages/@aws-cdk-testing/framework-integ/test/aws-rds/test/integ.cluster-rotation.lit.js.snapshot/aws-cdk-rds-cluster-rotation.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-rds/test/integ.cluster-rotation.lit.js.snapshot/aws-cdk-rds-cluster-rotation.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-rds/test/integ.cluster-rotation.lit.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-rds/test/integ.cluster-rotation.lit.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-rds/test/integ.cluster-rotation.lit.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-rds/test/integ.cluster-rotation.lit.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-rds/test/integ.cluster-rotation.lit.ts
  packages/aws-cdk-lib/aws-rds/README.md
  packages/aws-cdk-lib/aws-rds/lib/props.ts
  packages/aws-cdk-lib/aws-rds/test/cluster.test.ts
  packages/aws-cdk-lib/aws-secretsmanager/README.md
  packages/aws-cdk-lib/aws-secretsmanager/lib/rotation-schedule.ts
  packages/aws-cdk-lib/aws-secretsmanager/lib/secret-rotation.ts
  packages/aws-cdk-lib/aws-secretsmanager/test/secret-rotation.test.ts
Labels: p1, feature-request, pr/needs-review, effort/medium, contribution/core

#26373 fix(batch): SSM parameters can't be used as ECS Container secrets
  packages/@aws-cdk/aws-batch-alpha/README.md
  packages/@aws-cdk/aws-batch-alpha/lib/ecs-container-definition.ts
  packages/@aws-cdk/aws-batch-alpha/test/ecs-container-definition.test.ts
  packages/@aws-cdk/aws-batch-alpha/test/integ.ecs-job-definition.js.snapshot/manifest.json
  packages/@aws-cdk/aws-batch-alpha/test/integ.ecs-job-definition.js.snapshot/stack.assets.json
  packages/@aws-cdk/aws-batch-alpha/test/integ.ecs-job-definition.js.snapshot/stack.template.json
  packages/@aws-cdk/aws-batch-alpha/test/integ.ecs-job-definition.js.snapshot/tree.json
  packages/@aws-cdk/aws-batch-alpha/test/integ.ecs-job-definition.ts
Labels: bug, p1, effort/small, pr/needs-review, contribution/core

#26121 feat(codebuild): support for Docker Registry Image for Linux Arm
  packages/@aws-cdk-testing/framework-integ/test/aws-codebuild/test/integ.docker-registry-arm.lit.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-codebuild/test/integ.docker-registry-arm.lit.js.snapshot/codebuildarmdockerregistryDefaultTestDeployAssert69FB8AA0.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-codebuild/test/integ.docker-registry-arm.lit.js.snapshot/codebuildarmdockerregistryDefaultTestDeployAssert69FB8AA0.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-codebuild/test/integ.docker-registry-arm.lit.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-codebuild/test/integ.docker-registry-arm.lit.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-codebuild/test/integ.docker-registry-arm.lit.js.snapshot/test-codebuild-arm-docker-registry.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-codebuild/test/integ.docker-registry-arm.lit.js.snapshot/test-codebuild-arm-docker-registry.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-codebuild/test/integ.docker-registry-arm.lit.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-codebuild/test/integ.docker-registry-arm.lit.ts
  packages/aws-cdk-lib/aws-codebuild/README.md
  packages/aws-cdk-lib/aws-codebuild/lib/linux-arm-build-image.ts
Labels: bug, p2, effort/medium, beginning-contributor

#26402 chore(integ-tests-alpha): integ tests link is incorrect
  packages/@aws-cdk/integ-runner/README.md
  packages/@aws-cdk/integ-runner/lib/runner/integ-test-runner.ts
  packages/@aws-cdk/integ-runner/test/runner/integ-test-runner.test.ts
  packages/@aws-cdk/integ-runner/test/test-data/xxxxx.test-with-error.ts
Labels: p2, pr-linter/exempt-integ-test, valued-contributor, pr-linter/exemption-requested

#26382 fix(cli): hotswap doesn't update SSM parameter environment variables properly
  packages/aws-cdk/lib/api/util/cloudformation.ts
  packages/aws-cdk/test/api/deploy-stack.test.ts
Labels: p1, feature-request, effort/medium, pr-linter/exempt-integ-test, admired-contributor, pr-linter/cli-integ-tested

#26393 chore(prlint): allow CDK community reviews
  tools/@aws-cdk/prlint/lint.ts
  tools/@aws-cdk/prlint/test/lint.test.ts
Labels: p2, pr/needs-review, contribution/core

#26406 fix(redshift-alpha): incorrect CR runtime version
  packages/@aws-cdk/aws-redshift-alpha/lib/private/database-query.ts
  packages/@aws-cdk/aws-redshift-alpha/test/integ.database-columnid.js.snapshot/aws-cdk-redshift-cluster-database.assets.json
  packages/@aws-cdk/aws-redshift-alpha/test/integ.database-columnid.js.snapshot/aws-cdk-redshift-cluster-database.template.json
  packages/@aws-cdk/aws-redshift-alpha/test/integ.database-columnid.js.snapshot/manifest.json
  packages/@aws-cdk/aws-redshift-alpha/test/integ.database-columnid.js.snapshot/tree.json
  packages/@aws-cdk/aws-redshift-alpha/test/integ.database.js.snapshot/aws-cdk-redshift-cluster-database.assets.json
  packages/@aws-cdk/aws-redshift-alpha/test/integ.database.js.snapshot/aws-cdk-redshift-cluster-database.template.json
  packages/@aws-cdk/aws-redshift-alpha/test/integ.database.js.snapshot/manifest.json
  packages/@aws-cdk/aws-redshift-alpha/test/integ.database.js.snapshot/tree.json
Labels: p2, contribution/core, pr-linter/exempt-integ-test

#26427 feat(rds): support aurora postgresql 14.8
  packages/aws-cdk-lib/aws-rds/lib/cluster-engine.ts
Labels: p2, pr-linter/exempt-readme, pr-linter/exempt-test, pr-linter/exempt-integ-test, beginning-contributor

#26436 docs(trigger): fix incorrect construct id in README for aws-cdk-lib.triggers module
  packages/aws-cdk-lib/triggers/README.md
Labels: p2, pr/needs-review, repeat-contributor

#26419 feat(rds): support Aurora MySQL engine v. 2.11.3
  packages/aws-cdk-lib/aws-rds/lib/cluster-engine.ts
  packages/aws-cdk-lib/aws-rds/test/cluster-engine.test.ts
Labels: p2, feature-request, effort/small, pr-linter/exempt-readme, pr-linter/exempt-integ-test, star-contributor, pr-linter/exemption-requested

#26437 chore: run yarn-upgrade workflow on latest available node version
  .github/workflows/yarn-upgrade.yml
Labels: p2, contribution/core

#26411 fix(lambda): Update Python Lambda Adot Lambda layer versions
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda/test/integ.lambda-adot.js.snapshot/Stack1.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda/test/integ.lambda-adot.js.snapshot/Stack1.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda/test/integ.lambda-adot.js.snapshot/Stack2.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda/test/integ.lambda-adot.js.snapshot/Stack2.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda/test/integ.lambda-adot.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda/test/integ.lambda-adot.js.snapshot/tree.json
  packages/aws-cdk-lib/aws-lambda/lib/adot-layers.ts
  packages/aws-cdk-lib/aws-lambda/test/adot.test.ts
Labels: bug, p2, effort/small, pr-linter/exempt-integ-test, repeat-contributor, pr-linter/exemption-requested

#26438 chore: npm-check-updates && yarn upgrade
  package.json
  packages/@aws-cdk-testing/cli-integ/package.json
  packages/@aws-cdk-testing/framework-integ/package.json
  packages/@aws-cdk-testing/framework-integ/test/aws-eks/test/integ.eks-service-account-sdk-call.js.snapshot/asset.e97cf0d3cdb1f35a828c944dee8af681c86f96c983e136801416e3e37b036e14/.dockerignore
  packages/@aws-cdk-testing/framework-integ/test/aws-eks/test/integ.eks-service-account-sdk-call.js.snapshot/asset.e97cf0d3cdb1f35a828c944dee8af681c86f96c983e136801416e3e37b036e14/Dockerfile
  packages/@aws-cdk-testing/framework-integ/test/aws-eks/test/integ.eks-service-account-sdk-call.js.snapshot/asset.e97cf0d3cdb1f35a828c944dee8af681c86f96c983e136801416e3e37b036e14/package-lock.json
  packages/@aws-cdk-testing/framework-integ/test/aws-eks/test/integ.eks-service-account-sdk-call.js.snapshot/asset.e97cf0d3cdb1f35a828c944dee8af681c86f96c983e136801416e3e37b036e14/package.json
  packages/@aws-cdk-testing/framework-integ/test/aws-eks/test/integ.eks-service-account-sdk-call.js.snapshot/asset.e97cf0d3cdb1f35a828c944dee8af681c86f96c983e136801416e3e37b036e14/sdk-call.js
  packages/@aws-cdk-testing/framework-integ/test/aws-eks/test/integ.eks-service-account-sdk-call.js.snapshot/aws-eks-service-account-sdk-calls-test.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-eks/test/integ.eks-service-account-sdk-call.js.snapshot/aws-eks-service-account-sdk-calls-test.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-eks/test/integ.eks-service-account-sdk-call.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-eks/test/integ.eks-service-account-sdk-call.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-eks/test/integ.eks-service-account-sdk-call.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-eks/test/integ.eks-service-account-sdk-call.ts
  packages/@aws-cdk-testing/framework-integ/test/aws-eks/test/sdk-call-integ-test-docker-app/app/package.json
  packages/@aws-cdk/aws-amplify-alpha/package.json
  packages/@aws-cdk/aws-redshift-alpha/package.json
  packages/@aws-cdk/cli-lib-alpha/THIRD_PARTY_LICENSES
  packages/@aws-cdk/cli-lib-alpha/package.json
  packages/@aws-cdk/custom-resource-handlers/package.json
  packages/@aws-cdk/integ-runner/THIRD_PARTY_LICENSES
  packages/@aws-cdk/integ-tests-alpha/package.json
  packages/@aws-cdk/sdk-v2-to-v3-adapter/package.json
  packages/aws-cdk-lib/package.json
  packages/aws-cdk/THIRD_PARTY_LICENSES
  packages/aws-cdk/lib/api/aws-auth/sdk-provider.ts
  packages/aws-cdk/lib/init-templates/app/typescript/package.json
  packages/aws-cdk/lib/init-templates/lib/typescript/package.json
  packages/aws-cdk/lib/init-templates/sample-app/typescript/package.json
  packages/aws-cdk/package.json
  packages/aws-cdk/test/api/sdk-provider.test.ts
  packages/awslint/package.json
  packages/cdk-assets/package.json
  tools/@aws-cdk/cdk-build-tools/package.json
  tools/@aws-cdk/cfn2ts/package.json
  tools/@aws-cdk/node-bundle/package.json
  tools/@aws-cdk/spec2cdk/package.json
  yarn.lock
Labels: bug, p1, dependencies, contribution/core, auto-approve

#26449 chore(merge-back): 2.88.0
  CHANGELOG.v2.alpha.md
  CHANGELOG.v2.md
  packages/aws-cdk-lib/cx-api/FEATURE_FLAGS.md
  packages/aws-cdk-lib/cx-api/lib/features.ts
  version.v2.json
Labels: p2, pr/needs-review, pr/no-squash, auto-approve

#26448 chore: fix aws-lambda-nodejs test flakiness
  packages/aws-cdk-lib/aws-lambda-nodejs/test/.no-packagejson-validator
  packages/aws-cdk-lib/aws-lambda-nodejs/test/__snapshots__/bundling.test.js.snap
  packages/aws-cdk-lib/aws-lambda-nodejs/test/bundling.test.ts
  packages/aws-cdk-lib/aws-lambda-nodejs/test/function.test.handler1.ts
  packages/aws-cdk-lib/aws-lambda-nodejs/test/function.test.handler2.js
  packages/aws-cdk-lib/aws-lambda-nodejs/test/function.test.handler3.mjs
  packages/aws-cdk-lib/aws-lambda-nodejs/test/function.test.handler4.mts
  packages/aws-cdk-lib/aws-lambda-nodejs/test/function.test.handler5.cts
  packages/aws-cdk-lib/aws-lambda-nodejs/test/function.test.handler6.cjs
  packages/aws-cdk-lib/aws-lambda-nodejs/test/function.test.ts
  packages/aws-cdk-lib/aws-lambda-nodejs/test/handlers/define.ts
  packages/aws-cdk-lib/aws-lambda-nodejs/test/integ-handlers/dependencies-sdk-v3.ts
  packages/aws-cdk-lib/aws-lambda-nodejs/test/integ-handlers/dependencies.ts
  packages/aws-cdk-lib/aws-lambda-nodejs/test/integ-handlers/esm.ts
  packages/aws-cdk-lib/aws-lambda-nodejs/test/integ-handlers/js-handler.js
  packages/aws-cdk-lib/aws-lambda-nodejs/test/integ-handlers/pnpm/dependencies-pnpm.ts
  packages/aws-cdk-lib/aws-lambda-nodejs/test/integ-handlers/pnpm/pnpm-lock.yaml
  packages/aws-cdk-lib/aws-lambda-nodejs/test/integ-handlers/ts-decorator-handler.ts
  packages/aws-cdk-lib/aws-lambda-nodejs/test/integ-handlers/ts-handler.ts
  packages/aws-cdk-lib/aws-lambda-nodejs/test/integ-handlers/ts-web-handler.ts
  packages/aws-cdk-lib/aws-lambda-nodejs/test/integ-handlers/ts-web-run.sh
  packages/aws-cdk-lib/aws-lambda-nodejs/test/integ-handlers/util.ts
  packages/aws-cdk-lib/aws-lambda-nodejs/test/util.test.ts
  packages/aws-cdk/test/api/exec.test.ts
  packages/aws-cdk/test/api/sdk-provider.test.ts
  packages/cdk-assets/test/bockfs.ts
  packages/cdk-assets/test/zipping.test.ts
  tools/@aws-cdk/cdk-build-tools/lib/bockfs.ts
  tools/@aws-cdk/cdk-build-tools/lib/index.ts
Labels: p2, pr/needs-review, contribution/core

#26443 feat(stepfunctions): add stateMachineRevisionId property to StateMachine
  packages/aws-cdk-lib/aws-stepfunctions/lib/state-machine.ts
  packages/aws-cdk-lib/aws-stepfunctions/test/state-machine.test.ts
Labels: p2, feature-request, pr-linter/exempt-readme, pr-linter/exempt-integ-test, beginning-contributor

#26455 chore(prlint): rename pr/needs-review to pr/needs-community-review
  tools/@aws-cdk/prlint/lint.ts
  tools/@aws-cdk/prlint/test/lint.test.ts
Labels: p2, contribution/core

#26450 docs(triggers): add consideration about invocationType for the behavior of trigger failures
  packages/aws-cdk-lib/triggers/README.md
Labels: bug, p2, effort/small, pr/needs-community-review, repeat-contributor, pr/needs-maintainer-review

#26454 chore: add scanlonp to mergify and merit badger
  .github/workflows/github-merit-badger.yml
  .mergify.yml
Labels: p2, repeat-contributor

#26462 fix(rds): Add missing Aurora engine 8.0.mysql_aurora.3.02.3
  packages/aws-cdk-lib/aws-rds/lib/cluster-engine.ts
Labels: p2, pr-linter/exempt-readme, pr-linter/exempt-test, pr-linter/exempt-integ-test, beginning-contributor

#26457 chore(api-gateway): fix resource name in lambda-api.test.ts causing no-op test
  packages/aws-cdk-lib/aws-apigateway/test/lambda-api.test.ts
Labels: p2, pr/needs-community-review, pr-linter/exempt-readme, pr-linter/exempt-test, pr-linter/exempt-integ-test, beginning-contributor

#26378 fix(cdk): allow bootstrap with policy names with a path
  packages/@aws-cdk-testing/cli-integ/tests/cli-integ-tests/bootstrapping.integtest.ts
  packages/aws-cdk/lib/api/bootstrap/bootstrap-environment.ts
  packages/aws-cdk/test/api/bootstrap2.test.ts
Labels: bug, p1, effort/small, pr-linter/exempt-integ-test, star-contributor, pr-linter/cli-integ-tested

#26297 feat(cli): add diff message on the number of stacks with differences
  packages/aws-cdk/lib/cdk-toolkit.ts
  packages/aws-cdk/test/diff.test.ts
Labels: p2, feature-request, effort/small, pr/needs-community-review, pr-linter/exempt-readme, pr-linter/exempt-test, pr-linter/exempt-integ-test, beginning-contributor, pr-linter/cli-integ-tested

#26465 docs(contributing): document how to get around node out of memory error
  CONTRIBUTING.md
Labels: p1, effort/small, valued-contributor

#26466 fix(core): policy validation trace incorrect for larger constructs
  packages/aws-cdk-lib/core/lib/private/tree-metadata.ts
  packages/aws-cdk-lib/core/lib/validation/private/construct-tree.ts
  packages/aws-cdk-lib/core/test/validation/trace.test.ts
Labels: p2, contribution/core, pr-linter/exempt-integ-test

#26324 feat(app-staging-synthesizer): option to specify staging stack name prefix
  packages/@aws-cdk/app-staging-synthesizer-alpha/lib/default-staging-stack.ts
  packages/@aws-cdk/app-staging-synthesizer-alpha/test/app-staging-synthesizer.test.ts
Labels: p2, pr/needs-community-review, contribution/core, pr-linter/exempt-readme, pr-linter/exempt-integ-test

#26458 fix(ecs): deployment alarm configurations are being added in isolated partitions
  packages/aws-cdk-lib/aws-ecs/lib/base/base-service.ts
  packages/aws-cdk-lib/aws-ecs/test/ec2/ec2-service.test.ts
Labels: bug, p1, pr-linter/exempt-integ-test, repeat-contributor, pr/needs-maintainer-review

#26130 feat(apprunner): make `Service` implement `IGrantable`
  packages/@aws-cdk/aws-apprunner-alpha/README.md
  packages/@aws-cdk/aws-apprunner-alpha/lib/service.ts
  packages/@aws-cdk/aws-apprunner-alpha/test/integ.service-ecr-public.js.snapshot/integ-apprunner-ecr-public.template.json
  packages/@aws-cdk/aws-apprunner-alpha/test/integ.service-ecr.js.snapshot/integ-apprunner.template.json
  packages/@aws-cdk/aws-apprunner-alpha/test/integ.service-github.js.snapshot/integ-apprunner.template.json
  packages/@aws-cdk/aws-apprunner-alpha/test/integ.service-vpc-connector.js.snapshot/integ-apprunner.template.json
  packages/@aws-cdk/aws-apprunner-alpha/test/service.test.ts
Labels: p2, feature-request, effort/small, pr/needs-community-review, pr-linter/exempt-integ-test, admired-contributor, pr-linter/exemption-requested

#26110 fix(sns-subscriptions): SQS queue encrypted by AWS managed KMS key is allowed to be specified as subscription and dead-letter queue
  packages/aws-cdk-lib/aws-sns-subscriptions/lib/sqs.ts
  packages/aws-cdk-lib/aws-sns-subscriptions/test/subs.test.ts
  packages/aws-cdk-lib/aws-sqs/lib/queue-base.ts
  packages/aws-cdk-lib/aws-sqs/lib/queue.ts
  packages/aws-cdk-lib/aws-sqs/test/sqs.test.ts
Labels: bug, p1, effort/small, pr-linter/exempt-integ-test, beginning-contributor, pr-linter/exemption-requested

#26479 fix(lambda): bundling fails with pnpm >= 8.4.0 (#26478)
  packages/aws-cdk-lib/aws-lambda-nodejs/lib/bundling.ts
  packages/aws-cdk-lib/aws-lambda-nodejs/test/bundling.test.ts
Labels: bug, p2, pr-linter/exempt-integ-test, beginning-contributor

#26474 fix(stepfunctions-tasks): Default Retry policy for `LambdaInvoke` does not include `Lambda.ClientExecutionTimeoutException` default Retry settings
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/lambda/integ.invoke.js.snapshot/IntegTestDefaultTestDeployAssertE3E7D2A4.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/lambda/integ.invoke.js.snapshot/IntegTestDefaultTestDeployAssertE3E7D2A4.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/lambda/integ.invoke.js.snapshot/asset.69787af1117cf4a4b06d1936f2f27060292b3da90f9e91124d45ba7c146d4c95.bundle/index.js
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/lambda/integ.invoke.js.snapshot/asset.ae370e1010629b78f494346f49ceef3ab2875718f20e6c808114e6aa770c7bf3.bundle/index.js
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/lambda/integ.invoke.js.snapshot/aws-stepfunctions-tasks-lambda-invoke-integ.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/lambda/integ.invoke.js.snapshot/aws-stepfunctions-tasks-lambda-invoke-integ.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/lambda/integ.invoke.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/lambda/integ.invoke.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/lambda/integ.invoke.payload.only.js.snapshot/aws-stepfunctions-tasks-lambda-invoke-integ.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/lambda/integ.invoke.payload.only.js.snapshot/aws-stepfunctions-tasks-lambda-invoke-integ.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/lambda/integ.invoke.payload.only.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/lambda/integ.invoke.payload.only.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/lambda/integ.invoke.payload.only.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/lambda/integ.invoke.payload.only.js.snapshot/tree.json
  packages/aws-cdk-lib/aws-stepfunctions-tasks/README.md
  packages/aws-cdk-lib/aws-stepfunctions-tasks/lib/lambda/invoke.ts
  packages/aws-cdk-lib/aws-stepfunctions-tasks/test/lambda/invoke.test.ts
Labels: bug, p2, pr-linter/exempt-integ-test, beginning-contributor, pr-linter/exemption-requested, pr/reviewer-clarification-requested, pr/needs-maintainer-review

#26383 feat(route53): support geolocation routing
  packages/@aws-cdk-testing/framework-integ/test/aws-route53/test/integ.route53.js.snapshot/aws-cdk-route53-integ.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-route53/test/integ.route53.js.snapshot/aws-cdk-route53-integ.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-route53/test/integ.route53.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-route53/test/integ.route53.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-route53/test/integ.route53.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-route53/test/integ.route53.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-route53/test/integ.route53.ts
  packages/aws-cdk-lib/aws-route53/README.md
  packages/aws-cdk-lib/aws-route53/lib/geo-location.ts
  packages/aws-cdk-lib/aws-route53/lib/index.ts
  packages/aws-cdk-lib/aws-route53/lib/record-set.ts
  packages/aws-cdk-lib/aws-route53/test/geo-location.test.ts
  packages/aws-cdk-lib/aws-route53/test/record-set.test.ts
Labels: p1, feature-request, effort/medium, distinguished-contributor, pr/needs-maintainer-review

#26196 feat(scheduler): ScheduleGroup
  packages/@aws-cdk/aws-scheduler-alpha/README.md
  packages/@aws-cdk/aws-scheduler-alpha/lib/group.ts
  packages/@aws-cdk/aws-scheduler-alpha/lib/index.ts
  packages/@aws-cdk/aws-scheduler-alpha/lib/private/schedule.ts
  packages/@aws-cdk/aws-scheduler-alpha/lib/schedule.ts
  packages/@aws-cdk/aws-scheduler-alpha/rosetta/default.ts-fixture
  packages/@aws-cdk/aws-scheduler-alpha/test/group.test.ts
Labels: p2, pr/needs-community-review, pr-linter/exempt-integ-test, beginning-contributor

#26472 feat(rds): `isFromLegacyInstanceProps` migration flag with `ClusterInstance.serverlessV2`
  packages/aws-cdk-lib/aws-rds/lib/aurora-cluster-instance.ts
  packages/aws-cdk-lib/aws-rds/test/cluster.test.ts
Labels: bug, p1, effort/medium, pr-linter/exempt-readme, pr-linter/exempt-integ-test, beginning-contributor, pr/needs-maintainer-review

#26487 chore(prlint): core PRs are always `pr/needs-maintainer-review`
  tools/@aws-cdk/prlint/.eslintrc.js
  tools/@aws-cdk/prlint/.gitignore
  tools/@aws-cdk/prlint/index.ts
  tools/@aws-cdk/prlint/lint.ts
  tools/@aws-cdk/prlint/module.ts
  tools/@aws-cdk/prlint/package.json
  tools/@aws-cdk/prlint/test/lint.test.ts
  tools/@aws-cdk/prlint/test/module.test.ts
Labels: p2, pr/needs-community-review, contribution/core

#26488 chore(prlint): log additional information
  tools/@aws-cdk/prlint/lint.ts
Labels: p2, pr/needs-community-review, contribution/core

#26308 fix(secretsmanager): `arnForPolicies` evaluates to the partial ARN if accessed from a cross-env stack
  packages/aws-cdk-lib/aws-iam/test/merge-statements.test.ts
  packages/aws-cdk-lib/aws-secretsmanager/lib/secret.ts
  packages/aws-cdk-lib/aws-secretsmanager/test/secret.test.ts
Labels: bug, p1, effort/medium, pr-linter/exempt-integ-test, repeat-contributor

#26193 fix(ecs-patterns): `minHealthyPercent` and `maxHealthyPercent` props validation
  packages/aws-cdk-lib/aws-ecs-patterns/lib/fargate/application-load-balanced-fargate-service.ts
  packages/aws-cdk-lib/aws-ecs-patterns/test/fargate/load-balanced-fargate-service.test.ts
Labels: bug, p2, effort/small, pr-linter/exempt-integ-test, admired-contributor, pr-linter/exemption-requested

#26349 fix(stepfunctions-tasks): specify tags in BatchSubmitJob properties
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/batch/integ.submit-job.js
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/batch/integ.submit-job.js.snapshot/aws-stepfunctions-integ.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/batch/integ.submit-job.ts
  packages/@aws-cdk/aws-batch-alpha/test/aws-stepfunctions-tasks/submit-job.test.ts
  packages/aws-cdk-lib/aws-stepfunctions-tasks/lib/batch/submit-job.ts
Labels: p2, feature-request, effort/small, star-contributor, pr/needs-maintainer-review

#26445 feat(neptune-alpha): support for Neptune serverless
  packages/@aws-cdk/aws-neptune-alpha/README.md
  packages/@aws-cdk/aws-neptune-alpha/lib/cluster.ts
  packages/@aws-cdk/aws-neptune-alpha/lib/instance.ts
  packages/@aws-cdk/aws-neptune-alpha/test/cluster.test.ts
  packages/@aws-cdk/aws-neptune-alpha/test/instance.test.ts
  packages/@aws-cdk/aws-neptune-alpha/test/integ.cluster-serverless.js.snapshot/ClusterServerlessTestDefaultTestDeployAssert8C9220E6.assets.json
  packages/@aws-cdk/aws-neptune-alpha/test/integ.cluster-serverless.js.snapshot/ClusterServerlessTestDefaultTestDeployAssert8C9220E6.template.json
  packages/@aws-cdk/aws-neptune-alpha/test/integ.cluster-serverless.js.snapshot/aws-cdk-neptune-serverless-integ.assets.json
  packages/@aws-cdk/aws-neptune-alpha/test/integ.cluster-serverless.js.snapshot/aws-cdk-neptune-serverless-integ.template.json
  packages/@aws-cdk/aws-neptune-alpha/test/integ.cluster-serverless.js.snapshot/cdk.out
  packages/@aws-cdk/aws-neptune-alpha/test/integ.cluster-serverless.js.snapshot/integ.json
  packages/@aws-cdk/aws-neptune-alpha/test/integ.cluster-serverless.js.snapshot/manifest.json
  packages/@aws-cdk/aws-neptune-alpha/test/integ.cluster-serverless.js.snapshot/tree.json
  packages/@aws-cdk/aws-neptune-alpha/test/integ.cluster-serverless.ts
Labels: p2, feature-request, effort/medium, star-contributor, pr/needs-maintainer-review

#26494 chore(prlint): run linter on pull request reviews
  .github/workflows/pr-linter.yml
Labels: p2, contribution/core

#26473 docs(lambda): fromAsset exclude
  packages/aws-cdk-lib/aws-lambda/README.md
  packages/aws-cdk-lib/rosetta/aws_lambda/default.ts-fixture
Labels: p2, pr/needs-community-review, valued-contributor

#26284 chore: deprecate latestAmazonLinux2022()
  packages/aws-cdk-lib/aws-ec2/README.md
  packages/aws-cdk-lib/aws-ec2/lib/machine-image/machine-image.ts
Labels: bug, p2, effort/medium, contribution/core

#26490 fix(autoscaling): StepScalingPolicy intervals not checked for going over allowable maximum
  packages/aws-cdk-lib/aws-applicationautoscaling/lib/step-scaling-policy.ts
  packages/aws-cdk-lib/aws-applicationautoscaling/test/step-scaling-policy.test.ts
  packages/aws-cdk-lib/aws-autoscaling/lib/step-scaling-policy.ts
  packages/aws-cdk-lib/aws-autoscaling/test/scaling.test.ts
Labels: bug, p2, effort/medium, contribution/core, pr-linter/exempt-integ-test

#26510 chore: introduce issue metrics
  .github/workflows/README.md
  .github/workflows/issue-metrics.yml
Labels: p2, beginning-contributor

#26513 chore: fix issue-metrics workflow
  .github/workflows/issue-metrics.yml
  .github/workflows/repo-metrics.yml
Labels: p2, contribution/core

#26518 chore(node-bundle): remove projen
  tools/@aws-cdk/node-bundle/.eslintrc.json
  tools/@aws-cdk/node-bundle/.gitattributes
  tools/@aws-cdk/node-bundle/.gitignore
  tools/@aws-cdk/node-bundle/.npmignore
  tools/@aws-cdk/node-bundle/.projen/deps.json
  tools/@aws-cdk/node-bundle/.projen/files.json
  tools/@aws-cdk/node-bundle/.projen/tasks.json
  tools/@aws-cdk/node-bundle/.projenrc.js
  tools/@aws-cdk/node-bundle/package.json
  tools/@aws-cdk/node-bundle/tsconfig.dev.json
  tools/@aws-cdk/node-bundle/tsconfig.json
  yarn.lock
Labels: p2, contribution/core

#26496 chore: workflow to automatically request a deployment to the test-pipeline
  .github/workflows/request-cli-integ-test.yml
Labels: p2, contribution/core

#26523 chore: use different approach to authenticate user in request-cli-integ-test
  .github/workflows/README.md
  .github/workflows/request-cli-integ-test.yml
Labels: p2, contribution/core

#26507 feat(rds): support aurora mysql 3.03.1
  packages/aws-cdk-lib/aws-rds/lib/cluster-engine.ts
Labels: p2, pr-linter/exempt-readme, pr-linter/exempt-test, pr-linter/exempt-integ-test, beginning-contributor

#25606 chore(eks): improve eks doc for console access
  packages/aws-cdk-lib/aws-eks/README.md
Labels: bug, p2, contribution/core

#26525 chore: try different auth method for request-cli-integ-test
  .github/workflows/request-cli-integ-test.yml
Labels: p2, contribution/core

#26498 feat(logs): configure custom subscription filter name
  packages/@aws-cdk-testing/framework-integ/test/aws-logs/test/integ.subscriptionfilter.js.snapshot/aws-cdk-subscriptionfilter-integ.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-logs/test/integ.subscriptionfilter.js.snapshot/aws-cdk-subscriptionfilter-integ.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-logs/test/integ.subscriptionfilter.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-logs/test/integ.subscriptionfilter.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-logs/test/integ.subscriptionfilter.js.snapshot/integtestDefaultTestDeployAssert24D5C536.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-logs/test/integ.subscriptionfilter.js.snapshot/integtestDefaultTestDeployAssert24D5C536.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-logs/test/integ.subscriptionfilter.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-logs/test/integ.subscriptionfilter.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-logs/test/integ.subscriptionfilter.ts
  packages/aws-cdk-lib/aws-logs/README.md
  packages/aws-cdk-lib/aws-logs/lib/log-group.ts
  packages/aws-cdk-lib/aws-logs/lib/subscription-filter.ts
  packages/aws-cdk-lib/aws-logs/test/loggroup.test.ts
  packages/aws-cdk-lib/aws-logs/test/subscriptionfilter.test.ts
Labels: p2, feature-request, effort/small, pr/needs-community-review, valued-contributor

#26403 feat(opensearchservice): L2 properties for offPeakWindowOptions and softwareUpdateOptions
  packages/@aws-cdk-testing/framework-integ/test/aws-opensearchservice/test/integ.opensearch.js.snapshot/cdk-integ-opensearch.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-opensearchservice/test/integ.opensearch.ts
  packages/aws-cdk-lib/aws-opensearchservice/README.md
  packages/aws-cdk-lib/aws-opensearchservice/lib/domain.ts
  packages/aws-cdk-lib/aws-opensearchservice/test/domain.test.ts
Labels: p2, feature-request, effort/medium, star-contributor

#26531 chore: update aws service spec in a separate job
  .github/workflows/README.md
  .github/workflows/spec-update.yml
  .github/workflows/yarn-upgrade.yml
Labels: p2, contribution/core

#26535 chore(prlint): trigger pr linter from pr reviews
  .github/workflows/README.md
  .github/workflows/pr-linter-trigger.yml
  .github/workflows/pr-linter.yml
  tools/@aws-cdk/prlint/index.ts
Labels: p2, contribution/core, pr/needs-maintainer-review

#26542 chore(prlint): fix artifact name mismatch
  .github/workflows/pr-linter-trigger.yml
Labels: p2, contribution/core

#26541 feat: update AWS Service Spec
  tools/@aws-cdk/spec2cdk/package.json
  yarn.lock
Labels: p2, dependencies, contribution/core, pr-linter/exempt-readme, pr-linter/exempt-test, auto-approve, pr-linter/exempt-integ-test, pr/needs-maintainer-review

#26549 chore(lint): replace hard-coded separators with `path.sep`
  tools/@aws-cdk/eslint-plugin/lib/rules/invalid-cfn-imports.ts
Labels: p2, beginning-contributor

#26548 chore: exempt the spec update PRs from usual PR requirements
  .github/workflows/spec-update.yml
Labels: p2, contribution/core

#26547 chore: readme for hosted_zone tests
  packages/@aws-cdk-testing/framework-integ/README.md
  packages/@aws-cdk-testing/framework-integ/test/aws-certificatemanager/test/integ.certificate-name.ts
  packages/@aws-cdk-testing/framework-integ/test/aws-certificatemanager/test/integ.dns-validated-certificate.ts
  packages/@aws-cdk-testing/framework-integ/test/aws-cloudfront/test/integ.cloudfront-cross-region-cert.ts
  packages/@aws-cdk-testing/framework-integ/test/aws-elasticloadbalancingv2-actions/test/integ.cognito.ts
  packages/@aws-cdk-testing/framework-integ/test/aws-elasticloadbalancingv2/test/integ.alb.oidc.ts
  packages/@aws-cdk-testing/framework-integ/test/aws-route53-patterns/test/integ.hosted-redirect-same-region.ts
  packages/@aws-cdk-testing/framework-integ/test/aws-route53-patterns/test/integ.hosted-redirect.ts
Labels: p2, contribution/core

#26396 feat: support max-buffer-size for AWSLogs driver
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs/test/ec2/integ.firelens-s3-config.js.snapshot/aws-ecs-integ.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs/test/ec2/integ.firelens-s3-config.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs/test/ec2/integ.firelens-s3-config.ts
  packages/aws-cdk-lib/aws-ecs/README.md
  packages/aws-cdk-lib/aws-ecs/lib/log-drivers/aws-log-driver.ts
  packages/aws-cdk-lib/aws-ecs/test/aws-log-driver.test.ts
Labels: p2, beginning-contributor

#26551 fix(cli-lib): set skipLibCheck on generateSchema to prevent intermittent test failures
  packages/aws-cdk-lib/cloud-assembly-schema/scripts/update-schema.ts
Labels: p2, contribution/core, pr-linter/exempt-test, pr-linter/exempt-integ-test

#26567 chore(merge-back): 2.89.0
  CHANGELOG.v2.alpha.md
  CHANGELOG.v2.md
  version.v2.json
Labels: p2, pr/needs-community-review, pr/no-squash, auto-approve

#26568 chore(cdk-lib): cloud-assembly-schema tests are flaky, becaue they are not free of side-effects
  packages/aws-cdk-lib/cloud-assembly-schema/scripts/update-schema.ts
Labels: p2, contribution/core, pr/needs-maintainer-review

#26578 chore(actions): stop spamming stale notification for forks
  .github/workflows/close-stale-issues.yml
  .github/workflows/close-stale-prs.yml
  .github/workflows/handle-stale-discussions.yml
Labels: p2, beginning-contributor

#26552 chore(prlint): dismissed reviews should not count as requested changes
  tools/@aws-cdk/prlint/lint.ts
  tools/@aws-cdk/prlint/test/lint.test.ts
Labels: p2, contribution/core

#26579 feat: update AWS Service Spec
  allowed-breaking-changes.txt
  tools/@aws-cdk/spec2cdk/package.json
  yarn.lock
Labels: p2, dependencies, contribution/core, pr-linter/exempt-readme, pr-linter/exempt-test, auto-approve, pr-linter/exempt-integ-test

#24419 chore: ROADMAP doc updates
  ROADMAP.md
Labels: p2, contribution/core
