Repository aws/aws-cdk, pull requests merged in 2023-04, with the labels that each got.

#24899 docs(contributing): fixed buildup command example
  CONTRIBUTING.md
Labels: p2, valued-contributor

#24855 docs(servicecatalogappregistry): update README.md to track latest change
  packages/@aws-cdk/aws-servicecatalogappregistry/README.md
Labels: p2, repeat-contributor

#24925 docs(pipelines): explain that CDK Pipelines is not a security mechanism
  packages/aws-cdk-lib/pipelines/README.md
Labels: p2, contribution/core

#24927 chore(release): revert `1.199.0` merge-back
  CHANGELOG.md
  version.v1.json
Labels: p2, contribution/core

#24924 docs(cognito): Fix minor typos in documentation
  packages/aws-cdk-lib/aws-cognito/lib/user-pool-email.ts
  packages/aws-cdk-lib/aws-cognito/lib/user-pool.ts
Labels: p2, beginning-contributor

#24928 docs(cloudwatch): remove extra "the" in Alarms section
  packages/aws-cdk-lib/aws-cloudwatch/README.md
Labels: p2, beginning-contributor

#24401 fix(ecr): policytext errors when includes resource
  packages/@aws-cdk-testing/framework-integ/test/aws-ecr/test/integ.basic.js.snapshot/aws-ecr-integ-stack.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecr/test/integ.basic.ts
  packages/aws-cdk-lib/aws-ecr/README.md
  packages/aws-cdk-lib/aws-ecr/lib/repository.ts
  packages/aws-cdk-lib/aws-ecr/test/repository.test.ts
Labels: p2, pr-linter/exempt-integ-test, repeat-contributor

#24935 chore(rds): update aurora-mysql engine versions
  packages/aws-cdk-lib/aws-rds/lib/cluster-engine.ts
Labels: p2, beginning-contributor

#24934 chore: add maxWorkers and remove detectOpenHandles
  packages/aws-cdk-lib/package.json
Labels: p2, contribution/core

#24929 chore: remove duplicated cloud-assembly-schema
  packages/@aws-cdk/cloud-assembly-schema/.eslintrc.js
  packages/@aws-cdk/cloud-assembly-schema/.gitignore
  packages/@aws-cdk/cloud-assembly-schema/README.md
  packages/@aws-cdk/cloud-assembly-schema/jest.config.js
  packages/@aws-cdk/cloud-assembly-schema/lib/assets/aws-destination.ts
  packages/@aws-cdk/cloud-assembly-schema/lib/assets/docker-image-asset.ts
  packages/@aws-cdk/cloud-assembly-schema/lib/assets/file-asset.ts
  packages/@aws-cdk/cloud-assembly-schema/lib/assets/index.ts
  packages/@aws-cdk/cloud-assembly-schema/lib/assets/schema.ts
  packages/@aws-cdk/cloud-assembly-schema/lib/cloud-assembly/artifact-schema.ts
  packages/@aws-cdk/cloud-assembly-schema/lib/cloud-assembly/context-queries.ts
  packages/@aws-cdk/cloud-assembly-schema/lib/cloud-assembly/index.ts
  packages/@aws-cdk/cloud-assembly-schema/lib/cloud-assembly/metadata-schema.ts
  packages/@aws-cdk/cloud-assembly-schema/lib/cloud-assembly/schema.ts
  packages/@aws-cdk/cloud-assembly-schema/lib/index.ts
  packages/@aws-cdk/cloud-assembly-schema/lib/integ-tests/commands/common.ts
  packages/@aws-cdk/cloud-assembly-schema/lib/integ-tests/commands/deploy.ts
  packages/@aws-cdk/cloud-assembly-schema/lib/integ-tests/commands/destroy.ts
  packages/@aws-cdk/cloud-assembly-schema/lib/integ-tests/commands/index.ts
  packages/@aws-cdk/cloud-assembly-schema/lib/integ-tests/index.ts
  packages/@aws-cdk/cloud-assembly-schema/lib/integ-tests/schema.ts
  packages/@aws-cdk/cloud-assembly-schema/lib/integ-tests/test-case.ts
  packages/@aws-cdk/cloud-assembly-schema/lib/manifest.ts
  packages/@aws-cdk/cloud-assembly-schema/package.json
  packages/@aws-cdk/cloud-assembly-schema/schema/README.md
  packages/@aws-cdk/cloud-assembly-schema/schema/assets.schema.json
  packages/@aws-cdk/cloud-assembly-schema/schema/cloud-assembly.schema.json
  packages/@aws-cdk/cloud-assembly-schema/schema/cloud-assembly.version.json
  packages/@aws-cdk/cloud-assembly-schema/schema/integ.schema.json
  packages/@aws-cdk/cloud-assembly-schema/scripts/update-schema.sh
  packages/@aws-cdk/cloud-assembly-schema/scripts/update-schema.ts
  packages/@aws-cdk/cloud-assembly-schema/test/__snapshots__/manifest.test.js.snap
  packages/@aws-cdk/cloud-assembly-schema/test/assets.test.ts
  packages/@aws-cdk/cloud-assembly-schema/test/fixtures/high-version/manifest.json
  packages/@aws-cdk/cloud-assembly-schema/test/fixtures/invalid-artifact-type/manifest.json
  packages/@aws-cdk/cloud-assembly-schema/test/fixtures/invalid-nested-property/manifest.json
  packages/@aws-cdk/cloud-assembly-schema/test/fixtures/invalid-version/manifest.json
  packages/@aws-cdk/cloud-assembly-schema/test/fixtures/only-version/manifest.json
  packages/@aws-cdk/cloud-assembly-schema/test/fixtures/random-metadata/manifest.json
  packages/@aws-cdk/cloud-assembly-schema/test/fixtures/unknown-property/manifest.json
  packages/@aws-cdk/cloud-assembly-schema/test/fixtures/with-stack-tags/manifest.json
  packages/@aws-cdk/cloud-assembly-schema/test/integ-tests.test.ts
  packages/@aws-cdk/cloud-assembly-schema/test/manifest.test.ts
  packages/@aws-cdk/cloud-assembly-schema/test/schema.test.ts
  tools/@aws-cdk/cdk-build-tools/bin/cdk-build.ts
  tools/@aws-cdk/cdk-build-tools/bin/cdk-copy
  tools/@aws-cdk/cdk-build-tools/bin/cdk-copy.ts
  tools/@aws-cdk/cdk-build-tools/package.json
Labels: p2, contribution/core

#24940 chore(deps): bump rosetta to `1.80.0`
  package.json
  yarn.lock
Labels: p2, contribution/core

#24905 chore(scripts): pass higher memory limit in `buildup` and `builddown`
  scripts/builddown
  scripts/buildup
Labels: bug, p2, admired-contributor

#24486 fix(ec2): looking up a shared VPC has incorrect account ID in ARN
  packages/@aws-cdk/cx-api/lib/context/vpc.ts
  packages/aws-cdk-lib/aws-ec2/lib/vpc-lookup.ts
  packages/aws-cdk-lib/aws-ec2/lib/vpc.ts
  packages/aws-cdk-lib/aws-ec2/test/vpc.from-lookup.test.ts
  packages/aws-cdk-lib/cx-api/lib/context/vpc.ts
  packages/aws-cdk/lib/context-providers/vpcs.ts
  packages/aws-cdk/test/context-providers/vpcs.test.ts
Labels: bug, p2, effort/medium, pr-linter/exempt-integ-test, admired-contributor, pr-linter/cli-integ-tested

#24938 docs(elbv2): clarify target group documentation
  packages/aws-cdk-lib/aws-elasticloadbalancingv2/lib/alb/application-target-group.ts
  packages/aws-cdk-lib/aws-elasticloadbalancingv2/lib/nlb/network-target-group.ts
Labels: p2, admired-contributor

#24942 chore: bump jsii-rosetta to unblock pipeline
  package.json
  yarn.lock
Labels: p2, contribution/core

#24892 chore(merge-back): 2.72.1
  CHANGELOG.v2.alpha.md
  CHANGELOG.v2.md
  version.v2.json
Labels: p2, pr/no-squash, auto-approve

#24435 feat(trigger): Allow trigger to work with Lambda functions with long timeouts
  packages/@aws-cdk-testing/framework-integ/test/triggers/test/integ.triggers.js
  packages/@aws-cdk-testing/framework-integ/test/triggers/test/integ.triggers.js.snapshot/MyStack.assets.json
  packages/@aws-cdk-testing/framework-integ/test/triggers/test/integ.triggers.js.snapshot/MyStack.template.json
  packages/@aws-cdk-testing/framework-integ/test/triggers/test/integ.triggers.js.snapshot/TriggerTestDefaultTestDeployAssert61636546.assets.json
  packages/@aws-cdk-testing/framework-integ/test/triggers/test/integ.triggers.js.snapshot/TriggerTestDefaultTestDeployAssert61636546.template.json
  packages/@aws-cdk-testing/framework-integ/test/triggers/test/integ.triggers.js.snapshot/asset.004b12857696fed3c10ad54c8e3cabd07cdf653ec469cbadab6c64ae6c9ce690/index.js
  packages/@aws-cdk-testing/framework-integ/test/triggers/test/integ.triggers.js.snapshot/asset.36618132bd37b6b15f9987b57ad1fbf613f1ad937aec72381232b163ed9c44c4.bundle/index.js
  packages/@aws-cdk-testing/framework-integ/test/triggers/test/integ.triggers.js.snapshot/asset.e6b302aaee9bb5261338cf6b21e540e805eeaf2c18eb3246f7556104f361f68d/__entrypoint__.js
  packages/@aws-cdk-testing/framework-integ/test/triggers/test/integ.triggers.js.snapshot/asset.e6b302aaee9bb5261338cf6b21e540e805eeaf2c18eb3246f7556104f361f68d/index.js
  packages/@aws-cdk-testing/framework-integ/test/triggers/test/integ.triggers.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/triggers/test/integ.triggers.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/triggers/test/integ.triggers.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/triggers/test/integ.triggers.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/triggers/test/integ.triggers.ts
  packages/@aws-cdk-testing/framework-integ/test/triggers/test/lib/index.js
  packages/aws-cdk-lib/triggers/README.md
  packages/aws-cdk-lib/triggers/lib/lambda/index.ts
  packages/aws-cdk-lib/triggers/lib/trigger-function.ts
  packages/aws-cdk-lib/triggers/lib/trigger.ts
  packages/aws-cdk-lib/triggers/test/trigger-handler.test.ts
  packages/aws-cdk-lib/triggers/test/triggers.test.ts
Labels: bug, p2, effort/small, valued-contributor

#24951 chore: fix misspelling of "dismiss"
  tools/@aws-cdk/prlint/lint.ts
Labels: p2, beginning-contributor

#24584 feat(pipelines): Add ability to define fileSystemLocations for a CodePipeline
  packages/@aws-cdk-testing/framework-integ/test/pipelines/test/integ.newpipeline-with-file-system-locations.d.ts
  packages/@aws-cdk-testing/framework-integ/test/pipelines/test/integ.newpipeline-with-file-system-locations.js
  packages/@aws-cdk-testing/framework-integ/test/pipelines/test/integ.newpipeline-with-file-system-locations.js.snapshot/PipelinesFileSystemLocations.assets.json
  packages/@aws-cdk-testing/framework-integ/test/pipelines/test/integ.newpipeline-with-file-system-locations.js.snapshot/PipelinesFileSystemLocations.template.json
  packages/@aws-cdk-testing/framework-integ/test/pipelines/test/integ.newpipeline-with-file-system-locations.js.snapshot/PipelinesFileSystemLocationsPipeline5689C8D8.dot
  packages/@aws-cdk-testing/framework-integ/test/pipelines/test/integ.newpipeline-with-file-system-locations.js.snapshot/assembly-PipelinesFileSystemLocations-Beta/PipelinesFileSystemLocationsBetaStack18199ECAE.assets.json
  packages/@aws-cdk-testing/framework-integ/test/pipelines/test/integ.newpipeline-with-file-system-locations.js.snapshot/assembly-PipelinesFileSystemLocations-Beta/PipelinesFileSystemLocationsBetaStack18199ECAE.template.json
  packages/@aws-cdk-testing/framework-integ/test/pipelines/test/integ.newpipeline-with-file-system-locations.js.snapshot/assembly-PipelinesFileSystemLocations-Beta/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/pipelines/test/integ.newpipeline-with-file-system-locations.js.snapshot/assembly-PipelinesFileSystemLocations-Beta/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/pipelines/test/integ.newpipeline-with-file-system-locations.js.snapshot/asset.40aa87cdf43c4095cec18bc443965f22ab2f8c1ace47e482a0ba4e35d83b0cc9/__entrypoint__.js
  packages/@aws-cdk-testing/framework-integ/test/pipelines/test/integ.newpipeline-with-file-system-locations.js.snapshot/asset.40aa87cdf43c4095cec18bc443965f22ab2f8c1ace47e482a0ba4e35d83b0cc9/index.js
  packages/@aws-cdk-testing/framework-integ/test/pipelines/test/integ.newpipeline-with-file-system-locations.js.snapshot/asset.8289faf53c7da377bb2b90615999171adef5e1d8f6b88810e5fef75e6ca09ba5.txt
  packages/@aws-cdk-testing/framework-integ/test/pipelines/test/integ.newpipeline-with-file-system-locations.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/pipelines/test/integ.newpipeline-with-file-system-locations.js.snapshot/cdkintegcodepipelinewithfilesystemlocationsDefaultTestDeployAssert3E26E748.assets.json
  packages/@aws-cdk-testing/framework-integ/test/pipelines/test/integ.newpipeline-with-file-system-locations.js.snapshot/cdkintegcodepipelinewithfilesystemlocationsDefaultTestDeployAssert3E26E748.template.json
  packages/@aws-cdk-testing/framework-integ/test/pipelines/test/integ.newpipeline-with-file-system-locations.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/pipelines/test/integ.newpipeline-with-file-system-locations.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/pipelines/test/integ.newpipeline-with-file-system-locations.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/pipelines/test/integ.newpipeline-with-file-system-locations.ts
  packages/aws-cdk-lib/pipelines/README.md
  packages/aws-cdk-lib/pipelines/lib/codepipeline/codebuild-step.ts
  packages/aws-cdk-lib/pipelines/lib/codepipeline/codepipeline.ts
  packages/aws-cdk-lib/pipelines/lib/codepipeline/private/codebuild-factory.ts
  packages/aws-cdk-lib/pipelines/test/codepipeline/codebuild-step.test.ts
Labels: p2, feature-request, effort/medium, beginning-contributor

#24960 fix(servicecatalogappregistry): Imported attribute group cannot be associated to an application
  packages/@aws-cdk/aws-servicecatalogappregistry/lib/attribute-group.ts
  packages/@aws-cdk/aws-servicecatalogappregistry/test/attribute-group.test.ts
  packages/@aws-cdk/aws-servicecatalogappregistry/test/integ.attribute-group.js.snapshot/integ-servicecatalogappregistry-attribute-group.assets.json
  packages/@aws-cdk/aws-servicecatalogappregistry/test/integ.attribute-group.js.snapshot/integ-servicecatalogappregistry-attribute-group.template.json
  packages/@aws-cdk/aws-servicecatalogappregistry/test/integ.attribute-group.js.snapshot/manifest.json
  packages/@aws-cdk/aws-servicecatalogappregistry/test/integ.attribute-group.js.snapshot/tree.json
  packages/@aws-cdk/aws-servicecatalogappregistry/test/integ.attribute-group.ts
Labels: p2, repeat-contributor

#24965 chore(bump): bump script doesn't exit with 1 if anything fails
  scripts/bump.js
Labels: p2, contribution/core

#24968 chore(merge-back): 2.73.0
  CHANGELOG.v2.alpha.md
  CHANGELOG.v2.md
  version.v2.json
Labels: p2, pr/no-squash, auto-approve

#24963 feat(ec2): added ulimits property to ContainerDefinitionOptions
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs/test/ec2/integ.task-definition-container-ulimits.d.ts
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs/test/ec2/integ.task-definition-container-ulimits.js
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs/test/ec2/integ.task-definition-container-ulimits.js.snapshot/TaskDefinitionContainerUlimitsDefaultTestDeployAssert56AB1D42.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs/test/ec2/integ.task-definition-container-ulimits.js.snapshot/TaskDefinitionContainerUlimitsDefaultTestDeployAssert56AB1D42.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs/test/ec2/integ.task-definition-container-ulimits.js.snapshot/aws-ecs-task-definition-container-ulimits.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs/test/ec2/integ.task-definition-container-ulimits.js.snapshot/aws-ecs-task-definition-container-ulimits.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs/test/ec2/integ.task-definition-container-ulimits.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs/test/ec2/integ.task-definition-container-ulimits.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs/test/ec2/integ.task-definition-container-ulimits.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs/test/ec2/integ.task-definition-container-ulimits.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs/test/ec2/integ.task-definition-container-ulimits.ts
  packages/aws-cdk-lib/aws-ecs/README.md
  packages/aws-cdk-lib/aws-ecs/lib/container-definition.ts
  packages/aws-cdk-lib/aws-ecs/test/task-definition.test.ts
Labels: p2, feature-request, effort/small, valued-contributor

#24745 feat(ses): event destinations for configuration sets
  packages/@aws-cdk-testing/framework-integ/test/aws-apigateway/test/integ.cloudwatch-disabled.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-ses/test/integ.configuration-set.js.snapshot/ConfigurationSetIntegDefaultTestDeployAssert9B6AD46A.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ses/test/integ.configuration-set.js.snapshot/cdk-ses-configuration-set-integ.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ses/test/integ.configuration-set.js.snapshot/cdk-ses-configuration-set-integ.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ses/test/integ.configuration-set.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ses/test/integ.configuration-set.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ses/test/integ.configuration-set.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ses/test/integ.configuration-set.ts
  packages/aws-cdk-lib/aws-ses/README.md
  packages/aws-cdk-lib/aws-ses/lib/configuration-set-event-destination.ts
  packages/aws-cdk-lib/aws-ses/lib/configuration-set.ts
  packages/aws-cdk-lib/aws-ses/lib/index.ts
  packages/aws-cdk-lib/aws-ses/test/configuration-set-event-destination.test.ts
Labels: p2, distinguished-contributor

#24970 chore: add some memory debugging
  build.sh
  buildspec.yaml
  scripts/log-memory.js
Labels: p2, contribution/core

#24949 feat(step-functions-tasks): Support PropagatedTagSource property for EcsRunTask
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/ecs/integ.fargate-run-task.js
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/ecs/integ.fargate-run-task.js.snapshot/aws-sfn-tasks-ecs-fargate-integ.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/ecs/integ.fargate-run-task.js.snapshot/aws-sfn-tasks-ecs-fargate-integ.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/ecs/integ.fargate-run-task.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/ecs/integ.fargate-run-task.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/ecs/integ.fargate-run-task.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/ecs/integ.fargate-run-task.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/ecs/integ.fargate-run-task.ts
  packages/aws-cdk-lib/aws-stepfunctions-tasks/README.md
  packages/aws-cdk-lib/aws-stepfunctions-tasks/lib/ecs/run-task.ts
  packages/aws-cdk-lib/aws-stepfunctions-tasks/test/ecs/run-tasks.test.ts
Labels: p1, feature-request, effort/small, beginning-contributor

#24982 chore: raise memory limit for bump in pipeline build
  buildspec.yaml
Labels: p2, contribution/core

#24981 fix(cloudwatch): `p100` statistic is no longer recognized
  packages/aws-cdk-lib/aws-cloudwatch/lib/alarm.ts
  packages/aws-cdk-lib/aws-cloudwatch/lib/private/statistic.ts
  packages/aws-cdk-lib/aws-cloudwatch/test/alarm.test.ts
  packages/aws-cdk-lib/aws-cloudwatch/test/metrics.test.ts
Labels: bug, p0, effort/small, contribution/core, pr-linter/exempt-integ-test

#24945 feat(pipelines): allow artifactBucket to be overridden
  packages/@aws-cdk-testing/framework-integ/test/pipelines/test/integ.pipeline-with-artifact-bucket.js.snapshot/ClusterTestDefaultTestDeployAssert6A1BBA9D.assets.json
  packages/@aws-cdk-testing/framework-integ/test/pipelines/test/integ.pipeline-with-artifact-bucket.js.snapshot/ClusterTestDefaultTestDeployAssert6A1BBA9D.template.json
  packages/@aws-cdk-testing/framework-integ/test/pipelines/test/integ.pipeline-with-artifact-bucket.js.snapshot/PipelineStack.assets.json
  packages/@aws-cdk-testing/framework-integ/test/pipelines/test/integ.pipeline-with-artifact-bucket.js.snapshot/PipelineStack.template.json
  packages/@aws-cdk-testing/framework-integ/test/pipelines/test/integ.pipeline-with-artifact-bucket.js.snapshot/PipelineStackPipeline9DB740AF.dot
  packages/@aws-cdk-testing/framework-integ/test/pipelines/test/integ.pipeline-with-artifact-bucket.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/pipelines/test/integ.pipeline-with-artifact-bucket.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/pipelines/test/integ.pipeline-with-artifact-bucket.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/pipelines/test/integ.pipeline-with-artifact-bucket.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/pipelines/test/integ.pipeline-with-artifact-bucket.ts
  packages/aws-cdk-lib/pipelines/lib/codepipeline/codepipeline.ts
  packages/aws-cdk-lib/pipelines/test/codepipeline/codepipeline.test.ts
Labels: p2, contribution/core, pr-linter/exempt-readme

#24995 docs: add warning about unwanted deletion of replicas in docs
  packages/aws-cdk-lib/aws-dynamodb/lib/table.ts
Labels: p2, contribution/core

#24443 fix(core): Add stage prefix to stack name shortening process
  packages/aws-cdk-lib/core/lib/private/unique-resource-name.ts
  packages/aws-cdk-lib/core/lib/stack.ts
  packages/aws-cdk-lib/core/test/stage.test.ts
Labels: bug, p2, pr-linter/exempt-integ-test, beginning-contributor

#25035 chore: build fails if not running in git repo
  tools/@aws-cdk/cdk-release/lib/lifecycles/bumphooks.ts
Labels: p2, contribution/core

#25029 chore(region-info): turn into a `cdk-copy`ed package
  packages/@aws-cdk/region-info/.eslintrc.js
  packages/@aws-cdk/region-info/.gitignore
  packages/@aws-cdk/region-info/README.md
  packages/@aws-cdk/region-info/build-tools/fact-tables.ts
  packages/@aws-cdk/region-info/build-tools/generate-static-data.ts
  packages/@aws-cdk/region-info/build-tools/generate.sh
  packages/@aws-cdk/region-info/lib/.gitignore
  packages/@aws-cdk/region-info/lib/aws-entities.ts
  packages/@aws-cdk/region-info/lib/default.ts
  packages/@aws-cdk/region-info/lib/fact.ts
  packages/@aws-cdk/region-info/lib/index.ts
  packages/@aws-cdk/region-info/lib/region-info.ts
  packages/@aws-cdk/region-info/package.json
  packages/@aws-cdk/region-info/rosetta/default.ts-fixture
  packages/@aws-cdk/region-info/test/__snapshots__/region-info.test.js.snap
  packages/@aws-cdk/region-info/test/default.test.ts
  packages/@aws-cdk/region-info/test/fact.test.ts
  packages/@aws-cdk/region-info/test/region-info.test.ts
  packages/aws-cdk-lib/package.json
  packages/aws-cdk-lib/region-info/build-tools/generate.sh
  tools/@aws-cdk/cdk-build-tools/bin/cdk-copy.ts
Labels: p2, contribution/core

#25077 chore: rename aws-neptune → aws-neptune-alpha
  packages/@aws-cdk/aws-neptune-alpha/.eslintrc.js
  packages/@aws-cdk/aws-neptune-alpha/.gitignore
  packages/@aws-cdk/aws-neptune-alpha/.npmignore
  packages/@aws-cdk/aws-neptune-alpha/LICENSE
  packages/@aws-cdk/aws-neptune-alpha/NOTICE
  packages/@aws-cdk/aws-neptune-alpha/README.md
  packages/@aws-cdk/aws-neptune-alpha/jest.config.js
  packages/@aws-cdk/aws-neptune-alpha/lib/cluster.ts
  packages/@aws-cdk/aws-neptune-alpha/lib/endpoint.ts
  packages/@aws-cdk/aws-neptune-alpha/lib/index.ts
  packages/@aws-cdk/aws-neptune-alpha/lib/instance.ts
  packages/@aws-cdk/aws-neptune-alpha/lib/parameter-group.ts
  packages/@aws-cdk/aws-neptune-alpha/lib/subnet-group.ts
  packages/@aws-cdk/aws-neptune-alpha/package.json
  packages/@aws-cdk/aws-neptune-alpha/rosetta/default.ts-fixture
  packages/@aws-cdk/aws-neptune-alpha/rosetta/with-cluster.ts-fixture
  packages/@aws-cdk/aws-neptune-alpha/test/cluster.test.ts
  packages/@aws-cdk/aws-neptune-alpha/test/endpoint.test.ts
  packages/@aws-cdk/aws-neptune-alpha/test/instance.test.ts
  packages/@aws-cdk/aws-neptune-alpha/test/integ.cluster-ev12.js.snapshot/ClusterTestDefaultTestDeployAssert6A1BBA9D.assets.json
  packages/@aws-cdk/aws-neptune-alpha/test/integ.cluster-ev12.js.snapshot/ClusterTestDefaultTestDeployAssert6A1BBA9D.template.json
  packages/@aws-cdk/aws-neptune-alpha/test/integ.cluster-ev12.js.snapshot/aws-cdk-neptune-integ.assets.json
  packages/@aws-cdk/aws-neptune-alpha/test/integ.cluster-ev12.js.snapshot/aws-cdk-neptune-integ.template.json
  packages/@aws-cdk/aws-neptune-alpha/test/integ.cluster-ev12.js.snapshot/cdk.out
  packages/@aws-cdk/aws-neptune-alpha/test/integ.cluster-ev12.js.snapshot/integ.json
  packages/@aws-cdk/aws-neptune-alpha/test/integ.cluster-ev12.js.snapshot/manifest.json
  packages/@aws-cdk/aws-neptune-alpha/test/integ.cluster-ev12.js.snapshot/tree.json
  packages/@aws-cdk/aws-neptune-alpha/test/integ.cluster-ev12.ts
  packages/@aws-cdk/aws-neptune-alpha/test/integ.cluster.js.snapshot/ClusterTestDefaultTestDeployAssert6A1BBA9D.assets.json
  packages/@aws-cdk/aws-neptune-alpha/test/integ.cluster.js.snapshot/ClusterTestDefaultTestDeployAssert6A1BBA9D.template.json
  packages/@aws-cdk/aws-neptune-alpha/test/integ.cluster.js.snapshot/asset.d01c24641c7d8cb6488393ffceaefff282370a9a522bf9d77b21da73fa257347/index.d.ts
  packages/@aws-cdk/aws-neptune-alpha/test/integ.cluster.js.snapshot/asset.d01c24641c7d8cb6488393ffceaefff282370a9a522bf9d77b21da73fa257347/index.js
  packages/@aws-cdk/aws-neptune-alpha/test/integ.cluster.js.snapshot/asset.d01c24641c7d8cb6488393ffceaefff282370a9a522bf9d77b21da73fa257347/index.ts
  packages/@aws-cdk/aws-neptune-alpha/test/integ.cluster.js.snapshot/aws-cdk-neptune-integ.assets.json
  packages/@aws-cdk/aws-neptune-alpha/test/integ.cluster.js.snapshot/aws-cdk-neptune-integ.template.json
  packages/@aws-cdk/aws-neptune-alpha/test/integ.cluster.js.snapshot/cdk.out
  packages/@aws-cdk/aws-neptune-alpha/test/integ.cluster.js.snapshot/integ.json
  packages/@aws-cdk/aws-neptune-alpha/test/integ.cluster.js.snapshot/manifest.json
  packages/@aws-cdk/aws-neptune-alpha/test/integ.cluster.js.snapshot/tree.json
  packages/@aws-cdk/aws-neptune-alpha/test/integ.cluster.ts
  packages/@aws-cdk/aws-neptune-alpha/test/parameter-group.test.ts
  packages/@aws-cdk/aws-neptune-alpha/test/subnet-group.test.ts
Labels: p2, contribution/core

#25018 feat(sagemaker): support dlc images in sagemaker model
  packages/@aws-cdk/aws-sagemaker/README.md
  packages/@aws-cdk/aws-sagemaker/lib/container-image.ts
  packages/@aws-cdk/aws-sagemaker/test/integ.model.js.snapshot/aws-cdk-sagemaker-model.assets.json
  packages/@aws-cdk/aws-sagemaker/test/integ.model.js.snapshot/aws-cdk-sagemaker-model.template.json
  packages/@aws-cdk/aws-sagemaker/test/integ.model.js.snapshot/cdk.out
  packages/@aws-cdk/aws-sagemaker/test/integ.model.js.snapshot/integ.json
  packages/@aws-cdk/aws-sagemaker/test/integ.model.js.snapshot/integtestmodelDefaultTestDeployAssertCF40BD53.assets.json
  packages/@aws-cdk/aws-sagemaker/test/integ.model.js.snapshot/manifest.json
  packages/@aws-cdk/aws-sagemaker/test/integ.model.js.snapshot/tree.json
  packages/@aws-cdk/aws-sagemaker/test/integ.model.ts
  packages/@aws-cdk/aws-sagemaker/test/model.test.ts
Labels: p2, @aws-cdk/aws-sagemaker, contribution/core

#25041 fix: ecr policy warning always throws
  packages/aws-cdk-lib/aws-ecr/lib/repository.ts
  packages/aws-cdk-lib/aws-ecr/test/repository.test.ts
Labels: bug, p1, effort/small, contribution/core, pr-linter/exempt-integ-test, pr-linter/exemption-requested

#25046 chore: rename cli-lib → cli-lib-alpha
  packages/@aws-cdk/cli-lib-alpha/.eslintrc.js
  packages/@aws-cdk/cli-lib-alpha/.gitignore
  packages/@aws-cdk/cli-lib-alpha/.npmignore
  packages/@aws-cdk/cli-lib-alpha/LICENSE
  packages/@aws-cdk/cli-lib-alpha/NOTICE
  packages/@aws-cdk/cli-lib-alpha/README.md
  packages/@aws-cdk/cli-lib-alpha/THIRD_PARTY_LICENSES
  packages/@aws-cdk/cli-lib-alpha/jest.config.js
  packages/@aws-cdk/cli-lib-alpha/lib/cli.ts
  packages/@aws-cdk/cli-lib-alpha/lib/commands/common.ts
  packages/@aws-cdk/cli-lib-alpha/lib/commands/deploy.ts
  packages/@aws-cdk/cli-lib-alpha/lib/commands/destroy.ts
  packages/@aws-cdk/cli-lib-alpha/lib/commands/index.ts
  packages/@aws-cdk/cli-lib-alpha/lib/commands/list.ts
  packages/@aws-cdk/cli-lib-alpha/lib/commands/synth.ts
  packages/@aws-cdk/cli-lib-alpha/lib/index.ts
  packages/@aws-cdk/cli-lib-alpha/package.json
  packages/@aws-cdk/cli-lib-alpha/rosetta/default.ts-fixture
  packages/@aws-cdk/cli-lib-alpha/rosetta/imports.ts-fixture
  packages/@aws-cdk/cli-lib-alpha/rosetta/producer.ts-fixture
  packages/@aws-cdk/cli-lib-alpha/test/cli.test.ts
  packages/@aws-cdk/cli-lib-alpha/test/commands.test.ts
  packages/@aws-cdk/cli-lib-alpha/test/test-app/app.ts
  packages/@aws-cdk/cli-lib-alpha/test/test-app/cdk.json
Labels: p2, contribution/core

#24770 fix(s3): deprecate unencrypted encryption configuration for s3 bucket
  packages/@aws-cdk-testing/framework-integ/test/aws-cloudtrail/test/integ.cloudtrail-insight.ts
  packages/@aws-cdk/aws-glue/README.md
  packages/@aws-cdk/aws-glue/lib/table.ts
  packages/@aws-cdk/aws-glue/test/integ.partition-index.js.snapshot/asset.a268caa53756f51bda8ad5f499be4ed8484a81b314811806fbb66f874837c476/index.js
  packages/@aws-cdk/aws-glue/test/integ.partition-index.js.snapshot/aws-cdk-glue.assets.json
  packages/@aws-cdk/aws-glue/test/integ.partition-index.js.snapshot/aws-cdk-glue.template.json
  packages/@aws-cdk/aws-glue/test/integ.partition-index.js.snapshot/cdk.out
  packages/@aws-cdk/aws-glue/test/integ.partition-index.js.snapshot/integ.json
  packages/@aws-cdk/aws-glue/test/integ.partition-index.js.snapshot/manifest.json
  packages/@aws-cdk/aws-glue/test/integ.partition-index.js.snapshot/tree.json
  packages/@aws-cdk/aws-glue/test/integ.partition-index.ts
  packages/@aws-cdk/aws-glue/test/integ.table.js.snapshot/aws-cdk-glue.assets.json
  packages/@aws-cdk/aws-glue/test/integ.table.js.snapshot/aws-cdk-glue.template.json
  packages/@aws-cdk/aws-glue/test/integ.table.js.snapshot/cdk.out
  packages/@aws-cdk/aws-glue/test/integ.table.js.snapshot/integ.json
  packages/@aws-cdk/aws-glue/test/integ.table.js.snapshot/manifest.json
  packages/@aws-cdk/aws-glue/test/integ.table.js.snapshot/tree.json
  packages/@aws-cdk/aws-glue/test/table.test.ts
  packages/aws-cdk-lib/aws-cloudtrail/lib/cloudtrail.ts
  packages/aws-cdk-lib/aws-cloudtrail/test/cloudtrail.test.ts
  packages/aws-cdk-lib/aws-cloudtrail/test/integ.cloudtrail-supplied-bucket.lit.ts
  packages/aws-cdk-lib/aws-ec2/lib/vpc-flow-logs.ts
  packages/aws-cdk-lib/aws-s3/README.md
  packages/aws-cdk-lib/aws-s3/lib/bucket.ts
  packages/aws-cdk-lib/aws-s3/test/bucket.test.ts
Labels: p2, valued-contributor

#25051 chore: rename aws-route53resolver → aws-route53resolver-alpha
  packages/@aws-cdk/aws-route53resolver-alpha/.eslintrc.js
  packages/@aws-cdk/aws-route53resolver-alpha/.gitignore
  packages/@aws-cdk/aws-route53resolver-alpha/.npmignore
  packages/@aws-cdk/aws-route53resolver-alpha/LICENSE
  packages/@aws-cdk/aws-route53resolver-alpha/NOTICE
  packages/@aws-cdk/aws-route53resolver-alpha/README.md
  packages/@aws-cdk/aws-route53resolver-alpha/jest.config.js
  packages/@aws-cdk/aws-route53resolver-alpha/lib/firewall-domain-list.ts
  packages/@aws-cdk/aws-route53resolver-alpha/lib/firewall-rule-group-association.ts
  packages/@aws-cdk/aws-route53resolver-alpha/lib/firewall-rule-group.ts
  packages/@aws-cdk/aws-route53resolver-alpha/lib/index.ts
  packages/@aws-cdk/aws-route53resolver-alpha/package.json
  packages/@aws-cdk/aws-route53resolver-alpha/rosetta/default.ts-fixture
  packages/@aws-cdk/aws-route53resolver-alpha/test/domains.txt
  packages/@aws-cdk/aws-route53resolver-alpha/test/firewall-domain-list.test.ts
  packages/@aws-cdk/aws-route53resolver-alpha/test/firewall-rule-group.test.ts
  packages/@aws-cdk/aws-route53resolver-alpha/test/integ.firewall.js.snapshot/asset.e820b3f07bf66854be0dfd6f3ec357a10d644f2011069e5ad07d42f4f89ed35a.txt
  packages/@aws-cdk/aws-route53resolver-alpha/test/integ.firewall.js.snapshot/cdk-route53-resolver-firewall.assets.json
  packages/@aws-cdk/aws-route53resolver-alpha/test/integ.firewall.js.snapshot/cdk-route53-resolver-firewall.template.json
  packages/@aws-cdk/aws-route53resolver-alpha/test/integ.firewall.js.snapshot/cdk.out
  packages/@aws-cdk/aws-route53resolver-alpha/test/integ.firewall.js.snapshot/integ.json
  packages/@aws-cdk/aws-route53resolver-alpha/test/integ.firewall.js.snapshot/manifest.json
  packages/@aws-cdk/aws-route53resolver-alpha/test/integ.firewall.js.snapshot/tree.json
  packages/@aws-cdk/aws-route53resolver-alpha/test/integ.firewall.ts
Labels: p2, contribution/core

#25049 chore: rename aws-codestar → aws-codestar-alpha
  packages/@aws-cdk/aws-codestar-alpha/.eslintrc.js
  packages/@aws-cdk/aws-codestar-alpha/.gitignore
  packages/@aws-cdk/aws-codestar-alpha/.npmignore
  packages/@aws-cdk/aws-codestar-alpha/LICENSE
  packages/@aws-cdk/aws-codestar-alpha/NOTICE
  packages/@aws-cdk/aws-codestar-alpha/README.md
  packages/@aws-cdk/aws-codestar-alpha/jest.config.js
  packages/@aws-cdk/aws-codestar-alpha/lib/github-repository.ts
  packages/@aws-cdk/aws-codestar-alpha/lib/index.ts
  packages/@aws-cdk/aws-codestar-alpha/package.json
  packages/@aws-cdk/aws-codestar-alpha/rosetta/default.ts-fixture
  packages/@aws-cdk/aws-codestar-alpha/test/codestar.test.ts
Labels: p2, contribution/core

#25085 chore(batch): delete leftover compute-environment file
  packages/@aws-cdk/aws-batch/lib/compute-environment.ts
Labels: p2, contribution/core

#25057 chore: rename aws-s3objectlambda → aws-s3objectlambda-alpha
  packages/@aws-cdk/aws-s3objectlambda-alpha/.eslintrc.js
  packages/@aws-cdk/aws-s3objectlambda-alpha/.gitignore
  packages/@aws-cdk/aws-s3objectlambda-alpha/.npmignore
  packages/@aws-cdk/aws-s3objectlambda-alpha/LICENSE
  packages/@aws-cdk/aws-s3objectlambda-alpha/NOTICE
  packages/@aws-cdk/aws-s3objectlambda-alpha/README.md
  packages/@aws-cdk/aws-s3objectlambda-alpha/jest.config.js
  packages/@aws-cdk/aws-s3objectlambda-alpha/lib/access-point.ts
  packages/@aws-cdk/aws-s3objectlambda-alpha/lib/index.ts
  packages/@aws-cdk/aws-s3objectlambda-alpha/package.json
  packages/@aws-cdk/aws-s3objectlambda-alpha/test/integ.s3objectlambda.js.snapshot/aws-s3-object-lambda.assets.json
  packages/@aws-cdk/aws-s3objectlambda-alpha/test/integ.s3objectlambda.js.snapshot/aws-s3-object-lambda.template.json
  packages/@aws-cdk/aws-s3objectlambda-alpha/test/integ.s3objectlambda.js.snapshot/cdk.out
  packages/@aws-cdk/aws-s3objectlambda-alpha/test/integ.s3objectlambda.js.snapshot/integ.json
  packages/@aws-cdk/aws-s3objectlambda-alpha/test/integ.s3objectlambda.js.snapshot/manifest.json
  packages/@aws-cdk/aws-s3objectlambda-alpha/test/integ.s3objectlambda.js.snapshot/tree.json
  packages/@aws-cdk/aws-s3objectlambda-alpha/test/integ.s3objectlambda.ts
  packages/@aws-cdk/aws-s3objectlambda-alpha/test/s3objectlambda.test.ts
Labels: p2, contribution/core

#25050 chore: rename aws-cognito-identitypool → aws-cognito-identitypool-alpha
  packages/@aws-cdk/aws-cognito-identitypool-alpha/.eslintrc.js
  packages/@aws-cdk/aws-cognito-identitypool-alpha/.gitignore
  packages/@aws-cdk/aws-cognito-identitypool-alpha/.npmignore
  packages/@aws-cdk/aws-cognito-identitypool-alpha/LICENSE
  packages/@aws-cdk/aws-cognito-identitypool-alpha/NOTICE
  packages/@aws-cdk/aws-cognito-identitypool-alpha/README.md
  packages/@aws-cdk/aws-cognito-identitypool-alpha/jest.config.js
  packages/@aws-cdk/aws-cognito-identitypool-alpha/lib/identitypool-role-attachment.ts
  packages/@aws-cdk/aws-cognito-identitypool-alpha/lib/identitypool-user-pool-authentication-provider.ts
  packages/@aws-cdk/aws-cognito-identitypool-alpha/lib/identitypool.ts
  packages/@aws-cdk/aws-cognito-identitypool-alpha/lib/index.ts
  packages/@aws-cdk/aws-cognito-identitypool-alpha/package.json
  packages/@aws-cdk/aws-cognito-identitypool-alpha/rosetta/default.ts-fixture
  packages/@aws-cdk/aws-cognito-identitypool-alpha/test/identitypool.test.ts
  packages/@aws-cdk/aws-cognito-identitypool-alpha/test/integ.identitypool.js.snapshot/cdk.out
  packages/@aws-cdk/aws-cognito-identitypool-alpha/test/integ.identitypool.js.snapshot/integ-identitypool.assets.json
  packages/@aws-cdk/aws-cognito-identitypool-alpha/test/integ.identitypool.js.snapshot/integ-identitypool.template.json
  packages/@aws-cdk/aws-cognito-identitypool-alpha/test/integ.identitypool.js.snapshot/integ.json
  packages/@aws-cdk/aws-cognito-identitypool-alpha/test/integ.identitypool.js.snapshot/manifest.json
  packages/@aws-cdk/aws-cognito-identitypool-alpha/test/integ.identitypool.js.snapshot/tree.json
  packages/@aws-cdk/aws-cognito-identitypool-alpha/test/integ.identitypool.ts
Labels: p2, contribution/core

#25064 chore: rename aws-ivs → aws-ivs-alpha
  packages/@aws-cdk/aws-ivs-alpha/.eslintrc.js
  packages/@aws-cdk/aws-ivs-alpha/.gitignore
  packages/@aws-cdk/aws-ivs-alpha/.npmignore
  packages/@aws-cdk/aws-ivs-alpha/LICENSE
  packages/@aws-cdk/aws-ivs-alpha/NOTICE
  packages/@aws-cdk/aws-ivs-alpha/README.md
  packages/@aws-cdk/aws-ivs-alpha/jest.config.js
  packages/@aws-cdk/aws-ivs-alpha/lib/channel.ts
  packages/@aws-cdk/aws-ivs-alpha/lib/index.ts
  packages/@aws-cdk/aws-ivs-alpha/lib/playback-key-pair.ts
  packages/@aws-cdk/aws-ivs-alpha/lib/stream-key.ts
  packages/@aws-cdk/aws-ivs-alpha/package.json
  packages/@aws-cdk/aws-ivs-alpha/rosetta/default.ts-fixture
  packages/@aws-cdk/aws-ivs-alpha/rosetta/with-channel.ts-fixture
  packages/@aws-cdk/aws-ivs-alpha/test/integ.ivs.js.snapshot/aws-cdk-ivs.assets.json
  packages/@aws-cdk/aws-ivs-alpha/test/integ.ivs.js.snapshot/aws-cdk-ivs.template.json
  packages/@aws-cdk/aws-ivs-alpha/test/integ.ivs.js.snapshot/cdk.out
  packages/@aws-cdk/aws-ivs-alpha/test/integ.ivs.js.snapshot/integ.json
  packages/@aws-cdk/aws-ivs-alpha/test/integ.ivs.js.snapshot/ivstestDefaultTestDeployAssertDCE80D47.assets.json
  packages/@aws-cdk/aws-ivs-alpha/test/integ.ivs.js.snapshot/ivstestDefaultTestDeployAssertDCE80D47.template.json
  packages/@aws-cdk/aws-ivs-alpha/test/integ.ivs.js.snapshot/manifest.json
  packages/@aws-cdk/aws-ivs-alpha/test/integ.ivs.js.snapshot/tree.json
  packages/@aws-cdk/aws-ivs-alpha/test/integ.ivs.ts
  packages/@aws-cdk/aws-ivs-alpha/test/ivs.test.ts
Labels: p2, contribution/core

#25056 chore: rename integ-tests → integ-tests-alpha
  packages/@aws-cdk/integ-tests-alpha/.eslintrc.js
  packages/@aws-cdk/integ-tests-alpha/.gitignore
  packages/@aws-cdk/integ-tests-alpha/.npmignore
  packages/@aws-cdk/integ-tests-alpha/LICENSE
  packages/@aws-cdk/integ-tests-alpha/NOTICE
  packages/@aws-cdk/integ-tests-alpha/README.md
  packages/@aws-cdk/integ-tests-alpha/jest.config.js
  packages/@aws-cdk/integ-tests-alpha/lib/assertions/api-call-base.ts
  packages/@aws-cdk/integ-tests-alpha/lib/assertions/assertions.ts
  packages/@aws-cdk/integ-tests-alpha/lib/assertions/common.ts
  packages/@aws-cdk/integ-tests-alpha/lib/assertions/index.ts
  packages/@aws-cdk/integ-tests-alpha/lib/assertions/match.ts
  packages/@aws-cdk/integ-tests-alpha/lib/assertions/private/deploy-assert.ts
  packages/@aws-cdk/integ-tests-alpha/lib/assertions/private/hash.ts
  packages/@aws-cdk/integ-tests-alpha/lib/assertions/providers/index.ts
  packages/@aws-cdk/integ-tests-alpha/lib/assertions/providers/lambda-handler/assertion.ts
  packages/@aws-cdk/integ-tests-alpha/lib/assertions/providers/lambda-handler/base.ts
  packages/@aws-cdk/integ-tests-alpha/lib/assertions/providers/lambda-handler/index.ts
  packages/@aws-cdk/integ-tests-alpha/lib/assertions/providers/lambda-handler/sdk.ts
  packages/@aws-cdk/integ-tests-alpha/lib/assertions/providers/lambda-handler/types.ts
  packages/@aws-cdk/integ-tests-alpha/lib/assertions/providers/lambda-handler/utils.ts
  packages/@aws-cdk/integ-tests-alpha/lib/assertions/providers/provider.ts
  packages/@aws-cdk/integ-tests-alpha/lib/assertions/providers/sdk-api-metadata.json
  packages/@aws-cdk/integ-tests-alpha/lib/assertions/sdk.ts
  packages/@aws-cdk/integ-tests-alpha/lib/assertions/types.ts
  packages/@aws-cdk/integ-tests-alpha/lib/assertions/waiter-state-machine.ts
  packages/@aws-cdk/integ-tests-alpha/lib/index.ts
  packages/@aws-cdk/integ-tests-alpha/lib/manifest-synthesizer.ts
  packages/@aws-cdk/integ-tests-alpha/lib/manifest-writer.ts
  packages/@aws-cdk/integ-tests-alpha/lib/test-case.ts
  packages/@aws-cdk/integ-tests-alpha/package.json
  packages/@aws-cdk/integ-tests-alpha/rosetta/default.ts-fixture
  packages/@aws-cdk/integ-tests-alpha/test/assertions/deploy-assert.test.ts
  packages/@aws-cdk/integ-tests-alpha/test/assertions/private/hash.test.ts
  packages/@aws-cdk/integ-tests-alpha/test/assertions/providers/integ.assertions.js.snapshot/Assertions.assets.json
  packages/@aws-cdk/integ-tests-alpha/test/assertions/providers/integ.assertions.js.snapshot/Assertions.template.json
  packages/@aws-cdk/integ-tests-alpha/test/assertions/providers/integ.assertions.js.snapshot/AssertionsTestDefaultTestDeployAssertDC0672BB.assets.json
  packages/@aws-cdk/integ-tests-alpha/test/assertions/providers/integ.assertions.js.snapshot/AssertionsTestDefaultTestDeployAssertDC0672BB.template.json
  packages/@aws-cdk/integ-tests-alpha/test/assertions/providers/integ.assertions.js.snapshot/cdk.out
  packages/@aws-cdk/integ-tests-alpha/test/assertions/providers/integ.assertions.js.snapshot/integ.json
  packages/@aws-cdk/integ-tests-alpha/test/assertions/providers/integ.assertions.js.snapshot/manifest.json
  packages/@aws-cdk/integ-tests-alpha/test/assertions/providers/integ.assertions.js.snapshot/tree.json
  packages/@aws-cdk/integ-tests-alpha/test/assertions/providers/integ.assertions.ts
  packages/@aws-cdk/integ-tests-alpha/test/assertions/providers/lambda-handler/assertion.test.ts
  packages/@aws-cdk/integ-tests-alpha/test/assertions/providers/lambda-handler/base.test.ts
  packages/@aws-cdk/integ-tests-alpha/test/assertions/providers/lambda-handler/sdk.test.ts
  packages/@aws-cdk/integ-tests-alpha/test/assertions/providers/provider.test.ts
  packages/@aws-cdk/integ-tests-alpha/test/assertions/sdk.test.ts
  packages/@aws-cdk/integ-tests-alpha/test/manifest-synthesizer.test.ts
  packages/@aws-cdk/integ-tests-alpha/test/manifest-writer.test.ts
Labels: p2, contribution/core

#25061 chore: rename aws-cloud9 → aws-cloud9-alpha
  packages/@aws-cdk/aws-cloud9-alpha/.eslintrc.js
  packages/@aws-cdk/aws-cloud9-alpha/.gitignore
  packages/@aws-cdk/aws-cloud9-alpha/.npmignore
  packages/@aws-cdk/aws-cloud9-alpha/LICENSE
  packages/@aws-cdk/aws-cloud9-alpha/NOTICE
  packages/@aws-cdk/aws-cloud9-alpha/README.md
  packages/@aws-cdk/aws-cloud9-alpha/jest.config.js
  packages/@aws-cdk/aws-cloud9-alpha/lib/environment.ts
  packages/@aws-cdk/aws-cloud9-alpha/lib/index.ts
  packages/@aws-cdk/aws-cloud9-alpha/package.json
  packages/@aws-cdk/aws-cloud9-alpha/rosetta/default.ts-fixture
  packages/@aws-cdk/aws-cloud9-alpha/test/cloud9.environment.test.ts
  packages/@aws-cdk/aws-cloud9-alpha/test/integ.cloud9.js.snapshot/C9Stack.assets.json
  packages/@aws-cdk/aws-cloud9-alpha/test/integ.cloud9.js.snapshot/C9Stack.template.json
  packages/@aws-cdk/aws-cloud9-alpha/test/integ.cloud9.js.snapshot/cdk.out
  packages/@aws-cdk/aws-cloud9-alpha/test/integ.cloud9.js.snapshot/integ.json
  packages/@aws-cdk/aws-cloud9-alpha/test/integ.cloud9.js.snapshot/manifest.json
  packages/@aws-cdk/aws-cloud9-alpha/test/integ.cloud9.js.snapshot/tree.json
  packages/@aws-cdk/aws-cloud9-alpha/test/integ.cloud9.ts
  packages/@aws-cdk/aws-cloud9-alpha/test/integ.connection-type.js.snapshot/C9ConnectionTypeStack.assets.json
  packages/@aws-cdk/aws-cloud9-alpha/test/integ.connection-type.js.snapshot/C9ConnectionTypeStack.template.json
  packages/@aws-cdk/aws-cloud9-alpha/test/integ.connection-type.js.snapshot/cdk.out
  packages/@aws-cdk/aws-cloud9-alpha/test/integ.connection-type.js.snapshot/cloud9connectiontypeDefaultTestDeployAssert401C3608.assets.json
  packages/@aws-cdk/aws-cloud9-alpha/test/integ.connection-type.js.snapshot/cloud9connectiontypeDefaultTestDeployAssert401C3608.template.json
  packages/@aws-cdk/aws-cloud9-alpha/test/integ.connection-type.js.snapshot/integ.json
  packages/@aws-cdk/aws-cloud9-alpha/test/integ.connection-type.js.snapshot/manifest.json
  packages/@aws-cdk/aws-cloud9-alpha/test/integ.connection-type.js.snapshot/tree.json
  packages/@aws-cdk/aws-cloud9-alpha/test/integ.connection-type.ts
  packages/@aws-cdk/aws-cloud9-alpha/test/integ.image-id.js.snapshot/ImageIdIntegDefaultTestDeployAssert7D293EEE.assets.json
  packages/@aws-cdk/aws-cloud9-alpha/test/integ.image-id.js.snapshot/ImageIdIntegDefaultTestDeployAssert7D293EEE.template.json
  packages/@aws-cdk/aws-cloud9-alpha/test/integ.image-id.js.snapshot/cdk.out
  packages/@aws-cdk/aws-cloud9-alpha/test/integ.image-id.js.snapshot/cloud9-imageid-integ.assets.json
  packages/@aws-cdk/aws-cloud9-alpha/test/integ.image-id.js.snapshot/cloud9-imageid-integ.template.json
  packages/@aws-cdk/aws-cloud9-alpha/test/integ.image-id.js.snapshot/integ.json
  packages/@aws-cdk/aws-cloud9-alpha/test/integ.image-id.js.snapshot/manifest.json
  packages/@aws-cdk/aws-cloud9-alpha/test/integ.image-id.js.snapshot/tree.json
  packages/@aws-cdk/aws-cloud9-alpha/test/integ.image-id.ts
Labels: p2, contribution/core

#25069 chore: rename aws-msk → aws-msk-alpha
  packages/@aws-cdk/aws-msk-alpha/.eslintrc.js
  packages/@aws-cdk/aws-msk-alpha/.gitignore
  packages/@aws-cdk/aws-msk-alpha/.npmignore
  packages/@aws-cdk/aws-msk-alpha/LICENSE
  packages/@aws-cdk/aws-msk-alpha/NOTICE
  packages/@aws-cdk/aws-msk-alpha/README.md
  packages/@aws-cdk/aws-msk-alpha/jest.config.js
  packages/@aws-cdk/aws-msk-alpha/lib/cluster-version.ts
  packages/@aws-cdk/aws-msk-alpha/lib/cluster.ts
  packages/@aws-cdk/aws-msk-alpha/lib/index.ts
  packages/@aws-cdk/aws-msk-alpha/package.json
  packages/@aws-cdk/aws-msk-alpha/rosetta/default.ts-fixture
  packages/@aws-cdk/aws-msk-alpha/test/__snapshots__/cluster.test.js.snap
  packages/@aws-cdk/aws-msk-alpha/test/cluster.test.ts
  packages/@aws-cdk/aws-msk-alpha/test/integ.cluster.js.snapshot/MskLoggingDefaultTestDeployAssertC2F074AF.assets.json
  packages/@aws-cdk/aws-msk-alpha/test/integ.cluster.js.snapshot/MskLoggingDefaultTestDeployAssertC2F074AF.template.json
  packages/@aws-cdk/aws-msk-alpha/test/integ.cluster.js.snapshot/asset.33e2651435a0d472a75c1e033c9832b21321d9e56711926b04c5705e5f63874c/__entrypoint__.js
  packages/@aws-cdk/aws-msk-alpha/test/integ.cluster.js.snapshot/asset.33e2651435a0d472a75c1e033c9832b21321d9e56711926b04c5705e5f63874c/index.js
  packages/@aws-cdk/aws-msk-alpha/test/integ.cluster.js.snapshot/asset.73c20a669c041469f7fc3fc03d574b093b5b97e7c716f76c1e8117e6163e4dc4.bundle/index.js
  packages/@aws-cdk/aws-msk-alpha/test/integ.cluster.js.snapshot/aws-cdk-msk-integ.assets.json
  packages/@aws-cdk/aws-msk-alpha/test/integ.cluster.js.snapshot/aws-cdk-msk-integ.template.json
  packages/@aws-cdk/aws-msk-alpha/test/integ.cluster.js.snapshot/cdk.out
  packages/@aws-cdk/aws-msk-alpha/test/integ.cluster.js.snapshot/integ.json
  packages/@aws-cdk/aws-msk-alpha/test/integ.cluster.js.snapshot/manifest.json
  packages/@aws-cdk/aws-msk-alpha/test/integ.cluster.js.snapshot/tree.json
  packages/@aws-cdk/aws-msk-alpha/test/integ.cluster.ts
  packages/@aws-cdk/aws-msk-alpha/test/integ.cluster.ts.snapshot/MskLoggingDefaultTestDeployAssertC2F074AF.assets.json
  packages/@aws-cdk/aws-msk-alpha/test/integ.cluster.ts.snapshot/MskLoggingDefaultTestDeployAssertC2F074AF.template.json
  packages/@aws-cdk/aws-msk-alpha/test/integ.cluster.ts.snapshot/asset.1f3c2cfb18e102edc713fe4c4b4d87572f4297ee4a5e80a5960adf526ee9ea28.bundle/index.js
  packages/@aws-cdk/aws-msk-alpha/test/integ.cluster.ts.snapshot/asset.33e2651435a0d472a75c1e033c9832b21321d9e56711926b04c5705e5f63874c/__entrypoint__.js
  packages/@aws-cdk/aws-msk-alpha/test/integ.cluster.ts.snapshot/asset.33e2651435a0d472a75c1e033c9832b21321d9e56711926b04c5705e5f63874c/index.js
  packages/@aws-cdk/aws-msk-alpha/test/integ.cluster.ts.snapshot/asset.a268caa53756f51bda8ad5f499be4ed8484a81b314811806fbb66f874837c476/index.js
  packages/@aws-cdk/aws-msk-alpha/test/integ.cluster.ts.snapshot/aws-cdk-msk-integ.assets.json
  packages/@aws-cdk/aws-msk-alpha/test/integ.cluster.ts.snapshot/aws-cdk-msk-integ.template.json
  packages/@aws-cdk/aws-msk-alpha/test/integ.cluster.ts.snapshot/cdk.out
  packages/@aws-cdk/aws-msk-alpha/test/integ.cluster.ts.snapshot/integ.json
  packages/@aws-cdk/aws-msk-alpha/test/integ.cluster.ts.snapshot/manifest.json
  packages/@aws-cdk/aws-msk-alpha/test/integ.cluster.ts.snapshot/tree.json
Labels: p2, contribution/core

#25086 chore: ignore aws-cdk-lib tests in npm package
  packages/aws-cdk-lib/.npmignore
Labels: p2, contribution/core

#25079 chore(s3): documented how the bucket encryption configuration is computed
  packages/aws-cdk-lib/aws-s3/lib/bucket.ts
Labels: p2, contribution/core

#24546 fix(redshift): Column ids were not being default assigned
  packages/@aws-cdk/aws-redshift/lib/table.ts
  packages/@aws-cdk/aws-redshift/test/integ.database-columnid.ts
  packages/@aws-cdk/aws-redshift/test/integ.database.js.snapshot/asset.169a8c0beb97c903ee155ea9653e39b0884c9e3b860ac72ffbe906b3c1f4e338/table.js
  packages/@aws-cdk/aws-redshift/test/integ.database.js.snapshot/asset.1a159599b617b432864ddf9e4e9ec70b884de7656daa51073d4149a3080c5f79/handler-name.js
  packages/@aws-cdk/aws-redshift/test/integ.database.js.snapshot/asset.1a159599b617b432864ddf9e4e9ec70b884de7656daa51073d4149a3080c5f79/index.js
  packages/@aws-cdk/aws-redshift/test/integ.database.js.snapshot/asset.1a159599b617b432864ddf9e4e9ec70b884de7656daa51073d4149a3080c5f79/privileges.js
  packages/@aws-cdk/aws-redshift/test/integ.database.js.snapshot/asset.1a159599b617b432864ddf9e4e9ec70b884de7656daa51073d4149a3080c5f79/redshift-data.js
  packages/@aws-cdk/aws-redshift/test/integ.database.js.snapshot/asset.1a159599b617b432864ddf9e4e9ec70b884de7656daa51073d4149a3080c5f79/table.js
  packages/@aws-cdk/aws-redshift/test/integ.database.js.snapshot/asset.1a159599b617b432864ddf9e4e9ec70b884de7656daa51073d4149a3080c5f79/types.js
  packages/@aws-cdk/aws-redshift/test/integ.database.js.snapshot/asset.1a159599b617b432864ddf9e4e9ec70b884de7656daa51073d4149a3080c5f79/user.js
  packages/@aws-cdk/aws-redshift/test/integ.database.js.snapshot/asset.1a159599b617b432864ddf9e4e9ec70b884de7656daa51073d4149a3080c5f79/util.js
  packages/@aws-cdk/aws-redshift/test/integ.database.js.snapshot/asset.847e15feeb180b356ab9a8094d8b9459ea8ec26fc27957794d583ed9eb3a79d8/handler-name.js
  packages/@aws-cdk/aws-redshift/test/integ.database.js.snapshot/asset.847e15feeb180b356ab9a8094d8b9459ea8ec26fc27957794d583ed9eb3a79d8/index.js
  packages/@aws-cdk/aws-redshift/test/integ.database.js.snapshot/asset.847e15feeb180b356ab9a8094d8b9459ea8ec26fc27957794d583ed9eb3a79d8/privileges.js
  packages/@aws-cdk/aws-redshift/test/integ.database.js.snapshot/asset.847e15feeb180b356ab9a8094d8b9459ea8ec26fc27957794d583ed9eb3a79d8/redshift-data.js
  packages/@aws-cdk/aws-redshift/test/integ.database.js.snapshot/asset.847e15feeb180b356ab9a8094d8b9459ea8ec26fc27957794d583ed9eb3a79d8/table.js
  packages/@aws-cdk/aws-redshift/test/integ.database.js.snapshot/asset.847e15feeb180b356ab9a8094d8b9459ea8ec26fc27957794d583ed9eb3a79d8/types.js
  packages/@aws-cdk/aws-redshift/test/integ.database.js.snapshot/asset.847e15feeb180b356ab9a8094d8b9459ea8ec26fc27957794d583ed9eb3a79d8/user.js
  packages/@aws-cdk/aws-redshift/test/integ.database.js.snapshot/asset.847e15feeb180b356ab9a8094d8b9459ea8ec26fc27957794d583ed9eb3a79d8/util.js
  packages/@aws-cdk/aws-redshift/test/integ.database.js.snapshot/aws-cdk-redshift-cluster-database.assets.json
  packages/@aws-cdk/aws-redshift/test/integ.database.js.snapshot/aws-cdk-redshift-cluster-database.template.json
  packages/@aws-cdk/aws-redshift/test/integ.database.js.snapshot/cdk.out
  packages/@aws-cdk/aws-redshift/test/integ.database.js.snapshot/integ.json
  packages/@aws-cdk/aws-redshift/test/integ.database.js.snapshot/manifest.json
  packages/@aws-cdk/aws-redshift/test/integ.database.js.snapshot/redshiftclusterdatabaseintegDefaultTestDeployAssert4339FB48.assets.json
  packages/@aws-cdk/aws-redshift/test/integ.database.js.snapshot/tree.json
  packages/@aws-cdk/aws-redshift/test/table.test.ts
Labels: bug, p2, effort/medium, valued-contributor

#24786 fix(events-targets): parameter JobName can exceed limit of 128 characters
  packages/@aws-cdk/aws-batch/test/aws-events-targets/batch.test.ts
  packages/@aws-cdk/aws-batch/test/integ.batch-unique-name.js.snapshot/BatchUniqueNameTestDefaultTestDeployAssertA3886AB9.assets.json
  packages/@aws-cdk/aws-batch/test/integ.batch-unique-name.js.snapshot/BatchUniqueNameTestDefaultTestDeployAssertA3886AB9.template.json
  packages/@aws-cdk/aws-batch/test/integ.batch-unique-name.js.snapshot/cdk.out
  packages/@aws-cdk/aws-batch/test/integ.batch-unique-name.js.snapshot/integ.json
  packages/@aws-cdk/aws-batch/test/integ.batch-unique-name.js.snapshot/manifest.json
  packages/@aws-cdk/aws-batch/test/integ.batch-unique-name.js.snapshot/stack.assets.json
  packages/@aws-cdk/aws-batch/test/integ.batch-unique-name.js.snapshot/stack.template.json
  packages/@aws-cdk/aws-batch/test/integ.batch-unique-name.js.snapshot/tree.json
  packages/@aws-cdk/aws-batch/test/integ.batch-unique-name.ts
  packages/aws-cdk-lib/aws-events-targets/lib/batch.ts
Labels: bug, p1, effort/small, repeat-contributor

#24217 chore: build.sh script unnecessarily requires lerna to be globally installed
  build.sh
Labels: p2, beginning-contributor

#24537 chore(cloudformation-diff): Changed to a more abstract type.
  packages/@aws-cdk/cloudformation-diff/lib/format.ts
Labels: p2, beginning-contributor

#25000 chore(rds): upgrade cluster(postgresql) version
  packages/aws-cdk-lib/aws-rds/lib/cluster-engine.ts
Labels: p2, star-contributor

#25063 chore: rename aws-iot → aws-iot-alpha
  packages/@aws-cdk/aws-iot-alpha/.eslintrc.js
  packages/@aws-cdk/aws-iot-alpha/.gitignore
  packages/@aws-cdk/aws-iot-alpha/.npmignore
  packages/@aws-cdk/aws-iot-alpha/LICENSE
  packages/@aws-cdk/aws-iot-alpha/NOTICE
  packages/@aws-cdk/aws-iot-alpha/README.md
  packages/@aws-cdk/aws-iot-alpha/jest.config.js
  packages/@aws-cdk/aws-iot-alpha/lib/action.ts
  packages/@aws-cdk/aws-iot-alpha/lib/index.ts
  packages/@aws-cdk/aws-iot-alpha/lib/iot-sql.ts
  packages/@aws-cdk/aws-iot-alpha/lib/topic-rule.ts
  packages/@aws-cdk/aws-iot-alpha/package.json
  packages/@aws-cdk/aws-iot-alpha/rosetta/default.ts-fixture
  packages/@aws-cdk/aws-iot-alpha/test/integ.topic-rule.js.snapshot/TopicRuleDefaultTestDeployAssert86D4DD8C.assets.json
  packages/@aws-cdk/aws-iot-alpha/test/integ.topic-rule.js.snapshot/TopicRuleDefaultTestDeployAssert86D4DD8C.template.json
  packages/@aws-cdk/aws-iot-alpha/test/integ.topic-rule.js.snapshot/cdk.out
  packages/@aws-cdk/aws-iot-alpha/test/integ.topic-rule.js.snapshot/integ.json
  packages/@aws-cdk/aws-iot-alpha/test/integ.topic-rule.js.snapshot/manifest.json
  packages/@aws-cdk/aws-iot-alpha/test/integ.topic-rule.js.snapshot/topic-rule-test-stack.assets.json
  packages/@aws-cdk/aws-iot-alpha/test/integ.topic-rule.js.snapshot/topic-rule-test-stack.template.json
  packages/@aws-cdk/aws-iot-alpha/test/integ.topic-rule.js.snapshot/tree.json
  packages/@aws-cdk/aws-iot-alpha/test/integ.topic-rule.ts
  packages/@aws-cdk/aws-iot-alpha/test/topic-rule.test.ts
Labels: p2, contribution/core

#25065 chore: rename aws-iotevents → aws-iotevents-alpha
  packages/@aws-cdk/aws-iotevents-alpha/.eslintrc.js
  packages/@aws-cdk/aws-iotevents-alpha/.gitignore
  packages/@aws-cdk/aws-iotevents-alpha/.npmignore
  packages/@aws-cdk/aws-iotevents-alpha/LICENSE
  packages/@aws-cdk/aws-iotevents-alpha/NOTICE
  packages/@aws-cdk/aws-iotevents-alpha/README.md
  packages/@aws-cdk/aws-iotevents-alpha/jest.config.js
  packages/@aws-cdk/aws-iotevents-alpha/lib/action.ts
  packages/@aws-cdk/aws-iotevents-alpha/lib/detector-model.ts
  packages/@aws-cdk/aws-iotevents-alpha/lib/event.ts
  packages/@aws-cdk/aws-iotevents-alpha/lib/expression.ts
  packages/@aws-cdk/aws-iotevents-alpha/lib/index.ts
  packages/@aws-cdk/aws-iotevents-alpha/lib/input.ts
  packages/@aws-cdk/aws-iotevents-alpha/lib/state.ts
  packages/@aws-cdk/aws-iotevents-alpha/package.json
  packages/@aws-cdk/aws-iotevents-alpha/rosetta/default.ts-fixture
  packages/@aws-cdk/aws-iotevents-alpha/test/detector-model.test.ts
  packages/@aws-cdk/aws-iotevents-alpha/test/input.test.ts
  packages/@aws-cdk/aws-iotevents-alpha/test/integ.detector-model.js.snapshot/cdk.out
  packages/@aws-cdk/aws-iotevents-alpha/test/integ.detector-model.js.snapshot/detector-model-test-stack.assets.json
  packages/@aws-cdk/aws-iotevents-alpha/test/integ.detector-model.js.snapshot/detector-model-test-stack.template.json
  packages/@aws-cdk/aws-iotevents-alpha/test/integ.detector-model.js.snapshot/integ.json
  packages/@aws-cdk/aws-iotevents-alpha/test/integ.detector-model.js.snapshot/manifest.json
  packages/@aws-cdk/aws-iotevents-alpha/test/integ.detector-model.js.snapshot/tree.json
  packages/@aws-cdk/aws-iotevents-alpha/test/integ.detector-model.ts
Labels: p2, contribution/core

#25074 chore: rename aws-location → aws-location-alpha
  packages/@aws-cdk/aws-location-alpha/.eslintrc.js
  packages/@aws-cdk/aws-location-alpha/.gitignore
  packages/@aws-cdk/aws-location-alpha/.npmignore
  packages/@aws-cdk/aws-location-alpha/LICENSE
  packages/@aws-cdk/aws-location-alpha/NOTICE
  packages/@aws-cdk/aws-location-alpha/README.md
  packages/@aws-cdk/aws-location-alpha/jest.config.js
  packages/@aws-cdk/aws-location-alpha/lib/index.ts
  packages/@aws-cdk/aws-location-alpha/lib/place-index.ts
  packages/@aws-cdk/aws-location-alpha/package.json
  packages/@aws-cdk/aws-location-alpha/rosetta/default.ts-fixture
  packages/@aws-cdk/aws-location-alpha/test/integ.place-index.js.snapshot/PlaceIndexTestDefaultTestDeployAssert3F96C508.assets.json
  packages/@aws-cdk/aws-location-alpha/test/integ.place-index.js.snapshot/PlaceIndexTestDefaultTestDeployAssert3F96C508.template.json
  packages/@aws-cdk/aws-location-alpha/test/integ.place-index.js.snapshot/cdk-integ-location-place-index.assets.json
  packages/@aws-cdk/aws-location-alpha/test/integ.place-index.js.snapshot/cdk-integ-location-place-index.template.json
  packages/@aws-cdk/aws-location-alpha/test/integ.place-index.js.snapshot/cdk.out
  packages/@aws-cdk/aws-location-alpha/test/integ.place-index.js.snapshot/integ.json
  packages/@aws-cdk/aws-location-alpha/test/integ.place-index.js.snapshot/manifest.json
  packages/@aws-cdk/aws-location-alpha/test/integ.place-index.js.snapshot/tree.json
  packages/@aws-cdk/aws-location-alpha/test/integ.place-index.ts
  packages/@aws-cdk/aws-location-alpha/test/place-index.test.ts
Labels: p2, contribution/core

#25076 chore: rename aws-iotevents-actions → aws-iotevents-actions-alpha
  packages/@aws-cdk/aws-iotevents-actions-alpha/.eslintrc.js
  packages/@aws-cdk/aws-iotevents-actions-alpha/.gitignore
  packages/@aws-cdk/aws-iotevents-actions-alpha/.npmignore
  packages/@aws-cdk/aws-iotevents-actions-alpha/LICENSE
  packages/@aws-cdk/aws-iotevents-actions-alpha/NOTICE
  packages/@aws-cdk/aws-iotevents-actions-alpha/README.md
  packages/@aws-cdk/aws-iotevents-actions-alpha/jest.config.js
  packages/@aws-cdk/aws-iotevents-actions-alpha/lib/clear-timer-action.ts
  packages/@aws-cdk/aws-iotevents-actions-alpha/lib/index.ts
  packages/@aws-cdk/aws-iotevents-actions-alpha/lib/lambda-invoke-action.ts
  packages/@aws-cdk/aws-iotevents-actions-alpha/lib/reset-timer-action.ts
  packages/@aws-cdk/aws-iotevents-actions-alpha/lib/set-timer-action.ts
  packages/@aws-cdk/aws-iotevents-actions-alpha/lib/set-variable-action.ts
  packages/@aws-cdk/aws-iotevents-actions-alpha/lib/timer-duration.ts
  packages/@aws-cdk/aws-iotevents-actions-alpha/package.json
  packages/@aws-cdk/aws-iotevents-actions-alpha/test/iot/clear-timer-action.test.ts
  packages/@aws-cdk/aws-iotevents-actions-alpha/test/iot/integ.set-variable-action.js.snapshot/cdk.out
  packages/@aws-cdk/aws-iotevents-actions-alpha/test/iot/integ.set-variable-action.js.snapshot/integ.json
  packages/@aws-cdk/aws-iotevents-actions-alpha/test/iot/integ.set-variable-action.js.snapshot/iotevents-set-variable-action-test-stack.assets.json
  packages/@aws-cdk/aws-iotevents-actions-alpha/test/iot/integ.set-variable-action.js.snapshot/iotevents-set-variable-action-test-stack.template.json
  packages/@aws-cdk/aws-iotevents-actions-alpha/test/iot/integ.set-variable-action.js.snapshot/manifest.json
  packages/@aws-cdk/aws-iotevents-actions-alpha/test/iot/integ.set-variable-action.js.snapshot/tree.json
  packages/@aws-cdk/aws-iotevents-actions-alpha/test/iot/integ.set-variable-action.ts
  packages/@aws-cdk/aws-iotevents-actions-alpha/test/iot/integ.timer-actions.js.snapshot/TimerActionsDefaultTestDeployAssert89D9000B.assets.json
  packages/@aws-cdk/aws-iotevents-actions-alpha/test/iot/integ.timer-actions.js.snapshot/TimerActionsDefaultTestDeployAssert89D9000B.template.json
  packages/@aws-cdk/aws-iotevents-actions-alpha/test/iot/integ.timer-actions.js.snapshot/cdk.out
  packages/@aws-cdk/aws-iotevents-actions-alpha/test/iot/integ.timer-actions.js.snapshot/integ.json
  packages/@aws-cdk/aws-iotevents-actions-alpha/test/iot/integ.timer-actions.js.snapshot/iotevents-timer-actions-test-stack.assets.json
  packages/@aws-cdk/aws-iotevents-actions-alpha/test/iot/integ.timer-actions.js.snapshot/iotevents-timer-actions-test-stack.template.json
  packages/@aws-cdk/aws-iotevents-actions-alpha/test/iot/integ.timer-actions.js.snapshot/manifest.json
  packages/@aws-cdk/aws-iotevents-actions-alpha/test/iot/integ.timer-actions.js.snapshot/tree.json
  packages/@aws-cdk/aws-iotevents-actions-alpha/test/iot/integ.timer-actions.ts
  packages/@aws-cdk/aws-iotevents-actions-alpha/test/iot/reset-timer-action.test.ts
  packages/@aws-cdk/aws-iotevents-actions-alpha/test/iot/set-timer-action.test.ts
  packages/@aws-cdk/aws-iotevents-actions-alpha/test/iot/set-variable-action.test.ts
  packages/@aws-cdk/aws-iotevents-actions-alpha/test/lambda/integ.lambda-invoke-action.js.snapshot/cdk.out
  packages/@aws-cdk/aws-iotevents-actions-alpha/test/lambda/integ.lambda-invoke-action.js.snapshot/integ.json
  packages/@aws-cdk/aws-iotevents-actions-alpha/test/lambda/integ.lambda-invoke-action.js.snapshot/lambda-invoke-action-test-stack.assets.json
  packages/@aws-cdk/aws-iotevents-actions-alpha/test/lambda/integ.lambda-invoke-action.js.snapshot/lambda-invoke-action-test-stack.template.json
  packages/@aws-cdk/aws-iotevents-actions-alpha/test/lambda/integ.lambda-invoke-action.js.snapshot/manifest.json
  packages/@aws-cdk/aws-iotevents-actions-alpha/test/lambda/integ.lambda-invoke-action.js.snapshot/tree.json
  packages/@aws-cdk/aws-iotevents-actions-alpha/test/lambda/integ.lambda-invoke-action.ts
  packages/@aws-cdk/aws-iotevents-actions-alpha/test/lambda/lambda-invoke-action.test.ts
Labels: p2, contribution/core

#25068 chore: rename aws-kinesisanalytics-flink → aws-kinesisanalytics-flink-alpha
  packages/@aws-cdk/aws-kinesisanalytics-flink-alpha/.eslintrc.js
  packages/@aws-cdk/aws-kinesisanalytics-flink-alpha/.gitignore
  packages/@aws-cdk/aws-kinesisanalytics-flink-alpha/.npmignore
  packages/@aws-cdk/aws-kinesisanalytics-flink-alpha/LICENSE
  packages/@aws-cdk/aws-kinesisanalytics-flink-alpha/NOTICE
  packages/@aws-cdk/aws-kinesisanalytics-flink-alpha/README.md
  packages/@aws-cdk/aws-kinesisanalytics-flink-alpha/jest.config.js
  packages/@aws-cdk/aws-kinesisanalytics-flink-alpha/lib/application-code.ts
  packages/@aws-cdk/aws-kinesisanalytics-flink-alpha/lib/application.ts
  packages/@aws-cdk/aws-kinesisanalytics-flink-alpha/lib/index.ts
  packages/@aws-cdk/aws-kinesisanalytics-flink-alpha/lib/private/environment-properties.ts
  packages/@aws-cdk/aws-kinesisanalytics-flink-alpha/lib/private/flink-application-configuration.ts
  packages/@aws-cdk/aws-kinesisanalytics-flink-alpha/lib/private/validation.ts
  packages/@aws-cdk/aws-kinesisanalytics-flink-alpha/lib/types.ts
  packages/@aws-cdk/aws-kinesisanalytics-flink-alpha/package.json
  packages/@aws-cdk/aws-kinesisanalytics-flink-alpha/rosetta/default.ts-fixture
  packages/@aws-cdk/aws-kinesisanalytics-flink-alpha/test/application.test.ts
  packages/@aws-cdk/aws-kinesisanalytics-flink-alpha/test/code-asset/WordCount.jar
  packages/@aws-cdk/aws-kinesisanalytics-flink-alpha/test/integ.application-code-from-bucket.lit.js.snapshot/FlinkAppCodeFromBucketTest.assets.json
  packages/@aws-cdk/aws-kinesisanalytics-flink-alpha/test/integ.application-code-from-bucket.lit.js.snapshot/FlinkAppCodeFromBucketTest.template.json
  packages/@aws-cdk/aws-kinesisanalytics-flink-alpha/test/integ.application-code-from-bucket.lit.js.snapshot/asset.8be9e0b5f53d41e9a3b1d51c9572c65f24f8170a7188d0ed57fb7d571de4d577/WordCount.jar
  packages/@aws-cdk/aws-kinesisanalytics-flink-alpha/test/integ.application-code-from-bucket.lit.js.snapshot/cdk.out
  packages/@aws-cdk/aws-kinesisanalytics-flink-alpha/test/integ.application-code-from-bucket.lit.js.snapshot/integ.json
  packages/@aws-cdk/aws-kinesisanalytics-flink-alpha/test/integ.application-code-from-bucket.lit.js.snapshot/manifest.json
  packages/@aws-cdk/aws-kinesisanalytics-flink-alpha/test/integ.application-code-from-bucket.lit.js.snapshot/tree.json
  packages/@aws-cdk/aws-kinesisanalytics-flink-alpha/test/integ.application-code-from-bucket.lit.ts
  packages/@aws-cdk/aws-kinesisanalytics-flink-alpha/test/integ.application.lit.js.snapshot/FlinkAppTest.assets.json
  packages/@aws-cdk/aws-kinesisanalytics-flink-alpha/test/integ.application.lit.js.snapshot/FlinkAppTest.template.json
  packages/@aws-cdk/aws-kinesisanalytics-flink-alpha/test/integ.application.lit.js.snapshot/asset.8be9e0b5f53d41e9a3b1d51c9572c65f24f8170a7188d0ed57fb7d571de4d577/WordCount.jar
  packages/@aws-cdk/aws-kinesisanalytics-flink-alpha/test/integ.application.lit.js.snapshot/cdk.out
  packages/@aws-cdk/aws-kinesisanalytics-flink-alpha/test/integ.application.lit.js.snapshot/integ.json
  packages/@aws-cdk/aws-kinesisanalytics-flink-alpha/test/integ.application.lit.js.snapshot/manifest.json
  packages/@aws-cdk/aws-kinesisanalytics-flink-alpha/test/integ.application.lit.js.snapshot/tree.json
  packages/@aws-cdk/aws-kinesisanalytics-flink-alpha/test/integ.application.lit.ts
  packages/@aws-cdk/aws-kinesisanalytics-flink-alpha/test/integ.vpc-application.js.snapshot/FlinkAppTest.assets.json
  packages/@aws-cdk/aws-kinesisanalytics-flink-alpha/test/integ.vpc-application.js.snapshot/FlinkAppTest.template.json
  packages/@aws-cdk/aws-kinesisanalytics-flink-alpha/test/integ.vpc-application.js.snapshot/VpcTestDefaultTestDeployAssert06A9965C.assets.json
  packages/@aws-cdk/aws-kinesisanalytics-flink-alpha/test/integ.vpc-application.js.snapshot/VpcTestDefaultTestDeployAssert06A9965C.template.json
  packages/@aws-cdk/aws-kinesisanalytics-flink-alpha/test/integ.vpc-application.js.snapshot/asset.8be9e0b5f53d41e9a3b1d51c9572c65f24f8170a7188d0ed57fb7d571de4d577/WordCount.jar
  packages/@aws-cdk/aws-kinesisanalytics-flink-alpha/test/integ.vpc-application.js.snapshot/cdk.out
  packages/@aws-cdk/aws-kinesisanalytics-flink-alpha/test/integ.vpc-application.js.snapshot/integ.json
  packages/@aws-cdk/aws-kinesisanalytics-flink-alpha/test/integ.vpc-application.js.snapshot/manifest.json
  packages/@aws-cdk/aws-kinesisanalytics-flink-alpha/test/integ.vpc-application.js.snapshot/tree.json
  packages/@aws-cdk/aws-kinesisanalytics-flink-alpha/test/integ.vpc-application.ts
Labels: p2, contribution/core

#25053 chore: rename aws-lambda-go → aws-lambda-go-alpha
  packages/@aws-cdk/aws-lambda-go-alpha/.eslintrc.js
  packages/@aws-cdk/aws-lambda-go-alpha/.gitignore
  packages/@aws-cdk/aws-lambda-go-alpha/.npmignore
  packages/@aws-cdk/aws-lambda-go-alpha/LICENSE
  packages/@aws-cdk/aws-lambda-go-alpha/NOTICE
  packages/@aws-cdk/aws-lambda-go-alpha/README.md
  packages/@aws-cdk/aws-lambda-go-alpha/jest.config.js
  packages/@aws-cdk/aws-lambda-go-alpha/lib/Dockerfile
  packages/@aws-cdk/aws-lambda-go-alpha/lib/bundling.ts
  packages/@aws-cdk/aws-lambda-go-alpha/lib/function.ts
  packages/@aws-cdk/aws-lambda-go-alpha/lib/index.ts
  packages/@aws-cdk/aws-lambda-go-alpha/lib/types.ts
  packages/@aws-cdk/aws-lambda-go-alpha/lib/util.ts
  packages/@aws-cdk/aws-lambda-go-alpha/package.json
  packages/@aws-cdk/aws-lambda-go-alpha/rosetta/default.ts-fixture
  packages/@aws-cdk/aws-lambda-go-alpha/test/bundling.test.ts
  packages/@aws-cdk/aws-lambda-go-alpha/test/docker.test.ts
  packages/@aws-cdk/aws-lambda-go-alpha/test/function.test.ts
  packages/@aws-cdk/aws-lambda-go-alpha/test/integ.function.js.snapshot/asset.86891c59c6b1eb9b0ec971a6dfc2007af1a03467fd9157a78d28c154968b2980/bootstrap
  packages/@aws-cdk/aws-lambda-go-alpha/test/integ.function.js.snapshot/cdk-integ-lambda-golang.assets.json
  packages/@aws-cdk/aws-lambda-go-alpha/test/integ.function.js.snapshot/cdk-integ-lambda-golang.template.json
  packages/@aws-cdk/aws-lambda-go-alpha/test/integ.function.js.snapshot/cdk.out
  packages/@aws-cdk/aws-lambda-go-alpha/test/integ.function.js.snapshot/integ.json
  packages/@aws-cdk/aws-lambda-go-alpha/test/integ.function.js.snapshot/manifest.json
  packages/@aws-cdk/aws-lambda-go-alpha/test/integ.function.js.snapshot/tree.json
  packages/@aws-cdk/aws-lambda-go-alpha/test/integ.function.ts
  packages/@aws-cdk/aws-lambda-go-alpha/test/lambda-handler-vendor/cmd/api/main.go
  packages/@aws-cdk/aws-lambda-go-alpha/test/lambda-handler-vendor/go.mod
  packages/@aws-cdk/aws-lambda-go-alpha/test/util.test.ts
Labels: p2, contribution/core

#25058 chore: rename aws-kinesisfirehose-destinations → aws-kinesisfirehose-destinations-alpha
  packages/@aws-cdk/aws-kinesisfirehose-destinations-alpha/.eslintrc.js
  packages/@aws-cdk/aws-kinesisfirehose-destinations-alpha/.gitignore
  packages/@aws-cdk/aws-kinesisfirehose-destinations-alpha/.npmignore
  packages/@aws-cdk/aws-kinesisfirehose-destinations-alpha/LICENSE
  packages/@aws-cdk/aws-kinesisfirehose-destinations-alpha/NOTICE
  packages/@aws-cdk/aws-kinesisfirehose-destinations-alpha/README.md
  packages/@aws-cdk/aws-kinesisfirehose-destinations-alpha/jest.config.js
  packages/@aws-cdk/aws-kinesisfirehose-destinations-alpha/lib/common.ts
  packages/@aws-cdk/aws-kinesisfirehose-destinations-alpha/lib/index.ts
  packages/@aws-cdk/aws-kinesisfirehose-destinations-alpha/lib/private/helpers.ts
  packages/@aws-cdk/aws-kinesisfirehose-destinations-alpha/lib/s3-bucket.ts
  packages/@aws-cdk/aws-kinesisfirehose-destinations-alpha/package.json
  packages/@aws-cdk/aws-kinesisfirehose-destinations-alpha/rosetta/default.ts-fixture
  packages/@aws-cdk/aws-kinesisfirehose-destinations-alpha/test/integ.s3-bucket.lit.js.snapshot/asset.33e2651435a0d472a75c1e033c9832b21321d9e56711926b04c5705e5f63874c/__entrypoint__.js
  packages/@aws-cdk/aws-kinesisfirehose-destinations-alpha/test/integ.s3-bucket.lit.js.snapshot/asset.33e2651435a0d472a75c1e033c9832b21321d9e56711926b04c5705e5f63874c/index.js
  packages/@aws-cdk/aws-kinesisfirehose-destinations-alpha/test/integ.s3-bucket.lit.js.snapshot/asset.fe1ae9f614deb9ad8681131e8d3ebb6f23ae0c8f1f589d433c09881ad327487f/index.js
  packages/@aws-cdk/aws-kinesisfirehose-destinations-alpha/test/integ.s3-bucket.lit.js.snapshot/aws-cdk-firehose-delivery-stream-s3-all-properties.assets.json
  packages/@aws-cdk/aws-kinesisfirehose-destinations-alpha/test/integ.s3-bucket.lit.js.snapshot/aws-cdk-firehose-delivery-stream-s3-all-properties.template.json
  packages/@aws-cdk/aws-kinesisfirehose-destinations-alpha/test/integ.s3-bucket.lit.js.snapshot/cdk.out
  packages/@aws-cdk/aws-kinesisfirehose-destinations-alpha/test/integ.s3-bucket.lit.js.snapshot/integ.json
  packages/@aws-cdk/aws-kinesisfirehose-destinations-alpha/test/integ.s3-bucket.lit.js.snapshot/manifest.json
  packages/@aws-cdk/aws-kinesisfirehose-destinations-alpha/test/integ.s3-bucket.lit.js.snapshot/tree.json
  packages/@aws-cdk/aws-kinesisfirehose-destinations-alpha/test/integ.s3-bucket.lit.ts
  packages/@aws-cdk/aws-kinesisfirehose-destinations-alpha/test/lambda-data-processor.js
  packages/@aws-cdk/aws-kinesisfirehose-destinations-alpha/test/s3-bucket.test.ts
  packages/@aws-cdk/aws-kinesisfirehose/README.md
Labels: p2, contribution/core

#25054 chore: rename aws-kinesisfirehose → aws-kinesisfirehose-alpha
  packages/@aws-cdk/aws-kinesisfirehose-alpha/.eslintrc.js
  packages/@aws-cdk/aws-kinesisfirehose-alpha/.gitignore
  packages/@aws-cdk/aws-kinesisfirehose-alpha/.npmignore
  packages/@aws-cdk/aws-kinesisfirehose-alpha/LICENSE
  packages/@aws-cdk/aws-kinesisfirehose-alpha/NOTICE
  packages/@aws-cdk/aws-kinesisfirehose-alpha/README.md
  packages/@aws-cdk/aws-kinesisfirehose-alpha/jest.config.js
  packages/@aws-cdk/aws-kinesisfirehose-alpha/lib/delivery-stream.ts
  packages/@aws-cdk/aws-kinesisfirehose-alpha/lib/destination.ts
  packages/@aws-cdk/aws-kinesisfirehose-alpha/lib/index.ts
  packages/@aws-cdk/aws-kinesisfirehose-alpha/lib/lambda-function-processor.ts
  packages/@aws-cdk/aws-kinesisfirehose-alpha/lib/processor.ts
  packages/@aws-cdk/aws-kinesisfirehose-alpha/package.json
  packages/@aws-cdk/aws-kinesisfirehose-alpha/rosetta/default.ts-fixture
  packages/@aws-cdk/aws-kinesisfirehose-alpha/test/delivery-stream.test.ts
  packages/@aws-cdk/aws-kinesisfirehose-alpha/test/integ.delivery-stream.js.snapshot/aws-cdk-firehose-delivery-stream.assets.json
  packages/@aws-cdk/aws-kinesisfirehose-alpha/test/integ.delivery-stream.js.snapshot/aws-cdk-firehose-delivery-stream.template.json
  packages/@aws-cdk/aws-kinesisfirehose-alpha/test/integ.delivery-stream.js.snapshot/cdk.out
  packages/@aws-cdk/aws-kinesisfirehose-alpha/test/integ.delivery-stream.js.snapshot/integ.json
  packages/@aws-cdk/aws-kinesisfirehose-alpha/test/integ.delivery-stream.js.snapshot/manifest.json
  packages/@aws-cdk/aws-kinesisfirehose-alpha/test/integ.delivery-stream.js.snapshot/tree.json
  packages/@aws-cdk/aws-kinesisfirehose-alpha/test/integ.delivery-stream.source-stream.js.snapshot/aws-cdk-firehose-delivery-stream-source-stream.assets.json
  packages/@aws-cdk/aws-kinesisfirehose-alpha/test/integ.delivery-stream.source-stream.js.snapshot/aws-cdk-firehose-delivery-stream-source-stream.template.json
  packages/@aws-cdk/aws-kinesisfirehose-alpha/test/integ.delivery-stream.source-stream.js.snapshot/cdk.out
  packages/@aws-cdk/aws-kinesisfirehose-alpha/test/integ.delivery-stream.source-stream.js.snapshot/integ.json
  packages/@aws-cdk/aws-kinesisfirehose-alpha/test/integ.delivery-stream.source-stream.js.snapshot/manifest.json
  packages/@aws-cdk/aws-kinesisfirehose-alpha/test/integ.delivery-stream.source-stream.js.snapshot/tree.json
  packages/@aws-cdk/aws-kinesisfirehose-alpha/test/integ.delivery-stream.source-stream.ts
  packages/@aws-cdk/aws-kinesisfirehose-alpha/test/integ.delivery-stream.ts
  tools/@aws-cdk/eslint-plugin/test/rules/fixtures/invalid-cfn-imports/cfn-constructor.error.txt
  tools/@aws-cdk/eslint-plugin/test/rules/fixtures/invalid-cfn-imports/cfn-constructor.ts
  tools/@aws-cdk/eslint-plugin/test/rules/fixtures/invalid-cfn-imports/reference-cfn-construct-on-barrel-import.error.txt
  tools/@aws-cdk/eslint-plugin/test/rules/fixtures/invalid-cfn-imports/reference-cfn-construct-on-barrel-import.ts
Labels: p2, contribution/core

#25083 feat(ec2): add new latest amazon linux machine images
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.machine-image.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.machine-image.js.snapshot/integ-ec2-machine-image-test.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.machine-image.js.snapshot/integ-ec2-machine-image-test.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.machine-image.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.machine-image.js.snapshot/integtestDefaultTestDeployAssert24D5C536.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.machine-image.js.snapshot/integtestDefaultTestDeployAssert24D5C536.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.machine-image.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.machine-image.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.machine-image.ts
  packages/@aws-cdk/aws-batch-alpha/test/managed-compute-environment.test.ts
  packages/aws-cdk-lib/aws-ec2/README.md
  packages/aws-cdk-lib/aws-ec2/lib/index.ts
  packages/aws-cdk-lib/aws-ec2/lib/machine-image/amazon-linux-2022.ts
  packages/aws-cdk-lib/aws-ec2/lib/machine-image/amazon-linux-2023.ts
  packages/aws-cdk-lib/aws-ec2/lib/machine-image/amazon-linux2.ts
  packages/aws-cdk-lib/aws-ec2/lib/machine-image/common.ts
  packages/aws-cdk-lib/aws-ec2/lib/machine-image/index.ts
  packages/aws-cdk-lib/aws-ec2/lib/machine-image/machine-image.ts
  packages/aws-cdk-lib/aws-ec2/lib/machine-image/utils.ts
  packages/aws-cdk-lib/aws-ec2/test/machine-image.test.ts
Labels: bug, p1, effort/small, contribution/core

#25093 fix(batch): `jobQueueName` returns ARN instead of name
  packages/@aws-cdk/aws-batch-alpha/README.md
  packages/@aws-cdk/aws-batch-alpha/lib/ecs-container-definition.ts
  packages/@aws-cdk/aws-batch-alpha/lib/job-queue.ts
  packages/@aws-cdk/aws-batch-alpha/test/job-queue.test.ts
Labels: bug, p2, effort/small, contribution/core, pr-linter/exempt-integ-test

#24896 chore: upgrade lerna and use nx
  CONTRIBUTING.md
  build.sh
  buildspec-pr.yaml
  buildspec.yaml
  lerna.json
  nx.json
  package.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.nat-instances.lit.js.snapshot/aws-cdk-vpc-nat-instances.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.nat-instances.lit.js.snapshot/aws-cdk-vpc-nat-instances.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.nat-instances.lit.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.nat-instances.lit.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.nat-instances.lit.js.snapshot/integtestDefaultTestDeployAssert24D5C536.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.nat-instances.lit.js.snapshot/integtestDefaultTestDeployAssert24D5C536.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.nat-instances.lit.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.nat-instances.lit.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.nat-instances.lit.ts
  packages/@aws-cdk/cli-lib-alpha/THIRD_PARTY_LICENSES
  packages/aws-cdk/test/api/stack-activity-monitor.test.ts
  patches/@lerna+package-graph+4.0.0.patch
  yarn.lock
Labels: p2, contribution/core

#25123 chore(batch): fix typos in the README
  packages/@aws-cdk/aws-batch-alpha/README.md
Labels: p2, contribution/core

#25131 chore: switch cli-integ-testing package to stable
  packages/@aws-cdk-testing/cli-integ/README.md
  packages/@aws-cdk-testing/cli-integ/package.json
Labels: p2, contribution/core

#25117 chore(merge-back): 2.74.0
  CHANGELOG.v2.alpha.md
  CHANGELOG.v2.md
  version.v2.json
Labels: p2, pr/no-squash, auto-approve

#25136 feat(codebuild): adds support for standard (7.0) image
  packages/@aws-cdk-testing/framework-integ/test/aws-codebuild/test/integ.project-standard-image.js.snapshot/Standard1.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-codebuild/test/integ.project-standard-image.js.snapshot/Standard1.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-codebuild/test/integ.project-standard-image.js.snapshot/Standard2.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-codebuild/test/integ.project-standard-image.js.snapshot/Standard2.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-codebuild/test/integ.project-standard-image.js.snapshot/Standard3.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-codebuild/test/integ.project-standard-image.js.snapshot/Standard3.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-codebuild/test/integ.project-standard-image.js.snapshot/Standard4.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-codebuild/test/integ.project-standard-image.js.snapshot/Standard4.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-codebuild/test/integ.project-standard-image.js.snapshot/Standard5.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-codebuild/test/integ.project-standard-image.js.snapshot/Standard5.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-codebuild/test/integ.project-standard-image.js.snapshot/Standard6.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-codebuild/test/integ.project-standard-image.js.snapshot/Standard6.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-codebuild/test/integ.project-standard-image.js.snapshot/Standard7.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-codebuild/test/integ.project-standard-image.js.snapshot/Standard7.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-codebuild/test/integ.project-standard-image.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-codebuild/test/integ.project-standard-image.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-codebuild/test/integ.project-standard-image.js.snapshot/integprojectstandardimagesDefaultTestDeployAssertFEF871A7.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-codebuild/test/integ.project-standard-image.js.snapshot/integprojectstandardimagesDefaultTestDeployAssertFEF871A7.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-codebuild/test/integ.project-standard-image.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-codebuild/test/integ.project-standard-image.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-codebuild/test/integ.project-standard-image.ts
  packages/aws-cdk-lib/aws-codebuild/README.md
  packages/aws-cdk-lib/aws-codebuild/lib/project.ts
  packages/aws-cdk-lib/aws-codebuild/test/project.test.ts
Labels: p2, feature-request, effort/small, star-contributor

#25001 chore(apprunner): AWS App Runner adds 7 new compute configurations
  packages/@aws-cdk/aws-apprunner-alpha/lib/service.ts
Labels: p2, star-contributor

#25152 chore: fix yarn upgrade workflow
  .github/workflows/yarn-upgrade.yml
Labels: p2, contribution/core

#25154 chore: fixing yarn-upgrade workflow
  .github/workflows/yarn-upgrade.yml
Labels: p2, contribution/core

#25162 chore(release): 2.75.0
  CHANGELOG.v2.alpha.md
  CHANGELOG.v2.md
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda/test/integ.runtime.inlinecode.js.snapshot/aws-cdk-lambda-runtime-inlinecode.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda/test/integ.runtime.inlinecode.js.snapshot/aws-cdk-lambda-runtime-inlinecode.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda/test/integ.runtime.inlinecode.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda/test/integ.runtime.inlinecode.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda/test/integ.runtime.inlinecode.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda/test/integ.runtime.inlinecode.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda/test/integ.runtime.inlinecode.ts
  packages/aws-cdk-lib/aws-lambda/lib/runtime.ts
  version.v2.json
Labels: p2, contribution/core, pr/no-squash

#25163 chore(core): Revert #24443 add stage prefix to stack name shortening process
  packages/aws-cdk-lib/core/lib/private/unique-resource-name.ts
  packages/aws-cdk-lib/core/lib/stack.ts
  packages/aws-cdk-lib/core/test/stage.test.ts
Labels: p0, contribution/core

#25168 chore(merge-back): 2.75.0
  CHANGELOG.v2.alpha.md
  CHANGELOG.v2.md
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda/test/integ.runtime.inlinecode.js.snapshot/aws-cdk-lambda-runtime-inlinecode.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda/test/integ.runtime.inlinecode.js.snapshot/aws-cdk-lambda-runtime-inlinecode.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda/test/integ.runtime.inlinecode.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda/test/integ.runtime.inlinecode.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda/test/integ.runtime.inlinecode.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda/test/integ.runtime.inlinecode.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda/test/integ.runtime.inlinecode.ts
  packages/aws-cdk-lib/aws-lambda/lib/runtime.ts
  version.v2.json
Labels: p2, pr/no-squash, auto-approve

#25042 feat(cli-lib): add missing deploy options
  packages/@aws-cdk/cli-lib-alpha/lib/cli.ts
  packages/@aws-cdk/cli-lib-alpha/lib/commands/deploy.ts
  packages/@aws-cdk/cli-lib-alpha/test/commands.test.ts
Labels: p2, effort/small, pr-linter/exempt-readme, pr-linter/exempt-integ-test, repeat-contributor

#25084 feat(core): add rule IDs to the analytics string
  packages/aws-cdk-lib/core/README.md
  packages/aws-cdk-lib/core/lib/private/runtime-info.ts
  packages/aws-cdk-lib/core/lib/validation/validation.ts
  packages/aws-cdk-lib/core/test/runtime-info.test.ts
  packages/aws-cdk-lib/core/test/validation/validation.test.ts
Labels: p2, contribution/core, pr-linter/exempt-integ-test

#25144 chore: fix formatting and remove useless new lines and spaces from README
  README.md
Labels: p2, beginning-contributor

#25116 feat(kms): add required aliasname prefix to aliasnames with tokens
  packages/@aws-cdk-testing/framework-integ/test/aws-kms/test/integ.key-alias.js.snapshot/TestStack.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-kms/test/integ.key-alias.js.snapshot/TestStack.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-kms/test/integ.key-alias.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-kms/test/integ.key-alias.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-kms/test/integ.key-alias.js.snapshot/kmskeyaliastokenizedDefaultTestDeployAssertB7F64730.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-kms/test/integ.key-alias.js.snapshot/kmskeyaliastokenizedDefaultTestDeployAssertB7F64730.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-kms/test/integ.key-alias.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-kms/test/integ.key-alias.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-kms/test/integ.key-alias.ts
  packages/aws-cdk-lib/aws-kms/lib/alias.ts
  packages/aws-cdk-lib/aws-kms/test/alias.test.ts
Labels: p2, feature-request, effort/small, pr-linter/exempt-readme, star-contributor, pr-linter/exemption-requested

#25102 feat(rds): Support SQL Server for RDS proxy
  packages/@aws-cdk-testing/framework-integ/test/aws-rds/test/integ.proxy-sql-server.js.snapshot/aws-cdk-rds-proxy-sql-server.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-rds/test/integ.proxy-sql-server.js.snapshot/aws-cdk-rds-proxy-sql-server.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-rds/test/integ.proxy-sql-server.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-rds/test/integ.proxy-sql-server.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-rds/test/integ.proxy-sql-server.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-rds/test/integ.proxy-sql-server.js.snapshot/proxysqlserverintegtestDefaultTestDeployAssert14B31776.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-rds/test/integ.proxy-sql-server.js.snapshot/proxysqlserverintegtestDefaultTestDeployAssert14B31776.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-rds/test/integ.proxy-sql-server.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-rds/test/integ.proxy-sql-server.ts
  packages/aws-cdk-lib/aws-rds/lib/instance-engine.ts
  packages/aws-cdk-lib/aws-rds/test/instance-engine.test.ts
Labels: p2, feature-request, effort/small, pr-linter/exempt-readme, star-contributor, pr-linter/exemption-requested

#25010 fix(core): Duration.parse() doesn't parse milliseconds
  packages/aws-cdk-lib/core/lib/duration.ts
  packages/aws-cdk-lib/core/test/duration.test.ts
Labels: bug, p2, effort/small, pr-linter/exempt-integ-test, valued-contributor, pr-linter/exemption-requested, pr/reviewer-clarification-requested

#25169 docs(rds): improve the doc for deletionProtection
  packages/aws-cdk-lib/aws-rds/lib/cluster.ts
Labels: bug, p2, contribution/core

#25177 chore(release): 2.75.1
  CHANGELOG.v2.alpha.md
  CHANGELOG.v2.md
  packages/aws-cdk-lib/core/lib/private/unique-resource-name.ts
  packages/aws-cdk-lib/core/lib/stack.ts
  packages/aws-cdk-lib/core/test/stage.test.ts
  version.v2.json
Labels: p2, contribution/core, pr/no-squash

#23838 feat(events-targets): Add tagging for ECS tasks triggered by an event
  packages/@aws-cdk-testing/framework-integ/test/aws-apigateway/test/integ.api-definition.asset.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-events-targets/test/ecs/integ.event-ec2-task.js.snapshot/EcsTestDefaultTestDeployAssert8B2741C4.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-events-targets/test/ecs/integ.event-ec2-task.js.snapshot/aws-ecs-integ-ecs.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-events-targets/test/ecs/integ.event-ec2-task.js.snapshot/aws-ecs-integ-ecs.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-events-targets/test/ecs/integ.event-ec2-task.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-events-targets/test/ecs/integ.event-ec2-task.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-events-targets/test/ecs/integ.event-ec2-task.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-events-targets/test/ecs/integ.event-ec2-task.ts
  packages/@aws-cdk-testing/framework-integ/test/aws-events-targets/test/ecs/integ.event-fargate-task.js.snapshot/EcsFargateTestDefaultTestDeployAssert36341BFB.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-events-targets/test/ecs/integ.event-fargate-task.js.snapshot/aws-ecs-integ-fargate.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-events-targets/test/ecs/integ.event-fargate-task.js.snapshot/aws-ecs-integ-fargate.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-events-targets/test/ecs/integ.event-fargate-task.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-events-targets/test/ecs/integ.event-fargate-task.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-events-targets/test/ecs/integ.event-fargate-task.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-events-targets/test/ecs/integ.event-fargate-task.ts
  packages/aws-cdk-lib/aws-events-targets/README.md
  packages/aws-cdk-lib/aws-events-targets/lib/ecs-task.ts
  packages/aws-cdk-lib/aws-events-targets/test/ecs/event-rule-target.test.ts
Labels: p1, feature-request, effort/small, beginning-contributor

#25179 fix(core): pull alpine image from ecr public
  packages/aws-cdk-lib/core/lib/private/asset-staging.ts
  packages/aws-cdk-lib/core/test/private/asset-staging.test.ts
  packages/aws-cdk-lib/core/test/staging.test.ts
Labels: bug, p1, effort/small, contribution/core, pr-linter/exempt-integ-test

#25160 fix(aws-cdk-lib): compiled .js files are no longer being minified
  packages/aws-cdk-lib/package.json
Labels: p2, contribution/core, pr-linter/exempt-test, pr-linter/exempt-integ-test

#25184 chore(merge-back): 2.75.1
  CHANGELOG.v2.alpha.md
  CHANGELOG.v2.md
  version.v2.json
Labels: p2, pr/no-squash, auto-approve

#25176 chore(kinesisfirehose): small improvements to the README.
  packages/@aws-cdk/aws-kinesisfirehose-alpha/README.md
Labels: p2, contribution/core

#25193 chore: fixing nx cache rules
  nx.json
  packages/@aws-cdk/cloud-assembly-schema/package.json
  packages/@aws-cdk/cx-api/package.json
  packages/@aws-cdk/region-info/package.json
Labels: p2, contribution/core

#25201 chore: add yarn install to buildspec to fix align-version.sh
  buildspec.yaml
Labels: contribution/core, pr-linter/exempt-test, pr-linter/exempt-integ-test

#25202 chore(release): 2.76.0
  buildspec.yaml
Labels: p2, pr/no-squash, auto-approve

#25205 chore(merge-back): 2.76.0
  CHANGELOG.v2.alpha.md
  CHANGELOG.v2.md
  version.v2.json
Labels: p2, pr/no-squash, auto-approve

#25209 chore(neptune): add engine versions 1.2.0.1 , 1.2.0.2 & 1.2.1.0
  packages/@aws-cdk/aws-neptune-alpha/lib/cluster.ts
Labels: p2, feature-request, beginning-contributor

#25141 fix(rds): Correct ARN in IAM policy for IAM database access
  packages/aws-cdk-lib/aws-rds/lib/instance.ts
  packages/aws-cdk-lib/aws-rds/test/instance.test.ts
Labels: bug, p1, effort/small, pr-linter/exempt-integ-test, beginning-contributor, pr-linter/exemption-requested, pr/reviewer-clarification-requested

#24457 fix(elasticloadbalancingv2): can not set sessionTimeout
  packages/@aws-cdk-testing/framework-integ/test/aws-elasticloadbalancingv2-actions/test/integ.cognito.js.snapshot/integ-cognito.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-elasticloadbalancingv2-actions/test/integ.cognito.js.snapshot/integ-cognito.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-elasticloadbalancingv2-actions/test/integ.cognito.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-elasticloadbalancingv2-actions/test/integ.cognito.js.snapshot/integtestcognitoDefaultTestDeployAssert6F2623C9.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-elasticloadbalancingv2-actions/test/integ.cognito.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-elasticloadbalancingv2-actions/test/integ.cognito.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-elasticloadbalancingv2-actions/test/integ.cognito.ts
  packages/@aws-cdk-testing/framework-integ/test/aws-elasticloadbalancingv2/test/integ.alb.js.snapshot/cdk.out
  packages/aws-cdk-lib/aws-elasticloadbalancingv2-actions/lib/cognito-action.ts
  packages/aws-cdk-lib/aws-elasticloadbalancingv2-actions/test/cognito.test.ts
  packages/aws-cdk-lib/aws-elasticloadbalancingv2/lib/alb/application-listener-action.ts
  packages/aws-cdk-lib/aws-elasticloadbalancingv2/lib/alb/application-listener-rule.ts
  packages/aws-cdk-lib/aws-elasticloadbalancingv2/lib/nlb/network-listener-action.ts
  packages/aws-cdk-lib/aws-elasticloadbalancingv2/lib/shared/listener-action.ts
  packages/aws-cdk-lib/aws-elasticloadbalancingv2/test/alb/actions.test.ts
Labels: bug, p1, effort/small, valued-contributor

#25088 feat(eks): support for Kubernetes version 1.26
  packages/aws-cdk-lib/aws-eks/README.md
  packages/aws-cdk-lib/aws-eks/lib/cluster.ts
Labels: p1, feature-request, effort/small, pr-linter/exempt-test, pr-linter/exempt-integ-test, distinguished-contributor

#25224 chore: update .gitpod.yaml to ensure the prebuild
  .gitpod.yml
Labels: bug, p2, effort/small, contribution/core

#25228 fix(custom-resources): State functionActiveV2 not found
  packages/aws-cdk-lib/custom-resources/lib/provider-framework/runtime/outbound.ts
Labels: bug, p0, contribution/core, pr-linter/exempt-test, pr-linter/exempt-integ-test

#25227 chore(merge-back): 1.199.0
  CHANGELOG.md
  version.v1.json
Labels: p2, pr/no-squash, auto-approve

#25235 feat(custom-resource): expose removalPolicy
  packages/aws-cdk-lib/custom-resources/README.md
  packages/aws-cdk-lib/custom-resources/lib/aws-custom-resource/aws-custom-resource.ts
  packages/aws-cdk-lib/custom-resources/test/aws-custom-resource/aws-custom-resource.test.ts
Labels: p2, feature-request, effort/small, pr-linter/exempt-integ-test, admired-contributor, pr-linter/exemption-requested

#25222 feat(ecs-patterns): Tagging support for scheduled tasks
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs-patterns/test/ec2/integ.scheduled-ecs-task.js.snapshot/aws-ecs-integ-ecs.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs-patterns/test/ec2/integ.scheduled-ecs-task.js.snapshot/aws-ecs-integ-ecs.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs-patterns/test/ec2/integ.scheduled-ecs-task.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs-patterns/test/ec2/integ.scheduled-ecs-task.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs-patterns/test/ec2/integ.scheduled-ecs-task.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs-patterns/test/ec2/integ.scheduled-ecs-task.js.snapshot/scheduledEc2TaskTestDefaultTestDeployAssertF02313CA.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs-patterns/test/ec2/integ.scheduled-ecs-task.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs-patterns/test/ec2/integ.scheduled-ecs-task.ts
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs-patterns/test/fargate/integ.scheduled-fargate-task.js.snapshot/aws-fargate-integ.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs-patterns/test/fargate/integ.scheduled-fargate-task.js.snapshot/aws-fargate-integ.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs-patterns/test/fargate/integ.scheduled-fargate-task.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs-patterns/test/fargate/integ.scheduled-fargate-task.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs-patterns/test/fargate/integ.scheduled-fargate-task.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs-patterns/test/fargate/integ.scheduled-fargate-task.js.snapshot/publicQueueProcessingFargateServiceTestDefaultTestDeployAssertD65416D6.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs-patterns/test/fargate/integ.scheduled-fargate-task.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs-patterns/test/fargate/integ.scheduled-fargate-task.ts
  packages/aws-cdk-lib/aws-ecs-patterns/README.md
  packages/aws-cdk-lib/aws-ecs-patterns/lib/base/scheduled-task-base.ts
  packages/aws-cdk-lib/aws-ecs-patterns/lib/fargate/scheduled-fargate-task.ts
  packages/aws-cdk-lib/aws-ecs-patterns/test/ec2/scheduled-ecs-task.test.ts
  packages/aws-cdk-lib/aws-ecs-patterns/test/fargate/scheduled-fargate-task.test.ts
Labels: p2, beginning-contributor

#24856 feat(stepfunctions-tasks): add elasticmapreduce:AddTags permission for EmrCreateCluster state with tags
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/emr/integ.emr-create-cluster-with-tags.js.snapshot/EmrCreateClusterTestDefaultTestDeployAssert697DC891.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/emr/integ.emr-create-cluster-with-tags.js.snapshot/EmrCreateClusterTestDefaultTestDeployAssert697DC891.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/emr/integ.emr-create-cluster-with-tags.js.snapshot/aws-cdk-emr-create-cluster.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/emr/integ.emr-create-cluster-with-tags.js.snapshot/aws-cdk-emr-create-cluster.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/emr/integ.emr-create-cluster-with-tags.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/emr/integ.emr-create-cluster-with-tags.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/emr/integ.emr-create-cluster-with-tags.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/emr/integ.emr-create-cluster-with-tags.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/emr/integ.emr-create-cluster-with-tags.ts
  packages/aws-cdk-lib/aws-stepfunctions-tasks/lib/emr/emr-create-cluster.ts
Labels: bug, p1, effort/medium, pr-linter/exempt-readme, beginning-contributor

#25219 fix(bootstrap): add `previous-parameters` option to bootstrap command
  packages/@aws-cdk-testing/cli-integ/lib/with-cdk-app.ts
  packages/@aws-cdk-testing/cli-integ/tests/cli-integ-tests/bootstrapping.integtest.ts
  packages/aws-cdk/README.md
  packages/aws-cdk/lib/api/bootstrap/bootstrap-props.ts
  packages/aws-cdk/lib/api/bootstrap/deploy-bootstrap.ts
  packages/aws-cdk/lib/cli.ts
Labels: bug, p1, contribution/core, pr-linter/exempt-integ-test, pr-linter/cli-integ-tested

#25243 chore(release): 2.76.1
  CHANGELOG.v2.alpha.md
  CHANGELOG.v2.md
  packages/aws-cdk-lib/custom-resources/lib/provider-framework/runtime/outbound.ts
  version.v2.json
Labels: p2, contribution/core, pr/no-squash

#25240 feat(lambda): Java 17 runtime
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda/test/integ.runtime.fromasset.js.snapshot/IntegDefaultTestDeployAssert4E6713E1.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda/test/integ.runtime.fromasset.js.snapshot/IntegDefaultTestDeployAssert4E6713E1.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda/test/integ.runtime.fromasset.js.snapshot/asset.ae370e1010629b78f494346f49ceef3ab2875718f20e6c808114e6aa770c7bf3.bundle/index.js
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda/test/integ.runtime.fromasset.js.snapshot/asset.ff6ca8da1c8c599aa9f53b242d0e817f8a336ad653e62805a13a5ad46ea7ebe1.zip
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda/test/integ.runtime.fromasset.js.snapshot/aws-cdk-lambda-runtime-fromasset.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda/test/integ.runtime.fromasset.js.snapshot/aws-cdk-lambda-runtime-fromasset.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda/test/integ.runtime.fromasset.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda/test/integ.runtime.fromasset.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda/test/integ.runtime.fromasset.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda/test/integ.runtime.fromasset.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda/test/integ.runtime.fromasset.ts
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda/test/my-app-1.0-SNAPSHOT.zip
  packages/aws-cdk-lib/aws-lambda/lib/runtime.ts
Labels: p2, contribution/core, pr-linter/exempt-readme

#25259 fix(backup): `BackupVault.fromBackupVaultArn` parses wrong arn format
  packages/aws-cdk-lib/aws-backup/lib/vault.ts
  packages/aws-cdk-lib/aws-backup/test/vault.test.ts
Labels: bug, p2, effort/small, pr-linter/exempt-integ-test, admired-contributor, pr-linter/exemption-requested

#25207 fix(batch): jobDefinitionName returns ARN instead of name
  packages/@aws-cdk/aws-batch-alpha/lib/ecs-job-definition.ts
  packages/@aws-cdk/aws-batch-alpha/test/ecs-job-definition.test.ts
Labels: bug, p1, effort/small, pr-linter/exempt-integ-test, admired-contributor, pr-linter/exemption-requested

#25237 fix(eks): Allow helm pull from non-ECR OCI repositories
  packages/@aws-cdk-testing/framework-integ/test/aws-eks/test/integ.eks-helm-asset.js.snapshot/asset.1eabd374284db340b74179e3429008132f5b6b0b7b28d472d852807d7f5f9746/outbound.js
  packages/@aws-cdk-testing/framework-integ/test/aws-eks/test/integ.eks-helm-asset.js.snapshot/asset.45017ac1fb5b50dac36a255c328b0fe125f18a8e6d3689e188eab5e3a1bf8146/cfn-response.js
  packages/@aws-cdk-testing/framework-integ/test/aws-eks/test/integ.eks-helm-asset.js.snapshot/asset.45017ac1fb5b50dac36a255c328b0fe125f18a8e6d3689e188eab5e3a1bf8146/consts.js
  packages/@aws-cdk-testing/framework-integ/test/aws-eks/test/integ.eks-helm-asset.js.snapshot/asset.45017ac1fb5b50dac36a255c328b0fe125f18a8e6d3689e188eab5e3a1bf8146/framework.js
  packages/@aws-cdk-testing/framework-integ/test/aws-eks/test/integ.eks-helm-asset.js.snapshot/asset.45017ac1fb5b50dac36a255c328b0fe125f18a8e6d3689e188eab5e3a1bf8146/outbound.js
  packages/@aws-cdk-testing/framework-integ/test/aws-eks/test/integ.eks-helm-asset.js.snapshot/asset.45017ac1fb5b50dac36a255c328b0fe125f18a8e6d3689e188eab5e3a1bf8146/util.js
  packages/@aws-cdk-testing/framework-integ/test/aws-eks/test/integ.eks-helm-asset.js.snapshot/asset.9017774b84ae2457b1b2ad6fcbb4860d8ce2537062c77010b24d9b156ced5a1b/apply/__init__.py
  packages/@aws-cdk-testing/framework-integ/test/aws-eks/test/integ.eks-helm-asset.js.snapshot/asset.9017774b84ae2457b1b2ad6fcbb4860d8ce2537062c77010b24d9b156ced5a1b/get/__init__.py
  packages/@aws-cdk-testing/framework-integ/test/aws-eks/test/integ.eks-helm-asset.js.snapshot/asset.9017774b84ae2457b1b2ad6fcbb4860d8ce2537062c77010b24d9b156ced5a1b/helm/__init__.py
  packages/@aws-cdk-testing/framework-integ/test/aws-eks/test/integ.eks-helm-asset.js.snapshot/asset.9017774b84ae2457b1b2ad6fcbb4860d8ce2537062c77010b24d9b156ced5a1b/index.py
  packages/@aws-cdk-testing/framework-integ/test/aws-eks/test/integ.eks-helm-asset.js.snapshot/asset.9017774b84ae2457b1b2ad6fcbb4860d8ce2537062c77010b24d9b156ced5a1b/patch/__init__.py
  packages/@aws-cdk-testing/framework-integ/test/aws-eks/test/integ.eks-helm-asset.js.snapshot/aws-cdk-eks-helm-test.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-eks/test/integ.eks-helm-asset.js.snapshot/aws-cdk-eks-helm-test.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-eks/test/integ.eks-helm-asset.js.snapshot/awscdkekshelmtestawscdkawseksClusterResourceProviderB64048CD.nested.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-eks/test/integ.eks-helm-asset.js.snapshot/awscdkekshelmtestawscdkawseksKubectlProvider207F42E4.nested.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-eks/test/integ.eks-helm-asset.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-eks/test/integ.eks-helm-asset.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-eks/test/integ.eks-helm-asset.ts
  packages/aws-cdk-lib/aws-eks/lib/kubectl-handler/helm/__init__.py
Labels: bug, p2, effort/medium, beginning-contributor

#25216 chore: DeletePolicy should default to retain
  packages/aws-cdk/lib/api/cloudformation-deployments.ts
  packages/aws-cdk/lib/cdk-toolkit.ts
  packages/aws-cdk/lib/cli.ts
  packages/aws-cdk/lib/import.ts
Labels: p2, contribution/core, pr-linter/cli-integ-tested

#25270 chore: added colifran to ignore-usernames in github-merit-badges
  .github/workflows/github-merit-badger.yml
Labels: p2, contribution/core, beginning-contributor

#25266 feat(pipelines): added logging as option for codeBuildDefaults prop on CodePipeline construct
  packages/@aws-cdk-testing/framework-integ/test/pipelines/test/integ.newpipeline-with-codebuild-logging.js.snapshot/PipelineStack.assets.json
  packages/@aws-cdk-testing/framework-integ/test/pipelines/test/integ.newpipeline-with-codebuild-logging.js.snapshot/PipelineStack.template.json
  packages/@aws-cdk-testing/framework-integ/test/pipelines/test/integ.newpipeline-with-codebuild-logging.js.snapshot/PipelineStackPipeline9DB740AF.dot
  packages/@aws-cdk-testing/framework-integ/test/pipelines/test/integ.newpipeline-with-codebuild-logging.js.snapshot/PipelineWithCustomStepStackOutputTestDefaultTestDeployAssert6C17E8C5.assets.json
  packages/@aws-cdk-testing/framework-integ/test/pipelines/test/integ.newpipeline-with-codebuild-logging.js.snapshot/PipelineWithCustomStepStackOutputTestDefaultTestDeployAssert6C17E8C5.template.json
  packages/@aws-cdk-testing/framework-integ/test/pipelines/test/integ.newpipeline-with-codebuild-logging.js.snapshot/assembly-PipelineStack-Beta/PipelineStackBetaStack1E6541489.assets.json
  packages/@aws-cdk-testing/framework-integ/test/pipelines/test/integ.newpipeline-with-codebuild-logging.js.snapshot/assembly-PipelineStack-Beta/PipelineStackBetaStack1E6541489.template.json
  packages/@aws-cdk-testing/framework-integ/test/pipelines/test/integ.newpipeline-with-codebuild-logging.js.snapshot/assembly-PipelineStack-Beta/PipelineStackBetaStack2C79AD00A.assets.json
  packages/@aws-cdk-testing/framework-integ/test/pipelines/test/integ.newpipeline-with-codebuild-logging.js.snapshot/assembly-PipelineStack-Beta/PipelineStackBetaStack2C79AD00A.template.json
  packages/@aws-cdk-testing/framework-integ/test/pipelines/test/integ.newpipeline-with-codebuild-logging.js.snapshot/assembly-PipelineStack-Beta/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/pipelines/test/integ.newpipeline-with-codebuild-logging.js.snapshot/assembly-PipelineStack-Beta/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/pipelines/test/integ.newpipeline-with-codebuild-logging.js.snapshot/assembly-PipelineStack-Prod1/PipelineStackProd1Stack14013D698.assets.json
  packages/@aws-cdk-testing/framework-integ/test/pipelines/test/integ.newpipeline-with-codebuild-logging.js.snapshot/assembly-PipelineStack-Prod1/PipelineStackProd1Stack14013D698.template.json
  packages/@aws-cdk-testing/framework-integ/test/pipelines/test/integ.newpipeline-with-codebuild-logging.js.snapshot/assembly-PipelineStack-Prod1/PipelineStackProd1Stack2F0681AFF.assets.json
  packages/@aws-cdk-testing/framework-integ/test/pipelines/test/integ.newpipeline-with-codebuild-logging.js.snapshot/assembly-PipelineStack-Prod1/PipelineStackProd1Stack2F0681AFF.template.json
  packages/@aws-cdk-testing/framework-integ/test/pipelines/test/integ.newpipeline-with-codebuild-logging.js.snapshot/assembly-PipelineStack-Prod1/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/pipelines/test/integ.newpipeline-with-codebuild-logging.js.snapshot/assembly-PipelineStack-Prod1/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/pipelines/test/integ.newpipeline-with-codebuild-logging.js.snapshot/assembly-PipelineStack-Prod2/PipelineStackProd2Stack1FD464162.assets.json
  packages/@aws-cdk-testing/framework-integ/test/pipelines/test/integ.newpipeline-with-codebuild-logging.js.snapshot/assembly-PipelineStack-Prod2/PipelineStackProd2Stack1FD464162.template.json
  packages/@aws-cdk-testing/framework-integ/test/pipelines/test/integ.newpipeline-with-codebuild-logging.js.snapshot/assembly-PipelineStack-Prod2/PipelineStackProd2Stack2176123EB.assets.json
  packages/@aws-cdk-testing/framework-integ/test/pipelines/test/integ.newpipeline-with-codebuild-logging.js.snapshot/assembly-PipelineStack-Prod2/PipelineStackProd2Stack2176123EB.template.json
  packages/@aws-cdk-testing/framework-integ/test/pipelines/test/integ.newpipeline-with-codebuild-logging.js.snapshot/assembly-PipelineStack-Prod2/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/pipelines/test/integ.newpipeline-with-codebuild-logging.js.snapshot/assembly-PipelineStack-Prod2/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/pipelines/test/integ.newpipeline-with-codebuild-logging.js.snapshot/assembly-PipelineStack-Prod3/PipelineStackProd3Stack1795F3D43.assets.json
  packages/@aws-cdk-testing/framework-integ/test/pipelines/test/integ.newpipeline-with-codebuild-logging.js.snapshot/assembly-PipelineStack-Prod3/PipelineStackProd3Stack1795F3D43.template.json
  packages/@aws-cdk-testing/framework-integ/test/pipelines/test/integ.newpipeline-with-codebuild-logging.js.snapshot/assembly-PipelineStack-Prod3/PipelineStackProd3Stack2DFBBA0B2.assets.json
  packages/@aws-cdk-testing/framework-integ/test/pipelines/test/integ.newpipeline-with-codebuild-logging.js.snapshot/assembly-PipelineStack-Prod3/PipelineStackProd3Stack2DFBBA0B2.template.json
  packages/@aws-cdk-testing/framework-integ/test/pipelines/test/integ.newpipeline-with-codebuild-logging.js.snapshot/assembly-PipelineStack-Prod3/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/pipelines/test/integ.newpipeline-with-codebuild-logging.js.snapshot/assembly-PipelineStack-Prod3/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/pipelines/test/integ.newpipeline-with-codebuild-logging.js.snapshot/assembly-PipelineStack-Prod4/PipelineStackProd4Stack118F74ADB.assets.json
  packages/@aws-cdk-testing/framework-integ/test/pipelines/test/integ.newpipeline-with-codebuild-logging.js.snapshot/assembly-PipelineStack-Prod4/PipelineStackProd4Stack118F74ADB.template.json
  packages/@aws-cdk-testing/framework-integ/test/pipelines/test/integ.newpipeline-with-codebuild-logging.js.snapshot/assembly-PipelineStack-Prod4/PipelineStackProd4Stack2E2CB4ED3.assets.json
  packages/@aws-cdk-testing/framework-integ/test/pipelines/test/integ.newpipeline-with-codebuild-logging.js.snapshot/assembly-PipelineStack-Prod4/PipelineStackProd4Stack2E2CB4ED3.template.json
  packages/@aws-cdk-testing/framework-integ/test/pipelines/test/integ.newpipeline-with-codebuild-logging.js.snapshot/assembly-PipelineStack-Prod4/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/pipelines/test/integ.newpipeline-with-codebuild-logging.js.snapshot/assembly-PipelineStack-Prod4/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/pipelines/test/integ.newpipeline-with-codebuild-logging.js.snapshot/assembly-PipelineStack-Prod5/PipelineStackProd5Stack1E7E4E4C6.assets.json
  packages/@aws-cdk-testing/framework-integ/test/pipelines/test/integ.newpipeline-with-codebuild-logging.js.snapshot/assembly-PipelineStack-Prod5/PipelineStackProd5Stack1E7E4E4C6.template.json
  packages/@aws-cdk-testing/framework-integ/test/pipelines/test/integ.newpipeline-with-codebuild-logging.js.snapshot/assembly-PipelineStack-Prod5/PipelineStackProd5Stack2C39BEE5B.assets.json
  packages/@aws-cdk-testing/framework-integ/test/pipelines/test/integ.newpipeline-with-codebuild-logging.js.snapshot/assembly-PipelineStack-Prod5/PipelineStackProd5Stack2C39BEE5B.template.json
  packages/@aws-cdk-testing/framework-integ/test/pipelines/test/integ.newpipeline-with-codebuild-logging.js.snapshot/assembly-PipelineStack-Prod5/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/pipelines/test/integ.newpipeline-with-codebuild-logging.js.snapshot/assembly-PipelineStack-Prod5/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/pipelines/test/integ.newpipeline-with-codebuild-logging.js.snapshot/assembly-PipelineStack-Prod6/PipelineStackProd6Stack1E7C34314.assets.json
  packages/@aws-cdk-testing/framework-integ/test/pipelines/test/integ.newpipeline-with-codebuild-logging.js.snapshot/assembly-PipelineStack-Prod6/PipelineStackProd6Stack1E7C34314.template.json
  packages/@aws-cdk-testing/framework-integ/test/pipelines/test/integ.newpipeline-with-codebuild-logging.js.snapshot/assembly-PipelineStack-Prod6/PipelineStackProd6Stack2BED1BBCE.assets.json
  packages/@aws-cdk-testing/framework-integ/test/pipelines/test/integ.newpipeline-with-codebuild-logging.js.snapshot/assembly-PipelineStack-Prod6/PipelineStackProd6Stack2BED1BBCE.template.json
  packages/@aws-cdk-testing/framework-integ/test/pipelines/test/integ.newpipeline-with-codebuild-logging.js.snapshot/assembly-PipelineStack-Prod6/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/pipelines/test/integ.newpipeline-with-codebuild-logging.js.snapshot/assembly-PipelineStack-Prod6/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/pipelines/test/integ.newpipeline-with-codebuild-logging.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/pipelines/test/integ.newpipeline-with-codebuild-logging.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/pipelines/test/integ.newpipeline-with-codebuild-logging.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/pipelines/test/integ.newpipeline-with-codebuild-logging.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/pipelines/test/integ.newpipeline-with-codebuild-logging.ts
  packages/aws-cdk-lib/pipelines/README.md
  packages/aws-cdk-lib/pipelines/lib/codepipeline/codebuild-step.ts
  packages/aws-cdk-lib/pipelines/lib/codepipeline/codepipeline.ts
  packages/aws-cdk-lib/pipelines/lib/codepipeline/private/codebuild-factory.ts
  packages/aws-cdk-lib/pipelines/test/codepipeline/codebuild-step.test.ts
Labels: p2, feature-request, effort/small, contribution/core, beginning-contributor

#25186 chore: fix final example compilation issues
  package.json
  packages/@aws-cdk/aws-kinesisfirehose-alpha/package.json
  packages/aws-cdk-lib/assertions/README.md
  packages/aws-cdk-lib/aws-ec2/README.md
  packages/aws-cdk-lib/aws-ec2/lib/machine-image/amazon-linux-2023.ts
  packages/aws-cdk-lib/aws-ecs-patterns/README.md
  packages/aws-cdk-lib/aws-eks/README.md
  packages/aws-cdk-lib/aws-events-targets/README.md
  packages/aws-cdk-lib/aws-iam/README.md
  packages/aws-cdk-lib/aws-iam/lib/role.ts
  packages/aws-cdk-lib/aws-s3-deployment/README.md
  packages/aws-cdk-lib/aws-stepfunctions-tasks/README.md
  packages/aws-cdk-lib/custom-resources/README.md
  packages/aws-cdk-lib/package.json
  packages/aws-cdk-lib/pipelines/README.md
  packages/aws-cdk-lib/rosetta/assertions/default.ts-fixture
  packages/aws-cdk-lib/rosetta/aws_eks/cdk8schart.ts-fixture
  packages/aws-cdk-lib/rosetta/custom_resources/default.ts-fixture
  scripts/run-rosetta.sh
  yarn.lock
Labels: p2, contribution/core

#25005 fix(elasticloadbalancingv2): ALB listeners with multiple forwardi…
  packages/@aws-cdk-testing/framework-integ/package.json
  packages/@aws-cdk-testing/framework-integ/test/aws-elasticloadbalancingv2/test/integ.alb.two-target-groups.js.snapshot/Basic.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-elasticloadbalancingv2/test/integ.alb.two-target-groups.js.snapshot/Basic.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-elasticloadbalancingv2/test/integ.alb.two-target-groups.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-elasticloadbalancingv2/test/integ.alb.two-target-groups.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-elasticloadbalancingv2/test/integ.alb.two-target-groups.js.snapshot/issue24805DefaultTestDeployAssert4F284C49.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-elasticloadbalancingv2/test/integ.alb.two-target-groups.js.snapshot/issue24805DefaultTestDeployAssert4F284C49.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-elasticloadbalancingv2/test/integ.alb.two-target-groups.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-elasticloadbalancingv2/test/integ.alb.two-target-groups.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-elasticloadbalancingv2/test/integ.alb.two-target-groups.ts
  packages/aws-cdk-lib/aws-elasticloadbalancingv2/lib/alb/application-listener-action.ts
  packages/aws-cdk-lib/aws-elasticloadbalancingv2/lib/alb/application-listener-rule.ts
Labels: p1, effort/small, beginning-contributor, pr/reviewer-clarification-requested

#25284 fix(apigatewayv2): does not work in non-aws partition
  packages/@aws-cdk-testing/cli-integ/tests/cli-integ-tests/bootstrapping.integtest.ts
  packages/@aws-cdk/aws-apigatewayv2-alpha/lib/http/integration.ts
  packages/@aws-cdk/aws-apigatewayv2-alpha/lib/http/route.ts
  packages/@aws-cdk/aws-apigatewayv2-alpha/test/http/route.test.ts
  packages/@aws-cdk/aws-apigatewayv2-authorizers-alpha/test/http/integ.iam.js.snapshot/IntegApiGatewayV2Iam.assets.json
  packages/@aws-cdk/aws-apigatewayv2-authorizers-alpha/test/http/integ.iam.js.snapshot/IntegApiGatewayV2Iam.template.json
  packages/@aws-cdk/aws-apigatewayv2-authorizers-alpha/test/http/integ.iam.js.snapshot/cdk.out
  packages/@aws-cdk/aws-apigatewayv2-authorizers-alpha/test/http/integ.iam.js.snapshot/integ.json
  packages/@aws-cdk/aws-apigatewayv2-authorizers-alpha/test/http/integ.iam.js.snapshot/manifest.json
  packages/@aws-cdk/aws-apigatewayv2-authorizers-alpha/test/http/integ.iam.js.snapshot/tree.json
  packages/@aws-cdk/aws-cloud9-alpha/lib/environment.ts
  packages/@aws-cdk/aws-cloud9-alpha/test/cloud9.environment.test.ts
  packages/@aws-cdk/aws-servicecatalogappregistry-alpha/lib/application.ts
  packages/@aws-cdk/aws-servicecatalogappregistry-alpha/lib/attribute-group.ts
  packages/@aws-cdk/aws-servicecatalogappregistry-alpha/test/application.test.ts
  packages/@aws-cdk/aws-servicecatalogappregistry-alpha/test/attribute-group.test.ts
  packages/@aws-cdk/aws-servicecatalogappregistry-alpha/test/integ.application.js.snapshot/integ-servicecatalogappregistry-application.assets.json
  packages/@aws-cdk/aws-servicecatalogappregistry-alpha/test/integ.application.js.snapshot/integ-servicecatalogappregistry-application.template.json
  packages/@aws-cdk/aws-servicecatalogappregistry-alpha/test/integ.application.js.snapshot/manifest.json
  packages/@aws-cdk/aws-servicecatalogappregistry-alpha/test/integ.application.js.snapshot/tree.json
  packages/@aws-cdk/aws-servicecatalogappregistry-alpha/test/integ.attribute-group.js.snapshot/integ-servicecatalogappregistry-attribute-group.assets.json
  packages/@aws-cdk/aws-servicecatalogappregistry-alpha/test/integ.attribute-group.js.snapshot/integ-servicecatalogappregistry-attribute-group.template.json
  packages/@aws-cdk/aws-servicecatalogappregistry-alpha/test/integ.attribute-group.js.snapshot/manifest.json
  packages/@aws-cdk/aws-servicecatalogappregistry-alpha/test/integ.attribute-group.js.snapshot/tree.json
  packages/@aws-cdk/cloudformation-diff/lib/iam/statement.ts
  packages/@aws-cdk/integ-runner/lib/runner/runner-base.ts
  packages/aws-cdk/lib/api/bootstrap/bootstrap-environment.ts
  tools/@aws-cdk/cdk-build-tools/config/eslintrc.js
  tools/@aws-cdk/eslint-plugin/README.md
  tools/@aws-cdk/eslint-plugin/lib/index.ts
  tools/@aws-cdk/eslint-plugin/lib/private/is-prod-file.ts
  tools/@aws-cdk/eslint-plugin/lib/rules/no-literal-partition.ts
  tools/@aws-cdk/eslint-plugin/test/rules/fixtures.test.ts
  tools/@aws-cdk/eslint-plugin/test/rules/fixtures/no-literal-partition/eslintrc.js
  tools/@aws-cdk/eslint-plugin/test/rules/fixtures/no-literal-partition/literal-string.error.txt
  tools/@aws-cdk/eslint-plugin/test/rules/fixtures/no-literal-partition/literal-string.ts
  tools/@aws-cdk/eslint-plugin/test/rules/fixtures/no-literal-partition/template-after.error.txt
  tools/@aws-cdk/eslint-plugin/test/rules/fixtures/no-literal-partition/template-after.ts
  tools/@aws-cdk/eslint-plugin/test/rules/fixtures/no-literal-partition/template-before.error.txt
  tools/@aws-cdk/eslint-plugin/test/rules/fixtures/no-literal-partition/template-before.ts
  tools/@aws-cdk/eslint-plugin/test/rules/fixtures/no-literal-partition/template-solo.error.txt
  tools/@aws-cdk/eslint-plugin/test/rules/fixtures/no-literal-partition/template-solo.ts
Labels: p2, contribution/core, pr-linter/exempt-integ-test, pr-linter/cli-integ-tested

#25299 chore(doc): INTEGRATION_TESTS
  INTEGRATION_TESTS.md
Labels: p2, contribution/core

#25245 chore: update gitpod.yaml to build multiple packages
  .gitpod.yml
Labels: p2, contribution/core

#25313 chore: bump rosetta to unblock pipeline
  package.json
  yarn.lock
Labels: p2, contribution/core

#25296 chore(aws-cdk-lib): Add New ADOT Lambda Layer ARNs
  packages/aws-cdk-lib/region-info/build-tools/fact-tables.ts
Labels: p2, beginning-contributor

#25315 chore: disable rosetta strict mode again
  packages/aws-cdk-lib/package.json
Labels: p2, contribution/core

#25303 fix: log buckets don't have acls enabled
  packages/@aws-cdk-testing/framework-integ/test/aws-s3/test/integ.bucket-acls.js.snapshot/BucketOwnerFullControl.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-s3/test/integ.bucket-acls.js.snapshot/BucketOwnerFullControl.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-s3/test/integ.bucket-acls.js.snapshot/BucketOwnerRead.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-s3/test/integ.bucket-acls.js.snapshot/BucketOwnerRead.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-s3/test/integ.bucket-acls.js.snapshot/Private.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-s3/test/integ.bucket-acls.js.snapshot/Private.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-s3/test/integ.bucket-acls.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-s3/test/integ.bucket-acls.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-s3/test/integ.bucket-acls.js.snapshot/integtestDefaultTestDeployAssert24D5C536.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-s3/test/integ.bucket-acls.js.snapshot/integtestDefaultTestDeployAssert24D5C536.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-s3/test/integ.bucket-acls.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-s3/test/integ.bucket-acls.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-s3/test/integ.bucket-acls.ts
  packages/aws-cdk-lib/aws-s3/lib/bucket.ts
  packages/aws-cdk-lib/aws-s3/test/bucket.test.ts
Labels: p1, feature-request, effort/small, contribution/core, pr-linter/exempt-integ-test

#25316 fix(pipelines): CodeBuild Action role can be assumed by too many identities
  packages/@aws-cdk-testing/framework-integ/test/pipelines/test/integ.newpipeline-with-codebuild-logging.js.snapshot/PipelineStack.assets.json
  packages/@aws-cdk-testing/framework-integ/test/pipelines/test/integ.newpipeline-with-codebuild-logging.js.snapshot/PipelineStack.template.json
  packages/@aws-cdk-testing/framework-integ/test/pipelines/test/integ.newpipeline-with-codebuild-logging.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/pipelines/test/integ.newpipeline-with-codebuild-logging.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/pipelines/test/integ.newpipeline-with-cross-account-keys.js.snapshot/PipelineStack.assets.json
  packages/@aws-cdk-testing/framework-integ/test/pipelines/test/integ.newpipeline-with-cross-account-keys.js.snapshot/PipelineStack.template.json
  packages/@aws-cdk-testing/framework-integ/test/pipelines/test/integ.newpipeline-with-cross-account-keys.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/pipelines/test/integ.newpipeline-with-cross-account-keys.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/pipelines/test/integ.newpipeline-with-file-system-locations.js.snapshot/PipelinesFileSystemLocations.assets.json
  packages/@aws-cdk-testing/framework-integ/test/pipelines/test/integ.newpipeline-with-file-system-locations.js.snapshot/PipelinesFileSystemLocations.template.json
  packages/@aws-cdk-testing/framework-integ/test/pipelines/test/integ.newpipeline-with-file-system-locations.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/pipelines/test/integ.newpipeline-with-file-system-locations.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/pipelines/test/integ.newpipeline-with-vpc.js.snapshot/PipelineStack.assets.json
  packages/@aws-cdk-testing/framework-integ/test/pipelines/test/integ.newpipeline-with-vpc.js.snapshot/PipelineStack.template.json
  packages/@aws-cdk-testing/framework-integ/test/pipelines/test/integ.newpipeline-with-vpc.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/pipelines/test/integ.newpipeline-with-vpc.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/pipelines/test/integ.newpipeline.js.snapshot/PipelineStack.assets.json
  packages/@aws-cdk-testing/framework-integ/test/pipelines/test/integ.newpipeline.js.snapshot/PipelineStack.template.json
  packages/@aws-cdk-testing/framework-integ/test/pipelines/test/integ.newpipeline.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/pipelines/test/integ.newpipeline.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/pipelines/test/integ.pipeline-with-artifact-bucket.js.snapshot/PipelineStack.assets.json
  packages/@aws-cdk-testing/framework-integ/test/pipelines/test/integ.pipeline-with-artifact-bucket.js.snapshot/PipelineStack.template.json
  packages/@aws-cdk-testing/framework-integ/test/pipelines/test/integ.pipeline-with-artifact-bucket.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/pipelines/test/integ.pipeline-with-artifact-bucket.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/pipelines/test/integ.pipeline-with-stack-outputs-in-custom-step.js.snapshot/PipelineWithCustomStepStackOutputTestDefaultTestDeployAssert6C17E8C5.assets.json
  packages/@aws-cdk-testing/framework-integ/test/pipelines/test/integ.pipeline-with-stack-outputs-in-custom-step.js.snapshot/StackOutputPipelineStack.assets.json
  packages/@aws-cdk-testing/framework-integ/test/pipelines/test/integ.pipeline-with-stack-outputs-in-custom-step.js.snapshot/StackOutputPipelineStack.template.json
  packages/@aws-cdk-testing/framework-integ/test/pipelines/test/integ.pipeline-with-stack-outputs-in-custom-step.js.snapshot/assembly-StackOutputPipelineStack-AppStage/StackOutputPipelineStackAppStageStackB810E610.assets.json
  packages/@aws-cdk-testing/framework-integ/test/pipelines/test/integ.pipeline-with-stack-outputs-in-custom-step.js.snapshot/assembly-StackOutputPipelineStack-AppStage/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/pipelines/test/integ.pipeline-with-stack-outputs-in-custom-step.js.snapshot/assembly-StackOutputPipelineStack-AppStage/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/pipelines/test/integ.pipeline-with-stack-outputs-in-custom-step.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/pipelines/test/integ.pipeline-with-stack-outputs-in-custom-step.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/pipelines/test/integ.pipeline-with-stack-outputs-in-custom-step.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/pipelines/test/integ.pipeline-with-stack-outputs-in-custom-step.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/pipelines/test/integ.pipeline-with-variables.js.snapshot/VariablePipelineStack.assets.json
  packages/@aws-cdk-testing/framework-integ/test/pipelines/test/integ.pipeline-with-variables.js.snapshot/VariablePipelineStack.template.json
  packages/@aws-cdk-testing/framework-integ/test/pipelines/test/integ.pipeline-with-variables.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/pipelines/test/integ.pipeline-with-variables.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/pipelines/test/integ.pipeline-without-prepare.js.snapshot/PreparelessPipelineStack.assets.json
  packages/@aws-cdk-testing/framework-integ/test/pipelines/test/integ.pipeline-without-prepare.js.snapshot/PreparelessPipelineStack.template.json
  packages/@aws-cdk-testing/framework-integ/test/pipelines/test/integ.pipeline-without-prepare.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/pipelines/test/integ.pipeline-without-prepare.js.snapshot/tree.json
  packages/aws-cdk-lib/pipelines/lib/codepipeline/codepipeline-action-factory.ts
  packages/aws-cdk-lib/pipelines/lib/codepipeline/private/codebuild-factory.ts
  packages/aws-cdk-lib/pipelines/test/codepipeline/codepipeline.test.ts
Labels: p2, contribution/core, pr-linter/exempt-integ-test

#25294 fix(cli): diff doesn't display paths for removed resources
  packages/aws-cdk/lib/diff.ts
Labels: p2, contribution/core, pr-linter/exempt-test, pr-linter/exempt-integ-test, pr-linter/cli-integ-tested

#25320 chore(cfnspec): fix the cfnspec update
  buildspec-pr.yaml
  packages/@aws-cdk/cfnspec/build-tools/build.ts
  packages/@aws-cdk/cfnspec/build-tools/create-missing-libraries.ts
  packages/@aws-cdk/cfnspec/build-tools/spec-diff.ts
  packages/@aws-cdk/cfnspec/build-tools/update.sh
  packages/@aws-cdk/cfnspec/build-tools/validate-evolution.ts
  packages/@aws-cdk/cfnspec/package.json
  packages/@aws-cdk/cfnspec/spec-source/specification/000_cfn/560_Macie_FindingsFilter_Attributes_FindingsFilterListItems_patch.json
  packages/@aws-cdk/cfnspec/spec-source/specification/000_cfn/910_ApiGatewayV2_Route_patch.json
  packages/@aws-cdk/cfnspec/spec-source/specification/000_cfn/911_Batch_JobDefinition_patch.json
  packages/@aws-cdk/cfnspec/spec-source/specification/000_cfn/912_Macie_FindingsFilter_patch.json
Labels: p2, contribution/core

#25326 chore: fix patch build
  packages/@aws-cdk/cfnspec/build-tools/build.ts
  packages/@aws-cdk/cfnspec/build-tools/massage-spec.ts
  packages/@aws-cdk/cfnspec/build-tools/validate-evolution.ts
  packages/@aws-cdk/cfnspec/skip-evolution-check.txt
  packages/@aws-cdk/cfnspec/spec-source/specification/000_cfn/911_Batch_JobDefinition_patch.json
Labels: p2, contribution/core

#25321 chore(doc): update the contributing guide with more details
  CONTRIBUTING.md
Labels: p1, feature-request, effort/small, contribution/core

#25327 docs(triggers): correct triggers InvocationType documentation
  packages/aws-cdk-lib/triggers/lib/trigger.ts
Labels: bug, p2, effort/small, beginning-contributor

#25324 fix(apigateway): cannot use requestValidatorOptions multiple times (under feature flag)
  packages/aws-cdk-lib/aws-apigateway/README.md
  packages/aws-cdk-lib/aws-apigateway/lib/method.ts
  packages/aws-cdk-lib/aws-apigateway/test/resource.test.ts
  packages/aws-cdk-lib/cx-api/lib/features.ts
Labels: bug, p1, effort/small, contribution/core, pr-linter/exempt-integ-test

#25340 chore(merge-back): 2.77.0
  CHANGELOG.v2.alpha.md
  CHANGELOG.v2.md
  version.v2.json
Labels: pr/no-squash, auto-approve

#25341 chore(merge-back): 1.200.0
  CHANGELOG.md
  version.v1.json
Labels: p2, pr/no-squash, auto-approve

#25214 chore(core): fix typo
  packages/aws-cdk-lib/README.md
  packages/aws-cdk-lib/core/README.md
Labels: p2, beginning-contributor

#25239 chore(aws-cdk-lib): Run pre and post package steps for aws-cdk-lib from pack.sh
  pack.sh
  packages/aws-cdk-lib/package.json
  scripts/check-pack-prerequisites.sh
  tools/@aws-cdk/cdk-build-tools/bin/cdk-package.ts
  tools/@aws-cdk/cdk-build-tools/lib/package-info.ts
Labels: p2, contribution/core

#25269 fix(batch): JobQueue uses wrong id for underlying CfnJobQueue
  packages/@aws-cdk-testing/framework-integ/test/aws-events-targets/test/batch/integ.job-definition-events.js.snapshot/batch-events.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-events-targets/test/batch/integ.job-definition-events.js.snapshot/batch-events.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-events-targets/test/batch/integ.job-definition-events.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-events-targets/test/batch/integ.job-definition-events.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/batch/integ.run-batch-job.js.snapshot/aws-stepfunctions-integ.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/batch/integ.run-batch-job.js.snapshot/aws-stepfunctions-integ.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/batch/integ.run-batch-job.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/batch/integ.run-batch-job.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/batch/integ.submit-job.js.snapshot/aws-stepfunctions-integ.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/batch/integ.submit-job.js.snapshot/aws-stepfunctions-integ.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/batch/integ.submit-job.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/batch/integ.submit-job.js.snapshot/tree.json
  packages/@aws-cdk/aws-batch-alpha/lib/job-queue.ts
  packages/@aws-cdk/aws-batch-alpha/lib/managed-compute-environment.ts
  packages/@aws-cdk/aws-batch-alpha/lib/scheduling-policy.ts
  packages/@aws-cdk/aws-batch-alpha/test/aws-events-targets/batch.test.ts
  packages/@aws-cdk/aws-batch-alpha/test/aws-stepfunctions-tasks/run-batch-job.test.ts
  packages/@aws-cdk/aws-batch-alpha/test/aws-stepfunctions-tasks/submit-job.test.ts
  packages/@aws-cdk/aws-batch-alpha/test/integ.batch-unique-name.js.snapshot/manifest.json
  packages/@aws-cdk/aws-batch-alpha/test/integ.batch-unique-name.js.snapshot/stack.assets.json
  packages/@aws-cdk/aws-batch-alpha/test/integ.batch-unique-name.js.snapshot/stack.template.json
  packages/@aws-cdk/aws-batch-alpha/test/integ.batch-unique-name.js.snapshot/tree.json
  packages/@aws-cdk/aws-batch-alpha/test/integ.job-queue.js.snapshot/manifest.json
  packages/@aws-cdk/aws-batch-alpha/test/integ.job-queue.js.snapshot/stack.assets.json
  packages/@aws-cdk/aws-batch-alpha/test/integ.job-queue.js.snapshot/stack.template.json
  packages/@aws-cdk/aws-batch-alpha/test/integ.job-queue.js.snapshot/tree.json
  packages/@aws-cdk/aws-batch-alpha/test/integ.managed-compute-environment.js.snapshot/batch-stack.assets.json
  packages/@aws-cdk/aws-batch-alpha/test/integ.managed-compute-environment.js.snapshot/batch-stack.template.json
  packages/@aws-cdk/aws-batch-alpha/test/integ.managed-compute-environment.js.snapshot/manifest.json
  packages/@aws-cdk/aws-batch-alpha/test/integ.managed-compute-environment.js.snapshot/tree.json
  packages/@aws-cdk/aws-batch-alpha/test/job-queue.test.ts
Labels: bug, p2, effort/small, pr-linter/exempt-integ-test, star-contributor

#25349 chore(config): Runtime updating of test code
  packages/aws-cdk-lib/aws-config/README.md
  packages/aws-cdk-lib/aws-config/test/rule.test.ts
Labels: p2, star-contributor

#25348 fix: dns-validated-cert cr doesn't use node16
  packages/@aws-cdk-testing/framework-integ/test/aws-certificatemanager/test/integ.dns-validated-certificate.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-certificatemanager/test/integ.dns-validated-certificate.js.snapshot/integ-dns-validated-certificate.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-certificatemanager/test/integ.dns-validated-certificate.js.snapshot/integ-dns-validated-certificate.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-certificatemanager/test/integ.dns-validated-certificate.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-certificatemanager/test/integ.dns-validated-certificate.js.snapshot/integtestDefaultTestDeployAssert24D5C536.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-certificatemanager/test/integ.dns-validated-certificate.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-certificatemanager/test/integ.dns-validated-certificate.js.snapshot/tree.json
  packages/aws-cdk-lib/aws-certificatemanager/lib/dns-validated-certificate.ts
  packages/aws-cdk-lib/aws-certificatemanager/test/dns-validated-certificate.test.ts
Labels: p2, contribution/core, pr-linter/exempt-integ-test

#25357 chore: rename private package `cdk-cli-wrapper` to `@aws-cdk/cdk-cli-wrapper`
  packages/@aws-cdk/cdk-cli-wrapper/.eslintrc.js
  packages/@aws-cdk/cdk-cli-wrapper/.gitignore
  packages/@aws-cdk/cdk-cli-wrapper/.npmignore
  packages/@aws-cdk/cdk-cli-wrapper/LICENSE
  packages/@aws-cdk/cdk-cli-wrapper/NOTICE
  packages/@aws-cdk/cdk-cli-wrapper/README.md
  packages/@aws-cdk/cdk-cli-wrapper/jest.config.js
  packages/@aws-cdk/cdk-cli-wrapper/lib/cdk-wrapper.ts
  packages/@aws-cdk/cdk-cli-wrapper/lib/commands/common.ts
  packages/@aws-cdk/cdk-cli-wrapper/lib/commands/deploy.ts
  packages/@aws-cdk/cdk-cli-wrapper/lib/commands/destroy.ts
  packages/@aws-cdk/cdk-cli-wrapper/lib/commands/index.ts
  packages/@aws-cdk/cdk-cli-wrapper/lib/commands/list.ts
  packages/@aws-cdk/cdk-cli-wrapper/lib/commands/synth.ts
  packages/@aws-cdk/cdk-cli-wrapper/lib/index.ts
  packages/@aws-cdk/cdk-cli-wrapper/lib/utils.ts
  packages/@aws-cdk/cdk-cli-wrapper/package.json
  packages/@aws-cdk/cdk-cli-wrapper/test/cdk-wrapper.test.ts
  packages/@aws-cdk/cdk-cli-wrapper/tsconfig.json
  packages/@aws-cdk/integ-runner/lib/runner/integ-test-runner.ts
  packages/@aws-cdk/integ-runner/lib/runner/integ-test-suite.ts
  packages/@aws-cdk/integ-runner/lib/runner/runner-base.ts
  packages/@aws-cdk/integ-runner/package.json
  packages/@aws-cdk/integ-runner/test/helpers.ts
Labels: p2, contribution/core

#25241 fix(integ-tests): allow multiple AwsApiCalls with the same action and different parameters
  packages/@aws-cdk/aws-redshift-alpha/test/integ.cluster-reboot.js.snapshot/asset.36618132bd37b6b15f9987b57ad1fbf613f1ad937aec72381232b163ed9c44c4.bundle/index.js
  packages/@aws-cdk/aws-redshift-alpha/test/integ.cluster-reboot.js.snapshot/asset.382ba2a8fd0a13f6782aec5543e465f988f5c100f35ed20f90cd96b8ee53f674.bundle/index.js
  packages/@aws-cdk/aws-redshift-alpha/test/integ.cluster-reboot.js.snapshot/aws-cdk-redshift-cluster-create.assets.json
  packages/@aws-cdk/aws-redshift-alpha/test/integ.cluster-reboot.js.snapshot/aws-cdk-redshift-cluster-create.template.json
  packages/@aws-cdk/aws-redshift-alpha/test/integ.cluster-reboot.js.snapshot/aws-cdk-redshift-cluster-update.assets.json
  packages/@aws-cdk/aws-redshift-alpha/test/integ.cluster-reboot.js.snapshot/aws-cdk-redshift-cluster-update.template.json
  packages/@aws-cdk/aws-redshift-alpha/test/integ.cluster-reboot.js.snapshot/awscdkredshiftreboottestDefaultTestDeployAssert1AE11B34.assets.json
  packages/@aws-cdk/aws-redshift-alpha/test/integ.cluster-reboot.js.snapshot/awscdkredshiftreboottestDefaultTestDeployAssert1AE11B34.template.json
  packages/@aws-cdk/aws-redshift-alpha/test/integ.cluster-reboot.js.snapshot/cdk.out
  packages/@aws-cdk/aws-redshift-alpha/test/integ.cluster-reboot.js.snapshot/integ.json
  packages/@aws-cdk/aws-redshift-alpha/test/integ.cluster-reboot.js.snapshot/manifest.json
  packages/@aws-cdk/aws-redshift-alpha/test/integ.cluster-reboot.js.snapshot/tree.json
  packages/@aws-cdk/aws-redshift-alpha/test/integ.cluster-reboot.ts
  packages/@aws-cdk/integ-tests-alpha/lib/assertions/private/deploy-assert.ts
Labels: bug, p1, beginning-contributor

#25279 fix(batch): `ManagedEc2EcsComputeEnvironment` instance role missing managed policy
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/batch/integ.run-batch-job.js.snapshot/aws-stepfunctions-integ.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/batch/integ.run-batch-job.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/batch/integ.submit-job.js.snapshot/aws-stepfunctions-integ.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/batch/integ.submit-job.js.snapshot/tree.json
  packages/@aws-cdk/aws-batch-alpha/lib/managed-compute-environment.ts
  packages/@aws-cdk/aws-batch-alpha/test/integ.job-queue.js.snapshot/stack.template.json
  packages/@aws-cdk/aws-batch-alpha/test/integ.job-queue.js.snapshot/tree.json
  packages/@aws-cdk/aws-batch-alpha/test/integ.managed-compute-environment.js.snapshot/batch-stack.template.json
  packages/@aws-cdk/aws-batch-alpha/test/integ.managed-compute-environment.js.snapshot/tree.json
  packages/@aws-cdk/aws-batch-alpha/test/managed-compute-environment.test.ts
Labels: bug, p2, effort/small, pr-linter/exempt-integ-test, admired-contributor
