Repository aws/aws-cdk, pull requests merged in 2023-05, with the labels that each got.

#25381 chore: update nodejs to 18 in devcontainer
  .devcontainer/Dockerfile
Labels: p2, admired-contributor

#25382 chore(pkglint): ignore alpha version of `cdk-cli-wrapper`
  tools/@aws-cdk/pkglint/lib/rules.ts
Labels: p2, contribution/core

#25367 chore(opensearchsearvice): add opensearch 2.5 support
  packages/@aws-cdk-testing/framework-integ/test/aws-opensearchservice/test/integ.opensearch.min.js.snapshot/IntegDefaultTestDeployAssert4E6713E1.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-opensearchservice/test/integ.opensearch.min.js.snapshot/IntegDefaultTestDeployAssert4E6713E1.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-opensearchservice/test/integ.opensearch.min.js.snapshot/cdk-integ-opensearch.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-opensearchservice/test/integ.opensearch.min.js.snapshot/cdk-integ-opensearch.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-opensearchservice/test/integ.opensearch.min.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-opensearchservice/test/integ.opensearch.min.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-opensearchservice/test/integ.opensearch.min.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-opensearchservice/test/integ.opensearch.min.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-opensearchservice/test/integ.opensearch.min.ts
  packages/aws-cdk-lib/aws-opensearchservice/lib/version.ts
  packages/aws-cdk-lib/aws-opensearchservice/test/domain.test.ts
Labels: p2, feature-request, effort/medium, contribution/core

#25372 docs(lambda-nodejs): Correct Dockerfile link
  packages/aws-cdk-lib/aws-lambda-nodejs/README.md
Labels: p2, beginning-contributor

#25366 feat(events): Validate events rule name
  packages/aws-cdk-lib/aws-events/lib/rule.ts
  packages/aws-cdk-lib/aws-events/test/rule.test.ts
Labels: p2, feature-request, effort/small, pr-linter/exempt-readme, pr-linter/exempt-integ-test, beginning-contributor, pr-linter/exemption-requested

#25389 fix(iam): Role.fromRoleName fails on AWS created roles
  packages/aws-cdk-lib/aws-iam/lib/role.ts
  packages/aws-cdk-lib/aws-iam/test/role.test.ts
Labels: bug, p0, effort/small, contribution/core, pr-linter/exempt-integ-test

#25401 chore(integ-runner): removing cdk-cli-wrapper peer dependency
  packages/@aws-cdk/integ-runner/package.json
Labels: p2, contribution/core

#25355 chore: upgrade dependencies to remove `vm2` vulnerability
  package.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-nodejs/tsconfig.json
  packages/@aws-cdk/cdk-cli-wrapper/tsconfig.json
  packages/@aws-cdk/cfnspec/tsconfig.json
  packages/@aws-cdk/cli-lib-alpha/THIRD_PARTY_LICENSES
  packages/@aws-cdk/cloudformation-diff/tsconfig.json
  packages/@aws-cdk/integ-runner/THIRD_PARTY_LICENSES
  packages/aws-cdk-lib/aws-lambda-nodejs/test/testtsconfig.json
  packages/aws-cdk-lib/custom-resources/lib/aws-custom-resource/sdk-api-metadata.json
  packages/aws-cdk-lib/tsconfig.dev.json
  packages/aws-cdk/THIRD_PARTY_LICENSES
  packages/aws-cdk/lib/api/cxapp/cloud-assembly.ts
  packages/aws-cdk/lib/api/cxapp/environments.ts
  packages/aws-cdk/lib/commands/context.ts
  packages/aws-cdk/lib/init-templates/app/typescript/tsconfig.json
  packages/aws-cdk/lib/init-templates/lib/typescript/tsconfig.json
  packages/aws-cdk/lib/init-templates/sample-app/javascript/tsconfig.json
  packages/aws-cdk/lib/init-templates/sample-app/typescript/tsconfig.json
  packages/aws-cdk/package.json
  packages/aws-cdk/tsconfig.json
  packages/awslint/tsconfig.json
  tools/@aws-cdk/cdk-build-tools/tsconfig.json
  tools/@aws-cdk/cdk-release/tsconfig.json
  tools/@aws-cdk/cfn2ts/tsconfig.json
  tools/@aws-cdk/eslint-plugin/tsconfig.json
  tools/@aws-cdk/pkglint/tsconfig.json
  tools/@aws-cdk/pkgtools/tsconfig.json
  tools/@aws-cdk/prlint/tsconfig.json
  tools/@aws-cdk/yarn-cling/tsconfig.json
  yarn.lock
Labels: p2, contribution/core, pr-linter/cli-integ-tested

#25363 fix(s3-deployment): doesn't work in ADC regions
  packages/@aws-cdk-testing/framework-integ/test/aws-codepipeline-actions/test/integ.pipeilne-elastic-beanstalk-deploy.js.snapshot/aws-cdk-codepipeline-elastic-beanstalk-deploy.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-codepipeline-actions/test/integ.pipeilne-elastic-beanstalk-deploy.js.snapshot/aws-cdk-codepipeline-elastic-beanstalk-deploy.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-codepipeline-actions/test/integ.pipeilne-elastic-beanstalk-deploy.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-codepipeline-actions/test/integ.pipeilne-elastic-beanstalk-deploy.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs/test/ec2/integ.environment-file.js.snapshot/aws-ecs-integ.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs/test/ec2/integ.environment-file.js.snapshot/aws-ecs-integ.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs/test/ec2/integ.environment-file.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs/test/ec2/integ.environment-file.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-s3-deployment/test/integ.bucket-deployment-cloudfront.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-s3-deployment/test/integ.bucket-deployment-cloudfront.js.snapshot/test-bucket-deployments-1.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-s3-deployment/test/integ.bucket-deployment-cloudfront.js.snapshot/test-bucket-deployments-1.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-s3-deployment/test/integ.bucket-deployment-cloudfront.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-s3-deployment/test/integ.bucket-deployment-data.js.snapshot/TestBucketDeploymentContent.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-s3-deployment/test/integ.bucket-deployment-data.js.snapshot/TestBucketDeploymentContent.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-s3-deployment/test/integ.bucket-deployment-data.js.snapshot/asset.9eb41a5505d37607ac419321497a4f8c21cf0ee1f9b4a6b29aa04301aea5c7fd/index.py
  packages/@aws-cdk-testing/framework-integ/test/aws-s3-deployment/test/integ.bucket-deployment-data.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-s3-deployment/test/integ.bucket-deployment-data.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-s3-deployment/test/integ.bucket-deployment-deployed-bucket.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-s3-deployment/test/integ.bucket-deployment-deployed-bucket.js.snapshot/test-bucket-deployment-deployed-bucket.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-s3-deployment/test/integ.bucket-deployment-deployed-bucket.js.snapshot/test-bucket-deployment-deployed-bucket.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-s3-deployment/test/integ.bucket-deployment-deployed-bucket.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-s3-deployment/test/integ.bucket-deployment-signcontent.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-s3-deployment/test/integ.bucket-deployment-signcontent.js.snapshot/test-bucket-deployment-signobject.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-s3-deployment/test/integ.bucket-deployment-signcontent.js.snapshot/test-bucket-deployment-signobject.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-s3-deployment/test/integ.bucket-deployment-signcontent.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-s3-deployment/test/integ.bucket-deployment.js.snapshot/integtestbucketdeploymentsDefaultTestDeployAssertCF25A2DF.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-s3-deployment/test/integ.bucket-deployment.js.snapshot/integtestbucketdeploymentsDefaultTestDeployAssertCF25A2DF.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-s3-deployment/test/integ.bucket-deployment.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-s3-deployment/test/integ.bucket-deployment.js.snapshot/test-bucket-deployments-2.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-s3-deployment/test/integ.bucket-deployment.js.snapshot/test-bucket-deployments-2.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-s3-deployment/test/integ.bucket-deployment.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-servicecatalog/test/integ.product.js.snapshot/integ-servicecatalog-product.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-servicecatalog/test/integ.product.js.snapshot/integ-servicecatalog-product.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-servicecatalog/test/integ.product.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-servicecatalog/test/integ.product.js.snapshot/tree.json
  packages/aws-cdk-lib/aws-s3-deployment/lib/bucket-deployment.ts
  packages/aws-cdk-lib/aws-s3-deployment/test/bucket-deployment.test.ts
Labels: p2, contribution/core, pr-linter/exempt-integ-test

#25328 fix(ecs): Allow scheduling DAEMON services even if no EC2 capacity attached to cluster (#25306)
  packages/aws-cdk-lib/aws-ecs/lib/ec2/ec2-service.ts
  packages/aws-cdk-lib/aws-ecs/test/ec2/ec2-service.test.ts
Labels: p2, feature-request, effort/medium, pr-linter/exempt-integ-test, valued-contributor, pr-linter/exemption-requested

#25369 feat(appsync): L2 construct for EventBridge DataSource.
  packages/@aws-cdk-testing/framework-integ/test/aws-appsync/test/appsync.eventbridge.graphql
  packages/@aws-cdk-testing/framework-integ/test/aws-appsync/test/integ.appsync-eventbridge.js.snapshot/apiDefaultTestDeployAssert018781F2.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-appsync/test/integ.appsync-eventbridge.js.snapshot/apiDefaultTestDeployAssert018781F2.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-appsync/test/integ.appsync-eventbridge.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-appsync/test/integ.appsync-eventbridge.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-appsync/test/integ.appsync-eventbridge.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-appsync/test/integ.appsync-eventbridge.js.snapshot/stack.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-appsync/test/integ.appsync-eventbridge.js.snapshot/stack.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-appsync/test/integ.appsync-eventbridge.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-appsync/test/integ.appsync-eventbridge.ts
  packages/aws-cdk-lib/aws-appsync/README.md
  packages/aws-cdk-lib/aws-appsync/lib/data-source.ts
  packages/aws-cdk-lib/aws-appsync/lib/graphqlapi-base.ts
  packages/aws-cdk-lib/aws-appsync/test/appsync-eventbridge.test.ts
Labels: p2, feature-request, effort/medium, beginning-contributor

#25427 chore(merge-back): 2.78.0
  CHANGELOG.v2.alpha.md
  CHANGELOG.v2.md
  version.v2.json
Labels: p2, pr/no-squash, auto-approve

#25436 chore(aws-cdk-lib): ignore cfn-types-2-classes.json
  packages/aws-cdk-lib/.gitignore
  packages/aws-cdk-lib/.npmignore
  packages/aws-cdk-lib/cloudformation-include/cfn-types-2-classes.json
  packages/aws-cdk-lib/scripts/gen.ts
Labels: p2, contribution/core

#25435 chore: serverAccessLogsUseBucketPolicy flag was released in 2.60.0
  packages/@aws-cdk/cx-api/FEATURE_FLAGS.md
  packages/aws-cdk-lib/cx-api/FEATURE_FLAGS.md
  packages/aws-cdk-lib/cx-api/lib/features.ts
Labels: p2, contribution/core

#25439 chore: rename `_` identifiers away
  packages/aws-cdk-lib/aws-cloudformation/lib/custom-resource.ts
  packages/aws-cdk-lib/aws-codebuild/lib/project.ts
  packages/aws-cdk-lib/aws-lambda/lib/code.ts
  packages/aws-cdk-lib/core/lib/cfn-json.ts
  packages/aws-cdk-lib/custom-resources/lib/aws-custom-resource/aws-custom-resource.ts
Labels: p2, contribution/core

#25414 chore(prlint): use `pr/needs-review` label
  .github/workflows/pr-linter.yml
  CONTRIBUTING.md
  tools/@aws-cdk/prlint/index.ts
  tools/@aws-cdk/prlint/lint.ts
  tools/@aws-cdk/prlint/package.json
  tools/@aws-cdk/prlint/test/lint.test.ts
  tools/@aws-cdk/prlint/test/module.test.ts
  yarn.lock
Labels: p2, contribution/core

#25444 chore(prlint): handle case where label does not exist
  tools/@aws-cdk/prlint/lint.ts
  tools/@aws-cdk/prlint/test/lint.test.ts
Labels: p2, pr/needs-review, contribution/core

#25454 fix(servicecatalogappregistry): Revert deprecated method removing PR to keep deprecated method in alpha version
  packages/@aws-cdk/aws-servicecatalogappregistry-alpha/lib/application.ts
  packages/@aws-cdk/aws-servicecatalogappregistry-alpha/test/application.test.ts
  packages/@aws-cdk/aws-servicecatalogappregistry-alpha/test/integ.application.js.snapshot/integ-servicecatalogappregistry-application.assets.json
  packages/@aws-cdk/aws-servicecatalogappregistry-alpha/test/integ.application.js.snapshot/integ-servicecatalogappregistry-application.template.json
  packages/@aws-cdk/aws-servicecatalogappregistry-alpha/test/integ.application.js.snapshot/manifest.json
  packages/@aws-cdk/aws-servicecatalogappregistry-alpha/test/integ.application.js.snapshot/tree.json
  packages/@aws-cdk/aws-servicecatalogappregistry-alpha/test/integ.application.ts
Labels: p2, pr/needs-review, beginning-contributor

#25446 docs: add note about stored context when looking up VPC AZs
  packages/aws-cdk-lib/aws-ec2/README.md
Labels: p2, feature-request, effort/small, pr/needs-review, contribution/core

#25457 chore(prlint): get sha from context
  tools/@aws-cdk/prlint/index.ts
  tools/@aws-cdk/prlint/lint.ts
Labels: p2, pr/needs-review, contribution/core

#25445 feat(ecr): grantRead on repositories
  packages/@aws-cdk-testing/framework-integ/test/aws-ecr/test/integ.basic.js.snapshot/aws-ecr-integ-stack.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecr/test/integ.basic.js.snapshot/aws-ecr-integ-stack.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecr/test/integ.basic.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-ecr/test/integ.basic.js.snapshot/cdkecrintegtestbasicDefaultTestDeployAssert4F7FBFB4.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecr/test/integ.basic.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecr/test/integ.basic.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecr/test/integ.basic.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecr/test/integ.basic.ts
  packages/aws-cdk-lib/aws-ecr/lib/repository.ts
  packages/aws-cdk-lib/aws-ecr/test/repository.test.ts
Labels: p2, pr/needs-review, contribution/core, pr-linter/exempt-readme

#25464 chore(prlinter): fixing some errors in the needs review workflow
  tools/@aws-cdk/prlint/lint.ts
  tools/@aws-cdk/prlint/test/lint.test.ts
Labels: p2, pr/needs-review, contribution/core

#23402 feat(logs): support DataProtectionPolicy in LogGroup construct
  packages/@aws-cdk-testing/framework-integ/test/aws-logs/test/integ.log-group.js.snapshot/LogGroupIntegDefaultTestDeployAssertA9999A13.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-logs/test/integ.log-group.js.snapshot/LogGroupIntegDefaultTestDeployAssertA9999A13.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-logs/test/integ.log-group.js.snapshot/aws-cdk-log-group-integ.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-logs/test/integ.log-group.js.snapshot/aws-cdk-log-group-integ.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-logs/test/integ.log-group.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-logs/test/integ.log-group.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-logs/test/integ.log-group.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-logs/test/integ.log-group.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-logs/test/integ.log-group.ts
  packages/aws-cdk-lib/aws-logs/README.md
  packages/aws-cdk-lib/aws-logs/lib/data-protection-policy.ts
  packages/aws-cdk-lib/aws-logs/lib/index.ts
  packages/aws-cdk-lib/aws-logs/lib/log-group.ts
  packages/aws-cdk-lib/aws-logs/test/loggroup.test.ts
Labels: p2, feature-request, pr/needs-review, effort/medium, beginning-contributor

#25460 fix(cfn2ts): doesn't handle property types with the same type as a primitive type
  tools/@aws-cdk/cfn2ts/lib/genspec.ts
  tools/@aws-cdk/cfn2ts/lib/spec-utils.ts
Labels: bug, p1, effort/small, pr/needs-review, contribution/core, pr-linter/exempt-test, pr-linter/exempt-integ-test

#25466 fix(batch): JobDefinition's ContainerDefinition's Image is synthesized with `[Object object]`
  docs/DESIGN_GUIDELINES.md
  packages/@aws-cdk/aws-batch-alpha/lib/ecs-container-definition.ts
  packages/@aws-cdk/aws-batch-alpha/test/ecs-container-definition.test.ts
  packages/@aws-cdk/aws-batch-alpha/test/integ.ecs-job-definition.js.snapshot/BatchEcsJobDefinitionTestDefaultTestDeployAssertE5BAAC9B.assets.json
  packages/@aws-cdk/aws-batch-alpha/test/integ.ecs-job-definition.js.snapshot/asset.8b518243ecbfcfd08b4734069e7e74ff97b7889dfde0a60d16e7bdc96e6c593b/Dockerfile
  packages/@aws-cdk/aws-batch-alpha/test/integ.ecs-job-definition.js.snapshot/asset.8b518243ecbfcfd08b4734069e7e74ff97b7889dfde0a60d16e7bdc96e6c593b/index.py
  packages/@aws-cdk/aws-batch-alpha/test/integ.ecs-job-definition.js.snapshot/cdk.out
  packages/@aws-cdk/aws-batch-alpha/test/integ.ecs-job-definition.js.snapshot/integ.json
  packages/@aws-cdk/aws-batch-alpha/test/integ.ecs-job-definition.js.snapshot/manifest.json
  packages/@aws-cdk/aws-batch-alpha/test/integ.ecs-job-definition.js.snapshot/stack.assets.json
  packages/@aws-cdk/aws-batch-alpha/test/integ.ecs-job-definition.js.snapshot/stack.template.json
  packages/@aws-cdk/aws-batch-alpha/test/integ.ecs-job-definition.js.snapshot/tree.json
  packages/@aws-cdk/aws-batch-alpha/test/integ.ecs-job-definition.ts
Labels: bug, p2, pr/needs-review, effort/medium, contribution/core

#25494 chore(cfnspec): fix the cfnspec update (#25320)
  buildspec-pr.yaml
  packages/@aws-cdk/cfnspec/build-tools/build.ts
  packages/@aws-cdk/cfnspec/build-tools/create-missing-libraries.ts
  packages/@aws-cdk/cfnspec/build-tools/massage-spec.ts
  packages/@aws-cdk/cfnspec/build-tools/spec-diff.ts
  packages/@aws-cdk/cfnspec/build-tools/update.sh
  packages/@aws-cdk/cfnspec/build-tools/validate-evolution.ts
  packages/@aws-cdk/cfnspec/package.json
  packages/@aws-cdk/cfnspec/skip-evolution-check.txt
  packages/@aws-cdk/cfnspec/spec-source/specification/000_cfn/560_Macie_FindingsFilter_Attributes_FindingsFilterListItems_patch.json
  packages/@aws-cdk/cfnspec/spec-source/specification/000_cfn/910_ApiGatewayV2_Route_patch.json
  packages/@aws-cdk/cfnspec/spec-source/specification/000_cfn/912_Macie_FindingsFilter_patch.json
Labels: p2, contribution/core

#25482 chore(eks): test app should only exist in framework-integ
  .github/workflows/yarn-upgrade.yml
  packages/aws-cdk-lib/aws-eks/test/sdk-call-integ-test-docker-app/app/.dockerignore
  packages/aws-cdk-lib/aws-eks/test/sdk-call-integ-test-docker-app/app/Dockerfile
  packages/aws-cdk-lib/aws-eks/test/sdk-call-integ-test-docker-app/app/package-lock.json
Labels: p2, pr/needs-review, contribution/core

#25484 docs(iam): explain service principal behavior with feature flag
  packages/aws-cdk-lib/aws-iam/lib/principals.ts
Labels: p2, pr/needs-review, contribution/core

#25505 chore(custom-resources): fix broken links
  packages/aws-cdk-lib/custom-resources/README.md
Labels: p2, pr/needs-review, beginning-contributor

#25488 chore(eks): update README with consistent versions
  packages/aws-cdk-lib/aws-eks/README.md
Labels: p2, pr/needs-review, contribution/core

#25506 chore(prlint): remove needs-review label on approved prs
  tools/@aws-cdk/prlint/lint.ts
  tools/@aws-cdk/prlint/test/lint.test.ts
Labels: p2, pr/needs-review, contribution/core

#25514 chore: npm-check-updates && yarn upgrade
  package.json
  packages/@aws-cdk-testing/cli-integ/package.json
  packages/@aws-cdk-testing/framework-integ/package.json
  packages/@aws-cdk-testing/framework-integ/test/aws-eks/test/sdk-call-integ-test-docker-app/app/package.json
  packages/@aws-cdk/aws-amplify-alpha/package.json
  packages/@aws-cdk/aws-redshift-alpha/package.json
  packages/@aws-cdk/aws-sagemaker-alpha/package.json
  packages/@aws-cdk/cloud-assembly-schema/package.json
  packages/@aws-cdk/cx-api/package.json
  packages/@aws-cdk/integ-runner/THIRD_PARTY_LICENSES
  packages/@aws-cdk/integ-tests-alpha/package.json
  packages/aws-cdk-lib/aws-backupgateway/.jsiirc.json
  packages/aws-cdk-lib/aws-backupgateway/index.ts
  packages/aws-cdk-lib/aws-proton/.jsiirc.json
  packages/aws-cdk-lib/aws-proton/index.ts
  packages/aws-cdk-lib/index.ts
  packages/aws-cdk-lib/package.json
  packages/aws-cdk-lib/scripts/scope-map.json
  packages/aws-cdk/THIRD_PARTY_LICENSES
  packages/aws-cdk/lib/init-templates/app/typescript/package.json
  packages/aws-cdk/lib/init-templates/lib/typescript/package.json
  packages/aws-cdk/lib/init-templates/sample-app/typescript/package.json
  packages/aws-cdk/package.json
  packages/cdk-assets/package.json
  tools/@aws-cdk/cdk-build-tools/package.json
  tools/@aws-cdk/node-bundle/package.json
  tools/@aws-cdk/pkglint/package.json
  tools/@aws-cdk/yarn-cling/package.json
  yarn.lock
Labels: p2, pr/needs-review, dependencies, contribution/core, auto-approve

#25521 chore(merge-back): 2.79.0
  CHANGELOG.v2.alpha.md
  CHANGELOG.v2.md
  version.v2.json
Labels: p2, pr/needs-review, pr/no-squash, auto-approve

#25523 chore: added khushail to ignore-usernames in github-merit-badger
  .github/workflows/github-merit-badger.yml
Labels: p2, beginning-contributor

#25527 chore(merge-back): 1.201.0
  CHANGELOG.md
  build.sh
  buildspec-pr.yaml
  version.v1.json
Labels: p2, pr/no-squash, auto-approve

#25540 fix(bootstrap): bootstrap doesn't work in non-aws partitions anymore (revert security hub finding fix)
  packages/aws-cdk/lib/api/bootstrap/bootstrap-template.yaml
Labels: bug, p0, effort/small, contribution/core, pr-linter/exempt-test, pr-linter/exempt-integ-test

#25542 chore(release): 2.79.1
  CHANGELOG.v2.alpha.md
  CHANGELOG.v2.md
  packages/aws-cdk/lib/api/bootstrap/bootstrap-template.yaml
  version.v2.json
Labels: p2, contribution/core, pr/no-squash

#25229 feat(appmesh): access log format support for app mesh
  packages/@aws-cdk-testing/framework-integ/test/aws-appmesh/test/integ.mesh.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-appmesh/test/integ.mesh.js.snapshot/mesh-stack.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-appmesh/test/integ.mesh.js.snapshot/mesh-stack.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-appmesh/test/integ.mesh.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-appmesh/test/integ.mesh.ts
  packages/aws-cdk-lib/aws-appmesh/README.md
  packages/aws-cdk-lib/aws-appmesh/lib/shared-interfaces.ts
  packages/aws-cdk-lib/aws-appmesh/test/virtual-gateway.test.ts
  packages/aws-cdk-lib/aws-appmesh/test/virtual-node.test.ts
Labels: p2, pr/needs-review, @aws-cdk/aws-appmesh, beginning-contributor

#25539 chore(github): notice issue template
  .github/ISSUE_TEMPLATE/notice.yml
Labels: p2, contribution/core

#25541 chore(secretsmanager): update doc with correct examples
  packages/aws-cdk-lib/aws-rds/README.md
  packages/aws-cdk-lib/aws-secretsmanager/README.md
Labels: bug, p2, effort/small, contribution/core

#25543 chore(aws-cdk-lib): refactor submodule gen
  packages/@aws-cdk/cfnspec/build-tools/build.ts
  packages/@aws-cdk/cfnspec/build-tools/patch-set.ts
  packages/aws-cdk-lib/aws-backupgateway/README.md
  packages/aws-cdk-lib/aws-events-targets/build-tools/gen.js
  packages/aws-cdk-lib/aws-proton/README.md
  packages/aws-cdk-lib/index.ts
  packages/aws-cdk-lib/lazy-index.ts
  packages/aws-cdk-lib/package.json
  packages/aws-cdk-lib/scripts/gen.ts
  packages/aws-cdk-lib/scripts/scope-map.json
  packages/aws-cdk-lib/scripts/submodules/aws-events-targets.ts
  packages/aws-cdk-lib/scripts/submodules/cloudformation-include.ts
  packages/aws-cdk-lib/scripts/submodules/index.ts
  scripts/bump-cfnspec.sh
  tools/@aws-cdk/cfn2ts/lib/index.ts
Labels: p2, contribution/core

#25549 chore(merge-back): 2.79.1
  CHANGELOG.v2.alpha.md
  CHANGELOG.v2.md
  version.v2.json
Labels: p2, pr/needs-review, pr/no-squash, auto-approve

#25548 chore(core): fix typo in assets.ts
  packages/aws-cdk-lib/core/lib/assets.ts
Labels: p2, contribution/core

#25564 chore(cfnspec): fix cfnspec upgrade job
  packages/@aws-cdk/cfnspec/build-tools/build.ts
  packages/@aws-cdk/cfnspec/build-tools/create-missing-libraries.ts
  packages/@aws-cdk/cfnspec/build-tools/patch-set.ts
  packages/@aws-cdk/cfnspec/build-tools/update.sh
Labels: p2, contribution/core

#25597 chore: do not print the contents of `dist/`
  pack.sh
Labels: p2, contribution/core

#25579 docs(route53): add more detailed documentation to cname domain name property
  packages/aws-cdk-lib/aws-route53/lib/record-set.ts
Labels: p2, effort/small, star-contributor

#25566 chore(msk): deprecate kafka version 1.1.1
  packages/@aws-cdk/aws-msk-alpha/lib/cluster-version.ts
Labels: bug, p2, effort/small, star-contributor

#25330 feat(eks): alb controller include versions 2.4.2 - 2.5.1
  packages/@aws-cdk-testing/framework-integ/test/aws-eks/test/integ.alb-controller.js.snapshot/aws-cdk-eks-cluster-alb-controller-test.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-eks/test/integ.alb-controller.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-eks/test/integ.alb-controller.ts
  packages/@aws-cdk-testing/framework-integ/test/aws-eks/test/integ.eks-inference.js.snapshot/aws-cdk-eks-cluster-inference-test.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-eks/test/integ.eks-inference.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-eks/test/integ.eks-inference.ts
  packages/aws-cdk-lib/aws-eks/README.md
  packages/aws-cdk-lib/aws-eks/lib/addons/alb-iam_policy-v2.4.2.json
  packages/aws-cdk-lib/aws-eks/lib/addons/alb-iam_policy-v2.4.3.json
  packages/aws-cdk-lib/aws-eks/lib/addons/alb-iam_policy-v2.4.4.json
  packages/aws-cdk-lib/aws-eks/lib/addons/alb-iam_policy-v2.4.5.json
  packages/aws-cdk-lib/aws-eks/lib/addons/alb-iam_policy-v2.4.6.json
  packages/aws-cdk-lib/aws-eks/lib/addons/alb-iam_policy-v2.4.7.json
  packages/aws-cdk-lib/aws-eks/lib/addons/alb-iam_policy-v2.5.0.json
  packages/aws-cdk-lib/aws-eks/lib/addons/alb-iam_policy-v2.5.1.json
  packages/aws-cdk-lib/aws-eks/lib/alb-controller.ts
  packages/aws-cdk-lib/aws-eks/test/alb-controller.test.ts
Labels: p2, feature-request, effort/small, contribution/core

#25602 docs(assertions): update link to migration guide
  packages/aws-cdk-lib/assertions/README.md
Labels: p2, pr/needs-review, contribution/core

#25599 chore(synthetics): deprecate nodejs runtime versions 1 and 2
  packages/@aws-cdk/aws-synthetics-alpha/lib/runtime.ts
Labels: p2, contribution/core

#25613 chore: npm-check-updates && yarn upgrade
  package.json
  packages/@aws-cdk-testing/cli-integ/package.json
  packages/@aws-cdk-testing/framework-integ/package.json
  packages/@aws-cdk-testing/framework-integ/test/aws-eks/test/sdk-call-integ-test-docker-app/app/package.json
  packages/@aws-cdk/aws-amplify-alpha/package.json
  packages/@aws-cdk/aws-redshift-alpha/package.json
  packages/@aws-cdk/aws-sagemaker-alpha/package.json
  packages/@aws-cdk/cloud-assembly-schema/package.json
  packages/@aws-cdk/cx-api/package.json
  packages/@aws-cdk/integ-runner/THIRD_PARTY_LICENSES
  packages/@aws-cdk/integ-tests-alpha/package.json
  packages/aws-cdk-lib/package.json
  packages/aws-cdk/THIRD_PARTY_LICENSES
  packages/aws-cdk/lib/init-templates/app/typescript/package.json
  packages/aws-cdk/lib/init-templates/lib/typescript/package.json
  packages/aws-cdk/lib/init-templates/sample-app/typescript/package.json
  packages/aws-cdk/package.json
  packages/awslint/package.json
  packages/cdk-assets/package.json
  tools/@aws-cdk/cdk-build-tools/package.json
  tools/@aws-cdk/cdk-release/package.json
  tools/@aws-cdk/cfn2ts/package.json
  tools/@aws-cdk/node-bundle/package.json
  tools/@aws-cdk/pkglint/package.json
  tools/@aws-cdk/yarn-cling/package.json
  yarn.lock
Labels: p2, pr/needs-review, dependencies, contribution/core, auto-approve

#25557 feat(msk): Kafka version 3.4.0
  packages/@aws-cdk/aws-msk-alpha/lib/cluster-version.ts
  packages/@aws-cdk/aws-msk-alpha/test/cluster.test.ts
  packages/@aws-cdk/aws-msk-alpha/test/integ.cluster-version.js.snapshot/KafkaVersionIntegTestDefaultTestDeployAssertD6628743.assets.json
  packages/@aws-cdk/aws-msk-alpha/test/integ.cluster-version.js.snapshot/KafkaVersionIntegTestDefaultTestDeployAssertD6628743.template.json
  packages/@aws-cdk/aws-msk-alpha/test/integ.cluster-version.js.snapshot/KafkaVersionTestStack.assets.json
  packages/@aws-cdk/aws-msk-alpha/test/integ.cluster-version.js.snapshot/KafkaVersionTestStack.template.json
  packages/@aws-cdk/aws-msk-alpha/test/integ.cluster-version.js.snapshot/cdk.out
  packages/@aws-cdk/aws-msk-alpha/test/integ.cluster-version.js.snapshot/integ.json
  packages/@aws-cdk/aws-msk-alpha/test/integ.cluster-version.js.snapshot/manifest.json
  packages/@aws-cdk/aws-msk-alpha/test/integ.cluster-version.js.snapshot/tree.json
  packages/@aws-cdk/aws-msk-alpha/test/integ.cluster-version.ts
Labels: p2, feature-request, effort/small, pr-linter/exempt-readme, star-contributor

#25618 docs(assertions): add more detail about migrating from the old assert library
  packages/aws-cdk-lib/assertions/README.md
Labels: p2, pr/needs-review, contribution/core

#25631 chore: npm-check-updates && yarn upgrade
  package.json
  packages/@aws-cdk-testing/cli-integ/package.json
  packages/@aws-cdk-testing/framework-integ/package.json
  packages/@aws-cdk-testing/framework-integ/test/aws-eks/test/sdk-call-integ-test-docker-app/app/package.json
  packages/@aws-cdk/aws-amplify-alpha/package.json
  packages/@aws-cdk/aws-redshift-alpha/package.json
  packages/@aws-cdk/aws-sagemaker-alpha/package.json
  packages/@aws-cdk/integ-runner/THIRD_PARTY_LICENSES
  packages/@aws-cdk/integ-tests-alpha/package.json
  packages/aws-cdk-lib/package.json
  packages/aws-cdk/THIRD_PARTY_LICENSES
  packages/aws-cdk/lib/init-templates/app/typescript/package.json
  packages/aws-cdk/lib/init-templates/lib/typescript/package.json
  packages/aws-cdk/lib/init-templates/sample-app/typescript/package.json
  packages/aws-cdk/package.json
  packages/cdk-assets/package.json
  tools/@aws-cdk/node-bundle/package.json
  yarn.lock
Labels: p2, pr/needs-review, dependencies, contribution/core, auto-approve

#25422 feat(scheduler): schedule expression construct
  packages/@aws-cdk/aws-scheduler-alpha/.eslintrc.js
  packages/@aws-cdk/aws-scheduler-alpha/.gitignore
  packages/@aws-cdk/aws-scheduler-alpha/.npmignore
  packages/@aws-cdk/aws-scheduler-alpha/LICENSE
  packages/@aws-cdk/aws-scheduler-alpha/NOTICE
  packages/@aws-cdk/aws-scheduler-alpha/README.md
  packages/@aws-cdk/aws-scheduler-alpha/jest.config.js
  packages/@aws-cdk/aws-scheduler-alpha/lib/index.ts
  packages/@aws-cdk/aws-scheduler-alpha/lib/schedule-expression.ts
  packages/@aws-cdk/aws-scheduler-alpha/package.json
  packages/@aws-cdk/aws-scheduler-alpha/rosetta/default.ts-fixture
  packages/@aws-cdk/aws-scheduler-alpha/test/schedule-expression.test.ts
  packages/@aws-cdk/aws-scheduler-alpha/tsconfig.dev.json
Labels: p2, pr-linter/exempt-integ-test, beginning-contributor

#25581 docs(ssm): explain that SecretValue.ssmSecure() lives in core now
  packages/aws-cdk-lib/aws-ssm/lib/parameter.ts
Labels: p1, feature-request, effort/small, beginning-contributor

#24536 feat(codepipeline-actions): add KMSEncryptionKeyARN for S3DeployAction
  packages/@aws-cdk-testing/framework-integ/test/aws-codepipeline-actions/test/integ.pipeline-s3-deploy.js.snapshot/aws-cdk-codepipeline-s3-deploy.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-codepipeline-actions/test/integ.pipeline-s3-deploy.js.snapshot/aws-cdk-codepipeline-s3-deploy.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-codepipeline-actions/test/integ.pipeline-s3-deploy.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-codepipeline-actions/test/integ.pipeline-s3-deploy.js.snapshot/s3deploytestDefaultTestDeployAssert6BC61647.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-codepipeline-actions/test/integ.pipeline-s3-deploy.js.snapshot/s3deploytestDefaultTestDeployAssert6BC61647.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-codepipeline-actions/test/integ.pipeline-s3-deploy.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-codepipeline-actions/test/integ.pipeline-s3-deploy.ts
  packages/aws-cdk-lib/aws-codepipeline-actions/README.md
  packages/aws-cdk-lib/aws-codepipeline-actions/lib/s3/deploy-action.ts
  packages/aws-cdk-lib/aws-codepipeline-actions/test/s3/s3-deploy-action.test.ts
Labels: p2, feature-request, pr-linter/exempt-integ-test, beginning-contributor, pr-linter/exemption-requested, pr/reviewer-clarification-requested

#25644 feat(cli): logging can be corked
  packages/aws-cdk/lib/cdk-toolkit.ts
  packages/aws-cdk/lib/logging.ts
  packages/cdk-assets/lib/publishing.ts
  packages/cdk-assets/test/docker-images.test.ts
Labels: p2, contribution/core, pr-linter/exempt-readme, pr-linter/exempt-test, pr-linter/exempt-integ-test, pr-linter/cli-integ-tested

#25630 feat(apigateway): add grantExecute to API Methods
  packages/@aws-cdk-testing/framework-integ/test/aws-apigateway/test/integ.method-grant-execute.js.snapshot/GrantExecute.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-apigateway/test/integ.method-grant-execute.js.snapshot/GrantExecute.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-apigateway/test/integ.method-grant-execute.js.snapshot/GrantExecuteTestDefaultTestDeployAssertA66B6F20.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-apigateway/test/integ.method-grant-execute.js.snapshot/GrantExecuteTestDefaultTestDeployAssertA66B6F20.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-apigateway/test/integ.method-grant-execute.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-apigateway/test/integ.method-grant-execute.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-apigateway/test/integ.method-grant-execute.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-apigateway/test/integ.method-grant-execute.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-apigateway/test/integ.method-grant-execute.ts
  packages/aws-cdk-lib/aws-apigateway/README.md
  packages/aws-cdk-lib/aws-apigateway/lib/method.ts
  packages/aws-cdk-lib/aws-apigateway/test/method.test.ts
Labels: p1, feature-request, pr/needs-review, effort/medium, contribution/core

#25654 chore(release): 2.80.0
  CHANGELOG.v2.md
  packages/@aws-cdk-testing/framework-integ/test/aws-apigateway/test/integ.method-grant-execute.js.snapshot/GrantExecute.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-apigateway/test/integ.method-grant-execute.js.snapshot/GrantExecute.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-apigateway/test/integ.method-grant-execute.js.snapshot/GrantExecuteTestDefaultTestDeployAssertA66B6F20.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-apigateway/test/integ.method-grant-execute.js.snapshot/GrantExecuteTestDefaultTestDeployAssertA66B6F20.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-apigateway/test/integ.method-grant-execute.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-apigateway/test/integ.method-grant-execute.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-apigateway/test/integ.method-grant-execute.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-apigateway/test/integ.method-grant-execute.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-apigateway/test/integ.method-grant-execute.ts
  packages/aws-cdk-lib/aws-apigateway/README.md
  packages/aws-cdk-lib/aws-apigateway/lib/method.ts
  packages/aws-cdk-lib/aws-apigateway/test/method.test.ts
Labels: p2, pr/needs-review, pr/no-squash, auto-approve

#24430 feat: new synthesizer separates assets out per CDK application
  packages/@aws-cdk/app-staging-synthesizer-alpha/.eslintrc.js
  packages/@aws-cdk/app-staging-synthesizer-alpha/.gitignore
  packages/@aws-cdk/app-staging-synthesizer-alpha/.npmignore
  packages/@aws-cdk/app-staging-synthesizer-alpha/LICENSE
  packages/@aws-cdk/app-staging-synthesizer-alpha/NOTICE
  packages/@aws-cdk/app-staging-synthesizer-alpha/README.md
  packages/@aws-cdk/app-staging-synthesizer-alpha/adr/resource-names.md
  packages/@aws-cdk/app-staging-synthesizer-alpha/jest.config.js
  packages/@aws-cdk/app-staging-synthesizer-alpha/lib/app-staging-synthesizer.ts
  packages/@aws-cdk/app-staging-synthesizer-alpha/lib/bootstrap-roles.ts
  packages/@aws-cdk/app-staging-synthesizer-alpha/lib/default-staging-stack.ts
  packages/@aws-cdk/app-staging-synthesizer-alpha/lib/index.ts
  packages/@aws-cdk/app-staging-synthesizer-alpha/lib/per-env-staging-factory.ts
  packages/@aws-cdk/app-staging-synthesizer-alpha/lib/private/app-global.ts
  packages/@aws-cdk/app-staging-synthesizer-alpha/lib/private/no-tokens.ts
  packages/@aws-cdk/app-staging-synthesizer-alpha/lib/staging-stack.ts
  packages/@aws-cdk/app-staging-synthesizer-alpha/package.json
  packages/@aws-cdk/app-staging-synthesizer-alpha/rosetta/default.ts-fixture
  packages/@aws-cdk/app-staging-synthesizer-alpha/rosetta/with-custom-staging.ts-fixture
  packages/@aws-cdk/app-staging-synthesizer-alpha/test/app-staging-synthesizer.test.ts
  packages/@aws-cdk/app-staging-synthesizer-alpha/test/assets/Dockerfile
  packages/@aws-cdk/app-staging-synthesizer-alpha/test/assets/index.py
  packages/@aws-cdk/app-staging-synthesizer-alpha/test/bootstrap-roles.test.ts
  packages/@aws-cdk/app-staging-synthesizer-alpha/test/default-staging-stack.test.ts
  packages/@aws-cdk/app-staging-synthesizer-alpha/test/evaluate-cfn.ts
  packages/@aws-cdk/app-staging-synthesizer-alpha/test/integ.synth-default-resources.js.snapshot/StagingStack-default-resources-ACCOUNT-REGION.template.json
  packages/@aws-cdk/app-staging-synthesizer-alpha/test/integ.synth-default-resources.js.snapshot/asset.16624c2a162b07c5cc0e2c59c484f638bac238ca558ccbdc2aa0e0535df3e622/Dockerfile
  packages/@aws-cdk/app-staging-synthesizer-alpha/test/integ.synth-default-resources.js.snapshot/asset.16624c2a162b07c5cc0e2c59c484f638bac238ca558ccbdc2aa0e0535df3e622/index.py
  packages/@aws-cdk/app-staging-synthesizer-alpha/test/integ.synth-default-resources.js.snapshot/asset.68539effc3f7ad46fff9765606c2a01b7f7965833643ab37e62799f19a37f650/Dockerfile
  packages/@aws-cdk/app-staging-synthesizer-alpha/test/integ.synth-default-resources.js.snapshot/asset.68539effc3f7ad46fff9765606c2a01b7f7965833643ab37e62799f19a37f650/index.py
  packages/@aws-cdk/app-staging-synthesizer-alpha/test/integ.synth-default-resources.js.snapshot/cdk.out
  packages/@aws-cdk/app-staging-synthesizer-alpha/test/integ.synth-default-resources.js.snapshot/integ.json
  packages/@aws-cdk/app-staging-synthesizer-alpha/test/integ.synth-default-resources.js.snapshot/integtestsDefaultTestDeployAssert44C8D370.assets.json
  packages/@aws-cdk/app-staging-synthesizer-alpha/test/integ.synth-default-resources.js.snapshot/integtestsDefaultTestDeployAssert44C8D370.template.json
  packages/@aws-cdk/app-staging-synthesizer-alpha/test/integ.synth-default-resources.js.snapshot/manifest.json
  packages/@aws-cdk/app-staging-synthesizer-alpha/test/integ.synth-default-resources.js.snapshot/synthesize-default-resources.assets.json
  packages/@aws-cdk/app-staging-synthesizer-alpha/test/integ.synth-default-resources.js.snapshot/synthesize-default-resources.template.json
  packages/@aws-cdk/app-staging-synthesizer-alpha/test/integ.synth-default-resources.js.snapshot/tree.json
  packages/@aws-cdk/app-staging-synthesizer-alpha/test/integ.synth-default-resources.ts
  packages/@aws-cdk/app-staging-synthesizer-alpha/test/per-env-staging-factory.test.ts
  packages/@aws-cdk/app-staging-synthesizer-alpha/test/util.ts
  packages/aws-cdk-lib/aws-ecr-assets/lib/image-asset.ts
  packages/aws-cdk-lib/aws-s3-assets/lib/asset.ts
  packages/aws-cdk-lib/core/lib/assets.ts
  packages/aws-cdk-lib/core/lib/helpers-internal/index.ts
  packages/aws-cdk-lib/core/lib/helpers-internal/string-specializer.ts
  packages/aws-cdk-lib/core/lib/stack-synthesizers/_shared.ts
  packages/aws-cdk-lib/core/lib/stack-synthesizers/asset-manifest-builder.ts
  packages/aws-cdk-lib/core/lib/stack-synthesizers/bootstrapless-synthesizer.ts
  packages/aws-cdk-lib/core/lib/stack-synthesizers/cli-credentials-synthesizer.ts
  packages/aws-cdk-lib/core/lib/stack-synthesizers/default-synthesizer.ts
  packages/aws-cdk-lib/core/lib/stack-synthesizers/stack-synthesizer.ts
  packages/aws-cdk-lib/core/lib/stack.ts
  packages/aws-cdk-lib/core/test/helpers-internal/string-specializer.test.ts
  packages/aws-cdk/lib/api/aws-auth/sdk-provider.ts
  packages/aws-cdk/lib/util/asset-publishing.ts
  packages/cdk-assets/lib/aws.ts
  packages/cdk-assets/lib/private/handlers/container-images.ts
  packages/cdk-assets/lib/private/handlers/files.ts
Labels: p2, contribution/core, pr-linter/cli-integ-tested

#25659 chore(merge-back): 2.80.0
  CHANGELOG.v2.alpha.md
  CHANGELOG.v2.md
  version.v2.json
Labels: p2, pr/needs-review, pr/no-squash, auto-approve

#25426 chore: update nodejs to 18 in gitpod
  .gitpod.yml
Labels: p2, pr/needs-review, star-contributor

#25619 chore(batch-alpha): make batch dev-preview
  packages/@aws-cdk/aws-batch-alpha/README.md
  packages/@aws-cdk/aws-batch-alpha/package.json
Labels: p2, contribution/core

#25673 chore(merge-back): 1.202.0
  CHANGELOG.md
  version.v1.json
Labels: p2, pr/no-squash, auto-approve

#25089 chore(cdk): Speed up typescript app compile time
  packages/aws-cdk/README.md
Labels: p2, beginning-contributor

#24920 fix(core): allow override with cross-stack references
  packages/aws-cdk-lib/core/lib/cfn-resource.ts
  packages/aws-cdk-lib/core/lib/resolvable.ts
  packages/aws-cdk-lib/core/lib/util.ts
  packages/aws-cdk-lib/core/test/resource.test.ts
  packages/aws-cdk-lib/core/test/stack.test.ts
Labels: bug, p1, pr-linter/exempt-integ-test, admired-contributor, pr-linter/exemption-requested, pr/reviewer-clarification-requested

#25695 chore(aws-cdk-lib): fix new submodule gen only works when relative paths are provided
  packages/aws-cdk-lib/scripts/submodules/index.ts
Labels: p2, pr/needs-review, contribution/core

#25694 chore(ec2): add AppSync endpoint constant
  packages/aws-cdk-lib/aws-ec2/lib/vpc-endpoint.ts
Labels: p2, beginning-contributor

#25441 feat(ec2): added support for network interfaces on ec2 instances by providing an associatePublicIpAddress property
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.instance-public.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.instance-public.js.snapshot/instancetestDefaultTestDeployAssert5516EAF1.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.instance-public.js.snapshot/instancetestDefaultTestDeployAssert5516EAF1.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.instance-public.js.snapshot/integ-ec2-instance.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.instance-public.js.snapshot/integ-ec2-instance.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.instance-public.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.instance-public.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.instance-public.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.instance-public.ts
  packages/aws-cdk-lib/aws-ec2/README.md
  packages/aws-cdk-lib/aws-ec2/lib/instance.ts
  packages/aws-cdk-lib/aws-ec2/test/instance.test.ts
Labels: p2, feature-request, @aws-cdk/aws-ec2, effort/small, contribution/core

#25575 chore(eks): deprecate k8s 1.21 and 1.22
  packages/aws-cdk-lib/aws-eks/README.md
  packages/aws-cdk-lib/aws-eks/lib/cluster.ts
Labels: p2, pr/needs-review, distinguished-contributor

#25706 chore: update cloud assembly schema version
  packages/aws-cdk-lib/cloud-assembly-schema/schema/cloud-assembly.version.json
Labels: p2, pr/needs-review, contribution/core

#25707 docs(app-staging-synthesizer): document known limitations
  packages/@aws-cdk/app-staging-synthesizer-alpha/README.md
Labels: p2, contribution/core

#25637 feat(glue): Add G.4X and G.8X worker types for AWS Glue
  packages/@aws-cdk/aws-glue-alpha/README.md
  packages/@aws-cdk/aws-glue-alpha/lib/job.ts
  packages/@aws-cdk/aws-glue-alpha/test/integ.job.js.snapshot/aws-glue-job.template.json
  packages/@aws-cdk/aws-glue-alpha/test/integ.job.js.snapshot/tree.json
  packages/@aws-cdk/aws-glue-alpha/test/integ.job.ts
  packages/@aws-cdk/aws-glue-alpha/test/job.test.ts
Labels: p2, beginning-contributor

#25472 chore(region-info): ap-southeast-3 (Jakarta) EBS_ENV_ENDPOINT_HOSTED_ZONE_ID
  packages/aws-cdk-lib/region-info/build-tools/fact-tables.ts
Labels: p2, admired-contributor

#25350 fix(s3): KMS encryption works fine for server access logging target buckets
  packages/@aws-cdk-testing/framework-integ/test/aws-s3/test/integ.bucket-server-access-logs-sse-kms.js.snapshot/ServerAccessLogsSseKmsTestDefaultTestDeployAssertB937C102.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-s3/test/integ.bucket-server-access-logs-sse-kms.js.snapshot/ServerAccessLogsSseKmsTestDefaultTestDeployAssertB937C102.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-s3/test/integ.bucket-server-access-logs-sse-kms.js.snapshot/aws-cdk-s3-server-access-logs-sse-kms.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-s3/test/integ.bucket-server-access-logs-sse-kms.js.snapshot/aws-cdk-s3-server-access-logs-sse-kms.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-s3/test/integ.bucket-server-access-logs-sse-kms.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-s3/test/integ.bucket-server-access-logs-sse-kms.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-s3/test/integ.bucket-server-access-logs-sse-kms.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-s3/test/integ.bucket-server-access-logs-sse-kms.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-s3/test/integ.bucket-server-access-logs-sse-kms.ts
  packages/aws-cdk-lib/aws-s3/lib/bucket.ts
  packages/aws-cdk-lib/aws-s3/test/bucket.test.ts
Labels: p2, beginning-contributor, pr-linter/exemption-requested

#25643 feat(batch-alpha): tag instances launched from your managed CEs
  packages/@aws-cdk/aws-batch-alpha/README.md
  packages/@aws-cdk/aws-batch-alpha/lib/managed-compute-environment.ts
  packages/@aws-cdk/aws-batch-alpha/test/integ.managed-compute-environment.js.snapshot/batch-stack.assets.json
  packages/@aws-cdk/aws-batch-alpha/test/integ.managed-compute-environment.js.snapshot/batch-stack.template.json
  packages/@aws-cdk/aws-batch-alpha/test/integ.managed-compute-environment.js.snapshot/manifest.json
  packages/@aws-cdk/aws-batch-alpha/test/integ.managed-compute-environment.js.snapshot/tree.json
  packages/@aws-cdk/aws-batch-alpha/test/integ.managed-compute-environment.ts
  packages/@aws-cdk/aws-batch-alpha/test/managed-compute-environment.test.ts
Labels: p2, @aws-cdk/aws-batch, contribution/core

#25721 chore: remove redundant pack prequisite check
  scripts/check-pack-prerequisites.sh
Labels: p2, contribution/core

#25727 chore: check for javac >= 16
  scripts/check-pack-prerequisites.sh
Labels: p2, contribution/core

#25495 fix(lambda): validation for FunctionUrlCorsOptions.maxAge
  packages/aws-cdk-lib/aws-lambda/lib/function-url.ts
  packages/aws-cdk-lib/aws-lambda/test/function-url.test.ts
Labels: p2, pr-linter/exempt-integ-test, valued-contributor, pr-linter/exemption-requested

#25477 feat(s3-deployment): add some convenient methods to `CacheControl`
  packages/aws-cdk-lib/aws-s3-deployment/README.md
  packages/aws-cdk-lib/aws-s3-deployment/lib/bucket-deployment.ts
  packages/aws-cdk-lib/aws-s3-deployment/test/bucket-deployment.test.ts
Labels: p2, pr/needs-review, pr-linter/exempt-integ-test, valued-contributor, pr-linter/exemption-requested

#25610 chore(core): `ITaggableV2` is safe to implement for L1s
  packages/aws-cdk-lib/core/lib/cfn-resource.ts
  packages/aws-cdk-lib/core/lib/tag-aspect.ts
  packages/aws-cdk-lib/core/lib/tag-manager.ts
  packages/aws-cdk-lib/core/test/tag-aspect.test.ts
  packages/aws-cdk-lib/core/test/tag-manager.test.ts
  tools/@aws-cdk/cfn2ts/lib/codegen.ts
  tools/@aws-cdk/cfn2ts/lib/index.ts
Labels: p2, contribution/core

#25739 chore: bump jsii-pacmak (and related) to 1.82.0
  package.json
  tools/@aws-cdk/cdk-build-tools/package.json
  yarn.lock
Labels: p2, contribution/core

#25397 chore(doc): add Windows description in contributing guide
  CONTRIBUTING.md
Labels: bug, p2, docs/repo-general, contribution/core

#25743 chore(merge-back): 2.81.0
  CHANGELOG.v2.alpha.md
  CHANGELOG.v2.md
  version.v2.json
Labels: p2, pr/needs-review, pr/no-squash, auto-approve

#25744 chore(iam): support addSourceAccountCondition and addSourceArnCondition
  packages/aws-cdk-lib/aws-iam/README.md
  packages/aws-cdk-lib/aws-iam/lib/policy-statement.ts
  packages/aws-cdk-lib/aws-iam/test/policy-document.test.ts
Labels: p2, effort/medium, contribution/core

#25433 chore: switch convenience package `cdk` to stable
  packages/cdk/.eslintrc.js
  packages/cdk/.gitignore
  packages/cdk/.npmignore
  packages/cdk/README.md
  packages/cdk/package.json
Labels: p2, pr/needs-review, contribution/core

#25468 fix(ec2): non-agnostic stack throws error with availability zones defined in VPC
  packages/aws-cdk-lib/aws-ec2/lib/vpc.ts
  packages/aws-cdk-lib/aws-ec2/test/vpc.test.ts
Labels: bug, p1, effort/small, contribution/core, pr-linter/exempt-integ-test, pr-linter/exemption-requested

#25646 feat(stepfunctions): add getters for context object fields
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/lambda/integ.invoke.js.snapshot/IntegTestDefaultTestDeployAssertE3E7D2A4.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/lambda/integ.invoke.js.snapshot/IntegTestDefaultTestDeployAssertE3E7D2A4.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/lambda/integ.invoke.js.snapshot/asset.ae370e1010629b78f494346f49ceef3ab2875718f20e6c808114e6aa770c7bf3.bundle/index.js
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/lambda/integ.invoke.js.snapshot/aws-stepfunctions-tasks-lambda-invoke-integ.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/lambda/integ.invoke.js.snapshot/aws-stepfunctions-tasks-lambda-invoke-integ.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/lambda/integ.invoke.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/lambda/integ.invoke.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/lambda/integ.invoke.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/lambda/integ.invoke.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/lambda/integ.invoke.ts
  packages/aws-cdk-lib/aws-stepfunctions-tasks/test/lambda/run-lambda-task.test.ts
  packages/aws-cdk-lib/aws-stepfunctions/README.md
  packages/aws-cdk-lib/aws-stepfunctions/lib/fields.ts
  packages/aws-cdk-lib/aws-stepfunctions/test/fields.test.ts
Labels: p2, feature-request, effort/small, contribution/core, pr/needs-cli-test-run

#25772 chore(rds): upgrade rds(PostgreSQL) version
  packages/aws-cdk-lib/aws-rds/lib/instance-engine.ts
Labels: p2, pr/needs-review, star-contributor

#25379 feat(route53): HostedZone's default period at the end should be optional
  packages/@aws-cdk-testing/framework-integ/test/aws-route53/test/integ.route53.js.snapshot/aws-cdk-route53-integ.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-route53/test/integ.route53.js.snapshot/aws-cdk-route53-integ.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-route53/test/integ.route53.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-route53/test/integ.route53.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-route53/test/integ.route53.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-route53/test/integ.route53.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-route53/test/integ.route53.ts
  packages/aws-cdk-lib/aws-route53/README.md
  packages/aws-cdk-lib/aws-route53/lib/hosted-zone.ts
  packages/aws-cdk-lib/aws-route53/lib/util.ts
  packages/aws-cdk-lib/aws-route53/test/hosted-zone.test.ts
  packages/aws-cdk-lib/aws-route53/test/route53.test.ts
  packages/aws-cdk-lib/aws-route53/test/util.test.ts
Labels: bug, p2, @aws-cdk/aws-route53, effort/small, pr/needs-review, star-contributor

#25778 fix(aws-cdk-lib): attribute `FindingsFilterListItems` on AWS::Macie::FindingsFilter does not work
  packages/@aws-cdk/cfnspec/skip-evolution-check.txt
  packages/@aws-cdk/cfnspec/spec-source/specification/000_cfn/912_Macie_FindingsFilter_patch.json
Labels: p2, pr/needs-review, contribution/core, pr-linter/exempt-test, pr-linter/exempt-integ-test

#25622 docs(sqs): updated doc for grantSendMessage and grantConsumeMessage
  packages/aws-cdk-lib/aws-sqs/lib/queue-base.ts
Labels: bug, p1, beginning-contributor

#25779 chore: prlinter should use HEAD instead of base commit
  tools/@aws-cdk/prlint/index.ts
  tools/@aws-cdk/prlint/lint.ts
Labels: p2, pr/needs-review, contribution/core

#25781 chore: release app-staging-synthesizer-alpha
  packages/@aws-cdk/app-staging-synthesizer-alpha/.npmignore
  packages/@aws-cdk/app-staging-synthesizer-alpha/package.json
Labels: p2, contribution/core

#25553 feat(synthetics): support runtime nodejs puppeteer 4.0
  packages/@aws-cdk/aws-synthetics-alpha/README.md
  packages/@aws-cdk/aws-synthetics-alpha/lib/runtime.ts
  packages/@aws-cdk/aws-synthetics-alpha/package.json
  packages/@aws-cdk/aws-synthetics-alpha/test/canaries/nodejs/node_modules/canary.js
  packages/@aws-cdk/aws-synthetics-alpha/test/canaries/python/canary.py
  packages/@aws-cdk/aws-synthetics-alpha/test/integ.canary.js.snapshot/IntegCanaryTestDefaultTestDeployAssert3AD5A094.assets.json
  packages/@aws-cdk/aws-synthetics-alpha/test/integ.canary.js.snapshot/IntegCanaryTestDefaultTestDeployAssert3AD5A094.template.json
  packages/@aws-cdk/aws-synthetics-alpha/test/integ.canary.js.snapshot/asset.36618132bd37b6b15f9987b57ad1fbf613f1ad937aec72381232b163ed9c44c4.bundle/index.js
  packages/@aws-cdk/aws-synthetics-alpha/test/integ.canary.js.snapshot/asset.40aa87cdf43c4095cec18bc443965f22ab2f8c1ace47e482a0ba4e35d83b0cc9/__entrypoint__.js
  packages/@aws-cdk/aws-synthetics-alpha/test/integ.canary.js.snapshot/asset.40aa87cdf43c4095cec18bc443965f22ab2f8c1ace47e482a0ba4e35d83b0cc9/index.js
  packages/@aws-cdk/aws-synthetics-alpha/test/integ.canary.js.snapshot/asset.c33f4b91df43c8c958548ed571d6d05b4e3a4fa56a7e43aa5ba849f3d96d1699/nodejs/node_modules/canary.js
  packages/@aws-cdk/aws-synthetics-alpha/test/integ.canary.js.snapshot/asset.c33f4b91df43c8c958548ed571d6d05b4e3a4fa56a7e43aa5ba849f3d96d1699/python/canary.py
  packages/@aws-cdk/aws-synthetics-alpha/test/integ.canary.js.snapshot/canary-one.assets.json
  packages/@aws-cdk/aws-synthetics-alpha/test/integ.canary.js.snapshot/canary-one.template.json
  packages/@aws-cdk/aws-synthetics-alpha/test/integ.canary.js.snapshot/cdk.out
  packages/@aws-cdk/aws-synthetics-alpha/test/integ.canary.js.snapshot/integ.json
  packages/@aws-cdk/aws-synthetics-alpha/test/integ.canary.js.snapshot/manifest.json
  packages/@aws-cdk/aws-synthetics-alpha/test/integ.canary.js.snapshot/tree.json
  packages/@aws-cdk/aws-synthetics-alpha/test/integ.canary.ts
Labels: p2, feature-request, effort/small, pr/needs-review, admired-contributor

#25375 feat(lambda): response payload streaming
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda/test/integ.function-url.js.snapshot/IntegTestDefaultTestDeployAssertE3E7D2A4.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda/test/integ.function-url.js.snapshot/IntegTestDefaultTestDeployAssertE3E7D2A4.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda/test/integ.function-url.js.snapshot/Stack1.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda/test/integ.function-url.js.snapshot/Stack1.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda/test/integ.function-url.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda/test/integ.function-url.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda/test/integ.function-url.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda/test/integ.function-url.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda/test/integ.function-url.ts
  packages/aws-cdk-lib/aws-lambda/README.md
  packages/aws-cdk-lib/aws-lambda/lib/function-url.ts
  packages/aws-cdk-lib/aws-lambda/test/function-url.test.ts
Labels: p2, @aws-cdk/aws-lambda, pr/needs-review, star-contributor

#25302 feat(ecr): validate repository arn in fromRepositoryArn
  packages/aws-cdk-lib/aws-ecr/lib/repository.ts
  packages/aws-cdk-lib/aws-ecr/test/repository.test.ts
  packages/aws-cdk-lib/aws-lambda/test/lambda-insights.test.ts
  packages/aws-cdk-lib/pipelines/test/docker-credentials.test.ts
Labels: p2, feature-request, effort/small, contribution/core, pr-linter/exempt-readme, pr-linter/exempt-integ-test

#25709 feat(core): support nodejs18.x for CustomResourceProviderRuntime.
  packages/@aws-cdk-testing/framework-integ/test/aws-cloudformation/test/integ.core-custom-resources-node-18.js.snapshot/asset.5a80abfca3e7d70957e8c0a553225876c69fb6038b810fe65b581b6b58453bf7/__entrypoint__.js
  packages/@aws-cdk-testing/framework-integ/test/aws-cloudformation/test/integ.core-custom-resources-node-18.js.snapshot/asset.5a80abfca3e7d70957e8c0a553225876c69fb6038b810fe65b581b6b58453bf7/index.js
  packages/@aws-cdk-testing/framework-integ/test/aws-cloudformation/test/integ.core-custom-resources-node-18.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-cloudformation/test/integ.core-custom-resources-node-18.js.snapshot/custom-resource-test-node-18-stack.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-cloudformation/test/integ.core-custom-resources-node-18.js.snapshot/custom-resource-test-node-18-stack.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-cloudformation/test/integ.core-custom-resources-node-18.js.snapshot/customresourcetestnode18integDefaultTestDeployAssert9B8E9A20.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-cloudformation/test/integ.core-custom-resources-node-18.js.snapshot/customresourcetestnode18integDefaultTestDeployAssert9B8E9A20.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-cloudformation/test/integ.core-custom-resources-node-18.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-cloudformation/test/integ.core-custom-resources-node-18.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-cloudformation/test/integ.core-custom-resources-node-18.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-cloudformation/test/integ.core-custom-resources-node-18.ts
  packages/aws-cdk-lib/core/README.md
  packages/aws-cdk-lib/core/lib/custom-resource-provider/custom-resource-provider.ts
Labels: p2, feature-request, effort/small, pr/needs-review, beginning-contributor
