Repository aws/aws-cdk, pull requests merged in 2024-02, with the labels that each got.

#28949 chore: update Contributors File
  CONTRIBUTORS.md
Labels: p2, auto-approve

#28793 fix(stepfunctions): the Retry field in the statesJson in CustomState is always overwrited
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions/test/integ.custom-state.js.snapshot/aws-stepfunctions-custom-state-integ.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions/test/integ.custom-state.js.snapshot/aws-stepfunctions-custom-state-integ.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions/test/integ.custom-state.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions/test/integ.custom-state.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions/test/integ.custom-state.ts
  packages/aws-cdk-lib/aws-stepfunctions/README.md
  packages/aws-cdk-lib/aws-stepfunctions/lib/states/custom-state.ts
  packages/aws-cdk-lib/aws-stepfunctions/test/custom-state.test.ts
Labels: bug, p1, effort/medium, admired-contributor

#28953 chore(merge-back): 2.125.0
  CHANGELOG.v2.alpha.md
  CHANGELOG.v2.md
  version.v2.json
Labels: p2, pr/needs-community-review, pr/no-squash, auto-approve

#28799 chore(codepipeline-actions): bump up the solutionStack in the integ test
  packages/@aws-cdk-testing/framework-integ/test/aws-codepipeline-actions/test/integ.pipeline-elastic-beanstalk-deploy.js.snapshot/aws-cdk-codepipeline-elastic-beanstalk-deploy.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-codepipeline-actions/test/integ.pipeline-elastic-beanstalk-deploy.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-codepipeline-actions/test/integ.pipeline-elastic-beanstalk-deploy.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-codepipeline-actions/test/integ.pipeline-elastic-beanstalk-deploy.ts
Labels: p2, admired-contributor

#28958 chore(migrate): add migrate information to AWS::CDK::Metadata
  packages/aws-cdk-lib/core/lib/private/metadata-resource.ts
  packages/aws-cdk/lib/commands/migrate.ts
  packages/aws-cdk/lib/init.ts
  packages/aws-cdk/test/commands/migrate.test.ts
Labels: p2, contribution/core, pr-linter/cli-integ-tested

#28961 docs(migrate): update readme to reflect migrate from scan feature
  packages/aws-cdk/README.md
Labels: p2, contribution/core

#28962 feat(migrate): Add CDK Migrate `--from-scan` functionality
  packages/@aws-cdk-testing/cli-integ/lib/with-cdk-app.ts
  packages/@aws-cdk-testing/cli-integ/resources/cdk-apps/app/app.js
  packages/@aws-cdk-testing/cli-integ/tests/cli-integ-tests/cli.integtest.ts
  packages/aws-cdk/lib/cdk-toolkit.ts
  packages/aws-cdk/lib/cli.ts
  packages/aws-cdk/lib/commands/migrate.ts
  packages/aws-cdk/test/cdk-toolkit.test.ts
  packages/aws-cdk/test/commands/migrate.test.ts
  packages/aws-cdk/test/commands/test-resources/templates/empty-template.yml
Labels: p2, contribution/core, pr-linter/exempt-readme, pr-linter/exempt-integ-test, pr-linter/cli-integ-tested

#28967 chore: release 2.126.0
  CHANGELOG.v2.alpha.md
  CHANGELOG.v2.md
  packages/@aws-cdk-testing/cli-integ/lib/with-cdk-app.ts
  packages/@aws-cdk-testing/cli-integ/package.json
  packages/@aws-cdk-testing/cli-integ/resources/cdk-apps/app/app.js
  packages/@aws-cdk-testing/cli-integ/tests/cli-integ-tests/cli.integtest.ts
  packages/@aws-cdk-testing/framework-integ/package.json
  packages/@aws-cdk/cli-lib-alpha/THIRD_PARTY_LICENSES
  packages/@aws-cdk/cloudformation-diff/package.json
  packages/@aws-cdk/custom-resource-handlers/package.json
  packages/aws-cdk-lib/core/lib/private/metadata-resource.ts
  packages/aws-cdk-lib/package.json
  packages/aws-cdk/README.md
  packages/aws-cdk/THIRD_PARTY_LICENSES
  packages/aws-cdk/lib/cdk-toolkit.ts
  packages/aws-cdk/lib/cli.ts
  packages/aws-cdk/lib/commands/migrate.ts
  packages/aws-cdk/lib/init-templates/app/typescript/package.json
  packages/aws-cdk/lib/init-templates/lib/typescript/package.json
  packages/aws-cdk/lib/init-templates/sample-app/typescript/package.json
  packages/aws-cdk/lib/init.ts
  packages/aws-cdk/package.json
  packages/aws-cdk/test/cdk-toolkit.test.ts
  packages/aws-cdk/test/commands/migrate.test.ts
  packages/aws-cdk/test/commands/test-resources/stacks/s3.go
  packages/aws-cdk/test/commands/test-resources/templates/empty-template.yml
  packages/cdk-assets/package.json
  version.v2.json
  yarn.lock
Labels: p2, contribution/core, pr/no-squash, pr-linter/cli-integ-tested

#28968 chore(merge-back): 2.126.0
  CHANGELOG.v2.alpha.md
  CHANGELOG.v2.md
  version.v2.json
Labels: p2, pr/needs-community-review, pr/no-squash, auto-approve

#28959 chore: npm-check-updates && yarn upgrade
  packages/@aws-cdk-testing/framework-integ/package.json
  packages/@aws-cdk/aws-amplify-alpha/package.json
  packages/@aws-cdk/aws-appconfig-alpha/package.json
  packages/@aws-cdk/aws-apprunner-alpha/package.json
  packages/@aws-cdk/aws-cloud9-alpha/package.json
  packages/@aws-cdk/aws-codestar-alpha/package.json
  packages/@aws-cdk/aws-cognito-identitypool-alpha/package.json
  packages/@aws-cdk/aws-gamelift-alpha/package.json
  packages/@aws-cdk/aws-glue-alpha/package.json
  packages/@aws-cdk/aws-iot-actions-alpha/package.json
  packages/@aws-cdk/aws-iot-alpha/package.json
  packages/@aws-cdk/aws-iotevents-actions-alpha/package.json
  packages/@aws-cdk/aws-iotevents-alpha/package.json
  packages/@aws-cdk/aws-ivs-alpha/package.json
  packages/@aws-cdk/aws-kinesisanalytics-flink-alpha/package.json
  packages/@aws-cdk/aws-kinesisfirehose-alpha/package.json
  packages/@aws-cdk/aws-kinesisfirehose-destinations-alpha/package.json
  packages/@aws-cdk/aws-lambda-go-alpha/package.json
  packages/@aws-cdk/aws-lambda-python-alpha/package.json
  packages/@aws-cdk/aws-location-alpha/package.json
  packages/@aws-cdk/aws-msk-alpha/package.json
  packages/@aws-cdk/aws-neptune-alpha/package.json
  packages/@aws-cdk/aws-pipes-alpha/package.json
  packages/@aws-cdk/aws-redshift-alpha/package.json
  packages/@aws-cdk/aws-route53resolver-alpha/package.json
  packages/@aws-cdk/aws-s3objectlambda-alpha/package.json
  packages/@aws-cdk/aws-sagemaker-alpha/package.json
  packages/@aws-cdk/aws-scheduler-alpha/package.json
  packages/@aws-cdk/aws-scheduler-targets-alpha/package.json
  packages/@aws-cdk/aws-servicecatalogappregistry-alpha/package.json
  packages/@aws-cdk/cdk-cli-wrapper/package.json
  packages/@aws-cdk/cli-lib-alpha/package.json
  packages/@aws-cdk/cloud-assembly-schema/package.json
  packages/@aws-cdk/cloudformation-diff/package.json
  packages/@aws-cdk/custom-resource-handlers/package.json
  packages/@aws-cdk/cx-api/package.json
  packages/@aws-cdk/example-construct-library/package.json
  packages/@aws-cdk/integ-runner/package.json
  packages/@aws-cdk/integ-tests-alpha/package.json
  packages/@aws-cdk/region-info/package.json
  packages/@aws-cdk/sdk-v2-to-v3-adapter/package.json
  packages/aws-cdk-lib/package.json
  packages/aws-cdk/lib/init-templates/app/typescript/package.json
  packages/aws-cdk/lib/init-templates/lib/typescript/package.json
  packages/aws-cdk/lib/init-templates/sample-app/typescript/package.json
  packages/aws-cdk/package.json
  packages/awslint/package.json
  packages/cdk-assets/package.json
  tools/@aws-cdk/cdk-build-tools/package.json
  tools/@aws-cdk/cdk-release/package.json
  tools/@aws-cdk/eslint-plugin/package.json
  tools/@aws-cdk/lazify/package.json
  tools/@aws-cdk/node-bundle/package.json
  tools/@aws-cdk/pkglint/package.json
  tools/@aws-cdk/prlint/package.json
  tools/@aws-cdk/spec2cdk/package.json
  tools/@aws-cdk/yarn-cling/package.json
  yarn.lock
Labels: p2, dependencies, contribution/core, auto-approve, pr/needs-maintainer-review

#28556 feat(codepipeline): change default value for crossAccountKeys to false (under feature flag)
  packages/@aws-cdk-testing/framework-integ/test/aws-codepipeline-actions/test/integ.cfn-template-from-repo.lit.ts
  packages/@aws-cdk-testing/framework-integ/test/aws-codepipeline-actions/test/integ.lambda-deployed-through-codepipeline.lit.ts
  packages/@aws-cdk-testing/framework-integ/test/aws-codepipeline-actions/test/integ.lambda-pipeline.ts
  packages/@aws-cdk-testing/framework-integ/test/aws-codepipeline-actions/test/integ.pipeline-alexa-deploy.ts
  packages/@aws-cdk-testing/framework-integ/test/aws-codepipeline-actions/test/integ.pipeline-cfn.ts
  packages/@aws-cdk-testing/framework-integ/test/aws-codepipeline-actions/test/integ.pipeline-code-commit-build.ts
  packages/@aws-cdk-testing/framework-integ/test/aws-codepipeline-actions/test/integ.pipeline-code-commit-custom-event.ts
  packages/@aws-cdk-testing/framework-integ/test/aws-codepipeline-actions/test/integ.pipeline-code-commit-main.ts
  packages/@aws-cdk-testing/framework-integ/test/aws-codepipeline-actions/test/integ.pipeline-code-commit.ts
  packages/@aws-cdk-testing/framework-integ/test/aws-codepipeline-actions/test/integ.pipeline-events.ts
  packages/@aws-cdk-testing/framework-integ/test/aws-codepipeline-actions/test/integ.pipeline-stepfunctions.ts
  packages/@aws-cdk-testing/framework-integ/test/aws-codepipeline-actions/test/integ.pipeline-with-replication.ts
  packages/@aws-cdk-testing/framework-integ/test/aws-codepipeline-actions/test/s3/integ.source-bucket-events-cross-stack-same-env.ts
  packages/@aws-cdk-testing/framework-integ/test/aws-events-targets/test/codepipeline/integ.pipeline-event-target.ts
  packages/@aws-cdk-testing/framework-integ/test/pipelines/test/integ.pipeline-security.ts
  packages/@aws-cdk-testing/framework-integ/test/pipelines/test/integ.pipeline-with-assets-single-upload.ts
  packages/@aws-cdk-testing/framework-integ/test/pipelines/test/integ.pipeline-with-assets.ts
  packages/@aws-cdk-testing/framework-integ/test/pipelines/test/integ.pipeline.ts
  packages/@aws-cdk/aws-appconfig-alpha/test/integ.configuration.ts
  packages/@aws-cdk/aws-scheduler-targets-alpha/test/integ.codepipeline-start-pipeline-execution.ts
  packages/@aws-cdk/cx-api/FEATURE_FLAGS.md
  packages/aws-cdk-lib/aws-codepipeline-actions/test/integ.cfn-template-from-repo.lit.ts
  packages/aws-cdk-lib/aws-codepipeline-actions/test/integ.lambda-deployed-through-codepipeline.lit.ts
  packages/aws-cdk-lib/aws-codepipeline/lib/pipeline.ts
  packages/aws-cdk-lib/aws-codepipeline/test/pipeline.test.ts
  packages/aws-cdk-lib/cx-api/FEATURE_FLAGS.md
  packages/aws-cdk-lib/cx-api/README.md
  packages/aws-cdk-lib/cx-api/lib/features.ts
Labels: p1, feature-request, effort/medium, pr-linter/exempt-integ-test, distinguished-contributor, pr-linter/exemption-requested

#28969 docs(integ-runner): add missing options
  packages/@aws-cdk/integ-runner/README.md
Labels: p2, star-contributor

#28630 feat(codebuild): new CodeBuild lambda compute images
  packages/aws-cdk-lib/aws-codebuild/lib/linux-arm-lambda-build-image.ts
  packages/aws-cdk-lib/aws-codebuild/lib/linux-lambda-build-image.ts
Labels: p2, pr-linter/exempt-readme, pr-linter/exempt-test, pr-linter/exempt-integ-test, beginning-contributor

#28899 feat(cognito): specifying the trigger event version in UserPool.addTrigger()
  packages/@aws-cdk-testing/framework-integ/test/aws-cognito/test/integ.user-pool-pre-token-generation-v2.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-cognito/test/integ.user-pool-pre-token-generation-v2.js.snapshot/integ-user-pool-pre-token-generation-v2.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-cognito/test/integ.user-pool-pre-token-generation-v2.js.snapshot/integ-user-pool-pre-token-generation-v2.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-cognito/test/integ.user-pool-pre-token-generation-v2.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-cognito/test/integ.user-pool-pre-token-generation-v2.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-cognito/test/integ.user-pool-pre-token-generation-v2.js.snapshot/preTokenGenerationIntegTestDefaultTestDeployAssertF6CAA89D.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-cognito/test/integ.user-pool-pre-token-generation-v2.js.snapshot/preTokenGenerationIntegTestDefaultTestDeployAssertF6CAA89D.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-cognito/test/integ.user-pool-pre-token-generation-v2.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-cognito/test/integ.user-pool-pre-token-generation-v2.ts
  packages/aws-cdk-lib/aws-cognito/README.md
  packages/aws-cdk-lib/aws-cognito/lib/user-pool.ts
  packages/aws-cdk-lib/aws-cognito/test/user-pool.test.ts
Labels: p2, feature-request, effort/medium, admired-contributor

#28877 feat(ecs): `idleTimeout` and `perRequestTimeout` for service connect
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs/test/fargate/integ.service-connect.js.snapshot/ServiceConnectDefaultTestDeployAssert88F6A66F.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs/test/fargate/integ.service-connect.js.snapshot/ServiceConnectDefaultTestDeployAssert88F6A66F.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs/test/fargate/integ.service-connect.js.snapshot/asset.3f0f15596be1e3fbbf4a0571522aa1e5312d44abff27360f8d043c1b0704bcf4.bundle/index.js
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs/test/fargate/integ.service-connect.js.snapshot/aws-ecs-service-connect.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs/test/fargate/integ.service-connect.js.snapshot/aws-ecs-service-connect.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs/test/fargate/integ.service-connect.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs/test/fargate/integ.service-connect.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs/test/fargate/integ.service-connect.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs/test/fargate/integ.service-connect.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs/test/fargate/integ.service-connect.ts
  packages/aws-cdk-lib/aws-ecs/README.md
  packages/aws-cdk-lib/aws-ecs/lib/base/base-service.ts
  packages/aws-cdk-lib/aws-ecs/test/fargate/fargate-service.test.ts
Labels: p2, distinguished-contributor, pr/needs-maintainer-review

#28895 fix(integ-tests): cannot use v3 package name in an awsApiCall
  packages/@aws-cdk/integ-tests-alpha/README.md
  packages/@aws-cdk/integ-tests-alpha/lib/assertions/sdk.ts
  packages/@aws-cdk/integ-tests-alpha/lib/assertions/types.ts
  packages/@aws-cdk/integ-tests-alpha/test/assertions/deploy-assert.test.ts
  packages/@aws-cdk/integ-tests-alpha/test/assertions/providers/integ.assertions.js.snapshot/Assertions.assets.json
  packages/@aws-cdk/integ-tests-alpha/test/assertions/providers/integ.assertions.js.snapshot/AssertionsTestDefaultTestDeployAssertDC0672BB.assets.json
  packages/@aws-cdk/integ-tests-alpha/test/assertions/providers/integ.assertions.js.snapshot/AssertionsTestDefaultTestDeployAssertDC0672BB.template.json
  packages/@aws-cdk/integ-tests-alpha/test/assertions/providers/integ.assertions.js.snapshot/cdk.out
  packages/@aws-cdk/integ-tests-alpha/test/assertions/providers/integ.assertions.js.snapshot/integ.json
  packages/@aws-cdk/integ-tests-alpha/test/assertions/providers/integ.assertions.js.snapshot/manifest.json
  packages/@aws-cdk/integ-tests-alpha/test/assertions/providers/integ.assertions.js.snapshot/tree.json
  packages/@aws-cdk/integ-tests-alpha/test/assertions/providers/integ.assertions.ts
Labels: bug, p1, effort/medium, admired-contributor

#28973 fix(lambda): LoggingConfig default error
  packages/aws-cdk-lib/aws-lambda/lib/function.ts
Labels: p2, @aws-cdk/aws-lambda, contribution/core, pr-linter/exempt-test, pr-linter/exempt-breaking-change, pr-linter/exempt-integ-test

#28992 chore: remove erroneously committed file
  .pre-commit-config.yaml
Labels: p2, contribution/core

#28870 fix(cloudwatch): Math:UnknownIdentifier warning for INSIGHT_RULE_METRIC
  packages/aws-cdk-lib/aws-cloudwatch/lib/metric.ts
  packages/aws-cdk-lib/aws-cloudwatch/test/metric-math.test.ts
Labels: p2, pr-linter/exempt-integ-test, beginning-contributor

#28797 feat(ecs-patterns): `healthCheck` property for `ApplicationLoadBalancedFargateService`
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs-patterns/test/fargate/integ.alb-fargate-service-health-check.js.snapshot/aws-ecs-patterns-alb-health-check.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs-patterns/test/fargate/integ.alb-fargate-service-health-check.js.snapshot/aws-ecs-patterns-alb-health-check.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs-patterns/test/fargate/integ.alb-fargate-service-health-check.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs-patterns/test/fargate/integ.alb-fargate-service-health-check.js.snapshot/healthCheckApplicationLoadBalancedFargateServiceTestDefaultTestDeployAssert796A0E8E.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs-patterns/test/fargate/integ.alb-fargate-service-health-check.js.snapshot/healthCheckApplicationLoadBalancedFargateServiceTestDefaultTestDeployAssert796A0E8E.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs-patterns/test/fargate/integ.alb-fargate-service-health-check.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs-patterns/test/fargate/integ.alb-fargate-service-health-check.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs-patterns/test/fargate/integ.alb-fargate-service-health-check.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs-patterns/test/fargate/integ.alb-fargate-service-health-check.ts
  packages/aws-cdk-lib/aws-ecs-patterns/README.md
  packages/aws-cdk-lib/aws-ecs-patterns/lib/fargate/application-load-balanced-fargate-service.ts
  packages/aws-cdk-lib/aws-ecs-patterns/test/fargate/load-balanced-fargate-service.test.ts
Labels: p2, feature-request, effort/medium, beginning-contributor, pr-linter/exemption-requested

#29002 chore(prlint): enforce lowercase pr title
  tools/@aws-cdk/prlint/lint.ts
  tools/@aws-cdk/prlint/test/lint.test.ts
Labels: p2, contribution/core, pr/needs-maintainer-review

#28938 feat(route53): multivalue answer routing
  packages/@aws-cdk-testing/framework-integ/test/aws-route53/test/integ.multi-value-answer-routing.js.snapshot/Route53MultiValueAnswerRoutingIntegDefaultTestDeployAssert2794160C.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-route53/test/integ.multi-value-answer-routing.js.snapshot/Route53MultiValueAnswerRoutingIntegDefaultTestDeployAssert2794160C.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-route53/test/integ.multi-value-answer-routing.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-route53/test/integ.multi-value-answer-routing.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-route53/test/integ.multi-value-answer-routing.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-route53/test/integ.multi-value-answer-routing.js.snapshot/multi-value-answer-routing.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-route53/test/integ.multi-value-answer-routing.js.snapshot/multi-value-answer-routing.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-route53/test/integ.multi-value-answer-routing.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-route53/test/integ.multi-value-answer-routing.ts
  packages/aws-cdk-lib/aws-route53/README.md
  packages/aws-cdk-lib/aws-route53/lib/record-set.ts
  packages/aws-cdk-lib/aws-route53/test/record-set.test.ts
Labels: p2, feature-request, effort/medium, admired-contributor

#29015 docs(stepfunctions): `integrationPattern` update
  packages/aws-cdk-lib/aws-stepfunctions/README.md
  packages/aws-cdk-lib/aws-stepfunctions/lib/states/task-base.ts
Labels: p2, feature-request, effort/small, valued-contributor

#29005 chore(appconfig): fix eslint and update lambda extension arns
  packages/@aws-cdk/aws-appconfig-alpha/.eslintrc.js
  packages/@aws-cdk/aws-appconfig-alpha/lib/application.ts
  packages/@aws-cdk/aws-appconfig-alpha/lib/configuration.ts
  packages/@aws-cdk/aws-appconfig-alpha/test/application.test.ts
  packages/@aws-cdk/aws-appconfig-alpha/test/integ.application.ts
  packages/@aws-cdk/aws-appconfig-alpha/test/integ.configuration.ts
  packages/@aws-cdk/aws-appconfig-alpha/test/integ.deployment-strategy.ts
  packages/@aws-cdk/aws-appconfig-alpha/test/integ.environment.ts
  packages/@aws-cdk/aws-appconfig-alpha/test/integ.extension.ts
Labels: p2, admired-contributor

#28913 feat(efs): create read-only file system for use as a destination of replication
  packages/@aws-cdk-testing/framework-integ/test/aws-efs/test/integ.efs-filesystem-protection.js.snapshot/asset.4554b47be6f57b68c6c7a7391dcc73894866d2377fe174883351e7639097f292/__entrypoint__.js
  packages/@aws-cdk-testing/framework-integ/test/aws-efs/test/integ.efs-filesystem-protection.js.snapshot/asset.4554b47be6f57b68c6c7a7391dcc73894866d2377fe174883351e7639097f292/index.js
  packages/@aws-cdk-testing/framework-integ/test/aws-efs/test/integ.efs-filesystem-protection.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-efs/test/integ.efs-filesystem-protection.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-efs/test/integ.efs-filesystem-protection.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-efs/test/integ.efs-filesystem-protection.js.snapshot/test-efs-protection-integ.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-efs/test/integ.efs-filesystem-protection.js.snapshot/test-efs-protection-integ.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-efs/test/integ.efs-filesystem-protection.js.snapshot/testefsprotectionintegtestDefaultTestDeployAssertC510DC4F.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-efs/test/integ.efs-filesystem-protection.js.snapshot/testefsprotectionintegtestDefaultTestDeployAssertC510DC4F.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-efs/test/integ.efs-filesystem-protection.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-efs/test/integ.efs-filesystem-protection.ts
  packages/aws-cdk-lib/aws-efs/README.md
  packages/aws-cdk-lib/aws-efs/lib/efs-file-system.ts
  packages/aws-cdk-lib/aws-efs/test/efs-file-system.test.ts
Labels: p2, feature-request, pr/needs-community-review, effort/medium, admired-contributor

#29020 chore(migrate): update warning message
  packages/aws-cdk/lib/cdk-toolkit.ts
Labels: p2, contribution/core, pr-linter/cli-integ-tested

#28943 fix(lambda-event-sources): update s3-event-source to accept IBucket
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-event-sources/test/integ.s3.imported-bucket.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-event-sources/test/integ.s3.imported-bucket.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-event-sources/test/integ.s3.imported-bucket.js.snapshot/issue4324DefaultTestDeployAssert63CED672.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-event-sources/test/integ.s3.imported-bucket.js.snapshot/issue4324DefaultTestDeployAssert63CED672.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-event-sources/test/integ.s3.imported-bucket.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-event-sources/test/integ.s3.imported-bucket.js.snapshot/tester.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-event-sources/test/integ.s3.imported-bucket.js.snapshot/tester.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-event-sources/test/integ.s3.imported-bucket.js.snapshot/testersetup.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-event-sources/test/integ.s3.imported-bucket.js.snapshot/testersetup.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-event-sources/test/integ.s3.imported-bucket.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-event-sources/test/integ.s3.imported-bucket.ts
  packages/aws-cdk-lib/aws-lambda-event-sources/README.md
  packages/aws-cdk-lib/aws-lambda-event-sources/lib/s3.ts
  packages/aws-cdk-lib/aws-lambda-event-sources/test/s3.test.ts
Labels: p1, feature-request, effort/small, beginning-contributor

#29008 feat(sns): message archive policy
  packages/@aws-cdk-testing/framework-integ/test/aws-sns/test/integ.sns-fifo-archive-policy.js.snapshot/SNSFifoArchivePolicyStack.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-sns/test/integ.sns-fifo-archive-policy.js.snapshot/SNSFifoArchivePolicyStack.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-sns/test/integ.sns-fifo-archive-policy.js.snapshot/SqsTestDefaultTestDeployAssert659366A6.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-sns/test/integ.sns-fifo-archive-policy.js.snapshot/SqsTestDefaultTestDeployAssert659366A6.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-sns/test/integ.sns-fifo-archive-policy.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-sns/test/integ.sns-fifo-archive-policy.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-sns/test/integ.sns-fifo-archive-policy.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-sns/test/integ.sns-fifo-archive-policy.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-sns/test/integ.sns-fifo-archive-policy.ts
  packages/aws-cdk-lib/aws-sns/README.md
  packages/aws-cdk-lib/aws-sns/lib/topic.ts
  packages/aws-cdk-lib/aws-sns/test/sns.test.ts
Labels: p2, feature-request, star-contributor

#29030 chore(ecs): typo in ec2-service.ts
  packages/aws-cdk-lib/aws-ecs/lib/ec2/ec2-service.ts
Labels: p2, beginning-contributor

#29034 chore: comment out broken tests
  packages/@aws-cdk-testing/cli-integ/tests/cli-integ-tests/cli.integtest.ts
Labels: p2, contribution/core

#29035 fix(migrate): `--from-stack` does not retrieved processed template
  packages/aws-cdk/lib/commands/migrate.ts
Labels: p2, contribution/core, pr-linter/exempt-test, pr-linter/exempt-integ-test, pr-linter/cli-integ-tested, pr/needs-maintainer-review

#29036 chore: remove breaking changes comment from PR template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: p2, contribution/core

#29021 fix(appconfig): deprecate deploy method
  packages/@aws-cdk/aws-appconfig-alpha/lib/configuration.ts
Labels: p2, pr-linter/exempt-test, pr-linter/exempt-integ-test, admired-contributor

#28821 feat(stepfunctions): distributed map construct
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions/test/integ.distributed-map.js.snapshot/DistributedMapDefaultTestDeployAssertFD6CBCC4.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions/test/integ.distributed-map.js.snapshot/DistributedMapDefaultTestDeployAssertFD6CBCC4.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions/test/integ.distributed-map.js.snapshot/asset.2ec8ad9e91dcd6e7ad6a5c84ffc6c9c05c408aca3b26ceb2816d81043e6c4dc3/index.js
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions/test/integ.distributed-map.js.snapshot/asset.4984c845346313a408899c8ff361d3b7b97953a9d4202e47694ef2a101f4b5c3.bundle/index.js
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions/test/integ.distributed-map.js.snapshot/aws-stepfunctions-map-integ.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions/test/integ.distributed-map.js.snapshot/aws-stepfunctions-map-integ.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions/test/integ.distributed-map.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions/test/integ.distributed-map.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions/test/integ.distributed-map.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions/test/integ.distributed-map.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions/test/integ.distributed-map.ts
  packages/aws-cdk-lib/aws-stepfunctions/README.md
  packages/aws-cdk-lib/aws-stepfunctions/lib/index.ts
  packages/aws-cdk-lib/aws-stepfunctions/lib/state-graph.ts
  packages/aws-cdk-lib/aws-stepfunctions/lib/state-machine.ts
  packages/aws-cdk-lib/aws-stepfunctions/lib/states/distributed-map.ts
  packages/aws-cdk-lib/aws-stepfunctions/lib/states/distributed-map/item-batcher.ts
  packages/aws-cdk-lib/aws-stepfunctions/lib/states/distributed-map/item-reader.ts
  packages/aws-cdk-lib/aws-stepfunctions/lib/states/distributed-map/result-writer.ts
  packages/aws-cdk-lib/aws-stepfunctions/lib/states/map-base.ts
  packages/aws-cdk-lib/aws-stepfunctions/lib/states/map.ts
  packages/aws-cdk-lib/aws-stepfunctions/lib/states/state.ts
  packages/aws-cdk-lib/aws-stepfunctions/test/distributed-map.test.ts
  packages/aws-cdk-lib/aws-stepfunctions/test/state-machine.test.ts
Labels: p1, feature-request, effort/medium, beginning-contributor

#29000 chore(prlint): update second comment to state exemption request has been submitted
  tools/@aws-cdk/prlint/lint.ts
  tools/@aws-cdk/prlint/test/lint.test.ts
Labels: bug, p2, effort/medium, contribution/core

#29017 chore(appconfig): refactor README and integ tests
  packages/@aws-cdk/aws-appconfig-alpha/README.md
  packages/@aws-cdk/aws-appconfig-alpha/lib/environment.ts
  packages/@aws-cdk/aws-appconfig-alpha/test/integ.application.js.snapshot/appconfigapplicationDefaultTestDeployAssertD6537C40.assets.json
  packages/@aws-cdk/aws-appconfig-alpha/test/integ.application.js.snapshot/aws-appconfig-application.assets.json
  packages/@aws-cdk/aws-appconfig-alpha/test/integ.application.js.snapshot/aws-appconfig-application.template.json
  packages/@aws-cdk/aws-appconfig-alpha/test/integ.application.js.snapshot/cdk.out
  packages/@aws-cdk/aws-appconfig-alpha/test/integ.application.js.snapshot/integ.json
  packages/@aws-cdk/aws-appconfig-alpha/test/integ.application.js.snapshot/manifest.json
  packages/@aws-cdk/aws-appconfig-alpha/test/integ.application.js.snapshot/tree.json
  packages/@aws-cdk/aws-appconfig-alpha/test/integ.application.ts
  packages/@aws-cdk/aws-appconfig-alpha/test/integ.configuration.ts
  packages/@aws-cdk/aws-appconfig-alpha/test/integ.deployment-strategy.ts
  packages/@aws-cdk/aws-appconfig-alpha/test/integ.environment.ts
  packages/@aws-cdk/aws-appconfig-alpha/test/integ.extension.ts
Labels: p2, admired-contributor

#29053 feat: update L1 CloudFormation resource definitions
  packages/@aws-cdk/cloudformation-diff/package.json
  packages/@aws-cdk/integ-runner/package.json
  packages/aws-cdk-lib/package.json
  packages/aws-cdk-lib/scripts/scope-map.json
  tools/@aws-cdk/spec2cdk/package.json
  yarn.lock
Labels: p2, dependencies, contribution/core, pr-linter/exempt-readme, pr-linter/exempt-test, auto-approve, pr-linter/exempt-integ-test

#29040 feat(eks): support for Kubernetes version 1.29
  packages/aws-cdk-lib/aws-eks/README.md
  packages/aws-cdk-lib/aws-eks/lib/cluster.ts
  packages/aws-cdk-lib/package.json
Labels: p2, feature-request, effort/medium, pr-linter/exempt-test, pr-linter/exempt-integ-test, distinguished-contributor

#29048 feat(pipes-sources): new EventBridge Pipes sources alpha module
  packages/@aws-cdk/aws-pipes-sources-alpha/.eslintrc.js
  packages/@aws-cdk/aws-pipes-sources-alpha/.gitignore
  packages/@aws-cdk/aws-pipes-sources-alpha/.npmignore
  packages/@aws-cdk/aws-pipes-sources-alpha/LICENSE
  packages/@aws-cdk/aws-pipes-sources-alpha/NOTICE
  packages/@aws-cdk/aws-pipes-sources-alpha/README.md
  packages/@aws-cdk/aws-pipes-sources-alpha/awslint.json
  packages/@aws-cdk/aws-pipes-sources-alpha/jest.config.js
  packages/@aws-cdk/aws-pipes-sources-alpha/lib/index.ts
  packages/@aws-cdk/aws-pipes-sources-alpha/lib/sqs.ts
  packages/@aws-cdk/aws-pipes-sources-alpha/package.json
  packages/@aws-cdk/aws-pipes-sources-alpha/rosetta/default.ts-fixture
  packages/@aws-cdk/aws-pipes-sources-alpha/test/__snapshots__/sqs.test.ts.snap
  packages/@aws-cdk/aws-pipes-sources-alpha/test/integ.sqs.js.snapshot/asset.3f0f15596be1e3fbbf4a0571522aa1e5312d44abff27360f8d043c1b0704bcf4.bundle/index.js
  packages/@aws-cdk/aws-pipes-sources-alpha/test/integ.sqs.js.snapshot/aws-cdk-pipes-sources-sqs.assets.json
  packages/@aws-cdk/aws-pipes-sources-alpha/test/integ.sqs.js.snapshot/aws-cdk-pipes-sources-sqs.template.json
  packages/@aws-cdk/aws-pipes-sources-alpha/test/integ.sqs.js.snapshot/cdk.out
  packages/@aws-cdk/aws-pipes-sources-alpha/test/integ.sqs.js.snapshot/integ.json
  packages/@aws-cdk/aws-pipes-sources-alpha/test/integ.sqs.js.snapshot/integtestpipesourcesqsDefaultTestDeployAssertD36A35C2.assets.json
  packages/@aws-cdk/aws-pipes-sources-alpha/test/integ.sqs.js.snapshot/integtestpipesourcesqsDefaultTestDeployAssertD36A35C2.template.json
  packages/@aws-cdk/aws-pipes-sources-alpha/test/integ.sqs.js.snapshot/manifest.json
  packages/@aws-cdk/aws-pipes-sources-alpha/test/integ.sqs.js.snapshot/tree.json
  packages/@aws-cdk/aws-pipes-sources-alpha/test/integ.sqs.ts
  packages/@aws-cdk/aws-pipes-sources-alpha/test/sqs.test.ts
  packages/@aws-cdk/aws-pipes-sources-alpha/test/test-classes.ts
  packages/@aws-cdk/aws-pipes-sources-alpha/tsconfig.dev.json
Labels: p2, repeat-contributor

#29056 chore(prlint): fix linter call to listComments
  tools/@aws-cdk/prlint/lint.ts
Labels: p2, contribution/core

#29061 chore(merge-back): 2.127.0
  CHANGELOG.v2.alpha.md
  CHANGELOG.v2.md
  packages/aws-cdk-lib/cx-api/FEATURE_FLAGS.md
  packages/aws-cdk-lib/cx-api/lib/features.ts
  version.v2.json
Labels: p2, pr/needs-community-review, pr/no-squash, auto-approve

#29081 fix(lambda): @deprecated tag to deprecated runtimes
  packages/aws-cdk-lib/aws-lambda/lib/runtime.ts
Labels: p2, pr-linter/exempt-test, pr-linter/exempt-integ-test, repeat-contributor

#26957 feat(codedeploy): ignoreAlarmConfiguration parameter to Deployment Groups
  packages/@aws-cdk-testing/framework-integ/test/aws-codedeploy/test/ecs/integ.deployment-group.js.snapshot/EcsDeploymentGroupTestDefaultTestDeployAssert60AABFA0.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-codedeploy/test/ecs/integ.deployment-group.js.snapshot/aws-cdk-codedeploy-ecs-dg.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-codedeploy/test/ecs/integ.deployment-group.js.snapshot/aws-cdk-codedeploy-ecs-dg.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-codedeploy/test/ecs/integ.deployment-group.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-codedeploy/test/ecs/integ.deployment-group.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-codedeploy/test/ecs/integ.deployment-group.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-codedeploy/test/ecs/integ.deployment-group.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-codedeploy/test/ecs/integ.deployment-group.ts
  packages/aws-cdk-lib/aws-codedeploy/README.md
  packages/aws-cdk-lib/aws-codedeploy/lib/ecs/deployment-group.ts
  packages/aws-cdk-lib/aws-codedeploy/lib/lambda/deployment-group.ts
  packages/aws-cdk-lib/aws-codedeploy/lib/private/utils.ts
  packages/aws-cdk-lib/aws-codedeploy/lib/server/deployment-group.ts
  packages/aws-cdk-lib/aws-codedeploy/test/ecs/deployment-group.test.ts
  packages/aws-cdk-lib/aws-codedeploy/test/lambda/deployment-group.test.ts
  packages/aws-cdk-lib/aws-codedeploy/test/server/deployment-group.test.ts
Labels: p2, beginning-contributor, pr/needs-maintainer-review

#29084 feat(ses): `grant` methods to `IEmailIdentity`
  packages/@aws-cdk-testing/framework-integ/test/aws-ses/test/fixtures/send-email/index.py
  packages/@aws-cdk-testing/framework-integ/test/aws-ses/test/integ.email-identity.js.snapshot/EmailIdentityIntegDefaultTestDeployAssert3F909307.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ses/test/integ.email-identity.js.snapshot/asset.ab3156800c2f322f16da8bff913172139189a387dd64a4e622f82a790561fd4d/index.py
  packages/@aws-cdk-testing/framework-integ/test/aws-ses/test/integ.email-identity.js.snapshot/cdk-ses-email-identity-integ.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ses/test/integ.email-identity.js.snapshot/cdk-ses-email-identity-integ.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ses/test/integ.email-identity.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-ses/test/integ.email-identity.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ses/test/integ.email-identity.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ses/test/integ.email-identity.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ses/test/integ.email-identity.ts
  packages/aws-cdk-lib/aws-ses/README.md
  packages/aws-cdk-lib/aws-ses/lib/email-identity.ts
  packages/aws-cdk-lib/aws-ses/test/email-identity.test.ts
Labels: p2, feature-request, pr-linter/exempt-integ-test, beginning-contributor

#29078 feat(cloudwatch): add `TableWidget`
  packages/@aws-cdk-testing/framework-integ/test/aws-cloudwatch/test/integ.table-widget.js.snapshot/TableWidget.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-cloudwatch/test/integ.table-widget.js.snapshot/TableWidget.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-cloudwatch/test/integ.table-widget.js.snapshot/TableWidgetTestDefaultTestDeployAssertA94EAD9F.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-cloudwatch/test/integ.table-widget.js.snapshot/TableWidgetTestDefaultTestDeployAssertA94EAD9F.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-cloudwatch/test/integ.table-widget.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-cloudwatch/test/integ.table-widget.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-cloudwatch/test/integ.table-widget.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-cloudwatch/test/integ.table-widget.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-cloudwatch/test/integ.table-widget.ts
  packages/aws-cdk-lib/aws-cloudwatch/README.md
  packages/aws-cdk-lib/aws-cloudwatch/lib/graph.ts
  packages/aws-cdk-lib/aws-cloudwatch/test/graphs.test.ts
  packages/aws-cdk-lib/awslint.json
Labels: p2, feature-request, effort/medium, admired-contributor

#29057 feat(pipes-targets): new EventBridge Pipes targets alpha module
  packages/@aws-cdk/aws-pipes-targets-alpha/.eslintrc.js
  packages/@aws-cdk/aws-pipes-targets-alpha/.gitignore
  packages/@aws-cdk/aws-pipes-targets-alpha/.npmignore
  packages/@aws-cdk/aws-pipes-targets-alpha/LICENSE
  packages/@aws-cdk/aws-pipes-targets-alpha/NOTICE
  packages/@aws-cdk/aws-pipes-targets-alpha/README.md
  packages/@aws-cdk/aws-pipes-targets-alpha/awslint.json
  packages/@aws-cdk/aws-pipes-targets-alpha/jest.config.js
  packages/@aws-cdk/aws-pipes-targets-alpha/lib/index.ts
  packages/@aws-cdk/aws-pipes-targets-alpha/lib/sqs.ts
  packages/@aws-cdk/aws-pipes-targets-alpha/package.json
  packages/@aws-cdk/aws-pipes-targets-alpha/rosetta/default.ts-fixture
  packages/@aws-cdk/aws-pipes-targets-alpha/test/__snapshots__/sqs.test.ts.snap
  packages/@aws-cdk/aws-pipes-targets-alpha/test/integ.sqs.js.snapshot/asset.3f0f15596be1e3fbbf4a0571522aa1e5312d44abff27360f8d043c1b0704bcf4.bundle/index.js
  packages/@aws-cdk/aws-pipes-targets-alpha/test/integ.sqs.js.snapshot/aws-cdk-pipes-targets.assets.json
  packages/@aws-cdk/aws-pipes-targets-alpha/test/integ.sqs.js.snapshot/aws-cdk-pipes-targets.template.json
  packages/@aws-cdk/aws-pipes-targets-alpha/test/integ.sqs.js.snapshot/cdk.out
  packages/@aws-cdk/aws-pipes-targets-alpha/test/integ.sqs.js.snapshot/integ.json
  packages/@aws-cdk/aws-pipes-targets-alpha/test/integ.sqs.js.snapshot/integtestpipetargetsqsDefaultTestDeployAssertD5F047DA.assets.json
  packages/@aws-cdk/aws-pipes-targets-alpha/test/integ.sqs.js.snapshot/integtestpipetargetsqsDefaultTestDeployAssertD5F047DA.template.json
  packages/@aws-cdk/aws-pipes-targets-alpha/test/integ.sqs.js.snapshot/manifest.json
  packages/@aws-cdk/aws-pipes-targets-alpha/test/integ.sqs.js.snapshot/tree.json
  packages/@aws-cdk/aws-pipes-targets-alpha/test/integ.sqs.ts
  packages/@aws-cdk/aws-pipes-targets-alpha/test/sqs.test.ts
  packages/@aws-cdk/aws-pipes-targets-alpha/test/test-classes.ts
  packages/@aws-cdk/aws-pipes-targets-alpha/tsconfig.dev.json
Labels: p2, repeat-contributor

#28538 feat(codepipeline): pipeline type v2 with pipeline-level variables and triggers
  packages/@aws-cdk-testing/framework-integ/test/aws-codepipeline-actions/test/integ.pipeline-with-pipeline-triggers.js.snapshot/asset.3f0f15596be1e3fbbf4a0571522aa1e5312d44abff27360f8d043c1b0704bcf4.bundle/index.js
  packages/@aws-cdk-testing/framework-integ/test/aws-codepipeline-actions/test/integ.pipeline-with-pipeline-triggers.js.snapshot/aws-cdk-codepipeline-with-pipeline-triggers.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-codepipeline-actions/test/integ.pipeline-with-pipeline-triggers.js.snapshot/aws-cdk-codepipeline-with-pipeline-triggers.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-codepipeline-actions/test/integ.pipeline-with-pipeline-triggers.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-codepipeline-actions/test/integ.pipeline-with-pipeline-triggers.js.snapshot/codepipelinewithpipelinetriggerstestDefaultTestDeployAssertE3F8DDE6.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-codepipeline-actions/test/integ.pipeline-with-pipeline-triggers.js.snapshot/codepipelinewithpipelinetriggerstestDefaultTestDeployAssertE3F8DDE6.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-codepipeline-actions/test/integ.pipeline-with-pipeline-triggers.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-codepipeline-actions/test/integ.pipeline-with-pipeline-triggers.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-codepipeline-actions/test/integ.pipeline-with-pipeline-triggers.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-codepipeline-actions/test/integ.pipeline-with-pipeline-triggers.ts
  packages/@aws-cdk-testing/framework-integ/test/aws-codepipeline-actions/test/integ.pipeline-with-pipeline-variables.js.snapshot/asset.2ec8ad9e91dcd6e7ad6a5c84ffc6c9c05c408aca3b26ceb2816d81043e6c4dc3/index.js
  packages/@aws-cdk-testing/framework-integ/test/aws-codepipeline-actions/test/integ.pipeline-with-pipeline-variables.js.snapshot/asset.df6156f884f46480078633afbd0b768581022c5e444c5f72752980280ae15bd9.bundle/index.js
  packages/@aws-cdk-testing/framework-integ/test/aws-codepipeline-actions/test/integ.pipeline-with-pipeline-variables.js.snapshot/aws-cdk-codepipeline-with-pipeline-variables.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-codepipeline-actions/test/integ.pipeline-with-pipeline-variables.js.snapshot/aws-cdk-codepipeline-with-pipeline-variables.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-codepipeline-actions/test/integ.pipeline-with-pipeline-variables.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-codepipeline-actions/test/integ.pipeline-with-pipeline-variables.js.snapshot/codepipelinewithpipelinevariablestestDefaultTestDeployAssert9ACAEAAB.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-codepipeline-actions/test/integ.pipeline-with-pipeline-variables.js.snapshot/codepipelinewithpipelinevariablestestDefaultTestDeployAssert9ACAEAAB.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-codepipeline-actions/test/integ.pipeline-with-pipeline-variables.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-codepipeline-actions/test/integ.pipeline-with-pipeline-variables.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-codepipeline-actions/test/integ.pipeline-with-pipeline-variables.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-codepipeline-actions/test/integ.pipeline-with-pipeline-variables.ts
  packages/aws-cdk-lib/aws-codepipeline/README.md
  packages/aws-cdk-lib/aws-codepipeline/lib/index.ts
  packages/aws-cdk-lib/aws-codepipeline/lib/pipeline.ts
  packages/aws-cdk-lib/aws-codepipeline/lib/private/validation.ts
  packages/aws-cdk-lib/aws-codepipeline/lib/trigger.ts
  packages/aws-cdk-lib/aws-codepipeline/lib/variable.ts
  packages/aws-cdk-lib/aws-codepipeline/test/pipeline.test.ts
  packages/aws-cdk-lib/aws-codepipeline/test/triggers.test.ts
  packages/aws-cdk-lib/aws-codepipeline/test/variables.test.ts
  packages/aws-cdk-lib/pipelines/test/codepipeline/codepipeline.test.ts
Labels: p2, feature-request, effort/medium, distinguished-contributor

#28927 feat(scheduler-targets-alpha): `SageMakerStartPipelineExecution` Target
  packages/@aws-cdk/aws-scheduler-targets-alpha/.eslintrc.js
  packages/@aws-cdk/aws-scheduler-targets-alpha/README.md
  packages/@aws-cdk/aws-scheduler-targets-alpha/lib/index.ts
  packages/@aws-cdk/aws-scheduler-targets-alpha/lib/sage-maker-start-pipeline-execution.ts
  packages/@aws-cdk/aws-scheduler-targets-alpha/test/integ.sage-maker-start-pipeline-execution.js.snapshot/asset.3f0f15596be1e3fbbf4a0571522aa1e5312d44abff27360f8d043c1b0704bcf4.bundle/index.js
  packages/@aws-cdk/aws-scheduler-targets-alpha/test/integ.sage-maker-start-pipeline-execution.js.snapshot/aws-cdk-scheduler-targets-sagemaker-start-pipeline-execution.assets.json
  packages/@aws-cdk/aws-scheduler-targets-alpha/test/integ.sage-maker-start-pipeline-execution.js.snapshot/aws-cdk-scheduler-targets-sagemaker-start-pipeline-execution.template.json
  packages/@aws-cdk/aws-scheduler-targets-alpha/test/integ.sage-maker-start-pipeline-execution.js.snapshot/cdk.out
  packages/@aws-cdk/aws-scheduler-targets-alpha/test/integ.sage-maker-start-pipeline-execution.js.snapshot/integ.json
  packages/@aws-cdk/aws-scheduler-targets-alpha/test/integ.sage-maker-start-pipeline-execution.js.snapshot/integrationtestsagemakerstartpipelineexecutionDefaultTestDeployAssert19EB5121.assets.json
  packages/@aws-cdk/aws-scheduler-targets-alpha/test/integ.sage-maker-start-pipeline-execution.js.snapshot/integrationtestsagemakerstartpipelineexecutionDefaultTestDeployAssert19EB5121.template.json
  packages/@aws-cdk/aws-scheduler-targets-alpha/test/integ.sage-maker-start-pipeline-execution.js.snapshot/manifest.json
  packages/@aws-cdk/aws-scheduler-targets-alpha/test/integ.sage-maker-start-pipeline-execution.js.snapshot/tree.json
  packages/@aws-cdk/aws-scheduler-targets-alpha/test/integ.sage-maker-start-pipeline-execution.ts
  packages/@aws-cdk/aws-scheduler-targets-alpha/test/sage-maker-start-pipeline-execution.test.ts
  packages/aws-cdk-lib/aws-sagemaker/lib/index.ts
  packages/aws-cdk-lib/aws-sagemaker/lib/pipeline.ts
Labels: p2, feature-request, effort/medium, distinguished-contributor

#29063 feat(pipes-enrichments): new EventBridge Pipes enrichments alpha module
  packages/@aws-cdk/aws-pipes-enrichments-alpha/.eslintrc.js
  packages/@aws-cdk/aws-pipes-enrichments-alpha/.gitignore
  packages/@aws-cdk/aws-pipes-enrichments-alpha/.npmignore
  packages/@aws-cdk/aws-pipes-enrichments-alpha/LICENSE
  packages/@aws-cdk/aws-pipes-enrichments-alpha/NOTICE
  packages/@aws-cdk/aws-pipes-enrichments-alpha/README.md
  packages/@aws-cdk/aws-pipes-enrichments-alpha/awslint.json
  packages/@aws-cdk/aws-pipes-enrichments-alpha/jest.config.js
  packages/@aws-cdk/aws-pipes-enrichments-alpha/lib/index.ts
  packages/@aws-cdk/aws-pipes-enrichments-alpha/lib/lambda.ts
  packages/@aws-cdk/aws-pipes-enrichments-alpha/package.json
  packages/@aws-cdk/aws-pipes-enrichments-alpha/rosetta/default.ts-fixture
  packages/@aws-cdk/aws-pipes-enrichments-alpha/test/__snapshots__/lambda.test.ts.snap
  packages/@aws-cdk/aws-pipes-enrichments-alpha/test/integ.lambda.js.snapshot/asset.3f0f15596be1e3fbbf4a0571522aa1e5312d44abff27360f8d043c1b0704bcf4.bundle/index.js
  packages/@aws-cdk/aws-pipes-enrichments-alpha/test/integ.lambda.js.snapshot/aws-cdk-pipes-enrichments-lambda.assets.json
  packages/@aws-cdk/aws-pipes-enrichments-alpha/test/integ.lambda.js.snapshot/aws-cdk-pipes-enrichments-lambda.template.json
  packages/@aws-cdk/aws-pipes-enrichments-alpha/test/integ.lambda.js.snapshot/cdk.out
  packages/@aws-cdk/aws-pipes-enrichments-alpha/test/integ.lambda.js.snapshot/integ.json
  packages/@aws-cdk/aws-pipes-enrichments-alpha/test/integ.lambda.js.snapshot/integtestpipeenrichmentslambdaDefaultTestDeployAssert88DF3044.assets.json
  packages/@aws-cdk/aws-pipes-enrichments-alpha/test/integ.lambda.js.snapshot/integtestpipeenrichmentslambdaDefaultTestDeployAssert88DF3044.template.json
  packages/@aws-cdk/aws-pipes-enrichments-alpha/test/integ.lambda.js.snapshot/manifest.json
  packages/@aws-cdk/aws-pipes-enrichments-alpha/test/integ.lambda.js.snapshot/tree.json
  packages/@aws-cdk/aws-pipes-enrichments-alpha/test/integ.lambda.ts
  packages/@aws-cdk/aws-pipes-enrichments-alpha/test/lambda.test.ts
  packages/@aws-cdk/aws-pipes-enrichments-alpha/test/test-classes.ts
  packages/@aws-cdk/aws-pipes-enrichments-alpha/tsconfig.dev.json
Labels: p2, repeat-contributor

#28978 feat(app-staging-synthesizer-alpha): require passing `stagingBucketEncryption` and note that we intend to default to `S3_MANAGED` in the future
  packages/@aws-cdk/app-staging-synthesizer-alpha/README.md
  packages/@aws-cdk/app-staging-synthesizer-alpha/lib/default-staging-stack.ts
  packages/@aws-cdk/app-staging-synthesizer-alpha/test/app-staging-synthesizer.test.ts
  packages/@aws-cdk/app-staging-synthesizer-alpha/test/bootstrap-roles.test.ts
  packages/@aws-cdk/app-staging-synthesizer-alpha/test/default-staging-stack.test.ts
  packages/@aws-cdk/app-staging-synthesizer-alpha/test/integ.synth-default-resources.ts
  packages/@aws-cdk/app-staging-synthesizer-alpha/test/per-env-staging-factory.test.ts
Labels: p2, pr-linter/exempt-integ-test, admired-contributor

#28782 fix(appconfig): deployment recreated on every cdk deployment
  packages/@aws-cdk/aws-appconfig-alpha/lib/configuration.ts
  packages/@aws-cdk/aws-appconfig-alpha/test/integ.configuration.js.snapshot/.cache/e976a796f036a5efbf44b99e44cfb5a961df08d8dbf7cd37e60bf216fb982a00.zip
  packages/@aws-cdk/aws-appconfig-alpha/test/integ.configuration.js.snapshot/appconfigconfigurationDefaultTestDeployAssert6752CD38.assets.json
  packages/@aws-cdk/aws-appconfig-alpha/test/integ.configuration.js.snapshot/aws-appconfig-configuration.assets.json
  packages/@aws-cdk/aws-appconfig-alpha/test/integ.configuration.js.snapshot/aws-appconfig-configuration.template.json
  packages/@aws-cdk/aws-appconfig-alpha/test/integ.configuration.js.snapshot/cdk.out
  packages/@aws-cdk/aws-appconfig-alpha/test/integ.configuration.js.snapshot/integ.json
  packages/@aws-cdk/aws-appconfig-alpha/test/integ.configuration.js.snapshot/manifest.json
  packages/@aws-cdk/aws-appconfig-alpha/test/integ.configuration.js.snapshot/tree.json
  packages/@aws-cdk/aws-appconfig-alpha/test/integ.extension.js.snapshot/aws-appconfig-extension.assets.json
  packages/@aws-cdk/aws-appconfig-alpha/test/integ.extension.js.snapshot/aws-appconfig-extension.template.json
  packages/@aws-cdk/aws-appconfig-alpha/test/integ.extension.js.snapshot/awsappconfigextensionMyApplicationappconfigextensionDefaultTestDeployAssert64BA6C4E.assets.json
  packages/@aws-cdk/aws-appconfig-alpha/test/integ.extension.js.snapshot/cdk.out
  packages/@aws-cdk/aws-appconfig-alpha/test/integ.extension.js.snapshot/integ.json
  packages/@aws-cdk/aws-appconfig-alpha/test/integ.extension.js.snapshot/manifest.json
  packages/@aws-cdk/aws-appconfig-alpha/test/integ.extension.js.snapshot/tree.json
Labels: p2, pr-linter/exempt-integ-test, distinguished-contributor

#29110 chore(rds): add Aurora Postgres engine version 16.1
  packages/aws-cdk-lib/aws-rds/lib/cluster-engine.ts
Labels: p2, pr/needs-community-review, beginning-contributor

#29115 chore(merge-back): 2.128.0
  CHANGELOG.v2.alpha.md
  CHANGELOG.v2.md
  version.v2.json
Labels: p2, pr/needs-community-review, pr/no-squash, auto-approve

#29114 chore(ec2): correct device name in BastionHostLinux example
  packages/aws-cdk-lib/aws-ec2/README.md
Labels: bug, p2, pr/needs-community-review, effort/medium, star-contributor

#29069 feat(events-targets): `launchType` property for ECS task
  packages/@aws-cdk-testing/framework-integ/test/aws-events-targets/test/ecs/integ.event-fargate-task.js.snapshot/EcsFargateTestDefaultTestDeployAssert36341BFB.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-events-targets/test/ecs/integ.event-fargate-task.js.snapshot/aws-ecs-integ-fargate.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-events-targets/test/ecs/integ.event-fargate-task.js.snapshot/aws-ecs-integ-fargate.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-events-targets/test/ecs/integ.event-fargate-task.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-events-targets/test/ecs/integ.event-fargate-task.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-events-targets/test/ecs/integ.event-fargate-task.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-events-targets/test/ecs/integ.event-fargate-task.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-events-targets/test/ecs/integ.event-fargate-task.ts
  packages/aws-cdk-lib/aws-events-targets/README.md
  packages/aws-cdk-lib/aws-events-targets/lib/ecs-task.ts
  packages/aws-cdk-lib/aws-events-targets/test/ecs/event-rule-target.test.ts
Labels: p2, feature-request, effort/medium, distinguished-contributor

#29101 feat(cloudfront-origin): adding FunctionUrlOrigin
  packages/@aws-cdk-testing/framework-integ/test/aws-cloudfront-origins/test/integ.function-url-origin.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-cloudfront-origins/test/integ.function-url-origin.js.snapshot/integ-cloudfront-function-url-origin.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-cloudfront-origins/test/integ.function-url-origin.js.snapshot/integ-cloudfront-function-url-origin.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-cloudfront-origins/test/integ.function-url-origin.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-cloudfront-origins/test/integ.function-url-origin.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-cloudfront-origins/test/integ.function-url-origin.js.snapshot/restapioriginDefaultTestDeployAssert6BBA15BA.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-cloudfront-origins/test/integ.function-url-origin.js.snapshot/restapioriginDefaultTestDeployAssert6BBA15BA.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-cloudfront-origins/test/integ.function-url-origin.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-cloudfront-origins/test/integ.function-url-origin.ts
  packages/aws-cdk-lib/aws-cloudfront-origins/README.md
  packages/aws-cdk-lib/aws-cloudfront-origins/lib/function-url-origin.ts
  packages/aws-cdk-lib/aws-cloudfront-origins/lib/index.ts
  packages/aws-cdk-lib/aws-cloudfront-origins/test/function-url-origin.test.ts
Labels: p2, distinguished-contributor

#29085 feat(ecs): credentialSpecs in ContainerDefinitionOptions
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs/test/integ.task-definition-container-credentialspecs.js.snapshot/TaskDefinitionContainerCredSpecsDefaultTestDeployAssertF6677424.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs/test/integ.task-definition-container-credentialspecs.js.snapshot/TaskDefinitionContainerCredSpecsDefaultTestDeployAssertF6677424.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs/test/integ.task-definition-container-credentialspecs.js.snapshot/aws-ecs-task-definition-container-credentialspecs.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs/test/integ.task-definition-container-credentialspecs.js.snapshot/aws-ecs-task-definition-container-credentialspecs.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs/test/integ.task-definition-container-credentialspecs.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs/test/integ.task-definition-container-credentialspecs.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs/test/integ.task-definition-container-credentialspecs.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs/test/integ.task-definition-container-credentialspecs.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs/test/integ.task-definition-container-credentialspecs.ts
  packages/aws-cdk-lib/aws-ecs/README.md
  packages/aws-cdk-lib/aws-ecs/lib/container-definition.ts
  packages/aws-cdk-lib/aws-ecs/lib/credential-spec.ts
  packages/aws-cdk-lib/aws-ecs/lib/index.ts
  packages/aws-cdk-lib/aws-ecs/test/container-definition.test.ts
  packages/aws-cdk-lib/aws-ecs/test/credential-spec.test.ts
Labels: p2, beginning-contributor

#29156 chore: mergify.yml cleanup
  .mergify.yml
Labels: p2, contribution/core, pr/needs-maintainer-review

#29153 refactor(ecs-patterns): organize hierarchy of describe in tests
  packages/aws-cdk-lib/aws-ecs-patterns/test/fargate/load-balanced-fargate-service-v2.test.ts
  packages/aws-cdk-lib/aws-ecs-patterns/test/fargate/load-balanced-fargate-service.test.ts
Labels: p2, repeat-contributor

#29166 feat(rds): support Aurora MySQL 3.05.2
  packages/aws-cdk-lib/aws-rds/lib/cluster-engine.ts
Labels: p2, pr-linter/exempt-readme, pr-linter/exempt-test, pr-linter/exempt-integ-test, repeat-contributor

#29170 refactor(ecs-patterns): organize tests
  packages/aws-cdk-lib/aws-ecs-patterns/test/ec2/l3s-v2.test.ts
  packages/aws-cdk-lib/aws-ecs-patterns/test/ec2/l3s.test.ts
  packages/aws-cdk-lib/aws-ecs-patterns/test/fargate/load-balanced-fargate-service-v2.test.ts
  packages/aws-cdk-lib/aws-ecs-patterns/test/fargate/load-balanced-fargate-service.test.ts
Labels: p2, repeat-contributor

#29144 feat(sns): enforce ssl with topic policy
  packages/@aws-cdk-testing/framework-integ/test/aws-sns/test/integ.sns-topic-policy.js.snapshot/SNSTopicPolicyIntegDefaultTestDeployAssert005CA6BA.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-sns/test/integ.sns-topic-policy.js.snapshot/SNSTopicPolicyIntegDefaultTestDeployAssert005CA6BA.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-sns/test/integ.sns-topic-policy.js.snapshot/SNSTopicPolicyStack.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-sns/test/integ.sns-topic-policy.js.snapshot/SNSTopicPolicyStack.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-sns/test/integ.sns-topic-policy.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-sns/test/integ.sns-topic-policy.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-sns/test/integ.sns-topic-policy.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-sns/test/integ.sns-topic-policy.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-sns/test/integ.sns-topic-policy.ts
  packages/aws-cdk-lib/aws-sns/README.md
  packages/aws-cdk-lib/aws-sns/lib/policy.ts
  packages/aws-cdk-lib/aws-sns/lib/topic-base.ts
  packages/aws-cdk-lib/aws-sns/lib/topic.ts
  packages/aws-cdk-lib/aws-sns/test/sns.test.ts
Labels: p2, feature-request, pr/needs-community-review, star-contributor

#29178 feat(lambda): adding .net 8 (dotnet8) lambda runtime support
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda/test/dotnet-handler/handler.cs
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda/test/integ.runtimes.js.snapshot/asset.a328343cb12aa16bf2c12bfa98f28509923cf8a0e9771cccbbe967d9e15c08f6/handler.cs
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda/test/integ.runtimes.js.snapshot/aws-cdk-lambda-runtime-management.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda/test/integ.runtimes.js.snapshot/aws-cdk-lambda-runtime-management.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda/test/integ.runtimes.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda/test/integ.runtimes.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda/test/integ.runtimes.js.snapshot/lambdaruntimemanagementDefaultTestDeployAssertDE680AF3.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda/test/integ.runtimes.js.snapshot/lambdaruntimemanagementDefaultTestDeployAssertDE680AF3.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda/test/integ.runtimes.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda/test/integ.runtimes.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda/test/integ.runtimes.ts
  packages/aws-cdk-lib/aws-lambda/lib/runtime.ts
Labels: p2, contribution/core, pr-linter/exempt-readme

#29171 fix(appconfig): scope generated alarm role policy to '*' for composite alarm support
  packages/@aws-cdk/aws-appconfig-alpha/lib/environment.ts
  packages/@aws-cdk/aws-appconfig-alpha/test/environment.test.ts
  packages/@aws-cdk/aws-appconfig-alpha/test/integ.environment.js.snapshot/appconfigenvironmentDefaultTestDeployAssert75BD28E7.assets.json
  packages/@aws-cdk/aws-appconfig-alpha/test/integ.environment.js.snapshot/aws-appconfig-environment.assets.json
  packages/@aws-cdk/aws-appconfig-alpha/test/integ.environment.js.snapshot/aws-appconfig-environment.template.json
  packages/@aws-cdk/aws-appconfig-alpha/test/integ.environment.js.snapshot/cdk.out
  packages/@aws-cdk/aws-appconfig-alpha/test/integ.environment.js.snapshot/integ.json
  packages/@aws-cdk/aws-appconfig-alpha/test/integ.environment.js.snapshot/manifest.json
  packages/@aws-cdk/aws-appconfig-alpha/test/integ.environment.js.snapshot/tree.json
  packages/@aws-cdk/aws-appconfig-alpha/test/integ.environment.ts
Labels: p2, pr/needs-community-review, pr-linter/exempt-integ-test, admired-contributor

#28928 feat(lambda): Add `Ipv6AllowedforDualStack` support for Lambda function
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda/test/integ.lambda_with_dualStack_vpc.js.snapshot/DualStackTestingDefaultTestDeployAssert8ACBFB2C.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda/test/integ.lambda_with_dualStack_vpc.js.snapshot/DualStackTestingDefaultTestDeployAssert8ACBFB2C.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda/test/integ.lambda_with_dualStack_vpc.js.snapshot/DualStackVpc.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda/test/integ.lambda_with_dualStack_vpc.js.snapshot/DualStackVpc.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda/test/integ.lambda_with_dualStack_vpc.js.snapshot/asset.4554b47be6f57b68c6c7a7391dcc73894866d2377fe174883351e7639097f292/__entrypoint__.js
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda/test/integ.lambda_with_dualStack_vpc.js.snapshot/asset.4554b47be6f57b68c6c7a7391dcc73894866d2377fe174883351e7639097f292/index.js
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda/test/integ.lambda_with_dualStack_vpc.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda/test/integ.lambda_with_dualStack_vpc.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda/test/integ.lambda_with_dualStack_vpc.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda/test/integ.lambda_with_dualStack_vpc.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda/test/integ.lambda_with_dualStack_vpc.ts
  packages/aws-cdk-lib/aws-lambda/README.md
  packages/aws-cdk-lib/aws-lambda/lib/function.ts
  packages/aws-cdk-lib/aws-lambda/test/function.test.ts
Labels: p2, pr/needs-community-review, beginning-contributor

#29201 chore(eks): add private cluster reference link
  packages/aws-cdk-lib/aws-eks/README.md
Labels: p2, contribution/core, pr/needs-maintainer-review

#29202 chore(opensearch): improve the doc about disabling the logging
  packages/aws-cdk-lib/aws-opensearchservice/lib/domain.ts
Labels: bug, p2, effort/medium, contribution/core

#29206 chore(merge-back): 2.129.0
  CHANGELOG.v2.alpha.md
  CHANGELOG.v2.md
  version.v2.json
Labels: p2, pr/needs-community-review, pr/no-squash, auto-approve

#29210 feat(bedrock): stabilityai model
  packages/aws-cdk-lib/aws-bedrock/lib/foundation-model.ts
Labels: p2, pr-linter/exempt-readme, pr-linter/exempt-test, pr-linter/exempt-integ-test, distinguished-contributor

#29226 chore(appconfig): compilation error in ts 4.2 and below because of using get in interface
  packages/aws-cdk-lib/aws-appconfig/lib/application.ts
  packages/aws-cdk-lib/aws-appconfig/lib/configuration.ts
Labels: p2, contribution/core, pr-linter/exempt-test, pr-linter/exempt-integ-test

#28599 fix(custom-resources-handlers): s3 deployment handler log injection vulnerability
  packages/@aws-cdk-testing/framework-integ/test/aws-codepipeline-actions/test/integ.pipeline-elastic-beanstalk-deploy.js.snapshot/aws-cdk-codepipeline-elastic-beanstalk-deploy.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-codepipeline-actions/test/integ.pipeline-elastic-beanstalk-deploy.js.snapshot/aws-cdk-codepipeline-elastic-beanstalk-deploy.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-codepipeline-actions/test/integ.pipeline-elastic-beanstalk-deploy.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-dynamodb/test/integ.import-source.js.snapshot/S3Stack.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-dynamodb/test/integ.import-source.js.snapshot/S3Stack.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-dynamodb/test/integ.import-source.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs/test/ec2/integ.environment-file.js.snapshot/aws-ecs-integ.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs/test/ec2/integ.environment-file.js.snapshot/aws-ecs-integ.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs/test/ec2/integ.environment-file.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-s3-deployment/test/integ.bucket-deployment-cloudfront.js.snapshot/test-bucket-deployments-1.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-s3-deployment/test/integ.bucket-deployment-cloudfront.js.snapshot/test-bucket-deployments-1.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-s3-deployment/test/integ.bucket-deployment-cloudfront.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-s3-deployment/test/integ.bucket-deployment-deployed-bucket.js.snapshot/test-bucket-deployment-deployed-bucket.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-s3-deployment/test/integ.bucket-deployment-deployed-bucket.js.snapshot/test-bucket-deployment-deployed-bucket.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-s3-deployment/test/integ.bucket-deployment-deployed-bucket.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-s3-deployment/test/integ.bucket-deployment-signcontent.js.snapshot/test-bucket-deployment-signobject.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-s3-deployment/test/integ.bucket-deployment-signcontent.js.snapshot/test-bucket-deployment-signobject.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-s3-deployment/test/integ.bucket-deployment-signcontent.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-s3-deployment/test/integ.bucket-deployment.js.snapshot/test-bucket-deployments-2.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-s3-deployment/test/integ.bucket-deployment.js.snapshot/test-bucket-deployments-2.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-s3-deployment/test/integ.bucket-deployment.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-servicecatalog/test/integ.product.js.snapshot/integ-servicecatalog-product.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-servicecatalog/test/integ.product.js.snapshot/integ-servicecatalog-product.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-servicecatalog/test/integ.product.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-servicecatalog/test/integ.two-products.js.snapshot/integ-servicecatalog-two-products.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-servicecatalog/test/integ.two-products.js.snapshot/integ-servicecatalog-two-products.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-servicecatalog/test/integ.two-products.js.snapshot/tree.json
  packages/@aws-cdk/aws-appconfig-alpha/test/integ.configuration.js.snapshot/aws-appconfig-configuration.assets.json
  packages/@aws-cdk/aws-appconfig-alpha/test/integ.configuration.js.snapshot/aws-appconfig-configuration.template.json
  packages/@aws-cdk/aws-appconfig-alpha/test/integ.configuration.js.snapshot/tree.json
  packages/@aws-cdk/custom-resource-handlers/lib/aws-s3-deployment/bucket-deployment-handler/index.py
  packages/@aws-cdk/custom-resource-handlers/test/aws-s3-deployment/bucket-deployment-handler/test.py
Labels: bug, p1, effort/small, pr-linter/exempt-integ-test, distinguished-contributor, pr-linter/exemption-requested, pr/needs-maintainer-review

#29230 chore(merge-back): 2.130.0
  CHANGELOG.v2.alpha.md
  CHANGELOG.v2.md
  version.v2.json
Labels: p2, pr/needs-community-review, pr/no-squash, auto-approve

#29150 feat(core): add `description` to `exportValue` and `exportStringListValue` methods
  packages/@aws-cdk-testing/framework-integ/test/core/test/integ.stack.js.snapshot/Stack.assets.json
  packages/@aws-cdk-testing/framework-integ/test/core/test/integ.stack.js.snapshot/Stack.template.json
  packages/@aws-cdk-testing/framework-integ/test/core/test/integ.stack.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/core/test/integ.stack.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/core/test/integ.stack.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/core/test/integ.stack.js.snapshot/stackDefaultTestDeployAssert0386B0AD.assets.json
  packages/@aws-cdk-testing/framework-integ/test/core/test/integ.stack.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/core/test/integ.stack.ts
  packages/aws-cdk-lib/core/README.md
  packages/aws-cdk-lib/core/lib/stack.ts
  packages/aws-cdk-lib/core/test/stack.test.ts
Labels: p2, feature-request, effort/medium, distinguished-contributor

#29223 fix(CLI): sam resources hidden in changeset diffs
  packages/@aws-cdk/cloudformation-diff/lib/diff-template.ts
  packages/@aws-cdk/cloudformation-diff/test/diff-template.test.ts
Labels: bug, p1, effort/medium, contribution/core, pr-linter/exempt-integ-test

#29064 feat(appsync): `environmentVariables` property for GraphqlApi
  packages/@aws-cdk-testing/framework-integ/test/aws-appsync/test/integ.environment-variables.js.snapshot/AppSyncEnvironmentVariables.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-appsync/test/integ.environment-variables.js.snapshot/AppSyncEnvironmentVariables.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-appsync/test/integ.environment-variables.js.snapshot/IntegTestEnvironmentVariablesDefaultTestDeployAssertCD36F8FC.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-appsync/test/integ.environment-variables.js.snapshot/IntegTestEnvironmentVariablesDefaultTestDeployAssertCD36F8FC.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-appsync/test/integ.environment-variables.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-appsync/test/integ.environment-variables.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-appsync/test/integ.environment-variables.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-appsync/test/integ.environment-variables.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-appsync/test/integ.environment-variables.ts
  packages/aws-cdk-lib/aws-appsync/README.md
  packages/aws-cdk-lib/aws-appsync/lib/graphqlapi.ts
  packages/aws-cdk-lib/aws-appsync/test/appsync-environment-variables.test.ts
Labels: p2, distinguished-contributor

#29267 fix(stepfunctions): escaped curly braces result in error during state machine execution
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions/test/integ.intrinsics.js.snapshot/StateMachineIntrinsicsTestDefaultTestDeployAssert1C1E1D7E.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions/test/integ.intrinsics.js.snapshot/StateMachineIntrinsicsTestDefaultTestDeployAssert1C1E1D7E.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions/test/integ.intrinsics.js.snapshot/asset.ac51674cf5325b7a0e5444d6b7c1f88607c16a031b852bd51c375ac8c5c4fce5.bundle/index.js
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions/test/integ.intrinsics.js.snapshot/aws-stepfunctions-intrinsics-integ.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions/test/integ.intrinsics.js.snapshot/aws-stepfunctions-intrinsics-integ.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions/test/integ.intrinsics.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions/test/integ.intrinsics.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions/test/integ.intrinsics.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions/test/integ.intrinsics.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions/test/integ.intrinsics.ts
  packages/aws-cdk-lib/aws-stepfunctions/lib/private/json-path.ts
  packages/aws-cdk-lib/aws-stepfunctions/test/private/json-path.test.ts
Labels: bug, p2, pr/needs-community-review, admired-contributor

#29255 chore(cognito): fix grammar in UserPool IDP docstrings
  packages/aws-cdk-lib/aws-cognito/lib/user-pool-idps/amazon.ts
  packages/aws-cdk-lib/aws-cognito/lib/user-pool-idps/apple.ts
  packages/aws-cdk-lib/aws-cognito/lib/user-pool-idps/facebook.ts
  packages/aws-cdk-lib/aws-cognito/lib/user-pool-idps/google.ts
  packages/aws-cdk-lib/aws-cognito/lib/user-pool-idps/oidc.ts
  packages/aws-cdk-lib/aws-cognito/lib/user-pool-idps/saml.ts
Labels: p2, pr/needs-community-review, valued-contributor

#29283 chore(eks): improve the doc on updating clusters
  packages/aws-cdk-lib/aws-eks/README.md
Labels: bug, p1, effort/medium, contribution/core

#28982 feat(apigatewayv2-integrations): stepfunctions integration
  packages/@aws-cdk-testing/framework-integ/test/aws-apigatewayv2-integrations/test/http/integ.stepfunctions.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-apigatewayv2-integrations/test/http/integ.stepfunctions.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-apigatewayv2-integrations/test/http/integ.stepfunctions.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-apigatewayv2-integrations/test/http/integ.stepfunctions.js.snapshot/stepfunctions-integration.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-apigatewayv2-integrations/test/http/integ.stepfunctions.js.snapshot/stepfunctions-integration.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-apigatewayv2-integrations/test/http/integ.stepfunctions.js.snapshot/stepfunctionsintegrationintegtestDefaultTestDeployAssert09AC4C77.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-apigatewayv2-integrations/test/http/integ.stepfunctions.js.snapshot/stepfunctionsintegrationintegtestDefaultTestDeployAssert09AC4C77.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-apigatewayv2-integrations/test/http/integ.stepfunctions.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-apigatewayv2-integrations/test/http/integ.stepfunctions.ts
  packages/aws-cdk-lib/aws-apigatewayv2-integrations/README.md
  packages/aws-cdk-lib/aws-apigatewayv2-integrations/lib/http/index.ts
  packages/aws-cdk-lib/aws-apigatewayv2-integrations/lib/http/stepfunctions.ts
  packages/aws-cdk-lib/aws-apigatewayv2-integrations/test/http/stepfunctions.test.ts
Labels: bug, p2, pr/needs-community-review, effort/medium, star-contributor

#29158 fix(autoscaling): step scaling without adjustment type fails
  packages/@aws-cdk-testing/framework-integ/test/aws-autoscaling/test/integ.asg-step-scaling.js.snapshot/autoscaling-step-scaling.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-autoscaling/test/integ.asg-step-scaling.js.snapshot/autoscaling-step-scaling.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-autoscaling/test/integ.asg-step-scaling.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-autoscaling/test/integ.asg-step-scaling.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-autoscaling/test/integ.asg-step-scaling.ts
  packages/aws-cdk-lib/aws-autoscaling/lib/step-scaling-policy.ts
  packages/aws-cdk-lib/aws-autoscaling/test/scaling.test.ts
Labels: p2, distinguished-contributor, pr-linter/exemption-requested

#29303 chore: move github actions to cdklabs
  .github/workflows/close-stale-prs.yml
  .github/workflows/github-merit-badger.yml
  .github/workflows/issue-reprioritization.yml
  .github/workflows/pr-labeler.yml
  .github/workflows/pr-linter-exemption-labeler.yml
Labels: p2, contribution/core

#29244 fix(ecs): `autoscalingGroup` attribute does not exist on `ImportedCluster`
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs/test/integ.cluster-imported.js.snapshot/ClusterImportedDefaultTestDeployAssert8B67C7A2.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs/test/integ.cluster-imported.js.snapshot/ClusterImportedDefaultTestDeployAssert8B67C7A2.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs/test/integ.cluster-imported.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs/test/integ.cluster-imported.js.snapshot/integ-ecs-imported-cluster.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs/test/integ.cluster-imported.js.snapshot/integ-ecs-imported-cluster.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs/test/integ.cluster-imported.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs/test/integ.cluster-imported.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs/test/integ.cluster-imported.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs/test/integ.cluster-imported.ts
  packages/aws-cdk-lib/aws-ecs/lib/cluster.ts
  packages/aws-cdk-lib/aws-ecs/test/cluster.test.ts
Labels: bug, p2, star-contributor

#29305 fix(cli-integ): use `Python_3_12` instead of `Python_3_7` lambda runtime
  packages/@aws-cdk-testing/cli-integ/resources/cdk-apps/sam_cdk_integ_app/lib/nested-stack.js
  packages/@aws-cdk-testing/cli-integ/resources/cdk-apps/sam_cdk_integ_app/lib/test-stack.js
Labels: p2, contribution/core, pr-linter/exempt-integ-test

#29242 fix(cloudtrail): isOrganizationTrail attaches insufficient permissions to bucket
  packages/aws-cdk-lib/aws-cloudtrail/lib/cloudtrail.ts
  packages/aws-cdk-lib/aws-cloudtrail/test/cloudtrail.test.ts
Labels: bug, p1, effort/small, contribution/core, pr-linter/exempt-integ-test, pr-linter/exemption-requested

#28798 feat(docdb): support snapshot removal policy
  packages/@aws-cdk-testing/framework-integ/test/aws-docdb/test/integ.cluster-removal-policy-snapshot.js.snapshot/aws-cdk-docdb-removal-policy-snapshot-stack.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-docdb/test/integ.cluster-removal-policy-snapshot.js.snapshot/aws-cdk-docdb-removal-policy-snapshot-stack.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-docdb/test/integ.cluster-removal-policy-snapshot.js.snapshot/awscdkdocdbremovalpolicysnapshotintegDefaultTestDeployAssertF3753098.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-docdb/test/integ.cluster-removal-policy-snapshot.js.snapshot/awscdkdocdbremovalpolicysnapshotintegDefaultTestDeployAssertF3753098.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-docdb/test/integ.cluster-removal-policy-snapshot.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-docdb/test/integ.cluster-removal-policy-snapshot.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-docdb/test/integ.cluster-removal-policy-snapshot.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-docdb/test/integ.cluster-removal-policy-snapshot.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-docdb/test/integ.cluster-removal-policy-snapshot.ts
  packages/aws-cdk-lib/aws-docdb/README.md
  packages/aws-cdk-lib/aws-docdb/lib/cluster.ts
  packages/aws-cdk-lib/aws-docdb/test/cluster.test.ts
  packages/aws-cdk-lib/core/lib/cfn-resource.ts
  packages/aws-cdk-lib/core/test/cfn-resource.test.ts
  packages/aws-cdk-lib/rosetta/aws_docdb/default.ts-fixture
Labels: bug, p1, effort/medium, distinguished-contributor, pr-linter/exemption-requested

#29313 fix(cli-integ): add regression patch for cli integ fix
  packages/@aws-cdk-testing/cli-integ/.gitignore
  packages/@aws-cdk-testing/cli-integ/resources/cli-regression-patches/v2.130.0/NOTES.md
  packages/@aws-cdk-testing/cli-integ/resources/cli-regression-patches/v2.130.0/node_modules/@aws-cdk-testing/cli-integ/resources/cdk-apps/sam_cdk_integ_app/lib/nested-stack.js
  packages/@aws-cdk-testing/cli-integ/resources/cli-regression-patches/v2.130.0/node_modules/@aws-cdk-testing/cli-integ/resources/cdk-apps/sam_cdk_integ_app/lib/test-stack.js
Labels: p2, contribution/core, pr-linter/exempt-test, pr-linter/exempt-integ-test, pr/needs-maintainer-review

#29287 docs(events): mention property requirements when creating custom events
  packages/aws-cdk-lib/aws-events/lib/event-pattern.ts
Labels: p2, pr/needs-community-review, beginning-contributor

#29133 chore(rds): add clusterArn property to DatabaseCluster
  packages/aws-cdk-lib/aws-rds/lib/cluster-ref.ts
  packages/aws-cdk-lib/aws-rds/lib/cluster.ts
  packages/aws-cdk-lib/aws-rds/test/cluster.test.ts
Labels: p2, pr/needs-community-review, beginning-contributor

#29320 fix(cli): add skip-tests.txt file for v2.130.0
  packages/@aws-cdk-testing/cli-integ/resources/cli-regression-patches/v2.130.0/skip-tests.txt
Labels: p2, contribution/core, pr-linter/exempt-test, pr-linter/exempt-integ-test

#28728 feat(ec2): support for the credit configuration mode for burstable instances
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.instance-credit.js.snapshot/asset.4554b47be6f57b68c6c7a7391dcc73894866d2377fe174883351e7639097f292/__entrypoint__.js
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.instance-credit.js.snapshot/asset.4554b47be6f57b68c6c7a7391dcc73894866d2377fe174883351e7639097f292/index.js
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.instance-credit.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.instance-credit.js.snapshot/instancetestDefaultTestDeployAssert5516EAF1.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.instance-credit.js.snapshot/instancetestDefaultTestDeployAssert5516EAF1.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.instance-credit.js.snapshot/integ-ec2-instance-credit.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.instance-credit.js.snapshot/integ-ec2-instance-credit.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.instance-credit.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.instance-credit.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.instance-credit.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.instance-credit.ts
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.nat-instance-credit.js.snapshot/asset.4554b47be6f57b68c6c7a7391dcc73894866d2377fe174883351e7639097f292/__entrypoint__.js
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.nat-instance-credit.js.snapshot/asset.4554b47be6f57b68c6c7a7391dcc73894866d2377fe174883351e7639097f292/index.js
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.nat-instance-credit.js.snapshot/aws-cdk-vpc-nat-instance-credit.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.nat-instance-credit.js.snapshot/aws-cdk-vpc-nat-instance-credit.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.nat-instance-credit.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.nat-instance-credit.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.nat-instance-credit.js.snapshot/integtestDefaultTestDeployAssert24D5C536.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.nat-instance-credit.js.snapshot/integtestDefaultTestDeployAssert24D5C536.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.nat-instance-credit.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.nat-instance-credit.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.nat-instance-credit.ts
  packages/aws-cdk-lib/aws-ec2/README.md
  packages/aws-cdk-lib/aws-ec2/lib/instance-types.ts
  packages/aws-cdk-lib/aws-ec2/lib/instance.ts
  packages/aws-cdk-lib/aws-ec2/lib/nat.ts
  packages/aws-cdk-lib/aws-ec2/test/instance.test.ts
  packages/aws-cdk-lib/aws-ec2/test/vpc.test.ts
Labels: p2, feature-request, effort/small, admired-contributor, pr/needs-maintainer-review
