Repository aws/aws-cdk, pull requests merged in 2024-03, with the labels that each got.

#29235 fix(ecs): stack name can result in noncompliant capacity provider name
  packages/aws-cdk-lib/aws-ecs/lib/cluster.ts
  packages/aws-cdk-lib/aws-ecs/test/cluster.test.ts
Labels: bug, p2, effort/medium, pr-linter/exempt-integ-test, star-contributor, pr-linter/exemption-requested

#29324 chore: update Contributors File
  CONTRIBUTORS.md
Labels: p2, auto-approve

#28607 fix(ec2): internet gateway is created even if public subnets are reserved
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.reserved-public-subnet.js.snapshot/asset.4554b47be6f57b68c6c7a7391dcc73894866d2377fe174883351e7639097f292/__entrypoint__.js
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.reserved-public-subnet.js.snapshot/asset.4554b47be6f57b68c6c7a7391dcc73894866d2377fe174883351e7639097f292/index.js
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.reserved-public-subnet.js.snapshot/aws-cdk-ec2-vpc-reserved-public-subnet.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.reserved-public-subnet.js.snapshot/aws-cdk-ec2-vpc-reserved-public-subnet.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.reserved-public-subnet.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.reserved-public-subnet.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.reserved-public-subnet.js.snapshot/integawscdkec2vpcreservedpublicsubnetDefaultTestDeployAssert469B3DFB.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.reserved-public-subnet.js.snapshot/integawscdkec2vpcreservedpublicsubnetDefaultTestDeployAssert469B3DFB.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.reserved-public-subnet.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.reserved-public-subnet.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.reserved-public-subnet.ts
  packages/aws-cdk-lib/aws-ec2/lib/vpc.ts
  packages/aws-cdk-lib/aws-ec2/test/vpc.test.ts
Labels: bug, p2, effort/medium, distinguished-contributor

#29066 feat(applicationautoscaling): add missing PredefinedMetricType enum values
  packages/aws-cdk-lib/aws-applicationautoscaling/README.md
  packages/aws-cdk-lib/aws-applicationautoscaling/lib/target-tracking-scaling-policy.ts
  packages/aws-cdk-lib/aws-applicationautoscaling/test/target-tracking.test.ts
Labels: p2, feature-request, effort/medium, pr-linter/exempt-integ-test, star-contributor, pr-linter/exemption-requested, pr/needs-maintainer-review

#29332 chore: add some debugging to regression test skipping
  packages/@aws-cdk-testing/cli-integ/bin/apply-patches
  packages/@aws-cdk-testing/cli-integ/lib/integ-test.ts
Labels: p2, contribution/core, pr/needs-maintainer-review

#29335 chore(eks): support Amazon Linux 2023
  packages/aws-cdk-lib/aws-eks/lib/managed-nodegroup.ts
Labels: p2, feature-request, contribution/core

#29275 feat(ecs-patterns): allow custom ephemeral storage for ECS Fargate services
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs-patterns/test/fargate/integ.alb-fargate-service-custom-storage.js.snapshot/ApplicationLoadBalancedFargateServiceCustomStorageTestDefaultTestDeployAssertD8C2EA6F.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs-patterns/test/fargate/integ.alb-fargate-service-custom-storage.js.snapshot/ApplicationLoadBalancedFargateServiceCustomStorageTestDefaultTestDeployAssertD8C2EA6F.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs-patterns/test/fargate/integ.alb-fargate-service-custom-storage.js.snapshot/aws-ecs-patterns-alb-with-custom-storage.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs-patterns/test/fargate/integ.alb-fargate-service-custom-storage.js.snapshot/aws-ecs-patterns-alb-with-custom-storage.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs-patterns/test/fargate/integ.alb-fargate-service-custom-storage.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs-patterns/test/fargate/integ.alb-fargate-service-custom-storage.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs-patterns/test/fargate/integ.alb-fargate-service-custom-storage.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs-patterns/test/fargate/integ.alb-fargate-service-custom-storage.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs-patterns/test/fargate/integ.alb-fargate-service-custom-storage.ts
  packages/aws-cdk-lib/aws-ecs-patterns/README.md
  packages/aws-cdk-lib/aws-ecs-patterns/lib/base/fargate-service-base.ts
  packages/aws-cdk-lib/aws-ecs-patterns/lib/fargate/application-load-balanced-fargate-service.ts
  packages/aws-cdk-lib/aws-ecs-patterns/lib/fargate/application-multiple-target-groups-fargate-service.ts
  packages/aws-cdk-lib/aws-ecs-patterns/lib/fargate/network-load-balanced-fargate-service.ts
  packages/aws-cdk-lib/aws-ecs-patterns/lib/fargate/network-multiple-target-groups-fargate-service.ts
  packages/aws-cdk-lib/aws-ecs-patterns/lib/fargate/queue-processing-fargate-service.ts
  packages/aws-cdk-lib/aws-ecs-patterns/lib/fargate/scheduled-fargate-task.ts
  packages/aws-cdk-lib/aws-ecs-patterns/test/fargate/load-balanced-fargate-service-v2.test.ts
  packages/aws-cdk-lib/aws-ecs-patterns/test/fargate/queue-processing-fargate-service.test.ts
  packages/aws-cdk-lib/aws-ecs-patterns/test/fargate/scheduled-fargate-task.test.ts
Labels: p2, feature-request, effort/small, pr/needs-community-review, beginning-contributor

#29130 fix(sqs): `redrivePermission` is set to `byQueue` no matter what value is specified
  packages/@aws-cdk-testing/framework-integ/test/aws-sqs/test/integ.sqs-source-queue-permission.js.snapshot/aws-cdk-sqs.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-sqs/test/integ.sqs-source-queue-permission.ts
  packages/aws-cdk-lib/aws-sqs/lib/queue.ts
  packages/aws-cdk-lib/aws-sqs/test/sqs.test.ts
Labels: bug, p2, effort/small, beginning-contributor

#29341 fix(cloudwatch): allow up to 30 dimensions for metric
  packages/@aws-cdk-testing/framework-integ/test/aws-cloudwatch/test/integ.metric-with-dimensions.js.snapshot/aws-cdk-cloudwatch-metric-dimensions.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-cloudwatch/test/integ.metric-with-dimensions.js.snapshot/aws-cdk-cloudwatch-metric-dimensions.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-cloudwatch/test/integ.metric-with-dimensions.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-cloudwatch/test/integ.metric-with-dimensions.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-cloudwatch/test/integ.metric-with-dimensions.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-cloudwatch/test/integ.metric-with-dimensions.js.snapshot/metricwithdimensionstestDefaultTestDeployAssert1196DF0F.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-cloudwatch/test/integ.metric-with-dimensions.js.snapshot/metricwithdimensionstestDefaultTestDeployAssert1196DF0F.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-cloudwatch/test/integ.metric-with-dimensions.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-cloudwatch/test/integ.metric-with-dimensions.ts
  packages/aws-cdk-lib/aws-cloudwatch/lib/metric.ts
  packages/aws-cdk-lib/aws-cloudwatch/test/metrics.test.ts
Labels: bug, p2, effort/small, pr/needs-community-review, beginning-contributor

#29342 chore(merge-back): 2.131.0
  CHANGELOG.v2.alpha.md
  CHANGELOG.v2.md
  version.v2.json
Labels: p2, pr/needs-community-review, pr/no-squash, auto-approve

#29330 fix(stepfunctions): maxConcurrency does not support JsonPath
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions/test/integ.map-distributed.js.snapshot/cdk-stepfunctions-map-distributed-stack.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions/test/integ.map-distributed.js.snapshot/cdk-stepfunctions-map-distributed-stack.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions/test/integ.map-distributed.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions/test/integ.map-distributed.js.snapshot/cdkstepfunctionsmapdistributedintegDefaultTestDeployAssert69F30423.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions/test/integ.map-distributed.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions/test/integ.map-distributed.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions/test/integ.map-distributed.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions/test/integ.map-distributed.ts
  packages/aws-cdk-lib/aws-stepfunctions/lib/states/map-base.ts
  packages/aws-cdk-lib/aws-stepfunctions/test/map.test.ts
Labels: p2, beginning-contributor

#29344 docs(ecs-patterns): remove references to REMOVE_DEFAULT_DESIRED_COUNT
  packages/aws-cdk-lib/aws-ecs-patterns/README.md
  packages/aws-cdk-lib/aws-ecs-patterns/lib/base/application-load-balanced-service-base.ts
  packages/aws-cdk-lib/aws-ecs-patterns/lib/base/application-multiple-target-groups-service-base.ts
  packages/aws-cdk-lib/aws-ecs-patterns/lib/base/network-load-balanced-service-base.ts
  packages/aws-cdk-lib/aws-ecs-patterns/lib/base/network-multiple-target-groups-service-base.ts
  packages/aws-cdk-lib/aws-ecs-patterns/lib/base/queue-processing-service-base.ts
Labels: p2, beginning-contributor, pr/needs-maintainer-review

#29349 feat: update L1 CloudFormation resource definitions
  packages/@aws-cdk/cloudformation-diff/package.json
  packages/@aws-cdk/integ-runner/package.json
  packages/aws-cdk-lib/package.json
  tools/@aws-cdk/spec2cdk/package.json
  yarn.lock
Labels: p2, dependencies, contribution/core, pr-linter/exempt-readme, pr-linter/exempt-test, auto-approve, pr-linter/exempt-integ-test

#29352 fix(changelog): changelog for v2.131.0 has some errors
  CHANGELOG.v2.md
Labels: p2, contribution/core, pr-linter/exempt-test, pr-linter/exempt-integ-test

#29013 feat(ec2): add NAT instance V2 support using AL2023
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.nat-instances-v2.js.snapshot/aws-cdk-vpc-nat-instances-v2.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.nat-instances-v2.js.snapshot/aws-cdk-vpc-nat-instances-v2.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.nat-instances-v2.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.nat-instances-v2.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.nat-instances-v2.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.nat-instances-v2.js.snapshot/natinstancev2integtestDefaultTestDeployAssertD7458A47.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.nat-instances-v2.js.snapshot/natinstancev2integtestDefaultTestDeployAssertD7458A47.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.nat-instances-v2.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.nat-instances-v2.ts
  packages/aws-cdk-lib/aws-ec2/README.md
  packages/aws-cdk-lib/aws-ec2/lib/nat.ts
  packages/aws-cdk-lib/aws-ec2/test/vpc.test.ts
Labels: bug, p1, effort/medium, contribution/core

#29333 fix(ecs-patterns): resolve not being able to create ECS service in `integ.alb-ecs-service-command-entry-point`
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs-patterns/test/ec2/integ.alb-ecs-service-command-entry-point.js.snapshot/AlbEc2ServiceWithCommandAndEntryPointDefaultTestDeployAssert91EF33D6.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs-patterns/test/ec2/integ.alb-ecs-service-command-entry-point.js.snapshot/aws-ecs-integ-alb-ec2-cmd-entrypoint.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs-patterns/test/ec2/integ.alb-ecs-service-command-entry-point.js.snapshot/aws-ecs-integ-alb-ec2-cmd-entrypoint.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs-patterns/test/ec2/integ.alb-ecs-service-command-entry-point.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs-patterns/test/ec2/integ.alb-ecs-service-command-entry-point.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs-patterns/test/ec2/integ.alb-ecs-service-command-entry-point.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs-patterns/test/ec2/integ.alb-ecs-service-command-entry-point.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs-patterns/test/ec2/integ.alb-ecs-service-command-entry-point.ts
Labels: p2, valued-contributor

#29340 feat(autoscaling): support custom termination policy with lambda
  packages/@aws-cdk-testing/framework-integ/test/aws-autoscaling/test/integ.asg-instance-termination-policy.js.snapshot/InstanceTerminationPolicyTestDefaultTestDeployAssertD453E37E.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-autoscaling/test/integ.asg-instance-termination-policy.js.snapshot/InstanceTerminationPolicyTestDefaultTestDeployAssertD453E37E.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-autoscaling/test/integ.asg-instance-termination-policy.js.snapshot/aws-cdk-autoscaling-instance-termination-policy.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-autoscaling/test/integ.asg-instance-termination-policy.js.snapshot/aws-cdk-autoscaling-instance-termination-policy.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-autoscaling/test/integ.asg-instance-termination-policy.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-autoscaling/test/integ.asg-instance-termination-policy.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-autoscaling/test/integ.asg-instance-termination-policy.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-autoscaling/test/integ.asg-instance-termination-policy.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-autoscaling/test/integ.asg-instance-termination-policy.ts
  packages/aws-cdk-lib/aws-autoscaling/README.md
  packages/aws-cdk-lib/aws-autoscaling/lib/auto-scaling-group.ts
  packages/aws-cdk-lib/aws-autoscaling/lib/termination-policy.ts
  packages/aws-cdk-lib/aws-autoscaling/test/auto-scaling-group.test.ts
Labels: p1, feature-request, effort/small, contribution/core, pr/needs-maintainer-review

#28898 fix(events-targets): ecs:TagResource permission
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs-patterns/test/ec2/integ.scheduled-ecs-task.js.snapshot/aws-ecs-integ-ecs.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs-patterns/test/ec2/integ.scheduled-ecs-task.js.snapshot/aws-ecs-integ-ecs.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs-patterns/test/ec2/integ.scheduled-ecs-task.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs-patterns/test/ec2/integ.scheduled-ecs-task.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs-patterns/test/ec2/integ.scheduled-ecs-task.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs-patterns/test/ec2/integ.scheduled-ecs-task.js.snapshot/scheduledEc2TaskTestDefaultTestDeployAssertF02313CA.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs-patterns/test/ec2/integ.scheduled-ecs-task.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs-patterns/test/fargate/integ.runtime-platform-application-load-balanced-fargate-service.js.snapshot/IntegDefaultTestDeployAssert4E6713E1.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs-patterns/test/fargate/integ.runtime-platform-application-load-balanced-fargate-service.js.snapshot/aws-ecs-runtime-integ.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs-patterns/test/fargate/integ.runtime-platform-application-load-balanced-fargate-service.js.snapshot/aws-ecs-runtime-integ.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs-patterns/test/fargate/integ.runtime-platform-application-load-balanced-fargate-service.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs-patterns/test/fargate/integ.runtime-platform-application-load-balanced-fargate-service.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs-patterns/test/fargate/integ.runtime-platform-application-load-balanced-fargate-service.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs-patterns/test/fargate/integ.runtime-platform-application-load-balanced-fargate-service.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs-patterns/test/fargate/integ.scheduled-fargate-task.js.snapshot/aws-fargate-integ.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs-patterns/test/fargate/integ.scheduled-fargate-task.js.snapshot/aws-fargate-integ.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs-patterns/test/fargate/integ.scheduled-fargate-task.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs-patterns/test/fargate/integ.scheduled-fargate-task.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs-patterns/test/fargate/integ.scheduled-fargate-task.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs-patterns/test/fargate/integ.scheduled-fargate-task.js.snapshot/publicQueueProcessingFargateServiceTestDefaultTestDeployAssertD65416D6.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs-patterns/test/fargate/integ.scheduled-fargate-task.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-events-targets/test/ecs/image-simple/Dockerfile
  packages/@aws-cdk-testing/framework-integ/test/aws-events-targets/test/ecs/image-simple/index.py
  packages/@aws-cdk-testing/framework-integ/test/aws-events-targets/test/ecs/integ.event-ec2-task.js.snapshot/EcsTestDefaultTestDeployAssert8B2741C4.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-events-targets/test/ecs/integ.event-ec2-task.js.snapshot/asset.7a4895bc694ae074467753dddb9a798e58f2f5eda62bcce5833d7d356b8a1da2/Dockerfile
  packages/@aws-cdk-testing/framework-integ/test/aws-events-targets/test/ecs/integ.event-ec2-task.js.snapshot/asset.cb8db1ca45b29cf8a7db558e2cb31ac823252251ae003dc87318f485c6415d2b/Dockerfile
  packages/@aws-cdk-testing/framework-integ/test/aws-events-targets/test/ecs/integ.event-ec2-task.js.snapshot/asset.cb8db1ca45b29cf8a7db558e2cb31ac823252251ae003dc87318f485c6415d2b/index.py
  packages/@aws-cdk-testing/framework-integ/test/aws-events-targets/test/ecs/integ.event-ec2-task.js.snapshot/aws-ecs-integ-ecs.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-events-targets/test/ecs/integ.event-ec2-task.js.snapshot/aws-ecs-integ-ecs.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-events-targets/test/ecs/integ.event-ec2-task.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-events-targets/test/ecs/integ.event-ec2-task.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-events-targets/test/ecs/integ.event-ec2-task.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-events-targets/test/ecs/integ.event-ec2-task.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-events-targets/test/ecs/integ.event-ec2-task.ts
  packages/@aws-cdk-testing/framework-integ/test/aws-events-targets/test/ecs/integ.event-fargate-task.js.snapshot/aws-ecs-integ-fargate.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-events-targets/test/ecs/integ.event-fargate-task.js.snapshot/aws-ecs-integ-fargate.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-events-targets/test/ecs/integ.event-fargate-task.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-events-targets/test/ecs/integ.event-fargate-task.js.snapshot/tree.json
  packages/aws-cdk-lib/aws-events-targets/lib/ecs-task.ts
Labels: bug, p1, effort/medium, star-contributor

#28995 feat: list stack dependencies
  packages/@aws-cdk-testing/cli-integ/resources/cdk-apps/app/app.js
  packages/@aws-cdk-testing/cli-integ/tests/cli-integ-tests/cli.integtest.ts
  packages/aws-cdk/README.md
  packages/aws-cdk/lib/cdk-toolkit.ts
  packages/aws-cdk/lib/cli.ts
  packages/aws-cdk/lib/list-stacks.ts
  packages/aws-cdk/test/list-stacks.test.ts
Labels: p2, contribution/core, pr-linter/exempt-integ-test, pr-linter/cli-integ-tested, pr-linter/exemption-requested

#29358 chore: add new windows build image
  packages/aws-cdk-lib/aws-codebuild/lib/project.ts
  packages/aws-cdk-lib/aws-codebuild/test/project.test.ts
Labels: p2, contribution/core

#29338 feat(rds): enable data api for aurora cluster
  packages/@aws-cdk-testing/framework-integ/test/aws-rds/test/integ.cluster-data-api.js.snapshot/asset.e978ad4ad0dca7e1c6be5f49cbbd1c5a150ee050c24052fedfe5a42f835d55da/__entrypoint__.js
  packages/@aws-cdk-testing/framework-integ/test/aws-rds/test/integ.cluster-data-api.js.snapshot/asset.e978ad4ad0dca7e1c6be5f49cbbd1c5a150ee050c24052fedfe5a42f835d55da/index.js
  packages/@aws-cdk-testing/framework-integ/test/aws-rds/test/integ.cluster-data-api.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-rds/test/integ.cluster-data-api.js.snapshot/cluster-kerberos.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-rds/test/integ.cluster-data-api.js.snapshot/cluster-kerberos.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-rds/test/integ.cluster-data-api.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-rds/test/integ.cluster-data-api.js.snapshot/integclusterdataapiDefaultTestDeployAssertACD87C08.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-rds/test/integ.cluster-data-api.js.snapshot/integclusterdataapiDefaultTestDeployAssertACD87C08.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-rds/test/integ.cluster-data-api.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-rds/test/integ.cluster-data-api.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-rds/test/integ.cluster-data-api.ts
  packages/aws-cdk-lib/aws-rds/README.md
  packages/aws-cdk-lib/aws-rds/lib/cluster.ts
  packages/aws-cdk-lib/aws-rds/test/cluster.test.ts
Labels: p1, feature-request, effort/medium, star-contributor

#29033 feat(rds): add ability to specify PreferredMaintenanceWindow to RDS cluster database instances
  packages/aws-cdk-lib/aws-rds/README.md
  packages/aws-cdk-lib/aws-rds/lib/cluster.ts
  packages/aws-cdk-lib/aws-rds/lib/props.ts
  packages/aws-cdk-lib/aws-rds/test/cluster.test.ts
Labels: p2, pr/needs-community-review, pr-linter/exempt-integ-test, beginning-contributor, pr-linter/exemption-requested

#29365 fix(s3): incorrect account used for S3 event source mapping
  packages/aws-cdk-lib/aws-lambda-event-sources/test/s3.test.ts
  packages/aws-cdk-lib/aws-s3-notifications/lib/lambda.ts
  packages/aws-cdk-lib/aws-s3/lib/bucket.ts
Labels: p2, pr-linter/exempt-integ-test, beginning-contributor, pr-linter/exemption-requested

#29374 fix(events_targets): installing latest aws sdk fails in cn partition
  packages/aws-cdk-lib/aws-events-targets/README.md
  packages/aws-cdk-lib/aws-events-targets/lib/log-group-resource-policy.ts
  packages/aws-cdk-lib/aws-events-targets/lib/log-group.ts
  packages/aws-cdk-lib/aws-events-targets/test/logs/log-group.test.ts
Labels: bug, p1, contribution/core, pr-linter/exempt-integ-test

#29113 feat(autoscaling): add support for InstanceRefresh suspended process
  packages/@aws-cdk-testing/framework-integ/test/aws-autoscaling/test/integ.asg-update-policy.js.snapshot/AutoScalingUpdatePolicyTestDefaultTestDeployAssert35BEDF6F.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-autoscaling/test/integ.asg-update-policy.js.snapshot/AutoScalingUpdatePolicyTestDefaultTestDeployAssert35BEDF6F.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-autoscaling/test/integ.asg-update-policy.js.snapshot/aws-cdk-autoscaling-update-policy.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-autoscaling/test/integ.asg-update-policy.js.snapshot/aws-cdk-autoscaling-update-policy.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-autoscaling/test/integ.asg-update-policy.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-autoscaling/test/integ.asg-update-policy.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-autoscaling/test/integ.asg-update-policy.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-autoscaling/test/integ.asg-update-policy.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-autoscaling/test/integ.asg-update-policy.ts
  packages/aws-cdk-lib/aws-autoscaling/lib/auto-scaling-group.ts
  packages/aws-cdk-lib/aws-autoscaling/test/auto-scaling-group.test.ts
  packages/aws-cdk-lib/aws-autoscaling/test/scheduled-action.test.ts
  packages/aws-cdk-lib/aws-ecs/test/cluster.test.ts
Labels: p2, pr/needs-community-review, pr-linter/exempt-readme, beginning-contributor, pr-linter/exemption-requested

#29296 feat(stepfunctions-tasks): start build batch integration
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/codebuild/integ.start-build-batch.js.snapshot/StartBuildBatch.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/codebuild/integ.start-build-batch.js.snapshot/StartBuildBatch.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/codebuild/integ.start-build-batch.js.snapshot/StartBuildBatchIntegDefaultTestDeployAssert142C169A.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/codebuild/integ.start-build-batch.js.snapshot/StartBuildBatchIntegDefaultTestDeployAssert142C169A.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/codebuild/integ.start-build-batch.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/codebuild/integ.start-build-batch.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/codebuild/integ.start-build-batch.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/codebuild/integ.start-build-batch.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/codebuild/integ.start-build-batch.ts
  packages/aws-cdk-lib/aws-stepfunctions-tasks/README.md
  packages/aws-cdk-lib/aws-stepfunctions-tasks/lib/codebuild/start-build-batch.ts
  packages/aws-cdk-lib/aws-stepfunctions-tasks/lib/index.ts
  packages/aws-cdk-lib/aws-stepfunctions-tasks/test/codebuild/start-build-batch.test.ts
Labels: p2, feature-request, effort/medium, star-contributor

#29390 chore: typo fix in cli README.md
  packages/aws-cdk/README.md
Labels: p2, beginning-contributor

#29394 fix(cli): prevent changeset diff for non-deployed stacks
  packages/@aws-cdk/cloudformation-diff/lib/diff-template.ts
  packages/aws-cdk/lib/cdk-toolkit.ts
  packages/aws-cdk/lib/diff.ts
  packages/aws-cdk/test/diff.test.ts
Labels: p1, effort/medium, contribution/core, pr-linter/exempt-integ-test, pr-linter/cli-integ-tested

#28625 fix(glue): `PythonRayExecutableProps` has innaccurate properties
  packages/@aws-cdk/aws-glue-alpha/lib/job-executable.ts
  packages/@aws-cdk/aws-glue-alpha/lib/job.ts
  packages/@aws-cdk/aws-glue-alpha/test/integ.job.js.snapshot/asset.1c055910db2de9d0fcf53321842cab491bb6985900b80e05d634fceef328c5c4.zip
  packages/@aws-cdk/aws-glue-alpha/test/integ.job.js.snapshot/asset.9120cd4aa376310a46a09d707c5e0c75c164b9014f1740e4c5a3637a34dfafe7.py
  packages/@aws-cdk/aws-glue-alpha/test/integ.job.js.snapshot/aws-glue-job.assets.json
  packages/@aws-cdk/aws-glue-alpha/test/integ.job.js.snapshot/aws-glue-job.template.json
  packages/@aws-cdk/aws-glue-alpha/test/integ.job.js.snapshot/cdk.out
  packages/@aws-cdk/aws-glue-alpha/test/integ.job.js.snapshot/integ.json
  packages/@aws-cdk/aws-glue-alpha/test/integ.job.js.snapshot/manifest.json
  packages/@aws-cdk/aws-glue-alpha/test/integ.job.js.snapshot/tree.json
  packages/@aws-cdk/aws-glue-alpha/test/integ.job.ts
  packages/@aws-cdk/aws-glue-alpha/test/job-executable.test.ts
  packages/@aws-cdk/aws-glue-alpha/test/job-script/resolve_options.py
  packages/@aws-cdk/aws-glue-alpha/test/job.test.ts
  packages/@aws-cdk/aws-glue-alpha/test/module/utils.zip
Labels: bug, p2, effort/medium, repeat-contributor, pr/needs-maintainer-review

#29401 chore(codepipeline): add missing action for EcsDeployAction
  packages/@aws-cdk-testing/framework-integ/test/aws-codepipeline-actions/test/integ.pipeline-ecs-deploy.js.snapshot/aws-cdk-codepipeline-ecs-deploy.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-codepipeline-actions/test/integ.pipeline-ecs-deploy.js.snapshot/aws-cdk-codepipeline-ecs-deploy.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-codepipeline-actions/test/integ.pipeline-ecs-deploy.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-codepipeline-actions/test/integ.pipeline-ecs-deploy.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-codepipeline-actions/test/integ.pipeline-ecs-deploy.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-codepipeline-actions/test/integ.pipeline-ecs-deploy.js.snapshot/tree.json
  packages/aws-cdk-lib/aws-codepipeline-actions/lib/ecs/deploy-action.ts
Labels: bug, p1, effort/small, contribution/core, pr/needs-maintainer-review

#29348 docs(lambda): add missing JSDoc Markdown code block
  packages/aws-cdk-lib/aws-lambda/lib/event-source-mapping.ts
Labels: p2, distinguished-contributor

#29392 chore(cli): improve error message for cdk migrate
  packages/@aws-cdk/cli-lib-alpha/THIRD_PARTY_LICENSES
  packages/aws-cdk/THIRD_PARTY_LICENSES
  packages/aws-cdk/lib/commands/migrate.ts
  packages/aws-cdk/package.json
  packages/aws-cdk/test/cdk-toolkit.test.ts
  packages/aws-cdk/test/commands/migrate.test.ts
  packages/aws-cdk/test/commands/test-resources/templates/rds-template.json
  yarn.lock
Labels: p2, contribution/core, pr-linter/cli-integ-tested

#29404 fix(rds): incorrect error message for rds proxies
  packages/aws-cdk-lib/aws-rds/lib/proxy.ts
  packages/aws-cdk-lib/aws-rds/test/proxy.test.ts
Labels: bug, p2, effort/medium, pr-linter/exempt-integ-test, star-contributor, pr-linter/exemption-requested

#29075 feat(elasticloadbalancingv2): health check interval greater than timeout
  packages/aws-cdk-lib/aws-elasticloadbalancingv2/lib/nlb/network-target-group.ts
  packages/aws-cdk-lib/aws-elasticloadbalancingv2/lib/shared/base-target-group.ts
  packages/aws-cdk-lib/aws-elasticloadbalancingv2/test/alb/target-group.test.ts
  packages/aws-cdk-lib/aws-elasticloadbalancingv2/test/nlb/listener.test.ts
  packages/aws-cdk-lib/aws-elasticloadbalancingv2/test/nlb/target-group.test.ts
Labels: bug, p2, pr-linter/exempt-readme, pr-linter/exempt-integ-test, star-contributor, pr-linter/exemption-requested, pr/needs-maintainer-review

#29148 feat(codepipeline): `executionMode` property for Pipeline
  packages/@aws-cdk-testing/framework-integ/test/aws-codepipeline-actions/test/integ.pipeline-type-v2.js.snapshot/asset.54e6f07bf3aea46d100719f3b21fe0fb45ae789ee372d42d8cdfb97e21aba96c/index.js
  packages/@aws-cdk-testing/framework-integ/test/aws-codepipeline-actions/test/integ.pipeline-type-v2.js.snapshot/aws-cdk-codepipeline-type-v2.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-codepipeline-actions/test/integ.pipeline-type-v2.js.snapshot/aws-cdk-codepipeline-type-v2.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-codepipeline-actions/test/integ.pipeline-type-v2.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-codepipeline-actions/test/integ.pipeline-type-v2.js.snapshot/codepipelinetypev2testDefaultTestDeployAssertD8DB1C31.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-codepipeline-actions/test/integ.pipeline-type-v2.js.snapshot/codepipelinetypev2testDefaultTestDeployAssertD8DB1C31.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-codepipeline-actions/test/integ.pipeline-type-v2.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-codepipeline-actions/test/integ.pipeline-type-v2.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-codepipeline-actions/test/integ.pipeline-type-v2.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-codepipeline-actions/test/integ.pipeline-type-v2.ts
  packages/aws-cdk-lib/aws-codepipeline/README.md
  packages/aws-cdk-lib/aws-codepipeline/lib/pipeline.ts
  packages/aws-cdk-lib/aws-codepipeline/test/pipeline.test.ts
Labels: p2, feature-request, effort/medium, distinguished-contributor

#29337 fix(rds): `DatabaseCluster.instanceEndpoints` doesn't include writer endpoint
  packages/aws-cdk-lib/aws-rds/lib/cluster.ts
  packages/aws-cdk-lib/aws-rds/test/cluster.test.ts
Labels: bug, p1, effort/medium, pr-linter/exempt-integ-test, star-contributor, pr-linter/exemption-requested

#29395 chore(rds): `IO2` instance storage
  packages/@aws-cdk-testing/framework-integ/test/aws-rds/test/integ.instance-io2.js.snapshot/InstanceIo2TestDefaultTestDeployAssert183D49C3.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-rds/test/integ.instance-io2.js.snapshot/InstanceIo2TestDefaultTestDeployAssert183D49C3.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-rds/test/integ.instance-io2.js.snapshot/asset.e978ad4ad0dca7e1c6be5f49cbbd1c5a150ee050c24052fedfe5a42f835d55da/__entrypoint__.js
  packages/@aws-cdk-testing/framework-integ/test/aws-rds/test/integ.instance-io2.js.snapshot/asset.e978ad4ad0dca7e1c6be5f49cbbd1c5a150ee050c24052fedfe5a42f835d55da/index.js
  packages/@aws-cdk-testing/framework-integ/test/aws-rds/test/integ.instance-io2.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-rds/test/integ.instance-io2.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-rds/test/integ.instance-io2.js.snapshot/integRdsInstanceIo2.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-rds/test/integ.instance-io2.js.snapshot/integRdsInstanceIo2.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-rds/test/integ.instance-io2.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-rds/test/integ.instance-io2.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-rds/test/integ.instance-io2.ts
  packages/aws-cdk-lib/aws-rds/lib/instance.ts
  packages/aws-cdk-lib/aws-rds/test/instance.test.ts
Labels: p2, feature-request, star-contributor, pr-linter/exemption-requested

#29387 feat(opensearchservice): cold storage option
  packages/@aws-cdk-testing/framework-integ/test/aws-opensearchservice/test/integ.opensearch.coldstorage.js.snapshot/OpenSearchColdStorageIntegDefaultTestDeployAssert73848187.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-opensearchservice/test/integ.opensearch.coldstorage.js.snapshot/OpenSearchColdStorageIntegDefaultTestDeployAssert73848187.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-opensearchservice/test/integ.opensearch.coldstorage.js.snapshot/cdk-integ-opensearch-coldstorage.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-opensearchservice/test/integ.opensearch.coldstorage.js.snapshot/cdk-integ-opensearch-coldstorage.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-opensearchservice/test/integ.opensearch.coldstorage.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-opensearchservice/test/integ.opensearch.coldstorage.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-opensearchservice/test/integ.opensearch.coldstorage.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-opensearchservice/test/integ.opensearch.coldstorage.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-opensearchservice/test/integ.opensearch.coldstorage.ts
  packages/aws-cdk-lib/aws-opensearchservice/README.md
  packages/aws-cdk-lib/aws-opensearchservice/lib/domain.ts
  packages/aws-cdk-lib/aws-opensearchservice/test/domain.test.ts
Labels: p2, feature-request, effort/medium, star-contributor

#29408 feat(ec2): add APPCONFIG and APPCONFIGDATA to InterfaceVpcEndpointAwsService
  packages/aws-cdk-lib/aws-ec2/lib/vpc-endpoint.ts
Labels: p2, pr-linter/exempt-readme, pr-linter/exempt-test, pr-linter/exempt-integ-test, beginning-contributor

#29167 fix(lambda-nodejs): fixing esbuildArgs to take in account re-specified keys
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-nodejs/test/integ.esbuildArgs.js.snapshot/LambdaNodeJsEsbuildArgsIntegDefaultTestDeployAssertB1F5AACE.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-nodejs/test/integ.esbuildArgs.js.snapshot/LambdaNodeJsEsbuildArgsIntegDefaultTestDeployAssertB1F5AACE.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-nodejs/test/integ.esbuildArgs.js.snapshot/asset.5017e4b2e278e32bc634202d075b7ed8961b0d784f75450f7918a6a4f6f7df4a/index.js
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-nodejs/test/integ.esbuildArgs.js.snapshot/asset.5017e4b2e278e32bc634202d075b7ed8961b0d784f75450f7918a6a4f6f7df4a/index.js.map
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-nodejs/test/integ.esbuildArgs.js.snapshot/cdk-integ-lambda-nodejs-esbuildArgs.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-nodejs/test/integ.esbuildArgs.js.snapshot/cdk-integ-lambda-nodejs-esbuildArgs.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-nodejs/test/integ.esbuildArgs.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-nodejs/test/integ.esbuildArgs.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-nodejs/test/integ.esbuildArgs.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-nodejs/test/integ.esbuildArgs.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-nodejs/test/integ.esbuildArgs.ts
  packages/aws-cdk-lib/aws-lambda-nodejs/lib/bundling.ts
  packages/aws-cdk-lib/aws-lambda-nodejs/test/bundling.test.ts
Labels: bug, p1, effort/small, beginning-contributor

#29417 chore(merge-back): 2.132.0
  CHANGELOG.v2.alpha.md
  CHANGELOG.v2.md
  version.v2.json
Labels: p2, pr/needs-community-review, pr/no-squash, auto-approve

#29438 feat: update L1 CloudFormation resource definitions
  packages/@aws-cdk/cloudformation-diff/package.json
  packages/@aws-cdk/integ-runner/package.json
  packages/aws-cdk-lib/package.json
  tools/@aws-cdk/spec2cdk/package.json
  yarn.lock
Labels: p2, dependencies, contribution/core, pr-linter/exempt-readme, pr-linter/exempt-test, auto-approve, pr-linter/exempt-integ-test, pr/needs-maintainer-review

#29422 chore(rds): update engine versions
  packages/aws-cdk-lib/aws-rds/lib/cluster-engine.ts
  packages/aws-cdk-lib/aws-rds/lib/instance-engine.ts
Labels: p2, feature-request, effort/small, distinguished-contributor

#29427 chore(ec2): add missing instance types
  packages/aws-cdk-lib/aws-ec2/lib/instance-types.ts
Labels: p2, feature-request, effort/medium, distinguished-contributor

#29016 feat(stepfunctions-tasks): start glue crawler
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/glue/integ.glue-start-crawler.js.snapshot/EcsDeploymentConfigTestDefaultTestDeployAssertA6573788.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/glue/integ.glue-start-crawler.js.snapshot/EcsDeploymentConfigTestDefaultTestDeployAssertA6573788.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/glue/integ.glue-start-crawler.js.snapshot/aws-cdk-glue-crawler.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/glue/integ.glue-start-crawler.js.snapshot/aws-cdk-glue-crawler.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/glue/integ.glue-start-crawler.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/glue/integ.glue-start-crawler.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/glue/integ.glue-start-crawler.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/glue/integ.glue-start-crawler.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/glue/integ.glue-start-crawler.ts
  packages/aws-cdk-lib/aws-stepfunctions-tasks/README.md
  packages/aws-cdk-lib/aws-stepfunctions-tasks/lib/glue/start-crawler-run.ts
  packages/aws-cdk-lib/aws-stepfunctions-tasks/lib/index.ts
  packages/aws-cdk-lib/aws-stepfunctions-tasks/test/glue/start-crawler-run.test.ts
Labels: p2, feature-request, effort/small, star-contributor, pr/needs-maintainer-review

#29444 chore: add weekly workflow for github issues/pr metrics
  .github/workflows/repo-metrics-monthly.yml
  .github/workflows/repo-metrics-weekly.yml
Labels: p2, contribution/core

#29447 fix(cli): `cdk ls` returns stack id instead of stack display name
  packages/@aws-cdk-testing/cli-integ/resources/cli-regression-patches/v2.132.0/NOTES.md
  packages/@aws-cdk-testing/cli-integ/resources/cli-regression-patches/v2.132.0/skip-tests.txt
  packages/@aws-cdk-testing/cli-integ/tests/cli-integ-tests/cli.integtest.ts
  packages/aws-cdk/lib/list-stacks.ts
  packages/aws-cdk/test/list-stacks.test.ts
Labels: bug, p0, contribution/core, pr-linter/exempt-integ-test, pr-linter/cli-integ-tested

#29457 chore(release): v2.132.1
  CHANGELOG.v2.alpha.md
  CHANGELOG.v2.md
  packages/@aws-cdk-testing/cli-integ/resources/cli-regression-patches/v2.132.0/NOTES.md
  packages/@aws-cdk-testing/cli-integ/resources/cli-regression-patches/v2.132.0/skip-tests.txt
  packages/@aws-cdk-testing/cli-integ/tests/cli-integ-tests/cli.integtest.ts
  packages/aws-cdk/lib/list-stacks.ts
  packages/aws-cdk/test/list-stacks.test.ts
  version.v2.json
Labels: p2, contribution/core, pr/no-squash, pr-linter/cli-integ-tested, pr/needs-maintainer-review

#29431 feat(ecs-patterns): support `securityGroups` in `NetworkLoadBalancedFargateService`
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs-patterns/test/fargate/integ.nlb-sg.js.snapshot/aws-ecs-integ-lb-fargate.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs-patterns/test/fargate/integ.nlb-sg.js.snapshot/aws-ecs-integ-lb-fargate.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs-patterns/test/fargate/integ.nlb-sg.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs-patterns/test/fargate/integ.nlb-sg.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs-patterns/test/fargate/integ.nlb-sg.js.snapshot/l3FargateTestDefaultTestDeployAssert3391A20B.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs-patterns/test/fargate/integ.nlb-sg.js.snapshot/l3FargateTestDefaultTestDeployAssert3391A20B.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs-patterns/test/fargate/integ.nlb-sg.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs-patterns/test/fargate/integ.nlb-sg.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs-patterns/test/fargate/integ.nlb-sg.ts
  packages/aws-cdk-lib/aws-ecs-patterns/README.md
  packages/aws-cdk-lib/aws-ecs-patterns/lib/fargate/network-load-balanced-fargate-service.ts
  packages/aws-cdk-lib/aws-ecs-patterns/test/fargate/load-balanced-fargate-service.test.ts
Labels: p1, feature-request, valued-contributor

#29440 chore(msk-alpha): update KafkaVersion
  packages/@aws-cdk/aws-msk-alpha/README.md
  packages/@aws-cdk/aws-msk-alpha/lib/cluster-version.ts
  packages/@aws-cdk/aws-msk-alpha/test/cluster.test.ts
Labels: p2, distinguished-contributor

#29172 feat(CLI): improved nested stack diff
  packages/@aws-cdk/cloudformation-diff/lib/diff-template.ts
  packages/@aws-cdk/cloudformation-diff/lib/format.ts
  packages/aws-cdk/lib/api/deployments.ts
  packages/aws-cdk/lib/api/evaluate-cloudformation-template.ts
  packages/aws-cdk/lib/api/hotswap-deployments.ts
  packages/aws-cdk/lib/api/nested-stack-helpers.ts
  packages/aws-cdk/lib/cdk-toolkit.ts
  packages/aws-cdk/lib/diff.ts
  packages/aws-cdk/test/api/cloudformation-deployments.test.ts
  packages/aws-cdk/test/api/hotswap/nested-stacks-hotswap.test.ts
  packages/aws-cdk/test/diff.test.ts
  packages/aws-cdk/test/nested-stack-templates/one-stack-with-two-nested-stacks-stack.template.json
  packages/aws-cdk/test/nested-stack-templates/one-unnamed-lambda-two-stacks-stack.nested.template.json
  packages/aws-cdk/test/util.ts
Labels: p2, contribution/core, pr-linter/exempt-readme, pr-linter/exempt-integ-test, pr-linter/cli-integ-tested

#29412 feat(rds): proxy for mariadb
  packages/@aws-cdk-testing/framework-integ/test/aws-rds/test/integ.proxy-mariadb.js.snapshot/aws-cdk-rds-proxy-mariadb.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-rds/test/integ.proxy-mariadb.js.snapshot/aws-cdk-rds-proxy-mariadb.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-rds/test/integ.proxy-mariadb.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-rds/test/integ.proxy-mariadb.js.snapshot/databaseproxymariadbintegtestDefaultTestDeployAssert9D9B7FF3.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-rds/test/integ.proxy-mariadb.js.snapshot/databaseproxymariadbintegtestDefaultTestDeployAssert9D9B7FF3.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-rds/test/integ.proxy-mariadb.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-rds/test/integ.proxy-mariadb.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-rds/test/integ.proxy-mariadb.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-rds/test/integ.proxy-mariadb.ts
  packages/aws-cdk-lib/aws-rds/README.md
  packages/aws-cdk-lib/aws-rds/lib/instance-engine.ts
  packages/aws-cdk-lib/aws-rds/test/proxy.test.ts
Labels: bug, p2, effort/medium, star-contributor

#29485 revert: prevent changeset diff for non-deployed stacks
  packages/@aws-cdk/cloudformation-diff/lib/diff-template.ts
  packages/aws-cdk/lib/cdk-toolkit.ts
  packages/aws-cdk/lib/diff.ts
Labels: p2, contribution/core, pr-linter/cli-integ-tested

#29315 fix(kms): kms key grant methods misidentify region when enclosing stack is different region
  packages/aws-cdk-lib/aws-kms/lib/key.ts
  packages/aws-cdk-lib/aws-kms/test/key.test.ts
  packages/aws-cdk-lib/cx-api/FEATURE_FLAGS.md
  packages/aws-cdk-lib/cx-api/README.md
  packages/aws-cdk-lib/cx-api/lib/features.ts
Labels: bug, p1, effort/medium, contribution/core, pr-linter/exempt-integ-test

#29399 feat(rds): eliminating the need for explicit `secret.grantRead()` invokes when using DataAPI with Aurora cluster
  packages/@aws-cdk-testing/framework-integ/test/aws-rds/test/integ.cluster-data-api.js.snapshot/cluster-data-api.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-rds/test/integ.cluster-data-api.js.snapshot/cluster-data-api.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-rds/test/integ.cluster-data-api.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-rds/test/integ.cluster-data-api.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-rds/test/integ.cluster-data-api.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-rds/test/integ.cluster-data-api.ts
  packages/aws-cdk-lib/aws-rds/README.md
  packages/aws-cdk-lib/aws-rds/lib/cluster-ref.ts
  packages/aws-cdk-lib/aws-rds/lib/cluster.ts
  packages/aws-cdk-lib/aws-rds/test/cluster.test.ts
Labels: p2, feature-request, effort/medium, star-contributor

#29364 fix(cloudwatch): cloudwatch ec2 alarm action with multiple dimension results in error
  packages/aws-cdk-lib/aws-cloudwatch/lib/alarm.ts
  packages/aws-cdk-lib/aws-cloudwatch/test/alarm.test.ts
Labels: bug, p1, effort/medium, contribution/core, pr-linter/exempt-integ-test, pr-linter/exemption-requested

#29472 chore(synthetics): deprecate nodejs runtimes
  packages/aws-cdk-lib/aws-synthetics/lib/runtime.ts
Labels: p2, star-contributor

#29277 chore(integ-test-alpha): add log group retention days to integ test stack
  packages/@aws-cdk/integ-tests-alpha/README.md
  packages/@aws-cdk/integ-tests-alpha/lib/assertions/providers/provider.ts
  packages/@aws-cdk/integ-tests-alpha/lib/assertions/sdk.ts
  packages/@aws-cdk/integ-tests-alpha/test/assertions/providers/provider.test.ts
Labels: p1, feature-request, effort/medium, contribution/core

#29416 chore(iam): clarify policy docs
  packages/aws-cdk-lib/aws-iam/lib/policy.ts
Labels: p2, star-contributor

#29446 chore(synthetics): update runtimes
  packages/aws-cdk-lib/aws-synthetics/lib/runtime.ts
Labels: p2, distinguished-contributor

#29498 fix(cloudwatch): unrecognized statistic warning when using percentileRank statistic in Stats helper
  packages/aws-cdk-lib/aws-cloudwatch/lib/private/statistic.ts
  packages/aws-cdk-lib/aws-cloudwatch/test/stats.test.ts
Labels: bug, p1, effort/small, contribution/core, pr-linter/exempt-integ-test

#29506 chore(s3): upgrade S3BucketNotifications Lambda to python3.11
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-event-sources/test/integ.s3.imported-bucket.js.snapshot/tester.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-event-sources/test/integ.s3.js.snapshot/lambda-event-source-s3.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-s3-notifications/test/integ.notifications.js.snapshot/test-3.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-s3-notifications/test/lambda/integ.bucket-notifications.js.snapshot/cdk-integ-lambda-bucket-notifications.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-s3-notifications/test/sns/integ.sns-bucket-notifications.js.snapshot/sns-bucket-notifications.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-s3-notifications/test/sqs/integ.bucket-notifications-unmanaged.js.snapshot/integ-sqs-bucket-notifications.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-s3-notifications/test/sqs/integ.bucket-notifications.js.snapshot/sqs-bucket-notifications.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-s3/test/integ.bucket.notifications.js.snapshot/aws-cdk-s3-notifications.template.json
  packages/aws-cdk-lib/aws-s3/lib/notifications-resource/notifications-resource-handler.ts
  packages/aws-cdk-lib/aws-s3/test/notification.test.ts
Labels: p2, repeat-contributor

#29295 chore: npm-check-updates && yarn upgrade
  package.json
  packages/@aws-cdk-testing/cli-integ/package.json
  packages/@aws-cdk-testing/framework-integ/package.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-nodejs/test/integ.latest.js.snapshot/LambdaNodeJsLatestIntegDefaultTestDeployAssertD40B5C28.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-nodejs/test/integ.latest.js.snapshot/LambdaNodeJsLatestIntegDefaultTestDeployAssertD40B5C28.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-nodejs/test/integ.latest.js.snapshot/asset.310f432b946edeef3316f39f32b344b6bdc401a3b438433db42adadab1bf5e17.bundle/index.js
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-nodejs/test/integ.latest.js.snapshot/asset.386feb67b7bf6af448077c3c16e21124802b9da0b0c9a5e9f1ba783d2c2fb01f/index.js
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-nodejs/test/integ.latest.js.snapshot/asset.8675e444a7d27e73e12fdf56f28d1271ae188efc106fa19fc56a4b0e28290813/index.js
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-nodejs/test/integ.latest.js.snapshot/asset.8675e444a7d27e73e12fdf56f28d1271ae188efc106fa19fc56a4b0e28290813/node_modules/.yarn-integrity
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-nodejs/test/integ.latest.js.snapshot/asset.8675e444a7d27e73e12fdf56f28d1271ae188efc106fa19fc56a4b0e28290813/node_modules/delay/index.d.ts
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-nodejs/test/integ.latest.js.snapshot/asset.8675e444a7d27e73e12fdf56f28d1271ae188efc106fa19fc56a4b0e28290813/node_modules/delay/index.js
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-nodejs/test/integ.latest.js.snapshot/asset.8675e444a7d27e73e12fdf56f28d1271ae188efc106fa19fc56a4b0e28290813/node_modules/delay/license
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-nodejs/test/integ.latest.js.snapshot/asset.8675e444a7d27e73e12fdf56f28d1271ae188efc106fa19fc56a4b0e28290813/node_modules/delay/package.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-nodejs/test/integ.latest.js.snapshot/asset.8675e444a7d27e73e12fdf56f28d1271ae188efc106fa19fc56a4b0e28290813/node_modules/delay/readme.md
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-nodejs/test/integ.latest.js.snapshot/asset.8675e444a7d27e73e12fdf56f28d1271ae188efc106fa19fc56a4b0e28290813/package.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-nodejs/test/integ.latest.js.snapshot/asset.8675e444a7d27e73e12fdf56f28d1271ae188efc106fa19fc56a4b0e28290813/yarn.lock
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-nodejs/test/integ.latest.js.snapshot/asset.ac51674cf5325b7a0e5444d6b7c1f88607c16a031b852bd51c375ac8c5c4fce5.bundle/index.js
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-nodejs/test/integ.latest.js.snapshot/bundling-temp-71cc1f73324ecf927c754dd5f0d3c2a644d9d3210f3e05620217e3db1b009ddc/package.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-nodejs/test/integ.latest.js.snapshot/bundling-temp-71cc1f73324ecf927c754dd5f0d3c2a644d9d3210f3e05620217e3db1b009ddc/yarn.lock
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-nodejs/test/integ.latest.js.snapshot/cdk-integ-lambda-nodejs-latest.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-nodejs/test/integ.latest.js.snapshot/cdk-integ-lambda-nodejs-latest.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-nodejs/test/integ.latest.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-nodejs/test/integ.latest.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/pipelines/test/integ.newpipeline-with-file-system-locations.js
  packages/@aws-cdk/cloud-assembly-schema/package.json
  packages/@aws-cdk/cloudformation-diff/package.json
  packages/@aws-cdk/custom-resource-handlers/package.json
  packages/@aws-cdk/cx-api/package.json
  packages/@aws-cdk/integ-tests-alpha/package.json
  packages/@aws-cdk/sdk-v2-to-v3-adapter/package.json
  packages/aws-cdk-lib/package.json
  packages/aws-cdk/THIRD_PARTY_LICENSES
  packages/aws-cdk/lib/init-templates/app/typescript/package.json
  packages/aws-cdk/lib/init-templates/lib/typescript/package.json
  packages/aws-cdk/lib/init-templates/sample-app/typescript/package.json
  packages/aws-cdk/package.json
  packages/awslint/package.json
  packages/cdk-assets/package.json
  tools/@aws-cdk/cdk-build-tools/package.json
  tools/@aws-cdk/pkglint/package.json
  tools/@aws-cdk/yarn-cling/package.json
  yarn.lock
Labels: p2, dependencies, contribution/core, auto-approve

#29499 chore(merge-back): 2.133.0
  CHANGELOG.v2.alpha.md
  CHANGELOG.v2.md
  packages/aws-cdk-lib/cx-api/FEATURE_FLAGS.md
  packages/aws-cdk-lib/cx-api/lib/features.ts
  version.v2.json
Labels: p2, pr/needs-community-review, pr/no-squash, auto-approve

#29481 chore(ec2): dl2q instance type, `IntanceType` fixes
  packages/aws-cdk-lib/aws-ec2/lib/instance-types.ts
Labels: p2, distinguished-contributor

#29155 feat(eks): trainium instance types
  packages/aws-cdk-lib/aws-eks/README.md
  packages/aws-cdk-lib/aws-eks/lib/cluster.ts
  packages/aws-cdk-lib/aws-eks/lib/instance-types.ts
  packages/aws-cdk-lib/aws-eks/test/cluster.test.ts
Labels: bug, p2, effort/medium, pr-linter/exempt-integ-test, star-contributor, pr-linter/exemption-requested, pr/needs-maintainer-review

#28768 fix(cloudformation-diff): move aws-sdk to dependency for cfn-diff to get CFN types resolved in exports
  packages/@aws-cdk/cloudformation-diff/package.json
Labels: bug, p1, effort/medium, pr-linter/exempt-test, pr-linter/exempt-integ-test, beginning-contributor, pr-linter/exemption-requested, pr/needs-maintainer-review

#29445 fix(elasticloadbalancingv2): allow alb slow start duration of 0 seconds
  packages/aws-cdk-lib/aws-elasticloadbalancingv2/README.md
  packages/aws-cdk-lib/aws-elasticloadbalancingv2/lib/alb/application-target-group.ts
  packages/aws-cdk-lib/aws-elasticloadbalancingv2/test/alb/target-group.test.ts
Labels: bug, p1, effort/small, pr-linter/exempt-integ-test, star-contributor, pr-linter/exemption-requested

#29530 feat: update L1 CloudFormation resource definitions
  packages/@aws-cdk/cloudformation-diff/package.json
  packages/@aws-cdk/integ-runner/package.json
  packages/aws-cdk-lib/package.json
  tools/@aws-cdk/spec2cdk/package.json
  yarn.lock
Labels: p2, dependencies, contribution/core, pr-linter/exempt-readme, pr-linter/exempt-test, auto-approve, pr-linter/exempt-integ-test

#29205 fix(opensearch): cannot disable cluster logging
  packages/@aws-cdk-testing/framework-integ/test/aws-opensearchservice/test/integ.opensearch.disable-logging.js.snapshot/IntegDefaultTestDeployAssert4E6713E1.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-opensearchservice/test/integ.opensearch.disable-logging.js.snapshot/IntegDefaultTestDeployAssert4E6713E1.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-opensearchservice/test/integ.opensearch.disable-logging.js.snapshot/cdk-integ-opensearch-with-logging-disabled.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-opensearchservice/test/integ.opensearch.disable-logging.js.snapshot/cdk-integ-opensearch-with-logging-disabled.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-opensearchservice/test/integ.opensearch.disable-logging.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-opensearchservice/test/integ.opensearch.disable-logging.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-opensearchservice/test/integ.opensearch.disable-logging.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-opensearchservice/test/integ.opensearch.disable-logging.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-opensearchservice/test/integ.opensearch.disable-logging.ts
  packages/aws-cdk-lib/aws-opensearchservice/lib/domain.ts
  packages/aws-cdk-lib/aws-opensearchservice/test/domain.test.ts
Labels: bug, p2, effort/medium, beginning-contributor, pr/reviewer-clarification-requested

#29525 docs(opensearchservice): fix broken markdown link
  packages/aws-cdk-lib/aws-opensearchservice/lib/domain.ts
Labels: p2, star-contributor

#27921 feat(cli): warn of non-existent stacks in `cdk destroy`
  packages/aws-cdk/lib/cdk-toolkit.ts
Labels: bug, p2, effort/small, pr-linter/exempt-readme, pr-linter/exempt-test, pr-linter/exempt-integ-test, star-contributor, pr-linter/cli-integ-tested, pr-linter/do-not-close, pr-linter/exemption-requested

#29357 fix(glue): s3 path specified in --spark-event-logs-path needs to end with slash
  packages/@aws-cdk/aws-glue-alpha/lib/job.ts
  packages/@aws-cdk/aws-glue-alpha/test/integ.job.js.snapshot/aws-glue-job.assets.json
  packages/@aws-cdk/aws-glue-alpha/test/integ.job.js.snapshot/aws-glue-job.template.json
  packages/@aws-cdk/aws-glue-alpha/test/integ.job.js.snapshot/manifest.json
  packages/@aws-cdk/aws-glue-alpha/test/integ.job.js.snapshot/tree.json
  packages/@aws-cdk/aws-glue-alpha/test/integ.job.ts
  packages/@aws-cdk/aws-glue-alpha/test/job.test.ts
Labels: bug, p2, effort/medium, repeat-contributor

#29521 feat(elasticloadbalancingv2): `denyAllIgwTraffic` and `clientRoutingPolicy` for NLB
  packages/@aws-cdk-testing/framework-integ/test/aws-elasticloadbalancingv2/test/integ.nlb-attributes.js.snapshot/aws-cdk-nlb-attributes-integ.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-elasticloadbalancingv2/test/integ.nlb-attributes.js.snapshot/aws-cdk-nlb-attributes-integ.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-elasticloadbalancingv2/test/integ.nlb-attributes.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-elasticloadbalancingv2/test/integ.nlb-attributes.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-elasticloadbalancingv2/test/integ.nlb-attributes.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-elasticloadbalancingv2/test/integ.nlb-attributes.js.snapshot/nlbattlibutesintegDefaultTestDeployAssert2D727654.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-elasticloadbalancingv2/test/integ.nlb-attributes.js.snapshot/nlbattlibutesintegDefaultTestDeployAssert2D727654.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-elasticloadbalancingv2/test/integ.nlb-attributes.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-elasticloadbalancingv2/test/integ.nlb-attributes.ts
  packages/aws-cdk-lib/aws-elasticloadbalancingv2/README.md
  packages/aws-cdk-lib/aws-elasticloadbalancingv2/lib/nlb/network-load-balancer.ts
  packages/aws-cdk-lib/aws-elasticloadbalancingv2/lib/shared/base-load-balancer.ts
  packages/aws-cdk-lib/aws-elasticloadbalancingv2/test/alb/load-balancer.test.ts
  packages/aws-cdk-lib/aws-elasticloadbalancingv2/test/nlb/load-balancer.test.ts
Labels: p2, feature-request, star-contributor

#29492 fix(CLI): `cdk diff` stack deletion causes a race condition
  packages/@aws-cdk/cloudformation-diff/lib/diff-template.ts
  packages/aws-cdk/lib/api/util/cloudformation.ts
  packages/aws-cdk/lib/cdk-toolkit.ts
  packages/aws-cdk/lib/diff.ts
  packages/aws-cdk/test/diff.test.ts
Labels: p1, effort/medium, contribution/core, pr-linter/exempt-integ-test, pr-linter/cli-integ-tested

#29475 chore: typo fixes
  packages/aws-cdk/lib/commands/migrate.ts
  packages/cdk-assets/test/private/docker-credentials.test.ts
Labels: p2, beginning-contributor, pr-linter/cli-integ-tested

#29469 chore(opensearchservice): deprecate OpenSearch 2.10
  packages/aws-cdk-lib/aws-opensearchservice/lib/version.ts
Labels: p2, distinguished-contributor

#29554 feat(kinesisanalytics-flink): add support for Flink 1.18
  packages/@aws-cdk/aws-kinesisanalytics-flink-alpha/README.md
  packages/@aws-cdk/aws-kinesisanalytics-flink-alpha/lib/types.ts
  packages/@aws-cdk/aws-kinesisanalytics-flink-alpha/test/integ.application-code-from-bucket.lit.js.snapshot/FlinkAppCodeFromBucketTest.assets.json
  packages/@aws-cdk/aws-kinesisanalytics-flink-alpha/test/integ.application-code-from-bucket.lit.js.snapshot/FlinkAppCodeFromBucketTest.template.json
  packages/@aws-cdk/aws-kinesisanalytics-flink-alpha/test/integ.application-code-from-bucket.lit.js.snapshot/cdk.out
  packages/@aws-cdk/aws-kinesisanalytics-flink-alpha/test/integ.application-code-from-bucket.lit.js.snapshot/integ.json
  packages/@aws-cdk/aws-kinesisanalytics-flink-alpha/test/integ.application-code-from-bucket.lit.js.snapshot/manifest.json
  packages/@aws-cdk/aws-kinesisanalytics-flink-alpha/test/integ.application-code-from-bucket.lit.js.snapshot/tree.json
  packages/@aws-cdk/aws-kinesisanalytics-flink-alpha/test/integ.application-code-from-bucket.lit.ts
  packages/@aws-cdk/aws-kinesisanalytics-flink-alpha/test/integ.application.lit.js.snapshot/FlinkAppTest.assets.json
  packages/@aws-cdk/aws-kinesisanalytics-flink-alpha/test/integ.application.lit.js.snapshot/FlinkAppTest.template.json
  packages/@aws-cdk/aws-kinesisanalytics-flink-alpha/test/integ.application.lit.js.snapshot/cdk.out
  packages/@aws-cdk/aws-kinesisanalytics-flink-alpha/test/integ.application.lit.js.snapshot/integ.json
  packages/@aws-cdk/aws-kinesisanalytics-flink-alpha/test/integ.application.lit.js.snapshot/manifest.json
  packages/@aws-cdk/aws-kinesisanalytics-flink-alpha/test/integ.application.lit.js.snapshot/tree.json
  packages/@aws-cdk/aws-kinesisanalytics-flink-alpha/test/integ.application.lit.ts
  packages/@aws-cdk/aws-kinesisanalytics-flink-alpha/test/integ.vpc-application.js.snapshot/FlinkAppTest.assets.json
  packages/@aws-cdk/aws-kinesisanalytics-flink-alpha/test/integ.vpc-application.js.snapshot/FlinkAppTest.template.json
  packages/@aws-cdk/aws-kinesisanalytics-flink-alpha/test/integ.vpc-application.js.snapshot/VpcTestDefaultTestDeployAssert06A9965C.assets.json
  packages/@aws-cdk/aws-kinesisanalytics-flink-alpha/test/integ.vpc-application.js.snapshot/cdk.out
  packages/@aws-cdk/aws-kinesisanalytics-flink-alpha/test/integ.vpc-application.js.snapshot/integ.json
  packages/@aws-cdk/aws-kinesisanalytics-flink-alpha/test/integ.vpc-application.js.snapshot/manifest.json
  packages/@aws-cdk/aws-kinesisanalytics-flink-alpha/test/integ.vpc-application.js.snapshot/tree.json
  packages/@aws-cdk/aws-kinesisanalytics-flink-alpha/test/integ.vpc-application.ts
Labels: p2, beginning-contributor

#29534 feat(codepipeline-actions): show status reason in the pipeline for failed change set executions
  packages/@aws-cdk-testing/framework-integ/test/aws-codepipeline-actions/test/integ.cfn-template-from-repo.lit.js.snapshot/aws-cdk-codepipeline-cloudformation.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-codepipeline-actions/test/integ.cfn-template-from-repo.lit.js.snapshot/aws-cdk-codepipeline-cloudformation.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-codepipeline-actions/test/integ.cfn-template-from-repo.lit.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-codepipeline-actions/test/integ.cfn-template-from-repo.lit.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-codepipeline-actions/test/integ.cfn-template-from-repo.lit.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-codepipeline-actions/test/integ.cfn-template-from-repo.lit.js.snapshot/tree.json
  packages/aws-cdk-lib/aws-codepipeline-actions/lib/cloudformation/private/singleton-policy.ts
  packages/aws-cdk-lib/aws-codepipeline-actions/test/cloudformation/pipeline-actions.test.ts
Labels: p2, pr-linter/exempt-readme, pr-linter/exempt-integ-test, admired-contributor, pr-linter/exemption-requested

#29569 feat: update L1 CloudFormation resource definitions
  packages/@aws-cdk/cloudformation-diff/package.json
  packages/@aws-cdk/integ-runner/package.json
  packages/aws-cdk-lib/package.json
  tools/@aws-cdk/spec2cdk/package.json
  yarn.lock
Labels: p2, dependencies, contribution/core, pr-linter/exempt-readme, pr-linter/exempt-test, auto-approve, pr-linter/exempt-integ-test

#29567 docs(lambda-go): fix typos
  packages/@aws-cdk/aws-lambda-go-alpha/README.md
Labels: p2, beginning-contributor

#29512 docs(ec2): update `aws-ec2` README to include workaround for using a service principal in VPCEService `allowedPrincipals`
  packages/@aws-cdk-testing/framework-integ/test/aws-elasticloadbalancingv2/test/integ.vpc-endpoint-service.js.snapshot/aws-cdk-ec2-vpc-endpoint-service.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-elasticloadbalancingv2/test/integ.vpc-endpoint-service.js.snapshot/aws-cdk-ec2-vpc-endpoint-service.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-elasticloadbalancingv2/test/integ.vpc-endpoint-service.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-elasticloadbalancingv2/test/integ.vpc-endpoint-service.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-elasticloadbalancingv2/test/integ.vpc-endpoint-service.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-elasticloadbalancingv2/test/integ.vpc-endpoint-service.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-elasticloadbalancingv2/test/integ.vpc-endpoint-service.ts
  packages/aws-cdk-lib/aws-ec2/README.md
  packages/aws-cdk-lib/aws-ec2/test/vpc-endpoint-service.test.ts
Labels: bug, p2, effort/medium, beginning-contributor, pr/needs-maintainer-review

#29490 fix(ecs-patterns): integ test unable to create ECS service
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs-patterns/test/fargate/integ.alb-fargate-service-command-entry-point.js.snapshot/AlbFargateServiceWithCommandAndEntryPointDefaultTestDeployAssert84DAACDF.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs-patterns/test/fargate/integ.alb-fargate-service-command-entry-point.js.snapshot/aws-ecs-integ-lb-fargate-cmd-entrypoint-test.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs-patterns/test/fargate/integ.alb-fargate-service-command-entry-point.js.snapshot/aws-ecs-integ-lb-fargate-cmd-entrypoint-test.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs-patterns/test/fargate/integ.alb-fargate-service-command-entry-point.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs-patterns/test/fargate/integ.alb-fargate-service-command-entry-point.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs-patterns/test/fargate/integ.alb-fargate-service-command-entry-point.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs-patterns/test/fargate/integ.alb-fargate-service-command-entry-point.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs-patterns/test/fargate/integ.alb-fargate-service-command-entry-point.ts
Labels: p2, valued-contributor, pr/needs-maintainer-review

#29573 feat: update L1 CloudFormation resource definitions
  packages/@aws-cdk/cloudformation-diff/package.json
  packages/@aws-cdk/integ-runner/package.json
  packages/aws-cdk-lib/package.json
  tools/@aws-cdk/spec2cdk/package.json
  yarn.lock
Labels: p2, dependencies, contribution/core, pr-linter/exempt-readme, pr-linter/exempt-test, auto-approve, pr-linter/exempt-integ-test

#29524 chore(ec2): add missing vpc endpoints
  packages/aws-cdk-lib/aws-ec2/lib/vpc-endpoint.ts
  packages/aws-cdk-lib/awslint.json
Labels: p2, feature-request, distinguished-contributor

#29553 chore: npm-check-updates && yarn upgrade
  package.json
  packages/@aws-cdk-testing/cli-integ/package.json
  packages/@aws-cdk-testing/framework-integ/package.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-nodejs/test/integ.latest.js.snapshot/LambdaNodeJsLatestIntegDefaultTestDeployAssertD40B5C28.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-nodejs/test/integ.latest.js.snapshot/LambdaNodeJsLatestIntegDefaultTestDeployAssertD40B5C28.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-nodejs/test/integ.latest.js.snapshot/asset.30d328e47ab6c6a4d0d137aac9e53e30955ac7469bcb2be4a49f9baf5cfc2f9c.bundle/index.js
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-nodejs/test/integ.latest.js.snapshot/asset.f9b0f4d8625cbe898e0489f6ac67297230716f8ccea80be6f26c8793a9e220ac/index.js
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-nodejs/test/integ.latest.js.snapshot/asset.f9b0f4d8625cbe898e0489f6ac67297230716f8ccea80be6f26c8793a9e220ac/node_modules/.yarn-integrity
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-nodejs/test/integ.latest.js.snapshot/asset.f9b0f4d8625cbe898e0489f6ac67297230716f8ccea80be6f26c8793a9e220ac/node_modules/delay/index.d.ts
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-nodejs/test/integ.latest.js.snapshot/asset.f9b0f4d8625cbe898e0489f6ac67297230716f8ccea80be6f26c8793a9e220ac/node_modules/delay/index.js
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-nodejs/test/integ.latest.js.snapshot/asset.f9b0f4d8625cbe898e0489f6ac67297230716f8ccea80be6f26c8793a9e220ac/node_modules/delay/license
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-nodejs/test/integ.latest.js.snapshot/asset.f9b0f4d8625cbe898e0489f6ac67297230716f8ccea80be6f26c8793a9e220ac/node_modules/delay/package.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-nodejs/test/integ.latest.js.snapshot/asset.f9b0f4d8625cbe898e0489f6ac67297230716f8ccea80be6f26c8793a9e220ac/node_modules/delay/readme.md
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-nodejs/test/integ.latest.js.snapshot/asset.f9b0f4d8625cbe898e0489f6ac67297230716f8ccea80be6f26c8793a9e220ac/package.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-nodejs/test/integ.latest.js.snapshot/asset.f9b0f4d8625cbe898e0489f6ac67297230716f8ccea80be6f26c8793a9e220ac/yarn.lock
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-nodejs/test/integ.latest.js.snapshot/cdk-integ-lambda-nodejs-latest.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-nodejs/test/integ.latest.js.snapshot/cdk-integ-lambda-nodejs-latest.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-nodejs/test/integ.latest.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-nodejs/test/integ.latest.js.snapshot/tree.json
  packages/@aws-cdk/cloudformation-diff/package.json
  packages/@aws-cdk/custom-resource-handlers/package.json
  packages/@aws-cdk/cx-api/FEATURE_FLAGS.md
  packages/@aws-cdk/integ-runner/THIRD_PARTY_LICENSES
  packages/@aws-cdk/integ-tests-alpha/package.json
  packages/@aws-cdk/sdk-v2-to-v3-adapter/package.json
  packages/aws-cdk-lib/cx-api/FEATURE_FLAGS.md
  packages/aws-cdk-lib/package.json
  packages/aws-cdk/THIRD_PARTY_LICENSES
  packages/aws-cdk/lib/init-templates/app/typescript/package.json
  packages/aws-cdk/lib/init-templates/lib/typescript/package.json
  packages/aws-cdk/lib/init-templates/sample-app/typescript/package.json
  packages/aws-cdk/package.json
  packages/cdk-assets/package.json
  tools/@aws-cdk/cdk-build-tools/package.json
  tools/@aws-cdk/lazify/package.json
  tools/@aws-cdk/node-bundle/package.json
  yarn.lock
Labels: p2, dependencies, contribution/core, auto-approve

#29522 feat(elasticloadbalancingv2): enforce security group inbound rules prop
  packages/@aws-cdk-testing/framework-integ/test/aws-elasticloadbalancingv2/test/integ.nlb.enforce-sg-inbound-rules.js.snapshot/IntegTestDefaultTestDeployAssertE3E7D2A4.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-elasticloadbalancingv2/test/integ.nlb.enforce-sg-inbound-rules.js.snapshot/IntegTestDefaultTestDeployAssertE3E7D2A4.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-elasticloadbalancingv2/test/integ.nlb.enforce-sg-inbound-rules.js.snapshot/aws-cdk-elbv2-integ-enforce-sg-inbound-rules.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-elasticloadbalancingv2/test/integ.nlb.enforce-sg-inbound-rules.js.snapshot/aws-cdk-elbv2-integ-enforce-sg-inbound-rules.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-elasticloadbalancingv2/test/integ.nlb.enforce-sg-inbound-rules.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-elasticloadbalancingv2/test/integ.nlb.enforce-sg-inbound-rules.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-elasticloadbalancingv2/test/integ.nlb.enforce-sg-inbound-rules.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-elasticloadbalancingv2/test/integ.nlb.enforce-sg-inbound-rules.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-elasticloadbalancingv2/test/integ.nlb.enforce-sg-inbound-rules.ts
  packages/@aws-cdk-testing/framework-integ/test/aws-elasticloadbalancingv2/test/integ.nlb.js.snapshot/asset.310f432b946edeef3316f39f32b344b6bdc401a3b438433db42adadab1bf5e17.bundle/index.js
  packages/aws-cdk-lib/aws-elasticloadbalancingv2/README.md
  packages/aws-cdk-lib/aws-elasticloadbalancingv2/lib/nlb/network-load-balancer.ts
  packages/aws-cdk-lib/aws-elasticloadbalancingv2/test/nlb/load-balancer.test.ts
Labels: p2, feature-request, distinguished-contributor

#29545 docs(stepfunctions-tasks): update the table of contents and headers in README
  packages/aws-cdk-lib/aws-stepfunctions-tasks/README.md
Labels: p2, valued-contributor

#29504 feat(elasticloadbalancingv2): client keepalive for ALB
  packages/@aws-cdk-testing/framework-integ/test/aws-elasticloadbalancingv2/test/integ.alb.attributes.js.snapshot/Elbv2TestDefaultTestDeployAssert82DC2DEA.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-elasticloadbalancingv2/test/integ.alb.attributes.js.snapshot/aws-cdk-elbv2-integ.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-elasticloadbalancingv2/test/integ.alb.attributes.js.snapshot/aws-cdk-elbv2-integ.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-elasticloadbalancingv2/test/integ.alb.attributes.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-elasticloadbalancingv2/test/integ.alb.attributes.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-elasticloadbalancingv2/test/integ.alb.attributes.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-elasticloadbalancingv2/test/integ.alb.attributes.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-elasticloadbalancingv2/test/integ.alb.attributes.ts
  packages/aws-cdk-lib/aws-elasticloadbalancingv2/README.md
  packages/aws-cdk-lib/aws-elasticloadbalancingv2/lib/alb/application-load-balancer.ts
  packages/aws-cdk-lib/aws-elasticloadbalancingv2/test/alb/load-balancer.test.ts
Labels: p2, feature-request, star-contributor

#29537 chore(route53): support new partitions in route53 cross-account delegator
  packages/@aws-cdk-testing/framework-integ/test/aws-route53/test/integ.cross-account-zone-delegation.js.snapshot/asset.5e6e9858d1b0f5ba042ceacb850822cb985861c7bd174ceb7659a10daebe43e9/index.js
  packages/@aws-cdk-testing/framework-integ/test/aws-route53/test/integ.cross-account-zone-delegation.js.snapshot/asset.aca4a134bf7ace6088b21213be7ab4357e3705f714362b690d76376b8f1df53a/__entrypoint__.js
  packages/@aws-cdk-testing/framework-integ/test/aws-route53/test/integ.cross-account-zone-delegation.js.snapshot/asset.aca4a134bf7ace6088b21213be7ab4357e3705f714362b690d76376b8f1df53a/index.js
  packages/@aws-cdk-testing/framework-integ/test/aws-route53/test/integ.cross-account-zone-delegation.js.snapshot/child-opt-in-stack.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-route53/test/integ.cross-account-zone-delegation.js.snapshot/child-opt-in-stack.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-route53/test/integ.cross-account-zone-delegation.js.snapshot/child-stack.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-route53/test/integ.cross-account-zone-delegation.js.snapshot/child-stack.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-route53/test/integ.cross-account-zone-delegation.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-route53/test/integ.rename-cross-account-zone-delegation.js.snapshot/asset.5e6e9858d1b0f5ba042ceacb850822cb985861c7bd174ceb7659a10daebe43e9/index.js
  packages/@aws-cdk-testing/framework-integ/test/aws-route53/test/integ.rename-cross-account-zone-delegation.js.snapshot/asset.aca4a134bf7ace6088b21213be7ab4357e3705f714362b690d76376b8f1df53a/__entrypoint__.js
  packages/@aws-cdk-testing/framework-integ/test/aws-route53/test/integ.rename-cross-account-zone-delegation.js.snapshot/asset.aca4a134bf7ace6088b21213be7ab4357e3705f714362b690d76376b8f1df53a/index.js
  packages/@aws-cdk-testing/framework-integ/test/aws-route53/test/integ.rename-cross-account-zone-delegation.js.snapshot/child-stack.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-route53/test/integ.rename-cross-account-zone-delegation.js.snapshot/child-stack.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-route53/test/integ.rename-cross-account-zone-delegation.js.snapshot/manifest.json
  packages/@aws-cdk/custom-resource-handlers/lib/aws-route53/cross-account-zone-delegation-handler/index.ts
Labels: p2, pr/needs-community-review, beginning-contributor

#29566 feat(apigatewayv2): add missing `WebSocketIntegration` props
  packages/@aws-cdk-testing/framework-integ/test/aws-apigatewayv2-integrations/test/websocket/integ.aws.js.snapshot/integ-aws-websocket-integration.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-apigatewayv2-integrations/test/websocket/integ.aws.js.snapshot/integ-aws-websocket-integration.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-apigatewayv2-integrations/test/websocket/integ.aws.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-apigatewayv2-integrations/test/websocket/integ.aws.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-apigatewayv2-integrations/test/websocket/integ.aws.ts
  packages/@aws-cdk-testing/framework-integ/test/aws-apigatewayv2-integrations/test/websocket/integ.lambda.js.snapshot/WebSocketApiInteg.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-apigatewayv2-integrations/test/websocket/integ.lambda.js.snapshot/WebSocketApiInteg.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-apigatewayv2-integrations/test/websocket/integ.lambda.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-apigatewayv2-integrations/test/websocket/integ.lambda.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-apigatewayv2-integrations/test/websocket/integ.lambda.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-apigatewayv2-integrations/test/websocket/integ.lambda.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-apigatewayv2-integrations/test/websocket/integ.lambda.ts
  packages/aws-cdk-lib/aws-apigatewayv2-integrations/README.md
  packages/aws-cdk-lib/aws-apigatewayv2-integrations/lib/websocket/aws.ts
  packages/aws-cdk-lib/aws-apigatewayv2-integrations/lib/websocket/lambda.ts
  packages/aws-cdk-lib/aws-apigatewayv2-integrations/test/websocket/aws.test.ts
  packages/aws-cdk-lib/aws-apigatewayv2-integrations/test/websocket/lambda.test.ts
  packages/aws-cdk-lib/aws-apigatewayv2/lib/websocket/integration.ts
Labels: p2, distinguished-contributor

#29468 chore(bedrock): update foundation models
  packages/aws-cdk-lib/aws-bedrock/lib/foundation-model.ts
Labels: p2, distinguished-contributor

#29605 feat: update L1 CloudFormation resource definitions
  packages/@aws-cdk/cloudformation-diff/package.json
  packages/@aws-cdk/integ-runner/package.json
  packages/aws-cdk-lib/package.json
  tools/@aws-cdk/spec2cdk/package.json
  yarn.lock
Labels: p2, dependencies, contribution/core, pr-linter/exempt-readme, pr-linter/exempt-test, auto-approve, pr-linter/exempt-integ-test, pr/needs-maintainer-review

#29606 feat: update L1 CloudFormation resource definitions
  packages/@aws-cdk/cloudformation-diff/package.json
  packages/@aws-cdk/integ-runner/package.json
  packages/aws-cdk-lib/package.json
  tools/@aws-cdk/spec2cdk/package.json
  yarn.lock
Labels: p2, dependencies, contribution/core, pr-linter/exempt-readme, pr-linter/exempt-test, auto-approve, pr-linter/exempt-integ-test

#29577 revert: "feat(cli): warn of non-existent stacks in `cdk destroy`"
  packages/aws-cdk/lib/cdk-toolkit.ts
Labels: p2, contribution/core, pr-linter/cli-integ-tested

#28448 fix(cli): ecs hotswap deployment waits correctly for success or failure
  packages/@aws-cdk-testing/cli-integ/lib/aws.ts
  packages/@aws-cdk-testing/cli-integ/resources/cdk-apps/app/app.js
  packages/@aws-cdk-testing/cli-integ/tests/cli-integ-tests/cli.integtest.ts
  packages/aws-cdk/lib/api/hotswap/ecs-services.ts
Labels: bug, p1, effort/medium, pr-linter/exempt-integ-test, beginning-contributor, pr-linter/cli-integ-tested, pr-linter/exemption-requested

#29624 chore(merge-back): 2.134.0
  CHANGELOG.v2.alpha.md
  CHANGELOG.v2.md
  packages/aws-cdk-lib/cx-api/FEATURE_FLAGS.md
  packages/aws-cdk-lib/cx-api/lib/features.ts
  version.v2.json
Labels: p2, pr/needs-community-review, pr/no-squash, auto-approve

#29382 fix: add validation for ALB access log bucket when KMS key is provided
  packages/aws-cdk-lib/aws-elasticloadbalancingv2/README.md
  packages/aws-cdk-lib/aws-elasticloadbalancingv2/lib/alb/application-load-balancer.ts
  packages/aws-cdk-lib/aws-elasticloadbalancingv2/test/alb/load-balancer.test.ts
  packages/aws-cdk-lib/rosetta/aws_elasticloadbalancingv2/default.ts-fixture
Labels: bug, p2, effort/small, contribution/core, pr-linter/exempt-integ-test

#29451 fix(cli): cdk watch for Lambdas with Advanced Logging Controls do not stream logs to the terminal
  packages/aws-cdk/lib/api/evaluate-cloudformation-template.ts
  packages/aws-cdk/lib/api/logs/find-cloudwatch-logs.ts
  packages/aws-cdk/test/api/logs/find-cloudwatch-logs.test.ts
Labels: bug, p1, pr-linter/exempt-integ-test, beginning-contributor, pr-linter/cli-integ-tested

#29582 docs(lambda-event-source): improve docstring in KinesisEventSourceProps
  packages/aws-cdk-lib/aws-lambda-event-sources/lib/stream.ts
Labels: p2, effort/small, beginning-contributor

#29591 docs(sns): remove an unused variable declaration in Archive Policy
  packages/aws-cdk-lib/aws-sns/README.md
Labels: p2, beginning-contributor

#29599 docs(custom-resources): fix dead links in custom-resources package documentation
  packages/aws-cdk-lib/custom-resources/README.md
Labels: p2, beginning-contributor

#29630 chore: npm-check-updates && yarn upgrade
  package.json
  packages/@aws-cdk-testing/cli-integ/package.json
  packages/@aws-cdk-testing/framework-integ/package.json
  packages/@aws-cdk/cloudformation-diff/package.json
  packages/@aws-cdk/custom-resource-handlers/package.json
  packages/@aws-cdk/cx-api/FEATURE_FLAGS.md
  packages/@aws-cdk/integ-runner/THIRD_PARTY_LICENSES
  packages/aws-cdk-lib/package.json
  packages/aws-cdk/THIRD_PARTY_LICENSES
  packages/aws-cdk/package.json
  packages/awslint/package.json
  packages/cdk-assets/package.json
  tools/@aws-cdk/cdk-build-tools/package.json
  yarn.lock
Labels: p2, dependencies, contribution/core, auto-approve

#29595 fix(route53): allow records with a weight of 0
  packages/@aws-cdk-testing/framework-integ/test/aws-route53/test/integ.weighted-record.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-route53/test/integ.weighted-record.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-route53/test/integ.weighted-record.js.snapshot/weighted-record.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-route53/test/integ.weighted-record.js.snapshot/weighted-record.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-route53/test/integ.weighted-record.ts
  packages/aws-cdk-lib/aws-route53/lib/record-set.ts
  packages/aws-cdk-lib/aws-route53/test/record-set.test.ts
Labels: bug, p1, effort/small, beginning-contributor

#29435 chore(ec2): update WindowsVersions enum
  packages/aws-cdk-lib/aws-ec2/lib/windows-versions.ts
Labels: p2, distinguished-contributor

#29633 fix(events-targets): hardcoded AWS partition in ECS task resource ARN
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs-patterns/test/ec2/integ.scheduled-ecs-task.js.snapshot/aws-ecs-integ-ecs.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs-patterns/test/ec2/integ.scheduled-ecs-task.js.snapshot/aws-ecs-integ-ecs.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs-patterns/test/ec2/integ.scheduled-ecs-task.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs-patterns/test/ec2/integ.scheduled-ecs-task.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs-patterns/test/fargate/integ.runtime-platform-application-load-balanced-fargate-service.js.snapshot/aws-ecs-runtime-integ.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs-patterns/test/fargate/integ.runtime-platform-application-load-balanced-fargate-service.js.snapshot/aws-ecs-runtime-integ.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs-patterns/test/fargate/integ.runtime-platform-application-load-balanced-fargate-service.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs-patterns/test/fargate/integ.runtime-platform-application-load-balanced-fargate-service.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs-patterns/test/fargate/integ.scheduled-fargate-task.js.snapshot/aws-fargate-integ.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs-patterns/test/fargate/integ.scheduled-fargate-task.js.snapshot/aws-fargate-integ.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs-patterns/test/fargate/integ.scheduled-fargate-task.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs-patterns/test/fargate/integ.scheduled-fargate-task.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-events-targets/test/ecs/integ.event-ec2-task.js.snapshot/aws-ecs-integ-ecs.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-events-targets/test/ecs/integ.event-ec2-task.js.snapshot/aws-ecs-integ-ecs.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-events-targets/test/ecs/integ.event-ec2-task.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-events-targets/test/ecs/integ.event-ec2-task.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-events-targets/test/ecs/integ.event-fargate-task.js.snapshot/aws-ecs-integ-fargate.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-events-targets/test/ecs/integ.event-fargate-task.js.snapshot/aws-ecs-integ-fargate.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-events-targets/test/ecs/integ.event-fargate-task.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-events-targets/test/ecs/integ.event-fargate-task.js.snapshot/tree.json
  packages/aws-cdk-lib/aws-events-targets/lib/ecs-task.ts
Labels: bug, p0, effort/small, contribution/core, pr-linter/exempt-test, pr-linter/exempt-integ-test

#29634 docs(opensearchservice): change default value's description for `multiAzWithStandbyEnabled`
  packages/aws-cdk-lib/aws-opensearchservice/lib/domain.ts
Labels: p2, pr/needs-community-review, distinguished-contributor

#29607 chore(opensearchservice): t3 instance type does not support Multi-AZ with standby feature
  packages/aws-cdk-lib/aws-opensearchservice/lib/domain.ts
  packages/aws-cdk-lib/aws-opensearchservice/test/domain.test.ts
Labels: p2, star-contributor

#29543 feat(sns): add signature version prop
  packages/@aws-cdk-testing/framework-integ/test/aws-sns/test/integ.sns.js.snapshot/SNSInteg.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-sns/test/integ.sns.js.snapshot/SNSInteg.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-sns/test/integ.sns.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-sns/test/integ.sns.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-sns/test/integ.sns.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-sns/test/integ.sns.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-sns/test/integ.sns.ts
  packages/aws-cdk-lib/aws-sns/README.md
  packages/aws-cdk-lib/aws-sns/lib/topic.ts
  packages/aws-cdk-lib/aws-sns/test/sns.test.ts
Labels: p2, feature-request, effort/medium, distinguished-contributor

#29563 fix(ec2): global vpc endpoint support
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.vpc-global-endpoint.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.vpc-global-endpoint.js.snapshot/globalvpcendpointDefaultTestDeployAssertE52DED6D.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.vpc-global-endpoint.js.snapshot/globalvpcendpointDefaultTestDeployAssertE52DED6D.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.vpc-global-endpoint.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.vpc-global-endpoint.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.vpc-global-endpoint.js.snapshot/test-globalvpcendpoint.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.vpc-global-endpoint.js.snapshot/test-globalvpcendpoint.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.vpc-global-endpoint.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.vpc-global-endpoint.ts
  packages/aws-cdk-lib/aws-ec2/lib/vpc-endpoint.ts
  packages/aws-cdk-lib/aws-ec2/test/vpc-endpoint.test.ts
Labels: bug, p2, effort/medium, distinguished-contributor
