Repository aws/aws-cdk, pull requests merged in 2024-11, with the labels that each got.

#31969 chore: update CHANGELOG.v2.alpha.md to announce kinesisfirehose as developer preview
  CHANGELOG.v2.alpha.md
Labels: p2, contribution/core

#31909 feat(kinesis): support resource policy for a data stream
  packages/@aws-cdk-testing/framework-integ/test/aws-kinesis/test/integ.resource-policy.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-kinesis/test/integ.resource-policy.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-kinesis/test/integ.resource-policy.js.snapshot/integkinesisresourcepolicyDefaultTestDeployAssert52C5D16C.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-kinesis/test/integ.resource-policy.js.snapshot/integkinesisresourcepolicyDefaultTestDeployAssert52C5D16C.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-kinesis/test/integ.resource-policy.js.snapshot/kinesis-resource-policy.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-kinesis/test/integ.resource-policy.js.snapshot/kinesis-resource-policy.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-kinesis/test/integ.resource-policy.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-kinesis/test/integ.resource-policy.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-kinesis/test/integ.resource-policy.ts
  packages/aws-cdk-lib/aws-kinesis/README.md
  packages/aws-cdk-lib/aws-kinesis/lib/index.ts
  packages/aws-cdk-lib/aws-kinesis/lib/resource-policy.ts
  packages/aws-cdk-lib/aws-kinesis/lib/stream.ts
  packages/aws-cdk-lib/aws-kinesis/test/resource-policy.test.ts
  packages/aws-cdk-lib/aws-kinesis/test/stream.test.ts
  packages/aws-cdk-lib/awslint.json
Labels: p2, feature-request, effort/medium, distinguished-contributor

#31970 chore: update Contributors File
  CONTRIBUTORS.md
Labels: p2, pr/needs-community-review, auto-approve

#31962 feat(rds): configure `autoMinorVersionUpgrade` for a database cluster
  packages/@aws-cdk-testing/framework-integ/test/aws-rds/test/integ.cluster.js.snapshot/aws-cdk-rds-integ-with-feature-flag.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-rds/test/integ.cluster.js.snapshot/aws-cdk-rds-integ-with-feature-flag.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-rds/test/integ.cluster.js.snapshot/aws-cdk-rds-integ.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-rds/test/integ.cluster.js.snapshot/aws-cdk-rds-integ.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-rds/test/integ.cluster.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-rds/test/integ.cluster.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-rds/test/integ.cluster.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-rds/test/integ.cluster.js.snapshot/testrdsclusterDefaultTestDeployAssert23E53F17.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-rds/test/integ.cluster.js.snapshot/testrdsclusterwithfeatureflagDefaultTestDeployAssert8E2E540B.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-rds/test/integ.cluster.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-rds/test/integ.cluster.ts
  packages/aws-cdk-lib/aws-rds/README.md
  packages/aws-cdk-lib/aws-rds/lib/cluster.ts
  packages/aws-cdk-lib/aws-rds/test/cluster.test.ts
Labels: p2, distinguished-contributor

#31904 refactor: gate access to environment SDK behind new class
  packages/aws-cdk/lib/api/bootstrap/bootstrap-props.ts
  packages/aws-cdk/lib/api/deploy-stack.ts
  packages/aws-cdk/lib/api/deployments.ts
  packages/aws-cdk/lib/api/environment-access.ts
  packages/aws-cdk/lib/api/logs/find-cloudwatch-logs.ts
  packages/aws-cdk/lib/api/util/cloudformation.ts
  packages/aws-cdk/lib/api/util/placeholders.ts
  packages/aws-cdk/lib/util/type-brands.ts
  packages/aws-cdk/test/api/cloudformation-deployments.test.ts
  packages/aws-cdk/test/cdk-toolkit.test.ts
  packages/aws-cdk/test/version.test.ts
Labels: p2, contribution/core, pr-linter/cli-integ-tested

#31937 fix(cli): asset uploads fail if Object Lock is enabled on access bucket
  packages/@aws-cdk-testing/cli-integ/lib/aws.ts
  packages/@aws-cdk-testing/cli-integ/tests/cli-integ-tests/cli.integtest.ts
  packages/@aws-cdk/integ-runner/package.json
  packages/aws-cdk/lib/api/aws-auth/sdk.ts
  packages/aws-cdk/lib/api/plugin/plugin.ts
  packages/aws-cdk/package.json
  packages/aws-cdk/test/api/plugin/plugin-host.test.ts
  yarn.lock
Labels: p2, contribution/core, pr-linter/exempt-test, pr-linter/exempt-integ-test, pr-linter/cli-integ-tested

#31955 feat(route53): support HTTPS, SSHFP, SVCB, and TLSA DNS resource record
  packages/aws-cdk-lib/aws-route53/lib/record-set.ts
Labels: p2, pr-linter/exempt-readme, pr-linter/exempt-test, pr-linter/exempt-integ-test, distinguished-contributor

#31948 fix(opensearch): add I4G to list of OpenSearch nodes not requiring EBS volumes
  packages/@aws-cdk-testing/framework-integ/test/aws-opensearchservice/test/integ.opensearch.ebs.js.snapshot/IntegDefaultTestDeployAssert4E6713E1.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-opensearchservice/test/integ.opensearch.ebs.js.snapshot/IntegDefaultTestDeployAssert4E6713E1.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-opensearchservice/test/integ.opensearch.ebs.js.snapshot/cdk-integ-opensearch-instance-store.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-opensearchservice/test/integ.opensearch.ebs.js.snapshot/cdk-integ-opensearch-instance-store.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-opensearchservice/test/integ.opensearch.ebs.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-opensearchservice/test/integ.opensearch.ebs.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-opensearchservice/test/integ.opensearch.ebs.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-opensearchservice/test/integ.opensearch.ebs.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-opensearchservice/test/integ.opensearch.ebs.ts
  packages/aws-cdk-lib/aws-opensearchservice/lib/domain.ts
  packages/aws-cdk-lib/aws-opensearchservice/test/domain.test.ts
Labels: bug, p2, effort/small, beginning-contributor

#31980 chore(pipes-sources): update readme to use SqsTarget
  packages/@aws-cdk/aws-pipes-sources-alpha/README.md
  packages/@aws-cdk/aws-pipes-sources-alpha/rosetta/default.ts-fixture
Labels: p2, distinguished-contributor

#31959 chore(amplify): domain name validation
  packages/@aws-cdk/aws-amplify-alpha/lib/domain.ts
  packages/@aws-cdk/aws-amplify-alpha/test/domain.test.ts
  packages/@aws-cdk/aws-amplify-alpha/test/integ.app-custom-domain.js.snapshot/amplifyappcustomdomainintegDefaultTestDeployAssert5F8CD1EB.assets.json
  packages/@aws-cdk/aws-amplify-alpha/test/integ.app-custom-domain.js.snapshot/cdk-amplify-app-custom-domain.assets.json
  packages/@aws-cdk/aws-amplify-alpha/test/integ.app-custom-domain.js.snapshot/cdk-amplify-app-custom-domain.template.json
  packages/@aws-cdk/aws-amplify-alpha/test/integ.app-custom-domain.js.snapshot/cdk.out
  packages/@aws-cdk/aws-amplify-alpha/test/integ.app-custom-domain.js.snapshot/integ.json
  packages/@aws-cdk/aws-amplify-alpha/test/integ.app-custom-domain.js.snapshot/manifest.json
  packages/@aws-cdk/aws-amplify-alpha/test/integ.app-custom-domain.js.snapshot/tree.json
  packages/@aws-cdk/aws-amplify-alpha/test/integ.app-custom-domain.ts
Labels: p2, distinguished-contributor

#31986 chore(pipes-targets): remove dependency with pipes-sources
  packages/@aws-cdk/aws-pipes-sources-alpha/test/integ.dynamodb.ts
  packages/@aws-cdk/aws-pipes-sources-alpha/test/integ.kinesis.ts
  packages/@aws-cdk/aws-pipes-sources-alpha/test/integ.sqs.ts
  packages/@aws-cdk/aws-pipes-targets-alpha/package.json
  packages/@aws-cdk/aws-pipes-targets-alpha/test/integ.api-destination.ts
  packages/@aws-cdk/aws-pipes-targets-alpha/test/integ.cloudwatch-logs.ts
  packages/@aws-cdk/aws-pipes-targets-alpha/test/integ.event-bridge.ts
  packages/@aws-cdk/aws-pipes-targets-alpha/test/integ.kinesis.ts
  packages/@aws-cdk/aws-pipes-targets-alpha/test/integ.lambda.ts
  packages/@aws-cdk/aws-pipes-targets-alpha/test/integ.sagemaker.ts
  packages/@aws-cdk/aws-pipes-targets-alpha/test/integ.sqs.ts
  packages/@aws-cdk/aws-pipes-targets-alpha/test/integ.stepfunctions.ts
Labels: p2, pr/needs-community-review, distinguished-contributor

#31989 chore(neptune): engine version 1.3.4.0
  packages/@aws-cdk/aws-neptune-alpha/lib/cluster.ts
Labels: p2, distinguished-contributor

#31867 fix(dynamoDB): make TableV2 taggable
  packages/@aws-cdk-testing/framework-integ/test/aws-dynamodb/test/integ.dynamodb-v2.ondemand.js.snapshot/aws-cdk-global-table.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-dynamodb/test/integ.dynamodb-v2.ondemand.js.snapshot/awscdkglobaltableintegDefaultTestDeployAssertA2A9E81F.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-dynamodb/test/integ.dynamodb-v2.ondemand.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-dynamodb/test/integ.dynamodb-v2.ondemand.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-dynamodb/test/integ.dynamodb-v2.ondemand.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-dynamodb/test/integ.dynamodb-v2.ondemand.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-dynamodb/test/integ.table-v2-global.js.snapshot/aws-cdk-global-table.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-dynamodb/test/integ.table-v2-global.js.snapshot/aws-cdk-global-table.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-dynamodb/test/integ.table-v2-global.js.snapshot/awscdkglobaltableintegDefaultTestDeployAssertA2A9E81F.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-dynamodb/test/integ.table-v2-global.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-dynamodb/test/integ.table-v2-global.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-dynamodb/test/integ.table-v2-global.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-dynamodb/test/integ.table-v2-global.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-dynamodb/test/integ.table-v2-global.ts
  packages/aws-cdk-lib/aws-dynamodb/lib/table-v2.ts
  packages/aws-cdk-lib/aws-dynamodb/test/table-v2.test.ts
Labels: bug, p2, effort/small, repeat-contributor

#32007 feat: update L1 CloudFormation resource definitions
  packages/@aws-cdk/cloudformation-diff/package.json
  packages/@aws-cdk/integ-runner/package.json
  packages/aws-cdk-lib/package.json
  tools/@aws-cdk/spec2cdk/package.json
  yarn.lock
Labels: p2, dependencies, contribution/core, pr-linter/exempt-readme, pr-linter/exempt-test, auto-approve, pr-linter/exempt-integ-test

#31830 feat(glue-alpha): add job run queuing to Glue job
  packages/@aws-cdk/aws-glue-alpha/README.md
  packages/@aws-cdk/aws-glue-alpha/lib/job.ts
  packages/@aws-cdk/aws-glue-alpha/test/integ.job.js.snapshot/aws-glue-job.assets.json
  packages/@aws-cdk/aws-glue-alpha/test/integ.job.js.snapshot/aws-glue-job.template.json
  packages/@aws-cdk/aws-glue-alpha/test/integ.job.js.snapshot/cdk.out
  packages/@aws-cdk/aws-glue-alpha/test/integ.job.js.snapshot/integ.json
  packages/@aws-cdk/aws-glue-alpha/test/integ.job.js.snapshot/manifest.json
  packages/@aws-cdk/aws-glue-alpha/test/integ.job.js.snapshot/tree.json
  packages/@aws-cdk/aws-glue-alpha/test/integ.job.ts
  packages/@aws-cdk/aws-glue-alpha/test/job.test.ts
Labels: p2, feature-request, beginning-contributor, pr-linter/exemption-requested, pr/needs-maintainer-review

#31994 chore(glue): fix broken link
  packages/@aws-cdk/aws-glue-alpha/lib/job.ts
Labels: p2, distinguished-contributor

#32013 docs(cli): document what `--unstable` means for cdk gc
  packages/aws-cdk/README.md
  packages/aws-cdk/lib/cli.ts
Labels: p2, contribution/core, pr-linter/cli-integ-tested

#32015 chore(cdk): remove weekly metrics workflow
  .github/workflows/repo-metrics-weekly.yml
Labels: p2, contribution/core

#32016 chore(kinesisfirehose-alpha): update README to clarify default destination encryption setting
  packages/@aws-cdk/aws-kinesisfirehose-alpha/README.md
Labels: p2, contribution/core

#32014 chore(bedrock): support Claude 3.5 Haiku model
  packages/aws-cdk-lib/aws-bedrock/lib/foundation-model.ts
Labels: p2, distinguished-contributor

#32011 chore(s3): add more details to prune and destinationKeyPrefix property
  packages/aws-cdk-lib/aws-s3-deployment/lib/bucket-deployment.ts
Labels: p2, contribution/core

#32022 refactor: make node-bundle tests executable using ts-jest
  tools/@aws-cdk/node-bundle/package.json
  tools/@aws-cdk/node-bundle/src/api/bundle.ts
  tools/@aws-cdk/node-bundle/src/cli-main.ts
  tools/@aws-cdk/node-bundle/src/cli.ts
  tools/@aws-cdk/node-bundle/test/cli.test.ts
  tools/@aws-cdk/node-bundle/tsconfig.json
  yarn.lock
Labels: p2, contribution/core

#31850 refactor(cli): generate yargs configuration from TS
  lerna.json
  package.json
  packages/@aws-cdk/cli-lib-alpha/THIRD_PARTY_LICENSES
  packages/aws-cdk/CONTRIBUTING.md
  packages/aws-cdk/lib/cli.ts
  packages/aws-cdk/lib/config.ts
  packages/aws-cdk/lib/notices.ts
  packages/aws-cdk/lib/parse-command-line-arguments.ts
  packages/aws-cdk/package.json
  packages/aws-cdk/scripts/yargs-gen
  packages/aws-cdk/scripts/yargs-gen.ts
  packages/aws-cdk/test/notices.test.ts
  tools/@aws-cdk/yargs-gen/.eslintrc.js
  tools/@aws-cdk/yargs-gen/.gitignore
  tools/@aws-cdk/yargs-gen/.npmignore
  tools/@aws-cdk/yargs-gen/LICENSE
  tools/@aws-cdk/yargs-gen/NOTICE
  tools/@aws-cdk/yargs-gen/README.md
  tools/@aws-cdk/yargs-gen/jest.config.js
  tools/@aws-cdk/yargs-gen/lib/index.ts
  tools/@aws-cdk/yargs-gen/lib/yargs-gen.ts
  tools/@aws-cdk/yargs-gen/lib/yargs-types.ts
  tools/@aws-cdk/yargs-gen/package.json
  tools/@aws-cdk/yargs-gen/test/cli.test.ts
  tools/@aws-cdk/yargs-gen/tsconfig.json
  yarn.lock
Labels: p2, contribution/core, pr-linter/exempt-integ-test, pr-linter/cli-integ-tested

#31920 feat(cli): automatically roll back stacks if necessary
  packages/@aws-cdk-testing/cli-integ/resources/cdk-apps/rollback-test-app/app.js
  packages/@aws-cdk-testing/cli-integ/tests/cli-integ-tests/cli.integtest.ts
  packages/@aws-cdk/cloudformation-diff/lib/format.ts
  packages/aws-cdk/README.md
  packages/aws-cdk/lib/api/bootstrap/bootstrap-environment.ts
  packages/aws-cdk/lib/api/bootstrap/deploy-bootstrap.ts
  packages/aws-cdk/lib/api/deploy-stack.ts
  packages/aws-cdk/lib/api/hotswap-deployments.ts
  packages/aws-cdk/lib/api/util/cloudformation/stack-status.ts
  packages/aws-cdk/lib/cdk-toolkit.ts
  packages/aws-cdk/lib/diff.ts
  packages/aws-cdk/lib/import.ts
  packages/aws-cdk/test/api/bootstrap2.test.ts
  packages/aws-cdk/test/api/deploy-stack.test.ts
  packages/aws-cdk/test/api/hotswap/hotswap-test-setup.ts
  packages/aws-cdk/test/cdk-toolkit.test.ts
  packages/aws-cdk/test/diff.test.ts
Labels: bug, p1, effort/medium, contribution/core, pr-linter/exempt-readme, pr-linter/exempt-integ-test, pr-linter/cli-integ-tested

#32028 chore(assertions): remove unnecessary condition for if statement in `Template`
  packages/aws-cdk-lib/assertions/lib/template.ts
  packages/aws-cdk-lib/assertions/test/template.test.ts
Labels: p2, distinguished-contributor

#31991 chore(ec2): add missing interface VPC endpoint
  packages/aws-cdk-lib/aws-ec2/lib/vpc-endpoint.ts
Labels: p2, beginning-contributor, pr/needs-maintainer-review

#32030 chore: add saiyush to core contributors
  .github/workflows/github-merit-badger.yml
  .mergify.yml
Labels: p2, contribution/core

#32031 chore: add 5d to mergify and merit badger
  .github/workflows/github-merit-badger.yml
  .mergify.yml
Labels: p2, repeat-contributor

#32034 chore(scheduler-alpha): clean up readme
  packages/@aws-cdk/aws-scheduler-alpha/README.md
Labels: p2, contribution/core

#32029 chore(doc): update ROADMAP.md
  ROADMAP.md
Labels: p2, contribution/core

#32026 chore(synthetics): runtime puppeteer 9_1
  packages/aws-cdk-lib/aws-synthetics/lib/runtime.ts
Labels: p2, beginning-contributor

#31997 chore(docs): fix invalid anchor links in DESIGN_GUIDELINES
  docs/DESIGN_GUIDELINES.md
Labels: p2, beginning-contributor, pr/needs-maintainer-review

#30197 feat(synthetics): add `artifactS3Encryption` property to the Canary Construct.
  packages/@aws-cdk-testing/framework-integ/test/aws-synthetics/test/integ.canary-artifact-s3-encryption.js.snapshot/IntegCanaryTestDefaultTestDeployAssert3AD5A094.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-synthetics/test/integ.canary-artifact-s3-encryption.js.snapshot/IntegCanaryTestDefaultTestDeployAssert3AD5A094.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-synthetics/test/integ.canary-artifact-s3-encryption.js.snapshot/asset.44e9c4d7a5d3fd2d677e1a7e416b2b56f6b0104bd5eff9cac5557b4c65a9dc61/index.js
  packages/@aws-cdk-testing/framework-integ/test/aws-synthetics/test/integ.canary-artifact-s3-encryption.js.snapshot/asset.d57a897c2081bda5ce88819548c8b944dff49e721e1f7f7e9e3dd8323e6ccb0d/index.js
  packages/@aws-cdk-testing/framework-integ/test/aws-synthetics/test/integ.canary-artifact-s3-encryption.js.snapshot/canary-artifact-s3-encryption.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-synthetics/test/integ.canary-artifact-s3-encryption.js.snapshot/canary-artifact-s3-encryption.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-synthetics/test/integ.canary-artifact-s3-encryption.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-synthetics/test/integ.canary-artifact-s3-encryption.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-synthetics/test/integ.canary-artifact-s3-encryption.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-synthetics/test/integ.canary-artifact-s3-encryption.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-synthetics/test/integ.canary-artifact-s3-encryption.ts
  packages/aws-cdk-lib/aws-synthetics/README.md
  packages/aws-cdk-lib/aws-synthetics/lib/canary.ts
  packages/aws-cdk-lib/aws-synthetics/test/canary.test.ts
Labels: p2, feature-request, effort/medium, repeat-contributor

#32033 chore(scheduler-alpha): increase unit test coverage
  packages/@aws-cdk/aws-scheduler-alpha/lib/group.ts
  packages/@aws-cdk/aws-scheduler-alpha/test/group.test.ts
  packages/@aws-cdk/aws-scheduler-alpha/test/schedule-expression.test.ts
  packages/@aws-cdk/aws-scheduler-alpha/test/schedule.test.ts
Labels: p2, contribution/core

#32041 fix: deploy-time stack tags cause synthesis to fail
  packages/aws-cdk-lib/core/lib/stack-synthesizers/_shared.ts
  packages/aws-cdk-lib/core/test/stack.test.ts
Labels: p2, contribution/core, pr-linter/exempt-integ-test

#31899 feat(ivs): support recording configuration for channel
  packages/@aws-cdk/aws-ivs-alpha/README.md
  packages/@aws-cdk/aws-ivs-alpha/lib/channel.ts
  packages/@aws-cdk/aws-ivs-alpha/lib/index.ts
  packages/@aws-cdk/aws-ivs-alpha/lib/recording-configuration.ts
  packages/@aws-cdk/aws-ivs-alpha/lib/rendition-configuration.ts
  packages/@aws-cdk/aws-ivs-alpha/lib/thumbnail-configuration.ts
  packages/@aws-cdk/aws-ivs-alpha/lib/util.ts
  packages/@aws-cdk/aws-ivs-alpha/rosetta/default.ts-fixture
  packages/@aws-cdk/aws-ivs-alpha/test/integ.ivs-recording-configuration.js.snapshot/asset.44e9c4d7a5d3fd2d677e1a7e416b2b56f6b0104bd5eff9cac5557b4c65a9dc61/index.js
  packages/@aws-cdk/aws-ivs-alpha/test/integ.ivs-recording-configuration.js.snapshot/aws-cdk-ivs-recording-configuration-test.assets.json
  packages/@aws-cdk/aws-ivs-alpha/test/integ.ivs-recording-configuration.js.snapshot/aws-cdk-ivs-recording-configuration-test.template.json
  packages/@aws-cdk/aws-ivs-alpha/test/integ.ivs-recording-configuration.js.snapshot/cdk.out
  packages/@aws-cdk/aws-ivs-alpha/test/integ.ivs-recording-configuration.js.snapshot/integ.json
  packages/@aws-cdk/aws-ivs-alpha/test/integ.ivs-recording-configuration.js.snapshot/ivsrecordingconfigurationtestDefaultTestDeployAssert4AB65A05.assets.json
  packages/@aws-cdk/aws-ivs-alpha/test/integ.ivs-recording-configuration.js.snapshot/ivsrecordingconfigurationtestDefaultTestDeployAssert4AB65A05.template.json
  packages/@aws-cdk/aws-ivs-alpha/test/integ.ivs-recording-configuration.js.snapshot/manifest.json
  packages/@aws-cdk/aws-ivs-alpha/test/integ.ivs-recording-configuration.js.snapshot/tree.json
  packages/@aws-cdk/aws-ivs-alpha/test/integ.ivs-recording-configuration.ts
  packages/@aws-cdk/aws-ivs-alpha/test/recording-configuration.test.ts
Labels: p2, feature-request, effort/medium, distinguished-contributor

#32032 fix(scheduler-targets-alpha): add dlq policy to execution role instead of queue policy
  packages/@aws-cdk/aws-scheduler-targets-alpha/lib/target.ts
  packages/@aws-cdk/aws-scheduler-targets-alpha/test/codebuild-start-build.test.ts
  packages/@aws-cdk/aws-scheduler-targets-alpha/test/codepipeline-start-pipeline-execution.test.ts
  packages/@aws-cdk/aws-scheduler-targets-alpha/test/event-bridge-put-events.test.ts
  packages/@aws-cdk/aws-scheduler-targets-alpha/test/inspector-start-assessment-run.test.ts
  packages/@aws-cdk/aws-scheduler-targets-alpha/test/integ.schedule-with-dlq.js.snapshot/asset.d1a40db4788714a346364a87b7de0ff15b732e7367f085acf14f4a680c57c418.bundle/index.js
  packages/@aws-cdk/aws-scheduler-targets-alpha/test/integ.schedule-with-dlq.js.snapshot/aws-cdk-schedule-dlq.assets.json
  packages/@aws-cdk/aws-scheduler-targets-alpha/test/integ.schedule-with-dlq.js.snapshot/aws-cdk-schedule-dlq.template.json
  packages/@aws-cdk/aws-scheduler-targets-alpha/test/integ.schedule-with-dlq.js.snapshot/cdk.out
  packages/@aws-cdk/aws-scheduler-targets-alpha/test/integ.schedule-with-dlq.js.snapshot/integ.json
  packages/@aws-cdk/aws-scheduler-targets-alpha/test/integ.schedule-with-dlq.js.snapshot/integtestscheduledlqDefaultTestDeployAssertC769CF31.assets.json
  packages/@aws-cdk/aws-scheduler-targets-alpha/test/integ.schedule-with-dlq.js.snapshot/integtestscheduledlqDefaultTestDeployAssertC769CF31.template.json
  packages/@aws-cdk/aws-scheduler-targets-alpha/test/integ.schedule-with-dlq.js.snapshot/manifest.json
  packages/@aws-cdk/aws-scheduler-targets-alpha/test/integ.schedule-with-dlq.js.snapshot/tree.json
  packages/@aws-cdk/aws-scheduler-targets-alpha/test/integ.schedule-with-dlq.ts
  packages/@aws-cdk/aws-scheduler-targets-alpha/test/kinesis-data-firehose-put-record.test.ts
  packages/@aws-cdk/aws-scheduler-targets-alpha/test/kinesis-stream-put-record.test.ts
  packages/@aws-cdk/aws-scheduler-targets-alpha/test/lambda-invoke.test.ts
  packages/@aws-cdk/aws-scheduler-targets-alpha/test/sage-maker-start-pipeline-execution.test.ts
  packages/@aws-cdk/aws-scheduler-targets-alpha/test/sns-publish.test.ts
  packages/@aws-cdk/aws-scheduler-targets-alpha/test/sqs-send-message.test.ts
  packages/@aws-cdk/aws-scheduler-targets-alpha/test/stepfunction-start-execution.test.ts
Labels: p2, contribution/core, pr-linter/exempt-integ-test

#31985 feat(service-catalog): allow Product Stack to override analytics reporting and stack descriptions
  packages/@aws-cdk-testing/framework-integ/test/aws-servicecatalog/test/integ.product.js.snapshot/integ-servicecatalog-product.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-servicecatalog/test/integ.product.js.snapshot/integ-servicecatalog-product.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-servicecatalog/test/integ.product.js.snapshot/integservicecatalogproductSNSTopicProduct1B8D03934.product.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-servicecatalog/test/integ.product.js.snapshot/integservicecatalogproductSNSTopicProduct24C7C16DA.product.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-servicecatalog/test/integ.product.js.snapshot/integservicecatalogproductSNSTopicProduct3B51CF591.product.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-servicecatalog/test/integ.product.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-servicecatalog/test/integ.product.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-servicecatalog/test/integ.product.ts
  packages/@aws-cdk-testing/framework-integ/test/aws-servicecatalog/test/product-stack-snapshots/integservicecatalogproductProductStackHistory4D520FF1.integservicecatalogproductSNSTopicProduct3B51CF591.v1.product.template.json
  packages/aws-cdk-lib/aws-servicecatalog/lib/product-stack.ts
  packages/aws-cdk-lib/aws-servicecatalog/test/product-stack.test.ts
Labels: p2, feature-request, effort/medium, contribution/core, pr-linter/exempt-readme

#31990 feat(elasticloadbalancingv2): enable zonal shift for network load balancer
  packages/@aws-cdk-testing/framework-integ/test/aws-elasticloadbalancingv2/test/integ.nlb.attributes.js.snapshot/aws-cdk-nlb-attributes-integ.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-elasticloadbalancingv2/test/integ.nlb.attributes.js.snapshot/aws-cdk-nlb-attributes-integ.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-elasticloadbalancingv2/test/integ.nlb.attributes.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-elasticloadbalancingv2/test/integ.nlb.attributes.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-elasticloadbalancingv2/test/integ.nlb.attributes.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-elasticloadbalancingv2/test/integ.nlb.attributes.js.snapshot/nlbattlibutesintegDefaultTestDeployAssert2D727654.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-elasticloadbalancingv2/test/integ.nlb.attributes.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-elasticloadbalancingv2/test/integ.nlb.attributes.ts
  packages/aws-cdk-lib/aws-elasticloadbalancingv2/README.md
  packages/aws-cdk-lib/aws-elasticloadbalancingv2/lib/nlb/network-load-balancer.ts
  packages/aws-cdk-lib/aws-elasticloadbalancingv2/test/nlb/load-balancer.test.ts
Labels: p2, feature-request, effort/small, distinguished-contributor, pr/needs-maintainer-review

#32058 feat(rds): support minor engine versions for oracle
  packages/aws-cdk-lib/aws-rds/lib/instance-engine.ts
Labels: p2, pr/needs-community-review, pr-linter/exempt-readme, pr-linter/exempt-test, pr-linter/exempt-integ-test, distinguished-contributor

#32055 feat(rds): support minor versions for RDS for SQL Server
  packages/aws-cdk-lib/aws-rds/lib/instance-engine.ts
Labels: p2, pr-linter/exempt-readme, pr-linter/exempt-test, pr-linter/exempt-integ-test, distinguished-contributor

#30993 feat(kms): support KEY_AGREEMENT for keyUsage
  packages/@aws-cdk-testing/framework-integ/test/aws-kms/test/integ.key-key-agreement.js.snapshot/KeyAgreementIntegTestDefaultTestDeployAssert01B3C2C1.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-kms/test/integ.key-key-agreement.js.snapshot/KeyAgreementIntegTestDefaultTestDeployAssert01B3C2C1.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-kms/test/integ.key-key-agreement.js.snapshot/aws-cdk-kms-key-agreement.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-kms/test/integ.key-key-agreement.js.snapshot/aws-cdk-kms-key-agreement.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-kms/test/integ.key-key-agreement.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-kms/test/integ.key-key-agreement.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-kms/test/integ.key-key-agreement.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-kms/test/integ.key-key-agreement.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-kms/test/integ.key-key-agreement.ts
  packages/aws-cdk-lib/aws-kms/lib/key.ts
  packages/aws-cdk-lib/aws-kms/test/key.test.ts
Labels: p2, feature-request, effort/small, pr-linter/exempt-readme, distinguished-contributor

#32079 chore: code coverage configuration
  .github/workflows/codecov.yml
  CONTRIBUTING.md
  codecov.yml
  images/codecov-violations.png
  tools/@aws-cdk/cdk-build-tools/config/jest.config.js
Labels: p1, contribution/core, pr/needs-maintainer-review

#32090 feat: update L1 CloudFormation resource definitions
  packages/@aws-cdk/cloudformation-diff/package.json
  packages/@aws-cdk/integ-runner/package.json
  packages/aws-cdk-lib/package.json
  tools/@aws-cdk/spec2cdk/package.json
  yarn.lock
Labels: p2, dependencies, contribution/core, pr-linter/exempt-readme, pr-linter/exempt-test, auto-approve, pr-linter/exempt-integ-test

#32096 chore: make `@aws-cdk/yargs-gen` a devDependency
  packages/aws-cdk/lib/config.ts
  packages/aws-cdk/package.json
  tools/@aws-cdk/yargs-gen/lib/yargs-types.ts
Labels: p2, contribution/core, pr-linter/cli-integ-tested

#31993 feat(redshift): relocating a cluster
  packages/@aws-cdk/aws-redshift-alpha/README.md
  packages/@aws-cdk/aws-redshift-alpha/lib/cluster.ts
  packages/@aws-cdk/aws-redshift-alpha/test/cluster.test.ts
  packages/@aws-cdk/aws-redshift-alpha/test/integ.cluster-az-relocation.js.snapshot/AzRelocationClusterStack.assets.json
  packages/@aws-cdk/aws-redshift-alpha/test/integ.cluster-az-relocation.js.snapshot/AzRelocationClusterStack.template.json
  packages/@aws-cdk/aws-redshift-alpha/test/integ.cluster-az-relocation.js.snapshot/AzRelocationClusterStackIntegDefaultTestDeployAssert8A9859B5.assets.json
  packages/@aws-cdk/aws-redshift-alpha/test/integ.cluster-az-relocation.js.snapshot/AzRelocationClusterStackIntegDefaultTestDeployAssert8A9859B5.template.json
  packages/@aws-cdk/aws-redshift-alpha/test/integ.cluster-az-relocation.js.snapshot/cdk.out
  packages/@aws-cdk/aws-redshift-alpha/test/integ.cluster-az-relocation.js.snapshot/integ.json
  packages/@aws-cdk/aws-redshift-alpha/test/integ.cluster-az-relocation.js.snapshot/manifest.json
  packages/@aws-cdk/aws-redshift-alpha/test/integ.cluster-az-relocation.js.snapshot/tree.json
  packages/@aws-cdk/aws-redshift-alpha/test/integ.cluster-az-relocation.ts
Labels: p2, distinguished-contributor

#32116 chore(merge-back): 2.167.0
  CHANGELOG.v2.alpha.md
  CHANGELOG.v2.md
  version.v2.json
Labels: p2, pr/needs-community-review, pr/no-squash, auto-approve

#32125 chore: disable codecov from `v2-release` branch
  .github/workflows/codecov.yml
  .mergify.yml
  packages/aws-cdk/jest.config.js
  packages/aws-cdk/lib/api/logs/logs-monitor.ts
Labels: p2, pr/do-not-merge, contribution/core, pr-linter/cli-integ-tested

#32126 chore(contributing): mention manual PR merge option
  CONTRIBUTING.md
Labels: p2, contribution/core

#32134 fix(cli): failure to get credentials when session token is not set
  packages/aws-cdk/lib/api/aws-auth/awscli-compatible.ts
  packages/aws-cdk/test/api/aws-auth/awscli-compatible.test.ts
Labels: bug, p0, contribution/core, pr-linter/exempt-integ-test, pr-linter/cli-integ-tested

#32115 fix(cdk): use built-in source map support
  packages/@aws-cdk/cli-lib-alpha/THIRD_PARTY_LICENSES
  packages/@aws-cdk/cli-lib-alpha/package.json
  packages/aws-cdk/THIRD_PARTY_LICENSES
  packages/aws-cdk/bin/cdk
  packages/aws-cdk/lib/cli.ts
  packages/aws-cdk/package.json
  yarn.lock
Labels: p2, contribution/core, pr-linter/exempt-test, pr-linter/exempt-integ-test, pr-linter/cli-integ-tested

#32123 chore(scheduler-targets-alpha): readme updates
  packages/@aws-cdk/aws-scheduler-alpha/README.md
  packages/@aws-cdk/aws-scheduler-targets-alpha/README.md
Labels: p2, contribution/core

#29458 feat(stepfunctions-tasks): create scheduler
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/eventbridge-scheduler/integ.create-schedule.js.snapshot/PutEventsDefaultTestDeployAssert1A6BA3F3.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/eventbridge-scheduler/integ.create-schedule.js.snapshot/PutEventsDefaultTestDeployAssert1A6BA3F3.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/eventbridge-scheduler/integ.create-schedule.js.snapshot/asset.30e7020514effbaf2e0bf3983c7c37c6733aec254148a8f866da92fbbd7a4fb6.bundle/index.js
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/eventbridge-scheduler/integ.create-schedule.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/eventbridge-scheduler/integ.create-schedule.js.snapshot/createScheduleInteg.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/eventbridge-scheduler/integ.create-schedule.js.snapshot/createScheduleInteg.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/eventbridge-scheduler/integ.create-schedule.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/eventbridge-scheduler/integ.create-schedule.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/eventbridge-scheduler/integ.create-schedule.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/eventbridge-scheduler/integ.create-schedule.ts
  packages/aws-cdk-lib/aws-stepfunctions-tasks/README.md
  packages/aws-cdk-lib/aws-stepfunctions-tasks/lib/eventbridge-scheduler/create-schedule.ts
  packages/aws-cdk-lib/aws-stepfunctions-tasks/lib/index.ts
  packages/aws-cdk-lib/aws-stepfunctions-tasks/lib/schedule.ts
  packages/aws-cdk-lib/aws-stepfunctions-tasks/test/eventbridge-scheduler/create-schedule.test.ts
  packages/aws-cdk-lib/aws-stepfunctions-tasks/test/schedule.test.ts
Labels: p2, feature-request, effort/medium, star-contributor, pr/needs-maintainer-review

#31814 feat(elasticloadbalancingv2): support target group level cross-zone settings for ALB and NLB
  packages/@aws-cdk-testing/framework-integ/test/aws-elasticloadbalancingv2/test/integ.alb-target-group-cross-zone.js.snapshot/alb-target-group-cross-zone-stack.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-elasticloadbalancingv2/test/integ.alb-target-group-cross-zone.js.snapshot/alb-target-group-cross-zone-stack.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-elasticloadbalancingv2/test/integ.alb-target-group-cross-zone.js.snapshot/albtargetgroupcrosszoneteststackDefaultTestDeployAssertBFB9F5EA.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-elasticloadbalancingv2/test/integ.alb-target-group-cross-zone.js.snapshot/albtargetgroupcrosszoneteststackDefaultTestDeployAssertBFB9F5EA.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-elasticloadbalancingv2/test/integ.alb-target-group-cross-zone.js.snapshot/asset.bde7b5c89cb43285f884c94f0b9e17cdb0f5eb5345005114dd60342e0b8a85a1/__entrypoint__.js
  packages/@aws-cdk-testing/framework-integ/test/aws-elasticloadbalancingv2/test/integ.alb-target-group-cross-zone.js.snapshot/asset.bde7b5c89cb43285f884c94f0b9e17cdb0f5eb5345005114dd60342e0b8a85a1/index.js
  packages/@aws-cdk-testing/framework-integ/test/aws-elasticloadbalancingv2/test/integ.alb-target-group-cross-zone.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-elasticloadbalancingv2/test/integ.alb-target-group-cross-zone.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-elasticloadbalancingv2/test/integ.alb-target-group-cross-zone.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-elasticloadbalancingv2/test/integ.alb-target-group-cross-zone.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-elasticloadbalancingv2/test/integ.alb-target-group-cross-zone.ts
  packages/@aws-cdk-testing/framework-integ/test/aws-elasticloadbalancingv2/test/integ.nlb-target-group-cross-zone.js.snapshot/asset.bde7b5c89cb43285f884c94f0b9e17cdb0f5eb5345005114dd60342e0b8a85a1/__entrypoint__.js
  packages/@aws-cdk-testing/framework-integ/test/aws-elasticloadbalancingv2/test/integ.nlb-target-group-cross-zone.js.snapshot/asset.bde7b5c89cb43285f884c94f0b9e17cdb0f5eb5345005114dd60342e0b8a85a1/index.js
  packages/@aws-cdk-testing/framework-integ/test/aws-elasticloadbalancingv2/test/integ.nlb-target-group-cross-zone.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-elasticloadbalancingv2/test/integ.nlb-target-group-cross-zone.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-elasticloadbalancingv2/test/integ.nlb-target-group-cross-zone.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-elasticloadbalancingv2/test/integ.nlb-target-group-cross-zone.js.snapshot/nlb-target-group-cross-zone-stack.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-elasticloadbalancingv2/test/integ.nlb-target-group-cross-zone.js.snapshot/nlb-target-group-cross-zone-stack.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-elasticloadbalancingv2/test/integ.nlb-target-group-cross-zone.js.snapshot/nlbtargetgroupcrosszoneteststackDefaultTestDeployAssert1641E699.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-elasticloadbalancingv2/test/integ.nlb-target-group-cross-zone.js.snapshot/nlbtargetgroupcrosszoneteststackDefaultTestDeployAssert1641E699.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-elasticloadbalancingv2/test/integ.nlb-target-group-cross-zone.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-elasticloadbalancingv2/test/integ.nlb-target-group-cross-zone.ts
  packages/aws-cdk-lib/aws-elasticloadbalancingv2/README.md
  packages/aws-cdk-lib/aws-elasticloadbalancingv2/lib/shared/base-target-group.ts
  packages/aws-cdk-lib/aws-elasticloadbalancingv2/test/alb/target-group.test.ts
  packages/aws-cdk-lib/aws-elasticloadbalancingv2/test/nlb/target-group.test.ts
Labels: p2, feature-request, effort/small, distinguished-contributor, pr/needs-maintainer-review

#32133 fix(cli): region specified in `~/.aws/credentials` is ignored
  packages/aws-cdk/lib/api/aws-auth/awscli-compatible.ts
  packages/aws-cdk/test/api/aws-auth/awscli-compatible.test.ts
Labels: bug, p2, contribution/core, pr-linter/exempt-integ-test, pr-linter/cli-integ-tested

#32117 feat(rds): support 8.0.40 engine version for RDS for MySQL
  packages/aws-cdk-lib/aws-rds/lib/instance-engine.ts
Labels: p2, pr-linter/exempt-readme, pr-linter/exempt-test, pr-linter/exempt-integ-test, distinguished-contributor

#32105 fix(scheduler-targets-alpha): imported target resources as schedule target throws synth error
  packages/@aws-cdk/aws-scheduler-targets-alpha/README.md
  packages/@aws-cdk/aws-scheduler-targets-alpha/lib/codebuild-start-build.ts
  packages/@aws-cdk/aws-scheduler-targets-alpha/lib/codepipeline-start-pipeline-execution.ts
  packages/@aws-cdk/aws-scheduler-targets-alpha/lib/event-bridge-put-events.ts
  packages/@aws-cdk/aws-scheduler-targets-alpha/lib/inspector-start-assessment-run.ts
  packages/@aws-cdk/aws-scheduler-targets-alpha/lib/kinesis-data-firehose-put-record.ts
  packages/@aws-cdk/aws-scheduler-targets-alpha/lib/kinesis-stream-put-record.ts
  packages/@aws-cdk/aws-scheduler-targets-alpha/lib/lambda-invoke.ts
  packages/@aws-cdk/aws-scheduler-targets-alpha/lib/sage-maker-start-pipeline-execution.ts
  packages/@aws-cdk/aws-scheduler-targets-alpha/lib/sns-publish.ts
  packages/@aws-cdk/aws-scheduler-targets-alpha/lib/sqs-send-message.ts
  packages/@aws-cdk/aws-scheduler-targets-alpha/lib/stepfunctions-start-execution.ts
  packages/@aws-cdk/aws-scheduler-targets-alpha/lib/target.ts
  packages/@aws-cdk/aws-scheduler-targets-alpha/test/codebuild-start-build.test.ts
  packages/@aws-cdk/aws-scheduler-targets-alpha/test/codepipeline-start-pipeline-execution.test.ts
  packages/@aws-cdk/aws-scheduler-targets-alpha/test/event-bridge-put-events.test.ts
  packages/@aws-cdk/aws-scheduler-targets-alpha/test/inspector-start-assessment-run.test.ts
  packages/@aws-cdk/aws-scheduler-targets-alpha/test/kinesis-data-firehose-put-record.test.ts
  packages/@aws-cdk/aws-scheduler-targets-alpha/test/kinesis-stream-put-record.test.ts
  packages/@aws-cdk/aws-scheduler-targets-alpha/test/lambda-invoke.test.ts
  packages/@aws-cdk/aws-scheduler-targets-alpha/test/sage-maker-start-pipeline-execution.test.ts
  packages/@aws-cdk/aws-scheduler-targets-alpha/test/sns-publish.test.ts
  packages/@aws-cdk/aws-scheduler-targets-alpha/test/sqs-send-message.test.ts
  packages/@aws-cdk/aws-scheduler-targets-alpha/test/stepfunction-start-execution.test.ts
Labels: p2, contribution/core, pr-linter/exempt-integ-test

#32103 chore(ec2): billing interface vpc endpoint
  packages/aws-cdk-lib/aws-ec2/lib/vpc-endpoint.ts
Labels: p2, distinguished-contributor

#32140 chore(release): 2.167.1
  CHANGELOG.v2.alpha.md
  CHANGELOG.v2.md
  packages/aws-cdk/lib/api/aws-auth/awscli-compatible.ts
  packages/aws-cdk/test/api/aws-auth/awscli-compatible.test.ts
  version.v2.json
Labels: p2, contribution/core, pr/no-squash, pr-linter/cli-integ-tested

#32152 chore(merge-back): 2.167.1
  CHANGELOG.v2.alpha.md
  CHANGELOG.v2.md
  version.v2.json
Labels: p2, pr/needs-community-review, pr/no-squash, auto-approve

#32146 chore(secrets): bump semanticVersion for aws-gov-cloud
  packages/@aws-cdk-testing/framework-integ/test/aws-docdb/test/integ.cluster-rotation.lit.js.snapshot/aws-cdk-docdb-cluster-rotation.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-docdb/test/integ.cluster-rotation.lit.js.snapshot/aws-cdk-docdb-cluster-rotation.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-docdb/test/integ.cluster-rotation.lit.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-docdb/test/integ.cluster-rotation.lit.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-docdb/test/integ.cluster-rotation.lit.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-docdb/test/integ.cluster-rotation.lit.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-rds/test/integ.cluster-rotation.lit.js.snapshot/aws-cdk-rds-cluster-rotation.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-rds/test/integ.cluster-rotation.lit.js.snapshot/aws-cdk-rds-cluster-rotation.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-rds/test/integ.cluster-rotation.lit.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-rds/test/integ.cluster-rotation.lit.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-rds/test/integ.cluster-rotation.lit.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-rds/test/integ.cluster-rotation.lit.js.snapshot/testrdsclusterrotationDefaultTestDeployAssertCC761439.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-rds/test/integ.cluster-rotation.lit.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-rds/test/integ.cluster-snapshot.js.snapshot/cdk-integ-cluster-snapshot.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-rds/test/integ.cluster-snapshot.js.snapshot/cdk-integ-cluster-snapshot.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-rds/test/integ.cluster-snapshot.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-rds/test/integ.instance.lit.js.snapshot/asset.e4afb15788ec44ed9ff3377e1d131ba2768d7b2e2931bc000d1f2005879b3035/index.js
  packages/@aws-cdk-testing/framework-integ/test/aws-rds/test/integ.instance.lit.js.snapshot/aws-cdk-rds-instance.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-rds/test/integ.instance.lit.js.snapshot/aws-cdk-rds-instance.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-rds/test/integ.instance.lit.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-rds/test/integ.instance.lit.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-rds/test/integ.instance.lit.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-rds/test/integ.instance.lit.js.snapshot/tree.json
  packages/aws-cdk-lib/aws-secretsmanager/lib/secret-rotation.ts
Labels: p2, contribution/core, pr/needs-maintainer-review

#32165 fix(cli): `cdk diff` always falls back to template only diff
  packages/@aws-cdk-testing/cli-integ/resources/cdk-apps/app/app.js
  packages/@aws-cdk-testing/cli-integ/tests/cli-integ-tests/cli.integtest.ts
  packages/aws-cdk/lib/api/util/cloudformation.ts
Labels: bug, p1, contribution/core, pr-linter/exempt-integ-test, pr-linter/cli-integ-tested

#32164 fix(cli): the LoadBalancerProvider doesn't match LBs when querying by a subset of tags
  packages/aws-cdk/lib/context-providers/load-balancers.ts
  packages/aws-cdk/test/context-providers/load-balancers.test.ts
Labels: bug, p0, contribution/core, pr-linter/exempt-integ-test, pr-linter/cli-integ-tested

#32121 chore(opensearch): support OpenSearch version 2.17
  packages/@aws-cdk-testing/framework-integ/test/aws-opensearchservice/test/integ.opensearch.min.js.snapshot/cdk-integ-opensearch-min.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-opensearchservice/test/integ.opensearch.min.js.snapshot/cdk-integ-opensearch-min.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-opensearchservice/test/integ.opensearch.min.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-opensearchservice/test/integ.opensearch.min.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-opensearchservice/test/integ.opensearch.min.js.snapshot/integopenseachminDefaultTestDeployAssert0EB58658.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-opensearchservice/test/integ.opensearch.min.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-opensearchservice/test/integ.opensearch.min.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-opensearchservice/test/integ.opensearch.min.ts
  packages/aws-cdk-lib/aws-opensearchservice/lib/version.ts
  packages/aws-cdk-lib/aws-opensearchservice/test/domain.test.ts
Labels: p2, distinguished-contributor, pr-linter/exemption-requested

#32150 fix(scheduler-targets-alpha): kinesis data firehose target uses l1 instead of l2
  packages/@aws-cdk/aws-scheduler-targets-alpha/README.md
  packages/@aws-cdk/aws-scheduler-targets-alpha/lib/kinesis-data-firehose-put-record.ts
  packages/@aws-cdk/aws-scheduler-targets-alpha/package.json
  packages/@aws-cdk/aws-scheduler-targets-alpha/test/integ.kinesis-data-firehose-put-record.js.snapshot/asset.b98abee59e034ed29eeb601684dc34752baa86509a7d457d72305d4e19ecc80b.bundle/index.js
  packages/@aws-cdk/aws-scheduler-targets-alpha/test/integ.kinesis-data-firehose-put-record.js.snapshot/aws-cdk-scheduler-targets-firehose-put-record.assets.json
  packages/@aws-cdk/aws-scheduler-targets-alpha/test/integ.kinesis-data-firehose-put-record.js.snapshot/aws-cdk-scheduler-targets-firehose-put-record.template.json
  packages/@aws-cdk/aws-scheduler-targets-alpha/test/integ.kinesis-data-firehose-put-record.js.snapshot/integrationtestfirehoseputrecordDefaultTestDeployAssert781A189E.assets.json
  packages/@aws-cdk/aws-scheduler-targets-alpha/test/integ.kinesis-data-firehose-put-record.js.snapshot/integrationtestfirehoseputrecordDefaultTestDeployAssert781A189E.template.json
  packages/@aws-cdk/aws-scheduler-targets-alpha/test/integ.kinesis-data-firehose-put-record.js.snapshot/manifest.json
  packages/@aws-cdk/aws-scheduler-targets-alpha/test/integ.kinesis-data-firehose-put-record.js.snapshot/tree.json
  packages/@aws-cdk/aws-scheduler-targets-alpha/test/integ.kinesis-data-firehose-put-record.ts
  packages/@aws-cdk/aws-scheduler-targets-alpha/test/kinesis-data-firehose-put-record.test.ts
Labels: p2, contribution/core

#32143 chore(rds): support postgresql 17 engine version
  packages/aws-cdk-lib/aws-rds/lib/instance-engine.ts
Labels: p2, distinguished-contributor

#32163 fix(cli): externally managed stack notification arns are deleted on `deploy`
  allowed-breaking-changes.txt
  packages/@aws-cdk-testing/cli-integ/resources/cdk-apps/app/app.js
  packages/@aws-cdk-testing/cli-integ/tests/cli-integ-tests/cli.integtest.ts
  packages/aws-cdk-lib/core/README.md
  packages/aws-cdk-lib/core/lib/stack.ts
  packages/aws-cdk-lib/core/test/stack.test.ts
  packages/aws-cdk-lib/cx-api/lib/artifacts/cloudformation-artifact.ts
  packages/aws-cdk/lib/cdk-toolkit.ts
  packages/aws-cdk/lib/config.ts
  packages/aws-cdk/lib/parse-command-line-arguments.ts
  packages/aws-cdk/test/cdk-toolkit.test.ts
Labels: bug, p0, effort/medium, contribution/core, pr-linter/exempt-integ-test, pr-linter/cli-integ-tested

#32175 feat: update L1 CloudFormation resource definitions
  packages/@aws-cdk/cloudformation-diff/package.json
  packages/@aws-cdk/integ-runner/package.json
  packages/aws-cdk-lib/aws-connectcampaignsv2/.jsiirc.json
  packages/aws-cdk-lib/aws-connectcampaignsv2/README.md
  packages/aws-cdk-lib/aws-connectcampaignsv2/index.ts
  packages/aws-cdk-lib/aws-connectcampaignsv2/lib/index.ts
  packages/aws-cdk-lib/index.ts
  packages/aws-cdk-lib/package.json
  packages/aws-cdk-lib/scripts/scope-map.json
  tools/@aws-cdk/spec2cdk/package.json
  yarn.lock
Labels: p2, dependencies, contribution/core, pr-linter/exempt-readme, pr-linter/exempt-test, auto-approve, pr-linter/exempt-integ-test

#32102 feat(ses): maximum delivery time for emails
  packages/@aws-cdk-testing/framework-integ/test/aws-ses/test/integ.configuration-set.js.snapshot/ConfigurationSetIntegDefaultTestDeployAssert9B6AD46A.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ses/test/integ.configuration-set.js.snapshot/cdk-ses-configuration-set-integ.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ses/test/integ.configuration-set.js.snapshot/cdk-ses-configuration-set-integ.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ses/test/integ.configuration-set.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-ses/test/integ.configuration-set.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ses/test/integ.configuration-set.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ses/test/integ.configuration-set.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ses/test/integ.configuration-set.ts
  packages/aws-cdk-lib/aws-ses/README.md
  packages/aws-cdk-lib/aws-ses/lib/configuration-set.ts
  packages/aws-cdk-lib/aws-ses/test/configuration-set.test.ts
Labels: p2, distinguished-contributor

#31339 feat(cloudfront): `function URL` origin access control L2 construct
  packages/@aws-cdk-testing/framework-integ/test/aws-cloudfront-origins/test/integ.function-url-origin-oac-alias.js.snapshot/asset.da514df694ce3f41453746a766ae6aff13c869c38002598930d6d34e5711985b.bundle/index.js
  packages/@aws-cdk-testing/framework-integ/test/aws-cloudfront-origins/test/integ.function-url-origin-oac-alias.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-cloudfront-origins/test/integ.function-url-origin-oac-alias.js.snapshot/integ-cloudfront-function-url-origin-oac.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-cloudfront-origins/test/integ.function-url-origin-oac-alias.js.snapshot/integ-cloudfront-function-url-origin-oac.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-cloudfront-origins/test/integ.function-url-origin-oac-alias.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-cloudfront-origins/test/integ.function-url-origin-oac-alias.js.snapshot/lambdaaliasurloriginoacDefaultTestDeployAssert249534BF.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-cloudfront-origins/test/integ.function-url-origin-oac-alias.js.snapshot/lambdaaliasurloriginoacDefaultTestDeployAssert249534BF.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-cloudfront-origins/test/integ.function-url-origin-oac-alias.js.snapshot/lambdaaliasurltestDefaultTestDeployAssertF3A70BC0.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-cloudfront-origins/test/integ.function-url-origin-oac-alias.js.snapshot/lambdaaliasurltestDefaultTestDeployAssertF3A70BC0.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-cloudfront-origins/test/integ.function-url-origin-oac-alias.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-cloudfront-origins/test/integ.function-url-origin-oac-alias.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-cloudfront-origins/test/integ.function-url-origin-oac-alias.ts
  packages/@aws-cdk-testing/framework-integ/test/aws-cloudfront-origins/test/integ.function-url-origin-oac-custom.js.snapshot/asset.da514df694ce3f41453746a766ae6aff13c869c38002598930d6d34e5711985b.bundle/index.js
  packages/@aws-cdk-testing/framework-integ/test/aws-cloudfront-origins/test/integ.function-url-origin-oac-custom.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-cloudfront-origins/test/integ.function-url-origin-oac-custom.js.snapshot/integ-cloudfront-function-url-origin-custom-oac.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-cloudfront-origins/test/integ.function-url-origin-oac-custom.js.snapshot/integ-cloudfront-function-url-origin-custom-oac.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-cloudfront-origins/test/integ.function-url-origin-oac-custom.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-cloudfront-origins/test/integ.function-url-origin-oac-custom.js.snapshot/lambdaurlcustomoactestDefaultTestDeployAssert38EFB78E.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-cloudfront-origins/test/integ.function-url-origin-oac-custom.js.snapshot/lambdaurlcustomoactestDefaultTestDeployAssert38EFB78E.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-cloudfront-origins/test/integ.function-url-origin-oac-custom.js.snapshot/lambdaurlorigincustomoacDefaultTestDeployAssertD8D04E3C.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-cloudfront-origins/test/integ.function-url-origin-oac-custom.js.snapshot/lambdaurlorigincustomoacDefaultTestDeployAssertD8D04E3C.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-cloudfront-origins/test/integ.function-url-origin-oac-custom.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-cloudfront-origins/test/integ.function-url-origin-oac-custom.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-cloudfront-origins/test/integ.function-url-origin-oac-custom.ts
  packages/@aws-cdk-testing/framework-integ/test/aws-cloudfront-origins/test/integ.function-url-origin-oac.js.snapshot/asset.da514df694ce3f41453746a766ae6aff13c869c38002598930d6d34e5711985b.bundle/index.js
  packages/@aws-cdk-testing/framework-integ/test/aws-cloudfront-origins/test/integ.function-url-origin-oac.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-cloudfront-origins/test/integ.function-url-origin-oac.js.snapshot/integ-cloudfront-function-url-origin-oac.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-cloudfront-origins/test/integ.function-url-origin-oac.js.snapshot/integ-cloudfront-function-url-origin-oac.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-cloudfront-origins/test/integ.function-url-origin-oac.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-cloudfront-origins/test/integ.function-url-origin-oac.js.snapshot/lambdaurloriginoacDefaultTestDeployAssert0BF569B3.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-cloudfront-origins/test/integ.function-url-origin-oac.js.snapshot/lambdaurloriginoacDefaultTestDeployAssert0BF569B3.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-cloudfront-origins/test/integ.function-url-origin-oac.js.snapshot/lambdaurltestDefaultTestDeployAssertC8C2310A.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-cloudfront-origins/test/integ.function-url-origin-oac.js.snapshot/lambdaurltestDefaultTestDeployAssertC8C2310A.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-cloudfront-origins/test/integ.function-url-origin-oac.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-cloudfront-origins/test/integ.function-url-origin-oac.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-cloudfront-origins/test/integ.function-url-origin-oac.ts
  packages/aws-cdk-lib/aws-cloudfront-origins/README.md
  packages/aws-cdk-lib/aws-cloudfront-origins/lib/function-url-origin.ts
  packages/aws-cdk-lib/aws-cloudfront-origins/test/function-url-origin.test.ts
  packages/aws-cdk-lib/aws-cloudfront/lib/origin-access-control.ts
  packages/aws-cdk-lib/aws-cloudfront/test/origin-access-control.test.ts
  packages/aws-cdk-lib/aws-lambda/lib/function-url.ts
Labels: p2, distinguished-contributor

#32177 chore(release): 2.167.2
  CHANGELOG.v2.alpha.md
  CHANGELOG.v2.md
  allowed-breaking-changes.txt
  packages/@aws-cdk-testing/cli-integ/resources/cdk-apps/app/app.js
  packages/@aws-cdk-testing/cli-integ/tests/cli-integ-tests/cli.integtest.ts
  packages/aws-cdk-lib/core/README.md
  packages/aws-cdk-lib/core/lib/stack.ts
  packages/aws-cdk-lib/core/test/stack.test.ts
  packages/aws-cdk-lib/cx-api/lib/artifacts/cloudformation-artifact.ts
  packages/aws-cdk/lib/api/util/cloudformation.ts
  packages/aws-cdk/lib/cdk-toolkit.ts
  packages/aws-cdk/lib/config.ts
  packages/aws-cdk/lib/context-providers/load-balancers.ts
  packages/aws-cdk/lib/parse-command-line-arguments.ts
  packages/aws-cdk/test/cdk-toolkit.test.ts
  packages/aws-cdk/test/context-providers/load-balancers.test.ts
  version.v2.json
Labels: p2, contribution/core, pr/no-squash, pr-linter/cli-integ-tested

#32190 chore(merge-back): 2.167.2
  CHANGELOG.v2.alpha.md
  CHANGELOG.v2.md
  version.v2.json
Labels: p2, pr/no-squash, auto-approve

#32185 chore(cli): update tests for future monorepo
  packages/aws-cdk/test/api/assembly-versions.ts
  packages/aws-cdk/test/api/cloud-assembly.test.ts
  packages/aws-cdk/test/api/cloud-executable.test.ts
  packages/aws-cdk/test/api/exec.test.ts
  packages/aws-cdk/test/build.test.ts
  packages/aws-cdk/test/cdk-toolkit.test.ts
  packages/aws-cdk/test/util.ts
Labels: p2, contribution/core

#32062 refactor(apprunner): consolidate name validations for App Runner Resources and improve error messages
  packages/@aws-cdk/aws-apprunner-alpha/lib/auto-scaling-configuration.ts
  packages/@aws-cdk/aws-apprunner-alpha/lib/observability-configuration.ts
  packages/@aws-cdk/aws-apprunner-alpha/lib/service.ts
  packages/@aws-cdk/aws-apprunner-alpha/lib/vpc-connector.ts
  packages/@aws-cdk/aws-apprunner-alpha/lib/vpc-ingress-connection.ts
  packages/@aws-cdk/aws-apprunner-alpha/test/auto-scaling-configuration.test.ts
  packages/@aws-cdk/aws-apprunner-alpha/test/obserbability-configuration.test.ts
  packages/@aws-cdk/aws-apprunner-alpha/test/service.test.ts
  packages/@aws-cdk/aws-apprunner-alpha/test/vpc-connector.test.ts
  packages/@aws-cdk/aws-apprunner-alpha/test/vpc-ingress-connection.test.ts
Labels: p2, distinguished-contributor

#31709 feat(lambda-destinations): support Lambda async S3 destination
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-destinations/test/integ.destinations.js.snapshot/DestinationsDefaultTestDeployAssertCC49E667.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-destinations/test/integ.destinations.js.snapshot/DestinationsDefaultTestDeployAssertCC49E667.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-destinations/test/integ.destinations.js.snapshot/asset.da514df694ce3f41453746a766ae6aff13c869c38002598930d6d34e5711985b.bundle/index.js
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-destinations/test/integ.destinations.js.snapshot/aws-cdk-lambda-destinations.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-destinations/test/integ.destinations.js.snapshot/aws-cdk-lambda-destinations.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-destinations/test/integ.destinations.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-destinations/test/integ.destinations.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-destinations/test/integ.destinations.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-destinations/test/integ.destinations.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-destinations/test/integ.destinations.ts
  packages/aws-cdk-lib/aws-lambda-destinations/README.md
  packages/aws-cdk-lib/aws-lambda-destinations/lib/index.ts
  packages/aws-cdk-lib/aws-lambda-destinations/lib/s3.ts
  packages/aws-cdk-lib/aws-lambda-destinations/test/destinations.test.ts
Labels: p2, pr/needs-community-review, beginning-contributor

#32104 feat(lambda): add NodeJS 22.x support
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda/test/integ.runtime.inlinecode.js.snapshot/aws-cdk-lambda-runtime-inlinecode.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda/test/integ.runtime.inlinecode.js.snapshot/aws-cdk-lambda-runtime-inlinecode.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda/test/integ.runtime.inlinecode.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda/test/integ.runtime.inlinecode.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda/test/integ.runtime.inlinecode.ts
  packages/aws-cdk-lib/aws-lambda/lib/runtime.ts
Labels: p2, pr-linter/exempt-readme, repeat-contributor

#32204 feat(lambda): support observability for ESM ( DDB, Kinesis, SQS)
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-event-sources/test/integ.dynamodb-with-metrics-config.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-event-sources/test/integ.dynamodb-with-metrics-config.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-event-sources/test/integ.dynamodb-with-metrics-config.js.snapshot/lambda-event-source-metrics-config-dynamodb.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-event-sources/test/integ.dynamodb-with-metrics-config.js.snapshot/lambda-event-source-metrics-config-dynamodb.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-event-sources/test/integ.dynamodb-with-metrics-config.js.snapshot/lambdaeventsourcedynamodbwithmetricsDefaultTestDeployAssertC1C197C4.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-event-sources/test/integ.dynamodb-with-metrics-config.js.snapshot/lambdaeventsourcedynamodbwithmetricsDefaultTestDeployAssertC1C197C4.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-event-sources/test/integ.dynamodb-with-metrics-config.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-event-sources/test/integ.dynamodb-with-metrics-config.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-event-sources/test/integ.dynamodb-with-metrics-config.ts
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-event-sources/test/integ.kinesis-with-metrics-config.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-event-sources/test/integ.kinesis-with-metrics-config.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-event-sources/test/integ.kinesis-with-metrics-config.js.snapshot/lambda-event-source-metrics-config-kinesis.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-event-sources/test/integ.kinesis-with-metrics-config.js.snapshot/lambda-event-source-metrics-config-kinesis.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-event-sources/test/integ.kinesis-with-metrics-config.js.snapshot/lambdaeventsourcekinesiswithmetricsDefaultTestDeployAssert312685CA.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-event-sources/test/integ.kinesis-with-metrics-config.js.snapshot/lambdaeventsourcekinesiswithmetricsDefaultTestDeployAssert312685CA.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-event-sources/test/integ.kinesis-with-metrics-config.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-event-sources/test/integ.kinesis-with-metrics-config.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-event-sources/test/integ.kinesis-with-metrics-config.ts
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-event-sources/test/integ.sqs-with-metrics-config.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-event-sources/test/integ.sqs-with-metrics-config.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-event-sources/test/integ.sqs-with-metrics-config.js.snapshot/lambda-event-source-metrics-config-sqs.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-event-sources/test/integ.sqs-with-metrics-config.js.snapshot/lambda-event-source-metrics-config-sqs.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-event-sources/test/integ.sqs-with-metrics-config.js.snapshot/lambdaeventsourcesqswithmetricsDefaultTestDeployAssert9B567B16.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-event-sources/test/integ.sqs-with-metrics-config.js.snapshot/lambdaeventsourcesqswithmetricsDefaultTestDeployAssert9B567B16.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-event-sources/test/integ.sqs-with-metrics-config.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-event-sources/test/integ.sqs-with-metrics-config.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-event-sources/test/integ.sqs-with-metrics-config.ts
  packages/aws-cdk-lib/aws-lambda-event-sources/lib/dynamodb.ts
  packages/aws-cdk-lib/aws-lambda-event-sources/lib/kinesis.ts
  packages/aws-cdk-lib/aws-lambda-event-sources/lib/sqs.ts
  packages/aws-cdk-lib/aws-lambda-event-sources/lib/stream.ts
  packages/aws-cdk-lib/aws-lambda-event-sources/test/dynamo.test.ts
  packages/aws-cdk-lib/aws-lambda-event-sources/test/kinesis.test.ts
  packages/aws-cdk-lib/aws-lambda-event-sources/test/sqs.test.ts
  packages/aws-cdk-lib/aws-lambda/README.md
  packages/aws-cdk-lib/aws-lambda/lib/event-source-mapping.ts
  packages/aws-cdk-lib/aws-lambda/test/event-source-mapping.test.ts
  packages/aws-cdk-lib/awslint.json
  tools/@aws-cdk/spec2cdk/temporary-schemas/us-east-1/aws-lambda-event-source-metrics-config.json
Labels: p2, repeat-contributor

#32196 fix(cli): excessive stack event polling during deployment
  packages/aws-cdk/lib/api/aws-auth/sdk.ts
  packages/aws-cdk/lib/api/util/cloudformation/stack-event-poller.ts
  packages/aws-cdk/test/api/util/cloudformation/stack-event-poller.test.ts
Labels: bug, p0, effort/medium, contribution/core, pr-linter/exempt-integ-test, pr-linter/cli-integ-tested

#32215 chore(merge-back): 2.168.0
  CHANGELOG.v2.alpha.md
  CHANGELOG.v2.md
  version.v2.json
Labels: p2, pr/needs-community-review, pr/no-squash, auto-approve

#32216 fix(cli): cannot assume a doubly-chained role
  packages/aws-cdk/THIRD_PARTY_LICENSES
  packages/aws-cdk/package.json
  yarn.lock
Labels: bug, p0, contribution/core, pr-linter/exempt-test, pr-linter/exempt-integ-test

#32207 feat(scheduler): `scheduler` and `scheduler-targets` modules are now in Developer Preview
  packages/@aws-cdk/aws-scheduler-alpha/README.md
  packages/@aws-cdk/aws-scheduler-alpha/package.json
  packages/@aws-cdk/aws-scheduler-targets-alpha/README.md
  packages/@aws-cdk/aws-scheduler-targets-alpha/package.json
Labels: p2, contribution/core, pr-linter/exempt-test, pr-linter/exempt-integ-test

#32213 fix(cli): proxy is not configured correctly
  packages/aws-cdk/THIRD_PARTY_LICENSES
  packages/aws-cdk/lib/api/aws-auth/awscli-compatible.ts
  packages/aws-cdk/lib/api/aws-auth/sdk.ts
Labels: bug, p1, effort/medium, contribution/core, pr-linter/exempt-test, pr-linter/exempt-integ-test, pr-linter/cli-integ-tested

#32180 chore(rds): add support for 8.0.mysql_aurora.3.08.0
  packages/aws-cdk-lib/aws-rds/lib/cluster-engine.ts
  packages/aws-cdk-lib/aws-rds/test/cluster-engine.test.ts
Labels: p2, beginning-contributor

#32119 chore(glue): timeout and worker type validation for Ray jobs
  packages/@aws-cdk/aws-glue-alpha/lib/job.ts
  packages/@aws-cdk/aws-glue-alpha/test/job.test.ts
Labels: bug, p2, effort/medium, distinguished-contributor

#30830 feat(sns): add delivery policy to sns subscriptions
  packages/@aws-cdk-testing/framework-integ/test/aws-sns-subscriptions/test/integ.sns-url.js.snapshot/SnsToUrlStack.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-sns-subscriptions/test/integ.sns-url.js.snapshot/SnsToUrlStack.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-sns-subscriptions/test/integ.sns-url.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-sns-subscriptions/test/integ.sns-url.js.snapshot/cdkintegDefaultTestDeployAssert83AD650C.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-sns-subscriptions/test/integ.sns-url.js.snapshot/cdkintegDefaultTestDeployAssert83AD650C.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-sns-subscriptions/test/integ.sns-url.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-sns-subscriptions/test/integ.sns-url.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-sns-subscriptions/test/integ.sns-url.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-sns-subscriptions/test/integ.sns-url.ts
  packages/aws-cdk-lib/aws-sns-subscriptions/README.md
  packages/aws-cdk-lib/aws-sns-subscriptions/lib/url.ts
  packages/aws-cdk-lib/aws-sns/lib/delivery-policy.ts
  packages/aws-cdk-lib/aws-sns/lib/index.ts
  packages/aws-cdk-lib/aws-sns/lib/subscription.ts
  packages/aws-cdk-lib/aws-sns/test/subscription.test.ts
Labels: p2, feature-request, effort/small, beginning-contributor

#32046 fix(location): underscores are not allowed in the name
  packages/@aws-cdk/aws-location-alpha/lib/geofence-collection.ts
  packages/@aws-cdk/aws-location-alpha/lib/place-index.ts
  packages/@aws-cdk/aws-location-alpha/lib/route-calculator.ts
  packages/@aws-cdk/aws-location-alpha/lib/tracker.ts
  packages/@aws-cdk/aws-location-alpha/test/geofence-collection.test.ts
  packages/@aws-cdk/aws-location-alpha/test/integ.geofence-collection.js.snapshot/GeofenceCollectionTestDefaultTestDeployAssert44609017.assets.json
  packages/@aws-cdk/aws-location-alpha/test/integ.geofence-collection.js.snapshot/cdk-integ-location-geofence-collection.assets.json
  packages/@aws-cdk/aws-location-alpha/test/integ.geofence-collection.js.snapshot/cdk-integ-location-geofence-collection.template.json
  packages/@aws-cdk/aws-location-alpha/test/integ.geofence-collection.js.snapshot/cdk.out
  packages/@aws-cdk/aws-location-alpha/test/integ.geofence-collection.js.snapshot/integ.json
  packages/@aws-cdk/aws-location-alpha/test/integ.geofence-collection.js.snapshot/manifest.json
  packages/@aws-cdk/aws-location-alpha/test/integ.geofence-collection.js.snapshot/tree.json
  packages/@aws-cdk/aws-location-alpha/test/integ.geofence-collection.ts
  packages/@aws-cdk/aws-location-alpha/test/integ.place-index.js.snapshot/PlaceIndexTestDefaultTestDeployAssert3F96C508.assets.json
  packages/@aws-cdk/aws-location-alpha/test/integ.place-index.js.snapshot/cdk-integ-location-place-index.assets.json
  packages/@aws-cdk/aws-location-alpha/test/integ.place-index.js.snapshot/cdk-integ-location-place-index.template.json
  packages/@aws-cdk/aws-location-alpha/test/integ.place-index.js.snapshot/cdk.out
  packages/@aws-cdk/aws-location-alpha/test/integ.place-index.js.snapshot/integ.json
  packages/@aws-cdk/aws-location-alpha/test/integ.place-index.js.snapshot/manifest.json
  packages/@aws-cdk/aws-location-alpha/test/integ.place-index.js.snapshot/tree.json
  packages/@aws-cdk/aws-location-alpha/test/integ.place-index.ts
  packages/@aws-cdk/aws-location-alpha/test/integ.route-calculator.js.snapshot/RouteCalculatorTestDefaultTestDeployAssert5893D6F4.assets.json
  packages/@aws-cdk/aws-location-alpha/test/integ.route-calculator.js.snapshot/cdk-integ-location-route-calculator.assets.json
  packages/@aws-cdk/aws-location-alpha/test/integ.route-calculator.js.snapshot/cdk-integ-location-route-calculator.template.json
  packages/@aws-cdk/aws-location-alpha/test/integ.route-calculator.js.snapshot/cdk.out
  packages/@aws-cdk/aws-location-alpha/test/integ.route-calculator.js.snapshot/integ.json
  packages/@aws-cdk/aws-location-alpha/test/integ.route-calculator.js.snapshot/manifest.json
  packages/@aws-cdk/aws-location-alpha/test/integ.route-calculator.js.snapshot/tree.json
  packages/@aws-cdk/aws-location-alpha/test/integ.route-calculator.ts
  packages/@aws-cdk/aws-location-alpha/test/integ.tracker.js.snapshot/TrackerTestDefaultTestDeployAssert0E17BB8B.assets.json
  packages/@aws-cdk/aws-location-alpha/test/integ.tracker.js.snapshot/TrackerTestDefaultTestDeployAssert0E17BB8B.template.json
  packages/@aws-cdk/aws-location-alpha/test/integ.tracker.js.snapshot/asset.b98abee59e034ed29eeb601684dc34752baa86509a7d457d72305d4e19ecc80b.bundle/index.js
  packages/@aws-cdk/aws-location-alpha/test/integ.tracker.js.snapshot/cdk-integ-location-tracker.assets.json
  packages/@aws-cdk/aws-location-alpha/test/integ.tracker.js.snapshot/cdk-integ-location-tracker.template.json
  packages/@aws-cdk/aws-location-alpha/test/integ.tracker.js.snapshot/cdk.out
  packages/@aws-cdk/aws-location-alpha/test/integ.tracker.js.snapshot/integ.json
  packages/@aws-cdk/aws-location-alpha/test/integ.tracker.js.snapshot/manifest.json
  packages/@aws-cdk/aws-location-alpha/test/integ.tracker.js.snapshot/tree.json
  packages/@aws-cdk/aws-location-alpha/test/integ.tracker.ts
  packages/@aws-cdk/aws-location-alpha/test/place-index.test.ts
  packages/@aws-cdk/aws-location-alpha/test/route-calculator.test.ts
  packages/@aws-cdk/aws-location-alpha/test/tracker.test.ts
Labels: p2, distinguished-contributor

#32064 fix(s3): key rotation is not enabled while creating KMS encrypted S3 buckets
  packages/@aws-cdk-testing/framework-integ/test/aws-s3/test/integ.bucket-encryption.js.snapshot/IntegTestDSSEBucketDefaultTestDeployAssert56801A2F.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-s3/test/integ.bucket-encryption.js.snapshot/aws-cdk-s3-bucket-encryption.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-s3/test/integ.bucket-encryption.js.snapshot/aws-cdk-s3-bucket-encryption.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-s3/test/integ.bucket-encryption.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-s3/test/integ.bucket-encryption.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-s3/test/integ.bucket-encryption.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-s3/test/integ.bucket-encryption.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-s3/test/integ.bucket-encryption.ts
  packages/@aws-cdk-testing/framework-integ/test/aws-s3/test/integ.bucket-server-access-logs-sse-kms.js.snapshot/ServerAccessLogsSseKmsTestDefaultTestDeployAssertB937C102.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-s3/test/integ.bucket-server-access-logs-sse-kms.js.snapshot/aws-cdk-s3-server-access-logs-sse-kms.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-s3/test/integ.bucket-server-access-logs-sse-kms.js.snapshot/aws-cdk-s3-server-access-logs-sse-kms.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-s3/test/integ.bucket-server-access-logs-sse-kms.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-s3/test/integ.bucket-server-access-logs-sse-kms.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-s3/test/integ.bucket-server-access-logs-sse-kms.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-s3/test/integ.bucket-server-access-logs-sse-kms.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-s3/test/integ.bucket-server-access-logs-sse-kms.ts
  packages/@aws-cdk-testing/framework-integ/test/aws-s3/test/integ.bucket.js.snapshot/aws-cdk-s3.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-s3/test/integ.bucket.js.snapshot/aws-cdk-s3.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-s3/test/integ.bucket.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-s3/test/integ.bucket.js.snapshot/cdkintegs3bucketDefaultTestDeployAssertB89636B8.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-s3/test/integ.bucket.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-s3/test/integ.bucket.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-s3/test/integ.bucket.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-s3/test/integ.bucket.ts
  packages/aws-cdk-lib/aws-s3/lib/bucket.ts
  packages/aws-cdk-lib/aws-s3/test/bucket.test.ts
Labels: bug, p1, effort/small, repeat-contributor

#30648 feat(location): support Map
  packages/@aws-cdk/aws-location-alpha/README.md
  packages/@aws-cdk/aws-location-alpha/lib/index.ts
  packages/@aws-cdk/aws-location-alpha/lib/map.ts
  packages/@aws-cdk/aws-location-alpha/test/integ.map.js.snapshot/MapTestDefaultTestDeployAssert46CB2F9C.assets.json
  packages/@aws-cdk/aws-location-alpha/test/integ.map.js.snapshot/MapTestDefaultTestDeployAssert46CB2F9C.template.json
  packages/@aws-cdk/aws-location-alpha/test/integ.map.js.snapshot/cdk-integ-location-map.assets.json
  packages/@aws-cdk/aws-location-alpha/test/integ.map.js.snapshot/cdk-integ-location-map.template.json
  packages/@aws-cdk/aws-location-alpha/test/integ.map.js.snapshot/cdk.out
  packages/@aws-cdk/aws-location-alpha/test/integ.map.js.snapshot/integ.json
  packages/@aws-cdk/aws-location-alpha/test/integ.map.js.snapshot/manifest.json
  packages/@aws-cdk/aws-location-alpha/test/integ.map.js.snapshot/tree.json
  packages/@aws-cdk/aws-location-alpha/test/integ.map.ts
  packages/@aws-cdk/aws-location-alpha/test/map.test.ts
Labels: p2, feature-request, effort/small, star-contributor

#31167 docs(integ-tests): how to use `AwsApiCall.waiterProvider.addToRolePolicy()`
  packages/@aws-cdk/integ-tests-alpha/README.md
Labels: p2, distinguished-contributor

#32223 feat: update L1 CloudFormation resource definitions
  packages/@aws-cdk/cloudformation-diff/package.json
  packages/@aws-cdk/integ-runner/package.json
  packages/aws-cdk-lib/aws-rbin/.jsiirc.json
  packages/aws-cdk-lib/aws-rbin/README.md
  packages/aws-cdk-lib/aws-rbin/index.ts
  packages/aws-cdk-lib/aws-rbin/lib/index.ts
  packages/aws-cdk-lib/index.ts
  packages/aws-cdk-lib/package.json
  packages/aws-cdk-lib/scripts/scope-map.json
  tools/@aws-cdk/spec2cdk/package.json
  yarn.lock
Labels: p2, dependencies, contribution/core, pr-linter/exempt-readme, pr-linter/exempt-test, auto-approve, pr-linter/exempt-integ-test, pr/needs-maintainer-review

#30567 feat(cloudfront): add `attachWebAclId` method for Distribution
  packages/@aws-cdk-testing/framework-integ/test/aws-cloudfront/test/integ.cloudfront-with-webacl.js.snapshot/aws-cdk-cloudfront-with-webacl.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-cloudfront/test/integ.cloudfront-with-webacl.js.snapshot/aws-cdk-cloudfront-with-webacl.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-cloudfront/test/integ.cloudfront-with-webacl.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-cloudfront/test/integ.cloudfront-with-webacl.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-cloudfront/test/integ.cloudfront-with-webacl.js.snapshot/integcloudfrontwithwebaclDefaultTestDeployAssert166CAFCF.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-cloudfront/test/integ.cloudfront-with-webacl.js.snapshot/integcloudfrontwithwebaclDefaultTestDeployAssert166CAFCF.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-cloudfront/test/integ.cloudfront-with-webacl.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-cloudfront/test/integ.cloudfront-with-webacl.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-cloudfront/test/integ.cloudfront-with-webacl.ts
  packages/aws-cdk-lib/aws-cloudfront/README.md
  packages/aws-cdk-lib/aws-cloudfront/lib/distribution.ts
  packages/aws-cdk-lib/aws-cloudfront/test/distribution.test.ts
  packages/aws-cdk-lib/rosetta/aws_cloudfront/default.ts-fixture
Labels: p2, distinguished-contributor

#32229 chore(merge-back): 2.169.0
  CHANGELOG.v2.alpha.md
  CHANGELOG.v2.md
  version.v2.json
Labels: p2, pr/needs-community-review, pr/no-squash, auto-approve

#32227 fix(cli): sts retry options are ignored
  packages/aws-cdk/lib/api/aws-auth/sdk.ts
Labels: p2, contribution/core, pr-linter/exempt-test, pr-linter/exempt-integ-test, pr-linter/cli-integ-tested

#32194 chore: codeowners
  .github/CODEOWNERS
Labels: p2, pr/do-not-merge, contribution/core

#32205 feat(lambda): support for Provisioned Pollers
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-event-sources/test/integ.kafka-selfmanaged.js.snapshot/LambdaEventSourceKafkaSelfManagedTestDefaultTestDeployAssertAF78BD0F.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-event-sources/test/integ.kafka-selfmanaged.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-event-sources/test/integ.kafka-selfmanaged.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-event-sources/test/integ.kafka-selfmanaged.js.snapshot/lambda-event-source-kafka-self-managed.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-event-sources/test/integ.kafka-selfmanaged.js.snapshot/lambda-event-source-kafka-self-managed.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-event-sources/test/integ.kafka-selfmanaged.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-event-sources/test/integ.kafka-selfmanaged.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-event-sources/test/integ.kafka-selfmanaged.ts
  packages/aws-cdk-lib/aws-lambda-event-sources/README.md
  packages/aws-cdk-lib/aws-lambda-event-sources/lib/kafka.ts
  packages/aws-cdk-lib/aws-lambda-event-sources/lib/stream.ts
  packages/aws-cdk-lib/aws-lambda-event-sources/test/kafka.test.ts
  packages/aws-cdk-lib/aws-lambda/lib/event-source-mapping.ts
  packages/aws-cdk-lib/aws-lambda/test/event-source-mapping.test.ts
  packages/aws-cdk-lib/awslint.json
Labels: p2, repeat-contributor

#32157 feat(rds): enhanced monitoring configuration at the cluster level
  packages/@aws-cdk-testing/framework-integ/test/aws-rds/test/integ.cluster-enhanced-monitoring.js.snapshot/EnhancedMonitoringClusterIntegDefaultTestDeployAssertBBA17BDD.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-rds/test/integ.cluster-enhanced-monitoring.js.snapshot/EnhancedMonitoringClusterIntegDefaultTestDeployAssertBBA17BDD.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-rds/test/integ.cluster-enhanced-monitoring.js.snapshot/EnhancedMonitoringClusterStack.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-rds/test/integ.cluster-enhanced-monitoring.js.snapshot/EnhancedMonitoringClusterStack.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-rds/test/integ.cluster-enhanced-monitoring.js.snapshot/asset.a1acfc2b5f4f6b183fd2bb9863f486bc5edef6a357b355a070d9a0e502df418c/__entrypoint__.js
  packages/@aws-cdk-testing/framework-integ/test/aws-rds/test/integ.cluster-enhanced-monitoring.js.snapshot/asset.a1acfc2b5f4f6b183fd2bb9863f486bc5edef6a357b355a070d9a0e502df418c/index.js
  packages/@aws-cdk-testing/framework-integ/test/aws-rds/test/integ.cluster-enhanced-monitoring.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-rds/test/integ.cluster-enhanced-monitoring.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-rds/test/integ.cluster-enhanced-monitoring.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-rds/test/integ.cluster-enhanced-monitoring.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-rds/test/integ.cluster-enhanced-monitoring.ts
  packages/aws-cdk-lib/aws-rds/README.md
  packages/aws-cdk-lib/aws-rds/lib/cluster.ts
  packages/aws-cdk-lib/aws-rds/test/cluster.test.ts
Labels: p2, pr/needs-community-review, distinguished-contributor

#32249 chore(rds): add postgres engine 17.2, 16.6, 15.10, 14.15, 13.18, and 12.22
  packages/aws-cdk-lib/aws-rds/lib/cluster-engine.ts
  packages/aws-cdk-lib/aws-rds/lib/instance-engine.ts
Labels: p2, pr/needs-community-review, distinguished-contributor

#32246 chore(merge-back): 2.170.0
  CHANGELOG.v2.alpha.md
  CHANGELOG.v2.md
  version.v2.json
Labels: p2, pr/needs-community-review, pr/no-squash, auto-approve

#32231 feat(rds): support zero ACU for Aurora Serverless V2
  packages/@aws-cdk-testing/framework-integ/test/aws-rds/test/integ.cluster-serverless-v2-acu-0.js.snapshot/asset.a1acfc2b5f4f6b183fd2bb9863f486bc5edef6a357b355a070d9a0e502df418c/__entrypoint__.js
  packages/@aws-cdk-testing/framework-integ/test/aws-rds/test/integ.cluster-serverless-v2-acu-0.js.snapshot/asset.a1acfc2b5f4f6b183fd2bb9863f486bc5edef6a357b355a070d9a0e502df418c/index.js
  packages/@aws-cdk-testing/framework-integ/test/aws-rds/test/integ.cluster-serverless-v2-acu-0.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-rds/test/integ.cluster-serverless-v2-acu-0.js.snapshot/integ-aurora-serverlessv2-cluster-acu-0.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-rds/test/integ.cluster-serverless-v2-acu-0.js.snapshot/integ-aurora-serverlessv2-cluster-acu-0.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-rds/test/integ.cluster-serverless-v2-acu-0.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-rds/test/integ.cluster-serverless-v2-acu-0.js.snapshot/integtestacuDefaultTestDeployAssert17F73A1A.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-rds/test/integ.cluster-serverless-v2-acu-0.js.snapshot/integtestacuDefaultTestDeployAssert17F73A1A.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-rds/test/integ.cluster-serverless-v2-acu-0.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-rds/test/integ.cluster-serverless-v2-acu-0.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-rds/test/integ.cluster-serverless-v2-acu-0.ts
  packages/aws-cdk-lib/aws-rds/README.md
  packages/aws-cdk-lib/aws-rds/lib/cluster.ts
  packages/aws-cdk-lib/aws-rds/test/cluster.test.ts
Labels: p2, feature-request, distinguished-contributor, pr/needs-maintainer-review

#32254 chore(cli-integ): new test case for proxied requests
  packages/@aws-cdk-testing/cli-integ/package.json
  packages/@aws-cdk-testing/cli-integ/tests/cli-integ-tests/cli.integtest.ts
  packages/aws-cdk/lib/api/aws-auth/awscli-compatible.ts
  yarn.lock
Labels: p2, contribution/core, pr-linter/cli-integ-tested

#32261 fix(cli): sso with proxy fails
  packages/aws-cdk/THIRD_PARTY_LICENSES
  packages/aws-cdk/package.json
  yarn.lock
Labels: p2, contribution/core, pr-linter/exempt-test, pr-linter/exempt-integ-test

#32272 feat: update L1 CloudFormation resource definitions
  packages/@aws-cdk/cloudformation-diff/package.json
  packages/@aws-cdk/integ-runner/package.json
  packages/aws-cdk-lib/package.json
  tools/@aws-cdk/spec2cdk/package.json
  yarn.lock
Labels: p2, dependencies, contribution/core, pr-linter/exempt-readme, pr-linter/exempt-test, auto-approve, pr-linter/exempt-integ-test

#32270 chore(cli): prevent test interference
  packages/aws-cdk/jest.config.js
  packages/aws-cdk/lib/init.ts
  packages/aws-cdk/test/diff.test.ts
  packages/aws-cdk/test/init.test.ts
  packages/aws-cdk/test/jest-setup-after-env.ts
  packages/aws-cdk/test/notices.test.ts
Labels: p2, contribution/core, pr-linter/cli-integ-tested

#32275 chore(merge-back): 2.171.0
  CHANGELOG.v2.alpha.md
  CHANGELOG.v2.md
  version.v2.json
Labels: p2, pr/needs-community-review, pr/no-squash, auto-approve

#32277 chore(lambda): remove unnecessary lints
  packages/aws-cdk-lib/aws-lambda-event-sources/lib/stream.ts
  packages/aws-cdk-lib/aws-lambda/lib/event-source-mapping.ts
  packages/aws-cdk-lib/awslint.json
Labels: p2, contribution/core

#32257 chore(rds): support 8.4.3 engine version for Amazon RDS for MySQL
  packages/aws-cdk-lib/aws-rds/lib/instance-engine.ts
Labels: p2, distinguished-contributor

#32264 chore(ec2): add interface vpc endpoints
  packages/aws-cdk-lib/aws-ec2/lib/vpc-endpoint.ts
Labels: p2, distinguished-contributor

#31954 feat(pipes-targets): add API Gateway
  packages/@aws-cdk/aws-pipes-targets-alpha/README.md
  packages/@aws-cdk/aws-pipes-targets-alpha/lib/api-destination.ts
  packages/@aws-cdk/aws-pipes-targets-alpha/lib/api-gateway.ts
  packages/@aws-cdk/aws-pipes-targets-alpha/lib/index.ts
  packages/@aws-cdk/aws-pipes-targets-alpha/rosetta/default.ts-fixture
  packages/@aws-cdk/aws-pipes-targets-alpha/test/api-gateway.test.ts
  packages/@aws-cdk/aws-pipes-targets-alpha/test/integ.api-gateway.js.snapshot/asset.c9e084a249774d97a978bed2e1976874a70517128a904136b8737f0792322c1f/index.js
  packages/@aws-cdk/aws-pipes-targets-alpha/test/integ.api-gateway.js.snapshot/asset.da514df694ce3f41453746a766ae6aff13c869c38002598930d6d34e5711985b.bundle/index.js
  packages/@aws-cdk/aws-pipes-targets-alpha/test/integ.api-gateway.js.snapshot/aws-cdk-pipes-targets-api-gw.assets.json
  packages/@aws-cdk/aws-pipes-targets-alpha/test/integ.api-gateway.js.snapshot/aws-cdk-pipes-targets-api-gw.template.json
  packages/@aws-cdk/aws-pipes-targets-alpha/test/integ.api-gateway.js.snapshot/cdk.out
  packages/@aws-cdk/aws-pipes-targets-alpha/test/integ.api-gateway.js.snapshot/integ.json
  packages/@aws-cdk/aws-pipes-targets-alpha/test/integ.api-gateway.js.snapshot/integtestpipetargetapigwDefaultTestDeployAssertCBE10CAE.assets.json
  packages/@aws-cdk/aws-pipes-targets-alpha/test/integ.api-gateway.js.snapshot/integtestpipetargetapigwDefaultTestDeployAssertCBE10CAE.template.json
  packages/@aws-cdk/aws-pipes-targets-alpha/test/integ.api-gateway.js.snapshot/manifest.json
  packages/@aws-cdk/aws-pipes-targets-alpha/test/integ.api-gateway.js.snapshot/tree.json
  packages/@aws-cdk/aws-pipes-targets-alpha/test/integ.api-gateway.ts
Labels: p2, distinguished-contributor

#32284 fix(scheduler-targets-alpha): incorrect validation of maximumEventAge
  packages/@aws-cdk/aws-scheduler-targets-alpha/lib/target.ts
  packages/@aws-cdk/aws-scheduler-targets-alpha/test/codebuild-start-build.test.ts
  packages/@aws-cdk/aws-scheduler-targets-alpha/test/codepipeline-start-pipeline-execution.test.ts
  packages/@aws-cdk/aws-scheduler-targets-alpha/test/event-bridge-put-events.test.ts
  packages/@aws-cdk/aws-scheduler-targets-alpha/test/inspector-start-assessment-run.test.ts
  packages/@aws-cdk/aws-scheduler-targets-alpha/test/integ.lambda-invoke.js.snapshot/asset.14d52bdadae57c6ec2c7b715c5420ae5c3001a8252558f7219f6207e4f405a97.bundle/index.js
  packages/@aws-cdk/aws-scheduler-targets-alpha/test/integ.lambda-invoke.js.snapshot/aws-cdk-schedule-lambda.assets.json
  packages/@aws-cdk/aws-scheduler-targets-alpha/test/integ.lambda-invoke.js.snapshot/aws-cdk-schedule-lambda.template.json
  packages/@aws-cdk/aws-scheduler-targets-alpha/test/integ.lambda-invoke.js.snapshot/aws-cdk-schedule.assets.json
  packages/@aws-cdk/aws-scheduler-targets-alpha/test/integ.lambda-invoke.js.snapshot/aws-cdk-schedule.template.json
  packages/@aws-cdk/aws-scheduler-targets-alpha/test/integ.lambda-invoke.js.snapshot/integtestlambdainvokeDefaultTestDeployAssertEC6565E6.assets.json
  packages/@aws-cdk/aws-scheduler-targets-alpha/test/integ.lambda-invoke.js.snapshot/integtestlambdainvokeDefaultTestDeployAssertEC6565E6.template.json
  packages/@aws-cdk/aws-scheduler-targets-alpha/test/integ.lambda-invoke.js.snapshot/manifest.json
  packages/@aws-cdk/aws-scheduler-targets-alpha/test/integ.lambda-invoke.js.snapshot/tree.json
  packages/@aws-cdk/aws-scheduler-targets-alpha/test/integ.lambda-invoke.ts
  packages/@aws-cdk/aws-scheduler-targets-alpha/test/integ.schedule-lambda-target.handler/index.ts
  packages/@aws-cdk/aws-scheduler-targets-alpha/test/kinesis-data-firehose-put-record.test.ts
  packages/@aws-cdk/aws-scheduler-targets-alpha/test/kinesis-stream-put-record.test.ts
  packages/@aws-cdk/aws-scheduler-targets-alpha/test/lambda-invoke.test.ts
  packages/@aws-cdk/aws-scheduler-targets-alpha/test/sage-maker-start-pipeline-execution.test.ts
  packages/@aws-cdk/aws-scheduler-targets-alpha/test/sns-publish.test.ts
  packages/@aws-cdk/aws-scheduler-targets-alpha/test/sqs-send-message.test.ts
  packages/@aws-cdk/aws-scheduler-targets-alpha/test/stepfunction-start-execution.test.ts
Labels: p2, pr/needs-community-review, admired-contributor

#32189 feat(elasticloadbalancingv2): ip address type for both network and application target group
  packages/@aws-cdk-testing/framework-integ/test/aws-elasticloadbalancingv2/test/integ.alb-target-group-ip-address-type.js.snapshot/AlbTargetGroupIpAddressTypeTestIntegDefaultTestDeployAssert7B27CD73.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-elasticloadbalancingv2/test/integ.alb-target-group-ip-address-type.js.snapshot/AlbTargetGroupIpAddressTypeTestIntegDefaultTestDeployAssert7B27CD73.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-elasticloadbalancingv2/test/integ.alb-target-group-ip-address-type.js.snapshot/AlbTargetGroupIpAddressTypeTestStack.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-elasticloadbalancingv2/test/integ.alb-target-group-ip-address-type.js.snapshot/AlbTargetGroupIpAddressTypeTestStack.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-elasticloadbalancingv2/test/integ.alb-target-group-ip-address-type.js.snapshot/asset.a1acfc2b5f4f6b183fd2bb9863f486bc5edef6a357b355a070d9a0e502df418c/__entrypoint__.js
  packages/@aws-cdk-testing/framework-integ/test/aws-elasticloadbalancingv2/test/integ.alb-target-group-ip-address-type.js.snapshot/asset.a1acfc2b5f4f6b183fd2bb9863f486bc5edef6a357b355a070d9a0e502df418c/index.js
  packages/@aws-cdk-testing/framework-integ/test/aws-elasticloadbalancingv2/test/integ.alb-target-group-ip-address-type.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-elasticloadbalancingv2/test/integ.alb-target-group-ip-address-type.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-elasticloadbalancingv2/test/integ.alb-target-group-ip-address-type.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-elasticloadbalancingv2/test/integ.alb-target-group-ip-address-type.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-elasticloadbalancingv2/test/integ.alb-target-group-ip-address-type.ts
  packages/@aws-cdk-testing/framework-integ/test/aws-elasticloadbalancingv2/test/integ.nlb-target-group-ip-address-type.js.snapshot/NlbTargetGroupIpAddressTypeTestIntegDefaultTestDeployAssertF4BE6039.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-elasticloadbalancingv2/test/integ.nlb-target-group-ip-address-type.js.snapshot/NlbTargetGroupIpAddressTypeTestIntegDefaultTestDeployAssertF4BE6039.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-elasticloadbalancingv2/test/integ.nlb-target-group-ip-address-type.js.snapshot/NlbTargetGroupIpAddressTypeTestStack.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-elasticloadbalancingv2/test/integ.nlb-target-group-ip-address-type.js.snapshot/NlbTargetGroupIpAddressTypeTestStack.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-elasticloadbalancingv2/test/integ.nlb-target-group-ip-address-type.js.snapshot/asset.a1acfc2b5f4f6b183fd2bb9863f486bc5edef6a357b355a070d9a0e502df418c/__entrypoint__.js
  packages/@aws-cdk-testing/framework-integ/test/aws-elasticloadbalancingv2/test/integ.nlb-target-group-ip-address-type.js.snapshot/asset.a1acfc2b5f4f6b183fd2bb9863f486bc5edef6a357b355a070d9a0e502df418c/index.js
  packages/@aws-cdk-testing/framework-integ/test/aws-elasticloadbalancingv2/test/integ.nlb-target-group-ip-address-type.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-elasticloadbalancingv2/test/integ.nlb-target-group-ip-address-type.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-elasticloadbalancingv2/test/integ.nlb-target-group-ip-address-type.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-elasticloadbalancingv2/test/integ.nlb-target-group-ip-address-type.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-elasticloadbalancingv2/test/integ.nlb-target-group-ip-address-type.ts
  packages/aws-cdk-lib/aws-elasticloadbalancingv2/README.md
  packages/aws-cdk-lib/aws-elasticloadbalancingv2/lib/shared/base-target-group.ts
  packages/aws-cdk-lib/aws-elasticloadbalancingv2/test/alb/target-group.test.ts
  packages/aws-cdk-lib/aws-elasticloadbalancingv2/test/nlb/target-group.test.ts
Labels: p2, distinguished-contributor

#32297 fix(apigateway): remove deprecated apigatewayv2 from aws-apigateway module
  packages/aws-cdk-lib/aws-apigateway/README.md
  packages/aws-cdk-lib/aws-apigateway/lib/apigatewayv2.ts
  packages/aws-cdk-lib/aws-apigateway/lib/index.ts
Labels: bug, p1, contribution/core, pr-linter/exempt-test, pr-linter/exempt-breaking-change, pr-linter/exempt-integ-test

#31402 feat(cognito): new `cloudFrontEndpoint` method for user pool domain without custom resource
  packages/@aws-cdk-testing/framework-integ/test/aws-cognito/test/integ.user-pool-domain-cfdist.js.snapshot/asset.746da84b10e215c552e68b6d2061024e4429f0386f43a35ef5e4d2940655692e/index.js
  packages/@aws-cdk-testing/framework-integ/test/aws-cognito/test/integ.user-pool-domain-cfdist.js.snapshot/asset.9e8936ba1db43e0919ba2fc8265d50686eeaca82830c471ff8b7b0672c5970ec/index.js
  packages/@aws-cdk-testing/framework-integ/test/aws-cognito/test/integ.user-pool-domain-cfdist.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-cognito/test/integ.user-pool-domain-cfdist.js.snapshot/integ-user-pool-domain-cfdist.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-cognito/test/integ.user-pool-domain-cfdist.js.snapshot/integ-user-pool-domain-cfdist.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-cognito/test/integ.user-pool-domain-cfdist.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-cognito/test/integ.user-pool-domain-cfdist.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-cognito/test/integ.user-pool-domain-cfdist.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-cognito/test/integ.user-pool-domain-cfdist.ts
  packages/aws-cdk-lib/aws-cognito/README.md
  packages/aws-cdk-lib/aws-cognito/lib/user-pool-domain.ts
  packages/aws-cdk-lib/aws-cognito/test/user-pool-domain.test.ts
  packages/aws-cdk-lib/rosetta/aws_cognito/default.ts-fixture
Labels: p2, feature-request, effort/small, distinguished-contributor

#32291 fix(cli): assume role calls are skipping the proxy
  packages/@aws-cdk-testing/cli-integ/tests/cli-integ-tests/cli.integtest.ts
  packages/aws-cdk/lib/api/aws-auth/sdk-provider.ts
Labels: p1, contribution/core, pr-linter/exempt-test, pr-linter/exempt-integ-test, pr-linter/cli-integ-tested

#32311 chore(release): 2.171.1
  CHANGELOG.v2.alpha.md
  CHANGELOG.v2.md
  packages/aws-cdk/lib/api/aws-auth/sdk.ts
  packages/aws-cdk/test/api/hotswap/hotswap-test-setup.ts
  packages/aws-cdk/test/api/hotswap/lambda-functions-docker-hotswap-deployments.test.ts
  packages/aws-cdk/test/api/hotswap/lambda-functions-hotswap-deployments.test.ts
  version.v2.json
Labels: p2, contribution/core, pr/no-squash, pr-linter/cli-integ-tested

#32081 chore: change logging to use a single base logging method
  packages/aws-cdk/lib/api/util/cloudformation/stack-activity-monitor.ts
  packages/aws-cdk/lib/cli.ts
  packages/aws-cdk/lib/logging.ts
  packages/aws-cdk/test/api/exec.test.ts
  packages/aws-cdk/test/cli.test.ts
  packages/aws-cdk/test/logging.test.ts
Labels: p2, feature-request, effort/medium, contribution/core, pr-linter/cli-integ-tested

#32314 chore: un-bump codecov/codecov-action from 5 to 4
  .github/workflows/codecov.yml
Labels: p2, contribution/core

#32020 fix(cloudfront): propagate `originAccessControlId` CloudFront Origin property to CloudFormation templates
  packages/aws-cdk-lib/aws-cloudfront/lib/origin.ts
  packages/aws-cdk-lib/aws-cloudfront/test/distribution.test.ts
  packages/aws-cdk-lib/aws-cloudfront/test/test-origin.ts
Labels: bug, p2, effort/small, pr/needs-community-review, pr-linter/exempt-integ-test, beginning-contributor

#32316 feat(eks-v2-alpha): use native L1 to create fargate profile
  packages/@aws-cdk/aws-eks-v2-alpha/lib/fargate-profile.ts
  packages/@aws-cdk/aws-eks-v2-alpha/test/fargate.test.ts
Labels: p2, contribution/core, pr-linter/exempt-readme, pr-linter/exempt-integ-test

#32315 chore: update vscode devcontainer config
  .devcontainer/Dockerfile
  .devcontainer/devcontainer.json
Labels: p2, contribution/core

#32313 fix(cli): mfa code is not requested when `$AWS_PROFILE` is used
  packages/aws-cdk/lib/api/aws-auth/awscli-compatible.ts
Labels: bug, p0, effort/small, contribution/core, pr-linter/exempt-test, pr-linter/exempt-integ-test, pr-linter/cli-integ-tested

#32319 chore(cli): stops tests from interfering with each other
  packages/aws-cdk/jest.config.js
  packages/aws-cdk/test/api/garbage-collection.test.ts
  packages/aws-cdk/test/api/sdk-provider.test.ts
  packages/aws-cdk/test/commands/migrate.test.ts
  packages/aws-cdk/test/context.test.ts
  packages/aws-cdk/test/diff.test.ts
  packages/aws-cdk/test/jest-setup-after-env.ts
  packages/aws-cdk/test/notices.test.ts
  packages/aws-cdk/test/util/mock-sdk.ts
  packages/aws-cdk/test/util/stack-monitor.test.ts
Labels: p2, contribution/core

#32317 fix(cli): remove source maps
  packages/aws-cdk/CONTRIBUTING.md
  packages/aws-cdk/bin/cdk
  packages/aws-cdk/lib/cli.ts
  packages/aws-cdk/lib/config.ts
  packages/aws-cdk/lib/parse-command-line-arguments.ts
  packages/aws-cdk/lib/version.ts
  packages/aws-cdk/package.json
  packages/aws-cdk/test/version.test.ts
  tools/@aws-cdk/node-bundle/src/api/bundle.ts
Labels: bug, p1, effort/medium, contribution/core, pr-linter/exempt-test, pr-linter/exempt-integ-test, pr-linter/cli-integ-tested

#32309 fix(cli): warns about missing `--no-rollback` flag that is present
  packages/aws-cdk/lib/api/aws-auth/sdk.ts
  packages/aws-cdk/lib/api/deploy-stack.ts
  packages/aws-cdk/lib/cdk-toolkit.ts
  packages/aws-cdk/test/api/deploy-stack.test.ts
  packages/aws-cdk/test/cdk-toolkit.test.ts
Labels: bug, p2, effort/small, contribution/core, pr-linter/exempt-integ-test, pr-linter/cli-integ-tested

#32308 chore(cli): log SDK calls when using `-vvv`
  packages/aws-cdk/lib/api/aws-auth/sdk-logger.ts
  packages/aws-cdk/lib/api/aws-auth/sdk-provider.ts
  packages/aws-cdk/lib/api/aws-auth/sdk.ts
  packages/aws-cdk/lib/cli.ts
  packages/aws-cdk/lib/util/directories.ts
  packages/aws-cdk/lib/util/npm.ts
  packages/aws-cdk/test/api/aws-auth/__snapshots__/sdk-logger.test.ts.snap
  packages/aws-cdk/test/api/aws-auth/sdk-logger.test.ts
Labels: bug, p2, contribution/core, pr-linter/cli-integ-tested

#32073 feat(ec2): instance support passing IAM instance profile
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.instance-iam-profile.js.snapshot/asset.a1acfc2b5f4f6b183fd2bb9863f486bc5edef6a357b355a070d9a0e502df418c/__entrypoint__.js
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.instance-iam-profile.js.snapshot/asset.a1acfc2b5f4f6b183fd2bb9863f486bc5edef6a357b355a070d9a0e502df418c/index.js
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.instance-iam-profile.js.snapshot/asset.b98abee59e034ed29eeb601684dc34752baa86509a7d457d72305d4e19ecc80b.bundle/index.js
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.instance-iam-profile.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.instance-iam-profile.js.snapshot/instance-iam-profile.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.instance-iam-profile.js.snapshot/instance-iam-profile.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.instance-iam-profile.js.snapshot/instanceiamprofiletestDefaultTestDeployAssert8BAB0841.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.instance-iam-profile.js.snapshot/instanceiamprofiletestDefaultTestDeployAssert8BAB0841.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.instance-iam-profile.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.instance-iam-profile.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.instance-iam-profile.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.instance-iam-profile.ts
  packages/aws-cdk-lib/aws-ec2/README.md
  packages/aws-cdk-lib/aws-ec2/lib/instance.ts
  packages/aws-cdk-lib/aws-ec2/test/instance.test.ts
Labels: p1, feature-request, effort/small, beginning-contributor

#32327 chore(merge-back): 2.171.1
  CHANGELOG.v2.alpha.md
  CHANGELOG.v2.md
  version.v2.json
Labels: p2, pr/needs-community-review, pr/no-squash, auto-approve

#32331 chore: enforce no-throw-literal
  tools/@aws-cdk/cdk-build-tools/config/eslintrc.js
  tools/@aws-cdk/spec2cdk/lib/util/patterned-name.ts
Labels: p2, contribution/core

#31976 feat(route53-targets): add `AppSync` route53 target
  packages/@aws-cdk-testing/framework-integ/test/aws-route53-targets/test/integ.appsync-target.js.snapshot/appsyncdomainnameDefaultTestDeployAssert6D41B82A.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-route53-targets/test/integ.appsync-target.js.snapshot/appsyncdomainnameDefaultTestDeployAssert6D41B82A.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-route53-targets/test/integ.appsync-target.js.snapshot/aws-cdk-appsync-alias-integ.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-route53-targets/test/integ.appsync-target.js.snapshot/aws-cdk-appsync-alias-integ.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-route53-targets/test/integ.appsync-target.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-route53-targets/test/integ.appsync-target.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-route53-targets/test/integ.appsync-target.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-route53-targets/test/integ.appsync-target.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-route53-targets/test/integ.appsync-target.ts
  packages/aws-cdk-lib/aws-route53-targets/README.md
  packages/aws-cdk-lib/aws-route53-targets/lib/appsync-target.ts
  packages/aws-cdk-lib/aws-route53-targets/lib/index.ts
  packages/aws-cdk-lib/aws-route53-targets/test/appsync-target.test.ts
Labels: p2, feature-request, effort/medium, beginning-contributor

#32158 chore(build): add dotnot 9 to prerequisite check
  scripts/check-build-prerequisites.sh
Labels: bug, p2, effort/small, distinguished-contributor, pr/needs-maintainer-review
