Repository aws/aws-cdk, pull requests merged in 2024-08, with the labels that each got.

#30990 chore(rds): add support for 8.0.mysql_aurora.3.07.1
  packages/aws-cdk-lib/aws-rds/lib/cluster-engine.ts
  packages/aws-cdk-lib/aws-rds/test/cluster-engine.test.ts
Labels: p2, pr/needs-community-review, beginning-contributor, pr-linter/exemption-requested

#31015 chore(merge-back): 2.151.0
  CHANGELOG.v2.alpha.md
  CHANGELOG.v2.md
  packages/aws-cdk-lib/cx-api/FEATURE_FLAGS.md
  version.v2.json
Labels: p2, pr/needs-community-review, pr/no-squash, auto-approve

#31003 chore(rds): add support for aurora-postgresql 16.3
  packages/aws-cdk-lib/aws-rds/lib/cluster-engine.ts
  packages/aws-cdk-lib/aws-rds/test/cluster-engine.test.ts
Labels: p2, beginning-contributor, pr-linter/exemption-requested

#31025 feat: update L1 CloudFormation resource definitions
  packages/@aws-cdk/cloudformation-diff/package.json
  packages/@aws-cdk/integ-runner/package.json
  packages/aws-cdk-lib/aws-launchwizard/.jsiirc.json
  packages/aws-cdk-lib/aws-launchwizard/README.md
  packages/aws-cdk-lib/aws-launchwizard/index.ts
  packages/aws-cdk-lib/aws-launchwizard/lib/index.ts
  packages/aws-cdk-lib/index.ts
  packages/aws-cdk-lib/package.json
  packages/aws-cdk-lib/scripts/scope-map.json
  tools/@aws-cdk/spec2cdk/package.json
  yarn.lock
Labels: p2, dependencies, contribution/core, pr-linter/exempt-readme, pr-linter/exempt-test, auto-approve, pr-linter/exempt-integ-test

#30784 feat(elasticloadbalancingv2): support Mutual Authentication with TLS for Application Load Balancer
  packages/@aws-cdk-testing/framework-integ/test/aws-elasticloadbalancingv2/test/integ.alb-mtls.js.snapshot/alb-mtls-test-stack.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-elasticloadbalancingv2/test/integ.alb-mtls.js.snapshot/alb-mtls-test-stack.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-elasticloadbalancingv2/test/integ.alb-mtls.js.snapshot/albmtlsintegDefaultTestDeployAssert30225695.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-elasticloadbalancingv2/test/integ.alb-mtls.js.snapshot/albmtlsintegDefaultTestDeployAssert30225695.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-elasticloadbalancingv2/test/integ.alb-mtls.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-elasticloadbalancingv2/test/integ.alb-mtls.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-elasticloadbalancingv2/test/integ.alb-mtls.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-elasticloadbalancingv2/test/integ.alb-mtls.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-elasticloadbalancingv2/test/integ.alb-mtls.ts
  packages/@aws-cdk-testing/framework-integ/test/aws-elasticloadbalancingv2/test/mtls/crl.pem
  packages/@aws-cdk-testing/framework-integ/test/aws-elasticloadbalancingv2/test/mtls/rootCA_cert.pem
  packages/aws-cdk-lib/aws-elasticloadbalancingv2/README.md
  packages/aws-cdk-lib/aws-elasticloadbalancingv2/lib/alb/application-listener.ts
  packages/aws-cdk-lib/aws-elasticloadbalancingv2/lib/alb/trust-store-revocation.ts
  packages/aws-cdk-lib/aws-elasticloadbalancingv2/lib/alb/trust-store.ts
  packages/aws-cdk-lib/aws-elasticloadbalancingv2/lib/index.ts
  packages/aws-cdk-lib/aws-elasticloadbalancingv2/test/alb/listener.test.ts
  packages/aws-cdk-lib/aws-elasticloadbalancingv2/test/alb/trust-store-revocation.test.ts
  packages/aws-cdk-lib/aws-elasticloadbalancingv2/test/alb/trust-store.test.ts
  packages/aws-cdk-lib/awslint.json
Labels: p2, feature-request, effort/medium, star-contributor

#30928 feat(batch): add ECS_AL2023
  packages/@aws-cdk-testing/framework-integ/test/aws-batch/test/integ.managed-compute-environment.js.snapshot/BatchManagedComputeEnvironmentTestDefaultTestDeployAssertD4528F80.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-batch/test/integ.managed-compute-environment.js.snapshot/batch-stack.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-batch/test/integ.managed-compute-environment.js.snapshot/batch-stack.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-batch/test/integ.managed-compute-environment.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-batch/test/integ.managed-compute-environment.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-batch/test/integ.managed-compute-environment.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-batch/test/integ.managed-compute-environment.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-batch/test/integ.managed-compute-environment.ts
  packages/aws-cdk-lib/aws-batch/README.md
  packages/aws-cdk-lib/aws-batch/lib/managed-compute-environment.ts
  packages/aws-cdk-lib/aws-batch/test/managed-compute-environment.test.ts
Labels: p2, admired-contributor, pr/needs-maintainer-review

#30807 chore(ec2): add missing interface vpc endpoints
  packages/aws-cdk-lib/aws-ec2/lib/vpc-endpoint.ts
Labels: p2, star-contributor

#31044 feat(region-info): update Metadata regions
  packages/aws-cdk-lib/region-info/build-tools/metadata.ts
Labels: p2, dependencies, contribution/core, pr-linter/exempt-readme, pr-linter/exempt-test, auto-approve, pr-linter/exempt-integ-test

#31007 docs(opensearchservice): fix broken Markdown due to an invisible char
  packages/aws-cdk-lib/aws-opensearchservice/README.md
Labels: p2, beginning-contributor

#31046 feat(region-info): update Metadata regions
  packages/aws-cdk-lib/region-info/build-tools/metadata.ts
Labels: p2, dependencies, contribution/core, pr-linter/exempt-readme, pr-linter/exempt-test, auto-approve, pr-linter/exempt-integ-test

#31047 feat(region-info): update Metadata regions
  packages/aws-cdk-lib/region-info/build-tools/metadata.ts
Labels: p2, dependencies, contribution/core, pr-linter/exempt-readme, pr-linter/exempt-test, auto-approve, pr-linter/exempt-integ-test

#31056 chore: add needs-triage to issue templates
  .github/ISSUE_TEMPLATE/notice.yml
  .github/ISSUE_TEMPLATE/region.yml
  .github/ISSUE_TEMPLATE/tracking.yml
Labels: p2, contribution/core

#31065 revert: feat(ec2): security group lookup via filters
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.security-group-lookup.js.snapshot/LookupStack.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.security-group-lookup.js.snapshot/LookupStack.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.security-group-lookup.js.snapshot/SgLookupTestDefaultTestDeployAssert9466B7BF.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.security-group-lookup.js.snapshot/SgLookupTestDefaultTestDeployAssert9466B7BF.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.security-group-lookup.js.snapshot/StackWithSg.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.security-group-lookup.js.snapshot/StackWithSg.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.security-group-lookup.js.snapshot/asset.bde7b5c89cb43285f884c94f0b9e17cdb0f5eb5345005114dd60342e0b8a85a1/__entrypoint__.js
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.security-group-lookup.js.snapshot/asset.bde7b5c89cb43285f884c94f0b9e17cdb0f5eb5345005114dd60342e0b8a85a1/index.js
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.security-group-lookup.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.security-group-lookup.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.security-group-lookup.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.security-group-lookup.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.security-group-lookup.ts
  packages/aws-cdk-lib/aws-ec2/README.md
  packages/aws-cdk-lib/aws-ec2/lib/security-group.ts
  packages/aws-cdk-lib/aws-ec2/test/security-group.test.ts
  packages/aws-cdk-lib/cloud-assembly-schema/lib/cloud-assembly/context-queries.ts
  packages/aws-cdk-lib/cloud-assembly-schema/schema/cloud-assembly.schema.json
  packages/aws-cdk-lib/cloud-assembly-schema/schema/cloud-assembly.version.json
  packages/aws-cdk/lib/context-providers/security-groups.ts
  packages/aws-cdk/test/context-providers/security-groups.test.ts
Labels: p2, contribution/core, pr-linter/cli-integ-tested

#30821 fix(ec2): prevent deduplication of init command args
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.instance-init-multiple.js.snapshot/integ-ec2-multiple-instances-in-stack.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.instance-init-multiple.js.snapshot/integ-ec2-multiple-instances-in-stack.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.instance-init-multiple.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.instance-init-multiple.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.instance-init-multiple.ts
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.instance-init.js.snapshot/manifest.json
  packages/aws-cdk-lib/aws-ec2/lib/cfn-init.ts
  packages/aws-cdk-lib/aws-ec2/test/cfn-init.test.ts
Labels: bug, p1, effort/medium, contribution/core

#30599 feat(elasticloadbalancingv2): connection logs for ALB
  packages/@aws-cdk-testing/framework-integ/test/aws-elasticloadbalancingv2/test/integ.alb.extended.log.js.snapshot/aws-cdk-elbv2-integ.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-elasticloadbalancingv2/test/integ.alb.extended.log.js.snapshot/aws-cdk-elbv2-integ.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-elasticloadbalancingv2/test/integ.alb.extended.log.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-elasticloadbalancingv2/test/integ.alb.extended.log.js.snapshot/cdkintegalbextendedlogDefaultTestDeployAssertAEFAB19B.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-elasticloadbalancingv2/test/integ.alb.extended.log.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-elasticloadbalancingv2/test/integ.alb.extended.log.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-elasticloadbalancingv2/test/integ.alb.extended.log.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-elasticloadbalancingv2/test/integ.alb.extended.log.ts
  packages/@aws-cdk-testing/framework-integ/test/aws-elasticloadbalancingv2/test/integ.alb.log.imported-bucket.js.snapshot/aws-cdk-alb-log-imported-bucket-integ.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-elasticloadbalancingv2/test/integ.alb.log.imported-bucket.js.snapshot/aws-cdk-alb-log-imported-bucket-integ.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-elasticloadbalancingv2/test/integ.alb.log.imported-bucket.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-elasticloadbalancingv2/test/integ.alb.log.imported-bucket.js.snapshot/cdkintegalblogimportedbucketDefaultTestDeployAssert163162C1.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-elasticloadbalancingv2/test/integ.alb.log.imported-bucket.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-elasticloadbalancingv2/test/integ.alb.log.imported-bucket.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-elasticloadbalancingv2/test/integ.alb.log.imported-bucket.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-elasticloadbalancingv2/test/integ.alb.log.imported-bucket.ts
  packages/@aws-cdk-testing/framework-integ/test/aws-elasticloadbalancingv2/test/integ.alb.log.js.snapshot/aws-cdk-elbv2-integ.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-elasticloadbalancingv2/test/integ.alb.log.js.snapshot/aws-cdk-elbv2-integ.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-elasticloadbalancingv2/test/integ.alb.log.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-elasticloadbalancingv2/test/integ.alb.log.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-elasticloadbalancingv2/test/integ.alb.log.ts
  packages/aws-cdk-lib/aws-elasticloadbalancingv2/README.md
  packages/aws-cdk-lib/aws-elasticloadbalancingv2/lib/alb/application-load-balancer.ts
  packages/aws-cdk-lib/aws-elasticloadbalancingv2/test/alb/load-balancer.test.ts
Labels: p2, star-contributor

#31086 feat: update L1 CloudFormation resource definitions
  packages/@aws-cdk/cloudformation-diff/package.json
  packages/@aws-cdk/integ-runner/package.json
  packages/aws-cdk-lib/package.json
  tools/@aws-cdk/spec2cdk/package.json
  yarn.lock
Labels: p2, dependencies, contribution/core, pr-linter/exempt-readme, pr-linter/exempt-test, auto-approve, pr-linter/exempt-integ-test

#31088 chore(rds): added Postgres 16.4 version
  packages/aws-cdk-lib/aws-rds/lib/instance-engine.ts
Labels: p2, feature-request, effort/small

#31018 docs(cloudfront): fix typos
  packages/aws-cdk-lib/aws-cloudfront/lib/web-distribution.ts
Labels: p2, beginning-contributor

#31057 chore(template): adding regression info in the bug template
  .github/ISSUE_TEMPLATE/bug-report.yml
  .github/workflows/issue-regression-labeler.yml
Labels: p2, contribution/core

#31045 chore(bedrock): support Titan Image Generator v2
  packages/aws-cdk-lib/aws-bedrock/lib/foundation-model.ts
Labels: p2, distinguished-contributor, pr/needs-maintainer-review

#31095 chore(rds): add missing RDS instance engine versions for PostgreSQL, MySQL, and SQL Server
  packages/aws-cdk-lib/aws-rds/lib/instance-engine.ts
Labels: p2, distinguished-contributor, pr/needs-maintainer-review

#31094 chore(rds): add Aurora PostgreSQL cluster engine version 14.12, 13.15 and 12.19
  packages/aws-cdk-lib/aws-rds/lib/cluster-engine.ts
Labels: p2, distinguished-contributor

#31085 chore(rds): add support for aurora-postgresql 15.7
  packages/aws-cdk-lib/aws-rds/lib/cluster-engine.ts
  packages/aws-cdk-lib/aws-rds/test/cluster-engine.test.ts
Labels: p2, beginning-contributor

#30657 feat(sagemaker): network isolation for a model
  packages/@aws-cdk/aws-sagemaker-alpha/README.md
  packages/@aws-cdk/aws-sagemaker-alpha/lib/model.ts
  packages/@aws-cdk/aws-sagemaker-alpha/test/integ.model.js.snapshot/aws-cdk-sagemaker-model.assets.json
  packages/@aws-cdk/aws-sagemaker-alpha/test/integ.model.js.snapshot/aws-cdk-sagemaker-model.template.json
  packages/@aws-cdk/aws-sagemaker-alpha/test/integ.model.js.snapshot/manifest.json
  packages/@aws-cdk/aws-sagemaker-alpha/test/integ.model.js.snapshot/tree.json
  packages/@aws-cdk/aws-sagemaker-alpha/test/integ.model.ts
  packages/@aws-cdk/aws-sagemaker-alpha/test/model.test.ts
Labels: p2, distinguished-contributor, pr/needs-maintainer-review

#30551 feat(core): configure SNS topics to receive stack events on the Stack construct
  packages/@aws-cdk-testing/cli-integ/lib/package-sources/repo-source.ts
  packages/@aws-cdk-testing/cli-integ/lib/with-cdk-app.ts
  packages/@aws-cdk-testing/cli-integ/resources/cdk-apps/app/app.js
  packages/@aws-cdk-testing/cli-integ/tests/cli-integ-tests/cli.integtest.ts
  packages/aws-cdk-lib/cloud-assembly-schema/lib/cloud-assembly/artifact-schema.ts
  packages/aws-cdk-lib/cloud-assembly-schema/schema/cloud-assembly.schema.json
  packages/aws-cdk-lib/cloud-assembly-schema/schema/cloud-assembly.version.json
  packages/aws-cdk-lib/core/README.md
  packages/aws-cdk-lib/core/lib/stack-synthesizers/_shared.ts
  packages/aws-cdk-lib/core/lib/stack.ts
  packages/aws-cdk-lib/core/test/stack.test.ts
  packages/aws-cdk-lib/cx-api/lib/artifacts/cloudformation-artifact.ts
  packages/aws-cdk-lib/cx-api/test/stack-artifact.test.ts
  packages/aws-cdk/lib/api/deploy-stack.ts
  packages/aws-cdk/lib/api/util/cloudformation.ts
  packages/aws-cdk/lib/cdk-toolkit.ts
  packages/aws-cdk/test/api/deploy-stack.test.ts
  packages/aws-cdk/test/cdk-toolkit.test.ts
  packages/aws-cdk/test/util.ts
Labels: p1, contribution/core, pr-linter/exempt-integ-test, pr-linter/cli-integ-tested

#31100 revert: feat(core): configure SNS topics to receive stack events on the Stack construct
  packages/@aws-cdk-testing/cli-integ/lib/package-sources/repo-source.ts
  packages/@aws-cdk-testing/cli-integ/lib/with-cdk-app.ts
  packages/@aws-cdk-testing/cli-integ/resources/cdk-apps/app/app.js
  packages/@aws-cdk-testing/cli-integ/tests/cli-integ-tests/cli.integtest.ts
  packages/aws-cdk-lib/cloud-assembly-schema/lib/cloud-assembly/artifact-schema.ts
  packages/aws-cdk-lib/cloud-assembly-schema/schema/cloud-assembly.schema.json
  packages/aws-cdk-lib/cloud-assembly-schema/schema/cloud-assembly.version.json
  packages/aws-cdk-lib/core/README.md
  packages/aws-cdk-lib/core/lib/stack-synthesizers/_shared.ts
  packages/aws-cdk-lib/core/lib/stack.ts
  packages/aws-cdk-lib/core/test/stack.test.ts
  packages/aws-cdk-lib/cx-api/lib/artifacts/cloudformation-artifact.ts
  packages/aws-cdk-lib/cx-api/test/stack-artifact.test.ts
  packages/aws-cdk/lib/api/deploy-stack.ts
  packages/aws-cdk/lib/api/util/cloudformation.ts
  packages/aws-cdk/lib/cdk-toolkit.ts
  packages/aws-cdk/test/api/deploy-stack.test.ts
  packages/aws-cdk/test/cdk-toolkit.test.ts
  packages/aws-cdk/test/util.ts
Labels: p2, contribution/core, pr-linter/cli-integ-tested

#31110 revert: feat(ecs): add validation checks to memory cpu combinations of FARGATE compatible task definitions
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs/test/integ.fargate-task-def.js.snapshot/FargateTaskDefinitionDefaultTestDeployAssertD76B1D35.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs/test/integ.fargate-task-def.js.snapshot/FargateTaskDefinitionDefaultTestDeployAssertD76B1D35.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs/test/integ.fargate-task-def.js.snapshot/aws-ecs-fargate-task-def.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs/test/integ.fargate-task-def.js.snapshot/aws-ecs-fargate-task-def.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs/test/integ.fargate-task-def.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs/test/integ.fargate-task-def.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs/test/integ.fargate-task-def.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs/test/integ.fargate-task-def.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs/test/integ.fargate-task-def.ts
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs/test/integ.task-def.js.snapshot/TaskDefinitionDefaultTestDeployAssertF13B2133.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs/test/integ.task-def.js.snapshot/TaskDefinitionDefaultTestDeployAssertF13B2133.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs/test/integ.task-def.js.snapshot/aws-ecs-task-def.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs/test/integ.task-def.js.snapshot/aws-ecs-task-def.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs/test/integ.task-def.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs/test/integ.task-def.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs/test/integ.task-def.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs/test/integ.task-def.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs/test/integ.task-def.ts
  packages/aws-cdk-lib/aws-codepipeline-actions/test/servicecatalog/servicecatalog-deploy-action-beta1.test.ts
  packages/aws-cdk-lib/aws-ecs-patterns/test/fargate/load-balanced-fargate-service-v2.test.ts
  packages/aws-cdk-lib/aws-ecs-patterns/test/fargate/load-balanced-fargate-service.test.ts
  packages/aws-cdk-lib/aws-ecs-patterns/test/fargate/scheduled-fargate-task.test.ts
  packages/aws-cdk-lib/aws-ecs/README.md
  packages/aws-cdk-lib/aws-ecs/lib/base/task-definition.ts
  packages/aws-cdk-lib/aws-ecs/test/fargate/fargate-task-definition.test.ts
  packages/aws-cdk-lib/aws-ecs/test/task-definition.test.ts
  packages/aws-cdk/test/api/cloudformation-deployments.test.ts
Labels: p2, contribution/core

#31111 chore(release): 2.151.1
  CHANGELOG.v2.alpha.md
  CHANGELOG.v2.md
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs/test/integ.fargate-task-def.js.snapshot/FargateTaskDefinitionDefaultTestDeployAssertD76B1D35.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs/test/integ.fargate-task-def.js.snapshot/FargateTaskDefinitionDefaultTestDeployAssertD76B1D35.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs/test/integ.fargate-task-def.js.snapshot/aws-ecs-fargate-task-def.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs/test/integ.fargate-task-def.js.snapshot/aws-ecs-fargate-task-def.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs/test/integ.fargate-task-def.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs/test/integ.fargate-task-def.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs/test/integ.fargate-task-def.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs/test/integ.fargate-task-def.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs/test/integ.fargate-task-def.ts
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs/test/integ.task-def.js.snapshot/TaskDefinitionDefaultTestDeployAssertF13B2133.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs/test/integ.task-def.js.snapshot/TaskDefinitionDefaultTestDeployAssertF13B2133.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs/test/integ.task-def.js.snapshot/aws-ecs-task-def.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs/test/integ.task-def.js.snapshot/aws-ecs-task-def.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs/test/integ.task-def.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs/test/integ.task-def.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs/test/integ.task-def.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs/test/integ.task-def.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs/test/integ.task-def.ts
  packages/aws-cdk-lib/aws-codepipeline-actions/test/servicecatalog/servicecatalog-deploy-action-beta1.test.ts
  packages/aws-cdk-lib/aws-ecs-patterns/test/fargate/load-balanced-fargate-service-v2.test.ts
  packages/aws-cdk-lib/aws-ecs-patterns/test/fargate/load-balanced-fargate-service.test.ts
  packages/aws-cdk-lib/aws-ecs-patterns/test/fargate/scheduled-fargate-task.test.ts
  packages/aws-cdk-lib/aws-ecs/README.md
  packages/aws-cdk-lib/aws-ecs/lib/base/task-definition.ts
  packages/aws-cdk-lib/aws-ecs/test/fargate/fargate-task-definition.test.ts
  packages/aws-cdk-lib/aws-ecs/test/task-definition.test.ts
  packages/aws-cdk/test/api/cloudformation-deployments.test.ts
  version.v2.json
Labels: p2, contribution/core, pr/no-squash

#31102 fix(vpc-v2): fixing default scope id
  packages/@aws-cdk/aws-ec2-alpha/lib/ipam.ts
  packages/@aws-cdk/aws-ec2-alpha/test/integ.subnet-v2.js.snapshot/aws-cdk-vpcv2-alpha-new.assets.json
  packages/@aws-cdk/aws-ec2-alpha/test/integ.subnet-v2.js.snapshot/aws-cdk-vpcv2-alpha-new.template.json
  packages/@aws-cdk/aws-ec2-alpha/test/integ.subnet-v2.js.snapshot/cdk.out
  packages/@aws-cdk/aws-ec2-alpha/test/integ.subnet-v2.js.snapshot/integ.json
  packages/@aws-cdk/aws-ec2-alpha/test/integ.subnet-v2.js.snapshot/integtestmodelDefaultTestDeployAssertCF40BD53.assets.json
  packages/@aws-cdk/aws-ec2-alpha/test/integ.subnet-v2.js.snapshot/manifest.json
  packages/@aws-cdk/aws-ec2-alpha/test/integ.subnet-v2.js.snapshot/tree.json
  packages/@aws-cdk/aws-ec2-alpha/test/integ.subnet-v2.ts
  packages/@aws-cdk/aws-ec2-alpha/test/integ.vpc-v2-alpha.js.snapshot/aws-cdk-vpcv2-alpha.assets.json
  packages/@aws-cdk/aws-ec2-alpha/test/integ.vpc-v2-alpha.js.snapshot/aws-cdk-vpcv2-alpha.template.json
  packages/@aws-cdk/aws-ec2-alpha/test/integ.vpc-v2-alpha.js.snapshot/cdk.out
  packages/@aws-cdk/aws-ec2-alpha/test/integ.vpc-v2-alpha.js.snapshot/integ.json
  packages/@aws-cdk/aws-ec2-alpha/test/integ.vpc-v2-alpha.js.snapshot/integtestmodelDefaultTestDeployAssertCF40BD53.assets.json
  packages/@aws-cdk/aws-ec2-alpha/test/integ.vpc-v2-alpha.js.snapshot/manifest.json
  packages/@aws-cdk/aws-ec2-alpha/test/integ.vpc-v2-alpha.js.snapshot/tree.json
  packages/@aws-cdk/aws-ec2-alpha/test/integ.vpc-v2-alpha.ts
  packages/@aws-cdk/aws-ec2-alpha/test/ipam.test.ts
  packages/@aws-cdk/aws-ec2-alpha/test/subnet-v2.test.ts
  packages/@aws-cdk/aws-ec2-alpha/test/vpc-v2.test.ts
Labels: p2, contribution/core

#30817 chore(ec2): add `mac2-m1ultra` instance type
  packages/aws-cdk-lib/aws-ec2/lib/instance-types.ts
  packages/aws-cdk-lib/aws-ec2/test/instance-type.test.ts
Labels: p2, distinguished-contributor

#30995 chore: update Contributors File
  CONTRIBUTORS.md
Labels: p2, auto-approve

#30791 feat(amplify): support custom certificate
  packages/@aws-cdk/aws-amplify-alpha/README.md
  packages/@aws-cdk/aws-amplify-alpha/lib/domain.ts
  packages/@aws-cdk/aws-amplify-alpha/rosetta/default.ts-fixture
  packages/@aws-cdk/aws-amplify-alpha/test/domain.test.ts
  packages/@aws-cdk/aws-amplify-alpha/test/integ.app-custom-domain.js.snapshot/amplifyappcustomdomainintegDefaultTestDeployAssert5F8CD1EB.assets.json
  packages/@aws-cdk/aws-amplify-alpha/test/integ.app-custom-domain.js.snapshot/amplifyappcustomdomainintegDefaultTestDeployAssert5F8CD1EB.template.json
  packages/@aws-cdk/aws-amplify-alpha/test/integ.app-custom-domain.js.snapshot/cdk-amplify-app-custom-domain.assets.json
  packages/@aws-cdk/aws-amplify-alpha/test/integ.app-custom-domain.js.snapshot/cdk-amplify-app-custom-domain.template.json
  packages/@aws-cdk/aws-amplify-alpha/test/integ.app-custom-domain.js.snapshot/cdk.out
  packages/@aws-cdk/aws-amplify-alpha/test/integ.app-custom-domain.js.snapshot/integ.json
  packages/@aws-cdk/aws-amplify-alpha/test/integ.app-custom-domain.js.snapshot/manifest.json
  packages/@aws-cdk/aws-amplify-alpha/test/integ.app-custom-domain.js.snapshot/tree.json
  packages/@aws-cdk/aws-amplify-alpha/test/integ.app-custom-domain.ts
Labels: p2, feature-request, effort/small, star-contributor

#30882 fix(cognito-identitypool-alpha): validation error if provided id is a token
  packages/@aws-cdk/aws-cognito-identitypool-alpha/lib/identitypool.ts
  packages/@aws-cdk/aws-cognito-identitypool-alpha/test/identitypool.test.ts
Labels: bug, p2, effort/medium, pr-linter/exempt-integ-test, admired-contributor

#31118 chore(release): 2.152.0
  CHANGELOG.v2.alpha.md
  CHANGELOG.v2.md
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-event-sources/test/integ.dynamodb-with-filter-criteria.js.snapshot/DynamoDBFilterCriteriaDefaultTestDeployAssert448231D5.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-event-sources/test/integ.dynamodb-with-filter-criteria.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-event-sources/test/integ.dynamodb-with-filter-criteria.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-event-sources/test/integ.dynamodb-with-filter-criteria.js.snapshot/lambda-event-source-filter-criteria-dynamodb.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-event-sources/test/integ.dynamodb-with-filter-criteria.js.snapshot/lambda-event-source-filter-criteria-dynamodb.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-event-sources/test/integ.dynamodb-with-filter-criteria.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-event-sources/test/integ.dynamodb-with-filter-criteria.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-event-sources/test/integ.dynamodb-with-filter-criteria.ts
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-event-sources/test/integ.kafka-selfmanaged.js.snapshot/LambdaEventSourceKafkaSelfManagedTestDefaultTestDeployAssertAF78BD0F.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-event-sources/test/integ.kafka-selfmanaged.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-event-sources/test/integ.kafka-selfmanaged.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-event-sources/test/integ.kafka-selfmanaged.js.snapshot/lambda-event-source-kafka-self-managed.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-event-sources/test/integ.kafka-selfmanaged.js.snapshot/lambda-event-source-kafka-self-managed.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-event-sources/test/integ.kafka-selfmanaged.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-event-sources/test/integ.kafka-selfmanaged.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-event-sources/test/integ.kafka-selfmanaged.ts
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-event-sources/test/integ.sqs-with-filter-criteria.js.snapshot/SQSFilterCriteriaDefaultTestDeployAssert70A9A808.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-event-sources/test/integ.sqs-with-filter-criteria.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-event-sources/test/integ.sqs-with-filter-criteria.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-event-sources/test/integ.sqs-with-filter-criteria.js.snapshot/lambda-event-source-filter-criteria-sqs.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-event-sources/test/integ.sqs-with-filter-criteria.js.snapshot/lambda-event-source-filter-criteria-sqs.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-event-sources/test/integ.sqs-with-filter-criteria.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-event-sources/test/integ.sqs-with-filter-criteria.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-event-sources/test/integ.sqs-with-filter-criteria.ts
  packages/aws-cdk-lib/aws-lambda-event-sources/README.md
  packages/aws-cdk-lib/aws-lambda-event-sources/lib/kafka.ts
  packages/aws-cdk-lib/aws-lambda-event-sources/lib/sqs.ts
  packages/aws-cdk-lib/aws-lambda-event-sources/lib/stream.ts
  packages/aws-cdk-lib/aws-lambda-event-sources/test/dynamo.test.ts
  packages/aws-cdk-lib/aws-lambda-event-sources/test/kafka.test.ts
  packages/aws-cdk-lib/aws-lambda-event-sources/test/sqs.test.ts
  packages/aws-cdk-lib/aws-lambda/README.md
  packages/aws-cdk-lib/aws-lambda/lib/event-source-mapping.ts
  packages/aws-cdk-lib/aws-lambda/test/event-source-mapping.test.ts
  tools/@aws-cdk/spec2cdk/temporary-schemas/us-east-1/aws-lambda-eventsourcemapping.json
  version.v2.json
Labels: p2, contribution/core, pr/no-squash

#31121 chore(merge-back): 2.152.0
  CHANGELOG.v2.alpha.md
  CHANGELOG.v2.md
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-event-sources/test/integ.dynamodb-with-filter-criteria.js.snapshot/DynamoDBFilterCriteriaDefaultTestDeployAssert448231D5.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-event-sources/test/integ.dynamodb-with-filter-criteria.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-event-sources/test/integ.dynamodb-with-filter-criteria.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-event-sources/test/integ.dynamodb-with-filter-criteria.js.snapshot/lambda-event-source-filter-criteria-dynamodb.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-event-sources/test/integ.dynamodb-with-filter-criteria.js.snapshot/lambda-event-source-filter-criteria-dynamodb.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-event-sources/test/integ.dynamodb-with-filter-criteria.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-event-sources/test/integ.dynamodb-with-filter-criteria.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-event-sources/test/integ.dynamodb-with-filter-criteria.ts
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-event-sources/test/integ.kafka-selfmanaged.js.snapshot/LambdaEventSourceKafkaSelfManagedTestDefaultTestDeployAssertAF78BD0F.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-event-sources/test/integ.kafka-selfmanaged.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-event-sources/test/integ.kafka-selfmanaged.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-event-sources/test/integ.kafka-selfmanaged.js.snapshot/lambda-event-source-kafka-self-managed.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-event-sources/test/integ.kafka-selfmanaged.js.snapshot/lambda-event-source-kafka-self-managed.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-event-sources/test/integ.kafka-selfmanaged.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-event-sources/test/integ.kafka-selfmanaged.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-event-sources/test/integ.kafka-selfmanaged.ts
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-event-sources/test/integ.sqs-with-filter-criteria.js.snapshot/SQSFilterCriteriaDefaultTestDeployAssert70A9A808.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-event-sources/test/integ.sqs-with-filter-criteria.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-event-sources/test/integ.sqs-with-filter-criteria.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-event-sources/test/integ.sqs-with-filter-criteria.js.snapshot/lambda-event-source-filter-criteria-sqs.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-event-sources/test/integ.sqs-with-filter-criteria.js.snapshot/lambda-event-source-filter-criteria-sqs.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-event-sources/test/integ.sqs-with-filter-criteria.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-event-sources/test/integ.sqs-with-filter-criteria.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-event-sources/test/integ.sqs-with-filter-criteria.ts
  packages/aws-cdk-lib/aws-lambda-event-sources/README.md
  packages/aws-cdk-lib/aws-lambda-event-sources/lib/kafka.ts
  packages/aws-cdk-lib/aws-lambda-event-sources/lib/sqs.ts
  packages/aws-cdk-lib/aws-lambda-event-sources/lib/stream.ts
  packages/aws-cdk-lib/aws-lambda-event-sources/test/dynamo.test.ts
  packages/aws-cdk-lib/aws-lambda-event-sources/test/kafka.test.ts
  packages/aws-cdk-lib/aws-lambda-event-sources/test/sqs.test.ts
  packages/aws-cdk-lib/aws-lambda/README.md
  packages/aws-cdk-lib/aws-lambda/lib/event-source-mapping.ts
  packages/aws-cdk-lib/aws-lambda/test/event-source-mapping.test.ts
  tools/@aws-cdk/spec2cdk/temporary-schemas/us-east-1/aws-lambda-eventsourcemapping.json
  version.v2.json
Labels: p2, pr/needs-community-review, pr/no-squash, auto-approve

#31120 feat: update L1 CloudFormation resource definitions
  package.json
  packages/@aws-cdk/cloudformation-diff/package.json
  packages/@aws-cdk/integ-runner/package.json
  packages/aws-cdk-lib/package.json
  tools/@aws-cdk/spec2cdk/package.json
  yarn.lock
Labels: p2, dependencies, contribution/core, pr-linter/exempt-readme, pr-linter/exempt-test, auto-approve, pr-linter/exempt-integ-test, pr/needs-maintainer-review

#30396 fix(elasticloadbalancingv2-targets): add AlbListenerTarget for NLBs, deprecate AlbTarget due to ALB listener race conditions (#17208)
  packages/@aws-cdk-testing/framework-integ/test/aws-elasticloadbalancingv2-targets/test/integ.alb-listner-target.js.snapshot/IntegDefaultTestDeployAssert4E6713E1.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-elasticloadbalancingv2-targets/test/integ.alb-listner-target.js.snapshot/IntegDefaultTestDeployAssert4E6713E1.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-elasticloadbalancingv2-targets/test/integ.alb-listner-target.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-elasticloadbalancingv2-targets/test/integ.alb-listner-target.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-elasticloadbalancingv2-targets/test/integ.alb-listner-target.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-elasticloadbalancingv2-targets/test/integ.alb-listner-target.js.snapshot/nlb-alb-listner-stack.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-elasticloadbalancingv2-targets/test/integ.alb-listner-target.js.snapshot/nlb-alb-listner-stack.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-elasticloadbalancingv2-targets/test/integ.alb-listner-target.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-elasticloadbalancingv2-targets/test/integ.alb-listner-target.ts
  packages/aws-cdk-lib/aws-elasticloadbalancingv2-targets/lib/alb-target.ts
  packages/aws-cdk-lib/aws-elasticloadbalancingv2-targets/test/alb-target.test.ts
  packages/aws-cdk-lib/aws-elasticloadbalancingv2/README.md
  packages/aws-cdk-lib/aws-elasticloadbalancingv2/lib/alb/application-listener.ts
Labels: bug, p2, effort/small, beginning-contributor

#31092 feat(CLI): synth displays "AssertDescription: CDK bootstrap stack version 6 required"
  packages/@aws-cdk-testing/cli-integ/tests/cli-integ-tests/cli.integtest.ts
  packages/aws-cdk/README.md
  packages/aws-cdk/lib/cdk-toolkit.ts
  packages/aws-cdk/lib/cli.ts
  packages/aws-cdk/lib/diff.ts
  packages/aws-cdk/test/diff.test.ts
Labels: bug, p1, effort/medium, contribution/core, pr-linter/exempt-integ-test, pr-linter/cli-integ-tested

#31019 fix(lambda): validate localMountPath format and length
  packages/aws-cdk-lib/aws-lambda/lib/function.ts
  packages/aws-cdk-lib/aws-lambda/test/function.test.ts
Labels: bug, p2, effort/small, pr-linter/exempt-integ-test, beginning-contributor

#31115 chore(applicationautoscaling): add missing PredefinedMetricType enum values
  packages/aws-cdk-lib/aws-applicationautoscaling/lib/target-tracking-scaling-policy.ts
  packages/aws-cdk-lib/aws-applicationautoscaling/test/target-tracking.test.ts
Labels: p2, feature-request, pr/needs-community-review, beginning-contributor

#30916 feat(s3): add skip destination validation property
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-event-sources/test/integ.s3.imported-bucket.js.snapshot/TestStack.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-event-sources/test/integ.s3.imported-bucket.js.snapshot/TestStack1.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-event-sources/test/integ.s3.imported-bucket.js.snapshot/TestStack1.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-event-sources/test/integ.s3.imported-bucket.js.snapshot/TestStack2.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-event-sources/test/integ.s3.imported-bucket.js.snapshot/TestStack2.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-event-sources/test/integ.s3.imported-bucket.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-event-sources/test/integ.s3.imported-bucket.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-event-sources/test/integ.s3.imported-bucket.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-event-sources/test/integ.s3.imported-bucket.ts
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-event-sources/test/integ.s3.js.snapshot/lambda-event-source-s3.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-event-sources/test/integ.s3.js.snapshot/lambda-event-source-s3.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-event-sources/test/integ.s3.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-s3-notifications/test/integ.notifications.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-s3-notifications/test/integ.notifications.js.snapshot/test-3.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-s3-notifications/test/integ.notifications.js.snapshot/test-3.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-s3-notifications/test/lambda/integ.bucket-notifications.js.snapshot/LambdaBucketNotificationsTestDefaultTestDeployAssertDC5450F4.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-s3-notifications/test/lambda/integ.bucket-notifications.js.snapshot/LambdaBucketNotificationsTestDefaultTestDeployAssertDC5450F4.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-s3-notifications/test/lambda/integ.bucket-notifications.js.snapshot/asset.3cef2cdbb46b3821e641ffb8b9af9731af5f7e4a9e857ab633dbcd9023de724d.bundle/index.js
  packages/@aws-cdk-testing/framework-integ/test/aws-s3-notifications/test/lambda/integ.bucket-notifications.js.snapshot/cdk-integ-lambda-bucket-s3-notifications.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-s3-notifications/test/lambda/integ.bucket-notifications.js.snapshot/cdk-integ-lambda-bucket-s3-notifications.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-s3-notifications/test/lambda/integ.bucket-notifications.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-s3-notifications/test/lambda/integ.bucket-notifications.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-s3-notifications/test/lambda/integ.bucket-notifications.ts
  packages/@aws-cdk-testing/framework-integ/test/aws-s3-notifications/test/sns/integ.sns-bucket-notifications.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-s3-notifications/test/sns/integ.sns-bucket-notifications.js.snapshot/sns-bucket-notifications.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-s3-notifications/test/sqs/integ.bucket-notifications-unmanaged.js.snapshot/SQSBucketNotificationsTestDefaultTestDeployAssert53BCF57E.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-s3-notifications/test/sqs/integ.bucket-notifications-unmanaged.js.snapshot/SQSBucketNotificationsTestDefaultTestDeployAssert53BCF57E.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-s3-notifications/test/sqs/integ.bucket-notifications-unmanaged.js.snapshot/asset.3cef2cdbb46b3821e641ffb8b9af9731af5f7e4a9e857ab633dbcd9023de724d.bundle/index.js
  packages/@aws-cdk-testing/framework-integ/test/aws-s3-notifications/test/sqs/integ.bucket-notifications-unmanaged.js.snapshot/integ-sqs-bucket-notifications.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-s3-notifications/test/sqs/integ.bucket-notifications-unmanaged.js.snapshot/integ-sqs-bucket-notifications.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-s3-notifications/test/sqs/integ.bucket-notifications-unmanaged.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-s3-notifications/test/sqs/integ.bucket-notifications.js.snapshot/SQSBucketNotificationsTestDefaultTestDeployAssert53BCF57E.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-s3-notifications/test/sqs/integ.bucket-notifications.js.snapshot/SQSBucketNotificationsTestDefaultTestDeployAssert53BCF57E.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-s3-notifications/test/sqs/integ.bucket-notifications.js.snapshot/asset.3cef2cdbb46b3821e641ffb8b9af9731af5f7e4a9e857ab633dbcd9023de724d.bundle/index.js
  packages/@aws-cdk-testing/framework-integ/test/aws-s3-notifications/test/sqs/integ.bucket-notifications.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-s3-notifications/test/sqs/integ.bucket-notifications.js.snapshot/sqs-bucket-notifications.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-s3-notifications/test/sqs/integ.bucket-notifications.js.snapshot/sqs-bucket-notifications.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-s3-notifications/test/sqs/integ.bucket-notifications.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-s3-notifications/test/sqs/integ.bucket-notifications.ts
  packages/@aws-cdk-testing/framework-integ/test/aws-s3/test/integ.bucket.notifications.js.snapshot/aws-cdk-s3-notifications.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-s3/test/integ.bucket.notifications.js.snapshot/aws-cdk-s3-notifications.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-s3/test/integ.bucket.notifications.js.snapshot/manifest.json
  packages/@aws-cdk/custom-resource-handlers/lib/aws-s3/notifications-resource-handler/index.py
  packages/@aws-cdk/custom-resource-handlers/lib/custom-resources-framework/config.ts
  packages/@aws-cdk/custom-resource-handlers/lib/custom-resources-framework/utils/framework-utils.ts
  packages/@aws-cdk/custom-resource-handlers/test/aws-s3/notifications-resource-handler/Dockerfile
  packages/@aws-cdk/custom-resource-handlers/test/aws-s3/notifications-resource-handler/test_index.py
  packages/aws-cdk-lib/aws-s3-notifications/test/notifications.test.ts
  packages/aws-cdk-lib/aws-s3/README.md
  packages/aws-cdk-lib/aws-s3/lib/bucket.ts
  packages/aws-cdk-lib/aws-s3/lib/notifications-resource/notifications-resource-handler.ts
  packages/aws-cdk-lib/aws-s3/lib/notifications-resource/notifications-resource.ts
  packages/aws-cdk-lib/aws-s3/test/notification.test.ts
Labels: p2, feature-request, pr/needs-community-review, effort/medium, valued-contributor

#30646 feat(ssm): support cross-account sharing
  packages/@aws-cdk-testing/framework-integ/test/aws-ssm/test/integ.parameter-store-string-sharing.js.snapshot/SSMParameterStoreSharingTestDefaultTestDeployAssert51CBB447.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ssm/test/integ.parameter-store-string-sharing.js.snapshot/SSMParameterStoreSharingTestDefaultTestDeployAssert51CBB447.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ssm/test/integ.parameter-store-string-sharing.js.snapshot/asset.eafc02f6925151c95ac6a6ae81a3e36d4cf4e77db52eec8e467ce2a69454a41a.bundle/index.js
  packages/@aws-cdk-testing/framework-integ/test/aws-ssm/test/integ.parameter-store-string-sharing.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-ssm/test/integ.parameter-store-string-sharing.js.snapshot/integ-ssmps-sharing-accepting.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ssm/test/integ.parameter-store-string-sharing.js.snapshot/integ-ssmps-sharing-accepting.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ssm/test/integ.parameter-store-string-sharing.js.snapshot/integ-ssmps-sharing-consuming.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ssm/test/integ.parameter-store-string-sharing.js.snapshot/integ-ssmps-sharing-consuming.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ssm/test/integ.parameter-store-string-sharing.js.snapshot/integ-ssmps-sharing-producing.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ssm/test/integ.parameter-store-string-sharing.js.snapshot/integ-ssmps-sharing-producing.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ssm/test/integ.parameter-store-string-sharing.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ssm/test/integ.parameter-store-string-sharing.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ssm/test/integ.parameter-store-string-sharing.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ssm/test/integ.parameter-store-string-sharing.ts
  packages/aws-cdk-lib/aws-ssm/README.md
  packages/aws-cdk-lib/aws-ssm/lib/parameter.ts
  packages/aws-cdk-lib/aws-ssm/test/parameter.test.ts
Labels: p2, feature-request, effort/medium, contribution/core

#31152 chore(s3): update default object ownership docstring
  packages/aws-cdk-lib/aws-s3/lib/bucket.ts
Labels: p2, contribution/core

#31154 chore(release): 2.153.0
  CHANGELOG.v2.alpha.md
  CHANGELOG.v2.md
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda/test/integ.lambda-recursive-loop.js.snapshot/LambdaRecursiveLoopTestDefaultTestDeployAssert68FA1353.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda/test/integ.lambda-recursive-loop.js.snapshot/LambdaRecursiveLoopTestDefaultTestDeployAssert68FA1353.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda/test/integ.lambda-recursive-loop.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda/test/integ.lambda-recursive-loop.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda/test/integ.lambda-recursive-loop.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda/test/integ.lambda-recursive-loop.js.snapshot/stack.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda/test/integ.lambda-recursive-loop.js.snapshot/stack.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda/test/integ.lambda-recursive-loop.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda/test/integ.lambda-recursive-loop.ts
  packages/aws-cdk-lib/aws-lambda/README.md
  packages/aws-cdk-lib/aws-lambda/lib/function.ts
  packages/aws-cdk-lib/aws-lambda/test/function.test.ts
  packages/aws-cdk-lib/awslint.json
  tools/@aws-cdk/spec2cdk/temporary-schemas/us-east-1/aws-lambda-function-recursive-loop.json
  version.v2.json
Labels: p2, contribution/core, pr/no-squash

#31150 feat(cloudfront): s3 origin access control
  packages/@aws-cdk-testing/framework-integ/test/aws-cloudfront-origins/test/integ.s3-origin-oac.js.snapshot/asset.3cef2cdbb46b3821e641ffb8b9af9731af5f7e4a9e857ab633dbcd9023de724d.bundle/index.js
  packages/@aws-cdk-testing/framework-integ/test/aws-cloudfront-origins/test/integ.s3-origin-oac.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-cloudfront-origins/test/integ.s3-origin-oac.js.snapshot/cloudfront-s3-origin-oac.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-cloudfront-origins/test/integ.s3-origin-oac.js.snapshot/cloudfront-s3-origin-oac.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-cloudfront-origins/test/integ.s3-origin-oac.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-cloudfront-origins/test/integ.s3-origin-oac.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-cloudfront-origins/test/integ.s3-origin-oac.js.snapshot/s3originoacDefaultTestDeployAssertD8FD270A.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-cloudfront-origins/test/integ.s3-origin-oac.js.snapshot/s3originoacDefaultTestDeployAssertD8FD270A.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-cloudfront-origins/test/integ.s3-origin-oac.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-cloudfront-origins/test/integ.s3-origin-oac.ts
  packages/@aws-cdk/custom-resource-handlers/package.json
  packages/aws-cdk-lib/aws-cloudfront-origins/README.md
  packages/aws-cdk-lib/aws-cloudfront-origins/lib/index.ts
  packages/aws-cdk-lib/aws-cloudfront-origins/lib/s3-bucket-origin.ts
  packages/aws-cdk-lib/aws-cloudfront-origins/lib/s3-origin.ts
  packages/aws-cdk-lib/aws-cloudfront-origins/lib/s3-static-website-origin.ts
  packages/aws-cdk-lib/aws-cloudfront/README.md
  packages/aws-cdk-lib/aws-cloudfront/lib/distribution.ts
  packages/aws-cdk-lib/aws-cloudfront/lib/index.ts
  packages/aws-cdk-lib/aws-cloudfront/lib/origin-access-control.ts
  packages/aws-cdk-lib/aws-cloudfront/lib/origin.ts
  packages/aws-cdk-lib/aws-cloudfront/lib/web-distribution.ts
  packages/aws-cdk-lib/aws-cloudfront/test/origin-access-control.test.ts
Labels: p2, contribution/core

#31157 chore(merge-back): 2.153.0
  CHANGELOG.v2.alpha.md
  CHANGELOG.v2.md
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda/test/integ.lambda-recursive-loop.js.snapshot/LambdaRecursiveLoopTestDefaultTestDeployAssert68FA1353.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda/test/integ.lambda-recursive-loop.js.snapshot/LambdaRecursiveLoopTestDefaultTestDeployAssert68FA1353.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda/test/integ.lambda-recursive-loop.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda/test/integ.lambda-recursive-loop.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda/test/integ.lambda-recursive-loop.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda/test/integ.lambda-recursive-loop.js.snapshot/stack.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda/test/integ.lambda-recursive-loop.js.snapshot/stack.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda/test/integ.lambda-recursive-loop.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda/test/integ.lambda-recursive-loop.ts
  packages/aws-cdk-lib/aws-lambda/README.md
  packages/aws-cdk-lib/aws-lambda/lib/function.ts
  packages/aws-cdk-lib/aws-lambda/test/function.test.ts
  packages/aws-cdk-lib/awslint.json
  tools/@aws-cdk/spec2cdk/temporary-schemas/us-east-1/aws-lambda-function-recursive-loop.json
  version.v2.json
Labels: p2, pr/needs-community-review, pr/no-squash, auto-approve

#31164 Adding first unit test for S3BucketOrigin
  packages/aws-cdk-lib/aws-cloudfront-origins/test/s3-bucket-origin.test.ts
Labels: p2, contribution/core

#31165 chore: add ashishdhingra to `contribution/core` label
  .mergify.yml
Labels: p2, contribution/core

#31159 fix(cli-lib-alpha): bootstrap fails with "bad argument name" error for trust and trustForLookup
  packages/@aws-cdk/cli-lib-alpha/lib/cli.ts
Labels: bug, p2, effort/small, contribution/core, pr-linter/exempt-test, pr-linter/exempt-integ-test

#31145 feat: update L1 CloudFormation resource definitions
  packages/@aws-cdk/cloudformation-diff/package.json
  packages/@aws-cdk/integ-runner/package.json
  packages/aws-cdk-lib/aws-lambda/lib/function-hash.ts
  packages/aws-cdk-lib/package.json
  tools/@aws-cdk/spec2cdk/package.json
  yarn.lock
Labels: p2, dependencies, contribution/core, pr-linter/exempt-readme, pr-linter/exempt-test, auto-approve, pr-linter/exempt-integ-test

#31001 fix(cloudfront): requirement of domainNames prevents moving a domain name between distributions
  packages/aws-cdk-lib/aws-cloudfront/README.md
  packages/aws-cdk-lib/aws-cloudfront/lib/distribution.ts
  packages/aws-cdk-lib/aws-cloudfront/test/distribution.test.ts
Labels: bug, p2, effort/medium, pr-linter/exempt-integ-test, admired-contributor

#31156 chore(lambda): add ca-west-1 for Cloudwatch Lambda Insight for x86_64 on available versions
  packages/aws-cdk-lib/region-info/build-tools/fact-tables.ts
  packages/aws-cdk-lib/region-info/test/__snapshots__/region-info.test.ts.snap
Labels: p2, contribution/core

#31177 chore(custom-resources): add `@experimental` decorator to `CustomResourceConfig`
  packages/aws-cdk-lib/custom-resources/lib/custom-resource-config/custom-resource-config.ts
Labels: p2, contribution/core

#31178 chore(release): 2.154.0
  CHANGELOG.v2.alpha.md
  CHANGELOG.v2.md
  packages/aws-cdk-lib/aws-cloudfront/README.md
  packages/aws-cdk-lib/aws-cloudfront/lib/distribution.ts
  packages/aws-cdk-lib/aws-cloudfront/test/distribution.test.ts
  packages/aws-cdk-lib/custom-resources/lib/custom-resource-config/custom-resource-config.ts
  packages/aws-cdk-lib/region-info/build-tools/fact-tables.ts
  packages/aws-cdk-lib/region-info/test/__snapshots__/region-info.test.ts.snap
Labels: p2, pr/no-squash, auto-approve

#31179 chore(merge-back): 2.154.0
  CHANGELOG.v2.alpha.md
  CHANGELOG.v2.md
  version.v2.json
Labels: p2, pr/no-squash, auto-approve

#31186 Unit test S3BucketOrigin.withOriginAccessControl with custom props + removed originAccessControlId from OriginBase
  packages/aws-cdk-lib/aws-cloudfront-origins/test/s3-bucket-origin.test.ts
  packages/aws-cdk-lib/aws-cloudfront/lib/origin.ts
Labels: p2, contribution/core

#31188 chore(cloudfront-origins): grant key permissions to distribution
  packages/aws-cdk-lib/aws-cloudfront-origins/lib/s3-bucket-origin.ts
  packages/aws-cdk-lib/aws-cloudfront-origins/test/s3-bucket-origin.test.ts
  packages/aws-cdk-lib/aws-cloudfront/lib/origin.ts
Labels: p2, contribution/core

#30140 feat(stepfunctions-tasks): add cpu and memory parameters to EcsRunTask
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/ecs/integ.fargate-run-task.js.snapshot/aws-sfn-tasks-ecs-fargate-run-task.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/ecs/integ.fargate-run-task.js.snapshot/aws-sfn-tasks-ecs-fargate-run-task.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/ecs/integ.fargate-run-task.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/ecs/integ.fargate-run-task.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/ecs/integ.fargate-run-task.ts
  packages/aws-cdk-lib/aws-stepfunctions-tasks/README.md
  packages/aws-cdk-lib/aws-stepfunctions-tasks/lib/ecs/run-task.ts
  packages/aws-cdk-lib/aws-stepfunctions-tasks/test/ecs/run-tasks.test.ts
Labels: p2, feature-request, effort/small, beginning-contributor, pr/needs-maintainer-review

#31193 feat: update L1 CloudFormation resource definitions
  packages/@aws-cdk/cloudformation-diff/package.json
  packages/@aws-cdk/integ-runner/package.json
  packages/aws-cdk-lib/package.json
  tools/@aws-cdk/spec2cdk/package.json
  yarn.lock
Labels: p2, dependencies, contribution/core, pr-linter/exempt-readme, pr-linter/exempt-test, auto-approve, pr-linter/exempt-integ-test, pr/needs-maintainer-review

#31194 feat: update L1 CloudFormation resource definitions
  packages/@aws-cdk/cloudformation-diff/package.json
  packages/@aws-cdk/integ-runner/package.json
  packages/aws-cdk-lib/package.json
  tools/@aws-cdk/spec2cdk/package.json
  yarn.lock
Labels: p2, dependencies, contribution/core, pr-linter/exempt-readme, pr-linter/exempt-test, auto-approve, pr-linter/exempt-integ-test

#31195 chore(release): v2.154.1
  CHANGELOG.v2.alpha.md
  CHANGELOG.v2.md
  packages/@aws-cdk/cloudformation-diff/package.json
  packages/@aws-cdk/integ-runner/package.json
  packages/aws-cdk-lib/package.json
  tools/@aws-cdk/spec2cdk/package.json
  version.v2.json
  yarn.lock
Labels: p2, contribution/core, pr/no-squash

#31197 chore(merge-back): 2.154.1
  CHANGELOG.v2.alpha.md
  CHANGELOG.v2.md
  version.v2.json
Labels: p2, pr/needs-community-review, pr/no-squash, auto-approve

#31190 Unit test for S3BucketOrigin.withOriginAccessIdentity
  packages/aws-cdk-lib/aws-cloudfront-origins/lib/s3-bucket-origin.ts
  packages/aws-cdk-lib/aws-cloudfront-origins/test/s3-bucket-origin.test.ts
Labels: p2, contribution/core

#31191 chore(vpcv2): adding rosetta for ReadMe
  packages/@aws-cdk/aws-ec2-alpha/README.md
  packages/@aws-cdk/aws-ec2-alpha/rosetta/default.ts-fixture
Labels: p2, contribution/core

#31203 feat(codebuild): macOS codebuild support
  packages/@aws-cdk-testing/framework-integ/test/aws-codebuild/test/integ.project-macos-fleet.js.snapshot/MacOsProjectIntegTestDefaultTestDeployAssertB425ECC4.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-codebuild/test/integ.project-macos-fleet.js.snapshot/MacOsProjectIntegTestDefaultTestDeployAssertB425ECC4.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-codebuild/test/integ.project-macos-fleet.js.snapshot/asset.eafc02f6925151c95ac6a6ae81a3e36d4cf4e77db52eec8e467ce2a69454a41a.bundle/index.js
  packages/@aws-cdk-testing/framework-integ/test/aws-codebuild/test/integ.project-macos-fleet.js.snapshot/aws-cdk-project-macos.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-codebuild/test/integ.project-macos-fleet.js.snapshot/aws-cdk-project-macos.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-codebuild/test/integ.project-macos-fleet.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-codebuild/test/integ.project-macos-fleet.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-codebuild/test/integ.project-macos-fleet.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-codebuild/test/integ.project-macos-fleet.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-codebuild/test/integ.project-macos-fleet.ts
  packages/aws-cdk-lib/aws-codebuild/README.md
  packages/aws-cdk-lib/aws-codebuild/lib/environment-type.ts
  packages/aws-cdk-lib/aws-codebuild/lib/project.ts
  packages/aws-cdk-lib/aws-codebuild/test/project.test.ts
Labels: p2, feature-request, effort/medium, beginning-contributor

#31221 feat: update L1 CloudFormation resource definitions
  packages/@aws-cdk/cloudformation-diff/package.json
  packages/@aws-cdk/integ-runner/package.json
  packages/aws-cdk-lib/package.json
  tools/@aws-cdk/spec2cdk/package.json
  yarn.lock
Labels: p2, dependencies, contribution/core, pr-linter/exempt-readme, pr-linter/exempt-test, auto-approve, pr-linter/exempt-integ-test

#31131 chore(CLI-integ-tests): cli integ tests cannot use local CDK framework
  packages/@aws-cdk-testing/cli-integ/lib/package-sources/repo-source.ts
  packages/@aws-cdk-testing/cli-integ/lib/with-cdk-app.ts
Labels: p2, contribution/core, pr-linter/cli-integ-tested

#31101 feat(synthetics): add syn-python-selenium-4.0 runtime
  packages/@aws-cdk-testing/framework-integ/test/aws-synthetics/test/integ.canary.js.snapshot/IntegCanaryTestDefaultTestDeployAssert3AD5A094.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-synthetics/test/integ.canary.js.snapshot/IntegCanaryTestDefaultTestDeployAssert3AD5A094.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-synthetics/test/integ.canary.js.snapshot/canary-one.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-synthetics/test/integ.canary.js.snapshot/canary-one.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-synthetics/test/integ.canary.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-synthetics/test/integ.canary.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-synthetics/test/integ.canary.ts
  packages/aws-cdk-lib/aws-synthetics/lib/runtime.ts
  packages/aws-cdk-lib/aws-synthetics/test/canary.test.ts
Labels: p2, feature-request, effort/small, pr-linter/exempt-readme, distinguished-contributor, pr-linter/exemption-requested

#31091 fix(s3): bucket notifications in owning stack deletes bucket notifications from other stacks
  packages/aws-cdk-lib/aws-s3/lib/notifications-resource/notifications-resource.ts
  packages/aws-cdk-lib/aws-s3/test/notification.test.ts
  packages/aws-cdk-lib/cx-api/FEATURE_FLAGS.md
  packages/aws-cdk-lib/cx-api/lib/features.ts
  packages/aws-cdk-lib/cx-api/test/features.test.ts
Labels: bug, p1, effort/medium, contribution/core, pr-linter/exempt-integ-test

#31076 feat(ec2): `ipv6AddressCount` property for an instance
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.instance-ipv6-address-count.js.snapshot/InstanceIpv6AddressCountTestStack.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.instance-ipv6-address-count.js.snapshot/InstanceIpv6AddressCountTestStack.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.instance-ipv6-address-count.js.snapshot/IntegTestDefaultTestDeployAssertE3E7D2A4.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.instance-ipv6-address-count.js.snapshot/IntegTestDefaultTestDeployAssertE3E7D2A4.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.instance-ipv6-address-count.js.snapshot/asset.bde7b5c89cb43285f884c94f0b9e17cdb0f5eb5345005114dd60342e0b8a85a1/__entrypoint__.js
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.instance-ipv6-address-count.js.snapshot/asset.bde7b5c89cb43285f884c94f0b9e17cdb0f5eb5345005114dd60342e0b8a85a1/index.js
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.instance-ipv6-address-count.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.instance-ipv6-address-count.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.instance-ipv6-address-count.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.instance-ipv6-address-count.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.instance-ipv6-address-count.ts
  packages/aws-cdk-lib/aws-ec2/README.md
  packages/aws-cdk-lib/aws-ec2/lib/instance.ts
  packages/aws-cdk-lib/aws-ec2/test/instance.test.ts
Labels: p2, feature-request, distinguished-contributor

#31011 fix(lambda-event-source): allow dynamodb filtering on boolean value
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-event-sources/test/integ.dynamodb-with-boolean-filter.js.snapshot/DynamoDBFilterBooleanDefaultTestDeployAssert8561382F.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-event-sources/test/integ.dynamodb-with-boolean-filter.js.snapshot/DynamoDBFilterBooleanDefaultTestDeployAssert8561382F.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-event-sources/test/integ.dynamodb-with-boolean-filter.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-event-sources/test/integ.dynamodb-with-boolean-filter.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-event-sources/test/integ.dynamodb-with-boolean-filter.js.snapshot/lambda-event-source-filter-boolean-dynamodb.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-event-sources/test/integ.dynamodb-with-boolean-filter.js.snapshot/lambda-event-source-filter-boolean-dynamodb.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-event-sources/test/integ.dynamodb-with-boolean-filter.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-event-sources/test/integ.dynamodb-with-boolean-filter.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-event-sources/test/integ.dynamodb-with-boolean-filter.ts
  packages/aws-cdk-lib/aws-lambda-event-sources/README.md
  packages/aws-cdk-lib/aws-lambda-event-sources/test/dynamo.test.ts
  packages/aws-cdk-lib/aws-lambda/lib/event-source-filter.ts
Labels: bug, p2, effort/small, beginning-contributor

#31125 feat(kms): add `multiRegion` property to a `Key`
  packages/@aws-cdk-testing/framework-integ/test/aws-kms/test/integ.key-multi-region.js.snapshot/KmsKeyMultiRegionStack.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-kms/test/integ.key-multi-region.js.snapshot/KmsKeyMultiRegionStack.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-kms/test/integ.key-multi-region.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-kms/test/integ.key-multi-region.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-kms/test/integ.key-multi-region.js.snapshot/kmskeymultiregionDefaultTestDeployAssert5D62E49E.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-kms/test/integ.key-multi-region.js.snapshot/kmskeymultiregionDefaultTestDeployAssert5D62E49E.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-kms/test/integ.key-multi-region.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-kms/test/integ.key-multi-region.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-kms/test/integ.key-multi-region.ts
  packages/aws-cdk-lib/aws-kms/README.md
  packages/aws-cdk-lib/aws-kms/lib/key.ts
  packages/aws-cdk-lib/aws-kms/test/key.test.ts
Labels: p2, beginning-contributor

#31235 chore: format expected output
  packages/@aws-cdk-testing/cli-integ/package.json
  packages/@aws-cdk-testing/cli-integ/tests/cli-integ-tests/cli.integtest.ts
Labels: p2, contribution/core

#31053 chore(doc): improve the doc on DockerImageFunction for cross-platform bundling
  packages/aws-cdk-lib/aws-lambda/README.md
Labels: bug, p2, effort/small, contribution/core

#31225 add unit test for oac permission levels
  packages/aws-cdk-lib/aws-cloudfront-origins/lib/s3-bucket-origin.ts
  packages/aws-cdk-lib/aws-cloudfront-origins/test/s3-bucket-origin.test.ts
Labels: p2, contribution/core

#31233 chore(rds): support 11.22-rds.20240808 for RDS PostgreSQL
  packages/aws-cdk-lib/aws-rds/lib/instance-engine.ts
Labels: p2, distinguished-contributor

#30711 feat(location): support GeofenceCollection
  packages/@aws-cdk/aws-location-alpha/README.md
  packages/@aws-cdk/aws-location-alpha/lib/geofence-collection.ts
  packages/@aws-cdk/aws-location-alpha/lib/index.ts
  packages/@aws-cdk/aws-location-alpha/lib/place-index.ts
  packages/@aws-cdk/aws-location-alpha/lib/util.ts
  packages/@aws-cdk/aws-location-alpha/rosetta/default.ts-fixture
  packages/@aws-cdk/aws-location-alpha/test/geofence-collection.test.ts
  packages/@aws-cdk/aws-location-alpha/test/integ.geofence-collection.js.snapshot/GeofenceCollectionTestDefaultTestDeployAssert44609017.assets.json
  packages/@aws-cdk/aws-location-alpha/test/integ.geofence-collection.js.snapshot/GeofenceCollectionTestDefaultTestDeployAssert44609017.template.json
  packages/@aws-cdk/aws-location-alpha/test/integ.geofence-collection.js.snapshot/cdk-integ-location-geofence-collection.assets.json
  packages/@aws-cdk/aws-location-alpha/test/integ.geofence-collection.js.snapshot/cdk-integ-location-geofence-collection.template.json
  packages/@aws-cdk/aws-location-alpha/test/integ.geofence-collection.js.snapshot/cdk.out
  packages/@aws-cdk/aws-location-alpha/test/integ.geofence-collection.js.snapshot/integ.json
  packages/@aws-cdk/aws-location-alpha/test/integ.geofence-collection.js.snapshot/manifest.json
  packages/@aws-cdk/aws-location-alpha/test/integ.geofence-collection.js.snapshot/tree.json
  packages/@aws-cdk/aws-location-alpha/test/integ.geofence-collection.ts
Labels: p2, feature-request, effort/medium, star-contributor

#31247 add section to README on migrating from OAI to OAC
  packages/aws-cdk-lib/aws-cloudfront-origins/README.md
  packages/aws-cdk-lib/aws-cloudfront-origins/lib/s3-bucket-origin.ts
  packages/aws-cdk-lib/aws-cloudfront-origins/test/s3-bucket-origin.test.ts
  packages/aws-cdk-lib/aws-cloudfront/lib/origin-access-control.ts
Labels: p2, contribution/core

#31251 chore(cloudfront): add validation for length of comment in cache policy
  packages/aws-cdk-lib/aws-cloudfront/lib/cache-policy.ts
  packages/aws-cdk-lib/aws-cloudfront/test/cache-policy.test.ts
Labels: bug, p2, distinguished-contributor

#31256 Liniting fixes
  packages/@aws-cdk-testing/framework-integ/test/aws-cloudfront-origins/test/integ.s3-bucket-origin-default.ts
  packages/@aws-cdk-testing/framework-integ/test/aws-cloudfront-origins/test/integ.s3-bucket-origin-oai.ts
  packages/@aws-cdk-testing/framework-integ/test/aws-cloudfront-origins/test/integ.s3-static-website-origin.ts
  packages/aws-cdk-lib/aws-cloudfront-origins/test/s3-bucket-origin.test.ts
Labels: p2

#31214 feat(codebuild): support three arm-based compute types, Medium, X-Large and 2X-Large
  packages/@aws-cdk-testing/framework-integ/test/aws-codebuild/test/integ.project-linux-arm.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-codebuild/test/integ.project-linux-arm.js.snapshot/codebuild-project-arm.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-codebuild/test/integ.project-linux-arm.js.snapshot/codebuild-project-arm.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-codebuild/test/integ.project-linux-arm.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-codebuild/test/integ.project-linux-arm.js.snapshot/integtestcodebuildprojectarmDefaultTestDeployAssert4EE92337.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-codebuild/test/integ.project-linux-arm.js.snapshot/integtestcodebuildprojectarmDefaultTestDeployAssert4EE92337.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-codebuild/test/integ.project-linux-arm.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-codebuild/test/integ.project-linux-arm.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-codebuild/test/integ.project-linux-arm.ts
  packages/aws-cdk-lib/aws-codebuild/lib/linux-arm-build-image.ts
  packages/aws-cdk-lib/aws-codebuild/test/codebuild.test.ts
  packages/aws-cdk-lib/aws-codebuild/test/linux-arm-build-image.test.ts
Labels: bug, p2, pr-linter/exempt-readme, distinguished-contributor

#31226 chore: update cli integ tests to use sdk v3
  packages/@aws-cdk-testing/cli-integ/lib/aws.ts
  packages/@aws-cdk-testing/cli-integ/lib/staging/codeartifact.ts
  packages/@aws-cdk-testing/cli-integ/lib/with-cdk-app.ts
  packages/@aws-cdk-testing/cli-integ/package.json
  packages/@aws-cdk-testing/cli-integ/tests/cli-integ-tests/bootstrapping.integtest.ts
  packages/@aws-cdk-testing/cli-integ/tests/cli-integ-tests/cli-lib.integtest.ts
  packages/@aws-cdk-testing/cli-integ/tests/cli-integ-tests/cli.integtest.ts
  yarn.lock
Labels: p2, contribution/core

#30682 feat(location): support RouteCalculator
  packages/@aws-cdk/aws-location-alpha/README.md
  packages/@aws-cdk/aws-location-alpha/lib/index.ts
  packages/@aws-cdk/aws-location-alpha/lib/place-index.ts
  packages/@aws-cdk/aws-location-alpha/lib/route-calculator.ts
  packages/@aws-cdk/aws-location-alpha/lib/util.ts
  packages/@aws-cdk/aws-location-alpha/test/integ.route-calculator.js.snapshot/RouteCalculatorTestDefaultTestDeployAssert5893D6F4.assets.json
  packages/@aws-cdk/aws-location-alpha/test/integ.route-calculator.js.snapshot/RouteCalculatorTestDefaultTestDeployAssert5893D6F4.template.json
  packages/@aws-cdk/aws-location-alpha/test/integ.route-calculator.js.snapshot/cdk-integ-location-route-calculator.assets.json
  packages/@aws-cdk/aws-location-alpha/test/integ.route-calculator.js.snapshot/cdk-integ-location-route-calculator.template.json
  packages/@aws-cdk/aws-location-alpha/test/integ.route-calculator.js.snapshot/cdk.out
  packages/@aws-cdk/aws-location-alpha/test/integ.route-calculator.js.snapshot/integ.json
  packages/@aws-cdk/aws-location-alpha/test/integ.route-calculator.js.snapshot/manifest.json
  packages/@aws-cdk/aws-location-alpha/test/integ.route-calculator.js.snapshot/tree.json
  packages/@aws-cdk/aws-location-alpha/test/integ.route-calculator.ts
  packages/@aws-cdk/aws-location-alpha/test/place-index.test.ts
  packages/@aws-cdk/aws-location-alpha/test/route-calculator.test.ts
Labels: p2, feature-request, star-contributor

#31263 chore(merge-back): 2.155.0
  CHANGELOG.v2.alpha.md
  CHANGELOG.v2.md
  packages/aws-cdk-lib/cx-api/FEATURE_FLAGS.md
  packages/aws-cdk-lib/cx-api/lib/features.ts
  version.v2.json
Labels: p2, pr/needs-community-review, pr/no-squash, auto-approve

#31262 add README section for sse-kms circular dependency workaround
  packages/aws-cdk-lib/aws-cloudfront-origins/README.md
  packages/aws-cdk-lib/aws-cloudfront-origins/lib/s3-bucket-origin.ts
  packages/aws-cdk-lib/aws-cloudfront-origins/test/s3-bucket-origin.test.ts
  packages/aws-cdk-lib/aws-cloudfront/README.md
Labels: p2, contribution/core

#29462 feat(events-targets): support for `RedshiftDataParameters`
  packages/@aws-cdk-testing/framework-integ/test/aws-events-targets/test/redshift-query/integ.redshift-query.js.snapshot/LogGroupDefaultTestDeployAssert353EE07A.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-events-targets/test/redshift-query/integ.redshift-query.js.snapshot/LogGroupDefaultTestDeployAssert353EE07A.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-events-targets/test/redshift-query/integ.redshift-query.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-events-targets/test/redshift-query/integ.redshift-query.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-events-targets/test/redshift-query/integ.redshift-query.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-events-targets/test/redshift-query/integ.redshift-query.js.snapshot/redshift-query-events.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-events-targets/test/redshift-query/integ.redshift-query.js.snapshot/redshift-query-events.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-events-targets/test/redshift-query/integ.redshift-query.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-events-targets/test/redshift-query/integ.redshift-query.ts
  packages/aws-cdk-lib/aws-events-targets/README.md
  packages/aws-cdk-lib/aws-events-targets/lib/index.ts
  packages/aws-cdk-lib/aws-events-targets/lib/redshift-query.ts
  packages/aws-cdk-lib/aws-events-targets/test/redshift-query/redshift-query.test.ts
  packages/aws-cdk-lib/aws-events/lib/rule.ts
  packages/aws-cdk-lib/aws-events/lib/target.ts
  packages/aws-cdk-lib/aws-events/test/rule.test.ts
Labels: p1, feature-request, effort/medium, valued-contributor, pr/needs-maintainer-review

#31260 chore(rds): support 5.7.44-rds.20240808 for RDS for MySQL
  packages/aws-cdk-lib/aws-rds/lib/instance-engine.ts
Labels: p2, distinguished-contributor
