Repository aws/aws-cdk, pull requests merged in 2024-09, with the labels that each got.

#31277 chore: update Contributors File
  CONTRIBUTORS.md
Labels: p2, auto-approve

#31276 fix(scheduler): the value of the description property is not reflected to the resource.
  packages/@aws-cdk/aws-scheduler-alpha/lib/schedule.ts
  packages/@aws-cdk/aws-scheduler-alpha/test/integ.schedule.js.snapshot/aws-cdk-scheduler-schedule.assets.json
  packages/@aws-cdk/aws-scheduler-alpha/test/integ.schedule.js.snapshot/aws-cdk-scheduler-schedule.template.json
  packages/@aws-cdk/aws-scheduler-alpha/test/integ.schedule.js.snapshot/cdk.out
  packages/@aws-cdk/aws-scheduler-alpha/test/integ.schedule.js.snapshot/integ.json
  packages/@aws-cdk/aws-scheduler-alpha/test/integ.schedule.js.snapshot/integtestscheduleDefaultTestDeployAssert24CB3896.assets.json
  packages/@aws-cdk/aws-scheduler-alpha/test/integ.schedule.js.snapshot/manifest.json
  packages/@aws-cdk/aws-scheduler-alpha/test/integ.schedule.js.snapshot/tree.json
  packages/@aws-cdk/aws-scheduler-alpha/test/integ.schedule.ts
  packages/@aws-cdk/aws-scheduler-alpha/test/schedule.test.ts
Labels: bug, p2, effort/small, distinguished-contributor

#31295 docs(prlint): fix wrong path in sample commands
  tools/@aws-cdk/prlint/README.md
Labels: p2, distinguished-contributor

#31210 fix(stepfunctions-tasks): sageMakerCreateTrainingJob does not correctly support empty inputDataConfig
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/sagemaker/integ.create-training-job.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/sagemaker/integ.create-training-job.js.snapshot/integ-stepfunctions-sagemaker.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/sagemaker/integ.create-training-job.js.snapshot/integ-stepfunctions-sagemaker.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/sagemaker/integ.create-training-job.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/sagemaker/integ.create-training-job.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/sagemaker/integ.create-training-job.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/sagemaker/integ.create-training-job.ts
  packages/aws-cdk-lib/aws-stepfunctions-tasks/lib/sagemaker/create-training-job.ts
  packages/aws-cdk-lib/aws-stepfunctions-tasks/test/sagemaker/create-training-job.test.ts
Labels: bug, p1, effort/medium, contribution/core

#31292 docs: fix invalid anchor links in DESIGN_GUIDELINES
  docs/DESIGN_GUIDELINES.md
Labels: p2, distinguished-contributor

#31290 fix(prlint): a review label doesn't appear when a PR is approved if there are too many comments
  tools/@aws-cdk/prlint/lint.ts
Labels: bug, p2, pr-linter/exempt-test, pr-linter/exempt-integ-test, distinguished-contributor

#31274 chore: save the logs
  packages/aws-cdk/lib/init.ts
  packages/aws-cdk/test/api/hotswap/appsync-mapping-templates-hotswap-deployments.test.ts
  packages/aws-cdk/test/api/hotswap/code-build-projects-hotswap-deployments.test.ts
  packages/aws-cdk/test/api/hotswap/ecs-services-hotswap-deployments.test.ts
  packages/aws-cdk/test/api/hotswap/hotswap-deployments.test.ts
  packages/aws-cdk/test/api/hotswap/hotswap-test-setup.ts
  packages/aws-cdk/test/api/hotswap/iam-policy-hotswap-deployment.test.ts
  packages/aws-cdk/test/api/hotswap/lambda-functions-docker-hotswap-deployments.test.ts
  packages/aws-cdk/test/api/hotswap/lambda-functions-hotswap-deployments.test.ts
  packages/aws-cdk/test/api/hotswap/lambda-functions-inline-hotswap-deployments.test.ts
  packages/aws-cdk/test/api/hotswap/lambda-versions-aliases-hotswap-deployments.test.ts
  packages/aws-cdk/test/api/hotswap/nested-stacks-hotswap.test.ts
  packages/aws-cdk/test/api/hotswap/s3-bucket-hotswap-deployments.test.ts
  packages/aws-cdk/test/api/hotswap/state-machine-hotswap-deployments.test.ts
  packages/aws-cdk/test/util/silent.ts
Labels: p2, contribution/core, pr-linter/cli-integ-tested

#31308 revert(stepfunctions-tasks): "feat(stepfunctions-tasks): allow BedrockInvokeModel to use JsonPath"
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/bedrock/integ.invoke-model.js.snapshot/InvokeModelDefaultTestDeployAssert9C0D2DFC.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/bedrock/integ.invoke-model.js.snapshot/aws-stepfunctions-tasks-bedrock-invoke-model-integ.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/bedrock/integ.invoke-model.js.snapshot/aws-stepfunctions-tasks-bedrock-invoke-model-integ.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/bedrock/integ.invoke-model.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/bedrock/integ.invoke-model.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/bedrock/integ.invoke-model.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/bedrock/integ.invoke-model.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/bedrock/integ.invoke-model.ts
  packages/aws-cdk-lib/aws-stepfunctions-tasks/README.md
  packages/aws-cdk-lib/aws-stepfunctions-tasks/lib/bedrock/invoke-model.ts
  packages/aws-cdk-lib/aws-stepfunctions-tasks/test/bedrock/invoke-model.test.ts
Labels: bug, p0, contribution/core, pr-linter/exempt-breaking-change

#31309 chore(release): 2.155.1
  CHANGELOG.v2.alpha.md
  CHANGELOG.v2.md
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/bedrock/integ.invoke-model.js.snapshot/InvokeModelDefaultTestDeployAssert9C0D2DFC.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/bedrock/integ.invoke-model.js.snapshot/aws-stepfunctions-tasks-bedrock-invoke-model-integ.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/bedrock/integ.invoke-model.js.snapshot/aws-stepfunctions-tasks-bedrock-invoke-model-integ.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/bedrock/integ.invoke-model.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/bedrock/integ.invoke-model.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/bedrock/integ.invoke-model.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/bedrock/integ.invoke-model.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/bedrock/integ.invoke-model.ts
  packages/aws-cdk-lib/aws-stepfunctions-tasks/README.md
  packages/aws-cdk-lib/aws-stepfunctions-tasks/lib/bedrock/invoke-model.ts
  packages/aws-cdk-lib/aws-stepfunctions-tasks/test/bedrock/invoke-model.test.ts
  version.v2.json
Labels: p2, contribution/core, pr/no-squash

#31307 docs: update note on downtime during migration
  packages/aws-cdk-lib/aws-cloudfront-origins/README.md
Labels: p2, contribution/core

#31311 chore(doc): update ROADMAP.md
  ROADMAP.md
Labels: p2, beginning-contributor

#31275 chore: remove uses of aws-sdk outside cli
  packages/@aws-cdk-testing/framework-integ/package.json
  packages/@aws-cdk/custom-resource-handlers/package.json
  packages/aws-cdk-lib/aws-events-targets/lib/aws-api.ts
  packages/aws-cdk-lib/aws-events-targets/test/aws-api/aws-api.test.ts
  packages/aws-cdk-lib/package.json
  packages/aws-cdk-lib/scripts/submodules/aws-events-targets.ts
  packages/aws-cdk-lib/scripts/submodules/index.ts
  yarn.lock
Labels: p2, contribution/core

#31301 docs(cloudfront): updates to CloudFront ResponseHeadersPolicy XSSProtection
  packages/aws-cdk-lib/aws-cloudfront/README.md
  packages/aws-cdk-lib/aws-cloudfront/test/response-headers-policy.test.ts
Labels: bug, p2, effort/small, pr/needs-community-review, repeat-contributor

#31272 feat(synthetics): syn-nodejs-puppeteer-9.0 as supported runtime
  packages/aws-cdk-lib/aws-synthetics/lib/runtime.ts
Labels: p2, feature-request, contribution/core, pr-linter/exempt-readme, pr-linter/exempt-test, pr-linter/exempt-integ-test

#31200 feat(scheduler): validate schedule name length
  packages/@aws-cdk/aws-scheduler-alpha/lib/schedule.ts
  packages/@aws-cdk/aws-scheduler-alpha/test/schedule.test.ts
Labels: p2, pr-linter/exempt-readme, pr-linter/exempt-integ-test, beginning-contributor

#31321 Update S3BucketOrigin.withOriginAccessControl class methods to be private
  packages/aws-cdk-lib/aws-cloudfront-origins/lib/s3-bucket-origin.ts
Labels: p2, contribution/core

#30208 docs(elasticloadbalancingv2): update confusing AddNetworkTargets port description
  packages/aws-cdk-lib/aws-elasticloadbalancingv2/lib/nlb/network-listener.ts
Labels: p2, beginning-contributor

#30163 feat(docdb): i/o optimized storage type
  packages/@aws-cdk-testing/framework-integ/test/aws-docdb/test/integ.cluster-storage-type.js.snapshot/StorageTypeClusterTestDefaultTestDeployAssert1804B4F9.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-docdb/test/integ.cluster-storage-type.js.snapshot/StorageTypeClusterTestDefaultTestDeployAssert1804B4F9.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-docdb/test/integ.cluster-storage-type.js.snapshot/StorageTypeClusterTestStack.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-docdb/test/integ.cluster-storage-type.js.snapshot/StorageTypeClusterTestStack.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-docdb/test/integ.cluster-storage-type.js.snapshot/asset.bde7b5c89cb43285f884c94f0b9e17cdb0f5eb5345005114dd60342e0b8a85a1/__entrypoint__.js
  packages/@aws-cdk-testing/framework-integ/test/aws-docdb/test/integ.cluster-storage-type.js.snapshot/asset.bde7b5c89cb43285f884c94f0b9e17cdb0f5eb5345005114dd60342e0b8a85a1/index.js
  packages/@aws-cdk-testing/framework-integ/test/aws-docdb/test/integ.cluster-storage-type.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-docdb/test/integ.cluster-storage-type.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-docdb/test/integ.cluster-storage-type.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-docdb/test/integ.cluster-storage-type.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-docdb/test/integ.cluster-storage-type.ts
  packages/aws-cdk-lib/aws-docdb/README.md
  packages/aws-cdk-lib/aws-docdb/lib/cluster.ts
  packages/aws-cdk-lib/aws-docdb/test/cluster.test.ts
Labels: p2, feature-request, star-contributor

#31137 feat(neptune-alpha): specify port for the cluster
  packages/@aws-cdk/aws-neptune-alpha/README.md
  packages/@aws-cdk/aws-neptune-alpha/lib/cluster.ts
  packages/@aws-cdk/aws-neptune-alpha/test/cluster.test.ts
  packages/@aws-cdk/aws-neptune-alpha/test/integ.cluster-port.js.snapshot/NeptuneClusterPortTestDefaultTestDeployAssert7A0847B4.assets.json
  packages/@aws-cdk/aws-neptune-alpha/test/integ.cluster-port.js.snapshot/NeptuneClusterPortTestDefaultTestDeployAssert7A0847B4.template.json
  packages/@aws-cdk/aws-neptune-alpha/test/integ.cluster-port.js.snapshot/NeptuneClusterPortTestStack.assets.json
  packages/@aws-cdk/aws-neptune-alpha/test/integ.cluster-port.js.snapshot/NeptuneClusterPortTestStack.template.json
  packages/@aws-cdk/aws-neptune-alpha/test/integ.cluster-port.js.snapshot/asset.bde7b5c89cb43285f884c94f0b9e17cdb0f5eb5345005114dd60342e0b8a85a1/__entrypoint__.js
  packages/@aws-cdk/aws-neptune-alpha/test/integ.cluster-port.js.snapshot/asset.bde7b5c89cb43285f884c94f0b9e17cdb0f5eb5345005114dd60342e0b8a85a1/index.js
  packages/@aws-cdk/aws-neptune-alpha/test/integ.cluster-port.js.snapshot/cdk.out
  packages/@aws-cdk/aws-neptune-alpha/test/integ.cluster-port.js.snapshot/integ.json
  packages/@aws-cdk/aws-neptune-alpha/test/integ.cluster-port.js.snapshot/manifest.json
  packages/@aws-cdk/aws-neptune-alpha/test/integ.cluster-port.js.snapshot/tree.json
  packages/@aws-cdk/aws-neptune-alpha/test/integ.cluster-port.ts
Labels: p2, feature-request, effort/small, distinguished-contributor

#31250 chore: add option unacknowledged to cdk notices
  packages/@aws-cdk-testing/cli-integ/tests/cli-integ-tests/cli.integtest.ts
  packages/aws-cdk/README.md
  packages/aws-cdk/lib/cli.ts
  packages/aws-cdk/lib/notices.ts
  packages/aws-cdk/test/notices.test.ts
Labels: p2, feature-request, effort/small, repeat-contributor, pr-linter/cli-integ-tested

#31206 chore(kinesisfirehose-alpha): add ca-west-1 Firehose CIDR block
  packages/@aws-cdk/aws-iot-actions-alpha/test/kinesis-firehose/integ.firehose-put-record-action.js.snapshot/cdk.out
  packages/@aws-cdk/aws-iot-actions-alpha/test/kinesis-firehose/integ.firehose-put-record-action.js.snapshot/integ.json
  packages/@aws-cdk/aws-iot-actions-alpha/test/kinesis-firehose/integ.firehose-put-record-action.js.snapshot/manifest.json
  packages/@aws-cdk/aws-iot-actions-alpha/test/kinesis-firehose/integ.firehose-put-record-action.js.snapshot/test-stack.assets.json
  packages/@aws-cdk/aws-iot-actions-alpha/test/kinesis-firehose/integ.firehose-put-record-action.js.snapshot/test-stack.template.json
  packages/@aws-cdk/aws-iot-actions-alpha/test/kinesis-firehose/integ.firehose-put-record-action.js.snapshot/tree.json
  packages/@aws-cdk/aws-kinesisfirehose-alpha/test/integ.delivery-stream.js.snapshot/aws-cdk-firehose-delivery-stream.assets.json
  packages/@aws-cdk/aws-kinesisfirehose-alpha/test/integ.delivery-stream.js.snapshot/aws-cdk-firehose-delivery-stream.template.json
  packages/@aws-cdk/aws-kinesisfirehose-alpha/test/integ.delivery-stream.js.snapshot/cdk.out
  packages/@aws-cdk/aws-kinesisfirehose-alpha/test/integ.delivery-stream.js.snapshot/integ.json
  packages/@aws-cdk/aws-kinesisfirehose-alpha/test/integ.delivery-stream.js.snapshot/manifest.json
  packages/@aws-cdk/aws-kinesisfirehose-alpha/test/integ.delivery-stream.js.snapshot/tree.json
  packages/@aws-cdk/aws-kinesisfirehose-alpha/test/integ.delivery-stream.source-stream.js.snapshot/aws-cdk-firehose-delivery-stream-source-stream.assets.json
  packages/@aws-cdk/aws-kinesisfirehose-alpha/test/integ.delivery-stream.source-stream.js.snapshot/aws-cdk-firehose-delivery-stream-source-stream.template.json
  packages/@aws-cdk/aws-kinesisfirehose-alpha/test/integ.delivery-stream.source-stream.js.snapshot/cdk.out
  packages/@aws-cdk/aws-kinesisfirehose-alpha/test/integ.delivery-stream.source-stream.js.snapshot/integ.json
  packages/@aws-cdk/aws-kinesisfirehose-alpha/test/integ.delivery-stream.source-stream.js.snapshot/manifest.json
  packages/@aws-cdk/aws-kinesisfirehose-alpha/test/integ.kinesis-stream-events-target.js.snapshot/aws-cdk-firehose-delivery-stream.assets.json
  packages/@aws-cdk/aws-kinesisfirehose-alpha/test/integ.kinesis-stream-events-target.js.snapshot/aws-cdk-firehose-delivery-stream.template.json
  packages/@aws-cdk/aws-kinesisfirehose-alpha/test/integ.kinesis-stream-events-target.js.snapshot/cdk.out
  packages/@aws-cdk/aws-kinesisfirehose-alpha/test/integ.kinesis-stream-events-target.js.snapshot/integ.json
  packages/@aws-cdk/aws-kinesisfirehose-alpha/test/integ.kinesis-stream-events-target.js.snapshot/integtestsDefaultTestDeployAssert44C8D370.assets.json
  packages/@aws-cdk/aws-kinesisfirehose-alpha/test/integ.kinesis-stream-events-target.js.snapshot/manifest.json
  packages/@aws-cdk/aws-kinesisfirehose-destinations-alpha/test/integ.s3-bucket.lit.js.snapshot/aws-cdk-firehose-delivery-stream-s3-all-properties.assets.json
  packages/@aws-cdk/aws-kinesisfirehose-destinations-alpha/test/integ.s3-bucket.lit.js.snapshot/aws-cdk-firehose-delivery-stream-s3-all-properties.template.json
  packages/@aws-cdk/aws-kinesisfirehose-destinations-alpha/test/integ.s3-bucket.lit.js.snapshot/cdk.out
  packages/@aws-cdk/aws-kinesisfirehose-destinations-alpha/test/integ.s3-bucket.lit.js.snapshot/integ.json
  packages/@aws-cdk/aws-kinesisfirehose-destinations-alpha/test/integ.s3-bucket.lit.js.snapshot/manifest.json
  packages/aws-cdk-lib/region-info/build-tools/fact-tables.ts
Labels: bug, p2, effort/small, contribution/core

#31316 chore(vpcv2): set repo to private false in package json
  packages/@aws-cdk/aws-ec2-alpha/.npmignore
  packages/@aws-cdk/aws-ec2-alpha/README.md
  packages/@aws-cdk/aws-ec2-alpha/package.json
Labels: p2, contribution/core

#31325 fix(stepfunctions-tasks): add back BedrockInvokeModel to use JsonPath
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/bedrock/integ.invoke-model.js.snapshot/InvokeModelDefaultTestDeployAssert9C0D2DFC.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/bedrock/integ.invoke-model.js.snapshot/aws-stepfunctions-tasks-bedrock-invoke-model-integ.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/bedrock/integ.invoke-model.js.snapshot/aws-stepfunctions-tasks-bedrock-invoke-model-integ.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/bedrock/integ.invoke-model.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/bedrock/integ.invoke-model.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/bedrock/integ.invoke-model.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/bedrock/integ.invoke-model.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/bedrock/integ.invoke-model.ts
  packages/aws-cdk-lib/aws-stepfunctions-tasks/README.md
  packages/aws-cdk-lib/aws-stepfunctions-tasks/lib/bedrock/invoke-model.ts
  packages/aws-cdk-lib/aws-stepfunctions-tasks/test/bedrock/invoke-model.test.ts
Labels: p2, contribution/core

#31327 feat(bedrock): add Stable Image Ultra, Stable Diffusion 3 Large, and Stable Image Core model identifiers
  packages/aws-cdk-lib/aws-bedrock/lib/foundation-model.ts
Labels: p2, pr-linter/exempt-readme, pr-linter/exempt-test, pr-linter/exempt-integ-test, distinguished-contributor

#31305 fix(stepfunctions-tasks): fix bedrock input/output path in step-funct…
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/bedrock/integ.invoke-model.js.snapshot/InvokeModelDefaultTestDeployAssert9C0D2DFC.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/bedrock/integ.invoke-model.js.snapshot/aws-stepfunctions-tasks-bedrock-invoke-model-integ.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/bedrock/integ.invoke-model.js.snapshot/aws-stepfunctions-tasks-bedrock-invoke-model-integ.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/bedrock/integ.invoke-model.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/bedrock/integ.invoke-model.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/bedrock/integ.invoke-model.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/bedrock/integ.invoke-model.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/bedrock/integ.invoke-model.ts
  packages/@aws-cdk/cx-api/FEATURE_FLAGS.md
  packages/aws-cdk-lib/aws-stepfunctions-tasks/README.md
  packages/aws-cdk-lib/aws-stepfunctions-tasks/lib/bedrock/invoke-model.ts
  packages/aws-cdk-lib/aws-stepfunctions-tasks/test/bedrock/invoke-model.test.ts
  packages/aws-cdk-lib/cx-api/FEATURE_FLAGS.md
  packages/aws-cdk-lib/cx-api/README.md
  packages/aws-cdk-lib/cx-api/lib/features.ts
  packages/aws-cdk-lib/cx-api/test/features.test.ts
Labels: bug, p0, contribution/core

#31273 chore(ec2): add interface endpoint for Redshift Serverless
  packages/aws-cdk-lib/aws-ec2/lib/vpc-endpoint.ts
Labels: p2, distinguished-contributor, pr/needs-maintainer-review

#31326 feat(appsync): support DEBUG and INFO logging levels for AppSync GraphQL APIs
  packages/@aws-cdk-testing/framework-integ/test/aws-appsync/test/integ.graphql-field-level-log.js.snapshot/GraphQLFieldLevelLogDefaultTestDeployAssert06C4E034.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-appsync/test/integ.graphql-field-level-log.js.snapshot/GraphQLFieldLevelLogDefaultTestDeployAssert06C4E034.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-appsync/test/integ.graphql-field-level-log.js.snapshot/asset.e4afb15788ec44ed9ff3377e1d131ba2768d7b2e2931bc000d1f2005879b3035/index.js
  packages/@aws-cdk-testing/framework-integ/test/aws-appsync/test/integ.graphql-field-level-log.js.snapshot/aws-cdk-appsync-graphql-field-level-log.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-appsync/test/integ.graphql-field-level-log.js.snapshot/aws-cdk-appsync-graphql-field-level-log.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-appsync/test/integ.graphql-field-level-log.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-appsync/test/integ.graphql-field-level-log.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-appsync/test/integ.graphql-field-level-log.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-appsync/test/integ.graphql-field-level-log.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-appsync/test/integ.graphql-field-level-log.ts
  packages/aws-cdk-lib/aws-appsync/README.md
  packages/aws-cdk-lib/aws-appsync/lib/graphqlapi.ts
  packages/aws-cdk-lib/aws-appsync/test/appsync.test.ts
Labels: p2, distinguished-contributor

#31333 docs(contributing): quick start
  CONTRIBUTING.md
Labels: p2, repeat-contributor

#31346 chore: update changelog to include python 3.11 update
  CHANGELOG.v2.md
Labels: p2, contribution/core

#31013 feat(lambda): added new property allowAllIpv6Outbound to FunctionOptions
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda/test/integ.lambda-allow-all-ipv6-outbound.js.snapshot/LambdaAllowAllIpv6Outbound.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda/test/integ.lambda-allow-all-ipv6-outbound.js.snapshot/LambdaAllowAllIpv6Outbound.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda/test/integ.lambda-allow-all-ipv6-outbound.js.snapshot/asset.bde7b5c89cb43285f884c94f0b9e17cdb0f5eb5345005114dd60342e0b8a85a1/__entrypoint__.js
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda/test/integ.lambda-allow-all-ipv6-outbound.js.snapshot/asset.bde7b5c89cb43285f884c94f0b9e17cdb0f5eb5345005114dd60342e0b8a85a1/index.js
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda/test/integ.lambda-allow-all-ipv6-outbound.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda/test/integ.lambda-allow-all-ipv6-outbound.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda/test/integ.lambda-allow-all-ipv6-outbound.js.snapshot/lambdaallowallipv6outboundDefaultTestDeployAssert52B7EB97.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda/test/integ.lambda-allow-all-ipv6-outbound.js.snapshot/lambdaallowallipv6outboundDefaultTestDeployAssert52B7EB97.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda/test/integ.lambda-allow-all-ipv6-outbound.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda/test/integ.lambda-allow-all-ipv6-outbound.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda/test/integ.lambda-allow-all-ipv6-outbound.ts
  packages/aws-cdk-lib/aws-lambda/README.md
  packages/aws-cdk-lib/aws-lambda/lib/function.ts
  packages/aws-cdk-lib/aws-lambda/test/function.test.ts
Labels: p2, feature-request, effort/small, contribution/core

#31353 chore: fix spelling error of if
  packages/@aws-cdk/cloudformation-diff/lib/diff-template.ts
  packages/aws-cdk-lib/aws-ec2/lib/instance.ts
  packages/aws-cdk/lib/notices.ts
Labels: p2, distinguished-contributor, pr-linter/cli-integ-tested

#31365 chore(cognito): fix test case name for User Pool Domain
  packages/aws-cdk-lib/aws-cognito/test/user-pool-domain.test.ts
Labels: p2, pr/needs-community-review, distinguished-contributor

#31364 chore(stepfunctions-tasks): doc has incorrect api endpoint
  packages/aws-cdk-lib/aws-stepfunctions-tasks/README.md
Labels: bug, p2, effort/small, distinguished-contributor

#31354 fix(rds): proxy target group does not depend on database instances when using writer property for database cluster
  packages/@aws-cdk-testing/framework-integ/test/aws-rds/test/integ.proxy.js.snapshot/aws-cdk-rds-proxy.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-rds/test/integ.proxy.js.snapshot/aws-cdk-rds-proxy.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-rds/test/integ.proxy.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-rds/test/integ.proxy.js.snapshot/databaseproxyintegtestDefaultTestDeployAssert1DC3D9D5.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-rds/test/integ.proxy.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-rds/test/integ.proxy.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-rds/test/integ.proxy.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-rds/test/integ.proxy.ts
  packages/aws-cdk-lib/aws-rds/lib/proxy.ts
  packages/aws-cdk-lib/aws-rds/test/proxy.test.ts
Labels: bug, p2, effort/small, distinguished-contributor

#31363 chore(neptune-alpha): add engine versions, instance types
  packages/@aws-cdk/aws-neptune-alpha/lib/cluster.ts
  packages/@aws-cdk/aws-neptune-alpha/lib/instance.ts
Labels: p2, feature-request, effort/small, distinguished-contributor

#31359 chore(ec2): add interface VPC endpoints
  packages/aws-cdk-lib/aws-ec2/lib/vpc-endpoint.ts
Labels: p2, distinguished-contributor

#31350 chore(ec2): support FIPS interface VPC endpoint for Kinesis Data Streams
  packages/aws-cdk-lib/aws-ec2/lib/vpc-endpoint.ts
Labels: p2, distinguished-contributor

#31367 chore(cloudfront): warning on empty `domainNames` to alert a manual action
  packages/aws-cdk-lib/aws-cloudfront/lib/distribution.ts
  packages/aws-cdk-lib/aws-cloudfront/test/distribution.test.ts
Labels: p2, admired-contributor

#31361 feat: update L1 CloudFormation resource definitions
  packages/@aws-cdk/cloudformation-diff/package.json
  packages/@aws-cdk/integ-runner/package.json
  packages/aws-cdk-lib/aws-pcaconnectorscep/.jsiirc.json
  packages/aws-cdk-lib/aws-pcaconnectorscep/README.md
  packages/aws-cdk-lib/aws-pcaconnectorscep/index.ts
  packages/aws-cdk-lib/aws-pcaconnectorscep/lib/index.ts
  packages/aws-cdk-lib/aws-ssmquicksetup/.jsiirc.json
  packages/aws-cdk-lib/aws-ssmquicksetup/README.md
  packages/aws-cdk-lib/aws-ssmquicksetup/index.ts
  packages/aws-cdk-lib/aws-ssmquicksetup/lib/index.ts
  packages/aws-cdk-lib/index.ts
  packages/aws-cdk-lib/package.json
  packages/aws-cdk-lib/scripts/scope-map.json
  tools/@aws-cdk/spec2cdk/package.json
  yarn.lock
Labels: p2, dependencies, contribution/core, pr-linter/exempt-readme, pr-linter/exempt-test, auto-approve, pr-linter/exempt-integ-test, pr/needs-maintainer-review

#31382 chore(merge-back): 2.157.0
  CHANGELOG.v2.alpha.md
  CHANGELOG.v2.md
  version.v2.json
Labels: p2, pr/needs-community-review, pr/no-squash, auto-approve

#31352 feat(iot): configure IoT Logging
  packages/@aws-cdk/aws-iot-alpha/README.md
  packages/@aws-cdk/aws-iot-alpha/awslint.json
  packages/@aws-cdk/aws-iot-alpha/lib/index.ts
  packages/@aws-cdk/aws-iot-alpha/lib/logging.ts
  packages/@aws-cdk/aws-iot-alpha/test/integ.logging.js.snapshot/IotLoggingTestDefaultTestDeployAssertB1DE3CEF.assets.json
  packages/@aws-cdk/aws-iot-alpha/test/integ.logging.js.snapshot/IotLoggingTestDefaultTestDeployAssertB1DE3CEF.template.json
  packages/@aws-cdk/aws-iot-alpha/test/integ.logging.js.snapshot/IotLoggingTestStack.assets.json
  packages/@aws-cdk/aws-iot-alpha/test/integ.logging.js.snapshot/IotLoggingTestStack.template.json
  packages/@aws-cdk/aws-iot-alpha/test/integ.logging.js.snapshot/cdk.out
  packages/@aws-cdk/aws-iot-alpha/test/integ.logging.js.snapshot/integ.json
  packages/@aws-cdk/aws-iot-alpha/test/integ.logging.js.snapshot/manifest.json
  packages/@aws-cdk/aws-iot-alpha/test/integ.logging.js.snapshot/tree.json
  packages/@aws-cdk/aws-iot-alpha/test/integ.logging.ts
  packages/@aws-cdk/aws-iot-alpha/test/logging.test.ts
Labels: p2, feature-request, distinguished-contributor, pr/needs-maintainer-review

#31383 chore: fix CHANGELOG.v2.md
  CHANGELOG.v2.md
Labels: p2, contribution/core

#31381 feat(amplify): support cache configuration for app
  packages/@aws-cdk/aws-amplify-alpha/README.md
  packages/@aws-cdk/aws-amplify-alpha/lib/app.ts
  packages/@aws-cdk/aws-amplify-alpha/test/app.test.ts
  packages/@aws-cdk/aws-amplify-alpha/test/integ.app-cache-config.js.snapshot/amplifyappcachecofigintegDefaultTestDeployAssert14075C62.assets.json
  packages/@aws-cdk/aws-amplify-alpha/test/integ.app-cache-config.js.snapshot/amplifyappcachecofigintegDefaultTestDeployAssert14075C62.template.json
  packages/@aws-cdk/aws-amplify-alpha/test/integ.app-cache-config.js.snapshot/cdk-amplify-app-cache-config.assets.json
  packages/@aws-cdk/aws-amplify-alpha/test/integ.app-cache-config.js.snapshot/cdk-amplify-app-cache-config.template.json
  packages/@aws-cdk/aws-amplify-alpha/test/integ.app-cache-config.js.snapshot/cdk.out
  packages/@aws-cdk/aws-amplify-alpha/test/integ.app-cache-config.js.snapshot/integ.json
  packages/@aws-cdk/aws-amplify-alpha/test/integ.app-cache-config.js.snapshot/manifest.json
  packages/@aws-cdk/aws-amplify-alpha/test/integ.app-cache-config.js.snapshot/tree.json
  packages/@aws-cdk/aws-amplify-alpha/test/integ.app-cache-config.ts
Labels: p2, distinguished-contributor

#30515 fix(cloudformation-include): can't use CFN intrinsics in Tags
  packages/@aws-cdk-testing/framework-integ/test/cloudformation-include/test/integ.resource-tags-wtih-intrinsics.js.snapshot/ResourceTagIntrinsicStackDefaultTestDeployAssert069A8F1A.assets.json
  packages/@aws-cdk-testing/framework-integ/test/cloudformation-include/test/integ.resource-tags-wtih-intrinsics.js.snapshot/ResourceTagIntrinsicStackDefaultTestDeployAssert069A8F1A.template.json
  packages/@aws-cdk-testing/framework-integ/test/cloudformation-include/test/integ.resource-tags-wtih-intrinsics.js.snapshot/Stack.assets.json
  packages/@aws-cdk-testing/framework-integ/test/cloudformation-include/test/integ.resource-tags-wtih-intrinsics.js.snapshot/Stack.template.json
  packages/@aws-cdk-testing/framework-integ/test/cloudformation-include/test/integ.resource-tags-wtih-intrinsics.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/cloudformation-include/test/integ.resource-tags-wtih-intrinsics.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/cloudformation-include/test/integ.resource-tags-wtih-intrinsics.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/cloudformation-include/test/integ.resource-tags-wtih-intrinsics.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/cloudformation-include/test/integ.resource-tags-wtih-intrinsics.ts
  packages/@aws-cdk-testing/framework-integ/test/cloudformation-include/test/test-templates/tags-with-intrinsics.json
  packages/aws-cdk-lib/cloudformation-include/test/test-templates/tags-with-intrinsics.json
  packages/aws-cdk-lib/cloudformation-include/test/test-templates/tags-with-invalid-intrinsics.json
  packages/aws-cdk-lib/cloudformation-include/test/valid-templates.test.ts
  packages/aws-cdk-lib/core/lib/helpers-internal/cfn-parse.ts
  packages/aws-cdk-lib/core/lib/runtime.ts
Labels: bug, p1, contribution/core

#31396 chore(diff): fomatter unit test fails locally
  packages/@aws-cdk/cloudformation-diff/test/format.test.ts
Labels: p2, contribution/core

#30991 chore: npm-check-updates && yarn upgrade
  package.json
  packages/@aws-cdk-testing/cli-integ/package.json
  packages/@aws-cdk-testing/framework-integ/package.json
  packages/@aws-cdk/aws-redshift-alpha/lib/private/database-query-provider/privileges.ts
  packages/@aws-cdk/aws-redshift-alpha/lib/private/database-query-provider/table.ts
  packages/@aws-cdk/aws-redshift-alpha/lib/private/database-query-provider/user.ts
  packages/@aws-cdk/cloudformation-diff/package.json
  packages/@aws-cdk/custom-resource-handlers/package.json
  packages/@aws-cdk/cx-api/package.json
  packages/@aws-cdk/integ-runner/THIRD_PARTY_LICENSES
  packages/@aws-cdk/integ-runner/lib/runner/runner-base.ts
  packages/@aws-cdk/integ-runner/package.json
  packages/@aws-cdk/integ-tests-alpha/package.json
  packages/aws-cdk-lib/NOTICE
  packages/aws-cdk-lib/assertions/lib/private/resources.ts
  packages/aws-cdk-lib/aws-apigatewayv2-authorizers/test/websocket/iam.test.ts
  packages/aws-cdk-lib/aws-apigatewayv2-authorizers/test/websocket/lambda.test.ts
  packages/aws-cdk-lib/aws-apigatewayv2-integrations/test/http/http-proxy.test.ts
  packages/aws-cdk-lib/aws-apigatewayv2-integrations/test/http/lambda.test.ts
  packages/aws-cdk-lib/aws-apigatewayv2-integrations/test/http/nlb.test.ts
  packages/aws-cdk-lib/aws-apigatewayv2-integrations/test/http/private/integration.test.ts
  packages/aws-cdk-lib/aws-apigatewayv2-integrations/test/http/service-discovery.test.ts
  packages/aws-cdk-lib/aws-apigatewayv2-integrations/test/websocket/aws.test.ts
  packages/aws-cdk-lib/aws-apigatewayv2-integrations/test/websocket/lambda.test.ts
  packages/aws-cdk-lib/aws-apigatewayv2-integrations/test/websocket/mock.test.ts
  packages/aws-cdk-lib/aws-cognito/lib/user-pool-idps/amazon.ts
  packages/aws-cdk-lib/aws-cognito/lib/user-pool-idps/apple.ts
  packages/aws-cdk-lib/aws-cognito/lib/user-pool-idps/facebook.ts
  packages/aws-cdk-lib/aws-stepfunctions/lib/states/custom-state.ts
  packages/aws-cdk-lib/core/lib/private/cfn-utils-provider.ts
  packages/aws-cdk-lib/package.json
  packages/aws-cdk/THIRD_PARTY_LICENSES
  packages/aws-cdk/lib/api/deploy-stack.ts
  packages/aws-cdk/lib/api/deployments.ts
  packages/aws-cdk/lib/api/hotswap-deployments.ts
  packages/aws-cdk/lib/api/toolkit-info.ts
  packages/aws-cdk/lib/init-templates/app/typescript/package.json
  packages/aws-cdk/lib/init-templates/lib/typescript/package.json
  packages/aws-cdk/lib/init-templates/sample-app/typescript/package.json
  packages/aws-cdk/package.json
  packages/awslint/package.json
  tools/@aws-cdk/cdk-build-tools/package.json
  tools/@aws-cdk/cdk-release/package.json
  tools/@aws-cdk/lazify/package.json
  tools/@aws-cdk/node-bundle/LICENSE
  tools/@aws-cdk/node-bundle/package.json
  tools/@aws-cdk/pkglint/package.json
  tools/@aws-cdk/prlint/package.json
  tools/@aws-cdk/yarn-cling/package.json
  yarn.lock
Labels: p2, dependencies, contribution/core, auto-approve

#31399 chore: npm-check-updates && yarn upgrade
  package.json
  packages/@aws-cdk-testing/cli-integ/package.json
  packages/@aws-cdk-testing/framework-integ/package.json
  packages/@aws-cdk/cli-lib-alpha/THIRD_PARTY_LICENSES
  packages/@aws-cdk/cx-api/FEATURE_FLAGS.md
  packages/aws-cdk-lib/package.json
  packages/aws-cdk/THIRD_PARTY_LICENSES
  packages/aws-cdk/lib/init-templates/app/typescript/package.json
  packages/aws-cdk/lib/init-templates/lib/typescript/package.json
  packages/aws-cdk/lib/init-templates/sample-app/typescript/package.json
  packages/aws-cdk/package.json
  tools/@aws-cdk/cdk-build-tools/package.json
  tools/@aws-cdk/lazify/package.json
  yarn.lock
Labels: p2, dependencies, contribution/core, auto-approve

#31411 chore: add new intern michelle-wangg to list
  .github/workflows/github-merit-badger.yml
  .mergify.yml
Labels: p2, beginning-contributor

#31414 chore(merge-back): 2.158.0
  CHANGELOG.v2.alpha.md
  CHANGELOG.v2.md
  version.v2.json
Labels: p2, pr/needs-community-review, pr/no-squash, auto-approve

#31387 chore(rds): deprecate CA certificate rds-ca-2019
  packages/aws-cdk-lib/aws-rds/lib/ca-certificate.ts
Labels: p2, distinguished-contributor

#31432 chore(dynamodb): update waitForReplicationToFinish flag summary doc to highlight that it may cause deletion for existing replicas.
  packages/aws-cdk-lib/aws-dynamodb/lib/table.ts
Labels: p2, contribution/core, pr/needs-maintainer-review

#31435 feat(events-target): support Dead Letter Queue for Kinesis Stream Event Target
  packages/@aws-cdk-testing/framework-integ/test/aws-events-targets/test/kinesis/integ.kinesis-stream-dead-letter-queue.js.snapshot/KinesisDlqDefaultTestDeployAssertE4CFAC29.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-events-targets/test/kinesis/integ.kinesis-stream-dead-letter-queue.js.snapshot/KinesisDlqDefaultTestDeployAssertE4CFAC29.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-events-targets/test/kinesis/integ.kinesis-stream-dead-letter-queue.js.snapshot/aws-cdk-kinesis-event-target-dlq.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-events-targets/test/kinesis/integ.kinesis-stream-dead-letter-queue.js.snapshot/aws-cdk-kinesis-event-target-dlq.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-events-targets/test/kinesis/integ.kinesis-stream-dead-letter-queue.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-events-targets/test/kinesis/integ.kinesis-stream-dead-letter-queue.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-events-targets/test/kinesis/integ.kinesis-stream-dead-letter-queue.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-events-targets/test/kinesis/integ.kinesis-stream-dead-letter-queue.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-events-targets/test/kinesis/integ.kinesis-stream-dead-letter-queue.ts
  packages/aws-cdk-lib/aws-events-targets/README.md
  packages/aws-cdk-lib/aws-events-targets/lib/kinesis-stream.ts
  packages/aws-cdk-lib/aws-events-targets/test/kinesis/kinesis-stream.test.ts
Labels: p2, feature-request, effort/small, pr/needs-community-review, distinguished-contributor

#31388 chore(ec2): add new interface vpc endpoint
  packages/aws-cdk-lib/aws-ec2/lib/vpc-endpoint.ts
Labels: p2, distinguished-contributor

#30248 feat(elasticloadbalancingv2): alb dualstack without public ipv4
  packages/@aws-cdk-testing/framework-integ/test/aws-elasticloadbalancingv2/test/integ.alb.dualstack-without-public-ipv4.js.snapshot/AlbDualstackWithoutPublicIpv4DefaultTestDeployAssertFA6F90DD.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-elasticloadbalancingv2/test/integ.alb.dualstack-without-public-ipv4.js.snapshot/AlbDualstackWithoutPublicIpv4DefaultTestDeployAssertFA6F90DD.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-elasticloadbalancingv2/test/integ.alb.dualstack-without-public-ipv4.js.snapshot/aws-cdk-elbv2-integ-dualstack-without-public-ipv4.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-elasticloadbalancingv2/test/integ.alb.dualstack-without-public-ipv4.js.snapshot/aws-cdk-elbv2-integ-dualstack-without-public-ipv4.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-elasticloadbalancingv2/test/integ.alb.dualstack-without-public-ipv4.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-elasticloadbalancingv2/test/integ.alb.dualstack-without-public-ipv4.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-elasticloadbalancingv2/test/integ.alb.dualstack-without-public-ipv4.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-elasticloadbalancingv2/test/integ.alb.dualstack-without-public-ipv4.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-elasticloadbalancingv2/test/integ.alb.dualstack-without-public-ipv4.ts
  packages/aws-cdk-lib/aws-elasticloadbalancingv2/README.md
  packages/aws-cdk-lib/aws-elasticloadbalancingv2/lib/alb/application-load-balancer.ts
  packages/aws-cdk-lib/aws-elasticloadbalancingv2/lib/shared/base-load-balancer.ts
  packages/aws-cdk-lib/aws-elasticloadbalancingv2/lib/shared/enums.ts
  packages/aws-cdk-lib/aws-elasticloadbalancingv2/test/alb/load-balancer.test.ts
  packages/aws-cdk-lib/aws-elasticloadbalancingv2/test/nlb/load-balancer.test.ts
  packages/aws-cdk-lib/cx-api/lib/context/load-balancer.ts
Labels: p2, feature-request, effort/medium, valued-contributor

#31142 feat(stepfunctions-tasks): support idle timeout for EmrCreateCluster
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/emr/integ.emr-create-cluster-with-auto-deletion-policy-idle-timeout.js.snapshot/EmrCreateClusterTestAutoDeletionPolicyIdleTimeoutDefaultTestDeployAssert01F5278A.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/emr/integ.emr-create-cluster-with-auto-deletion-policy-idle-timeout.js.snapshot/EmrCreateClusterTestAutoDeletionPolicyIdleTimeoutDefaultTestDeployAssert01F5278A.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/emr/integ.emr-create-cluster-with-auto-deletion-policy-idle-timeout.js.snapshot/asset.3cef2cdbb46b3821e641ffb8b9af9731af5f7e4a9e857ab633dbcd9023de724d.bundle/index.js
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/emr/integ.emr-create-cluster-with-auto-deletion-policy-idle-timeout.js.snapshot/aws-cdk-emr-create-cluster-auto-deletion-policy-idle-timeout.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/emr/integ.emr-create-cluster-with-auto-deletion-policy-idle-timeout.js.snapshot/aws-cdk-emr-create-cluster-auto-deletion-policy-idle-timeout.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/emr/integ.emr-create-cluster-with-auto-deletion-policy-idle-timeout.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/emr/integ.emr-create-cluster-with-auto-deletion-policy-idle-timeout.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/emr/integ.emr-create-cluster-with-auto-deletion-policy-idle-timeout.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/emr/integ.emr-create-cluster-with-auto-deletion-policy-idle-timeout.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/emr/integ.emr-create-cluster-with-auto-deletion-policy-idle-timeout.ts
  packages/aws-cdk-lib/aws-stepfunctions-tasks/README.md
  packages/aws-cdk-lib/aws-stepfunctions-tasks/lib/emr/emr-create-cluster.ts
  packages/aws-cdk-lib/aws-stepfunctions-tasks/test/emr/emr-create-cluster.test.ts
Labels: p2, feature-request, effort/medium, distinguished-contributor

#31418 chore(rds): support engine versions for Aurora MySQL and RDS for SQL Server
  packages/aws-cdk-lib/aws-rds/lib/cluster-engine.ts
  packages/aws-cdk-lib/aws-rds/lib/instance-engine.ts
Labels: p2, distinguished-contributor

#31261 fix: pipelines ties cli version with cdk-assets version
  packages/@aws-cdk-testing/framework-integ/test/pipelines/test/integ.newpipeline-with-file-system-locations.js.snapshot/PipelinesFileSystemLocations.assets.json
  packages/@aws-cdk-testing/framework-integ/test/pipelines/test/integ.newpipeline-with-file-system-locations.js.snapshot/PipelinesFileSystemLocations.template.json
  packages/@aws-cdk-testing/framework-integ/test/pipelines/test/integ.newpipeline-with-file-system-locations.js.snapshot/assembly-PipelinesFileSystemLocations-Beta/PipelinesFileSystemLocationsBetaStack18199ECAE.assets.json
  packages/@aws-cdk-testing/framework-integ/test/pipelines/test/integ.newpipeline-with-file-system-locations.js.snapshot/assembly-PipelinesFileSystemLocations-Beta/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/pipelines/test/integ.newpipeline-with-file-system-locations.js.snapshot/assembly-PipelinesFileSystemLocations-Beta/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/pipelines/test/integ.newpipeline-with-file-system-locations.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/pipelines/test/integ.newpipeline-with-file-system-locations.js.snapshot/cdkintegcodepipelinewithfilesystemlocationsDefaultTestDeployAssert3E26E748.assets.json
  packages/@aws-cdk-testing/framework-integ/test/pipelines/test/integ.newpipeline-with-file-system-locations.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/pipelines/test/integ.newpipeline-with-file-system-locations.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/pipelines/test/integ.newpipeline-with-file-system-locations.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/pipelines/test/integ.newpipeline-with-vpc.js.snapshot/PipelineStack.assets.json
  packages/@aws-cdk-testing/framework-integ/test/pipelines/test/integ.newpipeline-with-vpc.js.snapshot/PipelineStack.template.json
  packages/@aws-cdk-testing/framework-integ/test/pipelines/test/integ.newpipeline-with-vpc.js.snapshot/assembly-PipelineStack-Beta/PipelineStackBetaStack1E6541489.assets.json
  packages/@aws-cdk-testing/framework-integ/test/pipelines/test/integ.newpipeline-with-vpc.js.snapshot/assembly-PipelineStack-Beta/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/pipelines/test/integ.newpipeline-with-vpc.js.snapshot/assembly-PipelineStack-Beta/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/pipelines/test/integ.newpipeline-with-vpc.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/pipelines/test/integ.newpipeline-with-vpc.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/pipelines/test/integ.newpipeline-with-vpc.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/pipelines/test/integ.newpipeline-with-vpc.js.snapshot/tree.json
  packages/aws-cdk-lib/pipelines/lib/codepipeline/codepipeline.ts
  packages/aws-cdk-lib/pipelines/lib/private/cli-version.ts
  packages/aws-cdk-lib/pipelines/test/compliance/assets.test.ts
Labels: bug, p2, effort/medium, contribution/core, pr-linter/exempt-integ-test

#31202 chore(elasticloadbalancingv2): add validation for `RedirectOptions.path`
  packages/aws-cdk-lib/aws-elasticloadbalancingv2/README.md
  packages/aws-cdk-lib/aws-elasticloadbalancingv2/lib/alb/application-listener-action.ts
  packages/aws-cdk-lib/aws-elasticloadbalancingv2/test/alb/actions.test.ts
Labels: p2, feature-request, effort/small, distinguished-contributor, pr-linter/exemption-requested

#31380 feat(ivs): support RTMP ingest for IVS channel
  packages/@aws-cdk/aws-ivs-alpha/README.md
  packages/@aws-cdk/aws-ivs-alpha/lib/channel.ts
  packages/@aws-cdk/aws-ivs-alpha/test/integ.ivs-insecure-ingest.js.snapshot/aws-cdk-ivs-insecure-ingest.assets.json
  packages/@aws-cdk/aws-ivs-alpha/test/integ.ivs-insecure-ingest.js.snapshot/aws-cdk-ivs-insecure-ingest.template.json
  packages/@aws-cdk/aws-ivs-alpha/test/integ.ivs-insecure-ingest.js.snapshot/cdk.out
  packages/@aws-cdk/aws-ivs-alpha/test/integ.ivs-insecure-ingest.js.snapshot/integ.json
  packages/@aws-cdk/aws-ivs-alpha/test/integ.ivs-insecure-ingest.js.snapshot/ivsinsecureingesttestDefaultTestDeployAssert6FABA1ED.assets.json
  packages/@aws-cdk/aws-ivs-alpha/test/integ.ivs-insecure-ingest.js.snapshot/ivsinsecureingesttestDefaultTestDeployAssert6FABA1ED.template.json
  packages/@aws-cdk/aws-ivs-alpha/test/integ.ivs-insecure-ingest.js.snapshot/manifest.json
  packages/@aws-cdk/aws-ivs-alpha/test/integ.ivs-insecure-ingest.js.snapshot/tree.json
  packages/@aws-cdk/aws-ivs-alpha/test/integ.ivs-insecure-ingest.ts
  packages/@aws-cdk/aws-ivs-alpha/test/ivs.test.ts
Labels: p2, distinguished-contributor

#31415 fix(ssm): update ssm-context to prevent raising an error on missing parameter
  packages/@aws-cdk-testing/framework-integ/test/aws-ssm/test/integ.value-from-lookup-with-default.js.snapshot/ValueFromLookupWithDefaultTestDeployAssert525E0911.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ssm/test/integ.value-from-lookup-with-default.js.snapshot/ValueFromLookupWithDefaultTestDeployAssert525E0911.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ssm/test/integ.value-from-lookup-with-default.js.snapshot/asset.2b0738aa9374af84bba13e7829ab41a876dcaf156e442d086ccd372af2fd13f9.bundle/index.js
  packages/@aws-cdk-testing/framework-integ/test/aws-ssm/test/integ.value-from-lookup-with-default.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-ssm/test/integ.value-from-lookup-with-default.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ssm/test/integ.value-from-lookup-with-default.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ssm/test/integ.value-from-lookup-with-default.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ssm/test/integ.value-from-lookup-with-default.js.snapshot/value-from-lookup-with-defaults.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ssm/test/integ.value-from-lookup-with-default.js.snapshot/value-from-lookup-with-defaults.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ssm/test/integ.value-from-lookup-with-default.ts
  packages/aws-cdk-lib/aws-ec2/test/machine-image.test.ts
  packages/aws-cdk-lib/aws-ssm/lib/parameter.ts
  packages/aws-cdk-lib/aws-ssm/test/parameter.test.ts
  packages/aws-cdk-lib/core/lib/context-provider.ts
  packages/aws-cdk/lib/context-providers/ssm-parameters.ts
Labels: p2, feature-request, effort/large, beginning-contributor, pr-linter/cli-integ-tested

#31409 fix(cognito): deprecate privateKey and add privateKeyValue as typed SecureValue
  packages/aws-cdk-lib/aws-cognito/lib/user-pool-idps/apple.ts
  packages/aws-cdk-lib/aws-cognito/test/user-pool-idps/apple.test.ts
Labels: bug, p2, effort/medium, contribution/core, pr-linter/exempt-integ-test

#31430 chore(kinesisfirehose-alpha): refactor encryption property to combine encryptionKey
  packages/@aws-cdk/aws-kinesisfirehose-alpha/README.md
  packages/@aws-cdk/aws-kinesisfirehose-alpha/lib/delivery-stream.ts
  packages/@aws-cdk/aws-kinesisfirehose-alpha/lib/encryption.ts
  packages/@aws-cdk/aws-kinesisfirehose-alpha/lib/index.ts
  packages/@aws-cdk/aws-kinesisfirehose-alpha/test/delivery-stream.test.ts
  packages/@aws-cdk/aws-kinesisfirehose-alpha/test/integ.delivery-stream.ts
Labels: p2, contribution/core

#31384 chore(ec2): support interface VPC endpoint for RAM
  packages/aws-cdk-lib/aws-ec2/lib/vpc-endpoint.ts
Labels: p2, distinguished-contributor

#31373 feat(apigatewayv2): support for setting `routeSelectionExpression` for an HTTP API
  packages/@aws-cdk-testing/framework-integ/test/aws-apigatewayv2/test/http/integ.api.js.snapshot/aws-cdk-aws-apigatewayv2.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-apigatewayv2/test/http/integ.api.js.snapshot/aws-cdk-aws-apigatewayv2.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-apigatewayv2/test/http/integ.api.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-apigatewayv2/test/http/integ.api.js.snapshot/httpapiDefaultTestDeployAssert77633A40.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-apigatewayv2/test/http/integ.api.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-apigatewayv2/test/http/integ.api.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-apigatewayv2/test/http/integ.api.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-apigatewayv2/test/http/integ.api.ts
  packages/aws-cdk-lib/aws-apigatewayv2/README.md
  packages/aws-cdk-lib/aws-apigatewayv2/lib/http/api.ts
  packages/aws-cdk-lib/aws-apigatewayv2/test/http/api.test.ts
Labels: p2, feature-request, effort/medium, distinguished-contributor

#31437 chore(s3): readme update with mixing L1 and L2 bucket policy
  packages/aws-cdk-lib/aws-s3/README.md
Labels: bug, p2, effort/medium, contribution/core

#31394 fix(eks): update private ecr repo url regex
  packages/@aws-cdk/custom-resource-handlers/lib/aws-eks/kubectl-handler/helm/__init__.py
  packages/aws-cdk-lib/aws-eks/test/helm-chart.test.ts
Labels: p2, pr-linter/exempt-integ-test, beginning-contributor, pr-linter/exemption-requested

#31433 fix(lambda): invalid Version object created from Version.fromVersionArn
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda/test/integ.lambda-version-arn.js.snapshot/asset.3cef2cdbb46b3821e641ffb8b9af9731af5f7e4a9e857ab633dbcd9023de724d.bundle/index.js
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda/test/integ.lambda-version-arn.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda/test/integ.lambda-version-arn.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda/test/integ.lambda-version-arn.js.snapshot/lambda-version-arn.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda/test/integ.lambda-version-arn.js.snapshot/lambda-version-arn.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda/test/integ.lambda-version-arn.js.snapshot/lambdaversionDefaultTestDeployAssert7B4F8B2D.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda/test/integ.lambda-version-arn.js.snapshot/lambdaversionDefaultTestDeployAssert7B4F8B2D.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda/test/integ.lambda-version-arn.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda/test/integ.lambda-version-arn.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda/test/integ.lambda-version-arn.ts
  packages/aws-cdk-lib/aws-lambda/lib/lambda-version.ts
  packages/aws-cdk-lib/aws-lambda/test/lambda-version.test.ts
Labels: bug, p1, effort/small, contribution/core

#31410 fix(cli): bootstrap respects qualifier from cdk.json
  packages/aws-cdk/lib/api/bootstrap/bootstrap-props.ts
  packages/aws-cdk/lib/cli.ts
  packages/aws-cdk/test/cdk-toolkit.test.ts
Labels: bug, p1, effort/medium, contribution/core, pr-linter/exempt-integ-test, pr-linter/cli-integ-tested

#31460 feat: update L1 CloudFormation resource definitions
  yarn.lock
Labels: p2, dependencies, contribution/core, pr-linter/exempt-readme, pr-linter/exempt-test, auto-approve, pr-linter/exempt-integ-test

#31434 fix(ec2): fixing vpc endpoint pattern for ecr and ecr docker
  packages/aws-cdk-lib/aws-ec2/lib/vpc-endpoint.ts
  packages/aws-cdk-lib/aws-ec2/test/vpc-endpoint.test.ts
Labels: p2, contribution/core, pr-linter/exempt-integ-test, pr-linter/exemption-requested

#31465 chore: add jiayiwang7 to mergify and merit badger
  .github/workflows/github-merit-badger.yml
  .mergify.yml
Labels: p2, beginning-contributor

#31398 feat(opensearch): support OpenSearch version 2.15
  packages/@aws-cdk-testing/framework-integ/test/aws-opensearchservice/test/integ.opensearch.min.js.snapshot/cdk-integ-opensearch-min.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-opensearchservice/test/integ.opensearch.min.js.snapshot/cdk-integ-opensearch-min.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-opensearchservice/test/integ.opensearch.min.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-opensearchservice/test/integ.opensearch.min.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-opensearchservice/test/integ.opensearch.min.js.snapshot/integopenseachminDefaultTestDeployAssert0EB58658.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-opensearchservice/test/integ.opensearch.min.js.snapshot/integopenseachminDefaultTestDeployAssert0EB58658.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-opensearchservice/test/integ.opensearch.min.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-opensearchservice/test/integ.opensearch.min.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-opensearchservice/test/integ.opensearch.min.ts
  packages/aws-cdk-lib/aws-opensearchservice/lib/version.ts
  packages/aws-cdk-lib/aws-opensearchservice/test/domain.test.ts
Labels: p2, pr-linter/exempt-readme, distinguished-contributor

#31395 docs(s3): updated docstring for BucketPolicy()
  packages/aws-cdk-lib/aws-s3/lib/bucket-policy.ts
Labels: bug, p2, @aws-cdk/aws-s3, effort/small, pr-linter/exemption-requested

#31406 fix(cli): hotswapping appsync functions fails when API does not return function on the first page
  packages/@aws-cdk-testing/cli-integ/resources/cdk-apps/app/app.js
  packages/@aws-cdk-testing/cli-integ/resources/cdk-apps/app/appsync.hotswap.graphql
  packages/@aws-cdk-testing/cli-integ/tests/cli-integ-tests/cli.integtest.ts
  packages/aws-cdk/lib/api/hotswap/appsync-mapping-templates.ts
  packages/aws-cdk/test/api/hotswap/appsync-mapping-templates-hotswap-deployments.test.ts
Labels: p2, pr-linter/exempt-integ-test, beginning-contributor, pr-linter/cli-integ-tested

#31464 chore(vpcv2): fix doc issue due to IRoute
  packages/@aws-cdk/aws-ec2-alpha/lib/route.ts
Labels: p2, contribution/core

#31476 chore: add 1kaileychen to mergify and merit badger
  .github/workflows/github-merit-badger.yml
  .mergify.yml
Labels: p2, beginning-contributor

#31484 feat: update L1 CloudFormation resource definitions
  packages/@aws-cdk/cloudformation-diff/package.json
  packages/@aws-cdk/integ-runner/package.json
  packages/aws-cdk-lib/package.json
  tools/@aws-cdk/spec2cdk/package.json
  yarn.lock
Labels: p2, dependencies, contribution/core, pr-linter/exempt-readme, pr-linter/exempt-test, auto-approve, pr-linter/exempt-integ-test

#31349 feat(kinesisanalytics-flink): support Apache Flink 1.20
  packages/@aws-cdk/aws-kinesisanalytics-flink-alpha/README.md
  packages/@aws-cdk/aws-kinesisanalytics-flink-alpha/lib/types.ts
  packages/@aws-cdk/aws-kinesisanalytics-flink-alpha/test/application.test.ts
  packages/@aws-cdk/aws-kinesisanalytics-flink-alpha/test/integ.application.lit.js.snapshot/ApplicationTestDefaultTestDeployAssertF9C5F731.assets.json
  packages/@aws-cdk/aws-kinesisanalytics-flink-alpha/test/integ.application.lit.js.snapshot/ApplicationTestDefaultTestDeployAssertF9C5F731.template.json
  packages/@aws-cdk/aws-kinesisanalytics-flink-alpha/test/integ.application.lit.js.snapshot/FlinkAppTest.assets.json
  packages/@aws-cdk/aws-kinesisanalytics-flink-alpha/test/integ.application.lit.js.snapshot/FlinkAppTest.template.json
  packages/@aws-cdk/aws-kinesisanalytics-flink-alpha/test/integ.application.lit.js.snapshot/cdk.out
  packages/@aws-cdk/aws-kinesisanalytics-flink-alpha/test/integ.application.lit.js.snapshot/integ.json
  packages/@aws-cdk/aws-kinesisanalytics-flink-alpha/test/integ.application.lit.js.snapshot/manifest.json
  packages/@aws-cdk/aws-kinesisanalytics-flink-alpha/test/integ.application.lit.js.snapshot/tree.json
  packages/@aws-cdk/aws-kinesisanalytics-flink-alpha/test/integ.application.lit.ts
Labels: p2, distinguished-contributor

#31441 chore(ec2): invalid Interface VPC Endpoints
  packages/aws-cdk-lib/aws-ec2/lib/vpc-endpoint.ts
Labels: p2, distinguished-contributor, pr-linter/exemption-requested

#30421 fix(cognito-identitypool-alpha): cannot configure roleMappings with imported userPool and client
  packages/@aws-cdk/aws-cognito-identitypool-alpha/lib/identitypool.ts
  packages/@aws-cdk/aws-cognito-identitypool-alpha/test/identitypool.test.ts
  packages/@aws-cdk/aws-cognito-identitypool-alpha/test/integ.identitypool.js.snapshot/cdk.out
  packages/@aws-cdk/aws-cognito-identitypool-alpha/test/integ.identitypool.js.snapshot/integ-identitypool.assets.json
  packages/@aws-cdk/aws-cognito-identitypool-alpha/test/integ.identitypool.js.snapshot/integ-identitypool.template.json
  packages/@aws-cdk/aws-cognito-identitypool-alpha/test/integ.identitypool.js.snapshot/integ.json
  packages/@aws-cdk/aws-cognito-identitypool-alpha/test/integ.identitypool.js.snapshot/manifest.json
  packages/@aws-cdk/aws-cognito-identitypool-alpha/test/integ.identitypool.js.snapshot/tree.json
  packages/@aws-cdk/aws-cognito-identitypool-alpha/test/integ.identitypool.ts
  packages/aws-cdk-lib/aws-cognito/lib/user-pool.ts
  packages/aws-cdk-lib/aws-cognito/test/user-pool.test.ts
Labels: bug, p2, effort/medium, star-contributor

#31477 chore(ec2): add GuardDuty Interface VPC Endpoint
  packages/aws-cdk-lib/aws-ec2/lib/vpc-endpoint.ts
Labels: p2, pr/needs-community-review, distinguished-contributor

#31489 chore(merge-back): 2.159.0
  CHANGELOG.v2.alpha.md
  CHANGELOG.v2.md
  packages/aws-cdk-lib/cx-api/FEATURE_FLAGS.md
  packages/aws-cdk-lib/cx-api/lib/features.ts
  version.v2.json
Labels: p2, pr/needs-community-review, pr/no-squash, auto-approve

#31496 revert: fix(ec2): fixing vpc endpoint pattern for ecr and ecr docker
  packages/aws-cdk-lib/aws-ec2/lib/vpc-endpoint.ts
  packages/aws-cdk-lib/aws-ec2/test/vpc-endpoint.test.ts
Labels: bug, p0, contribution/core, pr-linter/exempt-test, pr-linter/exemption-requested

#31498 chore(release): 2.159.1
  CHANGELOG.v2.alpha.md
  CHANGELOG.v2.md
  packages/aws-cdk-lib/aws-ec2/lib/vpc-endpoint.ts
  packages/aws-cdk-lib/aws-ec2/test/vpc-endpoint.test.ts
  version.v2.json
Labels: p2, contribution/core, pr/no-squash

#31500 chore(lambda): improve the doc about the code signing in Lambda
  packages/aws-cdk-lib/aws-lambda/README.md
Labels: bug, p2, @aws-cdk/aws-lambda, effort/medium, contribution/core

#31495 chore(ec2): add Serverless Application Repository Interface VPC Endpoint
  packages/aws-cdk-lib/aws-ec2/lib/vpc-endpoint.ts
Labels: p2, distinguished-contributor

#31503 chore(merge-back): 2.159.1
  CHANGELOG.v2.alpha.md
  CHANGELOG.v2.md
  version.v2.json
Labels: p2, pr/needs-community-review, pr/no-squash, auto-approve

#31491 chore(rds): support minor versions for RDS for SQL Server
  packages/aws-cdk-lib/aws-rds/lib/instance-engine.ts
Labels: p2, distinguished-contributor

#31504 chore(ec2): add Compute Optimizer Interface VPC Endpoint
  packages/aws-cdk-lib/aws-ec2/lib/vpc-endpoint.ts
Labels: p2, beginning-contributor, pr/needs-maintainer-review

#31473 docs(hotswap): remove un-needed newline in comment
  packages/aws-cdk/lib/api/hotswap-deployments.ts
Labels: p2, pr-linter/exempt-test, beginning-contributor, pr-linter/cli-integ-tested

#30959 feat(stepfunctions): add support for EncryptionConfiguration
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions/test/integ.state-machine-and-activity-cmk.js.snapshot/StateMachineAndActivityWithCMKEncryptionConfigurationDefaultTestDeployAssert11207853.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions/test/integ.state-machine-and-activity-cmk.js.snapshot/StateMachineAndActivityWithCMKEncryptionConfigurationDefaultTestDeployAssert11207853.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions/test/integ.state-machine-and-activity-cmk.js.snapshot/asset.3cef2cdbb46b3821e641ffb8b9af9731af5f7e4a9e857ab633dbcd9023de724d.bundle/index.js
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions/test/integ.state-machine-and-activity-cmk.js.snapshot/aws-stepfunctions-statemachine-and-activity-with-cmk-encryptionconfig.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions/test/integ.state-machine-and-activity-cmk.js.snapshot/aws-stepfunctions-statemachine-and-activity-with-cmk-encryptionconfig.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions/test/integ.state-machine-and-activity-cmk.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions/test/integ.state-machine-and-activity-cmk.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions/test/integ.state-machine-and-activity-cmk.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions/test/integ.state-machine-and-activity-cmk.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions/test/integ.state-machine-and-activity-cmk.ts
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions/test/integ.state-machine-cmk-with-cwl-encryption.js.snapshot/StateMachineAndActivityWithCMKEncryptionConfigurationDefaultTestDeployAssert11207853.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions/test/integ.state-machine-cmk-with-cwl-encryption.js.snapshot/StateMachineAndActivityWithCMKEncryptionConfigurationDefaultTestDeployAssert11207853.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions/test/integ.state-machine-cmk-with-cwl-encryption.js.snapshot/asset.3cef2cdbb46b3821e641ffb8b9af9731af5f7e4a9e857ab633dbcd9023de724d.bundle/index.js
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions/test/integ.state-machine-cmk-with-cwl-encryption.js.snapshot/aws-stepfunctions-statemachine-and-activity-with-cmk-encryptionconfig.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions/test/integ.state-machine-cmk-with-cwl-encryption.js.snapshot/aws-stepfunctions-statemachine-and-activity-with-cmk-encryptionconfig.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions/test/integ.state-machine-cmk-with-cwl-encryption.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions/test/integ.state-machine-cmk-with-cwl-encryption.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions/test/integ.state-machine-cmk-with-cwl-encryption.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions/test/integ.state-machine-cmk-with-cwl-encryption.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions/test/integ.state-machine-cmk-with-cwl-encryption.ts
  packages/aws-cdk-lib/aws-stepfunctions-tasks/lib/stepfunctions/invoke-activity.ts
  packages/aws-cdk-lib/aws-stepfunctions/README.md
  packages/aws-cdk-lib/aws-stepfunctions/lib/activity.ts
  packages/aws-cdk-lib/aws-stepfunctions/lib/aws-owned-key-encryption-configuration.ts
  packages/aws-cdk-lib/aws-stepfunctions/lib/customer-managed-key-encryption-configuration.ts
  packages/aws-cdk-lib/aws-stepfunctions/lib/encryption-configuration.ts
  packages/aws-cdk-lib/aws-stepfunctions/lib/index.ts
  packages/aws-cdk-lib/aws-stepfunctions/lib/private/util.ts
  packages/aws-cdk-lib/aws-stepfunctions/lib/state-machine.ts
  packages/aws-cdk-lib/aws-stepfunctions/lib/states/task.ts
  packages/aws-cdk-lib/aws-stepfunctions/lib/util.ts
  packages/aws-cdk-lib/aws-stepfunctions/test/activity.test.ts
  packages/aws-cdk-lib/aws-stepfunctions/test/state-machine.test.ts
Labels: p2, @aws-cdk/aws-stepfunctions, beginning-contributor

#31107 feat(core): configure Stack SNS notification ARNs on the Stack construct
  packages/@aws-cdk-testing/cli-integ/resources/cdk-apps/app/app.js
  packages/@aws-cdk-testing/cli-integ/tests/cli-integ-tests/cli.integtest.ts
  packages/@aws-cdk/cx-api/FEATURE_FLAGS.md
  packages/@aws-cdk/cx-api/package.json
  packages/@aws-cdk/integ-runner/package.json
  packages/aws-cdk-lib/core/README.md
  packages/aws-cdk-lib/core/lib/stack-synthesizers/_shared.ts
  packages/aws-cdk-lib/core/lib/stack.ts
  packages/aws-cdk-lib/core/test/stack.test.ts
  packages/aws-cdk-lib/cx-api/lib/artifacts/cloudformation-artifact.ts
  packages/aws-cdk-lib/cx-api/test/stack-artifact.test.ts
  packages/aws-cdk-lib/package.json
  packages/aws-cdk/lib/api/deploy-stack.ts
  packages/aws-cdk/lib/api/util/cloudformation.ts
  packages/aws-cdk/lib/cdk-toolkit.ts
  packages/aws-cdk/package.json
  packages/aws-cdk/test/api/deploy-stack.test.ts
  packages/aws-cdk/test/cdk-toolkit.test.ts
  packages/aws-cdk/test/util.ts
  yarn.lock
Labels: p1, contribution/core, pr-linter/exempt-integ-test, pr-linter/cli-integ-tested

#31534 feat: update L1 CloudFormation resource definitions
  yarn.lock
Labels: p2, dependencies, contribution/core, pr-linter/exempt-readme, pr-linter/exempt-test, auto-approve, pr-linter/exempt-integ-test

#31506 chore: advanced CodeQL configuration
  .github/workflows/codeql.yml
Labels: p2, contribution/core

#31539 fix: update L1 CloudFormation resource definitions by removing outdated schema overrides
  tools/@aws-cdk/spec2cdk/temporary-schemas/us-east-1/aws-ecs-capacityprovider.json
  tools/@aws-cdk/spec2cdk/temporary-schemas/us-east-1/aws-lambda-eventsourcemapping.json
  tools/@aws-cdk/spec2cdk/temporary-schemas/us-east-1/aws-lambda-function-recursive-loop.json
Labels: p2, contribution/core, pr-linter/exempt-test, pr-linter/exempt-integ-test

#31228 feat(ecs): support restart policy for container
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs/test/base/integ.task-definition-container-restart-policy.js.snapshot/TaskDefinitionContainerRestartPolicyDefaultTestDeployAssert2196C660.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs/test/base/integ.task-definition-container-restart-policy.js.snapshot/TaskDefinitionContainerRestartPolicyDefaultTestDeployAssert2196C660.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs/test/base/integ.task-definition-container-restart-policy.js.snapshot/aws-ecs-task-definition-container-restart-policy.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs/test/base/integ.task-definition-container-restart-policy.js.snapshot/aws-ecs-task-definition-container-restart-policy.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs/test/base/integ.task-definition-container-restart-policy.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs/test/base/integ.task-definition-container-restart-policy.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs/test/base/integ.task-definition-container-restart-policy.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs/test/base/integ.task-definition-container-restart-policy.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs/test/base/integ.task-definition-container-restart-policy.ts
  packages/aws-cdk-lib/aws-ecs/README.md
  packages/aws-cdk-lib/aws-ecs/lib/container-definition.ts
  packages/aws-cdk-lib/aws-ecs/test/container-definition.test.ts
Labels: p2, feature-request, effort/small, distinguished-contributor

#31488 chore(kinesisfirehose-destinations): refactor logging to combine logGroup and logging properties into loggingConfig
  packages/@aws-cdk/aws-kinesisfirehose-alpha/README.md
  packages/@aws-cdk/aws-kinesisfirehose-destinations-alpha/lib/common.ts
  packages/@aws-cdk/aws-kinesisfirehose-destinations-alpha/lib/index.ts
  packages/@aws-cdk/aws-kinesisfirehose-destinations-alpha/lib/logging-config.ts
  packages/@aws-cdk/aws-kinesisfirehose-destinations-alpha/lib/private/helpers.ts
  packages/@aws-cdk/aws-kinesisfirehose-destinations-alpha/lib/s3-bucket.ts
  packages/@aws-cdk/aws-kinesisfirehose-destinations-alpha/test/integ.s3-bucket.lit.ts
  packages/@aws-cdk/aws-kinesisfirehose-destinations-alpha/test/s3-bucket.test.ts
Labels: p2, contribution/core, pr/needs-maintainer-review

#31553 chore(merge-back): 2.160.0
  CHANGELOG.v2.alpha.md
  CHANGELOG.v2.md
  packages/aws-cdk-lib/cx-api/FEATURE_FLAGS.md
  packages/aws-cdk-lib/cx-api/lib/features.ts
  version.v2.json
Labels: p2, pr/needs-community-review, pr/no-squash, auto-approve

#31340 fix(lambda): configuring log retention fails on 70+ Lambdas
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda/test/integ.log-retention.js.snapshot/LambdaLogRetentionIntegDefaultTestDeployAssert90E53934.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda/test/integ.log-retention.js.snapshot/asset.c9e084a249774d97a978bed2e1976874a70517128a904136b8737f0792322c1f/index.js
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda/test/integ.log-retention.js.snapshot/asset.e4afb15788ec44ed9ff3377e1d131ba2768d7b2e2931bc000d1f2005879b3035/index.js
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda/test/integ.log-retention.js.snapshot/aws-cdk-lambda-log-retention.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda/test/integ.log-retention.js.snapshot/aws-cdk-lambda-log-retention.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda/test/integ.log-retention.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda/test/integ.log-retention.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda/test/integ.log-retention.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-logs/test/integ.log-retention.js.snapshot/LogRetentionIntegDefaultTestDeployAssert6ACC5A74.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-logs/test/integ.log-retention.js.snapshot/asset.c9e084a249774d97a978bed2e1976874a70517128a904136b8737f0792322c1f/index.js
  packages/@aws-cdk-testing/framework-integ/test/aws-logs/test/integ.log-retention.js.snapshot/asset.e4afb15788ec44ed9ff3377e1d131ba2768d7b2e2931bc000d1f2005879b3035/index.js
  packages/@aws-cdk-testing/framework-integ/test/aws-logs/test/integ.log-retention.js.snapshot/aws-cdk-log-retention-integ.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-logs/test/integ.log-retention.js.snapshot/aws-cdk-log-retention-integ.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-logs/test/integ.log-retention.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-logs/test/integ.log-retention.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-logs/test/integ.log-retention.js.snapshot/manifest.json
  packages/@aws-cdk/custom-resource-handlers/lib/aws-logs/log-retention-handler/index.ts
  packages/@aws-cdk/custom-resource-handlers/test/aws-logs/log-retention-handler.test.ts
Labels: bug, p2, effort/medium, contribution/core, pr-linter/exempt-integ-test

#31457 fix(stack): check stack tags for deploy-time values
  packages/aws-cdk-lib/core/lib/stack-synthesizers/_shared.ts
  packages/aws-cdk-lib/core/test/stack.test.ts
Labels: bug, p1, effort/medium, contribution/core, pr-linter/exempt-integ-test, pr/needs-maintainer-review

#31328 fix(pipelines): "Node with duplicate id" on duplicate stack names
  packages/aws-cdk-lib/pipelines/lib/helpers-internal/graph.ts
  packages/aws-cdk-lib/pipelines/lib/helpers-internal/pipeline-graph.ts
  packages/aws-cdk-lib/pipelines/test/compliance/basic-behavior.test.ts
Labels: contribution/core, pr-linter/exempt-integ-test

#31535 feat(logs): add metric methods for log group IncomingLogEvents and IncomingBytes
  packages/@aws-cdk-testing/framework-integ/test/aws-logs/test/integ.log-group-metrics.js.snapshot/LogGroupMetricsDefaultTestDeployAssertF61C3BCA.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-logs/test/integ.log-group-metrics.js.snapshot/LogGroupMetricsDefaultTestDeployAssertF61C3BCA.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-logs/test/integ.log-group-metrics.js.snapshot/aws-cdk-log-group-metrics.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-logs/test/integ.log-group-metrics.js.snapshot/aws-cdk-log-group-metrics.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-logs/test/integ.log-group-metrics.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-logs/test/integ.log-group-metrics.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-logs/test/integ.log-group-metrics.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-logs/test/integ.log-group-metrics.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-logs/test/integ.log-group-metrics.ts
  packages/aws-cdk-lib/aws-events-targets/test/logs/log-group.test.ts
  packages/aws-cdk-lib/aws-logs/README.md
  packages/aws-cdk-lib/aws-logs/lib/log-group.ts
Labels: p2, feature-request, effort/small, contribution/core

#30186 fix(cdk): `cdk diff --quiet` to print stack name when there is diffs
  packages/aws-cdk/lib/cdk-toolkit.ts
  packages/aws-cdk/lib/diff.ts
  packages/aws-cdk/test/diff.test.ts
Labels: bug, p1, effort/small, pr-linter/exempt-integ-test, star-contributor, pr-linter/cli-integ-tested

#31389 fix(cli): deployment errors are printed 3 times
  packages/@aws-cdk-testing/cli-integ/lib/with-cdk-app.ts
  packages/@aws-cdk-testing/cli-integ/resources/cli-regression-patches/v2.160.0/skip-tests.txt
  packages/@aws-cdk-testing/cli-integ/skip-tests.txt
  packages/@aws-cdk-testing/cli-integ/tests/cli-integ-tests/cli-lib.integtest.ts
  packages/@aws-cdk-testing/cli-integ/tests/cli-integ-tests/cli.integtest.ts
  packages/aws-cdk/lib/api/deployments.ts
  packages/aws-cdk/lib/cdk-toolkit.ts
Labels: p2, contribution/core, pr-linter/exempt-test, pr-linter/exempt-integ-test, pr-linter/cli-integ-tested

#31568 feat(bedrock): support meta llama3-2
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/bedrock/integ.invoke-model.js.snapshot/InvokeModelDefaultTestDeployAssert9C0D2DFC.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/bedrock/integ.invoke-model.js.snapshot/aws-stepfunctions-tasks-bedrock-invoke-model-integ.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/bedrock/integ.invoke-model.js.snapshot/aws-stepfunctions-tasks-bedrock-invoke-model-integ.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/bedrock/integ.invoke-model.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/bedrock/integ.invoke-model.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/bedrock/integ.invoke-model.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/bedrock/integ.invoke-model.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/bedrock/integ.invoke-model.ts
  packages/aws-cdk-lib/aws-bedrock/lib/foundation-model.ts
Labels: p2, pr/needs-community-review, pr-linter/exempt-readme, distinguished-contributor

#31482 chore(cognito-identitypool): refactor and remove Digits authentication provider
  packages/@aws-cdk/aws-cognito-identitypool-alpha/README.md
  packages/@aws-cdk/aws-cognito-identitypool-alpha/lib/identitypool-role-attachment.ts
  packages/@aws-cdk/aws-cognito-identitypool-alpha/lib/identitypool.ts
  packages/@aws-cdk/aws-cognito-identitypool-alpha/test/identitypool.test.ts
  packages/@aws-cdk/aws-cognito-identitypool-alpha/test/integ.identitypool.js.snapshot/integ-identitypool.assets.json
  packages/@aws-cdk/aws-cognito-identitypool-alpha/test/integ.identitypool.js.snapshot/integ-identitypool.template.json
  packages/@aws-cdk/aws-cognito-identitypool-alpha/test/integ.identitypool.js.snapshot/manifest.json
  packages/@aws-cdk/aws-cognito-identitypool-alpha/test/integ.identitypool.js.snapshot/tree.json
  packages/@aws-cdk/aws-cognito-identitypool-alpha/test/integ.identitypool.ts
Labels: p2, contribution/core, pr-linter/exemption-requested

#31524 feat(rds): support for local write forwarding in an Aurora Mysql cluster
  packages/@aws-cdk-testing/framework-integ/test/aws-rds/test/integ.cluster-enable-local-write-forwarding.js.snapshot/EnableLocalWriteForwardingClusterStack.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-rds/test/integ.cluster-enable-local-write-forwarding.js.snapshot/EnableLocalWriteForwardingClusterStack.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-rds/test/integ.cluster-enable-local-write-forwarding.js.snapshot/EnableLocalWriteForwardingClusterStackIntegDefaultTestDeployAssertFA53AD26.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-rds/test/integ.cluster-enable-local-write-forwarding.js.snapshot/EnableLocalWriteForwardingClusterStackIntegDefaultTestDeployAssertFA53AD26.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-rds/test/integ.cluster-enable-local-write-forwarding.js.snapshot/asset.bde7b5c89cb43285f884c94f0b9e17cdb0f5eb5345005114dd60342e0b8a85a1/__entrypoint__.js
  packages/@aws-cdk-testing/framework-integ/test/aws-rds/test/integ.cluster-enable-local-write-forwarding.js.snapshot/asset.bde7b5c89cb43285f884c94f0b9e17cdb0f5eb5345005114dd60342e0b8a85a1/index.js
  packages/@aws-cdk-testing/framework-integ/test/aws-rds/test/integ.cluster-enable-local-write-forwarding.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-rds/test/integ.cluster-enable-local-write-forwarding.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-rds/test/integ.cluster-enable-local-write-forwarding.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-rds/test/integ.cluster-enable-local-write-forwarding.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-rds/test/integ.cluster-enable-local-write-forwarding.ts
  packages/aws-cdk-lib/aws-rds/README.md
  packages/aws-cdk-lib/aws-rds/lib/cluster.ts
  packages/aws-cdk-lib/aws-rds/test/cluster.test.ts
Labels: p2, feature-request, distinguished-contributor

#29476 feat(pipes-sources): add Kinesis and DynamoDB
  packages/@aws-cdk/aws-pipes-alpha/lib/pipe.ts
  packages/@aws-cdk/aws-pipes-alpha/lib/source.ts
  packages/@aws-cdk/aws-pipes-alpha/test/pipe.test.ts
  packages/@aws-cdk/aws-pipes-alpha/test/test-classes.ts
  packages/@aws-cdk/aws-pipes-sources-alpha/README.md
  packages/@aws-cdk/aws-pipes-sources-alpha/lib/dynamodb.ts
  packages/@aws-cdk/aws-pipes-sources-alpha/lib/enums.ts
  packages/@aws-cdk/aws-pipes-sources-alpha/lib/index.ts
  packages/@aws-cdk/aws-pipes-sources-alpha/lib/kinesis.ts
  packages/@aws-cdk/aws-pipes-sources-alpha/lib/streamSource.ts
  packages/@aws-cdk/aws-pipes-sources-alpha/rosetta/default.ts-fixture
  packages/@aws-cdk/aws-pipes-sources-alpha/test/__snapshots__/dynamodb.test.ts.snap
  packages/@aws-cdk/aws-pipes-sources-alpha/test/__snapshots__/kinesis.test.ts.snap
  packages/@aws-cdk/aws-pipes-sources-alpha/test/__snapshots__/streamSource.test.ts.snap
  packages/@aws-cdk/aws-pipes-sources-alpha/test/dynamodb.test.ts
  packages/@aws-cdk/aws-pipes-sources-alpha/test/integ.dynamodb.js.snapshot/asset.310f432b946edeef3316f39f32b344b6bdc401a3b438433db42adadab1bf5e17.bundle/index.js
  packages/@aws-cdk/aws-pipes-sources-alpha/test/integ.dynamodb.js.snapshot/aws-cdk-pipes-sources-dynamodb.assets.json
  packages/@aws-cdk/aws-pipes-sources-alpha/test/integ.dynamodb.js.snapshot/aws-cdk-pipes-sources-dynamodb.template.json
  packages/@aws-cdk/aws-pipes-sources-alpha/test/integ.dynamodb.js.snapshot/cdk.out
  packages/@aws-cdk/aws-pipes-sources-alpha/test/integ.dynamodb.js.snapshot/integ.json
  packages/@aws-cdk/aws-pipes-sources-alpha/test/integ.dynamodb.js.snapshot/integtestpipesourcedynamodbDefaultTestDeployAssertD62992D6.assets.json
  packages/@aws-cdk/aws-pipes-sources-alpha/test/integ.dynamodb.js.snapshot/integtestpipesourcedynamodbDefaultTestDeployAssertD62992D6.template.json
  packages/@aws-cdk/aws-pipes-sources-alpha/test/integ.dynamodb.js.snapshot/manifest.json
  packages/@aws-cdk/aws-pipes-sources-alpha/test/integ.dynamodb.js.snapshot/tree.json
  packages/@aws-cdk/aws-pipes-sources-alpha/test/integ.dynamodb.ts
  packages/@aws-cdk/aws-pipes-sources-alpha/test/integ.kinesis.js.snapshot/asset.cfdb46b4f2c6702b4a1cc8e23ca426e8de43d13567e73a8453d01c1176393814.bundle/index.js
  packages/@aws-cdk/aws-pipes-sources-alpha/test/integ.kinesis.js.snapshot/aws-cdk-pipes-sources-kinesis.assets.json
  packages/@aws-cdk/aws-pipes-sources-alpha/test/integ.kinesis.js.snapshot/aws-cdk-pipes-sources-kinesis.template.json
  packages/@aws-cdk/aws-pipes-sources-alpha/test/integ.kinesis.js.snapshot/cdk.out
  packages/@aws-cdk/aws-pipes-sources-alpha/test/integ.kinesis.js.snapshot/integ.json
  packages/@aws-cdk/aws-pipes-sources-alpha/test/integ.kinesis.js.snapshot/integtestpipesourcekinesisDefaultTestDeployAssert6F0A38D7.assets.json
  packages/@aws-cdk/aws-pipes-sources-alpha/test/integ.kinesis.js.snapshot/integtestpipesourcekinesisDefaultTestDeployAssert6F0A38D7.template.json
  packages/@aws-cdk/aws-pipes-sources-alpha/test/integ.kinesis.js.snapshot/manifest.json
  packages/@aws-cdk/aws-pipes-sources-alpha/test/integ.kinesis.js.snapshot/tree.json
  packages/@aws-cdk/aws-pipes-sources-alpha/test/integ.kinesis.ts
  packages/@aws-cdk/aws-pipes-sources-alpha/test/kinesis.test.ts
  packages/@aws-cdk/aws-pipes-sources-alpha/test/streamSource.test.ts
Labels: p2, feature-request, star-contributor, pr/needs-maintainer-review

#30563 feat(redshift): supports excludeCharacters settings for DatabaseSecret
  packages/@aws-cdk/aws-redshift-alpha/README.md
  packages/@aws-cdk/aws-redshift-alpha/lib/cluster.ts
  packages/@aws-cdk/aws-redshift-alpha/lib/database-secret.ts
  packages/@aws-cdk/aws-redshift-alpha/lib/user.ts
  packages/@aws-cdk/aws-redshift-alpha/test/cluster.test.ts
  packages/@aws-cdk/aws-redshift-alpha/test/integ.cluster-exclude-characters.js.snapshot/ExcludeCharactersIntegDefaultTestDeployAssertF357433F.assets.json
  packages/@aws-cdk/aws-redshift-alpha/test/integ.cluster-exclude-characters.js.snapshot/ExcludeCharactersIntegDefaultTestDeployAssertF357433F.template.json
  packages/@aws-cdk/aws-redshift-alpha/test/integ.cluster-exclude-characters.js.snapshot/asset.46fb886516825167db3571f1ed91110fc6163ce20ee26fdb097c2c983f25fcd6/cfn-response.js
  packages/@aws-cdk/aws-redshift-alpha/test/integ.cluster-exclude-characters.js.snapshot/asset.46fb886516825167db3571f1ed91110fc6163ce20ee26fdb097c2c983f25fcd6/consts.js
  packages/@aws-cdk/aws-redshift-alpha/test/integ.cluster-exclude-characters.js.snapshot/asset.46fb886516825167db3571f1ed91110fc6163ce20ee26fdb097c2c983f25fcd6/framework.js
  packages/@aws-cdk/aws-redshift-alpha/test/integ.cluster-exclude-characters.js.snapshot/asset.46fb886516825167db3571f1ed91110fc6163ce20ee26fdb097c2c983f25fcd6/outbound.js
  packages/@aws-cdk/aws-redshift-alpha/test/integ.cluster-exclude-characters.js.snapshot/asset.46fb886516825167db3571f1ed91110fc6163ce20ee26fdb097c2c983f25fcd6/util.js
  packages/@aws-cdk/aws-redshift-alpha/test/integ.cluster-exclude-characters.js.snapshot/asset.6bdd909f81c84ffe7d00cf4d6a2dbac8606429bcc05b0db3da842c1941a532f2/handler-name.js
  packages/@aws-cdk/aws-redshift-alpha/test/integ.cluster-exclude-characters.js.snapshot/asset.6bdd909f81c84ffe7d00cf4d6a2dbac8606429bcc05b0db3da842c1941a532f2/index.js
  packages/@aws-cdk/aws-redshift-alpha/test/integ.cluster-exclude-characters.js.snapshot/asset.6bdd909f81c84ffe7d00cf4d6a2dbac8606429bcc05b0db3da842c1941a532f2/privileges.js
  packages/@aws-cdk/aws-redshift-alpha/test/integ.cluster-exclude-characters.js.snapshot/asset.6bdd909f81c84ffe7d00cf4d6a2dbac8606429bcc05b0db3da842c1941a532f2/redshift-data.js
  packages/@aws-cdk/aws-redshift-alpha/test/integ.cluster-exclude-characters.js.snapshot/asset.6bdd909f81c84ffe7d00cf4d6a2dbac8606429bcc05b0db3da842c1941a532f2/table.js
  packages/@aws-cdk/aws-redshift-alpha/test/integ.cluster-exclude-characters.js.snapshot/asset.6bdd909f81c84ffe7d00cf4d6a2dbac8606429bcc05b0db3da842c1941a532f2/types.js
  packages/@aws-cdk/aws-redshift-alpha/test/integ.cluster-exclude-characters.js.snapshot/asset.6bdd909f81c84ffe7d00cf4d6a2dbac8606429bcc05b0db3da842c1941a532f2/user.js
  packages/@aws-cdk/aws-redshift-alpha/test/integ.cluster-exclude-characters.js.snapshot/asset.6bdd909f81c84ffe7d00cf4d6a2dbac8606429bcc05b0db3da842c1941a532f2/util.js
  packages/@aws-cdk/aws-redshift-alpha/test/integ.cluster-exclude-characters.js.snapshot/cdk.out
  packages/@aws-cdk/aws-redshift-alpha/test/integ.cluster-exclude-characters.js.snapshot/integ.json
  packages/@aws-cdk/aws-redshift-alpha/test/integ.cluster-exclude-characters.js.snapshot/manifest.json
  packages/@aws-cdk/aws-redshift-alpha/test/integ.cluster-exclude-characters.js.snapshot/redshift-exclude-characters-integ.assets.json
  packages/@aws-cdk/aws-redshift-alpha/test/integ.cluster-exclude-characters.js.snapshot/redshift-exclude-characters-integ.template.json
  packages/@aws-cdk/aws-redshift-alpha/test/integ.cluster-exclude-characters.js.snapshot/tree.json
  packages/@aws-cdk/aws-redshift-alpha/test/integ.cluster-exclude-characters.ts
  packages/@aws-cdk/aws-redshift-alpha/test/user.test.ts
Labels: p2, feature-request, effort/medium, star-contributor

#31537 chore(bedrock): support Jamba 1.5 Large and Mini
  packages/aws-cdk-lib/aws-bedrock/lib/foundation-model.ts
Labels: p2, distinguished-contributor

#31579 fix(rds): fixed the IAM policy that grantConnect() generates for DatabaseInstanceReadReplica
  packages/@aws-cdk-testing/framework-integ/test/aws-rds/test/integ.read-replica.js.snapshot/cdk-rds-read-replica.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-rds/test/integ.read-replica.js.snapshot/cdk-rds-read-replica.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-rds/test/integ.read-replica.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-rds/test/integ.read-replica.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-rds/test/integ.read-replica.ts
  packages/aws-cdk-lib/aws-rds/lib/instance.ts
  packages/aws-cdk-lib/aws-rds/test/instance.test.ts
  packages/aws-cdk-lib/cx-api/FEATURE_FLAGS.md
  packages/aws-cdk-lib/cx-api/README.md
  packages/aws-cdk-lib/cx-api/lib/features.ts
Labels: bug, p2, effort/small, contribution/core

#31567 fix(appsync): lambda authorizer permission is not scoped to appsync api arn
  packages/@aws-cdk-testing/framework-integ/test/aws-appsync/test/integ.graphql-lambda-permission.graphql
  packages/@aws-cdk-testing/framework-integ/test/aws-appsync/test/integ.graphql-lambda-permission.js.snapshot/GraphqlApiLambdaPermissionTestDefaultTestDeployAssert7720B39B.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-appsync/test/integ.graphql-lambda-permission.js.snapshot/GraphqlApiLambdaPermissionTestDefaultTestDeployAssert7720B39B.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-appsync/test/integ.graphql-lambda-permission.js.snapshot/aws-graphql-lambda-permissions.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-appsync/test/integ.graphql-lambda-permission.js.snapshot/aws-graphql-lambda-permissions.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-appsync/test/integ.graphql-lambda-permission.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-appsync/test/integ.graphql-lambda-permission.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-appsync/test/integ.graphql-lambda-permission.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-appsync/test/integ.graphql-lambda-permission.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-appsync/test/integ.graphql-lambda-permission.ts
  packages/@aws-cdk-testing/framework-integ/test/aws-appsync/test/integ.lambda-auth.ts
  packages/aws-cdk-lib/aws-appsync/lib/graphqlapi.ts
  packages/aws-cdk-lib/aws-appsync/test/appsync-auth.test.ts
  packages/aws-cdk-lib/cx-api/FEATURE_FLAGS.md
  packages/aws-cdk-lib/cx-api/README.md
  packages/aws-cdk-lib/cx-api/lib/features.ts
Labels: bug, p1, contribution/core, pr/needs-maintainer-review

#31545 chore(ecs): add integ test for ECS with Windows use case
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs/test/integ.cluster-windows-server-ami.js.snapshot/ClusterWindowsServerDefaultTestDeployAssertC6412DEB.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs/test/integ.cluster-windows-server-ami.js.snapshot/ClusterWindowsServerDefaultTestDeployAssertC6412DEB.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs/test/integ.cluster-windows-server-ami.js.snapshot/asset.bde7b5c89cb43285f884c94f0b9e17cdb0f5eb5345005114dd60342e0b8a85a1/__entrypoint__.js
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs/test/integ.cluster-windows-server-ami.js.snapshot/asset.bde7b5c89cb43285f884c94f0b9e17cdb0f5eb5345005114dd60342e0b8a85a1/index.js
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs/test/integ.cluster-windows-server-ami.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs/test/integ.cluster-windows-server-ami.js.snapshot/integ-ecs-windows-server-ami.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs/test/integ.cluster-windows-server-ami.js.snapshot/integ-ecs-windows-server-ami.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs/test/integ.cluster-windows-server-ami.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs/test/integ.cluster-windows-server-ami.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs/test/integ.cluster-windows-server-ami.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs/test/integ.cluster-windows-server-ami.ts
Labels: p2, contribution/core

#31587 chore(logs): fix for yarn build warning from log-group doc string
  packages/aws-cdk-lib/aws-logs/lib/log-group.ts
Labels: p2, contribution/core

#30756 feat(pipes-targets): add API destination
  packages/@aws-cdk/aws-pipes-targets-alpha/README.md
  packages/@aws-cdk/aws-pipes-targets-alpha/lib/api-destination.ts
  packages/@aws-cdk/aws-pipes-targets-alpha/lib/index.ts
  packages/@aws-cdk/aws-pipes-targets-alpha/rosetta/default.ts-fixture
  packages/@aws-cdk/aws-pipes-targets-alpha/test/api-destination.test.ts
  packages/@aws-cdk/aws-pipes-targets-alpha/test/integ.api-destination.js.snapshot/asset.c9e084a249774d97a978bed2e1976874a70517128a904136b8737f0792322c1f/index.js
  packages/@aws-cdk/aws-pipes-targets-alpha/test/integ.api-destination.js.snapshot/asset.da514df694ce3f41453746a766ae6aff13c869c38002598930d6d34e5711985b.bundle/index.js
  packages/@aws-cdk/aws-pipes-targets-alpha/test/integ.api-destination.js.snapshot/aws-cdk-pipes-targets-api-dest.assets.json
  packages/@aws-cdk/aws-pipes-targets-alpha/test/integ.api-destination.js.snapshot/aws-cdk-pipes-targets-api-dest.template.json
  packages/@aws-cdk/aws-pipes-targets-alpha/test/integ.api-destination.js.snapshot/cdk.out
  packages/@aws-cdk/aws-pipes-targets-alpha/test/integ.api-destination.js.snapshot/integ.json
  packages/@aws-cdk/aws-pipes-targets-alpha/test/integ.api-destination.js.snapshot/integtestpipetargetapidestDefaultTestDeployAssert6B876A1E.assets.json
  packages/@aws-cdk/aws-pipes-targets-alpha/test/integ.api-destination.js.snapshot/integtestpipetargetapidestDefaultTestDeployAssert6B876A1E.template.json
  packages/@aws-cdk/aws-pipes-targets-alpha/test/integ.api-destination.js.snapshot/manifest.json
  packages/@aws-cdk/aws-pipes-targets-alpha/test/integ.api-destination.js.snapshot/tree.json
  packages/@aws-cdk/aws-pipes-targets-alpha/test/integ.api-destination.ts
Labels: p2, distinguished-contributor

#31555 feat(cli): notices on bootstrap version
  packages/@aws-cdk-testing/cli-integ/tests/cli-integ-tests/cli.integtest.ts
  packages/aws-cdk/README.md
  packages/aws-cdk/lib/api/environment-resources.ts
  packages/aws-cdk/lib/cli.ts
  packages/aws-cdk/lib/notices.ts
  packages/aws-cdk/test/api/environment-resources.test.ts
  packages/aws-cdk/test/notices.test.ts
Labels: p2, contribution/core, pr-linter/exempt-integ-test, pr-linter/cli-integ-tested
