Repository aws/aws-cdk, pull requests merged in 2024-10, with the labels that each got.

#31470 fix(core): apps that use token-aware-stringify are construct-instantiation-order-dependent
  packages/@aws-cdk-testing/framework-integ/test/core/test/integ.logical-id.ts
  packages/@aws-cdk-testing/framework-integ/test/core/test/integ.token-aware-stringify-logical-ids.js.snapshot/Stack.assets.json
  packages/@aws-cdk-testing/framework-integ/test/core/test/integ.token-aware-stringify-logical-ids.js.snapshot/Stack.template.json
  packages/@aws-cdk-testing/framework-integ/test/core/test/integ.token-aware-stringify-logical-ids.js.snapshot/TokenAwareStringifyLogicalIdsDefaultTestDeployAssert787DCCE3.assets.json
  packages/@aws-cdk-testing/framework-integ/test/core/test/integ.token-aware-stringify-logical-ids.js.snapshot/TokenAwareStringifyLogicalIdsDefaultTestDeployAssert787DCCE3.template.json
  packages/@aws-cdk-testing/framework-integ/test/core/test/integ.token-aware-stringify-logical-ids.js.snapshot/asset.9e8936ba1db43e0919ba2fc8265d50686eeaca82830c471ff8b7b0672c5970ec/index.js
  packages/@aws-cdk-testing/framework-integ/test/core/test/integ.token-aware-stringify-logical-ids.js.snapshot/asset.a4052fc8993f394f879e80c418974b5f01321a8ea600ed16668222a0705b6d1a/__entrypoint__.js
  packages/@aws-cdk-testing/framework-integ/test/core/test/integ.token-aware-stringify-logical-ids.js.snapshot/asset.a4052fc8993f394f879e80c418974b5f01321a8ea600ed16668222a0705b6d1a/index.js
  packages/@aws-cdk-testing/framework-integ/test/core/test/integ.token-aware-stringify-logical-ids.js.snapshot/asset.bde7b5c89cb43285f884c94f0b9e17cdb0f5eb5345005114dd60342e0b8a85a1/__entrypoint__.js
  packages/@aws-cdk-testing/framework-integ/test/core/test/integ.token-aware-stringify-logical-ids.js.snapshot/asset.bde7b5c89cb43285f884c94f0b9e17cdb0f5eb5345005114dd60342e0b8a85a1/index.js
  packages/@aws-cdk-testing/framework-integ/test/core/test/integ.token-aware-stringify-logical-ids.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/core/test/integ.token-aware-stringify-logical-ids.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/core/test/integ.token-aware-stringify-logical-ids.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/core/test/integ.token-aware-stringify-logical-ids.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/core/test/integ.token-aware-stringify-logical-ids.ts
  packages/aws-cdk-lib/core/lib/private/cloudformation-lang.ts
  packages/aws-cdk-lib/core/test/cloudformation-json.test.ts
Labels: bug, p1, effort/medium, contribution/core

#31601 chore: update Contributors File
  CONTRIBUTORS.md
Labels: p2, pr/needs-community-review, auto-approve

#31606 chore: improve integration test for notices
  packages/@aws-cdk-testing/cli-integ/resources/cdk-apps/app/app.js
  packages/@aws-cdk-testing/cli-integ/tests/cli-integ-tests/cli.integtest.ts
Labels: p2, contribution/core, pr/needs-maintainer-review

#31612 chore: document new `--unstable` protocol for CLI features
  CONTRIBUTING.md
  packages/aws-cdk/README.md
Labels: p2, contribution/core

#31510 fix(batch): remove default optimal for arm based instance types and add error checks
  packages/@aws-cdk-testing/framework-integ/test/aws-batch/test/integ.managed-compute-environment.js.snapshot/BatchManagedComputeEnvironmentTestDefaultTestDeployAssertD4528F80.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-batch/test/integ.managed-compute-environment.js.snapshot/batch-stack.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-batch/test/integ.managed-compute-environment.js.snapshot/batch-stack.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-batch/test/integ.managed-compute-environment.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-batch/test/integ.managed-compute-environment.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-batch/test/integ.managed-compute-environment.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-batch/test/integ.managed-compute-environment.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-batch/test/integ.managed-compute-environment.ts
  packages/aws-cdk-lib/aws-batch/lib/managed-compute-environment.ts
  packages/aws-cdk-lib/aws-batch/test/managed-compute-environment.test.ts
Labels: bug, p2, effort/small, contribution/core

#31407 feat(cli): `cdk rollback`
  packages/@aws-cdk-testing/cli-integ/README.md
  packages/@aws-cdk-testing/cli-integ/lib/with-cdk-app.ts
  packages/@aws-cdk-testing/cli-integ/resources/cdk-apps/rollback-test-app/app.js
  packages/@aws-cdk-testing/cli-integ/resources/cdk-apps/rollback-test-app/cdk.json
  packages/@aws-cdk-testing/cli-integ/tests/cli-integ-tests/cli.integtest.ts
  packages/aws-cdk/README.md
  packages/aws-cdk/lib/api/bootstrap/bootstrap-template.yaml
  packages/aws-cdk/lib/api/cxapp/exec.ts
  packages/aws-cdk/lib/api/deployments.ts
  packages/aws-cdk/lib/api/util/cloudformation/stack-activity-monitor.ts
  packages/aws-cdk/lib/api/util/cloudformation/stack-event-poller.ts
  packages/aws-cdk/lib/api/util/cloudformation/stack-status.ts
  packages/aws-cdk/lib/cdk-toolkit.ts
  packages/aws-cdk/lib/cli.ts
  packages/aws-cdk/test/api/cloudformation-deployments.test.ts
  packages/aws-cdk/test/api/fake-cloudformation-stack.ts
  packages/aws-cdk/test/api/stack-activity-monitor.test.ts
  packages/aws-cdk/test/cdk-toolkit.test.ts
  packages/aws-cdk/test/util/mock-sdk.ts
  packages/aws-cdk/test/util/stack-monitor.test.ts
Labels: p2, contribution/core, pr-linter/exempt-integ-test, pr-linter/cli-integ-tested

#31600 fix(core): `isTaggable` function can return undefined instead of false
  packages/aws-cdk-lib/core/lib/tag-manager.ts
  packages/aws-cdk-lib/core/test/tag-manager.test.ts
Labels: bug, p1, contribution/core, pr-linter/exempt-integ-test

#31625 chore: fix failing notices integ test
  packages/@aws-cdk-testing/cli-integ/tests/cli-integ-tests/cli.integtest.ts
Labels: p2, contribution/core

#31597 fix(core): file asset publishing role not used in `cdk diff` to upload large templates
  packages/@aws-cdk-testing/cli-integ/resources/cdk-apps/app/app.js
  packages/@aws-cdk-testing/cli-integ/tests/cli-integ-tests/cli.integtest.ts
  packages/aws-cdk/lib/api/deployments.ts
  packages/aws-cdk/lib/api/util/cloudformation.ts
  packages/aws-cdk/lib/api/util/template-body-parameter.ts
Labels: bug, p1, effort/medium, contribution/core, pr-linter/exempt-integ-test, pr-linter/cli-integ-tested

#31538 chore(ec2): add SageMaker Interface VPC Endpoint
  packages/aws-cdk-lib/aws-ec2/lib/vpc-endpoint.ts
Labels: p2, beginning-contributor, pr/needs-maintainer-review

#31590 chore(lambda): resolve unable to reference AuthType from FunctionUrl
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda/test/integ.function-url.js.snapshot/IntegTestDefaultTestDeployAssertE3E7D2A4.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda/test/integ.function-url.js.snapshot/Stack1.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda/test/integ.function-url.js.snapshot/Stack1.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda/test/integ.function-url.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda/test/integ.function-url.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda/test/integ.function-url.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda/test/integ.function-url.js.snapshot/tree.json
  packages/aws-cdk-lib/aws-lambda/lib/function-url.ts
  packages/aws-cdk-lib/aws-lambda/test/function-url.test.ts
Labels: p2, pr-linter/exempt-integ-test, distinguished-contributor, pr-linter/exemption-requested, pr/reviewer-clarification-requested, pr/needs-maintainer-review

#31604 chore(rds): supports Aurora PostgreSQL 16.4, 15.8, 14.13, 13.16, and 12.20
  packages/aws-cdk-lib/aws-rds/lib/cluster-engine.ts
Labels: p2, pr/needs-community-review, distinguished-contributor

#30162 feat(ec2): add interface endpoint dynamodb
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.vpc-endpoint.lit.js.snapshot/aws-cdk-ec2-vpc-endpoint.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.vpc-endpoint.lit.js.snapshot/aws-cdk-ec2-vpc-endpoint.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.vpc-endpoint.lit.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.vpc-endpoint.lit.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.vpc-endpoint.lit.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.vpc-endpoint.lit.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.vpc-endpoint.lit.ts
  packages/aws-cdk-lib/aws-ec2/lib/vpc-endpoint.ts
  packages/aws-cdk-lib/aws-ec2/test/vpc-endpoint.test.ts
Labels: p2, feature-request, effort/medium, pr-linter/exempt-readme, beginning-contributor, pr-linter/exemption-requested

#31640 feat: update L1 CloudFormation resource definitions
  packages/@aws-cdk/cloudformation-diff/package.json
  packages/@aws-cdk/integ-runner/package.json
  packages/aws-cdk-lib/package.json
  tools/@aws-cdk/spec2cdk/package.json
  yarn.lock
Labels: p2, dependencies, contribution/core, pr-linter/exempt-readme, pr-linter/exempt-test, auto-approve, pr-linter/exempt-integ-test

#30656 feat(pipes-targets): add Kinesis
  packages/@aws-cdk/aws-pipes-targets-alpha/README.md
  packages/@aws-cdk/aws-pipes-targets-alpha/lib/index.ts
  packages/@aws-cdk/aws-pipes-targets-alpha/lib/kinesis.ts
  packages/@aws-cdk/aws-pipes-targets-alpha/rosetta/default.ts-fixture
  packages/@aws-cdk/aws-pipes-targets-alpha/test/__snapshots__/kinesis.test.ts.snap
  packages/@aws-cdk/aws-pipes-targets-alpha/test/integ.kinesis.js.snapshot/asset.da514df694ce3f41453746a766ae6aff13c869c38002598930d6d34e5711985b.bundle/index.js
  packages/@aws-cdk/aws-pipes-targets-alpha/test/integ.kinesis.js.snapshot/aws-cdk-pipes-targets-kinesis.assets.json
  packages/@aws-cdk/aws-pipes-targets-alpha/test/integ.kinesis.js.snapshot/aws-cdk-pipes-targets-kinesis.template.json
  packages/@aws-cdk/aws-pipes-targets-alpha/test/integ.kinesis.js.snapshot/cdk.out
  packages/@aws-cdk/aws-pipes-targets-alpha/test/integ.kinesis.js.snapshot/integ.json
  packages/@aws-cdk/aws-pipes-targets-alpha/test/integ.kinesis.js.snapshot/integtestpipetargetkinesisDefaultTestDeployAssertA9FA1AAE.assets.json
  packages/@aws-cdk/aws-pipes-targets-alpha/test/integ.kinesis.js.snapshot/integtestpipetargetkinesisDefaultTestDeployAssertA9FA1AAE.template.json
  packages/@aws-cdk/aws-pipes-targets-alpha/test/integ.kinesis.js.snapshot/manifest.json
  packages/@aws-cdk/aws-pipes-targets-alpha/test/integ.kinesis.js.snapshot/tree.json
  packages/@aws-cdk/aws-pipes-targets-alpha/test/integ.kinesis.ts
  packages/@aws-cdk/aws-pipes-targets-alpha/test/kinesis.test.ts
Labels: p2, distinguished-contributor

#31639 fix(lambda-nodejs): remove smithy models from bundling for AWS SDK v3 runtimes (under feature flag)
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-nodejs/test/integ.function-exclude-smithy-models.js.snapshot/NodeJsFunctionExcludeSmithyIntegDefaultTestDeployAssert8BE0D2D1.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-nodejs/test/integ.function-exclude-smithy-models.js.snapshot/NodeJsFunctionExcludeSmithyIntegDefaultTestDeployAssert8BE0D2D1.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-nodejs/test/integ.function-exclude-smithy-models.js.snapshot/asset.5f1efdee2910b237bc92c947c2621e653fadf9ce9ef02e797da9ec166a2d4270/index.js
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-nodejs/test/integ.function-exclude-smithy-models.js.snapshot/cdk-integ-lambda-nodejs-18-exclude-smithy.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-nodejs/test/integ.function-exclude-smithy-models.js.snapshot/cdk-integ-lambda-nodejs-18-exclude-smithy.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-nodejs/test/integ.function-exclude-smithy-models.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-nodejs/test/integ.function-exclude-smithy-models.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-nodejs/test/integ.function-exclude-smithy-models.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-nodejs/test/integ.function-exclude-smithy-models.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-nodejs/test/integ.function-exclude-smithy-models.ts
  packages/aws-cdk-lib/aws-lambda-nodejs/lib/bundling.ts
  packages/aws-cdk-lib/aws-lambda-nodejs/test/bundling.test.ts
  packages/aws-cdk-lib/cx-api/FEATURE_FLAGS.md
  packages/aws-cdk-lib/cx-api/README.md
  packages/aws-cdk-lib/cx-api/lib/features.ts
Labels: bug, p1, effort/medium, contribution/core

#31280 feat(rds): enable `grantDataApiAccess` method for imported database cluster
  packages/@aws-cdk-testing/framework-integ/test/aws-rds/test/integ.cluster-data-api-to-imported-cluster.js.snapshot/asset.bde7b5c89cb43285f884c94f0b9e17cdb0f5eb5345005114dd60342e0b8a85a1/__entrypoint__.js
  packages/@aws-cdk-testing/framework-integ/test/aws-rds/test/integ.cluster-data-api-to-imported-cluster.js.snapshot/asset.bde7b5c89cb43285f884c94f0b9e17cdb0f5eb5345005114dd60342e0b8a85a1/index.js
  packages/@aws-cdk-testing/framework-integ/test/aws-rds/test/integ.cluster-data-api-to-imported-cluster.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-rds/test/integ.cluster-data-api-to-imported-cluster.js.snapshot/cluster-data-api-to-imported-cluster.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-rds/test/integ.cluster-data-api-to-imported-cluster.js.snapshot/cluster-data-api-to-imported-cluster.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-rds/test/integ.cluster-data-api-to-imported-cluster.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-rds/test/integ.cluster-data-api-to-imported-cluster.js.snapshot/integclusterdataapitoimportedclusterDefaultTestDeployAssert641C7C79.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-rds/test/integ.cluster-data-api-to-imported-cluster.js.snapshot/integclusterdataapitoimportedclusterDefaultTestDeployAssert641C7C79.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-rds/test/integ.cluster-data-api-to-imported-cluster.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-rds/test/integ.cluster-data-api-to-imported-cluster.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-rds/test/integ.cluster-data-api-to-imported-cluster.ts
  packages/aws-cdk-lib/aws-rds/README.md
  packages/aws-cdk-lib/aws-rds/lib/cluster-ref.ts
  packages/aws-cdk-lib/aws-rds/lib/cluster.ts
  packages/aws-cdk-lib/aws-rds/test/cluster.test.ts
Labels: bug, p2, effort/medium, distinguished-contributor

#31650 chore(merge-back): 2.161.0
  CHANGELOG.v2.alpha.md
  CHANGELOG.v2.md
  packages/aws-cdk-lib/cx-api/FEATURE_FLAGS.md
  packages/aws-cdk-lib/cx-api/lib/features.ts
  version.v2.json
Labels: p2, pr/needs-community-review, pr/no-squash, auto-approve

#31649 docs(dynamodb): fix doc for `awsManagedKey` method
  packages/aws-cdk-lib/aws-dynamodb/lib/encryption.ts
Labels: p2, distinguished-contributor

#31298 chore(lambda): add 1.0.333.0 lamba insights version
  packages/aws-cdk-lib/aws-lambda/lib/lambda-insights.ts
  packages/aws-cdk-lib/region-info/build-tools/fact-tables.ts
  packages/aws-cdk-lib/region-info/test/__snapshots__/region-info.test.ts.snap
Labels: p2, distinguished-contributor

#31630 chore(kinesisfirehose-alpha): replace`destinations` property with `destination` and change type from array to single IDestination
  packages/@aws-cdk/aws-iot-actions-alpha/README.md
  packages/@aws-cdk/aws-iot-actions-alpha/test/kinesis-firehose/integ.firehose-put-record-action.ts
  packages/@aws-cdk/aws-kinesisfirehose-alpha/README.md
  packages/@aws-cdk/aws-kinesisfirehose-alpha/lib/delivery-stream.ts
  packages/@aws-cdk/aws-kinesisfirehose-alpha/test/delivery-stream.test.ts
  packages/@aws-cdk/aws-kinesisfirehose-alpha/test/integ.delivery-stream.source-stream.ts
  packages/@aws-cdk/aws-kinesisfirehose-alpha/test/integ.delivery-stream.ts
  packages/@aws-cdk/aws-kinesisfirehose-alpha/test/integ.kinesis-stream-events-target.ts
  packages/@aws-cdk/aws-kinesisfirehose-destinations-alpha/test/integ.s3-bucket.lit.ts
  packages/@aws-cdk/aws-kinesisfirehose-destinations-alpha/test/s3-bucket.test.ts
  packages/aws-cdk-lib/aws-logs/README.md
Labels: p2, contribution/core

#31657 revert: feat(cli): cdk rollback (#31407)
  packages/@aws-cdk-testing/cli-integ/README.md
  packages/@aws-cdk-testing/cli-integ/lib/with-cdk-app.ts
  packages/@aws-cdk-testing/cli-integ/resources/cdk-apps/rollback-test-app/app.js
  packages/@aws-cdk-testing/cli-integ/resources/cdk-apps/rollback-test-app/cdk.json
  packages/@aws-cdk-testing/cli-integ/resources/cli-regression-patches/v2.161.0/NOTES.md
  packages/@aws-cdk-testing/cli-integ/resources/cli-regression-patches/v2.161.0/skip-tests.txt
  packages/@aws-cdk-testing/cli-integ/tests/cli-integ-tests/cli.integtest.ts
  packages/aws-cdk/README.md
  packages/aws-cdk/lib/api/bootstrap/bootstrap-template.yaml
  packages/aws-cdk/lib/api/cxapp/exec.ts
  packages/aws-cdk/lib/api/deployments.ts
  packages/aws-cdk/lib/api/util/cloudformation/stack-activity-monitor.ts
  packages/aws-cdk/lib/api/util/cloudformation/stack-event-poller.ts
  packages/aws-cdk/lib/api/util/cloudformation/stack-status.ts
  packages/aws-cdk/lib/cdk-toolkit.ts
  packages/aws-cdk/lib/cli.ts
  packages/aws-cdk/test/api/cloudformation-deployments.test.ts
  packages/aws-cdk/test/api/fake-cloudformation-stack.ts
  packages/aws-cdk/test/api/stack-activity-monitor.test.ts
  packages/aws-cdk/test/cdk-toolkit.test.ts
  packages/aws-cdk/test/util/mock-sdk.ts
  packages/aws-cdk/test/util/stack-monitor.test.ts
Labels: p2, contribution/core, pr-linter/cli-integ-tested

#31659 chore(release): 2.161.1
  CHANGELOG.v2.alpha.md
  CHANGELOG.v2.md
  packages/@aws-cdk-testing/cli-integ/README.md
  packages/@aws-cdk-testing/cli-integ/lib/with-cdk-app.ts
  packages/@aws-cdk-testing/cli-integ/resources/cdk-apps/rollback-test-app/app.js
  packages/@aws-cdk-testing/cli-integ/resources/cdk-apps/rollback-test-app/cdk.json
  packages/@aws-cdk-testing/cli-integ/resources/cli-regression-patches/v2.161.0/NOTES.md
  packages/@aws-cdk-testing/cli-integ/resources/cli-regression-patches/v2.161.0/skip-tests.txt
  packages/@aws-cdk-testing/cli-integ/tests/cli-integ-tests/cli.integtest.ts
  packages/aws-cdk/README.md
  packages/aws-cdk/lib/api/bootstrap/bootstrap-template.yaml
  packages/aws-cdk/lib/api/cxapp/exec.ts
  packages/aws-cdk/lib/api/deployments.ts
  packages/aws-cdk/lib/api/util/cloudformation/stack-activity-monitor.ts
  packages/aws-cdk/lib/api/util/cloudformation/stack-event-poller.ts
  packages/aws-cdk/lib/api/util/cloudformation/stack-status.ts
  packages/aws-cdk/lib/cdk-toolkit.ts
  packages/aws-cdk/lib/cli.ts
  packages/aws-cdk/test/api/cloudformation-deployments.test.ts
  packages/aws-cdk/test/api/fake-cloudformation-stack.ts
  packages/aws-cdk/test/api/stack-activity-monitor.test.ts
  packages/aws-cdk/test/cdk-toolkit.test.ts
  packages/aws-cdk/test/util/mock-sdk.ts
  packages/aws-cdk/test/util/stack-monitor.test.ts
  version.v2.json
Labels: p2, contribution/core, pr/no-squash, pr-linter/cli-integ-tested

#31662 chore(merge-back): 2.161.1
  CHANGELOG.v2.alpha.md
  CHANGELOG.v2.md
  version.v2.json
Labels: p2, pr/needs-community-review, pr/no-squash, auto-approve

#31636 fix(core): `cdk diff` on large templates fails when passing in `toolkitStackName` and `qualifier`
  packages/@aws-cdk-testing/cli-integ/lib/with-cdk-app.ts
  packages/@aws-cdk-testing/cli-integ/resources/cdk-apps/app/app.js
  packages/@aws-cdk-testing/cli-integ/tests/cli-integ-tests/cli.integtest.ts
  packages/aws-cdk/lib/api/util/cloudformation.ts
  packages/aws-cdk/lib/cdk-toolkit.ts
  packages/aws-cdk/lib/cli.ts
Labels: bug, p1, effort/medium, contribution/core, pr-linter/exempt-integ-test, pr-linter/cli-integ-tested

#31658 chore: upgrade sdkv3 to the newest version used by lambda distributions
  package.json
  packages/@aws-cdk-testing/cli-integ/lib/aws.ts
  packages/@aws-cdk-testing/cli-integ/package.json
  packages/@aws-cdk-testing/framework-integ/package.json
  packages/@aws-cdk-testing/framework-integ/test/aws-route53/test/integ.delete-existing-record-set.js.snapshot/Rooute53DeleteExistingRecordSetIntegDefaultTestDeployAssert62638412.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-route53/test/integ.delete-existing-record-set.js.snapshot/asset.782a34c2ce2f5bc5e5b90304f41348680a6f9ba7a0eb2de6f03658640f67ff15/__entrypoint__.js
  packages/@aws-cdk-testing/framework-integ/test/aws-route53/test/integ.delete-existing-record-set.js.snapshot/asset.782a34c2ce2f5bc5e5b90304f41348680a6f9ba7a0eb2de6f03658640f67ff15/index.js
  packages/@aws-cdk-testing/framework-integ/test/aws-route53/test/integ.delete-existing-record-set.js.snapshot/asset.e0e799a729f2e647a95d0ba4e1b63e93839a8f3034bfcb17ba52ea561cafba19/index.js
  packages/@aws-cdk-testing/framework-integ/test/aws-route53/test/integ.delete-existing-record-set.js.snapshot/cdk-route53-integ-delete-existing-record-set.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-route53/test/integ.delete-existing-record-set.js.snapshot/cdk-route53-integ-delete-existing-record-set.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-route53/test/integ.delete-existing-record-set.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-route53/test/integ.delete-existing-record-set.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-route53/test/integ.delete-existing-record-set.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/triggers/test/integ.triggers.js.snapshot/MyStack.assets.json
  packages/@aws-cdk-testing/framework-integ/test/triggers/test/integ.triggers.js.snapshot/MyStack.template.json
  packages/@aws-cdk-testing/framework-integ/test/triggers/test/integ.triggers.js.snapshot/TriggerTestDefaultTestDeployAssert61636546.assets.json
  packages/@aws-cdk-testing/framework-integ/test/triggers/test/integ.triggers.js.snapshot/TriggerTestDefaultTestDeployAssert61636546.template.json
  packages/@aws-cdk-testing/framework-integ/test/triggers/test/integ.triggers.js.snapshot/asset.332b43dd64df92147f3af7fe53689eb20106f7158d60d220b0b10b126035713b.bundle/index.js
  packages/@aws-cdk-testing/framework-integ/test/triggers/test/integ.triggers.js.snapshot/asset.6e5c0f63875937fea22d274138fc297c2a753e7516d437661017ee38ced6816c/__entrypoint__.js
  packages/@aws-cdk-testing/framework-integ/test/triggers/test/integ.triggers.js.snapshot/asset.6e5c0f63875937fea22d274138fc297c2a753e7516d437661017ee38ced6816c/index.js
  packages/@aws-cdk-testing/framework-integ/test/triggers/test/integ.triggers.js.snapshot/asset.ac5727a1b8e23c42dabba9ff5155c8fb26ae68568e083beac0908af8e70fc606/index.js
  packages/@aws-cdk-testing/framework-integ/test/triggers/test/integ.triggers.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/triggers/test/integ.triggers.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/triggers/test/integ.triggers.js.snapshot/manifest.json
  packages/@aws-cdk/aws-amplify-alpha/package.json
  packages/@aws-cdk/aws-custom-resource-sdk-adapter/package.json
  packages/@aws-cdk/aws-redshift-alpha/package.json
  packages/@aws-cdk/cloudformation-diff/package.json
  packages/@aws-cdk/custom-resource-handlers/lib/aws-eks/cluster-resource-handler/index.ts
  packages/@aws-cdk/custom-resource-handlers/lib/aws-route53/delete-existing-record-set-handler/index.ts
  packages/@aws-cdk/custom-resource-handlers/lib/triggers/lambda/index.ts
  packages/@aws-cdk/custom-resource-handlers/package.json
  packages/@aws-cdk/integ-tests-alpha/package.json
  packages/aws-cdk-lib/package.json
  tools/@aws-cdk/cdk-build-tools/config/jest.config.js
  yarn.lock
Labels: p2, contribution/core

#31678 chore: add integ test for doubly nested stack
  packages/@aws-cdk-testing/cli-integ/resources/cdk-apps/app/app.js
  packages/@aws-cdk-testing/cli-integ/resources/cdk-apps/app/nested-stack.js
  packages/@aws-cdk-testing/cli-integ/tests/cli-integ-tests/cli.integtest.ts
Labels: p2, contribution/core, pr/needs-maintainer-review

#31684 feat(cli): cdk rollback
  packages/@aws-cdk-testing/cli-integ/README.md
  packages/@aws-cdk-testing/cli-integ/lib/with-cdk-app.ts
  packages/@aws-cdk-testing/cli-integ/resources/cdk-apps/rollback-test-app/app.js
  packages/@aws-cdk-testing/cli-integ/resources/cdk-apps/rollback-test-app/cdk.json
  packages/@aws-cdk-testing/cli-integ/tests/cli-integ-tests/cli.integtest.ts
  packages/aws-cdk-lib/cx-api/FEATURE_FLAGS.md
  packages/aws-cdk/README.md
  packages/aws-cdk/lib/api/bootstrap/bootstrap-template.yaml
  packages/aws-cdk/lib/api/cxapp/exec.ts
  packages/aws-cdk/lib/api/deployments.ts
  packages/aws-cdk/lib/api/util/cloudformation/stack-activity-monitor.ts
  packages/aws-cdk/lib/api/util/cloudformation/stack-event-poller.ts
  packages/aws-cdk/lib/api/util/cloudformation/stack-status.ts
  packages/aws-cdk/lib/cdk-toolkit.ts
  packages/aws-cdk/lib/cli.ts
  packages/aws-cdk/test/api/cloudformation-deployments.test.ts
  packages/aws-cdk/test/api/fake-cloudformation-stack.ts
  packages/aws-cdk/test/api/stack-activity-monitor.test.ts
  packages/aws-cdk/test/cdk-toolkit.test.ts
  packages/aws-cdk/test/util/mock-sdk.ts
  packages/aws-cdk/test/util/stack-monitor.test.ts
Labels: p2, contribution/core, pr-linter/exempt-integ-test, pr-linter/cli-integ-tested

#31688 feat: update L1 CloudFormation resource definitions
  packages/@aws-cdk/cloudformation-diff/package.json
  packages/@aws-cdk/integ-runner/package.json
  packages/aws-cdk-lib/package.json
  tools/@aws-cdk/spec2cdk/package.json
  yarn.lock
Labels: p2, dependencies, contribution/core, pr-linter/exempt-readme, pr-linter/exempt-test, auto-approve, pr-linter/exempt-integ-test

#31585 feat(appsync): add `ownerContact` property to the `GraphqlApi`
  packages/@aws-cdk-testing/framework-integ/test/aws-appsync/test/integ.appsync-owner-contact.js.snapshot/apiDefaultTestDeployAssert018781F2.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-appsync/test/integ.appsync-owner-contact.js.snapshot/apiDefaultTestDeployAssert018781F2.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-appsync/test/integ.appsync-owner-contact.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-appsync/test/integ.appsync-owner-contact.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-appsync/test/integ.appsync-owner-contact.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-appsync/test/integ.appsync-owner-contact.js.snapshot/stack.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-appsync/test/integ.appsync-owner-contact.js.snapshot/stack.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-appsync/test/integ.appsync-owner-contact.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-appsync/test/integ.appsync-owner-contact.ts
  packages/aws-cdk-lib/aws-appsync/README.md
  packages/aws-cdk-lib/aws-appsync/lib/graphqlapi.ts
  packages/aws-cdk-lib/aws-appsync/test/appsync.test.ts
Labels: p2, beginning-contributor

#31615 fix(event-targets): ecsTask uses invalid task definition arn in policy
  packages/@aws-cdk-testing/framework-integ/test/aws-events-targets/test/ecs/integ.ecs-imported-task-def.js.snapshot/IntegEcsImportedTaskDefStack.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-events-targets/test/ecs/integ.ecs-imported-task-def.js.snapshot/IntegEcsImportedTaskDefStack.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-events-targets/test/ecs/integ.ecs-imported-task-def.js.snapshot/IntegTestEcsImportedTaskDefinitionDefaultTestDeployAssert69FA1335.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-events-targets/test/ecs/integ.ecs-imported-task-def.js.snapshot/IntegTestEcsImportedTaskDefinitionDefaultTestDeployAssert69FA1335.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-events-targets/test/ecs/integ.ecs-imported-task-def.js.snapshot/asset.bde7b5c89cb43285f884c94f0b9e17cdb0f5eb5345005114dd60342e0b8a85a1/__entrypoint__.js
  packages/@aws-cdk-testing/framework-integ/test/aws-events-targets/test/ecs/integ.ecs-imported-task-def.js.snapshot/asset.bde7b5c89cb43285f884c94f0b9e17cdb0f5eb5345005114dd60342e0b8a85a1/index.js
  packages/@aws-cdk-testing/framework-integ/test/aws-events-targets/test/ecs/integ.ecs-imported-task-def.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-events-targets/test/ecs/integ.ecs-imported-task-def.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-events-targets/test/ecs/integ.ecs-imported-task-def.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-events-targets/test/ecs/integ.ecs-imported-task-def.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-events-targets/test/ecs/integ.ecs-imported-task-def.ts
  packages/aws-cdk-lib/aws-events-targets/lib/ecs-task.ts
  packages/aws-cdk-lib/aws-events-targets/test/ecs/event-rule-target.test.ts
Labels: bug, p1, effort/small, contribution/core

#30654 feat(pipes-targets): add EventBridge
  packages/@aws-cdk/aws-pipes-targets-alpha/README.md
  packages/@aws-cdk/aws-pipes-targets-alpha/lib/event-bridge.ts
  packages/@aws-cdk/aws-pipes-targets-alpha/lib/index.ts
  packages/@aws-cdk/aws-pipes-targets-alpha/package.json
  packages/@aws-cdk/aws-pipes-targets-alpha/test/__snapshots__/event-bridge.test.ts.snap
  packages/@aws-cdk/aws-pipes-targets-alpha/test/event-bridge.test.ts
  packages/@aws-cdk/aws-pipes-targets-alpha/test/integ.event-bridge.js.snapshot/asset.da514df694ce3f41453746a766ae6aff13c869c38002598930d6d34e5711985b.bundle/index.js
  packages/@aws-cdk/aws-pipes-targets-alpha/test/integ.event-bridge.js.snapshot/aws-cdk-pipes-targets-event-bridge.assets.json
  packages/@aws-cdk/aws-pipes-targets-alpha/test/integ.event-bridge.js.snapshot/aws-cdk-pipes-targets-event-bridge.template.json
  packages/@aws-cdk/aws-pipes-targets-alpha/test/integ.event-bridge.js.snapshot/cdk.out
  packages/@aws-cdk/aws-pipes-targets-alpha/test/integ.event-bridge.js.snapshot/integ.json
  packages/@aws-cdk/aws-pipes-targets-alpha/test/integ.event-bridge.js.snapshot/integtestpipetargeteventbridgeDefaultTestDeployAssert7ABF1246.assets.json
  packages/@aws-cdk/aws-pipes-targets-alpha/test/integ.event-bridge.js.snapshot/integtestpipetargeteventbridgeDefaultTestDeployAssert7ABF1246.template.json
  packages/@aws-cdk/aws-pipes-targets-alpha/test/integ.event-bridge.js.snapshot/manifest.json
  packages/@aws-cdk/aws-pipes-targets-alpha/test/integ.event-bridge.js.snapshot/tree.json
  packages/@aws-cdk/aws-pipes-targets-alpha/test/integ.event-bridge.ts
Labels: p2, distinguished-contributor

#31374 fix(ecs): ecs exec cannot be enabled for ECS Anywhere (ecs.ExternalService)
  packages/aws-cdk-lib/aws-ecs/README.md
  packages/aws-cdk-lib/aws-ecs/lib/external/external-service.ts
  packages/aws-cdk-lib/aws-ecs/test/external/external-service.test.ts
Labels: bug, p2, effort/small, pr-linter/exempt-integ-test, distinguished-contributor

#31661 feat(iot-alpha): support for account audit configuration
  packages/@aws-cdk/aws-iot-alpha/README.md
  packages/@aws-cdk/aws-iot-alpha/awslint.json
  packages/@aws-cdk/aws-iot-alpha/lib/audit-configuration.ts
  packages/@aws-cdk/aws-iot-alpha/lib/index.ts
  packages/@aws-cdk/aws-iot-alpha/rosetta/default.ts-fixture
  packages/@aws-cdk/aws-iot-alpha/test/audit-configuration.test.ts
  packages/@aws-cdk/aws-iot-alpha/test/integ.audit-configuration.js.snapshot/IotAuditConfigurationTestDefaultTestDeployAssert6A603D00.assets.json
  packages/@aws-cdk/aws-iot-alpha/test/integ.audit-configuration.js.snapshot/IotAuditConfigurationTestDefaultTestDeployAssert6A603D00.template.json
  packages/@aws-cdk/aws-iot-alpha/test/integ.audit-configuration.js.snapshot/IotAuditConfigurationTestStack.assets.json
  packages/@aws-cdk/aws-iot-alpha/test/integ.audit-configuration.js.snapshot/IotAuditConfigurationTestStack.template.json
  packages/@aws-cdk/aws-iot-alpha/test/integ.audit-configuration.js.snapshot/cdk.out
  packages/@aws-cdk/aws-iot-alpha/test/integ.audit-configuration.js.snapshot/integ.json
  packages/@aws-cdk/aws-iot-alpha/test/integ.audit-configuration.js.snapshot/manifest.json
  packages/@aws-cdk/aws-iot-alpha/test/integ.audit-configuration.js.snapshot/tree.json
  packages/@aws-cdk/aws-iot-alpha/test/integ.audit-configuration.ts
Labels: p2, feature-request, distinguished-contributor

#31588 chore(pipes-targets): update integration tests to use SqsSource
  packages/@aws-cdk/aws-pipes-targets-alpha/README.md
  packages/@aws-cdk/aws-pipes-targets-alpha/test/integ.api-destination.ts
  packages/@aws-cdk/aws-pipes-targets-alpha/test/integ.kinesis.ts
  packages/@aws-cdk/aws-pipes-targets-alpha/test/integ.lambda.js.snapshot/asset.da514df694ce3f41453746a766ae6aff13c869c38002598930d6d34e5711985b.bundle/index.js
  packages/@aws-cdk/aws-pipes-targets-alpha/test/integ.lambda.js.snapshot/aws-cdk-pipes-lambda-target.assets.json
  packages/@aws-cdk/aws-pipes-targets-alpha/test/integ.lambda.js.snapshot/cdk.out
  packages/@aws-cdk/aws-pipes-targets-alpha/test/integ.lambda.js.snapshot/integ.json
  packages/@aws-cdk/aws-pipes-targets-alpha/test/integ.lambda.js.snapshot/integtestpipetargetlambdaDefaultTestDeployAssert48C58B78.assets.json
  packages/@aws-cdk/aws-pipes-targets-alpha/test/integ.lambda.js.snapshot/integtestpipetargetlambdaDefaultTestDeployAssert48C58B78.template.json
  packages/@aws-cdk/aws-pipes-targets-alpha/test/integ.lambda.js.snapshot/manifest.json
  packages/@aws-cdk/aws-pipes-targets-alpha/test/integ.lambda.js.snapshot/tree.json
  packages/@aws-cdk/aws-pipes-targets-alpha/test/integ.lambda.ts
  packages/@aws-cdk/aws-pipes-targets-alpha/test/integ.sqs.js.snapshot/asset.da514df694ce3f41453746a766ae6aff13c869c38002598930d6d34e5711985b.bundle/index.js
  packages/@aws-cdk/aws-pipes-targets-alpha/test/integ.sqs.js.snapshot/aws-cdk-pipes-targets.assets.json
  packages/@aws-cdk/aws-pipes-targets-alpha/test/integ.sqs.js.snapshot/cdk.out
  packages/@aws-cdk/aws-pipes-targets-alpha/test/integ.sqs.js.snapshot/integ.json
  packages/@aws-cdk/aws-pipes-targets-alpha/test/integ.sqs.js.snapshot/integtestpipetargetsqsDefaultTestDeployAssertD5F047DA.assets.json
  packages/@aws-cdk/aws-pipes-targets-alpha/test/integ.sqs.js.snapshot/integtestpipetargetsqsDefaultTestDeployAssertD5F047DA.template.json
  packages/@aws-cdk/aws-pipes-targets-alpha/test/integ.sqs.js.snapshot/manifest.json
  packages/@aws-cdk/aws-pipes-targets-alpha/test/integ.sqs.js.snapshot/tree.json
  packages/@aws-cdk/aws-pipes-targets-alpha/test/integ.sqs.ts
  packages/@aws-cdk/aws-pipes-targets-alpha/test/integ.stepfunctions.js.snapshot/asset.da514df694ce3f41453746a766ae6aff13c869c38002598930d6d34e5711985b.bundle/index.js
  packages/@aws-cdk/aws-pipes-targets-alpha/test/integ.stepfunctions.js.snapshot/aws-cdk-pipes-sfn-target.assets.json
  packages/@aws-cdk/aws-pipes-targets-alpha/test/integ.stepfunctions.js.snapshot/cdk.out
  packages/@aws-cdk/aws-pipes-targets-alpha/test/integ.stepfunctions.js.snapshot/integ.json
  packages/@aws-cdk/aws-pipes-targets-alpha/test/integ.stepfunctions.js.snapshot/integtestpipetargetsfnDefaultTestDeployAssert006F7F8F.assets.json
  packages/@aws-cdk/aws-pipes-targets-alpha/test/integ.stepfunctions.js.snapshot/integtestpipetargetsfnDefaultTestDeployAssert006F7F8F.template.json
  packages/@aws-cdk/aws-pipes-targets-alpha/test/integ.stepfunctions.js.snapshot/manifest.json
  packages/@aws-cdk/aws-pipes-targets-alpha/test/integ.stepfunctions.js.snapshot/tree.json
  packages/@aws-cdk/aws-pipes-targets-alpha/test/integ.stepfunctions.ts
Labels: p2, distinguished-contributor

#31693 docs(route53): fix broken heading
  packages/aws-cdk-lib/aws-route53/README.md
Labels: p2, pr/needs-community-review, distinguished-contributor

#31674 docs(events): update link about key policy for event bus
  packages/aws-cdk-lib/aws-events/lib/event-bus.ts
Labels: p2, pr/needs-community-review, distinguished-contributor

#31652 fix(iam): override Role.applyRemovalPolicy for customizeRoles
  packages/@aws-cdk-testing/framework-integ/test/aws-iam/test/integ.customize-roles-restapi.js.snapshot/IntegTestDefaultTestDeployAssertE3E7D2A4.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-iam/test/integ.customize-roles-restapi.js.snapshot/IntegTestDefaultTestDeployAssertE3E7D2A4.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-iam/test/integ.customize-roles-restapi.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-iam/test/integ.customize-roles-restapi.js.snapshot/iam-policy-report.json
  packages/@aws-cdk-testing/framework-integ/test/aws-iam/test/integ.customize-roles-restapi.js.snapshot/iam-policy-report.txt
  packages/@aws-cdk-testing/framework-integ/test/aws-iam/test/integ.customize-roles-restapi.js.snapshot/integ-customize-roles-restapi.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-iam/test/integ.customize-roles-restapi.js.snapshot/integ-customize-roles-restapi.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-iam/test/integ.customize-roles-restapi.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-iam/test/integ.customize-roles-restapi.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-iam/test/integ.customize-roles-restapi.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-iam/test/integ.customize-roles-restapi.ts
  packages/aws-cdk-lib/aws-iam/lib/role.ts
  packages/aws-cdk-lib/aws-iam/test/role.test.ts
Labels: bug, p2, beginning-contributor, pr-linter/exemption-requested

#31584 feat(elasticloadbalancingv2): support TCP idle timeout for Network Load Balancer Listener
  packages/@aws-cdk-testing/framework-integ/test/aws-elasticloadbalancingv2/test/integ.nlb-listener-tcp-idle-timeout.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-elasticloadbalancingv2/test/integ.nlb-listener-tcp-idle-timeout.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-elasticloadbalancingv2/test/integ.nlb-listener-tcp-idle-timeout.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-elasticloadbalancingv2/test/integ.nlb-listener-tcp-idle-timeout.js.snapshot/nlb-tcp-idle-timeout.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-elasticloadbalancingv2/test/integ.nlb-listener-tcp-idle-timeout.js.snapshot/nlb-tcp-idle-timeout.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-elasticloadbalancingv2/test/integ.nlb-listener-tcp-idle-timeout.js.snapshot/nlbtcpidletimeouttestDefaultTestDeployAssertAD9AE406.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-elasticloadbalancingv2/test/integ.nlb-listener-tcp-idle-timeout.js.snapshot/nlbtcpidletimeouttestDefaultTestDeployAssertAD9AE406.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-elasticloadbalancingv2/test/integ.nlb-listener-tcp-idle-timeout.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-elasticloadbalancingv2/test/integ.nlb-listener-tcp-idle-timeout.ts
  packages/aws-cdk-lib/aws-elasticloadbalancingv2/README.md
  packages/aws-cdk-lib/aws-elasticloadbalancingv2/lib/nlb/network-listener.ts
  packages/aws-cdk-lib/aws-elasticloadbalancingv2/lib/shared/base-listener.ts
  packages/aws-cdk-lib/aws-elasticloadbalancingv2/test/nlb/listener.test.ts
Labels: p2, feature-request, effort/medium, distinguished-contributor

#31622 feat(cdk): expose authorizer id and authorization type
  packages/@aws-cdk-testing/framework-integ/test/aws-apigatewayv2-authorizers/test/http/integ.lambda.js.snapshot/AuthorizerInteg.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-apigatewayv2-authorizers/test/http/integ.lambda.js.snapshot/AuthorizerInteg.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-apigatewayv2-authorizers/test/http/integ.lambda.js.snapshot/asset.0793b3c94d0be9d628975dbbcd1dc523196de50a41fb1920880248ae3c24259b.handler/index.js
  packages/@aws-cdk-testing/framework-integ/test/aws-apigatewayv2-authorizers/test/http/integ.lambda.js.snapshot/asset.54deaef2af5b9afbfc9cbcbb9261b1c0d4cce6560831d7ae1959f3da899011c8.handler/index.d.ts
  packages/@aws-cdk-testing/framework-integ/test/aws-apigatewayv2-authorizers/test/http/integ.lambda.js.snapshot/asset.54deaef2af5b9afbfc9cbcbb9261b1c0d4cce6560831d7ae1959f3da899011c8.handler/index.js
  packages/@aws-cdk-testing/framework-integ/test/aws-apigatewayv2-authorizers/test/http/integ.lambda.js.snapshot/asset.54deaef2af5b9afbfc9cbcbb9261b1c0d4cce6560831d7ae1959f3da899011c8.handler/index.ts
  packages/@aws-cdk-testing/framework-integ/test/aws-apigatewayv2-authorizers/test/http/integ.lambda.js.snapshot/asset.9b3143f6d2fe3103f2f3162c221163ad6a5a0ba2219cc1e5af2e300325588714/index.js
  packages/@aws-cdk-testing/framework-integ/test/aws-apigatewayv2-authorizers/test/http/integ.lambda.js.snapshot/asset.d7d3785243d748927f2a8d6edcecf909f96191df27a815e305aaeba98bcd2c64/index.d.ts
  packages/@aws-cdk-testing/framework-integ/test/aws-apigatewayv2-authorizers/test/http/integ.lambda.js.snapshot/asset.d7d3785243d748927f2a8d6edcecf909f96191df27a815e305aaeba98bcd2c64/index.js
  packages/@aws-cdk-testing/framework-integ/test/aws-apigatewayv2-authorizers/test/http/integ.lambda.js.snapshot/asset.d7d3785243d748927f2a8d6edcecf909f96191df27a815e305aaeba98bcd2c64/index.ts
  packages/@aws-cdk-testing/framework-integ/test/aws-apigatewayv2-authorizers/test/http/integ.lambda.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-apigatewayv2-authorizers/test/http/integ.lambda.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-apigatewayv2-authorizers/test/http/integ.lambda.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-apigatewayv2-authorizers/test/http/integ.lambda.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-apigatewayv2-authorizers/test/http/integ.lambda.ts
  packages/@aws-cdk-testing/framework-integ/test/aws-apigatewayv2-authorizers/test/http/integ.user-pool.js.snapshot/AuthorizerInteg.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-apigatewayv2-authorizers/test/http/integ.user-pool.js.snapshot/AuthorizerInteg.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-apigatewayv2-authorizers/test/http/integ.user-pool.js.snapshot/asset.305ef816d469be820f1dbbfee876dd1758bf6733bee4d3dba76995a755ac145a.handler/index.js
  packages/@aws-cdk-testing/framework-integ/test/aws-apigatewayv2-authorizers/test/http/integ.user-pool.js.snapshot/asset.867837e91f97aaf9c29d20a4fea18e3f520bb65d84e9bb59ec84058226225ffc.handler/index.d.ts
  packages/@aws-cdk-testing/framework-integ/test/aws-apigatewayv2-authorizers/test/http/integ.user-pool.js.snapshot/asset.867837e91f97aaf9c29d20a4fea18e3f520bb65d84e9bb59ec84058226225ffc.handler/index.js
  packages/@aws-cdk-testing/framework-integ/test/aws-apigatewayv2-authorizers/test/http/integ.user-pool.js.snapshot/asset.867837e91f97aaf9c29d20a4fea18e3f520bb65d84e9bb59ec84058226225ffc.handler/index.ts
  packages/@aws-cdk-testing/framework-integ/test/aws-apigatewayv2-authorizers/test/http/integ.user-pool.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-apigatewayv2-authorizers/test/http/integ.user-pool.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-apigatewayv2-authorizers/test/http/integ.user-pool.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-apigatewayv2-authorizers/test/http/integ.user-pool.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-apigatewayv2-authorizers/test/http/integ.user-pool.ts
  packages/aws-cdk-lib/aws-apigatewayv2-authorizers/README.md
  packages/aws-cdk-lib/aws-apigatewayv2-authorizers/lib/http/iam.ts
  packages/aws-cdk-lib/aws-apigatewayv2-authorizers/lib/http/jwt.ts
  packages/aws-cdk-lib/aws-apigatewayv2-authorizers/lib/http/lambda.ts
  packages/aws-cdk-lib/aws-apigatewayv2-authorizers/lib/http/user-pool.ts
  packages/aws-cdk-lib/aws-apigatewayv2-authorizers/test/http/jwt.test.ts
  packages/aws-cdk-lib/aws-apigatewayv2-authorizers/test/http/lambda.test.ts
  packages/aws-cdk-lib/aws-apigatewayv2-authorizers/test/http/user-pool.test.ts
  packages/aws-cdk-lib/aws-apigatewayv2/lib/http/authorizer.ts
Labels: p2, feature-request, effort/medium, beginning-contributor

#31565 chore(ec2): add kafka interface vpc endpoints
  packages/aws-cdk-lib/aws-ec2/lib/vpc-endpoint.ts
Labels: p2, distinguished-contributor

#31700 docs: note git-lfs prerequisite
  CONTRIBUTING.md
Labels: p2, beginning-contributor

#31713 fix(cli-lib): cannot bootstrap specific environment
  packages/@aws-cdk/cli-lib-alpha/lib/cli.ts
  packages/@aws-cdk/cli-lib-alpha/lib/commands/bootstrap.ts
  packages/@aws-cdk/cli-lib-alpha/test/commands.test.ts
Labels: bug, p2, effort/small, contribution/core, pr-linter/exempt-integ-test, pr/needs-maintainer-review

#31675 fix(elasticloadbalancingv2): `http2Enabled` with true is ignored in ApplicationLoadBalancer
  packages/@aws-cdk-testing/framework-integ/test/aws-elasticloadbalancingv2/test/integ.alb.attributes.js.snapshot/Elbv2TestDefaultTestDeployAssert82DC2DEA.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-elasticloadbalancingv2/test/integ.alb.attributes.js.snapshot/aws-cdk-elbv2-integ.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-elasticloadbalancingv2/test/integ.alb.attributes.js.snapshot/aws-cdk-elbv2-integ.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-elasticloadbalancingv2/test/integ.alb.attributes.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-elasticloadbalancingv2/test/integ.alb.attributes.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-elasticloadbalancingv2/test/integ.alb.attributes.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-elasticloadbalancingv2/test/integ.alb.attributes.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-elasticloadbalancingv2/test/integ.alb.attributes.ts
  packages/aws-cdk-lib/aws-elasticloadbalancingv2/lib/alb/application-load-balancer.ts
  packages/aws-cdk-lib/aws-elasticloadbalancingv2/test/alb/load-balancer.test.ts
Labels: bug, p2, effort/small, distinguished-contributor

#30395 chore(glue): support ConnectionType.MARKETPLACE and ConnectionType.CUSTOM
  packages/@aws-cdk/aws-glue-alpha/lib/connection.ts
Labels: p2, admired-contributor

#31718 docs(codebuild): updated Linux build image return type in doc
  packages/aws-cdk-lib/aws-codebuild/lib/linux-arm-build-image.ts
Labels: p2, effort/small, pr/needs-community-review, pr-linter/exemption-requested

#31721 chore(merge-back): 2.162.0
  CHANGELOG.v2.alpha.md
  CHANGELOG.v2.md
  version.v2.json
Labels: p2, pr/needs-community-review, pr/no-squash, auto-approve

#30207 feat(fsx): support HDD storage type for a Lustre file systems
  packages/@aws-cdk-testing/framework-integ/test/aws-fsx/test/integ.lustre-file-system-storage-type.js.snapshot/FsxLustreStorageTypeStack.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-fsx/test/integ.lustre-file-system-storage-type.js.snapshot/FsxLustreStorageTypeStack.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-fsx/test/integ.lustre-file-system-storage-type.js.snapshot/FsxLustreStorageTypeTestDefaultTestDeployAssert50B0FE3D.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-fsx/test/integ.lustre-file-system-storage-type.js.snapshot/FsxLustreStorageTypeTestDefaultTestDeployAssert50B0FE3D.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-fsx/test/integ.lustre-file-system-storage-type.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-fsx/test/integ.lustre-file-system-storage-type.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-fsx/test/integ.lustre-file-system-storage-type.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-fsx/test/integ.lustre-file-system-storage-type.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-fsx/test/integ.lustre-file-system-storage-type.ts
  packages/aws-cdk-lib/aws-fsx/README.md
  packages/aws-cdk-lib/aws-fsx/lib/file-system.ts
  packages/aws-cdk-lib/aws-fsx/lib/lustre-file-system.ts
  packages/aws-cdk-lib/aws-fsx/test/lustre-file-system.test.ts
Labels: p2, feature-request, effort/medium, star-contributor

#31727 fix(cli): `cdk import` errors with 'S3 error: Access Denied'
  packages/aws-cdk/lib/api/deployments.ts
  packages/aws-cdk/lib/api/util/cloudformation.ts
  packages/aws-cdk/lib/cdk-toolkit.ts
Labels: bug, p1, effort/medium, contribution/core, pr-linter/exempt-test, pr-linter/exempt-integ-test, pr-linter/cli-integ-tested

#31732 chore(release): 2.162.1
  CHANGELOG.v2.alpha.md
  CHANGELOG.v2.md
  packages/aws-cdk/lib/api/deployments.ts
  packages/aws-cdk/lib/api/util/cloudformation.ts
  packages/aws-cdk/lib/cdk-toolkit.ts
  version.v2.json
Labels: p2, contribution/core, pr/no-squash, pr-linter/cli-integ-tested

#31648 chore(rds): modify the ACU limit for serverless v2 from 128 to 256
  packages/@aws-cdk-testing/framework-integ/test/aws-rds/test/integ.cluster-serverless-v2-acu.js.snapshot/asset.bde7b5c89cb43285f884c94f0b9e17cdb0f5eb5345005114dd60342e0b8a85a1/__entrypoint__.js
  packages/@aws-cdk-testing/framework-integ/test/aws-rds/test/integ.cluster-serverless-v2-acu.js.snapshot/asset.bde7b5c89cb43285f884c94f0b9e17cdb0f5eb5345005114dd60342e0b8a85a1/index.js
  packages/@aws-cdk-testing/framework-integ/test/aws-rds/test/integ.cluster-serverless-v2-acu.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-rds/test/integ.cluster-serverless-v2-acu.js.snapshot/integ-aurora-serverlessv2-cluster-acu.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-rds/test/integ.cluster-serverless-v2-acu.js.snapshot/integ-aurora-serverlessv2-cluster-acu.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-rds/test/integ.cluster-serverless-v2-acu.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-rds/test/integ.cluster-serverless-v2-acu.js.snapshot/integtestacuDefaultTestDeployAssert17F73A1A.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-rds/test/integ.cluster-serverless-v2-acu.js.snapshot/integtestacuDefaultTestDeployAssert17F73A1A.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-rds/test/integ.cluster-serverless-v2-acu.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-rds/test/integ.cluster-serverless-v2-acu.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-rds/test/integ.cluster-serverless-v2-acu.ts
  packages/aws-cdk-lib/aws-rds/lib/cluster.ts
  packages/aws-cdk-lib/aws-rds/test/cluster.test.ts
Labels: p2, distinguished-contributor, pr-linter/exemption-requested

#30611 feat(ecs-patterns): support NLB with TLS listener and target group
  packages/@aws-cdk-testing/framework-integ/README.md
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs-patterns/test/ec2/integ.tls-network-load-balanced-ecs-service.js.snapshot/asset.bde7b5c89cb43285f884c94f0b9e17cdb0f5eb5345005114dd60342e0b8a85a1/__entrypoint__.js
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs-patterns/test/ec2/integ.tls-network-load-balanced-ecs-service.js.snapshot/asset.bde7b5c89cb43285f884c94f0b9e17cdb0f5eb5345005114dd60342e0b8a85a1/index.js
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs-patterns/test/ec2/integ.tls-network-load-balanced-ecs-service.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs-patterns/test/ec2/integ.tls-network-load-balanced-ecs-service.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs-patterns/test/ec2/integ.tls-network-load-balanced-ecs-service.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs-patterns/test/ec2/integ.tls-network-load-balanced-ecs-service.js.snapshot/networkLoadBalancedEc2ServiceTestDefaultTestDeployAssert34DAD7DE.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs-patterns/test/ec2/integ.tls-network-load-balanced-ecs-service.js.snapshot/networkLoadBalancedEc2ServiceTestDefaultTestDeployAssert34DAD7DE.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs-patterns/test/ec2/integ.tls-network-load-balanced-ecs-service.js.snapshot/tls-network-load-balanced-ecs-service.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs-patterns/test/ec2/integ.tls-network-load-balanced-ecs-service.js.snapshot/tls-network-load-balanced-ecs-service.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs-patterns/test/ec2/integ.tls-network-load-balanced-ecs-service.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs-patterns/test/ec2/integ.tls-network-load-balanced-ecs-service.ts
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs-patterns/test/fargate/integ.tls-network-load-balanced-fargate-service.js.snapshot/asset.bde7b5c89cb43285f884c94f0b9e17cdb0f5eb5345005114dd60342e0b8a85a1/__entrypoint__.js
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs-patterns/test/fargate/integ.tls-network-load-balanced-fargate-service.js.snapshot/asset.bde7b5c89cb43285f884c94f0b9e17cdb0f5eb5345005114dd60342e0b8a85a1/index.js
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs-patterns/test/fargate/integ.tls-network-load-balanced-fargate-service.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs-patterns/test/fargate/integ.tls-network-load-balanced-fargate-service.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs-patterns/test/fargate/integ.tls-network-load-balanced-fargate-service.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs-patterns/test/fargate/integ.tls-network-load-balanced-fargate-service.js.snapshot/networkLoadBalancedFargateServiceTestDefaultTestDeployAssertBFBAA75B.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs-patterns/test/fargate/integ.tls-network-load-balanced-fargate-service.js.snapshot/networkLoadBalancedFargateServiceTestDefaultTestDeployAssertBFBAA75B.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs-patterns/test/fargate/integ.tls-network-load-balanced-fargate-service.js.snapshot/tls-network-load-balanced-fargate-service.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs-patterns/test/fargate/integ.tls-network-load-balanced-fargate-service.js.snapshot/tls-network-load-balanced-fargate-service.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs-patterns/test/fargate/integ.tls-network-load-balanced-fargate-service.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs-patterns/test/fargate/integ.tls-network-load-balanced-fargate-service.ts
  packages/aws-cdk-lib/aws-ecs-patterns/README.md
  packages/aws-cdk-lib/aws-ecs-patterns/lib/base/network-load-balanced-service-base.ts
  packages/aws-cdk-lib/aws-ecs-patterns/test/ec2/l3s.test.ts
  packages/aws-cdk-lib/aws-ecs-patterns/test/fargate/load-balanced-fargate-service.test.ts
Labels: p1, feature-request, effort/medium, beginning-contributor

#31619 feat(step-functions): add bucketNamePath in item reader
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions/test/integ.s3-json-item-reader.js.snapshot/IntegTestDefaultTestDeployAssertE3E7D2A4.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions/test/integ.s3-json-item-reader.js.snapshot/IntegTestDefaultTestDeployAssertE3E7D2A4.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions/test/integ.s3-json-item-reader.js.snapshot/S3JsonItemReaderTestStack.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions/test/integ.s3-json-item-reader.js.snapshot/S3JsonItemReaderTestStack.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions/test/integ.s3-json-item-reader.js.snapshot/asset.44e9c4d7a5d3fd2d677e1a7e416b2b56f6b0104bd5eff9cac5557b4c65a9dc61/index.js
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions/test/integ.s3-json-item-reader.js.snapshot/asset.da514df694ce3f41453746a766ae6aff13c869c38002598930d6d34e5711985b.bundle/index.js
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions/test/integ.s3-json-item-reader.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions/test/integ.s3-json-item-reader.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions/test/integ.s3-json-item-reader.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions/test/integ.s3-json-item-reader.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions/test/integ.s3-json-item-reader.ts
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions/test/integ.s3-objects-item-reader.js.snapshot/IntegTestDefaultTestDeployAssertE3E7D2A4.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions/test/integ.s3-objects-item-reader.js.snapshot/IntegTestDefaultTestDeployAssertE3E7D2A4.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions/test/integ.s3-objects-item-reader.js.snapshot/S3ObjectsItemReaderTestStack.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions/test/integ.s3-objects-item-reader.js.snapshot/S3ObjectsItemReaderTestStack.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions/test/integ.s3-objects-item-reader.js.snapshot/asset.30e7020514effbaf2e0bf3983c7c37c6733aec254148a8f866da92fbbd7a4fb6.bundle/index.js
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions/test/integ.s3-objects-item-reader.js.snapshot/asset.44e9c4d7a5d3fd2d677e1a7e416b2b56f6b0104bd5eff9cac5557b4c65a9dc61/index.js
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions/test/integ.s3-objects-item-reader.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions/test/integ.s3-objects-item-reader.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions/test/integ.s3-objects-item-reader.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions/test/integ.s3-objects-item-reader.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions/test/integ.s3-objects-item-reader.ts
  packages/aws-cdk-lib/aws-stepfunctions/README.md
  packages/aws-cdk-lib/aws-stepfunctions/lib/states/distributed-map.ts
  packages/aws-cdk-lib/aws-stepfunctions/lib/states/distributed-map/item-reader.ts
  packages/aws-cdk-lib/aws-stepfunctions/test/distributed-map.test.ts
Labels: p2, feature-request, effort/medium, beginning-contributor

#31751 chore: suppress a type error
  tools/@aws-cdk/node-bundle/src/api/bundle.ts
Labels: p2, contribution/core

#31752 feat: update L1 CloudFormation resource definitions
  packages/@aws-cdk/cloudformation-diff/package.json
  packages/@aws-cdk/integ-runner/package.json
  packages/aws-cdk-lib/package.json
  tools/@aws-cdk/spec2cdk/package.json
  yarn.lock
Labels: p2, dependencies, contribution/core, pr-linter/exempt-readme, pr-linter/exempt-test, auto-approve, pr-linter/exempt-integ-test

#31623 feat: disallow cross account asset publishing in some scenarios
  packages/aws-cdk/lib/api/deploy-stack.ts
  packages/aws-cdk/lib/api/deployments.ts
  packages/aws-cdk/lib/api/util/checks.ts
  packages/aws-cdk/lib/util/asset-publishing.ts
  packages/aws-cdk/package.json
  packages/aws-cdk/test/api/bootstrap.test.ts
  packages/aws-cdk/test/api/deploy-stack.test.ts
  packages/aws-cdk/test/api/util/checks.test.ts
  yarn.lock
Labels: p2, contribution/core, pr-linter/exempt-readme, pr-linter/exempt-integ-test, pr-linter/cli-integ-tested

#31734 chore(apigatewayv2): rephrased the documentation for HttpApiProps.disableExecuteApiEndpoint to make it more clearer.
  packages/aws-cdk-lib/aws-apigatewayv2/lib/http/api.ts
Labels: p2, contribution/core

#31733 chore(merge-back): 2.162.1
  CHANGELOG.v2.alpha.md
  CHANGELOG.v2.md
  version.v2.json
Labels: p2, pr/no-squash, auto-approve

#31385 feat(rds): support performance insights configuration at cluster level
  packages/@aws-cdk-testing/framework-integ/test/aws-rds/test/integ.cluster-performance-insights.js.snapshot/aws-cdk-rds-integ-cluster-performance-insights.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-rds/test/integ.cluster-performance-insights.js.snapshot/aws-cdk-rds-integ-cluster-performance-insights.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-rds/test/integ.cluster-performance-insights.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-rds/test/integ.cluster-performance-insights.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-rds/test/integ.cluster-performance-insights.js.snapshot/integclusterperformanceinsightsDefaultTestDeployAssert60BCBDC0.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-rds/test/integ.cluster-performance-insights.js.snapshot/integclusterperformanceinsightsDefaultTestDeployAssert60BCBDC0.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-rds/test/integ.cluster-performance-insights.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-rds/test/integ.cluster-performance-insights.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-rds/test/integ.cluster-performance-insights.ts
  packages/aws-cdk-lib/aws-rds/README.md
  packages/aws-cdk-lib/aws-rds/lib/aurora-cluster-instance.ts
  packages/aws-cdk-lib/aws-rds/lib/cluster.ts
  packages/aws-cdk-lib/aws-rds/test/cluster.test.ts
Labels: p2, feature-request, effort/medium, distinguished-contributor

#31701 fix(lambda): filterRule.null() returns empty array
  allowed-breaking-changes.txt
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-event-sources/test/integ.sqs-null-filter.js.snapshot/FilterCriteriaNullDefaultTestDeployAssert51179964.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-event-sources/test/integ.sqs-null-filter.js.snapshot/FilterCriteriaNullDefaultTestDeployAssert51179964.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-event-sources/test/integ.sqs-null-filter.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-event-sources/test/integ.sqs-null-filter.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-event-sources/test/integ.sqs-null-filter.js.snapshot/lambda-event-source-filter-criteria-null.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-event-sources/test/integ.sqs-null-filter.js.snapshot/lambda-event-source-filter-criteria-null.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-event-sources/test/integ.sqs-null-filter.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-event-sources/test/integ.sqs-null-filter.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-event-sources/test/integ.sqs-null-filter.ts
  packages/aws-cdk-lib/aws-lambda/lib/event-source-filter.ts
Labels: bug, p1, effort/medium, contribution/core, pr-linter/exempt-breaking-change

#31769 chore(rds): support 11.4.3 engine version for MariaDB
  packages/aws-cdk-lib/aws-rds/lib/instance-engine.ts
  packages/aws-cdk-lib/aws-rds/test/instance-engine.test.ts
Labels: p2, distinguished-contributor

#31775 chore(mergify): move deprecated parameters from `pull_request_rules` to `queue_rules`
  .mergify.yml
Labels: p2, contribution/core

#31312 feat(pipes-enrichments): support API destination enrichment
  packages/@aws-cdk/aws-pipes-enrichments-alpha/README.md
  packages/@aws-cdk/aws-pipes-enrichments-alpha/lib/api-destination.ts
  packages/@aws-cdk/aws-pipes-enrichments-alpha/lib/index.ts
  packages/@aws-cdk/aws-pipes-enrichments-alpha/rosetta/default.ts-fixture
  packages/@aws-cdk/aws-pipes-enrichments-alpha/test/__snapshots__/api-destination.test.ts.snap
  packages/@aws-cdk/aws-pipes-enrichments-alpha/test/api-destination.test.ts
  packages/@aws-cdk/aws-pipes-enrichments-alpha/test/integ.api-destination.js.snapshot/asset.3cef2cdbb46b3821e641ffb8b9af9731af5f7e4a9e857ab633dbcd9023de724d.bundle/index.js
  packages/@aws-cdk/aws-pipes-enrichments-alpha/test/integ.api-destination.js.snapshot/aws-cdk-pipes-enrichments-lambda.assets.json
  packages/@aws-cdk/aws-pipes-enrichments-alpha/test/integ.api-destination.js.snapshot/aws-cdk-pipes-enrichments-lambda.template.json
  packages/@aws-cdk/aws-pipes-enrichments-alpha/test/integ.api-destination.js.snapshot/cdk.out
  packages/@aws-cdk/aws-pipes-enrichments-alpha/test/integ.api-destination.js.snapshot/integ.json
  packages/@aws-cdk/aws-pipes-enrichments-alpha/test/integ.api-destination.js.snapshot/integtestpipeenrichmentslambdaDefaultTestDeployAssert88DF3044.assets.json
  packages/@aws-cdk/aws-pipes-enrichments-alpha/test/integ.api-destination.js.snapshot/integtestpipeenrichmentslambdaDefaultTestDeployAssert88DF3044.template.json
  packages/@aws-cdk/aws-pipes-enrichments-alpha/test/integ.api-destination.js.snapshot/manifest.json
  packages/@aws-cdk/aws-pipes-enrichments-alpha/test/integ.api-destination.js.snapshot/tree.json
  packages/@aws-cdk/aws-pipes-enrichments-alpha/test/integ.api-destination.ts
Labels: p2, feature-request, effort/medium, distinguished-contributor

#30665 feat(pipes-targets): add CloudWatch Logs
  packages/@aws-cdk/aws-pipes-targets-alpha/README.md
  packages/@aws-cdk/aws-pipes-targets-alpha/lib/cloudwatch-logs.ts
  packages/@aws-cdk/aws-pipes-targets-alpha/lib/index.ts
  packages/@aws-cdk/aws-pipes-targets-alpha/rosetta/default.ts-fixture
  packages/@aws-cdk/aws-pipes-targets-alpha/test/__snapshots__/cloudwatch-logs.test.ts.snap
  packages/@aws-cdk/aws-pipes-targets-alpha/test/cloudwatch-logs.test.ts
  packages/@aws-cdk/aws-pipes-targets-alpha/test/integ.cloudwatch-logs.js.snapshot/asset.da514df694ce3f41453746a766ae6aff13c869c38002598930d6d34e5711985b.bundle/index.js
  packages/@aws-cdk/aws-pipes-targets-alpha/test/integ.cloudwatch-logs.js.snapshot/aws-cdk-pipes-targets-cwl.assets.json
  packages/@aws-cdk/aws-pipes-targets-alpha/test/integ.cloudwatch-logs.js.snapshot/aws-cdk-pipes-targets-cwl.template.json
  packages/@aws-cdk/aws-pipes-targets-alpha/test/integ.cloudwatch-logs.js.snapshot/cdk.out
  packages/@aws-cdk/aws-pipes-targets-alpha/test/integ.cloudwatch-logs.js.snapshot/integ.json
  packages/@aws-cdk/aws-pipes-targets-alpha/test/integ.cloudwatch-logs.js.snapshot/integtestpipetargetcwlDefaultTestDeployAssert4A6B8BD3.assets.json
  packages/@aws-cdk/aws-pipes-targets-alpha/test/integ.cloudwatch-logs.js.snapshot/integtestpipetargetcwlDefaultTestDeployAssert4A6B8BD3.template.json
  packages/@aws-cdk/aws-pipes-targets-alpha/test/integ.cloudwatch-logs.js.snapshot/manifest.json
  packages/@aws-cdk/aws-pipes-targets-alpha/test/integ.cloudwatch-logs.js.snapshot/tree.json
  packages/@aws-cdk/aws-pipes-targets-alpha/test/integ.cloudwatch-logs.ts
Labels: p2, distinguished-contributor

#30620 feat(ec2): disable api termination
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.instance-disable-api-termination.js.snapshot/asset.358df072f638d226bc60515a98fa15305e91193108367a0fa01dc626fb9b07d6.bundle/index.js
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.instance-disable-api-termination.js.snapshot/asset.bde7b5c89cb43285f884c94f0b9e17cdb0f5eb5345005114dd60342e0b8a85a1/__entrypoint__.js
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.instance-disable-api-termination.js.snapshot/asset.bde7b5c89cb43285f884c94f0b9e17cdb0f5eb5345005114dd60342e0b8a85a1/index.js
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.instance-disable-api-termination.js.snapshot/aws-cdk-ec2-disable-api-termination.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.instance-disable-api-termination.js.snapshot/aws-cdk-ec2-disable-api-termination.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.instance-disable-api-termination.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.instance-disable-api-termination.js.snapshot/instancedisableapiterminationDefaultTestDeployAssertE3D2E0F8.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.instance-disable-api-termination.js.snapshot/instancedisableapiterminationDefaultTestDeployAssertE3D2E0F8.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.instance-disable-api-termination.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.instance-disable-api-termination.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.instance-disable-api-termination.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.instance-disable-api-termination.ts
  packages/aws-cdk-lib/aws-ec2/README.md
  packages/aws-cdk-lib/aws-ec2/lib/instance.ts
  packages/aws-cdk-lib/aws-ec2/test/instance.test.ts
Labels: p2, beginning-contributor

#30560 feat(dynamodb): enable contributor insights for global secondary index
  packages/@aws-cdk-testing/framework-integ/test/aws-dynamodb/test/integ.dynamodb.contirubtor-insights-for-gsi.js.snapshot/aws-cdk-dynamodb-contributor-insights-for-gsi.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-dynamodb/test/integ.dynamodb.contirubtor-insights-for-gsi.js.snapshot/aws-cdk-dynamodb-contributor-insights-for-gsi.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-dynamodb/test/integ.dynamodb.contirubtor-insights-for-gsi.js.snapshot/awscdkdynamodbcontributorinsightsforgsitestDefaultTestDeployAssert9D8EC318.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-dynamodb/test/integ.dynamodb.contirubtor-insights-for-gsi.js.snapshot/awscdkdynamodbcontributorinsightsforgsitestDefaultTestDeployAssert9D8EC318.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-dynamodb/test/integ.dynamodb.contirubtor-insights-for-gsi.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-dynamodb/test/integ.dynamodb.contirubtor-insights-for-gsi.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-dynamodb/test/integ.dynamodb.contirubtor-insights-for-gsi.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-dynamodb/test/integ.dynamodb.contirubtor-insights-for-gsi.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-dynamodb/test/integ.dynamodb.contirubtor-insights-for-gsi.ts
  packages/aws-cdk-lib/aws-dynamodb/README.md
  packages/aws-cdk-lib/aws-dynamodb/lib/table.ts
  packages/aws-cdk-lib/aws-dynamodb/test/dynamodb.test.ts
Labels: p2, feature-request, effort/small, star-contributor

#31136 feat(fsx): specify file system type version for the Lustre file system
  packages/@aws-cdk-testing/framework-integ/test/aws-fsx/test/integ.lustre-file-system-file-system-type-version.js.snapshot/FsxLustreFileSystemTypeVersionStack.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-fsx/test/integ.lustre-file-system-file-system-type-version.js.snapshot/FsxLustreFileSystemTypeVersionStack.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-fsx/test/integ.lustre-file-system-file-system-type-version.js.snapshot/FsxLustreFileSystemTypeVersionTestDefaultTestDeployAssert045329BD.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-fsx/test/integ.lustre-file-system-file-system-type-version.js.snapshot/FsxLustreFileSystemTypeVersionTestDefaultTestDeployAssert045329BD.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-fsx/test/integ.lustre-file-system-file-system-type-version.js.snapshot/asset.bde7b5c89cb43285f884c94f0b9e17cdb0f5eb5345005114dd60342e0b8a85a1/__entrypoint__.js
  packages/@aws-cdk-testing/framework-integ/test/aws-fsx/test/integ.lustre-file-system-file-system-type-version.js.snapshot/asset.bde7b5c89cb43285f884c94f0b9e17cdb0f5eb5345005114dd60342e0b8a85a1/index.js
  packages/@aws-cdk-testing/framework-integ/test/aws-fsx/test/integ.lustre-file-system-file-system-type-version.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-fsx/test/integ.lustre-file-system-file-system-type-version.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-fsx/test/integ.lustre-file-system-file-system-type-version.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-fsx/test/integ.lustre-file-system-file-system-type-version.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-fsx/test/integ.lustre-file-system-file-system-type-version.ts
  packages/aws-cdk-lib/aws-fsx/README.md
  packages/aws-cdk-lib/aws-fsx/lib/lustre-file-system.ts
  packages/aws-cdk-lib/aws-fsx/test/lustre-file-system.test.ts
Labels: p2, feature-request, effort/small, distinguished-contributor

#31723 feat(kinesisfirehose-alpha): refactor sourceStream property to support multiple types of sources
  packages/@aws-cdk/aws-kinesisfirehose-alpha/README.md
  packages/@aws-cdk/aws-kinesisfirehose-alpha/lib/delivery-stream.ts
  packages/@aws-cdk/aws-kinesisfirehose-alpha/lib/index.ts
  packages/@aws-cdk/aws-kinesisfirehose-alpha/lib/source.ts
  packages/@aws-cdk/aws-kinesisfirehose-alpha/test/delivery-stream.test.ts
  packages/@aws-cdk/aws-kinesisfirehose-alpha/test/integ.delivery-stream.source-stream.ts
Labels: p2, contribution/core, pr-linter/exempt-integ-test

#31793 feat(iam): allow creating service principal using custom name
  packages/@aws-cdk-testing/framework-integ/test/aws-iam/test/integ.emr-service-principal-cn-partition.js.snapshot/EmrServicePrincipalAssertionStack.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-iam/test/integ.emr-service-principal-cn-partition.js.snapshot/EmrServicePrincipalAssertionStack.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-iam/test/integ.emr-service-principal-cn-partition.js.snapshot/EmrServicePrincipalTestingStack.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-iam/test/integ.emr-service-principal-cn-partition.js.snapshot/EmrServicePrincipalTestingStack.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-iam/test/integ.emr-service-principal-cn-partition.js.snapshot/asset.30e7020514effbaf2e0bf3983c7c37c6733aec254148a8f866da92fbbd7a4fb6.bundle/index.js
  packages/@aws-cdk-testing/framework-integ/test/aws-iam/test/integ.emr-service-principal-cn-partition.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-iam/test/integ.emr-service-principal-cn-partition.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-iam/test/integ.emr-service-principal-cn-partition.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-iam/test/integ.emr-service-principal-cn-partition.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-iam/test/integ.emr-service-principal-cn-partition.ts
  packages/@aws-cdk/integ-runner/lib/runner/runner-base.ts
  packages/aws-cdk-lib/aws-iam/README.md
  packages/aws-cdk-lib/aws-iam/lib/principals.ts
  packages/aws-cdk-lib/aws-iam/test/principals.test.ts
Labels: bug, p2, effort/small, contribution/core, pr/needs-maintainer-review

#31676 feat(kms): allow `fromLookup` method to return dummy key if target key was not found
  packages/@aws-cdk-testing/framework-integ/test/aws-kms/test/integ.key-from-lookup-dummy.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-kms/test/integ.key-from-lookup-dummy.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-kms/test/integ.key-from-lookup-dummy.js.snapshot/key-from-lookup-dummy.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-kms/test/integ.key-from-lookup-dummy.js.snapshot/key-from-lookup-dummy.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-kms/test/integ.key-from-lookup-dummy.js.snapshot/keyfromlookupdummyintegDefaultTestDeployAssert59B83056.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-kms/test/integ.key-from-lookup-dummy.js.snapshot/keyfromlookupdummyintegDefaultTestDeployAssert59B83056.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-kms/test/integ.key-from-lookup-dummy.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-kms/test/integ.key-from-lookup-dummy.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-kms/test/integ.key-from-lookup-dummy.ts
  packages/aws-cdk-lib/aws-kms/README.md
  packages/aws-cdk-lib/aws-kms/lib/key-lookup.ts
  packages/aws-cdk-lib/aws-kms/lib/key.ts
  packages/aws-cdk-lib/aws-kms/test/key.from-lookup.test.ts
  packages/aws-cdk-lib/core/lib/context-provider.ts
  packages/aws-cdk/lib/context-providers/keys.ts
  packages/aws-cdk/test/context-providers/keys.test.ts
Labels: p2, feature-request, effort/small, distinguished-contributor, pr-linter/cli-integ-tested, pr-linter/exemption-requested

#31632 feat(cognito): support `emailVerified` for `AttributeMapping` interface
  packages/@aws-cdk-testing/framework-integ/test/aws-cognito/test/integ.user-pool-idp.apple.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-cognito/test/integ.user-pool-idp.apple.js.snapshot/integ-user-pool-idp-apple.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-cognito/test/integ.user-pool-idp.apple.js.snapshot/integ-user-pool-idp-apple.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-cognito/test/integ.user-pool-idp.apple.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-cognito/test/integ.user-pool-idp.apple.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-cognito/test/integ.user-pool-idp.apple.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-cognito/test/integ.user-pool-idp.apple.ts
  packages/@aws-cdk-testing/framework-integ/test/aws-cognito/test/integ.user-pool-idp.google.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-cognito/test/integ.user-pool-idp.google.js.snapshot/integ-user-pool-idp-google.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-cognito/test/integ.user-pool-idp.google.js.snapshot/integ-user-pool-idp-google.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-cognito/test/integ.user-pool-idp.google.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-cognito/test/integ.user-pool-idp.google.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-cognito/test/integ.user-pool-idp.google.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-cognito/test/integ.user-pool-idp.google.ts
  packages/@aws-cdk-testing/framework-integ/test/aws-cognito/test/integ.user-pool-idp.oidc.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-cognito/test/integ.user-pool-idp.oidc.js.snapshot/integ-user-pool-idp-google.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-cognito/test/integ.user-pool-idp.oidc.js.snapshot/integ-user-pool-idp-google.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-cognito/test/integ.user-pool-idp.oidc.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-cognito/test/integ.user-pool-idp.oidc.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-cognito/test/integ.user-pool-idp.oidc.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-cognito/test/integ.user-pool-idp.oidc.ts
  packages/aws-cdk-lib/aws-cognito/README.md
  packages/aws-cdk-lib/aws-cognito/lib/user-pool-idps/base.ts
  packages/aws-cdk-lib/aws-cognito/test/user-pool-idps/apple.test.ts
  packages/aws-cdk-lib/aws-cognito/test/user-pool-idps/google.test.ts
Labels: bug, p2, effort/medium, beginning-contributor, pr-linter/exemption-requested

#31800 feat: update L1 CloudFormation resource definitions
  packages/@aws-cdk/cloudformation-diff/package.json
  packages/@aws-cdk/integ-runner/package.json
  packages/aws-cdk-lib/package.json
  tools/@aws-cdk/spec2cdk/package.json
  yarn.lock
Labels: p2, dependencies, contribution/core, pr-linter/exempt-readme, pr-linter/exempt-test, auto-approve, pr-linter/exempt-integ-test, pr/needs-maintainer-review

#31809 chore: remove legacy unused job for v2 migration
  .github/workflows/v2-pull-request.yml
Labels: p2, contribution/core

#31778 feat(s3): support `transitionDefaultMinimumObjectSize` for life cycle
  packages/@aws-cdk-testing/framework-integ/test/aws-s3/test/integ.lifecycle-transitions.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-s3/test/integ.lifecycle-transitions.js.snapshot/cdkintegs3lifecycletransitionsDefaultTestDeployAssert9A611ED6.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-s3/test/integ.lifecycle-transitions.js.snapshot/cdkintegs3lifecycletransitionsDefaultTestDeployAssert9A611ED6.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-s3/test/integ.lifecycle-transitions.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-s3/test/integ.lifecycle-transitions.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-s3/test/integ.lifecycle-transitions.js.snapshot/s3-lifecycle-transitions.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-s3/test/integ.lifecycle-transitions.js.snapshot/s3-lifecycle-transitions.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-s3/test/integ.lifecycle-transitions.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-s3/test/integ.lifecycle-transitions.ts
  packages/aws-cdk-lib/aws-s3/README.md
  packages/aws-cdk-lib/aws-s3/lib/bucket.ts
  packages/aws-cdk-lib/aws-s3/test/bucket.test.ts
Labels: p2, feature-request, pr/needs-community-review, distinguished-contributor

#31184 feat(efs): allow AccessPoint to set client token
  packages/@aws-cdk-testing/framework-integ/test/aws-efs/test/integ.efs.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-efs/test/integ.efs.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-efs/test/integ.efs.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-efs/test/integ.efs.js.snapshot/test-efs-integ.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-efs/test/integ.efs.js.snapshot/test-efs-integ.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-efs/test/integ.efs.js.snapshot/testefsintegtestDefaultTestDeployAssert7E1529D5.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-efs/test/integ.efs.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-efs/test/integ.efs.ts
  packages/aws-cdk-lib/aws-efs/README.md
  packages/aws-cdk-lib/aws-efs/lib/access-point.ts
  packages/aws-cdk-lib/aws-efs/test/access-point.test.ts
Labels: p2, beginning-contributor

#31803 feat(rds): support local write forwarding for an aurora PostgreSQL cluster
  packages/@aws-cdk-testing/framework-integ/test/aws-rds/test/integ.cluster-enable-local-write-forwarding.js.snapshot/EnableLocalWriteForwardingClusterStack.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-rds/test/integ.cluster-enable-local-write-forwarding.js.snapshot/EnableLocalWriteForwardingClusterStack.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-rds/test/integ.cluster-enable-local-write-forwarding.js.snapshot/EnableLocalWriteForwardingClusterStackIntegDefaultTestDeployAssertFA53AD26.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-rds/test/integ.cluster-enable-local-write-forwarding.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-rds/test/integ.cluster-enable-local-write-forwarding.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-rds/test/integ.cluster-enable-local-write-forwarding.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-rds/test/integ.cluster-enable-local-write-forwarding.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-rds/test/integ.cluster-enable-local-write-forwarding.ts
  packages/aws-cdk-lib/aws-rds/README.md
  packages/aws-cdk-lib/aws-rds/lib/cluster.ts
  packages/aws-cdk-lib/aws-rds/test/cluster.test.ts
Labels: p2, feature-request, distinguished-contributor

#30628 feat(events): dead letter queue for an Event Bus
  packages/@aws-cdk-testing/framework-integ/test/aws-events/test/integ.eventbus.js.snapshot/Stack.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-events/test/integ.eventbus.js.snapshot/Stack.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-events/test/integ.eventbus.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-events/test/integ.eventbus.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-events/test/integ.eventbus.ts
  packages/aws-cdk-lib/aws-events/README.md
  packages/aws-cdk-lib/aws-events/lib/event-bus.ts
  packages/aws-cdk-lib/aws-events/test/event-bus.test.ts
Labels: p2, feature-request, effort/small, distinguished-contributor, pr/needs-maintainer-review

#31813 fix(s3): add support for uppercase characters in legacy bucket names
  packages/@aws-cdk-testing/framework-integ/test/aws-s3/test/integ.bucket-legacy-naming.js.snapshot/aws-cdk-s3-legacy-name-integ.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-s3/test/integ.bucket-legacy-naming.js.snapshot/aws-cdk-s3-legacy-name-integ.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-s3/test/integ.bucket-legacy-naming.js.snapshot/awscdks3integtestDefaultTestDeployAssert9DECDFBF.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-s3/test/integ.bucket-legacy-naming.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-s3/test/integ.bucket-legacy-naming.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-s3/test/integ.bucket-legacy-naming.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-s3/test/integ.bucket-legacy-naming.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-s3/test/integ.bucket-legacy-naming.ts
  packages/aws-cdk-lib/aws-s3/lib/bucket.ts
  packages/aws-cdk-lib/aws-s3/test/bucket.test.ts
Labels: bug, p2, pr/needs-community-review, effort/medium, beginning-contributor

#31799 fix(scheduler-alpha): remove `targetOverrides` prop from Schedule
  packages/@aws-cdk/aws-scheduler-alpha/README.md
  packages/@aws-cdk/aws-scheduler-alpha/lib/schedule.ts
  packages/@aws-cdk/aws-scheduler-alpha/test/input.test.ts
  packages/@aws-cdk/aws-scheduler-alpha/test/integ.schedule.js.snapshot/aws-cdk-scheduler-schedule.assets.json
  packages/@aws-cdk/aws-scheduler-alpha/test/integ.schedule.js.snapshot/aws-cdk-scheduler-schedule.template.json
  packages/@aws-cdk/aws-scheduler-alpha/test/integ.schedule.js.snapshot/cdk.out
  packages/@aws-cdk/aws-scheduler-alpha/test/integ.schedule.js.snapshot/integ.json
  packages/@aws-cdk/aws-scheduler-alpha/test/integ.schedule.js.snapshot/integtestscheduleDefaultTestDeployAssert24CB3896.assets.json
  packages/@aws-cdk/aws-scheduler-alpha/test/integ.schedule.js.snapshot/manifest.json
  packages/@aws-cdk/aws-scheduler-alpha/test/integ.schedule.js.snapshot/tree.json
  packages/@aws-cdk/aws-scheduler-alpha/test/integ.schedule.ts
  packages/@aws-cdk/aws-scheduler-alpha/test/retry-policy.test.ts
Labels: p2, contribution/core

#31611 feat(cli): garbage collect s3 assets (under `--unstable` flag)
  packages/@aws-cdk-testing/cli-integ/lib/with-cdk-app.ts
  packages/@aws-cdk-testing/cli-integ/tests/cli-integ-tests/garbage-collection.integtest.ts
  packages/aws-cdk/README.md
  packages/aws-cdk/lib/api/garbage-collection/garbage-collector.ts
  packages/aws-cdk/lib/api/garbage-collection/progress-printer.ts
  packages/aws-cdk/lib/api/garbage-collection/stack-refresh.ts
  packages/aws-cdk/lib/api/index.ts
  packages/aws-cdk/lib/cdk-toolkit.ts
  packages/aws-cdk/lib/cli.ts
  packages/aws-cdk/lib/settings.ts
  packages/aws-cdk/test/api/garbage-collection.test.ts
Labels: p2, contribution/core, pr-linter/exempt-integ-test, pr-linter/cli-integ-tested

#31776 feat(iot): scheduled audit
  packages/@aws-cdk/aws-iot-alpha/README.md
  packages/@aws-cdk/aws-iot-alpha/lib/index.ts
  packages/@aws-cdk/aws-iot-alpha/lib/scheduled-audit.ts
  packages/@aws-cdk/aws-iot-alpha/test/integ.audit-configuration.js.snapshot/IotAuditConfigurationTestStack.assets.json
  packages/@aws-cdk/aws-iot-alpha/test/integ.audit-configuration.js.snapshot/IotAuditConfigurationTestStack.template.json
  packages/@aws-cdk/aws-iot-alpha/test/integ.audit-configuration.js.snapshot/manifest.json
  packages/@aws-cdk/aws-iot-alpha/test/integ.audit-configuration.js.snapshot/tree.json
  packages/@aws-cdk/aws-iot-alpha/test/integ.audit-configuration.ts
  packages/@aws-cdk/aws-iot-alpha/test/scheduled-audit.test.ts
Labels: p2, feature-request, distinguished-contributor

#31824 docs(lambda): fix some typos in function
  packages/aws-cdk-lib/aws-lambda/lib/function.ts
Labels: p2, distinguished-contributor

#31840 chore(kinesisfirehose-alpha): update README with name changes and clarifications
  packages/@aws-cdk/aws-kinesisfirehose-alpha/README.md
Labels: p2, contribution/core

#31842 chore(merge-back): 2.163.0
  CHANGELOG.v2.alpha.md
  CHANGELOG.v2.md
  packages/aws-cdk-lib/cx-api/FEATURE_FLAGS.md
  packages/aws-cdk-lib/cx-api/lib/features.ts
  version.v2.json
Labels: p2, pr/needs-community-review, pr/no-squash, auto-approve

#31839 chore(lambda-nodejs): grammatical correction in statement reg bundleAwsSDK
  packages/aws-cdk-lib/aws-lambda-nodejs/README.md
Labels: p2, effort/small, pr-linter/exemption-requested

#31846 fix: 'Need to perform AWS calls for account' when doing cross-account deployments
  packages/aws-cdk/lib/api/deployments.ts
Labels: bug, p2, contribution/core, pr-linter/exempt-test, pr-linter/exempt-integ-test, pr-linter/cli-integ-tested

#31847 chore(release): 2.163.1
  CHANGELOG.v2.alpha.md
  CHANGELOG.v2.md
  packages/aws-cdk/lib/api/deployments.ts
  version.v2.json
Labels: p2, contribution/core, pr/no-squash, pr-linter/cli-integ-tested

#31805 chore(ci): fix deprecated parameters for actions-comment-pull-request
  .github/workflows/request-cli-integ-test.yml
Labels: p2, beginning-contributor

#31710 fix(core): fix policy synthesizer logic for precreated roles
  packages/@aws-cdk-testing/framework-integ/test/aws-dynamodb/test/integ.table-with-customized-role.js.snapshot/cdk-table-with-customized-role.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-dynamodb/test/integ.table-with-customized-role.js.snapshot/cdk-table-with-customized-role.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-dynamodb/test/integ.table-with-customized-role.js.snapshot/cdk-table-with-customized-role2.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-dynamodb/test/integ.table-with-customized-role.js.snapshot/cdk-table-with-customized-role2.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-dynamodb/test/integ.table-with-customized-role.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-dynamodb/test/integ.table-with-customized-role.js.snapshot/cdkdynamodbcustomizedroleintegDefaultTestDeployAssertD6C925FC.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-dynamodb/test/integ.table-with-customized-role.js.snapshot/cdkdynamodbcustomizedroleintegDefaultTestDeployAssertD6C925FC.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-dynamodb/test/integ.table-with-customized-role.js.snapshot/iam-policy-report.json
  packages/@aws-cdk-testing/framework-integ/test/aws-dynamodb/test/integ.table-with-customized-role.js.snapshot/iam-policy-report.txt
  packages/@aws-cdk-testing/framework-integ/test/aws-dynamodb/test/integ.table-with-customized-role.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-dynamodb/test/integ.table-with-customized-role.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-dynamodb/test/integ.table-with-customized-role.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-dynamodb/test/integ.table-with-customized-role.ts
  packages/@aws-cdk-testing/framework-integ/test/aws-iam/test/integ.customize-role.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-iam/test/integ.customize-role.js.snapshot/iam-policy-report.json
  packages/@aws-cdk-testing/framework-integ/test/aws-iam/test/integ.customize-role.js.snapshot/iam-policy-report.txt
  packages/@aws-cdk-testing/framework-integ/test/aws-iam/test/integ.customize-role.js.snapshot/integ-customize-role.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-iam/test/integ.customize-role.js.snapshot/integ-customize-role.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-iam/test/integ.customize-role.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-iam/test/integ.customize-role.js.snapshot/integiamcustomizeroleDefaultTestDeployAssert811D838D.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-iam/test/integ.customize-role.js.snapshot/integiamcustomizeroleDefaultTestDeployAssert811D838D.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-iam/test/integ.customize-role.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-iam/test/integ.customize-role.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-iam/test/integ.customize-role.ts
  packages/aws-cdk-lib/aws-iam/README.md
  packages/aws-cdk-lib/core/lib/helpers-internal/customize-roles.ts
Labels: bug, p1, effort/medium, contribution/core, pr-linter/exempt-test

#31852 chore(s3): update README to mention support for uppercase letters in legacy bucket names
  packages/aws-cdk-lib/aws-s3/README.md
Labels: p2, beginning-contributor

#31811 chore(cognito-identitypool): update README to encourage least privilege
  packages/@aws-cdk/aws-cognito-identitypool-alpha/README.md
Labels: p2, contribution/core

#31853 chore(merge-back): 2.163.1
  CHANGELOG.v2.alpha.md
  CHANGELOG.v2.md
  version.v2.json
Labels: p2, pr/needs-community-review, pr/no-squash, auto-approve

#31854 feat(cognito): the Cognito Identity Pools module is now in Developer Preview
  packages/@aws-cdk/aws-cognito-identitypool-alpha/README.md
  packages/@aws-cdk/aws-cognito-identitypool-alpha/package.json
Labels: p2, contribution/core, pr-linter/exempt-test, pr-linter/exempt-integ-test

#31812 fix(ec2): allow NAT instance to associate public IP
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.nat-instances-with-public-ip.js.snapshot/aws-cdk-vpc-nat-instances-v2-with-public-ip.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.nat-instances-with-public-ip.js.snapshot/aws-cdk-vpc-nat-instances-v2-with-public-ip.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.nat-instances-with-public-ip.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.nat-instances-with-public-ip.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.nat-instances-with-public-ip.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.nat-instances-with-public-ip.js.snapshot/natinstancev2withpublicipintegtestDefaultTestDeployAssertB63E4D9C.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.nat-instances-with-public-ip.js.snapshot/natinstancev2withpublicipintegtestDefaultTestDeployAssertB63E4D9C.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.nat-instances-with-public-ip.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.nat-instances-with-public-ip.ts
  packages/aws-cdk-lib/aws-ec2/README.md
  packages/aws-cdk-lib/aws-ec2/lib/nat.ts
  packages/aws-cdk-lib/aws-ec2/test/vpc.test.ts
Labels: bug, p2, effort/small, contribution/core

#31816 feat(cognito): support email based MFA
  packages/@aws-cdk-testing/framework-integ/test/aws-cognito/test/integ.user-pool-mfa-email.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-cognito/test/integ.user-pool-mfa-email.js.snapshot/integ-user-email-mfa.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-cognito/test/integ.user-pool-mfa-email.js.snapshot/integ-user-email-mfa.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-cognito/test/integ.user-pool-mfa-email.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-cognito/test/integ.user-pool-mfa-email.js.snapshot/integuseremailmfatestDefaultTestDeployAssertD4C43B3C.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-cognito/test/integ.user-pool-mfa-email.js.snapshot/integuseremailmfatestDefaultTestDeployAssertD4C43B3C.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-cognito/test/integ.user-pool-mfa-email.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-cognito/test/integ.user-pool-mfa-email.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-cognito/test/integ.user-pool-mfa-email.ts
  packages/aws-cdk-lib/aws-cognito/README.md
  packages/aws-cdk-lib/aws-cognito/lib/user-pool-email.ts
  packages/aws-cdk-lib/aws-cognito/lib/user-pool.ts
  packages/aws-cdk-lib/aws-cognito/test/user-pool.test.ts
Labels: p2, feature-request, distinguished-contributor

#31857 chore(bedrock): add claude 3.5 sonnet v2
  packages/aws-cdk-lib/aws-bedrock/lib/foundation-model.ts
Labels: p2, contribution/core

#31820 docs: fix improper JSDoc formatting
  packages/@aws-cdk/aws-apprunner-alpha/lib/auto-scaling-configuration.ts
  packages/@aws-cdk/aws-apprunner-alpha/lib/service.ts
  packages/@aws-cdk/aws-apprunner-alpha/lib/vpc-connector.ts
  packages/@aws-cdk/aws-gamelift-alpha/lib/alias.ts
  packages/@aws-cdk/aws-gamelift-alpha/lib/build.ts
  packages/@aws-cdk/aws-gamelift-alpha/lib/fleet-base.ts
  packages/@aws-cdk/aws-gamelift-alpha/lib/game-server-group.ts
  packages/@aws-cdk/aws-gamelift-alpha/lib/ingress-rule.ts
  packages/@aws-cdk/aws-kinesisfirehose-alpha/lib/source.ts
  packages/@aws-cdk/aws-kinesisfirehose-destinations-alpha/lib/logging-config.ts
  packages/@aws-cdk/aws-pipes-alpha/lib/pipe.ts
  packages/@aws-cdk/aws-pipes-sources-alpha/lib/sqs.ts
  packages/@aws-cdk/aws-pipes-sources-alpha/lib/streamSource.ts
  packages/@aws-cdk/aws-redshift-alpha/lib/table.ts
  packages/@aws-cdk/aws-route53resolver-alpha/lib/firewall-domain-list.ts
  packages/@aws-cdk/aws-route53resolver-alpha/lib/firewall-rule-group-association.ts
  packages/@aws-cdk/aws-servicecatalogappregistry-alpha/lib/target-application.ts
  packages/@aws-cdk/cdk-cli-wrapper/lib/commands/common.ts
  packages/@aws-cdk/cli-lib-alpha/lib/commands/common.ts
  packages/@aws-cdk/integ-runner/lib/runner/integration-tests.ts
  packages/aws-cdk-lib/aws-apigatewayv2/lib/websocket/api.ts
  packages/aws-cdk-lib/aws-appsync/lib/schema.ts
  packages/aws-cdk-lib/aws-batch/lib/linux-parameters.ts
  packages/aws-cdk-lib/aws-certificatemanager/lib/certificate-base.ts
  packages/aws-cdk-lib/aws-cloudfront/lib/distribution.ts
  packages/aws-cdk-lib/aws-cloudfront/lib/endpoint.ts
  packages/aws-cdk-lib/aws-codebuild/lib/build-spec.ts
  packages/aws-cdk-lib/aws-codedeploy/lib/ecs/deployment-group.ts
  packages/aws-cdk-lib/aws-cognito/lib/user-pool-idps/oidc.ts
  packages/aws-cdk-lib/aws-config/lib/rule.ts
  packages/aws-cdk-lib/aws-docdb/lib/cluster.ts
  packages/aws-cdk-lib/aws-dynamodb/lib/table.ts
  packages/aws-cdk-lib/aws-ecs-patterns/lib/base/application-multiple-target-groups-service-base.ts
  packages/aws-cdk-lib/aws-ecs-patterns/lib/base/fargate-service-base.ts
  packages/aws-cdk-lib/aws-ecs-patterns/lib/base/scheduled-task-base.ts
  packages/aws-cdk-lib/aws-ecs/lib/cluster.ts
  packages/aws-cdk-lib/aws-ecs/lib/linux-parameters.ts
  packages/aws-cdk-lib/aws-events-targets/lib/ecs-task.ts
  packages/aws-cdk-lib/aws-iam/lib/role.ts
  packages/aws-cdk-lib/aws-ses/lib/email-identity.ts
  packages/aws-cdk-lib/aws-stepfunctions/test/private/fake-task.ts
  packages/aws-cdk-lib/aws-synthetics/lib/runtime.ts
  packages/aws-cdk/lib/api/deployments.ts
Labels: p2, pr/needs-community-review, pr-linter/exempt-test, distinguished-contributor, pr-linter/cli-integ-tested

#30511 feat(cli): add ability to configure hotswap properties for ECS
  packages/@aws-cdk-testing/cli-integ/tests/cli-integ-tests/cli.integtest.ts
  packages/aws-cdk/README.md
  packages/aws-cdk/lib/api/deploy-stack.ts
  packages/aws-cdk/lib/api/deployments.ts
  packages/aws-cdk/lib/api/hotswap-deployments.ts
  packages/aws-cdk/lib/api/hotswap/common.ts
  packages/aws-cdk/lib/api/hotswap/ecs-services.ts
  packages/aws-cdk/lib/cdk-toolkit.ts
  packages/aws-cdk/lib/settings.ts
  packages/aws-cdk/test/api/deploy-stack.test.ts
  packages/aws-cdk/test/api/hotswap/ecs-services-hotswap-deployments.test.ts
  packages/aws-cdk/test/api/hotswap/hotswap-test-setup.ts
Labels: p2, pr-linter/exempt-integ-test, beginning-contributor, pr-linter/cli-integ-tested, pr-linter/do-not-close

#31861 chore(kinesisfirehose-alpha): update README with Logging resource clarification
  packages/@aws-cdk/aws-kinesisfirehose-alpha/README.md
Labels: p2, contribution/core

#31868 chore(kinesisfirehose): update README to explicitly clarify which sources/destinations are supported in the CDK
  packages/@aws-cdk/aws-kinesisfirehose-alpha/README.md
Labels: p2, contribution/core

#31859 chore(codebuild): update default curated Docker image used in CodeBuild projects
  packages/@aws-cdk-testing/framework-integ/test/aws-codebuild/test/integ.asset-build-spec.js.snapshot/CodeBuildAssetBuildSpecStack.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-codebuild/test/integ.caching.js.snapshot/aws-cdk-codebuild.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-codebuild/test/integ.defaults.lit.js.snapshot/codebuild-default-project.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-codebuild/test/integ.github-webhook-batch.js.snapshot/test-codebuild-github-webhook-batch.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-codebuild/test/integ.github.js.snapshot/test-codebuild-github.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-codebuild/test/integ.project-bucket.js.snapshot/aws-cdk-codebuild.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-codebuild/test/integ.project-buildspec-artifacts.js.snapshot/aws-cdk-codebuild-buildspec-artifact-name.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-codebuild/test/integ.project-file-system-location.js.snapshot/aws-cdk-codebuild-file-system-locations.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-codebuild/test/integ.project-logging.js.snapshot/aws-cdk-codebuild-logging.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-codebuild/test/integ.project-notification.js.snapshot/aws-cdk-codebuild-project-vpc.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-codebuild/test/integ.project-secondary-sources-artifacts.js.snapshot/aws-cdk-codebuild-secondary-sources-artifacts.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-codebuild/test/integ.project-visibility.js.snapshot/codebuild-visibility.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-codebuild/test/integ.project-vpc.js.snapshot/aws-cdk-codebuild-project-vpc.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-codebuild/test/integ.report-group-delete-reports.js.snapshot/aws-cdk-report-group-delete-reports.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-codebuild/test/integ.report-group.js.snapshot/aws-cdk-report-group.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-codepipeline-actions/test/integ.pipeline-code-build-batch.js.snapshot/aws-cdk-codepipeline-codebuild-batch.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-codepipeline-actions/test/integ.pipeline-code-build-multiple-inputs-outputs.js.snapshot/aws-cdk-codepipeline-codebuild-multiple-inputs-outputs.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-codepipeline-actions/test/integ.pipeline-code-commit-build.js.snapshot/aws-cdk-codepipeline-codecommit-codebuild.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-codepipeline-actions/test/integ.pipeline-events.js.snapshot/aws-cdk-pipeline-event-target.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-codepipeline-actions/test/integ.pipeline-with-pipeline-triggers.js.snapshot/aws-cdk-codepipeline-with-pipeline-triggers.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-codepipeline-actions/test/integ.pipeline-with-replication.js.snapshot/integ-pipeline-consumer-stack.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-codepipeline-actions/test/s3/integ.source-bucket-events-cross-stack-same-env.js.snapshot/PipelineStack.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-events-targets/test/codebuild/integ.project-events.js.snapshot/aws-cdk-codebuild-events.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/codebuild/integ.start-build.js.snapshot/aws-stepfunctions-tasks-codebuild-start-build-integ.template.json
  packages/aws-cdk-lib/aws-codebuild/lib/project.ts
  packages/aws-cdk-lib/aws-codebuild/test/codebuild.test.ts
  packages/aws-cdk-lib/aws-codepipeline-actions/test/pipeline.test.ts
Labels: p2, feature-request, effort/small, beginning-contributor

#31876 fix(cli): cross-account asset publishing doesn't work without bootstrap stack
  packages/aws-cdk/lib/api/util/checks.ts
  packages/aws-cdk/test/api/util/checks.test.ts
Labels: bug, p1, contribution/core, pr-linter/exempt-test, pr-linter/exempt-integ-test, pr-linter/cli-integ-tested

#31878 fix(cli): deploy-role is not authorized to perform DescribeStackResources
  packages/aws-cdk/lib/api/util/checks.ts
  packages/aws-cdk/test/api/util/checks.test.ts
Labels: p2, contribution/core, pr-linter/exempt-test, pr-linter/exempt-integ-test, pr-linter/cli-integ-tested

#31872 chore(scheduler-alpha): unit test schedule with Lambda version as target
  packages/@aws-cdk/aws-scheduler-targets-alpha/test/lambda-invoke.test.ts
Labels: p2, contribution/core

#31873 chore(scheduler-alpha): unit test schedule with Lambda alias as target
  packages/@aws-cdk/aws-scheduler-targets-alpha/test/lambda-invoke.test.ts
Labels: p2, contribution/core

#31883 fix: enable node-fips compatible body checksums for S3
  packages/@aws-cdk/integ-runner/package.json
  packages/aws-cdk-lib/cx-api/FEATURE_FLAGS.md
  packages/aws-cdk/lib/api/aws-auth/sdk.ts
  packages/aws-cdk/package.json
  yarn.lock
Labels: p2, contribution/core, pr-linter/exempt-test, pr-linter/exempt-integ-test, pr-linter/cli-integ-tested

#31887 chore(scheduler-alpha): make LambdaInvoke prop optional
  packages/@aws-cdk/aws-scheduler-targets-alpha/lib/lambda-invoke.ts
  packages/@aws-cdk/aws-scheduler-targets-alpha/test/lambda-invoke.test.ts
Labels: p2, contribution/core

#31892 chore(merge-back): 2.164.0
  CHANGELOG.v2.alpha.md
  CHANGELOG.v2.md
  packages/aws-cdk-lib/cx-api/FEATURE_FLAGS.md
  packages/aws-cdk-lib/cx-api/lib/features.ts
  version.v2.json
Labels: p2, pr/needs-community-review, pr/no-squash, auto-approve

#31891 chore(mergify): clean up core aliases
  .github/workflows/github-merit-badger.yml
  .mergify.yml
Labels: p2, contribution/core

#31882 chore(ec2): add missing interface VPC endpoints
  packages/aws-cdk-lib/aws-ec2/lib/vpc-endpoint.ts
Labels: p2, distinguished-contributor

#31901 chore(release): 2.164.1
  CHANGELOG.v2.alpha.md
  CHANGELOG.v2.md
  packages/@aws-cdk/integ-runner/package.json
  packages/aws-cdk/lib/api/aws-auth/sdk.ts
  packages/aws-cdk/package.json
  version.v2.json
  yarn.lock
Labels: p2, contribution/core, pr/no-squash, pr-linter/cli-integ-tested

#31903 chore(cli): integ tests don't buffer shell output
  packages/@aws-cdk-testing/cli-integ/lib/shell.ts
  packages/@aws-cdk-testing/cli-integ/lib/staging/maven.ts
  packages/@aws-cdk-testing/cli-integ/lib/staging/npm.ts
  packages/@aws-cdk-testing/cli-integ/lib/staging/nuget.ts
  packages/@aws-cdk-testing/cli-integ/lib/staging/pypi.ts
  packages/@aws-cdk-testing/cli-integ/lib/with-cdk-app.ts
  packages/@aws-cdk-testing/cli-integ/lib/with-sam.ts
  packages/@aws-cdk-testing/cli-integ/tests/cli-integ-tests/cli.integtest.ts
Labels: p2, contribution/core

#31907 chore(ec2): add missing interface VPC endpoint
  packages/aws-cdk-lib/aws-ec2/lib/vpc-endpoint.ts
Labels: p2, contribution/core, pr/needs-maintainer-review

#31910 chore(merge-back): 2.164.1
  CHANGELOG.v2.alpha.md
  CHANGELOG.v2.md
  packages/aws-cdk/lib/api/aws-auth/sdk.ts
  packages/aws-cdk/lib/api/garbage-collection/garbage-collector.ts
  version.v2.json
Labels: p2, pr/no-squash, auto-approve

#31906 fix(cli): garbage collection ignores review_in_progress stacks
  packages/aws-cdk/lib/api/garbage-collection/garbage-collector.ts
  packages/aws-cdk/lib/api/garbage-collection/stack-refresh.ts
  packages/aws-cdk/test/api/garbage-collection.test.ts
Labels: p2, contribution/core, pr-linter/exempt-integ-test, pr-linter/cli-integ-tested

#31841 feat(cli): garbage collect ecr assets (under --unstable flag)
  packages/@aws-cdk-testing/cli-integ/lib/with-cdk-app.ts
  packages/@aws-cdk-testing/cli-integ/resources/cdk-apps/app/app.js
  packages/@aws-cdk-testing/cli-integ/tests/cli-integ-tests/garbage-collection.integtest.ts
  packages/aws-cdk/README.md
  packages/aws-cdk/lib/api/bootstrap/bootstrap-props.ts
  packages/aws-cdk/lib/api/garbage-collection/garbage-collector.ts
  packages/aws-cdk/lib/api/garbage-collection/progress-printer.ts
  packages/aws-cdk/lib/api/toolkit-info.ts
  packages/aws-cdk/test/api/garbage-collection.test.ts
  packages/aws-cdk/test/util/mock-sdk.ts
  packages/aws-cdk/test/util/mock-toolkitinfo.ts
Labels: p2, contribution/core, pr-linter/exempt-integ-test, pr-linter/cli-integ-tested

#31912 chore(ec2): pricing api interface vpc endpoint duplicated
  packages/aws-cdk-lib/aws-ec2/lib/vpc-endpoint.ts
Labels: bug, p2, distinguished-contributor, pr-linter/exemption-requested

#31917 feat: update L1 CloudFormation resource definitions
  packages/@aws-cdk/cloudformation-diff/package.json
  packages/@aws-cdk/integ-runner/package.json
  packages/aws-cdk-lib/package.json
  tools/@aws-cdk/spec2cdk/package.json
  yarn.lock
Labels: p2, dependencies, contribution/core, pr-linter/exempt-readme, pr-linter/exempt-test, auto-approve, pr-linter/exempt-integ-test

#31268 feat(location): support Tracker and TrackerConsumer
  packages/@aws-cdk/aws-location-alpha/README.md
  packages/@aws-cdk/aws-location-alpha/lib/index.ts
  packages/@aws-cdk/aws-location-alpha/lib/tracker.ts
  packages/@aws-cdk/aws-location-alpha/test/integ.tracker.js.snapshot/TrackerTestDefaultTestDeployAssert0E17BB8B.assets.json
  packages/@aws-cdk/aws-location-alpha/test/integ.tracker.js.snapshot/TrackerTestDefaultTestDeployAssert0E17BB8B.template.json
  packages/@aws-cdk/aws-location-alpha/test/integ.tracker.js.snapshot/asset.645dd1dc49076d88d406647a87b240b110b64bf4fc80bca4dfbfa23dc25b3fed.bundle/index.js
  packages/@aws-cdk/aws-location-alpha/test/integ.tracker.js.snapshot/cdk-integ-location-tracker.assets.json
  packages/@aws-cdk/aws-location-alpha/test/integ.tracker.js.snapshot/cdk-integ-location-tracker.template.json
  packages/@aws-cdk/aws-location-alpha/test/integ.tracker.js.snapshot/cdk.out
  packages/@aws-cdk/aws-location-alpha/test/integ.tracker.js.snapshot/integ.json
  packages/@aws-cdk/aws-location-alpha/test/integ.tracker.js.snapshot/manifest.json
  packages/@aws-cdk/aws-location-alpha/test/integ.tracker.js.snapshot/tree.json
  packages/@aws-cdk/aws-location-alpha/test/integ.tracker.ts
  packages/@aws-cdk/aws-location-alpha/test/tracker.test.ts
Labels: p2, feature-request, effort/medium, distinguished-contributor

#31740 feat(codebuild): add support of organization webhook in github source
  packages/@aws-cdk-testing/framework-integ/test/aws-codebuild/test/integ.github-org-webhook.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-codebuild/test/integ.github-org-webhook.js.snapshot/codebuild-github-org-webhook.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-codebuild/test/integ.github-org-webhook.js.snapshot/codebuild-github-org-webhook.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-codebuild/test/integ.github-org-webhook.js.snapshot/codebuildgithuborgwebhookintegDefaultTestDeployAssertB287C481.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-codebuild/test/integ.github-org-webhook.js.snapshot/codebuildgithuborgwebhookintegDefaultTestDeployAssertB287C481.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-codebuild/test/integ.github-org-webhook.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-codebuild/test/integ.github-org-webhook.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-codebuild/test/integ.github-org-webhook.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-codebuild/test/integ.github-org-webhook.ts
  packages/aws-cdk-lib/aws-codebuild/README.md
  packages/aws-cdk-lib/aws-codebuild/lib/source.ts
  packages/aws-cdk-lib/aws-codebuild/test/project.test.ts
Labels: p2, feature-request, effort/medium, beginning-contributor

#31922 fix(sqs): queue with `fifo: false` does not deploy
  packages/aws-cdk-lib/aws-sqs/lib/queue.ts
  packages/aws-cdk-lib/aws-sqs/test/sqs.test.ts
Labels: bug, p2, contribution/core, pr-linter/exempt-integ-test

#31923 fix(scheduler-alpha): too many KMS permissions granted
  packages/@aws-cdk/aws-scheduler-alpha/lib/schedule.ts
  packages/@aws-cdk/aws-scheduler-alpha/test/integ.schedule.js.snapshot/asset.b98abee59e034ed29eeb601684dc34752baa86509a7d457d72305d4e19ecc80b.bundle/index.js
  packages/@aws-cdk/aws-scheduler-alpha/test/integ.schedule.js.snapshot/aws-cdk-scheduler-schedule.assets.json
  packages/@aws-cdk/aws-scheduler-alpha/test/integ.schedule.js.snapshot/aws-cdk-scheduler-schedule.template.json
  packages/@aws-cdk/aws-scheduler-alpha/test/integ.schedule.js.snapshot/integtestscheduleDefaultTestDeployAssert24CB3896.assets.json
  packages/@aws-cdk/aws-scheduler-alpha/test/integ.schedule.js.snapshot/integtestscheduleDefaultTestDeployAssert24CB3896.template.json
  packages/@aws-cdk/aws-scheduler-alpha/test/integ.schedule.js.snapshot/manifest.json
  packages/@aws-cdk/aws-scheduler-alpha/test/integ.schedule.js.snapshot/tree.json
  packages/@aws-cdk/aws-scheduler-alpha/test/integ.schedule.ts
  packages/@aws-cdk/aws-scheduler-alpha/test/schedule.test.ts
Labels: p2, contribution/core

#31921 chore: add Amplify integration tests
  packages/@aws-cdk-testing/cli-integ/lib/package-sources/release-source.ts
  packages/@aws-cdk-testing/cli-integ/lib/package-sources/repo-source.ts
  packages/@aws-cdk-testing/cli-integ/lib/package-sources/source.ts
  packages/@aws-cdk-testing/cli-integ/tests/tool-integrations/amplify.integtest.ts
Labels: p2, contribution/core

#30597 fix(s3-assets): cannot publish a file without extension
  packages/@aws-cdk-testing/framework-integ/test/aws-s3-assets/test/integ.assets.file-bundling.lit.js.snapshot/IntegTestDefaultTestDeployAssertE3E7D2A4.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-s3-assets/test/integ.assets.file-bundling.lit.js.snapshot/asset.eb4b352e81f47c1880938665c15111e9aa20db0d42e929187a1b592a593ea713/main
  packages/@aws-cdk-testing/framework-integ/test/aws-s3-assets/test/integ.assets.file-bundling.lit.js.snapshot/asset.eb4b352e81f47c1880938665c15111e9aa20db0d42e929187a1b592a593ea713noext
  packages/@aws-cdk-testing/framework-integ/test/aws-s3-assets/test/integ.assets.file-bundling.lit.js.snapshot/cdk-integ-assets-bundling.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-s3-assets/test/integ.assets.file-bundling.lit.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-s3-assets/test/integ.assets.file-bundling.lit.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-s3-assets/test/integ.assets.file-bundling.lit.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-s3-assets/test/integ.assets.file-bundling.lit.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-s3-assets/test/integ.assets.file-bundling.lit.ts
  packages/aws-cdk-lib/core/lib/asset-staging.ts
  packages/aws-cdk-lib/core/test/docker-stub-cp.sh
  packages/aws-cdk-lib/core/test/docker-stub.sh
  packages/aws-cdk-lib/core/test/staging.test.ts
Labels: bug, p1, @aws-cdk/core, effort/medium, @aws-cdk/aws-s3-assets, star-contributor

#31925 chore(cli): add image to gc docs and document race condition
  packages/aws-cdk/README.md
  packages/aws-cdk/images/garbage-collection.png
Labels: p2, contribution/core, pr/needs-maintainer-review

#31936 chore(cdk): increase coverage limits
  packages/aws-cdk/jest.config.js
Labels: p2, contribution/core

#31865 fix(assertions): throw error or warn when `synth` is called multiple times on mutated construct tree
  packages/aws-cdk-lib/core/lib/app.ts
  packages/aws-cdk-lib/core/lib/stage.ts
  packages/aws-cdk-lib/core/test/synthesis.test.ts
  packages/aws-cdk-lib/pipelines/test/compliance/synths.test.ts
Labels: bug, p1, effort/medium, contribution/core, pr-linter/exempt-integ-test

#31935 chore(tools): update README for spec2cdk with an example
  tools/@aws-cdk/spec2cdk/README.md
Labels: p2, repeat-contributor

#31927 feat(cdk): update tsconfig to more modern settings in typescript init templates
  packages/aws-cdk/lib/init-templates/app/typescript/tsconfig.json
  packages/aws-cdk/lib/init-templates/sample-app/typescript/tsconfig.json
Labels: p2, pr-linter/exempt-readme, pr-linter/exempt-test, pr-linter/exempt-integ-test, beginning-contributor

#31944 chore: make the Amplify integration tests respect AWS region assignments
  packages/@aws-cdk-testing/cli-integ/lib/with-aws.ts
  packages/@aws-cdk-testing/cli-integ/tests/tool-integrations/amplify.integtest.ts
  packages/@aws-cdk-testing/cli-integ/tests/tool-integrations/with-tool-context.ts
Labels: p2, contribution/core

#31939 chore(scheduler-alpha): minor doc updates
  packages/@aws-cdk/aws-scheduler-alpha/README.md
  packages/@aws-cdk/aws-scheduler-alpha/lib/input.ts
Labels: p2, contribution/core

#31946 chore: fix C# build
  packages/@aws-cdk/aws-ec2-alpha/lib/vpc-v2-base.ts
Labels: p2, contribution/core

#31949 feat(bootstrap): delete noncurrent versions after 30 days
  packages/aws-cdk/lib/api/bootstrap/bootstrap-template.yaml
Labels: p2, contribution/core, pr-linter/exempt-readme, pr-linter/exempt-test, pr-linter/exempt-integ-test

#30623 feat(apprunner): support vpc ingress connection
  packages/@aws-cdk/aws-apprunner-alpha/README.md
  packages/@aws-cdk/aws-apprunner-alpha/lib/index.ts
  packages/@aws-cdk/aws-apprunner-alpha/lib/service.ts
  packages/@aws-cdk/aws-apprunner-alpha/lib/vpc-ingress-connection.ts
  packages/@aws-cdk/aws-apprunner-alpha/test/integ.service-vpc-ingress-connection.js.snapshot/AppRunnerVpcIngressConnectionDefaultTestDeployAssertC725050C.assets.json
  packages/@aws-cdk/aws-apprunner-alpha/test/integ.service-vpc-ingress-connection.js.snapshot/AppRunnerVpcIngressConnectionDefaultTestDeployAssertC725050C.template.json
  packages/@aws-cdk/aws-apprunner-alpha/test/integ.service-vpc-ingress-connection.js.snapshot/asset.bde7b5c89cb43285f884c94f0b9e17cdb0f5eb5345005114dd60342e0b8a85a1/__entrypoint__.js
  packages/@aws-cdk/aws-apprunner-alpha/test/integ.service-vpc-ingress-connection.js.snapshot/asset.bde7b5c89cb43285f884c94f0b9e17cdb0f5eb5345005114dd60342e0b8a85a1/index.js
  packages/@aws-cdk/aws-apprunner-alpha/test/integ.service-vpc-ingress-connection.js.snapshot/cdk.out
  packages/@aws-cdk/aws-apprunner-alpha/test/integ.service-vpc-ingress-connection.js.snapshot/integ-apprunner-vpc-ingress-connection.assets.json
  packages/@aws-cdk/aws-apprunner-alpha/test/integ.service-vpc-ingress-connection.js.snapshot/integ-apprunner-vpc-ingress-connection.template.json
  packages/@aws-cdk/aws-apprunner-alpha/test/integ.service-vpc-ingress-connection.js.snapshot/integ.json
  packages/@aws-cdk/aws-apprunner-alpha/test/integ.service-vpc-ingress-connection.js.snapshot/manifest.json
  packages/@aws-cdk/aws-apprunner-alpha/test/integ.service-vpc-ingress-connection.js.snapshot/tree.json
  packages/@aws-cdk/aws-apprunner-alpha/test/integ.service-vpc-ingress-connection.ts
  packages/@aws-cdk/aws-apprunner-alpha/test/service.test.ts
  packages/@aws-cdk/aws-apprunner-alpha/test/vpc-ingress-connection.test.ts
Labels: p2, feature-request, effort/medium, star-contributor

#30696 feat(pipes-targets): add SageMaker
  packages/@aws-cdk/aws-pipes-targets-alpha/README.md
  packages/@aws-cdk/aws-pipes-targets-alpha/lib/index.ts
  packages/@aws-cdk/aws-pipes-targets-alpha/lib/lambda.ts
  packages/@aws-cdk/aws-pipes-targets-alpha/lib/sagemaker.ts
  packages/@aws-cdk/aws-pipes-targets-alpha/lib/sqs.ts
  packages/@aws-cdk/aws-pipes-targets-alpha/lib/stepfunctions.ts
  packages/@aws-cdk/aws-pipes-targets-alpha/rosetta/default.ts-fixture
  packages/@aws-cdk/aws-pipes-targets-alpha/test/__snapshots__/sagemaker.test.ts.snap
  packages/@aws-cdk/aws-pipes-targets-alpha/test/integ.sagemaker.js.snapshot/asset.44e9c4d7a5d3fd2d677e1a7e416b2b56f6b0104bd5eff9cac5557b4c65a9dc61/index.js
  packages/@aws-cdk/aws-pipes-targets-alpha/test/integ.sagemaker.js.snapshot/asset.da514df694ce3f41453746a766ae6aff13c869c38002598930d6d34e5711985b.bundle/index.js
  packages/@aws-cdk/aws-pipes-targets-alpha/test/integ.sagemaker.js.snapshot/aws-cdk-pipes-targets-sagemaker.assets.json
  packages/@aws-cdk/aws-pipes-targets-alpha/test/integ.sagemaker.js.snapshot/aws-cdk-pipes-targets-sagemaker.template.json
  packages/@aws-cdk/aws-pipes-targets-alpha/test/integ.sagemaker.js.snapshot/cdk.out
  packages/@aws-cdk/aws-pipes-targets-alpha/test/integ.sagemaker.js.snapshot/integ.json
  packages/@aws-cdk/aws-pipes-targets-alpha/test/integ.sagemaker.js.snapshot/integtestpipetargetsagemakerDefaultTestDeployAssert7D2ED3D4.assets.json
  packages/@aws-cdk/aws-pipes-targets-alpha/test/integ.sagemaker.js.snapshot/integtestpipetargetsagemakerDefaultTestDeployAssert7D2ED3D4.template.json
  packages/@aws-cdk/aws-pipes-targets-alpha/test/integ.sagemaker.js.snapshot/manifest.json
  packages/@aws-cdk/aws-pipes-targets-alpha/test/integ.sagemaker.js.snapshot/tree.json
  packages/@aws-cdk/aws-pipes-targets-alpha/test/integ.sagemaker.ts
  packages/@aws-cdk/aws-pipes-targets-alpha/test/sagemaker.test.ts
Labels: p2, distinguished-contributor

#31951 fix(cli): ecr garbage collection hangs when repository has no images
  packages/aws-cdk/lib/api/garbage-collection/garbage-collector.ts
  packages/aws-cdk/test/api/garbage-collection.test.ts
Labels: p2, contribution/core, pr-linter/exempt-integ-test, pr-linter/cli-integ-tested

#31952 chore(kinesisfirehose-alpha): set module and destinations module to developer preview
  packages/@aws-cdk/aws-kinesisfirehose-alpha/README.md
  packages/@aws-cdk/aws-kinesisfirehose-alpha/package.json
  packages/@aws-cdk/aws-kinesisfirehose-destinations-alpha/README.md
  packages/@aws-cdk/aws-kinesisfirehose-destinations-alpha/package.json
Labels: p2, contribution/core

#31953 revert: feat(cdk): update tsconfig to more modern settings in typescript init templates
  packages/aws-cdk/lib/init-templates/app/typescript/tsconfig.json
  packages/aws-cdk/lib/init-templates/sample-app/typescript/tsconfig.json
Labels: p2, contribution/core

#31960 chore: automatically age out old TypeScript versions from testing
  packages/@aws-cdk-testing/cli-integ/lib/npm.ts
  packages/@aws-cdk-testing/cli-integ/tests/init-typescript-app/init-typescript-app.integtest.ts
Labels: p2, contribution/core, pr/needs-maintainer-review

#31956 feat(bootstrap): add lifecycle rule to abort multipart uploads after 7 days
  packages/aws-cdk/lib/api/bootstrap/bootstrap-template.yaml
Labels: p1, feature-request, effort/small, contribution/core, pr-linter/exempt-readme, pr-linter/exempt-test, pr-linter/exempt-integ-test

#31351 feat(cognito): support UserPoolGroup
  packages/@aws-cdk-testing/framework-integ/test/aws-cognito/test/integ.user-pool-group.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-cognito/test/integ.user-pool-group.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-cognito/test/integ.user-pool-group.js.snapshot/integuserpoolgroupDefaultTestDeployAssertED51AC37.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-cognito/test/integ.user-pool-group.js.snapshot/integuserpoolgroupDefaultTestDeployAssertED51AC37.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-cognito/test/integ.user-pool-group.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-cognito/test/integ.user-pool-group.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-cognito/test/integ.user-pool-group.js.snapshot/user-pool-group-stack.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-cognito/test/integ.user-pool-group.js.snapshot/user-pool-group-stack.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-cognito/test/integ.user-pool-group.ts
  packages/aws-cdk-lib/aws-cognito/README.md
  packages/aws-cdk-lib/aws-cognito/lib/index.ts
  packages/aws-cdk-lib/aws-cognito/lib/user-pool-group.ts
  packages/aws-cdk-lib/aws-cognito/lib/user-pool.ts
  packages/aws-cdk-lib/aws-cognito/test/user-pool-group.test.ts
  packages/aws-cdk-lib/awslint.json
Labels: p2, feature-request, effort/medium, distinguished-contributor

#31794 feat(pipes-enrichments): support API Gateway enrichment
  packages/@aws-cdk/aws-pipes-enrichments-alpha/README.md
  packages/@aws-cdk/aws-pipes-enrichments-alpha/lib/api-gateway.ts
  packages/@aws-cdk/aws-pipes-enrichments-alpha/lib/index.ts
  packages/@aws-cdk/aws-pipes-enrichments-alpha/rosetta/default.ts-fixture
  packages/@aws-cdk/aws-pipes-enrichments-alpha/test/__snapshots__/api-gateway.test.ts.snap
  packages/@aws-cdk/aws-pipes-enrichments-alpha/test/api-gateway.test.ts
  packages/@aws-cdk/aws-pipes-enrichments-alpha/test/integ.api-gateway.js.snapshot/asset.9dfc74c8bd7d47c1f4fd8d08d909920d2f8466195f82205f32046c6583d16809.bundle/index.js
  packages/@aws-cdk/aws-pipes-enrichments-alpha/test/integ.api-gateway.js.snapshot/aws-cdk-pipes-enrichments-api-gateway.assets.json
  packages/@aws-cdk/aws-pipes-enrichments-alpha/test/integ.api-gateway.js.snapshot/aws-cdk-pipes-enrichments-api-gateway.template.json
  packages/@aws-cdk/aws-pipes-enrichments-alpha/test/integ.api-gateway.js.snapshot/cdk.out
  packages/@aws-cdk/aws-pipes-enrichments-alpha/test/integ.api-gateway.js.snapshot/integ.json
  packages/@aws-cdk/aws-pipes-enrichments-alpha/test/integ.api-gateway.js.snapshot/integtestpipeenrichmentsapigatewayDefaultTestDeployAssertA630AACD.assets.json
  packages/@aws-cdk/aws-pipes-enrichments-alpha/test/integ.api-gateway.js.snapshot/integtestpipeenrichmentsapigatewayDefaultTestDeployAssertA630AACD.template.json
  packages/@aws-cdk/aws-pipes-enrichments-alpha/test/integ.api-gateway.js.snapshot/manifest.json
  packages/@aws-cdk/aws-pipes-enrichments-alpha/test/integ.api-gateway.js.snapshot/tree.json
  packages/@aws-cdk/aws-pipes-enrichments-alpha/test/integ.api-gateway.ts
Labels: p2, feature-request, effort/medium, distinguished-contributor

#31823 fix(aws_route53): cannot use CfnParameter.valueAsNumber for L2 RecordSet weight
  packages/@aws-cdk-testing/framework-integ/test/aws-route53/test/integ.record-weight-from-cfnparameter.js.snapshot/Route53RecordWeightFromCfnParameterIntegDefaultTestDeployAssertB313B703.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-route53/test/integ.record-weight-from-cfnparameter.js.snapshot/Route53RecordWeightFromCfnParameterIntegDefaultTestDeployAssertB313B703.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-route53/test/integ.record-weight-from-cfnparameter.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-route53/test/integ.record-weight-from-cfnparameter.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-route53/test/integ.record-weight-from-cfnparameter.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-route53/test/integ.record-weight-from-cfnparameter.js.snapshot/record-weight-from-cfnparameter.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-route53/test/integ.record-weight-from-cfnparameter.js.snapshot/record-weight-from-cfnparameter.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-route53/test/integ.record-weight-from-cfnparameter.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-route53/test/integ.record-weight-from-cfnparameter.ts
  packages/aws-cdk-lib/aws-route53/lib/record-set.ts
  packages/aws-cdk-lib/aws-route53/test/record-set.test.ts
Labels: bug, p2, beginning-contributor

#31968 chore(merge-back): 2.165.0
  CHANGELOG.v2.alpha.md
  CHANGELOG.v2.md
  version.v2.json
Labels: p2, pr/no-squash, auto-approve

#31945 chore(mergify): update queue rules minimum required conditions
  .mergify.yml
Labels: p2, contribution/core
