Repository aws/aws-cdk, pull requests merged in 2024-05, with the labels that each got.

#29765 fix(stepfunctions): regex in DistributedMap label is incorrectly escaping characters
  packages/aws-cdk-lib/aws-stepfunctions/lib/states/distributed-map.ts
  packages/aws-cdk-lib/aws-stepfunctions/test/distributed-map.test.ts
Labels: p2, pr-linter/exempt-integ-test, beginning-contributor

#30024 chore: update Contributors File
  CONTRIBUTORS.md
Labels: p2, auto-approve

#30031 chore: npm-check-updates && yarn upgrade
  package.json
  packages/@aws-cdk-testing/cli-integ/package.json
  packages/@aws-cdk-testing/framework-integ/package.json
  packages/@aws-cdk/cloudformation-diff/package.json
  packages/@aws-cdk/custom-resource-handlers/package.json
  packages/@aws-cdk/cx-api/FEATURE_FLAGS.md
  packages/@aws-cdk/integ-runner/THIRD_PARTY_LICENSES
  packages/aws-cdk-lib/cx-api/FEATURE_FLAGS.md
  packages/aws-cdk-lib/package.json
  packages/aws-cdk/THIRD_PARTY_LICENSES
  packages/aws-cdk/package.json
  packages/awslint/package.json
  packages/cdk-assets/package.json
  tools/@aws-cdk/cdk-build-tools/package.json
  tools/@aws-cdk/lazify/package.json
  yarn.lock
Labels: p2, dependencies, contribution/core, auto-approve

#30010 feat(efs): allow to specify az for one-zone
  packages/@aws-cdk-testing/framework-integ/test/aws-efs/test/integ.efs-filesystem-one-zone.js.snapshot/asset.4554b47be6f57b68c6c7a7391dcc73894866d2377fe174883351e7639097f292/__entrypoint__.js
  packages/@aws-cdk-testing/framework-integ/test/aws-efs/test/integ.efs-filesystem-one-zone.js.snapshot/asset.bde7b5c89cb43285f884c94f0b9e17cdb0f5eb5345005114dd60342e0b8a85a1/__entrypoint__.js
  packages/@aws-cdk-testing/framework-integ/test/aws-efs/test/integ.efs-filesystem-one-zone.js.snapshot/asset.bde7b5c89cb43285f884c94f0b9e17cdb0f5eb5345005114dd60342e0b8a85a1/index.js
  packages/@aws-cdk-testing/framework-integ/test/aws-efs/test/integ.efs-filesystem-one-zone.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-efs/test/integ.efs-filesystem-one-zone.js.snapshot/test-efs-one-zone-integ.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-efs/test/integ.efs-filesystem-one-zone.js.snapshot/test-efs-one-zone-integ.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-efs/test/integ.efs-filesystem-one-zone.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-efs/test/integ.efs-filesystem-one-zone.ts
  packages/aws-cdk-lib/aws-efs/README.md
  packages/aws-cdk-lib/aws-efs/lib/efs-file-system.ts
  packages/aws-cdk-lib/aws-efs/test/efs-file-system.test.ts
Labels: p2, feature-request, effort/medium, contribution/core

#30030 feat(cloudfront): add `autoPublish` property to the `Function`
  packages/@aws-cdk-testing/framework-integ/test/aws-cloudfront/test/integ.distribution-function-autopublish.js.snapshot/AutoPublishTestDefaultTestDeployAssert10053C6C.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-cloudfront/test/integ.distribution-function-autopublish.js.snapshot/AutoPublishTestDefaultTestDeployAssert10053C6C.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-cloudfront/test/integ.distribution-function-autopublish.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-cloudfront/test/integ.distribution-function-autopublish.js.snapshot/integ-distribution-function.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-cloudfront/test/integ.distribution-function-autopublish.js.snapshot/integ-distribution-function.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-cloudfront/test/integ.distribution-function-autopublish.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-cloudfront/test/integ.distribution-function-autopublish.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-cloudfront/test/integ.distribution-function-autopublish.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-cloudfront/test/integ.distribution-function-autopublish.ts
  packages/aws-cdk-lib/aws-cloudfront/README.md
  packages/aws-cdk-lib/aws-cloudfront/lib/function.ts
  packages/aws-cdk-lib/aws-cloudfront/test/function.test.ts
Labels: p2, feature-request, beginning-contributor

#29629 feat(ec2): add support for environment files and variables in systemd
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.instance-init.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.instance-init.js.snapshot/integ-init.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.instance-init.js.snapshot/integ-init.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.instance-init.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.instance-init.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.instance-init.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.instance-init.ts
  packages/aws-cdk-lib/aws-ec2/README.md
  packages/aws-cdk-lib/aws-ec2/lib/cfn-init-elements.ts
  packages/aws-cdk-lib/aws-ec2/test/cfn-init-element.test.ts
Labels: p2, beginning-contributor, pr-linter/exemption-requested

#30009 feat: support for IAM Identity Center in security diff
  packages/@aws-cdk-testing/cli-integ/lib/aws.ts
  packages/@aws-cdk-testing/cli-integ/resources/cdk-apps/app/app.js
  packages/@aws-cdk-testing/cli-integ/tests/cli-integ-tests/cli.integtest.ts
  packages/@aws-cdk/cloudformation-diff/lib/diff/types.ts
  packages/@aws-cdk/cloudformation-diff/lib/format.ts
  packages/@aws-cdk/cloudformation-diff/lib/iam/iam-changes.ts
  packages/@aws-cdk/cloudformation-diff/lib/iam/iam-identity-center.ts
  packages/@aws-cdk/cloudformation-diff/test/iam/detect-changes.test.ts
  packages/@aws-cdk/cloudformation-diff/test/util.ts
Labels: p1, contribution/core, pr-linter/exempt-readme, pr-linter/exempt-integ-test

#30047 chore(merge-back): 2.140.0
  CHANGELOG.v2.alpha.md
  CHANGELOG.v2.md
  packages/aws-cdk-lib/cx-api/FEATURE_FLAGS.md
  packages/aws-cdk-lib/cx-api/lib/features.ts
  version.v2.json
Labels: p2, pr/needs-community-review, pr/no-squash, auto-approve

#29243 fix(ecr): incorrect format for rule pattern
  packages/@aws-cdk-testing/framework-integ/test/aws-ecr/test/integ.basic.js.snapshot/aws-ecr-integ-stack.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecr/test/integ.basic.js.snapshot/aws-ecr-integ-stack.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecr/test/integ.basic.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-ecr/test/integ.basic.js.snapshot/cdkecrintegtestbasicDefaultTestDeployAssert4F7FBFB4.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecr/test/integ.basic.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecr/test/integ.basic.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecr/test/integ.basic.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecr/test/integ.basic.ts
  packages/aws-cdk-lib/aws-ecr/README.md
  packages/aws-cdk-lib/aws-ecr/lib/repository.ts
  packages/aws-cdk-lib/aws-ecr/test/repository.test.ts
Labels: bug, p2, effort/medium, star-contributor, pr/needs-maintainer-review

#30068 docs(ses): fix typos
  packages/aws-cdk-lib/aws-ses/lib/vdm-attributes.ts
Labels: p2, beginning-contributor

#29965 feat(rds): implement setting parameter group name
  packages/@aws-cdk-testing/framework-integ/test/aws-rds/test/integ.instance-with-parameter-group.js.snapshot/aws-cdk-rds-instance-with-rds-parameter-group.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-rds/test/integ.instance-with-parameter-group.js.snapshot/aws-cdk-rds-instance-with-rds-parameter-group.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-rds/test/integ.instance-with-parameter-group.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-rds/test/integ.instance-with-parameter-group.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-rds/test/integ.instance-with-parameter-group.ts
  packages/aws-cdk-lib/aws-rds/README.md
  packages/aws-cdk-lib/aws-rds/lib/parameter-group.ts
  packages/aws-cdk-lib/aws-rds/test/parameter-group.test.ts
Labels: p2, beginning-contributor, pr/reviewer-clarification-requested

#30060 chore(lambda): hide warning if skipPermissions is set
  packages/aws-cdk-lib/aws-lambda/lib/function-base.ts
  packages/aws-cdk-lib/aws-lambda/test/function.test.ts
Labels: bug, p2, effort/medium, star-contributor

#30084 fix(pipelines): pipeline asset role trust policy has account root principal
  packages/@aws-cdk-testing/framework-integ/test/pipelines/test/integ.newpipeline-with-file-system-locations.js
  packages/@aws-cdk-testing/framework-integ/test/pipelines/test/integ.newpipeline-with-file-system-locations.js.snapshot/PipelinesFileSystemLocations.assets.json
  packages/@aws-cdk-testing/framework-integ/test/pipelines/test/integ.newpipeline-with-file-system-locations.js.snapshot/PipelinesFileSystemLocations.template.json
  packages/@aws-cdk-testing/framework-integ/test/pipelines/test/integ.newpipeline-with-file-system-locations.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/pipelines/test/integ.newpipeline-with-file-system-locations.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/pipelines/test/integ.newpipeline-with-file-system-locations.ts
  packages/@aws-cdk-testing/framework-integ/test/pipelines/test/integ.newpipeline-with-vpc.ts
  packages/aws-cdk-lib/cx-api/FEATURE_FLAGS.md
  packages/aws-cdk-lib/cx-api/lib/features.ts
  packages/aws-cdk-lib/cx-api/test/features.test.ts
  packages/aws-cdk-lib/pipelines/lib/codepipeline/codepipeline.ts
  packages/aws-cdk-lib/pipelines/test/codepipeline/codepipeline.test.ts
  packages/aws-cdk-lib/pipelines/test/compliance/assets.test.ts
Labels: p1, contribution/core, pr/needs-maintainer-review

#30099 chore(lambda-nodejs): clean up sdk v2 references and warn about runtime updates related to sdk bundling
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-nodejs/test/integ-handlers/dependencies-sdk-v3.ts
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-nodejs/test/integ-handlers/dependencies.ts
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-nodejs/test/integ.dependencies.js.snapshot/LambdaDependenciesDefaultTestDeployAssert259C940B.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-nodejs/test/integ.dependencies.js.snapshot/LambdaDependenciesDefaultTestDeployAssert259C940B.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-nodejs/test/integ.dependencies.js.snapshot/asset.6490295a04c28034be33f0e7add2c643691996e66a6caff4f557a4664483de66/index.js
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-nodejs/test/integ.dependencies.js.snapshot/asset.c46b90b3424f50a27aa24f1460102bd87d1223bb01f7f6bf13bc50b977ec916e/index.js
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-nodejs/test/integ.dependencies.js.snapshot/asset.c7937690d1d588b8d91f5f71328142498813c7e04ad7f0da1bb807f0e7ee29a1/index.js
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-nodejs/test/integ.dependencies.js.snapshot/asset.c7937690d1d588b8d91f5f71328142498813c7e04ad7f0da1bb807f0e7ee29a1/node_modules/.yarn-integrity
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-nodejs/test/integ.dependencies.js.snapshot/asset.cfdb46b4f2c6702b4a1cc8e23ca426e8de43d13567e73a8453d01c1176393814.bundle/index.js
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-nodejs/test/integ.dependencies.js.snapshot/asset.f18e0ca318e68187e84c6f675953eae3b2bde151a45dc8d579b13c372355d928/index.js
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-nodejs/test/integ.dependencies.js.snapshot/cdk-integ-lambda-nodejs-dependencies-for-sdk-v3-bundled.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-nodejs/test/integ.dependencies.js.snapshot/cdk-integ-lambda-nodejs-dependencies-for-sdk-v3-bundled.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-nodejs/test/integ.dependencies.js.snapshot/cdk-integ-lambda-nodejs-dependencies-for-sdk-v3.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-nodejs/test/integ.dependencies.js.snapshot/cdk-integ-lambda-nodejs-dependencies-for-sdk-v3.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-nodejs/test/integ.dependencies.js.snapshot/cdk-integ-lambda-nodejs-dependencies.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-nodejs/test/integ.dependencies.js.snapshot/cdk-integ-lambda-nodejs-dependencies.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-nodejs/test/integ.dependencies.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-nodejs/test/integ.dependencies.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-nodejs/test/integ.dependencies.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-nodejs/test/integ.dependencies.ts
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-nodejs/test/integ.latest.js.snapshot/LambdaNodeJsLatestIntegDefaultTestDeployAssertD40B5C28.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-nodejs/test/integ.latest.js.snapshot/LambdaNodeJsLatestIntegDefaultTestDeployAssertD40B5C28.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-nodejs/test/integ.latest.js.snapshot/asset.2729d9b4af60cbbbe3182f0002dec1747647eedd8de3761325aa38f7ddf73f24/index.js
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-nodejs/test/integ.latest.js.snapshot/asset.2729d9b4af60cbbbe3182f0002dec1747647eedd8de3761325aa38f7ddf73f24/node_modules/.yarn-integrity
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-nodejs/test/integ.latest.js.snapshot/asset.2729d9b4af60cbbbe3182f0002dec1747647eedd8de3761325aa38f7ddf73f24/node_modules/delay/index.d.ts
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-nodejs/test/integ.latest.js.snapshot/asset.2729d9b4af60cbbbe3182f0002dec1747647eedd8de3761325aa38f7ddf73f24/node_modules/delay/index.js
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-nodejs/test/integ.latest.js.snapshot/asset.2729d9b4af60cbbbe3182f0002dec1747647eedd8de3761325aa38f7ddf73f24/node_modules/delay/license
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-nodejs/test/integ.latest.js.snapshot/asset.2729d9b4af60cbbbe3182f0002dec1747647eedd8de3761325aa38f7ddf73f24/node_modules/delay/package.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-nodejs/test/integ.latest.js.snapshot/asset.2729d9b4af60cbbbe3182f0002dec1747647eedd8de3761325aa38f7ddf73f24/node_modules/delay/readme.md
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-nodejs/test/integ.latest.js.snapshot/asset.2729d9b4af60cbbbe3182f0002dec1747647eedd8de3761325aa38f7ddf73f24/package.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-nodejs/test/integ.latest.js.snapshot/asset.2729d9b4af60cbbbe3182f0002dec1747647eedd8de3761325aa38f7ddf73f24/yarn.lock
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-nodejs/test/integ.latest.js.snapshot/asset.965224955600e6822d85d934a24a912edd776b1fb4dc2d2bd455fd31fc18efe7/index.js
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-nodejs/test/integ.latest.js.snapshot/asset.965224955600e6822d85d934a24a912edd776b1fb4dc2d2bd455fd31fc18efe7/node_modules/delay/index.d.ts
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-nodejs/test/integ.latest.js.snapshot/asset.965224955600e6822d85d934a24a912edd776b1fb4dc2d2bd455fd31fc18efe7/node_modules/delay/index.js
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-nodejs/test/integ.latest.js.snapshot/asset.965224955600e6822d85d934a24a912edd776b1fb4dc2d2bd455fd31fc18efe7/node_modules/delay/license
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-nodejs/test/integ.latest.js.snapshot/asset.965224955600e6822d85d934a24a912edd776b1fb4dc2d2bd455fd31fc18efe7/node_modules/delay/package.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-nodejs/test/integ.latest.js.snapshot/asset.965224955600e6822d85d934a24a912edd776b1fb4dc2d2bd455fd31fc18efe7/node_modules/delay/readme.md
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-nodejs/test/integ.latest.js.snapshot/asset.965224955600e6822d85d934a24a912edd776b1fb4dc2d2bd455fd31fc18efe7/package.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-nodejs/test/integ.latest.js.snapshot/asset.965224955600e6822d85d934a24a912edd776b1fb4dc2d2bd455fd31fc18efe7/yarn.lock
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-nodejs/test/integ.latest.js.snapshot/cdk-integ-lambda-nodejs-latest.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-nodejs/test/integ.latest.js.snapshot/cdk-integ-lambda-nodejs-latest.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-nodejs/test/integ.latest.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-nodejs/test/integ.latest.js.snapshot/tree.json
  packages/aws-cdk-lib/aws-lambda-nodejs/README.md
  packages/aws-cdk-lib/aws-lambda-nodejs/lib/bundling.ts
  packages/aws-cdk-lib/aws-lambda-nodejs/test/bundling.test.ts
Labels: p2, contribution/core

#30111 chore(release): 2.141.0
  CHANGELOG.v2.alpha.md
  CHANGELOG.v2.md
  packages/@aws-cdk-testing/cli-integ/lib/aws.ts
  packages/@aws-cdk-testing/cli-integ/resources/cdk-apps/app/app.js
  packages/@aws-cdk-testing/cli-integ/tests/cli-integ-tests/cli.integtest.ts
  packages/@aws-cdk-testing/framework-integ/test/aws-ecr/test/integ.basic.js.snapshot/aws-ecr-integ-stack.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecr/test/integ.basic.js.snapshot/aws-ecr-integ-stack.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecr/test/integ.basic.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-ecr/test/integ.basic.js.snapshot/cdkecrintegtestbasicDefaultTestDeployAssert4F7FBFB4.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecr/test/integ.basic.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecr/test/integ.basic.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecr/test/integ.basic.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecr/test/integ.basic.ts
  packages/@aws-cdk-testing/framework-integ/test/aws-rds/test/integ.instance-with-parameter-group.js.snapshot/aws-cdk-rds-instance-with-rds-parameter-group.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-rds/test/integ.instance-with-parameter-group.js.snapshot/aws-cdk-rds-instance-with-rds-parameter-group.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-rds/test/integ.instance-with-parameter-group.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-rds/test/integ.instance-with-parameter-group.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-rds/test/integ.instance-with-parameter-group.ts
  packages/@aws-cdk-testing/framework-integ/test/pipelines/test/integ.newpipeline-with-file-system-locations.js
  packages/@aws-cdk-testing/framework-integ/test/pipelines/test/integ.newpipeline-with-file-system-locations.js.snapshot/PipelinesFileSystemLocations.assets.json
  packages/@aws-cdk-testing/framework-integ/test/pipelines/test/integ.newpipeline-with-file-system-locations.js.snapshot/PipelinesFileSystemLocations.template.json
  packages/@aws-cdk-testing/framework-integ/test/pipelines/test/integ.newpipeline-with-file-system-locations.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/pipelines/test/integ.newpipeline-with-file-system-locations.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/pipelines/test/integ.newpipeline-with-file-system-locations.ts
  packages/@aws-cdk-testing/framework-integ/test/pipelines/test/integ.newpipeline-with-vpc.ts
  packages/@aws-cdk/cloudformation-diff/lib/diff/types.ts
  packages/@aws-cdk/cloudformation-diff/lib/format.ts
  packages/@aws-cdk/cloudformation-diff/lib/iam/iam-changes.ts
  packages/@aws-cdk/cloudformation-diff/lib/iam/iam-identity-center.ts
  packages/@aws-cdk/cloudformation-diff/package.json
  packages/@aws-cdk/cloudformation-diff/test/iam/detect-changes.test.ts
  packages/@aws-cdk/cloudformation-diff/test/util.ts
  packages/@aws-cdk/integ-runner/package.json
  packages/aws-cdk-lib/aws-ecr/README.md
  packages/aws-cdk-lib/aws-ecr/lib/repository.ts
  packages/aws-cdk-lib/aws-ecr/test/repository.test.ts
  packages/aws-cdk-lib/aws-lambda/lib/function-base.ts
  packages/aws-cdk-lib/aws-lambda/test/function.test.ts
  packages/aws-cdk-lib/aws-rds/README.md
  packages/aws-cdk-lib/aws-rds/lib/parameter-group.ts
  packages/aws-cdk-lib/aws-rds/test/parameter-group.test.ts
  packages/aws-cdk-lib/aws-ses/lib/vdm-attributes.ts
  packages/aws-cdk-lib/cx-api/FEATURE_FLAGS.md
  packages/aws-cdk-lib/cx-api/lib/features.ts
  packages/aws-cdk-lib/cx-api/test/features.test.ts
  packages/aws-cdk-lib/package.json
  packages/aws-cdk-lib/pipelines/lib/codepipeline/codepipeline.ts
  packages/aws-cdk-lib/pipelines/test/codepipeline/codepipeline.test.ts
  packages/aws-cdk-lib/pipelines/test/compliance/assets.test.ts
  tools/@aws-cdk/spec2cdk/package.json
  version.v2.json
  yarn.lock
Labels: p2, pr/no-squash, auto-approve

#30118 chore(merge-back): 2.141.0
  CHANGELOG.v2.alpha.md
  CHANGELOG.v2.md
  packages/aws-cdk-lib/cx-api/FEATURE_FLAGS.md
  packages/aws-cdk-lib/cx-api/lib/features.ts
  version.v2.json
Labels: p2, pr/needs-community-review, pr/no-squash, auto-approve

#30115 chore: document reason and mitigation for cross region reference failure from response objects being too large
  packages/aws-cdk-lib/README.md
Labels: p2, contribution/core

#30112 fix(cli): handle attributes of AWS::KMS::Key when hotswapping
  packages/aws-cdk/lib/api/evaluate-cloudformation-template.ts
  packages/aws-cdk/test/api/hotswap/state-machine-hotswap-deployments.test.ts
Labels: bug, p1, effort/medium, contribution/core, pr-linter/exempt-integ-test, pr-linter/cli-integ-tested

#30127 chore(prlint): exemption request is now case insensitive
  tools/@aws-cdk/prlint/lint.ts
Labels: p2, contribution/core, pr/needs-maintainer-review

#30125 chore(prlint): additional log outputs for debugging
  tools/@aws-cdk/prlint/lint.ts
Labels: p2, contribution/core

#30113 fix(cli): cdk bootstrap --help does not show some options
  packages/aws-cdk/lib/cli.ts
Labels: bug, p1, effort/small, contribution/core, pr-linter/exempt-readme, pr-linter/exempt-test, pr-linter/exempt-integ-test, pr-linter/cli-integ-tested

#30122 chore(rds): add Aurora Postgres 16.2 cluster support
  packages/aws-cdk-lib/aws-rds/lib/cluster-engine.ts
Labels: p2, beginning-contributor

#30023 fix(iam): fromUserArn returns incorrect principalAccount
  packages/@aws-cdk-testing/framework-integ/test/aws-iam/test/integ.user-import.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-iam/test/integ.user-import.js.snapshot/dummy-stack.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-iam/test/integ.user-import.js.snapshot/dummy-stack.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-iam/test/integ.user-import.js.snapshot/dummystackintegtestDefaultTestDeployAssertF190D0AF.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-iam/test/integ.user-import.js.snapshot/dummystackintegtestDefaultTestDeployAssertF190D0AF.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-iam/test/integ.user-import.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-iam/test/integ.user-import.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-iam/test/integ.user-import.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-iam/test/integ.user-import.ts
  packages/aws-cdk-lib/aws-iam/lib/user.ts
  packages/aws-cdk-lib/aws-iam/test/user.test.ts
Labels: bug, p1, effort/medium, contribution/core

#28791 feat(docdb): support CA certificate for cluster instances
  packages/@aws-cdk-testing/framework-integ/test/aws-docdb/test/integ.cluster-instance-ca-certificate.js.snapshot/ClusterInstanceCACertificateTestDefaultTestDeployAssertD9510038.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-docdb/test/integ.cluster-instance-ca-certificate.js.snapshot/ClusterInstanceCACertificateTestDefaultTestDeployAssertD9510038.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-docdb/test/integ.cluster-instance-ca-certificate.js.snapshot/cdk-integ-docdb-cluster-instance-ca-certificate.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-docdb/test/integ.cluster-instance-ca-certificate.js.snapshot/cdk-integ-docdb-cluster-instance-ca-certificate.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-docdb/test/integ.cluster-instance-ca-certificate.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-docdb/test/integ.cluster-instance-ca-certificate.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-docdb/test/integ.cluster-instance-ca-certificate.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-docdb/test/integ.cluster-instance-ca-certificate.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-docdb/test/integ.cluster-instance-ca-certificate.ts
  packages/aws-cdk-lib/aws-docdb/README.md
  packages/aws-cdk-lib/aws-docdb/lib/cluster.ts
  packages/aws-cdk-lib/aws-docdb/lib/index.ts
  packages/aws-cdk-lib/aws-docdb/lib/instance.ts
  packages/aws-cdk-lib/aws-docdb/test/cluster.test.ts
  packages/aws-cdk-lib/aws-docdb/test/instance.test.ts
Labels: p2, feature-request, effort/medium, beginning-contributor

#30133 chore(cloudfront): fix example formatting in README
  packages/aws-cdk-lib/aws-cloudfront/README.md
Labels: p2, contribution/core

#30135 chore(rds): fix certificate enum values misspelling
  packages/@aws-cdk-testing/framework-integ/test/aws-docdb/test/integ.cluster-instance-ca-certificate.ts
  packages/@aws-cdk-testing/framework-integ/test/aws-rds/test/integ.instance-ca-certificate.ts
  packages/aws-cdk-lib/aws-docdb/README.md
  packages/aws-cdk-lib/aws-docdb/test/cluster.test.ts
  packages/aws-cdk-lib/aws-docdb/test/instance.test.ts
  packages/aws-cdk-lib/aws-rds/README.md
  packages/aws-cdk-lib/aws-rds/lib/ca-certificate.ts
  packages/aws-cdk-lib/aws-rds/test/cluster.test.ts
  packages/aws-cdk-lib/aws-rds/test/instance.test.ts
Labels: bug, p2, effort/small, contribution/core

#30096 docs(s3): update documentation for more context around `autoDeleteObjects`
  packages/aws-cdk-lib/aws-s3/README.md
  packages/aws-cdk-lib/aws-s3/lib/bucket.ts
Labels: p2, contribution/core

#29830 fix(cli): template created during import should be written to assets folder
  packages/@aws-cdk-testing/cli-integ/resources/cdk-apps/app/app.js
  packages/@aws-cdk-testing/cli-integ/tests/cli-integ-tests/cli.integtest.ts
  packages/aws-cdk/lib/api/util/template-body-parameter.ts
Labels: bug, p1, effort/small, pr-linter/exempt-integ-test, beginning-contributor, pr-linter/cli-integ-tested

#30020 fix(ecs): require task pidMode for Linux-based Fargate tasks, not host
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs/test/fargate/integ.runtime.js.snapshot/aws-ecs-integ-runtime.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs/test/fargate/integ.runtime.ts
  packages/aws-cdk-lib/aws-ecs/README.md
  packages/aws-cdk-lib/aws-ecs/lib/base/task-definition.ts
  packages/aws-cdk-lib/aws-ecs/lib/fargate/fargate-task-definition.ts
  packages/aws-cdk-lib/aws-ecs/lib/runtime-platform.ts
  packages/aws-cdk-lib/aws-ecs/test/fargate/fargate-service.test.ts
  packages/aws-cdk-lib/aws-ecs/test/fargate/fargate-task-definition.test.ts
Labels: bug, p2, effort/small, beginning-contributor

#30035 fix(apigateway): set authorization scope when authorization type is Cognito
  packages/@aws-cdk-testing/framework-integ/test/aws-apigateway/test/authorizers/assets/index.py
  packages/@aws-cdk-testing/framework-integ/test/aws-apigateway/test/authorizers/integ.api-with-authorizer-and-proxy.js.snapshot/apigatewaywithauthorizerandproxyDefaultTestDeployAssertDBEA1774.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-apigateway/test/authorizers/integ.api-with-authorizer-and-proxy.js.snapshot/apigatewaywithauthorizerandproxyDefaultTestDeployAssertDBEA1774.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-apigateway/test/authorizers/integ.api-with-authorizer-and-proxy.js.snapshot/asset.8b7a863f778f5314bab7fdad7a7957ef133c826bb93a8611a3bac36ae684e683/index.py
  packages/@aws-cdk-testing/framework-integ/test/aws-apigateway/test/authorizers/integ.api-with-authorizer-and-proxy.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-apigateway/test/authorizers/integ.api-with-authorizer-and-proxy.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-apigateway/test/authorizers/integ.api-with-authorizer-and-proxy.js.snapshot/integtest-restapi-with-authorizer-and-proxy.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-apigateway/test/authorizers/integ.api-with-authorizer-and-proxy.js.snapshot/integtest-restapi-with-authorizer-and-proxy.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-apigateway/test/authorizers/integ.api-with-authorizer-and-proxy.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-apigateway/test/authorizers/integ.api-with-authorizer-and-proxy.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-apigateway/test/authorizers/integ.api-with-authorizer-and-proxy.ts
  packages/aws-cdk-lib/aws-apigateway/lib/method.ts
  packages/aws-cdk-lib/aws-apigateway/test/method.test.ts
Labels: bug, p1, effort/medium, contribution/core

#29679 feat(asg): support keypair functionality for asg
  packages/@aws-cdk-testing/framework-integ/test/aws-autoscaling/test/integ.asg-keypair.js.snapshot/AsgIntegKeyPairDefaultTestDeployAssert4EC47FB2.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-autoscaling/test/integ.asg-keypair.js.snapshot/AsgIntegKeyPairDefaultTestDeployAssert4EC47FB2.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-autoscaling/test/integ.asg-keypair.js.snapshot/aws-cdk-asg-integ.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-autoscaling/test/integ.asg-keypair.js.snapshot/aws-cdk-asg-integ.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-autoscaling/test/integ.asg-keypair.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-autoscaling/test/integ.asg-keypair.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-autoscaling/test/integ.asg-keypair.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-autoscaling/test/integ.asg-keypair.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-autoscaling/test/integ.asg-keypair.ts
  packages/aws-cdk-lib/aws-autoscaling/README.md
  packages/aws-cdk-lib/aws-autoscaling/lib/auto-scaling-group.ts
  packages/aws-cdk-lib/aws-autoscaling/test/auto-scaling-group.test.ts
Labels: bug, p2, effort/medium, beginning-contributor

#30136 chore(logs): fix typo in README and comments
  packages/aws-cdk-lib/aws-logs/README.md
  packages/aws-cdk-lib/aws-logs/lib/data-protection-policy.ts
  packages/aws-cdk-lib/aws-logs/lib/log-group.ts
Labels: p2, pr-linter/exempt-test, repeat-contributor

#30153 chore: add new hire `Leo10Gama` to list
  .github/workflows/github-merit-badger.yml
  .mergify.yml
Labels: p2, pr/needs-community-review, beginning-contributor

#30150 fix(autoscaling): cooldown cannot be set with step scaling actions
  packages/@aws-cdk-testing/framework-integ/test/aws-autoscaling/test/integ.step-scaling-with-cooldown.js.snapshot/aws-cdk-autoscaling-integ.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-autoscaling/test/integ.step-scaling-with-cooldown.js.snapshot/aws-cdk-autoscaling-integ.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-autoscaling/test/integ.step-scaling-with-cooldown.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-autoscaling/test/integ.step-scaling-with-cooldown.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-autoscaling/test/integ.step-scaling-with-cooldown.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-autoscaling/test/integ.step-scaling-with-cooldown.js.snapshot/stepscalingwithcooldownDefaultTestDeployAssert13B8C40F.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-autoscaling/test/integ.step-scaling-with-cooldown.js.snapshot/stepscalingwithcooldownDefaultTestDeployAssert13B8C40F.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-autoscaling/test/integ.step-scaling-with-cooldown.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-autoscaling/test/integ.step-scaling-with-cooldown.ts
  packages/aws-cdk-lib/aws-apigateway/lib/method.ts
  packages/aws-cdk-lib/aws-autoscaling/lib/step-scaling-action.ts
  packages/aws-cdk-lib/aws-autoscaling/test/scaling.test.ts
Labels: bug, p2, effort/small, contribution/core

#30120 feat(docdb): add copyTagsToSnapshot property to the DatabaseCluster Construct
  packages/@aws-cdk-testing/framework-integ/test/aws-docdb/test/integ.cluster-copy-tags-to-snapshot.js.snapshot/ClusterTestDefaultTestDeployAssert6A1BBA9D.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-docdb/test/integ.cluster-copy-tags-to-snapshot.js.snapshot/ClusterTestDefaultTestDeployAssert6A1BBA9D.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-docdb/test/integ.cluster-copy-tags-to-snapshot.js.snapshot/asset.bde7b5c89cb43285f884c94f0b9e17cdb0f5eb5345005114dd60342e0b8a85a1/__entrypoint__.js
  packages/@aws-cdk-testing/framework-integ/test/aws-docdb/test/integ.cluster-copy-tags-to-snapshot.js.snapshot/asset.bde7b5c89cb43285f884c94f0b9e17cdb0f5eb5345005114dd60342e0b8a85a1/index.js
  packages/@aws-cdk-testing/framework-integ/test/aws-docdb/test/integ.cluster-copy-tags-to-snapshot.js.snapshot/aws-cdk-docdb-integ.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-docdb/test/integ.cluster-copy-tags-to-snapshot.js.snapshot/aws-cdk-docdb-integ.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-docdb/test/integ.cluster-copy-tags-to-snapshot.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-docdb/test/integ.cluster-copy-tags-to-snapshot.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-docdb/test/integ.cluster-copy-tags-to-snapshot.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-docdb/test/integ.cluster-copy-tags-to-snapshot.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-docdb/test/integ.cluster-copy-tags-to-snapshot.ts
  packages/aws-cdk-lib/aws-docdb/README.md
  packages/aws-cdk-lib/aws-docdb/lib/cluster.ts
  packages/aws-cdk-lib/aws-docdb/test/cluster.test.ts
Labels: p2, feature-request, beginning-contributor

#29584 feat(events-targets): add support for AppSync as an EventBridge rule target
  packages/@aws-cdk-testing/framework-integ/test/aws-events-targets/test/appsync/appsync.test.graphql
  packages/@aws-cdk-testing/framework-integ/test/aws-events-targets/test/appsync/integ.appsync-events.js.snapshot/aws-cdk-aws-appsync-target-integ.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-events-targets/test/appsync/integ.appsync-events.js.snapshot/aws-cdk-aws-appsync-target-integ.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-events-targets/test/appsync/integ.appsync-events.js.snapshot/awsappsyncintegDefaultTestDeployAssert7E101DC4.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-events-targets/test/appsync/integ.appsync-events.js.snapshot/awsappsyncintegDefaultTestDeployAssert7E101DC4.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-events-targets/test/appsync/integ.appsync-events.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-events-targets/test/appsync/integ.appsync-events.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-events-targets/test/appsync/integ.appsync-events.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-events-targets/test/appsync/integ.appsync-events.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-events-targets/test/appsync/integ.appsync-events.ts
  packages/aws-cdk-lib/aws-appsync/README.md
  packages/aws-cdk-lib/aws-appsync/lib/graphqlapi-base.ts
  packages/aws-cdk-lib/aws-appsync/lib/graphqlapi.ts
  packages/aws-cdk-lib/aws-events-targets/README.md
  packages/aws-cdk-lib/aws-events-targets/lib/appsync.ts
  packages/aws-cdk-lib/aws-events-targets/lib/index.ts
  packages/aws-cdk-lib/aws-events-targets/test/appsync/appsync.test.graphql
  packages/aws-cdk-lib/aws-events-targets/test/appsync/appsync.test.ts
  packages/aws-cdk-lib/aws-events/lib/rule.ts
  packages/aws-cdk-lib/aws-events/lib/target.ts
Labels: p2, beginning-contributor

#30159 docs(stepfunctions-tasks): fix typo
  packages/aws-cdk-lib/aws-stepfunctions-tasks/lib/athena/start-query-execution.ts
Labels: p2, beginning-contributor

#30147 chore(region-info): add missing dlc repository accounts.
  packages/@aws-cdk-testing/framework-integ/test/aws-codebuild/test/integ.aws-deep-learning-container-build-image.js.snapshot/aws-deep-learning-container-build-image.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-codebuild/test/integ.aws-deep-learning-container-build-image.js.snapshot/aws-deep-learning-container-build-image.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-codebuild/test/integ.aws-deep-learning-container-build-image.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-codebuild/test/integ.aws-deep-learning-container-build-image.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-codebuild/test/integ.aws-deep-learning-container-build-image.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-codebuild/test/integ.aws-deep-learning-container-build-image.js.snapshot/tree.json
  packages/@aws-cdk/aws-sagemaker-alpha/test/integ.model.js.snapshot/aws-cdk-sagemaker-model.assets.json
  packages/@aws-cdk/aws-sagemaker-alpha/test/integ.model.js.snapshot/aws-cdk-sagemaker-model.template.json
  packages/@aws-cdk/aws-sagemaker-alpha/test/integ.model.js.snapshot/cdk.out
  packages/@aws-cdk/aws-sagemaker-alpha/test/integ.model.js.snapshot/integ.json
  packages/@aws-cdk/aws-sagemaker-alpha/test/integ.model.js.snapshot/integtestmodelDefaultTestDeployAssertCF40BD53.assets.json
  packages/@aws-cdk/aws-sagemaker-alpha/test/integ.model.js.snapshot/manifest.json
  packages/@aws-cdk/aws-sagemaker-alpha/test/integ.model.js.snapshot/tree.json
  packages/aws-cdk-lib/region-info/build-tools/fact-tables.ts
Labels: p2, contribution/core

#29128 feat(codepipeline): `GitPullRequestFilter` for pipeline trigger
  packages/@aws-cdk-testing/framework-integ/test/aws-codepipeline-actions/test/integ.pipeline-with-pipeline-triggers.js.snapshot/asset.310f432b946edeef3316f39f32b344b6bdc401a3b438433db42adadab1bf5e17.bundle/index.js
  packages/@aws-cdk-testing/framework-integ/test/aws-codepipeline-actions/test/integ.pipeline-with-pipeline-triggers.js.snapshot/aws-cdk-codepipeline-with-pipeline-triggers.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-codepipeline-actions/test/integ.pipeline-with-pipeline-triggers.js.snapshot/aws-cdk-codepipeline-with-pipeline-triggers.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-codepipeline-actions/test/integ.pipeline-with-pipeline-triggers.js.snapshot/codepipelinewithpipelinetriggerstestDefaultTestDeployAssertE3F8DDE6.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-codepipeline-actions/test/integ.pipeline-with-pipeline-triggers.js.snapshot/codepipelinewithpipelinetriggerstestDefaultTestDeployAssertE3F8DDE6.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-codepipeline-actions/test/integ.pipeline-with-pipeline-triggers.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-codepipeline-actions/test/integ.pipeline-with-pipeline-triggers.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-codepipeline-actions/test/integ.pipeline-with-pipeline-triggers.ts
  packages/aws-cdk-lib/aws-codepipeline/README.md
  packages/aws-cdk-lib/aws-codepipeline/lib/trigger.ts
  packages/aws-cdk-lib/aws-codepipeline/test/triggers.test.ts
Labels: p2, feature-request, effort/medium, distinguished-contributor, pr-linter/do-not-close

#30053 fix(s3): add bucket policy dependency to notification resource
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-event-sources/test/integ.s3.js.snapshot/lambda-event-source-s3.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-s3-notifications/test/sqs/integ.bucket-notifications.js.snapshot/sqs-bucket-notifications.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-s3/test/integ.bucket.notifications.js.snapshot/aws-cdk-s3-notifications.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-s3/test/integ.bucket.notifications.js.snapshot/aws-cdk-s3-notifications.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-s3/test/integ.bucket.notifications.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-s3/test/integ.bucket.notifications.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-s3/test/integ.bucket.notifications.ts
  packages/aws-cdk-lib/aws-s3/lib/notifications-resource/notifications-resource.ts
  packages/aws-cdk-lib/aws-s3/test/notification.test.ts
Labels: bug, p1, effort/small, valued-contributor

#30077 fix(stepfunctions-tasks): documentation fix for retryOnServiceExceptions
  packages/aws-cdk-lib/aws-stepfunctions-tasks/lib/lambda/invoke.ts
Labels: p2, docs/inline, pr-linter/exempt-test, pr-linter/exempt-integ-test, beginning-contributor

#29987 feat(pipes-targets): add step functions state machine target
  packages/@aws-cdk/aws-pipes-targets-alpha/README.md
  packages/@aws-cdk/aws-pipes-targets-alpha/lib/index.ts
  packages/@aws-cdk/aws-pipes-targets-alpha/lib/stepfunctions.ts
  packages/@aws-cdk/aws-pipes-targets-alpha/rosetta/default.ts-fixture
  packages/@aws-cdk/aws-pipes-targets-alpha/test/__snapshots__/stepfunctions.test.ts.snap
  packages/@aws-cdk/aws-pipes-targets-alpha/test/integ.stepfunctions.js.snapshot/asset.cfdb46b4f2c6702b4a1cc8e23ca426e8de43d13567e73a8453d01c1176393814.bundle/index.js
  packages/@aws-cdk/aws-pipes-targets-alpha/test/integ.stepfunctions.js.snapshot/aws-cdk-pipes-sfn-target.assets.json
  packages/@aws-cdk/aws-pipes-targets-alpha/test/integ.stepfunctions.js.snapshot/aws-cdk-pipes-sfn-target.template.json
  packages/@aws-cdk/aws-pipes-targets-alpha/test/integ.stepfunctions.js.snapshot/cdk.out
  packages/@aws-cdk/aws-pipes-targets-alpha/test/integ.stepfunctions.js.snapshot/integ.json
  packages/@aws-cdk/aws-pipes-targets-alpha/test/integ.stepfunctions.js.snapshot/integtestpipetargetsfnDefaultTestDeployAssert006F7F8F.assets.json
  packages/@aws-cdk/aws-pipes-targets-alpha/test/integ.stepfunctions.js.snapshot/integtestpipetargetsfnDefaultTestDeployAssert006F7F8F.template.json
  packages/@aws-cdk/aws-pipes-targets-alpha/test/integ.stepfunctions.js.snapshot/manifest.json
  packages/@aws-cdk/aws-pipes-targets-alpha/test/integ.stepfunctions.js.snapshot/tree.json
  packages/@aws-cdk/aws-pipes-targets-alpha/test/integ.stepfunctions.ts
  packages/@aws-cdk/aws-pipes-targets-alpha/test/stepfunctions.test.ts
Labels: p2, feature-request, pr/needs-community-review, effort/medium, repeat-contributor

#29976 feat(redshift): multi AZ cluster
  packages/@aws-cdk/aws-redshift-alpha/README.md
  packages/@aws-cdk/aws-redshift-alpha/lib/cluster.ts
  packages/@aws-cdk/aws-redshift-alpha/test/cluster.test.ts
  packages/@aws-cdk/aws-redshift-alpha/test/integ.cluster-multi-az.js.snapshot/MultiAzRedshift.assets.json
  packages/@aws-cdk/aws-redshift-alpha/test/integ.cluster-multi-az.js.snapshot/MultiAzRedshift.template.json
  packages/@aws-cdk/aws-redshift-alpha/test/integ.cluster-multi-az.js.snapshot/MultiAzRedshiftTestDefaultTestDeployAssert07040285.assets.json
  packages/@aws-cdk/aws-redshift-alpha/test/integ.cluster-multi-az.js.snapshot/MultiAzRedshiftTestDefaultTestDeployAssert07040285.template.json
  packages/@aws-cdk/aws-redshift-alpha/test/integ.cluster-multi-az.js.snapshot/cdk.out
  packages/@aws-cdk/aws-redshift-alpha/test/integ.cluster-multi-az.js.snapshot/integ.json
  packages/@aws-cdk/aws-redshift-alpha/test/integ.cluster-multi-az.js.snapshot/manifest.json
  packages/@aws-cdk/aws-redshift-alpha/test/integ.cluster-multi-az.js.snapshot/tree.json
  packages/@aws-cdk/aws-redshift-alpha/test/integ.cluster-multi-az.ts
Labels: p2, star-contributor

#30105 feat(servicecatalog): `ProductStack` memoryLimit prop
  packages/@aws-cdk-testing/framework-integ/test/aws-servicecatalog/test/integ.two-products.js.snapshot/integ-servicecatalog-two-products.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-servicecatalog/test/integ.two-products.js.snapshot/integ-servicecatalog-two-products.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-servicecatalog/test/integ.two-products.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-servicecatalog/test/integ.two-products.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-servicecatalog/test/integ.two-products.ts
  packages/aws-cdk-lib/aws-servicecatalog/lib/private/product-stack-synthesizer.ts
  packages/aws-cdk-lib/aws-servicecatalog/lib/product-stack.ts
  packages/aws-cdk-lib/aws-servicecatalog/test/product-stack.test.ts
Labels: p2, feature-request, effort/small, pr-linter/exempt-readme, distinguished-contributor

#30216 chore: add new hire `scorbiere` to list
  .github/workflows/github-merit-badger.yml
  .mergify.yml
Labels: p2, beginning-contributor

#30227 chore(merge-back): 2.142.0
  CHANGELOG.v2.alpha.md
  CHANGELOG.v2.md
  version.v2.json
Labels: p2, pr/needs-community-review, pr/no-squash, auto-approve

#30184 fix(s3): bucketKey does not support SSE-S3
  packages/@aws-cdk-testing/framework-integ/test/aws-s3/test/integ.bucket-encryption.js.snapshot/IntegTestDSSEBucketDefaultTestDeployAssert56801A2F.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-s3/test/integ.bucket-encryption.js.snapshot/aws-cdk-s3-bucket-encryption.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-s3/test/integ.bucket-encryption.js.snapshot/aws-cdk-s3-bucket-encryption.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-s3/test/integ.bucket-encryption.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-s3/test/integ.bucket-encryption.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-s3/test/integ.bucket-encryption.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-s3/test/integ.bucket-encryption.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-s3/test/integ.bucket-encryption.ts
  packages/aws-cdk-lib/aws-s3/lib/bucket.ts
  packages/aws-cdk-lib/aws-s3/test/bucket.test.ts
Labels: bug, p2, effort/medium, contribution/core

#30189 fix(events_targets): kinesisfirehosestream not accepting ideliverystream for imported deliverystream
  packages/@aws-cdk/aws-kinesisfirehose-alpha/package.json
  packages/@aws-cdk/aws-kinesisfirehose-alpha/test/delivery-stream.test.ts
  packages/@aws-cdk/aws-kinesisfirehose-alpha/test/integ.kinesis-stream-events-target.js.snapshot/aws-cdk-firehose-delivery-stream.assets.json
  packages/@aws-cdk/aws-kinesisfirehose-alpha/test/integ.kinesis-stream-events-target.js.snapshot/aws-cdk-firehose-delivery-stream.template.json
  packages/@aws-cdk/aws-kinesisfirehose-alpha/test/integ.kinesis-stream-events-target.js.snapshot/cdk.out
  packages/@aws-cdk/aws-kinesisfirehose-alpha/test/integ.kinesis-stream-events-target.js.snapshot/integ.json
  packages/@aws-cdk/aws-kinesisfirehose-alpha/test/integ.kinesis-stream-events-target.js.snapshot/integtestsDefaultTestDeployAssert44C8D370.assets.json
  packages/@aws-cdk/aws-kinesisfirehose-alpha/test/integ.kinesis-stream-events-target.js.snapshot/integtestsDefaultTestDeployAssert44C8D370.template.json
  packages/@aws-cdk/aws-kinesisfirehose-alpha/test/integ.kinesis-stream-events-target.js.snapshot/manifest.json
  packages/@aws-cdk/aws-kinesisfirehose-alpha/test/integ.kinesis-stream-events-target.js.snapshot/tree.json
  packages/@aws-cdk/aws-kinesisfirehose-alpha/test/integ.kinesis-stream-events-target.ts
  packages/aws-cdk-lib/aws-events-targets/lib/kinesis-firehose-stream.ts
Labels: bug, p1, effort/small, contribution/core

#30168 chore(rds): add aurora postgresql versions 12.18, 13.14 and 14.11
  packages/aws-cdk-lib/aws-rds/lib/cluster-engine.ts
Labels: p2, repeat-contributor

#30243 revert: "fix(diff): properties from ChangeSet diff were ignored"
  packages/@aws-cdk-testing/cli-integ/lib/aws.ts
  packages/@aws-cdk-testing/cli-integ/package.json
  packages/@aws-cdk-testing/cli-integ/resources/cdk-apps/app/app.js
  packages/@aws-cdk-testing/cli-integ/tests/cli-integ-tests/cli.integtest.ts
  packages/@aws-cdk/cloudformation-diff/lib/diff-template.ts
  packages/@aws-cdk/cloudformation-diff/lib/diff/types.ts
  packages/@aws-cdk/cloudformation-diff/test/diff-template.test.ts
  packages/@aws-cdk/cloudformation-diff/test/util.ts
Labels: p2, contribution/core, pr/needs-cli-test-run

#30169 chore(neptune): add neptune engine version 1.3.1.0
  packages/@aws-cdk/aws-neptune-alpha/lib/cluster.ts
Labels: p2, repeat-contributor

#30178 feat(cognito): add enablePropagateAdditionalUserContextData to UserClient Construct
  packages/@aws-cdk-testing/framework-integ/test/aws-cognito/test/integ.user-pool-client-enable-propagate-additional-data.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-cognito/test/integ.user-pool-client-enable-propagate-additional-data.js.snapshot/integ-user-pool-client-enable-propagate-additional-data.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-cognito/test/integ.user-pool-client-enable-propagate-additional-data.js.snapshot/integ-user-pool-client-enable-propagate-additional-data.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-cognito/test/integ.user-pool-client-enable-propagate-additional-data.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-cognito/test/integ.user-pool-client-enable-propagate-additional-data.js.snapshot/integuserpoolclientenablepropagateadditionaldatatestDefaultTestDeployAssertE48CC71B.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-cognito/test/integ.user-pool-client-enable-propagate-additional-data.js.snapshot/integuserpoolclientenablepropagateadditionaldatatestDefaultTestDeployAssertE48CC71B.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-cognito/test/integ.user-pool-client-enable-propagate-additional-data.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-cognito/test/integ.user-pool-client-enable-propagate-additional-data.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-cognito/test/integ.user-pool-client-enable-propagate-additional-data.ts
  packages/aws-cdk-lib/aws-cognito/README.md
  packages/aws-cdk-lib/aws-cognito/lib/user-pool-client.ts
  packages/aws-cdk-lib/aws-cognito/test/user-pool-client.test.ts
Labels: p2, repeat-contributor

#30245 chore(cli): skipping old cli integ test `cdk diff changes in change set` for new changes
  packages/@aws-cdk-testing/cli-integ/resources/cli-regression-patches/v2.142.0/NOTES.md
  packages/@aws-cdk-testing/cli-integ/resources/cli-regression-patches/v2.142.0/skip-tests.txt
Labels: p2, contribution/core, pr-linter/cli-integ-tested

#29956 fix(elbv2): unable to deploy template with IPv4 load balancer when denyAllIgwTraffic set
  packages/@aws-cdk-testing/framework-integ/test/aws-elasticloadbalancingv2/test/integ.nlb.attributes.js.snapshot/aws-cdk-nlb-attributes-integ.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-elasticloadbalancingv2/test/integ.nlb.attributes.js.snapshot/aws-cdk-nlb-attributes-integ.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-elasticloadbalancingv2/test/integ.nlb.attributes.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-elasticloadbalancingv2/test/integ.nlb.attributes.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-elasticloadbalancingv2/test/integ.nlb.attributes.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-elasticloadbalancingv2/test/integ.nlb.attributes.js.snapshot/nlbattlibutesintegDefaultTestDeployAssert2D727654.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-elasticloadbalancingv2/test/integ.nlb.attributes.js.snapshot/nlbattlibutesintegDefaultTestDeployAssert2D727654.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-elasticloadbalancingv2/test/integ.nlb.attributes.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-elasticloadbalancingv2/test/integ.nlb.attributes.ts
  packages/@aws-cdk-testing/framework-integ/test/aws-elasticloadbalancingv2/test/integ.nlb.dualstack.internal.js.snapshot/NlbDualstackInternalIntegDefaultTestDeployAssertEEBE69CB.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-elasticloadbalancingv2/test/integ.nlb.dualstack.internal.js.snapshot/aws-cdk-nlb-dualstack-internal.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-elasticloadbalancingv2/test/integ.nlb.dualstack.internal.js.snapshot/aws-cdk-nlb-dualstack-internal.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-elasticloadbalancingv2/test/integ.nlb.dualstack.internal.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-elasticloadbalancingv2/test/integ.nlb.dualstack.internal.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-elasticloadbalancingv2/test/integ.nlb.dualstack.internal.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-elasticloadbalancingv2/test/integ.nlb.dualstack.internal.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-elasticloadbalancingv2/test/integ.nlb.dualstack.internal.ts
  packages/aws-cdk-lib/aws-elasticloadbalancingv2/lib/shared/base-load-balancer.ts
  packages/aws-cdk-lib/aws-elasticloadbalancingv2/test/alb/load-balancer.test.ts
  packages/aws-cdk-lib/aws-elasticloadbalancingv2/test/nlb/load-balancer.test.ts
Labels: bug, p2, @aws-cdk/aws-elasticloadbalancingv2, beginning-contributor

#30249 chore(release): v2.142.1
  CHANGELOG.v2.alpha.md
  CHANGELOG.v2.md
  packages/@aws-cdk-testing/cli-integ/lib/aws.ts
  packages/@aws-cdk-testing/cli-integ/package.json
  packages/@aws-cdk-testing/cli-integ/resources/cdk-apps/app/app.js
  packages/@aws-cdk-testing/cli-integ/resources/cli-regression-patches/v2.142.0/NOTES.md
  packages/@aws-cdk-testing/cli-integ/resources/cli-regression-patches/v2.142.0/skip-tests.txt
  packages/@aws-cdk-testing/cli-integ/tests/cli-integ-tests/cli.integtest.ts
  packages/@aws-cdk/cloudformation-diff/lib/diff-template.ts
  packages/@aws-cdk/cloudformation-diff/lib/diff/types.ts
  packages/@aws-cdk/cloudformation-diff/test/diff-template.test.ts
  packages/@aws-cdk/cloudformation-diff/test/util.ts
  version.v2.json
Labels: p2, contribution/core, pr/no-squash, pr-linter/cli-integ-tested, pr/needs-maintainer-review

#30250 chore(merge-back): 2.142.1
  CHANGELOG.v2.alpha.md
  CHANGELOG.v2.md
  version.v2.json
Labels: p2, pr/needs-community-review, pr/no-squash, auto-approve

#30259 chore(eks): improve documentation for updating a cluster
  packages/aws-cdk-lib/aws-eks/README.md
Labels: p2, contribution/core

#30158 feat(batch): jobStateTimeLimitActions property added
  packages/@aws-cdk-testing/framework-integ/test/aws-batch/test/integ.job-queue-job-state-time-limit-actions.js.snapshot/BatchEcsJobDefinitionTestDefaultTestDeployAssertE5BAAC9B.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-batch/test/integ.job-queue-job-state-time-limit-actions.js.snapshot/BatchEcsJobDefinitionTestDefaultTestDeployAssertE5BAAC9B.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-batch/test/integ.job-queue-job-state-time-limit-actions.js.snapshot/asset.bde7b5c89cb43285f884c94f0b9e17cdb0f5eb5345005114dd60342e0b8a85a1/__entrypoint__.js
  packages/@aws-cdk-testing/framework-integ/test/aws-batch/test/integ.job-queue-job-state-time-limit-actions.js.snapshot/asset.bde7b5c89cb43285f884c94f0b9e17cdb0f5eb5345005114dd60342e0b8a85a1/index.js
  packages/@aws-cdk-testing/framework-integ/test/aws-batch/test/integ.job-queue-job-state-time-limit-actions.js.snapshot/batch-stack-job-queue.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-batch/test/integ.job-queue-job-state-time-limit-actions.js.snapshot/batch-stack-job-queue.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-batch/test/integ.job-queue-job-state-time-limit-actions.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-batch/test/integ.job-queue-job-state-time-limit-actions.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-batch/test/integ.job-queue-job-state-time-limit-actions.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-batch/test/integ.job-queue-job-state-time-limit-actions.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-batch/test/integ.job-queue-job-state-time-limit-actions.ts
  packages/aws-cdk-lib/aws-batch/README.md
  packages/aws-cdk-lib/aws-batch/lib/job-queue.ts
  packages/aws-cdk-lib/aws-batch/test/job-queue.test.ts
Labels: p2, feature-request, effort/medium, beginning-contributor

#30201 chore(secrets): bump semanticVersion for aws-cn
  packages/@aws-cdk-testing/framework-integ/test/aws-docdb/test/integ.cluster-rotation.lit.js.snapshot/aws-cdk-docdb-cluster-rotation.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-docdb/test/integ.cluster-rotation.lit.js.snapshot/aws-cdk-docdb-cluster-rotation.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-docdb/test/integ.cluster-rotation.lit.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-docdb/test/integ.cluster-rotation.lit.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-rds/test/integ.cluster-rotation.lit.js.snapshot/aws-cdk-rds-cluster-rotation.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-rds/test/integ.cluster-rotation.lit.js.snapshot/aws-cdk-rds-cluster-rotation.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-rds/test/integ.cluster-rotation.lit.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-rds/test/integ.cluster-rotation.lit.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-rds/test/integ.cluster-snapshot.js.snapshot/cdk-integ-cluster-snapshot.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-rds/test/integ.cluster-snapshot.js.snapshot/cdk-integ-cluster-snapshot.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-rds/test/integ.cluster-snapshot.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-rds/test/integ.instance.lit.js.snapshot/aws-cdk-rds-instance.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-rds/test/integ.instance.lit.js.snapshot/aws-cdk-rds-instance.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-rds/test/integ.instance.lit.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-rds/test/integ.instance.lit.js.snapshot/tree.json
  packages/aws-cdk-lib/aws-secretsmanager/lib/secret-rotation.ts
Labels: p1, effort/small, @aws-cdk/aws-secretsmanager, contribution/core

#30242 chore(rds): add support for postgres 16.3 engine
  packages/@aws-cdk-testing/framework-integ/test/aws-rds/test/integ.instance-dual.js.snapshot/aws-cdk-rds-instance-dual-integ.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-rds/test/integ.instance-dual.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-rds/test/integ.instance-dual.ts
  packages/@aws-cdk-testing/framework-integ/test/aws-rds/test/integ.instance-s3-postgres.js.snapshot/aws-cdk-rds-instance-s3-postgres-integ.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-rds/test/integ.instance-s3-postgres.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-rds/test/integ.instance-s3-postgres.ts
  packages/@aws-cdk-testing/framework-integ/test/aws-rds/test/integ.instance-with-metric.js.snapshot/aws-cdk-rds-instance-with-metric.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-rds/test/integ.instance-with-metric.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-rds/test/integ.instance-with-metric.ts
  packages/@aws-cdk-testing/framework-integ/test/aws-rds/test/integ.instance-with-parameter-group.js.snapshot/aws-cdk-rds-instance-with-rds-parameter-group.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-rds/test/integ.instance-with-parameter-group.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-rds/test/integ.instance-with-parameter-group.ts
  packages/@aws-cdk-testing/framework-integ/test/aws-rds/test/integ.proxy.js.snapshot/aws-cdk-rds-proxy.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-rds/test/integ.proxy.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-rds/test/integ.proxy.ts
  packages/@aws-cdk-testing/framework-integ/test/aws-rds/test/integ.read-replica.js.snapshot/cdk-rds-read-replica.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-rds/test/integ.read-replica.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-rds/test/integ.read-replica.ts
  packages/aws-cdk-lib/aws-rds/README.md
  packages/aws-cdk-lib/aws-rds/lib/cluster-engine.ts
  packages/aws-cdk-lib/aws-rds/lib/instance-engine.ts
  packages/aws-cdk-lib/aws-rds/test/instance-engine.test.ts
  packages/aws-cdk-lib/aws-rds/test/instance.test.ts
Labels: p2, beginning-contributor

#30279 docs(event-targets): clarify that adding an imported SNS Topic as an event target does not set required permissions
  packages/aws-cdk-lib/aws-events-targets/lib/sns.ts
Labels: p2, feature-request, effort/small, star-contributor

#30286 chore(stepfunctions): add `waitForAssertions` to distributed-map assertions to wait for the expected resource state
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions/test/integ.distributed-map.js.snapshot/DistributedMapDefaultTestDeployAssertFD6CBCC4.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions/test/integ.distributed-map.js.snapshot/DistributedMapDefaultTestDeployAssertFD6CBCC4.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions/test/integ.distributed-map.js.snapshot/asset.2ec8ad9e91dcd6e7ad6a5c84ffc6c9c05c408aca3b26ceb2816d81043e6c4dc3/index.js
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions/test/integ.distributed-map.js.snapshot/asset.96ea260348625427bb7f28ab3b379f62da6f428bcd155cb13f9261aa6a404b0d/index.js
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions/test/integ.distributed-map.js.snapshot/asset.cfdb46b4f2c6702b4a1cc8e23ca426e8de43d13567e73a8453d01c1176393814.bundle/index.js
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions/test/integ.distributed-map.js.snapshot/aws-stepfunctions-map-integ.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions/test/integ.distributed-map.js.snapshot/aws-stepfunctions-map-integ.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions/test/integ.distributed-map.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions/test/integ.distributed-map.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions/test/integ.distributed-map.ts
Labels: p2, contribution/core

#30282 chore(rds): deprecate unsupported aurora mysql versions
  packages/@aws-cdk-testing/framework-integ/test/aws-rds/test/integ.cluster-instance-id.js.snapshot/Default.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-rds/test/integ.cluster-instance-id.js.snapshot/Default.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-rds/test/integ.cluster-instance-id.js.snapshot/asset.18d379b052acd60e0d086d5b19d9bef956ebc0bd018c5570960125aab0c7f837/__entrypoint__.js
  packages/@aws-cdk-testing/framework-integ/test/aws-rds/test/integ.cluster-instance-id.js.snapshot/asset.18d379b052acd60e0d086d5b19d9bef956ebc0bd018c5570960125aab0c7f837/index.js
  packages/@aws-cdk-testing/framework-integ/test/aws-rds/test/integ.cluster-instance-id.js.snapshot/asset.bde7b5c89cb43285f884c94f0b9e17cdb0f5eb5345005114dd60342e0b8a85a1/__entrypoint__.js
  packages/@aws-cdk-testing/framework-integ/test/aws-rds/test/integ.cluster-instance-id.js.snapshot/asset.bde7b5c89cb43285f884c94f0b9e17cdb0f5eb5345005114dd60342e0b8a85a1/index.js
  packages/@aws-cdk-testing/framework-integ/test/aws-rds/test/integ.cluster-instance-id.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-rds/test/integ.cluster-instance-id.js.snapshot/instanceIdentifiersTestDefaultTestDeployAssertC062AEBE.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-rds/test/integ.cluster-instance-id.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-rds/test/integ.cluster-instance-id.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-rds/test/integ.cluster-instance-id.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-rds/test/integ.cluster-instance-id.ts
  packages/@aws-cdk-testing/framework-integ/test/aws-rds/test/integ.cluster-kerberos.js.snapshot/asset.4554b47be6f57b68c6c7a7391dcc73894866d2377fe174883351e7639097f292/__entrypoint__.js
  packages/@aws-cdk-testing/framework-integ/test/aws-rds/test/integ.cluster-kerberos.js.snapshot/asset.bde7b5c89cb43285f884c94f0b9e17cdb0f5eb5345005114dd60342e0b8a85a1/__entrypoint__.js
  packages/@aws-cdk-testing/framework-integ/test/aws-rds/test/integ.cluster-kerberos.js.snapshot/asset.bde7b5c89cb43285f884c94f0b9e17cdb0f5eb5345005114dd60342e0b8a85a1/index.js
  packages/@aws-cdk-testing/framework-integ/test/aws-rds/test/integ.cluster-kerberos.js.snapshot/cluster-kerberos.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-rds/test/integ.cluster-kerberos.js.snapshot/cluster-kerberos.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-rds/test/integ.cluster-kerberos.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-rds/test/integ.cluster-kerberos.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-rds/test/integ.cluster-kerberos.ts
  packages/aws-cdk-lib/aws-rds/lib/cluster-engine.ts
Labels: p2, contribution/core

#30296 chore(rds): removed unreleased aurora postgres 16.3 cluster engine.
  packages/aws-cdk-lib/aws-rds/lib/cluster-engine.ts
Labels: p2, feature-request, @aws-cdk/aws-rds, effort/small, beginning-contributor

#30302 fix(stepfunctions-tasks): runtime language used to evaluate expressions is ignored
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/integ.evaluate-expression-default-runtime.js.snapshot/EvaluateExpressionIntegDefaultTestDeployAssert03097648.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/integ.evaluate-expression-default-runtime.js.snapshot/EvaluateExpressionIntegDefaultTestDeployAssert03097648.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/integ.evaluate-expression-default-runtime.js.snapshot/asset.b8cec122f25692e8b194663d25a2ee5e0b65e55df966120791d6a3ddc08fc136/index.js
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/integ.evaluate-expression-default-runtime.js.snapshot/cdk-sfn-evaluate-expression-default-runtime-integ.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/integ.evaluate-expression-default-runtime.js.snapshot/cdk-sfn-evaluate-expression-default-runtime-integ.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/integ.evaluate-expression-default-runtime.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/integ.evaluate-expression-default-runtime.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/integ.evaluate-expression-default-runtime.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/integ.evaluate-expression-default-runtime.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/integ.evaluate-expression-default-runtime.ts
  packages/@aws-cdk/custom-resource-handlers/lib/custom-resources-framework/classes.ts
  packages/@aws-cdk/custom-resource-handlers/lib/custom-resources-framework/modules.ts
  packages/@aws-cdk/custom-resource-handlers/test/custom-resources-framework/expected/singleton-function-eval-nodejs.ts
  packages/@aws-cdk/custom-resource-handlers/test/custom-resources-framework/framework.test.ts
  packages/aws-cdk-lib/aws-stepfunctions-tasks/lib/evaluate-expression.ts
Labels: p2, contribution/core, pr/needs-maintainer-review

#30293 feat(ec2): support placementGroup for ec2.Instance
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.instance-placement-group.js.snapshot/Ec2InstancePlacementGroupDefaultTestDeployAssertCBC801E8.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.instance-placement-group.js.snapshot/Ec2InstancePlacementGroupDefaultTestDeployAssertCBC801E8.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.instance-placement-group.js.snapshot/asset.bde7b5c89cb43285f884c94f0b9e17cdb0f5eb5345005114dd60342e0b8a85a1/__entrypoint__.js
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.instance-placement-group.js.snapshot/asset.bde7b5c89cb43285f884c94f0b9e17cdb0f5eb5345005114dd60342e0b8a85a1/index.js
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.instance-placement-group.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.instance-placement-group.js.snapshot/ec2-instance-placementgroup-stack.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.instance-placement-group.js.snapshot/ec2-instance-placementgroup-stack.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.instance-placement-group.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.instance-placement-group.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.instance-placement-group.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.instance-placement-group.ts
  packages/aws-cdk-lib/aws-ec2/README.md
  packages/aws-cdk-lib/aws-ec2/lib/instance.ts
  packages/aws-cdk-lib/aws-ec2/test/instance.test.ts
Labels: p2, feature-request, effort/medium, contribution/core

#30277 fix(rds): readers not always be created after the writer
  packages/@aws-cdk-testing/framework-integ/test/aws-rds/test/integ.cluster-instance-id.js.snapshot/Default.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-rds/test/integ.cluster-instance-id.js.snapshot/Default.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-rds/test/integ.cluster-instance-id.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-rds/test/integ.cluster-serverless-v2.js.snapshot/asset.18d379b052acd60e0d086d5b19d9bef956ebc0bd018c5570960125aab0c7f837/__entrypoint__.js
  packages/@aws-cdk-testing/framework-integ/test/aws-rds/test/integ.cluster-serverless-v2.js.snapshot/asset.18d379b052acd60e0d086d5b19d9bef956ebc0bd018c5570960125aab0c7f837/index.js
  packages/@aws-cdk-testing/framework-integ/test/aws-rds/test/integ.cluster-serverless-v2.js.snapshot/asset.bde7b5c89cb43285f884c94f0b9e17cdb0f5eb5345005114dd60342e0b8a85a1/__entrypoint__.js
  packages/@aws-cdk-testing/framework-integ/test/aws-rds/test/integ.cluster-serverless-v2.js.snapshot/asset.bde7b5c89cb43285f884c94f0b9e17cdb0f5eb5345005114dd60342e0b8a85a1/index.js
  packages/@aws-cdk-testing/framework-integ/test/aws-rds/test/integ.cluster-serverless-v2.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-rds/test/integ.cluster-serverless-v2.js.snapshot/integ-aurora-serverlessv2-cluster.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-rds/test/integ.cluster-serverless-v2.js.snapshot/integ-aurora-serverlessv2-cluster.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-rds/test/integ.cluster-serverless-v2.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-rds/test/integ.cluster-serverless-v2.js.snapshot/integtestDefaultTestDeployAssert24D5C536.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-rds/test/integ.cluster-serverless-v2.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-rds/test/integ.cluster-serverless-v2.js.snapshot/tree.json
  packages/aws-cdk-lib/aws-rds/lib/cluster.ts
  packages/aws-cdk-lib/aws-rds/test/cluster.test.ts
Labels: bug, p1, effort/medium, contribution/core, pr-linter/exempt-integ-test

#30312 chore: add new team member `samson-keung`
  .github/workflows/github-merit-badger.yml
  .mergify.yml
Labels: p2, beginning-contributor

#30182 feat: update L1 CloudFormation resource definitions
  packages/@aws-cdk/cloudformation-diff/package.json
  packages/@aws-cdk/integ-runner/package.json
  packages/aws-cdk-lib/package.json
  tools/@aws-cdk/spec2cdk/package.json
  yarn.lock
Labels: p2, dependencies, contribution/core, pr-linter/exempt-readme, pr-linter/exempt-test, auto-approve, pr-linter/exempt-integ-test

#30141 feat(codebuild): add deleteReports property to the ReportGroup Construct
  packages/@aws-cdk-testing/framework-integ/test/aws-codebuild/test/integ.report-group-delete-reports.js.snapshot/ReportGroupDeleteReportsIntegTestDefaultTestDeployAssertFBD2FDC0.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-codebuild/test/integ.report-group-delete-reports.js.snapshot/ReportGroupDeleteReportsIntegTestDefaultTestDeployAssertFBD2FDC0.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-codebuild/test/integ.report-group-delete-reports.js.snapshot/aws-cdk-report-group-delete-reports.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-codebuild/test/integ.report-group-delete-reports.js.snapshot/aws-cdk-report-group-delete-reports.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-codebuild/test/integ.report-group-delete-reports.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-codebuild/test/integ.report-group-delete-reports.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-codebuild/test/integ.report-group-delete-reports.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-codebuild/test/integ.report-group-delete-reports.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-codebuild/test/integ.report-group-delete-reports.ts
  packages/aws-cdk-lib/aws-codebuild/README.md
  packages/aws-cdk-lib/aws-codebuild/lib/report-group.ts
  packages/aws-cdk-lib/aws-codebuild/test/report-group.test.ts
Labels: p2, beginning-contributor

#30323 chore(merge-back): 2.143.0
  CHANGELOG.v2.alpha.md
  CHANGELOG.v2.md
  packages/aws-cdk-lib/cx-api/FEATURE_FLAGS.md
  packages/aws-cdk-lib/cx-api/lib/features.ts
  version.v2.json
Labels: p2, pr/needs-community-review, pr/no-squash, auto-approve

#30306 chore(rds): add default engine version for aurora mysql version "3.04.2"
  packages/aws-cdk-lib/aws-rds/lib/cluster-engine.ts
Labels: p2, feature-request, effort/small, beginning-contributor, pr/needs-maintainer-review

#30316 docs(rds): improve docs about serverless v1
  packages/aws-cdk-lib/aws-rds/README.md
  packages/aws-cdk-lib/aws-rds/lib/serverless-cluster.ts
Labels: bug, p2, effort/small, valued-contributor

#30086 feat(ivs-alpha): support advanced channel type
  packages/@aws-cdk/aws-ivs-alpha/README.md
  packages/@aws-cdk/aws-ivs-alpha/lib/channel.ts
  packages/@aws-cdk/aws-ivs-alpha/test/integ.ivs-channel-advanced.js.snapshot/asset.cfdb46b4f2c6702b4a1cc8e23ca426e8de43d13567e73a8453d01c1176393814.bundle/index.js
  packages/@aws-cdk/aws-ivs-alpha/test/integ.ivs-channel-advanced.js.snapshot/aws-cdk-ivs.assets.json
  packages/@aws-cdk/aws-ivs-alpha/test/integ.ivs-channel-advanced.js.snapshot/aws-cdk-ivs.template.json
  packages/@aws-cdk/aws-ivs-alpha/test/integ.ivs-channel-advanced.js.snapshot/cdk.out
  packages/@aws-cdk/aws-ivs-alpha/test/integ.ivs-channel-advanced.js.snapshot/integ.json
  packages/@aws-cdk/aws-ivs-alpha/test/integ.ivs-channel-advanced.js.snapshot/ivstestDefaultTestDeployAssertDCE80D47.assets.json
  packages/@aws-cdk/aws-ivs-alpha/test/integ.ivs-channel-advanced.js.snapshot/ivstestDefaultTestDeployAssertDCE80D47.template.json
  packages/@aws-cdk/aws-ivs-alpha/test/integ.ivs-channel-advanced.js.snapshot/manifest.json
  packages/@aws-cdk/aws-ivs-alpha/test/integ.ivs-channel-advanced.js.snapshot/tree.json
  packages/@aws-cdk/aws-ivs-alpha/test/integ.ivs-channel-advanced.ts
  packages/@aws-cdk/aws-ivs-alpha/test/ivs.test.ts
Labels: p2, feature-request, effort/small, beginning-contributor

#30160 feat(ec2): support `instanceInitiatedShutdownBehavior` for EC2 instance
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.instance.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.instance.js.snapshot/instancetestDefaultTestDeployAssert5516EAF1.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.instance.js.snapshot/integ-ec2-instance.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.instance.js.snapshot/integ-ec2-instance.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.instance.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.instance.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.instance.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.instance.ts
  packages/aws-cdk-lib/aws-ec2/README.md
  packages/aws-cdk-lib/aws-ec2/lib/instance.ts
  packages/aws-cdk-lib/aws-ec2/test/instance.test.ts
Labels: p2, feature-request, star-contributor, pr/needs-maintainer-review

#30354 feat: update L1 CloudFormation resource definitions
  packages/@aws-cdk/cloudformation-diff/package.json
  packages/@aws-cdk/integ-runner/package.json
  packages/aws-cdk-lib/package.json
  tools/@aws-cdk/spec2cdk/package.json
  yarn.lock
Labels: p2, dependencies, contribution/core, pr-linter/exempt-readme, pr-linter/exempt-test, auto-approve, pr-linter/exempt-integ-test

#30319 feat(stepfunctions-tasks): add workerType and numberOfWorkers to GlueStartJobRun class
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/glue/integ.start-job-run-worker.js.snapshot/AwsSfnIntegTestDefaultTestDeployAssert8F32A58A.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/glue/integ.start-job-run-worker.js.snapshot/AwsSfnIntegTestDefaultTestDeployAssert8F32A58A.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/glue/integ.start-job-run-worker.js.snapshot/asset.cfdb46b4f2c6702b4a1cc8e23ca426e8de43d13567e73a8453d01c1176393814.bundle/index.js
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/glue/integ.start-job-run-worker.js.snapshot/asset.d030bb7913ca422df69f29b2ea678ab4e5085bb3cbb17029e4b101d2dc4e3e0d.py
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/glue/integ.start-job-run-worker.js.snapshot/aws-stepfunctions-integ-worker.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/glue/integ.start-job-run-worker.js.snapshot/aws-stepfunctions-integ-worker.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/glue/integ.start-job-run-worker.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/glue/integ.start-job-run-worker.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/glue/integ.start-job-run-worker.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/glue/integ.start-job-run-worker.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/glue/integ.start-job-run-worker.ts
  packages/aws-cdk-lib/aws-stepfunctions-tasks/README.md
  packages/aws-cdk-lib/aws-stepfunctions-tasks/lib/glue/start-job-run.ts
  packages/aws-cdk-lib/aws-stepfunctions-tasks/test/glue/start-job-run.test.ts
Labels: p1, feature-request, effort/small, valued-contributor

#30324 chore(bedrock): support missing model versions in Amazon Bedrock model
  packages/aws-cdk-lib/aws-bedrock/lib/foundation-model.ts
Labels: p2, beginning-contributor

#30342 fix(fsx): no validation error when `hour` property set to 24 in the `LustreMaintenanceTime` class.
  packages/@aws-cdk-testing/framework-integ/test/aws-fsx/test/integ.lustre-file-system-maintenance-time.js.snapshot/AwsCdkFsxLustreMaintenanceTime.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-fsx/test/integ.lustre-file-system-maintenance-time.js.snapshot/AwsCdkFsxLustreMaintenanceTime.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-fsx/test/integ.lustre-file-system-maintenance-time.js.snapshot/FsxLustreMaintenanceTimeDefaultTestDeployAssert402BBFE3.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-fsx/test/integ.lustre-file-system-maintenance-time.js.snapshot/FsxLustreMaintenanceTimeDefaultTestDeployAssert402BBFE3.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-fsx/test/integ.lustre-file-system-maintenance-time.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-fsx/test/integ.lustre-file-system-maintenance-time.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-fsx/test/integ.lustre-file-system-maintenance-time.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-fsx/test/integ.lustre-file-system-maintenance-time.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-fsx/test/integ.lustre-file-system-maintenance-time.ts
  packages/aws-cdk-lib/aws-fsx/lib/maintenance-time.ts
  packages/aws-cdk-lib/aws-fsx/test/maintenance-time.test.ts
Labels: bug, p2, valued-contributor

#30092 feat(neptune): add copyTagsToSnapshot property to the DatabaseCluster Construct
  packages/@aws-cdk/aws-neptune-alpha/README.md
  packages/@aws-cdk/aws-neptune-alpha/lib/cluster.ts
  packages/@aws-cdk/aws-neptune-alpha/test/cluster.test.ts
  packages/@aws-cdk/aws-neptune-alpha/test/integ.cluster-copy-tags-to-snapshot.js.snapshot/ClusterTestDefaultTestDeployAssert6A1BBA9D.assets.json
  packages/@aws-cdk/aws-neptune-alpha/test/integ.cluster-copy-tags-to-snapshot.js.snapshot/ClusterTestDefaultTestDeployAssert6A1BBA9D.template.json
  packages/@aws-cdk/aws-neptune-alpha/test/integ.cluster-copy-tags-to-snapshot.js.snapshot/aws-cdk-neptune-integ-copy-tags-to-snapshot.assets.json
  packages/@aws-cdk/aws-neptune-alpha/test/integ.cluster-copy-tags-to-snapshot.js.snapshot/aws-cdk-neptune-integ-copy-tags-to-snapshot.template.json
  packages/@aws-cdk/aws-neptune-alpha/test/integ.cluster-copy-tags-to-snapshot.js.snapshot/cdk.out
  packages/@aws-cdk/aws-neptune-alpha/test/integ.cluster-copy-tags-to-snapshot.js.snapshot/integ.json
  packages/@aws-cdk/aws-neptune-alpha/test/integ.cluster-copy-tags-to-snapshot.js.snapshot/manifest.json
  packages/@aws-cdk/aws-neptune-alpha/test/integ.cluster-copy-tags-to-snapshot.js.snapshot/tree.json
  packages/@aws-cdk/aws-neptune-alpha/test/integ.cluster-copy-tags-to-snapshot.ts
Labels: p2, feature-request, beginning-contributor

#30357 feat(ecs-patterns): allow custom container name for Scheduled ecs and fargate tasks
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs-patterns/test/ec2/integ.scheduled-ecs-task.js.snapshot/aws-ecs-integ-ecs.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs-patterns/test/ec2/integ.scheduled-ecs-task.js.snapshot/aws-ecs-integ-ecs.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs-patterns/test/ec2/integ.scheduled-ecs-task.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs-patterns/test/ec2/integ.scheduled-ecs-task.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs-patterns/test/ec2/integ.scheduled-ecs-task.ts
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs-patterns/test/fargate/integ.scheduled-fargate-task.js.snapshot/aws-fargate-integ.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs-patterns/test/fargate/integ.scheduled-fargate-task.js.snapshot/aws-fargate-integ.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs-patterns/test/fargate/integ.scheduled-fargate-task.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs-patterns/test/fargate/integ.scheduled-fargate-task.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs-patterns/test/fargate/integ.scheduled-fargate-task.ts
  packages/aws-cdk-lib/aws-ecs-patterns/README.md
  packages/aws-cdk-lib/aws-ecs-patterns/lib/base/scheduled-task-base.ts
  packages/aws-cdk-lib/aws-ecs-patterns/lib/ecs/scheduled-ecs-task.ts
  packages/aws-cdk-lib/aws-ecs-patterns/lib/fargate/scheduled-fargate-task.ts
  packages/aws-cdk-lib/aws-ecs-patterns/test/ec2/scheduled-ecs-task.test.ts
  packages/aws-cdk-lib/aws-ecs-patterns/test/fargate/scheduled-fargate-task.test.ts
Labels: p2, feature-request, effort/medium, contribution/core, pr/needs-maintainer-review

#30332 refactor(diff): make dedicated file and class for incorporating changeset to templateDiff
  packages/@aws-cdk/cloudformation-diff/lib/diff-template.ts
  packages/@aws-cdk/cloudformation-diff/lib/diff/template-and-changeset-diff-merger.ts
  packages/@aws-cdk/cloudformation-diff/lib/diff/types.ts
  packages/@aws-cdk/cloudformation-diff/lib/format.ts
  packages/@aws-cdk/cloudformation-diff/test/diff-template.test.ts
  packages/@aws-cdk/cloudformation-diff/test/format.test.ts
  packages/@aws-cdk/cloudformation-diff/test/template-and-changeset-diff-merger.test.ts
  packages/@aws-cdk/cloudformation-diff/test/util.ts
Labels: p2, contribution/core

#29632 fix(s3): publicReadAccess causes deployment failure due to access denied 403
  packages/@aws-cdk-testing/framework-integ/test/aws-cloudfront/test/integ.cloudfront-custom-s3.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-cloudfront/test/integ.cloudfront-custom-s3.js.snapshot/cloudfront-custom-s3-stack.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-cloudfront/test/integ.cloudfront-custom-s3.js.snapshot/cloudfront-custom-s3-stack.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-cloudfront/test/integ.cloudfront-custom-s3.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-cloudfront/test/integ.cloudfront-custom-s3.js.snapshot/integcloudfrontcustoms3DefaultTestDeployAssert2E08B1DA.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-cloudfront/test/integ.cloudfront-custom-s3.js.snapshot/integcloudfrontcustoms3DefaultTestDeployAssert2E08B1DA.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-cloudfront/test/integ.cloudfront-custom-s3.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-cloudfront/test/integ.cloudfront-custom-s3.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-cloudfront/test/integ.cloudfront-custom-s3.ts
  packages/aws-cdk-lib/aws-s3/README.md
  packages/aws-cdk-lib/aws-s3/lib/bucket.ts
  packages/aws-cdk-lib/aws-s3/test/bucket.test.ts
Labels: bug, p1, effort/medium, contribution/core

#30180 feat(appconfig): add grantReadConfig method to Environment Construct
  packages/@aws-cdk-testing/framework-integ/test/aws-appconfig/test/integ.environment-grant.js.snapshot/appconfigenvironmentDefaultTestDeployAssert75BD28E7.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-appconfig/test/integ.environment-grant.js.snapshot/appconfigenvironmentDefaultTestDeployAssert75BD28E7.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-appconfig/test/integ.environment-grant.js.snapshot/aws-appconfig-environment-grant.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-appconfig/test/integ.environment-grant.js.snapshot/aws-appconfig-environment-grant.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-appconfig/test/integ.environment-grant.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-appconfig/test/integ.environment-grant.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-appconfig/test/integ.environment-grant.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-appconfig/test/integ.environment-grant.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-appconfig/test/integ.environment-grant.ts
  packages/aws-cdk-lib/aws-appconfig/README.md
  packages/aws-cdk-lib/aws-appconfig/lib/environment.ts
  packages/aws-cdk-lib/aws-appconfig/test/environment.test.ts
Labels: p2, feature-request, effort/medium, repeat-contributor

#30367 chore(ecs): incorrect formatting of throw statement in the fromServiceArnWithCluster method
  packages/aws-cdk-lib/aws-ecs/lib/base/base-service.ts
Labels: p2, admired-contributor

#30246 chore(ec2): eventbridge pipes `pipes-data` vpc endpoint
  packages/aws-cdk-lib/aws-ec2/lib/vpc-endpoint.ts
Labels: p2, feature-request, effort/small, beginning-contributor

#30251 feat(dynamodb): add resource polices for table
  packages/@aws-cdk-testing/framework-integ/test/aws-dynamodb/test/integ.dynamodb-v2.policy.js.snapshot/ResourcePolicyTest-v2.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-dynamodb/test/integ.dynamodb-v2.policy.js.snapshot/ResourcePolicyTest-v2.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-dynamodb/test/integ.dynamodb-v2.policy.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-dynamodb/test/integ.dynamodb-v2.policy.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-dynamodb/test/integ.dynamodb-v2.policy.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-dynamodb/test/integ.dynamodb-v2.policy.js.snapshot/tablev2resourcepolicyintegtestDefaultTestDeployAssertBE3353C7.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-dynamodb/test/integ.dynamodb-v2.policy.js.snapshot/tablev2resourcepolicyintegtestDefaultTestDeployAssertBE3353C7.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-dynamodb/test/integ.dynamodb-v2.policy.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-dynamodb/test/integ.dynamodb-v2.policy.ts
  packages/@aws-cdk-testing/framework-integ/test/aws-dynamodb/test/integ.dynamodb.policy.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-dynamodb/test/integ.dynamodb.policy.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-dynamodb/test/integ.dynamodb.policy.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-dynamodb/test/integ.dynamodb.policy.js.snapshot/resource-policy-stack.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-dynamodb/test/integ.dynamodb.policy.js.snapshot/resource-policy-stack.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-dynamodb/test/integ.dynamodb.policy.js.snapshot/resourcepolicyintegtestDefaultTestDeployAssert9778837B.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-dynamodb/test/integ.dynamodb.policy.js.snapshot/resourcepolicyintegtestDefaultTestDeployAssert9778837B.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-dynamodb/test/integ.dynamodb.policy.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-dynamodb/test/integ.dynamodb.policy.ts
  packages/aws-cdk-lib/aws-dynamodb/README.md
  packages/aws-cdk-lib/aws-dynamodb/TABLE_V1_API.md
  packages/aws-cdk-lib/aws-dynamodb/lib/table-v2-base.ts
  packages/aws-cdk-lib/aws-dynamodb/lib/table-v2.ts
  packages/aws-cdk-lib/aws-dynamodb/lib/table.ts
  packages/aws-cdk-lib/aws-dynamodb/test/dynamodb.test.ts
  packages/aws-cdk-lib/aws-dynamodb/test/table-v2.test.ts
Labels: p2, feature-request, pr/needs-community-review, effort/medium, beginning-contributor

#29904 fix(lambda): use enum values for applicationLogLevel and systemLogLevel
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda/test/integ.logging-config.js.snapshot/aws-cdk-lambda-logging-config.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda/test/integ.logging-config.js.snapshot/aws-cdk-lambda-logging-config.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda/test/integ.logging-config.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda/test/integ.logging-config.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda/test/integ.logging-config.ts
  packages/aws-cdk-lib/aws-lambda/README.md
  packages/aws-cdk-lib/aws-lambda/lib/function.ts
  packages/aws-cdk-lib/aws-lambda/test/logging-config.test.ts
Labels: p2, beginning-contributor

#30375 revert: "fix(ses-actions): permissions too wide for S3 action"
  packages/@aws-cdk-testing/framework-integ/test/aws-ses-actions/test/integ.actions.js.snapshot/aws-cdk-ses-receipt.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ses-actions/test/integ.actions.js.snapshot/aws-cdk-ses-receipt.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ses-actions/test/integ.actions.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ses-actions/test/integ.actions.js.snapshot/tree.json
  packages/aws-cdk-lib/aws-ses-actions/lib/s3.ts
  packages/aws-cdk-lib/aws-ses-actions/test/actions.test.ts
  packages/aws-cdk-lib/aws-ses/lib/receipt-rule-action.ts
  packages/aws-cdk-lib/aws-ses/lib/receipt-rule.ts
Labels: p2, contribution/core, pr-linter/exempt-readme, pr-linter/exempt-integ-test

#30377 chore(release): v2.143.1
  CHANGELOG.v2.alpha.md
  CHANGELOG.v2.md
  packages/@aws-cdk-testing/framework-integ/test/aws-ses-actions/test/integ.actions.js.snapshot/aws-cdk-ses-receipt.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ses-actions/test/integ.actions.js.snapshot/aws-cdk-ses-receipt.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ses-actions/test/integ.actions.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ses-actions/test/integ.actions.js.snapshot/tree.json
  packages/aws-cdk-lib/aws-ses-actions/lib/s3.ts
  packages/aws-cdk-lib/aws-ses-actions/test/actions.test.ts
  packages/aws-cdk-lib/aws-ses/lib/receipt-rule-action.ts
  packages/aws-cdk-lib/aws-ses/lib/receipt-rule.ts
  version.v2.json
Labels: p2, contribution/core, pr/no-squash

#30380 chore(merge-back): 2.143.1
  CHANGELOG.v2.alpha.md
  CHANGELOG.v2.md
  version.v2.json
Labels: p2, pr/needs-community-review, pr/no-squash, auto-approve

#30382 fix(ecs): removed omitEmptyArray for placementConstraints (#27555)
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs/test/ec2/integ.placement-constraint-default-empty.js.snapshot/IntegDefaultTestDeployAssert4E6713E1.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs/test/ec2/integ.placement-constraint-default-empty.js.snapshot/IntegDefaultTestDeployAssert4E6713E1.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs/test/ec2/integ.placement-constraint-default-empty.js.snapshot/aws-cdk-ecs-integ-test-with-empty-placement-constraint-stack.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs/test/ec2/integ.placement-constraint-default-empty.js.snapshot/aws-cdk-ecs-integ-test-with-empty-placement-constraint-stack.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs/test/ec2/integ.placement-constraint-default-empty.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs/test/ec2/integ.placement-constraint-default-empty.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs/test/ec2/integ.placement-constraint-default-empty.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs/test/ec2/integ.placement-constraint-default-empty.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs/test/ec2/integ.placement-constraint-default-empty.ts
  packages/aws-cdk-lib/aws-ecs/lib/ec2/ec2-service.ts
  packages/aws-cdk-lib/aws-ecs/test/ec2/ec2-service.test.ts
Labels: bug, p1, beginning-contributor, pr/needs-maintainer-review

#30210 fix(stepfunctions): cannot use intrinsic functions in Fail state
  packages/aws-cdk-lib/aws-stepfunctions/README.md
  packages/aws-cdk-lib/aws-stepfunctions/lib/states/fail.ts
  packages/aws-cdk-lib/aws-stepfunctions/test/state-machine-resources.test.ts
Labels: bug, p1, effort/small, pr-linter/exempt-integ-test, star-contributor

#30393 chore: only use 50% of workers for jest
  tools/@aws-cdk/cdk-build-tools/config/jest.config.js
Labels: p2, contribution/core, pr/needs-maintainer-review

#30387 docs(apigatewayv2-integrations): add `StepFunctions Integration` to table of contents
  packages/aws-cdk-lib/aws-apigatewayv2-integrations/README.md
Labels: p2, star-contributor

#30196 feat(lambda): allow running a build file
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-nodejs/test/integ-handlers/custom_command_input/build.sh
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-nodejs/test/integ-handlers/custom_command_input/custom_command_handler.ts
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-nodejs/test/integ-handlers/custom_command_output/README.md
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-nodejs/test/integ.specifycode.js.snapshot/LambdaNodeJsCodeSpecifiedDefaultTestDeployAssertD50C7B96.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-nodejs/test/integ.specifycode.js.snapshot/LambdaNodeJsCodeSpecifiedDefaultTestDeployAssertD50C7B96.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-nodejs/test/integ.specifycode.js.snapshot/asset.65c9f57ca55e2d458059a930e997f2bc96560b3a3654cc442616d12089449d39.bundle/index.js
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-nodejs/test/integ.specifycode.js.snapshot/asset.c12bcea99402579807f652afcfc96ca3da8544cdb4d02ba9cad57e2cca16c5ea/README.md
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-nodejs/test/integ.specifycode.js.snapshot/asset.c12bcea99402579807f652afcfc96ca3da8544cdb4d02ba9cad57e2cca16c5ea/mylambdafile.js
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-nodejs/test/integ.specifycode.js.snapshot/cdk-integ-lambda-nodejs-codespecified.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-nodejs/test/integ.specifycode.js.snapshot/cdk-integ-lambda-nodejs-codespecified.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-nodejs/test/integ.specifycode.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-nodejs/test/integ.specifycode.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-nodejs/test/integ.specifycode.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-nodejs/test/integ.specifycode.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-nodejs/test/integ.specifycode.ts
  packages/aws-cdk-lib/aws-lambda-nodejs/README.md
  packages/aws-cdk-lib/aws-lambda-nodejs/lib/function.ts
  packages/aws-cdk-lib/aws-lambda-nodejs/test/function.test.ts
  packages/aws-cdk-lib/aws-lambda/README.md
  packages/aws-cdk-lib/aws-lambda/lib/code.ts
  packages/aws-cdk-lib/aws-lambda/test/code.test.ts
  packages/aws-cdk-lib/rosetta/aws_lambda_nodejs/default.ts-fixture
Labels: p1, feature-request, effort/large, contribution/core

#30253 docs(s3-deployment): update development section of readme
  packages/aws-cdk-lib/aws-s3-deployment/README.md
Labels: p2, beginning-contributor

#30410 chore(merge-back): 2.144.0
  CHANGELOG.v2.alpha.md
  CHANGELOG.v2.md
  version.v2.json
Labels: p2, pr/needs-community-review, pr/no-squash, auto-approve
