Repository aws/aws-cdk, pull requests merged in 2024-07, with the labels that each got.

#30713 chore: update Contributors File
  CONTRIBUTORS.md
Labels: p2, auto-approve

#30730 chore(merge-back): 2.147.3
  CHANGELOG.v2.alpha.md
  CHANGELOG.v2.md
  version.v2.json
Labels: p2, pr/no-squash, auto-approve

#29856 feat(lambda): add grantInvokeLatestVersion to grant invoke only to latest function version
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda/test/integ.permissions.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda/test/integ.permissions.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda/test/integ.permissions.js.snapshot/lambda-permissions.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda/test/integ.permissions.js.snapshot/lambda-permissions.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda/test/integ.permissions.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda/test/integ.permissions.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda/test/integ.permissions.ts
  packages/aws-cdk-lib/aws-cloudfront/lib/experimental/edge-function.ts
  packages/aws-cdk-lib/aws-lambda/README.md
  packages/aws-cdk-lib/aws-lambda/lib/function-base.ts
  packages/aws-cdk-lib/aws-lambda/test/function.test.ts
Labels: p1, feature-request, effort/small, repeat-contributor

#30744 chore: npm-check-updates && yarn upgrade
  package.json
  packages/@aws-cdk-testing/cli-integ/package.json
  packages/@aws-cdk-testing/framework-integ/package.json
  packages/@aws-cdk/custom-resource-handlers/package.json
  packages/aws-cdk-lib/package.json
  packages/aws-cdk/THIRD_PARTY_LICENSES
  packages/aws-cdk/lib/init-templates/app/typescript/package.json
  packages/aws-cdk/lib/init-templates/lib/typescript/package.json
  packages/aws-cdk/lib/init-templates/sample-app/typescript/package.json
  packages/aws-cdk/package.json
  packages/cdk-assets/package.json
  tools/@aws-cdk/cdk-build-tools/package.json
  tools/@aws-cdk/lazify/package.json
  tools/@aws-cdk/node-bundle/package.json
  yarn.lock
Labels: p2, dependencies, contribution/core, auto-approve

#30755 chore: update codepipipeline action test for ebs
  packages/@aws-cdk-testing/framework-integ/test/aws-codepipeline-actions/test/integ.pipeline-elastic-beanstalk-deploy.js.snapshot/aws-cdk-codepipeline-elastic-beanstalk-deploy.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-codepipeline-actions/test/integ.pipeline-elastic-beanstalk-deploy.js.snapshot/aws-cdk-codepipeline-elastic-beanstalk-deploy.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-codepipeline-actions/test/integ.pipeline-elastic-beanstalk-deploy.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-codepipeline-actions/test/integ.pipeline-elastic-beanstalk-deploy.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-codepipeline-actions/test/integ.pipeline-elastic-beanstalk-deploy.ts
Labels: p2, contribution/core

#30426 feat(stepfunctions-tasks): add guardrailConfiguration and trace property to the BedrockInvokeModel
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/bedrock/integ.invoke-model-guardrail-trace.js.snapshot/InvokeModelDefaultTestDeployAssert9C0D2DFC.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/bedrock/integ.invoke-model-guardrail-trace.js.snapshot/InvokeModelDefaultTestDeployAssert9C0D2DFC.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/bedrock/integ.invoke-model-guardrail-trace.js.snapshot/asset.3cef2cdbb46b3821e641ffb8b9af9731af5f7e4a9e857ab633dbcd9023de724d.bundle/index.js
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/bedrock/integ.invoke-model-guardrail-trace.js.snapshot/aws-stepfunctions-tasks-bedrock-invoke-model-guardrail-trace-integ.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/bedrock/integ.invoke-model-guardrail-trace.js.snapshot/aws-stepfunctions-tasks-bedrock-invoke-model-guardrail-trace-integ.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/bedrock/integ.invoke-model-guardrail-trace.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/bedrock/integ.invoke-model-guardrail-trace.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/bedrock/integ.invoke-model-guardrail-trace.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/bedrock/integ.invoke-model-guardrail-trace.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/bedrock/integ.invoke-model-guardrail-trace.ts
  packages/aws-cdk-lib/aws-stepfunctions-tasks/README.md
  packages/aws-cdk-lib/aws-stepfunctions-tasks/lib/bedrock/guardrail.ts
  packages/aws-cdk-lib/aws-stepfunctions-tasks/lib/bedrock/invoke-model.ts
  packages/aws-cdk-lib/aws-stepfunctions-tasks/lib/index.ts
  packages/aws-cdk-lib/aws-stepfunctions-tasks/test/bedrock/invoke-model.test.ts
Labels: p2, feature-request, admired-contributor, pr/needs-maintainer-review

#30766 chore(merge-back): 2.148.0
  CHANGELOG.v2.alpha.md
  CHANGELOG.v2.md
  packages/aws-cdk-lib/cx-api/FEATURE_FLAGS.md
  packages/aws-cdk-lib/cx-api/lib/features.ts
  version.v2.json
Labels: p2, pr/needs-community-review, pr/no-squash, auto-approve

#30786 feat: update L1 CloudFormation resource definitions
  packages/@aws-cdk/cloudformation-diff/package.json
  packages/@aws-cdk/integ-runner/package.json
  packages/aws-cdk-lib/package.json
  tools/@aws-cdk/spec2cdk/package.json
  yarn.lock
Labels: p2, dependencies, contribution/core, pr-linter/exempt-readme, pr-linter/exempt-test, auto-approve, pr-linter/exempt-integ-test

#30429 feat(codedeploy): zonal configuration for `ServerDeploymentConfig`
  packages/@aws-cdk-testing/framework-integ/test/aws-codedeploy/test/server/integ.deployment-group-zonal-config.js.snapshot/ServerDeploymentGroupZonalConfigDefaultTestDeployAssertEA00EA72.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-codedeploy/test/server/integ.deployment-group-zonal-config.js.snapshot/ServerDeploymentGroupZonalConfigDefaultTestDeployAssertEA00EA72.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-codedeploy/test/server/integ.deployment-group-zonal-config.js.snapshot/Stack.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-codedeploy/test/server/integ.deployment-group-zonal-config.js.snapshot/Stack.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-codedeploy/test/server/integ.deployment-group-zonal-config.js.snapshot/asset.bde7b5c89cb43285f884c94f0b9e17cdb0f5eb5345005114dd60342e0b8a85a1/__entrypoint__.js
  packages/@aws-cdk-testing/framework-integ/test/aws-codedeploy/test/server/integ.deployment-group-zonal-config.js.snapshot/asset.bde7b5c89cb43285f884c94f0b9e17cdb0f5eb5345005114dd60342e0b8a85a1/index.js
  packages/@aws-cdk-testing/framework-integ/test/aws-codedeploy/test/server/integ.deployment-group-zonal-config.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-codedeploy/test/server/integ.deployment-group-zonal-config.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-codedeploy/test/server/integ.deployment-group-zonal-config.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-codedeploy/test/server/integ.deployment-group-zonal-config.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-codedeploy/test/server/integ.deployment-group-zonal-config.ts
  packages/aws-cdk-lib/aws-codedeploy/README.md
  packages/aws-cdk-lib/aws-codedeploy/lib/base-deployment-config.ts
  packages/aws-cdk-lib/aws-codedeploy/lib/host-health-config.ts
  packages/aws-cdk-lib/aws-codedeploy/lib/server/deployment-config.ts
  packages/aws-cdk-lib/aws-codedeploy/test/server/deployment-config.test.ts
Labels: p2, feature-request, distinguished-contributor

#30447 feat(stepfunctions-tasks): enable resultReuseConfiguration in AthenaStartQueryExecution
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/athena/integ.start-query-execution-result-reuse-configuration.js.snapshot/AthenaResultReuseConfigurationDefaultTestDeployAssert59574A02.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/athena/integ.start-query-execution-result-reuse-configuration.js.snapshot/AthenaResultReuseConfigurationDefaultTestDeployAssert59574A02.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/athena/integ.start-query-execution-result-reuse-configuration.js.snapshot/asset.3cef2cdbb46b3821e641ffb8b9af9731af5f7e4a9e857ab633dbcd9023de724d.bundle/index.js
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/athena/integ.start-query-execution-result-reuse-configuration.js.snapshot/asset.44e9c4d7a5d3fd2d677e1a7e416b2b56f6b0104bd5eff9cac5557b4c65a9dc61/index.js
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/athena/integ.start-query-execution-result-reuse-configuration.js.snapshot/aws-stepfunctions-tasks-athena-start-query-execution-result-reuse-configuration-integ.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/athena/integ.start-query-execution-result-reuse-configuration.js.snapshot/aws-stepfunctions-tasks-athena-start-query-execution-result-reuse-configuration-integ.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/athena/integ.start-query-execution-result-reuse-configuration.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/athena/integ.start-query-execution-result-reuse-configuration.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/athena/integ.start-query-execution-result-reuse-configuration.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/athena/integ.start-query-execution-result-reuse-configuration.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/athena/integ.start-query-execution-result-reuse-configuration.ts
  packages/aws-cdk-lib/aws-stepfunctions-tasks/README.md
  packages/aws-cdk-lib/aws-stepfunctions-tasks/lib/athena/start-query-execution.ts
  packages/aws-cdk-lib/aws-stepfunctions-tasks/test/athena/start-query-execution.test.ts
Labels: p2, feature-request, admired-contributor

#30789 chore(doc): fix a broken link in the README.md
  packages/aws-cdk-lib/core/README.md
Labels: p2, contribution/core, pr/needs-maintainer-review

#30785 docs(events): improved maintenance of information on supported targets
  packages/aws-cdk-lib/aws-events/README.md
Labels: p2, star-contributor

#30780 feat(codestarnotifications): add `createdBy` property for notification rule
  packages/@aws-cdk-testing/framework-integ/test/aws-codepipeline-actions/test/integ.pipeline-with-codestarnotifications.js.snapshot/asset.44e9c4d7a5d3fd2d677e1a7e416b2b56f6b0104bd5eff9cac5557b4c65a9dc61/index.js
  packages/@aws-cdk-testing/framework-integ/test/aws-codepipeline-actions/test/integ.pipeline-with-codestarnotifications.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-codepipeline-actions/test/integ.pipeline-with-codestarnotifications.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-codepipeline-actions/test/integ.pipeline-with-codestarnotifications.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-codepipeline-actions/test/integ.pipeline-with-codestarnotifications.js.snapshot/pipeline-with-codestarnotifications.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-codepipeline-actions/test/integ.pipeline-with-codestarnotifications.js.snapshot/pipeline-with-codestarnotifications.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-codepipeline-actions/test/integ.pipeline-with-codestarnotifications.js.snapshot/pipelinewithcodestarnotificationstestDefaultTestDeployAssertDA0A4181.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-codepipeline-actions/test/integ.pipeline-with-codestarnotifications.js.snapshot/pipelinewithcodestarnotificationstestDefaultTestDeployAssertDA0A4181.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-codepipeline-actions/test/integ.pipeline-with-codestarnotifications.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-codepipeline-actions/test/integ.pipeline-with-codestarnotifications.ts
  packages/aws-cdk-lib/aws-codestarnotifications/README.md
  packages/aws-cdk-lib/aws-codestarnotifications/lib/notification-rule.ts
  packages/aws-cdk-lib/aws-codestarnotifications/test/notification-rule.test.ts
Labels: p2, beginning-contributor, pr-linter/exemption-requested

#30803 chore(ec2): add R8g instance type
  packages/aws-cdk-lib/aws-ec2/lib/instance-types.ts
Labels: p2, distinguished-contributor

#30634 fix(scheduler-targetes-alpha): multiple schedules cause resolution error during synth
  packages/@aws-cdk/aws-scheduler-targets-alpha/lib/target.ts
  packages/@aws-cdk/aws-scheduler-targets-alpha/test/codebuild-start-build.test.ts
  packages/@aws-cdk/aws-scheduler-targets-alpha/test/codepipeline-start-pipeline-execution.test.ts
  packages/@aws-cdk/aws-scheduler-targets-alpha/test/event-bridge-put-events.test.ts
  packages/@aws-cdk/aws-scheduler-targets-alpha/test/inspector-start-assessment-run.test.ts
  packages/@aws-cdk/aws-scheduler-targets-alpha/test/integ.lambda-invoke.js.snapshot/asset.eafc02f6925151c95ac6a6ae81a3e36d4cf4e77db52eec8e467ce2a69454a41a.bundle/index.js
  packages/@aws-cdk/aws-scheduler-targets-alpha/test/integ.lambda-invoke.js.snapshot/aws-cdk-schedule.assets.json
  packages/@aws-cdk/aws-scheduler-targets-alpha/test/integ.lambda-invoke.js.snapshot/aws-cdk-schedule.template.json
  packages/@aws-cdk/aws-scheduler-targets-alpha/test/integ.lambda-invoke.js.snapshot/cdk.out
  packages/@aws-cdk/aws-scheduler-targets-alpha/test/integ.lambda-invoke.js.snapshot/integ.json
  packages/@aws-cdk/aws-scheduler-targets-alpha/test/integ.lambda-invoke.js.snapshot/integtestlambdainvokeDefaultTestDeployAssertEC6565E6.assets.json
  packages/@aws-cdk/aws-scheduler-targets-alpha/test/integ.lambda-invoke.js.snapshot/integtestlambdainvokeDefaultTestDeployAssertEC6565E6.template.json
  packages/@aws-cdk/aws-scheduler-targets-alpha/test/integ.lambda-invoke.js.snapshot/manifest.json
  packages/@aws-cdk/aws-scheduler-targets-alpha/test/integ.lambda-invoke.js.snapshot/tree.json
  packages/@aws-cdk/aws-scheduler-targets-alpha/test/integ.lambda-invoke.ts
  packages/@aws-cdk/aws-scheduler-targets-alpha/test/kinesis-data-firehose-put-record.test.ts
  packages/@aws-cdk/aws-scheduler-targets-alpha/test/kinesis-stream-put-record.test.ts
  packages/@aws-cdk/aws-scheduler-targets-alpha/test/lambda-invoke.test.ts
  packages/@aws-cdk/aws-scheduler-targets-alpha/test/sage-maker-start-pipeline-execution.test.ts
  packages/@aws-cdk/aws-scheduler-targets-alpha/test/sns-publish.test.ts
  packages/@aws-cdk/aws-scheduler-targets-alpha/test/sqs-send-message.test.ts
  packages/@aws-cdk/aws-scheduler-targets-alpha/test/stepfunction-start-execution.test.ts
Labels: p2, valued-contributor

#30822 fix(apigateway): authorization scope is not added when not explicitly defining authorization type in method or root api
  packages/@aws-cdk-testing/framework-integ/test/aws-apigateway/test/authorizers/integ.api-with-authorizer-and-method.js.snapshot/apigatewaywithauthorizerandproxyDefaultTestDeployAssertDBEA1774.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-apigateway/test/authorizers/integ.api-with-authorizer-and-method.js.snapshot/apigatewaywithauthorizerandproxyDefaultTestDeployAssertDBEA1774.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-apigateway/test/authorizers/integ.api-with-authorizer-and-method.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-apigateway/test/authorizers/integ.api-with-authorizer-and-method.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-apigateway/test/authorizers/integ.api-with-authorizer-and-method.js.snapshot/integtest-restapi-with-authorizer-and-proxy.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-apigateway/test/authorizers/integ.api-with-authorizer-and-method.js.snapshot/integtest-restapi-with-authorizer-and-proxy.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-apigateway/test/authorizers/integ.api-with-authorizer-and-method.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-apigateway/test/authorizers/integ.api-with-authorizer-and-method.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-apigateway/test/authorizers/integ.api-with-authorizer-and-method.ts
  packages/@aws-cdk-testing/framework-integ/test/aws-apigateway/test/authorizers/integ.api-with-authorizer-and-proxy.ts
  packages/aws-cdk-lib/aws-apigateway/lib/method.ts
  packages/aws-cdk-lib/aws-apigateway/test/method.test.ts
Labels: bug, p0, effort/small, pr/do-not-merge, contribution/core

#30824 chore(release): v2.148.1
  CHANGELOG.v2.alpha.md
  CHANGELOG.v2.md
  packages/@aws-cdk-testing/framework-integ/test/aws-apigateway/test/authorizers/integ.api-with-authorizer-and-method.js.snapshot/apigatewaywithauthorizerandproxyDefaultTestDeployAssertDBEA1774.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-apigateway/test/authorizers/integ.api-with-authorizer-and-method.js.snapshot/apigatewaywithauthorizerandproxyDefaultTestDeployAssertDBEA1774.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-apigateway/test/authorizers/integ.api-with-authorizer-and-method.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-apigateway/test/authorizers/integ.api-with-authorizer-and-method.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-apigateway/test/authorizers/integ.api-with-authorizer-and-method.js.snapshot/integtest-restapi-with-authorizer-and-proxy.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-apigateway/test/authorizers/integ.api-with-authorizer-and-method.js.snapshot/integtest-restapi-with-authorizer-and-proxy.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-apigateway/test/authorizers/integ.api-with-authorizer-and-method.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-apigateway/test/authorizers/integ.api-with-authorizer-and-method.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-apigateway/test/authorizers/integ.api-with-authorizer-and-method.ts
  packages/@aws-cdk-testing/framework-integ/test/aws-apigateway/test/authorizers/integ.api-with-authorizer-and-proxy.ts
  packages/aws-cdk-lib/aws-apigateway/lib/method.ts
  packages/aws-cdk-lib/aws-apigateway/test/method.test.ts
  version.v2.json
Labels: p2, contribution/core, pr/no-squash

#30825 chore(merge-back): 2.148.1
  CHANGELOG.v2.alpha.md
  CHANGELOG.v2.md
  version.v2.json
Labels: p2, pr/needs-community-review, pr/no-squash, auto-approve

#30823 chore: add condition to bootstrap file publish role
  packages/aws-cdk/lib/api/bootstrap/bootstrap-template.yaml
Labels: p2, contribution/core, pr-linter/cli-integ-tested

#30840 chore: fix typo in bucket error message
  packages/aws-cdk-lib/aws-s3/lib/bucket.ts
  packages/aws-cdk-lib/aws-s3/test/bucket.test.ts
Labels: p2, pr/needs-community-review, beginning-contributor

#30832 chore: remove use of deprecated ServicePrincipal Mapping
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/glue/integ.glue-task.js.snapshot/aws-stepfunctions-integ.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/glue/integ.start-job-run.js.snapshot/aws-stepfunctions-integ.template.json
  packages/@aws-cdk/aws-pipes-enrichments-alpha/test/__snapshots__/stepfunctions.test.ts.snap
  packages/@aws-cdk/aws-pipes-targets-alpha/test/__snapshots__/stepfunctions.test.ts.snap
  packages/@aws-cdk/cx-api/FEATURE_FLAGS.md
  packages/aws-cdk-lib/aws-codedeploy/test/ecs/deployment-group.test.ts
  packages/aws-cdk-lib/aws-codedeploy/test/lambda/deployment-group.test.ts
  packages/aws-cdk-lib/aws-ec2/lib/vpc-endpoint-service.ts
  packages/aws-cdk-lib/aws-iam/lib/principals.ts
  packages/aws-cdk-lib/aws-iam/test/policy-document.test.ts
  packages/aws-cdk-lib/aws-iam/test/principals.test.ts
  packages/aws-cdk-lib/aws-logs-destinations/test/kinesis.test.ts
  packages/aws-cdk-lib/custom-resources/test/provider-framework/waiter-state-machine.test.ts
  packages/aws-cdk-lib/cx-api/FEATURE_FLAGS.md
  packages/aws-cdk-lib/cx-api/lib/features.ts
  packages/aws-cdk-lib/region-info/README.md
  packages/aws-cdk-lib/region-info/build-tools/generate-static-data.ts
  packages/aws-cdk-lib/region-info/lib/aws-entities.ts
  packages/aws-cdk-lib/region-info/lib/default.ts
  packages/aws-cdk-lib/region-info/lib/fact.ts
  packages/aws-cdk-lib/region-info/lib/region-info.ts
  packages/aws-cdk-lib/region-info/test/__snapshots__/region-info.test.ts.snap
  packages/aws-cdk-lib/region-info/test/region-info.test.ts
  scripts/check-region-info-compatibility.ts
Labels: p2, contribution/core

#30847 chore(merge-back): 2.149.0
  CHANGELOG.v2.alpha.md
  CHANGELOG.v2.md
  version.v2.json
Labels: p2, pr/needs-community-review, pr/no-squash, auto-approve

#30842 chore(lambda): deprecate Node.js v16 runtime
  packages/aws-cdk-lib/aws-lambda/lib/runtime.ts
Labels: p2, star-contributor

#30860 feat: update L1 CloudFormation resource definitions
  packages/@aws-cdk/cloudformation-diff/package.json
  packages/@aws-cdk/integ-runner/package.json
  packages/aws-cdk-lib/package.json
  tools/@aws-cdk/spec2cdk/package.json
  yarn.lock
Labels: p2, dependencies, contribution/core, pr-linter/exempt-readme, pr-linter/exempt-test, auto-approve, pr-linter/exempt-integ-test

#30865 chore: update issue-label-assign.yml to add cli-lib-alpha
  .github/workflows/issue-label-assign.yml
Labels: p2

#30795 fix(stepfunctions-tasks): allow camelCase for parameters of CallAwsServiceCrossRegion
  packages/aws-cdk-lib/aws-stepfunctions-tasks/lib/lambda/call-aws-service-cross-region.ts
  packages/aws-cdk-lib/aws-stepfunctions-tasks/test/lambda/call-aws-service-cross-region.test.ts
Labels: bug, p1, effort/small, pr-linter/exempt-integ-test, star-contributor, pr-linter/exemption-requested, pr/needs-maintainer-review

#30864 chore(roadmap): update a link in community contribution call-outs
  ROADMAP.md
Labels: p2, pr/needs-community-review, distinguished-contributor

#30853 docs(synthetics): fix syn-nodejs-puppeteer 6.2 link
  packages/aws-cdk-lib/aws-synthetics/lib/runtime.ts
Labels: p2, star-contributor

#30852 docs(pipelines): fix link for originarl API document in README
  packages/aws-cdk-lib/pipelines/README.md
Labels: p2, star-contributor

#30867 docs: fix SnsAction typo for aws-cdk-lib aws_cloudwatch Alarm addAlarmAction
  packages/aws-cdk-lib/aws-cloudwatch/lib/alarm.ts
Labels: p2, beginning-contributor

#30815 docs(eks): add documentation about add-ons
  packages/aws-cdk-lib/aws-eks/README.md
Labels: p2, distinguished-contributor

#30873 chore: exemption requested PRs should not be marked as stale
  .github/workflows/close-stale-prs.yml
Labels: p2, contribution/core

#30693 feat(ec2): add g6 instance
  packages/aws-cdk-lib/aws-ec2/lib/instance-types.ts
  packages/aws-cdk-lib/aws-ec2/test/instance.test.ts
Labels: p2, feature-request, effort/small, pr-linter/exempt-readme, pr-linter/exempt-integ-test, beginning-contributor

#30851 chore(synthetics): add nodejs puppeteer 8 runtime
  packages/@aws-cdk-testing/framework-integ/test/aws-synthetics/test/integ.canary.js.snapshot/IntegCanaryTestDefaultTestDeployAssert3AD5A094.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-synthetics/test/integ.canary.js.snapshot/IntegCanaryTestDefaultTestDeployAssert3AD5A094.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-synthetics/test/integ.canary.js.snapshot/asset.3cef2cdbb46b3821e641ffb8b9af9731af5f7e4a9e857ab633dbcd9023de724d.bundle/index.js
  packages/@aws-cdk-testing/framework-integ/test/aws-synthetics/test/integ.canary.js.snapshot/canary-one.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-synthetics/test/integ.canary.js.snapshot/canary-one.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-synthetics/test/integ.canary.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-synthetics/test/integ.canary.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-synthetics/test/integ.canary.ts
  packages/aws-cdk-lib/aws-synthetics/lib/runtime.ts
  packages/aws-cdk-lib/aws-synthetics/test/canary.test.ts
Labels: p2, feature-request, star-contributor

#30887 chore: cleanup custom resource handler files
  packages/aws-cdk-lib/core/lib/custom-resource-provider/custom-resource-provider-base.ts
  packages/aws-cdk-lib/core/test/custom-resource-provider/custom-resource-provider.test.ts
Labels: p2, contribution/core

#30812 chore(lambda): update the fact tables and tests for lambda layers v0.102.1
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda/test/integ.lambda-adot.js.snapshot/Stack1.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda/test/integ.lambda-adot.js.snapshot/Stack1.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda/test/integ.lambda-adot.js.snapshot/Stack2.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda/test/integ.lambda-adot.js.snapshot/Stack2.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda/test/integ.lambda-adot.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda/test/integ.lambda-adot.js.snapshot/tree.json
  packages/aws-cdk-lib/aws-lambda/lib/adot-layers.ts
  packages/aws-cdk-lib/aws-lambda/test/adot.test.ts
  packages/aws-cdk-lib/aws-lambda/test/function.test.ts
  packages/aws-cdk-lib/region-info/build-tools/fact-tables.ts
Labels: p2, pr/needs-community-review, beginning-contributor

#30892 chore: run closed issue message on PRs
  .github/workflows/closed-issue-message.yml
Labels: p2, contribution/core

#30894 chore: issue and pull requests permissions
  .github/workflows/closed-issue-message.yml
Labels: p2, contribution/core

#30904 feat(logs): enabling IA log group creation in CN and GovCloud regions
  packages/aws-cdk-lib/aws-logs/README.md
  packages/aws-cdk-lib/aws-logs/lib/log-group.ts
Labels: p2, pr-linter/exempt-test, pr-linter/exempt-integ-test, beginning-contributor

#30898 feat(lambda): add SnapStart support for arm64 functions
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda/test/integ.lambda.js.snapshot/aws-cdk-lambda-1.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda/test/integ.lambda.js.snapshot/aws-cdk-lambda-1.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda/test/integ.lambda.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda/test/integ.lambda.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda/test/integ.lambda.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda/test/integ.lambda.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda/test/integ.lambda.ts
  packages/aws-cdk-lib/aws-lambda/README.md
  packages/aws-cdk-lib/aws-lambda/lib/function.ts
  packages/aws-cdk-lib/aws-lambda/test/function.test.ts
Labels: p2, feature-request, beginning-contributor

#30907 chore(ec2): make applyCloudFormationInit() function public
  packages/aws-cdk-lib/aws-ec2/lib/instance.ts
Labels: bug, p1, effort/small, contribution/core

#30921 feat: update L1 CloudFormation resource definitions
  packages/@aws-cdk/cloudformation-diff/package.json
  packages/@aws-cdk/integ-runner/package.json
  packages/aws-cdk-lib/package.json
  tools/@aws-cdk/spec2cdk/package.json
  yarn.lock
Labels: p2, dependencies, contribution/core, pr-linter/exempt-readme, pr-linter/exempt-test, auto-approve, pr-linter/exempt-integ-test

#30820 feat(apigatewayv2): add `description` property for stage
  packages/@aws-cdk-testing/framework-integ/test/aws-apigatewayv2/test/http/integ.stage.js.snapshot/aws-cdk-aws-apigatewayv2-http-stage.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-apigatewayv2/test/http/integ.stage.js.snapshot/aws-cdk-aws-apigatewayv2-http-stage.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-apigatewayv2/test/http/integ.stage.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-apigatewayv2/test/http/integ.stage.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-apigatewayv2/test/http/integ.stage.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-apigatewayv2/test/http/integ.stage.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-apigatewayv2/test/http/integ.stage.ts
  packages/@aws-cdk-testing/framework-integ/test/aws-apigatewayv2/test/websocket/integ.stage.js.snapshot/aws-cdk-aws-apigatewayv2-websocket-stage.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-apigatewayv2/test/websocket/integ.stage.js.snapshot/aws-cdk-aws-apigatewayv2-websocket-stage.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-apigatewayv2/test/websocket/integ.stage.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-apigatewayv2/test/websocket/integ.stage.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-apigatewayv2/test/websocket/integ.stage.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-apigatewayv2/test/websocket/integ.stage.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-apigatewayv2/test/websocket/integ.stage.ts
  packages/aws-cdk-lib/aws-apigatewayv2/README.md
  packages/aws-cdk-lib/aws-apigatewayv2/lib/common/stage.ts
  packages/aws-cdk-lib/aws-apigatewayv2/lib/http/stage.ts
  packages/aws-cdk-lib/aws-apigatewayv2/lib/websocket/stage.ts
  packages/aws-cdk-lib/aws-apigatewayv2/test/http/stage.test.ts
  packages/aws-cdk-lib/aws-apigatewayv2/test/websocket/stage.test.ts
Labels: p2, beginning-contributor, pr-linter/exemption-requested, pr/needs-maintainer-review

#30902 fix(ecs): fromServiceArnWithCluster not accepting value from SSM Parameter string
  packages/aws-cdk-lib/aws-ecs/lib/base/base-service.ts
  packages/aws-cdk-lib/aws-ecs/test/base-service.test.ts
Labels: bug, p1, effort/small, contribution/core, pr-linter/exempt-integ-test

#30493 feat(events): support customer managed key for event bus
  packages/@aws-cdk-testing/framework-integ/test/aws-events/test/integ.eventbus-customer-managed-key.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-events/test/integ.eventbus-customer-managed-key.js.snapshot/eventbue-customer-managed-key.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-events/test/integ.eventbus-customer-managed-key.js.snapshot/eventbue-customer-managed-key.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-events/test/integ.eventbus-customer-managed-key.js.snapshot/eventbuecustomermanagedkeytestDefaultTestDeployAssertBCCA03C5.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-events/test/integ.eventbus-customer-managed-key.js.snapshot/eventbuecustomermanagedkeytestDefaultTestDeployAssertBCCA03C5.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-events/test/integ.eventbus-customer-managed-key.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-events/test/integ.eventbus-customer-managed-key.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-events/test/integ.eventbus-customer-managed-key.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-events/test/integ.eventbus-customer-managed-key.ts
  packages/aws-cdk-lib/aws-events/README.md
  packages/aws-cdk-lib/aws-events/lib/event-bus.ts
  packages/aws-cdk-lib/aws-events/test/event-bus.test.ts
Labels: p2, admired-contributor, pr/needs-maintainer-review

#30925 chore(merge-back): 2.150.0
  CHANGELOG.v2.alpha.md
  CHANGELOG.v2.md
  version.v2.json
Labels: p2, pr/needs-community-review, pr/no-squash, auto-approve

#30788 fix(stepfunctions-tasks): run task perm no longer valid
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/ecs/integ.ec2-run-task.ts
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/ecs/integ.fargate-run-task.ts
  packages/aws-cdk-lib/aws-stepfunctions-tasks/lib/ecs/run-task.ts
  packages/aws-cdk-lib/aws-stepfunctions-tasks/test/ecs/run-tasks-feature-flag.test.ts
  packages/aws-cdk-lib/aws-stepfunctions-tasks/test/ecs/run-tasks.test.ts
  packages/aws-cdk-lib/cx-api/lib/features.ts
Labels: bug, p2, effort/small, pr/needs-community-review, pr-linter/exempt-integ-test, distinguished-contributor

#30298 feat(stepfunctions-tasks): allow BedrockInvokeModel to use JsonPath
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/bedrock/integ.invoke-model.js.snapshot/InvokeModelDefaultTestDeployAssert9C0D2DFC.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/bedrock/integ.invoke-model.js.snapshot/aws-stepfunctions-tasks-bedrock-invoke-model-integ.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/bedrock/integ.invoke-model.js.snapshot/aws-stepfunctions-tasks-bedrock-invoke-model-integ.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/bedrock/integ.invoke-model.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/bedrock/integ.invoke-model.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/bedrock/integ.invoke-model.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/bedrock/integ.invoke-model.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/bedrock/integ.invoke-model.ts
  packages/aws-cdk-lib/aws-stepfunctions-tasks/README.md
  packages/aws-cdk-lib/aws-stepfunctions-tasks/lib/bedrock/invoke-model.ts
  packages/aws-cdk-lib/aws-stepfunctions-tasks/test/bedrock/invoke-model.test.ts
Labels: bug, p1, effort/medium, contribution/core

#30837 feat(ec2): add `versionDescription` property for `LaunchTemplate`
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.launch-template.js.snapshot/aws-cdk-ec2-lt-metadata-1.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.launch-template.js.snapshot/aws-cdk-ec2-lt-metadata-1.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.launch-template.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.launch-template.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.launch-template.ts
  packages/aws-cdk-lib/aws-ec2/README.md
  packages/aws-cdk-lib/aws-ec2/lib/launch-template.ts
  packages/aws-cdk-lib/aws-ec2/test/launch-template.test.ts
Labels: p2, beginning-contributor

#30829 chore(eks): update failing snapshots
  packages/@aws-cdk-testing/framework-integ/test/aws-eks/test/integ.eks-helm-asset.js.snapshot/asset.58216e9cbe7ed5d0c2b7c7d47e173e8f81c25ea6457f5446c34c22be7e6f7f51/apply/__init__.py
  packages/@aws-cdk-testing/framework-integ/test/aws-eks/test/integ.eks-helm-asset.js.snapshot/asset.58216e9cbe7ed5d0c2b7c7d47e173e8f81c25ea6457f5446c34c22be7e6f7f51/get/__init__.py
  packages/@aws-cdk-testing/framework-integ/test/aws-eks/test/integ.eks-helm-asset.js.snapshot/asset.58216e9cbe7ed5d0c2b7c7d47e173e8f81c25ea6457f5446c34c22be7e6f7f51/helm/__init__.py
  packages/@aws-cdk-testing/framework-integ/test/aws-eks/test/integ.eks-helm-asset.js.snapshot/asset.58216e9cbe7ed5d0c2b7c7d47e173e8f81c25ea6457f5446c34c22be7e6f7f51/index.py
  packages/@aws-cdk-testing/framework-integ/test/aws-eks/test/integ.eks-helm-asset.js.snapshot/asset.58216e9cbe7ed5d0c2b7c7d47e173e8f81c25ea6457f5446c34c22be7e6f7f51/patch/__init__.py
  packages/@aws-cdk-testing/framework-integ/test/aws-eks/test/integ.eks-helm-asset.js.snapshot/aws-cdk-eks-helm-test.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-eks/test/integ.eks-helm-asset.js.snapshot/aws-cdk-eks-helm-test.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-eks/test/integ.eks-helm-asset.js.snapshot/awscdkekshelmtestawscdkawseksKubectlProvider207F42E4.nested.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-eks/test/integ.eks-helm-asset.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-eks/test/integ.eks-helm-asset.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-eks/test/integ.eks-helm-asset.ts
Labels: p2, contribution/core

#30934 chore: add note to bug report template
  .github/ISSUE_TEMPLATE/bug-report.yml
Labels: p2, contribution/core

#30459 docs(rds): clarify how to enable S3Import/S3Export in Readme.md
  packages/aws-cdk-lib/aws-rds/README.md
  packages/aws-cdk-lib/aws-rds/lib/cluster.ts
Labels: p2, beginning-contributor

#30941 chore: lock conversations on closed issues and PRs with message
  .github/workflows/closed-issue-message.yml
  .github/workflows/lock-issue-pr-with-message.yml
Labels: p2, contribution/core

#30659 chore(elasticloadbalancingv2): specific 5XX CloudWatch metrics for ALB
  packages/aws-cdk-lib/aws-elasticloadbalancingv2/lib/alb/application-load-balancer.ts
  packages/aws-cdk-lib/aws-elasticloadbalancingv2/test/alb/load-balancer.test.ts
Labels: p2, star-contributor

#30942 chore: update message in GHA lock conversations
  .github/workflows/lock-issue-pr-with-message.yml
Labels: p2, contribution/core

#30932 chore(bedrock): support meta llama3-1
  packages/aws-cdk-lib/aws-bedrock/lib/foundation-model.ts
Labels: p2, star-contributor

#30733 fix(appconfig): sourcedConfiguration doesn't use retrievalRole
  packages/@aws-cdk-testing/framework-integ/test/aws-appconfig/test/integ.configuration.js.snapshot/asset.0158f40002a8c211635388a87874fd4dcc3d68f525fe08a0fe0f014069ae539c/index.py
  packages/@aws-cdk-testing/framework-integ/test/aws-appconfig/test/integ.configuration.js.snapshot/asset.44e9c4d7a5d3fd2d677e1a7e416b2b56f6b0104bd5eff9cac5557b4c65a9dc61/index.js
  packages/@aws-cdk-testing/framework-integ/test/aws-appconfig/test/integ.configuration.js.snapshot/aws-appconfig-configuration.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-appconfig/test/integ.configuration.js.snapshot/aws-appconfig-configuration.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-appconfig/test/integ.configuration.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-appconfig/test/integ.configuration.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-appconfig/test/integ.configuration.ts
  packages/aws-cdk-lib/aws-appconfig/lib/configuration.ts
  packages/aws-cdk-lib/aws-appconfig/test/configuration.test.ts
Labels: bug, p2, effort/small, contribution/core

#30314 chore(lambda): add `otel-sqs-handler` to the `AdotLambdaLayerType` enum
  packages/aws-cdk-lib/aws-lambda/lib/adot-layers.ts
Labels: p2, feature-request, effort/medium, valued-contributor

#30955 chore(doc): fix broken link for RFC in contributing guide
  CONTRIBUTING.md
Labels: p2, contribution/core

#30945 chore(bedrock): support Mistral Large 2
  packages/aws-cdk-lib/aws-bedrock/lib/foundation-model.ts
Labels: p2, star-contributor

#30797 chore(cloudfront): adding Managed cache policy
  packages/aws-cdk-lib/aws-cloudfront/lib/cache-policy.ts
Labels: p2, distinguished-contributor

#30926 docs(ecs): describe default tag value for fromEcrRepository method
  packages/aws-cdk-lib/aws-ecs/lib/container-image.ts
Labels: p2, star-contributor

#30770 feat(sns): add validation of `displayName` for topic
  packages/aws-cdk-lib/aws-sns/lib/topic.ts
  packages/aws-cdk-lib/aws-sns/test/sns.test.ts
Labels: p2, pr-linter/exempt-readme, pr-linter/exempt-integ-test, beginning-contributor

#30948 chore(sagemaker): added support for ml.g6 instances
  packages/@aws-cdk/aws-sagemaker-alpha/lib/instance-type.ts
Labels: p2, beginning-contributor

#30896 fix(stepfunctions-tasks): fix the generated IAM policy for EFS operations
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/aws-sdk/integ.call-aws-service-efs.js.snapshot/IntegTestDefaultTestDeployAssertE3E7D2A4.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/aws-sdk/integ.call-aws-service-efs.js.snapshot/IntegTestDefaultTestDeployAssertE3E7D2A4.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/aws-sdk/integ.call-aws-service-efs.js.snapshot/aws-stepfunctions-tasks-call-aws-service-efs-integ.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/aws-sdk/integ.call-aws-service-efs.js.snapshot/aws-stepfunctions-tasks-call-aws-service-efs-integ.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/aws-sdk/integ.call-aws-service-efs.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/aws-sdk/integ.call-aws-service-efs.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/aws-sdk/integ.call-aws-service-efs.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/aws-sdk/integ.call-aws-service-efs.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/aws-sdk/integ.call-aws-service-efs.ts
  packages/aws-cdk-lib/aws-stepfunctions-tasks/lib/aws-sdk/call-aws-service.ts
  packages/aws-cdk-lib/aws-stepfunctions-tasks/test/aws-sdk/call-aws-service.test.ts
Labels: bug, p2, effort/small

#30542 feat(elasticloadbalancingv2): support Weighted Random algorithm and Automatic Target Weights for alb
  packages/@aws-cdk-testing/framework-integ/test/aws-elasticloadbalancingv2/test/integ.alb.weighte-random-algorithm.js.snapshot/alb-weight-rando-algorithm-test-stack.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-elasticloadbalancingv2/test/integ.alb.weighte-random-algorithm.js.snapshot/alb-weight-rando-algorithm-test-stack.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-elasticloadbalancingv2/test/integ.alb.weighte-random-algorithm.js.snapshot/albweightrandoalgorithmtestintegDefaultTestDeployAssertD1584525.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-elasticloadbalancingv2/test/integ.alb.weighte-random-algorithm.js.snapshot/albweightrandoalgorithmtestintegDefaultTestDeployAssertD1584525.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-elasticloadbalancingv2/test/integ.alb.weighte-random-algorithm.js.snapshot/asset.bde7b5c89cb43285f884c94f0b9e17cdb0f5eb5345005114dd60342e0b8a85a1/__entrypoint__.js
  packages/@aws-cdk-testing/framework-integ/test/aws-elasticloadbalancingv2/test/integ.alb.weighte-random-algorithm.js.snapshot/asset.bde7b5c89cb43285f884c94f0b9e17cdb0f5eb5345005114dd60342e0b8a85a1/index.js
  packages/@aws-cdk-testing/framework-integ/test/aws-elasticloadbalancingv2/test/integ.alb.weighte-random-algorithm.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-elasticloadbalancingv2/test/integ.alb.weighte-random-algorithm.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-elasticloadbalancingv2/test/integ.alb.weighte-random-algorithm.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-elasticloadbalancingv2/test/integ.alb.weighte-random-algorithm.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-elasticloadbalancingv2/test/integ.alb.weighte-random-algorithm.ts
  packages/aws-cdk-lib/aws-elasticloadbalancingv2/README.md
  packages/aws-cdk-lib/aws-elasticloadbalancingv2/lib/alb/application-listener.ts
  packages/aws-cdk-lib/aws-elasticloadbalancingv2/lib/alb/application-target-group.ts
  packages/aws-cdk-lib/aws-elasticloadbalancingv2/lib/shared/enums.ts
  packages/aws-cdk-lib/aws-elasticloadbalancingv2/test/alb/listener.test.ts
  packages/aws-cdk-lib/aws-elasticloadbalancingv2/test/alb/target-group.test.ts
Labels: p2, feature-request, effort/small, admired-contributor, pr/needs-maintainer-review

#30166 feat(ecs): add validation checks to memory cpu combinations of FARGATE compatible task definitions
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs/test/integ.fargate-task-def.js.snapshot/FargateTaskDefinitionDefaultTestDeployAssertD76B1D35.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs/test/integ.fargate-task-def.js.snapshot/FargateTaskDefinitionDefaultTestDeployAssertD76B1D35.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs/test/integ.fargate-task-def.js.snapshot/aws-ecs-fargate-task-def.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs/test/integ.fargate-task-def.js.snapshot/aws-ecs-fargate-task-def.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs/test/integ.fargate-task-def.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs/test/integ.fargate-task-def.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs/test/integ.fargate-task-def.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs/test/integ.fargate-task-def.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs/test/integ.fargate-task-def.ts
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs/test/integ.task-def.js.snapshot/TaskDefinitionDefaultTestDeployAssertF13B2133.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs/test/integ.task-def.js.snapshot/TaskDefinitionDefaultTestDeployAssertF13B2133.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs/test/integ.task-def.js.snapshot/aws-ecs-task-def.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs/test/integ.task-def.js.snapshot/aws-ecs-task-def.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs/test/integ.task-def.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs/test/integ.task-def.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs/test/integ.task-def.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs/test/integ.task-def.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs/test/integ.task-def.ts
  packages/aws-cdk-lib/aws-codepipeline-actions/test/servicecatalog/servicecatalog-deploy-action-beta1.test.ts
  packages/aws-cdk-lib/aws-ecs-patterns/test/fargate/load-balanced-fargate-service-v2.test.ts
  packages/aws-cdk-lib/aws-ecs-patterns/test/fargate/load-balanced-fargate-service.test.ts
  packages/aws-cdk-lib/aws-ecs-patterns/test/fargate/scheduled-fargate-task.test.ts
  packages/aws-cdk-lib/aws-ecs/README.md
  packages/aws-cdk-lib/aws-ecs/lib/base/task-definition.ts
  packages/aws-cdk-lib/aws-ecs/test/fargate/fargate-task-definition.test.ts
  packages/aws-cdk-lib/aws-ecs/test/task-definition.test.ts
  packages/aws-cdk/test/api/cloudformation-deployments.test.ts
Labels: bug, p2, effort/small, beginning-contributor

#30202 chore(ec2): support new vpc flow log fields in v7
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.vpc-flow-logs-customformat.js.snapshot/FlowLogsTestStack.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.vpc-flow-logs-customformat.js.snapshot/FlowLogsTestStack.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.vpc-flow-logs-customformat.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.vpc-flow-logs-customformat.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.vpc-flow-logs-customformat.ts
  packages/aws-cdk-lib/aws-ec2/lib/vpc-flow-logs.ts
  packages/aws-cdk-lib/aws-ec2/test/vpc-flow-logs.test.ts
Labels: p2, admired-contributor

#30979 docs(ses): corrected default value as true for ConfigurationSet.reputationMetrics property
  packages/aws-cdk-lib/aws-ses/lib/configuration-set.ts
Labels: p2, effort/small

#30978 chore(apigateway): enhance code arounds method authorizers
  packages/aws-cdk-lib/aws-apigateway/lib/method.ts
Labels: p2, contribution/core

#30973 feat: update L1 CloudFormation resource definitions
  packages/@aws-cdk/cloudformation-diff/package.json
  packages/@aws-cdk/integ-runner/package.json
  packages/aws-cdk-lib/package.json
  tools/@aws-cdk/spec2cdk/package.json
  yarn.lock
Labels: p2, dependencies, contribution/core, pr-linter/exempt-readme, pr-linter/exempt-test, auto-approve, pr-linter/exempt-integ-test

#30965 docs: remove headings from method doc
  packages/aws-cdk-lib/core/lib/stack.ts
Labels: p2, beginning-contributor

#30149 chore(apprunner-alpha): add runtimes PYTHON_311 and NODEJS_18
  packages/@aws-cdk/aws-apprunner-alpha/lib/service.ts
Labels: bug, p2, effort/small, beginning-contributor

#30723 feat(kinesisanalytics-flink): add support for Flink 1.19
  packages/@aws-cdk/aws-kinesisanalytics-flink-alpha/README.md
  packages/@aws-cdk/aws-kinesisanalytics-flink-alpha/lib/types.ts
  packages/@aws-cdk/aws-kinesisanalytics-flink-alpha/test/application.test.ts
  packages/@aws-cdk/aws-kinesisanalytics-flink-alpha/test/integ.application-code-from-bucket.lit.js.snapshot/FlinkAppCodeFromBucketTest.assets.json
  packages/@aws-cdk/aws-kinesisanalytics-flink-alpha/test/integ.application-code-from-bucket.lit.js.snapshot/FlinkAppCodeFromBucketTest.template.json
  packages/@aws-cdk/aws-kinesisanalytics-flink-alpha/test/integ.application-code-from-bucket.lit.js.snapshot/manifest.json
  packages/@aws-cdk/aws-kinesisanalytics-flink-alpha/test/integ.application-code-from-bucket.lit.js.snapshot/tree.json
  packages/@aws-cdk/aws-kinesisanalytics-flink-alpha/test/integ.application-code-from-bucket.lit.ts
  packages/@aws-cdk/aws-kinesisanalytics-flink-alpha/test/integ.application.lit.js.snapshot/FlinkAppTest.assets.json
  packages/@aws-cdk/aws-kinesisanalytics-flink-alpha/test/integ.application.lit.js.snapshot/FlinkAppTest.template.json
  packages/@aws-cdk/aws-kinesisanalytics-flink-alpha/test/integ.application.lit.js.snapshot/manifest.json
  packages/@aws-cdk/aws-kinesisanalytics-flink-alpha/test/integ.application.lit.js.snapshot/tree.json
  packages/@aws-cdk/aws-kinesisanalytics-flink-alpha/test/integ.application.lit.ts
  packages/@aws-cdk/aws-kinesisanalytics-flink-alpha/test/integ.vpc-application.js.snapshot/FlinkAppTest.assets.json
  packages/@aws-cdk/aws-kinesisanalytics-flink-alpha/test/integ.vpc-application.js.snapshot/FlinkAppTest.template.json
  packages/@aws-cdk/aws-kinesisanalytics-flink-alpha/test/integ.vpc-application.js.snapshot/manifest.json
  packages/@aws-cdk/aws-kinesisanalytics-flink-alpha/test/integ.vpc-application.js.snapshot/tree.json
  packages/@aws-cdk/aws-kinesisanalytics-flink-alpha/test/integ.vpc-application.ts
Labels: p2, repeat-contributor

#30974 chore(location): add validation for description property in PlaceIndex class
  packages/@aws-cdk/aws-location-alpha/lib/place-index.ts
  packages/@aws-cdk/aws-location-alpha/test/place-index.test.ts
Labels: p2, star-contributor, pr-linter/exemption-requested

#30808 fix(stepfunctions): allow disable x-ray
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions/test/integ.state-machine-disable-xray.js.snapshot/StateMachineDisableXrayDefaultTestDeployAssert24D3F33C.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions/test/integ.state-machine-disable-xray.js.snapshot/StateMachineDisableXrayDefaultTestDeployAssert24D3F33C.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions/test/integ.state-machine-disable-xray.js.snapshot/aws-stepfunctions-integ.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions/test/integ.state-machine-disable-xray.js.snapshot/aws-stepfunctions-integ.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions/test/integ.state-machine-disable-xray.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions/test/integ.state-machine-disable-xray.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions/test/integ.state-machine-disable-xray.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions/test/integ.state-machine-disable-xray.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions/test/integ.state-machine-disable-xray.ts
  packages/aws-cdk-lib/aws-stepfunctions/lib/state-machine.ts
  packages/aws-cdk-lib/aws-stepfunctions/test/state-machine.test.ts
Labels: p2, distinguished-contributor

#28810 fix(ec2): export NatGatewayProvider for consistency with NatInstanceProvider
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.nat-gateway-provider.js.snapshot/asset.bde7b5c89cb43285f884c94f0b9e17cdb0f5eb5345005114dd60342e0b8a85a1/__entrypoint__.js
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.nat-gateway-provider.js.snapshot/asset.bde7b5c89cb43285f884c94f0b9e17cdb0f5eb5345005114dd60342e0b8a85a1/index.js
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.nat-gateway-provider.js.snapshot/aws-cdk-vpc-nat-gateway-provider.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.nat-gateway-provider.js.snapshot/aws-cdk-vpc-nat-gateway-provider.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.nat-gateway-provider.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.nat-gateway-provider.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.nat-gateway-provider.js.snapshot/integtestDefaultTestDeployAssert24D5C536.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.nat-gateway-provider.js.snapshot/integtestDefaultTestDeployAssert24D5C536.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.nat-gateway-provider.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.nat-gateway-provider.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.nat-gateway-provider.ts
  packages/aws-cdk-lib/aws-ec2/lib/nat.ts
  packages/aws-cdk-lib/aws-ec2/test/vpc.test.ts
Labels: p2, feature-request, effort/medium, beginning-contributor, pr/reviewer-clarification-requested

#30935 feat(events): add `description` property for `eventBus`
  packages/@aws-cdk-testing/framework-integ/test/aws-events/test/integ.eventbus.js.snapshot/Stack.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-events/test/integ.eventbus.js.snapshot/Stack.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-events/test/integ.eventbus.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-events/test/integ.eventbus.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-events/test/integ.eventbus.ts
  packages/aws-cdk-lib/aws-events/README.md
  packages/aws-cdk-lib/aws-events/lib/event-bus.ts
  packages/aws-cdk-lib/aws-events/test/event-bus.test.ts
Labels: p2, beginning-contributor, pr/needs-maintainer-review

#30556 feat(synthetics): add activeTracing, memory and timeout property to Canary class
  packages/@aws-cdk-testing/framework-integ/test/aws-synthetics/test/integ.canary-run-config.js.snapshot/asset.d57a897c2081bda5ce88819548c8b944dff49e721e1f7f7e9e3dd8323e6ccb0d/index.js
  packages/@aws-cdk-testing/framework-integ/test/aws-synthetics/test/integ.canary-run-config.js.snapshot/cdk-synthetics-canary-run-config.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-synthetics/test/integ.canary-run-config.js.snapshot/cdk-synthetics-canary-run-config.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-synthetics/test/integ.canary-run-config.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-synthetics/test/integ.canary-run-config.js.snapshot/cdkintegsyntheticscanaryrunconfigDefaultTestDeployAssertDF592B72.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-synthetics/test/integ.canary-run-config.js.snapshot/cdkintegsyntheticscanaryrunconfigDefaultTestDeployAssertDF592B72.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-synthetics/test/integ.canary-run-config.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-synthetics/test/integ.canary-run-config.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-synthetics/test/integ.canary-run-config.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-synthetics/test/integ.canary-run-config.ts
  packages/aws-cdk-lib/aws-synthetics/README.md
  packages/aws-cdk-lib/aws-synthetics/lib/canary.ts
  packages/aws-cdk-lib/aws-synthetics/test/canary.test.ts
Labels: p2, feature-request, effort/medium, star-contributor, pr/needs-maintainer-review
