Repository aws/aws-cdk, pull requests merged in 2025-10, with the labels that each got.

#35638 chore(ci): scope codebuild PR build to aws/aws-cdk
  .github/workflows/codebuild-pr-build.yml
Labels: p2, contribution/core

#35645 chore(rds): add support for 8.0.mysql_aurora.3.10.1
  packages/aws-cdk-lib/aws-rds/lib/cluster-engine.ts
  packages/aws-cdk-lib/aws-rds/test/cluster-engine.test.ts
Labels: p2, repeat-contributor

#35636 chore: add ignore-team parameter to github-merit-badger workflow
  .github/workflows/github-merit-badger.yml
Labels: p2, contribution/core

#35659 ci(mergify): rename conditions to queue_conditions to fix in place checks
  .mergify.yml
Labels: p2, contribution/core

#35633 fix(s3): resolve synthesis error in BucketPolicy.fromCfnBucketPolicy()
  packages/aws-cdk-lib/aws-s3/lib/bucket-policy.ts
  packages/aws-cdk-lib/aws-s3/test/bucket-policy.test.ts
Labels: p2, contribution/core, pr-linter/exempt-integ-test, queued

#35420 fix(s3tables): s3 table bucket read access role uses incorrect permission for s3tables:ListNamespaces
  packages/@aws-cdk/aws-s3tables-alpha/lib/permissions.ts
  packages/@aws-cdk/aws-s3tables-alpha/test/integration/integ.table-bucket-with-grants.js.snapshot/TableBucketWithGrantIntegTestDefaultTestDeployAssert60E58AB6.template.json
  packages/@aws-cdk/aws-s3tables-alpha/test/integration/integ.table-bucket-with-grants.js.snapshot/grant-read-bucket-all-tables.template.json
  packages/@aws-cdk/aws-s3tables-alpha/test/integration/integ.table-bucket-with-grants.js.snapshot/grant-read-bucket.template.json
  packages/@aws-cdk/aws-s3tables-alpha/test/integration/integ.table-bucket-with-grants.js.snapshot/grant-read-write-bucket-all-tables.template.json
  packages/@aws-cdk/aws-s3tables-alpha/test/integration/integ.table-bucket-with-grants.js.snapshot/grant-read-write-bucket.template.json
  packages/@aws-cdk/aws-s3tables-alpha/test/integration/integ.table-bucket-with-grants.js.snapshot/tree.json
Labels: p2, pr-linter/exempt-integ-test, beginning-contributor, pr-linter/exemption-requested, queued

#35538 feat(ec2): support for automatic VPN session reconnect on client VPN endpoint
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.client-vpn-endpoint-disconnect-on-session-timeout.js.snapshot/asset.a1acfc2b5f4f6b183fd2bb9863f486bc5edef6a357b355a070d9a0e502df418c/__entrypoint__.js
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.client-vpn-endpoint-disconnect-on-session-timeout.js.snapshot/asset.a1acfc2b5f4f6b183fd2bb9863f486bc5edef6a357b355a070d9a0e502df418c/index.js
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.client-vpn-endpoint-disconnect-on-session-timeout.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.client-vpn-endpoint-disconnect-on-session-timeout.js.snapshot/client-vpn-endpoint-stack.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.client-vpn-endpoint-disconnect-on-session-timeout.js.snapshot/client-vpn-endpoint-stack.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.client-vpn-endpoint-disconnect-on-session-timeout.js.snapshot/clientvpnendpointintegDefaultTestDeployAssert7B9D072C.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.client-vpn-endpoint-disconnect-on-session-timeout.js.snapshot/clientvpnendpointintegDefaultTestDeployAssert7B9D072C.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.client-vpn-endpoint-disconnect-on-session-timeout.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.client-vpn-endpoint-disconnect-on-session-timeout.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.client-vpn-endpoint-disconnect-on-session-timeout.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.client-vpn-endpoint-disconnect-on-session-timeout.ts
  packages/aws-cdk-lib/aws-ec2/README.md
  packages/aws-cdk-lib/aws-ec2/lib/client-vpn-endpoint.ts
  packages/aws-cdk-lib/aws-ec2/test/client-vpn-endpoint.test.ts
Labels: p2, pr/needs-community-review, distinguished-contributor, queued

#35679 feat: update L1 CloudFormation resource definitions
  packages/aws-cdk-lib/package.json
  tools/@aws-cdk/spec2cdk/package.json
  yarn.lock
Labels: p2, dependencies, contribution/core, pr-linter/exempt-readme, pr-linter/exempt-test, pr-linter/exempt-integ-test, queued

#35560 feat(eks): add removal policy support for EKS cluster construct
  packages/@aws-cdk-testing/framework-integ/test/aws-eks/test/integ.eks-cluster-removal-policy.js.snapshot/EksClusterRemovalPolicyStack.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-eks/test/integ.eks-cluster-removal-policy.js.snapshot/EksClusterRemovalPolicyStack.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-eks/test/integ.eks-cluster-removal-policy.js.snapshot/EksClusterRemovalPolicyStackawscdkawseksClusterResourceProviderCEDC6C1C.nested.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-eks/test/integ.eks-cluster-removal-policy.js.snapshot/EksClusterRemovalPolicyStackawscdkawseksKubectlProvider6267041B.nested.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-eks/test/integ.eks-cluster-removal-policy.js.snapshot/asset.39472b1c2875cf306d4ba429aeccdd34cb49bcf59dbde81f7e6b6cb9deac23a6/cfn-response.js
  packages/@aws-cdk-testing/framework-integ/test/aws-eks/test/integ.eks-cluster-removal-policy.js.snapshot/asset.39472b1c2875cf306d4ba429aeccdd34cb49bcf59dbde81f7e6b6cb9deac23a6/consts.js
  packages/@aws-cdk-testing/framework-integ/test/aws-eks/test/integ.eks-cluster-removal-policy.js.snapshot/asset.39472b1c2875cf306d4ba429aeccdd34cb49bcf59dbde81f7e6b6cb9deac23a6/framework.js
  packages/@aws-cdk-testing/framework-integ/test/aws-eks/test/integ.eks-cluster-removal-policy.js.snapshot/asset.39472b1c2875cf306d4ba429aeccdd34cb49bcf59dbde81f7e6b6cb9deac23a6/outbound.js
  packages/@aws-cdk-testing/framework-integ/test/aws-eks/test/integ.eks-cluster-removal-policy.js.snapshot/asset.39472b1c2875cf306d4ba429aeccdd34cb49bcf59dbde81f7e6b6cb9deac23a6/util.js
  packages/@aws-cdk-testing/framework-integ/test/aws-eks/test/integ.eks-cluster-removal-policy.js.snapshot/asset.6094cb0ff874f89ab5ab24fb6b9417df0fdeb6966645f90c88ec1d7e28130112.zip
  packages/@aws-cdk-testing/framework-integ/test/aws-eks/test/integ.eks-cluster-removal-policy.js.snapshot/asset.93d96d34e0d3cd20eb082652b91012b131bdc34fcf2bc16eb4170e04772fddb1.zip
  packages/@aws-cdk-testing/framework-integ/test/aws-eks/test/integ.eks-cluster-removal-policy.js.snapshot/asset.a1acfc2b5f4f6b183fd2bb9863f486bc5edef6a357b355a070d9a0e502df418c/__entrypoint__.js
  packages/@aws-cdk-testing/framework-integ/test/aws-eks/test/integ.eks-cluster-removal-policy.js.snapshot/asset.a1acfc2b5f4f6b183fd2bb9863f486bc5edef6a357b355a070d9a0e502df418c/index.js
  packages/@aws-cdk-testing/framework-integ/test/aws-eks/test/integ.eks-cluster-removal-policy.js.snapshot/asset.c49d356cac773d491c5f7ac148995a1181498a8e289429f8612a7f7e3814f535.zip
  packages/@aws-cdk-testing/framework-integ/test/aws-eks/test/integ.eks-cluster-removal-policy.js.snapshot/asset.cade4507238b95610e5a629416679281cfe0402b01ec588c0c282945725c767c/index.js
  packages/@aws-cdk-testing/framework-integ/test/aws-eks/test/integ.eks-cluster-removal-policy.js.snapshot/asset.d671460286b61f85906debbcec5341ea4edad148fbc432b0663593611866728e/apply/__init__.py
  packages/@aws-cdk-testing/framework-integ/test/aws-eks/test/integ.eks-cluster-removal-policy.js.snapshot/asset.d671460286b61f85906debbcec5341ea4edad148fbc432b0663593611866728e/get/__init__.py
  packages/@aws-cdk-testing/framework-integ/test/aws-eks/test/integ.eks-cluster-removal-policy.js.snapshot/asset.d671460286b61f85906debbcec5341ea4edad148fbc432b0663593611866728e/helm/__init__.py
  packages/@aws-cdk-testing/framework-integ/test/aws-eks/test/integ.eks-cluster-removal-policy.js.snapshot/asset.d671460286b61f85906debbcec5341ea4edad148fbc432b0663593611866728e/index.py
  packages/@aws-cdk-testing/framework-integ/test/aws-eks/test/integ.eks-cluster-removal-policy.js.snapshot/asset.d671460286b61f85906debbcec5341ea4edad148fbc432b0663593611866728e/patch/__init__.py
  packages/@aws-cdk-testing/framework-integ/test/aws-eks/test/integ.eks-cluster-removal-policy.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-eks/test/integ.eks-cluster-removal-policy.js.snapshot/eksclusterremovalpolicyintegDefaultTestDeployAssertC54E19AC.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-eks/test/integ.eks-cluster-removal-policy.js.snapshot/eksclusterremovalpolicyintegDefaultTestDeployAssertC54E19AC.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-eks/test/integ.eks-cluster-removal-policy.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-eks/test/integ.eks-cluster-removal-policy.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-eks/test/integ.eks-cluster-removal-policy.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-eks/test/integ.eks-cluster-removal-policy.ts
  packages/aws-cdk-lib/aws-eks/README.md
  packages/aws-cdk-lib/aws-eks/lib/cluster.ts
  packages/aws-cdk-lib/aws-eks/test/cluster.test.ts
Labels: p2, feature-request, effort/small, contribution/core, queued
