Repository aws/aws-cdk, pull requests merged in 2025-02, with the labels that each got.

#32956 feat(ec2-alpha): add Transit Gateway L2
  packages/@aws-cdk/aws-ec2-alpha/README.md
  packages/@aws-cdk/aws-ec2-alpha/awslint.json
  packages/@aws-cdk/aws-ec2-alpha/lib/index.ts
  packages/@aws-cdk/aws-ec2-alpha/lib/transit-gateway-association.ts
  packages/@aws-cdk/aws-ec2-alpha/lib/transit-gateway-attachment.ts
  packages/@aws-cdk/aws-ec2-alpha/lib/transit-gateway-route-table-association.ts
  packages/@aws-cdk/aws-ec2-alpha/lib/transit-gateway-route-table-propagation.ts
  packages/@aws-cdk/aws-ec2-alpha/lib/transit-gateway-route-table.ts
  packages/@aws-cdk/aws-ec2-alpha/lib/transit-gateway-route.ts
  packages/@aws-cdk/aws-ec2-alpha/lib/transit-gateway-vpc-attachment.ts
  packages/@aws-cdk/aws-ec2-alpha/lib/transit-gateway.ts
  packages/@aws-cdk/aws-ec2-alpha/lib/util.ts
  packages/@aws-cdk/aws-ec2-alpha/rosetta/default.ts-fixture
  packages/@aws-cdk/aws-ec2-alpha/test/integ.transit-gateway.js.snapshot/aws-cdk-ec2-alpha-transit-gateway-disable-automatic-settings.assets.json
  packages/@aws-cdk/aws-ec2-alpha/test/integ.transit-gateway.js.snapshot/aws-cdk-ec2-alpha-transit-gateway-disable-automatic-settings.template.json
  packages/@aws-cdk/aws-ec2-alpha/test/integ.transit-gateway.js.snapshot/cdk.out
  packages/@aws-cdk/aws-ec2-alpha/test/integ.transit-gateway.js.snapshot/integ.json
  packages/@aws-cdk/aws-ec2-alpha/test/integ.transit-gateway.js.snapshot/integtestmodelDefaultTestDeployAssertCF40BD53.assets.json
  packages/@aws-cdk/aws-ec2-alpha/test/integ.transit-gateway.js.snapshot/integtestmodelDefaultTestDeployAssertCF40BD53.template.json
  packages/@aws-cdk/aws-ec2-alpha/test/integ.transit-gateway.js.snapshot/manifest.json
  packages/@aws-cdk/aws-ec2-alpha/test/integ.transit-gateway.js.snapshot/tree.json
  packages/@aws-cdk/aws-ec2-alpha/test/integ.transit-gateway.ts
  packages/@aws-cdk/aws-ec2-alpha/test/transit-gateway-route-table-association.test.ts
  packages/@aws-cdk/aws-ec2-alpha/test/transit-gateway-route-table-propagation.test.ts
  packages/@aws-cdk/aws-ec2-alpha/test/transit-gateway-route-table.test.ts
  packages/@aws-cdk/aws-ec2-alpha/test/transit-gateway-route.test.ts
  packages/@aws-cdk/aws-ec2-alpha/test/transit-gateway-vpc-attachment.test.ts
  packages/@aws-cdk/aws-ec2-alpha/test/transit-gateway.test.ts
Labels: p2, feature-request, effort/medium, contribution/core

#33272 feat: update L1 CloudFormation resource definitions
  packages/@aws-cdk/cloudformation-diff/package.json
  packages/@aws-cdk/integ-runner/package.json
  packages/aws-cdk-lib/package.json
  tools/@aws-cdk/spec2cdk/package.json
  yarn.lock
Labels: p2, dependencies, contribution/core, pr-linter/exempt-readme, pr-linter/exempt-test, auto-approve, pr-linter/exempt-integ-test, pr/needs-maintainer-review

#33248 chore(ecs): mark TaskDefinition inferenceAccelerators as deprecated
  packages/aws-cdk-lib/aws-ecs/lib/base/task-definition.ts
Labels: p2, contribution/core

#32780 feat(msk): support ServerlessCluster
  packages/@aws-cdk/aws-msk-alpha/README.md
  packages/@aws-cdk/aws-msk-alpha/awslint.json
  packages/@aws-cdk/aws-msk-alpha/lib/cluster.ts
  packages/@aws-cdk/aws-msk-alpha/lib/index.ts
  packages/@aws-cdk/aws-msk-alpha/lib/serverless-cluster.ts
  packages/@aws-cdk/aws-msk-alpha/test/integ.serverless-cluster.js.snapshot/cdk.out
  packages/@aws-cdk/aws-msk-alpha/test/integ.serverless-cluster.js.snapshot/integ.json
  packages/@aws-cdk/aws-msk-alpha/test/integ.serverless-cluster.js.snapshot/manifest.json
  packages/@aws-cdk/aws-msk-alpha/test/integ.serverless-cluster.js.snapshot/msk-serverless-stack.assets.json
  packages/@aws-cdk/aws-msk-alpha/test/integ.serverless-cluster.js.snapshot/msk-serverless-stack.template.json
  packages/@aws-cdk/aws-msk-alpha/test/integ.serverless-cluster.js.snapshot/mskserverlessintegDefaultTestDeployAssertDD46F007.assets.json
  packages/@aws-cdk/aws-msk-alpha/test/integ.serverless-cluster.js.snapshot/mskserverlessintegDefaultTestDeployAssertDD46F007.template.json
  packages/@aws-cdk/aws-msk-alpha/test/integ.serverless-cluster.js.snapshot/tree.json
  packages/@aws-cdk/aws-msk-alpha/test/integ.serverless-cluster.ts
  packages/@aws-cdk/aws-msk-alpha/test/serverless-cluster.test.ts
Labels: p2, feature-request, effort/medium, distinguished-contributor

#32225 feat(ecs): support container version consistency
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs/test/base/integ.task-definition-container-version-consistency.js.snapshot/TaskDefinitionContainerRestartPolicyDefaultTestDeployAssert2196C660.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs/test/base/integ.task-definition-container-version-consistency.js.snapshot/TaskDefinitionContainerRestartPolicyDefaultTestDeployAssert2196C660.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs/test/base/integ.task-definition-container-version-consistency.js.snapshot/aws-ecs-task-definition-container-version-consistency.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs/test/base/integ.task-definition-container-version-consistency.js.snapshot/aws-ecs-task-definition-container-version-consistency.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs/test/base/integ.task-definition-container-version-consistency.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs/test/base/integ.task-definition-container-version-consistency.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs/test/base/integ.task-definition-container-version-consistency.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs/test/base/integ.task-definition-container-version-consistency.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs/test/base/integ.task-definition-container-version-consistency.ts
  packages/aws-cdk-lib/aws-ecs/README.md
  packages/aws-cdk-lib/aws-ecs/lib/container-definition.ts
  packages/aws-cdk-lib/aws-ecs/lib/container-image.ts
  packages/aws-cdk-lib/aws-ecs/lib/images/asset-image.ts
  packages/aws-cdk-lib/aws-ecs/test/container-definition.test.ts
Labels: p2, feature-request, effort/small, repeat-contributor

#33262 chore: enable GitHub workflow for Metadata updater
  .github/workflows/analytics-metadata-updater.yml
  tools/@aws-cdk/construct-metadata-updater/lib/metadata-updater.ts
Labels: p2, contribution/core

#30920 feat(ecs-patterns): add `containerCpu` and `containerMemoryLimitMiB` property to `ApplicationLoadBalancedFargateService`
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs-patterns/test/fargate/integ.container-cpu-memory.js.snapshot/aws-ecs-integ-container-cpu-memory.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs-patterns/test/fargate/integ.container-cpu-memory.js.snapshot/aws-ecs-integ-container-cpu-memory.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs-patterns/test/fargate/integ.container-cpu-memory.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs-patterns/test/fargate/integ.container-cpu-memory.js.snapshot/cpuAndMemoryAreSpecifiedTestDefaultTestDeployAssert2F87E3D5.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs-patterns/test/fargate/integ.container-cpu-memory.js.snapshot/cpuAndMemoryAreSpecifiedTestDefaultTestDeployAssert2F87E3D5.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs-patterns/test/fargate/integ.container-cpu-memory.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs-patterns/test/fargate/integ.container-cpu-memory.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs-patterns/test/fargate/integ.container-cpu-memory.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs-patterns/test/fargate/integ.container-cpu-memory.ts
  packages/aws-cdk-lib/aws-ecs-patterns/README.md
  packages/aws-cdk-lib/aws-ecs-patterns/lib/fargate/application-load-balanced-fargate-service.ts
  packages/aws-cdk-lib/aws-ecs-patterns/test/fargate/load-balanced-fargate-service.test.ts
  packages/aws-cdk-lib/aws-ecs/lib/fargate/fargate-task-definition.ts
Labels: p2, feature-request, effort/small, beginning-contributor, pr/needs-maintainer-review

#33263 chore: update Contributors File
  CONTRIBUTORS.md
Labels: p2, pr/needs-community-review, auto-approve

#32678 feat(elasticloadbalancingv2): support AdvertiseTrustStoreCaNames for mTLS
  packages/@aws-cdk-testing/framework-integ/test/aws-elasticloadbalancingv2/test/integ.alb-mtls.js.snapshot/alb-mtls-test-stack.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-elasticloadbalancingv2/test/integ.alb-mtls.js.snapshot/alb-mtls-test-stack.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-elasticloadbalancingv2/test/integ.alb-mtls.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-elasticloadbalancingv2/test/integ.alb-mtls.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-elasticloadbalancingv2/test/integ.alb-mtls.ts
  packages/aws-cdk-lib/aws-elasticloadbalancingv2/README.md
  packages/aws-cdk-lib/aws-elasticloadbalancingv2/lib/alb/application-listener.ts
  packages/aws-cdk-lib/aws-elasticloadbalancingv2/test/alb/listener.test.ts
Labels: p2, valued-contributor, pr/needs-maintainer-review

#33289 docs(ec2): fix typo
  packages/aws-cdk-lib/aws-ec2/lib/client-vpn-endpoint.ts
Labels: p2, pr/needs-community-review, star-contributor

#33284 chore(toolkit): trim whitespace from IoMessages
  packages/@aws-cdk/toolkit/lib/api/io/private/logger.ts
  packages/@aws-cdk/toolkit/lib/toolkit/toolkit.ts
  packages/@aws-cdk/toolkit/test/toolkit/toolkit.test.ts
Labels: p2, contribution/core, pr/needs-maintainer-review

#33287 chore(toolkit): consistent durations and error codes
  packages/@aws-cdk/toolkit/lib/api/io/private/codes.ts
  packages/@aws-cdk/toolkit/lib/api/io/private/timer.ts
  packages/@aws-cdk/toolkit/lib/toolkit/toolkit.ts
  packages/@aws-cdk/toolkit/test/actions/deploy.test.ts
  packages/@aws-cdk/toolkit/test/actions/synth.test.ts
Labels: p1, contribution/core, pr/needs-maintainer-review

#33294 chore(merge-queue): adding a new merge queue to tackle priority PR
  .mergify.yml
Labels: p2, contribution/core

#32630 feat(ecs): `ExternalService` support daemon scheduling strategy
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs/test/external/integ.daemon-service.js.snapshot/asset.0620cd173f15e6874350d35d31917579f8488aac349f5c15062107ebca21d5b6.bundle/index.js
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs/test/external/integ.daemon-service.js.snapshot/asset.a1acfc2b5f4f6b183fd2bb9863f486bc5edef6a357b355a070d9a0e502df418c/__entrypoint__.js
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs/test/external/integ.daemon-service.js.snapshot/asset.a1acfc2b5f4f6b183fd2bb9863f486bc5edef6a357b355a070d9a0e502df418c/index.js
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs/test/external/integ.daemon-service.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs/test/external/integ.daemon-service.js.snapshot/ecs-external-service-daemon.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs/test/external/integ.daemon-service.js.snapshot/ecs-external-service-daemon.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs/test/external/integ.daemon-service.js.snapshot/ecsexternalservicedaemonecsexternalservicedaemontestDefaultTestDeployAssert31EDBC58.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs/test/external/integ.daemon-service.js.snapshot/ecsexternalservicedaemonecsexternalservicedaemontestDefaultTestDeployAssert31EDBC58.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs/test/external/integ.daemon-service.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs/test/external/integ.daemon-service.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs/test/external/integ.daemon-service.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs/test/external/integ.daemon-service.ts
  packages/aws-cdk-lib/aws-ecs/README.md
  packages/aws-cdk-lib/aws-ecs/lib/external/external-service.ts
  packages/aws-cdk-lib/aws-ecs/test/external/external-service.test.ts
Labels: p2, feature-request, effort/small, pr/needs-community-review, repeat-contributor

#32263 feat(ecs): support availability zone rebalancing
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs/test/ec2/integ.availability-zone-rebalancing.js.snapshot/aws-ecs-integ-availability-zone-rebalancing.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs/test/ec2/integ.availability-zone-rebalancing.js.snapshot/aws-ecs-integ-availability-zone-rebalancing.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs/test/ec2/integ.availability-zone-rebalancing.js.snapshot/awsecsintegavailabilityzonerebalancingAvailabilityZoneRebalancingDefaultTestDeployAssert8F80E41A.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs/test/ec2/integ.availability-zone-rebalancing.js.snapshot/awsecsintegavailabilityzonerebalancingAvailabilityZoneRebalancingDefaultTestDeployAssert8F80E41A.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs/test/ec2/integ.availability-zone-rebalancing.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs/test/ec2/integ.availability-zone-rebalancing.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs/test/ec2/integ.availability-zone-rebalancing.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs/test/ec2/integ.availability-zone-rebalancing.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs/test/ec2/integ.availability-zone-rebalancing.ts
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs/test/fargate/integ.availability-zone-rebalancing.js.snapshot/aws-ecs-integ-availability-zone-rebalancing.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs/test/fargate/integ.availability-zone-rebalancing.js.snapshot/aws-ecs-integ-availability-zone-rebalancing.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs/test/fargate/integ.availability-zone-rebalancing.js.snapshot/awsecsintegavailabilityzonerebalancingAvailabilityZoneRebalancingDefaultTestDeployAssert8F80E41A.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs/test/fargate/integ.availability-zone-rebalancing.js.snapshot/awsecsintegavailabilityzonerebalancingAvailabilityZoneRebalancingDefaultTestDeployAssert8F80E41A.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs/test/fargate/integ.availability-zone-rebalancing.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs/test/fargate/integ.availability-zone-rebalancing.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs/test/fargate/integ.availability-zone-rebalancing.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs/test/fargate/integ.availability-zone-rebalancing.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs/test/fargate/integ.availability-zone-rebalancing.ts
  packages/aws-cdk-lib/aws-ecs/README.md
  packages/aws-cdk-lib/aws-ecs/lib/availability-zone-rebalancing.ts
  packages/aws-cdk-lib/aws-ecs/lib/base/base-service.ts
  packages/aws-cdk-lib/aws-ecs/lib/ec2/ec2-service.ts
  packages/aws-cdk-lib/aws-ecs/lib/fargate/fargate-service.ts
  packages/aws-cdk-lib/aws-ecs/lib/index.ts
  packages/aws-cdk-lib/aws-ecs/test/ec2/ec2-service.test.ts
  packages/aws-cdk-lib/aws-ecs/test/fargate/fargate-service.test.ts
Labels: p2, feature-request, effort/medium, repeat-contributor

#33303 chore(mergify): update priority for new rule
  .mergify.yml
Labels: p2, contribution/core, pr/no-squash

#33312 chore(merge-back): 2.178.0
  CHANGELOG.v2.alpha.md
  CHANGELOG.v2.md
  packages/aws-cdk-lib/aws-ecs/lib/ec2/ec2-service.ts
  packages/aws-cdk-lib/aws-ecs/lib/fargate/fargate-service.ts
  packages/aws-cdk-lib/core/lib/analytics-data-source/classes.ts
  packages/aws-cdk-lib/core/lib/analytics-data-source/enums.ts
  packages/aws-cdk-lib/cx-api/FEATURE_FLAGS.md
  packages/aws-cdk-lib/cx-api/lib/features.ts
  version.v2.json
Labels: p2, pr/needs-community-review, pr/no-squash, auto-approve

#33324 fix(cli): sdk logging is always present even when not turned on
  packages/aws-cdk/lib/api/aws-auth/sdk-logger.ts
  packages/aws-cdk/test/api/aws-auth/sdk-logger.test.ts
Labels: bug, p1, effort/medium, contribution/core, pr-linter/exempt-integ-test, pr-linter/cli-integ-tested

#32251 feat(codebuild): attribute-based compute type for Fleet
  packages/@aws-cdk-testing/framework-integ/test/aws-codebuild/test/integ.project-fleet-attribute-based-compute.js.snapshot/AttributeBasedComputeFleetIntegStack0.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-codebuild/test/integ.project-fleet-attribute-based-compute.js.snapshot/AttributeBasedComputeFleetIntegStack0.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-codebuild/test/integ.project-fleet-attribute-based-compute.js.snapshot/AttributeBasedComputeFleetIntegStack1.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-codebuild/test/integ.project-fleet-attribute-based-compute.js.snapshot/AttributeBasedComputeFleetIntegStack1.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-codebuild/test/integ.project-fleet-attribute-based-compute.js.snapshot/AttributeBasedComputeFleetIntegTestDefaultTestDeployAssertDD94353E.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-codebuild/test/integ.project-fleet-attribute-based-compute.js.snapshot/AttributeBasedComputeFleetIntegTestDefaultTestDeployAssertDD94353E.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-codebuild/test/integ.project-fleet-attribute-based-compute.js.snapshot/asset.bfcf4228d6660f50e81f19efdb64c6388dda6796296eb239decdff1dbc2f4981.bundle/index.js
  packages/@aws-cdk-testing/framework-integ/test/aws-codebuild/test/integ.project-fleet-attribute-based-compute.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-codebuild/test/integ.project-fleet-attribute-based-compute.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-codebuild/test/integ.project-fleet-attribute-based-compute.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-codebuild/test/integ.project-fleet-attribute-based-compute.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-codebuild/test/integ.project-fleet-attribute-based-compute.ts
  packages/aws-cdk-lib/aws-codebuild/README.md
  packages/aws-cdk-lib/aws-codebuild/lib/compute-type.ts
  packages/aws-cdk-lib/aws-codebuild/lib/fleet.ts
  packages/aws-cdk-lib/aws-codebuild/test/fleet.test.ts
Labels: p2, distinguished-contributor

#32937 fix(lambda-event-sources): `SelfManagedKafkaEventSource` cannot be used in NPM symlinked workspaces
  packages/aws-cdk-lib/aws-lambda-event-sources/lib/kafka.ts
Labels: p2, pr-linter/exempt-test, pr-linter/exempt-integ-test, beginning-contributor

#33283 chore: add PR to R2 list only if there are 2 approvals
  scripts/@aws-cdk/script-tests/prioritization/assign-r2-priority.test.js
  scripts/@aws-cdk/script-tests/prioritization/helpers/mock-data.js
  scripts/prioritization/assign-r2-priority.js
Labels: p2, contribution/core

#33311 chore: add needs-attention field assignment for prioritization board
  .github/workflows/README.md
  .github/workflows/project-prioritization-needs-attention.yml
  scripts/@aws-cdk/script-tests/prioritization/assign-r5-priority.test.js
  scripts/@aws-cdk/script-tests/prioritization/helpers/mock-data.js
  scripts/@aws-cdk/script-tests/prioritization/update-attention-status.test.js
  scripts/prioritization/project-api.js
  scripts/prioritization/project-config.js
  scripts/prioritization/update-attention-status.js
Labels: p2, contribution/core

#33317 chore(toolkit): all error messages must have a code
  packages/@aws-cdk/toolkit/lib/api/io/private/codes.ts
  packages/@aws-cdk/toolkit/lib/api/io/private/messages.ts
  packages/@aws-cdk/toolkit/lib/toolkit/toolkit.ts
Labels: p2, contribution/core

#32524 chore(ecs-patterns): fix ec2/multiple-application-load-balanced-ecs-service integration test
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs-patterns/test/ec2/integ.multiple-application-load-balanced-ecs-service.js.snapshot/applicationMultipleTargetGroupsEc2ServiceTestDefaultTestDeployAssert1194B50F.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs-patterns/test/ec2/integ.multiple-application-load-balanced-ecs-service.js.snapshot/aws-ecs-integ-multiple-alb.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs-patterns/test/ec2/integ.multiple-application-load-balanced-ecs-service.js.snapshot/aws-ecs-integ-multiple-alb.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs-patterns/test/ec2/integ.multiple-application-load-balanced-ecs-service.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs-patterns/test/ec2/integ.multiple-application-load-balanced-ecs-service.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs-patterns/test/ec2/integ.multiple-application-load-balanced-ecs-service.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs-patterns/test/ec2/integ.multiple-application-load-balanced-ecs-service.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs-patterns/test/ec2/integ.multiple-application-load-balanced-ecs-service.ts
Labels: p2, beginning-contributor

#33330 chore(merge-back): 2.178.1
  CHANGELOG.v2.alpha.md
  CHANGELOG.v2.md
  version.v2.json
Labels: p2, pr/needs-community-review, pr/no-squash, auto-approve

#33018 fix(vpc): typo VPC Endpoint Payment Cryptography
  packages/aws-cdk-lib/aws-ec2/lib/vpc-endpoint.ts
Labels: p2, pr-linter/exempt-test, pr-linter/exempt-integ-test, beginning-contributor

#32862 feat(cognito): add analyticsConfiguration to UserPoolClient
  packages/@aws-cdk-testing/framework-integ/test/aws-cognito/test/integ.user-pool-client-analytics.js.snapshot/IntegUserPoolClientAnalytics.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-cognito/test/integ.user-pool-client-analytics.js.snapshot/IntegUserPoolClientAnalytics.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-cognito/test/integ.user-pool-client-analytics.js.snapshot/IntegUserPoolClientAnalytics2.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-cognito/test/integ.user-pool-client-analytics.js.snapshot/IntegUserPoolClientAnalytics2.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-cognito/test/integ.user-pool-client-analytics.js.snapshot/asset.bfcf4228d6660f50e81f19efdb64c6388dda6796296eb239decdff1dbc2f4981.bundle/index.js
  packages/@aws-cdk-testing/framework-integ/test/aws-cognito/test/integ.user-pool-client-analytics.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-cognito/test/integ.user-pool-client-analytics.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-cognito/test/integ.user-pool-client-analytics.js.snapshot/integuserpoolclienttestDefaultTestDeployAssertB83B7A3F.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-cognito/test/integ.user-pool-client-analytics.js.snapshot/integuserpoolclienttestDefaultTestDeployAssertB83B7A3F.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-cognito/test/integ.user-pool-client-analytics.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-cognito/test/integ.user-pool-client-analytics.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-cognito/test/integ.user-pool-client-analytics.ts
  packages/aws-cdk-lib/aws-cognito/README.md
  packages/aws-cdk-lib/aws-cognito/lib/user-pool-client.ts
  packages/aws-cdk-lib/aws-cognito/test/user-pool-client.test.ts
Labels: p2, feature-request, effort/small, repeat-contributor

#33267 feat(apigatewayv2): stage support `detailedMetricsEnabled` property
  packages/@aws-cdk-testing/framework-integ/test/aws-apigatewayv2/test/http/integ.stage.js.snapshot/aws-cdk-aws-apigatewayv2-http-stage.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-apigatewayv2/test/http/integ.stage.js.snapshot/aws-cdk-aws-apigatewayv2-http-stage.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-apigatewayv2/test/http/integ.stage.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-apigatewayv2/test/http/integ.stage.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-apigatewayv2/test/http/integ.stage.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-apigatewayv2/test/http/integ.stage.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-apigatewayv2/test/http/integ.stage.ts
  packages/@aws-cdk-testing/framework-integ/test/aws-apigatewayv2/test/websocket/integ.stage.js.snapshot/aws-cdk-aws-apigatewayv2-websocket-stage.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-apigatewayv2/test/websocket/integ.stage.js.snapshot/aws-cdk-aws-apigatewayv2-websocket-stage.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-apigatewayv2/test/websocket/integ.stage.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-apigatewayv2/test/websocket/integ.stage.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-apigatewayv2/test/websocket/integ.stage.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-apigatewayv2/test/websocket/integ.stage.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-apigatewayv2/test/websocket/integ.stage.ts
  packages/aws-cdk-lib/aws-apigatewayv2/README.md
  packages/aws-cdk-lib/aws-apigatewayv2/lib/common/stage.ts
  packages/aws-cdk-lib/aws-apigatewayv2/lib/http/stage.ts
  packages/aws-cdk-lib/aws-apigatewayv2/lib/websocket/stage.ts
  packages/aws-cdk-lib/aws-apigatewayv2/test/http/stage.test.ts
  packages/aws-cdk-lib/aws-apigatewayv2/test/websocket/stage.test.ts
Labels: p2, feature-request, effort/medium, repeat-contributor

#33298 chore(toolkit): list action
  packages/@aws-cdk/toolkit/lib/actions/list/index.ts
  packages/@aws-cdk/toolkit/lib/api/aws-cdk.ts
  packages/@aws-cdk/toolkit/lib/api/cloud-assembly/stack-selector.ts
  packages/@aws-cdk/toolkit/lib/api/io/private/codes.ts
  packages/@aws-cdk/toolkit/lib/toolkit/toolkit.ts
  packages/@aws-cdk/toolkit/test/_fixtures/console-output/app.js
  packages/@aws-cdk/toolkit/test/_fixtures/external-context/app.js
  packages/@aws-cdk/toolkit/test/_fixtures/external-context/index.ts
  packages/@aws-cdk/toolkit/test/_fixtures/stack-with-bucket/index.js
  packages/@aws-cdk/toolkit/test/_fixtures/stack-with-bucket/index.ts
  packages/@aws-cdk/toolkit/test/_fixtures/stack-with-notification-arns/index.ts
  packages/@aws-cdk/toolkit/test/_fixtures/stack-with-role/index.ts
  packages/@aws-cdk/toolkit/test/_fixtures/two-empty-stacks/app.js
  packages/@aws-cdk/toolkit/test/_fixtures/two-empty-stacks/index.js
  packages/@aws-cdk/toolkit/test/_fixtures/two-empty-stacks/index.ts
  packages/@aws-cdk/toolkit/test/_fixtures/validation-error/app.js
  packages/@aws-cdk/toolkit/test/_helpers/index.ts
  packages/@aws-cdk/toolkit/test/_helpers/test-cloud-assembly-source.ts
  packages/@aws-cdk/toolkit/test/actions/list.test.ts
  packages/aws-cdk/lib/api/cxapp/cloud-assembly.ts
  packages/aws-cdk/lib/list-stacks.ts
Labels: p2, contribution/core, pr-linter/cli-integ-tested, pr/needs-maintainer-review, pr-linter/exempt-codecov

#32851 feat(rds): support Database Insights for Aurora databases
  packages/@aws-cdk-testing/framework-integ/test/aws-rds/test/integ.cluster-database-insights.js.snapshot/aws-cdk-rds-integ-cluster-database-insights.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-rds/test/integ.cluster-database-insights.js.snapshot/aws-cdk-rds-integ-cluster-database-insights.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-rds/test/integ.cluster-database-insights.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-rds/test/integ.cluster-database-insights.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-rds/test/integ.cluster-database-insights.js.snapshot/integclusterdatabaseinsightsDefaultTestDeployAssertDADC99BF.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-rds/test/integ.cluster-database-insights.js.snapshot/integclusterdatabaseinsightsDefaultTestDeployAssertDADC99BF.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-rds/test/integ.cluster-database-insights.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-rds/test/integ.cluster-database-insights.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-rds/test/integ.cluster-database-insights.ts
  packages/aws-cdk-lib/aws-rds/README.md
  packages/aws-cdk-lib/aws-rds/lib/cluster.ts
  packages/aws-cdk-lib/aws-rds/lib/validate-database-cluster-props.ts
  packages/aws-cdk-lib/aws-rds/test/cluster.test.ts
Labels: p2, feature-request, effort/medium, star-contributor

#32594 chore(lambda-python-alpha): make pipenv version a parameter for bundling
  packages/@aws-cdk/aws-lambda-python-alpha/lib/Dockerfile
Labels: p2, beginning-contributor

#30361 fix(integ-tests): http flattenResponse
  packages/@aws-cdk/integ-tests-alpha/lib/assertions/http-call.ts
  packages/@aws-cdk/integ-tests-alpha/lib/assertions/providers/lambda-handler/http.ts
  packages/@aws-cdk/integ-tests-alpha/lib/assertions/providers/lambda-handler/types.ts
  packages/@aws-cdk/integ-tests-alpha/test/assertions/providers/integ.http-api-call-assertions.js.snapshot/AssertionsTestDefaultTestDeployAssertDC0672BB.assets.json
  packages/@aws-cdk/integ-tests-alpha/test/assertions/providers/integ.http-api-call-assertions.js.snapshot/AssertionsTestDefaultTestDeployAssertDC0672BB.template.json
  packages/@aws-cdk/integ-tests-alpha/test/assertions/providers/integ.http-api-call-assertions.js.snapshot/InvokeFunctionAssertions.assets.json
  packages/@aws-cdk/integ-tests-alpha/test/assertions/providers/integ.http-api-call-assertions.js.snapshot/InvokeFunctionAssertions.template.json
  packages/@aws-cdk/integ-tests-alpha/test/assertions/providers/integ.http-api-call-assertions.js.snapshot/manifest.json
  packages/@aws-cdk/integ-tests-alpha/test/assertions/providers/integ.http-api-call-assertions.js.snapshot/tree.json
  packages/@aws-cdk/integ-tests-alpha/test/assertions/providers/integ.http-api-call-assertions.ts
  packages/@aws-cdk/integ-tests-alpha/test/assertions/providers/lambda-handler/http.test.ts
Labels: bug, p2, distinguished-contributor

#33340 fix(cli): cdk diff fails when deploy role requires tags
  packages/aws-cdk/lib/api/deployments/cloudformation.ts
  packages/aws-cdk/test/api/deployments/cloudformation-deployments.test.ts
Labels: bug, p1, effort/medium, contribution/core, pr-linter/exempt-integ-test, pr-linter/cli-integ-tested

#32807 fix(stepfunctions-tasks): `CallAwsServiceCrossRegion` doesn't work with WAIT_FOR_TASK_TOKEN
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/lambda/integ.call-aws-service-cross-region-task-token.js.snapshot/IntegTestDefaultTestDeployAssertE3E7D2A4.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/lambda/integ.call-aws-service-cross-region-task-token.js.snapshot/IntegTestDefaultTestDeployAssertE3E7D2A4.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/lambda/integ.call-aws-service-cross-region-task-token.js.snapshot/asset.50cc710fdaff3ff8ce06bf73945fa958504d45c5f63a093feddbc4e349dbac93.bundle/index.js
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/lambda/integ.call-aws-service-cross-region-task-token.js.snapshot/asset.ea123b4e391a9f352cc5dadc2250aab676981408fc6ccb0efb0d106bbd933ae3/index.js
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/lambda/integ.call-aws-service-cross-region-task-token.js.snapshot/aws-stepfunctions-aws-sdk-cross-region-task-token-integ.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/lambda/integ.call-aws-service-cross-region-task-token.js.snapshot/aws-stepfunctions-aws-sdk-cross-region-task-token-integ.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/lambda/integ.call-aws-service-cross-region-task-token.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/lambda/integ.call-aws-service-cross-region-task-token.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/lambda/integ.call-aws-service-cross-region-task-token.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/lambda/integ.call-aws-service-cross-region-task-token.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/lambda/integ.call-aws-service-cross-region-task-token.ts
  packages/aws-cdk-lib/aws-stepfunctions-tasks/README.md
  packages/aws-cdk-lib/aws-stepfunctions-tasks/lib/lambda/call-aws-service-cross-region.ts
  packages/aws-cdk-lib/aws-stepfunctions-tasks/test/lambda/call-aws-service-cross-region.test.ts
Labels: bug, p2, effort/small, star-contributor

#33346 chore: add more information to automatic comments on stale PRs
  .github/workflows/close-stale-prs.yml
Labels: p2, contribution/core

#31743 fix(msk): allow both sasl/scram and iam auth
  packages/@aws-cdk/aws-msk-alpha/README.md
  packages/@aws-cdk/aws-msk-alpha/lib/cluster.ts
  packages/@aws-cdk/aws-msk-alpha/test/__snapshots__/cluster.test.ts.snap
  packages/@aws-cdk/aws-msk-alpha/test/cluster.test.ts
  packages/@aws-cdk/aws-msk-alpha/test/integ.cluster-authentication.js.snapshot/MskClusterAuthDefaultTestDeployAssert1991B19C.assets.json
  packages/@aws-cdk/aws-msk-alpha/test/integ.cluster-authentication.js.snapshot/MskClusterAuthDefaultTestDeployAssert1991B19C.template.json
  packages/@aws-cdk/aws-msk-alpha/test/integ.cluster-authentication.js.snapshot/aws-cdk-msk-auth-integ.assets.json
  packages/@aws-cdk/aws-msk-alpha/test/integ.cluster-authentication.js.snapshot/aws-cdk-msk-auth-integ.template.json
  packages/@aws-cdk/aws-msk-alpha/test/integ.cluster-authentication.js.snapshot/cdk.out
  packages/@aws-cdk/aws-msk-alpha/test/integ.cluster-authentication.js.snapshot/integ.json
  packages/@aws-cdk/aws-msk-alpha/test/integ.cluster-authentication.js.snapshot/manifest.json
  packages/@aws-cdk/aws-msk-alpha/test/integ.cluster-authentication.js.snapshot/tree.json
  packages/@aws-cdk/aws-msk-alpha/test/integ.cluster-authentication.ts
Labels: bug, p2, effort/small, distinguished-contributor

#33349 chore: fix needs attention status update graphql api for priority board
  scripts/@aws-cdk/script-tests/prioritization/helpers/mock-data.js
  scripts/@aws-cdk/script-tests/prioritization/update-attention-status.test.js
  scripts/prioritization/update-attention-status.js
Labels: p2, contribution/core

#33363 feat: update L1 CloudFormation resource definitions
  packages/@aws-cdk/cloudformation-diff/package.json
  packages/@aws-cdk/integ-runner/package.json
  packages/aws-cdk-lib/package.json
  tools/@aws-cdk/spec2cdk/package.json
  yarn.lock
Labels: p2, dependencies, contribution/core, pr-linter/exempt-readme, pr-linter/exempt-test, auto-approve, pr-linter/exempt-integ-test

#33322 fix: do not skip bundling for stacks during CDK Import, otherwise fails
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-nodejs/test/integ.nodejs.build.images.ts
  packages/aws-cdk/lib/cli/user-configuration.ts
Labels: bug, p1, effort/medium, contribution/core, pr-linter/exempt-integ-test, pr-linter/cli-integ-tested, pr/needs-maintainer-review

#33288 chore(prlint): check PR size
  tools/@aws-cdk/prlint/README.md
  tools/@aws-cdk/prlint/constants.ts
  tools/@aws-cdk/prlint/github.ts
  tools/@aws-cdk/prlint/lint.ts
  tools/@aws-cdk/prlint/test/lint.test.ts
Labels: p2, contribution/core, pr-linter/exempt-codecov

#33362 docs(core): fix docs for Stack.account property
  packages/aws-cdk-lib/core/lib/stack.ts
Labels: p2, beginning-contributor

#33334 chore: update mergify rules to push priority PRs to priority queue
  .mergify.yml
Labels: p2, contribution/core, pr/needs-maintainer-review

#29646 feat(apigatewayv2-integrations): sqs integrations
  packages/@aws-cdk-testing/framework-integ/test/aws-apigatewayv2-integrations/test/http/integ.sqs.js.snapshot/SqsIntegrationIntegTestDefaultTestDeployAssert9AC3F75A.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-apigatewayv2-integrations/test/http/integ.sqs.js.snapshot/SqsIntegrationIntegTestDefaultTestDeployAssert9AC3F75A.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-apigatewayv2-integrations/test/http/integ.sqs.js.snapshot/asset.556f7b960c212183e2f73e1410a097107af3ccf13c8880a717edbcadd89611a4.bundle/index.js
  packages/@aws-cdk-testing/framework-integ/test/aws-apigatewayv2-integrations/test/http/integ.sqs.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-apigatewayv2-integrations/test/http/integ.sqs.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-apigatewayv2-integrations/test/http/integ.sqs.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-apigatewayv2-integrations/test/http/integ.sqs.js.snapshot/sqs-integration.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-apigatewayv2-integrations/test/http/integ.sqs.js.snapshot/sqs-integration.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-apigatewayv2-integrations/test/http/integ.sqs.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-apigatewayv2-integrations/test/http/integ.sqs.ts
  packages/aws-cdk-lib/aws-apigatewayv2-integrations/README.md
  packages/aws-cdk-lib/aws-apigatewayv2-integrations/lib/http/index.ts
  packages/aws-cdk-lib/aws-apigatewayv2-integrations/lib/http/sqs.ts
  packages/aws-cdk-lib/aws-apigatewayv2-integrations/test/http/sqs.test.ts
Labels: p2, feature-request, effort/medium, star-contributor

#32719 feat(apigateway): resource policy configuration for private API
  package.json
  packages/@aws-cdk-testing/framework-integ/test/aws-apigateway/test/integ.restapi.vpc-endpoint.js.snapshot/ApiGatewayVpcEndpointIntegDefaultTestDeployAssert55D396EF.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-apigateway/test/integ.restapi.vpc-endpoint.js.snapshot/ApiGatewayVpcEndpointIntegDefaultTestDeployAssert55D396EF.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-apigateway/test/integ.restapi.vpc-endpoint.js.snapshot/ApiGatewayVpcEndpointTestStack.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-apigateway/test/integ.restapi.vpc-endpoint.js.snapshot/ApiGatewayVpcEndpointTestStack.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-apigateway/test/integ.restapi.vpc-endpoint.js.snapshot/apigatewayvpcendpointDefaultTestDeployAssert95ED9392.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-apigateway/test/integ.restapi.vpc-endpoint.js.snapshot/asset.0620cd173f15e6874350d35d31917579f8488aac349f5c15062107ebca21d5b6.bundle/index.js
  packages/@aws-cdk-testing/framework-integ/test/aws-apigateway/test/integ.restapi.vpc-endpoint.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-apigateway/test/integ.restapi.vpc-endpoint.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-apigateway/test/integ.restapi.vpc-endpoint.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-apigateway/test/integ.restapi.vpc-endpoint.js.snapshot/test-apigateway-vpcendpoint.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-apigateway/test/integ.restapi.vpc-endpoint.js.snapshot/test-apigateway-vpcendpoint.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-apigateway/test/integ.restapi.vpc-endpoint.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-apigateway/test/integ.restapi.vpc-endpoint.ts
  packages/aws-cdk-lib/aws-apigateway/README.md
  packages/aws-cdk-lib/aws-apigateway/lib/restapi.ts
  packages/aws-cdk-lib/aws-apigateway/test/restapi.test.ts
Labels: p2, feature-request, effort/medium, distinguished-contributor

#33358 docs(appsync): fix `AppSyncAuthorizationType` enum references
  packages/aws-cdk-lib/aws-appsync/README.md
Labels: p2, star-contributor

#33359 chore: fetch lfs files for sync-workflow
  .github/workflows/sync-from-upstream.yml
Labels: p2, contribution/core

#33307 chore: enforce enums blueprint sort order
  packages/aws-cdk-lib/core/lib/analytics-data-source/enums.ts
  tools/@aws-cdk/construct-metadata-updater/lib/metadata-updater.ts
Labels: p2, contribution/core, pr-linter/analytics-metadata-change

#32985 fix(cli): old setInterval remains and is not cleared in garbage collection
  packages/aws-cdk/lib/api/garbage-collection/garbage-collector.ts
  packages/aws-cdk/lib/api/garbage-collection/progress-printer.ts
  packages/aws-cdk/test/api/garbage-collection.test.ts
Labels: p2, pr-linter/exempt-integ-test, star-contributor, pr-linter/cli-integ-tested

#33354 docs: correct code example in README of aws-cdk-lib/pipelines
  packages/aws-cdk-lib/pipelines/README.md
Labels: p2, beginning-contributor

#31490 docs(apigateway): update `RateLimitedApiKey` example code
  packages/aws-cdk-lib/aws-apigateway/README.md
  packages/aws-cdk-lib/aws-apigateway/lib/api-key.ts
Labels: p2, beginning-contributor

#33369 chore(contributing): mention calling out BREAKING CHANGES before the `---` in pr description
  CONTRIBUTING.md
Labels: p2, contribution/core

#33383 feat(assets): throw `ValidationError` instead of untyped Errors
  packages/aws-cdk-lib/.eslintrc.js
  packages/aws-cdk-lib/assets/lib/compat.ts
Labels: p2, contribution/core, pr-linter/exempt-readme, pr-linter/exempt-test, pr-linter/exempt-integ-test, pr/needs-maintainer-review

#33385 feat(pipelines): throw `ValidationError` instead of untyped Errors
  packages/aws-cdk-lib/.eslintrc.js
  packages/aws-cdk-lib/pipelines/lib/blueprint/file-set.ts
  packages/aws-cdk-lib/pipelines/lib/blueprint/shell-step.ts
  packages/aws-cdk-lib/pipelines/lib/blueprint/stack-deployment.ts
  packages/aws-cdk-lib/pipelines/lib/blueprint/stage-deployment.ts
  packages/aws-cdk-lib/pipelines/lib/blueprint/step.ts
  packages/aws-cdk-lib/pipelines/lib/codepipeline/codebuild-step.ts
  packages/aws-cdk-lib/pipelines/lib/codepipeline/codepipeline-source.ts
  packages/aws-cdk-lib/pipelines/lib/codepipeline/codepipeline.ts
  packages/aws-cdk-lib/pipelines/lib/codepipeline/confirm-permissions-broadening.ts
  packages/aws-cdk-lib/pipelines/lib/codepipeline/private/codebuild-factory.ts
  packages/aws-cdk-lib/pipelines/lib/codepipeline/private/outputs.ts
  packages/aws-cdk-lib/pipelines/lib/docker-credentials.ts
  packages/aws-cdk-lib/pipelines/lib/helpers-internal/graph.ts
  packages/aws-cdk-lib/pipelines/lib/helpers-internal/pipeline-graph.ts
  packages/aws-cdk-lib/pipelines/lib/helpers-internal/pipeline-queries.ts
  packages/aws-cdk-lib/pipelines/lib/helpers-internal/step-output.ts
  packages/aws-cdk-lib/pipelines/lib/helpers-internal/toposort.ts
  packages/aws-cdk-lib/pipelines/lib/main/pipeline-base.ts
  packages/aws-cdk-lib/pipelines/lib/private/asset-manifest.ts
  packages/aws-cdk-lib/pipelines/lib/private/construct-internals.ts
  packages/aws-cdk-lib/pipelines/lib/private/javascript.ts
  packages/aws-cdk-lib/pipelines/lib/private/toposort.ts
Labels: p2, contribution/core, pr-linter/exempt-readme, pr-linter/exempt-test, pr-linter/exempt-integ-test, pr/needs-maintainer-review

#33386 feat(appconfig): throw `ValidationError` instead of untyped Errors
  packages/aws-cdk-lib/.eslintrc.js
  packages/aws-cdk-lib/aws-appconfig/lib/application.ts
  packages/aws-cdk-lib/aws-appconfig/lib/deployment-strategy.ts
  packages/aws-cdk-lib/aws-appconfig/lib/environment.ts
  packages/aws-cdk-lib/aws-appconfig/lib/extension.ts
Labels: p2, contribution/core, pr-linter/exempt-readme, pr-linter/exempt-test, pr-linter/exempt-integ-test

#33389 feat(batch): throw `ValidationError` instead of untyped Errors
  packages/aws-cdk-lib/.eslintrc.js
  packages/aws-cdk-lib/aws-batch/lib/ecs-container-definition.ts
  packages/aws-cdk-lib/aws-batch/lib/eks-job-definition.ts
  packages/aws-cdk-lib/aws-batch/lib/job-queue.ts
  packages/aws-cdk-lib/aws-batch/lib/linux-parameters.ts
  packages/aws-cdk-lib/aws-batch/lib/managed-compute-environment.ts
Labels: p2, contribution/core, pr-linter/exempt-readme, pr-linter/exempt-test, pr-linter/exempt-integ-test, pr-linter/exempt-codecov

#33381 chore(cli): tests involving promptly don't work on GitHub Actions
  packages/aws-cdk/test/_helpers/prompts.ts
  packages/aws-cdk/test/toolkit/cli-io-host.test.ts
Labels: p2, contribution/core, pr-linter/cli-integ-tested

#33371 chore(rds): support 15.00.4415.2.v1 and 16.00.4175.1.v1 engine versions for SQL Server
  packages/aws-cdk-lib/aws-rds/lib/instance-engine.ts
Labels: p2, pr/needs-community-review, pr-linter/exempt-integ-test, distinguished-contributor, pr-linter/cli-integ-tested

#33398 fix(cli): do not print credentials refreshed by plugins
  packages/aws-cdk/lib/api/aws-auth/credential-plugins.ts
Labels: bug, p0, effort/medium, contribution/core, pr-linter/exempt-readme, pr-linter/exempt-test, pr-linter/exempt-integ-test, pr-linter/cli-integ-tested, pr-linter/exempt-codecov

#33402 chore: retain existing status in the priority board on github action trigger
  scripts/@aws-cdk/script-tests/prioritization/assign-priority.test.js
  scripts/@aws-cdk/script-tests/prioritization/helpers/mock-data.js
  scripts/prioritization/README.md
  scripts/prioritization/assign-bug-priority.js
  scripts/prioritization/assign-priority.js
  scripts/prioritization/assign-r2-priority.js
  scripts/prioritization/assign-r5-priority.js
  scripts/prioritization/project-api.js
Labels: p2, contribution/core

#33401 fix(opensearchservice): wrong iops limit checks
  packages/aws-cdk-lib/aws-opensearchservice/lib/domain.ts
  packages/aws-cdk-lib/aws-opensearchservice/test/domain.test.ts
Labels: bug, p1, effort/medium, contribution/core, pr-linter/exempt-readme, pr-linter/exempt-test, pr-linter/exempt-integ-test

#33407 chore(release): 2.178.2
  CHANGELOG.v2.alpha.md
  CHANGELOG.v2.md
  packages/aws-cdk/lib/api/aws-auth/credential-plugins.ts
  version.v2.json
Labels: p2, contribution/core, pr/no-squash, pr-linter/cli-integ-tested, pr/needs-maintainer-review

#33387 feat(backup): throw `ValidationError` instead of untyped Errors
  packages/aws-cdk-lib/.eslintrc.js
  packages/aws-cdk-lib/aws-backup/lib/plan.ts
  packages/aws-cdk-lib/aws-backup/lib/rule.ts
  packages/aws-cdk-lib/aws-backup/lib/vault.ts
Labels: p2, contribution/core, pr-linter/exempt-readme, pr-linter/exempt-test, pr-linter/exempt-integ-test, pr-linter/exempt-codecov

#33388 feat(autoscaling): throw `ValidationError` instead of untyped Errors
  packages/aws-cdk-lib/.eslintrc.js
  packages/aws-cdk-lib/aws-autoscaling-common/lib/interval-utils.ts
  packages/aws-cdk-lib/aws-autoscaling/lib/auto-scaling-group.ts
  packages/aws-cdk-lib/aws-autoscaling/lib/lifecycle-hook.ts
  packages/aws-cdk-lib/aws-autoscaling/lib/schedule.ts
  packages/aws-cdk-lib/aws-autoscaling/lib/scheduled-action.ts
  packages/aws-cdk-lib/aws-autoscaling/lib/step-scaling-action.ts
  packages/aws-cdk-lib/aws-autoscaling/lib/step-scaling-policy.ts
  packages/aws-cdk-lib/aws-autoscaling/lib/target-tracking-scaling-policy.ts
  packages/aws-cdk-lib/aws-autoscaling/lib/volume.ts
  packages/aws-cdk-lib/aws-autoscaling/lib/warm-pool.ts
Labels: p2, contribution/core, pr-linter/exempt-readme, pr-linter/exempt-test, pr-linter/exempt-integ-test, pr-linter/exempt-codecov

#33409 chore: temporarily skip sam test to release the patch
  packages/@aws-cdk-testing/cli-integ/resources/cli-regression-patches/v2.178.1/NOTES.md
  packages/@aws-cdk-testing/cli-integ/resources/cli-regression-patches/v2.178.1/skip-tests.txt
  packages/@aws-cdk-testing/cli-integ/tests/cli-integ-tests/cli.integtest.ts
Labels: p2, contribution/core

#33390 feat(cx-api): throw `CloudAssemblyError` instead of untyped Errors
  packages/aws-cdk-lib/.eslintrc.js
  packages/aws-cdk-lib/core/lib/errors.ts
  packages/aws-cdk-lib/cx-api/lib/artifacts/asset-manifest-artifact.ts
  packages/aws-cdk-lib/cx-api/lib/artifacts/cloudformation-artifact.ts
  packages/aws-cdk-lib/cx-api/lib/artifacts/tree-cloud-artifact.ts
  packages/aws-cdk-lib/cx-api/lib/cloud-artifact.ts
  packages/aws-cdk-lib/cx-api/lib/cloud-assembly.ts
  packages/aws-cdk-lib/cx-api/lib/environment.ts
  packages/aws-cdk-lib/cx-api/lib/features.ts
  packages/aws-cdk-lib/cx-api/lib/private/error.ts
  packages/aws-cdk-lib/cx-api/lib/toposort.ts
Labels: p2, contribution/core, pr-linter/exempt-readme, pr-linter/exempt-test, pr-linter/exempt-integ-test, pr-linter/exempt-codecov

#33391 feat(cloudformation-include): throw `ValidationError` instead of untyped Errors
  packages/aws-cdk-lib/.eslintrc.js
  packages/aws-cdk-lib/cloudformation-include/lib/cfn-include.ts
Labels: p2, contribution/core, pr-linter/exempt-readme, pr-linter/exempt-test, pr-linter/exempt-integ-test

#33411 chore(rds): add Oracle engine versions released in January 2025 Update
  packages/aws-cdk-lib/aws-rds/lib/instance-engine.ts
Labels: p2, pr/needs-community-review, distinguished-contributor

#33372 test(cli): cdk import works when used on a stack containing a nodejs lambda function
  packages/@aws-cdk-testing/cli-integ/resources/cdk-apps/app/app.js
  packages/@aws-cdk-testing/cli-integ/tests/cli-integ-tests/cli.integtest.ts
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-nodejs/test/integ.nodejs.build.images.ts
Labels: p2, contribution/core, pr-linter/cli-integ-tested

#33382 feat(assertions): throw typed errors
  packages/@aws-cdk/integ-tests-alpha/test/assertions/providers/lambda-handler/base.test.ts
  packages/aws-cdk-lib/.eslintrc.js
  packages/aws-cdk-lib/assertions/lib/annotations.ts
  packages/aws-cdk-lib/assertions/lib/capture.ts
  packages/aws-cdk-lib/assertions/lib/match.ts
  packages/aws-cdk-lib/assertions/lib/private/cyclic.ts
  packages/aws-cdk-lib/assertions/lib/private/error.ts
  packages/aws-cdk-lib/assertions/lib/tags.ts
  packages/aws-cdk-lib/assertions/lib/template.ts
  packages/aws-cdk-lib/core/lib/errors.ts
Labels: p2, contribution/core, pr-linter/exempt-readme, pr-linter/exempt-test, pr-linter/exempt-integ-test, pr-linter/exempt-codecov

#33419 chore(merge-back): 2.178.2
  CHANGELOG.v2.alpha.md
  CHANGELOG.v2.md
  packages/@aws-cdk-testing/cli-integ/resources/cli-regression-patches/v2.178.1/NOTES.md
  packages/@aws-cdk-testing/cli-integ/resources/cli-regression-patches/v2.178.1/skip-tests.txt
  packages/@aws-cdk-testing/cli-integ/tests/cli-integ-tests/cli.integtest.ts
  version.v2.json
Labels: p2, pr/needs-community-review, pr/no-squash, auto-approve

#33415 chore(deps): update cdk-assets
  packages/@aws-cdk/integ-runner/THIRD_PARTY_LICENSES
  packages/@aws-cdk/integ-runner/package.json
  packages/@aws-cdk/toolkit/package.json
  packages/@aws-cdk/toolkit/test/_fixtures/stack-with-asset/asset/index.ts
  packages/@aws-cdk/toolkit/test/_fixtures/stack-with-asset/index.ts
  packages/aws-cdk/THIRD_PARTY_LICENSES
  packages/aws-cdk/package.json
  yarn.lock
Labels: bug, p1, effort/medium, contribution/core

#33421 chore(cli): update documentation for generated files
  packages/aws-cdk/lib/cli/convert-to-user-input.ts
  packages/aws-cdk/lib/cli/parse-command-line-arguments.ts
  packages/aws-cdk/lib/cli/user-input.ts
  tools/@aws-cdk/user-input-gen/lib/convert-to-user-input-gen.ts
  tools/@aws-cdk/user-input-gen/lib/user-input-gen.ts
  tools/@aws-cdk/user-input-gen/lib/util.ts
  tools/@aws-cdk/user-input-gen/lib/yargs-gen.ts
  tools/@aws-cdk/user-input-gen/test/convert-to-user-input-gen.test.ts
  tools/@aws-cdk/user-input-gen/test/user-input-gen.test.ts
  tools/@aws-cdk/user-input-gen/test/yargs-gen.test.ts
Labels: p2, contribution/core, pr-linter/cli-integ-tested

#32344 feat(events-targets): allow all ECS TaskOverrides
  packages/@aws-cdk-testing/framework-integ/test/aws-events-targets/test/ecs/integ.event-ec2-task.js.snapshot/EcsTestDefaultTestDeployAssert8B2741C4.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-events-targets/test/ecs/integ.event-ec2-task.js.snapshot/aws-ecs-integ-ecs.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-events-targets/test/ecs/integ.event-ec2-task.js.snapshot/aws-ecs-integ-ecs.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-events-targets/test/ecs/integ.event-ec2-task.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-events-targets/test/ecs/integ.event-ec2-task.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-events-targets/test/ecs/integ.event-ec2-task.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-events-targets/test/ecs/integ.event-ec2-task.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-events-targets/test/ecs/integ.event-ec2-task.ts
  packages/@aws-cdk-testing/framework-integ/test/aws-events-targets/test/ecs/integ.event-fargate-task.js.snapshot/EcsFargateTestDefaultTestDeployAssert36341BFB.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-events-targets/test/ecs/integ.event-fargate-task.js.snapshot/aws-ecs-integ-fargate.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-events-targets/test/ecs/integ.event-fargate-task.js.snapshot/aws-ecs-integ-fargate.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-events-targets/test/ecs/integ.event-fargate-task.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-events-targets/test/ecs/integ.event-fargate-task.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-events-targets/test/ecs/integ.event-fargate-task.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-events-targets/test/ecs/integ.event-fargate-task.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-events-targets/test/ecs/integ.event-fargate-task.ts
  packages/aws-cdk-lib/aws-events-targets/README.md
  packages/aws-cdk-lib/aws-events-targets/lib/ecs-task-properties.ts
  packages/aws-cdk-lib/aws-events-targets/lib/ecs-task.ts
  packages/aws-cdk-lib/aws-events-targets/test/ecs/event-rule-target.test.ts
Labels: p2, feature-request, effort/small, pr/needs-community-review, admired-contributor

#33423 fix(stepfunctions): support assign property and fix Catch state issue
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions/test/integ.map-with-catch.js.snapshot/DistributedMapCatchDefaultTestDeployAssert25965E29.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions/test/integ.map-with-catch.js.snapshot/DistributedMapCatchDefaultTestDeployAssert25965E29.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions/test/integ.map-with-catch.js.snapshot/asset.bfcf4228d6660f50e81f19efdb64c6388dda6796296eb239decdff1dbc2f4981.bundle/index.js
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions/test/integ.map-with-catch.js.snapshot/aws-stepfunctions-map-with-catch.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions/test/integ.map-with-catch.js.snapshot/aws-stepfunctions-map-with-catch.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions/test/integ.map-with-catch.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions/test/integ.map-with-catch.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions/test/integ.map-with-catch.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions/test/integ.map-with-catch.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions/test/integ.map-with-catch.ts
  packages/aws-cdk-lib/aws-efs/lib/efs-file-system.ts
  packages/aws-cdk-lib/aws-stepfunctions/lib/states/map-base.ts
  packages/aws-cdk-lib/aws-stepfunctions/lib/states/state.ts
  packages/aws-cdk-lib/aws-stepfunctions/lib/types.ts
  packages/aws-cdk-lib/aws-stepfunctions/test/map.test.ts
Labels: bug, p1, effort/medium, contribution/core, pr-linter/exempt-readme

#33425 chore(cli-integ): restore sam test
  packages/@aws-cdk-testing/cli-integ/tests/cli-integ-tests/cli.integtest.ts
Labels: p2, contribution/core, pr-linter/cli-integ-tested, pr/needs-maintainer-review

#33427 chore(toolkit): tests don't exit
  packages/@aws-cdk/toolkit/test/actions/watch.test.ts
Labels: p2, contribution/core

#33429 chore(toolkit): randomize tests
  packages/@aws-cdk/toolkit/jest.config.js
  packages/@aws-cdk/toolkit/test/actions/destroy.test.ts
  packages/@aws-cdk/toolkit/test/actions/rollback.test.ts
Labels: p2, contribution/core

#33412 refactor(cli): resource-import uses IoHost
  packages/@aws-cdk/toolkit/lib/actions/deploy/index.ts
  packages/@aws-cdk/toolkit/lib/api/aws-cdk.ts
  packages/@aws-cdk/toolkit/lib/api/io/private/codes.ts
  packages/@aws-cdk/toolkit/lib/toolkit/toolkit.ts
  packages/aws-cdk/lib/api/resource-import/importer.ts
  packages/aws-cdk/lib/api/resource-import/index.ts
  packages/aws-cdk/lib/api/resource-import/migrator.ts
  packages/aws-cdk/lib/cli/cdk-toolkit.ts
  packages/aws-cdk/lib/cli/cli.ts
  packages/aws-cdk/lib/cli/messages.ts
  packages/aws-cdk/test/api/resource-import/import.test.ts
Labels: p2, contribution/core, pr-linter/cli-integ-tested, pr/needs-maintainer-review, pr-linter/exempt-codecov

#33433 chore(toolkit): remove accidentally added test infra
  packages/@aws-cdk/toolkit/test/_fixtures/stack-with-asset/asset/index.ts
  packages/@aws-cdk/toolkit/test/_fixtures/stack-with-asset/index.ts
Labels: p2, contribution/core

#33424 docs(appsync): clarify the structure of apiKeys object
  packages/aws-cdk-lib/aws-appsync/lib/eventapi.ts
Labels: p2, pr/needs-community-review, star-contributor

#32369 feat(cognito): choice-based authentication (passwordless sign-in / passkey sign-in)
  packages/@aws-cdk-testing/framework-integ/test/aws-cognito/test/integ.user-pool-passwordless.js.snapshot/IntegTestDefaultTestDeployAssertE3E7D2A4.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-cognito/test/integ.user-pool-passwordless.js.snapshot/IntegTestDefaultTestDeployAssertE3E7D2A4.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-cognito/test/integ.user-pool-passwordless.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-cognito/test/integ.user-pool-passwordless.js.snapshot/integ-user-pool-passwordless.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-cognito/test/integ.user-pool-passwordless.js.snapshot/integ-user-pool-passwordless.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-cognito/test/integ.user-pool-passwordless.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-cognito/test/integ.user-pool-passwordless.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-cognito/test/integ.user-pool-passwordless.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-cognito/test/integ.user-pool-passwordless.ts
  packages/aws-cdk-lib/aws-cognito/README.md
  packages/aws-cdk-lib/aws-cognito/lib/user-pool.ts
  packages/aws-cdk-lib/aws-cognito/test/user-pool.test.ts
Labels: p2, feature-request, effort/medium, admired-contributor

#33438 feat(cloudfront): throw `ValidationErrors` instead of untyped Errors
  packages/aws-cdk-lib/.eslintrc.js
  packages/aws-cdk-lib/aws-cloudfront-origins/lib/function-url-origin.ts
  packages/aws-cdk-lib/aws-cloudfront-origins/lib/origin-group.ts
  packages/aws-cdk-lib/aws-cloudfront-origins/lib/private/utils.ts
  packages/aws-cdk-lib/aws-cloudfront-origins/lib/s3-bucket-origin.ts
  packages/aws-cdk-lib/aws-cloudfront/lib/cache-policy.ts
  packages/aws-cdk-lib/aws-cloudfront/lib/distribution.ts
  packages/aws-cdk-lib/aws-cloudfront/lib/experimental/edge-function.ts
  packages/aws-cdk-lib/aws-cloudfront/lib/function.ts
  packages/aws-cdk-lib/aws-cloudfront/lib/geo-restriction.ts
  packages/aws-cdk-lib/aws-cloudfront/lib/key-value-store.ts
  packages/aws-cdk-lib/aws-cloudfront/lib/origin-request-policy.ts
  packages/aws-cdk-lib/aws-cloudfront/lib/origin.ts
  packages/aws-cdk-lib/aws-cloudfront/lib/private/cache-behavior.ts
  packages/aws-cdk-lib/aws-cloudfront/lib/public-key.ts
  packages/aws-cdk-lib/aws-cloudfront/lib/realtime-log-config.ts
  packages/aws-cdk-lib/aws-cloudfront/lib/response-headers-policy.ts
  packages/aws-cdk-lib/aws-cloudfront/lib/web-distribution.ts
Labels: contribution/core, pr-linter/exempt-readme, pr-linter/exempt-test, pr-linter/exempt-integ-test, pr/needs-maintainer-review

#33439 feat(chatbot): throw `ValidationError` instead of untyped Error
  packages/aws-cdk-lib/.eslintrc.js
  packages/aws-cdk-lib/aws-chatbot/lib/slack-channel-configuration.ts
Labels: p2, contribution/core, pr-linter/exempt-readme, pr-linter/exempt-test, pr-linter/exempt-integ-test

#33370 feat(ivs): support Multitrack Video
  packages/@aws-cdk/aws-ivs-alpha/README.md
  packages/@aws-cdk/aws-ivs-alpha/lib/channel.ts
  packages/@aws-cdk/aws-ivs-alpha/test/integ.ivs-multitrack-video.js.snapshot/aws-cdk-ivs-multitarck-video.assets.json
  packages/@aws-cdk/aws-ivs-alpha/test/integ.ivs-multitrack-video.js.snapshot/aws-cdk-ivs-multitarck-video.template.json
  packages/@aws-cdk/aws-ivs-alpha/test/integ.ivs-multitrack-video.js.snapshot/awscdkivsmultitarckvideotestDefaultTestDeployAssert4DE3589F.assets.json
  packages/@aws-cdk/aws-ivs-alpha/test/integ.ivs-multitrack-video.js.snapshot/awscdkivsmultitarckvideotestDefaultTestDeployAssert4DE3589F.template.json
  packages/@aws-cdk/aws-ivs-alpha/test/integ.ivs-multitrack-video.js.snapshot/cdk.out
  packages/@aws-cdk/aws-ivs-alpha/test/integ.ivs-multitrack-video.js.snapshot/integ.json
  packages/@aws-cdk/aws-ivs-alpha/test/integ.ivs-multitrack-video.js.snapshot/manifest.json
  packages/@aws-cdk/aws-ivs-alpha/test/integ.ivs-multitrack-video.js.snapshot/tree.json
  packages/@aws-cdk/aws-ivs-alpha/test/integ.ivs-multitrack-video.ts
  packages/@aws-cdk/aws-ivs-alpha/test/ivs.test.ts
Labels: p2, distinguished-contributor

#33442 chore: update workflows to use sha instead of ref
  .github/workflows/analytics-metadata-updater.yml
  .github/workflows/lambda-runtime-tests.yml
  .github/workflows/request-cli-integ-test.yml
Labels: p2, contribution/core

#33445 feat: update L1 CloudFormation resource definitions
  packages/@aws-cdk/cloudformation-diff/package.json
  packages/@aws-cdk/integ-runner/package.json
  packages/aws-cdk-lib/package.json
  tools/@aws-cdk/spec2cdk/package.json
  yarn.lock
Labels: p2, dependencies, contribution/core, pr-linter/exempt-readme, pr-linter/exempt-test, auto-approve, pr-linter/exempt-integ-test

#33008 docs(cdk-lib): fix typos
  packages/@aws-cdk/aws-lambda-python-alpha/lib/function.ts
  packages/aws-cdk-lib/aws-ec2/lib/security-group.ts
  packages/aws-cdk-lib/aws-ecs/lib/external/external-service.ts
  packages/aws-cdk-lib/aws-ecs/lib/external/external-task-definition.ts
  packages/aws-cdk-lib/aws-s3/README.md
  packages/aws-cdk-lib/aws-s3/lib/bucket.ts
  packages/aws-cdk-lib/aws-s3/test/notification.test.ts
  packages/aws-cdk-lib/cx-api/lib/features.ts
Labels: p2, admired-contributor

#33449 fix(cli): init templates still assume the same versions
  packages/aws-cdk/lib/cli/cli.ts
  packages/aws-cdk/lib/cli/util/yargs-helpers.ts
  packages/aws-cdk/lib/cli/version.ts
  packages/aws-cdk/lib/commands/doctor.ts
  packages/aws-cdk/lib/init-templates/app/javascript/package.json
  packages/aws-cdk/lib/init-templates/app/typescript/package.json
  packages/aws-cdk/lib/init-templates/sample-app/javascript/package.json
  packages/aws-cdk/lib/init-templates/sample-app/typescript/package.json
  packages/aws-cdk/lib/init.ts
  packages/aws-cdk/test/init.test.ts
Labels: p2, contribution/core, pr-linter/exempt-integ-test, pr-linter/cli-integ-tested, pr/needs-maintainer-review

#33450 chore(cli-integ): make the version of `cli-lib-alpha` switchable
  packages/@aws-cdk-testing/cli-integ/lib/with-cli-lib.ts
Labels: p2, contribution/core

#30741 feat(logs): support regex patterns for JSON Metrics filters
  packages/@aws-cdk-testing/framework-integ/test/aws-logs/test/integ.metricfilter.lit.js.snapshot/aws-cdk-metricfilter-integ.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-logs/test/integ.metricfilter.lit.ts
  packages/aws-cdk-lib/aws-logs/README.md
  packages/aws-cdk-lib/aws-logs/lib/pattern.ts
  packages/aws-cdk-lib/aws-logs/test/integ.metricfilter.lit.ts
  packages/aws-cdk-lib/aws-logs/test/pattern.test.ts
Labels: p2, feature-request, effort/medium, beginning-contributor, pr-linter/do-not-close

#33252 feat(stepfunctions-tasks): allow region override in call-rest-api task
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/apigateway/integ.call-rest-api-cross-region.js.snapshot/CallRestApiInteg-ApiStack.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/apigateway/integ.call-rest-api-cross-region.js.snapshot/CallRestApiInteg-ApiStack.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/apigateway/integ.call-rest-api-cross-region.js.snapshot/CallRestApiInteg-SfnStack.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/apigateway/integ.call-rest-api-cross-region.js.snapshot/CallRestApiInteg-SfnStack.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/apigateway/integ.call-rest-api-cross-region.js.snapshot/asset.bbfb567dc956ce71e67ac1f96589821990e2ca48307b93a577bbb345d2de441b/__entrypoint__.js
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/apigateway/integ.call-rest-api-cross-region.js.snapshot/asset.bbfb567dc956ce71e67ac1f96589821990e2ca48307b93a577bbb345d2de441b/index.js
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/apigateway/integ.call-rest-api-cross-region.js.snapshot/asset.d6fa38886a871b64de769ec5016af90a071e6429aa8e7de84f595e4e2462e17d/__entrypoint__.js
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/apigateway/integ.call-rest-api-cross-region.js.snapshot/asset.d6fa38886a871b64de769ec5016af90a071e6429aa8e7de84f595e4e2462e17d/index.js
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/apigateway/integ.call-rest-api-cross-region.js.snapshot/callrestapicrossregionDefaultTestDeployAssert2A1021D3.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/apigateway/integ.call-rest-api-cross-region.js.snapshot/callrestapicrossregionDefaultTestDeployAssert2A1021D3.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/apigateway/integ.call-rest-api-cross-region.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/apigateway/integ.call-rest-api-cross-region.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/apigateway/integ.call-rest-api-cross-region.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/apigateway/integ.call-rest-api-cross-region.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/apigateway/integ.call-rest-api-cross-region.ts
  packages/aws-cdk-lib/aws-stepfunctions-tasks/README.md
  packages/aws-cdk-lib/aws-stepfunctions-tasks/lib/apigateway/call-rest-api.ts
  packages/aws-cdk-lib/aws-stepfunctions-tasks/test/apigateway/call-rest-api.test.ts
Labels: p2, beginning-contributor, pr/reviewer-clarification-requested

#33440 feat(certificatemanager): throw `ValidationErrors` instead of untyped Errors
  packages/aws-cdk-lib/.eslintrc.js
  packages/aws-cdk-lib/aws-certificatemanager/lib/certificate.ts
  packages/aws-cdk-lib/aws-certificatemanager/lib/dns-validated-certificate.ts
Labels: p2, contribution/core, pr-linter/exempt-readme, pr-linter/exempt-test, pr-linter/exempt-integ-test

#33454 chore: fix yarn upgrade causing dependency incompatibility
  package.json
  tools/@aws-cdk/cdk-build-tools/package.json
Labels: p2, contribution/core

#33457 chore: fix workflows
  .github/workflows/analytics-metadata-updater.yml
  .github/workflows/lambda-runtime-tests.yml
Labels: p2, contribution/core

#33468 chore: install git lfs in dev container
  .devcontainer/Dockerfile
Labels: bug, p2, effort/medium, repeat-contributor

#33475 feat: update L1 CloudFormation resource definitions
  packages/@aws-cdk/cloudformation-diff/package.json
  packages/@aws-cdk/integ-runner/package.json
  packages/aws-cdk-lib/package.json
  tools/@aws-cdk/spec2cdk/package.json
  yarn.lock
Labels: p2, dependencies, contribution/core, pr-linter/exempt-readme, pr-linter/exempt-test, auto-approve, pr-linter/exempt-integ-test

#33476 feat: update L1 CloudFormation resource definitions
  packages/@aws-cdk/cloudformation-diff/package.json
  packages/@aws-cdk/integ-runner/package.json
  packages/aws-cdk-lib/package.json
  tools/@aws-cdk/spec2cdk/package.json
  yarn.lock
Labels: p2, dependencies, contribution/core, pr-linter/exempt-readme, pr-linter/exempt-test, auto-approve, pr-linter/exempt-integ-test

#33480 feat: update L1 CloudFormation resource definitions
  packages/@aws-cdk/cloudformation-diff/package.json
  packages/@aws-cdk/integ-runner/package.json
  packages/aws-cdk-lib/package.json
  tools/@aws-cdk/spec2cdk/package.json
  yarn.lock
Labels: p2, dependencies, contribution/core, pr-linter/exempt-readme, pr-linter/exempt-test, auto-approve, pr-linter/exempt-integ-test

#33455 feat(cloudtrail): throw `ValidationErrors` instead of untyped Errors
  packages/aws-cdk-lib/.eslintrc.js
  packages/aws-cdk-lib/aws-cloudtrail/lib/cloudtrail.ts
Labels: p2, contribution/core, pr-linter/exempt-readme, pr-linter/exempt-test, pr-linter/exempt-integ-test

#33481 chore(spec): current cfnspec contains breaking changes we are not ready to merge yet
  package.json
  packages/@aws-cdk/cloudformation-diff/package.json
  packages/@aws-cdk/integ-runner/package.json
  packages/aws-cdk-lib/package.json
  tools/@aws-cdk/spec2cdk/package.json
  tools/@aws-cdk/spec2cdk/temporary-schemas/us-east-1/aws-ivs-channel.json
  yarn.lock
Labels: p2, contribution/core

#33456 feat(cloudwatch): throw `ValidationErrors` instead of untyped Errors
  packages/aws-cdk-lib/.eslintrc.js
  packages/aws-cdk-lib/aws-cloudwatch/lib/alarm.ts
  packages/aws-cdk-lib/aws-cloudwatch/lib/composite-alarm.ts
  packages/aws-cdk-lib/aws-cloudwatch/lib/dashboard.ts
  packages/aws-cdk-lib/aws-cloudwatch/lib/graph.ts
  packages/aws-cdk-lib/aws-cloudwatch/lib/log-query.ts
  packages/aws-cdk-lib/aws-cloudwatch/lib/metric.ts
  packages/aws-cdk-lib/aws-cloudwatch/lib/private/metric-util.ts
  packages/aws-cdk-lib/aws-cloudwatch/lib/private/rendering.ts
  packages/aws-cdk-lib/aws-cloudwatch/lib/stats.ts
  packages/aws-cdk-lib/aws-cloudwatch/lib/variable.ts
  packages/aws-cdk-lib/aws-cloudwatch/lib/widget.ts
Labels: p2, contribution/core, pr-linter/exempt-readme, pr-linter/exempt-test, pr-linter/exempt-integ-test

#33379 docs: update CDK Roadmap - 2/2025
  ROADMAP.md
Labels: p2, contribution/core, pr-linter/exemption-requested

#33484 chore(merge-back): 2.179.0
  CHANGELOG.v2.alpha.md
  CHANGELOG.v2.md
  packages/aws-cdk-lib/aws-apigateway/lib/restapi.ts
  packages/aws-cdk-lib/core/lib/analytics-data-source/classes.ts
  packages/aws-cdk-lib/core/lib/analytics-data-source/enums.ts
  version.v2.json
Labels: p2, pr/needs-community-review, pr/no-squash, auto-approve

#33485 chore: remove service spec yarn resolutions
  package.json
Labels: p2, contribution/core

#33488 chore: remove packageManager from package.json
  package.json
Labels: p2, pr/needs-community-review, distinguished-contributor

#30816 fix(stepfunctions): disabling logging still requires LogGroup
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions/test/integ.state-machine-logging.js.snapshot/IntegTestDefaultTestDeployAssertE3E7D2A4.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions/test/integ.state-machine-logging.js.snapshot/IntegTestDefaultTestDeployAssertE3E7D2A4.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions/test/integ.state-machine-logging.js.snapshot/aws-stepfunctions-integ.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions/test/integ.state-machine-logging.js.snapshot/aws-stepfunctions-integ.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions/test/integ.state-machine-logging.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions/test/integ.state-machine-logging.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions/test/integ.state-machine-logging.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions/test/integ.state-machine-logging.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions/test/integ.state-machine-logging.ts
  packages/aws-cdk-lib/aws-stepfunctions/lib/state-machine.ts
  packages/aws-cdk-lib/aws-stepfunctions/test/state-machine.test.ts
Labels: bug, p2, effort/small, admired-contributor

#33459 chore(s3): update annotation phrase of addReplicationPolicy()
  packages/aws-cdk-lib/aws-s3/lib/bucket.ts
Labels: p2, distinguished-contributor, pr/needs-maintainer-review

#33404 fix(stepfunctions): various JSONata query language fix
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions/test/integ.distribution-map-with-result-writer-jsonata.js.snapshot/DistributedMapJSONATADefaultTestDeployAssertF1573CB9.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions/test/integ.distribution-map-with-result-writer-jsonata.js.snapshot/DistributedMapJSONATADefaultTestDeployAssertF1573CB9.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions/test/integ.distribution-map-with-result-writer-jsonata.js.snapshot/asset.bfcf4228d6660f50e81f19efdb64c6388dda6796296eb239decdff1dbc2f4981.bundle/index.js
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions/test/integ.distribution-map-with-result-writer-jsonata.js.snapshot/aws-stepfunctions-map-with-result-writer.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions/test/integ.distribution-map-with-result-writer-jsonata.js.snapshot/aws-stepfunctions-map-with-result-writer.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions/test/integ.distribution-map-with-result-writer-jsonata.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions/test/integ.distribution-map-with-result-writer-jsonata.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions/test/integ.distribution-map-with-result-writer-jsonata.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions/test/integ.distribution-map-with-result-writer-jsonata.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions/test/integ.distribution-map-with-result-writer-jsonata.ts
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions/test/integ.map-with-catch.js.snapshot/DistributedMapCatchDefaultTestDeployAssert25965E29.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions/test/integ.map-with-catch.js.snapshot/DistributedMapCatchDefaultTestDeployAssert25965E29.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions/test/integ.map-with-catch.js.snapshot/asset.bfcf4228d6660f50e81f19efdb64c6388dda6796296eb239decdff1dbc2f4981.bundle/index.js
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions/test/integ.map-with-catch.js.snapshot/aws-stepfunctions-map-with-catch.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions/test/integ.map-with-catch.js.snapshot/aws-stepfunctions-map-with-catch.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions/test/integ.map-with-catch.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions/test/integ.map-with-catch.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions/test/integ.map-with-catch.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions/test/integ.map-with-catch.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions/test/integ.map-with-catch.ts
  packages/aws-cdk-lib/aws-efs/lib/efs-file-system.ts
  packages/aws-cdk-lib/aws-stepfunctions/README.md
  packages/aws-cdk-lib/aws-stepfunctions/lib/states/distributed-map.ts
  packages/aws-cdk-lib/aws-stepfunctions/lib/states/distributed-map/item-reader.ts
  packages/aws-cdk-lib/aws-stepfunctions/lib/states/distributed-map/result-writer.ts
  packages/aws-cdk-lib/aws-stepfunctions/lib/states/map-base.ts
  packages/aws-cdk-lib/aws-stepfunctions/lib/states/state.ts
  packages/aws-cdk-lib/aws-stepfunctions/lib/types.ts
  packages/aws-cdk-lib/aws-stepfunctions/test/distributed-map.test.ts
  packages/aws-cdk-lib/aws-stepfunctions/test/map.test.ts
Labels: bug, p1, effort/medium, pr/do-not-merge, contribution/core

#33499 chore(ec2): add Windows Server 2025 to WindowsVersion enum
  packages/aws-cdk-lib/aws-ec2/lib/windows-versions.ts
Labels: p2, feature-request, beginning-contributor

#33472 feat(codepipeline-actions): support `timeout` for `ManualApprovalAction`
  packages/@aws-cdk-testing/framework-integ/test/aws-codepipeline-actions/test/integ.pipeline-manual-approval.js.snapshot/aws-cdk-codepipeline-manual-approval.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-codepipeline-actions/test/integ.pipeline-manual-approval.js.snapshot/aws-cdk-codepipeline-manual-approval.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-codepipeline-actions/test/integ.pipeline-manual-approval.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-codepipeline-actions/test/integ.pipeline-manual-approval.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-codepipeline-actions/test/integ.pipeline-manual-approval.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-codepipeline-actions/test/integ.pipeline-manual-approval.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-codepipeline-actions/test/integ.pipeline-manual-approval.ts
  packages/aws-cdk-lib/aws-codepipeline-actions/README.md
  packages/aws-cdk-lib/aws-codepipeline-actions/lib/manual-approval-action.ts
  packages/aws-cdk-lib/aws-codepipeline-actions/test/manual-approval.test.ts
  packages/aws-cdk-lib/aws-codepipeline/lib/action.ts
  packages/aws-cdk-lib/aws-codepipeline/lib/private/full-action-descriptor.ts
  packages/aws-cdk-lib/aws-codepipeline/lib/private/stage.ts
Labels: p2, feature-request, distinguished-contributor

#33462 fix(logs): `DataProtectionPolicy` template key must be PascalCase
  packages/@aws-cdk-testing/framework-integ/test/aws-logs/test/integ.log-group.js.snapshot/LogGroupIntegDefaultTestDeployAssertA9999A13.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-logs/test/integ.log-group.js.snapshot/aws-cdk-log-group-integ.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-logs/test/integ.log-group.js.snapshot/aws-cdk-log-group-integ.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-logs/test/integ.log-group.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-logs/test/integ.log-group.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-logs/test/integ.log-group.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-logs/test/integ.log-group.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-logs/test/integ.log-group.ts
  packages/aws-cdk-lib/aws-logs/lib/data-protection-policy.ts
  packages/aws-cdk-lib/aws-logs/lib/log-group.ts
  packages/aws-cdk-lib/aws-logs/test/loggroup.test.ts
Labels: bug, p1, effort/small, valued-contributor

#33486 chore: fix sync workflow
  .github/workflows/sync-from-upstream.yml
Labels: p2, contribution/core

#33509 chore(rds): added Postgres 16.7 version
  packages/aws-cdk-lib/aws-rds/lib/instance-engine.ts
Labels: p2, feature-request, contribution/core

#33500 chore: add enum-like updater
  packages/aws-cdk-lib/core/lib/analytics-data-source/enums.ts
  packages/aws-cdk-lib/core/lib/analytics-data-source/enums/module-enumlikes.json
  packages/aws-cdk-lib/core/lib/analytics-data-source/enums/module-enums.json
  tools/@aws-cdk/construct-metadata-updater/lib/index.ts
  tools/@aws-cdk/construct-metadata-updater/lib/metadata-updater.ts
  tools/@aws-cdk/construct-metadata-updater/test/metadata-updater.test.ts
  tools/@aws-cdk/prlint/lint.ts
Labels: p2, contribution/core, pr-linter/analytics-metadata-change

#33238 feat(glue-alpha): include extra jars parameter in pyspark jobs
  packages/@aws-cdk/aws-glue-alpha/lib/jobs/pyspark-etl-job.ts
  packages/@aws-cdk/aws-glue-alpha/lib/jobs/pyspark-flex-etl-job.ts
  packages/@aws-cdk/aws-glue-alpha/lib/jobs/pyspark-streaming-job.ts
  packages/@aws-cdk/aws-glue-alpha/test/pyspark-etl-jobs.test.ts
  packages/@aws-cdk/aws-glue-alpha/test/pyspark-streaming-jobs.test.ts
Labels: p2, feature-request, pr-linter/exempt-readme, pr-linter/exempt-integ-test, beginning-contributor, pr-linter/exemption-requested

#33507 fix(core): adding warnings to alert when properties will be overwritten
  packages/aws-cdk-lib/core/README.md
  packages/aws-cdk-lib/core/lib/custom-resource.ts
  packages/aws-cdk-lib/core/test/custom-resource.test.ts
Labels: bug, p2, effort/small, pr/needs-community-review, pr-linter/exempt-integ-test, beginning-contributor

#32535 feat(cloudfront): support gRPC for distribution
  packages/@aws-cdk-testing/framework-integ/test/aws-cloudfront/test/integ.distribution-grpc.js.snapshot/DistributionGrpcDefaultTestDeployAssertE740300C.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-cloudfront/test/integ.distribution-grpc.js.snapshot/DistributionGrpcDefaultTestDeployAssertE740300C.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-cloudfront/test/integ.distribution-grpc.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-cloudfront/test/integ.distribution-grpc.js.snapshot/integ-distribution-grpc.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-cloudfront/test/integ.distribution-grpc.js.snapshot/integ-distribution-grpc.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-cloudfront/test/integ.distribution-grpc.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-cloudfront/test/integ.distribution-grpc.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-cloudfront/test/integ.distribution-grpc.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-cloudfront/test/integ.distribution-grpc.ts
  packages/aws-cdk-lib/aws-cloudfront/README.md
  packages/aws-cdk-lib/aws-cloudfront/lib/distribution.ts
  packages/aws-cdk-lib/aws-cloudfront/lib/private/cache-behavior.ts
  packages/aws-cdk-lib/aws-cloudfront/test/distribution.test.ts
  packages/aws-cdk-lib/aws-cloudfront/test/private/cache-behavior.test.ts
Labels: p2, feature-request, effort/small, pr/needs-community-review, distinguished-contributor

#33525 chore: add remote branch check to workflows
  .github/workflows/analytics-metadata-updater.yml
  .github/workflows/lambda-runtime-tests.yml
Labels: p2, contribution/core, pr/needs-maintainer-review

#33529 chore: fix stepfunctions import
  packages/aws-cdk-lib/aws-stepfunctions/lib/states/map-base.ts
Labels: p2, contribution/core

#33531 feat: update L1 CloudFormation resource definitions
  package.json
  packages/@aws-cdk/integ-runner/package.json
  packages/aws-cdk-lib/package.json
  tools/@aws-cdk/spec2cdk/package.json
  yarn.lock
Labels: p2, dependencies, contribution/core, pr-linter/exempt-readme, pr-linter/exempt-test, auto-approve, pr-linter/exempt-integ-test, pr/needs-maintainer-review

#33533 chore: fix yarn upgrade workflow
  .github/workflows/yarn-upgrade.yml
Labels: p2, contribution/core

#33038 feat(cloudfront-origins): read versioned access level
  packages/@aws-cdk-testing/framework-integ/test/aws-cloudfront-origins/test/integ.s3-origin-oac-read-versioned.js.snapshot/asset.bfcf4228d6660f50e81f19efdb64c6388dda6796296eb239decdff1dbc2f4981.bundle/index.js
  packages/@aws-cdk-testing/framework-integ/test/aws-cloudfront-origins/test/integ.s3-origin-oac-read-versioned.js.snapshot/cloudfront-s3-bucket-origin-oac-read-versioned-access.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-cloudfront-origins/test/integ.s3-origin-oac-read-versioned.js.snapshot/cloudfront-s3-bucket-origin-oac-read-versioned-access.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-cloudfront-origins/test/integ.s3-origin-oac-read-versioned.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-cloudfront-origins/test/integ.s3-origin-oac-read-versioned.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-cloudfront-origins/test/integ.s3-origin-oac-read-versioned.js.snapshot/s3originoacreadversionedaccessDefaultTestDeployAssert4EB06593.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-cloudfront-origins/test/integ.s3-origin-oac-read-versioned.js.snapshot/s3originoacreadversionedaccessDefaultTestDeployAssert4EB06593.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-cloudfront-origins/test/integ.s3-origin-oac-read-versioned.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-cloudfront-origins/test/integ.s3-origin-oac-read-versioned.ts
  packages/aws-cdk-lib/aws-cloudfront-origins/README.md
  packages/aws-cdk-lib/aws-cloudfront-origins/lib/s3-bucket-origin.ts
  packages/aws-cdk-lib/aws-cloudfront-origins/test/s3-bucket-origin.test.ts
  packages/aws-cdk-lib/aws-cloudfront/lib/origin-access-control.ts
Labels: p2, feature-request, effort/medium, beginning-contributor

#33536 chore: tweak enum-like parser to exclude certain classes
  packages/aws-cdk-lib/core/lib/analytics-data-source/enums/module-enumlikes.json
  tools/@aws-cdk/construct-metadata-updater/lib/metadata-updater.ts
Labels: p2, contribution/core, pr-linter/analytics-metadata-change

#33540 chore(merge-back): 2.180.0
  CHANGELOG.v2.alpha.md
  CHANGELOG.v2.md
  packages/aws-cdk-lib/cx-api/FEATURE_FLAGS.md
  packages/aws-cdk-lib/cx-api/lib/features.ts
  version.v2.json
Labels: p2, pr/needs-community-review, pr/no-squash, auto-approve

#33539 chore: add git checkout to workflows
  .github/workflows/analytics-metadata-updater.yml
  .github/workflows/lambda-runtime-tests.yml
Labels: p2, contribution/core, pr/needs-maintainer-review

#33549 chore(cognito-identitypool-alpha): add assertions to integ test
  packages/@aws-cdk/aws-cognito-identitypool-alpha/test/integ.identitypool.js.snapshot/asset.3e61c39c0efebc770b86906206d499dc248b5325972df96455773db9e6a37216.bundle/index.js
  packages/@aws-cdk/aws-cognito-identitypool-alpha/test/integ.identitypool.js.snapshot/integ-idp.assets.json
  packages/@aws-cdk/aws-cognito-identitypool-alpha/test/integ.identitypool.js.snapshot/integ-idp.template.json
  packages/@aws-cdk/aws-cognito-identitypool-alpha/test/integ.identitypool.js.snapshot/integidentitypoolDefaultTestDeployAssert8F0BD226.assets.json
  packages/@aws-cdk/aws-cognito-identitypool-alpha/test/integ.identitypool.js.snapshot/integidentitypoolDefaultTestDeployAssert8F0BD226.template.json
  packages/@aws-cdk/aws-cognito-identitypool-alpha/test/integ.identitypool.js.snapshot/manifest.json
  packages/@aws-cdk/aws-cognito-identitypool-alpha/test/integ.identitypool.js.snapshot/tree.json
  packages/@aws-cdk/aws-cognito-identitypool-alpha/test/integ.identitypool.ts
Labels: contribution/core, pr/needs-maintainer-review, needs-security-review

#33516 fix(rds): `monitoringInterval` in `DatabaseClusterProps` does not work with token
  packages/aws-cdk-lib/aws-rds/lib/cluster.ts
  packages/aws-cdk-lib/aws-rds/test/cluster.test.ts
Labels: bug, p2, effort/small, pr-linter/exempt-integ-test, star-contributor

#33448 feat(rds): scheduling modifications in the next scheduled maintenance window
  packages/@aws-cdk-testing/framework-integ/test/aws-rds/test/integ.cluster-applyimmediately.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-rds/test/integ.cluster-applyimmediately.js.snapshot/cluster-applyimmediately-integ.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-rds/test/integ.cluster-applyimmediately.js.snapshot/cluster-applyimmediately-integ.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-rds/test/integ.cluster-applyimmediately.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-rds/test/integ.cluster-applyimmediately.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-rds/test/integ.cluster-applyimmediately.js.snapshot/testclusterapplyimmediatelyintegDefaultTestDeployAssertC097DD2F.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-rds/test/integ.cluster-applyimmediately.js.snapshot/testclusterapplyimmediatelyintegDefaultTestDeployAssertC097DD2F.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-rds/test/integ.cluster-applyimmediately.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-rds/test/integ.cluster-applyimmediately.ts
  packages/@aws-cdk-testing/framework-integ/test/aws-rds/test/integ.instance-applyimmediately.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-rds/test/integ.instance-applyimmediately.js.snapshot/instance-applyimmediately-integ.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-rds/test/integ.instance-applyimmediately.js.snapshot/instance-applyimmediately-integ.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-rds/test/integ.instance-applyimmediately.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-rds/test/integ.instance-applyimmediately.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-rds/test/integ.instance-applyimmediately.js.snapshot/testinstanceapplyimmediatelyintegDefaultTestDeployAssert27BFFA14.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-rds/test/integ.instance-applyimmediately.js.snapshot/testinstanceapplyimmediatelyintegDefaultTestDeployAssert27BFFA14.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-rds/test/integ.instance-applyimmediately.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-rds/test/integ.instance-applyimmediately.ts
  packages/aws-cdk-lib/aws-rds/README.md
  packages/aws-cdk-lib/aws-rds/lib/aurora-cluster-instance.ts
  packages/aws-cdk-lib/aws-rds/lib/instance.ts
  packages/aws-cdk-lib/aws-rds/test/cluster.test.ts
  packages/aws-cdk-lib/aws-rds/test/instance.test.ts
Labels: p2, feature-request, admired-contributor

#33551 chore: fix integ runner by not showing notices
  packages/@aws-cdk/integ-runner/lib/runner/integ-test-suite.ts
Labels: p2, contribution/core

#33501 chore(appsync): improve error message for missing iam authorization mode
  packages/aws-cdk-lib/aws-appsync/lib/eventapi.ts
  packages/aws-cdk-lib/aws-appsync/test/appsync-eventapi.test.ts
Labels: bug, p2, pr/needs-community-review, effort/medium, beginning-contributor

#33550 chore(cognito-identitypool-alpha): remove unused awslint condition
  packages/@aws-cdk/aws-cognito-identitypool-alpha/awslint.json
Labels: p2, contribution/core

#33541 fix(core): `serviceTimeout` for `CustomResource` does not work with token
  packages/aws-cdk-lib/core/lib/custom-resource.ts
  packages/aws-cdk-lib/core/test/custom-resource.test.ts
Labels: bug, p2, pr-linter/exempt-integ-test, distinguished-contributor

#33537 chore: update stale pr workflow
  .github/workflows/close-stale-prs.yml
Labels: p2, contribution/core

#33559 chore(rds): add support for Postgres versions 13.19, 13.20, 14.16, 14.17, 15.11, 15.12, 16.8, 17.3, and 17.4
  packages/aws-cdk-lib/aws-rds/lib/instance-engine.ts
Labels: p2, pr/needs-community-review, distinguished-contributor

#33553 feat(msk): support for Kafka version 3.8.x and add deprecated labels to legacy versions
  packages/@aws-cdk/aws-msk-alpha/README.md
  packages/@aws-cdk/aws-msk-alpha/lib/cluster-version.ts
  packages/@aws-cdk/aws-msk-alpha/test/cluster.test.ts
  packages/@aws-cdk/aws-msk-alpha/test/integ.cluster-version.js.snapshot/KafkaVersionIntegTestDefaultTestDeployAssertD6628743.assets.json
  packages/@aws-cdk/aws-msk-alpha/test/integ.cluster-version.js.snapshot/KafkaVersionTestStack.assets.json
  packages/@aws-cdk/aws-msk-alpha/test/integ.cluster-version.js.snapshot/KafkaVersionTestStack.template.json
  packages/@aws-cdk/aws-msk-alpha/test/integ.cluster-version.js.snapshot/cdk.out
  packages/@aws-cdk/aws-msk-alpha/test/integ.cluster-version.js.snapshot/integ.json
  packages/@aws-cdk/aws-msk-alpha/test/integ.cluster-version.js.snapshot/manifest.json
  packages/@aws-cdk/aws-msk-alpha/test/integ.cluster-version.js.snapshot/tree.json
  packages/@aws-cdk/aws-msk-alpha/test/integ.cluster-version.ts
Labels: p2, pr/needs-community-review, distinguished-contributor

#33571 chore(bedrock): add support for Anthropic Claude 3.7 Sonnet model
  packages/aws-cdk-lib/aws-bedrock/lib/foundation-model.ts
Labels: p2, distinguished-contributor, pr/needs-maintainer-review

#33558 feat(stepfunctions): add support for custom CSV delimiters in S3CsvItemReader
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions/test/integ.distributed-map-csv-delimiter.js.snapshot/DistributedMapCsvDelimiterDefaultTestDeployAssert47A59939.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions/test/integ.distributed-map-csv-delimiter.js.snapshot/DistributedMapCsvDelimiterDefaultTestDeployAssert47A59939.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions/test/integ.distributed-map-csv-delimiter.js.snapshot/asset.44e9c4d7a5d3fd2d677e1a7e416b2b56f6b0104bd5eff9cac5557b4c65a9dc61/index.js
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions/test/integ.distributed-map-csv-delimiter.js.snapshot/asset.dd00f112868c452fba27bada7b77220e5d1dd5b8df0112cf9080be6ac96c29cf.bundle/index.js
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions/test/integ.distributed-map-csv-delimiter.js.snapshot/aws-stepfunctions-csv-delimiter-integ.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions/test/integ.distributed-map-csv-delimiter.js.snapshot/aws-stepfunctions-csv-delimiter-integ.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions/test/integ.distributed-map-csv-delimiter.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions/test/integ.distributed-map-csv-delimiter.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions/test/integ.distributed-map-csv-delimiter.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions/test/integ.distributed-map-csv-delimiter.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions/test/integ.distributed-map-csv-delimiter.ts
  packages/aws-cdk-lib/aws-stepfunctions/lib/states/distributed-map/item-reader.ts
  packages/aws-cdk-lib/aws-stepfunctions/test/distributed-map.test.ts
Labels: p2, feature-request, effort/medium, pr-linter/exempt-readme, distinguished-contributor, pr-linter/exemption-requested

#32575 fix(core): cross-stack references to NestedStack list values produces invalid outputs
  packages/@aws-cdk-testing/framework-integ/test/core/test/integ.nested-stack-references.js.snapshot/Consumer.assets.json
  packages/@aws-cdk-testing/framework-integ/test/core/test/integ.nested-stack-references.js.snapshot/Consumer.template.json
  packages/@aws-cdk-testing/framework-integ/test/core/test/integ.nested-stack-references.js.snapshot/NestedStackReferencesDefaultTestDeployAssertFE4F9D3A.assets.json
  packages/@aws-cdk-testing/framework-integ/test/core/test/integ.nested-stack-references.js.snapshot/NestedStackReferencesDefaultTestDeployAssertFE4F9D3A.template.json
  packages/@aws-cdk-testing/framework-integ/test/core/test/integ.nested-stack-references.js.snapshot/Producer.assets.json
  packages/@aws-cdk-testing/framework-integ/test/core/test/integ.nested-stack-references.js.snapshot/Producer.template.json
  packages/@aws-cdk-testing/framework-integ/test/core/test/integ.nested-stack-references.js.snapshot/ProducerNested869755D4.nested.template.json
  packages/@aws-cdk-testing/framework-integ/test/core/test/integ.nested-stack-references.js.snapshot/asset.bfcf4228d6660f50e81f19efdb64c6388dda6796296eb239decdff1dbc2f4981.bundle/index.js
  packages/@aws-cdk-testing/framework-integ/test/core/test/integ.nested-stack-references.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/core/test/integ.nested-stack-references.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/core/test/integ.nested-stack-references.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/core/test/integ.nested-stack-references.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/core/test/integ.nested-stack-references.ts
  packages/aws-cdk-lib/core/lib/private/refs.ts
  packages/aws-cdk-lib/core/lib/stack.ts
  packages/aws-cdk-lib/core/test/stack.test.ts
Labels: bug, p2, beginning-contributor, skip-abstractions-board

#33460 fix(core): wrong priority for tag aspects
  packages/aws-cdk-lib/core/lib/tag-aspect.ts
  packages/aws-cdk-lib/core/test/aspect.test.ts
  packages/aws-cdk-lib/core/test/tag-aspect.test.ts
Labels: p2, pr-linter/exempt-integ-test, beginning-contributor

#33552 feat(redshift-alpha): maintenance track name
  packages/@aws-cdk/aws-redshift-alpha/README.md
  packages/@aws-cdk/aws-redshift-alpha/lib/cluster.ts
  packages/@aws-cdk/aws-redshift-alpha/test/cluster.test.ts
  packages/@aws-cdk/aws-redshift-alpha/test/integ.cluster-maintenance-track-name.js.snapshot/RedshiftMaintenanceTrackNameIntegDefaultTestDeployAssert73097553.assets.json
  packages/@aws-cdk/aws-redshift-alpha/test/integ.cluster-maintenance-track-name.js.snapshot/RedshiftMaintenanceTrackNameIntegDefaultTestDeployAssert73097553.template.json
  packages/@aws-cdk/aws-redshift-alpha/test/integ.cluster-maintenance-track-name.js.snapshot/RedshiftMaintenanceTrackNameIntegStack.assets.json
  packages/@aws-cdk/aws-redshift-alpha/test/integ.cluster-maintenance-track-name.js.snapshot/RedshiftMaintenanceTrackNameIntegStack.template.json
  packages/@aws-cdk/aws-redshift-alpha/test/integ.cluster-maintenance-track-name.js.snapshot/asset.39472b1c2875cf306d4ba429aeccdd34cb49bcf59dbde81f7e6b6cb9deac23a6/cfn-response.js
  packages/@aws-cdk/aws-redshift-alpha/test/integ.cluster-maintenance-track-name.js.snapshot/asset.39472b1c2875cf306d4ba429aeccdd34cb49bcf59dbde81f7e6b6cb9deac23a6/consts.js
  packages/@aws-cdk/aws-redshift-alpha/test/integ.cluster-maintenance-track-name.js.snapshot/asset.39472b1c2875cf306d4ba429aeccdd34cb49bcf59dbde81f7e6b6cb9deac23a6/framework.js
  packages/@aws-cdk/aws-redshift-alpha/test/integ.cluster-maintenance-track-name.js.snapshot/asset.39472b1c2875cf306d4ba429aeccdd34cb49bcf59dbde81f7e6b6cb9deac23a6/outbound.js
  packages/@aws-cdk/aws-redshift-alpha/test/integ.cluster-maintenance-track-name.js.snapshot/asset.39472b1c2875cf306d4ba429aeccdd34cb49bcf59dbde81f7e6b6cb9deac23a6/util.js
  packages/@aws-cdk/aws-redshift-alpha/test/integ.cluster-maintenance-track-name.js.snapshot/asset.60d6644ca7559903aa3a4516f84720a5f2cc1310aa4f456b1aad45a0c1e28046/handler-name.js
  packages/@aws-cdk/aws-redshift-alpha/test/integ.cluster-maintenance-track-name.js.snapshot/asset.60d6644ca7559903aa3a4516f84720a5f2cc1310aa4f456b1aad45a0c1e28046/index.js
  packages/@aws-cdk/aws-redshift-alpha/test/integ.cluster-maintenance-track-name.js.snapshot/asset.60d6644ca7559903aa3a4516f84720a5f2cc1310aa4f456b1aad45a0c1e28046/privileges.js
  packages/@aws-cdk/aws-redshift-alpha/test/integ.cluster-maintenance-track-name.js.snapshot/asset.60d6644ca7559903aa3a4516f84720a5f2cc1310aa4f456b1aad45a0c1e28046/redshift-data.js
  packages/@aws-cdk/aws-redshift-alpha/test/integ.cluster-maintenance-track-name.js.snapshot/asset.60d6644ca7559903aa3a4516f84720a5f2cc1310aa4f456b1aad45a0c1e28046/table.js
  packages/@aws-cdk/aws-redshift-alpha/test/integ.cluster-maintenance-track-name.js.snapshot/asset.60d6644ca7559903aa3a4516f84720a5f2cc1310aa4f456b1aad45a0c1e28046/types.js
  packages/@aws-cdk/aws-redshift-alpha/test/integ.cluster-maintenance-track-name.js.snapshot/asset.60d6644ca7559903aa3a4516f84720a5f2cc1310aa4f456b1aad45a0c1e28046/user.js
  packages/@aws-cdk/aws-redshift-alpha/test/integ.cluster-maintenance-track-name.js.snapshot/asset.60d6644ca7559903aa3a4516f84720a5f2cc1310aa4f456b1aad45a0c1e28046/util.js
  packages/@aws-cdk/aws-redshift-alpha/test/integ.cluster-maintenance-track-name.js.snapshot/asset.a1acfc2b5f4f6b183fd2bb9863f486bc5edef6a357b355a070d9a0e502df418c/__entrypoint__.js
  packages/@aws-cdk/aws-redshift-alpha/test/integ.cluster-maintenance-track-name.js.snapshot/asset.a1acfc2b5f4f6b183fd2bb9863f486bc5edef6a357b355a070d9a0e502df418c/index.js
  packages/@aws-cdk/aws-redshift-alpha/test/integ.cluster-maintenance-track-name.js.snapshot/cdk.out
  packages/@aws-cdk/aws-redshift-alpha/test/integ.cluster-maintenance-track-name.js.snapshot/integ.json
  packages/@aws-cdk/aws-redshift-alpha/test/integ.cluster-maintenance-track-name.js.snapshot/manifest.json
  packages/@aws-cdk/aws-redshift-alpha/test/integ.cluster-maintenance-track-name.js.snapshot/tree.json
  packages/@aws-cdk/aws-redshift-alpha/test/integ.cluster-maintenance-track-name.ts
Labels: p2, pr/needs-community-review, distinguished-contributor

#33579 feat: update L1 CloudFormation resource definitions
  packages/@aws-cdk/integ-runner/package.json
  packages/aws-cdk-lib/package.json
  tools/@aws-cdk/spec2cdk/package.json
  yarn.lock
Labels: p2, dependencies, contribution/core, pr-linter/exempt-readme, pr-linter/exempt-test, auto-approve, pr-linter/exempt-integ-test, pr/needs-maintainer-review

#33555 fix(iam): adding organization id pattern verification
  packages/@aws-cdk-testing/framework-integ/test/aws-iam/test/integ.role.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-iam/test/integ.role.js.snapshot/integ-iam-role-1.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-iam/test/integ.role.js.snapshot/integ-iam-role-1.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-iam/test/integ.role.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-iam/test/integ.role.js.snapshot/integiamroleDefaultTestDeployAssert48737E31.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-iam/test/integ.role.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-iam/test/integ.role.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-iam/test/integ.role.ts
  packages/aws-cdk-lib/aws-iam/lib/principals.ts
  packages/aws-cdk-lib/aws-iam/test/principals.test.ts
  packages/aws-cdk-lib/aws-kms/test/via-service-principal.test.ts
  packages/aws-cdk-lib/aws-lambda/test/function.test.ts
  packages/aws-cdk-lib/aws-s3/test/bucket.test.ts
Labels: bug, p1, effort/small, repeat-contributor, pr/needs-maintainer-review

#33596 docs(core): aspects with same priority are not guaranteed to be executed in the same order
  packages/aws-cdk-lib/core/README.md
  packages/aws-cdk-lib/core/lib/aspect.ts
Labels: p2, contribution/core

#31286 feat(autoscaling): add new `HealthChecks` for multiple health check types, including EBS and VPC_LATTICE types
  packages/@aws-cdk-testing/framework-integ/test/aws-autoscaling/test/integ.health-checks.js.snapshot/AutoScalingGroupHealthChecksDefaultTestDeployAssert9AAA1F3B.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-autoscaling/test/integ.health-checks.js.snapshot/AutoScalingGroupHealthChecksDefaultTestDeployAssert9AAA1F3B.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-autoscaling/test/integ.health-checks.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-autoscaling/test/integ.health-checks.js.snapshot/integ-health-checks.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-autoscaling/test/integ.health-checks.js.snapshot/integ-health-checks.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-autoscaling/test/integ.health-checks.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-autoscaling/test/integ.health-checks.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-autoscaling/test/integ.health-checks.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-autoscaling/test/integ.health-checks.ts
  packages/aws-cdk-lib/aws-autoscaling/README.md
  packages/aws-cdk-lib/aws-autoscaling/lib/auto-scaling-group.ts
  packages/aws-cdk-lib/aws-autoscaling/test/auto-scaling-group.test.ts
  packages/aws-cdk-lib/awslint.json
Labels: p2, feature-request, pr/needs-community-review, distinguished-contributor

#33535 feat(ecs): encrypting managed storage
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs/test/integ.cluster-encrypt-storage.js.snapshot/asset.3e61c39c0efebc770b86906206d499dc248b5325972df96455773db9e6a37216.bundle/index.js
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs/test/integ.cluster-encrypt-storage.js.snapshot/aws-ecs-encrypt-storage.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs/test/integ.cluster-encrypt-storage.js.snapshot/aws-ecs-encrypt-storage.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs/test/integ.cluster-encrypt-storage.js.snapshot/awsecsclusterencryptstorageDefaultTestDeployAssertAA409973.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs/test/integ.cluster-encrypt-storage.js.snapshot/awsecsclusterencryptstorageDefaultTestDeployAssertAA409973.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs/test/integ.cluster-encrypt-storage.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs/test/integ.cluster-encrypt-storage.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs/test/integ.cluster-encrypt-storage.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs/test/integ.cluster-encrypt-storage.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs/test/integ.cluster-encrypt-storage.ts
  packages/aws-cdk-lib/aws-ecs/README.md
  packages/aws-cdk-lib/aws-ecs/lib/cluster.ts
  packages/aws-cdk-lib/aws-ecs/test/cluster.test.ts
Labels: p2, feature-request, effort/medium, valued-contributor, pr/needs-maintainer-review

#33520 chore: change shebang in link_all.sh to be portable
  link-all.sh
Labels: p2, pr/needs-community-review, repeat-contributor

#33546 feat(pipes-alpha): support for customer-managed KMS keys to encrypt pipe data
  packages/@aws-cdk/aws-pipes-alpha/README.md
  packages/@aws-cdk/aws-pipes-alpha/lib/pipe.ts
  packages/@aws-cdk/aws-pipes-alpha/rosetta/default.ts-fixture
  packages/@aws-cdk/aws-pipes-alpha/test/integ.pipe-kmskey.js.snapshot/PipesKmsKeyTestDefaultTestDeployAssert1065A2A1.assets.json
  packages/@aws-cdk/aws-pipes-alpha/test/integ.pipe-kmskey.js.snapshot/PipesKmsKeyTestDefaultTestDeployAssert1065A2A1.template.json
  packages/@aws-cdk/aws-pipes-alpha/test/integ.pipe-kmskey.js.snapshot/PipesKmsKeyTestStack.assets.json
  packages/@aws-cdk/aws-pipes-alpha/test/integ.pipe-kmskey.js.snapshot/PipesKmsKeyTestStack.template.json
  packages/@aws-cdk/aws-pipes-alpha/test/integ.pipe-kmskey.js.snapshot/asset.4a8b2d1ae3fba266ef36adae459ae53392d074ee550352d271d073f06413f06b.bundle/index.js
  packages/@aws-cdk/aws-pipes-alpha/test/integ.pipe-kmskey.js.snapshot/cdk.out
  packages/@aws-cdk/aws-pipes-alpha/test/integ.pipe-kmskey.js.snapshot/integ.json
  packages/@aws-cdk/aws-pipes-alpha/test/integ.pipe-kmskey.js.snapshot/manifest.json
  packages/@aws-cdk/aws-pipes-alpha/test/integ.pipe-kmskey.js.snapshot/tree.json
  packages/@aws-cdk/aws-pipes-alpha/test/integ.pipe-kmskey.ts
  packages/@aws-cdk/aws-pipes-alpha/test/pipe.test.ts
Labels: p2, feature-request, effort/medium, distinguished-contributor

#33609 fix(cognito-identitypool-alpha): prevent stacks from not deploying correctly
  packages/@aws-cdk/aws-cognito-identitypool-alpha/lib/identitypool.ts
  packages/@aws-cdk/aws-cognito-identitypool-alpha/test/integ.identitypool.js.snapshot/integ-idp.assets.json
  packages/@aws-cdk/aws-cognito-identitypool-alpha/test/integ.identitypool.js.snapshot/integ-idp.template.json
  packages/@aws-cdk/aws-cognito-identitypool-alpha/test/integ.identitypool.js.snapshot/integidentitypoolDefaultTestDeployAssert8F0BD226.assets.json
  packages/@aws-cdk/aws-cognito-identitypool-alpha/test/integ.identitypool.js.snapshot/integidentitypoolDefaultTestDeployAssert8F0BD226.template.json
  packages/@aws-cdk/aws-cognito-identitypool-alpha/test/integ.identitypool.js.snapshot/manifest.json
  packages/@aws-cdk/aws-cognito-identitypool-alpha/test/integ.identitypool.js.snapshot/tree.json
Labels: bug, p1, effort/medium, contribution/core, pr-linter/exempt-integ-test

#33594 chore(batch): corrected the documentation string for updateToLatestImageVersion in ManagedComputeEnvironmentProps.
  packages/aws-cdk-lib/aws-batch/lib/managed-compute-environment.ts
Labels: p2, effort/small, contribution/core, pr/needs-maintainer-review

#33573 fix(eks-v2-alpha): can't delete fargate cluster
  packages/@aws-cdk/aws-eks-v2-alpha/lib/cluster.ts
  packages/@aws-cdk/aws-eks-v2-alpha/test/integ.fargate-cluster.js.snapshot/asset.2e670e0c40dc05a34d602c35c948edefcb81afaeea05b9f6240341173af6164e.zip
  packages/@aws-cdk/aws-eks-v2-alpha/test/integ.fargate-cluster.js.snapshot/eks-fargate-cluster-test-stack.assets.json
  packages/@aws-cdk/aws-eks-v2-alpha/test/integ.fargate-cluster.js.snapshot/eks-fargate-cluster-test-stack.template.json
  packages/@aws-cdk/aws-eks-v2-alpha/test/integ.fargate-cluster.js.snapshot/manifest.json
  packages/@aws-cdk/aws-eks-v2-alpha/test/integ.fargate-cluster.js.snapshot/tree.json
Labels: bug, p2, effort/medium, contribution/core, pr-linter/exempt-integ-test
