Repository aws/aws-cdk, pull requests merged in 2025-08, with the labels that each got.

#34925 refactor: drop support for Node.js <= 18.0.0
  packages/@aws-cdk-testing/framework-integ/package.json
  packages/@aws-cdk/app-staging-synthesizer-alpha/package.json
  packages/@aws-cdk/aws-amplify-alpha/package.json
  packages/@aws-cdk/aws-applicationsignals-alpha/package.json
  packages/@aws-cdk/aws-apprunner-alpha/package.json
  packages/@aws-cdk/aws-bedrock-alpha/package.json
  packages/@aws-cdk/aws-cloud9-alpha/package.json
  packages/@aws-cdk/aws-codestar-alpha/package.json
  packages/@aws-cdk/aws-custom-resource-sdk-adapter/package.json
  packages/@aws-cdk/aws-ec2-alpha/package.json
  packages/@aws-cdk/aws-eks-v2-alpha/package.json
  packages/@aws-cdk/aws-gamelift-alpha/package.json
  packages/@aws-cdk/aws-glue-alpha/package.json
  packages/@aws-cdk/aws-iot-actions-alpha/package.json
  packages/@aws-cdk/aws-iot-alpha/package.json
  packages/@aws-cdk/aws-iotevents-actions-alpha/package.json
  packages/@aws-cdk/aws-iotevents-alpha/package.json
  packages/@aws-cdk/aws-ivs-alpha/package.json
  packages/@aws-cdk/aws-kinesisanalytics-flink-alpha/package.json
  packages/@aws-cdk/aws-lambda-go-alpha/package.json
  packages/@aws-cdk/aws-lambda-python-alpha/package.json
  packages/@aws-cdk/aws-location-alpha/package.json
  packages/@aws-cdk/aws-msk-alpha/package.json
  packages/@aws-cdk/aws-neptune-alpha/package.json
  packages/@aws-cdk/aws-pipes-alpha/package.json
  packages/@aws-cdk/aws-pipes-enrichments-alpha/package.json
  packages/@aws-cdk/aws-pipes-sources-alpha/package.json
  packages/@aws-cdk/aws-pipes-targets-alpha/package.json
  packages/@aws-cdk/aws-redshift-alpha/package.json
  packages/@aws-cdk/aws-route53resolver-alpha/package.json
  packages/@aws-cdk/aws-s3objectlambda-alpha/package.json
  packages/@aws-cdk/aws-s3tables-alpha/package.json
  packages/@aws-cdk/aws-sagemaker-alpha/package.json
  packages/@aws-cdk/aws-servicecatalogappregistry-alpha/package.json
  packages/@aws-cdk/custom-resource-handlers/package.json
  packages/@aws-cdk/cx-api/package.json
  packages/@aws-cdk/example-construct-library/package.json
  packages/@aws-cdk/integ-tests-alpha/package.json
  packages/@aws-cdk/region-info/package.json
  packages/aws-cdk-lib/core/lib/custom-resource-provider/custom-resource-provider.ts
  packages/aws-cdk-lib/package.json
  packages/awslint/package.json
  tools/@aws-cdk/cdk-build-tools/package.json
  tools/@aws-cdk/cdk-release/package.json
  tools/@aws-cdk/pkglint/lib/rules.ts
  tools/@aws-cdk/pkgtools/package.json
  tools/@aws-cdk/spec2cdk/package.json
Labels: p1, contribution/core, pr-linter/exempt-integ-test

#35108 feat: add new field to feature flag report
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-nodejs/test/integ.latest.js.snapshot/LambdaNodeJsLatestIntegDefaultTestDeployAssertD40B5C28.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-nodejs/test/integ.latest.js.snapshot/LambdaNodeJsLatestIntegDefaultTestDeployAssertD40B5C28.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-nodejs/test/integ.latest.js.snapshot/asset.069f8376d0e4e8d1eb295d84e1d084c6b79c239097010bc64a3874e37e4a38e6/index.js
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-nodejs/test/integ.latest.js.snapshot/asset.069f8376d0e4e8d1eb295d84e1d084c6b79c239097010bc64a3874e37e4a38e6/node_modules/.yarn-integrity
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-nodejs/test/integ.latest.js.snapshot/asset.069f8376d0e4e8d1eb295d84e1d084c6b79c239097010bc64a3874e37e4a38e6/node_modules/delay/index.d.ts
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-nodejs/test/integ.latest.js.snapshot/asset.069f8376d0e4e8d1eb295d84e1d084c6b79c239097010bc64a3874e37e4a38e6/node_modules/delay/index.js
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-nodejs/test/integ.latest.js.snapshot/asset.069f8376d0e4e8d1eb295d84e1d084c6b79c239097010bc64a3874e37e4a38e6/node_modules/delay/license
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-nodejs/test/integ.latest.js.snapshot/asset.069f8376d0e4e8d1eb295d84e1d084c6b79c239097010bc64a3874e37e4a38e6/node_modules/delay/package.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-nodejs/test/integ.latest.js.snapshot/asset.069f8376d0e4e8d1eb295d84e1d084c6b79c239097010bc64a3874e37e4a38e6/node_modules/delay/readme.md
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-nodejs/test/integ.latest.js.snapshot/asset.069f8376d0e4e8d1eb295d84e1d084c6b79c239097010bc64a3874e37e4a38e6/package.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-nodejs/test/integ.latest.js.snapshot/asset.069f8376d0e4e8d1eb295d84e1d084c6b79c239097010bc64a3874e37e4a38e6/yarn.lock
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-nodejs/test/integ.latest.js.snapshot/asset.c74d4e3c82f2db3767a5b28f12d80d3dc43fdb041406fd738e1a754a716b9f96.bundle/index.js
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-nodejs/test/integ.latest.js.snapshot/cdk-integ-lambda-nodejs-latest.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-nodejs/test/integ.latest.js.snapshot/cdk-integ-lambda-nodejs-latest.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-nodejs/test/integ.latest.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-nodejs/test/integ.latest.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-nodejs/test/integ.latest.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-nodejs/test/integ.latest.js.snapshot/tree.json
  packages/@aws-cdk/cx-api/package.json
  packages/aws-cdk-lib/core/lib/private/feature-flag-report.ts
  packages/aws-cdk-lib/package.json
  yarn.lock
Labels: p2, contribution/core, pr-linter/exempt-readme, beginning-contributor, pr/needs-maintainer-review

#35061 feat(ecs): add support for native blue/green deployments in ECS L2
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs/test/base/integ.blue-green-deployment-strategy.js.snapshot/aws-ecs-blue-green-deployment.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs/test/base/integ.blue-green-deployment-strategy.js.snapshot/aws-ecs-blue-green-deployment.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs/test/base/integ.blue-green-deployment-strategy.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs/test/base/integ.blue-green-deployment-strategy.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs/test/base/integ.blue-green-deployment-strategy.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs/test/base/integ.blue-green-deployment-strategy.ts
  packages/aws-cdk-lib/aws-ecs/README.md
  packages/aws-cdk-lib/aws-ecs/lib/alternate-target-configuration.ts
  packages/aws-cdk-lib/aws-ecs/lib/base/base-service.ts
  packages/aws-cdk-lib/aws-ecs/lib/deployment-lifecycle-hook-target.ts
  packages/aws-cdk-lib/aws-ecs/lib/external/external-service.ts
  packages/aws-cdk-lib/aws-ecs/lib/index.ts
  packages/aws-cdk-lib/aws-ecs/test/alternate-target-configuration.test.ts
  packages/aws-cdk-lib/aws-ecs/test/base-service.test.ts
  packages/aws-cdk-lib/aws-ecs/test/deployment-lifecycle-hook-target.test.ts
Labels: p2, feature-request, @aws-cdk/aws-ecs, pr/needs-community-review, effort/medium, beginning-contributor

#34906 fix(rds): can not lookup VPC Security Groups with fromLookup method
  packages/@aws-cdk-testing/framework-integ/test/aws-rds/test/integ.instance-lookup.js.snapshot/aws-cdk-rds-instance-lookup.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-rds/test/integ.instance-lookup.js.snapshot/aws-cdk-rds-instance-lookup.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-rds/test/integ.instance-lookup.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-rds/test/integ.instance-lookup.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-rds/test/integ.instance-lookup.js.snapshot/integrdsinstancefromlookupDefaultTestDeployAssert675A9017.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-rds/test/integ.instance-lookup.js.snapshot/integrdsinstancefromlookupDefaultTestDeployAssert675A9017.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-rds/test/integ.instance-lookup.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-rds/test/integ.instance-lookup.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-rds/test/integ.instance-lookup.ts
  packages/aws-cdk-lib/aws-rds/lib/instance.ts
  packages/aws-cdk-lib/aws-rds/test/instance.from-lookup.test.ts
Labels: p2, distinguished-contributor

#35142 ci: downgrade jsii version
  package.json
  packages/awslint/package.json
  tools/@aws-cdk/cdk-build-tools/package.json
  yarn.lock
Labels: p2, contribution/core, valued-contributor

#35165 chore(merge-back): 2.209.1
  CHANGELOG.v2.alpha.md
  CHANGELOG.v2.md
  version.v2.json
Labels: p2, contribution/core, pr/no-squash, auto-approve, pr/needs-maintainer-review

#35144 fix(dynamodb): use keyId instead of keyArn for TableV2 replica encryption
  packages/aws-cdk-lib/aws-dynamodb/lib/encryption.ts
  packages/aws-cdk-lib/aws-dynamodb/test/encryption.test.ts
  packages/aws-cdk-lib/aws-dynamodb/test/table-v2.test.ts
Labels: bug, p1, effort/medium, contribution/core, pr-linter/exempt-integ-test, pr-linter/exemption-requested

#34909 feat(dynamodb): tableV2 MRSC feature addition
  packages/@aws-cdk-testing/framework-integ/test/aws-dynamodb/test/integ.table-v2-mrsc.js.snapshot/aws-cdk-global-table-mrsc.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-dynamodb/test/integ.table-v2-mrsc.js.snapshot/aws-cdk-global-table-mrsc.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-dynamodb/test/integ.table-v2-mrsc.js.snapshot/awscdkglobaltableintegDefaultTestDeployAssertA2A9E81F.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-dynamodb/test/integ.table-v2-mrsc.js.snapshot/awscdkglobaltableintegDefaultTestDeployAssertA2A9E81F.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-dynamodb/test/integ.table-v2-mrsc.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-dynamodb/test/integ.table-v2-mrsc.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-dynamodb/test/integ.table-v2-mrsc.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-dynamodb/test/integ.table-v2-mrsc.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-dynamodb/test/integ.table-v2-mrsc.ts
  packages/aws-cdk-lib/aws-dynamodb/README.md
  packages/aws-cdk-lib/aws-dynamodb/lib/shared.ts
  packages/aws-cdk-lib/aws-dynamodb/lib/table-v2.ts
  packages/aws-cdk-lib/aws-dynamodb/test/table-v2.test.ts
Labels: p2, feature-request, effort/medium, valued-contributor

#35178 chore(merge-back): 2.210.0
  CHANGELOG.v2.alpha.md
  CHANGELOG.v2.md
  packages/@aws-cdk/aws-bedrock-alpha/bedrock/inference-profiles/application-inference-profile.ts
  packages/@aws-cdk/aws-s3tables-alpha/lib/namespace.ts
  packages/@aws-cdk/aws-s3tables-alpha/lib/table.ts
  packages/aws-cdk-lib/core/lib/analytics-data-source/classes.ts
  packages/aws-cdk-lib/core/lib/analytics-data-source/enums.ts
  packages/aws-cdk-lib/core/lib/analytics-data-source/enums/module-enums.json
  version.v2.json
Labels: p2, contribution/core, pr/no-squash, auto-approve, pr/needs-maintainer-review

#35179 feat(ecs): add L2 support for native ECS blue/green deployments
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs/test/base/integ.blue-green-deployment-strategy.js.snapshot/aws-ecs-blue-green-deployment.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs/test/base/integ.blue-green-deployment-strategy.js.snapshot/aws-ecs-blue-green-deployment.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs/test/base/integ.blue-green-deployment-strategy.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs/test/base/integ.blue-green-deployment-strategy.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs/test/base/integ.blue-green-deployment-strategy.ts
  packages/aws-cdk-lib/aws-ecs/README.md
  packages/aws-cdk-lib/aws-ecs/lib/alternate-target-configuration.ts
  packages/aws-cdk-lib/aws-ecs/lib/base/base-service.ts
  packages/aws-cdk-lib/aws-ecs/lib/base/task-definition.ts
  packages/aws-cdk-lib/aws-ecs/lib/deployment-lifecycle-hook-target.ts
  packages/aws-cdk-lib/aws-ecs/lib/index.ts
  packages/aws-cdk-lib/aws-ecs/test/alternate-target-configuration.test.ts
  packages/aws-cdk-lib/aws-ecs/test/base-service.test.ts
  packages/aws-cdk-lib/aws-ecs/test/deployment-lifecycle-hook-target.test.ts
Labels: p2, feature-request, effort/medium, contribution/core

#35197 docs(ecs): remove L1 Construct native blue/green deployment example from README
  packages/aws-cdk-lib/aws-ecs/README.md
Labels: p2, distinguished-contributor

#35156 docs: update ECS service and Fargate documentation for new AZ rebalancing default values
  packages/aws-cdk-lib/aws-ecs/lib/ec2/ec2-service.ts
  packages/aws-cdk-lib/aws-ecs/lib/fargate/fargate-service.ts
Labels: p2, beginning-contributor

#35163 chore(bedrock): support Anthropic Claude Opus 4.1, gpt-oss-120b and gpt-oss-20b
  packages/aws-cdk-lib/aws-bedrock/lib/foundation-model.ts
Labels: p2, distinguished-contributor

#35216 chore(ci): add pull_request_target workflow for v2-release branch in pr build
  .github/workflows/codebuild-pr-build.yml
Labels: p2, contribution/core

#35221 chore(ci): enable mergify branch protection
  .mergify.yml
Labels: p2, contribution/core

#35215 chore(flags): feature flag report contains feature info for all library versions
  packages/aws-cdk-lib/core/lib/private/feature-flag-report.ts
Labels: p2, contribution/core

#35226 chore(merge-back): 2.211.0
  CHANGELOG.v2.alpha.md
  CHANGELOG.v2.md
  packages/aws-cdk-lib/core/lib/analytics-data-source/classes.ts
  packages/aws-cdk-lib/core/lib/analytics-data-source/enums.ts
  packages/aws-cdk-lib/core/lib/analytics-data-source/enums/module-enums.json
  version.v2.json
Labels: p2, contribution/core, pr/no-squash, auto-approve

#35227 fix(aws-cdk-lib): feature flag report contains unnecessary flags
  packages/aws-cdk-lib/core/lib/private/feature-flag-report.ts
  packages/aws-cdk-lib/core/test/feature-flag-report.test.ts
  packages/aws-cdk-lib/cx-api/lib/features.ts
Labels: p2, contribution/core, pr-linter/exempt-integ-test

#35229 docs(aws-cdk-lib): remove duplication of main docs
  packages/@aws-cdk/aws-pipes-alpha/package.json
  packages/aws-cdk-lib/README.md
  packages/aws-cdk-lib/aws-lakeformation/README.md
  packages/aws-cdk-lib/aws-stepfunctions-tasks/README.md
  packages/aws-cdk-lib/core/README.md
  packages/aws-cdk-lib/package.json
  packages/aws-cdk-lib/rosetta/default.ts-fixture
Labels: p2, contribution/core

#35191 ci(project-sync): fill in item priority
  tools/@aws-cdk/project-sync/lib/github.ts
  tools/@aws-cdk/project-sync/lib/issue-sync.ts
  tools/@aws-cdk/project-sync/lib/pr-sync.ts
  tools/@aws-cdk/project-sync/lib/sync-all.ts
  tools/@aws-cdk/project-sync/lib/utils.ts
  tools/@aws-cdk/project-sync/test/issue-sync.test.ts
  tools/@aws-cdk/project-sync/test/pr-sync.test.ts
  tools/@aws-cdk/project-sync/test/snapshots/get-issue/15891.json
  tools/@aws-cdk/project-sync/test/snapshots/get-issue/30793.json
  tools/@aws-cdk/project-sync/test/snapshots/get-issue/33208.json
  tools/@aws-cdk/project-sync/test/snapshots/get-issue/41.json
  tools/@aws-cdk/project-sync/test/snapshots/get-pr/34962.json
  tools/@aws-cdk/project-sync/test/snapshots/get-project-info.json
Labels: p2, contribution/core, admired-contributor

#34989 docs(lambda): fix incorrect import in autoscaling example
  packages/aws-cdk-lib/aws-lambda/README.md
Labels: p2, effort/small, beginning-contributor

#35269 chore: add a missing Rosetta dependency
  packages/@aws-cdk/aws-pipes-targets-alpha/package.json
Labels: p2, contribution/core

#35060 feat: implement UsagePlan and ApiKey support in L2 constructs for aws-apigatewayv2 (WebSocketApi)
  packages/@aws-cdk-testing/framework-integ/test/aws-apigatewayv2/test/websocket/integ.usage-plan.js.snapshot/WebSocketUsagePlanIntegDefaultTestDeployAssert17052BCC.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-apigatewayv2/test/websocket/integ.usage-plan.js.snapshot/WebSocketUsagePlanIntegDefaultTestDeployAssert17052BCC.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-apigatewayv2/test/websocket/integ.usage-plan.js.snapshot/aws-cdk-aws-apigatewayv2-websocket-usage-plan.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-apigatewayv2/test/websocket/integ.usage-plan.js.snapshot/aws-cdk-aws-apigatewayv2-websocket-usage-plan.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-apigatewayv2/test/websocket/integ.usage-plan.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-apigatewayv2/test/websocket/integ.usage-plan.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-apigatewayv2/test/websocket/integ.usage-plan.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-apigatewayv2/test/websocket/integ.usage-plan.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-apigatewayv2/test/websocket/integ.usage-plan.ts
  packages/aws-cdk-lib/aws-apigatewayv2/README.md
  packages/aws-cdk-lib/aws-apigatewayv2/lib/websocket/api-key.ts
  packages/aws-cdk-lib/aws-apigatewayv2/lib/websocket/index.ts
  packages/aws-cdk-lib/aws-apigatewayv2/lib/websocket/usage-plan.ts
  packages/aws-cdk-lib/aws-apigatewayv2/test/websocket/api-key.test.ts
  packages/aws-cdk-lib/aws-apigatewayv2/test/websocket/usage-plan.test.ts
Labels: p2, feature-request, pr/needs-community-review, effort/medium, beginning-contributor

#35256 feat: update L1 CloudFormation resource definitions
  packages/aws-cdk-lib/package.json
  tools/@aws-cdk/spec2cdk/package.json
  yarn.lock
Labels: p2, dependencies, contribution/core, pr-linter/exempt-readme, pr-linter/exempt-test, pr-linter/exempt-integ-test

#35285 chore(merge-back): 2.212.0
  CHANGELOG.v2.alpha.md
  CHANGELOG.v2.md
  packages/aws-cdk-lib/core/lib/analytics-data-source/classes.ts
  packages/aws-cdk-lib/core/lib/analytics-data-source/enums/module-enumlikes.json
  packages/aws-cdk-lib/core/lib/analytics-data-source/enums/module-enums.json
  packages/aws-cdk-lib/cx-api/FEATURE_FLAGS.md
  packages/aws-cdk-lib/cx-api/lib/features.ts
  version.v2.json
Labels: p2, contribution/core, pr/no-squash, auto-approve

#34962 feat(ecs): volume initialization rate
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs/test/fargate/integ.ebs-volume-initialization-rate.js.snapshot/EBSVolumeInitializationRateDefaultTestDeployAssertCB85F20D.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs/test/fargate/integ.ebs-volume-initialization-rate.js.snapshot/EBSVolumeInitializationRateDefaultTestDeployAssertCB85F20D.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs/test/fargate/integ.ebs-volume-initialization-rate.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs/test/fargate/integ.ebs-volume-initialization-rate.js.snapshot/integ-aws-ecs-ebs-volume-initialization-rate.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs/test/fargate/integ.ebs-volume-initialization-rate.js.snapshot/integ-aws-ecs-ebs-volume-initialization-rate.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs/test/fargate/integ.ebs-volume-initialization-rate.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs/test/fargate/integ.ebs-volume-initialization-rate.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs/test/fargate/integ.ebs-volume-initialization-rate.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs/test/fargate/integ.ebs-volume-initialization-rate.ts
  packages/aws-cdk-lib/aws-ecs/README.md
  packages/aws-cdk-lib/aws-ecs/lib/base/base-service.ts
  packages/aws-cdk-lib/aws-ecs/lib/base/service-managed-volume.ts
  packages/aws-cdk-lib/aws-ecs/test/fargate/fargate-service.test.ts
Labels: p2, pr/needs-community-review, distinguished-contributor

#35283 chore(sqs): increase maximum message size limit to 1 MiB
  packages/aws-cdk-lib/aws-sqs/lib/queue.ts
  packages/aws-cdk-lib/aws-sqs/lib/validate-queue-props.ts
  packages/aws-cdk-lib/aws-sqs/test/sqs.test.ts
Labels: bug, p1, effort/small, contribution/core

#35291 docs(s3-deployment): document waitForDistributionInvalidation property in README
  packages/aws-cdk-lib/aws-s3-deployment/README.md
Labels: p2, contribution/core, admired-contributor

#35297 fix(ecs_patterns): openListener should be false when custom sg is provided
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs-patterns/test/fargate/integ.alb-fargate-service-smart-defaults.js.snapshot/albFargateServiceSmartDefaultsTestDefaultTestDeployAssert0E39EDDC.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs-patterns/test/fargate/integ.alb-fargate-service-smart-defaults.js.snapshot/albFargateServiceSmartDefaultsTestDefaultTestDeployAssert0E39EDDC.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs-patterns/test/fargate/integ.alb-fargate-service-smart-defaults.js.snapshot/asset.7131a84a4415494610e808e07b00bedc7d2578a973f5069309ad6a8a74cf00db.bundle/index.js
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs-patterns/test/fargate/integ.alb-fargate-service-smart-defaults.js.snapshot/aws-ecs-integ-alb-fg-smart-defaults.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs-patterns/test/fargate/integ.alb-fargate-service-smart-defaults.js.snapshot/aws-ecs-integ-alb-fg-smart-defaults.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs-patterns/test/fargate/integ.alb-fargate-service-smart-defaults.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs-patterns/test/fargate/integ.alb-fargate-service-smart-defaults.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs-patterns/test/fargate/integ.alb-fargate-service-smart-defaults.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs-patterns/test/fargate/integ.alb-fargate-service-smart-defaults.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs-patterns/test/fargate/integ.alb-fargate-service-smart-defaults.ts
  packages/aws-cdk-lib/aws-ecs-patterns/README.md
  packages/aws-cdk-lib/aws-ecs-patterns/lib/base/application-load-balanced-service-base.ts
  packages/aws-cdk-lib/aws-ecs-patterns/test/fargate/load-balanced-fargate-service.test.ts
  packages/aws-cdk-lib/cx-api/FEATURE_FLAGS.md
  packages/aws-cdk-lib/cx-api/lib/features.ts
  packages/aws-cdk-lib/cx-api/test/features.test.ts
  packages/aws-cdk-lib/recommended-feature-flags.json
Labels: bug, p1, effort/medium, contribution/core

#35310 docs: add a note to prevent additional feature changes to `OpenIdConnectProvider`
  packages/aws-cdk-lib/aws-iam/lib/oidc-provider.ts
Labels: p1, effort/small, contribution/core, documentation

#35013 chore(rds): aurora postgres 16.9, 15.13, 14.18, 13.21, sqlserver 13.00.6460.7.v1,14.00.3495.9.v1,15.00.4435.7.v1,16.00.4195.2.v1,16.00.4205.1.v1, mysql 8.0.43, 8.4.6
  packages/aws-cdk-lib/aws-rds/lib/cluster-engine.ts
  packages/aws-cdk-lib/aws-rds/lib/instance-engine.ts
  packages/aws-cdk-lib/aws-rds/test/cluster-engine.test.ts
Labels: bug, p2, effort/small, pr/needs-community-review, star-contributor

#35306 ci(project-sync): exclude updates from 'related-issues-bot-for-aws'
  tools/@aws-cdk/project-sync/lib/github.ts
  tools/@aws-cdk/project-sync/lib/issue-sync.ts
  tools/@aws-cdk/project-sync/lib/pr-sync.ts
  tools/@aws-cdk/project-sync/lib/utils.ts
Labels: p2, contribution/core, admired-contributor

#35082 chore(glue-alpha): add new G.12X, G.16X, R.1X, R.2X, R.4X, and R.8X worker types
  packages/@aws-cdk/aws-glue-alpha/lib/constants.ts
Labels: bug, p2, distinguished-contributor

#34765 feat(bedrock-alpha): add guardrails l2 construct
  packages/@aws-cdk/aws-bedrock-alpha/README.md
  packages/@aws-cdk/aws-bedrock-alpha/bedrock/agents/agent.ts
  packages/@aws-cdk/aws-bedrock-alpha/bedrock/guardrails/guardrail-filters.ts
  packages/@aws-cdk/aws-bedrock-alpha/bedrock/guardrails/guardrail-version.ts
  packages/@aws-cdk/aws-bedrock-alpha/bedrock/guardrails/guardrails.ts
  packages/@aws-cdk/aws-bedrock-alpha/bedrock/index.ts
  packages/@aws-cdk/aws-bedrock-alpha/test/bedrock/agents/agent.test.ts
  packages/@aws-cdk/aws-bedrock-alpha/test/bedrock/agents/integ.agent-guardrail.js.snapshot/BedrockAgentGuardrailDefaultTestDeployAssert799FCED7.assets.json
  packages/@aws-cdk/aws-bedrock-alpha/test/bedrock/agents/integ.agent-guardrail.js.snapshot/BedrockAgentGuardrailDefaultTestDeployAssert799FCED7.template.json
  packages/@aws-cdk/aws-bedrock-alpha/test/bedrock/agents/integ.agent-guardrail.js.snapshot/aws-cdk-bedrock-agent-guardrail-1.assets.json
  packages/@aws-cdk/aws-bedrock-alpha/test/bedrock/agents/integ.agent-guardrail.js.snapshot/aws-cdk-bedrock-agent-guardrail-1.template.json
  packages/@aws-cdk/aws-bedrock-alpha/test/bedrock/agents/integ.agent-guardrail.js.snapshot/cdk.out
  packages/@aws-cdk/aws-bedrock-alpha/test/bedrock/agents/integ.agent-guardrail.js.snapshot/integ.json
  packages/@aws-cdk/aws-bedrock-alpha/test/bedrock/agents/integ.agent-guardrail.js.snapshot/manifest.json
  packages/@aws-cdk/aws-bedrock-alpha/test/bedrock/agents/integ.agent-guardrail.js.snapshot/tree.json
  packages/@aws-cdk/aws-bedrock-alpha/test/bedrock/agents/integ.agent-guardrail.ts
  packages/@aws-cdk/aws-bedrock-alpha/test/bedrock/guardrails/guardrails.test.ts
  packages/@aws-cdk/aws-bedrock-alpha/test/bedrock/guardrails/integ.guardrails.js.snapshot/BedrockGuardrailDefaultTestDeployAssert40827DC2.assets.json
  packages/@aws-cdk/aws-bedrock-alpha/test/bedrock/guardrails/integ.guardrails.js.snapshot/BedrockGuardrailDefaultTestDeployAssert40827DC2.template.json
  packages/@aws-cdk/aws-bedrock-alpha/test/bedrock/guardrails/integ.guardrails.js.snapshot/aws-cdk-bedrock-guardrail-1.assets.json
  packages/@aws-cdk/aws-bedrock-alpha/test/bedrock/guardrails/integ.guardrails.js.snapshot/aws-cdk-bedrock-guardrail-1.template.json
  packages/@aws-cdk/aws-bedrock-alpha/test/bedrock/guardrails/integ.guardrails.js.snapshot/cdk.out
  packages/@aws-cdk/aws-bedrock-alpha/test/bedrock/guardrails/integ.guardrails.js.snapshot/integ.json
  packages/@aws-cdk/aws-bedrock-alpha/test/bedrock/guardrails/integ.guardrails.js.snapshot/manifest.json
  packages/@aws-cdk/aws-bedrock-alpha/test/bedrock/guardrails/integ.guardrails.js.snapshot/tree.json
  packages/@aws-cdk/aws-bedrock-alpha/test/bedrock/guardrails/integ.guardrails.ts
Labels: p1, contribution/core, beginning-contributor

#34781 docs(eks): clarify TaintEffect enum usage for AWS vs Kubernetes contexts
  packages/@aws-cdk/aws-eks-v2-alpha/lib/managed-nodegroup.ts
  packages/aws-cdk-lib/aws-eks/lib/managed-nodegroup.ts
Labels: bug, p2, effort/small, contribution/core

#35320 feat: update L1 CloudFormation resource definitions
  packages/aws-cdk-lib/package.json
  tools/@aws-cdk/spec2cdk/package.json
  yarn.lock
Labels: p2, dependencies, contribution/core, pr-linter/exempt-readme, pr-linter/exempt-test, pr-linter/exempt-integ-test, pr/needs-maintainer-review

#34783 docs(eks): fix heading levels for Auto Mode
  packages/@aws-cdk/aws-eks-v2-alpha/README.md
Labels: p2, pr/needs-community-review, distinguished-contributor

#34725 feat(core): `DockerBuildOptions` support network param
  packages/@aws-cdk/aws-lambda-go-alpha/lib/bundling.ts
  packages/@aws-cdk/aws-lambda-go-alpha/test/bundling.test.ts
  packages/@aws-cdk/aws-lambda-python-alpha/README.md
  packages/@aws-cdk/aws-lambda-python-alpha/lib/bundling.ts
  packages/@aws-cdk/aws-lambda-python-alpha/test/bundling.test.ts
  packages/@aws-cdk/aws-lambda-python-alpha/test/integ.function.custom-build.js.snapshot/asset.84802aa01d2d2c9e7d8d69705ee832c97f1ebad2d73c72be5c32d53f16cf90a7.bundle/index.js
  packages/@aws-cdk/aws-lambda-python-alpha/test/integ.function.custom-build.js.snapshot/asset.d9986c6e44adb9331064dc0efb9c1ffeeb94f6d16b46c34353881608a339a107.bundle/index.js
  packages/@aws-cdk/aws-lambda-python-alpha/test/integ.function.custom-build.js.snapshot/cdk-integ-lambda-custom-build.assets.json
  packages/@aws-cdk/aws-lambda-python-alpha/test/integ.function.custom-build.js.snapshot/cdk-integ-lambda-custom-build.template.json
  packages/@aws-cdk/aws-lambda-python-alpha/test/integ.function.custom-build.js.snapshot/cdk.out
  packages/@aws-cdk/aws-lambda-python-alpha/test/integ.function.custom-build.js.snapshot/integ.json
  packages/@aws-cdk/aws-lambda-python-alpha/test/integ.function.custom-build.js.snapshot/lambdapythoncustombuildDefaultTestDeployAssert3F59C307.assets.json
  packages/@aws-cdk/aws-lambda-python-alpha/test/integ.function.custom-build.js.snapshot/lambdapythoncustombuildDefaultTestDeployAssert3F59C307.template.json
  packages/@aws-cdk/aws-lambda-python-alpha/test/integ.function.custom-build.js.snapshot/manifest.json
  packages/@aws-cdk/aws-lambda-python-alpha/test/integ.function.custom-build.js.snapshot/tree.json
  packages/@aws-cdk/aws-lambda-python-alpha/test/integ.function.custom-build.ts
  packages/@aws-cdk/aws-lambda-python-alpha/test/integ.function.project.js.snapshot/asset.84802aa01d2d2c9e7d8d69705ee832c97f1ebad2d73c72be5c32d53f16cf90a7.bundle/index.js
  packages/@aws-cdk/aws-lambda-python-alpha/test/integ.function.project.js.snapshot/asset.d9986c6e44adb9331064dc0efb9c1ffeeb94f6d16b46c34353881608a339a107.bundle/index.js
  packages/@aws-cdk/aws-lambda-python-alpha/test/integ.function.project.js.snapshot/cdk-integ-lambda-function-project.assets.json
  packages/@aws-cdk/aws-lambda-python-alpha/test/integ.function.project.js.snapshot/cdk-integ-lambda-function-project.template.json
  packages/@aws-cdk/aws-lambda-python-alpha/test/integ.function.project.js.snapshot/cdk.out
  packages/@aws-cdk/aws-lambda-python-alpha/test/integ.function.project.js.snapshot/integ.json
  packages/@aws-cdk/aws-lambda-python-alpha/test/integ.function.project.js.snapshot/lambdapythonprojectDefaultTestDeployAssert35F9254C.assets.json
  packages/@aws-cdk/aws-lambda-python-alpha/test/integ.function.project.js.snapshot/lambdapythonprojectDefaultTestDeployAssert35F9254C.template.json
  packages/@aws-cdk/aws-lambda-python-alpha/test/integ.function.project.js.snapshot/manifest.json
  packages/@aws-cdk/aws-lambda-python-alpha/test/integ.function.project.js.snapshot/tree.json
  packages/@aws-cdk/aws-lambda-python-alpha/test/integ.function.project.ts
  packages/@aws-cdk/aws-lambda-python-alpha/test/lambda-handler-custom-build/Dockerfile
  packages/aws-cdk-lib/aws-lambda-nodejs/lib/bundling.ts
  packages/aws-cdk-lib/aws-lambda-nodejs/test/bundling.test.ts
  packages/aws-cdk-lib/core/lib/bundling.ts
  packages/aws-cdk-lib/core/test/bundling.test.ts
Labels: p2, feature-request, pr/needs-community-review, star-contributor

#35349 chore(merge-back): 2.213.0
  CHANGELOG.v2.alpha.md
  CHANGELOG.v2.md
  version.v2.json
Labels: p2, contribution/core, pr/no-squash, auto-approve, pr/needs-maintainer-review

#35340 docs(glue-alpha): fix inconsistent structures in README
  packages/@aws-cdk/aws-glue-alpha/README.md
Labels: p2, contribution/core
