Repository aws/aws-cdk, pull requests merged in 2025-06, with the labels that each got.

#33811 feat(sns-subscriptions): support Amazon Data Firehose subscription
  packages/@aws-cdk-testing/framework-integ/test/aws-sns-subscriptions/test/integ.firehose-cross-region.js.snapshot/asset.44e9c4d7a5d3fd2d677e1a7e416b2b56f6b0104bd5eff9cac5557b4c65a9dc61/index.js
  packages/@aws-cdk-testing/framework-integ/test/aws-sns-subscriptions/test/integ.firehose-cross-region.js.snapshot/aws-cdk-sns-firehose-firehosestack.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-sns-subscriptions/test/integ.firehose-cross-region.js.snapshot/aws-cdk-sns-firehose-firehosestack.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-sns-subscriptions/test/integ.firehose-cross-region.js.snapshot/aws-cdk-sns-firehose-topicstack.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-sns-subscriptions/test/integ.firehose-cross-region.js.snapshot/aws-cdk-sns-firehose-topicstack.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-sns-subscriptions/test/integ.firehose-cross-region.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-sns-subscriptions/test/integ.firehose-cross-region.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-sns-subscriptions/test/integ.firehose-cross-region.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-sns-subscriptions/test/integ.firehose-cross-region.js.snapshot/snsfirehoseintegDefaultTestDeployAssert15062DA5.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-sns-subscriptions/test/integ.firehose-cross-region.js.snapshot/snsfirehoseintegDefaultTestDeployAssert15062DA5.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-sns-subscriptions/test/integ.firehose-cross-region.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-sns-subscriptions/test/integ.firehose-cross-region.ts
  packages/@aws-cdk-testing/framework-integ/test/aws-sns-subscriptions/test/integ.firehose.js.snapshot/asset.44e9c4d7a5d3fd2d677e1a7e416b2b56f6b0104bd5eff9cac5557b4c65a9dc61/index.js
  packages/@aws-cdk-testing/framework-integ/test/aws-sns-subscriptions/test/integ.firehose.js.snapshot/asset.97484721f29e34bf38d7a459804dd2d2a8dea6f8c27d7531e215bf4274fbc895.bundle/index.js
  packages/@aws-cdk-testing/framework-integ/test/aws-sns-subscriptions/test/integ.firehose.js.snapshot/aws-cdk-sns-firehose.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-sns-subscriptions/test/integ.firehose.js.snapshot/aws-cdk-sns-firehose.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-sns-subscriptions/test/integ.firehose.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-sns-subscriptions/test/integ.firehose.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-sns-subscriptions/test/integ.firehose.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-sns-subscriptions/test/integ.firehose.js.snapshot/snsfirehoseintegDefaultTestDeployAssert15062DA5.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-sns-subscriptions/test/integ.firehose.js.snapshot/snsfirehoseintegDefaultTestDeployAssert15062DA5.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-sns-subscriptions/test/integ.firehose.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-sns-subscriptions/test/integ.firehose.ts
  packages/aws-cdk-lib/aws-sns-subscriptions/README.md
  packages/aws-cdk-lib/aws-sns-subscriptions/lib/firehose.ts
  packages/aws-cdk-lib/aws-sns-subscriptions/lib/index.ts
  packages/aws-cdk-lib/aws-sns-subscriptions/lib/lambda.ts
  packages/aws-cdk-lib/aws-sns-subscriptions/lib/private/util.ts
  packages/aws-cdk-lib/aws-sns-subscriptions/lib/sqs.ts
  packages/aws-cdk-lib/aws-sns-subscriptions/test/firehose.test.ts
Labels: p2, feature-request, effort/small, pr/needs-community-review, star-contributor

#34501 feat(msk): support Kafka 4.0
  packages/@aws-cdk/aws-msk-alpha/README.md
  packages/@aws-cdk/aws-msk-alpha/lib/cluster-version.ts
  packages/@aws-cdk/aws-msk-alpha/test/cluster.test.ts
  packages/@aws-cdk/aws-msk-alpha/test/integ.cluster-version.js.snapshot/KafkaVersionTestStack.assets.json
  packages/@aws-cdk/aws-msk-alpha/test/integ.cluster-version.js.snapshot/KafkaVersionTestStack.template.json
  packages/@aws-cdk/aws-msk-alpha/test/integ.cluster-version.js.snapshot/integ.json
  packages/@aws-cdk/aws-msk-alpha/test/integ.cluster-version.js.snapshot/manifest.json
  packages/@aws-cdk/aws-msk-alpha/test/integ.cluster-version.js.snapshot/tree.json
  packages/@aws-cdk/aws-msk-alpha/test/integ.cluster-version.ts
Labels: p2, distinguished-contributor, pr/needs-maintainer-review

#34594 feat: update L1 CloudFormation resource definitions
  packages/aws-cdk-lib/package.json
  tools/@aws-cdk/spec2cdk/package.json
  yarn.lock
Labels: p2, dependencies, contribution/core, pr-linter/exempt-readme, pr-linter/exempt-test, pr-linter/exempt-integ-test, pr/needs-maintainer-review

#34613 fix(lambda): disable aws-lambda:useCdkManagedLogGroup feature flag when not set
  packages/aws-cdk-lib/aws-lambda/test/function.test.ts
  packages/aws-cdk-lib/cx-api/FEATURE_FLAGS.md
  packages/aws-cdk-lib/cx-api/lib/features.ts
  packages/aws-cdk-lib/cx-api/test/features.test.ts
  packages/aws-cdk-lib/recommended-feature-flags.json
Labels: bug, p0, contribution/core, pr-linter/exempt-integ-test

#34609 feat(synthetics): playwright 2.0 runtime
  packages/@aws-cdk-testing/framework-integ/test/aws-synthetics/test/integ.canary.js.snapshot/IntegCanaryTestDefaultTestDeployAssert3AD5A094.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-synthetics/test/integ.canary.js.snapshot/IntegCanaryTestDefaultTestDeployAssert3AD5A094.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-synthetics/test/integ.canary.js.snapshot/asset.5b7ddd1e0b18514d45c25a44b162f82431b091da093fb35e4b814bbba093c506.bundle/index.js
  packages/@aws-cdk-testing/framework-integ/test/aws-synthetics/test/integ.canary.js.snapshot/asset.b1b777dcb79a2fa2790059927207d10bf5f4747d6dd1516e2780726d9d6fa820.zip
  packages/@aws-cdk-testing/framework-integ/test/aws-synthetics/test/integ.canary.js.snapshot/canary-one.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-synthetics/test/integ.canary.js.snapshot/canary-one.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-synthetics/test/integ.canary.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-synthetics/test/integ.canary.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-synthetics/test/integ.canary.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-synthetics/test/integ.canary.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-synthetics/test/integ.canary.ts
  packages/aws-cdk-lib/aws-synthetics/lib/runtime.ts
  packages/aws-cdk-lib/aws-synthetics/test/canary.test.ts
Labels: p2, pr/needs-community-review, pr-linter/exempt-readme, distinguished-contributor, pr-linter/exemption-requested

#34621 chore(merge-back): 2.200.1
  CHANGELOG.v2.alpha.md
  CHANGELOG.v2.md
  packages/aws-cdk-lib/aws-iam/lib/oidc-provider-native.ts
  packages/aws-cdk-lib/core/lib/analytics-data-source/classes.ts
  packages/aws-cdk-lib/core/lib/analytics-data-source/enums/module-enumlikes.json
  version.v2.json
Labels: p2, pr/needs-community-review, pr/no-squash, auto-approve

#34623 chore(rds): add MariaDB versions 10.11.13 and 11.4.7
  packages/aws-cdk-lib/aws-rds/lib/instance-engine.ts
  packages/aws-cdk-lib/aws-rds/test/instance-engine.test.ts
Labels: p2, distinguished-contributor

#34626 docs(ec2): correct documentation for launch template userData property
  packages/aws-cdk-lib/aws-ec2/lib/launch-template.ts
Labels: p2, contribution/core

#34628 chore: npm-check-updates && yarn upgrade
  packages/@aws-cdk-testing/framework-integ/package.json
  packages/@aws-cdk/aws-eks-v2-alpha/package.json
  packages/aws-cdk-lib/package.json
  tools/@aws-cdk/cdk-build-tools/package.json
  yarn.lock
Labels: p2, dependencies, contribution/core, auto-approve

#31586 feat(core): support adding additional cache key to cdk context values
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.machine-image-cached.js.snapshot/cdk-ec2-machine-image-cached.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.machine-image-cached.js.snapshot/cdk-ec2-machine-image-cached.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.machine-image-cached.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.machine-image-cached.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.machine-image-cached.js.snapshot/integec2machineimagecachedDefaultTestDeployAssert24B647BE.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.machine-image-cached.js.snapshot/integec2machineimagecachedDefaultTestDeployAssert24B647BE.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.machine-image-cached.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.machine-image-cached.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.machine-image-cached.ts
  packages/aws-cdk-lib/aws-ec2/README.md
  packages/aws-cdk-lib/aws-ec2/lib/machine-image/amazon-linux-2022.ts
  packages/aws-cdk-lib/aws-ec2/lib/machine-image/amazon-linux-2023.ts
  packages/aws-cdk-lib/aws-ec2/lib/machine-image/amazon-linux2.ts
  packages/aws-cdk-lib/aws-ec2/lib/machine-image/common.ts
  packages/aws-cdk-lib/aws-ec2/lib/machine-image/machine-image.ts
  packages/aws-cdk-lib/aws-ec2/lib/machine-image/utils.ts
  packages/aws-cdk-lib/aws-ec2/test/machine-image.test.ts
  packages/aws-cdk-lib/aws-ecs/README.md
  packages/aws-cdk-lib/aws-ecs/lib/amis.ts
  packages/aws-cdk-lib/aws-ssm/README.md
  packages/aws-cdk-lib/aws-ssm/lib/parameter.ts
  packages/aws-cdk-lib/aws-ssm/test/parameter.test.ts
  packages/aws-cdk-lib/core/lib/context-provider.ts
Labels: p2, feature-request, effort/medium, beginning-contributor, skip-abstractions-board

#34620 fix: typo in jsdoc of noncurrentVersionTransitions property
  packages/aws-cdk-lib/aws-s3/lib/rule.ts
Labels: p2, pr-linter/exempt-test, pr-linter/exempt-integ-test, beginning-contributor

#34596 feat(ec2): support Firehose `IDeliveryStream` as flow log destination
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.vpc-flow-logs-firehose.js.snapshot/FlowLogsDefaultTestDeployAssert6AFD1854.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.vpc-flow-logs-firehose.js.snapshot/FlowLogsDefaultTestDeployAssert6AFD1854.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.vpc-flow-logs-firehose.js.snapshot/FlowLogsTestStack.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.vpc-flow-logs-firehose.js.snapshot/FlowLogsTestStack.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.vpc-flow-logs-firehose.js.snapshot/asset.44e9c4d7a5d3fd2d677e1a7e416b2b56f6b0104bd5eff9cac5557b4c65a9dc61/index.js
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.vpc-flow-logs-firehose.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.vpc-flow-logs-firehose.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.vpc-flow-logs-firehose.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.vpc-flow-logs-firehose.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.vpc-flow-logs-firehose.ts
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.vpc-flow-logs-kinesis.js.snapshot/asset.a1acfc2b5f4f6b183fd2bb9863f486bc5edef6a357b355a070d9a0e502df418c/__entrypoint__.js
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.vpc-flow-logs-kinesis.js.snapshot/asset.a1acfc2b5f4f6b183fd2bb9863f486bc5edef6a357b355a070d9a0e502df418c/index.js
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.vpc-flow-logs-kinesis.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.vpc-flow-logs-kinesis.ts
  packages/aws-cdk-lib/aws-ec2/README.md
  packages/aws-cdk-lib/aws-ec2/lib/vpc-flow-logs.ts
  packages/aws-cdk-lib/aws-ec2/test/vpc-flow-logs.test.ts
  packages/aws-cdk-lib/aws-kinesisfirehose/lib/delivery-stream.ts
Labels: p2, pr/needs-community-review, distinguished-contributor, pr/reviewer-clarification-requested

#33604 feat(codepipeline-actions): native Amazon EC2 deployment support
  packages/@aws-cdk-testing/framework-integ/test/aws-codepipeline-actions/test/ec2-deploy-artifacts/inline/index.html
  packages/@aws-cdk-testing/framework-integ/test/aws-codepipeline-actions/test/ec2-deploy-artifacts/inline/scripts/post-deploy.sh
  packages/@aws-cdk-testing/framework-integ/test/aws-codepipeline-actions/test/ec2-deploy-artifacts/inline/scripts/pre-deploy.sh
  packages/@aws-cdk-testing/framework-integ/test/aws-codepipeline-actions/test/integ.pipeline-ec2-deploy-ssm-managed.js.snapshot/asset.44e9c4d7a5d3fd2d677e1a7e416b2b56f6b0104bd5eff9cac5557b4c65a9dc61/index.js
  packages/@aws-cdk-testing/framework-integ/test/aws-codepipeline-actions/test/integ.pipeline-ec2-deploy-ssm-managed.js.snapshot/asset.93e64a8bca22f133010f6b56b48971e7b52020dc565d94d95683e48ad4396ce0/index.html
  packages/@aws-cdk-testing/framework-integ/test/aws-codepipeline-actions/test/integ.pipeline-ec2-deploy-ssm-managed.js.snapshot/asset.93e64a8bca22f133010f6b56b48971e7b52020dc565d94d95683e48ad4396ce0/scripts/post-deploy.sh
  packages/@aws-cdk-testing/framework-integ/test/aws-codepipeline-actions/test/integ.pipeline-ec2-deploy-ssm-managed.js.snapshot/asset.93e64a8bca22f133010f6b56b48971e7b52020dc565d94d95683e48ad4396ce0/scripts/pre-deploy.sh
  packages/@aws-cdk-testing/framework-integ/test/aws-codepipeline-actions/test/integ.pipeline-ec2-deploy-ssm-managed.js.snapshot/asset.97484721f29e34bf38d7a459804dd2d2a8dea6f8c27d7531e215bf4274fbc895.bundle/index.js
  packages/@aws-cdk-testing/framework-integ/test/aws-codepipeline-actions/test/integ.pipeline-ec2-deploy-ssm-managed.js.snapshot/asset.9a1fcb4a7ecba81ad70e9d3fb241f6794497da945dae5f25924e4dd002b65f2d/index.py
  packages/@aws-cdk-testing/framework-integ/test/aws-codepipeline-actions/test/integ.pipeline-ec2-deploy-ssm-managed.js.snapshot/asset.b8ab94266984268614c3fb2824a1c3a55395746c48b28c003b08bc1d08688f3e.zip
  packages/@aws-cdk-testing/framework-integ/test/aws-codepipeline-actions/test/integ.pipeline-ec2-deploy-ssm-managed.js.snapshot/aws-cdk-codepipeline-ec2-deploy-ssm-managed-node.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-codepipeline-actions/test/integ.pipeline-ec2-deploy-ssm-managed.js.snapshot/aws-cdk-codepipeline-ec2-deploy-ssm-managed-node.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-codepipeline-actions/test/integ.pipeline-ec2-deploy-ssm-managed.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-codepipeline-actions/test/integ.pipeline-ec2-deploy-ssm-managed.js.snapshot/ec2deployactionssmmanagednodeintegDefaultTestDeployAssert57618968.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-codepipeline-actions/test/integ.pipeline-ec2-deploy-ssm-managed.js.snapshot/ec2deployactionssmmanagednodeintegDefaultTestDeployAssert57618968.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-codepipeline-actions/test/integ.pipeline-ec2-deploy-ssm-managed.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-codepipeline-actions/test/integ.pipeline-ec2-deploy-ssm-managed.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-codepipeline-actions/test/integ.pipeline-ec2-deploy-ssm-managed.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-codepipeline-actions/test/integ.pipeline-ec2-deploy-ssm-managed.ts
  packages/@aws-cdk-testing/framework-integ/test/aws-codepipeline-actions/test/integ.pipeline-ec2-deploy.js.snapshot/asset.44e9c4d7a5d3fd2d677e1a7e416b2b56f6b0104bd5eff9cac5557b4c65a9dc61/index.js
  packages/@aws-cdk-testing/framework-integ/test/aws-codepipeline-actions/test/integ.pipeline-ec2-deploy.js.snapshot/asset.93e64a8bca22f133010f6b56b48971e7b52020dc565d94d95683e48ad4396ce0/index.html
  packages/@aws-cdk-testing/framework-integ/test/aws-codepipeline-actions/test/integ.pipeline-ec2-deploy.js.snapshot/asset.93e64a8bca22f133010f6b56b48971e7b52020dc565d94d95683e48ad4396ce0/scripts/post-deploy.sh
  packages/@aws-cdk-testing/framework-integ/test/aws-codepipeline-actions/test/integ.pipeline-ec2-deploy.js.snapshot/asset.93e64a8bca22f133010f6b56b48971e7b52020dc565d94d95683e48ad4396ce0/scripts/pre-deploy.sh
  packages/@aws-cdk-testing/framework-integ/test/aws-codepipeline-actions/test/integ.pipeline-ec2-deploy.js.snapshot/asset.97484721f29e34bf38d7a459804dd2d2a8dea6f8c27d7531e215bf4274fbc895.bundle/index.js
  packages/@aws-cdk-testing/framework-integ/test/aws-codepipeline-actions/test/integ.pipeline-ec2-deploy.js.snapshot/asset.9a1fcb4a7ecba81ad70e9d3fb241f6794497da945dae5f25924e4dd002b65f2d/index.py
  packages/@aws-cdk-testing/framework-integ/test/aws-codepipeline-actions/test/integ.pipeline-ec2-deploy.js.snapshot/asset.b8ab94266984268614c3fb2824a1c3a55395746c48b28c003b08bc1d08688f3e.zip
  packages/@aws-cdk-testing/framework-integ/test/aws-codepipeline-actions/test/integ.pipeline-ec2-deploy.js.snapshot/aws-cdk-codepipeline-ec2-deploy.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-codepipeline-actions/test/integ.pipeline-ec2-deploy.js.snapshot/aws-cdk-codepipeline-ec2-deploy.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-codepipeline-actions/test/integ.pipeline-ec2-deploy.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-codepipeline-actions/test/integ.pipeline-ec2-deploy.js.snapshot/ec2deployactionintegDefaultTestDeployAssert9BE1FE4E.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-codepipeline-actions/test/integ.pipeline-ec2-deploy.js.snapshot/ec2deployactionintegDefaultTestDeployAssert9BE1FE4E.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-codepipeline-actions/test/integ.pipeline-ec2-deploy.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-codepipeline-actions/test/integ.pipeline-ec2-deploy.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-codepipeline-actions/test/integ.pipeline-ec2-deploy.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-codepipeline-actions/test/integ.pipeline-ec2-deploy.ts
  packages/aws-cdk-lib/aws-codepipeline-actions/README.md
  packages/aws-cdk-lib/aws-codepipeline-actions/lib/ec2/deploy-action.ts
  packages/aws-cdk-lib/aws-codepipeline-actions/lib/index.ts
  packages/aws-cdk-lib/aws-codepipeline-actions/test/ec2/ec2-deploy-action.test.ts
Labels: p2, feature-request, effort/medium, star-contributor

#34633 docs: reflect aws-cdk-lib and CLI split in the contribution guide
  CONTRIBUTING.md
Labels: p2, effort/small, beginning-contributor

#34638 chore: updated onEvent example implementation to follow better coding practices
  packages/@aws-cdk/example-construct-library/lib/example-resource.ts
Labels: p2, contribution/core, pr/needs-maintainer-review

#33982 feat(rds): `DatabaseInstanceFromSnapshot` support `clusterSnapshotIdentifier`
  packages/@aws-cdk-testing/framework-integ/test/aws-rds/test/integ.instance-from-cluster-snapshot.js.snapshot/cdk-instance-from-cluster-snapshot.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-rds/test/integ.instance-from-cluster-snapshot.js.snapshot/cdk-instance-from-cluster-snapshot.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-rds/test/integ.instance-from-cluster-snapshot.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-rds/test/integ.instance-from-cluster-snapshot.js.snapshot/cdkinstancefromclustersnapshottestDefaultTestDeployAssertB916CEB9.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-rds/test/integ.instance-from-cluster-snapshot.js.snapshot/cdkinstancefromclustersnapshottestDefaultTestDeployAssertB916CEB9.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-rds/test/integ.instance-from-cluster-snapshot.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-rds/test/integ.instance-from-cluster-snapshot.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-rds/test/integ.instance-from-cluster-snapshot.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-rds/test/integ.instance-from-cluster-snapshot.ts
  packages/aws-cdk-lib/aws-rds/README.md
  packages/aws-cdk-lib/aws-rds/lib/instance.ts
  packages/aws-cdk-lib/aws-rds/test/instance.test.ts
Labels: bug, p2, effort/medium, admired-contributor

#34625 feat(stepfunctions): add support for Jsonata expressions to Map.ItemSelector
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions/test/integ.map-jsonata-itemselector.js.snapshot/asset.97484721f29e34bf38d7a459804dd2d2a8dea6f8c27d7531e215bf4274fbc895.bundle/index.js
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions/test/integ.map-jsonata-itemselector.js.snapshot/cdk-stepfunctions-map-jsonata-itemselector-stack.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions/test/integ.map-jsonata-itemselector.js.snapshot/cdk-stepfunctions-map-jsonata-itemselector-stack.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions/test/integ.map-jsonata-itemselector.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions/test/integ.map-jsonata-itemselector.js.snapshot/cdkstepfunctionsmapitemselectorintegDefaultTestDeployAssertB0D765C3.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions/test/integ.map-jsonata-itemselector.js.snapshot/cdkstepfunctionsmapitemselectorintegDefaultTestDeployAssertB0D765C3.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions/test/integ.map-jsonata-itemselector.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions/test/integ.map-jsonata-itemselector.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions/test/integ.map-jsonata-itemselector.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions/test/integ.map-jsonata-itemselector.ts
  packages/aws-cdk-lib/aws-stepfunctions/README.md
  packages/aws-cdk-lib/aws-stepfunctions/lib/states/map-base.ts
  packages/aws-cdk-lib/aws-stepfunctions/lib/states/map.ts
  packages/aws-cdk-lib/aws-stepfunctions/test/distributed-map.test.ts
  packages/aws-cdk-lib/aws-stepfunctions/test/map.test.ts
Labels: bug, p1, effort/small, contribution/core, pr/needs-maintainer-review

#33802 fix(cloudfront): use wildcard when grant some cloudfront permission
  packages/@aws-cdk-testing/framework-integ/test/aws-cloudfront/test/integ.distribution-basic.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-cloudfront/test/integ.distribution-basic.js.snapshot/integ-distribution-basic.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-cloudfront/test/integ.distribution-basic.js.snapshot/integ-distribution-basic.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-cloudfront/test/integ.distribution-basic.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-cloudfront/test/integ.distribution-basic.js.snapshot/integdistributionbasicdistributionbasictestDefaultTestDeployAssert2D53EBF0.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-cloudfront/test/integ.distribution-basic.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-cloudfront/test/integ.distribution-basic.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-cloudfront/test/integ.distribution-basic.ts
  packages/aws-cdk-lib/aws-cloudfront/lib/distribution.ts
  packages/aws-cdk-lib/aws-cloudfront/lib/private/utils.ts
  packages/aws-cdk-lib/aws-cloudfront/test/distribution.test.ts
Labels: bug, p2, effort/small, pr/needs-community-review, admired-contributor

#34663 chore(synthetics): selenium 6.0 runtime
  packages/@aws-cdk-testing/framework-integ/test/aws-synthetics/test/integ.canary.js.snapshot/IntegCanaryTestDefaultTestDeployAssert3AD5A094.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-synthetics/test/integ.canary.js.snapshot/IntegCanaryTestDefaultTestDeployAssert3AD5A094.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-synthetics/test/integ.canary.js.snapshot/asset.97484721f29e34bf38d7a459804dd2d2a8dea6f8c27d7531e215bf4274fbc895.bundle/index.js
  packages/@aws-cdk-testing/framework-integ/test/aws-synthetics/test/integ.canary.js.snapshot/asset.b1b777dcb79a2fa2790059927207d10bf5f4747d6dd1516e2780726d9d6fa820.zip
  packages/@aws-cdk-testing/framework-integ/test/aws-synthetics/test/integ.canary.js.snapshot/canary-one.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-synthetics/test/integ.canary.js.snapshot/canary-one.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-synthetics/test/integ.canary.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-synthetics/test/integ.canary.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-synthetics/test/integ.canary.ts
  packages/aws-cdk-lib/aws-synthetics/lib/runtime.ts
  packages/aws-cdk-lib/aws-synthetics/test/canary.test.ts
Labels: p2, star-contributor

#34608 feat(synthetics): safe canary update
  packages/@aws-cdk-testing/framework-integ/test/aws-synthetics/test/integ.canary-dryrun-update.js.snapshot/SyntheticsCanaryDryRunAndUpdateDefaultTestDeployAssertAF68FFC6.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-synthetics/test/integ.canary-dryrun-update.js.snapshot/SyntheticsCanaryDryRunAndUpdateDefaultTestDeployAssertAF68FFC6.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-synthetics/test/integ.canary-dryrun-update.js.snapshot/SyntheticsCanaryDryRunAndUpdateStack.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-synthetics/test/integ.canary-dryrun-update.js.snapshot/SyntheticsCanaryDryRunAndUpdateStack.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-synthetics/test/integ.canary-dryrun-update.js.snapshot/asset.5178413cfe8db00b2d5dcfa9be417e934c64601d0da3031d88c145c8293bc27f/canary.mjs
  packages/@aws-cdk-testing/framework-integ/test/aws-synthetics/test/integ.canary-dryrun-update.js.snapshot/asset.5178413cfe8db00b2d5dcfa9be417e934c64601d0da3031d88c145c8293bc27f/nodejs/node_modules/canary.js
  packages/@aws-cdk-testing/framework-integ/test/aws-synthetics/test/integ.canary-dryrun-update.js.snapshot/asset.5178413cfe8db00b2d5dcfa9be417e934c64601d0da3031d88c145c8293bc27f/nodejs/node_modules/folder/canary.js
  packages/@aws-cdk-testing/framework-integ/test/aws-synthetics/test/integ.canary-dryrun-update.js.snapshot/asset.5178413cfe8db00b2d5dcfa9be417e934c64601d0da3031d88c145c8293bc27f/playwright/canary.mjs
  packages/@aws-cdk-testing/framework-integ/test/aws-synthetics/test/integ.canary-dryrun-update.js.snapshot/asset.5178413cfe8db00b2d5dcfa9be417e934c64601d0da3031d88c145c8293bc27f/python/canary.py
  packages/@aws-cdk-testing/framework-integ/test/aws-synthetics/test/integ.canary-dryrun-update.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-synthetics/test/integ.canary-dryrun-update.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-synthetics/test/integ.canary-dryrun-update.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-synthetics/test/integ.canary-dryrun-update.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-synthetics/test/integ.canary-dryrun-update.ts
  packages/aws-cdk-lib/aws-synthetics/README.md
  packages/aws-cdk-lib/aws-synthetics/lib/canary.ts
  packages/aws-cdk-lib/aws-synthetics/test/canary.test.ts
Labels: p2, distinguished-contributor

#34648 fix(logs): exposed metric from the metric filter will now include the dimension map
  packages/@aws-cdk-testing/framework-integ/test/aws-logs/test/integ.expose-metric-with-dimensions.js.snapshot/aws-cdk-expose-metric-with-dimensions-integ.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-logs/test/integ.expose-metric-with-dimensions.js.snapshot/aws-cdk-expose-metric-with-dimensions-integ.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-logs/test/integ.expose-metric-with-dimensions.js.snapshot/awscdkexposemetricwithdimensionsintegExposeMetricWithDimensionsTestDefaultTestDeployAssert42449B59.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-logs/test/integ.expose-metric-with-dimensions.js.snapshot/awscdkexposemetricwithdimensionsintegExposeMetricWithDimensionsTestDefaultTestDeployAssert42449B59.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-logs/test/integ.expose-metric-with-dimensions.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-logs/test/integ.expose-metric-with-dimensions.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-logs/test/integ.expose-metric-with-dimensions.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-logs/test/integ.expose-metric-with-dimensions.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-logs/test/integ.expose-metric-with-dimensions.ts
  packages/aws-cdk-lib/aws-logs/README.md
  packages/aws-cdk-lib/aws-logs/lib/metric-filter.ts
  packages/aws-cdk-lib/aws-logs/test/metricfilter.test.ts
  yarn.lock
Labels: bug, p2, pr/needs-community-review, beginning-contributor

#34665 revert(ec2): support Firehose `IDeliveryStream` as flow log destination
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.vpc-flow-logs-firehose.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.vpc-flow-logs-firehose.ts
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.vpc-flow-logs-kinesis.js.snapshot/FlowLogsDefaultTestDeployAssert6AFD1854.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.vpc-flow-logs-kinesis.js.snapshot/FlowLogsDefaultTestDeployAssert6AFD1854.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.vpc-flow-logs-kinesis.js.snapshot/FlowLogsTestStack.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.vpc-flow-logs-kinesis.js.snapshot/FlowLogsTestStack.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.vpc-flow-logs-kinesis.js.snapshot/asset.44e9c4d7a5d3fd2d677e1a7e416b2b56f6b0104bd5eff9cac5557b4c65a9dc61/index.js
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.vpc-flow-logs-kinesis.js.snapshot/asset.a1acfc2b5f4f6b183fd2bb9863f486bc5edef6a357b355a070d9a0e502df418c/__entrypoint__.js
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.vpc-flow-logs-kinesis.js.snapshot/asset.a1acfc2b5f4f6b183fd2bb9863f486bc5edef6a357b355a070d9a0e502df418c/index.js
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.vpc-flow-logs-kinesis.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.vpc-flow-logs-kinesis.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.vpc-flow-logs-kinesis.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.vpc-flow-logs-kinesis.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.vpc-flow-logs-kinesis.ts
  packages/aws-cdk-lib/aws-ec2/README.md
  packages/aws-cdk-lib/aws-ec2/lib/vpc-flow-logs.ts
  packages/aws-cdk-lib/aws-ec2/test/vpc-flow-logs.test.ts
  packages/aws-cdk-lib/aws-kinesisfirehose/lib/delivery-stream.ts
Labels: p2, contribution/core

#34598 chore(rds): mariadb add versions 10.5.29 and 10.6.22, postgres add versions 11.22-rds.20250508 and 12.22-rds.20250508
  packages/aws-cdk-lib/aws-rds/lib/instance-engine.ts
  packages/aws-cdk-lib/aws-rds/test/instance-engine.test.ts
Labels: p2, star-contributor, pr/needs-maintainer-review

#34489 chore: update documentation for .NET requirement and scripts
  CONTRIBUTING.md
  README.md
  scripts/check-build-prerequisites.sh
Labels: p2, pr/needs-community-review, beginning-contributor, pr/reviewer-clarification-requested

#34676 docs(cloudfront): specify that cloudront does not support updating the key
  packages/aws-cdk-lib/aws-cloudfront/README.md
Labels: p2, contribution/core, pr/needs-maintainer-review

#34680 fix(opensearch): opensearchservice: existing integ test is failing
  packages/@aws-cdk-testing/framework-integ/test/aws-opensearchservice/test/integ.opensearch.gp3.js.snapshot/IntegDefaultTestDeployAssert4E6713E1.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-opensearchservice/test/integ.opensearch.gp3.js.snapshot/cdk-integ-opensearch-gp3.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-opensearchservice/test/integ.opensearch.gp3.js.snapshot/cdk-integ-opensearch-gp3.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-opensearchservice/test/integ.opensearch.gp3.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-opensearchservice/test/integ.opensearch.gp3.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-opensearchservice/test/integ.opensearch.gp3.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-opensearchservice/test/integ.opensearch.gp3.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-opensearchservice/test/integ.opensearch.gp3.ts
Labels: p2, contribution/core, @aws-cdk/aws-opensearch, pr/needs-maintainer-review

#33879 fix(apigateway): correct `JsonSchema.additionalItems` property type
  allowed-breaking-changes.txt
  packages/@aws-cdk-testing/framework-integ/test/aws-apigateway/test/integ.model-schema-additional-items.js.snapshot/ModelSchemaAdditionalItemsTestDefaultTestDeployAssert81CF581B.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-apigateway/test/integ.model-schema-additional-items.js.snapshot/ModelSchemaAdditionalItemsTestDefaultTestDeployAssert81CF581B.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-apigateway/test/integ.model-schema-additional-items.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-apigateway/test/integ.model-schema-additional-items.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-apigateway/test/integ.model-schema-additional-items.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-apigateway/test/integ.model-schema-additional-items.js.snapshot/model-schema-additional-items-test.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-apigateway/test/integ.model-schema-additional-items.js.snapshot/model-schema-additional-items-test.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-apigateway/test/integ.model-schema-additional-items.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-apigateway/test/integ.model-schema-additional-items.ts
  packages/aws-cdk-lib/aws-apigateway/lib/json-schema.ts
  packages/aws-cdk-lib/aws-apigateway/test/restapi.test.ts
Labels: bug, p2, pr/needs-community-review, effort/medium, beginning-contributor

#34656 feat(amplify): add skew protection feature for Amplify branches
  packages/@aws-cdk/aws-amplify-alpha/README.md
  packages/@aws-cdk/aws-amplify-alpha/lib/branch.ts
  packages/@aws-cdk/aws-amplify-alpha/test/branch.test.ts
  packages/@aws-cdk/aws-amplify-alpha/test/integ.branch-skew-protection.js.snapshot/amplifybranchskewprotectionDefaultTestDeployAssertA3D6DFAB.assets.json
  packages/@aws-cdk/aws-amplify-alpha/test/integ.branch-skew-protection.js.snapshot/amplifybranchskewprotectionDefaultTestDeployAssertA3D6DFAB.template.json
  packages/@aws-cdk/aws-amplify-alpha/test/integ.branch-skew-protection.js.snapshot/cdk-amplify-branch-skew-protection.assets.json
  packages/@aws-cdk/aws-amplify-alpha/test/integ.branch-skew-protection.js.snapshot/cdk-amplify-branch-skew-protection.template.json
  packages/@aws-cdk/aws-amplify-alpha/test/integ.branch-skew-protection.js.snapshot/cdk.out
  packages/@aws-cdk/aws-amplify-alpha/test/integ.branch-skew-protection.js.snapshot/integ.json
  packages/@aws-cdk/aws-amplify-alpha/test/integ.branch-skew-protection.js.snapshot/manifest.json
  packages/@aws-cdk/aws-amplify-alpha/test/integ.branch-skew-protection.js.snapshot/tree.json
  packages/@aws-cdk/aws-amplify-alpha/test/integ.branch-skew-protection.ts
Labels: p2, distinguished-contributor, pr/needs-maintainer-review

#34049 fix(pipelines): use display name for `Asset` actions when `publishAssetsInParallel` is false
  packages/@aws-cdk-testing/framework-integ/test/pipelines/test/integ.newpipeline-single-publisher.js.snapshot/PipelineStackSinglePublisher.assets.json
  packages/@aws-cdk-testing/framework-integ/test/pipelines/test/integ.newpipeline-single-publisher.js.snapshot/PipelineStackSinglePublisher.template.json
  packages/@aws-cdk-testing/framework-integ/test/pipelines/test/integ.newpipeline-single-publisher.js.snapshot/PipelineStackSinglePublisherPipeline201D00C8.dot
  packages/@aws-cdk-testing/framework-integ/test/pipelines/test/integ.newpipeline-single-publisher.js.snapshot/PipelineStackSinglePublisherintegDefaultTestDeployAssertCDD49B07.assets.json
  packages/@aws-cdk-testing/framework-integ/test/pipelines/test/integ.newpipeline-single-publisher.js.snapshot/PipelineStackSinglePublisherintegDefaultTestDeployAssertCDD49B07.template.json
  packages/@aws-cdk-testing/framework-integ/test/pipelines/test/integ.newpipeline-single-publisher.js.snapshot/assembly-PipelineStackSinglePublisher-Beta/PipelineStackSinglePublisherBetaStack14FCF5B0A.assets.json
  packages/@aws-cdk-testing/framework-integ/test/pipelines/test/integ.newpipeline-single-publisher.js.snapshot/assembly-PipelineStackSinglePublisher-Beta/PipelineStackSinglePublisherBetaStack14FCF5B0A.template.json
  packages/@aws-cdk-testing/framework-integ/test/pipelines/test/integ.newpipeline-single-publisher.js.snapshot/assembly-PipelineStackSinglePublisher-Beta/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/pipelines/test/integ.newpipeline-single-publisher.js.snapshot/assembly-PipelineStackSinglePublisher-Beta/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/pipelines/test/integ.newpipeline-single-publisher.js.snapshot/asset.8289faf53c7da377bb2b90615999171adef5e1d8f6b88810e5fef75e6ca09ba5.txt
  packages/@aws-cdk-testing/framework-integ/test/pipelines/test/integ.newpipeline-single-publisher.js.snapshot/asset.ac76997971c3f6ddf37120660003f1ced72b4fc58c498dfd99c78fa77e721e0e.txt
  packages/@aws-cdk-testing/framework-integ/test/pipelines/test/integ.newpipeline-single-publisher.js.snapshot/buildspec-c85b5a918443ddfc06c0be9a2655c12b81b6b1c88f-FileAsset.yaml
  packages/@aws-cdk-testing/framework-integ/test/pipelines/test/integ.newpipeline-single-publisher.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/pipelines/test/integ.newpipeline-single-publisher.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/pipelines/test/integ.newpipeline-single-publisher.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/pipelines/test/integ.newpipeline-single-publisher.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/pipelines/test/integ.newpipeline-single-publisher.ts
  packages/aws-cdk-lib/pipelines/lib/helpers-internal/pipeline-graph.ts
  packages/aws-cdk-lib/pipelines/test/codepipeline/codepipeline.test.ts
  packages/aws-cdk-lib/pipelines/test/compliance/assets.test.ts
Labels: bug, p2, pr/needs-community-review, star-contributor

#34526 fix(route53): warn when ttl is provided with alias target in RecordSet
  packages/aws-cdk-lib/aws-route53/lib/record-set.ts
  packages/aws-cdk-lib/aws-route53/test/record-set.test.ts
Labels: p2, contribution/core, pr-linter/exempt-test, pr-linter/exempt-integ-test

#34714 docs(core): correct comment
  packages/aws-cdk-lib/core/lib/cfn-output.ts
Labels: p2, pr/needs-community-review, beginning-contributor

#34237 feat(kms): implement .grant methods for Alias.fromAliasName (under feature flag)
  packages/@aws-cdk-testing/framework-integ/test/aws-kms/test/integ.alias-from-alias-name.js.snapshot/aws-cdk-kms.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-kms/test/integ.alias-from-alias-name.js.snapshot/aws-cdk-kms.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-kms/test/integ.alias-from-alias-name.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-kms/test/integ.alias-from-alias-name.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-kms/test/integ.alias-from-alias-name.js.snapshot/kmsaliasfromaliasnameDefaultTestDeployAssertFD733AC7.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-kms/test/integ.alias-from-alias-name.js.snapshot/kmsaliasfromaliasnameDefaultTestDeployAssertFD733AC7.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-kms/test/integ.alias-from-alias-name.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-kms/test/integ.alias-from-alias-name.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-kms/test/integ.alias-from-alias-name.ts
  packages/aws-cdk-lib/aws-kms/README.md
  packages/aws-cdk-lib/aws-kms/lib/alias.ts
  packages/aws-cdk-lib/aws-kms/test/alias.test.ts
  packages/aws-cdk-lib/cx-api/FEATURE_FLAGS.md
  packages/aws-cdk-lib/cx-api/README.md
  packages/aws-cdk-lib/cx-api/lib/features.ts
  packages/aws-cdk-lib/recommended-feature-flags.json
Labels: p2, feature-request, effort/small, beginning-contributor, pr-linter/cli-integ-tested

#34718 fix(core): splitting tree.json produces a lot of files
  packages/@aws-cdk-testing/framework-integ/test/core/test/tree-metadata.test.ts
  packages/aws-cdk-lib/core/lib/private/tree-metadata.ts
Labels: bug, p2, effort/medium, contribution/core, pr-linter/exempt-integ-test, pr/needs-maintainer-review

#34602 feat(eks): support eks with k8s 1.33
  packages/@aws-cdk-testing/framework-integ/package.json
  packages/@aws-cdk-testing/framework-integ/test/aws-eks/test/integ-tests-kubernetes-version.ts
  packages/@aws-cdk-testing/framework-integ/test/aws-eks/test/integ.eks-al2023-nodegroup.js.snapshot/asset.6094cb0ff874f89ab5ab24fb6b9417df0fdeb6966645f90c88ec1d7e28130112.zip
  packages/@aws-cdk-testing/framework-integ/test/aws-eks/test/integ.eks-al2023-nodegroup.js.snapshot/asset.e995b7fa13f3d9f946ff291512015444c90346ee68f0067f80037541a4b54d62.zip
  packages/@aws-cdk-testing/framework-integ/test/aws-eks/test/integ.eks-al2023-nodegroup.js.snapshot/aws-cdk-eks-cluster-al2023-nodegroup-test.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-eks/test/integ.eks-al2023-nodegroup.js.snapshot/aws-cdk-eks-cluster-al2023-nodegroup-test.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-eks/test/integ.eks-al2023-nodegroup.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-eks/test/integ.eks-al2023-nodegroup.ts
  packages/@aws-cdk-testing/framework-integ/test/aws-eks/test/integ.fargate-cluster.js.snapshot/asset.9953ad4c3e84d120643ece4b2e51caf43fd9850063641b4d78bf30fbe6b4d381.zip
  packages/@aws-cdk-testing/framework-integ/test/aws-eks/test/integ.fargate-cluster.js.snapshot/asset.e995b7fa13f3d9f946ff291512015444c90346ee68f0067f80037541a4b54d62.zip
  packages/@aws-cdk-testing/framework-integ/test/aws-eks/test/integ.fargate-cluster.js.snapshot/aws-cdk-eks-fargate-cluster-test-stack1.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-eks/test/integ.fargate-cluster.js.snapshot/aws-cdk-eks-fargate-cluster-test-stack1.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-eks/test/integ.fargate-cluster.js.snapshot/aws-cdk-eks-fargate-cluster-test-stack2.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-eks/test/integ.fargate-cluster.js.snapshot/aws-cdk-eks-fargate-cluster-test-stack2.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-eks/test/integ.fargate-cluster.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-eks/test/integ.fargate-cluster.ts
  packages/aws-cdk-lib/aws-eks/README.md
  packages/aws-cdk-lib/aws-eks/lib/cluster.ts
  packages/aws-cdk-lib/aws-eks/test/access-entry.test.ts
  packages/aws-cdk-lib/aws-eks/test/addon.test.ts
  packages/aws-cdk-lib/package.json
  yarn.lock
Labels: p2, star-contributor

#34729 docs(cloudfront): add example to update Cloudfront publickey
  packages/aws-cdk-lib/aws-cloudfront/README.md
Labels: p2, contribution/core

#34721 chore(ec2): add interface vpc endpoints
  packages/aws-cdk-lib/aws-ec2/lib/vpc-endpoint.ts
Labels: p2, beginning-contributor, pr/needs-maintainer-review

#34732 chore: add instructions to fix lfs errors
  CONTRIBUTING.md
Labels: p2, contribution/core, pr/needs-maintainer-review

#34742 docs(integ-tests-alpha): correct integ-runner link in README
  packages/@aws-cdk/integ-tests-alpha/README.md
Labels: p2, effort/small, pr/needs-community-review, beginning-contributor, @aws-cdk/integ-tests

#34708 feat(amplify): add compute role support for Amplify branches
  packages/@aws-cdk/aws-amplify-alpha/README.md
  packages/@aws-cdk/aws-amplify-alpha/lib/app.ts
  packages/@aws-cdk/aws-amplify-alpha/lib/branch.ts
  packages/@aws-cdk/aws-amplify-alpha/lib/utils.ts
  packages/@aws-cdk/aws-amplify-alpha/test/branch.test.ts
  packages/@aws-cdk/aws-amplify-alpha/test/integ.branch-compute-role.js.snapshot/amplifybranchcomputeroleDefaultTestDeployAssert73C754F8.assets.json
  packages/@aws-cdk/aws-amplify-alpha/test/integ.branch-compute-role.js.snapshot/amplifybranchcomputeroleDefaultTestDeployAssert73C754F8.template.json
  packages/@aws-cdk/aws-amplify-alpha/test/integ.branch-compute-role.js.snapshot/cdk-amplify-branch-compute-role.assets.json
  packages/@aws-cdk/aws-amplify-alpha/test/integ.branch-compute-role.js.snapshot/cdk-amplify-branch-compute-role.template.json
  packages/@aws-cdk/aws-amplify-alpha/test/integ.branch-compute-role.js.snapshot/cdk.out
  packages/@aws-cdk/aws-amplify-alpha/test/integ.branch-compute-role.js.snapshot/integ.json
  packages/@aws-cdk/aws-amplify-alpha/test/integ.branch-compute-role.js.snapshot/manifest.json
  packages/@aws-cdk/aws-amplify-alpha/test/integ.branch-compute-role.js.snapshot/tree.json
  packages/@aws-cdk/aws-amplify-alpha/test/integ.branch-compute-role.ts
Labels: p2, distinguished-contributor, pr/needs-maintainer-review

#34746 feat(lambda): support for schema registry for kafka
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-event-sources/test/integ.kafka-schema-registry.js.snapshot/SchemaRegistryIntegDefaultTestDeployAssertC190A9FD.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-event-sources/test/integ.kafka-schema-registry.js.snapshot/SchemaRegistryIntegDefaultTestDeployAssertC190A9FD.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-event-sources/test/integ.kafka-schema-registry.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-event-sources/test/integ.kafka-schema-registry.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-event-sources/test/integ.kafka-schema-registry.js.snapshot/lambda-event-source-confluent-schema-registry.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-event-sources/test/integ.kafka-schema-registry.js.snapshot/lambda-event-source-confluent-schema-registry.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-event-sources/test/integ.kafka-schema-registry.js.snapshot/lambda-event-source-glue-schema-registry.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-event-sources/test/integ.kafka-schema-registry.js.snapshot/lambda-event-source-glue-schema-registry.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-event-sources/test/integ.kafka-schema-registry.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-event-sources/test/integ.kafka-schema-registry.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-event-sources/test/integ.kafka-schema-registry.ts
  packages/aws-cdk-lib/aws-lambda-event-sources/README.md
  packages/aws-cdk-lib/aws-lambda-event-sources/lib/confluent-schema-registry.ts
  packages/aws-cdk-lib/aws-lambda-event-sources/lib/glue-schema-registry.ts
  packages/aws-cdk-lib/aws-lambda-event-sources/lib/index.ts
  packages/aws-cdk-lib/aws-lambda-event-sources/lib/kafka.ts
  packages/aws-cdk-lib/aws-lambda-event-sources/test/kafka.test.ts
  packages/aws-cdk-lib/aws-lambda/lib/event-source-mapping.ts
  packages/aws-cdk-lib/aws-lambda/lib/index.ts
  packages/aws-cdk-lib/aws-lambda/lib/schema-registry.ts
Labels: p2, beginning-contributor

#34762 fix(test-app): fix spelling error
  packages/aws-cdk-lib/pipelines/test/testhelpers/test-app.ts
Labels: p2, pr-linter/exempt-integ-test, beginning-contributor, pr-linter/exemption-requested

#34788 chore: remove old build tools that have been moved to aws-cdk-cli
  lerna.json
  package.json
  packages/aws-cdk-lib/package.json
  tools/@aws-cdk/cdk-build-tools/bin/cdk-package.ts
  tools/@aws-cdk/cdk-build-tools/lib/package-info.ts
  tools/@aws-cdk/cdk-build-tools/package.json
  tools/@aws-cdk/node-bundle/.eslintrc.json
  tools/@aws-cdk/node-bundle/.gitattributes
  tools/@aws-cdk/node-bundle/.gitignore
  tools/@aws-cdk/node-bundle/.npmignore
  tools/@aws-cdk/node-bundle/LICENSE
  tools/@aws-cdk/node-bundle/README.md
  tools/@aws-cdk/node-bundle/bin/node-bundle
  tools/@aws-cdk/node-bundle/package.json
  tools/@aws-cdk/node-bundle/src/api/_attributions.ts
  tools/@aws-cdk/node-bundle/src/api/_shell.ts
  tools/@aws-cdk/node-bundle/src/api/bundle.ts
  tools/@aws-cdk/node-bundle/src/api/index.ts
  tools/@aws-cdk/node-bundle/src/api/violation.ts
  tools/@aws-cdk/node-bundle/src/cli-main.ts
  tools/@aws-cdk/node-bundle/src/cli.ts
  tools/@aws-cdk/node-bundle/src/index.ts
  tools/@aws-cdk/node-bundle/test/_package.ts
  tools/@aws-cdk/node-bundle/test/api/bundle.test.ts
  tools/@aws-cdk/node-bundle/test/cli.test.ts
  tools/@aws-cdk/node-bundle/tsconfig.dev.json
  tools/@aws-cdk/node-bundle/tsconfig.json
  tools/@aws-cdk/pkglint/lib/rules.ts
  tools/@aws-cdk/pkglint/package.json
  tools/@aws-cdk/yarn-cling/.eslintrc.js
  tools/@aws-cdk/yarn-cling/.gitignore
  tools/@aws-cdk/yarn-cling/.npmignore
  tools/@aws-cdk/yarn-cling/LICENSE
  tools/@aws-cdk/yarn-cling/NOTICE
  tools/@aws-cdk/yarn-cling/README.md
  tools/@aws-cdk/yarn-cling/bin/yarn-cling
  tools/@aws-cdk/yarn-cling/bin/yarn-cling.ts
  tools/@aws-cdk/yarn-cling/jest.config.js
  tools/@aws-cdk/yarn-cling/lib/hoisting.ts
  tools/@aws-cdk/yarn-cling/lib/index.ts
  tools/@aws-cdk/yarn-cling/lib/types.ts
  tools/@aws-cdk/yarn-cling/package.json
  tools/@aws-cdk/yarn-cling/test/cling.test.ts
  tools/@aws-cdk/yarn-cling/test/hoisting.test.ts
  tools/@aws-cdk/yarn-cling/test/test-fixture/.gitignore
  tools/@aws-cdk/yarn-cling/test/test-fixture/.no-packagejson-validator
  tools/@aws-cdk/yarn-cling/test/test-fixture/cdk/package.json
  tools/@aws-cdk/yarn-cling/test/test-fixture/jsii/node_modules/aws-cdk-lib/package.json
  tools/@aws-cdk/yarn-cling/test/test-fixture/jsii/node_modules/aws-cdk/package.json
  tools/@aws-cdk/yarn-cling/test/test-fixture/jsii/node_modules/cdk
  tools/@aws-cdk/yarn-cling/test/test-fixture/jsii/package.json
  tools/@aws-cdk/yarn-cling/test/test-fixture/yarn.lock
  tools/@aws-cdk/yarn-cling/tsconfig.json
  yarn.lock
Labels: p2, contribution/core

#34405 feat(ec2): support for client route enforcement for client VPN endpoint
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.client-vpn-endpoint-client-route-enforcement.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.client-vpn-endpoint-client-route-enforcement.js.snapshot/client-vpn-endpoint-stack.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.client-vpn-endpoint-client-route-enforcement.js.snapshot/client-vpn-endpoint-stack.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.client-vpn-endpoint-client-route-enforcement.js.snapshot/clientvpnendpointintegDefaultTestDeployAssert7B9D072C.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.client-vpn-endpoint-client-route-enforcement.js.snapshot/clientvpnendpointintegDefaultTestDeployAssert7B9D072C.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.client-vpn-endpoint-client-route-enforcement.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.client-vpn-endpoint-client-route-enforcement.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.client-vpn-endpoint-client-route-enforcement.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.client-vpn-endpoint-client-route-enforcement.ts
  packages/aws-cdk-lib/aws-ec2/README.md
  packages/aws-cdk-lib/aws-ec2/lib/client-vpn-endpoint.ts
  packages/aws-cdk-lib/aws-ec2/test/client-vpn-endpoint.test.ts
Labels: p2, distinguished-contributor, pr/needs-maintainer-review

#34603 feat(backup): add support for ScheduleExpressionTimezone
  packages/@aws-cdk-testing/framework-integ/test/aws-backup/test/integ.backup.js.snapshot/cdk-backup.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-backup/test/integ.backup.js.snapshot/cdk-backup.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-backup/test/integ.backup.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-backup/test/integ.backup.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-backup/test/integ.backup.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-backup/test/integ.backup.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-backup/test/integ.backup.ts
  packages/aws-cdk-lib/aws-backup/README.md
  packages/aws-cdk-lib/aws-backup/lib/plan.ts
  packages/aws-cdk-lib/aws-backup/lib/rule.ts
  packages/aws-cdk-lib/aws-backup/test/plan.test.ts
Labels: p2, feature-request, effort/medium, distinguished-contributor

#34801 chore: add new team member abidhasan-aws to mergify configs
  .github/workflows/github-merit-badger.yml
  .mergify.yml
Labels: p2, beginning-contributor

#34803 refactor(pipelines): simplify CLI dependency version
  packages/aws-cdk-lib/package.json
  packages/aws-cdk-lib/pipelines/lib/codepipeline/codepipeline.ts
  packages/aws-cdk-lib/pipelines/lib/private/cli-version.ts
  packages/aws-cdk-lib/pipelines/test/codepipeline/codepipeline.test.ts
Labels: p2, contribution/core

#34817 revert: "ci: add tool to sync with project board"
  .github/workflows/README.md
  .github/workflows/issue-sync.yml
  package.json
  tools/@aws-cdk/project-sync/.eslintrc.js
  tools/@aws-cdk/project-sync/.gitignore
  tools/@aws-cdk/project-sync/LICENSE
  tools/@aws-cdk/project-sync/README.md
  tools/@aws-cdk/project-sync/bin/issue-sync-all.ts
  tools/@aws-cdk/project-sync/bin/issue-sync.ts
  tools/@aws-cdk/project-sync/jest.config.js
  tools/@aws-cdk/project-sync/lib/config.ts
  tools/@aws-cdk/project-sync/lib/github.ts
  tools/@aws-cdk/project-sync/lib/issue-sync-all.ts
  tools/@aws-cdk/project-sync/lib/issue-sync.ts
  tools/@aws-cdk/project-sync/package.json
  tools/@aws-cdk/project-sync/test/github-mock.ts
  tools/@aws-cdk/project-sync/test/issue-sync.test.ts
  tools/@aws-cdk/project-sync/test/snapshots/generate.ts
  tools/@aws-cdk/project-sync/test/snapshots/get-issue/15891.json
  tools/@aws-cdk/project-sync/test/snapshots/get-issue/30793.json
  tools/@aws-cdk/project-sync/test/snapshots/get-issue/33208.json
  tools/@aws-cdk/project-sync/test/snapshots/get-issue/41.json
  tools/@aws-cdk/project-sync/test/snapshots/get-project-info.json
  tools/@aws-cdk/project-sync/tsconfig.json
Labels: p2, contribution/core, pr/needs-maintainer-review

#34825 ci: github actions pr build
  .github/workflows/pr-build.yml
Labels: p2, contribution/core

#34814 fix(codecov): update codecov-upload.yml action to upload report with correct path
  .github/workflows/codecov-upload.yml
Labels: p2, contribution/core, pr-linter/exempt-test, pr-linter/exempt-integ-test, pr-linter/exemption-requested

#34772 docs(lambda): warn users on using fromBucket without setting objectVersion
  packages/aws-cdk-lib/aws-lambda/lib/code.ts
  packages/aws-cdk-lib/aws-lambda/test/code.test.ts
Labels: bug, p1, effort/small, contribution/core, repeat-contributor

#34834 ci: build code again on main to pre-fill the rosetta cache
  .github/workflows/pr-build.yml
Labels: p2, contribution/core

#34809 chore: integ-runner uses toolkit-lib engine
  packages/@aws-cdk-testing/framework-integ/package.json
  packages/@aws-cdk/app-staging-synthesizer-alpha/package.json
  packages/@aws-cdk/aws-amplify-alpha/package.json
  packages/@aws-cdk/aws-applicationsignals-alpha/package.json
  packages/@aws-cdk/aws-apprunner-alpha/package.json
  packages/@aws-cdk/aws-bedrock-alpha/package.json
  packages/@aws-cdk/aws-cloud9-alpha/package.json
  packages/@aws-cdk/aws-codestar-alpha/package.json
  packages/@aws-cdk/aws-ec2-alpha/package.json
  packages/@aws-cdk/aws-gamelift-alpha/package.json
  packages/@aws-cdk/aws-glue-alpha/package.json
  packages/@aws-cdk/aws-iot-actions-alpha/package.json
  packages/@aws-cdk/aws-iot-alpha/package.json
  packages/@aws-cdk/aws-iotevents-actions-alpha/package.json
  packages/@aws-cdk/aws-iotevents-alpha/package.json
  packages/@aws-cdk/aws-ivs-alpha/package.json
  packages/@aws-cdk/aws-kinesisanalytics-flink-alpha/package.json
  packages/@aws-cdk/aws-lambda-go-alpha/package.json
  packages/@aws-cdk/aws-lambda-python-alpha/package.json
  packages/@aws-cdk/aws-location-alpha/package.json
  packages/@aws-cdk/aws-msk-alpha/package.json
  packages/@aws-cdk/aws-neptune-alpha/package.json
  packages/@aws-cdk/aws-pipes-alpha/package.json
  packages/@aws-cdk/aws-pipes-enrichments-alpha/package.json
  packages/@aws-cdk/aws-pipes-sources-alpha/package.json
  packages/@aws-cdk/aws-pipes-targets-alpha/package.json
  packages/@aws-cdk/aws-redshift-alpha/package.json
  packages/@aws-cdk/aws-route53resolver-alpha/package.json
  packages/@aws-cdk/aws-s3objectlambda-alpha/package.json
  packages/@aws-cdk/aws-s3tables-alpha/package.json
  packages/@aws-cdk/aws-sagemaker-alpha/package.json
  packages/@aws-cdk/aws-servicecatalogappregistry-alpha/package.json
  packages/@aws-cdk/custom-resource-handlers/package.json
  packages/@aws-cdk/example-construct-library/package.json
  packages/@aws-cdk/integ-tests-alpha/package.json
Labels: p2, contribution/core

#34836 ci: require the GitHub Actions PR build for mergify
  .mergify.yml
Labels: p2, contribution/core

#34840 chore(automation): update spec-update.yml cron schedule
  .github/workflows/spec-update.yml
Labels: p2, contribution/core, pr/needs-maintainer-review

#34842 ci: cancel superseded PR builds
  .github/workflows/pr-build.yml
Labels: p2, contribution/core
