Repository aws/aws-cdk, pull requests merged in 2025-09, with the labels that each got.

#35079 feat(acm): add support for ACM exportable public certificates
  packages/aws-cdk-lib/aws-certificatemanager/README.md
  packages/aws-cdk-lib/aws-certificatemanager/lib/certificate.ts
  packages/aws-cdk-lib/aws-certificatemanager/lib/private-certificate.ts
  packages/aws-cdk-lib/aws-certificatemanager/test/certificate.test.ts
  packages/aws-cdk-lib/aws-certificatemanager/test/dns-validated-certificate.test.ts
  packages/aws-cdk-lib/aws-certificatemanager/test/private-certificate.test.ts
  tools/@aws-cdk/spec2cdk/package.json
  yarn.lock
Labels: p2, feature-request, pr-linter/exempt-integ-test, beginning-contributor, pr-linter/exemption-requested

#35372 feat(rds): retain automated backups for database cluster
  packages/@aws-cdk-testing/framework-integ/test/aws-rds/test/integ.cluster.js.snapshot/aws-cdk-rds-integ-with-feature-flag.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-rds/test/integ.cluster.js.snapshot/aws-cdk-rds-integ-with-feature-flag.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-rds/test/integ.cluster.js.snapshot/aws-cdk-rds-integ.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-rds/test/integ.cluster.js.snapshot/aws-cdk-rds-integ.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-rds/test/integ.cluster.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-rds/test/integ.cluster.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-rds/test/integ.cluster.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-rds/test/integ.cluster.js.snapshot/testrdsclusterDefaultTestDeployAssert23E53F17.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-rds/test/integ.cluster.js.snapshot/testrdsclusterwithfeatureflagDefaultTestDeployAssert8E2E540B.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-rds/test/integ.cluster.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-rds/test/integ.cluster.ts
  packages/aws-cdk-lib/aws-rds/README.md
  packages/aws-cdk-lib/aws-rds/lib/cluster.ts
  packages/aws-cdk-lib/aws-rds/test/cluster.test.ts
Labels: p2, distinguished-contributor

#35374 docs(appconfig): better docstring for app config content type
  packages/aws-cdk-lib/aws-appconfig/lib/configuration.ts
Labels: p2, effort/small, beginning-contributor

#35380 chore: fix PR build
  tools/@aws-cdk/lazify/test/no-double-getter.test.ts
Labels: p2, contribution/core

#35309 docs(events-targets): add documentation of invoking AwsApi method
  packages/aws-cdk-lib/aws-events-targets/README.md
Labels: p2, distinguished-contributor

#35400 chore(iot-actions-alpha): add missing rosetta dependency
  packages/@aws-cdk/aws-iot-alpha/package.json
Labels: p2, contribution/core

#35406 chore: npm-check-updates && yarn upgrade
  yarn.lock
Labels: p2, dependencies, contribution/core, auto-approve

#35314 chore(ci): add coverage for Actions to CodeQL scans.
  .github/workflows/codeql.yml
Labels: p2, beginning-contributor

#35345 chore(rds): postgres add 17.6,16.10,15.14,14.19,13.22, oracle add 21.0.0.0.ru-2025-07.rur-2025-07.r1,19.0.0.0.ru-2025-07.rur-2025-07.r1, mariadb 11.8.3
  packages/aws-cdk-lib/aws-rds/lib/instance-engine.ts
  packages/aws-cdk-lib/aws-rds/test/instance-engine.test.ts
Labels: p2, distinguished-contributor

#35341 feat(batch): ecs execute command
  packages/@aws-cdk-testing/framework-integ/test/aws-batch/test/integ.ecs-exec-batch-job.js.snapshot/EcsExecBatchStack.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-batch/test/integ.ecs-exec-batch-job.js.snapshot/EcsExecBatchStack.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-batch/test/integ.ecs-exec-batch-job.js.snapshot/EcsExecBatchTestDefaultTestDeployAssert6BC6470B.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-batch/test/integ.ecs-exec-batch-job.js.snapshot/EcsExecBatchTestDefaultTestDeployAssert6BC6470B.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-batch/test/integ.ecs-exec-batch-job.js.snapshot/asset.a1acfc2b5f4f6b183fd2bb9863f486bc5edef6a357b355a070d9a0e502df418c/__entrypoint__.js
  packages/@aws-cdk-testing/framework-integ/test/aws-batch/test/integ.ecs-exec-batch-job.js.snapshot/asset.a1acfc2b5f4f6b183fd2bb9863f486bc5edef6a357b355a070d9a0e502df418c/index.js
  packages/@aws-cdk-testing/framework-integ/test/aws-batch/test/integ.ecs-exec-batch-job.js.snapshot/asset.c74d4e3c82f2db3767a5b28f12d80d3dc43fdb041406fd738e1a754a716b9f96.bundle/index.js
  packages/@aws-cdk-testing/framework-integ/test/aws-batch/test/integ.ecs-exec-batch-job.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-batch/test/integ.ecs-exec-batch-job.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-batch/test/integ.ecs-exec-batch-job.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-batch/test/integ.ecs-exec-batch-job.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-batch/test/integ.ecs-exec-batch-job.ts
  packages/aws-cdk-lib/aws-batch/README.md
  packages/aws-cdk-lib/aws-batch/lib/ecs-container-definition.ts
  packages/aws-cdk-lib/aws-batch/test/ecs-container-definition.test.ts
Labels: p2, pr/needs-community-review, distinguished-contributor

#35354 docs: update ECS service and Fargate documentation for new AZ rebalancing default values
  packages/aws-cdk-lib/aws-ecs/lib/ec2/ec2-service.ts
  packages/aws-cdk-lib/aws-ecs/lib/fargate/fargate-service.ts
Labels: p2, beginning-contributor

#35455 fix: correct typo 'notfication' to 'notification' in Stack docstring
  packages/aws-cdk-lib/core/lib/stack.ts
Labels: p2, effort/small, pr-linter/exempt-test, pr-linter/exempt-integ-test, beginning-contributor, pr-linter/exemption-requested

#35366 fix(bedrock-alpha): added missing validation when prompt uses default variant
  packages/@aws-cdk/aws-bedrock-alpha/bedrock/prompts/prompt.ts
  packages/@aws-cdk/aws-bedrock-alpha/test/bedrock/prompts/prompt.test.ts
Labels: p2, contribution/core, pr-linter/exempt-integ-test, pr/needs-maintainer-review

#33351 feat(elasticloadbalancingv2): support target group health attributes
  packages/@aws-cdk-testing/framework-integ/test/aws-elasticloadbalancingv2/test/integ.alb-target-group-attributes.js.snapshot/alb-target-group-attributes.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-elasticloadbalancingv2/test/integ.alb-target-group-attributes.js.snapshot/alb-target-group-attributes.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-elasticloadbalancingv2/test/integ.alb-target-group-attributes.js.snapshot/albtargetgroupattributestestDefaultTestDeployAssert8393825C.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-elasticloadbalancingv2/test/integ.alb-target-group-attributes.js.snapshot/albtargetgroupattributestestDefaultTestDeployAssert8393825C.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-elasticloadbalancingv2/test/integ.alb-target-group-attributes.js.snapshot/asset.53e3ecec991005bc2ddc98d13a897e8eadf082b86dedf53475c933aed3069238.bundle/index.js
  packages/@aws-cdk-testing/framework-integ/test/aws-elasticloadbalancingv2/test/integ.alb-target-group-attributes.js.snapshot/asset.a1acfc2b5f4f6b183fd2bb9863f486bc5edef6a357b355a070d9a0e502df418c/__entrypoint__.js
  packages/@aws-cdk-testing/framework-integ/test/aws-elasticloadbalancingv2/test/integ.alb-target-group-attributes.js.snapshot/asset.a1acfc2b5f4f6b183fd2bb9863f486bc5edef6a357b355a070d9a0e502df418c/index.js
  packages/@aws-cdk-testing/framework-integ/test/aws-elasticloadbalancingv2/test/integ.alb-target-group-attributes.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-elasticloadbalancingv2/test/integ.alb-target-group-attributes.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-elasticloadbalancingv2/test/integ.alb-target-group-attributes.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-elasticloadbalancingv2/test/integ.alb-target-group-attributes.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-elasticloadbalancingv2/test/integ.alb-target-group-attributes.ts
  packages/@aws-cdk-testing/framework-integ/test/aws-elasticloadbalancingv2/test/integ.nlb-target-group-attributes.js.snapshot/asset.53e3ecec991005bc2ddc98d13a897e8eadf082b86dedf53475c933aed3069238.bundle/index.js
  packages/@aws-cdk-testing/framework-integ/test/aws-elasticloadbalancingv2/test/integ.nlb-target-group-attributes.js.snapshot/asset.a1acfc2b5f4f6b183fd2bb9863f486bc5edef6a357b355a070d9a0e502df418c/__entrypoint__.js
  packages/@aws-cdk-testing/framework-integ/test/aws-elasticloadbalancingv2/test/integ.nlb-target-group-attributes.js.snapshot/asset.a1acfc2b5f4f6b183fd2bb9863f486bc5edef6a357b355a070d9a0e502df418c/index.js
  packages/@aws-cdk-testing/framework-integ/test/aws-elasticloadbalancingv2/test/integ.nlb-target-group-attributes.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-elasticloadbalancingv2/test/integ.nlb-target-group-attributes.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-elasticloadbalancingv2/test/integ.nlb-target-group-attributes.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-elasticloadbalancingv2/test/integ.nlb-target-group-attributes.js.snapshot/nlb-target-group-attributes.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-elasticloadbalancingv2/test/integ.nlb-target-group-attributes.js.snapshot/nlb-target-group-attributes.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-elasticloadbalancingv2/test/integ.nlb-target-group-attributes.js.snapshot/nlbtargetgroupattributestestDefaultTestDeployAssertDA332C52.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-elasticloadbalancingv2/test/integ.nlb-target-group-attributes.js.snapshot/nlbtargetgroupattributestestDefaultTestDeployAssertDA332C52.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-elasticloadbalancingv2/test/integ.nlb-target-group-attributes.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-elasticloadbalancingv2/test/integ.nlb-target-group-attributes.ts
  packages/aws-cdk-lib/aws-elasticloadbalancingv2/README.md
  packages/aws-cdk-lib/aws-elasticloadbalancingv2/lib/shared/base-target-group.ts
  packages/aws-cdk-lib/aws-elasticloadbalancingv2/test/alb/target-group.test.ts
  packages/aws-cdk-lib/aws-elasticloadbalancingv2/test/nlb/target-group.test.ts
Labels: p2, feature-request, pr/needs-community-review, effort/medium, valued-contributor

#35425 fix(cloudformation-include): aws::novalue type validation error for non-string properties
  packages/@aws-cdk-testing/framework-integ/test/cloudformation-include/test/integ.novalue-nonstring.js.snapshot/CfnIncludeNoValueBooleanTestDefaultTestDeployAssert806459F3.assets.json
  packages/@aws-cdk-testing/framework-integ/test/cloudformation-include/test/integ.novalue-nonstring.js.snapshot/CfnIncludeNoValueBooleanTestDefaultTestDeployAssert806459F3.template.json
  packages/@aws-cdk-testing/framework-integ/test/cloudformation-include/test/integ.novalue-nonstring.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/cloudformation-include/test/integ.novalue-nonstring.js.snapshot/integ-cfninclude-novalue-boolean.assets.json
  packages/@aws-cdk-testing/framework-integ/test/cloudformation-include/test/integ.novalue-nonstring.js.snapshot/integ-cfninclude-novalue-boolean.template.json
  packages/@aws-cdk-testing/framework-integ/test/cloudformation-include/test/integ.novalue-nonstring.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/cloudformation-include/test/integ.novalue-nonstring.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/cloudformation-include/test/integ.novalue-nonstring.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/cloudformation-include/test/integ.novalue-nonstring.ts
  packages/@aws-cdk-testing/framework-integ/test/cloudformation-include/test/test-templates/novalue-boolean.json
  packages/aws-cdk-lib/core/lib/helpers-internal/cfn-parse.ts
Labels: bug, p2, effort/small, contribution/core, beginning-contributor

#35528 fix(secretsmanager): `SecretRotationApplication` creates lambda on python 3.9 which is EOL
  packages/@aws-cdk-testing/framework-integ/test/aws-docdb/test/integ.cluster-rotation.lit.js.snapshot/aws-cdk-docdb-cluster-rotation.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-docdb/test/integ.cluster-rotation.lit.js.snapshot/aws-cdk-docdb-cluster-rotation.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-docdb/test/integ.cluster-rotation.lit.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-docdb/test/integ.cluster-rotation.lit.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-docdb/test/integ.cluster-rotation.lit.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-docdb/test/integ.cluster-rotation.lit.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-rds/test/integ.cluster-rotation.lit.js.snapshot/aws-cdk-rds-cluster-rotation.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-rds/test/integ.cluster-rotation.lit.js.snapshot/aws-cdk-rds-cluster-rotation.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-rds/test/integ.cluster-rotation.lit.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-rds/test/integ.cluster-rotation.lit.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-rds/test/integ.cluster-rotation.lit.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-rds/test/integ.cluster-rotation.lit.js.snapshot/testrdsclusterrotationDefaultTestDeployAssertCC761439.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-rds/test/integ.cluster-rotation.lit.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-rds/test/integ.cluster-snapshot.js.snapshot/cdk-integ-cluster-snapshot.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-rds/test/integ.cluster-snapshot.js.snapshot/cdk-integ-cluster-snapshot.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-rds/test/integ.cluster-snapshot.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-rds/test/integ.instance.lit.js.snapshot/aws-cdk-rds-instance.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-rds/test/integ.instance.lit.js.snapshot/aws-cdk-rds-instance.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-rds/test/integ.instance.lit.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-rds/test/integ.instance.lit.js.snapshot/tree.json
  packages/aws-cdk-lib/aws-secretsmanager/lib/secret-rotation.ts
Labels: p1, feature-request, contribution/core, pr-linter/exempt-integ-test

#35525 chore(bedrock): support Qwen3 and DeepSeek-V3.1 models
  packages/aws-cdk-lib/aws-bedrock/lib/foundation-model.ts
Labels: p2, distinguished-contributor

#35511 fix(core): negated gitignore patterns inside subdirectories are not including matched files
  packages/aws-cdk-lib/core/lib/fs/fingerprint.ts
  packages/aws-cdk-lib/core/lib/fs/ignore.ts
  packages/aws-cdk-lib/core/test/fs/fs-copy.test.ts
  packages/aws-cdk-lib/core/test/fs/fs-fingerprint.test.ts
Labels: bug, p2, effort/small, pr-linter/exempt-integ-test, beginning-contributor, pr/reviewer-clarification-requested

#35536 chore(ec2): add r8gn instance classes
  packages/aws-cdk-lib/aws-ec2/lib/instance-types.ts
Labels: p2, distinguished-contributor

#35568 revert(dynamodb): use keyId instead of keyArn for TableV2 replica encryption
  packages/aws-cdk-lib/aws-dynamodb/lib/encryption.ts
  packages/aws-cdk-lib/aws-dynamodb/test/encryption.test.ts
  packages/aws-cdk-lib/aws-dynamodb/test/table-v2.test.ts
Labels: p1, contribution/core

#35572 chore(release): 2.217.0
  CHANGELOG.v2.alpha.md
  CHANGELOG.v2.md
  packages/@aws-cdk-testing/framework-integ/test/aws-cloudfront/test/integ.distribution-function-runtime.js.snapshot/integ-distribution-function.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-cloudfront/test/integ.distribution-function.js.snapshot/integ-distribution-function.template.json
  packages/aws-cdk-lib/aws-bedrockagentcore/.jsiirc.json
  packages/aws-cdk-lib/aws-bedrockagentcore/README.md
  packages/aws-cdk-lib/aws-bedrockagentcore/index.ts
  packages/aws-cdk-lib/aws-bedrockagentcore/lib/index.ts
  packages/aws-cdk-lib/aws-cloudfront/lib/function.ts
  packages/aws-cdk-lib/aws-cloudfront/test/distribution.test.ts
  packages/aws-cdk-lib/aws-cloudfront/test/function.test.ts
  packages/aws-cdk-lib/aws-cloudfront/test/web-distribution.test.ts
  packages/aws-cdk-lib/aws-dynamodb/lib/encryption.ts
  packages/aws-cdk-lib/aws-dynamodb/test/encryption.test.ts
  packages/aws-cdk-lib/aws-dynamodb/test/table-v2.test.ts
  packages/aws-cdk-lib/aws-ec2/lib/instance-types.ts
  packages/aws-cdk-lib/aws-kms/lib/alias.ts
  packages/aws-cdk-lib/aws-kms/lib/key.ts
  packages/aws-cdk-lib/aws-kms/test/alias.test.ts
  packages/aws-cdk-lib/aws-lambda/lib/function-base.ts
  packages/aws-cdk-lib/aws-lambda/test/alias.test.ts
  packages/aws-cdk-lib/aws-lambda/test/function.test.ts
  packages/aws-cdk-lib/aws-lambda/test/lambda-version.test.ts
  packages/aws-cdk-lib/aws-rds/lib/instance.ts
  packages/aws-cdk-lib/aws-rds/test/instance.from-lookup.test.ts
  packages/aws-cdk-lib/aws-smsvoice/.jsiirc.json
  packages/aws-cdk-lib/aws-smsvoice/README.md
  packages/aws-cdk-lib/aws-smsvoice/index.ts
  packages/aws-cdk-lib/aws-smsvoice/lib/index.ts
  packages/aws-cdk-lib/core/lib/analytics-data-source/enums.ts
  packages/aws-cdk-lib/core/lib/analytics-data-source/enums/module-enums.json
  packages/aws-cdk-lib/core/lib/fs/fingerprint.ts
  packages/aws-cdk-lib/core/lib/fs/ignore.ts
  packages/aws-cdk-lib/core/test/fs/fs-copy.test.ts
  packages/aws-cdk-lib/core/test/fs/fs-fingerprint.test.ts
  packages/aws-cdk-lib/index.ts
  packages/aws-cdk-lib/package.json
  packages/aws-cdk-lib/scripts/scope-map.json
  tools/@aws-cdk/spec2cdk/package.json
  version.v2.json
  yarn.lock
Labels: p2, contribution/core, pr/no-squash, auto-approve

#35569 chore: add new team member 9pace to github-merit-badger
  .github/workflows/github-merit-badger.yml
Labels: p2, contribution/core, queued

#35584 feat(pipelines): `CodeBuildFactory` support Docker server
  packages/@aws-cdk-testing/framework-integ/test/pipelines/test/integ.newpipeline-reduce-stagerole-scope.js.snapshot/CdkPipelineInvestigationStack.assets.json
  packages/@aws-cdk-testing/framework-integ/test/pipelines/test/integ.newpipeline-reduce-stagerole-scope.js.snapshot/CdkPipelineInvestigationStack.template.json
  packages/@aws-cdk-testing/framework-integ/test/pipelines/test/integ.newpipeline-reduce-stagerole-scope.js.snapshot/CdkPipelineInvestigationTestDefaultTestDeployAssertC69AF0A9.assets.json
  packages/@aws-cdk-testing/framework-integ/test/pipelines/test/integ.newpipeline-reduce-stagerole-scope.js.snapshot/assembly-CdkPipelineInvestigationStack-Prod/CdkPipelineInvestigationStackProdProdStackD4D4A90A.assets.json
  packages/@aws-cdk-testing/framework-integ/test/pipelines/test/integ.newpipeline-reduce-stagerole-scope.js.snapshot/assembly-CdkPipelineInvestigationStack-Prod/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/pipelines/test/integ.newpipeline-reduce-stagerole-scope.js.snapshot/assembly-CdkPipelineInvestigationStack-Prod/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/pipelines/test/integ.newpipeline-reduce-stagerole-scope.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/pipelines/test/integ.newpipeline-reduce-stagerole-scope.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/pipelines/test/integ.newpipeline-reduce-stagerole-scope.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/pipelines/test/integ.newpipeline-reduce-stagerole-scope.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/pipelines/test/integ.newpipeline-reduce-stagerole-scope.ts
  packages/aws-cdk-lib/pipelines/README.md
  packages/aws-cdk-lib/pipelines/lib/codepipeline/private/codebuild-factory.ts
  packages/aws-cdk-lib/pipelines/test/compliance/synths.test.ts
Labels: bug, p2, effort/medium, distinguished-contributor, queued

#35581 chore(rds): mysql version 5.7.44-RDS.20250818
  packages/aws-cdk-lib/aws-rds/lib/instance-engine.ts
Labels: p2, distinguished-contributor

#35578 chore(eks): add AL2023_ARM_64_NVIDIA AMI type for managed node groups
  packages/@aws-cdk/aws-eks-v2-alpha/lib/managed-nodegroup.ts
  packages/@aws-cdk/aws-eks-v2-alpha/test/nodegroup.test.ts
  packages/aws-cdk-lib/aws-eks/lib/managed-nodegroup.ts
  packages/aws-cdk-lib/aws-eks/test/nodegroup.test.ts
Labels: p2, beginning-contributor, queued

#35424 feat(elasticache): implement Serverless ElastiCache L2 Construct
  packages/@aws-cdk-testing/framework-integ/test/aws-cloudfront/test/integ.distribution-function-runtime.js.snapshot/integ-distribution-function.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-cloudfront/test/integ.distribution-function.js.snapshot/integ-distribution-function.template.json
  packages/@aws-cdk/aws-elasticache-alpha/.eslintrc.js
  packages/@aws-cdk/aws-elasticache-alpha/.gitignore
  packages/@aws-cdk/aws-elasticache-alpha/.npmignore
  packages/@aws-cdk/aws-elasticache-alpha/LICENSE
  packages/@aws-cdk/aws-elasticache-alpha/NOTICE
  packages/@aws-cdk/aws-elasticache-alpha/README.md
  packages/@aws-cdk/aws-elasticache-alpha/jest.config.js
  packages/@aws-cdk/aws-elasticache-alpha/lib/common.ts
  packages/@aws-cdk/aws-elasticache-alpha/lib/iam-user.ts
  packages/@aws-cdk/aws-elasticache-alpha/lib/index.ts
  packages/@aws-cdk/aws-elasticache-alpha/lib/no-password-user.ts
  packages/@aws-cdk/aws-elasticache-alpha/lib/password-user.ts
  packages/@aws-cdk/aws-elasticache-alpha/lib/serverless-cache-base.ts
  packages/@aws-cdk/aws-elasticache-alpha/lib/serverless-cache.ts
  packages/@aws-cdk/aws-elasticache-alpha/lib/user-base.ts
  packages/@aws-cdk/aws-elasticache-alpha/lib/user-group.ts
  packages/@aws-cdk/aws-elasticache-alpha/package.json
  packages/@aws-cdk/aws-elasticache-alpha/rosetta/default.ts-fixture
  packages/@aws-cdk/aws-elasticache-alpha/test/iam-user.test.ts
  packages/@aws-cdk/aws-elasticache-alpha/test/integ.serverless-cache.js.snapshot/asset.53e3ecec991005bc2ddc98d13a897e8eadf082b86dedf53475c933aed3069238.bundle/index.js
  packages/@aws-cdk/aws-elasticache-alpha/test/integ.serverless-cache.js.snapshot/aws-cdk-serverless-cache.assets.json
  packages/@aws-cdk/aws-elasticache-alpha/test/integ.serverless-cache.js.snapshot/aws-cdk-serverless-cache.template.json
  packages/@aws-cdk/aws-elasticache-alpha/test/integ.serverless-cache.js.snapshot/awscdkserverlesscacheintegDefaultTestDeployAssert7BD34438.assets.json
  packages/@aws-cdk/aws-elasticache-alpha/test/integ.serverless-cache.js.snapshot/awscdkserverlesscacheintegDefaultTestDeployAssert7BD34438.template.json
  packages/@aws-cdk/aws-elasticache-alpha/test/integ.serverless-cache.js.snapshot/cdk.out
  packages/@aws-cdk/aws-elasticache-alpha/test/integ.serverless-cache.js.snapshot/integ.json
  packages/@aws-cdk/aws-elasticache-alpha/test/integ.serverless-cache.js.snapshot/manifest.json
  packages/@aws-cdk/aws-elasticache-alpha/test/integ.serverless-cache.js.snapshot/tree.json
  packages/@aws-cdk/aws-elasticache-alpha/test/integ.serverless-cache.ts
  packages/@aws-cdk/aws-elasticache-alpha/test/no-password-user.test.ts
  packages/@aws-cdk/aws-elasticache-alpha/test/password-user.test.ts
  packages/@aws-cdk/aws-elasticache-alpha/test/serverless-cache-base.test.ts
  packages/@aws-cdk/aws-elasticache-alpha/test/serverless-cache.test.ts
  packages/@aws-cdk/aws-elasticache-alpha/test/user-group.test.ts
Labels: p2, beginning-contributor, queued

#35480 feat(codebuild): support overflow behavior of fleet
  packages/@aws-cdk-testing/framework-integ/test/aws-codebuild/test/integ.project-fleet-overflow-behavior.js.snapshot/OverflowBehaviorFleetIntegDefaultTestDeployAssert36A83E9C.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-codebuild/test/integ.project-fleet-overflow-behavior.js.snapshot/OverflowBehaviorFleetIntegDefaultTestDeployAssert36A83E9C.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-codebuild/test/integ.project-fleet-overflow-behavior.js.snapshot/OverflowBehaviorFleetStack.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-codebuild/test/integ.project-fleet-overflow-behavior.js.snapshot/OverflowBehaviorFleetStack.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-codebuild/test/integ.project-fleet-overflow-behavior.js.snapshot/asset.53e3ecec991005bc2ddc98d13a897e8eadf082b86dedf53475c933aed3069238.bundle/index.js
  packages/@aws-cdk-testing/framework-integ/test/aws-codebuild/test/integ.project-fleet-overflow-behavior.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-codebuild/test/integ.project-fleet-overflow-behavior.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-codebuild/test/integ.project-fleet-overflow-behavior.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-codebuild/test/integ.project-fleet-overflow-behavior.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-codebuild/test/integ.project-fleet-overflow-behavior.ts
  packages/aws-cdk-lib/aws-codebuild/README.md
  packages/aws-cdk-lib/aws-codebuild/lib/fleet.ts
  packages/aws-cdk-lib/aws-codebuild/test/fleet.test.ts
Labels: p2, distinguished-contributor, queued

#35518 fix(cloudfront): edgefunction does not propagate stack tags correctly
  packages/aws-cdk-lib/aws-cloudfront/lib/experimental/edge-function.ts
  packages/aws-cdk-lib/aws-cloudfront/test/experimental/edge-function.test.ts
Labels: bug, p1, effort/medium, pr-linter/exempt-readme, pr-linter/exempt-integ-test, beginning-contributor

#35631 chore(mergify): force in place checks
  .mergify.yml
Labels: p2, contribution/core
