Repository aws/aws-cdk, pull requests merged in 2025-04, with the labels that each got.

#33996 feat(ec2): add mailmanager vpc endpoints
  packages/aws-cdk-lib/aws-ec2/lib/vpc-endpoint.ts
Labels: p2, pr-linter/exempt-readme, pr-linter/exempt-test, pr-linter/exempt-integ-test, beginning-contributor

#33997 chore: update Contributors File
  CONTRIBUTORS.md
Labels: p2, auto-approve

#33979 fix: customer aspect cannot add Tags if a BucketNotifications construct is present
  packages/aws-cdk-lib/core/lib/aspect.ts
  packages/aws-cdk-lib/core/lib/private/synthesis.ts
  packages/aws-cdk-lib/core/test/aspect.test.ts
Labels: bug, p2, contribution/core, pr-linter/exempt-integ-test, pr/needs-maintainer-review, skip-abstractions-board

#33864 feat(events-targets): support ApiGatewayV2 HttpApi
  packages/@aws-cdk-testing/framework-integ/test/aws-events-targets/test/api-gatewayv2/integ.api-gatewayv2.js.snapshot/ApiGatewayTargetDefaultTestDeployAssert33F7AF34.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-events-targets/test/api-gatewayv2/integ.api-gatewayv2.js.snapshot/ApiGatewayTargetDefaultTestDeployAssert33F7AF34.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-events-targets/test/api-gatewayv2/integ.api-gatewayv2.js.snapshot/asset.97484721f29e34bf38d7a459804dd2d2a8dea6f8c27d7531e215bf4274fbc895.bundle/index.js
  packages/@aws-cdk-testing/framework-integ/test/aws-events-targets/test/api-gatewayv2/integ.api-gatewayv2.js.snapshot/aws-events-targets-api-gatewayv2-integ.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-events-targets/test/api-gatewayv2/integ.api-gatewayv2.js.snapshot/aws-events-targets-api-gatewayv2-integ.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-events-targets/test/api-gatewayv2/integ.api-gatewayv2.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-events-targets/test/api-gatewayv2/integ.api-gatewayv2.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-events-targets/test/api-gatewayv2/integ.api-gatewayv2.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-events-targets/test/api-gatewayv2/integ.api-gatewayv2.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-events-targets/test/api-gatewayv2/integ.api-gatewayv2.ts
  packages/aws-cdk-lib/aws-apigatewayv2/lib/http/api.ts
  packages/aws-cdk-lib/aws-events-targets/README.md
  packages/aws-cdk-lib/aws-events-targets/lib/api-gatewayv2.ts
  packages/aws-cdk-lib/aws-events-targets/lib/index.ts
  packages/aws-cdk-lib/aws-events-targets/test/api-gatewayv2/api-gatewayv2.test.ts
Labels: p1, feature-request, effort/medium, admired-contributor

#33778 feat(cognito): v3.0 pre token generation trigger event
  packages/@aws-cdk-testing/framework-integ/test/aws-cognito/test/integ.user-pool-pre-token-generation.js.snapshot/PreTokenGenerationIntegTestDefaultTestDeployAssert5121EE60.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-cognito/test/integ.user-pool-pre-token-generation.js.snapshot/PreTokenGenerationIntegTestDefaultTestDeployAssert5121EE60.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-cognito/test/integ.user-pool-pre-token-generation.js.snapshot/UserPoolPreTokenGenerationStack.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-cognito/test/integ.user-pool-pre-token-generation.js.snapshot/UserPoolPreTokenGenerationStack.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-cognito/test/integ.user-pool-pre-token-generation.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-cognito/test/integ.user-pool-pre-token-generation.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-cognito/test/integ.user-pool-pre-token-generation.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-cognito/test/integ.user-pool-pre-token-generation.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-cognito/test/integ.user-pool-pre-token-generation.ts
  packages/aws-cdk-lib/aws-cognito/README.md
  packages/aws-cdk-lib/aws-cognito/lib/user-pool.ts
  packages/aws-cdk-lib/aws-cognito/test/user-pool.test.ts
Labels: p2, feature-request, effort/small, distinguished-contributor, pr/needs-maintainer-review

#33375 feat(codepipeline-actions): support `ECRBuildAndPublish` action
  packages/@aws-cdk-testing/framework-integ/test/aws-codepipeline-actions/test/integ.pipeline-ecr-build-and-publish-private.js.snapshot/asset.530055f7515b3f0a47900f5df37e729ba40ca977b2d07b952bdefa2b8f883f42.bundle/index.js
  packages/@aws-cdk-testing/framework-integ/test/aws-codepipeline-actions/test/integ.pipeline-ecr-build-and-publish-private.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-codepipeline-actions/test/integ.pipeline-ecr-build-and-publish-private.js.snapshot/codepipeline-ecr-build-and-publish-private.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-codepipeline-actions/test/integ.pipeline-ecr-build-and-publish-private.js.snapshot/codepipeline-ecr-build-and-publish-private.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-codepipeline-actions/test/integ.pipeline-ecr-build-and-publish-private.js.snapshot/codepipelineecrbuildandpublishprivatetestDefaultTestDeployAssert80443302.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-codepipeline-actions/test/integ.pipeline-ecr-build-and-publish-private.js.snapshot/codepipelineecrbuildandpublishprivatetestDefaultTestDeployAssert80443302.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-codepipeline-actions/test/integ.pipeline-ecr-build-and-publish-private.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-codepipeline-actions/test/integ.pipeline-ecr-build-and-publish-private.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-codepipeline-actions/test/integ.pipeline-ecr-build-and-publish-private.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-codepipeline-actions/test/integ.pipeline-ecr-build-and-publish-private.ts
  packages/@aws-cdk-testing/framework-integ/test/aws-codepipeline-actions/test/integ.pipeline-ecr-build-and-publish-public.js.snapshot/asset.530055f7515b3f0a47900f5df37e729ba40ca977b2d07b952bdefa2b8f883f42.bundle/index.js
  packages/@aws-cdk-testing/framework-integ/test/aws-codepipeline-actions/test/integ.pipeline-ecr-build-and-publish-public.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-codepipeline-actions/test/integ.pipeline-ecr-build-and-publish-public.js.snapshot/codepipeline-ecr-build-and-publish-public.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-codepipeline-actions/test/integ.pipeline-ecr-build-and-publish-public.js.snapshot/codepipeline-ecr-build-and-publish-public.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-codepipeline-actions/test/integ.pipeline-ecr-build-and-publish-public.js.snapshot/codepipelineecrbuildandpublishpublictestDefaultTestDeployAssertC4039AD4.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-codepipeline-actions/test/integ.pipeline-ecr-build-and-publish-public.js.snapshot/codepipelineecrbuildandpublishpublictestDefaultTestDeployAssertC4039AD4.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-codepipeline-actions/test/integ.pipeline-ecr-build-and-publish-public.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-codepipeline-actions/test/integ.pipeline-ecr-build-and-publish-public.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-codepipeline-actions/test/integ.pipeline-ecr-build-and-publish-public.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-codepipeline-actions/test/integ.pipeline-ecr-build-and-publish-public.ts
  packages/aws-cdk-lib/aws-codepipeline-actions/README.md
  packages/aws-cdk-lib/aws-codepipeline-actions/lib/ecr/build-and-publish-action.ts
  packages/aws-cdk-lib/aws-codepipeline-actions/lib/ecr/index.ts
  packages/aws-cdk-lib/aws-codepipeline-actions/lib/index.ts
  packages/aws-cdk-lib/aws-codepipeline-actions/test/ecr/ecr-build-and-publish-action.test.ts
Labels: p2, feature-request, effort/medium, distinguished-contributor, pr-linter/exemption-requested

#33902 feat(rds): engine lifecycle support
  packages/@aws-cdk-testing/framework-integ/test/aws-rds/test/integ.cluster-engine-lifecycle-support.js.snapshot/RdsClusterEngineLifecycleSupportIntegDefaultTestDeployAssert6F5E7AEF.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-rds/test/integ.cluster-engine-lifecycle-support.js.snapshot/RdsClusterEngineLifecycleSupportIntegDefaultTestDeployAssert6F5E7AEF.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-rds/test/integ.cluster-engine-lifecycle-support.js.snapshot/RdsClusterEngineLifecycleSupportStack.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-rds/test/integ.cluster-engine-lifecycle-support.js.snapshot/RdsClusterEngineLifecycleSupportStack.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-rds/test/integ.cluster-engine-lifecycle-support.js.snapshot/asset.a1acfc2b5f4f6b183fd2bb9863f486bc5edef6a357b355a070d9a0e502df418c/__entrypoint__.js
  packages/@aws-cdk-testing/framework-integ/test/aws-rds/test/integ.cluster-engine-lifecycle-support.js.snapshot/asset.a1acfc2b5f4f6b183fd2bb9863f486bc5edef6a357b355a070d9a0e502df418c/index.js
  packages/@aws-cdk-testing/framework-integ/test/aws-rds/test/integ.cluster-engine-lifecycle-support.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-rds/test/integ.cluster-engine-lifecycle-support.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-rds/test/integ.cluster-engine-lifecycle-support.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-rds/test/integ.cluster-engine-lifecycle-support.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-rds/test/integ.cluster-engine-lifecycle-support.ts
  packages/aws-cdk-lib/aws-rds/README.md
  packages/aws-cdk-lib/aws-rds/lib/cluster.ts
  packages/aws-cdk-lib/aws-rds/test/cluster.test.ts
Labels: p2, feature-request, effort/medium, distinguished-contributor

#33683 feat(logs-destinations): support Amazon Data Firehose logs destination
  packages/@aws-cdk-testing/framework-integ/test/aws-logs-destinations/test/integ.firehose.js.snapshot/FirehoseIntegDefaultTestDeployAssert9D77F4C4.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-logs-destinations/test/integ.firehose.js.snapshot/FirehoseIntegDefaultTestDeployAssert9D77F4C4.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-logs-destinations/test/integ.firehose.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-logs-destinations/test/integ.firehose.js.snapshot/firehose-logsubscription-integ.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-logs-destinations/test/integ.firehose.js.snapshot/firehose-logsubscription-integ.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-logs-destinations/test/integ.firehose.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-logs-destinations/test/integ.firehose.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-logs-destinations/test/integ.firehose.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-logs-destinations/test/integ.firehose.ts
  packages/aws-cdk-lib/aws-logs-destinations/lib/firehose.ts
  packages/aws-cdk-lib/aws-logs-destinations/lib/index.ts
  packages/aws-cdk-lib/aws-logs-destinations/test/firehose.test.ts
  packages/aws-cdk-lib/aws-logs/README.md
Labels: p2, feature-request, effort/medium, star-contributor

#33967 fix(ecr-assets): handle Docker 27.4+ output format in TarballImageAsset
  packages/aws-cdk-lib/aws-ecr-assets/lib/tarball-asset.ts
  packages/aws-cdk-lib/aws-ecr-assets/test/tarball-asset.test.ts
Labels: bug, p1, effort/medium, contribution/core, pr-linter/exempt-integ-test

#34017 fix(pipelines): can't have the same asset display name 3 times
  packages/aws-cdk-lib/core/lib/stage.ts
  packages/aws-cdk-lib/core/test/stage.test.ts
  packages/aws-cdk-lib/pipelines/lib/codepipeline/codepipeline.ts
  packages/aws-cdk-lib/pipelines/test/codepipeline/codepipeline.test.ts
  packages/aws-cdk-lib/pipelines/test/compliance/assets.test.ts
  packages/aws-cdk-lib/pipelines/test/testhelpers/assets/test-file-asset-three.txt
  packages/aws-cdk-lib/pipelines/test/testhelpers/test-app.ts
Labels: bug, p1, contribution/core, pr-linter/exempt-integ-test

#34003 fix(cx-api): adding missing readme
  packages/aws-cdk-lib/cx-api/README.md
Labels: p2, pr-linter/exempt-test, pr-linter/exempt-integ-test, valued-contributor, pr-linter/exemption-requested

#33824 fix(ec2-alpha): addInternetGW handles shared route table for subnets
  packages/@aws-cdk/aws-ec2-alpha/lib/vpc-v2-base.ts
  packages/@aws-cdk/aws-ec2-alpha/test/integ.vpc-shared-route-table.js.snapshot/VpcSharedRouteTableIntegDefaultTestDeployAssert4BB1B1C8.assets.json
  packages/@aws-cdk/aws-ec2-alpha/test/integ.vpc-shared-route-table.js.snapshot/VpcSharedRouteTableIntegDefaultTestDeployAssert4BB1B1C8.template.json
  packages/@aws-cdk/aws-ec2-alpha/test/integ.vpc-shared-route-table.js.snapshot/asset.97484721f29e34bf38d7a459804dd2d2a8dea6f8c27d7531e215bf4274fbc895.bundle/index.js
  packages/@aws-cdk/aws-ec2-alpha/test/integ.vpc-shared-route-table.js.snapshot/aws-cdk-ec2-alpha-shared-route-table.assets.json
  packages/@aws-cdk/aws-ec2-alpha/test/integ.vpc-shared-route-table.js.snapshot/aws-cdk-ec2-alpha-shared-route-table.template.json
  packages/@aws-cdk/aws-ec2-alpha/test/integ.vpc-shared-route-table.js.snapshot/cdk.out
  packages/@aws-cdk/aws-ec2-alpha/test/integ.vpc-shared-route-table.js.snapshot/integ.json
  packages/@aws-cdk/aws-ec2-alpha/test/integ.vpc-shared-route-table.js.snapshot/manifest.json
  packages/@aws-cdk/aws-ec2-alpha/test/integ.vpc-shared-route-table.js.snapshot/tree.json
  packages/@aws-cdk/aws-ec2-alpha/test/integ.vpc-shared-route-table.ts
  packages/@aws-cdk/aws-ec2-alpha/test/vpc-shared-route-table.test.ts
Labels: bug, p1, effort/medium, contribution/core

#34010 fix(lambda): deprecate default feature flag @aws-cdk/aws-lambda:createNewPoliciesWithAddToRolePolicy
  packages/aws-cdk-lib/cx-api/FEATURE_FLAGS.md
  packages/aws-cdk-lib/cx-api/README.md
  packages/aws-cdk-lib/cx-api/lib/features.ts
  packages/aws-cdk-lib/recommended-feature-flags.json
Labels: bug, p1, effort/medium, contribution/core, pr-linter/exempt-test, pr-linter/exempt-integ-test, pr-linter/exemption-requested, pr/needs-maintainer-review

#34025 feat(eks-v2-alpha): add new nodegroup ami type
  packages/@aws-cdk/aws-eks-v2-alpha/lib/managed-nodegroup.ts
  packages/aws-cdk-lib/aws-eks/lib/managed-nodegroup.ts
Labels: p2, contribution/core, pr-linter/exempt-readme, pr-linter/exempt-test, pr-linter/exempt-integ-test, pr/needs-maintainer-review

#33980 feat: update L1 CloudFormation resource definitions
  packages/aws-cdk-lib/package.json
  tools/@aws-cdk/spec2cdk/package.json
  yarn.lock
Labels: p2, dependencies, contribution/core, pr-linter/exempt-readme, pr-linter/exempt-test, pr-linter/exempt-integ-test

#34009 fix(lambda): allow retryAttempts = -1 for infinite retries in EventSourceMapping
  packages/aws-cdk-lib/aws-lambda-event-sources/lib/stream.ts
  packages/aws-cdk-lib/aws-lambda-event-sources/test/dynamo.test.ts
  packages/aws-cdk-lib/aws-lambda/lib/event-source-mapping.ts
  packages/aws-cdk-lib/aws-lambda/test/event-source-mapping.test.ts
Labels: bug, p2, effort/small, contribution/core, pr-linter/exempt-integ-test

#33972 fix(stepfunctions-tasks): associateWithParent when using JSONata
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/stepfunctions/integ.start-execution-jsonata.js.snapshot/asset.97484721f29e34bf38d7a459804dd2d2a8dea6f8c27d7531e215bf4274fbc895.bundle/index.js
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/stepfunctions/integ.start-execution-jsonata.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/stepfunctions/integ.start-execution-jsonata.js.snapshot/integ-sfn-start-execution-jsonata.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/stepfunctions/integ.start-execution-jsonata.js.snapshot/integ-sfn-start-execution-jsonata.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/stepfunctions/integ.start-execution-jsonata.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/stepfunctions/integ.start-execution-jsonata.js.snapshot/integsfnstartexecutionjsonataintegDefaultTestDeployAssert66319094.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/stepfunctions/integ.start-execution-jsonata.js.snapshot/integsfnstartexecutionjsonataintegDefaultTestDeployAssert66319094.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/stepfunctions/integ.start-execution-jsonata.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/stepfunctions/integ.start-execution-jsonata.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/stepfunctions/integ.start-execution-jsonata.ts
  packages/aws-cdk-lib/aws-stepfunctions-tasks/lib/stepfunctions/start-execution.ts
  packages/aws-cdk-lib/aws-stepfunctions-tasks/test/stepfunctions/start-execution.test.ts
Labels: bug, p1, effort/medium, admired-contributor, pr/needs-maintainer-review

#34029 feat: update L1 CloudFormation resource definitions
  packages/aws-cdk-lib/package.json
  tools/@aws-cdk/spec2cdk/package.json
  yarn.lock
Labels: p2, dependencies, contribution/core, pr-linter/exempt-readme, pr-linter/exempt-test, pr-linter/exempt-integ-test

#34034 docs(s3): clarify encryption property's default behavior
  packages/aws-cdk-lib/aws-s3/lib/bucket.ts
Labels: p2, star-contributor

#34040 chore(merge-back): 2.188.0
  CHANGELOG.v2.alpha.md
  CHANGELOG.v2.md
  packages/aws-cdk-lib/core/lib/analytics-data-source/classes.ts
  packages/aws-cdk-lib/core/lib/analytics-data-source/enums.ts
  packages/aws-cdk-lib/core/lib/analytics-data-source/enums/module-enumlikes.json
  packages/aws-cdk-lib/core/lib/analytics-data-source/enums/module-enums.json
  version.v2.json
Labels: p2, pr/needs-community-review, pr/no-squash, auto-approve

#34005 feat(pipelines): add `V2` pipeline type support in L3 construct
  packages/@aws-cdk-testing/framework-integ/test/pipelines/test/integ.newpipeline-reduce-stagerole-scope.ts
  packages/@aws-cdk-testing/framework-integ/test/pipelines/test/integ.pipeline-v2.js.snapshot/UsePipelineRoleForActions.assets.json
  packages/@aws-cdk-testing/framework-integ/test/pipelines/test/integ.pipeline-v2.js.snapshot/UsePipelineRoleForActions.template.json
  packages/@aws-cdk-testing/framework-integ/test/pipelines/test/integ.pipeline-v2.js.snapshot/UsePipelineRoleForActionsPipeline72C9E132.dot
  packages/@aws-cdk-testing/framework-integ/test/pipelines/test/integ.pipeline-v2.js.snapshot/UsePipelineRoleForActionsTestDefaultTestDeployAssert16904455.assets.json
  packages/@aws-cdk-testing/framework-integ/test/pipelines/test/integ.pipeline-v2.js.snapshot/UsePipelineRoleForActionsTestDefaultTestDeployAssert16904455.template.json
  packages/@aws-cdk-testing/framework-integ/test/pipelines/test/integ.pipeline-v2.js.snapshot/asset.44e9c4d7a5d3fd2d677e1a7e416b2b56f6b0104bd5eff9cac5557b4c65a9dc61/index.js
  packages/@aws-cdk-testing/framework-integ/test/pipelines/test/integ.pipeline-v2.js.snapshot/asset.97484721f29e34bf38d7a459804dd2d2a8dea6f8c27d7531e215bf4274fbc895.bundle/index.js
  packages/@aws-cdk-testing/framework-integ/test/pipelines/test/integ.pipeline-v2.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/pipelines/test/integ.pipeline-v2.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/pipelines/test/integ.pipeline-v2.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/pipelines/test/integ.pipeline-v2.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/pipelines/test/integ.pipeline-v2.ts
  packages/aws-cdk-lib/pipelines/README.md
  packages/aws-cdk-lib/pipelines/lib/codepipeline/codepipeline.ts
  packages/aws-cdk-lib/pipelines/test/codepipeline/codepipeline.test.ts
Labels: p2, feature-request, pr/needs-community-review, effort/medium, repeat-contributor

#34056 chore: convert SkipReplicaDeletion custom resource property to boolean for replica table
  packages/@aws-cdk-testing/framework-integ/test/aws-dynamodb/test/integ.global-replicas-provisioned.js.snapshot/asset.7e256f5e4a92713cc232cd23819cb666756ee6023ce380130abac3b6a3fcea6a/index.js
  packages/@aws-cdk-testing/framework-integ/test/aws-dynamodb/test/integ.global-replicas-provisioned.js.snapshot/asset.beee194466d406430def0e84ec8b17a0aeb98fe29f5660882cb01e9db355d7c8/index.js
  packages/@aws-cdk-testing/framework-integ/test/aws-dynamodb/test/integ.global-replicas-provisioned.js.snapshot/aws-cdk-dynamodb-global-replicas-provisioned.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-dynamodb/test/integ.global-replicas-provisioned.js.snapshot/aws-cdk-dynamodb-global-replicas-provisioned.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-dynamodb/test/integ.global-replicas-provisioned.js.snapshot/awscdkdynamodbglobalreplicasprovisionedawscdkawsdynamodbReplicaProviderEA32CB30.nested.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-dynamodb/test/integ.global-replicas-provisioned.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-dynamodb/test/integ.global-replicas-provisioned.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-dynamodb/test/integ.global.js.snapshot/asset.7e256f5e4a92713cc232cd23819cb666756ee6023ce380130abac3b6a3fcea6a/index.js
  packages/@aws-cdk-testing/framework-integ/test/aws-dynamodb/test/integ.global.js.snapshot/asset.beee194466d406430def0e84ec8b17a0aeb98fe29f5660882cb01e9db355d7c8/index.js
  packages/@aws-cdk-testing/framework-integ/test/aws-dynamodb/test/integ.global.js.snapshot/cdk-dynamodb-global-20191121.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-dynamodb/test/integ.global.js.snapshot/cdk-dynamodb-global-20191121.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-dynamodb/test/integ.global.js.snapshot/cdkdynamodbglobal20191121awscdkawsdynamodbReplicaProviderB281C954.nested.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-dynamodb/test/integ.global.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-dynamodb/test/integ.global.js.snapshot/tree.json
  packages/@aws-cdk/custom-resource-handlers/lib/aws-dynamodb/replica-handler/index.ts
Labels: p2, contribution/core

#34038 docs: update contribution instructions with instructions for Docker replacements
  CONTRIBUTING.md
Labels: p2, pr/needs-community-review, beginning-contributor

#34015 docs(codepipeline-actions): fix permission's link for ECRBuildAndPublish
  packages/aws-cdk-lib/aws-codepipeline-actions/lib/ecr/build-and-publish-action.ts
Labels: p2, pr/needs-community-review, distinguished-contributor

#34022 docs(batch): add note on update fatgate compute environment
  packages/aws-cdk-lib/aws-batch/README.md
Labels: p2, beginning-contributor

#33948 docs(pipelines): add link to developer guide on how to use docker drop-in replacements
  packages/aws-cdk-lib/pipelines/README.md
Labels: p2, effort/medium, repeat-contributor

#33599 feat: support L2 constructs for Amazon S3 Tables
  packages/@aws-cdk/aws-s3tables-alpha/.eslintrc.js
  packages/@aws-cdk/aws-s3tables-alpha/.gitignore
  packages/@aws-cdk/aws-s3tables-alpha/.npmignore
  packages/@aws-cdk/aws-s3tables-alpha/LICENSE
  packages/@aws-cdk/aws-s3tables-alpha/NOTICE
  packages/@aws-cdk/aws-s3tables-alpha/README.md
  packages/@aws-cdk/aws-s3tables-alpha/jest.config.js
  packages/@aws-cdk/aws-s3tables-alpha/lib/index.ts
  packages/@aws-cdk/aws-s3tables-alpha/lib/permissions.ts
  packages/@aws-cdk/aws-s3tables-alpha/lib/table-bucket-policy.ts
  packages/@aws-cdk/aws-s3tables-alpha/lib/table-bucket.ts
  packages/@aws-cdk/aws-s3tables-alpha/lib/util.ts
  packages/@aws-cdk/aws-s3tables-alpha/package.json
  packages/@aws-cdk/aws-s3tables-alpha/test/integration/integ.table-bucket-with-grants.js.snapshot/TableBucketWithGrantIntegTestDefaultTestDeployAssert60E58AB6.assets.json
  packages/@aws-cdk/aws-s3tables-alpha/test/integration/integ.table-bucket-with-grants.js.snapshot/TableBucketWithGrantIntegTestDefaultTestDeployAssert60E58AB6.template.json
  packages/@aws-cdk/aws-s3tables-alpha/test/integration/integ.table-bucket-with-grants.js.snapshot/asset.530055f7515b3f0a47900f5df37e729ba40ca977b2d07b952bdefa2b8f883f42.bundle/index.js
  packages/@aws-cdk/aws-s3tables-alpha/test/integration/integ.table-bucket-with-grants.js.snapshot/cdk.out
  packages/@aws-cdk/aws-s3tables-alpha/test/integration/integ.table-bucket-with-grants.js.snapshot/grant-read-bucket-all-tables.assets.json
  packages/@aws-cdk/aws-s3tables-alpha/test/integration/integ.table-bucket-with-grants.js.snapshot/grant-read-bucket-all-tables.template.json
  packages/@aws-cdk/aws-s3tables-alpha/test/integration/integ.table-bucket-with-grants.js.snapshot/grant-read-bucket.assets.json
  packages/@aws-cdk/aws-s3tables-alpha/test/integration/integ.table-bucket-with-grants.js.snapshot/grant-read-bucket.template.json
  packages/@aws-cdk/aws-s3tables-alpha/test/integration/integ.table-bucket-with-grants.js.snapshot/grant-read-write-bucket-all-tables.assets.json
  packages/@aws-cdk/aws-s3tables-alpha/test/integration/integ.table-bucket-with-grants.js.snapshot/grant-read-write-bucket-all-tables.template.json
  packages/@aws-cdk/aws-s3tables-alpha/test/integration/integ.table-bucket-with-grants.js.snapshot/grant-read-write-bucket.assets.json
  packages/@aws-cdk/aws-s3tables-alpha/test/integration/integ.table-bucket-with-grants.js.snapshot/grant-read-write-bucket.template.json
  packages/@aws-cdk/aws-s3tables-alpha/test/integration/integ.table-bucket-with-grants.js.snapshot/grant-write-bucket-all-tables.assets.json
  packages/@aws-cdk/aws-s3tables-alpha/test/integration/integ.table-bucket-with-grants.js.snapshot/grant-write-bucket-all-tables.template.json
  packages/@aws-cdk/aws-s3tables-alpha/test/integration/integ.table-bucket-with-grants.js.snapshot/grant-write-bucket.assets.json
  packages/@aws-cdk/aws-s3tables-alpha/test/integration/integ.table-bucket-with-grants.js.snapshot/grant-write-bucket.template.json
  packages/@aws-cdk/aws-s3tables-alpha/test/integration/integ.table-bucket-with-grants.js.snapshot/integ.json
  packages/@aws-cdk/aws-s3tables-alpha/test/integration/integ.table-bucket-with-grants.js.snapshot/manifest.json
  packages/@aws-cdk/aws-s3tables-alpha/test/integration/integ.table-bucket-with-grants.js.snapshot/tree.json
  packages/@aws-cdk/aws-s3tables-alpha/test/integration/integ.table-bucket-with-grants.ts
  packages/@aws-cdk/aws-s3tables-alpha/test/integration/integ.table-bucket.js.snapshot/DefaultTestStack.assets.json
  packages/@aws-cdk/aws-s3tables-alpha/test/integration/integ.table-bucket.js.snapshot/DefaultTestStack.template.json
  packages/@aws-cdk/aws-s3tables-alpha/test/integration/integ.table-bucket.js.snapshot/TableBucketIntegTestDefaultTestDeployAssertA1204D2E.assets.json
  packages/@aws-cdk/aws-s3tables-alpha/test/integration/integ.table-bucket.js.snapshot/TableBucketIntegTestDefaultTestDeployAssertA1204D2E.template.json
  packages/@aws-cdk/aws-s3tables-alpha/test/integration/integ.table-bucket.js.snapshot/UnreferencedFileRemovalTestStack.assets.json
  packages/@aws-cdk/aws-s3tables-alpha/test/integration/integ.table-bucket.js.snapshot/UnreferencedFileRemovalTestStack.template.json
  packages/@aws-cdk/aws-s3tables-alpha/test/integration/integ.table-bucket.js.snapshot/asset.6eae57da2b343229b97cfa6b9fd2a70b0a928ebe32bb59e744e59440381146af.bundle/index.js
  packages/@aws-cdk/aws-s3tables-alpha/test/integration/integ.table-bucket.js.snapshot/cdk.out
  packages/@aws-cdk/aws-s3tables-alpha/test/integration/integ.table-bucket.js.snapshot/integ.json
  packages/@aws-cdk/aws-s3tables-alpha/test/integration/integ.table-bucket.js.snapshot/manifest.json
  packages/@aws-cdk/aws-s3tables-alpha/test/integration/integ.table-bucket.js.snapshot/tree.json
  packages/@aws-cdk/aws-s3tables-alpha/test/integration/integ.table-bucket.ts
  packages/@aws-cdk/aws-s3tables-alpha/test/table-bucket-grants.test.ts
  packages/@aws-cdk/aws-s3tables-alpha/test/table-bucket-policy.test.ts
  packages/@aws-cdk/aws-s3tables-alpha/test/table-bucket.test.ts
Labels: p1, beginning-contributor, pr/needs-maintainer-review

#34070 feat(bedrock): support Amazon Nova Reel 1.1
  packages/aws-cdk-lib/aws-bedrock/lib/foundation-model.ts
Labels: p2, pr-linter/exempt-readme, pr-linter/exempt-test, pr-linter/exempt-integ-test, distinguished-contributor

#34074 fix(codepipeline): replace account root principal with pipeline role in trust policy for cross-account actions (under feature flag)
  packages/@aws-cdk-testing/framework-integ/test/aws-codepipeline-actions/test/integ.cross-account-pipeline-cfn-action.js.snapshot/CdkPipelineCfnActionStack.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-codepipeline-actions/test/integ.cross-account-pipeline-cfn-action.js.snapshot/CdkPipelineCfnActionStack.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-codepipeline-actions/test/integ.cross-account-pipeline-cfn-action.js.snapshot/asset.12157b27d30ab71eb24ae65825f672ba5cc2c09dbb1703cd7adfcff3aeaca136.zip
  packages/@aws-cdk-testing/framework-integ/test/aws-codepipeline-actions/test/integ.cross-account-pipeline-cfn-action.js.snapshot/asset.44e9c4d7a5d3fd2d677e1a7e416b2b56f6b0104bd5eff9cac5557b4c65a9dc61/index.js
  packages/@aws-cdk-testing/framework-integ/test/aws-codepipeline-actions/test/integ.cross-account-pipeline-cfn-action.js.snapshot/asset.4fe0aba5e672b596d0f72505a9eec502f98d46906bb30fae2511fbdc1df4956f/index.py
  packages/@aws-cdk-testing/framework-integ/test/aws-codepipeline-actions/test/integ.cross-account-pipeline-cfn-action.js.snapshot/asset.5bcf205623ea5b34a1944fea4c9982e835555e710235ae6f60172097737302e2/template.yaml
  packages/@aws-cdk-testing/framework-integ/test/aws-codepipeline-actions/test/integ.cross-account-pipeline-cfn-action.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-codepipeline-actions/test/integ.cross-account-pipeline-cfn-action.js.snapshot/cross-account-support-stack-234567890123.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-codepipeline-actions/test/integ.cross-account-pipeline-cfn-action.js.snapshot/cross-account-support-stack-234567890123.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-codepipeline-actions/test/integ.cross-account-pipeline-cfn-action.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-codepipeline-actions/test/integ.cross-account-pipeline-cfn-action.js.snapshot/integpipelinecfncrossaccountDefaultTestDeployAssertC7E37541.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-codepipeline-actions/test/integ.cross-account-pipeline-cfn-action.js.snapshot/integpipelinecfncrossaccountDefaultTestDeployAssertC7E37541.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-codepipeline-actions/test/integ.cross-account-pipeline-cfn-action.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-codepipeline-actions/test/integ.cross-account-pipeline-cfn-action.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-codepipeline-actions/test/integ.cross-account-pipeline-cfn-action.ts
  packages/@aws-cdk-testing/framework-integ/test/aws-codepipeline-actions/test/integ.cross-account-pipeline-sfn-action.js.snapshot/CdkPipelineStepFunctionsActionStack.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-codepipeline-actions/test/integ.cross-account-pipeline-sfn-action.js.snapshot/CdkPipelineStepFunctionsActionStack.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-codepipeline-actions/test/integ.cross-account-pipeline-sfn-action.js.snapshot/CrossAccountStepFunctionStack.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-codepipeline-actions/test/integ.cross-account-pipeline-sfn-action.js.snapshot/CrossAccountStepFunctionStack.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-codepipeline-actions/test/integ.cross-account-pipeline-sfn-action.js.snapshot/asset.12157b27d30ab71eb24ae65825f672ba5cc2c09dbb1703cd7adfcff3aeaca136.zip
  packages/@aws-cdk-testing/framework-integ/test/aws-codepipeline-actions/test/integ.cross-account-pipeline-sfn-action.js.snapshot/asset.44e9c4d7a5d3fd2d677e1a7e416b2b56f6b0104bd5eff9cac5557b4c65a9dc61/index.js
  packages/@aws-cdk-testing/framework-integ/test/aws-codepipeline-actions/test/integ.cross-account-pipeline-sfn-action.js.snapshot/asset.4fe0aba5e672b596d0f72505a9eec502f98d46906bb30fae2511fbdc1df4956f/index.py
  packages/@aws-cdk-testing/framework-integ/test/aws-codepipeline-actions/test/integ.cross-account-pipeline-sfn-action.js.snapshot/asset.6a9a0507c3e2bfac9749f257bdd3d9f313c01ee3984ad7bf373597c341863d6f.zip
  packages/@aws-cdk-testing/framework-integ/test/aws-codepipeline-actions/test/integ.cross-account-pipeline-sfn-action.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-codepipeline-actions/test/integ.cross-account-pipeline-sfn-action.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-codepipeline-actions/test/integ.cross-account-pipeline-sfn-action.js.snapshot/integcrossaccountpipelinesfnactionDefaultTestDeployAssert199363B6.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-codepipeline-actions/test/integ.cross-account-pipeline-sfn-action.js.snapshot/integcrossaccountpipelinesfnactionDefaultTestDeployAssert199363B6.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-codepipeline-actions/test/integ.cross-account-pipeline-sfn-action.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-codepipeline-actions/test/integ.cross-account-pipeline-sfn-action.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-codepipeline-actions/test/integ.cross-account-pipeline-sfn-action.ts
  packages/@aws-cdk-testing/framework-integ/test/pipelines/test/integ.cross-account-pipeline-action.js.snapshot/CdkPipelineInvestigationStack.assets.json
  packages/@aws-cdk-testing/framework-integ/test/pipelines/test/integ.cross-account-pipeline-action.js.snapshot/CdkPipelineInvestigationStack.template.json
  packages/@aws-cdk-testing/framework-integ/test/pipelines/test/integ.cross-account-pipeline-action.js.snapshot/CdkPipelineInvestigationStackPipeline55B44D48.dot
  packages/@aws-cdk-testing/framework-integ/test/pipelines/test/integ.cross-account-pipeline-action.js.snapshot/CdkPipelineInvestigationTestDefaultTestDeployAssertC69AF0A9.assets.json
  packages/@aws-cdk-testing/framework-integ/test/pipelines/test/integ.cross-account-pipeline-action.js.snapshot/CdkPipelineInvestigationTestDefaultTestDeployAssertC69AF0A9.template.json
  packages/@aws-cdk-testing/framework-integ/test/pipelines/test/integ.cross-account-pipeline-action.js.snapshot/CrossAccountSourceStack.assets.json
  packages/@aws-cdk-testing/framework-integ/test/pipelines/test/integ.cross-account-pipeline-action.js.snapshot/CrossAccountSourceStack.template.json
  packages/@aws-cdk-testing/framework-integ/test/pipelines/test/integ.cross-account-pipeline-action.js.snapshot/assembly-CdkPipelineInvestigationStack-Prod/CdkPipelineInvestigationStackProdProdStackD4D4A90A.assets.json
  packages/@aws-cdk-testing/framework-integ/test/pipelines/test/integ.cross-account-pipeline-action.js.snapshot/assembly-CdkPipelineInvestigationStack-Prod/CdkPipelineInvestigationStackProdProdStackD4D4A90A.template.json
  packages/@aws-cdk-testing/framework-integ/test/pipelines/test/integ.cross-account-pipeline-action.js.snapshot/assembly-CdkPipelineInvestigationStack-Prod/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/pipelines/test/integ.cross-account-pipeline-action.js.snapshot/assembly-CdkPipelineInvestigationStack-Prod/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/pipelines/test/integ.cross-account-pipeline-action.js.snapshot/asset.12157b27d30ab71eb24ae65825f672ba5cc2c09dbb1703cd7adfcff3aeaca136.zip
  packages/@aws-cdk-testing/framework-integ/test/pipelines/test/integ.cross-account-pipeline-action.js.snapshot/asset.44e9c4d7a5d3fd2d677e1a7e416b2b56f6b0104bd5eff9cac5557b4c65a9dc61/index.js
  packages/@aws-cdk-testing/framework-integ/test/pipelines/test/integ.cross-account-pipeline-action.js.snapshot/asset.4fe0aba5e672b596d0f72505a9eec502f98d46906bb30fae2511fbdc1df4956f/index.py
  packages/@aws-cdk-testing/framework-integ/test/pipelines/test/integ.cross-account-pipeline-action.js.snapshot/asset.fbee18a86723a24ee3c75971c14b5bbff255873d741f6bbdde2218433a37a74d/source.zip
  packages/@aws-cdk-testing/framework-integ/test/pipelines/test/integ.cross-account-pipeline-action.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/pipelines/test/integ.cross-account-pipeline-action.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/pipelines/test/integ.cross-account-pipeline-action.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/pipelines/test/integ.cross-account-pipeline-action.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/pipelines/test/integ.cross-account-pipeline-action.ts
  packages/aws-cdk-lib/aws-codepipeline/lib/pipeline.ts
  packages/aws-cdk-lib/cx-api/FEATURE_FLAGS.md
  packages/aws-cdk-lib/cx-api/lib/features.ts
  packages/aws-cdk-lib/cx-api/test/features.test.ts
Labels: p2, contribution/core

#34064 feat: update L1 CloudFormation resource definitions
  packages/aws-cdk-lib/aws-dsql/.jsiirc.json
  packages/aws-cdk-lib/aws-dsql/README.md
  packages/aws-cdk-lib/aws-dsql/index.ts
  packages/aws-cdk-lib/aws-dsql/lib/index.ts
  packages/aws-cdk-lib/index.ts
  packages/aws-cdk-lib/package.json
  packages/aws-cdk-lib/scripts/scope-map.json
  tools/@aws-cdk/spec2cdk/package.json
  yarn.lock
Labels: p2, dependencies, contribution/core, pr-linter/exempt-readme, pr-linter/exempt-test, pr-linter/exempt-integ-test

#34054 feat(apigatewayv2): dualstack HTTP and WebSocket API
  packages/@aws-cdk-testing/framework-integ/test/aws-apigatewayv2/test/http/integ.api-dualstack.js.snapshot/DualStackHttpApiIntegDefaultTestDeployAssertCB101E5C.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-apigatewayv2/test/http/integ.api-dualstack.js.snapshot/DualStackHttpApiIntegDefaultTestDeployAssertCB101E5C.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-apigatewayv2/test/http/integ.api-dualstack.js.snapshot/DualStackHttpApiStack.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-apigatewayv2/test/http/integ.api-dualstack.js.snapshot/DualStackHttpApiStack.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-apigatewayv2/test/http/integ.api-dualstack.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-apigatewayv2/test/http/integ.api-dualstack.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-apigatewayv2/test/http/integ.api-dualstack.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-apigatewayv2/test/http/integ.api-dualstack.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-apigatewayv2/test/http/integ.api-dualstack.ts
  packages/@aws-cdk-testing/framework-integ/test/aws-apigatewayv2/test/websocket/integ.api-dualstack.js.snapshot/DualStackWebsocketApiIntegDefaultTestDeployAssert8B7A150B.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-apigatewayv2/test/websocket/integ.api-dualstack.js.snapshot/DualStackWebsocketApiIntegDefaultTestDeployAssert8B7A150B.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-apigatewayv2/test/websocket/integ.api-dualstack.js.snapshot/DualStackWebsocketApiStack.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-apigatewayv2/test/websocket/integ.api-dualstack.js.snapshot/DualStackWebsocketApiStack.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-apigatewayv2/test/websocket/integ.api-dualstack.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-apigatewayv2/test/websocket/integ.api-dualstack.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-apigatewayv2/test/websocket/integ.api-dualstack.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-apigatewayv2/test/websocket/integ.api-dualstack.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-apigatewayv2/test/websocket/integ.api-dualstack.ts
  packages/aws-cdk-lib/aws-apigatewayv2/README.md
  packages/aws-cdk-lib/aws-apigatewayv2/lib/common/api.ts
  packages/aws-cdk-lib/aws-apigatewayv2/lib/http/api.ts
  packages/aws-cdk-lib/aws-apigatewayv2/lib/websocket/api.ts
  packages/aws-cdk-lib/aws-apigatewayv2/test/http/api.test.ts
  packages/aws-cdk-lib/aws-apigatewayv2/test/websocket/api.test.ts
Labels: p2, distinguished-contributor, pr/needs-maintainer-review

#34084 chore(bedrock): support Pixtral Large 25.02
  packages/aws-cdk-lib/aws-bedrock/lib/foundation-model.ts
Labels: p2, pr/needs-community-review, distinguished-contributor

#34090 fix(custom-resources): custom resource config addLogRetentionLifetime parameter typo
  packages/aws-cdk-lib/custom-resources/lib/custom-resource-config/custom-resource-config.ts
Labels: bug, p2, pr-linter/exempt-test, pr-linter/exempt-integ-test, beginning-contributor

#34096 chore(merge-back): 2.189.0
  CHANGELOG.v2.alpha.md
  CHANGELOG.v2.md
  packages/aws-cdk-lib/core/lib/analytics-data-source/classes.ts
  packages/aws-cdk-lib/core/lib/analytics-data-source/enums.ts
  packages/aws-cdk-lib/core/lib/analytics-data-source/enums/module-enumlikes.json
  packages/aws-cdk-lib/core/lib/analytics-data-source/enums/module-enums.json
  packages/aws-cdk-lib/cx-api/FEATURE_FLAGS.md
  packages/aws-cdk-lib/cx-api/lib/features.ts
  version.v2.json
Labels: p2, pr/needs-community-review, pr/no-squash, auto-approve

#34095 chore: add partition map info if a new region is a new partition
  .github/ISSUE_TEMPLATE/region.yml
Labels: p2, contribution/core

#34098 feat(ses): throw ValidationErrors instead of untyped Errors
  packages/aws-cdk-lib/.eslintrc.js
  packages/aws-cdk-lib/aws-ses-actions/lib/add-header.ts
  packages/aws-cdk-lib/aws-ses/lib/configuration-set-event-destination.ts
  packages/aws-cdk-lib/aws-ses/lib/configuration-set.ts
  packages/aws-cdk-lib/aws-ses/lib/dedicated-ip-pool.ts
Labels: p2, pr-linter/exempt-readme, pr-linter/exempt-test, pr-linter/exempt-integ-test, beginning-contributor, pr-linter/exemption-requested, pr-linter/exempt-codecov

#33258 feat(rds): new `DatabaseInstance.fromLookup`
  packages/aws-cdk-lib/aws-rds/README.md
  packages/aws-cdk-lib/aws-rds/lib/instance.ts
  packages/aws-cdk-lib/aws-rds/test/instance.from-lookup.test.ts
Labels: p2, @aws-cdk/core, feature-request, effort/small, closed-for-staleness, pr-linter/exempt-integ-test, beginning-contributor

#33736 feat(elasticloadbalancingv2): subnet mappings for network load balancer
  packages/@aws-cdk-testing/framework-integ/test/aws-elasticloadbalancingv2/test/integ.nlb-subnet-mapping.js.snapshot/NlbSubnetMappingStack.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-elasticloadbalancingv2/test/integ.nlb-subnet-mapping.js.snapshot/NlbSubnetMappingStack.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-elasticloadbalancingv2/test/integ.nlb-subnet-mapping.js.snapshot/NlbSubnetMappingStackTestDefaultTestDeployAssert227D4D32.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-elasticloadbalancingv2/test/integ.nlb-subnet-mapping.js.snapshot/NlbSubnetMappingStackTestDefaultTestDeployAssert227D4D32.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-elasticloadbalancingv2/test/integ.nlb-subnet-mapping.js.snapshot/asset.a1acfc2b5f4f6b183fd2bb9863f486bc5edef6a357b355a070d9a0e502df418c/__entrypoint__.js
  packages/@aws-cdk-testing/framework-integ/test/aws-elasticloadbalancingv2/test/integ.nlb-subnet-mapping.js.snapshot/asset.a1acfc2b5f4f6b183fd2bb9863f486bc5edef6a357b355a070d9a0e502df418c/index.js
  packages/@aws-cdk-testing/framework-integ/test/aws-elasticloadbalancingv2/test/integ.nlb-subnet-mapping.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-elasticloadbalancingv2/test/integ.nlb-subnet-mapping.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-elasticloadbalancingv2/test/integ.nlb-subnet-mapping.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-elasticloadbalancingv2/test/integ.nlb-subnet-mapping.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-elasticloadbalancingv2/test/integ.nlb-subnet-mapping.ts
  packages/aws-cdk-lib/aws-elasticloadbalancingv2/README.md
  packages/aws-cdk-lib/aws-elasticloadbalancingv2/lib/nlb/network-load-balancer.ts
  packages/aws-cdk-lib/aws-elasticloadbalancingv2/lib/shared/base-load-balancer.ts
  packages/aws-cdk-lib/aws-elasticloadbalancingv2/test/nlb/load-balancer.test.ts
Labels: p1, feature-request, effort/medium, distinguished-contributor, pr/needs-maintainer-review

#34113 chore: `cx-api` should depend on `cloud-assembly-schema` using `>=`
  packages/@aws-cdk/cx-api/package.json
Labels: p2, contribution/core

#34108 chore(s3tables-alpha): add rosetta support to docs and make package non-private
  packages/@aws-cdk/aws-s3tables-alpha/.npmignore
  packages/@aws-cdk/aws-s3tables-alpha/README.md
  packages/@aws-cdk/aws-s3tables-alpha/awslint.json
  packages/@aws-cdk/aws-s3tables-alpha/lib/table-bucket.ts
  packages/@aws-cdk/aws-s3tables-alpha/package.json
  packages/@aws-cdk/aws-s3tables-alpha/rosetta/default.ts-fixture
Labels: p2, pr/needs-community-review, beginning-contributor

#34102 fix(cloudfront): fix validation for unresolved webAclId tokens
  packages/aws-cdk-lib/aws-cloudfront/lib/distribution.ts
  packages/aws-cdk-lib/aws-cloudfront/test/distribution.test.ts
Labels: bug, p1, effort/medium, contribution/core, pr-linter/exempt-test, pr-linter/exempt-integ-test, pr/needs-maintainer-review

#34120 feat(fsx): throw `ValidationErrors` instead of untyped Errors
  packages/aws-cdk-lib/.eslintrc.js
  packages/aws-cdk-lib/aws-fsx/lib/daily-automatic-backup-start-time.ts
  packages/aws-cdk-lib/aws-fsx/lib/lustre-file-system.ts
  packages/aws-cdk-lib/aws-fsx/lib/maintenance-time.ts
Labels: p2, pr-linter/exempt-readme, pr-linter/exempt-test, pr-linter/exempt-integ-test, distinguished-contributor, pr-linter/exemption-requested

#34133 docs(pipelines): remove notice for lack of CodePipeline V2 support
  packages/aws-cdk-lib/pipelines/README.md
Labels: p2, repeat-contributor

#34123 fix(core): typo
  packages/aws-cdk-lib/core/lib/token.ts
Labels: p2, pr-linter/exempt-test, pr-linter/exempt-integ-test, beginning-contributor, pr-linter/exemption-requested

#33978 feat(s3): allow specifying a custom IAM Role for bucket replication
  packages/@aws-cdk-testing/framework-integ/test/aws-s3/test/integ.bucket-replication-use-custom-role.js.snapshot/BucketReplicationTestStack.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-s3/test/integ.bucket-replication-use-custom-role.js.snapshot/BucketReplicationTestStack.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-s3/test/integ.bucket-replication-use-custom-role.js.snapshot/ReplicationIntegDefaultTestDeployAssert2C07A074.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-s3/test/integ.bucket-replication-use-custom-role.js.snapshot/ReplicationIntegDefaultTestDeployAssert2C07A074.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-s3/test/integ.bucket-replication-use-custom-role.js.snapshot/asset.44e9c4d7a5d3fd2d677e1a7e416b2b56f6b0104bd5eff9cac5557b4c65a9dc61/index.js
  packages/@aws-cdk-testing/framework-integ/test/aws-s3/test/integ.bucket-replication-use-custom-role.js.snapshot/asset.530055f7515b3f0a47900f5df37e729ba40ca977b2d07b952bdefa2b8f883f42.bundle/index.js
  packages/@aws-cdk-testing/framework-integ/test/aws-s3/test/integ.bucket-replication-use-custom-role.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-s3/test/integ.bucket-replication-use-custom-role.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-s3/test/integ.bucket-replication-use-custom-role.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-s3/test/integ.bucket-replication-use-custom-role.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-s3/test/integ.bucket-replication-use-custom-role.ts
  packages/aws-cdk-lib/aws-s3/README.md
  packages/aws-cdk-lib/aws-s3/lib/bucket.ts
  packages/aws-cdk-lib/aws-s3/test/bucket.test.ts
Labels: p2, feature-request, effort/medium, beginning-contributor

#34092 chore: enum updater improvement
  .github/workflows/enum-auto-updater.yml
  tools/@aws-cdk/enum-updater/lib/cdk-enums.json
  tools/@aws-cdk/enum-updater/lib/exclude-values.json
  tools/@aws-cdk/enum-updater/lib/exclude_values.json
  tools/@aws-cdk/enum-updater/lib/missing-enum-updater.ts
  tools/@aws-cdk/enum-updater/lib/sdk-enums.json
  tools/@aws-cdk/enum-updater/lib/static-enum-mapping-updater.ts
  tools/@aws-cdk/enum-updater/lib/static-enum-mapping.json
  tools/@aws-cdk/enum-updater/lib/unmatched-enums.json
  tools/@aws-cdk/enum-updater/test/static-enum-mapping-updater.test.ts
Labels: p2, contribution/core

#34094 fix(ec2-alpha): add multiple NATGW to the VPC using addNatGateway method
  packages/@aws-cdk/aws-ec2-alpha/lib/route.ts
  packages/@aws-cdk/aws-ec2-alpha/lib/subnet-v2.ts
  packages/@aws-cdk/aws-ec2-alpha/lib/vpc-v2-base.ts
  packages/@aws-cdk/aws-ec2-alpha/test/integ.test-import.js.snapshot/cdk.out
  packages/@aws-cdk/aws-ec2-alpha/test/integ.test-import.js.snapshot/integ.json
  packages/@aws-cdk/aws-ec2-alpha/test/integ.test-import.js.snapshot/integtestmodelDefaultTestDeployAssertCF40BD53.assets.json
  packages/@aws-cdk/aws-ec2-alpha/test/integ.test-import.js.snapshot/manifest.json
  packages/@aws-cdk/aws-ec2-alpha/test/integ.test-import.js.snapshot/tree.json
  packages/@aws-cdk/aws-ec2-alpha/test/integ.test-import.js.snapshot/vpcv2-import-integ-test.assets.json
  packages/@aws-cdk/aws-ec2-alpha/test/integ.test-import.js.snapshot/vpcv2-import-integ-test.template.json
  packages/@aws-cdk/aws-ec2-alpha/test/integ.vpc-add-gateways.js.snapshot/VpcSameAccountIntegDefaultTestDeployAssertDA1BF34D.assets.json
  packages/@aws-cdk/aws-ec2-alpha/test/integ.vpc-add-gateways.js.snapshot/VpcSameAccountIntegDefaultTestDeployAssertDA1BF34D.template.json
  packages/@aws-cdk/aws-ec2-alpha/test/integ.vpc-add-gateways.js.snapshot/asset.97484721f29e34bf38d7a459804dd2d2a8dea6f8c27d7531e215bf4274fbc895.bundle/index.js
  packages/@aws-cdk/aws-ec2-alpha/test/integ.vpc-add-gateways.js.snapshot/aws-cdk-ec2-alpha-gateways.assets.json
  packages/@aws-cdk/aws-ec2-alpha/test/integ.vpc-add-gateways.js.snapshot/aws-cdk-ec2-alpha-gateways.template.json
  packages/@aws-cdk/aws-ec2-alpha/test/integ.vpc-add-gateways.js.snapshot/cdk.out
  packages/@aws-cdk/aws-ec2-alpha/test/integ.vpc-add-gateways.js.snapshot/integ.json
  packages/@aws-cdk/aws-ec2-alpha/test/integ.vpc-add-gateways.js.snapshot/manifest.json
  packages/@aws-cdk/aws-ec2-alpha/test/integ.vpc-add-gateways.js.snapshot/tree.json
  packages/@aws-cdk/aws-ec2-alpha/test/integ.vpc-add-gateways.ts
  packages/@aws-cdk/aws-ec2-alpha/test/integ.vpc-shared-route-table.js.snapshot/asset.530055f7515b3f0a47900f5df37e729ba40ca977b2d07b952bdefa2b8f883f42.bundle/index.js
  packages/@aws-cdk/aws-ec2-alpha/test/integ.vpc-v2-alpha.js.snapshot/aws-cdk-vpcv2-alpha.assets.json
  packages/@aws-cdk/aws-ec2-alpha/test/integ.vpc-v2-alpha.js.snapshot/aws-cdk-vpcv2-alpha.template.json
  packages/@aws-cdk/aws-ec2-alpha/test/integ.vpc-v2-alpha.js.snapshot/cdk.out
  packages/@aws-cdk/aws-ec2-alpha/test/integ.vpc-v2-alpha.js.snapshot/integ.json
  packages/@aws-cdk/aws-ec2-alpha/test/integ.vpc-v2-alpha.js.snapshot/integtestmodelDefaultTestDeployAssertCF40BD53.assets.json
  packages/@aws-cdk/aws-ec2-alpha/test/integ.vpc-v2-alpha.js.snapshot/manifest.json
  packages/@aws-cdk/aws-ec2-alpha/test/integ.vpc-v2-alpha.js.snapshot/tree.json
  packages/@aws-cdk/aws-ec2-alpha/test/integ.vpc-v2-tagging.js.snapshot/asset.97484721f29e34bf38d7a459804dd2d2a8dea6f8c27d7531e215bf4274fbc895.bundle/index.js
  packages/@aws-cdk/aws-ec2-alpha/test/integ.vpc-v2-tagging.js.snapshot/aws-cdk-ec2-alpha-tag.assets.json
  packages/@aws-cdk/aws-ec2-alpha/test/integ.vpc-v2-tagging.js.snapshot/aws-cdk-ec2-alpha-tag.template.json
  packages/@aws-cdk/aws-ec2-alpha/test/integ.vpc-v2-tagging.js.snapshot/cdk.out
  packages/@aws-cdk/aws-ec2-alpha/test/integ.vpc-v2-tagging.js.snapshot/integ.json
  packages/@aws-cdk/aws-ec2-alpha/test/integ.vpc-v2-tagging.js.snapshot/integtestmodelDefaultTestDeployAssertCF40BD53.assets.json
  packages/@aws-cdk/aws-ec2-alpha/test/integ.vpc-v2-tagging.js.snapshot/integtestmodelDefaultTestDeployAssertCF40BD53.template.json
  packages/@aws-cdk/aws-ec2-alpha/test/integ.vpc-v2-tagging.js.snapshot/manifest.json
  packages/@aws-cdk/aws-ec2-alpha/test/integ.vpc-v2-tagging.js.snapshot/tree.json
  packages/@aws-cdk/aws-ec2-alpha/test/vpc-add-method.test.ts
Labels: p2, contribution/core, pr/needs-maintainer-review

#34115 chore: new github action to run security-guardian
  .github/workflows/security-guardian.yml
  tools/@aws-cdk/security-guardian/.gitignore
  tools/@aws-cdk/security-guardian/LICENSE
  tools/@aws-cdk/security-guardian/README.md
  tools/@aws-cdk/security-guardian/action.yml
  tools/@aws-cdk/security-guardian/package-lock.json
  tools/@aws-cdk/security-guardian/package.json
  tools/@aws-cdk/security-guardian/rules/trust_scope_rules.guard
  tools/@aws-cdk/security-guardian/src/index.ts
  tools/@aws-cdk/security-guardian/test/templates/CMCMK-Stack.template.json
  tools/@aws-cdk/security-guardian/test/templates/StagingStack-default-resourcesmax-ACCOUNT-REGION.template.json
  tools/@aws-cdk/security-guardian/test/templates/codepipelinenestedstackPipelineCrossRegionStack37C990C7.nested.template.json
  tools/@aws-cdk/security-guardian/tsconfig.json
Labels: p2, contribution/core, pr-linter/exemption-requested, pr/needs-maintainer-review

#34140 docs(iam): correct documentation of Grant.resourceStatements
  packages/aws-cdk-lib/aws-iam/lib/grant.ts
Labels: p2, beginning-contributor

#34134 feat(bedrock): support Amazon Nova Sonic 1.0
  packages/aws-cdk-lib/aws-bedrock/lib/foundation-model.ts
Labels: p2, pr-linter/exempt-readme, pr-linter/exempt-test, pr-linter/exempt-integ-test, admired-contributor, pr/needs-maintainer-review

#34152 chore: update codecov.yml to allow oidc to read contents and write pages
  .github/workflows/codecov.yml
Labels: p2, contribution/core, pr/needs-maintainer-review

#34154 chore: resolves bad object error when its run in the context of main branch
  .github/workflows/security-guardian.yml
Labels: p2, contribution/core

#34155 revert(ecs): add validation checks to memory cpu combinations of FARGATE compatible task definitions
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs/test/integ.fargate-task-def.js.snapshot/FargateTaskDefinitionDefaultTestDeployAssertD76B1D35.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs/test/integ.fargate-task-def.js.snapshot/FargateTaskDefinitionDefaultTestDeployAssertD76B1D35.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs/test/integ.fargate-task-def.js.snapshot/aws-ecs-fargate-task-def.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs/test/integ.fargate-task-def.js.snapshot/aws-ecs-fargate-task-def.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs/test/integ.fargate-task-def.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs/test/integ.fargate-task-def.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs/test/integ.fargate-task-def.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs/test/integ.fargate-task-def.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs/test/integ.fargate-task-def.ts
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs/test/integ.task-def.js.snapshot/TaskDefinitionDefaultTestDeployAssertF13B2133.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs/test/integ.task-def.js.snapshot/TaskDefinitionDefaultTestDeployAssertF13B2133.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs/test/integ.task-def.js.snapshot/aws-ecs-task-def.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs/test/integ.task-def.js.snapshot/aws-ecs-task-def.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs/test/integ.task-def.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs/test/integ.task-def.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs/test/integ.task-def.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs/test/integ.task-def.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs/test/integ.task-def.ts
  packages/aws-cdk-lib/aws-ecs-patterns/test/fargate/load-balanced-fargate-service-v2.test.ts
  packages/aws-cdk-lib/aws-ecs-patterns/test/fargate/load-balanced-fargate-service.test.ts
  packages/aws-cdk-lib/aws-ecs-patterns/test/fargate/scheduled-fargate-task.test.ts
  packages/aws-cdk-lib/aws-ecs/README.md
  packages/aws-cdk-lib/aws-ecs/lib/base/task-definition.ts
  packages/aws-cdk-lib/aws-ecs/test/fargate/fargate-task-definition.test.ts
  packages/aws-cdk-lib/aws-ecs/test/task-definition.test.ts
Labels: p2, contribution/core

#34127 feat(ec2): throw ValidationErrors instead of untyped Errors
  packages/aws-cdk-lib/.eslintrc.js
  packages/aws-cdk-lib/aws-ec2/lib/bastion-host.ts
  packages/aws-cdk-lib/aws-ec2/lib/cfn-init-elements.ts
  packages/aws-cdk-lib/aws-ec2/lib/cfn-init.ts
  packages/aws-cdk-lib/aws-ec2/lib/cidr-splits.ts
  packages/aws-cdk-lib/aws-ec2/lib/client-vpn-authorization-rule.ts
  packages/aws-cdk-lib/aws-ec2/lib/client-vpn-endpoint.ts
  packages/aws-cdk-lib/aws-ec2/lib/client-vpn-route.ts
  packages/aws-cdk-lib/aws-ec2/lib/connections.ts
  packages/aws-cdk-lib/aws-ec2/lib/instance-types.ts
  packages/aws-cdk-lib/aws-ec2/lib/instance.ts
  packages/aws-cdk-lib/aws-ec2/lib/ip-addresses.ts
  packages/aws-cdk-lib/aws-ec2/lib/key-pair.ts
  packages/aws-cdk-lib/aws-ec2/lib/launch-template.ts
  packages/aws-cdk-lib/aws-ec2/lib/machine-image/machine-image.ts
  packages/aws-cdk-lib/aws-ec2/lib/nat.ts
  packages/aws-cdk-lib/aws-ec2/lib/network-util.ts
  packages/aws-cdk-lib/aws-ec2/lib/peer.ts
  packages/aws-cdk-lib/aws-ec2/lib/placement-group.ts
  packages/aws-cdk-lib/aws-ec2/lib/prefix-list.ts
  packages/aws-cdk-lib/aws-ec2/lib/private/ebs-util.ts
  packages/aws-cdk-lib/aws-ec2/lib/security-group.ts
  packages/aws-cdk-lib/aws-ec2/lib/subnet.ts
  packages/aws-cdk-lib/aws-ec2/lib/user-data.ts
  packages/aws-cdk-lib/aws-ec2/lib/util.ts
  packages/aws-cdk-lib/aws-ec2/lib/volume.ts
  packages/aws-cdk-lib/aws-ec2/lib/vpc-endpoint-service.ts
  packages/aws-cdk-lib/aws-ec2/lib/vpc-endpoint.ts
  packages/aws-cdk-lib/aws-ec2/lib/vpc-flow-logs.ts
  packages/aws-cdk-lib/aws-ec2/lib/vpc.ts
  packages/aws-cdk-lib/aws-ec2/lib/vpn.ts
  packages/aws-cdk-lib/aws-ec2/test/volume.test.ts
  packages/aws-cdk-lib/core/lib/cfn-resource.ts
Labels: p2, pr-linter/exempt-readme, pr-linter/exempt-integ-test, repeat-contributor

#33989 feat(neptune-alpha): add engine versions up to v1.4.5.0
  packages/@aws-cdk/aws-neptune-alpha/README.md
  packages/@aws-cdk/aws-neptune-alpha/lib/cluster.ts
  packages/@aws-cdk/aws-neptune-alpha/lib/parameter-group.ts
  packages/@aws-cdk/aws-neptune-alpha/test/cluster.test.ts
  packages/@aws-cdk/aws-neptune-alpha/test/integ.cluster-ev14.js.snapshot/ClusterTestDefaultTestDeployAssert6A1BBA9D.assets.json
  packages/@aws-cdk/aws-neptune-alpha/test/integ.cluster-ev14.js.snapshot/ClusterTestDefaultTestDeployAssert6A1BBA9D.template.json
  packages/@aws-cdk/aws-neptune-alpha/test/integ.cluster-ev14.js.snapshot/aws-cdk-neptune-integ.assets.json
  packages/@aws-cdk/aws-neptune-alpha/test/integ.cluster-ev14.js.snapshot/aws-cdk-neptune-integ.template.json
  packages/@aws-cdk/aws-neptune-alpha/test/integ.cluster-ev14.js.snapshot/cdk.out
  packages/@aws-cdk/aws-neptune-alpha/test/integ.cluster-ev14.js.snapshot/integ.json
  packages/@aws-cdk/aws-neptune-alpha/test/integ.cluster-ev14.js.snapshot/manifest.json
  packages/@aws-cdk/aws-neptune-alpha/test/integ.cluster-ev14.js.snapshot/tree.json
  packages/@aws-cdk/aws-neptune-alpha/test/integ.cluster-ev14.ts
Labels: p2, feature-request, effort/small, beginning-contributor

#34109 feat(cognito-identitypool): throw ValidationErrors instead of untyped Errors
  packages/aws-cdk-lib/.eslintrc.js
  packages/aws-cdk-lib/aws-cognito-identitypool/lib/identitypool.ts
Labels: p2, pr-linter/exempt-readme, pr-linter/exempt-test, pr-linter/exempt-integ-test, repeat-contributor

#34169 chore: update codecov.yml to resolve upload issue
  .github/workflows/codecov.yml
Labels: p2, contribution/core

#34164 feat(cloudformation): update L1 CloudFormation resource definitions
  packages/aws-cdk-lib/package.json
  tools/@aws-cdk/spec2cdk/package.json
  yarn.lock
Labels: p2, dependencies, contribution/core, pr-linter/exempt-readme, pr-linter/exempt-test, pr-linter/exempt-breaking-change, pr-linter/exempt-integ-test, pr/needs-maintainer-review

#34172 chore(merge-back): 2.190.0
  CHANGELOG.v2.alpha.md
  CHANGELOG.v2.md
  packages/aws-cdk-lib/core/lib/analytics-data-source/classes.ts
  packages/aws-cdk-lib/core/lib/analytics-data-source/enums.ts
  packages/aws-cdk-lib/core/lib/analytics-data-source/enums/module-enumlikes.json
  packages/aws-cdk-lib/core/lib/analytics-data-source/enums/module-enums.json
  packages/aws-cdk-lib/cx-api/FEATURE_FLAGS.md
  packages/aws-cdk-lib/recommended-feature-flags.json
  version.v2.json
Labels: p2, pr/needs-community-review, pr/no-squash, auto-approve

#34174 feat(location): throw ValidationError instead of untyped errors
  packages/@aws-cdk/aws-location-alpha/.eslintrc.js
  packages/@aws-cdk/aws-location-alpha/lib/geofence-collection.ts
  packages/@aws-cdk/aws-location-alpha/lib/map.ts
  packages/@aws-cdk/aws-location-alpha/lib/place-index.ts
  packages/@aws-cdk/aws-location-alpha/lib/route-calculator.ts
  packages/@aws-cdk/aws-location-alpha/lib/tracker.ts
Labels: p2, pr-linter/exempt-readme, pr-linter/exempt-test, pr-linter/exempt-integ-test, distinguished-contributor, pr-linter/exemption-requested

#34180 chore: fix the enum backfill workflow to configure the cdk automation github user
  .github/workflows/enum-auto-updater.yml
Labels: p2, contribution/core, pr/needs-maintainer-review

#34182 chore: fix the enum backfill action
  .github/workflows/enum-auto-updater.yml
Labels: p2, contribution/core

#34188 chore: fix enum updater static mapping PR process
  .github/workflows/enum-auto-updater.yml
Labels: p2, contribution/core

#34045 feat(rds): add Aurora MySQL versions 2.12.4, 3.08.2
  packages/aws-cdk-lib/aws-rds/lib/cluster-engine.ts
  packages/aws-cdk-lib/aws-rds/test/cluster-engine.test.ts
Labels: p2, pr-linter/exempt-readme, pr-linter/exempt-integ-test, star-contributor

#34194 chore: exclude some EC2 enum values
  tools/@aws-cdk/enum-updater/lib/exclude_values.json
Labels: p2, contribution/core, pr/needs-maintainer-review

#34197 feat(codebuild): add additional build images for lambda
  packages/aws-cdk-lib/aws-codebuild/lib/linux-arm-lambda-build-image.ts
  packages/aws-cdk-lib/aws-codebuild/lib/linux-lambda-build-image.ts
Labels: p2, pr-linter/exempt-readme, pr-linter/exempt-test, pr-linter/exempt-integ-test, beginning-contributor

#34210 chore: add new team member Y-JayKim
  .github/workflows/github-merit-badger.yml
  .mergify.yml
Labels: p2, beginning-contributor

#34151 chore(rds): add postgres engine 16.8, 15.12, 14.17 and 13.20
  packages/aws-cdk-lib/aws-rds/lib/cluster-engine.ts
  packages/aws-cdk-lib/aws-rds/test/cluster-engine.test.ts
Labels: p2, admired-contributor, pr/needs-maintainer-review

#34214 feat(msk): throw ValidationError instead of untyped errors
  packages/@aws-cdk/aws-msk-alpha/.eslintrc.js
  packages/@aws-cdk/aws-msk-alpha/lib/cluster.ts
  packages/@aws-cdk/aws-msk-alpha/lib/serverless-cluster.ts
Labels: p2, pr-linter/exempt-readme, pr-linter/exempt-test, pr-linter/exempt-integ-test, distinguished-contributor, pr-linter/exemption-requested

#34221 chore: update error message to include key name for metric
  packages/aws-cdk-lib/aws-cloudwatch/lib/metric.ts
Labels: p2, feature-request, effort/small, contribution/core, pr/needs-maintainer-review

#34175 feat(rds): add support for SQL Server engine versions 15.00.4430.1.v1 and 16.00.4185.3.v1
  packages/aws-cdk-lib/aws-rds/lib/instance-engine.ts
Labels: p2, pr-linter/exempt-readme, pr-linter/exempt-test, pr-linter/exempt-integ-test, distinguished-contributor

#34226 chore(merge-back): 2.191.0
  CHANGELOG.v2.alpha.md
  CHANGELOG.v2.md
  packages/aws-cdk-lib/core/lib/analytics-data-source/enums/module-enumlikes.json
  version.v2.json
Labels: p2, pr/needs-community-review, pr/no-squash, auto-approve

#33603 feat(iam): support `Role.fromLookup()` method
  packages/@aws-cdk-testing/framework-integ/test/aws-iam/test/integ.role-from-lookup.js.snapshot/LookupRoleStack.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-iam/test/integ.role-from-lookup.js.snapshot/LookupRoleStack.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-iam/test/integ.role-from-lookup.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-iam/test/integ.role-from-lookup.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-iam/test/integ.role-from-lookup.js.snapshot/integiamrolefromlookupDefaultTestDeployAssert63955306.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-iam/test/integ.role-from-lookup.js.snapshot/integiamrolefromlookupDefaultTestDeployAssert63955306.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-iam/test/integ.role-from-lookup.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-iam/test/integ.role-from-lookup.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-iam/test/integ.role-from-lookup.ts
  packages/@aws-cdk-testing/framework-integ/test/aws-iam/test/policy-document.json
  packages/aws-cdk-lib/aws-iam/README.md
  packages/aws-cdk-lib/aws-iam/lib/role.ts
  packages/aws-cdk-lib/aws-iam/test/role.from-lookup.test.ts
Labels: p2, feature-request, pr/needs-community-review, effort/medium, distinguished-contributor

#34234 chore(cognito-identitypool): make role attachment resource public
  packages/aws-cdk-lib/aws-cognito-identitypool/lib/identitypool.ts
Labels: p2, contribution/core, pr/needs-maintainer-review

#33984 feat(ses): add fromEmailIdentityArn
  packages/@aws-cdk-testing/framework-integ/test/aws-ses/test/integ.email-identity-from-arn.js.snapshot/EmailIdentityFromArnIntegDefaultTestDeployAssertCC4631C7.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ses/test/integ.email-identity-from-arn.js.snapshot/EmailIdentityFromArnIntegDefaultTestDeployAssertCC4631C7.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ses/test/integ.email-identity-from-arn.js.snapshot/asset.ab3156800c2f322f16da8bff913172139189a387dd64a4e622f82a790561fd4d/index.py
  packages/@aws-cdk-testing/framework-integ/test/aws-ses/test/integ.email-identity-from-arn.js.snapshot/cdk-ses-email-identity-from-arn-integ.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ses/test/integ.email-identity-from-arn.js.snapshot/cdk-ses-email-identity-from-arn-integ.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ses/test/integ.email-identity-from-arn.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-ses/test/integ.email-identity-from-arn.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ses/test/integ.email-identity-from-arn.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ses/test/integ.email-identity-from-arn.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ses/test/integ.email-identity-from-arn.ts
  packages/aws-cdk-lib/aws-ses/README.md
  packages/aws-cdk-lib/aws-ses/lib/email-identity.ts
  packages/aws-cdk-lib/aws-ses/test/email-identity.test.ts
Labels: p2, feature-request, pr/needs-community-review, beginning-contributor

#34198 feat(apigateway): add `mode` property for `SpecRestApi`
  packages/@aws-cdk-testing/framework-integ/test/aws-apigateway/test/integ.spec-restapi.js.snapshot/apigatewayspecrestapiDefaultTestDeployAssertD16AA485.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-apigateway/test/integ.spec-restapi.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-apigateway/test/integ.spec-restapi.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-apigateway/test/integ.spec-restapi.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-apigateway/test/integ.spec-restapi.js.snapshot/test-apigateway-spec-restapi.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-apigateway/test/integ.spec-restapi.js.snapshot/test-apigateway-spec-restapi.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-apigateway/test/integ.spec-restapi.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-apigateway/test/integ.spec-restapi.ts
  packages/aws-cdk-lib/aws-apigateway/README.md
  packages/aws-cdk-lib/aws-apigateway/lib/restapi.ts
  packages/aws-cdk-lib/aws-apigateway/test/restapi.test.ts
Labels: p2, repeat-contributor

#33779 feat(events): `Rule` support role
  packages/@aws-cdk-testing/framework-integ/test/aws-events/test/integ.rule.js.snapshot/IntegTestBatchDefaultEnvVarsStackDefaultTestDeployAssertC15EFFF2.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-events/test/integ.rule.js.snapshot/RuleStack.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-events/test/integ.rule.js.snapshot/RuleStack.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-events/test/integ.rule.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-events/test/integ.rule.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-events/test/integ.rule.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-events/test/integ.rule.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-events/test/integ.rule.ts
  packages/aws-cdk-lib/aws-events/README.md
  packages/aws-cdk-lib/aws-events/lib/rule.ts
  packages/aws-cdk-lib/aws-events/test/rule.test.ts
Labels: p2, feature-request, effort/small, pr/needs-community-review, admired-contributor

#34039 feat(codepipeline-actions): add pipeline invoke action support.
  packages/@aws-cdk-testing/framework-integ/test/aws-codepipeline-actions/test/integ.pipeline-invoke-action.js.snapshot/Default.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-codepipeline-actions/test/integ.pipeline-invoke-action.js.snapshot/Default.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-codepipeline-actions/test/integ.pipeline-invoke-action.js.snapshot/asset.97484721f29e34bf38d7a459804dd2d2a8dea6f8c27d7531e215bf4274fbc895.bundle/index.js
  packages/@aws-cdk-testing/framework-integ/test/aws-codepipeline-actions/test/integ.pipeline-invoke-action.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-codepipeline-actions/test/integ.pipeline-invoke-action.js.snapshot/codepipelineintegtestDefaultTestDeployAssert88EAAC45.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-codepipeline-actions/test/integ.pipeline-invoke-action.js.snapshot/codepipelineintegtestDefaultTestDeployAssert88EAAC45.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-codepipeline-actions/test/integ.pipeline-invoke-action.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-codepipeline-actions/test/integ.pipeline-invoke-action.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-codepipeline-actions/test/integ.pipeline-invoke-action.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-codepipeline-actions/test/integ.pipeline-invoke-action.ts
  packages/aws-cdk-lib/aws-codepipeline-actions/README.md
  packages/aws-cdk-lib/aws-codepipeline-actions/lib/codepipeline/invoke-action.ts
  packages/aws-cdk-lib/aws-codepipeline-actions/lib/index.ts
  packages/aws-cdk-lib/aws-codepipeline-actions/test/codepipeline/invoke-action.test.ts
  packages/aws-cdk-lib/pipelines/lib/codepipeline/codepipeline.ts
Labels: p2, feature-request, effort/medium, repeat-contributor, pr/needs-maintainer-review

#34245 chore(ec2-alpha): check IPAM Pool local in Operating Region only if specified
  packages/@aws-cdk/aws-ec2-alpha/lib/ipam.ts
  packages/@aws-cdk/aws-ec2-alpha/test/ipam.test.ts
Labels: bug, p2, contribution/core

#34250 chore(merge-back): 2.192.0
  CHANGELOG.v2.alpha.md
  CHANGELOG.v2.md
  packages/aws-cdk-lib/core/lib/analytics-data-source/classes.ts
  packages/aws-cdk-lib/core/lib/analytics-data-source/enums.ts
  packages/aws-cdk-lib/core/lib/analytics-data-source/enums/module-enumlikes.json
  packages/aws-cdk-lib/core/lib/analytics-data-source/enums/module-enums.json
  version.v2.json
Labels: p2, pr/needs-community-review, pr/no-squash, auto-approve

#34239 feat(kinesis): throw `ValidationErrors` instead of untyped Errors
  packages/aws-cdk-lib/.eslintrc.js
  packages/aws-cdk-lib/aws-kinesis/lib/resource-policy.ts
  packages/aws-cdk-lib/aws-kinesis/lib/stream.ts
Labels: p2, pr-linter/exempt-readme, pr-linter/exempt-test, pr-linter/exempt-integ-test, distinguished-contributor, pr-linter/exemption-requested

#33860 feat(pipes-targets-alpha): support Amazon Data Firehose target
  packages/@aws-cdk/aws-pipes-targets-alpha/README.md
  packages/@aws-cdk/aws-pipes-targets-alpha/lib/firehose.ts
  packages/@aws-cdk/aws-pipes-targets-alpha/lib/index.ts
  packages/@aws-cdk/aws-pipes-targets-alpha/rosetta/default.ts-fixture
  packages/@aws-cdk/aws-pipes-targets-alpha/test/firehose.test.ts
  packages/@aws-cdk/aws-pipes-targets-alpha/test/integ.firehose.js.snapshot/asset.44e9c4d7a5d3fd2d677e1a7e416b2b56f6b0104bd5eff9cac5557b4c65a9dc61/index.js
  packages/@aws-cdk/aws-pipes-targets-alpha/test/integ.firehose.js.snapshot/asset.97484721f29e34bf38d7a459804dd2d2a8dea6f8c27d7531e215bf4274fbc895.bundle/index.js
  packages/@aws-cdk/aws-pipes-targets-alpha/test/integ.firehose.js.snapshot/aws-cdk-pipes-targets-firehose.assets.json
  packages/@aws-cdk/aws-pipes-targets-alpha/test/integ.firehose.js.snapshot/aws-cdk-pipes-targets-firehose.template.json
  packages/@aws-cdk/aws-pipes-targets-alpha/test/integ.firehose.js.snapshot/cdk.out
  packages/@aws-cdk/aws-pipes-targets-alpha/test/integ.firehose.js.snapshot/integ.json
  packages/@aws-cdk/aws-pipes-targets-alpha/test/integ.firehose.js.snapshot/integtestpipetargetfirehoseDefaultTestDeployAssert84E7EC09.assets.json
  packages/@aws-cdk/aws-pipes-targets-alpha/test/integ.firehose.js.snapshot/integtestpipetargetfirehoseDefaultTestDeployAssert84E7EC09.template.json
  packages/@aws-cdk/aws-pipes-targets-alpha/test/integ.firehose.js.snapshot/manifest.json
  packages/@aws-cdk/aws-pipes-targets-alpha/test/integ.firehose.js.snapshot/tree.json
  packages/@aws-cdk/aws-pipes-targets-alpha/test/integ.firehose.ts
Labels: p2, star-contributor, pr/needs-maintainer-review

#34041 fix(efs): support imported subnet
  packages/@aws-cdk-testing/framework-integ/test/aws-efs/test/integ.efs-from-imported-subnet.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-efs/test/integ.efs-from-imported-subnet.js.snapshot/efs-from-imported-subnet.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-efs/test/integ.efs-from-imported-subnet.js.snapshot/efs-from-imported-subnet.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-efs/test/integ.efs-from-imported-subnet.js.snapshot/efsfromimportedsubnettestDefaultTestDeployAssertC5BA6A6C.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-efs/test/integ.efs-from-imported-subnet.js.snapshot/efsfromimportedsubnettestDefaultTestDeployAssertC5BA6A6C.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-efs/test/integ.efs-from-imported-subnet.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-efs/test/integ.efs-from-imported-subnet.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-efs/test/integ.efs-from-imported-subnet.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-efs/test/integ.efs-from-imported-subnet.ts
  packages/aws-cdk-lib/aws-efs/lib/efs-file-system.ts
  packages/aws-cdk-lib/aws-efs/test/efs-file-system.test.ts
Labels: bug, p1, effort/medium, admired-contributor, pr/needs-maintainer-review

#34243 chore(region-template): update code reference links in region issue template
  .github/ISSUE_TEMPLATE/region.yml
Labels: p2, contribution/core

#34077 feat(eks): pass additional helm chart values to aws-load-balancer-controller
  packages/@aws-cdk-testing/framework-integ/test/aws-eks/test/integ.alb-controller.js.snapshot/aws-cdk-eks-cluster-alb-controller.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-eks/test/integ.alb-controller.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-eks/test/integ.alb-controller.ts
  packages/aws-cdk-lib/aws-eks/README.md
  packages/aws-cdk-lib/aws-eks/lib/alb-controller.ts
  packages/aws-cdk-lib/aws-eks/test/alb-controller.test.ts
Labels: p2, feature-request, effort/small, contribution/core

#34299 chore: adds new member `ykethan`
  .github/workflows/github-merit-badger.yml
  .mergify.yml
Labels: p2, beginning-contributor

#34288 chore(enum-updater): split out workflows and fix combined changes issue
  .github/workflows/enum-auto-updater.yml
  .github/workflows/enum-static-mapping-updater.yml
Labels: p2, contribution/core

#34303 chore(enum-updater): fix indentation
  .github/workflows/enum-auto-updater.yml
Labels: p2, contribution/core

#34306 chore(enum-updater): fix static mapping updater workflow name
  .github/workflows/enum-static-mapping-updater.yml
Labels: p2, contribution/core

#34295 fix(stepfunctions): containsTaskToken doesn't handle null values
  packages/aws-cdk-lib/aws-stepfunctions/lib/private/jsonata.ts
  packages/aws-cdk-lib/aws-stepfunctions/test/fields.test.ts
Labels: bug, p2, pr-linter/exempt-integ-test, beginning-contributor

#34313 chore(merge-back): 2.193.0
  CHANGELOG.v2.alpha.md
  CHANGELOG.v2.md
  packages/aws-cdk-lib/core/lib/analytics-data-source/classes.ts
  packages/aws-cdk-lib/core/lib/analytics-data-source/enums.ts
  packages/aws-cdk-lib/core/lib/analytics-data-source/enums/module-enums.json
  version.v2.json
Labels: p2, pr/needs-community-review, pr/no-squash, auto-approve

#34316 feat(events): throw `ValidationErrors` instead of untyped Errors
  packages/aws-cdk-lib/.eslintrc.js
  packages/aws-cdk-lib/aws-events/lib/api-destination.ts
  packages/aws-cdk-lib/aws-events/lib/connection.ts
  packages/aws-cdk-lib/aws-events/lib/event-bus.ts
  packages/aws-cdk-lib/aws-events/lib/event-pattern.ts
  packages/aws-cdk-lib/aws-events/lib/input.ts
  packages/aws-cdk-lib/aws-events/lib/rule.ts
  packages/aws-cdk-lib/aws-events/lib/schedule.ts
  packages/aws-cdk-lib/aws-events/lib/util.ts
Labels: p2, pr/needs-community-review, pr-linter/exempt-readme, pr-linter/exempt-test, pr-linter/exempt-integ-test, distinguished-contributor, pr-linter/exemption-requested

#34280 docs(s3): update link for s3 event notification filter
  packages/aws-cdk-lib/aws-s3/lib/bucket.ts
Labels: p2, effort/small, pr/needs-community-review, beginning-contributor
