Repository aws/aws-cdk, pull requests merged in 2025-01, with the labels that each got.

#32676 feat(cli): support CloudFormation simplified resource import
  packages/@aws-cdk-testing/cli-integ/tests/cli-integ-tests/cli.integtest.ts
  packages/aws-cdk/README.md
  packages/aws-cdk/lib/api/deploy-stack.ts
  packages/aws-cdk/lib/cli-arguments.ts
  packages/aws-cdk/lib/cli.ts
  packages/aws-cdk/lib/config.ts
  packages/aws-cdk/lib/parse-command-line-arguments.ts
  packages/aws-cdk/test/api/deploy-stack.test.ts
Labels: p1, feature-request, effort/medium, contribution/core, pr-linter/exempt-integ-test, pr-linter/cli-integ-tested

#32704 fix(cli): outdated dependency on `@aws-cdk/cloud-assembly-schema`
  packages/@aws-cdk/cx-api/package.json
  packages/@aws-cdk/integ-runner/package.json
  packages/aws-cdk-lib/package.json
  packages/aws-cdk/THIRD_PARTY_LICENSES
  packages/aws-cdk/package.json
  yarn.lock
Labels: contribution/core, pr-linter/exempt-readme, pr-linter/exempt-test, pr-linter/exempt-integ-test

#32696 chore(cli): function to turn yargs output to cliArguments
  codecov.yml
  packages/aws-cdk/jest.config.js
  packages/aws-cdk/lib/cli-arguments.ts
  packages/aws-cdk/lib/convert-to-cli-args.ts
  packages/aws-cdk/lib/parse-command-line-arguments.ts
  packages/aws-cdk/scripts/cli-args-gen.ts
  packages/aws-cdk/test/cli-arguments.test.ts
  tools/@aws-cdk/cli-args-gen/README.md
  tools/@aws-cdk/cli-args-gen/lib/cli-args-function-gen.ts
  tools/@aws-cdk/cli-args-gen/lib/cli-args-gen.ts
  tools/@aws-cdk/cli-args-gen/lib/index.ts
  tools/@aws-cdk/cli-args-gen/lib/util.ts
  tools/@aws-cdk/cli-args-gen/lib/yargs-gen.ts
  tools/@aws-cdk/cli-args-gen/lib/yargs-types.ts
  tools/@aws-cdk/cli-args-gen/test/cli-args-function-gen.test.ts
  tools/@aws-cdk/cli-args-gen/test/cli-args-gen.test.ts
Labels: p2, contribution/core, pr-linter/cli-integ-tested

#32658 chore(ec2): add missing instance types and sizes
  packages/aws-cdk-lib/aws-ec2/lib/instance-types.ts
Labels: p2, distinguished-contributor, pr/needs-maintainer-review

#32713 chore(cli): sync generated files
  packages/aws-cdk/lib/cli-arguments.ts
  packages/aws-cdk/lib/convert-to-cli-args.ts
  packages/aws-cdk/lib/parse-command-line-arguments.ts
Labels: p2, contribution/core, pr-linter/cli-integ-tested

#32729 feat(codebuild): add new environment types
  packages/aws-cdk-lib/aws-codebuild/lib/environment-type.ts
  packages/aws-cdk-lib/aws-codebuild/test/fleet.test.ts
Labels: p2, feature-request, pr-linter/exempt-readme, pr-linter/exempt-integ-test, beginning-contributor

#30911 feat(custom-resource): add serviceTimeout property for custom resources
  packages/@aws-cdk-testing/framework-integ/test/aws-cloudformation/test/integ.core-custom-resources-service-timeout.js.snapshot/asset.58b00a04670a58e0a99d0ca363cd2c6449822eb21c94bc5d3ca25a4816b69098/__entrypoint__.js
  packages/@aws-cdk-testing/framework-integ/test/aws-cloudformation/test/integ.core-custom-resources-service-timeout.js.snapshot/asset.58b00a04670a58e0a99d0ca363cd2c6449822eb21c94bc5d3ca25a4816b69098/index.js
  packages/@aws-cdk-testing/framework-integ/test/aws-cloudformation/test/integ.core-custom-resources-service-timeout.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-cloudformation/test/integ.core-custom-resources-service-timeout.js.snapshot/custom-resource-test-service-timeout.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-cloudformation/test/integ.core-custom-resources-service-timeout.js.snapshot/custom-resource-test-service-timeout.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-cloudformation/test/integ.core-custom-resources-service-timeout.js.snapshot/customresourcetestservicetimeoutintegtestDefaultTestDeployAssert8F844874.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-cloudformation/test/integ.core-custom-resources-service-timeout.js.snapshot/customresourcetestservicetimeoutintegtestDefaultTestDeployAssert8F844874.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-cloudformation/test/integ.core-custom-resources-service-timeout.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-cloudformation/test/integ.core-custom-resources-service-timeout.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-cloudformation/test/integ.core-custom-resources-service-timeout.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-cloudformation/test/integ.core-custom-resources-service-timeout.ts
  packages/@aws-cdk-testing/framework-integ/test/custom-resources/test/aws-custom-resource/integ.aws-custom-resource-service-timeout.js.snapshot/CreateParameterServiceTimeoutStack.assets.json
  packages/@aws-cdk-testing/framework-integ/test/custom-resources/test/aws-custom-resource/integ.aws-custom-resource-service-timeout.js.snapshot/CreateParameterServiceTimeoutStack.template.json
  packages/@aws-cdk-testing/framework-integ/test/custom-resources/test/aws-custom-resource/integ.aws-custom-resource-service-timeout.js.snapshot/GetParameterServiceTimeoutStack.assets.json
  packages/@aws-cdk-testing/framework-integ/test/custom-resources/test/aws-custom-resource/integ.aws-custom-resource-service-timeout.js.snapshot/GetParameterServiceTimeoutStack.template.json
  packages/@aws-cdk-testing/framework-integ/test/custom-resources/test/aws-custom-resource/integ.aws-custom-resource-service-timeout.js.snapshot/asset.9e8936ba1db43e0919ba2fc8265d50686eeaca82830c471ff8b7b0672c5970ec/index.js
  packages/@aws-cdk-testing/framework-integ/test/custom-resources/test/aws-custom-resource/integ.aws-custom-resource-service-timeout.js.snapshot/awscdkcustomresourcesservicetimeoutintegtestDefaultTestDeployAssert593A6038.assets.json
  packages/@aws-cdk-testing/framework-integ/test/custom-resources/test/aws-custom-resource/integ.aws-custom-resource-service-timeout.js.snapshot/awscdkcustomresourcesservicetimeoutintegtestDefaultTestDeployAssert593A6038.template.json
  packages/@aws-cdk-testing/framework-integ/test/custom-resources/test/aws-custom-resource/integ.aws-custom-resource-service-timeout.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/custom-resources/test/aws-custom-resource/integ.aws-custom-resource-service-timeout.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/custom-resources/test/aws-custom-resource/integ.aws-custom-resource-service-timeout.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/custom-resources/test/aws-custom-resource/integ.aws-custom-resource-service-timeout.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/custom-resources/test/aws-custom-resource/integ.aws-custom-resource-service-timeout.ts
  packages/aws-cdk-lib/core/README.md
  packages/aws-cdk-lib/core/lib/custom-resource.ts
  packages/aws-cdk-lib/core/test/custom-resource.test.ts
  packages/aws-cdk-lib/custom-resources/README.md
  packages/aws-cdk-lib/custom-resources/lib/aws-custom-resource/aws-custom-resource.ts
  packages/aws-cdk-lib/custom-resources/test/aws-custom-resource/aws-custom-resource.test.ts
Labels: p1, feature-request, effort/medium, star-contributor

#32734 chore(release): 2.174.0
  CHANGELOG.v2.md
  packages/@aws-cdk-testing/framework-integ/test/aws-cloudformation/test/integ.core-custom-resources-service-timeout.js.snapshot/asset.58b00a04670a58e0a99d0ca363cd2c6449822eb21c94bc5d3ca25a4816b69098/__entrypoint__.js
  packages/@aws-cdk-testing/framework-integ/test/aws-cloudformation/test/integ.core-custom-resources-service-timeout.js.snapshot/asset.58b00a04670a58e0a99d0ca363cd2c6449822eb21c94bc5d3ca25a4816b69098/index.js
  packages/@aws-cdk-testing/framework-integ/test/aws-cloudformation/test/integ.core-custom-resources-service-timeout.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-cloudformation/test/integ.core-custom-resources-service-timeout.js.snapshot/custom-resource-test-service-timeout.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-cloudformation/test/integ.core-custom-resources-service-timeout.js.snapshot/custom-resource-test-service-timeout.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-cloudformation/test/integ.core-custom-resources-service-timeout.js.snapshot/customresourcetestservicetimeoutintegtestDefaultTestDeployAssert8F844874.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-cloudformation/test/integ.core-custom-resources-service-timeout.js.snapshot/customresourcetestservicetimeoutintegtestDefaultTestDeployAssert8F844874.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-cloudformation/test/integ.core-custom-resources-service-timeout.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-cloudformation/test/integ.core-custom-resources-service-timeout.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-cloudformation/test/integ.core-custom-resources-service-timeout.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-cloudformation/test/integ.core-custom-resources-service-timeout.ts
  packages/@aws-cdk-testing/framework-integ/test/custom-resources/test/aws-custom-resource/integ.aws-custom-resource-service-timeout.js.snapshot/CreateParameterServiceTimeoutStack.assets.json
  packages/@aws-cdk-testing/framework-integ/test/custom-resources/test/aws-custom-resource/integ.aws-custom-resource-service-timeout.js.snapshot/CreateParameterServiceTimeoutStack.template.json
  packages/@aws-cdk-testing/framework-integ/test/custom-resources/test/aws-custom-resource/integ.aws-custom-resource-service-timeout.js.snapshot/GetParameterServiceTimeoutStack.assets.json
  packages/@aws-cdk-testing/framework-integ/test/custom-resources/test/aws-custom-resource/integ.aws-custom-resource-service-timeout.js.snapshot/GetParameterServiceTimeoutStack.template.json
  packages/@aws-cdk-testing/framework-integ/test/custom-resources/test/aws-custom-resource/integ.aws-custom-resource-service-timeout.js.snapshot/asset.9e8936ba1db43e0919ba2fc8265d50686eeaca82830c471ff8b7b0672c5970ec/index.js
  packages/@aws-cdk-testing/framework-integ/test/custom-resources/test/aws-custom-resource/integ.aws-custom-resource-service-timeout.js.snapshot/awscdkcustomresourcesservicetimeoutintegtestDefaultTestDeployAssert593A6038.assets.json
  packages/@aws-cdk-testing/framework-integ/test/custom-resources/test/aws-custom-resource/integ.aws-custom-resource-service-timeout.js.snapshot/awscdkcustomresourcesservicetimeoutintegtestDefaultTestDeployAssert593A6038.template.json
  packages/@aws-cdk-testing/framework-integ/test/custom-resources/test/aws-custom-resource/integ.aws-custom-resource-service-timeout.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/custom-resources/test/aws-custom-resource/integ.aws-custom-resource-service-timeout.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/custom-resources/test/aws-custom-resource/integ.aws-custom-resource-service-timeout.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/custom-resources/test/aws-custom-resource/integ.aws-custom-resource-service-timeout.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/custom-resources/test/aws-custom-resource/integ.aws-custom-resource-service-timeout.ts
  packages/aws-cdk-lib/aws-codebuild/lib/environment-type.ts
  packages/aws-cdk-lib/aws-codebuild/test/fleet.test.ts
  packages/aws-cdk-lib/core/README.md
  packages/aws-cdk-lib/core/lib/custom-resource.ts
  packages/aws-cdk-lib/core/test/custom-resource.test.ts
  packages/aws-cdk-lib/custom-resources/README.md
  packages/aws-cdk-lib/custom-resources/lib/aws-custom-resource/aws-custom-resource.ts
  packages/aws-cdk-lib/custom-resources/test/aws-custom-resource/aws-custom-resource.test.ts
Labels: p2, pr/no-squash, auto-approve

#32699 chore: update Contributors File
  CONTRIBUTORS.md
Labels: p2, pr/needs-community-review, auto-approve

#32736 chore(merge-back): 2.174.0
  CHANGELOG.v2.alpha.md
  CHANGELOG.v2.md
  packages/aws-cdk-lib/cx-api/FEATURE_FLAGS.md
  packages/aws-cdk-lib/cx-api/lib/features.ts
  version.v2.json
Labels: p2, pr/needs-community-review, pr/no-squash, auto-approve

#32718 chore(cli): model positional arguments in CliArguments
  packages/aws-cdk/lib/cli-arguments.ts
  packages/aws-cdk/lib/convert-to-cli-args.ts
  packages/aws-cdk/test/cli-arguments.test.ts
  tools/@aws-cdk/cli-args-gen/lib/cli-args-function-gen.ts
  tools/@aws-cdk/cli-args-gen/lib/cli-args-gen.ts
  tools/@aws-cdk/cli-args-gen/test/cli-args-function-gen.test.ts
  tools/@aws-cdk/cli-args-gen/test/cli-args-gen.test.ts
Labels: p2, contribution/core, pr-linter/cli-integ-tested

#32681 feat(kms): add sign and verify related grant methods
  packages/@aws-cdk-testing/framework-integ/test/aws-kms/test/integ.key-grants.js.snapshot/KeyGrantsIntegTestDefaultTestDeployAssert49AF830A.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-kms/test/integ.key-grants.js.snapshot/KeyGrantsIntegTestDefaultTestDeployAssert49AF830A.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-kms/test/integ.key-grants.js.snapshot/aws-cdk-kms-grants.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-kms/test/integ.key-grants.js.snapshot/aws-cdk-kms-grants.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-kms/test/integ.key-grants.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-kms/test/integ.key-grants.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-kms/test/integ.key-grants.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-kms/test/integ.key-grants.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-kms/test/integ.key-grants.ts
  packages/aws-cdk-lib/aws-kms/README.md
  packages/aws-cdk-lib/aws-kms/lib/alias.ts
  packages/aws-cdk-lib/aws-kms/lib/key.ts
  packages/aws-cdk-lib/aws-kms/lib/private/perms.ts
  packages/aws-cdk-lib/aws-kms/test/alias.test.ts
  packages/aws-cdk-lib/aws-kms/test/key.test.ts
Labels: p2, feature-request, effort/small, repeat-contributor, pr/needs-cli-test-run

#32748 chore: codecov includes files outside of configured packages
  codecov.yml
Labels: p2, contribution/core

#32749 fix(cli): cannot set environment variable `CI=false`
  packages/aws-cdk/lib/util/yargs-helpers.ts
  packages/aws-cdk/test/util/yargs-helpers.test.ts
Labels: p2, contribution/core, pr-linter/exempt-integ-test, pr-linter/cli-integ-tested

#32721 docs(elasticloadbalancingv2): fix typos
  packages/aws-cdk-lib/aws-elasticloadbalancingv2/README.md
Labels: p2, valued-contributor

#32750 fix(integ-runner): `ENOENT` no such file or directory 'recommended-feature-flags.json'
  packages/@aws-cdk/integ-runner/.gitignore
  packages/@aws-cdk/integ-runner/lib/runner/runner-base.ts
Labels: p2, contribution/core, pr-linter/exempt-test, pr-linter/exempt-integ-test

#32661 feat(s3objectlambda): open s3 access point arn
  packages/@aws-cdk/aws-s3objectlambda-alpha/README.md
  packages/@aws-cdk/aws-s3objectlambda-alpha/lib/access-point.ts
  packages/@aws-cdk/aws-s3objectlambda-alpha/test/s3objectlambda.test.ts
Labels: p2, feature-request, effort/small, pr-linter/exempt-integ-test, beginning-contributor, pr-linter/exemption-requested

#32710 chore(cli): remove legacy compat code to support version reporting in v1 apps
  packages/aws-cdk/lib/api/cxapp/cloud-executable.ts
  packages/aws-cdk/test/api/cloud-executable.test.ts
Labels: p2, contribution/core, pr-linter/cli-integ-tested

#32666 fix(cli): requiresRefresh function does not respect null
  packages/aws-cdk/lib/api/aws-auth/provider-caching.ts
Labels: p2, contribution/core, pr-linter/exempt-test, pr-linter/exempt-integ-test, pr-linter/cli-integ-tested

#32636 feat(cli): warn of non-existent stacks in `cdk destroy`
  packages/@aws-cdk-testing/cli-integ/tests/cli-integ-tests/cli.integtest.ts
  packages/aws-cdk/lib/cdk-toolkit.ts
  packages/aws-cdk/test/cdk-toolkit.test.ts
Labels: bug, p2, effort/medium, pr-linter/exempt-readme, pr-linter/exempt-integ-test, distinguished-contributor, pr-linter/cli-integ-tested, pr-linter/exemption-requested

#32768 feat: update L1 CloudFormation resource definitions
  packages/@aws-cdk/cloudformation-diff/package.json
  packages/@aws-cdk/integ-runner/package.json
  packages/aws-cdk-lib/package.json
  tools/@aws-cdk/spec2cdk/package.json
  yarn.lock
Labels: p2, dependencies, contribution/core, pr-linter/exempt-readme, pr-linter/exempt-test, auto-approve, pr-linter/exempt-integ-test, pr/needs-maintainer-review

#32773 chore(release): v2.174.1
  CHANGELOG.v2.alpha.md
  CHANGELOG.v2.md
  packages/@aws-cdk/cloudformation-diff/package.json
  packages/@aws-cdk/integ-runner/package.json
  packages/aws-cdk-lib/package.json
  tools/@aws-cdk/spec2cdk/package.json
  version.v2.json
  yarn.lock
Labels: p2, contribution/core, pr/no-squash

#32758 chore(cli): cli arguments with "count: true" are generated as number types
  packages/aws-cdk/lib/cli-arguments.ts
  tools/@aws-cdk/cli-args-gen/lib/cli-args-gen.ts
  tools/@aws-cdk/cli-args-gen/test/cli-args-gen.test.ts
Labels: p2, contribution/core, pr-linter/cli-integ-tested

#32778 chore(merge-back): 2.174.1
  CHANGELOG.v2.alpha.md
  CHANGELOG.v2.md
  version.v2.json
Labels: p2, pr/needs-community-review, pr/no-squash, auto-approve

#32759 chore: add ianhou to mergify and GH merit badger configs
  .github/workflows/github-merit-badger.yml
  .mergify.yml
Labels: p2, beginning-contributor

#32598 feat(ecs): enable fault injection flag
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs/test/integ.task-definition-enable-fault-injection.js.snapshot/TaskDefinitionEnableFaultInjectionDefaultTestDeployAssert16EB808C.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs/test/integ.task-definition-enable-fault-injection.js.snapshot/TaskDefinitionEnableFaultInjectionDefaultTestDeployAssert16EB808C.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs/test/integ.task-definition-enable-fault-injection.js.snapshot/aws-ecs-task-definition-enable-fault-injection.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs/test/integ.task-definition-enable-fault-injection.js.snapshot/aws-ecs-task-definition-enable-fault-injection.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs/test/integ.task-definition-enable-fault-injection.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs/test/integ.task-definition-enable-fault-injection.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs/test/integ.task-definition-enable-fault-injection.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs/test/integ.task-definition-enable-fault-injection.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs/test/integ.task-definition-enable-fault-injection.ts
  packages/aws-cdk-lib/aws-ecs/README.md
  packages/aws-cdk-lib/aws-ecs/lib/base/task-definition.ts
  packages/aws-cdk-lib/aws-ecs/test/task-definition.test.ts
Labels: p2, distinguished-contributor

#32771 fix(apprunner): the Service class does not implement IService
  packages/@aws-cdk/aws-apprunner-alpha/lib/service.ts
Labels: bug, p2, effort/small, pr-linter/exempt-test, pr-linter/exempt-integ-test, distinguished-contributor

#32763 fix(ecs): outdated linux commands for `canContainersAccessInstanceRole=false` and also deprecate property
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs-patterns/test/ec2/integ.alb-ecs-service-command-entry-point.ts
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs-patterns/test/ec2/integ.application-load-balanced-ecs-service.ts
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs-patterns/test/ec2/integ.healthchecks-multiple-application-load-balanced-ecs-service.ts
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs-patterns/test/ec2/integ.healthchecks-multiple-network-load-balanced-ecs-service.ts
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs-patterns/test/ec2/integ.multiple-application-load-balanced-ecs-service-idle-timeout.ts
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs-patterns/test/ec2/integ.multiple-application-load-balanced-ecs-service.ts
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs-patterns/test/ec2/integ.network-load-balanced-ecs-service.ts
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs-patterns/test/ec2/integ.scheduled-ecs-task.ts
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs-patterns/test/ec2/integ.tls-network-load-balanced-ecs-service.ts
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs/test/ec2/integ.app-mesh-proxy-config.ts
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs/test/ec2/integ.capacity-provider-managed-draining.ts
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs/test/ec2/integ.capacity-provider.ts
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs/test/ec2/integ.clb-host-nw.ts
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs/test/ec2/integ.cloudmap-container-port.ts
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs/test/ec2/integ.default-capacity-provider.ts
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs/test/ec2/integ.deployment-alarms.ts
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs/test/ec2/integ.enable-execute-command.ts
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs/test/ec2/integ.environment-file.ts
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs/test/ec2/integ.exec-command.ts
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs/test/ec2/integ.firelens-s3-config.ts
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs/test/ec2/integ.graviton.ts
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs/test/ec2/integ.lb-awsvpc-nw.ts
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs/test/ec2/integ.lb-bridge-nw.ts
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs/test/ec2/integ.placement-constraint-default-empty.ts
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs/test/ec2/integ.placement-strategies.ts
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs/test/ec2/integ.pseudo-terminal.ts
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs/test/ec2/integ.sd-awsvpc-nw.ts
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs/test/ec2/integ.sd-bridge-nw.ts
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs/test/ec2/integ.spot-drain.ts
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs/test/ec2/integ.swap-parameters.ts
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs/test/ec2/integ.task-definition-placement-constraints.ts
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs/test/integ.cluster-amazonlinux2-neuron-ami.ts
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs/test/integ.cluster-imported.ts
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs/test/integ.cluster-windows-server-ami.ts
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs/test/integ.cluster.amazonlinux2023-ami.js.snapshot/ClusterAL2023DefaultTestDeployAssert19111415.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs/test/integ.cluster.amazonlinux2023-ami.js.snapshot/ClusterAL2023DefaultTestDeployAssert19111415.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs/test/integ.cluster.amazonlinux2023-ami.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs/test/integ.cluster.amazonlinux2023-ami.js.snapshot/integ-ecs-al2023-ami.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs/test/integ.cluster.amazonlinux2023-ami.js.snapshot/integ-ecs-al2023-ami.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs/test/integ.cluster.amazonlinux2023-ami.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs/test/integ.cluster.amazonlinux2023-ami.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs/test/integ.cluster.amazonlinux2023-ami.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs/test/integ.cluster.amazonlinux2023-ami.ts
  packages/@aws-cdk-testing/framework-integ/test/aws-events-targets/test/ecs/integ.event-ec2-task.ts
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/ecs/integ.ec2-run-task-ref-definition.ts
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/ecs/integ.ec2-run-task.ts
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/ecs/integ.ec2-task.ts
  packages/aws-cdk-lib/aws-ecs/lib/cluster.ts
  packages/aws-cdk-lib/aws-ecs/test/cluster.test.ts
  packages/aws-cdk-lib/cx-api/FEATURE_FLAGS.md
  packages/aws-cdk-lib/cx-api/README.md
  packages/aws-cdk-lib/cx-api/build-tools/flag-report.ts
  packages/aws-cdk-lib/cx-api/lib/features.ts
  packages/aws-cdk-lib/cx-api/lib/private/flag-modeling.ts
Labels: bug, p1, effort/medium, contribution/core

#32325 fix(cloudwatch): render region and accountId when directly set on metrics
  packages/@aws-cdk-testing/framework-integ/test/aws-cloudwatch/test/integ.dashboard-and-widget-with-start-and-end.js.snapshot/DashboardAndWidgetWithStartAndEnd.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-cloudwatch/test/integ.dashboard-and-widget-with-start-and-end.js.snapshot/DashboardAndWidgetWithStartAndEnd.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-cloudwatch/test/integ.dashboard-and-widget-with-start-and-end.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-cloudwatch/test/integ.dashboard-and-widget-with-start-and-end.js.snapshot/cdkintegdashboardandwidgetwithstartandendDefaultTestDeployAssert4D8483F4.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-cloudwatch/test/integ.dashboard-and-widget-with-start-and-end.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-cloudwatch/test/integ.dashboard-and-widget-with-start-and-end.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-cloudwatch/test/integ.dashboard-and-widget-with-start-and-end.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-cloudwatch/test/integ.dashboard-and-widget-with-start-and-end.ts
  packages/aws-cdk-lib/aws-cloudwatch/lib/metric-types.ts
  packages/aws-cdk-lib/aws-cloudwatch/lib/metric.ts
  packages/aws-cdk-lib/aws-cloudwatch/lib/private/make-enumerable.ts
  packages/aws-cdk-lib/aws-cloudwatch/lib/private/rendering.ts
  packages/aws-cdk-lib/aws-cloudwatch/test/cross-environment.test.ts
  packages/aws-cdk-lib/aws-cloudwatch/test/metrics.test.ts
Labels: bug, p2, pr/needs-community-review, effort/medium, beginning-contributor

#32766 chore(cx-api): only include v1 feature flags in the `Flags with a different default in v2` section
  packages/aws-cdk-lib/cx-api/FEATURE_FLAGS.md
  packages/aws-cdk-lib/cx-api/build-tools/flag-report.ts
Labels: p2, contribution/core

#32692 chore(eks-v2-alpha): remove nested stack
  packages/@aws-cdk/aws-eks-v2-alpha/lib/kubectl-provider.ts
  packages/@aws-cdk/aws-eks-v2-alpha/test/cluster.test.ts
  packages/@aws-cdk/aws-eks-v2-alpha/test/k8s-object-value.test.ts
  packages/@aws-cdk/aws-eks-v2-alpha/test/k8s-patch.test.ts
  packages/@aws-cdk/aws-eks-v2-alpha/test/service-account.test.ts
Labels: p2, contribution/core

#32788 chore(tools): update lambda runtime tests github action
  .github/workflows/lambda-runtime-tests.yml
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-nodejs/test/integ.nodejs.build.images.js.snapshot/LambdaNodeJsLatestIntegDefaultTestDeployAssertD40B5C28.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-nodejs/test/integ.nodejs.build.images.js.snapshot/LambdaNodeJsLatestIntegDefaultTestDeployAssertD40B5C28.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-nodejs/test/integ.nodejs.build.images.js.snapshot/asset.bfcf4228d6660f50e81f19efdb64c6388dda6796296eb239decdff1dbc2f4981.bundle/index.js
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-nodejs/test/integ.nodejs.build.images.js.snapshot/cdk-integ-lambda-nodejs-latest.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-nodejs/test/integ.nodejs.build.images.js.snapshot/cdk-integ-lambda-nodejs-latest.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-nodejs/test/integ.nodejs.build.images.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-nodejs/test/integ.nodejs.build.images.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-nodejs/test/integ.nodejs.build.images.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-nodejs/test/integ.nodejs.build.images.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-nodejs/test/integ.nodejs.build.images.ts
  packages/@aws-cdk/aws-lambda-go-alpha/test/integ.function.provided.runtimes.js.snapshot/asset.bfcf4228d6660f50e81f19efdb64c6388dda6796296eb239decdff1dbc2f4981.bundle/index.js
  packages/@aws-cdk/aws-lambda-go-alpha/test/integ.function.provided.runtimes.js.snapshot/cdk-integ-lambda-golang-provided-al2023.assets.json
  packages/@aws-cdk/aws-lambda-go-alpha/test/integ.function.provided.runtimes.js.snapshot/cdk-integ-lambda-golang-provided-al2023.template.json
  packages/@aws-cdk/aws-lambda-go-alpha/test/integ.function.provided.runtimes.js.snapshot/cdk.out
  packages/@aws-cdk/aws-lambda-go-alpha/test/integ.function.provided.runtimes.js.snapshot/integ.json
  packages/@aws-cdk/aws-lambda-go-alpha/test/integ.function.provided.runtimes.js.snapshot/lambdagoruntimeDefaultTestDeployAssert366012A1.assets.json
  packages/@aws-cdk/aws-lambda-go-alpha/test/integ.function.provided.runtimes.js.snapshot/lambdagoruntimeDefaultTestDeployAssert366012A1.template.json
  packages/@aws-cdk/aws-lambda-go-alpha/test/integ.function.provided.runtimes.js.snapshot/manifest.json
  packages/@aws-cdk/aws-lambda-go-alpha/test/integ.function.provided.runtimes.js.snapshot/tree.json
  packages/@aws-cdk/aws-lambda-go-alpha/test/integ.function.provided.runtimes.ts
  packages/@aws-cdk/aws-lambda-python-alpha/test/integ.python.build.images.js.snapshot/asset.bfcf4228d6660f50e81f19efdb64c6388dda6796296eb239decdff1dbc2f4981.bundle/index.js
  packages/@aws-cdk/aws-lambda-python-alpha/test/integ.python.build.images.js.snapshot/cdk.out
  packages/@aws-cdk/aws-lambda-python-alpha/test/integ.python.build.images.js.snapshot/integ-lambda-python-test-build-images.assets.json
  packages/@aws-cdk/aws-lambda-python-alpha/test/integ.python.build.images.js.snapshot/integ-lambda-python-test-build-images.template.json
  packages/@aws-cdk/aws-lambda-python-alpha/test/integ.python.build.images.js.snapshot/integ.json
  packages/@aws-cdk/aws-lambda-python-alpha/test/integ.python.build.images.js.snapshot/lambdapythonbuildimagesDefaultTestDeployAssertB7623923.assets.json
  packages/@aws-cdk/aws-lambda-python-alpha/test/integ.python.build.images.js.snapshot/lambdapythonbuildimagesDefaultTestDeployAssertB7623923.template.json
  packages/@aws-cdk/aws-lambda-python-alpha/test/integ.python.build.images.js.snapshot/manifest.json
  packages/@aws-cdk/aws-lambda-python-alpha/test/integ.python.build.images.js.snapshot/tree.json
  packages/@aws-cdk/aws-lambda-python-alpha/test/integ.python.build.images.ts
Labels: p2, contribution/core

#32806 chore(cli): aliased commands can be converted to cli args
  packages/aws-cdk/lib/convert-to-cli-args.ts
  packages/aws-cdk/lib/settings.ts
  tools/@aws-cdk/cli-args-gen/lib/cli-args-function-gen.ts
  tools/@aws-cdk/cli-args-gen/test/cli-args-function-gen.test.ts
Labels: p2, contribution/core, pr-linter/cli-integ-tested

#32803 chore(cli): generate conversion from cdk.json to cli arguments
  packages/aws-cdk/lib/cli-arguments.ts
  packages/aws-cdk/lib/convert-to-cli-args.ts
  packages/aws-cdk/test/cli-arguments.test.ts
  tools/@aws-cdk/cli-args-gen/lib/cli-args-function-gen.ts
  tools/@aws-cdk/cli-args-gen/lib/cli-args-gen.ts
  tools/@aws-cdk/cli-args-gen/test/cli-args-function-gen.test.ts
  tools/@aws-cdk/cli-args-gen/test/cli-args-gen.test.ts
Labels: p2, contribution/core, pr-linter/cli-integ-tested

#32737 feat(appconfig): environment deletion protection
  packages/@aws-cdk-testing/framework-integ/test/aws-appconfig/test/integ.environment.js.snapshot/appconfigenvironmentDefaultTestDeployAssert75BD28E7.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-appconfig/test/integ.environment.js.snapshot/aws-appconfig-environment.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-appconfig/test/integ.environment.js.snapshot/aws-appconfig-environment.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-appconfig/test/integ.environment.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-appconfig/test/integ.environment.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-appconfig/test/integ.environment.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-appconfig/test/integ.environment.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-appconfig/test/integ.environment.ts
  packages/aws-cdk-lib/aws-appconfig/README.md
  packages/aws-cdk-lib/aws-appconfig/lib/environment.ts
  packages/aws-cdk-lib/aws-appconfig/lib/index.ts
  packages/aws-cdk-lib/aws-appconfig/lib/util.ts
  packages/aws-cdk-lib/aws-appconfig/test/environment.test.ts
Labels: p2, distinguished-contributor

#32826 chore(merge-back): 2.175.0
  CHANGELOG.v2.alpha.md
  CHANGELOG.v2.md
  packages/aws-cdk-lib/cx-api/FEATURE_FLAGS.md
  packages/aws-cdk-lib/cx-api/lib/features.ts
  packages/aws-cdk-lib/recommended-feature-flags.json
  version.v2.json
Labels: p2, pr/needs-community-review, pr/no-squash, auto-approve

#32765 fix(elasticloadbalancingv2): open, dual-stack-without-public-ipv4 ALB does not allow IPv6 inbound traffic (under feature flag)
  packages/@aws-cdk-testing/framework-integ/test/aws-elasticloadbalancingv2/test/integ.alb.dualstack-without-public-ipv4.js.snapshot/AlbDualstackWithoutPublicIpv4DefaultTestDeployAssertFA6F90DD.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-elasticloadbalancingv2/test/integ.alb.dualstack-without-public-ipv4.js.snapshot/aws-cdk-elbv2-integ-dualstack-without-public-ipv4.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-elasticloadbalancingv2/test/integ.alb.dualstack-without-public-ipv4.js.snapshot/aws-cdk-elbv2-integ-dualstack-without-public-ipv4.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-elasticloadbalancingv2/test/integ.alb.dualstack-without-public-ipv4.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-elasticloadbalancingv2/test/integ.alb.dualstack-without-public-ipv4.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-elasticloadbalancingv2/test/integ.alb.dualstack-without-public-ipv4.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-elasticloadbalancingv2/test/integ.alb.dualstack-without-public-ipv4.js.snapshot/tree.json
  packages/aws-cdk-lib/aws-elasticloadbalancingv2/README.md
  packages/aws-cdk-lib/aws-elasticloadbalancingv2/lib/alb/application-listener.ts
  packages/aws-cdk-lib/aws-elasticloadbalancingv2/lib/alb/application-load-balancer.ts
  packages/aws-cdk-lib/aws-elasticloadbalancingv2/test/alb/listener.test.ts
  packages/aws-cdk-lib/cx-api/FEATURE_FLAGS.md
  packages/aws-cdk-lib/cx-api/README.md
  packages/aws-cdk-lib/cx-api/lib/features.ts
  packages/aws-cdk-lib/cx-api/test/features.test.ts
Labels: bug, p2, effort/small, contribution/core, pr-linter/exempt-integ-test

#32821 chore(cli): rename cli-args-gen into user-input-gen
  aws-cdk.code-workspace
  lerna.json
  package.json
  packages/aws-cdk/CONTRIBUTING.md
  packages/aws-cdk/jest.config.js
  packages/aws-cdk/lib/config.ts
  packages/aws-cdk/lib/convert-to-user-input.ts
  packages/aws-cdk/lib/user-input.ts
  packages/aws-cdk/package.json
  packages/aws-cdk/scripts/cli-args-gen
  packages/aws-cdk/scripts/cli-args-gen.ts
  packages/aws-cdk/scripts/user-input-gen
  packages/aws-cdk/scripts/user-input-gen.ts
  packages/aws-cdk/test/cli-arguments.test.ts
  tools/@aws-cdk/cli-args-gen/lib/index.ts
  tools/@aws-cdk/user-input-gen/.eslintrc.js
  tools/@aws-cdk/user-input-gen/.gitignore
  tools/@aws-cdk/user-input-gen/.npmignore
  tools/@aws-cdk/user-input-gen/LICENSE
  tools/@aws-cdk/user-input-gen/NOTICE
  tools/@aws-cdk/user-input-gen/README.md
  tools/@aws-cdk/user-input-gen/jest.config.js
  tools/@aws-cdk/user-input-gen/lib/convert-to-user-input-gen.ts
  tools/@aws-cdk/user-input-gen/lib/index.ts
  tools/@aws-cdk/user-input-gen/lib/user-input-gen.ts
  tools/@aws-cdk/user-input-gen/lib/util.ts
  tools/@aws-cdk/user-input-gen/lib/yargs-gen.ts
  tools/@aws-cdk/user-input-gen/lib/yargs-types.ts
  tools/@aws-cdk/user-input-gen/package.json
  tools/@aws-cdk/user-input-gen/test/convert-to-user-input-gen.test.ts
  tools/@aws-cdk/user-input-gen/test/user-input-gen.test.ts
  tools/@aws-cdk/user-input-gen/test/yargs-gen.test.ts
  tools/@aws-cdk/user-input-gen/tsconfig.json
Labels: p2, contribution/core, pr-linter/cli-integ-tested

#32823 chore(cli): synth is now default command name, synthesize is alias
  packages/aws-cdk/lib/config.ts
  packages/aws-cdk/lib/convert-to-user-input.ts
  packages/aws-cdk/lib/parse-command-line-arguments.ts
  packages/aws-cdk/lib/user-input.ts
  packages/aws-cdk/test/cli-arguments.test.ts
Labels: p2, contribution/core, pr-linter/cli-integ-tested

#32822 chore(cli): rename `_` to `command` in `UserInput`
  packages/aws-cdk/lib/convert-to-user-input.ts
  packages/aws-cdk/lib/user-input.ts
  packages/aws-cdk/test/cli-arguments.test.ts
  tools/@aws-cdk/user-input-gen/lib/convert-to-user-input-gen.ts
  tools/@aws-cdk/user-input-gen/lib/user-input-gen.ts
  tools/@aws-cdk/user-input-gen/test/convert-to-user-input-gen.test.ts
  tools/@aws-cdk/user-input-gen/test/user-input-gen.test.ts
Labels: p2, contribution/core, pr-linter/cli-integ-tested

#32829 chore(lambda): fix snapstart warning grammar issue
  packages/aws-cdk-lib/aws-lambda/lib/function.ts
Labels: p2, effort/small, contribution/core

#32825 fix(rds): clusterScailabilityType is spelled wrong and should be clusterScalabilityType
  packages/aws-cdk-lib/aws-rds/README.md
  packages/aws-cdk-lib/aws-rds/lib/cluster.ts
  packages/aws-cdk-lib/aws-rds/test/cluster.test.ts
Labels: bug, p2, effort/small, contribution/core, pr-linter/exempt-integ-test

#32800 docs(ec2-alpha): fix typos
  packages/@aws-cdk/aws-ec2-alpha/README.md
Labels: p2, valued-contributor

#32839 fix(cli): "no stack found in the main cloud assembly"
  packages/@aws-cdk-testing/cli-integ/tests/cli-integ-tests/cli.integtest.ts
  packages/aws-cdk/lib/cdk-toolkit.ts
  packages/aws-cdk/test/cdk-toolkit.test.ts
Labels: bug, p0, effort/medium, contribution/core, pr-linter/exempt-test, pr-linter/exempt-integ-test, pr-linter/cli-integ-tested

#32842 chore(release): v2.175.1
  CHANGELOG.v2.alpha.md
  CHANGELOG.v2.md
  packages/@aws-cdk-testing/cli-integ/tests/cli-integ-tests/cli.integtest.ts
  packages/aws-cdk/lib/cdk-toolkit.ts
  packages/aws-cdk/test/cdk-toolkit.test.ts
  version.v2.json
Labels: p2, contribution/core, pr/no-squash, pr-linter/cli-integ-tested

#32843 chore: remove duplicate entry in feature flag
  packages/aws-cdk-lib/cx-api/FEATURE_FLAGS.md
Labels: p2, contribution/core

#32844 chore(iot1click): remove the shut down service aws-iot1click
  .github/workflows/issue-label-assign.yml
  deprecated_apis.txt
  packages/aws-cdk-lib/aws-iot1click/.jsiirc.json
  packages/aws-cdk-lib/aws-iot1click/README.md
  packages/aws-cdk-lib/aws-iot1click/index.ts
  packages/aws-cdk-lib/aws-iot1click/lib/index.ts
  packages/aws-cdk-lib/custom-resources/lib/helpers-internal/sdk-v2-to-v3.json
  packages/aws-cdk-lib/custom-resources/lib/helpers-internal/sdk-v3-metadata.json
  packages/aws-cdk-lib/index.ts
  packages/aws-cdk-lib/package.json
  packages/aws-cdk-lib/scripts/gen.ts
  packages/aws-cdk-lib/scripts/scope-map.json
  tools/@aws-cdk/pkglint/lib/aws-service-official-names.json
  tools/@aws-cdk/spec2cdk/lib/cfn2ts/index.ts
  tools/@aws-cdk/spec2cdk/lib/cfn2ts/types.ts
Labels: p2, contribution/core, pr/needs-maintainer-review

#32847 feat: update L1 CloudFormation resource definitions
  packages/@aws-cdk/cloudformation-diff/package.json
  packages/@aws-cdk/integ-runner/package.json
  packages/aws-cdk-lib/package.json
  tools/@aws-cdk/spec2cdk/package.json
  yarn.lock
Labels: p2, dependencies, contribution/core, pr-linter/exempt-readme, pr-linter/exempt-test, auto-approve, pr-linter/exempt-integ-test

#32860 chore(docs): fix typos
  packages/@aws-cdk/custom-resource-handlers/lib/aws-eks/kubectl-handler/get/__init__.py
Labels: p2, beginning-contributor

#32845 chore(merge-back): 2.175.1
  CHANGELOG.v2.alpha.md
  CHANGELOG.v2.md
  version.v2.json
Labels: p2, pr/no-squash, auto-approve

#32859 chore(docs): fix typos
  packages/@aws-cdk/custom-resource-handlers/lib/aws-eks/cluster-resource-handler/compareLogging.ts
Labels: p2, beginning-contributor

#32858 chore(docs): fix typos
  packages/@aws-cdk/cloudformation-diff/lib/diff/types.ts
Labels: p2, beginning-contributor

#32861 chore(docs): fix typos
  packages/aws-cdk/lib/api/logs/logs-monitor.ts
Labels: p2, beginning-contributor, pr-linter/cli-integ-tested

#32855 chore(s3objectlambda-alpha): fix typo
  packages/@aws-cdk/aws-s3objectlambda-alpha/lib/access-point.ts
Labels: p2, beginning-contributor

#32793 chore: correct comment syntax in PR template for IAM permissions
  .github/PULL_REQUEST_TEMPLATE.md
Labels: p2, distinguished-contributor

#32852 chore(dynamodb): fix typos
  packages/aws-cdk-lib/aws-dynamodb/README.md
  packages/aws-cdk-lib/aws-dynamodb/lib/table-v2.ts
  packages/aws-cdk-lib/aws-dynamodb/lib/table.ts
Labels: p2, valued-contributor

#32622 feat(ecs): enable Enhanced Observability for Container Insights
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs/test/integ.cluster-enhanced-container-insights.js.snapshot/ClusterEnhancedInsightsDefaultTestDeployAssert64FBF7AE.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs/test/integ.cluster-enhanced-container-insights.js.snapshot/ClusterEnhancedInsightsDefaultTestDeployAssert64FBF7AE.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs/test/integ.cluster-enhanced-container-insights.js.snapshot/asset.bfcf4228d6660f50e81f19efdb64c6388dda6796296eb239decdff1dbc2f4981.bundle/index.js
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs/test/integ.cluster-enhanced-container-insights.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs/test/integ.cluster-enhanced-container-insights.js.snapshot/integ-ecs-enhanced-container-insights.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs/test/integ.cluster-enhanced-container-insights.js.snapshot/integ-ecs-enhanced-container-insights.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs/test/integ.cluster-enhanced-container-insights.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs/test/integ.cluster-enhanced-container-insights.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs/test/integ.cluster-enhanced-container-insights.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs/test/integ.cluster-enhanced-container-insights.ts
  packages/aws-cdk-lib/aws-ecs/README.md
  packages/aws-cdk-lib/aws-ecs/lib/cluster.ts
  packages/aws-cdk-lib/aws-ecs/test/cluster.test.ts
Labels: p2, feature-request, effort/small, beginning-contributor

#32856 chore(servicecatalogappregistry-alpha): fix typos
  packages/@aws-cdk/aws-servicecatalogappregistry-alpha/lib/application.ts
Labels: p2, beginning-contributor

#32674 chore(prlint): fail prlinter on codecov failures, with exemption label
  tools/@aws-cdk/prlint/lint.ts
  tools/@aws-cdk/prlint/test/lint.test.ts
Labels: p2, contribution/core

#32867 revert(prlint): fail prlinter on codecov failures, with exemption label
  tools/@aws-cdk/prlint/lint.ts
  tools/@aws-cdk/prlint/test/lint.test.ts
Labels: p2, contribution/core

#32796 docs(ecs): fix incorrect rate
  packages/aws-cdk-lib/aws-ecs/README.md
Labels: p2, admired-contributor

#32863 chore(docs): fix typos
  packages/aws-cdk-lib/aws-lambda/lib/event-source-mapping.ts
Labels: p2, repeat-contributor

#32525 feat(codebuild): add new BuildImages
  packages/aws-cdk-lib/aws-codebuild/lib/linux-arm-build-image.ts
  packages/aws-cdk-lib/aws-codebuild/lib/project.ts
Labels: p2, pr-linter/exempt-readme, pr-linter/exempt-test, pr-linter/exempt-integ-test, distinguished-contributor

#32864 chore(docs): fix typos
  packages/aws-cdk-lib/aws-lambda/lib/function-base.ts
  packages/aws-cdk-lib/aws-lambda/lib/lambda-insights.ts
  packages/aws-cdk-lib/aws-lambda/lib/singleton-lambda.ts
Labels: p2, repeat-contributor

#32880 chore: don't add the same Aspect more than once
  packages/aws-cdk-lib/core/lib/aspect.ts
  packages/aws-cdk-lib/core/test/aspect.test.ts
Labels: p2, contribution/core

#32882 chore(cli): fix typo in ToolkitError symbol
  packages/aws-cdk/lib/toolkit/error.ts
Labels: p2, contribution/core, pr-linter/cli-integ-tested

#32884 chore: improved proptest logging
  packages/aws-cdk-lib/core/test/aspect.prop.test.ts
Labels: p2, contribution/core

#32817 fix(core): use correct formatting for aggregate errors in `aws-cdk`
  packages/aws-cdk/lib/api/aws-auth/credential-plugins.ts
  packages/aws-cdk/lib/api/aws-auth/sdk-provider.ts
  packages/aws-cdk/lib/api/aws-auth/sdk.ts
  packages/aws-cdk/lib/api/deploy-stack.ts
  packages/aws-cdk/lib/api/deployments.ts
  packages/aws-cdk/lib/api/environment-access.ts
  packages/aws-cdk/lib/api/environment-resources.ts
  packages/aws-cdk/lib/api/hotswap-deployments.ts
  packages/aws-cdk/lib/api/logs/find-cloudwatch-logs.ts
  packages/aws-cdk/lib/api/nested-stack-helpers.ts
  packages/aws-cdk/lib/api/util/cloudformation.ts
  packages/aws-cdk/lib/api/util/cloudformation/stack-event-poller.ts
  packages/aws-cdk/lib/cdk-toolkit.ts
  packages/aws-cdk/lib/context-providers/index.ts
  packages/aws-cdk/lib/init-hooks.ts
  packages/aws-cdk/lib/init.ts
  packages/aws-cdk/lib/notices.ts
  packages/aws-cdk/lib/util/archive.ts
  packages/aws-cdk/lib/util/error.ts
  packages/aws-cdk/test/api/fake-sts.ts
  packages/aws-cdk/test/api/util/error.test.ts
Labels: bug, p1, effort/small, contribution/core, pr-linter/exempt-integ-test, pr-linter/cli-integ-tested

#32874 docs(rds): fix typos
  packages/aws-cdk-lib/aws-rds/lib/database-secret.ts
Labels: p2, valued-contributor

#32878 docs(ec2-alpha): fix typos
  packages/@aws-cdk/aws-ec2-alpha/lib/route.ts
  packages/@aws-cdk/aws-ec2-alpha/test/vpc-add-method.test.ts
Labels: p2, valued-contributor

#32893 chore(toolkit): enforce codes at compile time
  packages/aws-cdk/lib/logging.ts
  packages/aws-cdk/lib/toolkit/cli-io-host.ts
  packages/aws-cdk/test/api/logs/logging.test.ts
  packages/aws-cdk/test/toolkit/cli-io-host.test.ts
Labels: p2, contribution/core, pr-linter/exempt-integ-test, pr-linter/cli-integ-tested

#32872 docs(lambda-event-sources): fix typos
  packages/aws-cdk-lib/aws-lambda-event-sources/lib/kafka.ts
Labels: p2, valued-contributor

#32890 docs(glue-alpha): fix typos
  packages/@aws-cdk/aws-glue-alpha/lib/job-executable.ts
  packages/@aws-cdk/aws-glue-alpha/lib/job.ts
  packages/@aws-cdk/aws-glue-alpha/lib/schema.ts
Labels: p2, valued-contributor

#32891 docs(iot-actions-alpha): fix typos
  packages/@aws-cdk/aws-iot-actions-alpha/lib/firehose-put-record-action.ts
  packages/@aws-cdk/aws-iot-actions-alpha/lib/kinesis-put-record-action.ts
  packages/@aws-cdk/aws-iot-actions-alpha/lib/step-functions-state-machine-action.ts
  packages/@aws-cdk/aws-iot-actions-alpha/test/kinesis-firehose/firehose-put-record-action.test.ts
Labels: p2, valued-contributor

#32873 docs(lambda-nodejs): fix typos
  packages/aws-cdk-lib/aws-lambda-nodejs/test/util.test.ts
Labels: p2, valued-contributor

#32792 fix(msk): clusterName validation in Cluster class is incorrect
  packages/@aws-cdk/aws-msk-alpha/lib/cluster.ts
Labels: p2, pr-linter/exempt-test, pr-linter/exempt-integ-test, distinguished-contributor

#32899 chore(spec2cdk): remove skipping iot1click service
  packages/aws-cdk-lib/scripts/gen.ts
Labels: p2, contribution/core

#32708 chore(cli): use CliIoHost as logger everywhere
  packages/aws-cdk/lib/api/aws-auth/credential-plugins.ts
  packages/aws-cdk/lib/api/cxapp/cloud-assembly.ts
  packages/aws-cdk/lib/api/deploy-stack.ts
  packages/aws-cdk/lib/api/deployments.ts
  packages/aws-cdk/lib/api/garbage-collection/garbage-collector.ts
  packages/aws-cdk/lib/api/garbage-collection/progress-printer.ts
  packages/aws-cdk/lib/api/hotswap-deployments.ts
  packages/aws-cdk/lib/api/logs/logs-monitor.ts
  packages/aws-cdk/lib/api/plugin/plugin.ts
  packages/aws-cdk/lib/api/util/cloudformation.ts
  packages/aws-cdk/lib/api/util/cloudformation/stack-activity-monitor.ts
  packages/aws-cdk/lib/cdk-toolkit.ts
  packages/aws-cdk/lib/cli.ts
  packages/aws-cdk/lib/commands/context.ts
  packages/aws-cdk/lib/commands/docs.ts
  packages/aws-cdk/lib/commands/doctor.ts
  packages/aws-cdk/lib/commands/migrate.ts
  packages/aws-cdk/lib/context-providers/ami.ts
  packages/aws-cdk/lib/diff.ts
  packages/aws-cdk/lib/import.ts
  packages/aws-cdk/lib/init.ts
  packages/aws-cdk/lib/logging.ts
  packages/aws-cdk/lib/notices.ts
  packages/aws-cdk/lib/toolkit/cli-io-host.ts
  packages/aws-cdk/lib/util/asset-publishing.ts
  packages/aws-cdk/lib/version.ts
  packages/aws-cdk/test/api/exec.test.ts
  packages/aws-cdk/test/api/logs/cli-logging.test.ts
  packages/aws-cdk/test/api/logs/logging.test.ts
  packages/aws-cdk/test/api/sdk-provider.test.ts
  packages/aws-cdk/test/api/stack-activity-monitor.test.ts
  packages/aws-cdk/test/cli.test.ts
  packages/aws-cdk/test/notices.test.ts
  packages/aws-cdk/test/toolkit/cli-io-host.test.ts
  packages/aws-cdk/test/util/silent.ts
  packages/aws-cdk/test/version.test.ts
Labels: p2, contribution/core, pr-linter/exempt-integ-test, pr-linter/cli-integ-tested

#32894 chore: dotnet upgrade from 6.0 -> 8.0
  packages/aws-cdk/lib/init-templates/app/csharp/src/%name.PascalCased%/%name.PascalCased%.template.csproj
  packages/aws-cdk/lib/init-templates/app/fsharp/src/%name.PascalCased%/%name.PascalCased%.template.fsproj
  packages/aws-cdk/lib/init-templates/sample-app/csharp/src/%name.PascalCased%/%name.PascalCased%.template.csproj
  packages/aws-cdk/lib/init-templates/sample-app/fsharp/src/%name.PascalCased%/%name.PascalCased%.template.fsproj
  packages/aws-cdk/test/init.test.ts
Labels: bug, p1, effort/small, contribution/core, pr-linter/cli-integ-tested, pr/needs-cli-test-run

#32914 docs(pipes-alpha): fix typos
  packages/@aws-cdk/aws-pipes-alpha/lib/logs.ts
Labels: p2, pr/needs-community-review, admired-contributor

#32913 docs(neptune-alpha): fix typos
  packages/@aws-cdk/aws-neptune-alpha/lib/cluster.ts
  packages/@aws-cdk/aws-neptune-alpha/lib/parameter-group.ts
  packages/@aws-cdk/aws-neptune-alpha/test/cluster.test.ts
Labels: p2, admired-contributor

#32922 chore(toolkit): fix logging statements
  packages/@aws-cdk/toolkit/lib/toolkit.ts
Labels: p2, contribution/core

#32924 chore(toolkit): fix build errors
  packages/@aws-cdk/toolkit/lib/actions/deploy.ts
  packages/@aws-cdk/toolkit/lib/toolkit.ts
Labels: p2, contribution/core

#32929 chore(toolkit): use global cli io host for now
  packages/@aws-cdk/toolkit/lib/toolkit.ts
  packages/aws-cdk/lib/cli.ts
  packages/aws-cdk/lib/logging.ts
  packages/aws-cdk/lib/toolkit/cli-io-host.ts
  packages/aws-cdk/test/toolkit/cli-io-host.test.ts
Labels: p2, contribution/core, pr/needs-cli-test-run

#32950 chore(toolkit): add to watch options
  packages/@aws-cdk/toolkit/lib/actions/watch.ts
Labels: p2, contribution/core

#32947 chore(toolkit): cloud assemblies
  packages/@aws-cdk/toolkit/lib/api/cloud-assembly/index.ts
  packages/@aws-cdk/toolkit/lib/api/cloud-assembly/private/context-aware-source.ts
  packages/@aws-cdk/toolkit/lib/api/cloud-assembly/private/exec.ts
  packages/@aws-cdk/toolkit/lib/api/cloud-assembly/private/prepare-source.ts
  packages/@aws-cdk/toolkit/lib/api/cloud-assembly/private/source-builder.ts
  packages/@aws-cdk/toolkit/lib/api/io/private/logger.ts
  packages/@aws-cdk/toolkit/lib/api/io/private/messages.ts
  packages/@aws-cdk/toolkit/lib/api/toolkit/private/index.ts
  packages/@aws-cdk/toolkit/lib/toolkit.ts
  packages/aws-cdk/lib/api/cxapp/exec.ts
  packages/aws-cdk/lib/settings.ts
Labels: p2, contribution/core, pr/needs-cli-test-run

#32953 chore(cli): prepare cli for programmatic toolkit
  packages/@aws-cdk/cli-lib-alpha/lib/cli.ts
  packages/aws-cdk/lib/api/bootstrap/bootstrap-props.ts
  packages/aws-cdk/lib/api/cxapp/cloud-assembly.ts
  packages/aws-cdk/lib/api/cxapp/exec.ts
  packages/aws-cdk/lib/api/deployments.ts
  packages/aws-cdk/lib/api/util/string-manipulation.ts
  packages/aws-cdk/lib/cdk-toolkit.ts
  packages/aws-cdk/lib/cli.ts
  packages/aws-cdk/lib/import.ts
  packages/aws-cdk/lib/logging.ts
  packages/aws-cdk/lib/migrator.ts
  packages/aws-cdk/lib/serialize.ts
  packages/aws-cdk/lib/settings.ts
  packages/aws-cdk/lib/tags.ts
  packages/aws-cdk/lib/toolkit/cli-io-host.ts
  packages/aws-cdk/lib/toolkit/error.ts
  packages/aws-cdk/test/api/cloud-assembly.test.ts
  packages/aws-cdk/test/cdk-toolkit.test.ts
  packages/aws-cdk/test/serialize.test.ts
  packages/aws-cdk/test/settings.test.ts
  packages/aws-cdk/test/toolkit-error.test.ts
  packages/aws-cdk/test/toolkit/cli-io-host.test.ts
Labels: p2, contribution/core, pr-linter/cli-integ-tested

#32960 chore(merge-back): 2.176.0
  CHANGELOG.v2.alpha.md
  CHANGELOG.v2.md
  packages/aws-cdk-lib/cx-api/FEATURE_FLAGS.md
  packages/aws-cdk-lib/cx-api/lib/features.ts
  packages/aws-cdk-lib/recommended-feature-flags.json
  version.v2.json
Labels: p2, pr/needs-community-review, pr/no-squash, auto-approve

#32915 docs(route53resolver-alpha): fix typos
  packages/@aws-cdk/aws-route53resolver-alpha/lib/firewall-rule-group-association.ts
Labels: p2, admired-contributor

#32932 chore(glue-alpha): revert fix typos
  packages/@aws-cdk/aws-glue-alpha/lib/job-executable.ts
  packages/@aws-cdk/aws-glue-alpha/lib/job.ts
  packages/@aws-cdk/aws-glue-alpha/lib/schema.ts
Labels: p2, contribution/core

#32245 feat(synthetics): node playwright 1.0 and python selenium 4.1 runtime
  packages/@aws-cdk-testing/framework-integ/test/aws-synthetics/test/canaries/canary.mjs
  packages/@aws-cdk-testing/framework-integ/test/aws-synthetics/test/canaries/playwright/canary.mjs
  packages/@aws-cdk-testing/framework-integ/test/aws-synthetics/test/integ.canary-artifact-s3-encryption.js.snapshot/IntegCanaryTestDefaultTestDeployAssert3AD5A094.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-synthetics/test/integ.canary-artifact-s3-encryption.js.snapshot/asset.5178413cfe8db00b2d5dcfa9be417e934c64601d0da3031d88c145c8293bc27f/canary.mjs
  packages/@aws-cdk-testing/framework-integ/test/aws-synthetics/test/integ.canary-artifact-s3-encryption.js.snapshot/asset.5178413cfe8db00b2d5dcfa9be417e934c64601d0da3031d88c145c8293bc27f/nodejs/node_modules/canary.js
  packages/@aws-cdk-testing/framework-integ/test/aws-synthetics/test/integ.canary-artifact-s3-encryption.js.snapshot/asset.5178413cfe8db00b2d5dcfa9be417e934c64601d0da3031d88c145c8293bc27f/nodejs/node_modules/folder/canary.js
  packages/@aws-cdk-testing/framework-integ/test/aws-synthetics/test/integ.canary-artifact-s3-encryption.js.snapshot/asset.5178413cfe8db00b2d5dcfa9be417e934c64601d0da3031d88c145c8293bc27f/playwright/canary.mjs
  packages/@aws-cdk-testing/framework-integ/test/aws-synthetics/test/integ.canary-artifact-s3-encryption.js.snapshot/asset.5178413cfe8db00b2d5dcfa9be417e934c64601d0da3031d88c145c8293bc27f/python/canary.py
  packages/@aws-cdk-testing/framework-integ/test/aws-synthetics/test/integ.canary-artifact-s3-encryption.js.snapshot/canary-artifact-s3-encryption.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-synthetics/test/integ.canary-artifact-s3-encryption.js.snapshot/canary-artifact-s3-encryption.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-synthetics/test/integ.canary-artifact-s3-encryption.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-synthetics/test/integ.canary-artifact-s3-encryption.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-synthetics/test/integ.canary-artifact-s3-encryption.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-synthetics/test/integ.canary-artifact-s3-encryption.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-synthetics/test/integ.canary-artifact-s3-encryption.ts
  packages/@aws-cdk-testing/framework-integ/test/aws-synthetics/test/integ.canary.js.snapshot/IntegCanaryTestDefaultTestDeployAssert3AD5A094.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-synthetics/test/integ.canary.js.snapshot/IntegCanaryTestDefaultTestDeployAssert3AD5A094.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-synthetics/test/integ.canary.js.snapshot/asset.5178413cfe8db00b2d5dcfa9be417e934c64601d0da3031d88c145c8293bc27f/canary.mjs
  packages/@aws-cdk-testing/framework-integ/test/aws-synthetics/test/integ.canary.js.snapshot/asset.5178413cfe8db00b2d5dcfa9be417e934c64601d0da3031d88c145c8293bc27f/nodejs/node_modules/canary.js
  packages/@aws-cdk-testing/framework-integ/test/aws-synthetics/test/integ.canary.js.snapshot/asset.5178413cfe8db00b2d5dcfa9be417e934c64601d0da3031d88c145c8293bc27f/nodejs/node_modules/folder/canary.js
  packages/@aws-cdk-testing/framework-integ/test/aws-synthetics/test/integ.canary.js.snapshot/asset.5178413cfe8db00b2d5dcfa9be417e934c64601d0da3031d88c145c8293bc27f/playwright/canary.mjs
  packages/@aws-cdk-testing/framework-integ/test/aws-synthetics/test/integ.canary.js.snapshot/asset.5178413cfe8db00b2d5dcfa9be417e934c64601d0da3031d88c145c8293bc27f/python/canary.py
  packages/@aws-cdk-testing/framework-integ/test/aws-synthetics/test/integ.canary.js.snapshot/asset.bfcf4228d6660f50e81f19efdb64c6388dda6796296eb239decdff1dbc2f4981.bundle/index.js
  packages/@aws-cdk-testing/framework-integ/test/aws-synthetics/test/integ.canary.js.snapshot/canary-one.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-synthetics/test/integ.canary.js.snapshot/canary-one.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-synthetics/test/integ.canary.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-synthetics/test/integ.canary.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-synthetics/test/integ.canary.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-synthetics/test/integ.canary.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-synthetics/test/integ.canary.ts
  packages/aws-cdk-lib/aws-synthetics/README.md
  packages/aws-cdk-lib/aws-synthetics/lib/canary.ts
  packages/aws-cdk-lib/aws-synthetics/lib/code.ts
  packages/aws-cdk-lib/aws-synthetics/lib/runtime.ts
  packages/aws-cdk-lib/aws-synthetics/test/canaries/canary.js
  packages/aws-cdk-lib/aws-synthetics/test/canaries/playwright/canary.js
  packages/aws-cdk-lib/aws-synthetics/test/canary.test.ts
  packages/aws-cdk-lib/aws-synthetics/test/code.test.ts
Labels: p2, distinguished-contributor

#32919 chore(toolkit): programmatic toolkit for the AWS CDK initial code
  packages/@aws-cdk/aws-custom-resource-sdk-adapter/package.json
  packages/@aws-cdk/custom-resource-handlers/lib/aws-events-targets/aws-api-handler/index.ts
  packages/@aws-cdk/toolkit/.gitignore
  packages/@aws-cdk/toolkit/.npmignore
  packages/@aws-cdk/toolkit/bundle.mjs
  packages/@aws-cdk/toolkit/lib/actions/deploy.ts
  packages/@aws-cdk/toolkit/lib/actions/destroy.ts
  packages/@aws-cdk/toolkit/lib/actions/diff.ts
  packages/@aws-cdk/toolkit/lib/actions/index.ts
  packages/@aws-cdk/toolkit/lib/actions/list.ts
  packages/@aws-cdk/toolkit/lib/actions/rollback.ts
  packages/@aws-cdk/toolkit/lib/actions/synth.ts
  packages/@aws-cdk/toolkit/lib/actions/watch.ts
  packages/@aws-cdk/toolkit/lib/api/aws-auth/index.ts
  packages/@aws-cdk/toolkit/lib/api/aws-auth/types.ts
  packages/@aws-cdk/toolkit/lib/api/aws-cdk.ts
  packages/@aws-cdk/toolkit/lib/api/cloud-assembly/cached-source.ts
  packages/@aws-cdk/toolkit/lib/api/cloud-assembly/identity-source.ts
  packages/@aws-cdk/toolkit/lib/api/cloud-assembly/index.ts
  packages/@aws-cdk/toolkit/lib/api/cloud-assembly/private/context-aware-source.ts
  packages/@aws-cdk/toolkit/lib/api/cloud-assembly/private/exec.ts
  packages/@aws-cdk/toolkit/lib/api/cloud-assembly/private/prepare-source.ts
  packages/@aws-cdk/toolkit/lib/api/cloud-assembly/private/source-builder.ts
  packages/@aws-cdk/toolkit/lib/api/cloud-assembly/stack-assembly.ts
  packages/@aws-cdk/toolkit/lib/api/cloud-assembly/stack-selector.ts
  packages/@aws-cdk/toolkit/lib/api/cloud-assembly/types.ts
  packages/@aws-cdk/toolkit/lib/api/errors.ts
  packages/@aws-cdk/toolkit/lib/api/io/index.ts
  packages/@aws-cdk/toolkit/lib/api/io/io-host.ts
  packages/@aws-cdk/toolkit/lib/api/io/private/index.ts
  packages/@aws-cdk/toolkit/lib/api/io/private/logger.ts
  packages/@aws-cdk/toolkit/lib/api/io/private/messages.ts
  packages/@aws-cdk/toolkit/lib/api/io/private/timer.ts
  packages/@aws-cdk/toolkit/lib/api/io/private/types.ts
  packages/@aws-cdk/toolkit/lib/api/toolkit/private/index.ts
  packages/@aws-cdk/toolkit/lib/cloud-assembly-source.ts
  packages/@aws-cdk/toolkit/lib/index.ts
  packages/@aws-cdk/toolkit/lib/io-host.ts
  packages/@aws-cdk/toolkit/lib/toolkit.ts
  packages/@aws-cdk/toolkit/lib/types.ts
  packages/@aws-cdk/toolkit/package.json
  packages/@aws-cdk/toolkit/tsconfig.json
Labels: p2, contribution/core

#32912 docs(iotevents-alpha): fix typos
  packages/@aws-cdk/aws-iotevents-alpha/lib/state.ts
  packages/@aws-cdk/aws-iotevents-alpha/test/detector-model.test.ts
Labels: p2, admired-contributor

#32967 chore(toolkit): prevent unintended public exports, file re-org
  packages/@aws-cdk/toolkit/.gitignore
  packages/@aws-cdk/toolkit/.npmignore
  packages/@aws-cdk/toolkit/lib/actions/deploy/index.ts
  packages/@aws-cdk/toolkit/lib/actions/deploy/private/helpers.ts
  packages/@aws-cdk/toolkit/lib/actions/deploy/private/index.ts
  packages/@aws-cdk/toolkit/lib/actions/destroy/index.ts
  packages/@aws-cdk/toolkit/lib/actions/diff/index.ts
  packages/@aws-cdk/toolkit/lib/actions/import/index.ts
  packages/@aws-cdk/toolkit/lib/actions/list/index.ts
  packages/@aws-cdk/toolkit/lib/actions/rollback/index.ts
  packages/@aws-cdk/toolkit/lib/actions/synth/index.ts
  packages/@aws-cdk/toolkit/lib/actions/watch/index.ts
  packages/@aws-cdk/toolkit/lib/api/cloud-assembly/private/context-aware-source.ts
  packages/@aws-cdk/toolkit/lib/api/cloud-assembly/private/prepare-source.ts
  packages/@aws-cdk/toolkit/lib/api/cloud-assembly/private/source-builder.ts
  packages/@aws-cdk/toolkit/lib/cloud-assembly-source.ts
  packages/@aws-cdk/toolkit/lib/index.ts
  packages/@aws-cdk/toolkit/lib/toolkit/index.ts
  packages/@aws-cdk/toolkit/lib/toolkit/private/index.ts
  packages/@aws-cdk/toolkit/lib/toolkit/toolkit.ts
Labels: p2, contribution/core

#30966 feat(s3): replicating objects
  packages/@aws-cdk-testing/framework-integ/test/aws-s3/test/integ.bucket-cross-account-replication.js.snapshot/ReplicationIntegDefaultTestDeployAssert2C07A074.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-s3/test/integ.bucket-cross-account-replication.js.snapshot/ReplicationIntegDefaultTestDeployAssert2C07A074.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-s3/test/integ.bucket-cross-account-replication.js.snapshot/asset.b98abee59e034ed29eeb601684dc34752baa86509a7d457d72305d4e19ecc80b.bundle/index.js
  packages/@aws-cdk-testing/framework-integ/test/aws-s3/test/integ.bucket-cross-account-replication.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-s3/test/integ.bucket-cross-account-replication.js.snapshot/child-stack.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-s3/test/integ.bucket-cross-account-replication.js.snapshot/child-stack.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-s3/test/integ.bucket-cross-account-replication.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-s3/test/integ.bucket-cross-account-replication.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-s3/test/integ.bucket-cross-account-replication.js.snapshot/parent-stack.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-s3/test/integ.bucket-cross-account-replication.js.snapshot/parent-stack.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-s3/test/integ.bucket-cross-account-replication.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-s3/test/integ.bucket-cross-account-replication.ts
  packages/@aws-cdk-testing/framework-integ/test/aws-s3/test/integ.bucket-replication.js.snapshot/ReplicationIntegDefaultTestDeployAssert2C07A074.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-s3/test/integ.bucket-replication.js.snapshot/ReplicationIntegDefaultTestDeployAssert2C07A074.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-s3/test/integ.bucket-replication.js.snapshot/ReplicationStack.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-s3/test/integ.bucket-replication.js.snapshot/ReplicationStack.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-s3/test/integ.bucket-replication.js.snapshot/asset.14d52bdadae57c6ec2c7b715c5420ae5c3001a8252558f7219f6207e4f405a97.bundle/index.js
  packages/@aws-cdk-testing/framework-integ/test/aws-s3/test/integ.bucket-replication.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-s3/test/integ.bucket-replication.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-s3/test/integ.bucket-replication.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-s3/test/integ.bucket-replication.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-s3/test/integ.bucket-replication.ts
  packages/aws-cdk-lib/aws-s3/README.md
  packages/aws-cdk-lib/aws-s3/lib/bucket.ts
  packages/aws-cdk-lib/aws-s3/test/bucket.test.ts
Labels: p1, feature-request, effort/small, distinguished-contributor, needs-security-review

#32970 chore(aws-cdk-lib): enable project references
  packages/@aws-cdk/aws-ec2-alpha/lib/subnet-v2.ts
  packages/@aws-cdk/aws-ec2-alpha/lib/vpc-v2-base.ts
  packages/@aws-cdk/aws-ec2-alpha/lib/vpc-v2.ts
  packages/@aws-cdk/aws-iot-actions-alpha/test/cloudwatch/integ.cloudwatch-set-alarm-state-action.ts
  packages/@aws-cdk/aws-iot-alpha/lib/logging.ts
  packages/@aws-cdk/aws-lambda-go-alpha/test/bundling.test.ts
  packages/@aws-cdk/aws-lambda-python-alpha/test/function.test.ts
  packages/@aws-cdk/aws-sagemaker-alpha/lib/endpoint.ts
  packages/@aws-cdk/aws-sagemaker-alpha/lib/model.ts
  packages/aws-cdk-lib/package.json
  tools/@aws-cdk/pkglint/lib/rules.ts
Labels: p2, contribution/core

#32976 chore: ensure docker file runs as non root user
  packages/@aws-cdk/aws-lambda-go-alpha/lib/Dockerfile
  packages/@aws-cdk/aws-lambda-python-alpha/lib/Dockerfile
  packages/aws-cdk-lib/aws-lambda-nodejs/lib/Dockerfile
Labels: p2, contribution/core

#32059 feat(cloudfront-origins): list access level for 404 response
  packages/@aws-cdk-testing/framework-integ/test/aws-cloudfront-origins/test/integ.s3-origin-oac-list-access.js.snapshot/asset.b98abee59e034ed29eeb601684dc34752baa86509a7d457d72305d4e19ecc80b.bundle/index.js
  packages/@aws-cdk-testing/framework-integ/test/aws-cloudfront-origins/test/integ.s3-origin-oac-list-access.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-cloudfront-origins/test/integ.s3-origin-oac-list-access.js.snapshot/cloudfront-s3-bucket-origin-oac-list-access.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-cloudfront-origins/test/integ.s3-origin-oac-list-access.js.snapshot/cloudfront-s3-bucket-origin-oac-list-access.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-cloudfront-origins/test/integ.s3-origin-oac-list-access.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-cloudfront-origins/test/integ.s3-origin-oac-list-access.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-cloudfront-origins/test/integ.s3-origin-oac-list-access.js.snapshot/s3originoaclistaccessDefaultTestDeployAssert6967EED4.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-cloudfront-origins/test/integ.s3-origin-oac-list-access.js.snapshot/s3originoaclistaccessDefaultTestDeployAssert6967EED4.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-cloudfront-origins/test/integ.s3-origin-oac-list-access.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-cloudfront-origins/test/integ.s3-origin-oac-list-access.ts
  packages/aws-cdk-lib/aws-cloudfront-origins/README.md
  packages/aws-cdk-lib/aws-cloudfront-origins/lib/s3-bucket-origin.ts
  packages/aws-cdk-lib/aws-cloudfront-origins/test/s3-bucket-origin.test.ts
  packages/aws-cdk-lib/aws-cloudfront/lib/origin-access-control.ts
Labels: p2, feature-request, pr/needs-community-review, effort/medium, admired-contributor, needs-security-review

#32889 docs(appsync): correct the schema definition for the sample code
  packages/aws-cdk-lib/aws-appsync/README.md
Labels: bug, p2, pr/needs-community-review, beginning-contributor

#32969 refactor: re-organize PR linter
  .github/workflows/pr-linter-review-trigger.yml
  .github/workflows/pr-linter.yml
  tools/@aws-cdk/prlint/constants.ts
  tools/@aws-cdk/prlint/github.ts
  tools/@aws-cdk/prlint/index.ts
  tools/@aws-cdk/prlint/lint.ts
  tools/@aws-cdk/prlint/linter-base.ts
  tools/@aws-cdk/prlint/results.ts
  tools/@aws-cdk/prlint/test/lint.test.ts
Labels: p2, contribution/core

#32987 chore: stop failing the PR linter on changes requested
  .mergify.yml
  tools/@aws-cdk/prlint/index.ts
Labels: p2, contribution/core

#32971 chore(toolkit): synth action with tests
  aws-cdk.code-workspace
  packages/@aws-cdk/toolkit/.gitignore
  packages/@aws-cdk/toolkit/jest.config.js
  packages/@aws-cdk/toolkit/lib/actions/synth/index.ts
  packages/@aws-cdk/toolkit/lib/actions/watch/index.ts
  packages/@aws-cdk/toolkit/lib/api/cloud-assembly/private/index.ts
  packages/@aws-cdk/toolkit/lib/api/cloud-assembly/private/prepare-source.ts
  packages/@aws-cdk/toolkit/lib/api/cloud-assembly/private/source-builder.ts
  packages/@aws-cdk/toolkit/lib/api/cloud-assembly/private/stack-selectors.ts
  packages/@aws-cdk/toolkit/lib/api/cloud-assembly/source-builder.ts
  packages/@aws-cdk/toolkit/lib/api/io/index.ts
  packages/@aws-cdk/toolkit/lib/api/io/io-host.ts
  packages/@aws-cdk/toolkit/lib/api/io/io-message.ts
  packages/@aws-cdk/toolkit/lib/api/io/private/logger.ts
  packages/@aws-cdk/toolkit/lib/api/io/private/messages.ts
  packages/@aws-cdk/toolkit/lib/api/io/private/types.ts
  packages/@aws-cdk/toolkit/lib/toolkit/toolkit.ts
  packages/@aws-cdk/toolkit/test/_fixtures/stack-with-bucket/cdk.out/Stack1.assets.json
  packages/@aws-cdk/toolkit/test/_fixtures/stack-with-bucket/cdk.out/Stack1.template.json
  packages/@aws-cdk/toolkit/test/_fixtures/stack-with-bucket/cdk.out/cdk.out
  packages/@aws-cdk/toolkit/test/_fixtures/stack-with-bucket/cdk.out/manifest.json
  packages/@aws-cdk/toolkit/test/_fixtures/stack-with-bucket/cdk.out/tree.json
  packages/@aws-cdk/toolkit/test/_fixtures/stack-with-bucket/index.js
  packages/@aws-cdk/toolkit/test/_fixtures/stack-with-bucket/index.ts
  packages/@aws-cdk/toolkit/test/_fixtures/two-empty-stacks/app.js
  packages/@aws-cdk/toolkit/test/_fixtures/two-empty-stacks/cdk.json
  packages/@aws-cdk/toolkit/test/_fixtures/two-empty-stacks/cdk.out/Stack1.assets.json
  packages/@aws-cdk/toolkit/test/_fixtures/two-empty-stacks/cdk.out/Stack1.template.json
  packages/@aws-cdk/toolkit/test/_fixtures/two-empty-stacks/cdk.out/Stack2.assets.json
  packages/@aws-cdk/toolkit/test/_fixtures/two-empty-stacks/cdk.out/Stack2.template.json
  packages/@aws-cdk/toolkit/test/_fixtures/two-empty-stacks/cdk.out/cdk.out
  packages/@aws-cdk/toolkit/test/_fixtures/two-empty-stacks/cdk.out/manifest.json
  packages/@aws-cdk/toolkit/test/_fixtures/two-empty-stacks/cdk.out/tree.json
  packages/@aws-cdk/toolkit/test/_fixtures/two-empty-stacks/index.js
  packages/@aws-cdk/toolkit/test/_fixtures/two-empty-stacks/index.ts
  packages/@aws-cdk/toolkit/test/_helpers/index.ts
  packages/@aws-cdk/toolkit/test/_helpers/test-io-host.ts
  packages/@aws-cdk/toolkit/test/actions/synth.test.ts
  packages/@aws-cdk/toolkit/test/api/cloud-assembly/source-builder.test.ts
  packages/@aws-cdk/toolkit/test/api/io/io-message.test.ts
  packages/@aws-cdk/toolkit/test/toolkit/toolkit.test.ts
  packages/@aws-cdk/toolkit/tsconfig.json
Labels: p2, contribution/core

#32986 chore: fix memory overflow for buffered console
  packages/aws-cdk-lib/testhelpers/jest-bufferedconsole.ts
  packages/aws-cdk/lib/version.ts
  packages/aws-cdk/test/jest-bufferedconsole.ts
Labels: p2, contribution/core, pr-linter/cli-integ-tested

#32990 chore: add test workflow for check_suite event
  .github/workflows/check-suite-test.yaml
Labels: p2, contribution/core

#32991 chore(toolkit): generate docs
  packages/@aws-cdk/toolkit/.npmignore
  packages/@aws-cdk/toolkit/lib/actions/diff/index.ts
  packages/@aws-cdk/toolkit/lib/api/cloud-assembly/private/source-builder.ts
  packages/@aws-cdk/toolkit/lib/api/cloud-assembly/stack-assembly.ts
  packages/@aws-cdk/toolkit/package.json
  yarn.lock
Labels: p2, contribution/core

#32989 chore(toolkit): change bundling to not have a dependency on the aws-cdk package
  packages/@aws-cdk/toolkit/.npmignore
  packages/@aws-cdk/toolkit/build-tools/bundle.mjs
  packages/@aws-cdk/toolkit/build-tools/package.sh
  packages/@aws-cdk/toolkit/bundle.mjs
  packages/@aws-cdk/toolkit/lib/api/aws-cdk.ts
  packages/@aws-cdk/toolkit/package.json
  packages/@aws-cdk/toolkit/tsconfig.json
Labels: p2, contribution/core

#32996 chore(toolkit): pass context to cx builders
  packages/@aws-cdk/toolkit/lib/api/cloud-assembly/private/context-aware-source.ts
  packages/@aws-cdk/toolkit/lib/api/cloud-assembly/private/prepare-source.ts
  packages/@aws-cdk/toolkit/lib/api/cloud-assembly/private/source-builder.ts
  packages/@aws-cdk/toolkit/lib/api/cloud-assembly/source-builder.ts
  packages/@aws-cdk/toolkit/test/_fixtures/external-context/app.js
  packages/@aws-cdk/toolkit/test/_fixtures/external-context/index.ts
  packages/@aws-cdk/toolkit/test/_helpers/index.ts
  packages/@aws-cdk/toolkit/test/api/cloud-assembly/source-builder.test.ts
Labels: p1, contribution/core, pr/needs-maintainer-review

#32977 chore(toolkit): requireApproval option for deploy
  packages/@aws-cdk/toolkit/lib/actions/deploy/index.ts
  packages/@aws-cdk/toolkit/lib/actions/diff/private/helpers.ts
  packages/@aws-cdk/toolkit/lib/actions/diff/private/index.ts
  packages/@aws-cdk/toolkit/lib/toolkit/toolkit.ts
  packages/@aws-cdk/toolkit/package.json
  packages/@aws-cdk/toolkit/test/_fixtures/stack-with-role/index.ts
  packages/@aws-cdk/toolkit/test/_helpers/test-io-host.ts
  packages/@aws-cdk/toolkit/test/actions/deploy.test.ts
  packages/@aws-cdk/toolkit/test/actions/synth.test.ts
  packages/@aws-cdk/toolkit/test/api/cloud-assembly/source-builder.test.ts
Labels: p2, contribution/core, pr/needs-maintainer-review

#32995 chore: ensure docker file runs as non root user
  packages/@aws-cdk-testing/cli-integ/resources/cdk-apps/sam_cdk_integ_app/src/docker/DockerImageFunctionConstruct/Dockerfile
Labels: p2, contribution/core

#32999 chore(cli): fix docs
  packages/aws-cdk/lib/cdk-toolkit.ts
  packages/aws-cdk/test/cdk-toolkit.test.ts
Labels: p2, contribution/core, pr-linter/cli-integ-tested

#33000 test(toolkit): more deploy tests
  packages/@aws-cdk/toolkit/lib/toolkit/toolkit.ts
  packages/@aws-cdk/toolkit/test/_fixtures/stack-with-notification-arns/index.ts
  packages/@aws-cdk/toolkit/test/actions/deploy.test.ts
Labels: p2, contribution/core

#32838 docs(lambda): add note on potential errors when updating lambda functions
  packages/aws-cdk-lib/aws-lambda/README.md
Labels: p2, beginning-contributor

#32993 refactor(cli): `CliIoHost` is more self contained
  packages/@aws-cdk/toolkit/lib/toolkit/toolkit.ts
  packages/aws-cdk/lib/api/util/cloudformation/stack-activity-monitor.ts
  packages/aws-cdk/lib/cli.ts
  packages/aws-cdk/lib/logging.ts
  packages/aws-cdk/lib/toolkit/cli-io-host.ts
  packages/aws-cdk/lib/util/yargs-helpers.ts
  packages/aws-cdk/test/api/bootstrap2.test.ts
  packages/aws-cdk/test/api/deploy-stack.test.ts
  packages/aws-cdk/test/api/exec.test.ts
  packages/aws-cdk/test/api/logs/logging.test.ts
  packages/aws-cdk/test/api/logs/logs-monitor.test.ts
  packages/aws-cdk/test/api/sdk-provider.test.ts
  packages/aws-cdk/test/api/stack-activity-monitor.test.ts
  packages/aws-cdk/test/cdk-toolkit.test.ts
  packages/aws-cdk/test/cli.test.ts
  packages/aws-cdk/test/toolkit/cli-io-host.test.ts
Labels: p2, pr/do-not-merge, contribution/core

#32619 docs(contributing): add introduction to contributing and update flowchart to include major and minor contributions
  CONTRIBUTING.md
Labels: p2, beginning-contributor

#33004 chore: revert ensure docker file runs as non root user
  packages/@aws-cdk/aws-lambda-go-alpha/lib/Dockerfile
  packages/@aws-cdk/aws-lambda-python-alpha/lib/Dockerfile
  packages/aws-cdk-lib/aws-lambda-nodejs/lib/Dockerfile
Labels: p2, contribution/core

#33002 test(toolkit): destroy tests
  packages/@aws-cdk/toolkit/test/actions/destroy.test.ts
Labels: p2, contribution/core

#32963 chore(README): remove Mergify badge
  README.md
Labels: p2, beginning-contributor

#33019 feat: update L1 CloudFormation resource definitions
  packages/@aws-cdk/cloudformation-diff/package.json
  packages/@aws-cdk/integ-runner/package.json
  packages/aws-cdk-lib/aws-notifications/.jsiirc.json
  packages/aws-cdk-lib/aws-notifications/README.md
  packages/aws-cdk-lib/aws-notifications/index.ts
  packages/aws-cdk-lib/aws-notifications/lib/index.ts
  packages/aws-cdk-lib/aws-notificationscontacts/.jsiirc.json
  packages/aws-cdk-lib/aws-notificationscontacts/README.md
  packages/aws-cdk-lib/aws-notificationscontacts/index.ts
  packages/aws-cdk-lib/aws-notificationscontacts/lib/index.ts
  packages/aws-cdk-lib/index.ts
  packages/aws-cdk-lib/package.json
  packages/aws-cdk-lib/scripts/scope-map.json
  tools/@aws-cdk/spec2cdk/package.json
  yarn.lock
Labels: p2, dependencies, contribution/core, pr-linter/exempt-readme, pr-linter/exempt-test, auto-approve, pr-linter/exempt-integ-test

#32988 chore: reduce the runtime of CLI unit tests by 2 minutes
  packages/aws-cdk/test/api/hotswap/appsync-mapping-templates-hotswap-deployments.test.ts
Labels: p2, contribution/core

#33016 chore: make tests work with new SDKv3 version
  packages/aws-cdk/THIRD_PARTY_LICENSES
  packages/aws-cdk/package.json
  packages/aws-cdk/test/api/fake-sts.ts
  packages/aws-cdk/test/api/sdk-provider.test.ts
  packages/aws-cdk/test/util/mock-sdk.ts
  yarn.lock
Labels: p2, contribution/core

#33003 chore(scheduler-alpha-targets): raise awareness for default policy risk
  packages/@aws-cdk/aws-scheduler-targets-alpha/README.md
  packages/@aws-cdk/aws-scheduler-targets-alpha/lib/universal.ts
  packages/@aws-cdk/aws-scheduler-targets-alpha/test/universal.test.ts
Labels: p2, contribution/core, pr/needs-maintainer-review

#33021 fix(cli): disallow import of internal cli libraries
  packages/@aws-cdk/cli-lib-alpha/lib/cli.ts
  packages/@aws-cdk/cli-lib-alpha/test/cli.test.ts
  packages/@aws-cdk/cli-lib-alpha/test/commands.test.ts
  packages/@aws-cdk/toolkit/lib/api/aws-cdk.ts
  packages/aws-cdk/lib/index.ts
  packages/aws-cdk/lib/legacy-exports-source.ts
  packages/aws-cdk/lib/legacy-exports.ts
  packages/aws-cdk/lib/legacy-logging-source.ts
  packages/aws-cdk/package.json
  packages/aws-cdk/test/api/fake-cloudformation-stack.ts
  packages/aws-cdk/test/api/logs/find-cloudwatch-logs.test.ts
  packages/aws-cdk/test/cdk-toolkit.test.ts
  packages/aws-cdk/test/context-providers/amis.test.ts
  packages/aws-cdk/test/context-providers/availability-zones.test.ts
  packages/aws-cdk/test/context-providers/endpoint-service-availability-zones.test.ts
  packages/aws-cdk/test/context-providers/hosted-zones.test.ts
  packages/aws-cdk/test/context-providers/load-balancers.test.ts
  packages/aws-cdk/test/context-providers/security-groups.test.ts
  packages/aws-cdk/test/context-providers/ssm-parameters.test.ts
  packages/aws-cdk/test/util/cloudformation.test.ts
  packages/aws-cdk/test/util/mock-sdk.ts
Labels: p2, contribution/core, pr-linter/exempt-test, pr-linter/exempt-integ-test

#32769 fix(cloudfront): add validations on ResponseHeadersCorsBehavior.accessControlAllowMethods
  packages/aws-cdk-lib/aws-cloudfront/lib/response-headers-policy.ts
  packages/aws-cdk-lib/aws-cloudfront/test/response-headers-policy.test.ts
Labels: p2, pr/needs-community-review, pr-linter/exempt-integ-test, admired-contributor

#32725 fix(bundling): enclosing metafile & tsconfig paths with quotes
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-nodejs/test/integ-handlers/whitespace path/ts-handler.ts
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-nodejs/test/integ.function.js.snapshot/asset.2853b22adf0b1929f5ccd54840d96d298c0ba574aa7a5bd02df65295244d1085/index.js
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-nodejs/test/integ.function.js.snapshot/asset.2853b22adf0b1929f5ccd54840d96d298c0ba574aa7a5bd02df65295244d1085/index.meta.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-nodejs/test/integ.function.js.snapshot/cdk-integ-lambda-nodejs.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-nodejs/test/integ.function.js.snapshot/cdk-integ-lambda-nodejs.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-nodejs/test/integ.function.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-nodejs/test/integ.function.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-nodejs/test/integ.function.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-nodejs/test/integ.function.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-nodejs/test/integ.function.ts
  packages/@aws-cdk-testing/framework-integ/test/aws-lambda-nodejs/test/whitespace path/tsconfig.json
  packages/aws-cdk-lib/aws-lambda-nodejs/lib/bundling.ts
  packages/aws-cdk-lib/aws-lambda-nodejs/test/bundling.test.ts
Labels: p2, beginning-contributor

#32961 chore(eks-v2): remove awsAuth
  packages/@aws-cdk/aws-eks-v2-alpha/lib/alb-controller.ts
  packages/@aws-cdk/aws-eks-v2-alpha/lib/aws-auth-mapping.ts
  packages/@aws-cdk/aws-eks-v2-alpha/lib/aws-auth.ts
  packages/@aws-cdk/aws-eks-v2-alpha/lib/cluster.ts
  packages/@aws-cdk/aws-eks-v2-alpha/lib/fargate-profile.ts
  packages/@aws-cdk/aws-eks-v2-alpha/lib/index.ts
  packages/@aws-cdk/aws-eks-v2-alpha/lib/managed-nodegroup.ts
  packages/@aws-cdk/aws-eks-v2-alpha/test/access-entry.test.ts
  packages/@aws-cdk/aws-eks-v2-alpha/test/alb-controller.test.ts
  packages/@aws-cdk/aws-eks-v2-alpha/test/awsauth.test.ts
  packages/@aws-cdk/aws-eks-v2-alpha/test/cluster.test.ts
  packages/@aws-cdk/aws-eks-v2-alpha/test/fargate.test.ts
  packages/@aws-cdk/aws-eks-v2-alpha/test/nodegroup.test.ts
Labels: p2, contribution/core

#32998 fix(cx-api): cannot detect CloudAssembly across different libraries
  allowed-breaking-changes.txt
  packages/@aws-cdk/cli-lib-alpha/THIRD_PARTY_LICENSES
  packages/@aws-cdk/cx-api/package.json
  packages/@aws-cdk/integ-runner/package.json
  packages/@aws-cdk/toolkit/lib/api/cloud-assembly/private/source-builder.ts
  packages/@aws-cdk/toolkit/lib/api/cloud-assembly/source-builder.ts
  packages/@aws-cdk/toolkit/package.json
  packages/@aws-cdk/toolkit/test/_fixtures/external-context/index.ts
  packages/@aws-cdk/toolkit/test/_fixtures/stack-with-bucket/index.js
  packages/@aws-cdk/toolkit/test/_fixtures/stack-with-bucket/index.ts
  packages/@aws-cdk/toolkit/test/_fixtures/two-empty-stacks/index.js
  packages/@aws-cdk/toolkit/test/_fixtures/two-empty-stacks/index.ts
  packages/aws-cdk-lib/cx-api/lib/cloud-assembly.ts
  packages/aws-cdk-lib/cx-api/test/cloud-assembly.test.ts
  packages/aws-cdk-lib/package.json
  packages/aws-cdk/package.json
  yarn.lock
Labels: p2, contribution/core, pr-linter/exempt-integ-test

#33036 chore: remove sumupitchayan from core contributors
  .github/workflows/github-merit-badger.yml
  .mergify.yml
Labels: p2, contribution/core

#33031 feat(s3): throw `ValidationError` instead of untyped errors
  packages/aws-cdk-lib/.eslintrc.js
  packages/aws-cdk-lib/aws-s3/lib/bucket.ts
  packages/aws-cdk-lib/aws-s3/lib/notifications-resource/notifications-resource.ts
  packages/aws-cdk-lib/aws-s3/lib/util.ts
  packages/aws-cdk-lib/core/lib/errors.ts
  packages/aws-cdk-lib/core/test/errors.test.ts
Labels: p2, contribution/core, pr-linter/exempt-readme, pr-linter/exempt-test, pr-linter/exempt-integ-test, pr/needs-maintainer-review, pr-linter/exempt-codecov

#33033 feat(lambda): throw `ValidationError` instead of untyped errors
  packages/aws-cdk-lib/.eslintrc.js
  packages/aws-cdk-lib/aws-lambda/lib/adot-layers.ts
  packages/aws-cdk-lib/aws-lambda/lib/alias.ts
  packages/aws-cdk-lib/aws-lambda/lib/code-signing-config.ts
  packages/aws-cdk-lib/aws-lambda/lib/code.ts
  packages/aws-cdk-lib/aws-lambda/lib/event-invoke-config.ts
  packages/aws-cdk-lib/aws-lambda/lib/event-source-mapping.ts
  packages/aws-cdk-lib/aws-lambda/lib/function-base.ts
  packages/aws-cdk-lib/aws-lambda/lib/function-hash.ts
  packages/aws-cdk-lib/aws-lambda/lib/function-url.ts
  packages/aws-cdk-lib/aws-lambda/lib/function.ts
  packages/aws-cdk-lib/aws-lambda/lib/lambda-insights.ts
  packages/aws-cdk-lib/aws-lambda/lib/lambda-version.ts
  packages/aws-cdk-lib/aws-lambda/lib/layers.ts
  packages/aws-cdk-lib/aws-lambda/lib/params-and-secrets-layers.ts
  packages/aws-cdk-lib/aws-lambda/lib/private/scalable-function-attribute.ts
Labels: p2, contribution/core, pr-linter/exempt-readme, pr-linter/exempt-test, pr-linter/exempt-integ-test, pr-linter/exempt-codecov

#33047 chore(glue-alpha): fix typos, inconsistencies, docs
  packages/@aws-cdk/aws-glue-alpha/README.md
  packages/@aws-cdk/aws-glue-alpha/lib/code.ts
  packages/@aws-cdk/aws-glue-alpha/lib/connection.ts
  packages/@aws-cdk/aws-glue-alpha/lib/constants.ts
  packages/@aws-cdk/aws-glue-alpha/lib/database.ts
  packages/@aws-cdk/aws-glue-alpha/lib/jobs/job.ts
  packages/@aws-cdk/aws-glue-alpha/lib/jobs/pyspark-etl-job.ts
  packages/@aws-cdk/aws-glue-alpha/lib/jobs/pyspark-flex-etl-job.ts
  packages/@aws-cdk/aws-glue-alpha/lib/jobs/pyspark-streaming-job.ts
  packages/@aws-cdk/aws-glue-alpha/lib/jobs/python-shell-job.ts
  packages/@aws-cdk/aws-glue-alpha/lib/jobs/ray-job.ts
  packages/@aws-cdk/aws-glue-alpha/lib/jobs/scala-spark-etl-job.ts
  packages/@aws-cdk/aws-glue-alpha/lib/jobs/scala-spark-flex-etl-job.ts
  packages/@aws-cdk/aws-glue-alpha/lib/jobs/scala-spark-streaming-job.ts
  packages/@aws-cdk/aws-glue-alpha/lib/jobs/spark-ui-utils.ts
  packages/@aws-cdk/aws-glue-alpha/lib/s3-table.ts
  packages/@aws-cdk/aws-glue-alpha/lib/security-configuration.ts
  packages/@aws-cdk/aws-glue-alpha/lib/triggers/trigger-options.ts
  packages/@aws-cdk/aws-glue-alpha/lib/triggers/workflow.ts
  packages/@aws-cdk/aws-glue-alpha/rosetta/default.ts-fixture
Labels: p2, contribution/core

#32927 feat(VpcV2): add BYOIP IPv6 to VPCv2
  packages/@aws-cdk/aws-ec2-alpha/README.md
  packages/@aws-cdk/aws-ec2-alpha/lib/subnet-v2.ts
  packages/@aws-cdk/aws-ec2-alpha/lib/util.ts
  packages/@aws-cdk/aws-ec2-alpha/lib/vpc-v2-base.ts
  packages/@aws-cdk/aws-ec2-alpha/lib/vpc-v2.ts
  packages/@aws-cdk/aws-ec2-alpha/test/integ.byoip-ipv6.js.snapshot/cdk.out
  packages/@aws-cdk/aws-ec2-alpha/test/integ.byoip-ipv6.js.snapshot/integ.json
  packages/@aws-cdk/aws-ec2-alpha/test/integ.byoip-ipv6.js.snapshot/integtestmodelDefaultTestDeployAssertCF40BD53.assets.json
  packages/@aws-cdk/aws-ec2-alpha/test/integ.byoip-ipv6.js.snapshot/integtestmodelDefaultTestDeployAssertCF40BD53.template.json
  packages/@aws-cdk/aws-ec2-alpha/test/integ.byoip-ipv6.js.snapshot/manifest.json
  packages/@aws-cdk/aws-ec2-alpha/test/integ.byoip-ipv6.js.snapshot/tree.json
  packages/@aws-cdk/aws-ec2-alpha/test/integ.byoip-ipv6.js.snapshot/vpc-byoip-ipv6.assets.json
  packages/@aws-cdk/aws-ec2-alpha/test/integ.byoip-ipv6.js.snapshot/vpc-byoip-ipv6.template.json
  packages/@aws-cdk/aws-ec2-alpha/test/integ.byoip-ipv6.ts
  packages/@aws-cdk/aws-ec2-alpha/test/subnet-v2.test.ts
  packages/@aws-cdk/aws-ec2-alpha/test/util.test.ts
  packages/@aws-cdk/aws-ec2-alpha/test/vpc-v2.test.ts
Labels: p2, contribution/core

#33023 docs(lambda-python-alpha): fix typos
  packages/@aws-cdk/aws-lambda-python-alpha/README.md
  packages/@aws-cdk/aws-lambda-python-alpha/lib/function.ts
Labels: p2, admired-contributor

#33029 docs(sagemaker-alpha): fix typo
  packages/@aws-cdk/aws-sagemaker-alpha/lib/scalable-instance-count.ts
Labels: p2, admired-contributor

#33009 docs(amplify-alpha): fix typo
  packages/@aws-cdk/aws-amplify-alpha/README.md
Labels: p2, admired-contributor

#33049 Revert: add project prioritization automation actions
  .github/workflows/README.md
  .github/workflows/project-prioritization-assignment.yml
  .github/workflows/project-prioritization-r2-assignment.yml
  .github/workflows/project-prioritization-r5-assignment.yml
  scripts/@aws-cdk/script-tests/prioritization/assign-priority.test.js
  scripts/@aws-cdk/script-tests/prioritization/assign-r2-priority.test.js
  scripts/@aws-cdk/script-tests/prioritization/assign-r5-priority.test.js
  scripts/@aws-cdk/script-tests/prioritization/helpers/mock-data.js
  scripts/prioritization/README.md
  scripts/prioritization/assign-priority.js
  scripts/prioritization/assign-r2-priority.js
  scripts/prioritization/assign-r5-priority.js
  scripts/prioritization/project-api.js
  scripts/prioritization/project-config.js
Labels: p2, contribution/core

#33024 docs(location-alpha): fix typos
  packages/@aws-cdk/aws-location-alpha/lib/map.ts
  packages/@aws-cdk/aws-location-alpha/test/tracker.test.ts
Labels: p2, pr/needs-community-review, admired-contributor

#33030 docs(servicecatalogappregistry-alpha): fix typo
  packages/@aws-cdk/aws-servicecatalogappregistry-alpha/lib/common.ts
Labels: p2, admired-contributor

#33048 chore(glue-alpha): fix Spark and Python versions used in Glue 5.0 JSDoc
  packages/@aws-cdk/aws-glue-alpha/lib/constants.ts
Labels: p2, distinguished-contributor

#33028 refactor(pipes-source-alpha): fix function name
  packages/@aws-cdk/aws-pipes-sources-alpha/lib/streamSource.ts
  packages/@aws-cdk/aws-pipes-sources-alpha/test/streamSource.test.ts
Labels: p2, admired-contributor

#33042 feat(rds): throw `ValidationError` instead of untyped errors
  packages/aws-cdk-lib/.eslintrc.js
  packages/aws-cdk-lib/aws-rds/lib/aurora-cluster-instance.ts
  packages/aws-cdk-lib/aws-rds/lib/cluster-engine.ts
  packages/aws-cdk-lib/aws-rds/lib/cluster.ts
  packages/aws-cdk-lib/aws-rds/lib/instance-engine.ts
  packages/aws-cdk-lib/aws-rds/lib/instance.ts
  packages/aws-cdk-lib/aws-rds/lib/option-group.ts
  packages/aws-cdk-lib/aws-rds/lib/parameter-group.ts
  packages/aws-cdk-lib/aws-rds/lib/private/util.ts
  packages/aws-cdk-lib/aws-rds/lib/proxy.ts
  packages/aws-cdk-lib/aws-rds/lib/serverless-cluster.ts
Labels: p2, contribution/core, pr-linter/exempt-readme, pr-linter/exempt-test, pr-linter/exempt-integ-test

#33045 feat(sns): throw `ValidationError` instead of untyped errors
  packages/aws-cdk-lib/.eslintrc.js
  packages/aws-cdk-lib/aws-sns/lib/subscription-filter.ts
  packages/aws-cdk-lib/aws-sns/lib/subscription.ts
  packages/aws-cdk-lib/aws-sns/lib/topic-base.ts
  packages/aws-cdk-lib/aws-sns/lib/topic.ts
Labels: p2, contribution/core, pr-linter/exempt-readme, pr-linter/exempt-test, pr-linter/exempt-integ-test

#33051 chore(cli-integ): cleanup unnecessary `AwsClients` creation
  packages/@aws-cdk-testing/cli-integ/lib/aws.ts
  packages/@aws-cdk-testing/cli-integ/lib/with-cdk-app.ts
  packages/@aws-cdk-testing/cli-integ/tests/uberpackage/uberpackage.integtest.ts
Labels: p2, contribution/core

#33065 chore(cli-integ): ensure bootstrap on cli-lib tests
  packages/@aws-cdk-testing/cli-integ/lib/with-cdk-app.ts
  packages/@aws-cdk-testing/cli-integ/lib/with-cli-lib.ts
Labels: p2, contribution/core

#33046 feat(sqs): throw `ValidationError` instead of untyped errors
  packages/aws-cdk-lib/.eslintrc.js
  packages/aws-cdk-lib/aws-sqs/lib/policy.ts
  packages/aws-cdk-lib/aws-sqs/lib/queue.ts
  packages/aws-cdk-lib/aws-sqs/lib/validate-props.ts
Labels: p2, contribution/core, pr-linter/exempt-readme, pr-linter/exempt-test, pr-linter/exempt-integ-test

#33050 chore: add project prioritization automation actions
  .github/workflows/README.md
  .github/workflows/project-prioritization-assignment.yml
  .github/workflows/project-prioritization-r2-assignment.yml
  .github/workflows/project-prioritization-r5-assignment.yml
  scripts/@aws-cdk/script-tests/prioritization/assign-priority.test.js
  scripts/@aws-cdk/script-tests/prioritization/assign-r2-priority.test.js
  scripts/@aws-cdk/script-tests/prioritization/assign-r5-priority.test.js
  scripts/@aws-cdk/script-tests/prioritization/helpers/mock-data.js
  scripts/prioritization/README.md
  scripts/prioritization/assign-priority.js
  scripts/prioritization/assign-r2-priority.js
  scripts/prioritization/assign-r5-priority.js
  scripts/prioritization/project-api.js
  scripts/prioritization/project-config.js
Labels: p2, contribution/core, pr/needs-maintainer-review

#33067 feat(ssm): throw `ValidationError` instead of untyped errors
  packages/aws-cdk-lib/.eslintrc.js
  packages/aws-cdk-lib/aws-ssm/lib/parameter.ts
  packages/aws-cdk-lib/aws-ssm/lib/util.ts
Labels: p2, contribution/core, pr-linter/exempt-readme, pr-linter/exempt-test, pr-linter/exempt-integ-test

#33057 chore: upgrade jsii-pacmak and other jsii tools to 1.106.0
  package.json
  packages/@aws-cdk/toolkit/package.json
  packages/aws-cdk/THIRD_PARTY_LICENSES
  packages/aws-cdk/package.json
  packages/awslint/package.json
  tools/@aws-cdk/cdk-build-tools/package.json
  yarn.lock
Labels: p2, contribution/core

#33073 fix: update fetchOpenPullRequests method to pass organisation in github action workflow for prioritization
  scripts/@aws-cdk/script-tests/prioritization/helpers/mock-data.js
  scripts/prioritization/assign-r2-priority.js
  scripts/prioritization/assign-r5-priority.js
  scripts/prioritization/project-api.js
Labels: p2, contribution/core, pr-linter/exempt-integ-test

#33079 feat(synthetics): throw `ValidationError` instead of untyped errors
  packages/aws-cdk-lib/.eslintrc.js
  packages/aws-cdk-lib/aws-synthetics/lib/canary.ts
  packages/aws-cdk-lib/aws-synthetics/lib/code.ts
  packages/aws-cdk-lib/aws-synthetics/lib/schedule.ts
Labels: p2, contribution/core, pr-linter/exempt-readme, pr-linter/exempt-test, pr-linter/exempt-integ-test

#33092 chore: add integ test that validates full proxy traversal
  packages/@aws-cdk-testing/cli-integ/lib/package-sources/release-source.ts
  packages/@aws-cdk-testing/cli-integ/lib/package-sources/repo-source.ts
  packages/@aws-cdk-testing/cli-integ/lib/proxy.ts
  packages/@aws-cdk-testing/cli-integ/lib/with-cdk-app.ts
  packages/@aws-cdk-testing/cli-integ/tests/cli-integ-tests/cli.integtest.ts
  packages/@aws-cdk-testing/cli-integ/tests/cli-integ-tests/proxy.integtest.ts
  packages/@aws-cdk-testing/cli-integ/tsconfig.json
Labels: p2, contribution/core
