Repository aws/aws-cdk, pull requests merged in 2025-05, with the labels that each got.

#34320 chore: update Contributors File
  CONTRIBUTORS.md
Labels: p2, auto-approve

#34278 feat: update L1 CloudFormation resource definitions
  packages/aws-cdk-lib/package.json
  tools/@aws-cdk/spec2cdk/package.json
  yarn.lock
Labels: p2, dependencies, contribution/core, pr-linter/exempt-readme, pr-linter/exempt-test, pr-linter/exempt-integ-test, pr/needs-maintainer-review

#34158 chore: refactored security guardian tool and security-guardian action. Enables local run.
  .github/workflows/security-guardian.yml
  tools/@aws-cdk/security-guardian/README.md
  tools/@aws-cdk/security-guardian/package-lock.json
  tools/@aws-cdk/security-guardian/package.json
  tools/@aws-cdk/security-guardian/rules/trust_scope_rules.guard
  tools/@aws-cdk/security-guardian/src/check-intrinsics.ts
  tools/@aws-cdk/security-guardian/src/get-changed-files.ts
  tools/@aws-cdk/security-guardian/src/index.ts
  tools/@aws-cdk/security-guardian/test/templates/CMCMK-Stack.template.json
  tools/@aws-cdk/security-guardian/test/test.sh
Labels: p2, contribution/core, pr/needs-maintainer-review

#34334 chore: security-guardian cfn-guard rule with updated rule scenarios
  tools/@aws-cdk/security-guardian/rules/trust_scope_rules.guard
Labels: p2, contribution/core

#34339 chore(merge-back): 2.194.0
  CHANGELOG.v2.alpha.md
  CHANGELOG.v2.md
  version.v2.json
Labels: p2, pr/needs-community-review, pr/no-squash, auto-approve

#34340 chore(rds): add MySQL 8.0.42 and 8.4.5, Aurora Postgres 17.4 and deprecate 16.5, 17.1, 17.2
  packages/aws-cdk-lib/aws-rds/lib/cluster-engine.ts
  packages/aws-cdk-lib/aws-rds/lib/instance-engine.ts
Labels: p2, star-contributor, pr/needs-maintainer-review

#34258 chore(ec2): add c8gd, m8gd, and r8gd instance classes
  packages/aws-cdk-lib/aws-ec2/lib/instance-types.ts
Labels: p2, admired-contributor, pr-linter/exemption-requested

#34310 chore(enum-updater): fix issue with exclusion mechanism + add README
  tools/@aws-cdk/construct-metadata-updater/README.md
  tools/@aws-cdk/enum-updater/README.md
  tools/@aws-cdk/enum-updater/lib/exclude-values.json
  tools/@aws-cdk/enum-updater/lib/missing-enum-updater.ts
  tools/@aws-cdk/enum-updater/lib/static-enum-mapping-updater.ts
  tools/@aws-cdk/enum-updater/test/missing-enum-updater.test.ts
  tools/@aws-cdk/enum-updater/test/static-enum-mapping-updater.test.ts
Labels: p2, contribution/core

#34326 chore(opensearchservice): add new OpenSearch version 2.19
  packages/aws-cdk-lib/aws-opensearchservice/lib/version.ts
  packages/aws-cdk-lib/aws-opensearchservice/test/domain.test.ts
Labels: p2, star-contributor

#34291 chore(bedrock): add Writer's Palmyra X4/X5, Llama 4 Scout 17B/Maverick 17B, and Amazon Nova Premier
  packages/aws-cdk-lib/aws-bedrock/lib/foundation-model.ts
Labels: p2, distinguished-contributor

#34353 fix(amplify-alpha): example code for adding a custom rule is wrong
  packages/@aws-cdk/aws-amplify-alpha/README.md
Labels: p2, effort/small, contribution/core, pr-linter/exempt-test, pr-linter/exempt-integ-test

#34236 chore: update bug and feature request templates
  .github/ISSUE_TEMPLATE/bug-report.yml
  .github/ISSUE_TEMPLATE/feature-request.yml
Labels: p2, contribution/core, beginning-contributor

#34267 fix(codepipeline): allow both `pullRequestFilter` and `pushFilter`
  packages/@aws-cdk-testing/framework-integ/test/aws-codepipeline-actions/test/integ.pipeline-with-pipeline-triggers.js.snapshot/aws-cdk-codepipeline-with-pipeline-triggers.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-codepipeline-actions/test/integ.pipeline-with-pipeline-triggers.js.snapshot/aws-cdk-codepipeline-with-pipeline-triggers.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-codepipeline-actions/test/integ.pipeline-with-pipeline-triggers.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-codepipeline-actions/test/integ.pipeline-with-pipeline-triggers.js.snapshot/codepipelinewithpipelinetriggerstestDefaultTestDeployAssertE3F8DDE6.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-codepipeline-actions/test/integ.pipeline-with-pipeline-triggers.js.snapshot/codepipelinewithpipelinetriggerstestDefaultTestDeployAssertE3F8DDE6.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-codepipeline-actions/test/integ.pipeline-with-pipeline-triggers.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-codepipeline-actions/test/integ.pipeline-with-pipeline-triggers.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-codepipeline-actions/test/integ.pipeline-with-pipeline-triggers.ts
  packages/aws-cdk-lib/aws-codepipeline/lib/private/validation.ts
  packages/aws-cdk-lib/aws-codepipeline/test/triggers.test.ts
Labels: bug, p1, effort/medium, admired-contributor, pr/needs-maintainer-review

#32733 feat(location): support L2 API Key Construct
  packages/@aws-cdk/aws-location-alpha/README.md
  packages/@aws-cdk/aws-location-alpha/lib/api-key.ts
  packages/@aws-cdk/aws-location-alpha/lib/index.ts
  packages/@aws-cdk/aws-location-alpha/test/api-key.test.ts
  packages/@aws-cdk/aws-location-alpha/test/integ.api-key.js.snapshot/ApiKeyTestDefaultTestDeployAssert140AB0A3.assets.json
  packages/@aws-cdk/aws-location-alpha/test/integ.api-key.js.snapshot/ApiKeyTestDefaultTestDeployAssert140AB0A3.template.json
  packages/@aws-cdk/aws-location-alpha/test/integ.api-key.js.snapshot/cdk-integ-location-api-key.assets.json
  packages/@aws-cdk/aws-location-alpha/test/integ.api-key.js.snapshot/cdk-integ-location-api-key.template.json
  packages/@aws-cdk/aws-location-alpha/test/integ.api-key.js.snapshot/cdk.out
  packages/@aws-cdk/aws-location-alpha/test/integ.api-key.js.snapshot/integ.json
  packages/@aws-cdk/aws-location-alpha/test/integ.api-key.js.snapshot/manifest.json
  packages/@aws-cdk/aws-location-alpha/test/integ.api-key.js.snapshot/tree.json
  packages/@aws-cdk/aws-location-alpha/test/integ.api-key.ts
Labels: p2, feature-request, effort/small, pr/needs-community-review, distinguished-contributor

#34328 chore: make all L2 Constructs property injectable during release
  tools/@aws-cdk/construct-metadata-updater/README.md
  tools/@aws-cdk/construct-metadata-updater/lib/metadata-updater.ts
  tools/@aws-cdk/construct-metadata-updater/test/metadata-updater.test.ts
Labels: p2, pr/needs-community-review, beginning-contributor

#34364 feat: publish 'app-staging-synthesizer-alpha' for Go
  packages/@aws-cdk/app-staging-synthesizer-alpha/package.json
Labels: p2, contribution/core, pr-linter/exempt-readme, pr-linter/exempt-test, pr-linter/exempt-integ-test

#34355 refactor(trace): simplify how construct traces get built
  packages/aws-cdk-lib/core/lib/private/tree-metadata.ts
  packages/aws-cdk-lib/core/lib/validation/private/construct-tree.ts
  packages/aws-cdk-lib/core/lib/validation/private/report.ts
  packages/aws-cdk-lib/core/lib/validation/private/trace.ts
Labels: p2, contribution/core, pr-linter/exempt-codecov

#34122 fix(route53-targets): beanstalk allow specifying `hostedZoneId` to support token endpoint with default value derived from stack region or endpointUrl
  packages/@aws-cdk-testing/framework-integ/test/aws-route53-targets/test/integ.elastic-beanstalk-hostedzoneid.js.snapshot/asset.695130a6c8132c255e833e84e8482a4a144a4a1261c979bd7e3cb7b8258e8876/index.js
  packages/@aws-cdk-testing/framework-integ/test/aws-route53-targets/test/integ.elastic-beanstalk-hostedzoneid.js.snapshot/cdk-route53-ebs-hostedzoneid-integ.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-route53-targets/test/integ.elastic-beanstalk-hostedzoneid.js.snapshot/cdk-route53-ebs-hostedzoneid-integ.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-route53-targets/test/integ.elastic-beanstalk-hostedzoneid.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-route53-targets/test/integ.elastic-beanstalk-hostedzoneid.js.snapshot/cdkroute53ebshostedzoneidintegtestDefaultTestDeployAssert57827FC3.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-route53-targets/test/integ.elastic-beanstalk-hostedzoneid.js.snapshot/cdkroute53ebshostedzoneidintegtestDefaultTestDeployAssert57827FC3.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-route53-targets/test/integ.elastic-beanstalk-hostedzoneid.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-route53-targets/test/integ.elastic-beanstalk-hostedzoneid.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-route53-targets/test/integ.elastic-beanstalk-hostedzoneid.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-route53-targets/test/integ.elastic-beanstalk-hostedzoneid.ts
  packages/@aws-cdk-testing/framework-integ/test/aws-route53-targets/test/integ.elastic-beanstalk-token-endpoint.js.snapshot/asset.695130a6c8132c255e833e84e8482a4a144a4a1261c979bd7e3cb7b8258e8876/index.js
  packages/@aws-cdk-testing/framework-integ/test/aws-route53-targets/test/integ.elastic-beanstalk-token-endpoint.js.snapshot/cdk-route53-ebs-token-endpoint-integ.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-route53-targets/test/integ.elastic-beanstalk-token-endpoint.js.snapshot/cdk-route53-ebs-token-endpoint-integ.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-route53-targets/test/integ.elastic-beanstalk-token-endpoint.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-route53-targets/test/integ.elastic-beanstalk-token-endpoint.js.snapshot/cdkroute53ebstokenendpointintegtestDefaultTestDeployAssertEE10A2D8.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-route53-targets/test/integ.elastic-beanstalk-token-endpoint.js.snapshot/cdkroute53ebstokenendpointintegtestDefaultTestDeployAssertEE10A2D8.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-route53-targets/test/integ.elastic-beanstalk-token-endpoint.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-route53-targets/test/integ.elastic-beanstalk-token-endpoint.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-route53-targets/test/integ.elastic-beanstalk-token-endpoint.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-route53-targets/test/integ.elastic-beanstalk-token-endpoint.ts
  packages/aws-cdk-lib/aws-route53-targets/README.md
  packages/aws-cdk-lib/aws-route53-targets/lib/elastic-beanstalk-environment-target.ts
  packages/aws-cdk-lib/aws-route53-targets/lib/shared.ts
  packages/aws-cdk-lib/aws-route53-targets/test/elastic-beanstalk-environment-target.test.ts
Labels: bug, p1, effort/medium, admired-contributor, pr/needs-maintainer-review

#33816 feat(iot): device certificate age check audit configuration
  packages/@aws-cdk/aws-iot-alpha/README.md
  packages/@aws-cdk/aws-iot-alpha/lib/audit-configuration.ts
  packages/@aws-cdk/aws-iot-alpha/test/audit-configuration.test.ts
  packages/@aws-cdk/aws-iot-alpha/test/integ.audit-configuration.js.snapshot/IotAuditConfigurationTestDefaultTestDeployAssert6A603D00.assets.json
  packages/@aws-cdk/aws-iot-alpha/test/integ.audit-configuration.js.snapshot/IotAuditConfigurationTestStack.assets.json
  packages/@aws-cdk/aws-iot-alpha/test/integ.audit-configuration.js.snapshot/IotAuditConfigurationTestStack.template.json
  packages/@aws-cdk/aws-iot-alpha/test/integ.audit-configuration.js.snapshot/cdk.out
  packages/@aws-cdk/aws-iot-alpha/test/integ.audit-configuration.js.snapshot/integ.json
  packages/@aws-cdk/aws-iot-alpha/test/integ.audit-configuration.js.snapshot/manifest.json
  packages/@aws-cdk/aws-iot-alpha/test/integ.audit-configuration.js.snapshot/tree.json
  packages/@aws-cdk/aws-iot-alpha/test/integ.audit-configuration.ts
Labels: p2, distinguished-contributor, pr/needs-maintainer-review

#34371 revert: "chore: make all L2 Constructs property injectable during release"
  tools/@aws-cdk/construct-metadata-updater/README.md
  tools/@aws-cdk/construct-metadata-updater/lib/metadata-updater.ts
  tools/@aws-cdk/construct-metadata-updater/test/metadata-updater.test.ts
Labels: p2, contribution/core

#33858 fix(s3-notifications): add a key policy to trust S3 for notifications to an SNS topic encrypted with a KMS key (under feature flag)
  packages/@aws-cdk-testing/framework-integ/test/aws-s3-notifications/test/sns/integ.encrypted-sns-bucket-notifications.js.snapshot/SnsBucketNotificationsSseIntegDefaultTestDeployAssertDBC1BF57.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-s3-notifications/test/sns/integ.encrypted-sns-bucket-notifications.js.snapshot/SnsBucketNotificationsSseIntegDefaultTestDeployAssertDBC1BF57.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-s3-notifications/test/sns/integ.encrypted-sns-bucket-notifications.js.snapshot/SnsBucketNotificationsStack.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-s3-notifications/test/sns/integ.encrypted-sns-bucket-notifications.js.snapshot/SnsBucketNotificationsStack.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-s3-notifications/test/sns/integ.encrypted-sns-bucket-notifications.js.snapshot/asset.44e9c4d7a5d3fd2d677e1a7e416b2b56f6b0104bd5eff9cac5557b4c65a9dc61/index.js
  packages/@aws-cdk-testing/framework-integ/test/aws-s3-notifications/test/sns/integ.encrypted-sns-bucket-notifications.js.snapshot/asset.5b7ddd1e0b18514d45c25a44b162f82431b091da093fb35e4b814bbba093c506.bundle/index.js
  packages/@aws-cdk-testing/framework-integ/test/aws-s3-notifications/test/sns/integ.encrypted-sns-bucket-notifications.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-s3-notifications/test/sns/integ.encrypted-sns-bucket-notifications.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-s3-notifications/test/sns/integ.encrypted-sns-bucket-notifications.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-s3-notifications/test/sns/integ.encrypted-sns-bucket-notifications.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-s3-notifications/test/sns/integ.encrypted-sns-bucket-notifications.ts
  packages/aws-cdk-lib/aws-s3-notifications/lib/sns.ts
  packages/aws-cdk-lib/aws-s3-notifications/test/sns.test.ts
  packages/aws-cdk-lib/aws-s3/lib/notifications-resource/notifications-resource.ts
  packages/aws-cdk-lib/cx-api/FEATURE_FLAGS.md
  packages/aws-cdk-lib/cx-api/lib/features.ts
  packages/aws-cdk-lib/recommended-feature-flags.json
Labels: p1, feature-request, distinguished-contributor, needs-security-review

#34366 chore: add new team member aemada-aws to mergify configs
  .github/workflows/github-merit-badger.yml
  .mergify.yml
Labels: p2, pr/needs-community-review, beginning-contributor

#34357 feat: update L1 CloudFormation resource definitions
  packages/aws-cdk-lib/aws-ssmguiconnect/.jsiirc.json
  packages/aws-cdk-lib/aws-ssmguiconnect/README.md
  packages/aws-cdk-lib/aws-ssmguiconnect/index.ts
  packages/aws-cdk-lib/aws-ssmguiconnect/lib/index.ts
  packages/aws-cdk-lib/index.ts
  packages/aws-cdk-lib/package.json
  packages/aws-cdk-lib/scripts/scope-map.json
  tools/@aws-cdk/spec2cdk/package.json
  yarn.lock
Labels: p2, dependencies, contribution/core, pr-linter/exempt-readme, pr-linter/exempt-test, pr-linter/exempt-integ-test

#34369 chore: upgrade `@aws-cdk/cloud-assembly-schema` to v41.2.0
  packages/@aws-cdk/cx-api/package.json
  packages/@aws-cdk/integ-tests-alpha/test/manifest-synthesizer.test.ts
  packages/@aws-cdk/integ-tests-alpha/test/manifest-writer.test.ts
  packages/aws-cdk-lib/core/test/synthesis.test.ts
  packages/aws-cdk-lib/cx-api/test/cloud-assembly-builder.test.ts
  packages/aws-cdk-lib/package.json
  yarn.lock
Labels: p2, contribution/core

#34373 chore: add new team member `astiwana`
  .github/workflows/github-merit-badger.yml
  .mergify.yml
Labels: p2, beginning-contributor

#34375 chore: add a new team member maharajhaider
  .github/workflows/github-merit-badger.yml
  .mergify.yml
Labels: p2, pr/needs-community-review, beginning-contributor

#34380 chore: add new team members
  .github/workflows/github-merit-badger.yml
  .mergify.yml
Labels: p2, beginning-contributor

#34111 feat(apigatewayv2): add dualstack support to domain name
  packages/@aws-cdk-testing/framework-integ/test/aws-apigatewayv2/test/http/integ.api-domain-name.js.snapshot/aws-cdk-aws-apigatewayv2-domain-name.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-apigatewayv2/test/http/integ.api-domain-name.js.snapshot/aws-cdk-aws-apigatewayv2-domain-name.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-apigatewayv2/test/http/integ.api-domain-name.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-apigatewayv2/test/http/integ.api-domain-name.js.snapshot/httpapiDefaultTestDeployAssert77633A40.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-apigatewayv2/test/http/integ.api-domain-name.js.snapshot/httpapiDefaultTestDeployAssert77633A40.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-apigatewayv2/test/http/integ.api-domain-name.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-apigatewayv2/test/http/integ.api-domain-name.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-apigatewayv2/test/http/integ.api-domain-name.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-apigatewayv2/test/http/integ.api-domain-name.ts
  packages/aws-cdk-lib/aws-apigatewayv2/README.md
  packages/aws-cdk-lib/aws-apigatewayv2/lib/common/domain-name.ts
  packages/aws-cdk-lib/aws-apigatewayv2/test/http/domain-name.test.ts
Labels: p2, star-contributor

#34254 feat(synthetics): add 5.0 and 5.1 python canary runtimes
  packages/@aws-cdk-testing/framework-integ/test/aws-synthetics/test/integ.canary.js.snapshot/IntegCanaryTestDefaultTestDeployAssert3AD5A094.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-synthetics/test/integ.canary.js.snapshot/IntegCanaryTestDefaultTestDeployAssert3AD5A094.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-synthetics/test/integ.canary.js.snapshot/asset.5b7ddd1e0b18514d45c25a44b162f82431b091da093fb35e4b814bbba093c506.bundle/index.js
  packages/@aws-cdk-testing/framework-integ/test/aws-synthetics/test/integ.canary.js.snapshot/asset.b1b777dcb79a2fa2790059927207d10bf5f4747d6dd1516e2780726d9d6fa820.zip
  packages/@aws-cdk-testing/framework-integ/test/aws-synthetics/test/integ.canary.js.snapshot/canary-one.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-synthetics/test/integ.canary.js.snapshot/canary-one.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-synthetics/test/integ.canary.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-synthetics/test/integ.canary.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-synthetics/test/integ.canary.ts
  packages/aws-cdk-lib/aws-synthetics/lib/runtime.ts
  packages/aws-cdk-lib/aws-synthetics/test/canary.test.ts
Labels: p2, feature-request, effort/small, pr-linter/exempt-readme, beginning-contributor, pr/needs-maintainer-review

#34386 chore(security-guardian): security-guardian to skip release pr
  .github/workflows/security-guardian.yml
Labels: p2, contribution/core

#34388 chore(merge-back): 2.195.0
  CHANGELOG.v2.alpha.md
  CHANGELOG.v2.md
  packages/@aws-cdk/aws-location-alpha/lib/api-key.ts
  packages/aws-cdk-lib/core/lib/analytics-data-source/classes.ts
  packages/aws-cdk-lib/core/lib/analytics-data-source/enums.ts
  packages/aws-cdk-lib/core/lib/analytics-data-source/enums/module-enumlikes.json
  packages/aws-cdk-lib/core/lib/analytics-data-source/enums/module-enums.json
  packages/aws-cdk-lib/cx-api/FEATURE_FLAGS.md
  packages/aws-cdk-lib/cx-api/lib/features.ts
  version.v2.json
Labels: p2, pr/needs-community-review, pr/no-squash, auto-approve

#34395 chore: exclude `@aws-cdk/asset-awscli-v1` from auto upgrading
  .github/workflows/yarn-upgrade.yml
Labels: p2, contribution/core, pr/needs-maintainer-review

#34231 feat: support healthCheckGracePeriod in QueueProcessingFargateService
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs-patterns/test/fargate/integ.queue-processing-fargate-service-grace-period.js.snapshot/asset.205c5d917605ee59cc93dc29526bc4f73b315ae613cdfbc52b8179f388041a03/Dockerfile
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs-patterns/test/fargate/integ.queue-processing-fargate-service-grace-period.js.snapshot/asset.205c5d917605ee59cc93dc29526bc4f73b315ae613cdfbc52b8179f388041a03/index.py
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs-patterns/test/fargate/integ.queue-processing-fargate-service-grace-period.js.snapshot/aws-ecs-patterns-queue-grace-period.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs-patterns/test/fargate/integ.queue-processing-fargate-service-grace-period.js.snapshot/aws-ecs-patterns-queue-grace-period.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs-patterns/test/fargate/integ.queue-processing-fargate-service-grace-period.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs-patterns/test/fargate/integ.queue-processing-fargate-service-grace-period.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs-patterns/test/fargate/integ.queue-processing-fargate-service-grace-period.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs-patterns/test/fargate/integ.queue-processing-fargate-service-grace-period.js.snapshot/queueProcessingFargateServiceGracePeriodTestDefaultTestDeployAssert2CA06C1B.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs-patterns/test/fargate/integ.queue-processing-fargate-service-grace-period.js.snapshot/queueProcessingFargateServiceGracePeriodTestDefaultTestDeployAssert2CA06C1B.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs-patterns/test/fargate/integ.queue-processing-fargate-service-grace-period.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs-patterns/test/fargate/integ.queue-processing-fargate-service-grace-period.ts
  packages/aws-cdk-lib/aws-ecs-patterns/README.md
  packages/aws-cdk-lib/aws-ecs-patterns/lib/fargate/queue-processing-fargate-service.ts
  packages/aws-cdk-lib/aws-ecs-patterns/test/fargate/queue-processing-fargate-service.test.ts
Labels: p2, feature-request, pr/needs-community-review, effort/medium, beginning-contributor

#34399 chore: pin `asset-awscli-v1` version
  packages/aws-cdk-lib/package.json
  yarn.lock
Labels: p2, contribution/core, pr/needs-maintainer-review

#34378 chore: npm-check-updates && yarn upgrade
  package.json
  packages/@aws-cdk-testing/framework-integ/package.json
  packages/@aws-cdk/app-staging-synthesizer-alpha/package.json
  packages/@aws-cdk/aws-amplify-alpha/package.json
  packages/@aws-cdk/aws-applicationsignals-alpha/package.json
  packages/@aws-cdk/aws-apprunner-alpha/package.json
  packages/@aws-cdk/aws-cloud9-alpha/package.json
  packages/@aws-cdk/aws-codestar-alpha/package.json
  packages/@aws-cdk/aws-ec2-alpha/package.json
  packages/@aws-cdk/aws-eks-v2-alpha/package.json
  packages/@aws-cdk/aws-gamelift-alpha/package.json
  packages/@aws-cdk/aws-glue-alpha/package.json
  packages/@aws-cdk/aws-iot-actions-alpha/package.json
  packages/@aws-cdk/aws-iot-alpha/package.json
  packages/@aws-cdk/aws-iotevents-actions-alpha/package.json
  packages/@aws-cdk/aws-iotevents-alpha/package.json
  packages/@aws-cdk/aws-ivs-alpha/package.json
  packages/@aws-cdk/aws-kinesisanalytics-flink-alpha/package.json
  packages/@aws-cdk/aws-lambda-go-alpha/package.json
  packages/@aws-cdk/aws-lambda-python-alpha/package.json
  packages/@aws-cdk/aws-location-alpha/package.json
  packages/@aws-cdk/aws-msk-alpha/package.json
  packages/@aws-cdk/aws-neptune-alpha/package.json
  packages/@aws-cdk/aws-pipes-alpha/package.json
  packages/@aws-cdk/aws-pipes-enrichments-alpha/package.json
  packages/@aws-cdk/aws-pipes-sources-alpha/package.json
  packages/@aws-cdk/aws-pipes-targets-alpha/package.json
  packages/@aws-cdk/aws-redshift-alpha/package.json
  packages/@aws-cdk/aws-route53resolver-alpha/package.json
  packages/@aws-cdk/aws-s3objectlambda-alpha/package.json
  packages/@aws-cdk/aws-sagemaker-alpha/package.json
  packages/@aws-cdk/aws-servicecatalogappregistry-alpha/package.json
  packages/@aws-cdk/custom-resource-handlers/package.json
  packages/@aws-cdk/example-construct-library/package.json
  packages/@aws-cdk/integ-tests-alpha/package.json
  packages/aws-cdk-lib/package.json
  packages/awslint/package.json
  tools/@aws-cdk/cdk-build-tools/package.json
  tools/@aws-cdk/construct-metadata-updater/package.json
  tools/@aws-cdk/lambda-integration-test-updater/package.json
  tools/@aws-cdk/lazify/package.json
  tools/@aws-cdk/node-bundle/package.json
  yarn.lock
Labels: p2, dependencies, contribution/core, auto-approve

#34409 chore(enum-updater): exclude none enum value for appsync AppSyncDataSourceType enum
  tools/@aws-cdk/enum-updater/lib/exclude-values.json
Labels: p2, contribution/core

#34298 feat(elasticloadbalancingv2): add support for multi-value headers in Lambda target groups
  packages/@aws-cdk-testing/framework-integ/test/aws-elasticloadbalancingv2/test/integ.alb-lambda-multi-value-headers.js.snapshot/aws-cdk-elbv2-lambda-multi-value-headers.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-elasticloadbalancingv2/test/integ.alb-lambda-multi-value-headers.js.snapshot/aws-cdk-elbv2-lambda-multi-value-headers.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-elasticloadbalancingv2/test/integ.alb-lambda-multi-value-headers.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-elasticloadbalancingv2/test/integ.alb-lambda-multi-value-headers.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-elasticloadbalancingv2/test/integ.alb-lambda-multi-value-headers.js.snapshot/integalblambdamultivalueheadersDefaultTestDeployAssert1FE62314.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-elasticloadbalancingv2/test/integ.alb-lambda-multi-value-headers.js.snapshot/integalblambdamultivalueheadersDefaultTestDeployAssert1FE62314.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-elasticloadbalancingv2/test/integ.alb-lambda-multi-value-headers.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-elasticloadbalancingv2/test/integ.alb-lambda-multi-value-headers.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-elasticloadbalancingv2/test/integ.alb-lambda-multi-value-headers.ts
  packages/aws-cdk-lib/aws-elasticloadbalancingv2/README.md
  packages/aws-cdk-lib/aws-elasticloadbalancingv2/lib/alb/application-target-group.ts
  packages/aws-cdk-lib/aws-elasticloadbalancingv2/test/alb/target-group.test.ts
Labels: p2, beginning-contributor

#34229 feat(s3tables): server-side encryption by customer managed KMS key
  packages/@aws-cdk/aws-s3tables-alpha/README.md
  packages/@aws-cdk/aws-s3tables-alpha/lib/table-bucket.ts
  packages/@aws-cdk/aws-s3tables-alpha/rosetta/default.ts-fixture
  packages/@aws-cdk/aws-s3tables-alpha/test/integration/integ.table-bucket-kms-key.js.snapshot/cdk.out
  packages/@aws-cdk/aws-s3tables-alpha/test/integration/integ.table-bucket-kms-key.js.snapshot/integ.json
  packages/@aws-cdk/aws-s3tables-alpha/test/integration/integ.table-bucket-kms-key.js.snapshot/kms-key-s3tables-stack.assets.json
  packages/@aws-cdk/aws-s3tables-alpha/test/integration/integ.table-bucket-kms-key.js.snapshot/kms-key-s3tables-stack.template.json
  packages/@aws-cdk/aws-s3tables-alpha/test/integration/integ.table-bucket-kms-key.js.snapshot/kmskeys3tablesintegDefaultTestDeployAssertC8AB8C4E.assets.json
  packages/@aws-cdk/aws-s3tables-alpha/test/integration/integ.table-bucket-kms-key.js.snapshot/kmskeys3tablesintegDefaultTestDeployAssertC8AB8C4E.template.json
  packages/@aws-cdk/aws-s3tables-alpha/test/integration/integ.table-bucket-kms-key.js.snapshot/manifest.json
  packages/@aws-cdk/aws-s3tables-alpha/test/integration/integ.table-bucket-kms-key.js.snapshot/tree.json
  packages/@aws-cdk/aws-s3tables-alpha/test/integration/integ.table-bucket-kms-key.ts
  packages/@aws-cdk/aws-s3tables-alpha/test/table-bucket.test.ts
Labels: p2, distinguished-contributor, pr/needs-maintainer-review

#34412 chore(enum-updater): exclude `CUSTOM_INSTANCE_TYPE` from codebuild `ComputeType` enum
  tools/@aws-cdk/enum-updater/lib/exclude-values.json
Labels: p2, contribution/core

#34417 chore: scope down pr-linter-exemption-labeler workflow permissions
  .github/workflows/pr-linter-exemption-labeler.yml
Labels: p2, contribution/core

#34420 chore(aws-cdk-lib): declare where no-throw-default-error is not yet supported
  packages/aws-cdk-lib/.eslintrc.js
Labels: p2, contribution/core, pr/needs-maintainer-review

#34301 feat(route53): add cidrRoutingConfig property
  packages/@aws-cdk-testing/framework-integ/test/aws-route53/test/integ.cidr-routing-config.js.snapshot/CidrRoutingConfig.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-route53/test/integ.cidr-routing-config.js.snapshot/CidrRoutingConfig.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-route53/test/integ.cidr-routing-config.js.snapshot/CidrRoutingConfigIntegDefaultTestDeployAssert2D4BBAED.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-route53/test/integ.cidr-routing-config.js.snapshot/CidrRoutingConfigIntegDefaultTestDeployAssert2D4BBAED.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-route53/test/integ.cidr-routing-config.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-route53/test/integ.cidr-routing-config.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-route53/test/integ.cidr-routing-config.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-route53/test/integ.cidr-routing-config.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-route53/test/integ.cidr-routing-config.ts
  packages/aws-cdk-lib/aws-route53/README.md
  packages/aws-cdk-lib/aws-route53/lib/cidr-routing-config.ts
  packages/aws-cdk-lib/aws-route53/lib/index.ts
  packages/aws-cdk-lib/aws-route53/lib/record-set.ts
  packages/aws-cdk-lib/aws-route53/test/cidr-routing-config.test.ts
  packages/aws-cdk-lib/aws-route53/test/record-set.test.ts
Labels: p2, valued-contributor, pr/needs-maintainer-review

#34428 feat(eks): throw `ValidationError`s instead of untyped errors
  packages/aws-cdk-lib/.eslintrc.js
  packages/aws-cdk-lib/aws-eks/lib/aws-auth.ts
  packages/aws-cdk-lib/aws-eks/lib/cluster-resource.ts
  packages/aws-cdk-lib/aws-eks/lib/cluster.ts
  packages/aws-cdk-lib/aws-eks/lib/fargate-profile.ts
  packages/aws-cdk-lib/aws-eks/lib/helm-chart.ts
  packages/aws-cdk-lib/aws-eks/lib/kubectl-provider.ts
  packages/aws-cdk-lib/aws-eks/lib/managed-nodegroup.ts
Labels: p2, contribution/core, pr-linter/exempt-readme, pr-linter/exempt-test, pr-linter/exempt-integ-test

#34431 feat(kms): throw `ValidationError`s instead of untyped errors
  packages/aws-cdk-lib/.eslintrc.js
  packages/aws-cdk-lib/aws-kms/lib/alias.ts
  packages/aws-cdk-lib/aws-kms/lib/key.ts
Labels: p2, contribution/core, pr-linter/exempt-readme, pr-linter/exempt-test, pr-linter/exempt-integ-test

#34432 feat(opensearchservice): throw `ValidationError`s instead of untyped errors
  packages/aws-cdk-lib/.eslintrc.js
  packages/aws-cdk-lib/aws-opensearchservice/lib/domain.ts
Labels: p2, contribution/core, pr-linter/exempt-readme, pr-linter/exempt-test, pr-linter/exempt-integ-test

#34435 feat(servicediscovery): throw `ValidationError`s instead of untyped errors
  packages/aws-cdk-lib/.eslintrc.js
  packages/aws-cdk-lib/aws-servicediscovery/lib/alias-target-instance.ts
  packages/aws-cdk-lib/aws-servicediscovery/lib/cname-instance.ts
  packages/aws-cdk-lib/aws-servicediscovery/lib/ip-instance.ts
  packages/aws-cdk-lib/aws-servicediscovery/lib/non-ip-instance.ts
  packages/aws-cdk-lib/aws-servicediscovery/lib/private-dns-namespace.ts
  packages/aws-cdk-lib/aws-servicediscovery/lib/service.ts
Labels: p2, contribution/core, pr-linter/exempt-readme, pr-linter/exempt-test, pr-linter/exempt-integ-test

#34430 feat(events-targets): throw `ValidationError`s instead of untyped errors
  packages/aws-cdk-lib/.eslintrc.js
  packages/aws-cdk-lib/aws-events-targets/lib/api-gateway.ts
  packages/aws-cdk-lib/aws-events-targets/lib/api-gatewayv2.ts
  packages/aws-cdk-lib/aws-events-targets/lib/appsync.ts
  packages/aws-cdk-lib/aws-events-targets/lib/batch.ts
  packages/aws-cdk-lib/aws-events-targets/lib/ecs-task.ts
  packages/aws-cdk-lib/aws-events-targets/lib/log-group.ts
  packages/aws-cdk-lib/aws-events-targets/lib/redshift-query.ts
  packages/aws-cdk-lib/aws-events-targets/lib/sqs.ts
  packages/aws-cdk-lib/aws-events-targets/lib/util.ts
Labels: p2, contribution/core, pr-linter/exempt-readme, pr-linter/exempt-test, pr-linter/exempt-integ-test

#34415 chore: new GH workflow for upgrading dependencies that require manual intervention
  .github/workflows/README.md
  .github/workflows/yarn-upgrade-need-manual-work.yml
Labels: p2, contribution/core

#33702 fix(s3): updating blockPublicAccess to enable default true settings (under feature flag)
  packages/@aws-cdk-testing/framework-integ/test/aws-s3/test/integ.bucket-block-access.js.snapshot/aws-cdk-s3-bucket-block-access.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-s3/test/integ.bucket-block-access.js.snapshot/aws-cdk-s3-bucket-block-access.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-s3/test/integ.bucket-block-access.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-s3/test/integ.bucket-block-access.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-s3/test/integ.bucket-block-access.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-s3/test/integ.bucket-block-access.js.snapshot/testBlockingBucketAccessDefaultTestDeployAssert2F4ACAD8.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-s3/test/integ.bucket-block-access.js.snapshot/testBlockingBucketAccessDefaultTestDeployAssert2F4ACAD8.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-s3/test/integ.bucket-block-access.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-s3/test/integ.bucket-block-access.ts
  packages/aws-cdk-lib/aws-s3/README.md
  packages/aws-cdk-lib/aws-s3/lib/bucket.ts
  packages/aws-cdk-lib/aws-s3/test/bucket.test.ts
  packages/aws-cdk-lib/cx-api/FEATURE_FLAGS.md
  packages/aws-cdk-lib/cx-api/README.md
  packages/aws-cdk-lib/cx-api/lib/features.ts
  packages/aws-cdk-lib/recommended-feature-flags.json
Labels: bug, p2, effort/small, pr/needs-community-review, repeat-contributor

#34159 feat(pipes-targets): add SNS
  packages/@aws-cdk/aws-pipes-targets-alpha/README.md
  packages/@aws-cdk/aws-pipes-targets-alpha/lib/index.ts
  packages/@aws-cdk/aws-pipes-targets-alpha/lib/sns.ts
  packages/@aws-cdk/aws-pipes-targets-alpha/rosetta/default.ts-fixture
  packages/@aws-cdk/aws-pipes-targets-alpha/test/__snapshots__/sns.test.ts.snap
  packages/@aws-cdk/aws-pipes-targets-alpha/test/integ.sns.js.snapshot/asset.97484721f29e34bf38d7a459804dd2d2a8dea6f8c27d7531e215bf4274fbc895.bundle/index.js
  packages/@aws-cdk/aws-pipes-targets-alpha/test/integ.sns.js.snapshot/aws-cdk-pipes-targets-sns.assets.json
  packages/@aws-cdk/aws-pipes-targets-alpha/test/integ.sns.js.snapshot/aws-cdk-pipes-targets-sns.template.json
  packages/@aws-cdk/aws-pipes-targets-alpha/test/integ.sns.js.snapshot/cdk.out
  packages/@aws-cdk/aws-pipes-targets-alpha/test/integ.sns.js.snapshot/integ.json
  packages/@aws-cdk/aws-pipes-targets-alpha/test/integ.sns.js.snapshot/integtestpipetargetsnsDefaultTestDeployAssert1F2E3164.assets.json
  packages/@aws-cdk/aws-pipes-targets-alpha/test/integ.sns.js.snapshot/integtestpipetargetsnsDefaultTestDeployAssert1F2E3164.template.json
  packages/@aws-cdk/aws-pipes-targets-alpha/test/integ.sns.js.snapshot/manifest.json
  packages/@aws-cdk/aws-pipes-targets-alpha/test/integ.sns.js.snapshot/tree.json
  packages/@aws-cdk/aws-pipes-targets-alpha/test/integ.sns.ts
  packages/@aws-cdk/aws-pipes-targets-alpha/test/sns.test.ts
Labels: p2, distinguished-contributor

#33793 feat(stepfunctions): `ResultWriter` support JSONPath/JSONata bucket
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions/test/integ.distribution-map-result-writer-bucket-jsonpath.js.snapshot/asset.44e9c4d7a5d3fd2d677e1a7e416b2b56f6b0104bd5eff9cac5557b4c65a9dc61/index.js
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions/test/integ.distribution-map-result-writer-bucket-jsonpath.js.snapshot/asset.97484721f29e34bf38d7a459804dd2d2a8dea6f8c27d7531e215bf4274fbc895.bundle/index.js
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions/test/integ.distribution-map-result-writer-bucket-jsonpath.js.snapshot/aws-stepfunctions-map-result-writer-bucket-jsonpath.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions/test/integ.distribution-map-result-writer-bucket-jsonpath.js.snapshot/aws-stepfunctions-map-result-writer-bucket-jsonpath.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions/test/integ.distribution-map-result-writer-bucket-jsonpath.js.snapshot/awsstepfunctionsmapresultwriterbucketjsonpathtestDefaultTestDeployAssert0581372F.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions/test/integ.distribution-map-result-writer-bucket-jsonpath.js.snapshot/awsstepfunctionsmapresultwriterbucketjsonpathtestDefaultTestDeployAssert0581372F.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions/test/integ.distribution-map-result-writer-bucket-jsonpath.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions/test/integ.distribution-map-result-writer-bucket-jsonpath.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions/test/integ.distribution-map-result-writer-bucket-jsonpath.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions/test/integ.distribution-map-result-writer-bucket-jsonpath.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions/test/integ.distribution-map-result-writer-bucket-jsonpath.ts
  packages/aws-cdk-lib/aws-stepfunctions/README.md
  packages/aws-cdk-lib/aws-stepfunctions/lib/states/distributed-map.ts
  packages/aws-cdk-lib/aws-stepfunctions/lib/states/distributed-map/result-writer.ts
  packages/aws-cdk-lib/aws-stepfunctions/test/distributed-map.test.ts
Labels: p2, feature-request, effort/medium, admired-contributor, needs-security-review

#34131 feat(stepfunctions): add parameters to parallel state
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions/test/integ.parallel-parameters.js.snapshot/ParallelParametersTestDefaultTestDeployAssert6493B6D6.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions/test/integ.parallel-parameters.js.snapshot/ParallelParametersTestDefaultTestDeployAssert6493B6D6.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions/test/integ.parallel-parameters.js.snapshot/asset.97484721f29e34bf38d7a459804dd2d2a8dea6f8c27d7531e215bf4274fbc895.bundle/index.js
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions/test/integ.parallel-parameters.js.snapshot/aws-stepfunctions-integ.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions/test/integ.parallel-parameters.js.snapshot/aws-stepfunctions-integ.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions/test/integ.parallel-parameters.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions/test/integ.parallel-parameters.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions/test/integ.parallel-parameters.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions/test/integ.parallel-parameters.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions/test/integ.parallel-parameters.ts
  packages/aws-cdk-lib/aws-stepfunctions/README.md
  packages/aws-cdk-lib/aws-stepfunctions/lib/states/parallel.ts
  packages/aws-cdk-lib/aws-stepfunctions/test/parallel.test.ts
Labels: p2, feature-request, effort/small, beginning-contributor

#34436 feat(sns-subscriptions): throw `ValidationError`s instead of untyped errors
  packages/aws-cdk-lib/.eslintrc.js
  packages/aws-cdk-lib/aws-sns-subscriptions/lib/lambda.ts
  packages/aws-cdk-lib/aws-sns-subscriptions/lib/sqs.ts
  packages/aws-cdk-lib/aws-sns-subscriptions/lib/url.ts
Labels: p2, contribution/core, pr-linter/exempt-readme, pr-linter/exempt-test, pr-linter/exempt-integ-test

#34429 feat(elasticsearch): throw `ValidationError`s instead of untyped errors
  packages/aws-cdk-lib/.eslintrc.js
  packages/aws-cdk-lib/aws-elasticsearch/lib/domain.ts
Labels: p2, contribution/core, pr-linter/exempt-readme, pr-linter/exempt-test, pr-linter/exempt-integ-test

#34434 feat(scheduler): throw `ValidationError`s instead of untyped errors
  packages/aws-cdk-lib/.eslintrc.js
  packages/aws-cdk-lib/aws-scheduler-targets/lib/event-bridge-put-events.ts
  packages/aws-cdk-lib/aws-scheduler-targets/lib/kinesis-stream-put-record.ts
  packages/aws-cdk-lib/aws-scheduler-targets/lib/sage-maker-start-pipeline-execution.ts
  packages/aws-cdk-lib/aws-scheduler-targets/lib/sqs-send-message.ts
  packages/aws-cdk-lib/aws-scheduler-targets/lib/target.ts
  packages/aws-cdk-lib/aws-scheduler-targets/lib/universal.ts
  packages/aws-cdk-lib/aws-scheduler/lib/schedule-expression.ts
  packages/aws-cdk-lib/aws-scheduler/lib/schedule.ts
Labels: p2, contribution/core, pr-linter/exempt-readme, pr-linter/exempt-test, pr-linter/exempt-integ-test

#34427 feat(ecs): throw `ValidationError`s instead of untyped errors
  packages/aws-cdk-lib/.eslintrc.js
  packages/aws-cdk-lib/aws-ecs-patterns/lib/base/application-load-balanced-service-base.ts
  packages/aws-cdk-lib/aws-ecs-patterns/lib/base/application-multiple-target-groups-service-base.ts
  packages/aws-cdk-lib/aws-ecs-patterns/lib/base/network-load-balanced-service-base.ts
  packages/aws-cdk-lib/aws-ecs-patterns/lib/base/network-multiple-target-groups-service-base.ts
  packages/aws-cdk-lib/aws-ecs-patterns/lib/base/queue-processing-service-base.ts
  packages/aws-cdk-lib/aws-ecs-patterns/lib/base/scheduled-task-base.ts
  packages/aws-cdk-lib/aws-ecs-patterns/lib/ecs/application-load-balanced-ecs-service.ts
  packages/aws-cdk-lib/aws-ecs-patterns/lib/ecs/application-multiple-target-groups-ecs-service.ts
  packages/aws-cdk-lib/aws-ecs-patterns/lib/ecs/network-load-balanced-ecs-service.ts
  packages/aws-cdk-lib/aws-ecs-patterns/lib/ecs/network-multiple-target-groups-ecs-service.ts
  packages/aws-cdk-lib/aws-ecs-patterns/lib/ecs/queue-processing-ecs-service.ts
  packages/aws-cdk-lib/aws-ecs-patterns/lib/ecs/scheduled-ecs-task.ts
  packages/aws-cdk-lib/aws-ecs-patterns/lib/fargate/application-load-balanced-fargate-service.ts
  packages/aws-cdk-lib/aws-ecs-patterns/lib/fargate/application-multiple-target-groups-fargate-service.ts
  packages/aws-cdk-lib/aws-ecs-patterns/lib/fargate/network-load-balanced-fargate-service.ts
  packages/aws-cdk-lib/aws-ecs-patterns/lib/fargate/network-multiple-target-groups-fargate-service.ts
  packages/aws-cdk-lib/aws-ecs-patterns/lib/fargate/queue-processing-fargate-service.ts
  packages/aws-cdk-lib/aws-ecs-patterns/lib/fargate/scheduled-fargate-task.ts
  packages/aws-cdk-lib/aws-ecs/lib/amis.ts
  packages/aws-cdk-lib/aws-ecs/lib/base/_imported-task-definition.ts
  packages/aws-cdk-lib/aws-ecs/lib/base/base-service.ts
  packages/aws-cdk-lib/aws-ecs/lib/base/from-service-attributes.ts
  packages/aws-cdk-lib/aws-ecs/lib/base/service-managed-volume.ts
  packages/aws-cdk-lib/aws-ecs/lib/base/task-definition.ts
  packages/aws-cdk-lib/aws-ecs/lib/cluster.ts
  packages/aws-cdk-lib/aws-ecs/lib/container-definition.ts
  packages/aws-cdk-lib/aws-ecs/lib/credential-spec.ts
  packages/aws-cdk-lib/aws-ecs/lib/ec2/ec2-service.ts
  packages/aws-cdk-lib/aws-ecs/lib/ec2/ec2-task-definition.ts
  packages/aws-cdk-lib/aws-ecs/lib/environment-file.ts
  packages/aws-cdk-lib/aws-ecs/lib/external/external-service.ts
  packages/aws-cdk-lib/aws-ecs/lib/external/external-task-definition.ts
  packages/aws-cdk-lib/aws-ecs/lib/fargate/fargate-service.ts
  packages/aws-cdk-lib/aws-ecs/lib/fargate/fargate-task-definition.ts
  packages/aws-cdk-lib/aws-ecs/lib/firelens-log-router.ts
  packages/aws-cdk-lib/aws-ecs/lib/images/tag-parameter-container-image.ts
  packages/aws-cdk-lib/aws-ecs/lib/linux-parameters.ts
  packages/aws-cdk-lib/aws-ecs/lib/log-drivers/aws-log-driver.ts
  packages/aws-cdk-lib/aws-ecs/lib/log-drivers/json-file-log-driver.ts
  packages/aws-cdk-lib/aws-ecs/lib/log-drivers/splunk-log-driver.ts
  packages/aws-cdk-lib/aws-ecs/lib/log-drivers/utils.ts
  packages/aws-cdk-lib/aws-ecs/lib/placement.ts
  packages/aws-cdk-lib/aws-ecs/lib/proxy-configuration/app-mesh-proxy-configuration.ts
Labels: p2, contribution/core, pr-linter/exempt-readme, pr-linter/exempt-test, pr-linter/exempt-integ-test

#34269 fix(cloudwatch-actions): lambda permission use unique prefix id
  packages/@aws-cdk-testing/framework-integ/test/aws-cloudwatch-actions/test/integ.lambda-alarm-multiple-stepscalingpolicy.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-cloudwatch-actions/test/integ.lambda-alarm-multiple-stepscalingpolicy.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-cloudwatch-actions/test/integ.lambda-alarm-multiple-stepscalingpolicy.js.snapshot/lambda-alarm-multiple-stepscalingpolicy.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-cloudwatch-actions/test/integ.lambda-alarm-multiple-stepscalingpolicy.js.snapshot/lambda-alarm-multiple-stepscalingpolicy.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-cloudwatch-actions/test/integ.lambda-alarm-multiple-stepscalingpolicy.js.snapshot/lambdaalarmmultiplestepscalingpolicytestDefaultTestDeployAssertD4E8CDE5.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-cloudwatch-actions/test/integ.lambda-alarm-multiple-stepscalingpolicy.js.snapshot/lambdaalarmmultiplestepscalingpolicytestDefaultTestDeployAssertD4E8CDE5.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-cloudwatch-actions/test/integ.lambda-alarm-multiple-stepscalingpolicy.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-cloudwatch-actions/test/integ.lambda-alarm-multiple-stepscalingpolicy.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-cloudwatch-actions/test/integ.lambda-alarm-multiple-stepscalingpolicy.ts
  packages/aws-cdk-lib/aws-cloudwatch-actions/lib/lambda.ts
  packages/aws-cdk-lib/aws-cloudwatch-actions/test/lambda.test.ts
Labels: bug, p1, effort/medium, admired-contributor, pr/needs-maintainer-review

#34450 chore: fix code snippet in Readme
  packages/aws-cdk-lib/cx-api/README.md
Labels: p2, contribution/core

#34446 chore(rds): postgres aurora add 16.8-limitless, rds add 17.5, 16.9, 15.13, 14.18, 13.21
  packages/@aws-cdk-testing/framework-integ/test/aws-rds/test/integ.cluster-limitless.js.snapshot/LimitlessClusterStack.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-rds/test/integ.cluster-limitless.js.snapshot/LimitlessClusterStack.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-rds/test/integ.cluster-limitless.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-rds/test/integ.cluster-limitless.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-rds/test/integ.cluster-limitless.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-rds/test/integ.cluster-limitless.ts
  packages/aws-cdk-lib/aws-rds/lib/cluster-engine.ts
  packages/aws-cdk-lib/aws-rds/lib/instance-engine.ts
Labels: p2, pr/needs-community-review, star-contributor

#34425 feat(cloudformation): update L1 CloudFormation resource definitions
  packages/aws-cdk-lib/package.json
  tools/@aws-cdk/spec2cdk/package.json
  yarn.lock
Labels: p2, dependencies, contribution/core, pr-linter/exempt-readme, pr-linter/exempt-test, pr-linter/exempt-breaking-change, pr-linter/exempt-integ-test

#34451 chore: split codecov to collect and upload workflows
  .github/workflows/codecov-collect.yml
  .github/workflows/codecov-upload.yml
Labels: p2, contribution/core

#34454 chore(security-guardian): skip release and mergeback PRs
  .github/workflows/security-guardian.yml
Labels: p2, contribution/core

#34455 chore: fixes codecov upload issue codecov split
  .github/workflows/codecov-upload.yml
Labels: p2, contribution/core

#34458 chore: npm-check-updates && yarn upgrade
  package.json
  packages/@aws-cdk-testing/framework-integ/package.json
  packages/@aws-cdk/app-staging-synthesizer-alpha/package.json
  packages/@aws-cdk/aws-amplify-alpha/package.json
  packages/@aws-cdk/aws-applicationsignals-alpha/package.json
  packages/@aws-cdk/aws-apprunner-alpha/package.json
  packages/@aws-cdk/aws-cloud9-alpha/package.json
  packages/@aws-cdk/aws-codestar-alpha/package.json
  packages/@aws-cdk/aws-ec2-alpha/package.json
  packages/@aws-cdk/aws-eks-v2-alpha/package.json
  packages/@aws-cdk/aws-gamelift-alpha/package.json
  packages/@aws-cdk/aws-glue-alpha/package.json
  packages/@aws-cdk/aws-iot-actions-alpha/package.json
  packages/@aws-cdk/aws-iot-alpha/package.json
  packages/@aws-cdk/aws-iotevents-actions-alpha/package.json
  packages/@aws-cdk/aws-iotevents-alpha/package.json
  packages/@aws-cdk/aws-ivs-alpha/package.json
  packages/@aws-cdk/aws-kinesisanalytics-flink-alpha/package.json
  packages/@aws-cdk/aws-lambda-go-alpha/package.json
  packages/@aws-cdk/aws-lambda-python-alpha/package.json
  packages/@aws-cdk/aws-location-alpha/package.json
  packages/@aws-cdk/aws-msk-alpha/package.json
  packages/@aws-cdk/aws-neptune-alpha/package.json
  packages/@aws-cdk/aws-pipes-alpha/package.json
  packages/@aws-cdk/aws-pipes-enrichments-alpha/package.json
  packages/@aws-cdk/aws-pipes-sources-alpha/package.json
  packages/@aws-cdk/aws-pipes-targets-alpha/package.json
  packages/@aws-cdk/aws-redshift-alpha/package.json
  packages/@aws-cdk/aws-route53resolver-alpha/package.json
  packages/@aws-cdk/aws-s3objectlambda-alpha/package.json
  packages/@aws-cdk/aws-sagemaker-alpha/package.json
  packages/@aws-cdk/aws-servicecatalogappregistry-alpha/package.json
  packages/@aws-cdk/cx-api/package.json
  packages/@aws-cdk/example-construct-library/package.json
  packages/@aws-cdk/integ-tests-alpha/package.json
  packages/aws-cdk-lib/package.json
  tools/@aws-cdk/cdk-build-tools/package.json
  tools/@aws-cdk/cdk-release/package.json
  tools/@aws-cdk/pkglint/package.json
  tools/@aws-cdk/yarn-cling/package.json
  yarn.lock
Labels: p2, dependencies, contribution/core, auto-approve

#34444 chore(rds): deprecate Aurora PostgreSQL versions 12.11-21, 13.7, 13.8, 13.10, 13.17, 14.3-5, 14.7, 14.4, 15.2, and 15.9
  packages/aws-cdk-lib/aws-rds/lib/cluster-engine.ts
Labels: p2, pr/needs-community-review, star-contributor

#34443 feat(rds): add Aurora MySQL versions 2.11.6, 2.12.5, 3.04.4
  packages/aws-cdk-lib/aws-rds/lib/cluster-engine.ts
  packages/aws-cdk-lib/aws-rds/test/cluster-engine.test.ts
Labels: p2, pr-linter/exempt-readme, pr-linter/exempt-integ-test, star-contributor, pr/needs-maintainer-review

#34459 chore(spec2cdk): remove temporary schema for AWS::AppSync::ChannelNamespace
  tools/@aws-cdk/spec2cdk/temporary-schemas/us-east-1/aws-appsync-channelnamespace.json
Labels: p2, contribution/core

#34460 revert: "feat(s3tables): server-side encryption by customer managed KMS key"
  packages/@aws-cdk/aws-s3tables-alpha/README.md
  packages/@aws-cdk/aws-s3tables-alpha/lib/table-bucket.ts
  packages/@aws-cdk/aws-s3tables-alpha/rosetta/default.ts-fixture
  packages/@aws-cdk/aws-s3tables-alpha/test/integration/integ.table-bucket-kms-key.js.snapshot/cdk.out
  packages/@aws-cdk/aws-s3tables-alpha/test/integration/integ.table-bucket-kms-key.js.snapshot/integ.json
  packages/@aws-cdk/aws-s3tables-alpha/test/integration/integ.table-bucket-kms-key.js.snapshot/kms-key-s3tables-stack.assets.json
  packages/@aws-cdk/aws-s3tables-alpha/test/integration/integ.table-bucket-kms-key.js.snapshot/kms-key-s3tables-stack.template.json
  packages/@aws-cdk/aws-s3tables-alpha/test/integration/integ.table-bucket-kms-key.js.snapshot/kmskeys3tablesintegDefaultTestDeployAssertC8AB8C4E.assets.json
  packages/@aws-cdk/aws-s3tables-alpha/test/integration/integ.table-bucket-kms-key.js.snapshot/kmskeys3tablesintegDefaultTestDeployAssertC8AB8C4E.template.json
  packages/@aws-cdk/aws-s3tables-alpha/test/integration/integ.table-bucket-kms-key.js.snapshot/manifest.json
  packages/@aws-cdk/aws-s3tables-alpha/test/integration/integ.table-bucket-kms-key.js.snapshot/tree.json
  packages/@aws-cdk/aws-s3tables-alpha/test/integration/integ.table-bucket-kms-key.ts
  packages/@aws-cdk/aws-s3tables-alpha/test/table-bucket.test.ts
Labels: p2, contribution/core

#34281 feat(s3-tables): add KMS support for TableBucket L2 construct
  packages/@aws-cdk/aws-s3tables-alpha/README.md
  packages/@aws-cdk/aws-s3tables-alpha/lib/permissions.ts
  packages/@aws-cdk/aws-s3tables-alpha/lib/table-bucket.ts
  packages/@aws-cdk/aws-s3tables-alpha/rosetta/default.ts-fixture
  packages/@aws-cdk/aws-s3tables-alpha/test/integration/integ.table-bucket-encryption.js.snapshot/KeyWithKMSEncryptionTypeTest.assets.json
  packages/@aws-cdk/aws-s3tables-alpha/test/integration/integ.table-bucket-encryption.js.snapshot/KeyWithKMSEncryptionTypeTest.template.json
  packages/@aws-cdk/aws-s3tables-alpha/test/integration/integ.table-bucket-encryption.js.snapshot/OnlyEncryptionKeyTest.assets.json
  packages/@aws-cdk/aws-s3tables-alpha/test/integration/integ.table-bucket-encryption.js.snapshot/OnlyEncryptionKeyTest.template.json
  packages/@aws-cdk/aws-s3tables-alpha/test/integration/integ.table-bucket-encryption.js.snapshot/OnlyKMSEncryptionTypeTest.assets.json
  packages/@aws-cdk/aws-s3tables-alpha/test/integration/integ.table-bucket-encryption.js.snapshot/OnlyKMSEncryptionTypeTest.template.json
  packages/@aws-cdk/aws-s3tables-alpha/test/integration/integ.table-bucket-encryption.js.snapshot/OnlyS3ManagedEncryptionTest.assets.json
  packages/@aws-cdk/aws-s3tables-alpha/test/integration/integ.table-bucket-encryption.js.snapshot/OnlyS3ManagedEncryptionTest.template.json
  packages/@aws-cdk/aws-s3tables-alpha/test/integration/integ.table-bucket-encryption.js.snapshot/TableBucketEncryptionIntegTestDefaultTestDeployAssert2F88D4F9.assets.json
  packages/@aws-cdk/aws-s3tables-alpha/test/integration/integ.table-bucket-encryption.js.snapshot/TableBucketEncryptionIntegTestDefaultTestDeployAssert2F88D4F9.template.json
  packages/@aws-cdk/aws-s3tables-alpha/test/integration/integ.table-bucket-encryption.js.snapshot/cdk.out
  packages/@aws-cdk/aws-s3tables-alpha/test/integration/integ.table-bucket-encryption.js.snapshot/integ.json
  packages/@aws-cdk/aws-s3tables-alpha/test/integration/integ.table-bucket-encryption.js.snapshot/manifest.json
  packages/@aws-cdk/aws-s3tables-alpha/test/integration/integ.table-bucket-encryption.js.snapshot/tree.json
  packages/@aws-cdk/aws-s3tables-alpha/test/integration/integ.table-bucket-encryption.ts
  packages/@aws-cdk/aws-s3tables-alpha/test/table-bucket-encryption.test.ts
  packages/@aws-cdk/aws-s3tables-alpha/test/table-bucket.test.ts
  packages/@aws-cdk/aws-s3tables-alpha/test/test-utils.ts
Labels: p1, beginning-contributor, pr/needs-maintainer-review, needs-security-review

#34449 fix(eks): eks cluster name exceeding the limit of 100 characters
  packages/aws-cdk-lib/aws-eks/lib/cluster.ts
  packages/aws-cdk-lib/aws-eks/test/cluster.test.ts
Labels: bug, p2, effort/small, contribution/core, pr-linter/exempt-integ-test

#34437 fix(ec2): dual-stack vpc without private subnets creates EgressOnlyInternetGateway (under feature flag)
  packages/aws-cdk-lib/aws-ec2/lib/vpc.ts
  packages/aws-cdk-lib/aws-ec2/test/vpc.test.ts
  packages/aws-cdk-lib/cx-api/FEATURE_FLAGS.md
  packages/aws-cdk-lib/cx-api/README.md
  packages/aws-cdk-lib/cx-api/lib/features.ts
  packages/aws-cdk-lib/recommended-feature-flags.json
Labels: bug, p2, effort/small, contribution/core, pr-linter/exempt-integ-test, pr/needs-maintainer-review

#34461 chore(codecov): codecov refactored into collect and upload workflows
  .github/workflows/codecov-upload.yml
  .github/workflows/codecov.yml
Labels: p2, contribution/core

#34213 feat(msk): support Kafka versions 3.9.x and 3.9.x Kraft
  packages/@aws-cdk/aws-msk-alpha/README.md
  packages/@aws-cdk/aws-msk-alpha/lib/cluster-version.ts
  packages/@aws-cdk/aws-msk-alpha/test/cluster.test.ts
  packages/@aws-cdk/aws-msk-alpha/test/integ.cluster-version.js.snapshot/KafkaVersionIntegTestDefaultTestDeployAssertD6628743.assets.json
  packages/@aws-cdk/aws-msk-alpha/test/integ.cluster-version.js.snapshot/KafkaVersionTestStack.assets.json
  packages/@aws-cdk/aws-msk-alpha/test/integ.cluster-version.js.snapshot/KafkaVersionTestStack.template.json
  packages/@aws-cdk/aws-msk-alpha/test/integ.cluster-version.js.snapshot/cdk.out
  packages/@aws-cdk/aws-msk-alpha/test/integ.cluster-version.js.snapshot/integ.json
  packages/@aws-cdk/aws-msk-alpha/test/integ.cluster-version.js.snapshot/manifest.json
  packages/@aws-cdk/aws-msk-alpha/test/integ.cluster-version.js.snapshot/tree.json
  packages/@aws-cdk/aws-msk-alpha/test/integ.cluster-version.ts
Labels: p2, distinguished-contributor

#34441 chore(enum-updater): support adding manual static enum mappings
  .github/workflows/enum-static-mapping-updater.yml
  tools/@aws-cdk/enum-updater/README.md
  tools/@aws-cdk/enum-updater/lib/manual-enum-mapping.json
  tools/@aws-cdk/enum-updater/lib/static-enum-mapping-updater.ts
  tools/@aws-cdk/enum-updater/test/static-enum-mapping-updater.test.ts
Labels: p2, contribution/core

#34314 feat(ses): https policy for custom tracking domain
  packages/@aws-cdk-testing/framework-integ/test/aws-ses/test/integ.configuration-set-tracking-options.js.snapshot/ConfigurationSetIntegDefaultTestDeployAssert9B6AD46A.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ses/test/integ.configuration-set-tracking-options.js.snapshot/ConfigurationSetIntegDefaultTestDeployAssert9B6AD46A.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ses/test/integ.configuration-set-tracking-options.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-ses/test/integ.configuration-set-tracking-options.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ses/test/integ.configuration-set-tracking-options.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ses/test/integ.configuration-set-tracking-options.js.snapshot/ses-configuration-set-tracking-options-integ.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ses/test/integ.configuration-set-tracking-options.js.snapshot/ses-configuration-set-tracking-options-integ.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ses/test/integ.configuration-set-tracking-options.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ses/test/integ.configuration-set-tracking-options.ts
  packages/aws-cdk-lib/aws-ses/README.md
  packages/aws-cdk-lib/aws-ses/lib/configuration-set.ts
  packages/aws-cdk-lib/aws-ses/test/configuration-set.test.ts
Labels: p2, distinguished-contributor, pr/needs-maintainer-review

#34464 docs: update Node.js version in contributing guide
  CONTRIBUTING.md
Labels: p2, pr/needs-community-review, beginning-contributor

#34128 chore(region-info): ap-southeast-7
  packages/aws-cdk-lib/region-info/build-tools/fact-tables.ts
  packages/aws-cdk-lib/region-info/test/__snapshots__/region-info.test.ts.snap
Labels: p2, pr/needs-community-review, admired-contributor

#34384 docs(eks-v2-alpha): remove spot instance related documentation
  packages/@aws-cdk/aws-eks-v2-alpha/lib/cluster.ts
Labels: p2, admired-contributor

#34462 test(ec2): add integ test for EC2_REQUIRE_PRIVATE_SUBNETS_FOR_EGRESSONLYINTERNETGATEWAY feature flag
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.vpc-egress-only-igw-feature-flag.js.snapshot/VpcEgressFeatureFlagTestDefaultTestDeployAssert9C3B9F44.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.vpc-egress-only-igw-feature-flag.js.snapshot/VpcEgressFeatureFlagTestDefaultTestDeployAssert9C3B9F44.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.vpc-egress-only-igw-feature-flag.js.snapshot/VpcMigrationFeatureFlagDisabledStack.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.vpc-egress-only-igw-feature-flag.js.snapshot/VpcMigrationFeatureFlagDisabledStack.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.vpc-egress-only-igw-feature-flag.js.snapshot/VpcMigrationFeatureFlagEnabledStack.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.vpc-egress-only-igw-feature-flag.js.snapshot/VpcMigrationFeatureFlagEnabledStack.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.vpc-egress-only-igw-feature-flag.js.snapshot/asset.a1acfc2b5f4f6b183fd2bb9863f486bc5edef6a357b355a070d9a0e502df418c/__entrypoint__.js
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.vpc-egress-only-igw-feature-flag.js.snapshot/asset.a1acfc2b5f4f6b183fd2bb9863f486bc5edef6a357b355a070d9a0e502df418c/index.js
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.vpc-egress-only-igw-feature-flag.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.vpc-egress-only-igw-feature-flag.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.vpc-egress-only-igw-feature-flag.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.vpc-egress-only-igw-feature-flag.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.vpc-egress-only-igw-feature-flag.ts
Labels: p2, contribution/core

#34474 chore(enum-updater): ensure missing enum updater runs with latest CDK enums
  tools/@aws-cdk/enum-updater/lib/missing-enum-updater.ts
  tools/@aws-cdk/enum-updater/lib/static-enum-mapping-updater.ts
  tools/@aws-cdk/enum-updater/test/missing-enum-updater.test.ts
Labels: p2, contribution/core, pr/needs-maintainer-review

#33865 fix(core): `platform` is ignored during asset bundling
  packages/@aws-cdk-testing/framework-integ/test/aws-s3-assets/test/integ.assets.bundling.docker-opts.ts
  packages/aws-cdk-lib/core/lib/private/asset-staging.ts
  packages/aws-cdk-lib/core/test/private/asset-staging.test.ts
Labels: bug, p2, pr/needs-community-review, effort/medium, pr-linter/exempt-integ-test, beginning-contributor, pr-linter/exemption-requested, skip-abstractions-board

#34485 docs: update Node.js version in README
  README.md
Labels: p2, pr/needs-community-review, beginning-contributor

#34498 fix(lambda-nodejs): instantiating `NodejsFunction` without the `entry` property fails
  packages/aws-cdk-lib/aws-lambda-nodejs/lib/function.ts
  tools/@aws-cdk/construct-metadata-updater/lib/metadata-updater.ts
Labels: bug, p0, effort/medium, contribution/core, pr-linter/exempt-test, pr-linter/exempt-integ-test

#34499 chore(release): 2.196.1
  CHANGELOG.v2.alpha.md
  CHANGELOG.v2.md
  packages/aws-cdk-lib/aws-lambda-nodejs/lib/function.ts
  tools/@aws-cdk/construct-metadata-updater/lib/metadata-updater.ts
  version.v2.json
Labels: contribution/core, pr/no-squash, pr-linter/analytics-metadata-change

#34500 chore(merge-back): 2.196.1
  CHANGELOG.v2.alpha.md
  CHANGELOG.v2.md
  version.v2.json
Labels: p2, pr/needs-community-review, pr/no-squash, auto-approve

#34497 feat: update L1 CloudFormation resource definitions
  packages/aws-cdk-lib/package.json
  tools/@aws-cdk/spec2cdk/package.json
  yarn.lock
Labels: p2, dependencies, contribution/core, pr-linter/exempt-readme, pr-linter/exempt-test, pr-linter/exempt-integ-test, pr/needs-maintainer-review

#34507 chore(merge-back): 2.197.0
  CHANGELOG.v2.alpha.md
  CHANGELOG.v2.md
  packages/aws-cdk-lib/aws-cloudwatch/lib/alarm.ts
  packages/aws-cdk-lib/core/lib/analytics-data-source/classes.ts
  packages/aws-cdk-lib/core/lib/analytics-data-source/enums.ts
  packages/aws-cdk-lib/core/lib/analytics-data-source/enums/module-enums.json
  version.v2.json
Labels: p2, pr/needs-community-review, pr/no-squash, auto-approve

#34081 fix(ses-actions): condition should use SourceAccount
  packages/@aws-cdk-testing/framework-integ/test/aws-ses-actions/test/integ.actions.js.snapshot/aws-cdk-ses-receipt.template.json
  packages/aws-cdk-lib/aws-ses-actions/lib/s3.ts
  packages/aws-cdk-lib/aws-ses-actions/test/actions.test.ts
  packages/aws-cdk-lib/aws-ses/README.md
Labels: p2, pr-linter/exempt-integ-test, beginning-contributor

#34490 chore(rds): deprecate MariaDB 10.4
  packages/aws-cdk-lib/aws-rds/lib/instance-engine.ts
Labels: p2, star-contributor

#34453 feat(ec2): add i7i instance class
  packages/aws-cdk-lib/aws-ec2/lib/instance-types.ts
Labels: p2, pr-linter/exempt-readme, pr-linter/exempt-test, pr-linter/exempt-integ-test, star-contributor

#34272 fix(route53): avoid setting unnecessary properties for Recovery Control type Route53 health check
  packages/@aws-cdk-testing/framework-integ/test/aws-route53/test/integ.health-check.js.snapshot/asset.97484721f29e34bf38d7a459804dd2d2a8dea6f8c27d7531e215bf4274fbc895.bundle/index.js
  packages/@aws-cdk-testing/framework-integ/test/aws-route53/test/integ.health-check.js.snapshot/aws-cdk-route53-health-check.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-route53/test/integ.health-check.js.snapshot/aws-cdk-route53-health-check.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-route53/test/integ.health-check.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-route53/test/integ.health-check.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-route53/test/integ.health-check.js.snapshot/integtestDefaultTestDeployAssert24D5C536.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-route53/test/integ.health-check.js.snapshot/integtestDefaultTestDeployAssert24D5C536.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-route53/test/integ.health-check.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-route53/test/integ.health-check.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-route53/test/integ.health-check.ts
  packages/aws-cdk-lib/aws-route53/lib/health-check.ts
  packages/aws-cdk-lib/aws-route53/test/health-check.test.ts
Labels: bug, p2, effort/medium, repeat-contributor

#34510 fix(ecs-patterns): add missing redirectHTTP dependency on main listener in ApplicationLoadBalancedFargateService
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs-patterns/test/fargate/integ.alb-fargate-service-https.js.snapshot/aws-ecs-integ-alb-fg-https.template.json
  packages/aws-cdk-lib/aws-ecs-patterns/lib/base/application-load-balanced-service-base.ts
Labels: bug, p1, contribution/core, pr-linter/exempt-integ-test, pr-linter/exemption-requested

#34478 fix: synthesis fails if `tree.json` exceeds 512MB
  packages/@aws-cdk-testing/framework-integ/test/core/test/tree-metadata.test.ts
  packages/aws-cdk-lib/core/lib/private/construct-iteration.ts
  packages/aws-cdk-lib/core/lib/private/linked-queue.ts
  packages/aws-cdk-lib/core/lib/private/tree-metadata.ts
  packages/aws-cdk-lib/core/test/private/linked-queue.test.ts
Labels: bug, p1, contribution/core, pr-linter/exempt-integ-test

#34528 feat: update L1 CloudFormation resource definitions
  packages/aws-cdk-lib/package.json
  tools/@aws-cdk/spec2cdk/package.json
  yarn.lock
Labels: p2, dependencies, contribution/core, pr-linter/exempt-readme, pr-linter/exempt-test, pr-linter/exempt-integ-test

#34483 chore(ec2): add VPC interface endpoint for Dynamodb Streams
  packages/aws-cdk-lib/aws-ec2/lib/vpc-endpoint.ts
Labels: p2, beginning-contributor, pr/needs-maintainer-review

#34530 docs(rds): correct default StorageType in DatabaseCluster
  packages/aws-cdk-lib/aws-rds/lib/cluster.ts
Labels: p2, effort/small, contribution/core, pr/needs-maintainer-review

#34531 chore(bedrock): add Claude4 Sonnet, Opus
  packages/aws-cdk-lib/aws-bedrock/lib/foundation-model.ts
Labels: p2, distinguished-contributor, pr/needs-maintainer-review

#33564 fix(rds): fix incorrect import/export combination check in AuroraMysqlEngineVersion.of()
  packages/@aws-cdk-testing/framework-integ/test/aws-rds/test/integ.cluster-s3.mysql-engine-version.js.snapshot/aws-cdk-rds-s3-mysql-engine-version-integ.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-rds/test/integ.cluster-s3.mysql-engine-version.js.snapshot/aws-cdk-rds-s3-mysql-engine-version-integ.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-rds/test/integ.cluster-s3.mysql-engine-version.js.snapshot/awscdkrdss3mysqlengineversionintegtestDefaultTestDeployAssert95FAB883.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-rds/test/integ.cluster-s3.mysql-engine-version.js.snapshot/awscdkrdss3mysqlengineversionintegtestDefaultTestDeployAssert95FAB883.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-rds/test/integ.cluster-s3.mysql-engine-version.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-rds/test/integ.cluster-s3.mysql-engine-version.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-rds/test/integ.cluster-s3.mysql-engine-version.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-rds/test/integ.cluster-s3.mysql-engine-version.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-rds/test/integ.cluster-s3.mysql-engine-version.ts
  packages/aws-cdk-lib/aws-rds/lib/cluster-engine.ts
  packages/aws-cdk-lib/aws-rds/test/cluster-engine.test.ts
Labels: bug, p2, beginning-contributor

#34516 feat(ecs-patterns): add minHealthyPercent and maxHealthyPercent props to NetworkMultipleTargetGroupsFargateService
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs-patterns/test/fargate/integ.network-load-balanced-fargate-service-custom-health.js.snapshot/aws-ecs-integ-fargate-health-percentage.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs-patterns/test/fargate/integ.network-load-balanced-fargate-service-custom-health.js.snapshot/aws-ecs-integ-fargate-health-percentage.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs-patterns/test/fargate/integ.network-load-balanced-fargate-service-custom-health.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs-patterns/test/fargate/integ.network-load-balanced-fargate-service-custom-health.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs-patterns/test/fargate/integ.network-load-balanced-fargate-service-custom-health.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs-patterns/test/fargate/integ.network-load-balanced-fargate-service-custom-health.js.snapshot/networkMultipleTargetGroupsFargateServiceTestDefaultTestDeployAssertC9049A80.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs-patterns/test/fargate/integ.network-load-balanced-fargate-service-custom-health.js.snapshot/networkMultipleTargetGroupsFargateServiceTestDefaultTestDeployAssertC9049A80.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs-patterns/test/fargate/integ.network-load-balanced-fargate-service-custom-health.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ecs-patterns/test/fargate/integ.network-load-balanced-fargate-service-custom-health.ts
  packages/aws-cdk-lib/aws-ecs-patterns/README.md
  packages/aws-cdk-lib/aws-ecs-patterns/lib/fargate/network-multiple-target-groups-fargate-service.ts
  packages/aws-cdk-lib/aws-ecs-patterns/test/fargate/network-multiple-target-groups-fargate-service.test.ts
Labels: p2, feature-request, contribution/core

#34535 chore(merge-back): 2.198.0
  CHANGELOG.v2.alpha.md
  CHANGELOG.v2.md
  packages/aws-cdk-lib/core/lib/analytics-data-source/classes.ts
  packages/aws-cdk-lib/core/lib/analytics-data-source/enums.ts
  packages/aws-cdk-lib/core/lib/analytics-data-source/enums/module-enumlikes.json
  packages/aws-cdk-lib/core/lib/analytics-data-source/enums/module-enums.json
  version.v2.json
Labels: p2, pr/needs-community-review, pr/no-squash, auto-approve

#34259 feat(events-targets): enable opt-in to use an IAM role for SnsTopic target
  packages/@aws-cdk-testing/framework-integ/test/aws-events-targets/test/sns/integ.sns-event-rule-target-custom-role.js.snapshot/aws-cdk-sns-event-target.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-events-targets/test/sns/integ.sns-event-rule-target-custom-role.js.snapshot/aws-cdk-sns-event-target.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-events-targets/test/sns/integ.sns-event-rule-target-custom-role.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-events-targets/test/sns/integ.sns-event-rule-target-custom-role.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-events-targets/test/sns/integ.sns-event-rule-target-custom-role.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-events-targets/test/sns/integ.sns-event-rule-target-custom-role.js.snapshot/snseventruletargetcustomroleDefaultTestDeployAssert83424588.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-events-targets/test/sns/integ.sns-event-rule-target-custom-role.js.snapshot/snseventruletargetcustomroleDefaultTestDeployAssert83424588.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-events-targets/test/sns/integ.sns-event-rule-target-custom-role.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-events-targets/test/sns/integ.sns-event-rule-target-custom-role.ts
  packages/@aws-cdk-testing/framework-integ/test/aws-events-targets/test/sns/integ.sns-event-rule-target-role-enabled.js.snapshot/aws-cdk-sns-event-target.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-events-targets/test/sns/integ.sns-event-rule-target-role-enabled.js.snapshot/aws-cdk-sns-event-target.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-events-targets/test/sns/integ.sns-event-rule-target-role-enabled.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-events-targets/test/sns/integ.sns-event-rule-target-role-enabled.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-events-targets/test/sns/integ.sns-event-rule-target-role-enabled.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-events-targets/test/sns/integ.sns-event-rule-target-role-enabled.js.snapshot/snseventruletargetroleenabledDefaultTestDeployAssertEF14CC5B.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-events-targets/test/sns/integ.sns-event-rule-target-role-enabled.js.snapshot/snseventruletargetroleenabledDefaultTestDeployAssertEF14CC5B.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-events-targets/test/sns/integ.sns-event-rule-target-role-enabled.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-events-targets/test/sns/integ.sns-event-rule-target-role-enabled.ts
  packages/aws-cdk-lib/aws-events-targets/README.md
  packages/aws-cdk-lib/aws-events-targets/lib/sns.ts
  packages/aws-cdk-lib/aws-events-targets/test/sns/sns.test.ts
Labels: p2, pr/needs-community-review, repeat-contributor

#31913 feat(stepfunctions-tasks): bedrock createModelCustomizationJob integration
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/bedrock/integ.create-model-customization-job.js.snapshot/CreateModelCustomizationJobDefaultTestDeployAssertEC679DFE.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/bedrock/integ.create-model-customization-job.js.snapshot/CreateModelCustomizationJobDefaultTestDeployAssertEC679DFE.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/bedrock/integ.create-model-customization-job.js.snapshot/asset.44e9c4d7a5d3fd2d677e1a7e416b2b56f6b0104bd5eff9cac5557b4c65a9dc61/index.js
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/bedrock/integ.create-model-customization-job.js.snapshot/asset.5b7ddd1e0b18514d45c25a44b162f82431b091da093fb35e4b814bbba093c506.bundle/index.js
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/bedrock/integ.create-model-customization-job.js.snapshot/asset.a1acfc2b5f4f6b183fd2bb9863f486bc5edef6a357b355a070d9a0e502df418c/__entrypoint__.js
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/bedrock/integ.create-model-customization-job.js.snapshot/asset.a1acfc2b5f4f6b183fd2bb9863f486bc5edef6a357b355a070d9a0e502df418c/index.js
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/bedrock/integ.create-model-customization-job.js.snapshot/aws-stepfunctions-tasks-bedrock-invoke-model-integ.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/bedrock/integ.create-model-customization-job.js.snapshot/aws-stepfunctions-tasks-bedrock-invoke-model-integ.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/bedrock/integ.create-model-customization-job.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/bedrock/integ.create-model-customization-job.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/bedrock/integ.create-model-customization-job.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/bedrock/integ.create-model-customization-job.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions-tasks/test/bedrock/integ.create-model-customization-job.ts
  packages/aws-cdk-lib/aws-stepfunctions-tasks/README.md
  packages/aws-cdk-lib/aws-stepfunctions-tasks/lib/bedrock/create-model-customization-job.ts
  packages/aws-cdk-lib/aws-stepfunctions-tasks/lib/index.ts
  packages/aws-cdk-lib/aws-stepfunctions-tasks/test/bedrock/create-model-customization-job.test.ts
Labels: p2, feature-request, pr/needs-community-review, effort/medium, distinguished-contributor, needs-security-review

#34544 chore(ec2): update vpc README with vpc lookup method
  packages/aws-cdk-lib/aws-ec2/README.md
Labels: p2, contribution/core, pr/needs-maintainer-review

#34233 fix(elasticloadbalancingv2): add validation on application listeners for certificates on HTTP protocol
  packages/aws-cdk-lib/aws-elasticloadbalancingv2/lib/alb/application-listener.ts
  packages/aws-cdk-lib/aws-elasticloadbalancingv2/test/alb/listener.test.ts
Labels: p2, pr-linter/exempt-integ-test, beginning-contributor, pr/needs-maintainer-review

#34563 chore(merge-back): 2.199.0
  CHANGELOG.v2.alpha.md
  CHANGELOG.v2.md
  packages/aws-cdk-lib/core/lib/analytics-data-source/classes.ts
  packages/aws-cdk-lib/core/lib/analytics-data-source/enums.ts
  packages/aws-cdk-lib/core/lib/analytics-data-source/enums/module-enumlikes.json
  packages/aws-cdk-lib/core/lib/analytics-data-source/enums/module-enums.json
  version.v2.json
Labels: p2, pr/needs-community-review, pr/no-squash, auto-approve

#33617 feat(ec2): implement `IPeer` to `PrefixList` to be usable as a connection peer
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.prefix-list.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.prefix-list.js.snapshot/integ-ec2-prefix-list-test.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.prefix-list.js.snapshot/integ-ec2-prefix-list-test.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.prefix-list.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.prefix-list.js.snapshot/integtestDefaultTestDeployAssert24D5C536.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.prefix-list.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.prefix-list.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.prefix-list.ts
  packages/aws-cdk-lib/aws-cloudfront-origins/README.md
  packages/aws-cdk-lib/aws-ec2/README.md
  packages/aws-cdk-lib/aws-ec2/lib/prefix-list.ts
  packages/aws-cdk-lib/aws-ec2/test/prefix-list.test.ts
Labels: p2, feature-request, pr/needs-community-review, effort/medium, star-contributor

#34584 chore: require cli integ test when changing/adding a feature flag.
  .github/workflows/request-cli-integ-test.yml
Labels: p2, contribution/core

#34581 feat(servicecatalog): throw `ValidationError`s instead of untyped errors
  packages/aws-cdk-lib/.eslintrc.js
  packages/aws-cdk-lib/aws-servicecatalog/lib/portfolio.ts
  packages/aws-cdk-lib/aws-servicecatalog/lib/private/association-manager.ts
  packages/aws-cdk-lib/aws-servicecatalog/lib/private/product-stack-synthesizer.ts
  packages/aws-cdk-lib/aws-servicecatalog/lib/private/validation.ts
  packages/aws-cdk-lib/aws-servicecatalog/lib/product-stack-history.ts
  packages/aws-cdk-lib/aws-servicecatalog/lib/product-stack.ts
  packages/aws-cdk-lib/aws-servicecatalog/lib/product.ts
  packages/aws-cdk-lib/aws-servicecatalog/lib/tag-options.ts
Labels: p2, contribution/core, pr-linter/exempt-readme, pr-linter/exempt-test, pr-linter/exempt-integ-test

#34586 fix(elasticloadbalancingv2): fix incorrect max for minimumCapacityUnit
  packages/aws-cdk-lib/aws-elasticloadbalancingv2/lib/alb/application-load-balancer.ts
  packages/aws-cdk-lib/aws-elasticloadbalancingv2/test/alb/load-balancer.test.ts
Labels: bug, p2, effort/small, pr-linter/exempt-integ-test, distinguished-contributor

#34585 docs(autoscaling): fix typos adjustment & interpreted
  packages/aws-cdk-lib/aws-applicationautoscaling/lib/step-scaling-action.ts
  packages/aws-cdk-lib/aws-autoscaling/lib/step-scaling-action.ts
Labels: p2, effort/small, contribution/core

#34580 feat(secretsmanager): throw `ValidationError`s instead of untyped errors
  packages/aws-cdk-lib/.eslintrc.js
  packages/aws-cdk-lib/aws-secretsmanager/lib/rotation-schedule.ts
  packages/aws-cdk-lib/aws-secretsmanager/lib/secret-rotation.ts
  packages/aws-cdk-lib/aws-secretsmanager/lib/secret.ts
Labels: p2, contribution/core, pr-linter/exempt-readme, pr-linter/exempt-test, pr-linter/exempt-integ-test

#33392 feat(custom-resources): throw `ValidationError` instead of untyped Errors
  packages/aws-cdk-lib/.eslintrc.js
  packages/aws-cdk-lib/custom-resources/lib/aws-custom-resource/aws-custom-resource.ts
  packages/aws-cdk-lib/custom-resources/lib/provider-framework/provider.ts
  packages/aws-cdk-lib/custom-resources/lib/provider-framework/util.ts
  packages/aws-cdk-lib/custom-resources/test/provider-framework/provider.test.ts
Labels: p2, contribution/core, pr-linter/exempt-readme, pr-linter/exempt-test, pr-linter/exempt-integ-test

#34576 chore(rds): add MySQL version 5.7.44-rds.20250508
  packages/aws-cdk-lib/aws-rds/lib/instance-engine.ts
Labels: p2, star-contributor, pr/needs-maintainer-review

#34508 chore(rds): add support for 8.0.mysql_aurora.3.09.0
  packages/aws-cdk-lib/aws-rds/lib/cluster-engine.ts
  packages/aws-cdk-lib/aws-rds/test/cluster-engine.test.ts
Labels: p2, beginning-contributor, pr/needs-maintainer-review

#34571 fix(ec2): validate throughput property on EC2 instance block devices
  packages/aws-cdk-lib/aws-ec2/lib/private/ebs-util.ts
  packages/aws-cdk-lib/aws-ec2/test/instance.test.ts
Labels: bug, p1, contribution/core, pr-linter/exempt-integ-test

#34592 revert(ec2): support Firehose `IDeliveryStream` as flow log destination
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.vpc-flow-logs-firehose.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.vpc-flow-logs-firehose.ts
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.vpc-flow-logs-kinesis.js.snapshot/FlowLogsDefaultTestDeployAssert6AFD1854.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.vpc-flow-logs-kinesis.js.snapshot/FlowLogsDefaultTestDeployAssert6AFD1854.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.vpc-flow-logs-kinesis.js.snapshot/FlowLogsTestStack.assets.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.vpc-flow-logs-kinesis.js.snapshot/FlowLogsTestStack.template.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.vpc-flow-logs-kinesis.js.snapshot/asset.44e9c4d7a5d3fd2d677e1a7e416b2b56f6b0104bd5eff9cac5557b4c65a9dc61/index.js
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.vpc-flow-logs-kinesis.js.snapshot/asset.a1acfc2b5f4f6b183fd2bb9863f486bc5edef6a357b355a070d9a0e502df418c/__entrypoint__.js
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.vpc-flow-logs-kinesis.js.snapshot/asset.a1acfc2b5f4f6b183fd2bb9863f486bc5edef6a357b355a070d9a0e502df418c/index.js
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.vpc-flow-logs-kinesis.js.snapshot/cdk.out
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.vpc-flow-logs-kinesis.js.snapshot/integ.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.vpc-flow-logs-kinesis.js.snapshot/manifest.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.vpc-flow-logs-kinesis.js.snapshot/tree.json
  packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.vpc-flow-logs-kinesis.ts
  packages/aws-cdk-lib/aws-ec2/README.md
  packages/aws-cdk-lib/aws-ec2/lib/vpc-flow-logs.ts
  packages/aws-cdk-lib/aws-ec2/test/vpc-flow-logs.test.ts
Labels: p2, contribution/core
